In [1]:
import os
import sys
import time

import numpy as np
import scipy

In [2]:
sys.path.insert(0, '../OptimalNumberOfTopics')

In [3]:
import topnum

from topnum.scores.perplexity_score import PerplexityScore
from topnum.scores.diversity_score import DiversityScore, KNOWN_METRICS
from topnum.model_constructor import init_model_from_family, KnownModel, PARAMS_EXPLORED

from topnum.regularizers import (
    FastFixPhiRegularizer, DecorrelateWithOtherPhiRegularizer, DecorrelateWithOtherPhiRegularizer2
)
from topnum.scores.intratext_coherence_score import (
    IntratextCoherenceScore,
    ComputationMethod,
    WordTopicRelatednessType,
)

In [4]:
import topicnet
from topicnet.cooking_machine.dataset import Dataset
from topicnet.cooking_machine.models import (
    BaseScore as BaseTopicNetScore,
    TopicModel
)
from topicnet.cooking_machine.models.thetaless_regularizer import (
    dataset2sparse_matrix,
)

In [5]:
topicnet.__file__

! ls /home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/dataset_manager/

20NG.csv	 MKB10__internals	    RTL_Wiki.csv
20NG__internals  postnauka.csv		    RTL_Wiki_person.csv
api.py		 postnauka__internals	    RTL_Wiki_person__internals
Brown		 postnauka_noow.csv	    ruwiki_good__internals
Brown_BOW.csv	 postnauka_noow__internals  ruwiki_good.txt
Brown_NOOW.csv	 __pycache__		    WikiRef-220
hf		 Reuters		    wiki_ref220_bow.csv
__init__.py	 Reuters_BOW.csv	    wiki_ref220_natural_order.csv
MKB10.csv	 Reuters_NOOW.csv

In [6]:
! ls /data_mil/shared/CompressaAI/iterative/data/noow

_20_Newsgroups.csv     Post_Science_NOOW_fixed.csv
_Lenta.csv	       Post_Science_NOOW_fixed__internals
MKB_10_NOOW.csv        Post_Science_NOOW__internals
Post_Science_NOOW.csv  WikiRef_220_NOOW.csv

In [7]:
DATA_FOLDER_PATH = '/data_mil/shared/CompressaAI/iterative/data/noow'

In [8]:
! head -n 2 /data_mil/shared/CompressaAI/iterative/data/noow/Post_Science_NOOW.csv

id,raw_text,vw_text
29998.txt,материал отрицательный показатель преломление физик виктор веселаго распространение свет вещество фазовый групповой скорость метаматериалы различаться фазовый групповой скорость каков физика распространение свет вещество находить применение материал отрицательный показатель преломление рассказывать доктор физикоматематический наука виктор веселаго скорость распространяться энергия вещество обычно говорить излучение распространяться вещество со скорость n раз маленький n коэффициент преломление вещество коэффициент преломление n отношение скорость свет скорость распространение излучение вещество обычно уточняться распространяться распространение энергия распространение импульс происходить различный закон энергия распространяться со скорость называться групповой скорость много скорость свет эйнштейн сформулировать самый больший скорость излучение скорость свет кмс импульс распространяться фазовый скорость сколь угодно много скорость свет скорость входить соотношение emc фазовый групповой оказываться здесь величина заменять произведение фазовый скорость групповой post id отрицательный преломление свет притягивать объект излучатель внутри вещество возможный явление чемто новый впервые указывать статья оказываться материал обладать отрицательный преломление описываться отрицательный коэффициент преломление n отношение скорость свет пустота скорость свет вещество излучатель освещать приемник внутри вещество приемник притягиваться излучатель отрицательный скорость положительный скорость излучатель приемник наоборот отрицательный классический школьный опыт брать вода пускать луч свет преломляться внутри вода идти угол идти поверхность вместо вода использовать вещество отрицательный преломление отклоняться налево направо комбинировать вещество отрицательный положительный преломление организовывать прохождение луч свет через набор материальный среда определенный закон както повертываться извиваться обычно привязывать эффект шапкиневидимка иметься эксперимент иметься некий объект сделать невидимый свет проходить вокруг объект наблюдатель кажется объект хотя дело практический применение далеко кроме явление связывать отрицательный преломление наблюдаться область электромагнитный излучение акустика распространение разный род колебание,|@word материал отрицательный показатель преломление физик виктор веселаго распространение свет вещество фазовый групповой скорость метаматериалы различаться фазовый групповой скорость каков физика распространение свет вещество находить применение материал отрицательный показатель преломление рассказывать доктор физикоматематический наука виктор веселаго скорость распространяться энергия вещество обычно говорить излучение распространяться вещество со скорость n раз маленький n коэффициент преломление вещество коэффициент преломление n отношение скорость свет скорость распространение излучение вещество обычно уточняться распространяться распространение энергия распространение импульс происходить различный закон энергия распространяться со скорость называться групповой скорость много скорость свет эйнштейн сформулировать самый больший скорость излучение скорость свет кмс импульс распространяться фазовый скорость сколь угодно много скорость свет скорость входить соотношение emc фазовый групповой оказываться здесь величина заменять произведение фазовый скорость групповой post id отрицательный преломление свет притягивать объект излучатель внутри вещество возможный явление чемто новый впервые указывать статья оказываться материал обладать отрицательный преломление описываться отрицательный коэффициент преломление n отношение скорость свет пустота скорость свет вещество излучатель освещать приемник внутри вещество приемник притягиваться излучатель отрицательный скорость положительный скорость излучатель приемник наоборот отрицательный классический школьный опыт брать вода пускать луч свет преломляться внутри вода идти угол идти поверхность вместо вода использовать вещество отрицательный преломление отклоняться налево направо комбинировать вещество отрицательный положительный преломление организовывать прохождение луч свет через набор материальный среда определенный закон както повертываться извиваться обычно привязывать эффект шапкиневидимка иметься эксперимент иметься некий объект сделать невидимый свет проходить вокруг объект наблюдатель кажется объект хотя дело практический применение далеко кроме явление связывать отрицательный преломление наблюдаться область электромагнитный излучение акустика распространение разный род колебание

In [9]:
dataset = Dataset(
    f'{DATA_FOLDER_PATH}/Post_Science_NOOW.csv',
)

dataset.get_possible_modalities()

set()

In [10]:
dataset._data.head()

,id,raw_text,vw_text
id,,,
29998.txt,29998.txt,материал отрицательный показатель преломление ...,|@word материал отрицательный показатель прело...
7770.txt,7770.txt,культурный код экономика экономист александр а...,|@word культурный код экономика экономист алек...
32230.txt,32230.txt,faq наука третий класс факт эксперимент резуль...,|@word faq наука третий класс факт эксперимент...
27293.txt,27293.txt,обрушение волна поверхность жидкость математик...,|@word обрушение волна поверхность жидкость ма...
481.txt,481.txt,существовать ли суперсимметрия мир элементарны...,|@word существовать ли суперсимметрия мир элем...

In [11]:
dataset._data['vw_text'] = dataset._data['id'] + ' ' + dataset._data['vw_text']

In [16]:
dataset._data.head()

                  id  ...                                            vw_text
id                    ...
29998.txt  29998.txt  ...  29998.txt |@word материал отрицательный показа...
7770.txt    7770.txt  ...  7770.txt |@word культурный код экономика эконо...
32230.txt  32230.txt  ...  32230.txt |@word faq наука третий класс факт э...
27293.txt  27293.txt  ...  27293.txt |@word обрушение волна поверхность ж...
481.txt      481.txt  ...  481.txt |@word существовать ли суперсимметрия ...

[5 rows x 3 columns]

In [18]:
dataset._data.to_csv(f'{DATA_FOLDER_PATH}/Post_Science_NOOW_fixed.csv', index=False)

In [19]:
! head -n 2 /data_mil/shared/CompressaAI/iterative/data/noow/Post_Science_NOOW.csv

id,raw_text,vw_text
29998.txt,материал отрицательный показатель преломление физик виктор веселаго распространение свет вещество фазовый групповой скорость метаматериалы различаться фазовый групповой скорость каков физика распространение свет вещество находить применение материал отрицательный показатель преломление рассказывать доктор физикоматематический наука виктор веселаго скорость распространяться энергия вещество обычно говорить излучение распространяться вещество со скорость n раз маленький n коэффициент преломление вещество коэффициент преломление n отношение скорость свет скорость распространение излучение вещество обычно уточняться распространяться распространение энергия распространение импульс происходить различный закон энергия распространяться со скорость называться групповой скорость много скорость свет эйнштейн сформулировать самый больший скорость излучение скорость свет кмс импульс распространяться фазовый скорость сколь угодно много скорость свет скорость входить соотношение emc фазовый групповой оказываться здесь величина заменять произведение фазовый скорость групповой post id отрицательный преломление свет притягивать объект излучатель внутри вещество возможный явление чемто новый впервые указывать статья оказываться материал обладать отрицательный преломление описываться отрицательный коэффициент преломление n отношение скорость свет пустота скорость свет вещество излучатель освещать приемник внутри вещество приемник притягиваться излучатель отрицательный скорость положительный скорость излучатель приемник наоборот отрицательный классический школьный опыт брать вода пускать луч свет преломляться внутри вода идти угол идти поверхность вместо вода использовать вещество отрицательный преломление отклоняться налево направо комбинировать вещество отрицательный положительный преломление организовывать прохождение луч свет через набор материальный среда определенный закон както повертываться извиваться обычно привязывать эффект шапкиневидимка иметься эксперимент иметься некий объект сделать невидимый свет проходить вокруг объект наблюдатель кажется объект хотя дело практический применение далеко кроме явление связывать отрицательный преломление наблюдаться область электромагнитный излучение акустика распространение разный род колебание,|@word материал отрицательный показатель преломление физик виктор веселаго распространение свет вещество фазовый групповой скорость метаматериалы различаться фазовый групповой скорость каков физика распространение свет вещество находить применение материал отрицательный показатель преломление рассказывать доктор физикоматематический наука виктор веселаго скорость распространяться энергия вещество обычно говорить излучение распространяться вещество со скорость n раз маленький n коэффициент преломление вещество коэффициент преломление n отношение скорость свет скорость распространение излучение вещество обычно уточняться распространяться распространение энергия распространение импульс происходить различный закон энергия распространяться со скорость называться групповой скорость много скорость свет эйнштейн сформулировать самый больший скорость излучение скорость свет кмс импульс распространяться фазовый скорость сколь угодно много скорость свет скорость входить соотношение emc фазовый групповой оказываться здесь величина заменять произведение фазовый скорость групповой post id отрицательный преломление свет притягивать объект излучатель внутри вещество возможный явление чемто новый впервые указывать статья оказываться материал обладать отрицательный преломление описываться отрицательный коэффициент преломление n отношение скорость свет пустота скорость свет вещество излучатель освещать приемник внутри вещество приемник притягиваться излучатель отрицательный скорость положительный скорость излучатель приемник наоборот отрицательный классический школьный опыт брать вода пускать луч свет преломляться внутри вода идти угол идти поверхность вместо вода использовать вещество отрицательный преломление отклоняться налево направо комбинировать вещество отрицательный положительный преломление организовывать прохождение луч свет через набор материальный среда определенный закон както повертываться извиваться обычно привязывать эффект шапкиневидимка иметься эксперимент иметься некий объект сделать невидимый свет проходить вокруг объект наблюдатель кажется объект хотя дело практический применение далеко кроме явление связывать отрицательный преломление наблюдаться область электромагнитный излучение акустика распространение разный род колебание

In [20]:
! head -n 2 /data_mil/shared/CompressaAI/iterative/data/noow/Post_Science_NOOW_fixed.csv

id,raw_text,vw_text
29998.txt,материал отрицательный показатель преломление физик виктор веселаго распространение свет вещество фазовый групповой скорость метаматериалы различаться фазовый групповой скорость каков физика распространение свет вещество находить применение материал отрицательный показатель преломление рассказывать доктор физикоматематический наука виктор веселаго скорость распространяться энергия вещество обычно говорить излучение распространяться вещество со скорость n раз маленький n коэффициент преломление вещество коэффициент преломление n отношение скорость свет скорость распространение излучение вещество обычно уточняться распространяться распространение энергия распространение импульс происходить различный закон энергия распространяться со скорость называться групповой скорость много скорость свет эйнштейн сформулировать самый больший скорость излучение скорость свет кмс импульс распространяться фазовый скорость сколь угодно много скорость свет скорость входить соотношение emc фазовый групповой оказываться здесь величина заменять произведение фазовый скорость групповой post id отрицательный преломление свет притягивать объект излучатель внутри вещество возможный явление чемто новый впервые указывать статья оказываться материал обладать отрицательный преломление описываться отрицательный коэффициент преломление n отношение скорость свет пустота скорость свет вещество излучатель освещать приемник внутри вещество приемник притягиваться излучатель отрицательный скорость положительный скорость излучатель приемник наоборот отрицательный классический школьный опыт брать вода пускать луч свет преломляться внутри вода идти угол идти поверхность вместо вода использовать вещество отрицательный преломление отклоняться налево направо комбинировать вещество отрицательный положительный преломление организовывать прохождение луч свет через набор материальный среда определенный закон както повертываться извиваться обычно привязывать эффект шапкиневидимка иметься эксперимент иметься некий объект сделать невидимый свет проходить вокруг объект наблюдатель кажется объект хотя дело практический применение далеко кроме явление связывать отрицательный преломление наблюдаться область электромагнитный излучение акустика распространение разный род колебание,29998.txt |@word материал отрицательный показатель преломление физик виктор веселаго распространение свет вещество фазовый групповой скорость метаматериалы различаться фазовый групповой скорость каков физика распространение свет вещество находить применение материал отрицательный показатель преломление рассказывать доктор физикоматематический наука виктор веселаго скорость распространяться энергия вещество обычно говорить излучение распространяться вещество со скорость n раз маленький n коэффициент преломление вещество коэффициент преломление n отношение скорость свет скорость распространение излучение вещество обычно уточняться распространяться распространение энергия распространение импульс происходить различный закон энергия распространяться со скорость называться групповой скорость много скорость свет эйнштейн сформулировать самый больший скорость излучение скорость свет кмс импульс распространяться фазовый скорость сколь угодно много скорость свет скорость входить соотношение emc фазовый групповой оказываться здесь величина заменять произведение фазовый скорость групповой post id отрицательный преломление свет притягивать объект излучатель внутри вещество возможный явление чемто новый впервые указывать статья оказываться материал обладать отрицательный преломление описываться отрицательный коэффициент преломление n отношение скорость свет пустота скорость свет вещество излучатель освещать приемник внутри вещество приемник притягиваться излучатель отрицательный скорость положительный скорость излучатель приемник наоборот отрицательный классический школьный опыт брать вода пускать луч свет преломляться внутри вода идти угол идти поверхность вместо вода использовать вещество отрицательный преломление отклоняться налево направо комбинировать вещество отрицательный положительный преломление организовывать прохождение луч свет через набор материальный среда определенный закон както повертываться извиваться обычно привязывать эффект шапкиневидимка иметься эксперимент иметься некий объект сделать невидимый свет проходить вокруг объект наблюдатель кажется объект хотя дело практический применение далеко кроме явление связывать отрицательный преломление наблюдаться область электромагнитный излучение акустика распространение разный род колебание

In [9]:
dataset = Dataset(
    f'{DATA_FOLDER_PATH}/Post_Science_NOOW_fixed.csv',
)

dataset.get_possible_modalities()

{'@word'}

In [10]:
MAIN_MODALITY = '@word'

In [11]:
dataset._data.head()

,id,raw_text,vw_text
id,,,
29998.txt,29998.txt,материал отрицательный показатель преломление ...,29998.txt |@word материал отрицательный показа...
7770.txt,7770.txt,культурный код экономика экономист александр а...,7770.txt |@word культурный код экономика эконо...
32230.txt,32230.txt,faq наука третий класс факт эксперимент резуль...,32230.txt |@word faq наука третий класс факт э...
27293.txt,27293.txt,обрушение волна поверхность жидкость математик...,27293.txt |@word обрушение волна поверхность ж...
481.txt,481.txt,существовать ли суперсимметрия мир элементарны...,481.txt |@word существовать ли суперсимметрия ...

In [12]:
dataset.get_dictionary()

artm.Dictionary(name=84e8ffe7-f675-4064-99d7-f1815cbd1945, num_entries=82162)

In [13]:
dataset._data.shape

(3446, 3)

In [14]:
dictionary = dataset.get_dictionary()

print(dictionary)

for modality in dataset.get_possible_modalities():
    if modality not in [MAIN_MODALITY]:
        dictionary.filter(class_id=modality, max_df=0, inplace=True)

artm.Dictionary(name=84e8ffe7-f675-4064-99d7-f1815cbd1945, num_entries=82162)

In [15]:
dictionary

artm.Dictionary(name=84e8ffe7-f675-4064-99d7-f1815cbd1945, num_entries=82162)

In [16]:
dataset._data.shape

(3446, 3)

In [17]:
dictionary.filter(min_df=5, max_df_rate=0.5)

artm.Dictionary(name=84e8ffe7-f675-4064-99d7-f1815cbd1945, num_entries=19537)

In [18]:
dataset._cached_dict = dictionary

In [19]:
dataset.get_dictionary()

artm.Dictionary(name=84e8ffe7-f675-4064-99d7-f1815cbd1945, num_entries=19537)

In [20]:
def calc_doc_occurrences(dataset, modality):
    """
    :param n_dw_matrix: sparse document-word matrix, shape is D x W
    :return: sparse matrix of co-occurrences

    doc_occurrences[w1, w2] = the number of the documents
    where there are w1 and w2
    """
    n_dw_matrix = dataset2sparse_matrix(dataset, modality, modalities_to_use=[modality])
    matrix = (scipy.sparse.csc_matrix(n_dw_matrix) > 0).astype(int)
    co_occurrences = matrix.T * matrix

    return co_occurrences.diagonal(), co_occurrences


def create_pmi_top_function(
    doc_occurrences, doc_co_occurrences,
    documents_number, top_sizes,
    topic_indices,
    co_occurrences_smooth=1.
):
    """
    :param doc_occurrences: array of doc occurrences of words
    :param doc_co_occurrences: sparse matrix of doc co-occurrences of words
    :param documents_number: number of the documents
    :param top_sizes: list of top values to calculate top-pmi for
    :param co_occurrences_smooth: constant to smooth co-occurrences in log
    :return: function which takes phi and theta and returns
    pair of two arrays: pmi-s of the tops and ppmi-s of the tops

    pmi[i] - pmi(top of size top_sizes[i])
    ppmi[i] - ppmi(top of size top_sizes[i])

    pmi(words) = sum_{u in words, v in words, u != v}
    log(
        (doc_co_occurrences[u, v] * documents_number + co_occurrences_smooth)
        / doc_occurrences[u] / doc_occurrences[v]
    )

    ppmi(words) = sum_{u in words, v in words, u != v}
    max(log(
        (doc_co_occurrences[u, v] * documents_number + co_occurrences_smooth)
        / doc_occurrences[u] / doc_occurrences[v]
    ), 0)

    """
    def func(phi):
        _T, W = phi.shape
        T = len(topic_indices)

        max_top_size = max(top_sizes)
        topic_pmis, topic_ppmis = dict(), dict()
        pmi, ppmi = np.zeros(max_top_size), np.zeros(max_top_size)
        tops = np.argpartition(phi, -max_top_size, axis=1)[:, -max_top_size:]
        
        for t in topic_indices:
            top = sorted(tops[t], key=lambda w: - phi[t, w])
            co_occurrences = doc_co_occurrences[top, :][:, top].todense()
            occurrences = doc_occurrences[top]
            values = np.log(
                (co_occurrences * documents_number + co_occurrences_smooth)
                / (occurrences[:, np.newaxis] * occurrences[np.newaxis, :] + co_occurrences_smooth)
            )
            diag = np.diag_indices(len(values))
            # values.cumsum(axis=0).cumsum(axis=1)[diag] - values[diag].cumsum()

            current_pmi = np.array(
               values.cumsum(axis=0).cumsum(axis=1)[diag] - values[diag].cumsum()
            ).ravel()
            topic_pmis[t] = current_pmi
            pmi += current_pmi

            values[values < 0.] = 0.
            current_ppmi = np.array(
               values.cumsum(axis=0).cumsum(axis=1)[diag] - values[diag].cumsum()
            ).ravel()
            topic_ppmis[t] = current_ppmi
            ppmi += current_ppmi
            
        sizes = np.arange(2, max_top_size + 1)
        pmi[1:] /= (T * sizes * (sizes - 1))  # TODO: sizes * (sizes - 1) ? no need for multiplier 2 ?
        ppmi[1:] /= (T * sizes * (sizes - 1))
        indices = np.array(top_sizes) - 1

        for t in topic_indices:
            topic_pmis[t][1:] /= (sizes * (sizes - 1))
            topic_ppmis[t][1:] /= (sizes * (sizes - 1))

        result_topic_pmis = {t: p[indices] for t, p in topic_pmis.items()}
        result_topic_ppmis = {t: p[indices] for t, p in topic_ppmis.items()}

        return pmi[indices], ppmi[indices], result_topic_pmis, result_topic_ppmis

    return func

In [21]:
%%time

occurences, co_occurences = calc_doc_occurrences(dataset, MAIN_MODALITY)

CPU times: user 6.05 s, sys: 251 ms, total: 6.3 s
Wall time: 6.22 s

In [22]:
calc_pmi = create_pmi_top_function(
    occurences, co_occurences,
    dataset.get_dataset().shape[0], [20],
    topic_indices=[0, 1, 2],
    co_occurrences_smooth=1e-2,
)

In [23]:
class TopTokenCoherence(BaseTopicNetScore):
    def __init__(self, name, func):
        super().__init__()

        self._name = name
        self.calc_pmi = func

    def call(self, model: TopicModel):
        values = self.calc_pmi(model.get_phi_dense()[0].T)

        return values[1]

    def call_by_topic(self, model: TopicModel):
        values = self.calc_pmi(model.get_phi_dense()[0].T)

        return values[3]

In [24]:
KnownModel

In [25]:
PARAMS_EXPLORED

{<KnownModel.LDA: 'LDA'>: {'prior': ['symmetric', 'asymmetric', 'heuristic']},
 <KnownModel.PLSA: 'PLSA'>: {},
 <KnownModel.TLESS: 'TARTM'>: {},
 <KnownModel.SPARSE: 'sparse'>: {'smooth_bcg_tau': [0.05, 0.1],
  'sparse_sp_tau': [-0.05, -0.1]},
 <KnownModel.DECORRELATION: 'decorrelation'>: {'decorrelation_tau': [0.02,
   0.05,
   0.1]},
 <KnownModel.ARTM: 'ARTM'>: {'smooth_bcg_tau': [0.05, 0.1],
  'sparse_sp_tau': [-0.05, -0.1],
  'decorrelation_tau': [0.02, 0.05, 0.1]}}

In [26]:
NUM_TOPICS = 20  # vary
NUM_TRAINS = 3
NUM_ITERATIONS = 20
NUM_TOP_TOKENS = 20

## Test

In [27]:
PARAMS_EXPLORED[KnownModel.PLSA]


model = init_model_from_family(
    family=KnownModel.PLSA,
    dataset=dataset,
    main_modality=MAIN_MODALITY,
    num_topics=NUM_TOPICS,
    seed=1,
)

model._fit(dataset.get_batch_vectorizer(), num_iterations=NUM_ITERATIONS)

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

In [28]:
model.get_phi().shape

(19537, 20)

In [29]:
list(model.scores.keys())

['PerplexityScore@all',
 'SparsityThetaScore',
 'SparsityPhiScore@word',
 'PerplexityScore@word',
 'TopicKernel@word.average_coherence',
 'TopicKernel@word.average_contrast',
 'TopicKernel@word.average_purity',
 'TopicKernel@word.average_size',
 'TopicKernel@word.coherence',
 'TopicKernel@word.contrast',
 'TopicKernel@word.purity',
 'TopicKernel@word.size',
 'TopicKernel@word.tokens']

In [30]:
model.scores['PerplexityScore@word']

[19201.404296875,
 4362.3388671875,
 4016.84814453125,
 3453.7880859375,
 3084.326171875,
 2892.353759765625,
 2776.40869140625,
 2699.38134765625,
 2645.42724609375,
 2606.574951171875,
 2578.23681640625,
 2557.467529296875,
 2542.052490234375,
 2530.478515625,
 2521.54443359375,
 2514.327392578125,
 2508.275146484375,
 2503.078125,
 2498.58056640625,
 2494.68310546875]

In [ ]:
phi = model.get_phi()
target_topic_indices = list(range(NUM_TOPICS))  # phi.columns.get_loc()
target_topic_names = [phi.columns[i] for i in target_topic_indices]

custom_scores = [
    TopTokenCoherence(
        name=f'coherence_{top}',
        func=create_pmi_top_function(
            occurences, co_occurences,
            dataset.get_dataset().shape[0], [top],
            topic_indices=target_topic_indices,
            co_occurrences_smooth=1e-2,
        )
    )
    for top in [20]  # [10, 20, 50, 100]
]
custom_scores = custom_scores + [
    DiversityScore(
        name=f'diversity_{metric}',
        topic_names=['topic_0', 'topic_1'],
        class_ids=MAIN_MODALITY,
    )

    for metric in KNOWN_METRICS
]

for score in custom_scores:    
    res = score.call(model)

    print(score._name)
    print(res)

    if isinstance(score, TopTokenCoherence):
        res_by_topic = score.call_by_topic(model)

        print(res_by_topic)

    print()

In [31]:
for score in custom_scores:
    if isinstance(score, TopTokenCoherence):
        break

toptok = score

In [118]:
toptok

TopTokenCoherence

In [121]:
%%timeit

res = toptok.call(model)

72.8 ms ± 21.1 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [120]:
intra1 = IntratextCoherenceScore(
    name='toplen',
    data=dataset,
    documents=list(dataset._data.index)[:1],
    computation_method=ComputationMethod.SEGMENT_LENGTH,
    word_topic_relatedness=WordTopicRelatednessType.PTW,
)
intra10 = IntratextCoherenceScore(
    name='toplen',
    data=dataset,
    documents=list(dataset._data.index)[:10],
    computation_method=ComputationMethod.SEGMENT_LENGTH,
    word_topic_relatedness=WordTopicRelatednessType.PTW,
)
intra100 = IntratextCoherenceScore(
    name='toplen',
    data=dataset,
    documents=list(dataset._data.index)[:100],
    computation_method=ComputationMethod.SEGMENT_LENGTH,
    word_topic_relatedness=WordTopicRelatednessType.PTW,
)

In [122]:
%%timeit

res = intra1.call(model)

271 ms ± 581 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [123]:
%%timeit

res = intra10.call(model)

2.43 s ± 6.55 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [124]:
%%time

res = intra100.call(model)

CPU times: user 26.4 s, sys: 0 ns, total: 26.4 s
Wall time: 25.3 s

In [103]:
intra_scores = [
    IntratextCoherenceScore(
        name='toplen',
        data=dataset,
        documents=list(dataset._data.index)[:1],
        computation_method=ComputationMethod.SEGMENT_LENGTH,
        word_topic_relatedness=WordTopicRelatednessType.PTW,
    ),
    IntratextCoherenceScore(
        name='toplen2',
        data=dataset,
        computation_method=ComputationMethod.SUM_OVER_WINDOW,
        word_topic_relatedness=WordTopicRelatednessType.PTW,
    ),
]

In [104]:
%%time

intra_scores[0].call(model)

CPU times: user 328 ms, sys: 6.14 ms, total: 334 ms
Wall time: 314 ms

1.3095238095238095

In [70]:
%%time

intra_scores[1].call(model)

KeyboardInterrupt:

In [71]:
_phi = model.get_phi()

In [72]:
_phi.head()

                        topic_0  topic_1  ...      topic_18      topic_19
modality token                            ...
@word    дублирование  0.000000      0.0  ...  0.000000e+00  2.014671e-05
         проучиться    0.000014      0.0  ...  7.175488e-11  7.105283e-09
         гимнастика    0.000000      0.0  ...  6.034839e-06  0.000000e+00
         софист        0.000000      0.0  ...  0.000000e+00  0.000000e+00
         парижанин     0.000000      0.0  ...  0.000000e+00  0.000000e+00

[5 rows x 20 columns]

In [76]:
intra_scores[0]._score._get_relatedness(
    ('@word', 'проучиться'), 'topic_0', _phi
)

1.4186415e-05

In [79]:
words = dataset._data.iloc[0, 2].split()[2:]

In [80]:
words

['материал',
 'отрицательный',
 'показатель',
 'преломление',
 'физик',
 'виктор',
 'веселаго',
 'распространение',
 'свет',
 'вещество',
 'фазовый',
 'групповой',
 'скорость',
 'метаматериалы',
 'различаться',
 'фазовый',
 'групповой',
 'скорость',
 'каков',
 'физика',
 'распространение',
 'свет',
 'вещество',
 'находить',
 'применение',
 'материал',
 'отрицательный',
 'показатель',
 'преломление',
 'рассказывать',
 'доктор',
 'физикоматематический',
 'наука',
 'виктор',
 'веселаго',
 'скорость',
 'распространяться',
 'энергия',
 'вещество',
 'обычно',
 'говорить',
 'излучение',
 'распространяться',
 'вещество',
 'со',
 'скорость',
 'n',
 'раз',
 'маленький',
 'n',
 'коэффициент',
 'преломление',
 'вещество',
 'коэффициент',
 'преломление',
 'n',
 'отношение',
 'скорость',
 'свет',
 'скорость',
 'распространение',
 'излучение',
 'вещество',
 'обычно',
 'уточняться',
 'распространяться',
 'распространение',
 'энергия',
 'распространение',
 'импульс',
 'происходить',
 'различный',
 'закон',
 'энергия',
 'распространяться',
 'со',
 'скорость',
 'называться',
 'групповой',
 'скорость',
 'много',
 'скорость',
 'свет',
 'эйнштейн',
 'сформулировать',
 'самый',
 'больший',
 'скорость',
 'излучение',
 'скорость',
 'свет',
 'кмс',
 'импульс',
 'распространяться',
 'фазовый',
 'скорость',
 'сколь',
 'угодно',
 'много',
 'скорость',
 'свет',
 'скорость',
 'входить',
 'соотношение',
 'emc',
 'фазовый',
 'групповой',
 'оказываться',
 'здесь',
 'величина',
 'заменять',
 'произведение',
 'фазовый',
 'скорость',
 'групповой',
 'post',
 'id',
 'отрицательный',
 'преломление',
 'свет',
 'притягивать',
 'объект',
 'излучатель',
 'внутри',
 'вещество',
 'возможный',
 'явление',
 'чемто',
 'новый',
 'впервые',
 'указывать',
 'статья',
 'оказываться',
 'материал',
 'обладать',
 'отрицательный',
 'преломление',
 'описываться',
 'отрицательный',
 'коэффициент',
 'преломление',
 'n',
 'отношение',
 'скорость',
 'свет',
 'пустота',
 'скорость',
 'свет',
 'вещество',
 'излучатель',
 'освещать',
 'приемник',
 'внутри',
 'вещество',
 'приемник',
 'притягиваться',
 'излучатель',
 'отрицательный',
 'скорость',
 'положительный',
 'скорость',
 'излучатель',
 'приемник',
 'наоборот',
 'отрицательный',
 'классический',
 'школьный',
 'опыт',
 'брать',
 'вода',
 'пускать',
 'луч',
 'свет',
 'преломляться',
 'внутри',
 'вода',
 'идти',
 'угол',
 'идти',
 'поверхность',
 'вместо',
 'вода',
 'использовать',
 'вещество',
 'отрицательный',
 'преломление',
 'отклоняться',
 'налево',
 'направо',
 'комбинировать',
 'вещество',
 'отрицательный',
 'положительный',
 'преломление',
 'организовывать',
 'прохождение',
 'луч',
 'свет',
 'через',
 'набор',
 'материальный',
 'среда',
 'определенный',
 'закон',
 'както',
 'повертываться',
 'извиваться',
 'обычно',
 'привязывать',
 'эффект',
 'шапкиневидимка',
 'иметься',
 'эксперимент',
 'иметься',
 'некий',
 'объект',
 'сделать',
 'невидимый',
 'свет',
 'проходить',
 'вокруг',
 'объект',
 'наблюдатель',
 'кажется',
 'объект',
 'хотя',
 'дело',
 'практический',
 'применение',
 'далеко',
 'кроме',
 'явление',
 'связывать',
 'отрицательный',
 'преломление',
 'наблюдаться',
 'область',
 'электромагнитный',
 'излучение',
 'акустика',
 'распространение',
 'разный',
 'род',
 'колебание']

In [109]:
def _get_relatedness(
        word,
        topic: str,
        word_topic_relatednesses) -> float:

    try:
        return 0  # word_topic_relatednesses.loc[word, topic]
    except KeyError as error:
        # print(
        #     f'Some word not found in Word-Topic relatedness matrix: "{error}"!'
        #     f' Returning mean value over all word relatednesses for topic "{topic}".'
        # )

        return 0  # float(np.mean(word_topic_relatednesses.values))

In [110]:
%%time

for i in range(1):
    for t in _phi.columns:
        for w in words:
            _get_relatedness(
                ('@word', w), t, _phi
            )

CPU times: user 2.18 ms, sys: 0 ns, total: 2.18 ms
Wall time: 2 ms

In [112]:
_phi.index[0]

('@word', 'дублирование')

In [113]:
_phi.to_dict()

{'topic_0': {('@word', 'дублирование'): 0.0,
  ('@word', 'проучиться'): 1.4186414773575962e-05,
  ('@word', 'гимнастика'): 0.0,
  ('@word', 'софист'): 0.0,
  ('@word', 'парижанин'): 0.0,
  ('@word', 'жадный'): 0.0,
  ('@word', 'антиd'): 8.654332486912608e-05,
  ('@word', 'volk'): 0.0,
  ('@word', 'огонек'): 0.0,
  ('@word', 'несторианский'): 0.0,
  ('@word', 'грайндхаус'): 0.0,
  ('@word', 'будить'): 0.0,
  ('@word', 'кихот'): 0.0,
  ('@word', 'алетейя'): 0.0,
  ('@word', 'халат'): 0.0,
  ('@word', 'винительный'): 0.0,
  ('@word', 'истерический'): 0.0,
  ('@word', 'якобинский'): 0.0,
  ('@word', 'шестеро'): 0.0,
  ('@word', 'уйгур'): 0.0,
  ('@word', 'фарси'): 0.0,
  ('@word', 'биосовместимый'): 0.0,
  ('@word', 'впрыскивать'): 1.5044696738186758e-05,
  ('@word', 'зарастать'): 0.0,
  ('@word', 'канава'): 0.0,
  ('@word', 'желудочек'): 0.0,
  ('@word', 'поручаться'): 0.0,
  ('@word', 'ja'): 0.0,
  ('@word', 'портовый'): 0.0,
  ('@word', 'придумывание'): 0.0,
  ('@word', 'таксист'): 0.0,
  ('@word', 'бернар'): 0.0,
  ('@word', 'фармацевт'): 0.0,
  ('@word', 'сасанидский'): 0.0,
  ('@word', 'аммоний'): 0.0,
  ('@word', 'чтко'): 3.089764645105111e-15,
  ('@word', 'торндайк'): 0.0,
  ('@word', 'слабоумие'): 0.0,
  ('@word', 'непрофессиональный'): 0.0,
  ('@word', 'препарировать'): 0.0,
  ('@word', 'разбухать'): 0.0,
  ('@word', 'прогностический'): 0.0,
  ('@word', 'циклически'): 0.0,
  ('@word', 'аплодисменты'): 0.0,
  ('@word', 'варшавский'): 0.0,
  ('@word', 'норвежец'): 0.0,
  ('@word', 'урбанизированный'): 0.0,
  ('@word', 'idизвестно'): 0.0,
  ('@word', 'opus'): 0.0,
  ('@word', 'down'): 5.773420343757607e-05,
  ('@word', 'одесса'): 0.0,
  ('@word', 'порнографический'): 0.0,
  ('@word', 'radiation'): 9.079327355721034e-06,
  ('@word', 'опьянение'): 0.0,
  ('@word', 'лоток'): 0.0,
  ('@word', 'покупаться'): 0.0,
  ('@word', 'двухуровневый'): 0.0,
  ('@word', 'рукопожатие'): 0.0,
  ('@word', 'сирота'): 0.0,
  ('@word', 'выжимать'): 1.3966676306154113e-05,
  ('@word', 'томографический'): 0.0,
  ('@word', 'афроамериканский'): 0.0,
  ('@word', 'несовершеннолетний'): 0.0,
  ('@word', 'expert'): 0.0,
  ('@word', 'осаждение'): 0.0,
  ('@word', 'подкручивать'): 0.0,
  ('@word', 'поставляться'): 0.0,
  ('@word', 'кафедральный'): 0.0,
  ('@word', 'нейрохимический'): 0.0,
  ('@word', 'впредь'): 0.0,
  ('@word', 'idпримерно'): 0.0,
  ('@word', 'репутационный'): 0.0,
  ('@word', 'европеоидный'): 0.0,
  ('@word', 'повзрослеть'): 0.0,
  ('@word', 'отскакивать'): 9.027241438088265e-14,
  ('@word', 'франс'): 0.0,
  ('@word', 'шажок'): 0.0,
  ('@word', 'яск'): 0.0,
  ('@word', 'пропускной'): 0.0,
  ('@word', 'угодный'): 2.6329507463174195e-09,
  ('@word', 'цинк'): 2.4517858037143014e-05,
  ('@word', 'пред'): 0.0,
  ('@word', 'авиценный'): 0.0,
  ('@word', 'namedrobyshevsky'): 0.0,
  ('@word', 'умеренность'): 0.0,
  ('@word', 'разумность'): 0.0,
  ('@word', 'сюзерен'): 0.0,
  ('@word', 'обаяние'): 0.0,
  ('@word', 'paradigm'): 0.0,
  ('@word', 'намагничивать'): 0.0,
  ('@word', 'излучающий'): 0.0,
  ('@word', 'деликатно'): 0.0,
  ('@word', 'михайловна'): 0.0,
  ('@word', 'локация'): 0.0,
  ('@word', 'пространственность'): 0.0,
  ('@word', 'сокрушать'): 0.0,
  ('@word', 'заглушать'): 0.0,
  ('@word', 'пугающий'): 0.0,
  ('@word', 'эрнест'): 0.0001990600721910596,
  ('@word', 'устремлять'): 1.4700340216222685e-05,
  ('@word', 'омар'): 0.0,
  ('@word', 'вицепрезидент'): 0.0,
  ('@word', 'idсогласно'): 2.8629307258221104e-10,
  ('@word', 'брукхейвен'): 1.466259709559381e-05,
  ('@word', 'march'): 0.0,
  ('@word', 'порочность'): 0.0,
  ('@word', 'попечитель'): 0.0,
  ('@word', 'великолепие'): 0.0,
  ('@word', 'стандартизировать'): 0.0,
  ('@word', 'абсолют'): 0.0,
  ('@word', 'жемчужина'): 0.0,
  ('@word', 'персонификация'): 0.0,
  ('@word', 'ларс'): 0.0,
  ('@word', 'коварство'): 0.0,
  ('@word', 'nd'): 0.0,
  ('@word', 'главенство'): 0.0,
  ('@word', 'маскировка'): 0.0,
  ('@word', 'укрупнение'): 0.0,
  ('@word', 'иконический'): 0.0,
  ('@word', 'преднамеренно'): 0.0,
  ('@word', 'truth'): 4.4359927414916456e-05,
  ('@word', 'конструктивист'): 0.0,
  ('@word', 'gaia'): 0.0,
  ('@word', 'тудасюда'): 1.3959340321889613e-05,
  ('@word', 'into'): 2.441227948957181e-11,
  ('@word', 'командующий'): 0.0,
  ('@word', 'курорт'): 0.0,
  ('@word', 'мадагаскар'): 0.0,
  ('@word', 'among'): 2.014342499023769e-06,
  ('@word', 'children'): 4.1280780876951084e-14,
  ('@word', 'рамочный'): 0.0,
  ('@word', 'english'): 0.0,
  ('@word', 'french'): 6.225318038843852e-10,
  ('@word', 'over'): 1.9181043171556666e-05,
  ('@word', 'диафрагма'): 0.0,
  ('@word', 'осанка'): 0.0,
  ('@word', 'взрослеть'): 0.0,
  ('@word', 'дельфин'): 0.0,
  ('@word', 'передаваемый'): 0.0,
  ('@word', 'эддингтон'): 0.0,
  ('@word', 'увольнять'): 0.0,
  ('@word', 'гонорар'): 0.0,
  ('@word', 'жданов'): 0.0,
  ('@word', 'разъединяться'): 5.870705939610421e-13,
  ('@word', 'дистанционный'): 0.0,
  ('@word', 'патронаж'): 0.0,
  ('@word', 'перепадать'): 0.0,
  ('@word', 'наводиться'): 8.724156130077555e-16,
  ('@word', 'индексация'): 0.0,
  ('@word', 'разливаться'): 0.0,
  ('@word', 'сейм'): 0.0,
  ('@word', 'столбовой'): 1.6356081687263213e-05,
  ('@word', 'правша'): 1.4561815987690352e-05,
  ('@word', 'тщательность'): 1.486270411987789e-05,
  ('@word', 'idодной'): 0.0,
  ('@word', 'рефлексировать'): 0.0,
  ('@word', 'исхак'): 0.0,
  ('@word', 'сборы'): 0.0,
  ('@word', 'плясать'): 0.0,
  ('@word', 'узко'): 0.0,
  ('@word', 'трасса'): 1.5472842278541066e-05,
  ('@word', 'reason'): 0.0,
  ('@word', 'like'): 7.066617472628112e-16,
  ('@word', 'летательный'): 2.863004278097492e-09,
  ('@word', 'налетать'): 2.9039429136901163e-05,
  ('@word', 'суета'): 1.3438495443551801e-05,
  ('@word', 'reality'): 0.0,
  ('@word', 'рискованно'): 0.0,
  ('@word', 'одалживать'): 3.319155659955303e-13,
  ('@word', 'отключение'): 0.0,
  ('@word', 'нарост'): 0.0,
  ('@word', 'игнатий'): 0.0,
  ('@word', 'прогрессировать'): 0.0,
  ('@word', 'томпсон'): 1.3685993508261163e-05,
  ('@word', 'композиционный'): 4.7134271596860344e-08,
  ('@word', 'стационар'): 0.0,
  ('@word', 'отпугивать'): 0.0,
  ('@word', 'аксион'): 0.00012056297418894246,
  ('@word', 'натяжение'): 2.0126515471591278e-12,
  ('@word', 'cosmic'): 1.745593544910662e-05,
  ('@word', 'wmap'): 2.137013473352354e-14,
  ('@word', 'пунктирный'): 5.7733610447030514e-05,
  ('@word', 'sn'): 9.135183251128207e-14,
  ('@word', 'мпк'): 0.0,
  ('@word', 'регресс'): 0.0,
  ('@word', 'легковесный'): 0.0,
  ('@word', 'грамматик'): 0.0,
  ('@word', 'тьерри'): 0.0,
  ('@word', 'звзд'): 0.0,
  ('@word', 'замахиваться'): 0.0,
  ('@word', 'правоотношение'): 0.0,
  ('@word', 'подтягивать'): 0.0,
  ('@word', 'постареть'): 0.0,
  ('@word', 'спрягаться'): 0.0,
  ('@word', 'пинкер'): 0.0,
  ('@word', 'запястье'): 0.0,
  ('@word', 'гусеница'): 0.0,
  ('@word', 'костромской'): 0.0,
  ('@word', 'какао'): 0.0,
  ('@word', 'черновцы'): 0.0,
  ('@word', 'базальный'): 0.0,
  ('@word', 'статут'): 0.0,
  ('@word', 'зерцало'): 0.0,
  ('@word', 'оптически'): 0.0,
  ('@word', 'голография'): 0.0,
  ('@word', 'еврипид'): 0.0,
  ('@word', 'одиссей'): 0.0,
  ('@word', 'еж'): 0.0,
  ('@word', 'феликс'): 1.3423247973223806e-12,
  ('@word', 'неотложный'): 0.0,
  ('@word', 'мультидисциплинарный'): 0.0,
  ('@word', 'гсм'): 3.2084443371690422e-15,
  ('@word', 'долл'): 0.0,
  ('@word', 'тмное'): 0.0,
  ('@word', 'самурай'): 0.0,
  ('@word', 'гавань'): 0.0,
  ('@word', 'абстрагироваться'): 3.0499282729579136e-05,
  ('@word', 'дробь'): 1.0963105978589738e-06,
  ('@word', 'пресечение'): 0.0,
  ('@word', 'kepler'): 0.0,
  ('@word', 'рапс'): 0.0,
  ('@word', 'ткач'): 0.0,
  ('@word', 'поликлиника'): 0.0,
  ('@word', 'хусейн'): 0.0,
  ('@word', 'канарский'): 0.0,
  ('@word', 'факультативный'): 0.0,
  ('@word', 'падальщик'): 0.0,
  ('@word', 'люся'): 0.0,
  ('@word', 'благоволить'): 0.0,
  ('@word', 'побоище'): 0.0,
  ('@word', 'стенли'): 0.0,
  ('@word', 'лоуренс'): 0.0003334775974508375,
  ('@word', 'институционально'): 0.0,
  ('@word', 'сентенция'): 0.0,
  ('@word', 'вывоз'): 0.0,
  ('@word', 'бросок'): 0.0,
  ('@word', 'баварский'): 0.0,
  ('@word', 'буржуа'): 0.0,
  ('@word', 'сорокалетний'): 0.0,
  ('@word', 'звучащий'): 0.0,
  ('@word', 'зорина'): 0.0,
  ('@word', 'налаживание'): 0.0,
  ('@word', 'врачевание'): 0.0,
  ('@word', 'сюняев'): 3.655460469368342e-15,
  ('@word', 'междоусобица'): 0.0,
  ('@word', 'виновник'): 0.0,
  ('@word', 'сворачивание'): 0.0,
  ('@word', 'аттракцион'): 0.0,
  ('@word', 'доходный'): 0.0,
  ('@word', 'независящий'): 0.0,
  ('@word', 'rise'): 5.177070667574204e-16,
  ('@word', 'univ'): 0.0,
  ('@word', 'серийный'): 0.0,
  ('@word', 'мур'): 0.0,
  ('@word', 'токвиль'): 0.0,
  ('@word', 'маломальский'): 0.0,
  ('@word', 'еи'): 0.0,
  ('@word', 'картографировать'): 0.0,
  ('@word', 'theories'): 0.0,
  ('@word', 'еп'): 0.0,
  ('@word', 'работорговля'): 0.0,
  ('@word', 'деструкция'): 0.0,
  ('@word', 'разгрузка'): 0.0,
  ('@word', 'секретировать'): 0.0,
  ('@word', 'погасить'): 3.1756965768181544e-07,
  ('@word', 'скольким'): 3.273099719081074e-05,
  ('@word', 'планетология'): 0.0,
  ('@word', 'idбыли'): 0.0,
  ('@word', 'эдикт'): 0.0,
  ('@word', 'нивелироваться'): 0.0,
  ('@word', 'обездоливать'): 0.0,
  ('@word', 'шов'): 0.0,
  ('@word', 'idтогда'): 0.0,
  ('@word', 'натолкнуться'): 4.625438305083662e-05,
  ('@word', 'будда'): 0.0,
  ('@word', 'мэр'): 0.0,
  ('@word', 'беззащитный'): 0.0,
  ('@word', 'невзирая'): 0.0,
  ('@word', 'драйв'): 0.0,
  ('@word', 'клубень'): 0.0,
  ('@word', 'блокнот'): 0.0,
  ('@word', 'балканский'): 0.0,
  ('@word', 'детектироваться'): 5.7765257224673405e-05,
  ('@word', 'синус'): 1.4541215023200493e-05,
  ('@word', 'ипотека'): 0.0,
  ('@word', 'зиждиться'): 0.0,
  ('@word', 'срединный'): 0.0,
  ('@word', 'поляризационный'): 0.0,
  ('@word', 'стриптиз'): 0.0,
  ('@word', 'classics'): 0.0,
  ('@word', 'ea'): 0.0,
  ('@word', 'кристаллограф'): 1.1330683502455523e-14,
  ('@word', 'нэш'): 1.91051965846528e-15,
  ('@word', 'выпуклость'): 1.6520589269930497e-05,
  ('@word', 'кобальт'): 2.237776425317861e-05,
  ('@word', 'закручиваться'): 3.553958076079136e-16,
  ('@word', 'продувать'): 0.0,
  ('@word', 'приют'): 0.0,
  ('@word', 'сосчитывать'): 2.0263801284192175e-14,
  ('@word', 'survey'): 0.0,
  ('@word', 'structures'): 0.0,
  ('@word', 'тельце'): 0.0,
  ('@word', 'копаться'): 1.0734433320430477e-16,
  ('@word', 'ронять'): 0.0,
  ('@word', 'гностический'): 0.0,
  ('@word', 'посмертно'): 0.0,
  ('@word', 'филогенез'): 0.0,
  ('@word', 'деннет'): 0.0,
  ('@word', 'томск'): 0.0,
  ('@word', 'создатся'): 1.087745778866056e-11,
  ('@word', 'кровопролитие'): 0.0,
  ('@word', 'северянин'): 0.0,
  ('@word', 'госбезопасность'): 0.0,
  ('@word', 'первичность'): 0.0,
  ('@word', 'стыд'): 0.0,
  ('@word', 'неподконтрольный'): 0.0,
  ('@word', 'окунать'): 1.462310228816932e-05,
  ('@word', 'lhcb'): 0.00021635832672473043,
  ('@word', 'бг'): 0.0,
  ('@word', 'уноситься'): 3.070003731409088e-05,
  ('@word', 'оправдательный'): 0.0,
  ('@word', 'томат'): 0.0,
  ('@word', 'зондировать'): 1.2321815120230895e-05,
  ('@word', 'сельва'): 0.0,
  ('@word', 'зачеркнуть'): 0.0,
  ('@word', 'одолевать'): 0.0,
  ('@word', 'dкварки'): 0.00010096721962327138,
  ('@word', 'стоун'): 0.0,
  ('@word', 'расшатывать'): 8.898919823252527e-09,
  ('@word', 'дотеоретический'): 0.0,
  ('@word', 'дубина'): 0.0,
  ('@word', 'объм'): 0.0,
  ('@word', 'пазл'): 1.0054557013361443e-12,
  ('@word', 'лапинакратасюк'): 0.0,
  ('@word', 'пользовательский'): 0.0,
  ('@word', 'кабинетный'): 0.0,
  ('@word', 'ослабнуть'): 0.0,
  ('@word', 'экстатический'): 0.0,
  ('@word', 'норман'): 0.0,
  ('@word', 'облекать'): 0.0,
  ('@word', 'нагой'): 0.0,
  ('@word', 'барабанный'): 1.896412804569536e-09,
  ('@word', 'неутилитарный'): 0.0,
  ('@word', 'jan'): 0.0,
  ('@word', 'ральф'): 1.161705824870296e-07,
  ('@word', 'charles'): 0.0,
  ('@word', 'тартуский'): 0.0,
  ('@word', 'беликов'): 0.0,
  ('@word', 'однородно'): 0.0,
  ('@word', 'предсказуемость'): 7.681979814907428e-15,
  ('@word', 'выборщик'): 0.0,
  ('@word', 'риторически'): 0.0,
  ('@word', 'idтретий'): 0.0,
  ('@word', 'адресный'): 0.0,
  ('@word', 'contemporary'): 0.0,
  ('@word', 'methodology'): 0.0,
  ('@word', 'методолог'): 0.0,
  ('@word', 'научность'): 0.0,
  ('@word', 'внимать'): 1.3571827366831712e-05,
  ('@word', 'фом'): 0.0,
  ('@word', 'шрам'): 0.0,
  ('@word', 'erectus'): 0.0,
  ('@word', 'ари'): 0.0,
  ('@word', 'ускоренно'): 1.0347294846724253e-05,
  ('@word', 'посредство'): 0.0,
  ('@word', 'сопроводительный'): 0.0,
  ('@word', 'сет'): 0.0,
  ('@word', 'гардероб'): 0.0,
  ('@word', 'трусы'): 0.0,
  ('@word', 'гост'): 0.0,
  ('@word', 'фольга'): 6.854776438558474e-05,
  ('@word', 'предрасположенный'): 0.0,
  ('@word', 'simmel'): 0.0,
  ('@word', 'изгнанник'): 0.0,
  ('@word', 'долговой'): 0.0,
  ('@word', 'запрашивать'): 0.0,
  ('@word', 'заемный'): 0.0,
  ('@word', 'триллион'): 4.6098994062049314e-05,
  ('@word', 'платеж'): 0.0,
  ('@word', 'вдумчивый'): 0.0,
  ('@word', 'мэйдзи'): 0.0,
  ('@word', 'макмиллан'): 3.03341839753557e-05,
  ('@word', 'анархия'): 0.0,
  ('@word', 'натуралист'): 0.0,
  ('@word', 'статься'): 0.0,
  ('@word', 'рекомбинантный'): 0.0,
  ('@word', 'полярность'): 1.7751328414306045e-05,
  ('@word', 'амстердам'): 0.0,
  ('@word', 'неравномерность'): 7.325793617563026e-13,
  ('@word', 'фихта'): 0.0,
  ('@word', 'переламывать'): 0.0,
  ('@word', 'троллейбус'): 0.0,
  ('@word', 'воспитанник'): 0.0,
  ('@word', 'устрашающий'): 0.0,
  ('@word', 'загробный'): 0.0,
  ('@word', 'франциск'): 0.0,
  ('@word', 'коррелят'): 0.0,
  ('@word', 'откладывание'): 0.0,
  ('@word', 'акула'): 0.0,
  ('@word', 'грабитель'): 0.0,
  ('@word', 'артхаус'): 0.0,
  ('@word', 'ссылать'): 0.0,
  ('@word', 'наполняться'): 1.4578798982256558e-05,
  ('@word', 'обуздывать'): 1.3913935617893003e-05,
  ('@word', 'изготовитель'): 1.3174669688531537e-12,
  ('@word', 'жестовый'): 0.0,
  ('@word', 'europe'): 0.0,
  ('@word', 'легально'): 0.0,
  ('@word', 'publications'): 2.929490619862918e-06,
  ('@word', 'sage'): 1.3811939425067976e-05,
  ('@word', 'юра'): 0.0,
  ('@word', 'фюра'): 0.0,
  ('@word', 'свирепый'): 0.0,
  ('@word', 'авангардистский'): 0.0,
  ('@word', 'равновесный'): 4.490761651432251e-10,
  ('@word', 'подростковый'): 0.0,
  ('@word', 'выскочить'): 5.399454403315492e-16,
  ('@word', 'отгораживать'): 0.0,
  ('@word', 'удлинение'): 0.0,
  ('@word', 'скромно'): 3.2415300665888935e-05,
  ('@word', 'цюрих'): 0.0,
  ('@word', 'ремарка'): 0.0,
  ('@word', 'мексиканец'): 0.0,
  ('@word', 'кругосветный'): 0.0,
  ('@word', 'предвзятость'): 0.0,
  ('@word', 'гавриил'): 0.0,
  ('@word', 'этноним'): 0.0,
  ('@word', 'диктаторский'): 0.0,
  ('@word', 'дикость'): 0.0,
  ('@word', 'задокументировать'): 0.0,
  ('@word', 'бессильный'): 0.0,
  ('@word', 'запутанность'): 0.0,
  ('@word', 'реализованный'): 9.895026778394822e-06,
  ('@word', 'постыдный'): 0.0,
  ('@word', 'выполнимый'): 0.0,
  ('@word', 'недооцениваться'): 1.2472320065626263e-07,
  ('@word', 'поитальянски'): 0.0,
  ('@word', 'стыдно'): 0.0,
  ('@word', 'средиземноморский'): 1.2028915080009028e-05,
  ('@word', 'усердие'): 0.0,
  ('@word', 'платонический'): 1.2732361938105896e-05,
  ('@word', 'утонченный'): 0.0,
  ('@word', 'полочка'): 0.0,
  ('@word', 'классифицироваться'): 3.0409108148887753e-05,
  ('@word', 'плантация'): 0.0,
  ('@word', 'хвалить'): 0.0,
  ('@word', 'холст'): 0.0,
  ('@word', 'анатом'): 0.0,
  ('@word', 'позвонок'): 0.0,
  ('@word', 'беспомощный'): 0.0,
  ('@word', 'ахилл'): 0.0,
  ('@word', 'периметр'): 8.613983663963154e-05,
  ('@word', 'водохранилище'): 0.0,
  ('@word', 'раздутый'): 0.0,
  ('@word', 'гортань'): 0.0,
  ('@word', 'теплоемкость'): 2.4028852570342173e-14,
  ('@word', 'фантомный'): 2.77538347859263e-08,
  ('@word', 'продлиться'): 0.0,
  ('@word', 'выборность'): 0.0,
  ('@word', 'неразрешенный'): 0.0,
  ('@word', 'фурор'): 1.0764992196266032e-11,
  ('@word', 'гектар'): 0.0,
  ('@word', 'топоним'): 0.0,
  ('@word', 'внутренность'): 1.58297989401035e-05,
  ('@word', 'пафосный'): 0.0,
  ('@word', 'перекрытие'): 0.0,
  ('@word', 'творчески'): 0.0,
  ('@word', 'символьный'): 0.0,
  ('@word', 'прощупывать'): 0.0,
  ('@word', 'шелк'): 0.0,
  ('@word', 'реплицировать'): 0.0,
  ('@word', 'красить'): 0.0,
  ('@word', 'подражательный'): 0.0,
  ('@word', 'medieval'): 0.0,
  ('@word', 'вторично'): 1.6723603364220303e-14,
  ('@word', 'problems'): 0.0,
  ('@word', 'дискутироваться'): 0.0,
  ('@word', 'прикрепление'): 0.0,
  ('@word', 'инородный'): 0.0,
  ('@word', 'осадконакопление'): 0.0,
  ('@word', 'окислитель'): 0.0,
  ('@word', 'нарезка'): 1.2382452008186107e-10,
  ('@word', 'раздражитель'): 0.0,
  ('@word', 'мф'): 0.0,
  ('@word', 'кордаит'): 0.0,
  ('@word', 'войновскиевый'): 0.0,
  ('@word', 'палеоботаник'): 0.0,
  ('@word', 'мех'): 0.0,
  ('@word', 'гусь'): 0.0,
  ('@word', 'консул'): 0.0,
  ('@word', 'design'): 0.0,
  ('@word', 'марксизмаленинизм'): 0.0,
  ('@word', 'овчинников'): 1.7857667401695353e-16,
  ('@word', 'неразрушающий'): 0.0,
  ('@word', 'убито'): 0.0,
  ('@word', 'левченко'): 0.0,
  ('@word', 'удовлетворяться'): 0.0,
  ('@word', 'окраинный'): 0.0,
  ('@word', 'theoretical'): 0.0,
  ('@word', 'купляпродажа'): 0.0,
  ('@word', 'греметь'): 0.0,
  ('@word', 'регулятивный'): 0.0,
  ('@word', 'донаучный'): 0.0,
  ('@word', 'продуктовый'): 0.0,
  ('@word', 'сверхчеловек'): 0.0,
  ('@word', 'самосовершенствование'): 0.0,
  ('@word', 'динамо'): 8.040159627853427e-06,
  ('@word', 'фотографировать'): 5.71588791295957e-16,
  ('@word', 'нанообъект'): 0.0,
  ('@word', 'чен'): 1.4744185136805754e-05,
  ('@word', 'колмогоровский'): 6.4384490509774954e-15,
  ('@word', 'дедыш'): 0.0,
  ('@word', 'горбачев'): 0.0,
  ('@word', 'нормальность'): 0.0,
  ('@word', 'шестидесятый'): 0.0,
  ('@word', 'младенческий'): 9.308535192653622e-11,
  ('@word', 'ясперс'): 0.0,
  ('@word', 'панический'): 0.0,
  ('@word', 'паралич'): 0.0,
  ('@word', 'сартр'): 0.0,
  ('@word', 'комический'): 0.0,
  ('@word', 'говорение'): 0.0,
  ('@word', 'армен'): 6.530557344897048e-11,
  ('@word', 'магнон'): 0.0,
  ('@word', 'тора'): 3.029049376385482e-16,
  ('@word', 'противозаконный'): 0.0,
  ('@word', 'апостольский'): 0.0,
  ('@word', 'тревожность'): 0.0,
  ('@word', 'новозаветный'): 0.0,
  ('@word', 'индивидуалист'): 1.4549426850862801e-05,
  ('@word', 'апокриф'): 0.0,
  ('@word', 'неизменность'): 5.842194514116272e-05,
  ('@word', 'загон'): 0.0,
  ('@word', 'инопланетянин'): 0.0,
  ('@word', 'speech'): 0.0,
  ('@word', 'передняя'): 0.0,
  ('@word', 'жар'): 0.0,
  ('@word', 'спорадически'): 0.0,
  ('@word', 'владимирский'): 0.0,
  ('@word', 'сейф'): 0.0,
  ('@word', 'двухмерный'): 1.1124414039140156e-14,
  ('@word', 'пролезать'): 0.0,
  ('@word', 'робототехнический'): 0.0,
  ('@word', 'инфляционный'): 3.224242433371577e-13,
  ('@word', 'остывать'): 2.24509699719988e-09,
  ('@word', 'легенда'): 3.42625867233437e-07,
  ('@word', 'кольский'): 0.0,
  ('@word', 'разыгрывать'): 0.0,
  ('@word', 'напоследок'): 0.0,
  ('@word', 'группироваться'): 8.891720790416002e-05,
  ('@word', 'насильно'): 0.0,
  ('@word', 'роджер'): 1.6417710332571858e-15,
  ('@word', 'ниша'): 0.0,
  ('@word', 'резидент'): 0.0,
  ('@word', 'естественно'): 0.0003584956575650722,
  ('@word', 'посланник'): 0.0,
  ('@word', 'изолировать'): 6.510065819753663e-10,
  ('@word', 'оазис'): 0.0,
  ('@word', 'высота'): 6.189365376485512e-05,
  ('@word', 'полететь'): 2.709948967094533e-05,
  ('@word', 'иск'): 0.0,
  ('@word', 'компаньон'): 7.867381225656889e-12,
  ('@word', 'женатый'): 0.0,
  ('@word', 'цветок'): 3.154324872411962e-07,
  ('@word', 'ancient'): 0.0,
  ('@word', 'гомологичный'): 0.0,
  ('@word', 'коробка'): 0.0,
  ('@word', 'элитный'): 0.0,
  ('@word', 'речка'): 0.0,
  ('@word', 'обучаемость'): 0.0,
  ('@word', 'принижать'): 0.0,
  ('@word', 'ручеек'): 0.0,
  ('@word', 'казино'): 0.0,
  ('@word', 'фараон'): 0.0,
  ('@word', 'материнский'): 0.0,
  ('@word', 'случайно'): 5.36402865236596e-07,
  ('@word', 'катерина'): 0.0,

In [125]:
np.mean(_phi)

5.1185107e-05

In [32]:
# With _word_topic_relatednesses_fast:

In [33]:
intra1 = IntratextCoherenceScore(
    name='toplen',
    data=dataset,
    documents=list(dataset._data.index)[:1],
    computation_method=ComputationMethod.SEGMENT_LENGTH,
    word_topic_relatedness=WordTopicRelatednessType.PTW,
)
intra10 = IntratextCoherenceScore(
    name='toplen',
    data=dataset,
    documents=list(dataset._data.index)[:10],
    computation_method=ComputationMethod.SEGMENT_LENGTH,
    word_topic_relatedness=WordTopicRelatednessType.PTW,
)
intra100 = IntratextCoherenceScore(
    name='toplen',
    data=dataset,
    documents=list(dataset._data.index)[:100],
    computation_method=ComputationMethod.SEGMENT_LENGTH,
    word_topic_relatedness=WordTopicRelatednessType.PTW,
)

In [34]:
%%timeit

res = intra1.call(model)

241 ms ± 2.83 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [35]:
%%timeit

res = intra10.call(model)

467 ms ± 5.55 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [36]:
%%time

res = intra100.call(model)

CPU times: user 3.02 s, sys: 29.4 ms, total: 3.05 s
Wall time: 2.9 s

In [37]:
intra = IntratextCoherenceScore(
    name='toplen',
    data=dataset,
    documents=list(dataset._data.index),
    computation_method=ComputationMethod.SEGMENT_LENGTH,
    word_topic_relatedness=WordTopicRelatednessType.PTW,
)

In [38]:
%%time

res = intra.call(model)

CPU times: user 1min 40s, sys: 1.58 s, total: 1min 41s
Wall time: 1min 36s

In [39]:
NUM_ITERATIONS

20

In [40]:
%%timeit

model._fit(dataset.get_batch_vectorizer(), num_iterations=NUM_ITERATIONS)

21.2 s ± 245 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [31]:
intra1 = IntratextCoherenceScore(
    name='toplen_pwt',
    data=dataset,
    computation_method=ComputationMethod.SEGMENT_LENGTH,
    word_topic_relatedness=WordTopicRelatednessType.PWT,
    should_compute=False,  # only on last iter
)
intra2 = IntratextCoherenceScore(
    name='toplen_ptw',
    data=dataset,
    computation_method=ComputationMethod.SEGMENT_LENGTH,
    word_topic_relatedness=WordTopicRelatednessType.PTW,
    should_compute=False,
)
intra3 = IntratextCoherenceScore(
    name='topden_ptw',
    data=dataset,
    computation_method=ComputationMethod.SUM_OVER_WINDOW,
    word_topic_relatedness=WordTopicRelatednessType.PTW,
    should_compute=False,
)

###

intra3_w4 = IntratextCoherenceScore(
    name='topden_ptw_w4',
    data=dataset,
    computation_method=ComputationMethod.SUM_OVER_WINDOW,
    word_topic_relatedness=WordTopicRelatednessType.PTW,
    window=4,
    should_compute=False,
)
intra3_w2 = IntratextCoherenceScore(
    name='topden_ptw_w2',
    data=dataset,
    computation_method=ComputationMethod.SUM_OVER_WINDOW,
    word_topic_relatedness=WordTopicRelatednessType.PTW,
    window=2,
    should_compute=False,
)

In [37]:
%%time

res = intra1.call(model)

CPU times: user 1min 39s, sys: 1.38 s, total: 1min 40s
Wall time: 1min 35s

In [38]:
%%time

res = intra2.call(model)

CPU times: user 1min 38s, sys: 1.61 s, total: 1min 40s
Wall time: 1min 35s

In [39]:
%%time

res = intra3.call(model)

CPU times: user 2min 36s, sys: 5.96 s, total: 2min 42s
Wall time: 2min 36s

In [94]:
%%time

res = intra3_w4.call(model)

CPU times: user 2min 21s, sys: 4.61 s, total: 2min 26s
Wall time: 2min 16s

In [95]:
%%time

res = intra3_w2.call(model)

CPU times: user 2min 12s, sys: 3.5 s, total: 2min 15s
Wall time: 2min 6s

In [ ]:
# After try-catch in _get_word_topic_index instead of if-else:

In [30]:
%%time

res = intra1.call(model)

CPU times: user 1min 36s, sys: 1.53 s, total: 1min 38s
Wall time: 1min 33s

In [31]:
%%time

res = intra2.call(model)

CPU times: user 1min 36s, sys: 1.95 s, total: 1min 38s
Wall time: 1min 33s

In [32]:
%%time

res = intra3.call(model)

CPU times: user 2min 34s, sys: 5.95 s, total: 2min 40s
Wall time: 2min 33s

In [33]:
%%time

res = intra3_w4.call(model)

CPU times: user 2min 16s, sys: 3.46 s, total: 2min 20s
Wall time: 2min 14s

In [34]:
%%time

res = intra3_w2.call(model)

CPU times: user 2min 6s, sys: 2.91 s, total: 2min 9s
Wall time: 2min 4s

In [ ]:
# After removing np.floor from self._window // 2

In [29]:
%%time

res = intra3.call(model)

CPU times: user 2min 28s, sys: 5.52 s, total: 2min 34s
Wall time: 2min 27s

In [30]:
%%time

res = intra3_w4.call(model)

CPU times: user 2min 9s, sys: 3.62 s, total: 2min 13s
Wall time: 2min 7s

In [31]:
%%time

res = intra3_w2.call(model)

CPU times: user 2min 1s, sys: 2.33 s, total: 2min 3s
Wall time: 1min 58s

In [ ]:
# After careful handling of left border (so as to eliminate intersections)

In [33]:
%%time

res = intra3.call(model)

CPU times: user 2min 25s, sys: 5.46 s, total: 2min 30s
Wall time: 2min 24s

In [34]:
%%time

res = intra3_w4.call(model)

CPU times: user 2min 9s, sys: 3.32 s, total: 2min 12s
Wall time: 2min 7s

In [35]:
%%time

res = intra3_w2.call(model)

CPU times: user 2min 1s, sys: 2.63 s, total: 2min 3s
Wall time: 1min 58s

In [28]:
# After np.sum -> sum

In [29]:
%%time

res = intra3.call(model)

CPU times: user 2min 12s, sys: 4.59 s, total: 2min 17s
Wall time: 2min 11s

In [30]:
%%time

res = intra3_w4.call(model)

CPU times: user 1min 58s, sys: 2.81 s, total: 2min
Wall time: 1min 55s

In [31]:
%%time

res = intra3_w2.call(model)

CPU times: user 1min 50s, sys: 2.2 s, total: 1min 52s
Wall time: 1min 47s

In [ ]:
# After sum(list) -> v + dv

In [32]:
%%time

res = intra3.call(model)

CPU times: user 2min 12s, sys: 4.73 s, total: 2min 17s
Wall time: 2min 11s

In [33]:
%%time

res = intra3_w4.call(model)

CPU times: user 1min 57s, sys: 2.76 s, total: 2min
Wall time: 1min 55s

In [34]:
%%time

res = intra3_w2.call(model)

CPU times: user 1min 49s, sys: 2.21 s, total: 1min 51s
Wall time: 1min 47s

In [ ]:
# After lru cache (unlimited) for _get_relatedness

In [34]:
%%time

res = intra3.call(model)

CPU times: user 1min 56s, sys: 2.66 s, total: 1min 58s
Wall time: 1min 54s

In [35]:
%%time

res = intra3_w4.call(model)

CPU times: user 1min 50s, sys: 2.09 s, total: 1min 52s
Wall time: 1min 47s

In [36]:
%%time

res = intra3_w2.call(model)

CPU times: user 1min 45s, sys: 1.55 s, total: 1min 47s
Wall time: 1min 43s

In [ ]:
# After lru cache (5_000_000) for _get_relatedness

In [32]:
%%time

res = intra3.call(model)

CPU times: user 1min 58s, sys: 2.67 s, total: 2min 1s
Wall time: 1min 56s

In [33]:
%%time

res = intra3_w4.call(model)

CPU times: user 1min 51s, sys: 2.26 s, total: 1min 53s
Wall time: 1min 49s

In [34]:
%%time

res = intra3_w2.call(model)

CPU times: user 1min 47s, sys: 1.5 s, total: 1min 48s
Wall time: 1min 44s

In [ ]:
# After lru cache (unlimited) for _get_relatedness and _get_word_topic_index

In [34]:
%%time

res = intra2.call(model)

CPU times: user 1min 39s, sys: 2.01 s, total: 1min 41s
Wall time: 1min 36s

In [31]:
%%time

res = intra3.call(model)

CPU times: user 1min 59s, sys: 2.78 s, total: 2min 2s
Wall time: 1min 57s

In [32]:
%%time

res = intra3_w4.call(model)

CPU times: user 1min 53s, sys: 1.87 s, total: 1min 55s
Wall time: 1min 50s

In [33]:
%%time

res = intra3_w2.call(model)

CPU times: user 1min 49s, sys: 1.43 s, total: 1min 51s
Wall time: 1min 46s

In [ ]:
# lru cache (unlimited) for _get_relatedness only

In [33]:
%%time

res = intra2.call(model)

CPU times: user 1min 36s, sys: 2.07 s, total: 1min 38s
Wall time: 1min 33s

In [34]:
%%time

res = intra3.call(model)

CPU times: user 1min 57s, sys: 2.64 s, total: 2min
Wall time: 1min 55s

In [35]:
%%time

res = intra3_w4.call(model)

CPU times: user 1min 51s, sys: 1.72 s, total: 1min 52s
Wall time: 1min 48s

In [36]:
%%time

res = intra3_w2.call(model)

CPU times: user 1min 45s, sys: 1.84 s, total: 1min 47s
Wall time: 1min 42s

In [37]:
model.get_phi(class_ids=MAIN_MODALITY)['topic_18'].sort_values(ascending=False)

modality  token
@word     система              0.008737
          технология           0.007684
          задача               0.007392
          данные               0.006979
          сеть                 0.005978
                                 ...
          ограда               0.000000
          насильственно        0.000000
          ячмень               0.000000
          тераэлектронвольт    0.000000
          дублирование         0.000000
Name: topic_18, Length: 19537, dtype: float32

In [38]:
model.class_ids

{'@word': 1}

In [39]:
KNOWN_METRICS

['euclidean', 'jensenshannon', 'hellinger', 'cosine']

In [40]:
MAIN_MODALITY

'@word'

In [41]:
def fit_and_compute_scores(model, dataset):
    model._fit(dataset.get_batch_vectorizer(), num_iterations=NUM_ITERATIONS)

    score_values = {
        'perplexity': model.scores[f'PerplexityScore{MAIN_MODALITY}'][-1],
    }

    phi = model.get_phi()

    # Currently all topics are taken into account
    target_topic_indices = list(range(NUM_TOPICS))  # phi.columns.get_loc()
    target_topic_names = [phi.columns[i] for i in target_topic_indices]

    
    top = NUM_TOP_TOKENS
    coherence_score = TopTokenCoherence(
        name=f'coherence_{top}',
        func=create_pmi_top_function(
            occurences, co_occurences,
            dataset.get_dataset().shape[0], [top],
            topic_indices=target_topic_indices,
            co_occurrences_smooth=1e-2,
        )
    )

    # print(f'Computing "{coherence_score._name}"...')
    
    value = coherence_score.call(model)
    score_values[coherence_score._name] = value
    topic_coherences = coherence_score.call_by_topic(model)
    topic_coherences = {t: float(v) for t, v in topic_coherences.items()}

    # print(f'Result by topic: {topic_coherences}.')


    # intra1 = IntratextCoherenceScore(
    #     name='toplen_pwt',
    #     data=dataset,
    #     computation_method=ComputationMethod.SEGMENT_LENGTH,
    #     word_topic_relatedness=WordTopicRelatednessType.PWT,
    #     should_compute=False,  # only on last iter
    # )
    intra2 = IntratextCoherenceScore(
        name='toplen_ptw',
        data=dataset,
        computation_method=ComputationMethod.SEGMENT_LENGTH,
        word_topic_relatedness=WordTopicRelatednessType.PTW,
        should_compute=False,
    )
    # intra3 = IntratextCoherenceScore(
    #     name='topden_ptw',
    #     data=dataset,
    #     computation_method=ComputationMethod.SUM_OVER_WINDOW,
    #     word_topic_relatedness=WordTopicRelatednessType.PTW,
    #     should_compute=False,
    # )
    intra3_w4 = IntratextCoherenceScore(
        name='topden_ptw',
        data=dataset,
        computation_method=ComputationMethod.SUM_OVER_WINDOW,
        word_topic_relatedness=WordTopicRelatednessType.PTW,
        window=4,
        should_compute=False,
    )

    intra_topic_coherences = dict()

    for intra in [intra2, intra3_w4]:  #[intra1, intra2, intra3]:
        # print(f'\nComputing "{intra._name}"...')

        current_intra_topic_coherences = intra.compute(model)

        assert all(v is not None for v in current_intra_topic_coherences.values())

        _values = current_intra_topic_coherences.values()

        current_intra_topic_coherences = {
            i: current_intra_topic_coherences[t]  # if v is not None else 0.0
            for i, t in enumerate(target_topic_names)
        }

        assert all(abs(x - y) <= 1e-6 for x, y in zip(_values, current_intra_topic_coherences.values())), (_values, current_intra_topic_coherences.values())  # "sorted" Python dicts
        
        intra_topic_coherences[f'topic_coherences_{intra._name}'] = current_intra_topic_coherences

        value = float(np.median(list(current_intra_topic_coherences.values())))
        score_values[intra._name] = value

        # print(f'Result by topic: {current_intra_topic_coherences}.')


    diversity_scores = [
        DiversityScore(
            name=f'diversity_{metric}',
            metric=metric,
            topic_names=target_topic_names,
            class_ids=MAIN_MODALITY,
        )
    
        for metric in KNOWN_METRICS
    ]
    
    for score in diversity_scores:
        value = score.call(model)
        score_values[score._name] = value

    
    return {
        'scores': score_values,
        'topic_coherences': topic_coherences,
        **intra_topic_coherences,
    }

In [42]:
BEST_PARAMS = dict()

## PLSA

In [43]:
PARAMS_EXPLORED[KnownModel.PLSA]

{}

In [44]:
NUM_TOPICS

20

In [45]:
model = init_model_from_family(
    family=KnownModel.PLSA,
    dataset=dataset,
    main_modality=MAIN_MODALITY,
    num_topics=NUM_TOPICS,
    seed=0,
)

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

In [71]:
start = time.time()

scores = fit_and_compute_scores(model, dataset)

end = time.time()

print(f'Elapsed: {(end - start) / 60} min')

Computing "coherence_20"...
Result by topic: {0: 0.4682133200037822, 1: 0.5525499039748306, 2: 0.3662412591097539, 3: 0.7660746688638103, 4: 0.6599584504901529, 5: 1.2151843412918593, 6: 0.784374938331295, 7: 0.6583524284174844, 8: 0.7558873960285204, 9: 0.8872288724338003, 10: 0.5060579830596448, 11: 1.1643195534386466, 12: 1.0551562205101295, 13: 0.6667121824386473, 14: 0.34910355580365166, 15: 0.7823822821267535, 16: 1.0022462210267367, 17: 0.8400496475709041, 18: 0.706545516531718, 19: 0.425808078140945}.

Computing "toplen_pwt"...
Result by topic: {0: 2.0956432149414908, 1: 2.1535240947120737, 2: 2.8292371579349185, 3: 1.87571387898929, 4: 2.346451870009993, 5: 3.226761710980802, 6: 1.9268920456173568, 7: 1.6180633470149492, 8: 2.1603641420965194, 9: 2.111364111726634, 10: 1.8843975960799404, 11: 2.67100155859519, 12: 2.0041191448861375, 13: 2.2960403613814058, 14: 2.29035348424422, 15: 2.2511018392627333, 16: 3.2202474401611747, 17: 2.1978257467664424, 18: 2.246628765802841, 19: 3.189557861813141}.

Computing "toplen_ptw"...
Result by topic: {0: 2.0956432149414908, 1: 2.1535240947120737, 2: 2.8292371579349185, 3: 1.87571387898929, 4: 2.346451870009993, 5: 3.226761710980802, 6: 1.9268920456173568, 7: 1.6180633470149492, 8: 2.1603641420965194, 9: 2.111364111726634, 10: 1.8843975960799404, 11: 2.67100155859519, 12: 2.0041191448861375, 13: 2.2960403613814058, 14: 2.29035348424422, 15: 2.2511018392627333, 16: 3.2202474401611747, 17: 2.1978257467664424, 18: 2.246628765802841, 19: 3.189557861813141}.

Computing "topden_ptw"...
Result by topic: {0: 0.7896331474849907, 1: 0.7559289034935677, 2: 0.8722740552381104, 3: 0.8514700601759121, 4: 0.73577100251197, 5: 0.7997852519793711, 6: 0.7778503322636471, 7: 0.7303882124383602, 8: 0.7675140659517793, 9: 0.8531204388078075, 10: 0.6444692721077557, 11: 0.7265469742183943, 12: 0.8373283671433829, 13: 0.7586853253659983, 14: 0.8129853359444171, 15: 0.7984751357249151, 16: 0.9248026176148187, 17: 0.7995769794528707, 18: 0.796055406491449, 19: 0.7363659184132179}.
Elapsed: 6.190842096010844 min

In [41]:
start = time.time()

scores = fit_and_compute_scores(model, dataset)

end = time.time()

print(f'\nElapsed: {(end - start) / 60} min')

Elapsed: 4.016988714536031 min

In [46]:
start = time.time()

scores = fit_and_compute_scores(model, dataset)

end = time.time()

print(f'\nElapsed: {(end - start) / 60} min')

Elapsed: 3.7278953472773235 min

In [47]:
scores

{'scores': {'perplexity': 2474.488525390625,
  'coherence_20': array([0.73062234]),
  'toplen_ptw': 2.2222272562846417,
  'topden_ptw': 0.4862072399044338,
  'diversity_euclidean': 0.05432938513130658,
  'diversity_jensenshannon': 0.6000053851445594,
  'diversity_hellinger': 0.6857673704489131,
  'diversity_cosine': 0.7377318942011689},
 'topic_coherences': {0: 0.4682133200037822,
  1: 0.5525499039748306,
  2: 0.3662412591097539,
  3: 0.7660746688638103,
  4: 0.6599584504901529,
  5: 1.2151843412918593,
  6: 0.784374938331295,
  7: 0.6583524284174844,
  8: 0.7558873960285204,
  9: 0.8872288724338003,
  10: 0.5060579830596448,
  11: 1.1643195534386466,
  12: 1.0551562205101295,
  13: 0.6667121824386473,
  14: 0.34910355580365166,
  15: 0.7823822821267535,
  16: 1.0022462210267367,
  17: 0.8400496475709041,
  18: 0.706545516531718,
  19: 0.425808078140945},
 'topic_coherences_toplen_ptw': {0: 2.0956432149414908,
  1: 2.1535240947120737,
  2: 2.8292371579349185,
  3: 1.87571387898929,
  4: 2.346451870009993,
  5: 3.226761710980802,
  6: 1.9268920456173568,
  7: 1.6180633470149492,
  8: 2.1603641420965194,
  9: 2.111364111726634,
  10: 1.8843975960799404,
  11: 2.67100155859519,
  12: 2.0041191448861375,
  13: 2.2960403613814058,
  14: 2.29035348424422,
  15: 2.2511018392627333,
  16: 3.2202474401611747,
  17: 2.1978257467664424,
  18: 2.246628765802841,
  19: 3.189557861813141},
 'topic_coherences_topden_ptw': {0: 0.49256696103040903,
  1: 0.4669669927009902,
  2: 0.4983296509375541,
  3: 0.5608629673890791,
  4: 0.4543158719210913,
  5: 0.4846404961879045,
  6: 0.48117616488283543,
  7: 0.4730692734803976,
  8: 0.4763528612894804,
  9: 0.5382440068279707,
  10: 0.3880340392847704,
  11: 0.4469950428952374,
  12: 0.55271049139953,
  13: 0.4649797338458489,
  14: 0.4877739836209631,
  15: 0.5050110227486303,
  16: 0.5583021770323158,
  17: 0.4943657458140127,
  18: 0.4937332651756125,
  19: 0.4260093947948369}}

In [26]:
BEST_PARAMS[KnownModel.PLSA] = None

## Sparse

In [27]:
PARAMS_EXPLORED[KnownModel.SPARSE]

{'smooth_bcg_tau': [0.05, 0.1], 'sparse_sp_tau': [-0.05, -0.1]}

In [39]:
results = dict()

for sparse_sp_tau in PARAMS_EXPLORED[KnownModel.SPARSE]['sparse_sp_tau']:
    for smooth_bcg_tau in PARAMS_EXPLORED[KnownModel.SPARSE]['smooth_bcg_tau']:
        key = (sparse_sp_tau, smooth_bcg_tau)
        results[key] = []

        print(key)

        for seed in range(NUM_TRAINS):
            print(seed)
            
            model = init_model_from_family(
                family=KnownModel.SPARSE,
                dataset=dataset,
                main_modality=MAIN_MODALITY,
                num_topics=NUM_TOPICS,
                seed=seed,
                model_params={'sparse_sp_tau': sparse_sp_tau, 'smooth_bcg_tau': smooth_bcg_tau}
            )

            for reg in model.regularizers.data:
                print(f"{reg}: {model.regularizers[reg].tau}")
 
            scores = fit_and_compute_scores(model, dataset)
            results[key].append(scores)

        print()

    print()

(-0.05, 0.05)
0
smooth_phi_bcg: 3.9330432826567625
smooth_theta_bcg: 22.167852062588906
sparse_phi_sp: -0.17792338659637733
sparse_theta_sp: -1.0028314028314027
1

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 3.9330432826567625
smooth_theta_bcg: 22.167852062588906
sparse_phi_sp: -0.17792338659637733
sparse_theta_sp: -1.0028314028314027
2

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 3.9330432826567625
smooth_theta_bcg: 22.167852062588906
sparse_phi_sp: -0.17792338659637733
sparse_theta_sp: -1.0028314028314027

(-0.05, 0.1)
0

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 8.30309137449761
smooth_theta_bcg: 46.7987987987988
sparse_phi_sp: -0.17792338659637733
sparse_theta_sp: -1.0028314028314027
1

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 8.30309137449761
smooth_theta_bcg: 46.7987987987988
sparse_phi_sp: -0.17792338659637733
sparse_theta_sp: -1.0028314028314027
2

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 8.30309137449761
smooth_theta_bcg: 46.7987987987988
sparse_phi_sp: -0.17792338659637733
sparse_theta_sp: -1.0028314028314027


(-0.1, 0.05)
0

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 3.9330432826567625
smooth_theta_bcg: 22.167852062588906
sparse_phi_sp: -0.33967191986581124
sparse_theta_sp: -1.914496314496314
1

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 3.9330432826567625
smooth_theta_bcg: 22.167852062588906
sparse_phi_sp: -0.33967191986581124
sparse_theta_sp: -1.914496314496314
2

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 3.9330432826567625
smooth_theta_bcg: 22.167852062588906
sparse_phi_sp: -0.33967191986581124
sparse_theta_sp: -1.914496314496314

(-0.1, 0.1)
0

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 8.30309137449761
smooth_theta_bcg: 46.7987987987988
sparse_phi_sp: -0.33967191986581124
sparse_theta_sp: -1.914496314496314
1

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 8.30309137449761
smooth_theta_bcg: 46.7987987987988
sparse_phi_sp: -0.33967191986581124
sparse_theta_sp: -1.914496314496314
2

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 8.30309137449761
smooth_theta_bcg: 46.7987987987988
sparse_phi_sp: -0.33967191986581124
sparse_theta_sp: -1.914496314496314

In [41]:
results

{(-0.05,
  0.05): [{'scores': {'perplexity': 3350.7021484375,
    'coherence_20': array([0.79300455]),
    'diversity_euclidean': 0.06043655558783355,
    'diversity_jensenshannon': 0.06043655558783355,
    'diversity_hellinger': 0.06043655558783355,
    'diversity_cosine': 0.06043655558783355},
   'topic_coherences': {0: 0.4613815887605477,
    1: 0.7254412703733861,
    2: 1.1825977284049987,
    3: 0.8628769522261815,
    4: 0.9995690399053021,
    5: 0.9733058107435728,
    6: 0.6980303292285863,
    7: 0.5761489198688887,
    8: 0.7483147931845104,
    9: 0.8621148798441607,
    10: 1.1127012218906336,
    11: 0.5671635792800231,
    12: 0.7538572393166724,
    13: 0.5220896659030285,
    14: 0.5394795375149565,
    15: 0.8817214328684023,
    16: 1.1619803113527283,
    17: 0.6217772221062762,
    18: 0.8775876214854835,
    19: 0.7319519205247833}}, {'scores': {'perplexity': 3328.0341796875,
    'coherence_20': array([0.78209502]),
    'diversity_euclidean': 0.05763263478401777,
    'diversity_jensenshannon': 0.05763263478401777,
    'diversity_hellinger': 0.05763263478401777,
    'diversity_cosine': 0.05763263478401777},
   'topic_coherences': {0: 1.023550182421416,
    1: 0.5248479121470289,
    2: 0.8225244009513806,
    3: 0.674308797657171,
    4: 0.6533449502459261,
    5: 0.5076190517446678,
    6: 0.7789456852763191,
    7: 0.876872179256724,
    8: 0.8368612460794617,
    9: 0.682384646270101,
    10: 0.8881398485748709,
    11: 0.7624418126020844,
    12: 0.7427119060768672,
    13: 0.9057220317086481,
    14: 0.9021693107469515,
    15: 1.152624772920907,
    16: 0.8885159437153582,
    17: 0.6267778588958965,
    18: 0.4963571085516563,
    19: 0.895180850802176}}, {'scores': {'perplexity': 3316.9189453125,
    'coherence_20': array([0.82440286]),
    'diversity_euclidean': 0.060409348937749734,
    'diversity_jensenshannon': 0.060409348937749734,
    'diversity_hellinger': 0.060409348937749734,
    'diversity_cosine': 0.060409348937749734},
   'topic_coherences': {0: 0.47289441744865024,
    1: 0.895191199582525,
    2: 0.9947829190435333,
    3: 0.5443723065708617,
    4: 0.5530509144617949,
    5: 0.9683580232146423,
    6: 0.6174294754377214,
    7: 0.817637601587416,
    8: 1.1044653880681299,
    9: 0.7748504876820261,
    10: 0.7113707582322109,
    11: 1.120295257533965,
    12: 0.8337056528533116,
    13: 1.1155502737727223,
    14: 0.8557567032160106,
    15: 0.8104272587205518,
    16: 0.8431258811334813,
    17: 0.8637743942777963,
    18: 0.5068581561985701,
    19: 1.0841602020589076}}],
 (-0.05,
  0.1): [{'scores': {'perplexity': 3508.26171875,
    'coherence_20': array([0.80173184]),
    'diversity_euclidean': 0.06597321506256922,
    'diversity_jensenshannon': 0.06597321506256922,
    'diversity_hellinger': 0.06597321506256922,
    'diversity_cosine': 0.06597321506256922},
   'topic_coherences': {0: 0.4613815887605476,
    1: 0.6829240312238523,
    2: 1.1655566135575277,
    3: 0.9057840995231455,
    4: 0.9900931922174752,
    5: 0.9776145540656336,
    6: 0.6762258732599193,
    7: 0.5895991418104306,
    8: 0.8204201742945285,
    9: 0.8959233556558651,
    10: 1.1127012218906336,
    11: 0.582987974502297,
    12: 0.8665740864020082,
    13: 0.4693519259443132,
    14: 0.500508932298005,
    15: 0.910133851879333,
    16: 1.103236082407385,
    17: 0.6996543462786133,
    18: 0.9053072935924146,
    19: 0.7186584313574509}}, {'scores': {'perplexity': 3489.381103515625,
    'coherence_20': array([0.79217732]),
    'diversity_euclidean': 0.06258639325165387,
    'diversity_jensenshannon': 0.06258639325165387,
    'diversity_hellinger': 0.06258639325165387,
    'diversity_cosine': 0.06258639325165387},
   'topic_coherences': {0: 1.023550182421416,
    1: 0.5248479121470288,
    2: 0.8116256452959394,
    3: 0.5442513142476701,
    4: 0.6656468075614915,
    5: 0.5039535366370199,
    6: 0.7789456852763191,
    7: 0.9300236489620377,
    8: 0.9982765937362239,
    9: 0.7067273490963958,
    10: 0.9589182002514065,
    11: 0.7548560275858105,
    12: 0.7610356140201445,
    13: 0.9534998576414598,
    14: 0.9021693107469517,
    15: 1.0958315989415028,
    16: 0.9016826143323675,
    17: 0.6221642855067032,
    18: 0.49431798542727906,
    19: 0.9112223157272399}}, {'scores': {'perplexity': 3476.9638671875,
    'coherence_20': array([0.8450533]),
    'diversity_euclidean': 0.06697923069340894,
    'diversity_jensenshannon': 0.06697923069340894,
    'diversity_hellinger': 0.06697923069340894,
    'diversity_cosine': 0.06697923069340894},
   'topic_coherences': {0: 0.5184457350099556,
    1: 1.1016281360109028,
    2: 1.0016320869064534,
    3: 0.5238198125987364,
    4: 0.5201958807899983,
    5: 0.8803614435615241,
    6: 0.6274133933354777,
    7: 0.7738546419404527,
    8: 1.3200143878869204,
    9: 0.8849182427869771,
    10: 0.9182779415108294,
    11: 1.120295257533965,
    12: 0.7770940670534239,
    13: 1.0355344526261172,
    14: 0.8597234841060967,
    15: 0.8169515987218213,
    16: 0.8089193276027205,
    17: 0.8738011356288502,
    18: 0.4948701453260389,
    19: 1.04331472938447}}],
 (-0.1,
  0.05): [{'scores': {'perplexity': 3494.60546875,
    'coherence_20': array([0.77860955]),
    'diversity_euclidean': 0.06657666667663305,
    'diversity_jensenshannon': 0.06657666667663305,
    'diversity_hellinger': 0.06657666667663305,
    'diversity_cosine': 0.06657666667663305},
   'topic_coherences': {0: 0.48364437783159253,
    1: 0.6534423526658132,
    2: 1.036482850379524,
    3: 0.8905639013498022,
    4: 0.8538229805950068,
    5: 0.937436539893936,
    6: 0.6781462846693352,
    7: 0.5873107630554116,
    8: 0.7483147931845104,
    9: 0.8334140541263738,
    10: 0.912993063636199,
    11: 0.567163579280023,
    12: 0.7779832257854561,
    13: 0.5532009834650008,
    14: 0.6313069721973684,
    15: 0.8850574687538703,
    16: 1.1814186955647135,
    17: 0.7230361643422202,
    18: 0.9053072935924146,
    19: 0.7321447306783987}}, {'scores': {'perplexity': 3469.619873046875,
    'coherence_20': array([0.79647317]),
    'diversity_euclidean': 0.06387695281106373,
    'diversity_jensenshannon': 0.06387695281106373,
    'diversity_hellinger': 0.06387695281106373,
    'diversity_cosine': 0.06387695281106373},
   'topic_coherences': {0: 1.023550182421416,
    1: 0.5248479121470289,
    2: 0.9384128301328961,
    3: 0.633865132038836,
    4: 0.6733326009226643,
    5: 0.5039535366370199,
    6: 0.7789456852763188,
    7: 0.8768721792567242,
    8: 0.7899426406830731,
    9: 0.6348277387203504,
    10: 0.9736503152520352,
    11: 0.7975322823674675,
    12: 0.7447871908443214,
    13: 1.0421589942648635,
    14: 0.9411706723127272,
    15: 1.0958315989415028,
    16: 0.8181809413099955,
    17: 0.7369746878675899,
    18: 0.5054453426393558,
    19: 0.895180850802176}}, {'scores': {'perplexity': 3463.411865234375,
    'coherence_20': array([0.82157881]),
    'diversity_euclidean': 0.06677323022220694,
    'diversity_jensenshannon': 0.06677323022220694,
    'diversity_hellinger': 0.06677323022220694,
    'diversity_cosine': 0.06677323022220694},
   'topic_coherences': {0: 0.5340785231045785,
    1: 0.9379356841275351,
    2: 0.9947829190435333,
    3: 0.5553667123396504,
    4: 0.5337667179838761,
    5: 0.8535760151566667,
    6: 0.6037781003693478,
    7: 0.79029092587478,
    8: 1.2715549527238157,
    9: 0.7690583970317358,
    10: 0.8493953537492995,
    11: 1.0429496397421623,
    12: 0.7692300943425667,
    13: 1.0092392793059999,
    14: 0.9325415511649958,
    15: 0.8417768291967237,
    16: 0.8089193276027202,
    17: 0.8637743942777965,
    18: 0.5098143772097791,
    19: 0.9597463217821807}}],
 (-0.1,
  0.1): [{'scores': {'perplexity': 3660.406494140625,
    'coherence_20': array([0.80726446]),
    'diversity_euclidean': 0.07249868779084843,
    'diversity_jensenshannon': 0.07249868779084843,
    'diversity_hellinger': 0.07249868779084843,
    'diversity_cosine': 0.07249868779084843},
   'topic_coherences': {0: 0.4613815887605477,
    1: 0.7802845558473921,
    2: 1.036400034618703,
    3: 0.9433173469971258,
    4: 0.9174545562627839,
    5: 1.0226821231432888,
    6: 0.6039798102976875,
    7: 0.5645733815766065,
    8: 0.8254019403643338,
    9: 0.8792641414718042,
    10: 1.1009218854191407,
    11: 0.5671635792800231,
    12: 0.8441551799828931,
    13: 0.5009599651385398,
    14: 0.5491763441685032,
    15: 0.8850574687538705,
    16: 1.2761776700035847,
    17: 0.721635742378151,
    18: 0.8520832721069133,
    19: 0.8132185278262964}}, {'scores': {'perplexity': 3631.0732421875,
    'coherence_20': array([0.79209292]),
    'diversity_euclidean': 0.06882978779033408,
    'diversity_jensenshannon': 0.06882978779033408,
    'diversity_hellinger': 0.06882978779033408,
    'diversity_cosine': 0.06882978779033408},
   'topic_coherences': {0: 1.023550182421416,
    1: 0.5183943938396494,
    2: 0.8089349187848021,
    3: 0.6330813699664368,
    4: 0.7072907732186825,
    5: 0.5076190517446678,
    6: 0.7789456852763189,
    7: 0.94984150584292,
    8: 1.0883564507554728,
    9: 0.6535255211329682,
    10: 0.9597948957871318,
    11: 0.7237543520839805,
    12: 0.7666270545062518,
    13: 0.654779288386038,
    14: 0.9411706723127272,
    15: 1.0958315989415028,
    16: 0.9548339363821812,
    17: 0.6677417774534287,
    18: 0.4965625587060566,
    19: 0.9112223157272399}}, {'scores': {'perplexity': 3621.5966796875,
    'coherence_20': array([0.84188609]),
    'diversity_euclidean': 0.07354040545012018,
    'diversity_jensenshannon': 0.07354040545012018,
    'diversity_hellinger': 0.07354040545012018,
    'diversity_cosine': 0.07354040545012018},
   'topic_coherences': {0: 0.5668799002856361,
    1: 1.1335190589152444,
    2: 0.9521900229399286,
    3: 0.5518227079685022,
    4: 0.5201958807899985,
    5: 0.8202895450736348,
    6: 0.6104630192590096,
    7: 0.8159545621151013,
    8: 1.2711226720119144,
    9: 0.9021459969802177,
    10: 0.7277904653411018,
    11: 1.120295257533965,
    12: 0.7254337075019552,
    13: 1.1305359981340306,
    14: 0.8716849169238327,
    15: 0.8169515987218213,
    16: 0.8089193276027205,
    17: 0.9207174270272137,
    18: 0.4948701453260389,
    19: 1.0759395793420663}}]}

In [42]:
for k, r in results.items():
    mean_ppl = sum(v['scores']['perplexity'] for v in r) / len(r)
    print(k, mean_ppl)

(-0.05, 0.05) 3331.8850911458335
(-0.05, 0.1) 3491.5355631510415
(-0.1, 0.05) 3475.8790690104165
(-0.1, 0.1) 3637.692138671875

In [ ]:
# Best: (-0.05, 0.05) 3331.8850911458335

In [27]:
BEST_PARAMS[KnownModel.SPARSE] = {
    'sparse_sp_tau': -0.05,
    'smooth_bcg_tau': 0.05,
}

## Decorrelation

In [17]:
PARAMS_EXPLORED[KnownModel.DECORRELATION]

{'decorrelation_tau': [0.02, 0.05, 0.1]}

In [23]:
PARAMS_EXPLORED[KnownModel.ARTM]

{'smooth_bcg_tau': [0.05, 0.1],
 'sparse_sp_tau': [-0.05, -0.1],
 'decorrelation_tau': [0.02, 0.05, 0.1]}

In [32]:
DECORRELATION_TAUS = [0.01] + PARAMS_EXPLORED[KnownModel.DECORRELATION]['decorrelation_tau']

In [33]:
results = dict()

for decorrelation_tau in DECORRELATION_TAUS:
    for smooth_bcg_tau in PARAMS_EXPLORED[KnownModel.SPARSE]['smooth_bcg_tau']:
        key = (decorrelation_tau, smooth_bcg_tau)
        results[key] = []

        print(key)

        for seed in range(NUM_TRAINS):
            print(seed)
            
            model = init_model_from_family(
                family=KnownModel.ARTM,
                dataset=dataset,
                main_modality=MAIN_MODALITY,
                num_topics=NUM_TOPICS,
                seed=seed,
                model_params={
                    'decorrelation_tau': decorrelation_tau,
                    'smooth_bcg_tau': smooth_bcg_tau,
                    'sparse_sp_tau': 0.0,
                }
            )

            for reg in model.regularizers.data:
                print(f"{reg}: {model.regularizers[reg].tau}")

            scores = fit_and_compute_scores(model, dataset)
            results[key].append(scores)

        print()

    print()

(0.02, 0.05)
0
smooth_phi_bcg: 3.9330432826567625
smooth_theta_bcg: 22.167852062588906
sparse_phi_sp: 0.0
sparse_theta_sp: 0.0
decorrelation: 0.02
1

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 3.9330432826567625
smooth_theta_bcg: 22.167852062588906
sparse_phi_sp: 0.0
sparse_theta_sp: 0.0
decorrelation: 0.02
2

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 3.9330432826567625
smooth_theta_bcg: 22.167852062588906
sparse_phi_sp: 0.0
sparse_theta_sp: 0.0
decorrelation: 0.02

(0.02, 0.1)
0

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 8.30309137449761
smooth_theta_bcg: 46.7987987987988
sparse_phi_sp: 0.0
sparse_theta_sp: 0.0
decorrelation: 0.02
1

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 8.30309137449761
smooth_theta_bcg: 46.7987987987988
sparse_phi_sp: 0.0
sparse_theta_sp: 0.0
decorrelation: 0.02
2

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 8.30309137449761
smooth_theta_bcg: 46.7987987987988
sparse_phi_sp: 0.0
sparse_theta_sp: 0.0
decorrelation: 0.02


(0.05, 0.05)
0

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 3.9330432826567625
smooth_theta_bcg: 22.167852062588906
sparse_phi_sp: 0.0
sparse_theta_sp: 0.0
decorrelation: 0.05
1

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 3.9330432826567625
smooth_theta_bcg: 22.167852062588906
sparse_phi_sp: 0.0
sparse_theta_sp: 0.0
decorrelation: 0.05
2

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 3.9330432826567625
smooth_theta_bcg: 22.167852062588906
sparse_phi_sp: 0.0
sparse_theta_sp: 0.0
decorrelation: 0.05

(0.05, 0.1)
0

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 8.30309137449761
smooth_theta_bcg: 46.7987987987988
sparse_phi_sp: 0.0
sparse_theta_sp: 0.0
decorrelation: 0.05
1

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 8.30309137449761
smooth_theta_bcg: 46.7987987987988
sparse_phi_sp: 0.0
sparse_theta_sp: 0.0
decorrelation: 0.05
2

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 8.30309137449761
smooth_theta_bcg: 46.7987987987988
sparse_phi_sp: 0.0
sparse_theta_sp: 0.0
decorrelation: 0.05


(0.1, 0.05)
0

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 3.9330432826567625
smooth_theta_bcg: 22.167852062588906
sparse_phi_sp: 0.0
sparse_theta_sp: 0.0
decorrelation: 0.1
1

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 3.9330432826567625
smooth_theta_bcg: 22.167852062588906
sparse_phi_sp: 0.0
sparse_theta_sp: 0.0
decorrelation: 0.1
2

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 3.9330432826567625
smooth_theta_bcg: 22.167852062588906
sparse_phi_sp: 0.0
sparse_theta_sp: 0.0
decorrelation: 0.1

(0.1, 0.1)
0

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 8.30309137449761
smooth_theta_bcg: 46.7987987987988
sparse_phi_sp: 0.0
sparse_theta_sp: 0.0
decorrelation: 0.1
1

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 8.30309137449761
smooth_theta_bcg: 46.7987987987988
sparse_phi_sp: 0.0
sparse_theta_sp: 0.0
decorrelation: 0.1
2

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 8.30309137449761
smooth_theta_bcg: 46.7987987987988
sparse_phi_sp: 0.0
sparse_theta_sp: 0.0
decorrelation: 0.1


(0.01, 0.05)
0

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 3.9330432826567625
smooth_theta_bcg: 22.167852062588906
sparse_phi_sp: 0.0
sparse_theta_sp: 0.0
decorrelation: 0.01
1

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 3.9330432826567625
smooth_theta_bcg: 22.167852062588906
sparse_phi_sp: 0.0
sparse_theta_sp: 0.0
decorrelation: 0.01
2

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 3.9330432826567625
smooth_theta_bcg: 22.167852062588906
sparse_phi_sp: 0.0
sparse_theta_sp: 0.0
decorrelation: 0.01

(0.01, 0.1)
0

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 8.30309137449761
smooth_theta_bcg: 46.7987987987988
sparse_phi_sp: 0.0
sparse_theta_sp: 0.0
decorrelation: 0.01
1

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 8.30309137449761
smooth_theta_bcg: 46.7987987987988
sparse_phi_sp: 0.0
sparse_theta_sp: 0.0
decorrelation: 0.01
2

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 8.30309137449761
smooth_theta_bcg: 46.7987987987988
sparse_phi_sp: 0.0
sparse_theta_sp: 0.0
decorrelation: 0.01

results

In [34]:
len(results)

8

In [35]:
for k, r in results.items():
    mean_ppl = sum(v['scores']['perplexity'] for v in r) / len(r)

    print(k, mean_ppl)

(0.02, 0.05) 3080.7899576822915
(0.02, 0.1) 3209.5741373697915
(0.05, 0.05) 3085.8776041666665
(0.05, 0.1) 3216.2530110677085
(0.1, 0.05) 3148.940673828125
(0.1, 0.1) 3275.7158203125
(0.01, 0.05) 3081.0397135416665
(0.01, 0.1) 3209.85693359375

In [ ]:
# Best: (0.02, 0.05) 3080.7899576822915

In [19]:
BEST_PARAMS[KnownModel.DECORRELATION] = {
    'decorrelation_tau': 0.02,
    'smooth_bcg_tau': 0.05,
}

## ARTM

In [27]:
PARAMS_EXPLORED[KnownModel.SPARSE]

{'smooth_bcg_tau': [0.05, 0.1], 'sparse_sp_tau': [-0.05, -0.1]}

In [28]:
PARAMS_EXPLORED[KnownModel.DECORRELATION]

{'decorrelation_tau': [0.02, 0.05, 0.1]}

In [29]:
PARAMS_EXPLORED[KnownModel.ARTM]

{'smooth_bcg_tau': [0.05, 0.1],
 'sparse_sp_tau': [-0.05, -0.1],
 'decorrelation_tau': [0.02, 0.05, 0.1]}

In [36]:
results = dict()

for decorrelation_tau in DECORRELATION_TAUS:
    for sparse_sp_tau in PARAMS_EXPLORED[KnownModel.ARTM]['sparse_sp_tau']:
        for smooth_bcg_tau in PARAMS_EXPLORED[KnownModel.SPARSE]['smooth_bcg_tau']:
            key = (decorrelation_tau, sparse_sp_tau, smooth_bcg_tau)
            results[key] = []
    
            print(key)
    
            for seed in range(NUM_TRAINS):
                print(seed)
                
                model = init_model_from_family(
                    family=KnownModel.ARTM,
                    dataset=dataset,
                    main_modality=MAIN_MODALITY,
                    num_topics=NUM_TOPICS,
                    seed=seed,
                    model_params={
                        'decorrelation_tau': decorrelation_tau,
                        'smooth_bcg_tau': smooth_bcg_tau,
                        'sparse_sp_tau': sparse_sp_tau,
                    }
                )
    
                for reg in model.regularizers.data:
                    print(f"{reg}: {model.regularizers[reg].tau}")
    
                scores = fit_and_compute_scores(model, dataset)
                results[key].append(scores)

            print()

        print()

    print()

(0.02, -0.05, 0.05)
0

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 3.9330432826567625
smooth_theta_bcg: 22.167852062588906
sparse_phi_sp: -0.17792338659637733
sparse_theta_sp: -1.0028314028314027
decorrelation: 0.02
1

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 3.9330432826567625
smooth_theta_bcg: 22.167852062588906
sparse_phi_sp: -0.17792338659637733
sparse_theta_sp: -1.0028314028314027
decorrelation: 0.02
2

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 3.9330432826567625
smooth_theta_bcg: 22.167852062588906
sparse_phi_sp: -0.17792338659637733
sparse_theta_sp: -1.0028314028314027
decorrelation: 0.02

(0.02, -0.05, 0.1)
0

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 8.30309137449761
smooth_theta_bcg: 46.7987987987988
sparse_phi_sp: -0.17792338659637733
sparse_theta_sp: -1.0028314028314027
decorrelation: 0.02
1

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 8.30309137449761
smooth_theta_bcg: 46.7987987987988
sparse_phi_sp: -0.17792338659637733
sparse_theta_sp: -1.0028314028314027
decorrelation: 0.02
2

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 8.30309137449761
smooth_theta_bcg: 46.7987987987988
sparse_phi_sp: -0.17792338659637733
sparse_theta_sp: -1.0028314028314027
decorrelation: 0.02


(0.02, -0.1, 0.05)
0

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 3.9330432826567625
smooth_theta_bcg: 22.167852062588906
sparse_phi_sp: -0.33967191986581124
sparse_theta_sp: -1.914496314496314
decorrelation: 0.02
1

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 3.9330432826567625
smooth_theta_bcg: 22.167852062588906
sparse_phi_sp: -0.33967191986581124
sparse_theta_sp: -1.914496314496314
decorrelation: 0.02
2

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 3.9330432826567625
smooth_theta_bcg: 22.167852062588906
sparse_phi_sp: -0.33967191986581124
sparse_theta_sp: -1.914496314496314
decorrelation: 0.02

(0.02, -0.1, 0.1)
0

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 8.30309137449761
smooth_theta_bcg: 46.7987987987988
sparse_phi_sp: -0.33967191986581124
sparse_theta_sp: -1.914496314496314
decorrelation: 0.02
1

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 8.30309137449761
smooth_theta_bcg: 46.7987987987988
sparse_phi_sp: -0.33967191986581124
sparse_theta_sp: -1.914496314496314
decorrelation: 0.02
2

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 8.30309137449761
smooth_theta_bcg: 46.7987987987988
sparse_phi_sp: -0.33967191986581124
sparse_theta_sp: -1.914496314496314
decorrelation: 0.02



(0.05, -0.05, 0.05)
0

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 3.9330432826567625
smooth_theta_bcg: 22.167852062588906
sparse_phi_sp: -0.17792338659637733
sparse_theta_sp: -1.0028314028314027
decorrelation: 0.05
1

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 3.9330432826567625
smooth_theta_bcg: 22.167852062588906
sparse_phi_sp: -0.17792338659637733
sparse_theta_sp: -1.0028314028314027
decorrelation: 0.05
2

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 3.9330432826567625
smooth_theta_bcg: 22.167852062588906
sparse_phi_sp: -0.17792338659637733
sparse_theta_sp: -1.0028314028314027
decorrelation: 0.05

(0.05, -0.05, 0.1)
0

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 8.30309137449761
smooth_theta_bcg: 46.7987987987988
sparse_phi_sp: -0.17792338659637733
sparse_theta_sp: -1.0028314028314027
decorrelation: 0.05
1

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 8.30309137449761
smooth_theta_bcg: 46.7987987987988
sparse_phi_sp: -0.17792338659637733
sparse_theta_sp: -1.0028314028314027
decorrelation: 0.05
2

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 8.30309137449761
smooth_theta_bcg: 46.7987987987988
sparse_phi_sp: -0.17792338659637733
sparse_theta_sp: -1.0028314028314027
decorrelation: 0.05


(0.05, -0.1, 0.05)
0

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 3.9330432826567625
smooth_theta_bcg: 22.167852062588906
sparse_phi_sp: -0.33967191986581124
sparse_theta_sp: -1.914496314496314
decorrelation: 0.05
1

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 3.9330432826567625
smooth_theta_bcg: 22.167852062588906
sparse_phi_sp: -0.33967191986581124
sparse_theta_sp: -1.914496314496314
decorrelation: 0.05
2

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 3.9330432826567625
smooth_theta_bcg: 22.167852062588906
sparse_phi_sp: -0.33967191986581124
sparse_theta_sp: -1.914496314496314
decorrelation: 0.05

(0.05, -0.1, 0.1)
0

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 8.30309137449761
smooth_theta_bcg: 46.7987987987988
sparse_phi_sp: -0.33967191986581124
sparse_theta_sp: -1.914496314496314
decorrelation: 0.05
1

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 8.30309137449761
smooth_theta_bcg: 46.7987987987988
sparse_phi_sp: -0.33967191986581124
sparse_theta_sp: -1.914496314496314
decorrelation: 0.05
2

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 8.30309137449761
smooth_theta_bcg: 46.7987987987988
sparse_phi_sp: -0.33967191986581124
sparse_theta_sp: -1.914496314496314
decorrelation: 0.05



(0.1, -0.05, 0.05)
0

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 3.9330432826567625
smooth_theta_bcg: 22.167852062588906
sparse_phi_sp: -0.17792338659637733
sparse_theta_sp: -1.0028314028314027
decorrelation: 0.1
1

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 3.9330432826567625
smooth_theta_bcg: 22.167852062588906
sparse_phi_sp: -0.17792338659637733
sparse_theta_sp: -1.0028314028314027
decorrelation: 0.1
2

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 3.9330432826567625
smooth_theta_bcg: 22.167852062588906
sparse_phi_sp: -0.17792338659637733
sparse_theta_sp: -1.0028314028314027
decorrelation: 0.1

(0.1, -0.05, 0.1)
0

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 8.30309137449761
smooth_theta_bcg: 46.7987987987988
sparse_phi_sp: -0.17792338659637733
sparse_theta_sp: -1.0028314028314027
decorrelation: 0.1
1

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 8.30309137449761
smooth_theta_bcg: 46.7987987987988
sparse_phi_sp: -0.17792338659637733
sparse_theta_sp: -1.0028314028314027
decorrelation: 0.1
2

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 8.30309137449761
smooth_theta_bcg: 46.7987987987988
sparse_phi_sp: -0.17792338659637733
sparse_theta_sp: -1.0028314028314027
decorrelation: 0.1


(0.1, -0.1, 0.05)
0

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 3.9330432826567625
smooth_theta_bcg: 22.167852062588906
sparse_phi_sp: -0.33967191986581124
sparse_theta_sp: -1.914496314496314
decorrelation: 0.1
1

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 3.9330432826567625
smooth_theta_bcg: 22.167852062588906
sparse_phi_sp: -0.33967191986581124
sparse_theta_sp: -1.914496314496314
decorrelation: 0.1
2

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 3.9330432826567625
smooth_theta_bcg: 22.167852062588906
sparse_phi_sp: -0.33967191986581124
sparse_theta_sp: -1.914496314496314
decorrelation: 0.1

(0.1, -0.1, 0.1)
0

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 8.30309137449761
smooth_theta_bcg: 46.7987987987988
sparse_phi_sp: -0.33967191986581124
sparse_theta_sp: -1.914496314496314
decorrelation: 0.1
1

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 8.30309137449761
smooth_theta_bcg: 46.7987987987988
sparse_phi_sp: -0.33967191986581124
sparse_theta_sp: -1.914496314496314
decorrelation: 0.1
2

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 8.30309137449761
smooth_theta_bcg: 46.7987987987988
sparse_phi_sp: -0.33967191986581124
sparse_theta_sp: -1.914496314496314
decorrelation: 0.1



(0.01, -0.05, 0.05)
0

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 3.9330432826567625
smooth_theta_bcg: 22.167852062588906
sparse_phi_sp: -0.17792338659637733
sparse_theta_sp: -1.0028314028314027
decorrelation: 0.01
1

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 3.9330432826567625
smooth_theta_bcg: 22.167852062588906
sparse_phi_sp: -0.17792338659637733
sparse_theta_sp: -1.0028314028314027
decorrelation: 0.01
2

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 3.9330432826567625
smooth_theta_bcg: 22.167852062588906
sparse_phi_sp: -0.17792338659637733
sparse_theta_sp: -1.0028314028314027
decorrelation: 0.01

(0.01, -0.05, 0.1)
0

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 8.30309137449761
smooth_theta_bcg: 46.7987987987988
sparse_phi_sp: -0.17792338659637733
sparse_theta_sp: -1.0028314028314027
decorrelation: 0.01
1

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 8.30309137449761
smooth_theta_bcg: 46.7987987987988
sparse_phi_sp: -0.17792338659637733
sparse_theta_sp: -1.0028314028314027
decorrelation: 0.01
2

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 8.30309137449761
smooth_theta_bcg: 46.7987987987988
sparse_phi_sp: -0.17792338659637733
sparse_theta_sp: -1.0028314028314027
decorrelation: 0.01


(0.01, -0.1, 0.05)
0

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 3.9330432826567625
smooth_theta_bcg: 22.167852062588906
sparse_phi_sp: -0.33967191986581124
sparse_theta_sp: -1.914496314496314
decorrelation: 0.01
1

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 3.9330432826567625
smooth_theta_bcg: 22.167852062588906
sparse_phi_sp: -0.33967191986581124
sparse_theta_sp: -1.914496314496314
decorrelation: 0.01
2

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 3.9330432826567625
smooth_theta_bcg: 22.167852062588906
sparse_phi_sp: -0.33967191986581124
sparse_theta_sp: -1.914496314496314
decorrelation: 0.01

(0.01, -0.1, 0.1)
0

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 8.30309137449761
smooth_theta_bcg: 46.7987987987988
sparse_phi_sp: -0.33967191986581124
sparse_theta_sp: -1.914496314496314
decorrelation: 0.01
1

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 8.30309137449761
smooth_theta_bcg: 46.7987987987988
sparse_phi_sp: -0.33967191986581124
sparse_theta_sp: -1.914496314496314
decorrelation: 0.01
2

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi_bcg: 8.30309137449761
smooth_theta_bcg: 46.7987987987988
sparse_phi_sp: -0.33967191986581124
sparse_theta_sp: -1.914496314496314
decorrelation: 0.01

results

In [37]:
len(results)

16

In [38]:
for k, r in results.items():
    mean_ppl = sum(v['scores']['perplexity'] for v in r) / len(r)
    print(k, mean_ppl)

(0.02, -0.05, 0.05) 3341.3675130208335
(0.02, -0.05, 0.1) 3497.8352864583335
(0.02, -0.1, 0.05) 3486.6405436197915
(0.02, -0.1, 0.1) 3645.3518880208335
(0.05, -0.05, 0.05) 3367.4226888020835
(0.05, -0.05, 0.1) 3518.19677734375
(0.05, -0.1, 0.05) 3512.6874186197915
(0.05, -0.1, 0.1) 3666.226318359375
(0.1, -0.05, 0.05) 3442.3375651041665
(0.1, -0.05, 0.1) 3582.7361653645835
(0.1, -0.1, 0.05) 3589.3958333333335
(0.1, -0.1, 0.1) 3733.7527669270835
(0.01, -0.05, 0.05) 3335.7916666666665
(0.01, -0.05, 0.1) 3493.9044596354165
(0.01, -0.1, 0.05) 3480.2273763020835
(0.01, -0.1, 0.1) 3640.7910970052085

In [ ]:
# Best: (0.01, -0.05, 0.05) 3335.7916666666665

# Close: (0.02, -0.05, 0.05) 3341.3675130208335

In [20]:
# BEST_PARAMS[KnownModel.DECORRELATION] = {
#     'decorrelation_tau': 0.01,
#     'sparse_sp_tau': -0.05,
#     'smooth_bcg_tau': 0.05,
# }

BEST_PARAMS[KnownModel.ARTM] = {
    'decorrelation_tau': 0.01,
    'sparse_sp_tau': -0.05,
    'smooth_bcg_tau': 0.05,
}

## TLESS

In [19]:
PARAMS_EXPLORED[KnownModel.TLESS]

{}

In [20]:
results = []

for seed in range(NUM_TRAINS):
    print(seed)
    
    model = init_model_from_family(
        family=KnownModel.TLESS,
        dataset=dataset,
        main_modality=MAIN_MODALITY,
        num_topics=NUM_TOPICS,
        seed=seed,
    )
    scores = fit_and_compute_scores(model, dataset)
    results.append(scores)

0

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

1

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

2

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

In [22]:
results

[{'scores': {'perplexity': 3648.019287109375,
   'coherence_20': array([0.73268797]),
   'diversity_euclidean': 0.0828906236701155,
   'diversity_jensenshannon': 0.0828906236701155,
   'diversity_hellinger': 0.0828906236701155,
   'diversity_cosine': 0.0828906236701155},
  'topic_coherences': {0: 0.5748634448468164,
   1: 0.730467322022561,
   2: 0.4112179157799582,
   3: 1.008451239401693,
   4: 1.1553236136598417,
   5: 0.5280133176474108,
   6: 0.597173470430456,
   7: 0.4813047901914537,
   8: 0.8452729644551105,
   9: 1.1083068584696496,
   10: 1.0975959440604885,
   11: 0.5723046051892471,
   12: 0.8491850406145895,
   13: 0.5719212219989672,
   14: 0.4161534136724659,
   15: 0.9974945274670723,
   16: 1.3190569328602562,
   17: 0.4682329257973112,
   18: 0.5698427247201727,
   19: 0.35157720925244956}},
 {'scores': {'perplexity': 3635.931884765625,
   'coherence_20': array([0.71696431]),
   'diversity_euclidean': 0.08295491382261991,
   'diversity_jensenshannon': 0.08295491382261991,
   'diversity_hellinger': 0.08295491382261991,
   'diversity_cosine': 0.08295491382261991},
  'topic_coherences': {0: 0.6666678135251947,
   1: 0.4892540493275609,
   2: 0.4852906735949223,
   3: 0.3863905130669438,
   4: 0.41694614223169935,
   5: 0.6153864200234671,
   6: 0.5573224393024139,
   7: 0.9480924517060174,
   8: 0.5301703036265389,
   9: 0.8777929824772452,
   10: 0.8846143211150467,
   11: 0.6693726534326059,
   12: 0.9320228941975065,
   13: 0.8159414755974183,
   14: 0.9370278244420268,
   15: 1.3211190775142019,
   16: 1.1620695303566675,
   17: 0.6008092477426638,
   18: 0.4773958737914385,
   19: 0.5655995433192764}},
 {'scores': {'perplexity': 3647.86767578125,
   'coherence_20': array([0.69390432]),
   'diversity_euclidean': 0.08392579689251126,
   'diversity_jensenshannon': 0.08392579689251126,
   'diversity_hellinger': 0.08392579689251126,
   'diversity_cosine': 0.08392579689251126},
  'topic_coherences': {0: 0.496564356405894,
   1: 0.4138790887807972,
   2: 0.6911596340255958,
   3: 0.5677897675788931,
   4: 0.557643132573217,
   5: 0.5831162513535244,
   6: 0.564308426043763,
   7: 1.1494787278321532,
   8: 0.5828943829111827,
   9: 0.7367793100444147,
   10: 0.4086990647547675,
   11: 0.6454736410677601,
   12: 0.9194341876851237,
   13: 0.4148384077826576,
   14: 1.1205265946446734,
   15: 0.6440825955184442,
   16: 0.815735216484374,
   17: 0.7593906582824701,
   18: 0.5947176414910345,
   19: 1.2115753170240544}}]

In [ ]:
# Best:

In [30]:
BEST_PARAMS[KnownModel.TLESS] = None

## LDA

In [41]:
PARAMS_EXPLORED[KnownModel.LDA]

{'prior': ['symmetric', 'asymmetric', 'heuristic']}

In [42]:
results = dict()

for prior in PARAMS_EXPLORED[KnownModel.LDA]['prior']:
    key = prior
    results[key] = []

    print(key)

    for seed in range(NUM_TRAINS):
        print(seed)
        
        model = init_model_from_family(
            family=KnownModel.LDA,
            dataset=dataset,
            main_modality=MAIN_MODALITY,
            num_topics=NUM_TOPICS,
            seed=seed,
            model_params={'prior': prior}
        )

        for reg in model.regularizers.data:
            print(f"{reg}: {model.regularizers[reg].tau}")

        scores = fit_and_compute_scores(model, dataset)
        results[key].append(scores)

    print()

symmetric
0

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi: 0.05
smooth_theta: 0.05
1

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi: 0.05
smooth_theta: 0.05
2

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi: 0.05
smooth_theta: 0.05

asymmetric
0

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi: 0.05
smooth_theta_0: 0.12456869333982468
smooth_theta_1: 0.10180450975894928
smooth_theta_2: 0.08607485145330429
smooth_theta_3: 0.0745554119348526
smooth_theta_4: 0.06575533747673035
smooth_theta_5: 0.05881335958838463
smooth_theta_6: 0.053197186440229416
smooth_theta_7: 0.04856010526418686
smooth_theta_8: 0.04466661810874939
smooth_theta_9: 0.041351135820150375
smooth_theta_10: 0.038493841886520386
smooth_theta_11: 0.036005899310112
smooth_theta_12: 0.033820029348134995
smooth_theta_13: 0.03188437223434448
smooth_theta_14: 0.03015829436480999
smooth_theta_15: 0.02860950119793415
smooth_theta_16: 0.02721201814711094
smooth_theta_17: 0.025944700464606285
smooth_theta_18: 0.024790173396468163
smooth_theta_19: 0.023734018206596375
1

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi: 0.05
smooth_theta_0: 0.12456869333982468
smooth_theta_1: 0.10180450975894928
smooth_theta_2: 0.08607485145330429
smooth_theta_3: 0.0745554119348526
smooth_theta_4: 0.06575533747673035
smooth_theta_5: 0.05881335958838463
smooth_theta_6: 0.053197186440229416
smooth_theta_7: 0.04856010526418686
smooth_theta_8: 0.04466661810874939
smooth_theta_9: 0.041351135820150375
smooth_theta_10: 0.038493841886520386
smooth_theta_11: 0.036005899310112
smooth_theta_12: 0.033820029348134995
smooth_theta_13: 0.03188437223434448
smooth_theta_14: 0.03015829436480999
smooth_theta_15: 0.02860950119793415
smooth_theta_16: 0.02721201814711094
smooth_theta_17: 0.025944700464606285
smooth_theta_18: 0.024790173396468163
smooth_theta_19: 0.023734018206596375
2

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi: 0.05
smooth_theta_0: 0.12456869333982468
smooth_theta_1: 0.10180450975894928
smooth_theta_2: 0.08607485145330429
smooth_theta_3: 0.0745554119348526
smooth_theta_4: 0.06575533747673035
smooth_theta_5: 0.05881335958838463
smooth_theta_6: 0.053197186440229416
smooth_theta_7: 0.04856010526418686
smooth_theta_8: 0.04466661810874939
smooth_theta_9: 0.041351135820150375
smooth_theta_10: 0.038493841886520386
smooth_theta_11: 0.036005899310112
smooth_theta_12: 0.033820029348134995
smooth_theta_13: 0.03188437223434448
smooth_theta_14: 0.03015829436480999
smooth_theta_15: 0.02860950119793415
smooth_theta_16: 0.02721201814711094
smooth_theta_17: 0.025944700464606285
smooth_theta_18: 0.024790173396468163
smooth_theta_19: 0.023734018206596375

heuristic
0

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi: 0.01
smooth_theta: 2.5
1

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi: 0.01
smooth_theta: 2.5
2

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

smooth_phi: 0.01
smooth_theta: 2.5

In [43]:
results

{'symmetric': [{'scores': {'perplexity': 2994.8544921875,
    'coherence_20': array([0.72912617]),
    'diversity_euclidean': 0.04538816307890767,
    'diversity_jensenshannon': 0.04538816307890767,
    'diversity_hellinger': 0.04538816307890767,
    'diversity_cosine': 0.04538816307890767},
   'topic_coherences': {0: 0.4747744148677699,
    1: 0.7036357726509829,
    2: 0.6385750582879668,
    3: 0.8588277998967593,
    4: 0.8910872346278833,
    5: 0.8629812802644291,
    6: 0.6893087965800643,
    7: 0.5541064624279066,
    8: 0.8431573420660817,
    9: 0.922791744160493,
    10: 1.1066082291804975,
    11: 0.4860267452007646,
    12: 0.6664376516550651,
    13: 0.4953589831508357,
    14: 0.4460860341997396,
    15: 0.865571529527662,
    16: 1.0827362012402582,
    17: 0.6510241808664234,
    18: 0.7806403172775794,
    19: 0.5627876636567518}},
  {'scores': {'perplexity': 2964.62841796875,
    'coherence_20': array([0.742071]),
    'diversity_euclidean': 0.04512760284455174,
    'diversity_jensenshannon': 0.04512760284455174,
    'diversity_hellinger': 0.04512760284455174,
    'diversity_cosine': 0.04512760284455174},
   'topic_coherences': {0: 1.1442143716596225,
    1: 0.5034900546560508,
    2: 0.8262565946497734,
    3: 0.9117662268928527,
    4: 0.5952541032383496,
    5: 0.48978685531454025,
    6: 0.6695469497041255,
    7: 0.8048225170745222,
    8: 0.8227877433759665,
    9: 0.6250460840202919,
    10: 0.8255862969585086,
    11: 0.6803569249074239,
    12: 0.6484750360694165,
    13: 0.8811453104389715,
    14: 0.7915126172476877,
    15: 0.84225122969191,
    16: 0.9178575440071646,
    17: 0.6716898474066497,
    18: 0.43248483704048407,
    19: 0.7570888825433075}},
  {'scores': {'perplexity': 2980.66845703125,
    'coherence_20': array([0.70460157]),
    'diversity_euclidean': 0.04451127042224863,
    'diversity_jensenshannon': 0.04451127042224863,
    'diversity_hellinger': 0.04451127042224863,
    'diversity_cosine': 0.04451127042224863},
   'topic_coherences': {0: 0.47167496588589514,
    1: 0.5953173662389842,
    2: 0.6606268089015332,
    3: 0.5329561540699572,
    4: 0.5724808141188308,
    5: 0.8301164405678185,
    6: 0.5913901044507066,
    7: 0.8234151606986991,
    8: 0.6794040363003969,
    9: 0.7375871975628232,
    10: 0.6348061461420775,
    11: 0.814384427928395,
    12: 0.7692300943425668,
    13: 0.9409436630681554,
    14: 0.7253727245643558,
    15: 0.6364323398623727,
    16: 0.8626837079963781,
    17: 0.7889231504743159,
    18: 0.4971110167668628,
    19: 0.9271751524591798}}],
 'asymmetric': [{'scores': {'perplexity': 2993.755126953125,
    'coherence_20': array([0.73292549]),
    'diversity_euclidean': 0.04538899479069177,
    'diversity_jensenshannon': 0.04538899479069177,
    'diversity_hellinger': 0.04538899479069177,
    'diversity_cosine': 0.04538899479069177},
   'topic_coherences': {0: 0.4772561413893442,
    1: 0.7036357726509829,
    2: 0.6573907790150917,
    3: 0.8588277998967593,
    4: 0.9654644411924509,
    5: 0.8251875305788683,
    6: 0.6893087965800643,
    7: 0.5793923223679018,
    8: 0.8370377046623241,
    9: 0.9227917441604933,
    10: 1.0542404650842239,
    11: 0.48602674520076466,
    12: 0.6992695861295758,
    13: 0.5379394809574781,
    14: 0.4796282891468304,
    15: 0.865571529527662,
    16: 1.0827362012402582,
    17: 0.5933764101162737,
    18: 0.7806403172775794,
    19: 0.5627876636567518}},
  {'scores': {'perplexity': 2963.585205078125,
    'coherence_20': array([0.7452191]),
    'diversity_euclidean': 0.04515048907451432,
    'diversity_jensenshannon': 0.04515048907451432,
    'diversity_hellinger': 0.04515048907451432,
    'diversity_cosine': 0.04515048907451432},
   'topic_coherences': {0: 1.1442143716596227,
    1: 0.503490054656051,
    2: 0.8262565946497734,
    3: 0.9117662268928526,
    4: 0.5952541032383496,
    5: 0.48978685531454025,
    6: 0.6695469497041255,
    7: 0.8048225170745225,
    8: 0.8443943449581373,
    9: 0.6250460840202919,
    10: 0.8239188562664891,
    11: 0.6470154637723854,
    12: 0.6484750360694164,
    13: 0.8811453104389714,
    14: 0.7915126172476877,
    15: 0.9021675759036892,
    16: 0.9178575440071646,
    17: 0.6645863312073103,
    18: 0.43248483704048407,
    19: 0.7806403172775794}},
  {'scores': {'perplexity': 2976.062255859375,
    'coherence_20': array([0.71278118]),
    'diversity_euclidean': 0.044630634007562675,
    'diversity_jensenshannon': 0.044630634007562675,
    'diversity_hellinger': 0.044630634007562675,
    'diversity_cosine': 0.044630634007562675},
   'topic_coherences': {0: 0.433744436141964,
    1: 0.7430383528336729,
    2: 0.7436064185615305,
    3: 0.5329561540699573,
    4: 0.5246588114407297,
    5: 0.8301164405678185,
    6: 0.5913901044507068,
    7: 0.8166548570856375,
    8: 0.6853311657398368,
    9: 0.7375871975628231,
    10: 0.6182030232939149,
    11: 0.7750769760761478,
    12: 0.7692300943425668,
    13: 1.0386836823456178,
    14: 0.7253727245643558,
    15: 0.6789608257484714,
    16: 0.8626837079963781,
    17: 0.7307910753870788,
    18: 0.4903623541605465,
    19: 0.9271751524591798}}],
 'heuristic': [{'scores': {'perplexity': 3176.1005859375,
    'coherence_20': array([0.70687961]),
    'diversity_euclidean': 0.05133095835891814,
    'diversity_jensenshannon': 0.05133095835891814,
    'diversity_hellinger': 0.05133095835891814,
    'diversity_cosine': 0.05133095835891814},
   'topic_coherences': {0: 0.4974252321655629,
    1: 0.7550203355673487,
    2: 0.4173411885570261,
    3: 0.8268468694998701,
    4: 0.9073620736860167,
    5: 0.8777531675128035,
    6: 0.5851749557052368,
    7: 0.43509247418960406,
    8: 0.7718687945829318,
    9: 0.8693767940376201,
    10: 0.9385092604860106,
    11: 0.597835070339396,
    12: 0.7772058602723013,
    13: 0.5332161102352113,
    14: 0.4868425901837586,
    15: 0.8816558372302211,
    16: 1.1804735057219429,
    17: 0.44362891923759745,
    18: 0.7258675571683973,
    19: 0.6290956821045214}},
  {'scores': {'perplexity': 3146.78125,
    'coherence_20': array([0.70712957]),
    'diversity_euclidean': 0.05027597984909801,
    'diversity_jensenshannon': 0.05027597984909801,
    'diversity_hellinger': 0.05027597984909801,
    'diversity_cosine': 0.05027597984909801},
   'topic_coherences': {0: 1.000104445664396,
    1: 0.4451892966938999,
    2: 0.6106287645015068,
    3: 0.5235882118125684,
    4: 0.5845277294150134,
    5: 0.5561402325998215,
    6: 0.6179836292443553,
    7: 0.8658789178918405,
    8: 0.6920171301462529,
    9: 0.6640932563604885,
    10: 0.879156140202416,
    11: 0.6684234297625551,
    12: 0.6874820103238586,
    13: 0.5990238544713098,
    14: 0.872505985965398,
    15: 1.0289024889363758,
    16: 0.9788804109927685,
    17: 0.6922628296484303,
    18: 0.4843890464904331,
    19: 0.69141352448545}},
  {'scores': {'perplexity': 3146.50830078125,
    'coherence_20': array([0.69388549]),
    'diversity_euclidean': 0.051064515019526004,
    'diversity_jensenshannon': 0.051064515019526004,
    'diversity_hellinger': 0.051064515019526004,
    'diversity_cosine': 0.051064515019526004},
   'topic_coherences': {0: 0.4044446234128667,
    1: 0.5513697060425142,
    2: 0.7624815715858846,
    3: 0.5329561540699573,
    4: 0.4853519622228599,
    5: 0.7623023597421602,
    6: 0.5661646419259211,
    7: 0.927860174075586,
    8: 0.5731384015160158,
    9: 0.7022989030709612,
    10: 0.5807764643611681,
    11: 0.709491814398746,
    12: 0.78989729230221,
    13: 0.9117274004104524,
    14: 0.8106242500454631,
    15: 0.71606873092343,
    16: 0.837440475254461,
    17: 0.7610027636905285,
    18: 0.5222817322308653,
    19: 0.970030394183081}}]}

In [44]:
for k, r in results.items():
    mean_ppl = sum(v['scores']['perplexity'] for v in r) / len(r)
    print(k, mean_ppl)

symmetric 2980.0504557291665
asymmetric 2977.8008626302085
heuristic 3156.46337890625

In [ ]:
# Best: asymmetric 2977.8008626302085

In [31]:
BEST_PARAMS[KnownModel.LDA] = {
    'prior': 'asymmetric',
}

In [37]:
BEST_PARAMS

{<KnownModel.PLSA: 'PLSA'>: None,
 <KnownModel.DECORRELATION: 'decorrelation'>: {'decorrelation_tau': 0.01,
  'sparse_sp_tau': -0.05,
  'smooth_bcg_tau': 0.05},
 <KnownModel.TLESS: 'TARTM'>: None,
 <KnownModel.SPARSE: 'sparse'>: {'sparse_sp_tau': -0.05,
  'smooth_bcg_tau': 0.05},
 <KnownModel.LDA: 'LDA'>: {'prior': 'asymmetric'}}

In [48]:
BEST_PARAMS = {KnownModel.PLSA: None,
     KnownModel.DECORRELATION: {'decorrelation_tau': 0.01,
      'sparse_sp_tau': -0.05,
      'smooth_bcg_tau': 0.05},
     KnownModel.TLESS: None,
     KnownModel.SPARSE: {'sparse_sp_tau': -0.05,
      'smooth_bcg_tau': 0.05},
     KnownModel.LDA: {'prior': 'asymmetric'}}

In [49]:
BEST_PARAMS

{<KnownModel.PLSA: 'PLSA'>: None,
 <KnownModel.DECORRELATION: 'decorrelation'>: {'decorrelation_tau': 0.01,
  'sparse_sp_tau': -0.05,
  'smooth_bcg_tau': 0.05},
 <KnownModel.TLESS: 'TARTM'>: None,
 <KnownModel.SPARSE: 'sparse'>: {'sparse_sp_tau': -0.05,
  'smooth_bcg_tau': 0.05},
 <KnownModel.LDA: 'LDA'>: {'prior': 'asymmetric'}}

In [50]:
import json
import warnings

warnings.simplefilter('ignore', UserWarning)

from tqdm.notebook import tqdm

In [47]:
scores.keys()

dict_keys(['scores', 'topic_coherences', 'topic_coherences_toplen_ptw', 'topic_coherences_topden_ptw'])

In [51]:
NUM_TRAINS = 20  # 100
COHERENCES = {
    'topic_coherences': list(),
    # 'topic_coherences_toplen_pwt': list(),
    'topic_coherences_toplen_ptw': list(),
    'topic_coherences_topden_ptw': list(),
}

In [52]:
SAVE_FOLDER = 'results_intra/postnauka'

! mkdir -p $SAVE_FOLDER

In [53]:
! ls

20_Newsgroups__internals
_ARTM-Models-20NewsGroups-T20.ipynb
ARTM-Models-20NewsGroups-T20.ipynb
ARTM-Models-20NewsGroups-T50.ipynb
ARTM-Models-MKB10-T20-Copy1.ipynb
ARTM-Models-MKB10-T20.ipynb
ARTM-Models-MKB10-T50.ipynb
ARTM-Models-PostNauka-T20-Intra.ipynb
ARTM-Models-PostNauka-T20.ipynb
ARTM-Models-PostNauka-T50.ipynb
ARTM-Models-RTL-Wiki-Person-T20-Copy1.ipynb
ARTM-Models-RTL-Wiki-Person-T20.ipynb
ARTM-Models-RTL-Wiki-Person-T50-Copy1.ipynb
ARTM-Models-RTL-Wiki-Person-T50.ipynb
ARTM-Models-RuWikiGood-T20.ipynb
ARTM-Models-RuWikiGood-T50.ipynb
BERTopic
BERTopic-Coherence-20NewsGroups-T20.ipynb
BERTopic-Coherence-20NewsGroups-T50.ipynb
BERTopic-Coherence-MKB10-T20.ipynb
BERTopic-Coherence-MKB10-T50.ipynb
BERTopic-Coherence-PostNauka-T20.ipynb
BERTopic-Coherence-PostNauka-T50.ipynb
BERTopic-Coherence-RTL-Wiki-Person-T20.ipynb
BERTopic-Coherence-RTL-Wiki-Person-T50.ipynb
BERTopic-Coherence-RuWikiGood-T20.ipynb
BERTopic-Coherence-RuWikiGood-T50-2.ipynb
_BERTopic-Coherence-RuWikiGood-T50.ipynb
BERTopic-Coherence-RuWikiGood-T50.ipynb
Datasets-and-Coherence-Plan.ipynb
Experiment_v2.ipynb
Experiment_v3.ipynb
find_cohs.sh
Good_RU_Wiki__internals
Iterative-Model-20NewsGroups-T20.ipynb
Iterative-Model-20NewsGroups-T20-Orig.ipynb
Iterative-Model-20NewsGroups-T50.ipynb
Iterative-Model-MKB10-T20.ipynb
Iterative-Model-MKB10-T50.ipynb
Iterative-Model-PostNauka-T20.ipynb
Iterative-Model-PostNauka-T50.ipynb
Iterative-Model-PostNauka-T50.py
Iterative-Model-RTL-Wiki-Person-T20.ipynb
Iterative-Model-RTL-Wiki-Person-T50.ipynb
Iterative-Model-RuWikiGood-T20.ipynb
Iterative-Model-RuWikiGood-T50.ipynb
MKB_10__internals
phi1.batch
Post_Science__internals
results_intra
Results-T20-T50.ipynb
RTL_Wiki_Person__internals
test_bt_results_test.json
test_dict.txt
TestTopicNet.ipynb
TopicBank-20NewsGroups-T20.ipynb
TopicBank-20NewsGroups-T50.ipynb
TopicBank-MKB10-T20.ipynb
TopicBank-MKB10-T50.ipynb
TopicBank-PostNauka-T20-Copy1.ipynb
TopicBank-PostNauka-T20.ipynb
TopicBank-PostNauka-T50.ipynb
TopicBank-RTL-Wiki-Person-T20.ipynb
TopicBank-RTL-Wiki-Person-T50.ipynb
TopicBank-RuWikiGood-T20-Copy1.ipynb
TopicBank-RuWikiGood-T20-Copy2.ipynb
TopicBank-RuWikiGood-T20.ipynb
TopicBank-RuWikiGood-T50.ipynb
Topic-Thetaless-Regularizer.ipynb

In [54]:
! ls $SAVE_FOLDER

plsa_with_cohs.json

In [55]:
# PLSA

start = time.time()

scores = []

# for seed in tqdm(range(NUM_TRAINS), total=NUM_TRAINS):
for seed in range(NUM_TRAINS):
    if seed != NUM_TRAINS - 1:
        print(seed, end=' ')
    else:
        print(seed)

    model = init_model_from_family(
        family=KnownModel.PLSA,
        dataset=dataset,
        main_modality=MAIN_MODALITY,
        num_topics=NUM_TOPICS,
        seed=seed,
    )
    results = fit_and_compute_scores(model, dataset)
    # scores.append(results['scores'])
    scores.append(results)

    # COHERENCES.extend(
    #     list(results['topic_coherences'].values())
    # )

    for k in COHERENCES:
        COHERENCES[k].extend(
            list(results[k].values())
        )

end = time.time()

print(f'Elapsed: {(end - start) / 60} min')

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19
Elapsed: 76.59856515725454 min

In [56]:
1

1

In [81]:
scores[-1]

{'scores': {'perplexity': 2481.011474609375,
  'coherence_20': array([0.69311395]),
  'toplen_pwt': 2.2419136748104247,
  'toplen_ptw': 2.2419136748104247,
  'topden_ptw': 0.7597696858931959,
  'diversity_euclidean': 0.051507117819155505,
  'diversity_jensenshannon': 0.5886639008885491,
  'diversity_hellinger': 0.6731241634368506,
  'diversity_cosine': 0.716436824471558},
 'topic_coherences': {0: 0.5133376224986828,
  1: 0.5636795412880685,
  2: 0.734942197901494,
  3: 1.106716850102659,
  4: 0.5436879375765777,
  5: 0.5289428294650398,
  6: 0.6085041139511407,
  7: 0.4131289730452274,
  8: 0.7236630293837298,
  9: 0.5207321747706948,
  10: 0.7016884077306269,
  11: 0.8370214440333109,
  12: 0.5981763032489854,
  13: 0.7666095142248066,
  14: 0.40974011652763215,
  15: 0.7858678342478069,
  16: 0.8803072445751484,
  17: 1.240285463956784,
  18: 0.8492280572719985,
  19: 0.5360192650721023},
 'topic_coherences_toplen_pwt': {0: 2.251163602635274,
  1: 2.5048643275639324,
  2: 2.3371964856594496,
  3: 2.8676723711508867,
  4: 1.8515397689440516,
  5: 1.7752883045582537,
  6: 2.7262990532561586,
  7: 1.869784151211071,
  8: 1.7280146408125303,
  9: 1.9607622565934868,
  10: 2.53860152762334,
  11: 2.195249517686346,
  12: 2.131017087374331,
  13: 2.232663746985575,
  14: 2.8470861010898703,
  15: 2.091585667140941,
  16: 2.5214941832462605,
  17: 3.167397536550704,
  18: 2.2944217927046813,
  19: 2.1216446608130584},
 'topic_coherences_toplen_ptw': {0: 2.251163602635274,
  1: 2.5048643275639324,
  2: 2.3371964856594496,
  3: 2.8676723711508867,
  4: 1.8515397689440516,
  5: 1.7752883045582537,
  6: 2.7262990532561586,
  7: 1.869784151211071,
  8: 1.7280146408125303,
  9: 1.9607622565934868,
  10: 2.53860152762334,
  11: 2.195249517686346,
  12: 2.131017087374331,
  13: 2.232663746985575,
  14: 2.8470861010898703,
  15: 2.091585667140941,
  16: 2.5214941832462605,
  17: 3.167397536550704,
  18: 2.2944217927046813,
  19: 2.1216446608130584},
 'topic_coherences_topden_ptw': {0: 0.8119231124981535,
  1: 0.7668042397111705,
  2: 0.8114152676178171,
  3: 0.7015114793421571,
  4: 0.7260438770038856,
  5: 0.7264713292155247,
  6: 0.7646698334361711,
  7: 0.6986935584071242,
  8: 0.7584820256808851,
  9: 0.7610573461055067,
  10: 0.8312848672891899,
  11: 0.7532851636539988,
  12: 0.7516471876772629,
  13: 0.8767615313475791,
  14: 0.7535645436902896,
  15: 0.7864462055840722,
  16: 0.7893960036946134,
  17: 0.7659069980238473,
  18: 0.7521681132067763,
  19: 0.7199311218983038}}

In [82]:
scores

[{'scores': {'perplexity': 2474.488525390625,
   'coherence_20': array([0.73062234]),
   'toplen_pwt': 2.2222272562846417,
   'toplen_ptw': 2.2222272562846417,
   'topden_ptw': 0.7928443137523,
   'diversity_euclidean': 0.05432938655690007,
   'diversity_jensenshannon': 0.6000053864026371,
   'diversity_hellinger': 0.6857673790274449,
   'diversity_cosine': 0.7377318963938092},
  'topic_coherences': {0: 0.4682133200037822,
   1: 0.5525499039748306,
   2: 0.3662412591097539,
   3: 0.7660746688638103,
   4: 0.6599584504901529,
   5: 1.2151843412918593,
   6: 0.784374938331295,
   7: 0.6583524284174844,
   8: 0.7558873960285204,
   9: 0.8872288724338003,
   10: 0.5060579830596448,
   11: 1.1643195534386466,
   12: 1.0551562205101295,
   13: 0.6667121824386473,
   14: 0.34910355580365166,
   15: 0.7823822821267535,
   16: 1.0022462210267367,
   17: 0.8400496475709041,
   18: 0.706545516531718,
   19: 0.425808078140945},
  'topic_coherences_toplen_pwt': {0: 2.0956432149414908,
   1: 2.1535240947120737,
   2: 2.8292371579349185,
   3: 1.87571387898929,
   4: 2.346451870009993,
   5: 3.226761710980802,
   6: 1.9268920456173568,
   7: 1.6180633470149492,
   8: 2.1603641420965194,
   9: 2.111364111726634,
   10: 1.8843975960799404,
   11: 2.67100155859519,
   12: 2.0041191448861375,
   13: 2.2960403613814058,
   14: 2.29035348424422,
   15: 2.2511018392627333,
   16: 3.2202474401611747,
   17: 2.1978257467664424,
   18: 2.246628765802841,
   19: 3.189557861813141},
  'topic_coherences_toplen_ptw': {0: 2.0956432149414908,
   1: 2.1535240947120737,
   2: 2.8292371579349185,
   3: 1.87571387898929,
   4: 2.346451870009993,
   5: 3.226761710980802,
   6: 1.9268920456173568,
   7: 1.6180633470149492,
   8: 2.1603641420965194,
   9: 2.111364111726634,
   10: 1.8843975960799404,
   11: 2.67100155859519,
   12: 2.0041191448861375,
   13: 2.2960403613814058,
   14: 2.29035348424422,
   15: 2.2511018392627333,
   16: 3.2202474401611747,
   17: 2.1978257467664424,
   18: 2.246628765802841,
   19: 3.189557861813141},
  'topic_coherences_topden_ptw': {0: 0.789633218462765,
   1: 0.7559288346846679,
   2: 0.8722740979953629,
   3: 0.8514701787001846,
   4: 0.7357710438870241,
   5: 0.7997852529539465,
   6: 0.7778503802615537,
   7: 0.730388121416676,
   8: 0.7675140677957543,
   9: 0.8531205064926973,
   10: 0.6444693914100562,
   11: 0.7265469723462264,
   12: 0.8373283660683627,
   13: 0.7586853596009673,
   14: 0.8129853091789907,
   15: 0.7984749882437627,
   16: 0.9248024965945786,
   17: 0.7995770252072332,
   18: 0.7960554090418351,
   19: 0.7363659655699476}},
 {'scores': {'perplexity': 2494.68310546875,
   'coherence_20': array([0.69067969]),
   'toplen_pwt': 2.1446847938806393,
   'toplen_ptw': 2.1446847938806393,
   'topden_ptw': 0.7663765814041159,
   'diversity_euclidean': 0.05193674176128434,
   'diversity_jensenshannon': 0.5926559623044345,
   'diversity_hellinger': 0.6774095253824262,
   'diversity_cosine': 0.7224775835975328},
  'topic_coherences': {0: 1.3242652199570513,
   1: 0.5722318709679326,
   2: 0.5943743640997695,
   3: 0.690679616728474,
   4: 0.539257289894177,
   5: 0.37097788905119117,
   6: 0.4497302529498234,
   7: 0.7614405692714401,
   8: 0.5175776821765838,
   9: 0.6621937385963241,
   10: 0.8423462341482593,
   11: 0.708637600018853,
   12: 0.41846542738493603,
   13: 0.6254327699417653,
   14: 1.213484947540808,
   15: 0.8842201698926271,
   16: 0.7557284244360403,
   17: 0.6408219757743792,
   18: 0.511304302409602,
   19: 0.730423536324743},
  'topic_coherences_toplen_pwt': {0: 2.5872781976785193,
   1: 2.5301008438108754,
   2: 2.0483876545399955,
   3: 1.757537800853324,
   4: 2.1071998379914048,
   5: 3.2230577059958994,
   6: 1.7914914507841155,
   7: 1.898844103458519,
   8: 2.187829678156063,
   9: 2.052452837070328,
   10: 1.756857868397566,
   11: 2.0791756852931136,
   12: 2.1821697497698738,
   13: 2.204497776758421,
   14: 3.4643496786478556,
   15: 3.4035513172857508,
   16: 1.9624732390221462,
   17: 1.8652626322777506,
   18: 2.4603657448354186,
   19: 2.243793355189312},
  'topic_coherences_toplen_ptw': {0: 2.5872781976785193,
   1: 2.5301008438108754,
   2: 2.0483876545399955,
   3: 1.757537800853324,
   4: 2.1071998379914048,
   5: 3.2230577059958994,
   6: 1.7914914507841155,
   7: 1.898844103458519,
   8: 2.187829678156063,
   9: 2.052452837070328,
   10: 1.756857868397566,
   11: 2.0791756852931136,
   12: 2.1821697497698738,
   13: 2.204497776758421,
   14: 3.4643496786478556,
   15: 3.4035513172857508,
   16: 1.9624732390221462,
   17: 1.8652626322777506,
   18: 2.4603657448354186,
   19: 2.243793355189312},
  'topic_coherences_topden_ptw': {0: 0.7084018748436884,
   1: 0.7929540404228583,
   2: 0.688437958721437,
   3: 0.7342908444407088,
   4: 0.8918059664289733,
   5: 0.7285882026948914,
   6: 0.749705046219392,
   7: 0.7635083913924824,
   8: 0.7034044486524245,
   9: 0.7773462417888262,
   10: 0.7559884353271784,
   11: 0.7820968927905683,
   12: 0.6926500538853945,
   13: 0.8352295921156363,
   14: 0.837429752579545,
   15: 0.9107125661589411,
   16: 0.788015621842787,
   17: 0.7133519250201763,
   18: 0.7692447714157493,
   19: 0.785870392849696}},
 {'scores': {'perplexity': 2495.913330078125,
   'coherence_20': array([0.63670894]),
   'toplen_pwt': 2.1597401559488802,
   'toplen_ptw': 2.1597401559488802,
   'topden_ptw': 0.7694587940645519,
   'diversity_euclidean': 0.052710599762649385,
   'diversity_jensenshannon': 0.5941837328427876,
   'diversity_hellinger': 0.6795533542091925,
   'diversity_cosine': 0.7320604420132084},
  'topic_coherences': {0: 0.5020493941601943,
   1: 0.5664712103832005,
   2: 0.7641518298953729,
   3: 0.46302107182953806,
   4: 0.45959968414533464,
   5: 0.7573422106377864,
   6: 0.4813143584488271,
   7: 0.7014214878526538,
   8: 0.7458214688111245,
   9: 0.690396803305276,
   10: 0.44212855569927956,
   11: 0.6681510538091537,
   12: 0.7054424723174707,
   13: 0.9584424382756616,
   14: 0.8572058868003847,
   15: 0.5129876628656329,
   16: 0.6775924074375445,
   17: 0.33548710692454065,
   18: 0.36750835522159697,
   19: 1.077643308280305},
  'topic_coherences_toplen_pwt': {0: 2.3105633196699893,
   1: 2.1514626854819885,
   2: 2.168017626415772,
   3: 2.127727695999189,
   4: 2.0398502201277897,
   5: 1.7610124373652989,
   6: 2.369576954883002,
   7: 2.125822891740122,
   8: 2.8800814278048206,
   9: 1.7463323899688443,
   10: 2.1746838587668154,
   11: 2.4083365172606217,
   12: 2.113906581392728,
   13: 3.2885496143196065,
   14: 1.8135335545294085,
   15: 2.352726661067561,
   16: 1.7218100360612218,
   17: 1.9119422075705046,
   18: 2.6915132675653997,
   19: 3.037930197597021},
  'topic_coherences_toplen_ptw': {0: 2.3105633196699893,
   1: 2.1514626854819885,
   2: 2.168017626415772,
   3: 2.127727695999189,
   4: 2.0398502201277897,
   5: 1.7610124373652989,
   6: 2.369576954883002,
   7: 2.125822891740122,
   8: 2.8800814278048206,
   9: 1.7463323899688443,
   10: 2.1746838587668154,
   11: 2.4083365172606217,
   12: 2.113906581392728,
   13: 3.2885496143196065,
   14: 1.8135335545294085,
   15: 2.352726661067561,
   16: 1.7218100360612218,
   17: 1.9119422075705046,
   18: 2.6915132675653997,
   19: 3.037930197597021},
  'topic_coherences_topden_ptw': {0: 0.8293268684924109,
   1: 0.7717112397043618,
   2: 0.8086134232353259,
   3: 0.7847287585671001,
   4: 0.7554179470918776,
   5: 0.7265569368037506,
   6: 0.7732130525157231,
   7: 0.7615547337537759,
   8: 0.8916838412857828,
   9: 0.7276881822327845,
   10: 0.6943325564711605,
   11: 0.7770877657656654,
   12: 0.767206348424742,
   13: 0.808541374072554,
   14: 0.782452257753379,
   15: 0.7143405698028532,
   16: 0.7419202345984011,
   17: 0.7421217283865098,
   18: 0.733369670814351,
   19: 0.8518577133000184}},
 {'scores': {'perplexity': 2494.03759765625,
   'coherence_20': array([0.67709643]),
   'toplen_pwt': 2.189404645926838,
   'toplen_ptw': 2.189404645926838,
   'topden_ptw': 0.7812183656429819,
   'diversity_euclidean': 0.053041270020065236,
   'diversity_jensenshannon': 0.5939587892603446,
   'diversity_hellinger': 0.6786459156826098,
   'diversity_cosine': 0.7277789817619483},
  'topic_coherences': {0: 0.6606005009754925,
   1: 0.6911349597068152,
   2: 0.6231606326700864,
   3: 0.602447688744272,
   4: 0.5203521576607764,
   5: 0.3622428141252291,
   6: 0.5827720584803182,
   7: 0.35997028875398135,
   8: 1.3766403070984696,
   9: 0.5621764337455439,
   10: 0.41315020284998105,
   11: 0.530748137476179,
   12: 0.7175148435323769,
   13: 0.707353410741158,
   14: 0.5749365154826165,
   15: 0.48480721708238594,
   16: 0.8668679392519993,
   17: 0.784760180661277,
   18: 1.0643202782131924,
   19: 1.055972066674802},
  'topic_coherences_toplen_pwt': {0: 2.1275937088576327,
   1: 2.18225325820167,
   2: 2.161032703201307,
   3: 1.6440081419893138,
   4: 1.8938701316711666,
   5: 2.644737292868619,
   6: 1.7620233980400382,
   7: 2.4633104910845747,
   8: 2.8944302718864927,
   9: 2.582508657311949,
   10: 2.1863316546932037,
   11: 1.993788643173034,
   12: 2.1924776371604726,
   13: 2.096405993334583,
   14: 1.9012815447255136,
   15: 2.4914636516909963,
   16: 2.2917844562940113,
   17: 2.370911995550846,
   18: 3.0036983229648917,
   19: 3.1571823859914554},
  'topic_coherences_toplen_ptw': {0: 2.1275937088576327,
   1: 2.18225325820167,
   2: 2.161032703201307,
   3: 1.6440081419893138,
   4: 1.8938701316711666,
   5: 2.644737292868619,
   6: 1.7620233980400382,
   7: 2.4633104910845747,
   8: 2.8944302718864927,
   9: 2.582508657311949,
   10: 2.1863316546932037,
   11: 1.993788643173034,
   12: 2.1924776371604726,
   13: 2.096405993334583,
   14: 1.9012815447255136,
   15: 2.4914636516909963,
   16: 2.2917844562940113,
   17: 2.370911995550846,
   18: 3.0036983229648917,
   19: 3.1571823859914554},
  'topic_coherences_topden_ptw': {0: 0.785149200567653,
   1: 0.7287083961095554,
   2: 0.7851832326527616,
   3: 0.747711647095255,
   4: 0.7078114896335376,
   5: 0.6821465486883931,
   6: 0.7772875307183107,
   7: 0.7685683462148338,
   8: 0.7876459748367921,
   9: 0.8308250161619711,
   10: 0.8781042611881438,
   11: 0.7522761679373076,
   12: 0.787366901957808,
   13: 0.8250789437085078,
   14: 0.7323754558687581,
   15: 0.734453645547618,
   16: 0.8405091267593533,
   17: 0.7883343717762068,
   18: 0.9116423738547501,
   19: 0.7140372399361921}},
 {'scores': {'perplexity': 2481.011474609375,
   'coherence_20': array([0.69311395]),
   'toplen_pwt': 2.2419136748104247,
   'toplen_ptw': 2.2419136748104247,
   'topden_ptw': 0.7597696858931959,
   'diversity_euclidean': 0.051507117819155505,
   'diversity_jensenshannon': 0.5886639008885491,
   'diversity_hellinger': 0.6731241634368506,
   'diversity_cosine': 0.716436824471558},
  'topic_coherences': {0: 0.5133376224986828,
   1: 0.5636795412880685,
   2: 0.734942197901494,
   3: 1.106716850102659,
   4: 0.5436879375765777,
   5: 0.5289428294650398,
   6: 0.6085041139511407,
   7: 0.4131289730452274,
   8: 0.7236630293837298,
   9: 0.5207321747706948,
   10: 0.7016884077306269,
   11: 0.8370214440333109,
   12: 0.5981763032489854,
   13: 0.7666095142248066,
   14: 0.40974011652763215,
   15: 0.7858678342478069,
   16: 0.8803072445751484,
   17: 1.240285463956784,
   18: 0.8492280572719985,
   19: 0.5360192650721023},
  'topic_coherences_toplen_pwt': {0: 2.251163602635274,
   1: 2.5048643275639324,
   2: 2.3371964856594496,
   3: 2.8676723711508867,
   4: 1.8515397689440516,
   5: 1.7752883045582537,
   6: 2.7262990532561586,
   7: 1.869784151211071,
   8: 1.7280146408125303,
   9: 1.9607622565934868,
   10: 2.53860152762334,
   11: 2.195249517686346,
   12: 2.131017087374331,
   13: 2.232663746985575,
   14: 2.8470861010898703,
   15: 2.091585667140941,
   16: 2.5214941832462605,
   17: 3.167397536550704,
   18: 2.2944217927046813,
   19: 2.1216446608130584},
  'topic_coherences_toplen_ptw': {0: 2.251163602635274,
   1: 2.5048643275639324,
   2: 2.3371964856594496,
   3: 2.8676723711508867,
   4: 1.8515397689440516,
   5: 1.7752883045582537,
   6: 2.7262990532561586,
   7: 1.869784151211071,
   8: 1.7280146408125303,
   9: 1.9607622565934868,
   10: 2.53860152762334,
   11: 2.195249517686346,
   12: 2.131017087374331,
   13: 2.232663746985575,
   14: 2.8470861010898703,
   15: 2.091585667140941,
   16: 2.5214941832462605,
   17: 3.167397536550704,
   18: 2.2944217927046813,
   19: 2.1216446608130584},
  'topic_coherences_topden_ptw': {0: 0.8119231124981535,
   1: 0.7668042397111705,
   2: 0.8114152676178171,
   3: 0.7015114793421571,
   4: 0.7260438770038856,
   5: 0.7264713292155247,
   6: 0.7646698334361711,
   7: 0.6986935584071242,
   8: 0.7584820256808851,
   9: 0.7610573461055067,
   10: 0.8312848672891899,
   11: 0.7532851636539988,
   12: 0.7516471876772629,
   13: 0.8767615313475791,
   14: 0.7535645436902896,
   15: 0.7864462055840722,
   16: 0.7893960036946134,
   17: 0.7659069980238473,
   18: 0.7521681132067763,
   19: 0.7199311218983038}}]

In [57]:
# for s in scores:
#     s['coherence_20'] = float(s['coherence_20'])

for s in scores:
    s['scores']['coherence_20'] = float(s['scores']['coherence_20'])

In [58]:
scores[0]

{'scores': {'perplexity': 2474.488525390625,
  'coherence_20': 0.7306223409796534,
  'toplen_ptw': 2.2222272562846417,
  'topden_ptw': 0.4862072599670759,
  'diversity_euclidean': 0.05432938184650551,
  'diversity_jensenshannon': 0.6000053797380491,
  'diversity_hellinger': 0.6857673609277269,
  'diversity_cosine': 0.7377318746693401},
 'topic_coherences': {0: 0.4682133200037822,
  1: 0.5525499039748306,
  2: 0.3662412591097539,
  3: 0.7660746688638103,
  4: 0.6599584504901529,
  5: 1.2151843412918593,
  6: 0.784374938331295,
  7: 0.6583524284174844,
  8: 0.7558873960285204,
  9: 0.8872288724338003,
  10: 0.5060579830596448,
  11: 1.1643195534386466,
  12: 1.0551562205101295,
  13: 0.6667121824386473,
  14: 0.34910355580365166,
  15: 0.7823822821267535,
  16: 1.0022462210267367,
  17: 0.8400496475709041,
  18: 0.706545516531718,
  19: 0.425808078140945},
 'topic_coherences_toplen_ptw': {0: 2.0956432149414908,
  1: 2.1535240947120737,
  2: 2.8292371579349185,
  3: 1.87571387898929,
  4: 2.346451870009993,
  5: 3.226761710980802,
  6: 1.9268920456173568,
  7: 1.6180633470149492,
  8: 2.1603641420965194,
  9: 2.111364111726634,
  10: 1.8843975960799404,
  11: 2.67100155859519,
  12: 2.0041191448861375,
  13: 2.2960403613814058,
  14: 2.29035348424422,
  15: 2.2511018392627333,
  16: 3.2202474401611747,
  17: 2.1978257467664424,
  18: 2.246628765802841,
  19: 3.189557861813141},
 'topic_coherences_topden_ptw': {0: 0.4925668686414926,
  1: 0.46696705579886877,
  2: 0.4983295065770929,
  3: 0.5608629688169506,
  4: 0.45431590652566406,
  5: 0.4846405106808665,
  6: 0.4811761912929174,
  7: 0.47306922706645943,
  8: 0.4763528424433685,
  9: 0.538244037690487,
  10: 0.3880339855067129,
  11: 0.44699508715643227,
  12: 0.5527104669441544,
  13: 0.4649797741703262,
  14: 0.4877740092532853,
  15: 0.5050110415464591,
  16: 0.5583022055602739,
  17: 0.4943657012570345,
  18: 0.4937332013500637,
  19: 0.4260094082478372}}

In [59]:
with open(SAVE_FOLDER + '/plsa_with_cohs.json', 'w') as f:
    f.write(
        json.dumps(scores, indent=4)
    )

In [60]:
COHERENCES

{'topic_coherences': [0.4682133200037822,
  0.5525499039748306,
  0.3662412591097539,
  0.7660746688638103,
  0.6599584504901529,
  1.2151843412918593,
  0.784374938331295,
  0.6583524284174844,
  0.7558873960285204,
  0.8872288724338003,
  0.5060579830596448,
  1.1643195534386466,
  1.0551562205101295,
  0.6667121824386473,
  0.34910355580365166,
  0.7823822821267535,
  1.0022462210267367,
  0.8400496475709041,
  0.706545516531718,
  0.425808078140945,
  1.3242652199570513,
  0.5722318709679326,
  0.5943743640997695,
  0.690679616728474,
  0.539257289894177,
  0.37097788905119117,
  0.4497302529498234,
  0.7614405692714401,
  0.5175776821765838,
  0.6621937385963241,
  0.8423462341482593,
  0.708637600018853,
  0.41846542738493603,
  0.6254327699417653,
  1.213484947540808,
  0.8842201698926271,
  0.7557284244360403,
  0.6408219757743792,
  0.511304302409602,
  0.730423536324743,
  0.5020493941601943,
  0.5664712103832005,
  0.7641518298953729,
  0.46302107182953806,
  0.45959968414533464,
  0.7573422106377864,
  0.4813143584488271,
  0.7014214878526538,
  0.7458214688111245,
  0.690396803305276,
  0.44212855569927956,
  0.6681510538091537,
  0.7054424723174707,
  0.9584424382756616,
  0.8572058868003847,
  0.5129876628656329,
  0.6775924074375445,
  0.33548710692454065,
  0.36750835522159697,
  1.077643308280305,
  0.6606005009754925,
  0.6911349597068152,
  0.6231606326700864,
  0.602447688744272,
  0.5203521576607764,
  0.3622428141252291,
  0.5827720584803182,
  0.35997028875398135,
  1.3766403070984696,
  0.5621764337455439,
  0.41315020284998105,
  0.530748137476179,
  0.7175148435323769,
  0.707353410741158,
  0.5749365154826165,
  0.48480721708238594,
  0.8668679392519993,
  0.784760180661277,
  1.0643202782131924,
  1.055972066674802,
  0.5133376224986828,
  0.5636795412880685,
  0.734942197901494,
  1.106716850102659,
  0.5436879375765777,
  0.5289428294650398,
  0.6085041139511407,
  0.4131289730452274,
  0.7236630293837298,
  0.5207321747706948,
  0.7016884077306269,
  0.8370214440333109,
  0.5981763032489854,
  0.7666095142248066,
  0.40974011652763215,
  0.7858678342478069,
  0.8803072445751484,
  1.240285463956784,
  0.8492280572719985,
  0.5360192650721023,
  0.7077658404416188,
  0.39393619348367104,
  0.5545771328544035,
  0.8930098320640429,
  0.45992589853355054,
  0.5628802714697683,
  0.7229958180440845,
  0.7023024406565862,
  0.5972796807643324,
  0.5246905449893028,
  1.2266509296765478,
  0.5109088444733775,
  0.7137615828511601,
  0.5492995147846726,
  0.681833890045364,
  0.6429105932780644,
  0.5208123350620915,
  0.9828717378186955,
  0.6895601785552901,
  0.9247234465445283,
  0.6197231400131281,
  0.6401515898311595,
  0.4513683642488448,
  0.6882224553512643,
  0.7043182688254693,
  1.1670754673067638,
  0.6717203158869678,
  0.5530618908625302,
  0.4010315991215703,
  0.4793641143199457,
  0.4655395079079524,
  0.5636755443268967,
  0.5476854944850136,
  1.003177452183273,
  0.8036548136637854,
  0.6910313694558009,
  0.9065721322480897,
  1.1111064510341755,
  0.6930838571049444,
  0.8543054655680155,
  0.5213537439844642,
  1.0238687744717938,
  0.4503489445712273,
  0.9302857946644146,
  0.6681510538091538,
  0.6049484697980946,
  0.637904092981905,
  0.7234749339156377,
  0.7596381826543015,
  0.7127332035189592,
  0.4573477339372203,
  0.44283395072462417,
  0.48442321331925964,
  0.4322707747017616,
  0.9894685221567273,
  0.7953816490176899,
  0.6714899317301688,
  0.5969549032380037,
  0.3903898655394913,
  0.7433128862030937,
  0.6636878110853359,
  1.0146042617496716,
  0.8149391637730496,
  0.8002076867461018,
  0.41607856740375443,
  0.763930462181283,
  0.4949641851736727,
  0.46787702029608214,
  0.7526029448855149,
  0.699438793355302,
  0.7455372487319141,
  0.5639583837977932,
  1.1596050293396745,
  0.45948044502077084,
  0.42580994335654077,
  0.5374480867834647,
  0.7528889014739353,
  0.5155602622388973,
  1.1205102835195633,
  0.6921227141422654,
  0.8183373913421987,
  0.5169108891934481,
  0.5552339891641396,
  1.0225631911593582,
  0.86987436775014,
  1.0063107635740545,
  0.7121196838764634,
  0.4919155279831783,
  0.6532900384417277,
  1.1670754673067638,
  0.6648234411428696,
  0.45424594186291956,
  0.4558336033107317,
  0.6936156008211904,
  0.5356143039962762,
  0.3416692159730625,
  0.6405314535201426,
  0.8234501142124449,
  0.565671908329175,
  0.4985334789449155,
  0.4969627319596485,
  0.6860213158420618,
  0.8128658354173928,
  0.6058876252641431,
  0.586374760487679,
  0.8935120018062555,
  0.9481011561226019,
  0.5869360863727935,
  0.6744893013183161,
  0.49837814995552476,
  1.1503516444106923,
  0.48434501611436737,
  0.6196338485413561,
  0.8515632831487041,
  0.5453173659002756,
  0.4056509428587945,
  0.4637763818347319,
  0.9518753934104109,
  0.5772612919670217,
  0.5383189095928823,
  0.5749371200624429,
  0.3944198075083739,
  0.7234240063988825,
  0.6143150808072126,
  0.7160622082767579,
  0.6812070501624832,
  0.6949062791172566,
  0.7945014635339747,
  0.5513855085230945,
  0.7568822629947625,
  0.5491323560666816,
  0.5772914319822275,
  1.0071160706199127,
  0.9320315195860155,
  0.7426149190179558,
  0.7944720190789789,
  0.3880895729096075,
  1.0659062329162272,
  0.7257751755066139,
  0.4742903206498916,
  0.784456976525747,
  0.6224444818991314,
  0.4471738920458791,
  0.5084184738247274,
  0.8905134754821219,
  0.637342811081684,
  0.706202132414829,
  0.5111895566644346,
  0.7532277555564889,
  0.9000530716689376,
  0.4749901003763636,
  0.32925354832623016,
  0.7458060331793489,
  0.5936959608412138,
  0.6770656548280604,
  0.5290466705014664,
  0.5573472654276446,
  0.6103297132488886,
  0.8959545031302906,
  0.8492267038403448,
  0.8801238481105125,
  0.49599146728808363,
  0.9418796453581287,
  0.849741067387428,
  0.7334359151968055,
  0.7315921022398424,
  0.8538120152787981,
  0.6281558089982263,
  1.1276801814176025,
  0.5981237144704713,
  0.6445854048522028,
  0.47232116148189496,
  0.7025682201032032,
  0.49895883255472673,
  0.9103431914960991,
  0.38152029376803426,
  0.5032927061487592,
  0.6339648144603779,
  1.1483280534084914,
  0.5557032208568624,
  0.9455690270511853,
  0.4197451067731039,
  0.6174311211782253,
  0.5827374966046363,
  0.8589918870757141,
  0.9071837427624667,
  0.538117021454795,
  0.6744989415621417,
  1.4401240021677997,
  0.5480713444475169,
  0.4931297408733445,
  0.4812801108971982,
  0.7717788266642518,
  0.62148233795586,
  0.43871616706651567,
  0.5028235419289536,
  0.8662904107595211,
  0.7241888524922123,
  0.6033562944619982,
  0.7617823067961035,
  0.9954854216107413,
  0.46894198390929787,
  0.6810026924940782,
  0.40673386910268045,
  0.773889626947361,
  0.7625675600571067,
  0.5444300054316981,
  0.46871078001393546,
  0.5408756241698613,
  0.6558676938284608,
  0.5420575649028124,
  0.4450750958247905,
  0.4537388237724859,
  1.263902871815794,
  0.8836164753103953,
  0.7923455291833961,
  0.5532410340360236,
  0.6329726091134673,
  0.8198830466965535,
  1.1577815702176595,
  0.7252488809477046,
  0.7804790972427478,
  0.5809672328594627,
  1.0315774106091102,
  0.40072213629028935,
  0.4069383327928458,
  0.6648246018457276,
  0.624784896641337,
  0.8571306099062264,
  0.8884978754067374,
  0.4401155610806354,
  0.5221106288673872,
  0.9475656665867492,
  0.7703204200702163,
  0.636563517587158,
  0.9178888810872483,
  0.525396220590717,
  0.49822191116063336,
  0.5818607858937568,
  0.775902514935756,
  0.9391346865971483,
  0.5099229567089414,
  0.7683398161212417,
  0.6048005215799798,
  0.576165709446365,
  1.2740180533493526,
  0.7103553659264895,
  0.7256179691480232,
  0.6516447383966455,
  0.4718003694392411,
  0.7286223551141856,
  0.5374080432629681,
  0.6862578934020497,
  1.101494668735875,
  0.40183236023765456,
  0.4390997539088694,
  0.9154834374485634,
  0.692077170585593,
  0.8675169950038181,
  0.3717769558960701,
  0.5238712434307183,
  1.3009735113978471,
  0.48729053583000786,
  0.545590060453007,
  0.9269786904334769,
  0.6334366086363943,
  0.5307252128409166,
  0.3850713389539493,
  0.9326730062538643,
  0.564592595535674,
  0.9494619929211545,
  0.8735254593025599,
  0.9129633207738425,
  0.5249831756504124,
  0.4411159209609836,
  0.568711130416668,
  0.39245088738305317,
  0.702524086726958,
  0.5828126590361737,
  0.7478320467219217,
  0.9727191529733276,
  0.8015907378721508,
  0.7946208860944831,
  0.5685386522268548,
  0.9248877595644476,
  0.8283676231074136,
  0.6880815391248685,
  0.982239144661414,
  0.5059795321434544,
  0.5626411728798282,
  0.5191672855254854,
  1.0629588284718763,
  0.47560284473071296,
  0.663345999950308,
  0.3885592361555484,
  0.45131454101419805,
  0.4960349607633919,
  0.717031953882184,
  0.6372862180787513,
  0.6305569848007829],
 'topic_coherences_toplen_ptw': [2.0956432149414908,
  2.1535240947120737,
  2.8292371579349185,
  1.87571387898929,
  2.346451870009993,
  3.226761710980802,
  1.9268920456173568,
  1.6180633470149492,
  2.1603641420965194,
  2.111364111726634,
  1.8843975960799404,
  2.67100155859519,
  2.0041191448861375,
  2.2960403613814058,
  2.29035348424422,
  2.2511018392627333,
  3.2202474401611747,
  2.1978257467664424,
  2.246628765802841,
  3.189557861813141,
  2.5872781976785193,
  2.5301008438108754,
  2.0483876545399955,
  1.757537800853324,
  2.1071998379914048,
  3.2230577059958994,
  1.7914914507841155,
  1.898844103458519,
  2.187829678156063,
  2.052452837070328,
  1.756857868397566,
  2.0791756852931136,
  2.1821697497698738,
  2.204497776758421,
  3.4643496786478556,
  3.4035513172857508,
  1.9624732390221462,
  1.8652626322777506,
  2.4603657448354186,
  2.243793355189312,
  2.3105633196699893,
  2.1514626854819885,
  2.168017626415772,
  2.127727695999189,
  2.0398502201277897,
  1.7610124373652989,
  2.369576954883002,
  2.125822891740122,
  2.8800814278048206,
  1.7463323899688443,
  2.1746838587668154,
  2.4083365172606217,
  2.113906581392728,
  3.2885496143196065,
  1.8135335545294085,
  2.352726661067561,
  1.7218100360612218,
  1.9119422075705046,
  2.6915132675653997,
  3.037930197597021,
  2.1275937088576327,
  2.18225325820167,
  2.161032703201307,
  1.6440081419893138,
  1.8938701316711666,
  2.644737292868619,
  1.7620233980400382,
  2.4633104910845747,
  2.8944302718864927,
  2.582508657311949,
  2.1863316546932037,
  1.993788643173034,
  2.1924776371604726,
  2.096405993334583,
  1.9012815447255136,
  2.4914636516909963,
  2.2917844562940113,
  2.370911995550846,
  3.0036983229648917,
  3.1571823859914554,
  2.251163602635274,
  2.5048643275639324,
  2.3371964856594496,
  2.8676723711508867,
  1.8515397689440516,
  1.7752883045582537,
  2.7262990532561586,
  1.869784151211071,
  1.7280146408125303,
  1.9607622565934868,
  2.53860152762334,
  2.195249517686346,
  2.131017087374331,
  2.232663746985575,
  2.8470861010898703,
  2.091585667140941,
  2.5214941832462605,
  3.167397536550704,
  2.2944217927046813,
  2.1216446608130584,
  1.9376697959793208,
  2.9026838590028223,
  2.081924203913317,
  2.3235953074093754,
  2.0741577436238368,
  2.1654176839717256,
  2.4821273845066862,
  1.9988662040774783,
  2.4307472335731144,
  2.1307193665650854,
  3.1537786753649883,
  1.9262808689576274,
  1.8928024279427185,
  2.5897352121700714,
  1.8888619944204739,
  2.120793377734788,
  2.0321871405503678,
  2.7002053022146177,
  1.8848328109122527,
  2.7865470463063136,
  2.1240534497175085,
  1.7099307901932366,
  2.0387761129024327,
  1.7652539859570724,
  1.8120693335838596,
  3.2974631316570684,
  1.910537222884533,
  1.9873431985342889,
  3.2476737888497467,
  2.6627574636386564,
  1.9502073384590475,
  2.3031645328052495,
  2.2072037712034884,
  2.547479639663226,
  2.235210855525473,
  2.4145437913193066,
  2.303586823346005,
  2.7505834456656966,
  2.307996393005644,
  2.1060936212240704,
  1.7807240367063115,
  3.0585961491174594,
  1.7853817758782622,
  1.886094065465048,
  2.4846626299553964,
  2.736128195434879,
  2.014550765101329,
  1.6495462794624187,
  1.7809643167381188,
  2.3869463780482545,
  2.6839433367699215,
  2.482611836970295,
  1.7716774612898905,
  2.315619487465026,
  2.681793417172246,
  2.2349202934157817,
  2.2032302102620176,
  2.11810771282725,
  2.406975912188134,
  3.0662634046786796,
  2.0453550751587843,
  2.225838733067944,
  2.2043797540555,
  2.001348380832673,
  2.358621349769896,
  2.134893683364026,
  2.9157073226604777,
  2.166499269327483,
  1.8482618508451198,
  1.787479955273039,
  1.9714236346161336,
  2.0208104308652826,
  3.042967814941562,
  2.344321313144827,
  2.6191062544358092,
  2.044241299941109,
  2.214401700463542,
  2.0244867396443134,
  3.8087273933324903,
  2.028188141537747,
  2.0434408273211684,
  2.100854778146696,
  2.6617129367209866,
  2.3932524558972363,
  2.019412675359794,
  2.9195703405623505,
  2.1350208789448444,
  2.2722157884351253,
  2.109702476937881,
  3.44066641860225,
  2.430153679578275,
  2.51058033734303,
  1.8463560472117249,
  1.609281391846779,
  1.690988377819422,
  3.3952310815082254,
  1.8453429354646418,
  2.178970722841124,
  1.9740346423995747,
  2.1074112850748214,
  2.060194141366841,
  1.9756735782451933,
  2.179579161444035,
  2.489231516037817,
  1.7388999972272274,
  2.077617699475089,
  3.3001477106833255,
  2.040090812994855,
  2.321541251039561,
  2.271863198702975,
  2.789610430536412,
  2.050099757259788,
  2.1504696660489655,
  2.4613163771890565,
  2.3093507061840945,
  2.5468595835375907,
  2.2079381403348526,
  3.2045060864900106,
  1.7938260425384707,
  2.168929797603287,
  2.0335862123951287,
  2.362986872540295,
  1.7238585494919734,
  1.77391225982577,
  1.7905289875828976,
  2.0134130425055066,
  2.3550454366635054,
  1.7460417792388965,
  2.1303430671068746,
  2.915229970113365,
  1.717389327472737,
  2.0157703128008118,
  3.6152554948704907,
  2.4044517911848726,
  1.8268120356359279,
  2.156741082893954,
  2.5710767867179327,
  4.029448164251379,
  2.2252916816083617,
  2.7156785524065548,
  2.0523577946254896,
  2.00327503218943,
  1.9802038933157793,
  1.737016239430647,
  3.1969490972196564,
  1.909569556341889,
  2.2431902852790246,
  2.2646313027479765,
  1.6836998232377198,
  4.149311897585999,
  2.292953078374404,
  3.28242202227629,
  2.8455848277366576,
  1.6309965370470694,
  1.9024028635524453,
  2.083426265573884,
  2.2573579599667504,
  2.555542121805878,
  1.9199334089028879,
  2.0449527199368087,
  2.9541822140403653,
  1.976694733063163,
  1.9681938732912305,
  2.0846045461514677,
  2.1855679079174233,
  2.1502545489657905,
  2.1710589343970654,
  1.9896221336251527,
  3.6812045053670785,
  2.232889260933011,
  2.557765175081415,
  2.6230155964685897,
  2.1637746265914957,
  1.9562159432153883,
  1.7530194621280721,
  2.8285451478226964,
  1.924629040631151,
  2.1287680817411117,
  2.593633852571711,
  1.9474862476687802,
  2.2761872522725333,
  1.8963231245443897,
  2.049471702554739,
  2.1602941315445983,
  2.0375149834077932,
  2.9724349312922724,
  2.3320772196492388,
  2.1643251845590004,
  3.0877972215393177,
  1.8636220135859352,
  2.2657920382236223,
  2.4517008172792423,
  2.2114898932886464,
  2.49624581807505,
  2.439793146873131,
  2.207711255733544,
  2.0626220925204364,
  2.455518730159316,
  1.686699374836936,
  2.658152492906268,
  2.093512558349825,
  2.418022789224081,
  2.052081177572381,
  3.1661618436667327,
  2.0222591256282465,
  2.3017120038525745,
  1.7769427719022033,
  2.575915796182474,
  2.1601147925834363,
  1.8218394376218996,
  2.005372619529182,
  1.9633375976895666,
  2.1514029706679927,
  2.891605415258374,
  2.905341307445965,
  2.1383360920786942,
  2.230777430445542,
  1.859892940273297,
  2.1632494358603385,
  3.6036164722011814,
  2.4680347233003017,
  2.348782824490247,
  2.070536243087102,
  2.97320865081157,
  3.009498335270652,
  2.073933619046584,
  1.9901652165842922,
  2.3838101374057823,
  3.0049594735742744,
  2.1514758912056817,
  2.3832624397290836,
  1.9375820270115611,
  2.078346593096341,
  2.57868853458769,
  2.030284656537308,
  2.140676929499115,
  2.988579578075111,
  1.8255076116846682,
  1.9478141328433396,
  1.5957941665169666,
  1.8779866635710163,
  2.295745968839435,
  2.119440837293248,
  1.7990276076576528,
  2.088788514053546,
  2.7304077611622564,
  1.8899962843317921,
  2.2992757009986162,
  1.8091645206322913,
  2.3837844927165777,
  2.128587182694623,
  2.3421214968551376,
  2.3240724419225596,
  2.324649482194121,
  1.9166625891432585,
  2.3499994946474283,
  2.7924840210442436,
  1.901877511577262,
  2.1958248501157014,
  2.8737027440466405,
  2.031675585572572,
  2.629517344082164,
  2.4638924639583504,
  2.031447556123568,
  2.969597348658606,
  2.128551753060812,
  2.0871356327391166,
  2.187482410220477,
  2.6659537662694546,
  2.1167971427522745,
  2.122155188386545,
  1.8693080697144078,
  2.2961228799557087,
  2.0629198895500624,
  2.256377853439426,
  3.087051881976203,
  2.1393306713566713,
  1.9217594569490484,
  2.2865153974881216,
  2.4056747738941344,
  2.0708291546477398,
  2.0747098019309513,
  2.093968546409083,
  1.9664456047493424,
  3.2036979750966204,
  2.12914602822772,
  1.9818443864506168,
  2.967130283023932,
  2.5566227839072915,
  1.9227084692425946,
  2.626079000644999,
  3.316167558675745,
  1.928307234860899,
  2.0668110587214166,
  2.297680191237693,
  2.0647488275023385,
  2.1859344024707124,
  2.029112122405598,
  1.9135978534720572,
  2.0769105449641074],
 'topic_coherences_topden_ptw': [0.4925668686414926,
  0.46696705579886877,
  0.4983295065770929,
  0.5608629688169506,
  0.45431590652566406,
  0.4846405106808665,
  0.4811761912929174,
  0.47306922706645943,
  0.4763528424433685,
  0.538244037690487,
  0.3880339855067129,
  0.44699508715643227,
  0.5527104669441544,
  0.4649797741703262,
  0.4877740092532853,
  0.5050110415464591,
  0.5583022055602739,
  0.4943657012570345,
  0.4937332013500637,
  0.4260094082478372,
  0.43890656232134817,
  0.4736237940441731,
  0.42167472191861105,
  0.47243309214836804,
  0.5494612435018045,
  0.41381919550473173,
  0.4631724576444666,
  0.4924311226358817,
  0.4322355240005264,
  0.4830670861064526,
  0.4791094207994077,
  0.47208994620021744,
  0.41302812158716595,
  0.5261735616521138,
  0.5025789815065018,
  0.5378376774720538,
  0.5028020088680409,
  0.43127641005662376,
  0.46404936265033486,
  0.4824895188932034,
  0.4993822490908001,
  0.47102144690054115,
  0.5134491107613003,
  0.4884089632561854,
  0.4686402123996117,
  0.44966890555764333,
  0.4658671671047297,
  0.4688823702771555,
  0.5252097034505165,
  0.4625526400994124,
  0.4106497578486032,
  0.47337784406242644,
  0.4888735645199846,
  0.4802147397474205,
  0.49436697828965304,
  0.426327769327783,
  0.47191701445310935,
  0.47164341537478066,
  0.42320892178374525,
  0.5254440943980235,
  0.4999220957158192,
  0.450727250378155,
  0.4870286237861011,
  0.4720744344227634,
  0.42304900454150257,
  0.39230648456171774,
  0.49324795010363714,
  0.4660921887932649,
  0.48190605460371044,
  0.49168078446883384,
  0.5346040168769977,
  0.46402043644577184,
  0.502439985705487,
  0.5200435617565972,
  0.4515908998404878,
  0.433153108630098,
  0.5310560490663073,
  0.48301113862453277,
  0.5553743695607148,
  0.4343941169032642,
  0.49412430055271844,
  0.4639854339105593,
  0.5218950952172431,
  0.4233859568689475,
  0.44057245637486325,
  0.44202404468308726,
  0.4580890476924092,
  0.42210393928533846,
  0.47896168409436146,
  0.4854588499987759,
  0.5084432515672076,
  0.4619155702384987,
  0.46716869221321444,
  0.5291103602242123,
  0.43771171924191643,
  0.4985126822746224,
  0.47950542104981236,
  0.4514052123421022,
  0.4517921245631876,
  0.438516763155167,
  0.4327428718687184,
  0.4101551291824081,
  0.48532794980271254,
  0.46116581862319844,
  0.43343424307411166,
  0.5524515976458381,
  0.4810668211868826,
  0.5352713929018018,
  0.4709400721161843,
  0.4847839440044544,
  0.458277219265286,
  0.4661509007149335,

In [61]:
len(COHERENCES['topic_coherences'])

400

In [89]:
COHERENCES['topic_coherences'][:10]

[0.4682133200037822,
 0.5525499039748306,
 0.3662412591097539,
 0.7660746688638103,
 0.6599584504901529,
 1.2151843412918593,
 0.784374938331295,
 0.6583524284174844,
 0.7558873960285204,
 0.8872288724338003]

In [90]:
COHERENCES['topic_coherences'][:20]

[0.4682133200037822,
 0.5525499039748306,
 0.3662412591097539,
 0.7660746688638103,
 0.6599584504901529,
 1.2151843412918593,
 0.784374938331295,
 0.6583524284174844,
 0.7558873960285204,
 0.8872288724338003,
 0.5060579830596448,
 1.1643195534386466,
 1.0551562205101295,
 0.6667121824386473,
 0.34910355580365166,
 0.7823822821267535,
 1.0022462210267367,
 0.8400496475709041,
 0.706545516531718,
 0.425808078140945]

In [62]:
# Sparse

start = time.time()

scores = []

# for seed in tqdm(range(NUM_TRAINS), total=NUM_TRAINS):
for seed in range(NUM_TRAINS):
    if seed != NUM_TRAINS - 1:
        print(seed, end=' ')
    else:
        print(seed)

    model = init_model_from_family(
        family=KnownModel.SPARSE,
        dataset=dataset,
        main_modality=MAIN_MODALITY,
        num_topics=NUM_TOPICS,
        seed=seed,
        model_params=BEST_PARAMS[KnownModel.SPARSE],
    )

    if seed == 0:
        for reg in model.regularizers.data:
            print(f"{reg}: {model.regularizers[reg].tau}")

    results = fit_and_compute_scores(model, dataset)
    # scores.append(results['scores'])
    scores.append(results)

    # COHERENCES.extend(
    #     list(results['topic_coherences'].values())
    # )

    for k in COHERENCES:
        COHERENCES[k].extend(
            list(results[k].values())
        )

end = time.time()

print(f'Elapsed: {(end - start) / 60} min')

0 smooth_phi_bcg: 5.337990264087306
smooth_theta_bcg: 30.263585545407338
sparse_phi_sp: -0.24148051194680664
sparse_theta_sp: -1.3690669651493796
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19
Elapsed: 83.63650202353796 min

In [63]:
# for s in scores:
#     s['coherence_20'] = float(s['coherence_20'])

for s in scores:
    s['scores']['coherence_20'] = float(s['scores']['coherence_20'])

In [64]:
with open(SAVE_FOLDER + '/sparse_with_cohs.json', 'w') as f:
    f.write(
        json.dumps(scores, indent=4)
    )

In [63]:
len(COHERENCES)

800

In [64]:
COHERENCES[-10:]

[0.880095624600911,
 0.9270009959013572,
 0.452872601334081,
 0.9753726382102174,
 0.4825404955153426,
 0.7157639092437795,
 0.632902255675745,
 0.7792618758677884,
 0.8436468554657421,
 0.6953114019848466]

In [65]:
max(COHERENCES)

1.3530270785302947

In [65]:
def train_many(model_family, save_file_path):
    start = time.time()
    
    scores = []

    # for seed in tqdm(range(NUM_TRAINS), total=NUM_TRAINS):
    for seed in range(NUM_TRAINS):
        if seed != NUM_TRAINS - 1:
            print(seed, end=' ')
        else:
            print(seed)
    
        model = init_model_from_family(
            family=model_family,
            dataset=dataset,
            main_modality=MAIN_MODALITY,
            num_topics=NUM_TOPICS,
            seed=seed,
            model_params=BEST_PARAMS[model_family],
        )
    
        if seed == 0:
            for reg in model.regularizers.data:
                print(f"{reg}: {model.regularizers[reg].tau}")
    
        results = fit_and_compute_scores(model, dataset)
        # scores.append(results['scores'])
        scores.append(results)
    
        # COHERENCES.extend(
        #     list(results['topic_coherences'].values())
        # )
    
        for k in COHERENCES:
            COHERENCES[k].extend(
                list(results[k].values())
            )
    
    end = time.time()
    
    print(f'Elapsed: {(end - start) / 60} min')

    # for s in scores:
    #     s['coherence_20'] = float(s['coherence_20'])
    
    for s in scores:
        s['scores']['coherence_20'] = float(s['scores']['coherence_20'])

    with open(save_file_path, 'w') as f:
        f.write(
            json.dumps(scores, indent=4)
        )

In [ ]:
# well, we missed it... whatever
# train_many(KnownModel.DECORRELATION, SAVE_FOLDER + '/decorrelation_with_cohs.json')

In [66]:
train_many(KnownModel.DECORRELATION, SAVE_FOLDER + '/decorrelation_with_cohs.json')

0 decorrelation: 0.01
smooth_phi_bcg: 5.337990264087306
smooth_theta_bcg: 30.263585545407338
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19
Elapsed: 80.19879750410716 min

In [68]:
len(COHERENCES)

1200

In [67]:
train_many(KnownModel.TLESS, SAVE_FOLDER + '/tless_with_cohs.json')

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19
Elapsed: 82.0886171221733 min

In [72]:
len(COHERENCES)

1600

In [68]:
train_many(KnownModel.LDA, SAVE_FOLDER + '/lda_with_cohs.json')

0 smooth_phi: 0.05
smooth_theta_0: 0.12456869333982468
smooth_theta_1: 0.10180450975894928
smooth_theta_2: 0.08607485145330429
smooth_theta_3: 0.0745554119348526
smooth_theta_4: 0.06575533747673035
smooth_theta_5: 0.05881335958838463
smooth_theta_6: 0.053197186440229416
smooth_theta_7: 0.04856010526418686
smooth_theta_8: 0.04466661810874939
smooth_theta_9: 0.041351135820150375
smooth_theta_10: 0.038493841886520386
smooth_theta_11: 0.036005899310112
smooth_theta_12: 0.033820029348134995
smooth_theta_13: 0.03188437223434448
smooth_theta_14: 0.03015829436480999
smooth_theta_15: 0.02860950119793415
smooth_theta_16: 0.02721201814711094
smooth_theta_17: 0.025944700464606285
smooth_theta_18: 0.024790173396468163
smooth_theta_19: 0.023734018206596375
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19
Elapsed: 80.19886320829391 min

In [41]:
len(COHERENCES)

2000

In [54]:
1

1

In [71]:
COHERENCES.keys()

dict_keys(['topic_coherences', 'topic_coherences_toplen_ptw', 'topic_coherences_topden_ptw'])

In [72]:
for k in COHERENCES:
    print(k)
    print(len(COHERENCES[k]))

topic_coherences
2000
topic_coherences_toplen_ptw
2000
topic_coherences_topden_ptw
2000

In [77]:
for p in range(5, 100, 5):
    print(f'{p:2}: {np.percentile(COHERENCES, p)}')

 5: 0.44909245458611957
10: 0.49633189795078303
15: 0.5312798544554967
20: 0.5568860704432789
25: 0.583641029664594
30: 0.6154803648381737
35: 0.6420080477800698
40: 0.6686072625177087
45: 0.6987521704785715
50: 0.7275350316751499
55: 0.7582740845556143
60: 0.7879524550264069
65: 0.8206503482616105
70: 0.8533797049735502
75: 0.8848794056365471
80: 0.9154723765333351
85: 0.9536494799334573
90: 1.0014147388051453
95: 1.089784010979277

In [74]:
for k in COHERENCES:
    print(k)

    for p in range(5, 100, 5):
        print(f'{p:2}: {np.percentile(COHERENCES[k], p)}')

    print()

topic_coherences
 5: 0.3761569938166719
10: 0.4143367527969667
15: 0.4542455875910814
20: 0.4834872457111293
25: 0.513590898996654
30: 0.5425365977325278
35: 0.565671908329175
40: 0.5961392562354773
45: 0.6277063043052796
50: 0.6607445968186382
55: 0.6904814875133726
60: 0.7210395226390767
65: 0.7526029448855149
70: 0.7852508343981067
75: 0.8319217345735135
80: 0.8825231364747546
85: 0.9321277425861927
90: 1.0118762991083503
95: 1.1294498709977603

topic_coherences_toplen_ptw
 5: 1.7428335802764752
10: 1.7938763485672071
15: 1.8444298959987273
20: 1.890894097939173
25: 1.9310106265475007
30: 1.9751818974915076
35: 2.018198141521423
40: 2.050908263530298
45: 2.0911345123527316
50: 2.13460198747896
55: 2.1653136419406804
60: 2.21950006446868
65: 2.273771732539559
70: 2.3394925682940233
75: 2.435017475164776
80: 2.5432101128006273
85: 2.6917629341488447
90: 2.939062174058066
95: 3.2270515940633073

topic_coherences_topden_ptw
 5: 0.42461509010515663
10: 0.4353252849916843
15: 0.4446734577152701
20: 0.45243046418253624
25: 0.45841456463705
30: 0.4648276799837873
35: 0.4699823247590858
40: 0.47517241616386724
45: 0.4813435951308032
50: 0.4871960371094318
55: 0.4952786120105073
60: 0.5036793284213187
65: 0.5131203235167563
70: 0.5265470400021937
75: 0.5482640607410305
80: 0.5957747531988743
85: 0.677377937022243
90: 0.7395531462385905
95: 0.801590515434341

In [78]:
min(COHERENCES), max(COHERENCES)

(0.23028683424984975, 1.3530270785302947)

In [80]:
np.argmin(COHERENCES), np.argmax(COHERENCES)

(939, 520)

In [75]:
for k in COHERENCES:
    print(k)
    print(min(COHERENCES[k]), max(COHERENCES[k]))
    print()

topic_coherences
0.15132387398111333 1.5020738514744776

topic_coherences_toplen_ptw
1.5032401948154457 5.126959948774844

topic_coherences_topden_ptw
0.3826427537899631 0.9706315338779786

In [83]:
for p in [2, 98]:
    print(f'{p:2}: {np.percentile(COHERENCES, p)}')

 2: 0.38638722557933053
98: 1.177163998303747

In [76]:
for k in COHERENCES:
    print(k)

    for p in [2, 98]:
        print(f'{p:2}: {np.percentile(COHERENCES[k], p)}')

    print()

topic_coherences
 2: 0.34199022361156417
98: 1.226462260611979

topic_coherences_toplen_ptw
 2: 1.663891658164501
98: 3.604047548237196

topic_coherences_topden_ptw
 2: 0.4138428867647952
98: 0.8520687916766032

In [84]:
BEST_PARAMS

{<KnownModel.PLSA: 'PLSA'>: None,
 <KnownModel.SPARSE: 'sparse'>: {'sparse_sp_tau': -0.05,
  'smooth_bcg_tau': 0.05},
 <KnownModel.DECORRELATION: 'decorrelation'>: {'decorrelation_tau': 0.01,
  'sparse_sp_tau': -0.05,
  'smooth_bcg_tau': 0.05},
 <KnownModel.TLESS: 'TARTM'>: None,
 <KnownModel.LDA: 'LDA'>: {'prior': 'asymmetric'}}

In [77]:
BEST_PARAMS

{<KnownModel.PLSA: 'PLSA'>: None,
 <KnownModel.DECORRELATION: 'decorrelation'>: {'decorrelation_tau': 0.01,
  'sparse_sp_tau': -0.05,
  'smooth_bcg_tau': 0.05},
 <KnownModel.TLESS: 'TARTM'>: None,
 <KnownModel.SPARSE: 'sparse'>: {'sparse_sp_tau': -0.05,
  'smooth_bcg_tau': 0.05},
 <KnownModel.LDA: 'LDA'>: {'prior': 'asymmetric'}}

In [78]:
COHERENCES

{'topic_coherences': [0.4682133200037822,
  0.5525499039748306,
  0.3662412591097539,
  0.7660746688638103,
  0.6599584504901529,
  1.2151843412918593,
  0.784374938331295,
  0.6583524284174844,
  0.7558873960285204,
  0.8872288724338003,
  0.5060579830596448,
  1.1643195534386466,
  1.0551562205101295,
  0.6667121824386473,
  0.34910355580365166,
  0.7823822821267535,
  1.0022462210267367,
  0.8400496475709041,
  0.706545516531718,
  0.425808078140945,
  1.3242652199570513,
  0.5722318709679326,
  0.5943743640997695,
  0.690679616728474,
  0.539257289894177,
  0.37097788905119117,
  0.4497302529498234,
  0.7614405692714401,
  0.5175776821765838,
  0.6621937385963241,
  0.8423462341482593,
  0.708637600018853,
  0.41846542738493603,
  0.6254327699417653,
  1.213484947540808,
  0.8842201698926271,
  0.7557284244360403,
  0.6408219757743792,
  0.511304302409602,
  0.730423536324743,
  0.5020493941601943,
  0.5664712103832005,
  0.7641518298953729,
  0.46302107182953806,
  0.45959968414533464,
  0.7573422106377864,
  0.4813143584488271,
  0.7014214878526538,
  0.7458214688111245,
  0.690396803305276,
  0.44212855569927956,
  0.6681510538091537,
  0.7054424723174707,
  0.9584424382756616,
  0.8572058868003847,
  0.5129876628656329,
  0.6775924074375445,
  0.33548710692454065,
  0.36750835522159697,
  1.077643308280305,
  0.6606005009754925,
  0.6911349597068152,
  0.6231606326700864,
  0.602447688744272,
  0.5203521576607764,
  0.3622428141252291,
  0.5827720584803182,
  0.35997028875398135,
  1.3766403070984696,
  0.5621764337455439,
  0.41315020284998105,
  0.530748137476179,
  0.7175148435323769,
  0.707353410741158,
  0.5749365154826165,
  0.48480721708238594,
  0.8668679392519993,
  0.784760180661277,
  1.0643202782131924,
  1.055972066674802,
  0.5133376224986828,
  0.5636795412880685,
  0.734942197901494,
  1.106716850102659,
  0.5436879375765777,
  0.5289428294650398,
  0.6085041139511407,
  0.4131289730452274,
  0.7236630293837298,
  0.5207321747706948,
  0.7016884077306269,
  0.8370214440333109,
  0.5981763032489854,
  0.7666095142248066,
  0.40974011652763215,
  0.7858678342478069,
  0.8803072445751484,
  1.240285463956784,
  0.8492280572719985,
  0.5360192650721023,
  0.7077658404416188,
  0.39393619348367104,
  0.5545771328544035,
  0.8930098320640429,
  0.45992589853355054,
  0.5628802714697683,
  0.7229958180440845,
  0.7023024406565862,
  0.5972796807643324,
  0.5246905449893028,
  1.2266509296765478,
  0.5109088444733775,
  0.7137615828511601,
  0.5492995147846726,
  0.681833890045364,
  0.6429105932780644,
  0.5208123350620915,
  0.9828717378186955,
  0.6895601785552901,
  0.9247234465445283,
  0.6197231400131281,
  0.6401515898311595,
  0.4513683642488448,
  0.6882224553512643,
  0.7043182688254693,
  1.1670754673067638,
  0.6717203158869678,
  0.5530618908625302,
  0.4010315991215703,
  0.4793641143199457,
  0.4655395079079524,
  0.5636755443268967,
  0.5476854944850136,
  1.003177452183273,
  0.8036548136637854,
  0.6910313694558009,
  0.9065721322480897,
  1.1111064510341755,
  0.6930838571049444,
  0.8543054655680155,
  0.5213537439844642,
  1.0238687744717938,
  0.4503489445712273,
  0.9302857946644146,
  0.6681510538091538,
  0.6049484697980946,
  0.637904092981905,
  0.7234749339156377,
  0.7596381826543015,
  0.7127332035189592,
  0.4573477339372203,
  0.44283395072462417,
  0.48442321331925964,
  0.4322707747017616,
  0.9894685221567273,
  0.7953816490176899,
  0.6714899317301688,
  0.5969549032380037,
  0.3903898655394913,
  0.7433128862030937,
  0.6636878110853359,
  1.0146042617496716,
  0.8149391637730496,
  0.8002076867461018,
  0.41607856740375443,
  0.763930462181283,
  0.4949641851736727,
  0.46787702029608214,
  0.7526029448855149,
  0.699438793355302,
  0.7455372487319141,
  0.5639583837977932,
  1.1596050293396745,
  0.45948044502077084,
  0.42580994335654077,
  0.5374480867834647,
  0.7528889014739353,
  0.5155602622388973,
  1.1205102835195633,
  0.6921227141422654,
  0.8183373913421987,
  0.5169108891934481,
  0.5552339891641396,
  1.0225631911593582,
  0.86987436775014,
  1.0063107635740545,
  0.7121196838764634,
  0.4919155279831783,
  0.6532900384417277,
  1.1670754673067638,
  0.6648234411428696,
  0.45424594186291956,
  0.4558336033107317,
  0.6936156008211904,
  0.5356143039962762,
  0.3416692159730625,
  0.6405314535201426,
  0.8234501142124449,
  0.565671908329175,
  0.4985334789449155,
  0.4969627319596485,
  0.6860213158420618,
  0.8128658354173928,
  0.6058876252641431,
  0.586374760487679,
  0.8935120018062555,
  0.9481011561226019,
  0.5869360863727935,
  0.6744893013183161,
  0.49837814995552476,
  1.1503516444106923,
  0.48434501611436737,
  0.6196338485413561,
  0.8515632831487041,
  0.5453173659002756,
  0.4056509428587945,
  0.4637763818347319,
  0.9518753934104109,
  0.5772612919670217,
  0.5383189095928823,
  0.5749371200624429,
  0.3944198075083739,
  0.7234240063988825,
  0.6143150808072126,
  0.7160622082767579,
  0.6812070501624832,
  0.6949062791172566,
  0.7945014635339747,
  0.5513855085230945,
  0.7568822629947625,
  0.5491323560666816,
  0.5772914319822275,
  1.0071160706199127,
  0.9320315195860155,
  0.7426149190179558,
  0.7944720190789789,
  0.3880895729096075,
  1.0659062329162272,
  0.7257751755066139,
  0.4742903206498916,
  0.784456976525747,
  0.6224444818991314,
  0.4471738920458791,
  0.5084184738247274,
  0.8905134754821219,
  0.637342811081684,
  0.706202132414829,
  0.5111895566644346,
  0.7532277555564889,
  0.9000530716689376,
  0.4749901003763636,
  0.32925354832623016,
  0.7458060331793489,
  0.5936959608412138,
  0.6770656548280604,
  0.5290466705014664,
  0.5573472654276446,
  0.6103297132488886,
  0.8959545031302906,
  0.8492267038403448,
  0.8801238481105125,
  0.49599146728808363,
  0.9418796453581287,
  0.849741067387428,
  0.7334359151968055,
  0.7315921022398424,
  0.8538120152787981,
  0.6281558089982263,
  1.1276801814176025,
  0.5981237144704713,
  0.6445854048522028,
  0.47232116148189496,
  0.7025682201032032,
  0.49895883255472673,
  0.9103431914960991,
  0.38152029376803426,
  0.5032927061487592,
  0.6339648144603779,
  1.1483280534084914,
  0.5557032208568624,
  0.9455690270511853,
  0.4197451067731039,
  0.6174311211782253,
  0.5827374966046363,
  0.8589918870757141,
  0.9071837427624667,
  0.538117021454795,
  0.6744989415621417,
  1.4401240021677997,
  0.5480713444475169,
  0.4931297408733445,
  0.4812801108971982,
  0.7717788266642518,
  0.62148233795586,
  0.43871616706651567,
  0.5028235419289536,
  0.8662904107595211,
  0.7241888524922123,
  0.6033562944619982,
  0.7617823067961035,
  0.9954854216107413,
  0.46894198390929787,
  0.6810026924940782,
  0.40673386910268045,
  0.773889626947361,
  0.7625675600571067,
  0.5444300054316981,
  0.46871078001393546,
  0.5408756241698613,
  0.6558676938284608,
  0.5420575649028124,
  0.4450750958247905,
  0.4537388237724859,
  1.263902871815794,
  0.8836164753103953,
  0.7923455291833961,
  0.5532410340360236,
  0.6329726091134673,
  0.8198830466965535,
  1.1577815702176595,
  0.7252488809477046,
  0.7804790972427478,
  0.5809672328594627,
  1.0315774106091102,
  0.40072213629028935,
  0.4069383327928458,
  0.6648246018457276,
  0.624784896641337,
  0.8571306099062264,
  0.8884978754067374,
  0.4401155610806354,
  0.5221106288673872,
  0.9475656665867492,
  0.7703204200702163,
  0.636563517587158,
  0.9178888810872483,
  0.525396220590717,
  0.49822191116063336,
  0.5818607858937568,
  0.775902514935756,
  0.9391346865971483,
  0.5099229567089414,
  0.7683398161212417,
  0.6048005215799798,
  0.576165709446365,
  1.2740180533493526,
  0.7103553659264895,
  0.7256179691480232,
  0.6516447383966455,
  0.4718003694392411,
  0.7286223551141856,
  0.5374080432629681,
  0.6862578934020497,
  1.101494668735875,
  0.40183236023765456,
  0.4390997539088694,
  0.9154834374485634,
  0.692077170585593,
  0.8675169950038181,
  0.3717769558960701,
  0.5238712434307183,
  1.3009735113978471,
  0.48729053583000786,
  0.545590060453007,
  0.9269786904334769,
  0.6334366086363943,
  0.5307252128409166,
  0.3850713389539493,
  0.9326730062538643,
  0.564592595535674,
  0.9494619929211545,
  0.8735254593025599,
  0.9129633207738425,
  0.5249831756504124,
  0.4411159209609836,
  0.568711130416668,
  0.39245088738305317,
  0.702524086726958,
  0.5828126590361737,
  0.7478320467219217,
  0.9727191529733276,
  0.8015907378721508,
  0.7946208860944831,
  0.5685386522268548,
  0.9248877595644476,
  0.8283676231074136,
  0.6880815391248685,
  0.982239144661414,
  0.5059795321434544,
  0.5626411728798282,
  0.5191672855254854,
  1.0629588284718763,
  0.47560284473071296,
  0.663345999950308,
  0.3885592361555484,
  0.45131454101419805,
  0.4960349607633919,
  0.717031953882184,
  0.6372862180787513,
  0.6305569848007829,
  0.5030885868011424,
  0.5207657748971292,
  0.46688254454371636,
  0.7143010581435777,
  0.6874723289012623,
  1.2508650222621893,
  0.765747875827312,
  0.6637798755185303,
  0.8050386426539776,
  0.8074832951131053,
  0.48457922041759666,
  1.5020738514744776,
  1.099819645341793,
  0.9169458547744285,
  0.5188023013769827,
  0.8655746125457305,
  1.180296731842603,
  0.7822405100660138,
  0.7625675600571067,
  0.43910536887445184,
  1.3242652199570513,
  0.616949459859535,
  0.7319808691689618,
  0.5166356190801646,
  0.5523149703942252,
  0.3700529609372436,
  0.40859977240252254,
  0.822286648226127,
  0.5282651536885317,
  0.6910176866653678,
  0.8846163310236639,
  0.694904755797349,
  0.43535753739991523,
  0.605582262851606,
  1.2638018897281007,
  1.0290901648714972,
  0.7954358623444974,
  0.9299475504069669,
  0.589548852674704,
  0.7847601806612766,
  0.45345494539580344,
  0.7080921383571869,
  0.8706241291846438,
  0.42897495014681875,
  0.5867479706768397,
  0.755390071030767,
  0.542292480499163,
  0.8282273177326441,
  0.50129406535894,
  0.789865256392824,
  0.5348136792521453,
  0.706545516531718,
  0.7158100131425837,
  1.2077964881010126,
  1.0929768105316378,
  0.6538596545750571,
  0.5298913462754988,
  1.1787817964230722,
  0.4046955199822676,
  1.0609143681675686,
  0.7017284948237033,
  0.691799790980106,
  0.733982595000144,
  0.6044054706158457,
  0.5400870391834774,
  0.42620159344431824,
  0.56812478807083,
  0.6496830595307124,
  1.2684661617682425,
  0.5994187284451052,
  0.5109730352179509,
  0.5710610995795833,
  0.8796152294329446,
  0.7908219657183452,
  0.5532741239543904,
  0.44291428766950486,
  0.974437388726443,
  0.7847601806612767,
  0.8630600587206345,
  1.0960977761800366,
  0.6743083022026773,
  0.5776283598761075,
  0.8037569792913873,
  1.0810369261819623,
  0.3682178636723512,
  0.6140625402905662,
  0.6624598630706422,
  0.38666392268997507,
  0.8536076866622329,
  0.555243550943771,
  0.6362227983980255,
  1.0563083493043004,
  0.721496289253933,
  0.946254961746085,
  0.48873975301177036,
  0.800666153373918,
  0.8907181577123691,
  1.2470573564284695,
  0.9394945469913535,
  0.5777001491069772,
  0.5916333690845906,
  0.41033445355709636,
  0.6156753937189449,
  0.4667461832169931,
  0.6526302501235828,
  0.8257155401025116,
  0.7229958180440845,
  0.8908857609217715,
  0.6895873716056875,
  0.5455165738551331,
  1.1683945074643751,
  0.5166506823745551,
  0.6843643670018248,
  0.58843699940341,
  0.7678439666473789,
  0.7317104882820051,
  0.5563212176158251,
  1.0128247084479336,
  0.8222590975856878,
  1.011252102382277,
  0.6153797321203746,
  0.8073626880924841,
  0.568266097470455,
  0.6539074346775802,
  0.7078588758853479,
  1.263801889728101,
  0.6074136470994833,
  0.5224359468274921,
  0.3744724326402785,
  0.4835402134026235,
  0.4042622305297671,
  0.8659736010725031,
  0.545922113769625,
  1.0086845644243765,
  0.7249604667899309,
  0.7427970683481551,
  0.9733191283177919,
  0.8875829588769972,
  0.7026234357204575,
  0.9389116478693191,
  0.5956673947390909,
  1.1542176086696783,
  0.48018355385631134,
  0.9893065247447658,
  0.6805414784901311,
  0.6641089139244027,
  0.6754830314642756,
  0.9536870973302706,
  0.7987622887221805,
  0.837982552016571,
  1.207964097038025,
  0.5159029480095179,
  0.4348046025585724,
  0.6183172805541143,
  1.0156998728998967,
  0.8313965372184431,
  0.7499062118598775,
  0.5870612368005963,
  0.42648620009872634,
  0.9043110885457233,
  0.7202695264213689,
  0.976608812817812,
  0.8904662599740657,
  0.8534622752078083,
  0.41326534778157314,
  0.9134621609481879,
  0.5020265148989844,
  0.4797943128039227,
  0.5502270334703337,
  0.7309846612809745,
  0.9961711735177164,
  0.6260382401948603,
  1.021910992481889,
  0.4938959277237353,
  0.5675636471358424,
  0.5507431444780608,
  0.8611046422918621,
  0.5555015744470694,
  1.2264584102229061,
  0.6587053303949284,
  0.7679596275677617,
  0.4976265802228573,
  0.7518737863470601,
  0.8863087102284645,
  0.86987436775014,
  1.0791267889769545,
  0.7101551502353824,
  0.6888157192407841,
  0.6885989385709799,
  1.206703084267664,
  0.7191164841538963,
  0.45205669910875323,
  0.5850900387518067,
  0.6576612416088762,
  0.6706931157782666,
  0.3746038525159407,
  0.5308295144241476,
  0.9134814804770062,
  0.565671908329175,
  0.7014058955805573,
  0.7218155266965517,
  0.7499816407292302,
  0.8076647675422615,
  0.6925678140747467,
  0.7367522716768701,
  0.8913528079444243,
  0.9575805807016342,
  0.542117040368961,
  0.5600005803530818,
  0.45988982582963406,
  1.2484693076722853,
  0.5836491845458821,
  0.7091436633192818,
  0.7803396903259769,
  0.4850425383971123,
  0.39533262743821496,
  0.9427463243995602,
  0.9443923013271426,
  0.6101844976463814,
  0.4597323945159632,
  0.5837144923890798,
  0.4115283606862885,
  0.6389983923230619,
  0.8707400622142244,
  0.7304508025750467,
  0.7482987477249238,
  0.5008086677462701,
  0.9056971997330753,
  0.5554819726612709,
  0.8256258229885328,
  0.7625675600571068,
  0.6901760003142665,
  1.121027614068779,
  0.9222197719479575,
  0.8160163289126419,
  1.0517542541494145,
  0.5095743702366164,
  0.9940179756226302,
  0.8802005283914417,
  0.4988676297169834,
  0.7295101581977768,
  0.6656562432941391,
  0.4473246931180789,
  0.510794168546397,
  0.9753659793251278,
  0.6310587113371766,
  0.7388333677419516,
  0.5886268687129009,
  0.9341070705035229,
  0.931885135272484,
  0.501036028521932,
  0.36763764492716794,
  0.750583637886714,
  0.6241316849726414,
  0.6831316584551572,
  0.6048793556233868,
  0.576757610035087,
  0.7388289391437443,
  0.9986044543257296,
  0.8020603663892092,
  0.7840056539294468,
  0.45302851952493123,
  0.8584026768391839,
  0.9613826437576268,
  0.47674281466238727,
  0.7899078987501704,
  0.8410780056564829,
  0.568738082803585,
  1.1871394635363925,
  0.7427820713258279,
  0.6981337857798402,
  0.5121462291151394,
  0.6696089732012399,
  0.5795010652141916,
  1.1187464848844673,
  0.40645648287031366,
  0.6887856452591511,
  0.648236095192062,
  1.2765276835535313,
  0.6832272987147983,
  0.9531869741941548,
  0.40115992891996016,
  0.607081191025425,
  0.7356121308211505,
  0.844424439111837,
  0.8668246892246552,
  0.5891144109559077,
  1.1771467889940668,
  1.1739119061447325,
  0.6600818053660376,
  0.5556347792938617,
  0.5925069439662094,
  0.7736569305058156,
  0.8922594111414639,
  0.47019143266568664,
  0.5307615123741701,
  0.8673969334289632,
  0.7256430421137171,
  0.6475184298265801,
  0.8248691665721762,
  0.8718474838198682,
  0.6195847334837786,
  0.7055307092557955,
  0.45179864000004316,
  0.7872870731643049,
  0.7625675600571067,
  0.4966855321824761,
  0.46565466682128215,
  0.5612809842953679,
  0.6741528537735951,
  0.6782367553207289,
  0.4536569268670933,
  0.4860992713265967,
  1.178514211503243,
  0.9187203414344118,
  0.898504297758558,
  0.6989673774668946,
  0.7507244571434528,
  0.9535149300653586,
  1.1276801814176025,
  0.7625675600571068,
  0.7358410836320075,
  0.6682315449559186,
  0.970835580053544,
  0.37295395884370947,
  0.4041073421551453,
  0.6706494803959894,
  0.5088629068238939,
  1.1022761846423563,
  0.9988350235675978,
  0.5340036743139015,
  0.6300101710326751,
  1.013628131476034,
  0.888001253264023,
  0.6102596241841562,
  0.9178888810872482,
  0.6422965078297206,
  0.7699779122018372,
  0.5497125011844624,
  0.926428226343095,
  1.0512931497394826,
  0.7626636660152307,
  0.7558240806231329,
  0.6590235979816441,
  0.4762936134009139,
  1.129197476736287,
  0.6936838579356933,
  0.7290772421835121,
  0.7521362060837926,
  0.5236675446009923,
  0.35955727009695937,
  0.5228710657273126,
  0.672031966950318,
  0.9180796426434199,
  0.39986906820781454,
  0.7847601806612766,
  0.9783282546035762,
  0.7319148625158143,
  1.0125694296030918,
  0.37177695589607007,
  0.5597843526898175,
  1.4221506951757563,
  0.7316405117094432,
  0.5165226981330884,
  0.9573133878930473,
  0.671885154918453,
  0.6322988014185363,
  0.33975046324275254,
  1.01804525633871,
  0.5647917209297846,
  0.896786185845056,
  0.9266256383758527,
  0.8367886171448495,
  0.7297465042320569,
  0.5725812468041876,
  0.9161172648422478,
  0.4603877510534294,
  0.6333339237418605,
  0.6706116344527422,
  0.7478320467219215,
  0.4451463274362693,
  0.630812416251519,
  0.8136166654324238,
  0.49705428752641806,
  0.9190562672348399,
  0.7894176333189508,
  0.5148366947047046,
  0.9631288253543943,
  0.5172647198372382,
  0.9877091647318024,
  0.7264909155956454,
  1.1729626496571433,
  0.4641920241514189,
  0.5178711721244734,
  0.39808023015074195,
  0.7655058516477026,
  0.4850224254823949,
  0.6514587049240339,
  0.6508381482911986,
  0.6494651548717936,
  0.41019413148576794,
  0.5470137368023253,
  0.43934023482539025,
  0.7152158432303094,
  0.7669322776918394,
  1.2271945221432523,
  0.754887783372435,
  0.6274971981263544,
  0.7891427690214298,
  0.8318240621605247,
  1.2781389730137753,
  0.5389517764158578,
  1.071561465008297,
  0.845099629709601,
  0.42542782099809945,
  0.8655746125457305,
  1.0784900817371266,
  0.7803400690867495,
  0.7229958180440845,
  0.16286909965538943,
  1.2389555621334325,
  0.6284586501543215,
  0.7064863499079392,
  0.5979359550632595,
  0.9118200904312863,
  0.41083134291327705,
  0.5624537491784551,
  0.7472819180209214,
  0.7062021324148291,
  0.71280952513422,
  0.8922826806423055,
  0.6902455239011354,
  0.4830961940221846,
  0.5863396645734326,
  1.2508650222621889,
  1.0908602014587199,
  0.7928038132643053,
  0.5142275812733398,
  0.44902671957940415,
  0.15323971631520716,
  0.6456738554051057,
  0.7942667578848371,
  0.8600777862552763,
  0.48085215130044673,
  0.5522730754826495,
  0.7325396450478853,
  0.47929013481655713,
  0.8976610520478856,
  0.9997378373669833,
  0.690396803305276,
  0.7781741692864985,
  0.6856193681907634,
  0.7218100507882872,
  1.0724937523301572,
  0.8470657520354968,
  0.6253395575071161,
  0.6860266395584059,
  1.1426073655139615,
  0.41083134291327705,
  0.17608189900221285,
  0.7017284948237033,
  0.4308290336413411,
  0.6912873394621343,
  0.5904405553533605,
  0.7558389277014749,
  0.5285971220301776,
  0.5781743561594997,
  0.3898998798415304,
  1.154030260252471,
  0.5384277395338664,
  0.5485768059139785,
  0.5493817248949703,
  0.7705112426200126,
  1.0096110017490274,
  0.5921990890867891,
  0.4574810155961829,
  0.917412124506403,
  0.7352590806351247,
  0.8344111584312344,
  0.15176791432393663,
  0.6542973288383188,
  0.5914756565790835,
  0.7783433170447537,
  1.106716850102659,
  0.44203775774748,
  0.4904922130823611,
  0.6251920022925973,
  0.45619839417389824,
  0.6353015140443459,
  0.5706969160179216,
  0.737966629040731,
  0.931979968392355,
  0.5737808981110437,
  0.944446879478909,
  0.48403616069929006,
  0.7784921588037614,
  0.9604927591655011,
  1.2029066497073142,
  0.7653423493815235,
  0.17630513951929458,
  0.6397471292039505,
  0.421836715989337,
  1.2527806245525448,
  0.6256049774587242,
  0.4206071808436301,
  0.743959359284167,
  0.7229958180440845,
  0.8233957640146568,
  0.803966577966077,
  0.5512161948032489,

## Newman Vs. Intratext

### Correlation

In [81]:
COHERENCES.keys()

dict_keys(['topic_coherences', 'topic_coherences_toplen_ptw', 'topic_coherences_topden_ptw'])

In [79]:
from scipy.stats import spearmanr

In [82]:
spearmanr(
    COHERENCES['topic_coherences'],
    COHERENCES['topic_coherences_toplen_ptw'],
)

SignificanceResult(statistic=0.25355294374651943, pvalue=1.0350547711474095e-30)

In [83]:
spearmanr(
    COHERENCES['topic_coherences'],
    COHERENCES['topic_coherences_topden_ptw'],
)

SignificanceResult(statistic=0.1523687495268863, pvalue=7.389691451133996e-12)

In [84]:
spearmanr(
    COHERENCES['topic_coherences_toplen_ptw'],
    COHERENCES['topic_coherences_topden_ptw'],
)

SignificanceResult(statistic=0.0064989661247415315, pvalue=0.7714613154312437)

### Tops Intersection

In [87]:
len(COHERENCES['topic_coherences'])

2000

In [88]:
inds1 = np.argsort(COHERENCES['topic_coherences'])[::-1][:100]

In [89]:
inds1

array([ 411,  288,  910,  761, 1888, 1088,   68, 1668, 1556, 1161,  420,
         20, 1319,  985, 1383, 1961,  361,  810,  678,  345, 1945,  468,
        313,  525,  434,  972, 1145, 1235,  902,  405,  834,  610, 1913,
        497,   97,  820, 1153,  805, 1710,  110,  578,  978, 1354, 1278,
       1697,    5, 1605,   34, 1634, 1620,  550,  453,  589,  897, 1515,
       1216,  668, 1068, 1115,  983, 1296,  416,  457,  713,  687,  925,
        688,  791,  510,  989,  125, 1725,  189, 1789, 1191,   11, 1444,
       1236,  172,  319, 1919, 1035,  541,  868,  937,  210, 1810,  278,
       1878, 1485, 1107, 1584,  857, 1737, 1248, 1437, 1519, 1010, 1060,
       1361])

In [92]:
COHERENCES['topic_coherences'][inds1[0]], COHERENCES['topic_coherences'][inds1[1]]

(1.5020738514744776, 1.4401240021677997)

In [94]:
inds1 = set(np.argsort(COHERENCES['topic_coherences'])[::-1][:100])
inds2 = set(np.argsort(COHERENCES['topic_coherences_toplen_ptw'])[::-1][:100])
inds3 = set(np.argsort(COHERENCES['topic_coherences_topden_ptw'])[::-1][:100])

In [97]:
len(inds1 & inds2), len(inds1 & inds3), len(inds2 & inds3)

(31, 16, 36)

In [98]:
inds1 = set(np.argsort(COHERENCES['topic_coherences'])[::-1][:200])
inds2 = set(np.argsort(COHERENCES['topic_coherences_toplen_ptw'])[::-1][:200])
inds3 = set(np.argsort(COHERENCES['topic_coherences_topden_ptw'])[::-1][:200])

In [99]:
len(inds1 & inds2), len(inds1 & inds3), len(inds2 & inds3)

(97, 38, 51)

In [100]:
inds1 = set(np.argsort(COHERENCES['topic_coherences'])[::-1][:500])
inds2 = set(np.argsort(COHERENCES['topic_coherences_toplen_ptw'])[::-1][:500])
inds3 = set(np.argsort(COHERENCES['topic_coherences_topden_ptw'])[::-1][:500])

In [101]:
len(inds1 & inds2), len(inds1 & inds3), len(inds2 & inds3)

(258, 149, 142)

### Newman-in-Intratext Density (Mutual Density / Intra-Top Density)

In [109]:
inds2 = np.argsort(COHERENCES['topic_coherences_toplen_ptw'])[::-1][:100]
inds3 = np.argsort(COHERENCES['topic_coherences_topden_ptw'])[::-1][:100]

In [110]:
np.mean(
    np.array(COHERENCES['topic_coherences'])
)

0.6880267784698945

In [111]:
np.mean(
    np.array(COHERENCES['topic_coherences'])[inds2]
)

0.9929759853960232

In [112]:
np.mean(
    np.array(COHERENCES['topic_coherences'])[inds3]
)

0.9230413598218548

In [113]:
inds2 = np.argsort(COHERENCES['topic_coherences_toplen_ptw'])[::-1][:200]
inds3 = np.argsort(COHERENCES['topic_coherences_topden_ptw'])[::-1][:200]

In [114]:
np.mean(
    np.array(COHERENCES['topic_coherences'])[inds2]
)

0.9272760323965406

In [115]:
np.mean(
    np.array(COHERENCES['topic_coherences'])[inds3]
)

0.7842457416235419

In [116]:
inds2 = np.argsort(COHERENCES['topic_coherences_toplen_ptw'])[::-1][:500]
inds3 = np.argsort(COHERENCES['topic_coherences_topden_ptw'])[::-1][:500]

In [117]:
np.mean(
    np.array(COHERENCES['topic_coherences'])[inds2]
)

0.8172972792504491

In [118]:
np.mean(
    np.array(COHERENCES['topic_coherences'])[inds3]
)

0.6594688636842502