In [1]:
import os
import json
import shutil
import sys

import numpy as np
import scipy

In [2]:
sys.path.insert(0, '../OptimalNumberOfTopics')

In [3]:
import topnum

from topnum.scores.perplexity_score import PerplexityScore
from topnum.scores.diversity_score import DiversityScore, KNOWN_METRICS
from topnum.model_constructor import init_model_from_family, KnownModel, PARAMS_EXPLORED, init_plsa

In [4]:
import artm
from artm import ARTM, Dictionary

import topicnet
from topicnet.cooking_machine.dataset import Dataset
from topicnet.cooking_machine.models import (
    BaseScore as BaseTopicNetScore,
    TopicModel
)
from topicnet.cooking_machine.models.base_regularizer import BaseRegularizer
from topicnet.cooking_machine.models.thetaless_regularizer import (
    dataset2sparse_matrix,
)

from topicnet.cooking_machine.models.topic_model import ARTM_NINE
from topicnet.cooking_machine.models.base_regularizer import BaseRegularizer
from topicnet.viewers.top_documents_viewer import TopDocumentsViewer
from topicnet.viewers.top_tokens_viewer import TopTokensViewer
from topicnet.cooking_machine.model_constructor import (
    add_standard_scores,
    create_default_topics,
    count_vocab_size,
    init_model,
)
from topicnet.cooking_machine.rel_toolbox_lite import (
    count_vocab_size,
    modality_weight_rel2abs,
    transform_regularizer,
)


import numpy as np
import pandas as pd
from pandas import DataFrame
from scipy.spatial.distance import cdist

import os
import tempfile
import warnings
from copy import deepcopy
from typing import Dict, List, Optional

In [5]:
NUM_TOPICS = 50  # TODO: this value does not affect anything

NUM_ITERATIONS = 5
NUM_TOP_TOKENS = 20
NUM_TRAINS = 20

In [6]:
BERTOPIC_FOLDER_PATH = '/data_mil/shared/CompressaAI/BERTopic'

In [7]:
! ls $BERTOPIC_FOLDER_PATH

results  results50

In [8]:
! ls $BERTOPIC_FOLDER_PATH/results50

20newsgroups  mkb10  postnauka	rtlwikiperson  ruwikigood

In [9]:
RESULTS_FOLDER_PATH = os.path.join(BERTOPIC_FOLDER_PATH, 'results50', 'rtlwikiperson')

In [10]:
RESULTS_FOLDER_PATH

'/data_mil/shared/CompressaAI/BERTopic/results50/rtlwikiperson'

In [11]:
! ls results50

20newsgroups  mkb10  postnauka	rtlwikiperson  ruwikigood

In [12]:
SAVE_FOLDER = os.path.join('results50', 'rtlwikiperson')

In [13]:
SAVE_FOLDER

'results50/rtlwikiperson'

In [14]:
! ls $SAVE_FOLDER

ablation_study	    iterative_1000000.json	lda.json     tless.json
decorrelation.json  iterative2_1000000000	plsa.json
iterative_1000000   iterative2_1000000000.json	sparse.json

In [15]:
! ls $RESULTS_FOLDER_PATH

0  1  10  11  12  13  14  15  16  17  18  19  2  3  4  5  6  7	8  9

In [16]:
! ls $RESULTS_FOLDER_PATH/0

dataset.csv  phi.csv  top_words.json

In [17]:
dataset = Dataset(
    f'{RESULTS_FOLDER_PATH}/0/dataset.csv',
)

dataset.get_possible_modalities()

{'@lemmatized'}

In [18]:
MAIN_MODALITY = '@lemmatized'

In [19]:
def calc_doc_occurrences(dataset, modality):
    """
    :param n_dw_matrix: sparse document-word matrix, shape is D x W
    :return: sparse matrix of co-occurrences

    doc_occurrences[w1, w2] = the number of the documents
    where there are w1 and w2
    """
    n_dw_matrix = dataset2sparse_matrix(dataset, modality, modalities_to_use=[modality])
    matrix = (scipy.sparse.csc_matrix(n_dw_matrix) > 0).astype(int)
    co_occurrences = matrix.T * matrix

    return co_occurrences.diagonal(), co_occurrences


def create_pmi_top_function(
    doc_occurrences, doc_co_occurrences,
    documents_number, top_sizes,
    topic_indices,
    co_occurrences_smooth=1.
):
    """
    :param doc_occurrences: array of doc occurrences of words
    :param doc_co_occurrences: sparse matrix of doc co-occurrences of words
    :param documents_number: number of the documents
    :param top_sizes: list of top values to calculate top-pmi for
    :param co_occurrences_smooth: constant to smooth co-occurrences in log
    :return: function which takes phi and theta and returns
    pair of two arrays: pmi-s of the tops and ppmi-s of the tops

    pmi[i] - pmi(top of size top_sizes[i])
    ppmi[i] - ppmi(top of size top_sizes[i])

    pmi(words) = sum_{u in words, v in words, u != v}
    log(
        (doc_co_occurrences[u, v] * documents_number + co_occurrences_smooth)
        / doc_occurrences[u] / doc_occurrences[v]
    )

    ppmi(words) = sum_{u in words, v in words, u != v}
    max(log(
        (doc_co_occurrences[u, v] * documents_number + co_occurrences_smooth)
        / doc_occurrences[u] / doc_occurrences[v]
    ), 0)

    """
    def func(phi):
        _T, W = phi.shape
        T = len(topic_indices)

        max_top_size = max(top_sizes)
        topic_pmis, topic_ppmis = dict(), dict()
        pmi, ppmi = np.zeros(max_top_size), np.zeros(max_top_size)
        tops = np.argpartition(phi, -max_top_size, axis=1)[:, -max_top_size:]
        
        for t in topic_indices:
            top = sorted(tops[t], key=lambda w: - phi[t, w])
            co_occurrences = doc_co_occurrences[top, :][:, top].todense()
            occurrences = doc_occurrences[top]
            values = np.log(
                (co_occurrences * documents_number + co_occurrences_smooth)
                / (occurrences[:, np.newaxis] * occurrences[np.newaxis, :] + co_occurrences_smooth)
            )
            diag = np.diag_indices(len(values))
            # values.cumsum(axis=0).cumsum(axis=1)[diag] - values[diag].cumsum()

            current_pmi = np.array(
               values.cumsum(axis=0).cumsum(axis=1)[diag] - values[diag].cumsum()
            ).ravel()
            topic_pmis[t] = current_pmi
            pmi += current_pmi

            values[values < 0.] = 0.
            current_ppmi = np.array(
               values.cumsum(axis=0).cumsum(axis=1)[diag] - values[diag].cumsum()
            ).ravel()
            topic_ppmis[t] = current_ppmi
            ppmi += current_ppmi
            
        sizes = np.arange(2, max_top_size + 1)
        pmi[1:] /= (T * sizes * (sizes - 1))
        ppmi[1:] /= (T * sizes * (sizes - 1))
        indices = np.array(top_sizes) - 1

        for t in topic_indices:
            topic_pmis[t][1:] /= (sizes * (sizes - 1))
            topic_ppmis[t][1:] /= (sizes * (sizes - 1))

        result_topic_pmis = {t: p[indices] for t, p in topic_pmis.items()}
        result_topic_ppmis = {t: p[indices] for t, p in topic_ppmis.items()}

        return pmi[indices], ppmi[indices], result_topic_pmis, result_topic_ppmis

    return func

In [20]:
%%time

occurences, co_occurences = calc_doc_occurrences(dataset, MAIN_MODALITY)

CPU times: user 23.2 s, sys: 6.16 s, total: 29.3 s
Wall time: 29 s

In [21]:
co_occurences.shape

(155407, 155407)

In [22]:
calc_pmi = create_pmi_top_function(
    occurences, co_occurences,
    dataset.get_dataset().shape[0], [20],
    topic_indices=[0, 1, 2],
    co_occurrences_smooth=1e-2,
)

In [23]:
class TopTokenCoherence(BaseTopicNetScore):
    def __init__(self, name, func):
        super().__init__()

        self._name = name
        self.calc_pmi = func

    def call(self, model: TopicModel):
        values = self.calc_pmi(model.get_phi_dense()[0].T)

        return values[1]

    def call_by_topic(self, model: TopicModel):
        values = self.calc_pmi(model.get_phi_dense()[0].T)

        return values[3]

In [24]:
def view_model(
        topic_model,
        dataset,
        num_top_tokens: int = 5,
        top_tokens_method: str = 'phi',
        num_topics: Optional[int] = 5,  # we do not want to fill the whole .ipynb notebook with topics...
        ):
    top_tok_viewer = TopTokensViewer(
        topic_model, num_top_tokens=num_top_tokens, method=top_tokens_method
    )
    top_doc_viewer = TopDocumentsViewer(topic_model, dataset=dataset)
    top_docs = top_doc_viewer.view()

    if num_topics is None:
        num_topics = len(topic_model.topic_names)

    for topic_name in topic_model.topic_names[:num_topics]:
        topic_top_toks = top_tok_viewer.to_html(topic_names=[topic_name])
        topic_top_docs = top_docs[topic_name]
        display_html(topic_top_toks, raw=True)
        display(topic_top_docs)

In [25]:
class FastFixPhiRegularizer(BaseRegularizer):
    _VERY_BIG_TAU = 10 ** 9

    def __init__(self, name: str, topic_names: List[str], parent_model=None, parent_phi=None, words=None):
        super().__init__(name, tau=self._VERY_BIG_TAU)

        self._topic_names = topic_names
        self._topic_indices = None
        self._words = words
        self._word_indices = None
        self._parent_model = parent_model
        self._parent_phi = parent_phi

    def grad(self, pwt, nwt):
        # print('Fixing')

        rwt = np.zeros_like(pwt)

        if self._parent_phi is not None:
            parent_phi = self._parent_phi
            vals = parent_phi.values
        else:
            assert False

            parent_phi = self._parent_model.get_phi()
            vals = parent_phi.values[:, self._topic_indices]

        if self._word_indices is None:
            assert vals.shape[0] == rwt.shape[0], (vals.shape[0], rwt.shape[0])
        else:
            assert vals.shape[0] == len(self._word_indices)

        assert vals.shape[1] == len(self._topic_indices)

        if self._word_indices is None:
            rwt[:, self._topic_indices] += vals
        else:
            # print(len(self._word_indices), len(self._topic_indices), rwt.shape, vals.shape)
            # print(self._word_indices[:3], self._topic_indices[:3])
            # print(rwt[np.ix_(self._word_indices, self._topic_indices)].shape, vals.shape)

            # https://github.com/numpy/numpy/issues/5574
            # https://github.com/numpy/numpy/issues/13255
            rwt[np.ix_(self._word_indices, self._topic_indices)] += vals

            # print(np.ix_(self._word_indices, self._topic_indices)[:3])

        return self.tau * rwt

    def attach(self, model):
        super().attach(model)
        
        phi = self._model.get_phi()
        self._topic_indices = [
            phi.columns.get_loc(topic_name)
            for topic_name in self._topic_names
        ]

        if self._words is not None:
            self._word_indices = [
                # phi.index.get_loc(w) for w in self._words
                int(phi.index.get_loc(w)) for w in self._words
            ]

            # print(f'!!! Word indices: {self._word_indices}')

In [26]:
def fit_and_compute_scores(model, dataset, target_topic_indices=None, custom_regularizers=None):
    print(custom_regularizers)

    model._fit(dataset.get_batch_vectorizer(), num_iterations=NUM_ITERATIONS, custom_regularizers=custom_regularizers)

    score_values = {
        'perplexity': model.scores[f'PerplexityScore{MAIN_MODALITY}'][-1],
    }

    phi = model.get_phi()

    # Currently all topics are taken into account

    if target_topic_indices is None:
        target_topic_indices = list(range(NUM_TOPICS))  # phi.columns.get_loc()

    target_topic_names = [phi.columns[i] for i in target_topic_indices]

    top = NUM_TOP_TOKENS
    coherence_score = TopTokenCoherence(
        name=f'coherence_{top}',
        func=create_pmi_top_function(
            occurences, co_occurences,
            dataset.get_dataset().shape[0], [top],
            topic_indices=target_topic_indices,
            co_occurrences_smooth=1e-2,
        )
    )

    value = coherence_score.call(model)
    score_values[coherence_score._name] = value
    topic_coherences = coherence_score.call_by_topic(model)
    topic_coherences = {t: float(v) for t, v in topic_coherences.items()}

    diversity_scores = [
        DiversityScore(
            name=f'diversity_{metric}',
            metric=metric,
            topic_names=target_topic_names,
            class_ids=MAIN_MODALITY,
        )
    
        for metric in KNOWN_METRICS
    ]
    
    for score in diversity_scores:
        value = score.call(model)
        score_values[score._name] = value

    return {
        'scores': score_values,
        'topic_coherences': topic_coherences,
    }

In [27]:
def init_model_from_family(
        family: str or KnownModel,
        dataset: Dataset,
        main_modality: str,
        num_topics: int,
        seed: int,
        specific_topic_names = None,
        modalities_to_use: List[str] = None,
        num_processors: int = 3,
        model_params: dict = None,
):
    """
    Returns
    -------
    model: TopicModel() instance
    """
    if isinstance(family, KnownModel):
        family = family.value

    if modalities_to_use is None:
        modalities_to_use = [main_modality]

    custom_regs = {}

    if family == "LDA":
        model = init_lda(
            dataset, modalities_to_use, main_modality, num_topics, model_params
        )
    elif family == "PLSA":
        model = init_plsa(
            dataset, modalities_to_use, main_modality, num_topics
        )
    elif family == "TARTM":
        model, custom_regs = init_thetaless(
            dataset, modalities_to_use, main_modality, num_topics, model_params
        )
    elif family == "sparse":
        model = init_bcg_sparse_model(
            dataset, modalities_to_use, main_modality, num_topics, 1, model_params
        )
    elif family == "decorrelation":
        model = init_decorrelated_plsa(
            dataset, modalities_to_use, main_modality, num_topics, model_params
        )
    elif family == "ARTM":
        model = init_baseline_artm(
            dataset, modalities_to_use, main_modality, num_topics, 1, specific_topic_names, model_params
        )
    else:
        raise ValueError(f'family: {family}')

    model.num_processors = num_processors

    if seed is not None:
        model.seed = seed

    dictionary = dataset.get_dictionary()

    # TODO: maybe this cycle is not necessary
    for modality in dataset.get_possible_modalities():
        if modality not in modalities_to_use:
            dictionary.filter(class_id=modality, max_df=0, inplace=True)

    model.initialize(dictionary)
    add_standard_scores(model, dictionary, main_modality=main_modality,
                        all_modalities=modalities_to_use)

    model = TopicModel(
        artm_model=model,
        custom_regularizers=custom_regs
    )

    return model


def init_bcg_sparse_model(
        dataset,
        modalities_to_use,
        main_modality,
        specific_topics,
        bcg_topics,
        specific_topic_names = None,
        model_params: dict = None
):
    """
    Creates simple artm model with standard scores.

    Parameters
    ----------
    dataset : Dataset
    modalities_to_use : list of str or dict
    main_modality : str
    specific_topics : int
    bcg_topics : int

    Returns
    -------
    model: artm.ARTM() instance
    """
    if model_params is None:
        model_params = dict()

    model = init_plsa(
        dataset, modalities_to_use, main_modality, specific_topics, bcg_topics
    )
    background_topic_names = model.topic_names[-bcg_topics:]

    if specific_topic_names is None:
        print('No spec topics')
        specific_topic_names = model.topic_names[:-bcg_topics]

    dictionary = dataset.get_dictionary()
    baseline_class_ids = {class_id: 1 for class_id in modalities_to_use}
    data_stats = count_vocab_size(dictionary, baseline_class_ids)

    # all coefficients are relative
    regularizers = [
        artm.SmoothSparsePhiRegularizer(
             name='smooth_phi_bcg',
             topic_names=background_topic_names,
             tau=model_params.get("smooth_bcg_tau", 0.1),
             class_ids=[main_modality],
        ),
        artm.SmoothSparseThetaRegularizer(
             name='smooth_theta_bcg',
             topic_names=background_topic_names,
             tau=model_params.get("smooth_bcg_tau", 0.1),
        ),
        artm.SmoothSparsePhiRegularizer(
             name='sparse_phi_sp',
             topic_names=specific_topic_names,
             tau=model_params.get("sparse_sp_tau", -0.05),
             class_ids=[main_modality],
            ),
        artm.SmoothSparseThetaRegularizer(
             name='sparse_theta_sp',
             topic_names=specific_topic_names,
             tau=model_params.get("sparse_sp_tau", -0.05),
        ),
    ]
    for reg in regularizers:
        model.regularizers.add(transform_regularizer(
            data_stats,
            reg,
            model.class_ids,
            n_topics=len(reg.topic_names)
        ))

    return model


def init_baseline_artm(
        dataset,
        modalities_to_use,
        main_modality,
        num_topics,
        bcg_topics,
        specific_topic_names = None,
        model_params: dict = None,
):
    """
    Creates simple artm model with standard scores.

    Parameters
    ----------
    dataset : Dataset
    modalities_to_use : list of str
    main_modality : str
    num_topics : int

    Returns
    -------
    model: artm.ARTM() instance
    """
    if model_params is None:
        model_params = dict()

    model = init_bcg_sparse_model(
        dataset, modalities_to_use, main_modality, num_topics, bcg_topics, specific_topic_names, model_params
    )

    if specific_topic_names is None:
        print('No spec topics')
        specific_topic_names = model.topic_names[:-bcg_topics]

    model.regularizers.add(
        artm.DecorrelatorPhiRegularizer(
            gamma=0,
            tau=model_params.get('decorrelation_tau', 0.01),
            name='decorrelation',
            topic_names=specific_topic_names,
            class_ids=modalities_to_use,
        )
    )

    return model

In [28]:
TOPIC_INDICES = list(range(NUM_TOPICS))

In [29]:
TOPIC_INDICES

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49]

In [30]:
phi0 = pd.read_csv(f'{RESULTS_FOLDER_PATH}/0/phi.csv', index_col=0)

In [31]:
phi0.head()

,background_1,topic_0,topic_1,topic_2,topic_3,topic_4,topic_5,topic_6,topic_7,topic_8,...,topic_40,topic_41,topic_42,topic_43,topic_44,topic_45,topic_46,topic_47,topic_48,topic_49
00,0.000000,0.000000,0.0,0.000000,0.000000,0.00000,0.0,0.001087,0.0,0.000167,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
000,0.000000,0.000155,0.0,0.000213,0.000000,0.00000,0.0,0.000000,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.004254,0.0,0.0,0.0,0.0
0000030719,0.000000,0.000000,0.0,0.000000,0.000000,0.00012,0.0,0.000000,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
0001,0.000000,0.000000,0.0,0.000000,0.000203,0.00000,0.0,0.000000,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
000200027x,0.000019,0.000000,0.0,0.000000,0.000000,0.00000,0.0,0.000000,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0

In [32]:
phi0.set_index([[MAIN_MODALITY] * len(phi0.index), phi0.index], inplace=True)

In [33]:
phi0.head()

                        background_1   topic_0  topic_1   topic_2   topic_3  \
@lemmatized 00              0.000000  0.000000      0.0  0.000000  0.000000
            000             0.000000  0.000155      0.0  0.000213  0.000000
            0000030719      0.000000  0.000000      0.0  0.000000  0.000000
            0001            0.000000  0.000000      0.0  0.000000  0.000203
            000200027x      0.000019  0.000000      0.0  0.000000  0.000000

                        topic_4  topic_5   topic_6  topic_7   topic_8  ...  \
@lemmatized 00          0.00000      0.0  0.001087      0.0  0.000167  ...
            000         0.00000      0.0  0.000000      0.0  0.000000  ...
            0000030719  0.00012      0.0  0.000000      0.0  0.000000  ...
            0001        0.00000      0.0  0.000000      0.0  0.000000  ...
            000200027x  0.00000      0.0  0.000000      0.0  0.000000  ...

                        topic_40  topic_41  topic_42  topic_43  topic_44  \
@lemmatized 00               0.0       0.0       0.0       0.0       0.0
            000              0.0       0.0       0.0       0.0       0.0
            0000030719       0.0       0.0       0.0       0.0       0.0
            0001             0.0       0.0       0.0       0.0       0.0
            000200027x       0.0       0.0       0.0       0.0       0.0

                        topic_45  topic_46  topic_47  topic_48  topic_49
@lemmatized 00          0.000000       0.0       0.0       0.0       0.0
            000         0.004254       0.0       0.0       0.0       0.0
            0000030719  0.000000       0.0       0.0       0.0       0.0
            0001        0.000000       0.0       0.0       0.0       0.0
            000200027x  0.000000       0.0       0.0       0.0       0.0

[5 rows x 51 columns]

In [34]:
DIFF_THRESHOLD = 2

In [35]:
def check_top_words(phi, top_words):
    diffs = []

    for t, topic_top_words in top_words.items():
        if t == 'background_1':
            print(f'Skipping background topic: {t}.')

            continue

        print(t)
        # print(top_words)
    
        top_phi = set(phi[t].sort_values(ascending=False)[:NUM_TOP_TOKENS].index.get_level_values(1))
        top_bt = set([p[0] for p in topic_top_words])
    
        if top_phi == top_bt:
            diffs.append(
                {
                    'total': 0,
                    'lost_bt': 0,
                    'lost_model': 0,
                }
            )
        else:
            diff1 = top_phi.difference(top_bt)
            diff2 = top_bt.difference(top_phi)
    
            print('  WTF:', diff1, diff2)
    
            if len(diff1) > DIFF_THRESHOLD:
                print(f'  WTF?!?!?', len(diff1))
    
            if len(diff2) > DIFF_THRESHOLD:
                print(f'  WTF?!?!?', len(diff2))

            diffs.append(
                {
                    'total': len(diff1 | diff2),
                    'lost_bt': len(diff2),
                    'lost_model': len(diff1),
                }
            )

    return diffs

In [36]:
def init_model_and_phi(num_topics, dataset, phi0):
    model = init_model_from_family(
        family=KnownModel.PLSA,
        dataset=dataset,
        main_modality=MAIN_MODALITY,
        num_topics=num_topics,
        seed=0,
    )
    
    phi = model.get_phi()
    
    # assert phi.shape[1] == phi0.shape[1] - 1
    assert phi.shape[1] == num_topics
    assert phi.shape[1] in [phi0.shape[1], phi0.shape[1] - 1]
    
    common_words = list(set(phi.index).intersection(phi0.index))
    
    phi.loc[:, :] = 0

    if phi.shape[1] == phi0.shape[1]:
        target_topics = phi0.columns
    elif phi.shape[1] == phi0.shape[1] - 1:
        target_topics = phi.columns
    else:
        assert False

    # print(common_words, phi.index, phi0.index)

    phi.loc[common_words, :] += phi0.loc[common_words, target_topics]

    diff = set(phi0.columns).symmetric_difference(set(phi.columns))

    assert diff == {'background_1'} or diff == {'background_1', f'topic_{len(phi.columns) - 1}'}
    
    phi = phi / phi.sum(axis=0)

    return model, phi, common_words

In [38]:
results = []

is_results_loaded = False

save_file_path = os.path.join(
    SAVE_FOLDER, 'bertopic.json'
)

if os.path.isfile(save_file_path):
    results = json.loads(
        open(save_file_path).read()
    )
    is_results_loaded = True


singles_save_folder = os.path.join(
    SAVE_FOLDER, 'bertopic'
)

os.makedirs(singles_save_folder, exist_ok=True)


for seed in range(NUM_TRAINS):
    if is_results_loaded:
        continue

    print(seed)

    current_save_file_path = os.path.join(
        singles_save_folder, f'bertopic_{seed}.json'
    )

    if os.path.isfile(current_save_file_path):
        print(f'Already computed results: {current_save_file_path}. Loading and skipping...')

        result = json.loads(
            open(current_save_file_path).read()
        )
        results.append(result)

        continue

    seed_load_folder = os.path.join(RESULTS_FOLDER_PATH, str(seed))
    files = [f for f in os.listdir(seed_load_folder) if os.path.isfile(f'{seed_load_folder}/{f}')]
    
    assert len(files) == 3

    dataset = Dataset(
        f'{seed_load_folder}/dataset.csv',
    )
    phi0 = pd.read_csv(f'{seed_load_folder}/phi.csv', index_col=0)
    phi0.set_index([[MAIN_MODALITY] * len(phi0.index), phi0.index], inplace=True)

    assert all('back' not in t for t in phi0.columns[1:])
    assert 'back' in phi0.columns[0]

    num_specific_topics = phi0.shape[1] - 1

    assert num_specific_topics == len([t for t in phi0.columns if 'back' not in t])

    print(f'Num model topics: {phi0.shape[1]}.')

    with open(f'{seed_load_folder}/top_words.json', 'r') as f:
        top_words = json.loads(f.read())


    
    model, phi, common_phi_words = init_model_and_phi(
        num_topics=num_specific_topics + 1,  # background
        dataset=dataset, phi0=phi0
    )
    common_words = [
        w[1] for w in common_phi_words  # without modality
    ]
    common_words_phi0_indices = [
        # phi0.index.get_loc(w) for w in common_words
        int(phi0.index.get_locs(w)) for w in common_phi_words
    ]

    print('Check before fit:')
    diff_tops1 = check_top_words(phi, top_words)  # Whatever...
    
    fix_regularizer = FastFixPhiRegularizer(
        name='fix',
        parent_phi=phi0.iloc[common_words_phi0_indices, 1:],
        words=common_words,
        topic_names=phi.columns[1:],
    )
    result = fit_and_compute_scores(
        model, dataset,
        target_topic_indices=list(range(phi.shape[1])),
        custom_regularizers = {
            fix_regularizer.name: fix_regularizer,
        }
    )

    print('Check after fit:')
    diff_tops2 = check_top_words(phi, top_words)  # Whatever...

    assert diff_tops1 == diff_tops2

    fair_ppl_free = result['scores']['perplexity']

    del model, phi, fix_regularizer, result


    
    model, phi, _ = init_model_and_phi(
        num_topics=num_specific_topics + 1,  # background
        dataset=dataset, phi0=phi0
    )
    fix_regularizer = FastFixPhiRegularizer(
        name='fix',
        parent_phi=phi0.iloc[common_words_phi0_indices, :],  # Diff here
        words=common_words,
        topic_names=phi.columns,
    )
    result = fit_and_compute_scores(
        model, dataset,
        target_topic_indices=list(range(phi.shape[1])),
        custom_regularizers = {
            fix_regularizer.name: fix_regularizer,
        }
    )
    
    fair_ppl_fix = result['scores']['perplexity']

    del model, phi, fix_regularizer, result

    
    
    model, phi, _ = init_model_and_phi(
        num_topics=num_specific_topics,  # Diff here
        dataset=dataset, phi0=phi0
    )
    fix_regularizer = FastFixPhiRegularizer(
        name='fix',
        parent_phi=phi0.iloc[common_words_phi0_indices, 1:],  # Diff here
        words=common_words,
        topic_names=phi.columns,
    )
    result = fit_and_compute_scores(
        model, dataset,
        custom_regularizers = {
            fix_regularizer.name: fix_regularizer,
        }
    )

    unfair_ppl_banklike = result['scores']['perplexity']


    
    result['scores']['fair_ppl_free'] = fair_ppl_free
    result['scores']['fair_ppl_fix'] = fair_ppl_fix
    result['scores']['unfair_ppl_banklike'] = unfair_ppl_banklike

    assert result['scores']['fair_ppl_free'] < result['scores']['unfair_ppl_banklike']
    # assert result['scores']['fair_ppl_fix'] < result['scores']['unfair_ppl_banklike']

    result['scores']['coherence_20'] = float(result['scores']['coherence_20'])
    result['stats'] = {
        'num_topics': phi0.shape[1],
        'num_common_words': len(common_words),
        'num_model_words': phi.shape[0],
        'num_bt_words': phi0.shape[0],
        'top_diffs': diff_tops2,
    }

    results.append(result)

    print(result['scores'])
    print(result['stats'])

    dumped_result = json.dumps(
        results[-1], indent=4
    )

    with open(current_save_file_path, 'w') as f:
        f.write(dumped_result)

    del model, phi, fix_regularizer


with open(save_file_path, 'w') as f:
    f.write(
        json.dumps(
            results, indent=4
        )
    )

0
Already computed results: results50/rtlwikiperson/bertopic/bertopic_0.json. Loading and skipping...
1
Already computed results: results50/rtlwikiperson/bertopic/bertopic_1.json. Loading and skipping...
2
Already computed results: results50/rtlwikiperson/bertopic/bertopic_2.json. Loading and skipping...
3
Already computed results: results50/rtlwikiperson/bertopic/bertopic_3.json. Loading and skipping...
4
Already computed results: results50/rtlwikiperson/bertopic/bertopic_4.json. Loading and skipping...
5
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
  WTF: {'energy', 'later', 'von', 'years'} {'bohr', 'kepler', 'planck', 'marconi'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_1
  WTF: {'du', 'philosophy', 'later', 'time', 'life', 'press', 'published', 'corbusier', 'museum', 'et'} {'sartre', 'paris', 'lacan', 'rodin', 'rousseau', 'satie', 'david', 'camus', 'warhol', 'baudelaire'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_2
  WTF: {'san', 'marble', 'father', 'cardinal', 'life', 'del', 'st', 'il', 'church', 'new'} {'francis', 'caravaggio', 'calvino', 'florence', 'rome', 'borgia', 'lucrezia', 'cesare', 'fellini', 'bruno'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_3
  WTF: {'dio', 'greek', 'emperors', 'caesars', 'life', 'ce', 'gibbon', 'senate', 'death', 'ancient', 'caesar', 'imperial'} {'augustus', 'rome', 'barnes', 'julian', 'eusebius', 'constantius', 'claudius', 'caligula', 'tiberius', 'diocletian', 'tacitus', 'suetonius'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_4
  WTF: {'army', 'palace', 'turkey', 'son', 'medicine', 'battle', 'time', 'ali', 'muslims', 'ii'} {'afghanistan', 'persian', 'abd', 'meher', 'rumi', 'arrahman', 'islamic', 'muhammad', 'abu', 'ahmad'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_5
  WTF: {'meat', 'recording', 'loaf'} {'elvis', 'presley', 'davis'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_6
  WTF: {'machine', 'project', 'information', 'language', 'work', 'institute', 'operating', 'interview', 'award'} {'shannon', 'minsky', 'sanger', 'turing', 'engelbart', 'warwick', 'babbage', 'zuse', 'wikipedia'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_7
  WTF: {'army', 'chess', 'military', 'film', 'committee', 'state', 'time', 'world', 'revolution', 'government', 'march', 'ii', 'order', 'new'} {'russian', 'moscow', 'trotsky', 'khmelnytsky', 'alexander', 'nicholas', 'stalin', 'chekhov', 'beria', 'gorbachev', 'tito', 'kasparov', 'yeltsin', 'russia'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_8
  WTF: {'series', 'world', 'books', 'english', 'mars'} {'steinbeck', 'moorcock', 'crichton', 'verne', 'pohl'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_9
  WTF: {'musical', 'string', 'words', 'quartet', 'cello', 'trio', 'da'} {'elgar', 'wk', 'handel', 'shostakovich', 'hoffmann', 'lugosi', 'haydn'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_10
  WTF: {'army', 'married', 'chancellor', 'military', 'otto', 'margrave', 'prince', 'emperor', 'iii', 'ii', 'died', 'maternal', 'insurance', 'paternal'} {'germany', 'clausewitz', 'gustavus', 'joachim', 'prussia', 'albert', 'albertus', 'bismarck', 'bismarcks', 'prussian', 'brandenburg', 'saxony', 'frederick', 'dresden'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_11
  WTF: {'grand', 'career', 'championship', 'lost', 'wickets', 'world'} {'jordan', 'earnhardt', 'agassi', 'muralitharan', 'schumacher', 'hingis'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_12
  WTF: {'production', 'role', 'directors', 'time', 'screenplay', 'directed', 'directing', 'brothers', 'new'} {'coen', 'cukor', 'scorsese', 'warren', 'david', 'york', 'mcgilligan', 'cameron', 'cagney'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_13
  WTF: {'war', 'hearings', 'baron', 'pp', 'supreme', 'union', 'american', 'beacon'} {'rumsfeld', 'carson', 'jay', 'stuart', 'oswald', 'hancock', 'davis', 'thomas'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_14
  WTF: {'war', 'empereurs', 'senso', 'japon', 'lady', 'clan', 'month', 'emperors', 'son', 'throne', 'court'} {'chinese', 'minamoto', 'nichiren', 'chiang', 'fujiwara', 'titsingh', 'kaishek', 'japanese', 'japan', 'deng', 'varley'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_15
  WTF: {'episodes', 'role', '2008', 'movie', 'awards', 'voice', 'nominated', 'radio', 'played'} {'leary', 'belushi', 'voight', 'keillor', 'palin', 'letterman', 'coleman', 'leno', 'grammer'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_16
  WTF: {'woman', 'poems', 'short', 'stories', 'books', 'introduction', 'wrote', 'family', 'life', 'story', 'fiction', 'works', 'letters', 'press', 'women'} {'seymour', 'charlotte', 'shelleys', 'hawthorne', 'shelley', 'anne', 'bronts', 'godwin', 'jane', 'austens', 'austen', 'tomalin', 'wollstonecraft', 'mary', 'percy'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_17
  WTF: {'tours', 'book', 'testament', 'writings', 'life', 'catholic', 'feast', 'bishop', 'roman', 'chapter', 'god', 'heresies'} {'christ', 'chrysostom', 'athanasius', 'anthony', 'luke', 'jesus', 'irenaeus', 'ephrem', 'alexandria', 'cyril', 'mary', 'martin'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_18
  WTF: {'scientific', 'behavior', 'pragmatism', 'knowledge', 'work', 'philosophical', 'logical', 'published', 'social', 'psychology', 'mathematics', 'sign'} {'dewey', 'skinner', 'rothbard', 'bertrand', 'hayek', 'russell', 'russells', 'peirce', 'peirces', 'friedman', 'milken', 'popper'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_19
  WTF: {'black', 'career', '2008', 'television', 'appeared', 'days', '2006', '2005', 'new'} {'doris', 'anderson', 'kidman', 'robeson', 'robesons', 'paul', 'duberman', 'theron', 'naomi'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_20
  WTF: {'war', 'voyage', '2004', 'forces', 'sir', 'admiral', 'commander', 'ship', 'ships', 'general', 'lord', 'spanish', 'royal'} {'british', 'drake', 'nelson', 'wellington', 'alexander', 'hibbert', 'montgomery', 'india', 'wellesley', 'mountbatten', 'blackbeard', 'auchinleck', 'sugden'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_21
  WTF: {'war', 'expedition', 'civil', 'king', 'city', 'military', 'married', 'la', 'issue', 'doa', 'president', 'troops', 'leader', 'government', 'new'} {'madero', 'alfonso', 'ortega', 'almagro', 'xavier', 'corts', 'cid', 'aztec', 'pizarro', 'daz', 'francisco', 'madrid', 'franco', 'mexico', 'moctezuma'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_22
  WTF: {'nobel', 'world', 'theory', 'cowpox', 'university', 'research', 'discovery', 'royal', 'physician'} {'fleming', 'london', 'koch', 'pasteur', 'carrel', 'lister', 'jenner', 'edinburgh', 'hutton'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_23
  WTF: {'war', 'harbor', 'moon', 'series', 'admiral', 'anime', 'pearl', 'born', 'carrier', 'american', 'midway', 'dragon'} {'akira', 'kahanamoku', 'japanese', 'hearn', 'yamamoto', 'kurosawa', 'lafcadio', 'fukuyama', 'morita', 'japan', 'yamamotos', 'ueshiba'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_24
  WTF: {'married', 'isbn', 'kingdom', 'ed', 'pp', 'chronicle', 'iii', 'isles', 'kingship', 'died', 'death', 'ii', 'english', 'saga', 'killed'} {'macbeth', 'selkirk', 'coluim', 'scots', 'kenneth', 'oram', 'alexander', 'scotland', 'maclaurin', 'mel', 'alba', 'malcolm', 'duncan', 'malcolms', 'scottish'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_25
  WTF: {'systems', 'die', 'reason', 'zur', 'ed', 'society', 'trans', 'objects', 'psychology', 'phenomenology'} {'luhmann', 'husserl', 'schwitters', 'husserls', 'ebbinghaus', 'berlin', 'habermas', 'schumpeter', 'fichte', 'frankfurt'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_26
  WTF: {'army', 'spain', 'tours', 'great', 'son', 'empire', 'iii', 'duc', 'ii', 'duke', 'spanish', 'imperial'} {'martel', 'france', 'italy', 'eugene', 'eugenes', 'europe', 'savoy', 'charlemagne', 'frankish', 'charles', 'louis', 'bernard'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_27
  WTF: {'trial', 'dictionary', 'reflections', 'pp', 'gin', 'society', 'haven', 'meetings', 'published', 'prior', 'english', 'church', 'christian'} {'yale', 'abbott', 'alcott', 'burke', 'foxs', 'connecticut', 'eli', 'mather', 'whitney', 'burkes', 'quakers', 'webster', 'nickalls'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_28
  WTF: {'married', 'grand', 'ca', 'daughter', 'empress', 'family', 'queen', 'emperor', 'sister', 'sons', 'ii', 'death', 'died', 'lands', 'brother'} {'mieszko', 'bolesaw', 'jadwiga', 'poland', 'feodorovna', 'lithuania', 'hungary', 'leszek', 'krakw', 'miller', 'lithuanian', 'casimir', 'maria', 'mindaugas', 'jadwigas'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_29
  WTF: {'succession', 'reign', 'vii', 'earl', 'council', 'protestant', 'throne', 'duke', 'marriage', 'ii', 'death', 'kings', 'royal'} {'england', 'elizabeth', 'anne', 'wales', 'edward', 'owain', 'henrys', 'henry', 'charles', 'catherine', 'tudor', 'elizabeths', 'mary'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_30
  WTF: {'expedition', 'arctic', 'actress', 'film', 'new', 'books', 'work', 'life', 'play', 'polar', 'works', '2005', 'award', 'scream', 'museum', 'metamorphosis', 'art'} {'alvar', 'nansen', 'kafkas', 'norway', 'finland', 'ibsen', 'ullmann', 'eggum', 'franz', 'munch', 'helsinki', 'kafka', 'rasmussen', 'fridtjof', 'aalto', 'prideaux', 'munchs'}
  WTF?!?!? 17
  WTF?!?!? 17
topic_31
  WTF: {'conservative', 'foreign', 'crisis', 'pages', 'page', 'cabinet', '1939'} {'british', 'hawke', 'disraeli', 'fraser', 'attlee', 'holt', 'tupper'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_32
  WTF: {'poets', 'years', 'later', 'ed', 'english', 'donnes', 'published', 'works', 'poet', 'death', 'letters', 'nonsense', 'literature'} {'london', 'hopkinss', 'alice', 'severn', 'lewis', 'lear', 'dodgson', 'keats', 'housmans', 'shropshire', 'carroll', 'hopkins', 'housman'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_33
  WTF: {'police', 'army', 'chancellor', 'law', '1945', 'foreign', 'von', 'political', 'power', 'nazis', 'crimes', 'sa', 'people', 'face'} {'waldheim', 'germany', 'reich', 'goebbels', 'gring', 'berlin', 'luftwaffe', 'hitlers', 'hitler', 'kershaw', 'grings', 'reichstag', 'nazi', 'himmler'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_34
  WTF: {'hijackers', 'united', 'detainees', 'department', 'waterboarding', 'flight', 'news', 'torture', 'states', 'officials'} {'osama', 'saudi', 'cia', 'qaeda', 'zubaydahs', 'alqaeda', 'fbi', 'zubaydah', 'hanjour', 'abu'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_35
  WTF: {'book', 'cartoonists', 'beat', 'work', 'life', 'road', 'award', 'characters', 'new'} {'thurber', 'abner', 'capp', 'barney', 'simon', 'kerouacs', 'kirby', 'lil', 'capps'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_36
  WTF: {'scientific', 'biology', 'science', 'ray', 'society', 'theory', 'animals', 'principles', 'origin', 'history', 'vol', 'edition', 'chapter'} {'slotten', 'mayr', 'haeckel', 'kikuyu', 'darwin', 'lyell', 'ernst', 'leakey', 'charles', 'wallace', 'louis', 'wallaces', 'darwins'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_37
  WTF: {'presidential', 'mission', 'military', 'flew', 'medal', 'flying', '11', 'general', 'states'} {'eisenhowers', 'eisenhower', 'dwight', 'apollo', 'aldrin', 'hopper', 'armstrong', 'hansen', 'yeager'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_38
  WTF: {'pg', 'chart', 'release', 'number', 'rb', 'singles', 'new', 'billboard'} {'uk', 'hatfield', 'mariah', 'careys', 'aaliyah', 'carey', 'enya', 'difranco'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_39
  WTF: {'differences', 'scientists', 'behavior', 'environmentalist', 'individual', 'carl', 'research'} {'rogers', 'wilson', 'rushton', 'jensens', 'venter', 'lomborg', 'jensen'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_40
  WTF: {'daughter', 'navigator', 'coast', 'prince', 'mother', 'iii', 'ii', 'expeditions', 'infanta', 'infante'} {'afonso', 'len', 'albuquerque', 'castile', 'portuguese', 'sancho', 'henry', 'portugal', 'aragon', 'coimbra'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_41
  WTF: {'performed', 'musical', 'pensiero', 'film', 'chorus', 'requiem', 'libretto', 'del', 'works'} {'rossini', 'morricone', 'busseto', 'ennio', 'rossinis', 'verdis', 'giuseppe', 'morricones', 'gioachino'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_42
  WTF: {'house', 'collected', 'world', 'books', 'joy', 'weird', 'monthly', 'fiction', 'literary', 'writing', 'english', 'new', 'novel'} {'lewiss', 'amis', 'melville', 'lewis', 'kingsley', 'melvilles', 'williams', 'dickenss', 'conrads', 'dickens', 'charles', 'herman', 'conrad'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_43
  WTF: {'professor', 'german', 'psychiatry', 'clinical', 'symptoms', 'university', 'und', 'research', 'organism', 'asylum'} {'alzheimer', 'alzheimers', 'ehrlichs', 'berlin', 'boerhaave', 'selye', 'ehrlich', 'leiden', 'munich', 'creutzfeldt'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_44
  WTF: {'rpt', 'description', 'grammar', 'sounds', 'linguists', 'english'} {'hockett', 'whorf', 'jones', 'witwatersrand', 'bantu', 'doke'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_45
  WTF: {'cancer', 'awareness', 'lady', 'sexual', 'vote', 'education', 'election', 'husband', 'president', 'states', 'sentence', 'parole', 'prison'} {'sacramento', 'soliah', 'california', 'lewinsky', 'olson', 'eastman', 'sla', 'jane', 'clinton', 'sara', 'laura', 'fargo', 'reno'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_46
  WTF: {'conservative', 'theological', 'study', 'law', 'theology', 'prophets', 'work', 'university', 'rabbis', 'man', 'sabbath', 'studies', 'scholars'} {'heschel', 'jts', 'steinsaltz', 'hebrew', 'jewish', 'neusner', 'kushner', 'judaism', 'kaplans', 'neusners', 'talmud', 'torah', 'kaplan'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_47
  WTF: {'park', 'designs', 'glass', 'home', 'center', 'homes', 'tower', 'art'} {'wright', 'lloyd', 'taliesin', 'lin', 'wrights', 'pei', 'chicago', 'mies'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_48
  WTF: {'commissioner', 'career', 'allstar', 'tigers', 'hit', 'pitched', 'american'} {'youngs', 'greenberg', 'milwaukee', 'knute', 'mlb', 'rockne', 'cy'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_49
  WTF: {'recorder', 'musical', 'film', 'record', 'rhythm', 'minutes', 'various', 'song', 'bob', 'artists', 'score'} {'elfman', 'cbs', 'ira', 'dowland', 'crosby', 'crosbys', 'gershwin', 'dowlands', 'styne', 'burton', 'bing'}
  WTF?!?!? 11
  WTF?!?!? 11
{'fix': <__main__.FastFixPhiRegularizer object at 0x7fd2cda9ff40>}
Check after fit:
Skipping background topic: background_1.
topic_0
  WTF: {'energy', 'later', 'von', 'years'} {'bohr', 'kepler', 'planck', 'marconi'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_1
  WTF: {'du', 'philosophy', 'later', 'time', 'life', 'press', 'published', 'corbusier', 'museum', 'et'} {'sartre', 'paris', 'lacan', 'rodin', 'rousseau', 'satie', 'david', 'camus', 'warhol', 'baudelaire'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_2
  WTF: {'san', 'marble', 'father', 'cardinal', 'life', 'del', 'st', 'il', 'church', 'new'} {'francis', 'caravaggio', 'calvino', 'florence', 'rome', 'borgia', 'lucrezia', 'cesare', 'fellini', 'bruno'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_3
  WTF: {'dio', 'greek', 'emperors', 'caesars', 'life', 'ce', 'gibbon', 'senate', 'death', 'ancient', 'caesar', 'imperial'} {'augustus', 'rome', 'barnes', 'julian', 'eusebius', 'constantius', 'claudius', 'caligula', 'tiberius', 'diocletian', 'tacitus', 'suetonius'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_4
  WTF: {'army', 'palace', 'turkey', 'son', 'medicine', 'battle', 'time', 'ali', 'muslims', 'ii'} {'afghanistan', 'persian', 'abd', 'meher', 'rumi', 'arrahman', 'islamic', 'muhammad', 'abu', 'ahmad'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_5
  WTF: {'meat', 'recording', 'loaf'} {'elvis', 'presley', 'davis'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_6
  WTF: {'machine', 'project', 'information', 'language', 'work', 'institute', 'operating', 'interview', 'award'} {'shannon', 'minsky', 'sanger', 'turing', 'engelbart', 'warwick', 'babbage', 'zuse', 'wikipedia'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_7
  WTF: {'army', 'chess', 'military', 'film', 'committee', 'state', 'time', 'world', 'revolution', 'government', 'march', 'ii', 'order', 'new'} {'russian', 'moscow', 'trotsky', 'khmelnytsky', 'alexander', 'nicholas', 'stalin', 'chekhov', 'beria', 'gorbachev', 'tito', 'kasparov', 'yeltsin', 'russia'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_8
  WTF: {'series', 'world', 'books', 'english', 'mars'} {'steinbeck', 'moorcock', 'crichton', 'verne', 'pohl'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_9
  WTF: {'musical', 'string', 'words', 'quartet', 'cello', 'trio', 'da'} {'elgar', 'wk', 'handel', 'shostakovich', 'hoffmann', 'lugosi', 'haydn'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_10
  WTF: {'army', 'married', 'chancellor', 'military', 'otto', 'margrave', 'prince', 'emperor', 'iii', 'ii', 'died', 'maternal', 'insurance', 'paternal'} {'germany', 'clausewitz', 'gustavus', 'joachim', 'prussia', 'albert', 'albertus', 'bismarck', 'bismarcks', 'prussian', 'brandenburg', 'saxony', 'frederick', 'dresden'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_11
  WTF: {'grand', 'career', 'championship', 'lost', 'wickets', 'world'} {'jordan', 'earnhardt', 'agassi', 'muralitharan', 'schumacher', 'hingis'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_12
  WTF: {'production', 'role', 'directors', 'time', 'screenplay', 'directed', 'directing', 'brothers', 'new'} {'coen', 'cukor', 'scorsese', 'warren', 'david', 'york', 'mcgilligan', 'cameron', 'cagney'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_13
  WTF: {'war', 'hearings', 'baron', 'pp', 'supreme', 'union', 'american', 'beacon'} {'rumsfeld', 'carson', 'jay', 'stuart', 'oswald', 'hancock', 'davis', 'thomas'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_14
  WTF: {'war', 'empereurs', 'senso', 'japon', 'lady', 'clan', 'month', 'emperors', 'son', 'throne', 'court'} {'chinese', 'minamoto', 'nichiren', 'chiang', 'fujiwara', 'titsingh', 'kaishek', 'japanese', 'japan', 'deng', 'varley'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_15
  WTF: {'episodes', 'role', '2008', 'movie', 'awards', 'voice', 'nominated', 'radio', 'played'} {'leary', 'belushi', 'voight', 'keillor', 'palin', 'letterman', 'coleman', 'leno', 'grammer'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_16
  WTF: {'woman', 'poems', 'short', 'stories', 'books', 'introduction', 'wrote', 'family', 'life', 'story', 'fiction', 'works', 'letters', 'press', 'women'} {'seymour', 'charlotte', 'shelleys', 'hawthorne', 'shelley', 'anne', 'bronts', 'godwin', 'jane', 'austens', 'austen', 'tomalin', 'wollstonecraft', 'mary', 'percy'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_17
  WTF: {'tours', 'book', 'testament', 'writings', 'life', 'catholic', 'feast', 'bishop', 'roman', 'chapter', 'god', 'heresies'} {'christ', 'chrysostom', 'athanasius', 'anthony', 'luke', 'jesus', 'irenaeus', 'ephrem', 'alexandria', 'cyril', 'mary', 'martin'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_18
  WTF: {'scientific', 'behavior', 'pragmatism', 'knowledge', 'work', 'philosophical', 'logical', 'published', 'social', 'psychology', 'mathematics', 'sign'} {'dewey', 'skinner', 'rothbard', 'bertrand', 'hayek', 'russell', 'russells', 'peirce', 'peirces', 'friedman', 'milken', 'popper'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_19
  WTF: {'black', 'career', '2008', 'television', 'appeared', 'days', '2006', '2005', 'new'} {'doris', 'anderson', 'kidman', 'robeson', 'robesons', 'paul', 'duberman', 'theron', 'naomi'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_20
  WTF: {'war', 'voyage', '2004', 'forces', 'sir', 'admiral', 'commander', 'ship', 'ships', 'general', 'lord', 'spanish', 'royal'} {'british', 'drake', 'nelson', 'wellington', 'alexander', 'hibbert', 'montgomery', 'india', 'wellesley', 'mountbatten', 'blackbeard', 'auchinleck', 'sugden'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_21
  WTF: {'war', 'expedition', 'civil', 'king', 'city', 'military', 'married', 'la', 'issue', 'doa', 'president', 'troops', 'leader', 'government', 'new'} {'madero', 'alfonso', 'ortega', 'almagro', 'xavier', 'corts', 'cid', 'aztec', 'pizarro', 'daz', 'francisco', 'madrid', 'franco', 'mexico', 'moctezuma'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_22
  WTF: {'nobel', 'world', 'theory', 'cowpox', 'university', 'research', 'discovery', 'royal', 'physician'} {'fleming', 'london', 'koch', 'pasteur', 'carrel', 'lister', 'jenner', 'edinburgh', 'hutton'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_23
  WTF: {'war', 'harbor', 'moon', 'series', 'admiral', 'anime', 'pearl', 'born', 'carrier', 'american', 'midway', 'dragon'} {'akira', 'kahanamoku', 'japanese', 'hearn', 'yamamoto', 'kurosawa', 'lafcadio', 'fukuyama', 'morita', 'japan', 'yamamotos', 'ueshiba'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_24
  WTF: {'married', 'isbn', 'kingdom', 'ed', 'pp', 'chronicle', 'iii', 'isles', 'kingship', 'died', 'death', 'ii', 'english', 'saga', 'killed'} {'macbeth', 'selkirk', 'coluim', 'scots', 'kenneth', 'oram', 'alexander', 'scotland', 'maclaurin', 'mel', 'alba', 'malcolm', 'duncan', 'malcolms', 'scottish'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_25
  WTF: {'systems', 'die', 'reason', 'zur', 'ed', 'society', 'trans', 'objects', 'psychology', 'phenomenology'} {'luhmann', 'husserl', 'schwitters', 'husserls', 'ebbinghaus', 'berlin', 'habermas', 'schumpeter', 'fichte', 'frankfurt'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_26

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7fd2fc0954c0>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7fd2d080ccd0>}
{'perplexity': 317863.25, 'coherence_20': 0.7587745403308302, 'diversity_euclidean': 0.03418251280022939, 'diversity_jensenshannon': 0.6541867169347886, 'diversity_hellinger': 0.7675295027380634, 'diversity_cosine': 0.7367812249553637, 'fair_ppl_free': 2770.963134765625, 'fair_ppl_fix': 358211.5, 'unfair_ppl_banklike': 317863.25}
{'num_topics': 51, 'num_common_words': 65750, 'num_model_words': 155407, 'num_bt_words': 135939, 'top_diffs': [{'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 34, 'lost_bt': 17, 'lost_model': 17}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}]}
6
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
  WTF: {'philosophy', 'later', 'design', 'les', 'university', 'published', 'press', 'et'} {'sartre', 'wright', 'paris', 'lacan', 'rodin', 'rousseau', 'camus', 'warhol'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_1
  WTF: {'new', 'recorded'} {'elvis', 'presley'}
topic_2
  WTF: {'army', 'palace', 'son', 'state', 'medicine', 'time', 'battle', 'ali', 'muslims', 'government'} {'afghanistan', 'persian', 'abd', 'meher', 'rumi', 'islamic', 'india', 'muhammad', 'abu', 'ahmad'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_3
  WTF: {'dio', 'emperors', 'christian', 'caesars', 'life', 'ce', 'gibbon', 'senate', 'ad', 'death', 'ancient', 'caesar', 'imperial'} {'augustus', 'rome', 'barnes', 'julian', 'eusebius', 'constantius', 'claudius', 'caligula', 'tiberius', 'hadrian', 'diocletian', 'tacitus', 'suetonius'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_4
  WTF: {'hill', 'army', 'hearings', 'kit', 'served', 'confederate', 'supreme', 'union', 'fowler', 'american'} {'eisenhower', 'rumsfeld', 'carson', 'jay', 'stuart', 'oswald', 'hancock', 'davis', 'armstrong', 'thomas'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_5
  WTF: {'machine', 'project', 'information', 'language', 'work', 'institute', 'operating', 'interview', 'award'} {'shannon', 'minsky', 'sanger', 'turing', 'engelbart', 'warwick', 'babbage', 'zuse', 'wikipedia'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_6
  WTF: {'army', 'chess', 'military', 'film', 'committee', 'state', 'time', 'world', 'life', 'revolution', 'government', 'march', 'order', 'new'} {'russian', 'philby', 'moscow', 'trotsky', 'alexander', 'nicholas', 'stalin', 'chekhov', 'beria', 'gorbachev', 'tito', 'kasparov', 'yeltsin', 'russia'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_7
  WTF: {'professor', 'scientific', 'wireless', 'quantum', 'theremin', 'institute', 'nuclear'} {'bohr', 'fermi', 'davy', 'planck', 'faraday', 'bardeen', 'marconi'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_8
  WTF: {'pope', 'della', 'film', 'leonardo', 'marble', 'san', 'work', 'life', 'painting', 'del', 'il', 'new'} {'giordano', 'caravaggios', 'caravaggio', 'florence', 'rome', 'medici', 'lucrezia', 'borgia', 'cesare', 'angelico', 'fellini', 'bruno'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_9
  WTF: {'series', 'world', 'books', 'english', 'mars'} {'steinbeck', 'moorcock', 'crichton', 'verne', 'ballard'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_10
  WTF: {'rabbit', 'poems', 'writing', 'short', 'wrote', 'family', 'fiction', 'story', 'letters', 'press', 'new'} {'shelleys', 'hawthorne', 'shelley', 'anne', 'jane', 'austen', 'dickens', 'wollstonecraft', 'mary', 'updike', 'percy'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_11
  WTF: {'string', 'words', 'concerto', 'quartet', 'composers', 'trio', 'da'} {'elgar', 'wk', 'handel', 'shostakovich', 'hoffmann', 'lugosi', 'haydn'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_12
  WTF: {'script', 'directors', 'stone', 'time', 'actors', 'picture', 'screenplay', 'new'} {'hollywood', 'scorsese', 'hitchcocks', 'warren', 'hitchcock', 'mcgilligan', 'cameron', 'cagney'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_13
  WTF: {'grand', 'career', 'championship', 'lost', 'wickets', 'world'} {'jordan', 'earnhardt', 'agassi', 'muralitharan', 'schumacher', 'hingis'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_14
  WTF: {'army', 'married', 'chancellor', 'military', 'otto', 'margrave', 'prince', 'emperor', 'iii', 'ii', 'magnus', 'maternal', 'insurance', 'paternal'} {'germany', 'clausewitz', 'gustavus', 'joachim', 'prussia', 'albert', 'albertus', 'bismarck', 'bismarcks', 'prussian', 'brandenburg', 'saxony', 'frederick', 'dresden'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_15
  WTF: {'surgeon', 'nobel', 'world', 'theory', 'stress', 'vaccination', 'discovery', 'physician'} {'fleming', 'koch', 'pasteur', 'carrel', 'lister', 'jenner', 'edinburgh', 'hutton'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_16
  WTF: {'war', 'empereurs', 'senso', 'japon', 'lady', 'clan', 'month', 'emperors', 'son', 'throne', 'court'} {'chinese', 'minamoto', 'nichiren', 'chiang', 'fujiwara', 'titsingh', 'kaishek', 'japanese', 'japan', 'deng', 'varley'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_17
  WTF: {'tours', 'book', 'testament', 'writings', 'life', 'catholic', 'feast', 'bishop', 'roman', 'chapter', 'god', 'heresies'} {'christ', 'chrysostom', 'athanasius', 'benedict', 'anthony', 'luke', 'jesus', 'irenaeus', 'ephrem', 'alexandria', 'mary', 'martin'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_18
  WTF: {'guest', 'episodes', 'voice', 'night', 'garrison', 'late', 'award', 'host'} {'lettermans', 'belushi', 'keillor', 'palin', 'letterman', 'coleman', 'leno', 'grammer'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_19
  WTF: {'beauty', 'days', 'globe', 'born', '2005', 'new', 'golden'} {'doris', 'danner', 'carangi', 'kidman', 'anderson', 'theron', 'naomi'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_20
  WTF: {'war', 'voyage', '2004', 'forces', 'admiral', 'ship', 'navy', 'general', 'lord', 'spanish', 'royal'} {'british', 'drake', 'nelson', 'wellington', 'alexander', 'hibbert', 'montgomery', 'india', 'mountbatten', 'blackbeard', 'sugden'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_21
  WTF: {'conservative', 'john', 'sir', 'crisis', '1939', 'lord', 'foot', 'cabinet', 'parliament'} {'british', 'canada', 'disraeli', 'canadian', 'riel', 'attlee', 'macdonald', 'holt', 'tupper'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_22
  WTF: {'war', 'harbor', 'moon', 'film', 'admiral', 'pearl', 'born', 'carrier', 'american', 'midway', 'dragon', 'pacific'} {'tokyo', 'akira', 'japanese', 'hearn', 'yamamoto', 'kurosawa', 'lafcadio', 'fukuyama', 'morita', 'japan', 'yamamotos', 'ueshiba'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_23
  WTF: {'war', 'expedition', 'conquest', 'king', 'city', 'military', 'civil', 'married', 'time', 'issue', 'doa', 'president', 'troops', 'government', 'new'} {'madero', 'francis', 'alfonso', 'ortega', 'almagro', 'xavier', 'corts', 'cid', 'pizarro', 'daz', 'madrid', 'francisco', 'franco', 'mexico', 'francos'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_24
  WTF: {'comics', 'paintings', 'short', 'collection', 'christian', 'hans', 'work', 'life', 'little', '2005', 'don', 'award', 'new', 'art'} {'alvar', 'nansen', 'kafkas', 'ibsen', 'eggum', 'munch', 'kafka', 'leiber', 'fafhrd', 'aalto', 'prideaux', 'andersen', 'mouser', 'munchs'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_25
  WTF: {'observatory', 'scientific', 'algebraic', 'geometry', 'academy', 'planetary', 'theorem', 'university', 'published', 'light', 'tables'} {'tycho', 'kepler', 'grothendieck', 'eulers', 'euler', 'caspar', 'rmer', 'peano', 'johannes', 'keplers', 'celsius'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_26
  WTF: {'isbn', 'kingdom', 'prophecy', 'ed', 'pp', 'chronicle', 'iii', 'isles', 'ii', 'death', 'died', 'english', 'saga', 'killed'} {'macbeth', 'selkirk', 'coluim', 'scots', 'kenneth', 'oram', 'alexander', 'scotland', 'mel', 'alba', 'malcolm', 'duncan', 'malcolms', 'scottish'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_27
  WTF: {'roman', 'army', 'great', 'tours', 'son', 'empire', 'iii', 'ii', 'death', 'duke', 'spanish', 'imperial'} {'martel', 'france', 'italy', 'eugene', 'europe', 'attila', 'savoy', 'charlemagne', 'frankish', 'charles', 'louis', 'bernard'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_28
  WTF: {'succession', 'reign', 'vii', 'earl', 'council', 'protestant', 'throne', 'duke', 'marriage', 'ii', 'death', 'kings', 'royal'} {'england', 'elizabeth', 'anne', 'wales', 'edward', 'owain', 'henrys', 'henry', 'charles', 'catherine', 'tudor', 'elizabeths', 'mary'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_29
  WTF: {'poets', 'illustrations', 'abbey', 'wrote', 'english', 'life', 'literature', 'published', 'works', 'nonsense', 'verse', 'lines'} {'ogden', 'housmans', 'severn', 'masefield', 'lear', 'nash', 'keats', 'manley', 'shropshire', 'hopkinss', 'hopkins', 'housman'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_30
  WTF: {'married', 'grand', 'ca', 'family', 'queen', 'emperor', 'sister', 'sons', 'ii', 'death', 'died', 'lands', 'brother'} {'mieszko', 'bolesaw', 'jadwiga', 'poland', 'feodorovna', 'lithuania', 'hungary', 'krakw', 'lithuanian', 'casimir', 'maria', 'mindaugas', 'jadwigas'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_31
  WTF: {'isbn', 'speller', 'school', 'books', 'trials', 'gay', 'liberty', 'witch', 'children', 'published', 'college', 'spelling'} {'yale', 'abbott', 'alcott', 'bellamy', 'noah', 'jerry', 'connecticut', 'mather', 'mathers', 'falwell', 'falwells', 'webster'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_32
  WTF: {'performed', 'musical', 'film', 'chorus', 'composition', 'requiem', 'works', 'scores', 'giovanni', 'counterpoint'} {'palestrina', 'rossini', 'morricone', 'milan', 'ennio', 'rossinis', 'verdis', 'giuseppe', 'morricones', 'gioachino'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_33
  WTF: {'scientists', 'genome', 'behavior', 'self', 'evolution', 'environmentalist', 'carl', 'research', 'chapter'} {'rogers', 'wilson', 'kikuyu', 'rushton', 'venter', 'leakey', 'lomborg', 'louis', 'jensen'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_34
  WTF: {'work', 'society', 'problem', 'physics', 'elliptic', 'cohomology', 'equations'} {'reid', 'neumann', 'atiyah', 'ktheory', 'hilberts', 'hilbert', 'neumanns'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_35
  WTF: {'bureau', 'relationship', 'sexual', 'office', 'vote', 'election', 'life', 'prison', 'bomb', 'president', 'general', 'sentence', 'parole', 'illness', 'gray'} {'sacramento', 'hoover', 'soliah', 'california', 'lewinsky', 'olson', 'eastman', 'sla', 'hoovers', 'cade', 'clinton', 'sara', 'fargo', 'reno', 'gandy'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_36
  WTF: {'police', 'army', 'chancellor', 'military', 'law', '1945', 'foreign', 'von', 'power', 'nazis', 'crimes', 'sa', 'people', 'face'} {'waldheim', 'germany', 'reich', 'goebbels', 'gring', 'berlin', 'luftwaffe', 'hitlers', 'hitler', 'kershaw', 'grings', 'reichstag', 'nazi', 'himmler'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_37
  WTF: {'sociology', 'die', 'ed', 'society', 'public', 'trans', 'communicative', 'memory', 'und', 'culture'} {'luhmann', 'gadamer', 'ebbinghaus', 'gesellschaft', 'fichtes', 'marcuse', 'habermas', 'horkheimer', 'fichte', 'frankfurt'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_38
  WTF: {'rpt', 'description', 'grammar', 'sounds', 'linguists', 'english'} {'hockett', 'whorf', 'jones', 'witwatersrand', 'bantu', 'doke'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_39
  WTF: {'book', 'new', 'shmoo', 'cartoonists', 'best', 'work', 'award', 'characters', 'shmoos', 'art'} {'abner', 'capp', 'barney', 'hobbes', 'simon', 'trudeau', 'watterson', 'kirby', 'lil', 'capps'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_40
  WTF: {'freedom', 'economists', 'education', 'value', 'banking', 'economist', 'social', 'money', 'government', 'philosophy'} {'ricardo', 'dewey', 'rothbard', 'hayek', 'mises', 'deweys', 'murray', 'friedman', 'tobin', 'hayeks'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_41
  WTF: {'scientific', 'ray', 'science', 'society', 'theory', 'animals', 'principles', 'origin', 'history', 'geological', 'vol', 'edition'} {'slotten', 'mayr', 'haeckel', 'darwin', 'maynard', 'lyell', 'ernst', 'charles', 'wallace', 'wallaces', 'lyells', 'darwins'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_42
  WTF: {'stated', 'united', 'department', 'waterboarding', 'memo', 'news', 'times', 'report'} {'osama', 'saudi', 'cia', 'qaeda', 'zubaydahs', 'alqaeda', 'zubaydah', 'abu'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_43
  WTF: {'signs', 'induction', 'inquiry', 'interpretant', 'knowledge', 'pragmatism', 'sense', 'method'} {'bertrand', 'poppers', 'russell', 'russells', 'peirce', 'peirces', 'popper', 'moore'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_44
  WTF: {'daughter', 'navigator', 'coast', 'prince', 'mother', 'iii', 'ii', 'expeditions', 'infanta', 'infante'} {'afonso', 'len', 'albuquerque', 'castile', 'portuguese', 'sancho', 'henry', 'portugal', 'aragon', 'coimbra'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_45
  WTF: {'spain', 'father', '911', 'life', 'feast', 'judges', 'roman', 'order', 'ibid', 'god'} {'francis', 'alberoni', 'bellarmine', 'rome', 'mychal', 'contarini', 'porziuncola', 'cardano', 'assisi', 'franciscan'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_46
  WTF: {'investiture', 'king', 'mission', 'philosophersaint', 'anglosaxon', 'abbey', '279306', 'bishop', 'magick', 'works', 'english', 'historia'} {'bedes', 'anselm', 'bede', 'canterbury', 'aleister', 'dunstan', 'augustine', 'vaughn', 'crowley', 'crowleys', 'anselms', 'sutin'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_47
  WTF: {'conservative', 'theological', 'study', 'law', 'theology', 'prophets', 'work', 'university', 'rabbis', 'man', 'sabbath', 'studies', 'scholars'} {'heschel', 'jts', 'steinsaltz', 'hebrew', 'jewish', 'neusner', 'kushner', 'judaism', 'kaplans', 'neusners', 'talmud', 'torah', 'kaplan'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_48
  WTF: {'commissioner', 'career', 'allstar', 'tigers', 'hit', 'pitched', 'american'} {'youngs', 'greenberg', 'milwaukee', 'knute', 'mlb', 'rockne', 'cy'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_49
  WTF: {'recorder', 'musical', 'film', 'record', 'rhythm', 'minutes', 'various', 'song', 'bob', 'artists', 'score'} {'elfman', 'cbs', 'ira', 'dowland', 'crosby', 'crosbys', 'gershwin', 'dowlands', 'styne', 'burton', 'bing'}
  WTF?!?!? 11
  WTF?!?!? 11
{'fix': <__main__.FastFixPhiRegularizer object at 0x7fd2ec58ea30>}
Check after fit:
Skipping background topic: background_1.
topic_0
  WTF: {'philosophy', 'later', 'design', 'les', 'university', 'published', 'press', 'et'} {'sartre', 'wright', 'paris', 'lacan', 'rodin', 'rousseau', 'camus', 'warhol'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_1
  WTF: {'new', 'recorded'} {'elvis', 'presley'}
topic_2
  WTF: {'army', 'palace', 'son', 'state', 'medicine', 'time', 'battle', 'ali', 'muslims', 'government'} {'afghanistan', 'persian', 'abd', 'meher', 'rumi', 'islamic', 'india', 'muhammad', 'abu', 'ahmad'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_3
  WTF: {'dio', 'emperors', 'christian', 'caesars', 'life', 'ce', 'gibbon', 'senate', 'ad', 'death', 'ancient', 'caesar', 'imperial'} {'augustus', 'rome', 'barnes', 'julian', 'eusebius', 'constantius', 'claudius', 'caligula', 'tiberius', 'hadrian', 'diocletian', 'tacitus', 'suetonius'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_4
  WTF: {'hill', 'army', 'hearings', 'kit', 'served', 'confederate', 'supreme', 'union', 'fowler', 'american'} {'eisenhower', 'rumsfeld', 'carson', 'jay', 'stuart', 'oswald', 'hancock', 'davis', 'armstrong', 'thomas'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_5
  WTF: {'machine', 'project', 'information', 'language', 'work', 'institute', 'operating', 'interview', 'award'} {'shannon', 'minsky', 'sanger', 'turing', 'engelbart', 'warwick', 'babbage', 'zuse', 'wikipedia'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_6
  WTF: {'army', 'chess', 'military', 'film', 'committee', 'state', 'time', 'world', 'life', 'revolution', 'government', 'march', 'order', 'new'} {'russian', 'philby', 'moscow', 'trotsky', 'alexander', 'nicholas', 'stalin', 'chekhov', 'beria', 'gorbachev', 'tito', 'kasparov', 'yeltsin', 'russia'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_7
  WTF: {'professor', 'scientific', 'wireless', 'quantum', 'theremin', 'institute', 'nuclear'} {'bohr', 'fermi', 'davy', 'planck', 'faraday', 'bardeen', 'marconi'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_8
  WTF: {'pope', 'della', 'film', 'leonardo', 'marble', 'san', 'work', 'life', 'painting', 'del', 'il', 'new'} {'giordano', 'caravaggios', 'caravaggio', 'florence', 'rome', 'medici', 'lucrezia', 'borgia', 'cesare', 'angelico', 'fellini', 'bruno'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_9
  WTF: {'series', 'world', 'books', 'english', 'mars'} {'steinbeck', 'moorcock', 'crichton', 'verne', 'ballard'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_10
  WTF: {'rabbit', 'poems', 'writing', 'short', 'wrote', 'family', 'fiction', 'story', 'letters', 'press', 'new'} {'shelleys', 'hawthorne', 'shelley', 'anne', 'jane', 'austen', 'dickens', 'wollstonecraft', 'mary', 'updike', 'percy'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_11
  WTF: {'string', 'words', 'concerto', 'quartet', 'composers', 'trio', 'da'} {'elgar', 'wk', 'handel', 'shostakovich', 'hoffmann', 'lugosi', 'haydn'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_12
  WTF: {'script', 'directors', 'stone', 'time', 'actors', 'picture', 'screenplay', 'new'} {'hollywood', 'scorsese', 'hitchcocks', 'warren', 'hitchcock', 'mcgilligan', 'cameron', 'cagney'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_13
  WTF: {'grand', 'career', 'championship', 'lost', 'wickets', 'world'} {'jordan', 'earnhardt', 'agassi', 'muralitharan', 'schumacher', 'hingis'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_14
  WTF: {'army', 'married', 'chancellor', 'military', 'otto', 'margrave', 'prince', 'emperor', 'iii', 'ii', 'magnus', 'maternal', 'insurance', 'paternal'} {'germany', 'clausewitz', 'gustavus', 'joachim', 'prussia', 'albert', 'albertus', 'bismarck', 'bismarcks', 'prussian', 'brandenburg', 'saxony', 'frederick', 'dresden'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_15
  WTF: {'surgeon', 'nobel', 'world', 'theory', 'stress', 'vaccination', 'discovery', 'physician'} {'fleming', 'koch', 'pasteur', 'carrel', 'lister', 'jenner', 'edinburgh', 'hutton'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_16
  WTF: {'war', 'empereurs', 'senso', 'japon', 'lady', 'clan', 'month', 'emperors', 'son', 'throne', 'court'} {'chinese', 'minamoto', 'nichiren', 'chiang', 'fujiwara', 'titsingh', 'kaishek', 'japanese', 'japan', 'deng', 'varley'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_17
  WTF: {'tours', 'book', 'testament', 'writings', 'life', 'catholic', 'feast', 'bishop', 'roman', 'chapter', 'god', 'heresies'} {'christ', 'chrysostom', 'athanasius', 'benedict', 'anthony', 'luke', 'jesus', 'irenaeus', 'ephrem', 'alexandria', 'mary', 'martin'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_18
  WTF: {'guest', 'episodes', 'voice', 'night', 'garrison', 'late', 'award', 'host'} {'lettermans', 'belushi', 'keillor', 'palin', 'letterman', 'coleman', 'leno', 'grammer'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_19
  WTF: {'beauty', 'days', 'globe', 'born', '2005', 'new', 'golden'} {'doris', 'danner', 'carangi', 'kidman', 'anderson', 'theron', 'naomi'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_20
  WTF: {'war', 'voyage', '2004', 'forces', 'admiral', 'ship', 'navy', 'general', 'lord', 'spanish', 'royal'} {'british', 'drake', 'nelson', 'wellington', 'alexander', 'hibbert', 'montgomery', 'india', 'mountbatten', 'blackbeard', 'sugden'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_21
  WTF: {'conservative', 'john', 'sir', 'crisis', '1939', 'lord', 'foot', 'cabinet', 'parliament'} {'british', 'canada', 'disraeli', 'canadian', 'riel', 'attlee', 'macdonald', 'holt', 'tupper'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_22
  WTF: {'war', 'harbor', 'moon', 'film', 'admiral', 'pearl', 'born', 'carrier', 'american', 'midway', 'dragon', 'pacific'} {'tokyo', 'akira', 'japanese', 'hearn', 'yamamoto', 'kurosawa', 'lafcadio', 'fukuyama', 'morita', 'japan', 'yamamotos', 'ueshiba'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_23
  WTF: {'war', 'expedition', 'conquest', 'king', 'city', 'military', 'civil', 'married', 'time', 'issue', 'doa', 'president', 'troops', 'government', 'new'} {'madero', 'francis', 'alfonso', 'ortega', 'almagro', 'xavier', 'corts', 'cid', 'pizarro', 'daz', 'madrid', 'francisco', 'franco', 'mexico', 'francos'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_24
  WTF: {'comics', 'paintings', 'short', 'collection', 'christian', 'hans', 'work', 'life', 'little', '2005', 'don', 'award', 'new', 'art'} {'alvar', 'nansen', 'kafkas', 'ibsen', 'eggum', 'munch', 'kafka', 'leiber', 'fafhrd', 'aalto', 'prideaux', 'andersen', 'mouser', 'munchs'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_25
  WTF: {'observatory', 'scientific', 'algebraic', 'geometry', 'academy', 'planetary', 'theorem', 'university', 'published', 'light', 'tables'} {'tycho', 'kepler', 'grothendieck', 'eulers', 'euler', 'caspar', 'rmer', 'peano', 'johannes', 'keplers', 'celsius'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_26
  WTF: {'isbn', 'kingdom', 'prophecy', 'ed', 'pp', 'chronicle', 'iii', 'isles', 'ii', 'death', 'died', 'english', 'saga', 'killed'} {'macbeth', 'selkirk', 'coluim', 'scots', 'kenneth', 'oram', 'alexander', 'scotland', 'mel', 'alba', 'malcolm', 'duncan', 'malcolms', 'scottish'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_27

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7fd2bf1bb100>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7fd2baa353a0>}
{'perplexity': 317922.34375, 'coherence_20': 0.7749045308466549, 'diversity_euclidean': 0.03396980235341026, 'diversity_jensenshannon': 0.6553345090066154, 'diversity_hellinger': 0.769278886363083, 'diversity_cosine': 0.7384553696802556, 'fair_ppl_free': 2772.8408203125, 'fair_ppl_fix': 287997.46875, 'unfair_ppl_banklike': 317922.34375}
{'num_topics': 51, 'num_common_words': 65750, 'num_model_words': 155407, 'num_bt_words': 135939, 'top_diffs': [{'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}]}
7
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
  WTF: {'academy', 'american', 'career', '2008'} {'hitchcock', 'paul', 'robeson', 'cagney'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_1
  WTF: {'philosophy', 'later', 'design', 'life', 'les', 'university', 'published', 'press', 'et'} {'sartre', 'wright', 'paris', 'lacan', 'rodin', 'rousseau', 'erasmus', 'camus', 'warhol'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_2
  WTF: {'renaissance', 'san', 'father', 'cardinal', 'life', 'saint', 'del', 'st', 'il', 'church', 'new'} {'francis', 'caravaggio', 'calvino', 'florence', 'rome', 'borgia', 'lucrezia', 'marco', 'cesare', 'fellini', 'bruno'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_3
  WTF: {'machine', 'information', 'computers', 'language', 'institute', 'operating', 'interview', 'award', 'mathematics'} {'shannon', 'minsky', 'sanger', 'turing', 'engelbart', 'warwick', 'babbage', 'zuse', 'wikipedia'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_4
  WTF: {'army', 'chess', 'military', 'film', 'committee', 'state', 'time', 'world', 'life', 'revolution', 'government', 'march', 'order', 'new'} {'russian', 'philby', 'moscow', 'trotsky', 'alexander', 'nicholas', 'stalin', 'chekhov', 'beria', 'gorbachev', 'tito', 'kasparov', 'yeltsin', 'russia'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_5
  WTF: {'hill', 'army', 'kit', 'confederate', 'served', 'supreme', 'union', 'fowler', 'american', 'beacon'} {'eisenhower', 'rumsfeld', 'carson', 'jay', 'stuart', 'oswald', 'hancock', 'davis', 'armstrong', 'thomas'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_6
  WTF: {'army', 'jews', 'state', 'world', 'party', 'theory', 'university', 'senate', 'logic', 'nazis', 'social', 'und', 'press', 'minister'} {'waldheim', 'germany', 'mccarthy', 'husserl', 'schwitters', 'reich', 'goebbels', 'hesse', 'gring', 'berlin', 'habermas', 'hitler', 'nazi', 'mccarthys'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_7
  WTF: {'series', 'world', 'books', 'english', 'mars'} {'steinbeck', 'moorcock', 'crichton', 'verne', 'pohl'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_8
  WTF: {'dio', 'annals', 'emperors', 'potter', 'caesars', 'life', 'ce', 'senate', 'ad', 'death', 'ancient', 'caesar', 'imperial'} {'augustus', 'rome', 'barnes', 'domitian', 'julian', 'constantius', 'claudius', 'caligula', 'tiberius', 'odahl', 'diocletian', 'tacitus', 'suetonius'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_9
  WTF: {'musical', 'string', 'words', 'concerto', 'quartet', 'work', 'trio', 'da'} {'munch', 'elgar', 'wk', 'handel', 'shostakovich', 'hoffmann', 'lugosi', 'haydn'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_10
  WTF: {'army', 'married', 'military', 'otto', 'empress', 'margrave', 'prince', 'emperor', 'iii', 'ii', 'death', 'died', 'maternal', 'paternal'} {'germany', 'clausewitz', 'gustavus', 'joachim', 'prussia', 'albert', 'bismarck', 'bismarcks', 'prussian', 'brandenburg', 'saxony', 'frederick', 'maria', 'dresden'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_11
  WTF: {'scientific', 'behavior', 'work', 'knowledge', 'object', 'society', 'philosophical', 'economic', 'published', 'social', 'psychology', 'linguistics'} {'dewey', 'skinner', 'chomsky', 'rothbard', 'hayek', 'russell', 'locke', 'russells', 'peirce', 'peirces', 'friedman', 'popper'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_12
  WTF: {'grand', 'career', 'championship', 'lost', 'wickets', 'world'} {'jordan', 'earnhardt', 'agassi', 'muralitharan', 'schumacher', 'hingis'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_13
  WTF: {'army', 'son', 'medicine', 'sn', 'time', 'ali', 'father', 'empire', 'muslims', 'history', 'caliph', 'nadir', 'aga', 'amir'} {'afghanistan', 'persian', 'abd', 'rumi', 'battuta', 'arrahman', 'islamic', 'avicenna', 'jahangir', 'aurangzeb', 'rumis', 'muhammad', 'abu', 'ahmad'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_14
  WTF: {'war', 'empereurs', 'senso', 'japon', 'lady', 'clan', 'month', 'emperors', 'son', 'throne', 'court'} {'chinese', 'minamoto', 'nichiren', 'chiang', 'fujiwara', 'titsingh', 'kaishek', 'japanese', 'japan', 'deng', 'varley'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_15
  WTF: {'records', 'albums', '2008'} {'peart', 'mitchell', 'nesmith'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_16
  WTF: {'uranium', 'scientific', 'work', 'quantum', 'theory', 'institute', 'scientists', 'telegraphy', 'radio'} {'bohr', 'meitner', 'fermi', 'enrico', 'planck', 'schrdinger', 'marie', 'wigner', 'marconi'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_17
  WTF: {'married', 'grand', 'turkey', 'son', 'spiritual', 'battle', 'pasha', 'prince', 'issue', 'nn', 'order', '1986', 'princess'} {'istanbul', 'turkish', 'meher', 'hatun', 'kalchuri', 'bayezid', 'mehmed', 'osman', 'hih', 'murad', 'efendi', 'hh', 'abdulbah'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_18
  WTF: {'woman', 'short', 'stories', 'books', 'introduction', 'wrote', 'family', 'life', 'story', 'fiction', 'university', 'works', 'letters', 'press', 'women'} {'seymour', 'charlotte', 'shelleys', 'hawthorne', 'shelley', 'anne', 'bronts', 'godwin', 'jane', 'austens', 'austen', 'tomalin', 'wollstonecraft', 'mary', 'percy'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_19
  WTF: {'guitar', 'live', 'wills', 'recording', 'diddley', '2007', 'new'} {'elvis', 'bo', 'presley', 'costello', 'davis', 'browns', 'armstrong'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_20
  WTF: {'war', 'voyage', '2004', 'forces', 'admiral', 'ship', 'navy', 'general', 'lord', 'spanish', 'royal'} {'british', 'drake', 'nelson', 'wellington', 'alexander', 'hibbert', 'montgomery', 'india', 'mountbatten', 'blackbeard', 'sugden'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_21
  WTF: {'surgeon', 'world', 'theory', 'cowpox', 'university', 'vaccination', 'bacteria', 'discovery', 'royal'} {'fleming', 'london', 'koch', 'pasteur', 'carrel', 'lister', 'jenner', 'edinburgh', 'hutton'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_22
  WTF: {'conservative', 'john', 'sir', 'crisis', '1939', 'lord', 'foot', 'cabinet', 'parliament'} {'british', 'canada', 'disraeli', 'canadian', 'riel', 'attlee', 'macdonald', 'holt', 'tupper'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_23
  WTF: {'married', 'isbn', 'kingdom', 'ed', 'pp', 'chronicle', 'iii', 'isles', 'kingship', 'died', 'death', 'ii', 'english', 'saga', 'killed'} {'macbeth', 'selkirk', 'coluim', 'scots', 'kenneth', 'oram', 'alexander', 'scotland', 'maclaurin', 'mel', 'alba', 'malcolm', 'duncan', 'malcolms', 'scottish'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_24
  WTF: {'war', 'expedition', 'conquest', 'king', 'city', 'military', 'civil', 'married', 'time', 'issue', 'doa', 'president', 'troops', 'government', 'new'} {'madero', 'francis', 'alfonso', 'ortega', 'almagro', 'xavier', 'corts', 'cid', 'pizarro', 'daz', 'madrid', 'francisco', 'franco', 'mexico', 'francos'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_25
  WTF: {'geometry', 'algebraic', 'instantons', 'formula', 'space', 'mathematician', 'academy', 'university', 'topological', 'observations'} {'kepler', 'grothendieck', 'eulers', 'atiyah', 'caspar', 'euler', 'rmer', 'ktheory', 'johannes', 'keplers'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_26
  WTF: {'army', 'spain', 'tours', 'son', 'empire', 'iii', 'duc', 'ii', 'duke', 'spanish', 'imperial'} {'martel', 'france', 'eugene', 'savoy', 'charlemagne', 'frankish', 'charles', 'alfred', 'alfreds', 'louis', 'bernard'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_27
  WTF: {'saints', 'homilies', 'book', 'day', 'writings', 'fathers', 'life', 'gospel', 'chapter', 'god'} {'chrysostom', 'athanasius', 'anthony', 'irenaeus', 'christians', 'ephrem', 'alexandria', 'jerome', 'cyril', 'martin'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_28
  WTF: {'war', 'harbor', 'moon', 'battle', 'pearl', 'samurai', 'born', 'navy', 'carrier', 'pacific'} {'akira', 'japanese', 'yamamoto', 'kurosawa', 'fukuyama', 'morita', 'kurosawas', 'japan', 'yamamotos', 'ueshiba'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_29
  WTF: {'succession', 'reign', 'vii', 'earl', 'council', 'protestant', 'throne', 'duke', 'marriage', 'ii', 'death', 'kings', 'royal'} {'england', 'elizabeth', 'anne', 'wales', 'edward', 'owain', 'henrys', 'henry', 'charles', 'catherine', 'tudor', 'elizabeths', 'mary'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_30
  WTF: {'dictionary', 'school', 'meeting', 'trials', 'gin', 'children', 'witch', 'bible', 'haven', 'meetings', 'published', 'church', 'spelling', 'christian'} {'yale', 'abbott', 'alcott', 'foxs', 'bellamy', 'noah', 'connecticut', 'eli', 'mather', 'mathers', 'whitney', 'quakers', 'webster', 'nickalls'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_31
  WTF: {'married', 'ca', 'lands', 'queen', 'emperor', 'iii', 'wife', 'dukes', 'sons', 'ii', 'death', 'died', 'iv', 'order', 'brother'} {'mieszko', 'poland', 'bolesaw', 'jadwiga', 'lithuania', 'hungary', 'leszek', 'krakw', 'kazimierz', 'miller', 'lithuanian', 'casimir', 'mindaugas', 'jadwigas', 'sigismund'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_32
  WTF: {'chlorine', 'electrical', 'experiments', 'later', 'gases', 'work', 'magnetic', 'discovered', 'lamp', 'chemist', 'hydrogen', 'equations'} {'humphry', 'davys', 'volta', 'penzance', 'lewis', 'oliver', 'davy', 'faradays', 'faraday', 'heaviside', 'ampre', 'langmuir'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_33
  WTF: {'drama', 'north', 'actress', 'film', 'architecture', 'nobel', 'prize', 'best', 'furniture', 'academy', 'journey', 'award', 'modernism', 'artek', 'new', 'play'} {'alvar', 'greenland', 'nansen', 'ibsen', 'norway', 'finland', 'ullmann', 'helsinki', 'fridtjof', 'rasmussen', 'nansens', 'aalto', 'thule', 'knud', 'ibsens', 'jasmuheen'}
  WTF?!?!? 16
  WTF?!?!? 16
topic_34
  WTF: {'scientists', 'genome', 'behavior', 'self', 'evolution', 'environmentalist', 'carl', 'research', 'chapter'} {'rogers', 'wilson', 'kikuyu', 'rushton', 'venter', 'leakey', 'lomborg', 'louis', 'jensen'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_35
  WTF: {'preserved', 'constantine', 'meditations', 'work', 'works', 'roman', 'philosophers', 'english', 'church', 'god'} {'heraclitus', 'eusebius', 'verus', 'apuleius', 'lactantius', 'dk', 'aurelius', 'marcus', 'diogenes', 'epicurus'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_36
  WTF: {'hijackers', 'united', 'detainees', 'department', 'waterboarding', 'flight', 'news', 'torture', 'states', 'officials'} {'osama', 'saudi', 'cia', 'qaeda', 'zubaydahs', 'alqaeda', 'fbi', 'zubaydah', 'hanjour', 'abu'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_37
  WTF: {'cartoon', 'series', 'shmoo', 'cartoonists', 'best', 'work', 'award', 'characters', 'new', 'art'} {'thurber', 'abner', 'capp', 'barney', 'simon', 'trudeau', 'watterson', 'kirby', 'lil', 'capps'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_38
  WTF: {'collected', 'joy', 'world', 'books', 'weird', 'fiction', 'monthly', 'poetry', 'literary', 'writing', 'new', 'novel'} {'lewiss', 'amis', 'melville', 'lewis', 'melvilles', 'conrad', 'williams', 'dickenss', 'conrads', 'dickens', 'charles', 'derleth'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_39
  WTF: {'chart', 'release', 'number', 'rb', 'singles', 'new', 'billboard', 'pop'} {'uk', 'mariah', 'careys', 'aaliyah', 'carey', 'courtney', 'enya', 'difranco'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_40
  WTF: {'performed', 'musical', 'film', 'chorus', 'concert', 'requiem', 'libretto', 'works', 'del'} {'rossini', 'morricone', 'milan', 'ennio', 'rossinis', 'verdis', 'giuseppe', 'morricones', 'gioachino'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_41
  WTF: {'king', 'philosophersaint', 'monastery', 'anglosaxon', 'abbey', '279306', 'bishop', 'bishops', 'abbot', 'saint', 'journal', 'english', 'historia'} {'bedes', 'columbanus', 'anselm', 'bede', 'canterbury', 'aleister', 'dunstan', 'augustine', 'vaughn', 'crowley', 'crowleys', 'anselms', 'sutin'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_42
  WTF: {'minor', 'theological', 'study', 'religion', 'theology', 'religious', 'work', 'life', 'civilization', 'prelude', 'university', 'rabbinical', 'man', 'vol', 'philosophy'} {'heschel', 'steinsaltz', 'hebrew', 'jesus', 'jewish', 'albert', 'judaism', 'neusners', 'talmud', 'schweitzer', 'schweitzers', 'torah', 'neusner', 'kaplan', 'lambarn'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_43
  WTF: {'poets', 'love', 'religious', 'ed', 'abbey', 'life', 'university', 'works', 'poet', 'death', 'poetic', 'literature'} {'london', 'housmans', 'yeats', 'keatss', 'oxford', 'keats', 'shepard', 'manley', 'shropshire', 'hopkinss', 'hopkins', 'housman'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_44
  WTF: {'daughter', 'navigator', 'coast', 'prince', 'mother', 'iii', 'ii', 'expeditions', 'infanta', 'infante'} {'afonso', 'len', 'albuquerque', 'castile', 'portuguese', 'sancho', 'henry', 'portugal', 'aragon', 'coimbra'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_45
  WTF: {'players', 'american', 'player', 'allstar', 'tigers', 'blues', 'pitched', 'pitchers'} {'youngs', 'greenberg', 'milwaukee', 'mlb', 'rockne', 'nhl', 'cy', 'doubleday'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_46
  WTF: {'scientific', 'biology', 'ray', 'science', 'society', 'theory', 'animals', 'principles', 'origin', 'history', 'geological', 'vol'} {'slotten', 'london', 'mayr', 'haeckel', 'darwin', 'lyell', 'ernst', 'charles', 'wallace', 'wallaces', 'lyells', 'darwins'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_47
  WTF: {'cancer', 'awareness', 'lady', 'sexual', 'vote', 'education', 'election', 'husband', 'president', 'states', 'sentence', 'parole', 'prison'} {'sacramento', 'soliah', 'california', 'lewinsky', 'olson', 'eastman', 'sla', 'jane', 'clinton', 'sara', 'laura', 'fargo', 'reno'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_48
  WTF: {'professor', 'patient', 'brain', 'neuropathology', 'hans', 'neurology', 'clinical', 'und', 'research', 'chemiae'} {'alzheimer', 'alzheimers', 'jakob', 'boerhaave', 'selye', 'kiel', 'leiden', 'creutzfeldtjakob', 'munich', 'creutzfeldt'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_49
  WTF: {'numbers', 'prize', '18991920', 'number', 'university', 'bang', 'chance', 'royal', 'nuclear'} {'cambridge', 'geoffrey', 'moseley', 'hoyles', 'brewster', 'moseleys', 'hoyle', 'fred', 'rayleigh'}
  WTF?!?!? 9
  WTF?!?!? 9
{'fix': <__main__.FastFixPhiRegularizer object at 0x7fd2cda9f940>}
Check after fit:
Skipping background topic: background_1.
topic_0
  WTF: {'academy', 'american', 'career', '2008'} {'hitchcock', 'paul', 'robeson', 'cagney'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_1
  WTF: {'philosophy', 'later', 'design', 'life', 'les', 'university', 'published', 'press', 'et'} {'sartre', 'wright', 'paris', 'lacan', 'rodin', 'rousseau', 'erasmus', 'camus', 'warhol'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_2
  WTF: {'renaissance', 'san', 'father', 'cardinal', 'life', 'saint', 'del', 'st', 'il', 'church', 'new'} {'francis', 'caravaggio', 'calvino', 'florence', 'rome', 'borgia', 'lucrezia', 'marco', 'cesare', 'fellini', 'bruno'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_3
  WTF: {'machine', 'information', 'computers', 'language', 'institute', 'operating', 'interview', 'award', 'mathematics'} {'shannon', 'minsky', 'sanger', 'turing', 'engelbart', 'warwick', 'babbage', 'zuse', 'wikipedia'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_4
  WTF: {'army', 'chess', 'military', 'film', 'committee', 'state', 'time', 'world', 'life', 'revolution', 'government', 'march', 'order', 'new'} {'russian', 'philby', 'moscow', 'trotsky', 'alexander', 'nicholas', 'stalin', 'chekhov', 'beria', 'gorbachev', 'tito', 'kasparov', 'yeltsin', 'russia'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_5
  WTF: {'hill', 'army', 'kit', 'confederate', 'served', 'supreme', 'union', 'fowler', 'american', 'beacon'} {'eisenhower', 'rumsfeld', 'carson', 'jay', 'stuart', 'oswald', 'hancock', 'davis', 'armstrong', 'thomas'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_6
  WTF: {'army', 'jews', 'state', 'world', 'party', 'theory', 'university', 'senate', 'logic', 'nazis', 'social', 'und', 'press', 'minister'} {'waldheim', 'germany', 'mccarthy', 'husserl', 'schwitters', 'reich', 'goebbels', 'hesse', 'gring', 'berlin', 'habermas', 'hitler', 'nazi', 'mccarthys'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_7
  WTF: {'series', 'world', 'books', 'english', 'mars'} {'steinbeck', 'moorcock', 'crichton', 'verne', 'pohl'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_8
  WTF: {'dio', 'annals', 'emperors', 'potter', 'caesars', 'life', 'ce', 'senate', 'ad', 'death', 'ancient', 'caesar', 'imperial'} {'augustus', 'rome', 'barnes', 'domitian', 'julian', 'constantius', 'claudius', 'caligula', 'tiberius', 'odahl', 'diocletian', 'tacitus', 'suetonius'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_9
  WTF: {'musical', 'string', 'words', 'concerto', 'quartet', 'work', 'trio', 'da'} {'munch', 'elgar', 'wk', 'handel', 'shostakovich', 'hoffmann', 'lugosi', 'haydn'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_10
  WTF: {'army', 'married', 'military', 'otto', 'empress', 'margrave', 'prince', 'emperor', 'iii', 'ii', 'death', 'died', 'maternal', 'paternal'} {'germany', 'clausewitz', 'gustavus', 'joachim', 'prussia', 'albert', 'bismarck', 'bismarcks', 'prussian', 'brandenburg', 'saxony', 'frederick', 'maria', 'dresden'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_11
  WTF: {'scientific', 'behavior', 'work', 'knowledge', 'object', 'society', 'philosophical', 'economic', 'published', 'social', 'psychology', 'linguistics'} {'dewey', 'skinner', 'chomsky', 'rothbard', 'hayek', 'russell', 'locke', 'russells', 'peirce', 'peirces', 'friedman', 'popper'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_12
  WTF: {'grand', 'career', 'championship', 'lost', 'wickets', 'world'} {'jordan', 'earnhardt', 'agassi', 'muralitharan', 'schumacher', 'hingis'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_13
  WTF: {'army', 'son', 'medicine', 'sn', 'time', 'ali', 'father', 'empire', 'muslims', 'history', 'caliph', 'nadir', 'aga', 'amir'} {'afghanistan', 'persian', 'abd', 'rumi', 'battuta', 'arrahman', 'islamic', 'avicenna', 'jahangir', 'aurangzeb', 'rumis', 'muhammad', 'abu', 'ahmad'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_14
  WTF: {'war', 'empereurs', 'senso', 'japon', 'lady', 'clan', 'month', 'emperors', 'son', 'throne', 'court'} {'chinese', 'minamoto', 'nichiren', 'chiang', 'fujiwara', 'titsingh', 'kaishek', 'japanese', 'japan', 'deng', 'varley'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_15
  WTF: {'records', 'albums', '2008'} {'peart', 'mitchell', 'nesmith'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_16
  WTF: {'uranium', 'scientific', 'work', 'quantum', 'theory', 'institute', 'scientists', 'telegraphy', 'radio'} {'bohr', 'meitner', 'fermi', 'enrico', 'planck', 'schrdinger', 'marie', 'wigner', 'marconi'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_17
  WTF: {'married', 'grand', 'turkey', 'son', 'spiritual', 'battle', 'pasha', 'prince', 'issue', 'nn', 'order', '1986', 'princess'} {'istanbul', 'turkish', 'meher', 'hatun', 'kalchuri', 'bayezid', 'mehmed', 'osman', 'hih', 'murad', 'efendi', 'hh', 'abdulbah'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_18
  WTF: {'woman', 'short', 'stories', 'books', 'introduction', 'wrote', 'family', 'life', 'story', 'fiction', 'university', 'works', 'letters', 'press', 'women'} {'seymour', 'charlotte', 'shelleys', 'hawthorne', 'shelley', 'anne', 'bronts', 'godwin', 'jane', 'austens', 'austen', 'tomalin', 'wollstonecraft', 'mary', 'percy'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_19
  WTF: {'guitar', 'live', 'wills', 'recording', 'diddley', '2007', 'new'} {'elvis', 'bo', 'presley', 'costello', 'davis', 'browns', 'armstrong'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_20
  WTF: {'war', 'voyage', '2004', 'forces', 'admiral', 'ship', 'navy', 'general', 'lord', 'spanish', 'royal'} {'british', 'drake', 'nelson', 'wellington', 'alexander', 'hibbert', 'montgomery', 'india', 'mountbatten', 'blackbeard', 'sugden'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_21
  WTF: {'surgeon', 'world', 'theory', 'cowpox', 'university', 'vaccination', 'bacteria', 'discovery', 'royal'} {'fleming', 'london', 'koch', 'pasteur', 'carrel', 'lister', 'jenner', 'edinburgh', 'hutton'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_22
  WTF: {'conservative', 'john', 'sir', 'crisis', '1939', 'lord', 'foot', 'cabinet', 'parliament'} {'british', 'canada', 'disraeli', 'canadian', 'riel', 'attlee', 'macdonald', 'holt', 'tupper'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_23
  WTF: {'married', 'isbn', 'kingdom', 'ed', 'pp', 'chronicle', 'iii', 'isles', 'kingship', 'died', 'death', 'ii', 'english', 'saga', 'killed'} {'macbeth', 'selkirk', 'coluim', 'scots', 'kenneth', 'oram', 'alexander', 'scotland', 'maclaurin', 'mel', 'alba', 'malcolm', 'duncan', 'malcolms', 'scottish'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_24

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7fd2c20105e0>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7fd2d20cd370>}
{'perplexity': 342182.0625, 'coherence_20': 0.7775100063127343, 'diversity_euclidean': 0.03379076401283799, 'diversity_jensenshannon': 0.6555273590057303, 'diversity_hellinger': 0.7696513170399334, 'diversity_cosine': 0.7389253667138549, 'fair_ppl_free': 2768.535888671875, 'fair_ppl_fix': 306273.875, 'unfair_ppl_banklike': 342182.0625}
{'num_topics': 51, 'num_common_words': 65750, 'num_model_words': 155407, 'num_bt_words': 135939, 'top_diffs': [{'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 32, 'lost_bt': 16, 'lost_model': 16}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}]}
8
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
  WTF: {'american', 'episode', 'career', '2008'} {'hitchcock', 'paul', 'robeson', 'cagney'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_1
  WTF: {'dio', 'greek', 'caesars', 'life', 'gibbon', 'senate', 'ad', 'saint', 'st', 'death', 'caesar'} {'augustus', 'rome', 'barnes', 'julian', 'eusebius', 'constantius', 'claudius', 'caligula', 'diocletian', 'tacitus', 'suetonius'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_2
  WTF: {'renaissance', 'years', 'san', 'work', 'polo', 'life', 'del', 'st', 'il', 'english', 'new'} {'francis', 'caravaggio', 'calvino', 'florence', 'rome', 'borgia', 'lucrezia', 'borges', 'marco', 'fellini', 'bruno'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_3
  WTF: {'army', 'palace', 'son', 'state', 'medicine', 'time', 'battle', 'ali', 'muslims', 'government'} {'afghanistan', 'persian', 'abd', 'meher', 'rumi', 'islamic', 'india', 'muhammad', 'abu', 'ahmad'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_4
  WTF: {'meat', 'albums'} {'elvis', 'presley'}
topic_5
  WTF: {'war', 'married', 'great', 'daughter', 'military', 'otto', 'prince', 'emperor', 'von', 'died', 'death', 'maternal', 'paternal'} {'mieszko', 'poland', 'hungary', 'prussia', 'albert', 'bismarck', 'brandenburg', 'prussian', 'saxony', 'frederick', 'casimir', 'alfred', 'alfreds'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_6
  WTF: {'string', 'concerto', 'composers', 'gamba', 'trio', 'da'} {'elgar', 'wk', 'handel', 'shostakovich', 'lugosi', 'haydn'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_7
  WTF: {'machine', 'information', 'language', 'work', 'program', 'institute', 'operating', 'interview', 'award'} {'shannon', 'minsky', 'sanger', 'turing', 'engelbart', 'warwick', 'babbage', 'zuse', 'wikipedia'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_8
  WTF: {'army', 'chess', 'military', 'film', 'committee', 'state', 'time', 'world', 'life', 'revolution', 'government', 'ii', 'order', 'new'} {'russian', 'philby', 'moscow', 'trotsky', 'alexander', 'nicholas', 'stalin', 'chekhov', 'beria', 'gorbachev', 'tito', 'kasparov', 'yeltsin', 'russia'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_9
  WTF: {'hill', 'army', 'john', 'baron', 'supreme', 'union', 'general', 'american', 'beacon'} {'goldman', 'eisenhower', 'hoover', 'rumsfeld', 'carson', 'stuart', 'hancock', 'davis', 'thomas'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_10
  WTF: {'professor', 'quantum', 'theremin', 'theory', 'research', 'institute', 'laboratory', 'nuclear'} {'bohr', 'fermi', 'davy', 'planck', 'marie', 'bardeen', 'heaviside', 'marconi'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_11
  WTF: {'series', 'world', 'books', 'best', 'mars'} {'steinbeck', 'moorcock', 'crichton', 'verne', 'ballard'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_12
  WTF: {'psychoanalysis', 'subject', 'time', 'work', 'life', 'des', 'political', 'trans', 'university', 'published', 'new'} {'sartre', 'nostradamus', 'paris', 'lacan', 'rousseau', 'satie', 'rousseaus', 'merleauponty', 'sade', 'baudelaire', 'deleuze'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_13
  WTF: {'grand', 'career', 'championship', 'lost', 'wickets', 'world'} {'jordan', 'earnhardt', 'agassi', 'muralitharan', 'schumacher', 'hingis'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_14
  WTF: {'surgeon', 'nobel', 'world', 'theory', 'stress', 'vaccination', 'discovery', 'physician'} {'fleming', 'koch', 'pasteur', 'carrel', 'lister', 'jenner', 'edinburgh', 'hutton'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_15
  WTF: {'war', 'empereurs', 'senso', 'japon', 'lady', 'clan', 'month', 'emperors', 'son', 'throne', 'court'} {'chinese', 'minamoto', 'nichiren', 'chiang', 'fujiwara', 'titsingh', 'kaishek', 'japanese', 'japan', 'deng', 'varley'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_16
  WTF: {'allied', 'john', 'voyage', 'admiral', 'attack', 'ships', 'navy', 'lord', 'royal'} {'british', 'drake', 'nelson', 'wellington', 'jay', 'montgomery', 'mountbatten', 'rommel', 'rommels'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_17
  WTF: {'paint', 'painters', 'french', 'giger', 'millet', 'salon', 'museum'} {'pissarro', 'rodin', 'paris', 'davids', 'rodins', 'monet', 'david'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_18
  WTF: {'woman', 'short', 'stories', 'books', 'introduction', 'wrote', 'family', 'life', 'story', 'fiction', 'university', 'works', 'letters', 'press', 'women'} {'seymour', 'charlotte', 'shelleys', 'hawthorne', 'shelley', 'anne', 'bronts', 'godwin', 'jane', 'austens', 'austen', 'tomalin', 'wollstonecraft', 'mary', 'percy'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_19
  WTF: {'conservative', 'john', 'sir', 'crisis', '1939', 'lord', 'foot', 'cabinet', 'parliament'} {'british', 'canada', 'disraeli', 'canadian', 'riel', 'attlee', 'macdonald', 'holt', 'tupper'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_20
  WTF: {'married', 'isbn', 'kingdom', 'ed', 'pp', 'chronicle', 'iii', 'isles', 'kingship', 'died', 'death', 'ii', 'english', 'saga', 'killed'} {'macbeth', 'selkirk', 'coluim', 'scots', 'kenneth', 'oram', 'alexander', 'scotland', 'maclaurin', 'mel', 'alba', 'malcolm', 'duncan', 'malcolms', 'scottish'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_21
  WTF: {'biography', 'writing', 'poems', 'house', 'books', 'work', 'wrote', 'life', 'literary', 'lord', 'letters'} {'lewiss', 'amis', 'melville', 'tolkien', 'lewis', 'tolkiens', 'dickenss', 'dickens', 'oxford', 'charles', 'conrad'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_22
  WTF: {'war', 'harbor', 'moon', 'series', 'anime', 'pearl', 'born', 'carrier', 'american', 'dragon'} {'akira', 'japanese', 'yamamoto', 'kurosawa', 'fukuyama', 'morita', 'kurosawas', 'japan', 'yamamotos', 'ueshiba'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_23
  WTF: {'roman', 'army', 'great', 'tours', 'son', 'empire', 'iii', 'ii', 'death', 'duke', 'spanish', 'imperial'} {'martel', 'france', 'italy', 'eugene', 'europe', 'attila', 'savoy', 'charlemagne', 'frankish', 'charles', 'louis', 'bernard'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_24
  WTF: {'comics', 'paintings', 'short', 'christian', 'work', 'life', 'story', 'polar', 'published', 'little', 'duck', '2005', 'new', 'art'} {'alvar', 'andersens', 'nansen', 'kafkas', 'norway', 'ibsen', 'eggum', 'franz', 'munch', 'kafka', 'aalto', 'prideaux', 'andersen', 'munchs'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_25
  WTF: {'poets', 'years', 'ed', 'work', 'wrote', 'english', 'donnes', 'published', 'works', 'letters', 'nonsense', 'literature'} {'london', 'alice', 'severn', 'masefield', 'lewis', 'dodgson', 'nash', 'keats', 'shropshire', 'carroll', 'hopkins', 'housman'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_26
  WTF: {'war', 'expedition', 'conquest', 'king', 'city', 'military', 'civil', 'married', 'time', 'issue', 'doa', 'president', 'troops', 'government', 'new'} {'madero', 'francis', 'alfonso', 'ortega', 'almagro', 'xavier', 'corts', 'cid', 'pizarro', 'daz', 'madrid', 'francisco', 'franco', 'mexico', 'francos'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_27
  WTF: {'isbn', 'dictionary', 'years', 'gin', 'english', 'life', 'society', 'children', 'meetings', 'published', 'prior', 'press', 'church'} {'yale', 'abbott', 'mead', 'alcott', 'burke', 'foxs', 'mather', 'margaret', 'whitney', 'burkes', 'quakers', 'webster', 'nickalls'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_28
  WTF: {'observatory', 'planets', 'scientific', 'geometry', 'algebraic', 'planetary', 'theorem', 'university', 'light', 'tables'} {'tycho', 'kepler', 'grothendieck', 'eulers', 'euler', 'caspar', 'rmer', 'johannes', 'keplers', 'celsius'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_29
  WTF: {'army', 'systems', 'chancellor', 'law', '1945', 'foreign', 'people', 'von', 'power', 'nazis', 'social', 'sa', 'und', 'der'} {'waldheim', 'luhmann', 'germany', 'reich', 'goebbels', 'gring', 'berlin', 'luftwaffe', 'hitlers', 'hitler', 'kershaw', 'grings', 'nazi', 'himmler'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_30
  WTF: {'succession', 'reign', 'vii', 'earl', 'council', 'protestant', 'throne', 'duke', 'marriage', 'ii', 'death', 'kings', 'royal'} {'england', 'elizabeth', 'anne', 'wales', 'edward', 'owain', 'henrys', 'henry', 'charles', 'catherine', 'tudor', 'elizabeths', 'mary'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_31
  WTF: {'biology', 'science', 'ray', 'animals', 'theory', 'society', 'principles', 'archaeology', 'origin', 'history', 'vol', 'edition', 'chapter'} {'slotten', 'london', 'mayr', 'haeckel', 'darwin', 'lyell', 'ernst', 'leakey', 'charles', 'wallace', 'louis', 'wallaces', 'darwins'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_32
  WTF: {'hijackers', 'united', 'detainees', 'department', 'waterboarding', 'flight', 'news', 'torture', 'states', 'officials'} {'osama', 'saudi', 'cia', 'qaeda', 'zubaydahs', 'alqaeda', 'fbi', 'zubaydah', 'hanjour', 'abu'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_33
  WTF: {'reinforcement', 'freedom', 'education', 'liberty', 'economist', 'economy', 'money', 'free', 'research', 'government', 'rent', 'philosophy'} {'ricardo', 'dewey', 'skinner', 'rothbard', 'hayek', 'deweys', 'murray', 'skinners', 'friedman', 'drexel', 'milken', 'hayeks'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_34
  WTF: {'differences', 'scientists', 'behavior', 'environmentalist', 'individual', 'carl', 'research'} {'rogers', 'wilson', 'rushton', 'jensens', 'venter', 'lomborg', 'jensen'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_35
  WTF: {'rpt', 'description', 'humans', 'grammar', 'sounds', 'linguists', 'english'} {'hockett', 'whorf', 'jones', 'bantu', 'westermann', 'doke', 'diedrich'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_36
  WTF: {'flew', 'flying', '11', 'navy', 'states', 'service', 'mach', 'crew'} {'apollo', 'jones', 'bingham', 'aldrin', 'hopper', 'armstrong', 'hansen', 'yeager'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_37
  WTF: {'book', 'series', 'shmoo', 'cartoonists', 'best', 'work', 'award', 'characters', 'new', 'art'} {'thurber', 'abner', 'capp', 'barney', 'simon', 'trudeau', 'watterson', 'kirby', 'lil', 'capps'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_38
  WTF: {'investiture', 'king', 'mission', 'philosophersaint', 'anglosaxon', 'abbey', '279306', 'bishop', 'magick', 'saint', 'english', 'historia'} {'bedes', 'anselm', 'bede', 'canterbury', 'aleister', 'dunstan', 'augustine', 'vaughn', 'crowley', 'crowleys', 'anselms', 'sutin'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_39
  WTF: {'daughter', 'navigator', 'coast', 'prince', 'mother', 'iii', 'ii', 'expeditions', 'infanta', 'infante'} {'afonso', 'len', 'albuquerque', 'castile', 'portuguese', 'sancho', 'henry', 'portugal', 'aragon', 'coimbra'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_40
  WTF: {'hot', 'pg', 'release', 'number', 'rb', 'singles', 'pop'} {'uk', 'mariah', 'careys', 'aaliyah', 'carey', 'enya', 'difranco'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_41
  WTF: {'signs', 'induction', 'inquiry', 'interpretant', 'knowledge', 'pragmatism', 'sense', 'method'} {'bertrand', 'poppers', 'russell', 'russells', 'peirce', 'peirces', 'popper', 'moore'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_42
  WTF: {'conservative', 'theological', 'book', 'study', 'theology', 'prophets', 'work', 'seminary', 'university', 'rabbis', 'sabbath', 'studies', 'scholars'} {'heschel', 'jts', 'steinsaltz', 'hebrew', 'jewish', 'neusner', 'kushner', 'judaism', 'kaplans', 'neusners', 'talmud', 'torah', 'kaplan'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_43
  WTF: {'park', 'designs', 'architectural', 'residential', 'center', 'tower', 'houses', 'new'} {'chihuly', 'wright', 'lloyd', 'lin', 'wrights', 'pei', 'chicago', 'mies'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_44
  WTF: {'players', 'hall', 'allstar', 'tigers', 'hit', 'pitched', 'american'} {'youngs', 'greenberg', 'milwaukee', 'mlb', 'rockne', 'cy', 'doubleday'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_45
  WTF: {'disciples', 'testament', 'orthodox', 'feast', 'relics', 'gospels', 'tradition', 'apostle', 'mark'} {'johns', 'christ', 'baptist', 'luke', 'jesus', 'matthew', 'barnabas', 'mary', 'yahya'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_46
  WTF: {'critical', 'curve', 'sphere', 'ed', 'work', 'philosophical', 'communicative', 'rationality', 'culture'} {'gadamer', 'ebbinghaus', 'fichtes', 'marcuse', 'habermas', 'derrida', 'horkheimer', 'fichte', 'frankfurt'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_47
  WTF: {'gravitational', 'papers', 'paper', 'stellar', 'stars', 'eclipse', 'astronomical', 'mathematics'} {'cambridge', 'eddingtons', 'einsteins', 'eddington', 'brewster', 'albert', 'hoyle', 'rayleigh'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_48
  WTF: {'shows', 'featured', 'film', 'lyrics', 'minutes', 'wrote', 'popular', 'composer', 'golf', 'musicals', 'radio'} {'elfman', 'ira', 'broadway', 'kern', 'dowland', 'crosby', 'crosbys', 'gershwin', 'dowlands', 'burton', 'bing'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_49
  WTF: {'cancer', 'awareness', 'sexual', 'primary', 'election', 'husband', 'breast', 'president', 'sentence', 'parole', 'prison', 'women'} {'sacramento', 'soliah', 'california', 'lewinsky', 'olson', 'sla', 'jane', 'clinton', 'sara', 'laura', 'fargo', 'reno'}
  WTF?!?!? 12
  WTF?!?!? 12
{'fix': <__main__.FastFixPhiRegularizer object at 0x7fd2baa38100>}
Check after fit:
Skipping background topic: background_1.
topic_0
  WTF: {'american', 'episode', 'career', '2008'} {'hitchcock', 'paul', 'robeson', 'cagney'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_1
  WTF: {'dio', 'greek', 'caesars', 'life', 'gibbon', 'senate', 'ad', 'saint', 'st', 'death', 'caesar'} {'augustus', 'rome', 'barnes', 'julian', 'eusebius', 'constantius', 'claudius', 'caligula', 'diocletian', 'tacitus', 'suetonius'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_2
  WTF: {'renaissance', 'years', 'san', 'work', 'polo', 'life', 'del', 'st', 'il', 'english', 'new'} {'francis', 'caravaggio', 'calvino', 'florence', 'rome', 'borgia', 'lucrezia', 'borges', 'marco', 'fellini', 'bruno'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_3
  WTF: {'army', 'palace', 'son', 'state', 'medicine', 'time', 'battle', 'ali', 'muslims', 'government'} {'afghanistan', 'persian', 'abd', 'meher', 'rumi', 'islamic', 'india', 'muhammad', 'abu', 'ahmad'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_4
  WTF: {'meat', 'albums'} {'elvis', 'presley'}
topic_5
  WTF: {'war', 'married', 'great', 'daughter', 'military', 'otto', 'prince', 'emperor', 'von', 'died', 'death', 'maternal', 'paternal'} {'mieszko', 'poland', 'hungary', 'prussia', 'albert', 'bismarck', 'brandenburg', 'prussian', 'saxony', 'frederick', 'casimir', 'alfred', 'alfreds'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_6
  WTF: {'string', 'concerto', 'composers', 'gamba', 'trio', 'da'} {'elgar', 'wk', 'handel', 'shostakovich', 'lugosi', 'haydn'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_7
  WTF: {'machine', 'information', 'language', 'work', 'program', 'institute', 'operating', 'interview', 'award'} {'shannon', 'minsky', 'sanger', 'turing', 'engelbart', 'warwick', 'babbage', 'zuse', 'wikipedia'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_8
  WTF: {'army', 'chess', 'military', 'film', 'committee', 'state', 'time', 'world', 'life', 'revolution', 'government', 'ii', 'order', 'new'} {'russian', 'philby', 'moscow', 'trotsky', 'alexander', 'nicholas', 'stalin', 'chekhov', 'beria', 'gorbachev', 'tito', 'kasparov', 'yeltsin', 'russia'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_9
  WTF: {'hill', 'army', 'john', 'baron', 'supreme', 'union', 'general', 'american', 'beacon'} {'goldman', 'eisenhower', 'hoover', 'rumsfeld', 'carson', 'stuart', 'hancock', 'davis', 'thomas'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_10
  WTF: {'professor', 'quantum', 'theremin', 'theory', 'research', 'institute', 'laboratory', 'nuclear'} {'bohr', 'fermi', 'davy', 'planck', 'marie', 'bardeen', 'heaviside', 'marconi'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_11
  WTF: {'series', 'world', 'books', 'best', 'mars'} {'steinbeck', 'moorcock', 'crichton', 'verne', 'ballard'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_12
  WTF: {'psychoanalysis', 'subject', 'time', 'work', 'life', 'des', 'political', 'trans', 'university', 'published', 'new'} {'sartre', 'nostradamus', 'paris', 'lacan', 'rousseau', 'satie', 'rousseaus', 'merleauponty', 'sade', 'baudelaire', 'deleuze'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_13
  WTF: {'grand', 'career', 'championship', 'lost', 'wickets', 'world'} {'jordan', 'earnhardt', 'agassi', 'muralitharan', 'schumacher', 'hingis'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_14
  WTF: {'surgeon', 'nobel', 'world', 'theory', 'stress', 'vaccination', 'discovery', 'physician'} {'fleming', 'koch', 'pasteur', 'carrel', 'lister', 'jenner', 'edinburgh', 'hutton'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_15
  WTF: {'war', 'empereurs', 'senso', 'japon', 'lady', 'clan', 'month', 'emperors', 'son', 'throne', 'court'} {'chinese', 'minamoto', 'nichiren', 'chiang', 'fujiwara', 'titsingh', 'kaishek', 'japanese', 'japan', 'deng', 'varley'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_16
  WTF: {'allied', 'john', 'voyage', 'admiral', 'attack', 'ships', 'navy', 'lord', 'royal'} {'british', 'drake', 'nelson', 'wellington', 'jay', 'montgomery', 'mountbatten', 'rommel', 'rommels'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_17
  WTF: {'paint', 'painters', 'french', 'giger', 'millet', 'salon', 'museum'} {'pissarro', 'rodin', 'paris', 'davids', 'rodins', 'monet', 'david'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_18
  WTF: {'woman', 'short', 'stories', 'books', 'introduction', 'wrote', 'family', 'life', 'story', 'fiction', 'university', 'works', 'letters', 'press', 'women'} {'seymour', 'charlotte', 'shelleys', 'hawthorne', 'shelley', 'anne', 'bronts', 'godwin', 'jane', 'austens', 'austen', 'tomalin', 'wollstonecraft', 'mary', 'percy'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_19
  WTF: {'conservative', 'john', 'sir', 'crisis', '1939', 'lord', 'foot', 'cabinet', 'parliament'} {'british', 'canada', 'disraeli', 'canadian', 'riel', 'attlee', 'macdonald', 'holt', 'tupper'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_20
  WTF: {'married', 'isbn', 'kingdom', 'ed', 'pp', 'chronicle', 'iii', 'isles', 'kingship', 'died', 'death', 'ii', 'english', 'saga', 'killed'} {'macbeth', 'selkirk', 'coluim', 'scots', 'kenneth', 'oram', 'alexander', 'scotland', 'maclaurin', 'mel', 'alba', 'malcolm', 'duncan', 'malcolms', 'scottish'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_21
  WTF: {'biography', 'writing', 'poems', 'house', 'books', 'work', 'wrote', 'life', 'literary', 'lord', 'letters'} {'lewiss', 'amis', 'melville', 'tolkien', 'lewis', 'tolkiens', 'dickenss', 'dickens', 'oxford', 'charles', 'conrad'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_22
  WTF: {'war', 'harbor', 'moon', 'series', 'anime', 'pearl', 'born', 'carrier', 'american', 'dragon'} {'akira', 'japanese', 'yamamoto', 'kurosawa', 'fukuyama', 'morita', 'kurosawas', 'japan', 'yamamotos', 'ueshiba'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_23
  WTF: {'roman', 'army', 'great', 'tours', 'son', 'empire', 'iii', 'ii', 'death', 'duke', 'spanish', 'imperial'} {'martel', 'france', 'italy', 'eugene', 'europe', 'attila', 'savoy', 'charlemagne', 'frankish', 'charles', 'louis', 'bernard'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_24
  WTF: {'comics', 'paintings', 'short', 'christian', 'work', 'life', 'story', 'polar', 'published', 'little', 'duck', '2005', 'new', 'art'} {'alvar', 'andersens', 'nansen', 'kafkas', 'norway', 'ibsen', 'eggum', 'franz', 'munch', 'kafka', 'aalto', 'prideaux', 'andersen', 'munchs'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_25
  WTF: {'poets', 'years', 'ed', 'work', 'wrote', 'english', 'donnes', 'published', 'works', 'letters', 'nonsense', 'literature'} {'london', 'alice', 'severn', 'masefield', 'lewis', 'dodgson', 'nash', 'keats', 'shropshire', 'carroll', 'hopkins', 'housman'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_26
  WTF: {'war', 'expedition', 'conquest', 'king', 'city', 'military', 'civil', 'married', 'time', 'issue', 'doa', 'president', 'troops', 'government', 'new'} {'madero', 'francis', 'alfonso', 'ortega', 'almagro', 'xavier', 'corts', 'cid', 'pizarro', 'daz', 'madrid', 'francisco', 'franco', 'mexico', 'francos'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_27
  WTF: {'isbn', 'dictionary', 'years', 'gin', 'english', 'life', 'society', 'children', 'meetings', 'published', 'prior', 'press', 'church'} {'yale', 'abbott', 'mead', 'alcott', 'burke', 'foxs', 'mather', 'margaret', 'whitney', 'burkes', 'quakers', 'webster', 'nickalls'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_28
  WTF: {'observatory', 'planets', 'scientific', 'geometry', 'algebraic', 'planetary', 'theorem', 'university', 'light', 'tables'} {'tycho', 'kepler', 'grothendieck', 'eulers', 'euler', 'caspar', 'rmer', 'johannes', 'keplers', 'celsius'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_29

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7fd2ec5bbee0>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7fd2ff181e80>}
{'perplexity': 373101.71875, 'coherence_20': 0.781060911745688, 'diversity_euclidean': 0.03360572978546191, 'diversity_jensenshannon': 0.6495301172935977, 'diversity_hellinger': 0.7616693019362927, 'diversity_cosine': 0.7310893305442706, 'fair_ppl_free': 2755.728515625, 'fair_ppl_fix': 333521.53125, 'unfair_ppl_banklike': 373101.71875}
{'num_topics': 51, 'num_common_words': 65750, 'num_model_words': 155407, 'num_bt_words': 135939, 'top_diffs': [{'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}]}
9
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
  WTF: {'renaissance', 'years', 'san', 'work', 'polo', 'life', 'saint', 'del', 'st', 'il', 'new'} {'francis', 'caravaggio', 'calvino', 'florence', 'rome', 'borgia', 'lucrezia', 'borges', 'marco', 'fellini', 'bruno'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_1
  WTF: {'recording', 'single'} {'elvis', 'presley'}
topic_2
  WTF: {'army', 'palace', 'son', 'state', 'medicine', 'time', 'battle', 'ali', 'muslims', 'government'} {'afghanistan', 'persian', 'abd', 'meher', 'rumi', 'islamic', 'india', 'muhammad', 'abu', 'ahmad'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_3
  WTF: {'book', 'orthodox', 'time', 'writings', 'life', 'catholic', 'bishop', 'history', 'century', 'roman'} {'athanasius', 'anselm', 'bede', 'irenaeus', 'eusebius', 'archimedes', 'alexandria', 'augustine', 'mary', 'crowley'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_4
  WTF: {'machine', 'information', 'computers', 'language', 'institute', 'operating', 'interview', 'award'} {'shannon', 'minsky', 'sanger', 'turing', 'engelbart', 'babbage', 'zuse', 'wikipedia'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_5
  WTF: {'string', 'words', 'concerto', 'quartet', 'opera', 'trio', 'da'} {'elgar', 'wk', 'handel', 'shostakovich', 'hoffmann', 'lugosi', 'haydn'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_6
  WTF: {'professor', 'scientific', 'chemical', 'wireless', 'science', 'quantum', 'scientists', 'research'} {'bohr', 'fermi', 'davy', 'planck', 'faraday', 'bardeen', 'heaviside', 'marconi'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_7
  WTF: {'annals', 'military', 'emperors', 'caesars', 'life', 'ce', 'gibbon', 'senate', 'ad', 'death', 'caesar', 'imperial'} {'augustus', 'rome', 'barnes', 'julian', 'constantius', 'claudius', 'caligula', 'tiberius', 'hadrian', 'diocletian', 'tacitus', 'suetonius'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_8
  WTF: {'army', 'chess', 'military', 'film', 'committee', 'state', 'time', 'world', 'revolution', 'government', 'march', 'ii', 'order', 'new'} {'russian', 'moscow', 'trotsky', 'khmelnytsky', 'alexander', 'nicholas', 'stalin', 'chekhov', 'beria', 'gorbachev', 'tito', 'kasparov', 'yeltsin', 'russia'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_9
  WTF: {'war', 'hearings', 'john', 'baron', 'pp', 'supreme', 'union', 'general', 'beacon'} {'hoover', 'rumsfeld', 'carson', 'stuart', 'oswald', 'hancock', 'davis', 'lee', 'thomas'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_10
  WTF: {'psychoanalysis', 'desire', 'perception', 'time', 'work', 'life', 'des', 'political', 'published', 'press', 'new'} {'sartre', 'nostradamus', 'paris', 'lacan', 'rousseau', 'satie', 'rousseaus', 'merleauponty', 'sade', 'baudelaire', 'deleuze'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_11
  WTF: {'series', 'world', 'books', 'english', 'mars'} {'steinbeck', 'moorcock', 'crichton', 'verne', 'pohl'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_12
  WTF: {'army', 'married', 'chancellor', 'military', 'otto', 'margrave', 'prince', 'emperor', 'iii', 'ii', 'died', 'maternal', 'insurance', 'paternal'} {'germany', 'clausewitz', 'gustavus', 'joachim', 'prussia', 'albert', 'albertus', 'bismarck', 'bismarcks', 'prussian', 'brandenburg', 'saxony', 'frederick', 'dresden'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_13
  WTF: {'grand', 'career', 'championship', 'lost', 'wickets', 'world'} {'jordan', 'earnhardt', 'agassi', 'muralitharan', 'schumacher', 'hingis'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_14
  WTF: {'episodes', 'role', '2008', 'movie', 'best', 'awards', 'voice', 'late', 'award', 'host', 'played'} {'leary', 'jones', 'belushi', 'voight', 'keillor', 'palin', 'letterman', 'coleman', 'groucho', 'marx', 'grammer'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_15
  WTF: {'sculpture', 'landscape', 'painters', 'french', 'maroger', 'millet', 'salon', 'artists'} {'pissarro', 'paris', 'debussy', 'rodin', 'rodins', 'monet', 'david', 'pollock'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_16
  WTF: {'surgeon', 'diseases', 'world', 'theory', 'stress', 'vaccination', 'bacteria', 'discovery'} {'fleming', 'koch', 'pasteur', 'carrel', 'lister', 'jenner', 'edinburgh', 'hutton'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_17
  WTF: {'production', 'role', 'actor', 'time', 'story', 'directed', 'received', 'award', 'screenplay'} {'coen', 'cukor', 'scorsese', 'warren', 'david', 'york', 'mcgilligan', 'cameron', 'cagney'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_18
  WTF: {'war', 'empereurs', 'senso', 'japon', 'lady', 'clan', 'month', 'emperors', 'son', 'throne', 'court'} {'chinese', 'minamoto', 'nichiren', 'chiang', 'fujiwara', 'titsingh', 'kaishek', 'japanese', 'japan', 'deng', 'varley'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_19
  WTF: {'years', 'ro', 'later', 'cartoonist', 'work', 'bubbles', 'lad', 'new', 'poem', 'art'} {'thurber', 'abner', 'capp', 'dodgson', 'kirby', 'keats', 'lil', 'carroll', 'housman', 'capps'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_20
  WTF: {'war', 'voyage', '2004', 'forces', 'admiral', 'ship', 'navy', 'general', 'lord', 'spanish', 'royal'} {'british', 'drake', 'nelson', 'wellington', 'alexander', 'hibbert', 'montgomery', 'india', 'mountbatten', 'blackbeard', 'sugden'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_21
  WTF: {'conservative', 'john', 'sir', 'crisis', '1939', 'lord', 'foot', 'cabinet', 'parliament'} {'british', 'canada', 'disraeli', 'canadian', 'riel', 'attlee', 'macdonald', 'holt', 'tupper'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_22
  WTF: {'relativity', 'science', 'stars', 'wiles', 'mathematician', 'physics', 'theorem', 'university', 'published', 'light'} {'kepler', 'grothendieck', 'eulers', 'eddington', 'keplers', 'euler', 'caspar', 'rmer', 'napier', 'hoyle'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_23
  WTF: {'2003', 'television', 'beauty', 'days', 'globe', '2005', 'new', 'golden'} {'doris', 'carangi', 'danner', 'kidman', 'anderson', 'melcher', 'theron', 'naomi'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_24
  WTF: {'scientific', 'behavior', 'pragmatism', 'knowledge', 'work', 'philosophical', 'logical', 'published', 'social', 'psychology', 'mathematics', 'sign'} {'dewey', 'skinner', 'rothbard', 'bertrand', 'hayek', 'russell', 'russells', 'peirce', 'peirces', 'friedman', 'milken', 'popper'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_25
  WTF: {'isbn', 'woman', 'poems', 'short', 'spark', 'stories', 'books', 'introduction', 'life', 'family', 'story', 'university', 'works', 'letters', 'press', 'women'} {'seymour', 'charlotte', 'shelleys', 'christie', 'shelley', 'anne', 'bronts', 'godwin', 'jane', 'austens', 'austen', 'tomalin', 'bront', 'wollstonecraft', 'mary', 'percy'}
  WTF?!?!? 16
  WTF?!?!? 16
topic_26
  WTF: {'war', 'harbor', 'moon', 'series', 'anime', 'pearl', 'born', 'carrier', 'american', 'dragon'} {'akira', 'japanese', 'yamamoto', 'kurosawa', 'fukuyama', 'morita', 'kurosawas', 'japan', 'yamamotos', 'ueshiba'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_27
  WTF: {'conquest', 'city', 'son', 'la', 'tlatoani', 'election', 'november', 'called', 'president', 'ii', 'leader', 'order', 'brother'} {'madero', 'aragon', 'alfonso', 'ortega', 'len', 'corts', 'cid', 'aztec', 'daz', 'madrid', 'cuauhtmoc', 'mexico', 'moctezuma'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_28
  WTF: {'isbn', 'kingdom', 'prophecy', 'ed', 'pp', 'chronicle', 'iii', 'isles', 'ii', 'death', 'died', 'english', 'saga', 'killed'} {'macbeth', 'selkirk', 'coluim', 'scots', 'kenneth', 'oram', 'alexander', 'scotland', 'mel', 'alba', 'malcolm', 'duncan', 'malcolms', 'scottish'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_29
  WTF: {'army', 'spain', 'tours', 'great', 'son', 'empire', 'iii', 'duc', 'ii', 'duke', 'spanish', 'imperial'} {'martel', 'france', 'italy', 'eugene', 'eugenes', 'europe', 'savoy', 'charlemagne', 'frankish', 'charles', 'louis', 'bernard'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_30
  WTF: {'expedition', 'arctic', 'short', 'paintings', 'new', 'christian', 'work', 'life', 'polar', 'published', 'little', 'works', '2005', 'scream', 'museum', 'fairy', 'art'} {'alvar', 'andersens', 'nansen', 'kafkas', 'norway', 'ibsen', 'ullmann', 'eggum', 'franz', 'munch', 'kafka', 'rasmussen', 'fridtjof', 'aalto', 'prideaux', 'andersen', 'munchs'}
  WTF?!?!? 17
  WTF?!?!? 17
topic_31
  WTF: {'succession', 'reign', 'vii', 'earl', 'council', 'protestant', 'throne', 'duke', 'marriage', 'ii', 'death', 'kings', 'royal'} {'england', 'elizabeth', 'anne', 'wales', 'edward', 'owain', 'henrys', 'henry', 'charles', 'catherine', 'tudor', 'elizabeths', 'mary'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_32
  WTF: {'married', 'grand', 'ca', 'daughter', 'empress', 'dowager', 'queen', 'family', 'heir', 'sister', 'sons', 'ii', 'death', 'died', 'lands'} {'mieszko', 'bolesaw', 'jadwiga', 'poland', 'feodorovna', 'lithuania', 'hungary', 'leszek', 'krakw', 'miller', 'lithuanian', 'casimir', 'maria', 'mindaugas', 'jadwigas'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_33
  WTF: {'isbn', 'speller', 'school', 'years', 'books', 'trials', 'children', 'bible', 'published', 'anthropologist', 'college', 'church', 'spelling', 'christian'} {'yale', 'abbott', 'mead', 'alcott', 'samoa', 'bellamy', 'noah', 'madras', 'meads', 'connecticut', 'mather', 'mathers', 'margaret', 'webster'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_34
  WTF: {'communist', 'hearings', 'committee', '1945', 'state', 'communists', 'von', 'senator', 'power', 'nazis', 'propaganda', 'subcommittee', 'speech'} {'waldheim', 'germany', 'mccarthy', 'reich', 'goebbels', 'gring', 'berlin', 'luftwaffe', 'hitlers', 'hitler', 'grings', 'nazi', 'mccarthys'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_35
  WTF: {'biography', 'new', 'collected', 'books', 'weird', 'life', 'monthly', 'university', 'literary', 'writing', 'press', 'literature', 'novel'} {'lewiss', 'melville', 'hawthorne', 'lewis', 'melvilles', 'conrad', 'williams', 'dickenss', 'conrads', 'nathaniel', 'dickens', 'charles', 'derleth'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_36
  WTF: {'hijackers', 'united', 'detainees', 'department', 'waterboarding', 'flight', 'news', 'torture', 'states', 'officials'} {'osama', 'saudi', 'cia', 'qaeda', 'zubaydahs', 'alqaeda', 'fbi', 'zubaydah', 'hanjour', 'abu'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_37
  WTF: {'differences', 'scientists', 'behavior', 'environmentalist', 'individual', 'carl', 'research'} {'rogers', 'wilson', 'rushton', 'jensens', 'venter', 'lomborg', 'jensen'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_38
  WTF: {'rpt', 'description', 'humans', 'grammar', 'sounds', 'linguists', 'english'} {'hockett', 'whorf', 'jones', 'bantu', 'westermann', 'doke', 'diedrich'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_39
  WTF: {'daughter', 'navigator', 'coast', 'prince', 'mother', 'iii', 'ii', 'expeditions', 'infanta', 'infante'} {'afonso', 'len', 'albuquerque', 'castile', 'portuguese', 'sancho', 'henry', 'portugal', 'aragon', 'coimbra'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_40
  WTF: {'hot', 'pg', 'release', 'number', 'rb', 'singles', 'pop'} {'uk', 'mariah', 'careys', 'aaliyah', 'carey', 'enya', 'difranco'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_41
  WTF: {'scientific', 'biology', 'science', 'ray', 'society', 'animals', 'principles', 'history', 'geological', 'man', 'vol', 'edition', 'chapter'} {'slotten', 'mayr', 'haeckel', 'kikuyu', 'darwin', 'lyell', 'ernst', 'leakey', 'charles', 'wallace', 'louis', 'wallaces', 'darwins'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_42
  WTF: {'moon', 'united', 'plane', 'grace', 'test', 'navy', 'mach', 'crew'} {'apollo', 'bingham', 'armstrongs', 'aldrin', 'hopper', 'armstrong', 'hansen', 'yeager'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_43
  WTF: {'shows', 'featured', 'film', 'lyrics', 'minutes', 'wrote', 'popular', 'composer', 'golf', 'musicals', 'radio'} {'elfman', 'ira', 'broadway', 'kern', 'dowland', 'crosby', 'crosbys', 'gershwin', 'dowlands', 'burton', 'bing'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_44
  WTF: {'sociology', 'communication', 'die', 'sphere', 'german', 'public', 'communicative', 'und', 'der', 'culture', 'philosophy'} {'luhmann', 'gadamer', 'ebbinghaus', 'gesellschaft', 'suhrkamp', 'marcuse', 'habermas', 'derrida', 'horkheimer', 'jrgen', 'frankfurt'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_45
  WTF: {'players', 'hall', 'allstar', 'tigers', 'hit', 'pitched', 'american'} {'youngs', 'greenberg', 'milwaukee', 'mlb', 'rockne', 'cy', 'doubleday'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_46
  WTF: {'conservative', 'theological', 'study', 'law', 'theology', 'prophets', 'work', 'university', 'rabbis', 'man', 'sabbath', 'studies', 'scholars'} {'heschel', 'jts', 'steinsaltz', 'hebrew', 'jewish', 'neusner', 'kushner', 'judaism', 'kaplans', 'neusners', 'talmud', 'torah', 'kaplan'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_47
  WTF: {'relationship', 'sentencing', 'school', '2002', 'primary', 'vote', 'election', 'march', 'bomb', 'councilman', 'general', 'murder', 'plea', 'parole'} {'sacramento', 'soliah', 'california', 'lewinsky', 'olson', 'eastman', 'sla', 'jane', 'heather', 'clinton', 'sara', 'fargo', 'reno', 'olsons'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_48
  WTF: {'book', 'city', 'consistory', 'churches', 'collge', 'teachings', 'ministers', 'family', 'synod', 'dynasty', 'religious'} {'servetus', 'chinese', 'confucianism', 'dupuis', 'confucian', 'amyraut', 'geneva', 'confucius', 'calvin', 'calvins', 'confuciuss'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_49
  WTF: {'1930', 'proof', 'work', 'axiom', 'problem', 'mathematician', 'bomb', '1996'} {'knigsberg', 'reid', 'neumann', 'gdel', 'hilberts', 'hilbert', 'neumanns', 'gttingen'}
  WTF?!?!? 8
  WTF?!?!? 8
{'fix': <__main__.FastFixPhiRegularizer object at 0x7fd2d1b3dbe0>}
Check after fit:
Skipping background topic: background_1.
topic_0
  WTF: {'renaissance', 'years', 'san', 'work', 'polo', 'life', 'saint', 'del', 'st', 'il', 'new'} {'francis', 'caravaggio', 'calvino', 'florence', 'rome', 'borgia', 'lucrezia', 'borges', 'marco', 'fellini', 'bruno'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_1
  WTF: {'recording', 'single'} {'elvis', 'presley'}
topic_2
  WTF: {'army', 'palace', 'son', 'state', 'medicine', 'time', 'battle', 'ali', 'muslims', 'government'} {'afghanistan', 'persian', 'abd', 'meher', 'rumi', 'islamic', 'india', 'muhammad', 'abu', 'ahmad'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_3
  WTF: {'book', 'orthodox', 'time', 'writings', 'life', 'catholic', 'bishop', 'history', 'century', 'roman'} {'athanasius', 'anselm', 'bede', 'irenaeus', 'eusebius', 'archimedes', 'alexandria', 'augustine', 'mary', 'crowley'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_4
  WTF: {'machine', 'information', 'computers', 'language', 'institute', 'operating', 'interview', 'award'} {'shannon', 'minsky', 'sanger', 'turing', 'engelbart', 'babbage', 'zuse', 'wikipedia'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_5
  WTF: {'string', 'words', 'concerto', 'quartet', 'opera', 'trio', 'da'} {'elgar', 'wk', 'handel', 'shostakovich', 'hoffmann', 'lugosi', 'haydn'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_6
  WTF: {'professor', 'scientific', 'chemical', 'wireless', 'science', 'quantum', 'scientists', 'research'} {'bohr', 'fermi', 'davy', 'planck', 'faraday', 'bardeen', 'heaviside', 'marconi'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_7
  WTF: {'annals', 'military', 'emperors', 'caesars', 'life', 'ce', 'gibbon', 'senate', 'ad', 'death', 'caesar', 'imperial'} {'augustus', 'rome', 'barnes', 'julian', 'constantius', 'claudius', 'caligula', 'tiberius', 'hadrian', 'diocletian', 'tacitus', 'suetonius'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_8
  WTF: {'army', 'chess', 'military', 'film', 'committee', 'state', 'time', 'world', 'revolution', 'government', 'march', 'ii', 'order', 'new'} {'russian', 'moscow', 'trotsky', 'khmelnytsky', 'alexander', 'nicholas', 'stalin', 'chekhov', 'beria', 'gorbachev', 'tito', 'kasparov', 'yeltsin', 'russia'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_9
  WTF: {'war', 'hearings', 'john', 'baron', 'pp', 'supreme', 'union', 'general', 'beacon'} {'hoover', 'rumsfeld', 'carson', 'stuart', 'oswald', 'hancock', 'davis', 'lee', 'thomas'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_10
  WTF: {'psychoanalysis', 'desire', 'perception', 'time', 'work', 'life', 'des', 'political', 'published', 'press', 'new'} {'sartre', 'nostradamus', 'paris', 'lacan', 'rousseau', 'satie', 'rousseaus', 'merleauponty', 'sade', 'baudelaire', 'deleuze'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_11
  WTF: {'series', 'world', 'books', 'english', 'mars'} {'steinbeck', 'moorcock', 'crichton', 'verne', 'pohl'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_12
  WTF: {'army', 'married', 'chancellor', 'military', 'otto', 'margrave', 'prince', 'emperor', 'iii', 'ii', 'died', 'maternal', 'insurance', 'paternal'} {'germany', 'clausewitz', 'gustavus', 'joachim', 'prussia', 'albert', 'albertus', 'bismarck', 'bismarcks', 'prussian', 'brandenburg', 'saxony', 'frederick', 'dresden'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_13
  WTF: {'grand', 'career', 'championship', 'lost', 'wickets', 'world'} {'jordan', 'earnhardt', 'agassi', 'muralitharan', 'schumacher', 'hingis'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_14
  WTF: {'episodes', 'role', '2008', 'movie', 'best', 'awards', 'voice', 'late', 'award', 'host', 'played'} {'leary', 'jones', 'belushi', 'voight', 'keillor', 'palin', 'letterman', 'coleman', 'groucho', 'marx', 'grammer'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_15
  WTF: {'sculpture', 'landscape', 'painters', 'french', 'maroger', 'millet', 'salon', 'artists'} {'pissarro', 'paris', 'debussy', 'rodin', 'rodins', 'monet', 'david', 'pollock'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_16
  WTF: {'surgeon', 'diseases', 'world', 'theory', 'stress', 'vaccination', 'bacteria', 'discovery'} {'fleming', 'koch', 'pasteur', 'carrel', 'lister', 'jenner', 'edinburgh', 'hutton'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_17
  WTF: {'production', 'role', 'actor', 'time', 'story', 'directed', 'received', 'award', 'screenplay'} {'coen', 'cukor', 'scorsese', 'warren', 'david', 'york', 'mcgilligan', 'cameron', 'cagney'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_18
  WTF: {'war', 'empereurs', 'senso', 'japon', 'lady', 'clan', 'month', 'emperors', 'son', 'throne', 'court'} {'chinese', 'minamoto', 'nichiren', 'chiang', 'fujiwara', 'titsingh', 'kaishek', 'japanese', 'japan', 'deng', 'varley'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_19
  WTF: {'years', 'ro', 'later', 'cartoonist', 'work', 'bubbles', 'lad', 'new', 'poem', 'art'} {'thurber', 'abner', 'capp', 'dodgson', 'kirby', 'keats', 'lil', 'carroll', 'housman', 'capps'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_20
  WTF: {'war', 'voyage', '2004', 'forces', 'admiral', 'ship', 'navy', 'general', 'lord', 'spanish', 'royal'} {'british', 'drake', 'nelson', 'wellington', 'alexander', 'hibbert', 'montgomery', 'india', 'mountbatten', 'blackbeard', 'sugden'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_21
  WTF: {'conservative', 'john', 'sir', 'crisis', '1939', 'lord', 'foot', 'cabinet', 'parliament'} {'british', 'canada', 'disraeli', 'canadian', 'riel', 'attlee', 'macdonald', 'holt', 'tupper'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_22
  WTF: {'relativity', 'science', 'stars', 'wiles', 'mathematician', 'physics', 'theorem', 'university', 'published', 'light'} {'kepler', 'grothendieck', 'eulers', 'eddington', 'keplers', 'euler', 'caspar', 'rmer', 'napier', 'hoyle'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_23
  WTF: {'2003', 'television', 'beauty', 'days', 'globe', '2005', 'new', 'golden'} {'doris', 'carangi', 'danner', 'kidman', 'anderson', 'melcher', 'theron', 'naomi'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_24
  WTF: {'scientific', 'behavior', 'pragmatism', 'knowledge', 'work', 'philosophical', 'logical', 'published', 'social', 'psychology', 'mathematics', 'sign'} {'dewey', 'skinner', 'rothbard', 'bertrand', 'hayek', 'russell', 'russells', 'peirce', 'peirces', 'friedman', 'milken', 'popper'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_25
  WTF: {'isbn', 'woman', 'poems', 'short', 'spark', 'stories', 'books', 'introduction', 'life', 'family', 'story', 'university', 'works', 'letters', 'press', 'women'} {'seymour', 'charlotte', 'shelleys', 'christie', 'shelley', 'anne', 'bronts', 'godwin', 'jane', 'austens', 'austen', 'tomalin', 'bront', 'wollstonecraft', 'mary', 'percy'}
  WTF?!?!? 16
  WTF?!?!? 16
topic_26
  WTF: {'war', 'harbor', 'moon', 'series', 'anime', 'pearl', 'born', 'carrier', 'american', 'dragon'} {'akira', 'japanese', 'yamamoto', 'kurosawa', 'fukuyama', 'morita', 'kurosawas', 'japan', 'yamamotos', 'ueshiba'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_27

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7fd2bf4fe4f0>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7fd2bf8b3c40>}
{'perplexity': 450574.90625, 'coherence_20': 0.757145397965717, 'diversity_euclidean': 0.03335221733324496, 'diversity_jensenshannon': 0.6534034420191971, 'diversity_hellinger': 0.766577585544413, 'diversity_cosine': 0.7305456216617975, 'fair_ppl_free': 2768.001708984375, 'fair_ppl_fix': 410808.9375, 'unfair_ppl_banklike': 450574.90625}
{'num_topics': 51, 'num_common_words': 65750, 'num_model_words': 155407, 'num_bt_words': 135939, 'top_diffs': [{'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 32, 'lost_bt': 16, 'lost_model': 16}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 34, 'lost_bt': 17, 'lost_model': 17}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}]}
10
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
  WTF: {'academy', 'american', 'career', '2008'} {'hitchcock', 'paul', 'robeson', 'cagney'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_1
  WTF: {'machine', 'information', 'computers', 'language', 'institute', 'operating', 'interview', 'award'} {'shannon', 'minsky', 'sanger', 'turing', 'engelbart', 'babbage', 'zuse', 'wikipedia'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_2
  WTF: {'teslas', 'hertz', 'science', 'theory', 'institute', 'research', 'nuclear', 'radio'} {'bohr', 'fermi', 'davy', 'planck', 'faraday', 'bardeen', 'nikola', 'marconi'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_3
  WTF: {'musical', 'string', 'words', 'quartet', 'opera', 'trio', 'da'} {'elgar', 'wk', 'handel', 'shostakovich', 'hoffmann', 'lugosi', 'haydn'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_4
  WTF: {'writing', 'poems', 'short', 'wrote', 'family', 'story', 'university', 'letters', 'press', 'new'} {'shelleys', 'tolkien', 'lewis', 'shelley', 'jane', 'austen', 'dickens', 'wollstonecraft', 'mary', 'updike'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_5
  WTF: {'annals', 'military', 'emperors', 'caesars', 'life', 'ce', 'gibbon', 'senate', 'ad', 'death', 'caesar', 'imperial'} {'augustus', 'rome', 'barnes', 'julian', 'constantius', 'claudius', 'caligula', 'tiberius', 'hadrian', 'diocletian', 'tacitus', 'suetonius'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_6
  WTF: {'war', 'army', 'military', 'film', 'congress', 'committee', 'state', 'time', 'world', 'match', 'revolution', 'government', 'order', 'new', 'central'} {'lenin', 'russian', 'moscow', 'trotsky', 'khmelnytsky', 'alexander', 'chekhov', 'stalin', 'beria', 'gorbachev', 'sakharov', 'tito', 'kasparov', 'yeltsin', 'russia'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_7
  WTF: {'pope', 'della', 'pietro', 'film', 'marble', 'san', 'work', 'life', 'painting', 'del', 'il', 'new'} {'giordano', 'caravaggios', 'caravaggio', 'florence', 'rome', 'medici', 'lucrezia', 'borgia', 'angelico', 'fellini', 'bruno', 'lorenzo'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_8
  WTF: {'army', 'jews', 'state', 'work', 'party', 'theory', 'political', 'von', 'logic', 'published', 'history', 'social', 'und', 'phenomenology'} {'germany', 'mccarthy', 'husserl', 'schwitters', 'reich', 'goebbels', 'hegel', 'hesse', 'gring', 'berlin', 'hegels', 'habermas', 'hitler', 'nazi'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_9
  WTF: {'designed', 'new', 'van', 'buildings', 'painter', 'architect', 'museum', 'building', 'painted'} {'wright', 'lloyd', 'paris', 'debussy', 'rodin', 'wrights', 'monet', 'david', 'mies'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_10
  WTF: {'english', 'world', 'best', 'mars'} {'steinbeck', 'crichton', 'verne', 'moorcock'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_11
  WTF: {'grand', 'career', 'championship', 'lost', 'wickets', 'tennis'} {'jordan', 'earnhardt', 'agassi', 'muralitharan', 'schumacher', 'hingis'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_12
  WTF: {'isbn', 'book', 'years', 'later', 'work', 'published', 'al', 'press', 'poem'} {'abner', 'capp', 'joyce', 'kirby', 'keats', 'lil', 'carroll', 'housman', 'joyces'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_13
  WTF: {'army', 'married', 'chancellor', 'military', 'otto', 'margrave', 'prince', 'emperor', 'iii', 'ii', 'died', 'maternal', 'insurance', 'paternal'} {'germany', 'clausewitz', 'gustavus', 'joachim', 'prussia', 'albert', 'albertus', 'bismarck', 'bismarcks', 'prussian', 'brandenburg', 'saxony', 'frederick', 'dresden'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_14
  WTF: {'records', 'albums', 'songs', 'brooks'} {'peart', 'browns', 'james', 'nesmith'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_15
  WTF: {'war', 'allied', 'john', 'captain', 'admiral', 'commander', 'nova', 'attack', 'ships', 'cook', 'lord', 'royal'} {'british', 'drake', 'canada', 'nelson', 'canadian', 'wellington', 'montgomery', 'riel', 'mountbatten', 'rommel', 'macdonald', 'tupper'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_16
  WTF: {'surgeon', 'nobel', 'world', 'theory', 'stress', 'vaccination', 'discovery', 'physician'} {'fleming', 'koch', 'pasteur', 'carrel', 'lister', 'jenner', 'edinburgh', 'hutton'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_17
  WTF: {'war', 'empereurs', 'senso', 'japon', 'lady', 'clan', 'month', 'emperors', 'son', 'throne', 'court'} {'chinese', 'minamoto', 'nichiren', 'chiang', 'fujiwara', 'titsingh', 'kaishek', 'japanese', 'japan', 'deng', 'varley'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_18
  WTF: {'army', 'city', 'son', 'medicine', 'sn', 'time', 'ali', 'empire', 'muslims', 'history', 'caliph', 'nadir', 'aga', 'amir'} {'afghanistan', 'persian', 'abd', 'rumi', 'sina', 'battuta', 'arrahman', 'islamic', 'avicenna', 'jahangir', 'rumis', 'muhammad', 'abu', 'ahmad'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_19
  WTF: {'mathematicians', 'proof', 'scientific', 'geometry', 'space', 'physics', 'university', 'astronomical', 'published', 'set', 'cohomology'} {'kepler', 'grothendieck', 'eulers', 'neumann', 'keplers', 'gdel', 'atiyah', 'euler', 'hilberts', 'hilbert', 'hoyle'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_20
  WTF: {'married', 'grand', 'turkey', 'reign', 'son', 'battle', 'pasha', 'prince', 'issue', 'valide', 'shah', 'followers', '1986', 'princess'} {'istanbul', 'turkish', 'meher', 'kalchuri', 'bayezid', 'mehmed', 'osman', 'abdulbah', 'aurangzeb', 'remey', 'murad', 'efendi', 'hh', 'aurangzebs'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_21
  WTF: {'war', 'american', 'united', 'pp', 'supreme', 'union', 'justice', 'new'} {'virginia', 'carson', 'stuart', 'quayle', 'hancock', 'navajo', 'davis', 'thomas'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_22
  WTF: {'sur', 'marquis', 'desire', 'subject', 'perception', 'work', 'political', 'works', 'prophecies', 'new', 'symbolic'} {'sartre', 'nostradamus', 'paris', 'lacan', 'rousseau', 'rousseaus', 'merleauponty', 'sade', 'diderot', 'deleuze', 'deleuzes'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_23
  WTF: {'saints', 'tours', 'book', 'day', 'writings', 'life', 'heresies', 'works', 'roman', 'chapter', 'sin'} {'chrysostom', 'athanasius', 'anthony', 'benedict', 'irenaeus', 'ephrem', 'alexandria', 'augustine', 'jerome', 'cyril', 'martin'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_24
  WTF: {'guitar', 'recording', 'playing', 'musicians', 'rock', 'miles'} {'brubeck', 'hooker', 'bo', 'haley', 'davis', 'armstrong'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_25
  WTF: {'married', 'isbn', 'kingdom', 'ed', 'pp', 'chronicle', 'iii', 'isles', 'kingship', 'died', 'death', 'ii', 'english', 'saga', 'killed'} {'macbeth', 'selkirk', 'coluim', 'scots', 'kenneth', 'oram', 'alexander', 'scotland', 'maclaurin', 'mel', 'alba', 'malcolm', 'duncan', 'malcolms', 'scottish'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_26
  WTF: {'war', 'harbor', 'moon', 'film', 'admiral', 'pearl', 'born', 'carrier', 'american', 'midway', 'dragon', 'pacific'} {'tokyo', 'akira', 'japanese', 'hearn', 'yamamoto', 'kurosawa', 'lafcadio', 'fukuyama', 'morita', 'japan', 'yamamotos', 'ueshiba'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_27
  WTF: {'roman', 'army', 'great', 'tours', 'son', 'empire', 'iii', 'ii', 'death', 'duke', 'spanish', 'imperial'} {'martel', 'france', 'italy', 'eugene', 'europe', 'attila', 'savoy', 'charlemagne', 'frankish', 'charles', 'louis', 'bernard'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_28
  WTF: {'expedition', 'comics', 'paintings', 'stories', 'christian', 'danish', 'work', 'life', 'story', 'polar', 'duck', '2005', 'scream', 'little', 'art'} {'alvar', 'andersens', 'nansen', 'norway', 'finland', 'ibsen', 'eggum', 'munch', 'fridtjof', 'rasmussen', 'barks', 'aalto', 'prideaux', 'andersen', 'munchs'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_29
  WTF: {'trial', 'dictionary', 'pp', 'gin', 'life', 'society', 'haven', 'meetings', 'published', 'prior', 'english', 'church', 'christian'} {'yale', 'abbott', 'alcott', 'burke', 'foxs', 'connecticut', 'eli', 'mather', 'whitney', 'burkes', 'quakers', 'webster', 'nickalls'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_30
  WTF: {'conservative', 'foreign', 'crisis', 'pages', 'page', 'cabinet'} {'british', 'hawke', 'disraeli', 'fraser', 'attlee', 'holt'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_31
  WTF: {'succession', 'reign', 'vii', 'earl', 'council', 'protestant', 'throne', 'duke', 'marriage', 'ii', 'death', 'kings', 'royal'} {'england', 'elizabeth', 'anne', 'wales', 'edward', 'owain', 'henrys', 'henry', 'charles', 'catherine', 'tudor', 'elizabeths', 'mary'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_32
  WTF: {'married', 'grand', 'ca', 'daughter', 'empress', 'family', 'queen', 'emperor', 'sister', 'sons', 'ii', 'death', 'died', 'lands', 'brother'} {'mieszko', 'bolesaw', 'jadwiga', 'poland', 'feodorovna', 'lithuania', 'hungary', 'leszek', 'krakw', 'miller', 'lithuanian', 'casimir', 'maria', 'mindaugas', 'jadwigas'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_33
  WTF: {'wolf', 'giovanni', 'father', 'life', 'bishop', 'roman', 'duke', 'order', 'ibid', 'god'} {'francis', 'alberoni', 'bellarmine', 'rome', 'mychal', 'contarini', 'borgia', 'cesare', 'cardano', 'assisi'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_34
  WTF: {'expedition', 'son', 'later', 'la', 'time', 'men', 'issue', 'doa', 'del', 'st', 'order', 'governor', 'new'} {'madero', 'francis', 'diego', 'alfonso', 'almagro', 'len', 'xavier', 'corts', 'cid', 'pizarro', 'daz', 'francisco', 'mexico'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_35
  WTF: {'iraq', 'mission', 'powers', 'served', 'flying', 'corps', 'service'} {'rumsfeld', 'apollo', 'jones', 'hopper', 'armstrong', 'hansen', 'yeager'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_36
  WTF: {'differences', 'scientists', 'behavior', 'environmentalist', 'individual', 'carl', 'research'} {'rogers', 'wilson', 'rushton', 'jensens', 'venter', 'lomborg', 'jensen'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_37
  WTF: {'rpt', 'description', 'humans', 'grammar', 'sounds', 'linguists', 'english'} {'hockett', 'whorf', 'jones', 'bantu', 'westermann', 'doke', 'diedrich'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_38
  WTF: {'pg', 'chart', 'release', 'number', 'rb', 'singles', 'new', 'billboard'} {'uk', 'hatfield', 'mariah', 'careys', 'aaliyah', 'carey', 'enya', 'difranco'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_39
  WTF: {'hijackers', 'united', 'detainees', 'department', 'waterboarding', 'flight', 'news', 'states', 'officials', 'report'} {'osama', 'saudi', 'cia', 'qaeda', 'zubaydahs', 'alqaeda', 'fbi', 'zubaydah', 'hanjour', 'abu'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_40
  WTF: {'psychology', 'cp', 'language', 'inquiry', 'pragmatism', 'work', 'object', 'method', 'eprint', 'mathematics'} {'dewey', 'chomsky', 'bertrand', 'poppers', 'russell', 'russells', 'peirce', 'peirces', 'popper', 'moore'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_41
  WTF: {'poems', 'theatre', 'plays', 'life', 'des', 'mother', 'published', 'prints', 'literary', 'play'} {'flaubert', 'paris', 'richardson', 'baudelaires', 'maupassant', 'jarry', 'flauberts', 'baudelaire', 'tremblay', 'ubu'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_42
  WTF: {'daughter', 'navigator', 'coast', 'prince', 'mother', 'iii', 'ii', 'expeditions', 'infanta', 'infante'} {'afonso', 'len', 'albuquerque', 'castile', 'portuguese', 'sancho', 'henry', 'portugal', 'aragon', 'coimbra'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_43
  WTF: {'scientific', 'biology', 'science', 'ray', 'society', 'animals', 'principles', 'history', 'geological', 'man', 'vol', 'edition', 'chapter'} {'slotten', 'mayr', 'haeckel', 'kikuyu', 'darwin', 'lyell', 'ernst', 'leakey', 'charles', 'wallace', 'louis', 'wallaces', 'darwins'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_44
  WTF: {'land', 'price', 'freedom', 'economists', 'value', 'banking', 'university', 'money', 'policy'} {'ricardo', 'rothbard', 'friedmans', 'hayek', 'mises', 'murray', 'friedman', 'tobin', 'hayeks'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_45
  WTF: {'players', 'hall', 'allstar', 'tigers', 'hit', 'pitched', 'american'} {'youngs', 'greenberg', 'milwaukee', 'mlb', 'rockne', 'cy', 'doubleday'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_46
  WTF: {'change', 'law', 'word', 'happiness', 'pleasure', 'identity', 'death', 'pain', 'nature'} {'bce', 'democritus', 'heraclitus', 'epicurean', 'dk', 'lactantius', 'stoics', 'diogenes', 'epicurus'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_47
  WTF: {'conservative', 'theological', 'study', 'law', 'theology', 'prophets', 'work', 'university', 'rabbis', 'man', 'sabbath', 'studies', 'scholars'} {'heschel', 'jts', 'steinsaltz', 'hebrew', 'jewish', 'neusner', 'kushner', 'judaism', 'kaplans', 'neusners', 'talmud', 'torah', 'kaplan'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_48
  WTF: {'cancer', 'awareness', 'sexual', 'primary', 'election', 'husband', 'breast', 'president', 'sentence', 'parole', 'prison', 'women'} {'sacramento', 'soliah', 'california', 'lewinsky', 'olson', 'sla', 'jane', 'clinton', 'sara', 'laura', 'fargo', 'reno'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_49
  WTF: {'investiture', 'archbishop', 'mission', 'philosophersaint', 'anglosaxon', '279306', 'bishop', 'magick', 'magical', 'works', 'ecclesiastica'} {'bedes', 'anselm', 'bede', 'canterbury', 'aleister', 'augustine', 'vaughn', 'crowley', 'crowleys', 'anselms', 'sutin'}
  WTF?!?!? 11
  WTF?!?!? 11
{'fix': <__main__.FastFixPhiRegularizer object at 0x7fd2d1a9cfd0>}
Check after fit:
Skipping background topic: background_1.
topic_0
  WTF: {'academy', 'american', 'career', '2008'} {'hitchcock', 'paul', 'robeson', 'cagney'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_1
  WTF: {'machine', 'information', 'computers', 'language', 'institute', 'operating', 'interview', 'award'} {'shannon', 'minsky', 'sanger', 'turing', 'engelbart', 'babbage', 'zuse', 'wikipedia'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_2
  WTF: {'teslas', 'hertz', 'science', 'theory', 'institute', 'research', 'nuclear', 'radio'} {'bohr', 'fermi', 'davy', 'planck', 'faraday', 'bardeen', 'nikola', 'marconi'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_3
  WTF: {'musical', 'string', 'words', 'quartet', 'opera', 'trio', 'da'} {'elgar', 'wk', 'handel', 'shostakovich', 'hoffmann', 'lugosi', 'haydn'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_4
  WTF: {'writing', 'poems', 'short', 'wrote', 'family', 'story', 'university', 'letters', 'press', 'new'} {'shelleys', 'tolkien', 'lewis', 'shelley', 'jane', 'austen', 'dickens', 'wollstonecraft', 'mary', 'updike'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_5
  WTF: {'annals', 'military', 'emperors', 'caesars', 'life', 'ce', 'gibbon', 'senate', 'ad', 'death', 'caesar', 'imperial'} {'augustus', 'rome', 'barnes', 'julian', 'constantius', 'claudius', 'caligula', 'tiberius', 'hadrian', 'diocletian', 'tacitus', 'suetonius'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_6
  WTF: {'war', 'army', 'military', 'film', 'congress', 'committee', 'state', 'time', 'world', 'match', 'revolution', 'government', 'order', 'new', 'central'} {'lenin', 'russian', 'moscow', 'trotsky', 'khmelnytsky', 'alexander', 'chekhov', 'stalin', 'beria', 'gorbachev', 'sakharov', 'tito', 'kasparov', 'yeltsin', 'russia'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_7
  WTF: {'pope', 'della', 'pietro', 'film', 'marble', 'san', 'work', 'life', 'painting', 'del', 'il', 'new'} {'giordano', 'caravaggios', 'caravaggio', 'florence', 'rome', 'medici', 'lucrezia', 'borgia', 'angelico', 'fellini', 'bruno', 'lorenzo'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_8
  WTF: {'army', 'jews', 'state', 'work', 'party', 'theory', 'political', 'von', 'logic', 'published', 'history', 'social', 'und', 'phenomenology'} {'germany', 'mccarthy', 'husserl', 'schwitters', 'reich', 'goebbels', 'hegel', 'hesse', 'gring', 'berlin', 'hegels', 'habermas', 'hitler', 'nazi'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_9
  WTF: {'designed', 'new', 'van', 'buildings', 'painter', 'architect', 'museum', 'building', 'painted'} {'wright', 'lloyd', 'paris', 'debussy', 'rodin', 'wrights', 'monet', 'david', 'mies'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_10
  WTF: {'english', 'world', 'best', 'mars'} {'steinbeck', 'crichton', 'verne', 'moorcock'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_11
  WTF: {'grand', 'career', 'championship', 'lost', 'wickets', 'tennis'} {'jordan', 'earnhardt', 'agassi', 'muralitharan', 'schumacher', 'hingis'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_12
  WTF: {'isbn', 'book', 'years', 'later', 'work', 'published', 'al', 'press', 'poem'} {'abner', 'capp', 'joyce', 'kirby', 'keats', 'lil', 'carroll', 'housman', 'joyces'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_13
  WTF: {'army', 'married', 'chancellor', 'military', 'otto', 'margrave', 'prince', 'emperor', 'iii', 'ii', 'died', 'maternal', 'insurance', 'paternal'} {'germany', 'clausewitz', 'gustavus', 'joachim', 'prussia', 'albert', 'albertus', 'bismarck', 'bismarcks', 'prussian', 'brandenburg', 'saxony', 'frederick', 'dresden'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_14
  WTF: {'records', 'albums', 'songs', 'brooks'} {'peart', 'browns', 'james', 'nesmith'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_15
  WTF: {'war', 'allied', 'john', 'captain', 'admiral', 'commander', 'nova', 'attack', 'ships', 'cook', 'lord', 'royal'} {'british', 'drake', 'canada', 'nelson', 'canadian', 'wellington', 'montgomery', 'riel', 'mountbatten', 'rommel', 'macdonald', 'tupper'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_16
  WTF: {'surgeon', 'nobel', 'world', 'theory', 'stress', 'vaccination', 'discovery', 'physician'} {'fleming', 'koch', 'pasteur', 'carrel', 'lister', 'jenner', 'edinburgh', 'hutton'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_17
  WTF: {'war', 'empereurs', 'senso', 'japon', 'lady', 'clan', 'month', 'emperors', 'son', 'throne', 'court'} {'chinese', 'minamoto', 'nichiren', 'chiang', 'fujiwara', 'titsingh', 'kaishek', 'japanese', 'japan', 'deng', 'varley'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_18
  WTF: {'army', 'city', 'son', 'medicine', 'sn', 'time', 'ali', 'empire', 'muslims', 'history', 'caliph', 'nadir', 'aga', 'amir'} {'afghanistan', 'persian', 'abd', 'rumi', 'sina', 'battuta', 'arrahman', 'islamic', 'avicenna', 'jahangir', 'rumis', 'muhammad', 'abu', 'ahmad'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_19
  WTF: {'mathematicians', 'proof', 'scientific', 'geometry', 'space', 'physics', 'university', 'astronomical', 'published', 'set', 'cohomology'} {'kepler', 'grothendieck', 'eulers', 'neumann', 'keplers', 'gdel', 'atiyah', 'euler', 'hilberts', 'hilbert', 'hoyle'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_20
  WTF: {'married', 'grand', 'turkey', 'reign', 'son', 'battle', 'pasha', 'prince', 'issue', 'valide', 'shah', 'followers', '1986', 'princess'} {'istanbul', 'turkish', 'meher', 'kalchuri', 'bayezid', 'mehmed', 'osman', 'abdulbah', 'aurangzeb', 'remey', 'murad', 'efendi', 'hh', 'aurangzebs'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_21
  WTF: {'war', 'american', 'united', 'pp', 'supreme', 'union', 'justice', 'new'} {'virginia', 'carson', 'stuart', 'quayle', 'hancock', 'navajo', 'davis', 'thomas'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_22
  WTF: {'sur', 'marquis', 'desire', 'subject', 'perception', 'work', 'political', 'works', 'prophecies', 'new', 'symbolic'} {'sartre', 'nostradamus', 'paris', 'lacan', 'rousseau', 'rousseaus', 'merleauponty', 'sade', 'diderot', 'deleuze', 'deleuzes'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_23
  WTF: {'saints', 'tours', 'book', 'day', 'writings', 'life', 'heresies', 'works', 'roman', 'chapter', 'sin'} {'chrysostom', 'athanasius', 'anthony', 'benedict', 'irenaeus', 'ephrem', 'alexandria', 'augustine', 'jerome', 'cyril', 'martin'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_24
  WTF: {'guitar', 'recording', 'playing', 'musicians', 'rock', 'miles'} {'brubeck', 'hooker', 'bo', 'haley', 'davis', 'armstrong'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_25
  WTF: {'married', 'isbn', 'kingdom', 'ed', 'pp', 'chronicle', 'iii', 'isles', 'kingship', 'died', 'death', 'ii', 'english', 'saga', 'killed'} {'macbeth', 'selkirk', 'coluim', 'scots', 'kenneth', 'oram', 'alexander', 'scotland', 'maclaurin', 'mel', 'alba', 'malcolm', 'duncan', 'malcolms', 'scottish'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_26
  WTF: {'war', 'harbor', 'moon', 'film', 'admiral', 'pearl', 'born', 'carrier', 'american', 'midway', 'dragon', 'pacific'} {'tokyo', 'akira', 'japanese', 'hearn', 'yamamoto', 'kurosawa', 'lafcadio', 'fukuyama', 'morita', 'japan', 'yamamotos', 'ueshiba'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_27
  WTF: {'roman', 'army', 'great', 'tours', 'son', 'empire', 'iii', 'ii', 'death', 'duke', 'spanish', 'imperial'} {'martel', 'france', 'italy', 'eugene', 'europe', 'attila', 'savoy', 'charlemagne', 'frankish', 'charles', 'louis', 'bernard'}
  WTF?!?!? 12
  WTF?!?!? 12

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7fd2bf8a1070>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7fd2d2140280>}
{'perplexity': 320706.0, 'coherence_20': 0.7444128080617007, 'diversity_euclidean': 0.03346587834592, 'diversity_jensenshannon': 0.6526411164018855, 'diversity_hellinger': 0.7657506564807545, 'diversity_cosine': 0.7381647492373689, 'fair_ppl_free': 2755.75341796875, 'fair_ppl_fix': 319511.78125, 'unfair_ppl_banklike': 320706.0}
{'num_topics': 51, 'num_common_words': 65750, 'num_model_words': 155407, 'num_bt_words': 135939, 'top_diffs': [{'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}]}
11
Num model topics: 52.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
  WTF: {'recording', 'single'} {'elvis', 'presley'}
topic_1
  WTF: {'army', 'palace', 'turkey', 'son', 'medicine', 'battle', 'time', 'ali', 'muslims', 'ii'} {'afghanistan', 'persian', 'abd', 'meher', 'rumi', 'arrahman', 'islamic', 'muhammad', 'abu', 'ahmad'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_2
  WTF: {'teslas', 'hertz', 'scientific', 'wireless', 'science', 'curie', 'nuclear'} {'bohr', 'fermi', 'davy', 'planck', 'faraday', 'nikola', 'marconi'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_3
  WTF: {'machine', 'information', 'computers', 'language', 'institute', 'operating', 'interview', 'award'} {'shannon', 'minsky', 'sanger', 'turing', 'engelbart', 'babbage', 'zuse', 'wikipedia'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_4
  WTF: {'poems', 'short', 'wrote', 'family', 'story', 'university', 'writing', 'press', 'new'} {'shelleys', 'tolkien', 'lewis', 'shelley', 'jane', 'austen', 'dickens', 'wollstonecraft', 'mary'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_5
  WTF: {'pope', 'della', 'film', 'leonardo', 'marble', 'san', 'work', 'life', 'painting', 'del', 'il', 'new'} {'giordano', 'caravaggios', 'caravaggio', 'florence', 'rome', 'medici', 'lucrezia', 'borgia', 'cesare', 'angelico', 'fellini', 'bruno'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_6
  WTF: {'annals', 'emperors', 'caesars', 'life', 'ce', 'gibbon', 'senate', 'ad', 'death', 'ancient', 'caesar', 'imperial'} {'augustus', 'rome', 'barnes', 'julian', 'constantius', 'claudius', 'caligula', 'tiberius', 'hadrian', 'diocletian', 'tacitus', 'suetonius'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_7
  WTF: {'army', 'jews', 'state', 'work', 'party', 'theory', 'political', 'von', 'logic', 'published', 'history', 'social', 'und', 'phenomenology'} {'germany', 'mccarthy', 'husserl', 'schwitters', 'reich', 'goebbels', 'hegel', 'hesse', 'gring', 'berlin', 'hegels', 'habermas', 'hitler', 'nazi'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_8
  WTF: {'communist', 'war', 'military', 'film', 'committee', 'state', 'time', 'world', 'match', 'life', 'revolution', 'bolsheviks', 'march', 'government', 'new'} {'lenin', 'russian', 'moscow', 'trotsky', 'khmelnytsky', 'alexander', 'nicholas', 'chekhov', 'beria', 'gorbachev', 'sakharov', 'kasparov', 'tarkovsky', 'yeltsin', 'russia'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_9
  WTF: {'series', 'world', 'books', 'english', 'mars'} {'steinbeck', 'moorcock', 'crichton', 'verne', 'pohl'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_10
  WTF: {'grand', 'career', 'championship', 'lost', 'wickets', 'world'} {'jordan', 'earnhardt', 'agassi', 'muralitharan', 'schumacher', 'hingis'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_11
  WTF: {'army', 'married', 'chancellor', 'military', 'otto', 'margrave', 'prince', 'emperor', 'iii', 'ii', 'died', 'maternal', 'insurance', 'paternal'} {'germany', 'clausewitz', 'gustavus', 'joachim', 'prussia', 'albert', 'albertus', 'bismarck', 'bismarcks', 'prussian', 'brandenburg', 'saxony', 'frederick', 'dresden'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_12
  WTF: {'musical', 'string', 'words', 'quartet', 'cello', 'trio', 'da'} {'elgar', 'wk', 'handel', 'shostakovich', 'hoffmann', 'lugosi', 'haydn'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_13
  WTF: {'saints', 'monastery', 'testament', 'medieval', 'pp', 'life', 'catholic', 'bishop', 'history', 'century', 'prophet'} {'bedes', 'athanasius', 'baptist', 'luke', 'anselm', 'jesus', 'bede', 'canterbury', 'augustine', 'mary', 'elijah'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_14
  WTF: {'episodes', '2008', 'movie', 'awards', 'voice', 'late', 'tonight', 'award', 'played'} {'leary', 'jones', 'belushi', 'voight', 'palin', 'letterman', 'coleman', 'leno', 'grammer'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_15
  WTF: {'army', 'john', 'pp', 'baron', 'supreme', 'union', 'general', 'american', 'new'} {'eisenhower', 'hoover', 'rumsfeld', 'carson', 'stuart', 'quayle', 'hancock', 'davis', 'thomas'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_16
  WTF: {'paint', 'landscape', 'painters', 'french', 'giger', 'millet', 'salon', 'museum'} {'pissarro', 'paris', 'rodin', 'davids', 'rodins', 'pei', 'monet', 'david'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_17
  WTF: {'surgeon', 'nobel', 'world', 'theory', 'stress', 'vaccination', 'discovery', 'physician'} {'fleming', 'koch', 'pasteur', 'carrel', 'lister', 'jenner', 'edinburgh', 'hutton'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_18
  WTF: {'war', 'empereurs', 'senso', 'japon', 'lady', 'clan', 'month', 'emperors', 'son', 'throne', 'court'} {'chinese', 'minamoto', 'nichiren', 'chiang', 'fujiwara', 'titsingh', 'kaishek', 'japanese', 'japan', 'deng', 'varley'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_19
  WTF: {'allied', 'john', 'voyage', 'admiral', 'attack', 'ships', 'navy', 'lord', 'royal'} {'british', 'drake', 'nelson', 'wellington', 'jay', 'montgomery', 'mountbatten', 'rommel', 'rommels'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_20
  WTF: {'cit', 'cartoonist', 'years', 'work', 'al', 'life', 'bubbles', 'lad', 'adventures', 'new', 'poem', 'art'} {'tintin', 'thurber', 'abner', 'capp', 'dodgson', 'kirby', 'keats', 'herg', 'lil', 'carroll', 'housman', 'capps'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_21
  WTF: {'black', 'career', '2008', 'television', 'appeared', 'days', '2006', '2005', 'new'} {'doris', 'anderson', 'kidman', 'robeson', 'robesons', 'paul', 'duberman', 'theron', 'naomi'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_22
  WTF: {'conservative', 'john', 'sir', 'crisis', '1939', 'lord', 'foot', 'cabinet', 'parliament'} {'british', 'canada', 'disraeli', 'canadian', 'riel', 'attlee', 'macdonald', 'holt', 'tupper'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_23
  WTF: {'success', 'role', 'actor', 'movie', 'time', 'actors', 'academy', 'directed', 'critics', 'received', 'set', 'brothers', 'new'} {'coen', 'fincher', 'cukor', 'demille', 'cagney', 'warren', 'mamet', 'david', 'cagneys', 'marvin', 'griffith', 'mcgilligan', 'coens'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_24
  WTF: {'married', 'isbn', 'kingdom', 'ed', 'pp', 'chronicle', 'iii', 'isles', 'kingship', 'died', 'death', 'ii', 'english', 'saga', 'killed'} {'macbeth', 'selkirk', 'coluim', 'scots', 'kenneth', 'oram', 'alexander', 'scotland', 'maclaurin', 'mel', 'alba', 'malcolm', 'duncan', 'malcolms', 'scottish'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_25
  WTF: {'sur', 'marquis', 'desire', 'subject', 'perception', 'work', 'political', 'works', 'prophecies', 'new', 'symbolic'} {'nostradamus', 'paris', 'lacan', 'rousseau', 'rousseaus', 'jacques', 'merleauponty', 'sade', 'diderot', 'deleuze', 'deleuzes'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_26
  WTF: {'geometry', 'algebraic', 'instantons', 'formula', 'space', 'mathematician', 'academy', 'university', 'topological', 'observations'} {'kepler', 'grothendieck', 'eulers', 'atiyah', 'caspar', 'euler', 'rmer', 'ktheory', 'johannes', 'keplers'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_27
  WTF: {'war', 'expedition', 'conquest', 'king', 'city', 'military', 'civil', 'married', 'time', 'issue', 'doa', 'president', 'troops', 'government', 'new'} {'madero', 'francis', 'alfonso', 'ortega', 'almagro', 'xavier', 'corts', 'cid', 'pizarro', 'daz', 'madrid', 'francisco', 'franco', 'mexico', 'francos'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_28
  WTF: {'comics', 'paintings', 'short', 'christian', 'work', 'life', 'story', 'polar', 'published', 'little', 'duck', '2005', 'new', 'art'} {'alvar', 'andersens', 'nansen', 'kafkas', 'norway', 'ibsen', 'eggum', 'franz', 'munch', 'kafka', 'aalto', 'prideaux', 'andersen', 'munchs'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_29
  WTF: {'great', 'words', 'dictionary', 'books', 'gin', 'life', 'society', 'meetings', 'cosmos', 'published', 'prior', 'church', 'christian'} {'yale', 'abbott', 'adler', 'burke', 'alcott', 'foxs', 'eli', 'mather', 'whitney', 'burkes', 'quakers', 'webster', 'nickalls'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_30
  WTF: {'apology', 'things', 'medicine', 'known', 'writings', 'fragments', 'history', 'roman', 'ancient', 'christian'} {'christ', 'galens', 'irenaeus', 'heraclitus', 'galen', 'archimedes', 'eusebius', 'dk', 'justin', 'epicurus'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_31
  WTF: {'army', 'spain', 'tours', 'great', 'son', 'empire', 'iii', 'duc', 'ii', 'duke', 'spanish', 'imperial'} {'martel', 'france', 'italy', 'eugene', 'eugenes', 'europe', 'savoy', 'charlemagne', 'frankish', 'charles', 'louis', 'bernard'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_32
  WTF: {'succession', 'reign', 'vii', 'earl', 'council', 'protestant', 'throne', 'duke', 'marriage', 'ii', 'death', 'kings', 'royal'} {'england', 'elizabeth', 'anne', 'wales', 'edward', 'owain', 'henrys', 'henry', 'charles', 'catherine', 'tudor', 'elizabeths', 'mary'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_33
  WTF: {'married', 'grand', 'ca', 'daughter', 'empress', 'dowager', 'queen', 'family', 'heir', 'sister', 'sons', 'ii', 'death', 'died', 'lands'} {'mieszko', 'bolesaw', 'jadwiga', 'poland', 'feodorovna', 'lithuania', 'hungary', 'leszek', 'krakw', 'miller', 'lithuanian', 'casimir', 'maria', 'mindaugas', 'jadwigas'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_34
  WTF: {'wolf', 'pietro', 'father', 'italian', 'feast', 'judges', 'roman', 'order', 'ibid', 'new', 'god'} {'polidori', 'francis', 'alberoni', 'bellarmine', 'rome', 'mychal', 'contarini', 'assisi', 'porziuncola', 'cardano', 'vampyre'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_35
  WTF: {'harbor', 'battle', 'manga', 'pearl', 'aircraft', 'samurai', 'born', 'navy', 'carrier', 'american', 'pacific'} {'tokyo', 'akira', 'takeuchi', 'japanese', 'yamamoto', 'kurosawa', 'morita', 'kurosawas', 'japan', 'yamamotos', 'ueshiba'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_36
  WTF: {'scientists', 'genome', 'behavior', 'self', 'evolution', 'environmentalist', 'carl', 'research', 'chapter'} {'rogers', 'wilson', 'kikuyu', 'rushton', 'venter', 'leakey', 'lomborg', 'louis', 'jensen'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_37
  WTF: {'scientific', 'science', 'ray', 'society', 'theory', 'animals', 'principles', 'origin', 'vol', 'geological', 'edition', 'plants'} {'slotten', 'mendel', 'mayr', 'haeckel', 'darwin', 'maynard', 'lyell', 'ernst', 'charles', 'wallace', 'wallaces', 'darwins'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_38
  WTF: {'stated', 'hijackers', 'united', 'department', 'waterboarding', 'flight', 'news', 'officials'} {'osama', 'saudi', 'cia', 'qaeda', 'zubaydahs', 'alqaeda', 'zubaydah', 'abu'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_39
  WTF: {'flew', 'flying', '11', 'navy', 'states', 'service', 'mach', 'crew'} {'apollo', 'jones', 'bingham', 'aldrin', 'hopper', 'armstrong', 'hansen', 'yeager'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_40
  WTF: {'years', 'later', 'work', 'life', 'des', 'published', 'mal', 'literary', 'fleurs', 'play'} {'flaubert', 'paris', 'satie', 'richardson', 'baudelaires', 'maupassant', 'jarry', 'saties', 'baudelaire', 'tremblay'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_41
  WTF: {'description', 'grammar', 'sounds', 'linguists', 'english'} {'hockett', 'whorf', 'jones', 'bantu', 'doke'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_42
  WTF: {'hot', 'pg', 'release', 'number', 'rb', 'singles', 'pop'} {'uk', 'mariah', 'careys', 'aaliyah', 'carey', 'enya', 'difranco'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_43
  WTF: {'daughter', 'navigator', 'coast', 'prince', 'mother', 'iii', 'ii', 'expeditions', 'infanta', 'infante'} {'afonso', 'len', 'albuquerque', 'castile', 'portuguese', 'sancho', 'henry', 'portugal', 'aragon', 'coimbra'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_44
  WTF: {'performed', 'musical', 'pensiero', 'film', 'chorus', 'composition', 'orchestra', 'requiem', 'libretto'} {'rossini', 'morricone', 'busseto', 'ennio', 'rossinis', 'verdis', 'giuseppe', 'morricones', 'gioachino'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_45
  WTF: {'players', 'hall', 'allstar', 'tigers', 'hit', 'pitched', 'american'} {'youngs', 'greenberg', 'milwaukee', 'mlb', 'rockne', 'cy', 'doubleday'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_46
  WTF: {'signs', 'induction', 'inquiry', 'interpretant', 'knowledge', 'pragmatism', 'sense', 'method'} {'bertrand', 'poppers', 'russell', 'russells', 'peirce', 'peirces', 'popper', 'moore'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_47
  WTF: {'shows', 'featured', 'film', 'lyrics', 'minutes', 'wrote', 'popular', 'composer', 'golf', 'musicals', 'radio'} {'elfman', 'ira', 'broadway', 'kern', 'dowland', 'crosby', 'crosbys', 'gershwin', 'dowlands', 'burton', 'bing'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_48
  WTF: {'conservative', 'theological', 'study', 'law', 'theology', 'prophets', 'work', 'university', 'rabbis', 'man', 'sabbath', 'studies', 'scholars'} {'heschel', 'jts', 'steinsaltz', 'hebrew', 'jewish', 'neusner', 'kushner', 'judaism', 'kaplans', 'neusners', 'talmud', 'torah', 'kaplan'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_49
  WTF: {'relationship', 'sentencing', 'school', '2002', 'primary', 'vote', 'election', 'march', 'bomb', 'councilman', 'general', 'murder', 'plea', 'parole'} {'sacramento', 'soliah', 'california', 'lewinsky', 'olson', 'eastman', 'sla', 'jane', 'heather', 'clinton', 'sara', 'fargo', 'reno', 'olsons'}
  WTF?!?!? 14
  WTF?!?!? 14
{'fix': <__main__.FastFixPhiRegularizer object at 0x7fd2bad00610>}
Check after fit:
Skipping background topic: background_1.
topic_0
  WTF: {'recording', 'single'} {'elvis', 'presley'}
topic_1
  WTF: {'army', 'palace', 'turkey', 'son', 'medicine', 'battle', 'time', 'ali', 'muslims', 'ii'} {'afghanistan', 'persian', 'abd', 'meher', 'rumi', 'arrahman', 'islamic', 'muhammad', 'abu', 'ahmad'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_2
  WTF: {'teslas', 'hertz', 'scientific', 'wireless', 'science', 'curie', 'nuclear'} {'bohr', 'fermi', 'davy', 'planck', 'faraday', 'nikola', 'marconi'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_3
  WTF: {'machine', 'information', 'computers', 'language', 'institute', 'operating', 'interview', 'award'} {'shannon', 'minsky', 'sanger', 'turing', 'engelbart', 'babbage', 'zuse', 'wikipedia'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_4
  WTF: {'poems', 'short', 'wrote', 'family', 'story', 'university', 'writing', 'press', 'new'} {'shelleys', 'tolkien', 'lewis', 'shelley', 'jane', 'austen', 'dickens', 'wollstonecraft', 'mary'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_5
  WTF: {'pope', 'della', 'film', 'leonardo', 'marble', 'san', 'work', 'life', 'painting', 'del', 'il', 'new'} {'giordano', 'caravaggios', 'caravaggio', 'florence', 'rome', 'medici', 'lucrezia', 'borgia', 'cesare', 'angelico', 'fellini', 'bruno'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_6
  WTF: {'annals', 'emperors', 'caesars', 'life', 'ce', 'gibbon', 'senate', 'ad', 'death', 'ancient', 'caesar', 'imperial'} {'augustus', 'rome', 'barnes', 'julian', 'constantius', 'claudius', 'caligula', 'tiberius', 'hadrian', 'diocletian', 'tacitus', 'suetonius'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_7
  WTF: {'army', 'jews', 'state', 'work', 'party', 'theory', 'political', 'von', 'logic', 'published', 'history', 'social', 'und', 'phenomenology'} {'germany', 'mccarthy', 'husserl', 'schwitters', 'reich', 'goebbels', 'hegel', 'hesse', 'gring', 'berlin', 'hegels', 'habermas', 'hitler', 'nazi'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_8
  WTF: {'communist', 'war', 'military', 'film', 'committee', 'state', 'time', 'world', 'match', 'life', 'revolution', 'bolsheviks', 'march', 'government', 'new'} {'lenin', 'russian', 'moscow', 'trotsky', 'khmelnytsky', 'alexander', 'nicholas', 'chekhov', 'beria', 'gorbachev', 'sakharov', 'kasparov', 'tarkovsky', 'yeltsin', 'russia'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_9
  WTF: {'series', 'world', 'books', 'english', 'mars'} {'steinbeck', 'moorcock', 'crichton', 'verne', 'pohl'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_10
  WTF: {'grand', 'career', 'championship', 'lost', 'wickets', 'world'} {'jordan', 'earnhardt', 'agassi', 'muralitharan', 'schumacher', 'hingis'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_11
  WTF: {'army', 'married', 'chancellor', 'military', 'otto', 'margrave', 'prince', 'emperor', 'iii', 'ii', 'died', 'maternal', 'insurance', 'paternal'} {'germany', 'clausewitz', 'gustavus', 'joachim', 'prussia', 'albert', 'albertus', 'bismarck', 'bismarcks', 'prussian', 'brandenburg', 'saxony', 'frederick', 'dresden'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_12
  WTF: {'musical', 'string', 'words', 'quartet', 'cello', 'trio', 'da'} {'elgar', 'wk', 'handel', 'shostakovich', 'hoffmann', 'lugosi', 'haydn'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_13
  WTF: {'saints', 'monastery', 'testament', 'medieval', 'pp', 'life', 'catholic', 'bishop', 'history', 'century', 'prophet'} {'bedes', 'athanasius', 'baptist', 'luke', 'anselm', 'jesus', 'bede', 'canterbury', 'augustine', 'mary', 'elijah'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_14
  WTF: {'episodes', '2008', 'movie', 'awards', 'voice', 'late', 'tonight', 'award', 'played'} {'leary', 'jones', 'belushi', 'voight', 'palin', 'letterman', 'coleman', 'leno', 'grammer'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_15
  WTF: {'army', 'john', 'pp', 'baron', 'supreme', 'union', 'general', 'american', 'new'} {'eisenhower', 'hoover', 'rumsfeld', 'carson', 'stuart', 'quayle', 'hancock', 'davis', 'thomas'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_16
  WTF: {'paint', 'landscape', 'painters', 'french', 'giger', 'millet', 'salon', 'museum'} {'pissarro', 'paris', 'rodin', 'davids', 'rodins', 'pei', 'monet', 'david'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_17
  WTF: {'surgeon', 'nobel', 'world', 'theory', 'stress', 'vaccination', 'discovery', 'physician'} {'fleming', 'koch', 'pasteur', 'carrel', 'lister', 'jenner', 'edinburgh', 'hutton'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_18
  WTF: {'war', 'empereurs', 'senso', 'japon', 'lady', 'clan', 'month', 'emperors', 'son', 'throne', 'court'} {'chinese', 'minamoto', 'nichiren', 'chiang', 'fujiwara', 'titsingh', 'kaishek', 'japanese', 'japan', 'deng', 'varley'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_19
  WTF: {'allied', 'john', 'voyage', 'admiral', 'attack', 'ships', 'navy', 'lord', 'royal'} {'british', 'drake', 'nelson', 'wellington', 'jay', 'montgomery', 'mountbatten', 'rommel', 'rommels'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_20
  WTF: {'cit', 'cartoonist', 'years', 'work', 'al', 'life', 'bubbles', 'lad', 'adventures', 'new', 'poem', 'art'} {'tintin', 'thurber', 'abner', 'capp', 'dodgson', 'kirby', 'keats', 'herg', 'lil', 'carroll', 'housman', 'capps'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_21
  WTF: {'black', 'career', '2008', 'television', 'appeared', 'days', '2006', '2005', 'new'} {'doris', 'anderson', 'kidman', 'robeson', 'robesons', 'paul', 'duberman', 'theron', 'naomi'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_22
  WTF: {'conservative', 'john', 'sir', 'crisis', '1939', 'lord', 'foot', 'cabinet', 'parliament'} {'british', 'canada', 'disraeli', 'canadian', 'riel', 'attlee', 'macdonald', 'holt', 'tupper'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_23
  WTF: {'success', 'role', 'actor', 'movie', 'time', 'actors', 'academy', 'directed', 'critics', 'received', 'set', 'brothers', 'new'} {'coen', 'fincher', 'cukor', 'demille', 'cagney', 'warren', 'mamet', 'david', 'cagneys', 'marvin', 'griffith', 'mcgilligan', 'coens'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_24
  WTF: {'married', 'isbn', 'kingdom', 'ed', 'pp', 'chronicle', 'iii', 'isles', 'kingship', 'died', 'death', 'ii', 'english', 'saga', 'killed'} {'macbeth', 'selkirk', 'coluim', 'scots', 'kenneth', 'oram', 'alexander', 'scotland', 'maclaurin', 'mel', 'alba', 'malcolm', 'duncan', 'malcolms', 'scottish'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_25
  WTF: {'sur', 'marquis', 'desire', 'subject', 'perception', 'work', 'political', 'works', 'prophecies', 'new', 'symbolic'} {'nostradamus', 'paris', 'lacan', 'rousseau', 'rousseaus', 'jacques', 'merleauponty', 'sade', 'diderot', 'deleuze', 'deleuzes'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_26
  WTF: {'geometry', 'algebraic', 'instantons', 'formula', 'space', 'mathematician', 'academy', 'university', 'topological', 'observations'} {'kepler', 'grothendieck', 'eulers', 'atiyah', 'caspar', 'euler', 'rmer', 'ktheory', 'johannes', 'keplers'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_27
  WTF: {'war', 'expedition', 'conquest', 'king', 'city', 'military', 'civil', 'married', 'time', 'issue', 'doa', 'president', 'troops', 'government', 'new'} {'madero', 'francis', 'alfonso', 'ortega', 'almagro', 'xavier', 'corts', 'cid', 'pizarro', 'daz', 'madrid', 'francisco', 'franco', 'mexico', 'francos'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_28

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7fd2fc0954c0>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7fd215aeecd0>}
{'perplexity': 347883.375, 'coherence_20': 0.7905966539651774, 'diversity_euclidean': 0.03331696429909047, 'diversity_jensenshannon': 0.6531548535321897, 'diversity_hellinger': 0.766417822553877, 'diversity_cosine': 0.7361010499671861, 'fair_ppl_free': 2755.047119140625, 'fair_ppl_fix': 340432.4375, 'unfair_ppl_banklike': 347883.375}
{'num_topics': 52, 'num_common_words': 65750, 'num_model_words': 155407, 'num_bt_words': 135939, 'top_diffs': [{'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}]}
12
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
  WTF: {'interrogation', 'army', '2002', 'ali', 'empire', 'muslims', 'al', 'government', 'new'} {'afghanistan', 'persian', 'abd', 'rumi', 'cia', 'islamic', 'muhammad', 'zubaydah', 'abu'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_1
  WTF: {'albums', 'single'} {'elvis', 'presley'}
topic_2
  WTF: {'dio', 'greek', 'annals', 'emperors', 'caesars', 'life', 'ce', 'senate', 'death', 'ancient', 'caesar', 'imperial'} {'augustus', 'rome', 'barnes', 'julian', 'eusebius', 'constantius', 'claudius', 'caligula', 'tiberius', 'diocletian', 'tacitus', 'suetonius'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_3
  WTF: {'string', 'verdi', 'concerto', 'composers', 'gamba', 'trio', 'da'} {'elgar', 'wk', 'shostakovich', 'chopin', 'lugosi', 'chopins', 'haydn'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_4
  WTF: {'machine', 'information', 'computers', 'program', 'institute', 'operating', 'mathematical', 'award', 'mathematics'} {'shannon', 'minsky', 'sanger', 'turing', 'engelbart', 'warwick', 'babbage', 'zuse', 'wikipedia'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_5
  WTF: {'pope', 'della', 'film', 'marble', 'san', 'work', 'life', 'painting', 'title', 'del', 'il', 'new'} {'giordano', 'caravaggios', 'caravaggio', 'florence', 'rome', 'medici', 'lucrezia', 'borgia', 'angelico', 'fellini', 'bruno', 'lorenzo'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_6
  WTF: {'grand', 'championship', 'lost', '62', 'tennis'} {'jordan', 'earnhardt', 'agassi', 'muralitharan', 'schumacher'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_7
  WTF: {'professor', 'scientific', 'atomic', 'chemical', 'science', 'quantum', 'institute', 'research', 'nuclear'} {'bohr', 'fermi', 'davy', 'planck', 'faraday', 'marie', 'bardeen', 'heaviside', 'marconi'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_8
  WTF: {'war', 'army', 'chess', 'military', 'film', 'committee', 'state', 'time', 'world', 'revolution', 'government', 'march', 'ii', 'order', 'new'} {'russian', 'moscow', 'trotsky', 'khmelnytsky', 'alexander', 'nicholas', 'stalin', 'chekhov', 'beria', 'gorbachev', 'sakharov', 'tito', 'kasparov', 'yeltsin', 'russia'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_9
  WTF: {'theatre', 'movie', 'awards', 'comedy', 'nominated', '2005'} {'leary', 'belushi', 'anderson', 'kidman', 'coleman', 'grammer'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_10
  WTF: {'du', 'psychoanalysis', 'subject', 'time', 'work', 'life', 'des', 'trans', 'political', 'university', 'published', 'new'} {'sartre', 'nostradamus', 'paris', 'lacan', 'rousseau', 'satie', 'rousseaus', 'merleauponty', 'camus', 'sade', 'baudelaire', 'deleuze'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_11
  WTF: {'war', 'married', 'daughter', 'otto', 'son', 'empress', 'margrave', 'prince', 'emperor', 'von', 'iii', 'died', 'death', 'maternal', 'paternal'} {'germany', 'austria', 'gustavus', 'joachim', 'prussia', 'albert', 'albertus', 'bismarck', 'bismarcks', 'prussian', 'brandenburg', 'saxony', 'frederick', 'maria', 'dresden'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_12
  WTF: {'world', 'books', 'mars'} {'moorcock', 'crichton', 'verne'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_13
  WTF: {'surgeon', 'nobel', 'world', 'theory', 'stress', 'vaccination', 'discovery', 'physician'} {'fleming', 'koch', 'pasteur', 'carrel', 'lister', 'jenner', 'edinburgh', 'hutton'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_14
  WTF: {'book', 'tours', 'testament', 'catholic', 'feast', 'bishop', 'apostles', 'century', 'relics', 'gospels', 'chapter', 'god'} {'christ', 'chrysostom', 'athanasius', 'anthony', 'baptist', 'luke', 'jesus', 'irenaeus', 'ephrem', 'alexandria', 'mary', 'martin'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_15
  WTF: {'directors', 'time', 'actors', 'directed', 'received', 'picture', 'screenplay', 'new'} {'cukor', 'scorsese', 'warren', 'voight', 'york', 'mcgilligan', 'cameron', 'cagney'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_16
  WTF: {'war', 'empereurs', 'senso', 'japon', 'lady', 'clan', 'month', 'emperors', 'son', 'throne', 'court'} {'chinese', 'minamoto', 'fujiwara', 'chiang', 'titsingh', 'kaishek', 'japanese', 'japan', 'dengs', 'deng', 'varley'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_17
  WTF: {'united', 'cavalry', 'pp', 'supreme', 'union', 'general', 'justice', 'new'} {'stuart', 'warren', 'oswald', 'quayle', 'hancock', 'davis', 'lee', 'thomas'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_18
  WTF: {'paint', 'painters', 'french', 'giger', 'millet', 'salon', 'museum'} {'pissarro', 'rodin', 'paris', 'davids', 'rodins', 'monet', 'david'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_19
  WTF: {'allied', 'voyage', 'admiral', 'ship', 'attack', 'ships', 'navy', 'lord', 'royal'} {'british', 'drake', 'nelson', 'wellington', 'montgomery', 'mountbatten', 'rommel', 'sugden', 'rommels'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_20
  WTF: {'conservative', 'john', 'sir', 'crisis', '1939', 'lord', 'foot', 'cabinet', 'parliament'} {'british', 'canada', 'disraeli', 'canadian', 'riel', 'attlee', 'macdonald', 'holt', 'tupper'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_21
  WTF: {'isbn', 'woman', 'poems', 'short', 'spark', 'stories', 'books', 'introduction', 'life', 'family', 'fiction', 'story', 'works', 'letters', 'press', 'women'} {'seymour', 'charlotte', 'shelleys', 'christie', 'shelley', 'anne', 'bronts', 'godwin', 'jane', 'austens', 'austen', 'tomalin', 'bront', 'wollstonecraft', 'mary', 'percy'}
  WTF?!?!? 16
  WTF?!?!? 16
topic_22
  WTF: {'observatory', 'scientific', 'geometry', 'algebraic', 'planetary', 'academy', 'theorem', 'university', 'published', 'light', 'tables', 'observations'} {'tycho', 'kepler', 'grothendieck', 'eulers', 'abel', 'euler', 'caspar', 'rmer', 'napier', 'johannes', 'keplers', 'celsius'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_23
  WTF: {'isbn', 'kingdom', 'prophecy', 'ed', 'pp', 'chronicle', 'iii', 'isles', 'kingship', 'ii', 'death', 'died', 'english', 'saga', 'killed'} {'macbeth', 'selkirk', 'coluim', 'scots', 'kenneth', 'oram', 'alexander', 'scotland', 'maclaurin', 'mel', 'alba', 'malcolm', 'duncan', 'malcolms', 'scottish'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_24
  WTF: {'poets', 'illustrations', 'ed', 'english', 'literature', 'published', 'works', 'letters', 'nonsense', 'verse', 'lines'} {'london', 'severn', 'masefield', 'lear', 'nash', 'keats', 'housmans', 'shropshire', 'hopkinss', 'hopkins', 'housman'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_25
  WTF: {'systems', 'die', 'reason', 'zur', 'ed', 'society', 'trans', 'objects', 'psychology', 'phenomenology'} {'luhmann', 'husserl', 'schwitters', 'husserls', 'ebbinghaus', 'berlin', 'habermas', 'schumpeter', 'fichte', 'frankfurt'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_26
  WTF: {'paintings', 'short', 'collection', 'award', 'christian', 'work', 'life', 'polar', 'little', 'works', '2005', 'scream', 'new', 'art'} {'alvar', 'nansen', 'kafkas', 'ibsen', 'eggum', 'munch', 'kafka', 'leiber', 'fafhrd', 'aalto', 'prideaux', 'andersen', 'mouser', 'munchs'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_27
  WTF: {'war', 'harbor', 'moon', 'battle', 'manga', 'pearl', 'samurai', 'born', 'navy', 'carrier', 'american', 'pacific'} {'tokyo', 'nichiren', 'akira', 'japanese', 'yamamoto', 'kurosawa', 'fukuyama', 'morita', 'kurosawas', 'japan', 'yamamotos', 'ueshiba'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_28
  WTF: {'biography', 'book', 'poems', 'house', 'books', 'world', 'work', 'life', 'literary', 'lord', 'letters', 'novel'} {'lewiss', 'amis', 'melville', 'tolkien', 'lewis', 'tolkiens', 'dickenss', 'conrads', 'dickens', 'oxford', 'charles', 'conrad'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_29
  WTF: {'war', 'expedition', 'conquest', 'king', 'city', 'military', 'civil', 'son', 'married', 'issue', 'doa', 'troops', 'government', 'governor', 'new'} {'madero', 'francis', 'alfonso', 'almagro', 'xavier', 'mara', 'corts', 'cid', 'pizarro', 'daz', 'francisco', 'madrid', 'franco', 'mexico', 'francos'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_30
  WTF: {'succession', 'reign', 'vii', 'earl', 'council', 'protestant', 'throne', 'duke', 'marriage', 'ii', 'death', 'kings', 'royal'} {'england', 'elizabeth', 'anne', 'wales', 'edward', 'owain', 'henrys', 'henry', 'charles', 'catherine', 'tudor', 'elizabeths', 'mary'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_31
  WTF: {'army', 'spain', 'tours', 'great', 'son', 'empire', 'iii', 'duc', 'ii', 'duke', 'spanish', 'imperial'} {'martel', 'france', 'italy', 'eugene', 'eugenes', 'europe', 'savoy', 'charlemagne', 'frankish', 'charles', 'louis', 'bernard'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_32
  WTF: {'isbn', 'speller', 'school', 'books', 'trials', 'children', 'witch', 'haven', 'published', 'anthropologist', 'college', 'church', 'spelling', 'christian'} {'yale', 'abbott', 'mead', 'alcott', 'samoa', 'bellamy', 'noah', 'connecticut', 'eli', 'mather', 'mathers', 'margaret', 'whitney', 'webster'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_33
  WTF: {'rpt', 'description', 'humans', 'grammar', 'sounds', 'linguists', 'english'} {'hockett', 'whorf', 'jones', 'bantu', 'westermann', 'doke', 'diedrich'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_34
  WTF: {'iraq', 'mission', 'powers', 'served', 'flying', 'corps', 'service'} {'rumsfeld', 'apollo', 'jones', 'hopper', 'armstrong', 'hansen', 'yeager'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_35
  WTF: {'police', 'army', 'chancellor', 'law', '1945', 'foreign', 'von', 'political', 'power', 'nazis', 'crimes', 'sa', 'people', 'face'} {'waldheim', 'germany', 'reich', 'goebbels', 'gring', 'berlin', 'luftwaffe', 'hitlers', 'hitler', 'kershaw', 'grings', 'reichstag', 'nazi', 'himmler'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_36
  WTF: {'biology', 'science', 'ray', 'animals', 'theory', 'society', 'principles', 'archaeology', 'origin', 'history', 'vol', 'edition', 'chapter'} {'slotten', 'london', 'mayr', 'haeckel', 'darwin', 'lyell', 'ernst', 'leakey', 'charles', 'wallace', 'louis', 'wallaces', 'darwins'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_37
  WTF: {'married', 'ca', 'queen', 'emperor', 'dukes', 'wife', 'sons', 'ii', 'death', 'died', 'iv', 'order', 'brother'} {'mieszko', 'poland', 'bolesaw', 'jadwiga', 'lithuania', 'hungary', 'krakw', 'kazimierz', 'lithuanian', 'casimir', 'mindaugas', 'jadwigas', 'sigismund'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_38
  WTF: {'wolf', 'pietro', 'giovanni', 'father', 'life', 'italian', 'bishop', 'duke', 'order', 'ibid', 'god'} {'francis', 'alberoni', 'bellarmine', 'rome', 'mychal', 'contarini', 'borgia', 'cesare', 'porziuncola', 'cardano', 'assisi'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_39
  WTF: {'differences', 'scientists', 'behavior', 'environmentalist', 'individual', 'carl', 'research'} {'rogers', 'wilson', 'rushton', 'jensens', 'venter', 'lomborg', 'jensen'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_40
  WTF: {'hot', 'pg', 'release', 'number', 'rb', 'singles', 'pop'} {'uk', 'mariah', 'careys', 'aaliyah', 'carey', 'enya', 'difranco'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_41
  WTF: {'freedom', 'economists', 'education', 'value', 'banking', 'economist', 'social', 'money', 'government', 'philosophy'} {'ricardo', 'dewey', 'rothbard', 'hayek', 'mises', 'deweys', 'murray', 'friedman', 'tobin', 'hayeks'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_42
  WTF: {'daughter', 'navigator', 'coast', 'prince', 'mother', 'iii', 'ii', 'expeditions', 'infanta', 'infante'} {'afonso', 'len', 'albuquerque', 'castile', 'portuguese', 'sancho', 'henry', 'portugal', 'aragon', 'coimbra'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_43
  WTF: {'investiture', 'king', 'mission', 'philosophersaint', 'anglosaxon', 'abbey', '279306', 'bishop', 'magick', 'works', 'english', 'historia'} {'bedes', 'anselm', 'bede', 'canterbury', 'aleister', 'dunstan', 'augustine', 'vaughn', 'crowley', 'crowleys', 'anselms', 'sutin'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_44
  WTF: {'signs', 'induction', 'inquiry', 'interpretant', 'knowledge', 'pragmatism', 'sense', 'method'} {'bertrand', 'poppers', 'russell', 'russells', 'peirce', 'peirces', 'popper', 'moore'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_45
  WTF: {'shows', 'featured', 'film', 'lyrics', 'minutes', 'wrote', 'popular', 'composer', 'golf', 'musicals', 'radio'} {'elfman', 'ira', 'broadway', 'kern', 'dowland', 'crosby', 'crosbys', 'gershwin', 'dowlands', 'burton', 'bing'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_46
  WTF: {'conservative', 'theological', 'study', 'law', 'theology', 'prophets', 'work', 'university', 'rabbis', 'man', 'sabbath', 'studies', 'scholars'} {'heschel', 'jts', 'steinsaltz', 'hebrew', 'jewish', 'neusner', 'kushner', 'judaism', 'kaplans', 'neusners', 'talmud', 'torah', 'kaplan'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_47
  WTF: {'relationship', 'sentencing', 'school', '2002', 'primary', 'vote', 'election', 'march', 'bomb', 'councilman', 'general', 'murder', 'plea', 'parole'} {'sacramento', 'soliah', 'california', 'lewinsky', 'olson', 'eastman', 'sla', 'jane', 'heather', 'clinton', 'sara', 'fargo', 'reno', 'olsons'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_48
  WTF: {'numbers', 'prize', '18991920', 'number', 'university', 'bang', 'chance', 'royal', 'nuclear'} {'cambridge', 'geoffrey', 'moseley', 'hoyles', 'brewster', 'moseleys', 'hoyle', 'fred', 'rayleigh'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_49
  WTF: {'captain', 'new', 'shmoo', 'cartoonists', 'best', 'work', 'syndicated', 'award', 'characters', 'shmoos', 'art'} {'abner', 'capp', 'hobbes', 'simon', 'decarlo', 'trudeau', 'watterson', 'kirby', 'lil', 'capps', 'kirbys'}
  WTF?!?!? 11
  WTF?!?!? 11
{'fix': <__main__.FastFixPhiRegularizer object at 0x7fd2d1acd9a0>}
Check after fit:
Skipping background topic: background_1.
topic_0
  WTF: {'interrogation', 'army', '2002', 'ali', 'empire', 'muslims', 'al', 'government', 'new'} {'afghanistan', 'persian', 'abd', 'rumi', 'cia', 'islamic', 'muhammad', 'zubaydah', 'abu'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_1
  WTF: {'albums', 'single'} {'elvis', 'presley'}
topic_2
  WTF: {'dio', 'greek', 'annals', 'emperors', 'caesars', 'life', 'ce', 'senate', 'death', 'ancient', 'caesar', 'imperial'} {'augustus', 'rome', 'barnes', 'julian', 'eusebius', 'constantius', 'claudius', 'caligula', 'tiberius', 'diocletian', 'tacitus', 'suetonius'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_3
  WTF: {'string', 'verdi', 'concerto', 'composers', 'gamba', 'trio', 'da'} {'elgar', 'wk', 'shostakovich', 'chopin', 'lugosi', 'chopins', 'haydn'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_4
  WTF: {'machine', 'information', 'computers', 'program', 'institute', 'operating', 'mathematical', 'award', 'mathematics'} {'shannon', 'minsky', 'sanger', 'turing', 'engelbart', 'warwick', 'babbage', 'zuse', 'wikipedia'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_5
  WTF: {'pope', 'della', 'film', 'marble', 'san', 'work', 'life', 'painting', 'title', 'del', 'il', 'new'} {'giordano', 'caravaggios', 'caravaggio', 'florence', 'rome', 'medici', 'lucrezia', 'borgia', 'angelico', 'fellini', 'bruno', 'lorenzo'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_6
  WTF: {'grand', 'championship', 'lost', '62', 'tennis'} {'jordan', 'earnhardt', 'agassi', 'muralitharan', 'schumacher'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_7
  WTF: {'professor', 'scientific', 'atomic', 'chemical', 'science', 'quantum', 'institute', 'research', 'nuclear'} {'bohr', 'fermi', 'davy', 'planck', 'faraday', 'marie', 'bardeen', 'heaviside', 'marconi'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_8
  WTF: {'war', 'army', 'chess', 'military', 'film', 'committee', 'state', 'time', 'world', 'revolution', 'government', 'march', 'ii', 'order', 'new'} {'russian', 'moscow', 'trotsky', 'khmelnytsky', 'alexander', 'nicholas', 'stalin', 'chekhov', 'beria', 'gorbachev', 'sakharov', 'tito', 'kasparov', 'yeltsin', 'russia'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_9
  WTF: {'theatre', 'movie', 'awards', 'comedy', 'nominated', '2005'} {'leary', 'belushi', 'anderson', 'kidman', 'coleman', 'grammer'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_10
  WTF: {'du', 'psychoanalysis', 'subject', 'time', 'work', 'life', 'des', 'trans', 'political', 'university', 'published', 'new'} {'sartre', 'nostradamus', 'paris', 'lacan', 'rousseau', 'satie', 'rousseaus', 'merleauponty', 'camus', 'sade', 'baudelaire', 'deleuze'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_11
  WTF: {'war', 'married', 'daughter', 'otto', 'son', 'empress', 'margrave', 'prince', 'emperor', 'von', 'iii', 'died', 'death', 'maternal', 'paternal'} {'germany', 'austria', 'gustavus', 'joachim', 'prussia', 'albert', 'albertus', 'bismarck', 'bismarcks', 'prussian', 'brandenburg', 'saxony', 'frederick', 'maria', 'dresden'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_12
  WTF: {'world', 'books', 'mars'} {'moorcock', 'crichton', 'verne'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_13
  WTF: {'surgeon', 'nobel', 'world', 'theory', 'stress', 'vaccination', 'discovery', 'physician'} {'fleming', 'koch', 'pasteur', 'carrel', 'lister', 'jenner', 'edinburgh', 'hutton'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_14
  WTF: {'book', 'tours', 'testament', 'catholic', 'feast', 'bishop', 'apostles', 'century', 'relics', 'gospels', 'chapter', 'god'} {'christ', 'chrysostom', 'athanasius', 'anthony', 'baptist', 'luke', 'jesus', 'irenaeus', 'ephrem', 'alexandria', 'mary', 'martin'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_15
  WTF: {'directors', 'time', 'actors', 'directed', 'received', 'picture', 'screenplay', 'new'} {'cukor', 'scorsese', 'warren', 'voight', 'york', 'mcgilligan', 'cameron', 'cagney'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_16
  WTF: {'war', 'empereurs', 'senso', 'japon', 'lady', 'clan', 'month', 'emperors', 'son', 'throne', 'court'} {'chinese', 'minamoto', 'fujiwara', 'chiang', 'titsingh', 'kaishek', 'japanese', 'japan', 'dengs', 'deng', 'varley'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_17
  WTF: {'united', 'cavalry', 'pp', 'supreme', 'union', 'general', 'justice', 'new'} {'stuart', 'warren', 'oswald', 'quayle', 'hancock', 'davis', 'lee', 'thomas'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_18
  WTF: {'paint', 'painters', 'french', 'giger', 'millet', 'salon', 'museum'} {'pissarro', 'rodin', 'paris', 'davids', 'rodins', 'monet', 'david'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_19
  WTF: {'allied', 'voyage', 'admiral', 'ship', 'attack', 'ships', 'navy', 'lord', 'royal'} {'british', 'drake', 'nelson', 'wellington', 'montgomery', 'mountbatten', 'rommel', 'sugden', 'rommels'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_20
  WTF: {'conservative', 'john', 'sir', 'crisis', '1939', 'lord', 'foot', 'cabinet', 'parliament'} {'british', 'canada', 'disraeli', 'canadian', 'riel', 'attlee', 'macdonald', 'holt', 'tupper'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_21
  WTF: {'isbn', 'woman', 'poems', 'short', 'spark', 'stories', 'books', 'introduction', 'life', 'family', 'fiction', 'story', 'works', 'letters', 'press', 'women'} {'seymour', 'charlotte', 'shelleys', 'christie', 'shelley', 'anne', 'bronts', 'godwin', 'jane', 'austens', 'austen', 'tomalin', 'bront', 'wollstonecraft', 'mary', 'percy'}
  WTF?!?!? 16
  WTF?!?!? 16
topic_22
  WTF: {'observatory', 'scientific', 'geometry', 'algebraic', 'planetary', 'academy', 'theorem', 'university', 'published', 'light', 'tables', 'observations'} {'tycho', 'kepler', 'grothendieck', 'eulers', 'abel', 'euler', 'caspar', 'rmer', 'napier', 'johannes', 'keplers', 'celsius'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_23
  WTF: {'isbn', 'kingdom', 'prophecy', 'ed', 'pp', 'chronicle', 'iii', 'isles', 'kingship', 'ii', 'death', 'died', 'english', 'saga', 'killed'} {'macbeth', 'selkirk', 'coluim', 'scots', 'kenneth', 'oram', 'alexander', 'scotland', 'maclaurin', 'mel', 'alba', 'malcolm', 'duncan', 'malcolms', 'scottish'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_24
  WTF: {'poets', 'illustrations', 'ed', 'english', 'literature', 'published', 'works', 'letters', 'nonsense', 'verse', 'lines'} {'london', 'severn', 'masefield', 'lear', 'nash', 'keats', 'housmans', 'shropshire', 'hopkinss', 'hopkins', 'housman'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_25
  WTF: {'systems', 'die', 'reason', 'zur', 'ed', 'society', 'trans', 'objects', 'psychology', 'phenomenology'} {'luhmann', 'husserl', 'schwitters', 'husserls', 'ebbinghaus', 'berlin', 'habermas', 'schumpeter', 'fichte', 'frankfurt'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_26
  WTF: {'paintings', 'short', 'collection', 'award', 'christian', 'work', 'life', 'polar', 'little', 'works', '2005', 'scream', 'new', 'art'} {'alvar', 'nansen', 'kafkas', 'ibsen', 'eggum', 'munch', 'kafka', 'leiber', 'fafhrd', 'aalto', 'prideaux', 'andersen', 'mouser', 'munchs'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_27

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7fd2d2134520>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7fd2d1a9c3d0>}
{'perplexity': 314195.6875, 'coherence_20': 0.7856933999335637, 'diversity_euclidean': 0.03275048022935808, 'diversity_jensenshannon': 0.6537909991569505, 'diversity_hellinger': 0.7673230187712501, 'diversity_cosine': 0.7303077805982927, 'fair_ppl_free': 2775.820068359375, 'fair_ppl_fix': 316803.46875, 'unfair_ppl_banklike': 314195.6875}
{'num_topics': 51, 'num_common_words': 65750, 'num_model_words': 155407, 'num_bt_words': 135939, 'top_diffs': [{'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 32, 'lost_bt': 16, 'lost_model': 16}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}]}
13
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
  WTF: {'academy', 'american', 'career', '2008'} {'hitchcock', 'paul', 'robeson', 'cagney'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_1
  WTF: {'renaissance', 'san', 'father', 'cardinal', 'life', 'del', 'st', 'il', 'church', 'new'} {'francis', 'caravaggio', 'calvino', 'florence', 'rome', 'borgia', 'lucrezia', 'marco', 'fellini', 'bruno'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_2
  WTF: {'recording', 'single'} {'elvis', 'presley'}
topic_3
  WTF: {'dio', 'greek', 'emperors', 'caesars', 'life', 'ce', 'gibbon', 'senate', 'ad', 'death', 'ancient', 'caesar', 'imperial'} {'augustus', 'rome', 'barnes', 'julian', 'eusebius', 'constantius', 'claudius', 'caligula', 'tiberius', 'hadrian', 'diocletian', 'tacitus', 'suetonius'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_4
  WTF: {'war', 'married', 'daughter', 'otto', 'polish', 'prince', 'emperor', 'von', 'died', 'death', 'maternal', 'brother', 'paternal'} {'mieszko', 'poland', 'hungary', 'prussia', 'albert', 'bismarck', 'brandenburg', 'prussian', 'saxony', 'frederick', 'casimir', 'maria', 'mindaugas'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_5
  WTF: {'machine', 'project', 'information', 'language', 'work', 'institute', 'operating', 'interview', 'award'} {'shannon', 'minsky', 'sanger', 'turing', 'engelbart', 'warwick', 'babbage', 'zuse', 'wikipedia'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_6
  WTF: {'army', 'chess', 'military', 'film', 'committee', 'state', 'time', 'world', 'life', 'revolution', 'government', 'ii', 'order', 'new'} {'russian', 'philby', 'moscow', 'trotsky', 'alexander', 'nicholas', 'stalin', 'chekhov', 'beria', 'gorbachev', 'tito', 'kasparov', 'yeltsin', 'russia'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_7
  WTF: {'die', 'jews', 'reason', 'world', 'press', 'party', 'von', 'social', 'logic', 'nazis', 'und', 'minister', 'phenomenology'} {'waldheim', 'germany', 'reich', 'husserl', 'schwitters', 'goebbels', 'hesse', 'gring', 'berlin', 'habermas', 'hitlers', 'hitler', 'nazi'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_8
  WTF: {'english', 'world', 'best', 'mars'} {'steinbeck', 'crichton', 'verne', 'sagan'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_9
  WTF: {'du', 'psychoanalysis', 'desire', 'perception', 'time', 'work', 'life', 'des', 'political', 'published', 'press', 'new'} {'flaubert', 'sartre', 'nostradamus', 'paris', 'lacan', 'rousseau', 'satie', 'rousseaus', 'merleauponty', 'sade', 'baudelaire', 'deleuze'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_10
  WTF: {'army', 'city', 'medicine', 'sn', 'time', 'forces', 'ali', 'said', 'muslims', 'history', 'caliph', 'nadir', 'government', 'aga'} {'afghan', 'afghanistan', 'persian', 'abd', 'rumi', 'arrahman', 'islamic', 'kabul', 'avicenna', 'jahangir', 'muhammad', 'abu', 'massoud', 'ahmad'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_11
  WTF: {'grand', 'career', 'championship', 'lost', 'wickets', 'world'} {'jordan', 'earnhardt', 'agassi', 'muralitharan', 'schumacher', 'hingis'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_12
  WTF: {'surgeon', 'nobel', 'world', 'theory', 'stress', 'vaccination', 'discovery', 'physician'} {'fleming', 'koch', 'pasteur', 'carrel', 'lister', 'jenner', 'edinburgh', 'hutton'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_13
  WTF: {'musical', 'string', 'words', 'concerto', 'quartet', 'der', 'da'} {'elgar', 'wk', 'handel', 'shostakovich', 'hoffmann', 'vienna', 'haydn'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_14
  WTF: {'war', 'empereurs', 'senso', 'japon', 'lady', 'clan', 'month', 'emperors', 'son', 'throne', 'court'} {'chinese', 'minamoto', 'nichiren', 'chiang', 'fujiwara', 'titsingh', 'kaishek', 'japanese', 'japan', 'deng', 'varley'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_15
  WTF: {'war', 'american', 'cavalry', 'pp', 'supreme', 'union', 'justice', 'new'} {'virginia', 'carson', 'stuart', 'quayle', 'hancock', 'davis', 'peltier', 'thomas'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_16
  WTF: {'cit', 'cartoonist', 'years', 'later', 'work', 'life', 'published', 'poetry', 'al', 'new', 'poem', 'art'} {'tintin', 'thurber', 'abner', 'capp', 'dodgson', 'kirby', 'keats', 'herg', 'lil', 'carroll', 'housman', 'capps'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_17
  WTF: {'married', 'grand', 'turkey', 'reign', 'son', 'battle', 'pasha', 'prince', 'issue', 'valide', 'shah', 'followers', '1986', 'princess'} {'istanbul', 'turkish', 'meher', 'kalchuri', 'bayezid', 'mehmed', 'osman', 'abdulbah', 'aurangzeb', 'remey', 'murad', 'efendi', 'hh', 'aurangzebs'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_18
  WTF: {'allied', 'john', 'voyage', 'admiral', 'attack', 'ships', 'navy', 'lord', 'royal'} {'british', 'drake', 'nelson', 'wellington', 'jay', 'montgomery', 'mountbatten', 'rommel', 'rommels'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_19
  WTF: {'paint', 'sculpture', 'painters', 'giger', 'millet', 'salon', 'artists', 'museum'} {'pissarro', 'rodin', 'paris', 'davids', 'rodins', 'monet', 'david', 'goya'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_20
  WTF: {'woman', 'short', 'stories', 'books', 'introduction', 'wrote', 'family', 'life', 'story', 'fiction', 'university', 'works', 'letters', 'press', 'women'} {'seymour', 'charlotte', 'shelleys', 'hawthorne', 'shelley', 'anne', 'bronts', 'godwin', 'jane', 'austens', 'austen', 'tomalin', 'wollstonecraft', 'mary', 'percy'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_21
  WTF: {'war', 'expedition', 'conquest', 'king', 'city', 'left', 'married', 'voyage', 'time', 'issue', 'islands', 'south', 'men', 'governor', 'new'} {'madero', 'alfonso', 'ortega', 'almagro', 'magellan', 'columbus', 'xavier', 'corts', 'cid', 'daz', 'madrid', 'francisco', 'franco', 'mexico', 'moctezuma'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_22
  WTF: {'conservative', 'parliament', 'john', 'sir', 'crisis', 'foot', 'brown', 'cabinet', '1939'} {'british', 'canada', 'disraeli', 'canadian', 'riel', 'attlee', 'macdonald', 'holt', 'tupper'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_23
  WTF: {'greek', 'tours', 'book', 'testament', 'writings', 'catholic', 'bishop', 'apostles', 'roman', 'chapter', 'god', 'heresies'} {'chrysostom', 'athanasius', 'anthony', 'luke', 'jesus', 'josephus', 'barnabas', 'irenaeus', 'ephrem', 'alexandria', 'mary', 'martin'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_24
  WTF: {'uranium', 'scientific', 'work', 'science', 'theory', 'physicist', 'institute', 'mechanics', 'research'} {'bohr', 'meitner', 'fermi', 'mullis', 'enrico', 'planck', 'schrdinger', 'marie', 'wigner'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_25
  WTF: {'comics', 'paintings', 'short', 'collection', 'christian', 'hans', 'work', 'life', 'little', '2005', 'don', 'award', 'new', 'art'} {'alvar', 'nansen', 'kafkas', 'ibsen', 'eggum', 'munch', 'kafka', 'leiber', 'fafhrd', 'aalto', 'prideaux', 'andersen', 'mouser', 'munchs'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_26
  WTF: {'isbn', 'kingdom', 'prophecy', 'ed', 'pp', 'chronicle', 'iii', 'isles', 'kingship', 'ii', 'death', 'died', 'english', 'saga', 'killed'} {'macbeth', 'selkirk', 'coluim', 'scots', 'kenneth', 'oram', 'alexander', 'scotland', 'maclaurin', 'mel', 'alba', 'malcolm', 'duncan', 'malcolms', 'scottish'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_27
  WTF: {'observatory', 'relativity', 'paper', 'work', 'science', 'mathematician', 'planetary', 'university', 'published', 'mathematical', 'observations'} {'tycho', 'kepler', 'eulers', 'einsteins', 'euler', 'caspar', 'albert', 'rmer', 'johannes', 'keplers', 'celsius'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_28
  WTF: {'succession', 'reign', 'vii', 'earl', 'council', 'protestant', 'throne', 'duke', 'marriage', 'ii', 'death', 'kings', 'royal'} {'england', 'elizabeth', 'anne', 'wales', 'edward', 'owain', 'henrys', 'henry', 'charles', 'catherine', 'tudor', 'elizabeths', 'mary'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_29
  WTF: {'genome', 'behavior', 'carl', 'self', 'evolution', 'environmentalist', 'scientists', 'research', 'chapter'} {'rogers', 'wilson', 'kikuyu', 'rushton', 'venter', 'leakey', 'lomborg', 'louis', 'jensen'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_30
  WTF: {'pope', 'spain', 'tours', 'great', 'son', 'empire', 'duc', 'roman', 'duke', 'spanish', 'death', 'imperial'} {'einhard', 'martel', 'france', 'italy', 'eugene', 'eugenes', 'europe', 'savoy', 'charlemagne', 'frankish', 'charles', 'louis'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_31
  WTF: {'landing', 'war', 'lunar', 'military', 'commander', 'powers', 'served', 'medal', 'president'} {'eisenhowers', 'eisenhower', 'dwight', 'apollo', 'jones', 'hopper', 'armstrong', 'hansen', 'yeager'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_32
  WTF: {'harbor', 'battle', 'pearl', 'aircraft', 'samurai', 'born', 'navy', 'carrier', 'american', 'pacific'} {'akira', 'takeuchi', 'japanese', 'yamamoto', 'kurosawa', 'morita', 'kurosawas', 'japan', 'yamamotos', 'ueshiba'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_33
  WTF: {'speller', 'school', 'christian', 'children', 'witch', 'bible', 'concord', 'company', 'college', 'church', 'spelling', 'interchangeable'} {'yale', 'abbott', 'alcott', 'noah', 'madras', 'connecticut', 'eli', 'mather', 'websters', 'mathers', 'whitney', 'webster'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_34
  WTF: {'inventions', 'wireless', 'work', 'energy', 'field', 'current', 'devices', 'light', 'royal', 'radio'} {'humphry', 'davys', 'volta', 'leon', 'oliver', 'davy', 'faradays', 'faraday', 'heaviside', 'nikola'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_35
  WTF: {'collected', 'joy', 'world', 'books', 'weird', 'fiction', 'monthly', 'poetry', 'literary', 'writing', 'new', 'novel'} {'lewiss', 'amis', 'melville', 'lewis', 'melvilles', 'conrad', 'williams', 'dickenss', 'conrads', 'dickens', 'charles', 'derleth'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_36
  WTF: {'hijackers', 'united', 'detainees', 'department', 'waterboarding', 'flight', 'news', 'states', 'officials', 'report'} {'osama', 'saudi', 'cia', 'qaeda', 'zubaydahs', 'alqaeda', 'fbi', 'zubaydah', 'hanjour', 'abu'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_37
  WTF: {'park', 'designs', 'architectural', 'residential', 'center', 'tower', 'houses', 'new'} {'chihuly', 'wright', 'lloyd', 'lin', 'wrights', 'pei', 'chicago', 'mies'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_38
  WTF: {'operas', 'dargento', 'album', 'composers', 'dal', 'al', 'works', 'award', 'score'} {'paris', 'rossini', 'morricone', 'ennio', 'rossinis', 'premio', 'morricones', 'gioachino', 'bologna'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_39
  WTF: {'freedom', 'economists', 'education', 'banking', 'theory', 'economist', 'policy', 'psychology', 'research', 'democracy', 'philosophy'} {'dewey', 'rothbard', 'hayek', 'mises', 'deweys', 'murray', 'friedman', 'drexel', 'milken', 'tobin', 'hayeks'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_40
  WTF: {'investiture', 'king', 'mission', 'philosophersaint', 'anglosaxon', 'abbey', '279306', 'bishop', 'magick', 'works', 'english', 'historia'} {'bedes', 'anselm', 'bede', 'canterbury', 'aleister', 'dunstan', 'augustine', 'vaughn', 'crowley', 'crowleys', 'anselms', 'sutin'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_41
  WTF: {'hot', 'pg', 'release', 'number', 'rb', 'singles', 'pop'} {'uk', 'mariah', 'careys', 'aaliyah', 'carey', 'enya', 'difranco'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_42
  WTF: {'daughter', 'navigator', 'coast', 'prince', 'mother', 'iii', 'ii', 'expeditions', 'infanta', 'infante'} {'afonso', 'len', 'albuquerque', 'castile', 'portuguese', 'sancho', 'henry', 'portugal', 'aragon', 'coimbra'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_43
  WTF: {'greek', 'minor', 'married', 'daughter', 'crusade', 'emperors', 'son', 'fleet', 'crusaders', '1204', 'coemperor', 'iv', '1183', '1180'} {'nikephoros', 'constantinople', 'komnenos', 'thrace', 'byzantine', 'isaac', 'komnene', 'doukas', 'anna', 'andronikos', 'kanaris', 'maria', 'alexios', 'manuel'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_44
  WTF: {'bureau', 'relationship', 'sexual', 'office', 'primary', 'vote', 'election', 'march', 'bomb', 'general', 'sentence', 'plea', 'parole', 'prison', 'gray', 'new'} {'sacramento', 'hoover', 'soliah', 'california', 'lewinsky', 'olson', 'eastman', 'sla', 'hoovers', 'sara', 'heather', 'clinton', 'fbi', 'fargo', 'reno', 'gandy'}
  WTF?!?!? 16
  WTF?!?!? 16
topic_45
  WTF: {'signs', 'induction', 'inquiry', 'interpretant', 'knowledge', 'pragmatism', 'sense', 'method'} {'bertrand', 'poppers', 'russell', 'russells', 'peirce', 'peirces', 'popper', 'moore'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_46
  WTF: {'scientific', 'biology', 'science', 'origin', 'society', 'theory', 'animals', 'principles', 'history', 'geological', 'vol'} {'slotten', 'mayr', 'haeckel', 'darwin', 'lyell', 'ernst', 'charles', 'wallace', 'wallaces', 'lyells', 'darwins'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_47
  WTF: {'sounds', 'languages', 'linguists', 'honeybees', 'speech'} {'hockett', 'whorf', 'jones', 'jespersen', 'halliday'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_48
  WTF: {'conservative', 'theological', 'study', 'law', 'theology', 'prophets', 'work', 'university', 'rabbis', 'man', 'sabbath', 'studies', 'scholars'} {'heschel', 'jts', 'steinsaltz', 'hebrew', 'jewish', 'neusner', 'kushner', 'judaism', 'kaplans', 'neusners', 'talmud', 'torah', 'kaplan'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_49
  WTF: {'commissioner', 'career', 'allstar', 'tigers', 'hit', 'pitched', 'american'} {'youngs', 'greenberg', 'milwaukee', 'knute', 'mlb', 'rockne', 'cy'}
  WTF?!?!? 7
  WTF?!?!? 7
{'fix': <__main__.FastFixPhiRegularizer object at 0x7fd2d2140280>}
Check after fit:
Skipping background topic: background_1.
topic_0
  WTF: {'academy', 'american', 'career', '2008'} {'hitchcock', 'paul', 'robeson', 'cagney'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_1
  WTF: {'renaissance', 'san', 'father', 'cardinal', 'life', 'del', 'st', 'il', 'church', 'new'} {'francis', 'caravaggio', 'calvino', 'florence', 'rome', 'borgia', 'lucrezia', 'marco', 'fellini', 'bruno'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_2
  WTF: {'recording', 'single'} {'elvis', 'presley'}
topic_3
  WTF: {'dio', 'greek', 'emperors', 'caesars', 'life', 'ce', 'gibbon', 'senate', 'ad', 'death', 'ancient', 'caesar', 'imperial'} {'augustus', 'rome', 'barnes', 'julian', 'eusebius', 'constantius', 'claudius', 'caligula', 'tiberius', 'hadrian', 'diocletian', 'tacitus', 'suetonius'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_4
  WTF: {'war', 'married', 'daughter', 'otto', 'polish', 'prince', 'emperor', 'von', 'died', 'death', 'maternal', 'brother', 'paternal'} {'mieszko', 'poland', 'hungary', 'prussia', 'albert', 'bismarck', 'brandenburg', 'prussian', 'saxony', 'frederick', 'casimir', 'maria', 'mindaugas'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_5
  WTF: {'machine', 'project', 'information', 'language', 'work', 'institute', 'operating', 'interview', 'award'} {'shannon', 'minsky', 'sanger', 'turing', 'engelbart', 'warwick', 'babbage', 'zuse', 'wikipedia'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_6
  WTF: {'army', 'chess', 'military', 'film', 'committee', 'state', 'time', 'world', 'life', 'revolution', 'government', 'ii', 'order', 'new'} {'russian', 'philby', 'moscow', 'trotsky', 'alexander', 'nicholas', 'stalin', 'chekhov', 'beria', 'gorbachev', 'tito', 'kasparov', 'yeltsin', 'russia'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_7
  WTF: {'die', 'jews', 'reason', 'world', 'press', 'party', 'von', 'social', 'logic', 'nazis', 'und', 'minister', 'phenomenology'} {'waldheim', 'germany', 'reich', 'husserl', 'schwitters', 'goebbels', 'hesse', 'gring', 'berlin', 'habermas', 'hitlers', 'hitler', 'nazi'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_8
  WTF: {'english', 'world', 'best', 'mars'} {'steinbeck', 'crichton', 'verne', 'sagan'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_9
  WTF: {'du', 'psychoanalysis', 'desire', 'perception', 'time', 'work', 'life', 'des', 'political', 'published', 'press', 'new'} {'flaubert', 'sartre', 'nostradamus', 'paris', 'lacan', 'rousseau', 'satie', 'rousseaus', 'merleauponty', 'sade', 'baudelaire', 'deleuze'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_10
  WTF: {'army', 'city', 'medicine', 'sn', 'time', 'forces', 'ali', 'said', 'muslims', 'history', 'caliph', 'nadir', 'government', 'aga'} {'afghan', 'afghanistan', 'persian', 'abd', 'rumi', 'arrahman', 'islamic', 'kabul', 'avicenna', 'jahangir', 'muhammad', 'abu', 'massoud', 'ahmad'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_11
  WTF: {'grand', 'career', 'championship', 'lost', 'wickets', 'world'} {'jordan', 'earnhardt', 'agassi', 'muralitharan', 'schumacher', 'hingis'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_12
  WTF: {'surgeon', 'nobel', 'world', 'theory', 'stress', 'vaccination', 'discovery', 'physician'} {'fleming', 'koch', 'pasteur', 'carrel', 'lister', 'jenner', 'edinburgh', 'hutton'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_13
  WTF: {'musical', 'string', 'words', 'concerto', 'quartet', 'der', 'da'} {'elgar', 'wk', 'handel', 'shostakovich', 'hoffmann', 'vienna', 'haydn'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_14
  WTF: {'war', 'empereurs', 'senso', 'japon', 'lady', 'clan', 'month', 'emperors', 'son', 'throne', 'court'} {'chinese', 'minamoto', 'nichiren', 'chiang', 'fujiwara', 'titsingh', 'kaishek', 'japanese', 'japan', 'deng', 'varley'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_15
  WTF: {'war', 'american', 'cavalry', 'pp', 'supreme', 'union', 'justice', 'new'} {'virginia', 'carson', 'stuart', 'quayle', 'hancock', 'davis', 'peltier', 'thomas'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_16
  WTF: {'cit', 'cartoonist', 'years', 'later', 'work', 'life', 'published', 'poetry', 'al', 'new', 'poem', 'art'} {'tintin', 'thurber', 'abner', 'capp', 'dodgson', 'kirby', 'keats', 'herg', 'lil', 'carroll', 'housman', 'capps'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_17
  WTF: {'married', 'grand', 'turkey', 'reign', 'son', 'battle', 'pasha', 'prince', 'issue', 'valide', 'shah', 'followers', '1986', 'princess'} {'istanbul', 'turkish', 'meher', 'kalchuri', 'bayezid', 'mehmed', 'osman', 'abdulbah', 'aurangzeb', 'remey', 'murad', 'efendi', 'hh', 'aurangzebs'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_18
  WTF: {'allied', 'john', 'voyage', 'admiral', 'attack', 'ships', 'navy', 'lord', 'royal'} {'british', 'drake', 'nelson', 'wellington', 'jay', 'montgomery', 'mountbatten', 'rommel', 'rommels'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_19
  WTF: {'paint', 'sculpture', 'painters', 'giger', 'millet', 'salon', 'artists', 'museum'} {'pissarro', 'rodin', 'paris', 'davids', 'rodins', 'monet', 'david', 'goya'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_20
  WTF: {'woman', 'short', 'stories', 'books', 'introduction', 'wrote', 'family', 'life', 'story', 'fiction', 'university', 'works', 'letters', 'press', 'women'} {'seymour', 'charlotte', 'shelleys', 'hawthorne', 'shelley', 'anne', 'bronts', 'godwin', 'jane', 'austens', 'austen', 'tomalin', 'wollstonecraft', 'mary', 'percy'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_21
  WTF: {'war', 'expedition', 'conquest', 'king', 'city', 'left', 'married', 'voyage', 'time', 'issue', 'islands', 'south', 'men', 'governor', 'new'} {'madero', 'alfonso', 'ortega', 'almagro', 'magellan', 'columbus', 'xavier', 'corts', 'cid', 'daz', 'madrid', 'francisco', 'franco', 'mexico', 'moctezuma'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_22
  WTF: {'conservative', 'parliament', 'john', 'sir', 'crisis', 'foot', 'brown', 'cabinet', '1939'} {'british', 'canada', 'disraeli', 'canadian', 'riel', 'attlee', 'macdonald', 'holt', 'tupper'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_23
  WTF: {'greek', 'tours', 'book', 'testament', 'writings', 'catholic', 'bishop', 'apostles', 'roman', 'chapter', 'god', 'heresies'} {'chrysostom', 'athanasius', 'anthony', 'luke', 'jesus', 'josephus', 'barnabas', 'irenaeus', 'ephrem', 'alexandria', 'mary', 'martin'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_24
  WTF: {'uranium', 'scientific', 'work', 'science', 'theory', 'physicist', 'institute', 'mechanics', 'research'} {'bohr', 'meitner', 'fermi', 'mullis', 'enrico', 'planck', 'schrdinger', 'marie', 'wigner'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_25
  WTF: {'comics', 'paintings', 'short', 'collection', 'christian', 'hans', 'work', 'life', 'little', '2005', 'don', 'award', 'new', 'art'} {'alvar', 'nansen', 'kafkas', 'ibsen', 'eggum', 'munch', 'kafka', 'leiber', 'fafhrd', 'aalto', 'prideaux', 'andersen', 'mouser', 'munchs'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_26

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7fd2c2010730>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7fd2d213d520>}
{'perplexity': 348776.21875, 'coherence_20': 0.7918963973797604, 'diversity_euclidean': 0.0344087764902775, 'diversity_jensenshannon': 0.6533666891077207, 'diversity_hellinger': 0.7666539601022628, 'diversity_cosine': 0.7416906738563741, 'fair_ppl_free': 2766.23876953125, 'fair_ppl_fix': 344202.71875, 'unfair_ppl_banklike': 348776.21875}
{'num_topics': 51, 'num_common_words': 65750, 'num_model_words': 155407, 'num_bt_words': 135939, 'top_diffs': [{'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 32, 'lost_bt': 16, 'lost_model': 16}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}]}
14
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
  WTF: {'academy', 'american', 'episode', '2008'} {'hitchcock', 'paul', 'robeson', 'cagney'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_1
  WTF: {'dio', 'john', 'new', 'senate', 'ad', 'saint', 'st', 'death', 'caesar', 'god'} {'augustus', 'rome', 'barnes', 'elijah', 'eusebius', 'claudius', 'caligula', 'diocletian', 'tacitus', 'suetonius'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_2
  WTF: {'recording', 'single'} {'elvis', 'presley'}
topic_3
  WTF: {'machine', 'information', 'language', 'work', 'program', 'institute', 'operating', 'interview', 'award'} {'shannon', 'minsky', 'sanger', 'turing', 'engelbart', 'warwick', 'babbage', 'zuse', 'wikipedia'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_4
  WTF: {'pope', 'della', 'film', 'marble', 'san', 'work', 'life', 'painting', 'title', 'del', 'il', 'new'} {'giordano', 'caravaggios', 'caravaggio', 'florence', 'rome', 'medici', 'lucrezia', 'borgia', 'angelico', 'fellini', 'bruno', 'lorenzo'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_5
  WTF: {'army', 'jews', 'state', 'work', 'party', 'theory', 'political', 'von', 'logic', 'published', 'history', 'social', 'und', 'phenomenology'} {'germany', 'mccarthy', 'husserl', 'schwitters', 'reich', 'goebbels', 'hegel', 'hesse', 'gring', 'berlin', 'hegels', 'habermas', 'hitler', 'nazi'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_6
  WTF: {'war', 'army', 'chess', 'military', 'film', 'committee', 'state', 'time', 'world', 'revolution', 'government', 'march', 'ii', 'order', 'new'} {'russian', 'moscow', 'trotsky', 'khmelnytsky', 'alexander', 'nicholas', 'stalin', 'chekhov', 'beria', 'gorbachev', 'sakharov', 'tito', 'kasparov', 'yeltsin', 'russia'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_7
  WTF: {'professor', 'scientific', 'chemical', 'work', 'quantum', 'institute', 'scientists', 'research'} {'bohr', 'meitner', 'fermi', 'mullis', 'planck', 'fuchs', 'marie', 'hoyle'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_8
  WTF: {'biography', 'poems', 'short', 'books', 'wrote', 'family', 'fiction', 'story', 'university', 'writing', 'press'} {'shelleys', 'tolkien', 'lewis', 'shelley', 'anne', 'jane', 'austen', 'dickens', 'wollstonecraft', 'mary', 'percy'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_9
  WTF: {'string', 'words', 'quartet', 'composers', 'works', 'trio', 'da'} {'elgar', 'wk', 'handel', 'shostakovich', 'hoffmann', 'lugosi', 'haydn'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_10
  WTF: {'world', 'english', 'books', 'mars'} {'steinbeck', 'crichton', 'verne', 'moorcock'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_11
  WTF: {'psychoanalysis', 'desire', 'perception', 'time', 'work', 'life', 'des', 'political', 'published', 'press', 'new'} {'sartre', 'nostradamus', 'paris', 'lacan', 'rousseau', 'satie', 'rousseaus', 'merleauponty', 'sade', 'baudelaire', 'deleuze'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_12
  WTF: {'grand', 'career', 'championship', 'lost', 'wickets', 'world'} {'jordan', 'earnhardt', 'agassi', 'muralitharan', 'schumacher', 'hingis'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_13
  WTF: {'army', 'son', 'medicine', 'sn', 'forces', 'time', 'ali', 'empire', 'muslims', 'history', 'caliph', 'nadir', 'government', 'aga'} {'afghan', 'afghanistan', 'persian', 'abd', 'rumi', 'arrahman', 'islamic', 'avicenna', 'jahangir', 'aurangzeb', 'muhammad', 'abu', 'massoud', 'ahmad'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_14
  WTF: {'war', 'married', 'army', 'daughter', 'chancellor', 'son', 'margrave', 'prince', 'emperor', 'von', 'iii', 'ii', 'died', 'paternal'} {'germany', 'austria', 'gustavus', 'joachim', 'prussia', 'albert', 'albertus', 'bismarck', 'bismarcks', 'prussian', 'brandenburg', 'saxony', 'frederick', 'dresden'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_15
  WTF: {'surgeon', 'nobel', 'world', 'theory', 'stress', 'vaccination', 'discovery', 'physician'} {'fleming', 'koch', 'pasteur', 'carrel', 'lister', 'jenner', 'edinburgh', 'hutton'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_16
  WTF: {'war', 'empereurs', 'senso', 'japon', 'lady', 'clan', 'month', 'emperors', 'son', 'throne', 'court'} {'chinese', 'minamoto', 'fujiwara', 'chiang', 'titsingh', 'kaishek', 'japanese', 'japan', 'dengs', 'deng', 'varley'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_17
  WTF: {'war', 'american', 'congress', 'union', 'justice', 'new'} {'virginia', 'jay', 'stuart', 'hancock', 'davis', 'thomas'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_18
  WTF: {'married', 'grand', 'turkey', 'son', 'spiritual', 'battle', 'pasha', 'prince', 'issue', 'valide', 'followers', '1986', 'god', 'princess'} {'istanbul', 'turkish', 'meher', 'hatun', 'kalchuri', 'bayezid', 'mehmed', 'osman', 'bah', 'remey', 'murad', 'efendi', 'hh', 'abdulbah'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_19
  WTF: {'medium', 'painters', 'french', 'giger', 'millet', 'works', 'museum'} {'pissarro', 'rodin', 'paris', 'davids', 'rodins', 'monet', 'david'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_20
  WTF: {'war', 'expedition', 'civil', 'king', 'city', 'military', 'married', 'la', 'issue', 'doa', 'president', 'troops', 'leader', 'government', 'new'} {'madero', 'alfonso', 'ortega', 'almagro', 'xavier', 'corts', 'cid', 'aztec', 'pizarro', 'daz', 'francisco', 'madrid', 'franco', 'mexico', 'moctezuma'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_21
  WTF: {'war', 'voyage', '2004', 'forces', 'admiral', 'ship', 'navy', 'general', 'lord', 'spanish', 'royal'} {'british', 'drake', 'nelson', 'wellington', 'alexander', 'hibbert', 'montgomery', 'india', 'mountbatten', 'blackbeard', 'sugden'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_22
  WTF: {'conservative', 'sir', '1939', 'begin', 'political', 'lord', 'foot', 'cabinet', 'parliament'} {'british', 'canada', 'disraeli', 'canadian', 'riel', 'attlee', 'macdonald', 'holt', 'tupper'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_23
  WTF: {'roman', 'army', 'great', 'tours', 'son', 'empire', 'iii', 'ii', 'death', 'duke', 'spanish', 'imperial'} {'martel', 'france', 'italy', 'eugene', 'europe', 'attila', 'savoy', 'charlemagne', 'frankish', 'charles', 'louis', 'bernard'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_24
  WTF: {'war', 'harbor', 'moon', 'film', 'admiral', 'pearl', 'oneshot', 'samurai', 'born', 'american', 'midway', 'dragon', 'pacific'} {'tokyo', 'nichiren', 'akira', 'japanese', 'hearn', 'yamamoto', 'kurosawa', 'lafcadio', 'fukuyama', 'morita', 'japan', 'yamamotos', 'ueshiba'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_25
  WTF: {'book', 'wake', 'ed', 'work', 'life', 'press', 'university', 'published', 'donnes', 'poet', 'works', 'lad', 'english'} {'london', 'severn', 'masefield', 'ulysses', 'joyce', 'nash', 'housman', 'keats', 'hopkins', 'shropshire', 'joyces', 'james', 'dublin'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_26
  WTF: {'observatory', 'scientific', 'algebraic', 'geometry', 'planetary', 'academy', 'theorem', 'university', 'light', 'tables'} {'tycho', 'kepler', 'grothendieck', 'eulers', 'euler', 'caspar', 'rmer', 'johannes', 'keplers', 'celsius'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_27
  WTF: {'isbn', 'kingdom', 'prophecy', 'ed', 'pp', 'chronicle', 'iii', 'isles', 'ii', 'death', 'died', 'english', 'saga', 'killed'} {'macbeth', 'selkirk', 'coluim', 'scots', 'kenneth', 'oram', 'alexander', 'scotland', 'mel', 'alba', 'malcolm', 'duncan', 'malcolms', 'scottish'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_28
  WTF: {'trial', 'isbn', 'dictionary', 'reflections', 'pp', 'trials', 'gin', 'fox', 'life', 'children', 'haven', 'published', 'prior', 'press', 'church'} {'yale', 'abbott', 'mead', 'alcott', 'burke', 'bellamy', 'noah', 'connecticut', 'eli', 'mather', 'mathers', 'margaret', 'whitney', 'burkes', 'webster'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_29
  WTF: {'succession', 'reign', 'vii', 'earl', 'council', 'protestant', 'throne', 'duke', 'marriage', 'ii', 'death', 'kings', 'royal'} {'england', 'elizabeth', 'anne', 'wales', 'edward', 'owain', 'henrys', 'henry', 'charles', 'catherine', 'tudor', 'elizabeths', 'mary'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_30
  WTF: {'expedition', 'arctic', 'museum', 'actress', 'film', 'new', 'work', 'best', 'life', 'play', 'works', '2005', 'award', 'scream', 'frieze', 'art'} {'alvar', 'nansen', 'ibsen', 'norway', 'finland', 'edvard', 'ullmann', 'eggum', 'munch', 'helsinki', 'fridtjof', 'rasmussen', 'aalto', 'prideaux', 'thule', 'munchs'}
  WTF?!?!? 16
  WTF?!?!? 16
topic_31
  WTF: {'wolf', 'pietro', 'father', 'italian', 'feast', 'judges', 'roman', 'order', 'ibid', 'new', 'god'} {'polidori', 'francis', 'alberoni', 'bellarmine', 'rome', 'mychal', 'contarini', 'assisi', 'porziuncola', 'cardano', 'vampyre'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_32
  WTF: {'book', 'cartoonists', 'beat', 'work', 'life', 'road', 'award', 'characters', 'new'} {'thurber', 'abner', 'capp', 'barney', 'simon', 'kerouacs', 'kirby', 'lil', 'capps'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_33
  WTF: {'hijackers', 'united', 'detainees', 'department', 'waterboarding', 'flight', 'news', 'torture', 'states', 'officials'} {'osama', 'saudi', 'cia', 'qaeda', 'zubaydahs', 'alqaeda', 'fbi', 'zubaydah', 'hanjour', 'abu'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_34
  WTF: {'scientists', 'genome', 'behavior', 'self', 'evolution', 'environmentalist', 'carl', 'research', 'chapter'} {'rogers', 'wilson', 'kikuyu', 'rushton', 'venter', 'leakey', 'lomborg', 'louis', 'jensen'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_35
  WTF: {'inventions', 'wireless', 'work', 'energy', 'field', 'current', 'devices', 'light', 'royal', 'radio'} {'humphry', 'davys', 'volta', 'leon', 'oliver', 'davy', 'faradays', 'faraday', 'heaviside', 'nikola'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_36
  WTF: {'signs', 'induction', 'inquiry', 'interpretant', 'knowledge', 'pragmatism', 'sense', 'method'} {'bertrand', 'poppers', 'russell', 'russells', 'peirce', 'peirces', 'popper', 'moore'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_37
  WTF: {'married', 'grand', 'ca', 'daughter', 'cathedral', 'family', 'queen', 'sister', 'sons', 'ii', 'death', 'died', 'iv', 'lands'} {'mieszko', 'bolesaw', 'jadwiga', 'poland', 'feodorovna', 'lithuania', 'hungary', 'krakw', 'kazimierz', 'lithuanian', 'casimir', 'maria', 'mindaugas', 'jadwigas'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_38
  WTF: {'reinforcement', 'education', 'banking', 'economist', 'economy', 'money', 'free', 'government', 'rent', 'philosophy'} {'ricardo', 'dewey', 'skinner', 'rothbard', 'hayek', 'deweys', 'murray', 'skinners', 'friedman', 'hayeks'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_39
  WTF: {'flew', 'flying', '11', 'navy', 'states', 'service', 'mach', 'crew'} {'apollo', 'jones', 'bingham', 'aldrin', 'hopper', 'armstrong', 'hansen', 'yeager'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_40
  WTF: {'rpt', 'description', 'humans', 'grammar', 'sounds', 'linguists', 'english'} {'hockett', 'whorf', 'jones', 'bantu', 'westermann', 'doke', 'diedrich'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_41
  WTF: {'scientific', 'biology', 'ray', 'science', 'society', 'theory', 'animals', 'principles', 'origin', 'history', 'geological', 'vol'} {'slotten', 'london', 'mayr', 'haeckel', 'darwin', 'lyell', 'ernst', 'charles', 'wallace', 'wallaces', 'lyells', 'darwins'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_42
  WTF: {'hot', 'pg', 'release', 'number', 'rb', 'singles', 'pop'} {'uk', 'mariah', 'careys', 'aaliyah', 'carey', 'enya', 'difranco'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_43
  WTF: {'daughter', 'navigator', 'coast', 'prince', 'mother', 'iii', 'ii', 'expeditions', 'infanta', 'infante'} {'afonso', 'len', 'albuquerque', 'castile', 'portuguese', 'sancho', 'henry', 'portugal', 'aragon', 'coimbra'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_44
  WTF: {'minor', 'theological', 'study', 'religion', 'theology', 'religious', 'work', 'life', 'civilization', 'prelude', 'university', 'rabbinical', 'man', 'vol', 'philosophy'} {'heschel', 'steinsaltz', 'hebrew', 'jesus', 'jewish', 'albert', 'judaism', 'neusners', 'talmud', 'schweitzer', 'schweitzers', 'torah', 'neusner', 'kaplan', 'lambarn'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_45
  WTF: {'players', 'hall', 'allstar', 'tigers', 'hit', 'pitched', 'american'} {'youngs', 'greenberg', 'milwaukee', 'mlb', 'rockne', 'cy', 'doubleday'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_46
  WTF: {'investiture', 'king', 'mission', 'philosophersaint', 'anglosaxon', 'abbey', '279306', 'bishop', 'magick', 'works', 'english', 'historia'} {'bedes', 'anselm', 'bede', 'canterbury', 'aleister', 'dunstan', 'augustine', 'vaughn', 'crowley', 'crowleys', 'anselms', 'sutin'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_47
  WTF: {'operas', 'dargento', 'composers', 'concert', 'dal', 'doro', 'al', 'award', 'score'} {'paris', 'rossini', 'morricone', 'ennio', 'rossinis', 'premio', 'morricones', 'gioachino', 'bologna'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_48
  WTF: {'shows', 'featured', 'film', 'lyrics', 'minutes', 'wrote', 'popular', 'composer', 'golf', 'musicals', 'radio'} {'elfman', 'ira', 'broadway', 'kern', 'dowland', 'crosby', 'crosbys', 'gershwin', 'dowlands', 'burton', 'bing'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_49
  WTF: {'book', 'city', 'consistory', 'churches', 'collge', 'teachings', 'ministers', 'family', 'synod', 'dynasty', 'religious'} {'servetus', 'chinese', 'confucianism', 'dupuis', 'confucian', 'amyraut', 'geneva', 'confucius', 'calvin', 'calvins', 'confuciuss'}
  WTF?!?!? 11
  WTF?!?!? 11
{'fix': <__main__.FastFixPhiRegularizer object at 0x7fd2d1b428e0>}
Check after fit:
Skipping background topic: background_1.
topic_0
  WTF: {'academy', 'american', 'episode', '2008'} {'hitchcock', 'paul', 'robeson', 'cagney'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_1
  WTF: {'dio', 'john', 'new', 'senate', 'ad', 'saint', 'st', 'death', 'caesar', 'god'} {'augustus', 'rome', 'barnes', 'elijah', 'eusebius', 'claudius', 'caligula', 'diocletian', 'tacitus', 'suetonius'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_2
  WTF: {'recording', 'single'} {'elvis', 'presley'}
topic_3
  WTF: {'machine', 'information', 'language', 'work', 'program', 'institute', 'operating', 'interview', 'award'} {'shannon', 'minsky', 'sanger', 'turing', 'engelbart', 'warwick', 'babbage', 'zuse', 'wikipedia'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_4
  WTF: {'pope', 'della', 'film', 'marble', 'san', 'work', 'life', 'painting', 'title', 'del', 'il', 'new'} {'giordano', 'caravaggios', 'caravaggio', 'florence', 'rome', 'medici', 'lucrezia', 'borgia', 'angelico', 'fellini', 'bruno', 'lorenzo'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_5
  WTF: {'army', 'jews', 'state', 'work', 'party', 'theory', 'political', 'von', 'logic', 'published', 'history', 'social', 'und', 'phenomenology'} {'germany', 'mccarthy', 'husserl', 'schwitters', 'reich', 'goebbels', 'hegel', 'hesse', 'gring', 'berlin', 'hegels', 'habermas', 'hitler', 'nazi'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_6
  WTF: {'war', 'army', 'chess', 'military', 'film', 'committee', 'state', 'time', 'world', 'revolution', 'government', 'march', 'ii', 'order', 'new'} {'russian', 'moscow', 'trotsky', 'khmelnytsky', 'alexander', 'nicholas', 'stalin', 'chekhov', 'beria', 'gorbachev', 'sakharov', 'tito', 'kasparov', 'yeltsin', 'russia'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_7
  WTF: {'professor', 'scientific', 'chemical', 'work', 'quantum', 'institute', 'scientists', 'research'} {'bohr', 'meitner', 'fermi', 'mullis', 'planck', 'fuchs', 'marie', 'hoyle'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_8
  WTF: {'biography', 'poems', 'short', 'books', 'wrote', 'family', 'fiction', 'story', 'university', 'writing', 'press'} {'shelleys', 'tolkien', 'lewis', 'shelley', 'anne', 'jane', 'austen', 'dickens', 'wollstonecraft', 'mary', 'percy'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_9
  WTF: {'string', 'words', 'quartet', 'composers', 'works', 'trio', 'da'} {'elgar', 'wk', 'handel', 'shostakovich', 'hoffmann', 'lugosi', 'haydn'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_10
  WTF: {'world', 'english', 'books', 'mars'} {'steinbeck', 'crichton', 'verne', 'moorcock'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_11
  WTF: {'psychoanalysis', 'desire', 'perception', 'time', 'work', 'life', 'des', 'political', 'published', 'press', 'new'} {'sartre', 'nostradamus', 'paris', 'lacan', 'rousseau', 'satie', 'rousseaus', 'merleauponty', 'sade', 'baudelaire', 'deleuze'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_12
  WTF: {'grand', 'career', 'championship', 'lost', 'wickets', 'world'} {'jordan', 'earnhardt', 'agassi', 'muralitharan', 'schumacher', 'hingis'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_13
  WTF: {'army', 'son', 'medicine', 'sn', 'forces', 'time', 'ali', 'empire', 'muslims', 'history', 'caliph', 'nadir', 'government', 'aga'} {'afghan', 'afghanistan', 'persian', 'abd', 'rumi', 'arrahman', 'islamic', 'avicenna', 'jahangir', 'aurangzeb', 'muhammad', 'abu', 'massoud', 'ahmad'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_14
  WTF: {'war', 'married', 'army', 'daughter', 'chancellor', 'son', 'margrave', 'prince', 'emperor', 'von', 'iii', 'ii', 'died', 'paternal'} {'germany', 'austria', 'gustavus', 'joachim', 'prussia', 'albert', 'albertus', 'bismarck', 'bismarcks', 'prussian', 'brandenburg', 'saxony', 'frederick', 'dresden'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_15
  WTF: {'surgeon', 'nobel', 'world', 'theory', 'stress', 'vaccination', 'discovery', 'physician'} {'fleming', 'koch', 'pasteur', 'carrel', 'lister', 'jenner', 'edinburgh', 'hutton'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_16
  WTF: {'war', 'empereurs', 'senso', 'japon', 'lady', 'clan', 'month', 'emperors', 'son', 'throne', 'court'} {'chinese', 'minamoto', 'fujiwara', 'chiang', 'titsingh', 'kaishek', 'japanese', 'japan', 'dengs', 'deng', 'varley'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_17
  WTF: {'war', 'american', 'congress', 'union', 'justice', 'new'} {'virginia', 'jay', 'stuart', 'hancock', 'davis', 'thomas'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_18
  WTF: {'married', 'grand', 'turkey', 'son', 'spiritual', 'battle', 'pasha', 'prince', 'issue', 'valide', 'followers', '1986', 'god', 'princess'} {'istanbul', 'turkish', 'meher', 'hatun', 'kalchuri', 'bayezid', 'mehmed', 'osman', 'bah', 'remey', 'murad', 'efendi', 'hh', 'abdulbah'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_19
  WTF: {'medium', 'painters', 'french', 'giger', 'millet', 'works', 'museum'} {'pissarro', 'rodin', 'paris', 'davids', 'rodins', 'monet', 'david'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_20
  WTF: {'war', 'expedition', 'civil', 'king', 'city', 'military', 'married', 'la', 'issue', 'doa', 'president', 'troops', 'leader', 'government', 'new'} {'madero', 'alfonso', 'ortega', 'almagro', 'xavier', 'corts', 'cid', 'aztec', 'pizarro', 'daz', 'francisco', 'madrid', 'franco', 'mexico', 'moctezuma'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_21
  WTF: {'war', 'voyage', '2004', 'forces', 'admiral', 'ship', 'navy', 'general', 'lord', 'spanish', 'royal'} {'british', 'drake', 'nelson', 'wellington', 'alexander', 'hibbert', 'montgomery', 'india', 'mountbatten', 'blackbeard', 'sugden'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_22
  WTF: {'conservative', 'sir', '1939', 'begin', 'political', 'lord', 'foot', 'cabinet', 'parliament'} {'british', 'canada', 'disraeli', 'canadian', 'riel', 'attlee', 'macdonald', 'holt', 'tupper'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_23
  WTF: {'roman', 'army', 'great', 'tours', 'son', 'empire', 'iii', 'ii', 'death', 'duke', 'spanish', 'imperial'} {'martel', 'france', 'italy', 'eugene', 'europe', 'attila', 'savoy', 'charlemagne', 'frankish', 'charles', 'louis', 'bernard'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_24
  WTF: {'war', 'harbor', 'moon', 'film', 'admiral', 'pearl', 'oneshot', 'samurai', 'born', 'american', 'midway', 'dragon', 'pacific'} {'tokyo', 'nichiren', 'akira', 'japanese', 'hearn', 'yamamoto', 'kurosawa', 'lafcadio', 'fukuyama', 'morita', 'japan', 'yamamotos', 'ueshiba'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_25
  WTF: {'book', 'wake', 'ed', 'work', 'life', 'press', 'university', 'published', 'donnes', 'poet', 'works', 'lad', 'english'} {'london', 'severn', 'masefield', 'ulysses', 'joyce', 'nash', 'housman', 'keats', 'hopkins', 'shropshire', 'joyces', 'james', 'dublin'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_26
  WTF: {'observatory', 'scientific', 'algebraic', 'geometry', 'planetary', 'academy', 'theorem', 'university', 'light', 'tables'} {'tycho', 'kepler', 'grothendieck', 'eulers', 'euler', 'caspar', 'rmer', 'johannes', 'keplers', 'celsius'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_27

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7fd2ff181e80>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7fd2c2000520>}
{'perplexity': 327826.28125, 'coherence_20': 0.7751361844900113, 'diversity_euclidean': 0.03345931849675339, 'diversity_jensenshannon': 0.6528692281477372, 'diversity_hellinger': 0.7665255756437577, 'diversity_cosine': 0.7369936085695412, 'fair_ppl_free': 2767.732421875, 'fair_ppl_fix': 423105.21875, 'unfair_ppl_banklike': 327826.28125}
{'num_topics': 51, 'num_common_words': 65750, 'num_model_words': 155407, 'num_bt_words': 135939, 'top_diffs': [{'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 32, 'lost_bt': 16, 'lost_model': 16}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}]}
15
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
  WTF: {'academy', 'episode', 'career', '2008'} {'hitchcock', 'paul', 'robeson', 'cagney'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_1
  WTF: {'interrogation', 'army', '2002', 'ali', 'empire', 'muslims', 'al', 'government', 'new'} {'afghanistan', 'persian', 'abd', 'rumi', 'cia', 'islamic', 'muhammad', 'zubaydah', 'abu'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_2
  WTF: {'renaissance', 'san', 'cardinal', 'life', 'del', 'st', 'il', 'english', 'church', 'new'} {'francis', 'caravaggio', 'calvino', 'florence', 'rome', 'borgia', 'lucrezia', 'marco', 'fellini', 'bruno'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_3
  WTF: {'dio', 'emperors', 'christian', 'caesars', 'life', 'gibbon', 'senate', 'death', 'ancient', 'church', 'caesar', 'imperial'} {'augustus', 'rome', 'barnes', 'julian', 'eusebius', 'constantius', 'claudius', 'caligula', 'tiberius', 'diocletian', 'tacitus', 'suetonius'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_4
  WTF: {'machine', 'project', 'information', 'language', 'work', 'institute', 'operating', 'interview', 'award'} {'shannon', 'minsky', 'sanger', 'turing', 'engelbart', 'warwick', 'babbage', 'zuse', 'wikipedia'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_5
  WTF: {'professor', 'scientific', 'chemical', 'wireless', 'science', 'quantum', 'theory', 'institute', 'research'} {'bohr', 'fermi', 'davy', 'planck', 'faraday', 'marie', 'bardeen', 'heaviside', 'marconi'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_6
  WTF: {'army', 'chess', 'military', 'film', 'committee', 'state', 'time', 'world', 'life', 'revolution', 'government', 'march', 'order', 'new'} {'russian', 'philby', 'moscow', 'trotsky', 'alexander', 'nicholas', 'stalin', 'chekhov', 'beria', 'gorbachev', 'tito', 'kasparov', 'yeltsin', 'russia'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_7
  WTF: {'war', 'psychology', 'state', 'language', 'work', 'party', 'theory', 'political', 'von', 'logic', 'published', 'history', 'social', 'und', 'phenomenology'} {'germany', 'mccarthy', 'husserl', 'schwitters', 'reich', 'goebbels', 'hegel', 'chomsky', 'hesse', 'gring', 'berlin', 'hegels', 'habermas', 'hitler', 'nazi'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_8
  WTF: {'series', 'world', 'books', 'english', 'mars'} {'steinbeck', 'moorcock', 'crichton', 'verne', 'pohl'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_9
  WTF: {'army', 'married', 'daughter', 'military', 'son', 'margrave', 'prince', 'emperor', 'iii', 'ii', 'died', 'maternal', 'paternal'} {'germany', 'clausewitz', 'gustavus', 'joachim', 'prussia', 'albert', 'bismarck', 'bismarcks', 'prussian', 'brandenburg', 'saxony', 'frederick', 'dresden'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_10
  WTF: {'grand', 'career', 'championship', 'lost', 'wickets', 'world'} {'jordan', 'earnhardt', 'agassi', 'muralitharan', 'schumacher', 'hingis'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_11
  WTF: {'surgeon', 'nobel', 'world', 'theory', 'stress', 'vaccination', 'discovery', 'physician'} {'fleming', 'koch', 'pasteur', 'carrel', 'lister', 'jenner', 'edinburgh', 'hutton'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_12
  WTF: {'book', 'john', 'years', 'cartoonist', 'later', 'ro', 'work', 'bubbles', 'lad', 'new', 'poem', 'art'} {'thurber', 'abner', 'capp', 'masefield', 'dodgson', 'kirby', 'keats', 'lil', 'carroll', 'hopkins', 'housman', 'capps'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_13
  WTF: {'musical', 'string', 'words', 'concerto', 'quartet', 'der', 'da'} {'elgar', 'wk', 'handel', 'shostakovich', 'hoffmann', 'vienna', 'haydn'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_14
  WTF: {'war', 'cavalry', 'pp', 'supreme', 'union', 'general', 'justice', 'new'} {'virginia', 'hoover', 'carson', 'stuart', 'quayle', 'hancock', 'davis', 'thomas'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_15
  WTF: {'war', 'empereurs', 'senso', 'lady', 'clan', 'month', 'japon', 'son', 'china', 'throne'} {'gukansh', 'minamoto', 'nichiren', 'chiang', 'fujiwara', 'titsingh', 'kaishek', 'japanese', 'japan', 'varley'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_16
  WTF: {'allied', 'john', 'voyage', 'admiral', 'attack', 'ships', 'navy', 'lord', 'royal'} {'british', 'drake', 'nelson', 'wellington', 'jay', 'montgomery', 'mountbatten', 'rommel', 'rommels'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_17
  WTF: {'woman', 'short', 'stories', 'books', 'introduction', 'wrote', 'family', 'life', 'story', 'fiction', 'university', 'works', 'letters', 'press', 'women'} {'seymour', 'charlotte', 'shelleys', 'hawthorne', 'shelley', 'anne', 'bronts', 'godwin', 'jane', 'austens', 'austen', 'tomalin', 'wollstonecraft', 'mary', 'percy'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_18
  WTF: {'paint', 'painters', 'french', 'giger', 'millet', 'salon', 'museum'} {'pissarro', 'rodin', 'paris', 'davids', 'rodins', 'monet', 'david'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_19
  WTF: {'scientific', 'geometry', 'paper', 'mathematician', 'academy', 'astronomical', 'published', 'index', 'light', 'cohomology'} {'kepler', 'grothendieck', 'eulers', 'einsteins', 'keplers', 'atiyah', 'caspar', 'euler', 'rmer', 'hoyle'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_20
  WTF: {'guitar', 'roll', 'album', 'live', 'recording', 'rock', '2007'} {'elvis', 'bo', 'presleys', 'presley', 'davis', 'browns', 'armstrong'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_21
  WTF: {'guitar', 'rap', 'song', 'songs', 'albums', 'solo'} {'peart', 'benson', 'dj', 'nesmith', 'lee', 'drdre'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_22
  WTF: {'conservative', 'john', 'sir', 'crisis', '1939', 'lord', 'foot', 'cabinet', 'parliament'} {'british', 'canada', 'disraeli', 'canadian', 'riel', 'attlee', 'macdonald', 'holt', 'tupper'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_23
  WTF: {'sur', 'marquis', 'desire', 'subject', 'perception', 'work', 'political', 'published', 'works', 'prophecies', 'symbolic'} {'nostradamus', 'paris', 'lacan', 'rousseau', 'rousseaus', 'jacques', 'merleauponty', 'sade', 'diderot', 'deleuze', 'deleuzes'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_24
  WTF: {'war', 'expedition', 'civil', 'king', 'city', 'military', 'married', 'la', 'issue', 'doa', 'president', 'troops', 'leader', 'government', 'new'} {'madero', 'alfonso', 'ortega', 'almagro', 'xavier', 'corts', 'cid', 'pizarro', 'daz', 'moctezuma', 'francisco', 'madrid', 'franco', 'mexico', 'francos'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_25
  WTF: {'greek', 'saints', 'tours', 'day', 'testament', 'writings', 'life', 'catholic', 'feast', 'bishop', 'relics', 'roman'} {'chrysostom', 'athanasius', 'anthony', 'benedict', 'luke', 'jesus', 'ephrem', 'alexandria', 'jerome', 'cyril', 'mary', 'martin'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_26
  WTF: {'paintings', 'short', 'collection', 'award', 'christian', 'work', 'life', 'polar', 'little', 'works', '2005', 'scream', 'new', 'art'} {'alvar', 'nansen', 'kafkas', 'ibsen', 'eggum', 'munch', 'kafka', 'leiber', 'fafhrd', 'aalto', 'prideaux', 'andersen', 'mouser', 'munchs'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_27
  WTF: {'married', 'isbn', 'kingdom', 'ed', 'pp', 'chronicle', 'iii', 'isles', 'died', 'death', 'ii', 'english', 'saga', 'killed'} {'macbeth', 'selkirk', 'coluim', 'scots', 'kenneth', 'oram', 'alexander', 'scotland', 'maclaurin', 'mel', 'alba', 'malcolm', 'duncan', 'malcolms'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_28
  WTF: {'harbor', 'moon', 'series', 'anime', 'pearl', 'born', 'carrier', 'american', 'midway', 'dragon', 'pacific'} {'akira', 'japanese', 'hearn', 'yamamoto', 'kurosawa', 'lafcadio', 'morita', 'kurosawas', 'japan', 'yamamotos', 'ueshiba'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_29
  WTF: {'succession', 'reign', 'vii', 'earl', 'council', 'protestant', 'throne', 'duke', 'marriage', 'ii', 'death', 'kings', 'royal'} {'england', 'elizabeth', 'anne', 'wales', 'edward', 'owain', 'henrys', 'henry', 'charles', 'catherine', 'tudor', 'elizabeths', 'mary'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_30
  WTF: {'trial', 'reflections', 'pp', 'trials', 'gin', 'fox', 'witch', 'haven', 'published', 'company', 'prior', 'english', 'church', 'spelling'} {'yale', 'abbott', 'alcott', 'burke', 'edmund', 'bellamy', 'noah', 'connecticut', 'eli', 'mather', 'mathers', 'whitney', 'burkes', 'webster'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_31
  WTF: {'army', 'spain', 'tours', 'great', 'son', 'empire', 'iii', 'duc', 'ii', 'duke', 'spanish', 'imperial'} {'martel', 'france', 'italy', 'eugene', 'eugenes', 'europe', 'savoy', 'charlemagne', 'frankish', 'charles', 'louis', 'bernard'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_32
  WTF: {'married', 'grand', 'ca', 'daughter', 'empress', 'dowager', 'queen', 'family', 'heir', 'sister', 'sons', 'ii', 'death', 'died', 'lands'} {'mieszko', 'bolesaw', 'jadwiga', 'poland', 'feodorovna', 'lithuania', 'hungary', 'leszek', 'krakw', 'miller', 'lithuanian', 'casimir', 'maria', 'mindaugas', 'jadwigas'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_33
  WTF: {'cp', 'inquiry', 'interpretant', 'work', 'university', 'sense', 'method', 'eprint', 'mathematics'} {'dewey', 'bertrand', 'poppers', 'russell', 'russells', 'peirce', 'peirces', 'popper', 'moore'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_34
  WTF: {'band', 'chart', 'release', 'number', 'singles', 'new', 'billboard', 'pop'} {'uk', 'hatfield', 'mariah', 'careys', 'aaliyah', 'carey', 'enya', 'difranco'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_35
  WTF: {'rpt', 'communication', 'linguistic', 'missionary', 'phonetics', 'description', 'phonetic', 'humans', 'work', 'english', 'linguist', 'ability', 'vowels'} {'olduvai', 'kenya', 'kikuyu', 'hockett', 'whorf', 'jones', 'africa', 'westermann', 'morell', 'leakey', 'mary', 'african', 'louis'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_36
  WTF: {'scientific', 'biology', 'science', 'ray', 'society', 'theory', 'animals', 'principles', 'origin', 'history', 'vol', 'plants'} {'slotten', 'mendel', 'london', 'mayr', 'haeckel', 'darwin', 'lyell', 'ernst', 'charles', 'wallace', 'wallaces', 'darwins'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_37
  WTF: {'years', 'later', 'work', 'life', 'des', 'published', 'mal', 'literary', 'fleurs', 'play'} {'flaubert', 'paris', 'satie', 'richardson', 'baudelaires', 'maupassant', 'jarry', 'saties', 'baudelaire', 'tremblay'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_38
  WTF: {'poems', 'collected', 'joy', 'world', 'books', 'work', 'weird', 'monthly', 'life', 'literary', 'press', 'new', 'novel'} {'lewiss', 'peake', 'melville', 'lewis', 'melvilles', 'conrad', 'williams', 'dickenss', 'conrads', 'dickens', 'charles', 'herman', 'derleth'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_39
  WTF: {'differences', 'scientists', 'behavior', 'environmentalist', 'individual', 'carl', 'research'} {'rogers', 'wilson', 'rushton', 'jensens', 'venter', 'lomborg', 'jensen'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_40
  WTF: {'daughter', 'navigator', 'coast', 'prince', 'mother', 'iii', 'ii', 'expeditions', 'infanta', 'infante'} {'afonso', 'len', 'albuquerque', 'castile', 'portuguese', 'sancho', 'henry', 'portugal', 'aragon', 'coimbra'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_41
  WTF: {'pope', 'king', 'philosophersaint', 'anglosaxon', 'abbey', '279306', 'bishop', 'bishops', 'abbot', 'saint', 'journal', 'english', 'historia'} {'bedes', 'columbanus', 'anselm', 'bede', 'canterbury', 'aleister', 'dunstan', 'augustine', 'vaughn', 'crowleys', 'crowley', 'anselms', 'sutin'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_42
  WTF: {'players', 'american', 'player', 'allstar', 'tigers', 'blues', 'pitched', 'pitchers'} {'youngs', 'greenberg', 'milwaukee', 'mlb', 'rockne', 'nhl', 'cy', 'doubleday'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_43
  WTF: {'moon', 'united', 'plane', 'grace', 'test', 'navy', 'mach', 'crew'} {'apollo', 'bingham', 'armstrongs', 'aldrin', 'hopper', 'armstrong', 'hansen', 'yeager'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_44
  WTF: {'shows', 'featured', 'film', 'lyrics', 'minutes', 'wrote', 'popular', 'composer', 'golf', 'musicals', 'radio'} {'elfman', 'ira', 'broadway', 'kern', 'dowland', 'crosby', 'crosbys', 'gershwin', 'dowlands', 'burton', 'bing'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_45
  WTF: {'conservative', 'theological', 'study', 'law', 'theology', 'prophets', 'work', 'university', 'rabbis', 'man', 'sabbath', 'studies', 'scholars'} {'heschel', 'jts', 'steinsaltz', 'hebrew', 'jewish', 'neusner', 'kushner', 'judaism', 'kaplans', 'neusners', 'talmud', 'torah', 'kaplan'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_46
  WTF: {'designs', 'glass', 'center', 'homes', 'houses', 'new', 'art'} {'wright', 'lloyd', 'lin', 'wrights', 'pei', 'chicago', 'mies'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_47
  WTF: {'operas', 'dargento', 'barbiere', 'composers', 'concert', 'dal', 'doro', 'award', 'score'} {'paris', 'rossini', 'morricone', 'ennio', 'rossinis', 'premio', 'morricones', 'gioachino', 'bologna'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_48
  WTF: {'reserve', 'freedom', 'monetary', 'economists', 'theory', 'von', 'university', 'economy', 'institute', 'policy'} {'rothbard', 'friedmans', 'hayek', 'mises', 'murray', 'friedman', 'drexel', 'milken', 'tobin', 'hayeks'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_49
  WTF: {'1930', 'proof', 'work', 'axiom', 'problem', 'mathematician', 'bomb', '1996'} {'knigsberg', 'reid', 'neumann', 'gdel', 'hilberts', 'hilbert', 'neumanns', 'gttingen'}
  WTF?!?!? 8
  WTF?!?!? 8
{'fix': <__main__.FastFixPhiRegularizer object at 0x7fd2c20001c0>}
Check after fit:
Skipping background topic: background_1.
topic_0
  WTF: {'academy', 'episode', 'career', '2008'} {'hitchcock', 'paul', 'robeson', 'cagney'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_1
  WTF: {'interrogation', 'army', '2002', 'ali', 'empire', 'muslims', 'al', 'government', 'new'} {'afghanistan', 'persian', 'abd', 'rumi', 'cia', 'islamic', 'muhammad', 'zubaydah', 'abu'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_2
  WTF: {'renaissance', 'san', 'cardinal', 'life', 'del', 'st', 'il', 'english', 'church', 'new'} {'francis', 'caravaggio', 'calvino', 'florence', 'rome', 'borgia', 'lucrezia', 'marco', 'fellini', 'bruno'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_3
  WTF: {'dio', 'emperors', 'christian', 'caesars', 'life', 'gibbon', 'senate', 'death', 'ancient', 'church', 'caesar', 'imperial'} {'augustus', 'rome', 'barnes', 'julian', 'eusebius', 'constantius', 'claudius', 'caligula', 'tiberius', 'diocletian', 'tacitus', 'suetonius'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_4
  WTF: {'machine', 'project', 'information', 'language', 'work', 'institute', 'operating', 'interview', 'award'} {'shannon', 'minsky', 'sanger', 'turing', 'engelbart', 'warwick', 'babbage', 'zuse', 'wikipedia'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_5
  WTF: {'professor', 'scientific', 'chemical', 'wireless', 'science', 'quantum', 'theory', 'institute', 'research'} {'bohr', 'fermi', 'davy', 'planck', 'faraday', 'marie', 'bardeen', 'heaviside', 'marconi'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_6
  WTF: {'army', 'chess', 'military', 'film', 'committee', 'state', 'time', 'world', 'life', 'revolution', 'government', 'march', 'order', 'new'} {'russian', 'philby', 'moscow', 'trotsky', 'alexander', 'nicholas', 'stalin', 'chekhov', 'beria', 'gorbachev', 'tito', 'kasparov', 'yeltsin', 'russia'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_7
  WTF: {'war', 'psychology', 'state', 'language', 'work', 'party', 'theory', 'political', 'von', 'logic', 'published', 'history', 'social', 'und', 'phenomenology'} {'germany', 'mccarthy', 'husserl', 'schwitters', 'reich', 'goebbels', 'hegel', 'chomsky', 'hesse', 'gring', 'berlin', 'hegels', 'habermas', 'hitler', 'nazi'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_8
  WTF: {'series', 'world', 'books', 'english', 'mars'} {'steinbeck', 'moorcock', 'crichton', 'verne', 'pohl'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_9
  WTF: {'army', 'married', 'daughter', 'military', 'son', 'margrave', 'prince', 'emperor', 'iii', 'ii', 'died', 'maternal', 'paternal'} {'germany', 'clausewitz', 'gustavus', 'joachim', 'prussia', 'albert', 'bismarck', 'bismarcks', 'prussian', 'brandenburg', 'saxony', 'frederick', 'dresden'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_10
  WTF: {'grand', 'career', 'championship', 'lost', 'wickets', 'world'} {'jordan', 'earnhardt', 'agassi', 'muralitharan', 'schumacher', 'hingis'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_11
  WTF: {'surgeon', 'nobel', 'world', 'theory', 'stress', 'vaccination', 'discovery', 'physician'} {'fleming', 'koch', 'pasteur', 'carrel', 'lister', 'jenner', 'edinburgh', 'hutton'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_12
  WTF: {'book', 'john', 'years', 'cartoonist', 'later', 'ro', 'work', 'bubbles', 'lad', 'new', 'poem', 'art'} {'thurber', 'abner', 'capp', 'masefield', 'dodgson', 'kirby', 'keats', 'lil', 'carroll', 'hopkins', 'housman', 'capps'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_13
  WTF: {'musical', 'string', 'words', 'concerto', 'quartet', 'der', 'da'} {'elgar', 'wk', 'handel', 'shostakovich', 'hoffmann', 'vienna', 'haydn'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_14
  WTF: {'war', 'cavalry', 'pp', 'supreme', 'union', 'general', 'justice', 'new'} {'virginia', 'hoover', 'carson', 'stuart', 'quayle', 'hancock', 'davis', 'thomas'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_15
  WTF: {'war', 'empereurs', 'senso', 'lady', 'clan', 'month', 'japon', 'son', 'china', 'throne'} {'gukansh', 'minamoto', 'nichiren', 'chiang', 'fujiwara', 'titsingh', 'kaishek', 'japanese', 'japan', 'varley'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_16
  WTF: {'allied', 'john', 'voyage', 'admiral', 'attack', 'ships', 'navy', 'lord', 'royal'} {'british', 'drake', 'nelson', 'wellington', 'jay', 'montgomery', 'mountbatten', 'rommel', 'rommels'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_17
  WTF: {'woman', 'short', 'stories', 'books', 'introduction', 'wrote', 'family', 'life', 'story', 'fiction', 'university', 'works', 'letters', 'press', 'women'} {'seymour', 'charlotte', 'shelleys', 'hawthorne', 'shelley', 'anne', 'bronts', 'godwin', 'jane', 'austens', 'austen', 'tomalin', 'wollstonecraft', 'mary', 'percy'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_18
  WTF: {'paint', 'painters', 'french', 'giger', 'millet', 'salon', 'museum'} {'pissarro', 'rodin', 'paris', 'davids', 'rodins', 'monet', 'david'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_19
  WTF: {'scientific', 'geometry', 'paper', 'mathematician', 'academy', 'astronomical', 'published', 'index', 'light', 'cohomology'} {'kepler', 'grothendieck', 'eulers', 'einsteins', 'keplers', 'atiyah', 'caspar', 'euler', 'rmer', 'hoyle'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_20
  WTF: {'guitar', 'roll', 'album', 'live', 'recording', 'rock', '2007'} {'elvis', 'bo', 'presleys', 'presley', 'davis', 'browns', 'armstrong'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_21
  WTF: {'guitar', 'rap', 'song', 'songs', 'albums', 'solo'} {'peart', 'benson', 'dj', 'nesmith', 'lee', 'drdre'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_22
  WTF: {'conservative', 'john', 'sir', 'crisis', '1939', 'lord', 'foot', 'cabinet', 'parliament'} {'british', 'canada', 'disraeli', 'canadian', 'riel', 'attlee', 'macdonald', 'holt', 'tupper'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_23
  WTF: {'sur', 'marquis', 'desire', 'subject', 'perception', 'work', 'political', 'published', 'works', 'prophecies', 'symbolic'} {'nostradamus', 'paris', 'lacan', 'rousseau', 'rousseaus', 'jacques', 'merleauponty', 'sade', 'diderot', 'deleuze', 'deleuzes'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_24
  WTF: {'war', 'expedition', 'civil', 'king', 'city', 'military', 'married', 'la', 'issue', 'doa', 'president', 'troops', 'leader', 'government', 'new'} {'madero', 'alfonso', 'ortega', 'almagro', 'xavier', 'corts', 'cid', 'pizarro', 'daz', 'moctezuma', 'francisco', 'madrid', 'franco', 'mexico', 'francos'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_25
  WTF: {'greek', 'saints', 'tours', 'day', 'testament', 'writings', 'life', 'catholic', 'feast', 'bishop', 'relics', 'roman'} {'chrysostom', 'athanasius', 'anthony', 'benedict', 'luke', 'jesus', 'ephrem', 'alexandria', 'jerome', 'cyril', 'mary', 'martin'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_26
  WTF: {'paintings', 'short', 'collection', 'award', 'christian', 'work', 'life', 'polar', 'little', 'works', '2005', 'scream', 'new', 'art'} {'alvar', 'nansen', 'kafkas', 'ibsen', 'eggum', 'munch', 'kafka', 'leiber', 'fafhrd', 'aalto', 'prideaux', 'andersen', 'mouser', 'munchs'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_27

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7fd2bad00610>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7fd2b316d880>}
{'perplexity': 313216.71875, 'coherence_20': 0.8045542585061849, 'diversity_euclidean': 0.03276592371773437, 'diversity_jensenshannon': 0.6513325844673593, 'diversity_hellinger': 0.7642723692652488, 'diversity_cosine': 0.7284861955371741, 'fair_ppl_free': 2761.56982421875, 'fair_ppl_fix': 310319.96875, 'unfair_ppl_banklike': 313216.71875}
{'num_topics': 51, 'num_common_words': 65750, 'num_model_words': 155407, 'num_bt_words': 135939, 'top_diffs': [{'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}]}
16
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
  WTF: {'academy', 'time', 'career', '2008'} {'hitchcock', 'paul', 'robeson', 'cagney'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_1
  WTF: {'interrogation', 'army', '2002', 'ali', 'empire', 'muslims', 'al', 'government', 'new'} {'afghanistan', 'persian', 'abd', 'rumi', 'cia', 'islamic', 'muhammad', 'zubaydah', 'abu'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_2
  WTF: {'dio', 'greek', 'emperors', 'caesars', 'life', 'imperial', 'gibbon', 'senate', 'death', 'ancient', 'caesar', 'christian'} {'augustus', 'rome', 'barnes', 'julian', 'eusebius', 'constantius', 'claudius', 'caligula', 'tiberius', 'diocletian', 'tacitus', 'suetonius'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_3
  WTF: {'meat', 'albums'} {'elvis', 'presley'}
topic_4
  WTF: {'machine', 'information', 'computers', 'institute', 'operating', 'interview', 'award', 'mathematical', 'mathematics'} {'shannon', 'minsky', 'sanger', 'turing', 'engelbart', 'warwick', 'babbage', 'zuse', 'wikipedia'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_5
  WTF: {'pope', 'della', 'film', 'leonardo', 'marble', 'san', 'work', 'life', 'painting', 'del', 'il', 'new'} {'giordano', 'caravaggios', 'caravaggio', 'florence', 'rome', 'medici', 'lucrezia', 'borgia', 'cesare', 'angelico', 'fellini', 'bruno'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_6
  WTF: {'war', 'psychology', 'state', 'language', 'world', 'work', 'theory', 'party', 'political', 'published', 'logic', 'social', 'und', 'phenomenology'} {'germany', 'mccarthy', 'husserl', 'schwitters', 'reich', 'goebbels', 'hegel', 'chomsky', 'gring', 'berlin', 'hegels', 'habermas', 'hitler', 'nazi'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_7
  WTF: {'army', 'chess', 'military', 'committee', 'state', 'time', 'world', 'revolution', 'bolsheviks', 'government', 'march', 'ii', 'order', 'new'} {'russian', 'philby', 'moscow', 'trotsky', 'alexander', 'nicholas', 'stalin', 'chekhov', 'beria', 'gorbachev', 'tito', 'kasparov', 'yeltsin', 'russia'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_8
  WTF: {'li', 'psychoanalysis', 'time', 'work', 'life', 'des', 'political', 'trans', 'university', 'published', 'new', 'philosophy'} {'sartre', 'nostradamus', 'paris', 'lacan', 'rousseau', 'satie', 'erasmus', 'rousseaus', 'camus', 'sade', 'baudelaire', 'deleuze'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_9
  WTF: {'series', 'world', 'books', 'english', 'mars'} {'steinbeck', 'moorcock', 'crichton', 'verne', 'pohl'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_10
  WTF: {'string', 'words', 'quartet', 'composers', 'works', 'trio', 'da'} {'elgar', 'wk', 'handel', 'shostakovich', 'hoffmann', 'lugosi', 'haydn'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_11
  WTF: {'army', 'married', 'chancellor', 'military', 'otto', 'margrave', 'prince', 'emperor', 'iii', 'ii', 'died', 'maternal', 'insurance', 'paternal'} {'germany', 'clausewitz', 'gustavus', 'joachim', 'prussia', 'albert', 'albertus', 'bismarck', 'bismarcks', 'prussian', 'brandenburg', 'saxony', 'frederick', 'dresden'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_12
  WTF: {'grand', 'career', 'championship', 'lost', 'wickets', 'world'} {'jordan', 'earnhardt', 'agassi', 'muralitharan', 'schumacher', 'hingis'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_13
  WTF: {'professor', 'scientific', 'work', 'science', 'quantum', 'institute', 'scientists', 'research'} {'bohr', 'meitner', 'fermi', 'planck', 'fuchs', 'marie', 'bardeen', 'marconi'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_14
  WTF: {'war', 'empereurs', 'senso', 'japon', 'lady', 'clan', 'month', 'emperors', 'son', 'throne', 'court'} {'chinese', 'minamoto', 'nichiren', 'chiang', 'fujiwara', 'titsingh', 'kaishek', 'japanese', 'japan', 'deng', 'varley'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_15
  WTF: {'war', 'cavalry', 'pp', 'supreme', 'union', 'general', 'justice', 'new'} {'virginia', 'hoover', 'carson', 'stuart', 'quayle', 'hancock', 'davis', 'thomas'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_16
  WTF: {'paint', 'sculpture', 'painters', 'giger', 'millet', 'salon', 'artists', 'museum'} {'pissarro', 'rodin', 'paris', 'davids', 'rodins', 'monet', 'david', 'goya'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_17
  WTF: {'war', 'john', 'voyage', 'commander', 'forces', 'ship', 'navy', 'general', 'lord', 'spanish', 'royal'} {'british', 'drake', 'nelson', 'wellington', 'alexander', 'hibbert', 'montgomery', 'india', 'mountbatten', 'blackbeard', 'sugden'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_18
  WTF: {'war', 'expedition', 'civil', 'king', 'city', 'military', 'married', 'la', 'issue', 'doa', 'president', 'troops', 'leader', 'government', 'new'} {'madero', 'alfonso', 'ortega', 'almagro', 'xavier', 'corts', 'cid', 'aztec', 'pizarro', 'daz', 'francisco', 'madrid', 'franco', 'mexico', 'moctezuma'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_19
  WTF: {'conservative', 'john', 'sir', 'crisis', '1939', 'lord', 'foot', 'cabinet', 'parliament'} {'british', 'canada', 'disraeli', 'canadian', 'riel', 'attlee', 'macdonald', 'holt', 'tupper'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_20
  WTF: {'libertarian', 'economist', 'climate', 'global', 'environmental', 'social', 'market', 'policy', 'institute', 'free', 'singer'} {'ricardo', 'rogers', 'wilson', 'dewey', 'rushton', 'rothbard', 'hayek', 'lomborg', 'friedman', 'milken', 'jensen'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_21
  WTF: {'greek', 'saints', 'encyclopedia', 'tours', 'testament', 'writings', 'life', 'feast', 'bishop', 'roman', 'evangelist'} {'chrysostom', 'athanasius', 'anthony', 'luke', 'jesus', 'ephrem', 'alexandria', 'jerome', 'cyril', 'mary', 'martin'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_22
  WTF: {'nobel', 'world', 'theory', 'cowpox', 'university', 'research', 'discovery', 'royal', 'physician'} {'fleming', 'london', 'koch', 'pasteur', 'carrel', 'lister', 'jenner', 'edinburgh', 'hutton'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_23
  WTF: {'isbn', 'kingdom', 'prophecy', 'ed', 'pp', 'chronicle', 'iii', 'isles', 'kingship', 'died', 'death', 'ii', 'english', 'saga', 'killed'} {'macbeth', 'selkirk', 'coluim', 'scots', 'kenneth', 'oram', 'alexander', 'scotland', 'maclaurin', 'mel', 'alba', 'malcolm', 'duncan', 'malcolms', 'scottish'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_24
  WTF: {'war', 'harbor', 'moon', 'film', 'admiral', 'manga', 'pearl', 'samurai', 'born', 'films', 'carrier', 'midway', 'pacific'} {'tokyo', 'akira', 'japanese', 'japan', 'yamamoto', 'kurosawa', 'lafcadio', 'fukuyama', 'morita', 'kurosawas', 'hearn', 'yamamotos', 'ueshiba'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_25
  WTF: {'poets', 'years', 'ed', 'work', 'english', 'donnes', 'published', 'works', 'death', 'letters', 'lad', 'nonsense', 'verse'} {'london', 'peake', 'alice', 'severn', 'masefield', 'lewis', 'dodgson', 'nash', 'keats', 'shropshire', 'carroll', 'hopkins', 'housman'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_26
  WTF: {'army', 'spain', 'tours', 'great', 'son', 'empire', 'iii', 'duc', 'ii', 'duke', 'spanish', 'imperial'} {'martel', 'france', 'italy', 'eugene', 'eugenes', 'europe', 'savoy', 'charlemagne', 'frankish', 'charles', 'louis', 'bernard'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_27
  WTF: {'dictionary', 'school', 'meeting', 'trials', 'gin', 'children', 'witch', 'bible', 'haven', 'meetings', 'published', 'church', 'spelling', 'christian'} {'yale', 'abbott', 'alcott', 'foxs', 'bellamy', 'noah', 'connecticut', 'eli', 'mather', 'mathers', 'whitney', 'quakers', 'webster', 'nickalls'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_28
  WTF: {'atomic', 'stars', 'society', 'mathematician', 'number', 'theorem', 'university', 'medal', 'mechanics'} {'cambridge', 'reid', 'eddingtons', 'eddington', 'napier', 'moseley', 'hilberts', 'hilbert', 'hoyle'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_29
  WTF: {'succession', 'reign', 'vii', 'earl', 'council', 'protestant', 'throne', 'duke', 'marriage', 'ii', 'death', 'kings', 'royal'} {'england', 'elizabeth', 'anne', 'wales', 'edward', 'owain', 'henrys', 'henry', 'charles', 'catherine', 'tudor', 'elizabeths', 'mary'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_30
  WTF: {'expedition', 'arctic', 'paintings', 'new', 'work', 'life', 'op', 'composer', 'polar', 'works', 'sand', 'music', '2005', 'scream', 'museum', 'art'} {'alvar', 'nansen', 'kafkas', 'norway', 'ibsen', 'franz', 'eggum', 'munch', 'kafka', 'fridtjof', 'chopin', 'aalto', 'prideaux', 'warsaw', 'chopins', 'munchs'}
  WTF?!?!? 16
  WTF?!?!? 16
topic_31
  WTF: {'married', 'grand', 'ca', 'daughter', 'empress', 'family', 'queen', 'emperor', 'sister', 'sons', 'ii', 'death', 'died', 'lands', 'brother'} {'mieszko', 'bolesaw', 'jadwiga', 'poland', 'feodorovna', 'lithuania', 'hungary', 'leszek', 'krakw', 'miller', 'lithuanian', 'casimir', 'maria', 'mindaugas', 'jadwigas'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_32
  WTF: {'isbn', 'woman', 'poems', 'sisters', 'spark', 'ed', 'introduction', 'wrote', 'life', 'university', 'published', 'works', 'cc', 'literary', 'letters', 'press', 'women'} {'seymour', 'charlotte', 'shelleys', 'hawthorne', 'sunstein', 'shelley', 'anne', 'bronts', 'godwin', 'jane', 'austens', 'austen', 'tomalin', 'bront', 'wollstonecraft', 'mary', 'percy'}
  WTF?!?!? 17
  WTF?!?!? 17
topic_33
  WTF: {'observatory', 'planets', 'scientific', 'formula', 'nova', 'astronomia', 'published', 'tables', 'optics'} {'tycho', 'kepler', 'eulers', 'euler', 'caspar', 'rmer', 'johannes', 'keplers', 'celsius'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_34
  WTF: {'performed', 'musical', 'film', 'chorus', 'composition', 'requiem', 'works', 'scores', 'giovanni', 'counterpoint'} {'palestrina', 'rossini', 'morricone', 'milan', 'ennio', 'rossinis', 'verdis', 'giuseppe', 'morricones', 'gioachino'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_35
  WTF: {'rpt', 'communication', 'linguistic', 'missionary', 'phonetics', 'description', 'phonetic', 'humans', 'work', 'english', 'linguist', 'ability', 'vowels'} {'olduvai', 'kenya', 'kikuyu', 'hockett', 'whorf', 'jones', 'africa', 'westermann', 'morell', 'leakey', 'mary', 'african', 'louis'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_36
  WTF: {'induction', 'cp', 'inquiry', 'interpretant', 'knowledge', 'pragmatism', 'work', 'method', 'eprint'} {'skinner', 'bertrand', 'poppers', 'russell', 'russells', 'peirce', 'peirces', 'popper', 'moore'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_37
  WTF: {'spain', 'pietro', 'father', 'italian', 'feast', 'judges', 'roman', 'ibid', 'god'} {'francis', 'alberoni', 'bellarmine', 'rome', 'mychal', 'contarini', 'porziuncola', 'assisi', 'franciscan'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_38
  WTF: {'daughter', 'navigator', 'coast', 'prince', 'mother', 'iii', 'ii', 'expeditions', 'infanta', 'infante'} {'afonso', 'len', 'albuquerque', 'castile', 'portuguese', 'sancho', 'henry', 'portugal', 'aragon', 'coimbra'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_39
  WTF: {'moon', 'united', 'plane', 'grace', 'test', 'navy', 'mach', 'crew'} {'apollo', 'bingham', 'armstrongs', 'aldrin', 'hopper', 'armstrong', 'hansen', 'yeager'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_40
  WTF: {'new', 'shmoo', 'cartoonists', 'best', 'work', 'syndicated', 'award', 'characters', 'shmoos', 'art'} {'abner', 'capp', 'barney', 'hobbes', 'simon', 'trudeau', 'watterson', 'kirby', 'lil', 'capps'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_41
  WTF: {'park', 'designs', 'architectural', 'residential', 'center', 'tower', 'houses', 'new'} {'chihuly', 'wright', 'lloyd', 'lin', 'wrights', 'pei', 'chicago', 'mies'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_42
  WTF: {'series', 'collection', 'life', 'adapted', 'novella', 'fiction', 'published', 'little', '2007', 'childrens', 'novel'} {'sheldon', 'beatrix', 'christie', 'christies', 'blytons', 'tiptree', 'enid', 'acker', 'blyton', 'erdrich', 'agatha'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_43
  WTF: {'hot', 'pg', 'release', 'number', 'rb', 'singles', 'pop'} {'uk', 'mariah', 'careys', 'aaliyah', 'carey', 'enya', 'difranco'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_44
  WTF: {'scientific', 'biology', 'ray', 'science', 'society', 'theory', 'animals', 'principles', 'origin', 'geological', 'vol', 'plants'} {'slotten', 'mendel', 'mayr', 'haeckel', 'darwin', 'lyell', 'ernst', 'charles', 'wallace', 'wallaces', 'lyells', 'darwins'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_45
  WTF: {'players', 'hall', 'allstar', 'tigers', 'hit', 'pitched', 'american'} {'youngs', 'greenberg', 'milwaukee', 'mlb', 'rockne', 'cy', 'doubleday'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_46
  WTF: {'professor', 'neuropathology', 'hans', 'clinical', 'chemotherapy', 'university', 'institute', 'serum', 'und', 'chemiae'} {'ehrlichs', 'berlin', 'jakob', 'selye', 'ehrlich', 'leiden', 'creutzfeldtjakob', 'kiel', 'boerhaave', 'creutzfeldt'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_47
  WTF: {'conservative', 'theological', 'study', 'law', 'theology', 'prophets', 'work', 'university', 'rabbis', 'man', 'sabbath', 'studies', 'scholars'} {'heschel', 'jts', 'steinsaltz', 'hebrew', 'jewish', 'neusner', 'kushner', 'judaism', 'kaplans', 'neusners', 'talmud', 'torah', 'kaplan'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_48
  WTF: {'electrical', 'gases', 'chemical', 'sir', 'society', 'lamp', 'como', 'discovered', 'field', 'current', 'chemistry'} {'humphry', 'davys', 'volta', 'penzance', 'oliver', 'davy', 'michael', 'heavisides', 'faradays', 'faraday', 'heaviside'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_49
  WTF: {'isbn', 'christmas', 'new', 'collected', 'written', 'bleak', 'life', 'literary', 'writing', 'serial'} {'melville', 'melvilles', 'williams', 'dickenss', 'conrads', 'smith', 'dickens', 'charles', 'herman', 'conrad'}
  WTF?!?!? 10
  WTF?!?!? 10
{'fix': <__main__.FastFixPhiRegularizer object at 0x7fd2166b2dc0>}
Check after fit:
Skipping background topic: background_1.
topic_0
  WTF: {'academy', 'time', 'career', '2008'} {'hitchcock', 'paul', 'robeson', 'cagney'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_1
  WTF: {'interrogation', 'army', '2002', 'ali', 'empire', 'muslims', 'al', 'government', 'new'} {'afghanistan', 'persian', 'abd', 'rumi', 'cia', 'islamic', 'muhammad', 'zubaydah', 'abu'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_2
  WTF: {'dio', 'greek', 'emperors', 'caesars', 'life', 'imperial', 'gibbon', 'senate', 'death', 'ancient', 'caesar', 'christian'} {'augustus', 'rome', 'barnes', 'julian', 'eusebius', 'constantius', 'claudius', 'caligula', 'tiberius', 'diocletian', 'tacitus', 'suetonius'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_3
  WTF: {'meat', 'albums'} {'elvis', 'presley'}
topic_4
  WTF: {'machine', 'information', 'computers', 'institute', 'operating', 'interview', 'award', 'mathematical', 'mathematics'} {'shannon', 'minsky', 'sanger', 'turing', 'engelbart', 'warwick', 'babbage', 'zuse', 'wikipedia'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_5
  WTF: {'pope', 'della', 'film', 'leonardo', 'marble', 'san', 'work', 'life', 'painting', 'del', 'il', 'new'} {'giordano', 'caravaggios', 'caravaggio', 'florence', 'rome', 'medici', 'lucrezia', 'borgia', 'cesare', 'angelico', 'fellini', 'bruno'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_6
  WTF: {'war', 'psychology', 'state', 'language', 'world', 'work', 'theory', 'party', 'political', 'published', 'logic', 'social', 'und', 'phenomenology'} {'germany', 'mccarthy', 'husserl', 'schwitters', 'reich', 'goebbels', 'hegel', 'chomsky', 'gring', 'berlin', 'hegels', 'habermas', 'hitler', 'nazi'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_7
  WTF: {'army', 'chess', 'military', 'committee', 'state', 'time', 'world', 'revolution', 'bolsheviks', 'government', 'march', 'ii', 'order', 'new'} {'russian', 'philby', 'moscow', 'trotsky', 'alexander', 'nicholas', 'stalin', 'chekhov', 'beria', 'gorbachev', 'tito', 'kasparov', 'yeltsin', 'russia'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_8
  WTF: {'li', 'psychoanalysis', 'time', 'work', 'life', 'des', 'political', 'trans', 'university', 'published', 'new', 'philosophy'} {'sartre', 'nostradamus', 'paris', 'lacan', 'rousseau', 'satie', 'erasmus', 'rousseaus', 'camus', 'sade', 'baudelaire', 'deleuze'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_9
  WTF: {'series', 'world', 'books', 'english', 'mars'} {'steinbeck', 'moorcock', 'crichton', 'verne', 'pohl'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_10
  WTF: {'string', 'words', 'quartet', 'composers', 'works', 'trio', 'da'} {'elgar', 'wk', 'handel', 'shostakovich', 'hoffmann', 'lugosi', 'haydn'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_11
  WTF: {'army', 'married', 'chancellor', 'military', 'otto', 'margrave', 'prince', 'emperor', 'iii', 'ii', 'died', 'maternal', 'insurance', 'paternal'} {'germany', 'clausewitz', 'gustavus', 'joachim', 'prussia', 'albert', 'albertus', 'bismarck', 'bismarcks', 'prussian', 'brandenburg', 'saxony', 'frederick', 'dresden'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_12
  WTF: {'grand', 'career', 'championship', 'lost', 'wickets', 'world'} {'jordan', 'earnhardt', 'agassi', 'muralitharan', 'schumacher', 'hingis'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_13
  WTF: {'professor', 'scientific', 'work', 'science', 'quantum', 'institute', 'scientists', 'research'} {'bohr', 'meitner', 'fermi', 'planck', 'fuchs', 'marie', 'bardeen', 'marconi'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_14
  WTF: {'war', 'empereurs', 'senso', 'japon', 'lady', 'clan', 'month', 'emperors', 'son', 'throne', 'court'} {'chinese', 'minamoto', 'nichiren', 'chiang', 'fujiwara', 'titsingh', 'kaishek', 'japanese', 'japan', 'deng', 'varley'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_15
  WTF: {'war', 'cavalry', 'pp', 'supreme', 'union', 'general', 'justice', 'new'} {'virginia', 'hoover', 'carson', 'stuart', 'quayle', 'hancock', 'davis', 'thomas'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_16
  WTF: {'paint', 'sculpture', 'painters', 'giger', 'millet', 'salon', 'artists', 'museum'} {'pissarro', 'rodin', 'paris', 'davids', 'rodins', 'monet', 'david', 'goya'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_17
  WTF: {'war', 'john', 'voyage', 'commander', 'forces', 'ship', 'navy', 'general', 'lord', 'spanish', 'royal'} {'british', 'drake', 'nelson', 'wellington', 'alexander', 'hibbert', 'montgomery', 'india', 'mountbatten', 'blackbeard', 'sugden'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_18
  WTF: {'war', 'expedition', 'civil', 'king', 'city', 'military', 'married', 'la', 'issue', 'doa', 'president', 'troops', 'leader', 'government', 'new'} {'madero', 'alfonso', 'ortega', 'almagro', 'xavier', 'corts', 'cid', 'aztec', 'pizarro', 'daz', 'francisco', 'madrid', 'franco', 'mexico', 'moctezuma'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_19
  WTF: {'conservative', 'john', 'sir', 'crisis', '1939', 'lord', 'foot', 'cabinet', 'parliament'} {'british', 'canada', 'disraeli', 'canadian', 'riel', 'attlee', 'macdonald', 'holt', 'tupper'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_20
  WTF: {'libertarian', 'economist', 'climate', 'global', 'environmental', 'social', 'market', 'policy', 'institute', 'free', 'singer'} {'ricardo', 'rogers', 'wilson', 'dewey', 'rushton', 'rothbard', 'hayek', 'lomborg', 'friedman', 'milken', 'jensen'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_21
  WTF: {'greek', 'saints', 'encyclopedia', 'tours', 'testament', 'writings', 'life', 'feast', 'bishop', 'roman', 'evangelist'} {'chrysostom', 'athanasius', 'anthony', 'luke', 'jesus', 'ephrem', 'alexandria', 'jerome', 'cyril', 'mary', 'martin'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_22
  WTF: {'nobel', 'world', 'theory', 'cowpox', 'university', 'research', 'discovery', 'royal', 'physician'} {'fleming', 'london', 'koch', 'pasteur', 'carrel', 'lister', 'jenner', 'edinburgh', 'hutton'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_23
  WTF: {'isbn', 'kingdom', 'prophecy', 'ed', 'pp', 'chronicle', 'iii', 'isles', 'kingship', 'died', 'death', 'ii', 'english', 'saga', 'killed'} {'macbeth', 'selkirk', 'coluim', 'scots', 'kenneth', 'oram', 'alexander', 'scotland', 'maclaurin', 'mel', 'alba', 'malcolm', 'duncan', 'malcolms', 'scottish'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_24
  WTF: {'war', 'harbor', 'moon', 'film', 'admiral', 'manga', 'pearl', 'samurai', 'born', 'films', 'carrier', 'midway', 'pacific'} {'tokyo', 'akira', 'japanese', 'japan', 'yamamoto', 'kurosawa', 'lafcadio', 'fukuyama', 'morita', 'kurosawas', 'hearn', 'yamamotos', 'ueshiba'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_25
  WTF: {'poets', 'years', 'ed', 'work', 'english', 'donnes', 'published', 'works', 'death', 'letters', 'lad', 'nonsense', 'verse'} {'london', 'peake', 'alice', 'severn', 'masefield', 'lewis', 'dodgson', 'nash', 'keats', 'shropshire', 'carroll', 'hopkins', 'housman'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_26

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7fd2baee0040>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7fd2bf8a11c0>}
{'perplexity': 340069.625, 'coherence_20': 0.8029668786416517, 'diversity_euclidean': 0.03346252646632267, 'diversity_jensenshannon': 0.6559184923631768, 'diversity_hellinger': 0.7703079599163548, 'diversity_cosine': 0.7365443905262021, 'fair_ppl_free': 2775.4365234375, 'fair_ppl_fix': 431778.15625, 'unfair_ppl_banklike': 340069.625}
{'num_topics': 51, 'num_common_words': 65750, 'num_model_words': 155407, 'num_bt_words': 135939, 'top_diffs': [{'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 32, 'lost_bt': 16, 'lost_model': 16}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 34, 'lost_bt': 17, 'lost_model': 17}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}]}
17
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
  WTF: {'greek', 'reign', 'time', 'ad', 'century', 'death', 'new', 'god'} {'augustus', 'rome', 'barnes', 'eusebius', 'claudius', 'caligula', 'diocletian', 'tacitus'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_1
  WTF: {'interrogation', 'army', '2002', 'ali', 'empire', 'muslims', 'al', 'government', 'new'} {'afghanistan', 'persian', 'abd', 'rumi', 'cia', 'islamic', 'muhammad', 'zubaydah', 'abu'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_2
  WTF: {'renaissance', 'san', 'father', 'cardinal', 'life', 'saint', 'del', 'st', 'il', 'church', 'new'} {'francis', 'caravaggio', 'calvino', 'florence', 'rome', 'borgia', 'lucrezia', 'marco', 'cesare', 'fellini', 'bruno'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_3
  WTF: {'recording', 'single'} {'elvis', 'presley'}
topic_4
  WTF: {'machine', 'information', 'computers', 'program', 'institute', 'operating', 'interview', 'award', 'mathematics'} {'shannon', 'minsky', 'sanger', 'turing', 'engelbart', 'warwick', 'babbage', 'zuse', 'wikipedia'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_5
  WTF: {'poems', 'short', 'books', 'work', 'wrote', 'family', 'story', 'university', 'writing', 'press'} {'shelleys', 'tolkien', 'lewis', 'shelley', 'anne', 'jane', 'austen', 'dickens', 'wollstonecraft', 'mary'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_6
  WTF: {'war', 'army', 'military', 'film', 'committee', 'state', 'later', 'time', 'world', 'life', 'revolution', 'government', 'order', 'new', 'central'} {'russian', 'philby', 'moscow', 'trotsky', 'khmelnytsky', 'alexander', 'chekhov', 'stalin', 'beria', 'gorbachev', 'sakharov', 'tito', 'kasparov', 'yeltsin', 'russia'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_7
  WTF: {'war', 'jews', 'state', 'reason', 'theory', 'party', 'political', 'von', 'logic', 'published', 'social', 'und', 'minister', 'phenomenology'} {'waldheim', 'germany', 'reich', 'husserl', 'schwitters', 'goebbels', 'hegel', 'hesse', 'gring', 'berlin', 'hegels', 'habermas', 'hitler', 'nazi'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_8
  WTF: {'short', 'world', 'writing', 'english', 'mars'} {'steinbeck', 'moorcock', 'crichton', 'verne', 'sagan'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_9
  WTF: {'string', 'words', 'quartet', 'composers', 'works', 'trio', 'da'} {'elgar', 'wk', 'handel', 'shostakovich', 'hoffmann', 'lugosi', 'haydn'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_10
  WTF: {'du', 'psychoanalysis', 'desire', 'time', 'work', 'life', 'des', 'political', 'university', 'published', 'press', 'new'} {'sartre', 'nostradamus', 'paris', 'debussy', 'lacan', 'rousseau', 'erasmus', 'rousseaus', 'merleauponty', 'sade', 'baudelaire', 'deleuze'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_11
  WTF: {'army', 'married', 'daughter', 'military', 'otto', 'chancellor', 'margrave', 'prince', 'emperor', 'iii', 'ii', 'died', 'maternal', 'paternal'} {'germany', 'clausewitz', 'gustavus', 'joachim', 'prussia', 'albert', 'albertus', 'bismarck', 'bismarcks', 'prussian', 'brandenburg', 'saxony', 'frederick', 'dresden'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_12
  WTF: {'army', 'john', 'pp', 'baron', 'union', 'american', 'new'} {'eisenhower', 'rumsfeld', 'carson', 'stuart', 'hancock', 'davis', 'thomas'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_13
  WTF: {'grand', 'career', 'championship', 'lost', 'wickets', 'world'} {'jordan', 'earnhardt', 'agassi', 'muralitharan', 'schumacher', 'hingis'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_14
  WTF: {'uranium', 'scientific', 'work', 'quantum', 'theory', 'physicist', 'institute', 'research', 'radio'} {'bohr', 'meitner', 'fermi', 'wigner', 'planck', 'fuchs', 'marie', 'bardeen', 'marconi'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_15
  WTF: {'script', 'role', 'actor', 'actors', 'directed', 'picture', 'screenplay', 'new'} {'cukor', 'scorsese', 'hitchcocks', 'warren', 'hitchcock', 'mcgilligan', 'cameron', 'cagney'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_16
  WTF: {'surgeon', 'nobel', 'world', 'theory', 'stress', 'vaccination', 'discovery', 'physician'} {'fleming', 'koch', 'pasteur', 'carrel', 'lister', 'jenner', 'edinburgh', 'hutton'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_17
  WTF: {'empereurs', 'japon', 'lady', 'son', 'month', 'clan', 'udaijin', 'sokui'} {'gukansh', 'minamoto', 'nichiren', 'fujiwara', 'titsingh', 'japanese', 'japan', 'varley'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_18
  WTF: {'paint', 'painters', 'french', 'giger', 'millet', 'salon', 'museum'} {'pissarro', 'rodin', 'paris', 'davids', 'rodins', 'monet', 'david'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_19
  WTF: {'war', 'voyage', '2004', 'forces', 'admiral', 'ship', 'navy', 'general', 'lord', 'spanish', 'royal'} {'british', 'drake', 'nelson', 'wellington', 'alexander', 'hibbert', 'montgomery', 'india', 'mountbatten', 'blackbeard', 'sugden'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_20
  WTF: {'conservative', 'john', 'sir', 'crisis', '1939', 'lord', 'foot', 'cabinet', 'parliament'} {'british', 'canada', 'disraeli', 'canadian', 'riel', 'attlee', 'macdonald', 'holt', 'tupper'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_21
  WTF: {'guest', 'movie', 'voice', 'garrison', 'late', 'tonight', 'host', 'played'} {'belushi', 'voight', 'keillor', 'palin', 'letterman', 'coleman', 'leno', 'grammer'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_22
  WTF: {'war', 'expedition', 'civil', 'king', 'city', 'military', 'married', 'la', 'issue', 'doa', 'president', 'troops', 'leader', 'government', 'new'} {'madero', 'alfonso', 'ortega', 'almagro', 'xavier', 'corts', 'cid', 'pizarro', 'daz', 'moctezuma', 'francisco', 'madrid', 'franco', 'mexico', 'francos'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_23
  WTF: {'married', 'isbn', 'kingdom', 'ed', 'pp', 'chronicle', 'iii', 'isles', 'kingship', 'died', 'death', 'ii', 'english', 'saga', 'killed'} {'macbeth', 'selkirk', 'coluim', 'scots', 'kenneth', 'oram', 'alexander', 'scotland', 'maclaurin', 'mel', 'alba', 'malcolm', 'duncan', 'malcolms', 'scottish'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_24
  WTF: {'observatory', 'scientific', 'algebraic', 'geometry', 'planetary', 'academy', 'theorem', 'university', 'published', 'light', 'tables'} {'tycho', 'kepler', 'grothendieck', 'eulers', 'euler', 'caspar', 'rmer', 'napier', 'johannes', 'keplers', 'celsius'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_25
  WTF: {'poets', 'years', 'new', 'later', 'ed', 'work', 'donnes', 'published', 'works', 'poet', 'letters', 'english', 'literature'} {'london', 'alice', 'severn', 'masefield', 'lewis', 'dodgson', 'nash', 'keats', 'housmans', 'shropshire', 'carroll', 'hopkins', 'housman'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_26
  WTF: {'2003', 'series', 'days', 'born', 'sera', '2005', 'new'} {'rosenthal', 'danner', 'naomi', 'kidman', 'anderson', 'melcher', 'doris'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_27
  WTF: {'expedition', 'arctic', 'paintings', 'comics', 'new', 'stories', 'work', 'best', 'life', 'polar', '2005', 'duck', 'award', 'scream', 'museum', 'art'} {'alvar', 'nansen', 'kafkas', 'norway', 'finland', 'ibsen', 'eggum', 'franz', 'munch', 'kafka', 'rasmussen', 'fridtjof', 'barks', 'aalto', 'prideaux', 'munchs'}
  WTF?!?!? 16
  WTF?!?!? 16
topic_28
  WTF: {'scientific', 'john', 'work', 'prize', 'society', 'number', 'university', 'set'} {'reid', 'neumann', 'eddington', 'moseley', 'hilberts', 'hilbert', 'hoyle', 'neumanns'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_29
  WTF: {'trial', 'isbn', 'dictionary', 'reflections', 'pp', 'trials', 'gin', 'fox', 'life', 'children', 'haven', 'published', 'prior', 'press', 'church'} {'yale', 'abbott', 'mead', 'alcott', 'burke', 'bellamy', 'noah', 'connecticut', 'eli', 'mather', 'mathers', 'margaret', 'whitney', 'burkes', 'webster'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_30
  WTF: {'war', 'harbor', 'moon', 'battle', 'manga', 'pearl', 'samurai', 'born', 'navy', 'carrier', 'pacific'} {'akira', 'kahanamoku', 'japanese', 'yamamoto', 'kurosawa', 'fukuyama', 'morita', 'kurosawas', 'japan', 'yamamotos', 'ueshiba'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_31
  WTF: {'army', 'spain', 'tours', 'great', 'son', 'empire', 'iii', 'duc', 'ii', 'duke', 'spanish', 'imperial'} {'martel', 'france', 'italy', 'eugene', 'eugenes', 'europe', 'savoy', 'charlemagne', 'frankish', 'charles', 'louis', 'bernard'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_32
  WTF: {'succession', 'reign', 'vii', 'earl', 'council', 'protestant', 'throne', 'duke', 'marriage', 'ii', 'death', 'kings', 'royal'} {'england', 'elizabeth', 'anne', 'wales', 'edward', 'owain', 'henrys', 'henry', 'charles', 'catherine', 'tudor', 'elizabeths', 'mary'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_33
  WTF: {'married', 'grand', 'ca', 'daughter', 'empress', 'dowager', 'queen', 'family', 'heir', 'sister', 'sons', 'ii', 'death', 'died', 'lands'} {'mieszko', 'bolesaw', 'jadwiga', 'poland', 'feodorovna', 'lithuania', 'hungary', 'leszek', 'krakw', 'miller', 'lithuanian', 'casimir', 'maria', 'mindaugas', 'jadwigas'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_34
  WTF: {'scientists', 'genome', 'behavior', 'self', 'evolution', 'environmentalist', 'carl', 'research', 'chapter'} {'rogers', 'wilson', 'kikuyu', 'rushton', 'venter', 'leakey', 'lomborg', 'louis', 'jensen'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_35
  WTF: {'automobile', 'inventions', 'new', 'energy', 'patent', 'company', 'current', 'light', 'royal', 'automobiles'} {'humphry', 'davys', 'volta', 'karl', 'oliver', 'davy', 'faradays', 'faraday', 'heaviside', 'nikola'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_36
  WTF: {'book', 'cartoonists', 'beat', 'work', 'life', 'road', 'award', 'characters', 'new'} {'thurber', 'abner', 'capp', 'barney', 'simon', 'kerouacs', 'kirby', 'lil', 'capps'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_37
  WTF: {'chart', 'release', 'number', 'artist', 'singles', 'new', 'billboard', 'pop'} {'uk', 'diab', 'mariah', 'careys', 'aaliyah', 'carey', 'enya', 'difranco'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_38
  WTF: {'performed', 'musical', 'film', 'chorus', 'concert', 'requiem', 'libretto', 'works', 'del'} {'rossini', 'morricone', 'milan', 'ennio', 'rossinis', 'verdis', 'giuseppe', 'morricones', 'gioachino'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_39
  WTF: {'rpt', 'description', 'humans', 'grammar', 'sounds', 'linguists', 'english'} {'hockett', 'whorf', 'jones', 'bantu', 'westermann', 'doke', 'diedrich'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_40
  WTF: {'conservative', 'theological', 'book', 'study', 'theology', 'prophets', 'work', 'seminary', 'university', 'rabbis', 'man', 'sabbath', 'studies', 'scholars'} {'abendana', 'heschel', 'jts', 'steinsaltz', 'hebrew', 'jewish', 'neusner', 'neusners', 'judaism', 'kaplans', 'talmud', 'jacob', 'torah', 'kaplan'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_41
  WTF: {'scientific', 'biology', 'ray', 'science', 'society', 'theory', 'animals', 'principles', 'origin', 'geological', 'vol', 'plants'} {'slotten', 'mendel', 'mayr', 'haeckel', 'darwin', 'lyell', 'ernst', 'charles', 'wallace', 'wallaces', 'lyells', 'darwins'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_42
  WTF: {'park', 'designs', 'architectural', 'residential', 'center', 'homes', 'houses', 'new'} {'chihuly', 'wright', 'lloyd', 'lin', 'wrights', 'pei', 'chicago', 'mies'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_43
  WTF: {'signs', 'induction', 'inquiry', 'interpretant', 'knowledge', 'pragmatism', 'sense', 'method'} {'bertrand', 'poppers', 'russell', 'russells', 'peirce', 'peirces', 'popper', 'moore'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_44
  WTF: {'moon', 'united', 'plane', 'grace', 'test', 'navy', 'mach', 'crew'} {'apollo', 'bingham', 'armstrongs', 'aldrin', 'hopper', 'armstrong', 'hansen', 'yeager'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_45
  WTF: {'gene', 'shows', 'featured', 'time', 'song', 'popular', 'golf', 'musicals', 'american'} {'elfman', 'broadway', 'kern', 'crosby', 'crosbys', 'kelly', 'gershwin', 'dowlands', 'bing'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_46
  WTF: {'players', 'hall', 'allstar', 'tigers', 'hit', 'pitched', 'american'} {'youngs', 'greenberg', 'milwaukee', 'mlb', 'rockne', 'cy', 'doubleday'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_47
  WTF: {'burgundy', 'daughter', 'kingdom', 'moors', 'ancestors', 'china', 'iii', 'throne', 'ii', 'infanta'} {'afonso', 'len', 'albuquerque', 'castile', 'portuguese', 'sancho', 'portugal', 'aragon', 'afonsos', 'coimbra'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_48
  WTF: {'bureau', 'relationship', 'sexual', 'office', 'primary', 'vote', 'election', 'march', 'bomb', 'general', 'sentence', 'murder', 'plea', 'parole', 'prison', 'gray'} {'sacramento', 'hoover', 'soliah', 'california', 'lewinsky', 'olson', 'hoovers', 'sla', 'olsons', 'sara', 'heather', 'clinton', 'fbi', 'fargo', 'reno', 'gandy'}
  WTF?!?!? 16
  WTF?!?!? 16
topic_49
  WTF: {'reserve', 'economists', 'public', 'economist', 'economy', 'policy', 'psychology', 'democracy', 'philosophy'} {'milton', 'dewey', 'rothbard', 'friedmans', 'mises', 'deweys', 'murray', 'friedman', 'tobin'}
  WTF?!?!? 9
  WTF?!?!? 9
{'fix': <__main__.FastFixPhiRegularizer object at 0x7fd2d0db2af0>}
Check after fit:
Skipping background topic: background_1.
topic_0
  WTF: {'greek', 'reign', 'time', 'ad', 'century', 'death', 'new', 'god'} {'augustus', 'rome', 'barnes', 'eusebius', 'claudius', 'caligula', 'diocletian', 'tacitus'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_1
  WTF: {'interrogation', 'army', '2002', 'ali', 'empire', 'muslims', 'al', 'government', 'new'} {'afghanistan', 'persian', 'abd', 'rumi', 'cia', 'islamic', 'muhammad', 'zubaydah', 'abu'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_2
  WTF: {'renaissance', 'san', 'father', 'cardinal', 'life', 'saint', 'del', 'st', 'il', 'church', 'new'} {'francis', 'caravaggio', 'calvino', 'florence', 'rome', 'borgia', 'lucrezia', 'marco', 'cesare', 'fellini', 'bruno'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_3
  WTF: {'recording', 'single'} {'elvis', 'presley'}
topic_4
  WTF: {'machine', 'information', 'computers', 'program', 'institute', 'operating', 'interview', 'award', 'mathematics'} {'shannon', 'minsky', 'sanger', 'turing', 'engelbart', 'warwick', 'babbage', 'zuse', 'wikipedia'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_5
  WTF: {'poems', 'short', 'books', 'work', 'wrote', 'family', 'story', 'university', 'writing', 'press'} {'shelleys', 'tolkien', 'lewis', 'shelley', 'anne', 'jane', 'austen', 'dickens', 'wollstonecraft', 'mary'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_6
  WTF: {'war', 'army', 'military', 'film', 'committee', 'state', 'later', 'time', 'world', 'life', 'revolution', 'government', 'order', 'new', 'central'} {'russian', 'philby', 'moscow', 'trotsky', 'khmelnytsky', 'alexander', 'chekhov', 'stalin', 'beria', 'gorbachev', 'sakharov', 'tito', 'kasparov', 'yeltsin', 'russia'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_7
  WTF: {'war', 'jews', 'state', 'reason', 'theory', 'party', 'political', 'von', 'logic', 'published', 'social', 'und', 'minister', 'phenomenology'} {'waldheim', 'germany', 'reich', 'husserl', 'schwitters', 'goebbels', 'hegel', 'hesse', 'gring', 'berlin', 'hegels', 'habermas', 'hitler', 'nazi'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_8
  WTF: {'short', 'world', 'writing', 'english', 'mars'} {'steinbeck', 'moorcock', 'crichton', 'verne', 'sagan'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_9
  WTF: {'string', 'words', 'quartet', 'composers', 'works', 'trio', 'da'} {'elgar', 'wk', 'handel', 'shostakovich', 'hoffmann', 'lugosi', 'haydn'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_10
  WTF: {'du', 'psychoanalysis', 'desire', 'time', 'work', 'life', 'des', 'political', 'university', 'published', 'press', 'new'} {'sartre', 'nostradamus', 'paris', 'debussy', 'lacan', 'rousseau', 'erasmus', 'rousseaus', 'merleauponty', 'sade', 'baudelaire', 'deleuze'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_11
  WTF: {'army', 'married', 'daughter', 'military', 'otto', 'chancellor', 'margrave', 'prince', 'emperor', 'iii', 'ii', 'died', 'maternal', 'paternal'} {'germany', 'clausewitz', 'gustavus', 'joachim', 'prussia', 'albert', 'albertus', 'bismarck', 'bismarcks', 'prussian', 'brandenburg', 'saxony', 'frederick', 'dresden'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_12
  WTF: {'army', 'john', 'pp', 'baron', 'union', 'american', 'new'} {'eisenhower', 'rumsfeld', 'carson', 'stuart', 'hancock', 'davis', 'thomas'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_13
  WTF: {'grand', 'career', 'championship', 'lost', 'wickets', 'world'} {'jordan', 'earnhardt', 'agassi', 'muralitharan', 'schumacher', 'hingis'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_14
  WTF: {'uranium', 'scientific', 'work', 'quantum', 'theory', 'physicist', 'institute', 'research', 'radio'} {'bohr', 'meitner', 'fermi', 'wigner', 'planck', 'fuchs', 'marie', 'bardeen', 'marconi'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_15
  WTF: {'script', 'role', 'actor', 'actors', 'directed', 'picture', 'screenplay', 'new'} {'cukor', 'scorsese', 'hitchcocks', 'warren', 'hitchcock', 'mcgilligan', 'cameron', 'cagney'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_16
  WTF: {'surgeon', 'nobel', 'world', 'theory', 'stress', 'vaccination', 'discovery', 'physician'} {'fleming', 'koch', 'pasteur', 'carrel', 'lister', 'jenner', 'edinburgh', 'hutton'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_17
  WTF: {'empereurs', 'japon', 'lady', 'son', 'month', 'clan', 'udaijin', 'sokui'} {'gukansh', 'minamoto', 'nichiren', 'fujiwara', 'titsingh', 'japanese', 'japan', 'varley'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_18
  WTF: {'paint', 'painters', 'french', 'giger', 'millet', 'salon', 'museum'} {'pissarro', 'rodin', 'paris', 'davids', 'rodins', 'monet', 'david'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_19
  WTF: {'war', 'voyage', '2004', 'forces', 'admiral', 'ship', 'navy', 'general', 'lord', 'spanish', 'royal'} {'british', 'drake', 'nelson', 'wellington', 'alexander', 'hibbert', 'montgomery', 'india', 'mountbatten', 'blackbeard', 'sugden'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_20
  WTF: {'conservative', 'john', 'sir', 'crisis', '1939', 'lord', 'foot', 'cabinet', 'parliament'} {'british', 'canada', 'disraeli', 'canadian', 'riel', 'attlee', 'macdonald', 'holt', 'tupper'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_21
  WTF: {'guest', 'movie', 'voice', 'garrison', 'late', 'tonight', 'host', 'played'} {'belushi', 'voight', 'keillor', 'palin', 'letterman', 'coleman', 'leno', 'grammer'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_22
  WTF: {'war', 'expedition', 'civil', 'king', 'city', 'military', 'married', 'la', 'issue', 'doa', 'president', 'troops', 'leader', 'government', 'new'} {'madero', 'alfonso', 'ortega', 'almagro', 'xavier', 'corts', 'cid', 'pizarro', 'daz', 'moctezuma', 'francisco', 'madrid', 'franco', 'mexico', 'francos'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_23
  WTF: {'married', 'isbn', 'kingdom', 'ed', 'pp', 'chronicle', 'iii', 'isles', 'kingship', 'died', 'death', 'ii', 'english', 'saga', 'killed'} {'macbeth', 'selkirk', 'coluim', 'scots', 'kenneth', 'oram', 'alexander', 'scotland', 'maclaurin', 'mel', 'alba', 'malcolm', 'duncan', 'malcolms', 'scottish'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_24
  WTF: {'observatory', 'scientific', 'algebraic', 'geometry', 'planetary', 'academy', 'theorem', 'university', 'published', 'light', 'tables'} {'tycho', 'kepler', 'grothendieck', 'eulers', 'euler', 'caspar', 'rmer', 'napier', 'johannes', 'keplers', 'celsius'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_25
  WTF: {'poets', 'years', 'new', 'later', 'ed', 'work', 'donnes', 'published', 'works', 'poet', 'letters', 'english', 'literature'} {'london', 'alice', 'severn', 'masefield', 'lewis', 'dodgson', 'nash', 'keats', 'housmans', 'shropshire', 'carroll', 'hopkins', 'housman'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_26
  WTF: {'2003', 'series', 'days', 'born', 'sera', '2005', 'new'} {'rosenthal', 'danner', 'naomi', 'kidman', 'anderson', 'melcher', 'doris'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_27
  WTF: {'expedition', 'arctic', 'paintings', 'comics', 'new', 'stories', 'work', 'best', 'life', 'polar', '2005', 'duck', 'award', 'scream', 'museum', 'art'} {'alvar', 'nansen', 'kafkas', 'norway', 'finland', 'ibsen', 'eggum', 'franz', 'munch', 'kafka', 'rasmussen', 'fridtjof', 'barks', 'aalto', 'prideaux', 'munchs'}
  WTF?!?!? 16
  WTF?!?!? 16
topic_28
  WTF: {'scientific', 'john', 'work', 'prize', 'society', 'number', 'university', 'set'} {'reid', 'neumann', 'eddington', 'moseley', 'hilberts', 'hilbert', 'hoyle', 'neumanns'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_29

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7fd2cda4bf70>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7fd2baf3bf10>}
{'perplexity': 314747.8125, 'coherence_20': 0.7935957315542084, 'diversity_euclidean': 0.03414482933100465, 'diversity_jensenshannon': 0.6528400512264001, 'diversity_hellinger': 0.7661158429765218, 'diversity_cosine': 0.7355183530777205, 'fair_ppl_free': 2774.225830078125, 'fair_ppl_fix': 318028.625, 'unfair_ppl_banklike': 314747.8125}
{'num_topics': 51, 'num_common_words': 65750, 'num_model_words': 155407, 'num_bt_words': 135939, 'top_diffs': [{'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 32, 'lost_bt': 16, 'lost_model': 16}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 32, 'lost_bt': 16, 'lost_model': 16}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}]}
18
Num model topics: 52.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
  WTF: {'interrogation', 'army', '2002', 'ali', 'empire', 'muslims', 'al', 'government', 'new'} {'afghanistan', 'persian', 'abd', 'rumi', 'cia', 'islamic', 'muhammad', 'zubaydah', 'abu'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_1
  WTF: {'recording', 'single'} {'elvis', 'presley'}
topic_2
  WTF: {'machine', 'information', 'computers', 'language', 'institute', 'operating', 'interview', 'award', 'mathematics'} {'shannon', 'minsky', 'sanger', 'turing', 'engelbart', 'warwick', 'babbage', 'zuse', 'wikipedia'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_3
  WTF: {'string', 'words', 'concerto', 'composers', 'trio', 'gamba'} {'elgar', 'wk', 'handel', 'shostakovich', 'lugosi', 'haydn'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_4
  WTF: {'army', 'chess', 'military', 'film', 'committee', 'state', 'time', 'world', 'revolution', 'government', 'march', 'ii', 'order', 'new'} {'russian', 'moscow', 'trotsky', 'khmelnytsky', 'alexander', 'nicholas', 'stalin', 'chekhov', 'beria', 'gorbachev', 'tito', 'kasparov', 'yeltsin', 'russia'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_5
  WTF: {'annals', 'emperors', 'potter', 'caesars', 'life', 'ce', 'gibbon', 'senate', 'ad', 'death', 'caesar', 'imperial'} {'augustus', 'rome', 'barnes', 'julian', 'constantius', 'claudius', 'caligula', 'tiberius', 'hadrian', 'diocletian', 'tacitus', 'suetonius'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_6
  WTF: {'pope', 'della', 'pietro', 'film', 'marble', 'san', 'work', 'life', 'painting', 'del', 'il', 'new'} {'giordano', 'caravaggios', 'caravaggio', 'florence', 'rome', 'medici', 'lucrezia', 'borgia', 'angelico', 'fellini', 'bruno', 'lorenzo'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_7
  WTF: {'army', 'jews', 'state', 'work', 'public', 'party', 'theory', 'von', 'logic', 'nazis', 'university', 'senate', 'und', 'social', 'minister'} {'waldheim', 'germany', 'mccarthy', 'husserl', 'schwitters', 'reich', 'goebbels', 'hesse', 'gring', 'berlin', 'habermas', 'hitlers', 'hitler', 'nazi', 'mccarthys'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_8
  WTF: {'book', 'books', 'world', 'english', 'mars'} {'moorcock', 'crichton', 'verne', 'pohl', 'hugo'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_9
  WTF: {'designs', 'modern', 'paint', 'landscape', 'design', 'works', 'artists', 'new', 'painted'} {'wright', 'lloyd', 'rodin', 'paris', 'wrights', 'monet', 'david', 'goya', 'pollock'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_10
  WTF: {'psychoanalysis', 'desire', 'perception', 'time', 'work', 'life', 'des', 'political', 'published', 'press', 'new'} {'sartre', 'nostradamus', 'paris', 'lacan', 'rousseau', 'satie', 'rousseaus', 'merleauponty', 'sade', 'baudelaire', 'deleuze'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_11
  WTF: {'mathematicians', 'proof', 'scientific', 'geometry', 'space', 'physics', 'university', 'astronomical', 'published', 'set', 'cohomology'} {'kepler', 'grothendieck', 'eulers', 'neumann', 'keplers', 'gdel', 'atiyah', 'euler', 'hilberts', 'hilbert', 'hoyle'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_12
  WTF: {'grand', 'career', 'championship', 'lost', 'wickets', 'world'} {'jordan', 'earnhardt', 'agassi', 'muralitharan', 'schumacher', 'hingis'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_13
  WTF: {'surgery', 'surgeon', 'nobel', 'world', 'theory', 'archaeology', 'stress', 'vaccination', 'physician', 'eccles'} {'fleming', 'london', 'koch', 'pasteur', 'carrel', 'kenyon', 'lister', 'jenner', 'edinburgh', 'hutton'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_14
  WTF: {'army', 'married', 'chancellor', 'military', 'margrave', 'prince', 'emperor', 'iii', 'ii', 'magnus', 'died', 'maternal', 'insurance', 'paternal'} {'clausewitz', 'austria', 'gustavus', 'joachim', 'prussia', 'albert', 'albertus', 'bismarck', 'bismarcks', 'prussian', 'brandenburg', 'saxony', 'frederick', 'dresden'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_15
  WTF: {'john', 'cavalry', 'pp', 'baron', 'supreme', 'union', 'general', 'new'} {'eisenhower', 'rumsfeld', 'carson', 'stuart', 'quayle', 'hancock', 'davis', 'thomas'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_16
  WTF: {'war', 'empereurs', 'senso', 'japon', 'lady', 'clan', 'month', 'emperors', 'son', 'throne', 'court'} {'chinese', 'minamoto', 'fujiwara', 'chiang', 'titsingh', 'kaishek', 'japanese', 'japan', 'dengs', 'deng', 'varley'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_17
  WTF: {'role', 'directors', 'time', 'actors', 'directed', 'received', 'picture', 'brothers'} {'coen', 'cukor', 'scorsese', 'warren', 'david', 'york', 'mcgilligan', 'cagney'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_18
  WTF: {'allied', 'john', 'voyage', 'admiral', 'attack', 'ships', 'navy', 'lord', 'royal'} {'british', 'drake', 'nelson', 'wellington', 'jay', 'montgomery', 'mountbatten', 'rommel', 'rommels'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_19
  WTF: {'pope', 'saints', 'monastery', 'john', 'orthodox', 'medieval', 'writings', 'life', 'catholic', 'history', 'works', 'sally', 'english', 'christian'} {'chrysostom', 'bedes', 'anthony', 'benedict', 'athanasius', 'anselm', 'bede', 'canterbury', 'ephrem', 'dunstan', 'alexandria', 'augustine', 'crowley', 'martin'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_20
  WTF: {'guest', 'episodes', 'series', 'movie', 'globe', 'voice', 'night', 'tonight', 'played'} {'jones', 'belushi', 'voight', 'keillor', 'palin', 'letterman', 'coleman', 'leno', 'grammer'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_21
  WTF: {'conservative', 'john', 'sir', 'crisis', '1939', 'lord', 'foot', 'cabinet', 'parliament'} {'british', 'canada', 'disraeli', 'canadian', 'riel', 'attlee', 'macdonald', 'holt', 'tupper'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_22
  WTF: {'war', 'expedition', 'civil', 'king', 'city', 'military', 'married', 'la', 'issue', 'doa', 'president', 'troops', 'leader', 'government', 'new'} {'madero', 'alfonso', 'ortega', 'almagro', 'xavier', 'corts', 'cid', 'aztec', 'pizarro', 'daz', 'francisco', 'madrid', 'franco', 'mexico', 'moctezuma'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_23
  WTF: {'2003', 'beauty', 'days', 'globe', '2005', 'new', 'golden'} {'doris', 'danner', 'carangi', 'kidman', 'anderson', 'theron', 'naomi'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_24
  WTF: {'isbn', 'woman', 'poems', 'short', 'spark', 'stories', 'books', 'introduction', 'life', 'family', 'fiction', 'story', 'works', 'letters', 'press', 'women'} {'seymour', 'charlotte', 'shelleys', 'christie', 'shelley', 'anne', 'bronts', 'godwin', 'jane', 'austens', 'austen', 'tomalin', 'bront', 'wollstonecraft', 'mary', 'percy'}
  WTF?!?!? 16
  WTF?!?!? 16
topic_25
  WTF: {'army', 'spain', 'tours', 'great', 'son', 'empire', 'iii', 'duc', 'ii', 'duke', 'spanish', 'imperial'} {'martel', 'france', 'italy', 'eugene', 'eugenes', 'europe', 'savoy', 'charlemagne', 'frankish', 'charles', 'louis', 'bernard'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_26
  WTF: {'isbn', 'kingdom', 'reign', 'prophecy', 'ed', 'pp', 'chronicle', 'iii', 'isles', 'ii', 'death', 'died', 'saga', 'killed'} {'macbeth', 'coluim', 'scots', 'kenneth', 'oram', 'alexander', 'scotland', 'domnall', 'mel', 'alba', 'malcolm', 'duncan', 'malcolms', 'scottish'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_27
  WTF: {'isbn', 'dictionary', 'years', 'meeting', 'trials', 'gin', 'children', 'witch', 'haven', 'meetings', 'published', 'church', 'spelling', 'christian'} {'yale', 'abbott', 'mead', 'alcott', 'foxs', 'bellamy', 'connecticut', 'eli', 'mather', 'margaret', 'whitney', 'quakers', 'webster', 'nickalls'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_28
  WTF: {'war', 'harbor', 'moon', 'battle', 'manga', 'pearl', 'samurai', 'born', 'navy', 'carrier', 'american', 'pacific'} {'tokyo', 'nichiren', 'akira', 'japanese', 'yamamoto', 'kurosawa', 'fukuyama', 'morita', 'kurosawas', 'japan', 'yamamotos', 'ueshiba'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_29
  WTF: {'original', 'logos', 'things', 'time', 'christian', 'work', 'life', 'fragments', 'history', 'sin', 'death', 'medical', 'nature'} {'aurelius', 'galens', 'augustines', 'heraclitus', 'galen', 'eusebius', 'verus', 'augustine', 'dk', 'latin', 'marcus', 'diogenes', 'epicurus'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_30
  WTF: {'comics', 'paintings', 'christian', 'work', 'life', 'story', 'polar', 'published', 'little', 'works', 'duck', '2005', 'new', 'art'} {'alvar', 'andersens', 'nansen', 'kafkas', 'norway', 'ibsen', 'eggum', 'franz', 'munch', 'kafka', 'aalto', 'prideaux', 'andersen', 'munchs'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_31
  WTF: {'succession', 'reign', 'vii', 'earl', 'council', 'protestant', 'throne', 'duke', 'marriage', 'ii', 'death', 'kings', 'royal'} {'england', 'elizabeth', 'anne', 'wales', 'edward', 'owain', 'henrys', 'henry', 'charles', 'catherine', 'tudor', 'elizabeths', 'mary'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_32
  WTF: {'professor', 'scientists', 'nobel', 'prize', 'theory', 'einstein', 'physicist', 'institute', 'mechanics', 'research', 'chemistry', 'german'} {'bohr', 'meitner', 'niels', 'plancks', 'copenhagen', 'planck', 'heisenberg', 'erwin', 'schrdinger', 'fuchs', 'hahn', 'wigner'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_33
  WTF: {'scientists', 'genome', 'behavior', 'skeptical', 'self', 'work', 'environmentalist', 'carl', 'research', 'chapter'} {'rogers', 'wilson', 'kikuyu', 'rushton', 'venter', 'leakey', 'lomborg', 'louis', 'snyder', 'jensen'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_34
  WTF: {'wolf', 'father', 'life', 'italian', 'feast', 'judges', 'roman', 'order', 'ibid', 'new', 'god'} {'polidori', 'francis', 'alberoni', 'bellarmine', 'rome', 'mychal', 'contarini', 'assisi', 'porziuncola', 'cardano', 'vampyre'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_35
  WTF: {'married', 'ca', 'queen', 'emperor', 'dukes', 'wife', 'sons', 'ii', 'death', 'died', 'iv', 'order', 'brother'} {'mieszko', 'poland', 'bolesaw', 'jadwiga', 'lithuania', 'hungary', 'krakw', 'kazimierz', 'lithuanian', 'casimir', 'mindaugas', 'jadwigas', 'sigismund'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_36
  WTF: {'book', '2008', 'strips', 'cartoonists', 'work', 'marvel', 'op', 'award', 'characters', 'adventures', 'art'} {'tintin', 'abner', 'capp', 'barney', 'goddin', 'simon', 'philippe', 'kirby', 'lil', 'herg', 'capps'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_37
  WTF: {'biography', 'collected', 'written', 'joy', 'work', 'weird', 'life', 'monthly', 'literary', 'writing', 'press', 'new', 'novel'} {'lewiss', 'melville', 'hawthorne', 'lewis', 'melvilles', 'conrad', 'williams', 'dickenss', 'conrads', 'nathaniel', 'dickens', 'charles', 'derleth'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_38
  WTF: {'rpt', 'description', 'humans', 'grammar', 'sounds', 'linguists', 'english'} {'hockett', 'whorf', 'jones', 'bantu', 'westermann', 'doke', 'diedrich'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_39
  WTF: {'daughter', 'navigator', 'coast', 'prince', 'mother', 'iii', 'ii', 'expeditions', 'infanta', 'infante'} {'afonso', 'len', 'albuquerque', 'castile', 'portuguese', 'sancho', 'henry', 'portugal', 'aragon', 'coimbra'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_40
  WTF: {'hot', 'pg', 'release', 'number', 'rb', 'singles', 'pop'} {'uk', 'mariah', 'careys', 'aaliyah', 'carey', 'enya', 'difranco'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_41
  WTF: {'moon', 'united', 'plane', 'grace', 'test', 'navy', 'mach', 'crew'} {'apollo', 'bingham', 'armstrongs', 'aldrin', 'hopper', 'armstrong', 'hansen', 'yeager'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_42
  WTF: {'induction', 'cp', 'inquiry', 'interpretant', 'knowledge', 'pragmatism', 'work', 'logical', 'method'} {'skinner', 'bertrand', 'poppers', 'russell', 'russells', 'peirce', 'peirces', 'popper', 'moore'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_43
  WTF: {'experiments', 'scientific', 'atomic', 'chemical', 'work', 'prize', 'transistor', 'discovered', 'chemist', 'university', 'electric', 'laboratory', 'royal'} {'humphry', 'davys', 'fermi', 'volta', 'brattain', 'enrico', 'davy', 'fermis', 'faradays', 'faraday', 'shockley', 'bardeen', 'langmuir'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_44
  WTF: {'conservative', 'theological', 'study', 'law', 'theology', 'prophets', 'work', 'university', 'rabbis', 'man', 'sabbath', 'studies', 'scholars'} {'heschel', 'jts', 'steinsaltz', 'hebrew', 'jewish', 'neusner', 'kushner', 'judaism', 'kaplans', 'neusners', 'talmud', 'torah', 'kaplan'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_45
  WTF: {'cancer', 'bureau', 'united', 'sexual', 'office', 'vote', 'election', 'general', 'states', 'awareness'} {'sacramento', 'hoover', 'lewinsky', 'eastman', 'hoovers', 'clinton', 'laura', 'fargo', 'reno', 'gandy'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_46
  WTF: {'book', 'portrait', 'new', 'ed', 'work', 'english', 'life', 'press', 'university', 'published', 'poet', 'man', 'nonsense', 'verse'} {'shropshire', 'masefield', 'lear', 'ulysses', 'joyce', 'nash', 'housman', 'housmans', 'finnegans', 'hopkinss', 'hopkins', 'dublin', 'joyces', 'james'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_47
  WTF: {'scientific', 'biology', 'science', 'origin', 'society', 'theory', 'animals', 'principles', 'history', 'geological', 'vol'} {'slotten', 'mayr', 'haeckel', 'darwin', 'lyell', 'ernst', 'charles', 'wallace', 'wallaces', 'lyells', 'darwins'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_48
  WTF: {'reserve', 'freedom', 'economists', 'theory', 'von', 'university', 'economy', 'institute', 'policy', 'research'} {'rothbard', 'friedmans', 'hayek', 'mises', 'murray', 'friedman', 'drexel', 'milken', 'tobin', 'hayeks'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_49
  WTF: {'players', 'hall', 'allstar', 'tigers', 'hit', 'pitched', 'american'} {'youngs', 'greenberg', 'milwaukee', 'mlb', 'rockne', 'cy', 'doubleday'}
  WTF?!?!? 7
  WTF?!?!? 7
{'fix': <__main__.FastFixPhiRegularizer object at 0x7fd2d2140280>}
Check after fit:
Skipping background topic: background_1.
topic_0
  WTF: {'interrogation', 'army', '2002', 'ali', 'empire', 'muslims', 'al', 'government', 'new'} {'afghanistan', 'persian', 'abd', 'rumi', 'cia', 'islamic', 'muhammad', 'zubaydah', 'abu'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_1
  WTF: {'recording', 'single'} {'elvis', 'presley'}
topic_2
  WTF: {'machine', 'information', 'computers', 'language', 'institute', 'operating', 'interview', 'award', 'mathematics'} {'shannon', 'minsky', 'sanger', 'turing', 'engelbart', 'warwick', 'babbage', 'zuse', 'wikipedia'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_3
  WTF: {'string', 'words', 'concerto', 'composers', 'trio', 'gamba'} {'elgar', 'wk', 'handel', 'shostakovich', 'lugosi', 'haydn'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_4
  WTF: {'army', 'chess', 'military', 'film', 'committee', 'state', 'time', 'world', 'revolution', 'government', 'march', 'ii', 'order', 'new'} {'russian', 'moscow', 'trotsky', 'khmelnytsky', 'alexander', 'nicholas', 'stalin', 'chekhov', 'beria', 'gorbachev', 'tito', 'kasparov', 'yeltsin', 'russia'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_5
  WTF: {'annals', 'emperors', 'potter', 'caesars', 'life', 'ce', 'gibbon', 'senate', 'ad', 'death', 'caesar', 'imperial'} {'augustus', 'rome', 'barnes', 'julian', 'constantius', 'claudius', 'caligula', 'tiberius', 'hadrian', 'diocletian', 'tacitus', 'suetonius'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_6
  WTF: {'pope', 'della', 'pietro', 'film', 'marble', 'san', 'work', 'life', 'painting', 'del', 'il', 'new'} {'giordano', 'caravaggios', 'caravaggio', 'florence', 'rome', 'medici', 'lucrezia', 'borgia', 'angelico', 'fellini', 'bruno', 'lorenzo'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_7
  WTF: {'army', 'jews', 'state', 'work', 'public', 'party', 'theory', 'von', 'logic', 'nazis', 'university', 'senate', 'und', 'social', 'minister'} {'waldheim', 'germany', 'mccarthy', 'husserl', 'schwitters', 'reich', 'goebbels', 'hesse', 'gring', 'berlin', 'habermas', 'hitlers', 'hitler', 'nazi', 'mccarthys'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_8
  WTF: {'book', 'books', 'world', 'english', 'mars'} {'moorcock', 'crichton', 'verne', 'pohl', 'hugo'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_9
  WTF: {'designs', 'modern', 'paint', 'landscape', 'design', 'works', 'artists', 'new', 'painted'} {'wright', 'lloyd', 'rodin', 'paris', 'wrights', 'monet', 'david', 'goya', 'pollock'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_10
  WTF: {'psychoanalysis', 'desire', 'perception', 'time', 'work', 'life', 'des', 'political', 'published', 'press', 'new'} {'sartre', 'nostradamus', 'paris', 'lacan', 'rousseau', 'satie', 'rousseaus', 'merleauponty', 'sade', 'baudelaire', 'deleuze'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_11
  WTF: {'mathematicians', 'proof', 'scientific', 'geometry', 'space', 'physics', 'university', 'astronomical', 'published', 'set', 'cohomology'} {'kepler', 'grothendieck', 'eulers', 'neumann', 'keplers', 'gdel', 'atiyah', 'euler', 'hilberts', 'hilbert', 'hoyle'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_12
  WTF: {'grand', 'career', 'championship', 'lost', 'wickets', 'world'} {'jordan', 'earnhardt', 'agassi', 'muralitharan', 'schumacher', 'hingis'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_13
  WTF: {'surgery', 'surgeon', 'nobel', 'world', 'theory', 'archaeology', 'stress', 'vaccination', 'physician', 'eccles'} {'fleming', 'london', 'koch', 'pasteur', 'carrel', 'kenyon', 'lister', 'jenner', 'edinburgh', 'hutton'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_14
  WTF: {'army', 'married', 'chancellor', 'military', 'margrave', 'prince', 'emperor', 'iii', 'ii', 'magnus', 'died', 'maternal', 'insurance', 'paternal'} {'clausewitz', 'austria', 'gustavus', 'joachim', 'prussia', 'albert', 'albertus', 'bismarck', 'bismarcks', 'prussian', 'brandenburg', 'saxony', 'frederick', 'dresden'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_15
  WTF: {'john', 'cavalry', 'pp', 'baron', 'supreme', 'union', 'general', 'new'} {'eisenhower', 'rumsfeld', 'carson', 'stuart', 'quayle', 'hancock', 'davis', 'thomas'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_16
  WTF: {'war', 'empereurs', 'senso', 'japon', 'lady', 'clan', 'month', 'emperors', 'son', 'throne', 'court'} {'chinese', 'minamoto', 'fujiwara', 'chiang', 'titsingh', 'kaishek', 'japanese', 'japan', 'dengs', 'deng', 'varley'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_17
  WTF: {'role', 'directors', 'time', 'actors', 'directed', 'received', 'picture', 'brothers'} {'coen', 'cukor', 'scorsese', 'warren', 'david', 'york', 'mcgilligan', 'cagney'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_18
  WTF: {'allied', 'john', 'voyage', 'admiral', 'attack', 'ships', 'navy', 'lord', 'royal'} {'british', 'drake', 'nelson', 'wellington', 'jay', 'montgomery', 'mountbatten', 'rommel', 'rommels'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_19
  WTF: {'pope', 'saints', 'monastery', 'john', 'orthodox', 'medieval', 'writings', 'life', 'catholic', 'history', 'works', 'sally', 'english', 'christian'} {'chrysostom', 'bedes', 'anthony', 'benedict', 'athanasius', 'anselm', 'bede', 'canterbury', 'ephrem', 'dunstan', 'alexandria', 'augustine', 'crowley', 'martin'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_20
  WTF: {'guest', 'episodes', 'series', 'movie', 'globe', 'voice', 'night', 'tonight', 'played'} {'jones', 'belushi', 'voight', 'keillor', 'palin', 'letterman', 'coleman', 'leno', 'grammer'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_21
  WTF: {'conservative', 'john', 'sir', 'crisis', '1939', 'lord', 'foot', 'cabinet', 'parliament'} {'british', 'canada', 'disraeli', 'canadian', 'riel', 'attlee', 'macdonald', 'holt', 'tupper'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_22
  WTF: {'war', 'expedition', 'civil', 'king', 'city', 'military', 'married', 'la', 'issue', 'doa', 'president', 'troops', 'leader', 'government', 'new'} {'madero', 'alfonso', 'ortega', 'almagro', 'xavier', 'corts', 'cid', 'aztec', 'pizarro', 'daz', 'francisco', 'madrid', 'franco', 'mexico', 'moctezuma'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_23
  WTF: {'2003', 'beauty', 'days', 'globe', '2005', 'new', 'golden'} {'doris', 'danner', 'carangi', 'kidman', 'anderson', 'theron', 'naomi'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_24
  WTF: {'isbn', 'woman', 'poems', 'short', 'spark', 'stories', 'books', 'introduction', 'life', 'family', 'fiction', 'story', 'works', 'letters', 'press', 'women'} {'seymour', 'charlotte', 'shelleys', 'christie', 'shelley', 'anne', 'bronts', 'godwin', 'jane', 'austens', 'austen', 'tomalin', 'bront', 'wollstonecraft', 'mary', 'percy'}
  WTF?!?!? 16
  WTF?!?!? 16
topic_25
  WTF: {'army', 'spain', 'tours', 'great', 'son', 'empire', 'iii', 'duc', 'ii', 'duke', 'spanish', 'imperial'} {'martel', 'france', 'italy', 'eugene', 'eugenes', 'europe', 'savoy', 'charlemagne', 'frankish', 'charles', 'louis', 'bernard'}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7fd2c2010ac0>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7fd2166b2dc0>}
{'perplexity': 369390.15625, 'coherence_20': 0.7442846403315648, 'diversity_euclidean': 0.033070706739948566, 'diversity_jensenshannon': 0.6519142153384461, 'diversity_hellinger': 0.7651115985705028, 'diversity_cosine': 0.7292298071190071, 'fair_ppl_free': 2771.722900390625, 'fair_ppl_fix': 302218.125, 'unfair_ppl_banklike': 369390.15625}
{'num_topics': 52, 'num_common_words': 65750, 'num_model_words': 155407, 'num_bt_words': 135939, 'top_diffs': [{'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 32, 'lost_bt': 16, 'lost_model': 16}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}]}
19
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
  WTF: {'academy', 'episode', 'career', '2008'} {'hitchcock', 'paul', 'robeson', 'cagney'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_1
  WTF: {'interrogation', 'army', '2002', 'ali', 'empire', 'muslims', 'al', 'government', 'new'} {'afghanistan', 'persian', 'abd', 'rumi', 'cia', 'islamic', 'muhammad', 'zubaydah', 'abu'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_2
  WTF: {'renaissance', 'san', 'father', 'cardinal', 'life', 'works', 'del', 'st', 'il', 'church', 'new'} {'francis', 'caravaggio', 'calvino', 'florence', 'rome', 'borgia', 'lucrezia', 'marco', 'cesare', 'fellini', 'bruno'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_3
  WTF: {'recording', 'single'} {'elvis', 'presley'}
topic_4
  WTF: {'war', 'married', 'great', 'daughter', 'military', 'otto', 'polish', 'prince', 'emperor', 'von', 'died', 'death', 'maternal'} {'mieszko', 'poland', 'hungary', 'prussia', 'albert', 'bismarck', 'brandenburg', 'prussian', 'saxony', 'frederick', 'casimir', 'alfred', 'alfreds'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_5
  WTF: {'senso', 'military', 'month', 'clan', 'emperors', 'son', 'manga', 'empress', 'throne', 'court', 'brown', 'sailor'} {'minamoto', 'nichiren', 'chiang', 'fujiwara', 'titsingh', 'japanese', 'japan', 'yamamoto', 'kaunda', 'kurosawa', 'deng', 'varley'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_6
  WTF: {'machine', 'information', 'computers', 'language', 'work', 'institute', 'operating', 'interview', 'award'} {'shannon', 'minsky', 'sanger', 'turing', 'engelbart', 'warwick', 'babbage', 'zuse', 'wikipedia'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_7
  WTF: {'war', 'army', 'chess', 'military', 'film', 'committee', 'state', 'time', 'world', 'revolution', 'government', 'march', 'ii', 'order', 'new'} {'russian', 'moscow', 'trotsky', 'khmelnytsky', 'alexander', 'nicholas', 'stalin', 'chekhov', 'beria', 'gorbachev', 'sakharov', 'tito', 'kasparov', 'yeltsin', 'russia'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_8
  WTF: {'dio', 'annals', 'emperors', 'potter', 'caesars', 'life', 'ce', 'senate', 'ad', 'death', 'ancient', 'caesar', 'imperial'} {'augustus', 'rome', 'barnes', 'domitian', 'julian', 'constantius', 'claudius', 'caligula', 'tiberius', 'odahl', 'diocletian', 'tacitus', 'suetonius'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_9
  WTF: {'professor', 'scientific', 'chemical', 'work', 'science', 'quantum', 'theory', 'institute', 'research'} {'bohr', 'meitner', 'fermi', 'davy', 'planck', 'faraday', 'fuchs', 'marie', 'marconi'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_10
  WTF: {'world', 'english', 'books', 'mars'} {'steinbeck', 'crichton', 'verne', 'moorcock'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_11
  WTF: {'musical', 'string', 'words', 'quartet', 'cello', 'trio', 'da'} {'elgar', 'wk', 'handel', 'shostakovich', 'hoffmann', 'lugosi', 'haydn'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_12
  WTF: {'hill', 'hearings', 'united', 'american', 'baron', 'pp', 'supreme', 'union', 'justice', 'beacon'} {'lee', 'carson', 'jay', 'stuart', 'oswald', 'warren', 'hancock', 'davis', 'ruby', 'thomas'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_13
  WTF: {'grand', 'career', 'championship', 'lost', 'wickets', 'world'} {'jordan', 'earnhardt', 'agassi', 'muralitharan', 'schumacher', 'hingis'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_14
  WTF: {'book', 'cartoonist', 'years', 'later', 'work', 'bubbles', 'published', 'al', 'new', 'poem', 'art'} {'thurber', 'abner', 'capp', 'masefield', 'dodgson', 'kirby', 'keats', 'lil', 'carroll', 'housman', 'capps'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_15
  WTF: {'scientific', 'behavior', 'work', 'knowledge', 'object', 'society', 'philosophical', 'logical', 'published', 'social', 'psychology', 'research', 'sign'} {'dewey', 'skinner', 'chomsky', 'rothbard', 'bertrand', 'hayek', 'russell', 'russells', 'peirce', 'peirces', 'friedman', 'milken', 'popper'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_16
  WTF: {'greek', 'saints', 'tours', 'book', 'writings', 'life', 'bishop', 'works', 'roman', 'chapter', 'god', 'heresies'} {'chrysostom', 'athanasius', 'anthony', 'benedict', 'luke', 'josephus', 'irenaeus', 'ephrem', 'alexandria', 'jerome', 'cyril', 'martin'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_17
  WTF: {'allied', 'voyage', 'admiral', 'ship', 'attack', 'ships', 'navy', 'lord', 'royal'} {'british', 'drake', 'nelson', 'wellington', 'montgomery', 'mountbatten', 'rommel', 'sugden', 'rommels'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_18
  WTF: {'medium', 'painters', 'french', 'giger', 'millet', 'works', 'museum'} {'pissarro', 'rodin', 'paris', 'davids', 'rodins', 'monet', 'david'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_19
  WTF: {'marquis', 'desire', 'subject', 'perception', 'work', 'political', 'university', 'published', 'works', 'new', 'symbolic'} {'sartre', 'nostradamus', 'paris', 'lacan', 'rousseau', 'erasmus', 'rousseaus', 'merleauponty', 'sade', 'diderot', 'deleuze'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_20
  WTF: {'woman', 'writing', 'short', 'spark', 'books', 'introduction', 'writer', 'family', 'life', 'story', 'published', 'works', 'literary', 'letters', 'press', 'women'} {'seymour', 'charlotte', 'shelleys', 'christie', 'shelley', 'anne', 'bronts', 'godwin', 'jane', 'austens', 'austen', 'tomalin', 'bront', 'wollstonecraft', 'mary', 'percy'}
  WTF?!?!? 16
  WTF?!?!? 16
topic_21
  WTF: {'conservative', 'john', 'sir', 'crisis', '1939', 'lord', 'foot', 'cabinet', 'parliament'} {'british', 'canada', 'disraeli', 'canadian', 'riel', 'attlee', 'macdonald', 'holt', 'tupper'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_22
  WTF: {'surgeon', 'world', 'theory', 'cowpox', 'university', 'vaccination', 'bacteria', 'discovery', 'royal'} {'fleming', 'london', 'koch', 'pasteur', 'carrel', 'lister', 'jenner', 'edinburgh', 'hutton'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_23
  WTF: {'isbn', 'relativity', 'physical', 'work', 'stars', 'wiles', 'university', 'mathematical', 'light'} {'kepler', 'eulers', 'eddington', 'keplers', 'euler', 'caspar', 'rmer', 'johannes', 'hoyle'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_24
  WTF: {'roman', 'army', 'great', 'tours', 'son', 'empire', 'iii', 'ii', 'death', 'duke', 'spanish', 'imperial'} {'martel', 'france', 'italy', 'eugene', 'europe', 'attila', 'savoy', 'charlemagne', 'frankish', 'charles', 'louis', 'bernard'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_25
  WTF: {'married', 'isbn', 'kingdom', 'ed', 'pp', 'chronicle', 'iii', 'isles', 'kingship', 'died', 'death', 'ii', 'english', 'saga', 'killed'} {'macbeth', 'selkirk', 'coluim', 'scots', 'kenneth', 'oram', 'alexander', 'scotland', 'maclaurin', 'mel', 'alba', 'malcolm', 'duncan', 'malcolms', 'scottish'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_26
  WTF: {'comics', 'paintings', 'short', 'christian', 'work', 'life', 'story', 'polar', 'published', 'little', 'duck', '2005', 'new', 'art'} {'alvar', 'andersens', 'nansen', 'kafkas', 'norway', 'ibsen', 'eggum', 'franz', 'munch', 'kafka', 'aalto', 'prideaux', 'andersen', 'munchs'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_27
  WTF: {'sociology', 'die', 'reason', 'society', 'public', 'economic', 'published', 'memory', 'psychology', 'culture', 'philosophy'} {'grimm', 'luhmann', 'gadamer', 'schwitters', 'ebbinghaus', 'hesse', 'berlin', 'merz', 'habermas', 'schumpeter', 'frankfurt'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_28
  WTF: {'war', 'expedition', 'conquest', 'king', 'city', 'military', 'civil', 'son', 'married', 'issue', 'doa', 'troops', 'government', 'governor', 'new'} {'madero', 'francis', 'alfonso', 'almagro', 'xavier', 'mara', 'corts', 'cid', 'pizarro', 'daz', 'francisco', 'madrid', 'franco', 'mexico', 'francos'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_29
  WTF: {'succession', 'reign', 'vii', 'earl', 'council', 'protestant', 'throne', 'duke', 'marriage', 'ii', 'death', 'kings', 'royal'} {'england', 'elizabeth', 'anne', 'wales', 'edward', 'owain', 'henrys', 'henry', 'charles', 'catherine', 'tudor', 'elizabeths', 'mary'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_30
  WTF: {'dictionary', 'school', 'meeting', 'trials', 'gin', 'children', 'witch', 'bible', 'haven', 'meetings', 'published', 'church', 'spelling', 'christian'} {'yale', 'abbott', 'alcott', 'foxs', 'bellamy', 'noah', 'connecticut', 'eli', 'mather', 'mathers', 'whitney', 'quakers', 'webster', 'nickalls'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_31
  WTF: {'palimpsest', 'antiquity', 'logos', 'things', 'known', 'work', 'gods', 'life', 'fragments', 'ad', 'cylinder', 'philosophers'} {'aurelius', 'galens', 'heraclitus', 'galen', 'archimedes', 'verus', 'apuleius', 'dk', 'latin', 'marcus', 'diogenes', 'epicurus'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_32
  WTF: {'communist', 'hearings', 'committee', '1945', 'state', 'communists', 'von', 'senator', 'power', 'nazis', 'propaganda', 'subcommittee', 'speech'} {'waldheim', 'germany', 'mccarthy', 'reich', 'goebbels', 'gring', 'berlin', 'luftwaffe', 'hitlers', 'hitler', 'grings', 'nazi', 'mccarthys'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_33
  WTF: {'iraq', 'mission', 'powers', 'served', 'flying', 'corps', 'service'} {'rumsfeld', 'apollo', 'jones', 'hopper', 'armstrong', 'hansen', 'yeager'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_34
  WTF: {'differences', 'scientists', 'behavior', 'environmentalist', 'individual', 'carl', 'research'} {'rogers', 'wilson', 'rushton', 'jensens', 'venter', 'lomborg', 'jensen'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_35
  WTF: {'scientific', 'biology', 'science', 'ray', 'animals', 'society', 'principles', 'origin', 'history', 'vol', 'geological', 'plants'} {'slotten', 'mendel', 'london', 'mayr', 'haeckel', 'darwin', 'lyell', 'ernst', 'charles', 'wallace', 'wallaces', 'darwins'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_36
  WTF: {'rpt', 'communication', 'linguistic', 'phonetics', 'description', 'humans', 'work', 'grammar', 'english', 'university', 'linguist', 'ability', 'vowels'} {'olduvai', 'kenya', 'mau', 'kikuyu', 'hockett', 'whorf', 'jones', 'africa', 'morell', 'leakey', 'mary', 'african', 'louis'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_37
  WTF: {'police', 'mayor', 'relationship', 'united', 'school', 'house', '1989', 'education', 'children', 'files', 'campaign', 'attorney', 'white', 'states', 'husbands', 'women'} {'hoover', 'soliah', 'nancy', 'california', 'reagan', 'reagans', 'olson', 'ronald', 'sla', 'hoovers', 'lewinsky', 'clinton', 'laura', 'fargo', 'reno', 'gandy'}
  WTF?!?!? 16
  WTF?!?!? 16
topic_38
  WTF: {'poems', 'theatre', 'plays', 'life', 'des', 'mother', 'published', 'prints', 'literary', 'play'} {'flaubert', 'paris', 'richardson', 'baudelaires', 'maupassant', 'jarry', 'flauberts', 'baudelaire', 'tremblay', 'ubu'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_39
  WTF: {'dargento', 'album', 'composers', 'concert', 'dal', 'works', 'cinema', 'al', 'score'} {'palestrina', 'rossini', 'morricone', 'ennio', 'rossinis', 'premio', 'morricones', 'gioachino', 'bologna'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_40
  WTF: {'daughter', 'navigator', 'coast', 'prince', 'mother', 'iii', 'ii', 'expeditions', 'infanta', 'infante'} {'afonso', 'len', 'albuquerque', 'castile', 'portuguese', 'sancho', 'henry', 'portugal', 'aragon', 'coimbra'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_41
  WTF: {'hot', 'pg', 'release', 'number', 'rb', 'singles', 'pop'} {'uk', 'mariah', 'careys', 'aaliyah', 'carey', 'enya', 'difranco'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_42
  WTF: {'shows', 'featured', 'film', 'lyrics', 'minutes', 'wrote', 'popular', 'composer', 'golf', 'musicals', 'radio'} {'elfman', 'ira', 'broadway', 'kern', 'dowland', 'crosby', 'crosbys', 'gershwin', 'dowlands', 'burton', 'bing'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_43
  WTF: {'players', 'hall', 'allstar', 'tigers', 'hit', 'pitched', 'american'} {'youngs', 'greenberg', 'milwaukee', 'mlb', 'rockne', 'cy', 'doubleday'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_44
  WTF: {'park', 'designs', 'glass', 'home', 'center', 'homes', 'tower', 'art'} {'wright', 'lloyd', 'taliesin', 'lin', 'wrights', 'pei', 'chicago', 'mies'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_45
  WTF: {'greek', 'minor', 'married', 'daughter', 'crusade', 'emperors', 'son', 'fleet', 'crusaders', '1204', 'coemperor', 'iv', '1183', '1180'} {'nikephoros', 'constantinople', 'komnenos', 'thrace', 'byzantine', 'isaac', 'komnene', 'doukas', 'anna', 'andronikos', 'kanaris', 'maria', 'alexios', 'manuel'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_46
  WTF: {'conservative', 'theological', 'study', 'law', 'theology', 'prophets', 'work', 'university', 'rabbis', 'man', 'sabbath', 'studies', 'scholars'} {'heschel', 'jts', 'steinsaltz', 'hebrew', 'jewish', 'neusner', 'kushner', 'judaism', 'kaplans', 'neusners', 'talmud', 'torah', 'kaplan'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_47
  WTF: {'investiture', 'archbishop', 'mission', 'philosophersaint', 'anglosaxon', '279306', 'bishop', 'magick', 'magical', 'works', 'ecclesiastica'} {'bedes', 'anselm', 'bede', 'canterbury', 'aleister', 'augustine', 'vaughn', 'crowley', 'crowleys', 'anselms', 'sutin'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_48
  WTF: {'professor', '1709', 'patient', 'neuropathology', 'pathology', 'university', 'research', 'chemiae', 'chemistry'} {'alzheimer', 'alzheimers', 'kraepelin', 'jakob', 'elementa', 'selye', 'leiden', 'boerhaave', 'boerhaaves'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_49
  WTF: {'christmas', 'biography', 'isbn', 'collected', 'stories', 'books', 'twist', 'bleak', 'writing', 'serial'} {'melville', 'melvilles', 'bryson', 'williams', 'dickenss', 'conrads', 'dickens', 'charles', 'herman', 'conrad'}
  WTF?!?!? 10
  WTF?!?!? 10
{'fix': <__main__.FastFixPhiRegularizer object at 0x7fd2ce12dc40>}
Check after fit:
Skipping background topic: background_1.
topic_0
  WTF: {'academy', 'episode', 'career', '2008'} {'hitchcock', 'paul', 'robeson', 'cagney'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_1
  WTF: {'interrogation', 'army', '2002', 'ali', 'empire', 'muslims', 'al', 'government', 'new'} {'afghanistan', 'persian', 'abd', 'rumi', 'cia', 'islamic', 'muhammad', 'zubaydah', 'abu'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_2
  WTF: {'renaissance', 'san', 'father', 'cardinal', 'life', 'works', 'del', 'st', 'il', 'church', 'new'} {'francis', 'caravaggio', 'calvino', 'florence', 'rome', 'borgia', 'lucrezia', 'marco', 'cesare', 'fellini', 'bruno'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_3
  WTF: {'recording', 'single'} {'elvis', 'presley'}
topic_4
  WTF: {'war', 'married', 'great', 'daughter', 'military', 'otto', 'polish', 'prince', 'emperor', 'von', 'died', 'death', 'maternal'} {'mieszko', 'poland', 'hungary', 'prussia', 'albert', 'bismarck', 'brandenburg', 'prussian', 'saxony', 'frederick', 'casimir', 'alfred', 'alfreds'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_5
  WTF: {'senso', 'military', 'month', 'clan', 'emperors', 'son', 'manga', 'empress', 'throne', 'court', 'brown', 'sailor'} {'minamoto', 'nichiren', 'chiang', 'fujiwara', 'titsingh', 'japanese', 'japan', 'yamamoto', 'kaunda', 'kurosawa', 'deng', 'varley'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_6
  WTF: {'machine', 'information', 'computers', 'language', 'work', 'institute', 'operating', 'interview', 'award'} {'shannon', 'minsky', 'sanger', 'turing', 'engelbart', 'warwick', 'babbage', 'zuse', 'wikipedia'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_7
  WTF: {'war', 'army', 'chess', 'military', 'film', 'committee', 'state', 'time', 'world', 'revolution', 'government', 'march', 'ii', 'order', 'new'} {'russian', 'moscow', 'trotsky', 'khmelnytsky', 'alexander', 'nicholas', 'stalin', 'chekhov', 'beria', 'gorbachev', 'sakharov', 'tito', 'kasparov', 'yeltsin', 'russia'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_8
  WTF: {'dio', 'annals', 'emperors', 'potter', 'caesars', 'life', 'ce', 'senate', 'ad', 'death', 'ancient', 'caesar', 'imperial'} {'augustus', 'rome', 'barnes', 'domitian', 'julian', 'constantius', 'claudius', 'caligula', 'tiberius', 'odahl', 'diocletian', 'tacitus', 'suetonius'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_9
  WTF: {'professor', 'scientific', 'chemical', 'work', 'science', 'quantum', 'theory', 'institute', 'research'} {'bohr', 'meitner', 'fermi', 'davy', 'planck', 'faraday', 'fuchs', 'marie', 'marconi'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_10
  WTF: {'world', 'english', 'books', 'mars'} {'steinbeck', 'crichton', 'verne', 'moorcock'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_11
  WTF: {'musical', 'string', 'words', 'quartet', 'cello', 'trio', 'da'} {'elgar', 'wk', 'handel', 'shostakovich', 'hoffmann', 'lugosi', 'haydn'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_12
  WTF: {'hill', 'hearings', 'united', 'american', 'baron', 'pp', 'supreme', 'union', 'justice', 'beacon'} {'lee', 'carson', 'jay', 'stuart', 'oswald', 'warren', 'hancock', 'davis', 'ruby', 'thomas'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_13
  WTF: {'grand', 'career', 'championship', 'lost', 'wickets', 'world'} {'jordan', 'earnhardt', 'agassi', 'muralitharan', 'schumacher', 'hingis'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_14
  WTF: {'book', 'cartoonist', 'years', 'later', 'work', 'bubbles', 'published', 'al', 'new', 'poem', 'art'} {'thurber', 'abner', 'capp', 'masefield', 'dodgson', 'kirby', 'keats', 'lil', 'carroll', 'housman', 'capps'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_15
  WTF: {'scientific', 'behavior', 'work', 'knowledge', 'object', 'society', 'philosophical', 'logical', 'published', 'social', 'psychology', 'research', 'sign'} {'dewey', 'skinner', 'chomsky', 'rothbard', 'bertrand', 'hayek', 'russell', 'russells', 'peirce', 'peirces', 'friedman', 'milken', 'popper'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_16
  WTF: {'greek', 'saints', 'tours', 'book', 'writings', 'life', 'bishop', 'works', 'roman', 'chapter', 'god', 'heresies'} {'chrysostom', 'athanasius', 'anthony', 'benedict', 'luke', 'josephus', 'irenaeus', 'ephrem', 'alexandria', 'jerome', 'cyril', 'martin'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_17
  WTF: {'allied', 'voyage', 'admiral', 'ship', 'attack', 'ships', 'navy', 'lord', 'royal'} {'british', 'drake', 'nelson', 'wellington', 'montgomery', 'mountbatten', 'rommel', 'sugden', 'rommels'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_18
  WTF: {'medium', 'painters', 'french', 'giger', 'millet', 'works', 'museum'} {'pissarro', 'rodin', 'paris', 'davids', 'rodins', 'monet', 'david'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_19
  WTF: {'marquis', 'desire', 'subject', 'perception', 'work', 'political', 'university', 'published', 'works', 'new', 'symbolic'} {'sartre', 'nostradamus', 'paris', 'lacan', 'rousseau', 'erasmus', 'rousseaus', 'merleauponty', 'sade', 'diderot', 'deleuze'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_20
  WTF: {'woman', 'writing', 'short', 'spark', 'books', 'introduction', 'writer', 'family', 'life', 'story', 'published', 'works', 'literary', 'letters', 'press', 'women'} {'seymour', 'charlotte', 'shelleys', 'christie', 'shelley', 'anne', 'bronts', 'godwin', 'jane', 'austens', 'austen', 'tomalin', 'bront', 'wollstonecraft', 'mary', 'percy'}
  WTF?!?!? 16
  WTF?!?!? 16
topic_21
  WTF: {'conservative', 'john', 'sir', 'crisis', '1939', 'lord', 'foot', 'cabinet', 'parliament'} {'british', 'canada', 'disraeli', 'canadian', 'riel', 'attlee', 'macdonald', 'holt', 'tupper'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_22
  WTF: {'surgeon', 'world', 'theory', 'cowpox', 'university', 'vaccination', 'bacteria', 'discovery', 'royal'} {'fleming', 'london', 'koch', 'pasteur', 'carrel', 'lister', 'jenner', 'edinburgh', 'hutton'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_23
  WTF: {'isbn', 'relativity', 'physical', 'work', 'stars', 'wiles', 'university', 'mathematical', 'light'} {'kepler', 'eulers', 'eddington', 'keplers', 'euler', 'caspar', 'rmer', 'johannes', 'hoyle'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_24
  WTF: {'roman', 'army', 'great', 'tours', 'son', 'empire', 'iii', 'ii', 'death', 'duke', 'spanish', 'imperial'} {'martel', 'france', 'italy', 'eugene', 'europe', 'attila', 'savoy', 'charlemagne', 'frankish', 'charles', 'louis', 'bernard'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_25
  WTF: {'married', 'isbn', 'kingdom', 'ed', 'pp', 'chronicle', 'iii', 'isles', 'kingship', 'died', 'death', 'ii', 'english', 'saga', 'killed'} {'macbeth', 'selkirk', 'coluim', 'scots', 'kenneth', 'oram', 'alexander', 'scotland', 'maclaurin', 'mel', 'alba', 'malcolm', 'duncan', 'malcolms', 'scottish'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_26

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7fd2ce12d280>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7fd2d0838100>}
{'perplexity': 314998.53125, 'coherence_20': 0.7557516129298933, 'diversity_euclidean': 0.032710057322435475, 'diversity_jensenshannon': 0.6540241607275221, 'diversity_hellinger': 0.7676021330136549, 'diversity_cosine': 0.727484089390626, 'fair_ppl_free': 2764.2158203125, 'fair_ppl_fix': 337734.46875, 'unfair_ppl_banklike': 314998.53125}
{'num_topics': 51, 'num_common_words': 65750, 'num_model_words': 155407, 'num_bt_words': 135939, 'top_diffs': [{'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 32, 'lost_bt': 16, 'lost_model': 16}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 32, 'lost_bt': 16, 'lost_model': 16}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}]}

In [41]:
1

1