In [1]:
import os
import json
import shutil
import sys

import numpy as np
import scipy

In [2]:
sys.path.insert(0, '../OptimalNumberOfTopics')

In [3]:
import topnum

from topnum.scores.perplexity_score import PerplexityScore
from topnum.scores.diversity_score import DiversityScore, KNOWN_METRICS
from topnum.model_constructor import init_model_from_family, KnownModel, PARAMS_EXPLORED, init_plsa

In [4]:
import artm
from artm import ARTM, Dictionary

import topicnet
from topicnet.cooking_machine.dataset import Dataset
from topicnet.cooking_machine.models import (
    BaseScore as BaseTopicNetScore,
    TopicModel
)
from topicnet.cooking_machine.models.base_regularizer import BaseRegularizer
from topicnet.cooking_machine.models.thetaless_regularizer import (
    dataset2sparse_matrix,
)

from topicnet.cooking_machine.models.topic_model import ARTM_NINE
from topicnet.cooking_machine.models.base_regularizer import BaseRegularizer
from topicnet.viewers.top_documents_viewer import TopDocumentsViewer
from topicnet.viewers.top_tokens_viewer import TopTokensViewer
from topicnet.cooking_machine.model_constructor import (
    add_standard_scores,
    create_default_topics,
    count_vocab_size,
    init_model,
)
from topicnet.cooking_machine.rel_toolbox_lite import (
    count_vocab_size,
    modality_weight_rel2abs,
    transform_regularizer,
)


import numpy as np
import pandas as pd
from pandas import DataFrame
from scipy.spatial.distance import cdist

import os
import tempfile
import warnings
from copy import deepcopy
from typing import Dict, List, Optional

In [5]:
NUM_TOPICS = 20  # TODO: this value does not affect anything

NUM_ITERATIONS = 5
NUM_TOP_TOKENS = 20
NUM_TRAINS = 20

In [6]:
BERTOPIC_FOLDER_PATH = '/data_mil/shared/CompressaAI/BERTopic'

In [7]:
! ls $BERTOPIC_FOLDER_PATH

results  results50

In [8]:
! ls $BERTOPIC_FOLDER_PATH/results

20newsgroups  mkb10  postnauka	rtlwikiperson  ruwikigood

In [9]:
RESULTS_FOLDER_PATH = os.path.join(BERTOPIC_FOLDER_PATH, 'results', 'ruwikigood')

In [10]:
RESULTS_FOLDER_PATH

'/data_mil/shared/CompressaAI/BERTopic/results/ruwikigood'

In [11]:
! ls results50

20newsgroups  mkb10  postnauka	rtlwikiperson  ruwikigood

In [12]:
SAVE_FOLDER = os.path.join('results', 'ruwikigood')

In [13]:
SAVE_FOLDER

'results/ruwikigood'

In [14]:
! ls $SAVE_FOLDER

ablation_study			     iterative2_1000000000
decorrelation.json		     iterative2_10000000000
iterative_1000000		     iterative2_100000000000
iterative_10000000		     iterative2_100000000000.json
iterative_100000000		     iterative2_10000000000.json
iterative_100000000_unfinished.json  iterative2_1000000000.json
_iterative_10000000.json	     lda.json
iterative_10000000.json		     plsa.json
_iterative_1000000.json		     sparse.json
iterative_1000000.json		     tless.json

In [15]:
! ls $RESULTS_FOLDER_PATH

0  1  10  11  12  13  14  15  16  17  18  19  2  3  4  5  6  7	8  9

In [16]:
! ls $RESULTS_FOLDER_PATH/0

dataset.csv  phi.csv  top_words.json

In [17]:
dataset = Dataset(
    f'{RESULTS_FOLDER_PATH}/0/dataset.csv',
)

dataset.get_possible_modalities()

{'@lemmatized'}

In [18]:
MAIN_MODALITY = '@lemmatized'

In [19]:
def calc_doc_occurrences(dataset, modality):
    """
    :param n_dw_matrix: sparse document-word matrix, shape is D x W
    :return: sparse matrix of co-occurrences

    doc_occurrences[w1, w2] = the number of the documents
    where there are w1 and w2
    """
    n_dw_matrix = dataset2sparse_matrix(dataset, modality, modalities_to_use=[modality])
    matrix = (scipy.sparse.csc_matrix(n_dw_matrix) > 0).astype(int)
    co_occurrences = matrix.T * matrix

    return co_occurrences.diagonal(), co_occurrences


def create_pmi_top_function(
    doc_occurrences, doc_co_occurrences,
    documents_number, top_sizes,
    topic_indices,
    co_occurrences_smooth=1.
):
    """
    :param doc_occurrences: array of doc occurrences of words
    :param doc_co_occurrences: sparse matrix of doc co-occurrences of words
    :param documents_number: number of the documents
    :param top_sizes: list of top values to calculate top-pmi for
    :param co_occurrences_smooth: constant to smooth co-occurrences in log
    :return: function which takes phi and theta and returns
    pair of two arrays: pmi-s of the tops and ppmi-s of the tops

    pmi[i] - pmi(top of size top_sizes[i])
    ppmi[i] - ppmi(top of size top_sizes[i])

    pmi(words) = sum_{u in words, v in words, u != v}
    log(
        (doc_co_occurrences[u, v] * documents_number + co_occurrences_smooth)
        / doc_occurrences[u] / doc_occurrences[v]
    )

    ppmi(words) = sum_{u in words, v in words, u != v}
    max(log(
        (doc_co_occurrences[u, v] * documents_number + co_occurrences_smooth)
        / doc_occurrences[u] / doc_occurrences[v]
    ), 0)

    """
    def func(phi):
        _T, W = phi.shape
        T = len(topic_indices)

        max_top_size = max(top_sizes)
        topic_pmis, topic_ppmis = dict(), dict()
        pmi, ppmi = np.zeros(max_top_size), np.zeros(max_top_size)
        tops = np.argpartition(phi, -max_top_size, axis=1)[:, -max_top_size:]
        
        for t in topic_indices:
            top = sorted(tops[t], key=lambda w: - phi[t, w])
            co_occurrences = doc_co_occurrences[top, :][:, top].todense()
            occurrences = doc_occurrences[top]
            values = np.log(
                (co_occurrences * documents_number + co_occurrences_smooth)
                / (occurrences[:, np.newaxis] * occurrences[np.newaxis, :] + co_occurrences_smooth)
            )
            diag = np.diag_indices(len(values))
            # values.cumsum(axis=0).cumsum(axis=1)[diag] - values[diag].cumsum()

            current_pmi = np.array(
               values.cumsum(axis=0).cumsum(axis=1)[diag] - values[diag].cumsum()
            ).ravel()
            topic_pmis[t] = current_pmi
            pmi += current_pmi

            values[values < 0.] = 0.
            current_ppmi = np.array(
               values.cumsum(axis=0).cumsum(axis=1)[diag] - values[diag].cumsum()
            ).ravel()
            topic_ppmis[t] = current_ppmi
            ppmi += current_ppmi
            
        sizes = np.arange(2, max_top_size + 1)
        pmi[1:] /= (T * sizes * (sizes - 1))
        ppmi[1:] /= (T * sizes * (sizes - 1))
        indices = np.array(top_sizes) - 1

        for t in topic_indices:
            topic_pmis[t][1:] /= (sizes * (sizes - 1))
            topic_ppmis[t][1:] /= (sizes * (sizes - 1))

        result_topic_pmis = {t: p[indices] for t, p in topic_pmis.items()}
        result_topic_ppmis = {t: p[indices] for t, p in topic_ppmis.items()}

        return pmi[indices], ppmi[indices], result_topic_pmis, result_topic_ppmis

    return func

In [20]:
%%time

occurences, co_occurences = calc_doc_occurrences(dataset, MAIN_MODALITY)

CPU times: user 1min 32s, sys: 32.6 s, total: 2min 4s
Wall time: 2min 3s

In [21]:
co_occurences.shape

(264943, 264943)

In [22]:
calc_pmi = create_pmi_top_function(
    occurences, co_occurences,
    dataset.get_dataset().shape[0], [20],
    topic_indices=[0, 1, 2],
    co_occurrences_smooth=1e-2,
)

In [23]:
class TopTokenCoherence(BaseTopicNetScore):
    def __init__(self, name, func):
        super().__init__()

        self._name = name
        self.calc_pmi = func

    def call(self, model: TopicModel):
        values = self.calc_pmi(model.get_phi_dense()[0].T)

        return values[1]

    def call_by_topic(self, model: TopicModel):
        values = self.calc_pmi(model.get_phi_dense()[0].T)

        return values[3]

In [24]:
def view_model(
        topic_model,
        dataset,
        num_top_tokens: int = 5,
        top_tokens_method: str = 'phi',
        num_topics: Optional[int] = 5,  # we do not want to fill the whole .ipynb notebook with topics...
        ):
    top_tok_viewer = TopTokensViewer(
        topic_model, num_top_tokens=num_top_tokens, method=top_tokens_method
    )
    top_doc_viewer = TopDocumentsViewer(topic_model, dataset=dataset)
    top_docs = top_doc_viewer.view()

    if num_topics is None:
        num_topics = len(topic_model.topic_names)

    for topic_name in topic_model.topic_names[:num_topics]:
        topic_top_toks = top_tok_viewer.to_html(topic_names=[topic_name])
        topic_top_docs = top_docs[topic_name]
        display_html(topic_top_toks, raw=True)
        display(topic_top_docs)

In [25]:
class FastFixPhiRegularizer(BaseRegularizer):
    _VERY_BIG_TAU = 10 ** 9

    def __init__(self, name: str, topic_names: List[str], parent_model=None, parent_phi=None, words=None):
        super().__init__(name, tau=self._VERY_BIG_TAU)

        self._topic_names = topic_names
        self._topic_indices = None
        self._words = words
        self._word_indices = None
        self._parent_model = parent_model
        self._parent_phi = parent_phi

    def grad(self, pwt, nwt):
        # print('Fixing')

        rwt = np.zeros_like(pwt)

        if self._parent_phi is not None:
            parent_phi = self._parent_phi
            vals = parent_phi.values
        else:
            assert False

            parent_phi = self._parent_model.get_phi()
            vals = parent_phi.values[:, self._topic_indices]

        if self._word_indices is None:
            assert vals.shape[0] == rwt.shape[0], (vals.shape[0], rwt.shape[0])
        else:
            assert vals.shape[0] == len(self._word_indices)

        assert vals.shape[1] == len(self._topic_indices)

        if self._word_indices is None:
            rwt[:, self._topic_indices] += vals
        else:
            # print(len(self._word_indices), len(self._topic_indices), rwt.shape, vals.shape)
            # print(self._word_indices[:3], self._topic_indices[:3])
            # print(rwt[np.ix_(self._word_indices, self._topic_indices)].shape, vals.shape)

            # https://github.com/numpy/numpy/issues/5574
            # https://github.com/numpy/numpy/issues/13255
            rwt[np.ix_(self._word_indices, self._topic_indices)] += vals

            # print(np.ix_(self._word_indices, self._topic_indices)[:3])

        return self.tau * rwt

    def attach(self, model):
        super().attach(model)
        
        phi = self._model.get_phi()
        self._topic_indices = [
            phi.columns.get_loc(topic_name)
            for topic_name in self._topic_names
        ]

        if self._words is not None:
            self._word_indices = [
                # phi.index.get_loc(w) for w in self._words
                int(phi.index.get_loc(w)) for w in self._words
            ]

            # print(f'!!! Word indices: {self._word_indices}')

In [26]:
def fit_and_compute_scores(model, dataset, target_topic_indices=None, custom_regularizers=None):
    print(custom_regularizers)

    model._fit(dataset.get_batch_vectorizer(), num_iterations=NUM_ITERATIONS, custom_regularizers=custom_regularizers)

    score_values = {
        'perplexity': model.scores[f'PerplexityScore{MAIN_MODALITY}'][-1],
    }

    phi = model.get_phi()

    # Currently all topics are taken into account

    if target_topic_indices is None:
        target_topic_indices = list(range(NUM_TOPICS))  # phi.columns.get_loc()

    target_topic_names = [phi.columns[i] for i in target_topic_indices]

    top = NUM_TOP_TOKENS
    coherence_score = TopTokenCoherence(
        name=f'coherence_{top}',
        func=create_pmi_top_function(
            occurences, co_occurences,
            dataset.get_dataset().shape[0], [top],
            topic_indices=target_topic_indices,
            co_occurrences_smooth=1e-2,
        )
    )

    value = coherence_score.call(model)
    score_values[coherence_score._name] = value
    topic_coherences = coherence_score.call_by_topic(model)
    topic_coherences = {t: float(v) for t, v in topic_coherences.items()}

    diversity_scores = [
        DiversityScore(
            name=f'diversity_{metric}',
            metric=metric,
            topic_names=target_topic_names,
            class_ids=MAIN_MODALITY,
        )
    
        for metric in KNOWN_METRICS
    ]
    
    for score in diversity_scores:
        value = score.call(model)
        score_values[score._name] = value

    return {
        'scores': score_values,
        'topic_coherences': topic_coherences,
    }

In [27]:
def init_model_from_family(
        family: str or KnownModel,
        dataset: Dataset,
        main_modality: str,
        num_topics: int,
        seed: int,
        specific_topic_names = None,
        modalities_to_use: List[str] = None,
        num_processors: int = 3,
        model_params: dict = None,
):
    """
    Returns
    -------
    model: TopicModel() instance
    """
    if isinstance(family, KnownModel):
        family = family.value

    if modalities_to_use is None:
        modalities_to_use = [main_modality]

    custom_regs = {}

    if family == "LDA":
        model = init_lda(
            dataset, modalities_to_use, main_modality, num_topics, model_params
        )
    elif family == "PLSA":
        model = init_plsa(
            dataset, modalities_to_use, main_modality, num_topics
        )
    elif family == "TARTM":
        model, custom_regs = init_thetaless(
            dataset, modalities_to_use, main_modality, num_topics, model_params
        )
    elif family == "sparse":
        model = init_bcg_sparse_model(
            dataset, modalities_to_use, main_modality, num_topics, 1, model_params
        )
    elif family == "decorrelation":
        model = init_decorrelated_plsa(
            dataset, modalities_to_use, main_modality, num_topics, model_params
        )
    elif family == "ARTM":
        model = init_baseline_artm(
            dataset, modalities_to_use, main_modality, num_topics, 1, specific_topic_names, model_params
        )
    else:
        raise ValueError(f'family: {family}')

    model.num_processors = num_processors

    if seed is not None:
        model.seed = seed

    dictionary = dataset.get_dictionary()

    # TODO: maybe this cycle is not necessary
    for modality in dataset.get_possible_modalities():
        if modality not in modalities_to_use:
            dictionary.filter(class_id=modality, max_df=0, inplace=True)

    model.initialize(dictionary)
    add_standard_scores(model, dictionary, main_modality=main_modality,
                        all_modalities=modalities_to_use)

    model = TopicModel(
        artm_model=model,
        custom_regularizers=custom_regs
    )

    return model


def init_bcg_sparse_model(
        dataset,
        modalities_to_use,
        main_modality,
        specific_topics,
        bcg_topics,
        specific_topic_names = None,
        model_params: dict = None
):
    """
    Creates simple artm model with standard scores.

    Parameters
    ----------
    dataset : Dataset
    modalities_to_use : list of str or dict
    main_modality : str
    specific_topics : int
    bcg_topics : int

    Returns
    -------
    model: artm.ARTM() instance
    """
    if model_params is None:
        model_params = dict()

    model = init_plsa(
        dataset, modalities_to_use, main_modality, specific_topics, bcg_topics
    )
    background_topic_names = model.topic_names[-bcg_topics:]

    if specific_topic_names is None:
        print('No spec topics')
        specific_topic_names = model.topic_names[:-bcg_topics]

    dictionary = dataset.get_dictionary()
    baseline_class_ids = {class_id: 1 for class_id in modalities_to_use}
    data_stats = count_vocab_size(dictionary, baseline_class_ids)

    # all coefficients are relative
    regularizers = [
        artm.SmoothSparsePhiRegularizer(
             name='smooth_phi_bcg',
             topic_names=background_topic_names,
             tau=model_params.get("smooth_bcg_tau", 0.1),
             class_ids=[main_modality],
        ),
        artm.SmoothSparseThetaRegularizer(
             name='smooth_theta_bcg',
             topic_names=background_topic_names,
             tau=model_params.get("smooth_bcg_tau", 0.1),
        ),
        artm.SmoothSparsePhiRegularizer(
             name='sparse_phi_sp',
             topic_names=specific_topic_names,
             tau=model_params.get("sparse_sp_tau", -0.05),
             class_ids=[main_modality],
            ),
        artm.SmoothSparseThetaRegularizer(
             name='sparse_theta_sp',
             topic_names=specific_topic_names,
             tau=model_params.get("sparse_sp_tau", -0.05),
        ),
    ]
    for reg in regularizers:
        model.regularizers.add(transform_regularizer(
            data_stats,
            reg,
            model.class_ids,
            n_topics=len(reg.topic_names)
        ))

    return model


def init_baseline_artm(
        dataset,
        modalities_to_use,
        main_modality,
        num_topics,
        bcg_topics,
        specific_topic_names = None,
        model_params: dict = None,
):
    """
    Creates simple artm model with standard scores.

    Parameters
    ----------
    dataset : Dataset
    modalities_to_use : list of str
    main_modality : str
    num_topics : int

    Returns
    -------
    model: artm.ARTM() instance
    """
    if model_params is None:
        model_params = dict()

    model = init_bcg_sparse_model(
        dataset, modalities_to_use, main_modality, num_topics, bcg_topics, specific_topic_names, model_params
    )

    if specific_topic_names is None:
        print('No spec topics')
        specific_topic_names = model.topic_names[:-bcg_topics]

    model.regularizers.add(
        artm.DecorrelatorPhiRegularizer(
            gamma=0,
            tau=model_params.get('decorrelation_tau', 0.01),
            name='decorrelation',
            topic_names=specific_topic_names,
            class_ids=modalities_to_use,
        )
    )

    return model

In [28]:
TOPIC_INDICES = list(range(NUM_TOPICS))

In [29]:
TOPIC_INDICES

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [30]:
phi0 = pd.read_csv(f'{RESULTS_FOLDER_PATH}/0/phi.csv', index_col=0)

In [31]:
phi0.head()

,background_1,topic_0,topic_1,topic_2,topic_3,topic_4,topic_5,topic_6,topic_7,topic_8,topic_9,topic_10,topic_11,topic_12,topic_13,topic_14,topic_15
aa,0.000019,0.000032,0.000065,0.0,0.00000,0.000016,0.0,0.000019,0.0,0.0,0.0,0.0,0.007627,0.0,0.0,0.0,0.0
aaa,0.000000,0.000072,0.000011,0.0,0.00003,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
aaaaa,0.000003,0.000000,0.000000,0.0,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
aaaaabbbbbabbbaabbababbaaababaab,0.000003,0.000000,0.000000,0.0,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
aaaab,0.000004,0.000000,0.000000,0.0,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0

In [32]:
phi0.set_index([[MAIN_MODALITY] * len(phi0.index), phi0.index], inplace=True)

In [124]:
phi0.head()

                                              background_1   topic_0  \
@lemmatized aa                                    0.000019  0.000032
            aaa                                   0.000000  0.000072
            aaaaa                                 0.000003  0.000000
            aaaaabbbbbabbbaabbababbaaababaab      0.000003  0.000000
            aaaab                                 0.000004  0.000000

                                               topic_1  topic_2  topic_3  \
@lemmatized aa                                0.000065      0.0  0.00000
            aaa                               0.000011      0.0  0.00003
            aaaaa                             0.000000      0.0  0.00000
            aaaaabbbbbabbbaabbababbaaababaab  0.000000      0.0  0.00000
            aaaab                             0.000000      0.0  0.00000

                                               topic_4  topic_5   topic_6  \
@lemmatized aa                                0.000016      0.0  0.000019
            aaa                               0.000000      0.0  0.000000
            aaaaa                             0.000000      0.0  0.000000
            aaaaabbbbbabbbaabbababbaaababaab  0.000000      0.0  0.000000
            aaaab                             0.000000      0.0  0.000000

                                              topic_7  topic_8  topic_9  \
@lemmatized aa                                    0.0      0.0      0.0
            aaa                                   0.0      0.0      0.0
            aaaaa                                 0.0      0.0      0.0
            aaaaabbbbbabbbaabbababbaaababaab      0.0      0.0      0.0
            aaaab                                 0.0      0.0      0.0

                                              topic_10  topic_11  topic_12  \
@lemmatized aa                                     0.0  0.007627       0.0
            aaa                                    0.0  0.000000       0.0
            aaaaa                                  0.0  0.000000       0.0
            aaaaabbbbbabbbaabbababbaaababaab       0.0  0.000000       0.0
            aaaab                                  0.0  0.000000       0.0

                                              topic_13  topic_14  topic_15
@lemmatized aa                                     0.0       0.0       0.0
            aaa                                    0.0       0.0       0.0
            aaaaa                                  0.0       0.0       0.0
            aaaaabbbbbabbbaabbababbaaababaab       0.0       0.0       0.0
            aaaab                                  0.0       0.0       0.0

In [125]:
proper_names = [f'topic_{i}' for i in range(phi0.shape[1])]

phi0.rename(
    columns={old_name: new_name for old_name, new_name in zip(phi0.columns, proper_names)},
    inplace=True,
)

In [126]:
phi0.head()

                                               topic_0   topic_1   topic_2  \
@lemmatized aa                                0.000019  0.000032  0.000065
            aaa                               0.000000  0.000072  0.000011
            aaaaa                             0.000003  0.000000  0.000000
            aaaaabbbbbabbbaabbababbaaababaab  0.000003  0.000000  0.000000
            aaaab                             0.000004  0.000000  0.000000

                                              topic_3  topic_4   topic_5  \
@lemmatized aa                                    0.0  0.00000  0.000016
            aaa                                   0.0  0.00003  0.000000
            aaaaa                                 0.0  0.00000  0.000000
            aaaaabbbbbabbbaabbababbaaababaab      0.0  0.00000  0.000000
            aaaab                                 0.0  0.00000  0.000000

                                              topic_6   topic_7  topic_8  \
@lemmatized aa                                    0.0  0.000019      0.0
            aaa                                   0.0  0.000000      0.0
            aaaaa                                 0.0  0.000000      0.0
            aaaaabbbbbabbbaabbababbaaababaab      0.0  0.000000      0.0
            aaaab                                 0.0  0.000000      0.0

                                              topic_9  topic_10  topic_11  \
@lemmatized aa                                    0.0       0.0       0.0
            aaa                                   0.0       0.0       0.0
            aaaaa                                 0.0       0.0       0.0
            aaaaabbbbbabbbaabbababbaaababaab      0.0       0.0       0.0
            aaaab                                 0.0       0.0       0.0

                                              topic_12  topic_13  topic_14  \
@lemmatized aa                                0.007627       0.0       0.0
            aaa                               0.000000       0.0       0.0
            aaaaa                             0.000000       0.0       0.0
            aaaaabbbbbabbbaabbababbaaababaab  0.000000       0.0       0.0
            aaaab                             0.000000       0.0       0.0

                                              topic_15  topic_16
@lemmatized aa                                     0.0       0.0
            aaa                                    0.0       0.0
            aaaaa                                  0.0       0.0
            aaaaabbbbbabbbaabbababbaaababaab       0.0       0.0
            aaaab                                  0.0       0.0

In [35]:
DIFF_THRESHOLD = 2

In [185]:
def check_top_words(phi, top_words):
    diffs = []

    for i, (t, topic_top_words) in enumerate(top_words.items()):
        if t == 'background_1':
            print(f'Skipping background topic: {t}.')

            # Sometimes it is here...
            # assert not topic_top_words  # TODO: BERTopic did not give -1 topic for GoodRuWiki...
                                        #   So, we have (model phi Vs. top words)
                                        #                     -            "background_1"
                                        #               "background_1" <-> "topic_0"
                                        #               "topic_1"      <-> "topic_2"
                                        #                              ...
                                        #               "topic_n-1"    <-> "topic_n"
                                        #               "topic_n"      <->     - (lost top words)

            continue

        print(t)
        # print(top_words)
    
        top_phi = set(phi[t].sort_values(ascending=False)[:NUM_TOP_TOKENS].index.get_level_values(1))
        top_bt = set([p[0] for p in topic_top_words])
    
        if top_phi == top_bt:
            diffs.append(
                {
                    'total': 0,
                    'lost_bt': 0,
                    'lost_model': 0,
                }
            )
        else:
            diff1 = top_phi.difference(top_bt)
            diff2 = top_bt.difference(top_phi)
    
            print('  WTF:', diff1, diff2)
    
            if len(diff1) > DIFF_THRESHOLD:
                print(f'  WTF?!?!?', len(diff1))
    
            if len(diff2) > DIFF_THRESHOLD:
                print(f'  WTF?!?!?', len(diff2))

            diffs.append(
                {
                    'total': len(diff1 | diff2),
                    'lost_bt': len(diff2),
                    'lost_model': len(diff1),
                }
            )

    return diffs

In [210]:
[phi.columns[-1]] + list(phi.columns[:-1])

['topic_19',
 'topic_0',
 'topic_1',
 'topic_2',
 'topic_3',
 'topic_4',
 'topic_5',
 'topic_6',
 'topic_7',
 'topic_8',
 'topic_9',
 'topic_10',
 'topic_11',
 'topic_12',
 'topic_13',
 'topic_14',
 'topic_15',
 'topic_16',
 'topic_17',
 'topic_18']

In [214]:
def init_model_and_phi(num_topics, dataset, phi0):
    model = init_model_from_family(
        family=KnownModel.PLSA,
        dataset=dataset,
        main_modality=MAIN_MODALITY,
        num_topics=num_topics,
        seed=0,
    )
    
    phi = model.get_phi()
    
    # assert phi.shape[1] == phi0.shape[1] - 1
    assert phi.shape[1] == num_topics
    # assert phi.shape[1] in [phi0.shape[1], phi0.shape[1] - 1]
    # assert phi.shape[1] in [phi0.shape[1], phi0.shape[1] + 1]  # TODO: GoodRuWiki specific fix
    assert phi.shape[1] in [
        phi0.shape[1],      # just save all
        phi0.shape[1] + 1,  # all plus bcg
        phi0.shape[1] - 1   # all minus bcg
    ]

    common_words = list(set(phi.index).intersection(phi0.index))
    
    phi.loc[:, :] = 1

    if phi.shape[1] == phi0.shape[1]:  # phi0 has bcg or does not
        target_topics = phi.columns
        source_topics = phi0.columns

        if 'back' in source_topics[0]:
            target_topics = [target_topics[-1]] + list(target_topics[:-1])  # bcg -- last

        # assert set(phi.columns) == set(phi0.columns)

    elif phi.shape[1] == phi0.shape[1] - 1:  # no bcg
        target_topics = phi.columns
        source_topics = [t for t in phi0.columns if 'back' not in t]

        assert list(target_topics) == list(source_topics), (target_topics, source_topics)

    elif phi.shape[1] == phi0.shape[1] + 1:  # with bcg but phi0 does not have bcg (TODO: GoodRuWiki specific)
        target_topics = phi0.columns
        source_topics = phi0.columns

    assert len(target_topics) == len(source_topics), (target_topics, source_topics)

    # print(common_words, phi.index, phi0.index)

    phi.loc[:, target_topics] = 0
    phi.loc[common_words, target_topics] = phi0.loc[common_words, source_topics]  # Fix for GoodRuWiki (but seems would be OK for all)

    diff = set(phi0.columns).symmetric_difference(set(phi.columns))

    # assert diff == {'background_1'} or diff == {'background_1', f'topic_{len(phi.columns) - 1}'}
    # assert diff == set() or diff == {f'topic_{len(phi.columns) - 1}'}  # TODO: GoodRuWiki specific
    assert diff == set() or diff == {f'topic_{len(phi.columns) - 1}'} or diff == {'background_1'} or diff == {'background_1', f'topic_{len(phi.columns) - 1}'}, (
        diff, phi0.columns, phi.columns
    )

    phi = phi / phi.sum(axis=0)

    return model, phi, common_words

In [215]:
not not 1

True

In [216]:
results = []

is_results_loaded = False

save_file_path = os.path.join(
    SAVE_FOLDER, 'bertopic.json'
)

if os.path.isfile(save_file_path):
    results = json.loads(
        open(save_file_path).read()
    )
    is_results_loaded = True


singles_save_folder = os.path.join(
    SAVE_FOLDER, 'bertopic'
)

os.makedirs(singles_save_folder, exist_ok=True)


for seed in range(NUM_TRAINS):
    if is_results_loaded:
        continue

    print(seed)

    current_save_file_path = os.path.join(
        singles_save_folder, f'bertopic_{seed}.json'
    )

    if os.path.isfile(current_save_file_path):
        print(f'Already computed results: {current_save_file_path}. Loading and skipping...')

        result = json.loads(
            open(current_save_file_path).read()
        )
        results.append(result)

        continue

    seed_load_folder = os.path.join(RESULTS_FOLDER_PATH, str(seed))
    files = [f for f in os.listdir(seed_load_folder) if os.path.isfile(f'{seed_load_folder}/{f}')]
    
    assert len(files) == 3

    dataset = Dataset(
        f'{seed_load_folder}/dataset.csv',
    )

    with open(f'{seed_load_folder}/top_words.json', 'r') as f:
        top_words = json.loads(f.read())

    has_bcg = not not top_words['background_1']
    
    phi0 = pd.read_csv(f'{seed_load_folder}/phi.csv', index_col=0)
    phi0.set_index([[MAIN_MODALITY] * len(phi0.index), phi0.index], inplace=True)

    if not has_bcg:
        # *** GoodRuWiki specific code ***
        proper_names = [f'topic_{i}' for i in range(phi0.shape[1])]
        phi0.rename(
            columns={old_name: new_name for old_name, new_name in zip(phi0.columns, proper_names)},
            inplace=True,
        )
        # *** GoodRuWiki specific code ***

        num_specific_topics = phi0.shape[1]  # - 1
    else:
        assert all('back' not in t for t in phi0.columns[1:])
        assert 'back' in phi0.columns[0]

        num_specific_topics = phi0.shape[1] - 1

    if not has_bcg:
        assert num_specific_topics == len(phi0.columns)  # len([t for t in phi0.columns if 'back' not in t])
    else:
        assert num_specific_topics == len([t for t in phi0.columns if 'back' not in t])

    print(f'Num model topics: {phi0.shape[1]}.')


    
    model, phi, common_phi_words = init_model_and_phi(
        num_topics=num_specific_topics + 1,  # background
        dataset=dataset, phi0=phi0
    )
    common_words = [
        w[1] for w in common_phi_words  # without modality
    ]
    common_words_phi0_indices = [
        # phi0.index.get_loc(w) for w in common_words
        int(phi0.index.get_locs(w)) for w in common_phi_words
    ]

    print('Check before fit:')
    diff_tops1 = check_top_words(phi, top_words)  # Whatever...

    if not has_bcg:
        fix_regularizer = FastFixPhiRegularizer(
            name='fix',
            parent_phi=phi0.iloc[common_words_phi0_indices, :],  # TODO: GoodRuWiki specific change (no bcg) 
            words=common_words,
            topic_names=phi.columns[:-1],  # TODO: GoodRuWiki specific change (bcg topic -- last)
        )
    else:
        fix_regularizer = FastFixPhiRegularizer(
            name='fix',
            parent_phi=phi0.iloc[common_words_phi0_indices, 1:],
            words=common_words,
            topic_names=phi.columns[:-1],  # TODO: GoodRuWiki specific change (bcg topic -- last)
        )

    result = fit_and_compute_scores(
        model, dataset,
        target_topic_indices=list(range(phi.shape[1])),
        custom_regularizers = {
            fix_regularizer.name: fix_regularizer,
        }
    )

    print('Check after fit:')
    diff_tops2 = check_top_words(phi, top_words)  # Whatever...

    assert diff_tops1 == diff_tops2

    fair_ppl_free = result['scores']['perplexity']

    del model, phi, fix_regularizer, result



    if has_bcg:
        model, phi, _ = init_model_and_phi(
            num_topics=num_specific_topics + 1,  # background
            dataset=dataset, phi0=phi0
        )
        fix_regularizer = FastFixPhiRegularizer(
            name='fix',
            parent_phi=phi0.iloc[common_words_phi0_indices, :],  # Diff here
            words=common_words,
            topic_names=phi.columns,
        )
        result = fit_and_compute_scores(
            model, dataset,
            target_topic_indices=list(range(phi.shape[1])),
            custom_regularizers = {
                fix_regularizer.name: fix_regularizer,
            }
        )
        
        fair_ppl_fix = result['scores']['perplexity']
    
        del model, phi, fix_regularizer, result
    else:
        fair_ppl_fix = None
    

    
    model, phi, _ = init_model_and_phi(
        num_topics=num_specific_topics,  # TODO: diff here
        dataset=dataset, phi0=phi0
    )

    if not has_bcg:
        fix_regularizer = FastFixPhiRegularizer(
            name='fix',
            parent_phi=phi0.iloc[common_words_phi0_indices, :],  # TODO: diff here
            words=common_words,
            topic_names=phi.columns,
        )
    else:
        fix_regularizer = FastFixPhiRegularizer(
            name='fix',
            parent_phi=phi0.iloc[common_words_phi0_indices, 1:],  # TODO: diff here
            words=common_words,
            topic_names=phi.columns,
        )

    result = fit_and_compute_scores(
        model, dataset,
        target_topic_indices=list(range(phi.shape[1])),  # TODO: not bad a fix
        custom_regularizers = {
            fix_regularizer.name: fix_regularizer,
        }
    )

    unfair_ppl_banklike = result['scores']['perplexity']


    
    result['scores']['fair_ppl_free'] = fair_ppl_free
    result['scores']['fair_ppl_fix'] = fair_ppl_fix
    result['scores']['unfair_ppl_banklike'] = unfair_ppl_banklike

    assert result['scores']['fair_ppl_free'] < result['scores']['unfair_ppl_banklike']
    # assert result['scores']['fair_ppl_fix'] < result['scores']['unfair_ppl_banklike']

    result['scores']['coherence_20'] = float(result['scores']['coherence_20'])
    result['stats'] = {
        'num_topics': phi0.shape[1],
        'num_common_words': len(common_words),
        'num_model_words': phi.shape[0],
        'num_bt_words': phi0.shape[0],
        'top_diffs': diff_tops2,
    }

    results.append(result)

    print(result['scores'])
    print(result['stats'])

    dumped_result = json.dumps(
        results[-1], indent=4
    )

    with open(current_save_file_path, 'w') as f:
        f.write(dumped_result)

    del model, phi, fix_regularizer


with open(save_file_path, 'w') as f:
    f.write(
        json.dumps(
            results, indent=4
        )
    )

0
Already computed results: results/ruwikigood/bertopic/bertopic_0.json. Loading and skipping...
1
Already computed results: results/ruwikigood/bertopic/bertopic_1.json. Loading and skipping...
2
Already computed results: results/ruwikigood/bertopic/bertopic_2.json. Loading and skipping...
3
Already computed results: results/ruwikigood/bertopic/bertopic_3.json. Loading and skipping...
4
Already computed results: results/ruwikigood/bertopic/bertopic_4.json. Loading and skipping...
5
Already computed results: results/ruwikigood/bertopic/bertopic_5.json. Loading and skipping...
6
Already computed results: results/ruwikigood/bertopic/bertopic_6.json. Loading and skipping...
7
Already computed results: results/ruwikigood/bertopic/bertopic_7.json. Loading and skipping...
8
Already computed results: results/ruwikigood/bertopic/bertopic_8.json. Loading and skipping...
9
Num model topics: 20.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
topic_3
topic_4
topic_5
topic_6
topic_7
topic_8
topic_9
topic_10
topic_11
topic_12
topic_13
topic_14
topic_15
topic_16
topic_17
topic_18
{'fix': <__main__.FastFixPhiRegularizer object at 0x7efdd0c84220>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
topic_3
topic_4
topic_5
topic_6
topic_7
topic_8
topic_9
topic_10
topic_11
topic_12
topic_13
topic_14
topic_15
topic_16
topic_17
topic_18

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7efdd0c84a00>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7efdd26bad60>}
{'perplexity': 5895.42626953125, 'coherence_20': 1.1196676849338756, 'diversity_euclidean': 0.046595504069194583, 'diversity_jensenshannon': 0.6525033258730681, 'diversity_hellinger': 0.7551224333058685, 'diversity_cosine': 0.8021593817512747, 'fair_ppl_free': 3949.231201171875, 'fair_ppl_fix': 5893.16357421875, 'unfair_ppl_banklike': 5895.42626953125}
{'num_topics': 20, 'num_common_words': 264923, 'num_model_words': 264943, 'num_bt_words': 264925, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}]}
10
Num model topics: 15.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
topic_3
topic_4
topic_5
topic_6
topic_7
topic_8
topic_9
topic_10
topic_11
topic_12
topic_13
{'fix': <__main__.FastFixPhiRegularizer object at 0x7efd98787310>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
topic_3
topic_4
topic_5
topic_6
topic_7
topic_8
topic_9
topic_10
topic_11
topic_12
topic_13

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7efdd269d190>}
{'perplexity': 6403.1298828125, 'coherence_20': 1.1029059509527626, 'diversity_euclidean': 0.049180012980306116, 'diversity_jensenshannon': 0.6554041351443206, 'diversity_hellinger': 0.759122260710975, 'diversity_cosine': 0.8119884527962906, 'fair_ppl_free': 4348.85546875, 'fair_ppl_fix': None, 'unfair_ppl_banklike': 6403.1298828125}
{'num_topics': 15, 'num_common_words': 264923, 'num_model_words': 264943, 'num_bt_words': 264925, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}]}
11
Num model topics: 20.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
topic_3
topic_4
topic_5
topic_6
topic_7
topic_8
topic_9
topic_10
topic_11
topic_12
topic_13
topic_14
topic_15
topic_16
topic_17
topic_18
{'fix': <__main__.FastFixPhiRegularizer object at 0x7efdd39fa1f0>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
topic_3
topic_4
topic_5
topic_6
topic_7
topic_8
topic_9
topic_10
topic_11
topic_12
topic_13
topic_14
topic_15
topic_16
topic_17
topic_18

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7efd582eca90>}
{'perplexity': 5802.18505859375, 'coherence_20': 1.0534770406884486, 'diversity_euclidean': 0.047727349440320775, 'diversity_jensenshannon': 0.6475520845549428, 'diversity_hellinger': 0.7485759239040483, 'diversity_cosine': 0.7858666141760837, 'fair_ppl_free': 3867.205810546875, 'fair_ppl_fix': None, 'unfair_ppl_banklike': 5802.18505859375}
{'num_topics': 20, 'num_common_words': 264923, 'num_model_words': 264943, 'num_bt_words': 264925, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}]}
12
Num model topics: 20.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
topic_3
topic_4
topic_5
topic_6
topic_7
topic_8
topic_9
topic_10
topic_11
topic_12
topic_13
topic_14
topic_15
topic_16
topic_17
topic_18
{'fix': <__main__.FastFixPhiRegularizer object at 0x7efd992571f0>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
topic_3
topic_4
topic_5
topic_6
topic_7
topic_8
topic_9
topic_10
topic_11
topic_12
topic_13
topic_14
topic_15
topic_16
topic_17
topic_18

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7efe697c86a0>}
{'perplexity': 5847.990234375, 'coherence_20': 1.1098364875592734, 'diversity_euclidean': 0.04640226152975057, 'diversity_jensenshannon': 0.6533440653243332, 'diversity_hellinger': 0.7564265144425691, 'diversity_cosine': 0.8067909616283576, 'fair_ppl_free': 3920.33984375, 'fair_ppl_fix': None, 'unfair_ppl_banklike': 5847.990234375}
{'num_topics': 20, 'num_common_words': 264923, 'num_model_words': 264943, 'num_bt_words': 264925, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}]}
13
Num model topics: 18.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
topic_3
topic_4
topic_5
topic_6
topic_7
topic_8
topic_9
topic_10
topic_11
topic_12
topic_13
topic_14
topic_15
topic_16
{'fix': <__main__.FastFixPhiRegularizer object at 0x7efe11078d30>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
topic_3
topic_4
topic_5
topic_6
topic_7
topic_8
topic_9
topic_10
topic_11
topic_12
topic_13
topic_14
topic_15
topic_16

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7efe127efe50>}
{'perplexity': 6124.7294921875, 'coherence_20': 1.1939362759906933, 'diversity_euclidean': 0.04876450854551621, 'diversity_jensenshannon': 0.6589477690779391, 'diversity_hellinger': 0.7634722854210099, 'diversity_cosine': 0.8155489859451857, 'fair_ppl_free': 4148.36279296875, 'fair_ppl_fix': None, 'unfair_ppl_banklike': 6124.7294921875}
{'num_topics': 18, 'num_common_words': 264923, 'num_model_words': 264943, 'num_bt_words': 264925, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}]}
14
Num model topics: 19.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
topic_3
topic_4
topic_5
topic_6
topic_7
topic_8
topic_9
topic_10
topic_11
topic_12
topic_13
topic_14
topic_15
topic_16
topic_17
{'fix': <__main__.FastFixPhiRegularizer object at 0x7efdd064f070>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
topic_3
topic_4
topic_5
topic_6
topic_7
topic_8
topic_9
topic_10
topic_11
topic_12
topic_13
topic_14
topic_15
topic_16
topic_17

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7efe48d0a940>}
{'perplexity': 5911.71044921875, 'coherence_20': 1.1195322844683164, 'diversity_euclidean': 0.04583980525234484, 'diversity_jensenshannon': 0.6487987671143488, 'diversity_hellinger': 0.7504401070829374, 'diversity_cosine': 0.7964384930641221, 'fair_ppl_free': 3959.352294921875, 'fair_ppl_fix': None, 'unfair_ppl_banklike': 5911.71044921875}
{'num_topics': 19, 'num_common_words': 264923, 'num_model_words': 264943, 'num_bt_words': 264925, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}]}
15
Num model topics: 17.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
topic_3
topic_4
topic_5
topic_6
topic_7
topic_8
topic_9
topic_10
topic_11
topic_12
topic_13
topic_14
topic_15
{'fix': <__main__.FastFixPhiRegularizer object at 0x7efe4dd1cf10>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
topic_3
topic_4
topic_5
topic_6
topic_7
topic_8
topic_9
topic_10
topic_11
topic_12
topic_13
topic_14
topic_15

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7efd992578e0>}
{'perplexity': 5986.90185546875, 'coherence_20': 1.0768124710721338, 'diversity_euclidean': 0.04769296967190488, 'diversity_jensenshannon': 0.6434023954291492, 'diversity_hellinger': 0.7433121531799243, 'diversity_cosine': 0.7832083010046635, 'fair_ppl_free': 4059.8076171875, 'fair_ppl_fix': None, 'unfair_ppl_banklike': 5986.90185546875}
{'num_topics': 17, 'num_common_words': 264923, 'num_model_words': 264943, 'num_bt_words': 264925, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}]}
16
Num model topics: 21.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
topic_3
topic_4
topic_5
topic_6
topic_7
topic_8
topic_9
topic_10
topic_11
topic_12
topic_13
topic_14
topic_15
topic_16
topic_17
topic_18
topic_19
{'fix': <__main__.FastFixPhiRegularizer object at 0x7efe2b1ab550>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
topic_3
topic_4
topic_5
topic_6
topic_7
topic_8
topic_9
topic_10
topic_11
topic_12
topic_13
topic_14
topic_15
topic_16
topic_17
topic_18
topic_19

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7efd9ab4ee50>}
{'perplexity': 5960.85595703125, 'coherence_20': 1.1353820623976068, 'diversity_euclidean': 0.04592260340939134, 'diversity_jensenshannon': 0.6502660369219002, 'diversity_hellinger': 0.7531628578990164, 'diversity_cosine': 0.8065988191934875, 'fair_ppl_free': 3987.77490234375, 'fair_ppl_fix': None, 'unfair_ppl_banklike': 5960.85595703125}
{'num_topics': 21, 'num_common_words': 264923, 'num_model_words': 264943, 'num_bt_words': 264925, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}]}
17
Num model topics: 18.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
topic_3
topic_4
topic_5
topic_6
topic_7
topic_8
topic_9
topic_10
topic_11
topic_12
topic_13
topic_14
topic_15
topic_16
{'fix': <__main__.FastFixPhiRegularizer object at 0x7efe69b2d370>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
topic_3
topic_4
topic_5
topic_6
topic_7
topic_8
topic_9
topic_10
topic_11
topic_12
topic_13
topic_14
topic_15
topic_16

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7efdd01eb8e0>}
{'perplexity': 5992.18359375, 'coherence_20': 1.0930774310141775, 'diversity_euclidean': 0.048036218133063614, 'diversity_jensenshannon': 0.6478780085010933, 'diversity_hellinger': 0.7493326143540024, 'diversity_cosine': 0.7966634655432945, 'fair_ppl_free': 4035.344970703125, 'fair_ppl_fix': None, 'unfair_ppl_banklike': 5992.18359375}
{'num_topics': 18, 'num_common_words': 264923, 'num_model_words': 264943, 'num_bt_words': 264925, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}]}
18
Num model topics: 20.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
topic_3
topic_4
topic_5
topic_6
topic_7
topic_8
topic_9
topic_10
topic_11
topic_12
topic_13
topic_14
topic_15
topic_16
topic_17
topic_18
{'fix': <__main__.FastFixPhiRegularizer object at 0x7efd92e9b2b0>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
topic_3
topic_4
topic_5
topic_6
topic_7
topic_8
topic_9
topic_10
topic_11
topic_12
topic_13
topic_14
topic_15
topic_16
topic_17
topic_18

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7efdd26bad60>}
{'perplexity': 6006.9013671875, 'coherence_20': 1.1946819355160077, 'diversity_euclidean': 0.04867373147741286, 'diversity_jensenshannon': 0.6568019697282852, 'diversity_hellinger': 0.7610876702424425, 'diversity_cosine': 0.8225186116846672, 'fair_ppl_free': 4053.443115234375, 'fair_ppl_fix': None, 'unfair_ppl_banklike': 6006.9013671875}
{'num_topics': 20, 'num_common_words': 264923, 'num_model_words': 264943, 'num_bt_words': 264925, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}]}
19
Num model topics: 18.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
topic_3
topic_4
topic_5
topic_6
topic_7
topic_8
topic_9
topic_10
topic_11
topic_12
topic_13
topic_14
topic_15
topic_16
{'fix': <__main__.FastFixPhiRegularizer object at 0x7efe118e41f0>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
topic_3
topic_4
topic_5
topic_6
topic_7
topic_8
topic_9
topic_10
topic_11
topic_12
topic_13
topic_14
topic_15
topic_16

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7efe697d4670>}
{'perplexity': 6198.82470703125, 'coherence_20': 1.167396157915651, 'diversity_euclidean': 0.04846391519781991, 'diversity_jensenshannon': 0.6637423358186256, 'diversity_hellinger': 0.7705792274710391, 'diversity_cosine': 0.8199637123306177, 'fair_ppl_free': 4194.4365234375, 'fair_ppl_fix': None, 'unfair_ppl_banklike': 6198.82470703125}
{'num_topics': 18, 'num_common_words': 264923, 'num_model_words': 264943, 'num_bt_words': 264925, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}]}

In [218]:
phi.columns

NameError: name 'phi' is not defined

In [219]:
1-201

1

In [ ]:
! cat $RESULTS_FOLDER_PATH/9/top_words.json

In [177]:
NUM_TOPICS

20

In [176]:
phi.shape

(264943, 17)

In [149]:
phi.head()

                              topic_0  topic_1  topic_2  topic_3  topic_4  \
modality    token
@lemmatized gdi          2.563433e-07      0.0      0.0      0.0      0.0
            egosoft      2.563433e-07      0.0      0.0      0.0      0.0
            ogame        4.866823e-07      0.0      0.0      0.0      0.0
            матёс        2.563433e-07      0.0      0.0      0.0      0.0
            шильцевский  2.563433e-07      0.0      0.0      0.0      0.0

                         topic_5  topic_6  topic_7  topic_8  topic_9  \
modality    token
@lemmatized gdi              0.0      0.0      0.0      0.0      0.0
            egosoft          0.0      0.0      0.0      0.0      0.0
            ogame            0.0      0.0      0.0      0.0      0.0
            матёс            0.0      0.0      0.0      0.0      0.0
            шильцевский      0.0      0.0      0.0      0.0      0.0

                         topic_10  topic_11  topic_12  topic_13  topic_14  \
modality    token
@lemmatized gdi               0.0       0.0       0.0       0.0       0.0
            egosoft           0.0       0.0       0.0       0.0       0.0
            ogame             0.0       0.0       0.0       0.0       0.0
            матёс             0.0       0.0       0.0       0.0       0.0
            шильцевский       0.0       0.0       0.0       0.0       0.0

                         topic_15  topic_16  topic_17
modality    token
@lemmatized gdi               0.0       0.0  0.000004
            egosoft           0.0       0.0  0.000004
            ogame             0.0       0.0  0.000004
            матёс             0.0       0.0  0.000004
            шильцевский       0.0       0.0  0.000004

In [163]:
phi['topic_16'].sort_values(ascending=False)[:20]

modality     token
@lemmatized  покемон     0.043134
             игра        0.017567
             pokemon     0.015402
             nintendo    0.009551
             игрок       0.007089
             пикача      0.006280
             серия       0.006174
             тренер      0.005622
             game        0.005394
             эш          0.004943
             red         0.004613
             аниме       0.004124
             blue        0.003957
             сериал      0.003954
             бой         0.003804
             boy         0.003653
             регион      0.003261
             ruby        0.003222
             sapphire    0.003204
             игровой     0.002989
Name: topic_16, dtype: float64

In [168]:
phi0['topic_16'].sort_values(ascending=False)[:20]

@lemmatized  покемон     0.268106
             игра        0.109189
             pokemon     0.095733
             nintendo    0.059366
             игрок       0.044063
             пикача      0.039032
             серия       0.038374
             тренер      0.034944
             game        0.033527
             эш          0.030722
             red         0.028671
             аниме       0.025636
             blue        0.024596
             сериал      0.024576
             бой         0.023642
             boy         0.022706
             регион      0.020267
             ruby        0.020025
             sapphire    0.019915
             игровой     0.018577
Name: topic_16, dtype: float64

In [167]:
phi0['topic_15'].sort_values(ascending=False)[:20]

@lemmatized  малдёр           0.138623
             эпизод           0.116320
             агент            0.049091
             person           0.047593
             сериал           0.041120
             тумс             0.037865
             секретный        0.036518
             картер           0.029176
             фбр              0.027501
             материал         0.027373
             серия            0.025630
             fox              0.024078
             сцена            0.023637
             съёмка           0.021304
             сценарий         0.019872
             малдрать         0.019669
             домохозяйство    0.019580
             премьера         0.018778
             сезон            0.018749
             расследовать     0.017247
Name: topic_15, dtype: float64

In [166]:
top_words['topic_15']

[['малдёр', 0.1386228369280603],
 ['эпизод', 0.11631993906668163],
 ['агент', 0.049090525093543905],
 ['person', 0.047593315648508897],
 ['сериал', 0.04111972980469913],
 ['тумс', 0.03786522487257441],
 ['секретный', 0.03651821212407736],
 ['картер', 0.02917647118432673],
 ['фбр', 0.027500518993828337],
 ['материал', 0.027373011451345342],
 ['серия', 0.025629757135196673],
 ['fox', 0.024077945281126726],
 ['сцена', 0.023637398476370437],
 ['съёмка', 0.021304282715615113],
 ['сценарий', 0.019872107173757463],
 ['малдрать', 0.019668540165023844],
 ['домохозяйство', 0.019580396028063024],
 ['премьера', 0.01877765221036062],
 ['сезон', 0.018749264086400926],
 ['расследовать', 0.01724706793607795]]

In [111]:
phi.shape

(264943, 17)

In [112]:
phi0.shape

(264925, 17)

In [66]:
phi.shape, len(top_words)

((264943, 17), 17)

In [46]:
check_top_words(phi, top_words)

Skipping background topic: background_1.
topic_0
  WTF: {'птица', 'клетка', 'вид', 'самка', 'ген', 'длина', 'белка', 'род', 'рнк', 'некоторый', 'акула', 'самец', 'белок', 'днк', 'растение'} {'большой', 'время', 'армия', 'книга', 'век', 'работа', 'находиться', 'стать', 'язык', 'город', 'война', 'часть', 'получить', 'человек', 'имя'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_1
  WTF: {'политический', 'римский', 'претор', 'цезарь', 'сципион', 'гракх', 'марка', 'квинта', 'рим', 'сын', 'красс', 'война', 'сенат', 'источник', 'армия', 'консул'} {'хороший', 'игровой', 'версия', 'актёр', 'игрок', 'герой', 'серия', 'фильм', 'сериал', 'сцена', 'игра', 'роль', 'эпизод', 'режиссёр', 'картина', 'персонаж'}
  WTF?!?!? 16
  WTF?!?!? 16
topic_2
  WTF: {'выиграть', 'счёт', 'команда', 'игрок', 'гол', 'сезон', 'игра', 'клуб', 'стать', 'матч', 'тренер', 'турнир', 'кубок', 'сборный', 'забить', 'победа', 'лига', 'чемпионат'} {'птица', 'клетка', 'белок', 'вид', 'мочь', 'самка', 'ген', 'иметь', 'длина', 'белка', 'род', 'рнк', 'некоторый', 'акула', 'самец', 'являться', 'днк', 'растение'}
  WTF?!?!? 18
  WTF?!?!? 18
topic_3
  WTF: {'хороший', 'песнь', 'сингл', 'композиция', 'альбом', 'музыкальный', 'концерт', 'запись', 'диск', 'выпустить', 'музыка', 'пластинка', 'записать', 'песня', 'музыкант', 'группа'} {'политический', 'римский', 'претор', 'цезарь', 'сципион', 'гракх', 'марка', 'квинта', 'рим', 'сын', 'красс', 'война', 'сенат', 'источник', 'армия', 'консул'}
  WTF?!?!? 16
  WTF?!?!? 16
topic_4
  WTF: {'шахматы', 'художественный', 'искусство', 'время', 'выставка', 'живопись', 'работа', 'художник', 'фигура', 'полотно', 'изобразить', 'портрет', 'галерея', 'картина', 'музей', 'искусствовед', 'изображение', 'писать'} {'выиграть', 'счёт', 'команда', 'игрок', 'гол', 'сезон', 'игра', 'клуб', 'стать', 'матч', 'тренер', 'турнир', 'кубок', 'сборный', 'забить', 'победа', 'лига', 'чемпионат'}
  WTF?!?!? 18
  WTF?!?!? 18
topic_5
  WTF: {'флот', 'мм', 'линкор', 'лодка', 'эскадра', 'тип', 'установка', 'снаряд', 'крейсер', 'проект', 'борт', 'орудие', 'линейный', 'скорость', 'корабль', 'палуба', 'башня', 'подводный'} {'хороший', 'песнь', 'сингл', 'композиция', 'альбом', 'время', 'музыкальный', 'концерт', 'запись', 'диск', 'выпустить', 'музыка', 'стать', 'пластинка', 'записать', 'песня', 'музыкант', 'группа'}
  WTF?!?!? 18
  WTF?!?!? 18
topic_6
  WTF: {'станция', 'железный', 'строительство', 'дорога', 'троллейбус', 'метрополитен', 'вагон', 'паровоз', 'метро', 'вестибюль', 'депо', 'трамвайный', 'состав', 'участок', 'поезд', 'линия', 'завод', 'дизель', 'московский'} {'художественный', 'художник', 'портрет', 'галерея', 'музей', 'изображение', 'выставка', 'изобразить', 'искусство', 'время', 'живопись', 'фигура', 'писать', 'person', 'работа', 'полотно', 'шахматы', 'картина', 'искусствовед'}
  WTF?!?!? 19
  WTF?!?!? 19
topic_7
  WTF: {'версия', 'робот', 'уровень', 'игровой', 'игрок', 'серия', 'прохождение', 'ёж', 'платформер', 'изумруд', 'sega', 'adventure', 'персонаж', 'hedgehog', 'консоль', 'игра', 'соника', 'кольцо', 'sonic'} {'линкор', 'установка', 'снаряд', 'крейсер', 'борт', 'линейный', 'подводный', 'эскадра', 'орудие', 'флот', 'проект', 'скорость', 'мм', 'лодка', 'год', 'тип', 'корабль', 'палуба', 'башня'}
  WTF?!?!? 19
  WTF?!?!? 19
topic_8
  WTF: {'изображение', 'шоу', 'перфорация', 'чемпион', 'фотограф', 'киноплёнка', 'съёмка', 'стать', 'негатив', 'время', 'поединок', 'матч', 'фотография', 'камера', 'титул', 'person', 'ринг', 'wwe', 'объектив'} {'станция', 'железный', 'строительство', 'дорога', 'троллейбус', 'метрополитен', 'вагон', 'паровоз', 'метро', 'вестибюль', 'депо', 'трамвайный', 'состав', 'участок', 'поезд', 'линия', 'завод', 'дизель', 'московский'}
  WTF?!?!? 19
  WTF?!?!? 19
topic_9
  WTF: {'смоленский', 'утвердить', 'официальный', 'город', 'изображение', 'золотой', 'городской', 'совет', 'район', 'символ', 'муниципальный', 'серебряный', 'год', 'символика', 'герб', 'щит', 'ставропольский', 'геральдический', 'гербовый'} {'версия', 'робот', 'уровень', 'игровой', 'игрок', 'серия', 'прохождение', 'ёж', 'платформер', 'изумруд', 'sega', 'adventure', 'персонаж', 'hedgehog', 'консоль', 'игра', 'соника', 'кольцо', 'sonic'}
  WTF?!?!? 19
  WTF?!?!? 19
topic_10
  WTF: {'использоваться', 'арабский', 'буква', 'язык', 'руно', 'латиница', 'письменность', 'букварь', 'знак', 'алфавит', 'звук', 'латинизировать', 'латинский', 'кириллический', 'рунический', 'диалект', 'кириллица', 'основа', 'руна'} {'изображение', 'шоу', 'перфорация', 'чемпион', 'фотограф', 'киноплёнка', 'съёмка', 'стать', 'негатив', 'время', 'поединок', 'матч', 'фотография', 'камера', 'титул', 'person', 'ринг', 'wwe', 'объектив'}
  WTF?!?!? 19
  WTF?!?!? 19
topic_11
  WTF: {'шерсть', 'сиб', 'крафт', 'клуб', 'холка', 'охотничий', 'охота', 'выставка', 'бульдог', 'крыса', 'карачаевский', 'собака', 'порода', 'окрас', 'стандарт', 'лошадь', 'морда', 'мочь', 'ухо'} {'смоленский', 'утвердить', 'официальный', 'город', 'изображение', 'золотой', 'городской', 'совет', 'район', 'символ', 'муниципальный', 'серебряный', 'person', 'символика', 'герб', 'щит', 'ставропольский', 'геральдический', 'гербовый'}
  WTF?!?!? 19
  WTF?!?!? 19
topic_12
  WTF: {'кухня', 'горчица', 'индонезия', 'вино', 'соус', 'гонконг', 'приготовление', 'писко', 'лапша', 'блюдо', 'суп', 'кулинарный', 'ресторан', 'напиток', 'хлеб', 'мясо', 'овощ', 'продукт', 'различный', 'рис'} {'использоваться', 'арабский', 'буква', 'язык', 'руно', 'латиница', 'письменность', 'букварь', 'знак', 'алфавит', 'звук', 'латинизировать', 'латинский', 'кириллический', 'рунический', 'диалект', 'кириллица', 'год', 'основа', 'руна'}
  WTF?!?!? 20
  WTF?!?!? 20
topic_13
  WTF: {'расследовать', 'агент', 'премьера', 'картер', 'малдрать', 'серия', 'съёмка', 'сцена', 'материал', 'секретный', 'fox', 'домохозяйство', 'фбр', 'сценарий', 'эпизод', 'тумс', 'малдёр', 'person', 'сезон', 'сериал'} {'шерсть', 'сиб', 'крафт', 'клуб', 'холка', 'охотничий', 'охота', 'выставка', 'бульдог', 'крыса', 'карачаевский', 'собака', 'порода', 'окрас', 'стандарт', 'лошадь', 'морда', 'мочь', 'ухо', 'год'}
  WTF?!?!? 20
  WTF?!?!? 20
topic_14
  WTF: {'sapphire', 'game', 'red', 'boy', 'игровой', 'игрок', 'pokemon', 'серия', 'покемон', 'регион', 'blue', 'бой', 'тренер', 'nintendo', 'ruby', 'пикача', 'эш', 'сериал', 'игра', 'аниме'} {'кухня', 'горчица', 'индонезия', 'вино', 'соус', 'гонконг', 'приготовление', 'писко', 'лапша', 'блюдо', 'суп', 'кулинарный', 'ресторан', 'напиток', 'хлеб', 'мясо', 'овощ', 'продукт', 'различный', 'рис'}
  WTF?!?!? 20
  WTF?!?!? 20
topic_15
  WTF: {'syrene', 'варнецкий', 'morskie', 'карасиньский', 'мессалить', 'мишечкина', 'syrenie', 'мосеево', 'ogame', 'зиминьский', 'тарапун', 'дпрс', 'egosoft', 'шильцевский', 'gdi', 'гардать', 'бостоновый', 'bagatel', 'zaiks', 'матёс'} {'расследовать', 'агент', 'премьера', 'картер', 'малдрать', 'серия', 'съёмка', 'сцена', 'материал', 'секретный', 'fox', 'домохозяйство', 'фбр', 'сценарий', 'эпизод', 'тумс', 'малдёр', 'person', 'сезон', 'сериал'}
  WTF?!?!? 20
  WTF?!?!? 20

[{'total': 30, 'lost_bt': 15, 'lost_model': 15},
 {'total': 32, 'lost_bt': 16, 'lost_model': 16},
 {'total': 36, 'lost_bt': 18, 'lost_model': 18},
 {'total': 32, 'lost_bt': 16, 'lost_model': 16},
 {'total': 36, 'lost_bt': 18, 'lost_model': 18},
 {'total': 36, 'lost_bt': 18, 'lost_model': 18},
 {'total': 38, 'lost_bt': 19, 'lost_model': 19},
 {'total': 38, 'lost_bt': 19, 'lost_model': 19},
 {'total': 38, 'lost_bt': 19, 'lost_model': 19},
 {'total': 38, 'lost_bt': 19, 'lost_model': 19},
 {'total': 38, 'lost_bt': 19, 'lost_model': 19},
 {'total': 38, 'lost_bt': 19, 'lost_model': 19},
 {'total': 40, 'lost_bt': 20, 'lost_model': 20},
 {'total': 40, 'lost_bt': 20, 'lost_model': 20},
 {'total': 40, 'lost_bt': 20, 'lost_model': 20},
 {'total': 40, 'lost_bt': 20, 'lost_model': 20}]

In [59]:
! cat '/data_mil/shared/CompressaAI/BERTopic/results/ruwikigood/0/top_words.json'

{
    "background_1": false,
    "topic_0": [
        [
            "person",
            0.0422573407299807
        ],
        [
            "год",
            0.029529524372319878
        ],
        [
            "время",
            0.012102291687147673
        ],
        [
            "стать",
            0.010141119486329416
        ],
        [
            "город",
            0.009177191305420053
        ],
        [
            "человек",
            0.0085192620682621
        ],
        [
            "часть",
            0.008051808916342945
        ],
        [
            "век",
            0.007805910871055686
        ],
        [
            "имя",
            0.007420150137652238
        ],
        [
            "армия",
            0.007204607579826462
        ],
        [
            "являться",
            0.007019571092204588
        ],
        [
            "мочь",
            0.006865394327750571
        ],
        [
            "иметь",
            0.006847778180194606
        ],
        [
            "война",
            0.006679773966025352
        ],
        [
            "получить",
            0.006672689870839094
        ],
        [
            "работа",
            0.006517804032917204
        ],
        [
            "большой",
            0.006191131955561368
        ],
        [
            "находиться",
            0.005972721385662755
        ],
        [
            "язык",
            0.005945349787161841
        ],
        [
            "книга",
            0.005661034032538145
        ]
    ],
    "topic_1": [
        [
            "person",
            0.044235989853675974
        ],
        [
            "игра",
            0.0387382873759443
        ],
        [
            "фильм",
            0.034460608860536146
        ],
        [
            "год",
            0.021440806375940213
        ],
        [
            "персонаж",
            0.018763569372780647
        ],
        [
            "роль",
            0.01691528654003225
        ],
        [
            "время",
            0.013179582065132664
        ],
        [
            "сцена",
            0.012967765359657869
        ],
        [
            "герой",
            0.012617957383598114
        ],
        [
            "актёр",
            0.01202547379667657
        ],
        [
            "серия",
            0.01188295046266246
        ],
        [
            "режиссёр",
            0.01181331044036697
        ],
        [
            "игрок",
            0.011805007576893822
        ],
        [
            "стать",
            0.011129362726140676
        ],
        [
            "сериал",
            0.011006356914471157
        ],
        [
            "картина",
            0.01080528813709529
        ],
        [
            "хороший",
            0.010352734596734994
        ],
        [
            "игровой",
            0.009919317386098348
        ],
        [
            "эпизод",
            0.009715262708623107
        ],
        [
            "версия",
            0.009560538600799823
        ]
    ],
    "topic_2": [
        [
            "вид",
            0.030215148673318974
        ],
        [
            "клетка",
            0.02579397754963481
        ],
        [
            "мочь",
            0.022082817407119912
        ],
        [
            "птица",
            0.020521085282441655
        ],
        [
            "акула",
            0.01657235038142157
        ],
        [
            "являться",
            0.014445202933896511
        ],
        [
            "person",
            0.014365602795943212
        ],
        [
            "ген",
            0.013378943817396719
        ],
        [
            "некоторый",
            0.013116810594674731
        ],
        [
            "растение",
            0.012987671436217459
        ],
        [
            "белок",
            0.01236520674394188
        ],
        [
            "самка",
            0.012306624995602205
        ],
        [
            "длина",
            0.012054247200103235
        ],
        [
            "иметь",
            0.011887324754242687
        ],
        [
            "рнк",
            0.01160610247693715
        ],
        [
            "белка",
            0.01137567370888491
        ],
        [
            "год",
            0.01112030857944126
        ],
        [
            "род",
            0.010888929805607668
        ],
        [
            "днк",
            0.010733196001582826
        ],
        [
            "самец",
            0.010614612497904003
        ]
    ],
    "topic_3": [
        [
            "person",
            0.0841527483812516
        ],
        [
            "консул",
            0.04306035529257968
        ],
        [
            "цезарь",
            0.033783847022959584
        ],
        [
            "год",
            0.033760342571942735
        ],
        [
            "рим",
            0.033076312124254936
        ],
        [
            "квинта",
            0.03255117036907093
        ],
        [
            "римский",
            0.02469154489409693
        ],
        [
            "сципион",
            0.023912239284115674
        ],
        [
            "война",
            0.022948577283771903
        ],
        [
            "сенат",
            0.021666185636563192
        ],
        [
            "стать",
            0.018245147251432565
        ],
        [
            "марка",
            0.017272737985466857
        ],
        [
            "источник",
            0.016012977746414914
        ],
        [
            "армия",
            0.016011318583284813
        ],
        [
            "время",
            0.013742947952166275
        ],
        [
            "красс",
            0.012812105236022591
        ],
        [
            "сын",
            0.01265868695501787
        ],
        [
            "гракх",
            0.011985725865605869
        ],
        [
            "претор",
            0.011886226274606225
        ],
        [
            "политический",
            0.0117890838085003
        ]
    ],
    "topic_4": [
        [
            "матч",
            0.06196697543819613
        ],
        [
            "person",
            0.05221854822208545
        ],
        [
            "команда",
            0.05218490045127047
        ],
        [
            "сезон",
            0.042307008781434355
        ],
        [
            "клуб",
            0.03819269650922297
        ],
        [
            "год",
            0.0380927930674332
        ],
        [
            "чемпионат",
            0.034639781580528425
        ],
        [
            "игра",
            0.03450288595893967
        ],
        [
            "игрок",
            0.03199732699485274
        ],
        [
            "турнир",
            0.025576535987194084
        ],
        [
            "стать",
            0.025513023294643992
        ],
        [
            "сборный",
            0.024757138329553903
        ],
        [
            "счёт",
            0.022622645441115988
        ],
        [
            "кубок",
            0.021777351417733536
        ],
        [
            "гол",
            0.02165673397872249
        ],
        [
            "лига",
            0.021068714892202287
        ],
        [
            "забить",
            0.02085347476358155
        ],
        [
            "тренер",
            0.02057802327536501
        ],
        [
            "победа",
            0.020071746702425588
        ],
        [
            "выиграть",
            0.018818786140917237
        ]
    ],
    "topic_5": [
        [
            "альбом",
            0.08493066475701502
        ],
        [
            "группа",
            0.05587826508543907
        ],
        [
            "песня",
            0.04532092132491192
        ],
        [
            "person",
            0.03895056100844638
        ],
        [
            "песнь",
            0.028126683410859037
        ],
        [
            "год",
            0.027452891855811856
        ],
        [
            "музыкант",
            0.026701176520108293
        ],
        [
            "запись",
            0.022405928954889954
        ],
        [
            "композиция",
            0.0219877561953017
        ],
        [
            "сингл",
            0.021787665368888435
        ],
        [
            "концерт",
            0.020802094454072044
        ],
        [
            "музыкальный",
            0.0204561812231181
        ],
        [
            "музыка",
            0.017425156848285345
        ],
        [
            "выпустить",
            0.017115151499441632
        ],
        [
            "стать",
            0.016572787206695635
        ],
        [
            "время",
            0.015590105348982884
        ],
        [
            "пластинка",
            0.015588264308807135
        ],
        [
            "записать",
            0.015469923010697051
        ],
        [
            "хороший",
            0.013482147899156341
        ],
        [
            "диск",
            0.013382640027254948
        ]
    ],
    "topic_6": [
        [
            "картина",
            0.06784141674309457
        ],
        [
            "художник",
            0.05655445524043672
        ],
        [
            "person",
            0.051050738681211495
        ],
        [
            "год",
            0.03047461554620188
        ],
        [
            "полотно",
            0.02301409077229612
        ],
        [
            "портрет",
            0.02174523409115007
        ],
        [
            "работа",
            0.019929193755247404
        ],
        [
            "выставка",
            0.019098189503231073
        ],
        [
            "искусство",
            0.016894644627850196
        ],
        [
            "время",
            0.014427125875090626
        ],
        [
            "живопись",
            0.01422666786493558
        ],
        [
            "музей",
            0.014077649749664118
        ],
        [
            "изобразить",
            0.013730051487358159
        ],
        [
            "искусствовед",
            0.013135474258319449
        ],
        [
            "фигура",
            0.01296862441906373
        ],
        [
            "художественный",
            0.012674702304604728
        ],
        [
            "галерея",
            0.0117330969308483
        ],
        [
            "писать",
            0.011322937727904742
        ],
        [
            "изображение",
            0.010742692127324531
        ],
        [
            "шахматы",
            0.010589871197274208
        ]
    ],
    "topic_7": [
        [
            "корабль",
            0.061135027330581786
        ],
        [
            "крейсер",
            0.04963131147216833
        ],
        [
            "мм",
            0.04275156172559051
        ],
        [
            "флот",
            0.030321497702430842
        ],
        [
            "орудие",
            0.028826435016410797
        ],
        [
            "год",
            0.028147663960723476
        ],
        [
            "person",
            0.025709069278324614
        ],
        [
            "линкор",
            0.024130824238685043
        ],
        [
            "тип",
            0.023396053612308815
        ],
        [
            "палуба",
            0.02004251639991332
        ],
        [
            "башня",
            0.019957936356259004
        ],
        [
            "снаряд",
            0.019590201837591813
        ],
        [
            "проект",
            0.01795391720800892
        ],
        [
            "линейный",
            0.01771271020855401
        ],
        [
            "установка",
            0.01701120597969879
        ],
        [
            "подводный",
            0.016389748674991936
        ],
        [
            "борт",
            0.016232577539619927
        ],
        [
            "лодка",
            0.015513192064940451
        ],
        [
            "эскадра",
            0.015502352053428996
        ],
        [
            "скорость",
            0.01493337958587967
        ]
    ],
    "topic_8": [
        [
            "станция",
            0.09007570400734867
        ],
        [
            "паровоз",
            0.05712851428046863
        ],
        [
            "поезд",
            0.05220709177793897
        ],
        [
            "вагон",
            0.04785589716475774
        ],
        [
            "линия",
            0.042825393690960604
        ],
        [
            "год",
            0.03639166982837442
        ],
        [
            "дорога",
            0.036030782729962144
        ],
        [
            "железный",
            0.02937242809046936
        ],
        [
            "строительство",
            0.02147981394835432
        ],
        [
            "депо",
            0.02134908469252574
        ],
        [
            "метрополитен",
            0.02116810714040615
        ],
        [
            "метро",
            0.02033395496220223
        ],
        [
            "вестибюль",
            0.02026491288475578
        ],
        [
            "трамвайный",
            0.020000663472535426
        ],
        [
            "завод",
            0.018815191362806887
        ],
        [
            "участок",
            0.01873808927805568
        ],
        [
            "троллейбус",
            0.018409484961187012
        ],
        [
            "московский",
            0.018129590535350643
        ],
        [
            "дизель",
            0.01780968582432959
        ],
        [
            "состав",
            0.0163403296313843
        ]
    ],
    "topic_9": [
        [
            "sonic",
            0.17224179961986724
        ],
        [
            "игра",
            0.09250357884223097
        ],
        [
            "hedgehog",
            0.062336305907061705
        ],
        [
            "соника",
            0.05144687581579275
        ],
        [
            "уровень",
            0.04379958930968486
        ],
        [
            "персонаж",
            0.04328221924932132
        ],
        [
            "sega",
            0.03696724448877664
        ],
        [
            "игрок",
            0.03614787996833785
        ],
        [
            "серия",
            0.0334399505798377
        ],
        [
            "ёж",
            0.030774407410768773
        ],
        [
            "игровой",
            0.029981579029404206
        ],
        [
            "adventure",
            0.026562938105981516
        ],
        [
            "изумруд",
            0.02527885110402573
        ],
        [
            "консоль",
            0.024706191513924336
        ],
        [
            "person",
            0.023514575900293433
        ],
        [
            "кольцо",
            0.02265654193954611
        ],
        [
            "версия",
            0.022046541272303464
        ],
        [
            "прохождение",
            0.019906168261542755
        ],
        [
            "робот",
            0.019274077825312413
        ],
        [
            "платформер",
            0.019186521912468522
        ]
    ],
    "topic_10": [
        [
            "фотография",
            0.07949930887290067
        ],
        [
            "person",
            0.044749892550015505
        ],
        [
            "шоу",
            0.03646249023138975
        ],
        [
            "wwe",
            0.03322337247139302
        ],
        [
            "фотограф",
            0.032064203978450535
        ],
        [
            "киноплёнка",
            0.029497345665161136
        ],
        [
            "год",
            0.027096881385825108
        ],
        [
            "поединок",
            0.02469935300881912
        ],
        [
            "матч",
            0.022917267867726868
        ],
        [
            "титул",
            0.022073996551174712
        ],
        [
            "время",
            0.018916523622722472
        ],
        [
            "стать",
            0.018366916681042282
        ],
        [
            "изображение",
            0.01731905166892394
        ],
        [
            "объектив",
            0.017194229803491567
        ],
        [
            "негатив",
            0.017075878921995795
        ],
        [
            "съёмка",
            0.016807988223792928
        ],
        [
            "чемпион",
            0.01637911188772787
        ],
        [
            "камера",
            0.016219134978719078
        ],
        [
            "ринг",
            0.01579863206172525
        ],
        [
            "перфорация",
            0.014517574126471908
        ]
    ],
    "topic_11": [
        [
            "герб",
            0.2465816569430666
        ],
        [
            "геральдический",
            0.07565315301302024
        ],
        [
            "щит",
            0.06574001642538452
        ],
        [
            "город",
            0.06472526715142707
        ],
        [
            "муниципальный",
            0.051088791843450526
        ],
        [
            "символ",
            0.050724240604793185
        ],
        [
            "золотой",
            0.04685224557003737
        ],
        [
            "городской",
            0.04228975512000389
        ],
        [
            "утвердить",
            0.03960165858245089
        ],
        [
            "год",
            0.03697373118002053
        ],
        [
            "гербовый",
            0.03219191674981601
        ],
        [
            "символика",
            0.03166492442243593
        ],
        [
            "совет",
            0.030213306456932862
        ],
        [
            "район",
            0.029853728575348425
        ],
        [
            "серебряный",
            0.029478232965183936
        ],
        [
            "ставропольский",
            0.028850879974333922
        ],
        [
            "изображение",
            0.028104075540310768
        ],
        [
            "person",
            0.026231009452910778
        ],
        [
            "смоленский",
            0.025017039737062645
        ],
        [
            "официальный",
            0.024968445670692816
        ]
    ],
    "topic_12": [
        [
            "алфавит",
            0.2559041872459918
        ],
        [
            "письменность",
            0.12949297302667126
        ],
        [
            "буква",
            0.1243270131734294
        ],
        [
            "язык",
            0.09294793491305166
        ],
        [
            "кириллица",
            0.051794533046437205
        ],
        [
            "год",
            0.04602755907105228
        ],
        [
            "букварь",
            0.038154984384602235
        ],
        [
            "кириллический",
            0.037887338369330094
        ],
        [
            "знак",
            0.037745484000844404
        ],
        [
            "использоваться",
            0.03652142182903645
        ],
        [
            "основа",
            0.03614480966087923
        ],
        [
            "латиница",
            0.03290414894963932
        ],
        [
            "латинизировать",
            0.03081056087673823
        ],
        [
            "звук",
            0.030796125205166683
        ],
        [
            "руна",
            0.028320421467826696
        ],
        [
            "руно",
            0.026803633938704885
        ],
        [
            "арабский",
            0.025817841456851686
        ],
        [
            "рунический",
            0.025296618193609663
        ],
        [
            "латинский",
            0.02290952643723039
        ],
        [

In [53]:
phi0.columns

Index(['background_1', 'topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4',
       'topic_5', 'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10',
       'topic_11', 'topic_12', 'topic_13', 'topic_14', 'topic_15'],
      dtype='object')

In [64]:
phi0['background_1'].sort_values(ascending=False)[:20]

@lemmatized  person        0.042257
             год           0.029530
             время         0.012102
             стать         0.010141
             город         0.009177
             человек       0.008519
             часть         0.008052
             век           0.007806
             имя           0.007420
             армия         0.007205
             являться      0.007020
             мочь          0.006865
             иметь         0.006848
             война         0.006680
             получить      0.006673
             работа        0.006518
             большой       0.006191
             находиться    0.005973
             язык          0.005945
             книга         0.005661
Name: background_1, dtype: float64

In [60]:
phi0['topic_0'].sort_values(ascending=False)[:20]

@lemmatized  person      0.044236
             игра        0.038738
             фильм       0.034461
             год         0.021441
             персонаж    0.018764
             роль        0.016915
             время       0.013180
             сцена       0.012968
             герой       0.012618
             актёр       0.012025
             серия       0.011883
             режиссёр    0.011813
             игрок       0.011805
             стать       0.011129
             сериал      0.011006
             картина     0.010805
             хороший     0.010353
             игровой     0.009919
             эпизод      0.009715
             версия      0.009561
Name: topic_0, dtype: float64

In [61]:
phi0['topic_0'].sort_values(ascending=False)[:20]

@lemmatized  person      0.044236
             игра        0.038738
             фильм       0.034461
             год         0.021441
             персонаж    0.018764
             роль        0.016915
             время       0.013180
             сцена       0.012968
             герой       0.012618
             актёр       0.012025
             серия       0.011883
             режиссёр    0.011813
             игрок       0.011805
             стать       0.011129
             сериал      0.011006
             картина     0.010805
             хороший     0.010353
             игровой     0.009919
             эпизод      0.009715
             версия      0.009561
Name: topic_0, dtype: float64

In [62]:
phi['topic_0'].sort_values(ascending=False)[:20]

modality     token
@lemmatized  person      0.007280
             игра        0.006375
             фильм       0.005671
             год         0.003528
             персонаж    0.003088
             роль        0.002784
             время       0.002169
             сцена       0.002134
             герой       0.002077
             актёр       0.001979
             серия       0.001956
             режиссёр    0.001944
             игрок       0.001943
             стать       0.001832
             сериал      0.001811
             картина     0.001778
             хороший     0.001704
             игровой     0.001632
             эпизод      0.001599
             версия      0.001573
Name: topic_0, dtype: float64

In [67]:
phi0['background_1'].sort_values(ascending=False)[:20]

@lemmatized  person        0.042257
             год           0.029530
             время         0.012102
             стать         0.010141
             город         0.009177
             человек       0.008519
             часть         0.008052
             век           0.007806
             имя           0.007420
             армия         0.007205
             являться      0.007020
             мочь          0.006865
             иметь         0.006848
             война         0.006680
             получить      0.006673
             работа        0.006518
             большой       0.006191
             находиться    0.005973
             язык          0.005945
             книга         0.005661
Name: background_1, dtype: float64

In [63]:
top_words['topic_0']

[['person', 0.0422573407299807],
 ['год', 0.029529524372319878],
 ['время', 0.012102291687147673],
 ['стать', 0.010141119486329416],
 ['город', 0.009177191305420053],
 ['человек', 0.0085192620682621],
 ['часть', 0.008051808916342945],
 ['век', 0.007805910871055686],
 ['имя', 0.007420150137652238],
 ['армия', 0.007204607579826462],
 ['являться', 0.007019571092204588],
 ['мочь', 0.006865394327750571],
 ['иметь', 0.006847778180194606],
 ['война', 0.006679773966025352],
 ['получить', 0.006672689870839094],
 ['работа', 0.006517804032917204],
 ['большой', 0.006191131955561368],
 ['находиться', 0.005972721385662755],
 ['язык', 0.005945349787161841],
 ['книга', 0.005661034032538145]]

In [116]:
phi0['background_1'].sort_values(ascending=False)[:20]

@lemmatized  person        0.042257
             год           0.029530
             время         0.012102
             стать         0.010141
             город         0.009177
             человек       0.008519
             часть         0.008052
             век           0.007806
             имя           0.007420
             армия         0.007205
             являться      0.007020
             мочь          0.006865
             иметь         0.006848
             война         0.006680
             получить      0.006673
             работа        0.006518
             большой       0.006191
             находиться    0.005973
             язык          0.005945
             книга         0.005661
Name: background_1, dtype: float64

In [122]:
phi0['topic_15'].sort_values(ascending=False)[:20]

@lemmatized  покемон     0.268106
             игра        0.109189
             pokemon     0.095733
             nintendo    0.059366
             игрок       0.044063
             пикача      0.039032
             серия       0.038374
             тренер      0.034944
             game        0.033527
             эш          0.030722
             red         0.028671
             аниме       0.025636
             blue        0.024596
             сериал      0.024576
             бой         0.023642
             boy         0.022706
             регион      0.020267
             ruby        0.020025
             sapphire    0.019915
             игровой     0.018577
Name: topic_15, dtype: float64

In [68]:
top_words['topic_1']

[['person', 0.044235989853675974],
 ['игра', 0.0387382873759443],
 ['фильм', 0.034460608860536146],
 ['год', 0.021440806375940213],
 ['персонаж', 0.018763569372780647],
 ['роль', 0.01691528654003225],
 ['время', 0.013179582065132664],
 ['сцена', 0.012967765359657869],
 ['герой', 0.012617957383598114],
 ['актёр', 0.01202547379667657],
 ['серия', 0.01188295046266246],
 ['режиссёр', 0.01181331044036697],
 ['игрок', 0.011805007576893822],
 ['стать', 0.011129362726140676],
 ['сериал', 0.011006356914471157],
 ['картина', 0.01080528813709529],
 ['хороший', 0.010352734596734994],
 ['игровой', 0.009919317386098348],
 ['эпизод', 0.009715262708623107],
 ['версия', 0.009560538600799823]]

In [123]:
phi['topic_15'].sort_values(ascending=False)[:20]

modality     token
@lemmatized  покемон     0.043134
             игра        0.017567
             pokemon     0.015402
             nintendo    0.009551
             игрок       0.007089
             пикача      0.006280
             серия       0.006174
             тренер      0.005622
             game        0.005394
             эш          0.004943
             red         0.004613
             аниме       0.004124
             blue        0.003957
             сериал      0.003954
             бой         0.003804
             boy         0.003653
             регион      0.003261
             ruby        0.003222
             sapphire    0.003204
             игровой     0.002989
Name: topic_15, dtype: float64

In [117]:
phi.shape, phi0.shape

((264943, 17), (264925, 17))

In [118]:
phi.columns

Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16'],
      dtype='object')

In [119]:
phi0.columns

Index(['background_1', 'topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4',
       'topic_5', 'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10',
       'topic_11', 'topic_12', 'topic_13', 'topic_14', 'topic_15'],
      dtype='object')

In [70]:
seed_load_folder

'/data_mil/shared/CompressaAI/BERTopic/results/ruwikigood/0'

In [71]:
! head -n 2 '/data_mil/shared/CompressaAI/BERTopic/results/ruwikigood/0/phi.csv'

,background_1,topic_0,topic_1,topic_2,topic_3,topic_4,topic_5,topic_6,topic_7,topic_8,topic_9,topic_10,topic_11,topic_12,topic_13,topic_14,topic_15
aa,1.880537854513533e-05,3.155666363779187e-05,6.524287003967717e-05,0.0,0.0,1.5913009450918555e-05,0.0,1.9111301643428782e-05,0.0,0.0,0.0,0.0,0.0076266546732638605,0.0,0.0,0.0,0.0

In [84]:
phi0.shape, len(top_words)

((264925, 17), 17)

In [85]:
phi0['topic_15'].sort_values(ascending=False)[:20]

@lemmatized  покемон     0.268106
             игра        0.109189
             pokemon     0.095733
             nintendo    0.059366
             игрок       0.044063
             пикача      0.039032
             серия       0.038374
             тренер      0.034944
             game        0.033527
             эш          0.030722
             red         0.028671
             аниме       0.025636
             blue        0.024596
             сериал      0.024576
             бой         0.023642
             boy         0.022706
             регион      0.020267
             ruby        0.020025
             sapphire    0.019915
             игровой     0.018577
Name: topic_15, dtype: float64

In [88]:
top_words.keys()

dict_keys(['background_1', 'topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5', 'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11', 'topic_12', 'topic_13', 'topic_14', 'topic_15'])

In [86]:
top_words['topic_16']

KeyError: 'topic_16'

In [81]:
len(top_words)

17

In [82]:
phi0['topic_14'].sort_values(ascending=False)[:20]

@lemmatized  малдёр           0.138623
             эпизод           0.116320
             агент            0.049091
             person           0.047593
             сериал           0.041120
             тумс             0.037865
             секретный        0.036518
             картер           0.029176
             фбр              0.027501
             материал         0.027373
             серия            0.025630
             fox              0.024078
             сцена            0.023637
             съёмка           0.021304
             сценарий         0.019872
             малдрать         0.019669
             домохозяйство    0.019580
             премьера         0.018778
             сезон            0.018749
             расследовать     0.017247
Name: topic_14, dtype: float64

In [83]:
top_words['topic_15']

[['малдёр', 0.1386228369280603],
 ['эпизод', 0.11631993906668163],
 ['агент', 0.049090525093543905],
 ['person', 0.047593315648508897],
 ['сериал', 0.04111972980469913],
 ['тумс', 0.03786522487257441],
 ['секретный', 0.03651821212407736],
 ['картер', 0.02917647118432673],
 ['фбр', 0.027500518993828337],
 ['материал', 0.027373011451345342],
 ['серия', 0.025629757135196673],
 ['fox', 0.024077945281126726],
 ['сцена', 0.023637398476370437],
 ['съёмка', 0.021304282715615113],
 ['сценарий', 0.019872107173757463],
 ['малдрать', 0.019668540165023844],
 ['домохозяйство', 0.019580396028063024],
 ['премьера', 0.01877765221036062],
 ['сезон', 0.018749264086400926],
 ['расследовать', 0.01724706793607795]]

In [98]:
phi0.columns

Index(['background_1', 'topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4',
       'topic_5', 'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10',
       'topic_11', 'topic_12', 'topic_13', 'topic_14', 'topic_15'],
      dtype='object')

In [105]:
phi0['topic_15'].sort_values(ascending=False)[:20]

@lemmatized  покемон     0.268106
             игра        0.109189
             pokemon     0.095733
             nintendo    0.059366
             игрок       0.044063
             пикача      0.039032
             серия       0.038374
             тренер      0.034944
             game        0.033527
             эш          0.030722
             red         0.028671
             аниме       0.025636
             blue        0.024596
             сериал      0.024576
             бой         0.023642
             boy         0.022706
             регион      0.020267
             ruby        0.020025
             sapphire    0.019915
             игровой     0.018577
Name: topic_15, dtype: float64

In [103]:
top_words['topic_15']

[['малдёр', 0.1386228369280603],
 ['эпизод', 0.11631993906668163],
 ['агент', 0.049090525093543905],
 ['person', 0.047593315648508897],
 ['сериал', 0.04111972980469913],
 ['тумс', 0.03786522487257441],
 ['секретный', 0.03651821212407736],
 ['картер', 0.02917647118432673],
 ['фбр', 0.027500518993828337],
 ['материал', 0.027373011451345342],
 ['серия', 0.025629757135196673],
 ['fox', 0.024077945281126726],
 ['сцена', 0.023637398476370437],
 ['съёмка', 0.021304282715615113],
 ['сценарий', 0.019872107173757463],
 ['малдрать', 0.019668540165023844],
 ['домохозяйство', 0.019580396028063024],
 ['премьера', 0.01877765221036062],
 ['сезон', 0.018749264086400926],
 ['расследовать', 0.01724706793607795]]

In [104]:
phi0.columns

Index(['background_1', 'topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4',
       'topic_5', 'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10',
       'topic_11', 'topic_12', 'topic_13', 'topic_14', 'topic_15'],
      dtype='object')

In [101]:
top_words.keys()

dict_keys(['background_1', 'topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5', 'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11', 'topic_12', 'topic_13', 'topic_14', 'topic_15'])

In [106]:
top_words

{'background_1': False,
 'topic_0': [['person', 0.0422573407299807],
  ['год', 0.029529524372319878],
  ['время', 0.012102291687147673],
  ['стать', 0.010141119486329416],
  ['город', 0.009177191305420053],
  ['человек', 0.0085192620682621],
  ['часть', 0.008051808916342945],
  ['век', 0.007805910871055686],
  ['имя', 0.007420150137652238],
  ['армия', 0.007204607579826462],
  ['являться', 0.007019571092204588],
  ['мочь', 0.006865394327750571],
  ['иметь', 0.006847778180194606],
  ['война', 0.006679773966025352],
  ['получить', 0.006672689870839094],
  ['работа', 0.006517804032917204],
  ['большой', 0.006191131955561368],
  ['находиться', 0.005972721385662755],
  ['язык', 0.005945349787161841],
  ['книга', 0.005661034032538145]],
 'topic_1': [['person', 0.044235989853675974],
  ['игра', 0.0387382873759443],
  ['фильм', 0.034460608860536146],
  ['год', 0.021440806375940213],
  ['персонаж', 0.018763569372780647],
  ['роль', 0.01691528654003225],
  ['время', 0.013179582065132664],
  ['сцена', 0.012967765359657869],
  ['герой', 0.012617957383598114],
  ['актёр', 0.01202547379667657],
  ['серия', 0.01188295046266246],
  ['режиссёр', 0.01181331044036697],
  ['игрок', 0.011805007576893822],
  ['стать', 0.011129362726140676],
  ['сериал', 0.011006356914471157],
  ['картина', 0.01080528813709529],
  ['хороший', 0.010352734596734994],
  ['игровой', 0.009919317386098348],
  ['эпизод', 0.009715262708623107],
  ['версия', 0.009560538600799823]],
 'topic_2': [['вид', 0.030215148673318974],
  ['клетка', 0.02579397754963481],
  ['мочь', 0.022082817407119912],
  ['птица', 0.020521085282441655],
  ['акула', 0.01657235038142157],
  ['являться', 0.014445202933896511],
  ['person', 0.014365602795943212],
  ['ген', 0.013378943817396719],
  ['некоторый', 0.013116810594674731],
  ['растение', 0.012987671436217459],
  ['белок', 0.01236520674394188],
  ['самка', 0.012306624995602205],
  ['длина', 0.012054247200103235],
  ['иметь', 0.011887324754242687],
  ['рнк', 0.01160610247693715],
  ['белка', 0.01137567370888491],
  ['год', 0.01112030857944126],
  ['род', 0.010888929805607668],
  ['днк', 0.010733196001582826],
  ['самец', 0.010614612497904003]],
 'topic_3': [['person', 0.0841527483812516],
  ['консул', 0.04306035529257968],
  ['цезарь', 0.033783847022959584],
  ['год', 0.033760342571942735],
  ['рим', 0.033076312124254936],
  ['квинта', 0.03255117036907093],
  ['римский', 0.02469154489409693],
  ['сципион', 0.023912239284115674],
  ['война', 0.022948577283771903],
  ['сенат', 0.021666185636563192],
  ['стать', 0.018245147251432565],
  ['марка', 0.017272737985466857],
  ['источник', 0.016012977746414914],
  ['армия', 0.016011318583284813],
  ['время', 0.013742947952166275],
  ['красс', 0.012812105236022591],
  ['сын', 0.01265868695501787],
  ['гракх', 0.011985725865605869],
  ['претор', 0.011886226274606225],
  ['политический', 0.0117890838085003]],
 'topic_4': [['матч', 0.06196697543819613],
  ['person', 0.05221854822208545],
  ['команда', 0.05218490045127047],
  ['сезон', 0.042307008781434355],
  ['клуб', 0.03819269650922297],
  ['год', 0.0380927930674332],
  ['чемпионат', 0.034639781580528425],
  ['игра', 0.03450288595893967],
  ['игрок', 0.03199732699485274],
  ['турнир', 0.025576535987194084],
  ['стать', 0.025513023294643992],
  ['сборный', 0.024757138329553903],
  ['счёт', 0.022622645441115988],
  ['кубок', 0.021777351417733536],
  ['гол', 0.02165673397872249],
  ['лига', 0.021068714892202287],
  ['забить', 0.02085347476358155],
  ['тренер', 0.02057802327536501],
  ['победа', 0.020071746702425588],
  ['выиграть', 0.018818786140917237]],
 'topic_5': [['альбом', 0.08493066475701502],
  ['группа', 0.05587826508543907],
  ['песня', 0.04532092132491192],
  ['person', 0.03895056100844638],
  ['песнь', 0.028126683410859037],
  ['год', 0.027452891855811856],
  ['музыкант', 0.026701176520108293],
  ['запись', 0.022405928954889954],
  ['композиция', 0.0219877561953017],
  ['сингл', 0.021787665368888435],
  ['концерт', 0.020802094454072044],
  ['музыкальный', 0.0204561812231181],
  ['музыка', 0.017425156848285345],
  ['выпустить', 0.017115151499441632],
  ['стать', 0.016572787206695635],
  ['время', 0.015590105348982884],
  ['пластинка', 0.015588264308807135],
  ['записать', 0.015469923010697051],
  ['хороший', 0.013482147899156341],
  ['диск', 0.013382640027254948]],
 'topic_6': [['картина', 0.06784141674309457],
  ['художник', 0.05655445524043672],
  ['person', 0.051050738681211495],
  ['год', 0.03047461554620188],
  ['полотно', 0.02301409077229612],
  ['портрет', 0.02174523409115007],
  ['работа', 0.019929193755247404],
  ['выставка', 0.019098189503231073],
  ['искусство', 0.016894644627850196],
  ['время', 0.014427125875090626],
  ['живопись', 0.01422666786493558],
  ['музей', 0.014077649749664118],
  ['изобразить', 0.013730051487358159],
  ['искусствовед', 0.013135474258319449],
  ['фигура', 0.01296862441906373],
  ['художественный', 0.012674702304604728],
  ['галерея', 0.0117330969308483],
  ['писать', 0.011322937727904742],
  ['изображение', 0.010742692127324531],
  ['шахматы', 0.010589871197274208]],
 'topic_7': [['корабль', 0.061135027330581786],
  ['крейсер', 0.04963131147216833],
  ['мм', 0.04275156172559051],
  ['флот', 0.030321497702430842],
  ['орудие', 0.028826435016410797],
  ['год', 0.028147663960723476],
  ['person', 0.025709069278324614],
  ['линкор', 0.024130824238685043],
  ['тип', 0.023396053612308815],
  ['палуба', 0.02004251639991332],
  ['башня', 0.019957936356259004],
  ['снаряд', 0.019590201837591813],
  ['проект', 0.01795391720800892],
  ['линейный', 0.01771271020855401],
  ['установка', 0.01701120597969879],
  ['подводный', 0.016389748674991936],
  ['борт', 0.016232577539619927],
  ['лодка', 0.015513192064940451],
  ['эскадра', 0.015502352053428996],
  ['скорость', 0.01493337958587967]],
 'topic_8': [['станция', 0.09007570400734867],
  ['паровоз', 0.05712851428046863],
  ['поезд', 0.05220709177793897],
  ['вагон', 0.04785589716475774],
  ['линия', 0.042825393690960604],
  ['год', 0.03639166982837442],
  ['дорога', 0.036030782729962144],
  ['железный', 0.02937242809046936],
  ['строительство', 0.02147981394835432],
  ['депо', 0.02134908469252574],
  ['метрополитен', 0.02116810714040615],
  ['метро', 0.02033395496220223],
  ['вестибюль', 0.02026491288475578],
  ['трамвайный', 0.020000663472535426],
  ['завод', 0.018815191362806887],
  ['участок', 0.01873808927805568],
  ['троллейбус', 0.018409484961187012],
  ['московский', 0.018129590535350643],
  ['дизель', 0.01780968582432959],
  ['состав', 0.0163403296313843]],
 'topic_9': [['sonic', 0.17224179961986724],
  ['игра', 0.09250357884223097],
  ['hedgehog', 0.062336305907061705],
  ['соника', 0.05144687581579275],
  ['уровень', 0.04379958930968486],
  ['персонаж', 0.04328221924932132],
  ['sega', 0.03696724448877664],
  ['игрок', 0.03614787996833785],
  ['серия', 0.0334399505798377],
  ['ёж', 0.030774407410768773],
  ['игровой', 0.029981579029404206],
  ['adventure', 0.026562938105981516],
  ['изумруд', 0.02527885110402573],
  ['консоль', 0.024706191513924336],
  ['person', 0.023514575900293433],
  ['кольцо', 0.02265654193954611],
  ['версия', 0.022046541272303464],
  ['прохождение', 0.019906168261542755],
  ['робот', 0.019274077825312413],
  ['платформер', 0.019186521912468522]],
 'topic_10': [['фотография', 0.07949930887290067],
  ['person', 0.044749892550015505],
  ['шоу', 0.03646249023138975],
  ['wwe', 0.03322337247139302],
  ['фотограф', 0.032064203978450535],
  ['киноплёнка', 0.029497345665161136],
  ['год', 0.027096881385825108],
  ['поединок', 0.02469935300881912],
  ['матч', 0.022917267867726868],
  ['титул', 0.022073996551174712],
  ['время', 0.018916523622722472],
  ['стать', 0.018366916681042282],
  ['изображение', 0.01731905166892394],
  ['объектив', 0.017194229803491567],
  ['негатив', 0.017075878921995795],
  ['съёмка', 0.016807988223792928],
  ['чемпион', 0.01637911188772787],
  ['камера', 0.016219134978719078],
  ['ринг', 0.01579863206172525],
  ['перфорация', 0.014517574126471908]],
 'topic_11': [['герб', 0.2465816569430666],
  ['геральдический', 0.07565315301302024],
  ['щит', 0.06574001642538452],
  ['город', 0.06472526715142707],
  ['муниципальный', 0.051088791843450526],
  ['символ', 0.050724240604793185],
  ['золотой', 0.04685224557003737],
  ['городской', 0.04228975512000389],
  ['утвердить', 0.03960165858245089],
  ['год', 0.03697373118002053],
  ['гербовый', 0.03219191674981601],
  ['символика', 0.03166492442243593],
  ['совет', 0.030213306456932862],
  ['район', 0.029853728575348425],
  ['серебряный', 0.029478232965183936],
  ['ставропольский', 0.028850879974333922],
  ['изображение', 0.028104075540310768],
  ['person', 0.026231009452910778],
  ['смоленский', 0.025017039737062645],
  ['официальный', 0.024968445670692816]],
 'topic_12': [['алфавит', 0.2559041872459918],
  ['письменность', 0.12949297302667126],
  ['буква', 0.1243270131734294],
  ['язык', 0.09294793491305166],
  ['кириллица', 0.051794533046437205],
  ['год', 0.04602755907105228],
  ['букварь', 0.038154984384602235],
  ['кириллический', 0.037887338369330094],
  ['знак', 0.037745484000844404],
  ['использоваться', 0.03652142182903645],
  ['основа', 0.03614480966087923],
  ['латиница', 0.03290414894963932],
  ['латинизировать', 0.03081056087673823],
  ['звук', 0.030796125205166683],
  ['руна', 0.028320421467826696],
  ['руно', 0.026803633938704885],
  ['арабский', 0.025817841456851686],
  ['рунический', 0.025296618193609663],
  ['латинский', 0.02290952643723039],
  ['диалект', 0.022355594451362246]],
 'topic_13': [['собака', 0.14744064208045587],
  ['порода', 0.11098998169351919],
  ['бульдог', 0.06460089836994493],
  ['шерсть', 0.04171225645265177],
  ['лошадь', 0.040614845465488714],
  ['крыса', 0.038988782626498235],
  ['окрас', 0.0377240547984743],
  ['карачаевский', 0.03147834533177605],
  ['выставка', 0.02662409065963615],
  ['крафт', 0.024137623918518692],
  ['стандарт', 0.021691597024853577],
  ['год', 0.02090228354946776],
  ['ухо', 0.01785257353935807],
  ['сиб', 0.01760717141494888],
  ['мочь', 0.01760403368024112],
  ['охота', 0.017218323481391302],
  ['клуб', 0.016946249483606828],
  ['холка', 0.01677073939165584],
  ['охотничий', 0.016696797083060724],
  ['морда', 0.016438770031776767]],
 'topic_14': [['блюдо', 0.08483791993532859],
  ['кухня', 0.06921703385628254],
  ['соус', 0.04379969887473472],
  ['напиток', 0.03496582358909257],
  ['рис', 0.03372151360113247],
  ['хлеб', 0.0327214562326707],
  ['продукт', 0.0295168142068896],
  ['горчица', 0.02948254068445559],
  ['приготовление', 0.027887574257750708],
  ['различный', 0.02659774026082518],
  ['гонконг', 0.02622790777266512],
  ['ресторан', 0.026083271495935634],
  ['овощ', 0.024637127724458436],
  ['кулинарный', 0.024352466439202008],
  ['писко', 0.024312095335572364],
  ['суп', 0.024040853790914935],
  ['мясо', 0.02379587138086734],
  ['индонезия', 0.023165622101092954],
  ['вино', 0.021988040450296592],
  ['лапша', 0.02164859717183316]],
 'topic_15': [['малдёр', 0.1386228369280603],
  ['эпизод', 0.11631993906668163],
  ['агент', 0.049090525093543905],
  ['person', 0.047593315648508897],
  ['сериал', 0.04111972980469913],
  ['тумс', 0.03786522487257441],
  ['секретный', 0.03651821212407736],
  ['картер', 0.02917647118432673],
  ['фбр', 0.027500518993828337],
  ['материал', 0.027373011451345342],
  ['серия', 0.025629757135196673],
  ['fox', 0.024077945281126726],
  ['сцена', 0.023637398476370437],
  ['съёмка', 0.021304282715615113],
  ['сценарий', 0.019872107173757463],
  ['малдрать', 0.019668540165023844],
  ['домохозяйство', 0.019580396028063024],
  ['премьера', 0.01877765221036062],
  ['сезон', 0.018749264086400926],
  ['расследовать', 0.01724706793607795]]}