In [1]:
import os
import json
import shutil
import sys
import time

import numpy as np
import scipy

In [2]:
sys.path.insert(0, '../OptimalNumberOfTopics')

In [3]:
import topnum

from topnum.scores.perplexity_score import PerplexityScore
from topnum.scores.diversity_score import DiversityScore, KNOWN_METRICS
from topnum.model_constructor import init_model_from_family, KnownModel, PARAMS_EXPLORED, init_plsa

from topnum.regularizers import (
    FastFixPhiRegularizer, DecorrelateWithOtherPhiRegularizer, DecorrelateWithOtherPhiRegularizer2
)
from topnum.scores.intratext_coherence_score import (
    IntratextCoherenceScore,
    ComputationMethod,
    WordTopicRelatednessType,
)

In [4]:
import artm
from artm import ARTM, Dictionary

import topicnet
from topicnet.cooking_machine.dataset import Dataset
from topicnet.cooking_machine.models import (
    BaseScore as BaseTopicNetScore,
    TopicModel
)
from topicnet.cooking_machine.models.base_regularizer import BaseRegularizer
from topicnet.cooking_machine.models.thetaless_regularizer import (
    dataset2sparse_matrix,
)

from topicnet.cooking_machine.models.topic_model import ARTM_NINE
from topicnet.cooking_machine.models.base_regularizer import BaseRegularizer
from topicnet.viewers.top_documents_viewer import TopDocumentsViewer
from topicnet.viewers.top_tokens_viewer import TopTokensViewer
from topicnet.cooking_machine.model_constructor import (
    add_standard_scores,
    create_default_topics,
    count_vocab_size,
    init_model,
)
from topicnet.cooking_machine.rel_toolbox_lite import (
    count_vocab_size,
    modality_weight_rel2abs,
    transform_regularizer,
)


import numpy as np
import pandas as pd
from pandas import DataFrame
from scipy.spatial.distance import cdist

import os
import tempfile
import warnings
from copy import deepcopy
from typing import Dict, List, Optional

In [5]:
NUM_TOPICS = 50  # TODO: this value does not affect anything

NUM_ITERATIONS = 5
NUM_TOP_TOKENS = 20
NUM_TRAINS = 20

In [6]:
BERTOPIC_FOLDER_PATH = '/data_mil/shared/CompressaAI/iterative/results/newman/BERTopic'

In [7]:
! ls $BERTOPIC_FOLDER_PATH

results  results50

In [8]:
! ls $BERTOPIC_FOLDER_PATH/results50

20newsgroups  mkb10  postnauka	rtlwikiperson  ruwikigood

In [9]:
RESULTS_FOLDER_PATH = os.path.join(BERTOPIC_FOLDER_PATH, 'results50', 'mkb10')

In [10]:
RESULTS_FOLDER_PATH

'/data_mil/shared/CompressaAI/iterative/results/newman/BERTopic/results50/mkb10'

In [11]:
! ls results50

ls: cannot access 'results50': No such file or directory

In [12]:
SAVE_FOLDER = os.path.join('results50_intra', 'mkb10')

In [13]:
SAVE_FOLDER

'results50_intra/mkb10'

In [14]:
! ls $SAVE_FOLDER

decorrelation_with_cohs.json  iterative2_100000000	 plsa_with_cohs.json
iterative_100000	      iterative2_100000000.json  sparse_with_cohs.json
iterative_100000.json	      lda_with_cohs.json	 tless_with_cohs.json

In [15]:
! ls $RESULTS_FOLDER_PATH

0  1  10  11  12  13  14  15  16  17  18  19  2  3  4  5  6  7	8  9

In [16]:
! ls $RESULTS_FOLDER_PATH/0

dataset.csv  dataset__internals  phi.csv  top_words.json

In [17]:
dataset = Dataset(
    f'{RESULTS_FOLDER_PATH}/0/dataset.csv',
)

dataset.get_possible_modalities()

{'@text'}

In [18]:
MAIN_MODALITY = '@text'

In [19]:
def calc_doc_occurrences(dataset, modality):
    """
    :param n_dw_matrix: sparse document-word matrix, shape is D x W
    :return: sparse matrix of co-occurrences

    doc_occurrences[w1, w2] = the number of the documents
    where there are w1 and w2
    """
    n_dw_matrix = dataset2sparse_matrix(dataset, modality, modalities_to_use=[modality])
    matrix = (scipy.sparse.csc_matrix(n_dw_matrix) > 0).astype(int)
    co_occurrences = matrix.T * matrix

    return co_occurrences.diagonal(), co_occurrences


def create_pmi_top_function(
    doc_occurrences, doc_co_occurrences,
    documents_number, top_sizes,
    topic_indices,
    co_occurrences_smooth=1.
):
    """
    :param doc_occurrences: array of doc occurrences of words
    :param doc_co_occurrences: sparse matrix of doc co-occurrences of words
    :param documents_number: number of the documents
    :param top_sizes: list of top values to calculate top-pmi for
    :param co_occurrences_smooth: constant to smooth co-occurrences in log
    :return: function which takes phi and theta and returns
    pair of two arrays: pmi-s of the tops and ppmi-s of the tops

    pmi[i] - pmi(top of size top_sizes[i])
    ppmi[i] - ppmi(top of size top_sizes[i])

    pmi(words) = sum_{u in words, v in words, u != v}
    log(
        (doc_co_occurrences[u, v] * documents_number + co_occurrences_smooth)
        / doc_occurrences[u] / doc_occurrences[v]
    )

    ppmi(words) = sum_{u in words, v in words, u != v}
    max(log(
        (doc_co_occurrences[u, v] * documents_number + co_occurrences_smooth)
        / doc_occurrences[u] / doc_occurrences[v]
    ), 0)

    """
    def func(phi):
        _T, W = phi.shape
        T = len(topic_indices)

        max_top_size = max(top_sizes)
        topic_pmis, topic_ppmis = dict(), dict()
        pmi, ppmi = np.zeros(max_top_size), np.zeros(max_top_size)
        tops = np.argpartition(phi, -max_top_size, axis=1)[:, -max_top_size:]
        
        for t in topic_indices:
            top = sorted(tops[t], key=lambda w: - phi[t, w])
            co_occurrences = doc_co_occurrences[top, :][:, top].todense()
            occurrences = doc_occurrences[top]
            values = np.log(
                (co_occurrences * documents_number + co_occurrences_smooth)
                / (occurrences[:, np.newaxis] * occurrences[np.newaxis, :] + co_occurrences_smooth)
            )
            diag = np.diag_indices(len(values))
            # values.cumsum(axis=0).cumsum(axis=1)[diag] - values[diag].cumsum()

            current_pmi = np.array(
               values.cumsum(axis=0).cumsum(axis=1)[diag] - values[diag].cumsum()
            ).ravel()
            topic_pmis[t] = current_pmi
            pmi += current_pmi

            values[values < 0.] = 0.
            current_ppmi = np.array(
               values.cumsum(axis=0).cumsum(axis=1)[diag] - values[diag].cumsum()
            ).ravel()
            topic_ppmis[t] = current_ppmi
            ppmi += current_ppmi
            
        sizes = np.arange(2, max_top_size + 1)
        pmi[1:] /= (T * sizes * (sizes - 1))
        ppmi[1:] /= (T * sizes * (sizes - 1))
        indices = np.array(top_sizes) - 1

        for t in topic_indices:
            topic_pmis[t][1:] /= (sizes * (sizes - 1))
            topic_ppmis[t][1:] /= (sizes * (sizes - 1))

        result_topic_pmis = {t: p[indices] for t, p in topic_pmis.items()}
        result_topic_ppmis = {t: p[indices] for t, p in topic_ppmis.items()}

        return pmi[indices], ppmi[indices], result_topic_pmis, result_topic_ppmis

    return func

In [20]:
%%time

occurences, co_occurences = calc_doc_occurrences(dataset, MAIN_MODALITY)

CPU times: user 10.4 s, sys: 537 ms, total: 11 s
Wall time: 11 s

In [21]:
co_occurences.shape

(127266, 127266)

In [22]:
calc_pmi = create_pmi_top_function(
    occurences, co_occurences,
    dataset.get_dataset().shape[0], [20],
    topic_indices=[0, 1, 2],
    co_occurrences_smooth=1e-2,
)

In [23]:
class TopTokenCoherence(BaseTopicNetScore):
    def __init__(self, name, func):
        super().__init__()

        self._name = name
        self.calc_pmi = func

    def call(self, model: TopicModel):
        values = self.calc_pmi(model.get_phi_dense()[0].T)

        return values[1]

    def call_by_topic(self, model: TopicModel):
        values = self.calc_pmi(model.get_phi_dense()[0].T)

        return values[3]

In [24]:
def view_model(
        topic_model,
        dataset,
        num_top_tokens: int = 5,
        top_tokens_method: str = 'phi',
        num_topics: Optional[int] = 5,  # we do not want to fill the whole .ipynb notebook with topics...
        ):
    top_tok_viewer = TopTokensViewer(
        topic_model, num_top_tokens=num_top_tokens, method=top_tokens_method
    )
    top_doc_viewer = TopDocumentsViewer(topic_model, dataset=dataset)
    top_docs = top_doc_viewer.view()

    if num_topics is None:
        num_topics = len(topic_model.topic_names)

    for topic_name in topic_model.topic_names[:num_topics]:
        topic_top_toks = top_tok_viewer.to_html(topic_names=[topic_name])
        topic_top_docs = top_docs[topic_name]
        display_html(topic_top_toks, raw=True)
        display(topic_top_docs)

In [25]:
class FastFixPhiRegularizer(BaseRegularizer):
    _VERY_BIG_TAU = 10 ** 9

    def __init__(self, name: str, topic_names: List[str], parent_model=None, parent_phi=None, words=None):
        super().__init__(name, tau=self._VERY_BIG_TAU)

        self._topic_names = topic_names
        self._topic_indices = None
        self._words = words
        self._word_indices = None
        self._parent_model = parent_model
        self._parent_phi = parent_phi

    def grad(self, pwt, nwt):
        # print('Fixing')

        rwt = np.zeros_like(pwt)

        if self._parent_phi is not None:
            parent_phi = self._parent_phi
            vals = parent_phi.values
        else:
            assert False

            parent_phi = self._parent_model.get_phi()
            vals = parent_phi.values[:, self._topic_indices]

        if self._word_indices is None:
            assert vals.shape[0] == rwt.shape[0], (vals.shape[0], rwt.shape[0])
        else:
            assert vals.shape[0] == len(self._word_indices)

        assert vals.shape[1] == len(self._topic_indices)

        if self._word_indices is None:
            rwt[:, self._topic_indices] += vals
        else:
            # print(len(self._word_indices), len(self._topic_indices), rwt.shape, vals.shape)
            # print(self._word_indices[:3], self._topic_indices[:3])
            # print(rwt[np.ix_(self._word_indices, self._topic_indices)].shape, vals.shape)

            # https://github.com/numpy/numpy/issues/5574
            # https://github.com/numpy/numpy/issues/13255
            rwt[np.ix_(self._word_indices, self._topic_indices)] += vals

            # print(np.ix_(self._word_indices, self._topic_indices)[:3])

        return self.tau * rwt

    def attach(self, model):
        super().attach(model)
        
        phi = self._model.get_phi()
        self._topic_indices = [
            phi.columns.get_loc(topic_name)
            for topic_name in self._topic_names
        ]

        if self._words is not None:
            self._word_indices = [
                # phi.index.get_loc(w) for w in self._words
                int(phi.index.get_loc(w)) for w in self._words
            ]

            # print(f'!!! Word indices: {self._word_indices}')

In [26]:
def fit_and_compute_scores(model, dataset, target_topic_indices=None, custom_regularizers=None):
    print(custom_regularizers)

    model._fit(dataset.get_batch_vectorizer(), num_iterations=NUM_ITERATIONS, custom_regularizers=custom_regularizers)

    score_values = {
        'perplexity': model.scores[f'PerplexityScore{MAIN_MODALITY}'][-1],
    }

    phi = model.get_phi()

    # Currently all topics are taken into account

    if target_topic_indices is None:
        target_topic_indices = list(range(NUM_TOPICS))  # phi.columns.get_loc()

    target_topic_names = [phi.columns[i] for i in target_topic_indices]

    top = NUM_TOP_TOKENS
    coherence_score = TopTokenCoherence(
        name=f'coherence_{top}',
        func=create_pmi_top_function(
            occurences, co_occurences,
            dataset.get_dataset().shape[0], [top],
            topic_indices=target_topic_indices,
            co_occurrences_smooth=1e-2,
        )
    )

    value = coherence_score.call(model)
    score_values[coherence_score._name] = value
    topic_coherences = coherence_score.call_by_topic(model)
    topic_coherences = {t: float(v) for t, v in topic_coherences.items()}





    # intra1 = IntratextCoherenceScore(
    #     name='toplen_pwt',
    #     data=dataset,
    #     computation_method=ComputationMethod.SEGMENT_LENGTH,
    #     word_topic_relatedness=WordTopicRelatednessType.PWT,
    #     should_compute=False,  # only on last iter
    # )
    intra2 = IntratextCoherenceScore(
        name='toplen_ptw',
        data=dataset,
        computation_method=ComputationMethod.SEGMENT_LENGTH,
        word_topic_relatedness=WordTopicRelatednessType.PTW,
        should_compute=False,
    )
    # intra3 = IntratextCoherenceScore(
    #     name='topden_ptw',
    #     data=dataset,
    #     computation_method=ComputationMethod.SUM_OVER_WINDOW,
    #     word_topic_relatedness=WordTopicRelatednessType.PTW,
    #     should_compute=False,
    # )
    # intra3_w4 = IntratextCoherenceScore(
    #     name='topden_ptw',
    #     data=dataset,
    #     computation_method=ComputationMethod.SUM_OVER_WINDOW,
    #     word_topic_relatedness=WordTopicRelatednessType.PTW,
    #     window=4,
    #     should_compute=False,
    # )

    intra_topic_coherences = dict()

    for intra in [intra2]:  # [intra2, intra3_w4]:  #[intra1, intra2, intra3]:
        # print(f'\nComputing "{intra._name}"...')

        current_intra_topic_coherences = intra.compute(model)

        assert all(v is not None for v in current_intra_topic_coherences.values())

        _values = current_intra_topic_coherences.values()

        current_intra_topic_coherences = {
            i: current_intra_topic_coherences[t]  # if v is not None else 0.0
            for i, t in enumerate(target_topic_names)
        }

        assert all(abs(x - y) <= 1e-6 for x, y in zip(_values, current_intra_topic_coherences.values())), (_values, current_intra_topic_coherences.values())  # "sorted" Python dicts
        
        intra_topic_coherences[f'topic_coherences_{intra._name}'] = current_intra_topic_coherences

        value = float(np.median(list(current_intra_topic_coherences.values())))
        score_values[intra._name] = value

        # print(f'Result by topic: {current_intra_topic_coherences}.')




    
    diversity_scores = [
        DiversityScore(
            name=f'diversity_{metric}',
            metric=metric,
            topic_names=target_topic_names,
            class_ids=MAIN_MODALITY,
        )
    
        for metric in KNOWN_METRICS
    ]
    
    for score in diversity_scores:
        value = score.call(model)
        score_values[score._name] = value

    return {
        'scores': score_values,
        'topic_coherences': topic_coherences,
        **intra_topic_coherences,
    }

In [27]:
def init_model_from_family(
        family: str or KnownModel,
        dataset: Dataset,
        main_modality: str,
        num_topics: int,
        seed: int,
        specific_topic_names = None,
        modalities_to_use: List[str] = None,
        num_processors: int = 3,
        model_params: dict = None,
):
    """
    Returns
    -------
    model: TopicModel() instance
    """
    if isinstance(family, KnownModel):
        family = family.value

    if modalities_to_use is None:
        modalities_to_use = [main_modality]

    custom_regs = {}

    if family == "LDA":
        model = init_lda(
            dataset, modalities_to_use, main_modality, num_topics, model_params
        )
    elif family == "PLSA":
        model = init_plsa(
            dataset, modalities_to_use, main_modality, num_topics
        )
    elif family == "TARTM":
        model, custom_regs = init_thetaless(
            dataset, modalities_to_use, main_modality, num_topics, model_params
        )
    elif family == "sparse":
        model = init_bcg_sparse_model(
            dataset, modalities_to_use, main_modality, num_topics, 1, model_params
        )
    elif family == "decorrelation":
        model = init_decorrelated_plsa(
            dataset, modalities_to_use, main_modality, num_topics, model_params
        )
    elif family == "ARTM":
        model = init_baseline_artm(
            dataset, modalities_to_use, main_modality, num_topics, 1, specific_topic_names, model_params
        )
    else:
        raise ValueError(f'family: {family}')

    model.num_processors = num_processors

    if seed is not None:
        model.seed = seed

    dictionary = dataset.get_dictionary()

    # TODO: maybe this cycle is not necessary
    for modality in dataset.get_possible_modalities():
        if modality not in modalities_to_use:
            dictionary.filter(class_id=modality, max_df=0, inplace=True)

    model.initialize(dictionary)
    add_standard_scores(model, dictionary, main_modality=main_modality,
                        all_modalities=modalities_to_use)

    model = TopicModel(
        artm_model=model,
        custom_regularizers=custom_regs
    )

    return model


def init_bcg_sparse_model(
        dataset,
        modalities_to_use,
        main_modality,
        specific_topics,
        bcg_topics,
        specific_topic_names = None,
        model_params: dict = None
):
    """
    Creates simple artm model with standard scores.

    Parameters
    ----------
    dataset : Dataset
    modalities_to_use : list of str or dict
    main_modality : str
    specific_topics : int
    bcg_topics : int

    Returns
    -------
    model: artm.ARTM() instance
    """
    if model_params is None:
        model_params = dict()

    model = init_plsa(
        dataset, modalities_to_use, main_modality, specific_topics, bcg_topics
    )
    background_topic_names = model.topic_names[-bcg_topics:]

    if specific_topic_names is None:
        print('No spec topics')
        specific_topic_names = model.topic_names[:-bcg_topics]

    dictionary = dataset.get_dictionary()
    baseline_class_ids = {class_id: 1 for class_id in modalities_to_use}
    data_stats = count_vocab_size(dictionary, baseline_class_ids)

    # all coefficients are relative
    regularizers = [
        artm.SmoothSparsePhiRegularizer(
             name='smooth_phi_bcg',
             topic_names=background_topic_names,
             tau=model_params.get("smooth_bcg_tau", 0.1),
             class_ids=[main_modality],
        ),
        artm.SmoothSparseThetaRegularizer(
             name='smooth_theta_bcg',
             topic_names=background_topic_names,
             tau=model_params.get("smooth_bcg_tau", 0.1),
        ),
        artm.SmoothSparsePhiRegularizer(
             name='sparse_phi_sp',
             topic_names=specific_topic_names,
             tau=model_params.get("sparse_sp_tau", -0.05),
             class_ids=[main_modality],
            ),
        artm.SmoothSparseThetaRegularizer(
             name='sparse_theta_sp',
             topic_names=specific_topic_names,
             tau=model_params.get("sparse_sp_tau", -0.05),
        ),
    ]
    for reg in regularizers:
        model.regularizers.add(transform_regularizer(
            data_stats,
            reg,
            model.class_ids,
            n_topics=len(reg.topic_names)
        ))

    return model


def init_baseline_artm(
        dataset,
        modalities_to_use,
        main_modality,
        num_topics,
        bcg_topics,
        specific_topic_names = None,
        model_params: dict = None,
):
    """
    Creates simple artm model with standard scores.

    Parameters
    ----------
    dataset : Dataset
    modalities_to_use : list of str
    main_modality : str
    num_topics : int

    Returns
    -------
    model: artm.ARTM() instance
    """
    if model_params is None:
        model_params = dict()

    model = init_bcg_sparse_model(
        dataset, modalities_to_use, main_modality, num_topics, bcg_topics, specific_topic_names, model_params
    )

    if specific_topic_names is None:
        print('No spec topics')
        specific_topic_names = model.topic_names[:-bcg_topics]

    model.regularizers.add(
        artm.DecorrelatorPhiRegularizer(
            gamma=0,
            tau=model_params.get('decorrelation_tau', 0.01),
            name='decorrelation',
            topic_names=specific_topic_names,
            class_ids=modalities_to_use,
        )
    )

    return model

In [28]:
TOPIC_INDICES = list(range(NUM_TOPICS))

In [29]:
TOPIC_INDICES

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49]

In [30]:
phi0 = pd.read_csv(f'{RESULTS_FOLDER_PATH}/0/phi.csv', index_col=0)

In [31]:
phi0.head()

,background_1,topic_0,topic_1,topic_2,topic_3,topic_4,topic_5,topic_6,topic_7,topic_8,...,topic_40,topic_41,topic_42,topic_43,topic_44,topic_45,topic_46,topic_47,topic_48,topic_49
00,0.000000,0.000000,0.000219,0.000369,0.000000,0.000000,0.00000,0.000000,0.000000,0.00000,...,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
000,0.001543,0.001565,0.002554,0.000337,0.000787,0.001491,0.00233,0.000346,0.000724,0.00049,...,0.0,0.0,0.001618,0.0,0.0,0.005659,0.0,0.0,0.0,0.0
0000001,0.000000,0.000050,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.00000,...,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
00002,0.000068,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.00000,...,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
0001,0.000000,0.000043,0.000000,0.000000,0.000163,0.000000,0.00000,0.000000,0.000000,0.00000,...,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0

In [32]:
phi0.set_index([[MAIN_MODALITY] * len(phi0.index), phi0.index], inplace=True)

In [33]:
phi0.head()

               background_1   topic_0   topic_1   topic_2   topic_3   topic_4  \
@text 00           0.000000  0.000000  0.000219  0.000369  0.000000  0.000000
      000          0.001543  0.001565  0.002554  0.000337  0.000787  0.001491
      0000001      0.000000  0.000050  0.000000  0.000000  0.000000  0.000000
      00002        0.000068  0.000000  0.000000  0.000000  0.000000  0.000000
      0001         0.000000  0.000043  0.000000  0.000000  0.000163  0.000000

               topic_5   topic_6   topic_7  topic_8  ...  topic_40  topic_41  \
@text 00       0.00000  0.000000  0.000000  0.00000  ...       0.0       0.0
      000      0.00233  0.000346  0.000724  0.00049  ...       0.0       0.0
      0000001  0.00000  0.000000  0.000000  0.00000  ...       0.0       0.0
      00002    0.00000  0.000000  0.000000  0.00000  ...       0.0       0.0
      0001     0.00000  0.000000  0.000000  0.00000  ...       0.0       0.0

               topic_42  topic_43  topic_44  topic_45  topic_46  topic_47  \
@text 00       0.000000       0.0       0.0  0.000000       0.0       0.0
      000      0.001618       0.0       0.0  0.005659       0.0       0.0
      0000001  0.000000       0.0       0.0  0.000000       0.0       0.0
      00002    0.000000       0.0       0.0  0.000000       0.0       0.0
      0001     0.000000       0.0       0.0  0.000000       0.0       0.0

               topic_48  topic_49
@text 00            0.0       0.0
      000           0.0       0.0
      0000001       0.0       0.0
      00002         0.0       0.0
      0001          0.0       0.0

[5 rows x 51 columns]

In [34]:
DIFF_THRESHOLD = 2

In [35]:
def check_top_words(phi, top_words):
    diffs = []

    for t, topic_top_words in top_words.items():
        if t == 'background_1':
            print(f'Skipping background topic: {t}.')

            continue

        print(t)
        # print(top_words)
    
        top_phi = set(phi[t].sort_values(ascending=False)[:NUM_TOP_TOKENS].index.get_level_values(1))
        top_bt = set([p[0] for p in topic_top_words])
    
        if top_phi == top_bt:
            diffs.append(
                {
                    'total': 0,
                    'lost_bt': 0,
                    'lost_model': 0,
                }
            )
        else:
            diff1 = top_phi.difference(top_bt)
            diff2 = top_bt.difference(top_phi)
    
            print('  WTF:', diff1, diff2)
    
            if len(diff1) > DIFF_THRESHOLD:
                print(f'  WTF?!?!?', len(diff1))
    
            if len(diff2) > DIFF_THRESHOLD:
                print(f'  WTF?!?!?', len(diff2))

            diffs.append(
                {
                    'total': len(diff1 | diff2),
                    'lost_bt': len(diff2),
                    'lost_model': len(diff1),
                }
            )

    return diffs

In [36]:
def init_model_and_phi(num_topics, dataset, phi0):
    model = init_model_from_family(
        family=KnownModel.PLSA,
        dataset=dataset,
        main_modality=MAIN_MODALITY,
        num_topics=num_topics,
        seed=0,
    )
    
    phi = model.get_phi()
    
    # assert phi.shape[1] == phi0.shape[1] - 1
    assert phi.shape[1] == num_topics
    assert phi.shape[1] in [phi0.shape[1], phi0.shape[1] - 1]
    
    common_words = list(set(phi.index).intersection(phi0.index))
    
    phi.loc[:, :] = 0

    if phi.shape[1] == phi0.shape[1]:
        target_topics = phi0.columns
    elif phi.shape[1] == phi0.shape[1] - 1:
        target_topics = phi.columns
    else:
        assert False

    # print(common_words, phi.index, phi0.index)

    phi.loc[common_words, :] += phi0.loc[common_words, target_topics]

    diff = set(phi0.columns).symmetric_difference(set(phi.columns))

    assert diff == {'background_1'} or diff == {'background_1', f'topic_{len(phi.columns) - 1}'}
    
    phi = phi / phi.sum(axis=0)

    return model, phi, common_words

In [37]:
results = []

is_results_loaded = False

save_file_path = os.path.join(
    SAVE_FOLDER, 'bertopic.json'
)

if os.path.isfile(save_file_path):
    results = json.loads(
        open(save_file_path).read()
    )
    is_results_loaded = True


singles_save_folder = os.path.join(
    SAVE_FOLDER, 'bertopic'
)

os.makedirs(singles_save_folder, exist_ok=True)


for seed in range(NUM_TRAINS):
    if is_results_loaded:
        continue

    print(seed)

    current_save_file_path = os.path.join(
        singles_save_folder, f'bertopic_{seed}.json'
    )

    if os.path.isfile(current_save_file_path):
        print(f'Already computed results: {current_save_file_path}. Loading and skipping...')

        result = json.loads(
            open(current_save_file_path).read()
        )
        results.append(result)

        continue

    seed_load_folder = os.path.join(RESULTS_FOLDER_PATH, str(seed))
    files = [f for f in os.listdir(seed_load_folder) if os.path.isfile(f'{seed_load_folder}/{f}')]
    
    assert len(files) == 3

    dataset = Dataset(
        f'{seed_load_folder}/dataset.csv',
    )
    phi0 = pd.read_csv(f'{seed_load_folder}/phi.csv', index_col=0)
    phi0.set_index([[MAIN_MODALITY] * len(phi0.index), phi0.index], inplace=True)

    assert all('back' not in t for t in phi0.columns[1:])
    assert 'back' in phi0.columns[0]

    num_specific_topics = phi0.shape[1] - 1

    assert num_specific_topics == len([t for t in phi0.columns if 'back' not in t])

    print(f'Num model topics: {phi0.shape[1]}.')

    with open(f'{seed_load_folder}/top_words.json', 'r') as f:
        top_words = json.loads(f.read())


    
    model, phi, common_phi_words = init_model_and_phi(
        num_topics=num_specific_topics + 1,  # background
        dataset=dataset, phi0=phi0
    )
    common_words = [
        w[1] for w in common_phi_words  # without modality
    ]
    common_words_phi0_indices = [
        # phi0.index.get_loc(w) for w in common_words
        int(phi0.index.get_locs(w)) for w in common_phi_words
    ]

    print('Check before fit:')
    diff_tops1 = check_top_words(phi, top_words)  # Whatever...
    
    fix_regularizer = FastFixPhiRegularizer(
        name='fix',
        parent_phi=phi0.iloc[common_words_phi0_indices, 1:],
        words=common_words,
        topic_names=phi.columns[1:],
    )
    result = fit_and_compute_scores(
        model, dataset,
        target_topic_indices=list(range(phi.shape[1])),
        custom_regularizers = {
            fix_regularizer.name: fix_regularizer,
        }
    )

    print('Check after fit:')
    diff_tops2 = check_top_words(phi, top_words)  # Whatever...

    assert diff_tops1 == diff_tops2

    fair_ppl_free = result['scores']['perplexity']

    del model, phi, fix_regularizer, result


    
    model, phi, _ = init_model_and_phi(
        num_topics=num_specific_topics + 1,  # background
        dataset=dataset, phi0=phi0
    )
    fix_regularizer = FastFixPhiRegularizer(
        name='fix',
        parent_phi=phi0.iloc[common_words_phi0_indices, :],  # Diff here
        words=common_words,
        topic_names=phi.columns,
    )
    result = fit_and_compute_scores(
        model, dataset,
        target_topic_indices=list(range(phi.shape[1])),
        custom_regularizers = {
            fix_regularizer.name: fix_regularizer,
        }
    )
    
    fair_ppl_fix = result['scores']['perplexity']

    del model, phi, fix_regularizer, result

    
    
    model, phi, _ = init_model_and_phi(
        num_topics=num_specific_topics,  # Diff here
        dataset=dataset, phi0=phi0
    )
    fix_regularizer = FastFixPhiRegularizer(
        name='fix',
        parent_phi=phi0.iloc[common_words_phi0_indices, 1:],  # Diff here
        words=common_words,
        topic_names=phi.columns,
    )
    result = fit_and_compute_scores(
        model, dataset,
        custom_regularizers = {
            fix_regularizer.name: fix_regularizer,
        }
    )

    unfair_ppl_banklike = result['scores']['perplexity']


    
    result['scores']['fair_ppl_free'] = fair_ppl_free
    result['scores']['fair_ppl_fix'] = fair_ppl_fix
    result['scores']['unfair_ppl_banklike'] = unfair_ppl_banklike

    assert result['scores']['fair_ppl_free'] < result['scores']['unfair_ppl_banklike']
    # assert result['scores']['fair_ppl_fix'] < result['scores']['unfair_ppl_banklike']

    result['scores']['coherence_20'] = float(result['scores']['coherence_20'])
    result['stats'] = {
        'num_topics': phi0.shape[1],
        'num_common_words': len(common_words),
        'num_model_words': phi.shape[0],
        'num_bt_words': phi0.shape[0],
        'top_diffs': diff_tops2,
    }

    results.append(result)

    print(result['scores'])
    print(result['stats'])

    dumped_result = json.dumps(
        results[-1], indent=4
    )

    with open(current_save_file_path, 'w') as f:
        f.write(dumped_result)

    del model, phi, fix_regularizer


with open(save_file_path, 'w') as f:
    f.write(
        json.dumps(
            results, indent=4
        )
    )

0
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
  WTF: {'10'} {'вич'}
topic_1
topic_2
  WTF: {'quote', 'аутизма', 'часто', 'например'} {'dsm', 'начало_цитаты', 'мкб', 'аспергера'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_3
topic_4
  WTF: {'метастазов'} {'гисо'}
topic_5
  WTF: {'кровообращения', 'артериальной'} {'ибс', 'экг'}
topic_6
topic_7
  WTF: {'болезни'} {'срк'}
topic_8
  WTF: {'ts'} {'спнка'}
topic_9
  WTF: {'астмой', 'мокроты'} {'хобл', 'блд'}
topic_10
topic_11
  WTF: {'гемофилия', 'анемия', 'уровня'} {'виллебранда', 'viii', 'гит'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_12
  WTF: {'лимфома', 'миелоидного', 'циклина'} {'опл', 'd1', 'омл'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_13
topic_14
topic_15
  WTF: {'хороидеремии', 'кератансульфатов'} {'кератоэпителин', 'tgfbi'}
topic_16
topic_17
  WTF: {'ожирения', 'ожирением', 'энурез'} {'dsm', 'мкб', 'commentedtext'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_18
  WTF: {'крови', 'глюкозы', 'сознания', 'мозжечка'} {'кт', 'сдг', 'вчг', 'сак'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_19
topic_20
topic_21
  WTF: {'сонного'} {'hppd'}
topic_22
  WTF: {'нейросенсорная'} {'дб'}
topic_23
topic_24
topic_25
  WTF: {'терапии'} {'знс'}
topic_26
  WTF: {'костей', 'пластины'} {'дюпюитрена', 'мортона'}
topic_27
  WTF: {'обычно', 'две', 'анеуплоидия', 'также', 'хромосому', 'могут', 'мужчин'} {'магенис', 'xxyy', 'xxxy', 'фабри', 'xy', 'xx', 'смит'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_28
topic_29
  WTF: {'содержание'} {'адг'}
topic_30
topic_31
  WTF: {'кисты'} {'пвл'}
topic_32
  WTF: {'en'} {'альцгеймера'}
topic_33
topic_34
  WTF: {'системы', 'гиперкортицизм'} {'щж', 'аит'}
topic_35
topic_36
  WTF: {'доказательности', 'пищевода', 'геморрагическими', 'гранулематоз', 'течение', 'васкулита', 'грудной', 'трахеи', 'больных'} {'иэ', 'св', 'мпа', 'эгпа', 'вегенера', 'цф', 'анца', 'эхокг', 'гпа'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_37
  WTF: {'миелоидные', 'клетки', 'выживаемость'} {'юинга', 'амс', 'капоши'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_38
  WTF: {'витамина', 'заболевание'} {'вельтищеву', 'хлб'}
topic_39
  WTF: {'кишки', 'приона', 'прионные', 'головки', 'парапроктита'} {'prpsc', 'крейтцфельдта', 'prpc', 'prp', 'paragonimus'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_40
  WTF: {'атрофия'} {'кпт'}
topic_41
  WTF: {'недостатка', 'животных'} {'b1', 'b12'}
topic_42
  WTF: {'ткани'} {'trombicula'}
topic_43
  WTF: {'канала'} {'дгпж'}
topic_44
  WTF: {'бензнидазол'} {'шагаса'}
topic_45
  WTF: {'случаев', 'моно', '50', 'артритом'} {'цог', 'b27', 'гкс', 'нпвп'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_46
  WTF: {'невралгия'} {'гбн'}
topic_47
  WTF: {'чаще', 'болеют'} {'wnt3', 'бехчета'}
topic_48
topic_49
  WTF: {'окостенению', 'фибродисплазией'} {'фоп', 'дф'}
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f404c1e9c40>}
Check after fit:
Skipping background topic: background_1.
topic_0
  WTF: {'10'} {'вич'}
topic_1
topic_2
  WTF: {'quote', 'аутизма', 'часто', 'например'} {'dsm', 'начало_цитаты', 'мкб', 'аспергера'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_3
topic_4
  WTF: {'метастазов'} {'гисо'}
topic_5
  WTF: {'кровообращения', 'артериальной'} {'ибс', 'экг'}
topic_6
topic_7
  WTF: {'болезни'} {'срк'}
topic_8
  WTF: {'ts'} {'спнка'}
topic_9
  WTF: {'астмой', 'мокроты'} {'хобл', 'блд'}
topic_10
topic_11
  WTF: {'гемофилия', 'анемия', 'уровня'} {'виллебранда', 'viii', 'гит'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_12
  WTF: {'лимфома', 'миелоидного', 'циклина'} {'опл', 'd1', 'омл'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_13
topic_14
topic_15
  WTF: {'хороидеремии', 'кератансульфатов'} {'кератоэпителин', 'tgfbi'}
topic_16
topic_17
  WTF: {'ожирения', 'ожирением', 'энурез'} {'dsm', 'мкб', 'commentedtext'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_18
  WTF: {'крови', 'глюкозы', 'сознания', 'мозжечка'} {'кт', 'сдг', 'вчг', 'сак'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_19
topic_20
topic_21
  WTF: {'сонного'} {'hppd'}
topic_22
  WTF: {'нейросенсорная'} {'дб'}
topic_23
topic_24
topic_25
  WTF: {'терапии'} {'знс'}
topic_26
  WTF: {'костей', 'пластины'} {'дюпюитрена', 'мортона'}
topic_27
  WTF: {'обычно', 'две', 'анеуплоидия', 'также', 'хромосому', 'могут', 'мужчин'} {'магенис', 'xxyy', 'xxxy', 'фабри', 'xy', 'xx', 'смит'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_28
topic_29
  WTF: {'содержание'} {'адг'}
topic_30
topic_31
  WTF: {'кисты'} {'пвл'}
topic_32
  WTF: {'en'} {'альцгеймера'}
topic_33
topic_34
  WTF: {'системы', 'гиперкортицизм'} {'щж', 'аит'}
topic_35
topic_36
  WTF: {'доказательности', 'пищевода', 'геморрагическими', 'гранулематоз', 'течение', 'васкулита', 'грудной', 'трахеи', 'больных'} {'иэ', 'св', 'мпа', 'эгпа', 'вегенера', 'цф', 'анца', 'эхокг', 'гпа'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_37
  WTF: {'миелоидные', 'клетки', 'выживаемость'} {'юинга', 'амс', 'капоши'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_38
  WTF: {'витамина', 'заболевание'} {'вельтищеву', 'хлб'}
topic_39
  WTF: {'кишки', 'приона', 'прионные', 'головки', 'парапроктита'} {'prpsc', 'крейтцфельдта', 'prpc', 'prp', 'paragonimus'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_40
  WTF: {'атрофия'} {'кпт'}
topic_41
  WTF: {'недостатка', 'животных'} {'b1', 'b12'}
topic_42
  WTF: {'ткани'} {'trombicula'}
topic_43
  WTF: {'канала'} {'дгпж'}
topic_44
  WTF: {'бензнидазол'} {'шагаса'}
topic_45
  WTF: {'случаев', 'моно', '50', 'артритом'} {'цог', 'b27', 'гкс', 'нпвп'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_46
  WTF: {'невралгия'} {'гбн'}
topic_47
  WTF: {'чаще', 'болеют'} {'wnt3', 'бехчета'}
topic_48
topic_49
  WTF: {'окостенению', 'фибродисплазией'} {'фоп', 'дф'}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3fea4fe460>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3f33abf340>}
{'perplexity': 46747.03125, 'coherence_20': 1.4507651354753799, 'toplen_ptw': 1.4953236517968609, 'diversity_euclidean': 0.03512343743136369, 'diversity_jensenshannon': 0.7224571063507161, 'diversity_hellinger': 0.8572494990821297, 'diversity_cosine': 0.80604851219669, 'fair_ppl_free': 6122.6025390625, 'fair_ppl_fix': 42166.61328125, 'unfair_ppl_banklike': 46747.03125}
{'num_topics': 51, 'num_common_words': 101018, 'num_model_words': 127266, 'num_bt_words': 115899, 'top_diffs': [{'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}]}
1
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
  WTF: {'10'} {'вич'}
topic_1
topic_2
  WTF: {'quote', 'аутизма', 'часто', 'например'} {'dsm', 'начало_цитаты', 'мкб', 'аспергера'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_3
topic_4
  WTF: {'метастазов'} {'гисо'}
topic_5
topic_6
  WTF: {'перегородки', 'пучка', 'кровообращения', 'левой'} {'гиса', 'фп', 'ибс', 'экг'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_7
  WTF: {'ts'} {'спнка'}
topic_8
  WTF: {'отдела', 'лечение'} {'крона', 'срк'}
topic_9
  WTF: {'туберкулёзом', 'астмой'} {'хобл', 'блд'}
topic_10
topic_11
topic_12
  WTF: {'анемия', 'эритроцитов', 'кровотечений'} {'виллебранда', 'viii', 'гит'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_13
topic_14
  WTF: {'кератоэпителин', 'хороидеремии'} {'tgfbi', 'кератансульфатов'}
topic_15
  WTF: {'ожирения', 'ожирением', 'энурез'} {'dsm', 'мкб', 'commentedtext'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_16
topic_17
topic_18
topic_19
  WTF: {'паркинсонизма', 'головы'} {'альцгеймера', 'дцп'}
topic_20
  WTF: {'нейросенсорная'} {'дб'}
topic_21
topic_22
topic_23
  WTF: {'терапии'} {'знс'}
topic_24
topic_25
topic_26
  WTF: {'обычно', 'две', 'анеуплоидия', 'также', 'хромосому', 'могут', 'мужчин'} {'магенис', 'xxyy', 'xxxy', 'фабри', 'xy', 'xx', 'смит'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_27
  WTF: {'пластины', 'фаланг'} {'дюпюитрена', 'мортона'}
topic_28
  WTF: {'крови', 'abl', 'химиотерапии', 'транс', 'стволовых'} {'хмл', 'опл', 'омл', 'atra', 'фаб'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_29
  WTF: {'вещества', 'вируса'} {'пмл', 'пвл'}
topic_30
  WTF: {'англ', 'экспрессии', 'клетках', 'больных'} {'хлл', 'd1', 'нхл', 'ходжкина'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_31
  WTF: {'содержание'} {'адг'}
topic_32
  WTF: {'сосудов', 'кровотока', 'давление', 'сознания'} {'кт', 'сдг', 'вчг', 'сак'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_33
  WTF: {'ядер', 'снижение'} {'т4', 'b12'}
topic_34
  WTF: {'узловой', 'гиперальдостеронизм'} {'псевдогиперпаратиреоз', 'аит'}
topic_35
topic_36
topic_37
  WTF: {'паука'} {'buthidae'}
topic_38
  WTF: {'сосудов', 'гипертонический', 'портальной', 'больных'} {'иапф', 'ад', 'ара', 'аг'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_39
  WTF: {'редкое', 'органов'} {'боуэна', 'wnt3'}
topic_40
  WTF: {'атрофия'} {'кпт'}
topic_41
topic_42
  WTF: {'кишки', 'приона', 'прионные', 'головки', 'парапроктита'} {'prpsc', 'крейтцфельдта', 'prpc', 'prp', 'paragonimus'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_43
  WTF: {'резкая'} {'фос'}
topic_44
  WTF: {'случаев', 'моно', '50', 'артритом'} {'цог', 'b27', 'гкс', 'нпвп'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_45
  WTF: {'бензнидазол'} {'шагаса'}
topic_46
  WTF: {'канала'} {'дгпж'}
topic_47
  WTF: {'клещей'} {'trombicula'}
topic_48
topic_49
  WTF: {'окостенению', 'фибродисплазией'} {'фоп', 'дф'}
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3faab050a0>}
Check after fit:
Skipping background topic: background_1.
topic_0
  WTF: {'10'} {'вич'}
topic_1
topic_2
  WTF: {'quote', 'аутизма', 'часто', 'например'} {'dsm', 'начало_цитаты', 'мкб', 'аспергера'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_3
topic_4
  WTF: {'метастазов'} {'гисо'}
topic_5
topic_6
  WTF: {'перегородки', 'пучка', 'кровообращения', 'левой'} {'гиса', 'фп', 'ибс', 'экг'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_7
  WTF: {'ts'} {'спнка'}
topic_8
  WTF: {'отдела', 'лечение'} {'крона', 'срк'}
topic_9
  WTF: {'туберкулёзом', 'астмой'} {'хобл', 'блд'}
topic_10
topic_11
topic_12
  WTF: {'анемия', 'эритроцитов', 'кровотечений'} {'виллебранда', 'viii', 'гит'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_13
topic_14
  WTF: {'кератоэпителин', 'хороидеремии'} {'tgfbi', 'кератансульфатов'}
topic_15
  WTF: {'ожирения', 'ожирением', 'энурез'} {'dsm', 'мкб', 'commentedtext'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_16
topic_17
topic_18
topic_19
  WTF: {'паркинсонизма', 'головы'} {'альцгеймера', 'дцп'}
topic_20
  WTF: {'нейросенсорная'} {'дб'}
topic_21
topic_22
topic_23
  WTF: {'терапии'} {'знс'}
topic_24
topic_25
topic_26
  WTF: {'обычно', 'две', 'анеуплоидия', 'также', 'хромосому', 'могут', 'мужчин'} {'магенис', 'xxyy', 'xxxy', 'фабри', 'xy', 'xx', 'смит'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_27
  WTF: {'пластины', 'фаланг'} {'дюпюитрена', 'мортона'}
topic_28
  WTF: {'крови', 'abl', 'химиотерапии', 'транс', 'стволовых'} {'хмл', 'опл', 'омл', 'atra', 'фаб'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_29
  WTF: {'вещества', 'вируса'} {'пмл', 'пвл'}
topic_30
  WTF: {'англ', 'экспрессии', 'клетках', 'больных'} {'хлл', 'd1', 'нхл', 'ходжкина'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_31
  WTF: {'содержание'} {'адг'}
topic_32
  WTF: {'сосудов', 'кровотока', 'давление', 'сознания'} {'кт', 'сдг', 'вчг', 'сак'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_33
  WTF: {'ядер', 'снижение'} {'т4', 'b12'}
topic_34
  WTF: {'узловой', 'гиперальдостеронизм'} {'псевдогиперпаратиреоз', 'аит'}
topic_35
topic_36
topic_37
  WTF: {'паука'} {'buthidae'}
topic_38
  WTF: {'сосудов', 'гипертонический', 'портальной', 'больных'} {'иапф', 'ад', 'ара', 'аг'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_39
  WTF: {'редкое', 'органов'} {'боуэна', 'wnt3'}
topic_40
  WTF: {'атрофия'} {'кпт'}
topic_41
topic_42
  WTF: {'кишки', 'приона', 'прионные', 'головки', 'парапроктита'} {'prpsc', 'крейтцфельдта', 'prpc', 'prp', 'paragonimus'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_43
  WTF: {'резкая'} {'фос'}
topic_44
  WTF: {'случаев', 'моно', '50', 'артритом'} {'цог', 'b27', 'гкс', 'нпвп'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_45
  WTF: {'бензнидазол'} {'шагаса'}
topic_46
  WTF: {'канала'} {'дгпж'}
topic_47
  WTF: {'клещей'} {'trombicula'}
topic_48
topic_49
  WTF: {'окостенению', 'фибродисплазией'} {'фоп', 'дф'}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f406f9a5430>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f406f9a5280>}
{'perplexity': 46482.0703125, 'coherence_20': 1.453203647940362, 'toplen_ptw': 1.4887809648914516, 'diversity_euclidean': 0.03398003121282238, 'diversity_jensenshannon': 0.7205049027548576, 'diversity_hellinger': 0.8549467491985647, 'diversity_cosine': 0.8018497409311374, 'fair_ppl_free': 6094.2158203125, 'fair_ppl_fix': 42155.3359375, 'unfair_ppl_banklike': 46482.0703125}
{'num_topics': 51, 'num_common_words': 101018, 'num_model_words': 127266, 'num_bt_words': 115899, 'top_diffs': [{'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}]}
2
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
  WTF: {'10'} {'вич'}
topic_1
topic_2
  WTF: {'quote', 'аутизма', 'часто', 'например'} {'dsm', 'начало_цитаты', 'мкб', 'аспергера'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_3
  WTF: {'является'} {'спнка'}
topic_4
  WTF: {'мозга'} {'гисо'}
topic_5
  WTF: {'случаев', 'могут'} {'эчб', 'мдс'}
topic_6
  WTF: {'перегородки', 'пучка', 'левой', 'правого'} {'гиса', 'фп', 'ибс', 'экг'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_7
  WTF: {'ферментов', 'типа', 'типу'} {'гфф', 'gm2', 'iga'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_8
topic_9
topic_10
  WTF: {'также', 'детей'} {'хобл', 'блд'}
topic_11
  WTF: {'лечение', 'является'} {'крона', 'срк'}
topic_12
  WTF: {'мигрень', 'нарушения'} {'альцгеймера', 'знс'}
topic_13
  WTF: {'эритроцитов', 'кровотечений', 'вен'} {'виллебранда', 'viii', 'гит'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_14
topic_15
  WTF: {'хороидеремии', 'кератансульфатов'} {'кератоэпителин', 'tgfbi'}
topic_16
topic_17
  WTF: {'ожирения', 'ожирением', 'энурез'} {'dsm', 'мкб', 'commentedtext'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_18
topic_19
topic_20
topic_21
  WTF: {'нейросенсорная'} {'дб'}
topic_22
topic_23
topic_24
  WTF: {'крови', 'abl', 'химиотерапии', 'транс', 'стволовых'} {'хмл', 'опл', 'омл', 'atra', 'фаб'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_25
topic_26
  WTF: {'обычно', 'две', 'анеуплоидия', 'также', 'хромосому', 'могут', 'мужчин'} {'магенис', 'xxyy', 'xxxy', 'фабри', 'xy', 'xx', 'смит'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_27
  WTF: {'англ', 'экспрессии', 'клетках', 'больных'} {'хлл', 'd1', 'нхл', 'ходжкина'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_28
  WTF: {'содержание'} {'адг'}
topic_29
topic_30
  WTF: {'сыворотки', 'больного', 'ботулотоксин'} {'киари', 'сак', 'арнольда'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_31
  WTF: {'артерий', 'кровотока', 'окклюзии', 'давление'} {'кт', 'сдг', 'вчг', 'сак'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_32
  WTF: {'других', 'аутосомно', 'больных'} {'пмл', 'пвл', 'jc'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_33
topic_34
  WTF: {'поражение', 'люпус'} {'олб', 'wnt3'}
topic_35
  WTF: {'функции'} {'т4'}
topic_36
  WTF: {'системы', 'гиперкортицизм'} {'щж', 'аит'}
topic_37
  WTF: {'давление', 'гипертонический', 'сосудов', 'портальной', 'больных'} {'зг', 'ара', 'иапф', 'ад', 'аг'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_38
  WTF: {'паука'} {'buthidae'}
topic_39
topic_40
  WTF: {'крапивницы'} {'ige'}
topic_41
  WTF: {'кишки', 'приона', 'прионные', 'головки', 'парапроктита'} {'prpsc', 'крейтцфельдта', 'prpc', 'prp', 'paragonimus'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_42
  WTF: {'10'} {'кпт'}
topic_43
  WTF: {'саркоидоз', 'остеогенная', 'миелоидных'} {'юинга', 'амс', 'капоши'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_44
  WTF: {'цитрусовые', 'титруемых'} {'вельтищеву', 'беллью'}
topic_45
  WTF: {'бензнидазол'} {'шагаса'}
topic_46
  WTF: {'случаев', 'моно', '50', 'артритом'} {'цог', 'b27', 'гкс', 'нпвп'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_47
topic_48
  WTF: {'клещей'} {'trombicula'}
topic_49
  WTF: {'канала'} {'дгпж'}
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3d65f78cd0>}
Check after fit:
Skipping background topic: background_1.
topic_0
  WTF: {'10'} {'вич'}
topic_1
topic_2
  WTF: {'quote', 'аутизма', 'часто', 'например'} {'dsm', 'начало_цитаты', 'мкб', 'аспергера'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_3
  WTF: {'является'} {'спнка'}
topic_4
  WTF: {'мозга'} {'гисо'}
topic_5
  WTF: {'случаев', 'могут'} {'эчб', 'мдс'}
topic_6
  WTF: {'перегородки', 'пучка', 'левой', 'правого'} {'гиса', 'фп', 'ибс', 'экг'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_7
  WTF: {'ферментов', 'типа', 'типу'} {'гфф', 'gm2', 'iga'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_8
topic_9
topic_10
  WTF: {'также', 'детей'} {'хобл', 'блд'}
topic_11
  WTF: {'лечение', 'является'} {'крона', 'срк'}
topic_12
  WTF: {'мигрень', 'нарушения'} {'альцгеймера', 'знс'}
topic_13
  WTF: {'эритроцитов', 'кровотечений', 'вен'} {'виллебранда', 'viii', 'гит'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_14
topic_15
  WTF: {'хороидеремии', 'кератансульфатов'} {'кератоэпителин', 'tgfbi'}
topic_16
topic_17
  WTF: {'ожирения', 'ожирением', 'энурез'} {'dsm', 'мкб', 'commentedtext'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_18
topic_19
topic_20
topic_21
  WTF: {'нейросенсорная'} {'дб'}
topic_22
topic_23
topic_24
  WTF: {'крови', 'abl', 'химиотерапии', 'транс', 'стволовых'} {'хмл', 'опл', 'омл', 'atra', 'фаб'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_25
topic_26
  WTF: {'обычно', 'две', 'анеуплоидия', 'также', 'хромосому', 'могут', 'мужчин'} {'магенис', 'xxyy', 'xxxy', 'фабри', 'xy', 'xx', 'смит'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_27
  WTF: {'англ', 'экспрессии', 'клетках', 'больных'} {'хлл', 'd1', 'нхл', 'ходжкина'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_28
  WTF: {'содержание'} {'адг'}
topic_29
topic_30
  WTF: {'сыворотки', 'больного', 'ботулотоксин'} {'киари', 'сак', 'арнольда'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_31
  WTF: {'артерий', 'кровотока', 'окклюзии', 'давление'} {'кт', 'сдг', 'вчг', 'сак'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_32
  WTF: {'других', 'аутосомно', 'больных'} {'пмл', 'пвл', 'jc'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_33
topic_34
  WTF: {'поражение', 'люпус'} {'олб', 'wnt3'}
topic_35
  WTF: {'функции'} {'т4'}
topic_36
  WTF: {'системы', 'гиперкортицизм'} {'щж', 'аит'}
topic_37
  WTF: {'давление', 'гипертонический', 'сосудов', 'портальной', 'больных'} {'зг', 'ара', 'иапф', 'ад', 'аг'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_38
  WTF: {'паука'} {'buthidae'}
topic_39
topic_40
  WTF: {'крапивницы'} {'ige'}
topic_41
  WTF: {'кишки', 'приона', 'прионные', 'головки', 'парапроктита'} {'prpsc', 'крейтцфельдта', 'prpc', 'prp', 'paragonimus'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_42
  WTF: {'10'} {'кпт'}
topic_43
  WTF: {'саркоидоз', 'остеогенная', 'миелоидных'} {'юинга', 'амс', 'капоши'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_44
  WTF: {'цитрусовые', 'титруемых'} {'вельтищеву', 'беллью'}
topic_45
  WTF: {'бензнидазол'} {'шагаса'}
topic_46
  WTF: {'случаев', 'моно', '50', 'артритом'} {'цог', 'b27', 'гкс', 'нпвп'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_47
topic_48
  WTF: {'клещей'} {'trombicula'}
topic_49
  WTF: {'канала'} {'дгпж'}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3da255ac70>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3d9ff59eb0>}
{'perplexity': 46466.92578125, 'coherence_20': 1.4893951817792885, 'toplen_ptw': 1.4837137962660856, 'diversity_euclidean': 0.033757716999576956, 'diversity_jensenshannon': 0.7183836398376372, 'diversity_hellinger': 0.8524623225094591, 'diversity_cosine': 0.7970768061002527, 'fair_ppl_free': 6042.015625, 'fair_ppl_fix': 42420.1640625, 'unfair_ppl_banklike': 46466.92578125}
{'num_topics': 51, 'num_common_words': 101018, 'num_model_words': 127266, 'num_bt_words': 115899, 'top_diffs': [{'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}]}
3
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
  WTF: {'10'} {'вич'}
topic_1
  WTF: {'quote', 'аутизма', 'часто', 'например'} {'dsm', 'начало_цитаты', 'мкб', 'аспергера'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_2
topic_3
  WTF: {'молочной'} {'гисо'}
topic_4
  WTF: {'могут', 'году'} {'эчб', 'мдс'}
topic_5
topic_6
  WTF: {'ферментов', 'встречается'} {'gm2', 'iga'}
topic_7
  WTF: {'перегородки', 'пучка', 'кровообращения', 'левой'} {'гиса', 'фп', 'ибс', 'экг'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_8
  WTF: {'мозга'} {'пвл'}
topic_9
  WTF: {'ts'} {'спнка'}
topic_10
  WTF: {'кашель', 'воздуха'} {'хобл', 'блд'}
topic_11
topic_12
  WTF: {'пищеводного', 'отдела'} {'крона', 'срк'}
topic_13
  WTF: {'анемией', 'гемоглобин', 'гемофилия', 'дефицита', 'конечностей', 'анемия'} {'viii', 'виллебранда', 'св', 'гит', 'анца', 'тэла'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_14
  WTF: {'лимфома', 'миелоидного', 'циклина'} {'опл', 'd1', 'омл'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_15
topic_16
  WTF: {'хороидеремии'} {'tgfbi'}
topic_17
  WTF: {'ожирения', 'ожирением', 'энурез'} {'dsm', 'мкб', 'commentedtext'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_18
topic_19
topic_20
topic_21
  WTF: {'нейросенсорная'} {'дб'}
topic_22
  WTF: {'терапии'} {'знс'}
topic_23
topic_24
topic_25
topic_26
  WTF: {'обычно', 'две', 'анеуплоидия', 'также', 'хромосому', 'могут', 'мужчин'} {'магенис', 'xxyy', 'xxxy', 'фабри', 'xy', 'xx', 'смит'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_27
  WTF: {'сосудов', 'тяжести', 'щитовидной'} {'олб', 'боуэна', 'wnt3'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_28
  WTF: {'синдром'} {'b12'}
topic_29
  WTF: {'пластины', 'фаланг'} {'дюпюитрена', 'мортона'}
topic_30
  WTF: {'содержание'} {'адг'}
topic_31
topic_32
  WTF: {'черепа', 'кровотока', 'давление', 'сознания'} {'кт', 'сдг', 'вчг', 'сак'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_33
  WTF: {'паротитом'} {'к05'}
topic_34
topic_35
  WTF: {'крапивницы'} {'ige'}
topic_36
  WTF: {'давление', 'гипертонический', 'сосудов', 'портальной', 'больных'} {'зг', 'ара', 'иапф', 'ад', 'аг'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_37
  WTF: {'механизму', 'заболевания'} {'щж', 'аит'}
topic_38
  WTF: {'паука'} {'buthidae'}
topic_39
  WTF: {'кишки', 'приона', 'прионные', 'головки', 'парапроктита'} {'prpsc', 'крейтцфельдта', 'prpc', 'prp', 'paragonimus'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_40
  WTF: {'головного'} {'гбн'}
topic_41
  WTF: {'10'} {'кпт'}
topic_42
topic_43
  WTF: {'случаев', 'моно', '50', 'артритом'} {'цог', 'b27', 'гкс', 'нпвп'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_44
  WTF: {'канала'} {'дгпж'}
topic_45
  WTF: {'вещества', 'соединения'} {'аи', 'фос'}
topic_46
  WTF: {'клещей'} {'trombicula'}
topic_47
  WTF: {'также', 'развития'} {'альцгеймера', 'дцп'}
topic_48
  WTF: {'бревно', 'терминальной', 'синдром'} {'скф', 'хбп', 'хпн'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_49
  WTF: {'строго'} {'дф'}
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3fea43deb0>}
Check after fit:
Skipping background topic: background_1.
topic_0
  WTF: {'10'} {'вич'}
topic_1
  WTF: {'quote', 'аутизма', 'часто', 'например'} {'dsm', 'начало_цитаты', 'мкб', 'аспергера'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_2
topic_3
  WTF: {'молочной'} {'гисо'}
topic_4
  WTF: {'могут', 'году'} {'эчб', 'мдс'}
topic_5
topic_6
  WTF: {'ферментов', 'встречается'} {'gm2', 'iga'}
topic_7
  WTF: {'перегородки', 'пучка', 'кровообращения', 'левой'} {'гиса', 'фп', 'ибс', 'экг'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_8
  WTF: {'мозга'} {'пвл'}
topic_9
  WTF: {'ts'} {'спнка'}
topic_10
  WTF: {'кашель', 'воздуха'} {'хобл', 'блд'}
topic_11
topic_12
  WTF: {'пищеводного', 'отдела'} {'крона', 'срк'}
topic_13
  WTF: {'анемией', 'гемоглобин', 'гемофилия', 'дефицита', 'конечностей', 'анемия'} {'viii', 'виллебранда', 'св', 'гит', 'анца', 'тэла'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_14
  WTF: {'лимфома', 'миелоидного', 'циклина'} {'опл', 'd1', 'омл'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_15
topic_16
  WTF: {'хороидеремии'} {'tgfbi'}
topic_17
  WTF: {'ожирения', 'ожирением', 'энурез'} {'dsm', 'мкб', 'commentedtext'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_18
topic_19
topic_20
topic_21
  WTF: {'нейросенсорная'} {'дб'}
topic_22
  WTF: {'терапии'} {'знс'}
topic_23
topic_24
topic_25
topic_26
  WTF: {'обычно', 'две', 'анеуплоидия', 'также', 'хромосому', 'могут', 'мужчин'} {'магенис', 'xxyy', 'xxxy', 'фабри', 'xy', 'xx', 'смит'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_27
  WTF: {'сосудов', 'тяжести', 'щитовидной'} {'олб', 'боуэна', 'wnt3'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_28
  WTF: {'синдром'} {'b12'}
topic_29
  WTF: {'пластины', 'фаланг'} {'дюпюитрена', 'мортона'}
topic_30
  WTF: {'содержание'} {'адг'}
topic_31
topic_32
  WTF: {'черепа', 'кровотока', 'давление', 'сознания'} {'кт', 'сдг', 'вчг', 'сак'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_33
  WTF: {'паротитом'} {'к05'}
topic_34
topic_35
  WTF: {'крапивницы'} {'ige'}
topic_36
  WTF: {'давление', 'гипертонический', 'сосудов', 'портальной', 'больных'} {'зг', 'ара', 'иапф', 'ад', 'аг'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_37
  WTF: {'механизму', 'заболевания'} {'щж', 'аит'}
topic_38
  WTF: {'паука'} {'buthidae'}
topic_39
  WTF: {'кишки', 'приона', 'прионные', 'головки', 'парапроктита'} {'prpsc', 'крейтцфельдта', 'prpc', 'prp', 'paragonimus'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_40
  WTF: {'головного'} {'гбн'}
topic_41
  WTF: {'10'} {'кпт'}
topic_42
topic_43
  WTF: {'случаев', 'моно', '50', 'артритом'} {'цог', 'b27', 'гкс', 'нпвп'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_44
  WTF: {'канала'} {'дгпж'}
topic_45
  WTF: {'вещества', 'соединения'} {'аи', 'фос'}
topic_46
  WTF: {'клещей'} {'trombicula'}
topic_47
  WTF: {'также', 'развития'} {'альцгеймера', 'дцп'}
topic_48
  WTF: {'бревно', 'терминальной', 'синдром'} {'скф', 'хбп', 'хпн'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_49
  WTF: {'строго'} {'дф'}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3fea4238b0>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3d126f5040>}
{'perplexity': 46752.578125, 'coherence_20': 1.4595289219930663, 'toplen_ptw': 1.534619526173212, 'diversity_euclidean': 0.033996128543347374, 'diversity_jensenshannon': 0.7181444001038152, 'diversity_hellinger': 0.852010599672801, 'diversity_cosine': 0.7980071257958347, 'fair_ppl_free': 6032.189453125, 'fair_ppl_fix': 41988.78515625, 'unfair_ppl_banklike': 46752.578125}
{'num_topics': 51, 'num_common_words': 101018, 'num_model_words': 127266, 'num_bt_words': 115899, 'top_diffs': [{'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}]}
4
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
  WTF: {'10'} {'вич'}
topic_1
  WTF: {'quote', 'детей', 'часто', 'например'} {'dsm', 'начало_цитаты', 'мкб', 'аспергера'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_2
topic_3
  WTF: {'саркомы'} {'гисо'}
topic_4
topic_5
  WTF: {'склероза'} {'мдс'}
topic_6
  WTF: {'встречается', 'наследуется'} {'gm2', 'iga'}
topic_7
  WTF: {'перегородки', 'пучка', 'кровообращения', 'левой'} {'гиса', 'фп', 'ибс', 'экг'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_8
  WTF: {'ts'} {'спнка'}
topic_9
  WTF: {'кашель', 'воздуха'} {'хобл', 'блд'}
topic_10
topic_11
  WTF: {'отдела', 'лечение'} {'крона', 'срк'}
topic_12
  WTF: {'арахноидита', 'ишемического'} {'сдг', 'сак'}
topic_13
topic_14
  WTF: {'эритроцитов', 'уровня', 'кровотечений', 'вен'} {'виллебранда', 'тр', 'viii', 'гит'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_15
  WTF: {'кератоэпителин', 'кератансульфатов'} {'tgfbi', 'bcd'}
topic_16
topic_17
  WTF: {'ожирения', 'ожирением', 'энурез'} {'dsm', 'мкб', 'commentedtext'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_18
  WTF: {'анафилактического'} {'ige'}
topic_19
topic_20
topic_21
topic_22
topic_23
  WTF: {'крови', 'abl', 'химиотерапии', 'транс', 'стволовых'} {'хмл', 'опл', 'омл', 'atra', 'фаб'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_24
  WTF: {'терапии'} {'знс'}
topic_25
topic_26
  WTF: {'обычно', 'две', 'анеуплоидия', 'также', 'хромосому', 'могут', 'мужчин'} {'магенис', 'xxyy', 'xxxy', 'фабри', 'xy', 'xx', 'смит'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_27
  WTF: {'крови', 'почек', 'каждые', 'плевры', 'сосудов', 'эмфиземы', 'артерии', 'больных'} {'иэ', 'св', 'мпа', 'рейно', 'цф', 'анца', 'тэла', 'гпа'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_28
  WTF: {'случаев', 'развития'} {'альцгеймера', 'дцп'}
topic_29
  WTF: {'англ', 'экспрессии', 'клетках', 'больных'} {'хлл', 'd1', 'нхл', 'ходжкина'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_30
  WTF: {'содержание'} {'адг'}
topic_31
  WTF: {'анестезией', 'анестетика'} {'дюпюитрена', 'мортона'}
topic_32
topic_33
  WTF: {'давление', 'гипертонический', 'сосудов', 'портальной', 'больных'} {'зг', 'ара', 'иапф', 'ад', 'аг'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_34
topic_35
  WTF: {'других'} {'пвл'}
topic_36
  WTF: {'механизму', 'заболевания'} {'щж', 'аит'}
topic_37
  WTF: {'недоедания'} {'кпт'}
topic_38
topic_39
  WTF: {'паука'} {'buthidae'}
topic_40
  WTF: {'кишки', 'приона', 'прионные', 'головки', 'парапроктита'} {'prpsc', 'крейтцфельдта', 'prpc', 'prp', 'paragonimus'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_41
  WTF: {'мастоцитоз'} {'wnt3'}
topic_42
  WTF: {'головного'} {'гбн'}
topic_43
topic_44
  WTF: {'бензнидазол'} {'шагаса'}
topic_45
  WTF: {'случаев', 'моно', '50', 'артритом'} {'цог', 'b27', 'гкс', 'нпвп'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_46
  WTF: {'канала'} {'дгпж'}
topic_47
  WTF: {'нарушением', 'витаминной'} {'бад', 'b12'}
topic_48
  WTF: {'клещей'} {'trombicula'}
topic_49
  WTF: {'заеда', 'диеты', 'аглютеновой', 'заболевания', 'лакунарная', 'тонкой', 'вводят', 'заеде'} {'dq', 'людвига', 'жансуля', 'dq8', 'dqa1', 'dq2', 'hla', 'ттг'}
  WTF?!?!? 8
  WTF?!?!? 8
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3d12729b20>}
Check after fit:
Skipping background topic: background_1.
topic_0
  WTF: {'10'} {'вич'}
topic_1
  WTF: {'quote', 'детей', 'часто', 'например'} {'dsm', 'начало_цитаты', 'мкб', 'аспергера'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_2
topic_3
  WTF: {'саркомы'} {'гисо'}
topic_4
topic_5
  WTF: {'склероза'} {'мдс'}
topic_6
  WTF: {'встречается', 'наследуется'} {'gm2', 'iga'}
topic_7
  WTF: {'перегородки', 'пучка', 'кровообращения', 'левой'} {'гиса', 'фп', 'ибс', 'экг'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_8
  WTF: {'ts'} {'спнка'}
topic_9
  WTF: {'кашель', 'воздуха'} {'хобл', 'блд'}
topic_10
topic_11
  WTF: {'отдела', 'лечение'} {'крона', 'срк'}
topic_12
  WTF: {'арахноидита', 'ишемического'} {'сдг', 'сак'}
topic_13
topic_14
  WTF: {'эритроцитов', 'уровня', 'кровотечений', 'вен'} {'виллебранда', 'тр', 'viii', 'гит'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_15
  WTF: {'кератоэпителин', 'кератансульфатов'} {'tgfbi', 'bcd'}
topic_16
topic_17
  WTF: {'ожирения', 'ожирением', 'энурез'} {'dsm', 'мкб', 'commentedtext'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_18
  WTF: {'анафилактического'} {'ige'}
topic_19
topic_20
topic_21
topic_22
topic_23
  WTF: {'крови', 'abl', 'химиотерапии', 'транс', 'стволовых'} {'хмл', 'опл', 'омл', 'atra', 'фаб'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_24
  WTF: {'терапии'} {'знс'}
topic_25
topic_26
  WTF: {'обычно', 'две', 'анеуплоидия', 'также', 'хромосому', 'могут', 'мужчин'} {'магенис', 'xxyy', 'xxxy', 'фабри', 'xy', 'xx', 'смит'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_27
  WTF: {'крови', 'почек', 'каждые', 'плевры', 'сосудов', 'эмфиземы', 'артерии', 'больных'} {'иэ', 'св', 'мпа', 'рейно', 'цф', 'анца', 'тэла', 'гпа'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_28
  WTF: {'случаев', 'развития'} {'альцгеймера', 'дцп'}
topic_29
  WTF: {'англ', 'экспрессии', 'клетках', 'больных'} {'хлл', 'd1', 'нхл', 'ходжкина'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_30
  WTF: {'содержание'} {'адг'}
topic_31
  WTF: {'анестезией', 'анестетика'} {'дюпюитрена', 'мортона'}
topic_32
topic_33
  WTF: {'давление', 'гипертонический', 'сосудов', 'портальной', 'больных'} {'зг', 'ара', 'иапф', 'ад', 'аг'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_34
topic_35
  WTF: {'других'} {'пвл'}
topic_36
  WTF: {'механизму', 'заболевания'} {'щж', 'аит'}
topic_37
  WTF: {'недоедания'} {'кпт'}
topic_38
topic_39
  WTF: {'паука'} {'buthidae'}
topic_40
  WTF: {'кишки', 'приона', 'прионные', 'головки', 'парапроктита'} {'prpsc', 'крейтцфельдта', 'prpc', 'prp', 'paragonimus'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_41
  WTF: {'мастоцитоз'} {'wnt3'}
topic_42
  WTF: {'головного'} {'гбн'}
topic_43
topic_44
  WTF: {'бензнидазол'} {'шагаса'}
topic_45
  WTF: {'случаев', 'моно', '50', 'артритом'} {'цог', 'b27', 'гкс', 'нпвп'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_46
  WTF: {'канала'} {'дгпж'}
topic_47
  WTF: {'нарушением', 'витаминной'} {'бад', 'b12'}
topic_48
  WTF: {'клещей'} {'trombicula'}
topic_49
  WTF: {'заеда', 'диеты', 'аглютеновой', 'заболевания', 'лакунарная', 'тонкой', 'вводят', 'заеде'} {'dq', 'людвига', 'жансуля', 'dq8', 'dqa1', 'dq2', 'hla', 'ттг'}
  WTF?!?!? 8
  WTF?!?!? 8

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3d6b657220>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3cd87c90d0>}
{'perplexity': 46264.01953125, 'coherence_20': 1.4711808731503295, 'toplen_ptw': 1.481798196676419, 'diversity_euclidean': 0.03499392861437571, 'diversity_jensenshannon': 0.7188758897131495, 'diversity_hellinger': 0.8527604026066142, 'diversity_cosine': 0.7976036665199087, 'fair_ppl_free': 6018.822265625, 'fair_ppl_fix': 42058.6484375, 'unfair_ppl_banklike': 46264.01953125}
{'num_topics': 51, 'num_common_words': 101018, 'num_model_words': 127266, 'num_bt_words': 115899, 'top_diffs': [{'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}]}
5
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
  WTF: {'период'} {'вич'}
topic_1
topic_2
  WTF: {'quote', 'аутизма', 'часто', 'например'} {'dsm', 'начало_цитаты', 'мкб', 'аспергера'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_3
topic_4
  WTF: {'могут', 'году'} {'эчб', 'мдс'}
topic_5
  WTF: {'мозга'} {'гисо'}
topic_6
  WTF: {'ребёнка'} {'спнка'}
topic_7
  WTF: {'перегородки', 'пучка', 'левой', 'правого'} {'гиса', 'фп', 'ибс', 'экг'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_8
  WTF: {'типа', 'типу'} {'gm2', 'iga'}
topic_9
topic_10
  WTF: {'кашель', 'воздуха'} {'хобл', 'блд'}
topic_11
  WTF: {'является', 'язвенной'} {'крона', 'срк'}
topic_12
topic_13
  WTF: {'эритроцитов', 'уровня', 'вен'} {'виллебранда', 'viii', 'гит'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_14
  WTF: {'лимфома', 'миелоидного', 'циклина'} {'опл', 'd1', 'омл'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_15
topic_16
  WTF: {'году', 'болей', 'людей', 'заболевания'} {'альцгеймера', 'туретта', 'atm', 'дцп'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_17
topic_18
  WTF: {'кератоэпителин', 'хороидеремии'} {'tgfbi', 'кератансульфатов'}
topic_19
  WTF: {'ожирения', 'ожирением', 'энурез'} {'dsm', 'мкб', 'commentedtext'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_20
  WTF: {'крови', 'жидкости', 'глюкозы', 'сознания'} {'кт', 'сдг', 'вчг', 'сак'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_21
topic_22
  WTF: {'нейросенсорная'} {'дб'}
topic_23
topic_24
  WTF: {'эндемического'} {'т3'}
topic_25
topic_26
  WTF: {'терапии'} {'знс'}
topic_27
topic_28
  WTF: {'обычно', 'две', 'анеуплоидия', 'также', 'хромосому', 'могут', 'мужчин'} {'магенис', 'xxyy', 'xxxy', 'фабри', 'xy', 'xx', 'смит'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_29
topic_30
topic_31
  WTF: {'содержание'} {'адг'}
topic_32
  WTF: {'анестезией', 'анестетика'} {'дюпюитрена', 'мортона'}
topic_33
  WTF: {'почек', 'лёгочной', 'сосудов', 'эмболии', 'лёгких', 'грудной', 'артерии', 'эндокардита'} {'иэ', 'св', 'мпа', 'рейно', 'цф', 'анца', 'тэла', 'гпа'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_34
topic_35
  WTF: {'аутосомно', 'больных', 'костного'} {'пмл', 'пвл', 'jc'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_36
  WTF: {'давление', 'гипертонический', 'сосудов', 'портальной', 'больных'} {'зг', 'ара', 'иапф', 'ад', 'аг'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_37
  WTF: {'конъюнктивиты'} {'ige'}
topic_38
  WTF: {'мкг', 'гиперпаратиреоз', 'эндемический'} {'щж', 'псевдогиперпаратиреоз', 'аит'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_39
  WTF: {'атрофия'} {'кпт'}
topic_40
topic_41
  WTF: {'кишки', 'приона', 'прионные', 'головки', 'парапроктита'} {'prpsc', 'крейтцфельдта', 'prpc', 'prp', 'paragonimus'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_42
  WTF: {'случаев', 'пациентов', 'заражения', 'терапии'} {'пппд', 'рнк', 'аиг', 'hbv'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_43
  WTF: {'недостатка', 'животных'} {'b1', 'b12'}
topic_44
  WTF: {'саркоидоз', 'остеогенная', 'миелоидных'} {'юинга', 'амс', 'капоши'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_45
  WTF: {'случаев', 'моно', '50', 'артритом'} {'цог', 'b27', 'гкс', 'нпвп'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_46
  WTF: {'бензнидазол'} {'шагаса'}
topic_47
  WTF: {'канала'} {'дгпж'}
topic_48
  WTF: {'клещей'} {'trombicula'}
topic_49
  WTF: {'рта', 'ряд'} {'wnt3', 'бехчета'}
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3d3ebe4490>}
Check after fit:
Skipping background topic: background_1.
topic_0
  WTF: {'период'} {'вич'}
topic_1
topic_2
  WTF: {'quote', 'аутизма', 'часто', 'например'} {'dsm', 'начало_цитаты', 'мкб', 'аспергера'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_3
topic_4
  WTF: {'могут', 'году'} {'эчб', 'мдс'}
topic_5
  WTF: {'мозга'} {'гисо'}
topic_6
  WTF: {'ребёнка'} {'спнка'}
topic_7
  WTF: {'перегородки', 'пучка', 'левой', 'правого'} {'гиса', 'фп', 'ибс', 'экг'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_8
  WTF: {'типа', 'типу'} {'gm2', 'iga'}
topic_9
topic_10
  WTF: {'кашель', 'воздуха'} {'хобл', 'блд'}
topic_11
  WTF: {'является', 'язвенной'} {'крона', 'срк'}
topic_12
topic_13
  WTF: {'эритроцитов', 'уровня', 'вен'} {'виллебранда', 'viii', 'гит'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_14
  WTF: {'лимфома', 'миелоидного', 'циклина'} {'опл', 'd1', 'омл'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_15
topic_16
  WTF: {'году', 'болей', 'людей', 'заболевания'} {'альцгеймера', 'туретта', 'atm', 'дцп'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_17
topic_18
  WTF: {'кератоэпителин', 'хороидеремии'} {'tgfbi', 'кератансульфатов'}
topic_19
  WTF: {'ожирения', 'ожирением', 'энурез'} {'dsm', 'мкб', 'commentedtext'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_20
  WTF: {'крови', 'жидкости', 'глюкозы', 'сознания'} {'кт', 'сдг', 'вчг', 'сак'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_21
topic_22
  WTF: {'нейросенсорная'} {'дб'}
topic_23
topic_24
  WTF: {'эндемического'} {'т3'}
topic_25
topic_26
  WTF: {'терапии'} {'знс'}
topic_27
topic_28
  WTF: {'обычно', 'две', 'анеуплоидия', 'также', 'хромосому', 'могут', 'мужчин'} {'магенис', 'xxyy', 'xxxy', 'фабри', 'xy', 'xx', 'смит'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_29
topic_30
topic_31
  WTF: {'содержание'} {'адг'}
topic_32
  WTF: {'анестезией', 'анестетика'} {'дюпюитрена', 'мортона'}
topic_33
  WTF: {'почек', 'лёгочной', 'сосудов', 'эмболии', 'лёгких', 'грудной', 'артерии', 'эндокардита'} {'иэ', 'св', 'мпа', 'рейно', 'цф', 'анца', 'тэла', 'гпа'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_34
topic_35
  WTF: {'аутосомно', 'больных', 'костного'} {'пмл', 'пвл', 'jc'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_36
  WTF: {'давление', 'гипертонический', 'сосудов', 'портальной', 'больных'} {'зг', 'ара', 'иапф', 'ад', 'аг'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_37
  WTF: {'конъюнктивиты'} {'ige'}
topic_38
  WTF: {'мкг', 'гиперпаратиреоз', 'эндемический'} {'щж', 'псевдогиперпаратиреоз', 'аит'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_39
  WTF: {'атрофия'} {'кпт'}
topic_40
topic_41
  WTF: {'кишки', 'приона', 'прионные', 'головки', 'парапроктита'} {'prpsc', 'крейтцфельдта', 'prpc', 'prp', 'paragonimus'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_42
  WTF: {'случаев', 'пациентов', 'заражения', 'терапии'} {'пппд', 'рнк', 'аиг', 'hbv'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_43
  WTF: {'недостатка', 'животных'} {'b1', 'b12'}
topic_44
  WTF: {'саркоидоз', 'остеогенная', 'миелоидных'} {'юинга', 'амс', 'капоши'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_45
  WTF: {'случаев', 'моно', '50', 'артритом'} {'цог', 'b27', 'гкс', 'нпвп'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_46
  WTF: {'бензнидазол'} {'шагаса'}
topic_47
  WTF: {'канала'} {'дгпж'}
topic_48
  WTF: {'клещей'} {'trombicula'}
topic_49
  WTF: {'рта', 'ряд'} {'wnt3', 'бехчета'}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3fd4517c10>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3cb641bac0>}
{'perplexity': 48536.1953125, 'coherence_20': 1.456653998641672, 'toplen_ptw': 1.4908627364403246, 'diversity_euclidean': 0.03390790904584437, 'diversity_jensenshannon': 0.7145477715914985, 'diversity_hellinger': 0.8473037909678537, 'diversity_cosine': 0.7904739888367632, 'fair_ppl_free': 5863.78076171875, 'fair_ppl_fix': 44945.48828125, 'unfair_ppl_banklike': 48536.1953125}
{'num_topics': 51, 'num_common_words': 101018, 'num_model_words': 127266, 'num_bt_words': 115899, 'top_diffs': [{'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}]}
6
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
  WTF: {'болезнь'} {'вич'}
topic_1
topic_2
topic_3
  WTF: {'quote', 'аутизма', 'часто', 'например'} {'dsm', 'начало_цитаты', 'мкб', 'аспергера'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_4
  WTF: {'метастазов'} {'гисо'}
topic_5
topic_6
  WTF: {'случаев', 'это'} {'эчб', 'мдс'}
topic_7
  WTF: {'перегородки', 'пучка', 'левой', 'правого'} {'гиса', 'фп', 'ибс', 'экг'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_8
  WTF: {'ферментов', 'типа', 'типу'} {'гфф', 'gm2', 'iga'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_9
  WTF: {'ts'} {'спнка'}
topic_10
  WTF: {'лечение', 'является'} {'крона', 'срк'}
topic_11
  WTF: {'также', 'детей'} {'хобл', 'блд'}
topic_12
topic_13
  WTF: {'эритроцитов', 'кровотечений', 'вен'} {'виллебранда', 'viii', 'гит'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_14
  WTF: {'лимфома', 'миелоидного', 'циклина'} {'опл', 'd1', 'омл'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_15
  WTF: {'обмена'} {'b12'}
topic_16
topic_17
topic_18
  WTF: {'гипогликемии', 'ишемического'} {'сдг', 'сак'}
topic_19
  WTF: {'хороидеремии', 'кератансульфатов'} {'кератоэпителин', 'tgfbi'}
topic_20
topic_21
  WTF: {'ожирения', 'ожирением', 'энурез'} {'dsm', 'мкб', 'commentedtext'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_22
topic_23
topic_24
topic_25
  WTF: {'нейросенсорная'} {'дб'}
topic_26
topic_27
topic_28
  WTF: {'терапии'} {'знс'}
topic_29
topic_30
  WTF: {'обычно', 'две', 'анеуплоидия', 'также', 'хромосому', 'могут', 'мужчин'} {'магенис', 'xxyy', 'xxxy', 'фабри', 'xy', 'xx', 'смит'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_31
  WTF: {'содержание'} {'адг'}
topic_32
topic_33
  WTF: {'заболевание', 'вирус'} {'пмл', 'пвл'}
topic_34
  WTF: {'случаев', 'развития'} {'альцгеймера', 'дцп'}
topic_35
  WTF: {'гипотиреоза', 'тиреоидитом'} {'щж', 'аит'}
topic_36
topic_37
  WTF: {'давление', 'гипертонический', 'сосудов', 'портальной', 'больных'} {'зг', 'ара', 'иапф', 'ад', 'аг'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_38
  WTF: {'крови', 'выпот', 'периферической', 'мягких', 'экссудат', 'стенки', 'воздуха'} {'св', 'гк', 'мпа', 'эгпа', 'цф', 'анца', 'гпа'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_39
  WTF: {'процесс', 'тяжелые'} {'боуэна', 'wnt3'}
topic_40
  WTF: {'кишки', 'приона', 'прионные', 'головки', 'парапроктита'} {'prpsc', 'крейтцфельдта', 'prpc', 'prp', 'paragonimus'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_41
  WTF: {'уремией'} {'т4'}
topic_42
  WTF: {'саркоидоз', 'остеогенная', 'миелоидных'} {'юинга', 'амс', 'капоши'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_43
  WTF: {'10'} {'кпт'}
topic_44
  WTF: {'случаев', 'моно', '50', 'артритом'} {'цог', 'b27', 'гкс', 'нпвп'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_45
  WTF: {'бензнидазол'} {'шагаса'}
topic_46
  WTF: {'канала'} {'дгпж'}
topic_47
  WTF: {'невралгия'} {'гбн'}
topic_48
  WTF: {'клещей'} {'trombicula'}
topic_49
  WTF: {'веществ', 'гипофиза', 'извитые'} {'вельтищеву', 'беллью', 'линд'}
  WTF?!?!? 3
  WTF?!?!? 3
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3ca33a8b80>}
Check after fit:
Skipping background topic: background_1.
topic_0
  WTF: {'болезнь'} {'вич'}
topic_1
topic_2
topic_3
  WTF: {'quote', 'аутизма', 'часто', 'например'} {'dsm', 'начало_цитаты', 'мкб', 'аспергера'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_4
  WTF: {'метастазов'} {'гисо'}
topic_5
topic_6
  WTF: {'случаев', 'это'} {'эчб', 'мдс'}
topic_7
  WTF: {'перегородки', 'пучка', 'левой', 'правого'} {'гиса', 'фп', 'ибс', 'экг'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_8
  WTF: {'ферментов', 'типа', 'типу'} {'гфф', 'gm2', 'iga'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_9
  WTF: {'ts'} {'спнка'}
topic_10
  WTF: {'лечение', 'является'} {'крона', 'срк'}
topic_11
  WTF: {'также', 'детей'} {'хобл', 'блд'}
topic_12
topic_13
  WTF: {'эритроцитов', 'кровотечений', 'вен'} {'виллебранда', 'viii', 'гит'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_14
  WTF: {'лимфома', 'миелоидного', 'циклина'} {'опл', 'd1', 'омл'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_15
  WTF: {'обмена'} {'b12'}
topic_16
topic_17
topic_18
  WTF: {'гипогликемии', 'ишемического'} {'сдг', 'сак'}
topic_19
  WTF: {'хороидеремии', 'кератансульфатов'} {'кератоэпителин', 'tgfbi'}
topic_20
topic_21
  WTF: {'ожирения', 'ожирением', 'энурез'} {'dsm', 'мкб', 'commentedtext'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_22
topic_23
topic_24
topic_25
  WTF: {'нейросенсорная'} {'дб'}
topic_26
topic_27
topic_28
  WTF: {'терапии'} {'знс'}
topic_29
topic_30
  WTF: {'обычно', 'две', 'анеуплоидия', 'также', 'хромосому', 'могут', 'мужчин'} {'магенис', 'xxyy', 'xxxy', 'фабри', 'xy', 'xx', 'смит'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_31
  WTF: {'содержание'} {'адг'}
topic_32
topic_33
  WTF: {'заболевание', 'вирус'} {'пмл', 'пвл'}
topic_34
  WTF: {'случаев', 'развития'} {'альцгеймера', 'дцп'}
topic_35
  WTF: {'гипотиреоза', 'тиреоидитом'} {'щж', 'аит'}
topic_36
topic_37
  WTF: {'давление', 'гипертонический', 'сосудов', 'портальной', 'больных'} {'зг', 'ара', 'иапф', 'ад', 'аг'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_38
  WTF: {'крови', 'выпот', 'периферической', 'мягких', 'экссудат', 'стенки', 'воздуха'} {'св', 'гк', 'мпа', 'эгпа', 'цф', 'анца', 'гпа'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_39
  WTF: {'процесс', 'тяжелые'} {'боуэна', 'wnt3'}
topic_40
  WTF: {'кишки', 'приона', 'прионные', 'головки', 'парапроктита'} {'prpsc', 'крейтцфельдта', 'prpc', 'prp', 'paragonimus'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_41
  WTF: {'уремией'} {'т4'}
topic_42
  WTF: {'саркоидоз', 'остеогенная', 'миелоидных'} {'юинга', 'амс', 'капоши'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_43
  WTF: {'10'} {'кпт'}
topic_44
  WTF: {'случаев', 'моно', '50', 'артритом'} {'цог', 'b27', 'гкс', 'нпвп'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_45
  WTF: {'бензнидазол'} {'шагаса'}
topic_46
  WTF: {'канала'} {'дгпж'}
topic_47
  WTF: {'невралгия'} {'гбн'}
topic_48
  WTF: {'клещей'} {'trombicula'}
topic_49
  WTF: {'веществ', 'гипофиза', 'извитые'} {'вельтищеву', 'беллью', 'линд'}
  WTF?!?!? 3
  WTF?!?!? 3

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3cfe897190>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3cc5ee7ac0>}
{'perplexity': 48348.19921875, 'coherence_20': 1.4372463126452102, 'toplen_ptw': 1.4986079579188418, 'diversity_euclidean': 0.0331261020189922, 'diversity_jensenshannon': 0.7145863534068277, 'diversity_hellinger': 0.8475716864623042, 'diversity_cosine': 0.7903897642633846, 'fair_ppl_free': 5862.556640625, 'fair_ppl_fix': 41907.26171875, 'unfair_ppl_banklike': 48348.19921875}
{'num_topics': 51, 'num_common_words': 101018, 'num_model_words': 127266, 'num_bt_words': 115899, 'top_diffs': [{'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}]}
7
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
  WTF: {'года'} {'вич'}
topic_1
  WTF: {'quote', 'аутизма', 'часто', 'например'} {'dsm', 'начало_цитаты', 'мкб', 'аспергера'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_2
topic_3
  WTF: {'мозга'} {'гисо'}
topic_4
  WTF: {'ребёнка'} {'спнка'}
topic_5
  WTF: {'случаев', 'могут'} {'эчб', 'мдс'}
topic_6
  WTF: {'встречается', 'наследуется'} {'gm2', 'iga'}
topic_7
  WTF: {'перегородки', 'пучка', 'кровообращения', 'левой'} {'гиса', 'фп', 'ибс', 'экг'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_8
topic_9
  WTF: {'болезни', 'больных'} {'крона', 'срк'}
topic_10
  WTF: {'также', 'воздуха'} {'хобл', 'блд'}
topic_11
  WTF: {'синдрома', 'отмены', 'заболевания'} {'альцгеймера', 'знс', 'дцп'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_12
  WTF: {'лимфома', 'миелоидного', 'циклина'} {'опл', 'd1', 'омл'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_13
  WTF: {'эритроцитов', 'уровня', 'кровотечений'} {'виллебранда', 'viii', 'гит'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_14
topic_15
topic_16
  WTF: {'хороидеремии', 'кератансульфатов'} {'кератоэпителин', 'tgfbi'}
topic_17
topic_18
topic_19
  WTF: {'ожирения', 'ожирением', 'энурез'} {'dsm', 'мкб', 'commentedtext'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_20
  WTF: {'нейросенсорная'} {'дб'}
topic_21
topic_22
topic_23
topic_24
topic_25
topic_26
  WTF: {'обычно', 'две', 'анеуплоидия', 'также', 'хромосому', 'могут', 'мужчин'} {'магенис', 'xxyy', 'xxxy', 'фабри', 'xy', 'xx', 'смит'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_27
  WTF: {'пластины', 'фаланг'} {'дюпюитрена', 'мортона'}
topic_28
  WTF: {'трубочек'} {'адг'}
topic_29
  WTF: {'артерий', 'кровотока', 'окклюзии', 'давление'} {'кт', 'сдг', 'вчг', 'сак'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_30
  WTF: {'кифосколиоз'} {'шморля'}
topic_31
  WTF: {'пациентом'} {'к05'}
topic_32
  WTF: {'содержании'} {'b12'}
topic_33
  WTF: {'кисты'} {'пвл'}
topic_34
topic_35
topic_36
  WTF: {'системы', 'гиперкортицизм'} {'щж', 'аит'}
topic_37
  WTF: {'давление', 'гипертонический', 'сосудов', 'портальной', 'больных'} {'зг', 'ара', 'иапф', 'ад', 'аг'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_38
  WTF: {'атрофия'} {'кпт'}
topic_39
  WTF: {'кишки', 'приона', 'прионные', 'головки', 'парапроктита'} {'prpsc', 'крейтцфельдта', 'prpc', 'prp', 'paragonimus'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_40
  WTF: {'саркоидоз', 'остеогенная', 'миелоидных'} {'юинга', 'амс', 'капоши'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_41
  WTF: {'болезни', 'реактивный', 'псориатического'} {'цог', 'b27', 'нпвп'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_42
  WTF: {'мастоцитоз'} {'wnt3'}
topic_43
topic_44
  WTF: {'клещей'} {'trombicula'}
topic_45
  WTF: {'невралгия'} {'гбн'}
topic_46
  WTF: {'канала'} {'дгпж'}
topic_47
  WTF: {'бензнидазол'} {'шагаса'}
topic_48
  WTF: {'веществ', 'гипофиза', 'извитые'} {'вельтищеву', 'беллью', 'линд'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_49
  WTF: {'крови', 'органа', 'эмболия', 'биопсии', 'лейкоцитов', 'свойственно', 'васкулита', 'пр', 'больных', 'тромбоцитов'} {'гн', 'св', 'гк', 'мпа', 'эгпа', 'аст', 'алт', 'цф', 'анца', 'гпа'}
  WTF?!?!? 10
  WTF?!?!? 10
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3c7bebb940>}
Check after fit:
Skipping background topic: background_1.
topic_0
  WTF: {'года'} {'вич'}
topic_1
  WTF: {'quote', 'аутизма', 'часто', 'например'} {'dsm', 'начало_цитаты', 'мкб', 'аспергера'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_2
topic_3
  WTF: {'мозга'} {'гисо'}
topic_4
  WTF: {'ребёнка'} {'спнка'}
topic_5
  WTF: {'случаев', 'могут'} {'эчб', 'мдс'}
topic_6
  WTF: {'встречается', 'наследуется'} {'gm2', 'iga'}
topic_7
  WTF: {'перегородки', 'пучка', 'кровообращения', 'левой'} {'гиса', 'фп', 'ибс', 'экг'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_8
topic_9
  WTF: {'болезни', 'больных'} {'крона', 'срк'}
topic_10
  WTF: {'также', 'воздуха'} {'хобл', 'блд'}
topic_11
  WTF: {'синдрома', 'отмены', 'заболевания'} {'альцгеймера', 'знс', 'дцп'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_12
  WTF: {'лимфома', 'миелоидного', 'циклина'} {'опл', 'd1', 'омл'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_13
  WTF: {'эритроцитов', 'уровня', 'кровотечений'} {'виллебранда', 'viii', 'гит'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_14
topic_15
topic_16
  WTF: {'хороидеремии', 'кератансульфатов'} {'кератоэпителин', 'tgfbi'}
topic_17
topic_18
topic_19
  WTF: {'ожирения', 'ожирением', 'энурез'} {'dsm', 'мкб', 'commentedtext'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_20
  WTF: {'нейросенсорная'} {'дб'}
topic_21
topic_22
topic_23
topic_24
topic_25
topic_26
  WTF: {'обычно', 'две', 'анеуплоидия', 'также', 'хромосому', 'могут', 'мужчин'} {'магенис', 'xxyy', 'xxxy', 'фабри', 'xy', 'xx', 'смит'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_27
  WTF: {'пластины', 'фаланг'} {'дюпюитрена', 'мортона'}
topic_28
  WTF: {'трубочек'} {'адг'}
topic_29
  WTF: {'артерий', 'кровотока', 'окклюзии', 'давление'} {'кт', 'сдг', 'вчг', 'сак'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_30
  WTF: {'кифосколиоз'} {'шморля'}
topic_31
  WTF: {'пациентом'} {'к05'}
topic_32
  WTF: {'содержании'} {'b12'}
topic_33
  WTF: {'кисты'} {'пвл'}
topic_34
topic_35
topic_36
  WTF: {'системы', 'гиперкортицизм'} {'щж', 'аит'}
topic_37
  WTF: {'давление', 'гипертонический', 'сосудов', 'портальной', 'больных'} {'зг', 'ара', 'иапф', 'ад', 'аг'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_38
  WTF: {'атрофия'} {'кпт'}
topic_39
  WTF: {'кишки', 'приона', 'прионные', 'головки', 'парапроктита'} {'prpsc', 'крейтцфельдта', 'prpc', 'prp', 'paragonimus'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_40
  WTF: {'саркоидоз', 'остеогенная', 'миелоидных'} {'юинга', 'амс', 'капоши'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_41
  WTF: {'болезни', 'реактивный', 'псориатического'} {'цог', 'b27', 'нпвп'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_42
  WTF: {'мастоцитоз'} {'wnt3'}
topic_43
topic_44
  WTF: {'клещей'} {'trombicula'}
topic_45
  WTF: {'невралгия'} {'гбн'}
topic_46
  WTF: {'канала'} {'дгпж'}
topic_47
  WTF: {'бензнидазол'} {'шагаса'}
topic_48
  WTF: {'веществ', 'гипофиза', 'извитые'} {'вельтищеву', 'беллью', 'линд'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_49
  WTF: {'крови', 'органа', 'эмболия', 'биопсии', 'лейкоцитов', 'свойственно', 'васкулита', 'пр', 'больных', 'тромбоцитов'} {'гн', 'св', 'гк', 'мпа', 'эгпа', 'аст', 'алт', 'цф', 'анца', 'гпа'}
  WTF?!?!? 10
  WTF?!?!? 10

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3fa93f43d0>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3c8f8c68b0>}
{'perplexity': 45962.10546875, 'coherence_20': 1.463173119077526, 'toplen_ptw': 1.477275179725883, 'diversity_euclidean': 0.03432510623042221, 'diversity_jensenshannon': 0.718736751626291, 'diversity_hellinger': 0.8526844191780091, 'diversity_cosine': 0.7981652959488876, 'fair_ppl_free': 6052.296875, 'fair_ppl_fix': 41800.07421875, 'unfair_ppl_banklike': 45962.10546875}
{'num_topics': 51, 'num_common_words': 101018, 'num_model_words': 127266, 'num_bt_words': 115899, 'top_diffs': [{'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}]}
8
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
  WTF: {'quote', 'аутизма', 'часто', 'например'} {'dsm', 'начало_цитаты', 'мкб', 'аспергера'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_3
topic_4
  WTF: {'англ', 'склероза'} {'iga', 'мдс'}
topic_5
  WTF: {'мозга'} {'гисо'}
topic_6
topic_7
  WTF: {'перегородки', 'пучка', 'левой', 'сердце'} {'гиса', 'фп', 'ибс', 'экг'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_8
  WTF: {'ts'} {'спнка'}
topic_9
  WTF: {'гепатитом', 'период'} {'hsv', 'вич'}
topic_10
  WTF: {'также', 'детей'} {'хобл', 'блд'}
topic_11
  WTF: {'пищеводного', 'отдела'} {'крона', 'срк'}
topic_12
topic_13
  WTF: {'уровня', 'кровотечений', 'вен'} {'виллебранда', 'viii', 'гит'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_14
  WTF: {'лимфома', 'миелоидного', 'циклина'} {'опл', 'd1', 'омл'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_15
topic_16
  WTF: {'черепа', 'внутричерепной'} {'сдг', 'сак'}
topic_17
  WTF: {'деменции', 'эпилепсией', 'дистония'} {'альцгеймера', 'знс', 'дцп'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_18
topic_19
  WTF: {'ожирения', 'ожирением', 'энурез'} {'dsm', 'мкб', 'commentedtext'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_20
topic_21
  WTF: {'нейросенсорная'} {'дб'}
topic_22
topic_23
topic_24
topic_25
topic_26
  WTF: {'жировая'} {'т3'}
topic_27
topic_28
topic_29
  WTF: {'обычно', 'две', 'анеуплоидия', 'также', 'хромосому', 'могут', 'мужчин'} {'магенис', 'xxyy', 'xxxy', 'фабри', 'xy', 'xx', 'смит'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_30
  WTF: {'гена', 'объединяемых', 'кодирующего'} {'p450', 'вгкн', 'vldlr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_31
  WTF: {'содержание'} {'адг'}
topic_32
  WTF: {'анестезией', 'анестетика'} {'дюпюитрена', 'мортона'}
topic_33
  WTF: {'сирингомиелия'} {'шморля'}
topic_34
  WTF: {'организма', 'эндемический', 'гиперальдостеронизм'} {'иценко', 'псевдогиперпаратиреоз', 'аит'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_35
topic_36
  WTF: {'содержании'} {'b12'}
topic_37
  WTF: {'заболевания', 'развивается'} {'олб', 'wnt3'}
topic_38
  WTF: {'других'} {'пвл'}
topic_39
  WTF: {'давление', 'гипертонический', 'сосудов', 'портальной', 'больных'} {'зг', 'ара', 'иапф', 'ад', 'аг'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_40
  WTF: {'эмболия', 'доказательности', 'геморрагическими', 'вен', 'гранулематоз', 'трахеи', 'кг', 'артерии'} {'св', 'мпа', 'эгпа', 'вегенера', 'цф', 'анца', 'тэла', 'гпа'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_41
topic_42
  WTF: {'кишки', 'приона', 'прионные', 'головки', 'парапроктита'} {'prpsc', 'крейтцфельдта', 'prpc', 'prp', 'paragonimus'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_43
  WTF: {'саркоидоз', 'остеогенная', 'миелоидных'} {'юинга', 'амс', 'капоши'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_44
  WTF: {'10'} {'кпт'}
topic_45
  WTF: {'канала'} {'дгпж'}
topic_46
  WTF: {'случаев', 'моно', '50', 'артритом'} {'цог', 'b27', 'гкс', 'нпвп'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_47
  WTF: {'бензнидазол'} {'шагаса'}
topic_48
  WTF: {'клещей'} {'trombicula'}
topic_49
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3c7beb11c0>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
  WTF: {'quote', 'аутизма', 'часто', 'например'} {'dsm', 'начало_цитаты', 'мкб', 'аспергера'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_3
topic_4
  WTF: {'англ', 'склероза'} {'iga', 'мдс'}
topic_5
  WTF: {'мозга'} {'гисо'}
topic_6
topic_7
  WTF: {'перегородки', 'пучка', 'левой', 'сердце'} {'гиса', 'фп', 'ибс', 'экг'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_8
  WTF: {'ts'} {'спнка'}
topic_9
  WTF: {'гепатитом', 'период'} {'hsv', 'вич'}
topic_10
  WTF: {'также', 'детей'} {'хобл', 'блд'}
topic_11
  WTF: {'пищеводного', 'отдела'} {'крона', 'срк'}
topic_12
topic_13
  WTF: {'уровня', 'кровотечений', 'вен'} {'виллебранда', 'viii', 'гит'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_14
  WTF: {'лимфома', 'миелоидного', 'циклина'} {'опл', 'd1', 'омл'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_15
topic_16
  WTF: {'черепа', 'внутричерепной'} {'сдг', 'сак'}
topic_17
  WTF: {'деменции', 'эпилепсией', 'дистония'} {'альцгеймера', 'знс', 'дцп'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_18
topic_19
  WTF: {'ожирения', 'ожирением', 'энурез'} {'dsm', 'мкб', 'commentedtext'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_20
topic_21
  WTF: {'нейросенсорная'} {'дб'}
topic_22
topic_23
topic_24
topic_25
topic_26
  WTF: {'жировая'} {'т3'}
topic_27
topic_28
topic_29
  WTF: {'обычно', 'две', 'анеуплоидия', 'также', 'хромосому', 'могут', 'мужчин'} {'магенис', 'xxyy', 'xxxy', 'фабри', 'xy', 'xx', 'смит'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_30
  WTF: {'гена', 'объединяемых', 'кодирующего'} {'p450', 'вгкн', 'vldlr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_31
  WTF: {'содержание'} {'адг'}
topic_32
  WTF: {'анестезией', 'анестетика'} {'дюпюитрена', 'мортона'}
topic_33
  WTF: {'сирингомиелия'} {'шморля'}
topic_34
  WTF: {'организма', 'эндемический', 'гиперальдостеронизм'} {'иценко', 'псевдогиперпаратиреоз', 'аит'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_35
topic_36
  WTF: {'содержании'} {'b12'}
topic_37
  WTF: {'заболевания', 'развивается'} {'олб', 'wnt3'}
topic_38
  WTF: {'других'} {'пвл'}
topic_39
  WTF: {'давление', 'гипертонический', 'сосудов', 'портальной', 'больных'} {'зг', 'ара', 'иапф', 'ад', 'аг'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_40
  WTF: {'эмболия', 'доказательности', 'геморрагическими', 'вен', 'гранулематоз', 'трахеи', 'кг', 'артерии'} {'св', 'мпа', 'эгпа', 'вегенера', 'цф', 'анца', 'тэла', 'гпа'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_41
topic_42
  WTF: {'кишки', 'приона', 'прионные', 'головки', 'парапроктита'} {'prpsc', 'крейтцфельдта', 'prpc', 'prp', 'paragonimus'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_43
  WTF: {'саркоидоз', 'остеогенная', 'миелоидных'} {'юинга', 'амс', 'капоши'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_44
  WTF: {'10'} {'кпт'}
topic_45
  WTF: {'канала'} {'дгпж'}
topic_46
  WTF: {'случаев', 'моно', '50', 'артритом'} {'цог', 'b27', 'гкс', 'нпвп'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_47
  WTF: {'бензнидазол'} {'шагаса'}
topic_48
  WTF: {'клещей'} {'trombicula'}
topic_49

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3c5cc2a2e0>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3c11db0e20>}
{'perplexity': 51178.00390625, 'coherence_20': 1.458419840924499, 'toplen_ptw': 1.5084193354492141, 'diversity_euclidean': 0.03250212009071356, 'diversity_jensenshannon': 0.7129515615699684, 'diversity_hellinger': 0.845468466783309, 'diversity_cosine': 0.7877528679894632, 'fair_ppl_free': 5841.56201171875, 'fair_ppl_fix': 44627.93359375, 'unfair_ppl_banklike': 51178.00390625}
{'num_topics': 51, 'num_common_words': 101018, 'num_model_words': 127266, 'num_bt_words': 115899, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}]}
9
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
  WTF: {'случаев'} {'вич'}
topic_1
topic_2
  WTF: {'quote', 'аутизма', 'часто', 'например'} {'dsm', 'начало_цитаты', 'мкб', 'аспергера'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_3
topic_4
topic_5
  WTF: {'метастазов'} {'гисо'}
topic_6
  WTF: {'артериальной', 'сердце'} {'ибс', 'экг'}
topic_7
  WTF: {'ts'} {'спнка'}
topic_8
  WTF: {'кашель', 'воздуха'} {'хобл', 'блд'}
topic_9
  WTF: {'кардии', 'гастрита'} {'крона', 'срк'}
topic_10
topic_11
  WTF: {'лимфома', 'миелоидного', 'циклина'} {'опл', 'd1', 'омл'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_12
  WTF: {'лет', 'отмены', 'заболевания', 'нейролептического'} {'туретта', 'альцгеймера', 'знс', 'дцп'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_13
  WTF: {'анемия', 'эритроцитов', 'кровотечений'} {'виллебранда', 'viii', 'гит'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_14
topic_15
topic_16
  WTF: {'хороидеремии', 'кератансульфатов'} {'кератоэпителин', 'tgfbi'}
topic_17
  WTF: {'ожирения', 'ожирением', 'энурез'} {'dsm', 'мкб', 'commentedtext'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_18
topic_19
topic_20
  WTF: {'нейросенсорная'} {'дб'}
topic_21
topic_22
topic_23
  WTF: {'обычно', 'две', 'анеуплоидия', 'также', 'хромосому', 'могут', 'мужчин'} {'магенис', 'xxyy', 'xxxy', 'фабри', 'xy', 'xx', 'смит'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_24
  WTF: {'пластины', 'фаланг'} {'дюпюитрена', 'мортона'}
topic_25
  WTF: {'заболевание', 'поликистоза', 'вещества'} {'пмл', 'дст', 'пвл'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_26
  WTF: {'лёгочной', 'легких', 'сердца', 'доказательности', 'эмболии', 'указан', 'лёгких', 'источник'} {'св', 'мпа', 'эгпа', 'рейно', 'цф', 'анца', 'тэла', 'гпа'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_27
topic_28
  WTF: {'трубочек'} {'адг'}
topic_29
topic_30
  WTF: {'черепа', 'кровотока', 'давление', 'сознания'} {'кт', 'сдг', 'вчг', 'сак'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_31
topic_32
  WTF: {'системы', 'гиперкортицизм'} {'щж', 'аит'}
topic_33
  WTF: {'недоедания'} {'кпт'}
topic_34
  WTF: {'паука'} {'buthidae'}
topic_35
topic_36
topic_37
  WTF: {'кишки', 'приона', 'прионные', 'головки', 'парапроктита'} {'prpsc', 'крейтцфельдта', 'prpc', 'prp', 'paragonimus'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_38
  WTF: {'клещей'} {'trombicula'}
topic_39
  WTF: {'других'} {'wnt3'}
topic_40
  WTF: {'саркоидоз', 'остеогенная', 'миелоидных'} {'юинга', 'амс', 'капоши'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_41
  WTF: {'холестерина'} {'жкб'}
topic_42
  WTF: {'лечения', 'женщинам', 'маммография'} {'фоп', 'дф', 'фм'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_43
  WTF: {'случаев', 'моно', '50', 'артритом'} {'цог', 'b27', 'гкс', 'нпвп'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_44
  WTF: {'снижение'} {'т4'}
topic_45
  WTF: {'нарушением', 'витаминной'} {'бад', 'b12'}
topic_46
  WTF: {'невралгия'} {'гбн'}
topic_47
  WTF: {'канала'} {'дгпж'}
topic_48
  WTF: {'бензнидазол'} {'шагаса'}
topic_49
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3befc3e970>}
Check after fit:
Skipping background topic: background_1.
topic_0
  WTF: {'случаев'} {'вич'}
topic_1
topic_2
  WTF: {'quote', 'аутизма', 'часто', 'например'} {'dsm', 'начало_цитаты', 'мкб', 'аспергера'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_3
topic_4
topic_5
  WTF: {'метастазов'} {'гисо'}
topic_6
  WTF: {'артериальной', 'сердце'} {'ибс', 'экг'}
topic_7
  WTF: {'ts'} {'спнка'}
topic_8
  WTF: {'кашель', 'воздуха'} {'хобл', 'блд'}
topic_9
  WTF: {'кардии', 'гастрита'} {'крона', 'срк'}
topic_10
topic_11
  WTF: {'лимфома', 'миелоидного', 'циклина'} {'опл', 'd1', 'омл'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_12
  WTF: {'лет', 'отмены', 'заболевания', 'нейролептического'} {'туретта', 'альцгеймера', 'знс', 'дцп'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_13
  WTF: {'анемия', 'эритроцитов', 'кровотечений'} {'виллебранда', 'viii', 'гит'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_14
topic_15
topic_16
  WTF: {'хороидеремии', 'кератансульфатов'} {'кератоэпителин', 'tgfbi'}
topic_17
  WTF: {'ожирения', 'ожирением', 'энурез'} {'dsm', 'мкб', 'commentedtext'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_18
topic_19
topic_20
  WTF: {'нейросенсорная'} {'дб'}
topic_21
topic_22
topic_23
  WTF: {'обычно', 'две', 'анеуплоидия', 'также', 'хромосому', 'могут', 'мужчин'} {'магенис', 'xxyy', 'xxxy', 'фабри', 'xy', 'xx', 'смит'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_24
  WTF: {'пластины', 'фаланг'} {'дюпюитрена', 'мортона'}
topic_25
  WTF: {'заболевание', 'поликистоза', 'вещества'} {'пмл', 'дст', 'пвл'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_26
  WTF: {'лёгочной', 'легких', 'сердца', 'доказательности', 'эмболии', 'указан', 'лёгких', 'источник'} {'св', 'мпа', 'эгпа', 'рейно', 'цф', 'анца', 'тэла', 'гпа'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_27
topic_28
  WTF: {'трубочек'} {'адг'}
topic_29
topic_30
  WTF: {'черепа', 'кровотока', 'давление', 'сознания'} {'кт', 'сдг', 'вчг', 'сак'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_31
topic_32
  WTF: {'системы', 'гиперкортицизм'} {'щж', 'аит'}
topic_33
  WTF: {'недоедания'} {'кпт'}
topic_34
  WTF: {'паука'} {'buthidae'}
topic_35
topic_36
topic_37
  WTF: {'кишки', 'приона', 'прионные', 'головки', 'парапроктита'} {'prpsc', 'крейтцфельдта', 'prpc', 'prp', 'paragonimus'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_38
  WTF: {'клещей'} {'trombicula'}
topic_39
  WTF: {'других'} {'wnt3'}
topic_40
  WTF: {'саркоидоз', 'остеогенная', 'миелоидных'} {'юинга', 'амс', 'капоши'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_41
  WTF: {'холестерина'} {'жкб'}
topic_42
  WTF: {'лечения', 'женщинам', 'маммография'} {'фоп', 'дф', 'фм'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_43
  WTF: {'случаев', 'моно', '50', 'артритом'} {'цог', 'b27', 'гкс', 'нпвп'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_44
  WTF: {'снижение'} {'т4'}
topic_45
  WTF: {'нарушением', 'витаминной'} {'бад', 'b12'}
topic_46
  WTF: {'невралгия'} {'гбн'}
topic_47
  WTF: {'канала'} {'дгпж'}
topic_48
  WTF: {'бензнидазол'} {'шагаса'}
topic_49

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3c2507e4c0>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3bc9e45ca0>}
{'perplexity': 46165.0703125, 'coherence_20': 1.5214690760651481, 'toplen_ptw': 1.483826932880753, 'diversity_euclidean': 0.03573437490078221, 'diversity_jensenshannon': 0.7234734598236563, 'diversity_hellinger': 0.8586104832144189, 'diversity_cosine': 0.8090859645771503, 'fair_ppl_free': 6119.5068359375, 'fair_ppl_fix': 42363.5, 'unfair_ppl_banklike': 46165.0703125}
{'num_topics': 51, 'num_common_words': 101018, 'num_model_words': 127266, 'num_bt_words': 115899, 'top_diffs': [{'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}]}
10
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
  WTF: {'заражения'} {'вич'}
topic_1
topic_2
  WTF: {'quote', 'аутизма', 'часто', 'например'} {'dsm', 'начало_цитаты', 'мкб', 'аспергера'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_3
topic_4
  WTF: {'мозга'} {'гисо'}
topic_5
  WTF: {'году', 'лет'} {'эчб', 'мдс'}
topic_6
  WTF: {'ферментов', 'встречается'} {'gm2', 'iga'}
topic_7
  WTF: {'перегородки', 'пучка', 'кровообращения', 'левой'} {'гиса', 'фп', 'ибс', 'экг'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_8
  WTF: {'кашель', 'воздуха'} {'хобл', 'блд'}
topic_9
topic_10
  WTF: {'пищеводного', 'pylori'} {'крона', 'срк'}
topic_11
topic_12
topic_13
  WTF: {'гемофилия', 'анемия', 'эритроцитов'} {'виллебранда', 'viii', 'гит'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_14
  WTF: {'мазохизм'} {'мкб'}
topic_15
  WTF: {'ожирения', 'ожирением', 'энурез'} {'dsm', 'мкб', 'commentedtext'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_16
  WTF: {'крови', 'глюкозы', 'сознания', 'мозжечка'} {'кт', 'сдг', 'вчг', 'сак'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_17
  WTF: {'пола', 'андрогенов', 'маскулинизации'} {'лейдига', 'слнка', 'спнка'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_18
topic_19
  WTF: {'нейросенсорная'} {'дб'}
topic_20
topic_21
topic_22
topic_23
topic_24
  WTF: {'крови', 'abl', 'химиотерапии', 'транс', 'стволовых'} {'хмл', 'опл', 'омл', 'atra', 'фаб'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_25
  WTF: {'терапии'} {'знс'}
topic_26
  WTF: {'обычно', 'две', 'анеуплоидия', 'также', 'хромосому', 'могут', 'мужчин'} {'магенис', 'xxyy', 'xxxy', 'фабри', 'xy', 'xx', 'смит'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_27
  WTF: {'анестезией', 'анестетика'} {'дюпюитрена', 'мортона'}
topic_28
  WTF: {'содержание'} {'адг'}
topic_29
  WTF: {'англ', 'экспрессии', 'клетках', 'больных'} {'хлл', 'd1', 'нхл', 'ходжкина'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_30
  WTF: {'случаев', 'развития'} {'альцгеймера', 'дцп'}
topic_31
  WTF: {'ткани', 'системной'} {'олб', 'wnt3'}
topic_32
  WTF: {'вещества', 'вируса'} {'пмл', 'пвл'}
topic_33
topic_34
topic_35
  WTF: {'содержании'} {'b12'}
topic_36
  WTF: {'системы', 'гиперкортицизм'} {'щж', 'аит'}
topic_37
  WTF: {'давление', 'гипертонический', 'сосудов', 'портальной', 'больных'} {'зг', 'ара', 'иапф', 'ад', 'аг'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_38
  WTF: {'доказательности', 'геморрагическими', 'гранулематоз', 'течение', 'васкулита', 'мг', 'трахеи', 'больных'} {'иэ', 'св', 'мпа', 'эгпа', 'цф', 'анца', 'эхокг', 'гпа'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_39
  WTF: {'паука'} {'buthidae'}
topic_40
  WTF: {'крапивницы'} {'ige'}
topic_41
topic_42
  WTF: {'кишки', 'приона', 'прионные', 'головки', 'парапроктита'} {'prpsc', 'крейтцфельдта', 'prpc', 'prp', 'paragonimus'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_43
  WTF: {'случаев', 'пациентов', 'заражения', 'терапии'} {'пппд', 'рнк', 'аиг', 'hbv'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_44
  WTF: {'атрофия'} {'кпт'}
topic_45
  WTF: {'клещей'} {'trombicula'}
topic_46
  WTF: {'саркоидоз', 'остеогенная', 'миелоидных'} {'юинга', 'амс', 'капоши'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_47
  WTF: {'бензнидазол'} {'шагаса'}
topic_48
  WTF: {'случаев', 'моно', '50', 'артритом'} {'цог', 'b27', 'гкс', 'нпвп'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_49
  WTF: {'канала'} {'дгпж'}
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3befcac340>}
Check after fit:
Skipping background topic: background_1.
topic_0
  WTF: {'заражения'} {'вич'}
topic_1
topic_2
  WTF: {'quote', 'аутизма', 'часто', 'например'} {'dsm', 'начало_цитаты', 'мкб', 'аспергера'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_3
topic_4
  WTF: {'мозга'} {'гисо'}
topic_5
  WTF: {'году', 'лет'} {'эчб', 'мдс'}
topic_6
  WTF: {'ферментов', 'встречается'} {'gm2', 'iga'}
topic_7
  WTF: {'перегородки', 'пучка', 'кровообращения', 'левой'} {'гиса', 'фп', 'ибс', 'экг'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_8
  WTF: {'кашель', 'воздуха'} {'хобл', 'блд'}
topic_9
topic_10
  WTF: {'пищеводного', 'pylori'} {'крона', 'срк'}
topic_11
topic_12
topic_13
  WTF: {'гемофилия', 'анемия', 'эритроцитов'} {'виллебранда', 'viii', 'гит'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_14
  WTF: {'мазохизм'} {'мкб'}
topic_15
  WTF: {'ожирения', 'ожирением', 'энурез'} {'dsm', 'мкб', 'commentedtext'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_16
  WTF: {'крови', 'глюкозы', 'сознания', 'мозжечка'} {'кт', 'сдг', 'вчг', 'сак'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_17
  WTF: {'пола', 'андрогенов', 'маскулинизации'} {'лейдига', 'слнка', 'спнка'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_18
topic_19
  WTF: {'нейросенсорная'} {'дб'}
topic_20
topic_21
topic_22
topic_23
topic_24
  WTF: {'крови', 'abl', 'химиотерапии', 'транс', 'стволовых'} {'хмл', 'опл', 'омл', 'atra', 'фаб'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_25
  WTF: {'терапии'} {'знс'}
topic_26
  WTF: {'обычно', 'две', 'анеуплоидия', 'также', 'хромосому', 'могут', 'мужчин'} {'магенис', 'xxyy', 'xxxy', 'фабри', 'xy', 'xx', 'смит'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_27
  WTF: {'анестезией', 'анестетика'} {'дюпюитрена', 'мортона'}
topic_28
  WTF: {'содержание'} {'адг'}
topic_29
  WTF: {'англ', 'экспрессии', 'клетках', 'больных'} {'хлл', 'd1', 'нхл', 'ходжкина'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_30
  WTF: {'случаев', 'развития'} {'альцгеймера', 'дцп'}
topic_31
  WTF: {'ткани', 'системной'} {'олб', 'wnt3'}
topic_32
  WTF: {'вещества', 'вируса'} {'пмл', 'пвл'}
topic_33
topic_34
topic_35
  WTF: {'содержании'} {'b12'}
topic_36
  WTF: {'системы', 'гиперкортицизм'} {'щж', 'аит'}
topic_37
  WTF: {'давление', 'гипертонический', 'сосудов', 'портальной', 'больных'} {'зг', 'ара', 'иапф', 'ад', 'аг'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_38
  WTF: {'доказательности', 'геморрагическими', 'гранулематоз', 'течение', 'васкулита', 'мг', 'трахеи', 'больных'} {'иэ', 'св', 'мпа', 'эгпа', 'цф', 'анца', 'эхокг', 'гпа'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_39
  WTF: {'паука'} {'buthidae'}
topic_40
  WTF: {'крапивницы'} {'ige'}
topic_41
topic_42
  WTF: {'кишки', 'приона', 'прионные', 'головки', 'парапроктита'} {'prpsc', 'крейтцфельдта', 'prpc', 'prp', 'paragonimus'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_43
  WTF: {'случаев', 'пациентов', 'заражения', 'терапии'} {'пппд', 'рнк', 'аиг', 'hbv'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_44
  WTF: {'атрофия'} {'кпт'}
topic_45
  WTF: {'клещей'} {'trombicula'}
topic_46
  WTF: {'саркоидоз', 'остеогенная', 'миелоидных'} {'юинга', 'амс', 'капоши'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_47
  WTF: {'бензнидазол'} {'шагаса'}
topic_48
  WTF: {'случаев', 'моно', '50', 'артритом'} {'цог', 'b27', 'гкс', 'нпвп'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_49
  WTF: {'канала'} {'дгпж'}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3d65f78730>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3d53e06fd0>}
{'perplexity': 46158.765625, 'coherence_20': 1.5078295754758286, 'toplen_ptw': 1.4753746361278077, 'diversity_euclidean': 0.03261664201382367, 'diversity_jensenshannon': 0.7131875083056215, 'diversity_hellinger': 0.8462647518834571, 'diversity_cosine': 0.7923929101034104, 'fair_ppl_free': 5973.26171875, 'fair_ppl_fix': 41962.43359375, 'unfair_ppl_banklike': 46158.765625}
{'num_topics': 51, 'num_common_words': 101018, 'num_model_words': 127266, 'num_bt_words': 115899, 'top_diffs': [{'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}]}
11
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
  WTF: {'является'} {'вич'}
topic_1
  WTF: {'quote', 'аутизма', 'часто', 'например'} {'dsm', 'начало_цитаты', 'мкб', 'аспергера'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_2
topic_3
topic_4
  WTF: {'саркомы'} {'гисо'}
topic_5
  WTF: {'синдромом', 'гена', 'году'} {'ахс', 'мдс', 'эчб'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_6
  WTF: {'перегородки', 'пучка', 'кровообращения', 'левой'} {'гиса', 'фп', 'ибс', 'экг'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_7
  WTF: {'типа', 'типу'} {'gm2', 'iga'}
topic_8
topic_9
  WTF: {'ts'} {'спнка'}
topic_10
  WTF: {'также', 'детей'} {'хобл', 'блд'}
topic_11
topic_12
topic_13
  WTF: {'пищеводного', 'pylori'} {'крона', 'срк'}
topic_14
topic_15
  WTF: {'уровня', 'кровотечений', 'вен'} {'виллебранда', 'viii', 'гит'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_16
topic_17
  WTF: {'хороидеремии', 'кератансульфатов'} {'кератоэпителин', 'tgfbi'}
topic_18
  WTF: {'случаев', 'внутричерепной', 'заболевания'} {'сдг', 'вчг', 'сак'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_19
  WTF: {'ожирения', 'ожирением', 'энурез'} {'dsm', 'мкб', 'commentedtext'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_20
topic_21
  WTF: {'недостаточности'} {'b12'}
topic_22
  WTF: {'нейросенсорная'} {'дб'}
topic_23
topic_24
topic_25
topic_26
  WTF: {'могут'} {'знс'}
topic_27
topic_28
  WTF: {'крови', 'abl', 'химиотерапии', 'транс', 'стволовых'} {'хмл', 'опл', 'омл', 'atra', 'фаб'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_29
  WTF: {'обычно', 'две', 'анеуплоидия', 'также', 'хромосому', 'могут', 'мужчин'} {'магенис', 'xxyy', 'xxxy', 'фабри', 'xy', 'xx', 'смит'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_30
  WTF: {'англ', 'экспрессии', 'клетках', 'больных'} {'хлл', 'd1', 'нхл', 'ходжкина'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_31
  WTF: {'анестезией', 'анестетика'} {'дюпюитрена', 'мортона'}
topic_32
  WTF: {'трубочек'} {'адг'}
topic_33
  WTF: {'заболевание', 'вирус'} {'пмл', 'пвл'}
topic_34
topic_35
  WTF: {'организма', 'эндемический', 'гиперальдостеронизм'} {'иценко', 'псевдогиперпаратиреоз', 'аит'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_36
  WTF: {'конъюнктивиты'} {'ige'}
topic_37
  WTF: {'правил'} {'к05'}
topic_38
  WTF: {'паука'} {'buthidae'}
topic_39
  WTF: {'движений', 'нарушений'} {'альцгеймера', 'дцп'}
topic_40
  WTF: {'криза', 'сосудов', 'портальной', 'больных'} {'иапф', 'ад', 'ара', 'аг'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_41
  WTF: {'кишки', 'приона', 'прионные', 'головки', 'парапроктита'} {'prpsc', 'крейтцфельдта', 'prpc', 'prp', 'paragonimus'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_42
topic_43
  WTF: {'коже', 'зубов'} {'боуэна', 'wnt3'}
topic_44
  WTF: {'крови', 'выпот', '109', 'поражения', 'характеризуется', 'язвенно', 'эмболии', 'экссудат', 'источник'} {'св', 'гк', 'мпа', 'эгпа', 'аст', 'вегенера', 'цф', 'анца', 'гпа'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_45
  WTF: {'бензнидазол'} {'шагаса'}
topic_46
  WTF: {'случаев', 'моно', '50', 'артритом'} {'цог', 'b27', 'гкс', 'нпвп'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_47
  WTF: {'веществ', 'белков'} {'dsm', 'кпт'}
topic_48
  WTF: {'клещей'} {'trombicula'}
topic_49
  WTF: {'канала'} {'дгпж'}
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3b85876430>}
Check after fit:
Skipping background topic: background_1.
topic_0
  WTF: {'является'} {'вич'}
topic_1
  WTF: {'quote', 'аутизма', 'часто', 'например'} {'dsm', 'начало_цитаты', 'мкб', 'аспергера'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_2
topic_3
topic_4
  WTF: {'саркомы'} {'гисо'}
topic_5
  WTF: {'синдромом', 'гена', 'году'} {'ахс', 'мдс', 'эчб'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_6
  WTF: {'перегородки', 'пучка', 'кровообращения', 'левой'} {'гиса', 'фп', 'ибс', 'экг'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_7
  WTF: {'типа', 'типу'} {'gm2', 'iga'}
topic_8
topic_9
  WTF: {'ts'} {'спнка'}
topic_10
  WTF: {'также', 'детей'} {'хобл', 'блд'}
topic_11
topic_12
topic_13
  WTF: {'пищеводного', 'pylori'} {'крона', 'срк'}
topic_14
topic_15
  WTF: {'уровня', 'кровотечений', 'вен'} {'виллебранда', 'viii', 'гит'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_16
topic_17
  WTF: {'хороидеремии', 'кератансульфатов'} {'кератоэпителин', 'tgfbi'}
topic_18
  WTF: {'случаев', 'внутричерепной', 'заболевания'} {'сдг', 'вчг', 'сак'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_19
  WTF: {'ожирения', 'ожирением', 'энурез'} {'dsm', 'мкб', 'commentedtext'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_20
topic_21
  WTF: {'недостаточности'} {'b12'}
topic_22
  WTF: {'нейросенсорная'} {'дб'}
topic_23
topic_24
topic_25
topic_26
  WTF: {'могут'} {'знс'}
topic_27
topic_28
  WTF: {'крови', 'abl', 'химиотерапии', 'транс', 'стволовых'} {'хмл', 'опл', 'омл', 'atra', 'фаб'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_29
  WTF: {'обычно', 'две', 'анеуплоидия', 'также', 'хромосому', 'могут', 'мужчин'} {'магенис', 'xxyy', 'xxxy', 'фабри', 'xy', 'xx', 'смит'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_30
  WTF: {'англ', 'экспрессии', 'клетках', 'больных'} {'хлл', 'd1', 'нхл', 'ходжкина'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_31
  WTF: {'анестезией', 'анестетика'} {'дюпюитрена', 'мортона'}
topic_32
  WTF: {'трубочек'} {'адг'}
topic_33
  WTF: {'заболевание', 'вирус'} {'пмл', 'пвл'}
topic_34
topic_35
  WTF: {'организма', 'эндемический', 'гиперальдостеронизм'} {'иценко', 'псевдогиперпаратиреоз', 'аит'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_36
  WTF: {'конъюнктивиты'} {'ige'}
topic_37
  WTF: {'правил'} {'к05'}
topic_38
  WTF: {'паука'} {'buthidae'}
topic_39
  WTF: {'движений', 'нарушений'} {'альцгеймера', 'дцп'}
topic_40
  WTF: {'криза', 'сосудов', 'портальной', 'больных'} {'иапф', 'ад', 'ара', 'аг'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_41
  WTF: {'кишки', 'приона', 'прионные', 'головки', 'парапроктита'} {'prpsc', 'крейтцфельдта', 'prpc', 'prp', 'paragonimus'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_42
topic_43
  WTF: {'коже', 'зубов'} {'боуэна', 'wnt3'}
topic_44
  WTF: {'крови', 'выпот', '109', 'поражения', 'характеризуется', 'язвенно', 'эмболии', 'экссудат', 'источник'} {'св', 'гк', 'мпа', 'эгпа', 'аст', 'вегенера', 'цф', 'анца', 'гпа'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_45
  WTF: {'бензнидазол'} {'шагаса'}
topic_46
  WTF: {'случаев', 'моно', '50', 'артритом'} {'цог', 'b27', 'гкс', 'нпвп'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_47
  WTF: {'веществ', 'белков'} {'dsm', 'кпт'}
topic_48
  WTF: {'клещей'} {'trombicula'}
topic_49
  WTF: {'канала'} {'дгпж'}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3bbacc2520>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3c7b9b49d0>}
{'perplexity': 50156.8203125, 'coherence_20': 1.4501847841297792, 'toplen_ptw': 1.508046765304777, 'diversity_euclidean': 0.0331048467110409, 'diversity_jensenshannon': 0.7141201981086763, 'diversity_hellinger': 0.8470501706319522, 'diversity_cosine': 0.7904945255667183, 'fair_ppl_free': 5877.390625, 'fair_ppl_fix': 43097.31640625, 'unfair_ppl_banklike': 50156.8203125}
{'num_topics': 51, 'num_common_words': 101018, 'num_model_words': 127266, 'num_bt_words': 115899, 'top_diffs': [{'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}]}
12
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
  WTF: {'quote', 'аутизма', 'часто', 'например'} {'dsm', 'начало_цитаты', 'мкб', 'аспергера'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_2
topic_3
  WTF: {'болезнь'} {'вич'}
topic_4
  WTF: {'является'} {'спнка'}
topic_5
  WTF: {'случаев', 'могут'} {'эчб', 'мдс'}
topic_6
  WTF: {'желудка'} {'гисо'}
topic_7
  WTF: {'ферментов', 'встречается'} {'gm2', 'iga'}
topic_8
  WTF: {'перегородки', 'пучка', 'левой', 'сердце'} {'гиса', 'фп', 'ибс', 'экг'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_9
topic_10
  WTF: {'кашель', 'воздуха'} {'хобл', 'блд'}
topic_11
  WTF: {'гастрита', 'язвенной'} {'крона', 'срк'}
topic_12
  WTF: {'деформации'} {'дюпюитрена'}
topic_13
  WTF: {'эритроцитов', 'уровня', 'кровотечений', 'вен'} {'виллебранда', 'тр', 'viii', 'гит'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_14
  WTF: {'гипогликемии', 'ишемического'} {'сдг', 'сак'}
topic_15
topic_16
  WTF: {'тип'} {'tgfbi'}
topic_17
topic_18
  WTF: {'ожирения', 'ожирением', 'энурез'} {'dsm', 'мкб', 'commentedtext'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_19
topic_20
topic_21
topic_22
  WTF: {'нейросенсорная'} {'дб'}
topic_23
topic_24
topic_25
  WTF: {'терапии'} {'знс'}
topic_26
  WTF: {'крови', 'abl', 'химиотерапии', 'транс', 'стволовых'} {'хмл', 'опл', 'омл', 'atra', 'фаб'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_27
topic_28
  WTF: {'спорадический', 'заболевания'} {'псевдогиперпаратиреоз', 'аит'}
topic_29
  WTF: {'обычно', 'две', 'анеуплоидия', 'также', 'хромосому', 'могут', 'мужчин'} {'магенис', 'xxyy', 'xxxy', 'фабри', 'xy', 'xx', 'смит'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_30
  WTF: {'движений', 'дистонии'} {'альцгеймера', 'дцп'}
topic_31
  WTF: {'англ', 'экспрессии', 'клетках', 'больных'} {'хлл', 'd1', 'нхл', 'ходжкина'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_32
  WTF: {'вещества', 'вируса'} {'пмл', 'пвл'}
topic_33
  WTF: {'содержание'} {'адг'}
topic_34
  WTF: {'паратгормона'} {'b12'}
topic_35
topic_36
topic_37
  WTF: {'фиброматоз', 'тяжести'} {'олб', 'wnt3'}
topic_38
  WTF: {'почек', 'спонтанной', 'характеризуется', 'сердца', 'эмболии', 'течение', 'трахеи', 'подкожная'} {'иэ', 'св', 'мпа', 'эгпа', 'цф', 'анца', 'эхокг', 'гпа'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_39
  WTF: {'сосудов', 'гипертонический', 'портальной', 'больных'} {'иапф', 'ад', 'ара', 'аг'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_40
  WTF: {'кишки', 'приона', 'прионные', 'головки', 'парапроктита'} {'prpsc', 'крейтцфельдта', 'prpc', 'prp', 'paragonimus'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_41
  WTF: {'саркоидоз', 'остеогенная', 'миелоидных'} {'юинга', 'амс', 'капоши'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_42
  WTF: {'10'} {'кпт'}
topic_43
topic_44
  WTF: {'канала'} {'дгпж'}
topic_45
  WTF: {'случаев', 'моно', '50', 'артритом'} {'цог', 'b27', 'гкс', 'нпвп'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_46
  WTF: {'бензнидазол'} {'шагаса'}
topic_47
  WTF: {'невралгия'} {'гбн'}
topic_48
  WTF: {'клещей'} {'trombicula'}
topic_49
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3b50648490>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
  WTF: {'quote', 'аутизма', 'часто', 'например'} {'dsm', 'начало_цитаты', 'мкб', 'аспергера'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_2
topic_3
  WTF: {'болезнь'} {'вич'}
topic_4
  WTF: {'является'} {'спнка'}
topic_5
  WTF: {'случаев', 'могут'} {'эчб', 'мдс'}
topic_6
  WTF: {'желудка'} {'гисо'}
topic_7
  WTF: {'ферментов', 'встречается'} {'gm2', 'iga'}
topic_8
  WTF: {'перегородки', 'пучка', 'левой', 'сердце'} {'гиса', 'фп', 'ибс', 'экг'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_9
topic_10
  WTF: {'кашель', 'воздуха'} {'хобл', 'блд'}
topic_11
  WTF: {'гастрита', 'язвенной'} {'крона', 'срк'}
topic_12
  WTF: {'деформации'} {'дюпюитрена'}
topic_13
  WTF: {'эритроцитов', 'уровня', 'кровотечений', 'вен'} {'виллебранда', 'тр', 'viii', 'гит'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_14
  WTF: {'гипогликемии', 'ишемического'} {'сдг', 'сак'}
topic_15
topic_16
  WTF: {'тип'} {'tgfbi'}
topic_17
topic_18
  WTF: {'ожирения', 'ожирением', 'энурез'} {'dsm', 'мкб', 'commentedtext'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_19
topic_20
topic_21
topic_22
  WTF: {'нейросенсорная'} {'дб'}
topic_23
topic_24
topic_25
  WTF: {'терапии'} {'знс'}
topic_26
  WTF: {'крови', 'abl', 'химиотерапии', 'транс', 'стволовых'} {'хмл', 'опл', 'омл', 'atra', 'фаб'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_27
topic_28
  WTF: {'спорадический', 'заболевания'} {'псевдогиперпаратиреоз', 'аит'}
topic_29
  WTF: {'обычно', 'две', 'анеуплоидия', 'также', 'хромосому', 'могут', 'мужчин'} {'магенис', 'xxyy', 'xxxy', 'фабри', 'xy', 'xx', 'смит'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_30
  WTF: {'движений', 'дистонии'} {'альцгеймера', 'дцп'}
topic_31
  WTF: {'англ', 'экспрессии', 'клетках', 'больных'} {'хлл', 'd1', 'нхл', 'ходжкина'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_32
  WTF: {'вещества', 'вируса'} {'пмл', 'пвл'}
topic_33
  WTF: {'содержание'} {'адг'}
topic_34
  WTF: {'паратгормона'} {'b12'}
topic_35
topic_36
topic_37
  WTF: {'фиброматоз', 'тяжести'} {'олб', 'wnt3'}
topic_38
  WTF: {'почек', 'спонтанной', 'характеризуется', 'сердца', 'эмболии', 'течение', 'трахеи', 'подкожная'} {'иэ', 'св', 'мпа', 'эгпа', 'цф', 'анца', 'эхокг', 'гпа'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_39
  WTF: {'сосудов', 'гипертонический', 'портальной', 'больных'} {'иапф', 'ад', 'ара', 'аг'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_40
  WTF: {'кишки', 'приона', 'прионные', 'головки', 'парапроктита'} {'prpsc', 'крейтцфельдта', 'prpc', 'prp', 'paragonimus'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_41
  WTF: {'саркоидоз', 'остеогенная', 'миелоидных'} {'юинга', 'амс', 'капоши'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_42
  WTF: {'10'} {'кпт'}
topic_43
topic_44
  WTF: {'канала'} {'дгпж'}
topic_45
  WTF: {'случаев', 'моно', '50', 'артритом'} {'цог', 'b27', 'гкс', 'нпвп'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_46
  WTF: {'бензнидазол'} {'шагаса'}
topic_47
  WTF: {'невралгия'} {'гбн'}
topic_48
  WTF: {'клещей'} {'trombicula'}
topic_49

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3d6b6579a0>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3b81edeb50>}
{'perplexity': 47193.3671875, 'coherence_20': 1.4379813322260135, 'toplen_ptw': 1.4869681344177414, 'diversity_euclidean': 0.032569005582254534, 'diversity_jensenshannon': 0.7130798099276728, 'diversity_hellinger': 0.8458605389366581, 'diversity_cosine': 0.7872369759683439, 'fair_ppl_free': 5871.4833984375, 'fair_ppl_fix': 46827.796875, 'unfair_ppl_banklike': 47193.3671875}
{'num_topics': 51, 'num_common_words': 101018, 'num_model_words': 127266, 'num_bt_words': 115899, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}]}
13
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
  WTF: {'период'} {'вич'}
topic_1
  WTF: {'quote', 'часто', 'например', 'симптомы'} {'dsm', 'начало_цитаты', 'мкб', 'аспергера'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_2
topic_3
  WTF: {'году', 'лет'} {'эчб', 'мдс'}
topic_4
topic_5
  WTF: {'встречается', 'типу'} {'gm2', 'iga'}
topic_6
  WTF: {'метастазов'} {'гисо'}
topic_7
topic_8
  WTF: {'перегородки', 'пучка', 'левой', 'правого'} {'гиса', 'фп', 'ибс', 'экг'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_9
  WTF: {'ts'} {'спнка'}
topic_10
  WTF: {'кашель', 'воздуха'} {'хобл', 'блд'}
topic_11
  WTF: {'является', 'хронического'} {'крона', 'срк'}
topic_12
topic_13
  WTF: {'гемофилия', 'анемия', 'кровотечений'} {'виллебранда', 'viii', 'гит'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_14
  WTF: {'лимфома', 'миелоидного', 'циклина'} {'опл', 'd1', 'омл'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_15
topic_16
  WTF: {'кератансульфатов'} {'tgfbi'}
topic_17
topic_18
  WTF: {'внутричерепной', 'заболевания'} {'сдг', 'сак'}
topic_19
  WTF: {'деменции', 'дистония', 'терапии'} {'альцгеймера', 'знс', 'дцп'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_20
topic_21
  WTF: {'ожирения', 'ожирением', 'энурез'} {'dsm', 'мкб', 'commentedtext'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_22
topic_23
topic_24
topic_25
  WTF: {'нейросенсорная'} {'дб'}
topic_26
topic_27
topic_28
  WTF: {'обычно', 'две', 'анеуплоидия', 'также', 'хромосому', 'могут', 'мужчин'} {'магенис', 'xxyy', 'xxxy', 'фабри', 'xy', 'xx', 'смит'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_29
  WTF: {'спорадический', 'третичный'} {'псевдогиперпаратиреоз', 'аит'}
topic_30
  WTF: {'пластины', 'фаланг'} {'дюпюитрена', 'мортона'}
topic_31
  WTF: {'содержание'} {'адг'}
topic_32
topic_33
  WTF: {'фиброматоз', 'изменения'} {'боуэна', 'wnt3'}
topic_34
topic_35
  WTF: {'крапивницы'} {'ige'}
topic_36
topic_37
  WTF: {'других'} {'пвл'}
topic_38
  WTF: {'уремией'} {'т4'}
topic_39
  WTF: {'давление', 'гипертонический', 'сосудов', 'портальной', 'больных'} {'зг', 'ара', 'иапф', 'ад', 'аг'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_40
  WTF: {'миелоидные', 'ткани', 'опухолей'} {'юинга', 'амс', 'капоши'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_41
  WTF: {'атрофия'} {'кпт'}
topic_42
  WTF: {'периферической', 'спонтанной', 'характеризуется', 'утопление', 'геморрагическими', 'трупа', 'утоплении'} {'св', 'мпа', 'эгпа', 'рейно', 'цф', 'анца', 'гпа'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_43
  WTF: {'кишки', 'приона', 'прионные', 'головки', 'парапроктита'} {'prpsc', 'крейтцфельдта', 'prpc', 'prp', 'paragonimus'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_44
  WTF: {'головного'} {'гбн'}
topic_45
  WTF: {'канала'} {'дгпж'}
topic_46
  WTF: {'случаев', 'моно', '50', 'артритом'} {'цог', 'b27', 'гкс', 'нпвп'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_47
  WTF: {'нарушением', 'витаминной'} {'бад', 'b12'}
topic_48
  WTF: {'клещей'} {'trombicula'}
topic_49
  WTF: {'яда', 'результате'} {'аи', 'фос'}
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3c69eedf10>}
Check after fit:
Skipping background topic: background_1.
topic_0
  WTF: {'период'} {'вич'}
topic_1
  WTF: {'quote', 'часто', 'например', 'симптомы'} {'dsm', 'начало_цитаты', 'мкб', 'аспергера'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_2
topic_3
  WTF: {'году', 'лет'} {'эчб', 'мдс'}
topic_4
topic_5
  WTF: {'встречается', 'типу'} {'gm2', 'iga'}
topic_6
  WTF: {'метастазов'} {'гисо'}
topic_7
topic_8
  WTF: {'перегородки', 'пучка', 'левой', 'правого'} {'гиса', 'фп', 'ибс', 'экг'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_9
  WTF: {'ts'} {'спнка'}
topic_10
  WTF: {'кашель', 'воздуха'} {'хобл', 'блд'}
topic_11
  WTF: {'является', 'хронического'} {'крона', 'срк'}
topic_12
topic_13
  WTF: {'гемофилия', 'анемия', 'кровотечений'} {'виллебранда', 'viii', 'гит'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_14
  WTF: {'лимфома', 'миелоидного', 'циклина'} {'опл', 'd1', 'омл'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_15
topic_16
  WTF: {'кератансульфатов'} {'tgfbi'}
topic_17
topic_18
  WTF: {'внутричерепной', 'заболевания'} {'сдг', 'сак'}
topic_19
  WTF: {'деменции', 'дистония', 'терапии'} {'альцгеймера', 'знс', 'дцп'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_20
topic_21
  WTF: {'ожирения', 'ожирением', 'энурез'} {'dsm', 'мкб', 'commentedtext'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_22
topic_23
topic_24
topic_25
  WTF: {'нейросенсорная'} {'дб'}
topic_26
topic_27
topic_28
  WTF: {'обычно', 'две', 'анеуплоидия', 'также', 'хромосому', 'могут', 'мужчин'} {'магенис', 'xxyy', 'xxxy', 'фабри', 'xy', 'xx', 'смит'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_29
  WTF: {'спорадический', 'третичный'} {'псевдогиперпаратиреоз', 'аит'}
topic_30
  WTF: {'пластины', 'фаланг'} {'дюпюитрена', 'мортона'}
topic_31
  WTF: {'содержание'} {'адг'}
topic_32
topic_33
  WTF: {'фиброматоз', 'изменения'} {'боуэна', 'wnt3'}
topic_34
topic_35
  WTF: {'крапивницы'} {'ige'}
topic_36
topic_37
  WTF: {'других'} {'пвл'}
topic_38
  WTF: {'уремией'} {'т4'}
topic_39
  WTF: {'давление', 'гипертонический', 'сосудов', 'портальной', 'больных'} {'зг', 'ара', 'иапф', 'ад', 'аг'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_40
  WTF: {'миелоидные', 'ткани', 'опухолей'} {'юинга', 'амс', 'капоши'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_41
  WTF: {'атрофия'} {'кпт'}
topic_42
  WTF: {'периферической', 'спонтанной', 'характеризуется', 'утопление', 'геморрагическими', 'трупа', 'утоплении'} {'св', 'мпа', 'эгпа', 'рейно', 'цф', 'анца', 'гпа'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_43
  WTF: {'кишки', 'приона', 'прионные', 'головки', 'парапроктита'} {'prpsc', 'крейтцфельдта', 'prpc', 'prp', 'paragonimus'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_44
  WTF: {'головного'} {'гбн'}
topic_45
  WTF: {'канала'} {'дгпж'}
topic_46
  WTF: {'случаев', 'моно', '50', 'артритом'} {'цог', 'b27', 'гкс', 'нпвп'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_47
  WTF: {'нарушением', 'витаминной'} {'бад', 'b12'}
topic_48
  WTF: {'клещей'} {'trombicula'}
topic_49
  WTF: {'яда', 'результате'} {'аи', 'фос'}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3d8ff3bb20>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3b7e886190>}
{'perplexity': 46578.64453125, 'coherence_20': 1.439128173141383, 'toplen_ptw': 1.5290144537838737, 'diversity_euclidean': 0.034015208006399726, 'diversity_jensenshannon': 0.7169934950649979, 'diversity_hellinger': 0.8504782893692138, 'diversity_cosine': 0.7958762411077318, 'fair_ppl_free': 5895.65478515625, 'fair_ppl_fix': 41812.4296875, 'unfair_ppl_banklike': 46578.64453125}
{'num_topics': 51, 'num_common_words': 101018, 'num_model_words': 127266, 'num_bt_words': 115899, 'top_diffs': [{'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}]}
14
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
  WTF: {'10'} {'вич'}
topic_1
  WTF: {'quote', 'детей', 'часто', 'например'} {'dsm', 'начало_цитаты', 'мкб', 'аспергера'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_2
topic_3
topic_4
  WTF: {'году', 'гена', 'синдромом'} {'ахс', 'мдс', 'эчб'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_5
topic_6
  WTF: {'мозга'} {'гисо'}
topic_7
  WTF: {'перегородки', 'пучка', 'левой', 'сердце'} {'гиса', 'фп', 'ибс', 'экг'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_8
topic_9
  WTF: {'ферментов', 'группы', 'наследственное'} {'gm2', 'iga', 'тея'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_10
  WTF: {'также', 'детей'} {'хобл', 'блд'}
topic_11
  WTF: {'отдела', 'лечение'} {'крона', 'срк'}
topic_12
topic_13
  WTF: {'анемией', 'анемия', 'вен'} {'виллебранда', 'viii', 'гит'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_14
topic_15
topic_16
  WTF: {'хороидеремии', 'кератансульфатов'} {'кератоэпителин', 'tgfbi'}
topic_17
topic_18
  WTF: {'ожирения', 'ожирением', 'энурез'} {'dsm', 'мкб', 'commentedtext'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_19
topic_20
topic_21
  WTF: {'уремия'} {'b12'}
topic_22
  WTF: {'нейролептика', 'терапии'} {'знс', 'дцп'}
topic_23
topic_24
topic_25
  WTF: {'крови', 'abl', 'химиотерапии', 'транс', 'стволовых'} {'хмл', 'опл', 'омл', 'atra', 'фаб'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_26
  WTF: {'обычно', 'две', 'анеуплоидия', 'также', 'хромосому', 'могут', 'мужчин'} {'магенис', 'xxyy', 'xxxy', 'фабри', 'xy', 'xx', 'смит'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_27
topic_28
  WTF: {'пластины', 'фаланг'} {'дюпюитрена', 'мортона'}
topic_29
  WTF: {'спорадический', 'третичный'} {'псевдогиперпаратиреоз', 'аит'}
topic_30
  WTF: {'англ', 'экспрессии', 'клетках', 'больных'} {'хлл', 'd1', 'нхл', 'ходжкина'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_31
  WTF: {'содержание'} {'адг'}
topic_32
  WTF: {'кифосколиоз'} {'шморля'}
topic_33
  WTF: {'других', 'аутосомно', 'больных'} {'пмл', 'пвл', 'jc'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_34
  WTF: {'реакции', 'заболевания'} {'олб', 'wnt3'}
topic_35
topic_36
  WTF: {'давление', 'гипертонический', 'сосудов', 'портальной', 'больных'} {'зг', 'ара', 'иапф', 'ад', 'аг'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_37
  WTF: {'пациентов'} {'альцгеймера'}
topic_38
  WTF: {'черепа', 'кровотока', 'субарахноидальное', 'объёма'} {'кт', 'сдг', 'вчг', 'сак'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_39
  WTF: {'паука'} {'buthidae'}
topic_40
  WTF: {'также'} {'clostridium'}
topic_41
  WTF: {'атрофия'} {'кпт'}
topic_42
  WTF: {'кишки', 'приона', 'прионные', 'головки', 'парапроктита'} {'prpsc', 'крейтцфельдта', 'prpc', 'prp', 'paragonimus'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_43
  WTF: {'саркоидоз', 'остеогенная', 'миелоидных'} {'юинга', 'амс', 'капоши'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_44
  WTF: {'канала'} {'дгпж'}
topic_45
  WTF: {'бензнидазол'} {'шагаса'}
topic_46
  WTF: {'невралгия'} {'гбн'}
topic_47
  WTF: {'случаев', 'моно', '50', 'артритом'} {'цог', 'b27', 'гкс', 'нпвп'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_48
  WTF: {'клещей'} {'trombicula'}
topic_49
  WTF: {'бревно', 'терминальной', 'синдром'} {'скф', 'хбп', 'хпн'}
  WTF?!?!? 3
  WTF?!?!? 3
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3af8bb73d0>}
Check after fit:
Skipping background topic: background_1.
topic_0
  WTF: {'10'} {'вич'}
topic_1
  WTF: {'quote', 'детей', 'часто', 'например'} {'dsm', 'начало_цитаты', 'мкб', 'аспергера'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_2
topic_3
topic_4
  WTF: {'году', 'гена', 'синдромом'} {'ахс', 'мдс', 'эчб'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_5
topic_6
  WTF: {'мозга'} {'гисо'}
topic_7
  WTF: {'перегородки', 'пучка', 'левой', 'сердце'} {'гиса', 'фп', 'ибс', 'экг'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_8
topic_9
  WTF: {'ферментов', 'группы', 'наследственное'} {'gm2', 'iga', 'тея'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_10
  WTF: {'также', 'детей'} {'хобл', 'блд'}
topic_11
  WTF: {'отдела', 'лечение'} {'крона', 'срк'}
topic_12
topic_13
  WTF: {'анемией', 'анемия', 'вен'} {'виллебранда', 'viii', 'гит'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_14
topic_15
topic_16
  WTF: {'хороидеремии', 'кератансульфатов'} {'кератоэпителин', 'tgfbi'}
topic_17
topic_18
  WTF: {'ожирения', 'ожирением', 'энурез'} {'dsm', 'мкб', 'commentedtext'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_19
topic_20
topic_21
  WTF: {'уремия'} {'b12'}
topic_22
  WTF: {'нейролептика', 'терапии'} {'знс', 'дцп'}
topic_23
topic_24
topic_25
  WTF: {'крови', 'abl', 'химиотерапии', 'транс', 'стволовых'} {'хмл', 'опл', 'омл', 'atra', 'фаб'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_26
  WTF: {'обычно', 'две', 'анеуплоидия', 'также', 'хромосому', 'могут', 'мужчин'} {'магенис', 'xxyy', 'xxxy', 'фабри', 'xy', 'xx', 'смит'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_27
topic_28
  WTF: {'пластины', 'фаланг'} {'дюпюитрена', 'мортона'}
topic_29
  WTF: {'спорадический', 'третичный'} {'псевдогиперпаратиреоз', 'аит'}
topic_30
  WTF: {'англ', 'экспрессии', 'клетках', 'больных'} {'хлл', 'd1', 'нхл', 'ходжкина'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_31
  WTF: {'содержание'} {'адг'}
topic_32
  WTF: {'кифосколиоз'} {'шморля'}
topic_33
  WTF: {'других', 'аутосомно', 'больных'} {'пмл', 'пвл', 'jc'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_34
  WTF: {'реакции', 'заболевания'} {'олб', 'wnt3'}
topic_35
topic_36
  WTF: {'давление', 'гипертонический', 'сосудов', 'портальной', 'больных'} {'зг', 'ара', 'иапф', 'ад', 'аг'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_37
  WTF: {'пациентов'} {'альцгеймера'}
topic_38
  WTF: {'черепа', 'кровотока', 'субарахноидальное', 'объёма'} {'кт', 'сдг', 'вчг', 'сак'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_39
  WTF: {'паука'} {'buthidae'}
topic_40
  WTF: {'также'} {'clostridium'}
topic_41
  WTF: {'атрофия'} {'кпт'}
topic_42
  WTF: {'кишки', 'приона', 'прионные', 'головки', 'парапроктита'} {'prpsc', 'крейтцфельдта', 'prpc', 'prp', 'paragonimus'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_43
  WTF: {'саркоидоз', 'остеогенная', 'миелоидных'} {'юинга', 'амс', 'капоши'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_44
  WTF: {'канала'} {'дгпж'}
topic_45
  WTF: {'бензнидазол'} {'шагаса'}
topic_46
  WTF: {'невралгия'} {'гбн'}
topic_47
  WTF: {'случаев', 'моно', '50', 'артритом'} {'цог', 'b27', 'гкс', 'нпвп'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_48
  WTF: {'клещей'} {'trombicula'}
topic_49
  WTF: {'бревно', 'терминальной', 'синдром'} {'скф', 'хбп', 'хпн'}
  WTF?!?!? 3
  WTF?!?!? 3

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3c7bebbd90>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3c90be7490>}
{'perplexity': 48675.48828125, 'coherence_20': 1.4679998569336463, 'toplen_ptw': 1.4639272113603763, 'diversity_euclidean': 0.03317751013279821, 'diversity_jensenshannon': 0.7145744339175251, 'diversity_hellinger': 0.8476862421206804, 'diversity_cosine': 0.7916680266632516, 'fair_ppl_free': 5964.75830078125, 'fair_ppl_fix': 42911.96484375, 'unfair_ppl_banklike': 48675.48828125}
{'num_topics': 51, 'num_common_words': 101018, 'num_model_words': 127266, 'num_bt_words': 115899, 'top_diffs': [{'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}]}
15
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
topic_3
  WTF: {'quote', 'аутизма', 'часто', 'симптомы'} {'dsm', 'начало_цитаты', 'мкб', 'аспергера'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_4
topic_5
  WTF: {'году', 'гена', 'мутации'} {'ахс', 'мдс', 'эчб'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_6
  WTF: {'мозга'} {'гисо'}
topic_7
  WTF: {'группы', 'наследуется'} {'gm2', 'iga'}
topic_8
  WTF: {'перегородки', 'пучка', 'кровообращения', 'левой'} {'гиса', 'фп', 'ибс', 'экг'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_9
  WTF: {'человек'} {'вич'}
topic_10
  WTF: {'ts'} {'спнка'}
topic_11
  WTF: {'кашель', 'воздуха'} {'хобл', 'блд'}
topic_12
topic_13
  WTF: {'лечения', 'лечение'} {'крона', 'срк'}
topic_14
  WTF: {'лимфома', 'миелоидного', 'циклина'} {'опл', 'd1', 'омл'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_15
  WTF: {'эритроцитов', 'кровотечений', 'вен'} {'виллебранда', 'viii', 'гит'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_16
topic_17
topic_18
  WTF: {'ожирения', 'ожирением', 'энурез'} {'dsm', 'мкб', 'commentedtext'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_19
  WTF: {'головы', 'болезнь'} {'альцгеймера', 'дцп'}
topic_20
topic_21
  WTF: {'письма'} {'дб'}
topic_22
topic_23
topic_24
topic_25
topic_26
  WTF: {'терапии'} {'знс'}
topic_27
  WTF: {'обычно', 'две', 'анеуплоидия', 'также', 'хромосому', 'могут', 'мужчин'} {'магенис', 'xxyy', 'xxxy', 'фабри', 'xy', 'xx', 'смит'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_28
  WTF: {'вещества', 'вируса'} {'пмл', 'пвл'}
topic_29
  WTF: {'содержание'} {'адг'}
topic_30
  WTF: {'артерий', 'кровотока', 'окклюзии', 'давление'} {'кт', 'сдг', 'вчг', 'сак'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_31
  WTF: {'щитовидной', 'железы'} {'стг', 'b12'}
topic_32
topic_33
  WTF: {'давление', 'гипертонический', 'сосудов', 'портальной', 'больных'} {'зг', 'ара', 'иапф', 'ад', 'аг'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_34
  WTF: {'крови', 'эмболия', 'лёгочной', 'вен', 'сосудов', 'эмболии', 'мг', 'грудной', 'артерии', 'эндокардита'} {'иэ', 'св', 'мпа', 'эгпа', 'рейно', 'цф', 'анца', 'тэла', 'эхокг', 'гпа'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_35
  WTF: {'системы', 'гиперкортицизм'} {'щж', 'аит'}
topic_36
topic_37
  WTF: {'паука'} {'buthidae'}
topic_38
topic_39
  WTF: {'тетраамели'} {'wnt3'}
topic_40
  WTF: {'атрофия'} {'кпт'}
topic_41
  WTF: {'миелоидные', 'клетки', 'выживаемость'} {'юинга', 'амс', 'капоши'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_42
  WTF: {'кишки', 'приона', 'прионные', 'головки', 'парапроктита'} {'prpsc', 'крейтцфельдта', 'prpc', 'prp', 'paragonimus'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_43
  WTF: {'холестерина'} {'жкб'}
topic_44
  WTF: {'случаев', 'моно', '50', 'артритом'} {'цог', 'b27', 'гкс', 'нпвп'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_45
  WTF: {'бензнидазол'} {'шагаса'}
topic_46
  WTF: {'канала'} {'дгпж'}
topic_47
topic_48
  WTF: {'вещества', 'соединения'} {'аи', 'фос'}
topic_49
  WTF: {'клещей'} {'trombicula'}
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3d8faf9790>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
topic_3
  WTF: {'quote', 'аутизма', 'часто', 'симптомы'} {'dsm', 'начало_цитаты', 'мкб', 'аспергера'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_4
topic_5
  WTF: {'году', 'гена', 'мутации'} {'ахс', 'мдс', 'эчб'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_6
  WTF: {'мозга'} {'гисо'}
topic_7
  WTF: {'группы', 'наследуется'} {'gm2', 'iga'}
topic_8
  WTF: {'перегородки', 'пучка', 'кровообращения', 'левой'} {'гиса', 'фп', 'ибс', 'экг'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_9
  WTF: {'человек'} {'вич'}
topic_10
  WTF: {'ts'} {'спнка'}
topic_11
  WTF: {'кашель', 'воздуха'} {'хобл', 'блд'}
topic_12
topic_13
  WTF: {'лечения', 'лечение'} {'крона', 'срк'}
topic_14
  WTF: {'лимфома', 'миелоидного', 'циклина'} {'опл', 'd1', 'омл'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_15
  WTF: {'эритроцитов', 'кровотечений', 'вен'} {'виллебранда', 'viii', 'гит'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_16
topic_17
topic_18
  WTF: {'ожирения', 'ожирением', 'энурез'} {'dsm', 'мкб', 'commentedtext'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_19
  WTF: {'головы', 'болезнь'} {'альцгеймера', 'дцп'}
topic_20
topic_21
  WTF: {'письма'} {'дб'}
topic_22
topic_23
topic_24
topic_25
topic_26
  WTF: {'терапии'} {'знс'}
topic_27
  WTF: {'обычно', 'две', 'анеуплоидия', 'также', 'хромосому', 'могут', 'мужчин'} {'магенис', 'xxyy', 'xxxy', 'фабри', 'xy', 'xx', 'смит'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_28
  WTF: {'вещества', 'вируса'} {'пмл', 'пвл'}
topic_29
  WTF: {'содержание'} {'адг'}
topic_30
  WTF: {'артерий', 'кровотока', 'окклюзии', 'давление'} {'кт', 'сдг', 'вчг', 'сак'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_31
  WTF: {'щитовидной', 'железы'} {'стг', 'b12'}
topic_32
topic_33
  WTF: {'давление', 'гипертонический', 'сосудов', 'портальной', 'больных'} {'зг', 'ара', 'иапф', 'ад', 'аг'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_34
  WTF: {'крови', 'эмболия', 'лёгочной', 'вен', 'сосудов', 'эмболии', 'мг', 'грудной', 'артерии', 'эндокардита'} {'иэ', 'св', 'мпа', 'эгпа', 'рейно', 'цф', 'анца', 'тэла', 'эхокг', 'гпа'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_35
  WTF: {'системы', 'гиперкортицизм'} {'щж', 'аит'}
topic_36
topic_37
  WTF: {'паука'} {'buthidae'}
topic_38
topic_39
  WTF: {'тетраамели'} {'wnt3'}
topic_40
  WTF: {'атрофия'} {'кпт'}
topic_41
  WTF: {'миелоидные', 'клетки', 'выживаемость'} {'юинга', 'амс', 'капоши'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_42
  WTF: {'кишки', 'приона', 'прионные', 'головки', 'парапроктита'} {'prpsc', 'крейтцфельдта', 'prpc', 'prp', 'paragonimus'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_43
  WTF: {'холестерина'} {'жкб'}
topic_44
  WTF: {'случаев', 'моно', '50', 'артритом'} {'цог', 'b27', 'гкс', 'нпвп'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_45
  WTF: {'бензнидазол'} {'шагаса'}
topic_46
  WTF: {'канала'} {'дгпж'}
topic_47
topic_48
  WTF: {'вещества', 'соединения'} {'аи', 'фос'}
topic_49
  WTF: {'клещей'} {'trombicula'}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3bec3d5be0>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3b7eb7e460>}
{'perplexity': 48240.28125, 'coherence_20': 1.4439265102432532, 'toplen_ptw': 1.5325766528905662, 'diversity_euclidean': 0.03237681744007794, 'diversity_jensenshannon': 0.7131532145943447, 'diversity_hellinger': 0.8455002910718149, 'diversity_cosine': 0.7835864237114595, 'fair_ppl_free': 5790.52685546875, 'fair_ppl_fix': 46209.34375, 'unfair_ppl_banklike': 48240.28125}
{'num_topics': 51, 'num_common_words': 101018, 'num_model_words': 127266, 'num_bt_words': 115899, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}]}
16
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
  WTF: {'года'} {'вич'}
topic_1
  WTF: {'quote', 'аутизма', 'часто', 'например'} {'dsm', 'начало_цитаты', 'мкб', 'аспергера'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_2
topic_3
  WTF: {'of'} {'iga'}
topic_4
  WTF: {'могут', 'синдромом'} {'эчб', 'мдс'}
topic_5
  WTF: {'мозга'} {'гисо'}
topic_6
topic_7
  WTF: {'перегородки', 'пучка', 'кровообращения', 'левой'} {'гиса', 'фп', 'ибс', 'экг'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_8
  WTF: {'ts'} {'спнка'}
topic_9
  WTF: {'также', 'воздуха'} {'хобл', 'блд'}
topic_10
topic_11
  WTF: {'пищеводного', 'панкреатита'} {'крона', 'срк'}
topic_12
  WTF: {'лет', '16', 'отмены', 'нейролептического'} {'туретта', 'альцгеймера', 'знс', 'дцп'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_13
  WTF: {'лимфома', 'миелоидного', 'циклина'} {'опл', 'd1', 'омл'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_14
  WTF: {'анемия', 'эритроцитов', 'кровотечений'} {'виллебранда', 'viii', 'гит'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_15
topic_16
  WTF: {'хороидеремии', 'кератансульфатов'} {'кератоэпителин', 'tgfbi'}
topic_17
topic_18
  WTF: {'ожирения', 'ожирением', 'энурез'} {'dsm', 'мкб', 'commentedtext'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_19
topic_20
topic_21
topic_22
topic_23
  WTF: {'нейросенсорная'} {'дб'}
topic_24
topic_25
  WTF: {'сонного'} {'hppd'}
topic_26
topic_27
  WTF: {'обычно', 'две', 'анеуплоидия', 'также', 'хромосому', 'могут', 'мужчин'} {'магенис', 'xxyy', 'xxxy', 'фабри', 'xy', 'xx', 'смит'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_28
  WTF: {'анестезией', 'анестетика'} {'дюпюитрена', 'мортона'}
topic_29
  WTF: {'содержание'} {'адг'}
topic_30
  WTF: {'артерий', 'кровотока', 'окклюзии', 'давление'} {'кт', 'сдг', 'вчг', 'сак'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_31
  WTF: {'заболевание', 'вирус'} {'пмл', 'пвл'}
topic_32
topic_33
topic_34
topic_35
  WTF: {'конъюнктивиты'} {'ige'}
topic_36
  WTF: {'давление', 'гипертонический', 'сосудов', 'портальной', 'больных'} {'зг', 'ара', 'иапф', 'ад', 'аг'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_37
  WTF: {'механизму', 'заболевания'} {'щж', 'аит'}
topic_38
  WTF: {'кишки', 'приона', 'прионные', 'головки', 'парапроктита'} {'prpsc', 'крейтцфельдта', 'prpc', 'prp', 'paragonimus'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_39
  WTF: {'фиброматоз', 'ткани'} {'олб', 'wnt3'}
topic_40
  WTF: {'миелоидные', 'клетки', 'выживаемость'} {'юинга', 'амс', 'капоши'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_41
  WTF: {'10'} {'кпт'}
topic_42
  WTF: {'клещей'} {'trombicula'}
topic_43
  WTF: {'случаев', 'моно', '50', 'артритом'} {'цог', 'b27', 'гкс', 'нпвп'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_44
  WTF: {'бензнидазол'} {'шагаса'}
topic_45
  WTF: {'крови', 'органа', 'эмболия', '109', 'эмфизема', 'биопсии', 'свойственно', 'васкулита', 'больных', 'тромбоцитов'} {'гн', 'св', 'гк', 'мпа', 'эгпа', 'аст', 'алт', 'цф', 'анца', 'гпа'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_46
  WTF: {'канала'} {'дгпж'}
topic_47
  WTF: {'цитрусовые', 'титруемых'} {'вельтищеву', 'беллью'}
topic_48
  WTF: {'невралгия'} {'гбн'}
topic_49
  WTF: {'трихомониаз', 'половых'} {'иппп', 'neisseria'}
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3d5a879460>}
Check after fit:
Skipping background topic: background_1.
topic_0
  WTF: {'года'} {'вич'}
topic_1
  WTF: {'quote', 'аутизма', 'часто', 'например'} {'dsm', 'начало_цитаты', 'мкб', 'аспергера'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_2
topic_3
  WTF: {'of'} {'iga'}
topic_4
  WTF: {'могут', 'синдромом'} {'эчб', 'мдс'}
topic_5
  WTF: {'мозга'} {'гисо'}
topic_6
topic_7
  WTF: {'перегородки', 'пучка', 'кровообращения', 'левой'} {'гиса', 'фп', 'ибс', 'экг'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_8
  WTF: {'ts'} {'спнка'}
topic_9
  WTF: {'также', 'воздуха'} {'хобл', 'блд'}
topic_10
topic_11
  WTF: {'пищеводного', 'панкреатита'} {'крона', 'срк'}
topic_12
  WTF: {'лет', '16', 'отмены', 'нейролептического'} {'туретта', 'альцгеймера', 'знс', 'дцп'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_13
  WTF: {'лимфома', 'миелоидного', 'циклина'} {'опл', 'd1', 'омл'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_14
  WTF: {'анемия', 'эритроцитов', 'кровотечений'} {'виллебранда', 'viii', 'гит'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_15
topic_16
  WTF: {'хороидеремии', 'кератансульфатов'} {'кератоэпителин', 'tgfbi'}
topic_17
topic_18
  WTF: {'ожирения', 'ожирением', 'энурез'} {'dsm', 'мкб', 'commentedtext'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_19
topic_20
topic_21
topic_22
topic_23
  WTF: {'нейросенсорная'} {'дб'}
topic_24
topic_25
  WTF: {'сонного'} {'hppd'}
topic_26
topic_27
  WTF: {'обычно', 'две', 'анеуплоидия', 'также', 'хромосому', 'могут', 'мужчин'} {'магенис', 'xxyy', 'xxxy', 'фабри', 'xy', 'xx', 'смит'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_28
  WTF: {'анестезией', 'анестетика'} {'дюпюитрена', 'мортона'}
topic_29
  WTF: {'содержание'} {'адг'}
topic_30
  WTF: {'артерий', 'кровотока', 'окклюзии', 'давление'} {'кт', 'сдг', 'вчг', 'сак'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_31
  WTF: {'заболевание', 'вирус'} {'пмл', 'пвл'}
topic_32
topic_33
topic_34
topic_35
  WTF: {'конъюнктивиты'} {'ige'}
topic_36
  WTF: {'давление', 'гипертонический', 'сосудов', 'портальной', 'больных'} {'зг', 'ара', 'иапф', 'ад', 'аг'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_37
  WTF: {'механизму', 'заболевания'} {'щж', 'аит'}
topic_38
  WTF: {'кишки', 'приона', 'прионные', 'головки', 'парапроктита'} {'prpsc', 'крейтцфельдта', 'prpc', 'prp', 'paragonimus'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_39
  WTF: {'фиброматоз', 'ткани'} {'олб', 'wnt3'}
topic_40
  WTF: {'миелоидные', 'клетки', 'выживаемость'} {'юинга', 'амс', 'капоши'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_41
  WTF: {'10'} {'кпт'}
topic_42
  WTF: {'клещей'} {'trombicula'}
topic_43
  WTF: {'случаев', 'моно', '50', 'артритом'} {'цог', 'b27', 'гкс', 'нпвп'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_44
  WTF: {'бензнидазол'} {'шагаса'}
topic_45
  WTF: {'крови', 'органа', 'эмболия', '109', 'эмфизема', 'биопсии', 'свойственно', 'васкулита', 'больных', 'тромбоцитов'} {'гн', 'св', 'гк', 'мпа', 'эгпа', 'аст', 'алт', 'цф', 'анца', 'гпа'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_46
  WTF: {'канала'} {'дгпж'}
topic_47
  WTF: {'цитрусовые', 'титруемых'} {'вельтищеву', 'беллью'}
topic_48
  WTF: {'невралгия'} {'гбн'}
topic_49
  WTF: {'трихомониаз', 'половых'} {'иппп', 'neisseria'}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3bb6554670>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3d76efea30>}
{'perplexity': 46067.921875, 'coherence_20': 1.476534142848298, 'toplen_ptw': 1.4985134910163054, 'diversity_euclidean': 0.033619193346193205, 'diversity_jensenshannon': 0.7176653811908966, 'diversity_hellinger': 0.8515153553822962, 'diversity_cosine': 0.7971221459096153, 'fair_ppl_free': 6000.279296875, 'fair_ppl_fix': 41807.1875, 'unfair_ppl_banklike': 46067.921875}
{'num_topics': 51, 'num_common_words': 101018, 'num_model_words': 127266, 'num_bt_words': 115899, 'top_diffs': [{'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}]}
17
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
  WTF: {'10'} {'вич'}
topic_1
topic_2
  WTF: {'quote', 'детей', 'часто', 'например'} {'dsm', 'начало_цитаты', 'мкб', 'аспергера'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_3
topic_4
  WTF: {'метастазов'} {'гисо'}
topic_5
topic_6
  WTF: {'перегородки', 'пучка', 'левой', 'правого'} {'гиса', 'фп', 'ибс', 'экг'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_7
topic_8
  WTF: {'ts'} {'спнка'}
topic_9
  WTF: {'лечения', 'лечение'} {'крона', 'срк'}
topic_10
  WTF: {'кашель', 'воздуха'} {'хобл', 'блд'}
topic_11
topic_12
topic_13
  WTF: {'происходит', 'уровень', 'поражение', 'заболевания', 'больных'} {'viii', 'виллебранда', 'гит', 'св', 'анца'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_14
topic_15
  WTF: {'хороидеремии', 'кератансульфатов'} {'кератоэпителин', 'tgfbi'}
topic_16
  WTF: {'могут', 'деменции', 'болезнь'} {'туретта', 'альцгеймера', 'дцп'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_17
topic_18
  WTF: {'ожирения', 'ожирением', 'энурез'} {'dsm', 'мкб', 'commentedtext'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_19
topic_20
topic_21
topic_22
  WTF: {'терапии'} {'знс'}
topic_23
  WTF: {'крови', 'abl', 'химиотерапии', 'транс', 'стволовых'} {'хмл', 'опл', 'омл', 'atra', 'фаб'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_24
topic_25
  WTF: {'обычно', 'две', 'анеуплоидия', 'также', 'хромосому', 'могут', 'мужчин'} {'магенис', 'xxyy', 'xxxy', 'фабри', 'xy', 'xx', 'смит'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_26
topic_27
  WTF: {'облучении', 'органов', 'тетраамелии'} {'олб', 'wnt3', 'жкб'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_28
  WTF: {'пластины', 'фаланг'} {'дюпюитрена', 'мортона'}
topic_29
  WTF: {'англ', 'экспрессии', 'клетках', 'больных'} {'хлл', 'd1', 'нхл', 'ходжкина'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_30
  WTF: {'содержание'} {'адг'}
topic_31
  WTF: {'сыворотки', 'заболевания', 'botulinum'} {'киари', 'сак', 'арнольда'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_32
  WTF: {'артерий', 'кровотока', 'окклюзии', 'давление'} {'кт', 'сдг', 'вчг', 'сак'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_33
topic_34
  WTF: {'системы', 'гиперкортицизм'} {'щж', 'аит'}
topic_35
  WTF: {'других'} {'пвл'}
topic_36
  WTF: {'давление', 'гипертонический', 'сосудов', 'портальной', 'больных'} {'зг', 'ара', 'иапф', 'ад', 'аг'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_37
topic_38
  WTF: {'недоедания'} {'кпт'}
topic_39
  WTF: {'паука'} {'buthidae'}
topic_40
  WTF: {'кишки', 'приона', 'прионные', 'головки', 'парапроктита'} {'prpsc', 'крейтцфельдта', 'prpc', 'prp', 'paragonimus'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_41
topic_42
  WTF: {'саркоидоз', 'остеогенная', 'миелоидных'} {'юинга', 'амс', 'капоши'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_43
  WTF: {'бензнидазол'} {'шагаса'}
topic_44
topic_45
  WTF: {'случаев', 'моно', '50', 'артритом'} {'цог', 'b27', 'гкс', 'нпвп'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_46
topic_47
  WTF: {'канала'} {'дгпж'}
topic_48
  WTF: {'клещей'} {'trombicula'}
topic_49
  WTF: {'канальцы'} {'вельтищеву'}
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3bebdf9a60>}
Check after fit:
Skipping background topic: background_1.
topic_0
  WTF: {'10'} {'вич'}
topic_1
topic_2
  WTF: {'quote', 'детей', 'часто', 'например'} {'dsm', 'начало_цитаты', 'мкб', 'аспергера'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_3
topic_4
  WTF: {'метастазов'} {'гисо'}
topic_5
topic_6
  WTF: {'перегородки', 'пучка', 'левой', 'правого'} {'гиса', 'фп', 'ибс', 'экг'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_7
topic_8
  WTF: {'ts'} {'спнка'}
topic_9
  WTF: {'лечения', 'лечение'} {'крона', 'срк'}
topic_10
  WTF: {'кашель', 'воздуха'} {'хобл', 'блд'}
topic_11
topic_12
topic_13
  WTF: {'происходит', 'уровень', 'поражение', 'заболевания', 'больных'} {'viii', 'виллебранда', 'гит', 'св', 'анца'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_14
topic_15
  WTF: {'хороидеремии', 'кератансульфатов'} {'кератоэпителин', 'tgfbi'}
topic_16
  WTF: {'могут', 'деменции', 'болезнь'} {'туретта', 'альцгеймера', 'дцп'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_17
topic_18
  WTF: {'ожирения', 'ожирением', 'энурез'} {'dsm', 'мкб', 'commentedtext'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_19
topic_20
topic_21
topic_22
  WTF: {'терапии'} {'знс'}
topic_23
  WTF: {'крови', 'abl', 'химиотерапии', 'транс', 'стволовых'} {'хмл', 'опл', 'омл', 'atra', 'фаб'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_24
topic_25
  WTF: {'обычно', 'две', 'анеуплоидия', 'также', 'хромосому', 'могут', 'мужчин'} {'магенис', 'xxyy', 'xxxy', 'фабри', 'xy', 'xx', 'смит'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_26
topic_27
  WTF: {'облучении', 'органов', 'тетраамелии'} {'олб', 'wnt3', 'жкб'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_28
  WTF: {'пластины', 'фаланг'} {'дюпюитрена', 'мортона'}
topic_29
  WTF: {'англ', 'экспрессии', 'клетках', 'больных'} {'хлл', 'd1', 'нхл', 'ходжкина'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_30
  WTF: {'содержание'} {'адг'}
topic_31
  WTF: {'сыворотки', 'заболевания', 'botulinum'} {'киари', 'сак', 'арнольда'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_32
  WTF: {'артерий', 'кровотока', 'окклюзии', 'давление'} {'кт', 'сдг', 'вчг', 'сак'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_33
topic_34
  WTF: {'системы', 'гиперкортицизм'} {'щж', 'аит'}
topic_35
  WTF: {'других'} {'пвл'}
topic_36
  WTF: {'давление', 'гипертонический', 'сосудов', 'портальной', 'больных'} {'зг', 'ара', 'иапф', 'ад', 'аг'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_37
topic_38
  WTF: {'недоедания'} {'кпт'}
topic_39
  WTF: {'паука'} {'buthidae'}
topic_40
  WTF: {'кишки', 'приона', 'прионные', 'головки', 'парапроктита'} {'prpsc', 'крейтцфельдта', 'prpc', 'prp', 'paragonimus'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_41
topic_42
  WTF: {'саркоидоз', 'остеогенная', 'миелоидных'} {'юинга', 'амс', 'капоши'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_43
  WTF: {'бензнидазол'} {'шагаса'}
topic_44
topic_45
  WTF: {'случаев', 'моно', '50', 'артритом'} {'цог', 'b27', 'гкс', 'нпвп'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_46
topic_47
  WTF: {'канала'} {'дгпж'}
topic_48
  WTF: {'клещей'} {'trombicula'}
topic_49
  WTF: {'канальцы'} {'вельтищеву'}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3fa93f4f40>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3d5a118b20>}
{'perplexity': 46806.62890625, 'coherence_20': 1.5182082111362583, 'toplen_ptw': 1.488491241266792, 'diversity_euclidean': 0.03481497066043875, 'diversity_jensenshannon': 0.7199953659981178, 'diversity_hellinger': 0.8542157852285308, 'diversity_cosine': 0.8017133250073217, 'fair_ppl_free': 5995.595703125, 'fair_ppl_fix': 42583.8125, 'unfair_ppl_banklike': 46806.62890625}
{'num_topics': 51, 'num_common_words': 101018, 'num_model_words': 127266, 'num_bt_words': 115899, 'top_diffs': [{'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}]}
18
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
  WTF: {'личинки'} {'вич'}
topic_1
topic_2
  WTF: {'quote', 'аутизма', 'часто', 'например'} {'dsm', 'начало_цитаты', 'мкб', 'аспергера'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_3
topic_4
  WTF: {'метастазов'} {'гисо'}
topic_5
  WTF: {'могут', 'году', 'мутации'} {'ахс', 'мдс', 'эчб'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_6
  WTF: {'перегородки', 'пучка', 'левой', 'сердце'} {'гиса', 'фп', 'ибс', 'экг'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_7
  WTF: {'группы', 'наследуется', 'and'} {'gm2', 'iga', 'тея'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_8
  WTF: {'ts'} {'спнка'}
topic_9
  WTF: {'кашель', 'воздуха'} {'хобл', 'блд'}
topic_10
  WTF: {'лечения', 'железы'} {'крона', 'срк'}
topic_11
topic_12
  WTF: {'нейролептического', 'отмены', 'эпилепсии', '16'} {'туретта', 'альцгеймера', 'знс', 'дцп'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_13
  WTF: {'миндалин'} {'ige'}
topic_14
  WTF: {'гемофилия', 'кровотечений', 'вен'} {'виллебранда', 'viii', 'гит'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_15
  WTF: {'лимфома', 'миелоидного', 'циклина'} {'опл', 'd1', 'омл'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_16
topic_17
topic_18
  WTF: {'арахноидите', 'ишемического'} {'сдг', 'сак'}
topic_19
  WTF: {'кератоэпителин', 'кератансульфатов'} {'tgfbi', 'bcd'}
topic_20
  WTF: {'ожирения', 'ожирением', 'энурез'} {'dsm', 'мкб', 'commentedtext'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_21
topic_22
  WTF: {'нейросенсорная'} {'дб'}
topic_23
topic_24
topic_25
topic_26
  WTF: {'недостаточности'} {'т3'}
topic_27
topic_28
  WTF: {'обычно', 'две', 'анеуплоидия', 'также', 'хромосому', 'могут', 'мужчин'} {'магенис', 'xxyy', 'xxxy', 'фабри', 'xy', 'xx', 'смит'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_29
  WTF: {'пластины', 'фаланг'} {'дюпюитрена', 'мортона'}
topic_30
  WTF: {'содержание'} {'адг'}
topic_31
topic_32
topic_33
  WTF: {'конкременты', 'заболевания'} {'wnt3', 'жкб'}
topic_34
  WTF: {'гипокальциемический'} {'b12'}
topic_35
  WTF: {'аутосомно', 'больных', 'костного'} {'пмл', 'пвл', 'jc'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_36
topic_37
  WTF: {'системы', 'гиперкортицизм'} {'щж', 'аит'}
topic_38
  WTF: {'давление', 'гипертонический', 'сосудов', 'портальной', 'больных'} {'зг', 'ара', 'иапф', 'ад', 'аг'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_39
  WTF: {'миелоидные', 'клетки', 'выживаемость'} {'юинга', 'амс', 'капоши'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_40
  WTF: {'кишки', 'приона', 'прионные', 'головки', 'парапроктита'} {'prpsc', 'крейтцфельдта', 'prpc', 'prp', 'paragonimus'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_41
  WTF: {'эмболия'} {'вегенера'}
topic_42
  WTF: {'лечения', 'женщинам', 'маммография'} {'фоп', 'дф', 'фм'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_43
  WTF: {'10'} {'кпт'}
topic_44
  WTF: {'бензнидазол'} {'шагаса'}
topic_45
  WTF: {'случаев', 'моно', '50', 'артритом'} {'цог', 'b27', 'гкс', 'нпвп'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_46
  WTF: {'канала'} {'дгпж'}
topic_47
  WTF: {'невралгия'} {'гбн'}
topic_48
  WTF: {'клещей'} {'trombicula'}
topic_49
  WTF: {'изменения'} {'т4'}
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3cedc563d0>}
Check after fit:
Skipping background topic: background_1.
topic_0
  WTF: {'личинки'} {'вич'}
topic_1
topic_2
  WTF: {'quote', 'аутизма', 'часто', 'например'} {'dsm', 'начало_цитаты', 'мкб', 'аспергера'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_3
topic_4
  WTF: {'метастазов'} {'гисо'}
topic_5
  WTF: {'могут', 'году', 'мутации'} {'ахс', 'мдс', 'эчб'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_6
  WTF: {'перегородки', 'пучка', 'левой', 'сердце'} {'гиса', 'фп', 'ибс', 'экг'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_7
  WTF: {'группы', 'наследуется', 'and'} {'gm2', 'iga', 'тея'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_8
  WTF: {'ts'} {'спнка'}
topic_9
  WTF: {'кашель', 'воздуха'} {'хобл', 'блд'}
topic_10
  WTF: {'лечения', 'железы'} {'крона', 'срк'}
topic_11
topic_12
  WTF: {'нейролептического', 'отмены', 'эпилепсии', '16'} {'туретта', 'альцгеймера', 'знс', 'дцп'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_13
  WTF: {'миндалин'} {'ige'}
topic_14
  WTF: {'гемофилия', 'кровотечений', 'вен'} {'виллебранда', 'viii', 'гит'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_15
  WTF: {'лимфома', 'миелоидного', 'циклина'} {'опл', 'd1', 'омл'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_16
topic_17
topic_18
  WTF: {'арахноидите', 'ишемического'} {'сдг', 'сак'}
topic_19
  WTF: {'кератоэпителин', 'кератансульфатов'} {'tgfbi', 'bcd'}
topic_20
  WTF: {'ожирения', 'ожирением', 'энурез'} {'dsm', 'мкб', 'commentedtext'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_21
topic_22
  WTF: {'нейросенсорная'} {'дб'}
topic_23
topic_24
topic_25
topic_26
  WTF: {'недостаточности'} {'т3'}
topic_27
topic_28
  WTF: {'обычно', 'две', 'анеуплоидия', 'также', 'хромосому', 'могут', 'мужчин'} {'магенис', 'xxyy', 'xxxy', 'фабри', 'xy', 'xx', 'смит'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_29
  WTF: {'пластины', 'фаланг'} {'дюпюитрена', 'мортона'}
topic_30
  WTF: {'содержание'} {'адг'}
topic_31
topic_32
topic_33
  WTF: {'конкременты', 'заболевания'} {'wnt3', 'жкб'}
topic_34
  WTF: {'гипокальциемический'} {'b12'}
topic_35
  WTF: {'аутосомно', 'больных', 'костного'} {'пмл', 'пвл', 'jc'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_36
topic_37
  WTF: {'системы', 'гиперкортицизм'} {'щж', 'аит'}
topic_38
  WTF: {'давление', 'гипертонический', 'сосудов', 'портальной', 'больных'} {'зг', 'ара', 'иапф', 'ад', 'аг'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_39
  WTF: {'миелоидные', 'клетки', 'выживаемость'} {'юинга', 'амс', 'капоши'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_40
  WTF: {'кишки', 'приона', 'прионные', 'головки', 'парапроктита'} {'prpsc', 'крейтцфельдта', 'prpc', 'prp', 'paragonimus'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_41
  WTF: {'эмболия'} {'вегенера'}
topic_42
  WTF: {'лечения', 'женщинам', 'маммография'} {'фоп', 'дф', 'фм'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_43
  WTF: {'10'} {'кпт'}
topic_44
  WTF: {'бензнидазол'} {'шагаса'}
topic_45
  WTF: {'случаев', 'моно', '50', 'артритом'} {'цог', 'b27', 'гкс', 'нпвп'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_46
  WTF: {'канала'} {'дгпж'}
topic_47
  WTF: {'невралгия'} {'гбн'}
topic_48
  WTF: {'клещей'} {'trombicula'}
topic_49
  WTF: {'изменения'} {'т4'}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f4052221850>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3d5314d040>}
{'perplexity': 46421.11328125, 'coherence_20': 1.4778297349484453, 'toplen_ptw': 1.4996038857101455, 'diversity_euclidean': 0.034097937187359255, 'diversity_jensenshannon': 0.7168915819239785, 'diversity_hellinger': 0.8505552840526284, 'diversity_cosine': 0.7955505469228155, 'fair_ppl_free': 6006.765625, 'fair_ppl_fix': 42289.36328125, 'unfair_ppl_banklike': 46421.11328125}
{'num_topics': 51, 'num_common_words': 101018, 'num_model_words': 127266, 'num_bt_words': 115899, 'top_diffs': [{'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}]}
19
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
  WTF: {'болезнь'} {'вич'}
topic_2
  WTF: {'quote', 'аутизма', 'часто', 'например'} {'dsm', 'начало_цитаты', 'мкб', 'аспергера'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_3
topic_4
  WTF: {'является'} {'спнка'}
topic_5
  WTF: {'мозга'} {'гисо'}
topic_6
  WTF: {'синдромом', 'мутации'} {'эчб', 'мдс'}
topic_7
topic_8
  WTF: {'группы', 'наследуется'} {'gm2', 'iga'}
topic_9
  WTF: {'перегородки', 'пучка', 'кровообращения', 'левой'} {'гиса', 'фп', 'ибс', 'экг'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_10
  WTF: {'кашель', 'воздуха'} {'хобл', 'блд'}
topic_11
  WTF: {'лечения', 'болезни'} {'крона', 'срк'}
topic_12
  WTF: {'гемофилия', 'анемия', 'кровотечений'} {'виллебранда', 'viii', 'гит'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_13
topic_14
  WTF: {'хороидеремии', 'кератансульфатов'} {'кератоэпителин', 'tgfbi'}
topic_15
  WTF: {'жидкости', 'течение'} {'сдг', 'сак'}
topic_16
topic_17
  WTF: {'ожирения', 'ожирением', 'энурез'} {'dsm', 'мкб', 'commentedtext'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_18
  WTF: {'пиелонефрита'} {'dq2'}
topic_19
topic_20
  WTF: {'головы', 'болезнь'} {'альцгеймера', 'дцп'}
topic_21
topic_22
  WTF: {'нейросенсорная'} {'дб'}
topic_23
topic_24
topic_25
  WTF: {'крови', 'abl', 'химиотерапии', 'транс', 'стволовых'} {'хмл', 'опл', 'омл', 'atra', 'фаб'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_26
  WTF: {'терапии'} {'знс'}
topic_27
topic_28
  WTF: {'обычно', 'две', 'анеуплоидия', 'также', 'хромосому', 'могут', 'мужчин'} {'магенис', 'xxyy', 'xxxy', 'фабри', 'xy', 'xx', 'смит'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_29
  WTF: {'содержание'} {'адг'}
topic_30
  WTF: {'англ', 'экспрессии', 'клетках', 'больных'} {'хлл', 'd1', 'нхл', 'ходжкина'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_31
  WTF: {'анестезией', 'анестетика'} {'дюпюитрена', 'мортона'}
topic_32
  WTF: {'крови', 'каждые', 'почек', 'лёгочной', 'вен', 'сосудов', 'эмфиземы', 'артерии'} {'иэ', 'св', 'мпа', 'рейно', 'цф', 'анца', 'тэла', 'гпа'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_33
  WTF: {'организма', 'ти'} {'жкб', 'аит'}
topic_34
topic_35
topic_36
  WTF: {'крапивницы'} {'ige'}
topic_37
  WTF: {'сосудов', 'излучения', 'коже'} {'боуэна', 'wnt3', 'хлб'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_38
  WTF: {'других'} {'пвл'}
topic_39
  WTF: {'давление', 'гипертонический', 'сосудов', 'портальной', 'больных'} {'зг', 'ара', 'иапф', 'ад', 'аг'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_40
  WTF: {'паука'} {'buthidae'}
topic_41
topic_42
  WTF: {'кишки', 'приона', 'прионные', 'головки', 'парапроктита'} {'prpsc', 'крейтцфельдта', 'prpc', 'prp', 'paragonimus'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_43
  WTF: {'тел'} {'шморля'}
topic_44
  WTF: {'саркоидоз', 'остеогенная', 'миелоидных'} {'юинга', 'амс', 'капоши'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_45
  WTF: {'бензнидазол'} {'шагаса'}
topic_46
  WTF: {'случаев', 'моно', '50', 'артритом'} {'цог', 'b27', 'гкс', 'нпвп'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_47
  WTF: {'10'} {'кпт'}
topic_48
  WTF: {'клещей'} {'trombicula'}
topic_49
  WTF: {'канала'} {'дгпж'}
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3cb8a5e6d0>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
  WTF: {'болезнь'} {'вич'}
topic_2
  WTF: {'quote', 'аутизма', 'часто', 'например'} {'dsm', 'начало_цитаты', 'мкб', 'аспергера'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_3
topic_4
  WTF: {'является'} {'спнка'}
topic_5
  WTF: {'мозга'} {'гисо'}
topic_6
  WTF: {'синдромом', 'мутации'} {'эчб', 'мдс'}
topic_7
topic_8
  WTF: {'группы', 'наследуется'} {'gm2', 'iga'}
topic_9
  WTF: {'перегородки', 'пучка', 'кровообращения', 'левой'} {'гиса', 'фп', 'ибс', 'экг'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_10
  WTF: {'кашель', 'воздуха'} {'хобл', 'блд'}
topic_11
  WTF: {'лечения', 'болезни'} {'крона', 'срк'}
topic_12
  WTF: {'гемофилия', 'анемия', 'кровотечений'} {'виллебранда', 'viii', 'гит'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_13
topic_14
  WTF: {'хороидеремии', 'кератансульфатов'} {'кератоэпителин', 'tgfbi'}
topic_15
  WTF: {'жидкости', 'течение'} {'сдг', 'сак'}
topic_16
topic_17
  WTF: {'ожирения', 'ожирением', 'энурез'} {'dsm', 'мкб', 'commentedtext'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_18
  WTF: {'пиелонефрита'} {'dq2'}
topic_19
topic_20
  WTF: {'головы', 'болезнь'} {'альцгеймера', 'дцп'}
topic_21
topic_22
  WTF: {'нейросенсорная'} {'дб'}
topic_23
topic_24
topic_25
  WTF: {'крови', 'abl', 'химиотерапии', 'транс', 'стволовых'} {'хмл', 'опл', 'омл', 'atra', 'фаб'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_26
  WTF: {'терапии'} {'знс'}
topic_27
topic_28
  WTF: {'обычно', 'две', 'анеуплоидия', 'также', 'хромосому', 'могут', 'мужчин'} {'магенис', 'xxyy', 'xxxy', 'фабри', 'xy', 'xx', 'смит'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_29
  WTF: {'содержание'} {'адг'}
topic_30
  WTF: {'англ', 'экспрессии', 'клетках', 'больных'} {'хлл', 'd1', 'нхл', 'ходжкина'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_31
  WTF: {'анестезией', 'анестетика'} {'дюпюитрена', 'мортона'}
topic_32
  WTF: {'крови', 'каждые', 'почек', 'лёгочной', 'вен', 'сосудов', 'эмфиземы', 'артерии'} {'иэ', 'св', 'мпа', 'рейно', 'цф', 'анца', 'тэла', 'гпа'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_33
  WTF: {'организма', 'ти'} {'жкб', 'аит'}
topic_34
topic_35
topic_36
  WTF: {'крапивницы'} {'ige'}
topic_37
  WTF: {'сосудов', 'излучения', 'коже'} {'боуэна', 'wnt3', 'хлб'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_38
  WTF: {'других'} {'пвл'}
topic_39
  WTF: {'давление', 'гипертонический', 'сосудов', 'портальной', 'больных'} {'зг', 'ара', 'иапф', 'ад', 'аг'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_40
  WTF: {'паука'} {'buthidae'}
topic_41
topic_42
  WTF: {'кишки', 'приона', 'прионные', 'головки', 'парапроктита'} {'prpsc', 'крейтцфельдта', 'prpc', 'prp', 'paragonimus'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_43
  WTF: {'тел'} {'шморля'}
topic_44
  WTF: {'саркоидоз', 'остеогенная', 'миелоидных'} {'юинга', 'амс', 'капоши'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_45
  WTF: {'бензнидазол'} {'шагаса'}
topic_46
  WTF: {'случаев', 'моно', '50', 'артритом'} {'цог', 'b27', 'гкс', 'нпвп'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_47
  WTF: {'10'} {'кпт'}
topic_48
  WTF: {'клещей'} {'trombicula'}
topic_49
  WTF: {'канала'} {'дгпж'}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3b08e49520>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f405e22b220>}
{'perplexity': 46278.7578125, 'coherence_20': 1.4747495666597021, 'toplen_ptw': 1.4998679787132394, 'diversity_euclidean': 0.03270914355288536, 'diversity_jensenshannon': 0.7146472473983259, 'diversity_hellinger': 0.847744329969208, 'diversity_cosine': 0.7886641526952555, 'fair_ppl_free': 5870.7783203125, 'fair_ppl_fix': 45125.9921875, 'unfair_ppl_banklike': 46278.7578125}
{'num_topics': 51, 'num_common_words': 101018, 'num_model_words': 127266, 'num_bt_words': 115899, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}]}

In [38]:
1

1

In [39]:
! ls $SAVE_FOLDER

bertopic		      iterative_100000.json	 plsa_with_cohs.json
bertopic.json		      iterative2_100000000	 sparse_with_cohs.json
decorrelation_with_cohs.json  iterative2_100000000.json  tless_with_cohs.json
iterative_100000	      lda_with_cohs.json

In [40]:
! ls $SAVE_FOLDER/bertopic -alh

total 248K
drwxrwxr-x 2 alekseev_v mil_lab 4,0K июл 27 20:52 .
drwxrwxr-x 5 alekseev_v mil_lab 4,0K июл 27 20:52 ..
-rw-rw-r-- 1 alekseev_v mil_lab 9,9K июл 27 17:52 bertopic_0.json
-rw-rw-r-- 1 alekseev_v mil_lab 9,9K июл 27 19:27 bertopic_10.json
-rw-rw-r-- 1 alekseev_v mil_lab 9,9K июл 27 19:36 bertopic_11.json
-rw-rw-r-- 1 alekseev_v mil_lab 9,9K июл 27 19:46 bertopic_12.json
-rw-rw-r-- 1 alekseev_v mil_lab 9,9K июл 27 19:55 bertopic_13.json
-rw-rw-r-- 1 alekseev_v mil_lab 9,9K июл 27 20:04 bertopic_14.json
-rw-rw-r-- 1 alekseev_v mil_lab 9,9K июл 27 20:14 bertopic_15.json
-rw-rw-r-- 1 alekseev_v mil_lab 9,8K июл 27 20:23 bertopic_16.json
-rw-rw-r-- 1 alekseev_v mil_lab 9,9K июл 27 20:33 bertopic_17.json
-rw-rw-r-- 1 alekseev_v mil_lab 9,9K июл 27 20:42 bertopic_18.json
-rw-rw-r-- 1 alekseev_v mil_lab 9,9K июл 27 20:52 bertopic_19.json
-rw-rw-r-- 1 alekseev_v mil_lab 9,9K июл 27 18:01 bertopic_1.json
-rw-rw-r-- 1 alekseev_v mil_lab 9,9K июл 27 18:11 bertopic_2.json
-rw-rw-r-- 1 alekseev_v mil_lab 9,9K июл 27 18:21 bertopic_3.json
-rw-rw-r-- 1 alekseev_v mil_lab 9,9K июл 27 18:30 bertopic_4.json
-rw-rw-r-- 1 alekseev_v mil_lab 9,9K июл 27 18:40 bertopic_5.json
-rw-rw-r-- 1 alekseev_v mil_lab 9,9K июл 27 18:49 bertopic_6.json
-rw-rw-r-- 1 alekseev_v mil_lab 9,9K июл 27 18:59 bertopic_7.json
-rw-rw-r-- 1 alekseev_v mil_lab 9,9K июл 27 19:08 bertopic_8.json
-rw-rw-r-- 1 alekseev_v mil_lab 9,8K июл 27 19:18 bertopic_9.json

In [41]:
! cat $SAVE_FOLDER/bertopic/bertopic_0.json

{
    "scores": {
        "perplexity": 46747.03125,
        "coherence_20": 1.4507651354753799,
        "toplen_ptw": 1.4953236517968609,
        "diversity_euclidean": 0.03512343743136369,
        "diversity_jensenshannon": 0.7224571063507161,
        "diversity_hellinger": 0.8572494990821297,
        "diversity_cosine": 0.80604851219669,
        "fair_ppl_free": 6122.6025390625,
        "fair_ppl_fix": 42166.61328125,
        "unfair_ppl_banklike": 46747.03125
    },
    "topic_coherences": {
        "0": 0.49255303142557155,
        "1": 0.48653028598445114,
        "2": 1.2366261616419016,
        "3": 0.6890030288355441,
        "4": 1.0751905567276814,
        "5": 1.5320656046065961,
        "6": 1.7967012667468176,
        "7": 0.9412092727717618,
        "8": 1.3940961353128882,
        "9": 1.4988855334994744,
        "10": 1.0623824902505083,
        "11": 1.0204016455954235,
        "12": 1.3235546468639876,
        "13": 1.7110040697949838,
        "14": 0.72014693381834,
        "15": 1.4831702722005145,
        "16": 1.4050305900586646,
        "17": 1.5752013659119144,
        "18": 1.5378386716489747,
        "19": 1.0050863017667986,
        "20": 1.676880369528394,
        "21": 2.4309053899154245,
        "22": 1.9147528699249545,
        "23": 1.9366335181864525,
        "24": 3.0386897632767185,
        "25": 1.4243852715388614,
        "26": 1.7555253518154736,
        "27": 0.7907551280448927,
        "28": 2.5753541929519805,
        "29": 1.397257812212889,
        "30": 0.7629509285672815,
        "31": 0.6007186906449545,
        "32": 0.9338347975479735,
        "33": 3.097882394755202,
        "34": 1.733143633789119,
        "35": 1.2552601816310518,
        "36": 1.1023418642012563,
        "37": 1.8212750651734493,
        "38": 1.266902430121246,
        "39": 2.243484842704819,
        "40": 1.7203280329108894,
        "41": 1.5082090385390095,
        "42": 1.2636706515647065,
        "43": 2.0383446921068638,
        "44": 1.5850561997558044,
        "45": 1.8156573057601184,
        "46": 1.7454780082095436,
        "47": 0.7423399874422104,
        "48": 1.1937695460442457,
        "49": 1.1797909494404002
    },
    "topic_coherences_toplen_ptw": {
        "0": 13.648054315371935,
        "1": 1.8267127879993914,
        "2": 2.4904639343529906,
        "3": 1.9537937986354312,
        "4": 1.57375924264307,
        "5": 1.8144941393405316,
        "6": 1.4391575085571253,
        "7": 1.5047956712402895,
        "8": 1.6405787465928519,
        "9": 1.3764920890378218,
        "10": 1.536362618171972,
        "11": 1.389774903202323,
        "12": 1.5151241946874918,
        "13": 1.4211222106214219,
        "14": 1.3107821735339438,
        "15": 2.013690181813252,
        "16": 1.4280058088302667,
        "17": 1.909920838766324,
        "18": 1.3836948316752875,
        "19": 1.2472987599158716,
        "20": 1.2685563808210736,
        "21": 1.4031574323469063,
        "22": 1.4962323707102727,
        "23": 1.2366200220499173,
        "24": 1.377756548697804,
        "25": 1.2751437500815161,
        "26": 1.476702302914049,
        "27": 1.7588785052743579,
        "28": 1.7448222363436885,
        "29": 1.669090485932979,
        "30": 1.3054435782949625,
        "31": 1.3420979299344327,
        "32": 1.257557777801724,
        "33": 1.662261713289709,
        "34": 1.941166883801922,
        "35": 1.3686483882601583,
        "36": 1.3908432541359825,
        "37": 1.313340436206376,
        "38": 1.6864326209858724,
        "39": 1.2551654711775697,
        "40": 1.3009428350455465,
        "41": 1.8321715824469398,
        "42": 1.4693198270831438,
        "43": 1.6450832253993446,
        "44": 1.6008491361500168,
        "45": 1.4944149328834493,
        "46": 1.3086386229081541,
        "47": 2.0635248866246214,
        "48": 1.6484072405677375,
        "49": 1.5662137778049745
    },
    "stats": {
        "num_topics": 51,
        "num_common_words": 101018,
        "num_model_words": 127266,
        "num_bt_words": 115899,
        "top_diffs": [
            {
                "total": 2,
                "lost_bt": 1,
                "lost_model": 1
            },
            {
                "total": 0,
                "lost_bt": 0,
                "lost_model": 0
            },
            {
                "total": 8,
                "lost_bt": 4,
                "lost_model": 4
            },
            {
                "total": 0,
                "lost_bt": 0,
                "lost_model": 0
            },
            {
                "total": 2,
                "lost_bt": 1,
                "lost_model": 1
            },
            {
                "total": 4,
                "lost_bt": 2,
                "lost_model": 2
            },
            {
                "total": 0,
                "lost_bt": 0,
                "lost_model": 0
            },
            {
                "total": 2,
                "lost_bt": 1,
                "lost_model": 1
            },
            {
                "total": 2,
                "lost_bt": 1,
                "lost_model": 1
            },
            {
                "total": 4,
                "lost_bt": 2,
                "lost_model": 2
            },
            {
                "total": 0,
                "lost_bt": 0,
                "lost_model": 0
            },
            {
                "total": 6,
                "lost_bt": 3,
                "lost_model": 3
            },
            {
                "total": 6,
                "lost_bt": 3,
                "lost_model": 3
            },
            {
                "total": 0,
                "lost_bt": 0,
                "lost_model": 0
            },
            {
                "total": 0,
                "lost_bt": 0,
                "lost_model": 0
            },
            {
                "total": 4,
                "lost_bt": 2,
                "lost_model": 2
            },
            {
                "total": 0,
                "lost_bt": 0,
                "lost_model": 0
            },
            {
                "total": 6,
                "lost_bt": 3,
                "lost_model": 3
            },
            {
                "total": 8,
                "lost_bt": 4,
                "lost_model": 4
            },
            {
                "total": 0,
                "lost_bt": 0,
                "lost_model": 0
            },
            {
                "total": 0,
                "lost_bt": 0,
                "lost_model": 0
            },
            {
                "total": 2,
                "lost_bt": 1,
                "lost_model": 1
            },
            {
                "total": 2,
                "lost_bt": 1,
                "lost_model": 1
            },
            {
                "total": 0,
                "lost_bt": 0,
                "lost_model": 0
            },
            {
                "total": 0,
                "lost_bt": 0,
                "lost_model": 0
            },
            {
                "total": 2,
                "lost_bt": 1,
                "lost_model": 1
            },
            {
                "total": 4,
                "lost_bt": 2,
                "lost_model": 2
            },
            {
                "total": 14,
                "lost_bt": 7,
                "lost_model": 7
            },
            {
                "total": 0,
                "lost_bt": 0,
                "lost_model": 0
            },
            {
                "total": 2,
                "lost_bt": 1,
                "lost_model": 1
            },
            {
                "total": 0,
                "lost_bt": 0,
                "lost_model": 0
            },
            {
                "total": 2,
                "lost_bt": 1,
                "lost_model": 1
            },
            {
                "total": 2,
                "lost_bt": 1,
                "lost_model": 1
            },
            {
                "total": 0,
                "lost_bt": 0,
                "lost_model": 0
            },
            {
                "total": 4,
                "lost_bt": 2,
                "lost_model": 2
            },
            {
                "total": 0,
                "lost_bt": 0,
                "lost_model": 0
            },
            {
                "total": 18,
                "lost_bt": 9,
                "lost_model": 9
            },
            {
                "total": 6,
                "lost_bt": 3,
                "lost_model": 3
            },
            {
                "total": 4,
                "lost_bt": 2,
                "lost_model": 2
            },
            {
                "total": 10,
                "lost_bt": 5,
                "lost_model": 5
            },
            {
                "total": 2,
                "lost_bt": 1,
                "lost_model": 1
            },
            {
                "total": 4,
                "lost_bt": 2,
                "lost_model": 2
            },
            {
                "total": 2,
                "lost_bt": 1,
                "lost_model": 1
            },
            {
                "total": 2,
                "lost_bt": 1,
                "lost_model": 1
            },
            {
                "total": 2,
                "lost_bt": 1,
                "lost_model": 1
            },
            {
                "total": 8,
                "lost_bt": 4,
                "lost_model": 4
            },
            {
                "total": 2,
                "lost_bt": 1,
                "lost_model": 1
            },
            {
                "total": 4,
                "lost_bt": 2,
                "lost_model": 2
            },
            {
                "total": 0,
                "lost_bt": 0,
                "lost_model": 0
            },
            {
                "total": 4,
                "lost_bt": 2,
                "lost_model": 2
            }
        ]
    }
}