In [1]:
import os
import json
import shutil
import sys

import numpy as np
import scipy

In [2]:
sys.path.insert(0, '../OptimalNumberOfTopics')

In [3]:
import topnum

from topnum.scores.perplexity_score import PerplexityScore
from topnum.scores.diversity_score import DiversityScore, KNOWN_METRICS
from topnum.model_constructor import init_model_from_family, KnownModel, PARAMS_EXPLORED, init_plsa

In [4]:
import artm
from artm import ARTM, Dictionary

import topicnet
from topicnet.cooking_machine.dataset import Dataset
from topicnet.cooking_machine.models import (
    BaseScore as BaseTopicNetScore,
    TopicModel
)
from topicnet.cooking_machine.models.base_regularizer import BaseRegularizer
from topicnet.cooking_machine.models.thetaless_regularizer import (
    dataset2sparse_matrix,
)

from topicnet.cooking_machine.models.topic_model import ARTM_NINE
from topicnet.cooking_machine.models.base_regularizer import BaseRegularizer
from topicnet.viewers.top_documents_viewer import TopDocumentsViewer
from topicnet.viewers.top_tokens_viewer import TopTokensViewer
from topicnet.cooking_machine.model_constructor import (
    add_standard_scores,
    create_default_topics,
    count_vocab_size,
    init_model,
)
from topicnet.cooking_machine.rel_toolbox_lite import (
    count_vocab_size,
    modality_weight_rel2abs,
    transform_regularizer,
)


import numpy as np
import pandas as pd
from pandas import DataFrame
from scipy.spatial.distance import cdist

import os
import tempfile
import warnings
from copy import deepcopy
from typing import Dict, List, Optional

In [6]:
NUM_TOPICS = 20  # TODO: this value does not affect anything

NUM_ITERATIONS = 5
NUM_TOP_TOKENS = 20
NUM_TRAINS = 20

In [7]:
BERTOPIC_FOLDER_PATH = '/data_mil/shared/CompressaAI/BERTopic'

In [8]:
! ls $BERTOPIC_FOLDER_PATH

results  results50

In [9]:
! ls $BERTOPIC_FOLDER_PATH/results

20newsgroups  mkb10  postnauka	rtlwikiperson  ruwikigood

In [10]:
RESULTS_FOLDER_PATH = os.path.join(BERTOPIC_FOLDER_PATH, 'results', 'rtlwikiperson')

In [11]:
RESULTS_FOLDER_PATH

'/data_mil/shared/CompressaAI/BERTopic/results/rtlwikiperson'

In [36]:
! ls results50

20newsgroups  mkb10  postnauka	rtlwikiperson  ruwikigood

In [37]:
SAVE_FOLDER = os.path.join('results', 'rtlwikiperson')

In [38]:
SAVE_FOLDER

'results/rtlwikiperson'

In [39]:
! ls $SAVE_FOLDER

ablation_study			    iterative2_1000000000
decorrelation.json		    iterative2_10000000000
iterative_100000		    iterative2_10000000000.json
iterative_1000000		    iterative2_1000000000.json
iterative_10000000		    iterative2_100000000.json
iterative_10000000_unfinished.json  lda.json
iterative_1000000.json		    plsa.json
iterative_100000.json		    sparse.json
iterative2_100000000		    tless.json

In [12]:
! ls $RESULTS_FOLDER_PATH

0  1  10  11  12  13  14  15  16  17  18  19  2  3  4  5  6  7	8  9

In [13]:
! ls $RESULTS_FOLDER_PATH/0

dataset.csv  phi.csv  top_words.json

In [14]:
dataset = Dataset(
    f'{RESULTS_FOLDER_PATH}/0/dataset.csv',
)

dataset.get_possible_modalities()

{'@lemmatized'}

In [16]:
MAIN_MODALITY = '@lemmatized'

In [17]:
def calc_doc_occurrences(dataset, modality):
    """
    :param n_dw_matrix: sparse document-word matrix, shape is D x W
    :return: sparse matrix of co-occurrences

    doc_occurrences[w1, w2] = the number of the documents
    where there are w1 and w2
    """
    n_dw_matrix = dataset2sparse_matrix(dataset, modality, modalities_to_use=[modality])
    matrix = (scipy.sparse.csc_matrix(n_dw_matrix) > 0).astype(int)
    co_occurrences = matrix.T * matrix

    return co_occurrences.diagonal(), co_occurrences


def create_pmi_top_function(
    doc_occurrences, doc_co_occurrences,
    documents_number, top_sizes,
    topic_indices,
    co_occurrences_smooth=1.
):
    """
    :param doc_occurrences: array of doc occurrences of words
    :param doc_co_occurrences: sparse matrix of doc co-occurrences of words
    :param documents_number: number of the documents
    :param top_sizes: list of top values to calculate top-pmi for
    :param co_occurrences_smooth: constant to smooth co-occurrences in log
    :return: function which takes phi and theta and returns
    pair of two arrays: pmi-s of the tops and ppmi-s of the tops

    pmi[i] - pmi(top of size top_sizes[i])
    ppmi[i] - ppmi(top of size top_sizes[i])

    pmi(words) = sum_{u in words, v in words, u != v}
    log(
        (doc_co_occurrences[u, v] * documents_number + co_occurrences_smooth)
        / doc_occurrences[u] / doc_occurrences[v]
    )

    ppmi(words) = sum_{u in words, v in words, u != v}
    max(log(
        (doc_co_occurrences[u, v] * documents_number + co_occurrences_smooth)
        / doc_occurrences[u] / doc_occurrences[v]
    ), 0)

    """
    def func(phi):
        _T, W = phi.shape
        T = len(topic_indices)

        max_top_size = max(top_sizes)
        topic_pmis, topic_ppmis = dict(), dict()
        pmi, ppmi = np.zeros(max_top_size), np.zeros(max_top_size)
        tops = np.argpartition(phi, -max_top_size, axis=1)[:, -max_top_size:]
        
        for t in topic_indices:
            top = sorted(tops[t], key=lambda w: - phi[t, w])
            co_occurrences = doc_co_occurrences[top, :][:, top].todense()
            occurrences = doc_occurrences[top]
            values = np.log(
                (co_occurrences * documents_number + co_occurrences_smooth)
                / (occurrences[:, np.newaxis] * occurrences[np.newaxis, :] + co_occurrences_smooth)
            )
            diag = np.diag_indices(len(values))
            # values.cumsum(axis=0).cumsum(axis=1)[diag] - values[diag].cumsum()

            current_pmi = np.array(
               values.cumsum(axis=0).cumsum(axis=1)[diag] - values[diag].cumsum()
            ).ravel()
            topic_pmis[t] = current_pmi
            pmi += current_pmi

            values[values < 0.] = 0.
            current_ppmi = np.array(
               values.cumsum(axis=0).cumsum(axis=1)[diag] - values[diag].cumsum()
            ).ravel()
            topic_ppmis[t] = current_ppmi
            ppmi += current_ppmi
            
        sizes = np.arange(2, max_top_size + 1)
        pmi[1:] /= (T * sizes * (sizes - 1))
        ppmi[1:] /= (T * sizes * (sizes - 1))
        indices = np.array(top_sizes) - 1

        for t in topic_indices:
            topic_pmis[t][1:] /= (sizes * (sizes - 1))
            topic_ppmis[t][1:] /= (sizes * (sizes - 1))

        result_topic_pmis = {t: p[indices] for t, p in topic_pmis.items()}
        result_topic_ppmis = {t: p[indices] for t, p in topic_ppmis.items()}

        return pmi[indices], ppmi[indices], result_topic_pmis, result_topic_ppmis

    return func

In [18]:
%%time

occurences, co_occurences = calc_doc_occurrences(dataset, MAIN_MODALITY)

CPU times: user 21.8 s, sys: 1.43 s, total: 23.3 s
Wall time: 23 s

In [19]:
co_occurences.shape

(155407, 155407)

In [20]:
calc_pmi = create_pmi_top_function(
    occurences, co_occurences,
    dataset.get_dataset().shape[0], [20],
    topic_indices=[0, 1, 2],
    co_occurrences_smooth=1e-2,
)

In [21]:
class TopTokenCoherence(BaseTopicNetScore):
    def __init__(self, name, func):
        super().__init__()

        self._name = name
        self.calc_pmi = func

    def call(self, model: TopicModel):
        values = self.calc_pmi(model.get_phi_dense()[0].T)

        return values[1]

    def call_by_topic(self, model: TopicModel):
        values = self.calc_pmi(model.get_phi_dense()[0].T)

        return values[3]

In [22]:
def view_model(
        topic_model,
        dataset,
        num_top_tokens: int = 5,
        top_tokens_method: str = 'phi',
        num_topics: Optional[int] = 5,  # we do not want to fill the whole .ipynb notebook with topics...
        ):
    top_tok_viewer = TopTokensViewer(
        topic_model, num_top_tokens=num_top_tokens, method=top_tokens_method
    )
    top_doc_viewer = TopDocumentsViewer(topic_model, dataset=dataset)
    top_docs = top_doc_viewer.view()

    if num_topics is None:
        num_topics = len(topic_model.topic_names)

    for topic_name in topic_model.topic_names[:num_topics]:
        topic_top_toks = top_tok_viewer.to_html(topic_names=[topic_name])
        topic_top_docs = top_docs[topic_name]
        display_html(topic_top_toks, raw=True)
        display(topic_top_docs)

In [23]:
class FastFixPhiRegularizer(BaseRegularizer):
    _VERY_BIG_TAU = 10 ** 9

    def __init__(self, name: str, topic_names: List[str], parent_model=None, parent_phi=None, words=None):
        super().__init__(name, tau=self._VERY_BIG_TAU)

        self._topic_names = topic_names
        self._topic_indices = None
        self._words = words
        self._word_indices = None
        self._parent_model = parent_model
        self._parent_phi = parent_phi

    def grad(self, pwt, nwt):
        # print('Fixing')

        rwt = np.zeros_like(pwt)

        if self._parent_phi is not None:
            parent_phi = self._parent_phi
            vals = parent_phi.values
        else:
            assert False

            parent_phi = self._parent_model.get_phi()
            vals = parent_phi.values[:, self._topic_indices]

        if self._word_indices is None:
            assert vals.shape[0] == rwt.shape[0], (vals.shape[0], rwt.shape[0])
        else:
            assert vals.shape[0] == len(self._word_indices)

        assert vals.shape[1] == len(self._topic_indices)

        if self._word_indices is None:
            rwt[:, self._topic_indices] += vals
        else:
            # print(len(self._word_indices), len(self._topic_indices), rwt.shape, vals.shape)
            # print(self._word_indices[:3], self._topic_indices[:3])
            # print(rwt[np.ix_(self._word_indices, self._topic_indices)].shape, vals.shape)

            # https://github.com/numpy/numpy/issues/5574
            # https://github.com/numpy/numpy/issues/13255
            rwt[np.ix_(self._word_indices, self._topic_indices)] += vals

            # print(np.ix_(self._word_indices, self._topic_indices)[:3])

        return self.tau * rwt

    def attach(self, model):
        super().attach(model)
        
        phi = self._model.get_phi()
        self._topic_indices = [
            phi.columns.get_loc(topic_name)
            for topic_name in self._topic_names
        ]

        if self._words is not None:
            self._word_indices = [
                # phi.index.get_loc(w) for w in self._words
                int(phi.index.get_loc(w)) for w in self._words
            ]

            # print(f'!!! Word indices: {self._word_indices}')

In [24]:
def fit_and_compute_scores(model, dataset, target_topic_indices=None, custom_regularizers=None):
    print(custom_regularizers)

    model._fit(dataset.get_batch_vectorizer(), num_iterations=NUM_ITERATIONS, custom_regularizers=custom_regularizers)

    score_values = {
        'perplexity': model.scores[f'PerplexityScore{MAIN_MODALITY}'][-1],
    }

    phi = model.get_phi()

    # Currently all topics are taken into account

    if target_topic_indices is None:
        target_topic_indices = list(range(NUM_TOPICS))  # phi.columns.get_loc()

    target_topic_names = [phi.columns[i] for i in target_topic_indices]

    top = NUM_TOP_TOKENS
    coherence_score = TopTokenCoherence(
        name=f'coherence_{top}',
        func=create_pmi_top_function(
            occurences, co_occurences,
            dataset.get_dataset().shape[0], [top],
            topic_indices=target_topic_indices,
            co_occurrences_smooth=1e-2,
        )
    )

    value = coherence_score.call(model)
    score_values[coherence_score._name] = value
    topic_coherences = coherence_score.call_by_topic(model)
    topic_coherences = {t: float(v) for t, v in topic_coherences.items()}

    diversity_scores = [
        DiversityScore(
            name=f'diversity_{metric}',
            metric=metric,
            topic_names=target_topic_names,
            class_ids=MAIN_MODALITY,
        )
    
        for metric in KNOWN_METRICS
    ]
    
    for score in diversity_scores:
        value = score.call(model)
        score_values[score._name] = value

    return {
        'scores': score_values,
        'topic_coherences': topic_coherences,
    }

In [25]:
def init_model_from_family(
        family: str or KnownModel,
        dataset: Dataset,
        main_modality: str,
        num_topics: int,
        seed: int,
        specific_topic_names = None,
        modalities_to_use: List[str] = None,
        num_processors: int = 3,
        model_params: dict = None,
):
    """
    Returns
    -------
    model: TopicModel() instance
    """
    if isinstance(family, KnownModel):
        family = family.value

    if modalities_to_use is None:
        modalities_to_use = [main_modality]

    custom_regs = {}

    if family == "LDA":
        model = init_lda(
            dataset, modalities_to_use, main_modality, num_topics, model_params
        )
    elif family == "PLSA":
        model = init_plsa(
            dataset, modalities_to_use, main_modality, num_topics
        )
    elif family == "TARTM":
        model, custom_regs = init_thetaless(
            dataset, modalities_to_use, main_modality, num_topics, model_params
        )
    elif family == "sparse":
        model = init_bcg_sparse_model(
            dataset, modalities_to_use, main_modality, num_topics, 1, model_params
        )
    elif family == "decorrelation":
        model = init_decorrelated_plsa(
            dataset, modalities_to_use, main_modality, num_topics, model_params
        )
    elif family == "ARTM":
        model = init_baseline_artm(
            dataset, modalities_to_use, main_modality, num_topics, 1, specific_topic_names, model_params
        )
    else:
        raise ValueError(f'family: {family}')

    model.num_processors = num_processors

    if seed is not None:
        model.seed = seed

    dictionary = dataset.get_dictionary()

    # TODO: maybe this cycle is not necessary
    for modality in dataset.get_possible_modalities():
        if modality not in modalities_to_use:
            dictionary.filter(class_id=modality, max_df=0, inplace=True)

    model.initialize(dictionary)
    add_standard_scores(model, dictionary, main_modality=main_modality,
                        all_modalities=modalities_to_use)

    model = TopicModel(
        artm_model=model,
        custom_regularizers=custom_regs
    )

    return model


def init_bcg_sparse_model(
        dataset,
        modalities_to_use,
        main_modality,
        specific_topics,
        bcg_topics,
        specific_topic_names = None,
        model_params: dict = None
):
    """
    Creates simple artm model with standard scores.

    Parameters
    ----------
    dataset : Dataset
    modalities_to_use : list of str or dict
    main_modality : str
    specific_topics : int
    bcg_topics : int

    Returns
    -------
    model: artm.ARTM() instance
    """
    if model_params is None:
        model_params = dict()

    model = init_plsa(
        dataset, modalities_to_use, main_modality, specific_topics, bcg_topics
    )
    background_topic_names = model.topic_names[-bcg_topics:]

    if specific_topic_names is None:
        print('No spec topics')
        specific_topic_names = model.topic_names[:-bcg_topics]

    dictionary = dataset.get_dictionary()
    baseline_class_ids = {class_id: 1 for class_id in modalities_to_use}
    data_stats = count_vocab_size(dictionary, baseline_class_ids)

    # all coefficients are relative
    regularizers = [
        artm.SmoothSparsePhiRegularizer(
             name='smooth_phi_bcg',
             topic_names=background_topic_names,
             tau=model_params.get("smooth_bcg_tau", 0.1),
             class_ids=[main_modality],
        ),
        artm.SmoothSparseThetaRegularizer(
             name='smooth_theta_bcg',
             topic_names=background_topic_names,
             tau=model_params.get("smooth_bcg_tau", 0.1),
        ),
        artm.SmoothSparsePhiRegularizer(
             name='sparse_phi_sp',
             topic_names=specific_topic_names,
             tau=model_params.get("sparse_sp_tau", -0.05),
             class_ids=[main_modality],
            ),
        artm.SmoothSparseThetaRegularizer(
             name='sparse_theta_sp',
             topic_names=specific_topic_names,
             tau=model_params.get("sparse_sp_tau", -0.05),
        ),
    ]
    for reg in regularizers:
        model.regularizers.add(transform_regularizer(
            data_stats,
            reg,
            model.class_ids,
            n_topics=len(reg.topic_names)
        ))

    return model


def init_baseline_artm(
        dataset,
        modalities_to_use,
        main_modality,
        num_topics,
        bcg_topics,
        specific_topic_names = None,
        model_params: dict = None,
):
    """
    Creates simple artm model with standard scores.

    Parameters
    ----------
    dataset : Dataset
    modalities_to_use : list of str
    main_modality : str
    num_topics : int

    Returns
    -------
    model: artm.ARTM() instance
    """
    if model_params is None:
        model_params = dict()

    model = init_bcg_sparse_model(
        dataset, modalities_to_use, main_modality, num_topics, bcg_topics, specific_topic_names, model_params
    )

    if specific_topic_names is None:
        print('No spec topics')
        specific_topic_names = model.topic_names[:-bcg_topics]

    model.regularizers.add(
        artm.DecorrelatorPhiRegularizer(
            gamma=0,
            tau=model_params.get('decorrelation_tau', 0.01),
            name='decorrelation',
            topic_names=specific_topic_names,
            class_ids=modalities_to_use,
        )
    )

    return model

In [26]:
TOPIC_INDICES = list(range(NUM_TOPICS))

In [27]:
TOPIC_INDICES

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [28]:
phi0 = pd.read_csv(f'{RESULTS_FOLDER_PATH}/0/phi.csv', index_col=0)

In [29]:
phi0.head()

,background_1,topic_0,topic_1,topic_2,topic_3,topic_4,topic_5,topic_6,topic_7,topic_8,...,topic_10,topic_11,topic_12,topic_13,topic_14,topic_15,topic_16,topic_17,topic_18,topic_19
00,0.00000,0.000000,0.000055,0.0,0.000044,0.000067,0.0,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.001207,0.00000,0.0,0.0,0.0,0.0,0.0
000,0.00000,0.000115,0.000000,0.0,0.000000,0.000069,0.0,0.000172,0.000236,0.000000,...,0.0,0.0,0.0,0.000000,0.00024,0.0,0.0,0.0,0.0,0.0
0000030719,0.00000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000105,...,0.0,0.0,0.0,0.000000,0.00000,0.0,0.0,0.0,0.0,0.0
0001,0.00000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.000000,0.00000,0.0,0.0,0.0,0.0,0.0
000200027x,0.00005,0.000000,0.000000,0.0,0.000149,0.000000,0.0,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.000000,0.00000,0.0,0.0,0.0,0.0,0.0

In [30]:
phi0.set_index([[MAIN_MODALITY] * len(phi0.index), phi0.index], inplace=True)

In [31]:
phi0.head()

                        background_1   topic_0   topic_1  topic_2   topic_3  \
@lemmatized 00               0.00000  0.000000  0.000055      0.0  0.000044
            000              0.00000  0.000115  0.000000      0.0  0.000000
            0000030719       0.00000  0.000000  0.000000      0.0  0.000000
            0001             0.00000  0.000000  0.000000      0.0  0.000000
            000200027x       0.00005  0.000000  0.000000      0.0  0.000149

                         topic_4  topic_5   topic_6   topic_7   topic_8  ...  \
@lemmatized 00          0.000067      0.0  0.000000  0.000000  0.000000  ...
            000         0.000069      0.0  0.000172  0.000236  0.000000  ...
            0000030719  0.000000      0.0  0.000000  0.000000  0.000105  ...
            0001        0.000000      0.0  0.000000  0.000000  0.000000  ...
            000200027x  0.000000      0.0  0.000000  0.000000  0.000000  ...

                        topic_10  topic_11  topic_12  topic_13  topic_14  \
@lemmatized 00               0.0       0.0       0.0  0.001207   0.00000
            000              0.0       0.0       0.0  0.000000   0.00024
            0000030719       0.0       0.0       0.0  0.000000   0.00000
            0001             0.0       0.0       0.0  0.000000   0.00000
            000200027x       0.0       0.0       0.0  0.000000   0.00000

                        topic_15  topic_16  topic_17  topic_18  topic_19
@lemmatized 00               0.0       0.0       0.0       0.0       0.0
            000              0.0       0.0       0.0       0.0       0.0
            0000030719       0.0       0.0       0.0       0.0       0.0
            0001             0.0       0.0       0.0       0.0       0.0
            000200027x       0.0       0.0       0.0       0.0       0.0

[5 rows x 21 columns]

In [32]:
DIFF_THRESHOLD = 2

In [33]:
def check_top_words(phi, top_words):
    diffs = []

    for t, topic_top_words in top_words.items():
        if t == 'background_1':
            print(f'Skipping background topic: {t}.')

            continue

        print(t)
        # print(top_words)
    
        top_phi = set(phi[t].sort_values(ascending=False)[:NUM_TOP_TOKENS].index.get_level_values(1))
        top_bt = set([p[0] for p in topic_top_words])
    
        if top_phi == top_bt:
            diffs.append(
                {
                    'total': 0,
                    'lost_bt': 0,
                    'lost_model': 0,
                }
            )
        else:
            diff1 = top_phi.difference(top_bt)
            diff2 = top_bt.difference(top_phi)
    
            print('  WTF:', diff1, diff2)
    
            if len(diff1) > DIFF_THRESHOLD:
                print(f'  WTF?!?!?', len(diff1))
    
            if len(diff2) > DIFF_THRESHOLD:
                print(f'  WTF?!?!?', len(diff2))

            diffs.append(
                {
                    'total': len(diff1 | diff2),
                    'lost_bt': len(diff2),
                    'lost_model': len(diff1),
                }
            )

    return diffs

In [34]:
def init_model_and_phi(num_topics, dataset, phi0):
    model = init_model_from_family(
        family=KnownModel.PLSA,
        dataset=dataset,
        main_modality=MAIN_MODALITY,
        num_topics=num_topics,
        seed=0,
    )
    
    phi = model.get_phi()
    
    # assert phi.shape[1] == phi0.shape[1] - 1
    assert phi.shape[1] == num_topics
    assert phi.shape[1] in [phi0.shape[1], phi0.shape[1] - 1]
    
    common_words = list(set(phi.index).intersection(phi0.index))
    
    phi.loc[:, :] = 0

    if phi.shape[1] == phi0.shape[1]:
        target_topics = phi0.columns
    elif phi.shape[1] == phi0.shape[1] - 1:
        target_topics = phi.columns
    else:
        assert False

    # print(common_words, phi.index, phi0.index)

    phi.loc[common_words, :] += phi0.loc[common_words, target_topics]

    diff = set(phi0.columns).symmetric_difference(set(phi.columns))

    assert diff == {'background_1'} or diff == {'background_1', f'topic_{len(phi.columns) - 1}'}
    
    phi = phi / phi.sum(axis=0)

    return model, phi, common_words

In [41]:
results = []

is_results_loaded = False

save_file_path = os.path.join(
    SAVE_FOLDER, 'bertopic.json'
)

if os.path.isfile(save_file_path):
    results = json.loads(
        open(save_file_path).read()
    )
    is_results_loaded = True


singles_save_folder = os.path.join(
    SAVE_FOLDER, 'bertopic'
)

os.makedirs(singles_save_folder, exist_ok=True)


for seed in range(NUM_TRAINS):
    if is_results_loaded:
        continue

    print(seed)

    current_save_file_path = os.path.join(
        singles_save_folder, f'bertopic_{seed}.json'
    )

    if os.path.isfile(current_save_file_path):
        print(f'Already computed results: {current_save_file_path}. Loading and skipping...')

        result = json.loads(
            open(current_save_file_path).read()
        )
        results.append(result)

        continue

    seed_load_folder = os.path.join(RESULTS_FOLDER_PATH, str(seed))
    files = [f for f in os.listdir(seed_load_folder) if os.path.isfile(f'{seed_load_folder}/{f}')]
    
    assert len(files) == 3

    dataset = Dataset(
        f'{seed_load_folder}/dataset.csv',
    )
    phi0 = pd.read_csv(f'{seed_load_folder}/phi.csv', index_col=0)
    phi0.set_index([[MAIN_MODALITY] * len(phi0.index), phi0.index], inplace=True)

    assert all('back' not in t for t in phi0.columns[1:])
    assert 'back' in phi0.columns[0]

    num_specific_topics = phi0.shape[1] - 1

    assert num_specific_topics == len([t for t in phi0.columns if 'back' not in t])

    print(f'Num model topics: {phi0.shape[1]}.')

    with open(f'{seed_load_folder}/top_words.json', 'r') as f:
        top_words = json.loads(f.read())


    
    model, phi, common_phi_words = init_model_and_phi(
        num_topics=num_specific_topics + 1,  # background
        dataset=dataset, phi0=phi0
    )
    common_words = [
        w[1] for w in common_phi_words  # without modality
    ]
    common_words_phi0_indices = [
        # phi0.index.get_loc(w) for w in common_words
        int(phi0.index.get_locs(w)) for w in common_phi_words
    ]

    print('Check before fit:')
    diff_tops1 = check_top_words(phi, top_words)  # Whatever...
    
    fix_regularizer = FastFixPhiRegularizer(
        name='fix',
        parent_phi=phi0.iloc[common_words_phi0_indices, 1:],
        words=common_words,
        topic_names=phi.columns[1:],
    )
    result = fit_and_compute_scores(
        model, dataset,
        target_topic_indices=list(range(phi.shape[1])),
        custom_regularizers = {
            fix_regularizer.name: fix_regularizer,
        }
    )

    print('Check after fit:')
    diff_tops2 = check_top_words(phi, top_words)  # Whatever...

    assert diff_tops1 == diff_tops2

    fair_ppl_free = result['scores']['perplexity']

    del model, phi, fix_regularizer, result


    
    model, phi, _ = init_model_and_phi(
        num_topics=num_specific_topics + 1,  # background
        dataset=dataset, phi0=phi0
    )
    fix_regularizer = FastFixPhiRegularizer(
        name='fix',
        parent_phi=phi0.iloc[common_words_phi0_indices, :],  # Diff here
        words=common_words,
        topic_names=phi.columns,
    )
    result = fit_and_compute_scores(
        model, dataset,
        target_topic_indices=list(range(phi.shape[1])),
        custom_regularizers = {
            fix_regularizer.name: fix_regularizer,
        }
    )
    
    fair_ppl_fix = result['scores']['perplexity']

    del model, phi, fix_regularizer, result

    
    
    model, phi, _ = init_model_and_phi(
        num_topics=num_specific_topics,  # Diff here
        dataset=dataset, phi0=phi0
    )
    fix_regularizer = FastFixPhiRegularizer(
        name='fix',
        parent_phi=phi0.iloc[common_words_phi0_indices, 1:],  # Diff here
        words=common_words,
        topic_names=phi.columns,
    )
    result = fit_and_compute_scores(
        model, dataset,
        custom_regularizers = {
            fix_regularizer.name: fix_regularizer,
        }
    )

    unfair_ppl_banklike = result['scores']['perplexity']


    
    result['scores']['fair_ppl_free'] = fair_ppl_free
    result['scores']['fair_ppl_fix'] = fair_ppl_fix
    result['scores']['unfair_ppl_banklike'] = unfair_ppl_banklike

    assert result['scores']['fair_ppl_free'] < result['scores']['unfair_ppl_banklike']
    # assert result['scores']['fair_ppl_fix'] < result['scores']['unfair_ppl_banklike']

    result['scores']['coherence_20'] = float(result['scores']['coherence_20'])
    result['stats'] = {
        'num_topics': phi0.shape[1],
        'num_common_words': len(common_words),
        'num_model_words': phi.shape[0],
        'num_bt_words': phi0.shape[0],
        'top_diffs': diff_tops2,
    }

    results.append(result)

    print(result['scores'])
    print(result['stats'])

    dumped_result = json.dumps(
        results[-1], indent=4
    )

    with open(current_save_file_path, 'w') as f:
        f.write(dumped_result)

    del model, phi, fix_regularizer


with open(save_file_path, 'w') as f:
    f.write(
        json.dumps(
            results, indent=4
        )
    )

0
Already computed results: results/rtlwikiperson/bertopic/bertopic_0.json. Loading and skipping...
1
Already computed results: results/rtlwikiperson/bertopic/bertopic_1.json. Loading and skipping...
2
Already computed results: results/rtlwikiperson/bertopic/bertopic_2.json. Loading and skipping...
3
Already computed results: results/rtlwikiperson/bertopic/bertopic_3.json. Loading and skipping...
4
Already computed results: results/rtlwikiperson/bertopic/bertopic_4.json. Loading and skipping...
5
Already computed results: results/rtlwikiperson/bertopic/bertopic_5.json. Loading and skipping...
6
Already computed results: results/rtlwikiperson/bertopic/bertopic_6.json. Loading and skipping...
7
Already computed results: results/rtlwikiperson/bertopic/bertopic_7.json. Loading and skipping...
8
Num model topics: 21.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
  WTF: {'english', 'writing'} {'mary', 'lewis'}
topic_2
  WTF: {'son', 'ad', 'king', 'time'} {'louis', 'augustus', 'rome', 'claudius'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_3
  WTF: {'years', 'national', 'prime'} {'nelson', 'british', 'rommel'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_4
  WTF: {'2008', 'career', 'american', 'academy'} {'cagney', 'robeson', 'hitchcock', 'paul'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_5
  WTF: {'university', 'philosophy', 'later', 'architecture', 'published', 'time', 'design', 'isbn'} {'paris', 'rodin', 'rousseau', 'warhol', 'wright', 'lacan', 'sartre', 'york'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_6
  WTF: {'army', 'government', 'empire', 'new', 'al', 'son', 'muslims', 'time', 'interrogation'} {'rumi', 'muhammad', 'afghanistan', 'islamic', 'abd', 'persian', 'zubaydah', 'abu', 'cia'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_7
  WTF: {'recorded', 'tour'} {'elvis', 'presley'}
topic_8
  WTF: {'il', 'life', 'work', 'polo', 'father', 'fra', 'san', 'english', 'years', 'church', 'st'} {'fellini', 'lucrezia', 'borgia', 'bruno', 'rome', 'francis', 'marco', 'florence', 'caravaggio', 'calvino', 'borges'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_9
  WTF: {'von', 'paternal', 'prince', 'elector', 'death', 'died', 'maternal', 'emperor', 'married', 'military', 'otto', 'daughter'} {'prussia', 'hungary', 'saxony', 'alfreds', 'albert', 'poland', 'brandenburg', 'bismarck', 'alfred', 'prussian', 'frederick', 'casimir'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_10
  WTF: {'empress', 'clan', 'brown', 'month', 'emperors', 'son', 'court', 'military', 'senso', 'years', 'throne', 'sailor'} {'japanese', 'nichiren', 'minamoto', 'kurosawa', 'deng', 'varley', 'chiang', 'fujiwara', 'japan', 'yamamoto', 'chinese', 'titsingh'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_11
  WTF: {'concerto', 'gamba', 'words', 'string', 'da', 'composers'} {'handel', 'haydn', 'shostakovich', 'wk', 'elgar', 'lugosi'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_12
  WTF: {'army', 'government', 'chess', 'revolution', 'life', 'film', 'later', 'committee', 'new', 'world', 'military', 'time', 'order', 'state'} {'stalin', 'russian', 'beria', 'philby', 'trotsky', 'nicholas', 'alexander', 'chekhov', 'yeltsin', 'russia', 'moscow', 'tito', 'kasparov', 'gorbachev'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_13
  WTF: {'voyage', 'later', 'mothers', 'new', 'islands', 'son', 'married', 'war', 'time', 'conquest', 'men', 'years', 'city', 'expedition'} {'corts', 'castile', 'xavier', 'columbus', 'madero', 'almagro', 'franco', 'mexico', 'portuguese', 'moctezuma', 'cid', 'afonso', 'portugal', 'alfonso'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_14
  WTF: {'earl', 'duke', 'prince', 'royal', 'marriage', 'death', 'ii', 'died', 'reign', 'succession', 'throne'} {'william', 'edward', 'england', 'wales', 'elizabeth', 'mary', 'catherine', 'charles', 'scotland', 'henry', 'henrys'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_15
  WTF: {'championship', 'lost', 'grand', 'tennis', 'wickets'} {'muralitharan', 'agassi', 'jordan', 'schumacher', 'earnhardt'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_16
  WTF: {'little', 'christian', 'paintings', 'life', 'works', 'short', 'best', 'new', 'work', 'art', 'published', '2005', 'comics'} {'prideaux', 'kafkas', 'munch', 'aalto', 'nansen', 'kafka', 'munchs', 'andersen', 'franz', 'norway', 'alvar', 'eggum', 'ibsen'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_17
  WTF: {'seminary', 'work', 'new', 'studies', 'prophets', 'rabbis', 'theology', 'sabbath', 'scholars', 'conservative', 'theological', 'book'} {'neusners', 'hebrew', 'jewish', 'kaplan', 'kaplans', 'talmud', 'steinsaltz', 'judaism', 'torah', 'jts', 'neusner', 'heschel'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_18
  WTF: {'radio', 'featured', 'new', 'minutes', 'golf', 'time', 'composer', 'lyrics', 'shows', 'popular'} {'dowland', 'bing', 'gershwin', 'kern', 'crosby', 'elfman', 'crosbys', 'dowlands', 'broadway', 'ira'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_19
  WTF: {'tigers', 'players', 'allstar', 'hall', 'pitchers', 'hit', 'pitched'} {'greenberg', 'cy', 'doubleday', 'rockne', 'milwaukee', 'youngs', 'mlb'}
  WTF?!?!? 7
  WTF?!?!? 7
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f9ffb40d2e0>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
  WTF: {'english', 'writing'} {'mary', 'lewis'}
topic_2
  WTF: {'son', 'ad', 'king', 'time'} {'louis', 'augustus', 'rome', 'claudius'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_3
  WTF: {'years', 'national', 'prime'} {'nelson', 'british', 'rommel'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_4
  WTF: {'2008', 'career', 'american', 'academy'} {'cagney', 'robeson', 'hitchcock', 'paul'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_5
  WTF: {'university', 'philosophy', 'later', 'architecture', 'published', 'time', 'design', 'isbn'} {'paris', 'rodin', 'rousseau', 'warhol', 'wright', 'lacan', 'sartre', 'york'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_6
  WTF: {'army', 'government', 'empire', 'new', 'al', 'son', 'muslims', 'time', 'interrogation'} {'rumi', 'muhammad', 'afghanistan', 'islamic', 'abd', 'persian', 'zubaydah', 'abu', 'cia'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_7
  WTF: {'recorded', 'tour'} {'elvis', 'presley'}
topic_8
  WTF: {'il', 'life', 'work', 'polo', 'father', 'fra', 'san', 'english', 'years', 'church', 'st'} {'fellini', 'lucrezia', 'borgia', 'bruno', 'rome', 'francis', 'marco', 'florence', 'caravaggio', 'calvino', 'borges'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_9
  WTF: {'von', 'paternal', 'prince', 'elector', 'death', 'died', 'maternal', 'emperor', 'married', 'military', 'otto', 'daughter'} {'prussia', 'hungary', 'saxony', 'alfreds', 'albert', 'poland', 'brandenburg', 'bismarck', 'alfred', 'prussian', 'frederick', 'casimir'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_10
  WTF: {'empress', 'clan', 'brown', 'month', 'emperors', 'son', 'court', 'military', 'senso', 'years', 'throne', 'sailor'} {'japanese', 'nichiren', 'minamoto', 'kurosawa', 'deng', 'varley', 'chiang', 'fujiwara', 'japan', 'yamamoto', 'chinese', 'titsingh'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_11
  WTF: {'concerto', 'gamba', 'words', 'string', 'da', 'composers'} {'handel', 'haydn', 'shostakovich', 'wk', 'elgar', 'lugosi'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_12
  WTF: {'army', 'government', 'chess', 'revolution', 'life', 'film', 'later', 'committee', 'new', 'world', 'military', 'time', 'order', 'state'} {'stalin', 'russian', 'beria', 'philby', 'trotsky', 'nicholas', 'alexander', 'chekhov', 'yeltsin', 'russia', 'moscow', 'tito', 'kasparov', 'gorbachev'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_13
  WTF: {'voyage', 'later', 'mothers', 'new', 'islands', 'son', 'married', 'war', 'time', 'conquest', 'men', 'years', 'city', 'expedition'} {'corts', 'castile', 'xavier', 'columbus', 'madero', 'almagro', 'franco', 'mexico', 'portuguese', 'moctezuma', 'cid', 'afonso', 'portugal', 'alfonso'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_14
  WTF: {'earl', 'duke', 'prince', 'royal', 'marriage', 'death', 'ii', 'died', 'reign', 'succession', 'throne'} {'william', 'edward', 'england', 'wales', 'elizabeth', 'mary', 'catherine', 'charles', 'scotland', 'henry', 'henrys'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_15
  WTF: {'championship', 'lost', 'grand', 'tennis', 'wickets'} {'muralitharan', 'agassi', 'jordan', 'schumacher', 'earnhardt'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_16
  WTF: {'little', 'christian', 'paintings', 'life', 'works', 'short', 'best', 'new', 'work', 'art', 'published', '2005', 'comics'} {'prideaux', 'kafkas', 'munch', 'aalto', 'nansen', 'kafka', 'munchs', 'andersen', 'franz', 'norway', 'alvar', 'eggum', 'ibsen'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_17
  WTF: {'seminary', 'work', 'new', 'studies', 'prophets', 'rabbis', 'theology', 'sabbath', 'scholars', 'conservative', 'theological', 'book'} {'neusners', 'hebrew', 'jewish', 'kaplan', 'kaplans', 'talmud', 'steinsaltz', 'judaism', 'torah', 'jts', 'neusner', 'heschel'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_18
  WTF: {'radio', 'featured', 'new', 'minutes', 'golf', 'time', 'composer', 'lyrics', 'shows', 'popular'} {'dowland', 'bing', 'gershwin', 'kern', 'crosby', 'elfman', 'crosbys', 'dowlands', 'broadway', 'ira'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_19
  WTF: {'tigers', 'players', 'allstar', 'hall', 'pitchers', 'hit', 'pitched'} {'greenberg', 'cy', 'doubleday', 'rockne', 'milwaukee', 'youngs', 'mlb'}
  WTF?!?!? 7
  WTF?!?!? 7

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7fa018759340>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7fa004fcccd0>}
{'perplexity': 359794.1875, 'coherence_20': 0.6431456788050639, 'diversity_euclidean': 0.027796357232294507, 'diversity_jensenshannon': 0.5863405333018918, 'diversity_hellinger': 0.6790146947064181, 'diversity_cosine': 0.6092885145726101, 'fair_ppl_free': 2975.633544921875, 'fair_ppl_fix': 340422.46875, 'unfair_ppl_banklike': 359794.1875}
{'num_topics': 21, 'num_common_words': 65750, 'num_model_words': 155407, 'num_bt_words': 135939, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}]}
9
Num model topics: 21.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
  WTF: {'reign', 'later'} {'augustus', 'rome'}
topic_1
  WTF: {'press'} {'hegel'}
topic_2
  WTF: {'television'} {'robeson'}
topic_3
  WTF: {'english', 'time'} {'mary', 'lewis'}
topic_4
  WTF: {'election', 'battle', 'prime', 'american', 'years'} {'oswald', 'thomas', 'british', 'rommel', 'nelson'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_5
  WTF: {'university', 'philosophy', 'later', 'architecture', 'published', 'time', 'design', 'isbn'} {'paris', 'rodin', 'rousseau', 'warhol', 'wright', 'lacan', 'sartre', 'york'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_6
  WTF: {'army', 'government', 'empire', 'new', 'al', 'son', 'muslims', 'time', 'interrogation'} {'rumi', 'muhammad', 'afghanistan', 'islamic', 'abd', 'persian', 'zubaydah', 'abu', 'cia'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_7
  WTF: {'il', 'life', 'work', 'polo', 'new', 'fra', 'del', 'san', 'renaissance', 'years', 'st'} {'fellini', 'lucrezia', 'borgia', 'bruno', 'rome', 'francis', 'marco', 'florence', 'caravaggio', 'calvino', 'borges'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_8
  WTF: {'empress', 'clan', 'brown', 'month', 'emperors', 'son', 'court', 'military', 'senso', 'years', 'throne', 'sailor'} {'japanese', 'nichiren', 'minamoto', 'kurosawa', 'deng', 'varley', 'chiang', 'fujiwara', 'japan', 'yamamoto', 'chinese', 'titsingh'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_9
  WTF: {'trio', 'concerto', 'words', 'string', 'da', 'opera', 'quartet'} {'handel', 'haydn', 'shostakovich', 'wk', 'elgar', 'hoffmann', 'lugosi'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_10
  WTF: {'voyage', 'later', 'mothers', 'new', 'islands', 'son', 'del', 'married', 'war', 'time', 'conquest', 'men', 'years', 'city', 'expedition'} {'corts', 'aztec', 'castile', 'xavier', 'columbus', 'madero', 'almagro', 'franco', 'mexico', 'portuguese', 'moctezuma', 'cid', 'afonso', 'portugal', 'alfonso'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_11
  WTF: {'earl', 'duke', 'prince', 'royal', 'marriage', 'death', 'ii', 'died', 'reign', 'succession', 'throne'} {'william', 'edward', 'england', 'wales', 'elizabeth', 'mary', 'catherine', 'charles', 'scotland', 'henry', 'henrys'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_12
  WTF: {'evolutionary', 'theory', 'environmental', 'life', 'singer', 'research', 'geology', 'published', 'climate'} {'lyell', 'wallace', 'darwin', 'mayr', 'louis', 'haeckel', 'jensen', 'wilson', 'lomborg'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_13
  WTF: {'championship', 'lost', 'grand', 'tennis', 'wickets'} {'muralitharan', 'agassi', 'jordan', 'schumacher', 'earnhardt'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_14
  WTF: {'philosophical', 'work', 'logical', 'knowledge', 'sign', 'research', 'scientific', 'world', 'published', 'social', 'mathematics', 'isbn'} {'peirces', 'milken', 'popper', 'bertrand', 'dewey', 'russell', 'peirce', 'hayek', 'skinner', 'friedman', 'russells', 'rothbard'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_15
  WTF: {'little', 'museum', 'stories', 'paintings', 'life', 'film', 'works', 'short', 'new', 'work', 'polar', 'art', 'scream', 'published', '2005', 'expedition'} {'prideaux', 'rasmussen', 'munch', 'kafkas', 'aalto', 'fridtjof', 'nansen', 'kafka', 'munchs', 'andersens', 'andersen', 'franz', 'norway', 'alvar', 'eggum', 'ibsen'}
  WTF?!?!? 16
  WTF?!?!? 16
topic_16
  WTF: {'tigers', 'players', 'allstar', 'hall', 'pitchers', 'hit', 'pitched'} {'greenberg', 'cy', 'doubleday', 'rockne', 'milwaukee', 'youngs', 'mlb'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_17
  WTF: {'radio', 'featured', 'new', 'minutes', 'golf', 'time', 'composer', 'lyrics', 'shows', 'popular'} {'dowland', 'bing', 'gershwin', 'kern', 'crosby', 'elfman', 'crosbys', 'dowlands', 'broadway', 'ira'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_18
  WTF: {'seminary', 'work', 'study', 'new', 'studies', 'prophets', 'rabbis', 'theology', 'sabbath', 'scholars', 'conservative', 'theological'} {'neusners', 'hebrew', 'jewish', 'kaplan', 'kaplans', 'talmud', 'steinsaltz', 'judaism', 'torah', 'jts', 'neusner', 'heschel'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_19
  WTF: {'teachings', 'synod', 'dynasty', 'religious', 'new', 'collge', 'ministers', 'city', 'churches', 'family'} {'confucius', 'confucian', 'geneva', 'calvins', 'servetus', 'confucianism', 'dupuis', 'amyraut', 'calvin', 'chinese'}
  WTF?!?!? 10
  WTF?!?!? 10
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f9ff8ea59a0>}
Check after fit:
Skipping background topic: background_1.
topic_0
  WTF: {'reign', 'later'} {'augustus', 'rome'}
topic_1
  WTF: {'press'} {'hegel'}
topic_2
  WTF: {'television'} {'robeson'}
topic_3
  WTF: {'english', 'time'} {'mary', 'lewis'}
topic_4
  WTF: {'election', 'battle', 'prime', 'american', 'years'} {'oswald', 'thomas', 'british', 'rommel', 'nelson'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_5
  WTF: {'university', 'philosophy', 'later', 'architecture', 'published', 'time', 'design', 'isbn'} {'paris', 'rodin', 'rousseau', 'warhol', 'wright', 'lacan', 'sartre', 'york'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_6
  WTF: {'army', 'government', 'empire', 'new', 'al', 'son', 'muslims', 'time', 'interrogation'} {'rumi', 'muhammad', 'afghanistan', 'islamic', 'abd', 'persian', 'zubaydah', 'abu', 'cia'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_7
  WTF: {'il', 'life', 'work', 'polo', 'new', 'fra', 'del', 'san', 'renaissance', 'years', 'st'} {'fellini', 'lucrezia', 'borgia', 'bruno', 'rome', 'francis', 'marco', 'florence', 'caravaggio', 'calvino', 'borges'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_8
  WTF: {'empress', 'clan', 'brown', 'month', 'emperors', 'son', 'court', 'military', 'senso', 'years', 'throne', 'sailor'} {'japanese', 'nichiren', 'minamoto', 'kurosawa', 'deng', 'varley', 'chiang', 'fujiwara', 'japan', 'yamamoto', 'chinese', 'titsingh'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_9
  WTF: {'trio', 'concerto', 'words', 'string', 'da', 'opera', 'quartet'} {'handel', 'haydn', 'shostakovich', 'wk', 'elgar', 'hoffmann', 'lugosi'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_10
  WTF: {'voyage', 'later', 'mothers', 'new', 'islands', 'son', 'del', 'married', 'war', 'time', 'conquest', 'men', 'years', 'city', 'expedition'} {'corts', 'aztec', 'castile', 'xavier', 'columbus', 'madero', 'almagro', 'franco', 'mexico', 'portuguese', 'moctezuma', 'cid', 'afonso', 'portugal', 'alfonso'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_11
  WTF: {'earl', 'duke', 'prince', 'royal', 'marriage', 'death', 'ii', 'died', 'reign', 'succession', 'throne'} {'william', 'edward', 'england', 'wales', 'elizabeth', 'mary', 'catherine', 'charles', 'scotland', 'henry', 'henrys'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_12
  WTF: {'evolutionary', 'theory', 'environmental', 'life', 'singer', 'research', 'geology', 'published', 'climate'} {'lyell', 'wallace', 'darwin', 'mayr', 'louis', 'haeckel', 'jensen', 'wilson', 'lomborg'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_13
  WTF: {'championship', 'lost', 'grand', 'tennis', 'wickets'} {'muralitharan', 'agassi', 'jordan', 'schumacher', 'earnhardt'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_14
  WTF: {'philosophical', 'work', 'logical', 'knowledge', 'sign', 'research', 'scientific', 'world', 'published', 'social', 'mathematics', 'isbn'} {'peirces', 'milken', 'popper', 'bertrand', 'dewey', 'russell', 'peirce', 'hayek', 'skinner', 'friedman', 'russells', 'rothbard'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_15
  WTF: {'little', 'museum', 'stories', 'paintings', 'life', 'film', 'works', 'short', 'new', 'work', 'polar', 'art', 'scream', 'published', '2005', 'expedition'} {'prideaux', 'rasmussen', 'munch', 'kafkas', 'aalto', 'fridtjof', 'nansen', 'kafka', 'munchs', 'andersens', 'andersen', 'franz', 'norway', 'alvar', 'eggum', 'ibsen'}
  WTF?!?!? 16
  WTF?!?!? 16
topic_16
  WTF: {'tigers', 'players', 'allstar', 'hall', 'pitchers', 'hit', 'pitched'} {'greenberg', 'cy', 'doubleday', 'rockne', 'milwaukee', 'youngs', 'mlb'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_17
  WTF: {'radio', 'featured', 'new', 'minutes', 'golf', 'time', 'composer', 'lyrics', 'shows', 'popular'} {'dowland', 'bing', 'gershwin', 'kern', 'crosby', 'elfman', 'crosbys', 'dowlands', 'broadway', 'ira'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_18
  WTF: {'seminary', 'work', 'study', 'new', 'studies', 'prophets', 'rabbis', 'theology', 'sabbath', 'scholars', 'conservative', 'theological'} {'neusners', 'hebrew', 'jewish', 'kaplan', 'kaplans', 'talmud', 'steinsaltz', 'judaism', 'torah', 'jts', 'neusner', 'heschel'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_19
  WTF: {'teachings', 'synod', 'dynasty', 'religious', 'new', 'collge', 'ministers', 'city', 'churches', 'family'} {'confucius', 'confucian', 'geneva', 'calvins', 'servetus', 'confucianism', 'dupuis', 'amyraut', 'calvin', 'chinese'}
  WTF?!?!? 10
  WTF?!?!? 10

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7fa019736550>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7fa0070a9fa0>}
{'perplexity': 351229.625, 'coherence_20': 0.6707485586232642, 'diversity_euclidean': 0.028176682493570023, 'diversity_jensenshannon': 0.598508662118602, 'diversity_hellinger': 0.6945825804860494, 'diversity_cosine': 0.6185026831743194, 'fair_ppl_free': 2994.616455078125, 'fair_ppl_fix': 333160.03125, 'unfair_ppl_banklike': 351229.625}
{'num_topics': 21, 'num_common_words': 65750, 'num_model_words': 155407, 'num_bt_words': 135939, 'top_diffs': [{'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 32, 'lost_bt': 16, 'lost_model': 16}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}]}
10
Num model topics: 21.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
  WTF: {'son', 'reign', 'later'} {'louis', 'augustus', 'rome'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_2
  WTF: {'2008', 'comedy', 'career', 'appeared'} {'cagney', 'robeson', 'hitchcock', 'paul'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_3
  WTF: {'writing', 'poems', 'literary'} {'mary', 'lewis', 'tolkien'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_4
  WTF: {'house', 'years', 'national', 'battle'} {'nelson', 'british', 'kemp', 'rommel'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_5
  WTF: {'pope', 'film', 'new', 'giovanni', 'years'} {'fellini', 'haydn', 'rome', 'wk', 'borges'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_6
  WTF: {'university', 'later', 'architecture', 'published', 'time', 'design', 'years', 'isbn'} {'paris', 'rodin', 'rousseau', 'warhol', 'wright', 'lacan', 'sartre', 'york'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_7
  WTF: {'recorded', 'tour'} {'elvis', 'presley'}
topic_8
  WTF: {'army', 'government', 'empire', 'new', 'al', 'son', 'muslims', 'time', 'interrogation'} {'rumi', 'muhammad', 'afghanistan', 'islamic', 'abd', 'persian', 'zubaydah', 'abu', 'cia'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_9
  WTF: {'empress', 'brown', 'new', 'month', 'emperors', 'son', 'court', 'military', 'senso', 'years', 'throne', 'sailor'} {'kaunda', 'japanese', 'nichiren', 'minamoto', 'kurosawa', 'deng', 'varley', 'chiang', 'fujiwara', 'japan', 'yamamoto', 'titsingh'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_10
  WTF: {'voyage', 'later', 'mothers', 'new', 'islands', 'son', 'del', 'married', 'war', 'time', 'conquest', 'men', 'years', 'city', 'expedition'} {'corts', 'aztec', 'castile', 'xavier', 'columbus', 'madero', 'almagro', 'franco', 'mexico', 'portuguese', 'moctezuma', 'cid', 'afonso', 'portugal', 'alfonso'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_11
  WTF: {'championship', 'lost', 'grand', 'tennis', 'wickets'} {'muralitharan', 'agassi', 'jordan', 'schumacher', 'earnhardt'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_12
  WTF: {'evolutionary', 'global', 'theory', 'environmental', 'life', 'singer', 'pp', 'geology', 'published', 'climate', 'nature'} {'lyell', 'wallace', 'darwin', 'rushton', 'mayr', 'louis', 'haeckel', 'jensen', 'wilson', 'lomborg', 'snyder'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_13
  WTF: {'iii', 'saga', 'death', 'ii', 'died', 'pp', 'married', 'killed', 'ed', 'kingship', 'brother', 'english', 'isbn', 'kingdom', 'chronicle'} {'mel', 'oram', 'macbeth', 'maclaurin', 'coluim', 'scots', 'malcolm', 'duncan', 'alexander', 'scottish', 'selkirk', 'alba', 'kenneth', 'malcolms', 'scotland'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_14
  WTF: {'little', 'stories', 'paintings', 'life', 'best', 'work', 'new', 'award', 'polar', 'art', 'duck', '2005', 'comics'} {'prideaux', 'munch', 'aalto', 'fridtjof', 'nansen', 'andersens', 'munchs', 'andersen', 'barks', 'norway', 'alvar', 'eggum', 'ibsen'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_15
  WTF: {'life', 'later', 'meetings', 'dictionary', 'pp', 'society', 'gin', 'published', 'time', 'english', 'years', 'church', 'prior'} {'burkes', 'webster', 'connecticut', 'alcott', 'whitney', 'eli', 'foxs', 'quakers', 'yale', 'mather', 'nickalls', 'abbott', 'burke'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_16
  WTF: {'earl', 'duke', 'royal', 'death', 'ii', 'reign', 'protestant', 'kings', 'succession', 'council', 'church', 'throne'} {'tudor', 'edward', 'england', 'anne', 'wales', 'elizabeth', 'mary', 'catherine', 'owain', 'charles', 'henry', 'henrys'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_17
  WTF: {'grammar', 'rpt', 'work', 'description', 'humans', 'linguist', 'english', 'linguists'} {'african', 'whorf', 'doke', 'jones', 'diedrich', 'westermann', 'hockett', 'bantu'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_18
  WTF: {'tigers', 'players', 'allstar', 'hall', 'pitchers', 'hit', 'pitched'} {'greenberg', 'cy', 'doubleday', 'rockne', 'milwaukee', 'youngs', 'mlb'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_19
  WTF: {'seminary', 'work', 'study', 'new', 'studies', 'prophets', 'rabbis', 'theology', 'sabbath', 'scholars', 'conservative', 'theological'} {'neusners', 'hebrew', 'jewish', 'kaplan', 'kaplans', 'talmud', 'steinsaltz', 'judaism', 'torah', 'jts', 'neusner', 'heschel'}
  WTF?!?!? 12
  WTF?!?!? 12
{'fix': <__main__.FastFixPhiRegularizer object at 0x7fa019224340>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
  WTF: {'son', 'reign', 'later'} {'louis', 'augustus', 'rome'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_2
  WTF: {'2008', 'comedy', 'career', 'appeared'} {'cagney', 'robeson', 'hitchcock', 'paul'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_3
  WTF: {'writing', 'poems', 'literary'} {'mary', 'lewis', 'tolkien'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_4
  WTF: {'house', 'years', 'national', 'battle'} {'nelson', 'british', 'kemp', 'rommel'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_5
  WTF: {'pope', 'film', 'new', 'giovanni', 'years'} {'fellini', 'haydn', 'rome', 'wk', 'borges'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_6
  WTF: {'university', 'later', 'architecture', 'published', 'time', 'design', 'years', 'isbn'} {'paris', 'rodin', 'rousseau', 'warhol', 'wright', 'lacan', 'sartre', 'york'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_7
  WTF: {'recorded', 'tour'} {'elvis', 'presley'}
topic_8
  WTF: {'army', 'government', 'empire', 'new', 'al', 'son', 'muslims', 'time', 'interrogation'} {'rumi', 'muhammad', 'afghanistan', 'islamic', 'abd', 'persian', 'zubaydah', 'abu', 'cia'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_9
  WTF: {'empress', 'brown', 'new', 'month', 'emperors', 'son', 'court', 'military', 'senso', 'years', 'throne', 'sailor'} {'kaunda', 'japanese', 'nichiren', 'minamoto', 'kurosawa', 'deng', 'varley', 'chiang', 'fujiwara', 'japan', 'yamamoto', 'titsingh'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_10
  WTF: {'voyage', 'later', 'mothers', 'new', 'islands', 'son', 'del', 'married', 'war', 'time', 'conquest', 'men', 'years', 'city', 'expedition'} {'corts', 'aztec', 'castile', 'xavier', 'columbus', 'madero', 'almagro', 'franco', 'mexico', 'portuguese', 'moctezuma', 'cid', 'afonso', 'portugal', 'alfonso'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_11
  WTF: {'championship', 'lost', 'grand', 'tennis', 'wickets'} {'muralitharan', 'agassi', 'jordan', 'schumacher', 'earnhardt'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_12
  WTF: {'evolutionary', 'global', 'theory', 'environmental', 'life', 'singer', 'pp', 'geology', 'published', 'climate', 'nature'} {'lyell', 'wallace', 'darwin', 'rushton', 'mayr', 'louis', 'haeckel', 'jensen', 'wilson', 'lomborg', 'snyder'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_13
  WTF: {'iii', 'saga', 'death', 'ii', 'died', 'pp', 'married', 'killed', 'ed', 'kingship', 'brother', 'english', 'isbn', 'kingdom', 'chronicle'} {'mel', 'oram', 'macbeth', 'maclaurin', 'coluim', 'scots', 'malcolm', 'duncan', 'alexander', 'scottish', 'selkirk', 'alba', 'kenneth', 'malcolms', 'scotland'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_14
  WTF: {'little', 'stories', 'paintings', 'life', 'best', 'work', 'new', 'award', 'polar', 'art', 'duck', '2005', 'comics'} {'prideaux', 'munch', 'aalto', 'fridtjof', 'nansen', 'andersens', 'munchs', 'andersen', 'barks', 'norway', 'alvar', 'eggum', 'ibsen'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_15
  WTF: {'life', 'later', 'meetings', 'dictionary', 'pp', 'society', 'gin', 'published', 'time', 'english', 'years', 'church', 'prior'} {'burkes', 'webster', 'connecticut', 'alcott', 'whitney', 'eli', 'foxs', 'quakers', 'yale', 'mather', 'nickalls', 'abbott', 'burke'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_16
  WTF: {'earl', 'duke', 'royal', 'death', 'ii', 'reign', 'protestant', 'kings', 'succession', 'council', 'church', 'throne'} {'tudor', 'edward', 'england', 'anne', 'wales', 'elizabeth', 'mary', 'catherine', 'owain', 'charles', 'henry', 'henrys'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_17
  WTF: {'grammar', 'rpt', 'work', 'description', 'humans', 'linguist', 'english', 'linguists'} {'african', 'whorf', 'doke', 'jones', 'diedrich', 'westermann', 'hockett', 'bantu'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_18
  WTF: {'tigers', 'players', 'allstar', 'hall', 'pitchers', 'hit', 'pitched'} {'greenberg', 'cy', 'doubleday', 'rockne', 'milwaukee', 'youngs', 'mlb'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_19
  WTF: {'seminary', 'work', 'study', 'new', 'studies', 'prophets', 'rabbis', 'theology', 'sabbath', 'scholars', 'conservative', 'theological'} {'neusners', 'hebrew', 'jewish', 'kaplan', 'kaplans', 'talmud', 'steinsaltz', 'judaism', 'torah', 'jts', 'neusner', 'heschel'}
  WTF?!?!? 12
  WTF?!?!? 12

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7fa018daab20>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7fa004affeb0>}
{'perplexity': 379797.6875, 'coherence_20': 0.6478186695728434, 'diversity_euclidean': 0.030687359962305524, 'diversity_jensenshannon': 0.6042554554507573, 'diversity_hellinger': 0.7013259557764396, 'diversity_cosine': 0.6410990802244904, 'fair_ppl_free': 2994.542236328125, 'fair_ppl_fix': 335089.5625, 'unfair_ppl_banklike': 379797.6875}
{'num_topics': 21, 'num_common_words': 65750, 'num_model_words': 155407, 'num_bt_words': 135939, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}]}
11
Num model topics: 21.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
  WTF: {'reign', 'later', 'son'} {'louis', 'augustus', 'rome'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_1
  WTF: {'logic'} {'peirce'}
topic_2
  WTF: {'english', 'writing', 'literary'} {'mary', 'lewis', 'tolkien'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_3
  WTF: {'house', 'years', 'national', 'battle'} {'thomas', 'nelson', 'british', 'rommel'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_4
  WTF: {'pope', 'later', 'new', 'musical', 'da', 'years'} {'haydn', 'chopin', 'rome', 'wk', 'pessoa', 'borges'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_5
  WTF: {'2008', 'comedy', 'american', 'career'} {'cagney', 'robeson', 'hitchcock', 'paul'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_6
  WTF: {'university', 'philosophy', 'later', 'architecture', 'published', 'time', 'design', 'isbn'} {'paris', 'rodin', 'rousseau', 'warhol', 'wright', 'lacan', 'sartre', 'york'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_7
  WTF: {'recorded', 'tour'} {'elvis', 'presley'}
topic_8
  WTF: {'army', 'government', 'empire', 'new', 'al', 'son', 'muslims', 'time', 'interrogation'} {'rumi', 'muhammad', 'afghanistan', 'islamic', 'abd', 'persian', 'zubaydah', 'abu', 'cia'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_9
  WTF: {'empress', 'clan', 'brown', 'month', 'emperors', 'son', 'court', 'military', 'senso', 'years', 'throne', 'sailor'} {'japanese', 'nichiren', 'minamoto', 'kurosawa', 'deng', 'varley', 'chiang', 'fujiwara', 'japan', 'yamamoto', 'chinese', 'titsingh'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_10
  WTF: {'interview', 'machine', 'project', 'institute', 'language', 'award', 'information'} {'babbage', 'shannon', 'turing', 'engelbart', 'zuse', 'wikipedia', 'sanger'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_11
  WTF: {'voyage', 'later', 'mothers', 'new', 'islands', 'son', 'del', 'married', 'war', 'time', 'conquest', 'men', 'years', 'city', 'expedition'} {'corts', 'aztec', 'castile', 'xavier', 'columbus', 'madero', 'almagro', 'franco', 'mexico', 'portuguese', 'moctezuma', 'cid', 'afonso', 'portugal', 'alfonso'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_12
  WTF: {'earl', 'duke', 'prince', 'royal', 'marriage', 'death', 'ii', 'died', 'reign', 'succession', 'throne'} {'william', 'edward', 'england', 'wales', 'elizabeth', 'mary', 'catherine', 'charles', 'scotland', 'henry', 'henrys'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_13
  WTF: {'life', 'research', 'pp', 'society', 'geology', 'published', 'climate', 'book'} {'lyell', 'wallace', 'darwin', 'mayr', 'louis', 'haeckel', 'jensen', 'lomborg'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_14
  WTF: {'championship', 'lost', 'grand', 'tennis', 'wickets'} {'muralitharan', 'agassi', 'jordan', 'schumacher', 'earnhardt'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_15
  WTF: {'little', 'christian', 'paintings', 'life', 'works', 'short', 'best', 'new', 'work', 'art', 'published', '2005', 'comics'} {'prideaux', 'kafkas', 'munch', 'aalto', 'nansen', 'kafka', 'munchs', 'andersen', 'franz', 'norway', 'alvar', 'eggum', 'ibsen'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_16
  WTF: {'books', 'cosmos', 'life', 'dictionary', 'society', 'gin', 'published', 'time', 'english', 'isbn', 'church', 'prior'} {'burkes', 'webster', 'adler', 'alcott', 'whitney', 'foxs', 'quakers', 'yale', 'mather', 'nickalls', 'abbott', 'burke'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_17
  WTF: {'tigers', 'players', 'allstar', 'hall', 'pitchers', 'hit', 'pitched'} {'greenberg', 'cy', 'doubleday', 'rockne', 'milwaukee', 'youngs', 'mlb'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_18
  WTF: {'radio', 'featured', 'new', 'minutes', 'golf', 'time', 'composer', 'lyrics', 'shows', 'popular'} {'dowland', 'bing', 'gershwin', 'kern', 'crosby', 'elfman', 'crosbys', 'dowlands', 'broadway', 'ira'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_19
  WTF: {'seminary', 'work', 'study', 'new', 'studies', 'prophets', 'rabbis', 'theology', 'sabbath', 'scholars', 'conservative', 'theological'} {'neusners', 'hebrew', 'jewish', 'kaplan', 'kaplans', 'talmud', 'steinsaltz', 'judaism', 'torah', 'jts', 'neusner', 'heschel'}
  WTF?!?!? 12
  WTF?!?!? 12
{'fix': <__main__.FastFixPhiRegularizer object at 0x7fa018ea5340>}
Check after fit:
Skipping background topic: background_1.
topic_0
  WTF: {'reign', 'later', 'son'} {'louis', 'augustus', 'rome'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_1
  WTF: {'logic'} {'peirce'}
topic_2
  WTF: {'english', 'writing', 'literary'} {'mary', 'lewis', 'tolkien'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_3
  WTF: {'house', 'years', 'national', 'battle'} {'thomas', 'nelson', 'british', 'rommel'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_4
  WTF: {'pope', 'later', 'new', 'musical', 'da', 'years'} {'haydn', 'chopin', 'rome', 'wk', 'pessoa', 'borges'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_5
  WTF: {'2008', 'comedy', 'american', 'career'} {'cagney', 'robeson', 'hitchcock', 'paul'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_6
  WTF: {'university', 'philosophy', 'later', 'architecture', 'published', 'time', 'design', 'isbn'} {'paris', 'rodin', 'rousseau', 'warhol', 'wright', 'lacan', 'sartre', 'york'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_7
  WTF: {'recorded', 'tour'} {'elvis', 'presley'}
topic_8
  WTF: {'army', 'government', 'empire', 'new', 'al', 'son', 'muslims', 'time', 'interrogation'} {'rumi', 'muhammad', 'afghanistan', 'islamic', 'abd', 'persian', 'zubaydah', 'abu', 'cia'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_9
  WTF: {'empress', 'clan', 'brown', 'month', 'emperors', 'son', 'court', 'military', 'senso', 'years', 'throne', 'sailor'} {'japanese', 'nichiren', 'minamoto', 'kurosawa', 'deng', 'varley', 'chiang', 'fujiwara', 'japan', 'yamamoto', 'chinese', 'titsingh'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_10
  WTF: {'interview', 'machine', 'project', 'institute', 'language', 'award', 'information'} {'babbage', 'shannon', 'turing', 'engelbart', 'zuse', 'wikipedia', 'sanger'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_11
  WTF: {'voyage', 'later', 'mothers', 'new', 'islands', 'son', 'del', 'married', 'war', 'time', 'conquest', 'men', 'years', 'city', 'expedition'} {'corts', 'aztec', 'castile', 'xavier', 'columbus', 'madero', 'almagro', 'franco', 'mexico', 'portuguese', 'moctezuma', 'cid', 'afonso', 'portugal', 'alfonso'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_12
  WTF: {'earl', 'duke', 'prince', 'royal', 'marriage', 'death', 'ii', 'died', 'reign', 'succession', 'throne'} {'william', 'edward', 'england', 'wales', 'elizabeth', 'mary', 'catherine', 'charles', 'scotland', 'henry', 'henrys'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_13
  WTF: {'life', 'research', 'pp', 'society', 'geology', 'published', 'climate', 'book'} {'lyell', 'wallace', 'darwin', 'mayr', 'louis', 'haeckel', 'jensen', 'lomborg'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_14
  WTF: {'championship', 'lost', 'grand', 'tennis', 'wickets'} {'muralitharan', 'agassi', 'jordan', 'schumacher', 'earnhardt'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_15
  WTF: {'little', 'christian', 'paintings', 'life', 'works', 'short', 'best', 'new', 'work', 'art', 'published', '2005', 'comics'} {'prideaux', 'kafkas', 'munch', 'aalto', 'nansen', 'kafka', 'munchs', 'andersen', 'franz', 'norway', 'alvar', 'eggum', 'ibsen'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_16
  WTF: {'books', 'cosmos', 'life', 'dictionary', 'society', 'gin', 'published', 'time', 'english', 'isbn', 'church', 'prior'} {'burkes', 'webster', 'adler', 'alcott', 'whitney', 'foxs', 'quakers', 'yale', 'mather', 'nickalls', 'abbott', 'burke'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_17
  WTF: {'tigers', 'players', 'allstar', 'hall', 'pitchers', 'hit', 'pitched'} {'greenberg', 'cy', 'doubleday', 'rockne', 'milwaukee', 'youngs', 'mlb'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_18
  WTF: {'radio', 'featured', 'new', 'minutes', 'golf', 'time', 'composer', 'lyrics', 'shows', 'popular'} {'dowland', 'bing', 'gershwin', 'kern', 'crosby', 'elfman', 'crosbys', 'dowlands', 'broadway', 'ira'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_19
  WTF: {'seminary', 'work', 'study', 'new', 'studies', 'prophets', 'rabbis', 'theology', 'sabbath', 'scholars', 'conservative', 'theological'} {'neusners', 'hebrew', 'jewish', 'kaplan', 'kaplans', 'talmud', 'steinsaltz', 'judaism', 'torah', 'jts', 'neusner', 'heschel'}
  WTF?!?!? 12
  WTF?!?!? 12

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7fa018daa7c0>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7fa019736c10>}
{'perplexity': 336022.6875, 'coherence_20': 0.6418428000936529, 'diversity_euclidean': 0.028064738242142614, 'diversity_jensenshannon': 0.5909922919105342, 'diversity_hellinger': 0.6847418062753835, 'diversity_cosine': 0.6158648467431379, 'fair_ppl_free': 2981.890380859375, 'fair_ppl_fix': 361825.75, 'unfair_ppl_banklike': 336022.6875}
{'num_topics': 21, 'num_common_words': 65750, 'num_model_words': 155407, 'num_bt_words': 135939, 'top_diffs': [{'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}]}
12
Num model topics: 21.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
  WTF: {'mathematics'} {'peirce'}
topic_1
  WTF: {'english', 'literary'} {'mary', 'lewis'}
topic_2
  WTF: {'2008', 'comedy', 'american', 'career'} {'cagney', 'robeson', 'hitchcock', 'paul'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_3
  WTF: {'election', 'battle', 'prime', 'later', 'years'} {'oswald', 'british', 'kemp', 'rommel', 'nelson'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_4
  WTF: {'reign', 'ad', 'time', 'century', 'greek'} {'moses', 'augustus', 'rome', 'claudius', 'eusebius'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_5
  WTF: {'prince', 'union', 'later', 'death', 'new', 'son', 'emperor', 'time', 'order', 'great', 'german', 'years'} {'charlemagne', 'russian', 'france', 'trotsky', 'nicholas', 'yeltsin', 'louis', 'bismarck', 'russia', 'charles', 'eugene', 'gorbachev'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_6
  WTF: {'university', 'philosophy', 'later', 'architecture', 'published', 'time', 'design', 'isbn'} {'paris', 'rodin', 'rousseau', 'warhol', 'wright', 'lacan', 'sartre', 'york'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_7
  WTF: {'time', 'single'} {'elvis', 'presley'}
topic_8
  WTF: {'army', 'government', 'empire', 'new', 'al', 'son', 'muslims', 'time', 'interrogation'} {'rumi', 'muhammad', 'afghanistan', 'islamic', 'abd', 'persian', 'zubaydah', 'abu', 'cia'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_9
  WTF: {'il', 'work', 'polo', 'new', 'father', 'fra', 'san', 'english', 'years', 'church', 'st'} {'fellini', 'lucrezia', 'borgia', 'bruno', 'rome', 'francis', 'marco', 'florence', 'caravaggio', 'calvino', 'borges'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_10
  WTF: {'trio', 'concerto', 'gamba', 'verdi', 'words', 'composers', 'da'} {'chopins', 'haydn', 'chopin', 'shostakovich', 'wk', 'elgar', 'lugosi'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_11
  WTF: {'empress', 'brown', 'new', 'month', 'emperors', 'son', 'court', 'military', 'senso', 'years', 'throne', 'sailor'} {'kaunda', 'japanese', 'nichiren', 'minamoto', 'kurosawa', 'deng', 'varley', 'chiang', 'fujiwara', 'japan', 'yamamoto', 'titsingh'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_12
  WTF: {'interview', 'machine', 'theory', 'award', 'computers', 'mathematical', 'information'} {'babbage', 'shannon', 'turing', 'engelbart', 'zuse', 'wikipedia', 'sanger'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_13
  WTF: {'voyage', 'later', 'mothers', 'new', 'islands', 'son', 'del', 'married', 'war', 'time', 'conquest', 'men', 'years', 'city', 'expedition'} {'corts', 'aztec', 'castile', 'xavier', 'columbus', 'madero', 'almagro', 'franco', 'mexico', 'portuguese', 'moctezuma', 'cid', 'afonso', 'portugal', 'alfonso'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_14
  WTF: {'62', 'championship', 'lost', 'grand', 'tennis'} {'muralitharan', 'agassi', 'jordan', 'schumacher', 'earnhardt'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_15
  WTF: {'earl', 'duke', 'prince', 'royal', 'marriage', 'death', 'ii', 'died', 'reign', 'succession', 'throne'} {'william', 'edward', 'england', 'wales', 'elizabeth', 'mary', 'catherine', 'charles', 'scotland', 'henry', 'henrys'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_16
  WTF: {'global', 'theory', 'environmental', 'life', 'work', 'singer', 'pp', 'society', 'geology', 'published', 'climate'} {'lyell', 'wallace', 'darwin', 'slotten', 'rushton', 'mayr', 'louis', 'haeckel', 'jensen', 'wilson', 'lomborg'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_17
  WTF: {'little', 'museum', 'christian', 'paintings', 'life', 'works', 'work', 'new', 'award', 'art', 'published', 'collection', '2005'} {'prideaux', 'kafkas', 'munch', 'aalto', 'fafhrd', 'nansen', 'kafka', 'munchs', 'andersen', 'alvar', 'mouser', 'eggum', 'ibsen'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_18
  WTF: {'christian', 'life', 'church', 'later', 'haven', 'witch', 'children', 'published', 'spelling', 'school', 'years', 'isbn', 'trials', 'college'} {'bellamy', 'margaret', 'webster', 'connecticut', 'mead', 'alcott', 'whitney', 'eli', 'samoa', 'noah', 'mathers', 'mather', 'yale', 'abbott'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_19
  WTF: {'seminary', 'work', 'study', 'new', 'studies', 'prophets', 'rabbis', 'theology', 'sabbath', 'scholars', 'conservative', 'theological'} {'neusners', 'hebrew', 'jewish', 'kaplan', 'kaplans', 'talmud', 'steinsaltz', 'judaism', 'torah', 'jts', 'neusner', 'heschel'}
  WTF?!?!? 12
  WTF?!?!? 12
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f9fffa5bd30>}
Check after fit:
Skipping background topic: background_1.
topic_0
  WTF: {'mathematics'} {'peirce'}
topic_1
  WTF: {'english', 'literary'} {'mary', 'lewis'}
topic_2
  WTF: {'2008', 'comedy', 'american', 'career'} {'cagney', 'robeson', 'hitchcock', 'paul'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_3
  WTF: {'election', 'battle', 'prime', 'later', 'years'} {'oswald', 'british', 'kemp', 'rommel', 'nelson'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_4
  WTF: {'reign', 'ad', 'time', 'century', 'greek'} {'moses', 'augustus', 'rome', 'claudius', 'eusebius'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_5
  WTF: {'prince', 'union', 'later', 'death', 'new', 'son', 'emperor', 'time', 'order', 'great', 'german', 'years'} {'charlemagne', 'russian', 'france', 'trotsky', 'nicholas', 'yeltsin', 'louis', 'bismarck', 'russia', 'charles', 'eugene', 'gorbachev'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_6
  WTF: {'university', 'philosophy', 'later', 'architecture', 'published', 'time', 'design', 'isbn'} {'paris', 'rodin', 'rousseau', 'warhol', 'wright', 'lacan', 'sartre', 'york'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_7
  WTF: {'time', 'single'} {'elvis', 'presley'}
topic_8
  WTF: {'army', 'government', 'empire', 'new', 'al', 'son', 'muslims', 'time', 'interrogation'} {'rumi', 'muhammad', 'afghanistan', 'islamic', 'abd', 'persian', 'zubaydah', 'abu', 'cia'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_9
  WTF: {'il', 'work', 'polo', 'new', 'father', 'fra', 'san', 'english', 'years', 'church', 'st'} {'fellini', 'lucrezia', 'borgia', 'bruno', 'rome', 'francis', 'marco', 'florence', 'caravaggio', 'calvino', 'borges'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_10
  WTF: {'trio', 'concerto', 'gamba', 'verdi', 'words', 'composers', 'da'} {'chopins', 'haydn', 'chopin', 'shostakovich', 'wk', 'elgar', 'lugosi'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_11
  WTF: {'empress', 'brown', 'new', 'month', 'emperors', 'son', 'court', 'military', 'senso', 'years', 'throne', 'sailor'} {'kaunda', 'japanese', 'nichiren', 'minamoto', 'kurosawa', 'deng', 'varley', 'chiang', 'fujiwara', 'japan', 'yamamoto', 'titsingh'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_12
  WTF: {'interview', 'machine', 'theory', 'award', 'computers', 'mathematical', 'information'} {'babbage', 'shannon', 'turing', 'engelbart', 'zuse', 'wikipedia', 'sanger'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_13
  WTF: {'voyage', 'later', 'mothers', 'new', 'islands', 'son', 'del', 'married', 'war', 'time', 'conquest', 'men', 'years', 'city', 'expedition'} {'corts', 'aztec', 'castile', 'xavier', 'columbus', 'madero', 'almagro', 'franco', 'mexico', 'portuguese', 'moctezuma', 'cid', 'afonso', 'portugal', 'alfonso'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_14
  WTF: {'62', 'championship', 'lost', 'grand', 'tennis'} {'muralitharan', 'agassi', 'jordan', 'schumacher', 'earnhardt'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_15
  WTF: {'earl', 'duke', 'prince', 'royal', 'marriage', 'death', 'ii', 'died', 'reign', 'succession', 'throne'} {'william', 'edward', 'england', 'wales', 'elizabeth', 'mary', 'catherine', 'charles', 'scotland', 'henry', 'henrys'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_16
  WTF: {'global', 'theory', 'environmental', 'life', 'work', 'singer', 'pp', 'society', 'geology', 'published', 'climate'} {'lyell', 'wallace', 'darwin', 'slotten', 'rushton', 'mayr', 'louis', 'haeckel', 'jensen', 'wilson', 'lomborg'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_17
  WTF: {'little', 'museum', 'christian', 'paintings', 'life', 'works', 'work', 'new', 'award', 'art', 'published', 'collection', '2005'} {'prideaux', 'kafkas', 'munch', 'aalto', 'fafhrd', 'nansen', 'kafka', 'munchs', 'andersen', 'alvar', 'mouser', 'eggum', 'ibsen'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_18
  WTF: {'christian', 'life', 'church', 'later', 'haven', 'witch', 'children', 'published', 'spelling', 'school', 'years', 'isbn', 'trials', 'college'} {'bellamy', 'margaret', 'webster', 'connecticut', 'mead', 'alcott', 'whitney', 'eli', 'samoa', 'noah', 'mathers', 'mather', 'yale', 'abbott'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_19
  WTF: {'seminary', 'work', 'study', 'new', 'studies', 'prophets', 'rabbis', 'theology', 'sabbath', 'scholars', 'conservative', 'theological'} {'neusners', 'hebrew', 'jewish', 'kaplan', 'kaplans', 'talmud', 'steinsaltz', 'judaism', 'torah', 'jts', 'neusner', 'heschel'}
  WTF?!?!? 12
  WTF?!?!? 12

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7fa0026a2fa0>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7fa019d4c070>}
{'perplexity': 341755.78125, 'coherence_20': 0.633430493522031, 'diversity_euclidean': 0.025821480266496485, 'diversity_jensenshannon': 0.5783375060611278, 'diversity_hellinger': 0.6690948987648186, 'diversity_cosine': 0.5941125001164986, 'fair_ppl_free': 2962.483154296875, 'fair_ppl_fix': 399885.75, 'unfair_ppl_banklike': 341755.78125}
{'num_topics': 21, 'num_common_words': 65750, 'num_model_words': 155407, 'num_bt_words': 135939, 'top_diffs': [{'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}]}
13
Num model topics: 21.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
  WTF: {'english', 'writing'} {'mary', 'lewis'}
topic_2
  WTF: {'pope', 'later', 'new', 'da', 'musical'} {'haydn', 'chopin', 'rome', 'wk', 'borges'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_3
  WTF: {'2008', 'comedy', 'actress', 'career'} {'cagney', 'robeson', 'hitchcock', 'paul'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_4
  WTF: {'election', 'battle', 'american', 'national', 'years'} {'thomas', 'british', 'kemp', 'rommel', 'nelson'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_5
  WTF: {'reign', 'ad', 'time', 'century', 'greek'} {'moses', 'augustus', 'rome', 'claudius', 'eusebius'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_6
  WTF: {'university', 'later', 'architecture', 'published', 'time', 'design', 'years', 'isbn'} {'paris', 'rodin', 'rousseau', 'warhol', 'wright', 'lacan', 'sartre', 'york'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_7
  WTF: {'guitar', 'love'} {'elvis', 'presley'}
topic_8
  WTF: {'army', 'government', 'empire', 'new', 'al', 'son', 'muslims', 'time', 'interrogation'} {'rumi', 'muhammad', 'afghanistan', 'islamic', 'abd', 'persian', 'zubaydah', 'abu', 'cia'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_9
  WTF: {'army', 'empire', 'elector', 'death', 'died', 'married', 'military', 'german', 'years'} {'charlemagne', 'france', 'poland', 'louis', 'bismarck', 'alfred', 'frederick', 'charles', 'eugene'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_10
  WTF: {'empress', 'brown', 'new', 'month', 'emperors', 'son', 'court', 'military', 'senso', 'years', 'throne', 'sailor'} {'kaunda', 'japanese', 'nichiren', 'minamoto', 'kurosawa', 'deng', 'varley', 'chiang', 'fujiwara', 'japan', 'yamamoto', 'titsingh'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_11
  WTF: {'army', 'government', 'chess', 'revolution', 'life', 'film', 'later', 'committee', 'new', 'world', 'military', 'time', 'order', 'state'} {'stalin', 'russian', 'beria', 'philby', 'trotsky', 'nicholas', 'alexander', 'chekhov', 'yeltsin', 'russia', 'moscow', 'tito', 'kasparov', 'gorbachev'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_12
  WTF: {'voyage', 'later', 'mothers', 'new', 'islands', 'son', 'del', 'married', 'war', 'time', 'conquest', 'men', 'years', 'city', 'expedition'} {'corts', 'aztec', 'castile', 'xavier', 'columbus', 'madero', 'almagro', 'franco', 'mexico', 'portuguese', 'moctezuma', 'cid', 'afonso', 'portugal', 'alfonso'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_13
  WTF: {'earl', 'duke', 'prince', 'royal', 'marriage', 'death', 'ii', 'died', 'reign', 'succession', 'throne'} {'william', 'edward', 'england', 'wales', 'elizabeth', 'mary', 'catherine', 'charles', 'scotland', 'henry', 'henrys'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_14
  WTF: {'championship', 'lost', 'grand', 'tennis', 'wickets'} {'muralitharan', 'agassi', 'jordan', 'schumacher', 'earnhardt'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_15
  WTF: {'evolutionary', 'global', 'theory', 'environmental', 'life', 'work', 'singer', 'pp', 'published', 'climate', 'book'} {'lyell', 'wallace', 'darwin', 'slotten', 'rushton', 'mayr', 'louis', 'haeckel', 'jensen', 'wilson', 'lomborg'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_16
  WTF: {'little', 'christian', 'paintings', 'life', 'work', 'new', 'hans', 'award', 'art', 'published', 'don', 'collection', '2005'} {'prideaux', 'kafkas', 'munch', 'aalto', 'fafhrd', 'nansen', 'kafka', 'munchs', 'andersen', 'alvar', 'mouser', 'eggum', 'ibsen'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_17
  WTF: {'seminary', 'work', 'study', 'new', 'studies', 'prophets', 'rabbis', 'theology', 'sabbath', 'scholars', 'conservative', 'theological'} {'neusners', 'hebrew', 'jewish', 'kaplan', 'kaplans', 'talmud', 'steinsaltz', 'judaism', 'torah', 'jts', 'neusner', 'heschel'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_18
  WTF: {'john', 'crusaders', 'death', 'minor', 'emperors', '1180', 'iv', 'married', 'fleet', 'daughter', 'crusade', 'greek', '1204'} {'byzantine', 'maria', 'isaac', 'doukas', 'thrace', 'alexios', 'kanaris', 'komnenos', 'andronikos', 'constantinople', 'komnene', 'manuel', 'nikephoros'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_19
  WTF: {'tigers', 'allstar', 'american', 'commissioner', 'hit', 'pitched'} {'greenberg', 'cy', 'rockne', 'milwaukee', 'youngs', 'mlb'}
  WTF?!?!? 6
  WTF?!?!? 6
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f9ffb735520>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
  WTF: {'english', 'writing'} {'mary', 'lewis'}
topic_2
  WTF: {'pope', 'later', 'new', 'da', 'musical'} {'haydn', 'chopin', 'rome', 'wk', 'borges'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_3
  WTF: {'2008', 'comedy', 'actress', 'career'} {'cagney', 'robeson', 'hitchcock', 'paul'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_4
  WTF: {'election', 'battle', 'american', 'national', 'years'} {'thomas', 'british', 'kemp', 'rommel', 'nelson'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_5
  WTF: {'reign', 'ad', 'time', 'century', 'greek'} {'moses', 'augustus', 'rome', 'claudius', 'eusebius'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_6
  WTF: {'university', 'later', 'architecture', 'published', 'time', 'design', 'years', 'isbn'} {'paris', 'rodin', 'rousseau', 'warhol', 'wright', 'lacan', 'sartre', 'york'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_7
  WTF: {'guitar', 'love'} {'elvis', 'presley'}
topic_8
  WTF: {'army', 'government', 'empire', 'new', 'al', 'son', 'muslims', 'time', 'interrogation'} {'rumi', 'muhammad', 'afghanistan', 'islamic', 'abd', 'persian', 'zubaydah', 'abu', 'cia'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_9
  WTF: {'army', 'empire', 'elector', 'death', 'died', 'married', 'military', 'german', 'years'} {'charlemagne', 'france', 'poland', 'louis', 'bismarck', 'alfred', 'frederick', 'charles', 'eugene'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_10
  WTF: {'empress', 'brown', 'new', 'month', 'emperors', 'son', 'court', 'military', 'senso', 'years', 'throne', 'sailor'} {'kaunda', 'japanese', 'nichiren', 'minamoto', 'kurosawa', 'deng', 'varley', 'chiang', 'fujiwara', 'japan', 'yamamoto', 'titsingh'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_11
  WTF: {'army', 'government', 'chess', 'revolution', 'life', 'film', 'later', 'committee', 'new', 'world', 'military', 'time', 'order', 'state'} {'stalin', 'russian', 'beria', 'philby', 'trotsky', 'nicholas', 'alexander', 'chekhov', 'yeltsin', 'russia', 'moscow', 'tito', 'kasparov', 'gorbachev'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_12
  WTF: {'voyage', 'later', 'mothers', 'new', 'islands', 'son', 'del', 'married', 'war', 'time', 'conquest', 'men', 'years', 'city', 'expedition'} {'corts', 'aztec', 'castile', 'xavier', 'columbus', 'madero', 'almagro', 'franco', 'mexico', 'portuguese', 'moctezuma', 'cid', 'afonso', 'portugal', 'alfonso'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_13
  WTF: {'earl', 'duke', 'prince', 'royal', 'marriage', 'death', 'ii', 'died', 'reign', 'succession', 'throne'} {'william', 'edward', 'england', 'wales', 'elizabeth', 'mary', 'catherine', 'charles', 'scotland', 'henry', 'henrys'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_14
  WTF: {'championship', 'lost', 'grand', 'tennis', 'wickets'} {'muralitharan', 'agassi', 'jordan', 'schumacher', 'earnhardt'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_15
  WTF: {'evolutionary', 'global', 'theory', 'environmental', 'life', 'work', 'singer', 'pp', 'published', 'climate', 'book'} {'lyell', 'wallace', 'darwin', 'slotten', 'rushton', 'mayr', 'louis', 'haeckel', 'jensen', 'wilson', 'lomborg'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_16
  WTF: {'little', 'christian', 'paintings', 'life', 'work', 'new', 'hans', 'award', 'art', 'published', 'don', 'collection', '2005'} {'prideaux', 'kafkas', 'munch', 'aalto', 'fafhrd', 'nansen', 'kafka', 'munchs', 'andersen', 'alvar', 'mouser', 'eggum', 'ibsen'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_17
  WTF: {'seminary', 'work', 'study', 'new', 'studies', 'prophets', 'rabbis', 'theology', 'sabbath', 'scholars', 'conservative', 'theological'} {'neusners', 'hebrew', 'jewish', 'kaplan', 'kaplans', 'talmud', 'steinsaltz', 'judaism', 'torah', 'jts', 'neusner', 'heschel'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_18
  WTF: {'john', 'crusaders', 'death', 'minor', 'emperors', '1180', 'iv', 'married', 'fleet', 'daughter', 'crusade', 'greek', '1204'} {'byzantine', 'maria', 'isaac', 'doukas', 'thrace', 'alexios', 'kanaris', 'komnenos', 'andronikos', 'constantinople', 'komnene', 'manuel', 'nikephoros'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_19
  WTF: {'tigers', 'allstar', 'american', 'commissioner', 'hit', 'pitched'} {'greenberg', 'cy', 'rockne', 'milwaukee', 'youngs', 'mlb'}
  WTF?!?!? 6
  WTF?!?!? 6

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f9ffb423760>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f9ffb7040d0>}
{'perplexity': 326901.21875, 'coherence_20': 0.6129705773605179, 'diversity_euclidean': 0.028391503062408778, 'diversity_jensenshannon': 0.5906524243879305, 'diversity_hellinger': 0.6840093168321064, 'diversity_cosine': 0.6119799845201385, 'fair_ppl_free': 2973.170654296875, 'fair_ppl_fix': 351438.46875, 'unfair_ppl_banklike': 326901.21875}
{'num_topics': 21, 'num_common_words': 65750, 'num_model_words': 155407, 'num_bt_words': 135939, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}]}
14
Num model topics: 21.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
  WTF: {'writing', 'time'} {'mary', 'lewis'}
topic_2
  WTF: {'years', 'national', 'battle', 'prime'} {'thomas', 'nelson', 'british', 'rommel'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_3
  WTF: {'2008', 'comedy', 'american', 'academy'} {'cagney', 'robeson', 'hitchcock', 'paul'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_4
  WTF: {'pope', 'later', 'new', 'da', 'musical'} {'haydn', 'chopin', 'rome', 'wk', 'borges'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_5
  WTF: {'prince', 'party', 'union', 'later', 'new', 'emperor', 'german', 'great', 'years', 'iii'} {'charlemagne', 'russian', 'trotsky', 'nicholas', 'yeltsin', 'louis', 'bismarck', 'russia', 'eugene', 'gorbachev'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_6
  WTF: {'new', 'according', 'reign', 'ad', 'time', 'century'} {'moses', 'augustus', 'rome', 'claudius', 'eusebius', 'tacitus'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_7
  WTF: {'university', 'press', 'philosophy', 'later', 'architecture', 'time', 'published', 'les', 'et'} {'paris', 'rodin', 'rousseau', 'warhol', 'wright', 'lacan', 'sartre', 'york', 'camus'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_8
  WTF: {'army', 'government', 'empire', 'new', 'al', 'son', 'muslims', 'time', 'interrogation'} {'rumi', 'muhammad', 'afghanistan', 'islamic', 'abd', 'persian', 'zubaydah', 'abu', 'cia'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_9
  WTF: {'recorded', 'tour'} {'elvis', 'presley'}
topic_10
  WTF: {'empress', 'clan', 'brown', 'month', 'emperors', 'son', 'court', 'military', 'senso', 'years', 'throne', 'sailor'} {'japanese', 'nichiren', 'minamoto', 'kurosawa', 'deng', 'varley', 'chiang', 'fujiwara', 'japan', 'yamamoto', 'chinese', 'titsingh'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_11
  WTF: {'interview', 'machine', 'program', 'project', 'language', 'award', 'information'} {'babbage', 'shannon', 'turing', 'engelbart', 'zuse', 'wikipedia', 'sanger'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_12
  WTF: {'la', 'voyage', 'later', 'mothers', 'new', 'islands', 'son', 'del', 'married', 'war', 'time', 'conquest', 'men', 'years', 'city', 'expedition'} {'corts', 'castile', 'xavier', 'columbus', 'madero', 'almagro', 'franco', 'pessoa', 'fernando', 'mexico', 'portuguese', 'moctezuma', 'cid', 'afonso', 'portugal', 'alfonso'}
  WTF?!?!? 16
  WTF?!?!? 16
topic_13
  WTF: {'earl', 'duke', 'prince', 'royal', 'marriage', 'death', 'ii', 'died', 'reign', 'succession', 'throne'} {'william', 'edward', 'england', 'wales', 'elizabeth', 'mary', 'catherine', 'charles', 'scotland', 'henry', 'henrys'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_14
  WTF: {'championship', 'lost', 'grand', 'tennis', 'wickets'} {'muralitharan', 'agassi', 'jordan', 'schumacher', 'earnhardt'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_15
  WTF: {'university', 'museum', 'life', 'film', 'best', 'works', 'new', 'play', 'work', 'award', 'polar', 'art', 'scream', 'actress', 'expedition', 'arctic'} {'prideaux', 'rasmussen', 'munch', 'finland', 'aalto', 'fridtjof', 'helsinki', 'ullmann', 'edvard', 'nansen', 'munchs', 'thule', 'norway', 'alvar', 'eggum', 'ibsen'}
  WTF?!?!? 16
  WTF?!?!? 16
topic_16
  WTF: {'man', 'university', 'edition', 'religious', 'study', 'philosophy', 'new', 'minor', 'prelude', 'religion', 'theology', 'vol', 'theological'} {'neusners', 'hebrew', 'jewish', 'jesus', 'kaplan', 'schweitzer', 'lambarn', 'albert', 'talmud', 'steinsaltz', 'judaism', 'neusner', 'heschel'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_17
  WTF: {'radio', 'featured', 'new', 'minutes', 'golf', 'time', 'composer', 'lyrics', 'shows', 'popular'} {'dowland', 'bing', 'gershwin', 'kern', 'crosby', 'elfman', 'crosbys', 'dowlands', 'broadway', 'ira'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_18
  WTF: {'tigers', 'players', 'allstar', 'hall', 'pitchers', 'hit', 'pitched'} {'greenberg', 'cy', 'doubleday', 'rockne', 'milwaukee', 'youngs', 'mlb'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_19
  WTF: {'teachings', 'synod', 'dynasty', 'religious', 'new', 'collge', 'ministers', 'city', 'churches', 'family'} {'confucius', 'confucian', 'geneva', 'calvins', 'servetus', 'confucianism', 'dupuis', 'amyraut', 'calvin', 'chinese'}
  WTF?!?!? 10
  WTF?!?!? 10
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f9ffb7350d0>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
  WTF: {'writing', 'time'} {'mary', 'lewis'}
topic_2
  WTF: {'years', 'national', 'battle', 'prime'} {'thomas', 'nelson', 'british', 'rommel'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_3
  WTF: {'2008', 'comedy', 'american', 'academy'} {'cagney', 'robeson', 'hitchcock', 'paul'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_4
  WTF: {'pope', 'later', 'new', 'da', 'musical'} {'haydn', 'chopin', 'rome', 'wk', 'borges'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_5
  WTF: {'prince', 'party', 'union', 'later', 'new', 'emperor', 'german', 'great', 'years', 'iii'} {'charlemagne', 'russian', 'trotsky', 'nicholas', 'yeltsin', 'louis', 'bismarck', 'russia', 'eugene', 'gorbachev'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_6
  WTF: {'new', 'according', 'reign', 'ad', 'time', 'century'} {'moses', 'augustus', 'rome', 'claudius', 'eusebius', 'tacitus'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_7
  WTF: {'university', 'press', 'philosophy', 'later', 'architecture', 'time', 'published', 'les', 'et'} {'paris', 'rodin', 'rousseau', 'warhol', 'wright', 'lacan', 'sartre', 'york', 'camus'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_8
  WTF: {'army', 'government', 'empire', 'new', 'al', 'son', 'muslims', 'time', 'interrogation'} {'rumi', 'muhammad', 'afghanistan', 'islamic', 'abd', 'persian', 'zubaydah', 'abu', 'cia'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_9
  WTF: {'recorded', 'tour'} {'elvis', 'presley'}
topic_10
  WTF: {'empress', 'clan', 'brown', 'month', 'emperors', 'son', 'court', 'military', 'senso', 'years', 'throne', 'sailor'} {'japanese', 'nichiren', 'minamoto', 'kurosawa', 'deng', 'varley', 'chiang', 'fujiwara', 'japan', 'yamamoto', 'chinese', 'titsingh'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_11
  WTF: {'interview', 'machine', 'program', 'project', 'language', 'award', 'information'} {'babbage', 'shannon', 'turing', 'engelbart', 'zuse', 'wikipedia', 'sanger'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_12
  WTF: {'la', 'voyage', 'later', 'mothers', 'new', 'islands', 'son', 'del', 'married', 'war', 'time', 'conquest', 'men', 'years', 'city', 'expedition'} {'corts', 'castile', 'xavier', 'columbus', 'madero', 'almagro', 'franco', 'pessoa', 'fernando', 'mexico', 'portuguese', 'moctezuma', 'cid', 'afonso', 'portugal', 'alfonso'}
  WTF?!?!? 16
  WTF?!?!? 16
topic_13
  WTF: {'earl', 'duke', 'prince', 'royal', 'marriage', 'death', 'ii', 'died', 'reign', 'succession', 'throne'} {'william', 'edward', 'england', 'wales', 'elizabeth', 'mary', 'catherine', 'charles', 'scotland', 'henry', 'henrys'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_14
  WTF: {'championship', 'lost', 'grand', 'tennis', 'wickets'} {'muralitharan', 'agassi', 'jordan', 'schumacher', 'earnhardt'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_15
  WTF: {'university', 'museum', 'life', 'film', 'best', 'works', 'new', 'play', 'work', 'award', 'polar', 'art', 'scream', 'actress', 'expedition', 'arctic'} {'prideaux', 'rasmussen', 'munch', 'finland', 'aalto', 'fridtjof', 'helsinki', 'ullmann', 'edvard', 'nansen', 'munchs', 'thule', 'norway', 'alvar', 'eggum', 'ibsen'}
  WTF?!?!? 16
  WTF?!?!? 16
topic_16
  WTF: {'man', 'university', 'edition', 'religious', 'study', 'philosophy', 'new', 'minor', 'prelude', 'religion', 'theology', 'vol', 'theological'} {'neusners', 'hebrew', 'jewish', 'jesus', 'kaplan', 'schweitzer', 'lambarn', 'albert', 'talmud', 'steinsaltz', 'judaism', 'neusner', 'heschel'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_17
  WTF: {'radio', 'featured', 'new', 'minutes', 'golf', 'time', 'composer', 'lyrics', 'shows', 'popular'} {'dowland', 'bing', 'gershwin', 'kern', 'crosby', 'elfman', 'crosbys', 'dowlands', 'broadway', 'ira'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_18
  WTF: {'tigers', 'players', 'allstar', 'hall', 'pitchers', 'hit', 'pitched'} {'greenberg', 'cy', 'doubleday', 'rockne', 'milwaukee', 'youngs', 'mlb'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_19
  WTF: {'teachings', 'synod', 'dynasty', 'religious', 'new', 'collge', 'ministers', 'city', 'churches', 'family'} {'confucius', 'confucian', 'geneva', 'calvins', 'servetus', 'confucianism', 'dupuis', 'amyraut', 'calvin', 'chinese'}
  WTF?!?!? 10
  WTF?!?!? 10

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7fa019095280>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7fa018ea5670>}
{'perplexity': 376379.34375, 'coherence_20': 0.6326612234326658, 'diversity_euclidean': 0.027334151323132785, 'diversity_jensenshannon': 0.592268348492124, 'diversity_hellinger': 0.6863913292903551, 'diversity_cosine': 0.6125646336601248, 'fair_ppl_free': 2976.813232421875, 'fair_ppl_fix': 354028.21875, 'unfair_ppl_banklike': 376379.34375}
{'num_topics': 21, 'num_common_words': 65750, 'num_model_words': 155407, 'num_bt_words': 135939, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 32, 'lost_bt': 16, 'lost_model': 16}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 32, 'lost_bt': 16, 'lost_model': 16}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}]}
15
Num model topics: 21.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
  WTF: {'ii', 'time', 'god'} {'louis', 'augustus', 'rome'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_2
  WTF: {'writing', 'time'} {'mary', 'lewis'}
topic_3
  WTF: {'pope', 'later', 'new', 'da', 'musical'} {'haydn', 'chopin', 'rome', 'wk', 'borges'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_4
  WTF: {'battle', 'prime', 'american', 'house', 'years'} {'oswald', 'thomas', 'british', 'rommel', 'nelson'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_5
  WTF: {'2008', 'comedy', 'career', 'academy'} {'cagney', 'robeson', 'hitchcock', 'paul'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_6
  WTF: {'press', 'philosophy', 'later', 'du', 'published', 'time', 'les', 'corbusier', 'years', 'et'} {'david', 'paris', 'satie', 'erasmus', 'rodin', 'rousseau', 'warhol', 'lacan', 'sartre', 'camus'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_7
  WTF: {'guitar', 'love'} {'elvis', 'presley'}
topic_8
  WTF: {'army', 'government', 'empire', 'new', 'al', 'son', 'muslims', 'time', 'interrogation'} {'rumi', 'muhammad', 'afghanistan', 'islamic', 'abd', 'persian', 'zubaydah', 'abu', 'cia'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_9
  WTF: {'empress', 'clan', 'brown', 'month', 'emperors', 'son', 'court', 'military', 'senso', 'years', 'throne', 'sailor'} {'japanese', 'nichiren', 'minamoto', 'kurosawa', 'deng', 'varley', 'chiang', 'fujiwara', 'japan', 'yamamoto', 'chinese', 'titsingh'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_10
  WTF: {'army', 'government', 'chess', 'revolution', 'life', 'film', 'later', 'committee', 'new', 'world', 'military', 'time', 'order', 'state'} {'stalin', 'russian', 'beria', 'philby', 'trotsky', 'nicholas', 'alexander', 'chekhov', 'yeltsin', 'russia', 'moscow', 'tito', 'kasparov', 'gorbachev'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_11
  WTF: {'voyage', 'later', 'mothers', 'new', 'islands', 'son', 'del', 'married', 'war', 'time', 'conquest', 'men', 'years', 'city', 'expedition'} {'corts', 'aztec', 'castile', 'xavier', 'columbus', 'madero', 'almagro', 'franco', 'mexico', 'portuguese', 'moctezuma', 'cid', 'afonso', 'portugal', 'alfonso'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_12
  WTF: {'evolutionary', 'press', 'life', 'research', 'pp', 'society', 'geology', 'published', 'book'} {'lyell', 'wallace', 'darwin', 'mayr', 'louis', 'haeckel', 'jensen', 'london', 'lomborg'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_13
  WTF: {'earl', 'duke', 'prince', 'royal', 'marriage', 'death', 'ii', 'died', 'reign', 'succession', 'throne'} {'william', 'edward', 'england', 'wales', 'elizabeth', 'mary', 'catherine', 'charles', 'scotland', 'henry', 'henrys'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_14
  WTF: {'championship', 'lost', 'grand', 'tennis', 'wickets'} {'muralitharan', 'agassi', 'jordan', 'schumacher', 'earnhardt'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_15
  WTF: {'little', 'museum', 'christian', 'paintings', 'life', 'works', 'work', 'new', 'award', 'art', 'published', 'collection', '2005'} {'prideaux', 'kafkas', 'munch', 'aalto', 'fafhrd', 'nansen', 'kafka', 'munchs', 'andersen', 'alvar', 'mouser', 'eggum', 'ibsen'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_16
  WTF: {'blues', 'allstar', 'record', 'pitchers', 'player', 'pitched'} {'greenberg', 'nhl', 'doubleday', 'rockne', 'milwaukee', 'youngs'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_17
  WTF: {'architectural', 'glass', 'home', 'houses', 'art', 'tower', 'designs'} {'chicago', 'wrights', 'lloyd', 'pei', 'wright', 'lin', 'mies'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_18
  WTF: {'radio', 'featured', 'new', 'minutes', 'golf', 'time', 'composer', 'lyrics', 'shows', 'popular'} {'dowland', 'bing', 'gershwin', 'kern', 'crosby', 'elfman', 'crosbys', 'dowlands', 'broadway', 'ira'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_19
  WTF: {'seminary', 'work', 'study', 'new', 'studies', 'prophets', 'rabbis', 'theology', 'sabbath', 'scholars', 'conservative', 'theological'} {'neusners', 'hebrew', 'jewish', 'kaplan', 'kaplans', 'talmud', 'steinsaltz', 'judaism', 'torah', 'jts', 'neusner', 'heschel'}
  WTF?!?!? 12
  WTF?!?!? 12
{'fix': <__main__.FastFixPhiRegularizer object at 0x7fa0196c0160>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
  WTF: {'ii', 'time', 'god'} {'louis', 'augustus', 'rome'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_2
  WTF: {'writing', 'time'} {'mary', 'lewis'}
topic_3
  WTF: {'pope', 'later', 'new', 'da', 'musical'} {'haydn', 'chopin', 'rome', 'wk', 'borges'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_4
  WTF: {'battle', 'prime', 'american', 'house', 'years'} {'oswald', 'thomas', 'british', 'rommel', 'nelson'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_5
  WTF: {'2008', 'comedy', 'career', 'academy'} {'cagney', 'robeson', 'hitchcock', 'paul'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_6
  WTF: {'press', 'philosophy', 'later', 'du', 'published', 'time', 'les', 'corbusier', 'years', 'et'} {'david', 'paris', 'satie', 'erasmus', 'rodin', 'rousseau', 'warhol', 'lacan', 'sartre', 'camus'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_7
  WTF: {'guitar', 'love'} {'elvis', 'presley'}
topic_8
  WTF: {'army', 'government', 'empire', 'new', 'al', 'son', 'muslims', 'time', 'interrogation'} {'rumi', 'muhammad', 'afghanistan', 'islamic', 'abd', 'persian', 'zubaydah', 'abu', 'cia'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_9
  WTF: {'empress', 'clan', 'brown', 'month', 'emperors', 'son', 'court', 'military', 'senso', 'years', 'throne', 'sailor'} {'japanese', 'nichiren', 'minamoto', 'kurosawa', 'deng', 'varley', 'chiang', 'fujiwara', 'japan', 'yamamoto', 'chinese', 'titsingh'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_10
  WTF: {'army', 'government', 'chess', 'revolution', 'life', 'film', 'later', 'committee', 'new', 'world', 'military', 'time', 'order', 'state'} {'stalin', 'russian', 'beria', 'philby', 'trotsky', 'nicholas', 'alexander', 'chekhov', 'yeltsin', 'russia', 'moscow', 'tito', 'kasparov', 'gorbachev'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_11
  WTF: {'voyage', 'later', 'mothers', 'new', 'islands', 'son', 'del', 'married', 'war', 'time', 'conquest', 'men', 'years', 'city', 'expedition'} {'corts', 'aztec', 'castile', 'xavier', 'columbus', 'madero', 'almagro', 'franco', 'mexico', 'portuguese', 'moctezuma', 'cid', 'afonso', 'portugal', 'alfonso'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_12
  WTF: {'evolutionary', 'press', 'life', 'research', 'pp', 'society', 'geology', 'published', 'book'} {'lyell', 'wallace', 'darwin', 'mayr', 'louis', 'haeckel', 'jensen', 'london', 'lomborg'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_13
  WTF: {'earl', 'duke', 'prince', 'royal', 'marriage', 'death', 'ii', 'died', 'reign', 'succession', 'throne'} {'william', 'edward', 'england', 'wales', 'elizabeth', 'mary', 'catherine', 'charles', 'scotland', 'henry', 'henrys'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_14
  WTF: {'championship', 'lost', 'grand', 'tennis', 'wickets'} {'muralitharan', 'agassi', 'jordan', 'schumacher', 'earnhardt'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_15
  WTF: {'little', 'museum', 'christian', 'paintings', 'life', 'works', 'work', 'new', 'award', 'art', 'published', 'collection', '2005'} {'prideaux', 'kafkas', 'munch', 'aalto', 'fafhrd', 'nansen', 'kafka', 'munchs', 'andersen', 'alvar', 'mouser', 'eggum', 'ibsen'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_16
  WTF: {'blues', 'allstar', 'record', 'pitchers', 'player', 'pitched'} {'greenberg', 'nhl', 'doubleday', 'rockne', 'milwaukee', 'youngs'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_17
  WTF: {'architectural', 'glass', 'home', 'houses', 'art', 'tower', 'designs'} {'chicago', 'wrights', 'lloyd', 'pei', 'wright', 'lin', 'mies'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_18
  WTF: {'radio', 'featured', 'new', 'minutes', 'golf', 'time', 'composer', 'lyrics', 'shows', 'popular'} {'dowland', 'bing', 'gershwin', 'kern', 'crosby', 'elfman', 'crosbys', 'dowlands', 'broadway', 'ira'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_19
  WTF: {'seminary', 'work', 'study', 'new', 'studies', 'prophets', 'rabbis', 'theology', 'sabbath', 'scholars', 'conservative', 'theological'} {'neusners', 'hebrew', 'jewish', 'kaplan', 'kaplans', 'talmud', 'steinsaltz', 'judaism', 'torah', 'jts', 'neusner', 'heschel'}
  WTF?!?!? 12
  WTF?!?!? 12

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7fa0196eee50>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7fa0190a03a0>}
{'perplexity': 336954.3125, 'coherence_20': 0.6467578634855055, 'diversity_euclidean': 0.02848992702925148, 'diversity_jensenshannon': 0.5916321452129447, 'diversity_hellinger': 0.6852134699810333, 'diversity_cosine': 0.6177501242700735, 'fair_ppl_free': 2981.325439453125, 'fair_ppl_fix': 323583.21875, 'unfair_ppl_banklike': 336954.3125}
{'num_topics': 21, 'num_common_words': 65750, 'num_model_words': 155407, 'num_bt_words': 135939, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}]}
16
Num model topics: 21.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
  WTF: {'years', 'later'} {'kepler', 'crick'}
topic_1
  WTF: {'writing', 'poems', 'literary'} {'mary', 'lewis', 'tolkien'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_2
  WTF: {'2008', 'comedy', 'career', 'academy'} {'cagney', 'robeson', 'hitchcock', 'paul'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_3
  WTF: {'house', 'years', 'battle', 'prime'} {'thomas', 'nelson', 'british', 'rommel'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_4
  WTF: {'pope', 'film', 'new', 'giovanni', 'years'} {'fellini', 'haydn', 'rome', 'wk', 'borges'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_5
  WTF: {'new', 'reign', 'ad', 'time', 'century', 'greek'} {'barnes', 'augustus', 'rome', 'claudius', 'eusebius', 'tacitus'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_6
  WTF: {'university', 'later', 'architecture', 'published', 'time', 'design', 'isbn', 'et'} {'paris', 'rodin', 'rousseau', 'warhol', 'wright', 'lacan', 'sartre', 'york'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_7
  WTF: {'army', 'government', 'empire', 'new', 'al', 'son', 'muslims', 'time', 'interrogation'} {'rumi', 'muhammad', 'afghanistan', 'islamic', 'abd', 'persian', 'zubaydah', 'abu', 'cia'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_8
  WTF: {'recorded', 'tour'} {'elvis', 'presley'}
topic_9
  WTF: {'army', 'empire', 'pope', 'death', 'died', 'married', 'military', 'german', 'years'} {'charlemagne', 'france', 'poland', 'louis', 'bismarck', 'alfred', 'frederick', 'charles', 'eugene'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_10
  WTF: {'economics', 'life', 'new', 'natural', 'research', 'pp', 'society', 'language', 'book'} {'popper', 'wallace', 'darwin', 'dewey', 'russell', 'peirce', 'hayek', 'friedman', 'london'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_11
  WTF: {'empress', 'brown', 'new', 'month', 'emperors', 'son', 'court', 'military', 'senso', 'years', 'throne', 'sailor'} {'kaunda', 'japanese', 'nichiren', 'minamoto', 'kurosawa', 'deng', 'varley', 'chiang', 'fujiwara', 'japan', 'yamamoto', 'titsingh'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_12
  WTF: {'62', 'record', 'grand', 'lost'} {'jordan', 'schumacher', 'earnhardt', 'kemp'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_13
  WTF: {'logic', 'theory', 'party', 'phenomenology', 'political', 'new', 'world', 'language', 'war', 'time', 'und', 'social', 'state'} {'reich', 'husserl', 'chomsky', 'berlin', 'nazi', 'hegel', 'habermas', 'hitler', 'hegels', 'gring', 'schwitters', 'mccarthy', 'goebbels'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_14
  WTF: {'voyage', 'later', 'mothers', 'new', 'islands', 'son', 'del', 'married', 'war', 'time', 'conquest', 'men', 'years', 'city', 'expedition'} {'corts', 'aztec', 'castile', 'xavier', 'columbus', 'madero', 'almagro', 'franco', 'mexico', 'portuguese', 'moctezuma', 'cid', 'afonso', 'portugal', 'alfonso'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_15
  WTF: {'army', 'government', 'chess', 'revolution', 'life', 'later', 'committee', 'new', 'ii', 'world', 'military', 'time', 'order', 'state'} {'stalin', 'russian', 'beria', 'philby', 'trotsky', 'nicholas', 'alexander', 'chekhov', 'yeltsin', 'russia', 'moscow', 'tito', 'kasparov', 'gorbachev'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_16
  WTF: {'earl', 'duke', 'prince', 'royal', 'marriage', 'death', 'ii', 'died', 'reign', 'succession', 'throne'} {'william', 'edward', 'england', 'wales', 'elizabeth', 'mary', 'catherine', 'charles', 'scotland', 'henry', 'henrys'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_17
  WTF: {'sand', 'museum', 'paintings', 'works', 'work', 'later', 'new', 'father', 'polar', 'art', 'scream', 'op', '2005', 'expedition'} {'prideaux', 'chopins', 'munch', 'warsaw', 'aalto', 'kafkas', 'chopin', 'nansen', 'kafka', 'munchs', 'franz', 'alvar', 'eggum', 'ibsen'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_18
  WTF: {'school', 'bible', 'christian', 'later', 'meetings', 'haven', 'dictionary', 'gin', 'children', 'published', 'spelling', 'meeting', 'years', 'church'} {'bellamy', 'webster', 'connecticut', 'alcott', 'whitney', 'eli', 'foxs', 'quakers', 'noah', 'mathers', 'mather', 'nickalls', 'yale', 'abbott'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_19
  WTF: {'seminary', 'work', 'study', 'new', 'studies', 'prophets', 'rabbis', 'theology', 'sabbath', 'scholars', 'conservative', 'theological'} {'neusners', 'hebrew', 'jewish', 'kaplan', 'kaplans', 'talmud', 'steinsaltz', 'judaism', 'torah', 'jts', 'neusner', 'heschel'}
  WTF?!?!? 12
  WTF?!?!? 12
{'fix': <__main__.FastFixPhiRegularizer object at 0x7fa019db82b0>}
Check after fit:
Skipping background topic: background_1.
topic_0
  WTF: {'years', 'later'} {'kepler', 'crick'}
topic_1
  WTF: {'writing', 'poems', 'literary'} {'mary', 'lewis', 'tolkien'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_2
  WTF: {'2008', 'comedy', 'career', 'academy'} {'cagney', 'robeson', 'hitchcock', 'paul'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_3
  WTF: {'house', 'years', 'battle', 'prime'} {'thomas', 'nelson', 'british', 'rommel'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_4
  WTF: {'pope', 'film', 'new', 'giovanni', 'years'} {'fellini', 'haydn', 'rome', 'wk', 'borges'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_5
  WTF: {'new', 'reign', 'ad', 'time', 'century', 'greek'} {'barnes', 'augustus', 'rome', 'claudius', 'eusebius', 'tacitus'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_6
  WTF: {'university', 'later', 'architecture', 'published', 'time', 'design', 'isbn', 'et'} {'paris', 'rodin', 'rousseau', 'warhol', 'wright', 'lacan', 'sartre', 'york'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_7
  WTF: {'army', 'government', 'empire', 'new', 'al', 'son', 'muslims', 'time', 'interrogation'} {'rumi', 'muhammad', 'afghanistan', 'islamic', 'abd', 'persian', 'zubaydah', 'abu', 'cia'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_8
  WTF: {'recorded', 'tour'} {'elvis', 'presley'}
topic_9
  WTF: {'army', 'empire', 'pope', 'death', 'died', 'married', 'military', 'german', 'years'} {'charlemagne', 'france', 'poland', 'louis', 'bismarck', 'alfred', 'frederick', 'charles', 'eugene'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_10
  WTF: {'economics', 'life', 'new', 'natural', 'research', 'pp', 'society', 'language', 'book'} {'popper', 'wallace', 'darwin', 'dewey', 'russell', 'peirce', 'hayek', 'friedman', 'london'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_11
  WTF: {'empress', 'brown', 'new', 'month', 'emperors', 'son', 'court', 'military', 'senso', 'years', 'throne', 'sailor'} {'kaunda', 'japanese', 'nichiren', 'minamoto', 'kurosawa', 'deng', 'varley', 'chiang', 'fujiwara', 'japan', 'yamamoto', 'titsingh'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_12
  WTF: {'62', 'record', 'grand', 'lost'} {'jordan', 'schumacher', 'earnhardt', 'kemp'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_13
  WTF: {'logic', 'theory', 'party', 'phenomenology', 'political', 'new', 'world', 'language', 'war', 'time', 'und', 'social', 'state'} {'reich', 'husserl', 'chomsky', 'berlin', 'nazi', 'hegel', 'habermas', 'hitler', 'hegels', 'gring', 'schwitters', 'mccarthy', 'goebbels'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_14
  WTF: {'voyage', 'later', 'mothers', 'new', 'islands', 'son', 'del', 'married', 'war', 'time', 'conquest', 'men', 'years', 'city', 'expedition'} {'corts', 'aztec', 'castile', 'xavier', 'columbus', 'madero', 'almagro', 'franco', 'mexico', 'portuguese', 'moctezuma', 'cid', 'afonso', 'portugal', 'alfonso'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_15
  WTF: {'army', 'government', 'chess', 'revolution', 'life', 'later', 'committee', 'new', 'ii', 'world', 'military', 'time', 'order', 'state'} {'stalin', 'russian', 'beria', 'philby', 'trotsky', 'nicholas', 'alexander', 'chekhov', 'yeltsin', 'russia', 'moscow', 'tito', 'kasparov', 'gorbachev'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_16
  WTF: {'earl', 'duke', 'prince', 'royal', 'marriage', 'death', 'ii', 'died', 'reign', 'succession', 'throne'} {'william', 'edward', 'england', 'wales', 'elizabeth', 'mary', 'catherine', 'charles', 'scotland', 'henry', 'henrys'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_17
  WTF: {'sand', 'museum', 'paintings', 'works', 'work', 'later', 'new', 'father', 'polar', 'art', 'scream', 'op', '2005', 'expedition'} {'prideaux', 'chopins', 'munch', 'warsaw', 'aalto', 'kafkas', 'chopin', 'nansen', 'kafka', 'munchs', 'franz', 'alvar', 'eggum', 'ibsen'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_18
  WTF: {'school', 'bible', 'christian', 'later', 'meetings', 'haven', 'dictionary', 'gin', 'children', 'published', 'spelling', 'meeting', 'years', 'church'} {'bellamy', 'webster', 'connecticut', 'alcott', 'whitney', 'eli', 'foxs', 'quakers', 'noah', 'mathers', 'mather', 'nickalls', 'yale', 'abbott'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_19
  WTF: {'seminary', 'work', 'study', 'new', 'studies', 'prophets', 'rabbis', 'theology', 'sabbath', 'scholars', 'conservative', 'theological'} {'neusners', 'hebrew', 'jewish', 'kaplan', 'kaplans', 'talmud', 'steinsaltz', 'judaism', 'torah', 'jts', 'neusner', 'heschel'}
  WTF?!?!? 12
  WTF?!?!? 12

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f9ffb42f7f0>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7fa019db82b0>}
{'perplexity': 340878.0, 'coherence_20': 0.5761589705225132, 'diversity_euclidean': 0.024717188371388428, 'diversity_jensenshannon': 0.5692391600541162, 'diversity_hellinger': 0.6576902617023914, 'diversity_cosine': 0.5741698657353749, 'fair_ppl_free': 2951.655517578125, 'fair_ppl_fix': 372304.34375, 'unfair_ppl_banklike': 340878.0}
{'num_topics': 21, 'num_common_words': 65750, 'num_model_words': 155407, 'num_bt_words': 135939, 'top_diffs': [{'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}]}
17
Num model topics: 21.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
  WTF: {'son', 'war', 'time'} {'louis', 'augustus', 'rome'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_1
  WTF: {'house', 'battle', 'chamberlain', 'national'} {'thomas', 'nelson', 'british', 'rommel'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_2
  WTF: {'time', 'professor'} {'kepler', 'crick'}
topic_3
  WTF: {'english', 'literary'} {'mary', 'lewis'}
topic_4
  WTF: {'2008', 'career', 'appeared', 'love'} {'cagney', 'robeson', 'hitchcock', 'paul'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_5
  WTF: {'later', 'new', 'da', 'musical', 'opera'} {'haydn', 'chopin', 'rome', 'wk', 'borges'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_6
  WTF: {'university', 'later', 'architecture', 'published', 'time', 'design', 'years', 'isbn'} {'paris', 'rodin', 'rousseau', 'warhol', 'wright', 'lacan', 'sartre', 'york'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_7
  WTF: {'army', 'government', 'empire', 'new', 'al', 'son', 'muslims', 'time', 'interrogation'} {'rumi', 'muhammad', 'afghanistan', 'islamic', 'abd', 'persian', 'zubaydah', 'abu', 'cia'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_8
  WTF: {'guitar', 'tour'} {'elvis', 'presley'}
topic_9
  WTF: {'economics', 'philosophical', 'political', 'knowledge', 'new', 'world', 'economic', 'society', 'war', 'published', 'state'} {'popper', 'russell', 'peirce', 'chomsky', 'hayek', 'hegel', 'hitler', 'hegels', 'gring', 'mccarthy', 'goebbels'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_10
  WTF: {'empress', 'clan', 'brown', 'month', 'emperors', 'son', 'court', 'military', 'senso', 'years', 'throne', 'sailor'} {'japanese', 'nichiren', 'minamoto', 'kurosawa', 'deng', 'varley', 'chiang', 'fujiwara', 'japan', 'yamamoto', 'chinese', 'titsingh'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_11
  WTF: {'interview', 'machine', 'theory', 'program', 'language', 'award', 'information'} {'babbage', 'shannon', 'turing', 'engelbart', 'zuse', 'wikipedia', 'sanger'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_12
  WTF: {'army', 'government', 'december', 'revolution', 'life', 'film', 'later', 'committee', 'new', 'world', 'military', 'time', 'order', 'state'} {'stalin', 'russian', 'beria', 'khmelnytsky', 'philby', 'trotsky', 'alexander', 'chekhov', 'yeltsin', 'russia', 'moscow', 'tito', 'kasparov', 'gorbachev'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_13
  WTF: {'voyage', 'later', 'mothers', 'new', 'islands', 'son', 'del', 'married', 'war', 'time', 'conquest', 'men', 'years', 'city', 'expedition'} {'corts', 'aztec', 'castile', 'xavier', 'columbus', 'madero', 'almagro', 'franco', 'mexico', 'portuguese', 'moctezuma', 'cid', 'afonso', 'portugal', 'alfonso'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_14
  WTF: {'evolutionary', 'life', 'research', 'pp', 'society', 'geology', 'nature', 'book'} {'lyell', 'wallace', 'darwin', 'louis', 'haeckel', 'jensen', 'lomborg', 'snyder'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_15
  WTF: {'earl', 'duke', 'prince', 'royal', 'marriage', 'death', 'ii', 'died', 'reign', 'succession', 'throne'} {'william', 'edward', 'england', 'wales', 'elizabeth', 'mary', 'catherine', 'charles', 'scotland', 'henry', 'henrys'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_16
  WTF: {'championship', 'lost', 'grand', 'tennis', 'wickets'} {'muralitharan', 'agassi', 'jordan', 'schumacher', 'earnhardt'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_17
  WTF: {'museum', 'stories', 'paintings', 'life', 'best', 'works', 'new', 'award', 'polar', 'art', 'scream', 'duck', '2005', 'expedition', 'comics'} {'prideaux', 'kafkas', 'munch', 'finland', 'aalto', 'fridtjof', 'nansen', 'kafka', 'munchs', 'barks', 'franz', 'norway', 'alvar', 'eggum', 'ibsen'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_18
  WTF: {'seminary', 'work', 'new', 'studies', 'prophets', 'theology', 'sabbath', 'scholars', 'published', 'conservative', 'theological', 'book'} {'neusners', 'hebrew', 'jewish', 'jacob', 'kaplan', 'talmud', 'steinsaltz', 'judaism', 'abendana', 'torah', 'neusner', 'heschel'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_19
  WTF: {'tigers', 'players', 'allstar', 'hall', 'pitchers', 'hit', 'pitched'} {'greenberg', 'cy', 'doubleday', 'rockne', 'milwaukee', 'youngs', 'mlb'}
  WTF?!?!? 7
  WTF?!?!? 7
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f9ff8ea5cd0>}
Check after fit:
Skipping background topic: background_1.
topic_0
  WTF: {'son', 'war', 'time'} {'louis', 'augustus', 'rome'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_1
  WTF: {'house', 'battle', 'chamberlain', 'national'} {'thomas', 'nelson', 'british', 'rommel'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_2
  WTF: {'time', 'professor'} {'kepler', 'crick'}
topic_3
  WTF: {'english', 'literary'} {'mary', 'lewis'}
topic_4
  WTF: {'2008', 'career', 'appeared', 'love'} {'cagney', 'robeson', 'hitchcock', 'paul'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_5
  WTF: {'later', 'new', 'da', 'musical', 'opera'} {'haydn', 'chopin', 'rome', 'wk', 'borges'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_6
  WTF: {'university', 'later', 'architecture', 'published', 'time', 'design', 'years', 'isbn'} {'paris', 'rodin', 'rousseau', 'warhol', 'wright', 'lacan', 'sartre', 'york'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_7
  WTF: {'army', 'government', 'empire', 'new', 'al', 'son', 'muslims', 'time', 'interrogation'} {'rumi', 'muhammad', 'afghanistan', 'islamic', 'abd', 'persian', 'zubaydah', 'abu', 'cia'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_8
  WTF: {'guitar', 'tour'} {'elvis', 'presley'}
topic_9
  WTF: {'economics', 'philosophical', 'political', 'knowledge', 'new', 'world', 'economic', 'society', 'war', 'published', 'state'} {'popper', 'russell', 'peirce', 'chomsky', 'hayek', 'hegel', 'hitler', 'hegels', 'gring', 'mccarthy', 'goebbels'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_10
  WTF: {'empress', 'clan', 'brown', 'month', 'emperors', 'son', 'court', 'military', 'senso', 'years', 'throne', 'sailor'} {'japanese', 'nichiren', 'minamoto', 'kurosawa', 'deng', 'varley', 'chiang', 'fujiwara', 'japan', 'yamamoto', 'chinese', 'titsingh'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_11
  WTF: {'interview', 'machine', 'theory', 'program', 'language', 'award', 'information'} {'babbage', 'shannon', 'turing', 'engelbart', 'zuse', 'wikipedia', 'sanger'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_12
  WTF: {'army', 'government', 'december', 'revolution', 'life', 'film', 'later', 'committee', 'new', 'world', 'military', 'time', 'order', 'state'} {'stalin', 'russian', 'beria', 'khmelnytsky', 'philby', 'trotsky', 'alexander', 'chekhov', 'yeltsin', 'russia', 'moscow', 'tito', 'kasparov', 'gorbachev'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_13
  WTF: {'voyage', 'later', 'mothers', 'new', 'islands', 'son', 'del', 'married', 'war', 'time', 'conquest', 'men', 'years', 'city', 'expedition'} {'corts', 'aztec', 'castile', 'xavier', 'columbus', 'madero', 'almagro', 'franco', 'mexico', 'portuguese', 'moctezuma', 'cid', 'afonso', 'portugal', 'alfonso'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_14
  WTF: {'evolutionary', 'life', 'research', 'pp', 'society', 'geology', 'nature', 'book'} {'lyell', 'wallace', 'darwin', 'louis', 'haeckel', 'jensen', 'lomborg', 'snyder'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_15
  WTF: {'earl', 'duke', 'prince', 'royal', 'marriage', 'death', 'ii', 'died', 'reign', 'succession', 'throne'} {'william', 'edward', 'england', 'wales', 'elizabeth', 'mary', 'catherine', 'charles', 'scotland', 'henry', 'henrys'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_16
  WTF: {'championship', 'lost', 'grand', 'tennis', 'wickets'} {'muralitharan', 'agassi', 'jordan', 'schumacher', 'earnhardt'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_17
  WTF: {'museum', 'stories', 'paintings', 'life', 'best', 'works', 'new', 'award', 'polar', 'art', 'scream', 'duck', '2005', 'expedition', 'comics'} {'prideaux', 'kafkas', 'munch', 'finland', 'aalto', 'fridtjof', 'nansen', 'kafka', 'munchs', 'barks', 'franz', 'norway', 'alvar', 'eggum', 'ibsen'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_18
  WTF: {'seminary', 'work', 'new', 'studies', 'prophets', 'theology', 'sabbath', 'scholars', 'published', 'conservative', 'theological', 'book'} {'neusners', 'hebrew', 'jewish', 'jacob', 'kaplan', 'talmud', 'steinsaltz', 'judaism', 'abendana', 'torah', 'neusner', 'heschel'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_19
  WTF: {'tigers', 'players', 'allstar', 'hall', 'pitchers', 'hit', 'pitched'} {'greenberg', 'cy', 'doubleday', 'rockne', 'milwaukee', 'youngs', 'mlb'}
  WTF?!?!? 7
  WTF?!?!? 7

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7fa019da5eb0>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7fa018daa190>}
{'perplexity': 385046.78125, 'coherence_20': 0.6262768462983989, 'diversity_euclidean': 0.027049328297710167, 'diversity_jensenshannon': 0.579906477839056, 'diversity_hellinger': 0.6708563902764687, 'diversity_cosine': 0.6018837861925072, 'fair_ppl_free': 2959.697509765625, 'fair_ppl_fix': 340666.5, 'unfair_ppl_banklike': 385046.78125}
{'num_topics': 21, 'num_common_words': 65750, 'num_model_words': 155407, 'num_bt_words': 135939, 'top_diffs': [{'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}]}
18
Num model topics: 21.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
  WTF: {'ii', 'time', 'god'} {'louis', 'augustus', 'rome'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_2
  WTF: {'chemistry', 'society', 'published'} {'darwin', 'kepler', 'crick'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_3
  WTF: {'writing', 'poems', 'literary'} {'mary', 'lewis', 'tolkien'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_4
  WTF: {'years', 'american', 'battle', 'prime'} {'nelson', 'british', 'kemp', 'rommel'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_5
  WTF: {'pope', 'new', 'musical', 'years', 'opera'} {'fellini', 'haydn', 'chopin', 'rome', 'wk'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_6
  WTF: {'university', 'philosophy', 'later', 'architecture', 'published', 'time', 'design', 'isbn'} {'paris', 'rodin', 'rousseau', 'warhol', 'wright', 'lacan', 'sartre', 'york'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_7
  WTF: {'economics', 'political', 'knowledge', 'new', 'world', 'economic', 'society', 'war', 'published', 'der'} {'popper', 'russell', 'peirce', 'chomsky', 'hayek', 'hegel', 'hitler', 'gring', 'mccarthy', 'goebbels'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_8
  WTF: {'army', 'government', 'empire', 'new', 'al', 'son', 'muslims', 'time', 'interrogation'} {'rumi', 'muhammad', 'afghanistan', 'islamic', 'abd', 'persian', 'zubaydah', 'abu', 'cia'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_9
  WTF: {'empress', 'brown', 'new', 'month', 'emperors', 'son', 'court', 'military', 'senso', 'years', 'throne', 'sailor'} {'kaunda', 'japanese', 'nichiren', 'minamoto', 'kurosawa', 'deng', 'varley', 'chiang', 'fujiwara', 'japan', 'yamamoto', 'titsingh'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_10
  WTF: {'interview', 'machine', 'theory', 'institute', 'language', 'computers', 'mathematics', 'information'} {'babbage', 'shannon', 'turing', 'engelbart', 'zuse', 'wikipedia', 'warwick', 'sanger'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_11
  WTF: {'voyage', 'later', 'mothers', 'new', 'islands', 'son', 'del', 'married', 'war', 'time', 'conquest', 'men', 'years', 'city', 'expedition'} {'corts', 'aztec', 'castile', 'xavier', 'columbus', 'madero', 'almagro', 'franco', 'mexico', 'portuguese', 'moctezuma', 'cid', 'afonso', 'portugal', 'alfonso'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_12
  WTF: {'army', 'government', 'march', 'revolution', 'life', 'film', 'committee', 'new', 'world', 'military', 'time', 'order', 'state'} {'stalin', 'russian', 'beria', 'trotsky', 'nicholas', 'alexander', 'chekhov', 'yeltsin', 'russia', 'moscow', 'tito', 'kasparov', 'gorbachev'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_13
  WTF: {'earl', 'duke', 'prince', 'royal', 'marriage', 'death', 'ii', 'died', 'reign', 'succession', 'throne'} {'william', 'edward', 'england', 'wales', 'elizabeth', 'mary', 'catherine', 'charles', 'scotland', 'henry', 'henrys'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_14
  WTF: {'championship', 'lost', 'grand', 'tennis', 'wickets'} {'muralitharan', 'agassi', 'jordan', 'schumacher', 'earnhardt'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_15
  WTF: {'little', 'christian', 'paintings', 'life', 'works', 'short', 'best', 'new', 'work', 'art', 'published', '2005', 'comics'} {'prideaux', 'kafkas', 'munch', 'aalto', 'nansen', 'kafka', 'munchs', 'andersen', 'franz', 'norway', 'alvar', 'eggum', 'ibsen'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_16
  WTF: {'christian', 'life', 'later', 'meetings', 'haven', 'dictionary', 'gin', 'children', 'published', 'spelling', 'meeting', 'years', 'isbn', 'church'} {'bellamy', 'margaret', 'webster', 'connecticut', 'mead', 'alcott', 'whitney', 'eli', 'foxs', 'quakers', 'mather', 'nickalls', 'yale', 'abbott'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_17
  WTF: {'skeptical', '2002', 'genome', 'chapter', 'american', 'research', 'self', 'carl', 'behavior'} {'rogers', 'venter', 'rushton', 'leakey', 'louis', 'jensen', 'wilson', 'lomborg', 'snyder'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_18
  WTF: {'tigers', 'players', 'allstar', 'hall', 'pitchers', 'hit', 'pitched'} {'greenberg', 'cy', 'doubleday', 'rockne', 'milwaukee', 'youngs', 'mlb'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_19
  WTF: {'seminary', 'work', 'study', 'new', 'studies', 'prophets', 'rabbis', 'theology', 'sabbath', 'scholars', 'conservative', 'theological'} {'neusners', 'hebrew', 'jewish', 'kaplan', 'kaplans', 'talmud', 'steinsaltz', 'judaism', 'torah', 'jts', 'neusner', 'heschel'}
  WTF?!?!? 12
  WTF?!?!? 12
{'fix': <__main__.FastFixPhiRegularizer object at 0x7fa019224fd0>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
  WTF: {'ii', 'time', 'god'} {'louis', 'augustus', 'rome'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_2
  WTF: {'chemistry', 'society', 'published'} {'darwin', 'kepler', 'crick'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_3
  WTF: {'writing', 'poems', 'literary'} {'mary', 'lewis', 'tolkien'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_4
  WTF: {'years', 'american', 'battle', 'prime'} {'nelson', 'british', 'kemp', 'rommel'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_5
  WTF: {'pope', 'new', 'musical', 'years', 'opera'} {'fellini', 'haydn', 'chopin', 'rome', 'wk'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_6
  WTF: {'university', 'philosophy', 'later', 'architecture', 'published', 'time', 'design', 'isbn'} {'paris', 'rodin', 'rousseau', 'warhol', 'wright', 'lacan', 'sartre', 'york'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_7
  WTF: {'economics', 'political', 'knowledge', 'new', 'world', 'economic', 'society', 'war', 'published', 'der'} {'popper', 'russell', 'peirce', 'chomsky', 'hayek', 'hegel', 'hitler', 'gring', 'mccarthy', 'goebbels'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_8
  WTF: {'army', 'government', 'empire', 'new', 'al', 'son', 'muslims', 'time', 'interrogation'} {'rumi', 'muhammad', 'afghanistan', 'islamic', 'abd', 'persian', 'zubaydah', 'abu', 'cia'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_9
  WTF: {'empress', 'brown', 'new', 'month', 'emperors', 'son', 'court', 'military', 'senso', 'years', 'throne', 'sailor'} {'kaunda', 'japanese', 'nichiren', 'minamoto', 'kurosawa', 'deng', 'varley', 'chiang', 'fujiwara', 'japan', 'yamamoto', 'titsingh'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_10
  WTF: {'interview', 'machine', 'theory', 'institute', 'language', 'computers', 'mathematics', 'information'} {'babbage', 'shannon', 'turing', 'engelbart', 'zuse', 'wikipedia', 'warwick', 'sanger'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_11
  WTF: {'voyage', 'later', 'mothers', 'new', 'islands', 'son', 'del', 'married', 'war', 'time', 'conquest', 'men', 'years', 'city', 'expedition'} {'corts', 'aztec', 'castile', 'xavier', 'columbus', 'madero', 'almagro', 'franco', 'mexico', 'portuguese', 'moctezuma', 'cid', 'afonso', 'portugal', 'alfonso'}
  WTF?!?!? 15
  WTF?!?!? 15
topic_12
  WTF: {'army', 'government', 'march', 'revolution', 'life', 'film', 'committee', 'new', 'world', 'military', 'time', 'order', 'state'} {'stalin', 'russian', 'beria', 'trotsky', 'nicholas', 'alexander', 'chekhov', 'yeltsin', 'russia', 'moscow', 'tito', 'kasparov', 'gorbachev'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_13
  WTF: {'earl', 'duke', 'prince', 'royal', 'marriage', 'death', 'ii', 'died', 'reign', 'succession', 'throne'} {'william', 'edward', 'england', 'wales', 'elizabeth', 'mary', 'catherine', 'charles', 'scotland', 'henry', 'henrys'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_14
  WTF: {'championship', 'lost', 'grand', 'tennis', 'wickets'} {'muralitharan', 'agassi', 'jordan', 'schumacher', 'earnhardt'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_15
  WTF: {'little', 'christian', 'paintings', 'life', 'works', 'short', 'best', 'new', 'work', 'art', 'published', '2005', 'comics'} {'prideaux', 'kafkas', 'munch', 'aalto', 'nansen', 'kafka', 'munchs', 'andersen', 'franz', 'norway', 'alvar', 'eggum', 'ibsen'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_16
  WTF: {'christian', 'life', 'later', 'meetings', 'haven', 'dictionary', 'gin', 'children', 'published', 'spelling', 'meeting', 'years', 'isbn', 'church'} {'bellamy', 'margaret', 'webster', 'connecticut', 'mead', 'alcott', 'whitney', 'eli', 'foxs', 'quakers', 'mather', 'nickalls', 'yale', 'abbott'}
  WTF?!?!? 14
  WTF?!?!? 14
topic_17
  WTF: {'skeptical', '2002', 'genome', 'chapter', 'american', 'research', 'self', 'carl', 'behavior'} {'rogers', 'venter', 'rushton', 'leakey', 'louis', 'jensen', 'wilson', 'lomborg', 'snyder'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_18
  WTF: {'tigers', 'players', 'allstar', 'hall', 'pitchers', 'hit', 'pitched'} {'greenberg', 'cy', 'doubleday', 'rockne', 'milwaukee', 'youngs', 'mlb'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_19
  WTF: {'seminary', 'work', 'study', 'new', 'studies', 'prophets', 'rabbis', 'theology', 'sabbath', 'scholars', 'conservative', 'theological'} {'neusners', 'hebrew', 'jewish', 'kaplan', 'kaplans', 'talmud', 'steinsaltz', 'judaism', 'torah', 'jts', 'neusner', 'heschel'}
  WTF?!?!? 12
  WTF?!?!? 12

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7fa004fcccd0>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7fa040780070>}
{'perplexity': 336125.5625, 'coherence_20': 0.5995287421362379, 'diversity_euclidean': 0.027281400822544367, 'diversity_jensenshannon': 0.5857990675564345, 'diversity_hellinger': 0.6785349038499938, 'diversity_cosine': 0.6039264166817916, 'fair_ppl_free': 2974.361572265625, 'fair_ppl_fix': 348602.0625, 'unfair_ppl_banklike': 336125.5625}
{'num_topics': 21, 'num_common_words': 65750, 'num_model_words': 155407, 'num_bt_words': 135939, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 30, 'lost_bt': 15, 'lost_model': 15}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 28, 'lost_bt': 14, 'lost_model': 14}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}]}
19
Num model topics: 21.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
  WTF: {'son', 'great'} {'augustus', 'rome'}
topic_2
  WTF: {'english', 'university'} {'mary', 'lewis'}
topic_3
  WTF: {'house', 'years', 'national', 'battle'} {'thomas', 'nelson', 'british', 'rommel'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_4
  WTF: {'2008', 'comedy', 'american', 'career'} {'cagney', 'robeson', 'hitchcock', 'paul'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_5
  WTF: {'university', 'later', 'architecture', 'published', 'time', 'design', 'isbn', 'et'} {'paris', 'rodin', 'rousseau', 'warhol', 'wright', 'lacan', 'sartre', 'york'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_6
  WTF: {'life', 'film', 'work', 'polo', 'fra', 'del', 'san', 'renaissance', 'years', 'st'} {'fellini', 'lucrezia', 'borgia', 'bruno', 'rome', 'francis', 'marco', 'florence', 'caravaggio', 'calvino'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_7
  WTF: {'guitar', 'love'} {'elvis', 'presley'}
topic_8
  WTF: {'army', 'government', 'empire', 'new', 'al', 'son', 'muslims', 'time', 'interrogation'} {'rumi', 'muhammad', 'afghanistan', 'islamic', 'abd', 'persian', 'zubaydah', 'abu', 'cia'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_9
  WTF: {'empress', 'brown', 'new', 'month', 'emperors', 'son', 'court', 'military', 'senso', 'years', 'throne', 'sailor'} {'kaunda', 'japanese', 'nichiren', 'minamoto', 'kurosawa', 'deng', 'varley', 'chiang', 'fujiwara', 'japan', 'yamamoto', 'titsingh'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_10
  WTF: {'la', 'voyage', 'later', 'mothers', 'new', 'islands', 'son', 'del', 'married', 'war', 'time', 'conquest', 'men', 'years', 'city', 'expedition'} {'corts', 'castile', 'xavier', 'columbus', 'madero', 'almagro', 'franco', 'pessoa', 'fernando', 'mexico', 'portuguese', 'moctezuma', 'cid', 'afonso', 'portugal', 'alfonso'}
  WTF?!?!? 16
  WTF?!?!? 16
topic_11
  WTF: {'earl', 'duke', 'prince', 'royal', 'marriage', 'death', 'ii', 'died', 'reign', 'succession', 'throne'} {'william', 'edward', 'england', 'wales', 'elizabeth', 'mary', 'catherine', 'charles', 'scotland', 'henry', 'henrys'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_12
  WTF: {'trio', 'concerto', 'work', 'words', 'string', 'da', 'musical', 'quartet'} {'handel', 'haydn', 'shostakovich', 'wk', 'vienna', 'elgar', 'hoffmann', 'lugosi'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_13
  WTF: {'championship', 'lost', 'grand', 'tennis', 'wickets'} {'muralitharan', 'agassi', 'jordan', 'schumacher', 'earnhardt'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_14
  WTF: {'philosophical', 'work', 'new', 'psychology', 'sign', 'scientific', 'world', 'society', 'published', 'social', 'behavior', 'object'} {'peirces', 'milken', 'popper', 'dewey', 'russell', 'peirce', 'chomsky', 'hayek', 'skinner', 'friedman', 'russells', 'rothbard'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_15
  WTF: {'little', 'christian', 'paintings', 'life', 'works', 'short', 'best', 'new', 'work', 'art', 'published', '2005', 'comics'} {'prideaux', 'kafkas', 'munch', 'aalto', 'nansen', 'kafka', 'munchs', 'andersen', 'franz', 'norway', 'alvar', 'eggum', 'ibsen'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_16
  WTF: {'tigers', 'players', 'allstar', 'hall', 'pitchers', 'hit', 'pitched'} {'greenberg', 'cy', 'doubleday', 'rockne', 'milwaukee', 'youngs', 'mlb'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_17
  WTF: {'john', 'crusaders', 'death', 'minor', 'emperors', '1180', 'iv', 'married', 'fleet', 'daughter', 'crusade', 'greek', '1204'} {'byzantine', 'maria', 'isaac', 'doukas', 'thrace', 'alexios', 'kanaris', 'komnenos', 'andronikos', 'constantinople', 'komnene', 'manuel', 'nikephoros'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_18
  WTF: {'radio', 'featured', 'new', 'minutes', 'golf', 'time', 'composer', 'lyrics', 'shows', 'popular'} {'dowland', 'bing', 'gershwin', 'kern', 'crosby', 'elfman', 'crosbys', 'dowlands', 'broadway', 'ira'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_19
  WTF: {'seminary', 'work', 'study', 'new', 'studies', 'prophets', 'rabbis', 'theology', 'sabbath', 'scholars', 'conservative', 'theological'} {'neusners', 'hebrew', 'jewish', 'kaplan', 'kaplans', 'talmud', 'steinsaltz', 'judaism', 'torah', 'jts', 'neusner', 'heschel'}
  WTF?!?!? 12
  WTF?!?!? 12
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f9ffb1491f0>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
  WTF: {'son', 'great'} {'augustus', 'rome'}
topic_2
  WTF: {'english', 'university'} {'mary', 'lewis'}
topic_3
  WTF: {'house', 'years', 'national', 'battle'} {'thomas', 'nelson', 'british', 'rommel'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_4
  WTF: {'2008', 'comedy', 'american', 'career'} {'cagney', 'robeson', 'hitchcock', 'paul'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_5
  WTF: {'university', 'later', 'architecture', 'published', 'time', 'design', 'isbn', 'et'} {'paris', 'rodin', 'rousseau', 'warhol', 'wright', 'lacan', 'sartre', 'york'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_6
  WTF: {'life', 'film', 'work', 'polo', 'fra', 'del', 'san', 'renaissance', 'years', 'st'} {'fellini', 'lucrezia', 'borgia', 'bruno', 'rome', 'francis', 'marco', 'florence', 'caravaggio', 'calvino'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_7
  WTF: {'guitar', 'love'} {'elvis', 'presley'}
topic_8
  WTF: {'army', 'government', 'empire', 'new', 'al', 'son', 'muslims', 'time', 'interrogation'} {'rumi', 'muhammad', 'afghanistan', 'islamic', 'abd', 'persian', 'zubaydah', 'abu', 'cia'}
  WTF?!?!? 9
  WTF?!?!? 9
topic_9
  WTF: {'empress', 'brown', 'new', 'month', 'emperors', 'son', 'court', 'military', 'senso', 'years', 'throne', 'sailor'} {'kaunda', 'japanese', 'nichiren', 'minamoto', 'kurosawa', 'deng', 'varley', 'chiang', 'fujiwara', 'japan', 'yamamoto', 'titsingh'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_10
  WTF: {'la', 'voyage', 'later', 'mothers', 'new', 'islands', 'son', 'del', 'married', 'war', 'time', 'conquest', 'men', 'years', 'city', 'expedition'} {'corts', 'castile', 'xavier', 'columbus', 'madero', 'almagro', 'franco', 'pessoa', 'fernando', 'mexico', 'portuguese', 'moctezuma', 'cid', 'afonso', 'portugal', 'alfonso'}
  WTF?!?!? 16
  WTF?!?!? 16
topic_11
  WTF: {'earl', 'duke', 'prince', 'royal', 'marriage', 'death', 'ii', 'died', 'reign', 'succession', 'throne'} {'william', 'edward', 'england', 'wales', 'elizabeth', 'mary', 'catherine', 'charles', 'scotland', 'henry', 'henrys'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_12
  WTF: {'trio', 'concerto', 'work', 'words', 'string', 'da', 'musical', 'quartet'} {'handel', 'haydn', 'shostakovich', 'wk', 'vienna', 'elgar', 'hoffmann', 'lugosi'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_13
  WTF: {'championship', 'lost', 'grand', 'tennis', 'wickets'} {'muralitharan', 'agassi', 'jordan', 'schumacher', 'earnhardt'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_14
  WTF: {'philosophical', 'work', 'new', 'psychology', 'sign', 'scientific', 'world', 'society', 'published', 'social', 'behavior', 'object'} {'peirces', 'milken', 'popper', 'dewey', 'russell', 'peirce', 'chomsky', 'hayek', 'skinner', 'friedman', 'russells', 'rothbard'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_15
  WTF: {'little', 'christian', 'paintings', 'life', 'works', 'short', 'best', 'new', 'work', 'art', 'published', '2005', 'comics'} {'prideaux', 'kafkas', 'munch', 'aalto', 'nansen', 'kafka', 'munchs', 'andersen', 'franz', 'norway', 'alvar', 'eggum', 'ibsen'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_16
  WTF: {'tigers', 'players', 'allstar', 'hall', 'pitchers', 'hit', 'pitched'} {'greenberg', 'cy', 'doubleday', 'rockne', 'milwaukee', 'youngs', 'mlb'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_17
  WTF: {'john', 'crusaders', 'death', 'minor', 'emperors', '1180', 'iv', 'married', 'fleet', 'daughter', 'crusade', 'greek', '1204'} {'byzantine', 'maria', 'isaac', 'doukas', 'thrace', 'alexios', 'kanaris', 'komnenos', 'andronikos', 'constantinople', 'komnene', 'manuel', 'nikephoros'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_18
  WTF: {'radio', 'featured', 'new', 'minutes', 'golf', 'time', 'composer', 'lyrics', 'shows', 'popular'} {'dowland', 'bing', 'gershwin', 'kern', 'crosby', 'elfman', 'crosbys', 'dowlands', 'broadway', 'ira'}
  WTF?!?!? 10
  WTF?!?!? 10
topic_19
  WTF: {'seminary', 'work', 'study', 'new', 'studies', 'prophets', 'rabbis', 'theology', 'sabbath', 'scholars', 'conservative', 'theological'} {'neusners', 'hebrew', 'jewish', 'kaplan', 'kaplans', 'talmud', 'steinsaltz', 'judaism', 'torah', 'jts', 'neusner', 'heschel'}
  WTF?!?!? 12
  WTF?!?!? 12

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f9ffb423700>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f9ffb40d4f0>}
{'perplexity': 350092.53125, 'coherence_20': 0.6586360587821484, 'diversity_euclidean': 0.029423612954354885, 'diversity_jensenshannon': 0.6011181813850918, 'diversity_hellinger': 0.6972345241836143, 'diversity_cosine': 0.6299226275525601, 'fair_ppl_free': 2988.765380859375, 'fair_ppl_fix': 334162.625, 'unfair_ppl_banklike': 350092.53125}
{'num_topics': 21, 'num_common_words': 65750, 'num_model_words': 155407, 'num_bt_words': 135939, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 18, 'lost_bt': 9, 'lost_model': 9}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 32, 'lost_bt': 16, 'lost_model': 16}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 20, 'lost_bt': 10, 'lost_model': 10}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}]}

In [3]:
! ls results/rtlwikiperson/bertopic

bertopic_0.json   bertopic_14.json  bertopic_19.json  bertopic_5.json
bertopic_10.json  bertopic_15.json  bertopic_1.json   bertopic_6.json
bertopic_11.json  bertopic_16.json  bertopic_2.json   bertopic_7.json
bertopic_12.json  bertopic_17.json  bertopic_3.json   bertopic_8.json
bertopic_13.json  bertopic_18.json  bertopic_4.json   bertopic_9.json

In [4]:
! ls results50/rtlwikiperson/bertopic

bertopic_0.json   bertopic_14.json  bertopic_19.json  bertopic_5.json
bertopic_10.json  bertopic_15.json  bertopic_1.json   bertopic_6.json
bertopic_11.json  bertopic_16.json  bertopic_2.json   bertopic_7.json
bertopic_12.json  bertopic_17.json  bertopic_3.json   bertopic_8.json
bertopic_13.json  bertopic_18.json  bertopic_4.json   bertopic_9.json