In [1]:
import os
import json
import shutil
import sys
import time

import numpy as np
import scipy

In [2]:
sys.path.insert(0, '../OptimalNumberOfTopics')

In [3]:
import topnum

from topnum.scores.perplexity_score import PerplexityScore
from topnum.scores.diversity_score import DiversityScore, KNOWN_METRICS
from topnum.model_constructor import init_model_from_family, KnownModel, PARAMS_EXPLORED, init_plsa

from topnum.regularizers import (
    FastFixPhiRegularizer, DecorrelateWithOtherPhiRegularizer, DecorrelateWithOtherPhiRegularizer2
)
from topnum.scores.intratext_coherence_score import (
    IntratextCoherenceScore,
    ComputationMethod,
    WordTopicRelatednessType,
)

In [4]:
import artm
from artm import ARTM, Dictionary

import topicnet
from topicnet.cooking_machine.dataset import Dataset
from topicnet.cooking_machine.models import (
    BaseScore as BaseTopicNetScore,
    TopicModel
)
from topicnet.cooking_machine.models.base_regularizer import BaseRegularizer
from topicnet.cooking_machine.models.thetaless_regularizer import (
    dataset2sparse_matrix,
)

from topicnet.cooking_machine.models.topic_model import ARTM_NINE
from topicnet.cooking_machine.models.base_regularizer import BaseRegularizer
from topicnet.viewers.top_documents_viewer import TopDocumentsViewer
from topicnet.viewers.top_tokens_viewer import TopTokensViewer
from topicnet.cooking_machine.model_constructor import (
    add_standard_scores,
    create_default_topics,
    count_vocab_size,
    init_model,
)
from topicnet.cooking_machine.rel_toolbox_lite import (
    count_vocab_size,
    modality_weight_rel2abs,
    transform_regularizer,
)


import numpy as np
import pandas as pd
from pandas import DataFrame
from scipy.spatial.distance import cdist

import os
import tempfile
import warnings
from copy import deepcopy
from typing import Dict, List, Optional

In [5]:
NUM_TOPICS = 50

NUM_ITERATIONS = 5
NUM_TOP_TOKENS = 20
NUM_TRAINS = 20

In [9]:
BERTOPIC_FOLDER_PATH = '/data_mil/shared/CompressaAI/iterative/results/newman/BERTopic'
RESULTS_FOLDER_PATH = os.path.join(BERTOPIC_FOLDER_PATH, 'results50', '20newsgroups')

In [10]:
RESULTS_FOLDER_PATH

'/data_mil/shared/CompressaAI/iterative/results/newman/BERTopic/results50/20newsgroups'

In [11]:
! ls $RESULTS_FOLDER_PATH

0  1  10  11  12  13  14  15  16  17  18  19  2  3  4  5  6  7	8  9

In [12]:
! ls $RESULTS_FOLDER_PATH/0

dataset.csv  dataset__internals  phi.csv  top_words.json

In [13]:
dataset = Dataset(
    f'{RESULTS_FOLDER_PATH}/0/dataset.csv',
)

dataset.get_possible_modalities()

{'@lemmatized'}

In [14]:
MAIN_MODALITY = '@lemmatized'

In [15]:
def calc_doc_occurrences(dataset, modality):
    """
    :param n_dw_matrix: sparse document-word matrix, shape is D x W
    :return: sparse matrix of co-occurrences

    doc_occurrences[w1, w2] = the number of the documents
    where there are w1 and w2
    """
    n_dw_matrix = dataset2sparse_matrix(dataset, modality, modalities_to_use=[modality])
    matrix = (scipy.sparse.csc_matrix(n_dw_matrix) > 0).astype(int)
    co_occurrences = matrix.T * matrix

    return co_occurrences.diagonal(), co_occurrences


def create_pmi_top_function(
    doc_occurrences, doc_co_occurrences,
    documents_number, top_sizes,
    topic_indices,
    co_occurrences_smooth=1.
):
    """
    :param doc_occurrences: array of doc occurrences of words
    :param doc_co_occurrences: sparse matrix of doc co-occurrences of words
    :param documents_number: number of the documents
    :param top_sizes: list of top values to calculate top-pmi for
    :param co_occurrences_smooth: constant to smooth co-occurrences in log
    :return: function which takes phi and theta and returns
    pair of two arrays: pmi-s of the tops and ppmi-s of the tops

    pmi[i] - pmi(top of size top_sizes[i])
    ppmi[i] - ppmi(top of size top_sizes[i])

    pmi(words) = sum_{u in words, v in words, u != v}
    log(
        (doc_co_occurrences[u, v] * documents_number + co_occurrences_smooth)
        / doc_occurrences[u] / doc_occurrences[v]
    )

    ppmi(words) = sum_{u in words, v in words, u != v}
    max(log(
        (doc_co_occurrences[u, v] * documents_number + co_occurrences_smooth)
        / doc_occurrences[u] / doc_occurrences[v]
    ), 0)

    """
    def func(phi):
        _T, W = phi.shape
        T = len(topic_indices)

        max_top_size = max(top_sizes)
        topic_pmis, topic_ppmis = dict(), dict()
        pmi, ppmi = np.zeros(max_top_size), np.zeros(max_top_size)
        tops = np.argpartition(phi, -max_top_size, axis=1)[:, -max_top_size:]
        
        for t in topic_indices:
            top = sorted(tops[t], key=lambda w: - phi[t, w])
            co_occurrences = doc_co_occurrences[top, :][:, top].todense()
            occurrences = doc_occurrences[top]
            values = np.log(
                (co_occurrences * documents_number + co_occurrences_smooth)
                / (occurrences[:, np.newaxis] * occurrences[np.newaxis, :] + co_occurrences_smooth)
            )
            diag = np.diag_indices(len(values))
            # values.cumsum(axis=0).cumsum(axis=1)[diag] - values[diag].cumsum()

            current_pmi = np.array(
               values.cumsum(axis=0).cumsum(axis=1)[diag] - values[diag].cumsum()
            ).ravel()
            topic_pmis[t] = current_pmi
            pmi += current_pmi

            values[values < 0.] = 0.
            current_ppmi = np.array(
               values.cumsum(axis=0).cumsum(axis=1)[diag] - values[diag].cumsum()
            ).ravel()
            topic_ppmis[t] = current_ppmi
            ppmi += current_ppmi
            
        sizes = np.arange(2, max_top_size + 1)
        pmi[1:] /= (T * sizes * (sizes - 1))
        ppmi[1:] /= (T * sizes * (sizes - 1))
        indices = np.array(top_sizes) - 1

        for t in topic_indices:
            topic_pmis[t][1:] /= (sizes * (sizes - 1))
            topic_ppmis[t][1:] /= (sizes * (sizes - 1))

        result_topic_pmis = {t: p[indices] for t, p in topic_pmis.items()}
        result_topic_ppmis = {t: p[indices] for t, p in topic_ppmis.items()}

        return pmi[indices], ppmi[indices], result_topic_pmis, result_topic_ppmis

    return func

In [16]:
%%time

occurences, co_occurences = calc_doc_occurrences(dataset, MAIN_MODALITY)

CPU times: user 7.67 s, sys: 279 ms, total: 7.95 s
Wall time: 8.11 s

In [17]:
co_occurences.shape

(114951, 114951)

In [18]:
calc_pmi = create_pmi_top_function(
    occurences, co_occurences,
    dataset.get_dataset().shape[0], [20],
    topic_indices=[0, 1, 2],
    co_occurrences_smooth=1e-2,
)

In [19]:
class TopTokenCoherence(BaseTopicNetScore):
    def __init__(self, name, func):
        super().__init__()

        self._name = name
        self.calc_pmi = func

    def call(self, model: TopicModel):
        values = self.calc_pmi(model.get_phi_dense()[0].T)

        return values[1]

    def call_by_topic(self, model: TopicModel):
        values = self.calc_pmi(model.get_phi_dense()[0].T)

        return values[3]

In [20]:
def view_model(
        topic_model,
        dataset,
        num_top_tokens: int = 5,
        top_tokens_method: str = 'phi',
        num_topics: Optional[int] = 5,  # we do not want to fill the whole .ipynb notebook with topics...
        ):
    top_tok_viewer = TopTokensViewer(
        topic_model, num_top_tokens=num_top_tokens, method=top_tokens_method
    )
    top_doc_viewer = TopDocumentsViewer(topic_model, dataset=dataset)
    top_docs = top_doc_viewer.view()

    if num_topics is None:
        num_topics = len(topic_model.topic_names)

    for topic_name in topic_model.topic_names[:num_topics]:
        topic_top_toks = top_tok_viewer.to_html(topic_names=[topic_name])
        topic_top_docs = top_docs[topic_name]
        display_html(topic_top_toks, raw=True)
        display(topic_top_docs)

In [21]:
class FastFixPhiRegularizer(BaseRegularizer):
    _VERY_BIG_TAU = 10 ** 9

    def __init__(self, name: str, topic_names: List[str], parent_model=None, parent_phi=None, words=None):
        super().__init__(name, tau=self._VERY_BIG_TAU)

        self._topic_names = topic_names
        self._topic_indices = None
        self._words = words
        self._word_indices = None
        self._parent_model = parent_model
        self._parent_phi = parent_phi

    def grad(self, pwt, nwt):
        # print('Fixing')

        rwt = np.zeros_like(pwt)

        if self._parent_phi is not None:
            parent_phi = self._parent_phi
            vals = parent_phi.values
        else:
            assert False

            parent_phi = self._parent_model.get_phi()
            vals = parent_phi.values[:, self._topic_indices]

        if self._word_indices is None:
            assert vals.shape[0] == rwt.shape[0], (vals.shape[0], rwt.shape[0])
        else:
            assert vals.shape[0] == len(self._word_indices)

        assert vals.shape[1] == len(self._topic_indices)

        if self._word_indices is None:
            rwt[:, self._topic_indices] += vals
        else:
            # print(len(self._word_indices), len(self._topic_indices), rwt.shape, vals.shape)
            # print(self._word_indices[:3], self._topic_indices[:3])
            # print(rwt[np.ix_(self._word_indices, self._topic_indices)].shape, vals.shape)

            # https://github.com/numpy/numpy/issues/5574
            # https://github.com/numpy/numpy/issues/13255
            rwt[np.ix_(self._word_indices, self._topic_indices)] += vals

            # print(np.ix_(self._word_indices, self._topic_indices)[:3])

        return self.tau * rwt

    def attach(self, model):
        super().attach(model)
        
        phi = self._model.get_phi()
        self._topic_indices = [
            phi.columns.get_loc(topic_name)
            for topic_name in self._topic_names
        ]

        if self._words is not None:
            self._word_indices = [
                # phi.index.get_loc(w) for w in self._words
                int(phi.index.get_loc(w)) for w in self._words
            ]

            # print(f'!!! Word indices: {self._word_indices}')

In [22]:
def fit_and_compute_scores(model, dataset, target_topic_indices=None, custom_regularizers=None):
    print(custom_regularizers)

    model._fit(dataset.get_batch_vectorizer(), num_iterations=NUM_ITERATIONS, custom_regularizers=custom_regularizers)

    score_values = {
        'perplexity': model.scores[f'PerplexityScore{MAIN_MODALITY}'][-1],
    }

    phi = model.get_phi()

    # Currently all topics are taken into account

    if target_topic_indices is None:
        target_topic_indices = list(range(NUM_TOPICS))  # phi.columns.get_loc()

    target_topic_names = [phi.columns[i] for i in target_topic_indices]

    top = NUM_TOP_TOKENS
    coherence_score = TopTokenCoherence(
        name=f'coherence_{top}',
        func=create_pmi_top_function(
            occurences, co_occurences,
            dataset.get_dataset().shape[0], [top],
            topic_indices=target_topic_indices,
            co_occurrences_smooth=1e-2,
        )
    )

    value = coherence_score.call(model)
    score_values[coherence_score._name] = value
    topic_coherences = coherence_score.call_by_topic(model)
    topic_coherences = {t: float(v) for t, v in topic_coherences.items()}





    # intra1 = IntratextCoherenceScore(
    #     name='toplen_pwt',
    #     data=dataset,
    #     computation_method=ComputationMethod.SEGMENT_LENGTH,
    #     word_topic_relatedness=WordTopicRelatednessType.PWT,
    #     should_compute=False,  # only on last iter
    # )
    intra2 = IntratextCoherenceScore(
        name='toplen_ptw',
        data=dataset,
        computation_method=ComputationMethod.SEGMENT_LENGTH,
        word_topic_relatedness=WordTopicRelatednessType.PTW,
        should_compute=False,
    )
    # intra3 = IntratextCoherenceScore(
    #     name='topden_ptw',
    #     data=dataset,
    #     computation_method=ComputationMethod.SUM_OVER_WINDOW,
    #     word_topic_relatedness=WordTopicRelatednessType.PTW,
    #     should_compute=False,
    # )
    # intra3_w4 = IntratextCoherenceScore(
    #     name='topden_ptw',
    #     data=dataset,
    #     computation_method=ComputationMethod.SUM_OVER_WINDOW,
    #     word_topic_relatedness=WordTopicRelatednessType.PTW,
    #     window=4,
    #     should_compute=False,
    # )

    intra_topic_coherences = dict()

    for intra in [intra2]:  # [intra2, intra3_w4]:  #[intra1, intra2, intra3]:
        # print(f'\nComputing "{intra._name}"...')

        current_intra_topic_coherences = intra.compute(model)

        assert all(v is not None for v in current_intra_topic_coherences.values())

        _values = current_intra_topic_coherences.values()

        current_intra_topic_coherences = {
            i: current_intra_topic_coherences[t]  # if v is not None else 0.0
            for i, t in enumerate(target_topic_names)
        }

        assert all(abs(x - y) <= 1e-6 for x, y in zip(_values, current_intra_topic_coherences.values())), (_values, current_intra_topic_coherences.values())  # "sorted" Python dicts
        
        intra_topic_coherences[f'topic_coherences_{intra._name}'] = current_intra_topic_coherences

        value = float(np.median(list(current_intra_topic_coherences.values())))
        score_values[intra._name] = value

        # print(f'Result by topic: {current_intra_topic_coherences}.')




    
    diversity_scores = [
        DiversityScore(
            name=f'diversity_{metric}',
            metric=metric,
            topic_names=target_topic_names,
            class_ids=MAIN_MODALITY,
        )
    
        for metric in KNOWN_METRICS
    ]
    
    for score in diversity_scores:
        value = score.call(model)
        score_values[score._name] = value

    return {
        'scores': score_values,
        'topic_coherences': topic_coherences,
        **intra_topic_coherences,
    }

In [23]:
def init_model_from_family(
        family: str or KnownModel,
        dataset: Dataset,
        main_modality: str,
        num_topics: int,
        seed: int,
        specific_topic_names = None,
        modalities_to_use: List[str] = None,
        num_processors: int = 3,
        model_params: dict = None,
):
    """
    Returns
    -------
    model: TopicModel() instance
    """
    if isinstance(family, KnownModel):
        family = family.value

    if modalities_to_use is None:
        modalities_to_use = [main_modality]

    custom_regs = {}

    if family == "LDA":
        model = init_lda(
            dataset, modalities_to_use, main_modality, num_topics, model_params
        )
    elif family == "PLSA":
        model = init_plsa(
            dataset, modalities_to_use, main_modality, num_topics
        )
    elif family == "TARTM":
        model, custom_regs = init_thetaless(
            dataset, modalities_to_use, main_modality, num_topics, model_params
        )
    elif family == "sparse":
        model = init_bcg_sparse_model(
            dataset, modalities_to_use, main_modality, num_topics, 1, model_params
        )
    elif family == "decorrelation":
        model = init_decorrelated_plsa(
            dataset, modalities_to_use, main_modality, num_topics, model_params
        )
    elif family == "ARTM":
        model = init_baseline_artm(
            dataset, modalities_to_use, main_modality, num_topics, 1, specific_topic_names, model_params
        )
    else:
        raise ValueError(f'family: {family}')

    model.num_processors = num_processors

    if seed is not None:
        model.seed = seed

    dictionary = dataset.get_dictionary()

    # TODO: maybe this cycle is not necessary
    for modality in dataset.get_possible_modalities():
        if modality not in modalities_to_use:
            dictionary.filter(class_id=modality, max_df=0, inplace=True)

    model.initialize(dictionary)
    add_standard_scores(model, dictionary, main_modality=main_modality,
                        all_modalities=modalities_to_use)

    model = TopicModel(
        artm_model=model,
        custom_regularizers=custom_regs
    )

    return model


def init_bcg_sparse_model(
        dataset,
        modalities_to_use,
        main_modality,
        specific_topics,
        bcg_topics,
        specific_topic_names = None,
        model_params: dict = None
):
    """
    Creates simple artm model with standard scores.

    Parameters
    ----------
    dataset : Dataset
    modalities_to_use : list of str or dict
    main_modality : str
    specific_topics : int
    bcg_topics : int

    Returns
    -------
    model: artm.ARTM() instance
    """
    if model_params is None:
        model_params = dict()

    model = init_plsa(
        dataset, modalities_to_use, main_modality, specific_topics, bcg_topics
    )
    background_topic_names = model.topic_names[-bcg_topics:]

    if specific_topic_names is None:
        print('No spec topics')
        specific_topic_names = model.topic_names[:-bcg_topics]

    dictionary = dataset.get_dictionary()
    baseline_class_ids = {class_id: 1 for class_id in modalities_to_use}
    data_stats = count_vocab_size(dictionary, baseline_class_ids)

    # all coefficients are relative
    regularizers = [
        artm.SmoothSparsePhiRegularizer(
             name='smooth_phi_bcg',
             topic_names=background_topic_names,
             tau=model_params.get("smooth_bcg_tau", 0.1),
             class_ids=[main_modality],
        ),
        artm.SmoothSparseThetaRegularizer(
             name='smooth_theta_bcg',
             topic_names=background_topic_names,
             tau=model_params.get("smooth_bcg_tau", 0.1),
        ),
        artm.SmoothSparsePhiRegularizer(
             name='sparse_phi_sp',
             topic_names=specific_topic_names,
             tau=model_params.get("sparse_sp_tau", -0.05),
             class_ids=[main_modality],
            ),
        artm.SmoothSparseThetaRegularizer(
             name='sparse_theta_sp',
             topic_names=specific_topic_names,
             tau=model_params.get("sparse_sp_tau", -0.05),
        ),
    ]
    for reg in regularizers:
        model.regularizers.add(transform_regularizer(
            data_stats,
            reg,
            model.class_ids,
            n_topics=len(reg.topic_names)
        ))

    return model


def init_baseline_artm(
        dataset,
        modalities_to_use,
        main_modality,
        num_topics,
        bcg_topics,
        specific_topic_names = None,
        model_params: dict = None,
):
    """
    Creates simple artm model with standard scores.

    Parameters
    ----------
    dataset : Dataset
    modalities_to_use : list of str
    main_modality : str
    num_topics : int

    Returns
    -------
    model: artm.ARTM() instance
    """
    if model_params is None:
        model_params = dict()

    model = init_bcg_sparse_model(
        dataset, modalities_to_use, main_modality, num_topics, bcg_topics, specific_topic_names, model_params
    )

    if specific_topic_names is None:
        print('No spec topics')
        specific_topic_names = model.topic_names[:-bcg_topics]

    model.regularizers.add(
        artm.DecorrelatorPhiRegularizer(
            gamma=0,
            tau=model_params.get('decorrelation_tau', 0.01),
            name='decorrelation',
            topic_names=specific_topic_names,
            class_ids=modalities_to_use,
        )
    )

    return model

In [24]:
TOPIC_INDICES = list(range(NUM_TOPICS))

In [25]:
TOPIC_INDICES

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49]

In [26]:
phi0 = pd.read_csv(f'{RESULTS_FOLDER_PATH}/0/phi.csv', index_col=0)

In [27]:
phi0.head()

,background_1,topic_0,topic_1,topic_2,topic_3,topic_4,topic_5,topic_6,topic_7,topic_8,...,topic_40,topic_41,topic_42,topic_43,topic_44,topic_45,topic_46,topic_47,topic_48,topic_49
00,0.000000,0.001140,0.000138,0.0,0.004540,0.0,0.00000,0.001633,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
000,0.000125,0.000070,0.000031,0.0,0.003937,0.0,0.00013,0.000311,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
0000,0.000140,0.000026,0.000000,0.0,0.002774,0.0,0.00000,0.000000,0.0,0.000105,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
00000,0.000000,0.000043,0.000000,0.0,0.000000,0.0,0.00000,0.000000,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.00000,0.000605,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [28]:
phi0.set_index([[MAIN_MODALITY] * len(phi0.index), phi0.index], inplace=True)

In [29]:
phi0.head()

                    background_1   topic_0   topic_1  topic_2   topic_3  \
@lemmatized 00          0.000000  0.001140  0.000138      0.0  0.004540
            000         0.000125  0.000070  0.000031      0.0  0.003937
            0000        0.000140  0.000026  0.000000      0.0  0.002774
            00000       0.000000  0.000043  0.000000      0.0  0.000000
            000000      0.000000  0.000000  0.000000      0.0  0.000000

                    topic_4  topic_5   topic_6  topic_7   topic_8  ...  \
@lemmatized 00          0.0  0.00000  0.001633      0.0  0.000000  ...
            000         0.0  0.00013  0.000311      0.0  0.000000  ...
            0000        0.0  0.00000  0.000000      0.0  0.000105  ...
            00000       0.0  0.00000  0.000000      0.0  0.000000  ...
            000000      0.0  0.00000  0.000605      0.0  0.000000  ...

                    topic_40  topic_41  topic_42  topic_43  topic_44  \
@lemmatized 00           0.0       0.0       0.0       0.0       0.0
            000          0.0       0.0       0.0       0.0       0.0
            0000         0.0       0.0       0.0       0.0       0.0
            00000        0.0       0.0       0.0       0.0       0.0
            000000       0.0       0.0       0.0       0.0       0.0

                    topic_45  topic_46  topic_47  topic_48  topic_49
@lemmatized 00           0.0       0.0       0.0       0.0       0.0
            000          0.0       0.0       0.0       0.0       0.0
            0000         0.0       0.0       0.0       0.0       0.0
            00000        0.0       0.0       0.0       0.0       0.0
            000000       0.0       0.0       0.0       0.0       0.0

[5 rows x 51 columns]

In [30]:
DIFF_THRESHOLD = 2

In [31]:
def check_top_words(phi, top_words):
    diffs = []

    for t, topic_top_words in top_words.items():
        if t == 'background_1':
            print(f'Skipping background topic: {t}.')

            continue

        print(t)
        # print(top_words)
    
        top_phi = set(phi[t].sort_values(ascending=False)[:NUM_TOP_TOKENS].index.get_level_values(1))
        top_bt = set([p[0] for p in topic_top_words])
    
        if top_phi == top_bt:
            diffs.append(
                {
                    'total': 0,
                    'lost_bt': 0,
                    'lost_model': 0,
                }
            )
        else:
            diff1 = top_phi.difference(top_bt)
            diff2 = top_bt.difference(top_phi)
    
            print('  WTF:', diff1, diff2)
    
            if len(diff1) > DIFF_THRESHOLD:
                print(f'  WTF?!?!?', len(diff1))
    
            if len(diff2) > DIFF_THRESHOLD:
                print(f'  WTF?!?!?', len(diff2))

            diffs.append(
                {
                    'total': len(diff1 | diff2),
                    'lost_bt': len(diff2),
                    'lost_model': len(diff1),
                }
            )

    return diffs

In [32]:
def init_model_and_phi(num_topics, dataset, phi0):
    model = init_model_from_family(
        family=KnownModel.PLSA,
        dataset=dataset,
        main_modality=MAIN_MODALITY,
        num_topics=num_topics,
        seed=0,
    )
    
    phi = model.get_phi()
    
    # assert phi.shape[1] == phi0.shape[1] - 1
    assert phi.shape[1] == num_topics
    assert phi.shape[1] in [phi0.shape[1], phi0.shape[1] - 1]
    
    common_words = list(set(phi.index).intersection(phi0.index))
    
    phi.loc[:, :] = 0

    if phi.shape[1] == phi0.shape[1]:
        target_topics = phi0.columns
    elif phi.shape[1] == phi0.shape[1] - 1:
        target_topics = phi.columns
    else:
        assert False

    # print(common_words, phi.index, phi0.index)

    phi.loc[common_words, :] += phi0.loc[common_words, target_topics]

    diff = set(phi0.columns).symmetric_difference(set(phi.columns))

    assert diff == {'background_1'} or diff == {'background_1', f'topic_{len(phi.columns) - 1}'}
    
    phi = phi / phi.sum(axis=0)

    return model, phi, common_words

In [33]:
! ls results50

ls: cannot access 'results50': No such file or directory

In [34]:
SAVE_FOLDER = os.path.join('results50_intra', '20newsgroups')

In [35]:
! ls $SAVE_FOLDER

decorrelation_with_cohs.json  iterative2_100000000	 plsa_with_cohs.json
iterative_100000	      iterative2_100000000.json  sparse_with_cohs.json
iterative_100000.json	      lda_with_cohs.json	 tless_with_cohs.json

In [36]:
results = []

is_results_loaded = False

save_file_path = os.path.join(
    SAVE_FOLDER, 'bertopic.json'
)

if os.path.isfile(save_file_path):
    results = json.loads(
        open(save_file_path).read()
    )
    is_results_loaded = True


singles_save_folder = os.path.join(
    SAVE_FOLDER, 'bertopic'
)

os.makedirs(singles_save_folder, exist_ok=True)


for seed in range(NUM_TRAINS):
    if is_results_loaded:
        continue

    print(seed)

    current_save_file_path = os.path.join(
        singles_save_folder, f'bertopic_{seed}.json'
    )

    if os.path.isfile(current_save_file_path):
        print(f'Already computed results: {current_save_file_path}. Loading and skipping...')

        result = json.loads(
            open(current_save_file_path).read()
        )
        results.append(result)

        continue

    seed_load_folder = os.path.join(RESULTS_FOLDER_PATH, str(seed))
    files = [f for f in os.listdir(seed_load_folder) if os.path.isfile(f'{seed_load_folder}/{f}')]
    
    assert len(files) == 3

    dataset = Dataset(
        f'{seed_load_folder}/dataset.csv',
    )
    phi0 = pd.read_csv(f'{seed_load_folder}/phi.csv', index_col=0)
    phi0.set_index([[MAIN_MODALITY] * len(phi0.index), phi0.index], inplace=True)

    assert all('back' not in t for t in phi0.columns[1:])
    assert 'back' in phi0.columns[0]

    num_specific_topics = phi0.shape[1] - 1

    assert num_specific_topics == len([t for t in phi0.columns if 'back' not in t])

    print(f'Num model topics: {phi0.shape[1]}.')

    with open(f'{seed_load_folder}/top_words.json', 'r') as f:
        top_words = json.loads(f.read())


    
    model, phi, common_phi_words = init_model_and_phi(
        num_topics=num_specific_topics + 1,  # background
        dataset=dataset, phi0=phi0
    )
    common_words = [
        w[1] for w in common_phi_words  # without modality
    ]
    common_words_phi0_indices = [
        # phi0.index.get_loc(w) for w in common_words
        int(phi0.index.get_locs(w)) for w in common_phi_words
    ]

    print('Check before fit:')
    diff_tops1 = check_top_words(phi, top_words)  # Whatever...
    
    fix_regularizer = FastFixPhiRegularizer(
        name='fix',
        parent_phi=phi0.iloc[common_words_phi0_indices, 1:],
        words=common_words,
        topic_names=phi.columns[1:],
    )
    result = fit_and_compute_scores(
        model, dataset,
        target_topic_indices=list(range(phi.shape[1])),
        custom_regularizers = {
            fix_regularizer.name: fix_regularizer,
        }
    )

    print('Check after fit:')
    diff_tops2 = check_top_words(phi, top_words)  # Whatever...

    assert diff_tops1 == diff_tops2

    fair_ppl_free = result['scores']['perplexity']

    del model, phi, fix_regularizer, result


    
    model, phi, _ = init_model_and_phi(
        num_topics=num_specific_topics + 1,  # background
        dataset=dataset, phi0=phi0
    )
    fix_regularizer = FastFixPhiRegularizer(
        name='fix',
        parent_phi=phi0.iloc[common_words_phi0_indices, :],  # Diff here
        words=common_words,
        topic_names=phi.columns,
    )
    result = fit_and_compute_scores(
        model, dataset,
        target_topic_indices=list(range(phi.shape[1])),
        custom_regularizers = {
            fix_regularizer.name: fix_regularizer,
        }
    )
    
    fair_ppl_fix = result['scores']['perplexity']

    del model, phi, fix_regularizer, result

    
    
    model, phi, _ = init_model_and_phi(
        num_topics=num_specific_topics,  # Diff here
        dataset=dataset, phi0=phi0
    )
    fix_regularizer = FastFixPhiRegularizer(
        name='fix',
        parent_phi=phi0.iloc[common_words_phi0_indices, 1:],  # Diff here
        words=common_words,
        topic_names=phi.columns,
    )
    result = fit_and_compute_scores(
        model, dataset,
        custom_regularizers = {
            fix_regularizer.name: fix_regularizer,
        }
    )

    unfair_ppl_banklike = result['scores']['perplexity']


    
    result['scores']['fair_ppl_free'] = fair_ppl_free
    result['scores']['fair_ppl_fix'] = fair_ppl_fix
    result['scores']['unfair_ppl_banklike'] = unfair_ppl_banklike

    assert result['scores']['fair_ppl_free'] < result['scores']['unfair_ppl_banklike']
    # assert result['scores']['fair_ppl_fix'] < result['scores']['unfair_ppl_banklike']

    result['scores']['coherence_20'] = float(result['scores']['coherence_20'])
    result['stats'] = {
        'num_topics': phi0.shape[1],
        'num_common_words': len(common_words),
        'num_model_words': phi.shape[0],
        'num_bt_words': phi0.shape[0],
        'top_diffs': diff_tops2,
    }

    results.append(result)

    print(result['scores'])
    print(result['stats'])

    dumped_result = json.dumps(
        results[-1], indent=4
    )

    with open(current_save_file_path, 'w') as f:
        f.write(dumped_result)

    del model, phi, fix_regularizer


with open(save_file_path, 'w') as f:
    f.write(
        json.dumps(
            results, indent=4
        )
    )

0
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
  WTF: {'firearms'} {'stephanopoulos'}
topic_3
  WTF: {'vs'} {'nhl'}
topic_4
topic_5
  WTF: {'dont', 'surrender', 'candida'} {'gordon', 'hiv', 'n3jxp'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_6
topic_7
  WTF: {'news', 'thanks'} {'o157h7', 'anania'}
topic_8
  WTF: {'children', 'started', 'government', 'ottoman', 'muslim', 'saw'} {'armenia', 'azerbaijan', 'sumgait', 'turks', 'armenian', 'armenians'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_9
  WTF: {'driver'} {'bj200'}
topic_10
  WTF: {'just', 'sin'} {'caligiuri', 'enviroleague'}
topic_11
  WTF: {'toolbox', 'effortsall', 'dragdrop', 'taxation', 'Epilepsy', '207556000', 'CDROMCATZIP', 'NikeCajun', '8800CS', 'CSCSTD00385', 'L2PMABGZ7VAZV0PZRI', 'knowlege', 'ringleaders', '1795', '5152940082'} {''}
  WTF?!?!? 15
topic_12
topic_13
topic_14
  WTF: {'email', 'posting'} {'rsa', 'ripem'}
topic_15
topic_16
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_17
topic_18
topic_19
topic_20
  WTF: {'email', 'writing', 'vol', 'copyright', 'analytic', '02106chopinudeledu'} {'vinge', 'dune', 'vernor', 'petrucci', 'gibson', 'baen'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_21
  WTF: {'250', 'use'} {'irwin', 'mactools'}
topic_22
  WTF: {'400', 'grayscales', 'handheld', 'buy', 'scans', 'market'} {'ocr', 'dexxa', 'scanman', 'paintbrush', 'mustek', 'ocr104zip'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_23
  WTF: {'rule', 'bang', 'king', 'sort', 'guide', 'forget'} {'altima', 'adams', 'alice', 'maxima', 'douglas', 'infiniti'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_24
topic_25
  WTF: {'pm', 'students', 'cs', 'andrew'} {'mellon', 'japan', 'jstmp', 'carnegie'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_26
  WTF: {'objects', 'charged'} {'kirlian', 'krillean'}
topic_27
topic_28
  WTF: {'fissionable'} {'civillians'}
topic_29
  WTF: {'english', 'people'} {'bede', 'ishtar'}
topic_30
  WTF: {'aside'} {'darius'}
topic_31
  WTF: {'nick', '49er', 'car'} {'sept', 'cambridge', 'quincy'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_32
  WTF: {'stripped', 'regards'} {'babak', 'sehari'}
topic_33
  WTF: {'envelopes'} {'mary'}
topic_34
  WTF: {'eabu288140493210752dialin33635slipntsuciedu', 'nebulised', 'eabu288orionoacuciedu'} {'petesmtldemoncouk', 'bridgend', 'asthmatics'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_35
  WTF: {'commission', 'corps', 'axe'} {'irs', 'registries', 'admistration'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_36
  WTF: {'energyefficiency', 'governmentmandated', 'safety', 'world', 'perfect'} {'shafer', 'ames', 'mary', 'cato', 'dryden'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_37
  WTF: {'uuencode', 'ioccc'} {'eofnotok', 'xvoid'}
topic_38
  WTF: {'vending', 'patchmaking', 'unpatentable', 'remixed'} {'cocacola', 'yerazunis', 'cola', 'pepsi'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_39
  WTF: {'wooden', 'punch', 'vent'} {'pistrix', 'lesabre', 'sanjay'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_40
  WTF: {'financial', 'amish'} {'q6', 'mym'}
topic_41
topic_42
  WTF: {'stabilized', 'addition', 'version', 'pads', 'combo'} {'t4', 'salyut', 'russia', 'energiam', 't4centaur'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_43
  WTF: {'licensed', 'product', 'promote', 'science', 'include', 'internet', 'publications'} {'regal', 'robb', 'milwaukee', 'wi', 'marquette', 'dubinski', 'doublemajor'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_44
  WTF: {'audio', 'problem', 'returned'} {'hifi', 'emerson', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_45
  WTF: {'promote'} {'fenholt'}
topic_46
  WTF: {'mole', 'leave', 'gigabytes'} {'menuts', 'eachus', 'avagadros'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_47
  WTF: {'tp', 'mf', 'mj', 'mh', 'm1', 'u0', 'trinomials', 'mm', '644', 'pw', '0n', 'ma'} {'mx', 'm0', 'pnospsxop8f', 'mw', 'm6', 'o3', 'm5', 'm3', 'e8', 'lu', 'm9', 'p6'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_48
  WTF: {'3rd'} {'ses'}
topic_49
  WTF: {'illusion', 'advertised', 'toilet'} {'kepley', 'mcguire', 'workdays'}
  WTF?!?!? 3
  WTF?!?!? 3
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3073c72f70>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
  WTF: {'firearms'} {'stephanopoulos'}
topic_3
  WTF: {'vs'} {'nhl'}
topic_4
topic_5
  WTF: {'dont', 'surrender', 'candida'} {'gordon', 'hiv', 'n3jxp'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_6
topic_7
  WTF: {'news', 'thanks'} {'o157h7', 'anania'}
topic_8
  WTF: {'children', 'started', 'government', 'ottoman', 'muslim', 'saw'} {'armenia', 'azerbaijan', 'sumgait', 'turks', 'armenian', 'armenians'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_9
  WTF: {'driver'} {'bj200'}
topic_10
  WTF: {'just', 'sin'} {'caligiuri', 'enviroleague'}
topic_11
  WTF: {'toolbox', 'effortsall', 'dragdrop', 'taxation', 'Epilepsy', '207556000', 'CDROMCATZIP', 'NikeCajun', '8800CS', 'CSCSTD00385', 'L2PMABGZ7VAZV0PZRI', 'knowlege', 'ringleaders', '1795', '5152940082'} {''}
  WTF?!?!? 15
topic_12
topic_13
topic_14
  WTF: {'email', 'posting'} {'rsa', 'ripem'}
topic_15
topic_16
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_17
topic_18
topic_19
topic_20
  WTF: {'email', 'writing', 'vol', 'copyright', 'analytic', '02106chopinudeledu'} {'vinge', 'dune', 'vernor', 'petrucci', 'gibson', 'baen'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_21
  WTF: {'250', 'use'} {'irwin', 'mactools'}
topic_22
  WTF: {'400', 'grayscales', 'handheld', 'buy', 'scans', 'market'} {'ocr', 'dexxa', 'scanman', 'paintbrush', 'mustek', 'ocr104zip'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_23
  WTF: {'rule', 'bang', 'king', 'sort', 'guide', 'forget'} {'altima', 'adams', 'alice', 'maxima', 'douglas', 'infiniti'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_24
topic_25
  WTF: {'pm', 'students', 'cs', 'andrew'} {'mellon', 'japan', 'jstmp', 'carnegie'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_26
  WTF: {'objects', 'charged'} {'kirlian', 'krillean'}
topic_27
topic_28
  WTF: {'fissionable'} {'civillians'}
topic_29
  WTF: {'english', 'people'} {'bede', 'ishtar'}
topic_30
  WTF: {'aside'} {'darius'}
topic_31
  WTF: {'nick', '49er', 'car'} {'sept', 'cambridge', 'quincy'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_32
  WTF: {'stripped', 'regards'} {'babak', 'sehari'}
topic_33
  WTF: {'envelopes'} {'mary'}
topic_34
  WTF: {'eabu288140493210752dialin33635slipntsuciedu', 'nebulised', 'eabu288orionoacuciedu'} {'petesmtldemoncouk', 'bridgend', 'asthmatics'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_35
  WTF: {'commission', 'corps', 'axe'} {'irs', 'registries', 'admistration'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_36
  WTF: {'energyefficiency', 'governmentmandated', 'safety', 'world', 'perfect'} {'shafer', 'ames', 'mary', 'cato', 'dryden'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_37
  WTF: {'uuencode', 'ioccc'} {'eofnotok', 'xvoid'}
topic_38
  WTF: {'vending', 'patchmaking', 'unpatentable', 'remixed'} {'cocacola', 'yerazunis', 'cola', 'pepsi'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_39
  WTF: {'wooden', 'punch', 'vent'} {'pistrix', 'lesabre', 'sanjay'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_40
  WTF: {'financial', 'amish'} {'q6', 'mym'}
topic_41
topic_42
  WTF: {'stabilized', 'addition', 'version', 'pads', 'combo'} {'t4', 'salyut', 'russia', 'energiam', 't4centaur'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_43
  WTF: {'licensed', 'product', 'promote', 'science', 'include', 'internet', 'publications'} {'regal', 'robb', 'milwaukee', 'wi', 'marquette', 'dubinski', 'doublemajor'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_44
  WTF: {'audio', 'problem', 'returned'} {'hifi', 'emerson', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_45
  WTF: {'promote'} {'fenholt'}
topic_46
  WTF: {'mole', 'leave', 'gigabytes'} {'menuts', 'eachus', 'avagadros'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_47
  WTF: {'tp', 'mf', 'mj', 'mh', 'm1', 'u0', 'trinomials', 'mm', '644', 'pw', '0n', 'ma'} {'mx', 'm0', 'pnospsxop8f', 'mw', 'm6', 'o3', 'm5', 'm3', 'e8', 'lu', 'm9', 'p6'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_48
  WTF: {'3rd'} {'ses'}
topic_49
  WTF: {'illusion', 'advertised', 'toilet'} {'kepley', 'mcguire', 'workdays'}
  WTF?!?!? 3
  WTF?!?!? 3

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3015e9f760>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3073b40880>}
{'perplexity': 50620.3359375, 'coherence_20': 1.8455919239185774, 'toplen_ptw': 1.1528501347545348, 'diversity_euclidean': 0.10544738016575618, 'diversity_jensenshannon': 0.7757965562983609, 'diversity_hellinger': 0.9212522523991468, 'diversity_cosine': 0.9165479447048536, 'fair_ppl_free': 2053.462646484375, 'fair_ppl_fix': 50116.61328125, 'unfair_ppl_banklike': 50620.3359375}
{'num_topics': 51, 'num_common_words': 59415, 'num_model_words': 114951, 'num_bt_words': 97541, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 16, 'lost_bt': 1, 'lost_model': 15}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}]}
1
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
  WTF: {'vs'} {'nhl'}
topic_3
topic_4
  WTF: {'dont', 'diet', 'doctors'} {'gordon', 'hiv', 'n3jxp'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_5
topic_6
  WTF: {'discussion'} {'o157h7'}
topic_7
  WTF: {'children', 'started', 'government', 'ottoman', 'muslim', 'saw'} {'armenia', 'azerbaijan', 'sumgait', 'turks', 'armenian', 'armenians'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_8
  WTF: {'use'} {'bj200'}
topic_9
  WTF: {'toolbox', 'effortsall', 'dragdrop', 'recollection', 'taxation', 'CDROMCATZIP', '207556000', 'NikeDeacon', 'NikeCajun', '8800CS', 'CSCSTD00385', 'L2PMABGZ7VAZV0PZRI', '1795', '5152940082'} {''}
  WTF?!?!? 14
topic_10
topic_11
  WTF: {'football', 'adventure', '35'} {'snes', 'cdi', 'sega'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_12
topic_13
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_14
topic_15
  WTF: {'festival'} {'ishtar'}
topic_16
  WTF: {'general', 'plasktbdemoncouk', '19851986', '19891990'} {'boulder', 'rex', 'gre', 'ets'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_17
  WTF: {'email', 'writing', 'vol', 'copyright', 'analytic', '02106chopinudeledu'} {'vinge', 'dune', 'vernor', 'hogan', 'gibson', 'baen'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_18
  WTF: {'chemicals', 'insisting'} {'cato', 'shafer'}
topic_19
topic_20
  WTF: {'250', 'use'} {'irwin', 'mactools'}
topic_21
  WTF: {'new', 'installations', 'islands', 'southern', 'plan', 'armada', 'fleet'} {'bolsheviks', 'georgia', 'argentina', 'argentine', 'rockefeller', 'falklands', 'bolshevik'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_22
topic_23
  WTF: {'400', 'grayscales', 'handheld', 'buy', 'scans', 'market'} {'ocr', 'dexxa', 'scanman', 'paintbrush', 'mustek', 'ocr104zip'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_24
  WTF: {'try', 'card'} {'microsofts', 'sb'}
topic_25
topic_26
topic_27
  WTF: {'year'} {'aiken'}
topic_28
  WTF: {'stuff', 'molding', 'waxed'} {'meguiars', 'mcquires', 'glaze'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_29
  WTF: {'objects', 'charged'} {'kirlian', 'krillean'}
topic_30
  WTF: {'stripped', 'regards'} {'babak', 'sehari'}
topic_31
  WTF: {'nick', '49er', 'mit'} {'sept', 'cambridge', 'quincy'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_32
  WTF: {'dim', 'type'} {'emi', 'hv'}
topic_33
  WTF: {'list', 'utter', 'military', 'jobs'} {'irs', 'registries', 'c17', 'admistration'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_34
  WTF: {'20', 'production', 'compsysamigagraphics', 'pictures', 'bet'} {'ipas', 'icbm', 'titan', '3do', 'v200'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_35
  WTF: {'rule', 'forget', 'bang'} {'douglas', 'alice', 'adams'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_36
  WTF: {'6192214511', 'outputing', 'pubdkbtraceutils', '6192212527', 'raytrace', 'runnining'} {'tce', 'succes', 'a0size', 'perth', 'zeh', 'versatec'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_37
  WTF: {'worse', 'germany', 'dangerous'} {'femine', 'calverts', 'fatti'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_38
  WTF: {'ground', 'reliability', 'horizontal'} {'hifi', 'emerson', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_39
  WTF: {'combination'} {'lonoak'}
topic_40
  WTF: {'quite'} {'biscayne'}
topic_41
  WTF: {'uuencode', 'ioccc'} {'eofnotok', 'xvoid'}
topic_42
  WTF: {'correct', 'trick', 'screen'} {'supercharging', 'robbinsgreat', 'judd'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_43
  WTF: {'stabilized', 'addition', 'version', 'pads', 'combo'} {'t4', 'salyut', 'russia', 'energiam', 't4centaur'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_44
  WTF: {'vending', 'patchmaking', 'unpatentable', 'remixed'} {'cocacola', 'yerazunis', 'cola', 'pepsi'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_45
  WTF: {'tp', 'mf', 'mj', 'mh', 'm1', 'u0', 'trinomials', 'mm', '644', 'pw', '0n', 'ma'} {'mx', 'm0', 'pnospsxop8f', 'mw', 'm6', 'o3', 'm5', 'm3', 'e8', 'lu', 'm9', 'p6'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_46
  WTF: {'reference', 'loan', 'kernel'} {'tns', 'q6', 'mym'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_47
  WTF: {'list', 'patches', 'cerritos', 'archive'} {'kotl', 'hopalonga', 'heritick', 'denizen'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_48
  WTF: {'promote'} {'fenholt'}
topic_49
  WTF: {'shoulf'} {'aplace'}
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3015e30fd0>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
  WTF: {'vs'} {'nhl'}
topic_3
topic_4
  WTF: {'dont', 'diet', 'doctors'} {'gordon', 'hiv', 'n3jxp'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_5
topic_6
  WTF: {'discussion'} {'o157h7'}
topic_7
  WTF: {'children', 'started', 'government', 'ottoman', 'muslim', 'saw'} {'armenia', 'azerbaijan', 'sumgait', 'turks', 'armenian', 'armenians'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_8
  WTF: {'use'} {'bj200'}
topic_9
  WTF: {'toolbox', 'effortsall', 'dragdrop', 'recollection', 'taxation', 'CDROMCATZIP', '207556000', 'NikeDeacon', 'NikeCajun', '8800CS', 'CSCSTD00385', 'L2PMABGZ7VAZV0PZRI', '1795', '5152940082'} {''}
  WTF?!?!? 14
topic_10
topic_11
  WTF: {'football', 'adventure', '35'} {'snes', 'cdi', 'sega'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_12
topic_13
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_14
topic_15
  WTF: {'festival'} {'ishtar'}
topic_16
  WTF: {'general', 'plasktbdemoncouk', '19851986', '19891990'} {'boulder', 'rex', 'gre', 'ets'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_17
  WTF: {'email', 'writing', 'vol', 'copyright', 'analytic', '02106chopinudeledu'} {'vinge', 'dune', 'vernor', 'hogan', 'gibson', 'baen'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_18
  WTF: {'chemicals', 'insisting'} {'cato', 'shafer'}
topic_19
topic_20
  WTF: {'250', 'use'} {'irwin', 'mactools'}
topic_21
  WTF: {'new', 'installations', 'islands', 'southern', 'plan', 'armada', 'fleet'} {'bolsheviks', 'georgia', 'argentina', 'argentine', 'rockefeller', 'falklands', 'bolshevik'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_22
topic_23
  WTF: {'400', 'grayscales', 'handheld', 'buy', 'scans', 'market'} {'ocr', 'dexxa', 'scanman', 'paintbrush', 'mustek', 'ocr104zip'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_24
  WTF: {'try', 'card'} {'microsofts', 'sb'}
topic_25
topic_26
topic_27
  WTF: {'year'} {'aiken'}
topic_28
  WTF: {'stuff', 'molding', 'waxed'} {'meguiars', 'mcquires', 'glaze'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_29
  WTF: {'objects', 'charged'} {'kirlian', 'krillean'}
topic_30
  WTF: {'stripped', 'regards'} {'babak', 'sehari'}
topic_31
  WTF: {'nick', '49er', 'mit'} {'sept', 'cambridge', 'quincy'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_32
  WTF: {'dim', 'type'} {'emi', 'hv'}
topic_33
  WTF: {'list', 'utter', 'military', 'jobs'} {'irs', 'registries', 'c17', 'admistration'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_34
  WTF: {'20', 'production', 'compsysamigagraphics', 'pictures', 'bet'} {'ipas', 'icbm', 'titan', '3do', 'v200'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_35
  WTF: {'rule', 'forget', 'bang'} {'douglas', 'alice', 'adams'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_36
  WTF: {'6192214511', 'outputing', 'pubdkbtraceutils', '6192212527', 'raytrace', 'runnining'} {'tce', 'succes', 'a0size', 'perth', 'zeh', 'versatec'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_37
  WTF: {'worse', 'germany', 'dangerous'} {'femine', 'calverts', 'fatti'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_38
  WTF: {'ground', 'reliability', 'horizontal'} {'hifi', 'emerson', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_39
  WTF: {'combination'} {'lonoak'}
topic_40
  WTF: {'quite'} {'biscayne'}
topic_41
  WTF: {'uuencode', 'ioccc'} {'eofnotok', 'xvoid'}
topic_42
  WTF: {'correct', 'trick', 'screen'} {'supercharging', 'robbinsgreat', 'judd'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_43
  WTF: {'stabilized', 'addition', 'version', 'pads', 'combo'} {'t4', 'salyut', 'russia', 'energiam', 't4centaur'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_44
  WTF: {'vending', 'patchmaking', 'unpatentable', 'remixed'} {'cocacola', 'yerazunis', 'cola', 'pepsi'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_45
  WTF: {'tp', 'mf', 'mj', 'mh', 'm1', 'u0', 'trinomials', 'mm', '644', 'pw', '0n', 'ma'} {'mx', 'm0', 'pnospsxop8f', 'mw', 'm6', 'o3', 'm5', 'm3', 'e8', 'lu', 'm9', 'p6'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_46
  WTF: {'reference', 'loan', 'kernel'} {'tns', 'q6', 'mym'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_47
  WTF: {'list', 'patches', 'cerritos', 'archive'} {'kotl', 'hopalonga', 'heritick', 'denizen'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_48
  WTF: {'promote'} {'fenholt'}
topic_49
  WTF: {'shoulf'} {'aplace'}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3087fd8fa0>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3015de4f70>}
{'perplexity': 52182.9765625, 'coherence_20': 1.7859453831714371, 'toplen_ptw': 1.1493372974428273, 'diversity_euclidean': 0.11084360827941732, 'diversity_jensenshannon': 0.7812483409267726, 'diversity_hellinger': 0.9288220020495234, 'diversity_cosine': 0.9258888344463115, 'fair_ppl_free': 2118.781494140625, 'fair_ppl_fix': 51689.3515625, 'unfair_ppl_banklike': 52182.9765625}
{'num_topics': 51, 'num_common_words': 59415, 'num_model_words': 114951, 'num_bt_words': 97541, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 15, 'lost_bt': 1, 'lost_model': 14}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}]}
2
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
  WTF: {'state'} {'fbi'}
topic_2
topic_3
  WTF: {'vs'} {'nhl'}
topic_4
topic_5
  WTF: {'dont', 'diet', 'surrender'} {'gordon', 'hiv', 'n3jxp'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_6
topic_7
topic_8
  WTF: {'votes'} {'o157h7'}
topic_9
  WTF: {'children', 'started', 'government', 'ottoman', 'muslim', 'saw'} {'armenia', 'azerbaijan', 'sumgait', 'turks', 'armenian', 'armenians'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_10
  WTF: {'ps'} {'bj200'}
topic_11
  WTF: {'toolbox', 'effortsall', 'dragdrop', 'taxation', 'Epilepsy', '207556000', 'CDROMCATZIP', 'NikeCajun', '8800CS', 'CSCSTD00385', 'L2PMABGZ7VAZV0PZRI', 'knowlege', 'ringleaders', '1795', '5152940082'} {''}
  WTF?!?!? 15
topic_12
  WTF: {'football', 'adventure', '35'} {'snes', 'cdi', 'sega'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_13
  WTF: {'dont', 'congress'} {'stephanopoulos', 'myers'}
topic_14
  WTF: {'posting', 'use'} {'rsa', 'ripem'}
topic_15
  WTF: {'russian', 'solve', 'printing', 'article', 'mesur', 'famous', 'envoy', 'wild'} {'iosef', 'anania', 'armenia', 'persians', 'orbeli', 'tyukhik', 'armenian', 'shirak'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_16
topic_17
topic_18
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_19
  WTF: {'festival'} {'ishtar'}
topic_20
topic_21
  WTF: {'250', 'use'} {'irwin', 'mactools'}
topic_22
  WTF: {'explanations', 'writing', 'vol', 'copyright', 'analytic', '02106chopinudeledu'} {'vinge', 'dune', 'vernor', 'gibson', 'baen', 'gre'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_23
topic_24
  WTF: {'circuitry', 'voltage'} {'emerson', 'vcr'}
topic_25
  WTF: {'intrinsics'} {'r3'}
topic_26
  WTF: {'try', 'card'} {'microsofts', 'sb'}
topic_27
topic_28
  WTF: {'400', 'grayscales', 'handheld', 'buy', 'scans', 'market'} {'ocr', 'dexxa', 'scanman', 'paintbrush', 'mustek', 'ocr104zip'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_29
  WTF: {'know', 'doityourselfers'} {'kirlian', 'krillean'}
topic_30
topic_31
topic_32
  WTF: {'use'} {'heydt'}
topic_33
  WTF: {'stripped', 'regards'} {'babak', 'sehari'}
topic_34
  WTF: {'list', 'utter', 'military', 'jobs'} {'irs', 'registries', 'c17', 'admistration'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_35
  WTF: {'april'} {'hicnet'}
topic_36
  WTF: {'worse', 'germany', 'dangerous'} {'femine', 'calverts', 'fatti'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_37
  WTF: {'bb', 'interested', 'mit'} {'sept', 'cambridge', 'quincy'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_38
  WTF: {'theory'} {'alice'}
topic_39
  WTF: {'launch', 'safety', 'power'} {'hpr', 'tripoli', 'faa'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_40
  WTF: {'nebulised'} {'bridgend'}
topic_41
topic_42
  WTF: {'stabilized', 'addition', 'version', 'pads', 'combo'} {'t4', 'salyut', 'russia', 'energiam', 't4centaur'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_43
  WTF: {'vending', 'patchmaking', 'unpatentable', 'remixed'} {'cocacola', 'yerazunis', 'cola', 'pepsi'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_44
  WTF: {'heinous', 'discussion', 'stalled'} {'hoovers', 'lyle', 'transarc'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_45
  WTF: {'yknow', 'nucleus', 'coma', 'windscreen'} {'tommy', 'canopies', 'punchline', 'mcwilliams'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_46
  WTF: {'nazism', 'hell', 'dem', 'mr', 'ya', 'moments', 'oddly', 'utilize'} {'zeuge', 'timucin', 'turc', 'davidssons', 'srinivas', 'yo', 'koph', 'hoffnung'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_47
  WTF: {'tp', 'mf', 'mj', 'mh', 'm1', 'u0', 'trinomials', 'mm', '644', 'pw', '0n', 'ma'} {'mx', 'm0', 'pnospsxop8f', 'mw', 'm6', 'o3', 'm5', 'm3', 'e8', 'lu', 'm9', 'p6'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_48
  WTF: {'licensed', 'product', 'promote', 'science', 'include', 'internet', 'publications'} {'regal', 'robb', 'milwaukee', 'wi', 'marquette', 'dubinski', 'doublemajor'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_49
  WTF: {'tooling', 'preproduction', 'compsysamigagraphics', 'licensees', 'bullshitting', '300'} {'activa', '3do', 'visicalc', 'riccione', 'bitmovie', 'sergio'}
  WTF?!?!? 6
  WTF?!?!? 6
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f303d44c310>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
  WTF: {'state'} {'fbi'}
topic_2
topic_3
  WTF: {'vs'} {'nhl'}
topic_4
topic_5
  WTF: {'dont', 'diet', 'surrender'} {'gordon', 'hiv', 'n3jxp'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_6
topic_7
topic_8
  WTF: {'votes'} {'o157h7'}
topic_9
  WTF: {'children', 'started', 'government', 'ottoman', 'muslim', 'saw'} {'armenia', 'azerbaijan', 'sumgait', 'turks', 'armenian', 'armenians'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_10
  WTF: {'ps'} {'bj200'}
topic_11
  WTF: {'toolbox', 'effortsall', 'dragdrop', 'taxation', 'Epilepsy', '207556000', 'CDROMCATZIP', 'NikeCajun', '8800CS', 'CSCSTD00385', 'L2PMABGZ7VAZV0PZRI', 'knowlege', 'ringleaders', '1795', '5152940082'} {''}
  WTF?!?!? 15
topic_12
  WTF: {'football', 'adventure', '35'} {'snes', 'cdi', 'sega'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_13
  WTF: {'dont', 'congress'} {'stephanopoulos', 'myers'}
topic_14
  WTF: {'posting', 'use'} {'rsa', 'ripem'}
topic_15
  WTF: {'russian', 'solve', 'printing', 'article', 'mesur', 'famous', 'envoy', 'wild'} {'iosef', 'anania', 'armenia', 'persians', 'orbeli', 'tyukhik', 'armenian', 'shirak'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_16
topic_17
topic_18
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_19
  WTF: {'festival'} {'ishtar'}
topic_20
topic_21
  WTF: {'250', 'use'} {'irwin', 'mactools'}
topic_22
  WTF: {'explanations', 'writing', 'vol', 'copyright', 'analytic', '02106chopinudeledu'} {'vinge', 'dune', 'vernor', 'gibson', 'baen', 'gre'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_23
topic_24
  WTF: {'circuitry', 'voltage'} {'emerson', 'vcr'}
topic_25
  WTF: {'intrinsics'} {'r3'}
topic_26
  WTF: {'try', 'card'} {'microsofts', 'sb'}
topic_27
topic_28
  WTF: {'400', 'grayscales', 'handheld', 'buy', 'scans', 'market'} {'ocr', 'dexxa', 'scanman', 'paintbrush', 'mustek', 'ocr104zip'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_29
  WTF: {'know', 'doityourselfers'} {'kirlian', 'krillean'}
topic_30
topic_31
topic_32
  WTF: {'use'} {'heydt'}
topic_33
  WTF: {'stripped', 'regards'} {'babak', 'sehari'}
topic_34
  WTF: {'list', 'utter', 'military', 'jobs'} {'irs', 'registries', 'c17', 'admistration'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_35
  WTF: {'april'} {'hicnet'}
topic_36
  WTF: {'worse', 'germany', 'dangerous'} {'femine', 'calverts', 'fatti'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_37
  WTF: {'bb', 'interested', 'mit'} {'sept', 'cambridge', 'quincy'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_38
  WTF: {'theory'} {'alice'}
topic_39
  WTF: {'launch', 'safety', 'power'} {'hpr', 'tripoli', 'faa'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_40
  WTF: {'nebulised'} {'bridgend'}
topic_41
topic_42
  WTF: {'stabilized', 'addition', 'version', 'pads', 'combo'} {'t4', 'salyut', 'russia', 'energiam', 't4centaur'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_43
  WTF: {'vending', 'patchmaking', 'unpatentable', 'remixed'} {'cocacola', 'yerazunis', 'cola', 'pepsi'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_44
  WTF: {'heinous', 'discussion', 'stalled'} {'hoovers', 'lyle', 'transarc'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_45
  WTF: {'yknow', 'nucleus', 'coma', 'windscreen'} {'tommy', 'canopies', 'punchline', 'mcwilliams'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_46
  WTF: {'nazism', 'hell', 'dem', 'mr', 'ya', 'moments', 'oddly', 'utilize'} {'zeuge', 'timucin', 'turc', 'davidssons', 'srinivas', 'yo', 'koph', 'hoffnung'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_47
  WTF: {'tp', 'mf', 'mj', 'mh', 'm1', 'u0', 'trinomials', 'mm', '644', 'pw', '0n', 'ma'} {'mx', 'm0', 'pnospsxop8f', 'mw', 'm6', 'o3', 'm5', 'm3', 'e8', 'lu', 'm9', 'p6'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_48
  WTF: {'licensed', 'product', 'promote', 'science', 'include', 'internet', 'publications'} {'regal', 'robb', 'milwaukee', 'wi', 'marquette', 'dubinski', 'doublemajor'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_49
  WTF: {'tooling', 'preproduction', 'compsysamigagraphics', 'licensees', 'bullshitting', '300'} {'activa', '3do', 'visicalc', 'riccione', 'bitmovie', 'sergio'}
  WTF?!?!? 6
  WTF?!?!? 6

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f2fc8bbbe20>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3015de9cd0>}
{'perplexity': 50938.7265625, 'coherence_20': 1.7564448591815767, 'toplen_ptw': 1.1494404134454776, 'diversity_euclidean': 0.10691279997770296, 'diversity_jensenshannon': 0.774906111123842, 'diversity_hellinger': 0.9199545822850284, 'diversity_cosine': 0.9136516144338805, 'fair_ppl_free': 2065.5439453125, 'fair_ppl_fix': 50273.37890625, 'unfair_ppl_banklike': 50938.7265625}
{'num_topics': 51, 'num_common_words': 59415, 'num_model_words': 114951, 'num_bt_words': 97541, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 16, 'lost_bt': 1, 'lost_model': 15}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}]}
3
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
topic_3
topic_4
  WTF: {'12'} {'nhl'}
topic_5
  WTF: {'dont', 'surrender', 'candida'} {'gordon', 'hiv', 'n3jxp'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_6
topic_7
topic_8
  WTF: {'thanks', 'posting'} {'o157h7', 'anania'}
topic_9
  WTF: {'children', 'started', 'government', 'ottoman', 'muslim', 'saw'} {'armenia', 'azerbaijan', 'sumgait', 'turks', 'armenian', 'armenians'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_10
  WTF: {'quality'} {'bj200'}
topic_11
topic_12
  WTF: {'toolbox', 'effortsall', 'dragdrop', 'taxation', 'Epilepsy', '207556000', 'CDROMCATZIP', 'NikeCajun', '8800CS', 'CSCSTD00385', 'L2PMABGZ7VAZV0PZRI', 'knowlege', 'ringleaders', '1795', '5152940082'} {''}
  WTF?!?!? 15
topic_13
topic_14
topic_15
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_16
topic_17
topic_18
  WTF: {'fuel', 'insisting', 'live'} {'cato', 'dryden', 'shafer'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_19
  WTF: {'fortran', 'writing', 'vol', 'copyright', 'analytic', '02106chopinudeledu'} {'vinge', 'vernor', 'petrucci', 'hogan', 'gibson', 'baen'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_20
  WTF: {'email', 'format'} {'irwin', 'mactools'}
topic_21
  WTF: {'try', 'card'} {'microsofts', 'sb'}
topic_22
  WTF: {'intrinsics'} {'r3'}
topic_23
  WTF: {'circuitry', 'heh'} {'emerson', 'vcr'}
topic_24
  WTF: {'english', 'people'} {'bede', 'ishtar'}
topic_25
  WTF: {'objects', 'charged'} {'kirlian', 'krillean'}
topic_26
  WTF: {'network', 'using', 'machines'} {'wfwg', 'odi', 'ndis'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_27
topic_28
topic_29
  WTF: {'aside'} {'darius'}
topic_30
  WTF: {'lemmings'} {'soundbase'}
topic_31
  WTF: {'cute'} {'heydt'}
topic_32
  WTF: {'regulator', 'paying'} {'geico', 'nofault'}
topic_33
  WTF: {'stripped', 'regards'} {'babak', 'sehari'}
topic_34
  WTF: {'nick', '49er', 'mit'} {'sept', 'cambridge', 'quincy'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_35
  WTF: {'rule', 'forget', 'bang'} {'douglas', 'alice', 'adams'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_36
  WTF: {'tutorial', 'participants', 'engineers', 'conference'} {'mellon', 'japan', 'jstmp', 'carnegie'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_37
  WTF: {'commission', 'utter', 'axe'} {'irs', 'registries', 'admistration'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_38
  WTF: {'motor', 'class', 'propellant'} {'hpr', 'tripoli', 'faa'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_39
  WTF: {'performance', 'hardisk', 'movie', '320x240'} {'compactvideo', '3do', '3d0o', 'ramvram'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_40
  WTF: {'uuencode', 'ioccc'} {'eofnotok', 'xvoid'}
topic_41
  WTF: {'existing', 'specificed'} {'scotyy', 'avagadros'}
topic_42
  WTF: {'years', 'tradition'} {'joe', 'olympia'}
topic_43
  WTF: {'correct', 'trick', 'screen'} {'supercharging', 'robbinsgreat', 'judd'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_44
  WTF: {'stabilized', 'addition', 'version', 'pads', 'combo'} {'t4', 'salyut', 'russia', 'energiam', 't4centaur'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_45
  WTF: {'tp', 'mf', 'mj', 'mh', 'm1', 'u0', 'trinomials', 'mm', '644', 'pw', '0n', 'ma'} {'mx', 'm0', 'pnospsxop8f', 'mw', 'm6', 'o3', 'm5', 'm3', 'e8', 'lu', 'm9', 'p6'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_46
  WTF: {'fee', 'writes', 'equally', 'involved', 'aj', 'construction'} {'teel', 'ajteeldendritecscoloradoedu', 'reitman', 'schiff', 'daniel', 'newman'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_47
  WTF: {'drag'} {'mary'}
topic_48
  WTF: {'memorial', 'sun', 'culture', 'service', 'scientific', 'centers', 'ghetto'} {'nozyk', 'shul', 'palace', 'belorusskaya', 'iki', 'moscow', 'kremlin'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_49
  WTF: {'concentrates', 'sooo', 'cover', 'merciless', 'infringing', 'design', 'ideas'} {'crah', 'yerazunis', 'cola', 'cocacola', 'pepsicos', 'pepsi', 'rc4'}
  WTF?!?!? 7
  WTF?!?!? 7
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f2e3f6dfc40>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
topic_3
topic_4
  WTF: {'12'} {'nhl'}
topic_5
  WTF: {'dont', 'surrender', 'candida'} {'gordon', 'hiv', 'n3jxp'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_6
topic_7
topic_8
  WTF: {'thanks', 'posting'} {'o157h7', 'anania'}
topic_9
  WTF: {'children', 'started', 'government', 'ottoman', 'muslim', 'saw'} {'armenia', 'azerbaijan', 'sumgait', 'turks', 'armenian', 'armenians'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_10
  WTF: {'quality'} {'bj200'}
topic_11
topic_12
  WTF: {'toolbox', 'effortsall', 'dragdrop', 'taxation', 'Epilepsy', '207556000', 'CDROMCATZIP', 'NikeCajun', '8800CS', 'CSCSTD00385', 'L2PMABGZ7VAZV0PZRI', 'knowlege', 'ringleaders', '1795', '5152940082'} {''}
  WTF?!?!? 15
topic_13
topic_14
topic_15
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_16
topic_17
topic_18
  WTF: {'fuel', 'insisting', 'live'} {'cato', 'dryden', 'shafer'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_19
  WTF: {'fortran', 'writing', 'vol', 'copyright', 'analytic', '02106chopinudeledu'} {'vinge', 'vernor', 'petrucci', 'hogan', 'gibson', 'baen'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_20
  WTF: {'email', 'format'} {'irwin', 'mactools'}
topic_21
  WTF: {'try', 'card'} {'microsofts', 'sb'}
topic_22
  WTF: {'intrinsics'} {'r3'}
topic_23
  WTF: {'circuitry', 'heh'} {'emerson', 'vcr'}
topic_24
  WTF: {'english', 'people'} {'bede', 'ishtar'}
topic_25
  WTF: {'objects', 'charged'} {'kirlian', 'krillean'}
topic_26
  WTF: {'network', 'using', 'machines'} {'wfwg', 'odi', 'ndis'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_27
topic_28
topic_29
  WTF: {'aside'} {'darius'}
topic_30
  WTF: {'lemmings'} {'soundbase'}
topic_31
  WTF: {'cute'} {'heydt'}
topic_32
  WTF: {'regulator', 'paying'} {'geico', 'nofault'}
topic_33
  WTF: {'stripped', 'regards'} {'babak', 'sehari'}
topic_34
  WTF: {'nick', '49er', 'mit'} {'sept', 'cambridge', 'quincy'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_35
  WTF: {'rule', 'forget', 'bang'} {'douglas', 'alice', 'adams'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_36
  WTF: {'tutorial', 'participants', 'engineers', 'conference'} {'mellon', 'japan', 'jstmp', 'carnegie'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_37
  WTF: {'commission', 'utter', 'axe'} {'irs', 'registries', 'admistration'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_38
  WTF: {'motor', 'class', 'propellant'} {'hpr', 'tripoli', 'faa'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_39
  WTF: {'performance', 'hardisk', 'movie', '320x240'} {'compactvideo', '3do', '3d0o', 'ramvram'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_40
  WTF: {'uuencode', 'ioccc'} {'eofnotok', 'xvoid'}
topic_41
  WTF: {'existing', 'specificed'} {'scotyy', 'avagadros'}
topic_42
  WTF: {'years', 'tradition'} {'joe', 'olympia'}
topic_43
  WTF: {'correct', 'trick', 'screen'} {'supercharging', 'robbinsgreat', 'judd'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_44
  WTF: {'stabilized', 'addition', 'version', 'pads', 'combo'} {'t4', 'salyut', 'russia', 'energiam', 't4centaur'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_45
  WTF: {'tp', 'mf', 'mj', 'mh', 'm1', 'u0', 'trinomials', 'mm', '644', 'pw', '0n', 'ma'} {'mx', 'm0', 'pnospsxop8f', 'mw', 'm6', 'o3', 'm5', 'm3', 'e8', 'lu', 'm9', 'p6'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_46
  WTF: {'fee', 'writes', 'equally', 'involved', 'aj', 'construction'} {'teel', 'ajteeldendritecscoloradoedu', 'reitman', 'schiff', 'daniel', 'newman'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_47
  WTF: {'drag'} {'mary'}
topic_48
  WTF: {'memorial', 'sun', 'culture', 'service', 'scientific', 'centers', 'ghetto'} {'nozyk', 'shul', 'palace', 'belorusskaya', 'iki', 'moscow', 'kremlin'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_49
  WTF: {'concentrates', 'sooo', 'cover', 'merciless', 'infringing', 'design', 'ideas'} {'crah', 'yerazunis', 'cola', 'cocacola', 'pepsicos', 'pepsi', 'rc4'}
  WTF?!?!? 7
  WTF?!?!? 7

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3090996ac0>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3073c72fa0>}
{'perplexity': 50915.80078125, 'coherence_20': 1.7958162381084457, 'toplen_ptw': 1.1574981169091882, 'diversity_euclidean': 0.1062903431873827, 'diversity_jensenshannon': 0.7755513038558738, 'diversity_hellinger': 0.9210673069048732, 'diversity_cosine': 0.9177605980824759, 'fair_ppl_free': 2061.677734375, 'fair_ppl_fix': 50217.4765625, 'unfair_ppl_banklike': 50915.80078125}
{'num_topics': 51, 'num_common_words': 59415, 'num_model_words': 114951, 'num_bt_words': 97541, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 16, 'lost_bt': 1, 'lost_model': 15}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}]}
4
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
  WTF: {'vs'} {'nhl'}
topic_3
topic_4
topic_5
  WTF: {'dont', 'surrender', 'candida'} {'gordon', 'hiv', 'n3jxp'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_6
topic_7
topic_8
  WTF: {'votes'} {'o157h7'}
topic_9
topic_10
  WTF: {'children', 'started', 'government', 'ottoman', 'muslim', 'saw'} {'armenia', 'azerbaijan', 'sumgait', 'turks', 'armenian', 'armenians'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_11
  WTF: {'driver'} {'bj200'}
topic_12
  WTF: {'toolbox', 'effortsall', 'dragdrop', 'taxation', 'Epilepsy', '207556000', 'CDROMCATZIP', 'NikeCajun', '8800CS', 'CSCSTD00385', 'L2PMABGZ7VAZV0PZRI', 'knowlege', 'ringleaders', '1795', '5152940082'} {''}
  WTF?!?!? 15
topic_13
  WTF: {'email', 'posting'} {'rsa', 'ripem'}
topic_14
  WTF: {'transferable'} {'hotelco'}
topic_15
topic_16
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_17
  WTF: {'declutch'} {'caltrans'}
topic_18
topic_19
  WTF: {'reactor'} {'cato'}
topic_20
topic_21
  WTF: {'250', 'use'} {'irwin', 'mactools'}
topic_22
topic_23
  WTF: {'writing', 'vol', 'copyright', 'analytic', '02106chopinudeledu', 'manual'} {'vinge', 'dune', 'vernor', 'hogan', 'gibson', 'baen'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_24
  WTF: {'server'} {'r3'}
topic_25
  WTF: {'know', 'doityourselfers'} {'kirlian', 'krillean'}
topic_26
topic_27
  WTF: {'400', 'resoltuion', 'handheld', 'buy', 'scans', 'market'} {'ocr', 'dexxa', 'scanman', 'paintbrush', 'mustek', 'ocr104zip'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_28
topic_29
topic_30
  WTF: {'aside'} {'darius'}
topic_31
  WTF: {'shield', 'vulnerable'} {'emi', 'hv'}
topic_32
  WTF: {'nick', '49er', 'mit'} {'sept', 'cambridge', 'quincy'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_33
  WTF: {'stripped', 'regards'} {'babak', 'sehari'}
topic_34
  WTF: {'number', 'rule', 'computer'} {'douglas', 'alice', 'adams'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_35
  WTF: {'uuencode', 'ioccc'} {'eofnotok', 'xvoid'}
topic_36
topic_37
  WTF: {'radars', 'element', 'km', 'phase', 'pattern', 'results', 'geodetic'} {'exosc', 'egs', 'rrl', 'japan', 'ohzora', 'kyoto', 'sato'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_38
  WTF: {'difference'} {'dj'}
topic_39
  WTF: {'commission', 'corps', 'axe'} {'irs', 'registries', 'admistration'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_40
topic_41
  WTF: {'dont', 'memorable', 'somethin', 'changing', 'trench'} {'yankess', 'dykstra', 'ballad', 'subterranean', 'anime'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_42
topic_43
  WTF: {'audio', 'problem', 'returned'} {'hifi', 'emerson', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_44
  WTF: {'2275753', '2273618', 'lipmanoasysdtnavymil', 'pace'} {'sigkids', 'siggraph', 'lipman', 'bethesda'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_45
  WTF: {'tp', 'mf', 'mj', 'mh', 'm1', 'u0', 'trinomials', 'mm', '644', 'pw', '0n', 'ma'} {'mx', 'm0', 'pnospsxop8f', 'mw', 'm6', 'o3', 'm5', 'm3', 'e8', 'lu', 'm9', 'p6'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_46
  WTF: {'years', 'tradition'} {'joe', 'olympia'}
topic_47
  WTF: {'stabilized', 'addition', 'version', 'pads', 'combo'} {'t4', 'salyut', 'russia', 'energiam', 't4centaur'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_48
  WTF: {'popular', 'flight', 'purchase'} {'hpr', 'tripoli', 'faa'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_49
  WTF: {'improvements', 'version', 'upgrading'} {'ipas', 'v200', 'photostyler'}
  WTF?!?!? 3
  WTF?!?!? 3
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3015e06910>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
  WTF: {'vs'} {'nhl'}
topic_3
topic_4
topic_5
  WTF: {'dont', 'surrender', 'candida'} {'gordon', 'hiv', 'n3jxp'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_6
topic_7
topic_8
  WTF: {'votes'} {'o157h7'}
topic_9
topic_10
  WTF: {'children', 'started', 'government', 'ottoman', 'muslim', 'saw'} {'armenia', 'azerbaijan', 'sumgait', 'turks', 'armenian', 'armenians'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_11
  WTF: {'driver'} {'bj200'}
topic_12
  WTF: {'toolbox', 'effortsall', 'dragdrop', 'taxation', 'Epilepsy', '207556000', 'CDROMCATZIP', 'NikeCajun', '8800CS', 'CSCSTD00385', 'L2PMABGZ7VAZV0PZRI', 'knowlege', 'ringleaders', '1795', '5152940082'} {''}
  WTF?!?!? 15
topic_13
  WTF: {'email', 'posting'} {'rsa', 'ripem'}
topic_14
  WTF: {'transferable'} {'hotelco'}
topic_15
topic_16
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_17
  WTF: {'declutch'} {'caltrans'}
topic_18
topic_19
  WTF: {'reactor'} {'cato'}
topic_20
topic_21
  WTF: {'250', 'use'} {'irwin', 'mactools'}
topic_22
topic_23
  WTF: {'writing', 'vol', 'copyright', 'analytic', '02106chopinudeledu', 'manual'} {'vinge', 'dune', 'vernor', 'hogan', 'gibson', 'baen'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_24
  WTF: {'server'} {'r3'}
topic_25
  WTF: {'know', 'doityourselfers'} {'kirlian', 'krillean'}
topic_26
topic_27
  WTF: {'400', 'resoltuion', 'handheld', 'buy', 'scans', 'market'} {'ocr', 'dexxa', 'scanman', 'paintbrush', 'mustek', 'ocr104zip'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_28
topic_29
topic_30
  WTF: {'aside'} {'darius'}
topic_31
  WTF: {'shield', 'vulnerable'} {'emi', 'hv'}
topic_32
  WTF: {'nick', '49er', 'mit'} {'sept', 'cambridge', 'quincy'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_33
  WTF: {'stripped', 'regards'} {'babak', 'sehari'}
topic_34
  WTF: {'number', 'rule', 'computer'} {'douglas', 'alice', 'adams'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_35
  WTF: {'uuencode', 'ioccc'} {'eofnotok', 'xvoid'}
topic_36
topic_37
  WTF: {'radars', 'element', 'km', 'phase', 'pattern', 'results', 'geodetic'} {'exosc', 'egs', 'rrl', 'japan', 'ohzora', 'kyoto', 'sato'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_38
  WTF: {'difference'} {'dj'}
topic_39
  WTF: {'commission', 'corps', 'axe'} {'irs', 'registries', 'admistration'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_40
topic_41
  WTF: {'dont', 'memorable', 'somethin', 'changing', 'trench'} {'yankess', 'dykstra', 'ballad', 'subterranean', 'anime'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_42
topic_43
  WTF: {'audio', 'problem', 'returned'} {'hifi', 'emerson', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_44
  WTF: {'2275753', '2273618', 'lipmanoasysdtnavymil', 'pace'} {'sigkids', 'siggraph', 'lipman', 'bethesda'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_45
  WTF: {'tp', 'mf', 'mj', 'mh', 'm1', 'u0', 'trinomials', 'mm', '644', 'pw', '0n', 'ma'} {'mx', 'm0', 'pnospsxop8f', 'mw', 'm6', 'o3', 'm5', 'm3', 'e8', 'lu', 'm9', 'p6'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_46
  WTF: {'years', 'tradition'} {'joe', 'olympia'}
topic_47
  WTF: {'stabilized', 'addition', 'version', 'pads', 'combo'} {'t4', 'salyut', 'russia', 'energiam', 't4centaur'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_48
  WTF: {'popular', 'flight', 'purchase'} {'hpr', 'tripoli', 'faa'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_49
  WTF: {'improvements', 'version', 'upgrading'} {'ipas', 'v200', 'photostyler'}
  WTF?!?!? 3
  WTF?!?!? 3

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f2e08b9e610>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f2dc4de4550>}
{'perplexity': 51101.72265625, 'coherence_20': 1.9122876897814254, 'toplen_ptw': 1.1621013911939058, 'diversity_euclidean': 0.10087701100719147, 'diversity_jensenshannon': 0.7736505934198132, 'diversity_hellinger': 0.9185885057595522, 'diversity_cosine': 0.9131660408053444, 'fair_ppl_free': 2046.1607666015625, 'fair_ppl_fix': 50372.00390625, 'unfair_ppl_banklike': 51101.72265625}
{'num_topics': 51, 'num_common_words': 59415, 'num_model_words': 114951, 'num_bt_words': 97541, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 16, 'lost_bt': 1, 'lost_model': 15}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}]}
5
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
topic_3
  WTF: {'vs'} {'nhl'}
topic_4
topic_5
  WTF: {'dont', 'diet', 'surrender'} {'gordon', 'hiv', 'n3jxp'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_6
topic_7
topic_8
  WTF: {'posting'} {'o157h7'}
topic_9
  WTF: {'children', 'started', 'government', 'ottoman', 'muslim', 'saw'} {'armenia', 'azerbaijan', 'sumgait', 'turks', 'armenian', 'armenians'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_10
  WTF: {'scanner'} {'bj200'}
topic_11
  WTF: {'toolbox', 'effortsall', 'dragdrop', 'recollection', 'taxation', 'CDROMCATZIP', '207556000', 'NikeDeacon', 'NikeCajun', '8800CS', 'CSCSTD00385', 'L2PMABGZ7VAZV0PZRI', '1795', '5152940082'} {''}
  WTF?!?!? 14
topic_12
  WTF: {'transferable'} {'hotelco'}
topic_13
topic_14
topic_15
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_16
  WTF: {'testtaking', 'general', 'karichaeiscalstateedu', 'length'} {'boulder', 'rex', 'gre', 'ets'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_17
  WTF: {'reactor'} {'cato'}
topic_18
topic_19
  WTF: {'writing', 'vol', 'copyright', 'analytic', '02106chopinudeledu', 'manual'} {'vinge', 'vernor', 'petrucci', 'hogan', 'gibson', 'baen'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_20
  WTF: {'innate', 'pay', 'people'} {'vip', 'heydt', 'cnn'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_21
  WTF: {'250', 'pickup'} {'irwin', 'mactools'}
topic_22
  WTF: {'intrinsics'} {'r3'}
topic_23
topic_24
  WTF: {'try', 'card'} {'microsofts', 'sb'}
topic_25
  WTF: {'english', 'spring', 'people'} {'bede', 'pesach', 'ishtar'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_26
  WTF: {'objects', 'charged'} {'kirlian', 'krillean'}
topic_27
topic_28
  WTF: {'russian', 'solve', 'typeset', 'printing', 'mesur', 'famous', 'envoy', 'wild'} {'iosef', 'anania', 'armenia', 'persians', 'orbeli', 'tyukhik', 'armenian', 'shirak'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_29
  WTF: {'pork', 'abolished', 'immoral', 'bases'} {'registries', 'c5s', 'c17', 'admistration'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_30
  WTF: {'pm', 'students', 'cs', 'andrew'} {'mellon', 'japan', 'jstmp', 'carnegie'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_31
  WTF: {'stripped', 'regards'} {'babak', 'sehari'}
topic_32
  WTF: {'aside'} {'darius'}
topic_33
  WTF: {'nick', '49er', 'mit'} {'sept', 'cambridge', 'quincy'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_34
  WTF: {'theory'} {'alice'}
topic_35
  WTF: {'sodium', 'class', 'propellant'} {'hpr', 'tripoli', 'faa'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_36
  WTF: {'readers', 'use', 'send', 'advertisers'} {'cocacola', 'tektronics', 'cola', 'pepsi'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_37
  WTF: {'youll', 'expound', 'usa'} {'hoovers', 'lyle', 'transarc'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_38
  WTF: {'pipes'} {'mary'}
topic_39
  WTF: {'screen', 'trick', 'switcher'} {'supercharging', 'robbinsgreat', 'judd'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_40
  WTF: {'signature', 'holds', 'spring', 'direction', 'dark'} {'exussr', 'nicks', 'hrivnak', 'albert', 'pitily'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_41
  WTF: {'years', 'tradition'} {'joe', 'olympia'}
topic_42
  WTF: {'stabilized', 'addition', 'version', 'pads', 'combo'} {'t4', 'salyut', 'russia', 'energiam', 't4centaur'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_43
  WTF: {'audio', 'problem', 'returned'} {'hifi', 'emerson', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_44
  WTF: {'980665', 'microns', '1163'} {'inhalation', '9g', 'bridgend'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_45
  WTF: {'promote'} {'fenholt'}
topic_46
  WTF: {'cuz', 'outlived'} {'menuts', 'scotyy'}
topic_47
  WTF: {'2042', '2273618', 'pace', '2275753', 'lipmanoasysdtnavymil'} {'sigkids', 'navyrelated', 'siggraph', 'lipman', 'bethesda'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_48
  WTF: {'tp', 'mf', 'mj', 'mh', 'm1', 'u0', 'trinomials', 'mm', '644', 'pw', '0n', 'ma'} {'mx', 'm0', 'pnospsxop8f', 'mw', 'm6', 'o3', 'm5', 'm3', 'e8', 'lu', 'm9', 'p6'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_49
  WTF: {'racers', 'rebel', '90s', 'rednecks', 'soar', '8177', 'giveaway'} {'yogis', 'yogi', 'pgh', 'thumper', 'smokey', 'mcqueen', 'bandit'}
  WTF?!?!? 7
  WTF?!?!? 7
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3015eb3520>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
topic_3
  WTF: {'vs'} {'nhl'}
topic_4
topic_5
  WTF: {'dont', 'diet', 'surrender'} {'gordon', 'hiv', 'n3jxp'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_6
topic_7
topic_8
  WTF: {'posting'} {'o157h7'}
topic_9
  WTF: {'children', 'started', 'government', 'ottoman', 'muslim', 'saw'} {'armenia', 'azerbaijan', 'sumgait', 'turks', 'armenian', 'armenians'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_10
  WTF: {'scanner'} {'bj200'}
topic_11
  WTF: {'toolbox', 'effortsall', 'dragdrop', 'recollection', 'taxation', 'CDROMCATZIP', '207556000', 'NikeDeacon', 'NikeCajun', '8800CS', 'CSCSTD00385', 'L2PMABGZ7VAZV0PZRI', '1795', '5152940082'} {''}
  WTF?!?!? 14
topic_12
  WTF: {'transferable'} {'hotelco'}
topic_13
topic_14
topic_15
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_16
  WTF: {'testtaking', 'general', 'karichaeiscalstateedu', 'length'} {'boulder', 'rex', 'gre', 'ets'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_17
  WTF: {'reactor'} {'cato'}
topic_18
topic_19
  WTF: {'writing', 'vol', 'copyright', 'analytic', '02106chopinudeledu', 'manual'} {'vinge', 'vernor', 'petrucci', 'hogan', 'gibson', 'baen'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_20
  WTF: {'innate', 'pay', 'people'} {'vip', 'heydt', 'cnn'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_21
  WTF: {'250', 'pickup'} {'irwin', 'mactools'}
topic_22
  WTF: {'intrinsics'} {'r3'}
topic_23
topic_24
  WTF: {'try', 'card'} {'microsofts', 'sb'}
topic_25
  WTF: {'english', 'spring', 'people'} {'bede', 'pesach', 'ishtar'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_26
  WTF: {'objects', 'charged'} {'kirlian', 'krillean'}
topic_27
topic_28
  WTF: {'russian', 'solve', 'typeset', 'printing', 'mesur', 'famous', 'envoy', 'wild'} {'iosef', 'anania', 'armenia', 'persians', 'orbeli', 'tyukhik', 'armenian', 'shirak'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_29
  WTF: {'pork', 'abolished', 'immoral', 'bases'} {'registries', 'c5s', 'c17', 'admistration'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_30
  WTF: {'pm', 'students', 'cs', 'andrew'} {'mellon', 'japan', 'jstmp', 'carnegie'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_31
  WTF: {'stripped', 'regards'} {'babak', 'sehari'}
topic_32
  WTF: {'aside'} {'darius'}
topic_33
  WTF: {'nick', '49er', 'mit'} {'sept', 'cambridge', 'quincy'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_34
  WTF: {'theory'} {'alice'}
topic_35
  WTF: {'sodium', 'class', 'propellant'} {'hpr', 'tripoli', 'faa'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_36
  WTF: {'readers', 'use', 'send', 'advertisers'} {'cocacola', 'tektronics', 'cola', 'pepsi'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_37
  WTF: {'youll', 'expound', 'usa'} {'hoovers', 'lyle', 'transarc'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_38
  WTF: {'pipes'} {'mary'}
topic_39
  WTF: {'screen', 'trick', 'switcher'} {'supercharging', 'robbinsgreat', 'judd'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_40
  WTF: {'signature', 'holds', 'spring', 'direction', 'dark'} {'exussr', 'nicks', 'hrivnak', 'albert', 'pitily'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_41
  WTF: {'years', 'tradition'} {'joe', 'olympia'}
topic_42
  WTF: {'stabilized', 'addition', 'version', 'pads', 'combo'} {'t4', 'salyut', 'russia', 'energiam', 't4centaur'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_43
  WTF: {'audio', 'problem', 'returned'} {'hifi', 'emerson', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_44
  WTF: {'980665', 'microns', '1163'} {'inhalation', '9g', 'bridgend'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_45
  WTF: {'promote'} {'fenholt'}
topic_46
  WTF: {'cuz', 'outlived'} {'menuts', 'scotyy'}
topic_47
  WTF: {'2042', '2273618', 'pace', '2275753', 'lipmanoasysdtnavymil'} {'sigkids', 'navyrelated', 'siggraph', 'lipman', 'bethesda'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_48
  WTF: {'tp', 'mf', 'mj', 'mh', 'm1', 'u0', 'trinomials', 'mm', '644', 'pw', '0n', 'ma'} {'mx', 'm0', 'pnospsxop8f', 'mw', 'm6', 'o3', 'm5', 'm3', 'e8', 'lu', 'm9', 'p6'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_49
  WTF: {'racers', 'rebel', '90s', 'rednecks', 'soar', '8177', 'giveaway'} {'yogis', 'yogi', 'pgh', 'thumper', 'smokey', 'mcqueen', 'bandit'}
  WTF?!?!? 7
  WTF?!?!? 7

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f30b0598130>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f2d4af1ca90>}
{'perplexity': 51663.9609375, 'coherence_20': 1.7414886569592958, 'toplen_ptw': 1.1461235986542255, 'diversity_euclidean': 0.10892007590922914, 'diversity_jensenshannon': 0.7807779079687608, 'diversity_hellinger': 0.9277581730022451, 'diversity_cosine': 0.9209706307366751, 'fair_ppl_free': 2096.759521484375, 'fair_ppl_fix': 51151.390625, 'unfair_ppl_banklike': 51663.9609375}
{'num_topics': 51, 'num_common_words': 59415, 'num_model_words': 114951, 'num_bt_words': 97541, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 15, 'lost_bt': 1, 'lost_model': 14}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}]}
6
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
  WTF: {'vs'} {'nhl'}
topic_3
topic_4
  WTF: {'banks', 'surrender', 'candida'} {'gordon', 'hiv', 'n3jxp'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_5
topic_6
  WTF: {'discussion'} {'o157h7'}
topic_7
  WTF: {'children', 'started', 'government', 'ottoman', 'muslim', 'saw'} {'armenia', 'azerbaijan', 'sumgait', 'turks', 'armenian', 'armenians'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_8
  WTF: {'im'} {'bj200'}
topic_9
  WTF: {'paradoxes', 'recollection', 'effortsall', 'taxation', 'CDROMCATZIP', '207556000', 'NikeCajun', '8800CS', 'CSCSTD00385', 'strobe', 'Ferris', 'knowlege', 'ringleaders', '5152940082'} {'', 'whatta'}
  WTF?!?!? 14
topic_10
topic_11
  WTF: {'controller', 'adventure', '35'} {'snes', 'cdi', 'sega'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_12
  WTF: {'mail'} {'ripem'}
topic_13
topic_14
  WTF: {'drv'} {'soundbase'}
topic_15
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_16
topic_17
topic_18
  WTF: {'email', 'writing', 'vol', 'copyright', 'analytic', '02106chopinudeledu'} {'vinge', 'dune', 'vernor', 'petrucci', 'gibson', 'baen'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_19
topic_20
  WTF: {'250', 'pickup'} {'irwin', 'mactools'}
topic_21
  WTF: {'thanks', '400', 'grayscales', 'buy', 'scans', 'market'} {'ocr', 'dexxa', 'scanman', 'paintbrush', 'mustek', 'ocr104zip'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_22
  WTF: {'ra', 'suspiciously', 'membership', 'arenas', 'active'} {'guzzi', 'ama', 'bmwmoa', 'moa', 'stafford'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_23
  WTF: {'pm', 'students', 'cs', 'andrew'} {'mellon', 'japan', 'jstmp', 'carnegie'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_24
  WTF: {'king'} {'alice'}
topic_25
topic_26
  WTF: {'manufacture'} {'patent'}
topic_27
topic_28
  WTF: {'ownthen'} {'femine'}
topic_29
  WTF: {'cute'} {'heydt'}
topic_30
  WTF: {'russian', 'solve', 'typeset', 'printing', 'mesur', 'famous', 'envoy', 'wild'} {'iosef', 'anania', 'armenia', 'persians', 'orbeli', 'tyukhik', 'armenian', 'shirak'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_31
  WTF: {'coil'} {'emi'}
topic_32
  WTF: {'stripped', 'regards'} {'babak', 'sehari'}
topic_33
  WTF: {'list', 'utter', 'military', 'jobs'} {'irs', 'registries', 'c17', 'admistration'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_34
  WTF: {'tooling', 'compsysamigagraphics', '20'} {'ipas', 'v200', '3do'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_35
  WTF: {'nick', '49er', 'mit'} {'sept', 'cambridge', 'quincy'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_36
  WTF: {'inhalation', 'nostalgia', 'microns'} {'edgetacalculator', 'hexadecimals', 'bridgend'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_37
  WTF: {'mf', 'mh', 'mj', 'm1', 'u0', 'coke', 'trinomials', 'fuselage', 'mm', 'pw', '0n', 'ma'} {'mx', 'm0', 'pnospsxop8f', 'mw', 'm6', 'o3', 'm5', 'm3', 'e8', 'gh', 'm9', 'p6'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_38
  WTF: {'dc', 'balls', 'governmentmandated'} {'cato', 'dryden', 'shafer'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_39
  WTF: {'devoid', 'chew', 'contractors'} {'baghdad', 'mea', 'bnr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_40
  WTF: {'2275753', '2042', '2273618', 'pace'} {'sigkids', 'siggraph', 'lipman', 'bethesda'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_41
  WTF: {'years', 'playoff'} {'joe', 'olympia'}
topic_42
  WTF: {'stabilized', 'addition', 'version', 'pads', 'combo'} {'t4', 'salyut', 'russia', 'energiam', 't4centaur'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_43
  WTF: {'fps', 'quadra'} {'qt', '3d0o'}
topic_44
  WTF: {'promote'} {'fenholt'}
topic_45
  WTF: {'audio', 'problem', 'returned'} {'hifi', 'emerson', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_46
  WTF: {'yknow', 'windscreen', 'respondent', 'cones'} {'tommy', 'canopies', 'punchline', 'mcwilliams'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_47
  WTF: {'licensed', 'product', 'promote', 'science', 'include', 'internet', 'publications'} {'regal', 'robb', 'milwaukee', 'wi', 'marquette', 'dubinski', 'doublemajor'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_48
  WTF: {'elaborate', 'pretend', 'partial', 'pretends', 'rc', 'terribly', 'exotic', 'chemists'} {'crah', 'yerazunis', 'cola', 'rc2', 'cocacola', 'pepsicos', 'pepsi', 'rc4'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_49
  WTF: {'undergrad', 'bettereasier', 'routers', 'zawodny', 'numberoh', 'v2305'} {'dastar', 'phonenet', 'etherroutetcp', 'fallon', 'ncsa', 'localtalk'}
  WTF?!?!? 6
  WTF?!?!? 6
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f2d5782c1f0>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
  WTF: {'vs'} {'nhl'}
topic_3
topic_4
  WTF: {'banks', 'surrender', 'candida'} {'gordon', 'hiv', 'n3jxp'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_5
topic_6
  WTF: {'discussion'} {'o157h7'}
topic_7
  WTF: {'children', 'started', 'government', 'ottoman', 'muslim', 'saw'} {'armenia', 'azerbaijan', 'sumgait', 'turks', 'armenian', 'armenians'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_8
  WTF: {'im'} {'bj200'}
topic_9
  WTF: {'paradoxes', 'recollection', 'effortsall', 'taxation', 'CDROMCATZIP', '207556000', 'NikeCajun', '8800CS', 'CSCSTD00385', 'strobe', 'Ferris', 'knowlege', 'ringleaders', '5152940082'} {'', 'whatta'}
  WTF?!?!? 14
topic_10
topic_11
  WTF: {'controller', 'adventure', '35'} {'snes', 'cdi', 'sega'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_12
  WTF: {'mail'} {'ripem'}
topic_13
topic_14
  WTF: {'drv'} {'soundbase'}
topic_15
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_16
topic_17
topic_18
  WTF: {'email', 'writing', 'vol', 'copyright', 'analytic', '02106chopinudeledu'} {'vinge', 'dune', 'vernor', 'petrucci', 'gibson', 'baen'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_19
topic_20
  WTF: {'250', 'pickup'} {'irwin', 'mactools'}
topic_21
  WTF: {'thanks', '400', 'grayscales', 'buy', 'scans', 'market'} {'ocr', 'dexxa', 'scanman', 'paintbrush', 'mustek', 'ocr104zip'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_22
  WTF: {'ra', 'suspiciously', 'membership', 'arenas', 'active'} {'guzzi', 'ama', 'bmwmoa', 'moa', 'stafford'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_23
  WTF: {'pm', 'students', 'cs', 'andrew'} {'mellon', 'japan', 'jstmp', 'carnegie'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_24
  WTF: {'king'} {'alice'}
topic_25
topic_26
  WTF: {'manufacture'} {'patent'}
topic_27
topic_28
  WTF: {'ownthen'} {'femine'}
topic_29
  WTF: {'cute'} {'heydt'}
topic_30
  WTF: {'russian', 'solve', 'typeset', 'printing', 'mesur', 'famous', 'envoy', 'wild'} {'iosef', 'anania', 'armenia', 'persians', 'orbeli', 'tyukhik', 'armenian', 'shirak'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_31
  WTF: {'coil'} {'emi'}
topic_32
  WTF: {'stripped', 'regards'} {'babak', 'sehari'}
topic_33
  WTF: {'list', 'utter', 'military', 'jobs'} {'irs', 'registries', 'c17', 'admistration'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_34
  WTF: {'tooling', 'compsysamigagraphics', '20'} {'ipas', 'v200', '3do'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_35
  WTF: {'nick', '49er', 'mit'} {'sept', 'cambridge', 'quincy'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_36
  WTF: {'inhalation', 'nostalgia', 'microns'} {'edgetacalculator', 'hexadecimals', 'bridgend'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_37
  WTF: {'mf', 'mh', 'mj', 'm1', 'u0', 'coke', 'trinomials', 'fuselage', 'mm', 'pw', '0n', 'ma'} {'mx', 'm0', 'pnospsxop8f', 'mw', 'm6', 'o3', 'm5', 'm3', 'e8', 'gh', 'm9', 'p6'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_38
  WTF: {'dc', 'balls', 'governmentmandated'} {'cato', 'dryden', 'shafer'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_39
  WTF: {'devoid', 'chew', 'contractors'} {'baghdad', 'mea', 'bnr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_40
  WTF: {'2275753', '2042', '2273618', 'pace'} {'sigkids', 'siggraph', 'lipman', 'bethesda'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_41
  WTF: {'years', 'playoff'} {'joe', 'olympia'}
topic_42
  WTF: {'stabilized', 'addition', 'version', 'pads', 'combo'} {'t4', 'salyut', 'russia', 'energiam', 't4centaur'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_43
  WTF: {'fps', 'quadra'} {'qt', '3d0o'}
topic_44
  WTF: {'promote'} {'fenholt'}
topic_45
  WTF: {'audio', 'problem', 'returned'} {'hifi', 'emerson', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_46
  WTF: {'yknow', 'windscreen', 'respondent', 'cones'} {'tommy', 'canopies', 'punchline', 'mcwilliams'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_47
  WTF: {'licensed', 'product', 'promote', 'science', 'include', 'internet', 'publications'} {'regal', 'robb', 'milwaukee', 'wi', 'marquette', 'dubinski', 'doublemajor'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_48
  WTF: {'elaborate', 'pretend', 'partial', 'pretends', 'rc', 'terribly', 'exotic', 'chemists'} {'crah', 'yerazunis', 'cola', 'rc2', 'cocacola', 'pepsicos', 'pepsi', 'rc4'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_49
  WTF: {'undergrad', 'bettereasier', 'routers', 'zawodny', 'numberoh', 'v2305'} {'dastar', 'phonenet', 'etherroutetcp', 'fallon', 'ncsa', 'localtalk'}
  WTF?!?!? 6
  WTF?!?!? 6

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f30b0598820>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3073b40e50>}
{'perplexity': 57292.03515625, 'coherence_20': 1.727850477437102, 'toplen_ptw': 1.151197254010596, 'diversity_euclidean': 0.10833439596812629, 'diversity_jensenshannon': 0.780942442445229, 'diversity_hellinger': 0.9282859474473402, 'diversity_cosine': 0.9222577491730978, 'fair_ppl_free': 2111.054443359375, 'fair_ppl_fix': 56563.1171875, 'unfair_ppl_banklike': 57292.03515625}
{'num_topics': 51, 'num_common_words': 59415, 'num_model_words': 114951, 'num_bt_words': 97541, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 16, 'lost_bt': 2, 'lost_model': 14}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}]}
7
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
topic_3
  WTF: {'vs'} {'nhl'}
topic_4
topic_5
topic_6
  WTF: {'dont', 'surrender', 'candida'} {'gordon', 'hiv', 'n3jxp'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_7
  WTF: {'land'} {'stephanopoulos'}
topic_8
  WTF: {'children', 'started', 'government', 'ottoman', 'muslim', 'saw'} {'armenia', 'azerbaijan', 'sumgait', 'turks', 'armenian', 'armenians'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_9
  WTF: {'like', 'sin'} {'caligiuri', 'enviroleague'}
topic_10
  WTF: {'toolbox', 'effortsall', 'dragdrop', 'recollection', 'taxation', 'CDROMCATZIP', '207556000', 'NikeCajun', '8800CS', 'CSCSTD00385', 'L2PMABGZ7VAZV0PZRI', 'strobe', 'knowlege', 'JH2SC281XPM100187', '1795', '5152940082'} {''}
  WTF?!?!? 16
topic_11
topic_12
  WTF: {'uk', 'controller'} {'cdi', 'sega'}
topic_13
  WTF: {'congress', 'working'} {'stephanopoulos', 'myers'}
topic_14
  WTF: {'new'} {'hotelco'}
topic_15
topic_16
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_17
  WTF: {'festival'} {'ishtar'}
topic_18
topic_19
  WTF: {'table'} {'alice'}
topic_20
  WTF: {'250', 'use'} {'irwin', 'mactools'}
topic_21
  WTF: {'energy', 'balls'} {'dryden', 'shafer'}
topic_22
  WTF: {'university', 'hebrew', 'april', 'oriental', 'dead', 'metaphysical', 'orders', 'equinox', 'golden', 'superior', 'dawn', 'studies'} {'rosae', 'orientis', 'reuss', 'crowley', 'qumran', 'crucis', 'ordo', 'rosicrucian', 'amorc', 'frater', 'oto', 'templi'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_23
  WTF: {'intrinsics'} {'r3'}
topic_24
  WTF: {'writing', 'vol', 'copyright', 'analytic', '02106chopinudeledu', 'manual'} {'vinge', 'dune', 'vernor', 'hogan', 'gibson', 'baen'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_25
topic_26
topic_27
  WTF: {'si', 'socket', 'focus', 'apple', 'able'} {'marvins', 'lciii', 'spigot', 'etherlan', 'pds'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_28
topic_29
topic_30
  WTF: {'tutorial', 'participants', 'engineers', 'conference'} {'mellon', 'japan', 'jstmp', 'carnegie'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_31
  WTF: {'62000', '42839'} {'reids', 'heydt'}
topic_32
  WTF: {'stripped', 'regards'} {'babak', 'sehari'}
topic_33
  WTF: {'plays', 'groundballs', 'goldglover', 'batted', 'clutch', 'studied', 'player'} {'rni', 'baergas', 'slg', 'baerga', 'dps', 'alomars', 'alomar'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_34
  WTF: {'abolished', 'immoral', 'deficit'} {'registries', 'c17', 'admistration'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_35
  WTF: {'nick', '49er', 'mit'} {'sept', 'cambridge', 'quincy'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_36
  WTF: {'gourd', 'netperson', 'equalize', 'capacitive'} {'behnke', 'nat', 'behnkefnalffnalgov', 'pistrix'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_37
  WTF: {'uuencode', 'ioccc'} {'eofnotok', 'xvoid'}
topic_38
  WTF: {'commercially'} {'emi'}
topic_39
  WTF: {'sure', '2020', 'flyback'} {'hifi', 'emerson', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_40
topic_41
  WTF: {'dragdrop', 'recollection', 'Uzi', 'L2PMABGZ7VAZV0PZRI', 'Guideline', 'knowlege', 'JH2SC281XPM100187', '1795', 'toolbox', 'effortsall', 'taxation', 'CDROMCATZIP', '207556000', 'NikeCajun', '8800CS', 'CSCSTD00385', 'strobe', 'monthly', '5152940082'} {''}
  WTF?!?!? 19
topic_42
  WTF: {'headin', 'roam', 'fortyniner', 'excavating', 'predictionsteam', 'melody'} {'dykstra', 'ballad', 'subterranean', 'anime', 'dwelt', 'clementine'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_43
  WTF: {'vending', 'patchmaking', 'remixed', 'patentable'} {'cocacola', 'yerazunis', 'cola', 'pepsi'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_44
  WTF: {'tp', 'mf', 'mj', 'mh', 'm1', 'u0', 'trinomials', 'mm', '644', 'pw', '0n', 'ma'} {'mx', 'm0', 'pnospsxop8f', 'mw', 'm6', 'o3', 'm5', 'm3', 'e8', 'lu', 'm9', 'p6'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_45
  WTF: {'stabilized', 'addition', 'version', 'pads', 'combo'} {'t4', 'salyut', 'russia', 'energiam', 't4centaur'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_46
  WTF: {'promote'} {'fenholt'}
topic_47
  WTF: {'csamiga', 'significant', 'look', 'thank', 'wrongthe'} {'activa', 'v200', 'bitmovie', 'sergio', 'r3d'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_48
  WTF: {'drag'} {'mary'}
topic_49
  WTF: {'commercial', 'integer'} {'macsyma', 'pcdos'}
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f2dc4de49a0>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
topic_3
  WTF: {'vs'} {'nhl'}
topic_4
topic_5
topic_6
  WTF: {'dont', 'surrender', 'candida'} {'gordon', 'hiv', 'n3jxp'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_7
  WTF: {'land'} {'stephanopoulos'}
topic_8
  WTF: {'children', 'started', 'government', 'ottoman', 'muslim', 'saw'} {'armenia', 'azerbaijan', 'sumgait', 'turks', 'armenian', 'armenians'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_9
  WTF: {'like', 'sin'} {'caligiuri', 'enviroleague'}
topic_10
  WTF: {'toolbox', 'effortsall', 'dragdrop', 'recollection', 'taxation', 'CDROMCATZIP', '207556000', 'NikeCajun', '8800CS', 'CSCSTD00385', 'L2PMABGZ7VAZV0PZRI', 'strobe', 'knowlege', 'JH2SC281XPM100187', '1795', '5152940082'} {''}
  WTF?!?!? 16
topic_11
topic_12
  WTF: {'uk', 'controller'} {'cdi', 'sega'}
topic_13
  WTF: {'congress', 'working'} {'stephanopoulos', 'myers'}
topic_14
  WTF: {'new'} {'hotelco'}
topic_15
topic_16
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_17
  WTF: {'festival'} {'ishtar'}
topic_18
topic_19
  WTF: {'table'} {'alice'}
topic_20
  WTF: {'250', 'use'} {'irwin', 'mactools'}
topic_21
  WTF: {'energy', 'balls'} {'dryden', 'shafer'}
topic_22
  WTF: {'university', 'hebrew', 'april', 'oriental', 'dead', 'metaphysical', 'orders', 'equinox', 'golden', 'superior', 'dawn', 'studies'} {'rosae', 'orientis', 'reuss', 'crowley', 'qumran', 'crucis', 'ordo', 'rosicrucian', 'amorc', 'frater', 'oto', 'templi'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_23
  WTF: {'intrinsics'} {'r3'}
topic_24
  WTF: {'writing', 'vol', 'copyright', 'analytic', '02106chopinudeledu', 'manual'} {'vinge', 'dune', 'vernor', 'hogan', 'gibson', 'baen'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_25
topic_26
topic_27
  WTF: {'si', 'socket', 'focus', 'apple', 'able'} {'marvins', 'lciii', 'spigot', 'etherlan', 'pds'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_28
topic_29
topic_30
  WTF: {'tutorial', 'participants', 'engineers', 'conference'} {'mellon', 'japan', 'jstmp', 'carnegie'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_31
  WTF: {'62000', '42839'} {'reids', 'heydt'}
topic_32
  WTF: {'stripped', 'regards'} {'babak', 'sehari'}
topic_33
  WTF: {'plays', 'groundballs', 'goldglover', 'batted', 'clutch', 'studied', 'player'} {'rni', 'baergas', 'slg', 'baerga', 'dps', 'alomars', 'alomar'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_34
  WTF: {'abolished', 'immoral', 'deficit'} {'registries', 'c17', 'admistration'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_35
  WTF: {'nick', '49er', 'mit'} {'sept', 'cambridge', 'quincy'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_36
  WTF: {'gourd', 'netperson', 'equalize', 'capacitive'} {'behnke', 'nat', 'behnkefnalffnalgov', 'pistrix'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_37
  WTF: {'uuencode', 'ioccc'} {'eofnotok', 'xvoid'}
topic_38
  WTF: {'commercially'} {'emi'}
topic_39
  WTF: {'sure', '2020', 'flyback'} {'hifi', 'emerson', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_40
topic_41
  WTF: {'dragdrop', 'recollection', 'Uzi', 'L2PMABGZ7VAZV0PZRI', 'Guideline', 'knowlege', 'JH2SC281XPM100187', '1795', 'toolbox', 'effortsall', 'taxation', 'CDROMCATZIP', '207556000', 'NikeCajun', '8800CS', 'CSCSTD00385', 'strobe', 'monthly', '5152940082'} {''}
  WTF?!?!? 19
topic_42
  WTF: {'headin', 'roam', 'fortyniner', 'excavating', 'predictionsteam', 'melody'} {'dykstra', 'ballad', 'subterranean', 'anime', 'dwelt', 'clementine'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_43
  WTF: {'vending', 'patchmaking', 'remixed', 'patentable'} {'cocacola', 'yerazunis', 'cola', 'pepsi'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_44
  WTF: {'tp', 'mf', 'mj', 'mh', 'm1', 'u0', 'trinomials', 'mm', '644', 'pw', '0n', 'ma'} {'mx', 'm0', 'pnospsxop8f', 'mw', 'm6', 'o3', 'm5', 'm3', 'e8', 'lu', 'm9', 'p6'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_45
  WTF: {'stabilized', 'addition', 'version', 'pads', 'combo'} {'t4', 'salyut', 'russia', 'energiam', 't4centaur'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_46
  WTF: {'promote'} {'fenholt'}
topic_47
  WTF: {'csamiga', 'significant', 'look', 'thank', 'wrongthe'} {'activa', 'v200', 'bitmovie', 'sergio', 'r3d'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_48
  WTF: {'drag'} {'mary'}
topic_49
  WTF: {'commercial', 'integer'} {'macsyma', 'pcdos'}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f30904ac610>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f2d4af1cf40>}
{'perplexity': 51270.2578125, 'coherence_20': 1.7117446406672152, 'toplen_ptw': 1.1502055302442238, 'diversity_euclidean': 0.13637776528047552, 'diversity_jensenshannon': 0.7755256774875854, 'diversity_hellinger': 0.9212687299108452, 'diversity_cosine': 0.9153514950537592, 'fair_ppl_free': 2058.568603515625, 'fair_ppl_fix': 50560.43359375, 'unfair_ppl_banklike': 51270.2578125}
{'num_topics': 51, 'num_common_words': 59415, 'num_model_words': 114951, 'num_bt_words': 97541, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 17, 'lost_bt': 1, 'lost_model': 16}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 20, 'lost_bt': 1, 'lost_model': 19}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}]}
8
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
  WTF: {'vs'} {'nhl'}
topic_3
topic_4
  WTF: {'just'} {'nsa'}
topic_5
topic_6
  WTF: {'dont', 'surrender', 'candida'} {'gordon', 'hiv', 'n3jxp'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_7
topic_8
topic_9
  WTF: {'ps'} {'bj200'}
topic_10
  WTF: {'children', 'started', 'government', 'ottoman', 'muslim', 'saw'} {'armenia', 'azerbaijan', 'sumgait', 'turks', 'armenian', 'armenians'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_11
  WTF: {'just', 'like'} {'caligiuri', 'enviroleague'}
topic_12
  WTF: {'toolbox', 'effortsall', 'dragdrop', 'taxation', 'Epilepsy', '207556000', 'CDROMCATZIP', 'NikeCajun', '8800CS', 'CSCSTD00385', 'L2PMABGZ7VAZV0PZRI', 'knowlege', 'ringleaders', '1795', '5152940082'} {''}
  WTF?!?!? 15
topic_13
  WTF: {'usenet', 'posting'} {'rsa', 'ripem'}
topic_14
  WTF: {'transferable'} {'hotelco'}
topic_15
topic_16
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_17
  WTF: {'testtaking', 'general', 'plasktbdemoncouk', 'jgfootminervacisyaleedu'} {'boulder', 'rex', 'gre', 'ets'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_18
topic_19
  WTF: {'writing', 'vol', 'copyright', 'analytic', '02106chopinudeledu', 'manual'} {'vinge', 'dune', 'vernor', 'petrucci', 'gibson', 'baen'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_20
  WTF: {'tons', 'warhead'} {'dryden', 'shafer'}
topic_21
  WTF: {'sophisticated', 'tools', 'levels', 'management', 'statistical'} {'sei', 'bret', 'thiokol', 'wingert', 'challenger'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_22
  WTF: {'server'} {'r3'}
topic_23
  WTF: {'bookstore', 'wilt', 'interested', 'queer', 'love', 'spinoffs', 'rose', 'books', 'degrees', 'magic', 'study', 'organization', 'groups'} {'rosae', 'orientis', 'kent', 'jose', 'san', 'crucis', 'ordo', 'rosicrucian', 'amorc', 'templars', 'orc', 'oto', 'templi'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_24
  WTF: {'computer'} {'alice'}
topic_25
topic_26
  WTF: {'smears', 'stuff'} {'meguiars', 'glaze'}
topic_27
  WTF: {'hover', 'coradeschi', 'holdings', 'ambassadors', 'tcorapicaarmymil', 'nows', 'proxy', 'theyre', 'blazes', 'bring', 'exactly'} {'maginot', 'bvhis', 'bvi', 'ccrtkba', 'bvbidder', 'goa', 'matson', 'cnnyuppietv', 'cnn', 'biscayne', 'saf'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_28
  WTF: {'english', 'people'} {'bede', 'ishtar'}
topic_29
  WTF: {'russian', 'solve', 'typeset', 'printing', 'mesur', 'famous', 'envoy', 'wild'} {'iosef', 'anania', 'armenia', 'persians', 'orbeli', 'tyukhik', 'armenian', 'shirak'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_30
  WTF: {'aside'} {'darius'}
topic_31
topic_32
  WTF: {'dim', 'type'} {'emi', 'hv'}
topic_33
  WTF: {'know', 'doityourselfers'} {'kirlian', 'krillean'}
topic_34
  WTF: {'eabu288140493210752dialin33635slipntsuciedu', 'nebulised', 'requisition', 'smth', 'petesmtldemoncouk', 'eabu288orionoacuciedu'} {'nottoodistant', 'bridgend', 'militioners', '0656652166', 'hundredths', 'pitily'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_35
  WTF: {'stripped', 'regards'} {'babak', 'sehari'}
topic_36
  WTF: {'nick', '49er', 'mit'} {'sept', 'cambridge', 'quincy'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_37
  WTF: {'list', 'utter', 'military', 'jobs'} {'irs', 'registries', 'c17', 'admistration'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_38
  WTF: {'folks', 'articles', 'rode', 'directors'} {'bmwmoa', 'moa', 'ama', 'mc'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_39
  WTF: {'tutorial', 'participants', 'engineers', 'conference'} {'mellon', 'japan', 'jstmp', 'carnegie'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_40
  WTF: {'april'} {'hicnet'}
topic_41
  WTF: {'george'} {'robbie'}
topic_42
  WTF: {'sending', 'green'} {'null', 'ncsa'}
topic_43
topic_44
  WTF: {'ground', 'glass', 'powers'} {'hifi', 'emerson', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_45
topic_46
  WTF: {'promote'} {'fenholt'}
topic_47
  WTF: {'tp', 'mf', 'mj', 'mh', 'm1', 'u0', 'trinomials', 'mm', '644', 'pw', '0n', 'ma'} {'mx', 'm0', 'pnospsxop8f', 'mw', 'm6', 'o3', 'm5', 'm3', 'e8', 'lu', 'm9', 'p6'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_48
  WTF: {'thoughts', 'combination'} {'neto', 'megatek'}
topic_49
  WTF: {'upgrade'} {'ses'}
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3015e06250>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
  WTF: {'vs'} {'nhl'}
topic_3
topic_4
  WTF: {'just'} {'nsa'}
topic_5
topic_6
  WTF: {'dont', 'surrender', 'candida'} {'gordon', 'hiv', 'n3jxp'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_7
topic_8
topic_9
  WTF: {'ps'} {'bj200'}
topic_10
  WTF: {'children', 'started', 'government', 'ottoman', 'muslim', 'saw'} {'armenia', 'azerbaijan', 'sumgait', 'turks', 'armenian', 'armenians'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_11
  WTF: {'just', 'like'} {'caligiuri', 'enviroleague'}
topic_12
  WTF: {'toolbox', 'effortsall', 'dragdrop', 'taxation', 'Epilepsy', '207556000', 'CDROMCATZIP', 'NikeCajun', '8800CS', 'CSCSTD00385', 'L2PMABGZ7VAZV0PZRI', 'knowlege', 'ringleaders', '1795', '5152940082'} {''}
  WTF?!?!? 15
topic_13
  WTF: {'usenet', 'posting'} {'rsa', 'ripem'}
topic_14
  WTF: {'transferable'} {'hotelco'}
topic_15
topic_16
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_17
  WTF: {'testtaking', 'general', 'plasktbdemoncouk', 'jgfootminervacisyaleedu'} {'boulder', 'rex', 'gre', 'ets'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_18
topic_19
  WTF: {'writing', 'vol', 'copyright', 'analytic', '02106chopinudeledu', 'manual'} {'vinge', 'dune', 'vernor', 'petrucci', 'gibson', 'baen'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_20
  WTF: {'tons', 'warhead'} {'dryden', 'shafer'}
topic_21
  WTF: {'sophisticated', 'tools', 'levels', 'management', 'statistical'} {'sei', 'bret', 'thiokol', 'wingert', 'challenger'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_22
  WTF: {'server'} {'r3'}
topic_23
  WTF: {'bookstore', 'wilt', 'interested', 'queer', 'love', 'spinoffs', 'rose', 'books', 'degrees', 'magic', 'study', 'organization', 'groups'} {'rosae', 'orientis', 'kent', 'jose', 'san', 'crucis', 'ordo', 'rosicrucian', 'amorc', 'templars', 'orc', 'oto', 'templi'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_24
  WTF: {'computer'} {'alice'}
topic_25
topic_26
  WTF: {'smears', 'stuff'} {'meguiars', 'glaze'}
topic_27
  WTF: {'hover', 'coradeschi', 'holdings', 'ambassadors', 'tcorapicaarmymil', 'nows', 'proxy', 'theyre', 'blazes', 'bring', 'exactly'} {'maginot', 'bvhis', 'bvi', 'ccrtkba', 'bvbidder', 'goa', 'matson', 'cnnyuppietv', 'cnn', 'biscayne', 'saf'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_28
  WTF: {'english', 'people'} {'bede', 'ishtar'}
topic_29
  WTF: {'russian', 'solve', 'typeset', 'printing', 'mesur', 'famous', 'envoy', 'wild'} {'iosef', 'anania', 'armenia', 'persians', 'orbeli', 'tyukhik', 'armenian', 'shirak'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_30
  WTF: {'aside'} {'darius'}
topic_31
topic_32
  WTF: {'dim', 'type'} {'emi', 'hv'}
topic_33
  WTF: {'know', 'doityourselfers'} {'kirlian', 'krillean'}
topic_34
  WTF: {'eabu288140493210752dialin33635slipntsuciedu', 'nebulised', 'requisition', 'smth', 'petesmtldemoncouk', 'eabu288orionoacuciedu'} {'nottoodistant', 'bridgend', 'militioners', '0656652166', 'hundredths', 'pitily'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_35
  WTF: {'stripped', 'regards'} {'babak', 'sehari'}
topic_36
  WTF: {'nick', '49er', 'mit'} {'sept', 'cambridge', 'quincy'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_37
  WTF: {'list', 'utter', 'military', 'jobs'} {'irs', 'registries', 'c17', 'admistration'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_38
  WTF: {'folks', 'articles', 'rode', 'directors'} {'bmwmoa', 'moa', 'ama', 'mc'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_39
  WTF: {'tutorial', 'participants', 'engineers', 'conference'} {'mellon', 'japan', 'jstmp', 'carnegie'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_40
  WTF: {'april'} {'hicnet'}
topic_41
  WTF: {'george'} {'robbie'}
topic_42
  WTF: {'sending', 'green'} {'null', 'ncsa'}
topic_43
topic_44
  WTF: {'ground', 'glass', 'powers'} {'hifi', 'emerson', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_45
topic_46
  WTF: {'promote'} {'fenholt'}
topic_47
  WTF: {'tp', 'mf', 'mj', 'mh', 'm1', 'u0', 'trinomials', 'mm', '644', 'pw', '0n', 'ma'} {'mx', 'm0', 'pnospsxop8f', 'mw', 'm6', 'o3', 'm5', 'm3', 'e8', 'lu', 'm9', 'p6'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_48
  WTF: {'thoughts', 'combination'} {'neto', 'megatek'}
topic_49
  WTF: {'upgrade'} {'ses'}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3090b34610>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3073bbd850>}
{'perplexity': 51142.125, 'coherence_20': 1.7346483654125884, 'toplen_ptw': 1.1510212448987471, 'diversity_euclidean': 0.10087447854715544, 'diversity_jensenshannon': 0.7754992249466967, 'diversity_hellinger': 0.9208061356361217, 'diversity_cosine': 0.9125550919033107, 'fair_ppl_free': 2069.33251953125, 'fair_ppl_fix': 50428.0625, 'unfair_ppl_banklike': 51142.125}
{'num_topics': 51, 'num_common_words': 59415, 'num_model_words': 114951, 'num_bt_words': 97541, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 16, 'lost_bt': 1, 'lost_model': 15}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}]}
9
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
  WTF: {'vs'} {'nhl'}
topic_3
topic_4
  WTF: {'know', 'law'} {'stephanopoulos', 'nsa'}
topic_5
  WTF: {'banks', 'surrender', 'candida'} {'gordon', 'hiv', 'n3jxp'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_6
topic_7
topic_8
  WTF: {'discussion', 'news'} {'o157h7', 'anania'}
topic_9
  WTF: {'children', 'started', 'government', 'ottoman', 'muslim', 'saw'} {'armenia', 'azerbaijan', 'sumgait', 'turks', 'armenian', 'armenians'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_10
  WTF: {'driver'} {'bj200'}
topic_11
  WTF: {'influenza'} {'enviroleague'}
topic_12
  WTF: {'toolbox', 'effortsall', 'dragdrop', 'recollection', 'taxation', 'CDROMCATZIP', '207556000', 'NikeDeacon', 'NikeCajun', '8800CS', 'CSCSTD00385', 'L2PMABGZ7VAZV0PZRI', '1795', '5152940082'} {''}
  WTF?!?!? 14
topic_13
topic_14
  WTF: {'case', 'agent', 'texas', 'jury', 'testimony', 'evidence'} {'spence', 'atlantic', 'idaho', 'cooper', 'harris', 'degan'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_15
  WTF: {'nick', 'near', 'parking'} {'aug', 'sept', 'cambridge'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_16
topic_17
topic_18
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_19
topic_20
  WTF: {'chemicals', 'make'} {'dryden', 'shafer'}
topic_21
  WTF: {'explanations', 'writing', 'vol', 'copyright', 'analytic', '02106chopinudeledu'} {'vinge', 'vernor', 'petrucci', 'gibson', 'baen', 'gre'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_22
  WTF: {'intrinsics'} {'r3'}
topic_23
  WTF: {'protection', 'heh'} {'emerson', 'vcr'}
topic_24
  WTF: {'buy', 'handheld', '400', 'scans', 'market'} {'ocr', 'scanman', 'paintbrush', 'mustek', 'ocr104zip'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_25
  WTF: {'folks', 'articles', 'dod', 'directors'} {'bmwmoa', 'yogi', 'ama', 'moa'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_26
  WTF: {'try', 'card'} {'microsofts', 'sb'}
topic_27
  WTF: {'objects', 'charged'} {'kirlian', 'krillean'}
topic_28
topic_29
topic_30
  WTF: {'mail'} {'vip'}
topic_31
  WTF: {'stripped', 'regards'} {'babak', 'sehari'}
topic_32
  WTF: {'aside'} {'darius'}
topic_33
  WTF: {'backand', 'remixed', 'unpatentable', 'gimic', 'patentable'} {'crah', 'yerazunis', 'cola', 'cocacola', 'pepsi'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_34
  WTF: {'commission', 'utter', 'jobs'} {'irs', 'registries', 'admistration'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_35
  WTF: {'rule', 'computer', 'forget'} {'douglas', 'alice', 'adams'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_36
topic_37
  WTF: {'fax', 'computational', 'navy'} {'sigkids', 'siggraph', 'bethesda'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_38
  WTF: {'tuesday', 'mall', 'participants'} {'kenai', 'amc', 'quincy'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_39
  WTF: {'years', 'tradition'} {'joe', 'olympia'}
topic_40
  WTF: {'stabilized', 'addition', 'version', 'pads', 'combo'} {'t4', 'salyut', 'russia', 'energiam', 't4centaur'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_41
  WTF: {'popular', 'flight', 'purchase'} {'hpr', 'tripoli', 'faa'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_42
  WTF: {'minded'} {'robbie'}
topic_43
  WTF: {'heinous', 'discussion', 'stalled'} {'hoovers', 'lyle', 'transarc'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_44
  WTF: {'promote'} {'fenholt'}
topic_45
  WTF: {'tp', 'mf', 'mj', 'mh', 'm1', 'u0', 'trinomials', 'mm', '644', 'pw', '0n', 'ma'} {'mx', 'm0', 'pnospsxop8f', 'mw', 'm6', 'o3', 'm5', 'm3', 'e8', 'lu', 'm9', 'p6'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_46
  WTF: {'licensed', 'product', 'promote', 'science', 'include', 'internet', 'publications'} {'regal', 'robb', 'milwaukee', 'wi', 'marquette', 'dubinski', 'doublemajor'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_47
  WTF: {'nazism', 'inherent', 'dem', 'mr', 'der', 'ya', 'oddly', 'utilize'} {'zeuge', 'timucin', 'davidsson', 'turc', 'davidssons', 'yo', 'koph', 'hoffnung'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_48
topic_49
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f2c9eb449a0>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
  WTF: {'vs'} {'nhl'}
topic_3
topic_4
  WTF: {'know', 'law'} {'stephanopoulos', 'nsa'}
topic_5
  WTF: {'banks', 'surrender', 'candida'} {'gordon', 'hiv', 'n3jxp'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_6
topic_7
topic_8
  WTF: {'discussion', 'news'} {'o157h7', 'anania'}
topic_9
  WTF: {'children', 'started', 'government', 'ottoman', 'muslim', 'saw'} {'armenia', 'azerbaijan', 'sumgait', 'turks', 'armenian', 'armenians'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_10
  WTF: {'driver'} {'bj200'}
topic_11
  WTF: {'influenza'} {'enviroleague'}
topic_12
  WTF: {'toolbox', 'effortsall', 'dragdrop', 'recollection', 'taxation', 'CDROMCATZIP', '207556000', 'NikeDeacon', 'NikeCajun', '8800CS', 'CSCSTD00385', 'L2PMABGZ7VAZV0PZRI', '1795', '5152940082'} {''}
  WTF?!?!? 14
topic_13
topic_14
  WTF: {'case', 'agent', 'texas', 'jury', 'testimony', 'evidence'} {'spence', 'atlantic', 'idaho', 'cooper', 'harris', 'degan'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_15
  WTF: {'nick', 'near', 'parking'} {'aug', 'sept', 'cambridge'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_16
topic_17
topic_18
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_19
topic_20
  WTF: {'chemicals', 'make'} {'dryden', 'shafer'}
topic_21
  WTF: {'explanations', 'writing', 'vol', 'copyright', 'analytic', '02106chopinudeledu'} {'vinge', 'vernor', 'petrucci', 'gibson', 'baen', 'gre'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_22
  WTF: {'intrinsics'} {'r3'}
topic_23
  WTF: {'protection', 'heh'} {'emerson', 'vcr'}
topic_24
  WTF: {'buy', 'handheld', '400', 'scans', 'market'} {'ocr', 'scanman', 'paintbrush', 'mustek', 'ocr104zip'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_25
  WTF: {'folks', 'articles', 'dod', 'directors'} {'bmwmoa', 'yogi', 'ama', 'moa'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_26
  WTF: {'try', 'card'} {'microsofts', 'sb'}
topic_27
  WTF: {'objects', 'charged'} {'kirlian', 'krillean'}
topic_28
topic_29
topic_30
  WTF: {'mail'} {'vip'}
topic_31
  WTF: {'stripped', 'regards'} {'babak', 'sehari'}
topic_32
  WTF: {'aside'} {'darius'}
topic_33
  WTF: {'backand', 'remixed', 'unpatentable', 'gimic', 'patentable'} {'crah', 'yerazunis', 'cola', 'cocacola', 'pepsi'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_34
  WTF: {'commission', 'utter', 'jobs'} {'irs', 'registries', 'admistration'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_35
  WTF: {'rule', 'computer', 'forget'} {'douglas', 'alice', 'adams'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_36
topic_37
  WTF: {'fax', 'computational', 'navy'} {'sigkids', 'siggraph', 'bethesda'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_38
  WTF: {'tuesday', 'mall', 'participants'} {'kenai', 'amc', 'quincy'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_39
  WTF: {'years', 'tradition'} {'joe', 'olympia'}
topic_40
  WTF: {'stabilized', 'addition', 'version', 'pads', 'combo'} {'t4', 'salyut', 'russia', 'energiam', 't4centaur'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_41
  WTF: {'popular', 'flight', 'purchase'} {'hpr', 'tripoli', 'faa'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_42
  WTF: {'minded'} {'robbie'}
topic_43
  WTF: {'heinous', 'discussion', 'stalled'} {'hoovers', 'lyle', 'transarc'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_44
  WTF: {'promote'} {'fenholt'}
topic_45
  WTF: {'tp', 'mf', 'mj', 'mh', 'm1', 'u0', 'trinomials', 'mm', '644', 'pw', '0n', 'ma'} {'mx', 'm0', 'pnospsxop8f', 'mw', 'm6', 'o3', 'm5', 'm3', 'e8', 'lu', 'm9', 'p6'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_46
  WTF: {'licensed', 'product', 'promote', 'science', 'include', 'internet', 'publications'} {'regal', 'robb', 'milwaukee', 'wi', 'marquette', 'dubinski', 'doublemajor'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_47
  WTF: {'nazism', 'inherent', 'dem', 'mr', 'der', 'ya', 'oddly', 'utilize'} {'zeuge', 'timucin', 'davidsson', 'turc', 'davidssons', 'yo', 'koph', 'hoffnung'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_48
topic_49

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f30b0598490>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f2fc7ff8d30>}
{'perplexity': 51008.06640625, 'coherence_20': 1.8461436004918788, 'toplen_ptw': 1.150803387293137, 'diversity_euclidean': 0.10523552851569604, 'diversity_jensenshannon': 0.776993445605684, 'diversity_hellinger': 0.9226526038550703, 'diversity_cosine': 0.9161325853477598, 'fair_ppl_free': 2070.12890625, 'fair_ppl_fix': 50525.12890625, 'unfair_ppl_banklike': 51008.06640625}
{'num_topics': 51, 'num_common_words': 59415, 'num_model_words': 114951, 'num_bt_words': 97541, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 15, 'lost_bt': 1, 'lost_model': 14}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}]}
10
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
topic_3
  WTF: {'vs'} {'nhl'}
topic_4
  WTF: {'just'} {'nsa'}
topic_5
  WTF: {'banks', 'dont', 'research'} {'gordon', 'hiv', 'n3jxp'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_6
topic_7
topic_8
  WTF: {'land'} {'stephanopoulos'}
topic_9
  WTF: {'children', 'package', 'work'} {'stephanopoulos', 'myers', 'fbi'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_10
  WTF: {'news'} {'o157h7'}
topic_11
  WTF: {'children', 'started', 'government', 'ottoman', 'muslim', 'saw'} {'armenia', 'azerbaijan', 'sumgait', 'turks', 'armenian', 'armenians'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_12
  WTF: {'driver'} {'bj200'}
topic_13
  WTF: {'just', 'partners'} {'caligiuri', 'enviroleague'}
topic_14
  WTF: {'toolbox', 'effortsall', 'dragdrop', 'recollection', 'taxation', 'CDROMCATZIP', '207556000', 'NikeCajun', '8800CS', 'CSCSTD00385', 'L2PMABGZ7VAZV0PZRI', 'Guideline', 'divvied', '1795', '5152940082'} {''}
  WTF?!?!? 15
topic_15
topic_16
  WTF: {'interested', 'email'} {'snes', 'sega'}
topic_17
  WTF: {'email', 'posting'} {'rsa', 'ripem'}
topic_18
topic_19
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_20
topic_21
topic_22
  WTF: {'email', 'writing', 'vol', 'copyright', 'analytic', '02106chopinudeledu'} {'vinge', 'vernor', 'petrucci', 'hogan', 'gibson', 'baen'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_23
  WTF: {'university', 'congress', 'hebrew', 'april', 'oriental', 'metaphysical', 'orders', 'equinox', 'golden', 'superior', 'dawn', 'studies'} {'orientis', 'rosae', 'reuss', 'crowley', 'qumran', 'crucis', 'ordo', 'rosicrucian', 'amorc', 'frater', 'oto', 'templi'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_24
  WTF: {'trillion'} {'alice'}
topic_25
  WTF: {'intrinsics'} {'r3'}
topic_26
  WTF: {'400', 'grayscales', 'handheld', 'buy', 'scans', 'market'} {'ocr', 'dexxa', 'scanman', 'paintbrush', 'mustek', 'ocr104zip'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_27
topic_28
  WTF: {'programming', 'students', 'cs', 'andrew'} {'mellon', 'japan', 'jstmp', 'carnegie'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_29
  WTF: {'russian', 'solve', 'typeset', 'printing', 'mesur', 'famous', 'envoy', 'wild'} {'iosef', 'anania', 'armenia', 'persians', 'orbeli', 'tyukhik', 'armenian', 'shirak'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_30
  WTF: {'english', 'spring', 'people'} {'bede', 'pesach', 'ishtar'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_31
topic_32
  WTF: {'stripped', 'regards'} {'babak', 'sehari'}
topic_33
  WTF: {'aside'} {'darius'}
topic_34
  WTF: {'objects', 'charged'} {'kirlian', 'krillean'}
topic_35
  WTF: {'pork', 'abolished', 'immoral', 'bases'} {'registries', 'c5s', 'c17', 'admistration'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_36
topic_37
  WTF: {'teh'} {'mary'}
topic_38
  WTF: {'lowvoltage'} {'emi'}
topic_39
  WTF: {'dragdrop', 'recollection', 'Uzi', 'L2PMABGZ7VAZV0PZRI', 'Guideline', 'knowlege', 'JH2SC281XPM100187', '1795', 'toolbox', 'effortsall', 'taxation', 'CDROMCATZIP', '207556000', 'NikeCajun', '8800CS', 'CSCSTD00385', 'strobe', 'monthly', '5152940082'} {''}
  WTF?!?!? 19
topic_40
  WTF: {'need', 'environments', 'gui', 'downloaded'} {'evets', 'rewerb', 'bonn', 'brewer'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_41
  WTF: {'uuencode', 'ioccc'} {'eofnotok', 'xvoid'}
topic_42
  WTF: {'stabilized', 'addition', 'version', 'pads', 'combo'} {'t4', 'salyut', 'russia', 'energiam', 't4centaur'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_43
  WTF: {'played'} {'fenholt'}
topic_44
  WTF: {'tp', 'mf', 'mj', 'mh', 'm1', 'u0', 'trinomials', 'mm', '644', 'pw', '0n', 'ma'} {'mx', 'm0', 'pnospsxop8f', 'mw', 'm6', 'o3', 'm5', 'm3', 'e8', 'lu', 'm9', 'p6'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_45
  WTF: {'audio', 'problem', 'returned'} {'hifi', 'emerson', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_46
  WTF: {'csamiga', 'licensees', 'bullshitting', '300'} {'pong', '3do', 'sergio', 'r3d'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_47
  WTF: {'dont', 'memorable', 'hes', 'lyrics', 'changing', 'trench'} {'yankess', 'dykstra', 'ballad', 'homesick', 'subterranean', 'anime'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_48
  WTF: {'reprogramming', 'hobbyist', 'preproduction', 'products', 'erasure', 'surethats', 'types'} {'neuronr', 'hc711', 'motorolas', 'mc143120', 'hc705k1', 'snvt', 'mc143150'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_49
  WTF: {'cozy', 'salvage', 'mosques', 'exemption', 'rules', 'doublespeak', 'essays', 'punishments'} {'barfling', 'hymies', 'harikari', 'ragheads', 'followingup', 'commandeer', 'kkkaldis', 'israelists'}
  WTF?!?!? 8
  WTF?!?!? 8
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f2d5782cf10>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
topic_3
  WTF: {'vs'} {'nhl'}
topic_4
  WTF: {'just'} {'nsa'}
topic_5
  WTF: {'banks', 'dont', 'research'} {'gordon', 'hiv', 'n3jxp'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_6
topic_7
topic_8
  WTF: {'land'} {'stephanopoulos'}
topic_9
  WTF: {'children', 'package', 'work'} {'stephanopoulos', 'myers', 'fbi'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_10
  WTF: {'news'} {'o157h7'}
topic_11
  WTF: {'children', 'started', 'government', 'ottoman', 'muslim', 'saw'} {'armenia', 'azerbaijan', 'sumgait', 'turks', 'armenian', 'armenians'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_12
  WTF: {'driver'} {'bj200'}
topic_13
  WTF: {'just', 'partners'} {'caligiuri', 'enviroleague'}
topic_14
  WTF: {'toolbox', 'effortsall', 'dragdrop', 'recollection', 'taxation', 'CDROMCATZIP', '207556000', 'NikeCajun', '8800CS', 'CSCSTD00385', 'L2PMABGZ7VAZV0PZRI', 'Guideline', 'divvied', '1795', '5152940082'} {''}
  WTF?!?!? 15
topic_15
topic_16
  WTF: {'interested', 'email'} {'snes', 'sega'}
topic_17
  WTF: {'email', 'posting'} {'rsa', 'ripem'}
topic_18
topic_19
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_20
topic_21
topic_22
  WTF: {'email', 'writing', 'vol', 'copyright', 'analytic', '02106chopinudeledu'} {'vinge', 'vernor', 'petrucci', 'hogan', 'gibson', 'baen'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_23
  WTF: {'university', 'congress', 'hebrew', 'april', 'oriental', 'metaphysical', 'orders', 'equinox', 'golden', 'superior', 'dawn', 'studies'} {'orientis', 'rosae', 'reuss', 'crowley', 'qumran', 'crucis', 'ordo', 'rosicrucian', 'amorc', 'frater', 'oto', 'templi'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_24
  WTF: {'trillion'} {'alice'}
topic_25
  WTF: {'intrinsics'} {'r3'}
topic_26
  WTF: {'400', 'grayscales', 'handheld', 'buy', 'scans', 'market'} {'ocr', 'dexxa', 'scanman', 'paintbrush', 'mustek', 'ocr104zip'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_27
topic_28
  WTF: {'programming', 'students', 'cs', 'andrew'} {'mellon', 'japan', 'jstmp', 'carnegie'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_29
  WTF: {'russian', 'solve', 'typeset', 'printing', 'mesur', 'famous', 'envoy', 'wild'} {'iosef', 'anania', 'armenia', 'persians', 'orbeli', 'tyukhik', 'armenian', 'shirak'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_30
  WTF: {'english', 'spring', 'people'} {'bede', 'pesach', 'ishtar'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_31
topic_32
  WTF: {'stripped', 'regards'} {'babak', 'sehari'}
topic_33
  WTF: {'aside'} {'darius'}
topic_34
  WTF: {'objects', 'charged'} {'kirlian', 'krillean'}
topic_35
  WTF: {'pork', 'abolished', 'immoral', 'bases'} {'registries', 'c5s', 'c17', 'admistration'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_36
topic_37
  WTF: {'teh'} {'mary'}
topic_38
  WTF: {'lowvoltage'} {'emi'}
topic_39
  WTF: {'dragdrop', 'recollection', 'Uzi', 'L2PMABGZ7VAZV0PZRI', 'Guideline', 'knowlege', 'JH2SC281XPM100187', '1795', 'toolbox', 'effortsall', 'taxation', 'CDROMCATZIP', '207556000', 'NikeCajun', '8800CS', 'CSCSTD00385', 'strobe', 'monthly', '5152940082'} {''}
  WTF?!?!? 19
topic_40
  WTF: {'need', 'environments', 'gui', 'downloaded'} {'evets', 'rewerb', 'bonn', 'brewer'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_41
  WTF: {'uuencode', 'ioccc'} {'eofnotok', 'xvoid'}
topic_42
  WTF: {'stabilized', 'addition', 'version', 'pads', 'combo'} {'t4', 'salyut', 'russia', 'energiam', 't4centaur'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_43
  WTF: {'played'} {'fenholt'}
topic_44
  WTF: {'tp', 'mf', 'mj', 'mh', 'm1', 'u0', 'trinomials', 'mm', '644', 'pw', '0n', 'ma'} {'mx', 'm0', 'pnospsxop8f', 'mw', 'm6', 'o3', 'm5', 'm3', 'e8', 'lu', 'm9', 'p6'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_45
  WTF: {'audio', 'problem', 'returned'} {'hifi', 'emerson', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_46
  WTF: {'csamiga', 'licensees', 'bullshitting', '300'} {'pong', '3do', 'sergio', 'r3d'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_47
  WTF: {'dont', 'memorable', 'hes', 'lyrics', 'changing', 'trench'} {'yankess', 'dykstra', 'ballad', 'homesick', 'subterranean', 'anime'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_48
  WTF: {'reprogramming', 'hobbyist', 'preproduction', 'products', 'erasure', 'surethats', 'types'} {'neuronr', 'hc711', 'motorolas', 'mc143120', 'hc705k1', 'snvt', 'mc143150'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_49
  WTF: {'cozy', 'salvage', 'mosques', 'exemption', 'rules', 'doublespeak', 'essays', 'punishments'} {'barfling', 'hymies', 'harikari', 'ragheads', 'followingup', 'commandeer', 'kkkaldis', 'israelists'}
  WTF?!?!? 8
  WTF?!?!? 8

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f2d376a87c0>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3015de4970>}
{'perplexity': 50123.54296875, 'coherence_20': 1.8315779963302445, 'toplen_ptw': 1.1690547329090804, 'diversity_euclidean': 0.13331861669962583, 'diversity_jensenshannon': 0.7696382208119087, 'diversity_hellinger': 0.9130321970722772, 'diversity_cosine': 0.9065731308116947, 'fair_ppl_free': 2011.5960693359375, 'fair_ppl_fix': 49555.4375, 'unfair_ppl_banklike': 50123.54296875}
{'num_topics': 51, 'num_common_words': 59415, 'num_model_words': 114951, 'num_bt_words': 97541, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 16, 'lost_bt': 1, 'lost_model': 15}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 20, 'lost_bt': 1, 'lost_model': 19}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}]}
11
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
topic_3
  WTF: {'make'} {'stephanopoulos'}
topic_4
  WTF: {'vs'} {'nhl'}
topic_5
topic_6
  WTF: {'dont', 'surrender', 'candida'} {'gordon', 'hiv', 'n3jxp'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_7
topic_8
  WTF: {'crime'} {'cooper'}
topic_9
  WTF: {'discussion'} {'o157h7'}
topic_10
  WTF: {'children', 'started', 'government', 'ottoman', 'muslim', 'saw'} {'armenia', 'azerbaijan', 'sumgait', 'turks', 'armenian', 'armenians'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_11
  WTF: {'im'} {'bj200'}
topic_12
  WTF: {'toolbox', 'effortsall', 'dragdrop', 'recollection', 'taxation', 'CDROMCATZIP', '207556000', 'haunt', 'NikeCajun', '8800CS', 'CSCSTD00385', 'L2PMABGZ7VAZV0PZRI', '1795', '5152940082'} {''}
  WTF?!?!? 14
topic_13
topic_14
  WTF: {'mail'} {'ripem'}
topic_15
  WTF: {'transferable'} {'hotelco'}
topic_16
topic_17
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_18
topic_19
  WTF: {'testtaking', '19851986', 'j3davidstudentbusinessuwoca', '19891990'} {'boulder', 'rex', 'gre', 'ets'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_20
topic_21
  WTF: {'writing', 'vol', 'copyright', 'analytic', '02106chopinudeledu', 'manual'} {'vinge', 'vernor', 'petrucci', 'hogan', 'gibson', 'baen'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_22
  WTF: {'university', 'hebrew', 'april', 'oriental', 'dead', 'metaphysical', 'orders', 'equinox', 'golden', 'superior', 'dawn', 'studies'} {'orientis', 'rosae', 'reuss', 'crowley', 'qumran', 'crucis', 'ordo', 'rosicrucian', 'amorc', 'frater', 'oto', 'templi'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_23
  WTF: {'hm', 'bugs', 'levels', 'nasa', 'grows'} {'sei', 'bret', 'mcwilliams', 'wingert', 'challenger'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_24
  WTF: {'intrinsics'} {'r3'}
topic_25
  WTF: {'thanks', 'properties', 'particular', 'grayscales', 'market'} {'ocr', 'dexxa', 'scanman', 'paintbrush', 'mustek'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_26
topic_27
  WTF: {'russian', 'solve', 'typeset', 'printing', 'mesur', 'famous', 'envoy', 'wild'} {'iosef', 'anania', 'armenia', 'persians', 'orbeli', 'tyukhik', 'armenian', 'shirak'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_28
topic_29
topic_30
  WTF: {'use'} {'heydt'}
topic_31
topic_32
  WTF: {'stripped', 'regards'} {'babak', 'sehari'}
topic_33
  WTF: {'stuff', 'waxed'} {'mcquires', 'glaze'}
topic_34
  WTF: {'aside'} {'darius'}
topic_35
  WTF: {'systems', 'facilities', 'inventions', 'launch', 'version'} {'t4', 'salyut', 'russia', 'energiam', 't4centaur'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_36
  WTF: {'pork', 'abolished', 'immoral', 'bases'} {'registries', 'c5s', 'c17', 'admistration'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_37
  WTF: {'nick', '49er', 'mit'} {'sept', 'cambridge', 'quincy'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_38
  WTF: {'know', 'doityourselfers'} {'kirlian', 'krillean'}
topic_39
  WTF: {'theory'} {'alice'}
topic_40
  WTF: {'teh'} {'mary'}
topic_41
  WTF: {'audio', 'problem', 'returned'} {'hifi', 'emerson', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_42
  WTF: {'tp', 'mf', 'mj', 'mh', 'm1', 'u0', 'trinomials', 'mm', '644', 'pw', '0n', 'ma'} {'mx', 'm0', 'pnospsxop8f', 'mw', 'm6', 'o3', 'm5', 'm3', 'e8', 'lu', 'm9', 'p6'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_43
  WTF: {'mach'} {'ses'}
topic_44
  WTF: {'transliterated', 'reseacher', 'fiansovamcom', '6144594256', 'kutuzovavenusitebserpukhovsu'} {'ussrsu', 'belorusskaya', 'iki', 'moscow', 'kremlin'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_45
  WTF: {'promote'} {'fenholt'}
topic_46
  WTF: {'120mph'} {'lubbock'}
topic_47
  WTF: {'revenue', 'washington'} {'cato', 'catos'}
topic_48
  WTF: {'university', 'incribed', 'mr', 'wish', 'mistyped', 'science', 'include'} {'regal', 'robb', 'milwaukee', 'wi', 'marquette', 'dubinski', 'doublemajor'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_49
  WTF: {'telex', 'unload', 'simplicitys', 'laserdisc', 'abyss', 'raylauffastrotempleedu', 'received'} {'zeitgeist', 'h2y', 'cbsfox', 'nobles', 'lauff', 'filmtransmtl', '1c8'}
  WTF?!?!? 7
  WTF?!?!? 7
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f2be0cfa2b0>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
topic_3
  WTF: {'make'} {'stephanopoulos'}
topic_4
  WTF: {'vs'} {'nhl'}
topic_5
topic_6
  WTF: {'dont', 'surrender', 'candida'} {'gordon', 'hiv', 'n3jxp'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_7
topic_8
  WTF: {'crime'} {'cooper'}
topic_9
  WTF: {'discussion'} {'o157h7'}
topic_10
  WTF: {'children', 'started', 'government', 'ottoman', 'muslim', 'saw'} {'armenia', 'azerbaijan', 'sumgait', 'turks', 'armenian', 'armenians'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_11
  WTF: {'im'} {'bj200'}
topic_12
  WTF: {'toolbox', 'effortsall', 'dragdrop', 'recollection', 'taxation', 'CDROMCATZIP', '207556000', 'haunt', 'NikeCajun', '8800CS', 'CSCSTD00385', 'L2PMABGZ7VAZV0PZRI', '1795', '5152940082'} {''}
  WTF?!?!? 14
topic_13
topic_14
  WTF: {'mail'} {'ripem'}
topic_15
  WTF: {'transferable'} {'hotelco'}
topic_16
topic_17
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_18
topic_19
  WTF: {'testtaking', '19851986', 'j3davidstudentbusinessuwoca', '19891990'} {'boulder', 'rex', 'gre', 'ets'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_20
topic_21
  WTF: {'writing', 'vol', 'copyright', 'analytic', '02106chopinudeledu', 'manual'} {'vinge', 'vernor', 'petrucci', 'hogan', 'gibson', 'baen'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_22
  WTF: {'university', 'hebrew', 'april', 'oriental', 'dead', 'metaphysical', 'orders', 'equinox', 'golden', 'superior', 'dawn', 'studies'} {'orientis', 'rosae', 'reuss', 'crowley', 'qumran', 'crucis', 'ordo', 'rosicrucian', 'amorc', 'frater', 'oto', 'templi'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_23
  WTF: {'hm', 'bugs', 'levels', 'nasa', 'grows'} {'sei', 'bret', 'mcwilliams', 'wingert', 'challenger'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_24
  WTF: {'intrinsics'} {'r3'}
topic_25
  WTF: {'thanks', 'properties', 'particular', 'grayscales', 'market'} {'ocr', 'dexxa', 'scanman', 'paintbrush', 'mustek'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_26
topic_27
  WTF: {'russian', 'solve', 'typeset', 'printing', 'mesur', 'famous', 'envoy', 'wild'} {'iosef', 'anania', 'armenia', 'persians', 'orbeli', 'tyukhik', 'armenian', 'shirak'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_28
topic_29
topic_30
  WTF: {'use'} {'heydt'}
topic_31
topic_32
  WTF: {'stripped', 'regards'} {'babak', 'sehari'}
topic_33
  WTF: {'stuff', 'waxed'} {'mcquires', 'glaze'}
topic_34
  WTF: {'aside'} {'darius'}
topic_35
  WTF: {'systems', 'facilities', 'inventions', 'launch', 'version'} {'t4', 'salyut', 'russia', 'energiam', 't4centaur'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_36
  WTF: {'pork', 'abolished', 'immoral', 'bases'} {'registries', 'c5s', 'c17', 'admistration'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_37
  WTF: {'nick', '49er', 'mit'} {'sept', 'cambridge', 'quincy'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_38
  WTF: {'know', 'doityourselfers'} {'kirlian', 'krillean'}
topic_39
  WTF: {'theory'} {'alice'}
topic_40
  WTF: {'teh'} {'mary'}
topic_41
  WTF: {'audio', 'problem', 'returned'} {'hifi', 'emerson', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_42
  WTF: {'tp', 'mf', 'mj', 'mh', 'm1', 'u0', 'trinomials', 'mm', '644', 'pw', '0n', 'ma'} {'mx', 'm0', 'pnospsxop8f', 'mw', 'm6', 'o3', 'm5', 'm3', 'e8', 'lu', 'm9', 'p6'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_43
  WTF: {'mach'} {'ses'}
topic_44
  WTF: {'transliterated', 'reseacher', 'fiansovamcom', '6144594256', 'kutuzovavenusitebserpukhovsu'} {'ussrsu', 'belorusskaya', 'iki', 'moscow', 'kremlin'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_45
  WTF: {'promote'} {'fenholt'}
topic_46
  WTF: {'120mph'} {'lubbock'}
topic_47
  WTF: {'revenue', 'washington'} {'cato', 'catos'}
topic_48
  WTF: {'university', 'incribed', 'mr', 'wish', 'mistyped', 'science', 'include'} {'regal', 'robb', 'milwaukee', 'wi', 'marquette', 'dubinski', 'doublemajor'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_49
  WTF: {'telex', 'unload', 'simplicitys', 'laserdisc', 'abyss', 'raylauffastrotempleedu', 'received'} {'zeitgeist', 'h2y', 'cbsfox', 'nobles', 'lauff', 'filmtransmtl', '1c8'}
  WTF?!?!? 7
  WTF?!?!? 7

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f2d2362f3a0>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f2d2363a0d0>}
{'perplexity': 51954.96484375, 'coherence_20': 1.763172038711789, 'toplen_ptw': 1.1516509334199339, 'diversity_euclidean': 0.10216692057604905, 'diversity_jensenshannon': 0.7752454610644334, 'diversity_hellinger': 0.920089705994194, 'diversity_cosine': 0.9118006021270234, 'fair_ppl_free': 2037.6807861328125, 'fair_ppl_fix': 51338.78515625, 'unfair_ppl_banklike': 51954.96484375}
{'num_topics': 51, 'num_common_words': 59415, 'num_model_words': 114951, 'num_bt_words': 97541, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 15, 'lost_bt': 1, 'lost_model': 14}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}]}
12
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
topic_3
  WTF: {'vs'} {'nhl'}
topic_4
topic_5
  WTF: {'dont', 'surrender', 'candida'} {'gordon', 'hiv', 'n3jxp'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_6
topic_7
  WTF: {'discussion'} {'o157h7'}
topic_8
topic_9
  WTF: {'children', 'started', 'government', 'ottoman', 'muslim', 'saw'} {'armenia', 'azerbaijan', 'sumgait', 'turks', 'armenian', 'armenians'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_10
  WTF: {'driver'} {'bj200'}
topic_11
  WTF: {'dragdrop', 'L2PMABGZ7VAZV0PZRI', 'Guideline', 'knowlege', 'ringleaders', 'JH2SC281XPM100187', '1795', 'toolbox', 'effortsall', 'taxation', '207556000', 'CDROMCATZIP', 'NikeCajun', '8800CS', 'CSCSTD00385', 'monthly', '5152940082'} {''}
  WTF?!?!? 17
topic_12
  WTF: {'email', 'posting'} {'rsa', 'ripem'}
topic_13
  WTF: {'technology', 'management'} {'vinge', 'gre'}
topic_14
topic_15
  WTF: {'available'} {'hotelco'}
topic_16
  WTF: {'built'} {'cato'}
topic_17
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_18
topic_19
  WTF: {'accident'} {'supra'}
topic_20
topic_21
topic_22
  WTF: {'sensor', '16ea'} {'irwin', 'mactools'}
topic_23
  WTF: {'properties', 'particular', 'grayscales', 'resoltuion', 'market'} {'ocr', 'scanman', 'paintbrush', 'mustek', 'ocr104zip'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_24
  WTF: {'video', 'heh'} {'emerson', 'vcr'}
topic_25
  WTF: {'english', 'sunday', 'spring'} {'bede', 'pesach', 'ishtar'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_26
topic_27
  WTF: {'aside'} {'darius'}
topic_28
  WTF: {'russian', 'solve', 'typeset', 'printing', 'mesur', 'famous', 'envoy', 'wild'} {'iosef', 'anania', 'armenia', 'persians', 'orbeli', 'tyukhik', 'armenian', 'shirak'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_29
  WTF: {'pork', 'abolished', 'immoral', 'bases'} {'registries', 'c5s', 'c17', 'admistration'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_30
  WTF: {'stripped', 'regards'} {'babak', 'sehari'}
topic_31
  WTF: {'tuesday', 'mall', 'participants'} {'kenai', 'amc', 'quincy'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_32
  WTF: {'theory'} {'alice'}
topic_33
  WTF: {'whipping', 'columbia', 'bc', 'campus', 'punks', 'latchkey', 'fred', 'followups'} {'bach', '2a3', 'v6t', 'ubc', 'meson', 'wesbrook', 'triuniversity', 'triumf'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_34
  WTF: {'hiden'} {'scotyy'}
topic_35
  WTF: {'culture', 'student', 'laundromat', 'womenandrewcmuedu'} {'nozyk', 'shul', 'gainesville', 'palace'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_36
  WTF: {'uunetkc2wzbob', 'backand', '07090', 'vending', 'unpatentable', 'patentable'} {'crah', 'yerazunis', 'cola', 'billson', 'cocacola', 'pepsi'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_37
topic_38
  WTF: {'uuencode', 'ioccc'} {'eofnotok', 'xvoid'}
topic_39
  WTF: {'stabilized', 'addition', 'version', 'pads', 'combo'} {'t4', 'salyut', 'russia', 'energiam', 't4centaur'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_40
  WTF: {'promote'} {'fenholt'}
topic_41
  WTF: {'licensed', 'product', 'promote', 'science', 'include', 'internet', 'publications'} {'regal', 'robb', 'milwaukee', 'wi', 'marquette', 'dubinski', 'doublemajor'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_42
  WTF: {'tp', 'mf', 'mj', 'mh', 'm1', 'u0', 'trinomials', 'mm', '644', 'pw', '0n', 'ma'} {'mx', 'm0', 'pnospsxop8f', 'mw', 'm6', 'o3', 'm5', 'm3', 'e8', 'lu', 'm9', 'p6'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_43
  WTF: {'software', 'informations', 'ive', 'wrongthe', 'imaginerequestemailspparamaxcom', 'licensees', 'allright'} {'ipas', 'activa', '3do', 'riccione', 'bitmovie', 'sergio', 'r3d'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_44
  WTF: {'racers', 'rebel', '90s', 'rednecks', 'soar', '8177', 'giveaway'} {'yogis', 'yogi', 'pgh', 'thumper', 'smokey', 'mcqueen', 'bandit'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_45
topic_46
  WTF: {'heinous', 'throats', 'radicals'} {'hoovers', 'lyle', 'transarc'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_47
  WTF: {'asshole', 'oil'} {'bakker', 'cambodia'}
topic_48
  WTF: {'2042', '2273618', 'pace', '2275753', 'lipmanoasysdtnavymil'} {'sigkids', 'navyrelated', 'siggraph', 'lipman', 'bethesda'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_49
  WTF: {'themey', 'concensus', 'addition'} {'bridgend', 'faires', 'mattell'}
  WTF?!?!? 3
  WTF?!?!? 3
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f2df2b42e20>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
topic_3
  WTF: {'vs'} {'nhl'}
topic_4
topic_5
  WTF: {'dont', 'surrender', 'candida'} {'gordon', 'hiv', 'n3jxp'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_6
topic_7
  WTF: {'discussion'} {'o157h7'}
topic_8
topic_9
  WTF: {'children', 'started', 'government', 'ottoman', 'muslim', 'saw'} {'armenia', 'azerbaijan', 'sumgait', 'turks', 'armenian', 'armenians'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_10
  WTF: {'driver'} {'bj200'}
topic_11
  WTF: {'dragdrop', 'L2PMABGZ7VAZV0PZRI', 'Guideline', 'knowlege', 'ringleaders', 'JH2SC281XPM100187', '1795', 'toolbox', 'effortsall', 'taxation', '207556000', 'CDROMCATZIP', 'NikeCajun', '8800CS', 'CSCSTD00385', 'monthly', '5152940082'} {''}
  WTF?!?!? 17
topic_12
  WTF: {'email', 'posting'} {'rsa', 'ripem'}
topic_13
  WTF: {'technology', 'management'} {'vinge', 'gre'}
topic_14
topic_15
  WTF: {'available'} {'hotelco'}
topic_16
  WTF: {'built'} {'cato'}
topic_17
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_18
topic_19
  WTF: {'accident'} {'supra'}
topic_20
topic_21
topic_22
  WTF: {'sensor', '16ea'} {'irwin', 'mactools'}
topic_23
  WTF: {'properties', 'particular', 'grayscales', 'resoltuion', 'market'} {'ocr', 'scanman', 'paintbrush', 'mustek', 'ocr104zip'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_24
  WTF: {'video', 'heh'} {'emerson', 'vcr'}
topic_25
  WTF: {'english', 'sunday', 'spring'} {'bede', 'pesach', 'ishtar'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_26
topic_27
  WTF: {'aside'} {'darius'}
topic_28
  WTF: {'russian', 'solve', 'typeset', 'printing', 'mesur', 'famous', 'envoy', 'wild'} {'iosef', 'anania', 'armenia', 'persians', 'orbeli', 'tyukhik', 'armenian', 'shirak'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_29
  WTF: {'pork', 'abolished', 'immoral', 'bases'} {'registries', 'c5s', 'c17', 'admistration'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_30
  WTF: {'stripped', 'regards'} {'babak', 'sehari'}
topic_31
  WTF: {'tuesday', 'mall', 'participants'} {'kenai', 'amc', 'quincy'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_32
  WTF: {'theory'} {'alice'}
topic_33
  WTF: {'whipping', 'columbia', 'bc', 'campus', 'punks', 'latchkey', 'fred', 'followups'} {'bach', '2a3', 'v6t', 'ubc', 'meson', 'wesbrook', 'triuniversity', 'triumf'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_34
  WTF: {'hiden'} {'scotyy'}
topic_35
  WTF: {'culture', 'student', 'laundromat', 'womenandrewcmuedu'} {'nozyk', 'shul', 'gainesville', 'palace'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_36
  WTF: {'uunetkc2wzbob', 'backand', '07090', 'vending', 'unpatentable', 'patentable'} {'crah', 'yerazunis', 'cola', 'billson', 'cocacola', 'pepsi'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_37
topic_38
  WTF: {'uuencode', 'ioccc'} {'eofnotok', 'xvoid'}
topic_39
  WTF: {'stabilized', 'addition', 'version', 'pads', 'combo'} {'t4', 'salyut', 'russia', 'energiam', 't4centaur'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_40
  WTF: {'promote'} {'fenholt'}
topic_41
  WTF: {'licensed', 'product', 'promote', 'science', 'include', 'internet', 'publications'} {'regal', 'robb', 'milwaukee', 'wi', 'marquette', 'dubinski', 'doublemajor'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_42
  WTF: {'tp', 'mf', 'mj', 'mh', 'm1', 'u0', 'trinomials', 'mm', '644', 'pw', '0n', 'ma'} {'mx', 'm0', 'pnospsxop8f', 'mw', 'm6', 'o3', 'm5', 'm3', 'e8', 'lu', 'm9', 'p6'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_43
  WTF: {'software', 'informations', 'ive', 'wrongthe', 'imaginerequestemailspparamaxcom', 'licensees', 'allright'} {'ipas', 'activa', '3do', 'riccione', 'bitmovie', 'sergio', 'r3d'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_44
  WTF: {'racers', 'rebel', '90s', 'rednecks', 'soar', '8177', 'giveaway'} {'yogis', 'yogi', 'pgh', 'thumper', 'smokey', 'mcqueen', 'bandit'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_45
topic_46
  WTF: {'heinous', 'throats', 'radicals'} {'hoovers', 'lyle', 'transarc'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_47
  WTF: {'asshole', 'oil'} {'bakker', 'cambodia'}
topic_48
  WTF: {'2042', '2273618', 'pace', '2275753', 'lipmanoasysdtnavymil'} {'sigkids', 'navyrelated', 'siggraph', 'lipman', 'bethesda'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_49
  WTF: {'themey', 'concensus', 'addition'} {'bridgend', 'faires', 'mattell'}
  WTF?!?!? 3
  WTF?!?!? 3

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f2d376a81c0>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3015de4d30>}
{'perplexity': 50738.1953125, 'coherence_20': 1.7510864040431553, 'toplen_ptw': 1.1570245852352803, 'diversity_euclidean': 0.10585434305893363, 'diversity_jensenshannon': 0.7767316371169658, 'diversity_hellinger': 0.9222932736685101, 'diversity_cosine': 0.9120563963587613, 'fair_ppl_free': 2058.753173828125, 'fair_ppl_fix': 50247.55078125, 'unfair_ppl_banklike': 50738.1953125}
{'num_topics': 51, 'num_common_words': 59415, 'num_model_words': 114951, 'num_bt_words': 97541, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 18, 'lost_bt': 1, 'lost_model': 17}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}]}
13
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
  WTF: {'vs'} {'nhl'}
topic_3
topic_4
  WTF: {'just', 'algorithm'} {'stephanopoulos', 'nsa'}
topic_5
  WTF: {'government'} {'fbi'}
topic_6
  WTF: {'dont', 'surrender', 'candida'} {'gordon', 'hiv', 'n3jxp'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_7
topic_8
  WTF: {'thanks'} {'o157h7'}
topic_9
  WTF: {'children', 'started', 'government', 'ottoman', 'muslim', 'saw'} {'armenia', 'azerbaijan', 'sumgait', 'turks', 'armenian', 'armenians'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_10
  WTF: {'scanner'} {'bj200'}
topic_11
  WTF: {'like', 'sin'} {'caligiuri', 'enviroleague'}
topic_12
  WTF: {'toolbox', 'effortsall', 'dragdrop', 'recollection', 'taxation', 'CDROMCATZIP', '207556000', 'NikeDeacon', 'NikeCajun', '8800CS', 'CSCSTD00385', 'L2PMABGZ7VAZV0PZRI', '1795', '5152940082'} {''}
  WTF?!?!? 14
topic_13
topic_14
  WTF: {'email', 'posting'} {'rsa', 'ripem'}
topic_15
  WTF: {'driving'} {'caltrans'}
topic_16
  WTF: {'sale'} {'hotelco'}
topic_17
topic_18
topic_19
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_20
  WTF: {'festival'} {'ishtar'}
topic_21
topic_22
  WTF: {'fuel'} {'cato'}
topic_23
  WTF: {'writing', 'vol', 'copyright', 'analytic', '02106chopinudeledu', 'manual'} {'vinge', 'vernor', 'petrucci', 'hogan', 'gibson', 'baen'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_24
  WTF: {'different'} {'clayton'}
topic_25
  WTF: {'intrinsics'} {'r3'}
topic_26
topic_27
  WTF: {'objects', 'charged'} {'kirlian', 'krillean'}
topic_28
  WTF: {'dim'} {'emi'}
topic_29
  WTF: {'stripped', 'regards'} {'babak', 'sehari'}
topic_30
  WTF: {'russian', 'solve', 'typeset', 'printing', 'mesur', 'famous', 'envoy', 'wild'} {'iosef', 'anania', 'armenia', 'persians', 'orbeli', 'tyukhik', 'armenian', 'shirak'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_31
  WTF: {'pork', 'abolished', 'immoral', 'bases'} {'registries', 'c5s', 'c17', 'admistration'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_32
  WTF: {'nick', '49er', 'car'} {'sept', 'cambridge', 'quincy'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_33
  WTF: {'folks', 'articles', 'rode', 'directors'} {'bmwmoa', 'moa', 'ama', 'mc'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_34
topic_35
  WTF: {'launches', 'launch', 'class', 'sodium'} {'hpr', 'tripoli', 'ssrt', 'faa'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_36
  WTF: {'theory'} {'alice'}
topic_37
  WTF: {'screen', 'trick', 'switcher'} {'supercharging', 'robbinsgreat', 'judd'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_38
  WTF: {'uuencode', 'ioccc'} {'eofnotok', 'xvoid'}
topic_39
  WTF: {'2275753', '2042', '2273618', 'pace'} {'sigkids', 'siggraph', 'lipman', 'bethesda'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_40
  WTF: {'racers', 'rebel', '90s', 'rednecks', 'soar', 'stoned', 'giveaway'} {'yogis', 'yogi', 'pgh', 'thumper', 'smokey', 'mcqueen', 'bandit'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_41
  WTF: {'audio', 'problem', 'returned'} {'hifi', 'emerson', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_42
  WTF: {'stabilized', 'addition', 'version', 'pads', 'combo'} {'t4', 'salyut', 'russia', 'energiam', 't4centaur'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_43
  WTF: {'preciated', 't2', 'letterbox', 'simplicitys', 'rmers', 'raylauffastrotempleedu', 'received'} {'nasm', 'zeitgeist', 'cbsfox', 'lauff', 'csundh30ursacalvinedu', 'filmtransmtl', '1c8'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_44
  WTF: {'120mph', 'deleted', 'commuter'} {'lubbock', 'houston', 'dallas'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_45
  WTF: {'290000', 'facts', 'article', '010101', 'karrcscornelledu', 'bad'} {'barnstaple', 'wales', 'coterill', 'karr', 'roberts', 'england'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_46
  WTF: {'promote'} {'fenholt'}
topic_47
  WTF: {'tp', 'mf', 'mj', 'mh', 'm1', 'u0', 'trinomials', 'mm', '644', 'pw', '0n', 'ma'} {'mx', 'm0', 'pnospsxop8f', 'mw', 'm6', 'o3', 'm5', 'm3', 'e8', 'lu', 'm9', 'p6'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_48
  WTF: {'accessno', 'choking', 'netxt'} {'17500', 'hermesmeritedu', 'vax'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_49
  WTF: {'port', 'break', '8051', 'define', 'register', 'include', 'leds'} {'uartdata', 'sta', 'mvi', 'uartcmd', 'lda', 'porta', 'equ'}
  WTF?!?!? 7
  WTF?!?!? 7
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f2c922abc70>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
  WTF: {'vs'} {'nhl'}
topic_3
topic_4
  WTF: {'just', 'algorithm'} {'stephanopoulos', 'nsa'}
topic_5
  WTF: {'government'} {'fbi'}
topic_6
  WTF: {'dont', 'surrender', 'candida'} {'gordon', 'hiv', 'n3jxp'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_7
topic_8
  WTF: {'thanks'} {'o157h7'}
topic_9
  WTF: {'children', 'started', 'government', 'ottoman', 'muslim', 'saw'} {'armenia', 'azerbaijan', 'sumgait', 'turks', 'armenian', 'armenians'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_10
  WTF: {'scanner'} {'bj200'}
topic_11
  WTF: {'like', 'sin'} {'caligiuri', 'enviroleague'}
topic_12
  WTF: {'toolbox', 'effortsall', 'dragdrop', 'recollection', 'taxation', 'CDROMCATZIP', '207556000', 'NikeDeacon', 'NikeCajun', '8800CS', 'CSCSTD00385', 'L2PMABGZ7VAZV0PZRI', '1795', '5152940082'} {''}
  WTF?!?!? 14
topic_13
topic_14
  WTF: {'email', 'posting'} {'rsa', 'ripem'}
topic_15
  WTF: {'driving'} {'caltrans'}
topic_16
  WTF: {'sale'} {'hotelco'}
topic_17
topic_18
topic_19
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_20
  WTF: {'festival'} {'ishtar'}
topic_21
topic_22
  WTF: {'fuel'} {'cato'}
topic_23
  WTF: {'writing', 'vol', 'copyright', 'analytic', '02106chopinudeledu', 'manual'} {'vinge', 'vernor', 'petrucci', 'hogan', 'gibson', 'baen'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_24
  WTF: {'different'} {'clayton'}
topic_25
  WTF: {'intrinsics'} {'r3'}
topic_26
topic_27
  WTF: {'objects', 'charged'} {'kirlian', 'krillean'}
topic_28
  WTF: {'dim'} {'emi'}
topic_29
  WTF: {'stripped', 'regards'} {'babak', 'sehari'}
topic_30
  WTF: {'russian', 'solve', 'typeset', 'printing', 'mesur', 'famous', 'envoy', 'wild'} {'iosef', 'anania', 'armenia', 'persians', 'orbeli', 'tyukhik', 'armenian', 'shirak'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_31
  WTF: {'pork', 'abolished', 'immoral', 'bases'} {'registries', 'c5s', 'c17', 'admistration'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_32
  WTF: {'nick', '49er', 'car'} {'sept', 'cambridge', 'quincy'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_33
  WTF: {'folks', 'articles', 'rode', 'directors'} {'bmwmoa', 'moa', 'ama', 'mc'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_34
topic_35
  WTF: {'launches', 'launch', 'class', 'sodium'} {'hpr', 'tripoli', 'ssrt', 'faa'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_36
  WTF: {'theory'} {'alice'}
topic_37
  WTF: {'screen', 'trick', 'switcher'} {'supercharging', 'robbinsgreat', 'judd'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_38
  WTF: {'uuencode', 'ioccc'} {'eofnotok', 'xvoid'}
topic_39
  WTF: {'2275753', '2042', '2273618', 'pace'} {'sigkids', 'siggraph', 'lipman', 'bethesda'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_40
  WTF: {'racers', 'rebel', '90s', 'rednecks', 'soar', 'stoned', 'giveaway'} {'yogis', 'yogi', 'pgh', 'thumper', 'smokey', 'mcqueen', 'bandit'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_41
  WTF: {'audio', 'problem', 'returned'} {'hifi', 'emerson', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_42
  WTF: {'stabilized', 'addition', 'version', 'pads', 'combo'} {'t4', 'salyut', 'russia', 'energiam', 't4centaur'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_43
  WTF: {'preciated', 't2', 'letterbox', 'simplicitys', 'rmers', 'raylauffastrotempleedu', 'received'} {'nasm', 'zeitgeist', 'cbsfox', 'lauff', 'csundh30ursacalvinedu', 'filmtransmtl', '1c8'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_44
  WTF: {'120mph', 'deleted', 'commuter'} {'lubbock', 'houston', 'dallas'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_45
  WTF: {'290000', 'facts', 'article', '010101', 'karrcscornelledu', 'bad'} {'barnstaple', 'wales', 'coterill', 'karr', 'roberts', 'england'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_46
  WTF: {'promote'} {'fenholt'}
topic_47
  WTF: {'tp', 'mf', 'mj', 'mh', 'm1', 'u0', 'trinomials', 'mm', '644', 'pw', '0n', 'ma'} {'mx', 'm0', 'pnospsxop8f', 'mw', 'm6', 'o3', 'm5', 'm3', 'e8', 'lu', 'm9', 'p6'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_48
  WTF: {'accessno', 'choking', 'netxt'} {'17500', 'hermesmeritedu', 'vax'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_49
  WTF: {'port', 'break', '8051', 'define', 'register', 'include', 'leds'} {'uartdata', 'sta', 'mvi', 'uartcmd', 'lda', 'porta', 'equ'}
  WTF?!?!? 7
  WTF?!?!? 7

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f2b6f8036a0>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f2d2f797cd0>}
{'perplexity': 50005.89453125, 'coherence_20': 1.8700102752034873, 'toplen_ptw': 1.1594341018199912, 'diversity_euclidean': 0.09733881838341198, 'diversity_jensenshannon': 0.7713295308717837, 'diversity_hellinger': 0.9153408466393869, 'diversity_cosine': 0.9083818544541636, 'fair_ppl_free': 2028.7783203125, 'fair_ppl_fix': 49477.6171875, 'unfair_ppl_banklike': 50005.89453125}
{'num_topics': 51, 'num_common_words': 59415, 'num_model_words': 114951, 'num_bt_words': 97541, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 15, 'lost_bt': 1, 'lost_model': 14}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}]}
14
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
  WTF: {'vs'} {'nhl'}
topic_3
topic_4
  WTF: {'banks', 'surrender', 'candida'} {'gordon', 'hiv', 'n3jxp'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_5
topic_6
  WTF: {'posting'} {'o157h7'}
topic_7
  WTF: {'children', 'started', 'government', 'ottoman', 'muslim', 'saw'} {'armenia', 'azerbaijan', 'sumgait', 'turks', 'armenian', 'armenians'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_8
  WTF: {'quality'} {'bj200'}
topic_9
  WTF: {'like', 'sin'} {'caligiuri', 'enviroleague'}
topic_10
  WTF: {'toolbox', 'effortsall', 'dragdrop', 'taxation', 'Epilepsy', '207556000', 'CDROMCATZIP', 'NikeCajun', '8800CS', 'CSCSTD00385', 'L2PMABGZ7VAZV0PZRI', 'knowlege', 'ringleaders', '1795', '5152940082'} {''}
  WTF?!?!? 15
topic_11
topic_12
  WTF: {'football', 'adventure', '35'} {'snes', 'cdi', 'sega'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_13
  WTF: {'email', 'posting'} {'rsa', 'ripem'}
topic_14
  WTF: {'cars'} {'caltrans'}
topic_15
  WTF: {'transferable'} {'hotelco'}
topic_16
topic_17
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_18
  WTF: {'testtaking', 'general', 'plasktbdemoncouk', 'j3davidstudentbusinessuwoca'} {'boulder', 'rex', 'gre', 'ets'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_19
topic_20
  WTF: {'bomb', 'things', 'insisting', 'filtration'} {'barre', 'auth', 'epa', 'cato'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_21
topic_22
  WTF: {'email', 'writing', 'vol', 'copyright', 'analytic', '02106chopinudeledu'} {'vinge', 'dune', 'vernor', 'petrucci', 'gibson', 'baen'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_23
  WTF: {'250', 'use'} {'irwin', 'mactools'}
topic_24
  WTF: {'intrinsics'} {'r3'}
topic_25
  WTF: {'bookstore', 'scroll', 'april', 'books', 'orders', 'exhibition', 'studies'} {'rosae', 'qumran', 'crucis', 'ordo', 'rosicrucian', 'amorc', 'oto'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_26
  WTF: {'try', 'card'} {'microsofts', 'sb'}
topic_27
  WTF: {'russian', 'solve', 'typeset', 'printing', 'mesur', 'famous', 'envoy', 'wild'} {'iosef', 'anania', 'armenia', 'persians', 'orbeli', 'tyukhik', 'armenian', 'shirak'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_28
  WTF: {'english', 'people'} {'bede', 'ishtar'}
topic_29
topic_30
topic_31
  WTF: {'know', 'doityourselfers'} {'kirlian', 'krillean'}
topic_32
  WTF: {'aside'} {'darius'}
topic_33
topic_34
  WTF: {'dim', 'type'} {'emi', 'hv'}
topic_35
  WTF: {'stripped', 'regards'} {'babak', 'sehari'}
topic_36
  WTF: {'tutorial', 'participants', 'engineers', 'conference'} {'mellon', 'japan', 'jstmp', 'carnegie'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_37
  WTF: {'nick', '49er', 'mit'} {'sept', 'cambridge', 'quincy'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_38
  WTF: {'nive', '6192214511', 'outputing', 'ftpinformatikunioldenburgdepubdkbtraceutils', '6192212527', 'raytrace'} {'ply16386', 'povshell', 'psadobe20', 'perth', 'vvfont18zip', 'versatec'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_39
  WTF: {'number', 'rule', 'computer'} {'douglas', 'alice', 'adams'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_40
  WTF: {'commission', 'utter', 'axe'} {'irs', 'registries', 'admistration'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_41
  WTF: {'postings', 'wit', 'contractors'} {'baghdad', 'mea', 'bnr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_42
  WTF: {'genetic', 'fax', 'computational'} {'sigkids', 'siggraph', 'bethesda'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_43
  WTF: {'tp', 'mf', 'mj', 'mh', 'm1', 'u0', 'trinomials', 'mm', '644', 'pw', '0n', 'ma'} {'mx', 'm0', 'pnospsxop8f', 'mw', 'm6', 'o3', 'm5', 'm3', 'e8', 'lu', 'm9', 'p6'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_44
  WTF: {'audio', 'problem', 'returned'} {'hifi', 'emerson', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_45
  WTF: {'stabilized', 'addition', 'version', 'pads', 'combo'} {'t4', 'salyut', 'russia', 'energiam', 't4centaur'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_46
  WTF: {'uuencode', 'ioccc'} {'eofnotok', 'xvoid'}
topic_47
  WTF: {'promote'} {'fenholt'}
topic_48
  WTF: {'memorable', 'hes', 'roam', 'somethin', 'changing', 'trench'} {'yankess', 'dykstra', 'ballad', 'homesick', 'subterranean', 'anime'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_49
  WTF: {'leave', 'suspicions'} {'menuts', 'avagadros'}
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f2d4af1cd60>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
  WTF: {'vs'} {'nhl'}
topic_3
topic_4
  WTF: {'banks', 'surrender', 'candida'} {'gordon', 'hiv', 'n3jxp'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_5
topic_6
  WTF: {'posting'} {'o157h7'}
topic_7
  WTF: {'children', 'started', 'government', 'ottoman', 'muslim', 'saw'} {'armenia', 'azerbaijan', 'sumgait', 'turks', 'armenian', 'armenians'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_8
  WTF: {'quality'} {'bj200'}
topic_9
  WTF: {'like', 'sin'} {'caligiuri', 'enviroleague'}
topic_10
  WTF: {'toolbox', 'effortsall', 'dragdrop', 'taxation', 'Epilepsy', '207556000', 'CDROMCATZIP', 'NikeCajun', '8800CS', 'CSCSTD00385', 'L2PMABGZ7VAZV0PZRI', 'knowlege', 'ringleaders', '1795', '5152940082'} {''}
  WTF?!?!? 15
topic_11
topic_12
  WTF: {'football', 'adventure', '35'} {'snes', 'cdi', 'sega'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_13
  WTF: {'email', 'posting'} {'rsa', 'ripem'}
topic_14
  WTF: {'cars'} {'caltrans'}
topic_15
  WTF: {'transferable'} {'hotelco'}
topic_16
topic_17
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_18
  WTF: {'testtaking', 'general', 'plasktbdemoncouk', 'j3davidstudentbusinessuwoca'} {'boulder', 'rex', 'gre', 'ets'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_19
topic_20
  WTF: {'bomb', 'things', 'insisting', 'filtration'} {'barre', 'auth', 'epa', 'cato'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_21
topic_22
  WTF: {'email', 'writing', 'vol', 'copyright', 'analytic', '02106chopinudeledu'} {'vinge', 'dune', 'vernor', 'petrucci', 'gibson', 'baen'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_23
  WTF: {'250', 'use'} {'irwin', 'mactools'}
topic_24
  WTF: {'intrinsics'} {'r3'}
topic_25
  WTF: {'bookstore', 'scroll', 'april', 'books', 'orders', 'exhibition', 'studies'} {'rosae', 'qumran', 'crucis', 'ordo', 'rosicrucian', 'amorc', 'oto'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_26
  WTF: {'try', 'card'} {'microsofts', 'sb'}
topic_27
  WTF: {'russian', 'solve', 'typeset', 'printing', 'mesur', 'famous', 'envoy', 'wild'} {'iosef', 'anania', 'armenia', 'persians', 'orbeli', 'tyukhik', 'armenian', 'shirak'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_28
  WTF: {'english', 'people'} {'bede', 'ishtar'}
topic_29
topic_30
topic_31
  WTF: {'know', 'doityourselfers'} {'kirlian', 'krillean'}
topic_32
  WTF: {'aside'} {'darius'}
topic_33
topic_34
  WTF: {'dim', 'type'} {'emi', 'hv'}
topic_35
  WTF: {'stripped', 'regards'} {'babak', 'sehari'}
topic_36
  WTF: {'tutorial', 'participants', 'engineers', 'conference'} {'mellon', 'japan', 'jstmp', 'carnegie'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_37
  WTF: {'nick', '49er', 'mit'} {'sept', 'cambridge', 'quincy'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_38
  WTF: {'nive', '6192214511', 'outputing', 'ftpinformatikunioldenburgdepubdkbtraceutils', '6192212527', 'raytrace'} {'ply16386', 'povshell', 'psadobe20', 'perth', 'vvfont18zip', 'versatec'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_39
  WTF: {'number', 'rule', 'computer'} {'douglas', 'alice', 'adams'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_40
  WTF: {'commission', 'utter', 'axe'} {'irs', 'registries', 'admistration'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_41
  WTF: {'postings', 'wit', 'contractors'} {'baghdad', 'mea', 'bnr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_42
  WTF: {'genetic', 'fax', 'computational'} {'sigkids', 'siggraph', 'bethesda'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_43
  WTF: {'tp', 'mf', 'mj', 'mh', 'm1', 'u0', 'trinomials', 'mm', '644', 'pw', '0n', 'ma'} {'mx', 'm0', 'pnospsxop8f', 'mw', 'm6', 'o3', 'm5', 'm3', 'e8', 'lu', 'm9', 'p6'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_44
  WTF: {'audio', 'problem', 'returned'} {'hifi', 'emerson', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_45
  WTF: {'stabilized', 'addition', 'version', 'pads', 'combo'} {'t4', 'salyut', 'russia', 'energiam', 't4centaur'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_46
  WTF: {'uuencode', 'ioccc'} {'eofnotok', 'xvoid'}
topic_47
  WTF: {'promote'} {'fenholt'}
topic_48
  WTF: {'memorable', 'hes', 'roam', 'somethin', 'changing', 'trench'} {'yankess', 'dykstra', 'ballad', 'homesick', 'subterranean', 'anime'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_49
  WTF: {'leave', 'suspicions'} {'menuts', 'avagadros'}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3015eb36a0>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f2d5782c940>}
{'perplexity': 54154.77734375, 'coherence_20': 1.873774859919966, 'toplen_ptw': 1.1488641912483195, 'diversity_euclidean': 0.10040875707475971, 'diversity_jensenshannon': 0.7740074522239611, 'diversity_hellinger': 0.9194568372081103, 'diversity_cosine': 0.9159794318488914, 'fair_ppl_free': 2078.692626953125, 'fair_ppl_fix': 53432.05859375, 'unfair_ppl_banklike': 54154.77734375}
{'num_topics': 51, 'num_common_words': 59415, 'num_model_words': 114951, 'num_bt_words': 97541, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 16, 'lost_bt': 1, 'lost_model': 15}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}]}
15
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
  WTF: {'like'} {'stephanopoulos'}
topic_3
  WTF: {'vs'} {'nhl'}
topic_4
topic_5
  WTF: {'dont', 'surrender', 'candida'} {'gordon', 'hiv', 'n3jxp'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_6
topic_7
  WTF: {'news'} {'o157h7'}
topic_8
topic_9
  WTF: {'children', 'started', 'government', 'ottoman', 'muslim', 'saw'} {'armenia', 'azerbaijan', 'sumgait', 'turks', 'armenian', 'armenians'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_10
  WTF: {'driver'} {'bj200'}
topic_11
  WTF: {'toolbox', 'effortsall', 'dragdrop', 'taxation', 'Epilepsy', '207556000', 'CDROMCATZIP', 'NikeCajun', '8800CS', 'CSCSTD00385', 'L2PMABGZ7VAZV0PZRI', 'knowlege', 'ringleaders', '1795', '5152940082'} {''}
  WTF?!?!? 15
topic_12
  WTF: {'mail'} {'ripem'}
topic_13
topic_14
  WTF: {'living'} {'hotelco'}
topic_15
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_16
topic_17
topic_18
  WTF: {'porsche'} {'supra'}
topic_19
  WTF: {'writing', 'vol', 'copyright', 'analytic', '02106chopinudeledu', 'manual'} {'vinge', 'dune', 'vernor', 'hogan', 'gibson', 'baen'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_20
  WTF: {'250', 'use'} {'irwin', 'mactools'}
topic_21
  WTF: {'ray', 'motif'} {'r3', 'rsi'}
topic_22
  WTF: {'thanks', 'properties', 'particular', 'grayscales', 'market'} {'ocr', 'dexxa', 'scanman', 'paintbrush', 'mustek'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_23
  WTF: {'try', 'card'} {'microsofts', 'sb'}
topic_24
topic_25
  WTF: {'fourdcom', '6174940565'} {'reids', '1493'}
topic_26
topic_27
topic_28
  WTF: {'aside'} {'darius'}
topic_29
  WTF: {'tutorial', 'participants', 'engineers', 'conference'} {'mellon', 'japan', 'jstmp', 'carnegie'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_30
  WTF: {'trillion', 'forget', 'bang'} {'douglas', 'alice', 'adams'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_31
  WTF: {'stripped', 'regards'} {'babak', 'sehari'}
topic_32
  WTF: {'folks', 'articles', 'rode', 'directors'} {'bmwmoa', 'moa', 'ama', 'mc'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_33
  WTF: {'list', 'utter', 'military', 'jobs'} {'irs', 'registries', 'c17', 'admistration'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_34
  WTF: {'dim', 'type'} {'emi', 'hv'}
topic_35
  WTF: {'know', 'doityourselfers'} {'kirlian', 'krillean'}
topic_36
  WTF: {'worse', 'germany', 'dangerous'} {'femine', 'calverts', 'fatti'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_37
  WTF: {'genetic', 'fax', 'computational'} {'sigkids', 'siggraph', 'bethesda'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_38
  WTF: {'sound', 'horizontal', 'glass'} {'hifi', 'emerson', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_39
  WTF: {'orthogonal', 'sets', 'faster', 'cpu', 'clock'} {'cisc', 'vlsi', 'vax', 'risc', 'uvax'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_40
  WTF: {'backand', '0099', 'vending', 'patentable'} {'cocacola', 'unpatentable', 'cola', 'pepsi'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_41
  WTF: {'years', 'tradition'} {'joe', 'olympia'}
topic_42
  WTF: {'stabilized', 'addition', 'version', 'pads', 'combo'} {'t4', 'salyut', 'russia', 'energiam', 't4centaur'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_43
  WTF: {'correct', 'trick', 'screen'} {'supercharging', 'robbinsgreat', 'judd'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_44
  WTF: {'deluded', 'nicht', 'alle', 'lunacy', 'pinks', 'st', '881', 'guy'} {'zeuge', 'thedoge', 'turc', 'dobbsapproved', 'conspiratortm', 'koph', 'condupes', 'hoffnung'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_45
  WTF: {'promote'} {'fenholt'}
topic_46
  WTF: {'tp', 'mf', 'mj', 'mh', 'm1', 'u0', 'trinomials', 'mm', '644', 'pw', '0n', 'ma'} {'mx', 'm0', 'pnospsxop8f', 'mw', 'm6', 'o3', 'm5', 'm3', 'e8', 'lu', 'm9', 'p6'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_47
  WTF: {'way', 'nick', 'law', 'bars', 'leg', 'strings'} {'barnstaple', 'wales', 'coterill', 'karr', 'roberts', 'england'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_48
  WTF: {'ccs', 'mcguirecsutexasedu'} {'edgetacalculator', 'bridgend'}
topic_49
  WTF: {'orchestra', '17yearolds'} {'dahmer', 'theresa'}
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f2b72997520>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
  WTF: {'like'} {'stephanopoulos'}
topic_3
  WTF: {'vs'} {'nhl'}
topic_4
topic_5
  WTF: {'dont', 'surrender', 'candida'} {'gordon', 'hiv', 'n3jxp'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_6
topic_7
  WTF: {'news'} {'o157h7'}
topic_8
topic_9
  WTF: {'children', 'started', 'government', 'ottoman', 'muslim', 'saw'} {'armenia', 'azerbaijan', 'sumgait', 'turks', 'armenian', 'armenians'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_10
  WTF: {'driver'} {'bj200'}
topic_11
  WTF: {'toolbox', 'effortsall', 'dragdrop', 'taxation', 'Epilepsy', '207556000', 'CDROMCATZIP', 'NikeCajun', '8800CS', 'CSCSTD00385', 'L2PMABGZ7VAZV0PZRI', 'knowlege', 'ringleaders', '1795', '5152940082'} {''}
  WTF?!?!? 15
topic_12
  WTF: {'mail'} {'ripem'}
topic_13
topic_14
  WTF: {'living'} {'hotelco'}
topic_15
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_16
topic_17
topic_18
  WTF: {'porsche'} {'supra'}
topic_19
  WTF: {'writing', 'vol', 'copyright', 'analytic', '02106chopinudeledu', 'manual'} {'vinge', 'dune', 'vernor', 'hogan', 'gibson', 'baen'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_20
  WTF: {'250', 'use'} {'irwin', 'mactools'}
topic_21
  WTF: {'ray', 'motif'} {'r3', 'rsi'}
topic_22
  WTF: {'thanks', 'properties', 'particular', 'grayscales', 'market'} {'ocr', 'dexxa', 'scanman', 'paintbrush', 'mustek'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_23
  WTF: {'try', 'card'} {'microsofts', 'sb'}
topic_24
topic_25
  WTF: {'fourdcom', '6174940565'} {'reids', '1493'}
topic_26
topic_27
topic_28
  WTF: {'aside'} {'darius'}
topic_29
  WTF: {'tutorial', 'participants', 'engineers', 'conference'} {'mellon', 'japan', 'jstmp', 'carnegie'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_30
  WTF: {'trillion', 'forget', 'bang'} {'douglas', 'alice', 'adams'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_31
  WTF: {'stripped', 'regards'} {'babak', 'sehari'}
topic_32
  WTF: {'folks', 'articles', 'rode', 'directors'} {'bmwmoa', 'moa', 'ama', 'mc'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_33
  WTF: {'list', 'utter', 'military', 'jobs'} {'irs', 'registries', 'c17', 'admistration'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_34
  WTF: {'dim', 'type'} {'emi', 'hv'}
topic_35
  WTF: {'know', 'doityourselfers'} {'kirlian', 'krillean'}
topic_36
  WTF: {'worse', 'germany', 'dangerous'} {'femine', 'calverts', 'fatti'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_37
  WTF: {'genetic', 'fax', 'computational'} {'sigkids', 'siggraph', 'bethesda'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_38
  WTF: {'sound', 'horizontal', 'glass'} {'hifi', 'emerson', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_39
  WTF: {'orthogonal', 'sets', 'faster', 'cpu', 'clock'} {'cisc', 'vlsi', 'vax', 'risc', 'uvax'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_40
  WTF: {'backand', '0099', 'vending', 'patentable'} {'cocacola', 'unpatentable', 'cola', 'pepsi'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_41
  WTF: {'years', 'tradition'} {'joe', 'olympia'}
topic_42
  WTF: {'stabilized', 'addition', 'version', 'pads', 'combo'} {'t4', 'salyut', 'russia', 'energiam', 't4centaur'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_43
  WTF: {'correct', 'trick', 'screen'} {'supercharging', 'robbinsgreat', 'judd'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_44
  WTF: {'deluded', 'nicht', 'alle', 'lunacy', 'pinks', 'st', '881', 'guy'} {'zeuge', 'thedoge', 'turc', 'dobbsapproved', 'conspiratortm', 'koph', 'condupes', 'hoffnung'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_45
  WTF: {'promote'} {'fenholt'}
topic_46
  WTF: {'tp', 'mf', 'mj', 'mh', 'm1', 'u0', 'trinomials', 'mm', '644', 'pw', '0n', 'ma'} {'mx', 'm0', 'pnospsxop8f', 'mw', 'm6', 'o3', 'm5', 'm3', 'e8', 'lu', 'm9', 'p6'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_47
  WTF: {'way', 'nick', 'law', 'bars', 'leg', 'strings'} {'barnstaple', 'wales', 'coterill', 'karr', 'roberts', 'england'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_48
  WTF: {'ccs', 'mcguirecsutexasedu'} {'edgetacalculator', 'bridgend'}
topic_49
  WTF: {'orchestra', '17yearolds'} {'dahmer', 'theresa'}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f2fc7ff8970>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f2d74feeee0>}
{'perplexity': 51077.30859375, 'coherence_20': 1.8468556546800055, 'toplen_ptw': 1.1511601607352644, 'diversity_euclidean': 0.10906698705889456, 'diversity_jensenshannon': 0.7793512991991165, 'diversity_hellinger': 0.9258398150096976, 'diversity_cosine': 0.919998080360862, 'fair_ppl_free': 2070.597900390625, 'fair_ppl_fix': 50503.265625, 'unfair_ppl_banklike': 51077.30859375}
{'num_topics': 51, 'num_common_words': 59415, 'num_model_words': 114951, 'num_bt_words': 97541, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 16, 'lost_bt': 1, 'lost_model': 15}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}]}
16
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
topic_3
  WTF: {'vs'} {'nhl'}
topic_4
topic_5
  WTF: {'dont', 'surrender', 'candida'} {'gordon', 'hiv', 'n3jxp'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_6
topic_7
  WTF: {'news', 'book'} {'o157h7', 'anania'}
topic_8
  WTF: {'children', 'started', 'government', 'ottoman', 'muslim', 'saw'} {'armenia', 'azerbaijan', 'sumgait', 'turks', 'armenian', 'armenians'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_9
  WTF: {'quality'} {'bj200'}
topic_10
  WTF: {'toolbox', 'effortsall', 'dragdrop', 'recollection', 'taxation', 'CDROMCATZIP', '207556000', 'NikeDeacon', 'NikeCajun', '8800CS', 'CSCSTD00385', 'L2PMABGZ7VAZV0PZRI', '1795', '5152940082'} {''}
  WTF?!?!? 14
topic_11
topic_12
  WTF: {'football', 'adventure', '35'} {'snes', 'cdi', 'sega'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_13
topic_14
  WTF: {'declutch'} {'caltrans'}
topic_15
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_16
topic_17
topic_18
  WTF: {'chemicals', 'insisting'} {'cato', 'shafer'}
topic_19
  WTF: {'hotels'} {'hotelco'}
topic_20
  WTF: {'writing', 'vol', 'copyright', 'analytic', '02106chopinudeledu', 'manual'} {'vinge', 'dune', 'vernor', 'petrucci', 'gibson', 'baen'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_21
topic_22
  WTF: {'difference', 'pay', 'people'} {'vip', 'heydt', 'moody'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_23
  WTF: {'hotel', 'use'} {'tuscon', 'bahamas'}
topic_24
  WTF: {'server'} {'r3'}
topic_25
topic_26
  WTF: {'requisition', 'centigrade', 'hundredths', 'eabu288orionoacuciedu'} {'nottoodistant', 'bridgend', 'asthmatics', 'avagadros'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_27
  WTF: {'know', 'doityourselfers'} {'kirlian', 'krillean'}
topic_28
topic_29
  WTF: {'bookstore', 'wilt', 'members', 'words', 'love', 'invoke', 'law', 'magic', 'restriction', 'organization', 'superior', 'groups', 'oriental'} {'orientis', 'rosae', 'reuss', 'crowley', 'lewis', 'crucis', 'ordo', 'rosicrucian', 'amorc', 'frater', 'oto', 'templi', 'masonic'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_30
  WTF: {'stripped', 'regards'} {'babak', 'sehari'}
topic_31
  WTF: {'nick', '49er', 'mit'} {'sept', 'cambridge', 'quincy'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_32
  WTF: {'list', 'utter', 'military', 'jobs'} {'irs', 'registries', 'c17', 'admistration'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_33
topic_34
  WTF: {'bending', 'm4', 'tunnel', 'height'} {'m5', 'm3', 'mw', 'rsi'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_35
  WTF: {'theory'} {'alice'}
topic_36
  WTF: {'worse', 'germany', 'dangerous'} {'femine', 'calverts', 'fatti'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_37
  WTF: {'hardware', 'internet', 'left'} {'null', 'localtalk', 'munich'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_38
  WTF: {'uuencode', 'ioccc'} {'eofnotok', 'xvoid'}
topic_39
  WTF: {'vending', 'patchmaking', 'remixed', 'patentable'} {'cocacola', 'yerazunis', 'cola', 'pepsi'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_40
  WTF: {'memorable', 'hes', 'somethin', 'changing', 'trench'} {'yankess', 'dykstra', 'ballad', 'subterranean', 'anime'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_41
  WTF: {'mach'} {'ses'}
topic_42
  WTF: {'dleungeeubcca', '128196128234', 'hermesmeritedu', 'dkmillerunixgubcca', 'horrendously'} {'tocserve', 'pradhaanrebelsb', 'sivesh', 'ncsa', 'sprintnet'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_43
  WTF: {'stabilized', 'addition', 'version', 'pads', 'combo'} {'t4', 'salyut', 'russia', 'energiam', 't4centaur'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_44
  WTF: {'correct', 'trick', 'screen'} {'supercharging', 'robbinsgreat', 'judd'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_45
  WTF: {'ground', 'glass', 'powers'} {'hifi', 'emerson', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_46
  WTF: {'promote'} {'fenholt'}
topic_47
  WTF: {'circuitry', 'carrier'} {'100mhz', 'ecl'}
topic_48
  WTF: {'nazism', 'hell', 'dem', 'mr', 'ya', 'moments', 'oddly', 'utilize'} {'zeuge', 'timucin', 'turc', 'davidssons', 'srinivas', 'yo', 'koph', 'hoffnung'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_49
  WTF: {'school'} {'robbie'}
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3015eb30d0>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
topic_3
  WTF: {'vs'} {'nhl'}
topic_4
topic_5
  WTF: {'dont', 'surrender', 'candida'} {'gordon', 'hiv', 'n3jxp'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_6
topic_7
  WTF: {'news', 'book'} {'o157h7', 'anania'}
topic_8
  WTF: {'children', 'started', 'government', 'ottoman', 'muslim', 'saw'} {'armenia', 'azerbaijan', 'sumgait', 'turks', 'armenian', 'armenians'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_9
  WTF: {'quality'} {'bj200'}
topic_10
  WTF: {'toolbox', 'effortsall', 'dragdrop', 'recollection', 'taxation', 'CDROMCATZIP', '207556000', 'NikeDeacon', 'NikeCajun', '8800CS', 'CSCSTD00385', 'L2PMABGZ7VAZV0PZRI', '1795', '5152940082'} {''}
  WTF?!?!? 14
topic_11
topic_12
  WTF: {'football', 'adventure', '35'} {'snes', 'cdi', 'sega'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_13
topic_14
  WTF: {'declutch'} {'caltrans'}
topic_15
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_16
topic_17
topic_18
  WTF: {'chemicals', 'insisting'} {'cato', 'shafer'}
topic_19
  WTF: {'hotels'} {'hotelco'}
topic_20
  WTF: {'writing', 'vol', 'copyright', 'analytic', '02106chopinudeledu', 'manual'} {'vinge', 'dune', 'vernor', 'petrucci', 'gibson', 'baen'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_21
topic_22
  WTF: {'difference', 'pay', 'people'} {'vip', 'heydt', 'moody'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_23
  WTF: {'hotel', 'use'} {'tuscon', 'bahamas'}
topic_24
  WTF: {'server'} {'r3'}
topic_25
topic_26
  WTF: {'requisition', 'centigrade', 'hundredths', 'eabu288orionoacuciedu'} {'nottoodistant', 'bridgend', 'asthmatics', 'avagadros'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_27
  WTF: {'know', 'doityourselfers'} {'kirlian', 'krillean'}
topic_28
topic_29
  WTF: {'bookstore', 'wilt', 'members', 'words', 'love', 'invoke', 'law', 'magic', 'restriction', 'organization', 'superior', 'groups', 'oriental'} {'orientis', 'rosae', 'reuss', 'crowley', 'lewis', 'crucis', 'ordo', 'rosicrucian', 'amorc', 'frater', 'oto', 'templi', 'masonic'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_30
  WTF: {'stripped', 'regards'} {'babak', 'sehari'}
topic_31
  WTF: {'nick', '49er', 'mit'} {'sept', 'cambridge', 'quincy'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_32
  WTF: {'list', 'utter', 'military', 'jobs'} {'irs', 'registries', 'c17', 'admistration'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_33
topic_34
  WTF: {'bending', 'm4', 'tunnel', 'height'} {'m5', 'm3', 'mw', 'rsi'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_35
  WTF: {'theory'} {'alice'}
topic_36
  WTF: {'worse', 'germany', 'dangerous'} {'femine', 'calverts', 'fatti'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_37
  WTF: {'hardware', 'internet', 'left'} {'null', 'localtalk', 'munich'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_38
  WTF: {'uuencode', 'ioccc'} {'eofnotok', 'xvoid'}
topic_39
  WTF: {'vending', 'patchmaking', 'remixed', 'patentable'} {'cocacola', 'yerazunis', 'cola', 'pepsi'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_40
  WTF: {'memorable', 'hes', 'somethin', 'changing', 'trench'} {'yankess', 'dykstra', 'ballad', 'subterranean', 'anime'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_41
  WTF: {'mach'} {'ses'}
topic_42
  WTF: {'dleungeeubcca', '128196128234', 'hermesmeritedu', 'dkmillerunixgubcca', 'horrendously'} {'tocserve', 'pradhaanrebelsb', 'sivesh', 'ncsa', 'sprintnet'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_43
  WTF: {'stabilized', 'addition', 'version', 'pads', 'combo'} {'t4', 'salyut', 'russia', 'energiam', 't4centaur'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_44
  WTF: {'correct', 'trick', 'screen'} {'supercharging', 'robbinsgreat', 'judd'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_45
  WTF: {'ground', 'glass', 'powers'} {'hifi', 'emerson', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_46
  WTF: {'promote'} {'fenholt'}
topic_47
  WTF: {'circuitry', 'carrier'} {'100mhz', 'ecl'}
topic_48
  WTF: {'nazism', 'hell', 'dem', 'mr', 'ya', 'moments', 'oddly', 'utilize'} {'zeuge', 'timucin', 'turc', 'davidssons', 'srinivas', 'yo', 'koph', 'hoffnung'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_49
  WTF: {'school'} {'robbie'}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f30b0598a60>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f303d44cf40>}
{'perplexity': 118120.890625, 'coherence_20': 1.8251798650906563, 'toplen_ptw': 1.1455751517055066, 'diversity_euclidean': 0.1053952480902036, 'diversity_jensenshannon': 0.7784913556079828, 'diversity_hellinger': 0.9250351433662752, 'diversity_cosine': 0.9191083837294143, 'fair_ppl_free': 2080.80517578125, 'fair_ppl_fix': 116616.2890625, 'unfair_ppl_banklike': 118120.890625}
{'num_topics': 51, 'num_common_words': 59415, 'num_model_words': 114951, 'num_bt_words': 97541, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 15, 'lost_bt': 1, 'lost_model': 14}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}]}
17
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
topic_3
  WTF: {'vs'} {'nhl'}
topic_4
topic_5
  WTF: {'dont', 'surrender', 'candida'} {'gordon', 'hiv', 'n3jxp'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_6
topic_7
  WTF: {'land'} {'stephanopoulos'}
topic_8
  WTF: {'discussion'} {'o157h7'}
topic_9
  WTF: {'children', 'started', 'government', 'ottoman', 'muslim', 'saw'} {'armenia', 'azerbaijan', 'sumgait', 'turks', 'armenian', 'armenians'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_10
  WTF: {'scanner'} {'bj200'}
topic_11
  WTF: {'just', 'like'} {'caligiuri', 'enviroleague'}
topic_12
  WTF: {'dragdrop', 'recollection', 'L2PMABGZ7VAZV0PZRI', 'Guideline', 'knowlege', 'JH2SC281XPM100187', '1795', 'toolbox', 'effortsall', 'taxation', '207556000', 'CDROMCATZIP', 'NikeCajun', '8800CS', 'CSCSTD00385', 'strobe', 'monthly', '5152940082'} {''}
  WTF?!?!? 18
topic_13
topic_14
  WTF: {'cars'} {'caltrans'}
topic_15
topic_16
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_17
topic_18
topic_19
  WTF: {'driving'} {'supra'}
topic_20
  WTF: {'email', 'writing', 'vol', 'copyright', 'analytic', '02106chopinudeledu'} {'vinge', 'dune', 'vernor', 'hogan', 'gibson', 'baen'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_21
  WTF: {'chemicals', 'insisting'} {'cato', 'shafer'}
topic_22
  WTF: {'250', 'use'} {'irwin', 'mactools'}
topic_23
  WTF: {'fulllength', 'j3davidstudentbusinessuwoca', 'official', 'practive'} {'ets', 'testno', 'gre', 'selkeforgive'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_24
  WTF: {'intrinsics'} {'r3'}
topic_25
topic_26
  WTF: {'bookstore', 'wilt', 'members', 'words', 'love', 'invoke', 'law', 'magic', 'restriction', 'organization', 'superior', 'groups', 'oriental'} {'orientis', 'rosae', 'jose', 'reuss', 'crowley', 'crucis', 'ordo', 'rosicrucian', 'amorc', 'frater', 'oto', 'templi', 'masonic'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_27
  WTF: {'programming', 'students', 'cs', 'andrew'} {'mellon', 'japan', 'jstmp', 'carnegie'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_28
  WTF: {'russian', 'solve', 'typeset', 'printing', 'mesur', 'famous', 'envoy', 'wild'} {'iosef', 'anania', 'armenia', 'persians', 'orbeli', 'tyukhik', 'armenian', 'shirak'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_29
  WTF: {'know', 'doityourselfers'} {'kirlian', 'krillean'}
topic_30
topic_31
topic_32
  WTF: {'aside'} {'darius'}
topic_33
  WTF: {'stripped', 'regards'} {'babak', 'sehari'}
topic_34
  WTF: {'stuff', 'molding', 'waxed'} {'meguiars', 'mcquires', 'glaze'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_35
  WTF: {'cute'} {'heydt'}
topic_36
  WTF: {'dragdrop', 'recollection', 'L2PMABGZ7VAZV0PZRI', 'Guideline', 'knowlege', 'JH2SC281XPM100187', '1795', 'toolbox', 'effortsall', 'taxation', 'CDROMCATZIP', '207556000', 'NikeCajun', '8800CS', 'CSCSTD00385', 'strobe', '5152940082'} {''}
  WTF?!?!? 17
topic_37
  WTF: {'list', 'utter', 'military', 'jobs'} {'irs', 'registries', 'c17', 'admistration'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_38
  WTF: {'nick', '49er', 'mit'} {'sept', 'cambridge', 'quincy'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_39
topic_40
  WTF: {'theory'} {'alice'}
topic_41
  WTF: {'company', 'launch', 'power'} {'hpr', 'tripoli', 'faa'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_42
  WTF: {'worse', 'germany', 'dangerous'} {'femine', 'calverts', 'fatti'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_43
  WTF: {'genetic', 'fax', 'computational'} {'sigkids', 'siggraph', 'bethesda'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_44
  WTF: {'mf', 'mj', 'mh', 'm1', 'u0', 'et', 'trinomials', 'mm', '644', 'pw', '0n', 'ma'} {'mx', 'm0', 'pnospsxop8f', 'mw', 'm6', 'o3', 'm5', 'm3', 'e8', 'gh', 'm9', 'p6'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_45
  WTF: {'stabilized', 'addition', 'version', 'pads', 'combo'} {'t4', 'salyut', 'russia', 'energiam', 't4centaur'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_46
  WTF: {'played'} {'fenholt'}
topic_47
  WTF: {'audio', 'problem', 'returned'} {'hifi', 'emerson', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_48
  WTF: {'infringing', 'merciless', 'discreet'} {'crah', 'yerazunis', 'cola'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_49
  WTF: {'17500', 'dleungeeubcca'} {'dastar', 'vax'}
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f2b1ba200d0>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
topic_3
  WTF: {'vs'} {'nhl'}
topic_4
topic_5
  WTF: {'dont', 'surrender', 'candida'} {'gordon', 'hiv', 'n3jxp'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_6
topic_7
  WTF: {'land'} {'stephanopoulos'}
topic_8
  WTF: {'discussion'} {'o157h7'}
topic_9
  WTF: {'children', 'started', 'government', 'ottoman', 'muslim', 'saw'} {'armenia', 'azerbaijan', 'sumgait', 'turks', 'armenian', 'armenians'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_10
  WTF: {'scanner'} {'bj200'}
topic_11
  WTF: {'just', 'like'} {'caligiuri', 'enviroleague'}
topic_12
  WTF: {'dragdrop', 'recollection', 'L2PMABGZ7VAZV0PZRI', 'Guideline', 'knowlege', 'JH2SC281XPM100187', '1795', 'toolbox', 'effortsall', 'taxation', '207556000', 'CDROMCATZIP', 'NikeCajun', '8800CS', 'CSCSTD00385', 'strobe', 'monthly', '5152940082'} {''}
  WTF?!?!? 18
topic_13
topic_14
  WTF: {'cars'} {'caltrans'}
topic_15
topic_16
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_17
topic_18
topic_19
  WTF: {'driving'} {'supra'}
topic_20
  WTF: {'email', 'writing', 'vol', 'copyright', 'analytic', '02106chopinudeledu'} {'vinge', 'dune', 'vernor', 'hogan', 'gibson', 'baen'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_21
  WTF: {'chemicals', 'insisting'} {'cato', 'shafer'}
topic_22
  WTF: {'250', 'use'} {'irwin', 'mactools'}
topic_23
  WTF: {'fulllength', 'j3davidstudentbusinessuwoca', 'official', 'practive'} {'ets', 'testno', 'gre', 'selkeforgive'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_24
  WTF: {'intrinsics'} {'r3'}
topic_25
topic_26
  WTF: {'bookstore', 'wilt', 'members', 'words', 'love', 'invoke', 'law', 'magic', 'restriction', 'organization', 'superior', 'groups', 'oriental'} {'orientis', 'rosae', 'jose', 'reuss', 'crowley', 'crucis', 'ordo', 'rosicrucian', 'amorc', 'frater', 'oto', 'templi', 'masonic'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_27
  WTF: {'programming', 'students', 'cs', 'andrew'} {'mellon', 'japan', 'jstmp', 'carnegie'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_28
  WTF: {'russian', 'solve', 'typeset', 'printing', 'mesur', 'famous', 'envoy', 'wild'} {'iosef', 'anania', 'armenia', 'persians', 'orbeli', 'tyukhik', 'armenian', 'shirak'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_29
  WTF: {'know', 'doityourselfers'} {'kirlian', 'krillean'}
topic_30
topic_31
topic_32
  WTF: {'aside'} {'darius'}
topic_33
  WTF: {'stripped', 'regards'} {'babak', 'sehari'}
topic_34
  WTF: {'stuff', 'molding', 'waxed'} {'meguiars', 'mcquires', 'glaze'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_35
  WTF: {'cute'} {'heydt'}
topic_36
  WTF: {'dragdrop', 'recollection', 'L2PMABGZ7VAZV0PZRI', 'Guideline', 'knowlege', 'JH2SC281XPM100187', '1795', 'toolbox', 'effortsall', 'taxation', 'CDROMCATZIP', '207556000', 'NikeCajun', '8800CS', 'CSCSTD00385', 'strobe', '5152940082'} {''}
  WTF?!?!? 17
topic_37
  WTF: {'list', 'utter', 'military', 'jobs'} {'irs', 'registries', 'c17', 'admistration'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_38
  WTF: {'nick', '49er', 'mit'} {'sept', 'cambridge', 'quincy'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_39
topic_40
  WTF: {'theory'} {'alice'}
topic_41
  WTF: {'company', 'launch', 'power'} {'hpr', 'tripoli', 'faa'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_42
  WTF: {'worse', 'germany', 'dangerous'} {'femine', 'calverts', 'fatti'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_43
  WTF: {'genetic', 'fax', 'computational'} {'sigkids', 'siggraph', 'bethesda'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_44
  WTF: {'mf', 'mj', 'mh', 'm1', 'u0', 'et', 'trinomials', 'mm', '644', 'pw', '0n', 'ma'} {'mx', 'm0', 'pnospsxop8f', 'mw', 'm6', 'o3', 'm5', 'm3', 'e8', 'gh', 'm9', 'p6'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_45
  WTF: {'stabilized', 'addition', 'version', 'pads', 'combo'} {'t4', 'salyut', 'russia', 'energiam', 't4centaur'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_46
  WTF: {'played'} {'fenholt'}
topic_47
  WTF: {'audio', 'problem', 'returned'} {'hifi', 'emerson', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_48
  WTF: {'infringing', 'merciless', 'discreet'} {'crah', 'yerazunis', 'cola'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_49
  WTF: {'17500', 'dleungeeubcca'} {'dastar', 'vax'}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f2e51d1ee80>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3073c728b0>}
{'perplexity': 54311.24609375, 'coherence_20': 1.7993323579551546, 'toplen_ptw': 1.1556226573391764, 'diversity_euclidean': 0.1330228582312914, 'diversity_jensenshannon': 0.773545231220898, 'diversity_hellinger': 0.9187622054519611, 'diversity_cosine': 0.9136478297862621, 'fair_ppl_free': 2073.733154296875, 'fair_ppl_fix': 53719.2734375, 'unfair_ppl_banklike': 54311.24609375}
{'num_topics': 51, 'num_common_words': 59415, 'num_model_words': 114951, 'num_bt_words': 97541, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 19, 'lost_bt': 1, 'lost_model': 18}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 18, 'lost_bt': 1, 'lost_model': 17}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}]}
18
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
  WTF: {'vs'} {'nhl'}
topic_3
topic_4
  WTF: {'koresh'} {'fbi'}
topic_5
  WTF: {'just', 'enforcement'} {'stephanopoulos', 'nsa'}
topic_6
  WTF: {'surrender', 'research', 'doctors'} {'gordon', 'hiv', 'n3jxp'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_7
topic_8
  WTF: {'votes'} {'o157h7'}
topic_9
  WTF: {'children', 'started', 'government', 'ottoman', 'muslim', 'saw'} {'armenia', 'azerbaijan', 'sumgait', 'turks', 'armenian', 'armenians'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_10
  WTF: {'im'} {'bj200'}
topic_11
  WTF: {'just', 'like'} {'caligiuri', 'enviroleague'}
topic_12
  WTF: {'toolbox', 'effortsall', 'dragdrop', 'taxation', 'Epilepsy', '207556000', 'CDROMCATZIP', 'NikeCajun', '8800CS', 'CSCSTD00385', 'L2PMABGZ7VAZV0PZRI', 'knowlege', 'ringleaders', '1795', '5152940082'} {''}
  WTF?!?!? 15
topic_13
topic_14
  WTF: {'driving'} {'caltrans'}
topic_15
  WTF: {'mail'} {'ripem'}
topic_16
  WTF: {'new'} {'hotelco'}
topic_17
topic_18
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_19
  WTF: {'festival'} {'ishtar'}
topic_20
topic_21
topic_22
  WTF: {'email', 'writing', 'vol', 'copyright', 'analytic', '02106chopinudeledu'} {'vinge', 'dune', 'vernor', 'petrucci', 'gibson', 'baen'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_23
  WTF: {'250', 'use'} {'irwin', 'mactools'}
topic_24
  WTF: {'400', 'grayscales', 'handheld', 'buy', 'scans', 'market'} {'ocr', 'dexxa', 'scanman', 'paintbrush', 'mustek', 'ocr104zip'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_25
  WTF: {'server'} {'r3'}
topic_26
topic_27
  WTF: {'bookstore', 'wilt', 'members', 'words', 'love', 'invoke', 'law', 'magic', 'restriction', 'organization', 'superior', 'groups', 'oriental'} {'orientis', 'rosae', 'jose', 'reuss', 'crowley', 'crucis', 'ordo', 'rosicrucian', 'amorc', 'frater', 'oto', 'templi', 'masonic'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_28
  WTF: {'try', 'card'} {'microsofts', 'sb'}
topic_29
  WTF: {'posts', 'gotten', 'frontpage', 'documentaries', 'evil', 'articles', 'times', 'auto'} {'id314159', 'mossad', 'lazarus', 'mahantgvcom', 'mahan', 'samuel', 'patrick', 'tgv'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_30
topic_31
topic_32
  WTF: {'condemning', 'races', 'pharisees', 'quote', 'fundamentalists'} {'kent', 'sandvik', 'ks', 'malcolm', 'gen'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_33
  WTF: {'know', 'doityourselfers'} {'kirlian', 'krillean'}
topic_34
  WTF: {'dim', 'type'} {'emi', 'hv'}
topic_35
  WTF: {'cute'} {'heydt'}
topic_36
  WTF: {'stripped', 'regards'} {'babak', 'sehari'}
topic_37
  WTF: {'rule', 'bang', 'king', 'sort', 'guide', 'forget'} {'altima', 'adams', 'alice', 'maxima', 'douglas', 'infiniti'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_38
  WTF: {'pork', 'abolished', 'immoral', 'bases'} {'registries', 'c5s', 'c17', 'admistration'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_39
  WTF: {'university'} {'aiken'}
topic_40
  WTF: {'blows', 'feeding', 'react'} {'hifi', 'emerson', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_41
  WTF: {'tuesday', 'mall', 'participants'} {'kenai', 'amc', 'quincy'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_42
  WTF: {'backand', '0099', 'remixed', 'patchmaking', 'unpatentable'} {'crah', 'yerazunis', 'cola', 'cocacola', 'pepsi'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_43
  WTF: {'promote'} {'fenholt'}
topic_44
  WTF: {'preliminary', 'rumor', 'confirm'} {'biscayne', 'matson', 'alabama'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_45
  WTF: {'stabilized', 'addition', 'version', 'pads', 'combo'} {'t4', 'salyut', 'russia', 'energiam', 't4centaur'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_46
  WTF: {'flowers', 'distrust', 'airports'} {'bahamas', 'subgenii', 'barnum'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_47
  WTF: {'tp', 'mf', 'mj', 'mh', 'm1', 'u0', 'trinomials', 'mm', '644', 'pw', '0n', 'ma'} {'mx', 'm0', 'pnospsxop8f', 'mw', 'm6', 'o3', 'm5', 'm3', 'e8', 'lu', 'm9', 'p6'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_48
  WTF: {'tongs', 'alveoli', 'trust'} {'oxygenco2', 'co2', 'cyclically'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_49
  WTF: {'division', 'balls', 'insisting', 'live', 'boston', 'tons', 'energy', 'nations'} {'barre', 'olson', 'creek', 'auth', 'wilkes', 'epa', 'bozeman', 'rochester'}
  WTF?!?!? 8
  WTF?!?!? 8
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f2e08b9ee20>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
  WTF: {'vs'} {'nhl'}
topic_3
topic_4
  WTF: {'koresh'} {'fbi'}
topic_5
  WTF: {'just', 'enforcement'} {'stephanopoulos', 'nsa'}
topic_6
  WTF: {'surrender', 'research', 'doctors'} {'gordon', 'hiv', 'n3jxp'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_7
topic_8
  WTF: {'votes'} {'o157h7'}
topic_9
  WTF: {'children', 'started', 'government', 'ottoman', 'muslim', 'saw'} {'armenia', 'azerbaijan', 'sumgait', 'turks', 'armenian', 'armenians'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_10
  WTF: {'im'} {'bj200'}
topic_11
  WTF: {'just', 'like'} {'caligiuri', 'enviroleague'}
topic_12
  WTF: {'toolbox', 'effortsall', 'dragdrop', 'taxation', 'Epilepsy', '207556000', 'CDROMCATZIP', 'NikeCajun', '8800CS', 'CSCSTD00385', 'L2PMABGZ7VAZV0PZRI', 'knowlege', 'ringleaders', '1795', '5152940082'} {''}
  WTF?!?!? 15
topic_13
topic_14
  WTF: {'driving'} {'caltrans'}
topic_15
  WTF: {'mail'} {'ripem'}
topic_16
  WTF: {'new'} {'hotelco'}
topic_17
topic_18
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_19
  WTF: {'festival'} {'ishtar'}
topic_20
topic_21
topic_22
  WTF: {'email', 'writing', 'vol', 'copyright', 'analytic', '02106chopinudeledu'} {'vinge', 'dune', 'vernor', 'petrucci', 'gibson', 'baen'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_23
  WTF: {'250', 'use'} {'irwin', 'mactools'}
topic_24
  WTF: {'400', 'grayscales', 'handheld', 'buy', 'scans', 'market'} {'ocr', 'dexxa', 'scanman', 'paintbrush', 'mustek', 'ocr104zip'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_25
  WTF: {'server'} {'r3'}
topic_26
topic_27
  WTF: {'bookstore', 'wilt', 'members', 'words', 'love', 'invoke', 'law', 'magic', 'restriction', 'organization', 'superior', 'groups', 'oriental'} {'orientis', 'rosae', 'jose', 'reuss', 'crowley', 'crucis', 'ordo', 'rosicrucian', 'amorc', 'frater', 'oto', 'templi', 'masonic'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_28
  WTF: {'try', 'card'} {'microsofts', 'sb'}
topic_29
  WTF: {'posts', 'gotten', 'frontpage', 'documentaries', 'evil', 'articles', 'times', 'auto'} {'id314159', 'mossad', 'lazarus', 'mahantgvcom', 'mahan', 'samuel', 'patrick', 'tgv'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_30
topic_31
topic_32
  WTF: {'condemning', 'races', 'pharisees', 'quote', 'fundamentalists'} {'kent', 'sandvik', 'ks', 'malcolm', 'gen'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_33
  WTF: {'know', 'doityourselfers'} {'kirlian', 'krillean'}
topic_34
  WTF: {'dim', 'type'} {'emi', 'hv'}
topic_35
  WTF: {'cute'} {'heydt'}
topic_36
  WTF: {'stripped', 'regards'} {'babak', 'sehari'}
topic_37
  WTF: {'rule', 'bang', 'king', 'sort', 'guide', 'forget'} {'altima', 'adams', 'alice', 'maxima', 'douglas', 'infiniti'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_38
  WTF: {'pork', 'abolished', 'immoral', 'bases'} {'registries', 'c5s', 'c17', 'admistration'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_39
  WTF: {'university'} {'aiken'}
topic_40
  WTF: {'blows', 'feeding', 'react'} {'hifi', 'emerson', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_41
  WTF: {'tuesday', 'mall', 'participants'} {'kenai', 'amc', 'quincy'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_42
  WTF: {'backand', '0099', 'remixed', 'patchmaking', 'unpatentable'} {'crah', 'yerazunis', 'cola', 'cocacola', 'pepsi'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_43
  WTF: {'promote'} {'fenholt'}
topic_44
  WTF: {'preliminary', 'rumor', 'confirm'} {'biscayne', 'matson', 'alabama'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_45
  WTF: {'stabilized', 'addition', 'version', 'pads', 'combo'} {'t4', 'salyut', 'russia', 'energiam', 't4centaur'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_46
  WTF: {'flowers', 'distrust', 'airports'} {'bahamas', 'subgenii', 'barnum'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_47
  WTF: {'tp', 'mf', 'mj', 'mh', 'm1', 'u0', 'trinomials', 'mm', '644', 'pw', '0n', 'ma'} {'mx', 'm0', 'pnospsxop8f', 'mw', 'm6', 'o3', 'm5', 'm3', 'e8', 'lu', 'm9', 'p6'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_48
  WTF: {'tongs', 'alveoli', 'trust'} {'oxygenco2', 'co2', 'cyclically'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_49
  WTF: {'division', 'balls', 'insisting', 'live', 'boston', 'tons', 'energy', 'nations'} {'barre', 'olson', 'creek', 'auth', 'wilkes', 'epa', 'bozeman', 'rochester'}
  WTF?!?!? 8
  WTF?!?!? 8

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f2fc7ff8a30>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f30903e1070>}
{'perplexity': 50541.65234375, 'coherence_20': 1.797234009740845, 'toplen_ptw': 1.151113989566064, 'diversity_euclidean': 0.10263763742228328, 'diversity_jensenshannon': 0.7714968481340951, 'diversity_hellinger': 0.9156526976990833, 'diversity_cosine': 0.9103862788970033, 'fair_ppl_free': 2048.618408203125, 'fair_ppl_fix': 49880.93359375, 'unfair_ppl_banklike': 50541.65234375}
{'num_topics': 51, 'num_common_words': 59415, 'num_model_words': 114951, 'num_bt_words': 97541, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 16, 'lost_bt': 1, 'lost_model': 15}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}]}
19
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
  WTF: {'vs'} {'nhl'}
topic_3
topic_4
  WTF: {'banks', 'surrender', 'candida'} {'gordon', 'hiv', 'n3jxp'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_5
topic_6
  WTF: {'votes'} {'o157h7'}
topic_7
  WTF: {'children', 'started', 'government', 'ottoman', 'muslim', 'saw'} {'armenia', 'azerbaijan', 'sumgait', 'turks', 'armenian', 'armenians'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_8
  WTF: {'driver'} {'bj200'}
topic_9
  WTF: {'like', 'sin'} {'caligiuri', 'enviroleague'}
topic_10
  WTF: {'toolbox', 'effortsall', 'dragdrop', 'taxation', 'Epilepsy', '207556000', 'CDROMCATZIP', 'NikeCajun', '8800CS', 'CSCSTD00385', 'L2PMABGZ7VAZV0PZRI', 'knowlege', 'ringleaders', '1795', '5152940082'} {''}
  WTF?!?!? 15
topic_11
topic_12
  WTF: {'mail'} {'ripem'}
topic_13
  WTF: {'dont', 'working'} {'stephanopoulos', 'myers'}
topic_14
  WTF: {'declutch'} {'caltrans'}
topic_15
topic_16
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_17
topic_18
topic_19
topic_20
topic_21
  WTF: {'writing', 'vol', 'copyright', 'analytic', '02106chopinudeledu', 'manual'} {'vinge', 'vernor', 'petrucci', 'hogan', 'gibson', 'baen'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_22
topic_23
  WTF: {'250', 'pickup'} {'irwin', 'mactools'}
topic_24
  WTF: {'intrinsics'} {'r3'}
topic_25
  WTF: {'400', 'grayscales', 'handheld', 'buy', 'scans', 'market'} {'ocr', 'dexxa', 'scanman', 'paintbrush', 'mustek', 'ocr104zip'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_26
  WTF: {'rule'} {'alice'}
topic_27
  WTF: {'etiquette', 'difference'} {'vip', 'heydt'}
topic_28
  WTF: {'tutorial', 'participants', 'year', 'cs'} {'mellon', 'japan', 'jstmp', 'carnegie'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_29
  WTF: {'know', 'doityourselfers'} {'kirlian', 'krillean'}
topic_30
  WTF: {'english', 'people'} {'bede', 'ishtar'}
topic_31
topic_32
  WTF: {'pork', 'abolished', 'immoral', 'bases'} {'registries', 'c5s', 'c17', 'admistration'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_33
  WTF: {'russian', 'solve', 'typeset', 'printing', 'mesur', 'famous', 'envoy', 'wild'} {'iosef', 'anania', 'armenia', 'persians', 'orbeli', 'tyukhik', 'armenian', 'shirak'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_34
  WTF: {'aside'} {'darius'}
topic_35
  WTF: {'stripped', 'regards'} {'babak', 'sehari'}
topic_36
  WTF: {'folks', 'articles', 'rode', 'directors'} {'bmwmoa', 'moa', 'ama', 'mc'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_37
  WTF: {'nick', '49er', 'mit'} {'sept', 'cambridge', 'quincy'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_38
  WTF: {'frequencies'} {'emi'}
topic_39
  WTF: {'audio', 'cords', 'capacitor', 'sure', 'elect'} {'hv', 'goldstar', 'vcr', 'hifi', 'emerson'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_40
  WTF: {'launch', 'class', 'safety'} {'hpr', 'tripoli', 'faa'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_41
  WTF: {'tcpip', 'best', 'route'} {'phonenet', 'localtalk', 'workgroups'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_42
  WTF: {'stabilized', 'facilities', 'big', 'launch', 'version', 'combo'} {'joe', 't4', 'salyut', 'russia', 'energiam', 't4centaur'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_43
  WTF: {'hiden'} {'scotyy'}
topic_44
  WTF: {'genetic', 'fax', 'computational'} {'sigkids', 'siggraph', 'bethesda'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_45
  WTF: {'uploaded', 'commercials', 'major'} {'ipas', 'v200', 'nwres2dll'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_46
  WTF: {'tp', 'mf', 'mj', 'mh', 'm1', 'u0', 'trinomials', 'mm', '644', 'pw', '0n', 'ma'} {'mx', 'm0', 'pnospsxop8f', 'mw', 'm6', 'o3', 'm5', 'm3', 'e8', 'lu', 'm9', 'p6'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_47
  WTF: {'nazism', 'hell', 'dem', 'mr', 'ya', 'moments', 'oddly', 'utilize'} {'zeuge', 'timucin', 'turc', 'davidssons', 'srinivas', 'yo', 'koph', 'hoffnung'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_48
  WTF: {'product', 'commercial', 'preproduction', 'release', 'allright', '300'} {'pacman', 'ces', '3do', 'pong', 'visicalc', '3dos'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_49
  WTF: {'transliterated', 'reseacher', 'fiansovamcom', '6144594256', 'kutuzovavenusitebserpukhovsu'} {'ussrsu', 'belorusskaya', 'iki', 'moscow', 'kremlin'}
  WTF?!?!? 5
  WTF?!?!? 5
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f2b1ba357c0>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
  WTF: {'vs'} {'nhl'}
topic_3
topic_4
  WTF: {'banks', 'surrender', 'candida'} {'gordon', 'hiv', 'n3jxp'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_5
topic_6
  WTF: {'votes'} {'o157h7'}
topic_7
  WTF: {'children', 'started', 'government', 'ottoman', 'muslim', 'saw'} {'armenia', 'azerbaijan', 'sumgait', 'turks', 'armenian', 'armenians'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_8
  WTF: {'driver'} {'bj200'}
topic_9
  WTF: {'like', 'sin'} {'caligiuri', 'enviroleague'}
topic_10
  WTF: {'toolbox', 'effortsall', 'dragdrop', 'taxation', 'Epilepsy', '207556000', 'CDROMCATZIP', 'NikeCajun', '8800CS', 'CSCSTD00385', 'L2PMABGZ7VAZV0PZRI', 'knowlege', 'ringleaders', '1795', '5152940082'} {''}
  WTF?!?!? 15
topic_11
topic_12
  WTF: {'mail'} {'ripem'}
topic_13
  WTF: {'dont', 'working'} {'stephanopoulos', 'myers'}
topic_14
  WTF: {'declutch'} {'caltrans'}
topic_15
topic_16
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_17
topic_18
topic_19
topic_20
topic_21
  WTF: {'writing', 'vol', 'copyright', 'analytic', '02106chopinudeledu', 'manual'} {'vinge', 'vernor', 'petrucci', 'hogan', 'gibson', 'baen'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_22
topic_23
  WTF: {'250', 'pickup'} {'irwin', 'mactools'}
topic_24
  WTF: {'intrinsics'} {'r3'}
topic_25
  WTF: {'400', 'grayscales', 'handheld', 'buy', 'scans', 'market'} {'ocr', 'dexxa', 'scanman', 'paintbrush', 'mustek', 'ocr104zip'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_26
  WTF: {'rule'} {'alice'}
topic_27
  WTF: {'etiquette', 'difference'} {'vip', 'heydt'}
topic_28
  WTF: {'tutorial', 'participants', 'year', 'cs'} {'mellon', 'japan', 'jstmp', 'carnegie'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_29
  WTF: {'know', 'doityourselfers'} {'kirlian', 'krillean'}
topic_30
  WTF: {'english', 'people'} {'bede', 'ishtar'}
topic_31
topic_32
  WTF: {'pork', 'abolished', 'immoral', 'bases'} {'registries', 'c5s', 'c17', 'admistration'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_33
  WTF: {'russian', 'solve', 'typeset', 'printing', 'mesur', 'famous', 'envoy', 'wild'} {'iosef', 'anania', 'armenia', 'persians', 'orbeli', 'tyukhik', 'armenian', 'shirak'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_34
  WTF: {'aside'} {'darius'}
topic_35
  WTF: {'stripped', 'regards'} {'babak', 'sehari'}
topic_36
  WTF: {'folks', 'articles', 'rode', 'directors'} {'bmwmoa', 'moa', 'ama', 'mc'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_37
  WTF: {'nick', '49er', 'mit'} {'sept', 'cambridge', 'quincy'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_38
  WTF: {'frequencies'} {'emi'}
topic_39
  WTF: {'audio', 'cords', 'capacitor', 'sure', 'elect'} {'hv', 'goldstar', 'vcr', 'hifi', 'emerson'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_40
  WTF: {'launch', 'class', 'safety'} {'hpr', 'tripoli', 'faa'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_41
  WTF: {'tcpip', 'best', 'route'} {'phonenet', 'localtalk', 'workgroups'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_42
  WTF: {'stabilized', 'facilities', 'big', 'launch', 'version', 'combo'} {'joe', 't4', 'salyut', 'russia', 'energiam', 't4centaur'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_43
  WTF: {'hiden'} {'scotyy'}
topic_44
  WTF: {'genetic', 'fax', 'computational'} {'sigkids', 'siggraph', 'bethesda'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_45
  WTF: {'uploaded', 'commercials', 'major'} {'ipas', 'v200', 'nwres2dll'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_46
  WTF: {'tp', 'mf', 'mj', 'mh', 'm1', 'u0', 'trinomials', 'mm', '644', 'pw', '0n', 'ma'} {'mx', 'm0', 'pnospsxop8f', 'mw', 'm6', 'o3', 'm5', 'm3', 'e8', 'lu', 'm9', 'p6'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_47
  WTF: {'nazism', 'hell', 'dem', 'mr', 'ya', 'moments', 'oddly', 'utilize'} {'zeuge', 'timucin', 'turc', 'davidssons', 'srinivas', 'yo', 'koph', 'hoffnung'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_48
  WTF: {'product', 'commercial', 'preproduction', 'release', 'allright', '300'} {'pacman', 'ces', '3do', 'pong', 'visicalc', '3dos'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_49
  WTF: {'transliterated', 'reseacher', 'fiansovamcom', '6144594256', 'kutuzovavenusitebserpukhovsu'} {'ussrsu', 'belorusskaya', 'iki', 'moscow', 'kremlin'}
  WTF?!?!? 5
  WTF?!?!? 5

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f3073b70fd0>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f2e18e31400>}
{'perplexity': 51453.03515625, 'coherence_20': 1.7888420085794032, 'toplen_ptw': 1.1527515510703177, 'diversity_euclidean': 0.10142367686004278, 'diversity_jensenshannon': 0.7734498107149447, 'diversity_hellinger': 0.9186120979591645, 'diversity_cosine': 0.9142060015213784, 'fair_ppl_free': 2086.357421875, 'fair_ppl_fix': 50791.91015625, 'unfair_ppl_banklike': 51453.03515625}
{'num_topics': 51, 'num_common_words': 59415, 'num_model_words': 114951, 'num_bt_words': 97541, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 16, 'lost_bt': 1, 'lost_model': 15}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}]}

In [37]:
1

1

In [ ]:
top_words

In [38]:
! ls $SAVE_FOLDER

bertopic		      iterative_100000.json	 plsa_with_cohs.json
bertopic.json		      iterative2_100000000	 sparse_with_cohs.json
decorrelation_with_cohs.json  iterative2_100000000.json  tless_with_cohs.json
iterative_100000	      lda_with_cohs.json

In [40]:
! ls $SAVE_FOLDER/bertopic -alh

total 248K
drwxrwxr-x 2 alekseev_v mil_lab 4,0K июл 27 16:12 .
drwxrwxr-x 5 alekseev_v mil_lab 4,0K июл 27 16:12 ..
-rw-rw-r-- 1 alekseev_v mil_lab 9,9K июл 27 07:59 bertopic_0.json
-rw-rw-r-- 1 alekseev_v mil_lab 9,9K июл 27 12:20 bertopic_10.json
-rw-rw-r-- 1 alekseev_v mil_lab 9,9K июл 27 12:46 bertopic_11.json
-rw-rw-r-- 1 alekseev_v mil_lab 9,9K июл 27 13:11 bertopic_12.json
-rw-rw-r-- 1 alekseev_v mil_lab 9,9K июл 27 13:37 bertopic_13.json
-rw-rw-r-- 1 alekseev_v mil_lab 9,9K июл 27 14:03 bertopic_14.json
-rw-rw-r-- 1 alekseev_v mil_lab 9,9K июл 27 14:28 bertopic_15.json
-rw-rw-r-- 1 alekseev_v mil_lab 9,9K июл 27 14:54 bertopic_16.json
-rw-rw-r-- 1 alekseev_v mil_lab 9,9K июл 27 15:20 bertopic_17.json
-rw-rw-r-- 1 alekseev_v mil_lab 9,9K июл 27 15:46 bertopic_18.json
-rw-rw-r-- 1 alekseev_v mil_lab 9,9K июл 27 16:12 bertopic_19.json
-rw-rw-r-- 1 alekseev_v mil_lab 9,9K июл 27 08:25 bertopic_1.json
-rw-rw-r-- 1 alekseev_v mil_lab 9,9K июл 27 08:52 bertopic_2.json
-rw-rw-r-- 1 alekseev_v mil_lab 9,9K июл 27 09:18 bertopic_3.json
-rw-rw-r-- 1 alekseev_v mil_lab 9,9K июл 27 09:44 bertopic_4.json
-rw-rw-r-- 1 alekseev_v mil_lab 9,9K июл 27 10:11 bertopic_5.json
-rw-rw-r-- 1 alekseev_v mil_lab 9,9K июл 27 10:36 bertopic_6.json
-rw-rw-r-- 1 alekseev_v mil_lab 9,8K июл 27 11:03 bertopic_7.json
-rw-rw-r-- 1 alekseev_v mil_lab 9,9K июл 27 11:29 bertopic_8.json
-rw-rw-r-- 1 alekseev_v mil_lab 9,9K июл 27 11:55 bertopic_9.json

In [41]:
! cat $SAVE_FOLDER/bertopic/bertopic_0.json

{
    "scores": {
        "perplexity": 50620.3359375,
        "coherence_20": 1.8455919239185774,
        "toplen_ptw": 1.1528501347545348,
        "diversity_euclidean": 0.10544738016575618,
        "diversity_jensenshannon": 0.7757965562983609,
        "diversity_hellinger": 0.9212522523991468,
        "diversity_cosine": 0.9165479447048536,
        "fair_ppl_free": 2053.462646484375,
        "fair_ppl_fix": 50116.61328125,
        "unfair_ppl_banklike": 50620.3359375
    },
    "topic_coherences": {
        "0": 0.8417338335807545,
        "1": 1.2158048736180374,
        "2": 0.9038911082260183,
        "3": 1.7435182036513177,
        "4": 1.3185101190923818,
        "5": 1.8307735869367339,
        "6": 2.761703107570687,
        "7": 1.5059996645800025,
        "8": 1.1010261350651018,
        "9": 1.8376920141684219,
        "10": 2.221732234639326,
        "11": 0.11077045587647175,
        "12": 1.7882253733198608,
        "13": 1.8848328888647778,
        "14": 2.0729125558302286,
        "15": 1.6500494183072165,
        "16": 2.3749365833698453,
        "17": 4.315723788131953,
        "18": 3.2767273850445635,
        "19": 1.957026855503117,
        "20": 1.3677451796206377,
        "21": 1.2807770023275034,
        "22": 2.031208839981024,
        "23": 1.4808428438251473,
        "24": 2.4447699840878476,
        "25": 1.3113348631878727,
        "26": 4.183798859293114,
        "27": 3.7567500660203463,
        "28": 2.0787123949373876,
        "29": 1.927610904988673,
        "30": 1.7520811949383328,
        "31": 0.650911907042481,
        "32": 1.3770167995683047,
        "33": 1.5782205394635975,
        "34": 1.357245333446955,
        "35": 2.147960296634493,
        "36": 1.6763841885283843,
        "37": 3.9655590420746494,
        "38": 2.150769177059853,
        "39": 2.4708702047743176,
        "40": 1.3772971805046774,
        "41": 1.9873434219527188,
        "42": 2.0294898149052445,
        "43": 1.3258669039399194,
        "44": 1.3010470970691403,
        "45": 1.1946909515501167,
        "46": 1.6172965989113703,
        "47": 0.2288675749154625,
        "48": 1.4611537249651367,
        "49": 2.0523831200373546
    },
    "topic_coherences_toplen_ptw": {
        "0": 1.7499656727584105,
        "1": 1.3064101701937623,
        "2": 1.2788132301264004,
        "3": 2.169133661049326,
        "4": 1.4337833579398989,
        "5": 1.446001375516368,
        "6": 1.2847007816711171,
        "7": 1.1529163161763187,
        "8": 1.233773539036999,
        "9": 1.2019995769696858,
        "10": 1.1321525332059452,
        "11": 1.0192307692307692,
        "12": 1.163048551127149,
        "13": 1.184333096974794,
        "14": 1.1542675982382746,
        "15": 1.1514909983103963,
        "16": 1.1065822226032405,
        "17": 1.1825815455909825,
        "18": 1.1262201930315765,
        "19": 1.169171788094216,
        "20": 1.1121999672274976,
        "21": 1.1561260821874662,
        "22": 1.1606291868726009,
        "23": 1.1387725204150914,
        "24": 1.1900649282961513,
        "25": 1.116807401762222,
        "26": 1.1129048407367446,
        "27": 1.1383387793914574,
        "28": 1.1363471418383497,
        "29": 1.093481465161614,
        "30": 1.1344809178085569,
        "31": 1.1149766825273062,
        "32": 1.1596975429778411,
        "33": 1.14441389604664,
        "34": 1.1527839533327509,
        "35": 1.1321074944878147,
        "36": 1.135448781730505,
        "37": 1.1434950330528477,
        "38": 1.1435576718703317,
        "39": 1.1209292568534333,
        "40": 1.120918262088152,
        "41": 1.1166525317718499,
        "42": 1.1588150947330491,
        "43": 1.186999436618388,
        "44": 1.1961240629251428,
        "45": 1.1814458183414407,
        "46": 1.218566638877504,
        "47": 101.43762737346067,
        "48": 1.1224408799256425,
        "49": 1.0742352788770269
    },
    "stats": {
        "num_topics": 51,
        "num_common_words": 59415,
        "num_model_words": 114951,
        "num_bt_words": 97541,
        "top_diffs": [
            {
                "total": 0,
                "lost_bt": 0,
                "lost_model": 0
            },
            {
                "total": 0,
                "lost_bt": 0,
                "lost_model": 0
            },
            {
                "total": 2,
                "lost_bt": 1,
                "lost_model": 1
            },
            {
                "total": 2,
                "lost_bt": 1,
                "lost_model": 1
            },
            {
                "total": 0,
                "lost_bt": 0,
                "lost_model": 0
            },
            {
                "total": 6,
                "lost_bt": 3,
                "lost_model": 3
            },
            {
                "total": 0,
                "lost_bt": 0,
                "lost_model": 0
            },
            {
                "total": 4,
                "lost_bt": 2,
                "lost_model": 2
            },
            {
                "total": 12,
                "lost_bt": 6,
                "lost_model": 6
            },
            {
                "total": 2,
                "lost_bt": 1,
                "lost_model": 1
            },
            {
                "total": 4,
                "lost_bt": 2,
                "lost_model": 2
            },
            {
                "total": 16,
                "lost_bt": 1,
                "lost_model": 15
            },
            {
                "total": 0,
                "lost_bt": 0,
                "lost_model": 0
            },
            {
                "total": 0,
                "lost_bt": 0,
                "lost_model": 0
            },
            {
                "total": 4,
                "lost_bt": 2,
                "lost_model": 2
            },
            {
                "total": 0,
                "lost_bt": 0,
                "lost_model": 0
            },
            {
                "total": 4,
                "lost_bt": 2,
                "lost_model": 2
            },
            {
                "total": 0,
                "lost_bt": 0,
                "lost_model": 0
            },
            {
                "total": 0,
                "lost_bt": 0,
                "lost_model": 0
            },
            {
                "total": 0,
                "lost_bt": 0,
                "lost_model": 0
            },
            {
                "total": 12,
                "lost_bt": 6,
                "lost_model": 6
            },
            {
                "total": 4,
                "lost_bt": 2,
                "lost_model": 2
            },
            {
                "total": 12,
                "lost_bt": 6,
                "lost_model": 6
            },
            {
                "total": 12,
                "lost_bt": 6,
                "lost_model": 6
            },
            {
                "total": 0,
                "lost_bt": 0,
                "lost_model": 0
            },
            {
                "total": 8,
                "lost_bt": 4,
                "lost_model": 4
            },
            {
                "total": 4,
                "lost_bt": 2,
                "lost_model": 2
            },
            {
                "total": 0,
                "lost_bt": 0,
                "lost_model": 0
            },
            {
                "total": 2,
                "lost_bt": 1,
                "lost_model": 1
            },
            {
                "total": 4,
                "lost_bt": 2,
                "lost_model": 2
            },
            {
                "total": 2,
                "lost_bt": 1,
                "lost_model": 1
            },
            {
                "total": 6,
                "lost_bt": 3,
                "lost_model": 3
            },
            {
                "total": 4,
                "lost_bt": 2,
                "lost_model": 2
            },
            {
                "total": 2,
                "lost_bt": 1,
                "lost_model": 1
            },
            {
                "total": 6,
                "lost_bt": 3,
                "lost_model": 3
            },
            {
                "total": 6,
                "lost_bt": 3,
                "lost_model": 3
            },
            {
                "total": 10,
                "lost_bt": 5,
                "lost_model": 5
            },
            {
                "total": 4,
                "lost_bt": 2,
                "lost_model": 2
            },
            {
                "total": 8,
                "lost_bt": 4,
                "lost_model": 4
            },
            {
                "total": 6,
                "lost_bt": 3,
                "lost_model": 3
            },
            {
                "total": 4,
                "lost_bt": 2,
                "lost_model": 2
            },
            {
                "total": 0,
                "lost_bt": 0,
                "lost_model": 0
            },
            {
                "total": 10,
                "lost_bt": 5,
                "lost_model": 5
            },
            {
                "total": 14,
                "lost_bt": 7,
                "lost_model": 7
            },
            {
                "total": 6,
                "lost_bt": 3,
                "lost_model": 3
            },
            {
                "total": 2,
                "lost_bt": 1,
                "lost_model": 1
            },
            {
                "total": 6,
                "lost_bt": 3,
                "lost_model": 3
            },
            {
                "total": 24,
                "lost_bt": 12,
                "lost_model": 12
            },
            {
                "total": 2,
                "lost_bt": 1,
                "lost_model": 1
            },
            {
                "total": 6,
                "lost_bt": 3,
                "lost_model": 3
            }
        ]
    }
}

In [42]:
! cat $SAVE_FOLDER/bertopic.json

[
    {
        "scores": {
            "perplexity": 50620.3359375,
            "coherence_20": 1.8455919239185774,
            "toplen_ptw": 1.1528501347545348,
            "diversity_euclidean": 0.10544738016575618,
            "diversity_jensenshannon": 0.7757965562983609,
            "diversity_hellinger": 0.9212522523991468,
            "diversity_cosine": 0.9165479447048536,
            "fair_ppl_free": 2053.462646484375,
            "fair_ppl_fix": 50116.61328125,
            "unfair_ppl_banklike": 50620.3359375
        },
        "topic_coherences": {
            "0": 0.8417338335807545,
            "1": 1.2158048736180374,
            "2": 0.9038911082260183,
            "3": 1.7435182036513177,
            "4": 1.3185101190923818,
            "5": 1.8307735869367339,
            "6": 2.761703107570687,
            "7": 1.5059996645800025,
            "8": 1.1010261350651018,
            "9": 1.8376920141684219,
            "10": 2.221732234639326,
            "11": 0.11077045587647175,
            "12": 1.7882253733198608,
            "13": 1.8848328888647778,
            "14": 2.0729125558302286,
            "15": 1.6500494183072165,
            "16": 2.3749365833698453,
            "17": 4.315723788131953,
            "18": 3.2767273850445635,
            "19": 1.957026855503117,
            "20": 1.3677451796206377,
            "21": 1.2807770023275034,
            "22": 2.031208839981024,
            "23": 1.4808428438251473,
            "24": 2.4447699840878476,
            "25": 1.3113348631878727,
            "26": 4.183798859293114,
            "27": 3.7567500660203463,
            "28": 2.0787123949373876,
            "29": 1.927610904988673,
            "30": 1.7520811949383328,
            "31": 0.650911907042481,
            "32": 1.3770167995683047,
            "33": 1.5782205394635975,
            "34": 1.357245333446955,
            "35": 2.147960296634493,
            "36": 1.6763841885283843,
            "37": 3.9655590420746494,
            "38": 2.150769177059853,
            "39": 2.4708702047743176,
            "40": 1.3772971805046774,
            "41": 1.9873434219527188,
            "42": 2.0294898149052445,
            "43": 1.3258669039399194,
            "44": 1.3010470970691403,
            "45": 1.1946909515501167,
            "46": 1.6172965989113703,
            "47": 0.2288675749154625,
            "48": 1.4611537249651367,
            "49": 2.0523831200373546
        },
        "topic_coherences_toplen_ptw": {
            "0": 1.7499656727584105,
            "1": 1.3064101701937623,
            "2": 1.2788132301264004,
            "3": 2.169133661049326,
            "4": 1.4337833579398989,
            "5": 1.446001375516368,
            "6": 1.2847007816711171,
            "7": 1.1529163161763187,
            "8": 1.233773539036999,
            "9": 1.2019995769696858,
            "10": 1.1321525332059452,
            "11": 1.0192307692307692,
            "12": 1.163048551127149,
            "13": 1.184333096974794,
            "14": 1.1542675982382746,
            "15": 1.1514909983103963,
            "16": 1.1065822226032405,
            "17": 1.1825815455909825,
            "18": 1.1262201930315765,
            "19": 1.169171788094216,
            "20": 1.1121999672274976,
            "21": 1.1561260821874662,
            "22": 1.1606291868726009,
            "23": 1.1387725204150914,
            "24": 1.1900649282961513,
            "25": 1.116807401762222,
            "26": 1.1129048407367446,
            "27": 1.1383387793914574,
            "28": 1.1363471418383497,
            "29": 1.093481465161614,
            "30": 1.1344809178085569,
            "31": 1.1149766825273062,
            "32": 1.1596975429778411,
            "33": 1.14441389604664,
            "34": 1.1527839533327509,
            "35": 1.1321074944878147,
            "36": 1.135448781730505,
            "37": 1.1434950330528477,
            "38": 1.1435576718703317,
            "39": 1.1209292568534333,
            "40": 1.120918262088152,
            "41": 1.1166525317718499,
            "42": 1.1588150947330491,
            "43": 1.186999436618388,
            "44": 1.1961240629251428,
            "45": 1.1814458183414407,
            "46": 1.218566638877504,
            "47": 101.43762737346067,
            "48": 1.1224408799256425,
            "49": 1.0742352788770269
        },
        "stats": {
            "num_topics": 51,
            "num_common_words": 59415,
            "num_model_words": 114951,
            "num_bt_words": 97541,
            "top_diffs": [
                {
                    "total": 0,
                    "lost_bt": 0,
                    "lost_model": 0
                },
                {
                    "total": 0,
                    "lost_bt": 0,
                    "lost_model": 0
                },
                {
                    "total": 2,
                    "lost_bt": 1,
                    "lost_model": 1
                },
                {
                    "total": 2,
                    "lost_bt": 1,
                    "lost_model": 1
                },
                {
                    "total": 0,
                    "lost_bt": 0,
                    "lost_model": 0
                },
                {
                    "total": 6,
                    "lost_bt": 3,
                    "lost_model": 3
                },
                {
                    "total": 0,
                    "lost_bt": 0,
                    "lost_model": 0
                },
                {
                    "total": 4,
                    "lost_bt": 2,
                    "lost_model": 2
                },
                {
                    "total": 12,
                    "lost_bt": 6,
                    "lost_model": 6
                },
                {
                    "total": 2,
                    "lost_bt": 1,
                    "lost_model": 1
                },
                {
                    "total": 4,
                    "lost_bt": 2,
                    "lost_model": 2
                },
                {
                    "total": 16,
                    "lost_bt": 1,
                    "lost_model": 15
                },
                {
                    "total": 0,
                    "lost_bt": 0,
                    "lost_model": 0
                },
                {
                    "total": 0,
                    "lost_bt": 0,
                    "lost_model": 0
                },
                {
                    "total": 4,
                    "lost_bt": 2,
                    "lost_model": 2
                },
                {
                    "total": 0,
                    "lost_bt": 0,
                    "lost_model": 0
                },
                {
                    "total": 4,
                    "lost_bt": 2,
                    "lost_model": 2
                },
                {
                    "total": 0,
                    "lost_bt": 0,
                    "lost_model": 0
                },
                {
                    "total": 0,
                    "lost_bt": 0,
                    "lost_model": 0
                },
                {
                    "total": 0,
                    "lost_bt": 0,
                    "lost_model": 0
                },
                {
                    "total": 12,
                    "lost_bt": 6,
                    "lost_model": 6
                },
                {
                    "total": 4,
                    "lost_bt": 2,
                    "lost_model": 2
                },
                {
                    "total": 12,
                    "lost_bt": 6,
                    "lost_model": 6
                },
                {
                    "total": 12,
                    "lost_bt": 6,
                    "lost_model": 6
                },
                {
                    "total": 0,
                    "lost_bt": 0,
                    "lost_model": 0
                },
                {
                    "total": 8,
                    "lost_bt": 4,
                    "lost_model": 4
                },
                {
                    "total": 4,
                    "lost_bt": 2,
                    "lost_model": 2
                },
                {
                    "total": 0,
                    "lost_bt": 0,
                    "lost_model": 0
                },
                {
                    "total": 2,
                    "lost_bt": 1,
                    "lost_model": 1
                },
                {
                    "total": 4,
                    "lost_bt": 2,
                    "lost_model": 2
                },
                {
                    "total": 2,
                    "lost_bt": 1,
                    "lost_model": 1
                },
                {
                    "total": 6,
                    "lost_bt": 3,
                    "lost_model": 3
                },
                {
                    "total": 4,
                    "lost_bt": 2,
                    "lost_model": 2
                },
                {
                    "total": 2,
                    "lost_bt": 1,
                    "lost_model": 1
                },
                {
                    "total": 6,
                    "lost_bt": 3,
                    "lost_model": 3
                },
                {
                    "total": 6,
                    "lost_bt": 3,
                    "lost_model": 3
                },
                {
                    "total": 10,
                    "lost_bt": 5,
                    "lost_model": 5
                },
                {
                    "total": 4,
                    "lost_bt": 2,
                    "lost_model": 2
                },
                {
                    "total": 8,
                    "lost_bt": 4,
                    "lost_model": 4
                },
                {
                    "total": 6,
                    "lost_bt": 3,
                    "lost_model": 3
                },
                {
                    "total": 4,
                    "lost_bt": 2,
                    "lost_model": 2
                },
                {
                    "total": 0,
                    "lost_bt": 0,
                    "lost_model": 0
                },
                {
                    "total": 10,
                    "lost_bt": 5,
                    "lost_model": 5
                },
                {
                    "total": 14,
                    "lost_bt": 7,
                    "lost_model": 7
                },
                {
                    "total": 6,
                    "lost_bt": 3,
                    "lost_model": 3
                },
                {
                    "total": 2,
                    "lost_bt": 1,
                    "lost_model": 1
                },
                {
                    "total": 6,
                    "lost_bt": 3,
                    "lost_model": 3
                },
                {
                    "total": 24,
                    "lost_bt": 12,
                    "lost_model": 12
                },
                {
                    "total": 2,
                    "lost_bt": 1,
                    "lost_model": 1
                },
                {
                    "total": 6,
                    "lost_bt": 3,
                    "lost_model": 3
                }
            ]
        }
    },
    {
        "scores": {
            "perplexity": 52182.9765625,
            "coherence_20": 1.7859453831714371,
            "toplen_ptw": 1.1493372974428273,
            "diversity_euclidean": 0.11084360827941732,
            "diversity_jensenshannon": 0.7812483409267726,
            "diversity_hellinger": 0.9288220020495234,
            "diversity_cosine": 0.9258888344463115,
            "fair_ppl_free": 2118.781494140625,
            "fair_ppl_fix": 51689.3515625,
            "unfair_ppl_banklike": 52182.9765625
        },
        "topic_coherences": {
            "0": 0.9327033340649997,
            "1": 0.7216640880608317,
            "2": 1.7435182036513177,
            "3": 1.0834278730642135,
            "4": 1.7624969938884025,
            "5": 2.563488381651125,
            "6": 1.673567050830537,
            "7": 1.1010261350651018,
            "8": 1.7343524384452695,
            "9": 0.04990329257241071,
            "10": 1.818830718387739,
            "11": 1.2063905260426202,
            "12": 1.6500494183072165,
            "13": 2.3749365833698453,
            "14": 4.315723788131953,
            "15": 1.7009891651008018,
            "16": 0.6603484546767382,
            "17": 1.367745179620637,
            "18": 1.7657834679246227,
            "19": 3.2767273850445644,
            "20": 1.2807770023275034,
            "21": 2.400208452786185,
            "22": 1.957026855503117,
            "23": 2.031208839981024,
            "24": 1.1723655804165072,
            "25": 3.7567500660203463,
            "26": 2.4447699840878476,
            "27": 1.1952384804715532,
            "28": 1.795723870804917,
            "29": 4.183798859293114,
            "30": 1.3770167995683047,
            "31": 0.593858981098609,
            "32": 1.5669261497641247,
            "33": 1.9334291167792266,
            "34": 1.023874265272274,
            "35": 1.4808428438251473,
            "36": 1.7891834636927255,
            "37": 1.1694305870710056,
            "38": 1.381145317036739,
            "39": 3.1659773889324687,
            "40": 1.1317711299904443,
            "41": 3.9655590420746494,
            "42": 1.8039875165692179,
            "43": 2.0294898149052445,
            "44": 2.136876804854279,
            "45": 0.2288675749154625,
            "46": 1.3111492355801062,
            "47": 1.9586036210555269,
            "48": 1.1946909515501167,
            "49": 2.3330480844431345
        },
        "topic_coherences_toplen_ptw": {
            "0": 1.6697473483678507,
            "1": 1.4775691395206072,
            "2": 2.0444002022846623,
            "3": 1.3953237631009858,
            "4": 1.4343766788164376,
            "5": 1.2795486151971363,
            "6": 1.167278272638336,
            "7": 1.2585721567502777,
            "8": 1.1800747336870143,
            "9": 1.059843117408907,
            "10": 1.2119003322670907,
            "11": 1.1493129865044713,
            "12": 1.1601393176362198,
            "13": 1.1185814000745053,
            "14": 1.2115960584749246,
            "15": 1.136641708665479,
            "16": 1.1439239842465256,
            "17": 1.1052038459925788,
            "18": 1.1393534969007932,
            "19": 1.1634933892192123,
            "20": 1.1475091700458828,
            "21": 1.1025339781088943,
            "22": 1.1493616083811833,
            "23": 1.1598632067544417,
            "24": 1.172255522886722,
            "25": 1.1335648821677091,
            "26": 1.1577087276237203,
            "27": 1.1322519959641224,
            "28": 1.1210575421602467,
            "29": 1.111762971435397,
            "30": 1.1439704716152528,
            "31": 1.1163210587442052,
            "32": 1.1291227115578732,
            "33": 1.132422220774796,
            "34": 1.158076642308333,
            "35": 1.1351353684846217,
            "36": 1.1723689656241305,
            "37": 1.20950654834329,
            "38": 1.1633807794884061,
            "39": 1.096662809385925,
            "40": 1.0964978658446454,
            "41": 1.112312140266164,
            "42": 1.135727803327545,
            "43": 1.1496388198359664,
            "44": 1.149748940226696,
            "45": 101.11022340595622,
            "46": 1.1248503668631982,
            "47": 1.0879325805730284,
            "48": 1.1846561399809161,
            "49": 1.124114734561615
        },
        "stats": {
            "num_topics": 51,
            "num_common_words": 59415,
            "num_model_words": 114951,
            "num_bt_words": 97541,
            "top_diffs": [
                {
                    "total": 0,
                    "lost_bt": 0,
                    "lost_model": 0
                },
                {
                    "total": 0,
                    "lost_bt": 0,
                    "lost_model": 0
                },
                {
                    "total": 2,
                    "lost_bt": 1,
                    "lost_model": 1
                },
                {
                    "total": 0,
                    "lost_bt": 0,
                    "lost_model": 0
                },
                {
                    "total": 6,
                    "lost_bt": 3,
                    "lost_model": 3
                },
                {
                    "total": 0,
                    "lost_bt": 0,
                    "lost_model": 0
                },
                {
                    "total": 2,
                    "lost_bt": 1,
                    "lost_model": 1
                },
                {
                    "total": 12,
                    "lost_bt": 6,
                    "lost_model": 6
                },
                {
                    "total": 2,
                    "lost_bt": 1,
                    "lost_model": 1
                },
                {
                    "total": 15,
                    "lost_bt": 1,
                    "lost_model": 14
                },
                {
                    "total": 0,
                    "lost_bt": 0,
                    "lost_model": 0
                },
                {
                    "total": 6,
                    "lost_bt": 3,
                    "lost_model": 3
                },
                {
                    "total": 0,
                    "lost_bt": 0,
                    "lost_model": 0
                },
                {
                    "total": 4,
                    "lost_bt": 2,
                    "lost_model": 2
                },
                {
                    "total": 0,
                    "lost_bt": 0,
                    "lost_model": 0
                },
                {
                    "total": 2,
                    "lost_bt": 1,
                    "lost_model": 1
                },
                {
                    "total": 8,
                    "lost_bt": 4,
                    "lost_model": 4
                },
                {
                    "total": 12,
                    "lost_bt": 6,
                    "lost_model": 6
                },
                {
                    "total": 4,
                    "lost_bt": 2,
                    "lost_model": 2
                },
                {
                    "total": 0,
                    "lost_bt": 0,
                    "lost_model": 0
                },
                {
                    "total": 4,
                    "lost_bt": 2,
                    "lost_model": 2
                },
                {
                    "total": 14,
                    "lost_bt": 7,
                    "lost_model": 7
                },
                {
                    "total": 0,
                    "lost_bt": 0,
                    "lost_model": 0
                },
                {
                    "total": 12,
                    "lost_bt": 6,
                    "lost_model": 6
                },
                {
                    "total": 4,
                    "lost_bt": 2,
                    "lost_model": 2
                },
                {
                    "total": 0,
                    "lost_bt": 0,
                    "lost_model": 0
                },
                {
                    "total": 0,
                    "lost_bt": 0,
                    "lost_model": 0
                },
                {
                    "total": 2,
                    "lost_bt": 1,