In [2]:
import os
import json
import shutil
import sys

import numpy as np
import scipy

In [3]:
sys.path.insert(0, '../OptimalNumberOfTopics')

In [4]:
import topnum

from topnum.scores.perplexity_score import PerplexityScore
from topnum.scores.diversity_score import DiversityScore, KNOWN_METRICS
from topnum.model_constructor import init_model_from_family, KnownModel, PARAMS_EXPLORED, init_plsa

In [5]:
import artm
from artm import ARTM, Dictionary

import topicnet
from topicnet.cooking_machine.dataset import Dataset
from topicnet.cooking_machine.models import (
    BaseScore as BaseTopicNetScore,
    TopicModel
)
from topicnet.cooking_machine.models.base_regularizer import BaseRegularizer
from topicnet.cooking_machine.models.thetaless_regularizer import (
    dataset2sparse_matrix,
)

from topicnet.cooking_machine.models.topic_model import ARTM_NINE
from topicnet.cooking_machine.models.base_regularizer import BaseRegularizer
from topicnet.viewers.top_documents_viewer import TopDocumentsViewer
from topicnet.viewers.top_tokens_viewer import TopTokensViewer
from topicnet.cooking_machine.model_constructor import (
    add_standard_scores,
    create_default_topics,
    count_vocab_size,
    init_model,
)
from topicnet.cooking_machine.rel_toolbox_lite import (
    count_vocab_size,
    modality_weight_rel2abs,
    transform_regularizer,
)


import numpy as np
import pandas as pd
from pandas import DataFrame
from scipy.spatial.distance import cdist

import os
import tempfile
import warnings
from copy import deepcopy
from typing import Dict, List, Optional

In [6]:
BERTOPIC_FOLDER_PATH = '/data_mil/shared/CompressaAI/BERTopic'
RESULTS_FOLDER_PATH = os.path.join(BERTOPIC_FOLDER_PATH, 'results', '20newsgroups')

In [7]:
! ls $RESULTS_FOLDER_PATH

0  1  10  11  12  13  14  15  16  17  18  19  2  3  4  5  6  7	8  9

In [8]:
! ls $RESULTS_FOLDER_PATH/0

dataset.csv  dataset__internals  phi.csv  top_words.json

In [9]:
dataset = Dataset(
    f'{RESULTS_FOLDER_PATH}/0/dataset.csv',
)

dataset.get_possible_modalities()

{'@lemmatized'}

In [10]:
MAIN_MODALITY = '@lemmatized'

In [11]:
def calc_doc_occurrences(dataset, modality):
    """
    :param n_dw_matrix: sparse document-word matrix, shape is D x W
    :return: sparse matrix of co-occurrences

    doc_occurrences[w1, w2] = the number of the documents
    where there are w1 and w2
    """
    n_dw_matrix = dataset2sparse_matrix(dataset, modality, modalities_to_use=[modality])
    matrix = (scipy.sparse.csc_matrix(n_dw_matrix) > 0).astype(int)
    co_occurrences = matrix.T * matrix

    return co_occurrences.diagonal(), co_occurrences


def create_pmi_top_function(
    doc_occurrences, doc_co_occurrences,
    documents_number, top_sizes,
    topic_indices,
    co_occurrences_smooth=1.
):
    """
    :param doc_occurrences: array of doc occurrences of words
    :param doc_co_occurrences: sparse matrix of doc co-occurrences of words
    :param documents_number: number of the documents
    :param top_sizes: list of top values to calculate top-pmi for
    :param co_occurrences_smooth: constant to smooth co-occurrences in log
    :return: function which takes phi and theta and returns
    pair of two arrays: pmi-s of the tops and ppmi-s of the tops

    pmi[i] - pmi(top of size top_sizes[i])
    ppmi[i] - ppmi(top of size top_sizes[i])

    pmi(words) = sum_{u in words, v in words, u != v}
    log(
        (doc_co_occurrences[u, v] * documents_number + co_occurrences_smooth)
        / doc_occurrences[u] / doc_occurrences[v]
    )

    ppmi(words) = sum_{u in words, v in words, u != v}
    max(log(
        (doc_co_occurrences[u, v] * documents_number + co_occurrences_smooth)
        / doc_occurrences[u] / doc_occurrences[v]
    ), 0)

    """
    def func(phi):
        _T, W = phi.shape
        T = len(topic_indices)

        max_top_size = max(top_sizes)
        topic_pmis, topic_ppmis = dict(), dict()
        pmi, ppmi = np.zeros(max_top_size), np.zeros(max_top_size)
        tops = np.argpartition(phi, -max_top_size, axis=1)[:, -max_top_size:]
        
        for t in topic_indices:
            top = sorted(tops[t], key=lambda w: - phi[t, w])
            co_occurrences = doc_co_occurrences[top, :][:, top].todense()
            occurrences = doc_occurrences[top]
            values = np.log(
                (co_occurrences * documents_number + co_occurrences_smooth)
                / (occurrences[:, np.newaxis] * occurrences[np.newaxis, :] + co_occurrences_smooth)
            )
            diag = np.diag_indices(len(values))
            # values.cumsum(axis=0).cumsum(axis=1)[diag] - values[diag].cumsum()

            current_pmi = np.array(
               values.cumsum(axis=0).cumsum(axis=1)[diag] - values[diag].cumsum()
            ).ravel()
            topic_pmis[t] = current_pmi
            pmi += current_pmi

            values[values < 0.] = 0.
            current_ppmi = np.array(
               values.cumsum(axis=0).cumsum(axis=1)[diag] - values[diag].cumsum()
            ).ravel()
            topic_ppmis[t] = current_ppmi
            ppmi += current_ppmi
            
        sizes = np.arange(2, max_top_size + 1)
        pmi[1:] /= (T * sizes * (sizes - 1))
        ppmi[1:] /= (T * sizes * (sizes - 1))
        indices = np.array(top_sizes) - 1

        for t in topic_indices:
            topic_pmis[t][1:] /= (sizes * (sizes - 1))
            topic_ppmis[t][1:] /= (sizes * (sizes - 1))

        result_topic_pmis = {t: p[indices] for t, p in topic_pmis.items()}
        result_topic_ppmis = {t: p[indices] for t, p in topic_ppmis.items()}

        return pmi[indices], ppmi[indices], result_topic_pmis, result_topic_ppmis

    return func

In [12]:
%%time

occurences, co_occurences = calc_doc_occurrences(dataset, MAIN_MODALITY)

CPU times: user 6.29 s, sys: 333 ms, total: 6.63 s
Wall time: 6.55 s

In [13]:
co_occurences.shape

(114951, 114951)

In [14]:
calc_pmi = create_pmi_top_function(
    occurences, co_occurences,
    dataset.get_dataset().shape[0], [20],
    topic_indices=[0, 1, 2],
    co_occurrences_smooth=1e-2,
)

In [15]:
class TopTokenCoherence(BaseTopicNetScore):
    def __init__(self, name, func):
        super().__init__()

        self._name = name
        self.calc_pmi = func

    def call(self, model: TopicModel):
        values = self.calc_pmi(model.get_phi_dense()[0].T)

        return values[1]

    def call_by_topic(self, model: TopicModel):
        values = self.calc_pmi(model.get_phi_dense()[0].T)

        return values[3]

In [16]:
def view_model(
        topic_model,
        dataset,
        num_top_tokens: int = 5,
        top_tokens_method: str = 'phi',
        num_topics: Optional[int] = 5,  # we do not want to fill the whole .ipynb notebook with topics...
        ):
    top_tok_viewer = TopTokensViewer(
        topic_model, num_top_tokens=num_top_tokens, method=top_tokens_method
    )
    top_doc_viewer = TopDocumentsViewer(topic_model, dataset=dataset)
    top_docs = top_doc_viewer.view()

    if num_topics is None:
        num_topics = len(topic_model.topic_names)

    for topic_name in topic_model.topic_names[:num_topics]:
        topic_top_toks = top_tok_viewer.to_html(topic_names=[topic_name])
        topic_top_docs = top_docs[topic_name]
        display_html(topic_top_toks, raw=True)
        display(topic_top_docs)

In [17]:
class FastFixPhiRegularizer(BaseRegularizer):
    _VERY_BIG_TAU = 10 ** 9

    def __init__(self, name: str, topic_names: List[str], parent_model=None, parent_phi=None, words=None):
        super().__init__(name, tau=self._VERY_BIG_TAU)

        self._topic_names = topic_names
        self._topic_indices = None
        self._words = words
        self._word_indices = None
        self._parent_model = parent_model
        self._parent_phi = parent_phi

    def grad(self, pwt, nwt):
        # print('Fixing')

        rwt = np.zeros_like(pwt)

        if self._parent_phi is not None:
            parent_phi = self._parent_phi
            vals = parent_phi.values
        else:
            assert False

            parent_phi = self._parent_model.get_phi()
            vals = parent_phi.values[:, self._topic_indices]

        if self._word_indices is None:
            assert vals.shape[0] == rwt.shape[0], (vals.shape[0], rwt.shape[0])
        else:
            assert vals.shape[0] == len(self._word_indices)

        assert vals.shape[1] == len(self._topic_indices)

        if self._word_indices is None:
            rwt[:, self._topic_indices] += vals
        else:
            # print(len(self._word_indices), len(self._topic_indices), rwt.shape, vals.shape)
            # print(self._word_indices[:3], self._topic_indices[:3])
            # print(rwt[np.ix_(self._word_indices, self._topic_indices)].shape, vals.shape)

            # https://github.com/numpy/numpy/issues/5574
            # https://github.com/numpy/numpy/issues/13255
            rwt[np.ix_(self._word_indices, self._topic_indices)] += vals

            # print(np.ix_(self._word_indices, self._topic_indices)[:3])

        return self.tau * rwt

    def attach(self, model):
        super().attach(model)
        
        phi = self._model.get_phi()
        self._topic_indices = [
            phi.columns.get_loc(topic_name)
            for topic_name in self._topic_names
        ]

        if self._words is not None:
            self._word_indices = [
                # phi.index.get_loc(w) for w in self._words
                int(phi.index.get_loc(w)) for w in self._words
            ]

            # print(f'!!! Word indices: {self._word_indices}')

In [18]:
NUM_TOPICS = 20

NUM_ITERATIONS = 5
NUM_TOP_TOKENS = 20
NUM_TRAINS = 20

In [19]:
NUM_TOPICS

20

In [20]:
def fit_and_compute_scores(model, dataset, target_topic_indices=None, custom_regularizers=None):
    print(custom_regularizers)

    model._fit(dataset.get_batch_vectorizer(), num_iterations=NUM_ITERATIONS, custom_regularizers=custom_regularizers)

    score_values = {
        'perplexity': model.scores[f'PerplexityScore{MAIN_MODALITY}'][-1],
    }

    phi = model.get_phi()

    # Currently all topics are taken into account

    if target_topic_indices is None:
        target_topic_indices = list(range(NUM_TOPICS))  # phi.columns.get_loc()

    target_topic_names = [phi.columns[i] for i in target_topic_indices]

    top = NUM_TOP_TOKENS
    coherence_score = TopTokenCoherence(
        name=f'coherence_{top}',
        func=create_pmi_top_function(
            occurences, co_occurences,
            dataset.get_dataset().shape[0], [top],
            topic_indices=target_topic_indices,
            co_occurrences_smooth=1e-2,
        )
    )

    value = coherence_score.call(model)
    score_values[coherence_score._name] = value
    topic_coherences = coherence_score.call_by_topic(model)
    topic_coherences = {t: float(v) for t, v in topic_coherences.items()}

    diversity_scores = [
        DiversityScore(
            name=f'diversity_{metric}',
            metric=metric,
            topic_names=target_topic_names,
            class_ids=MAIN_MODALITY,
        )
    
        for metric in KNOWN_METRICS
    ]
    
    for score in diversity_scores:
        value = score.call(model)
        score_values[score._name] = value

    return {
        'scores': score_values,
        'topic_coherences': topic_coherences,
    }

In [21]:
def init_model_from_family(
        family: str or KnownModel,
        dataset: Dataset,
        main_modality: str,
        num_topics: int,
        seed: int,
        specific_topic_names = None,
        modalities_to_use: List[str] = None,
        num_processors: int = 3,
        model_params: dict = None,
):
    """
    Returns
    -------
    model: TopicModel() instance
    """
    if isinstance(family, KnownModel):
        family = family.value

    if modalities_to_use is None:
        modalities_to_use = [main_modality]

    custom_regs = {}

    if family == "LDA":
        model = init_lda(
            dataset, modalities_to_use, main_modality, num_topics, model_params
        )
    elif family == "PLSA":
        model = init_plsa(
            dataset, modalities_to_use, main_modality, num_topics
        )
    elif family == "TARTM":
        model, custom_regs = init_thetaless(
            dataset, modalities_to_use, main_modality, num_topics, model_params
        )
    elif family == "sparse":
        model = init_bcg_sparse_model(
            dataset, modalities_to_use, main_modality, num_topics, 1, model_params
        )
    elif family == "decorrelation":
        model = init_decorrelated_plsa(
            dataset, modalities_to_use, main_modality, num_topics, model_params
        )
    elif family == "ARTM":
        model = init_baseline_artm(
            dataset, modalities_to_use, main_modality, num_topics, 1, specific_topic_names, model_params
        )
    else:
        raise ValueError(f'family: {family}')

    model.num_processors = num_processors

    if seed is not None:
        model.seed = seed

    dictionary = dataset.get_dictionary()

    # TODO: maybe this cycle is not necessary
    for modality in dataset.get_possible_modalities():
        if modality not in modalities_to_use:
            dictionary.filter(class_id=modality, max_df=0, inplace=True)

    model.initialize(dictionary)
    add_standard_scores(model, dictionary, main_modality=main_modality,
                        all_modalities=modalities_to_use)

    model = TopicModel(
        artm_model=model,
        custom_regularizers=custom_regs
    )

    return model


def init_bcg_sparse_model(
        dataset,
        modalities_to_use,
        main_modality,
        specific_topics,
        bcg_topics,
        specific_topic_names = None,
        model_params: dict = None
):
    """
    Creates simple artm model with standard scores.

    Parameters
    ----------
    dataset : Dataset
    modalities_to_use : list of str or dict
    main_modality : str
    specific_topics : int
    bcg_topics : int

    Returns
    -------
    model: artm.ARTM() instance
    """
    if model_params is None:
        model_params = dict()

    model = init_plsa(
        dataset, modalities_to_use, main_modality, specific_topics, bcg_topics
    )
    background_topic_names = model.topic_names[-bcg_topics:]

    if specific_topic_names is None:
        print('No spec topics')
        specific_topic_names = model.topic_names[:-bcg_topics]

    dictionary = dataset.get_dictionary()
    baseline_class_ids = {class_id: 1 for class_id in modalities_to_use}
    data_stats = count_vocab_size(dictionary, baseline_class_ids)

    # all coefficients are relative
    regularizers = [
        artm.SmoothSparsePhiRegularizer(
             name='smooth_phi_bcg',
             topic_names=background_topic_names,
             tau=model_params.get("smooth_bcg_tau", 0.1),
             class_ids=[main_modality],
        ),
        artm.SmoothSparseThetaRegularizer(
             name='smooth_theta_bcg',
             topic_names=background_topic_names,
             tau=model_params.get("smooth_bcg_tau", 0.1),
        ),
        artm.SmoothSparsePhiRegularizer(
             name='sparse_phi_sp',
             topic_names=specific_topic_names,
             tau=model_params.get("sparse_sp_tau", -0.05),
             class_ids=[main_modality],
            ),
        artm.SmoothSparseThetaRegularizer(
             name='sparse_theta_sp',
             topic_names=specific_topic_names,
             tau=model_params.get("sparse_sp_tau", -0.05),
        ),
    ]
    for reg in regularizers:
        model.regularizers.add(transform_regularizer(
            data_stats,
            reg,
            model.class_ids,
            n_topics=len(reg.topic_names)
        ))

    return model


def init_baseline_artm(
        dataset,
        modalities_to_use,
        main_modality,
        num_topics,
        bcg_topics,
        specific_topic_names = None,
        model_params: dict = None,
):
    """
    Creates simple artm model with standard scores.

    Parameters
    ----------
    dataset : Dataset
    modalities_to_use : list of str
    main_modality : str
    num_topics : int

    Returns
    -------
    model: artm.ARTM() instance
    """
    if model_params is None:
        model_params = dict()

    model = init_bcg_sparse_model(
        dataset, modalities_to_use, main_modality, num_topics, bcg_topics, specific_topic_names, model_params
    )

    if specific_topic_names is None:
        print('No spec topics')
        specific_topic_names = model.topic_names[:-bcg_topics]

    model.regularizers.add(
        artm.DecorrelatorPhiRegularizer(
            gamma=0,
            tau=model_params.get('decorrelation_tau', 0.01),
            name='decorrelation',
            topic_names=specific_topic_names,
            class_ids=modalities_to_use,
        )
    )

    return model

In [22]:
TOPIC_INDICES = list(range(NUM_TOPICS))

In [23]:
TOPIC_INDICES

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [24]:
phi0 = pd.read_csv(f'{RESULTS_FOLDER_PATH}/0/phi.csv', index_col=0)

In [25]:
phi0.head()

,background_1,topic_0,topic_1,topic_2,topic_3,topic_4,topic_5,topic_6,topic_7,topic_8,...,topic_10,topic_11,topic_12,topic_13,topic_14,topic_15,topic_16,topic_17,topic_18,topic_19
00,0.0,0.001167,0.000092,0.005393,0.0,0.001362,0.000000,0.000000,0.0,0.0,...,0.000737,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
000,0.0,0.000270,0.000051,0.004587,0.0,0.000254,0.000151,0.000000,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
0000,0.0,0.000050,0.000000,0.003186,0.0,0.000000,0.000000,0.000121,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
00000,0.0,0.000039,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
000000,0.0,0.000126,0.000000,0.000000,0.0,0.000473,0.000000,0.000000,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [26]:
phi0.set_index([[MAIN_MODALITY] * len(phi0.index), phi0.index], inplace=True)

In [27]:
phi0.head()

                    background_1   topic_0   topic_1   topic_2  topic_3  \
@lemmatized 00               0.0  0.001167  0.000092  0.005393      0.0
            000              0.0  0.000270  0.000051  0.004587      0.0
            0000             0.0  0.000050  0.000000  0.003186      0.0
            00000            0.0  0.000039  0.000000  0.000000      0.0
            000000           0.0  0.000126  0.000000  0.000000      0.0

                     topic_4   topic_5   topic_6  topic_7  topic_8  ...  \
@lemmatized 00      0.001362  0.000000  0.000000      0.0      0.0  ...
            000     0.000254  0.000151  0.000000      0.0      0.0  ...
            0000    0.000000  0.000000  0.000121      0.0      0.0  ...
            00000   0.000000  0.000000  0.000000      0.0      0.0  ...
            000000  0.000473  0.000000  0.000000      0.0      0.0  ...

                    topic_10  topic_11  topic_12  topic_13  topic_14  \
@lemmatized 00      0.000737       0.0       0.0       0.0       0.0
            000     0.000000       0.0       0.0       0.0       0.0
            0000    0.000000       0.0       0.0       0.0       0.0
            00000   0.000000       0.0       0.0       0.0       0.0
            000000  0.000000       0.0       0.0       0.0       0.0

                    topic_15  topic_16  topic_17  topic_18  topic_19
@lemmatized 00           0.0       0.0       0.0       0.0       0.0
            000          0.0       0.0       0.0       0.0       0.0
            0000         0.0       0.0       0.0       0.0       0.0
            00000        0.0       0.0       0.0       0.0       0.0
            000000       0.0       0.0       0.0       0.0       0.0

[5 rows x 21 columns]

In [28]:
DIFF_THRESHOLD = 2

In [39]:
def check_top_words(phi, top_words):
    diffs = []

    for t, topic_top_words in top_words.items():
        print(t)
        # print(top_words)
    
        top_phi = set(phi[t].sort_values(ascending=False)[:NUM_TOP_TOKENS].index.get_level_values(1))
        top_bt = set([p[0] for p in topic_top_words])
    
        if top_phi == top_bt:
            diffs.append(
                {
                    'total': 0,
                    'lost_bt': 0,
                    'lost_model': 0,
                }
            )
        else:
            diff1 = top_phi.difference(top_bt)
            diff2 = top_bt.difference(top_phi)
    
            print('  WTF:', diff1, diff2)
    
            if len(diff1) > DIFF_THRESHOLD:
                print(f'  WTF?!?!?', len(diff1))
    
            if len(diff2) > DIFF_THRESHOLD:
                print(f'  WTF?!?!?', len(diff2))

            diffs.append(
                {
                    'total': len(diff1 | diff2),
                    'lost_bt': len(diff2),
                    'lost_model': len(diff1),
                }
            )

    return diffs

In [40]:
def init_model_and_phi(num_topics, dataset, phi0):
    model = init_model_from_family(
        family=KnownModel.PLSA,
        dataset=dataset,
        main_modality=MAIN_MODALITY,
        num_topics=num_topics,
        seed=0,
    )
    
    phi = model.get_phi()
    
    # assert phi.shape[1] == phi0.shape[1] - 1
    assert phi.shape[1] == num_topics
    assert phi.shape[1] in [phi0.shape[1], phi0.shape[1] - 1]
    
    common_words = list(set(phi.index).intersection(phi0.index))
    
    phi.loc[:, :] = 0

    if phi.shape[1] == phi0.shape[1]:
        target_topics = phi0.columns
    elif phi.shape[1] == phi0.shape[1] - 1:
        target_topics = phi.columns
    else:
        assert False

    # print(common_words, phi.index, phi0.index)

    phi.loc[common_words, :] += phi0.loc[common_words, target_topics]

    diff = set(phi0.columns).symmetric_difference(set(phi.columns))

    assert diff == {'background_1'} or diff == {'background_1', f'topic_{len(phi.columns) - 1}'}
    
    phi = phi / phi.sum(axis=0)

    return model, phi, common_words

In [41]:
! ls results

20newsgroups  mkb10  postnauka	rtlwikiperson  ruwikigood

In [42]:
SAVE_FOLDER = os.path.join('results', '20newsgroups')

In [43]:
! ls $SAVE_FOLDER

ablation_study		iterative_100.json	    lda.json
bertopic		iterative2_1000000000.json  plsa.json
decorrelation.json	iterative2_100000000.json   sparse.json
iterative_1000000.json	iterative2_10000000.json    tless.json
iterative_100000.json	iterative2_1000000.json
iterative_1000.json	iterative2_100000.json

In [49]:
results = []

is_results_loaded = False

save_file_path = os.path.join(
    SAVE_FOLDER, 'bertopic.json'
)

if os.path.isfile(save_file_path):
    results = json.loads(
        open(save_file_path).read()
    )
    is_results_loaded = True


singles_save_folder = os.path.join(
    SAVE_FOLDER, 'bertopic'
)

os.makedirs(singles_save_folder, exist_ok=True)


for seed in range(NUM_TRAINS):
    if is_results_loaded:
        continue

    print(seed)

    current_save_file_path = os.path.join(
        singles_save_folder, f'bertopic_{seed}.json'
    )

    if os.path.isfile(current_save_file_path):
        print(f'Already computed results: {current_save_file_path}. Loading and skipping...')

        result = json.loads(
            open(current_save_file_path).read()
        )
        results.append(result)

        continue

    seed_load_folder = os.path.join(RESULTS_FOLDER_PATH, str(seed))
    files = [f for f in os.listdir(seed_load_folder) if os.path.isfile(f'{seed_load_folder}/{f}')]
    
    assert len(files) == 3

    dataset = Dataset(
        f'{seed_load_folder}/dataset.csv',
    )
    phi0 = pd.read_csv(f'{seed_load_folder}/phi.csv', index_col=0)
    phi0.set_index([[MAIN_MODALITY] * len(phi0.index), phi0.index], inplace=True)

    assert all('back' not in t for t in phi0.columns[1:])
    assert 'back' in phi0.columns[0]

    num_specific_topics = phi0.shape[1] - 1

    assert num_specific_topics == len([t for t in phi0.columns if 'back' not in t])

    print(f'Num model topics: {phi0.shape[1]}.')

    with open(f'{seed_load_folder}/top_words.json', 'r') as f:
        top_words = json.loads(f.read())


    
    model, phi, common_phi_words = init_model_and_phi(
        num_topics=num_specific_topics + 1,  # background
        dataset=dataset, phi0=phi0
    )
    common_words = [
        w[1] for w in common_phi_words  # without modality
    ]
    common_words_phi0_indices = [
        # phi0.index.get_loc(w) for w in common_words
        int(phi0.index.get_locs(w)) for w in common_phi_words
    ]

    print('Check before fit:')
    diff_tops1 = check_top_words(phi, top_words)  # Whatever...
    
    fix_regularizer = FastFixPhiRegularizer(
        name='fix',
        parent_phi=phi0.iloc[common_words_phi0_indices, 1:],
        words=common_words,
        topic_names=phi.columns[1:],
    )
    result = fit_and_compute_scores(
        model, dataset,
        target_topic_indices=list(range(phi.shape[1])),
        custom_regularizers = {
            fix_regularizer.name: fix_regularizer,
        }
    )

    print('Check after fit:')
    diff_tops2 = check_top_words(phi, top_words)  # Whatever...

    assert diff_tops1 == diff_tops2

    fair_ppl_free = result['scores']['perplexity']

    del model, phi, fix_regularizer, result


    
    model, phi, _ = init_model_and_phi(
        num_topics=num_specific_topics + 1,  # background
        dataset=dataset, phi0=phi0
    )
    fix_regularizer = FastFixPhiRegularizer(
        name='fix',
        parent_phi=phi0.iloc[common_words_phi0_indices, :],  # Diff here
        words=common_words,
        topic_names=phi.columns,
    )
    result = fit_and_compute_scores(
        model, dataset,
        target_topic_indices=list(range(phi.shape[1])),
        custom_regularizers = {
            fix_regularizer.name: fix_regularizer,
        }
    )
    
    fair_ppl_fix = result['scores']['perplexity']

    del model, phi, fix_regularizer, result

    
    
    model, phi, _ = init_model_and_phi(
        num_topics=num_specific_topics,  # Diff here
        dataset=dataset, phi0=phi0
    )
    fix_regularizer = FastFixPhiRegularizer(
        name='fix',
        parent_phi=phi0.iloc[common_words_phi0_indices, 1:],  # Diff here
        words=common_words,
        topic_names=phi.columns,
    )
    result = fit_and_compute_scores(
        model, dataset,
        custom_regularizers = {
            fix_regularizer.name: fix_regularizer,
        }
    )

    unfair_ppl_banklike = result['scores']['perplexity']


    
    result['scores']['fair_ppl_free'] = fair_ppl_free
    result['scores']['fair_ppl_fix'] = fair_ppl_fix
    result['scores']['unfair_ppl_banklike'] = unfair_ppl_banklike

    assert result['scores']['fair_ppl_free'] < result['scores']['unfair_ppl_banklike']
    # assert result['scores']['fair_ppl_fix'] < result['scores']['unfair_ppl_banklike']

    result['scores']['coherence_20'] = float(result['scores']['coherence_20'])
    result['stats'] = {
        'num_topics': phi0.shape[1],
        'num_common_words': len(common_words),
        'num_model_words': phi.shape[0],
        'num_bt_words': phi0.shape[0],
        'top_diffs': diff_tops2,
    }

    results.append(result)

    print(result['scores'])
    print(result['stats'])

    dumped_result = json.dumps(
        results[-1], indent=4
    )

    with open(current_save_file_path, 'w') as f:
        f.write(dumped_result)

    del model, phi, fix_regularizer


with open(save_file_path, 'w') as f:
    f.write(
        json.dumps(
            results, indent=4
        )
    )

0
Already computed results: results/20newsgroups/bertopic/bertopic_0.json. Loading and skipping...
1
Already computed results: results/20newsgroups/bertopic/bertopic_1.json. Loading and skipping...
2
Already computed results: results/20newsgroups/bertopic/bertopic_2.json. Loading and skipping...
3
Already computed results: results/20newsgroups/bertopic/bertopic_3.json. Loading and skipping...
4
Num model topics: 21.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
topic_0
topic_1
topic_2
  WTF: {'good'} {'nhl'}
topic_3
  WTF: {'like', 'banks'} {'n3jxp', 'gordon'}
topic_4
topic_5
  WTF: {'government', 'ottoman', 'dont', 'started', 'saw', 'know'} {'armenians', 'armenian', 'sumgait', 'turks', 'armenia', 'azerbaijan'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_6
  WTF: {'toolbox', '8800CS', '1795', 'knowlege', 'ringleaders', 'dragdrop', 'Epilepsy', '5152940082', 'CDROMCATZIP', 'CSCSTD00385', 'L2PMABGZ7VAZV0PZRI', 'NikeCajun', 'effortsall', '207556000', 'taxation'} {''}
  WTF?!?!? 15
topic_7
topic_8
  WTF: {'software', 'email', 'spice'} {'vinge', 'vernor', 'gibson'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_9
  WTF: {'social'} {'lsd'}
topic_10
  WTF: {'intrinsics'} {'r3'}
topic_11
  WTF: {'uuencode', 'int'} {'xvoid', 'eofnotok'}
topic_12
  WTF: {'charged', 'picture'} {'krillean', 'kirlian'}
topic_13
topic_14
  WTF: {'stripped', 'regards'} {'sehari', 'babak'}
topic_15
  WTF: {'computer', 'rule', 'bang'} {'adams', 'douglas', 'alice'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_16
  WTF: {'km', 'experiment', 'pattern', 'phase'} {'japan', 'kyoto', 'ohzora', 'egs'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_17
  WTF: {'corps', 'commission', 'axe'} {'admistration', 'registries', 'irs'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_18
  WTF: {'somethin', 'hes', 'hand', 'roam'} {'dykstra', 'anime', 'ballad', 'yankess'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_19
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f63123cbbe0>}
Check after fit:
topic_0
topic_1
topic_2
  WTF: {'good'} {'nhl'}
topic_3
  WTF: {'like', 'banks'} {'n3jxp', 'gordon'}
topic_4
topic_5
  WTF: {'government', 'ottoman', 'dont', 'started', 'saw', 'know'} {'armenians', 'armenian', 'sumgait', 'turks', 'armenia', 'azerbaijan'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_6
  WTF: {'toolbox', '8800CS', '1795', 'knowlege', 'ringleaders', 'dragdrop', 'Epilepsy', '5152940082', 'CDROMCATZIP', 'CSCSTD00385', 'L2PMABGZ7VAZV0PZRI', 'NikeCajun', 'effortsall', '207556000', 'taxation'} {''}
  WTF?!?!? 15
topic_7
topic_8
  WTF: {'software', 'email', 'spice'} {'vinge', 'vernor', 'gibson'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_9
  WTF: {'social'} {'lsd'}
topic_10
  WTF: {'intrinsics'} {'r3'}
topic_11
  WTF: {'uuencode', 'int'} {'xvoid', 'eofnotok'}
topic_12
  WTF: {'charged', 'picture'} {'krillean', 'kirlian'}
topic_13
topic_14
  WTF: {'stripped', 'regards'} {'sehari', 'babak'}
topic_15
  WTF: {'computer', 'rule', 'bang'} {'adams', 'douglas', 'alice'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_16
  WTF: {'km', 'experiment', 'pattern', 'phase'} {'japan', 'kyoto', 'ohzora', 'egs'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_17
  WTF: {'corps', 'commission', 'axe'} {'admistration', 'registries', 'irs'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_18
  WTF: {'somethin', 'hes', 'hand', 'roam'} {'dykstra', 'anime', 'ballad', 'yankess'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_19

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f63123de3a0>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f63123cbaf0>}
{'perplexity': 254864.703125, 'coherence_20': 1.8910867708810457, 'diversity_euclidean': 0.11453703275030573, 'diversity_jensenshannon': 0.760803678759738, 'diversity_hellinger': 0.8994272101342373, 'diversity_cosine': 0.8792692172113139, 'fair_ppl_free': 2280.89697265625, 'fair_ppl_fix': 448028.0625, 'unfair_ppl_banklike': 254864.703125}
{'num_topics': 21, 'num_common_words': 59415, 'num_model_words': 114951, 'num_bt_words': 97541, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 16, 'lost_bt': 1, 'lost_model': 15}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}]}
5
Num model topics: 21.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
topic_0
topic_1
topic_2
topic_3
  WTF: {'good'} {'nhl'}
topic_4
  WTF: {'like', 'doctors'} {'n3jxp', 'gordon'}
topic_5
  WTF: {'government', 'ottoman', 'dont', 'started', 'saw', 'know'} {'armenians', 'armenian', 'sumgait', 'turks', 'armenia', 'azerbaijan'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_6
  WTF: {'toolbox', '8800CS', '1795', 'recollection', 'dragdrop', '5152940082', 'CSCSTD00385', 'CDROMCATZIP', 'L2PMABGZ7VAZV0PZRI', 'NikeCajun', 'effortsall', '207556000', 'NikeDeacon', 'taxation'} {''}
  WTF?!?!? 14
topic_7
  WTF: {'remodeled'} {'hotelco'}
topic_8
  WTF: {'good', 'management'} {'japan', 'vinge'}
topic_9
topic_10
  WTF: {'social'} {'lsd'}
topic_11
  WTF: {'type'} {'r3'}
topic_12
  WTF: {'abolished', 'immoral', 'bases', 'deficit'} {'c5s', 'admistration', 'registries', 'c17'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_13
topic_14
  WTF: {'stripped', 'regards'} {'sehari', 'babak'}
topic_15
  WTF: {'theory'} {'alice'}
topic_16
  WTF: {'readers', 'phone', 'inventions'} {'pepsi', 'cocacola', 'tektronics'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_17
  WTF: {'1163', '980665', 'microns'} {'concensus', 'bridgend', '9g'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_18
  WTF: {'pw', '0n', 'u0', 'trinomials', 'mh', '644', 'mf', 'm1', 'mj', 'ma', 'begin', 'mm'} {'m3', 'm5', 'o3', 'lu', 'm0', 'mw', 'm9', 'pnospsxop8f', 'e8', 'mx', 'p6', 'm6'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_19
  WTF: {'ones', 'curiousity'} {'menuts', 'scotyy'}
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f63127da550>}
Check after fit:
topic_0
topic_1
topic_2
topic_3
  WTF: {'good'} {'nhl'}
topic_4
  WTF: {'like', 'doctors'} {'n3jxp', 'gordon'}
topic_5
  WTF: {'government', 'ottoman', 'dont', 'started', 'saw', 'know'} {'armenians', 'armenian', 'sumgait', 'turks', 'armenia', 'azerbaijan'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_6
  WTF: {'toolbox', '8800CS', '1795', 'recollection', 'dragdrop', '5152940082', 'CSCSTD00385', 'CDROMCATZIP', 'L2PMABGZ7VAZV0PZRI', 'NikeCajun', 'effortsall', '207556000', 'NikeDeacon', 'taxation'} {''}
  WTF?!?!? 14
topic_7
  WTF: {'remodeled'} {'hotelco'}
topic_8
  WTF: {'good', 'management'} {'japan', 'vinge'}
topic_9
topic_10
  WTF: {'social'} {'lsd'}
topic_11
  WTF: {'type'} {'r3'}
topic_12
  WTF: {'abolished', 'immoral', 'bases', 'deficit'} {'c5s', 'admistration', 'registries', 'c17'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_13
topic_14
  WTF: {'stripped', 'regards'} {'sehari', 'babak'}
topic_15
  WTF: {'theory'} {'alice'}
topic_16
  WTF: {'readers', 'phone', 'inventions'} {'pepsi', 'cocacola', 'tektronics'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_17
  WTF: {'1163', '980665', 'microns'} {'concensus', 'bridgend', '9g'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_18
  WTF: {'pw', '0n', 'u0', 'trinomials', 'mh', '644', 'mf', 'm1', 'mj', 'ma', 'begin', 'mm'} {'m3', 'm5', 'o3', 'lu', 'm0', 'mw', 'm9', 'pnospsxop8f', 'e8', 'mx', 'p6', 'm6'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_19
  WTF: {'ones', 'curiousity'} {'menuts', 'scotyy'}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f630fabb850>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f632a116f70>}
{'perplexity': 60774.28515625, 'coherence_20': 1.4569597907164384, 'diversity_euclidean': 0.11682413043910159, 'diversity_jensenshannon': 0.7635279382615238, 'diversity_hellinger': 0.9026354812926355, 'diversity_cosine': 0.874833650384061, 'fair_ppl_free': 2299.958740234375, 'fair_ppl_fix': 60526.8515625, 'unfair_ppl_banklike': 60774.28515625}
{'num_topics': 21, 'num_common_words': 59415, 'num_model_words': 114951, 'num_bt_words': 97541, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 15, 'lost_bt': 1, 'lost_model': 14}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}]}
6
Num model topics: 21.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
topic_0
topic_1
topic_2
topic_3
  WTF: {'good'} {'nhl'}
topic_4
  WTF: {'skepticism', 'like'} {'n3jxp', 'gordon'}
topic_5
  WTF: {'government', 'ottoman', 'dont', 'started', 'saw', 'know'} {'armenians', 'armenian', 'sumgait', 'turks', 'armenia', 'azerbaijan'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_6
  WTF: {'8800CS', 'recollection', 'knowlege', 'ringleaders', 'paradoxes', '5152940082', 'CSCSTD00385', 'CDROMCATZIP', 'Ferris', 'strobe', 'NikeCajun', 'effortsall', '207556000', 'taxation'} {'', 'whatta'}
  WTF?!?!? 14
topic_7
topic_8
  WTF: {'social'} {'lsd'}
topic_9
topic_10
  WTF: {'vol', 'molecular', 'manual', 'writing'} {'baen', 'vinge', 'vernor', 'gibson'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_11
topic_12
  WTF: {'andrew', 'cs', 'pm', 'students'} {'mellon', 'japan', 'carnegie', 'jstmp'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_13
topic_14
topic_15
  WTF: {'clinton', 'jobs', 'pork'} {'admistration', 'registries', 'c17'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_16
  WTF: {'stripped', 'regards'} {'sehari', 'babak'}
topic_17
  WTF: {'respondent', 'yknow', 'windscreen', 'cones'} {'canopies', 'tommy', 'mcwilliams', 'punchline'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_18
  WTF: {'returned', 'just', 'tube'} {'hifi', 'emerson', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_19
  WTF: {'exotic', 'rc', 'terribly', 'elaborate', 'chemists', 'pretends', 'pretend', 'partial'} {'pepsi', 'rc4', 'yerazunis', 'crah', 'cocacola', 'pepsicos', 'cola', 'rc2'}
  WTF?!?!? 8
  WTF?!?!? 8
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f6312ca02e0>}
Check after fit:
topic_0
topic_1
topic_2
topic_3
  WTF: {'good'} {'nhl'}
topic_4
  WTF: {'skepticism', 'like'} {'n3jxp', 'gordon'}
topic_5
  WTF: {'government', 'ottoman', 'dont', 'started', 'saw', 'know'} {'armenians', 'armenian', 'sumgait', 'turks', 'armenia', 'azerbaijan'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_6
  WTF: {'8800CS', 'recollection', 'knowlege', 'ringleaders', 'paradoxes', '5152940082', 'CSCSTD00385', 'CDROMCATZIP', 'Ferris', 'strobe', 'NikeCajun', 'effortsall', '207556000', 'taxation'} {'', 'whatta'}
  WTF?!?!? 14
topic_7
topic_8
  WTF: {'social'} {'lsd'}
topic_9
topic_10
  WTF: {'vol', 'molecular', 'manual', 'writing'} {'baen', 'vinge', 'vernor', 'gibson'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_11
topic_12
  WTF: {'andrew', 'cs', 'pm', 'students'} {'mellon', 'japan', 'carnegie', 'jstmp'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_13
topic_14
topic_15
  WTF: {'clinton', 'jobs', 'pork'} {'admistration', 'registries', 'c17'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_16
  WTF: {'stripped', 'regards'} {'sehari', 'babak'}
topic_17
  WTF: {'respondent', 'yknow', 'windscreen', 'cones'} {'canopies', 'tommy', 'mcwilliams', 'punchline'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_18
  WTF: {'returned', 'just', 'tube'} {'hifi', 'emerson', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_19
  WTF: {'exotic', 'rc', 'terribly', 'elaborate', 'chemists', 'pretends', 'pretend', 'partial'} {'pepsi', 'rc4', 'yerazunis', 'crah', 'cocacola', 'pepsicos', 'cola', 'rc2'}
  WTF?!?!? 8
  WTF?!?!? 8

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f6329658490>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f630d3a31c0>}
{'perplexity': 317347.1875, 'coherence_20': 1.702231101846186, 'diversity_euclidean': 0.12428409970869883, 'diversity_jensenshannon': 0.7610766899879671, 'diversity_hellinger': 0.8996483215958757, 'diversity_cosine': 0.8804029377815177, 'fair_ppl_free': 2299.525146484375, 'fair_ppl_fix': 470212.28125, 'unfair_ppl_banklike': 317347.1875}
{'num_topics': 21, 'num_common_words': 59415, 'num_model_words': 114951, 'num_bt_words': 97541, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 16, 'lost_bt': 2, 'lost_model': 14}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}]}
7
Num model topics: 21.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
topic_0
topic_1
topic_2
topic_3
  WTF: {'good'} {'nhl'}
topic_4
  WTF: {'doctors', 'banks'} {'n3jxp', 'gordon'}
topic_5
  WTF: {'toolbox', '8800CS', '1795', 'JH2SC281XPM100187', 'recollection', 'knowlege', 'dragdrop', '5152940082', 'CSCSTD00385', 'CDROMCATZIP', 'strobe', 'L2PMABGZ7VAZV0PZRI', 'NikeCajun', 'effortsall', '207556000', 'taxation'} {''}
  WTF?!?!? 16
topic_6
  WTF: {'living'} {'hotelco'}
topic_7
topic_8
  WTF: {'social'} {'lsd'}
topic_9
  WTF: {'computer'} {'alice'}
topic_10
  WTF: {'balls', 'energy'} {'shafer', 'dryden'}
topic_11
  WTF: {'type'} {'r3'}
topic_12
topic_13
topic_14
  WTF: {'stripped', 'regards'} {'sehari', 'babak'}
topic_15
  WTF: {'immoral', 'deficit', 'maintaining'} {'admistration', 'registries', 'c17'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_16
  WTF: {'uuencode', 'int'} {'xvoid', 'eofnotok'}
topic_17
  WTF: {'headin', 'melody', 'predictionsteam'} {'clementine', 'dykstra', 'yankess'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_18
  WTF: {'vending', 'remixed', 'patchmaking', 'patentable'} {'cola', 'pepsi', 'cocacola', 'yerazunis'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_19
  WTF: {'pw', '0n', 'u0', 'trinomials', 'mh', '644', 'mf', 'm1', 'mj', 'ma', 'begin', 'mm'} {'m3', 'm5', 'o3', 'lu', 'm0', 'mw', 'm9', 'pnospsxop8f', 'e8', 'mx', 'p6', 'm6'}
  WTF?!?!? 12
  WTF?!?!? 12
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f632948b670>}
Check after fit:
topic_0
topic_1
topic_2
topic_3
  WTF: {'good'} {'nhl'}
topic_4
  WTF: {'doctors', 'banks'} {'n3jxp', 'gordon'}
topic_5
  WTF: {'toolbox', '8800CS', '1795', 'JH2SC281XPM100187', 'recollection', 'knowlege', 'dragdrop', '5152940082', 'CSCSTD00385', 'CDROMCATZIP', 'strobe', 'L2PMABGZ7VAZV0PZRI', 'NikeCajun', 'effortsall', '207556000', 'taxation'} {''}
  WTF?!?!? 16
topic_6
  WTF: {'living'} {'hotelco'}
topic_7
topic_8
  WTF: {'social'} {'lsd'}
topic_9
  WTF: {'computer'} {'alice'}
topic_10
  WTF: {'balls', 'energy'} {'shafer', 'dryden'}
topic_11
  WTF: {'type'} {'r3'}
topic_12
topic_13
topic_14
  WTF: {'stripped', 'regards'} {'sehari', 'babak'}
topic_15
  WTF: {'immoral', 'deficit', 'maintaining'} {'admistration', 'registries', 'c17'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_16
  WTF: {'uuencode', 'int'} {'xvoid', 'eofnotok'}
topic_17
  WTF: {'headin', 'melody', 'predictionsteam'} {'clementine', 'dykstra', 'yankess'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_18
  WTF: {'vending', 'remixed', 'patchmaking', 'patentable'} {'cola', 'pepsi', 'cocacola', 'yerazunis'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_19
  WTF: {'pw', '0n', 'u0', 'trinomials', 'mh', '644', 'mf', 'm1', 'mj', 'ma', 'begin', 'mm'} {'m3', 'm5', 'o3', 'lu', 'm0', 'mw', 'm9', 'pnospsxop8f', 'e8', 'mx', 'p6', 'm6'}
  WTF?!?!? 12
  WTF?!?!? 12

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f630d3b24f0>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f632964e280>}
{'perplexity': 61986.98046875, 'coherence_20': 1.6415310069667512, 'diversity_euclidean': 0.12003962280800538, 'diversity_jensenshannon': 0.7659496921644611, 'diversity_hellinger': 0.9069866250639116, 'diversity_cosine': 0.8849623942524844, 'fair_ppl_free': 2319.594970703125, 'fair_ppl_fix': 61703.2734375, 'unfair_ppl_banklike': 61986.98046875}
{'num_topics': 21, 'num_common_words': 59415, 'num_model_words': 114951, 'num_bt_words': 97541, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 17, 'lost_bt': 1, 'lost_model': 16}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}]}
8
Num model topics: 21.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
topic_0
topic_1
topic_2
topic_3
  WTF: {'good'} {'nhl'}
topic_4
  WTF: {'like', 'banks'} {'n3jxp', 'gordon'}
topic_5
topic_6
  WTF: {'government', 'ottoman', 'dont', 'started', 'saw', 'know'} {'armenians', 'armenian', 'sumgait', 'turks', 'armenia', 'azerbaijan'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_7
  WTF: {'toolbox', '8800CS', '1795', 'knowlege', 'ringleaders', 'dragdrop', 'Epilepsy', '5152940082', 'CDROMCATZIP', 'CSCSTD00385', 'L2PMABGZ7VAZV0PZRI', 'NikeCajun', 'effortsall', '207556000', 'taxation'} {''}
  WTF?!?!? 15
topic_8
  WTF: {'good', 'management'} {'japan', 'vinge'}
topic_9
topic_10
  WTF: {'social'} {'lsd'}
topic_11
  WTF: {'charged', 'picture'} {'krillean', 'kirlian'}
topic_12
  WTF: {'chemicals', 'tons'} {'shafer', 'dryden'}
topic_13
topic_14
topic_15
  WTF: {'bang'} {'alice'}
topic_16
  WTF: {'stripped', 'regards'} {'sehari', 'babak'}
topic_17
  WTF: {'clinton', 'jobs', 'pork'} {'admistration', 'registries', 'c17'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_18
  WTF: {'promote'} {'fenholt'}
topic_19
  WTF: {'pw', '0n', 'u0', 'trinomials', 'mh', '644', 'mf', 'm1', 'mj', 'ma', 'begin', 'mm'} {'m3', 'm5', 'o3', 'lu', 'm0', 'mw', 'm9', 'pnospsxop8f', 'e8', 'mx', 'p6', 'm6'}
  WTF?!?!? 12
  WTF?!?!? 12
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f6323da82e0>}
Check after fit:
topic_0
topic_1
topic_2
topic_3
  WTF: {'good'} {'nhl'}
topic_4
  WTF: {'like', 'banks'} {'n3jxp', 'gordon'}
topic_5
topic_6
  WTF: {'government', 'ottoman', 'dont', 'started', 'saw', 'know'} {'armenians', 'armenian', 'sumgait', 'turks', 'armenia', 'azerbaijan'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_7
  WTF: {'toolbox', '8800CS', '1795', 'knowlege', 'ringleaders', 'dragdrop', 'Epilepsy', '5152940082', 'CDROMCATZIP', 'CSCSTD00385', 'L2PMABGZ7VAZV0PZRI', 'NikeCajun', 'effortsall', '207556000', 'taxation'} {''}
  WTF?!?!? 15
topic_8
  WTF: {'good', 'management'} {'japan', 'vinge'}
topic_9
topic_10
  WTF: {'social'} {'lsd'}
topic_11
  WTF: {'charged', 'picture'} {'krillean', 'kirlian'}
topic_12
  WTF: {'chemicals', 'tons'} {'shafer', 'dryden'}
topic_13
topic_14
topic_15
  WTF: {'bang'} {'alice'}
topic_16
  WTF: {'stripped', 'regards'} {'sehari', 'babak'}
topic_17
  WTF: {'clinton', 'jobs', 'pork'} {'admistration', 'registries', 'c17'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_18
  WTF: {'promote'} {'fenholt'}
topic_19
  WTF: {'pw', '0n', 'u0', 'trinomials', 'mh', '644', 'mf', 'm1', 'mj', 'ma', 'begin', 'mm'} {'m3', 'm5', 'o3', 'lu', 'm0', 'mw', 'm9', 'pnospsxop8f', 'e8', 'mx', 'p6', 'm6'}
  WTF?!?!? 12
  WTF?!?!? 12

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f6313025f70>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f630d3b7160>}
{'perplexity': 59706.69140625, 'coherence_20': 1.5900737941507737, 'diversity_euclidean': 0.11244587299879637, 'diversity_jensenshannon': 0.7516352604759642, 'diversity_hellinger': 0.8874336728790946, 'diversity_cosine': 0.8628771626237269, 'fair_ppl_free': 2257.6533203125, 'fair_ppl_fix': 59263.92578125, 'unfair_ppl_banklike': 59706.69140625}
{'num_topics': 21, 'num_common_words': 59415, 'num_model_words': 114951, 'num_bt_words': 97541, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 16, 'lost_bt': 1, 'lost_model': 15}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}]}
9
Num model topics: 21.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
topic_0
topic_1
topic_2
  WTF: {'good'} {'nhl'}
topic_3
topic_4
topic_5
  WTF: {'skepticism', 'like'} {'n3jxp', 'gordon'}
topic_6
  WTF: {'government', 'ottoman', 'dont', 'started', 'saw', 'know'} {'armenians', 'armenian', 'sumgait', 'turks', 'armenia', 'azerbaijan'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_7
  WTF: {'toolbox', '8800CS', '1795', 'recollection', 'dragdrop', '5152940082', 'CSCSTD00385', 'CDROMCATZIP', 'L2PMABGZ7VAZV0PZRI', 'NikeCajun', 'effortsall', '207556000', 'NikeDeacon', 'taxation'} {''}
  WTF?!?!? 14
topic_8
topic_9
  WTF: {'social'} {'lsd'}
topic_10
  WTF: {'send', 'hard', 'programming', 'spice'} {'vinge', 'gre', 'vernor', 'gibson'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_11
  WTF: {'fuel'} {'shafer'}
topic_12
  WTF: {'good', '400', 'thanks', 'buy', 'resoltuion', 'satam'} {'paintbrush', 'ocr104zip', 'scanman', 'dexxa', 'ocr', 'mustek'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_13
topic_14
topic_15
  WTF: {'rest'} {'darius'}
topic_16
  WTF: {'stripped', 'regards'} {'sehari', 'babak'}
topic_17
  WTF: {'need', 'utter'} {'admistration', 'registries'}
topic_18
  WTF: {'0099', 'backand', 'patchmaking', 'vending', 'unpatentable'} {'pepsi', 'yerazunis', 'crah', 'cocacola', 'cola'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_19
  WTF: {'publications', 'think', 'licensed', 'science', 'internet', 'journalists', 'promote'} {'dubinski', 'milwaukee', 'marquette', 'doublemajor', 'wi', 'regal', 'robb'}
  WTF?!?!? 7
  WTF?!?!? 7
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f632964ed60>}
Check after fit:
topic_0
topic_1
topic_2
  WTF: {'good'} {'nhl'}
topic_3
topic_4
topic_5
  WTF: {'skepticism', 'like'} {'n3jxp', 'gordon'}
topic_6
  WTF: {'government', 'ottoman', 'dont', 'started', 'saw', 'know'} {'armenians', 'armenian', 'sumgait', 'turks', 'armenia', 'azerbaijan'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_7
  WTF: {'toolbox', '8800CS', '1795', 'recollection', 'dragdrop', '5152940082', 'CSCSTD00385', 'CDROMCATZIP', 'L2PMABGZ7VAZV0PZRI', 'NikeCajun', 'effortsall', '207556000', 'NikeDeacon', 'taxation'} {''}
  WTF?!?!? 14
topic_8
topic_9
  WTF: {'social'} {'lsd'}
topic_10
  WTF: {'send', 'hard', 'programming', 'spice'} {'vinge', 'gre', 'vernor', 'gibson'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_11
  WTF: {'fuel'} {'shafer'}
topic_12
  WTF: {'good', '400', 'thanks', 'buy', 'resoltuion', 'satam'} {'paintbrush', 'ocr104zip', 'scanman', 'dexxa', 'ocr', 'mustek'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_13
topic_14
topic_15
  WTF: {'rest'} {'darius'}
topic_16
  WTF: {'stripped', 'regards'} {'sehari', 'babak'}
topic_17
  WTF: {'need', 'utter'} {'admistration', 'registries'}
topic_18
  WTF: {'0099', 'backand', 'patchmaking', 'vending', 'unpatentable'} {'pepsi', 'yerazunis', 'crah', 'cocacola', 'cola'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_19
  WTF: {'publications', 'think', 'licensed', 'science', 'internet', 'journalists', 'promote'} {'dubinski', 'milwaukee', 'marquette', 'doublemajor', 'wi', 'regal', 'robb'}
  WTF?!?!? 7
  WTF?!?!? 7

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f6312624ca0>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f630fabbd30>}
{'perplexity': 346089.21875, 'coherence_20': 1.7894232128425154, 'diversity_euclidean': 0.1162632545244165, 'diversity_jensenshannon': 0.7555202182756369, 'diversity_hellinger': 0.8921611431892935, 'diversity_cosine': 0.8691254715692927, 'fair_ppl_free': 2273.909912109375, 'fair_ppl_fix': 426315.59375, 'unfair_ppl_banklike': 346089.21875}
{'num_topics': 21, 'num_common_words': 59415, 'num_model_words': 114951, 'num_bt_words': 97541, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 15, 'lost_bt': 1, 'lost_model': 14}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}]}
10
Num model topics: 21.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
topic_0
topic_1
topic_2
topic_3
  WTF: {'good'} {'nhl'}
topic_4
  WTF: {'intellect', 'doctors'} {'n3jxp', 'gordon'}
topic_5
topic_6
  WTF: {'news'} {'o157h7'}
topic_7
  WTF: {'government', 'ottoman', 'dont', 'started', 'saw', 'know'} {'armenians', 'armenian', 'sumgait', 'turks', 'armenia', 'azerbaijan'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_8
  WTF: {'Guideline', 'toolbox', '8800CS', '1795', 'recollection', 'dragdrop', '5152940082', 'CSCSTD00385', 'CDROMCATZIP', 'L2PMABGZ7VAZV0PZRI', 'NikeCajun', 'effortsall', 'divvied', '207556000', 'taxation'} {''}
  WTF?!?!? 15
topic_9
  WTF: {'available', 'management'} {'japan', 'vinge'}
topic_10
topic_11
  WTF: {'social'} {'lsd'}
topic_12
  WTF: {'king'} {'alice'}
topic_13
  WTF: {'type'} {'r3'}
topic_14
  WTF: {'printing', 'russian', 'envoy', 'solve', 'wild', 'mesur', 'translation'} {'iosef', 'orbeli', 'shirak', 'armenian', 'tyukhik', 'anania', 'armenia'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_15
topic_16
  WTF: {'stripped', 'regards'} {'sehari', 'babak'}
topic_17
  WTF: {'abolished', 'immoral', 'bases', 'deficit'} {'c5s', 'admistration', 'registries', 'c17'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_18
  WTF: {'pw', '0n', 'u0', 'trinomials', 'mh', '644', 'mf', 'm1', 'mj', 'ma', 'begin', 'mm'} {'m3', 'm5', 'o3', 'lu', 'm0', 'mw', 'm9', 'pnospsxop8f', 'e8', 'mx', 'p6', 'm6'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_19
  WTF: {'returned', 'just', 'tube'} {'hifi', 'emerson', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f63298dc700>}
Check after fit:
topic_0
topic_1
topic_2
topic_3
  WTF: {'good'} {'nhl'}
topic_4
  WTF: {'intellect', 'doctors'} {'n3jxp', 'gordon'}
topic_5
topic_6
  WTF: {'news'} {'o157h7'}
topic_7
  WTF: {'government', 'ottoman', 'dont', 'started', 'saw', 'know'} {'armenians', 'armenian', 'sumgait', 'turks', 'armenia', 'azerbaijan'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_8
  WTF: {'Guideline', 'toolbox', '8800CS', '1795', 'recollection', 'dragdrop', '5152940082', 'CSCSTD00385', 'CDROMCATZIP', 'L2PMABGZ7VAZV0PZRI', 'NikeCajun', 'effortsall', 'divvied', '207556000', 'taxation'} {''}
  WTF?!?!? 15
topic_9
  WTF: {'available', 'management'} {'japan', 'vinge'}
topic_10
topic_11
  WTF: {'social'} {'lsd'}
topic_12
  WTF: {'king'} {'alice'}
topic_13
  WTF: {'type'} {'r3'}
topic_14
  WTF: {'printing', 'russian', 'envoy', 'solve', 'wild', 'mesur', 'translation'} {'iosef', 'orbeli', 'shirak', 'armenian', 'tyukhik', 'anania', 'armenia'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_15
topic_16
  WTF: {'stripped', 'regards'} {'sehari', 'babak'}
topic_17
  WTF: {'abolished', 'immoral', 'bases', 'deficit'} {'c5s', 'admistration', 'registries', 'c17'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_18
  WTF: {'pw', '0n', 'u0', 'trinomials', 'mh', '644', 'mf', 'm1', 'mj', 'ma', 'begin', 'mm'} {'m3', 'm5', 'o3', 'lu', 'm0', 'mw', 'm9', 'pnospsxop8f', 'e8', 'mx', 'p6', 'm6'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_19
  WTF: {'returned', 'just', 'tube'} {'hifi', 'emerson', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f632944bdf0>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f63297dbb20>}
{'perplexity': 59860.1328125, 'coherence_20': 1.537821297576474, 'diversity_euclidean': 0.10309709161278169, 'diversity_jensenshannon': 0.7437013480547396, 'diversity_hellinger': 0.8770958421762005, 'diversity_cosine': 0.8442821084191366, 'fair_ppl_free': 2242.21240234375, 'fair_ppl_fix': 59465.4140625, 'unfair_ppl_banklike': 59860.1328125}
{'num_topics': 21, 'num_common_words': 59415, 'num_model_words': 114951, 'num_bt_words': 97541, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 16, 'lost_bt': 1, 'lost_model': 15}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}]}
11
Num model topics: 21.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
topic_0
topic_1
topic_2
  WTF: {'good'} {'nhl'}
topic_3
  WTF: {'know', 'doctors'} {'n3jxp', 'gordon'}
topic_4
  WTF: {'government', 'ottoman', 'dont', 'started', 'saw', 'know'} {'armenians', 'armenian', 'sumgait', 'turks', 'armenia', 'azerbaijan'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_5
  WTF: {'toolbox', '8800CS', 'haunt', '1795', 'recollection', 'dragdrop', '5152940082', 'CSCSTD00385', 'CDROMCATZIP', 'L2PMABGZ7VAZV0PZRI', 'NikeCajun', 'effortsall', '207556000', 'taxation'} {''}
  WTF?!?!? 14
topic_6
topic_7
  WTF: {'social'} {'lsd'}
topic_8
  WTF: {'vol', '02106chopinudeledu', 'molecular', 'manual'} {'baen', 'vinge', 'vernor', 'gibson'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_9
  WTF: {'type'} {'r3'}
topic_10
  WTF: {'grayscales', 'cytoskeleton', 'satam', 'resoltuion'} {'ocr', 'scanman', 'paintbrush', 'mustek'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_11
topic_12
topic_13
  WTF: {'dia', 'used', 'facilities', 'use'} {'russia', 't4', 'energiam', 't4centaur'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_14
  WTF: {'stripped', 'regards'} {'sehari', 'babak'}
topic_15
  WTF: {'theory'} {'alice'}
topic_16
  WTF: {'pw', 'mb', '0n', 'u0', 'trinomials', 'mh', '644', 'mf', 'm1', 'mj', 'ma', 'mm'} {'m3', 'm5', 'o3', 'lu', 'm0', 'mw', 'm9', 'pnospsxop8f', 'e8', 'mx', 'p6', 'm6'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_17
  WTF: {'powers', 'returned', 'just'} {'hifi', 'emerson', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_18
  WTF: {'organization', 'university', 'incribed', 'include', 'wish', 'mr', 'promote'} {'dubinski', 'milwaukee', 'marquette', 'doublemajor', 'wi', 'regal', 'robb'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_19
  WTF: {'telex', 'hope', 'laserdisc', 'received', 'abyss', 'raylauffastrotempleedu', 'simplicitys'} {'filmtransmtl', 'h2y', 'nobles', 'cbsfox', '1c8', 'lauff', 'zeitgeist'}
  WTF?!?!? 7
  WTF?!?!? 7
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f63298a8400>}
Check after fit:
topic_0
topic_1
topic_2
  WTF: {'good'} {'nhl'}
topic_3
  WTF: {'know', 'doctors'} {'n3jxp', 'gordon'}
topic_4
  WTF: {'government', 'ottoman', 'dont', 'started', 'saw', 'know'} {'armenians', 'armenian', 'sumgait', 'turks', 'armenia', 'azerbaijan'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_5
  WTF: {'toolbox', '8800CS', 'haunt', '1795', 'recollection', 'dragdrop', '5152940082', 'CSCSTD00385', 'CDROMCATZIP', 'L2PMABGZ7VAZV0PZRI', 'NikeCajun', 'effortsall', '207556000', 'taxation'} {''}
  WTF?!?!? 14
topic_6
topic_7
  WTF: {'social'} {'lsd'}
topic_8
  WTF: {'vol', '02106chopinudeledu', 'molecular', 'manual'} {'baen', 'vinge', 'vernor', 'gibson'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_9
  WTF: {'type'} {'r3'}
topic_10
  WTF: {'grayscales', 'cytoskeleton', 'satam', 'resoltuion'} {'ocr', 'scanman', 'paintbrush', 'mustek'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_11
topic_12
topic_13
  WTF: {'dia', 'used', 'facilities', 'use'} {'russia', 't4', 'energiam', 't4centaur'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_14
  WTF: {'stripped', 'regards'} {'sehari', 'babak'}
topic_15
  WTF: {'theory'} {'alice'}
topic_16
  WTF: {'pw', 'mb', '0n', 'u0', 'trinomials', 'mh', '644', 'mf', 'm1', 'mj', 'ma', 'mm'} {'m3', 'm5', 'o3', 'lu', 'm0', 'mw', 'm9', 'pnospsxop8f', 'e8', 'mx', 'p6', 'm6'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_17
  WTF: {'powers', 'returned', 'just'} {'hifi', 'emerson', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_18
  WTF: {'organization', 'university', 'incribed', 'include', 'wish', 'mr', 'promote'} {'dubinski', 'milwaukee', 'marquette', 'doublemajor', 'wi', 'regal', 'robb'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_19
  WTF: {'telex', 'hope', 'laserdisc', 'received', 'abyss', 'raylauffastrotempleedu', 'simplicitys'} {'filmtransmtl', 'h2y', 'nobles', 'cbsfox', '1c8', 'lauff', 'zeitgeist'}
  WTF?!?!? 7
  WTF?!?!? 7

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f63298c7d60>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f6344b04a00>}
{'perplexity': 64648.15234375, 'coherence_20': 1.4154674871522945, 'diversity_euclidean': 0.12258966598754108, 'diversity_jensenshannon': 0.7745382754450859, 'diversity_hellinger': 0.9174547628752739, 'diversity_cosine': 0.8966865239606705, 'fair_ppl_free': 2361.895263671875, 'fair_ppl_fix': 64159.4140625, 'unfair_ppl_banklike': 64648.15234375}
{'num_topics': 21, 'num_common_words': 59415, 'num_model_words': 114951, 'num_bt_words': 97541, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 15, 'lost_bt': 1, 'lost_model': 14}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}]}
12
Num model topics: 21.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
topic_0
topic_1
topic_2
  WTF: {'good'} {'nhl'}
topic_3
  WTF: {'doctors', 'banks'} {'n3jxp', 'gordon'}
topic_4
  WTF: {'government', 'ottoman', 'dont', 'started', 'saw', 'know'} {'armenians', 'armenian', 'sumgait', 'turks', 'armenia', 'azerbaijan'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_5
  WTF: {'toolbox', '1795', 'JH2SC281XPM100187', 'knowlege', 'dragdrop', '5152940082', 'CSCSTD00385', 'CDROMCATZIP', 'monthly', 'Guideline', '8800CS', 'ringleaders', 'L2PMABGZ7VAZV0PZRI', 'NikeCajun', 'effortsall', '207556000', 'taxation'} {''}
  WTF?!?!? 17
topic_6
  WTF: {'412', 'management'} {'gre', 'vinge'}
topic_7
topic_8
  WTF: {'social'} {'lsd'}
topic_9
topic_10
  WTF: {'grayscales', 'cytoskeleton', 'satam', 'resoltuion'} {'ocr', 'scanman', 'paintbrush', 'mustek'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_11
topic_12
  WTF: {'abolished', 'immoral', 'bases', 'deficit'} {'c5s', 'admistration', 'registries', 'c17'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_13
  WTF: {'stripped', 'regards'} {'sehari', 'babak'}
topic_14
  WTF: {'theory'} {'alice'}
topic_15
  WTF: {'exponents'} {'scotyy'}
topic_16
  WTF: {'student', '153955', 'culture', 'happy'} {'palace', 'shul', 'gainesville', 'nozyk'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_17
  WTF: {'bobkc2wzbubbleorg', 'backand', '07090', 'patentable', 'altfolkloreurban', 'uunetkc2wzbob'} {'pepsi', 'yerazunis', 'crah', 'cocacola', 'cola', 'billson'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_18
  WTF: {'know', 'used', 'stabilized', 'combo'} {'russia', 't4', 'energiam', 't4centaur'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_19
  WTF: {'pw', '0n', 'u0', 'trinomials', 'mh', '644', 'mf', 'm1', 'mj', 'ma', 'begin', 'mm'} {'m3', 'm5', 'o3', 'lu', 'm0', 'mw', 'm9', 'pnospsxop8f', 'e8', 'mx', 'p6', 'm6'}
  WTF?!?!? 12
  WTF?!?!? 12
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f63123c4970>}
Check after fit:
topic_0
topic_1
topic_2
  WTF: {'good'} {'nhl'}
topic_3
  WTF: {'doctors', 'banks'} {'n3jxp', 'gordon'}
topic_4
  WTF: {'government', 'ottoman', 'dont', 'started', 'saw', 'know'} {'armenians', 'armenian', 'sumgait', 'turks', 'armenia', 'azerbaijan'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_5
  WTF: {'toolbox', '1795', 'JH2SC281XPM100187', 'knowlege', 'dragdrop', '5152940082', 'CSCSTD00385', 'CDROMCATZIP', 'monthly', 'Guideline', '8800CS', 'ringleaders', 'L2PMABGZ7VAZV0PZRI', 'NikeCajun', 'effortsall', '207556000', 'taxation'} {''}
  WTF?!?!? 17
topic_6
  WTF: {'412', 'management'} {'gre', 'vinge'}
topic_7
topic_8
  WTF: {'social'} {'lsd'}
topic_9
topic_10
  WTF: {'grayscales', 'cytoskeleton', 'satam', 'resoltuion'} {'ocr', 'scanman', 'paintbrush', 'mustek'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_11
topic_12
  WTF: {'abolished', 'immoral', 'bases', 'deficit'} {'c5s', 'admistration', 'registries', 'c17'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_13
  WTF: {'stripped', 'regards'} {'sehari', 'babak'}
topic_14
  WTF: {'theory'} {'alice'}
topic_15
  WTF: {'exponents'} {'scotyy'}
topic_16
  WTF: {'student', '153955', 'culture', 'happy'} {'palace', 'shul', 'gainesville', 'nozyk'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_17
  WTF: {'bobkc2wzbubbleorg', 'backand', '07090', 'patentable', 'altfolkloreurban', 'uunetkc2wzbob'} {'pepsi', 'yerazunis', 'crah', 'cocacola', 'cola', 'billson'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_18
  WTF: {'know', 'used', 'stabilized', 'combo'} {'russia', 't4', 'energiam', 't4centaur'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_19
  WTF: {'pw', '0n', 'u0', 'trinomials', 'mh', '644', 'mf', 'm1', 'mj', 'ma', 'begin', 'mm'} {'m3', 'm5', 'o3', 'lu', 'm0', 'mw', 'm9', 'pnospsxop8f', 'e8', 'mx', 'p6', 'm6'}
  WTF?!?!? 12
  WTF?!?!? 12

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f6323a6c820>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f63298a8400>}
{'perplexity': 62173.67578125, 'coherence_20': 1.4456143379844884, 'diversity_euclidean': 0.13553944458083136, 'diversity_jensenshannon': 0.7743805760223453, 'diversity_hellinger': 0.9172793804232777, 'diversity_cosine': 0.8962632141533349, 'fair_ppl_free': 2350.655517578125, 'fair_ppl_fix': 61865.69140625, 'unfair_ppl_banklike': 62173.67578125}
{'num_topics': 21, 'num_common_words': 59415, 'num_model_words': 114951, 'num_bt_words': 97541, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 18, 'lost_bt': 1, 'lost_model': 17}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}]}
13
Num model topics: 21.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
topic_0
topic_1
topic_2
topic_3
  WTF: {'good'} {'nhl'}
topic_4
topic_5
  WTF: {'doctors', 'banks'} {'n3jxp', 'gordon'}
topic_6
  WTF: {'government', 'ottoman', 'dont', 'started', 'saw', 'know'} {'armenians', 'armenian', 'sumgait', 'turks', 'armenia', 'azerbaijan'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_7
  WTF: {'toolbox', '8800CS', '1795', 'recollection', 'dragdrop', '5152940082', 'CSCSTD00385', 'CDROMCATZIP', 'L2PMABGZ7VAZV0PZRI', 'NikeCajun', 'effortsall', '207556000', 'NikeDeacon', 'taxation'} {''}
  WTF?!?!? 14
topic_8
topic_9
  WTF: {'social'} {'lsd'}
topic_10
  WTF: {'vol', '02106chopinudeledu', 'molecular', 'manual'} {'baen', 'vinge', 'vernor', 'gibson'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_11
topic_12
  WTF: {'auras', 'appartus'} {'krillean', 'kirlian'}
topic_13
  WTF: {'uuencode', 'int'} {'xvoid', 'eofnotok'}
topic_14
  WTF: {'stripped', 'regards'} {'sehari', 'babak'}
topic_15
  WTF: {'abolished', 'immoral', 'bases', 'deficit'} {'c5s', 'admistration', 'registries', 'c17'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_16
topic_17
  WTF: {'theory'} {'alice'}
topic_18
  WTF: {'8177', 'remember', 'rebel', 'rednecks', 'giveaway', 'phone', 'soar'} {'yogi', 'bandit', 'mcqueen', 'pgh', 'yogis', 'smokey', 'thumper'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_19
  WTF: {'120mph', 'boondoggle', 'publics'} {'houston', 'lubbock', 'dallas'}
  WTF?!?!? 3
  WTF?!?!? 3
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f630fadec70>}
Check after fit:
topic_0
topic_1
topic_2
topic_3
  WTF: {'good'} {'nhl'}
topic_4
topic_5
  WTF: {'doctors', 'banks'} {'n3jxp', 'gordon'}
topic_6
  WTF: {'government', 'ottoman', 'dont', 'started', 'saw', 'know'} {'armenians', 'armenian', 'sumgait', 'turks', 'armenia', 'azerbaijan'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_7
  WTF: {'toolbox', '8800CS', '1795', 'recollection', 'dragdrop', '5152940082', 'CSCSTD00385', 'CDROMCATZIP', 'L2PMABGZ7VAZV0PZRI', 'NikeCajun', 'effortsall', '207556000', 'NikeDeacon', 'taxation'} {''}
  WTF?!?!? 14
topic_8
topic_9
  WTF: {'social'} {'lsd'}
topic_10
  WTF: {'vol', '02106chopinudeledu', 'molecular', 'manual'} {'baen', 'vinge', 'vernor', 'gibson'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_11
topic_12
  WTF: {'auras', 'appartus'} {'krillean', 'kirlian'}
topic_13
  WTF: {'uuencode', 'int'} {'xvoid', 'eofnotok'}
topic_14
  WTF: {'stripped', 'regards'} {'sehari', 'babak'}
topic_15
  WTF: {'abolished', 'immoral', 'bases', 'deficit'} {'c5s', 'admistration', 'registries', 'c17'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_16
topic_17
  WTF: {'theory'} {'alice'}
topic_18
  WTF: {'8177', 'remember', 'rebel', 'rednecks', 'giveaway', 'phone', 'soar'} {'yogi', 'bandit', 'mcqueen', 'pgh', 'yogis', 'smokey', 'thumper'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_19
  WTF: {'120mph', 'boondoggle', 'publics'} {'houston', 'lubbock', 'dallas'}
  WTF?!?!? 3
  WTF?!?!? 3

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f62feece760>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f62fefafca0>}
{'perplexity': 401359.59375, 'coherence_20': 1.8875729624300859, 'diversity_euclidean': 0.115553223225278, 'diversity_jensenshannon': 0.7578785526954639, 'diversity_hellinger': 0.8947547352392732, 'diversity_cosine': 0.8692175504946094, 'fair_ppl_free': 2249.280517578125, 'fair_ppl_fix': 263690.34375, 'unfair_ppl_banklike': 401359.59375}
{'num_topics': 21, 'num_common_words': 59415, 'num_model_words': 114951, 'num_bt_words': 97541, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 15, 'lost_bt': 1, 'lost_model': 14}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}]}
14
Num model topics: 21.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
topic_0
topic_1
topic_2
  WTF: {'good'} {'nhl'}
topic_3
  WTF: {'skepticism', 'banks'} {'n3jxp', 'gordon'}
topic_4
  WTF: {'government', 'ottoman', 'dont', 'started', 'saw', 'know'} {'armenians', 'armenian', 'sumgait', 'turks', 'armenia', 'azerbaijan'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_5
  WTF: {'toolbox', '8800CS', '1795', 'knowlege', 'ringleaders', 'dragdrop', 'Epilepsy', '5152940082', 'CDROMCATZIP', 'CSCSTD00385', 'L2PMABGZ7VAZV0PZRI', 'NikeCajun', 'effortsall', '207556000', 'taxation'} {''}
  WTF?!?!? 15
topic_6
topic_7
  WTF: {'social'} {'lsd'}
topic_8
  WTF: {'vol', 'molecular', 'manual', 'writing'} {'baen', 'vinge', 'vernor', 'gibson'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_9
topic_10
topic_11
  WTF: {'year', 'tutorial', 'participants', 'conference'} {'mellon', 'japan', 'carnegie', 'jstmp'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_12
  WTF: {'stripped', 'regards'} {'sehari', 'babak'}
topic_13
  WTF: {'mit', 'nick', 'offroad'} {'cambridge', 'sept', 'quincy'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_14
  WTF: {'computer', 'rule', 'bang'} {'adams', 'douglas', 'alice'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_15
  WTF: {'utter', 'commission', 'axe'} {'admistration', 'registries', 'irs'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_16
  WTF: {'pw', 'mb', '0n', 'u0', 'trinomials', 'mh', '644', 'mf', 'm1', 'mj', 'ma', 'mm'} {'m3', 'm5', 'o3', 'lu', 'm0', 'mw', 'm9', 'pnospsxop8f', 'e8', 'mx', 'p6', 'm6'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_17
  WTF: {'uuencode', 'int'} {'xvoid', 'eofnotok'}
topic_18
  WTF: {'changing', 'hes', 'roam', 'predictionsteam', 'somethin'} {'yankess', 'ballad', 'anime', 'subterranean', 'dykstra'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_19
  WTF: {'1080', 'mole'} {'menuts', 'avagadros'}
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f6344b04a00>}
Check after fit:
topic_0
topic_1
topic_2
  WTF: {'good'} {'nhl'}
topic_3
  WTF: {'skepticism', 'banks'} {'n3jxp', 'gordon'}
topic_4
  WTF: {'government', 'ottoman', 'dont', 'started', 'saw', 'know'} {'armenians', 'armenian', 'sumgait', 'turks', 'armenia', 'azerbaijan'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_5
  WTF: {'toolbox', '8800CS', '1795', 'knowlege', 'ringleaders', 'dragdrop', 'Epilepsy', '5152940082', 'CDROMCATZIP', 'CSCSTD00385', 'L2PMABGZ7VAZV0PZRI', 'NikeCajun', 'effortsall', '207556000', 'taxation'} {''}
  WTF?!?!? 15
topic_6
topic_7
  WTF: {'social'} {'lsd'}
topic_8
  WTF: {'vol', 'molecular', 'manual', 'writing'} {'baen', 'vinge', 'vernor', 'gibson'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_9
topic_10
topic_11
  WTF: {'year', 'tutorial', 'participants', 'conference'} {'mellon', 'japan', 'carnegie', 'jstmp'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_12
  WTF: {'stripped', 'regards'} {'sehari', 'babak'}
topic_13
  WTF: {'mit', 'nick', 'offroad'} {'cambridge', 'sept', 'quincy'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_14
  WTF: {'computer', 'rule', 'bang'} {'adams', 'douglas', 'alice'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_15
  WTF: {'utter', 'commission', 'axe'} {'admistration', 'registries', 'irs'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_16
  WTF: {'pw', 'mb', '0n', 'u0', 'trinomials', 'mh', '644', 'mf', 'm1', 'mj', 'ma', 'mm'} {'m3', 'm5', 'o3', 'lu', 'm0', 'mw', 'm9', 'pnospsxop8f', 'e8', 'mx', 'p6', 'm6'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_17
  WTF: {'uuencode', 'int'} {'xvoid', 'eofnotok'}
topic_18
  WTF: {'changing', 'hes', 'roam', 'predictionsteam', 'somethin'} {'yankess', 'ballad', 'anime', 'subterranean', 'dykstra'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_19
  WTF: {'1080', 'mole'} {'menuts', 'avagadros'}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f632964ed60>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f63298b70d0>}
{'perplexity': 65811.671875, 'coherence_20': 1.5844644939398354, 'diversity_euclidean': 0.12589684910484852, 'diversity_jensenshannon': 0.7755066779816622, 'diversity_hellinger': 0.9192447165024212, 'diversity_cosine': 0.9026022218034493, 'fair_ppl_free': 2350.2236328125, 'fair_ppl_fix': 65134.98828125, 'unfair_ppl_banklike': 65811.671875}
{'num_topics': 21, 'num_common_words': 59415, 'num_model_words': 114951, 'num_bt_words': 97541, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 16, 'lost_bt': 1, 'lost_model': 15}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}]}
15
Num model topics: 21.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
topic_0
topic_1
topic_2
  WTF: {'good'} {'nhl'}
topic_3
topic_4
  WTF: {'know', 'doctors'} {'n3jxp', 'gordon'}
topic_5
  WTF: {'government', 'ottoman', 'dont', 'started', 'saw', 'know'} {'armenians', 'armenian', 'sumgait', 'turks', 'armenia', 'azerbaijan'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_6
  WTF: {'toolbox', '8800CS', '1795', 'knowlege', 'ringleaders', 'dragdrop', 'Epilepsy', '5152940082', 'CDROMCATZIP', 'CSCSTD00385', 'L2PMABGZ7VAZV0PZRI', 'NikeCajun', 'effortsall', '207556000', 'taxation'} {''}
  WTF?!?!? 15
topic_7
topic_8
  WTF: {'good', 'management'} {'japan', 'vinge'}
topic_9
  WTF: {'social'} {'lsd'}
topic_10
topic_11
  WTF: {'mail'} {'r3'}
topic_12
  WTF: {'grayscales', 'cytoskeleton', 'satam', 'resoltuion'} {'ocr', 'scanman', 'paintbrush', 'mustek'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_13
topic_14
  WTF: {'computer', 'rule', 'forget'} {'adams', 'douglas', 'alice'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_15
  WTF: {'stripped', 'regards'} {'sehari', 'babak'}
topic_16
  WTF: {'vending', 'unpatentable', 'equipment'} {'cola', 'pepsi', 'cocacola'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_17
  WTF: {'know', 'used', 'stabilized', 'combo'} {'russia', 't4', 'energiam', 't4centaur'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_18
  WTF: {'attitute', 'hell', 'deluded', 'lunacy', 'pinks', 'nicht', 'goofball', 'alle'} {'koph', 'dobbsapproved', 'hoffnung', 'thedoge', 'condupes', 'turc', 'conspiratortm', 'zeuge'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_19
  WTF: {'pw', '0n', 'u0', 'trinomials', 'mh', '644', 'mf', 'm1', 'mj', 'ma', 'begin', 'mm'} {'m3', 'm5', 'o3', 'lu', 'm0', 'mw', 'm9', 'pnospsxop8f', 'e8', 'mx', 'p6', 'm6'}
  WTF?!?!? 12
  WTF?!?!? 12
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f630fe93940>}
Check after fit:
topic_0
topic_1
topic_2
  WTF: {'good'} {'nhl'}
topic_3
topic_4
  WTF: {'know', 'doctors'} {'n3jxp', 'gordon'}
topic_5
  WTF: {'government', 'ottoman', 'dont', 'started', 'saw', 'know'} {'armenians', 'armenian', 'sumgait', 'turks', 'armenia', 'azerbaijan'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_6
  WTF: {'toolbox', '8800CS', '1795', 'knowlege', 'ringleaders', 'dragdrop', 'Epilepsy', '5152940082', 'CDROMCATZIP', 'CSCSTD00385', 'L2PMABGZ7VAZV0PZRI', 'NikeCajun', 'effortsall', '207556000', 'taxation'} {''}
  WTF?!?!? 15
topic_7
topic_8
  WTF: {'good', 'management'} {'japan', 'vinge'}
topic_9
  WTF: {'social'} {'lsd'}
topic_10
topic_11
  WTF: {'mail'} {'r3'}
topic_12
  WTF: {'grayscales', 'cytoskeleton', 'satam', 'resoltuion'} {'ocr', 'scanman', 'paintbrush', 'mustek'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_13
topic_14
  WTF: {'computer', 'rule', 'forget'} {'adams', 'douglas', 'alice'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_15
  WTF: {'stripped', 'regards'} {'sehari', 'babak'}
topic_16
  WTF: {'vending', 'unpatentable', 'equipment'} {'cola', 'pepsi', 'cocacola'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_17
  WTF: {'know', 'used', 'stabilized', 'combo'} {'russia', 't4', 'energiam', 't4centaur'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_18
  WTF: {'attitute', 'hell', 'deluded', 'lunacy', 'pinks', 'nicht', 'goofball', 'alle'} {'koph', 'dobbsapproved', 'hoffnung', 'thedoge', 'condupes', 'turc', 'conspiratortm', 'zeuge'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_19
  WTF: {'pw', '0n', 'u0', 'trinomials', 'mh', '644', 'mf', 'm1', 'mj', 'ma', 'begin', 'mm'} {'m3', 'm5', 'o3', 'lu', 'm0', 'mw', 'm9', 'pnospsxop8f', 'e8', 'mx', 'p6', 'm6'}
  WTF?!?!? 12
  WTF?!?!? 12

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f6305b7b520>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f6323da8940>}
{'perplexity': 60964.1484375, 'coherence_20': 1.5936113866016572, 'diversity_euclidean': 0.12275905459860621, 'diversity_jensenshannon': 0.7644996120481171, 'diversity_hellinger': 0.904429241003587, 'diversity_cosine': 0.8838247964330604, 'fair_ppl_free': 2305.083251953125, 'fair_ppl_fix': 60581.50390625, 'unfair_ppl_banklike': 60964.1484375}
{'num_topics': 21, 'num_common_words': 59415, 'num_model_words': 114951, 'num_bt_words': 97541, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 16, 'lost_bt': 1, 'lost_model': 15}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}]}
16
Num model topics: 21.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
topic_0
topic_1
topic_2
topic_3
  WTF: {'good'} {'nhl'}
topic_4
  WTF: {'like', 'banks'} {'n3jxp', 'gordon'}
topic_5
  WTF: {'government', 'ottoman', 'dont', 'started', 'saw', 'know'} {'armenians', 'armenian', 'sumgait', 'turks', 'armenia', 'azerbaijan'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_6
  WTF: {'toolbox', '8800CS', '1795', 'recollection', 'dragdrop', '5152940082', 'CSCSTD00385', 'CDROMCATZIP', 'L2PMABGZ7VAZV0PZRI', 'NikeCajun', 'effortsall', '207556000', 'NikeDeacon', 'taxation'} {''}
  WTF?!?!? 14
topic_7
topic_8
  WTF: {'social'} {'lsd'}
topic_9
topic_10
  WTF: {'deep', 'like', 'thermometer'} {'adams', 'douglas', 'alice'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_11
  WTF: {'intrinsics'} {'r3'}
topic_12
  WTF: {'charged', 'picture'} {'krillean', 'kirlian'}
topic_13
topic_14
  WTF: {'stripped', 'regards'} {'sehari', 'babak'}
topic_15
  WTF: {'clinton', 'jobs', 'pork'} {'admistration', 'registries', 'c17'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_16
topic_17
  WTF: {'tension', 'tunnel', 'carpal', 'm4'} {'m3', 'm5', 'rsi', 'mw'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_18
  WTF: {'vending', 'remixed', 'patchmaking', 'patentable'} {'cola', 'pepsi', 'cocacola', 'yerazunis'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_19
  WTF: {'nazism', 'moments', 'dem', 'utilize', 'mr', 'oddly', 'ya'} {'koph', 'hoffnung', 'davidssons', 'srinivas', 'turc', 'zeuge', 'timucin'}
  WTF?!?!? 7
  WTF?!?!? 7
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f6312ca07c0>}
Check after fit:
topic_0
topic_1
topic_2
topic_3
  WTF: {'good'} {'nhl'}
topic_4
  WTF: {'like', 'banks'} {'n3jxp', 'gordon'}
topic_5
  WTF: {'government', 'ottoman', 'dont', 'started', 'saw', 'know'} {'armenians', 'armenian', 'sumgait', 'turks', 'armenia', 'azerbaijan'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_6
  WTF: {'toolbox', '8800CS', '1795', 'recollection', 'dragdrop', '5152940082', 'CSCSTD00385', 'CDROMCATZIP', 'L2PMABGZ7VAZV0PZRI', 'NikeCajun', 'effortsall', '207556000', 'NikeDeacon', 'taxation'} {''}
  WTF?!?!? 14
topic_7
topic_8
  WTF: {'social'} {'lsd'}
topic_9
topic_10
  WTF: {'deep', 'like', 'thermometer'} {'adams', 'douglas', 'alice'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_11
  WTF: {'intrinsics'} {'r3'}
topic_12
  WTF: {'charged', 'picture'} {'krillean', 'kirlian'}
topic_13
topic_14
  WTF: {'stripped', 'regards'} {'sehari', 'babak'}
topic_15
  WTF: {'clinton', 'jobs', 'pork'} {'admistration', 'registries', 'c17'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_16
topic_17
  WTF: {'tension', 'tunnel', 'carpal', 'm4'} {'m3', 'm5', 'rsi', 'mw'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_18
  WTF: {'vending', 'remixed', 'patchmaking', 'patentable'} {'cola', 'pepsi', 'cocacola', 'yerazunis'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_19
  WTF: {'nazism', 'moments', 'dem', 'utilize', 'mr', 'oddly', 'ya'} {'koph', 'hoffnung', 'davidssons', 'srinivas', 'turc', 'zeuge', 'timucin'}
  WTF?!?!? 7
  WTF?!?!? 7

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f6312ca0f40>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f63296077c0>}
{'perplexity': 140448.140625, 'coherence_20': 1.807210462627682, 'diversity_euclidean': 0.11630912130771853, 'diversity_jensenshannon': 0.7609583292612505, 'diversity_hellinger': 0.8999011583246643, 'diversity_cosine': 0.8772766215660629, 'fair_ppl_free': 2296.708740234375, 'fair_ppl_fix': 140155.078125, 'unfair_ppl_banklike': 140448.140625}
{'num_topics': 21, 'num_common_words': 59415, 'num_model_words': 114951, 'num_bt_words': 97541, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 15, 'lost_bt': 1, 'lost_model': 14}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}]}
17
Num model topics: 21.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
topic_0
topic_1
topic_2
topic_3
  WTF: {'good'} {'nhl'}
topic_4
  WTF: {'doctors', 'banks'} {'n3jxp', 'gordon'}
topic_5
  WTF: {'government', 'ottoman', 'dont', 'started', 'saw', 'know'} {'armenians', 'armenian', 'sumgait', 'turks', 'armenia', 'azerbaijan'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_6
  WTF: {'toolbox', '1795', 'JH2SC281XPM100187', 'knowlege', 'dragdrop', '5152940082', 'CSCSTD00385', 'CDROMCATZIP', 'monthly', 'Guideline', '8800CS', 'recollection', 'strobe', 'L2PMABGZ7VAZV0PZRI', 'NikeCajun', 'effortsall', '207556000', 'taxation'} {''}
  WTF?!?!? 18
topic_7
topic_8
  WTF: {'social'} {'lsd'}
topic_9
topic_10
  WTF: {'vol', 'molecular', 'manual', 'writing'} {'baen', 'vinge', 'vernor', 'gibson'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_11
  WTF: {'type'} {'r3'}
topic_12
  WTF: {'andrew', 'cs', 'year', 'students'} {'mellon', 'japan', 'carnegie', 'jstmp'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_13
topic_14
  WTF: {'charged', 'picture'} {'krillean', 'kirlian'}
topic_15
  WTF: {'stripped', 'regards'} {'sehari', 'babak'}
topic_16
  WTF: {'clinton', 'jobs', 'pork'} {'admistration', 'registries', 'c17'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_17
  WTF: {'theory'} {'alice'}
topic_18
  WTF: {'pw', '0n', 'u0', 'trinomials', 'mh', '644', 'et', 'mf', 'm1', 'mj', 'ma', 'mm'} {'m3', 'gh', 'm5', 'o3', 'm0', 'mw', 'm9', 'pnospsxop8f', 'e8', 'mx', 'p6', 'm6'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_19
  WTF: {'design', 'cover', 'ideas'} {'cola', 'yerazunis', 'crah'}
  WTF?!?!? 3
  WTF?!?!? 3
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f6312624c40>}
Check after fit:
topic_0
topic_1
topic_2
topic_3
  WTF: {'good'} {'nhl'}
topic_4
  WTF: {'doctors', 'banks'} {'n3jxp', 'gordon'}
topic_5
  WTF: {'government', 'ottoman', 'dont', 'started', 'saw', 'know'} {'armenians', 'armenian', 'sumgait', 'turks', 'armenia', 'azerbaijan'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_6
  WTF: {'toolbox', '1795', 'JH2SC281XPM100187', 'knowlege', 'dragdrop', '5152940082', 'CSCSTD00385', 'CDROMCATZIP', 'monthly', 'Guideline', '8800CS', 'recollection', 'strobe', 'L2PMABGZ7VAZV0PZRI', 'NikeCajun', 'effortsall', '207556000', 'taxation'} {''}
  WTF?!?!? 18
topic_7
topic_8
  WTF: {'social'} {'lsd'}
topic_9
topic_10
  WTF: {'vol', 'molecular', 'manual', 'writing'} {'baen', 'vinge', 'vernor', 'gibson'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_11
  WTF: {'type'} {'r3'}
topic_12
  WTF: {'andrew', 'cs', 'year', 'students'} {'mellon', 'japan', 'carnegie', 'jstmp'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_13
topic_14
  WTF: {'charged', 'picture'} {'krillean', 'kirlian'}
topic_15
  WTF: {'stripped', 'regards'} {'sehari', 'babak'}
topic_16
  WTF: {'clinton', 'jobs', 'pork'} {'admistration', 'registries', 'c17'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_17
  WTF: {'theory'} {'alice'}
topic_18
  WTF: {'pw', '0n', 'u0', 'trinomials', 'mh', '644', 'et', 'mf', 'm1', 'mj', 'ma', 'mm'} {'m3', 'gh', 'm5', 'o3', 'm0', 'mw', 'm9', 'pnospsxop8f', 'e8', 'mx', 'p6', 'm6'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_19
  WTF: {'design', 'cover', 'ideas'} {'cola', 'yerazunis', 'crah'}
  WTF?!?!? 3
  WTF?!?!? 3

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f630d39af70>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f63296c0e50>}
{'perplexity': 64771.984375, 'coherence_20': 1.6561368182589993, 'diversity_euclidean': 0.13870181279578206, 'diversity_jensenshannon': 0.7610105431868573, 'diversity_hellinger': 0.9000518150222149, 'diversity_cosine': 0.8798651822529638, 'fair_ppl_free': 2302.51123046875, 'fair_ppl_fix': 64460.39453125, 'unfair_ppl_banklike': 64771.984375}
{'num_topics': 21, 'num_common_words': 59415, 'num_model_words': 114951, 'num_bt_words': 97541, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 19, 'lost_bt': 1, 'lost_model': 18}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}]}
18
Num model topics: 21.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
topic_0
topic_1
topic_2
topic_3
  WTF: {'good'} {'nhl'}
topic_4
  WTF: {'skepticism', 'like'} {'n3jxp', 'gordon'}
topic_5
topic_6
  WTF: {'government', 'ottoman', 'dont', 'started', 'saw', 'know'} {'armenians', 'armenian', 'sumgait', 'turks', 'armenia', 'azerbaijan'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_7
  WTF: {'toolbox', '8800CS', '1795', 'knowlege', 'ringleaders', 'dragdrop', 'Epilepsy', '5152940082', 'CDROMCATZIP', 'CSCSTD00385', 'L2PMABGZ7VAZV0PZRI', 'NikeCajun', 'effortsall', '207556000', 'taxation'} {''}
  WTF?!?!? 15
topic_8
topic_9
  WTF: {'social'} {'lsd'}
topic_10
  WTF: {'cities', 'make', 'use'} {'epa', 'auth', 'barre'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_11
  WTF: {'intrinsics'} {'r3'}
topic_12
topic_13
topic_14
  WTF: {'stripped', 'regards'} {'sehari', 'babak'}
topic_15
  WTF: {'computer', 'king', 'forget', 'guide', 'rule'} {'infiniti', 'altima', 'douglas', 'alice', 'adams'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_16
  WTF: {'abolished', 'immoral', 'bases', 'deficit'} {'c5s', 'admistration', 'registries', 'c17'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_17
  WTF: {'0099', 'patchmaking', 'patentable', 'legionaires', 'unpatentable'} {'pepsi', 'yerazunis', 'crah', 'cocacola', 'cola'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_18
  WTF: {'pw', '0n', 'u0', 'trinomials', 'mh', '644', 'mf', 'm1', 'mj', 'ma', 'begin', 'mm'} {'m3', 'm5', 'o3', 'lu', 'm0', 'mw', 'm9', 'pnospsxop8f', 'e8', 'mx', 'p6', 'm6'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_19
  WTF: {'aquanauts', 'alveoli'} {'co2', 'breather'}
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f6323da8910>}
Check after fit:
topic_0
topic_1
topic_2
topic_3
  WTF: {'good'} {'nhl'}
topic_4
  WTF: {'skepticism', 'like'} {'n3jxp', 'gordon'}
topic_5
topic_6
  WTF: {'government', 'ottoman', 'dont', 'started', 'saw', 'know'} {'armenians', 'armenian', 'sumgait', 'turks', 'armenia', 'azerbaijan'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_7
  WTF: {'toolbox', '8800CS', '1795', 'knowlege', 'ringleaders', 'dragdrop', 'Epilepsy', '5152940082', 'CDROMCATZIP', 'CSCSTD00385', 'L2PMABGZ7VAZV0PZRI', 'NikeCajun', 'effortsall', '207556000', 'taxation'} {''}
  WTF?!?!? 15
topic_8
topic_9
  WTF: {'social'} {'lsd'}
topic_10
  WTF: {'cities', 'make', 'use'} {'epa', 'auth', 'barre'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_11
  WTF: {'intrinsics'} {'r3'}
topic_12
topic_13
topic_14
  WTF: {'stripped', 'regards'} {'sehari', 'babak'}
topic_15
  WTF: {'computer', 'king', 'forget', 'guide', 'rule'} {'infiniti', 'altima', 'douglas', 'alice', 'adams'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_16
  WTF: {'abolished', 'immoral', 'bases', 'deficit'} {'c5s', 'admistration', 'registries', 'c17'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_17
  WTF: {'0099', 'patchmaking', 'patentable', 'legionaires', 'unpatentable'} {'pepsi', 'yerazunis', 'crah', 'cocacola', 'cola'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_18
  WTF: {'pw', '0n', 'u0', 'trinomials', 'mh', '644', 'mf', 'm1', 'mj', 'ma', 'begin', 'mm'} {'m3', 'm5', 'o3', 'lu', 'm0', 'mw', 'm9', 'pnospsxop8f', 'e8', 'mx', 'p6', 'm6'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_19
  WTF: {'aquanauts', 'alveoli'} {'co2', 'breather'}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f63177313d0>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f6312567b80>}
{'perplexity': 59934.94921875, 'coherence_20': 1.611873746211432, 'diversity_euclidean': 0.12146717957715591, 'diversity_jensenshannon': 0.7573218193959136, 'diversity_hellinger': 0.8945043194914635, 'diversity_cosine': 0.876351684131617, 'fair_ppl_free': 2267.092041015625, 'fair_ppl_fix': 59526.26171875, 'unfair_ppl_banklike': 59934.94921875}
{'num_topics': 21, 'num_common_words': 59415, 'num_model_words': 114951, 'num_bt_words': 97541, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 16, 'lost_bt': 1, 'lost_model': 15}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}]}
19
Num model topics: 21.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
topic_0
topic_1
topic_2
  WTF: {'good'} {'nhl'}
topic_3
  WTF: {'skepticism', 'banks'} {'n3jxp', 'gordon'}
topic_4
  WTF: {'government', 'ottoman', 'dont', 'started', 'saw', 'know'} {'armenians', 'armenian', 'sumgait', 'turks', 'armenia', 'azerbaijan'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_5
  WTF: {'toolbox', '8800CS', '1795', 'knowlege', 'ringleaders', 'dragdrop', 'Epilepsy', '5152940082', 'CDROMCATZIP', 'CSCSTD00385', 'L2PMABGZ7VAZV0PZRI', 'NikeCajun', 'effortsall', '207556000', 'taxation'} {''}
  WTF?!?!? 15
topic_6
topic_7
  WTF: {'tutorial', 'conference', 'technology'} {'japan', 'vernor', 'vinge'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_8
  WTF: {'social'} {'lsd'}
topic_9
  WTF: {'type'} {'r3'}
topic_10
  WTF: {'rule'} {'alice'}
topic_11
  WTF: {'charged', 'picture'} {'krillean', 'kirlian'}
topic_12
  WTF: {'abolished', 'immoral', 'bases', 'deficit'} {'c5s', 'admistration', 'registries', 'c17'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_13
topic_14
  WTF: {'stripped', 'regards'} {'sehari', 'babak'}
topic_15
  WTF: {'rest'} {'darius'}
topic_16
  WTF: {'used', 'dia', 'shroud', 'stabilized', 'big'} {'russia', 't4', 'joe', 't4centaur', 'energiam'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_17
  WTF: {'exponents'} {'scotyy'}
topic_18
  WTF: {'pw', '0n', 'u0', 'trinomials', 'mh', '644', 'mf', 'm1', 'mj', 'ma', 'begin', 'mm'} {'m3', 'm5', 'o3', 'lu', 'm0', 'mw', 'm9', 'pnospsxop8f', 'e8', 'mx', 'p6', 'm6'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_19
  WTF: {'nazism', 'moments', 'dem', 'utilize', 'mr', 'oddly', 'ya'} {'koph', 'hoffnung', 'davidssons', 'srinivas', 'turc', 'zeuge', 'timucin'}
  WTF?!?!? 7
  WTF?!?!? 7
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f630d3a53a0>}
Check after fit:
topic_0
topic_1
topic_2
  WTF: {'good'} {'nhl'}
topic_3
  WTF: {'skepticism', 'banks'} {'n3jxp', 'gordon'}
topic_4
  WTF: {'government', 'ottoman', 'dont', 'started', 'saw', 'know'} {'armenians', 'armenian', 'sumgait', 'turks', 'armenia', 'azerbaijan'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_5
  WTF: {'toolbox', '8800CS', '1795', 'knowlege', 'ringleaders', 'dragdrop', 'Epilepsy', '5152940082', 'CDROMCATZIP', 'CSCSTD00385', 'L2PMABGZ7VAZV0PZRI', 'NikeCajun', 'effortsall', '207556000', 'taxation'} {''}
  WTF?!?!? 15
topic_6
topic_7
  WTF: {'tutorial', 'conference', 'technology'} {'japan', 'vernor', 'vinge'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_8
  WTF: {'social'} {'lsd'}
topic_9
  WTF: {'type'} {'r3'}
topic_10
  WTF: {'rule'} {'alice'}
topic_11
  WTF: {'charged', 'picture'} {'krillean', 'kirlian'}
topic_12
  WTF: {'abolished', 'immoral', 'bases', 'deficit'} {'c5s', 'admistration', 'registries', 'c17'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_13
topic_14
  WTF: {'stripped', 'regards'} {'sehari', 'babak'}
topic_15
  WTF: {'rest'} {'darius'}
topic_16
  WTF: {'used', 'dia', 'shroud', 'stabilized', 'big'} {'russia', 't4', 'joe', 't4centaur', 'energiam'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_17
  WTF: {'exponents'} {'scotyy'}
topic_18
  WTF: {'pw', '0n', 'u0', 'trinomials', 'mh', '644', 'mf', 'm1', 'mj', 'ma', 'begin', 'mm'} {'m3', 'm5', 'o3', 'lu', 'm0', 'mw', 'm9', 'pnospsxop8f', 'e8', 'mx', 'p6', 'm6'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_19
  WTF: {'nazism', 'moments', 'dem', 'utilize', 'mr', 'oddly', 'ya'} {'koph', 'hoffnung', 'davidssons', 'srinivas', 'turc', 'zeuge', 'timucin'}
  WTF?!?!? 7
  WTF?!?!? 7

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f62ed6d8460>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f63298485e0>}
{'perplexity': 62375.53125, 'coherence_20': 1.622967801803077, 'diversity_euclidean': 0.12952848347882429, 'diversity_jensenshannon': 0.7729057378549365, 'diversity_hellinger': 0.9157510602284704, 'diversity_cosine': 0.8974720996620763, 'fair_ppl_free': 2357.569091796875, 'fair_ppl_fix': 62029.11328125, 'unfair_ppl_banklike': 62375.53125}
{'num_topics': 21, 'num_common_words': 59415, 'num_model_words': 114951, 'num_bt_words': 97541, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 16, 'lost_bt': 1, 'lost_model': 15}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}]}

In [50]:
1

1

In [51]:
result['scores']

{'perplexity': 62375.53125,
 'coherence_20': 1.622967801803077,
 'diversity_euclidean': 0.12952848347882429,
 'diversity_jensenshannon': 0.7729057378549365,
 'diversity_hellinger': 0.9157510602284704,
 'diversity_cosine': 0.8974720996620763,
 'fair_ppl_free': 2357.569091796875,
 'fair_ppl_fix': 62029.11328125,
 'unfair_ppl_banklike': 62375.53125}

In [ ]:
phi0.iloc[common_words_phi0_indices, 1:].shape

In [112]:
len(common_words)

59415

In [88]:
common_words[0]

('@lemmatized', 'discomfort')

In [89]:
phi0.index

MultiIndex([('@lemmatized',                                 '00'),
            ('@lemmatized',                                '000'),
            ('@lemmatized',                               '0000'),
            ('@lemmatized',                              '00000'),
            ('@lemmatized',                             '000000'),
            ('@lemmatized',                           '00000000'),
            ('@lemmatized',                         '0000000004'),
            ('@lemmatized',                          '00000000b'),
            ('@lemmatized',                           '00000001'),
            ('@lemmatized',                          '00000001b'),
            ...
            ('@lemmatized', 'zysv2j6q8hb0nsrlxeod3ediwnpqzmthd2'),
            ('@lemmatized',                       'zyugh5pzi72g'),
            ('@lemmatized',                              'zyxel'),
            ('@lemmatized',                         'zyxel1496b'),
            ('@lemmatized',                                 'zz'),
            ('@lemmatized',                              'zz960'),
            ('@lemmatized',                               'zzc2'),
            ('@lemmatized',                               'zzzs'),
            ('@lemmatized',                             'zzzzzz'),
            ('@lemmatized',                            'zzzzzzt')],
           length=97541)

In [110]:
phi0[common_words_phi0_indices, :]

InvalidIndexError: ([31415, 23332, 24830, 41527, 25367, 29918, 23310, 21466, 74196, 82185, 90251, 24363, 77176, 80391, 12773, 39766, 19033, 46480, 1027, 39799, 1678, 36821, 45958, 54699, 67440, 69360, 1798, 7624, 52458, 45430, 3732, 71490, 13324, 73901, 65838, 25952, 38372, 58540, 20748, 55925, 22070, 15756, 55774, 16918, 28958, 7680, 27000, 92198, 56017, 34444, 75886, 66352, 4349, 89058, 88167, 27137, 55043, 64791, 23240, 71654, 16429, 11019, 6512, 68526, 97022, 14159, 12133, 23886, 75887, 72922, 44346, 83078, 13303, 64086, 29132, 45327, 313, 19326, 82824, 1863, 91283, 16541, 88787, 24360, 74077, 86788, 12821, 31527, 77428, 76191, 57116, 65488, 16886, 28534, 84, 9295, 33786, 46702, 63335, 66489, 10938, 14208, 71293, 3809, 50182, 79996, 68568, 72510, 13154, 79162, 91427, 94251, 19649, 76185, 84909, 12374, 39958, 51252, 69826, 77240, 44746, 79151, 27243, 72147, 11015, 68807, 68572, 26572, 52094, 95302, 46300, 6160, 21441, 48459, 11989, 45052, 17679, 74435, 88757, 26497, 47137, 79341, 77941, 58756, 19738, 52336, 34974, 18655, 77022, 27126, 75038, 81747, 92435, 22747, 55934, 65616, 84352, 49578, 30872, 27869, 16053, 33340, 81462, 15689, 54973, 74714, 53033, 86381, 37828, 33602, 73268, 76431, 79135, 60070, 68822, 6338, 41490, 13588, 11066, 30396, 3526, 74636, 80571, 27811, 14534, 20584, 12059, 17351, 50030, 90165, 67361, 48602, 14851, 75283, 56792, 86740, 39643, 25034, 23318, 27931, 1038, 16774, 61690, 8184, 59881, 20329, 70296, 94606, 47025, 18046, 45895, 58683, 67905, 88696, 65410, 74442, 74864, 7909, 13419, 21764, 14535, 17305, 45514, 68974, 2283, 8311, 45686, 10770, 27163, 37869, 22460, 87072, 75888, 81468, 81378, 68014, 84706, 95496, 5718, 20713, 3627, 36384, 3203, 21283, 15945, 8608, 25907, 7343, 44280, 55552, 50274, 26581, 68785, 44289, 3119, 38154, 52414, 26294, 79984, 29765, 31539, 67286, 20157, 76761, 24180, 6961, 25821, 62771, 16664, 10919, 13428, 45415, 69926, 35105, 41240, 42151, 4866, 55428, 9422, 37410, 41337, 41563, 25752, 9334, 77114, 87, 6205, 41046, 37479, 4085, 35657, 68819, 72255, 9159, 88549, 97533, 28524, 90754, 9157, 83533, 10080, 2669, 79653, 64687, 28733, 55951, 95279, 27398, 19103, 62533, 68613, 80345, 2493, 35944, 36878, 13802, 43431, 25410, 84013, 19688, 52304, 63243, 42576, 55410, 70562, 83331, 19306, 74247, 74683, 10882, 14369, 14965, 20169, 89063, 38185, 89421, 35465, 52582, 13671, 58576, 86416, 9323, 29753, 33102, 75988, 70589, 85330, 91447, 28484, 72525, 90128, 82817, 76756, 16634, 85573, 80775, 73885, 49925, 31560, 24150, 45909, 10260, 19668, 23897, 33371, 33548, 83715, 84309, 81025, 70131, 66013, 74506, 92463, 70882, 58032, 25287, 49357, 74518, 72782, 63160, 28097, 75968, 42000, 40005, 55490, 73789, 9182, 93618, 16092, 6003, 36964, 31732, 71387, 72164, 643, 19675, 25744, 73915, 554, 21901, 17381, 43694, 69418, 63455, 64173, 58841, 4629, 41772, 14817, 16387, 79554, 7884, 10240, 27577, 81984, 7259, 31546, 60051, 25658, 81796, 63699, 35142, 92743, 39128, 70227, 46559, 85130, 35505, 63650, 55711, 12262, 58760, 81575, 29253, 41126, 7583, 45984, 21262, 60014, 4792, 80034, 95405, 95784, 14036, 11937, 83694, 34747, 76750, 70256, 8508, 43223, 36145, 26934, 63682, 16223, 24418, 28567, 19746, 72158, 63425, 74256, 2827, 18582, 38406, 83743, 93977, 73887, 75128, 57397, 40523, 66102, 74729, 82536, 51990, 85795, 37687, 47621, 9998, 88378, 64322, 1047, 78443, 37876, 52878, 8263, 3980, 31727, 34656, 30638, 31468, 25296, 33663, 78474, 90491, 74898, 88617, 40508, 27063, 8519, 41505, 36490, 66090, 49117, 46932, 35469, 52720, 54712, 73394, 55076, 75725, 94172, 66553, 51566, 28713, 24155, 54936, 80713, 30156, 84559, 89802, 83485, 27506, 91971, 90772, 29744, 15256, 72203, 81396, 85683, 45659, 2419, 58716, 66297, 90525, 29689, 2695, 72053, 78202, 37080, 45463, 10036, 52043, 66259, 71368, 7694, 42977, 67130, 80636, 29581, 8727, 86629, 76367, 63677, 16034, 45738, 51597, 5448, 46204, 2153, 5720, 53323, 51362, 19781, 48921, 38819, 81659, 84249, 4294, 30736, 67422, 12526, 91472, 42996, 24798, 65994, 87959, 63806, 90478, 83333, 78708, 90506, 38018, 72419, 38309, 80238, 75511, 67235, 76569, 64658, 74331, 75699, 38083, 21211, 48811, 13553, 5517, 12386, 14245, 22290, 18527, 58761, 91010, 25648, 12742, 18105, 27509, 6302, 8190, 19113, 43843, 14801, 23463, 52956, 29544, 70208, 46462, 96030, 4160, 57077, 70487, 8225, 21467, 24268, 97211, 57310, 76470, 7292, 53197, 80154, 82938, 720, 42209, 81647, 77514, 24851, 29641, 57111, 56798, 74452, 31362, 3161, 66926, 70118, 59855, 44007, 67712, 82596, 9678, 68691, 64804, 72033, 86997, 85087, 26083, 90005, 85465, 34493, 62786, 37210, 12031, 38379, 35044, 22468, 67999, 82540, 85361, 12409, 42332, 60428, 11194, 85319, 46092, 9619, 1229, 90185, 94739, 64862, 78367, 22001, 2931, 49920, 71498, 37739, 55756, 30260, 13793, 2094, 41, 37177, 75131, 45645, 70226, 93078, 88601, 45860, 9904, 48309, 82012, 90091, 38009, 75472, 500, 21661, 66693, 70008, 858, 17057, 21488, 32086, 61629, 67724, 44492, 51086, 10173, 75109, 58046, 73398, 66026, 46544, 47574, 1823, 24443, 51352, 13475, 27220, 45705, 76039, 70981, 81339, 84996, 5905, 92443, 1053, 80847, 4640, 34797, 40748, 68844, 11568, 29803, 81784, 36706, 44542, 82315, 43899, 97517, 13623, 2019, 58742, 5980, 38778, 37181, 91702, 15740, 58812, 63253, 26770, 16986, 35976, 63378, 18590, 90273, 4928, 29577, 68548, 83970, 10229, 86313, 87911, 10318, 75405, 31348, 20089, 3818, 67275, 84357, 28572, 66983, 63983, 13349, 76878, 7548, 72076, 53250, 26665, 72244, 9079, 3778, 74595, 65512, 75928, 42459, 7195, 20564, 67077, 84941, 33443, 90958, 45078, 4426, 61195, 87521, 61522, 91811, 1562, 131, 89675, 31508, 5581, 96995, 14216, 7887, 79311, 5728, 72885, 74289, 9071, 3579, 11810, 20265, 53316, 67867, 23181, 68545, 10508, 78413, 89409, 23905, 15942, 8770, 84004, 4348, 92045, 49989, 11176, 29657, 6962, 38527, 69768, 44583, 90181, 27134, 63194, 87525, 6106, 15668, 38418, 39158, 13118, 1771, 10267, 68772, 76685, 50287, 70609, 13297, 37456, 56789, 33255, 670, 11607, 34066, 93570, 94295, 42359, 92216, 25824, 42631, 39507, 42346, 26622, 33840, 7041, 4365, 7572, 75044, 39170, 1612, 19165, 86685, 45502, 29682, 84310, 32182, 63449, 9139, 36540, 25422, 64504, 10386, 86502, 87878, 51611, 5926, 62943, 31192, 11202, 17196, 92436, 61285, 58353, 33445, 56794, 66334, 4561, 26501, 79291, 85324, 94186, 45783, 62530, 97440, 24975, 74113, 86062, 36840, 68017, 10949, 65670, 26919, 75788, 76832, 80041, 91950, 1866, 52108, 21437, 94671, 3408, 51384, 26801, 79644, 84713, 35790, 75979, 64073, 4476, 41534, 66229, 15604, 70014, 45817, 44841, 10731, 69631, 38398, 19376, 16696, 89778, 70339, 32053, 38722, 71420, 71646, 14875, 39252, 78199, 53282, 86362, 91016, 95974, 66699, 89236, 29963, 28098, 94482, 9106, 46580, 35242, 21448, 90211, 84665, 27097, 17453, 20964, 8693, 14952, 77364, 94935, 369, 46997, 72224, 73995, 4181, 44130, 10266, 45739, 54852, 21204, 5732, 58740, 69516, 38731, 44857, 94836, 79710, 51335, 30010, 58228, 42331, 86679, 92191, 36887, 12276, 46908, 80645, 92381, 43285, 9124, 19669, 1989, 21549, 57144, 67282, 79303, 77597, 3169, 17778, 44650, 41153, 40518, 29057, 81790, 12426, 84461, 22898, 67147, 78230, 4050, 44783, 14212, 21541, 66176, 74738, 72339, 95108, 42865, 58813, 68793, 83417, 27582, 28047, 36600, 1974, 21269, 6439, 25045, 58551, 8987, 32654, 3827, 58187, 40347, 5791, 40766, 32583, 74990, 66789, 1788, 90049, 11362, 30816, 32407, 85062, 58481, 45063, 48450, 3302, 17332, 58665, 70943, 82964, 74700, 76558, 602, 54967, 76704, 72853, 74081, 31489, 8562, 7706, 29190, 33728, 12569, 29536, 8619, 14741, 24602, 5648, 25685, 38132, 46327, 68002, 69425, 85481, 6028, 41711, 36386, 12346, 68632, 83405, 91640, 42453, 25098, 27896, 3671, 71877, 32810, 19607, 5, 94281, 69662, 66953, 8174, 84437, 37595, 11022, 90957, 5954, 589, 16987, 78750, 70656, 60561, 29285, 80991, 68757, 16039, 78706, 89657, 43459, 25735, 46352, 88220, 35803, 83380, 507, 8318, 7722, 81180, 12055, 91414, 32919, 70112, 86831, 8549, 84060, 27767, 51942, 82090, 28183, 43260, 3976, 15920, 26000, 27061, 85941, 50944, 88192, 14186, 53168, 3933, 39611, 51196, 58684, 84016, 22785, 2340, 87093, 64434, 68102, 87964, 68394, 78091, 21237, 44891, 8370, 2430, 95485, 4394, 71445, 88450, 89810, 65105, 17786, 75103, 89099, 9880, 39155, 50843, 30109, 54, 3498, 11312, 79879, 3355, 10054, 85722, 91469, 19789, 72674, 37488, 80474, 4638, 34341, 82187, 69683, 89380, 94307, 14496, 6027, 2996, 8394, 78843, 44196, 5149, 79338, 83486, 47463, 31043, 56881, 88499, 95100, 86591, 35676, 60158, 3864, 34923, 39141, 12893, 18469, 47225, 4002, 46143, 68068, 36451, 89397, 41451, 6239, 3023, 17156, 52870, 40069, 89166, 15478, 18932, 23887, 57219, 16781, 4887, 48213, 65743, 67804, 8162, 73896, 10111, 9510, 42521, 89819, 66776, 56783, 71528, 89336, 10268, 39021, 92010, 18914, 27483, 29598, 83392, 93883, 10910, 34438, 33005, 47173, 90527, 91302, 80774, 33024, 87912, 49411, 94871, 3970, 87935, 29647, 14430, 7188, 30708, 97294, 77271, 79035, 9151, 6246, 43, 22330, 45934, 85983, 14888, 18642, 35857, 16795, 88292, 35516, 21889, 85756, 19514, 30764, 74662, 33228, 58835, 34995, 89323, 43511, 31230, 27371, 77759, 42356, 15009, 28127, 45214, 75291, 414, 46457, 58744, 26464, 2911, 64732, 30469, 82106, 79709, 78709, 96989, 93692, 20583, 83765, 6971, 38944, 73377, 83218, 1728, 20070, 85865, 4990, 7794, 4084, 13237, 12477, 52504, 35837, 90008, 38108, 29065, 84233, 94282, 37240, 88206, 28277, 75147, 29062, 3666, 27961, 22649, 89857, 30641, 66263, 72104, 73737, 74847, 81933, 30966, 30604, 66226, 79315, 89326, 10075, 14655, 39777, 49761, 38345, 86982, 28105, 95384, 25366, 24920, 70154, 82936, 89102, 28041, 34211, 55650, 72003, 38770, 31992, 38742, 14471, 20809, 67753, 26131, 71507, 9122, 20994, 25890, 26656, 69415, 79238, 19205, 14612, 5094, 39310, 13500, 72536, 90199, 11842, 30007, 81742, 84052, 80931, 9042, 80142, 13488, 31888, 18348, 18930, 91596, 24226, 75271, 90505, 18876, 67527, 32718, 94660, 33053, 38306, 21062, 92051, 50542, 85520, 21447, 818, 25893, 32624, 71255, 37697, 84595, 50350, 41098, 8885, 26649, 37333, 70650, 5449, 20839, 46956, 27069, 57168, 8656, 17041, 92641, 80927, 86322, 89925, 21160, 51819, 64335, 72379, 80005, 37163, 81424, 377, 67119, 17752, 53353, 56806, 82625, 45820, 52741, 63138, 93982, 46166, 48633, 86376, 38519, 91594, 76192, 74128, 51628, 52408, 66532, 74325, 85102, 53041, 7682, 40500, 87494, 92240, 64452, 9824, 96100, 74478, 2729, 1236, 7109, 40782, 76482, 84397, 892, 23412, 75958, 17352, 2509, 28488, 27363, 82192, 3478, 29897, 18403, 82983, 42668, 67266, 24437, 5733, 28336, 70121, 88813, 16814, 17757, 18070, 16318, 90356, 50241, 92476, 19261, 33460, 46119, 75012, 43107, 63441, 12449, 72098, 31511, 85252, 34306, 8874, 13265, 14666, 2562, 38270, 37624, 67113, 92031, 825, 69264, 16590, 20913, 9420, 2343, 71377, 78211, 83610, 84068, 88654, 60140, 23562, 20444, 7895, 19841, 74042, 3448, 69537, 1217, 431, 2690, 72376, 66494, 35943, 8159, 44837, 27226, 50970, 46886, 14943, 35888, 36464, 81130, 41890, 91438, 91937, 6285, 26765, 87455, 32832, 52230, 88327, 27103, 46189, 50255, 27547, 88522, 8861, 40815, 46754, 31129, 38688, 39409, 75551, 63268, 72836, 17544, 24657, 72231, 75820, 26063, 27736, 92431, 78056, 66862, 9337, 35589, 23981, 10889, 74381, 89471, 5105, 54945, 75717, 22860, 74318, 85485, 4128, 35787, 87356, 80149, 41210, 27516, 43586, 56907, 6565, 62984, 87876, 79788, 43352, 31182, 5042, 62461, 12907, 29607, 64641, 82746, 37970, 84513, 86676, 70416, 8847, 91349, 6464, 8664, 479, 22143, 49814, 93174, 75098, 13842, 78379, 83224, 15220, 45434, 16969, 46634, 26663, 64094, 29970, 76986, 36028, 52736, 20316, 6221, 76236, 26677, 52370, 9344, 75172, 55821, 13311, 87608, 19118, 6555, 26694, 40274, 64144, 70953, 73932, 76904, 46174, 42803, 74151, 57768, 1121, 18119, 34223, 56775, 72582, 87441, 5594, 61639, 76046, 38939, 81707, 6324, 72672, 22660, 56, 72914, 83601, 87319, 18296, 29966, 29976, 14443, 8217, 2417, 73994, 93373, 2210, 43505, 7456, 46955, 23692, 90278, 75471, 7899, 38213, 42659, 69344, 21420, 61952, 15677, 85299, 37041, 55945, 4026, 24018, 43443, 47095, 35704, 48524, 3885, 35523, 61838, 75020, 10604, 4498, 35931, 96098, 80233, 90259, 16140, 29296, 42318, 77825, 22585, 11347, 23556, 41622, 46941, 76996, 8880, 76528, 77812, 20115, 21396, 52463, 68814, 10972, 23366, 75844, 72825, 77350, 39975, 49922, 8737, 46056, 76450, 28427, 60328, 70466, 84307, 73569, 45700, 11498, 4865, 17038, 29282, 3228, 55684, 20304, 2557, 58959, 59916, 51590, 67900, 72513, 76592, 86998, 94008, 17879, 68598, 37948, 76466, 37858, 63003, 6641, 23788, 32210, 65489, 71443, 84857, 36131, 52398, 4489, 46038, 3317, 23167, 58040, 71998, 17688, 17101, 41516, 5340, 39925, 92635, 68637, 67020, 93155, 76612, 82199, 3904, 32101, 89506, 68040, 5585, 10404, 31801, 26028, 18096, 51527, 58503, 4055, 65773, 86602, 51379, 30878, 72742, 89268, 21503, 94492, 26478, 59858, 1797, 77058, 45055, 29061, 66292, 10971, 94531, 29731, 27487, 76584, 66054, 43037, 74783, 38035, 5251, 61183, 5786, 25136, 79393, 83438, 11997, 75980, 36523, 17065, 18338, 41881, 47216, 78648, 25055, 28417, 96987, 17341, 21355, 44159, 4139, 72822, 76056, 63976, 86196, 1721, 42378, 87376, 32739, 2849, 78884, 12918, 89949, 77164, 21914, 31100, 15070, 43760, 39961, 46928, 73853, 73648, 20166, 82646, 77434, 48935, 4039, 37393, 45097, 64584, 72827, 86573, 57059, 42092, 17095, 16161, 42487, 73708, 36932, 34892, 57324, 8292, 4663, 79652, 8117, 35946, 46792, 42495, 75418, 50020, 69523, 2512, 3180, 45213, 10299, 45816, 41760, 47142, 66299, 83520, 92070, 68168, 23329, 9442, 37031, 42152, 55906, 25084, 34646, 27015, 67128, 75234, 76919, 95402, 1664, 10179, 15782, 27485, 88299, 82270, 669, 55320, 17470, 31291, 75833, 67778, 81537, 84563, 17551, 13736, 9842, 31473, 89204, 20918, 58658, 84789, 5962, 69252, 16324, 57132, 48523, 7220, 94415, 10023, 74974, 6637, 40173, 50211, 94269, 79691, 38412, 82059, 38981, 44231, 73740, 45771, 71859, 35107, 49217, 69108, 24646, 38299, 63880, 86924, 27821, 88152, 8495, 61825, 90771, 63473, 83616, 30121, 19626, 15926, 46587, 26326, 17192, 90347, 92588, 64267, 45019, 18451, 42047, 17809, 8330, 84109, 89227, 88177, 72072, 58624, 41659, 4447, 29334, 8708, 16157, 6625, 2428, 24064, 31799, 44394, 46767, 92403, 70634, 2553, 15733, 26067, 45160, 52855, 39547, 8718, 91030, 25419, 84001, 64588, 90466, 1977, 74954, 29251, 84621, 14658, 97032, 51571, 75530, 72506, 20523, 46788, 54820, 75606, 58752, 12434, 91331, 3028, 81608, 21119, 22771, 25322, 94820, 4962, 34169, 11000, 10637, 22673, 24059, 84031, 32125, 6677, 37964, 6033, 32503, 33218, 51741, 5874, 16645, 12287, 22833, 2499, 39529, 52597, 59850, 65338, 68879, 55648, 28461, 34196, 25049, 39, 19571, 21055, 48829, 75936, 77315, 77455, 83740, 91871, 97488, 7461, 3196, 41258, 49962, 25785, 44043, 64635, 81358, 11588, 651, 37960, 47570, 79777, 45547, 2241, 74316, 7789, 14708, 74342, 78690, 82907, 2976, 8497, 19595, 47212, 68686, 13116, 1922, 58227, 86995, 30693, 89033, 39051, 94066, 44269, 30186, 46867, 79316, 66850, 52824, 46562, 27140, 60376, 87407, 92167, 31832, 78885, 90250, 38772, 9233, 62444, 65984, 21169, 36174, 97036, 20346, 74402, 90474, 75608, 76171, 95128, 14772, 66685, 65376, 89011, 57533, 61535, 89927, 92340, 93142, 76605, 24008, 69863, 3689, 33234, 30799, 92848, 47826, 83856, 10098, 68499, 9307, 46121, 34595, 75734, 55290, 76382, 86165, 44844, 88596, 86630, 32256, 39989, 71982, 94685, 13006, 42416, 43458, 43538, 47402, 47234, 86800, 24595, 89968, 67504, 7916, 90622, 17335, 2102, 57433, 33179, 10298, 20168, 75832, 88257, 38432, 46699, 8240, 31022, 502, 53085, 1908, 61430, 60112, 75850, 67671, 81363, 54709, 30700, 63451, 2620, 25308, 2492, 20160, 26165, 15570, 35913, 10963, 62495, 23740, 25467, 37933, 73841, 23736, 69212, 8752, 51136, 63274, 46880, 65038, 43202, 5007, 25399, 4820, 2555, 96750, 31332, 83446, 63345, 190, 60086, 85375, 71331, 6638, 78927, 84524, 4327, 59347, 15987, 79599, 80012, 45978, 86391, 52821, 4370, 78720, 3353, 47430, 31405, 3461, 89287, 68818, 79198, 63239, 44140, 66579, 86889, 14836, 56772, 35342, 17405, 15037, 30292, 20823, 33378, 30267, 33740, 14004, 9216, 84134, 14553, 36213, 18574, 74769, 3319, 9143, 79508, 81189, 32263, 67682, 89135, 84653, 64391, 74028, 17001, 4647, 84625, 48722, 37729, 72054, 87527, 11187, 39716, 19786, 60449, 35887, 76008, 6714, 35143, 18545, 46183, 79975, 20706, 30220, 70820, 51531, 87992, 89182, 91251, 3070, 3037, 19364, 1128, 3258, 37342, 41212, 69597, 50157, 76076, 29840, 3511, 46776, 26409, 76496, 80460, 23174, 67388, 47714, 88274, 23878, 42083, 30270, 41656, 69260, 5544, 89295, 80468, 64404, 41864, 2691, 16354, 6480, 27733, 13041, 2401, 79713, 40395, 83924, 92827, 26661, 31490, 64514, 24154, 19007, 84430, 76476, 71781, 90252, 9240, 36633, 2622, 42927, 66696, 77168, 46079, 32273, 50508, 84592, 96823, 74805, 5563, 37818, 62828, 23176, 23490, 2411, 44846, 16942, 5287, 68655, 83500, 944, 18942, 52718, 1371, 90665, 19618, 2876, 74279, 47667, 346, 63642, 19568, 12152, 30221, 27469, 57499, 69369, 94868, 60692, 30058, 1934, 93196, 74234, 93637, 64803, 73020, 67495, 1724, 50447, 6382, 5464, 34692, 71179, 46707, 34796, 39153, 68046, 95225, 4034, 15658, 40960, 35965, 75433, 75463, 34123, 63526, 5689, 728, 66216, 69226, 2365, 5003, 77986, 17076, 80825, 17788, 22036, 79964, 67198, 3906, 43787, 83483, 37771, 53005, 55127, 97310, 71812, 79290, 70117, 58667, 8488, 3223, 47038, 40831, 29200, 73563, 41064, 75238, 342, 14634, 51834, 71072, 76396, 14812, 80102, 31305, 9604, 79673, 36739, 30594, 49954, 78746, 89244, 12861, 66338, 9029, 95583, 11423, 3263, 55806, 25810, 38068, 384, 26950, 14458, 84385, 41462, 18349, 2146, 67991, 64305, 70565, 1398, 70156, 91103, 66872, 78414, 84543, 593, 94777, 37145, 47091, 74790, 6671, 69099, 91321, 1056, 89762, 73849, 60392, 33888, 64155, 63485, 12487, 96796, 34230, 17491, 29849, 63480, 76962, 11543, 47344, 66744, 42906, 80634, 46089, 38011, 45847, 47975, 78141, 43005, 79168, 42968, 46909, 79392, 93619, 3729, 88740, 86828, 76424, 21562, 51975, 35909, 38417, 23502, 42797, 41779, 27822, 7348, 34722, 63229, 67977, 33375, 31849, 28511, 6144, 16041, 74260, 72952, 66724, 14484, 66881, 24992, 72000, 45915, 87998, 40511, 66892, 64815, 36109, 36954, 69173, 88347, 3624, 1233, 26058, 35863, 64607, 27112, 42689, 20894, 12989, 83344, 85500, 33388, 45797, 40074, 2456, 5616, 6722, 16900, 80321, 5381, 43628, 627, 8628, 10344, 88136, 32740, 63292, 36005, 74989, 85580, 2971, 64163, 51545, 36743, 30597, 44526, 45243, 38780, 39247, 39285, 39040, 95272, 6660, 68280, 2901, 24665, 106, 46857, 70967, 46998, 7084, 28546, 19980, 90244, 5854, 86132, 72539, 8813, 12922, 26125, 84628, 54871, 14844, 28937, 48625, 33679, 16627, 70473, 56089, 12, 8666, 58116, 6569, 80175, 40227, 47271, 13730, 52052, 70849, 34176, 45173, 41437, 25035, 39156, 30999, 637, 67914, 83225, 74428, 77349, 83488, 40764, 84300, 51551, 1726, 41475, 43153, 47618, 61199, 41281, 77534, 27601, 9960, 31183, 36041, 23660, 27754, 66799, 68377, 78733, 20660, 61658, 70432, 39184, 87451, 10378, 28244, 81026, 88452, 35407, 57127, 19828, 69592, 10642, 76051, 67166, 94560, 21359, 21066, 68038, 44383, 47631, 82918, 52210, 86499, 1860, 14959, 23628, 7465, 26035, 43113, 69549, 24093, 77881, 56770, 40622, 47017, 65496, 11269, 36764, 5999, 2455, 70172, 9995, 3250, 5667, 89850, 3501, 277, 35383, 73468, 44246, 77775, 88920, 75286, 76091, 25185, 13200, 85424, 20149, 86007, 37555, 64816, 13216, 41313, 43548, 96167, 93012, 43863, 23723, 84778, 73898, 49021, 61202, 3459, 51721, 4169, 81328, 2159, 19248, 80739, 88320, 57135, 82656, 92069, 26925, 35737, 47015, 23555, 93040, 93454, 39415, 58158, 1102, 3865, 31793, 1918, 8754, 2387, 11515, 40543, 4880, 49292, 63275, 3795, 22426, 30817, 40808, 63334, 89975, 19021, 77210, 17579, 68571, 79405, 51970, 95664, 91509, 76239, 12904, 73992, 13149, 34478, 64043, 89087, 74861, 429, 11460, 75785, 38209, 75702, 28074, 10668, 95757, 51216, 35778, 51119, 66963, 84954, 7475, 65386, 25857, 43338, 68005, 40391, 43626, 95305, 51883, 69890, 81139, 46936, 60479, 5107, 58202, 5823, 16283, 88644, 45957, 51123, 41083, 78299, 35267, 79650, 78859, 76136, 69566, 47021, 96645, 25668, 4443, 47753, 29184, 11245, 86455, 31893, 63023, 76694, 71897, 654

In [87]:
phi0.index.get_loc(common_words[0])

/tmp/ipykernel_956566/4262250715.py:1: PerformanceWarning:

indexing past lexsort depth may impact performance.

slice(31415, 31416, None)

In [95]:
phi0.index.get_loc(('@lemmatized', '00'))

/tmp/ipykernel_956566/1220232106.py:1: PerformanceWarning:

indexing past lexsort depth may impact performance.

slice(0, 1, None)

In [100]:
phi0.index.get_locs(common_words[:2])

KeyError: 'discomfort'

In [104]:
int(phi0.index.get_locs(('@lemmatized', 'discomfort')))

31415

In [85]:
common_words_phi0_indices

[slice(31415, 31416, None),
 slice(23332, 23333, None),
 slice(24830, 24831, None),
 slice(41527, 41528, None),
 slice(25367, 25368, None),
 slice(29918, 29919, None),
 slice(23310, 23311, None),
 slice(21466, 21467, None),
 slice(74196, 74197, None),
 slice(82185, 82186, None),
 slice(90251, 90252, None),
 slice(24363, 24364, None),
 slice(77176, 77177, None),
 slice(80391, 80392, None),
 slice(12773, 12774, None),
 slice(39766, 39767, None),
 slice(19033, 19034, None),
 slice(46480, 46481, None),
 slice(1027, 1028, None),
 slice(39799, 39800, None),
 slice(1678, 1679, None),
 slice(36821, 36822, None),
 slice(45958, 45959, None),
 slice(54699, 54700, None),
 slice(67440, 67441, None),
 slice(69360, 69361, None),
 slice(1798, 1799, None),
 slice(7624, 7625, None),
 slice(52458, 52459, None),
 slice(45430, 45431, None),
 slice(3732, 3733, None),
 slice(71490, 71491, None),
 slice(13324, 13325, None),
 slice(73901, 73902, None),
 slice(65838, 65839, None),
 slice(25952, 25953, None),
 slice(38372, 38373, None),
 slice(58540, 58541, None),
 slice(20748, 20749, None),
 slice(55925, 55926, None),
 slice(22070, 22071, None),
 slice(15756, 15757, None),
 slice(55774, 55775, None),
 slice(16918, 16919, None),
 slice(28958, 28959, None),
 slice(7680, 7681, None),
 slice(27000, 27001, None),
 slice(92198, 92199, None),
 slice(56017, 56018, None),
 slice(34444, 34445, None),
 slice(75886, 75887, None),
 slice(66352, 66353, None),
 slice(4349, 4350, None),
 slice(89058, 89059, None),
 slice(88167, 88168, None),
 slice(27137, 27138, None),
 slice(55043, 55044, None),
 slice(64791, 64792, None),
 slice(23240, 23241, None),
 slice(71654, 71655, None),
 slice(16429, 16430, None),
 slice(11019, 11020, None),
 slice(6512, 6513, None),
 slice(68526, 68527, None),
 slice(97022, 97023, None),
 slice(14159, 14160, None),
 slice(12133, 12134, None),
 slice(23886, 23887, None),
 slice(75887, 75888, None),
 slice(72922, 72923, None),
 slice(44346, 44347, None),
 slice(83078, 83079, None),
 slice(13303, 13304, None),
 slice(64086, 64087, None),
 slice(29132, 29133, None),
 slice(45327, 45328, None),
 slice(313, 314, None),
 slice(19326, 19327, None),
 slice(82824, 82825, None),
 slice(1863, 1864, None),
 slice(91283, 91284, None),
 slice(16541, 16542, None),
 slice(88787, 88788, None),
 slice(24360, 24361, None),
 slice(74077, 74078, None),
 slice(86788, 86789, None),
 slice(12821, 12822, None),
 slice(31527, 31528, None),
 slice(77428, 77429, None),
 slice(76191, 76192, None),
 slice(57116, 57117, None),
 slice(65488, 65489, None),
 slice(16886, 16887, None),
 slice(28534, 28535, None),
 slice(84, 85, None),
 slice(9295, 9296, None),
 slice(33786, 33787, None),
 slice(46702, 46703, None),
 slice(63335, 63336, None),
 slice(66489, 66490, None),
 slice(10938, 10939, None),
 slice(14208, 14209, None),
 slice(71293, 71294, None),
 slice(3809, 3810, None),
 slice(50182, 50183, None),
 slice(79996, 79997, None),
 slice(68568, 68569, None),
 slice(72510, 72511, None),
 slice(13154, 13155, None),
 slice(79162, 79163, None),
 slice(91427, 91428, None),
 slice(94251, 94252, None),
 slice(19649, 19650, None),
 slice(76185, 76186, None),
 slice(84909, 84910, None),
 slice(12374, 12375, None),
 slice(39958, 39959, None),
 slice(51252, 51253, None),
 slice(69826, 69827, None),
 slice(77240, 77241, None),
 slice(44746, 44747, None),
 slice(79151, 79152, None),
 slice(27243, 27244, None),
 slice(72147, 72148, None),
 slice(11015, 11016, None),
 slice(68807, 68808, None),
 slice(68572, 68573, None),
 slice(26572, 26573, None),
 slice(52094, 52095, None),
 slice(95302, 95303, None),
 slice(46300, 46301, None),
 slice(6160, 6161, None),
 slice(21441, 21442, None),
 slice(48459, 48460, None),
 slice(11989, 11990, None),
 slice(45052, 45053, None),
 slice(17679, 17680, None),
 slice(74435, 74436, None),
 slice(88757, 88758, None),
 slice(26497, 26498, None),
 slice(47137, 47138, None),
 slice(79341, 79342, None),
 slice(77941, 77942, None),
 slice(58756, 58757, None),
 slice(19738, 19739, None),
 slice(52336, 52337, None),
 slice(34974, 34975, None),
 slice(18655, 18656, None),
 slice(77022, 77023, None),
 slice(27126, 27127, None),
 slice(75038, 75039, None),
 slice(81747, 81748, None),
 slice(92435, 92436, None),
 slice(22747, 22748, None),
 slice(55934, 55935, None),
 slice(65616, 65617, None),
 slice(84352, 84353, None),
 slice(49578, 49579, None),
 slice(30872, 30873, None),
 slice(27869, 27870, None),
 slice(16053, 16054, None),
 slice(33340, 33341, None),
 slice(81462, 81463, None),
 slice(15689, 15690, None),
 slice(54973, 54974, None),
 slice(74714, 74715, None),
 slice(53033, 53034, None),
 slice(86381, 86382, None),
 slice(37828, 37829, None),
 slice(33602, 33603, None),
 slice(73268, 73269, None),
 slice(76431, 76432, None),
 slice(79135, 79136, None),
 slice(60070, 60071, None),
 slice(68822, 68823, None),
 slice(6338, 6339, None),
 slice(41490, 41491, None),
 slice(13588, 13589, None),
 slice(11066, 11067, None),
 slice(30396, 30397, None),
 slice(3526, 3527, None),
 slice(74636, 74637, None),
 slice(80571, 80572, None),
 slice(27811, 27812, None),
 slice(14534, 14535, None),
 slice(20584, 20585, None),
 slice(12059, 12060, None),
 slice(17351, 17352, None),
 slice(50030, 50031, None),
 slice(90165, 90166, None),
 slice(67361, 67362, None),
 slice(48602, 48603, None),
 slice(14851, 14852, None),
 slice(75283, 75284, None),
 slice(56792, 56793, None),
 slice(86740, 86741, None),
 slice(39643, 39644, None),
 slice(25034, 25035, None),
 slice(23318, 23319, None),
 slice(27931, 27932, None),
 slice(1038, 1039, None),
 slice(16774, 16775, None),
 slice(61690, 61691, None),
 slice(8184, 8185, None),
 slice(59881, 59882, None),
 slice(20329, 20330, None),
 slice(70296, 70297, None),
 slice(94606, 94607, None),
 slice(47025, 47026, None),
 slice(18046, 18047, None),
 slice(45895, 45896, None),
 slice(58683, 58684, None),
 slice(67905, 67906, None),
 slice(88696, 88697, None),
 slice(65410, 65411, None),
 slice(74442, 74443, None),
 slice(74864, 74865, None),
 slice(7909, 7910, None),
 slice(13419, 13420, None),
 slice(21764, 21765, None),
 slice(14535, 14536, None),
 slice(17305, 17306, None),
 slice(45514, 45515, None),
 slice(68974, 68975, None),
 slice(2283, 2284, None),
 slice(8311, 8312, None),
 slice(45686, 45687, None),
 slice(10770, 10771, None),
 slice(27163, 27164, None),
 slice(37869, 37870, None),
 slice(22460, 22461, None),
 slice(87072, 87073, None),
 slice(75888, 75889, None),
 slice(81468, 81469, None),
 slice(81378, 81379, None),
 slice(68014, 68015, None),
 slice(84706, 84707, None),
 slice(95496, 95497, None),
 slice(5718, 5719, None),
 slice(20713, 20714, None),
 slice(3627, 3628, None),
 slice(36384, 36385, None),
 slice(3203, 3204, None),
 slice(21283, 21284, None),
 slice(15945, 15946, None),
 slice(8608, 8609, None),
 slice(25907, 25908, None),
 slice(7343, 7344, None),
 slice(44280, 44281, None),
 slice(55552, 55553, None),
 slice(50274, 50275, None),
 slice(26581, 26582, None),
 slice(68785, 68786, None),
 slice(44289, 44290, None),
 slice(3119, 3120, None),
 slice(38154, 38155, None),
 slice(52414, 52415, None),
 slice(26294, 26295, None),
 slice(79984, 79985, None),
 slice(29765, 29766, None),
 slice(31539, 31540, None),
 slice(67286, 67287, None),
 slice(20157, 20158, None),
 slice(76761, 76762, None),
 slice(24180, 24181, None),
 slice(6961, 6962, None),
 slice(25821, 25822, None),
 slice(62771, 62772, None),
 slice(16664, 16665, None),
 slice(10919, 10920, None),
 slice(13428, 13429, None),
 slice(45415, 45416, None),
 slice(69926, 69927, None),
 slice(35105, 35106, None),
 slice(41240, 41241, None),
 slice(42151, 42152, None),
 slice(4866, 4867, None),
 slice(55428, 55429, None),
 slice(9422, 9423, None),
 slice(37410, 37411, None),
 slice(41337, 41338, None),
 slice(41563, 41564, None),
 slice(25752, 25753, None),
 slice(9334, 9335, None),
 slice(77114, 77115, None),
 slice(87, 88, None),
 slice(6205, 6206, None),
 slice(41046, 41047, None),
 slice(37479, 37480, None),
 slice(4085, 4086, None),
 slice(35657, 35658, None),
 slice(68819, 68820, None),
 slice(72255, 72256, None),
 slice(9159, 9160, None),
 slice(88549, 88550, None),
 slice(97533, 97534, None),
 slice(28524, 28525, None),
 slice(90754, 90755, None),
 slice(9157, 9158, None),
 slice(83533, 83534, None),
 slice(10080, 10081, None),
 slice(2669, 2670, None),
 slice(79653, 79654, None),
 slice(64687, 64688, None),
 slice(28733, 28734, None),
 slice(55951, 55952, None),
 slice(95279, 95280, None),
 slice(27398, 27399, None),
 slice(19103, 19104, None),
 slice(62533, 62534, None),
 slice(68613, 68614, None),
 slice(80345, 80346, None),
 slice(2493, 2494, None),
 slice(35944, 35945, None),
 slice(36878, 36879, None),
 slice(13802, 13803, None),
 slice(43431, 43432, None),
 slice(25410, 25411, None),
 slice(84013, 84014, None),
 slice(19688, 19689, None),
 slice(52304, 52305, None),
 slice(63243, 63244, None),
 slice(42576, 42577, None),
 slice(55410, 55411, None),
 slice(70562, 70563, None),
 slice(83331, 83332, None),
 slice(19306, 19307, None),
 slice(74247, 74248, None),
 slice(74683, 74684, None),
 slice(10882, 10883, None),
 slice(14369, 14370, None),
 slice(14965, 14966, None),
 slice(20169, 20170, None),
 slice(89063, 89064, None),
 slice(38185, 38186, None),
 slice(89421, 89422, None),
 slice(35465, 35466, None),
 slice(52582, 52583, None),
 slice(13671, 13672, None),
 slice(58576, 58577, None),
 slice(86416, 86417, None),
 slice(9323, 9324, None),
 slice(29753, 29754, None),
 slice(33102, 33103, None),
 slice(75988, 75989, None),
 slice(70589, 70590, None),
 slice(85330, 85331, None),
 slice(91447, 91448, None),
 slice(28484, 28485, None),
 slice(72525, 72526, None),
 slice(90128, 90129, None),
 slice(82817, 82818, None),
 slice(76756, 76757, None),
 slice(16634, 16635, None),
 slice(85573, 85574, None),
 slice(80775, 80776, None),
 slice(73885, 73886, None),
 slice(49925, 49926, None),
 slice(31560, 31561, None),
 slice(24150, 24151, None),
 slice(45909, 45910, None),
 slice(10260, 10261, None),
 slice(19668, 19669, None),
 slice(23897, 23898, None),
 slice(33371, 33372, None),
 slice(33548, 33549, None),
 slice(83715, 83716, None),
 slice(84309, 84310, None),
 slice(81025, 81026, None),
 slice(70131, 70132, None),
 slice(66013, 66014, None),
 slice(74506, 74507, None),
 slice(92463, 92464, None),
 slice(70882, 70883, None),
 slice(58032, 58033, None),
 slice(25287, 25288, None),
 slice(49357, 49358, None),
 slice(74518, 74519, None),
 slice(72782, 72783, None),
 slice(63160, 63161, None),
 slice(28097, 28098, None),
 slice(75968, 75969, None),
 slice(42000, 42001, None),
 slice(40005, 40006, None),
 slice(55490, 55491, None),
 slice(73789, 73790, None),
 slice(9182, 9183, None),
 slice(93618, 93619, None),
 slice(16092, 16093, None),
 slice(6003, 6004, None),
 slice(36964, 36965, None),
 slice(31732, 31733, None),
 slice(71387, 71388, None),
 slice(72164, 72165, None),
 slice(643, 644, None),
 slice(19675, 19676, None),
 slice(25744, 25745, None),
 slice(73915, 73916, None),
 slice(554, 555, None),
 slice(21901, 21902, None),
 slice(17381, 17382, None),
 slice(43694, 43695, None),
 slice(69418, 69419, None),
 slice(63455, 63456, None),
 slice(64173, 64174, None),
 slice(58841, 58842, None),
 slice(4629, 4630, None),
 slice(41772, 41773, None),
 slice(14817, 14818, None),
 slice(16387, 16388, None),
 slice(79554, 79555, None),
 slice(7884, 7885, None),
 slice(10240, 10241, None),
 slice(27577, 27578, None),
 slice(81984, 81985, None),
 slice(7259, 7260, None),
 slice(31546, 31547, None),
 slice(60051, 60052, None),
 slice(25658, 25659, None),
 slice(81796, 81797, None),
 slice(63699, 63700, None),
 slice(35142, 35143, None),
 slice(92743, 92744, None),
 slice(39128, 39129, None),
 slice(70227, 70228, None),
 slice(46559, 46560, None),
 slice(85130, 85131, None),
 slice(35505, 35506, None),
 slice(63650, 63651, None),
 slice(55711, 55712, None),
 slice(12262, 12263, None),
 slice(58760, 58761, None),
 slice(81575, 81576, None),
 slice(29253, 29254, None),
 slice(41126, 41127, None),
 slice(7583, 7584, None),
 slice(45984, 45985, None),
 slice(21262, 21263, None),
 slice(60014, 60015, None),
 slice(4792, 4793, None),
 slice(80034, 80035, None),
 slice(95405, 95406, None),
 slice(95784, 95785, None),
 slice(14036, 14037, None),
 slice(11937, 11938, None),
 slice(83694, 83695, None),
 slice(34747, 34748, None),
 slice(76750, 76751, None),
 slice(70256, 70257, None),
 slice(8508, 8509, None),
 slice(43223, 43224, None),
 slice(36145, 36146, None),
 slice(26934, 26935, None),
 slice(63682, 63683, None),
 slice(16223, 16224, None),
 slice(24418, 24419, None),
 slice(28567, 28568, None),
 slice(19746, 19747, None),
 slice(72158, 72159, None),
 slice(63425, 63426, None),
 slice(74256, 74257, None),
 slice(2827, 2828, None),
 slice(18582, 18583, None),
 slice(38406, 38407, None),
 slice(83743, 83744, None),
 slice(93977, 93978, None),
 slice(73887, 73888, None),
 slice(75128, 75129, None),
 slice(57397, 57398, None),
 slice(40523, 40524, None),
 slice(66102, 66103, None),
 slice(74729, 74730, None),
 slice(82536, 82537, None),
 slice(51990, 51991, None),
 slice(85795, 85796, None),
 slice(37687, 37688, None),
 slice(47621, 47622, None),
 slice(9998, 9999, None),
 slice(88378, 88379, None),
 slice(64322, 64323, None),
 slice(1047, 1048, None),
 slice(78443, 78444, None),
 slice(37876, 37877, None),
 slice(52878, 52879, None),
 slice(8263, 8264, None),
 slice(3980, 3981, None),
 slice(31727, 31728, None),
 slice(34656, 34657, None),
 slice(30638, 30639, None),
 slice(31468, 31469, None),
 slice(25296, 25297, None),
 slice(33663, 33664, None),
 slice(78474, 78475, None),
 slice(90491, 90492, None),
 slice(74898, 74899, None),
 slice(88617, 88618, None),
 slice(40508, 40509, None),
 slice(27063, 27064, None),
 slice(8519, 8520, None),
 slice(41505, 41506, None),
 slice(36490, 36491, None),
 slice(66090, 66091, None),
 slice(49117, 49118, None),
 slice(46932, 46933, None),
 slice(35469, 35470, None),
 slice(52720, 52721, None),
 slice(54712, 54713, None),
 slice(73394, 73395, None),
 slice(55076, 55077, None),
 slice(75725, 75726, None),
 slice(94172, 94173, None),
 slice(66553, 66554, None),
 slice(51566, 51567, None),
 slice(28713, 28714, None),
 slice(24155, 24156, None),
 slice(54936, 54937, None),
 slice(80713, 80714, None),
 slice(30156, 30157, None),
 slice(84559, 84560, None),
 slice(89802, 89803, None),
 slice(83485, 83486, None),
 slice(27506, 27507, None),
 slice(91971, 91972, None),
 slice(90772, 90773, None),
 slice(29744, 29745, None),
 slice(15256, 15257, None),
 slice(72203, 72204, None),
 slice(81396, 81397, None),
 slice(85683, 85684, None),
 slice(45659, 45660, None),
 slice(2419, 2420, None),
 slice(58716, 58717, None),
 slice(66297, 66298, None),
 slice(90525, 90526, None),
 slice(29689, 29690, None),
 slice(2695, 2696, None),
 slice(72053, 72054, None),
 slice(78202, 78203, None),
 slice(37080, 37081, None),
 slice(45463, 45464, None),
 slice(10036, 10037, None),
 slice(52043, 52044, None),
 slice(66259, 66260, None),
 slice(71368, 71369, None),
 slice(7694, 7695, None),
 slice(42977, 42978, None),
 slice(67130, 67131, None),
 slice(80636, 80637, None),
 slice(29581, 29582, None),
 slice(8727, 8728, None),
 slice(86629, 86630, None),
 slice(76367, 76368, None),
 slice(63677, 63678, None),
 slice(16034, 16035, None),
 slice(45738, 45739, None),
 slice(51597, 51598, None),
 slice(5448, 5449, None),
 slice(46204, 46205, None),
 slice(2153, 2154, None),
 slice(5720, 5721, None),
 slice(53323, 53324, None),
 slice(51362, 51363, None),
 slice(19781, 19782, None),
 slice(48921, 48922, None),
 slice(38819, 38820, None),
 slice(81659, 81660, None),
 slice(84249, 84250, None),
 slice(4294, 4295, None),
 slice(30736, 30737, None),
 slice(67422, 67423, None),
 slice(12526, 12527, None),
 slice(91472, 91473, None),
 slice(42996, 42997, None),
 slice(24798, 24799, None),
 slice(65994, 65995, None),
 slice(87959, 87960, None),
 slice(63806, 63807, None),
 slice(90478, 90479, None),
 slice(83333, 83334, None),
 slice(78708, 78709, None),
 slice(90506, 90507, None),
 slice(38018, 38019, None),
 slice(72419, 72420, None),
 slice(38309, 38310, None),
 slice(80238, 80239, None),
 slice(75511, 75512, None),
 slice(67235, 67236, None),
 slice(76569, 76570, None),
 slice(64658, 64659, None),
 slice(74331, 74332, None),
 slice(75699, 75700, None),
 slice(38083, 38084, None),
 slice(21211, 21212, None),
 slice(48811, 48812, None),
 slice(13553, 13554, None),
 slice(5517, 5518, None),
 slice(12386, 12387, None),
 slice(14245, 14246, None),
 slice(22290, 22291, None),
 slice(18527, 18528, None),
 slice(58761, 58762, None),
 slice(91010, 91011, None),
 slice(25648, 25649, None),
 slice(12742, 12743, None),
 slice(18105, 18106, None),
 slice(27509, 27510, None),
 slice(6302, 6303, None),
 slice(8190, 8191, None),
 slice(19113, 19114, None),
 slice(43843, 43844, None),
 slice(14801, 14802, None),
 slice(23463, 23464, None),
 slice(52956, 52957, None),
 slice(29544, 29545, None),
 slice(70208, 70209, None),
 slice(46462, 46463, None),
 slice(96030, 96031, None),
 slice(4160, 4161, None),
 slice(57077, 57078, None),
 slice(70487, 70488, None),
 slice(8225, 8226, None),
 slice(21467, 21468, None),
 slice(24268, 24269, None),
 slice(97211, 97212, None),
 slice(57310, 57311, None),
 slice(76470, 76471, None),
 slice(7292, 7293, None),
 slice(53197, 53198, None),
 slice(80154, 80155, None),
 slice(82938, 82939, None),
 slice(720, 721, None),
 slice(42209, 42210, None),
 slice(81647, 81648, None),
 slice(77514, 77515, None),
 slice(24851, 24852, None),
 slice(29641, 29642, None),
 slice(57111, 57112, None),
 slice(56798, 56799, None),
 slice(74452, 74453, None),
 slice(31362, 31363, None),
 slice(3161, 3162, None),
 slice(66926, 66927, None),
 slice(70118, 70119, None),
 slice(59855, 59856, None),
 slice(44007, 44008, None),
 slice(67712, 67713, None),
 slice(82596, 82597, None),
 slice(9678, 9679, None),
 slice(68691, 68692, None),
 slice(64804, 64805, None),
 slice(72033, 72034, None),
 slice(86997, 86998, None),
 slice(85087, 85088, None),
 slice(26083, 26084, None),
 slice(90005, 90006, None),
 slice(85465, 85466, None),
 slice(34493, 34494, None),
 slice(62786, 62787, None),
 slice(37210, 37211, None),
 slice(12031, 12032, None),
 slice(38379, 38380, None),
 slice(35044, 35045, None),
 slice(22468, 22469, None),
 slice(67999, 68000, None),
 slice(82540, 82541, None),
 slice(85361, 85362, None),
 slice(12409, 12410, None),
 slice(42332, 42333, None),
 slice(60428, 60429, None),
 slice(11194, 11195, None),
 slice(85319, 85320, None),
 slice(46092, 46093, None),
 slice(9619, 9620, None),
 slice(1229, 1230, None),
 slice(90185, 90186, None),
 slice(94739, 94740, None),
 slice(64862, 64863, None),
 slice(78367, 78368, None),
 slice(22001, 22002, None),
 slice(2931, 2932, None),
 slice(49920, 49921, None),
 slice(71498, 71499, None),
 slice(37739, 37740, None),
 slice(55756, 55757, None),
 slice(30260, 30261, None),
 slice(13793, 13794, None),
 slice(2094, 2095, None),
 slice(41, 42, None),
 slice(37177, 37178, None),
 slice(75131, 75132, None),
 slice(45645, 45646, None),
 slice(70226, 70227, None),
 slice(93078, 93079, None),
 slice(88601, 88602, None),
 slice(45860, 45861, None),
 slice(9904, 9905, None),
 slice(48309, 48310, None),
 slice(82012, 82013, None),
 slice(90091, 90092, None),
 slice(38009, 38010, None),
 slice(75472, 75473, None),
 slice(500, 501, None),
 slice(21661, 21662, None),
 slice(66693, 66694, None),
 slice(70008, 70009, None),
 slice(858, 859, None),
 slice(17057, 17058, None),
 slice(21488, 21489, None),
 slice(32086, 32087, None),
 slice(61629, 61630, None),
 slice(67724, 67725, None),
 slice(44492, 44493, None),
 slice(51086, 51087, None),
 slice(10173, 10174, None),
 slice(75109, 75110, None),
 slice(58046, 58047, None),
 slice(73398, 73399, None),
 slice(66026, 66027, None),
 slice(46544, 46545, None),
 slice(47574, 47575, None),

In [80]:
phi.index

MultiIndex([('@lemmatized', 'JH2SC281XPM100187'),
            ('@lemmatized',            '3space'),
            ('@lemmatized',       'hypersphere'),
            ('@lemmatized',             'Bodin'),
            ('@lemmatized',          'jiggling'),
            ('@lemmatized',           'Millies'),
            ('@lemmatized',            'Millie'),
            ('@lemmatized',        'hemicrania'),
            ('@lemmatized',        'paroxysmal'),
            ('@lemmatized',          'kneecaps'),
            ...
            ('@lemmatized',           'crystal'),
            ('@lemmatized',       'Herpesvirus'),
            ('@lemmatized',          '9600baud'),
            ('@lemmatized',         'Decimates'),
            ('@lemmatized',        'Immunecell'),
            ('@lemmatized',      'herpesvirus6'),
            ('@lemmatized',            'Lussos'),
            ('@lemmatized',         'Sumarikis'),
            ('@lemmatized',             'Lusso'),
            ('@lemmatized',        'Priorities')],
           names=['modality', 'token'], length=114951)

In [81]:
common_word_model_indices = [
    phi.index.get_loc(w) for w in [('@lemmatized', 'JH2SC281XPM100187')]
]

In [82]:
common_word_model_indices

[0]

In [75]:
phi0.shape

(97541, 21)

In [76]:
phi.shape

(114951, 21)

In [ ]:
for k, r in results.items():
    r['scores']['coherence_20'] = float(r['scores']['coherence_20'])

In [ ]:
for k, r in results.items():
    with open(f'test_bt_results_{k}.json', 'w') as f:
        f.write(
            json.dumps(r, indent=4)
        )

In [37]:
! ls $seed_save_folder

dataset.csv  dataset__internals  phi.csv  top_words.json

In [8]:
dataset = Dataset(
    f'{RESULTS_FOLDER_PATH}/0/dataset.csv',
)

dataset.get_possible_modalities()

{'@lemmatized'}

In [9]:
MAIN_MODALITY = '@lemmatized'

In [10]:
dataset._data.head()

,Unnamed: 0,id,vw_text
id,,,
rec_autos_102994,0,rec_autos_102994,rec_autos_102994 |@lemmatized was wondering if...
comp_sys_mac_hardware_51861,1,comp_sys_mac_hardware_51861,comp_sys_mac_hardware_51861 |@lemmatized fair ...
comp_sys_mac_hardware_51879,2,comp_sys_mac_hardware_51879,comp_sys_mac_hardware_51879 |@lemmatized well ...
comp_graphics_38242,3,comp_graphics_38242,comp_graphics_38242 |@lemmatized Do you have W...
sci_space_60880,4,sci_space_60880,sci_space_60880 |@lemmatized From article C5ow...

In [11]:
phi0 = pd.read_csv(f'{RESULTS_FOLDER_PATH}/0/phi.csv', index_col=0)

In [12]:
phi0.head()

,background_1,topic_0,topic_1,topic_2,topic_3,topic_4,topic_5,topic_6,topic_7,topic_8,...,topic_10,topic_11,topic_12,topic_13,topic_14,topic_15,topic_16,topic_17,topic_18,topic_19
00,0.0,0.001167,0.000092,0.005393,0.0,0.001362,0.000000,0.000000,0.0,0.0,...,0.000737,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
000,0.0,0.000270,0.000051,0.004587,0.0,0.000254,0.000151,0.000000,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
0000,0.0,0.000050,0.000000,0.003186,0.0,0.000000,0.000000,0.000121,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
00000,0.0,0.000039,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
000000,0.0,0.000126,0.000000,0.000000,0.0,0.000473,0.000000,0.000000,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [13]:
phi0.shape

(97541, 21)

In [14]:
phi0.set_index([[MAIN_MODALITY] * len(phi0.index), phi0.index], inplace=True)

In [15]:
phi0.sum(axis=0)

background_1    6.419650
topic_0         6.345205
topic_1         6.062952
topic_2         6.507537
topic_3         6.308676
topic_4         6.537928
topic_5         6.431884
topic_6         6.305140
topic_7         6.767294
topic_8         5.938382
topic_9         5.970806
topic_10        6.570667
topic_11        6.863978
topic_12        5.966615
topic_13        6.075575
topic_14        6.103501
topic_15        5.832443
topic_16        6.409397
topic_17        6.341861
topic_18        5.961218
topic_19        5.698086
dtype: float64

In [16]:
min(phi0.sum(axis=0)), max(phi0.sum(axis=0))

(5.698085908033937, 6.8639784215610575)

In [17]:
dictionary = dataset.get_dictionary()

In [18]:
dictionary

artm.Dictionary(name=5e94fbf5-85b7-46b0-bf46-29cfb34b910f, num_entries=114951)

In [19]:
def calc_doc_occurrences(dataset, modality):
    """
    :param n_dw_matrix: sparse document-word matrix, shape is D x W
    :return: sparse matrix of co-occurrences

    doc_occurrences[w1, w2] = the number of the documents
    where there are w1 and w2
    """
    n_dw_matrix = dataset2sparse_matrix(dataset, modality, modalities_to_use=[modality])
    matrix = (scipy.sparse.csc_matrix(n_dw_matrix) > 0).astype(int)
    co_occurrences = matrix.T * matrix

    return co_occurrences.diagonal(), co_occurrences


def create_pmi_top_function(
    doc_occurrences, doc_co_occurrences,
    documents_number, top_sizes,
    topic_indices,
    co_occurrences_smooth=1.
):
    """
    :param doc_occurrences: array of doc occurrences of words
    :param doc_co_occurrences: sparse matrix of doc co-occurrences of words
    :param documents_number: number of the documents
    :param top_sizes: list of top values to calculate top-pmi for
    :param co_occurrences_smooth: constant to smooth co-occurrences in log
    :return: function which takes phi and theta and returns
    pair of two arrays: pmi-s of the tops and ppmi-s of the tops

    pmi[i] - pmi(top of size top_sizes[i])
    ppmi[i] - ppmi(top of size top_sizes[i])

    pmi(words) = sum_{u in words, v in words, u != v}
    log(
        (doc_co_occurrences[u, v] * documents_number + co_occurrences_smooth)
        / doc_occurrences[u] / doc_occurrences[v]
    )

    ppmi(words) = sum_{u in words, v in words, u != v}
    max(log(
        (doc_co_occurrences[u, v] * documents_number + co_occurrences_smooth)
        / doc_occurrences[u] / doc_occurrences[v]
    ), 0)

    """
    def func(phi):
        _T, W = phi.shape
        T = len(topic_indices)

        max_top_size = max(top_sizes)
        topic_pmis, topic_ppmis = dict(), dict()
        pmi, ppmi = np.zeros(max_top_size), np.zeros(max_top_size)
        tops = np.argpartition(phi, -max_top_size, axis=1)[:, -max_top_size:]
        
        for t in topic_indices:
            top = sorted(tops[t], key=lambda w: - phi[t, w])
            co_occurrences = doc_co_occurrences[top, :][:, top].todense()
            occurrences = doc_occurrences[top]
            values = np.log(
                (co_occurrences * documents_number + co_occurrences_smooth)
                / (occurrences[:, np.newaxis] * occurrences[np.newaxis, :] + co_occurrences_smooth)
            )
            diag = np.diag_indices(len(values))
            # values.cumsum(axis=0).cumsum(axis=1)[diag] - values[diag].cumsum()

            current_pmi = np.array(
               values.cumsum(axis=0).cumsum(axis=1)[diag] - values[diag].cumsum()
            ).ravel()
            topic_pmis[t] = current_pmi
            pmi += current_pmi

            values[values < 0.] = 0.
            current_ppmi = np.array(
               values.cumsum(axis=0).cumsum(axis=1)[diag] - values[diag].cumsum()
            ).ravel()
            topic_ppmis[t] = current_ppmi
            ppmi += current_ppmi
            
        sizes = np.arange(2, max_top_size + 1)
        pmi[1:] /= (T * sizes * (sizes - 1))
        ppmi[1:] /= (T * sizes * (sizes - 1))
        indices = np.array(top_sizes) - 1

        for t in topic_indices:
            topic_pmis[t][1:] /= (sizes * (sizes - 1))
            topic_ppmis[t][1:] /= (sizes * (sizes - 1))

        result_topic_pmis = {t: p[indices] for t, p in topic_pmis.items()}
        result_topic_ppmis = {t: p[indices] for t, p in topic_ppmis.items()}

        return pmi[indices], ppmi[indices], result_topic_pmis, result_topic_ppmis

    return func

In [20]:
%%time

occurences, co_occurences = calc_doc_occurrences(dataset, MAIN_MODALITY)

CPU times: user 6.77 s, sys: 312 ms, total: 7.08 s
Wall time: 7 s

In [21]:
calc_pmi = create_pmi_top_function(
    occurences, co_occurences,
    dataset.get_dataset().shape[0], [20],
    topic_indices=[0, 1, 2],
    co_occurrences_smooth=1e-2,
)

In [22]:
class TopTokenCoherence(BaseTopicNetScore):
    def __init__(self, name, func):
        super().__init__()

        self._name = name
        self.calc_pmi = func

    def call(self, model: TopicModel):
        values = self.calc_pmi(model.get_phi_dense()[0].T)

        return values[1]

    def call_by_topic(self, model: TopicModel):
        values = self.calc_pmi(model.get_phi_dense()[0].T)

        return values[3]

In [23]:
def view_model(
        topic_model,
        dataset,
        num_top_tokens: int = 5,
        top_tokens_method: str = 'phi',
        num_topics: Optional[int] = 5,  # we do not want to fill the whole .ipynb notebook with topics...
        ):
    top_tok_viewer = TopTokensViewer(
        topic_model, num_top_tokens=num_top_tokens, method=top_tokens_method
    )
    top_doc_viewer = TopDocumentsViewer(topic_model, dataset=dataset)
    top_docs = top_doc_viewer.view()

    if num_topics is None:
        num_topics = len(topic_model.topic_names)

    for topic_name in topic_model.topic_names[:num_topics]:
        topic_top_toks = top_tok_viewer.to_html(topic_names=[topic_name])
        topic_top_docs = top_docs[topic_name]
        display_html(topic_top_toks, raw=True)
        display(topic_top_docs)

In [24]:
class FastFixPhiRegularizer(BaseRegularizer):
    _VERY_BIG_TAU = 10 ** 9

    def __init__(self, name: str, topic_names: List[str], parent_model=None, parent_phi=None):
        super().__init__(name, tau=self._VERY_BIG_TAU)

        self._topic_names = topic_names
        self._topic_indices = None
        self._parent_model = parent_model
        self._parent_phi = parent_phi

    def grad(self, pwt, nwt):
        # print('Fixing')

        rwt = np.zeros_like(pwt)

        if self._parent_phi is not None:
            parent_phi = self._parent_phi
            vals = parent_phi.values
        else:
            parent_phi = self._parent_model.get_phi()
            vals = parent_phi.values[:, self._topic_indices]

        assert vals.shape[0] == rwt.shape[0]
        assert vals.shape[1] == len(self._topic_indices)
        
        rwt[:, self._topic_indices] += vals

        return self.tau * rwt

    def attach(self, model):
        super().attach(model)
        
        phi = self._model.get_phi()
        self._topic_indices = [
            phi.columns.get_loc(topic_name)
            for topic_name in self._topic_names
        ]

In [25]:
NUM_TOPICS = 20
NUM_ITERATIONS = 5
NUM_TOP_TOKENS = 20

In [26]:
NUM_TOPICS

20

In [47]:
def fit_and_compute_scores(model, dataset, target_topic_indices=None, custom_regularizers=None):
    print(custom_regularizers)

    model._fit(dataset.get_batch_vectorizer(), num_iterations=NUM_ITERATIONS, custom_regularizers=custom_regularizers)

    score_values = {
        'perplexity': model.scores[f'PerplexityScore{MAIN_MODALITY}'][-1],
    }

    phi = model.get_phi()

    # Currently all topics are taken into account

    if target_topic_indices is None:
        target_topic_indices = list(range(NUM_TOPICS))  # phi.columns.get_loc()

    target_topic_names = [phi.columns[i] for i in target_topic_indices]

    top = NUM_TOP_TOKENS
    coherence_score = TopTokenCoherence(
        name=f'coherence_{top}',
        func=create_pmi_top_function(
            occurences, co_occurences,
            dataset.get_dataset().shape[0], [top],
            topic_indices=target_topic_indices,
            co_occurrences_smooth=1e-2,
        )
    )

    value = coherence_score.call(model)
    score_values[coherence_score._name] = value
    topic_coherences = coherence_score.call_by_topic(model)
    topic_coherences = {t: float(v) for t, v in topic_coherences.items()}

    diversity_scores = [
        DiversityScore(
            name=f'diversity_{metric}',
            metric=metric,
            topic_names=target_topic_names,
            class_ids=MAIN_MODALITY,
        )
    
        for metric in KNOWN_METRICS
    ]
    
    for score in diversity_scores:
        value = score.call(model)
        score_values[score._name] = value

    return {
        'scores': score_values,
        'topic_coherences': topic_coherences,
    }

In [28]:
def init_model_from_family(
        family: str or KnownModel,
        dataset: Dataset,
        main_modality: str,
        num_topics: int,
        seed: int,
        specific_topic_names = None,
        modalities_to_use: List[str] = None,
        num_processors: int = 3,
        model_params: dict = None,
):
    """
    Returns
    -------
    model: TopicModel() instance
    """
    if isinstance(family, KnownModel):
        family = family.value

    if modalities_to_use is None:
        modalities_to_use = [main_modality]

    custom_regs = {}

    if family == "LDA":
        model = init_lda(
            dataset, modalities_to_use, main_modality, num_topics, model_params
        )
    elif family == "PLSA":
        model = init_plsa(
            dataset, modalities_to_use, main_modality, num_topics
        )
    elif family == "TARTM":
        model, custom_regs = init_thetaless(
            dataset, modalities_to_use, main_modality, num_topics, model_params
        )
    elif family == "sparse":
        model = init_bcg_sparse_model(
            dataset, modalities_to_use, main_modality, num_topics, 1, model_params
        )
    elif family == "decorrelation":
        model = init_decorrelated_plsa(
            dataset, modalities_to_use, main_modality, num_topics, model_params
        )
    elif family == "ARTM":
        model = init_baseline_artm(
            dataset, modalities_to_use, main_modality, num_topics, 1, specific_topic_names, model_params
        )
    else:
        raise ValueError(f'family: {family}')

    model.num_processors = num_processors

    if seed is not None:
        model.seed = seed

    dictionary = dataset.get_dictionary()

    # TODO: maybe this cycle is not necessary
    for modality in dataset.get_possible_modalities():
        if modality not in modalities_to_use:
            dictionary.filter(class_id=modality, max_df=0, inplace=True)

    model.initialize(dictionary)
    add_standard_scores(model, dictionary, main_modality=main_modality,
                        all_modalities=modalities_to_use)

    model = TopicModel(
        artm_model=model,
        custom_regularizers=custom_regs
    )

    return model


def init_bcg_sparse_model(
        dataset,
        modalities_to_use,
        main_modality,
        specific_topics,
        bcg_topics,
        specific_topic_names = None,
        model_params: dict = None
):
    """
    Creates simple artm model with standard scores.

    Parameters
    ----------
    dataset : Dataset
    modalities_to_use : list of str or dict
    main_modality : str
    specific_topics : int
    bcg_topics : int

    Returns
    -------
    model: artm.ARTM() instance
    """
    if model_params is None:
        model_params = dict()

    model = init_plsa(
        dataset, modalities_to_use, main_modality, specific_topics, bcg_topics
    )
    background_topic_names = model.topic_names[-bcg_topics:]

    if specific_topic_names is None:
        print('No spec topics')
        specific_topic_names = model.topic_names[:-bcg_topics]

    dictionary = dataset.get_dictionary()
    baseline_class_ids = {class_id: 1 for class_id in modalities_to_use}
    data_stats = count_vocab_size(dictionary, baseline_class_ids)

    # all coefficients are relative
    regularizers = [
        artm.SmoothSparsePhiRegularizer(
             name='smooth_phi_bcg',
             topic_names=background_topic_names,
             tau=model_params.get("smooth_bcg_tau", 0.1),
             class_ids=[main_modality],
        ),
        artm.SmoothSparseThetaRegularizer(
             name='smooth_theta_bcg',
             topic_names=background_topic_names,
             tau=model_params.get("smooth_bcg_tau", 0.1),
        ),
        artm.SmoothSparsePhiRegularizer(
             name='sparse_phi_sp',
             topic_names=specific_topic_names,
             tau=model_params.get("sparse_sp_tau", -0.05),
             class_ids=[main_modality],
            ),
        artm.SmoothSparseThetaRegularizer(
             name='sparse_theta_sp',
             topic_names=specific_topic_names,
             tau=model_params.get("sparse_sp_tau", -0.05),
        ),
    ]
    for reg in regularizers:
        model.regularizers.add(transform_regularizer(
            data_stats,
            reg,
            model.class_ids,
            n_topics=len(reg.topic_names)
        ))

    return model


def init_baseline_artm(
        dataset,
        modalities_to_use,
        main_modality,
        num_topics,
        bcg_topics,
        specific_topic_names = None,
        model_params: dict = None,
):
    """
    Creates simple artm model with standard scores.

    Parameters
    ----------
    dataset : Dataset
    modalities_to_use : list of str
    main_modality : str
    num_topics : int

    Returns
    -------
    model: artm.ARTM() instance
    """
    if model_params is None:
        model_params = dict()

    model = init_bcg_sparse_model(
        dataset, modalities_to_use, main_modality, num_topics, bcg_topics, specific_topic_names, model_params
    )

    if specific_topic_names is None:
        print('No spec topics')
        specific_topic_names = model.topic_names[:-bcg_topics]

    model.regularizers.add(
        artm.DecorrelatorPhiRegularizer(
            gamma=0,
            tau=model_params.get('decorrelation_tau', 0.01),
            name='decorrelation',
            topic_names=specific_topic_names,
            class_ids=modalities_to_use,
        )
    )

    return model

In [29]:
NUM_TRAINS = 3
TOPIC_INDICES = list(range(NUM_TOPICS))

In [30]:
TOPIC_INDICES

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [31]:
NUM_TOPICS

20

In [32]:
model = init_model_from_family(
    family=KnownModel.PLSA,
    dataset=dataset,
    main_modality=MAIN_MODALITY,
    num_topics=NUM_TOPICS + 1,  # background
    seed=0
)

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

In [33]:
model.get_phi().shape

(114951, 21)

In [34]:
phi = model.get_phi()

In [35]:
phi.columns

Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'topic_20'],
      dtype='object')

In [36]:
assert phi.shape[1] == phi0.shape[1], (phi.shape[1], phi0.shape[1])

In [37]:
common_words = list(set(phi.index).intersection(phi0.index))

phi.loc[:, :] = 0
phi.loc[common_words,:] += phi0.loc[common_words,:]

phi = phi / phi.sum(axis=0)

In [38]:
phi.shape

(114951, 21)

In [39]:
with open(f'{RESULTS_FOLDER_PATH}/0/top_words.json', 'r') as f:
    top_words = json.loads(f.read())

In [40]:
top_words.keys()

dict_keys(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5', 'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11', 'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17', 'topic_18', 'topic_19'])

In [43]:
DIFF_THRESHOLD = 2

In [44]:
for t, topic_top_words in top_words.items():
    print(t)
    # print(top_words)

    top_phi = set(phi[t].sort_values(ascending=False)[:NUM_TOP_TOKENS].index.get_level_values(1))
    top_bt = set([p[0] for p in topic_top_words])

    if top_phi != top_bt:
        diff1 = top_phi.difference(top_bt)
        diff2 = top_bt.difference(top_phi)

        print('  WTF:', diff1, diff2)

        if len(diff1) > DIFF_THRESHOLD:
            print(f'  WTF?!?!?', len(diff1))

        if len(diff2) > DIFF_THRESHOLD:
            print(f'  WTF?!?!?', len(diff2))
        

# Whatever...

topic_0
topic_1
topic_2
  WTF: {'good'} {'nhl'}
topic_3
topic_4
topic_5
  WTF: {'doctors', 'banks'} {'gordon', 'n3jxp'}
topic_6
  WTF: {'dont', 'ottoman', 'saw', 'government', 'know', 'started'} {'armenian', 'turks', 'sumgait', 'azerbaijan', 'armenians', 'armenia'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_7
  WTF: {'L2PMABGZ7VAZV0PZRI', 'NikeCajun', '207556000', 'effortsall', 'knowlege', '8800CS', 'CDROMCATZIP', 'dragdrop', 'toolbox', 'ringleaders', 'CSCSTD00385', '1795', 'taxation', '5152940082', 'Epilepsy'} {''}
  WTF?!?!? 15
topic_8
topic_9
  WTF: {'social'} {'lsd'}
topic_10
topic_11
  WTF: {'vol', 'writing', 'molecular', 'manual'} {'vernor', 'vinge', 'baen', 'gibson'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_12
  WTF: {'king', 'forget', 'computer', 'rule', 'guide'} {'douglas', 'adams', 'altima', 'alice', 'infiniti'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_13
  WTF: {'students', 'andrew', 'pm', 'cs'} {'jstmp', 'carnegie', 'mellon', 'japan'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_14
topic_15
  WTF: {'stripped', 'regards'} {'babak', 'sehari'}
topic_16
  WTF: {'vent', 'problem', 'cookie'} {'pistrix', 'lesabre', 'sanjay'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_17
  WTF: {'vending', 'patchmaking', 'unpatentable', 'remixed'} {'cocacola', 'cola', 'yerazunis', 'pepsi'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_18
  WTF: {'promote'} {'fenholt'}
topic_19
  WTF: {'mole', '1080'} {'avagadros', 'menuts'}

In [48]:
phi.columns

Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'topic_20'],
      dtype='object')

In [51]:
fix_regularizer = FastFixPhiRegularizer(
    name='fix',
    parent_phi=phi.iloc[:, 1:],
    topic_names=phi.columns[1:],
)

custom_regularizers = {
    fix_regularizer.name: fix_regularizer,
}

result = fit_and_compute_scores(
    model, dataset,
    target_topic_indices=list(range(phi.shape[1])),
    custom_regularizers=custom_regularizers
)

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f992830dee0>}

In [53]:
result

{'scores': {'perplexity': 2334.455078125,
  'coherence_20': array([1.4539663]),
  'diversity_euclidean': 0.11831513976417281,
  'diversity_jensenshannon': 0.7622861942596016,
  'diversity_hellinger': 0.882083585763223,
  'diversity_cosine': 0.8845350885792939},
 'topic_coherences': {0: 0.2332319384114421,
  1: 0.7828129948159336,
  2: 1.6570045095465096,
  3: 1.0912535311363014,
  4: 1.9160995627076196,
  5: 1.515770697307198,
  6: 1.0234783229373245,
  7: 0.05614310769281872,
  8: 1.5587540470905896,
  9: 2.1618052278586286,
  10: 1.7600162217628093,
  11: 1.3728873168770976,
  12: 1.5945788250399215,
  13: 1.3113348631878727,
  14: 3.7567500660203463,
  15: 1.3770167995683047,
  16: 2.3764950147175274,
  17: 2.150769177059853,
  18: 1.1946909515501167,
  19: 1.6025324815271995,
  20: 0.03986670434526436}}

In [54]:
result['scores']

{'perplexity': 2334.455078125,
 'coherence_20': array([1.4539663]),
 'diversity_euclidean': 0.11831513976417281,
 'diversity_jensenshannon': 0.7622861942596016,
 'diversity_hellinger': 0.882083585763223,
 'diversity_cosine': 0.8845350885792939}

In [55]:
cheatty_ppl = result['scores']['perplexity']

In [56]:
cheatty_ppl

2334.455078125

In [57]:
model = init_model_from_family(
    family=KnownModel.PLSA,
    dataset=dataset,
    main_modality=MAIN_MODALITY,
    num_topics=NUM_TOPICS,
    seed=0
)

phi = model.get_phi()

assert phi.shape[1] == phi0.shape[1] - 1

common_words = list(set(phi.index).intersection(phi0.index))

phi.loc[:, :] = 0
phi.loc[common_words, :] += phi0.loc[common_words, phi.columns]

assert set(phi0.columns).difference(set(phi.columns)) == {'background_1'}

phi = phi / phi.sum(axis=0)

fix_regularizer = FastFixPhiRegularizer(
    name='fix',
    parent_phi=phi,
    topic_names=phi.columns,
)
custom_regularizers = {
    fix_regularizer.name: fix_regularizer,
}

result = fit_and_compute_scores(model, dataset, custom_regularizers=custom_regularizers)

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f9928fafdf0>}

In [58]:
result

{'scores': {'perplexity': 116999.8359375,
  'coherence_20': array([1.59646966]),
  'diversity_euclidean': 0.11651928466902746,
  'diversity_jensenshannon': 0.7540381700256178,
  'diversity_hellinger': 0.8895890345296852,
  'diversity_cosine': 0.8593474498289518},
 'topic_coherences': {0: 0.8065581739518853,
  1: 0.7828129948159336,
  2: 1.6570045095465096,
  3: 1.0912535311363014,
  4: 1.9160995627076196,
  5: 1.515770697307198,
  6: 1.0234783229373245,
  7: 0.9326767872324533,
  8: 1.5587540470905896,
  9: 2.1618052278586286,
  10: 1.7600162217628093,
  11: 1.3728873168770976,
  12: 1.5945788250399215,
  13: 1.3113348631878727,
  14: 3.7567500660203463,
  15: 1.3770167995683051,
  16: 2.3764950147175274,
  17: 2.136876804854279,
  18: 1.1946909515501167,
  19: 1.6025324815271995}}

In [59]:
result['scores']['cheatty_ppl'] = cheatty_ppl
result['scores']['fair_ppl'] = result['scores']['perplexity']

In [60]:
result

{'scores': {'perplexity': 116999.8359375,
  'coherence_20': array([1.59646966]),
  'diversity_euclidean': 0.11651928466902746,
  'diversity_jensenshannon': 0.7540381700256178,
  'diversity_hellinger': 0.8895890345296852,
  'diversity_cosine': 0.8593474498289518,
  'cheatty_ppl': 2334.455078125,
  'fair_ppl': 116999.8359375},
 'topic_coherences': {0: 0.8065581739518853,
  1: 0.7828129948159336,
  2: 1.6570045095465096,
  3: 1.0912535311363014,
  4: 1.9160995627076196,
  5: 1.515770697307198,
  6: 1.0234783229373245,
  7: 0.9326767872324533,
  8: 1.5587540470905896,
  9: 2.1618052278586286,
  10: 1.7600162217628093,
  11: 1.3728873168770976,
  12: 1.5945788250399215,
  13: 1.3113348631878727,
  14: 3.7567500660203463,
  15: 1.3770167995683051,
  16: 2.3764950147175274,
  17: 2.136876804854279,
  18: 1.1946909515501167,
  19: 1.6025324815271995}}

In [62]:
results = dict()

results[0] = result

In [63]:
for k, r in results.items():
    r['scores']['coherence_20'] = float(r['scores']['coherence_20'])

In [64]:
results

{0: {'scores': {'perplexity': 116999.8359375,
   'coherence_20': 1.5964696599844959,
   'diversity_euclidean': 0.11651928466902746,
   'diversity_jensenshannon': 0.7540381700256178,
   'diversity_hellinger': 0.8895890345296852,
   'diversity_cosine': 0.8593474498289518,
   'cheatty_ppl': 2334.455078125,
   'fair_ppl': 116999.8359375},
  'topic_coherences': {0: 0.8065581739518853,
   1: 0.7828129948159336,
   2: 1.6570045095465096,
   3: 1.0912535311363014,
   4: 1.9160995627076196,
   5: 1.515770697307198,
   6: 1.0234783229373245,
   7: 0.9326767872324533,
   8: 1.5587540470905896,
   9: 2.1618052278586286,
   10: 1.7600162217628093,
   11: 1.3728873168770976,
   12: 1.5945788250399215,
   13: 1.3113348631878727,
   14: 3.7567500660203463,
   15: 1.3770167995683051,
   16: 2.3764950147175274,
   17: 2.136876804854279,
   18: 1.1946909515501167,
   19: 1.6025324815271995}}}

In [ ]:
for k, r in results.items():
    with open(f'test_bt_results_{k}.json', 'w') as f:
        f.write(
            json.dumps(r, indent=4)
        )

In [128]:
('@word', 'nsa') in model.get_phi().index

False

In [127]:
for d in dataset._data['vw_text']:
    if 'zq6kkf8hkjoj5jcwcfper6j' in d:
        print(d)

In [59]:
phi0.iloc[:, 0] > 0

@word  00          True
       000         True
       0000        True
       00000      False
       000000     False
                  ...
       zz960      False
       zzc2       False
       zzzs       False
       zzzzzz      True
       zzzzzzt     True
Name: topic_0, Length: 97851, dtype: bool

In [99]:
phi = model.get_phi()

In [100]:
phi0.sum(axis=0)

topic_0      3.563466
topic_1      3.105079
topic_2      2.712872
topic_3      2.873670
topic_4      2.740778
               ...
topic_141    4.756303
topic_142    3.229138
topic_143    2.920812
topic_144    3.076361
topic_145    2.709027
Length: 146, dtype: float64

In [101]:
phi.shape[1], phi0.shape[1]

(146, 146)

In [102]:
common_words = list(set(phi.index).intersection(phi0.index))

In [103]:
phi.loc[:, :] = 0

In [104]:
phi.sum(axis=0)

topic_0      0.0
topic_1      0.0
topic_2      0.0
topic_3      0.0
topic_4      0.0
            ...
topic_141    0.0
topic_142    0.0
topic_143    0.0
topic_144    0.0
topic_145    0.0
Length: 146, dtype: float32

In [105]:
phi0.columns

Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9',
       ...
       'topic_136', 'topic_137', 'topic_138', 'topic_139', 'topic_140',
       'topic_141', 'topic_142', 'topic_143', 'topic_144', 'topic_145'],
      dtype='object', length=146)

In [106]:
phi.loc[common_words,:] += phi0.loc[common_words,:]

In [107]:
phi.sum(axis=0)

topic_0      2.803020
topic_1      2.900242
topic_2      2.579136
topic_3      2.616285
topic_4      2.573774
               ...
topic_141    3.882989
topic_142    3.013007
topic_143    2.576366
topic_144    2.883666
topic_145    2.496880
Length: 146, dtype: float64

In [108]:
min(phi.sum(axis=0)), max(phi.sum(axis=0))

(2.2481894708336334, 3.8829893193144196)

In [109]:
phi = phi / phi.sum(axis=0)

In [129]:
phi['topic_0'].sort_values(ascending=False)[:10]

modality  token
@word     team       0.003889
          game       0.003540
          he         0.003227
          season     0.002869
          games      0.002801
          players    0.002687
          play       0.002677
          hockey     0.002592
          year       0.002399
          league     0.002248
Name: topic_0, dtype: float64

In [122]:
set(phi['topic_0'].sort_values(ascending=False)[:10].index.get_level_values(1))

{'game',
 'games',
 'he',
 'hockey',
 'league',
 'play',
 'players',
 'season',
 'team',
 'year'}

In [114]:
with open(DATA_FOLDER_PATH + '/test_bt_topwords.json', 'r') as f:
    bt_topwords = json.loads(f.read())

In [131]:
for t, top_words in bt_topwords.items():
    print(t)
    # print(top_words)

    top_phi = set(phi[t].sort_values(ascending=False)[:NUM_TOP_TOKENS].index.get_level_values(1))
    top_bt = set([p[0] for p in top_words])

    if top_phi != top_bt:
        print(top_phi.difference(top_bt), top_bt.difference(top_phi))

# Whatever...

topic_0
topic_1
topic_2
{'is'} {'nsa'}
topic_3
topic_4
{'have'} {'fbi'}
topic_5
topic_6
topic_7
topic_8
{'that'} {'ssf'}
topic_9
topic_10
topic_11
{'users', 'of'} {'o157h7', 'hus'}
topic_12
topic_13
topic_14
topic_15
{'program'} {'jfif'}
topic_16
topic_17
{'code'} {'null'}
topic_18
{'typinginjuryfaqgeneral', 'Neuhaus', 'scoresheets', 'attacks', 'Ellen', 'ecclesisatical', 'GrayHound', 'wraptype', 'OConnor', 'antibiotic', 'directors', '437', '258bit'} {''}
topic_19
topic_20
topic_21
{'it'} {'bj200'}
topic_22
topic_23
topic_24
{'gaybi', 'as', 'dont'} {'enviroleague', 'cramer', 'bsa'}
topic_25
{'size'} {'mathcad'}
topic_26
topic_27
topic_28
{'university', 'history', 'they', 'had', 'population'} {'turks', 'armenian', 'armenians', 'armenia', 'argic'}
topic_29
{'book', 'as', 'prophets'} {'quran', 'muhammad', 'rushdie'}
topic_30
topic_31
{'card', 'devices'} {'scsi2', 'scsi1'}
topic_32
{'duo'} {'irqs'}
topic_33
{'adventure', 'interested'} {'snes', 'sega'}
topic_34
topic_35
{'can', 'provides'} {'grafsys', 'plplot'}
topic_36
{'is', 'that', 'field'} {'judas', 'decenso', 'matthew'}
topic_37
{'have', 'software'} {'pmp', 'ccitt'}
topic_38
{'republicans', 'years', 'didnt'} {'duke', 'hillary', 'gritz'}
topic_39
{'with'} {'fsk'}
topic_40
{'to', 'deficits', 'block', 'care'} {'vat', 'gnp', 'reagan', 'clintons'}
topic_41
{'agent', 'that', 'his', 'testimony', 'he'} {'harris', 'atlantic', 'degan', 'spence', 'cooper'}
topic_42
{'his', 'to', 'that', 'he'} {'chancellor', 'dg', 'hitler', 'limbaugh'}
topic_43
{'try', 'includes', 'bored'} {'dss', 'ets', 'gre'}
topic_44
{'hinting'} {'atm'}
topic_45
topic_46
topic_47
topic_48
topic_49
{'and', 'empire', 'killed', 'government', 'turkey', 'rights', 'by', 'henrik', 'their'} {'cyprus', 'turks', 'yalcin', 'greece', 'salonica', 'cypriot', 'pkk', 'onur', 'thrace'}
topic_50
{'unfulfilled', 'waffle', 'seconded'} {'c5j0tk52blazecsjhuedu', 'zbibs', 'christie'}
topic_51
topic_52
{'mosaic', 'like', 'courtesy', 'advance', 'test', 'fixed', 'xarchie'} {'x11', 'ncd', 'xremote', 'xrunner', 'xtm', 'urls', 'ncsa'}
topic_53
{'abuse'} {'lsd'}
topic_54
{'be', 'features', 'run', 'multiuser', 'operating'} {'nt', 'c7', 'os2', 'vc', 'chicogo'}
topic_55
topic_56
{'summer', 'young'} {'myers', 'stephanopoulos'}
topic_57
{'that', 'nature'} {'larsons', 'larson'}
topic_58
{'us', 'didnt', 'went', 'people'} {'azerbaijan', 'armenian', 'armenians', 'sumgait'}
topic_59
topic_60
topic_61
topic_62
topic_63
{'photocd', 'upgrade', 'my', 'multisession', 'with'} {'3m', 'cdtechnology', 'trantor', 'nec', 'md'}
topic_64
{'ciphers', 'and'} {'rsa', 'ripem'}
topic_65
{'sell', 'vehicle'} {'perth', 'ser'}
topic_66
topic_67
topic_68
{'good', 'hard', 'send', 'copyright'} {'gibson', 'baen', 'vinge', 'vernor'}
topic_69
topic_70
{'formats', 'format'} {'pci', 'sgi'}
topic_71
topic_72
{'myintvar', 'smartcan'} {'spss', 'ndw'}
topic_73
{'jones', 'love', 'following', 'singles', 'elvis', 'vinyl', 'shipping', 'brooks', 'dance', 'postage'} {'sleeve545', 'sleeve10', 'sleeve1045', 'london', 'sleeve1545', 'promopicture', 'dec', 'sep', 'jun', 'mccartney'}
topic_74
{'apples'} {'nec'}
topic_75
{'ceiling'} {'hotelco'}
topic_76
{'144k', 'khz'} {'pcboard', 'celp'}
topic_77
topic_78
{'turbo'} {'supra'}
topic_79
topic_80
{'imake', 'referenced', 'aix', 'xwindows', 'referencing', 'directive'} {'lxmu', 'lx11', 'lxext', 'libxmulibxmuso', 'liblibx11so', 'libxmulibxmua'}
topic_81
topic_82
{'deci', 'simulatenously', 'revolutionized'} {'decibell', 'ohmite', 'dbm'}
topic_83
{'awful'} {'ch'}
topic_84
{'was'} {'mormons'}
topic_85
topic_86
{'pickup', 'drives'} {'mactools', 'irwin'}
topic_87
topic_88
{'conditioning', 'auto'} {'r12', 'militech'}
topic_89
{'intrinsics'} {'r3'}
topic_90
{'request'} {'x11r5'}
topic_91
{'lines', 'screen', 'problems', 'annoying', 'image', 'one'} {'t560i', 'nanao', 'viewsonic', 'mitsubishi', 'nec', '5fg'}
topic_92
{'color'} {'mb80'}
topic_93
{'lord', 'holy', 'st', 'father', 'son'} {'maria', 'alessandro', 'aloysius', 'mary', 'joseph'}
topic_94
{'safeties', 'safe', 'but', 'auto', 'round'} {'glock', 'kratz', 'm16', 'glocks', 'ar15'}
topic_95
{'my', '0x0', 'mask'} {'mod2mask', 'mod3mask', 'xlookupstring'}
topic_96
topic_97
{'of', 'frontline', 'peace', 'aid', 'oil', 'usa', 'in', 'movement'} {'iraq', 'irans', 'somalia', 'kuwaitis', 'mumin', 'iran', 'iranian', 'mack'}
topic_98
topic_99
{'hunting', 'floor', 'handguns', 'waiting', 'amendment'} {'nra', 'hb', 'senate', 'sb', 'hci'}
topic_100
{'twopiece'} {'aerostitch'}
topic_101
topic_102
{'35894', '8371174', '7303169'} {'uunetingrb30catbytedtmedin', 'ssdnetworking', 'medin'}
topic_103
topic_104
{'invisible'} {'euclidean'}
topic_105
{'socket', 'focus', 'si', 'technicallyhip', 'cage', 'apple', 'gadget'} {'lclcii', 'spigot', 'lclc', 'marvins', 'etherlan', 'pds', 'lciii'}
topic_106
{'motorcyclists', 'lighten', 'dont'} {'beav', 'dwi', 'dwidui'}
topic_107
{'card', 'hello'} {'sb', 'microsofts'}
topic_108
{'colorcell', '143'} {'xmugetcolormapallocation', 'xalloccolor'}
topic_109
{'name', 'english'} {'ishtar', 'bede'}
topic_110
{'bugs', 'mailing'} {'cosecomplient', 'devguide'}
topic_111
{'2035659372', '06108', 'uunetpwabanneser', '16105'} {'homebuilt', 'anneser', 'cb650', 'ooo'}
topic_112
{'wont', 'condemning', 'word', 'pharisees', 'fundamentalists'} {'gen', 'sandvik', 'kent', 'ks', 'malcolm'}
topic_113
{'king', 'guide', 'bang'} {'adams', 'douglas', 'alice'}
topic_114
topic_115
{'power'} {'grayhill'}
topic_116
{'version', 'xdm', 'has', 'monitor'} {'wcl', '22mar93', 'solaris', 'x11r5'}
topic_117
{'400', 'scans', 'hand', 'scanning', 'handheld', 'market'} {'ocr104zip', 'ocr', 'dexxa', 'paintbrush', 'mustek', 'scanman'}
topic_118
topic_119
{'objects', 'charged'} {'kirlian', 'krillean'}
topic_120
{'315', 'book', 'remembered', 'refute', 'disappointing', 'marks', 'definitive'} {'8aohonj024nsktbdemoncouk', '1r3jgbinn35ielicsyaleedu', 'velapoldi', 'cheryl', '1993apr150242468076virginiaedu', 'ejv2jvirginiaedu', 'strnlghtc5t3nhis1netcomcom'}
topic_121
{'paul'} {'darius'}
topic_122
{'lemmings'} {'soundbase'}
topic_123
{'mailing'} {'vip'}
topic_124
{'is'} {'bbbbb'}
topic_125
{'blit', 'im', 'drawable', 'borderwidth', 'y3'} {'xsetfunction', 'xdrawline', 'xflush', 'gxxor', 'drawindex'}
topic_126
{'regards', 'stripped'} {'babak', 'sehari'}
topic_127
topic_128
{'working'} {'stephanopoulos'}
topic_129
{'words', 'members', 'the', 'organization', 'love', 'of', 'superior', 'am', 'wilt', 'magic', 'invoke', 'oriental', 'law'} {'rosicrucian', 'ordo', 'crowley', 'oto', 'masonic', 'crucis', 'reuss', 'frater', 'templi', 'rosae', 'orientis', 'amorc', 'jose'}
topic_130
{'5221904', 'wbuku', 'jasonlimiastateedu', 'bengcaewiscedu'} {'asicic', 'tuscon', 'flywrite', 'eshnekenuiucedu'}
topic_131
{'japanese', 'subtract'} {'saturns', 'sc1'}
topic_132
{'the', 'of', 'authority', 'consecration', 'catholics'} {'lefebvre', 'pius', 'sspx', 'archbishop', 'popes'}
topic_133
{'uuencode', 'ioccc'} {'xvoid', 'eofnotok'}
topic_134
{'possible'} {'gudgeon'}
topic_135
{'repressive'} {'clancys'}
topic_136
{'removing', 'finish'} {'meguiars', 'mcquires'}
topic_137
{'existing', 'notebook', 'board', 'heat'} {'rocketshare', 'alphas', 'macrescue', 'powerpc'}
topic_138
{'may', 'and', 'as', 'clowns', 'was', 'who', 'by', 'christian', 'among'} {'boobtists', 'masonry', 'baptist', 'masonic', 'holly', 'lewis', 'baptists', 'masons', 'wbt'}
topic_139
topic_140
{'cars', 'april', '49er'} {'quincy', 'sept', 'cambridge'}
topic_141
{'150', '210', 'vs', 'rider', 'each'} {'wolverine', 'liefeld', 'sabretooth', 'hobgoblin', 'punisher'}
topic_142
{'315569259747', 'dives', 'eabu288orionoacuciedu', 'eabu288140493210752dialin33635slipntsuciedu'} {'bridgend', '86400', '8g', 'hundredths'}
topic_143
{'jobs', 'utter', 'volunteer', 'list', 'whether'} {'irs', 'registries', 'admistration', 'hultman', 'c17'}
topic_144
topic_145
{'dispersil', 'sharewares', 'illeagle'} {'radiusware', 'bitgraypixel', 'nonftp'}

In [133]:
fix_regularizer = FastFixPhiRegularizer(
    name='fix',
    parent_phi=phi,
    topic_names=phi.columns,
)

custom_regularizers = {
    fix_regularizer.name: fix_regularizer,
}

result = fit_and_compute_scores(model, dataset, custom_regularizers=custom_regularizers)

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f71851de850>}

In [134]:
result = new_result

In [136]:
result['scores']

{'perplexity': 9313.6455078125,
 'coherence_20': array([1.53849689]),
 'diversity_euclidean': 0.06944713960080998,
 'diversity_jensenshannon': 0.7210854989101421,
 'diversity_hellinger': 0.8565287662161661,
 'diversity_cosine': 0.8326357482944967}

In [140]:
results = {
    'test': result
}

In [143]:
r

{'scores': {'perplexity': 9313.6455078125,
  'coherence_20': array([1.53849689]),
  'diversity_euclidean': 0.06944713960080998,
  'diversity_jensenshannon': 0.7210854989101421,
  'diversity_hellinger': 0.8565287662161661,
  'diversity_cosine': 0.8326357482944967},
 'topic_coherences': {0: 1.2252953493262035,
  1: 0.622924615224085,
  2: 1.1583919440035115,
  3: 1.0855657296738097,
  4: 0.677690967785305,
  5: 0.5630280933439489,
  6: 1.2178763350206647,
  7: 1.31892096280969,
  8: 1.0080110613759343,
  9: 1.726066996458189,
  10: 1.411324251030534,
  11: 1.6803373416371612,
  12: 0.74318595857547,
  13: 2.249348135503753,
  14: 0.9931107411332841,
  15: 1.799890990293903,
  16: 1.0286068610126915,
  17: 1.6705548497219567,
  18: 0.3213578724353934,
  19: 1.235485065372899,
  20: 1.566994324245821,
  21: 1.9020915201357333,
  22: 0.9738945194022423,
  23: 1.1826511243101272,
  24: 2.2424500177628186,
  25: 1.439606731445224,
  26: 1.411553817644481,
  27: 1.0335294683808687,
  28: 0.6768516147792625,
  29: 0.6293042867399811,
  30: 1.2334484900861504,
  31: 1.6541367198723873,
  32: 2.0865480824962463,
  33: 0.9706850081508265,
  34: 1.391178149168946,
  35: 1.4926462306354118,
  36: 1.2159557625135224,
  37: 1.4989157285600916,
  38: 0.8990703972051446,
  39: 1.5767946284694934,
  40: 1.3397080099730387,
  41: 1.232437855435216,
  42: 0.4832951960737495,
  43: 0.7370468835187339,
  44: 1.485437112242095,
  45: 2.0062424477247394,
  46: 1.478588956949661,
  47: 1.7814883642358619,
  48: 1.465516629964561,
  49: 1.0926563244891332,
  50: 0.30840211278875396,
  51: 2.4646331741933287,
  52: 1.1120545874735444,
  53: 2.1550313278907027,
  54: 0.9846365908435807,
  55: 1.1032044406520354,
  56: 0.6785843516050585,
  57: 1.3710602374863214,
  58: 1.0052513494216533,
  59: 4.315723788131953,
  60: 1.342282437889004,
  61: 1.2687731365228376,
  62: 1.7747644904236608,
  63: 1.295084491875316,
  64: 1.938284600054732,
  65: 1.471722874005389,
  66: 1.360719234782693,
  67: 1.5848198906204276,
  68: 1.262907685627422,
  69: 2.5321931770228097,
  70: 1.8537382636012394,
  71: 1.330028754861526,
  72: 1.8701644680419969,
  73: 0.7125831980681638,
  74: 1.450720184847752,
  75: 2.1275705149144195,
  76: 1.5584770531500274,
  77: 1.3124836436714822,
  78: 1.4195019705455985,
  79: 2.8532670214258986,
  80: 2.260748725783511,
  81: 1.6433165063368853,
  82: 2.5065907274203747,
  83: 1.5392231008348816,
  84: 0.6660639491696817,
  85: 1.5549912317707804,
  86: 1.2014046141990375,
  87: 1.3817293345055919,
  88: 1.6568604584711424,
  89: 1.6792596150495827,
  90: 1.8246958362558545,
  91: 1.4503792437626317,
  92: 1.3659565406416654,
  93: 1.4859101042891385,
  94: 3.0848932458787943,
  95: 2.1593505655861223,
  96: 1.6615196604787104,
  97: 0.7143276010859965,
  98: 1.1188426942040586,
  99: 2.489211182547683,
  100: 2.56379481974003,
  101: 1.5606761328920704,
  102: 1.8119185925489716,
  103: 1.5883397244100954,
  104: 1.853617339583024,
  105: 1.388997851047087,
  106: 1.2784950341466301,
  107: 1.1096056640921683,
  108: 2.5345817372810955,
  109: 1.9662335232288817,
  110: 1.6084639759508252,
  111: 2.276499811397846,
  112: 0.9498622552445884,
  113: 1.4963805966762358,
  114: 2.3432873839786406,
  115: 2.066049543766591,
  116: 1.5397311814807213,
  117: 2.1068305155853833,
  118: 3.756750066020347,
  119: 4.059632365073044,
  120: 0.6960845660238134,
  121: 1.6778085928270723,
  122: 0.9625904041893516,
  123: 1.2543700738238532,
  124: 1.348358433791909,
  125: 1.3639232344917271,
  126: 1.3479570657893019,
  127: 2.1831734150132345,
  128: 0.6272288471640947,
  129: 1.027039137179092,
  130: 0.985745453997735,
  131: 1.5396077567971955,
  132: 3.01909043553682,
  133: 3.96555904207465,
  134: 1.58081914264555,
  135: 2.0640078367495844,
  136: 1.8901758248591265,
  137: 1.0793356710967021,
  138: 0.8791035530533649,
  139: 1.1427550411873943,
  140: 0.6673636773544815,
  141: 2.1566426799241145,
  142: 1.2120684364172407,
  143: 1.8152657751025585,
  144: 2.0499215490033,
  145: 1.043159361464251}}

In [144]:
for k, r in results.items():
    r['scores']['coherence_20'] = float(r['scores']['coherence_20'])

for k, r in results.items():
    with open(f'test_bt_results_{k}.json', 'w') as f:
        f.write(
            json.dumps(r, indent=4)
        )