In [1]:
import os
import json
import shutil
import sys

import numpy as np
import scipy

In [2]:
sys.path.insert(0, '../OptimalNumberOfTopics')

In [3]:
import topnum

from topnum.scores.perplexity_score import PerplexityScore
from topnum.scores.diversity_score import DiversityScore, KNOWN_METRICS
from topnum.model_constructor import init_model_from_family, KnownModel, PARAMS_EXPLORED, init_plsa

In [4]:
import artm
from artm import ARTM, Dictionary

import topicnet
from topicnet.cooking_machine.dataset import Dataset
from topicnet.cooking_machine.models import (
    BaseScore as BaseTopicNetScore,
    TopicModel
)
from topicnet.cooking_machine.models.base_regularizer import BaseRegularizer
from topicnet.cooking_machine.models.thetaless_regularizer import (
    dataset2sparse_matrix,
)

from topicnet.cooking_machine.models.topic_model import ARTM_NINE
from topicnet.cooking_machine.models.base_regularizer import BaseRegularizer
from topicnet.viewers.top_documents_viewer import TopDocumentsViewer
from topicnet.viewers.top_tokens_viewer import TopTokensViewer
from topicnet.cooking_machine.model_constructor import (
    add_standard_scores,
    create_default_topics,
    count_vocab_size,
    init_model,
)
from topicnet.cooking_machine.rel_toolbox_lite import (
    count_vocab_size,
    modality_weight_rel2abs,
    transform_regularizer,
)


import numpy as np
import pandas as pd
from pandas import DataFrame
from scipy.spatial.distance import cdist

import os
import tempfile
import warnings
from copy import deepcopy
from typing import Dict, List, Optional

In [20]:
NUM_TOPICS = 50

NUM_ITERATIONS = 5
NUM_TOP_TOKENS = 20
NUM_TRAINS = 20

In [5]:
BERTOPIC_FOLDER_PATH = '/data_mil/shared/CompressaAI/BERTopic'
RESULTS_FOLDER_PATH = os.path.join(BERTOPIC_FOLDER_PATH, 'results50', '20newsgroups')

In [7]:
RESULTS_FOLDER_PATH

'/data_mil/shared/CompressaAI/BERTopic/results50/20newsgroups'

In [8]:
! ls $RESULTS_FOLDER_PATH

0  1  10  11  12  13  14  15  16  17  18  19  2  3  4  5  6  7	8  9

In [9]:
! ls $RESULTS_FOLDER_PATH/0

dataset.csv  phi.csv  top_words.json

In [10]:
dataset = Dataset(
    f'{RESULTS_FOLDER_PATH}/0/dataset.csv',
)

dataset.get_possible_modalities()

{'@lemmatized'}

In [11]:
MAIN_MODALITY = '@lemmatized'

In [12]:
def calc_doc_occurrences(dataset, modality):
    """
    :param n_dw_matrix: sparse document-word matrix, shape is D x W
    :return: sparse matrix of co-occurrences

    doc_occurrences[w1, w2] = the number of the documents
    where there are w1 and w2
    """
    n_dw_matrix = dataset2sparse_matrix(dataset, modality, modalities_to_use=[modality])
    matrix = (scipy.sparse.csc_matrix(n_dw_matrix) > 0).astype(int)
    co_occurrences = matrix.T * matrix

    return co_occurrences.diagonal(), co_occurrences


def create_pmi_top_function(
    doc_occurrences, doc_co_occurrences,
    documents_number, top_sizes,
    topic_indices,
    co_occurrences_smooth=1.
):
    """
    :param doc_occurrences: array of doc occurrences of words
    :param doc_co_occurrences: sparse matrix of doc co-occurrences of words
    :param documents_number: number of the documents
    :param top_sizes: list of top values to calculate top-pmi for
    :param co_occurrences_smooth: constant to smooth co-occurrences in log
    :return: function which takes phi and theta and returns
    pair of two arrays: pmi-s of the tops and ppmi-s of the tops

    pmi[i] - pmi(top of size top_sizes[i])
    ppmi[i] - ppmi(top of size top_sizes[i])

    pmi(words) = sum_{u in words, v in words, u != v}
    log(
        (doc_co_occurrences[u, v] * documents_number + co_occurrences_smooth)
        / doc_occurrences[u] / doc_occurrences[v]
    )

    ppmi(words) = sum_{u in words, v in words, u != v}
    max(log(
        (doc_co_occurrences[u, v] * documents_number + co_occurrences_smooth)
        / doc_occurrences[u] / doc_occurrences[v]
    ), 0)

    """
    def func(phi):
        _T, W = phi.shape
        T = len(topic_indices)

        max_top_size = max(top_sizes)
        topic_pmis, topic_ppmis = dict(), dict()
        pmi, ppmi = np.zeros(max_top_size), np.zeros(max_top_size)
        tops = np.argpartition(phi, -max_top_size, axis=1)[:, -max_top_size:]
        
        for t in topic_indices:
            top = sorted(tops[t], key=lambda w: - phi[t, w])
            co_occurrences = doc_co_occurrences[top, :][:, top].todense()
            occurrences = doc_occurrences[top]
            values = np.log(
                (co_occurrences * documents_number + co_occurrences_smooth)
                / (occurrences[:, np.newaxis] * occurrences[np.newaxis, :] + co_occurrences_smooth)
            )
            diag = np.diag_indices(len(values))
            # values.cumsum(axis=0).cumsum(axis=1)[diag] - values[diag].cumsum()

            current_pmi = np.array(
               values.cumsum(axis=0).cumsum(axis=1)[diag] - values[diag].cumsum()
            ).ravel()
            topic_pmis[t] = current_pmi
            pmi += current_pmi

            values[values < 0.] = 0.
            current_ppmi = np.array(
               values.cumsum(axis=0).cumsum(axis=1)[diag] - values[diag].cumsum()
            ).ravel()
            topic_ppmis[t] = current_ppmi
            ppmi += current_ppmi
            
        sizes = np.arange(2, max_top_size + 1)
        pmi[1:] /= (T * sizes * (sizes - 1))
        ppmi[1:] /= (T * sizes * (sizes - 1))
        indices = np.array(top_sizes) - 1

        for t in topic_indices:
            topic_pmis[t][1:] /= (sizes * (sizes - 1))
            topic_ppmis[t][1:] /= (sizes * (sizes - 1))

        result_topic_pmis = {t: p[indices] for t, p in topic_pmis.items()}
        result_topic_ppmis = {t: p[indices] for t, p in topic_ppmis.items()}

        return pmi[indices], ppmi[indices], result_topic_pmis, result_topic_ppmis

    return func

In [13]:
%%time

occurences, co_occurences = calc_doc_occurrences(dataset, MAIN_MODALITY)

CPU times: user 6.86 s, sys: 344 ms, total: 7.2 s
Wall time: 7.12 s

In [14]:
co_occurences.shape

(114951, 114951)

In [15]:
calc_pmi = create_pmi_top_function(
    occurences, co_occurences,
    dataset.get_dataset().shape[0], [20],
    topic_indices=[0, 1, 2],
    co_occurrences_smooth=1e-2,
)

In [21]:
class TopTokenCoherence(BaseTopicNetScore):
    def __init__(self, name, func):
        super().__init__()

        self._name = name
        self.calc_pmi = func

    def call(self, model: TopicModel):
        values = self.calc_pmi(model.get_phi_dense()[0].T)

        return values[1]

    def call_by_topic(self, model: TopicModel):
        values = self.calc_pmi(model.get_phi_dense()[0].T)

        return values[3]

In [22]:
def view_model(
        topic_model,
        dataset,
        num_top_tokens: int = 5,
        top_tokens_method: str = 'phi',
        num_topics: Optional[int] = 5,  # we do not want to fill the whole .ipynb notebook with topics...
        ):
    top_tok_viewer = TopTokensViewer(
        topic_model, num_top_tokens=num_top_tokens, method=top_tokens_method
    )
    top_doc_viewer = TopDocumentsViewer(topic_model, dataset=dataset)
    top_docs = top_doc_viewer.view()

    if num_topics is None:
        num_topics = len(topic_model.topic_names)

    for topic_name in topic_model.topic_names[:num_topics]:
        topic_top_toks = top_tok_viewer.to_html(topic_names=[topic_name])
        topic_top_docs = top_docs[topic_name]
        display_html(topic_top_toks, raw=True)
        display(topic_top_docs)

In [23]:
class FastFixPhiRegularizer(BaseRegularizer):
    _VERY_BIG_TAU = 10 ** 9

    def __init__(self, name: str, topic_names: List[str], parent_model=None, parent_phi=None, words=None):
        super().__init__(name, tau=self._VERY_BIG_TAU)

        self._topic_names = topic_names
        self._topic_indices = None
        self._words = words
        self._word_indices = None
        self._parent_model = parent_model
        self._parent_phi = parent_phi

    def grad(self, pwt, nwt):
        # print('Fixing')

        rwt = np.zeros_like(pwt)

        if self._parent_phi is not None:
            parent_phi = self._parent_phi
            vals = parent_phi.values
        else:
            assert False

            parent_phi = self._parent_model.get_phi()
            vals = parent_phi.values[:, self._topic_indices]

        if self._word_indices is None:
            assert vals.shape[0] == rwt.shape[0], (vals.shape[0], rwt.shape[0])
        else:
            assert vals.shape[0] == len(self._word_indices)

        assert vals.shape[1] == len(self._topic_indices)

        if self._word_indices is None:
            rwt[:, self._topic_indices] += vals
        else:
            # print(len(self._word_indices), len(self._topic_indices), rwt.shape, vals.shape)
            # print(self._word_indices[:3], self._topic_indices[:3])
            # print(rwt[np.ix_(self._word_indices, self._topic_indices)].shape, vals.shape)

            # https://github.com/numpy/numpy/issues/5574
            # https://github.com/numpy/numpy/issues/13255
            rwt[np.ix_(self._word_indices, self._topic_indices)] += vals

            # print(np.ix_(self._word_indices, self._topic_indices)[:3])

        return self.tau * rwt

    def attach(self, model):
        super().attach(model)
        
        phi = self._model.get_phi()
        self._topic_indices = [
            phi.columns.get_loc(topic_name)
            for topic_name in self._topic_names
        ]

        if self._words is not None:
            self._word_indices = [
                # phi.index.get_loc(w) for w in self._words
                int(phi.index.get_loc(w)) for w in self._words
            ]

            # print(f'!!! Word indices: {self._word_indices}')

In [24]:
def fit_and_compute_scores(model, dataset, target_topic_indices=None, custom_regularizers=None):
    print(custom_regularizers)

    model._fit(dataset.get_batch_vectorizer(), num_iterations=NUM_ITERATIONS, custom_regularizers=custom_regularizers)

    score_values = {
        'perplexity': model.scores[f'PerplexityScore{MAIN_MODALITY}'][-1],
    }

    phi = model.get_phi()

    # Currently all topics are taken into account

    if target_topic_indices is None:
        target_topic_indices = list(range(NUM_TOPICS))  # phi.columns.get_loc()

    target_topic_names = [phi.columns[i] for i in target_topic_indices]

    top = NUM_TOP_TOKENS
    coherence_score = TopTokenCoherence(
        name=f'coherence_{top}',
        func=create_pmi_top_function(
            occurences, co_occurences,
            dataset.get_dataset().shape[0], [top],
            topic_indices=target_topic_indices,
            co_occurrences_smooth=1e-2,
        )
    )

    value = coherence_score.call(model)
    score_values[coherence_score._name] = value
    topic_coherences = coherence_score.call_by_topic(model)
    topic_coherences = {t: float(v) for t, v in topic_coherences.items()}

    diversity_scores = [
        DiversityScore(
            name=f'diversity_{metric}',
            metric=metric,
            topic_names=target_topic_names,
            class_ids=MAIN_MODALITY,
        )
    
        for metric in KNOWN_METRICS
    ]
    
    for score in diversity_scores:
        value = score.call(model)
        score_values[score._name] = value

    return {
        'scores': score_values,
        'topic_coherences': topic_coherences,
    }

In [25]:
def init_model_from_family(
        family: str or KnownModel,
        dataset: Dataset,
        main_modality: str,
        num_topics: int,
        seed: int,
        specific_topic_names = None,
        modalities_to_use: List[str] = None,
        num_processors: int = 3,
        model_params: dict = None,
):
    """
    Returns
    -------
    model: TopicModel() instance
    """
    if isinstance(family, KnownModel):
        family = family.value

    if modalities_to_use is None:
        modalities_to_use = [main_modality]

    custom_regs = {}

    if family == "LDA":
        model = init_lda(
            dataset, modalities_to_use, main_modality, num_topics, model_params
        )
    elif family == "PLSA":
        model = init_plsa(
            dataset, modalities_to_use, main_modality, num_topics
        )
    elif family == "TARTM":
        model, custom_regs = init_thetaless(
            dataset, modalities_to_use, main_modality, num_topics, model_params
        )
    elif family == "sparse":
        model = init_bcg_sparse_model(
            dataset, modalities_to_use, main_modality, num_topics, 1, model_params
        )
    elif family == "decorrelation":
        model = init_decorrelated_plsa(
            dataset, modalities_to_use, main_modality, num_topics, model_params
        )
    elif family == "ARTM":
        model = init_baseline_artm(
            dataset, modalities_to_use, main_modality, num_topics, 1, specific_topic_names, model_params
        )
    else:
        raise ValueError(f'family: {family}')

    model.num_processors = num_processors

    if seed is not None:
        model.seed = seed

    dictionary = dataset.get_dictionary()

    # TODO: maybe this cycle is not necessary
    for modality in dataset.get_possible_modalities():
        if modality not in modalities_to_use:
            dictionary.filter(class_id=modality, max_df=0, inplace=True)

    model.initialize(dictionary)
    add_standard_scores(model, dictionary, main_modality=main_modality,
                        all_modalities=modalities_to_use)

    model = TopicModel(
        artm_model=model,
        custom_regularizers=custom_regs
    )

    return model


def init_bcg_sparse_model(
        dataset,
        modalities_to_use,
        main_modality,
        specific_topics,
        bcg_topics,
        specific_topic_names = None,
        model_params: dict = None
):
    """
    Creates simple artm model with standard scores.

    Parameters
    ----------
    dataset : Dataset
    modalities_to_use : list of str or dict
    main_modality : str
    specific_topics : int
    bcg_topics : int

    Returns
    -------
    model: artm.ARTM() instance
    """
    if model_params is None:
        model_params = dict()

    model = init_plsa(
        dataset, modalities_to_use, main_modality, specific_topics, bcg_topics
    )
    background_topic_names = model.topic_names[-bcg_topics:]

    if specific_topic_names is None:
        print('No spec topics')
        specific_topic_names = model.topic_names[:-bcg_topics]

    dictionary = dataset.get_dictionary()
    baseline_class_ids = {class_id: 1 for class_id in modalities_to_use}
    data_stats = count_vocab_size(dictionary, baseline_class_ids)

    # all coefficients are relative
    regularizers = [
        artm.SmoothSparsePhiRegularizer(
             name='smooth_phi_bcg',
             topic_names=background_topic_names,
             tau=model_params.get("smooth_bcg_tau", 0.1),
             class_ids=[main_modality],
        ),
        artm.SmoothSparseThetaRegularizer(
             name='smooth_theta_bcg',
             topic_names=background_topic_names,
             tau=model_params.get("smooth_bcg_tau", 0.1),
        ),
        artm.SmoothSparsePhiRegularizer(
             name='sparse_phi_sp',
             topic_names=specific_topic_names,
             tau=model_params.get("sparse_sp_tau", -0.05),
             class_ids=[main_modality],
            ),
        artm.SmoothSparseThetaRegularizer(
             name='sparse_theta_sp',
             topic_names=specific_topic_names,
             tau=model_params.get("sparse_sp_tau", -0.05),
        ),
    ]
    for reg in regularizers:
        model.regularizers.add(transform_regularizer(
            data_stats,
            reg,
            model.class_ids,
            n_topics=len(reg.topic_names)
        ))

    return model


def init_baseline_artm(
        dataset,
        modalities_to_use,
        main_modality,
        num_topics,
        bcg_topics,
        specific_topic_names = None,
        model_params: dict = None,
):
    """
    Creates simple artm model with standard scores.

    Parameters
    ----------
    dataset : Dataset
    modalities_to_use : list of str
    main_modality : str
    num_topics : int

    Returns
    -------
    model: artm.ARTM() instance
    """
    if model_params is None:
        model_params = dict()

    model = init_bcg_sparse_model(
        dataset, modalities_to_use, main_modality, num_topics, bcg_topics, specific_topic_names, model_params
    )

    if specific_topic_names is None:
        print('No spec topics')
        specific_topic_names = model.topic_names[:-bcg_topics]

    model.regularizers.add(
        artm.DecorrelatorPhiRegularizer(
            gamma=0,
            tau=model_params.get('decorrelation_tau', 0.01),
            name='decorrelation',
            topic_names=specific_topic_names,
            class_ids=modalities_to_use,
        )
    )

    return model

In [26]:
TOPIC_INDICES = list(range(NUM_TOPICS))

In [27]:
TOPIC_INDICES

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [28]:
phi0 = pd.read_csv(f'{RESULTS_FOLDER_PATH}/0/phi.csv', index_col=0)

In [29]:
phi0.head()

,background_1,topic_0,topic_1,topic_2,topic_3,topic_4,topic_5,topic_6,topic_7,topic_8,...,topic_40,topic_41,topic_42,topic_43,topic_44,topic_45,topic_46,topic_47,topic_48,topic_49
00,0.000000,0.001140,0.000138,0.0,0.004540,0.0,0.00000,0.001633,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
000,0.000125,0.000070,0.000031,0.0,0.003937,0.0,0.00013,0.000311,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
0000,0.000140,0.000026,0.000000,0.0,0.002774,0.0,0.00000,0.000000,0.0,0.000105,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
00000,0.000000,0.000043,0.000000,0.0,0.000000,0.0,0.00000,0.000000,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.00000,0.000605,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [30]:
phi0.set_index([[MAIN_MODALITY] * len(phi0.index), phi0.index], inplace=True)

In [31]:
phi0.head()

                    background_1   topic_0   topic_1  topic_2   topic_3  \
@lemmatized 00          0.000000  0.001140  0.000138      0.0  0.004540
            000         0.000125  0.000070  0.000031      0.0  0.003937
            0000        0.000140  0.000026  0.000000      0.0  0.002774
            00000       0.000000  0.000043  0.000000      0.0  0.000000
            000000      0.000000  0.000000  0.000000      0.0  0.000000

                    topic_4  topic_5   topic_6  topic_7   topic_8  ...  \
@lemmatized 00          0.0  0.00000  0.001633      0.0  0.000000  ...
            000         0.0  0.00013  0.000311      0.0  0.000000  ...
            0000        0.0  0.00000  0.000000      0.0  0.000105  ...
            00000       0.0  0.00000  0.000000      0.0  0.000000  ...
            000000      0.0  0.00000  0.000605      0.0  0.000000  ...

                    topic_40  topic_41  topic_42  topic_43  topic_44  \
@lemmatized 00           0.0       0.0       0.0       0.0       0.0
            000          0.0       0.0       0.0       0.0       0.0
            0000         0.0       0.0       0.0       0.0       0.0
            00000        0.0       0.0       0.0       0.0       0.0
            000000       0.0       0.0       0.0       0.0       0.0

                    topic_45  topic_46  topic_47  topic_48  topic_49
@lemmatized 00           0.0       0.0       0.0       0.0       0.0
            000          0.0       0.0       0.0       0.0       0.0
            0000         0.0       0.0       0.0       0.0       0.0
            00000        0.0       0.0       0.0       0.0       0.0
            000000       0.0       0.0       0.0       0.0       0.0

[5 rows x 51 columns]

In [32]:
DIFF_THRESHOLD = 2

In [42]:
def check_top_words(phi, top_words):
    diffs = []

    for t, topic_top_words in top_words.items():
        if t == 'background_1':
            print(f'Skipping background topic: {t}.')

            continue

        print(t)
        # print(top_words)
    
        top_phi = set(phi[t].sort_values(ascending=False)[:NUM_TOP_TOKENS].index.get_level_values(1))
        top_bt = set([p[0] for p in topic_top_words])
    
        if top_phi == top_bt:
            diffs.append(
                {
                    'total': 0,
                    'lost_bt': 0,
                    'lost_model': 0,
                }
            )
        else:
            diff1 = top_phi.difference(top_bt)
            diff2 = top_bt.difference(top_phi)
    
            print('  WTF:', diff1, diff2)
    
            if len(diff1) > DIFF_THRESHOLD:
                print(f'  WTF?!?!?', len(diff1))
    
            if len(diff2) > DIFF_THRESHOLD:
                print(f'  WTF?!?!?', len(diff2))

            diffs.append(
                {
                    'total': len(diff1 | diff2),
                    'lost_bt': len(diff2),
                    'lost_model': len(diff1),
                }
            )

    return diffs

In [34]:
def init_model_and_phi(num_topics, dataset, phi0):
    model = init_model_from_family(
        family=KnownModel.PLSA,
        dataset=dataset,
        main_modality=MAIN_MODALITY,
        num_topics=num_topics,
        seed=0,
    )
    
    phi = model.get_phi()
    
    # assert phi.shape[1] == phi0.shape[1] - 1
    assert phi.shape[1] == num_topics
    assert phi.shape[1] in [phi0.shape[1], phi0.shape[1] - 1]
    
    common_words = list(set(phi.index).intersection(phi0.index))
    
    phi.loc[:, :] = 0

    if phi.shape[1] == phi0.shape[1]:
        target_topics = phi0.columns
    elif phi.shape[1] == phi0.shape[1] - 1:
        target_topics = phi.columns
    else:
        assert False

    # print(common_words, phi.index, phi0.index)

    phi.loc[common_words, :] += phi0.loc[common_words, target_topics]

    diff = set(phi0.columns).symmetric_difference(set(phi.columns))

    assert diff == {'background_1'} or diff == {'background_1', f'topic_{len(phi.columns) - 1}'}
    
    phi = phi / phi.sum(axis=0)

    return model, phi, common_words

In [37]:
! ls results50

20newsgroups  mkb10  postnauka	rtlwikiperson  ruwikigood

In [38]:
SAVE_FOLDER = os.path.join('results50', '20newsgroups')

In [39]:
! ls $SAVE_FOLDER

ablation_study	    iterative_100000.json      lda.json     tless.json
decorrelation.json  iterative2_100000000       plsa.json
iterative_100000    iterative2_100000000.json  sparse.json

In [43]:
results = []

is_results_loaded = False

save_file_path = os.path.join(
    SAVE_FOLDER, 'bertopic.json'
)

if os.path.isfile(save_file_path):
    results = json.loads(
        open(save_file_path).read()
    )
    is_results_loaded = True


singles_save_folder = os.path.join(
    SAVE_FOLDER, 'bertopic'
)

os.makedirs(singles_save_folder, exist_ok=True)


for seed in range(NUM_TRAINS):
    if is_results_loaded:
        continue

    print(seed)

    current_save_file_path = os.path.join(
        singles_save_folder, f'bertopic_{seed}.json'
    )

    if os.path.isfile(current_save_file_path):
        print(f'Already computed results: {current_save_file_path}. Loading and skipping...')

        result = json.loads(
            open(current_save_file_path).read()
        )
        results.append(result)

        continue

    seed_load_folder = os.path.join(RESULTS_FOLDER_PATH, str(seed))
    files = [f for f in os.listdir(seed_load_folder) if os.path.isfile(f'{seed_load_folder}/{f}')]
    
    assert len(files) == 3

    dataset = Dataset(
        f'{seed_load_folder}/dataset.csv',
    )
    phi0 = pd.read_csv(f'{seed_load_folder}/phi.csv', index_col=0)
    phi0.set_index([[MAIN_MODALITY] * len(phi0.index), phi0.index], inplace=True)

    assert all('back' not in t for t in phi0.columns[1:])
    assert 'back' in phi0.columns[0]

    num_specific_topics = phi0.shape[1] - 1

    assert num_specific_topics == len([t for t in phi0.columns if 'back' not in t])

    print(f'Num model topics: {phi0.shape[1]}.')

    with open(f'{seed_load_folder}/top_words.json', 'r') as f:
        top_words = json.loads(f.read())


    
    model, phi, common_phi_words = init_model_and_phi(
        num_topics=num_specific_topics + 1,  # background
        dataset=dataset, phi0=phi0
    )
    common_words = [
        w[1] for w in common_phi_words  # without modality
    ]
    common_words_phi0_indices = [
        # phi0.index.get_loc(w) for w in common_words
        int(phi0.index.get_locs(w)) for w in common_phi_words
    ]

    print('Check before fit:')
    diff_tops1 = check_top_words(phi, top_words)  # Whatever...
    
    fix_regularizer = FastFixPhiRegularizer(
        name='fix',
        parent_phi=phi0.iloc[common_words_phi0_indices, 1:],
        words=common_words,
        topic_names=phi.columns[1:],
    )
    result = fit_and_compute_scores(
        model, dataset,
        target_topic_indices=list(range(phi.shape[1])),
        custom_regularizers = {
            fix_regularizer.name: fix_regularizer,
        }
    )

    print('Check after fit:')
    diff_tops2 = check_top_words(phi, top_words)  # Whatever...

    assert diff_tops1 == diff_tops2

    fair_ppl_free = result['scores']['perplexity']

    del model, phi, fix_regularizer, result


    
    model, phi, _ = init_model_and_phi(
        num_topics=num_specific_topics + 1,  # background
        dataset=dataset, phi0=phi0
    )
    fix_regularizer = FastFixPhiRegularizer(
        name='fix',
        parent_phi=phi0.iloc[common_words_phi0_indices, :],  # Diff here
        words=common_words,
        topic_names=phi.columns,
    )
    result = fit_and_compute_scores(
        model, dataset,
        target_topic_indices=list(range(phi.shape[1])),
        custom_regularizers = {
            fix_regularizer.name: fix_regularizer,
        }
    )
    
    fair_ppl_fix = result['scores']['perplexity']

    del model, phi, fix_regularizer, result

    
    
    model, phi, _ = init_model_and_phi(
        num_topics=num_specific_topics,  # Diff here
        dataset=dataset, phi0=phi0
    )
    fix_regularizer = FastFixPhiRegularizer(
        name='fix',
        parent_phi=phi0.iloc[common_words_phi0_indices, 1:],  # Diff here
        words=common_words,
        topic_names=phi.columns,
    )
    result = fit_and_compute_scores(
        model, dataset,
        custom_regularizers = {
            fix_regularizer.name: fix_regularizer,
        }
    )

    unfair_ppl_banklike = result['scores']['perplexity']


    
    result['scores']['fair_ppl_free'] = fair_ppl_free
    result['scores']['fair_ppl_fix'] = fair_ppl_fix
    result['scores']['unfair_ppl_banklike'] = unfair_ppl_banklike

    assert result['scores']['fair_ppl_free'] < result['scores']['unfair_ppl_banklike']
    # assert result['scores']['fair_ppl_fix'] < result['scores']['unfair_ppl_banklike']

    result['scores']['coherence_20'] = float(result['scores']['coherence_20'])
    result['stats'] = {
        'num_topics': phi0.shape[1],
        'num_common_words': len(common_words),
        'num_model_words': phi.shape[0],
        'num_bt_words': phi0.shape[0],
        'top_diffs': diff_tops2,
    }

    results.append(result)

    print(result['scores'])
    print(result['stats'])

    dumped_result = json.dumps(
        results[-1], indent=4
    )

    with open(current_save_file_path, 'w') as f:
        f.write(dumped_result)

    del model, phi, fix_regularizer


with open(save_file_path, 'w') as f:
    f.write(
        json.dumps(
            results, indent=4
        )
    )

0
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
  WTF: {'firearms'} {'stephanopoulos'}
topic_3
  WTF: {'vs'} {'nhl'}
topic_4
topic_5
  WTF: {'candida', 'surrender', 'dont'} {'hiv', 'n3jxp', 'gordon'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_6
topic_7
  WTF: {'news', 'thanks'} {'o157h7', 'anania'}
topic_8
  WTF: {'ottoman', 'children', 'muslim', 'government', 'saw', 'started'} {'armenia', 'azerbaijan', 'armenians', 'sumgait', 'armenian', 'turks'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_9
  WTF: {'driver'} {'bj200'}
topic_10
  WTF: {'just', 'sin'} {'caligiuri', 'enviroleague'}
topic_11
  WTF: {'CDROMCATZIP', 'ringleaders', 'CSCSTD00385', 'dragdrop', 'NikeCajun', '8800CS', '5152940082', 'taxation', 'Epilepsy', 'knowlege', '1795', '207556000', 'toolbox', 'effortsall', 'L2PMABGZ7VAZV0PZRI'} {''}
  WTF?!?!? 15
topic_12
topic_13
topic_14
  WTF: {'posting', 'email'} {'rsa', 'ripem'}
topic_15
topic_16
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_17
topic_18
topic_19
topic_20
  WTF: {'analytic', '02106chopinudeledu', 'vol', 'email', 'copyright', 'writing'} {'vernor', 'dune', 'baen', 'gibson', 'vinge', 'petrucci'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_21
  WTF: {'use', '250'} {'irwin', 'mactools'}
topic_22
  WTF: {'handheld', 'scans', 'grayscales', 'market', 'buy', '400'} {'ocr', 'dexxa', 'mustek', 'scanman', 'paintbrush', 'ocr104zip'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_23
  WTF: {'king', 'forget', 'sort', 'bang', 'guide', 'rule'} {'adams', 'maxima', 'alice', 'altima', 'douglas', 'infiniti'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_24
topic_25
  WTF: {'pm', 'students', 'cs', 'andrew'} {'mellon', 'japan', 'carnegie', 'jstmp'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_26
  WTF: {'objects', 'charged'} {'kirlian', 'krillean'}
topic_27
topic_28
  WTF: {'fissionable'} {'civillians'}
topic_29
  WTF: {'people', 'english'} {'ishtar', 'bede'}
topic_30
  WTF: {'aside'} {'darius'}
topic_31
  WTF: {'49er', 'nick', 'car'} {'quincy', 'cambridge', 'sept'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_32
  WTF: {'regards', 'stripped'} {'sehari', 'babak'}
topic_33
  WTF: {'envelopes'} {'mary'}
topic_34
  WTF: {'eabu288orionoacuciedu', 'nebulised', 'eabu288140493210752dialin33635slipntsuciedu'} {'asthmatics', 'bridgend', 'petesmtldemoncouk'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_35
  WTF: {'corps', 'axe', 'commission'} {'registries', 'admistration', 'irs'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_36
  WTF: {'governmentmandated', 'safety', 'world', 'energyefficiency', 'perfect'} {'ames', 'shafer', 'cato', 'dryden', 'mary'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_37
  WTF: {'uuencode', 'ioccc'} {'eofnotok', 'xvoid'}
topic_38
  WTF: {'patchmaking', 'unpatentable', 'remixed', 'vending'} {'cocacola', 'cola', 'yerazunis', 'pepsi'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_39
  WTF: {'vent', 'wooden', 'punch'} {'pistrix', 'sanjay', 'lesabre'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_40
  WTF: {'amish', 'financial'} {'mym', 'q6'}
topic_41
topic_42
  WTF: {'pads', 'addition', 'combo', 'version', 'stabilized'} {'t4', 'energiam', 't4centaur', 'russia', 'salyut'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_43
  WTF: {'publications', 'product', 'licensed', 'internet', 'science', 'promote', 'include'} {'marquette', 'regal', 'milwaukee', 'wi', 'robb', 'doublemajor', 'dubinski'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_44
  WTF: {'audio', 'returned', 'problem'} {'emerson', 'hifi', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_45
  WTF: {'promote'} {'fenholt'}
topic_46
  WTF: {'mole', 'gigabytes', 'leave'} {'eachus', 'avagadros', 'menuts'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_47
  WTF: {'trinomials', '0n', 'tp', '644', 'mm', 'pw', 'mj', 'ma', 'm1', 'u0', 'mf', 'mh'} {'p6', 'm3', 'm9', 'lu', 'm0', 'm5', 'o3', 'm6', 'pnospsxop8f', 'mw', 'e8', 'mx'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_48
  WTF: {'3rd'} {'ses'}
topic_49
  WTF: {'advertised', 'toilet', 'illusion'} {'kepley', 'workdays', 'mcguire'}
  WTF?!?!? 3
  WTF?!?!? 3
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f4fd48ab820>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
  WTF: {'firearms'} {'stephanopoulos'}
topic_3
  WTF: {'vs'} {'nhl'}
topic_4
topic_5
  WTF: {'candida', 'surrender', 'dont'} {'hiv', 'n3jxp', 'gordon'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_6
topic_7
  WTF: {'news', 'thanks'} {'o157h7', 'anania'}
topic_8
  WTF: {'ottoman', 'children', 'muslim', 'government', 'saw', 'started'} {'armenia', 'azerbaijan', 'armenians', 'sumgait', 'armenian', 'turks'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_9
  WTF: {'driver'} {'bj200'}
topic_10
  WTF: {'just', 'sin'} {'caligiuri', 'enviroleague'}
topic_11
  WTF: {'CDROMCATZIP', 'ringleaders', 'CSCSTD00385', 'dragdrop', 'NikeCajun', '8800CS', '5152940082', 'taxation', 'Epilepsy', 'knowlege', '1795', '207556000', 'toolbox', 'effortsall', 'L2PMABGZ7VAZV0PZRI'} {''}
  WTF?!?!? 15
topic_12
topic_13
topic_14
  WTF: {'posting', 'email'} {'rsa', 'ripem'}
topic_15
topic_16
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_17
topic_18
topic_19
topic_20
  WTF: {'analytic', '02106chopinudeledu', 'vol', 'email', 'copyright', 'writing'} {'vernor', 'dune', 'baen', 'gibson', 'vinge', 'petrucci'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_21
  WTF: {'use', '250'} {'irwin', 'mactools'}
topic_22
  WTF: {'handheld', 'scans', 'grayscales', 'market', 'buy', '400'} {'ocr', 'dexxa', 'mustek', 'scanman', 'paintbrush', 'ocr104zip'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_23
  WTF: {'king', 'forget', 'sort', 'bang', 'guide', 'rule'} {'adams', 'maxima', 'alice', 'altima', 'douglas', 'infiniti'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_24
topic_25
  WTF: {'pm', 'students', 'cs', 'andrew'} {'mellon', 'japan', 'carnegie', 'jstmp'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_26
  WTF: {'objects', 'charged'} {'kirlian', 'krillean'}
topic_27
topic_28
  WTF: {'fissionable'} {'civillians'}
topic_29
  WTF: {'people', 'english'} {'ishtar', 'bede'}
topic_30
  WTF: {'aside'} {'darius'}
topic_31
  WTF: {'49er', 'nick', 'car'} {'quincy', 'cambridge', 'sept'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_32
  WTF: {'regards', 'stripped'} {'sehari', 'babak'}
topic_33
  WTF: {'envelopes'} {'mary'}
topic_34
  WTF: {'eabu288orionoacuciedu', 'nebulised', 'eabu288140493210752dialin33635slipntsuciedu'} {'asthmatics', 'bridgend', 'petesmtldemoncouk'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_35
  WTF: {'corps', 'axe', 'commission'} {'registries', 'admistration', 'irs'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_36
  WTF: {'governmentmandated', 'safety', 'world', 'energyefficiency', 'perfect'} {'ames', 'shafer', 'cato', 'dryden', 'mary'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_37
  WTF: {'uuencode', 'ioccc'} {'eofnotok', 'xvoid'}
topic_38
  WTF: {'patchmaking', 'unpatentable', 'remixed', 'vending'} {'cocacola', 'cola', 'yerazunis', 'pepsi'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_39
  WTF: {'vent', 'wooden', 'punch'} {'pistrix', 'sanjay', 'lesabre'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_40
  WTF: {'amish', 'financial'} {'mym', 'q6'}
topic_41
topic_42
  WTF: {'pads', 'addition', 'combo', 'version', 'stabilized'} {'t4', 'energiam', 't4centaur', 'russia', 'salyut'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_43
  WTF: {'publications', 'product', 'licensed', 'internet', 'science', 'promote', 'include'} {'marquette', 'regal', 'milwaukee', 'wi', 'robb', 'doublemajor', 'dubinski'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_44
  WTF: {'audio', 'returned', 'problem'} {'emerson', 'hifi', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_45
  WTF: {'promote'} {'fenholt'}
topic_46
  WTF: {'mole', 'gigabytes', 'leave'} {'eachus', 'avagadros', 'menuts'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_47
  WTF: {'trinomials', '0n', 'tp', '644', 'mm', 'pw', 'mj', 'ma', 'm1', 'u0', 'mf', 'mh'} {'p6', 'm3', 'm9', 'lu', 'm0', 'm5', 'o3', 'm6', 'pnospsxop8f', 'mw', 'e8', 'mx'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_48
  WTF: {'3rd'} {'ses'}
topic_49
  WTF: {'advertised', 'toilet', 'illusion'} {'kepley', 'workdays', 'mcguire'}
  WTF?!?!? 3
  WTF?!?!? 3

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f50285ba4f0>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f4ff13c5d60>}
{'perplexity': 50620.33984375, 'coherence_20': 1.835679509268841, 'diversity_euclidean': 0.09045936838277058, 'diversity_jensenshannon': 0.7021761788531902, 'diversity_hellinger': 0.8255944794600201, 'diversity_cosine': 0.8046380223680973, 'fair_ppl_free': 2053.462646484375, 'fair_ppl_fix': 50116.61328125, 'unfair_ppl_banklike': 50620.33984375}
{'num_topics': 51, 'num_common_words': 59415, 'num_model_words': 114951, 'num_bt_words': 97541, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 16, 'lost_bt': 1, 'lost_model': 15}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}]}
1
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
  WTF: {'vs'} {'nhl'}
topic_3
topic_4
  WTF: {'dont', 'diet', 'doctors'} {'hiv', 'n3jxp', 'gordon'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_5
topic_6
  WTF: {'discussion'} {'o157h7'}
topic_7
  WTF: {'ottoman', 'children', 'muslim', 'government', 'saw', 'started'} {'armenia', 'azerbaijan', 'armenians', 'sumgait', 'armenian', 'turks'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_8
  WTF: {'use'} {'bj200'}
topic_9
  WTF: {'NikeDeacon', 'CDROMCATZIP', '8800CS', 'CSCSTD00385', 'dragdrop', 'NikeCajun', '5152940082', 'recollection', 'taxation', '1795', '207556000', 'toolbox', 'effortsall', 'L2PMABGZ7VAZV0PZRI'} {''}
  WTF?!?!? 14
topic_10
topic_11
  WTF: {'football', 'adventure', '35'} {'snes', 'cdi', 'sega'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_12
topic_13
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_14
topic_15
  WTF: {'festival'} {'ishtar'}
topic_16
  WTF: {'general', 'plasktbdemoncouk', '19851986', '19891990'} {'ets', 'boulder', 'gre', 'rex'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_17
  WTF: {'analytic', '02106chopinudeledu', 'vol', 'email', 'copyright', 'writing'} {'vernor', 'dune', 'hogan', 'baen', 'gibson', 'vinge'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_18
  WTF: {'insisting', 'chemicals'} {'shafer', 'cato'}
topic_19
topic_20
  WTF: {'use', '250'} {'irwin', 'mactools'}
topic_21
  WTF: {'southern', 'armada', 'new', 'fleet', 'islands', 'installations', 'plan'} {'rockefeller', 'bolsheviks', 'argentina', 'falklands', 'georgia', 'argentine', 'bolshevik'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_22
topic_23
  WTF: {'handheld', 'scans', 'grayscales', 'market', 'buy', '400'} {'ocr', 'dexxa', 'mustek', 'scanman', 'paintbrush', 'ocr104zip'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_24
  WTF: {'try', 'card'} {'sb', 'microsofts'}
topic_25
topic_26
topic_27
  WTF: {'year'} {'aiken'}
topic_28
  WTF: {'waxed', 'stuff', 'molding'} {'glaze', 'meguiars', 'mcquires'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_29
  WTF: {'objects', 'charged'} {'kirlian', 'krillean'}
topic_30
  WTF: {'regards', 'stripped'} {'sehari', 'babak'}
topic_31
  WTF: {'49er', 'mit', 'nick'} {'quincy', 'cambridge', 'sept'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_32
  WTF: {'type', 'dim'} {'emi', 'hv'}
topic_33
  WTF: {'list', 'utter', 'jobs', 'military'} {'registries', 'admistration', 'irs', 'c17'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_34
  WTF: {'bet', 'production', '20', 'compsysamigagraphics', 'pictures'} {'ipas', '3do', 'titan', 'icbm', 'v200'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_35
  WTF: {'bang', 'forget', 'rule'} {'alice', 'douglas', 'adams'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_36
  WTF: {'6192214511', 'runnining', 'pubdkbtraceutils', 'outputing', '6192212527', 'raytrace'} {'zeh', 'a0size', 'tce', 'perth', 'versatec', 'succes'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_37
  WTF: {'worse', 'dangerous', 'germany'} {'fatti', 'femine', 'calverts'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_38
  WTF: {'ground', 'horizontal', 'reliability'} {'emerson', 'hifi', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_39
  WTF: {'combination'} {'lonoak'}
topic_40
  WTF: {'quite'} {'biscayne'}
topic_41
  WTF: {'uuencode', 'ioccc'} {'eofnotok', 'xvoid'}
topic_42
  WTF: {'screen', 'correct', 'trick'} {'robbinsgreat', 'supercharging', 'judd'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_43
  WTF: {'pads', 'addition', 'combo', 'version', 'stabilized'} {'t4', 'energiam', 't4centaur', 'russia', 'salyut'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_44
  WTF: {'patchmaking', 'unpatentable', 'remixed', 'vending'} {'cocacola', 'cola', 'yerazunis', 'pepsi'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_45
  WTF: {'trinomials', '0n', 'tp', '644', 'mm', 'pw', 'mj', 'ma', 'm1', 'u0', 'mf', 'mh'} {'p6', 'm3', 'm9', 'lu', 'm0', 'm5', 'o3', 'm6', 'pnospsxop8f', 'mw', 'e8', 'mx'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_46
  WTF: {'reference', 'loan', 'kernel'} {'mym', 'tns', 'q6'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_47
  WTF: {'list', 'archive', 'cerritos', 'patches'} {'denizen', 'heritick', 'hopalonga', 'kotl'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_48
  WTF: {'promote'} {'fenholt'}
topic_49
  WTF: {'shoulf'} {'aplace'}
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f4fe86d86d0>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
  WTF: {'vs'} {'nhl'}
topic_3
topic_4
  WTF: {'dont', 'diet', 'doctors'} {'hiv', 'n3jxp', 'gordon'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_5
topic_6
  WTF: {'discussion'} {'o157h7'}
topic_7
  WTF: {'ottoman', 'children', 'muslim', 'government', 'saw', 'started'} {'armenia', 'azerbaijan', 'armenians', 'sumgait', 'armenian', 'turks'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_8
  WTF: {'use'} {'bj200'}
topic_9
  WTF: {'NikeDeacon', 'CDROMCATZIP', '8800CS', 'CSCSTD00385', 'dragdrop', 'NikeCajun', '5152940082', 'recollection', 'taxation', '1795', '207556000', 'toolbox', 'effortsall', 'L2PMABGZ7VAZV0PZRI'} {''}
  WTF?!?!? 14
topic_10
topic_11
  WTF: {'football', 'adventure', '35'} {'snes', 'cdi', 'sega'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_12
topic_13
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_14
topic_15
  WTF: {'festival'} {'ishtar'}
topic_16
  WTF: {'general', 'plasktbdemoncouk', '19851986', '19891990'} {'ets', 'boulder', 'gre', 'rex'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_17
  WTF: {'analytic', '02106chopinudeledu', 'vol', 'email', 'copyright', 'writing'} {'vernor', 'dune', 'hogan', 'baen', 'gibson', 'vinge'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_18
  WTF: {'insisting', 'chemicals'} {'shafer', 'cato'}
topic_19
topic_20
  WTF: {'use', '250'} {'irwin', 'mactools'}
topic_21
  WTF: {'southern', 'armada', 'new', 'fleet', 'islands', 'installations', 'plan'} {'rockefeller', 'bolsheviks', 'argentina', 'falklands', 'georgia', 'argentine', 'bolshevik'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_22
topic_23
  WTF: {'handheld', 'scans', 'grayscales', 'market', 'buy', '400'} {'ocr', 'dexxa', 'mustek', 'scanman', 'paintbrush', 'ocr104zip'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_24
  WTF: {'try', 'card'} {'sb', 'microsofts'}
topic_25
topic_26
topic_27
  WTF: {'year'} {'aiken'}
topic_28
  WTF: {'waxed', 'stuff', 'molding'} {'glaze', 'meguiars', 'mcquires'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_29
  WTF: {'objects', 'charged'} {'kirlian', 'krillean'}
topic_30
  WTF: {'regards', 'stripped'} {'sehari', 'babak'}
topic_31
  WTF: {'49er', 'mit', 'nick'} {'quincy', 'cambridge', 'sept'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_32
  WTF: {'type', 'dim'} {'emi', 'hv'}
topic_33
  WTF: {'list', 'utter', 'jobs', 'military'} {'registries', 'admistration', 'irs', 'c17'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_34
  WTF: {'bet', 'production', '20', 'compsysamigagraphics', 'pictures'} {'ipas', '3do', 'titan', 'icbm', 'v200'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_35
  WTF: {'bang', 'forget', 'rule'} {'alice', 'douglas', 'adams'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_36
  WTF: {'6192214511', 'runnining', 'pubdkbtraceutils', 'outputing', '6192212527', 'raytrace'} {'zeh', 'a0size', 'tce', 'perth', 'versatec', 'succes'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_37
  WTF: {'worse', 'dangerous', 'germany'} {'fatti', 'femine', 'calverts'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_38
  WTF: {'ground', 'horizontal', 'reliability'} {'emerson', 'hifi', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_39
  WTF: {'combination'} {'lonoak'}
topic_40
  WTF: {'quite'} {'biscayne'}
topic_41
  WTF: {'uuencode', 'ioccc'} {'eofnotok', 'xvoid'}
topic_42
  WTF: {'screen', 'correct', 'trick'} {'robbinsgreat', 'supercharging', 'judd'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_43
  WTF: {'pads', 'addition', 'combo', 'version', 'stabilized'} {'t4', 'energiam', 't4centaur', 'russia', 'salyut'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_44
  WTF: {'patchmaking', 'unpatentable', 'remixed', 'vending'} {'cocacola', 'cola', 'yerazunis', 'pepsi'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_45
  WTF: {'trinomials', '0n', 'tp', '644', 'mm', 'pw', 'mj', 'ma', 'm1', 'u0', 'mf', 'mh'} {'p6', 'm3', 'm9', 'lu', 'm0', 'm5', 'o3', 'm6', 'pnospsxop8f', 'mw', 'e8', 'mx'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_46
  WTF: {'reference', 'loan', 'kernel'} {'mym', 'tns', 'q6'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_47
  WTF: {'list', 'archive', 'cerritos', 'patches'} {'denizen', 'heritick', 'hopalonga', 'kotl'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_48
  WTF: {'promote'} {'fenholt'}
topic_49
  WTF: {'shoulf'} {'aplace'}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f4fe871ee50>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f4ff13c5d60>}
{'perplexity': 52182.9765625, 'coherence_20': 1.6751836238950473, 'diversity_euclidean': 0.10051696403037613, 'diversity_jensenshannon': 0.7374930905438268, 'diversity_hellinger': 0.8706478183859896, 'diversity_cosine': 0.8560379626842046, 'fair_ppl_free': 2118.781494140625, 'fair_ppl_fix': 51689.3515625, 'unfair_ppl_banklike': 52182.9765625}
{'num_topics': 51, 'num_common_words': 59415, 'num_model_words': 114951, 'num_bt_words': 97541, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 15, 'lost_bt': 1, 'lost_model': 14}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}]}
2
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
  WTF: {'state'} {'fbi'}
topic_2
topic_3
  WTF: {'vs'} {'nhl'}
topic_4
topic_5
  WTF: {'diet', 'surrender', 'dont'} {'hiv', 'n3jxp', 'gordon'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_6
topic_7
topic_8
  WTF: {'votes'} {'o157h7'}
topic_9
  WTF: {'ottoman', 'children', 'muslim', 'government', 'saw', 'started'} {'armenia', 'azerbaijan', 'armenians', 'sumgait', 'armenian', 'turks'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_10
  WTF: {'ps'} {'bj200'}
topic_11
  WTF: {'CDROMCATZIP', 'ringleaders', 'CSCSTD00385', 'dragdrop', 'NikeCajun', '8800CS', '5152940082', 'taxation', 'Epilepsy', 'knowlege', '1795', '207556000', 'toolbox', 'effortsall', 'L2PMABGZ7VAZV0PZRI'} {''}
  WTF?!?!? 15
topic_12
  WTF: {'football', 'adventure', '35'} {'snes', 'cdi', 'sega'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_13
  WTF: {'congress', 'dont'} {'myers', 'stephanopoulos'}
topic_14
  WTF: {'use', 'posting'} {'rsa', 'ripem'}
topic_15
  WTF: {'mesur', 'solve', 'envoy', 'article', 'printing', 'wild', 'russian', 'famous'} {'armenia', 'persians', 'iosef', 'shirak', 'tyukhik', 'anania', 'armenian', 'orbeli'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_16
topic_17
topic_18
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_19
  WTF: {'festival'} {'ishtar'}
topic_20
topic_21
  WTF: {'use', '250'} {'irwin', 'mactools'}
topic_22
  WTF: {'analytic', '02106chopinudeledu', 'vol', 'copyright', 'explanations', 'writing'} {'vernor', 'dune', 'baen', 'gre', 'gibson', 'vinge'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_23
topic_24
  WTF: {'circuitry', 'voltage'} {'emerson', 'vcr'}
topic_25
  WTF: {'intrinsics'} {'r3'}
topic_26
  WTF: {'try', 'card'} {'sb', 'microsofts'}
topic_27
topic_28
  WTF: {'handheld', 'scans', 'grayscales', 'market', 'buy', '400'} {'ocr', 'dexxa', 'mustek', 'scanman', 'paintbrush', 'ocr104zip'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_29
  WTF: {'doityourselfers', 'know'} {'kirlian', 'krillean'}
topic_30
topic_31
topic_32
  WTF: {'use'} {'heydt'}
topic_33
  WTF: {'regards', 'stripped'} {'sehari', 'babak'}
topic_34
  WTF: {'list', 'utter', 'jobs', 'military'} {'registries', 'admistration', 'irs', 'c17'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_35
  WTF: {'april'} {'hicnet'}
topic_36
  WTF: {'worse', 'dangerous', 'germany'} {'fatti', 'femine', 'calverts'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_37
  WTF: {'bb', 'interested', 'mit'} {'quincy', 'cambridge', 'sept'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_38
  WTF: {'theory'} {'alice'}
topic_39
  WTF: {'safety', 'power', 'launch'} {'tripoli', 'hpr', 'faa'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_40
  WTF: {'nebulised'} {'bridgend'}
topic_41
topic_42
  WTF: {'pads', 'addition', 'combo', 'version', 'stabilized'} {'t4', 'energiam', 't4centaur', 'russia', 'salyut'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_43
  WTF: {'patchmaking', 'unpatentable', 'remixed', 'vending'} {'cocacola', 'cola', 'yerazunis', 'pepsi'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_44
  WTF: {'heinous', 'discussion', 'stalled'} {'transarc', 'hoovers', 'lyle'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_45
  WTF: {'windscreen', 'nucleus', 'coma', 'yknow'} {'tommy', 'canopies', 'punchline', 'mcwilliams'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_46
  WTF: {'mr', 'oddly', 'nazism', 'moments', 'ya', 'hell', 'utilize', 'dem'} {'timucin', 'yo', 'turc', 'srinivas', 'hoffnung', 'koph', 'zeuge', 'davidssons'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_47
  WTF: {'trinomials', '0n', 'tp', '644', 'mm', 'pw', 'mj', 'ma', 'm1', 'u0', 'mf', 'mh'} {'p6', 'm3', 'm9', 'lu', 'm0', 'm5', 'o3', 'm6', 'pnospsxop8f', 'mw', 'e8', 'mx'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_48
  WTF: {'publications', 'product', 'licensed', 'internet', 'science', 'promote', 'include'} {'marquette', 'regal', 'milwaukee', 'wi', 'robb', 'doublemajor', 'dubinski'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_49
  WTF: {'bullshitting', 'tooling', '300', 'compsysamigagraphics', 'licensees', 'preproduction'} {'bitmovie', '3do', 'activa', 'riccione', 'visicalc', 'sergio'}
  WTF?!?!? 6
  WTF?!?!? 6
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f4fe86caeb0>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
  WTF: {'state'} {'fbi'}
topic_2
topic_3
  WTF: {'vs'} {'nhl'}
topic_4
topic_5
  WTF: {'diet', 'surrender', 'dont'} {'hiv', 'n3jxp', 'gordon'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_6
topic_7
topic_8
  WTF: {'votes'} {'o157h7'}
topic_9
  WTF: {'ottoman', 'children', 'muslim', 'government', 'saw', 'started'} {'armenia', 'azerbaijan', 'armenians', 'sumgait', 'armenian', 'turks'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_10
  WTF: {'ps'} {'bj200'}
topic_11
  WTF: {'CDROMCATZIP', 'ringleaders', 'CSCSTD00385', 'dragdrop', 'NikeCajun', '8800CS', '5152940082', 'taxation', 'Epilepsy', 'knowlege', '1795', '207556000', 'toolbox', 'effortsall', 'L2PMABGZ7VAZV0PZRI'} {''}
  WTF?!?!? 15
topic_12
  WTF: {'football', 'adventure', '35'} {'snes', 'cdi', 'sega'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_13
  WTF: {'congress', 'dont'} {'myers', 'stephanopoulos'}
topic_14
  WTF: {'use', 'posting'} {'rsa', 'ripem'}
topic_15
  WTF: {'mesur', 'solve', 'envoy', 'article', 'printing', 'wild', 'russian', 'famous'} {'armenia', 'persians', 'iosef', 'shirak', 'tyukhik', 'anania', 'armenian', 'orbeli'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_16
topic_17
topic_18
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_19
  WTF: {'festival'} {'ishtar'}
topic_20
topic_21
  WTF: {'use', '250'} {'irwin', 'mactools'}
topic_22
  WTF: {'analytic', '02106chopinudeledu', 'vol', 'copyright', 'explanations', 'writing'} {'vernor', 'dune', 'baen', 'gre', 'gibson', 'vinge'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_23
topic_24
  WTF: {'circuitry', 'voltage'} {'emerson', 'vcr'}
topic_25
  WTF: {'intrinsics'} {'r3'}
topic_26
  WTF: {'try', 'card'} {'sb', 'microsofts'}
topic_27
topic_28
  WTF: {'handheld', 'scans', 'grayscales', 'market', 'buy', '400'} {'ocr', 'dexxa', 'mustek', 'scanman', 'paintbrush', 'ocr104zip'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_29
  WTF: {'doityourselfers', 'know'} {'kirlian', 'krillean'}
topic_30
topic_31
topic_32
  WTF: {'use'} {'heydt'}
topic_33
  WTF: {'regards', 'stripped'} {'sehari', 'babak'}
topic_34
  WTF: {'list', 'utter', 'jobs', 'military'} {'registries', 'admistration', 'irs', 'c17'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_35
  WTF: {'april'} {'hicnet'}
topic_36
  WTF: {'worse', 'dangerous', 'germany'} {'fatti', 'femine', 'calverts'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_37
  WTF: {'bb', 'interested', 'mit'} {'quincy', 'cambridge', 'sept'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_38
  WTF: {'theory'} {'alice'}
topic_39
  WTF: {'safety', 'power', 'launch'} {'tripoli', 'hpr', 'faa'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_40
  WTF: {'nebulised'} {'bridgend'}
topic_41
topic_42
  WTF: {'pads', 'addition', 'combo', 'version', 'stabilized'} {'t4', 'energiam', 't4centaur', 'russia', 'salyut'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_43
  WTF: {'patchmaking', 'unpatentable', 'remixed', 'vending'} {'cocacola', 'cola', 'yerazunis', 'pepsi'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_44
  WTF: {'heinous', 'discussion', 'stalled'} {'transarc', 'hoovers', 'lyle'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_45
  WTF: {'windscreen', 'nucleus', 'coma', 'yknow'} {'tommy', 'canopies', 'punchline', 'mcwilliams'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_46
  WTF: {'mr', 'oddly', 'nazism', 'moments', 'ya', 'hell', 'utilize', 'dem'} {'timucin', 'yo', 'turc', 'srinivas', 'hoffnung', 'koph', 'zeuge', 'davidssons'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_47
  WTF: {'trinomials', '0n', 'tp', '644', 'mm', 'pw', 'mj', 'ma', 'm1', 'u0', 'mf', 'mh'} {'p6', 'm3', 'm9', 'lu', 'm0', 'm5', 'o3', 'm6', 'pnospsxop8f', 'mw', 'e8', 'mx'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_48
  WTF: {'publications', 'product', 'licensed', 'internet', 'science', 'promote', 'include'} {'marquette', 'regal', 'milwaukee', 'wi', 'robb', 'doublemajor', 'dubinski'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_49
  WTF: {'bullshitting', 'tooling', '300', 'compsysamigagraphics', 'licensees', 'preproduction'} {'bitmovie', '3do', 'activa', 'riccione', 'visicalc', 'sergio'}
  WTF?!?!? 6
  WTF?!?!? 6

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f4ff13c5820>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f4fe611ad90>}
{'perplexity': 50938.7265625, 'coherence_20': 1.6872127386984748, 'diversity_euclidean': 0.09114985648942356, 'diversity_jensenshannon': 0.7083279990067616, 'diversity_hellinger': 0.8330178583437285, 'diversity_cosine': 0.811709274206031, 'fair_ppl_free': 2065.5439453125, 'fair_ppl_fix': 50273.37890625, 'unfair_ppl_banklike': 50938.7265625}
{'num_topics': 51, 'num_common_words': 59415, 'num_model_words': 114951, 'num_bt_words': 97541, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 16, 'lost_bt': 1, 'lost_model': 15}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}]}
3
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
topic_3
topic_4
  WTF: {'12'} {'nhl'}
topic_5
  WTF: {'candida', 'surrender', 'dont'} {'hiv', 'n3jxp', 'gordon'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_6
topic_7
topic_8
  WTF: {'posting', 'thanks'} {'o157h7', 'anania'}
topic_9
  WTF: {'ottoman', 'children', 'muslim', 'government', 'saw', 'started'} {'armenia', 'azerbaijan', 'armenians', 'sumgait', 'armenian', 'turks'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_10
  WTF: {'quality'} {'bj200'}
topic_11
topic_12
  WTF: {'CDROMCATZIP', 'ringleaders', 'CSCSTD00385', 'dragdrop', 'NikeCajun', '8800CS', '5152940082', 'taxation', 'Epilepsy', 'knowlege', '1795', '207556000', 'toolbox', 'effortsall', 'L2PMABGZ7VAZV0PZRI'} {''}
  WTF?!?!? 15
topic_13
topic_14
topic_15
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_16
topic_17
topic_18
  WTF: {'live', 'insisting', 'fuel'} {'shafer', 'dryden', 'cato'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_19
  WTF: {'analytic', '02106chopinudeledu', 'vol', 'copyright', 'fortran', 'writing'} {'vernor', 'hogan', 'baen', 'gibson', 'vinge', 'petrucci'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_20
  WTF: {'format', 'email'} {'irwin', 'mactools'}
topic_21
  WTF: {'try', 'card'} {'sb', 'microsofts'}
topic_22
  WTF: {'intrinsics'} {'r3'}
topic_23
  WTF: {'circuitry', 'heh'} {'emerson', 'vcr'}
topic_24
  WTF: {'people', 'english'} {'ishtar', 'bede'}
topic_25
  WTF: {'objects', 'charged'} {'kirlian', 'krillean'}
topic_26
  WTF: {'network', 'using', 'machines'} {'ndis', 'wfwg', 'odi'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_27
topic_28
topic_29
  WTF: {'aside'} {'darius'}
topic_30
  WTF: {'lemmings'} {'soundbase'}
topic_31
  WTF: {'cute'} {'heydt'}
topic_32
  WTF: {'paying', 'regulator'} {'geico', 'nofault'}
topic_33
  WTF: {'regards', 'stripped'} {'sehari', 'babak'}
topic_34
  WTF: {'49er', 'mit', 'nick'} {'quincy', 'cambridge', 'sept'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_35
  WTF: {'bang', 'forget', 'rule'} {'alice', 'douglas', 'adams'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_36
  WTF: {'engineers', 'participants', 'tutorial', 'conference'} {'mellon', 'japan', 'carnegie', 'jstmp'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_37
  WTF: {'utter', 'axe', 'commission'} {'registries', 'admistration', 'irs'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_38
  WTF: {'motor', 'propellant', 'class'} {'tripoli', 'hpr', 'faa'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_39
  WTF: {'320x240', 'movie', 'hardisk', 'performance'} {'ramvram', 'compactvideo', '3d0o', '3do'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_40
  WTF: {'uuencode', 'ioccc'} {'eofnotok', 'xvoid'}
topic_41
  WTF: {'specificed', 'existing'} {'avagadros', 'scotyy'}
topic_42
  WTF: {'tradition', 'years'} {'olympia', 'joe'}
topic_43
  WTF: {'screen', 'correct', 'trick'} {'robbinsgreat', 'supercharging', 'judd'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_44
  WTF: {'pads', 'addition', 'combo', 'version', 'stabilized'} {'t4', 'energiam', 't4centaur', 'russia', 'salyut'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_45
  WTF: {'trinomials', '0n', 'tp', '644', 'mm', 'pw', 'mj', 'ma', 'm1', 'u0', 'mf', 'mh'} {'p6', 'm3', 'm9', 'lu', 'm0', 'm5', 'o3', 'm6', 'pnospsxop8f', 'mw', 'e8', 'mx'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_46
  WTF: {'fee', 'involved', 'construction', 'writes', 'aj', 'equally'} {'newman', 'daniel', 'reitman', 'ajteeldendritecscoloradoedu', 'teel', 'schiff'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_47
  WTF: {'drag'} {'mary'}
topic_48
  WTF: {'ghetto', 'centers', 'scientific', 'sun', 'culture', 'memorial', 'service'} {'iki', 'belorusskaya', 'kremlin', 'moscow', 'nozyk', 'palace', 'shul'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_49
  WTF: {'cover', 'design', 'sooo', 'ideas', 'infringing', 'concentrates', 'merciless'} {'pepsicos', 'crah', 'cocacola', 'yerazunis', 'pepsi', 'rc4', 'cola'}
  WTF?!?!? 7
  WTF?!?!? 7
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f4ff13c07c0>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
topic_3
topic_4
  WTF: {'12'} {'nhl'}
topic_5
  WTF: {'candida', 'surrender', 'dont'} {'hiv', 'n3jxp', 'gordon'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_6
topic_7
topic_8
  WTF: {'posting', 'thanks'} {'o157h7', 'anania'}
topic_9
  WTF: {'ottoman', 'children', 'muslim', 'government', 'saw', 'started'} {'armenia', 'azerbaijan', 'armenians', 'sumgait', 'armenian', 'turks'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_10
  WTF: {'quality'} {'bj200'}
topic_11
topic_12
  WTF: {'CDROMCATZIP', 'ringleaders', 'CSCSTD00385', 'dragdrop', 'NikeCajun', '8800CS', '5152940082', 'taxation', 'Epilepsy', 'knowlege', '1795', '207556000', 'toolbox', 'effortsall', 'L2PMABGZ7VAZV0PZRI'} {''}
  WTF?!?!? 15
topic_13
topic_14
topic_15
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_16
topic_17
topic_18
  WTF: {'live', 'insisting', 'fuel'} {'shafer', 'dryden', 'cato'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_19
  WTF: {'analytic', '02106chopinudeledu', 'vol', 'copyright', 'fortran', 'writing'} {'vernor', 'hogan', 'baen', 'gibson', 'vinge', 'petrucci'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_20
  WTF: {'format', 'email'} {'irwin', 'mactools'}
topic_21
  WTF: {'try', 'card'} {'sb', 'microsofts'}
topic_22
  WTF: {'intrinsics'} {'r3'}
topic_23
  WTF: {'circuitry', 'heh'} {'emerson', 'vcr'}
topic_24
  WTF: {'people', 'english'} {'ishtar', 'bede'}
topic_25
  WTF: {'objects', 'charged'} {'kirlian', 'krillean'}
topic_26
  WTF: {'network', 'using', 'machines'} {'ndis', 'wfwg', 'odi'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_27
topic_28
topic_29
  WTF: {'aside'} {'darius'}
topic_30
  WTF: {'lemmings'} {'soundbase'}
topic_31
  WTF: {'cute'} {'heydt'}
topic_32
  WTF: {'paying', 'regulator'} {'geico', 'nofault'}
topic_33
  WTF: {'regards', 'stripped'} {'sehari', 'babak'}
topic_34
  WTF: {'49er', 'mit', 'nick'} {'quincy', 'cambridge', 'sept'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_35
  WTF: {'bang', 'forget', 'rule'} {'alice', 'douglas', 'adams'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_36
  WTF: {'engineers', 'participants', 'tutorial', 'conference'} {'mellon', 'japan', 'carnegie', 'jstmp'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_37
  WTF: {'utter', 'axe', 'commission'} {'registries', 'admistration', 'irs'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_38
  WTF: {'motor', 'propellant', 'class'} {'tripoli', 'hpr', 'faa'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_39
  WTF: {'320x240', 'movie', 'hardisk', 'performance'} {'ramvram', 'compactvideo', '3d0o', '3do'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_40
  WTF: {'uuencode', 'ioccc'} {'eofnotok', 'xvoid'}
topic_41
  WTF: {'specificed', 'existing'} {'avagadros', 'scotyy'}
topic_42
  WTF: {'tradition', 'years'} {'olympia', 'joe'}
topic_43
  WTF: {'screen', 'correct', 'trick'} {'robbinsgreat', 'supercharging', 'judd'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_44
  WTF: {'pads', 'addition', 'combo', 'version', 'stabilized'} {'t4', 'energiam', 't4centaur', 'russia', 'salyut'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_45
  WTF: {'trinomials', '0n', 'tp', '644', 'mm', 'pw', 'mj', 'ma', 'm1', 'u0', 'mf', 'mh'} {'p6', 'm3', 'm9', 'lu', 'm0', 'm5', 'o3', 'm6', 'pnospsxop8f', 'mw', 'e8', 'mx'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_46
  WTF: {'fee', 'involved', 'construction', 'writes', 'aj', 'equally'} {'newman', 'daniel', 'reitman', 'ajteeldendritecscoloradoedu', 'teel', 'schiff'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_47
  WTF: {'drag'} {'mary'}
topic_48
  WTF: {'ghetto', 'centers', 'scientific', 'sun', 'culture', 'memorial', 'service'} {'iki', 'belorusskaya', 'kremlin', 'moscow', 'nozyk', 'palace', 'shul'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_49
  WTF: {'cover', 'design', 'sooo', 'ideas', 'infringing', 'concentrates', 'merciless'} {'pepsicos', 'crah', 'cocacola', 'yerazunis', 'pepsi', 'rc4', 'cola'}
  WTF?!?!? 7
  WTF?!?!? 7

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f4f43b89310>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f4fd47f7340>}
{'perplexity': 50915.80078125, 'coherence_20': 1.7457575088452784, 'diversity_euclidean': 0.09301388874673185, 'diversity_jensenshannon': 0.7130466641196616, 'diversity_hellinger': 0.8393837608223557, 'diversity_cosine': 0.8201445372279059, 'fair_ppl_free': 2061.677734375, 'fair_ppl_fix': 50217.4765625, 'unfair_ppl_banklike': 50915.80078125}
{'num_topics': 51, 'num_common_words': 59415, 'num_model_words': 114951, 'num_bt_words': 97541, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 16, 'lost_bt': 1, 'lost_model': 15}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}]}
4
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
  WTF: {'vs'} {'nhl'}
topic_3
topic_4
topic_5
  WTF: {'candida', 'surrender', 'dont'} {'hiv', 'n3jxp', 'gordon'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_6
topic_7
topic_8
  WTF: {'votes'} {'o157h7'}
topic_9
topic_10
  WTF: {'ottoman', 'children', 'muslim', 'government', 'saw', 'started'} {'armenia', 'azerbaijan', 'armenians', 'sumgait', 'armenian', 'turks'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_11
  WTF: {'driver'} {'bj200'}
topic_12
  WTF: {'CDROMCATZIP', 'ringleaders', 'CSCSTD00385', 'dragdrop', 'NikeCajun', '8800CS', '5152940082', 'taxation', 'Epilepsy', 'knowlege', '1795', '207556000', 'toolbox', 'effortsall', 'L2PMABGZ7VAZV0PZRI'} {''}
  WTF?!?!? 15
topic_13
  WTF: {'posting', 'email'} {'rsa', 'ripem'}
topic_14
  WTF: {'transferable'} {'hotelco'}
topic_15
topic_16
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_17
  WTF: {'declutch'} {'caltrans'}
topic_18
topic_19
  WTF: {'reactor'} {'cato'}
topic_20
topic_21
  WTF: {'use', '250'} {'irwin', 'mactools'}
topic_22
topic_23
  WTF: {'analytic', '02106chopinudeledu', 'vol', 'copyright', 'manual', 'writing'} {'vernor', 'dune', 'hogan', 'baen', 'gibson', 'vinge'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_24
  WTF: {'server'} {'r3'}
topic_25
  WTF: {'doityourselfers', 'know'} {'kirlian', 'krillean'}
topic_26
topic_27
  WTF: {'handheld', 'scans', 'resoltuion', 'market', 'buy', '400'} {'ocr', 'dexxa', 'mustek', 'scanman', 'paintbrush', 'ocr104zip'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_28
topic_29
topic_30
  WTF: {'aside'} {'darius'}
topic_31
  WTF: {'vulnerable', 'shield'} {'emi', 'hv'}
topic_32
  WTF: {'49er', 'mit', 'nick'} {'quincy', 'cambridge', 'sept'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_33
  WTF: {'regards', 'stripped'} {'sehari', 'babak'}
topic_34
  WTF: {'number', 'rule', 'computer'} {'alice', 'douglas', 'adams'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_35
  WTF: {'uuencode', 'ioccc'} {'eofnotok', 'xvoid'}
topic_36
topic_37
  WTF: {'element', 'km', 'phase', 'geodetic', 'results', 'radars', 'pattern'} {'kyoto', 'ohzora', 'japan', 'sato', 'rrl', 'egs', 'exosc'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_38
  WTF: {'difference'} {'dj'}
topic_39
  WTF: {'corps', 'axe', 'commission'} {'registries', 'admistration', 'irs'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_40
topic_41
  WTF: {'somethin', 'memorable', 'trench', 'changing', 'dont'} {'dykstra', 'yankess', 'ballad', 'subterranean', 'anime'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_42
topic_43
  WTF: {'audio', 'returned', 'problem'} {'emerson', 'hifi', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_44
  WTF: {'2275753', 'lipmanoasysdtnavymil', 'pace', '2273618'} {'siggraph', 'bethesda', 'lipman', 'sigkids'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_45
  WTF: {'trinomials', '0n', 'tp', '644', 'mm', 'pw', 'mj', 'ma', 'm1', 'u0', 'mf', 'mh'} {'p6', 'm3', 'm9', 'lu', 'm0', 'm5', 'pnospsxop8f', 'm6', 'o3', 'mw', 'e8', 'mx'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_46
  WTF: {'tradition', 'years'} {'olympia', 'joe'}
topic_47
  WTF: {'pads', 'addition', 'combo', 'version', 'stabilized'} {'t4', 'energiam', 't4centaur', 'russia', 'salyut'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_48
  WTF: {'flight', 'purchase', 'popular'} {'tripoli', 'hpr', 'faa'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_49
  WTF: {'improvements', 'upgrading', 'version'} {'ipas', 'photostyler', 'v200'}
  WTF?!?!? 3
  WTF?!?!? 3
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f4fff1b0e80>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
  WTF: {'vs'} {'nhl'}
topic_3
topic_4
topic_5
  WTF: {'candida', 'surrender', 'dont'} {'hiv', 'n3jxp', 'gordon'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_6
topic_7
topic_8
  WTF: {'votes'} {'o157h7'}
topic_9
topic_10
  WTF: {'ottoman', 'children', 'muslim', 'government', 'saw', 'started'} {'armenia', 'azerbaijan', 'armenians', 'sumgait', 'armenian', 'turks'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_11
  WTF: {'driver'} {'bj200'}
topic_12
  WTF: {'CDROMCATZIP', 'ringleaders', 'CSCSTD00385', 'dragdrop', 'NikeCajun', '8800CS', '5152940082', 'taxation', 'Epilepsy', 'knowlege', '1795', '207556000', 'toolbox', 'effortsall', 'L2PMABGZ7VAZV0PZRI'} {''}
  WTF?!?!? 15
topic_13
  WTF: {'posting', 'email'} {'rsa', 'ripem'}
topic_14
  WTF: {'transferable'} {'hotelco'}
topic_15
topic_16
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_17
  WTF: {'declutch'} {'caltrans'}
topic_18
topic_19
  WTF: {'reactor'} {'cato'}
topic_20
topic_21
  WTF: {'use', '250'} {'irwin', 'mactools'}
topic_22
topic_23
  WTF: {'analytic', '02106chopinudeledu', 'vol', 'copyright', 'manual', 'writing'} {'vernor', 'dune', 'hogan', 'baen', 'gibson', 'vinge'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_24
  WTF: {'server'} {'r3'}
topic_25
  WTF: {'doityourselfers', 'know'} {'kirlian', 'krillean'}
topic_26
topic_27
  WTF: {'handheld', 'scans', 'resoltuion', 'market', 'buy', '400'} {'ocr', 'dexxa', 'mustek', 'scanman', 'paintbrush', 'ocr104zip'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_28
topic_29
topic_30
  WTF: {'aside'} {'darius'}
topic_31
  WTF: {'vulnerable', 'shield'} {'emi', 'hv'}
topic_32
  WTF: {'49er', 'mit', 'nick'} {'quincy', 'cambridge', 'sept'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_33
  WTF: {'regards', 'stripped'} {'sehari', 'babak'}
topic_34
  WTF: {'number', 'rule', 'computer'} {'alice', 'douglas', 'adams'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_35
  WTF: {'uuencode', 'ioccc'} {'eofnotok', 'xvoid'}
topic_36
topic_37
  WTF: {'element', 'km', 'phase', 'geodetic', 'results', 'radars', 'pattern'} {'kyoto', 'ohzora', 'japan', 'sato', 'rrl', 'egs', 'exosc'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_38
  WTF: {'difference'} {'dj'}
topic_39
  WTF: {'corps', 'axe', 'commission'} {'registries', 'admistration', 'irs'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_40
topic_41
  WTF: {'somethin', 'memorable', 'trench', 'changing', 'dont'} {'dykstra', 'yankess', 'ballad', 'subterranean', 'anime'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_42
topic_43
  WTF: {'audio', 'returned', 'problem'} {'emerson', 'hifi', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_44
  WTF: {'2275753', 'lipmanoasysdtnavymil', 'pace', '2273618'} {'siggraph', 'bethesda', 'lipman', 'sigkids'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_45
  WTF: {'trinomials', '0n', 'tp', '644', 'mm', 'pw', 'mj', 'ma', 'm1', 'u0', 'mf', 'mh'} {'p6', 'm3', 'm9', 'lu', 'm0', 'm5', 'pnospsxop8f', 'm6', 'o3', 'mw', 'e8', 'mx'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_46
  WTF: {'tradition', 'years'} {'olympia', 'joe'}
topic_47
  WTF: {'pads', 'addition', 'combo', 'version', 'stabilized'} {'t4', 'energiam', 't4centaur', 'russia', 'salyut'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_48
  WTF: {'flight', 'purchase', 'popular'} {'tripoli', 'hpr', 'faa'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_49
  WTF: {'improvements', 'upgrading', 'version'} {'ipas', 'photostyler', 'v200'}
  WTF?!?!? 3
  WTF?!?!? 3

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f4fe8729880>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f4ff1656f40>}
{'perplexity': 51101.72265625, 'coherence_20': 1.8137469410685487, 'diversity_euclidean': 0.09078246907636559, 'diversity_jensenshannon': 0.7088417532591015, 'diversity_hellinger': 0.8340096270359957, 'diversity_cosine': 0.8134916165166107, 'fair_ppl_free': 2046.1607666015625, 'fair_ppl_fix': 50372.00390625, 'unfair_ppl_banklike': 51101.72265625}
{'num_topics': 51, 'num_common_words': 59415, 'num_model_words': 114951, 'num_bt_words': 97541, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 16, 'lost_bt': 1, 'lost_model': 15}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}]}
5
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
topic_3
  WTF: {'vs'} {'nhl'}
topic_4
topic_5
  WTF: {'diet', 'surrender', 'dont'} {'hiv', 'n3jxp', 'gordon'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_6
topic_7
topic_8
  WTF: {'posting'} {'o157h7'}
topic_9
  WTF: {'ottoman', 'children', 'muslim', 'government', 'saw', 'started'} {'armenia', 'azerbaijan', 'armenians', 'sumgait', 'armenian', 'turks'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_10
  WTF: {'scanner'} {'bj200'}
topic_11
  WTF: {'NikeDeacon', 'CDROMCATZIP', '8800CS', 'CSCSTD00385', 'dragdrop', 'NikeCajun', '5152940082', 'recollection', 'taxation', '1795', '207556000', 'toolbox', 'effortsall', 'L2PMABGZ7VAZV0PZRI'} {''}
  WTF?!?!? 14
topic_12
  WTF: {'transferable'} {'hotelco'}
topic_13
topic_14
topic_15
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_16
  WTF: {'general', 'karichaeiscalstateedu', 'length', 'testtaking'} {'ets', 'boulder', 'gre', 'rex'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_17
  WTF: {'reactor'} {'cato'}
topic_18
topic_19
  WTF: {'analytic', '02106chopinudeledu', 'vol', 'copyright', 'manual', 'writing'} {'vernor', 'hogan', 'baen', 'gibson', 'vinge', 'petrucci'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_20
  WTF: {'people', 'pay', 'innate'} {'heydt', 'cnn', 'vip'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_21
  WTF: {'pickup', '250'} {'irwin', 'mactools'}
topic_22
  WTF: {'intrinsics'} {'r3'}
topic_23
topic_24
  WTF: {'try', 'card'} {'sb', 'microsofts'}
topic_25
  WTF: {'people', 'spring', 'english'} {'pesach', 'ishtar', 'bede'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_26
  WTF: {'objects', 'charged'} {'kirlian', 'krillean'}
topic_27
topic_28
  WTF: {'mesur', 'solve', 'envoy', 'typeset', 'printing', 'wild', 'russian', 'famous'} {'armenia', 'persians', 'iosef', 'shirak', 'tyukhik', 'anania', 'armenian', 'orbeli'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_29
  WTF: {'immoral', 'pork', 'bases', 'abolished'} {'registries', 'c5s', 'admistration', 'c17'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_30
  WTF: {'pm', 'students', 'cs', 'andrew'} {'mellon', 'japan', 'carnegie', 'jstmp'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_31
  WTF: {'regards', 'stripped'} {'sehari', 'babak'}
topic_32
  WTF: {'aside'} {'darius'}
topic_33
  WTF: {'49er', 'mit', 'nick'} {'quincy', 'cambridge', 'sept'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_34
  WTF: {'theory'} {'alice'}
topic_35
  WTF: {'sodium', 'propellant', 'class'} {'tripoli', 'hpr', 'faa'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_36
  WTF: {'use', 'readers', 'send', 'advertisers'} {'cocacola', 'cola', 'tektronics', 'pepsi'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_37
  WTF: {'expound', 'usa', 'youll'} {'transarc', 'hoovers', 'lyle'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_38
  WTF: {'pipes'} {'mary'}
topic_39
  WTF: {'screen', 'trick', 'switcher'} {'robbinsgreat', 'supercharging', 'judd'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_40
  WTF: {'spring', 'dark', 'direction', 'holds', 'signature'} {'exussr', 'nicks', 'pitily', 'albert', 'hrivnak'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_41
  WTF: {'tradition', 'years'} {'olympia', 'joe'}
topic_42
  WTF: {'pads', 'addition', 'combo', 'version', 'stabilized'} {'t4', 'energiam', 't4centaur', 'russia', 'salyut'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_43
  WTF: {'audio', 'returned', 'problem'} {'emerson', 'hifi', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_44
  WTF: {'1163', 'microns', '980665'} {'inhalation', 'bridgend', '9g'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_45
  WTF: {'promote'} {'fenholt'}
topic_46
  WTF: {'cuz', 'outlived'} {'menuts', 'scotyy'}
topic_47
  WTF: {'2275753', '2042', 'lipmanoasysdtnavymil', 'pace', '2273618'} {'bethesda', 'lipman', 'navyrelated', 'siggraph', 'sigkids'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_48
  WTF: {'trinomials', '0n', 'tp', '644', 'mm', 'pw', 'mj', 'ma', 'm1', 'u0', 'mf', 'mh'} {'p6', 'm3', 'm9', 'lu', 'm0', 'm5', 'o3', 'm6', 'pnospsxop8f', 'mw', 'e8', 'mx'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_49
  WTF: {'90s', 'rebel', 'giveaway', 'rednecks', '8177', 'soar', 'racers'} {'smokey', 'pgh', 'yogis', 'yogi', 'thumper', 'mcqueen', 'bandit'}
  WTF?!?!? 7
  WTF?!?!? 7
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f4fe86f3820>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
topic_3
  WTF: {'vs'} {'nhl'}
topic_4
topic_5
  WTF: {'diet', 'surrender', 'dont'} {'hiv', 'n3jxp', 'gordon'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_6
topic_7
topic_8
  WTF: {'posting'} {'o157h7'}
topic_9
  WTF: {'ottoman', 'children', 'muslim', 'government', 'saw', 'started'} {'armenia', 'azerbaijan', 'armenians', 'sumgait', 'armenian', 'turks'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_10
  WTF: {'scanner'} {'bj200'}
topic_11
  WTF: {'NikeDeacon', 'CDROMCATZIP', '8800CS', 'CSCSTD00385', 'dragdrop', 'NikeCajun', '5152940082', 'recollection', 'taxation', '1795', '207556000', 'toolbox', 'effortsall', 'L2PMABGZ7VAZV0PZRI'} {''}
  WTF?!?!? 14
topic_12
  WTF: {'transferable'} {'hotelco'}
topic_13
topic_14
topic_15
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_16
  WTF: {'general', 'karichaeiscalstateedu', 'length', 'testtaking'} {'ets', 'boulder', 'gre', 'rex'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_17
  WTF: {'reactor'} {'cato'}
topic_18
topic_19
  WTF: {'analytic', '02106chopinudeledu', 'vol', 'copyright', 'manual', 'writing'} {'vernor', 'hogan', 'baen', 'gibson', 'vinge', 'petrucci'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_20
  WTF: {'people', 'pay', 'innate'} {'heydt', 'cnn', 'vip'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_21
  WTF: {'pickup', '250'} {'irwin', 'mactools'}
topic_22
  WTF: {'intrinsics'} {'r3'}
topic_23
topic_24
  WTF: {'try', 'card'} {'sb', 'microsofts'}
topic_25
  WTF: {'people', 'spring', 'english'} {'pesach', 'ishtar', 'bede'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_26
  WTF: {'objects', 'charged'} {'kirlian', 'krillean'}
topic_27
topic_28
  WTF: {'mesur', 'solve', 'envoy', 'typeset', 'printing', 'wild', 'russian', 'famous'} {'armenia', 'persians', 'iosef', 'shirak', 'tyukhik', 'anania', 'armenian', 'orbeli'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_29
  WTF: {'immoral', 'pork', 'bases', 'abolished'} {'registries', 'c5s', 'admistration', 'c17'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_30
  WTF: {'pm', 'students', 'cs', 'andrew'} {'mellon', 'japan', 'carnegie', 'jstmp'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_31
  WTF: {'regards', 'stripped'} {'sehari', 'babak'}
topic_32
  WTF: {'aside'} {'darius'}
topic_33
  WTF: {'49er', 'mit', 'nick'} {'quincy', 'cambridge', 'sept'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_34
  WTF: {'theory'} {'alice'}
topic_35
  WTF: {'sodium', 'propellant', 'class'} {'tripoli', 'hpr', 'faa'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_36
  WTF: {'use', 'readers', 'send', 'advertisers'} {'cocacola', 'cola', 'tektronics', 'pepsi'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_37
  WTF: {'expound', 'usa', 'youll'} {'transarc', 'hoovers', 'lyle'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_38
  WTF: {'pipes'} {'mary'}
topic_39
  WTF: {'screen', 'trick', 'switcher'} {'robbinsgreat', 'supercharging', 'judd'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_40
  WTF: {'spring', 'dark', 'direction', 'holds', 'signature'} {'exussr', 'nicks', 'pitily', 'albert', 'hrivnak'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_41
  WTF: {'tradition', 'years'} {'olympia', 'joe'}
topic_42
  WTF: {'pads', 'addition', 'combo', 'version', 'stabilized'} {'t4', 'energiam', 't4centaur', 'russia', 'salyut'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_43
  WTF: {'audio', 'returned', 'problem'} {'emerson', 'hifi', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_44
  WTF: {'1163', 'microns', '980665'} {'inhalation', 'bridgend', '9g'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_45
  WTF: {'promote'} {'fenholt'}
topic_46
  WTF: {'cuz', 'outlived'} {'menuts', 'scotyy'}
topic_47
  WTF: {'2275753', '2042', 'lipmanoasysdtnavymil', 'pace', '2273618'} {'bethesda', 'lipman', 'navyrelated', 'siggraph', 'sigkids'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_48
  WTF: {'trinomials', '0n', 'tp', '644', 'mm', 'pw', 'mj', 'ma', 'm1', 'u0', 'mf', 'mh'} {'p6', 'm3', 'm9', 'lu', 'm0', 'm5', 'o3', 'm6', 'pnospsxop8f', 'mw', 'e8', 'mx'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_49
  WTF: {'90s', 'rebel', 'giveaway', 'rednecks', '8177', 'soar', 'racers'} {'smokey', 'pgh', 'yogis', 'yogi', 'thumper', 'mcqueen', 'bandit'}
  WTF?!?!? 7
  WTF?!?!? 7

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f4f430227c0>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f4fd47de700>}
{'perplexity': 51663.9609375, 'coherence_20': 1.7538754334672113, 'diversity_euclidean': 0.09534420890072394, 'diversity_jensenshannon': 0.7268087898009921, 'diversity_hellinger': 0.8563238130343586, 'diversity_cosine': 0.8354859019028562, 'fair_ppl_free': 2096.759521484375, 'fair_ppl_fix': 51151.390625, 'unfair_ppl_banklike': 51663.9609375}
{'num_topics': 51, 'num_common_words': 59415, 'num_model_words': 114951, 'num_bt_words': 97541, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 15, 'lost_bt': 1, 'lost_model': 14}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}]}
6
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
  WTF: {'vs'} {'nhl'}
topic_3
topic_4
  WTF: {'banks', 'candida', 'surrender'} {'hiv', 'n3jxp', 'gordon'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_5
topic_6
  WTF: {'discussion'} {'o157h7'}
topic_7
  WTF: {'ottoman', 'children', 'muslim', 'government', 'saw', 'started'} {'armenia', 'azerbaijan', 'armenians', 'sumgait', 'armenian', 'turks'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_8
  WTF: {'im'} {'bj200'}
topic_9
  WTF: {'ringleaders', 'CDROMCATZIP', 'strobe', 'Ferris', 'CSCSTD00385', 'NikeCajun', '8800CS', '5152940082', 'recollection', 'taxation', 'paradoxes', 'knowlege', '207556000', 'effortsall'} {'', 'whatta'}
  WTF?!?!? 14
topic_10
topic_11
  WTF: {'adventure', 'controller', '35'} {'snes', 'cdi', 'sega'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_12
  WTF: {'mail'} {'ripem'}
topic_13
topic_14
  WTF: {'drv'} {'soundbase'}
topic_15
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_16
topic_17
topic_18
  WTF: {'analytic', '02106chopinudeledu', 'vol', 'email', 'copyright', 'writing'} {'vernor', 'dune', 'baen', 'gibson', 'vinge', 'petrucci'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_19
topic_20
  WTF: {'pickup', '250'} {'irwin', 'mactools'}
topic_21
  WTF: {'scans', 'grayscales', 'market', 'buy', 'thanks', '400'} {'ocr', 'dexxa', 'mustek', 'scanman', 'paintbrush', 'ocr104zip'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_22
  WTF: {'suspiciously', 'arenas', 'active', 'ra', 'membership'} {'stafford', 'ama', 'guzzi', 'moa', 'bmwmoa'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_23
  WTF: {'pm', 'students', 'cs', 'andrew'} {'mellon', 'japan', 'carnegie', 'jstmp'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_24
  WTF: {'king'} {'alice'}
topic_25
topic_26
  WTF: {'manufacture'} {'patent'}
topic_27
topic_28
  WTF: {'ownthen'} {'femine'}
topic_29
  WTF: {'cute'} {'heydt'}
topic_30
  WTF: {'mesur', 'solve', 'envoy', 'typeset', 'printing', 'wild', 'russian', 'famous'} {'armenia', 'persians', 'iosef', 'shirak', 'tyukhik', 'anania', 'armenian', 'orbeli'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_31
  WTF: {'coil'} {'emi'}
topic_32
  WTF: {'regards', 'stripped'} {'sehari', 'babak'}
topic_33
  WTF: {'list', 'utter', 'jobs', 'military'} {'registries', 'admistration', 'irs', 'c17'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_34
  WTF: {'20', 'tooling', 'compsysamigagraphics'} {'ipas', '3do', 'v200'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_35
  WTF: {'49er', 'mit', 'nick'} {'quincy', 'cambridge', 'sept'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_36
  WTF: {'inhalation', 'microns', 'nostalgia'} {'edgetacalculator', 'bridgend', 'hexadecimals'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_37
  WTF: {'trinomials', '0n', 'coke', 'mm', 'pw', 'mj', 'ma', 'm1', 'u0', 'mf', 'fuselage', 'mh'} {'p6', 'm3', 'gh', 'm9', 'm0', 'm5', 'o3', 'm6', 'pnospsxop8f', 'mw', 'e8', 'mx'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_38
  WTF: {'dc', 'governmentmandated', 'balls'} {'shafer', 'dryden', 'cato'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_39
  WTF: {'devoid', 'contractors', 'chew'} {'mea', 'baghdad', 'bnr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_40
  WTF: {'2275753', 'pace', '2042', '2273618'} {'siggraph', 'bethesda', 'lipman', 'sigkids'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_41
  WTF: {'playoff', 'years'} {'olympia', 'joe'}
topic_42
  WTF: {'pads', 'addition', 'combo', 'version', 'stabilized'} {'t4', 'energiam', 't4centaur', 'russia', 'salyut'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_43
  WTF: {'fps', 'quadra'} {'qt', '3d0o'}
topic_44
  WTF: {'promote'} {'fenholt'}
topic_45
  WTF: {'audio', 'returned', 'problem'} {'emerson', 'hifi', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_46
  WTF: {'respondent', 'windscreen', 'yknow', 'cones'} {'tommy', 'canopies', 'punchline', 'mcwilliams'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_47
  WTF: {'publications', 'product', 'licensed', 'internet', 'science', 'promote', 'include'} {'marquette', 'regal', 'milwaukee', 'wi', 'robb', 'doublemajor', 'dubinski'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_48
  WTF: {'rc', 'pretend', 'exotic', 'pretends', 'elaborate', 'partial', 'terribly', 'chemists'} {'pepsicos', 'crah', 'cocacola', 'yerazunis', 'pepsi', 'rc4', 'rc2', 'cola'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_49
  WTF: {'v2305', 'numberoh', 'undergrad', 'bettereasier', 'zawodny', 'routers'} {'localtalk', 'phonenet', 'fallon', 'etherroutetcp', 'dastar', 'ncsa'}
  WTF?!?!? 6
  WTF?!?!? 6
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f4ffebfd610>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
  WTF: {'vs'} {'nhl'}
topic_3
topic_4
  WTF: {'banks', 'candida', 'surrender'} {'hiv', 'n3jxp', 'gordon'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_5
topic_6
  WTF: {'discussion'} {'o157h7'}
topic_7
  WTF: {'ottoman', 'children', 'muslim', 'government', 'saw', 'started'} {'armenia', 'azerbaijan', 'armenians', 'sumgait', 'armenian', 'turks'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_8
  WTF: {'im'} {'bj200'}
topic_9
  WTF: {'ringleaders', 'CDROMCATZIP', 'strobe', 'Ferris', 'CSCSTD00385', 'NikeCajun', '8800CS', '5152940082', 'recollection', 'taxation', 'paradoxes', 'knowlege', '207556000', 'effortsall'} {'', 'whatta'}
  WTF?!?!? 14
topic_10
topic_11
  WTF: {'adventure', 'controller', '35'} {'snes', 'cdi', 'sega'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_12
  WTF: {'mail'} {'ripem'}
topic_13
topic_14
  WTF: {'drv'} {'soundbase'}
topic_15
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_16
topic_17
topic_18
  WTF: {'analytic', '02106chopinudeledu', 'vol', 'email', 'copyright', 'writing'} {'vernor', 'dune', 'baen', 'gibson', 'vinge', 'petrucci'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_19
topic_20
  WTF: {'pickup', '250'} {'irwin', 'mactools'}
topic_21
  WTF: {'scans', 'grayscales', 'market', 'buy', 'thanks', '400'} {'ocr', 'dexxa', 'mustek', 'scanman', 'paintbrush', 'ocr104zip'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_22
  WTF: {'suspiciously', 'arenas', 'active', 'ra', 'membership'} {'stafford', 'ama', 'guzzi', 'moa', 'bmwmoa'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_23
  WTF: {'pm', 'students', 'cs', 'andrew'} {'mellon', 'japan', 'carnegie', 'jstmp'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_24
  WTF: {'king'} {'alice'}
topic_25
topic_26
  WTF: {'manufacture'} {'patent'}
topic_27
topic_28
  WTF: {'ownthen'} {'femine'}
topic_29
  WTF: {'cute'} {'heydt'}
topic_30
  WTF: {'mesur', 'solve', 'envoy', 'typeset', 'printing', 'wild', 'russian', 'famous'} {'armenia', 'persians', 'iosef', 'shirak', 'tyukhik', 'anania', 'armenian', 'orbeli'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_31
  WTF: {'coil'} {'emi'}
topic_32
  WTF: {'regards', 'stripped'} {'sehari', 'babak'}
topic_33
  WTF: {'list', 'utter', 'jobs', 'military'} {'registries', 'admistration', 'irs', 'c17'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_34
  WTF: {'20', 'tooling', 'compsysamigagraphics'} {'ipas', '3do', 'v200'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_35
  WTF: {'49er', 'mit', 'nick'} {'quincy', 'cambridge', 'sept'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_36
  WTF: {'inhalation', 'microns', 'nostalgia'} {'edgetacalculator', 'bridgend', 'hexadecimals'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_37
  WTF: {'trinomials', '0n', 'coke', 'mm', 'pw', 'mj', 'ma', 'm1', 'u0', 'mf', 'fuselage', 'mh'} {'p6', 'm3', 'gh', 'm9', 'm0', 'm5', 'o3', 'm6', 'pnospsxop8f', 'mw', 'e8', 'mx'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_38
  WTF: {'dc', 'governmentmandated', 'balls'} {'shafer', 'dryden', 'cato'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_39
  WTF: {'devoid', 'contractors', 'chew'} {'mea', 'baghdad', 'bnr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_40
  WTF: {'2275753', 'pace', '2042', '2273618'} {'siggraph', 'bethesda', 'lipman', 'sigkids'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_41
  WTF: {'playoff', 'years'} {'olympia', 'joe'}
topic_42
  WTF: {'pads', 'addition', 'combo', 'version', 'stabilized'} {'t4', 'energiam', 't4centaur', 'russia', 'salyut'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_43
  WTF: {'fps', 'quadra'} {'qt', '3d0o'}
topic_44
  WTF: {'promote'} {'fenholt'}
topic_45
  WTF: {'audio', 'returned', 'problem'} {'emerson', 'hifi', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_46
  WTF: {'respondent', 'windscreen', 'yknow', 'cones'} {'tommy', 'canopies', 'punchline', 'mcwilliams'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_47
  WTF: {'publications', 'product', 'licensed', 'internet', 'science', 'promote', 'include'} {'marquette', 'regal', 'milwaukee', 'wi', 'robb', 'doublemajor', 'dubinski'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_48
  WTF: {'rc', 'pretend', 'exotic', 'pretends', 'elaborate', 'partial', 'terribly', 'chemists'} {'pepsicos', 'crah', 'cocacola', 'yerazunis', 'pepsi', 'rc4', 'rc2', 'cola'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_49
  WTF: {'v2305', 'numberoh', 'undergrad', 'bettereasier', 'zawodny', 'routers'} {'localtalk', 'phonenet', 'fallon', 'etherroutetcp', 'dastar', 'ncsa'}
  WTF?!?!? 6
  WTF?!?!? 6

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f4fe87a0d90>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f4fe8732f10>}
{'perplexity': 57292.03515625, 'coherence_20': 1.7224061869993135, 'diversity_euclidean': 0.09264061628850896, 'diversity_jensenshannon': 0.7227921094622918, 'diversity_hellinger': 0.8515642424041431, 'diversity_cosine': 0.8355264844483896, 'fair_ppl_free': 2111.05419921875, 'fair_ppl_fix': 56563.12109375, 'unfair_ppl_banklike': 57292.03515625}
{'num_topics': 51, 'num_common_words': 59415, 'num_model_words': 114951, 'num_bt_words': 97541, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 16, 'lost_bt': 2, 'lost_model': 14}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}]}
7
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
topic_3
  WTF: {'vs'} {'nhl'}
topic_4
topic_5
topic_6
  WTF: {'candida', 'surrender', 'dont'} {'hiv', 'n3jxp', 'gordon'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_7
  WTF: {'land'} {'stephanopoulos'}
topic_8
  WTF: {'ottoman', 'children', 'muslim', 'government', 'saw', 'started'} {'armenia', 'azerbaijan', 'armenians', 'sumgait', 'armenian', 'turks'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_9
  WTF: {'like', 'sin'} {'caligiuri', 'enviroleague'}
topic_10
  WTF: {'CDROMCATZIP', 'strobe', 'CSCSTD00385', 'dragdrop', 'NikeCajun', '8800CS', '5152940082', 'recollection', 'taxation', 'knowlege', '1795', '207556000', 'toolbox', 'effortsall', 'JH2SC281XPM100187', 'L2PMABGZ7VAZV0PZRI'} {''}
  WTF?!?!? 16
topic_11
topic_12
  WTF: {'controller', 'uk'} {'cdi', 'sega'}
topic_13
  WTF: {'congress', 'working'} {'myers', 'stephanopoulos'}
topic_14
  WTF: {'new'} {'hotelco'}
topic_15
topic_16
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_17
  WTF: {'festival'} {'ishtar'}
topic_18
topic_19
  WTF: {'table'} {'alice'}
topic_20
  WTF: {'use', '250'} {'irwin', 'mactools'}
topic_21
  WTF: {'energy', 'balls'} {'shafer', 'dryden'}
topic_22
  WTF: {'university', 'equinox', 'hebrew', 'april', 'studies', 'dead', 'superior', 'orders', 'dawn', 'oriental', 'golden', 'metaphysical'} {'rosae', 'reuss', 'amorc', 'crowley', 'crucis', 'rosicrucian', 'qumran', 'oto', 'orientis', 'frater', 'templi', 'ordo'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_23
  WTF: {'intrinsics'} {'r3'}
topic_24
  WTF: {'analytic', '02106chopinudeledu', 'vol', 'copyright', 'manual', 'writing'} {'vernor', 'dune', 'hogan', 'baen', 'gibson', 'vinge'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_25
topic_26
topic_27
  WTF: {'able', 'focus', 'si', 'apple', 'socket'} {'marvins', 'spigot', 'etherlan', 'lciii', 'pds'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_28
topic_29
topic_30
  WTF: {'engineers', 'participants', 'tutorial', 'conference'} {'mellon', 'japan', 'carnegie', 'jstmp'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_31
  WTF: {'42839', '62000'} {'reids', 'heydt'}
topic_32
  WTF: {'regards', 'stripped'} {'sehari', 'babak'}
topic_33
  WTF: {'groundballs', 'studied', 'plays', 'goldglover', 'clutch', 'batted', 'player'} {'alomar', 'baergas', 'alomars', 'rni', 'dps', 'baerga', 'slg'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_34
  WTF: {'immoral', 'deficit', 'abolished'} {'registries', 'admistration', 'c17'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_35
  WTF: {'49er', 'mit', 'nick'} {'quincy', 'cambridge', 'sept'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_36
  WTF: {'netperson', 'equalize', 'capacitive', 'gourd'} {'behnkefnalffnalgov', 'pistrix', 'nat', 'behnke'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_37
  WTF: {'uuencode', 'ioccc'} {'eofnotok', 'xvoid'}
topic_38
  WTF: {'commercially'} {'emi'}
topic_39
  WTF: {'2020', 'sure', 'flyback'} {'emerson', 'hifi', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_40
topic_41
  WTF: {'CDROMCATZIP', 'Guideline', 'Uzi', 'dragdrop', 'recollection', 'taxation', '1795', 'knowlege', 'toolbox', 'monthly', 'effortsall', 'strobe', 'CSCSTD00385', 'NikeCajun', '8800CS', '5152940082', '207556000', 'JH2SC281XPM100187', 'L2PMABGZ7VAZV0PZRI'} {''}
  WTF?!?!? 19
topic_42
  WTF: {'melody', 'predictionsteam', 'fortyniner', 'roam', 'excavating', 'headin'} {'clementine', 'dykstra', 'dwelt', 'ballad', 'subterranean', 'anime'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_43
  WTF: {'patentable', 'patchmaking', 'remixed', 'vending'} {'cocacola', 'cola', 'yerazunis', 'pepsi'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_44
  WTF: {'trinomials', '0n', 'tp', '644', 'mm', 'pw', 'mj', 'ma', 'm1', 'u0', 'mf', 'mh'} {'p6', 'm3', 'm9', 'lu', 'm0', 'm5', 'pnospsxop8f', 'm6', 'o3', 'mw', 'e8', 'mx'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_45
  WTF: {'pads', 'addition', 'combo', 'version', 'stabilized'} {'t4', 'energiam', 't4centaur', 'russia', 'salyut'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_46
  WTF: {'promote'} {'fenholt'}
topic_47
  WTF: {'significant', 'wrongthe', 'csamiga', 'thank', 'look'} {'bitmovie', 'activa', 'r3d', 'v200', 'sergio'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_48
  WTF: {'drag'} {'mary'}
topic_49
  WTF: {'integer', 'commercial'} {'pcdos', 'macsyma'}
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f4fff2d3eb0>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
topic_3
  WTF: {'vs'} {'nhl'}
topic_4
topic_5
topic_6
  WTF: {'candida', 'surrender', 'dont'} {'hiv', 'n3jxp', 'gordon'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_7
  WTF: {'land'} {'stephanopoulos'}
topic_8
  WTF: {'ottoman', 'children', 'muslim', 'government', 'saw', 'started'} {'armenia', 'azerbaijan', 'armenians', 'sumgait', 'armenian', 'turks'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_9
  WTF: {'like', 'sin'} {'caligiuri', 'enviroleague'}
topic_10
  WTF: {'CDROMCATZIP', 'strobe', 'CSCSTD00385', 'dragdrop', 'NikeCajun', '8800CS', '5152940082', 'recollection', 'taxation', 'knowlege', '1795', '207556000', 'toolbox', 'effortsall', 'JH2SC281XPM100187', 'L2PMABGZ7VAZV0PZRI'} {''}
  WTF?!?!? 16
topic_11
topic_12
  WTF: {'controller', 'uk'} {'cdi', 'sega'}
topic_13
  WTF: {'congress', 'working'} {'myers', 'stephanopoulos'}
topic_14
  WTF: {'new'} {'hotelco'}
topic_15
topic_16
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_17
  WTF: {'festival'} {'ishtar'}
topic_18
topic_19
  WTF: {'table'} {'alice'}
topic_20
  WTF: {'use', '250'} {'irwin', 'mactools'}
topic_21
  WTF: {'energy', 'balls'} {'shafer', 'dryden'}
topic_22
  WTF: {'university', 'equinox', 'hebrew', 'april', 'studies', 'dead', 'superior', 'orders', 'dawn', 'oriental', 'golden', 'metaphysical'} {'rosae', 'reuss', 'amorc', 'crowley', 'crucis', 'rosicrucian', 'qumran', 'oto', 'orientis', 'frater', 'templi', 'ordo'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_23
  WTF: {'intrinsics'} {'r3'}
topic_24
  WTF: {'analytic', '02106chopinudeledu', 'vol', 'copyright', 'manual', 'writing'} {'vernor', 'dune', 'hogan', 'baen', 'gibson', 'vinge'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_25
topic_26
topic_27
  WTF: {'able', 'focus', 'si', 'apple', 'socket'} {'marvins', 'spigot', 'etherlan', 'lciii', 'pds'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_28
topic_29
topic_30
  WTF: {'engineers', 'participants', 'tutorial', 'conference'} {'mellon', 'japan', 'carnegie', 'jstmp'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_31
  WTF: {'42839', '62000'} {'reids', 'heydt'}
topic_32
  WTF: {'regards', 'stripped'} {'sehari', 'babak'}
topic_33
  WTF: {'groundballs', 'studied', 'plays', 'goldglover', 'clutch', 'batted', 'player'} {'alomar', 'baergas', 'alomars', 'rni', 'dps', 'baerga', 'slg'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_34
  WTF: {'immoral', 'deficit', 'abolished'} {'registries', 'admistration', 'c17'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_35
  WTF: {'49er', 'mit', 'nick'} {'quincy', 'cambridge', 'sept'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_36
  WTF: {'netperson', 'equalize', 'capacitive', 'gourd'} {'behnkefnalffnalgov', 'pistrix', 'nat', 'behnke'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_37
  WTF: {'uuencode', 'ioccc'} {'eofnotok', 'xvoid'}
topic_38
  WTF: {'commercially'} {'emi'}
topic_39
  WTF: {'2020', 'sure', 'flyback'} {'emerson', 'hifi', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_40
topic_41
  WTF: {'CDROMCATZIP', 'Guideline', 'Uzi', 'dragdrop', 'recollection', 'taxation', '1795', 'knowlege', 'toolbox', 'monthly', 'effortsall', 'strobe', 'CSCSTD00385', 'NikeCajun', '8800CS', '5152940082', '207556000', 'JH2SC281XPM100187', 'L2PMABGZ7VAZV0PZRI'} {''}
  WTF?!?!? 19
topic_42
  WTF: {'melody', 'predictionsteam', 'fortyniner', 'roam', 'excavating', 'headin'} {'clementine', 'dykstra', 'dwelt', 'ballad', 'subterranean', 'anime'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_43
  WTF: {'patentable', 'patchmaking', 'remixed', 'vending'} {'cocacola', 'cola', 'yerazunis', 'pepsi'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_44
  WTF: {'trinomials', '0n', 'tp', '644', 'mm', 'pw', 'mj', 'ma', 'm1', 'u0', 'mf', 'mh'} {'p6', 'm3', 'm9', 'lu', 'm0', 'm5', 'pnospsxop8f', 'm6', 'o3', 'mw', 'e8', 'mx'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_45
  WTF: {'pads', 'addition', 'combo', 'version', 'stabilized'} {'t4', 'energiam', 't4centaur', 'russia', 'salyut'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_46
  WTF: {'promote'} {'fenholt'}
topic_47
  WTF: {'significant', 'wrongthe', 'csamiga', 'thank', 'look'} {'bitmovie', 'activa', 'r3d', 'v200', 'sergio'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_48
  WTF: {'drag'} {'mary'}
topic_49
  WTF: {'integer', 'commercial'} {'pcdos', 'macsyma'}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f4fe8938bb0>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f4f430227c0>}
{'perplexity': 51270.2578125, 'coherence_20': 1.6213158918525448, 'diversity_euclidean': 0.09484945966341937, 'diversity_jensenshannon': 0.7121655335627051, 'diversity_hellinger': 0.8375723750335893, 'diversity_cosine': 0.8159470069278887, 'fair_ppl_free': 2058.568603515625, 'fair_ppl_fix': 50560.4375, 'unfair_ppl_banklike': 51270.2578125}
{'num_topics': 51, 'num_common_words': 59415, 'num_model_words': 114951, 'num_bt_words': 97541, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 17, 'lost_bt': 1, 'lost_model': 16}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 20, 'lost_bt': 1, 'lost_model': 19}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}]}
8
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
  WTF: {'vs'} {'nhl'}
topic_3
topic_4
  WTF: {'just'} {'nsa'}
topic_5
topic_6
  WTF: {'candida', 'surrender', 'dont'} {'hiv', 'n3jxp', 'gordon'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_7
topic_8
topic_9
  WTF: {'ps'} {'bj200'}
topic_10
  WTF: {'ottoman', 'children', 'muslim', 'government', 'saw', 'started'} {'armenia', 'azerbaijan', 'armenians', 'sumgait', 'armenian', 'turks'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_11
  WTF: {'just', 'like'} {'caligiuri', 'enviroleague'}
topic_12
  WTF: {'CDROMCATZIP', 'ringleaders', 'CSCSTD00385', 'dragdrop', 'NikeCajun', '8800CS', '5152940082', 'taxation', 'Epilepsy', 'knowlege', '1795', '207556000', 'toolbox', 'effortsall', 'L2PMABGZ7VAZV0PZRI'} {''}
  WTF?!?!? 15
topic_13
  WTF: {'usenet', 'posting'} {'rsa', 'ripem'}
topic_14
  WTF: {'transferable'} {'hotelco'}
topic_15
topic_16
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_17
  WTF: {'general', 'jgfootminervacisyaleedu', 'plasktbdemoncouk', 'testtaking'} {'ets', 'boulder', 'gre', 'rex'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_18
topic_19
  WTF: {'analytic', '02106chopinudeledu', 'vol', 'copyright', 'manual', 'writing'} {'vernor', 'dune', 'baen', 'gibson', 'vinge', 'petrucci'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_20
  WTF: {'tons', 'warhead'} {'shafer', 'dryden'}
topic_21
  WTF: {'levels', 'sophisticated', 'statistical', 'management', 'tools'} {'wingert', 'sei', 'challenger', 'bret', 'thiokol'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_22
  WTF: {'server'} {'r3'}
topic_23
  WTF: {'queer', 'books', 'rose', 'wilt', 'interested', 'magic', 'degrees', 'organization', 'spinoffs', 'love', 'groups', 'bookstore', 'study'} {'rosae', 'amorc', 'crucis', 'san', 'rosicrucian', 'templars', 'kent', 'jose', 'orc', 'oto', 'orientis', 'templi', 'ordo'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_24
  WTF: {'computer'} {'alice'}
topic_25
topic_26
  WTF: {'stuff', 'smears'} {'glaze', 'meguiars'}
topic_27
  WTF: {'bring', 'coradeschi', 'nows', 'holdings', 'tcorapicaarmymil', 'proxy', 'hover', 'blazes', 'theyre', 'exactly', 'ambassadors'} {'saf', 'bvhis', 'matson', 'bvbidder', 'ccrtkba', 'maginot', 'bvi', 'biscayne', 'goa', 'cnn', 'cnnyuppietv'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_28
  WTF: {'people', 'english'} {'ishtar', 'bede'}
topic_29
  WTF: {'mesur', 'solve', 'envoy', 'typeset', 'printing', 'wild', 'russian', 'famous'} {'armenia', 'persians', 'iosef', 'shirak', 'tyukhik', 'anania', 'armenian', 'orbeli'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_30
  WTF: {'aside'} {'darius'}
topic_31
topic_32
  WTF: {'type', 'dim'} {'emi', 'hv'}
topic_33
  WTF: {'doityourselfers', 'know'} {'kirlian', 'krillean'}
topic_34
  WTF: {'requisition', 'nebulised', 'eabu288140493210752dialin33635slipntsuciedu', 'smth', 'eabu288orionoacuciedu', 'petesmtldemoncouk'} {'0656652166', 'hundredths', 'militioners', 'pitily', 'bridgend', 'nottoodistant'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_35
  WTF: {'regards', 'stripped'} {'sehari', 'babak'}
topic_36
  WTF: {'49er', 'mit', 'nick'} {'quincy', 'cambridge', 'sept'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_37
  WTF: {'list', 'utter', 'jobs', 'military'} {'registries', 'admistration', 'irs', 'c17'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_38
  WTF: {'directors', 'folks', 'rode', 'articles'} {'ama', 'moa', 'bmwmoa', 'mc'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_39
  WTF: {'engineers', 'participants', 'tutorial', 'conference'} {'mellon', 'japan', 'carnegie', 'jstmp'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_40
  WTF: {'april'} {'hicnet'}
topic_41
  WTF: {'george'} {'robbie'}
topic_42
  WTF: {'sending', 'green'} {'null', 'ncsa'}
topic_43
topic_44
  WTF: {'ground', 'powers', 'glass'} {'emerson', 'hifi', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_45
topic_46
  WTF: {'promote'} {'fenholt'}
topic_47
  WTF: {'trinomials', '0n', 'tp', '644', 'mm', 'pw', 'mj', 'ma', 'm1', 'u0', 'mf', 'mh'} {'p6', 'm3', 'm9', 'lu', 'm0', 'm5', 'o3', 'm6', 'pnospsxop8f', 'mw', 'e8', 'mx'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_48
  WTF: {'combination', 'thoughts'} {'megatek', 'neto'}
topic_49
  WTF: {'upgrade'} {'ses'}
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f4ff13c0a30>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
  WTF: {'vs'} {'nhl'}
topic_3
topic_4
  WTF: {'just'} {'nsa'}
topic_5
topic_6
  WTF: {'candida', 'surrender', 'dont'} {'hiv', 'n3jxp', 'gordon'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_7
topic_8
topic_9
  WTF: {'ps'} {'bj200'}
topic_10
  WTF: {'ottoman', 'children', 'muslim', 'government', 'saw', 'started'} {'armenia', 'azerbaijan', 'armenians', 'sumgait', 'armenian', 'turks'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_11
  WTF: {'just', 'like'} {'caligiuri', 'enviroleague'}
topic_12
  WTF: {'CDROMCATZIP', 'ringleaders', 'CSCSTD00385', 'dragdrop', 'NikeCajun', '8800CS', '5152940082', 'taxation', 'Epilepsy', 'knowlege', '1795', '207556000', 'toolbox', 'effortsall', 'L2PMABGZ7VAZV0PZRI'} {''}
  WTF?!?!? 15
topic_13
  WTF: {'usenet', 'posting'} {'rsa', 'ripem'}
topic_14
  WTF: {'transferable'} {'hotelco'}
topic_15
topic_16
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_17
  WTF: {'general', 'jgfootminervacisyaleedu', 'plasktbdemoncouk', 'testtaking'} {'ets', 'boulder', 'gre', 'rex'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_18
topic_19
  WTF: {'analytic', '02106chopinudeledu', 'vol', 'copyright', 'manual', 'writing'} {'vernor', 'dune', 'baen', 'gibson', 'vinge', 'petrucci'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_20
  WTF: {'tons', 'warhead'} {'shafer', 'dryden'}
topic_21
  WTF: {'levels', 'sophisticated', 'statistical', 'management', 'tools'} {'wingert', 'sei', 'challenger', 'bret', 'thiokol'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_22
  WTF: {'server'} {'r3'}
topic_23
  WTF: {'queer', 'books', 'rose', 'wilt', 'interested', 'magic', 'degrees', 'organization', 'spinoffs', 'love', 'groups', 'bookstore', 'study'} {'rosae', 'amorc', 'crucis', 'san', 'rosicrucian', 'templars', 'kent', 'jose', 'orc', 'oto', 'orientis', 'templi', 'ordo'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_24
  WTF: {'computer'} {'alice'}
topic_25
topic_26
  WTF: {'stuff', 'smears'} {'glaze', 'meguiars'}
topic_27
  WTF: {'bring', 'coradeschi', 'nows', 'holdings', 'tcorapicaarmymil', 'proxy', 'hover', 'blazes', 'theyre', 'exactly', 'ambassadors'} {'saf', 'bvhis', 'matson', 'bvbidder', 'ccrtkba', 'maginot', 'bvi', 'biscayne', 'goa', 'cnn', 'cnnyuppietv'}
  WTF?!?!? 11
  WTF?!?!? 11
topic_28
  WTF: {'people', 'english'} {'ishtar', 'bede'}
topic_29
  WTF: {'mesur', 'solve', 'envoy', 'typeset', 'printing', 'wild', 'russian', 'famous'} {'armenia', 'persians', 'iosef', 'shirak', 'tyukhik', 'anania', 'armenian', 'orbeli'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_30
  WTF: {'aside'} {'darius'}
topic_31
topic_32
  WTF: {'type', 'dim'} {'emi', 'hv'}
topic_33
  WTF: {'doityourselfers', 'know'} {'kirlian', 'krillean'}
topic_34
  WTF: {'requisition', 'nebulised', 'eabu288140493210752dialin33635slipntsuciedu', 'smth', 'eabu288orionoacuciedu', 'petesmtldemoncouk'} {'0656652166', 'hundredths', 'militioners', 'pitily', 'bridgend', 'nottoodistant'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_35
  WTF: {'regards', 'stripped'} {'sehari', 'babak'}
topic_36
  WTF: {'49er', 'mit', 'nick'} {'quincy', 'cambridge', 'sept'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_37
  WTF: {'list', 'utter', 'jobs', 'military'} {'registries', 'admistration', 'irs', 'c17'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_38
  WTF: {'directors', 'folks', 'rode', 'articles'} {'ama', 'moa', 'bmwmoa', 'mc'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_39
  WTF: {'engineers', 'participants', 'tutorial', 'conference'} {'mellon', 'japan', 'carnegie', 'jstmp'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_40
  WTF: {'april'} {'hicnet'}
topic_41
  WTF: {'george'} {'robbie'}
topic_42
  WTF: {'sending', 'green'} {'null', 'ncsa'}
topic_43
topic_44
  WTF: {'ground', 'powers', 'glass'} {'emerson', 'hifi', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_45
topic_46
  WTF: {'promote'} {'fenholt'}
topic_47
  WTF: {'trinomials', '0n', 'tp', '644', 'mm', 'pw', 'mj', 'ma', 'm1', 'u0', 'mf', 'mh'} {'p6', 'm3', 'm9', 'lu', 'm0', 'm5', 'o3', 'm6', 'pnospsxop8f', 'mw', 'e8', 'mx'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_48
  WTF: {'combination', 'thoughts'} {'megatek', 'neto'}
topic_49
  WTF: {'upgrade'} {'ses'}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f50285aeb80>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f4ff13c5c10>}
{'perplexity': 51142.125, 'coherence_20': 1.6471898501381064, 'diversity_euclidean': 0.09654208390918931, 'diversity_jensenshannon': 0.716876862785511, 'diversity_hellinger': 0.8434262654294556, 'diversity_cosine': 0.8202347025301884, 'fair_ppl_free': 2069.332763671875, 'fair_ppl_fix': 50428.0625, 'unfair_ppl_banklike': 51142.125}
{'num_topics': 51, 'num_common_words': 59415, 'num_model_words': 114951, 'num_bt_words': 97541, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 16, 'lost_bt': 1, 'lost_model': 15}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 22, 'lost_bt': 11, 'lost_model': 11}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}]}
9
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
  WTF: {'vs'} {'nhl'}
topic_3
topic_4
  WTF: {'law', 'know'} {'stephanopoulos', 'nsa'}
topic_5
  WTF: {'banks', 'candida', 'surrender'} {'hiv', 'n3jxp', 'gordon'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_6
topic_7
topic_8
  WTF: {'discussion', 'news'} {'o157h7', 'anania'}
topic_9
  WTF: {'ottoman', 'children', 'muslim', 'government', 'saw', 'started'} {'armenia', 'azerbaijan', 'armenians', 'sumgait', 'armenian', 'turks'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_10
  WTF: {'driver'} {'bj200'}
topic_11
  WTF: {'influenza'} {'enviroleague'}
topic_12
  WTF: {'NikeDeacon', 'CDROMCATZIP', '8800CS', 'CSCSTD00385', 'dragdrop', 'NikeCajun', '5152940082', 'recollection', 'taxation', '1795', '207556000', 'toolbox', 'effortsall', 'L2PMABGZ7VAZV0PZRI'} {''}
  WTF?!?!? 14
topic_13
topic_14
  WTF: {'agent', 'case', 'jury', 'testimony', 'evidence', 'texas'} {'cooper', 'harris', 'idaho', 'spence', 'atlantic', 'degan'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_15
  WTF: {'near', 'nick', 'parking'} {'cambridge', 'sept', 'aug'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_16
topic_17
topic_18
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_19
topic_20
  WTF: {'chemicals', 'make'} {'shafer', 'dryden'}
topic_21
  WTF: {'analytic', '02106chopinudeledu', 'vol', 'copyright', 'explanations', 'writing'} {'vernor', 'baen', 'gre', 'gibson', 'vinge', 'petrucci'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_22
  WTF: {'intrinsics'} {'r3'}
topic_23
  WTF: {'heh', 'protection'} {'emerson', 'vcr'}
topic_24
  WTF: {'handheld', 'scans', 'market', 'buy', '400'} {'ocr', 'mustek', 'scanman', 'paintbrush', 'ocr104zip'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_25
  WTF: {'directors', 'folks', 'articles', 'dod'} {'ama', 'yogi', 'moa', 'bmwmoa'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_26
  WTF: {'try', 'card'} {'sb', 'microsofts'}
topic_27
  WTF: {'objects', 'charged'} {'kirlian', 'krillean'}
topic_28
topic_29
topic_30
  WTF: {'mail'} {'vip'}
topic_31
  WTF: {'regards', 'stripped'} {'sehari', 'babak'}
topic_32
  WTF: {'aside'} {'darius'}
topic_33
  WTF: {'gimic', 'unpatentable', 'backand', 'patentable', 'remixed'} {'crah', 'cocacola', 'yerazunis', 'pepsi', 'cola'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_34
  WTF: {'jobs', 'utter', 'commission'} {'registries', 'admistration', 'irs'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_35
  WTF: {'forget', 'rule', 'computer'} {'alice', 'douglas', 'adams'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_36
topic_37
  WTF: {'computational', 'fax', 'navy'} {'siggraph', 'bethesda', 'sigkids'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_38
  WTF: {'participants', 'tuesday', 'mall'} {'quincy', 'kenai', 'amc'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_39
  WTF: {'tradition', 'years'} {'olympia', 'joe'}
topic_40
  WTF: {'pads', 'addition', 'combo', 'version', 'stabilized'} {'t4', 'energiam', 't4centaur', 'russia', 'salyut'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_41
  WTF: {'flight', 'purchase', 'popular'} {'tripoli', 'hpr', 'faa'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_42
  WTF: {'minded'} {'robbie'}
topic_43
  WTF: {'heinous', 'discussion', 'stalled'} {'transarc', 'hoovers', 'lyle'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_44
  WTF: {'promote'} {'fenholt'}
topic_45
  WTF: {'trinomials', '0n', 'tp', '644', 'mm', 'pw', 'mj', 'ma', 'm1', 'u0', 'mf', 'mh'} {'p6', 'm3', 'm9', 'lu', 'm0', 'm5', 'o3', 'm6', 'pnospsxop8f', 'mw', 'e8', 'mx'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_46
  WTF: {'publications', 'product', 'licensed', 'internet', 'science', 'promote', 'include'} {'marquette', 'regal', 'milwaukee', 'wi', 'robb', 'doublemajor', 'dubinski'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_47
  WTF: {'mr', 'oddly', 'nazism', 'ya', 'utilize', 'inherent', 'der', 'dem'} {'timucin', 'davidsson', 'yo', 'turc', 'hoffnung', 'koph', 'zeuge', 'davidssons'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_48
topic_49
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f4fe86ca9a0>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
  WTF: {'vs'} {'nhl'}
topic_3
topic_4
  WTF: {'law', 'know'} {'stephanopoulos', 'nsa'}
topic_5
  WTF: {'banks', 'candida', 'surrender'} {'hiv', 'n3jxp', 'gordon'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_6
topic_7
topic_8
  WTF: {'discussion', 'news'} {'o157h7', 'anania'}
topic_9
  WTF: {'ottoman', 'children', 'muslim', 'government', 'saw', 'started'} {'armenia', 'azerbaijan', 'armenians', 'sumgait', 'armenian', 'turks'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_10
  WTF: {'driver'} {'bj200'}
topic_11
  WTF: {'influenza'} {'enviroleague'}
topic_12
  WTF: {'NikeDeacon', 'CDROMCATZIP', '8800CS', 'CSCSTD00385', 'dragdrop', 'NikeCajun', '5152940082', 'recollection', 'taxation', '1795', '207556000', 'toolbox', 'effortsall', 'L2PMABGZ7VAZV0PZRI'} {''}
  WTF?!?!? 14
topic_13
topic_14
  WTF: {'agent', 'case', 'jury', 'testimony', 'evidence', 'texas'} {'cooper', 'harris', 'idaho', 'spence', 'atlantic', 'degan'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_15
  WTF: {'near', 'nick', 'parking'} {'cambridge', 'sept', 'aug'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_16
topic_17
topic_18
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_19
topic_20
  WTF: {'chemicals', 'make'} {'shafer', 'dryden'}
topic_21
  WTF: {'analytic', '02106chopinudeledu', 'vol', 'copyright', 'explanations', 'writing'} {'vernor', 'baen', 'gre', 'gibson', 'vinge', 'petrucci'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_22
  WTF: {'intrinsics'} {'r3'}
topic_23
  WTF: {'heh', 'protection'} {'emerson', 'vcr'}
topic_24
  WTF: {'handheld', 'scans', 'market', 'buy', '400'} {'ocr', 'mustek', 'scanman', 'paintbrush', 'ocr104zip'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_25
  WTF: {'directors', 'folks', 'articles', 'dod'} {'ama', 'yogi', 'moa', 'bmwmoa'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_26
  WTF: {'try', 'card'} {'sb', 'microsofts'}
topic_27
  WTF: {'objects', 'charged'} {'kirlian', 'krillean'}
topic_28
topic_29
topic_30
  WTF: {'mail'} {'vip'}
topic_31
  WTF: {'regards', 'stripped'} {'sehari', 'babak'}
topic_32
  WTF: {'aside'} {'darius'}
topic_33
  WTF: {'gimic', 'unpatentable', 'backand', 'patentable', 'remixed'} {'crah', 'cocacola', 'yerazunis', 'pepsi', 'cola'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_34
  WTF: {'jobs', 'utter', 'commission'} {'registries', 'admistration', 'irs'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_35
  WTF: {'forget', 'rule', 'computer'} {'alice', 'douglas', 'adams'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_36
topic_37
  WTF: {'computational', 'fax', 'navy'} {'siggraph', 'bethesda', 'sigkids'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_38
  WTF: {'participants', 'tuesday', 'mall'} {'quincy', 'kenai', 'amc'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_39
  WTF: {'tradition', 'years'} {'olympia', 'joe'}
topic_40
  WTF: {'pads', 'addition', 'combo', 'version', 'stabilized'} {'t4', 'energiam', 't4centaur', 'russia', 'salyut'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_41
  WTF: {'flight', 'purchase', 'popular'} {'tripoli', 'hpr', 'faa'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_42
  WTF: {'minded'} {'robbie'}
topic_43
  WTF: {'heinous', 'discussion', 'stalled'} {'transarc', 'hoovers', 'lyle'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_44
  WTF: {'promote'} {'fenholt'}
topic_45
  WTF: {'trinomials', '0n', 'tp', '644', 'mm', 'pw', 'mj', 'ma', 'm1', 'u0', 'mf', 'mh'} {'p6', 'm3', 'm9', 'lu', 'm0', 'm5', 'o3', 'm6', 'pnospsxop8f', 'mw', 'e8', 'mx'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_46
  WTF: {'publications', 'product', 'licensed', 'internet', 'science', 'promote', 'include'} {'marquette', 'regal', 'milwaukee', 'wi', 'robb', 'doublemajor', 'dubinski'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_47
  WTF: {'mr', 'oddly', 'nazism', 'ya', 'utilize', 'inherent', 'der', 'dem'} {'timucin', 'davidsson', 'yo', 'turc', 'hoffnung', 'koph', 'zeuge', 'davidssons'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_48
topic_49

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f4fe611b100>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f4fe611af10>}
{'perplexity': 51008.06640625, 'coherence_20': 1.7985938912044237, 'diversity_euclidean': 0.08817682824023859, 'diversity_jensenshannon': 0.7077957676050765, 'diversity_hellinger': 0.8327032752341657, 'diversity_cosine': 0.8155932510572522, 'fair_ppl_free': 2070.12890625, 'fair_ppl_fix': 50525.12890625, 'unfair_ppl_banklike': 51008.06640625}
{'num_topics': 51, 'num_common_words': 59415, 'num_model_words': 114951, 'num_bt_words': 97541, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 15, 'lost_bt': 1, 'lost_model': 14}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}]}
10
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
topic_3
  WTF: {'vs'} {'nhl'}
topic_4
  WTF: {'just'} {'nsa'}
topic_5
  WTF: {'research', 'banks', 'dont'} {'hiv', 'n3jxp', 'gordon'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_6
topic_7
topic_8
  WTF: {'land'} {'stephanopoulos'}
topic_9
  WTF: {'work', 'package', 'children'} {'fbi', 'myers', 'stephanopoulos'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_10
  WTF: {'news'} {'o157h7'}
topic_11
  WTF: {'ottoman', 'children', 'muslim', 'government', 'saw', 'started'} {'armenia', 'azerbaijan', 'armenians', 'sumgait', 'armenian', 'turks'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_12
  WTF: {'driver'} {'bj200'}
topic_13
  WTF: {'just', 'partners'} {'caligiuri', 'enviroleague'}
topic_14
  WTF: {'CDROMCATZIP', 'Guideline', 'CSCSTD00385', 'dragdrop', 'NikeCajun', '8800CS', '5152940082', 'recollection', 'taxation', 'divvied', '1795', '207556000', 'toolbox', 'effortsall', 'L2PMABGZ7VAZV0PZRI'} {''}
  WTF?!?!? 15
topic_15
topic_16
  WTF: {'interested', 'email'} {'snes', 'sega'}
topic_17
  WTF: {'posting', 'email'} {'rsa', 'ripem'}
topic_18
topic_19
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_20
topic_21
topic_22
  WTF: {'analytic', '02106chopinudeledu', 'vol', 'email', 'copyright', 'writing'} {'vernor', 'hogan', 'baen', 'gibson', 'vinge', 'petrucci'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_23
  WTF: {'university', 'equinox', 'hebrew', 'april', 'studies', 'superior', 'orders', 'dawn', 'congress', 'oriental', 'golden', 'metaphysical'} {'rosae', 'reuss', 'amorc', 'crowley', 'crucis', 'rosicrucian', 'qumran', 'oto', 'orientis', 'frater', 'templi', 'ordo'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_24
  WTF: {'trillion'} {'alice'}
topic_25
  WTF: {'intrinsics'} {'r3'}
topic_26
  WTF: {'handheld', 'scans', 'grayscales', 'market', 'buy', '400'} {'ocr', 'dexxa', 'mustek', 'scanman', 'paintbrush', 'ocr104zip'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_27
topic_28
  WTF: {'programming', 'cs', 'students', 'andrew'} {'mellon', 'japan', 'carnegie', 'jstmp'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_29
  WTF: {'mesur', 'solve', 'envoy', 'typeset', 'printing', 'wild', 'russian', 'famous'} {'armenia', 'persians', 'iosef', 'shirak', 'tyukhik', 'anania', 'armenian', 'orbeli'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_30
  WTF: {'people', 'spring', 'english'} {'pesach', 'ishtar', 'bede'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_31
topic_32
  WTF: {'regards', 'stripped'} {'sehari', 'babak'}
topic_33
  WTF: {'aside'} {'darius'}
topic_34
  WTF: {'objects', 'charged'} {'kirlian', 'krillean'}
topic_35
  WTF: {'immoral', 'pork', 'bases', 'abolished'} {'registries', 'c5s', 'admistration', 'c17'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_36
topic_37
  WTF: {'teh'} {'mary'}
topic_38
  WTF: {'lowvoltage'} {'emi'}
topic_39
  WTF: {'CDROMCATZIP', 'Guideline', 'Uzi', 'dragdrop', 'recollection', 'taxation', '1795', 'knowlege', 'toolbox', 'monthly', 'effortsall', 'strobe', 'CSCSTD00385', 'NikeCajun', '8800CS', '5152940082', '207556000', 'JH2SC281XPM100187', 'L2PMABGZ7VAZV0PZRI'} {''}
  WTF?!?!? 19
topic_40
  WTF: {'gui', 'downloaded', 'environments', 'need'} {'evets', 'bonn', 'rewerb', 'brewer'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_41
  WTF: {'uuencode', 'ioccc'} {'eofnotok', 'xvoid'}
topic_42
  WTF: {'pads', 'addition', 'combo', 'version', 'stabilized'} {'t4', 'energiam', 't4centaur', 'russia', 'salyut'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_43
  WTF: {'played'} {'fenholt'}
topic_44
  WTF: {'trinomials', '0n', 'tp', '644', 'mm', 'pw', 'mj', 'ma', 'm1', 'u0', 'mf', 'mh'} {'p6', 'm3', 'm9', 'lu', 'm0', 'm5', 'pnospsxop8f', 'm6', 'o3', 'mw', 'e8', 'mx'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_45
  WTF: {'audio', 'returned', 'problem'} {'emerson', 'hifi', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_46
  WTF: {'300', 'bullshitting', 'licensees', 'csamiga'} {'r3d', '3do', 'pong', 'sergio'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_47
  WTF: {'memorable', 'trench', 'lyrics', 'changing', 'hes', 'dont'} {'dykstra', 'homesick', 'yankess', 'ballad', 'subterranean', 'anime'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_48
  WTF: {'erasure', 'products', 'surethats', 'reprogramming', 'types', 'hobbyist', 'preproduction'} {'neuronr', 'mc143150', 'snvt', 'mc143120', 'hc705k1', 'motorolas', 'hc711'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_49
  WTF: {'salvage', 'mosques', 'cozy', 'doublespeak', 'rules', 'essays', 'punishments', 'exemption'} {'commandeer', 'israelists', 'hymies', 'harikari', 'barfling', 'followingup', 'kkkaldis', 'ragheads'}
  WTF?!?!? 8
  WTF?!?!? 8
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f4fe86e36a0>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
topic_3
  WTF: {'vs'} {'nhl'}
topic_4
  WTF: {'just'} {'nsa'}
topic_5
  WTF: {'research', 'banks', 'dont'} {'hiv', 'n3jxp', 'gordon'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_6
topic_7
topic_8
  WTF: {'land'} {'stephanopoulos'}
topic_9
  WTF: {'work', 'package', 'children'} {'fbi', 'myers', 'stephanopoulos'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_10
  WTF: {'news'} {'o157h7'}
topic_11
  WTF: {'ottoman', 'children', 'muslim', 'government', 'saw', 'started'} {'armenia', 'azerbaijan', 'armenians', 'sumgait', 'armenian', 'turks'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_12
  WTF: {'driver'} {'bj200'}
topic_13
  WTF: {'just', 'partners'} {'caligiuri', 'enviroleague'}
topic_14
  WTF: {'CDROMCATZIP', 'Guideline', 'CSCSTD00385', 'dragdrop', 'NikeCajun', '8800CS', '5152940082', 'recollection', 'taxation', 'divvied', '1795', '207556000', 'toolbox', 'effortsall', 'L2PMABGZ7VAZV0PZRI'} {''}
  WTF?!?!? 15
topic_15
topic_16
  WTF: {'interested', 'email'} {'snes', 'sega'}
topic_17
  WTF: {'posting', 'email'} {'rsa', 'ripem'}
topic_18
topic_19
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_20
topic_21
topic_22
  WTF: {'analytic', '02106chopinudeledu', 'vol', 'email', 'copyright', 'writing'} {'vernor', 'hogan', 'baen', 'gibson', 'vinge', 'petrucci'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_23
  WTF: {'university', 'equinox', 'hebrew', 'april', 'studies', 'superior', 'orders', 'dawn', 'congress', 'oriental', 'golden', 'metaphysical'} {'rosae', 'reuss', 'amorc', 'crowley', 'crucis', 'rosicrucian', 'qumran', 'oto', 'orientis', 'frater', 'templi', 'ordo'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_24
  WTF: {'trillion'} {'alice'}
topic_25
  WTF: {'intrinsics'} {'r3'}
topic_26
  WTF: {'handheld', 'scans', 'grayscales', 'market', 'buy', '400'} {'ocr', 'dexxa', 'mustek', 'scanman', 'paintbrush', 'ocr104zip'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_27
topic_28
  WTF: {'programming', 'cs', 'students', 'andrew'} {'mellon', 'japan', 'carnegie', 'jstmp'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_29
  WTF: {'mesur', 'solve', 'envoy', 'typeset', 'printing', 'wild', 'russian', 'famous'} {'armenia', 'persians', 'iosef', 'shirak', 'tyukhik', 'anania', 'armenian', 'orbeli'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_30
  WTF: {'people', 'spring', 'english'} {'pesach', 'ishtar', 'bede'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_31
topic_32
  WTF: {'regards', 'stripped'} {'sehari', 'babak'}
topic_33
  WTF: {'aside'} {'darius'}
topic_34
  WTF: {'objects', 'charged'} {'kirlian', 'krillean'}
topic_35
  WTF: {'immoral', 'pork', 'bases', 'abolished'} {'registries', 'c5s', 'admistration', 'c17'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_36
topic_37
  WTF: {'teh'} {'mary'}
topic_38
  WTF: {'lowvoltage'} {'emi'}
topic_39
  WTF: {'CDROMCATZIP', 'Guideline', 'Uzi', 'dragdrop', 'recollection', 'taxation', '1795', 'knowlege', 'toolbox', 'monthly', 'effortsall', 'strobe', 'CSCSTD00385', 'NikeCajun', '8800CS', '5152940082', '207556000', 'JH2SC281XPM100187', 'L2PMABGZ7VAZV0PZRI'} {''}
  WTF?!?!? 19
topic_40
  WTF: {'gui', 'downloaded', 'environments', 'need'} {'evets', 'bonn', 'rewerb', 'brewer'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_41
  WTF: {'uuencode', 'ioccc'} {'eofnotok', 'xvoid'}
topic_42
  WTF: {'pads', 'addition', 'combo', 'version', 'stabilized'} {'t4', 'energiam', 't4centaur', 'russia', 'salyut'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_43
  WTF: {'played'} {'fenholt'}
topic_44
  WTF: {'trinomials', '0n', 'tp', '644', 'mm', 'pw', 'mj', 'ma', 'm1', 'u0', 'mf', 'mh'} {'p6', 'm3', 'm9', 'lu', 'm0', 'm5', 'pnospsxop8f', 'm6', 'o3', 'mw', 'e8', 'mx'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_45
  WTF: {'audio', 'returned', 'problem'} {'emerson', 'hifi', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_46
  WTF: {'300', 'bullshitting', 'licensees', 'csamiga'} {'r3d', '3do', 'pong', 'sergio'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_47
  WTF: {'memorable', 'trench', 'lyrics', 'changing', 'hes', 'dont'} {'dykstra', 'homesick', 'yankess', 'ballad', 'subterranean', 'anime'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_48
  WTF: {'erasure', 'products', 'surethats', 'reprogramming', 'types', 'hobbyist', 'preproduction'} {'neuronr', 'mc143150', 'snvt', 'mc143120', 'hc705k1', 'motorolas', 'hc711'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_49
  WTF: {'salvage', 'mosques', 'cozy', 'doublespeak', 'rules', 'essays', 'punishments', 'exemption'} {'commandeer', 'israelists', 'hymies', 'harikari', 'barfling', 'followingup', 'kkkaldis', 'ragheads'}
  WTF?!?!? 8
  WTF?!?!? 8

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f4fe86e3a30>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f4f4301c790>}
{'perplexity': 50123.54296875, 'coherence_20': 1.641029095322782, 'diversity_euclidean': 0.08114183195959096, 'diversity_jensenshannon': 0.6837640172359791, 'diversity_hellinger': 0.8020476296880763, 'diversity_cosine': 0.7804889135146729, 'fair_ppl_free': 2011.5960693359375, 'fair_ppl_fix': 49555.4375, 'unfair_ppl_banklike': 50123.54296875}
{'num_topics': 51, 'num_common_words': 59415, 'num_model_words': 114951, 'num_bt_words': 97541, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 16, 'lost_bt': 1, 'lost_model': 15}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 20, 'lost_bt': 1, 'lost_model': 19}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}]}
11
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
topic_3
  WTF: {'make'} {'stephanopoulos'}
topic_4
  WTF: {'vs'} {'nhl'}
topic_5
topic_6
  WTF: {'candida', 'surrender', 'dont'} {'hiv', 'n3jxp', 'gordon'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_7
topic_8
  WTF: {'crime'} {'cooper'}
topic_9
  WTF: {'discussion'} {'o157h7'}
topic_10
  WTF: {'ottoman', 'children', 'muslim', 'government', 'saw', 'started'} {'armenia', 'azerbaijan', 'armenians', 'sumgait', 'armenian', 'turks'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_11
  WTF: {'im'} {'bj200'}
topic_12
  WTF: {'CDROMCATZIP', '8800CS', 'CSCSTD00385', 'dragdrop', 'NikeCajun', '5152940082', 'recollection', 'taxation', '1795', '207556000', 'haunt', 'toolbox', 'effortsall', 'L2PMABGZ7VAZV0PZRI'} {''}
  WTF?!?!? 14
topic_13
topic_14
  WTF: {'mail'} {'ripem'}
topic_15
  WTF: {'transferable'} {'hotelco'}
topic_16
topic_17
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_18
topic_19
  WTF: {'j3davidstudentbusinessuwoca', '19851986', '19891990', 'testtaking'} {'ets', 'boulder', 'gre', 'rex'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_20
topic_21
  WTF: {'analytic', '02106chopinudeledu', 'vol', 'copyright', 'manual', 'writing'} {'vernor', 'hogan', 'baen', 'gibson', 'vinge', 'petrucci'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_22
  WTF: {'university', 'equinox', 'hebrew', 'april', 'studies', 'dead', 'superior', 'orders', 'dawn', 'oriental', 'golden', 'metaphysical'} {'rosae', 'reuss', 'amorc', 'crowley', 'crucis', 'rosicrucian', 'qumran', 'oto', 'orientis', 'frater', 'templi', 'ordo'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_23
  WTF: {'bugs', 'nasa', 'grows', 'levels', 'hm'} {'wingert', 'sei', 'mcwilliams', 'challenger', 'bret'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_24
  WTF: {'intrinsics'} {'r3'}
topic_25
  WTF: {'grayscales', 'market', 'properties', 'thanks', 'particular'} {'ocr', 'dexxa', 'mustek', 'scanman', 'paintbrush'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_26
topic_27
  WTF: {'mesur', 'solve', 'envoy', 'typeset', 'printing', 'wild', 'russian', 'famous'} {'armenia', 'persians', 'iosef', 'shirak', 'tyukhik', 'anania', 'armenian', 'orbeli'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_28
topic_29
topic_30
  WTF: {'use'} {'heydt'}
topic_31
topic_32
  WTF: {'regards', 'stripped'} {'sehari', 'babak'}
topic_33
  WTF: {'waxed', 'stuff'} {'glaze', 'mcquires'}
topic_34
  WTF: {'aside'} {'darius'}
topic_35
  WTF: {'facilities', 'systems', 'launch', 'version', 'inventions'} {'t4', 'energiam', 't4centaur', 'russia', 'salyut'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_36
  WTF: {'immoral', 'pork', 'bases', 'abolished'} {'registries', 'c5s', 'admistration', 'c17'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_37
  WTF: {'49er', 'mit', 'nick'} {'quincy', 'cambridge', 'sept'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_38
  WTF: {'doityourselfers', 'know'} {'kirlian', 'krillean'}
topic_39
  WTF: {'theory'} {'alice'}
topic_40
  WTF: {'teh'} {'mary'}
topic_41
  WTF: {'audio', 'returned', 'problem'} {'emerson', 'hifi', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_42
  WTF: {'trinomials', '0n', 'tp', '644', 'mm', 'pw', 'mj', 'ma', 'm1', 'u0', 'mf', 'mh'} {'p6', 'm3', 'm9', 'lu', 'm0', 'm5', 'o3', 'm6', 'pnospsxop8f', 'mw', 'e8', 'mx'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_43
  WTF: {'mach'} {'ses'}
topic_44
  WTF: {'fiansovamcom', 'reseacher', '6144594256', 'transliterated', 'kutuzovavenusitebserpukhovsu'} {'ussrsu', 'iki', 'belorusskaya', 'kremlin', 'moscow'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_45
  WTF: {'promote'} {'fenholt'}
topic_46
  WTF: {'120mph'} {'lubbock'}
topic_47
  WTF: {'revenue', 'washington'} {'catos', 'cato'}
topic_48
  WTF: {'mr', 'university', 'wish', 'incribed', 'science', 'mistyped', 'include'} {'marquette', 'regal', 'milwaukee', 'wi', 'robb', 'doublemajor', 'dubinski'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_49
  WTF: {'unload', 'received', 'telex', 'raylauffastrotempleedu', 'laserdisc', 'simplicitys', 'abyss'} {'h2y', '1c8', 'lauff', 'zeitgeist', 'cbsfox', 'nobles', 'filmtransmtl'}
  WTF?!?!? 7
  WTF?!?!? 7
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f4fe871e760>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
topic_3
  WTF: {'make'} {'stephanopoulos'}
topic_4
  WTF: {'vs'} {'nhl'}
topic_5
topic_6
  WTF: {'candida', 'surrender', 'dont'} {'hiv', 'n3jxp', 'gordon'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_7
topic_8
  WTF: {'crime'} {'cooper'}
topic_9
  WTF: {'discussion'} {'o157h7'}
topic_10
  WTF: {'ottoman', 'children', 'muslim', 'government', 'saw', 'started'} {'armenia', 'azerbaijan', 'armenians', 'sumgait', 'armenian', 'turks'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_11
  WTF: {'im'} {'bj200'}
topic_12
  WTF: {'CDROMCATZIP', '8800CS', 'CSCSTD00385', 'dragdrop', 'NikeCajun', '5152940082', 'recollection', 'taxation', '1795', '207556000', 'haunt', 'toolbox', 'effortsall', 'L2PMABGZ7VAZV0PZRI'} {''}
  WTF?!?!? 14
topic_13
topic_14
  WTF: {'mail'} {'ripem'}
topic_15
  WTF: {'transferable'} {'hotelco'}
topic_16
topic_17
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_18
topic_19
  WTF: {'j3davidstudentbusinessuwoca', '19851986', '19891990', 'testtaking'} {'ets', 'boulder', 'gre', 'rex'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_20
topic_21
  WTF: {'analytic', '02106chopinudeledu', 'vol', 'copyright', 'manual', 'writing'} {'vernor', 'hogan', 'baen', 'gibson', 'vinge', 'petrucci'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_22
  WTF: {'university', 'equinox', 'hebrew', 'april', 'studies', 'dead', 'superior', 'orders', 'dawn', 'oriental', 'golden', 'metaphysical'} {'rosae', 'reuss', 'amorc', 'crowley', 'crucis', 'rosicrucian', 'qumran', 'oto', 'orientis', 'frater', 'templi', 'ordo'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_23
  WTF: {'bugs', 'nasa', 'grows', 'levels', 'hm'} {'wingert', 'sei', 'mcwilliams', 'challenger', 'bret'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_24
  WTF: {'intrinsics'} {'r3'}
topic_25
  WTF: {'grayscales', 'market', 'properties', 'thanks', 'particular'} {'ocr', 'dexxa', 'mustek', 'scanman', 'paintbrush'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_26
topic_27
  WTF: {'mesur', 'solve', 'envoy', 'typeset', 'printing', 'wild', 'russian', 'famous'} {'armenia', 'persians', 'iosef', 'shirak', 'tyukhik', 'anania', 'armenian', 'orbeli'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_28
topic_29
topic_30
  WTF: {'use'} {'heydt'}
topic_31
topic_32
  WTF: {'regards', 'stripped'} {'sehari', 'babak'}
topic_33
  WTF: {'waxed', 'stuff'} {'glaze', 'mcquires'}
topic_34
  WTF: {'aside'} {'darius'}
topic_35
  WTF: {'facilities', 'systems', 'launch', 'version', 'inventions'} {'t4', 'energiam', 't4centaur', 'russia', 'salyut'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_36
  WTF: {'immoral', 'pork', 'bases', 'abolished'} {'registries', 'c5s', 'admistration', 'c17'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_37
  WTF: {'49er', 'mit', 'nick'} {'quincy', 'cambridge', 'sept'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_38
  WTF: {'doityourselfers', 'know'} {'kirlian', 'krillean'}
topic_39
  WTF: {'theory'} {'alice'}
topic_40
  WTF: {'teh'} {'mary'}
topic_41
  WTF: {'audio', 'returned', 'problem'} {'emerson', 'hifi', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_42
  WTF: {'trinomials', '0n', 'tp', '644', 'mm', 'pw', 'mj', 'ma', 'm1', 'u0', 'mf', 'mh'} {'p6', 'm3', 'm9', 'lu', 'm0', 'm5', 'o3', 'm6', 'pnospsxop8f', 'mw', 'e8', 'mx'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_43
  WTF: {'mach'} {'ses'}
topic_44
  WTF: {'fiansovamcom', 'reseacher', '6144594256', 'transliterated', 'kutuzovavenusitebserpukhovsu'} {'ussrsu', 'iki', 'belorusskaya', 'kremlin', 'moscow'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_45
  WTF: {'promote'} {'fenholt'}
topic_46
  WTF: {'120mph'} {'lubbock'}
topic_47
  WTF: {'revenue', 'washington'} {'catos', 'cato'}
topic_48
  WTF: {'mr', 'university', 'wish', 'incribed', 'science', 'mistyped', 'include'} {'marquette', 'regal', 'milwaukee', 'wi', 'robb', 'doublemajor', 'dubinski'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_49
  WTF: {'unload', 'received', 'telex', 'raylauffastrotempleedu', 'laserdisc', 'simplicitys', 'abyss'} {'h2y', '1c8', 'lauff', 'zeitgeist', 'cbsfox', 'nobles', 'filmtransmtl'}
  WTF?!?!? 7
  WTF?!?!? 7

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f4fd47f7070>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f50285c60d0>}
{'perplexity': 51954.96484375, 'coherence_20': 1.640633039536707, 'diversity_euclidean': 0.09129003243695974, 'diversity_jensenshannon': 0.7111699490515716, 'diversity_hellinger': 0.8360519236095001, 'diversity_cosine': 0.8116510771299862, 'fair_ppl_free': 2037.6807861328125, 'fair_ppl_fix': 51338.7890625, 'unfair_ppl_banklike': 51954.96484375}
{'num_topics': 51, 'num_common_words': 59415, 'num_model_words': 114951, 'num_bt_words': 97541, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 15, 'lost_bt': 1, 'lost_model': 14}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}]}
12
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
topic_3
  WTF: {'vs'} {'nhl'}
topic_4
topic_5
  WTF: {'candida', 'surrender', 'dont'} {'hiv', 'n3jxp', 'gordon'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_6
topic_7
  WTF: {'discussion'} {'o157h7'}
topic_8
topic_9
  WTF: {'ottoman', 'children', 'muslim', 'government', 'saw', 'started'} {'armenia', 'azerbaijan', 'armenians', 'sumgait', 'armenian', 'turks'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_10
  WTF: {'driver'} {'bj200'}
topic_11
  WTF: {'CDROMCATZIP', 'ringleaders', 'Guideline', 'dragdrop', 'taxation', '1795', 'knowlege', 'toolbox', 'effortsall', 'monthly', '8800CS', 'CSCSTD00385', 'NikeCajun', '5152940082', '207556000', 'JH2SC281XPM100187', 'L2PMABGZ7VAZV0PZRI'} {''}
  WTF?!?!? 17
topic_12
  WTF: {'posting', 'email'} {'rsa', 'ripem'}
topic_13
  WTF: {'technology', 'management'} {'vinge', 'gre'}
topic_14
topic_15
  WTF: {'available'} {'hotelco'}
topic_16
  WTF: {'built'} {'cato'}
topic_17
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_18
topic_19
  WTF: {'accident'} {'supra'}
topic_20
topic_21
topic_22
  WTF: {'16ea', 'sensor'} {'irwin', 'mactools'}
topic_23
  WTF: {'resoltuion', 'grayscales', 'market', 'properties', 'particular'} {'ocr', 'mustek', 'scanman', 'paintbrush', 'ocr104zip'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_24
  WTF: {'heh', 'video'} {'emerson', 'vcr'}
topic_25
  WTF: {'spring', 'english', 'sunday'} {'pesach', 'ishtar', 'bede'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_26
topic_27
  WTF: {'aside'} {'darius'}
topic_28
  WTF: {'mesur', 'solve', 'envoy', 'typeset', 'printing', 'wild', 'russian', 'famous'} {'armenia', 'persians', 'iosef', 'shirak', 'tyukhik', 'anania', 'armenian', 'orbeli'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_29
  WTF: {'immoral', 'pork', 'bases', 'abolished'} {'registries', 'c5s', 'admistration', 'c17'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_30
  WTF: {'regards', 'stripped'} {'sehari', 'babak'}
topic_31
  WTF: {'participants', 'tuesday', 'mall'} {'quincy', 'kenai', 'amc'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_32
  WTF: {'theory'} {'alice'}
topic_33
  WTF: {'punks', 'latchkey', 'columbia', 'campus', 'followups', 'bc', 'whipping', 'fred'} {'meson', 'bach', 'v6t', 'triuniversity', '2a3', 'ubc', 'triumf', 'wesbrook'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_34
  WTF: {'hiden'} {'scotyy'}
topic_35
  WTF: {'womenandrewcmuedu', 'laundromat', 'culture', 'student'} {'palace', 'nozyk', 'gainesville', 'shul'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_36
  WTF: {'07090', 'uunetkc2wzbob', 'unpatentable', 'backand', 'patentable', 'vending'} {'billson', 'crah', 'cocacola', 'yerazunis', 'pepsi', 'cola'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_37
topic_38
  WTF: {'uuencode', 'ioccc'} {'eofnotok', 'xvoid'}
topic_39
  WTF: {'pads', 'addition', 'combo', 'version', 'stabilized'} {'t4', 'energiam', 't4centaur', 'russia', 'salyut'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_40
  WTF: {'promote'} {'fenholt'}
topic_41
  WTF: {'publications', 'product', 'licensed', 'internet', 'science', 'promote', 'include'} {'marquette', 'regal', 'milwaukee', 'wi', 'robb', 'doublemajor', 'dubinski'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_42
  WTF: {'trinomials', '0n', 'tp', '644', 'mm', 'pw', 'mj', 'ma', 'm1', 'u0', 'mf', 'mh'} {'p6', 'm3', 'm9', 'lu', 'm0', 'm5', 'o3', 'm6', 'pnospsxop8f', 'mw', 'e8', 'mx'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_43
  WTF: {'informations', 'ive', 'wrongthe', 'software', 'imaginerequestemailspparamaxcom', 'licensees', 'allright'} {'bitmovie', 'ipas', '3do', 'activa', 'riccione', 'r3d', 'sergio'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_44
  WTF: {'90s', 'rebel', 'giveaway', 'rednecks', '8177', 'soar', 'racers'} {'smokey', 'pgh', 'yogis', 'yogi', 'thumper', 'mcqueen', 'bandit'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_45
topic_46
  WTF: {'heinous', 'radicals', 'throats'} {'transarc', 'hoovers', 'lyle'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_47
  WTF: {'asshole', 'oil'} {'cambodia', 'bakker'}
topic_48
  WTF: {'2275753', '2042', 'lipmanoasysdtnavymil', 'pace', '2273618'} {'bethesda', 'lipman', 'navyrelated', 'siggraph', 'sigkids'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_49
  WTF: {'concensus', 'themey', 'addition'} {'faires', 'bridgend', 'mattell'}
  WTF?!?!? 3
  WTF?!?!? 3
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f4ff13c05b0>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
topic_3
  WTF: {'vs'} {'nhl'}
topic_4
topic_5
  WTF: {'candida', 'surrender', 'dont'} {'hiv', 'n3jxp', 'gordon'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_6
topic_7
  WTF: {'discussion'} {'o157h7'}
topic_8
topic_9
  WTF: {'ottoman', 'children', 'muslim', 'government', 'saw', 'started'} {'armenia', 'azerbaijan', 'armenians', 'sumgait', 'armenian', 'turks'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_10
  WTF: {'driver'} {'bj200'}
topic_11
  WTF: {'CDROMCATZIP', 'ringleaders', 'Guideline', 'dragdrop', 'taxation', '1795', 'knowlege', 'toolbox', 'effortsall', 'monthly', '8800CS', 'CSCSTD00385', 'NikeCajun', '5152940082', '207556000', 'JH2SC281XPM100187', 'L2PMABGZ7VAZV0PZRI'} {''}
  WTF?!?!? 17
topic_12
  WTF: {'posting', 'email'} {'rsa', 'ripem'}
topic_13
  WTF: {'technology', 'management'} {'vinge', 'gre'}
topic_14
topic_15
  WTF: {'available'} {'hotelco'}
topic_16
  WTF: {'built'} {'cato'}
topic_17
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_18
topic_19
  WTF: {'accident'} {'supra'}
topic_20
topic_21
topic_22
  WTF: {'16ea', 'sensor'} {'irwin', 'mactools'}
topic_23
  WTF: {'resoltuion', 'grayscales', 'market', 'properties', 'particular'} {'ocr', 'mustek', 'scanman', 'paintbrush', 'ocr104zip'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_24
  WTF: {'heh', 'video'} {'emerson', 'vcr'}
topic_25
  WTF: {'spring', 'english', 'sunday'} {'pesach', 'ishtar', 'bede'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_26
topic_27
  WTF: {'aside'} {'darius'}
topic_28
  WTF: {'mesur', 'solve', 'envoy', 'typeset', 'printing', 'wild', 'russian', 'famous'} {'armenia', 'persians', 'iosef', 'shirak', 'tyukhik', 'anania', 'armenian', 'orbeli'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_29
  WTF: {'immoral', 'pork', 'bases', 'abolished'} {'registries', 'c5s', 'admistration', 'c17'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_30
  WTF: {'regards', 'stripped'} {'sehari', 'babak'}
topic_31
  WTF: {'participants', 'tuesday', 'mall'} {'quincy', 'kenai', 'amc'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_32
  WTF: {'theory'} {'alice'}
topic_33
  WTF: {'punks', 'latchkey', 'columbia', 'campus', 'followups', 'bc', 'whipping', 'fred'} {'meson', 'bach', 'v6t', 'triuniversity', '2a3', 'ubc', 'triumf', 'wesbrook'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_34
  WTF: {'hiden'} {'scotyy'}
topic_35
  WTF: {'womenandrewcmuedu', 'laundromat', 'culture', 'student'} {'palace', 'nozyk', 'gainesville', 'shul'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_36
  WTF: {'07090', 'uunetkc2wzbob', 'unpatentable', 'backand', 'patentable', 'vending'} {'billson', 'crah', 'cocacola', 'yerazunis', 'pepsi', 'cola'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_37
topic_38
  WTF: {'uuencode', 'ioccc'} {'eofnotok', 'xvoid'}
topic_39
  WTF: {'pads', 'addition', 'combo', 'version', 'stabilized'} {'t4', 'energiam', 't4centaur', 'russia', 'salyut'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_40
  WTF: {'promote'} {'fenholt'}
topic_41
  WTF: {'publications', 'product', 'licensed', 'internet', 'science', 'promote', 'include'} {'marquette', 'regal', 'milwaukee', 'wi', 'robb', 'doublemajor', 'dubinski'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_42
  WTF: {'trinomials', '0n', 'tp', '644', 'mm', 'pw', 'mj', 'ma', 'm1', 'u0', 'mf', 'mh'} {'p6', 'm3', 'm9', 'lu', 'm0', 'm5', 'o3', 'm6', 'pnospsxop8f', 'mw', 'e8', 'mx'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_43
  WTF: {'informations', 'ive', 'wrongthe', 'software', 'imaginerequestemailspparamaxcom', 'licensees', 'allright'} {'bitmovie', 'ipas', '3do', 'activa', 'riccione', 'r3d', 'sergio'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_44
  WTF: {'90s', 'rebel', 'giveaway', 'rednecks', '8177', 'soar', 'racers'} {'smokey', 'pgh', 'yogis', 'yogi', 'thumper', 'mcqueen', 'bandit'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_45
topic_46
  WTF: {'heinous', 'radicals', 'throats'} {'transarc', 'hoovers', 'lyle'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_47
  WTF: {'asshole', 'oil'} {'cambodia', 'bakker'}
topic_48
  WTF: {'2275753', '2042', 'lipmanoasysdtnavymil', 'pace', '2273618'} {'bethesda', 'lipman', 'navyrelated', 'siggraph', 'sigkids'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_49
  WTF: {'concensus', 'themey', 'addition'} {'faires', 'bridgend', 'mattell'}
  WTF?!?!? 3
  WTF?!?!? 3

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f4fe86d8a60>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f5028561340>}
{'perplexity': 50738.1953125, 'coherence_20': 1.6560570089144222, 'diversity_euclidean': 0.10094926677769439, 'diversity_jensenshannon': 0.7113251147897297, 'diversity_hellinger': 0.8369293292208932, 'diversity_cosine': 0.8119847710238492, 'fair_ppl_free': 2058.753173828125, 'fair_ppl_fix': 50247.5546875, 'unfair_ppl_banklike': 50738.1953125}
{'num_topics': 51, 'num_common_words': 59415, 'num_model_words': 114951, 'num_bt_words': 97541, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 18, 'lost_bt': 1, 'lost_model': 17}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}]}
13
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
  WTF: {'vs'} {'nhl'}
topic_3
topic_4
  WTF: {'just', 'algorithm'} {'stephanopoulos', 'nsa'}
topic_5
  WTF: {'government'} {'fbi'}
topic_6
  WTF: {'candida', 'surrender', 'dont'} {'hiv', 'n3jxp', 'gordon'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_7
topic_8
  WTF: {'thanks'} {'o157h7'}
topic_9
  WTF: {'ottoman', 'children', 'muslim', 'government', 'saw', 'started'} {'armenia', 'azerbaijan', 'armenians', 'sumgait', 'armenian', 'turks'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_10
  WTF: {'scanner'} {'bj200'}
topic_11
  WTF: {'like', 'sin'} {'caligiuri', 'enviroleague'}
topic_12
  WTF: {'NikeDeacon', 'CDROMCATZIP', '8800CS', 'CSCSTD00385', 'dragdrop', 'NikeCajun', '5152940082', 'recollection', 'taxation', '1795', '207556000', 'toolbox', 'effortsall', 'L2PMABGZ7VAZV0PZRI'} {''}
  WTF?!?!? 14
topic_13
topic_14
  WTF: {'posting', 'email'} {'rsa', 'ripem'}
topic_15
  WTF: {'driving'} {'caltrans'}
topic_16
  WTF: {'sale'} {'hotelco'}
topic_17
topic_18
topic_19
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_20
  WTF: {'festival'} {'ishtar'}
topic_21
topic_22
  WTF: {'fuel'} {'cato'}
topic_23
  WTF: {'analytic', '02106chopinudeledu', 'vol', 'copyright', 'manual', 'writing'} {'vernor', 'hogan', 'baen', 'gibson', 'vinge', 'petrucci'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_24
  WTF: {'different'} {'clayton'}
topic_25
  WTF: {'intrinsics'} {'r3'}
topic_26
topic_27
  WTF: {'objects', 'charged'} {'kirlian', 'krillean'}
topic_28
  WTF: {'dim'} {'emi'}
topic_29
  WTF: {'regards', 'stripped'} {'sehari', 'babak'}
topic_30
  WTF: {'mesur', 'solve', 'envoy', 'typeset', 'printing', 'wild', 'russian', 'famous'} {'armenia', 'persians', 'iosef', 'shirak', 'tyukhik', 'anania', 'armenian', 'orbeli'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_31
  WTF: {'immoral', 'pork', 'bases', 'abolished'} {'registries', 'c5s', 'admistration', 'c17'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_32
  WTF: {'49er', 'nick', 'car'} {'quincy', 'cambridge', 'sept'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_33
  WTF: {'directors', 'folks', 'rode', 'articles'} {'ama', 'moa', 'bmwmoa', 'mc'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_34
topic_35
  WTF: {'sodium', 'launches', 'launch', 'class'} {'ssrt', 'tripoli', 'hpr', 'faa'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_36
  WTF: {'theory'} {'alice'}
topic_37
  WTF: {'screen', 'trick', 'switcher'} {'robbinsgreat', 'supercharging', 'judd'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_38
  WTF: {'uuencode', 'ioccc'} {'eofnotok', 'xvoid'}
topic_39
  WTF: {'2275753', 'pace', '2042', '2273618'} {'siggraph', 'bethesda', 'lipman', 'sigkids'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_40
  WTF: {'90s', 'rebel', 'giveaway', 'rednecks', 'stoned', 'soar', 'racers'} {'smokey', 'pgh', 'yogis', 'yogi', 'thumper', 'mcqueen', 'bandit'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_41
  WTF: {'audio', 'returned', 'problem'} {'emerson', 'hifi', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_42
  WTF: {'pads', 'addition', 'combo', 'version', 'stabilized'} {'t4', 'energiam', 't4centaur', 'russia', 'salyut'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_43
  WTF: {'received', 'preciated', 'letterbox', 'raylauffastrotempleedu', 't2', 'simplicitys', 'rmers'} {'csundh30ursacalvinedu', '1c8', 'lauff', 'nasm', 'zeitgeist', 'cbsfox', 'filmtransmtl'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_44
  WTF: {'deleted', 'commuter', '120mph'} {'lubbock', 'houston', 'dallas'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_45
  WTF: {'bad', 'article', 'facts', '010101', 'karrcscornelledu', '290000'} {'wales', 'karr', 'coterill', 'england', 'barnstaple', 'roberts'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_46
  WTF: {'promote'} {'fenholt'}
topic_47
  WTF: {'trinomials', '0n', 'tp', '644', 'mm', 'pw', 'mj', 'ma', 'm1', 'u0', 'mf', 'mh'} {'p6', 'm3', 'm9', 'lu', 'm0', 'm5', 'o3', 'm6', 'pnospsxop8f', 'mw', 'e8', 'mx'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_48
  WTF: {'accessno', 'choking', 'netxt'} {'17500', 'hermesmeritedu', 'vax'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_49
  WTF: {'leds', 'define', 'port', '8051', 'register', 'break', 'include'} {'mvi', 'uartcmd', 'equ', 'porta', 'lda', 'sta', 'uartdata'}
  WTF?!?!? 7
  WTF?!?!? 7
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f4fd48ab340>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
  WTF: {'vs'} {'nhl'}
topic_3
topic_4
  WTF: {'just', 'algorithm'} {'stephanopoulos', 'nsa'}
topic_5
  WTF: {'government'} {'fbi'}
topic_6
  WTF: {'candida', 'surrender', 'dont'} {'hiv', 'n3jxp', 'gordon'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_7
topic_8
  WTF: {'thanks'} {'o157h7'}
topic_9
  WTF: {'ottoman', 'children', 'muslim', 'government', 'saw', 'started'} {'armenia', 'azerbaijan', 'armenians', 'sumgait', 'armenian', 'turks'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_10
  WTF: {'scanner'} {'bj200'}
topic_11
  WTF: {'like', 'sin'} {'caligiuri', 'enviroleague'}
topic_12
  WTF: {'NikeDeacon', 'CDROMCATZIP', '8800CS', 'CSCSTD00385', 'dragdrop', 'NikeCajun', '5152940082', 'recollection', 'taxation', '1795', '207556000', 'toolbox', 'effortsall', 'L2PMABGZ7VAZV0PZRI'} {''}
  WTF?!?!? 14
topic_13
topic_14
  WTF: {'posting', 'email'} {'rsa', 'ripem'}
topic_15
  WTF: {'driving'} {'caltrans'}
topic_16
  WTF: {'sale'} {'hotelco'}
topic_17
topic_18
topic_19
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_20
  WTF: {'festival'} {'ishtar'}
topic_21
topic_22
  WTF: {'fuel'} {'cato'}
topic_23
  WTF: {'analytic', '02106chopinudeledu', 'vol', 'copyright', 'manual', 'writing'} {'vernor', 'hogan', 'baen', 'gibson', 'vinge', 'petrucci'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_24
  WTF: {'different'} {'clayton'}
topic_25
  WTF: {'intrinsics'} {'r3'}
topic_26
topic_27
  WTF: {'objects', 'charged'} {'kirlian', 'krillean'}
topic_28
  WTF: {'dim'} {'emi'}
topic_29
  WTF: {'regards', 'stripped'} {'sehari', 'babak'}
topic_30
  WTF: {'mesur', 'solve', 'envoy', 'typeset', 'printing', 'wild', 'russian', 'famous'} {'armenia', 'persians', 'iosef', 'shirak', 'tyukhik', 'anania', 'armenian', 'orbeli'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_31
  WTF: {'immoral', 'pork', 'bases', 'abolished'} {'registries', 'c5s', 'admistration', 'c17'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_32
  WTF: {'49er', 'nick', 'car'} {'quincy', 'cambridge', 'sept'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_33
  WTF: {'directors', 'folks', 'rode', 'articles'} {'ama', 'moa', 'bmwmoa', 'mc'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_34
topic_35
  WTF: {'sodium', 'launches', 'launch', 'class'} {'ssrt', 'tripoli', 'hpr', 'faa'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_36
  WTF: {'theory'} {'alice'}
topic_37
  WTF: {'screen', 'trick', 'switcher'} {'robbinsgreat', 'supercharging', 'judd'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_38
  WTF: {'uuencode', 'ioccc'} {'eofnotok', 'xvoid'}
topic_39
  WTF: {'2275753', 'pace', '2042', '2273618'} {'siggraph', 'bethesda', 'lipman', 'sigkids'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_40
  WTF: {'90s', 'rebel', 'giveaway', 'rednecks', 'stoned', 'soar', 'racers'} {'smokey', 'pgh', 'yogis', 'yogi', 'thumper', 'mcqueen', 'bandit'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_41
  WTF: {'audio', 'returned', 'problem'} {'emerson', 'hifi', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_42
  WTF: {'pads', 'addition', 'combo', 'version', 'stabilized'} {'t4', 'energiam', 't4centaur', 'russia', 'salyut'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_43
  WTF: {'received', 'preciated', 'letterbox', 'raylauffastrotempleedu', 't2', 'simplicitys', 'rmers'} {'csundh30ursacalvinedu', '1c8', 'lauff', 'nasm', 'zeitgeist', 'cbsfox', 'filmtransmtl'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_44
  WTF: {'deleted', 'commuter', '120mph'} {'lubbock', 'houston', 'dallas'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_45
  WTF: {'bad', 'article', 'facts', '010101', 'karrcscornelledu', '290000'} {'wales', 'karr', 'coterill', 'england', 'barnstaple', 'roberts'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_46
  WTF: {'promote'} {'fenholt'}
topic_47
  WTF: {'trinomials', '0n', 'tp', '644', 'mm', 'pw', 'mj', 'ma', 'm1', 'u0', 'mf', 'mh'} {'p6', 'm3', 'm9', 'lu', 'm0', 'm5', 'o3', 'm6', 'pnospsxop8f', 'mw', 'e8', 'mx'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_48
  WTF: {'accessno', 'choking', 'netxt'} {'17500', 'hermesmeritedu', 'vax'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_49
  WTF: {'leds', 'define', 'port', '8051', 'register', 'break', 'include'} {'mvi', 'uartcmd', 'equ', 'porta', 'lda', 'sta', 'uartdata'}
  WTF?!?!? 7
  WTF?!?!? 7

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f4fe86e3c40>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f4ff1213220>}
{'perplexity': 50005.89453125, 'coherence_20': 1.7796361469571491, 'diversity_euclidean': 0.08603999241578436, 'diversity_jensenshannon': 0.701010992195722, 'diversity_hellinger': 0.8240966942910557, 'diversity_cosine': 0.8045174837568688, 'fair_ppl_free': 2028.7783203125, 'fair_ppl_fix': 49477.6171875, 'unfair_ppl_banklike': 50005.89453125}
{'num_topics': 51, 'num_common_words': 59415, 'num_model_words': 114951, 'num_bt_words': 97541, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 15, 'lost_bt': 1, 'lost_model': 14}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}]}
14
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
  WTF: {'vs'} {'nhl'}
topic_3
topic_4
  WTF: {'banks', 'candida', 'surrender'} {'hiv', 'n3jxp', 'gordon'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_5
topic_6
  WTF: {'posting'} {'o157h7'}
topic_7
  WTF: {'ottoman', 'children', 'muslim', 'government', 'saw', 'started'} {'armenia', 'azerbaijan', 'armenians', 'sumgait', 'armenian', 'turks'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_8
  WTF: {'quality'} {'bj200'}
topic_9
  WTF: {'like', 'sin'} {'caligiuri', 'enviroleague'}
topic_10
  WTF: {'CDROMCATZIP', 'ringleaders', 'CSCSTD00385', 'dragdrop', 'NikeCajun', '8800CS', '5152940082', 'taxation', 'Epilepsy', 'knowlege', '1795', '207556000', 'toolbox', 'effortsall', 'L2PMABGZ7VAZV0PZRI'} {''}
  WTF?!?!? 15
topic_11
topic_12
  WTF: {'football', 'adventure', '35'} {'snes', 'cdi', 'sega'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_13
  WTF: {'posting', 'email'} {'rsa', 'ripem'}
topic_14
  WTF: {'cars'} {'caltrans'}
topic_15
  WTF: {'transferable'} {'hotelco'}
topic_16
topic_17
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_18
  WTF: {'general', 'j3davidstudentbusinessuwoca', 'plasktbdemoncouk', 'testtaking'} {'ets', 'boulder', 'gre', 'rex'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_19
topic_20
  WTF: {'filtration', 'insisting', 'bomb', 'things'} {'barre', 'auth', 'cato', 'epa'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_21
topic_22
  WTF: {'analytic', '02106chopinudeledu', 'vol', 'email', 'copyright', 'writing'} {'vernor', 'dune', 'baen', 'gibson', 'vinge', 'petrucci'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_23
  WTF: {'use', '250'} {'irwin', 'mactools'}
topic_24
  WTF: {'intrinsics'} {'r3'}
topic_25
  WTF: {'books', 'april', 'studies', 'exhibition', 'orders', 'bookstore', 'scroll'} {'rosae', 'amorc', 'crucis', 'rosicrucian', 'qumran', 'oto', 'ordo'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_26
  WTF: {'try', 'card'} {'sb', 'microsofts'}
topic_27
  WTF: {'mesur', 'solve', 'envoy', 'typeset', 'printing', 'wild', 'russian', 'famous'} {'armenia', 'persians', 'iosef', 'shirak', 'tyukhik', 'anania', 'armenian', 'orbeli'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_28
  WTF: {'people', 'english'} {'ishtar', 'bede'}
topic_29
topic_30
topic_31
  WTF: {'doityourselfers', 'know'} {'kirlian', 'krillean'}
topic_32
  WTF: {'aside'} {'darius'}
topic_33
topic_34
  WTF: {'type', 'dim'} {'emi', 'hv'}
topic_35
  WTF: {'regards', 'stripped'} {'sehari', 'babak'}
topic_36
  WTF: {'engineers', 'participants', 'tutorial', 'conference'} {'mellon', 'japan', 'carnegie', 'jstmp'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_37
  WTF: {'49er', 'mit', 'nick'} {'quincy', 'cambridge', 'sept'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_38
  WTF: {'6192214511', 'nive', 'ftpinformatikunioldenburgdepubdkbtraceutils', 'outputing', '6192212527', 'raytrace'} {'vvfont18zip', 'perth', 'psadobe20', 'povshell', 'versatec', 'ply16386'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_39
  WTF: {'number', 'rule', 'computer'} {'alice', 'douglas', 'adams'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_40
  WTF: {'utter', 'axe', 'commission'} {'registries', 'admistration', 'irs'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_41
  WTF: {'contractors', 'postings', 'wit'} {'mea', 'baghdad', 'bnr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_42
  WTF: {'computational', 'fax', 'genetic'} {'siggraph', 'bethesda', 'sigkids'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_43
  WTF: {'trinomials', '0n', 'tp', '644', 'mm', 'pw', 'mj', 'ma', 'm1', 'u0', 'mf', 'mh'} {'p6', 'm3', 'm9', 'lu', 'm0', 'm5', 'pnospsxop8f', 'm6', 'o3', 'mw', 'e8', 'mx'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_44
  WTF: {'audio', 'returned', 'problem'} {'emerson', 'hifi', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_45
  WTF: {'pads', 'addition', 'combo', 'version', 'stabilized'} {'t4', 'energiam', 't4centaur', 'russia', 'salyut'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_46
  WTF: {'uuencode', 'ioccc'} {'eofnotok', 'xvoid'}
topic_47
  WTF: {'promote'} {'fenholt'}
topic_48
  WTF: {'somethin', 'memorable', 'trench', 'changing', 'hes', 'roam'} {'dykstra', 'homesick', 'yankess', 'ballad', 'subterranean', 'anime'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_49
  WTF: {'suspicions', 'leave'} {'avagadros', 'menuts'}
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f4fe86f3f70>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
  WTF: {'vs'} {'nhl'}
topic_3
topic_4
  WTF: {'banks', 'candida', 'surrender'} {'hiv', 'n3jxp', 'gordon'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_5
topic_6
  WTF: {'posting'} {'o157h7'}
topic_7
  WTF: {'ottoman', 'children', 'muslim', 'government', 'saw', 'started'} {'armenia', 'azerbaijan', 'armenians', 'sumgait', 'armenian', 'turks'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_8
  WTF: {'quality'} {'bj200'}
topic_9
  WTF: {'like', 'sin'} {'caligiuri', 'enviroleague'}
topic_10
  WTF: {'CDROMCATZIP', 'ringleaders', 'CSCSTD00385', 'dragdrop', 'NikeCajun', '8800CS', '5152940082', 'taxation', 'Epilepsy', 'knowlege', '1795', '207556000', 'toolbox', 'effortsall', 'L2PMABGZ7VAZV0PZRI'} {''}
  WTF?!?!? 15
topic_11
topic_12
  WTF: {'football', 'adventure', '35'} {'snes', 'cdi', 'sega'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_13
  WTF: {'posting', 'email'} {'rsa', 'ripem'}
topic_14
  WTF: {'cars'} {'caltrans'}
topic_15
  WTF: {'transferable'} {'hotelco'}
topic_16
topic_17
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_18
  WTF: {'general', 'j3davidstudentbusinessuwoca', 'plasktbdemoncouk', 'testtaking'} {'ets', 'boulder', 'gre', 'rex'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_19
topic_20
  WTF: {'filtration', 'insisting', 'bomb', 'things'} {'barre', 'auth', 'cato', 'epa'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_21
topic_22
  WTF: {'analytic', '02106chopinudeledu', 'vol', 'email', 'copyright', 'writing'} {'vernor', 'dune', 'baen', 'gibson', 'vinge', 'petrucci'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_23
  WTF: {'use', '250'} {'irwin', 'mactools'}
topic_24
  WTF: {'intrinsics'} {'r3'}
topic_25
  WTF: {'books', 'april', 'studies', 'exhibition', 'orders', 'bookstore', 'scroll'} {'rosae', 'amorc', 'crucis', 'rosicrucian', 'qumran', 'oto', 'ordo'}
  WTF?!?!? 7
  WTF?!?!? 7
topic_26
  WTF: {'try', 'card'} {'sb', 'microsofts'}
topic_27
  WTF: {'mesur', 'solve', 'envoy', 'typeset', 'printing', 'wild', 'russian', 'famous'} {'armenia', 'persians', 'iosef', 'shirak', 'tyukhik', 'anania', 'armenian', 'orbeli'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_28
  WTF: {'people', 'english'} {'ishtar', 'bede'}
topic_29
topic_30
topic_31
  WTF: {'doityourselfers', 'know'} {'kirlian', 'krillean'}
topic_32
  WTF: {'aside'} {'darius'}
topic_33
topic_34
  WTF: {'type', 'dim'} {'emi', 'hv'}
topic_35
  WTF: {'regards', 'stripped'} {'sehari', 'babak'}
topic_36
  WTF: {'engineers', 'participants', 'tutorial', 'conference'} {'mellon', 'japan', 'carnegie', 'jstmp'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_37
  WTF: {'49er', 'mit', 'nick'} {'quincy', 'cambridge', 'sept'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_38
  WTF: {'6192214511', 'nive', 'ftpinformatikunioldenburgdepubdkbtraceutils', 'outputing', '6192212527', 'raytrace'} {'vvfont18zip', 'perth', 'psadobe20', 'povshell', 'versatec', 'ply16386'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_39
  WTF: {'number', 'rule', 'computer'} {'alice', 'douglas', 'adams'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_40
  WTF: {'utter', 'axe', 'commission'} {'registries', 'admistration', 'irs'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_41
  WTF: {'contractors', 'postings', 'wit'} {'mea', 'baghdad', 'bnr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_42
  WTF: {'computational', 'fax', 'genetic'} {'siggraph', 'bethesda', 'sigkids'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_43
  WTF: {'trinomials', '0n', 'tp', '644', 'mm', 'pw', 'mj', 'ma', 'm1', 'u0', 'mf', 'mh'} {'p6', 'm3', 'm9', 'lu', 'm0', 'm5', 'pnospsxop8f', 'm6', 'o3', 'mw', 'e8', 'mx'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_44
  WTF: {'audio', 'returned', 'problem'} {'emerson', 'hifi', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_45
  WTF: {'pads', 'addition', 'combo', 'version', 'stabilized'} {'t4', 'energiam', 't4centaur', 'russia', 'salyut'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_46
  WTF: {'uuencode', 'ioccc'} {'eofnotok', 'xvoid'}
topic_47
  WTF: {'promote'} {'fenholt'}
topic_48
  WTF: {'somethin', 'memorable', 'trench', 'changing', 'hes', 'roam'} {'dykstra', 'homesick', 'yankess', 'ballad', 'subterranean', 'anime'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_49
  WTF: {'suspicions', 'leave'} {'avagadros', 'menuts'}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f4fe5d426d0>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f5028561340>}
{'perplexity': 54154.7734375, 'coherence_20': 1.7136920583037496, 'diversity_euclidean': 0.09926125212283365, 'diversity_jensenshannon': 0.7258979453210477, 'diversity_hellinger': 0.8556682144631138, 'diversity_cosine': 0.8404012537903796, 'fair_ppl_free': 2078.6923828125, 'fair_ppl_fix': 53432.05859375, 'unfair_ppl_banklike': 54154.7734375}
{'num_topics': 51, 'num_common_words': 59415, 'num_model_words': 114951, 'num_bt_words': 97541, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 16, 'lost_bt': 1, 'lost_model': 15}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 14, 'lost_bt': 7, 'lost_model': 7}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}]}
15
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
  WTF: {'like'} {'stephanopoulos'}
topic_3
  WTF: {'vs'} {'nhl'}
topic_4
topic_5
  WTF: {'candida', 'surrender', 'dont'} {'hiv', 'n3jxp', 'gordon'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_6
topic_7
  WTF: {'news'} {'o157h7'}
topic_8
topic_9
  WTF: {'ottoman', 'children', 'muslim', 'government', 'saw', 'started'} {'armenia', 'azerbaijan', 'armenians', 'sumgait', 'armenian', 'turks'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_10
  WTF: {'driver'} {'bj200'}
topic_11
  WTF: {'CDROMCATZIP', 'ringleaders', 'CSCSTD00385', 'dragdrop', 'NikeCajun', '8800CS', '5152940082', 'taxation', 'Epilepsy', 'knowlege', '1795', '207556000', 'toolbox', 'effortsall', 'L2PMABGZ7VAZV0PZRI'} {''}
  WTF?!?!? 15
topic_12
  WTF: {'mail'} {'ripem'}
topic_13
topic_14
  WTF: {'living'} {'hotelco'}
topic_15
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_16
topic_17
topic_18
  WTF: {'porsche'} {'supra'}
topic_19
  WTF: {'analytic', '02106chopinudeledu', 'vol', 'copyright', 'manual', 'writing'} {'vernor', 'dune', 'hogan', 'baen', 'gibson', 'vinge'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_20
  WTF: {'use', '250'} {'irwin', 'mactools'}
topic_21
  WTF: {'ray', 'motif'} {'rsi', 'r3'}
topic_22
  WTF: {'grayscales', 'market', 'properties', 'thanks', 'particular'} {'ocr', 'dexxa', 'mustek', 'scanman', 'paintbrush'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_23
  WTF: {'try', 'card'} {'sb', 'microsofts'}
topic_24
topic_25
  WTF: {'6174940565', 'fourdcom'} {'reids', '1493'}
topic_26
topic_27
topic_28
  WTF: {'aside'} {'darius'}
topic_29
  WTF: {'engineers', 'participants', 'tutorial', 'conference'} {'mellon', 'japan', 'carnegie', 'jstmp'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_30
  WTF: {'bang', 'forget', 'trillion'} {'alice', 'douglas', 'adams'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_31
  WTF: {'regards', 'stripped'} {'sehari', 'babak'}
topic_32
  WTF: {'directors', 'folks', 'rode', 'articles'} {'ama', 'moa', 'bmwmoa', 'mc'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_33
  WTF: {'list', 'utter', 'jobs', 'military'} {'registries', 'admistration', 'irs', 'c17'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_34
  WTF: {'type', 'dim'} {'emi', 'hv'}
topic_35
  WTF: {'doityourselfers', 'know'} {'kirlian', 'krillean'}
topic_36
  WTF: {'worse', 'dangerous', 'germany'} {'fatti', 'femine', 'calverts'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_37
  WTF: {'computational', 'fax', 'genetic'} {'siggraph', 'bethesda', 'sigkids'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_38
  WTF: {'horizontal', 'sound', 'glass'} {'emerson', 'hifi', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_39
  WTF: {'orthogonal', 'faster', 'clock', 'cpu', 'sets'} {'uvax', 'vlsi', 'vax', 'risc', 'cisc'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_40
  WTF: {'patentable', 'backand', '0099', 'vending'} {'cocacola', 'cola', 'unpatentable', 'pepsi'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_41
  WTF: {'tradition', 'years'} {'olympia', 'joe'}
topic_42
  WTF: {'pads', 'addition', 'combo', 'version', 'stabilized'} {'t4', 'energiam', 't4centaur', 'russia', 'salyut'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_43
  WTF: {'screen', 'correct', 'trick'} {'robbinsgreat', 'supercharging', 'judd'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_44
  WTF: {'guy', 'nicht', 'alle', 'deluded', 'pinks', '881', 'st', 'lunacy'} {'conspiratortm', 'thedoge', 'turc', 'hoffnung', 'koph', 'zeuge', 'dobbsapproved', 'condupes'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_45
  WTF: {'promote'} {'fenholt'}
topic_46
  WTF: {'trinomials', '0n', 'tp', '644', 'mm', 'pw', 'mj', 'ma', 'm1', 'u0', 'mf', 'mh'} {'p6', 'm3', 'm9', 'lu', 'm0', 'm5', 'o3', 'm6', 'pnospsxop8f', 'mw', 'e8', 'mx'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_47
  WTF: {'bars', 'law', 'way', 'leg', 'strings', 'nick'} {'wales', 'karr', 'coterill', 'england', 'barnstaple', 'roberts'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_48
  WTF: {'mcguirecsutexasedu', 'ccs'} {'edgetacalculator', 'bridgend'}
topic_49
  WTF: {'17yearolds', 'orchestra'} {'dahmer', 'theresa'}
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f4fe871e100>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
  WTF: {'like'} {'stephanopoulos'}
topic_3
  WTF: {'vs'} {'nhl'}
topic_4
topic_5
  WTF: {'candida', 'surrender', 'dont'} {'hiv', 'n3jxp', 'gordon'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_6
topic_7
  WTF: {'news'} {'o157h7'}
topic_8
topic_9
  WTF: {'ottoman', 'children', 'muslim', 'government', 'saw', 'started'} {'armenia', 'azerbaijan', 'armenians', 'sumgait', 'armenian', 'turks'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_10
  WTF: {'driver'} {'bj200'}
topic_11
  WTF: {'CDROMCATZIP', 'ringleaders', 'CSCSTD00385', 'dragdrop', 'NikeCajun', '8800CS', '5152940082', 'taxation', 'Epilepsy', 'knowlege', '1795', '207556000', 'toolbox', 'effortsall', 'L2PMABGZ7VAZV0PZRI'} {''}
  WTF?!?!? 15
topic_12
  WTF: {'mail'} {'ripem'}
topic_13
topic_14
  WTF: {'living'} {'hotelco'}
topic_15
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_16
topic_17
topic_18
  WTF: {'porsche'} {'supra'}
topic_19
  WTF: {'analytic', '02106chopinudeledu', 'vol', 'copyright', 'manual', 'writing'} {'vernor', 'dune', 'hogan', 'baen', 'gibson', 'vinge'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_20
  WTF: {'use', '250'} {'irwin', 'mactools'}
topic_21
  WTF: {'ray', 'motif'} {'rsi', 'r3'}
topic_22
  WTF: {'grayscales', 'market', 'properties', 'thanks', 'particular'} {'ocr', 'dexxa', 'mustek', 'scanman', 'paintbrush'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_23
  WTF: {'try', 'card'} {'sb', 'microsofts'}
topic_24
topic_25
  WTF: {'6174940565', 'fourdcom'} {'reids', '1493'}
topic_26
topic_27
topic_28
  WTF: {'aside'} {'darius'}
topic_29
  WTF: {'engineers', 'participants', 'tutorial', 'conference'} {'mellon', 'japan', 'carnegie', 'jstmp'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_30
  WTF: {'bang', 'forget', 'trillion'} {'alice', 'douglas', 'adams'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_31
  WTF: {'regards', 'stripped'} {'sehari', 'babak'}
topic_32
  WTF: {'directors', 'folks', 'rode', 'articles'} {'ama', 'moa', 'bmwmoa', 'mc'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_33
  WTF: {'list', 'utter', 'jobs', 'military'} {'registries', 'admistration', 'irs', 'c17'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_34
  WTF: {'type', 'dim'} {'emi', 'hv'}
topic_35
  WTF: {'doityourselfers', 'know'} {'kirlian', 'krillean'}
topic_36
  WTF: {'worse', 'dangerous', 'germany'} {'fatti', 'femine', 'calverts'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_37
  WTF: {'computational', 'fax', 'genetic'} {'siggraph', 'bethesda', 'sigkids'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_38
  WTF: {'horizontal', 'sound', 'glass'} {'emerson', 'hifi', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_39
  WTF: {'orthogonal', 'faster', 'clock', 'cpu', 'sets'} {'uvax', 'vlsi', 'vax', 'risc', 'cisc'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_40
  WTF: {'patentable', 'backand', '0099', 'vending'} {'cocacola', 'cola', 'unpatentable', 'pepsi'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_41
  WTF: {'tradition', 'years'} {'olympia', 'joe'}
topic_42
  WTF: {'pads', 'addition', 'combo', 'version', 'stabilized'} {'t4', 'energiam', 't4centaur', 'russia', 'salyut'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_43
  WTF: {'screen', 'correct', 'trick'} {'robbinsgreat', 'supercharging', 'judd'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_44
  WTF: {'guy', 'nicht', 'alle', 'deluded', 'pinks', '881', 'st', 'lunacy'} {'conspiratortm', 'thedoge', 'turc', 'hoffnung', 'koph', 'zeuge', 'dobbsapproved', 'condupes'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_45
  WTF: {'promote'} {'fenholt'}
topic_46
  WTF: {'trinomials', '0n', 'tp', '644', 'mm', 'pw', 'mj', 'ma', 'm1', 'u0', 'mf', 'mh'} {'p6', 'm3', 'm9', 'lu', 'm0', 'm5', 'o3', 'm6', 'pnospsxop8f', 'mw', 'e8', 'mx'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_47
  WTF: {'bars', 'law', 'way', 'leg', 'strings', 'nick'} {'wales', 'karr', 'coterill', 'england', 'barnstaple', 'roberts'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_48
  WTF: {'mcguirecsutexasedu', 'ccs'} {'edgetacalculator', 'bridgend'}
topic_49
  WTF: {'17yearolds', 'orchestra'} {'dahmer', 'theresa'}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f4fd47f7040>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f4fff2d8d60>}
{'perplexity': 51077.3046875, 'coherence_20': 1.7715224163439087, 'diversity_euclidean': 0.09346308489731138, 'diversity_jensenshannon': 0.7162411373906441, 'diversity_hellinger': 0.8429558467094194, 'diversity_cosine': 0.822035664024149, 'fair_ppl_free': 2070.597900390625, 'fair_ppl_fix': 50503.26171875, 'unfair_ppl_banklike': 51077.3046875}
{'num_topics': 51, 'num_common_words': 59415, 'num_model_words': 114951, 'num_bt_words': 97541, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 16, 'lost_bt': 1, 'lost_model': 15}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}]}
16
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
topic_3
  WTF: {'vs'} {'nhl'}
topic_4
topic_5
  WTF: {'candida', 'surrender', 'dont'} {'hiv', 'n3jxp', 'gordon'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_6
topic_7
  WTF: {'book', 'news'} {'o157h7', 'anania'}
topic_8
  WTF: {'ottoman', 'children', 'muslim', 'government', 'saw', 'started'} {'armenia', 'azerbaijan', 'armenians', 'sumgait', 'armenian', 'turks'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_9
  WTF: {'quality'} {'bj200'}
topic_10
  WTF: {'NikeDeacon', 'CDROMCATZIP', '8800CS', 'CSCSTD00385', 'dragdrop', 'NikeCajun', '5152940082', 'recollection', 'taxation', '1795', '207556000', 'toolbox', 'effortsall', 'L2PMABGZ7VAZV0PZRI'} {''}
  WTF?!?!? 14
topic_11
topic_12
  WTF: {'football', 'adventure', '35'} {'snes', 'cdi', 'sega'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_13
topic_14
  WTF: {'declutch'} {'caltrans'}
topic_15
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_16
topic_17
topic_18
  WTF: {'insisting', 'chemicals'} {'shafer', 'cato'}
topic_19
  WTF: {'hotels'} {'hotelco'}
topic_20
  WTF: {'analytic', '02106chopinudeledu', 'vol', 'copyright', 'manual', 'writing'} {'vernor', 'dune', 'baen', 'gibson', 'vinge', 'petrucci'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_21
topic_22
  WTF: {'difference', 'people', 'pay'} {'heydt', 'moody', 'vip'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_23
  WTF: {'use', 'hotel'} {'bahamas', 'tuscon'}
topic_24
  WTF: {'server'} {'r3'}
topic_25
topic_26
  WTF: {'centigrade', 'requisition', 'eabu288orionoacuciedu', 'hundredths'} {'asthmatics', 'avagadros', 'bridgend', 'nottoodistant'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_27
  WTF: {'doityourselfers', 'know'} {'kirlian', 'krillean'}
topic_28
topic_29
  WTF: {'restriction', 'wilt', 'oriental', 'love', 'magic', 'law', 'organization', 'superior', 'groups', 'invoke', 'members', 'bookstore', 'words'} {'rosae', 'amorc', 'crowley', 'crucis', 'reuss', 'rosicrucian', 'masonic', 'oto', 'orientis', 'lewis', 'frater', 'templi', 'ordo'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_30
  WTF: {'regards', 'stripped'} {'sehari', 'babak'}
topic_31
  WTF: {'49er', 'mit', 'nick'} {'quincy', 'cambridge', 'sept'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_32
  WTF: {'list', 'utter', 'jobs', 'military'} {'registries', 'admistration', 'irs', 'c17'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_33
topic_34
  WTF: {'height', 'tunnel', 'm4', 'bending'} {'rsi', 'm3', 'm5', 'mw'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_35
  WTF: {'theory'} {'alice'}
topic_36
  WTF: {'worse', 'dangerous', 'germany'} {'fatti', 'femine', 'calverts'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_37
  WTF: {'hardware', 'left', 'internet'} {'localtalk', 'munich', 'null'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_38
  WTF: {'uuencode', 'ioccc'} {'eofnotok', 'xvoid'}
topic_39
  WTF: {'patentable', 'patchmaking', 'remixed', 'vending'} {'cocacola', 'cola', 'yerazunis', 'pepsi'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_40
  WTF: {'somethin', 'memorable', 'trench', 'changing', 'hes'} {'dykstra', 'yankess', 'ballad', 'subterranean', 'anime'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_41
  WTF: {'mach'} {'ses'}
topic_42
  WTF: {'horrendously', 'hermesmeritedu', 'dkmillerunixgubcca', '128196128234', 'dleungeeubcca'} {'sivesh', 'pradhaanrebelsb', 'sprintnet', 'ncsa', 'tocserve'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_43
  WTF: {'pads', 'addition', 'combo', 'version', 'stabilized'} {'t4', 'energiam', 't4centaur', 'russia', 'salyut'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_44
  WTF: {'screen', 'correct', 'trick'} {'robbinsgreat', 'supercharging', 'judd'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_45
  WTF: {'ground', 'powers', 'glass'} {'emerson', 'hifi', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_46
  WTF: {'promote'} {'fenholt'}
topic_47
  WTF: {'carrier', 'circuitry'} {'100mhz', 'ecl'}
topic_48
  WTF: {'mr', 'oddly', 'nazism', 'moments', 'ya', 'hell', 'utilize', 'dem'} {'timucin', 'yo', 'turc', 'srinivas', 'hoffnung', 'koph', 'zeuge', 'davidssons'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_49
  WTF: {'school'} {'robbie'}
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f4fe879e100>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
topic_3
  WTF: {'vs'} {'nhl'}
topic_4
topic_5
  WTF: {'candida', 'surrender', 'dont'} {'hiv', 'n3jxp', 'gordon'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_6
topic_7
  WTF: {'book', 'news'} {'o157h7', 'anania'}
topic_8
  WTF: {'ottoman', 'children', 'muslim', 'government', 'saw', 'started'} {'armenia', 'azerbaijan', 'armenians', 'sumgait', 'armenian', 'turks'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_9
  WTF: {'quality'} {'bj200'}
topic_10
  WTF: {'NikeDeacon', 'CDROMCATZIP', '8800CS', 'CSCSTD00385', 'dragdrop', 'NikeCajun', '5152940082', 'recollection', 'taxation', '1795', '207556000', 'toolbox', 'effortsall', 'L2PMABGZ7VAZV0PZRI'} {''}
  WTF?!?!? 14
topic_11
topic_12
  WTF: {'football', 'adventure', '35'} {'snes', 'cdi', 'sega'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_13
topic_14
  WTF: {'declutch'} {'caltrans'}
topic_15
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_16
topic_17
topic_18
  WTF: {'insisting', 'chemicals'} {'shafer', 'cato'}
topic_19
  WTF: {'hotels'} {'hotelco'}
topic_20
  WTF: {'analytic', '02106chopinudeledu', 'vol', 'copyright', 'manual', 'writing'} {'vernor', 'dune', 'baen', 'gibson', 'vinge', 'petrucci'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_21
topic_22
  WTF: {'difference', 'people', 'pay'} {'heydt', 'moody', 'vip'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_23
  WTF: {'use', 'hotel'} {'bahamas', 'tuscon'}
topic_24
  WTF: {'server'} {'r3'}
topic_25
topic_26
  WTF: {'centigrade', 'requisition', 'eabu288orionoacuciedu', 'hundredths'} {'asthmatics', 'avagadros', 'bridgend', 'nottoodistant'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_27
  WTF: {'doityourselfers', 'know'} {'kirlian', 'krillean'}
topic_28
topic_29
  WTF: {'restriction', 'wilt', 'oriental', 'love', 'magic', 'law', 'organization', 'superior', 'groups', 'invoke', 'members', 'bookstore', 'words'} {'rosae', 'amorc', 'crowley', 'crucis', 'reuss', 'rosicrucian', 'masonic', 'oto', 'orientis', 'lewis', 'frater', 'templi', 'ordo'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_30
  WTF: {'regards', 'stripped'} {'sehari', 'babak'}
topic_31
  WTF: {'49er', 'mit', 'nick'} {'quincy', 'cambridge', 'sept'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_32
  WTF: {'list', 'utter', 'jobs', 'military'} {'registries', 'admistration', 'irs', 'c17'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_33
topic_34
  WTF: {'height', 'tunnel', 'm4', 'bending'} {'rsi', 'm3', 'm5', 'mw'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_35
  WTF: {'theory'} {'alice'}
topic_36
  WTF: {'worse', 'dangerous', 'germany'} {'fatti', 'femine', 'calverts'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_37
  WTF: {'hardware', 'left', 'internet'} {'localtalk', 'munich', 'null'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_38
  WTF: {'uuencode', 'ioccc'} {'eofnotok', 'xvoid'}
topic_39
  WTF: {'patentable', 'patchmaking', 'remixed', 'vending'} {'cocacola', 'cola', 'yerazunis', 'pepsi'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_40
  WTF: {'somethin', 'memorable', 'trench', 'changing', 'hes'} {'dykstra', 'yankess', 'ballad', 'subterranean', 'anime'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_41
  WTF: {'mach'} {'ses'}
topic_42
  WTF: {'horrendously', 'hermesmeritedu', 'dkmillerunixgubcca', '128196128234', 'dleungeeubcca'} {'sivesh', 'pradhaanrebelsb', 'sprintnet', 'ncsa', 'tocserve'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_43
  WTF: {'pads', 'addition', 'combo', 'version', 'stabilized'} {'t4', 'energiam', 't4centaur', 'russia', 'salyut'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_44
  WTF: {'screen', 'correct', 'trick'} {'robbinsgreat', 'supercharging', 'judd'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_45
  WTF: {'ground', 'powers', 'glass'} {'emerson', 'hifi', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_46
  WTF: {'promote'} {'fenholt'}
topic_47
  WTF: {'carrier', 'circuitry'} {'100mhz', 'ecl'}
topic_48
  WTF: {'mr', 'oddly', 'nazism', 'moments', 'ya', 'hell', 'utilize', 'dem'} {'timucin', 'yo', 'turc', 'srinivas', 'hoffnung', 'koph', 'zeuge', 'davidssons'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_49
  WTF: {'school'} {'robbie'}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f5028561340>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f4fe5f0a5b0>}
{'perplexity': 118120.890625, 'coherence_20': 1.8380368870647277, 'diversity_euclidean': 0.0923483764403073, 'diversity_jensenshannon': 0.7225713807820531, 'diversity_hellinger': 0.8516574932975256, 'diversity_cosine': 0.8354409005451546, 'fair_ppl_free': 2080.804931640625, 'fair_ppl_fix': 116616.2890625, 'unfair_ppl_banklike': 118120.890625}
{'num_topics': 51, 'num_common_words': 59415, 'num_model_words': 114951, 'num_bt_words': 97541, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 15, 'lost_bt': 1, 'lost_model': 14}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}]}
17
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
topic_3
  WTF: {'vs'} {'nhl'}
topic_4
topic_5
  WTF: {'candida', 'surrender', 'dont'} {'hiv', 'n3jxp', 'gordon'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_6
topic_7
  WTF: {'land'} {'stephanopoulos'}
topic_8
  WTF: {'discussion'} {'o157h7'}
topic_9
  WTF: {'ottoman', 'children', 'muslim', 'government', 'saw', 'started'} {'armenia', 'azerbaijan', 'armenians', 'sumgait', 'armenian', 'turks'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_10
  WTF: {'scanner'} {'bj200'}
topic_11
  WTF: {'just', 'like'} {'caligiuri', 'enviroleague'}
topic_12
  WTF: {'CDROMCATZIP', 'Guideline', 'dragdrop', 'recollection', 'taxation', '1795', 'knowlege', 'toolbox', 'effortsall', 'monthly', 'strobe', 'CSCSTD00385', 'NikeCajun', '8800CS', '5152940082', '207556000', 'JH2SC281XPM100187', 'L2PMABGZ7VAZV0PZRI'} {''}
  WTF?!?!? 18
topic_13
topic_14
  WTF: {'cars'} {'caltrans'}
topic_15
topic_16
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_17
topic_18
topic_19
  WTF: {'driving'} {'supra'}
topic_20
  WTF: {'analytic', '02106chopinudeledu', 'vol', 'email', 'copyright', 'writing'} {'vernor', 'dune', 'hogan', 'baen', 'gibson', 'vinge'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_21
  WTF: {'insisting', 'chemicals'} {'shafer', 'cato'}
topic_22
  WTF: {'use', '250'} {'irwin', 'mactools'}
topic_23
  WTF: {'j3davidstudentbusinessuwoca', 'practive', 'fulllength', 'official'} {'ets', 'selkeforgive', 'testno', 'gre'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_24
  WTF: {'intrinsics'} {'r3'}
topic_25
topic_26
  WTF: {'restriction', 'wilt', 'oriental', 'love', 'magic', 'law', 'organization', 'superior', 'groups', 'invoke', 'members', 'bookstore', 'words'} {'rosae', 'amorc', 'crowley', 'crucis', 'reuss', 'rosicrucian', 'masonic', 'jose', 'oto', 'orientis', 'frater', 'templi', 'ordo'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_27
  WTF: {'programming', 'cs', 'students', 'andrew'} {'mellon', 'japan', 'carnegie', 'jstmp'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_28
  WTF: {'mesur', 'solve', 'envoy', 'typeset', 'printing', 'wild', 'russian', 'famous'} {'armenia', 'persians', 'iosef', 'shirak', 'tyukhik', 'anania', 'armenian', 'orbeli'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_29
  WTF: {'doityourselfers', 'know'} {'kirlian', 'krillean'}
topic_30
topic_31
topic_32
  WTF: {'aside'} {'darius'}
topic_33
  WTF: {'regards', 'stripped'} {'sehari', 'babak'}
topic_34
  WTF: {'waxed', 'stuff', 'molding'} {'glaze', 'meguiars', 'mcquires'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_35
  WTF: {'cute'} {'heydt'}
topic_36
  WTF: {'CDROMCATZIP', 'Guideline', 'dragdrop', 'recollection', 'taxation', '1795', 'knowlege', 'effortsall', 'toolbox', 'strobe', 'CSCSTD00385', 'NikeCajun', '8800CS', '5152940082', '207556000', 'JH2SC281XPM100187', 'L2PMABGZ7VAZV0PZRI'} {''}
  WTF?!?!? 17
topic_37
  WTF: {'list', 'utter', 'jobs', 'military'} {'registries', 'admistration', 'irs', 'c17'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_38
  WTF: {'49er', 'mit', 'nick'} {'quincy', 'cambridge', 'sept'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_39
topic_40
  WTF: {'theory'} {'alice'}
topic_41
  WTF: {'power', 'company', 'launch'} {'tripoli', 'hpr', 'faa'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_42
  WTF: {'worse', 'dangerous', 'germany'} {'fatti', 'femine', 'calverts'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_43
  WTF: {'computational', 'fax', 'genetic'} {'siggraph', 'bethesda', 'sigkids'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_44
  WTF: {'trinomials', '0n', '644', 'mm', 'pw', 'mj', 'm1', 'ma', 'u0', 'mf', 'et', 'mh'} {'p6', 'm3', 'gh', 'm9', 'm0', 'm5', 'o3', 'm6', 'pnospsxop8f', 'mw', 'e8', 'mx'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_45
  WTF: {'pads', 'addition', 'combo', 'version', 'stabilized'} {'t4', 'energiam', 't4centaur', 'russia', 'salyut'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_46
  WTF: {'played'} {'fenholt'}
topic_47
  WTF: {'audio', 'returned', 'problem'} {'emerson', 'hifi', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_48
  WTF: {'merciless', 'infringing', 'discreet'} {'crah', 'yerazunis', 'cola'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_49
  WTF: {'dleungeeubcca', '17500'} {'vax', 'dastar'}
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f4fe86e3370>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
topic_3
  WTF: {'vs'} {'nhl'}
topic_4
topic_5
  WTF: {'candida', 'surrender', 'dont'} {'hiv', 'n3jxp', 'gordon'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_6
topic_7
  WTF: {'land'} {'stephanopoulos'}
topic_8
  WTF: {'discussion'} {'o157h7'}
topic_9
  WTF: {'ottoman', 'children', 'muslim', 'government', 'saw', 'started'} {'armenia', 'azerbaijan', 'armenians', 'sumgait', 'armenian', 'turks'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_10
  WTF: {'scanner'} {'bj200'}
topic_11
  WTF: {'just', 'like'} {'caligiuri', 'enviroleague'}
topic_12
  WTF: {'CDROMCATZIP', 'Guideline', 'dragdrop', 'recollection', 'taxation', '1795', 'knowlege', 'toolbox', 'effortsall', 'monthly', 'strobe', 'CSCSTD00385', 'NikeCajun', '8800CS', '5152940082', '207556000', 'JH2SC281XPM100187', 'L2PMABGZ7VAZV0PZRI'} {''}
  WTF?!?!? 18
topic_13
topic_14
  WTF: {'cars'} {'caltrans'}
topic_15
topic_16
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_17
topic_18
topic_19
  WTF: {'driving'} {'supra'}
topic_20
  WTF: {'analytic', '02106chopinudeledu', 'vol', 'email', 'copyright', 'writing'} {'vernor', 'dune', 'hogan', 'baen', 'gibson', 'vinge'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_21
  WTF: {'insisting', 'chemicals'} {'shafer', 'cato'}
topic_22
  WTF: {'use', '250'} {'irwin', 'mactools'}
topic_23
  WTF: {'j3davidstudentbusinessuwoca', 'practive', 'fulllength', 'official'} {'ets', 'selkeforgive', 'testno', 'gre'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_24
  WTF: {'intrinsics'} {'r3'}
topic_25
topic_26
  WTF: {'restriction', 'wilt', 'oriental', 'love', 'magic', 'law', 'organization', 'superior', 'groups', 'invoke', 'members', 'bookstore', 'words'} {'rosae', 'amorc', 'crowley', 'crucis', 'reuss', 'rosicrucian', 'masonic', 'jose', 'oto', 'orientis', 'frater', 'templi', 'ordo'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_27
  WTF: {'programming', 'cs', 'students', 'andrew'} {'mellon', 'japan', 'carnegie', 'jstmp'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_28
  WTF: {'mesur', 'solve', 'envoy', 'typeset', 'printing', 'wild', 'russian', 'famous'} {'armenia', 'persians', 'iosef', 'shirak', 'tyukhik', 'anania', 'armenian', 'orbeli'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_29
  WTF: {'doityourselfers', 'know'} {'kirlian', 'krillean'}
topic_30
topic_31
topic_32
  WTF: {'aside'} {'darius'}
topic_33
  WTF: {'regards', 'stripped'} {'sehari', 'babak'}
topic_34
  WTF: {'waxed', 'stuff', 'molding'} {'glaze', 'meguiars', 'mcquires'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_35
  WTF: {'cute'} {'heydt'}
topic_36
  WTF: {'CDROMCATZIP', 'Guideline', 'dragdrop', 'recollection', 'taxation', '1795', 'knowlege', 'effortsall', 'toolbox', 'strobe', 'CSCSTD00385', 'NikeCajun', '8800CS', '5152940082', '207556000', 'JH2SC281XPM100187', 'L2PMABGZ7VAZV0PZRI'} {''}
  WTF?!?!? 17
topic_37
  WTF: {'list', 'utter', 'jobs', 'military'} {'registries', 'admistration', 'irs', 'c17'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_38
  WTF: {'49er', 'mit', 'nick'} {'quincy', 'cambridge', 'sept'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_39
topic_40
  WTF: {'theory'} {'alice'}
topic_41
  WTF: {'power', 'company', 'launch'} {'tripoli', 'hpr', 'faa'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_42
  WTF: {'worse', 'dangerous', 'germany'} {'fatti', 'femine', 'calverts'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_43
  WTF: {'computational', 'fax', 'genetic'} {'siggraph', 'bethesda', 'sigkids'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_44
  WTF: {'trinomials', '0n', '644', 'mm', 'pw', 'mj', 'm1', 'ma', 'u0', 'mf', 'et', 'mh'} {'p6', 'm3', 'gh', 'm9', 'm0', 'm5', 'o3', 'm6', 'pnospsxop8f', 'mw', 'e8', 'mx'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_45
  WTF: {'pads', 'addition', 'combo', 'version', 'stabilized'} {'t4', 'energiam', 't4centaur', 'russia', 'salyut'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_46
  WTF: {'played'} {'fenholt'}
topic_47
  WTF: {'audio', 'returned', 'problem'} {'emerson', 'hifi', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_48
  WTF: {'merciless', 'infringing', 'discreet'} {'crah', 'yerazunis', 'cola'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_49
  WTF: {'dleungeeubcca', '17500'} {'vax', 'dastar'}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f4fe5f0a640>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f4fd47de700>}
{'perplexity': 54311.24609375, 'coherence_20': 1.858334731294445, 'diversity_euclidean': 0.11604627742459599, 'diversity_jensenshannon': 0.7085621995866936, 'diversity_hellinger': 0.8340087461668231, 'diversity_cosine': 0.8193043069770247, 'fair_ppl_free': 2073.733154296875, 'fair_ppl_fix': 53719.2734375, 'unfair_ppl_banklike': 54311.24609375}
{'num_topics': 51, 'num_common_words': 59415, 'num_model_words': 114951, 'num_bt_words': 97541, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 19, 'lost_bt': 1, 'lost_model': 18}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 18, 'lost_bt': 1, 'lost_model': 17}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}]}
18
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
  WTF: {'vs'} {'nhl'}
topic_3
topic_4
  WTF: {'koresh'} {'fbi'}
topic_5
  WTF: {'just', 'enforcement'} {'stephanopoulos', 'nsa'}
topic_6
  WTF: {'research', 'surrender', 'doctors'} {'hiv', 'n3jxp', 'gordon'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_7
topic_8
  WTF: {'votes'} {'o157h7'}
topic_9
  WTF: {'ottoman', 'children', 'muslim', 'government', 'saw', 'started'} {'armenia', 'azerbaijan', 'armenians', 'sumgait', 'armenian', 'turks'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_10
  WTF: {'im'} {'bj200'}
topic_11
  WTF: {'just', 'like'} {'caligiuri', 'enviroleague'}
topic_12
  WTF: {'CDROMCATZIP', 'ringleaders', 'CSCSTD00385', 'dragdrop', 'NikeCajun', '8800CS', '5152940082', 'taxation', 'Epilepsy', 'knowlege', '1795', '207556000', 'toolbox', 'effortsall', 'L2PMABGZ7VAZV0PZRI'} {''}
  WTF?!?!? 15
topic_13
topic_14
  WTF: {'driving'} {'caltrans'}
topic_15
  WTF: {'mail'} {'ripem'}
topic_16
  WTF: {'new'} {'hotelco'}
topic_17
topic_18
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_19
  WTF: {'festival'} {'ishtar'}
topic_20
topic_21
topic_22
  WTF: {'analytic', '02106chopinudeledu', 'vol', 'email', 'copyright', 'writing'} {'vernor', 'dune', 'baen', 'gibson', 'vinge', 'petrucci'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_23
  WTF: {'use', '250'} {'irwin', 'mactools'}
topic_24
  WTF: {'handheld', 'scans', 'grayscales', 'market', 'buy', '400'} {'ocr', 'dexxa', 'mustek', 'scanman', 'paintbrush', 'ocr104zip'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_25
  WTF: {'server'} {'r3'}
topic_26
topic_27
  WTF: {'restriction', 'wilt', 'oriental', 'love', 'magic', 'law', 'organization', 'superior', 'groups', 'invoke', 'members', 'bookstore', 'words'} {'rosae', 'amorc', 'crowley', 'crucis', 'reuss', 'rosicrucian', 'masonic', 'jose', 'oto', 'orientis', 'frater', 'templi', 'ordo'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_28
  WTF: {'try', 'card'} {'sb', 'microsofts'}
topic_29
  WTF: {'posts', 'frontpage', 'gotten', 'articles', 'evil', 'documentaries', 'times', 'auto'} {'id314159', 'mossad', 'tgv', 'mahan', 'mahantgvcom', 'patrick', 'lazarus', 'samuel'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_30
topic_31
topic_32
  WTF: {'races', 'quote', 'fundamentalists', 'pharisees', 'condemning'} {'gen', 'kent', 'ks', 'sandvik', 'malcolm'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_33
  WTF: {'doityourselfers', 'know'} {'kirlian', 'krillean'}
topic_34
  WTF: {'type', 'dim'} {'emi', 'hv'}
topic_35
  WTF: {'cute'} {'heydt'}
topic_36
  WTF: {'regards', 'stripped'} {'sehari', 'babak'}
topic_37
  WTF: {'king', 'forget', 'sort', 'bang', 'guide', 'rule'} {'adams', 'maxima', 'alice', 'altima', 'douglas', 'infiniti'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_38
  WTF: {'immoral', 'pork', 'bases', 'abolished'} {'registries', 'c5s', 'admistration', 'c17'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_39
  WTF: {'university'} {'aiken'}
topic_40
  WTF: {'blows', 'react', 'feeding'} {'emerson', 'hifi', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_41
  WTF: {'participants', 'tuesday', 'mall'} {'quincy', 'kenai', 'amc'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_42
  WTF: {'0099', 'unpatentable', 'backand', 'remixed', 'patchmaking'} {'crah', 'cocacola', 'yerazunis', 'pepsi', 'cola'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_43
  WTF: {'promote'} {'fenholt'}
topic_44
  WTF: {'rumor', 'confirm', 'preliminary'} {'biscayne', 'alabama', 'matson'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_45
  WTF: {'pads', 'addition', 'combo', 'version', 'stabilized'} {'t4', 'energiam', 't4centaur', 'russia', 'salyut'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_46
  WTF: {'distrust', 'flowers', 'airports'} {'subgenii', 'barnum', 'bahamas'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_47
  WTF: {'trinomials', '0n', 'tp', '644', 'mm', 'pw', 'mj', 'ma', 'm1', 'u0', 'mf', 'mh'} {'p6', 'm3', 'm9', 'lu', 'm0', 'm5', 'o3', 'm6', 'pnospsxop8f', 'mw', 'e8', 'mx'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_48
  WTF: {'tongs', 'trust', 'alveoli'} {'co2', 'cyclically', 'oxygenco2'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_49
  WTF: {'live', 'tons', 'balls', 'boston', 'energy', 'division', 'insisting', 'nations'} {'bozeman', 'auth', 'wilkes', 'barre', 'creek', 'olson', 'epa', 'rochester'}
  WTF?!?!? 8
  WTF?!?!? 8
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f4feaf962b0>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
  WTF: {'vs'} {'nhl'}
topic_3
topic_4
  WTF: {'koresh'} {'fbi'}
topic_5
  WTF: {'just', 'enforcement'} {'stephanopoulos', 'nsa'}
topic_6
  WTF: {'research', 'surrender', 'doctors'} {'hiv', 'n3jxp', 'gordon'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_7
topic_8
  WTF: {'votes'} {'o157h7'}
topic_9
  WTF: {'ottoman', 'children', 'muslim', 'government', 'saw', 'started'} {'armenia', 'azerbaijan', 'armenians', 'sumgait', 'armenian', 'turks'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_10
  WTF: {'im'} {'bj200'}
topic_11
  WTF: {'just', 'like'} {'caligiuri', 'enviroleague'}
topic_12
  WTF: {'CDROMCATZIP', 'ringleaders', 'CSCSTD00385', 'dragdrop', 'NikeCajun', '8800CS', '5152940082', 'taxation', 'Epilepsy', 'knowlege', '1795', '207556000', 'toolbox', 'effortsall', 'L2PMABGZ7VAZV0PZRI'} {''}
  WTF?!?!? 15
topic_13
topic_14
  WTF: {'driving'} {'caltrans'}
topic_15
  WTF: {'mail'} {'ripem'}
topic_16
  WTF: {'new'} {'hotelco'}
topic_17
topic_18
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_19
  WTF: {'festival'} {'ishtar'}
topic_20
topic_21
topic_22
  WTF: {'analytic', '02106chopinudeledu', 'vol', 'email', 'copyright', 'writing'} {'vernor', 'dune', 'baen', 'gibson', 'vinge', 'petrucci'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_23
  WTF: {'use', '250'} {'irwin', 'mactools'}
topic_24
  WTF: {'handheld', 'scans', 'grayscales', 'market', 'buy', '400'} {'ocr', 'dexxa', 'mustek', 'scanman', 'paintbrush', 'ocr104zip'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_25
  WTF: {'server'} {'r3'}
topic_26
topic_27
  WTF: {'restriction', 'wilt', 'oriental', 'love', 'magic', 'law', 'organization', 'superior', 'groups', 'invoke', 'members', 'bookstore', 'words'} {'rosae', 'amorc', 'crowley', 'crucis', 'reuss', 'rosicrucian', 'masonic', 'jose', 'oto', 'orientis', 'frater', 'templi', 'ordo'}
  WTF?!?!? 13
  WTF?!?!? 13
topic_28
  WTF: {'try', 'card'} {'sb', 'microsofts'}
topic_29
  WTF: {'posts', 'frontpage', 'gotten', 'articles', 'evil', 'documentaries', 'times', 'auto'} {'id314159', 'mossad', 'tgv', 'mahan', 'mahantgvcom', 'patrick', 'lazarus', 'samuel'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_30
topic_31
topic_32
  WTF: {'races', 'quote', 'fundamentalists', 'pharisees', 'condemning'} {'gen', 'kent', 'ks', 'sandvik', 'malcolm'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_33
  WTF: {'doityourselfers', 'know'} {'kirlian', 'krillean'}
topic_34
  WTF: {'type', 'dim'} {'emi', 'hv'}
topic_35
  WTF: {'cute'} {'heydt'}
topic_36
  WTF: {'regards', 'stripped'} {'sehari', 'babak'}
topic_37
  WTF: {'king', 'forget', 'sort', 'bang', 'guide', 'rule'} {'adams', 'maxima', 'alice', 'altima', 'douglas', 'infiniti'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_38
  WTF: {'immoral', 'pork', 'bases', 'abolished'} {'registries', 'c5s', 'admistration', 'c17'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_39
  WTF: {'university'} {'aiken'}
topic_40
  WTF: {'blows', 'react', 'feeding'} {'emerson', 'hifi', 'vcr'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_41
  WTF: {'participants', 'tuesday', 'mall'} {'quincy', 'kenai', 'amc'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_42
  WTF: {'0099', 'unpatentable', 'backand', 'remixed', 'patchmaking'} {'crah', 'cocacola', 'yerazunis', 'pepsi', 'cola'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_43
  WTF: {'promote'} {'fenholt'}
topic_44
  WTF: {'rumor', 'confirm', 'preliminary'} {'biscayne', 'alabama', 'matson'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_45
  WTF: {'pads', 'addition', 'combo', 'version', 'stabilized'} {'t4', 'energiam', 't4centaur', 'russia', 'salyut'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_46
  WTF: {'distrust', 'flowers', 'airports'} {'subgenii', 'barnum', 'bahamas'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_47
  WTF: {'trinomials', '0n', 'tp', '644', 'mm', 'pw', 'mj', 'ma', 'm1', 'u0', 'mf', 'mh'} {'p6', 'm3', 'm9', 'lu', 'm0', 'm5', 'o3', 'm6', 'pnospsxop8f', 'mw', 'e8', 'mx'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_48
  WTF: {'tongs', 'trust', 'alveoli'} {'co2', 'cyclically', 'oxygenco2'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_49
  WTF: {'live', 'tons', 'balls', 'boston', 'energy', 'division', 'insisting', 'nations'} {'bozeman', 'auth', 'wilkes', 'barre', 'creek', 'olson', 'epa', 'rochester'}
  WTF?!?!? 8
  WTF?!?!? 8

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f4fe867c370>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f4fff9ae0d0>}
{'perplexity': 50541.65234375, 'coherence_20': 1.624470774078839, 'diversity_euclidean': 0.08948721698638877, 'diversity_jensenshannon': 0.7012300702899817, 'diversity_hellinger': 0.8242278158420516, 'diversity_cosine': 0.8028027202558022, 'fair_ppl_free': 2048.618408203125, 'fair_ppl_fix': 49880.9296875, 'unfair_ppl_banklike': 50541.65234375}
{'num_topics': 51, 'num_common_words': 59415, 'num_model_words': 114951, 'num_bt_words': 97541, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 16, 'lost_bt': 1, 'lost_model': 15}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 26, 'lost_bt': 13, 'lost_model': 13}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}]}
19
Num model topics: 51.

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

Check before fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
  WTF: {'vs'} {'nhl'}
topic_3
topic_4
  WTF: {'banks', 'candida', 'surrender'} {'hiv', 'n3jxp', 'gordon'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_5
topic_6
  WTF: {'votes'} {'o157h7'}
topic_7
  WTF: {'ottoman', 'children', 'muslim', 'government', 'saw', 'started'} {'armenia', 'azerbaijan', 'armenians', 'sumgait', 'armenian', 'turks'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_8
  WTF: {'driver'} {'bj200'}
topic_9
  WTF: {'like', 'sin'} {'caligiuri', 'enviroleague'}
topic_10
  WTF: {'CDROMCATZIP', 'ringleaders', 'CSCSTD00385', 'dragdrop', 'NikeCajun', '8800CS', '5152940082', 'taxation', 'Epilepsy', 'knowlege', '1795', '207556000', 'toolbox', 'effortsall', 'L2PMABGZ7VAZV0PZRI'} {''}
  WTF?!?!? 15
topic_11
topic_12
  WTF: {'mail'} {'ripem'}
topic_13
  WTF: {'working', 'dont'} {'myers', 'stephanopoulos'}
topic_14
  WTF: {'declutch'} {'caltrans'}
topic_15
topic_16
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_17
topic_18
topic_19
topic_20
topic_21
  WTF: {'analytic', '02106chopinudeledu', 'vol', 'copyright', 'manual', 'writing'} {'vernor', 'hogan', 'baen', 'gibson', 'vinge', 'petrucci'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_22
topic_23
  WTF: {'pickup', '250'} {'irwin', 'mactools'}
topic_24
  WTF: {'intrinsics'} {'r3'}
topic_25
  WTF: {'handheld', 'scans', 'grayscales', 'market', 'buy', '400'} {'ocr', 'dexxa', 'mustek', 'scanman', 'paintbrush', 'ocr104zip'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_26
  WTF: {'rule'} {'alice'}
topic_27
  WTF: {'etiquette', 'difference'} {'heydt', 'vip'}
topic_28
  WTF: {'year', 'cs', 'participants', 'tutorial'} {'mellon', 'japan', 'carnegie', 'jstmp'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_29
  WTF: {'doityourselfers', 'know'} {'kirlian', 'krillean'}
topic_30
  WTF: {'people', 'english'} {'ishtar', 'bede'}
topic_31
topic_32
  WTF: {'immoral', 'pork', 'bases', 'abolished'} {'registries', 'c5s', 'admistration', 'c17'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_33
  WTF: {'mesur', 'solve', 'envoy', 'typeset', 'printing', 'wild', 'russian', 'famous'} {'armenia', 'persians', 'iosef', 'shirak', 'tyukhik', 'anania', 'armenian', 'orbeli'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_34
  WTF: {'aside'} {'darius'}
topic_35
  WTF: {'regards', 'stripped'} {'sehari', 'babak'}
topic_36
  WTF: {'directors', 'folks', 'rode', 'articles'} {'ama', 'moa', 'bmwmoa', 'mc'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_37
  WTF: {'49er', 'mit', 'nick'} {'quincy', 'cambridge', 'sept'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_38
  WTF: {'frequencies'} {'emi'}
topic_39
  WTF: {'audio', 'capacitor', 'elect', 'cords', 'sure'} {'hv', 'emerson', 'hifi', 'vcr', 'goldstar'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_40
  WTF: {'safety', 'launch', 'class'} {'tripoli', 'hpr', 'faa'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_41
  WTF: {'best', 'tcpip', 'route'} {'localtalk', 'phonenet', 'workgroups'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_42
  WTF: {'facilities', 'big', 'combo', 'launch', 'version', 'stabilized'} {'t4', 'energiam', 'joe', 't4centaur', 'russia', 'salyut'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_43
  WTF: {'hiden'} {'scotyy'}
topic_44
  WTF: {'computational', 'fax', 'genetic'} {'siggraph', 'bethesda', 'sigkids'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_45
  WTF: {'commercials', 'major', 'uploaded'} {'ipas', 'nwres2dll', 'v200'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_46
  WTF: {'trinomials', '0n', 'tp', '644', 'mm', 'pw', 'mj', 'ma', 'm1', 'u0', 'mf', 'mh'} {'p6', 'm3', 'm9', 'lu', 'm0', 'm5', 'o3', 'm6', 'pnospsxop8f', 'mw', 'e8', 'mx'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_47
  WTF: {'mr', 'oddly', 'nazism', 'moments', 'ya', 'hell', 'utilize', 'dem'} {'timucin', 'yo', 'turc', 'srinivas', 'hoffnung', 'koph', 'zeuge', 'davidssons'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_48
  WTF: {'product', '300', 'release', 'commercial', 'allright', 'preproduction'} {'pong', '3do', '3dos', 'pacman', 'visicalc', 'ces'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_49
  WTF: {'fiansovamcom', 'reseacher', '6144594256', 'transliterated', 'kutuzovavenusitebserpukhovsu'} {'ussrsu', 'iki', 'belorusskaya', 'kremlin', 'moscow'}
  WTF?!?!? 5
  WTF?!?!? 5
{'fix': <__main__.FastFixPhiRegularizer object at 0x7f4fe87321c0>}
Check after fit:
Skipping background topic: background_1.
topic_0
topic_1
topic_2
  WTF: {'vs'} {'nhl'}
topic_3
topic_4
  WTF: {'banks', 'candida', 'surrender'} {'hiv', 'n3jxp', 'gordon'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_5
topic_6
  WTF: {'votes'} {'o157h7'}
topic_7
  WTF: {'ottoman', 'children', 'muslim', 'government', 'saw', 'started'} {'armenia', 'azerbaijan', 'armenians', 'sumgait', 'armenian', 'turks'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_8
  WTF: {'driver'} {'bj200'}
topic_9
  WTF: {'like', 'sin'} {'caligiuri', 'enviroleague'}
topic_10
  WTF: {'CDROMCATZIP', 'ringleaders', 'CSCSTD00385', 'dragdrop', 'NikeCajun', '8800CS', '5152940082', 'taxation', 'Epilepsy', 'knowlege', '1795', '207556000', 'toolbox', 'effortsall', 'L2PMABGZ7VAZV0PZRI'} {''}
  WTF?!?!? 15
topic_11
topic_12
  WTF: {'mail'} {'ripem'}
topic_13
  WTF: {'working', 'dont'} {'myers', 'stephanopoulos'}
topic_14
  WTF: {'declutch'} {'caltrans'}
topic_15
topic_16
  WTF: {'pot', 'social'} {'lsd', 'dea'}
topic_17
topic_18
topic_19
topic_20
topic_21
  WTF: {'analytic', '02106chopinudeledu', 'vol', 'copyright', 'manual', 'writing'} {'vernor', 'hogan', 'baen', 'gibson', 'vinge', 'petrucci'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_22
topic_23
  WTF: {'pickup', '250'} {'irwin', 'mactools'}
topic_24
  WTF: {'intrinsics'} {'r3'}
topic_25
  WTF: {'handheld', 'scans', 'grayscales', 'market', 'buy', '400'} {'ocr', 'dexxa', 'mustek', 'scanman', 'paintbrush', 'ocr104zip'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_26
  WTF: {'rule'} {'alice'}
topic_27
  WTF: {'etiquette', 'difference'} {'heydt', 'vip'}
topic_28
  WTF: {'year', 'cs', 'participants', 'tutorial'} {'mellon', 'japan', 'carnegie', 'jstmp'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_29
  WTF: {'doityourselfers', 'know'} {'kirlian', 'krillean'}
topic_30
  WTF: {'people', 'english'} {'ishtar', 'bede'}
topic_31
topic_32
  WTF: {'immoral', 'pork', 'bases', 'abolished'} {'registries', 'c5s', 'admistration', 'c17'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_33
  WTF: {'mesur', 'solve', 'envoy', 'typeset', 'printing', 'wild', 'russian', 'famous'} {'armenia', 'persians', 'iosef', 'shirak', 'tyukhik', 'anania', 'armenian', 'orbeli'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_34
  WTF: {'aside'} {'darius'}
topic_35
  WTF: {'regards', 'stripped'} {'sehari', 'babak'}
topic_36
  WTF: {'directors', 'folks', 'rode', 'articles'} {'ama', 'moa', 'bmwmoa', 'mc'}
  WTF?!?!? 4
  WTF?!?!? 4
topic_37
  WTF: {'49er', 'mit', 'nick'} {'quincy', 'cambridge', 'sept'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_38
  WTF: {'frequencies'} {'emi'}
topic_39
  WTF: {'audio', 'capacitor', 'elect', 'cords', 'sure'} {'hv', 'emerson', 'hifi', 'vcr', 'goldstar'}
  WTF?!?!? 5
  WTF?!?!? 5
topic_40
  WTF: {'safety', 'launch', 'class'} {'tripoli', 'hpr', 'faa'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_41
  WTF: {'best', 'tcpip', 'route'} {'localtalk', 'phonenet', 'workgroups'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_42
  WTF: {'facilities', 'big', 'combo', 'launch', 'version', 'stabilized'} {'t4', 'energiam', 'joe', 't4centaur', 'russia', 'salyut'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_43
  WTF: {'hiden'} {'scotyy'}
topic_44
  WTF: {'computational', 'fax', 'genetic'} {'siggraph', 'bethesda', 'sigkids'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_45
  WTF: {'commercials', 'major', 'uploaded'} {'ipas', 'nwres2dll', 'v200'}
  WTF?!?!? 3
  WTF?!?!? 3
topic_46
  WTF: {'trinomials', '0n', 'tp', '644', 'mm', 'pw', 'mj', 'ma', 'm1', 'u0', 'mf', 'mh'} {'p6', 'm3', 'm9', 'lu', 'm0', 'm5', 'o3', 'm6', 'pnospsxop8f', 'mw', 'e8', 'mx'}
  WTF?!?!? 12
  WTF?!?!? 12
topic_47
  WTF: {'mr', 'oddly', 'nazism', 'moments', 'ya', 'hell', 'utilize', 'dem'} {'timucin', 'yo', 'turc', 'srinivas', 'hoffnung', 'koph', 'zeuge', 'davidssons'}
  WTF?!?!? 8
  WTF?!?!? 8
topic_48
  WTF: {'product', '300', 'release', 'commercial', 'allright', 'preproduction'} {'pong', '3do', '3dos', 'pacman', 'visicalc', 'ces'}
  WTF?!?!? 6
  WTF?!?!? 6
topic_49
  WTF: {'fiansovamcom', 'reseacher', '6144594256', 'transliterated', 'kutuzovavenusitebserpukhovsu'} {'ussrsu', 'iki', 'belorusskaya', 'kremlin', 'moscow'}
  WTF?!?!? 5
  WTF?!?!? 5

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f4fe87a0c10>}

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f4fff1b0790>}
{'perplexity': 51453.03125, 'coherence_20': 1.8614283177346875, 'diversity_euclidean': 0.09703550253599807, 'diversity_jensenshannon': 0.7157048806945295, 'diversity_hellinger': 0.8429020420523214, 'diversity_cosine': 0.8348490275412973, 'fair_ppl_free': 2086.357177734375, 'fair_ppl_fix': 50791.91015625, 'unfair_ppl_banklike': 51453.03125}
{'num_topics': 51, 'num_common_words': 59415, 'num_model_words': 114951, 'num_bt_words': 97541, 'top_diffs': [{'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 16, 'lost_bt': 1, 'lost_model': 15}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 0, 'lost_bt': 0, 'lost_model': 0}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 4, 'lost_bt': 2, 'lost_model': 2}, {'total': 8, 'lost_bt': 4, 'lost_model': 4}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 2, 'lost_bt': 1, 'lost_model': 1}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 6, 'lost_bt': 3, 'lost_model': 3}, {'total': 24, 'lost_bt': 12, 'lost_model': 12}, {'total': 16, 'lost_bt': 8, 'lost_model': 8}, {'total': 12, 'lost_bt': 6, 'lost_model': 6}, {'total': 10, 'lost_bt': 5, 'lost_model': 5}]}

In [44]:
1

1

In [41]:
top_words

{'background_1': [['cancer', 0.008057708533386602],
  ['water', 0.007760658430890415],
  ['like', 0.007687364739919708],
  ['use', 0.007593121473417186],
  ['new', 0.007265890475525043],
  ['dont', 0.00702699541366676],
  ['know', 0.006963602650395305],
  ['people', 0.006623638500866859],
  ['just', 0.006608341035706224],
  ['using', 0.0066068898896937366],
  ['need', 0.006286250186181283],
  ['im', 0.006283685583312624],
  ['available', 0.006213303035868458],
  ['does', 0.006203679176134194],
  ['time', 0.005982497796075295],
  ['university', 0.005981672387529071],
  ['research', 0.005774139956588921],
  ['file', 0.005738888636068809],
  ['windows', 0.005642742429057228],
  ['software', 0.005600596756622336]],
 'topic_0': [['use', 0.01101325961080856],
  ['drive', 0.010813409061598096],
  ['windows', 0.010725423960779022],
  ['card', 0.009703823403302435],
  ['thanks', 0.00878767133308823],
  ['db', 0.008722930426813996],
  ['like', 0.008045514356091481],
  ['problem', 0.008033831208459793],
  ['dos', 0.007943067969980499],
  ['using', 0.007923046295015397],
  ['window', 0.007799030977934483],
  ['does', 0.007744919804674457],
  ['disk', 0.007527724646109574],
  ['software', 0.007348474795268882],
  ['file', 0.007294183146623759],
  ['version', 0.007291102400089863],
  ['available', 0.0069964243651159715],
  ['know', 0.006963753655548734],
  ['image', 0.006941938592572132],
  ['im', 0.006847659459848954]],
 'topic_1': [['god', 0.022735740909988693],
  ['jesus', 0.01500025296639783],
  ['people', 0.011202611082939587],
  ['bible', 0.010444602967076264],
  ['israel', 0.010327939096668579],
  ['believe', 0.009686958176957904],
  ['say', 0.00925183906808454],
  ['does', 0.008870198639664276],
  ['think', 0.008762542138335726],
  ['faith', 0.008483600732191074],
  ['just', 0.008388264062873166],
  ['christian', 0.008372606220133017],
  ['church', 0.008265742512851504],
  ['dont', 0.00804657045650185],
  ['israeli', 0.007854687669654995],
  ['jews', 0.007755501631748072],
  ['life', 0.007741072089088458],
  ['know', 0.007717181628426884],
  ['christians', 0.007595047440313416],
  ['true', 0.007585525948223027]],
 'topic_2': [['gun', 0.014432418942837807],
  ['government', 0.014429393176395302],
  ['people', 0.012513712858938686],
  ['key', 0.012279503820981225],
  ['president', 0.011341746731330154],
  ['chip', 0.009859737331124843],
  ['mr', 0.009812133659680127],
  ['think', 0.009730438909132829],
  ['clipper', 0.009598352598862473],
  ['dont', 0.00932349995826966],
  ['encryption', 0.00902606080286986],
  ['law', 0.00892702489623322],
  ['right', 0.008766422521893752],
  ['guns', 0.008638403645688112],
  ['know', 0.007866731056597824],
  ['just', 0.00781829591564057],
  ['going', 0.00769309341727737],
  ['keys', 0.007583852399770859],
  ['stephanopoulos', 0.007159135316064632],
  ['file', 0.007023445627374933]],
 'topic_3': [['team', 0.02045290686864594],
  ['game', 0.018635956890172847],
  ['season', 0.014816657371295592],
  ['games', 0.014618387728262917],
  ['play', 0.013942062164086761],
  ['players', 0.013843717097209227],
  ['hockey', 0.013368093933181226],
  ['year', 0.012890378222610082],
  ['league', 0.01155946945986847],
  ['550', 0.011465745047129538],
  ['25', 0.011421477578336793],
  ['10', 0.010973676930302401],
  ['teams', 0.01090232796990708],
  ['win', 0.010381276239908704],
  ['nhl', 0.009716928103876154],
  ['period', 0.009408174613858813],
  ['pts', 0.00928012762626315],
  ['la', 0.008817917690855543],
  ['12', 0.008777072490914778],
  ['11', 0.008421465773418065]],
 'topic_4': [['car', 0.02940954890194002],
  ['bike', 0.021703325318024214],
  ['cars', 0.014680459684583688],
  ['engine', 0.012197746307491064],
  ['just', 0.01191257465547765],
  ['like', 0.01113885075080835],
  ['dod', 0.011108536470947202],
  ['good', 0.009633371704393523],
  ['miles', 0.00949468127072855],
  ['ride', 0.009006525449440066],
  ['oil', 0.008762224105940946],
  ['dont', 0.008650161971593325],
  ['motorcycle', 0.008616852843900073],
  ['bikes', 0.00838544226569494],
  ['riding', 0.00815310753313575],
  ['know', 0.008112285333040065],
  ['tires', 0.00802464302664339],
  ['new', 0.007785471572067295],
  ['speed', 0.0077318175046609695],
  ['right', 0.007632381465931753]],
 'topic_5': [['patients', 0.01784293880810059],
  ['msg', 0.016506763683498914],
  ['medical', 0.015517794445125433],
  ['health', 0.014753991181132868],
  ['disease', 0.014059082675034038],
  ['food', 0.014056173784039],
  ['doctor', 0.01300807796977656],
  ['pain', 0.012950478032094183],
  ['treatment', 0.010507495556755227],
  ['medicine', 0.010260591630028227],
  ['gordon', 0.010118374652820327],
  ['gebcadredslpittedu', 0.009373957472742452],
  ['n3jxp', 0.009351345588385577],
  ['chastity', 0.009351345588385577],
  ['shameful', 0.00928530576468523],
  ['intellect', 0.009242698897292567],
  ['skepticism', 0.009101663146841132],
  ['hiv', 0.008988322289465714],
  ['banks', 0.008932750360259867],
  ['doctors', 0.008929754637515068]],
 'topic_6': [['space', 0.04014314354538466],
  ['launch', 0.020272137948184818],
  ['nasa', 0.017875777603393744],
  ['lunar', 0.015823899272451532],
  ['orbit', 0.015315754409848647],
  ['shuttle', 0.013961806046614069],
  ['satellite', 0.013849404355923712],
  ['mission', 0.012108589755356393],
  ['moon', 0.012097660535249646],
  ['earth', 0.011415730005080688],
  ['spacecraft', 0.011344982100034135],
  ['mars', 0.009686825597317865],
  ['solar', 0.009438619832991648],
  ['rocket', 0.008793133452608421],
  ['satellites', 0.00876912633020354],
  ['data', 0.008766631484813684],
  ['flight', 0.008621943003918716],
  ['station', 0.008561712458997959],
  ['missions', 0.00807465490761791],
  ['planetary', 0.007979504738370368]],
 'topic_7': [['email', 0.0197962742429453],
  ['tobacco', 0.01898196053726096],
  ['list', 0.017874640804797292],
  ['send', 0.016839726600173216],
  ['address', 0.015452077048120839],
  ['health', 0.015328868140533528],
  ['smokeless', 0.014948276718831938],
  ['requests', 0.014681900226691079],
  ['newsgroup', 0.013012630956694396],
  ['coli', 0.01261605632387023],
  ['group', 0.012382374351570902],
  ['mailing', 0.011670479343376528],
  ['o157h7', 0.011596391815073801],
  ['mail', 0.011243967198644676],
  ['posts', 0.010579495734694166],
  ['1993', 0.00967669334820437],
  ['article', 0.009157957162947292],
  ['voting', 0.009038444057119939],
  ['anania', 0.008855649631433945],
  ['book', 0.008599969055421762]],
 'topic_8': [['armenian', 0.034831062458411076],
  ['armenians', 0.03256514921739366],
  ['turkish', 0.030661231206927576],
  ['said', 0.01775991230808626],
  ['turkey', 0.01773791075382837],
  ['people', 0.017645397894322346],
  ['turks', 0.015973393405700934],
  ['armenia', 0.015337526236451635],
  ['genocide', 0.013826668842879327],
  ['greek', 0.01307625615393705],
  ['azerbaijan', 0.012841241629550984],
  ['went', 0.011628977424260398],
  ['didnt', 0.011251605078741914],
  ['azerbaijani', 0.01085299307373059],
  ['jews', 0.010459302503851521],
  ['apartment', 0.010397975528322681],
  ['sumgait', 0.010339063638627709],
  ['came', 0.010247262314221095],
  ['russian', 0.009996844596951047],
  ['killed', 0.009723962458135066]],
 'topic_9': [['printer', 0.09665767764149757],
  ['fonts', 0.056751003503752666],
  ['font', 0.04913363059579713],
  ['print', 0.04413846575392549],
  ['laser', 0.034744000759320263],
  ['ink', 0.03464693708575205],
  ['printers', 0.034162602897211555],
  ['hp', 0.03295278758187674],
  ['windows', 0.02931022759547412],
  ['tt', 0.027742260994266216],
  ['truetype', 0.02761946134564539],
  ['postscript', 0.02658763098632685],
  ['deskjet', 0.026251969561008198],
  ['toner', 0.021407069642274658],
  ['using', 0.02059099263875292],
  ['printing', 0.01923524450396781],
  ['bj200', 0.018461094307756134],
  ['characters', 0.017251186892396683],
  ['ps', 0.017083327508989853],
  ['use', 0.016799638501498553]],
 'topic_10': [['gay', 0.04956629432762478],
  ['homosexual', 0.04072987857317622],
  ['sex', 0.038308869695609364],
  ['homosexuality', 0.036313891050223826],
  ['homosexuals', 0.03358591283616071],
  ['sexual', 0.030466392401118172],
  ['men', 0.02984533361286807],
  ['people', 0.025916658300959898],
  ['gays', 0.023802640085177657],
  ['orientation', 0.019761833871816934],
  ['dont', 0.014671575680829524],
  ['enviroleague', 0.013919764236981599],
  ['heterosexual', 0.013710959240019511],
  ['caligiuri', 0.01325343611098888],
  ['male', 0.012974453197689069],
  ['love', 0.01185802756475115],
  ['think', 0.01169142759404302],
  ['promiscuous', 0.010914594444343784],
  ['believe', 0.010663317511582514],
  ['straight', 0.010199055095570477]],
 'topic_11': [['ditto', 2.3210301313986728],
  ['hello', 1.059472257767196],
  ['ites', 0.9786799993369897],
  ['hi', 0.8804906036472108],
  ['huh', 0.6443049838103396],
  ['', 1e-05],
  ['', 1e-05],
  ['', 1e-05],
  ['', 1e-05],
  ['', 1e-05],
  ['', 1e-05],
  ['', 1e-05],
  ['', 1e-05],
  ['', 1e-05],
  ['', 1e-05],
  ['', 1e-05],
  ['', 1e-05],
  ['', 1e-05],
  ['', 1e-05],
  ['', 1e-05]],
 'topic_12': [['morality', 0.09336639635711544],
  ['moral', 0.08239577507750469],
  ['objective', 0.07933314297426095],
  ['hudson', 0.037383415406192874],
  ['immoral', 0.027266522892476115],
  ['values', 0.0270250699672453],
  ['animals', 0.024395341471998865],
  ['science', 0.021021432898935658],
  ['society', 0.020674283290238515],
  ['people', 0.02065055053660517],
  ['think', 0.02063622766227407],
  ['morals', 0.019817415939464497],
  ['species', 0.016943722973616536],
  ['relative', 0.015316596868164178],
  ['accept', 0.015225194310236105],
  ['absolute', 0.015010434296564925],
  ['standard', 0.014290792841274403],
  ['omniscient', 0.014278619514381925],
  ['dont', 0.014106342969429498],
  ['say', 0.013743565352931432]],
 'topic_13': [['blacks', 0.033801255335602624],
  ['crimes', 0.029095019873021363],
  ['crime', 0.027236053325471733],
  ['penalty', 0.025159768761781817],
  ['people', 0.02419478501279717],
  ['capital', 0.02257321573535754],
  ['punishment', 0.021433639123341477],
  ['death', 0.021228949057116545],
  ['cruel', 0.02034043775229184],
  ['slavery', 0.019451844078929525],
  ['rape', 0.01874123997932482],
  ['labor', 0.018624907530282245],
  ['murder', 0.018621906770166504],
  ['society', 0.017503800182397434],
  ['slave', 0.016604391318035084],
  ['states', 0.016443608867295526],
  ['slaves', 0.015657721394486932],
  ['white', 0.014958934887492534],
  ['innocent', 0.014720660739096676],
  ['black', 0.014536290196017133]],
 'topic_14': [['anonymous', 0.026719785326353777],
  ['privacy', 0.02639215728842958],
  ['key', 0.02451345827256883],
  ['internet', 0.024277483719916077],
  ['encryption', 0.023065113980524205],
  ['ripem', 0.02088316011630779],
  ['security', 0.018234546882289628],
  ['des', 0.0170725715930008],
  ['anonymity', 0.016980871509910535],
  ['information', 0.01652261051797071],
  ['mail', 0.01641509853977029],
  ['cryptography', 0.013668085319751002],
  ['message', 0.013282258127068658],
  ['computer', 0.01309875260698201],
  ['electronic', 0.012628501306045063],
  ['rsa', 0.012593203516185796],
  ['users', 0.012076354612617208],
  ['use', 0.012069902891350995],
  ['public', 0.011650655713011453],
  ['cipher', 0.01126177076551416]],
 'topic_15': [['phone', 0.10925604686820635],
  ['number', 0.09303485612023249],
  ['dial', 0.09100196183011214],
  ['line', 0.06550754458389581],
  ['led', 0.0521567659643022],
  ['hook', 0.042009108563255286],
  ['onhook', 0.041653584544941856],
  ['telephone', 0.03877131696155984],
  ['lines', 0.035964073294713204],
  ['current', 0.03501181708874153],
  ['company', 0.033515823540168986],
  ['telco', 0.02980832961681022],
  ['al', 0.027198254789413435],
  ['green', 0.026588775119461925],
  ['offhook', 0.026530481909737672],
  ['zener', 0.025664119754113455],
  ['yellow', 0.025513966938501862],
  ['draw', 0.024140703567532704],
  ['disconnected', 0.023978980318925813],
  ['numbers', 0.023733584543501083]],
 'topic_16': [['drugs', 0.15135782258450772],
  ['drug', 0.09477374660858663],
  ['marijuana', 0.04083570693935278],
  ['cocaine', 0.033801409680563194],
  ['alcohol', 0.033425494544880835],
  ['says', 0.03039224058505293],
  ['lsd', 0.029402196687538695],
  ['war', 0.028702282876477858],
  ['legalization', 0.024950830708165936],
  ['kids', 0.024204777661320828],
  ['people', 0.023964697728933625],
  ['use', 0.021787880677914383],
  ['crack', 0.021622314942348664],
  ['cigarettes', 0.020203696891214335],
  ['heroin', 0.019322867635639247],
  ['legal', 0.017224416305561468],
  ['eighthgraders', 0.01678275493801055],
  ['survey', 0.015655239005153504],
  ['dea', 0.015012690280310973],
  ['abuse', 0.014998134314958621]],
 'topic_17': [['water', 0.12097064912336701],
  ['cooling', 0.11385166828322271],
  ['steam', 0.10336630111517771],
  ['towers', 0.0889304886016402],
  ['plants', 0.08749405604353006],
  ['nuclear', 0.06131436624702879],
  ['temperature', 0.05599355564024398],
  ['heat', 0.05093627937891555],
  ['fossil', 0.05012219868506786],
  ['plant', 0.047397401432419835],
  ['tower', 0.04107774790809719],
  ['turbine', 0.038125417691983216],
  ['power', 0.0379482721687427],
  ['cool', 0.03475809438377455],
  ['hot', 0.033387231706941474],
  ['reactor', 0.031095456825110047],
  ['hotwell', 0.030619313330320655],
  ['condenser', 0.030619313330320655],
  ['boiler', 0.030619313330320655],
  ['river', 0.029857111674027062]],
 'topic_18': [['marriage', 0.1743543889771801],
  ['married', 0.11024076563063415],
  ['ceremony', 0.06180218648118128],
  ['church', 0.047902817198998686],
  ['commitment', 0.04633085452723728],
  ['divorce', 0.04353919305124655],
  ['couple', 0.04136246755087852],
  ['marry', 0.03885930159562138],
  ['priest', 0.03334896465977409],
  ['couples', 0.02924132449006202],
  ['vows', 0.02876261380618049],
  ['wedding', 0.027592991833368972],
  ['state', 0.02541742283594765],
  ['god', 0.023978167080622857],
  ['eyes', 0.023729958424137443],
  ['marriages', 0.02247178344885572],
  ['civil', 0.02220839416322698],
  ['gods', 0.022003772841193057],
  ['intercourse', 0.01948103431649802],
  ['clergyman', 0.01789078794407489]],
 'topic_19': [['widget', 0.019938582423666036],
  ['keyboard', 0.019087323779462546],
  ['available', 0.017136044546949704],
  ['data', 0.016684248051640944],
  ['window', 0.01384862142196314],
  ['resource', 0.013656627628324718],
  ['graphics', 0.013588272241799423],
  ['3d', 0.01322766043020179],
  ['xt', 0.01273243562229051],
  ['visual', 0.012233686545267129],
  ['information', 0.011942262426100582],
  ['ftp', 0.011572985509308723],
  ['image', 0.011084797642772756],
  ['application', 0.010922067968732494],
  ['converter', 0.010744506467593389],
  ['motif', 0.010565741841971095],
  ['widgets', 0.010376080731988337],
  ['faq', 0.010369269606731405],
  ['file', 0.010141353600685795],
  ['server', 0.010054009140580834]],
 'topic_20': [['books', 0.061012292242406625],
  ['book', 0.060394173477181276],
  ['vinge', 0.04937333650996899],
  ['chemistry', 0.04852631295457785],
  ['cover', 0.036042007422938616],
  ['vernor', 0.033309713246373926],
  ['gibson', 0.028715926892524075],
  ['paperback', 0.028715926892524075],
  ['trek', 0.028157843111319407],
  ['guide', 0.02606703807892378],
  ['spice', 0.0247979499143826],
  ['baen', 0.0247979499143826],
  ['star', 0.024750989168249634],
  ['edition', 0.024709463203593195],
  ['offer', 0.024121572249756588],
  ['condition', 0.02279615121537978],
  ['good', 0.022449325679775364],
  ['hard', 0.021449511609717947],
  ['dune', 0.020371757939905956],
  ['petrucci', 0.020371757939905956]],
 'topic_21': [['tape', 0.2175458573612331],
  ['tapes', 0.08665673319986392],
  ['backup', 0.0858750262240528],
  ['drive', 0.08126553287204076],
  ['device', 0.05234044261520597],
  ['525', 0.04156668659458964],
  ['marker', 0.0376765181451053],
  ['retrospect', 0.03178696406136263],
  ['holes', 0.028389980123563932],
  ['mactools', 0.02682676140314591],
  ['apple', 0.02610550288334797],
  ['250mb', 0.025950724137154314],
  ['reels', 0.025271250887367768],
  ['irwin', 0.02471610857779519],
  ['bezel', 0.023481644737532812],
  ['faceplate', 0.022870768430413874],
  ['mirror', 0.022766292156795865],
  ['colorado', 0.021200622643947977],
  ['format', 0.02041638809322928],
  ['drives', 0.02029531084537119]],
 'topic_22': [['scanner', 0.1868931606378484],
  ['grayscale', 0.0884242576697168],
  ['dpi', 0.08191970920691105],
  ['scanners', 0.07576769463729228],
  ['logitech', 0.07451795910700355],
  ['scanman', 0.07342826585267626],
  ['ocr', 0.05636121391775837],
  ['256', 0.05310460866743841],
  ['software', 0.0496140395083033],
  ['mustek', 0.04676877872937827],
  ['paintbrush', 0.04405695951160576],
  ['gray', 0.03358330963620953],
  ['recommendations', 0.03358330963620953],
  ['offers', 0.03347313078552056],
  ['hand', 0.03329702925590537],
  ['purchasing', 0.0331590966261438],
  ['resoltuion', 0.032614284116363544],
  ['satam', 0.032614284116363544],
  ['ocr104zip', 0.032614284116363544],
  ['dexxa', 0.032614284116363544]],
 'topic_23': [['42', 0.12320397770009361],
  ['question', 0.08643669601121107],
  ['answer', 0.06332817999696236],
  ['universe', 0.05543750185991143],
  ['alice', 0.054396184619453496],
  ['discovered', 0.05201514057684578],
  ['101010', 0.0512099999653076],
  ['tea', 0.050974984090184305],
  ['fortytwo', 0.04953771952538178],
  ['douglas', 0.04495151049839579],
  ['adams', 0.04411208382525372],
  ['said', 0.03430333184983186],
  ['times', 0.03314604838995274],
  ['infiniti', 0.03302514635025452],
  ['number', 0.03265071060456362],
  ['life', 0.032164379184391294],
  ['binary', 0.03214265018333842],
  ['altima', 0.03145396246657398],
  ['maxima', 0.030856672348385152],
  ['deep', 0.030624199987277834]],
 'topic_24': [['cview', 0.34093143716506324],
  ['temp', 0.186592812708786],
  ['files', 0.08608033867107605],
  ['directory', 0.0841567408229412],
  ['file', 0.0796414270470449],
  ['disk', 0.06159077792066409],
  ['floppy', 0.06002180218129212],
  ['dir', 0.054440745982640926],
  ['bit', 0.054345734027237406],
  ['root', 0.04707985781152725],
  ['data', 0.046794166325577646],
  ['variable', 0.040249057428863866],
  ['places', 0.03930225300060414],
  ['0byte', 0.03914719997347959],
  ['create', 0.03749016198231947],
  ['drive', 0.035137031496937234],
  ['invokes', 0.03478906622271354],
  ['tmp', 0.034265807505881214],
  ['bugs', 0.034079316783013965],
  ['resides', 0.0333743805984558]],
 'topic_25': [['japanese', 0.09934043925335848],
  ['courses', 0.06088150634467759],
  ['university', 0.046984199047290176],
  ['language', 0.04456441757741924],
  ['computer', 0.04244281231722901],
  ['pittsburgh', 0.04220768390324095],
  ['conference', 0.04055351679521142],
  ['intensive', 0.040022963771355904],
  ['engineering', 0.039395724225069394],
  ['june', 0.03933939625997427],
  ['science', 0.036862903982761014],
  ['412', 0.0354639416505141],
  ['program', 0.03522015167720719],
  ['japan', 0.03412172515892259],
  ['tutorial', 0.03407014987050319],
  ['management', 0.03278442814561948],
  ['carnegie', 0.03096625754602371],
  ['mellon', 0.030672525693280325],
  ['jstmp', 0.029635261045804336],
  ['technology', 0.027786413932510357]],
 'topic_26': [['photography', 0.15565647669882351],
  ['kirlian', 0.15017573086756864],
  ['pictures', 0.07948767874143946],
  ['object', 0.0761748304348729],
  ['krillean', 0.068694634101646],
  ['fields', 0.06661524261008585],
  ['energy', 0.06617536938594086],
  ['electric', 0.0478375489834076],
  ['spikes', 0.04398440279878638],
  ['patterns', 0.040172397808318654],
  ['photographed', 0.03665366899898865],
  ['organic', 0.035354742096253604],
  ['aura', 0.03282846893026001],
  ['suppliers', 0.028283793677002882],
  ['plates', 0.02516021822654388],
  ['signature', 0.02508470794752918],
  ['variations', 0.0246310254879721],
  ['appartus', 0.02387024388626804],
  ['informationsupplies', 0.02387024388626804],
  ['auras', 0.02387024388626804]],