In [1]:
import os
import sys

import numpy as np
import scipy

In [2]:
sys.path.insert(0, '../OptimalNumberOfTopics')

In [3]:
import topnum

from topnum.scores.perplexity_score import PerplexityScore
from topnum.scores.diversity_score import DiversityScore, KNOWN_METRICS
from topnum.model_constructor import init_model_from_family, KnownModel, PARAMS_EXPLORED, init_plsa

In [4]:
import artm
from artm import ARTM, Dictionary

import topicnet
from topicnet.cooking_machine.dataset import Dataset
from topicnet.cooking_machine.models import (
    BaseScore as BaseTopicNetScore,
    TopicModel
)
from topicnet.cooking_machine.models.base_regularizer import BaseRegularizer
from topicnet.cooking_machine.models.thetaless_regularizer import (
    dataset2sparse_matrix,
)

from topicnet.cooking_machine.models.topic_model import ARTM_NINE
from topicnet.cooking_machine.models.base_regularizer import BaseRegularizer
from topicnet.viewers.top_documents_viewer import TopDocumentsViewer
from topicnet.viewers.top_tokens_viewer import TopTokensViewer
from topicnet.cooking_machine.model_constructor import (
    add_standard_scores,
    create_default_topics,
    count_vocab_size,
    init_model,
)
from topicnet.cooking_machine.rel_toolbox_lite import (
    count_vocab_size,
    modality_weight_rel2abs,
    transform_regularizer,
)


import numpy as np
import pandas as pd
from pandas import DataFrame
from scipy.spatial.distance import cdist

import os
import tempfile
import warnings
from copy import deepcopy
from typing import Dict, List, Optional

In [5]:
from IPython.display import display, display_html

In [6]:
DATA_FOLDER_PATH = '/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/dataset_manager'

In [7]:
! ls $DATA_FOLDER_PATH

20NG.csv	 MKB10__internals	    RTL_Wiki.csv
20NG__internals  postnauka.csv		    RTL_Wiki_person.csv
api.py		 postnauka__internals	    RTL_Wiki_person__internals
Brown		 postnauka_noow.csv	    ruwiki_good__internals
Brown_BOW.csv	 postnauka_noow__internals  ruwiki_good.txt
Brown_NOOW.csv	 __pycache__		    WikiRef-220
hf		 Reuters		    wiki_ref220_bow.csv
__init__.py	 Reuters_BOW.csv	    wiki_ref220_natural_order.csv
MKB10.csv	 Reuters_NOOW.csv

In [8]:
dataset = Dataset(
    f'{DATA_FOLDER_PATH}/20NG.csv',
)

dataset.get_possible_modalities()

{'@bigram', '@lemmatized'}

In [9]:
MAIN_MODALITY = '@lemmatized'

In [10]:
dataset._data.head()

,Unnamed: 0,raw_text,filenames,target,id,tokenized,lemmatized,bigram,vw_text
id,,,,,,,,,
rec_autos_102994,0,I was wondering if anyone out there could enli...,/home/egorov/scikit_learn_data/20news_home/20n...,7,rec_autos_102994,"[('was', 'VBD'), ('wondering', 'VBG'), ('if', ...","['wonder', 'anyone', 'could', 'enlighten', 'ca...","['wonder_anyone', 'anyone_could', 'sport_car',...",rec_autos_102994 |@lemmatized wonder:1 anyone:...
comp_sys_mac_hardware_51861,1,A fair number of brave souls who upgraded thei...,/home/egorov/scikit_learn_data/20news_home/20n...,4,comp_sys_mac_hardware_51861,"[('fair', 'JJ'), ('number', 'NN'), ('of', 'IN'...","['fair', 'number', 'brave', 'soul', 'upgrade',...","['clock_oscillator', 'please_send', 'top_speed...",comp_sys_mac_hardware_51861 |@lemmatized fair:...
comp_sys_mac_hardware_51879,2,"well folks, my mac plus finally gave up the gh...",/home/egorov/scikit_learn_data/20news_home/20n...,4,comp_sys_mac_hardware_51879,"[('well', 'RB'), ('folks', 'NNS'), ('my', 'PRP...","['well', 'folk', 'mac', 'plus', 'finally', 'gi...","['mac_plus', 'life_way', 'way_back', 'market_n...",comp_sys_mac_hardware_51879 |@lemmatized well:...
comp_graphics_38242,3,\nDo you have Weitek's address/phone number? ...,/home/egorov/scikit_learn_data/20news_home/20n...,1,comp_graphics_38242,"[('do', 'VBP'), ('you', 'PRP'), ('have', 'VB')...","['weitek', 'address', 'phone', 'number', 'like...","['address_phone', 'phone_number', 'number_like...",comp_graphics_38242 |@lemmatized weitek:1 addr...
sci_space_60880,4,"From article <C5owCB.n3p@world.std.com>, by to...",/home/egorov/scikit_learn_data/20news_home/20n...,14,sci_space_60880,"[('from', 'IN'), ('article', 'NN'), ('by', 'IN...","['article', 'tom', 'baker', 'understanding', '...","['system_software', 'thing_check', 'introduce_...",sci_space_60880 |@lemmatized article:1 tom:1 b...

In [11]:
def calc_doc_occurrences(dataset, modality):
    """
    :param n_dw_matrix: sparse document-word matrix, shape is D x W
    :return: sparse matrix of co-occurrences

    doc_occurrences[w1, w2] = the number of the documents
    where there are w1 and w2
    """
    n_dw_matrix = dataset2sparse_matrix(dataset, modality, modalities_to_use=[modality])
    matrix = (scipy.sparse.csc_matrix(n_dw_matrix) > 0).astype(int)
    co_occurrences = matrix.T * matrix

    return co_occurrences.diagonal(), co_occurrences


def create_pmi_top_function(
    doc_occurrences, doc_co_occurrences,
    documents_number, top_sizes,
    topic_indices,
    co_occurrences_smooth=1.
):
    """
    :param doc_occurrences: array of doc occurrences of words
    :param doc_co_occurrences: sparse matrix of doc co-occurrences of words
    :param documents_number: number of the documents
    :param top_sizes: list of top values to calculate top-pmi for
    :param co_occurrences_smooth: constant to smooth co-occurrences in log
    :return: function which takes phi and theta and returns
    pair of two arrays: pmi-s of the tops and ppmi-s of the tops

    pmi[i] - pmi(top of size top_sizes[i])
    ppmi[i] - ppmi(top of size top_sizes[i])

    pmi(words) = sum_{u in words, v in words, u != v}
    log(
        (doc_co_occurrences[u, v] * documents_number + co_occurrences_smooth)
        / doc_occurrences[u] / doc_occurrences[v]
    )

    ppmi(words) = sum_{u in words, v in words, u != v}
    max(log(
        (doc_co_occurrences[u, v] * documents_number + co_occurrences_smooth)
        / doc_occurrences[u] / doc_occurrences[v]
    ), 0)

    """
    def func(phi):
        _T, W = phi.shape
        T = len(topic_indices)

        max_top_size = max(top_sizes)
        topic_pmis, topic_ppmis = dict(), dict()
        pmi, ppmi = np.zeros(max_top_size), np.zeros(max_top_size)
        tops = np.argpartition(phi, -max_top_size, axis=1)[:, -max_top_size:]
        
        for t in topic_indices:
            top = sorted(tops[t], key=lambda w: - phi[t, w])
            print(f'Topic: {t}. Top: {top}')
            co_occurrences = doc_co_occurrences[top, :][:, top].todense()
            occurrences = doc_occurrences[top]
            values = np.log(
                (co_occurrences * documents_number + co_occurrences_smooth)
                / (occurrences[:, np.newaxis] * occurrences[np.newaxis, :] + co_occurrences_smooth)
            )
            diag = np.diag_indices(len(values))
            # values.cumsum(axis=0).cumsum(axis=1)[diag] - values[diag].cumsum()

            current_pmi = np.array(
               values.cumsum(axis=0).cumsum(axis=1)[diag] - values[diag].cumsum()
            ).ravel()
            topic_pmis[t] = current_pmi
            pmi += current_pmi

            values[values < 0.] = 0.
            current_ppmi = np.array(
               values.cumsum(axis=0).cumsum(axis=1)[diag] - values[diag].cumsum()
            ).ravel()
            topic_ppmis[t] = current_ppmi
            ppmi += current_ppmi
            
        sizes = np.arange(2, max_top_size + 1)
        pmi[1:] /= (T * sizes * (sizes - 1))
        ppmi[1:] /= (T * sizes * (sizes - 1))
        indices = np.array(top_sizes) - 1

        for t in topic_indices:
            topic_pmis[t][1:] /= (sizes * (sizes - 1))
            topic_ppmis[t][1:] /= (sizes * (sizes - 1))

        result_topic_pmis = {t: p[indices] for t, p in topic_pmis.items()}
        result_topic_ppmis = {t: p[indices] for t, p in topic_ppmis.items()}

        return pmi[indices], ppmi[indices], result_topic_pmis, result_topic_ppmis

    return func

In [12]:
%%time

occurences, co_occurences = calc_doc_occurrences(dataset, MAIN_MODALITY)

CPU times: user 2.64 s, sys: 130 ms, total: 2.77 s
Wall time: 2.74 s

In [13]:
co_occurences

<52744x52744 sparse matrix of type '<class 'numpy.int64'>'
	with 72331838 stored elements in Compressed Sparse Row format>

In [14]:
calc_pmi = create_pmi_top_function(
    occurences, co_occurences,
    dataset.get_dataset().shape[0], [20],
    topic_indices=[0, 1, 2],
    co_occurrences_smooth=1e-2,
)

In [15]:
class TopTokenCoherence(BaseTopicNetScore):
    def __init__(self, name, func):
        super().__init__()

        self._name = name
        self.calc_pmi = func

    def call(self, model: TopicModel):
        values = self.calc_pmi(model.get_phi_dense()[0].T)

        return values[1]

    def call_by_topic(self, model: TopicModel):
        values = self.calc_pmi(model.get_phi_dense()[0].T)

        return values[3]

In [16]:
def view_model(
        topic_model,
        dataset,
        num_top_tokens: int = 5,
        top_tokens_method: str = 'phi',
        num_topics: Optional[int] = 5,  # we do not want to fill the whole .ipynb notebook with topics...
        ):
    top_tok_viewer = TopTokensViewer(
        topic_model, num_top_tokens=num_top_tokens, method=top_tokens_method
    )
    top_doc_viewer = TopDocumentsViewer(topic_model, dataset=dataset)
    top_docs = top_doc_viewer.view()

    if num_topics is None:
        num_topics = len(topic_model.topic_names)

    for topic_name in topic_model.topic_names[:num_topics]:
        topic_top_toks = top_tok_viewer.to_html(topic_names=[topic_name])
        topic_top_docs = top_docs[topic_name]
        display_html(topic_top_toks, raw=True)
        display(topic_top_docs)

In [17]:
class FastFixPhiRegularizer(BaseRegularizer):
    _VERY_BIG_TAU = 10 ** 9

    def __init__(self, name: str, parent_model, topic_names: List[str]):
        super().__init__(name, tau=self._VERY_BIG_TAU)

        self._topic_names = topic_names
        self._topic_indices = None
        self._parent_model = parent_model

    def grad(self, pwt, nwt):
        # print('Fixing')

        rwt = np.zeros_like(pwt)
        parent_phi = self._parent_model.get_phi()
        
        rwt[:, self._topic_indices] += parent_phi.values[:, self._topic_indices]

        return self.tau * rwt

    def attach(self, model):
        super().attach(model)
        
        phi = self._model.get_phi()
        self._topic_indices = [
            phi.columns.get_loc(topic_name)
            for topic_name in self._topic_names
        ]

In [18]:
class DecorrelatorWithOtherPhiRegularizer(BaseRegularizer):
    def __init__(self, name, tau, topic_names, other_phi):
        super().__init__(name, tau=tau)

        self._topic_names = topic_names
        self._other_phi = other_phi
        self._other_topic_sum = self._other_phi.values.sum(
            axis=1, keepdims=True
        )
        
        self._topic_indices = None
        
    def grad(self, pwt, nwt):
        # print('Decorring')

        rwt = np.zeros_like(pwt)
        rwt[:, self._topic_indices] += (
            pwt.values[:, self._topic_indices] * self._other_topic_sum
        )

        return -1 * self.tau * rwt

    def attach(self, model):
        super().attach(model)
        
        phi = model.get_phi()
        self._topic_indices = [
            phi.columns.get_loc(topic_name)
            for topic_name in self._topic_names
        ]

In [19]:
class DecorrelatorWithOtherPhiRegularizer2(BaseRegularizer):
    def __init__(self, name, tau, topic_names, other_phi, num_iters: Optional[int] = None):
        super().__init__(name, tau=tau)

        self._topic_names = topic_names
        self._other_phi = other_phi
        self._num_iters = num_iters
        self._cur_iter = 0
        
        self._topic_indices = None
        
    def grad(self, pwt, nwt):
        rwt = np.zeros_like(pwt)
        
        if self._num_iters is not None and self._cur_iter >= self._num_iters:
            return rwt

        correlations = cdist(
            self._other_phi.values.T,
            pwt.values[:, self._topic_indices].T,
            lambda u, v: (u * v).sum()
        )
        weighted_other_topics = self._other_phi.values.dot(correlations)

        rwt[:, self._topic_indices] += (
            pwt.values[:, self._topic_indices] * weighted_other_topics
        )
        self._cur_iter += 1

        return -1 * self.tau * rwt

    def attach(self, model):
        super().attach(model)
        
        phi = model.get_phi()
        self._topic_indices = [
            phi.columns.get_loc(topic_name)
            for topic_name in self._topic_names
        ]

In [20]:
NUM_TOPICS = 20  # vary
MAX_NUM_TRAINS = 20
NUM_ITERATIONS = 20
NUM_TOP_TOKENS = 20

In [21]:
def fit_and_compute_scores(model, dataset, custom_regularizers=None):
    print(custom_regularizers)

    model._fit(dataset.get_batch_vectorizer(), num_iterations=NUM_ITERATIONS, custom_regularizers=custom_regularizers)

    score_values = {
        'perplexity': model.scores[f'PerplexityScore{MAIN_MODALITY}'][-1],
    }

    phi = model.get_phi()

    # Currently all topics are taken into account
    target_topic_indices = list(range(NUM_TOPICS))  # phi.columns.get_loc()
    target_topic_names = [phi.columns[i] for i in target_topic_indices]

    top = NUM_TOP_TOKENS
    coherence_score = TopTokenCoherence(
        name=f'coherence_{top}',
        func=create_pmi_top_function(
            occurences, co_occurences,
            dataset.get_dataset().shape[0], [top],
            topic_indices=target_topic_indices,
            co_occurrences_smooth=1e-2,
        )
    )

    value = coherence_score.call(model)
    score_values[coherence_score._name] = value
    topic_coherences = coherence_score.call_by_topic(model)
    topic_coherences = {t: float(v) for t, v in topic_coherences.items()}

    diversity_scores = [
        DiversityScore(
            name=f'diversity_{metric}',
            metric=metric,
            topic_names=target_topic_names,
            class_ids=MAIN_MODALITY,
        )
    
        for metric in KNOWN_METRICS
    ]
    
    for score in diversity_scores:
        value = score.call(model)
        score_values[score._name] = value

    return {
        'scores': score_values,
        'topic_coherences': topic_coherences,
    }

In [22]:
def is_good(coherence):
    # 80 p
    return 1.6095355359760972 <= coherence

def is_bad(coherence):
    # 20 p
    return coherence <= 0.8497888357888863

## Test

In [35]:
model = init_model_from_family(
    family=KnownModel.PLSA,
    dataset=dataset,
    main_modality=MAIN_MODALITY,
    num_topics=NUM_TOPICS,
    seed=2024,
)

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

In [36]:
result = fit_and_compute_scores(model, dataset)

None
Topic: 0. Top: [34687, 23755, 28828, 52105, 29766, 30497, 30086, 29319, 30736, 45004, 31472, 29644, 30490, 24053, 33123, 28701, 47946, 27689, 47238, 35416]
Topic: 1. Top: [28651, 30339, 33036, 39719, 37833, 34089, 29237, 32510, 43571, 29282, 33125, 34317, 29096, 30596, 25706, 17946, 30374, 24315, 21347, 26129]
Topic: 2. Top: [35331, 36195, 40295, 37263, 27624, 30827, 25859, 42454, 31186, 32833, 52105, 31264, 30331, 33654, 32209, 28980, 32028, 47035, 20877, 34724]
Topic: 3. Top: [22893, 43613, 34170, 32833, 32665, 31147, 22254, 20528, 46780, 34317, 39575, 33484, 47812, 29033, 27185, 33123, 29282, 29331, 38446, 31997]
Topic: 4. Top: [30791, 32833, 43613, 44211, 40029, 35657, 35416, 32135, 21123, 32665, 27086, 33123, 39872, 25945, 25943, 19656, 26567, 36303, 28393, 34729]
Topic: 5. Top: [32254, 30220, 26587, 29396, 25783, 29237, 37318, 29386, 36376, 25273, 26627, 22424, 22730, 23396, 24023, 30082, 25212, 34887, 29262, 18394]
Topic: 6. Top: [37154, 31055, 22986, 34085, 30110, 26128, 33941, 43613, 52105, 32833, 29939, 32489, 36334, 28992, 19730, 32665, 27902, 30490, 25902, 25859]
Topic: 7. Top: [34364, 33123, 33036, 26745, 31298, 29282, 31683, 32833, 32510, 33176, 28701, 44121, 24278, 40029, 28695, 29331, 48735, 24160, 33124, 28172]
Topic: 8. Top: [38537, 18311, 30869, 37038, 29116, 31186, 29282, 30339, 32913, 30391, 29237, 25998, 27179, 33036, 26379, 28731, 36483, 28016, 25196, 33176]
Topic: 9. Top: [39575, 38245, 31059, 33484, 28884, 20370, 34409, 29939, 24203, 25911, 28992, 31997, 50360, 49264, 26648, 31759, 22254, 32833, 25289, 43613]
Topic: 10. Top: [29237, 19900, 47238, 30339, 31803, 32510, 33125, 29116, 31186, 34317, 19656, 33047, 29282, 28695, 39625, 33123, 31622, 29902, 29096, 33176]
Topic: 11. Top: [43613, 21915, 26616, 46714, 32665, 32833, 32237, 29791, 34713, 31412, 20141, 29068, 26303, 27323, 16955, 27643, 29998, 27839, 27985, 26776]
Topic: 12. Top: [36383, 29282, 29237, 40999, 29453, 33036, 51040, 32833, 26627, 32510, 33125, 32678, 34014, 30160, 29116, 28695, 27970, 51496, 28016, 20164]
Topic: 13. Top: [33036, 27532, 17905, 30066, 29282, 30339, 45841, 34089, 32510, 34317, 26466, 37833, 33125, 27970, 29331, 30252, 38087, 24317, 33176, 30655]
Topic: 14. Top: [33123, 29282, 33125, 28701, 26745, 33036, 34317, 28995, 29902, 28172, 34871, 32510, 29728, 47812, 22422, 40029, 17194, 33176, 28695, 47238]
Topic: 15. Top: [49838, 32833, 37130, 28100, 29939, 34287, 31855, 28019, 33826, 37692, 19656, 33036, 30597, 40029, 30627, 26190, 28999, 34531, 28095, 51400]
Topic: 16. Top: [30339, 47238, 33036, 34317, 30252, 33123, 29237, 31298, 26745, 29684, 33124, 29096, 29282, 17231, 33176, 33125, 31397, 17194, 28695, 29902]
Topic: 17. Top: [29385, 32833, 32942, 28820, 29453, 26627, 36874, 44833, 35189, 29939, 37553, 28019, 29282, 29304, 25902, 46187, 42639, 41012, 50360, 33036]
Topic: 18. Top: [32833, 33036, 18601, 28585, 25025, 29939, 29875, 20164, 42030, 51997, 30152, 37974, 30444, 29960, 33176, 35416, 47079, 18692, 29331, 26239]
Topic: 19. Top: [27066, 50488, 28068, 27624, 35842, 21650, 26483, 45761, 21394, 25284, 52456, 31147, 32545, 39575, 17853, 30119, 20370, 46583, 31759, 28701]
Topic: 0. Top: [34687, 23755, 28828, 52105, 29766, 30497, 30086, 29319, 30736, 45004, 31472, 29644, 30490, 24053, 33123, 28701, 47946, 27689, 47238, 35416]
Topic: 1. Top: [28651, 30339, 33036, 39719, 37833, 34089, 29237, 32510, 43571, 29282, 33125, 34317, 29096, 30596, 25706, 17946, 30374, 24315, 21347, 26129]
Topic: 2. Top: [35331, 36195, 40295, 37263, 27624, 30827, 25859, 42454, 31186, 32833, 52105, 31264, 30331, 33654, 32209, 28980, 32028, 47035, 20877, 34724]
Topic: 3. Top: [22893, 43613, 34170, 32833, 32665, 31147, 22254, 20528, 46780, 34317, 39575, 33484, 47812, 29033, 27185, 33123, 29282, 29331, 38446, 31997]
Topic: 4. Top: [30791, 32833, 43613, 44211, 40029, 35657, 35416, 32135, 21123, 32665, 27086, 33123, 39872, 25945, 25943, 19656, 26567, 36303, 28393, 34729]
Topic: 5. Top: [32254, 30220, 26587, 29396, 25783, 29237, 37318, 29386, 36376, 25273, 26627, 22424, 22730, 23396, 24023, 30082, 25212, 34887, 29262, 18394]
Topic: 6. Top: [37154, 31055, 22986, 34085, 30110, 26128, 33941, 43613, 52105, 32833, 29939, 32489, 36334, 28992, 19730, 32665, 27902, 30490, 25902, 25859]
Topic: 7. Top: [34364, 33123, 33036, 26745, 31298, 29282, 31683, 32833, 32510, 33176, 28701, 44121, 24278, 40029, 28695, 29331, 48735, 24160, 33124, 28172]
Topic: 8. Top: [38537, 18311, 30869, 37038, 29116, 31186, 29282, 30339, 32913, 30391, 29237, 25998, 27179, 33036, 26379, 28731, 36483, 28016, 25196, 33176]
Topic: 9. Top: [39575, 38245, 31059, 33484, 28884, 20370, 34409, 29939, 24203, 25911, 28992, 31997, 50360, 49264, 26648, 31759, 22254, 32833, 25289, 43613]
Topic: 10. Top: [29237, 19900, 47238, 30339, 31803, 32510, 33125, 29116, 31186, 34317, 19656, 33047, 29282, 28695, 39625, 33123, 31622, 29902, 29096, 33176]
Topic: 11. Top: [43613, 21915, 26616, 46714, 32665, 32833, 32237, 29791, 34713, 31412, 20141, 29068, 26303, 27323, 16955, 27643, 29998, 27839, 27985, 26776]
Topic: 12. Top: [36383, 29282, 29237, 40999, 29453, 33036, 51040, 32833, 26627, 32510, 33125, 32678, 34014, 30160, 29116, 28695, 27970, 51496, 28016, 20164]
Topic: 13. Top: [33036, 27532, 17905, 30066, 29282, 30339, 45841, 34089, 32510, 34317, 26466, 37833, 33125, 27970, 29331, 30252, 38087, 24317, 33176, 30655]
Topic: 14. Top: [33123, 29282, 33125, 28701, 26745, 33036, 34317, 28995, 29902, 28172, 34871, 32510, 29728, 47812, 22422, 40029, 17194, 33176, 28695, 47238]
Topic: 15. Top: [49838, 32833, 37130, 28100, 29939, 34287, 31855, 28019, 33826, 37692, 19656, 33036, 30597, 40029, 30627, 26190, 28999, 34531, 28095, 51400]
Topic: 16. Top: [30339, 47238, 33036, 34317, 30252, 33123, 29237, 31298, 26745, 29684, 33124, 29096, 29282, 17231, 33176, 33125, 31397, 17194, 28695, 29902]
Topic: 17. Top: [29385, 32833, 32942, 28820, 29453, 26627, 36874, 44833, 35189, 29939, 37553, 28019, 29282, 29304, 25902, 46187, 42639, 41012, 50360, 33036]
Topic: 18. Top: [32833, 33036, 18601, 28585, 25025, 29939, 29875, 20164, 42030, 51997, 30152, 37974, 30444, 29960, 33176, 35416, 47079, 18692, 29331, 26239]
Topic: 19. Top: [27066, 50488, 28068, 27624, 35842, 21650, 26483, 45761, 21394, 25284, 52456, 31147, 32545, 39575, 17853, 30119, 20370, 46583, 31759, 28701]

In [28]:
result['topic_coherences']

{0: 1.3237581790853068,
 1: 1.2829826937052067,
 2: 1.490025133820413,
 3: 0.7857971478575373,
 4: 1.3135809496335025,
 5: 3.3417329208687425,
 6: 1.860396670636734,
 7: 0.6210007920538984,
 8: 1.5062729063927354,
 9: 1.5163815087267571,
 10: 0.8543499618407997,
 11: 1.5498711537678034,
 12: 0.9686454389395989,
 13: 0.896240503636927,
 14: 0.5476823963231512,
 15: 1.0634088355376492,
 16: 0.65465596884585,
 17: 1.5921116878827575,
 18: 0.9202599190166817,
 19: 1.1071412340594873}

In [101]:
good_topic_indices = [
    t for t, c in result['topic_coherences'].items() if is_good(c)  # c >= HIGH_COHERENCE_THRESHOLD
]
bad_topic_indices = [
    t for t, c in result['topic_coherences'].items() if is_bad(c)  # c <= LOW_COHERENCE_THRESHOLD
]

phi = model.get_phi()
good_topic_names = [phi.columns[t] for t in good_topic_indices]
bad_topic_names = [phi.columns[t] for t in bad_topic_indices]

In [102]:
len(good_topic_indices), len(bad_topic_indices)

(3, 4)

In [103]:
good_topic_names, bad_topic_names

(['topic_3', 'topic_11', 'topic_15'],
 ['topic_8', 'topic_13', 'topic_18', 'topic_19'])

In [99]:
phi['topic_11'].sort_values(ascending=False)[:20]

modality  token
@word     россия          0.008695
          война           0.008296
          государство     0.008275
          власть          0.007372
          страна          0.006107
          германия        0.005124
          политический    0.005033
          сталин          0.004779
          стать           0.004387
          революция       0.004353
          политика        0.003816
          франция         0.003641
          партия          0.003525
          военный         0.003510
          сторона         0.003133
          русский         0.003102
          должный         0.003097
          демократия      0.002889
          вопрос          0.002860
          народ           0.002849
Name: topic_11, dtype: float32

In [106]:
fix_regularizer = FastFixPhiRegularizer(
    name='fix',
    parent_model=model._model,
    topic_names=good_topic_names,
)

other_phi = model._model.get_phi()[bad_topic_names]
other_phi = deepcopy(other_phi)
decorr_bad_regularizer = DecorrelatorWithOtherPhiRegularizer(
    name='ext_decorr_bad', tau=25,  # 1e5
    topic_names=bad_topic_names,
    other_phi=other_phi
)

other_phi = model._model.get_phi()[good_topic_names]
other_phi = deepcopy(other_phi)
decorr_good_regularizer = DecorrelatorWithOtherPhiRegularizer(
    name='ext_decorr_good', tau=25,  # 1e5
    topic_names=good_topic_names,
    other_phi=other_phi
)

In [107]:
%%time

model._fit(
    dataset.get_batch_vectorizer(),
    num_iterations=10,
    custom_regularizers={
        fix_regularizer.name: fix_regularizer,
        decorr_bad_regularizer.name: decorr_bad_regularizer,
        decorr_good_regularizer.name: decorr_good_regularizer,
    }
)

CPU times: user 19.9 s, sys: 0 ns, total: 19.9 s
Wall time: 10.9 s

In [108]:
other_phi = model._model.get_phi()[bad_topic_names]
other_phi = deepcopy(other_phi)

In [112]:
other_phi.rename(
    columns={n: f'm1_{n}' for n in bad_topic_names}, inplace=True
)

In [116]:
pd.concat([other_phi, model._model.get_phi(['topic_0'])], axis=1)

,m1_topic_8,m1_topic_13,m1_topic_18,m1_topic_19,topic_0
инвалидность,7.263344e-06,0.000000e+00,0.000000e+00,0.000000e+00,1.535188e-09
мазка,0.000000e+00,0.000000e+00,2.024645e-05,1.530354e-05,9.608340e-14
professor,0.000000e+00,3.533544e-13,1.517497e-12,0.000000e+00,0.000000e+00
умно,1.804371e-11,0.000000e+00,2.047675e-05,1.227452e-15,0.000000e+00
игил,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
...,...,...,...,...,...
милосердие,1.776537e-05,0.000000e+00,3.757288e-16,2.070272e-14,2.191762e-05
поверка,0.000000e+00,6.251613e-06,2.226501e-05,0.000000e+00,3.302222e-06
вто,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
слоить,1.872259e-05,6.039159e-16,3.578878e-05,0.000000e+00,1.846761e-15
акт,5.693086e-04,2.758584e-07,2.699137e-04,4.598258e-05,8.215548e-05

In [23]:
def init_model_from_family(
        family: str or KnownModel,
        dataset: Dataset,
        main_modality: str,
        num_topics: int,
        seed: int,
        specific_topic_names = None,
        modalities_to_use: List[str] = None,
        num_processors: int = 3,
        model_params: dict = None,
):
    """
    Returns
    -------
    model: TopicModel() instance
    """
    if isinstance(family, KnownModel):
        family = family.value

    if modalities_to_use is None:
        modalities_to_use = [main_modality]

    custom_regs = {}

    if family == "LDA":
        model = init_lda(
            dataset, modalities_to_use, main_modality, num_topics, model_params
        )
    elif family == "PLSA":
        model = init_plsa(
            dataset, modalities_to_use, main_modality, num_topics
        )
    elif family == "TARTM":
        model, custom_regs = init_thetaless(
            dataset, modalities_to_use, main_modality, num_topics, model_params
        )
    elif family == "sparse":
        model = init_bcg_sparse_model(
            dataset, modalities_to_use, main_modality, num_topics, 1, model_params
        )
    elif family == "decorrelation":
        model = init_decorrelated_plsa(
            dataset, modalities_to_use, main_modality, num_topics, model_params
        )
    elif family == "ARTM":
        model = init_baseline_artm(
            dataset, modalities_to_use, main_modality, num_topics, 1, specific_topic_names, model_params
        )
    else:
        raise ValueError(f'family: {family}')

    model.num_processors = num_processors

    if seed is not None:
        model.seed = seed

    dictionary = dataset.get_dictionary()

    # TODO: maybe this cycle is not necessary
    for modality in dataset.get_possible_modalities():
        if modality not in modalities_to_use:
            dictionary.filter(class_id=modality, max_df=0, inplace=True)

    model.initialize(dictionary)
    add_standard_scores(model, dictionary, main_modality=main_modality,
                        all_modalities=modalities_to_use)

    model = TopicModel(
        artm_model=model,
        custom_regularizers=custom_regs
    )

    return model


def init_bcg_sparse_model(
        dataset,
        modalities_to_use,
        main_modality,
        specific_topics,
        bcg_topics,
        specific_topic_names = None,
        model_params: dict = None
):
    """
    Creates simple artm model with standard scores.

    Parameters
    ----------
    dataset : Dataset
    modalities_to_use : list of str or dict
    main_modality : str
    specific_topics : int
    bcg_topics : int

    Returns
    -------
    model: artm.ARTM() instance
    """
    if model_params is None:
        model_params = dict()

    model = init_plsa(
        dataset, modalities_to_use, main_modality, specific_topics, bcg_topics
    )
    background_topic_names = model.topic_names[-bcg_topics:]

    if specific_topic_names is None:
        print('No spec topics')
        specific_topic_names = model.topic_names[:-bcg_topics]

    dictionary = dataset.get_dictionary()
    baseline_class_ids = {class_id: 1 for class_id in modalities_to_use}
    data_stats = count_vocab_size(dictionary, baseline_class_ids)

    # all coefficients are relative
    regularizers = [
        artm.SmoothSparsePhiRegularizer(
             name='smooth_phi_bcg',
             topic_names=background_topic_names,
             tau=model_params.get("smooth_bcg_tau", 0.1),
             class_ids=[main_modality],
        ),
        artm.SmoothSparseThetaRegularizer(
             name='smooth_theta_bcg',
             topic_names=background_topic_names,
             tau=model_params.get("smooth_bcg_tau", 0.1),
        ),
        artm.SmoothSparsePhiRegularizer(
             name='sparse_phi_sp',
             topic_names=specific_topic_names,
             tau=model_params.get("sparse_sp_tau", -0.05),
             class_ids=[main_modality],
            ),
        artm.SmoothSparseThetaRegularizer(
             name='sparse_theta_sp',
             topic_names=specific_topic_names,
             tau=model_params.get("sparse_sp_tau", -0.05),
        ),
    ]
    for reg in regularizers:
        model.regularizers.add(transform_regularizer(
            data_stats,
            reg,
            model.class_ids,
            n_topics=len(reg.topic_names)
        ))

    return model


def init_baseline_artm(
        dataset,
        modalities_to_use,
        main_modality,
        num_topics,
        bcg_topics,
        specific_topic_names = None,
        model_params: dict = None,
):
    """
    Creates simple artm model with standard scores.

    Parameters
    ----------
    dataset : Dataset
    modalities_to_use : list of str
    main_modality : str
    num_topics : int

    Returns
    -------
    model: artm.ARTM() instance
    """
    if model_params is None:
        model_params = dict()

    model = init_bcg_sparse_model(
        dataset, modalities_to_use, main_modality, num_topics, bcg_topics, specific_topic_names, model_params
    )

    if specific_topic_names is None:
        print('No spec topics')
        specific_topic_names = model.topic_names[:-bcg_topics]

    model.regularizers.add(
        artm.DecorrelatorPhiRegularizer(
            gamma=0,
            tau=model_params.get('decorrelation_tau', 0.01),
            name='decorrelation',
            topic_names=specific_topic_names,
            class_ids=modalities_to_use,
        )
    )

    return model

In [24]:
NUM_TRAINS = 3
TOPIC_INDICES = list(range(NUM_TOPICS))

In [25]:
TOPIC_INDICES

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [25]:
prev_results = dict()
results = dict()

DECORRELATOR_REGULARIZER_CLASS = DecorrelatorWithOtherPhiRegularizer
DECORRELATION_TAUS = [10, 100, 1000, 10000, 1e5, 1e6, 1e7]


for decorrelation_tau in DECORRELATION_TAUS:
    key = decorrelation_tau
    prev_results[key] = []
    results[key] = []

    print(key)

    for seed in range(NUM_TRAINS):
        print(seed)
        
        model = init_model_from_family(
            family=KnownModel.ARTM,
            dataset=dataset,
            main_modality=MAIN_MODALITY,
            num_topics=NUM_TOPICS,
            seed=seed,
            model_params={
                'decorrelation_tau': 0.01,  # best values
                'smooth_bcg_tau': 0.05,
                'sparse_sp_tau': -0.05,
            }
        )

        for reg in model.regularizers.data:
            print(f"{reg}: {model.regularizers[reg].tau}")

        result = fit_and_compute_scores(model, dataset)
        prev_results[key].append(result)

        
        good_topic_indices = [
            t for t, c in result['topic_coherences'].items() if t in TOPIC_INDICES and is_good(c)
        ]
        bad_topic_indices = [
            t for t, c in result['topic_coherences'].items() if t in TOPIC_INDICES and is_bad(c)
        ]
        not_good_topic_indices = [
            t for t in TOPIC_INDICES if t not in good_topic_indices
        ]
        
        phi = model.get_phi()
        good_topic_names = [phi.columns[t] for t in good_topic_indices]
        bad_topic_names = [phi.columns[t] for t in bad_topic_indices]
        not_good_topic_names = [phi.columns[t] for t in not_good_topic_indices]


        assert len(good_topic_names) > 0
        assert len(bad_topic_names) > 0

        print(len(good_topic_names), len(bad_topic_names), len(not_good_topic_names))


        fix_regularizer = FastFixPhiRegularizer(
            name='fix',
            parent_model=model._model,
            topic_names=good_topic_names,
        )
        
        bad_phi = model._model.get_phi()[bad_topic_names]
        bad_phi = deepcopy(bad_phi)
        decorr_bad_regularizer = DECORRELATOR_REGULARIZER_CLASS(
            name='ext_decorr_bad', tau=decorrelation_tau,
            topic_names=not_good_topic_names,
            other_phi=bad_phi
        )
        
        good_phi = model._model.get_phi()[good_topic_names]
        good_phi = deepcopy(good_phi)
        decorr_good_regularizer = DECORRELATOR_REGULARIZER_CLASS(
            name='ext_decorr_good', tau=decorrelation_tau,
            topic_names=not_good_topic_names,
            other_phi=good_phi
        )

        
        assert not hasattr(fix_regularizer, '_model')


        new_model = init_model_from_family(
            family=KnownModel.ARTM,
            dataset=dataset,
            main_modality=MAIN_MODALITY,
            num_topics=NUM_TOPICS,
            seed=seed,
            specific_topic_names=not_good_topic_names,
            model_params={
                'decorrelation_tau': 0.01,
                'smooth_bcg_tau': 0.05,
                'sparse_sp_tau': -0.05,
            }
        )
        custom_regularizers = {
            fix_regularizer.name: fix_regularizer,
            decorr_bad_regularizer.name: decorr_bad_regularizer,
            decorr_good_regularizer.name: decorr_good_regularizer,
        }

        new_result = fit_and_compute_scores(new_model, dataset, custom_regularizers=custom_regularizers)
        
        for reg in new_model.regularizers.data:
            print(f"{reg}: {new_model.regularizers[reg].tau}")

        for reg_name, reg in custom_regularizers.items():
            print(f"{reg_name}: {reg.tau}")

        
        results[key].append(new_result)

10
0
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
6 2 14

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f96d1385040>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f96d13850d0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f96d120fa90>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.0684473508802884
sparse_theta_sp: -0.319457311284836
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 10
ext_decorr_good: 10
1
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
5 3 15

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f96d120fe20>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f9607055880>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f96d0c897c0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.06388419415493585
sparse_theta_sp: -0.29816015719918026
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 10
ext_decorr_good: 10
2
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
7 3 13

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f96d12240a0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f96d0aabca0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f96d0aabfd0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.07371253171723367
sparse_theta_sp: -0.3440309506144388
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 10
ext_decorr_good: 10
100
0
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
6 2 14

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f96d07b35b0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f96d1245d90>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f96d0c89640>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.0684473508802884
sparse_theta_sp: -0.319457311284836
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100
ext_decorr_good: 100
1
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
5 3 15

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f96d1067190>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f96d1245d60>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f96d0aab190>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.06388419415493585
sparse_theta_sp: -0.29816015719918026
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100
ext_decorr_good: 100
2
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
7 3 13

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f96d0ab5460>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f96d0ab5400>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f96d0ab55b0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.07371253171723367
sparse_theta_sp: -0.3440309506144388
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100
ext_decorr_good: 100
1000
0
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
6 2 14

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f96d0ab49a0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f96d0ab4400>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f96d0ab4310>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.0684473508802884
sparse_theta_sp: -0.319457311284836
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 1000
ext_decorr_good: 1000
1
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
5 3 15

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f96d10812e0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f96d0ab5cd0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f96d0ab5d30>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.06388419415493585
sparse_theta_sp: -0.29816015719918026
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 1000
ext_decorr_good: 1000
2
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
7 3 13

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f96d0dcf100>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f96d0dcf9a0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f96d0dcf0a0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.07371253171723367
sparse_theta_sp: -0.3440309506144388
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 1000
ext_decorr_good: 1000
10000
0
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
6 2 14

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f96d1068790>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f96d1068160>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f96d0e24f40>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.0684473508802884
sparse_theta_sp: -0.319457311284836
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 10000
ext_decorr_good: 10000
1
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
5 3 15

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f96d0e2cee0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f96d0e2cbe0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f96f8748ac0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.06388419415493585
sparse_theta_sp: -0.29816015719918026
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 10000
ext_decorr_good: 10000
2
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
7 3 13

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f96c5ffdfd0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f96d07980a0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f96d1126d90>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.07371253171723367
sparse_theta_sp: -0.3440309506144388
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 10000
ext_decorr_good: 10000
100000.0
0
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
6 2 14

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f96d1131310>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f9607c241c0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f96d11208e0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.0684473508802884
sparse_theta_sp: -0.319457311284836
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000.0
ext_decorr_good: 100000.0
1
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
5 3 15

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f96d08e1820>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f96fafcddc0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f96d11209a0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.06388419415493585
sparse_theta_sp: -0.29816015719918026
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000.0
ext_decorr_good: 100000.0
2
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
7 3 13

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f96d029fd60>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f96d1067310>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f96d11207c0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.07371253171723367
sparse_theta_sp: -0.3440309506144388
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000.0
ext_decorr_good: 100000.0
1000000.0
0
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
6 2 14

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f96c5f26160>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f96c33a9490>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f96d02add00>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.0684473508802884
sparse_theta_sp: -0.319457311284836
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 1000000.0
ext_decorr_good: 1000000.0
1
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
5 3 15

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f96c37f2ac0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f96d1245b50>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f96c5f1bca0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.06388419415493585
sparse_theta_sp: -0.29816015719918026
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 1000000.0
ext_decorr_good: 1000000.0
2
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
7 3 13

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f96d07320d0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f96c5f1b7f0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f96c5f1bbb0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.07371253171723367
sparse_theta_sp: -0.3440309506144388
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 1000000.0
ext_decorr_good: 1000000.0
10000000.0
0
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
6 2 14

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f96d0a040a0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f96d0a04700>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f96d0890fd0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.0684473508802884
sparse_theta_sp: -0.319457311284836
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 10000000.0
ext_decorr_good: 10000000.0
1
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
5 3 15

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f96d08e6460>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f96d0895e50>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f96d10683d0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.06388419415493585
sparse_theta_sp: -0.29816015719918026
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 10000000.0
ext_decorr_good: 10000000.0
2
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
7 3 13

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f96d0798760>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f96d08a3ee0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f96d0dcf730>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.07371253171723367
sparse_theta_sp: -0.3440309506144388
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 10000000.0
ext_decorr_good: 10000000.0

In [30]:
for k, r in prev_results.items():
    mean_ppl = sum(v['scores']['perplexity'] for v in r) / len(r)
    print(k, mean_ppl)

10 2226.6844889322915
100 2226.6844889322915
1000 2226.6844889322915
10000 2226.6844889322915
100000.0 2226.6844889322915
1000000.0 2226.6844889322915
10000000.0 2226.6844889322915

In [31]:
for k, r in results.items():
    mean_ppl = sum(v['scores']['perplexity'] for v in r) / len(r)
    print(k, mean_ppl)

10 2239.01025390625
100 2239.0091959635415
1000 2239.0104166666665
10000 2239.0723470052085
100000.0 2239.7661946614585
1000000.0 2299.219970703125
10000000.0 2659.0167643229165

In [32]:
for k, r in results.items():
    mean_ppl = sum(v['scores']['perplexity'] for v in r) / len(r)

    prev_r = prev_results[k]
    prev_mean_ppl = sum(v['scores']['perplexity'] for v in prev_r) / len(prev_r)

    print(k, mean_ppl - prev_mean_ppl)

10 12.325764973958485
100 12.32470703125
1000 12.325927734375
10000 12.38785807291697
100000.0 13.08170572916697
1000000.0 72.53548177083348
10000000.0 432.332275390625

In [ ]:
#  Best: 100  12.32470703125
# Close: 10   12.325764973958485
#        1000 12.325927734375

In [33]:
prev_results = dict()
results = dict()

DECORRELATOR_REGULARIZER_CLASS = DecorrelatorWithOtherPhiRegularizer2
DECORRELATION_TAUS = [10, 100, 1000, 10000, 1e5, 1e6, 1e7, 1e8, 1e9, 1e10]

for decorrelation_tau in DECORRELATION_TAUS:
    key = decorrelation_tau
    prev_results[key] = []
    results[key] = []

    print(key)

    for seed in range(NUM_TRAINS):
        print(seed)
        
        model = init_model_from_family(
            family=KnownModel.ARTM,
            dataset=dataset,
            main_modality=MAIN_MODALITY,
            num_topics=NUM_TOPICS,
            seed=seed,
            model_params={
                'decorrelation_tau': 0.01,  # best values
                'smooth_bcg_tau': 0.05,
                'sparse_sp_tau': -0.05,
            }
        )

        for reg in model.regularizers.data:
            print(f"{reg}: {model.regularizers[reg].tau}")

        result = fit_and_compute_scores(model, dataset)
        prev_results[key].append(result)

        
        good_topic_indices = [
            t for t, c in result['topic_coherences'].items() if t in TOPIC_INDICES and is_good(c)
        ]
        bad_topic_indices = [
            t for t, c in result['topic_coherences'].items() if t in TOPIC_INDICES and is_bad(c)
        ]
        not_good_topic_indices = [
            t for t in TOPIC_INDICES if t not in good_topic_indices
        ]
        
        phi = model.get_phi()
        good_topic_names = [phi.columns[t] for t in good_topic_indices]
        bad_topic_names = [phi.columns[t] for t in bad_topic_indices]
        not_good_topic_names = [phi.columns[t] for t in not_good_topic_indices]


        assert len(good_topic_names) > 0
        assert len(bad_topic_names) > 0

        print(len(good_topic_names), len(bad_topic_names), len(not_good_topic_names))


        fix_regularizer = FastFixPhiRegularizer(
            name='fix',
            parent_model=model._model,
            topic_names=good_topic_names,
        )
        
        bad_phi = model._model.get_phi()[bad_topic_names]
        bad_phi = deepcopy(bad_phi)
        decorr_bad_regularizer = DECORRELATOR_REGULARIZER_CLASS(
            name='ext_decorr_bad', tau=decorrelation_tau,
            topic_names=not_good_topic_names,
            other_phi=bad_phi
        )
        
        good_phi = model._model.get_phi()[good_topic_names]
        good_phi = deepcopy(good_phi)
        decorr_good_regularizer = DECORRELATOR_REGULARIZER_CLASS(
            name='ext_decorr_good', tau=decorrelation_tau,
            topic_names=not_good_topic_names,
            other_phi=good_phi
        )

        
        assert not hasattr(fix_regularizer, '_model')


        new_model = init_model_from_family(
            family=KnownModel.ARTM,
            dataset=dataset,
            main_modality=MAIN_MODALITY,
            num_topics=NUM_TOPICS,
            seed=seed,
            specific_topic_names=not_good_topic_names,
            model_params={
                'decorrelation_tau': 0.01,
                'smooth_bcg_tau': 0.05,
                'sparse_sp_tau': -0.05,
            }
        )
        custom_regularizers = {
            fix_regularizer.name: fix_regularizer,
            decorr_bad_regularizer.name: decorr_bad_regularizer,
            decorr_good_regularizer.name: decorr_good_regularizer,
        }

        new_result = fit_and_compute_scores(new_model, dataset, custom_regularizers=custom_regularizers)
        
        for reg in new_model.regularizers.data:
            print(f"{reg}: {new_model.regularizers[reg].tau}")

        for reg_name, reg in custom_regularizers.items():
            print(f"{reg_name}: {reg.tau}")

        
        results[key].append(new_result)

10
0
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
6 2 14

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f96d08a8460>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96c5f1b910>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96e83a8820>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.0684473508802884
sparse_theta_sp: -0.319457311284836
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 10
ext_decorr_good: 10
1
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
5 3 15

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f96e83a85b0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96c33cf460>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96c33cf1f0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.06388419415493585
sparse_theta_sp: -0.29816015719918026
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 10
ext_decorr_good: 10
2
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
7 3 13

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f96d01df220>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96d0cbba30>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96d0cbb160>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.07371253171723367
sparse_theta_sp: -0.3440309506144388
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 10
ext_decorr_good: 10
100
0
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
6 2 14

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f96d089b8e0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96d089b940>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96d089bfa0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.0684473508802884
sparse_theta_sp: -0.319457311284836
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100
ext_decorr_good: 100
1
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
5 3 15

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f96d1409190>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96d14092e0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96d1409370>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.06388419415493585
sparse_theta_sp: -0.29816015719918026
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100
ext_decorr_good: 100
2
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
7 3 13

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f96d0e1b0a0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96d0e1b0d0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96d0e1b130>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.07371253171723367
sparse_theta_sp: -0.3440309506144388
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100
ext_decorr_good: 100
1000
0
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
6 2 14

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f96d09ff160>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96d120f5b0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96d1126e50>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.0684473508802884
sparse_theta_sp: -0.319457311284836
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 1000
ext_decorr_good: 1000
1
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
5 3 15

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f96d1048280>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96d1048340>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96d14b5820>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.06388419415493585
sparse_theta_sp: -0.29816015719918026
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 1000
ext_decorr_good: 1000
2
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
7 3 13

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f96d110f3a0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96d110f190>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96d110f4f0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.07371253171723367
sparse_theta_sp: -0.3440309506144388
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 1000
ext_decorr_good: 1000
10000
0
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
6 2 14

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f96d034d3d0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96d14097c0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96d0895f10>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.0684473508802884
sparse_theta_sp: -0.319457311284836
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 10000
ext_decorr_good: 10000
1
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
5 3 15

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f96d144fa30>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96d0895eb0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96d1409190>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.06388419415493585
sparse_theta_sp: -0.29816015719918026
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 10000
ext_decorr_good: 10000
2
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
7 3 13

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f96d0a073d0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96d0a07520>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96d0a07910>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.07371253171723367
sparse_theta_sp: -0.3440309506144388
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 10000
ext_decorr_good: 10000
100000.0
0
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
6 2 14

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f96d11d19a0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96d11d1430>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96d11d1070>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.0684473508802884
sparse_theta_sp: -0.319457311284836
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000.0
ext_decorr_good: 100000.0
1
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
5 3 15

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f96d105d220>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96d1081b50>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96d10815e0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.06388419415493585
sparse_theta_sp: -0.29816015719918026
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000.0
ext_decorr_good: 100000.0
2
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
7 3 13

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f96c34da100>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96c34da9a0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96c34da0a0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.07371253171723367
sparse_theta_sp: -0.3440309506144388
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000.0
ext_decorr_good: 100000.0
1000000.0
0
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
6 2 14

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f96c3648100>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96c3648df0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96c3648130>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.0684473508802884
sparse_theta_sp: -0.319457311284836
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 1000000.0
ext_decorr_good: 1000000.0
1
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
5 3 15

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f96d0ab5400>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96d14764f0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96d14768b0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.06388419415493585
sparse_theta_sp: -0.29816015719918026
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 1000000.0
ext_decorr_good: 1000000.0
2
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
7 3 13

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f96d0e28700>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96d0447dc0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96d04478b0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.07371253171723367
sparse_theta_sp: -0.3440309506144388
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 1000000.0
ext_decorr_good: 1000000.0
10000000.0
0
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
6 2 14

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f96d036f6a0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96d0b21940>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96d036fb80>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.06388419415493585
sparse_theta_sp: -0.29816015719918026
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 10000000.0
ext_decorr_good: 10000000.0
2
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
7 3 13

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f96d08dd850>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96d08ddf70>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96d0a06b20>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.07371253171723367
sparse_theta_sp: -0.3440309506144388
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 10000000.0
ext_decorr_good: 10000000.0
100000000.0
0
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
6 2 14

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f96d0ec7310>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96d06a77c0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96d0ec77f0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.0684473508802884
sparse_theta_sp: -0.319457311284836
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000000.0
ext_decorr_good: 100000000.0
1
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
5 3 15

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f96d0ab5640>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96d059bcd0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96d0caf2b0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.06388419415493585
sparse_theta_sp: -0.29816015719918026
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000000.0
ext_decorr_good: 100000000.0
2
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
7 3 13

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f96d0ea5370>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96d0ed7dc0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96d059bc40>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.07371253171723367
sparse_theta_sp: -0.3440309506144388
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000000.0
ext_decorr_good: 100000000.0
1000000000.0
0
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
6 2 14

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f96c34c6430>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96d05d0f40>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96d0ed7c70>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.0684473508802884
sparse_theta_sp: -0.319457311284836
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 1000000000.0
ext_decorr_good: 1000000000.0
1
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
5 3 15

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f96c3532d90>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96d0d60fd0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96d0d609a0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.06388419415493585
sparse_theta_sp: -0.29816015719918026
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 1000000000.0
ext_decorr_good: 1000000000.0
2
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
7 3 13

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f96d1126fd0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96d107d040>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96d02adb50>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.07371253171723367
sparse_theta_sp: -0.3440309506144388
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 1000000000.0
ext_decorr_good: 1000000000.0
10000000000.0
0
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
6 2 14

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f96d0798d90>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96fafcddc0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96d1227790>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.0684473508802884
sparse_theta_sp: -0.319457311284836
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 10000000000.0
ext_decorr_good: 10000000000.0
1
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
5 3 15

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f96d01bcfa0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96d0d60ee0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96d0d60490>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.06388419415493585
sparse_theta_sp: -0.29816015719918026
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 10000000000.0
ext_decorr_good: 10000000000.0
2
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
7 3 13

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f96d05ce0d0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96d0ea5280>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f96d0ea5220>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.07371253171723367
sparse_theta_sp: -0.3440309506144388
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 10000000000.0
ext_decorr_good: 10000000000.0

In [37]:
for k, r in prev_results.items():
    mean_ppl = sum(v['scores']['perplexity'] for v in r) / len(r)
    print(k, mean_ppl)

10 2226.6844889322915
100 2226.6844889322915
1000 2226.6844889322915
10000 2226.6844889322915
100000.0 2226.6844889322915
1000000.0 2226.6844889322915
10000000.0 2226.6844889322915
100000000.0 2226.6844889322915
1000000000.0 2226.6844889322915
10000000000.0 2226.6844889322915

In [38]:
for k, r in results.items():
    mean_ppl = sum(v['scores']['perplexity'] for v in r) / len(r)
    print(k, mean_ppl)

10 2239.0099283854165
100 2239.0099283854165
1000 2239.0100911458335
10000 2239.01025390625
100000.0 2239.0098470052085
1000000.0 2239.0165201822915
10000000.0 2239.1668294270835
100000000.0 2240.8199055989585
1000000000.0 2285.2738444010415
10000000000.0 2437.2290852864585

In [39]:
for k, r in results.items():
    mean_ppl = sum(v['scores']['perplexity'] for v in r) / len(r)

    prev_r = prev_results[k]
    prev_mean_ppl = sum(v['scores']['perplexity'] for v in prev_r) / len(prev_r)

    print(k, mean_ppl - prev_mean_ppl)

10 12.325439453125
100 12.325439453125
1000 12.32560221354197
10000 12.325764973958485
100000.0 12.32535807291697
1000000.0 12.33203125
10000000.0 12.48234049479197
100000000.0 14.13541666666697
1000000000.0 58.58935546875
10000000000.0 210.54459635416697

In [40]:
#  Best: 100000  12.32535807291697
# Close: 1000000 12.33203125
#        10000   12.325764973958485

# Edgy:
# 10000000.0 12.48234049479197
# 100000000.0 14.13541666666697
# 1000000000.0 58.58935546875

In [41]:
MAX_NUM_TRAINS

20

In [42]:
results

{10: [{'scores': {'perplexity': 2253.85498046875,
    'coherence_20': array([1.44551848]),
    'diversity_euclidean': 0.07102475422861072,
    'diversity_jensenshannon': 0.6992353616454047,
    'diversity_hellinger': 0.8179134374781466,
    'diversity_cosine': 0.8265317080905235},
   'topic_coherences': {0: 1.054240285921331,
    1: 1.453658536717904,
    2: 1.4334904461780176,
    3: 1.0063072833414675,
    4: 1.0096204089012255,
    5: 1.5539136077121654,
    6: 1.3994107963122735,
    7: 0.9778608908985307,
    8: 0.6195399396999054,
    9: 0.8006673680341132,
    10: 1.840761298075488,
    11: 1.2604398789491713,
    12: 1.7073209789137267,
    13: 1.8580910947101374,
    14: 1.4267776480811674,
    15: 1.6073534123690463,
    16: 2.0158025400053132,
    17: 2.636592011876535,
    18: 1.7554318141499257,
    19: 1.4930893269495578}},
  {'scores': {'perplexity': 2230.625244140625,
    'coherence_20': array([1.46466194]),
    'diversity_euclidean': 0.0683676049899362,
    'diversity_jensenshannon': 0.6939977256805049,
    'diversity_hellinger': 0.8108436726518281,
    'diversity_cosine': 0.8153640917696908},
   'topic_coherences': {0: 0.6396204917880516,
    1: 1.4894742830800083,
    2: 1.3686757692061315,
    3: 0.6244184212210658,
    4: 0.9079345653122926,
    5: 1.510304355415203,
    6: 1.5123197870455498,
    7: 0.8574741731712825,
    8: 1.044643746742568,
    9: 1.8032848505598649,
    10: 1.042438176716673,
    11: 3.6148133798456175,
    12: 1.8125303764407255,
    13: 1.2868693196774341,
    14: 1.2787704134723867,
    15: 1.4637416002371149,
    16: 1.603572270783483,
    17: 2.2133516704858605,
    18: 2.3337578327353596,
    19: 0.8852433897072066}},
  {'scores': {'perplexity': 2232.549560546875,
    'coherence_20': array([1.43724819]),
    'diversity_euclidean': 0.0686741192595982,
    'diversity_jensenshannon': 0.6905923892297601,
    'diversity_hellinger': 0.8066957682689985,
    'diversity_cosine': 0.8107531981955428},
   'topic_coherences': {0: 1.7300523146588405,
    1: 1.0011339322592363,
    2: 1.9563085816159047,
    3: 1.6460933884449667,
    4: 1.4232000182863762,
    5: 1.3338542382661231,
    6: 1.4898214631509419,
    7: 1.2641223306369482,
    8: 2.237799559639728,
    9: 0.97719939896769,
    10: 1.9824795351569895,
    11: 2.159035393982212,
    12: 0.764870588718921,
    13: 0.7674230110899558,
    14: 1.3479183851656573,
    15: 0.6903762780733693,
    16: 2.8450990542764627,
    17: 0.6990922223049143,
    18: 1.4874224091549701,
    19: 0.9416617210914205}}],
 100: [{'scores': {'perplexity': 2253.85498046875,
    'coherence_20': array([1.44551848]),
    'diversity_euclidean': 0.0710247519744175,
    'diversity_jensenshannon': 0.6992353691681112,
    'diversity_hellinger': 0.8179134357616353,
    'diversity_cosine': 0.8265317246883895},
   'topic_coherences': {0: 1.054240285921331,
    1: 1.453658536717904,
    2: 1.4334904461780176,
    3: 1.0063072833414675,
    4: 1.0096204089012255,
    5: 1.5539136077121654,
    6: 1.3994107963122735,
    7: 0.9778608908985307,
    8: 0.6195399396999054,
    9: 0.8006673680341132,
    10: 1.840761298075488,
    11: 1.2604398789491713,
    12: 1.7073209789137267,
    13: 1.8580910947101374,
    14: 1.4267776480811674,
    15: 1.6073534123690463,
    16: 2.0158025400053132,
    17: 2.636592011876535,
    18: 1.7554318141499257,
    19: 1.4930893269495578}},
  {'scores': {'perplexity': 2230.625244140625,
    'coherence_20': array([1.46466194]),
    'diversity_euclidean': 0.06836760453117229,
    'diversity_jensenshannon': 0.6939977227572892,
    'diversity_hellinger': 0.810843672216476,
    'diversity_cosine': 0.8153640843128505},
   'topic_coherences': {0: 0.6396204917880516,
    1: 1.4894742830800083,
    2: 1.3686757692061315,
    3: 0.6244184212210658,
    4: 0.9079345653122926,
    5: 1.510304355415203,
    6: 1.5123197870455498,
    7: 0.8574741731712825,
    8: 1.044643746742568,
    9: 1.8032848505598649,
    10: 1.042438176716673,
    11: 3.6148133798456175,
    12: 1.8125303764407255,
    13: 1.2868693196774341,
    14: 1.2787704134723867,
    15: 1.4637416002371149,
    16: 1.603572270783483,
    17: 2.2133516704858605,
    18: 2.3337578327353596,
    19: 0.8852433897072066}},
  {'scores': {'perplexity': 2232.549560546875,
    'coherence_20': array([1.43724819]),
    'diversity_euclidean': 0.06867411868066396,
    'diversity_jensenshannon': 0.6905923861106484,
    'diversity_hellinger': 0.806695773224758,
    'diversity_cosine': 0.8107531842831706},
   'topic_coherences': {0: 1.7300523146588405,
    1: 1.0011339322592363,
    2: 1.9563085816159047,
    3: 1.6460933884449667,
    4: 1.4232000182863762,
    5: 1.3338542382661231,
    6: 1.4898214631509419,
    7: 1.2641223306369482,
    8: 2.237799559639728,
    9: 0.97719939896769,
    10: 1.9824795351569895,
    11: 2.159035393982212,
    12: 0.764870588718921,
    13: 0.7674230110899558,
    14: 1.3479183851656573,
    15: 0.6903762780733693,
    16: 2.8450990542764627,
    17: 0.6990922223049143,
    18: 1.4874224091549701,
    19: 0.9416617210914205}}],
 1000: [{'scores': {'perplexity': 2253.855224609375,
    'coherence_20': array([1.44551848]),
    'diversity_euclidean': 0.07102475621098227,
    'diversity_jensenshannon': 0.6992353949285544,
    'diversity_hellinger': 0.8179134745123278,
    'diversity_cosine': 0.8265318034030779},
   'topic_coherences': {0: 1.054240285921331,
    1: 1.453658536717904,
    2: 1.4334904461780176,
    3: 1.0063072833414675,
    4: 1.0096204089012255,
    5: 1.5539136077121654,
    6: 1.3994107963122735,
    7: 0.9778608908985307,
    8: 0.6195399396999054,
    9: 0.8006673680341132,
    10: 1.840761298075488,
    11: 1.2604398789491713,
    12: 1.7073209789137267,
    13: 1.8580910947101374,
    14: 1.4267776480811674,
    15: 1.6073534123690463,
    16: 2.0158025400053132,
    17: 2.636592011876535,
    18: 1.7554318141499257,
    19: 1.4930893269495578}},
  {'scores': {'perplexity': 2230.625244140625,
    'coherence_20': array([1.46466194]),
    'diversity_euclidean': 0.06836759159073837,
    'diversity_jensenshannon': 0.6939977333634683,
    'diversity_hellinger': 0.8108436907174926,
    'diversity_cosine': 0.8153641247687415},
   'topic_coherences': {0: 0.6396204917880516,
    1: 1.4894742830800083,
    2: 1.3686757692061315,
    3: 0.6244184212210658,
    4: 0.9079345653122926,
    5: 1.510304355415203,
    6: 1.5123197870455498,
    7: 0.8574741731712825,
    8: 1.044643746742568,
    9: 1.8032848505598649,
    10: 1.042438176716673,
    11: 3.6148133798456175,
    12: 1.8125303764407255,
    13: 1.2868693196774341,
    14: 1.2787704134723867,
    15: 1.4637416002371149,
    16: 1.603572270783483,
    17: 2.2133516704858605,
    18: 2.3337578327353596,
    19: 0.8852433897072066}},
  {'scores': {'perplexity': 2232.5498046875,
    'coherence_20': array([1.43724819]),
    'diversity_euclidean': 0.06867410964471471,
    'diversity_jensenshannon': 0.6905924028070181,
    'diversity_hellinger': 0.8066958135405359,
    'diversity_cosine': 0.8107532403126584},
   'topic_coherences': {0: 1.7300523146588405,
    1: 1.0011339322592363,
    2: 1.9563085816159047,
    3: 1.6460933884449667,
    4: 1.4232000182863762,
    5: 1.3338542382661231,
    6: 1.4898214631509419,
    7: 1.2641223306369482,
    8: 2.237799559639728,
    9: 0.97719939896769,
    10: 1.9824795351569895,
    11: 2.159035393982212,
    12: 0.764870588718921,
    13: 0.7674230110899558,
    14: 1.3479183851656573,
    15: 0.6903762780733693,
    16: 2.8450990542764627,
    17: 0.6990922223049143,
    18: 1.4874224091549701,
    19: 0.9416617210914205}}],
 10000: [{'scores': {'perplexity': 2253.855224609375,
    'coherence_20': array([1.44551848]),
    'diversity_euclidean': 0.07102472134399287,
    'diversity_jensenshannon': 0.6992355817337141,
    'diversity_hellinger': 0.8179136935409568,
    'diversity_cosine': 0.8265323503691856},
   'topic_coherences': {0: 1.054240285921331,
    1: 1.453658536717904,
    2: 1.4334904461780176,
    3: 1.0063072833414675,
    4: 1.0096204089012255,
    5: 1.5539136077121654,
    6: 1.3994107963122735,
    7: 0.9778608908985307,
    8: 0.6195399396999054,
    9: 0.8006673680341132,
    10: 1.840761298075488,
    11: 1.2604398789491713,
    12: 1.7073209789137267,
    13: 1.8580910947101374,
    14: 1.4267776480811674,
    15: 1.6073534123690463,
    16: 2.0158025400053132,
    17: 2.636592011876535,
    18: 1.7554318141499257,
    19: 1.4930893269495578}},
  {'scores': {'perplexity': 2230.625732421875,
    'coherence_20': array([1.46466194]),
    'diversity_euclidean': 0.06836746500804107,
    'diversity_jensenshannon': 0.6939978481342034,
    'diversity_hellinger': 0.8108438771527655,
    'diversity_cosine': 0.8153645650366038},
   'topic_coherences': {0: 0.6396204917880516,
    1: 1.4894742830800083,
    2: 1.3686757692061315,
    3: 0.6244184212210658,
    4: 0.9079345653122926,
    5: 1.510304355415203,
    6: 1.5123197870455498,
    7: 0.8574741731712825,
    8: 1.044643746742568,
    9: 1.8032848505598649,
    10: 1.042438176716673,
    11: 3.6148133798456175,
    12: 1.8125303764407255,
    13: 1.2868693196774341,
    14: 1.2787704134723867,
    15: 1.4637416002371149,
    16: 1.603572270783483,
    17: 2.2133516704858605,
    18: 2.3337578327353596,
    19: 0.8852433897072066}},
  {'scores': {'perplexity': 2232.5498046875,
    'coherence_20': array([1.43724819]),
    'diversity_euclidean': 0.06867399168202422,
    'diversity_jensenshannon': 0.6905925113799004,
    'diversity_hellinger': 0.8066959861178219,
    'diversity_cosine': 0.810753599804651},
   'topic_coherences': {0: 1.7300523146588405,
    1: 1.0011339322592363,
    2: 1.9563085816159047,
    3: 1.6460933884449667,
    4: 1.4232000182863762,
    5: 1.3338542382661231,
    6: 1.4898214631509419,
    7: 1.2641223306369482,
    8: 2.237799559639728,
    9: 0.97719939896769,
    10: 1.9824795351569895,
    11: 2.159035393982212,
    12: 0.764870588718921,
    13: 0.7674230110899558,
    14: 1.3479183851656573,
    15: 0.6903762780733693,
    16: 2.8450990542764627,
    17: 0.6990922223049143,
    18: 1.4874224091549701,
    19: 0.9416617210914205}}],
 100000.0: [{'scores': {'perplexity': 2253.856201171875,
    'coherence_20': array([1.44551848]),
    'diversity_euclidean': 0.07102439615998558,
    'diversity_jensenshannon': 0.6992374365302431,
    'diversity_hellinger': 0.8179160978500061,
    'diversity_cosine': 0.8265377843343141},
   'topic_coherences': {0: 1.054240285921331,
    1: 1.453658536717904,
    2: 1.4334904461780176,
    3: 1.0063072833414675,
    4: 1.0096204089012255,
    5: 1.5539136077121654,
    6: 1.3994107963122735,
    7: 0.9778608908985307,
    8: 0.6195399396999054,
    9: 0.8006673680341132,
    10: 1.840761298075488,
    11: 1.2604398789491713,
    12: 1.7073209789137267,
    13: 1.8580910947101374,
    14: 1.4267776480811674,
    15: 1.6073534123690463,
    16: 2.0158025400053132,
    17: 2.636592011876535,
    18: 1.7554318141499257,
    19: 1.4930893269495578}},
  {'scores': {'perplexity': 2230.6220703125,
    'coherence_20': array([1.46466194]),
    'diversity_euclidean': 0.06836613563052667,
    'diversity_jensenshannon': 0.6939993318304954,
    'diversity_hellinger': 0.8108461372342537,
    'diversity_cosine': 0.815370461889995},
   'topic_coherences': {0: 0.6396204917880516,
    1: 1.4894742830800083,
    2: 1.3686757692061315,
    3: 0.6244184212210658,
    4: 0.9079345653122926,
    5: 1.510304355415203,
    6: 1.5123197870455498,
    7: 0.8574741731712825,
    8: 1.044643746742568,
    9: 1.8032848505598649,
    10: 1.042438176716673,
    11: 3.6148133798456175,
    12: 1.8125303764407255,
    13: 1.2868693196774341,
    14: 1.2787704134723867,
    15: 1.4637416002371149,
    16: 1.603572270783483,
    17: 2.2133516704858605,
    18: 2.3337578327353596,
    19: 0.8852433897072066}},
  {'scores': {'perplexity': 2232.55126953125,
    'coherence_20': array([1.43724819]),
    'diversity_euclidean': 0.06867276541886481,
    'diversity_jensenshannon': 0.6905935834463142,
    'diversity_hellinger': 0.8066975614854757,
    'diversity_cosine': 0.8107572926028223},
   'topic_coherences': {0: 1.7300523146588405,
    1: 1.0011339322592363,
    2: 1.9563085816159047,
    3: 1.6460933884449667,
    4: 1.4232000182863762,
    5: 1.3338542382661231,
    6: 1.4898214631509419,
    7: 1.2641223306369482,
    8: 2.237799559639728,
    9: 0.97719939896769,
    10: 1.9824795351569895,
    11: 2.159035393982212,
    12: 0.764870588718921,
    13: 0.7674230110899558,
    14: 1.3479183851656573,
    15: 0.6903762780733693,
    16: 2.8450990542764627,
    17: 0.6990922223049143,
    18: 1.4874224091549701,
    19: 0.9416617210914205}}],
 1000000.0: [{'scores': {'perplexity': 2253.859619140625,
    'coherence_20': array([1.44551848]),
    'diversity_euclidean': 0.07102114296127712,
    'diversity_jensenshannon': 0.699256379413943,
    'diversity_hellinger': 0.8179410998195683,
    'diversity_cosine': 0.8265924917130084},
   'topic_coherences': {0: 1.054240285921331,
    1: 1.453658536717904,
    2: 1.4334904461780176,
    3: 1.0063072833414675,
    4: 1.0096204089012255,
    5: 1.5539136077121654,
    6: 1.3994107963122735,
    7: 0.9778608908985307,
    8: 0.6195399396999054,
    9: 0.8006673680341132,
    10: 1.840761298075488,
    11: 1.2604398789491713,
    12: 1.7073209789137267,
    13: 1.8580910947101374,
    14: 1.4267776480811674,
    15: 1.6073534123690463,
    16: 2.0158025400053132,
    17: 2.636592011876535,
    18: 1.7554318141499257,
    19: 1.4930893269495578}},
  {'scores': {'perplexity': 2230.63232421875,
    'coherence_20': array([1.46466194]),
    'diversity_euclidean': 0.0683536130868116,
    'diversity_jensenshannon': 0.6940140107691227,
    'diversity_hellinger': 0.8108672794502036,
    'diversity_cosine': 0.8154257415729333},
   'topic_coherences': {0: 0.6396204917880516,
    1: 1.4894742830800083,
    2: 1.3686757692061315,
    3: 0.6244184212210658,
    4: 0.9079345653122926,
    5: 1.510304355415203,
    6: 1.5123197870455498,
    7: 0.8574741731712825,
    8: 1.044643746742568,
    9: 1.8032848505598649,
    10: 1.042438176716673,
    11: 3.6148133798456175,
    12: 1.8125303764407255,
    13: 1.2868693196774341,
    14: 1.2787704134723867,
    15: 1.4637416002371149,
    16: 1.603572270783483,
    17: 2.2133516704858605,
    18: 2.3337578327353596,
    19: 0.8852433897072066}},
  {'scores': {'perplexity': 2232.5576171875,
    'coherence_20': array([1.43724819]),
    'diversity_euclidean': 0.06866043473174603,
    'diversity_jensenshannon': 0.690603452756782,
    'diversity_hellinger': 0.8067122772272636,
    'diversity_cosine': 0.8107928458029544},
   'topic_coherences': {0: 1.7300523146588405,
    1: 1.0011339322592363,
    2: 1.9563085816159047,
    3: 1.6460933884449667,
    4: 1.4232000182863762,
    5: 1.3338542382661231,
    6: 1.4898214631509419,
    7: 1.2641223306369482,
    8: 2.237799559639728,
    9: 0.97719939896769,
    10: 1.9824795351569895,
    11: 2.159035393982212,
    12: 0.764870588718921,
    13: 0.7674230110899558,
    14: 1.3479183851656573,
    15: 0.6903762780733693,
    16: 2.8450990542764627,
    17: 0.6990922223049143,
    18: 1.4874224091549701,
    19: 0.9416617210914205}}],
 10000000.0: [{'scores': {'perplexity': 2254.0302734375,
    'coherence_20': array([1.44661384]),
    'diversity_euclidean': 0.07098876188368566,
    'diversity_jensenshannon': 0.6994534389030087,
    'diversity_hellinger': 0.8181995008315643,
    'diversity_cosine': 0.8271404775495458},
   'topic_coherences': {0: 1.0542402859213311,
    1: 1.453658536717904,
    2: 1.4334904461780176,
    3: 1.028214544363564,
    4: 1.0096204089012255,
    5: 1.5539136077121654,
    6: 1.3994107963122735,
    7: 0.9778608908985309,
    8: 0.6195399396999054,
    9: 0.8006673680341132,
    10: 1.840761298075488,
    11: 1.2604398789491713,
    12: 1.7073209789137267,
    13: 1.8580910947101374,
    14: 1.4267776480811674,
    15: 1.6073534123690463,
    16: 2.0158025400053132,
    17: 2.636592011876535,
    18: 1.7554318141499257,
    19: 1.4930893269495578}},
  {'scores': {'perplexity': 2230.76171875,
    'coherence_20': array([1.46951214]),
    'diversity_euclidean': 0.0682264958820385,
    'diversity_jensenshannon': 0.6941507312844039,
    'diversity_hellinger': 0.8110619693634643,
    'diversity_cosine': 0.8159124260260446},
   'topic_coherences': {0: 0.6396204917880516,
    1: 1.4894742830800083,
    2: 1.3686757692061315,
    3: 0.6244184212210658,
    4: 0.9079345653122926,
    5: 1.510304355415203,
    6: 1.5123197870455498,
    7: 0.8088920857418463,
    8: 1.044643746742568,
    9: 1.8032848505598649,
    10: 1.0424381767166728,
    11: 3.6148133798456175,
    12: 1.8125303764407255,
    13: 1.432455365398278,
    14: 1.2787704134723867,
    15: 1.4637416002371149,
    16: 1.603572270783483,
    17: 2.2133516704858605,
    18: 2.3337578327353596,
    19: 0.8852433897072066}},
  {'scores': {'perplexity': 2232.70849609375,
    'coherence_20': array([1.4386688]),
    'diversity_euclidean': 0.068539312612949,
    'diversity_jensenshannon': 0.6907100356982321,
    'diversity_hellinger': 0.8068711624700667,
    'diversity_cosine': 0.8111620740492425},
   'topic_coherences': {0: 1.7300523146588405,
    1: 1.0011339322592363,
    2: 1.9563085816159047,
    3: 1.6460933884449667,
    4: 1.4232000182863762,
    5: 1.3338542382661231,
    6: 1.4898214631509419,
    7: 1.2641223306369482,
    8: 2.237799559639728,
    9: 0.9912228356454019,
    10: 1.9824795351569895,
    11: 2.159035393982212,
    12: 0.7792592625432258,
    13: 0.7674230110899558,
    14: 1.3479183851656573,
    15: 0.6903762780733693,
    16: 2.8450990542764627,
    17: 0.6990922223049143,
    18: 1.4874224091549701,
    19: 0.9416617210914205}}],
 100000000.0: [{'scores': {'perplexity': 2255.593505859375,
    'coherence_20': array([1.46393395]),
    'diversity_euclidean': 0.07071805930954278,
    'diversity_jensenshannon': 0.7013416231289901,
    'diversity_hellinger': 0.8207096338486365,
    'diversity_cosine': 0.8325058767497496},
   'topic_coherences': {0: 1.2523059169879707,
    1: 1.453658536717904,
    2: 1.4334904461780176,
    3: 1.028214544363564,
    4: 1.0692324469705354,
    5: 1.5397336823644967,
    6: 1.3994107963122735,
    7: 1.0627809584756542,
    8: 0.6195399396999054,
    9: 0.8006673680341132,
    10: 1.840761298075488,
    11: 1.2604398789491713,
    12: 1.7073209789137267,
    13: 1.8580910947101374,
    14: 1.4267776480811674,
    15: 1.6073534123690463,
    16: 2.0158025400053132,
    17: 2.636592011876535,
    18: 1.7554318141499257,
    19: 1.5110737464760944}},
  {'scores': {'perplexity': 2232.280517578125,
    'coherence_20': array([1.49229642]),
    'diversity_euclidean': 0.06725831747181896,
    'diversity_jensenshannon': 0.6956768849856158,
    'diversity_hellinger': 0.8132005008377698,
    'diversity_cosine': 0.8214248350037998},
   'topic_coherences': {0: 0.6396204917880515,
    1: 1.4894742830800083,
    2: 1.3686757692061309,
    3: 0.6894655494384608,
    4: 1.0432980653928652,
    5: 1.5103043554152034,
    6: 1.614713158111078,
    7: 0.8635925359735489,
    8: 1.1392559054050289,
    9: 1.8032848505598649,
    10: 1.1238591216746587,
    11: 3.6148133798456175,
    12: 1.8125303764407255,
    13: 1.4461977775860198,
    14: 1.2787704134723867,
    15: 1.463741600237115,
    16: 1.5119778458649786,
    17: 2.2133516704858605,
    18: 2.3337578327353596,
    19: 0.8852433897072066}},
  {'scores': {'perplexity': 2234.585693359375,
    'coherence_20': array([1.45325411]),
    'diversity_euclidean': 0.06752653864309156,
    'diversity_jensenshannon': 0.6920605915115405,
    'diversity_hellinger': 0.8087811446427607,
    'diversity_cosine': 0.8153091247178301},
   'topic_coherences': {0: 1.7300523146588405,
    1: 1.0011339322592363,
    2: 1.9563085816159047,
    3: 1.6460933884449667,
    4: 1.4232000182863762,
    5: 1.3714624095551446,

In [43]:
new_result

{'scores': {'perplexity': 2461.866943359375,
  'coherence_20': array([1.85850209]),
  'diversity_euclidean': 0.07356362067834214,
  'diversity_jensenshannon': 0.7711511659469856,
  'diversity_hellinger': 0.9155164493873434,
  'diversity_cosine': 0.9444821285586293},
 'topic_coherences': {0: 1.7300523146588405,
  1: 1.5709401517076538,
  2: 1.9563085816159047,
  3: 1.6460933884449667,
  4: 2.26887264809252,
  5: 2.133835008205159,
  6: 2.107893087858345,
  7: 1.6728566636808413,
  8: 2.237799559639728,
  9: 1.8893206007995285,
  10: 1.9824795351569895,
  11: 2.159035393982212,
  12: 0.9739755322110191,
  13: 2.2229610002548172,
  14: 1.2609566862135837,
  15: 1.6770159675711767,
  16: 2.8450990542764627,
  17: 1.6517525523607473,
  18: 2.116133177601322,
  19: 1.066660946339064}}

In [44]:
fix_regularizer._topic_names

['topic_0',
 'topic_2',
 'topic_3',
 'topic_8',
 'topic_10',
 'topic_11',
 'topic_16']

In [45]:
del model

In [76]:
results = dict()

DECORRELATOR_REGULARIZER_CLASS = DecorrelatorWithOtherPhiRegularizer

#  Best: 100  12.32470703125
# Close: 10   12.325764973958485
#        1000 12.325927734375

# Edgy:
# 100000.0 13.08170572916697
# 1000000.0 72.53548177083348

# DECORRELATION_TAUS = [100, 1000]  # Best
DECORRELATION_TAUS = [100000, 1000000]  # Dangerous

for decorrelation_tau in DECORRELATION_TAUS:
    key = decorrelation_tau
    results[key] = []

    print(key)

    prev_model = None
    good_topic_names = list()
    bad_topic_names = None
    not_good_topic_names = None
    bad_phi = None
    seed = 0

    while seed < MAX_NUM_TRAINS and len(good_topic_names) < NUM_TOPICS:
        print(seed)

        if seed == 0:
            prev_model = init_model_from_family(
                family=KnownModel.ARTM,
                dataset=dataset,
                main_modality=MAIN_MODALITY,
                num_topics=NUM_TOPICS,
                seed=seed,
                model_params={
                    'decorrelation_tau': 0.01,  # best values
                    'smooth_bcg_tau': 0.05,
                    'sparse_sp_tau': -0.05,
                }
            )

            for reg in prev_model.regularizers.data:
                print(f"{reg}: {prev_model.regularizers[reg].tau}")
    
            result = fit_and_compute_scores(prev_model, dataset)
            results[key].append(result)

            assert len(results[key]) == seed + 1
    
            
            good_topic_indices = [
                t for t, c in result['topic_coherences'].items() if t in TOPIC_INDICES and is_good(c)
            ]
            bad_topic_indices = [
                t for t, c in result['topic_coherences'].items() if t in TOPIC_INDICES and is_bad(c)
            ]
            not_good_topic_indices = [
                t for t in TOPIC_INDICES if t not in good_topic_indices
            ]
            
            phi = prev_model.get_phi()
            good_topic_names = [phi.columns[t] for t in good_topic_indices]
            bad_topic_names = [phi.columns[t] for t in bad_topic_indices]
            not_good_topic_names = [phi.columns[t] for t in not_good_topic_indices]

            assert len(good_topic_names) > 0
            assert len(bad_topic_names) > 0
            assert set(bad_topic_names) <= set(not_good_topic_names)
            assert not any(t in not_good_topic_names for t in good_topic_names)
            assert len(good_topic_names) + len(not_good_topic_names) == NUM_TOPICS

            assert 'num_topics' not in results[key][-1]

            results[key][-1]['num_topics'] = {
                'good': len(good_topic_names),
                'bad': len(bad_topic_names),
                'not_good': len(not_good_topic_names),
                'total_bad': len(bad_topic_names),
            }

            print(f"num_topics: {results[key][-1]['num_topics']}")

            seed += 1
            
            del result, phi
            model = None

        else:

            fix_regularizer = FastFixPhiRegularizer(
                name='fix',
                parent_model=prev_model._model,
                topic_names=good_topic_names,
            )
            
            cur_bad_phi = prev_model._model.get_phi()[bad_topic_names]

            if bad_phi is None:
                bad_phi = cur_bad_phi
            else:
                # bad_phi.rename(
                #     columns={n: f'm1_{n}' for n in bad_topic_names}, inplace=True
                # )
                bad_phi = pd.concat([bad_phi, cur_bad_phi], axis=1)
    
            bad_phi = deepcopy(bad_phi)
            decorr_bad_regularizer = DECORRELATOR_REGULARIZER_CLASS(
                name='ext_decorr_bad', tau=decorrelation_tau,
                topic_names=not_good_topic_names,
                other_phi=bad_phi
            )
            
            good_phi = prev_model._model.get_phi()[good_topic_names]
            good_phi = deepcopy(good_phi)
            decorr_good_regularizer = DECORRELATOR_REGULARIZER_CLASS(
                name='ext_decorr_good', tau=decorrelation_tau,
                topic_names=not_good_topic_names,
                other_phi=good_phi
            )
        
    
            new_model = init_model_from_family(
                family=KnownModel.ARTM,
                dataset=dataset,
                main_modality=MAIN_MODALITY,
                num_topics=NUM_TOPICS,
                seed=seed,
                specific_topic_names=not_good_topic_names,
                model_params={
                    'decorrelation_tau': 0.01,
                    'smooth_bcg_tau': 0.05,
                    'sparse_sp_tau': -0.05,
                }
            )
            custom_regularizers = {
                fix_regularizer.name: fix_regularizer,
                decorr_bad_regularizer.name: decorr_bad_regularizer,
                decorr_good_regularizer.name: decorr_good_regularizer,
            }
    
            new_result = fit_and_compute_scores(new_model, dataset, custom_regularizers=custom_regularizers)
            
            for reg in new_model.regularizers.data:
                print(f"{reg}: {new_model.regularizers[reg].tau}")
    
            for reg_name, reg in custom_regularizers.items():
                print(f"{reg_name}: {reg.tau}")
    
            
            results[key].append(new_result)

            assert len(results[key]) == seed + 1


            
            good_topic_indices = [
                t for t, c in new_result['topic_coherences'].items() if t in TOPIC_INDICES and is_good(c)
            ]
            bad_topic_indices = [
                t for t, c in new_result['topic_coherences'].items() if t in TOPIC_INDICES and is_bad(c)
            ]
            not_good_topic_indices = [
                t for t in TOPIC_INDICES if t not in good_topic_indices
            ]
            
            phi = new_model.get_phi()
            new_good_topic_names = [phi.columns[t] for t in good_topic_indices]
            new_bad_topic_names = [phi.columns[t] for t in bad_topic_indices]
            new_not_good_topic_names = [phi.columns[t] for t in not_good_topic_indices]

            assert len(new_good_topic_names) > 0
            # assert len(new_bad_topic_names) > 0
            assert set(new_bad_topic_names) <= set(new_not_good_topic_names)
            assert not any(t in new_not_good_topic_names for t in new_good_topic_names)
            assert len(new_good_topic_names) + len(new_not_good_topic_names) == NUM_TOPICS

            assert set(good_topic_names) <= set(new_good_topic_names)
            # assert len(new_bad_topic_names) <= len(bad_topic_names)

            if len(new_good_topic_names) > len(good_topic_names):
                print('SUCCESS: more good topics')
            if len(new_bad_topic_names) < len(bad_topic_names):
                print('SUCCESS: less bad topics')
            if len(new_bad_topic_names) > len(bad_topic_names):
                print('DOWNFALL: more bad topics...')
            if len(new_bad_topic_names) == 0:
                print('SUCCESS: no bad topics!')
    
            good_topic_names = new_good_topic_names
            bad_topic_names = new_bad_topic_names
            not_good_topic_names = new_not_good_topic_names

            
            assert 'num_topics' not in results[key][-1]

            results[key][-1]['num_topics'] = {
                'good': len(good_topic_names),
                'bad': len(bad_topic_names),
                'not_good': len(not_good_topic_names),
                'total_bad': bad_phi.shape[1] + len(bad_topic_names),
            }

            prev_model = new_model

            print(f"num_topics: {results[key][-1]['num_topics']}")

            seed += 1

100000
0
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
num_topics: {'good': 6, 'bad': 2, 'not_good': 14, 'total_bad': 2}
1

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f12388778e0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f123a6ecf40>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f123b1d57c0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.0684473508802884
sparse_theta_sp: -0.319457311284836
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000
ext_decorr_good: 100000
SUCCESS: more good topics
DOWNFALL: more bad topics...
num_topics: {'good': 8, 'bad': 3, 'not_good': 12, 'total_bad': 5}
2

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f121d04cc10>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f1238a85e20>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f1218bb7d00>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.07985524269366981
sparse_theta_sp: -0.37270019649897534
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000
ext_decorr_good: 100000
SUCCESS: less bad topics
num_topics: {'good': 8, 'bad': 2, 'not_good': 12, 'total_bad': 7}
3

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f1238abf5b0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f123b04fc70>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f121d042be0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.07985524269366981
sparse_theta_sp: -0.37270019649897534
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000
ext_decorr_good: 100000
SUCCESS: more good topics
num_topics: {'good': 10, 'bad': 2, 'not_good': 10, 'total_bad': 9}
4

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f121d1f3910>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f121d1f34f0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f121d04cfd0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.09582629123240377
sparse_theta_sp: -0.4472402357987704
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000
ext_decorr_good: 100000
SUCCESS: more good topics
num_topics: {'good': 13, 'bad': 2, 'not_good': 7, 'total_bad': 11}
5

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f1218a5edc0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f121d5b7700>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f123ad69910>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1368947017605768
sparse_theta_sp: -0.638914622569672
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000
ext_decorr_good: 100000
num_topics: {'good': 13, 'bad': 2, 'not_good': 7, 'total_bad': 13}
6

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f1239e70070>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f12388778e0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f123a6ecf40>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1368947017605768
sparse_theta_sp: -0.638914622569672
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000
ext_decorr_good: 100000
SUCCESS: less bad topics
num_topics: {'good': 13, 'bad': 1, 'not_good': 7, 'total_bad': 14}
7

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f123a95ec10>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f121d6e3cd0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f12399c8b50>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1368947017605768
sparse_theta_sp: -0.638914622569672
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000
ext_decorr_good: 100000
SUCCESS: more good topics
num_topics: {'good': 15, 'bad': 1, 'not_good': 5, 'total_bad': 15}
8

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f121d79d460>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f123ad69910>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f121d06c2e0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.19165258246480754
sparse_theta_sp: -0.8944804715975408
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000
ext_decorr_good: 100000
num_topics: {'good': 15, 'bad': 1, 'not_good': 5, 'total_bad': 16}
9

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f123aebe220>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f1218e7aa60>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f123aebe7c0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.19165258246480754
sparse_theta_sp: -0.8944804715975408
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000
ext_decorr_good: 100000
SUCCESS: more good topics
SUCCESS: less bad topics
SUCCESS: no bad topics!
num_topics: {'good': 17, 'bad': 0, 'not_good': 3, 'total_bad': 16}
10

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f121d043ca0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f1218daceb0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f1239a717c0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.31942097077467924
sparse_theta_sp: -1.4908007859959014
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000
ext_decorr_good: 100000
SUCCESS: more good topics
SUCCESS: no bad topics!
num_topics: {'good': 18, 'bad': 0, 'not_good': 2, 'total_bad': 16}
11

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f1238fce7c0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f1218eb3ca0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f1238ff1610>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.47913145616201885
sparse_theta_sp: -2.236201178993852
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000
ext_decorr_good: 100000
SUCCESS: more good topics
SUCCESS: no bad topics!
num_topics: {'good': 19, 'bad': 0, 'not_good': 1, 'total_bad': 16}
12

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f123a95e7c0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f121d6fcb80>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f1238abf670>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.9582629123240377
sparse_theta_sp: -4.472402357987704
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000
ext_decorr_good: 100000
DOWNFALL: more bad topics...
num_topics: {'good': 19, 'bad': 1, 'not_good': 1, 'total_bad': 17}
13

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f1218daceb0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f1218e555b0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f1218e7aa60>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.9582629123240377
sparse_theta_sp: -4.472402357987704
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000
ext_decorr_good: 100000
num_topics: {'good': 19, 'bad': 1, 'not_good': 1, 'total_bad': 18}
14

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f121d00a0d0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f123aa6c760>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f121d028f10>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.9582629123240377
sparse_theta_sp: -4.472402357987704
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000
ext_decorr_good: 100000
num_topics: {'good': 19, 'bad': 1, 'not_good': 1, 'total_bad': 19}
15

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f121d56b730>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f12388778e0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f1218e7aa60>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.9582629123240377
sparse_theta_sp: -4.472402357987704
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000
ext_decorr_good: 100000
num_topics: {'good': 19, 'bad': 1, 'not_good': 1, 'total_bad': 20}
16

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f1239c13430>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f1218e555b0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f12399af670>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.9582629123240377
sparse_theta_sp: -4.472402357987704
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000
ext_decorr_good: 100000
num_topics: {'good': 19, 'bad': 1, 'not_good': 1, 'total_bad': 21}
17

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f1218b02400>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f1238f869a0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f12607addf0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.9582629123240377
sparse_theta_sp: -4.472402357987704
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000
ext_decorr_good: 100000
num_topics: {'good': 19, 'bad': 1, 'not_good': 1, 'total_bad': 22}
18

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f123a9581c0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f123b28c160>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f121d028b20>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.9582629123240377
sparse_theta_sp: -4.472402357987704
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000
ext_decorr_good: 100000
num_topics: {'good': 19, 'bad': 1, 'not_good': 1, 'total_bad': 23}
19

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f1218d683d0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f1218c212e0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f1239a715b0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.9582629123240377
sparse_theta_sp: -4.472402357987704
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000
ext_decorr_good: 100000
num_topics: {'good': 19, 'bad': 1, 'not_good': 1, 'total_bad': 24}
1000000
0
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
num_topics: {'good': 6, 'bad': 2, 'not_good': 14, 'total_bad': 2}
1

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f121d302f40>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f1239cff490>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f121d6fcb80>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.0684473508802884
sparse_theta_sp: -0.319457311284836
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 1000000
ext_decorr_good: 1000000
SUCCESS: more good topics
SUCCESS: less bad topics
num_topics: {'good': 14, 'bad': 1, 'not_good': 6, 'total_bad': 3}
2

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f1218eb3ca0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f121d39feb0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f1239cff190>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.15971048538733962
sparse_theta_sp: -0.7454003929979507
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 1000000
ext_decorr_good: 1000000
SUCCESS: more good topics
SUCCESS: less bad topics
SUCCESS: no bad topics!
num_topics: {'good': 18, 'bad': 0, 'not_good': 2, 'total_bad': 3}
3

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f123ae91640>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f1239a71460>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f123ae915b0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.47913145616201885
sparse_theta_sp: -2.236201178993852
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 1000000
ext_decorr_good: 1000000
SUCCESS: more good topics
DOWNFALL: more bad topics...
num_topics: {'good': 19, 'bad': 1, 'not_good': 1, 'total_bad': 4}
4

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f123aed1e80>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f12399e5160>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f1218d687f0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.9582629123240377
sparse_theta_sp: -4.472402357987704
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 1000000
ext_decorr_good: 1000000
num_topics: {'good': 19, 'bad': 1, 'not_good': 1, 'total_bad': 5}
5

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f123aa98be0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f1239cff490>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f123aee09d0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.9582629123240377
sparse_theta_sp: -4.472402357987704
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 1000000
ext_decorr_good: 1000000
num_topics: {'good': 19, 'bad': 1, 'not_good': 1, 'total_bad': 6}
6

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f1218d437c0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f12399e5160>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f1218f2db80>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.9582629123240377
sparse_theta_sp: -4.472402357987704
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 1000000
ext_decorr_good: 1000000
num_topics: {'good': 19, 'bad': 1, 'not_good': 1, 'total_bad': 7}
7

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f12389167f0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f1238916700>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f123993efa0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.9582629123240377
sparse_theta_sp: -4.472402357987704
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 1000000
ext_decorr_good: 1000000
SUCCESS: less bad topics
SUCCESS: no bad topics!
num_topics: {'good': 19, 'bad': 0, 'not_good': 1, 'total_bad': 7}
8

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f12389057c0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f123aee09d0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f123a7bca90>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.9582629123240377
sparse_theta_sp: -4.472402357987704
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 1000000
ext_decorr_good: 1000000
DOWNFALL: more bad topics...
num_topics: {'good': 19, 'bad': 1, 'not_good': 1, 'total_bad': 8}
9

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f1218f2da30>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f123b1d85b0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f1239a71460>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.9582629123240377
sparse_theta_sp: -4.472402357987704
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 1000000
ext_decorr_good: 1000000
SUCCESS: less bad topics
SUCCESS: no bad topics!
num_topics: {'good': 19, 'bad': 0, 'not_good': 1, 'total_bad': 8}
10

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f123aac8ca0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f123993efa0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f123ad69910>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.9582629123240377
sparse_theta_sp: -4.472402357987704
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 1000000
ext_decorr_good: 1000000
DOWNFALL: more bad topics...
num_topics: {'good': 19, 'bad': 1, 'not_good': 1, 'total_bad': 9}
11

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f123a7aad30>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f1218d437c0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f121d06e130>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.9582629123240377
sparse_theta_sp: -4.472402357987704
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 1000000
ext_decorr_good: 1000000
num_topics: {'good': 19, 'bad': 1, 'not_good': 1, 'total_bad': 10}
12

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f121d056f40>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f12389164f0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f123b2d7670>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.9582629123240377
sparse_theta_sp: -4.472402357987704
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 1000000
ext_decorr_good: 1000000
num_topics: {'good': 19, 'bad': 1, 'not_good': 1, 'total_bad': 11}
13

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f123911d190>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f1238ff1dc0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f123aae4370>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.9582629123240377
sparse_theta_sp: -4.472402357987704
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 1000000
ext_decorr_good: 1000000
num_topics: {'good': 19, 'bad': 1, 'not_good': 1, 'total_bad': 12}
14

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f123b2d7670>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f123993efa0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f121d4a5f40>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.9582629123240377
sparse_theta_sp: -4.472402357987704
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 1000000
ext_decorr_good: 1000000
SUCCESS: less bad topics
SUCCESS: no bad topics!
num_topics: {'good': 19, 'bad': 0, 'not_good': 1, 'total_bad': 12}
15

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f12390d02b0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f1218d437c0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f12390d01f0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.9582629123240377
sparse_theta_sp: -4.472402357987704
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 1000000
ext_decorr_good: 1000000
DOWNFALL: more bad topics...
num_topics: {'good': 19, 'bad': 1, 'not_good': 1, 'total_bad': 13}
16

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f121d2d8400>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f123aa63fd0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f121d4a5f40>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.9582629123240377
sparse_theta_sp: -4.472402357987704
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 1000000
ext_decorr_good: 1000000
num_topics: {'good': 19, 'bad': 1, 'not_good': 1, 'total_bad': 14}
17

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f12399e5160>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f123a6ecf40>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f123ab21670>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.9582629123240377
sparse_theta_sp: -4.472402357987704
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 1000000
ext_decorr_good: 1000000
num_topics: {'good': 19, 'bad': 1, 'not_good': 1, 'total_bad': 15}
18

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f121d4a5f40>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f123aa4ed30>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f123af1cdc0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.9582629123240377
sparse_theta_sp: -4.472402357987704
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 1000000
ext_decorr_good: 1000000
SUCCESS: less bad topics
SUCCESS: no bad topics!
num_topics: {'good': 19, 'bad': 0, 'not_good': 1, 'total_bad': 15}
19

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f123a6ecf40>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f1218b9d5b0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f121d390430>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.9582629123240377
sparse_theta_sp: -4.472402357987704
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 1000000
ext_decorr_good: 1000000
DOWNFALL: more bad topics...
num_topics: {'good': 19, 'bad': 1, 'not_good': 1, 'total_bad': 16}

In [77]:
1

1

In [78]:
results.keys()

dict_keys([100000, 1000000])

In [79]:
for k, r in results.items():
    for s in r:
        s['scores']['coherence_20'] = float(s['scores']['coherence_20'])

In [27]:
import json

SAVE_FOLDER = 'results/20newsgroups'

! mkdir -p $SAVE_FOLDER

In [30]:
results[100][0]

{'scores': {'perplexity': 2236.79248046875,
  'coherence_20': 1.4469243975267287,
  'diversity_euclidean': 0.06941780360242247,
  'diversity_jensenshannon': 0.6988145697570417,
  'diversity_hellinger': 0.8168150929911163,
  'diversity_cosine': 0.8307823760072601},
 'topic_coherences': {0: 1.1491291917105928,
  1: 1.5517711527505458,
  2: 1.405924126520918,
  3: 1.0506564618250258,
  4: 1.1270220165324627,
  5: 1.5564847213025248,
  6: 1.3764434481297354,
  7: 0.9760657812912945,
  8: 0.6237645959171805,
  9: 0.7385423660674926,
  10: 1.840761298075488,
  11: 1.330514926154629,
  12: 1.7073209789137267,
  13: 1.8580910947101374,
  14: 1.3211340090044137,
  15: 1.4857567187040455,
  16: 2.0158025400053132,
  17: 2.636592011876535,
  18: 1.7554318141499257,
  19: 1.4312786968925868},
 'num_topics': {'good': 6, 'bad': 2, 'not_good': 14, 'total_bad': 2}}

In [80]:
for k, r in results.items():
    with open(SAVE_FOLDER + f'/iterative_{int(k)}.json', 'w') as f:
        f.write(
            json.dumps(r, indent=4)
        )

In [44]:
! ls $SAVE_FOLDER

decorrelation.json   iterative2_1000000.json  plsa.json
iterative_1000.json  iterative2_100000.json   sparse.json
iterative_100.json   lda.json		      tless.json

In [46]:
! tail -n 50 $SAVE_FOLDER/iterative_100.json

            "17": 2.636592011876535,
            "18": 1.7554318141499257,
            "19": 1.640629444035244
        },
        "num_topics": {
            "good": 13,
            "bad": 4,
            "not_good": 7,
            "total_bad": 54
        }
    },
    {
        "scores": {
            "perplexity": 2399.683349609375,
            "coherence_20": 1.5343349867118177,
            "diversity_euclidean": 0.07490313695236982,
            "diversity_jensenshannon": 0.709611598639548,
            "diversity_hellinger": 0.8321301188245224,
            "diversity_cosine": 0.8474179226005811
        },
        "topic_coherences": {
            "0": 0.9217079965108185,
            "1": 1.3621768174895768,
            "2": 1.6694630947055196,
            "3": 0.8541021951209471,
            "4": 0.9697594159537758,
            "5": 0.6067957005801524,
            "6": 1.8054658007396136,
            "7": 0.9076733045710277,
            "8": 0.9002829919095333,
            "9": 1.6300267904928862,
            "10": 1.840761298075488,
            "11": 1.8250263857445232,
            "12": 1.7073209789137267,
            "13": 1.8580910947101374,
            "14": 1.6809928119557065,
            "15": 2.0985972466959013,
            "16": 2.0158025400053132,
            "17": 2.636592011876535,
            "18": 1.7554318141499257,
            "19": 1.640629444035244
        },
        "num_topics": {
            "good": 13,
            "bad": 1,
            "not_good": 7,
            "total_bad": 55
        }
    }
]

In [47]:
! tail -n 50 $SAVE_FOLDER/iterative_1000.json

            "17": 2.636592011876535,
            "18": 1.7554318141499257,
            "19": 1.640629444035244
        },
        "num_topics": {
            "good": 13,
            "bad": 4,
            "not_good": 7,
            "total_bad": 54
        }
    },
    {
        "scores": {
            "perplexity": 2399.755859375,
            "coherence_20": 1.5422349498469412,
            "diversity_euclidean": 0.07488431260088221,
            "diversity_jensenshannon": 0.7099821904985755,
            "diversity_hellinger": 0.8326169812227255,
            "diversity_cosine": 0.8487093680907188
        },
        "topic_coherences": {
            "0": 1.00113211617019,
            "1": 1.3621768174895768,
            "2": 1.6694630947055196,
            "3": 0.901739498209401,
            "4": 0.9697594159537758,
            "5": 0.6067957005801523,
            "6": 1.8054658007396136,
            "7": 0.9076733045710277,
            "8": 0.9312208318641825,
            "9": 1.6300267904928862,
            "10": 1.840761298075488,
            "11": 1.825026385744523,
            "12": 1.7073209789137267,
            "13": 1.8580910947101374,
            "14": 1.6809928119557065,
            "15": 2.0985972466959013,
            "16": 2.0158025400053132,
            "17": 2.636592011876535,
            "18": 1.7554318141499257,
            "19": 1.640629444035244
        },
        "num_topics": {
            "good": 13,
            "bad": 1,
            "not_good": 7,
            "total_bad": 55
        }
    }
]

In [ ]:
results.keys()

In [ ]:
results[1000][-1]

In [81]:
results = dict()

DECORRELATOR_REGULARIZER_CLASS = DecorrelatorWithOtherPhiRegularizer2

#  Best: 100000  12.32535807291697
# Close: 1000000 12.33203125
#        10000   12.325764973958485

# Edgy:
# 10000000.0 12.48234049479197
# 100000000.0 14.13541666666697
# 1000000000.0 58.58935546875

# DECORRELATION_TAUS = [100000, 1000000]  # Best
DECORRELATION_TAUS = [10000000, 100000000, 1000000000]  # Dangerous

for decorrelation_tau in DECORRELATION_TAUS:
    key = decorrelation_tau
    results[key] = []

    print(key)

    prev_model = None
    good_topic_names = list()
    bad_topic_names = None
    not_good_topic_names = None
    bad_phi = None
    seed = 0

    while seed < MAX_NUM_TRAINS and len(good_topic_names) < NUM_TOPICS:
        print(seed)

        if seed == 0:
            prev_model = init_model_from_family(
                family=KnownModel.ARTM,
                dataset=dataset,
                main_modality=MAIN_MODALITY,
                num_topics=NUM_TOPICS,
                seed=seed,
                model_params={
                    'decorrelation_tau': 0.01,  # best values
                    'smooth_bcg_tau': 0.05,
                    'sparse_sp_tau': -0.05,
                }
            )

            for reg in prev_model.regularizers.data:
                print(f"{reg}: {prev_model.regularizers[reg].tau}")
    
            result = fit_and_compute_scores(prev_model, dataset)
            results[key].append(result)

            assert len(results[key]) == seed + 1
    
            
            good_topic_indices = [
                t for t, c in result['topic_coherences'].items() if t in TOPIC_INDICES and is_good(c)
            ]
            bad_topic_indices = [
                t for t, c in result['topic_coherences'].items() if t in TOPIC_INDICES and is_bad(c)
            ]
            not_good_topic_indices = [
                t for t in TOPIC_INDICES if t not in good_topic_indices
            ]
            
            phi = prev_model.get_phi()
            good_topic_names = [phi.columns[t] for t in good_topic_indices]
            bad_topic_names = [phi.columns[t] for t in bad_topic_indices]
            not_good_topic_names = [phi.columns[t] for t in not_good_topic_indices]

            assert len(good_topic_names) > 0
            assert len(bad_topic_names) > 0
            assert set(bad_topic_names) <= set(not_good_topic_names)
            assert not any(t in not_good_topic_names for t in good_topic_names)
            assert len(good_topic_names) + len(not_good_topic_names) == NUM_TOPICS

            assert 'num_topics' not in results[key][-1]

            results[key][-1]['num_topics'] = {
                'good': len(good_topic_names),
                'bad': len(bad_topic_names),
                'not_good': len(not_good_topic_names),
                'total_bad': len(bad_topic_names),
            }

            print(f"num_topics: {results[key][-1]['num_topics']}")

            seed += 1
            
            del result, phi
            model = None

        else:

            fix_regularizer = FastFixPhiRegularizer(
                name='fix',
                parent_model=prev_model._model,
                topic_names=good_topic_names,
            )
            
            cur_bad_phi = prev_model._model.get_phi()[bad_topic_names]

            if bad_phi is None:
                bad_phi = cur_bad_phi
            else:
                # bad_phi.rename(
                #     columns={n: f'm1_{n}' for n in bad_topic_names}, inplace=True
                # )
                bad_phi = pd.concat([bad_phi, cur_bad_phi], axis=1)
    
            bad_phi = deepcopy(bad_phi)
            decorr_bad_regularizer = DECORRELATOR_REGULARIZER_CLASS(
                name='ext_decorr_bad', tau=decorrelation_tau,
                topic_names=not_good_topic_names,
                other_phi=bad_phi
            )
            
            good_phi = prev_model._model.get_phi()[good_topic_names]
            good_phi = deepcopy(good_phi)
            decorr_good_regularizer = DECORRELATOR_REGULARIZER_CLASS(
                name='ext_decorr_good', tau=decorrelation_tau,
                topic_names=not_good_topic_names,
                other_phi=good_phi
            )
        
    
            new_model = init_model_from_family(
                family=KnownModel.ARTM,
                dataset=dataset,
                main_modality=MAIN_MODALITY,
                num_topics=NUM_TOPICS,
                seed=seed,
                specific_topic_names=not_good_topic_names,
                model_params={
                    'decorrelation_tau': 0.01,
                    'smooth_bcg_tau': 0.05,
                    'sparse_sp_tau': -0.05,
                }
            )
            custom_regularizers = {
                fix_regularizer.name: fix_regularizer,
                decorr_bad_regularizer.name: decorr_bad_regularizer,
                decorr_good_regularizer.name: decorr_good_regularizer,
            }
    
            new_result = fit_and_compute_scores(new_model, dataset, custom_regularizers=custom_regularizers)
            
            for reg in new_model.regularizers.data:
                print(f"{reg}: {new_model.regularizers[reg].tau}")
    
            for reg_name, reg in custom_regularizers.items():
                print(f"{reg_name}: {reg.tau}")
    
            
            results[key].append(new_result)

            assert len(results[key]) == seed + 1


            
            good_topic_indices = [
                t for t, c in new_result['topic_coherences'].items() if t in TOPIC_INDICES and is_good(c)
            ]
            bad_topic_indices = [
                t for t, c in new_result['topic_coherences'].items() if t in TOPIC_INDICES and is_bad(c)
            ]
            not_good_topic_indices = [
                t for t in TOPIC_INDICES if t not in good_topic_indices
            ]
            
            phi = new_model.get_phi()
            new_good_topic_names = [phi.columns[t] for t in good_topic_indices]
            new_bad_topic_names = [phi.columns[t] for t in bad_topic_indices]
            new_not_good_topic_names = [phi.columns[t] for t in not_good_topic_indices]

            assert len(new_good_topic_names) > 0
            # assert len(new_bad_topic_names) > 0
            assert set(new_bad_topic_names) <= set(new_not_good_topic_names)
            assert not any(t in new_not_good_topic_names for t in new_good_topic_names)
            assert len(new_good_topic_names) + len(new_not_good_topic_names) == NUM_TOPICS

            assert set(good_topic_names) <= set(new_good_topic_names)
            # assert len(new_bad_topic_names) <= len(bad_topic_names)

            if len(new_good_topic_names) > len(good_topic_names):
                print('SUCCESS: more good topics')
            if len(new_bad_topic_names) < len(bad_topic_names):
                print('SUCCESS: less bad topics')
            if len(new_bad_topic_names) > len(bad_topic_names):
                print('DOWNFALL: more bad topics...')
            if len(new_bad_topic_names) == 0:
                print('SUCCESS: no bad topics!')
    
            good_topic_names = new_good_topic_names
            bad_topic_names = new_bad_topic_names
            not_good_topic_names = new_not_good_topic_names

            
            assert 'num_topics' not in results[key][-1]

            results[key][-1]['num_topics'] = {
                'good': len(good_topic_names),
                'bad': len(bad_topic_names),
                'not_good': len(not_good_topic_names),
                'total_bad': bad_phi.shape[1] + len(bad_topic_names),
            }

            prev_model = new_model

            print(f"num_topics: {results[key][-1]['num_topics']}")

            seed += 1

10000000
0
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
num_topics: {'good': 6, 'bad': 2, 'not_good': 14, 'total_bad': 2}
1

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f123b2d60a0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f123ab218e0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f12188032b0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.0684473508802884
sparse_theta_sp: -0.319457311284836
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 10000000
ext_decorr_good: 10000000
SUCCESS: more good topics
DOWNFALL: more bad topics...
num_topics: {'good': 8, 'bad': 3, 'not_good': 12, 'total_bad': 5}
2

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f1238a85ca0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f121d390430>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f12399e5160>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.07985524269366981
sparse_theta_sp: -0.37270019649897534
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 10000000
ext_decorr_good: 10000000
num_topics: {'good': 8, 'bad': 3, 'not_good': 12, 'total_bad': 8}
3

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f123ac1cf70>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f123aebe490>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f123ab21be0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.07985524269366981
sparse_theta_sp: -0.37270019649897534
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 10000000
ext_decorr_good: 10000000
SUCCESS: more good topics
num_topics: {'good': 10, 'bad': 3, 'not_good': 10, 'total_bad': 11}
4

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f123aebea90>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f12399e5160>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f123aac8ca0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.09582629123240377
sparse_theta_sp: -0.4472402357987704
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 10000000
ext_decorr_good: 10000000
SUCCESS: more good topics
num_topics: {'good': 11, 'bad': 3, 'not_good': 9, 'total_bad': 14}
5

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f123a981640>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f123aae4be0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f123ab21d90>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1064736569248931
sparse_theta_sp: -0.4969335953319671
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 10000000
ext_decorr_good: 10000000
DOWNFALL: more bad topics...
num_topics: {'good': 11, 'bad': 4, 'not_good': 9, 'total_bad': 18}
6

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f1218b9d6d0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f1238905a00>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f123ab21be0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1064736569248931
sparse_theta_sp: -0.4969335953319671
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 10000000
ext_decorr_good: 10000000
SUCCESS: less bad topics
num_topics: {'good': 11, 'bad': 1, 'not_good': 9, 'total_bad': 19}
7

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f1238948af0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f1218b9e880>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f1218b21580>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1064736569248931
sparse_theta_sp: -0.4969335953319671
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 10000000
ext_decorr_good: 10000000
SUCCESS: more good topics
DOWNFALL: more bad topics...
num_topics: {'good': 12, 'bad': 4, 'not_good': 8, 'total_bad': 23}
8

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f1238a85ca0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f123aa63fd0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f123adab730>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.11978286404050471
sparse_theta_sp: -0.559050294748463
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 10000000
ext_decorr_good: 10000000
SUCCESS: less bad topics
num_topics: {'good': 12, 'bad': 3, 'not_good': 8, 'total_bad': 26}
9

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f1218844400>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f123ab21670>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f121d06c340>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.11978286404050471
sparse_theta_sp: -0.559050294748463
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 10000000
ext_decorr_good: 10000000
SUCCESS: more good topics
SUCCESS: less bad topics
num_topics: {'good': 13, 'bad': 1, 'not_good': 7, 'total_bad': 27}
10

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f1218d687f0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f1238948af0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f1218844580>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1368947017605768
sparse_theta_sp: -0.638914622569672
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 10000000
ext_decorr_good: 10000000
DOWNFALL: more bad topics...
num_topics: {'good': 13, 'bad': 4, 'not_good': 7, 'total_bad': 31}
11

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f123adffa30>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f123adabfa0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f123adffa60>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1368947017605768
sparse_theta_sp: -0.638914622569672
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 10000000
ext_decorr_good: 10000000
SUCCESS: less bad topics
num_topics: {'good': 13, 'bad': 2, 'not_good': 7, 'total_bad': 33}
12

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f123b03abb0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f123adabd90>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f123b03adf0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1368947017605768
sparse_theta_sp: -0.638914622569672
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 10000000
ext_decorr_good: 10000000
SUCCESS: less bad topics
num_topics: {'good': 13, 'bad': 1, 'not_good': 7, 'total_bad': 34}
13

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f1239e70070>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f121880d7c0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f121880d7f0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1368947017605768
sparse_theta_sp: -0.638914622569672
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 10000000
ext_decorr_good: 10000000
num_topics: {'good': 13, 'bad': 1, 'not_good': 7, 'total_bad': 35}
14

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f1218f33fa0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f1216790130>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f121d0c3bb0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1368947017605768
sparse_theta_sp: -0.638914622569672
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 10000000
ext_decorr_good: 10000000
DOWNFALL: more bad topics...
num_topics: {'good': 13, 'bad': 3, 'not_good': 7, 'total_bad': 38}
15

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f1239e456d0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f123aa709a0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f121d792a90>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1368947017605768
sparse_theta_sp: -0.638914622569672
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 10000000
ext_decorr_good: 10000000
SUCCESS: less bad topics
num_topics: {'good': 13, 'bad': 2, 'not_good': 7, 'total_bad': 40}
16

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f1238fb2e50>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f1238fb2f10>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f1239e45940>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1368947017605768
sparse_theta_sp: -0.638914622569672
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 10000000
ext_decorr_good: 10000000
num_topics: {'good': 13, 'bad': 2, 'not_good': 7, 'total_bad': 42}
17

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f12399fc430>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f123a8fe6a0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f123ab21670>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1368947017605768
sparse_theta_sp: -0.638914622569672
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 10000000
ext_decorr_good: 10000000
SUCCESS: less bad topics
num_topics: {'good': 13, 'bad': 1, 'not_good': 7, 'total_bad': 43}
18

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f1216790130>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f1218a49d90>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f1218d68d90>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1368947017605768
sparse_theta_sp: -0.638914622569672
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 10000000
ext_decorr_good: 10000000
DOWNFALL: more bad topics...
num_topics: {'good': 13, 'bad': 2, 'not_good': 7, 'total_bad': 45}
19

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f1239cd9f70>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f1239cd9220>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f1239cf1d90>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1368947017605768
sparse_theta_sp: -0.638914622569672
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 10000000
ext_decorr_good: 10000000
SUCCESS: less bad topics
num_topics: {'good': 13, 'bad': 1, 'not_good': 7, 'total_bad': 46}
100000000
0
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
num_topics: {'good': 6, 'bad': 2, 'not_good': 14, 'total_bad': 2}
1

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f1239a42e50>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f123b03a0d0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f1239a42ee0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.0684473508802884
sparse_theta_sp: -0.319457311284836
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000000
ext_decorr_good: 100000000
SUCCESS: more good topics
DOWNFALL: more bad topics...
num_topics: {'good': 8, 'bad': 3, 'not_good': 12, 'total_bad': 5}
2

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f1239a53ca0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f1216790250>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f121d3a6310>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.07985524269366981
sparse_theta_sp: -0.37270019649897534
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000000
ext_decorr_good: 100000000
SUCCESS: less bad topics
num_topics: {'good': 8, 'bad': 2, 'not_good': 12, 'total_bad': 7}
3

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f1238e53fa0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f121d03a490>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f123b07fbe0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.07985524269366981
sparse_theta_sp: -0.37270019649897534
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000000
ext_decorr_good: 100000000
SUCCESS: more good topics
num_topics: {'good': 10, 'bad': 2, 'not_good': 10, 'total_bad': 9}
4

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f1239a42c70>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f121d3a6940>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f1239cd9d60>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.09582629123240377
sparse_theta_sp: -0.4472402357987704
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000000
ext_decorr_good: 100000000
SUCCESS: more good topics
SUCCESS: less bad topics
num_topics: {'good': 11, 'bad': 1, 'not_good': 9, 'total_bad': 10}
5

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f123b03a190>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f123adff0a0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f123a981640>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1064736569248931
sparse_theta_sp: -0.4969335953319671
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000000
ext_decorr_good: 100000000
SUCCESS: more good topics
num_topics: {'good': 12, 'bad': 1, 'not_good': 8, 'total_bad': 11}
6

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f123ab21670>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f123ae1feb0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f1238370e80>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.11978286404050471
sparse_theta_sp: -0.559050294748463
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000000
ext_decorr_good: 100000000
SUCCESS: more good topics
num_topics: {'good': 13, 'bad': 1, 'not_good': 7, 'total_bad': 12}
7

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f123adff0a0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f12383705e0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f123ac362e0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1368947017605768
sparse_theta_sp: -0.638914622569672
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000000
ext_decorr_good: 100000000
SUCCESS: more good topics
SUCCESS: less bad topics
SUCCESS: no bad topics!
num_topics: {'good': 14, 'bad': 0, 'not_good': 6, 'total_bad': 12}
8

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f123ac36130>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f12188445b0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f123ac36640>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.15971048538733962
sparse_theta_sp: -0.7454003929979507
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000000
ext_decorr_good: 100000000
SUCCESS: more good topics
DOWNFALL: more bad topics...
num_topics: {'good': 15, 'bad': 2, 'not_good': 5, 'total_bad': 14}
9

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f1239d78730>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f121d0c3280>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f123ab21670>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.19165258246480754
sparse_theta_sp: -0.8944804715975408
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000000
ext_decorr_good: 100000000
SUCCESS: more good topics
SUCCESS: less bad topics
SUCCESS: no bad topics!
num_topics: {'good': 16, 'bad': 0, 'not_good': 4, 'total_bad': 14}
10

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f1218afa610>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f1238f48040>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f123aa63fd0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.23956572808100943
sparse_theta_sp: -1.118100589496926
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000000
ext_decorr_good: 100000000
SUCCESS: no bad topics!
num_topics: {'good': 16, 'bad': 0, 'not_good': 4, 'total_bad': 14}
11

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f121d042b20>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f121d00d400>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f1239266490>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.23956572808100943
sparse_theta_sp: -1.118100589496926
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000000
ext_decorr_good: 100000000
SUCCESS: more good topics
SUCCESS: no bad topics!
num_topics: {'good': 17, 'bad': 0, 'not_good': 3, 'total_bad': 14}
12

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f1239bf0a00>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f123b0b2e50>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f1238f48040>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.31942097077467924
sparse_theta_sp: -1.4908007859959014
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000000
ext_decorr_good: 100000000
SUCCESS: no bad topics!
num_topics: {'good': 17, 'bad': 0, 'not_good': 3, 'total_bad': 14}
13

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f1239bf07f0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f121d0b6e50>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f12188444f0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.31942097077467924
sparse_theta_sp: -1.4908007859959014
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000000
ext_decorr_good: 100000000
SUCCESS: more good topics
SUCCESS: no bad topics!
num_topics: {'good': 18, 'bad': 0, 'not_good': 2, 'total_bad': 14}
14

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f122bfd83a0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f123aaf22e0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f1238a87e80>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.47913145616201885
sparse_theta_sp: -2.236201178993852
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000000
ext_decorr_good: 100000000
SUCCESS: no bad topics!
num_topics: {'good': 18, 'bad': 0, 'not_good': 2, 'total_bad': 14}
15

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f1239a53850>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f1239e58ca0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f12188446a0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.47913145616201885
sparse_theta_sp: -2.236201178993852
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000000
ext_decorr_good: 100000000
SUCCESS: more good topics
SUCCESS: no bad topics!
num_topics: {'good': 19, 'bad': 0, 'not_good': 1, 'total_bad': 14}
16

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f121880da60>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f123aa63fd0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f1239a42c40>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.9582629123240377
sparse_theta_sp: -4.472402357987704
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000000
ext_decorr_good: 100000000
DOWNFALL: more bad topics...
num_topics: {'good': 19, 'bad': 1, 'not_good': 1, 'total_bad': 15}
17

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f121d0b6e50>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f123aaf22e0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f12188446a0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.9582629123240377
sparse_theta_sp: -4.472402357987704
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000000
ext_decorr_good: 100000000
num_topics: {'good': 19, 'bad': 1, 'not_good': 1, 'total_bad': 16}
18

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f1218afad90>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f121d36b2e0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f122bfd8e80>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.9582629123240377
sparse_theta_sp: -4.472402357987704
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000000
ext_decorr_good: 100000000
num_topics: {'good': 19, 'bad': 1, 'not_good': 1, 'total_bad': 17}
19

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f1239cf1ca0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f12399fc430>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f121d03a460>}
SUCCESS: more good topics
SUCCESS: less bad topics
SUCCESS: no bad topics!
num_topics: {'good': 9, 'bad': 0, 'not_good': 11, 'total_bad': 2}
2

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f1239897e80>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f1238953d90>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f1239cf1ca0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.08711481021127616
sparse_theta_sp: -0.4065820325443367
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 1000000000
ext_decorr_good: 1000000000
SUCCESS: more good topics
SUCCESS: no bad topics!
num_topics: {'good': 12, 'bad': 0, 'not_good': 8, 'total_bad': 2}
3

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f1238948790>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f123a8fe6a0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f121d3f0670>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.11978286404050471
sparse_theta_sp: -0.559050294748463
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 1000000000
ext_decorr_good: 1000000000
SUCCESS: more good topics
SUCCESS: no bad topics!
num_topics: {'good': 15, 'bad': 0, 'not_good': 5, 'total_bad': 2}
4

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f123a99f550>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f1239bc4e50>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f123912e8e0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.19165258246480754
sparse_theta_sp: -0.8944804715975408
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 1000000000
ext_decorr_good: 1000000000
SUCCESS: more good topics
SUCCESS: no bad topics!
num_topics: {'good': 16, 'bad': 0, 'not_good': 4, 'total_bad': 2}
5

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f123b07fc10>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f1238a87e20>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f12383702e0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.23956572808100943
sparse_theta_sp: -1.118100589496926
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 1000000000
ext_decorr_good: 1000000000
SUCCESS: more good topics
SUCCESS: no bad topics!
num_topics: {'good': 18, 'bad': 0, 'not_good': 2, 'total_bad': 2}
6

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f123a8c4160>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f1239bf07f0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f122bfc7940>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.47913145616201885
sparse_theta_sp: -2.236201178993852
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 1000000000
ext_decorr_good: 1000000000
SUCCESS: more good topics
SUCCESS: no bad topics!
num_topics: {'good': 19, 'bad': 0, 'not_good': 1, 'total_bad': 2}
7

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f1238e40580>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f1239897e80>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f123a8da100>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.9582629123240377
sparse_theta_sp: -4.472402357987704
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 1000000000
ext_decorr_good: 1000000000
DOWNFALL: more bad topics...
num_topics: {'good': 19, 'bad': 1, 'not_good': 1, 'total_bad': 3}
8

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f121d042520>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f12188445b0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f1239ba73d0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.9582629123240377
sparse_theta_sp: -4.472402357987704
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 1000000000
ext_decorr_good: 1000000000
num_topics: {'good': 19, 'bad': 1, 'not_good': 1, 'total_bad': 4}
9

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f121d3f0910>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f1239bf07f0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f1238953bb0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.9582629123240377
sparse_theta_sp: -4.472402357987704
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 1000000000
ext_decorr_good: 1000000000
num_topics: {'good': 19, 'bad': 1, 'not_good': 1, 'total_bad': 5}
10

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f123897a400>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f1238a87e20>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f123b07fbe0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.9582629123240377
sparse_theta_sp: -4.472402357987704
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 1000000000
ext_decorr_good: 1000000000
num_topics: {'good': 19, 'bad': 1, 'not_good': 1, 'total_bad': 6}
11

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f1238f18580>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f123a6cb040>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f1238f18610>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.9582629123240377
sparse_theta_sp: -4.472402357987704
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 1000000000
ext_decorr_good: 1000000000
num_topics: {'good': 19, 'bad': 1, 'not_good': 1, 'total_bad': 7}
12

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f123aaf22e0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f1239ba7310>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f121d042a30>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.9582629123240377
sparse_theta_sp: -4.472402357987704
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 1000000000
ext_decorr_good: 1000000000
num_topics: {'good': 19, 'bad': 1, 'not_good': 1, 'total_bad': 8}
13

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f123a8c4190>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f12383703a0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f123a6cb040>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.9582629123240377
sparse_theta_sp: -4.472402357987704
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 1000000000
ext_decorr_good: 1000000000
num_topics: {'good': 19, 'bad': 1, 'not_good': 1, 'total_bad': 9}
14

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f123aab4be0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f122bfc7970>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f121880d7c0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.9582629123240377
sparse_theta_sp: -4.472402357987704
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 1000000000
ext_decorr_good: 1000000000
num_topics: {'good': 19, 'bad': 1, 'not_good': 1, 'total_bad': 10}
15

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f1239139bb0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f12188446a0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f12383703a0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.9582629123240377
sparse_theta_sp: -4.472402357987704
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 1000000000
ext_decorr_good: 1000000000
num_topics: {'good': 19, 'bad': 1, 'not_good': 1, 'total_bad': 11}
16

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f123a8c4820>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f123a8fe6a0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f1239ba73d0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.9582629123240377
sparse_theta_sp: -4.472402357987704
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 1000000000
ext_decorr_good: 1000000000
num_topics: {'good': 19, 'bad': 1, 'not_good': 1, 'total_bad': 12}
17

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f1238f0a0a0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f12383703a0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f1238ad7340>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.9582629123240377
sparse_theta_sp: -4.472402357987704
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 1000000000
ext_decorr_good: 1000000000
num_topics: {'good': 19, 'bad': 1, 'not_good': 1, 'total_bad': 13}
18

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f1239d4b7f0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f1239bf0880>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f121880d7c0>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.9582629123240377
sparse_theta_sp: -4.472402357987704
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 1000000000
ext_decorr_good: 1000000000
num_topics: {'good': 19, 'bad': 1, 'not_good': 1, 'total_bad': 14}
19

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f123aab4d90>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f12188445b0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f123aece940>}
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.9582629123240377
sparse_theta_sp: -4.472402357987704
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 1000000000
ext_decorr_good: 1000000000
num_topics: {'good': 19, 'bad': 1, 'not_good': 1, 'total_bad': 15}

In [87]:
1

1

In [90]:
results.keys()

dict_keys([10000000, 100000000, 1000000000])

In [91]:
for k, r in results.items():
    for s in r:
        s['scores']['coherence_20'] = float(s['scores']['coherence_20'])

In [ ]:
1

In [92]:
for k, r in results.items():
    with open(SAVE_FOLDER + f'/iterative2_{int(k)}.json', 'w') as f:
        f.write(
            json.dumps(r, indent=4)
        )

In [93]:
! ls $SAVE_FOLDER

ablation_study		iterative_100.json	    iterative2_100000.json
decorrelation.json	iterative2_1000000000.json  lda.json
iterative_1000000.json	iterative2_100000000.json   plsa.json
iterative_100000.json	iterative2_10000000.json    sparse.json
iterative_1000.json	iterative2_1000000.json     tless.json

In [ ]:
view_model(prev_model, dataset)

In [48]:
! tail -n 50 $SAVE_FOLDER/iterative2_100000.json

            "17": 2.636592011876535,
            "18": 1.7554318141499257,
            "19": 1.640629444035244
        },
        "num_topics": {
            "good": 13,
            "bad": 4,
            "not_good": 7,
            "total_bad": 54
        }
    },
    {
        "scores": {
            "perplexity": 2399.692138671875,
            "coherence_20": 1.5343349867118177,
            "diversity_euclidean": 0.07488779816367575,
            "diversity_jensenshannon": 0.7096028483722486,
            "diversity_hellinger": 0.832122429571492,
            "diversity_cosine": 0.8473827547639936
        },
        "topic_coherences": {
            "0": 0.9217079965108185,
            "1": 1.3621768174895768,
            "2": 1.6694630947055196,
            "3": 0.8541021951209471,
            "4": 0.9697594159537758,
            "5": 0.6067957005801524,
            "6": 1.8054658007396136,
            "7": 0.9076733045710277,
            "8": 0.9002829919095333,
            "9": 1.6300267904928862,
            "10": 1.840761298075488,
            "11": 1.8250263857445232,
            "12": 1.7073209789137267,
            "13": 1.8580910947101374,
            "14": 1.6809928119557065,
            "15": 2.0985972466959013,
            "16": 2.0158025400053132,
            "17": 2.636592011876535,
            "18": 1.7554318141499257,
            "19": 1.640629444035244
        },
        "num_topics": {
            "good": 13,
            "bad": 1,
            "not_good": 7,
            "total_bad": 55
        }
    }
]

In [49]:
! tail -n 50 $SAVE_FOLDER/iterative2_1000000.json

            "17": 2.636592011876535,
            "18": 1.7554318141499257,
            "19": 1.640629444035244
        },
        "num_topics": {
            "good": 13,
            "bad": 4,
            "not_good": 7,
            "total_bad": 54
        }
    },
    {
        "scores": {
            "perplexity": 2399.75244140625,
            "coherence_20": 1.5422349498469412,
            "diversity_euclidean": 0.07473976332049242,
            "diversity_jensenshannon": 0.7098907759986864,
            "diversity_hellinger": 0.8325292643052555,
            "diversity_cosine": 0.8483379385827017
        },
        "topic_coherences": {
            "0": 1.00113211617019,
            "1": 1.3621768174895768,
            "2": 1.6694630947055196,
            "3": 0.901739498209401,
            "4": 0.9697594159537758,
            "5": 0.6067957005801524,
            "6": 1.8054658007396136,
            "7": 0.907673304571028,
            "8": 0.9312208318641825,
            "9": 1.6300267904928862,
            "10": 1.840761298075488,
            "11": 1.825026385744523,
            "12": 1.7073209789137267,
            "13": 1.8580910947101374,
            "14": 1.6809928119557065,
            "15": 2.0985972466959013,
            "16": 2.0158025400053132,
            "17": 2.636592011876535,
            "18": 1.7554318141499257,
            "19": 1.640629444035244
        },
        "num_topics": {
            "good": 13,
            "bad": 1,
            "not_good": 7,
            "total_bad": 55
        }
    }
]

In [94]:
! ls $SAVE_FOLDER

ablation_study		iterative_100.json	    iterative2_100000.json
decorrelation.json	iterative2_1000000000.json  lda.json
iterative_1000000.json	iterative2_100000000.json   plsa.json
iterative_100000.json	iterative2_10000000.json    sparse.json
iterative_1000.json	iterative2_1000000.json     tless.json

In [98]:
! tail -n 50 $SAVE_FOLDER/iterative2_1000000.json

            "17": 2.636592011876535,
            "18": 1.7554318141499257,
            "19": 1.640629444035244
        },
        "num_topics": {
            "good": 13,
            "bad": 4,
            "not_good": 7,
            "total_bad": 54
        }
    },
    {
        "scores": {
            "perplexity": 2399.75244140625,
            "coherence_20": 1.5422349498469412,
            "diversity_euclidean": 0.07473976332049242,
            "diversity_jensenshannon": 0.7098907759986864,
            "diversity_hellinger": 0.8325292643052555,
            "diversity_cosine": 0.8483379385827017
        },
        "topic_coherences": {
            "0": 1.00113211617019,
            "1": 1.3621768174895768,
            "2": 1.6694630947055196,
            "3": 0.901739498209401,
            "4": 0.9697594159537758,
            "5": 0.6067957005801524,
            "6": 1.8054658007396136,
            "7": 0.907673304571028,
            "8": 0.9312208318641825,
            "9": 1.6300267904928862,
            "10": 1.840761298075488,
            "11": 1.825026385744523,
            "12": 1.7073209789137267,
            "13": 1.8580910947101374,
            "14": 1.6809928119557065,
            "15": 2.0985972466959013,
            "16": 2.0158025400053132,
            "17": 2.636592011876535,
            "18": 1.7554318141499257,
            "19": 1.640629444035244
        },
        "num_topics": {
            "good": 13,
            "bad": 1,
            "not_good": 7,
            "total_bad": 55
        }
    }
]

## Ablation Study

In [28]:
! ls $SAVE_FOLDER

ablation_study		      iterative_100.json	  plsa.json
bertopic		      iterative2_1000000000.json  plsa_with_cohs.json
bertopic.json		      iterative2_100000000.json   sparse.json
decorrelation.json	      iterative2_10000000.json	  sparse_with_cohs.json
decorrelation_with_cohs.json  iterative2_1000000.json	  tless.json
iterative_1000000.json	      iterative2_100000.json	  tless_with_cohs.json
iterative_100000.json	      lda.json
iterative_1000.json	      lda_with_cohs.json

In [104]:
! tail -n 50 $SAVE_FOLDER/iterative_1000.json

            "17": 2.636592011876535,
            "18": 1.7554318141499257,
            "19": 1.640629444035244
        },
        "num_topics": {
            "good": 13,
            "bad": 4,
            "not_good": 7,
            "total_bad": 54
        }
    },
    {
        "scores": {
            "perplexity": 2399.755859375,
            "coherence_20": 1.5422349498469412,
            "diversity_euclidean": 0.07488431260088221,
            "diversity_jensenshannon": 0.7099821904985755,
            "diversity_hellinger": 0.8326169812227255,
            "diversity_cosine": 0.8487093680907188
        },
        "topic_coherences": {
            "0": 1.00113211617019,
            "1": 1.3621768174895768,
            "2": 1.6694630947055196,
            "3": 0.901739498209401,
            "4": 0.9697594159537758,
            "5": 0.6067957005801523,
            "6": 1.8054658007396136,
            "7": 0.9076733045710277,
            "8": 0.9312208318641825,
            "9": 1.6300267904928862,
            "10": 1.840761298075488,
            "11": 1.825026385744523,
            "12": 1.7073209789137267,
            "13": 1.8580910947101374,
            "14": 1.6809928119557065,
            "15": 2.0985972466959013,
            "16": 2.0158025400053132,
            "17": 2.636592011876535,
            "18": 1.7554318141499257,
            "19": 1.640629444035244
        },
        "num_topics": {
            "good": 13,
            "bad": 1,
            "not_good": 7,
            "total_bad": 55
        }
    }
]

In [105]:
! tail -n 50 $SAVE_FOLDER/iterative_100000.json

            "17": 2.636592011876535,
            "18": 1.7554318141499257,
            "19": 1.640629444035244
        },
        "num_topics": {
            "good": 19,
            "bad": 1,
            "not_good": 1,
            "total_bad": 23
        }
    },
    {
        "scores": {
            "perplexity": 2524.498046875,
            "coherence_20": 1.8160830373355887,
            "diversity_euclidean": 0.09386924139489292,
            "diversity_jensenshannon": 0.7519331493667284,
            "diversity_hellinger": 0.8879142519887491,
            "diversity_cosine": 0.91592813474032
        },
        "topic_coherences": {
            "0": 1.7445017980379762,
            "1": 2.057984232106506,
            "2": 1.7450314186955223,
            "3": 0.6671540546965984,
            "4": 2.29197749690007,
            "5": 1.6710892938824142,
            "6": 1.8767654446024988,
            "7": 1.76869936619555,
            "8": 2.215910718477992,
            "9": 1.6300267904928862,
            "10": 1.840761298075488,
            "11": 1.6530146151609852,
            "12": 1.7073209789137267,
            "13": 1.8580910947101374,
            "14": 1.6809928119557067,
            "15": 1.8638835237406963,
            "16": 2.0158025400053132,
            "17": 2.636592011876535,
            "18": 1.7554318141499257,
            "19": 1.640629444035244
        },
        "num_topics": {
            "good": 19,
            "bad": 1,
            "not_good": 1,
            "total_bad": 24
        }
    }
]

In [106]:
! tail -n 50 $SAVE_FOLDER/iterative_1000000.json

            "17": 2.636592011876535,
            "18": 1.7554318141499257,
            "19": 1.6457005218273515
        },
        "num_topics": {
            "good": 19,
            "bad": 0,
            "not_good": 1,
            "total_bad": 15
        }
    },
    {
        "scores": {
            "perplexity": 2509.45068359375,
            "coherence_20": 1.8343696152756745,
            "diversity_euclidean": 0.10217171248725132,
            "diversity_jensenshannon": 0.7695284135036325,
            "diversity_hellinger": 0.9123624284297017,
            "diversity_cosine": 0.9442764712790213
        },
        "topic_coherences": {
            "0": 0.6043036512713817,
            "1": 1.85624161842734,
            "2": 1.8789415533863691,
            "3": 2.0087784467994148,
            "4": 1.837319679382072,
            "5": 1.8946013416131207,
            "6": 1.90155438803718,
            "7": 1.6737924853770243,
            "8": 1.8444252589807613,
            "9": 2.113804106027984,
            "10": 1.840761298075488,
            "11": 1.6905916251442585,
            "12": 1.7073209789137267,
            "13": 1.8580910947101374,
            "14": 2.019125765599579,
            "15": 1.9042121259085285,
            "16": 2.0158025400053132,
            "17": 2.636592011876535,
            "18": 1.7554318141499257,
            "19": 1.6457005218273515
        },
        "num_topics": {
            "good": 19,
            "bad": 1,
            "not_good": 1,
            "total_bad": 16
        }
    }
]

In [ ]:
DECORRELATION_TAUS = [100000, 1000000]  # Dangerous
DECORRELATION_TAUS = [10000000, 100000000, 1000000000]  # Dangerous

In [100]:
! ls $SAVE_FOLDER/ablation_study

iterative_1000_0-0-1.json  iterative2_1000000_0-0-1.json
iterative_1000_0-1-0.json  iterative2_1000000_0-1-0.json
iterative_1000_0-1-1.json  iterative2_1000000_0-1-1.json
iterative_1000_1-0-0.json  iterative2_1000000_1-0-0.json
iterative_1000_1-0-1.json  iterative2_1000000_1-0-1.json
iterative_1000_1-1-0.json  iterative2_1000000_1-1-0.json

In [29]:
# DECORRELATION_TAU = 1000
# DECORRELATION_TAU = 1000000  # new best # TODO: maybe even higher?
DECORRELATION_TAU = 100000

ALL_PARAMS = [
    # (0, 1, 1),
    (1, 0, 1),
    (1, 1, 0),

    (1, 0, 0),
    # (0, 1, 0),
    # (0, 0, 1),
]

In [30]:
results = dict()

DECORRELATOR_REGULARIZER_CLASS = DecorrelatorWithOtherPhiRegularizer

for params in ALL_PARAMS:
    key = params
    results[key] = []

    print(key)

    prev_model = None
    good_topic_names = list()
    bad_topic_names = None
    not_good_topic_names = None
    bad_phi = None
    seed = 0

    while seed < MAX_NUM_TRAINS and len(good_topic_names) < NUM_TOPICS:
        print(seed)

        if seed == 0:
            prev_model = init_model_from_family(
                family=KnownModel.ARTM,
                dataset=dataset,
                main_modality=MAIN_MODALITY,
                num_topics=NUM_TOPICS,
                seed=seed,
                model_params={
                    'decorrelation_tau': 0.01,  # best values
                    'smooth_bcg_tau': 0.05,
                    'sparse_sp_tau': -0.05,
                }
            )

            for reg in prev_model.regularizers.data:
                print(f"{reg}: {prev_model.regularizers[reg].tau}")
    
            result = fit_and_compute_scores(prev_model, dataset)
            results[key].append(result)

            assert len(results[key]) == seed + 1
    
            
            good_topic_indices = [
                t for t, c in result['topic_coherences'].items() if t in TOPIC_INDICES and is_good(c)
            ]
            bad_topic_indices = [
                t for t, c in result['topic_coherences'].items() if t in TOPIC_INDICES and is_bad(c)
            ]
            not_good_topic_indices = [
                t for t in TOPIC_INDICES if t not in good_topic_indices
            ]
            
            phi = prev_model.get_phi()
            good_topic_names = [phi.columns[t] for t in good_topic_indices]
            bad_topic_names = [phi.columns[t] for t in bad_topic_indices]
            not_good_topic_names = [phi.columns[t] for t in not_good_topic_indices]

            assert len(good_topic_names) > 0
            assert len(bad_topic_names) > 0
            assert set(bad_topic_names) <= set(not_good_topic_names)
            assert not any(t in not_good_topic_names for t in good_topic_names)
            assert len(good_topic_names) + len(not_good_topic_names) == NUM_TOPICS

            assert 'num_topics' not in results[key][-1]

            results[key][-1]['num_topics'] = {
                'good': len(good_topic_names),
                'bad': len(bad_topic_names),
                'not_good': len(not_good_topic_names),
                'total_bad': len(bad_topic_names),
            }

            print(f"num_topics: {results[key][-1]['num_topics']}")

            seed += 1
            
            del result, phi
            model = None

        else:
            custom_regularizers = dict()
            
            if params[0]:
                fix_regularizer = FastFixPhiRegularizer(
                    name='fix',
                    parent_model=prev_model._model,
                    topic_names=good_topic_names,
                )
                custom_regularizers[fix_regularizer.name] = fix_regularizer
            else:
                fix_regularizer = None
            
            cur_bad_phi = prev_model._model.get_phi()[bad_topic_names]

            if bad_phi is None:
                bad_phi = cur_bad_phi
            else:
                # bad_phi.rename(
                #     columns={n: f'm1_{n}' for n in bad_topic_names}, inplace=True
                # )
                bad_phi = pd.concat([bad_phi, cur_bad_phi], axis=1)
    
            bad_phi = deepcopy(bad_phi)

            if params[1]:
                decorr_bad_regularizer = DECORRELATOR_REGULARIZER_CLASS(
                    name='ext_decorr_bad', tau=DECORRELATION_TAU,
                    topic_names=not_good_topic_names,
                    other_phi=bad_phi
                )
                custom_regularizers[decorr_bad_regularizer.name] = decorr_bad_regularizer
            else:
                decorr_bad_regularizer = None
            
            good_phi = prev_model._model.get_phi()[good_topic_names]
            good_phi = deepcopy(good_phi)

            if params[2]:
                decorr_good_regularizer = DECORRELATOR_REGULARIZER_CLASS(
                    name='ext_decorr_good', tau=DECORRELATION_TAU,
                    topic_names=not_good_topic_names,
                    other_phi=good_phi
                )
                custom_regularizers[decorr_good_regularizer.name] = decorr_good_regularizer
            else:
                decorr_good_regularizer = None
    
            new_model = init_model_from_family(
                family=KnownModel.ARTM,
                dataset=dataset,
                main_modality=MAIN_MODALITY,
                num_topics=NUM_TOPICS,
                seed=seed,
                specific_topic_names=not_good_topic_names,
                model_params={
                    'decorrelation_tau': 0.01,
                    'smooth_bcg_tau': 0.05,
                    'sparse_sp_tau': -0.05,
                }
            )
    
            new_result = fit_and_compute_scores(new_model, dataset, custom_regularizers=custom_regularizers)
            
            for reg in new_model.regularizers.data:
                print(f"{reg}: {new_model.regularizers[reg].tau}")
    
            for reg_name, reg in custom_regularizers.items():
                print(f"{reg_name}: {reg.tau}")
    
            
            results[key].append(new_result)

            assert len(results[key]) == seed + 1


            
            good_topic_indices = [
                t for t, c in new_result['topic_coherences'].items() if t in TOPIC_INDICES and is_good(c)
            ]
            bad_topic_indices = [
                t for t, c in new_result['topic_coherences'].items() if t in TOPIC_INDICES and is_bad(c)
            ]
            not_good_topic_indices = [
                t for t in TOPIC_INDICES if t not in good_topic_indices
            ]
            
            phi = new_model.get_phi()
            new_good_topic_names = [phi.columns[t] for t in good_topic_indices]
            new_bad_topic_names = [phi.columns[t] for t in bad_topic_indices]
            new_not_good_topic_names = [phi.columns[t] for t in not_good_topic_indices]

            # assert len(new_good_topic_names) > 0
            if len(new_good_topic_names) == 0:
                print('DOWNFALL: no good topics...')
            # assert len(new_bad_topic_names) > 0
            assert set(new_bad_topic_names) <= set(new_not_good_topic_names)
            assert not any(t in new_not_good_topic_names for t in new_good_topic_names)
            assert len(new_good_topic_names) + len(new_not_good_topic_names) == NUM_TOPICS

            # assert set(good_topic_names) <= set(new_good_topic_names)
            if not (set(good_topic_names) <= set(new_good_topic_names)):
                print('DOWNFALL: some good topics lost...')
            # assert len(new_bad_topic_names) <= len(bad_topic_names)

            if len(new_good_topic_names) > len(good_topic_names):
                print('SUCCESS: more good topics')
            if len(new_bad_topic_names) < len(bad_topic_names):
                print('SUCCESS: less bad topics')
            if len(new_bad_topic_names) > len(bad_topic_names):
                print('DOWNFALL: more bad topics...')
            if len(new_bad_topic_names) == 0:
                print('SUCCESS: no bad topics!')
    
            good_topic_names = new_good_topic_names
            bad_topic_names = new_bad_topic_names
            not_good_topic_names = new_not_good_topic_names

            
            assert 'num_topics' not in results[key][-1]

            results[key][-1]['num_topics'] = {
                'good': len(good_topic_names),
                'bad': len(bad_topic_names),
                'not_good': len(not_good_topic_names),
                'total_bad': bad_phi.shape[1] + len(bad_topic_names),
            }

            prev_model = new_model

            print(f"num_topics: {results[key][-1]['num_topics']}")

            seed += 1

(1, 0, 1)
0
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
Topic: 0. Top: [32833, 40029, 33826, 30791, 37692, 28368, 19656, 28999, 27300, 35416, 28775, 25945, 25220, 41831, 26306, 29939, 33036, 37130, 38446, 27264]
Topic: 1. Top: [36195, 42454, 30130, 34207, 27360, 30827, 32833, 24160, 32028, 31683, 47035, 48735, 40820, 27934, 33726, 29464, 28122, 36226, 29858, 38105]
Topic: 2. Top: [43613, 30791, 32833, 32665, 27086, 44211, 33123, 33484, 31997, 21123, 35416, 35657, 32135, 25289, 29331, 20673, 34170, 23885, 39872, 38446]
Topic: 3. Top: [30339, 28016, 47238, 29237, 33036, 30252, 29096, 27030, 47035, 30887, 34317, 32254, 29684, 31298, 31397, 17231, 30795, 37492, 37631, 48735]
Topic: 4. Top: [28172, 35842, 28465, 22422, 28629, 27624, 21650, 49838, 36585, 29272, 30656, 40295, 24278, 40736, 31622, 17856, 27066, 29834, 34095, 52105]
Topic: 5. Top: [29385, 32833, 32942, 28820, 36874, 29939, 50360, 46187, 31059, 24494, 44833, 37553, 28019, 35189, 27643, 25902, 28992, 39575, 35113, 23798]
Topic: 6. Top: [29453, 36383, 29116, 26627, 31186, 29237, 29282, 32833, 40999, 51040, 32510, 35708, 34014, 51902, 32678, 51496, 35189, 29096, 28406, 36928]
Topic: 7. Top: [28884, 35023, 33036, 20164, 29939, 27187, 27587, 51610, 30152, 24317, 29085, 28701, 33006, 37168, 36515, 27970, 38087, 33124, 21347, 32510]
Topic: 8. Top: [33123, 33125, 47238, 29282, 28701, 30339, 33036, 26745, 32510, 28695, 34317, 33176, 29237, 33124, 34871, 29902, 31298, 52105, 30160, 29728]
Topic: 9. Top: [32833, 34364, 33123, 33036, 42030, 25342, 50442, 25025, 44121, 31777, 35416, 18601, 40029, 46714, 33176, 46583, 19656, 27624, 31683, 38753]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [20528, 22254, 28068, 33484, 29939, 34170, 32677, 50360, 29328, 29998, 27185, 37083, 27787, 25911, 28992, 49264, 42166, 28193, 39945, 32833]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [28651, 30339, 34089, 37833, 33036, 39719, 29237, 25706, 27532, 30596, 30066, 29282, 43571, 32510, 24315, 17946, 34317, 26129, 30252, 29096]
Topic: 15. Top: [35331, 27540, 31186, 32665, 52105, 30331, 39921, 42456, 27624, 22209, 20197, 27307, 43613, 50360, 32929, 37263, 32028, 19656, 25859, 43025]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [49838, 37130, 28100, 34287, 29939, 32833, 26190, 28095, 24123, 30627, 30597, 51400, 34531, 28019, 32942, 30119, 40409, 32717, 31192, 36268]
Topic: 0. Top: [32833, 40029, 33826, 30791, 37692, 28368, 19656, 28999, 27300, 35416, 28775, 25945, 25220, 41831, 26306, 29939, 33036, 37130, 38446, 27264]
Topic: 1. Top: [36195, 42454, 30130, 34207, 27360, 30827, 32833, 24160, 32028, 31683, 47035, 48735, 40820, 27934, 33726, 29464, 28122, 36226, 29858, 38105]
Topic: 2. Top: [43613, 30791, 32833, 32665, 27086, 44211, 33123, 33484, 31997, 21123, 35416, 35657, 32135, 25289, 29331, 20673, 34170, 23885, 39872, 38446]
Topic: 3. Top: [30339, 28016, 47238, 29237, 33036, 30252, 29096, 27030, 47035, 30887, 34317, 32254, 29684, 31298, 31397, 17231, 30795, 37492, 37631, 48735]
Topic: 4. Top: [28172, 35842, 28465, 22422, 28629, 27624, 21650, 49838, 36585, 29272, 30656, 40295, 24278, 40736, 31622, 17856, 27066, 29834, 34095, 52105]
Topic: 5. Top: [29385, 32833, 32942, 28820, 36874, 29939, 50360, 46187, 31059, 24494, 44833, 37553, 28019, 35189, 27643, 25902, 28992, 39575, 35113, 23798]
Topic: 6. Top: [29453, 36383, 29116, 26627, 31186, 29237, 29282, 32833, 40999, 51040, 32510, 35708, 34014, 51902, 32678, 51496, 35189, 29096, 28406, 36928]
Topic: 7. Top: [28884, 35023, 33036, 20164, 29939, 27187, 27587, 51610, 30152, 24317, 29085, 28701, 33006, 37168, 36515, 27970, 38087, 33124, 21347, 32510]
Topic: 8. Top: [33123, 33125, 47238, 29282, 28701, 30339, 33036, 26745, 32510, 28695, 34317, 33176, 29237, 33124, 34871, 29902, 31298, 52105, 30160, 29728]
Topic: 9. Top: [32833, 34364, 33123, 33036, 42030, 25342, 50442, 25025, 44121, 31777, 35416, 18601, 40029, 46714, 33176, 46583, 19656, 27624, 31683, 38753]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [20528, 22254, 28068, 33484, 29939, 34170, 32677, 50360, 29328, 29998, 27185, 37083, 27787, 25911, 28992, 49264, 42166, 28193, 39945, 32833]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [28651, 30339, 34089, 37833, 33036, 39719, 29237, 25706, 27532, 30596, 30066, 29282, 43571, 32510, 24315, 17946, 34317, 26129, 30252, 29096]
Topic: 15. Top: [35331, 27540, 31186, 32665, 52105, 30331, 39921, 42456, 27624, 22209, 20197, 27307, 43613, 50360, 32929, 37263, 32028, 19656, 25859, 43025]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [49838, 37130, 28100, 34287, 29939, 32833, 26190, 28095, 24123, 30627, 30597, 51400, 34531, 28019, 32942, 30119, 40409, 32717, 31192, 36268]
num_topics: {'good': 6, 'bad': 2, 'not_good': 14, 'total_bad': 2}
1

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8f57b190>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f7b8f57b1c0>}
Topic: 0. Top: [29282, 33125, 33036, 32510, 30339, 28701, 28695, 34317, 34871, 20164, 26745, 17194, 33123, 30160, 33124, 29237, 47238, 33176, 33731, 35023]
Topic: 1. Top: [43613, 37130, 33484, 31997, 30627, 22254, 34170, 20673, 27185, 20528, 28992, 28068, 32665, 32677, 29939, 25289, 33826, 28100, 32833, 42166]
Topic: 2. Top: [39575, 28884, 50360, 38245, 34409, 20370, 31059, 27187, 31759, 25911, 24203, 29068, 43613, 30152, 35331, 32931, 24494, 29085, 31147, 37868]
Topic: 3. Top: [49838, 32833, 33123, 34287, 40029, 33036, 17856, 28172, 19656, 42030, 26190, 29939, 34364, 28100, 37130, 45727, 22422, 28095, 33176, 30444]
Topic: 4. Top: [52105, 19656, 30339, 42456, 21874, 33047, 32665, 27624, 33176, 47238, 28465, 29237, 29096, 27540, 29592, 33123, 32929, 35331, 36376, 31186]
Topic: 5. Top: [36383, 29453, 31186, 26627, 51040, 29116, 32833, 40999, 51902, 29237, 34014, 33799, 36928, 35708, 51496, 35750, 35189, 21129, 30130, 22209]
Topic: 6. Top: [32833, 30791, 21123, 35657, 27086, 35538, 43613, 32135, 32665, 33123, 35416, 26809, 28193, 36303, 22254, 32760, 28068, 29592, 19656, 34729]
Topic: 7. Top: [29237, 43571, 29096, 33125, 33036, 29902, 30596, 28701, 32510, 40395, 47035, 30339, 32711, 46434, 27970, 29597, 33124, 26745, 35057, 30876]
Topic: 8. Top: [32833, 30791, 38446, 40029, 25945, 35416, 44211, 20528, 46714, 32665, 29939, 33484, 37692, 19656, 26306, 33036, 45727, 25220, 39872, 29033]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 27643, 33036, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [46583, 21394, 52456, 33761, 24452, 29205, 29393, 43332, 40157, 27624, 23739, 24625, 45519, 35494, 48872, 41048, 17398, 24932, 29520, 23664]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 27532, 24315, 26129, 17946, 30374, 30252, 30066, 31484, 34317, 29453, 25420, 32510, 21347]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [47238, 30339, 33123, 33036, 31298, 30252, 34317, 33176, 29237, 29684, 33124, 44121, 26745, 31397, 48735, 29096, 17231, 33125, 28695, 29282]
Topic: 0. Top: [29282, 33125, 33036, 32510, 30339, 28701, 28695, 34317, 34871, 20164, 26745, 17194, 33123, 30160, 33124, 29237, 47238, 33176, 33731, 35023]
Topic: 1. Top: [43613, 37130, 33484, 31997, 30627, 22254, 34170, 20673, 27185, 20528, 28992, 28068, 32665, 32677, 29939, 25289, 33826, 28100, 32833, 42166]
Topic: 2. Top: [39575, 28884, 50360, 38245, 34409, 20370, 31059, 27187, 31759, 25911, 24203, 29068, 43613, 30152, 35331, 32931, 24494, 29085, 31147, 37868]
Topic: 3. Top: [49838, 32833, 33123, 34287, 40029, 33036, 17856, 28172, 19656, 42030, 26190, 29939, 34364, 28100, 37130, 45727, 22422, 28095, 33176, 30444]
Topic: 4. Top: [52105, 19656, 30339, 42456, 21874, 33047, 32665, 27624, 33176, 47238, 28465, 29237, 29096, 27540, 29592, 33123, 32929, 35331, 36376, 31186]
Topic: 5. Top: [36383, 29453, 31186, 26627, 51040, 29116, 32833, 40999, 51902, 29237, 34014, 33799, 36928, 35708, 51496, 35750, 35189, 21129, 30130, 22209]
Topic: 6. Top: [32833, 30791, 21123, 35657, 27086, 35538, 43613, 32135, 32665, 33123, 35416, 26809, 28193, 36303, 22254, 32760, 28068, 29592, 19656, 34729]
Topic: 7. Top: [29237, 43571, 29096, 33125, 33036, 29902, 30596, 28701, 32510, 40395, 47035, 30339, 32711, 46434, 27970, 29597, 33124, 26745, 35057, 30876]
Topic: 8. Top: [32833, 30791, 38446, 40029, 25945, 35416, 44211, 20528, 46714, 32665, 29939, 33484, 37692, 19656, 26306, 33036, 45727, 25220, 39872, 29033]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 27643, 33036, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [46583, 21394, 52456, 33761, 24452, 29205, 29393, 43332, 40157, 27624, 23739, 24625, 45519, 35494, 48872, 41048, 17398, 24932, 29520, 23664]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 27532, 24315, 26129, 17946, 30374, 30252, 30066, 31484, 34317, 29453, 25420, 32510, 21347]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [47238, 30339, 33123, 33036, 31298, 30252, 34317, 33176, 29237, 29684, 33124, 44121, 26745, 31397, 48735, 29096, 17231, 33125, 28695, 29282]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.0684473508802884
sparse_theta_sp: -0.319457311284836
decorrelation: 0.01
fix: 1000000000
ext_decorr_good: 100000
SUCCESS: more good topics
DOWNFALL: more bad topics...
num_topics: {'good': 8, 'bad': 3, 'not_good': 12, 'total_bad': 5}
2

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8f7747f0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f7ad5138070>}
Topic: 0. Top: [49838, 28100, 26190, 28095, 32833, 29939, 32717, 40409, 37130, 51400, 42030, 28775, 25538, 19656, 40029, 29486, 36268, 28540, 33036, 31374]
Topic: 1. Top: [28172, 34364, 32833, 33123, 28629, 33036, 28701, 40295, 42030, 27624, 17856, 49838, 34095, 34130, 25025, 24278, 25342, 30152, 47238, 40736]
Topic: 2. Top: [36383, 51040, 40999, 29282, 27030, 32833, 51902, 29453, 28016, 51496, 22209, 34014, 49904, 30130, 29888, 26362, 33036, 31622, 30656, 28701]
Topic: 3. Top: [37833, 28651, 33036, 30596, 30339, 39719, 29453, 17946, 19828, 29259, 31484, 30066, 21347, 17905, 45841, 25706, 33480, 27985, 38087, 27970]
Topic: 4. Top: [30791, 32833, 44211, 21123, 35657, 32135, 32665, 27086, 43613, 35416, 38446, 35538, 33123, 40029, 25945, 39872, 19656, 26239, 34729, 25943]
Topic: 5. Top: [28651, 34089, 27532, 30339, 33036, 26129, 30252, 25706, 37833, 29096, 39719, 34507, 32510, 52298, 34317, 29282, 30876, 43184, 19933, 43571]
Topic: 6. Top: [43613, 33484, 31997, 22254, 39575, 25289, 50360, 29939, 26648, 20528, 32833, 20370, 38245, 32665, 28068, 34170, 27185, 49264, 20673, 24203]
Topic: 7. Top: [34287, 37692, 32833, 28019, 30627, 17856, 28999, 25466, 28368, 26306, 24123, 32942, 35416, 31964, 39661, 31192, 27264, 29939, 46951, 20528]
Topic: 8. Top: [29282, 29237, 33125, 32510, 28701, 20164, 30339, 34871, 28695, 33036, 29902, 33124, 28995, 29784, 35023, 26745, 27136, 30160, 33731, 34317]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 27643, 33036, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [31186, 29116, 27540, 26627, 35750, 29453, 43613, 39921, 20197, 31620, 35331, 35708, 35189, 27624, 36985, 26993, 52105, 27307, 42456, 43025]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [47238, 30339, 33123, 33036, 30252, 34317, 31298, 33176, 29237, 29684, 26745, 33125, 33124, 44121, 29096, 31397, 48735, 17231, 29282, 28695]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [37130, 33826, 35842, 27624, 32833, 30597, 30791, 40029, 27066, 34531, 22422, 21650, 33123, 19656, 50488, 30119, 27300, 37974, 39575, 38446]
Topic: 0. Top: [49838, 28100, 26190, 28095, 32833, 29939, 32717, 40409, 37130, 51400, 42030, 28775, 25538, 19656, 40029, 29486, 36268, 28540, 33036, 31374]
Topic: 1. Top: [28172, 34364, 32833, 33123, 28629, 33036, 28701, 40295, 42030, 27624, 17856, 49838, 34095, 34130, 25025, 24278, 25342, 30152, 47238, 40736]
Topic: 2. Top: [36383, 51040, 40999, 29282, 27030, 32833, 51902, 29453, 28016, 51496, 22209, 34014, 49904, 30130, 29888, 26362, 33036, 31622, 30656, 28701]
Topic: 3. Top: [37833, 28651, 33036, 30596, 30339, 39719, 29453, 17946, 19828, 29259, 31484, 30066, 21347, 17905, 45841, 25706, 33480, 27985, 38087, 27970]
Topic: 4. Top: [30791, 32833, 44211, 21123, 35657, 32135, 32665, 27086, 43613, 35416, 38446, 35538, 33123, 40029, 25945, 39872, 19656, 26239, 34729, 25943]
Topic: 5. Top: [28651, 34089, 27532, 30339, 33036, 26129, 30252, 25706, 37833, 29096, 39719, 34507, 32510, 52298, 34317, 29282, 30876, 43184, 19933, 43571]
Topic: 6. Top: [43613, 33484, 31997, 22254, 39575, 25289, 50360, 29939, 26648, 20528, 32833, 20370, 38245, 32665, 28068, 34170, 27185, 49264, 20673, 24203]
Topic: 7. Top: [34287, 37692, 32833, 28019, 30627, 17856, 28999, 25466, 28368, 26306, 24123, 32942, 35416, 31964, 39661, 31192, 27264, 29939, 46951, 20528]
Topic: 8. Top: [29282, 29237, 33125, 32510, 28701, 20164, 30339, 34871, 28695, 33036, 29902, 33124, 28995, 29784, 35023, 26745, 27136, 30160, 33731, 34317]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 27643, 33036, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [31186, 29116, 27540, 26627, 35750, 29453, 43613, 39921, 20197, 31620, 35331, 35708, 35189, 27624, 36985, 26993, 52105, 27307, 42456, 43025]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [47238, 30339, 33123, 33036, 30252, 34317, 31298, 33176, 29237, 29684, 26745, 33125, 33124, 44121, 29096, 31397, 48735, 17231, 29282, 28695]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [37130, 33826, 35842, 27624, 32833, 30597, 30791, 40029, 27066, 34531, 22422, 21650, 33123, 19656, 50488, 30119, 27300, 37974, 39575, 38446]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.07985524269366981
sparse_theta_sp: -0.37270019649897534
decorrelation: 0.01
fix: 1000000000
ext_decorr_good: 100000
num_topics: {'good': 8, 'bad': 3, 'not_good': 12, 'total_bad': 8}
3

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8edaa7f0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f7b8f749d00>}
Topic: 0. Top: [29282, 29237, 32510, 33125, 30339, 33036, 29116, 30160, 26745, 28701, 20164, 33123, 28695, 32678, 17194, 32833, 28995, 34317, 39719, 31298]
Topic: 1. Top: [28172, 27624, 28629, 40295, 35842, 42030, 34095, 32833, 25025, 21394, 34364, 49838, 40736, 25342, 26483, 29272, 31133, 30429, 46583, 21650]
Topic: 2. Top: [42456, 30339, 29237, 35331, 30444, 36226, 28252, 40820, 19933, 27934, 22772, 47035, 31228, 27307, 33036, 26095, 52105, 45080, 26584, 29644]
Topic: 3. Top: [28651, 30339, 34089, 37833, 33036, 39719, 29237, 29282, 25706, 27532, 30066, 34317, 32510, 43571, 33125, 24315, 30252, 26129, 29096, 30374]
Topic: 4. Top: [30791, 32833, 21123, 44211, 35657, 32135, 40029, 35538, 25945, 35416, 33123, 27086, 32665, 25943, 26567, 36303, 19656, 34729, 27587, 29592]
Topic: 5. Top: [33123, 47238, 52105, 33176, 28701, 33125, 28695, 33036, 31298, 32510, 19656, 26745, 44121, 30339, 46780, 34871, 34317, 33124, 28995, 29902]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 40999, 29237, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [49838, 37130, 32833, 28100, 34287, 29939, 33826, 40029, 37692, 19656, 30597, 28019, 28999, 26190, 34531, 28095, 35416, 30627, 33036, 31192]
Topic: 8. Top: [30339, 47238, 30252, 34317, 33036, 29684, 29096, 29237, 30887, 31298, 47035, 17231, 28016, 33123, 30795, 31397, 29902, 37492, 37631, 33124]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 27643, 33036, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [33036, 21347, 35023, 20164, 31484, 28701, 19828, 32833, 32939, 29559, 33006, 27315, 48622, 27970, 27587, 28884, 26027, 40395, 29939, 32436]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [33484, 32665, 32833, 20528, 27185, 30791, 42166, 20673, 43613, 28992, 28068, 29939, 38446, 34170, 26239, 30627, 22254, 39872, 26306, 39945]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 23885, 34409, 29331, 31759, 28068]
Topic: 0. Top: [29282, 29237, 32510, 33125, 30339, 33036, 29116, 30160, 26745, 28701, 20164, 33123, 28695, 32678, 17194, 32833, 28995, 34317, 39719, 31298]
Topic: 1. Top: [28172, 27624, 28629, 40295, 35842, 42030, 34095, 32833, 25025, 21394, 34364, 49838, 40736, 25342, 26483, 29272, 31133, 30429, 46583, 21650]
Topic: 2. Top: [42456, 30339, 29237, 35331, 30444, 36226, 28252, 40820, 19933, 27934, 22772, 47035, 31228, 27307, 33036, 26095, 52105, 45080, 26584, 29644]
Topic: 3. Top: [28651, 30339, 34089, 37833, 33036, 39719, 29237, 29282, 25706, 27532, 30066, 34317, 32510, 43571, 33125, 24315, 30252, 26129, 29096, 30374]
Topic: 4. Top: [30791, 32833, 21123, 44211, 35657, 32135, 40029, 35538, 25945, 35416, 33123, 27086, 32665, 25943, 26567, 36303, 19656, 34729, 27587, 29592]
Topic: 5. Top: [33123, 47238, 52105, 33176, 28701, 33125, 28695, 33036, 31298, 32510, 19656, 26745, 44121, 30339, 46780, 34871, 34317, 33124, 28995, 29902]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 40999, 29237, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [49838, 37130, 32833, 28100, 34287, 29939, 33826, 40029, 37692, 19656, 30597, 28019, 28999, 26190, 34531, 28095, 35416, 30627, 33036, 31192]
Topic: 8. Top: [30339, 47238, 30252, 34317, 33036, 29684, 29096, 29237, 30887, 31298, 47035, 17231, 28016, 33123, 30795, 31397, 29902, 37492, 37631, 33124]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 27643, 33036, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [33036, 21347, 35023, 20164, 31484, 28701, 19828, 32833, 32939, 29559, 33006, 27315, 48622, 27970, 27587, 28884, 26027, 40395, 29939, 32436]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [33484, 32665, 32833, 20528, 27185, 30791, 42166, 20673, 43613, 28992, 28068, 29939, 38446, 34170, 26239, 30627, 22254, 39872, 26306, 39945]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 23885, 34409, 29331, 31759, 28068]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.07985524269366981
sparse_theta_sp: -0.37270019649897534
decorrelation: 0.01
fix: 1000000000
ext_decorr_good: 100000
SUCCESS: more good topics
SUCCESS: less bad topics
num_topics: {'good': 10, 'bad': 2, 'not_good': 10, 'total_bad': 10}
4

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8eaea100>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f7b89677790>}
Topic: 0. Top: [29237, 30339, 33125, 33036, 39719, 28651, 29282, 32510, 34317, 43571, 30596, 29096, 37833, 34871, 45841, 27970, 33124, 32939, 35023, 30160]
Topic: 1. Top: [30339, 47238, 33036, 30252, 33123, 31298, 29237, 34317, 29684, 33176, 28016, 29096, 48735, 17231, 44121, 29902, 33124, 31397, 29282, 33125]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 28095, 37130, 29939, 28019, 40409, 51400, 32833, 30627, 30119, 36268, 31964, 23120, 28999, 25538, 17856]
Topic: 3. Top: [30791, 32833, 33484, 32665, 43613, 27185, 44211, 38446, 20528, 35416, 25945, 20673, 34170, 40029, 28992, 29939, 42166, 26466, 39872, 35657]
Topic: 4. Top: [28172, 37130, 32833, 35842, 33826, 22422, 27624, 40029, 30597, 21650, 33123, 19656, 37692, 33036, 34531, 27066, 27300, 28701, 45727, 50488]
Topic: 5. Top: [32833, 21123, 33036, 35538, 19656, 41831, 33123, 25220, 35657, 31374, 32135, 25025, 37974, 18601, 46714, 30791, 41106, 47079, 28775, 40029]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 40999, 29237, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [29282, 33123, 28701, 26745, 33036, 32510, 33125, 28695, 28995, 34871, 33176, 33124, 30160, 47238, 29728, 20164, 17194, 34317, 32833, 29237]
Topic: 8. Top: [28651, 34089, 27532, 37833, 25706, 33036, 30339, 26129, 30066, 24315, 34507, 29453, 17905, 52298, 29331, 43184, 29282, 30252, 27315, 33176]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 27643, 33036, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [27587, 22099, 33707, 29592, 36303, 19828, 25943, 35331, 29559, 40521, 22107, 35657, 31228, 33036, 32135, 29834, 32879, 48622, 24452, 44826]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [19656, 29237, 21874, 47238, 52105, 33047, 33125, 32510, 29282, 26192, 26627, 32665, 29902, 30339, 28465, 42456, 33123, 32677, 29096, 36585]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 23885, 34409, 29331, 31759, 28068]
Topic: 0. Top: [29237, 30339, 33125, 33036, 39719, 28651, 29282, 32510, 34317, 43571, 30596, 29096, 37833, 34871, 45841, 27970, 33124, 32939, 35023, 30160]
Topic: 1. Top: [30339, 47238, 33036, 30252, 33123, 31298, 29237, 34317, 29684, 33176, 28016, 29096, 48735, 17231, 44121, 29902, 33124, 31397, 29282, 33125]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 28095, 37130, 29939, 28019, 40409, 51400, 32833, 30627, 30119, 36268, 31964, 23120, 28999, 25538, 17856]
Topic: 3. Top: [30791, 32833, 33484, 32665, 43613, 27185, 44211, 38446, 20528, 35416, 25945, 20673, 34170, 40029, 28992, 29939, 42166, 26466, 39872, 35657]
Topic: 4. Top: [28172, 37130, 32833, 35842, 33826, 22422, 27624, 40029, 30597, 21650, 33123, 19656, 37692, 33036, 34531, 27066, 27300, 28701, 45727, 50488]
Topic: 5. Top: [32833, 21123, 33036, 35538, 19656, 41831, 33123, 25220, 35657, 31374, 32135, 25025, 37974, 18601, 46714, 30791, 41106, 47079, 28775, 40029]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 40999, 29237, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [29282, 33123, 28701, 26745, 33036, 32510, 33125, 28695, 28995, 34871, 33176, 33124, 30160, 47238, 29728, 20164, 17194, 34317, 32833, 29237]
Topic: 8. Top: [28651, 34089, 27532, 37833, 25706, 33036, 30339, 26129, 30066, 24315, 34507, 29453, 17905, 52298, 29331, 43184, 29282, 30252, 27315, 33176]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 27643, 33036, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [27587, 22099, 33707, 29592, 36303, 19828, 25943, 35331, 29559, 40521, 22107, 35657, 31228, 33036, 32135, 29834, 32879, 48622, 24452, 44826]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [19656, 29237, 21874, 47238, 52105, 33047, 33125, 32510, 29282, 26192, 26627, 32665, 29902, 30339, 28465, 42456, 33123, 32677, 29096, 36585]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 23885, 34409, 29331, 31759, 28068]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.09582629123240377
sparse_theta_sp: -0.4472402357987704
decorrelation: 0.01
fix: 1000000000
ext_decorr_good: 100000
DOWNFALL: more bad topics...
num_topics: {'good': 10, 'bad': 4, 'not_good': 10, 'total_bad': 14}
5

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b89766940>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f7b8e8bbaf0>}
Topic: 0. Top: [28172, 32833, 33123, 33036, 42030, 34364, 35842, 49838, 22422, 28701, 27624, 28629, 40295, 21650, 17856, 21580, 26745, 25342, 30444, 25025]
Topic: 1. Top: [49838, 32833, 37130, 40029, 28100, 29939, 30791, 34287, 19656, 35416, 33826, 33123, 37692, 30627, 30597, 33036, 28999, 21123, 28019, 26190]
Topic: 2. Top: [29282, 33125, 29237, 33123, 32510, 33036, 28701, 26745, 30339, 28695, 34871, 33124, 47238, 34317, 30160, 33176, 28995, 20164, 29902, 17194]
Topic: 3. Top: [30791, 32833, 33484, 38446, 44211, 32665, 43613, 25945, 35657, 27587, 34170, 26239, 20673, 33123, 26809, 46714, 35538, 28019, 32135, 32343]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 21347, 29096, 29237, 29453]
Topic: 5. Top: [29259, 19828, 27532, 40820, 28701, 30655, 17905, 29559, 22099, 32678, 25163, 42892, 48622, 45841, 17398, 34966, 32510, 26095, 27754, 28872]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 40999, 29237, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [19656, 47238, 52105, 21874, 33047, 33123, 28465, 42456, 32510, 32665, 31298, 30339, 26192, 29902, 36585, 33176, 29331, 27624, 30656, 32929]
Topic: 8. Top: [46583, 20164, 30339, 29275, 21394, 43931, 31931, 29205, 29085, 31298, 33707, 28884, 24684, 33096, 33761, 19900, 27624, 28830, 33036, 30870]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 27643, 33036, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [30339, 47238, 33036, 30252, 29237, 34317, 28016, 31298, 29096, 29684, 30887, 47035, 33176, 33123, 27030, 48735, 31397, 33124, 17231, 30795]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [20528, 27185, 28068, 28992, 42166, 33484, 32833, 32665, 39945, 27787, 25911, 26306, 35842, 29939, 29834, 52456, 22980, 39872, 22254, 30627]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 23885, 34409, 29331, 31759, 28068]
Topic: 0. Top: [28172, 32833, 33123, 33036, 42030, 34364, 35842, 49838, 22422, 28701, 27624, 28629, 40295, 21650, 17856, 21580, 26745, 25342, 30444, 25025]
Topic: 1. Top: [49838, 32833, 37130, 40029, 28100, 29939, 30791, 34287, 19656, 35416, 33826, 33123, 37692, 30627, 30597, 33036, 28999, 21123, 28019, 26190]
Topic: 2. Top: [29282, 33125, 29237, 33123, 32510, 33036, 28701, 26745, 30339, 28695, 34871, 33124, 47238, 34317, 30160, 33176, 28995, 20164, 29902, 17194]
Topic: 3. Top: [30791, 32833, 33484, 38446, 44211, 32665, 43613, 25945, 35657, 27587, 34170, 26239, 20673, 33123, 26809, 46714, 35538, 28019, 32135, 32343]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 21347, 29096, 29237, 29453]
Topic: 5. Top: [29259, 19828, 27532, 40820, 28701, 30655, 17905, 29559, 22099, 32678, 25163, 42892, 48622, 45841, 17398, 34966, 32510, 26095, 27754, 28872]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 40999, 29237, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [19656, 47238, 52105, 21874, 33047, 33123, 28465, 42456, 32510, 32665, 31298, 30339, 26192, 29902, 36585, 33176, 29331, 27624, 30656, 32929]
Topic: 8. Top: [46583, 20164, 30339, 29275, 21394, 43931, 31931, 29205, 29085, 31298, 33707, 28884, 24684, 33096, 33761, 19900, 27624, 28830, 33036, 30870]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 27643, 33036, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [30339, 47238, 33036, 30252, 29237, 34317, 28016, 31298, 29096, 29684, 30887, 47035, 33176, 33123, 27030, 48735, 31397, 33124, 17231, 30795]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [20528, 27185, 28068, 28992, 42166, 33484, 32833, 32665, 39945, 27787, 25911, 26306, 35842, 29939, 29834, 52456, 22980, 39872, 22254, 30627]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 23885, 34409, 29331, 31759, 28068]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.09582629123240377
sparse_theta_sp: -0.4472402357987704
decorrelation: 0.01
fix: 1000000000
ext_decorr_good: 100000
SUCCESS: more good topics
SUCCESS: less bad topics
num_topics: {'good': 11, 'bad': 2, 'not_good': 9, 'total_bad': 16}
6

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8e828340>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f7b89766d00>}
Topic: 0. Top: [32833, 37130, 27185, 20528, 30791, 29939, 30627, 37692, 33826, 32665, 30597, 34531, 35416, 38446, 32677, 28999, 19656, 28068, 42166, 34170]
Topic: 1. Top: [29282, 33123, 29237, 33125, 28701, 32510, 47238, 26745, 30339, 28695, 34871, 33036, 28995, 33176, 34317, 52105, 29902, 30160, 17194, 33124]
Topic: 2. Top: [33484, 20673, 38446, 26239, 28992, 28019, 31502, 32665, 43613, 39945, 40820, 44211, 36226, 21001, 32833, 27985, 25391, 20528, 37027, 34170]
Topic: 3. Top: [33036, 35023, 19828, 33125, 29282, 32510, 29559, 29259, 29237, 30152, 45841, 20164, 30339, 48622, 29939, 44259, 31298, 32939, 28884, 32678]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 21347, 29096, 29237, 29453]
Topic: 5. Top: [49838, 28172, 34287, 28100, 32833, 26190, 29939, 40029, 42030, 28095, 17856, 19656, 31374, 32717, 30119, 24123, 40409, 33036, 33123, 52215]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 40999, 29237, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [30791, 32833, 21123, 35657, 32135, 40029, 32665, 25943, 44211, 35538, 35416, 33123, 39872, 26567, 43613, 19656, 36303, 27086, 33707, 28393]
Topic: 8. Top: [30339, 47238, 30252, 34317, 29096, 29237, 30887, 33036, 29684, 32254, 31298, 33123, 29902, 47035, 30795, 45934, 17231, 29592, 37492, 37712]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 27643, 33036, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [34364, 24278, 40295, 38753, 35185, 34130, 32833, 50442, 28585, 30429, 36922, 34095, 25342, 29393, 29397, 30806, 47238, 44121, 24684, 32241]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [33036, 33176, 48735, 31298, 44121, 27030, 29282, 28016, 47238, 33124, 30252, 31397, 52105, 30339, 34809, 33123, 29644, 22363, 28268, 28633]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 23885, 34409, 29331, 31759, 28068]
Topic: 0. Top: [32833, 37130, 27185, 20528, 30791, 29939, 30627, 37692, 33826, 32665, 30597, 34531, 35416, 38446, 32677, 28999, 19656, 28068, 42166, 34170]
Topic: 1. Top: [29282, 33123, 29237, 33125, 28701, 32510, 47238, 26745, 30339, 28695, 34871, 33036, 28995, 33176, 34317, 52105, 29902, 30160, 17194, 33124]
Topic: 2. Top: [33484, 20673, 38446, 26239, 28992, 28019, 31502, 32665, 43613, 39945, 40820, 44211, 36226, 21001, 32833, 27985, 25391, 20528, 37027, 34170]
Topic: 3. Top: [33036, 35023, 19828, 33125, 29282, 32510, 29559, 29259, 29237, 30152, 45841, 20164, 30339, 48622, 29939, 44259, 31298, 32939, 28884, 32678]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 21347, 29096, 29237, 29453]
Topic: 5. Top: [49838, 28172, 34287, 28100, 32833, 26190, 29939, 40029, 42030, 28095, 17856, 19656, 31374, 32717, 30119, 24123, 40409, 33036, 33123, 52215]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 40999, 29237, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [30791, 32833, 21123, 35657, 32135, 40029, 32665, 25943, 44211, 35538, 35416, 33123, 39872, 26567, 43613, 19656, 36303, 27086, 33707, 28393]
Topic: 8. Top: [30339, 47238, 30252, 34317, 29096, 29237, 30887, 33036, 29684, 32254, 31298, 33123, 29902, 47035, 30795, 45934, 17231, 29592, 37492, 37712]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 27643, 33036, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [34364, 24278, 40295, 38753, 35185, 34130, 32833, 50442, 28585, 30429, 36922, 34095, 25342, 29393, 29397, 30806, 47238, 44121, 24684, 32241]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [33036, 33176, 48735, 31298, 44121, 27030, 29282, 28016, 47238, 33124, 30252, 31397, 52105, 30339, 34809, 33123, 29644, 22363, 28268, 28633]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 23885, 34409, 29331, 31759, 28068]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1064736569248931
sparse_theta_sp: -0.4969335953319671
decorrelation: 0.01
fix: 1000000000
ext_decorr_good: 100000
num_topics: {'good': 11, 'bad': 2, 'not_good': 9, 'total_bad': 18}
7

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b71155520>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f7b712c3d30>}
Topic: 0. Top: [30791, 32833, 40029, 35416, 32665, 19656, 33826, 28999, 29939, 34170, 43613, 20528, 25945, 33123, 25220, 28393, 26567, 29033, 45727, 33176]
Topic: 1. Top: [47238, 33123, 31298, 33176, 30339, 29237, 30252, 52105, 33036, 33125, 48735, 34317, 31397, 29902, 29684, 44121, 17231, 28695, 19656, 30490]
Topic: 2. Top: [29237, 33125, 29282, 30339, 32510, 34317, 34871, 20164, 26745, 33036, 33124, 30160, 28695, 39719, 32939, 45841, 17194, 29116, 27136, 29902]
Topic: 3. Top: [30339, 32254, 33036, 37712, 28453, 34317, 29096, 37631, 45183, 30416, 30252, 20581, 30082, 32449, 33096, 28016, 30887, 33354, 30795, 52298]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 21347, 29096, 29237, 29453]
Topic: 5. Top: [49838, 37130, 32833, 28100, 34287, 33484, 37692, 28019, 27185, 29939, 38446, 30627, 28992, 26190, 30597, 34531, 28095, 20673, 20528, 17856]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 40999, 29237, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [28701, 29282, 33036, 28995, 26745, 30160, 33124, 32510, 33123, 40029, 29784, 28695, 33714, 30152, 20164, 27970, 32337, 52105, 32681, 47238]
Topic: 8. Top: [34364, 32833, 33036, 42030, 33123, 40295, 25342, 18601, 25025, 28585, 34130, 44121, 50442, 38753, 31374, 26745, 30444, 47238, 31777, 35185]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 27643, 33036, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [32833, 21123, 35657, 44211, 26809, 32135, 35538, 27587, 26864, 33484, 32665, 36303, 30791, 29592, 34571, 38446, 46714, 33707, 20164, 34729]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [28172, 49838, 28465, 36585, 28629, 35842, 27624, 21874, 33123, 52105, 19656, 33047, 22422, 28701, 30656, 17856, 21650, 40736, 28995, 29331]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 23885, 34409, 29331, 31759, 28068]
Topic: 0. Top: [30791, 32833, 40029, 35416, 32665, 19656, 33826, 28999, 29939, 34170, 43613, 20528, 25945, 33123, 25220, 28393, 26567, 29033, 45727, 33176]
Topic: 1. Top: [47238, 33123, 31298, 33176, 30339, 29237, 30252, 52105, 33036, 33125, 48735, 34317, 31397, 29902, 29684, 44121, 17231, 28695, 19656, 30490]
Topic: 2. Top: [29237, 33125, 29282, 30339, 32510, 34317, 34871, 20164, 26745, 33036, 33124, 30160, 28695, 39719, 32939, 45841, 17194, 29116, 27136, 29902]
Topic: 3. Top: [30339, 32254, 33036, 37712, 28453, 34317, 29096, 37631, 45183, 30416, 30252, 20581, 30082, 32449, 33096, 28016, 30887, 33354, 30795, 52298]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 21347, 29096, 29237, 29453]
Topic: 5. Top: [49838, 37130, 32833, 28100, 34287, 33484, 37692, 28019, 27185, 29939, 38446, 30627, 28992, 26190, 30597, 34531, 28095, 20673, 20528, 17856]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 40999, 29237, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [28701, 29282, 33036, 28995, 26745, 30160, 33124, 32510, 33123, 40029, 29784, 28695, 33714, 30152, 20164, 27970, 32337, 52105, 32681, 47238]
Topic: 8. Top: [34364, 32833, 33036, 42030, 33123, 40295, 25342, 18601, 25025, 28585, 34130, 44121, 50442, 38753, 31374, 26745, 30444, 47238, 31777, 35185]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 27643, 33036, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [32833, 21123, 35657, 44211, 26809, 32135, 35538, 27587, 26864, 33484, 32665, 36303, 30791, 29592, 34571, 38446, 46714, 33707, 20164, 34729]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [28172, 49838, 28465, 36585, 28629, 35842, 27624, 21874, 33123, 52105, 19656, 33047, 22422, 28701, 30656, 17856, 21650, 40736, 28995, 29331]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 23885, 34409, 29331, 31759, 28068]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1064736569248931
sparse_theta_sp: -0.4969335953319671
decorrelation: 0.01
fix: 1000000000
ext_decorr_good: 100000
SUCCESS: more good topics
DOWNFALL: more bad topics...
num_topics: {'good': 12, 'bad': 3, 'not_good': 8, 'total_bad': 21}
8

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b710da6d0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f7b890b7fa0>}
Topic: 0. Top: [47238, 33123, 29237, 30339, 33125, 29282, 31298, 34317, 29902, 30252, 32510, 33176, 26745, 33036, 33124, 28701, 52105, 28695, 34871, 29684]
Topic: 1. Top: [40029, 32833, 33176, 33123, 33036, 34364, 28393, 19656, 29784, 47238, 31298, 44121, 50442, 34871, 26745, 30490, 30444, 29282, 26916, 34317]
Topic: 2. Top: [27030, 40820, 32241, 21394, 28701, 25941, 24452, 32833, 29791, 27934, 26095, 22255, 43791, 17744, 19354, 28872, 27441, 18500, 25284, 18091]
Topic: 3. Top: [30339, 32254, 33036, 37712, 28453, 34317, 29096, 37631, 45183, 30416, 30252, 20581, 30082, 32449, 33096, 28016, 30887, 33354, 30795, 52298]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 21347, 29096, 29237, 29453]
Topic: 5. Top: [29237, 27624, 19656, 40295, 33047, 42456, 35057, 28252, 46583, 26627, 32929, 25540, 29282, 32665, 27835, 36226, 33746, 27540, 25163, 30655]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 40999, 29237, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [49838, 32833, 28100, 34287, 37130, 29939, 33826, 30627, 28019, 28095, 26190, 37692, 28775, 28999, 31192, 32677, 24123, 40409, 32135, 28992]
Topic: 8. Top: [28172, 35842, 33123, 37130, 22422, 30597, 27624, 42030, 21650, 17856, 19656, 27300, 27066, 33036, 49838, 45727, 34531, 31374, 25911, 35416]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 27643, 33036, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [30791, 32833, 33484, 32665, 43613, 27185, 44211, 20528, 35416, 35657, 38446, 25945, 34170, 26809, 42166, 19656, 20673, 32135, 33123, 21123]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [29282, 32510, 33125, 33036, 20164, 28701, 28695, 30152, 35023, 30160, 32678, 28995, 19828, 26745, 44259, 27136, 45841, 33124, 27970, 29259]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 23885, 34409, 29331, 31759, 28068]
Topic: 0. Top: [47238, 33123, 29237, 30339, 33125, 29282, 31298, 34317, 29902, 30252, 32510, 33176, 26745, 33036, 33124, 28701, 52105, 28695, 34871, 29684]
Topic: 1. Top: [40029, 32833, 33176, 33123, 33036, 34364, 28393, 19656, 29784, 47238, 31298, 44121, 50442, 34871, 26745, 30490, 30444, 29282, 26916, 34317]
Topic: 2. Top: [27030, 40820, 32241, 21394, 28701, 25941, 24452, 32833, 29791, 27934, 26095, 22255, 43791, 17744, 19354, 28872, 27441, 18500, 25284, 18091]
Topic: 3. Top: [30339, 32254, 33036, 37712, 28453, 34317, 29096, 37631, 45183, 30416, 30252, 20581, 30082, 32449, 33096, 28016, 30887, 33354, 30795, 52298]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 21347, 29096, 29237, 29453]
Topic: 5. Top: [29237, 27624, 19656, 40295, 33047, 42456, 35057, 28252, 46583, 26627, 32929, 25540, 29282, 32665, 27835, 36226, 33746, 27540, 25163, 30655]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 40999, 29237, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [49838, 32833, 28100, 34287, 37130, 29939, 33826, 30627, 28019, 28095, 26190, 37692, 28775, 28999, 31192, 32677, 24123, 40409, 32135, 28992]
Topic: 8. Top: [28172, 35842, 33123, 37130, 22422, 30597, 27624, 42030, 21650, 17856, 19656, 27300, 27066, 33036, 49838, 45727, 34531, 31374, 25911, 35416]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 27643, 33036, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [30791, 32833, 33484, 32665, 43613, 27185, 44211, 20528, 35416, 35657, 38446, 25945, 34170, 26809, 42166, 19656, 20673, 32135, 33123, 21123]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [29282, 32510, 33125, 33036, 20164, 28701, 28695, 30152, 35023, 30160, 32678, 28995, 19828, 26745, 44259, 27136, 45841, 33124, 27970, 29259]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 23885, 34409, 29331, 31759, 28068]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.11978286404050471
sparse_theta_sp: -0.559050294748463
decorrelation: 0.01
fix: 1000000000
ext_decorr_good: 100000
num_topics: {'good': 12, 'bad': 3, 'not_good': 8, 'total_bad': 24}
9

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8926b400>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f7b8ee4f370>}
Topic: 0. Top: [20528, 27185, 28068, 42166, 32665, 28992, 33484, 32833, 26809, 29939, 25911, 39945, 30627, 29834, 34571, 27787, 26165, 49264, 35657, 22254]
Topic: 1. Top: [32833, 33484, 43613, 40029, 38446, 20673, 26239, 39872, 46714, 32665, 19656, 44211, 33123, 25025, 26306, 35416, 31502, 33176, 47079, 27587]
Topic: 2. Top: [28172, 34364, 28629, 34130, 34095, 33707, 24278, 38753, 49838, 27624, 35185, 40736, 17856, 29272, 30429, 21394, 31133, 24256, 24684, 42030]
Topic: 3. Top: [30339, 32254, 33036, 37712, 28453, 34317, 29096, 37631, 45183, 30416, 30252, 20581, 30082, 32449, 33096, 28016, 30887, 33354, 30795, 52298]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 21347, 29096, 29237, 29453]
Topic: 5. Top: [35842, 28465, 21650, 52105, 22422, 27624, 36585, 27066, 33123, 40295, 29282, 30656, 21874, 50488, 31301, 48735, 34966, 30036, 27937, 26952]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 40999, 29237, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [29237, 29282, 32510, 30339, 19656, 26627, 33125, 47238, 32677, 29902, 21874, 33047, 29096, 27187, 31186, 42456, 27540, 31298, 32665, 26192]
Topic: 8. Top: [33123, 47238, 33125, 29282, 33036, 29237, 30339, 28701, 33176, 34317, 26745, 31298, 32510, 28695, 34871, 33124, 30160, 30252, 28995, 17194]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 27643, 33036, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [30791, 32833, 37130, 35416, 40029, 35657, 21123, 30597, 33123, 19656, 33826, 32665, 28999, 32135, 44211, 38446, 34531, 25945, 29939, 28368]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [49838, 28100, 34287, 26190, 28095, 29939, 37130, 32833, 30119, 40409, 24123, 32717, 28775, 51400, 36268, 17856, 31374, 52215, 23120, 30627]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 23885, 34409, 29331, 31759, 28068]
Topic: 0. Top: [20528, 27185, 28068, 42166, 32665, 28992, 33484, 32833, 26809, 29939, 25911, 39945, 30627, 29834, 34571, 27787, 26165, 49264, 35657, 22254]
Topic: 1. Top: [32833, 33484, 43613, 40029, 38446, 20673, 26239, 39872, 46714, 32665, 19656, 44211, 33123, 25025, 26306, 35416, 31502, 33176, 47079, 27587]
Topic: 2. Top: [28172, 34364, 28629, 34130, 34095, 33707, 24278, 38753, 49838, 27624, 35185, 40736, 17856, 29272, 30429, 21394, 31133, 24256, 24684, 42030]
Topic: 3. Top: [30339, 32254, 33036, 37712, 28453, 34317, 29096, 37631, 45183, 30416, 30252, 20581, 30082, 32449, 33096, 28016, 30887, 33354, 30795, 52298]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 21347, 29096, 29237, 29453]
Topic: 5. Top: [35842, 28465, 21650, 52105, 22422, 27624, 36585, 27066, 33123, 40295, 29282, 30656, 21874, 50488, 31301, 48735, 34966, 30036, 27937, 26952]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 40999, 29237, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [29237, 29282, 32510, 30339, 19656, 26627, 33125, 47238, 32677, 29902, 21874, 33047, 29096, 27187, 31186, 42456, 27540, 31298, 32665, 26192]
Topic: 8. Top: [33123, 47238, 33125, 29282, 33036, 29237, 30339, 28701, 33176, 34317, 26745, 31298, 32510, 28695, 34871, 33124, 30160, 30252, 28995, 17194]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 27643, 33036, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [30791, 32833, 37130, 35416, 40029, 35657, 21123, 30597, 33123, 19656, 33826, 32665, 28999, 32135, 44211, 38446, 34531, 25945, 29939, 28368]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [49838, 28100, 34287, 26190, 28095, 29939, 37130, 32833, 30119, 40409, 24123, 32717, 28775, 51400, 36268, 17856, 31374, 52215, 23120, 30627]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 23885, 34409, 29331, 31759, 28068]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.11978286404050471
sparse_theta_sp: -0.559050294748463
decorrelation: 0.01
fix: 1000000000
ext_decorr_good: 100000
SUCCESS: more good topics
SUCCESS: less bad topics
num_topics: {'good': 13, 'bad': 1, 'not_good': 7, 'total_bad': 25}
10

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b711554c0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f7b8e8a4640>}
Topic: 0. Top: [32833, 34364, 28701, 33036, 33176, 33123, 28629, 32510, 40029, 28995, 42030, 20164, 30152, 19656, 26745, 47238, 28695, 50442, 17856, 30444]
Topic: 1. Top: [28172, 27030, 31298, 33123, 30656, 32241, 30806, 47238, 40295, 34012, 48735, 30130, 21580, 42892, 19933, 52105, 22725, 29109, 24278, 19780]
Topic: 2. Top: [30791, 32833, 32665, 35416, 40029, 20528, 19656, 27185, 29939, 25945, 33826, 35657, 33123, 34170, 37130, 44211, 32677, 34531, 30597, 32135]
Topic: 3. Top: [30339, 32254, 33036, 37712, 28453, 34317, 29096, 37631, 45183, 30416, 30252, 20581, 30082, 32449, 33096, 28016, 30887, 33354, 30795, 52298]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 21347, 29096, 29237, 29453]
Topic: 5. Top: [33484, 43613, 38446, 20673, 28992, 21123, 26239, 27587, 44211, 32135, 36303, 35657, 21001, 27985, 34571, 30833, 27185, 30750, 46714, 32833]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 40999, 29237, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [29237, 29282, 33125, 47238, 30339, 33123, 33036, 32510, 34317, 26745, 28695, 33124, 31298, 28701, 33176, 34871, 30160, 29902, 30252, 17194]
Topic: 8. Top: [19656, 32665, 52105, 21874, 33047, 42456, 35331, 31186, 32929, 27624, 31803, 28252, 36376, 26192, 26627, 33746, 27540, 28535, 32677, 25540]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 27643, 33036, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [35842, 27066, 21650, 50488, 27624, 28068, 26483, 27300, 39575, 52456, 35223, 32545, 37974, 17853, 21394, 37130, 17905, 25284, 24684, 46583]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [49838, 28100, 34287, 26190, 28095, 29939, 37130, 32833, 30119, 40409, 24123, 32717, 28775, 51400, 36268, 17856, 31374, 52215, 23120, 30627]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 23885, 34409, 29331, 31759, 28068]
Topic: 0. Top: [32833, 34364, 28701, 33036, 33176, 33123, 28629, 32510, 40029, 28995, 42030, 20164, 30152, 19656, 26745, 47238, 28695, 50442, 17856, 30444]
Topic: 1. Top: [28172, 27030, 31298, 33123, 30656, 32241, 30806, 47238, 40295, 34012, 48735, 30130, 21580, 42892, 19933, 52105, 22725, 29109, 24278, 19780]
Topic: 2. Top: [30791, 32833, 32665, 35416, 40029, 20528, 19656, 27185, 29939, 25945, 33826, 35657, 33123, 34170, 37130, 44211, 32677, 34531, 30597, 32135]
Topic: 3. Top: [30339, 32254, 33036, 37712, 28453, 34317, 29096, 37631, 45183, 30416, 30252, 20581, 30082, 32449, 33096, 28016, 30887, 33354, 30795, 52298]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 21347, 29096, 29237, 29453]
Topic: 5. Top: [33484, 43613, 38446, 20673, 28992, 21123, 26239, 27587, 44211, 32135, 36303, 35657, 21001, 27985, 34571, 30833, 27185, 30750, 46714, 32833]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 40999, 29237, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [29237, 29282, 33125, 47238, 30339, 33123, 33036, 32510, 34317, 26745, 28695, 33124, 31298, 28701, 33176, 34871, 30160, 29902, 30252, 17194]
Topic: 8. Top: [19656, 32665, 52105, 21874, 33047, 42456, 35331, 31186, 32929, 27624, 31803, 28252, 36376, 26192, 26627, 33746, 27540, 28535, 32677, 25540]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 27643, 33036, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [35842, 27066, 21650, 50488, 27624, 28068, 26483, 27300, 39575, 52456, 35223, 32545, 37974, 17853, 21394, 37130, 17905, 25284, 24684, 46583]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [49838, 28100, 34287, 26190, 28095, 29939, 37130, 32833, 30119, 40409, 24123, 32717, 28775, 51400, 36268, 17856, 31374, 52215, 23120, 30627]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 23885, 34409, 29331, 31759, 28068]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1368947017605768
sparse_theta_sp: -0.638914622569672
decorrelation: 0.01
fix: 1000000000
ext_decorr_good: 100000
SUCCESS: more good topics
DOWNFALL: more bad topics...
num_topics: {'good': 14, 'bad': 2, 'not_good': 6, 'total_bad': 27}
11

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8ea13f10>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f7b8eb8b700>}
Topic: 0. Top: [19656, 32665, 21874, 52105, 27624, 33047, 31803, 42456, 32929, 35331, 31622, 26627, 36376, 33746, 26192, 31186, 27540, 28252, 21394, 47238]
Topic: 1. Top: [33036, 29282, 32510, 33125, 30339, 20164, 26745, 33123, 28701, 33124, 34871, 35023, 28695, 33176, 29728, 28995, 32833, 28393, 30152, 27136]
Topic: 2. Top: [30791, 27030, 25220, 35538, 39872, 26567, 40029, 32833, 31397, 32241, 19656, 33707, 32275, 32135, 26440, 27334, 30806, 19933, 34130, 33123]
Topic: 3. Top: [30339, 32254, 33036, 37712, 28453, 34317, 29096, 37631, 45183, 30416, 30252, 20581, 30082, 32449, 33096, 28016, 30887, 33354, 30795, 52298]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 21347, 29096, 29237, 29453]
Topic: 5. Top: [33484, 43613, 38446, 20673, 28992, 21123, 26239, 27587, 44211, 32135, 36303, 35657, 21001, 27985, 34571, 30833, 27185, 30750, 46714, 32833]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 40999, 29237, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [28172, 34364, 33123, 28629, 22422, 47238, 28701, 17856, 24278, 34095, 21580, 44121, 40736, 30656, 30429, 35185, 35842, 31133, 50442, 42030]
Topic: 8. Top: [47238, 29237, 33125, 29282, 33123, 31298, 30339, 30252, 34317, 30160, 33176, 28701, 29902, 29096, 29684, 29116, 17231, 28695, 33124, 17194]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 27643, 33036, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [30791, 32833, 32665, 37130, 20528, 35416, 29939, 33826, 27185, 40029, 25945, 34531, 30597, 19656, 30627, 37692, 28999, 34170, 32677, 28368]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [49838, 28100, 34287, 26190, 28095, 29939, 37130, 32833, 30119, 40409, 24123, 32717, 28775, 51400, 36268, 17856, 31374, 52215, 23120, 30627]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 23885, 34409, 29331, 31759, 28068]
Topic: 0. Top: [19656, 32665, 21874, 52105, 27624, 33047, 31803, 42456, 32929, 35331, 31622, 26627, 36376, 33746, 26192, 31186, 27540, 28252, 21394, 47238]
Topic: 1. Top: [33036, 29282, 32510, 33125, 30339, 20164, 26745, 33123, 28701, 33124, 34871, 35023, 28695, 33176, 29728, 28995, 32833, 28393, 30152, 27136]
Topic: 2. Top: [30791, 27030, 25220, 35538, 39872, 26567, 40029, 32833, 31397, 32241, 19656, 33707, 32275, 32135, 26440, 27334, 30806, 19933, 34130, 33123]
Topic: 3. Top: [30339, 32254, 33036, 37712, 28453, 34317, 29096, 37631, 45183, 30416, 30252, 20581, 30082, 32449, 33096, 28016, 30887, 33354, 30795, 52298]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 21347, 29096, 29237, 29453]
Topic: 5. Top: [33484, 43613, 38446, 20673, 28992, 21123, 26239, 27587, 44211, 32135, 36303, 35657, 21001, 27985, 34571, 30833, 27185, 30750, 46714, 32833]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 40999, 29237, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [28172, 34364, 33123, 28629, 22422, 47238, 28701, 17856, 24278, 34095, 21580, 44121, 40736, 30656, 30429, 35185, 35842, 31133, 50442, 42030]
Topic: 8. Top: [47238, 29237, 33125, 29282, 33123, 31298, 30339, 30252, 34317, 30160, 33176, 28701, 29902, 29096, 29684, 29116, 17231, 28695, 33124, 17194]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 27643, 33036, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [30791, 32833, 32665, 37130, 20528, 35416, 29939, 33826, 27185, 40029, 25945, 34531, 30597, 19656, 30627, 37692, 28999, 34170, 32677, 28368]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [49838, 28100, 34287, 26190, 28095, 29939, 37130, 32833, 30119, 40409, 24123, 32717, 28775, 51400, 36268, 17856, 31374, 52215, 23120, 30627]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 23885, 34409, 29331, 31759, 28068]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.15971048538733962
sparse_theta_sp: -0.7454003929979507
decorrelation: 0.01
fix: 1000000000
ext_decorr_good: 100000
num_topics: {'good': 14, 'bad': 2, 'not_good': 6, 'total_bad': 29}
12

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b89239160>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f7b711ae970>}
Topic: 0. Top: [47238, 29237, 29282, 33125, 33123, 30339, 33036, 32510, 34317, 31298, 33176, 26745, 28701, 28695, 33124, 34871, 30160, 29902, 30252, 17194]
Topic: 1. Top: [19656, 32665, 21874, 52105, 33047, 35331, 42456, 30656, 36585, 32929, 31186, 25025, 28252, 28465, 27540, 32677, 26627, 31622, 27624, 33746]
Topic: 2. Top: [28172, 34364, 33123, 28629, 28701, 32833, 42030, 22422, 25342, 17856, 34095, 24278, 28995, 44121, 30429, 47238, 30806, 27624, 40736, 49838]
Topic: 3. Top: [30339, 32254, 33036, 37712, 28453, 34317, 29096, 37631, 45183, 30416, 30252, 20581, 30082, 32449, 33096, 28016, 30887, 33354, 30795, 52298]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 21347, 29096, 29237, 29453]
Topic: 5. Top: [33484, 43613, 38446, 20673, 28992, 21123, 26239, 27587, 44211, 32135, 36303, 35657, 21001, 27985, 34571, 30833, 27185, 30750, 46714, 32833]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 40999, 29237, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [30791, 32833, 35416, 32665, 40029, 19656, 35657, 25945, 29939, 33123, 35538, 25220, 39872, 26567, 27086, 20528, 26809, 44211, 34170, 45727]
Topic: 8. Top: [29259, 47035, 30887, 46583, 19828, 45841, 27934, 27030, 20164, 40820, 29205, 36226, 33380, 21394, 25163, 26095, 30655, 22725, 19933, 29363]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 27643, 33036, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [37130, 30597, 34531, 27185, 37692, 20528, 28019, 35842, 38446, 32833, 27300, 30627, 28368, 31192, 28701, 26306, 41785, 33826, 31964, 28999]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [49838, 28100, 34287, 26190, 28095, 29939, 37130, 32833, 30119, 40409, 24123, 32717, 28775, 51400, 36268, 17856, 31374, 52215, 23120, 30627]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 23885, 34409, 29331, 31759, 28068]
Topic: 0. Top: [47238, 29237, 29282, 33125, 33123, 30339, 33036, 32510, 34317, 31298, 33176, 26745, 28701, 28695, 33124, 34871, 30160, 29902, 30252, 17194]
Topic: 1. Top: [19656, 32665, 21874, 52105, 33047, 35331, 42456, 30656, 36585, 32929, 31186, 25025, 28252, 28465, 27540, 32677, 26627, 31622, 27624, 33746]
Topic: 2. Top: [28172, 34364, 33123, 28629, 28701, 32833, 42030, 22422, 25342, 17856, 34095, 24278, 28995, 44121, 30429, 47238, 30806, 27624, 40736, 49838]
Topic: 3. Top: [30339, 32254, 33036, 37712, 28453, 34317, 29096, 37631, 45183, 30416, 30252, 20581, 30082, 32449, 33096, 28016, 30887, 33354, 30795, 52298]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 21347, 29096, 29237, 29453]
Topic: 5. Top: [33484, 43613, 38446, 20673, 28992, 21123, 26239, 27587, 44211, 32135, 36303, 35657, 21001, 27985, 34571, 30833, 27185, 30750, 46714, 32833]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 40999, 29237, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [30791, 32833, 35416, 32665, 40029, 19656, 35657, 25945, 29939, 33123, 35538, 25220, 39872, 26567, 27086, 20528, 26809, 44211, 34170, 45727]
Topic: 8. Top: [29259, 47035, 30887, 46583, 19828, 45841, 27934, 27030, 20164, 40820, 29205, 36226, 33380, 21394, 25163, 26095, 30655, 22725, 19933, 29363]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 27643, 33036, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [37130, 30597, 34531, 27185, 37692, 20528, 28019, 35842, 38446, 32833, 27300, 30627, 28368, 31192, 28701, 26306, 41785, 33826, 31964, 28999]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [49838, 28100, 34287, 26190, 28095, 29939, 37130, 32833, 30119, 40409, 24123, 32717, 28775, 51400, 36268, 17856, 31374, 52215, 23120, 30627]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 23885, 34409, 29331, 31759, 28068]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.15971048538733962
sparse_theta_sp: -0.7454003929979507
decorrelation: 0.01
fix: 1000000000
ext_decorr_good: 100000
SUCCESS: less bad topics
num_topics: {'good': 14, 'bad': 1, 'not_good': 6, 'total_bad': 30}
13

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b89322790>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f7b893e5c40>}
Topic: 0. Top: [29282, 29237, 33125, 32510, 33036, 20164, 30339, 34871, 28695, 35023, 33124, 27136, 30160, 28701, 32939, 26745, 44259, 45841, 34317, 19828]
Topic: 1. Top: [32833, 40029, 35416, 37130, 33826, 30791, 19656, 30597, 33123, 34531, 37692, 28999, 30627, 29939, 28368, 33036, 25945, 28019, 31192, 33176]
Topic: 2. Top: [52105, 29237, 29282, 47238, 19656, 21874, 33123, 32510, 29902, 33125, 33047, 28465, 26627, 29096, 30339, 36585, 32677, 33176, 28701, 26192]
Topic: 3. Top: [30339, 32254, 33036, 37712, 28453, 34317, 29096, 37631, 45183, 30416, 30252, 20581, 30082, 32449, 33096, 28016, 30887, 33354, 30795, 52298]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 21347, 29096, 29237, 29453]
Topic: 5. Top: [33484, 43613, 38446, 20673, 28992, 21123, 26239, 27587, 44211, 32135, 36303, 35657, 21001, 27985, 34571, 30833, 27185, 30750, 46714, 32833]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 40999, 29237, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [47238, 33123, 31298, 33176, 30339, 30252, 29237, 33036, 33125, 28701, 48735, 26745, 34317, 44121, 33124, 29684, 17231, 29282, 30160, 31397]
Topic: 8. Top: [30791, 32665, 32833, 35657, 20528, 28068, 35538, 26567, 49264, 27086, 42166, 29592, 27185, 34729, 26809, 19656, 52456, 29939, 26165, 39945]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 27643, 33036, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [28172, 34364, 28629, 40295, 24278, 17856, 34095, 34130, 29272, 40736, 38753, 35185, 30429, 31133, 40820, 32241, 22028, 25342, 30806, 27030]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [49838, 28100, 34287, 26190, 28095, 29939, 37130, 32833, 30119, 40409, 24123, 32717, 28775, 51400, 36268, 17856, 31374, 52215, 23120, 30627]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 23885, 34409, 29331, 31759, 28068]
Topic: 0. Top: [29282, 29237, 33125, 32510, 33036, 20164, 30339, 34871, 28695, 35023, 33124, 27136, 30160, 28701, 32939, 26745, 44259, 45841, 34317, 19828]
Topic: 1. Top: [32833, 40029, 35416, 37130, 33826, 30791, 19656, 30597, 33123, 34531, 37692, 28999, 30627, 29939, 28368, 33036, 25945, 28019, 31192, 33176]
Topic: 2. Top: [52105, 29237, 29282, 47238, 19656, 21874, 33123, 32510, 29902, 33125, 33047, 28465, 26627, 29096, 30339, 36585, 32677, 33176, 28701, 26192]
Topic: 3. Top: [30339, 32254, 33036, 37712, 28453, 34317, 29096, 37631, 45183, 30416, 30252, 20581, 30082, 32449, 33096, 28016, 30887, 33354, 30795, 52298]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 21347, 29096, 29237, 29453]
Topic: 5. Top: [33484, 43613, 38446, 20673, 28992, 21123, 26239, 27587, 44211, 32135, 36303, 35657, 21001, 27985, 34571, 30833, 27185, 30750, 46714, 32833]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 40999, 29237, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [47238, 33123, 31298, 33176, 30339, 30252, 29237, 33036, 33125, 28701, 48735, 26745, 34317, 44121, 33124, 29684, 17231, 29282, 30160, 31397]
Topic: 8. Top: [30791, 32665, 32833, 35657, 20528, 28068, 35538, 26567, 49264, 27086, 42166, 29592, 27185, 34729, 26809, 19656, 52456, 29939, 26165, 39945]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 27643, 33036, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [28172, 34364, 28629, 40295, 24278, 17856, 34095, 34130, 29272, 40736, 38753, 35185, 30429, 31133, 40820, 32241, 22028, 25342, 30806, 27030]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [49838, 28100, 34287, 26190, 28095, 29939, 37130, 32833, 30119, 40409, 24123, 32717, 28775, 51400, 36268, 17856, 31374, 52215, 23120, 30627]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 23885, 34409, 29331, 31759, 28068]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.15971048538733962
sparse_theta_sp: -0.7454003929979507
decorrelation: 0.01
fix: 1000000000
ext_decorr_good: 100000
DOWNFALL: more bad topics...
num_topics: {'good': 14, 'bad': 3, 'not_good': 6, 'total_bad': 33}
14

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8ee71dc0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f7b8ee71cd0>}
Topic: 0. Top: [30791, 32833, 32665, 35416, 20528, 37130, 40029, 19656, 29939, 27185, 25945, 33826, 34531, 30597, 34170, 30627, 28999, 32677, 35657, 37692]
Topic: 1. Top: [29282, 29237, 33125, 33036, 30339, 32510, 20164, 35023, 33124, 45841, 28884, 19828, 34317, 28695, 44259, 30160, 32678, 29259, 27136, 32939]
Topic: 2. Top: [29272, 30655, 42892, 27030, 27532, 33707, 40157, 24625, 29791, 22255, 31228, 31556, 18500, 19382, 34621, 43791, 24901, 43719, 17744, 37854]
Topic: 3. Top: [30339, 32254, 33036, 37712, 28453, 34317, 29096, 37631, 45183, 30416, 30252, 20581, 30082, 32449, 33096, 28016, 30887, 33354, 30795, 52298]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 21347, 29096, 29237, 29453]
Topic: 5. Top: [33484, 43613, 38446, 20673, 28992, 21123, 26239, 27587, 44211, 32135, 36303, 35657, 21001, 27985, 34571, 30833, 27185, 30750, 46714, 32833]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 40999, 29237, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [29237, 21874, 32665, 52105, 19656, 33047, 26627, 31803, 32929, 30656, 28465, 27540, 31622, 32677, 36226, 29282, 42456, 31186, 33746, 47238]
Topic: 8. Top: [33123, 28701, 29282, 26745, 33125, 28695, 34871, 32510, 28995, 28172, 47238, 33176, 33036, 29728, 29902, 29784, 34317, 29237, 30339, 34803]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 27643, 33036, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [47238, 33123, 31298, 30252, 33176, 29237, 48735, 30339, 33036, 44121, 29684, 17231, 33125, 34317, 33124, 31397, 29116, 29282, 29902, 30160]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [49838, 28100, 34287, 26190, 28095, 29939, 37130, 32833, 30119, 40409, 24123, 32717, 28775, 51400, 36268, 17856, 31374, 52215, 23120, 30627]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 23885, 34409, 29331, 31759, 28068]
Topic: 0. Top: [30791, 32833, 32665, 35416, 20528, 37130, 40029, 19656, 29939, 27185, 25945, 33826, 34531, 30597, 34170, 30627, 28999, 32677, 35657, 37692]
Topic: 1. Top: [29282, 29237, 33125, 33036, 30339, 32510, 20164, 35023, 33124, 45841, 28884, 19828, 34317, 28695, 44259, 30160, 32678, 29259, 27136, 32939]
Topic: 2. Top: [29272, 30655, 42892, 27030, 27532, 33707, 40157, 24625, 29791, 22255, 31228, 31556, 18500, 19382, 34621, 43791, 24901, 43719, 17744, 37854]
Topic: 3. Top: [30339, 32254, 33036, 37712, 28453, 34317, 29096, 37631, 45183, 30416, 30252, 20581, 30082, 32449, 33096, 28016, 30887, 33354, 30795, 52298]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 21347, 29096, 29237, 29453]
Topic: 5. Top: [33484, 43613, 38446, 20673, 28992, 21123, 26239, 27587, 44211, 32135, 36303, 35657, 21001, 27985, 34571, 30833, 27185, 30750, 46714, 32833]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 40999, 29237, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [29237, 21874, 32665, 52105, 19656, 33047, 26627, 31803, 32929, 30656, 28465, 27540, 31622, 32677, 36226, 29282, 42456, 31186, 33746, 47238]
Topic: 8. Top: [33123, 28701, 29282, 26745, 33125, 28695, 34871, 32510, 28995, 28172, 47238, 33176, 33036, 29728, 29902, 29784, 34317, 29237, 30339, 34803]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 27643, 33036, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [47238, 33123, 31298, 30252, 33176, 29237, 48735, 30339, 33036, 44121, 29684, 17231, 33125, 34317, 33124, 31397, 29116, 29282, 29902, 30160]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [49838, 28100, 34287, 26190, 28095, 29939, 37130, 32833, 30119, 40409, 24123, 32717, 28775, 51400, 36268, 17856, 31374, 52215, 23120, 30627]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 23885, 34409, 29331, 31759, 28068]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.15971048538733962
sparse_theta_sp: -0.7454003929979507
decorrelation: 0.01
fix: 1000000000
ext_decorr_good: 100000
num_topics: {'good': 14, 'bad': 3, 'not_good': 6, 'total_bad': 36}
15

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8ee1c5e0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f7b89226c40>}
Topic: 0. Top: [29282, 33125, 20164, 35023, 32510, 33036, 27136, 19828, 28884, 28995, 44259, 33124, 29784, 29939, 19330, 28695, 29559, 29237, 31298, 22786]
Topic: 1. Top: [29237, 30339, 47238, 29282, 33125, 33123, 34317, 32510, 26745, 33036, 31298, 29902, 34871, 30160, 33176, 28701, 33124, 28695, 29684, 30252]
Topic: 2. Top: [30791, 35538, 35657, 34729, 26809, 28068, 26165, 29592, 46583, 27086, 21123, 32665, 26567, 52456, 31747, 42166, 21394, 17905, 27334, 40521]
Topic: 3. Top: [30339, 32254, 33036, 37712, 28453, 34317, 29096, 37631, 45183, 30416, 30252, 20581, 30082, 32449, 33096, 28016, 30887, 33354, 30795, 52298]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 21347, 29096, 29237, 29453]
Topic: 5. Top: [33484, 43613, 38446, 20673, 28992, 21123, 26239, 27587, 44211, 32135, 36303, 35657, 21001, 27985, 34571, 30833, 27185, 30750, 46714, 32833]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 40999, 29237, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [30791, 32833, 37130, 35416, 40029, 32665, 20528, 29939, 33826, 19656, 25945, 27185, 30597, 34531, 30627, 37692, 28999, 28368, 34170, 31192]
Topic: 8. Top: [32833, 21580, 40295, 18601, 28585, 25025, 42030, 22209, 33036, 45727, 37265, 19656, 47079, 33047, 36585, 30656, 32510, 33123, 35416, 28701]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 27643, 33036, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [28172, 47238, 33123, 52105, 31298, 33176, 44121, 19656, 28701, 46780, 21874, 28695, 48735, 33036, 28995, 50442, 28629, 30444, 26745, 29116]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [49838, 28100, 34287, 26190, 28095, 29939, 37130, 32833, 30119, 40409, 24123, 32717, 28775, 51400, 36268, 17856, 31374, 52215, 23120, 30627]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 23885, 34409, 29331, 31759, 28068]
Topic: 0. Top: [29282, 33125, 20164, 35023, 32510, 33036, 27136, 19828, 28884, 28995, 44259, 33124, 29784, 29939, 19330, 28695, 29559, 29237, 31298, 22786]
Topic: 1. Top: [29237, 30339, 47238, 29282, 33125, 33123, 34317, 32510, 26745, 33036, 31298, 29902, 34871, 30160, 33176, 28701, 33124, 28695, 29684, 30252]
Topic: 2. Top: [30791, 35538, 35657, 34729, 26809, 28068, 26165, 29592, 46583, 27086, 21123, 32665, 26567, 52456, 31747, 42166, 21394, 17905, 27334, 40521]
Topic: 3. Top: [30339, 32254, 33036, 37712, 28453, 34317, 29096, 37631, 45183, 30416, 30252, 20581, 30082, 32449, 33096, 28016, 30887, 33354, 30795, 52298]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 21347, 29096, 29237, 29453]
Topic: 5. Top: [33484, 43613, 38446, 20673, 28992, 21123, 26239, 27587, 44211, 32135, 36303, 35657, 21001, 27985, 34571, 30833, 27185, 30750, 46714, 32833]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 40999, 29237, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [30791, 32833, 37130, 35416, 40029, 32665, 20528, 29939, 33826, 19656, 25945, 27185, 30597, 34531, 30627, 37692, 28999, 28368, 34170, 31192]
Topic: 8. Top: [32833, 21580, 40295, 18601, 28585, 25025, 42030, 22209, 33036, 45727, 37265, 19656, 47079, 33047, 36585, 30656, 32510, 33123, 35416, 28701]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 27643, 33036, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [28172, 47238, 33123, 52105, 31298, 33176, 44121, 19656, 28701, 46780, 21874, 28695, 48735, 33036, 28995, 50442, 28629, 30444, 26745, 29116]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [49838, 28100, 34287, 26190, 28095, 29939, 37130, 32833, 30119, 40409, 24123, 32717, 28775, 51400, 36268, 17856, 31374, 52215, 23120, 30627]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 23885, 34409, 29331, 31759, 28068]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.15971048538733962
sparse_theta_sp: -0.7454003929979507
decorrelation: 0.01
fix: 1000000000
ext_decorr_good: 100000
SUCCESS: more good topics
num_topics: {'good': 15, 'bad': 3, 'not_good': 5, 'total_bad': 39}
16

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8b95cb80>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f7b89547040>}
Topic: 0. Top: [29237, 33125, 29282, 32510, 30339, 20164, 33036, 30160, 19828, 45841, 44259, 30152, 33124, 27970, 32678, 28995, 27136, 28695, 34871, 31298]
Topic: 1. Top: [19656, 21874, 33047, 32665, 40295, 28465, 29237, 30656, 32929, 36585, 31622, 35331, 42456, 22209, 28252, 52105, 32677, 27540, 28535, 35619]
Topic: 2. Top: [30791, 35538, 35657, 34729, 26809, 28068, 26165, 29592, 46583, 27086, 21123, 32665, 26567, 52456, 31747, 42166, 21394, 17905, 27334, 40521]
Topic: 3. Top: [30339, 32254, 33036, 37712, 28453, 34317, 29096, 37631, 45183, 30416, 30252, 20581, 30082, 32449, 33096, 28016, 30887, 33354, 30795, 52298]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 21347, 29096, 29237, 29453]
Topic: 5. Top: [33484, 43613, 38446, 20673, 28992, 21123, 26239, 27587, 44211, 32135, 36303, 35657, 21001, 27985, 34571, 30833, 27185, 30750, 46714, 32833]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 40999, 29237, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [29282, 47238, 30339, 17194, 29684, 27030, 33125, 31298, 48735, 17231, 34317, 30252, 17853, 28016, 31397, 34966, 29592, 30444, 29902, 35023]
Topic: 8. Top: [30791, 32833, 37130, 35416, 20528, 33826, 40029, 29939, 34531, 30597, 37692, 25945, 27185, 30627, 32665, 28368, 31192, 34170, 19656, 28019]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 27643, 33036, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [33123, 47238, 28701, 33176, 33125, 33036, 31298, 28695, 26745, 34871, 28172, 44121, 29237, 34317, 33124, 32510, 30252, 30339, 28995, 29784]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [49838, 28100, 34287, 26190, 28095, 29939, 37130, 32833, 30119, 40409, 24123, 32717, 28775, 51400, 36268, 17856, 31374, 52215, 23120, 30627]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 23885, 34409, 29331, 31759, 28068]
Topic: 0. Top: [29237, 33125, 29282, 32510, 30339, 20164, 33036, 30160, 19828, 45841, 44259, 30152, 33124, 27970, 32678, 28995, 27136, 28695, 34871, 31298]
Topic: 1. Top: [19656, 21874, 33047, 32665, 40295, 28465, 29237, 30656, 32929, 36585, 31622, 35331, 42456, 22209, 28252, 52105, 32677, 27540, 28535, 35619]
Topic: 2. Top: [30791, 35538, 35657, 34729, 26809, 28068, 26165, 29592, 46583, 27086, 21123, 32665, 26567, 52456, 31747, 42166, 21394, 17905, 27334, 40521]
Topic: 3. Top: [30339, 32254, 33036, 37712, 28453, 34317, 29096, 37631, 45183, 30416, 30252, 20581, 30082, 32449, 33096, 28016, 30887, 33354, 30795, 52298]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 21347, 29096, 29237, 29453]
Topic: 5. Top: [33484, 43613, 38446, 20673, 28992, 21123, 26239, 27587, 44211, 32135, 36303, 35657, 21001, 27985, 34571, 30833, 27185, 30750, 46714, 32833]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 40999, 29237, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [29282, 47238, 30339, 17194, 29684, 27030, 33125, 31298, 48735, 17231, 34317, 30252, 17853, 28016, 31397, 34966, 29592, 30444, 29902, 35023]
Topic: 8. Top: [30791, 32833, 37130, 35416, 20528, 33826, 40029, 29939, 34531, 30597, 37692, 25945, 27185, 30627, 32665, 28368, 31192, 34170, 19656, 28019]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 27643, 33036, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [33123, 47238, 28701, 33176, 33125, 33036, 31298, 28695, 26745, 34871, 28172, 44121, 29237, 34317, 33124, 32510, 30252, 30339, 28995, 29784]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [49838, 28100, 34287, 26190, 28095, 29939, 37130, 32833, 30119, 40409, 24123, 32717, 28775, 51400, 36268, 17856, 31374, 52215, 23120, 30627]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 23885, 34409, 29331, 31759, 28068]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.19165258246480754
sparse_theta_sp: -0.8944804715975408
decorrelation: 0.01
fix: 1000000000
ext_decorr_good: 100000
num_topics: {'good': 15, 'bad': 3, 'not_good': 5, 'total_bad': 42}
17

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b7167b580>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f7b716b1550>}
Topic: 0. Top: [28172, 34364, 33123, 47238, 28629, 50442, 17856, 44121, 33036, 24278, 25342, 34095, 33176, 25025, 42030, 31298, 28701, 30429, 35185, 40736]
Topic: 1. Top: [19656, 21874, 33047, 32665, 31803, 26627, 42456, 32929, 52105, 36376, 47238, 33746, 27624, 32677, 31622, 31186, 26192, 27540, 27662, 32510]
Topic: 2. Top: [30791, 35538, 35657, 34729, 26809, 28068, 26165, 29592, 46583, 27086, 21123, 32665, 26567, 52456, 31747, 42166, 21394, 17905, 27334, 40521]
Topic: 3. Top: [30339, 32254, 33036, 37712, 28453, 34317, 29096, 37631, 45183, 30416, 30252, 20581, 30082, 32449, 33096, 28016, 30887, 33354, 30795, 52298]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 21347, 29096, 29237, 29453]
Topic: 5. Top: [33484, 43613, 38446, 20673, 28992, 21123, 26239, 27587, 44211, 32135, 36303, 35657, 21001, 27985, 34571, 30833, 27185, 30750, 46714, 32833]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 40999, 29237, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [47238, 33125, 33123, 29237, 29282, 30339, 28701, 34317, 26745, 33176, 31298, 28695, 34871, 33036, 33124, 32510, 30160, 29902, 52105, 30252]
Topic: 8. Top: [19828, 29237, 32510, 35023, 32678, 28884, 29282, 33036, 29559, 45841, 30887, 27187, 44259, 30152, 29085, 48622, 29116, 40820, 32939, 30160]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 27643, 33036, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [27030, 40295, 29282, 28016, 20164, 29939, 29259, 33380, 32241, 30806, 49904, 29888, 45841, 47035, 35227, 32510, 32413, 31768, 17194, 28026]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [49838, 28100, 34287, 26190, 28095, 29939, 37130, 32833, 30119, 40409, 24123, 32717, 28775, 51400, 36268, 17856, 31374, 52215, 23120, 30627]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 23885, 34409, 29331, 31759, 28068]
Topic: 0. Top: [28172, 34364, 33123, 47238, 28629, 50442, 17856, 44121, 33036, 24278, 25342, 34095, 33176, 25025, 42030, 31298, 28701, 30429, 35185, 40736]
Topic: 1. Top: [19656, 21874, 33047, 32665, 31803, 26627, 42456, 32929, 52105, 36376, 47238, 33746, 27624, 32677, 31622, 31186, 26192, 27540, 27662, 32510]
Topic: 2. Top: [30791, 35538, 35657, 34729, 26809, 28068, 26165, 29592, 46583, 27086, 21123, 32665, 26567, 52456, 31747, 42166, 21394, 17905, 27334, 40521]
Topic: 3. Top: [30339, 32254, 33036, 37712, 28453, 34317, 29096, 37631, 45183, 30416, 30252, 20581, 30082, 32449, 33096, 28016, 30887, 33354, 30795, 52298]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 21347, 29096, 29237, 29453]
Topic: 5. Top: [33484, 43613, 38446, 20673, 28992, 21123, 26239, 27587, 44211, 32135, 36303, 35657, 21001, 27985, 34571, 30833, 27185, 30750, 46714, 32833]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 40999, 29237, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [47238, 33125, 33123, 29237, 29282, 30339, 28701, 34317, 26745, 33176, 31298, 28695, 34871, 33036, 33124, 32510, 30160, 29902, 52105, 30252]
Topic: 8. Top: [19828, 29237, 32510, 35023, 32678, 28884, 29282, 33036, 29559, 45841, 30887, 27187, 44259, 30152, 29085, 48622, 29116, 40820, 32939, 30160]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 27643, 33036, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [27030, 40295, 29282, 28016, 20164, 29939, 29259, 33380, 32241, 30806, 49904, 29888, 45841, 47035, 35227, 32510, 32413, 31768, 17194, 28026]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [49838, 28100, 34287, 26190, 28095, 29939, 37130, 32833, 30119, 40409, 24123, 32717, 28775, 51400, 36268, 17856, 31374, 52215, 23120, 30627]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 23885, 34409, 29331, 31759, 28068]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.19165258246480754
sparse_theta_sp: -0.8944804715975408
decorrelation: 0.01
fix: 1000000000
ext_decorr_good: 100000
SUCCESS: less bad topics
num_topics: {'good': 15, 'bad': 1, 'not_good': 5, 'total_bad': 43}
18

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b897663a0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f7b8f774d00>}
Topic: 0. Top: [32833, 30791, 37130, 35416, 20528, 40029, 29939, 33826, 32665, 27185, 25945, 34531, 30597, 30627, 19656, 37692, 28999, 31192, 34170, 25220]
Topic: 1. Top: [21874, 19656, 33047, 29282, 29237, 26627, 32929, 42456, 32665, 26192, 35023, 29891, 32677, 31186, 28252, 28535, 36376, 32510, 39872, 33746]
Topic: 2. Top: [30791, 35538, 35657, 34729, 26809, 28068, 26165, 29592, 46583, 27086, 21123, 32665, 26567, 52456, 31747, 42166, 21394, 17905, 27334, 40521]
Topic: 3. Top: [30339, 32254, 33036, 37712, 28453, 34317, 29096, 37631, 45183, 30416, 30252, 20581, 30082, 32449, 33096, 28016, 30887, 33354, 30795, 52298]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 21347, 29096, 29237, 29453]
Topic: 5. Top: [33484, 43613, 38446, 20673, 28992, 21123, 26239, 27587, 44211, 32135, 36303, 35657, 21001, 27985, 34571, 30833, 27185, 30750, 46714, 32833]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 40999, 29237, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [47238, 33123, 30339, 33176, 31298, 29282, 33125, 30252, 52105, 29237, 33036, 34317, 48735, 44121, 29684, 29902, 31397, 28695, 17194, 17231]
Topic: 8. Top: [29237, 33125, 32510, 33036, 28701, 29282, 30339, 30160, 20164, 33124, 26745, 28695, 34317, 34871, 28995, 27136, 30152, 32678, 27970, 32939]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 27643, 33036, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [28172, 28629, 42030, 17856, 32833, 25025, 34095, 24278, 21580, 40736, 28701, 25342, 29272, 30429, 31133, 28585, 35416, 37265, 30152, 33826]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [49838, 28100, 34287, 26190, 28095, 29939, 37130, 32833, 30119, 40409, 24123, 32717, 28775, 51400, 36268, 17856, 31374, 52215, 23120, 30627]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 23885, 34409, 29331, 31759, 28068]
Topic: 0. Top: [32833, 30791, 37130, 35416, 20528, 40029, 29939, 33826, 32665, 27185, 25945, 34531, 30597, 30627, 19656, 37692, 28999, 31192, 34170, 25220]
Topic: 1. Top: [21874, 19656, 33047, 29282, 29237, 26627, 32929, 42456, 32665, 26192, 35023, 29891, 32677, 31186, 28252, 28535, 36376, 32510, 39872, 33746]
Topic: 2. Top: [30791, 35538, 35657, 34729, 26809, 28068, 26165, 29592, 46583, 27086, 21123, 32665, 26567, 52456, 31747, 42166, 21394, 17905, 27334, 40521]
Topic: 3. Top: [30339, 32254, 33036, 37712, 28453, 34317, 29096, 37631, 45183, 30416, 30252, 20581, 30082, 32449, 33096, 28016, 30887, 33354, 30795, 52298]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 21347, 29096, 29237, 29453]
Topic: 5. Top: [33484, 43613, 38446, 20673, 28992, 21123, 26239, 27587, 44211, 32135, 36303, 35657, 21001, 27985, 34571, 30833, 27185, 30750, 46714, 32833]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 40999, 29237, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [47238, 33123, 30339, 33176, 31298, 29282, 33125, 30252, 52105, 29237, 33036, 34317, 48735, 44121, 29684, 29902, 31397, 28695, 17194, 17231]
Topic: 8. Top: [29237, 33125, 32510, 33036, 28701, 29282, 30339, 30160, 20164, 33124, 26745, 28695, 34317, 34871, 28995, 27136, 30152, 32678, 27970, 32939]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 27643, 33036, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [28172, 28629, 42030, 17856, 32833, 25025, 34095, 24278, 21580, 40736, 28701, 25342, 29272, 30429, 31133, 28585, 35416, 37265, 30152, 33826]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [49838, 28100, 34287, 26190, 28095, 29939, 37130, 32833, 30119, 40409, 24123, 32717, 28775, 51400, 36268, 17856, 31374, 52215, 23120, 30627]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 23885, 34409, 29331, 31759, 28068]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.19165258246480754
sparse_theta_sp: -0.8944804715975408
decorrelation: 0.01
fix: 1000000000
ext_decorr_good: 100000
DOWNFALL: more bad topics...
num_topics: {'good': 15, 'bad': 2, 'not_good': 5, 'total_bad': 45}
19

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b89322f40>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f7b8eaa8f10>}
Topic: 0. Top: [32833, 30791, 35416, 40029, 37130, 33826, 29939, 20528, 19656, 30597, 32665, 34531, 25945, 28999, 33176, 28368, 37692, 27185, 30627, 33123]
Topic: 1. Top: [27030, 28016, 22209, 29282, 36383, 33123, 30656, 32241, 52105, 33176, 28465, 47035, 22725, 32510, 30806, 36585, 31298, 30444, 29845, 35121]
Topic: 2. Top: [30791, 35538, 35657, 34729, 26809, 28068, 26165, 29592, 46583, 27086, 21123, 32665, 26567, 52456, 31747, 42166, 21394, 17905, 27334, 40521]
Topic: 3. Top: [30339, 32254, 33036, 37712, 28453, 34317, 29096, 37631, 45183, 30416, 30252, 20581, 30082, 32449, 33096, 28016, 30887, 33354, 30795, 52298]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 21347, 29096, 29237, 29453]
Topic: 5. Top: [33484, 43613, 38446, 20673, 28992, 21123, 26239, 27587, 44211, 32135, 36303, 35657, 21001, 27985, 34571, 30833, 27185, 30750, 46714, 32833]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 40999, 29237, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [29282, 33125, 29237, 33036, 32510, 30339, 20164, 28701, 34871, 26745, 33124, 30160, 28695, 28995, 34317, 35023, 27136, 29784, 30152, 32939]
Topic: 8. Top: [28172, 34364, 28629, 40295, 34130, 25025, 35185, 38753, 34095, 42030, 40736, 24278, 31133, 30429, 30152, 50442, 29834, 25342, 26172, 28585]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 27643, 33036, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [47238, 29237, 33123, 30339, 33125, 31298, 34317, 33176, 30252, 29902, 52105, 19656, 29684, 28695, 48735, 32510, 29096, 29282, 17231, 30490]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [49838, 28100, 34287, 26190, 28095, 29939, 37130, 32833, 30119, 40409, 24123, 32717, 28775, 51400, 36268, 17856, 31374, 52215, 23120, 30627]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 23885, 34409, 29331, 31759, 28068]
Topic: 0. Top: [32833, 30791, 35416, 40029, 37130, 33826, 29939, 20528, 19656, 30597, 32665, 34531, 25945, 28999, 33176, 28368, 37692, 27185, 30627, 33123]
Topic: 1. Top: [27030, 28016, 22209, 29282, 36383, 33123, 30656, 32241, 52105, 33176, 28465, 47035, 22725, 32510, 30806, 36585, 31298, 30444, 29845, 35121]
Topic: 2. Top: [30791, 35538, 35657, 34729, 26809, 28068, 26165, 29592, 46583, 27086, 21123, 32665, 26567, 52456, 31747, 42166, 21394, 17905, 27334, 40521]
Topic: 3. Top: [30339, 32254, 33036, 37712, 28453, 34317, 29096, 37631, 45183, 30416, 30252, 20581, 30082, 32449, 33096, 28016, 30887, 33354, 30795, 52298]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 21347, 29096, 29237, 29453]
Topic: 5. Top: [33484, 43613, 38446, 20673, 28992, 21123, 26239, 27587, 44211, 32135, 36303, 35657, 21001, 27985, 34571, 30833, 27185, 30750, 46714, 32833]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 40999, 29237, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [29282, 33125, 29237, 33036, 32510, 30339, 20164, 28701, 34871, 26745, 33124, 30160, 28695, 28995, 34317, 35023, 27136, 29784, 30152, 32939]
Topic: 8. Top: [28172, 34364, 28629, 40295, 34130, 25025, 35185, 38753, 34095, 42030, 40736, 24278, 31133, 30429, 30152, 50442, 29834, 25342, 26172, 28585]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 27643, 33036, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [47238, 29237, 33123, 30339, 33125, 31298, 34317, 33176, 30252, 29902, 52105, 19656, 29684, 28695, 48735, 32510, 29096, 29282, 17231, 30490]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [49838, 28100, 34287, 26190, 28095, 29939, 37130, 32833, 30119, 40409, 24123, 32717, 28775, 51400, 36268, 17856, 31374, 52215, 23120, 30627]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 23885, 34409, 29331, 31759, 28068]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.19165258246480754
sparse_theta_sp: -0.8944804715975408
decorrelation: 0.01
fix: 1000000000
ext_decorr_good: 100000
num_topics: {'good': 15, 'bad': 2, 'not_good': 5, 'total_bad': 47}
(1, 1, 0)
0
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
Topic: 0. Top: [32833, 40029, 33826, 30791, 37692, 28368, 19656, 28999, 27300, 35416, 28775, 25945, 25220, 41831, 26306, 29939, 33036, 37130, 38446, 27264]
Topic: 1. Top: [36195, 42454, 30130, 34207, 27360, 30827, 32833, 24160, 32028, 31683, 47035, 48735, 40820, 27934, 33726, 29464, 28122, 36226, 29858, 38105]
Topic: 2. Top: [43613, 30791, 32833, 32665, 27086, 44211, 33123, 33484, 31997, 21123, 35416, 35657, 32135, 25289, 29331, 20673, 34170, 23885, 39872, 38446]
Topic: 3. Top: [30339, 28016, 47238, 29237, 33036, 30252, 29096, 27030, 47035, 30887, 34317, 32254, 29684, 31298, 31397, 17231, 30795, 37492, 37631, 48735]
Topic: 4. Top: [28172, 35842, 28465, 22422, 28629, 27624, 21650, 49838, 36585, 29272, 30656, 40295, 24278, 40736, 31622, 17856, 27066, 29834, 34095, 52105]
Topic: 5. Top: [29385, 32833, 32942, 28820, 36874, 29939, 50360, 46187, 31059, 24494, 44833, 37553, 28019, 35189, 27643, 25902, 28992, 39575, 35113, 23798]
Topic: 6. Top: [29453, 36383, 29116, 26627, 31186, 29237, 29282, 32833, 40999, 51040, 32510, 35708, 34014, 51902, 32678, 51496, 35189, 29096, 28406, 36928]
Topic: 7. Top: [28884, 35023, 33036, 20164, 29939, 27187, 27587, 51610, 30152, 24317, 29085, 28701, 33006, 37168, 36515, 27970, 38087, 33124, 21347, 32510]
Topic: 8. Top: [33123, 33125, 47238, 29282, 28701, 30339, 33036, 26745, 32510, 28695, 34317, 33176, 29237, 33124, 34871, 29902, 31298, 52105, 30160, 29728]
Topic: 9. Top: [32833, 34364, 33123, 33036, 42030, 25342, 50442, 25025, 44121, 31777, 35416, 18601, 40029, 46714, 33176, 46583, 19656, 27624, 31683, 38753]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [20528, 22254, 28068, 33484, 29939, 34170, 32677, 50360, 29328, 29998, 27185, 37083, 27787, 25911, 28992, 49264, 42166, 28193, 39945, 32833]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [28651, 30339, 34089, 37833, 33036, 39719, 29237, 25706, 27532, 30596, 30066, 29282, 43571, 32510, 24315, 17946, 34317, 26129, 30252, 29096]
Topic: 15. Top: [35331, 27540, 31186, 32665, 52105, 30331, 39921, 42456, 27624, 22209, 20197, 27307, 43613, 50360, 32929, 37263, 32028, 19656, 25859, 43025]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [49838, 37130, 28100, 34287, 29939, 32833, 26190, 28095, 24123, 30627, 30597, 51400, 34531, 28019, 32942, 30119, 40409, 32717, 31192, 36268]
Topic: 0. Top: [32833, 40029, 33826, 30791, 37692, 28368, 19656, 28999, 27300, 35416, 28775, 25945, 25220, 41831, 26306, 29939, 33036, 37130, 38446, 27264]
Topic: 1. Top: [36195, 42454, 30130, 34207, 27360, 30827, 32833, 24160, 32028, 31683, 47035, 48735, 40820, 27934, 33726, 29464, 28122, 36226, 29858, 38105]
Topic: 2. Top: [43613, 30791, 32833, 32665, 27086, 44211, 33123, 33484, 31997, 21123, 35416, 35657, 32135, 25289, 29331, 20673, 34170, 23885, 39872, 38446]
Topic: 3. Top: [30339, 28016, 47238, 29237, 33036, 30252, 29096, 27030, 47035, 30887, 34317, 32254, 29684, 31298, 31397, 17231, 30795, 37492, 37631, 48735]
Topic: 4. Top: [28172, 35842, 28465, 22422, 28629, 27624, 21650, 49838, 36585, 29272, 30656, 40295, 24278, 40736, 31622, 17856, 27066, 29834, 34095, 52105]
Topic: 5. Top: [29385, 32833, 32942, 28820, 36874, 29939, 50360, 46187, 31059, 24494, 44833, 37553, 28019, 35189, 27643, 25902, 28992, 39575, 35113, 23798]
Topic: 6. Top: [29453, 36383, 29116, 26627, 31186, 29237, 29282, 32833, 40999, 51040, 32510, 35708, 34014, 51902, 32678, 51496, 35189, 29096, 28406, 36928]
Topic: 7. Top: [28884, 35023, 33036, 20164, 29939, 27187, 27587, 51610, 30152, 24317, 29085, 28701, 33006, 37168, 36515, 27970, 38087, 33124, 21347, 32510]
Topic: 8. Top: [33123, 33125, 47238, 29282, 28701, 30339, 33036, 26745, 32510, 28695, 34317, 33176, 29237, 33124, 34871, 29902, 31298, 52105, 30160, 29728]
Topic: 9. Top: [32833, 34364, 33123, 33036, 42030, 25342, 50442, 25025, 44121, 31777, 35416, 18601, 40029, 46714, 33176, 46583, 19656, 27624, 31683, 38753]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [20528, 22254, 28068, 33484, 29939, 34170, 32677, 50360, 29328, 29998, 27185, 37083, 27787, 25911, 28992, 49264, 42166, 28193, 39945, 32833]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [28651, 30339, 34089, 37833, 33036, 39719, 29237, 25706, 27532, 30596, 30066, 29282, 43571, 32510, 24315, 17946, 34317, 26129, 30252, 29096]
Topic: 15. Top: [35331, 27540, 31186, 32665, 52105, 30331, 39921, 42456, 27624, 22209, 20197, 27307, 43613, 50360, 32929, 37263, 32028, 19656, 25859, 43025]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [49838, 37130, 28100, 34287, 29939, 32833, 26190, 28095, 24123, 30627, 30597, 51400, 34531, 28019, 32942, 30119, 40409, 32717, 31192, 36268]
num_topics: {'good': 6, 'bad': 2, 'not_good': 14, 'total_bad': 2}
1

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7ad5138070>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f7b8eaa8ca0>}
Topic: 0. Top: [29282, 33125, 32510, 33036, 30339, 28701, 28695, 34317, 34871, 20164, 26745, 33123, 17194, 29237, 30160, 33124, 47238, 33176, 33731, 31298]
Topic: 1. Top: [43613, 37130, 33484, 31997, 30627, 22254, 34170, 20673, 27185, 20528, 28068, 28992, 32677, 32665, 29939, 33826, 25289, 28100, 32833, 42166]
Topic: 2. Top: [39575, 28884, 50360, 38245, 34409, 20370, 31059, 27187, 31759, 25911, 24203, 29068, 43613, 30152, 32931, 24494, 35331, 29085, 31147, 37868]
Topic: 3. Top: [49838, 32833, 34287, 40029, 33123, 33036, 17856, 19656, 28172, 42030, 26190, 29939, 28100, 34364, 45727, 22422, 28095, 33176, 30444, 21580]
Topic: 4. Top: [52105, 19656, 42456, 32665, 21874, 33047, 30339, 27624, 33176, 28465, 47238, 29237, 29096, 27540, 29592, 35331, 31186, 36376, 32929, 27187]
Topic: 5. Top: [36383, 29453, 31186, 26627, 51040, 29116, 40999, 32833, 51902, 29237, 34014, 33799, 36928, 35708, 35750, 51496, 35189, 43613, 21129, 30130]
Topic: 6. Top: [32833, 30791, 21123, 35657, 27086, 43613, 35538, 32135, 32665, 33123, 35416, 26809, 28193, 36303, 28068, 22254, 32760, 29592, 29998, 19656]
Topic: 7. Top: [29237, 43571, 29096, 33125, 30596, 29902, 33036, 40395, 47035, 46434, 29597, 32510, 32711, 28701, 27970, 30339, 35057, 30876, 33124, 29939]
Topic: 8. Top: [32833, 30791, 38446, 40029, 25945, 44211, 33484, 35416, 20528, 32665, 46714, 29939, 26306, 19656, 37692, 39872, 25220, 45727, 33036, 29033]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 28992, 42639, 33036, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [46583, 21394, 52456, 33761, 24452, 29205, 29393, 27624, 43332, 40157, 24625, 23739, 35494, 45519, 48872, 41048, 24932, 17398, 19900, 23664]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 36195, 32833, 30827, 34207, 31683, 24317, 27360, 24160, 24193, 30331, 33036, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [28651, 34089, 37833, 30339, 33036, 25706, 39719, 27532, 24315, 26129, 17946, 30374, 30066, 30252, 31484, 34317, 29453, 25420, 32510, 21347]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [47238, 30339, 33123, 33036, 31298, 30252, 34317, 33176, 29237, 29684, 44121, 48735, 33124, 31397, 26745, 29096, 17231, 28172, 33125, 28695]
Topic: 0. Top: [29282, 33125, 32510, 33036, 30339, 28701, 28695, 34317, 34871, 20164, 26745, 33123, 17194, 29237, 30160, 33124, 47238, 33176, 33731, 31298]
Topic: 1. Top: [43613, 37130, 33484, 31997, 30627, 22254, 34170, 20673, 27185, 20528, 28068, 28992, 32677, 32665, 29939, 33826, 25289, 28100, 32833, 42166]
Topic: 2. Top: [39575, 28884, 50360, 38245, 34409, 20370, 31059, 27187, 31759, 25911, 24203, 29068, 43613, 30152, 32931, 24494, 35331, 29085, 31147, 37868]
Topic: 3. Top: [49838, 32833, 34287, 40029, 33123, 33036, 17856, 19656, 28172, 42030, 26190, 29939, 28100, 34364, 45727, 22422, 28095, 33176, 30444, 21580]
Topic: 4. Top: [52105, 19656, 42456, 32665, 21874, 33047, 30339, 27624, 33176, 28465, 47238, 29237, 29096, 27540, 29592, 35331, 31186, 36376, 32929, 27187]
Topic: 5. Top: [36383, 29453, 31186, 26627, 51040, 29116, 40999, 32833, 51902, 29237, 34014, 33799, 36928, 35708, 35750, 51496, 35189, 43613, 21129, 30130]
Topic: 6. Top: [32833, 30791, 21123, 35657, 27086, 43613, 35538, 32135, 32665, 33123, 35416, 26809, 28193, 36303, 28068, 22254, 32760, 29592, 29998, 19656]
Topic: 7. Top: [29237, 43571, 29096, 33125, 30596, 29902, 33036, 40395, 47035, 46434, 29597, 32510, 32711, 28701, 27970, 30339, 35057, 30876, 33124, 29939]
Topic: 8. Top: [32833, 30791, 38446, 40029, 25945, 44211, 33484, 35416, 20528, 32665, 46714, 29939, 26306, 19656, 37692, 39872, 25220, 45727, 33036, 29033]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 28992, 42639, 33036, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [46583, 21394, 52456, 33761, 24452, 29205, 29393, 27624, 43332, 40157, 24625, 23739, 35494, 45519, 48872, 41048, 24932, 17398, 19900, 23664]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 36195, 32833, 30827, 34207, 31683, 24317, 27360, 24160, 24193, 30331, 33036, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [28651, 34089, 37833, 30339, 33036, 25706, 39719, 27532, 24315, 26129, 17946, 30374, 30066, 30252, 31484, 34317, 29453, 25420, 32510, 21347]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [47238, 30339, 33123, 33036, 31298, 30252, 34317, 33176, 29237, 29684, 44121, 48735, 33124, 31397, 26745, 29096, 17231, 28172, 33125, 28695]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.0684473508802884
sparse_theta_sp: -0.319457311284836
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000
SUCCESS: more good topics
DOWNFALL: more bad topics...
num_topics: {'good': 8, 'bad': 3, 'not_good': 12, 'total_bad': 5}
2

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8e83bdc0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f7b7167adc0>}
Topic: 0. Top: [49838, 28100, 26190, 32833, 29939, 28095, 32717, 40409, 37130, 51400, 28775, 42030, 25538, 28992, 19656, 40029, 36268, 29486, 30444, 28540]
Topic: 1. Top: [28172, 32833, 34364, 28629, 42030, 40295, 27624, 17856, 49838, 33036, 34095, 34130, 25025, 28701, 24278, 30152, 25342, 21580, 40736, 38753]
Topic: 2. Top: [36383, 51040, 40999, 29453, 51902, 32833, 27030, 51496, 28016, 22209, 34014, 49904, 30130, 29282, 31622, 29888, 26362, 30656, 21129, 51331]
Topic: 3. Top: [37833, 28651, 30596, 29453, 17946, 39719, 33036, 19828, 29259, 31484, 30339, 17905, 30066, 21347, 33480, 25706, 45841, 27985, 27315, 24315]
Topic: 4. Top: [30791, 32833, 44211, 21123, 35657, 32665, 32135, 27086, 43613, 35538, 35416, 38446, 25945, 40029, 39872, 19656, 34729, 26239, 33123, 26567]
Topic: 5. Top: [28651, 34089, 27532, 30339, 26129, 33036, 30252, 25706, 37833, 39719, 29096, 34507, 52298, 32510, 34317, 30876, 43184, 43571, 24315, 19933]
Topic: 6. Top: [43613, 33484, 31997, 22254, 39575, 25289, 50360, 26648, 20528, 32833, 29939, 20370, 38245, 32665, 34170, 27185, 28068, 49264, 20673, 24203]
Topic: 7. Top: [37692, 34287, 32833, 28019, 30627, 17856, 26306, 28368, 25466, 24123, 28999, 32942, 29939, 39661, 46951, 31192, 35416, 27264, 20528, 25911]
Topic: 8. Top: [29237, 29282, 33125, 32510, 20164, 28701, 30339, 34871, 28695, 33036, 35023, 29784, 28995, 33124, 29902, 30160, 33731, 29116, 27136, 19656]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 28992, 42639, 33036, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [31186, 29116, 27540, 43613, 35750, 26627, 29453, 39921, 20197, 35331, 31620, 27624, 35708, 35189, 36985, 27307, 26993, 43025, 42456, 52105]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 36195, 32833, 30827, 34207, 31683, 24317, 27360, 24160, 24193, 30331, 33036, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [47238, 30339, 33123, 33036, 34317, 31298, 30252, 33176, 29237, 29684, 26745, 33125, 33124, 44121, 29096, 48735, 31397, 17231, 29282, 52105]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [37130, 33826, 35842, 27624, 32833, 30597, 30791, 40029, 34531, 27066, 21650, 50488, 22422, 19656, 27300, 30119, 38446, 37974, 39575, 28068]
Topic: 0. Top: [49838, 28100, 26190, 32833, 29939, 28095, 32717, 40409, 37130, 51400, 28775, 42030, 25538, 28992, 19656, 40029, 36268, 29486, 30444, 28540]
Topic: 1. Top: [28172, 32833, 34364, 28629, 42030, 40295, 27624, 17856, 49838, 33036, 34095, 34130, 25025, 28701, 24278, 30152, 25342, 21580, 40736, 38753]
Topic: 2. Top: [36383, 51040, 40999, 29453, 51902, 32833, 27030, 51496, 28016, 22209, 34014, 49904, 30130, 29282, 31622, 29888, 26362, 30656, 21129, 51331]
Topic: 3. Top: [37833, 28651, 30596, 29453, 17946, 39719, 33036, 19828, 29259, 31484, 30339, 17905, 30066, 21347, 33480, 25706, 45841, 27985, 27315, 24315]
Topic: 4. Top: [30791, 32833, 44211, 21123, 35657, 32665, 32135, 27086, 43613, 35538, 35416, 38446, 25945, 40029, 39872, 19656, 34729, 26239, 33123, 26567]
Topic: 5. Top: [28651, 34089, 27532, 30339, 26129, 33036, 30252, 25706, 37833, 39719, 29096, 34507, 52298, 32510, 34317, 30876, 43184, 43571, 24315, 19933]
Topic: 6. Top: [43613, 33484, 31997, 22254, 39575, 25289, 50360, 26648, 20528, 32833, 29939, 20370, 38245, 32665, 34170, 27185, 28068, 49264, 20673, 24203]
Topic: 7. Top: [37692, 34287, 32833, 28019, 30627, 17856, 26306, 28368, 25466, 24123, 28999, 32942, 29939, 39661, 46951, 31192, 35416, 27264, 20528, 25911]
Topic: 8. Top: [29237, 29282, 33125, 32510, 20164, 28701, 30339, 34871, 28695, 33036, 35023, 29784, 28995, 33124, 29902, 30160, 33731, 29116, 27136, 19656]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 28992, 42639, 33036, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [31186, 29116, 27540, 43613, 35750, 26627, 29453, 39921, 20197, 35331, 31620, 27624, 35708, 35189, 36985, 27307, 26993, 43025, 42456, 52105]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 36195, 32833, 30827, 34207, 31683, 24317, 27360, 24160, 24193, 30331, 33036, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [47238, 30339, 33123, 33036, 34317, 31298, 30252, 33176, 29237, 29684, 26745, 33125, 33124, 44121, 29096, 48735, 31397, 17231, 29282, 52105]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [37130, 33826, 35842, 27624, 32833, 30597, 30791, 40029, 34531, 27066, 21650, 50488, 22422, 19656, 27300, 30119, 38446, 37974, 39575, 28068]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.07985524269366981
sparse_theta_sp: -0.37270019649897534
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000
SUCCESS: less bad topics
num_topics: {'good': 8, 'bad': 2, 'not_good': 12, 'total_bad': 7}
3

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8e83beb0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f7b89547100>}
Topic: 0. Top: [29282, 29237, 32510, 33125, 30339, 33036, 30160, 29116, 28701, 28695, 26745, 20164, 33123, 28995, 47238, 31298, 17194, 32678, 32833, 33176]
Topic: 1. Top: [28172, 27624, 28629, 40295, 35842, 42030, 34095, 25025, 21394, 32833, 26483, 40736, 25342, 27066, 31133, 29272, 17905, 21650, 46583, 30429]
Topic: 2. Top: [42456, 35331, 36226, 28252, 40820, 30444, 27934, 19933, 47035, 22772, 31228, 30339, 27307, 31264, 26095, 52105, 45080, 26584, 28068, 33096]
Topic: 3. Top: [28651, 30339, 33036, 34089, 37833, 29237, 39719, 29282, 25706, 33125, 34317, 27532, 30066, 32510, 43571, 30252, 29096, 24315, 33124, 34871]
Topic: 4. Top: [30791, 32833, 21123, 44211, 35657, 32135, 35538, 32665, 25945, 27086, 40029, 35416, 25943, 26567, 36303, 34729, 27587, 29592, 33707, 26809]
Topic: 5. Top: [47238, 33123, 52105, 19656, 33176, 21874, 31298, 28695, 32510, 44121, 28701, 46780, 34364, 29902, 33125, 33036, 33047, 34803, 33731, 30444]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 36928, 27540, 33799, 40999, 26072, 26993, 21129, 20197, 35189, 29237, 31620]
Topic: 7. Top: [49838, 37130, 32833, 28100, 29939, 34287, 33826, 40029, 37692, 28019, 30597, 28999, 19656, 26190, 34531, 30627, 28095, 31192, 35416, 17856]
Topic: 8. Top: [30339, 47238, 30252, 30887, 29096, 34317, 29684, 33036, 47035, 29237, 31298, 32254, 30795, 28016, 37492, 37631, 17231, 31397, 28453, 17400]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 28992, 42639, 33036, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [21347, 31484, 35023, 19828, 27315, 20164, 48622, 29559, 30596, 32833, 40395, 27587, 29939, 32436, 24317, 32939, 28701, 28884, 33006, 28748]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 36195, 32833, 30827, 34207, 31683, 24317, 27360, 24160, 24193, 30331, 33036, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [33484, 32665, 20528, 32833, 27185, 42166, 20673, 30791, 28068, 28992, 29939, 43613, 34170, 38446, 22254, 30627, 39872, 26239, 26306, 39945]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 29908, 28884, 27086, 34170, 23885, 34409, 31759, 29331, 29939]
Topic: 0. Top: [29282, 29237, 32510, 33125, 30339, 33036, 30160, 29116, 28701, 28695, 26745, 20164, 33123, 28995, 47238, 31298, 17194, 32678, 32833, 33176]
Topic: 1. Top: [28172, 27624, 28629, 40295, 35842, 42030, 34095, 25025, 21394, 32833, 26483, 40736, 25342, 27066, 31133, 29272, 17905, 21650, 46583, 30429]
Topic: 2. Top: [42456, 35331, 36226, 28252, 40820, 30444, 27934, 19933, 47035, 22772, 31228, 30339, 27307, 31264, 26095, 52105, 45080, 26584, 28068, 33096]
Topic: 3. Top: [28651, 30339, 33036, 34089, 37833, 29237, 39719, 29282, 25706, 33125, 34317, 27532, 30066, 32510, 43571, 30252, 29096, 24315, 33124, 34871]
Topic: 4. Top: [30791, 32833, 21123, 44211, 35657, 32135, 35538, 32665, 25945, 27086, 40029, 35416, 25943, 26567, 36303, 34729, 27587, 29592, 33707, 26809]
Topic: 5. Top: [47238, 33123, 52105, 19656, 33176, 21874, 31298, 28695, 32510, 44121, 28701, 46780, 34364, 29902, 33125, 33036, 33047, 34803, 33731, 30444]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 36928, 27540, 33799, 40999, 26072, 26993, 21129, 20197, 35189, 29237, 31620]
Topic: 7. Top: [49838, 37130, 32833, 28100, 29939, 34287, 33826, 40029, 37692, 28019, 30597, 28999, 19656, 26190, 34531, 30627, 28095, 31192, 35416, 17856]
Topic: 8. Top: [30339, 47238, 30252, 30887, 29096, 34317, 29684, 33036, 47035, 29237, 31298, 32254, 30795, 28016, 37492, 37631, 17231, 31397, 28453, 17400]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 28992, 42639, 33036, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [21347, 31484, 35023, 19828, 27315, 20164, 48622, 29559, 30596, 32833, 40395, 27587, 29939, 32436, 24317, 32939, 28701, 28884, 33006, 28748]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 36195, 32833, 30827, 34207, 31683, 24317, 27360, 24160, 24193, 30331, 33036, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [33484, 32665, 20528, 32833, 27185, 42166, 20673, 30791, 28068, 28992, 29939, 43613, 34170, 38446, 22254, 30627, 39872, 26239, 26306, 39945]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 29908, 28884, 27086, 34170, 23885, 34409, 31759, 29331, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.07985524269366981
sparse_theta_sp: -0.37270019649897534
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000
SUCCESS: more good topics
num_topics: {'good': 10, 'bad': 2, 'not_good': 10, 'total_bad': 9}
4

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8e966640>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f7b89466040>}
Topic: 0. Top: [28651, 29237, 30339, 39719, 33036, 33125, 37833, 32510, 43571, 29282, 29096, 34317, 30596, 27970, 45841, 35023, 34871, 30374, 29259, 33124]
Topic: 1. Top: [30339, 47238, 30252, 33036, 29237, 31298, 34317, 28016, 29684, 29096, 48735, 33176, 17231, 33123, 30887, 31397, 44121, 30795, 29902, 27030]
Topic: 2. Top: [49838, 28100, 34287, 28095, 29939, 26190, 24123, 37130, 28019, 40409, 32833, 51400, 30119, 36268, 30627, 23120, 31964, 28992, 25538, 29972]
Topic: 3. Top: [30791, 32833, 33484, 32665, 43613, 27185, 44211, 38446, 20528, 35416, 25945, 20673, 34170, 28992, 42166, 29939, 40029, 26466, 39872, 26239]
Topic: 4. Top: [28172, 37130, 32833, 33826, 35842, 27624, 22422, 30597, 37692, 40029, 21650, 19656, 34531, 27066, 27300, 50488, 29939, 45727, 28368, 25911]
Topic: 5. Top: [32833, 21123, 35538, 30791, 35657, 25220, 19656, 32135, 25025, 37974, 46714, 31374, 18601, 41831, 47079, 27624, 41106, 40029, 33036, 46583]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 36928, 27540, 33799, 40999, 26072, 26993, 21129, 20197, 35189, 29237, 31620]
Topic: 7. Top: [29282, 33123, 28701, 33125, 32510, 33036, 26745, 28695, 28995, 29237, 33176, 47238, 34871, 33124, 30160, 34317, 20164, 29728, 17194, 31298]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 25706, 37833, 29453, 34507, 52298, 27315, 24315, 43184, 17905, 30340, 30655, 29331, 28049, 51694, 19933]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 28992, 42639, 33036, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [27587, 22099, 33707, 36303, 29592, 25943, 35657, 21123, 28068, 35331, 19828, 31228, 40521, 22107, 29791, 44826, 29834, 32665, 29559, 17398]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 36195, 32833, 30827, 34207, 31683, 24317, 27360, 24160, 24193, 30331, 33036, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [19656, 32665, 33047, 26627, 21874, 52105, 42456, 31803, 32677, 26192, 32929, 31622, 31186, 27540, 35331, 36585, 27624, 28252, 33746, 27662]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 29908, 28884, 27086, 34170, 23885, 34409, 31759, 29331, 29939]
Topic: 0. Top: [28651, 29237, 30339, 39719, 33036, 33125, 37833, 32510, 43571, 29282, 29096, 34317, 30596, 27970, 45841, 35023, 34871, 30374, 29259, 33124]
Topic: 1. Top: [30339, 47238, 30252, 33036, 29237, 31298, 34317, 28016, 29684, 29096, 48735, 33176, 17231, 33123, 30887, 31397, 44121, 30795, 29902, 27030]
Topic: 2. Top: [49838, 28100, 34287, 28095, 29939, 26190, 24123, 37130, 28019, 40409, 32833, 51400, 30119, 36268, 30627, 23120, 31964, 28992, 25538, 29972]
Topic: 3. Top: [30791, 32833, 33484, 32665, 43613, 27185, 44211, 38446, 20528, 35416, 25945, 20673, 34170, 28992, 42166, 29939, 40029, 26466, 39872, 26239]
Topic: 4. Top: [28172, 37130, 32833, 33826, 35842, 27624, 22422, 30597, 37692, 40029, 21650, 19656, 34531, 27066, 27300, 50488, 29939, 45727, 28368, 25911]
Topic: 5. Top: [32833, 21123, 35538, 30791, 35657, 25220, 19656, 32135, 25025, 37974, 46714, 31374, 18601, 41831, 47079, 27624, 41106, 40029, 33036, 46583]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 36928, 27540, 33799, 40999, 26072, 26993, 21129, 20197, 35189, 29237, 31620]
Topic: 7. Top: [29282, 33123, 28701, 33125, 32510, 33036, 26745, 28695, 28995, 29237, 33176, 47238, 34871, 33124, 30160, 34317, 20164, 29728, 17194, 31298]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 25706, 37833, 29453, 34507, 52298, 27315, 24315, 43184, 17905, 30340, 30655, 29331, 28049, 51694, 19933]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 28992, 42639, 33036, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [27587, 22099, 33707, 36303, 29592, 25943, 35657, 21123, 28068, 35331, 19828, 31228, 40521, 22107, 29791, 44826, 29834, 32665, 29559, 17398]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 36195, 32833, 30827, 34207, 31683, 24317, 27360, 24160, 24193, 30331, 33036, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [19656, 32665, 33047, 26627, 21874, 52105, 42456, 31803, 32677, 26192, 32929, 31622, 31186, 27540, 35331, 36585, 27624, 28252, 33746, 27662]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 29908, 28884, 27086, 34170, 23885, 34409, 31759, 29331, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.09582629123240377
sparse_theta_sp: -0.4472402357987704
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000
SUCCESS: more good topics
num_topics: {'good': 13, 'bad': 2, 'not_good': 7, 'total_bad': 11}
5

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b713d78b0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f7ad4551a90>}
Topic: 0. Top: [28172, 33123, 32833, 42030, 28629, 21580, 44121, 33176, 27030, 25342, 33036, 52105, 28465, 45727, 19656, 30444, 28995, 40029, 30429, 34095]
Topic: 1. Top: [30791, 32833, 32665, 40029, 35416, 43613, 19656, 44211, 38446, 25945, 33826, 35657, 32135, 30597, 21123, 37130, 29939, 34170, 34531, 25220]
Topic: 2. Top: [49838, 28100, 34287, 28095, 29939, 26190, 24123, 37130, 28019, 40409, 32833, 51400, 30119, 36268, 30627, 23120, 31964, 28992, 25538, 29972]
Topic: 3. Top: [28651, 29237, 33036, 39719, 37833, 30339, 30596, 43571, 35023, 17946, 30374, 21347, 29784, 46434, 27970, 31484, 25420, 29096, 32939, 48622]
Topic: 4. Top: [29754, 21394, 46583, 37692, 17905, 33761, 21753, 52456, 32529, 29275, 25647, 18981, 28521, 27185, 29205, 27417, 27624, 26072, 25158, 23739]
Topic: 5. Top: [29282, 33125, 28701, 32510, 29237, 28695, 20164, 30160, 30339, 34317, 33124, 34871, 28995, 33731, 33176, 39719, 32678, 26745, 47238, 17194]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 36928, 27540, 33799, 40999, 26072, 26993, 21129, 20197, 35189, 29237, 31620]
Topic: 7. Top: [30339, 47238, 29237, 30252, 33036, 29096, 34317, 31298, 29684, 30887, 28016, 29902, 33123, 47035, 17231, 32254, 19656, 33176, 30795, 48735]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 25706, 37833, 29453, 34507, 52298, 27315, 24315, 43184, 17905, 30340, 30655, 29331, 28049, 51694, 19933]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 28992, 42639, 33036, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [27587, 22099, 33707, 36303, 29592, 25943, 35657, 21123, 28068, 35331, 19828, 31228, 40521, 22107, 29791, 44826, 29834, 32665, 29559, 17398]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 36195, 32833, 30827, 34207, 31683, 24317, 27360, 24160, 24193, 30331, 33036, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [33484, 20528, 27185, 28068, 35842, 28992, 32833, 20673, 42166, 26239, 27066, 50488, 25911, 29834, 21650, 39945, 25025, 30627, 51997, 27624]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 29908, 28884, 27086, 34170, 23885, 34409, 31759, 29331, 29939]
Topic: 0. Top: [28172, 33123, 32833, 42030, 28629, 21580, 44121, 33176, 27030, 25342, 33036, 52105, 28465, 45727, 19656, 30444, 28995, 40029, 30429, 34095]
Topic: 1. Top: [30791, 32833, 32665, 40029, 35416, 43613, 19656, 44211, 38446, 25945, 33826, 35657, 32135, 30597, 21123, 37130, 29939, 34170, 34531, 25220]
Topic: 2. Top: [49838, 28100, 34287, 28095, 29939, 26190, 24123, 37130, 28019, 40409, 32833, 51400, 30119, 36268, 30627, 23120, 31964, 28992, 25538, 29972]
Topic: 3. Top: [28651, 29237, 33036, 39719, 37833, 30339, 30596, 43571, 35023, 17946, 30374, 21347, 29784, 46434, 27970, 31484, 25420, 29096, 32939, 48622]
Topic: 4. Top: [29754, 21394, 46583, 37692, 17905, 33761, 21753, 52456, 32529, 29275, 25647, 18981, 28521, 27185, 29205, 27417, 27624, 26072, 25158, 23739]
Topic: 5. Top: [29282, 33125, 28701, 32510, 29237, 28695, 20164, 30160, 30339, 34317, 33124, 34871, 28995, 33731, 33176, 39719, 32678, 26745, 47238, 17194]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 36928, 27540, 33799, 40999, 26072, 26993, 21129, 20197, 35189, 29237, 31620]
Topic: 7. Top: [30339, 47238, 29237, 30252, 33036, 29096, 34317, 31298, 29684, 30887, 28016, 29902, 33123, 47035, 17231, 32254, 19656, 33176, 30795, 48735]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 25706, 37833, 29453, 34507, 52298, 27315, 24315, 43184, 17905, 30340, 30655, 29331, 28049, 51694, 19933]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 28992, 42639, 33036, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [27587, 22099, 33707, 36303, 29592, 25943, 35657, 21123, 28068, 35331, 19828, 31228, 40521, 22107, 29791, 44826, 29834, 32665, 29559, 17398]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 36195, 32833, 30827, 34207, 31683, 24317, 27360, 24160, 24193, 30331, 33036, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [33484, 20528, 27185, 28068, 35842, 28992, 32833, 20673, 42166, 26239, 27066, 50488, 25911, 29834, 21650, 39945, 25025, 30627, 51997, 27624]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 29908, 28884, 27086, 34170, 23885, 34409, 31759, 29331, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1368947017605768
sparse_theta_sp: -0.638914622569672
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000
num_topics: {'good': 13, 'bad': 2, 'not_good': 7, 'total_bad': 13}
6

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8f7c3dc0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f7b8ed301f0>}
Topic: 0. Top: [32833, 30791, 35416, 40029, 44211, 25945, 35657, 32665, 38446, 30597, 19656, 21123, 37130, 34531, 35538, 27086, 32135, 46714, 33826, 26306]
Topic: 1. Top: [29237, 29282, 33125, 47238, 33123, 32510, 52105, 28701, 33176, 30339, 28695, 29902, 28995, 31298, 34871, 19656, 26745, 30160, 34317, 27970]
Topic: 2. Top: [49838, 28100, 34287, 28095, 29939, 26190, 24123, 37130, 28019, 40409, 32833, 51400, 30119, 36268, 30627, 23120, 31964, 28992, 25538, 29972]
Topic: 3. Top: [28651, 39719, 30339, 29237, 33036, 43571, 37833, 30596, 45841, 32510, 35023, 33125, 29096, 25420, 30152, 20164, 29259, 21347, 29282, 32939]
Topic: 4. Top: [33484, 27185, 20528, 37692, 32665, 20673, 42166, 28992, 43613, 26239, 28068, 34170, 30627, 38446, 32833, 29939, 31502, 39945, 28019, 25911]
Topic: 5. Top: [28172, 34364, 42030, 28629, 32833, 18601, 17856, 25025, 29272, 34095, 25342, 40736, 28585, 21580, 35185, 24278, 30429, 25143, 31374, 40295]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 36928, 27540, 33799, 40999, 26072, 26993, 21129, 20197, 35189, 29237, 31620]
Topic: 7. Top: [30791, 41831, 25220, 37974, 39872, 43613, 33826, 52456, 46583, 27624, 32665, 32275, 32135, 29567, 21394, 29766, 33761, 25098, 27567, 39716]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 25706, 37833, 29453, 34507, 52298, 27315, 24315, 43184, 17905, 30340, 30655, 29331, 28049, 51694, 19933]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 28992, 42639, 33036, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [27587, 22099, 33707, 36303, 29592, 25943, 35657, 21123, 28068, 35331, 19828, 31228, 40521, 22107, 29791, 44826, 29834, 32665, 29559, 17398]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 36195, 32833, 30827, 34207, 31683, 24317, 27360, 24160, 24193, 30331, 33036, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [30339, 47238, 30252, 28016, 33036, 29096, 30887, 29684, 34317, 27030, 47035, 29237, 31298, 32254, 31397, 30795, 37631, 17231, 37492, 48735]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 29908, 28884, 27086, 34170, 23885, 34409, 31759, 29331, 29939]
Topic: 0. Top: [32833, 30791, 35416, 40029, 44211, 25945, 35657, 32665, 38446, 30597, 19656, 21123, 37130, 34531, 35538, 27086, 32135, 46714, 33826, 26306]
Topic: 1. Top: [29237, 29282, 33125, 47238, 33123, 32510, 52105, 28701, 33176, 30339, 28695, 29902, 28995, 31298, 34871, 19656, 26745, 30160, 34317, 27970]
Topic: 2. Top: [49838, 28100, 34287, 28095, 29939, 26190, 24123, 37130, 28019, 40409, 32833, 51400, 30119, 36268, 30627, 23120, 31964, 28992, 25538, 29972]
Topic: 3. Top: [28651, 39719, 30339, 29237, 33036, 43571, 37833, 30596, 45841, 32510, 35023, 33125, 29096, 25420, 30152, 20164, 29259, 21347, 29282, 32939]
Topic: 4. Top: [33484, 27185, 20528, 37692, 32665, 20673, 42166, 28992, 43613, 26239, 28068, 34170, 30627, 38446, 32833, 29939, 31502, 39945, 28019, 25911]
Topic: 5. Top: [28172, 34364, 42030, 28629, 32833, 18601, 17856, 25025, 29272, 34095, 25342, 40736, 28585, 21580, 35185, 24278, 30429, 25143, 31374, 40295]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 36928, 27540, 33799, 40999, 26072, 26993, 21129, 20197, 35189, 29237, 31620]
Topic: 7. Top: [30791, 41831, 25220, 37974, 39872, 43613, 33826, 52456, 46583, 27624, 32665, 32275, 32135, 29567, 21394, 29766, 33761, 25098, 27567, 39716]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 25706, 37833, 29453, 34507, 52298, 27315, 24315, 43184, 17905, 30340, 30655, 29331, 28049, 51694, 19933]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 28992, 42639, 33036, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [27587, 22099, 33707, 36303, 29592, 25943, 35657, 21123, 28068, 35331, 19828, 31228, 40521, 22107, 29791, 44826, 29834, 32665, 29559, 17398]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 36195, 32833, 30827, 34207, 31683, 24317, 27360, 24160, 24193, 30331, 33036, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [30339, 47238, 30252, 28016, 33036, 29096, 30887, 29684, 34317, 27030, 47035, 29237, 31298, 32254, 31397, 30795, 37631, 17231, 37492, 48735]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 29908, 28884, 27086, 34170, 23885, 34409, 31759, 29331, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1368947017605768
sparse_theta_sp: -0.638914622569672
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000
SUCCESS: less bad topics
num_topics: {'good': 13, 'bad': 1, 'not_good': 7, 'total_bad': 14}
7

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b892390a0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f7b8946c1c0>}
Topic: 0. Top: [30791, 32833, 35657, 21123, 32665, 35538, 44211, 32135, 27086, 25220, 34170, 26567, 35416, 34729, 26809, 26864, 46583, 35604, 40029, 25945]
Topic: 1. Top: [36376, 32665, 32929, 42456, 31803, 26192, 33746, 33047, 48811, 26627, 21874, 28535, 25540, 28252, 29891, 45935, 26885, 27540, 27738, 27662]
Topic: 2. Top: [49838, 28100, 34287, 28095, 29939, 26190, 24123, 37130, 28019, 40409, 32833, 51400, 30119, 36268, 30627, 23120, 31964, 28992, 25538, 29972]
Topic: 3. Top: [33484, 27185, 28992, 46714, 42166, 25025, 20528, 32833, 28068, 25911, 34713, 18601, 47079, 26616, 39945, 26809, 51997, 25465, 31374, 29939]
Topic: 4. Top: [30339, 29237, 47238, 33125, 33036, 29282, 34317, 30252, 31298, 32510, 33123, 29096, 33176, 33124, 29684, 29902, 34871, 30160, 28695, 26745]
Topic: 5. Top: [32833, 43613, 38446, 30791, 37130, 32665, 37692, 33826, 33484, 30597, 20528, 34531, 40029, 27300, 30627, 35416, 25945, 20673, 26306, 26239]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 36928, 27540, 33799, 40999, 26072, 26993, 21129, 20197, 35189, 29237, 31620]
Topic: 7. Top: [28651, 39719, 30596, 37833, 35023, 45841, 19828, 30152, 21347, 29259, 25420, 17946, 44259, 30374, 48622, 27970, 43571, 31484, 46434, 20164]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 25706, 37833, 29453, 34507, 52298, 27315, 24315, 43184, 17905, 30340, 30655, 29331, 28049, 51694, 19933]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 28992, 42639, 33036, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [27587, 22099, 33707, 36303, 29592, 25943, 35657, 21123, 28068, 35331, 19828, 31228, 40521, 22107, 29791, 44826, 29834, 32665, 29559, 17398]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 36195, 32833, 30827, 34207, 31683, 24317, 27360, 24160, 24193, 30331, 33036, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [28172, 34364, 27624, 28629, 35842, 17856, 34095, 24278, 30656, 22422, 42030, 40736, 49838, 21580, 35185, 38753, 34130, 30429, 21650, 31133]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 29908, 28884, 27086, 34170, 23885, 34409, 31759, 29331, 29939]
Topic: 0. Top: [30791, 32833, 35657, 21123, 32665, 35538, 44211, 32135, 27086, 25220, 34170, 26567, 35416, 34729, 26809, 26864, 46583, 35604, 40029, 25945]
Topic: 1. Top: [36376, 32665, 32929, 42456, 31803, 26192, 33746, 33047, 48811, 26627, 21874, 28535, 25540, 28252, 29891, 45935, 26885, 27540, 27738, 27662]
Topic: 2. Top: [49838, 28100, 34287, 28095, 29939, 26190, 24123, 37130, 28019, 40409, 32833, 51400, 30119, 36268, 30627, 23120, 31964, 28992, 25538, 29972]
Topic: 3. Top: [33484, 27185, 28992, 46714, 42166, 25025, 20528, 32833, 28068, 25911, 34713, 18601, 47079, 26616, 39945, 26809, 51997, 25465, 31374, 29939]
Topic: 4. Top: [30339, 29237, 47238, 33125, 33036, 29282, 34317, 30252, 31298, 32510, 33123, 29096, 33176, 33124, 29684, 29902, 34871, 30160, 28695, 26745]
Topic: 5. Top: [32833, 43613, 38446, 30791, 37130, 32665, 37692, 33826, 33484, 30597, 20528, 34531, 40029, 27300, 30627, 35416, 25945, 20673, 26306, 26239]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 36928, 27540, 33799, 40999, 26072, 26993, 21129, 20197, 35189, 29237, 31620]
Topic: 7. Top: [28651, 39719, 30596, 37833, 35023, 45841, 19828, 30152, 21347, 29259, 25420, 17946, 44259, 30374, 48622, 27970, 43571, 31484, 46434, 20164]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 25706, 37833, 29453, 34507, 52298, 27315, 24315, 43184, 17905, 30340, 30655, 29331, 28049, 51694, 19933]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 28992, 42639, 33036, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [27587, 22099, 33707, 36303, 29592, 25943, 35657, 21123, 28068, 35331, 19828, 31228, 40521, 22107, 29791, 44826, 29834, 32665, 29559, 17398]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 36195, 32833, 30827, 34207, 31683, 24317, 27360, 24160, 24193, 30331, 33036, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [28172, 34364, 27624, 28629, 35842, 17856, 34095, 24278, 30656, 22422, 42030, 40736, 49838, 21580, 35185, 38753, 34130, 30429, 21650, 31133]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 29908, 28884, 27086, 34170, 23885, 34409, 31759, 29331, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1368947017605768
sparse_theta_sp: -0.638914622569672
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000
SUCCESS: more good topics
num_topics: {'good': 14, 'bad': 1, 'not_good': 6, 'total_bad': 15}
8

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8f8bc2e0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f7b8f7dcfd0>}
Topic: 0. Top: [29237, 30339, 29282, 33125, 47238, 33036, 34317, 32510, 33123, 33124, 34871, 29096, 30252, 29902, 33176, 26745, 28701, 28695, 31298, 29684]
Topic: 1. Top: [36376, 32665, 32929, 42456, 31803, 26192, 33746, 33047, 48811, 26627, 21874, 28535, 25540, 28252, 29891, 45935, 26885, 27540, 27738, 27662]
Topic: 2. Top: [49838, 28100, 34287, 28095, 29939, 26190, 24123, 37130, 28019, 40409, 32833, 51400, 30119, 36268, 30627, 23120, 31964, 28992, 25538, 29972]
Topic: 3. Top: [30887, 32254, 30795, 37492, 28172, 37631, 30444, 27794, 28016, 47238, 44121, 49897, 31397, 31298, 30252, 30100, 28453, 29684, 37712, 30339]
Topic: 4. Top: [32833, 40029, 37130, 33826, 19656, 30597, 34531, 30791, 37692, 35416, 27300, 28368, 29939, 41831, 26306, 25911, 25220, 45727, 35842, 42030]
Topic: 5. Top: [28651, 37833, 30596, 17946, 31484, 21347, 33480, 43571, 32573, 25706, 29205, 39719, 40395, 30374, 27315, 32436, 46434, 24315, 36226, 29597]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 36928, 27540, 33799, 40999, 26072, 26993, 21129, 20197, 35189, 29237, 31620]
Topic: 7. Top: [30791, 33484, 32833, 32665, 43613, 27185, 44211, 38446, 20528, 35657, 20673, 32135, 34170, 21123, 28992, 26809, 42166, 35538, 35416, 26466]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 25706, 37833, 29453, 34507, 52298, 27315, 24315, 43184, 17905, 30340, 30655, 29331, 28049, 51694, 19933]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 28992, 42639, 33036, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [27587, 22099, 33707, 36303, 29592, 25943, 35657, 21123, 28068, 35331, 19828, 31228, 40521, 22107, 29791, 44826, 29834, 32665, 29559, 17398]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 36195, 32833, 30827, 34207, 31683, 24317, 27360, 24160, 24193, 30331, 33036, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [35023, 30152, 45841, 20164, 29259, 32678, 19828, 44259, 39719, 33036, 38536, 19330, 29939, 25420, 32833, 27970, 50581, 48622, 27754, 32939]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 29908, 28884, 27086, 34170, 23885, 34409, 31759, 29331, 29939]
Topic: 0. Top: [29237, 30339, 29282, 33125, 47238, 33036, 34317, 32510, 33123, 33124, 34871, 29096, 30252, 29902, 33176, 26745, 28701, 28695, 31298, 29684]
Topic: 1. Top: [36376, 32665, 32929, 42456, 31803, 26192, 33746, 33047, 48811, 26627, 21874, 28535, 25540, 28252, 29891, 45935, 26885, 27540, 27738, 27662]
Topic: 2. Top: [49838, 28100, 34287, 28095, 29939, 26190, 24123, 37130, 28019, 40409, 32833, 51400, 30119, 36268, 30627, 23120, 31964, 28992, 25538, 29972]
Topic: 3. Top: [30887, 32254, 30795, 37492, 28172, 37631, 30444, 27794, 28016, 47238, 44121, 49897, 31397, 31298, 30252, 30100, 28453, 29684, 37712, 30339]
Topic: 4. Top: [32833, 40029, 37130, 33826, 19656, 30597, 34531, 30791, 37692, 35416, 27300, 28368, 29939, 41831, 26306, 25911, 25220, 45727, 35842, 42030]
Topic: 5. Top: [28651, 37833, 30596, 17946, 31484, 21347, 33480, 43571, 32573, 25706, 29205, 39719, 40395, 30374, 27315, 32436, 46434, 24315, 36226, 29597]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 36928, 27540, 33799, 40999, 26072, 26993, 21129, 20197, 35189, 29237, 31620]
Topic: 7. Top: [30791, 33484, 32833, 32665, 43613, 27185, 44211, 38446, 20528, 35657, 20673, 32135, 34170, 21123, 28992, 26809, 42166, 35538, 35416, 26466]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 25706, 37833, 29453, 34507, 52298, 27315, 24315, 43184, 17905, 30340, 30655, 29331, 28049, 51694, 19933]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 28992, 42639, 33036, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [27587, 22099, 33707, 36303, 29592, 25943, 35657, 21123, 28068, 35331, 19828, 31228, 40521, 22107, 29791, 44826, 29834, 32665, 29559, 17398]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 36195, 32833, 30827, 34207, 31683, 24317, 27360, 24160, 24193, 30331, 33036, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [35023, 30152, 45841, 20164, 29259, 32678, 19828, 44259, 39719, 33036, 38536, 19330, 29939, 25420, 32833, 27970, 50581, 48622, 27754, 32939]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 29908, 28884, 27086, 34170, 23885, 34409, 31759, 29331, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.15971048538733962
sparse_theta_sp: -0.7454003929979507
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000
SUCCESS: more good topics
num_topics: {'good': 15, 'bad': 1, 'not_good': 5, 'total_bad': 16}
9

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8ee1c040>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f7b8e916310>}
Topic: 0. Top: [30791, 32833, 32665, 35416, 37692, 35657, 20528, 44211, 21123, 30597, 32135, 35538, 28068, 37130, 34170, 39872, 29939, 27086, 34531, 19656]
Topic: 1. Top: [36376, 32665, 32929, 42456, 31803, 26192, 33746, 33047, 48811, 26627, 21874, 28535, 25540, 28252, 29891, 45935, 26885, 27540, 27738, 27662]
Topic: 2. Top: [49838, 28100, 34287, 28095, 29939, 26190, 24123, 37130, 28019, 40409, 32833, 51400, 30119, 36268, 30627, 23120, 31964, 28992, 25538, 29972]
Topic: 3. Top: [29096, 30252, 29684, 31298, 34317, 30160, 39719, 17231, 29902, 47035, 28016, 35023, 33124, 34871, 45841, 26027, 29784, 26000, 17853, 27970]
Topic: 4. Top: [28172, 32254, 28629, 30887, 40736, 28453, 37712, 37631, 37492, 34012, 30656, 31133, 30429, 22028, 30795, 20581, 49897, 45080, 30100, 37017]
Topic: 5. Top: [28651, 37833, 30596, 17946, 31484, 21347, 33480, 43571, 32573, 25706, 29205, 39719, 40395, 30374, 27315, 32436, 46434, 24315, 36226, 29597]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 36928, 27540, 33799, 40999, 26072, 26993, 21129, 20197, 35189, 29237, 31620]
Topic: 7. Top: [33484, 27185, 28992, 20528, 20673, 42166, 32665, 39945, 25911, 28146, 28068, 34571, 46714, 29939, 22254, 34130, 26809, 27787, 26466, 42660]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 25706, 37833, 29453, 34507, 52298, 27315, 24315, 43184, 17905, 30340, 30655, 29331, 28049, 51694, 19933]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 28992, 42639, 33036, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [27587, 22099, 33707, 36303, 29592, 25943, 35657, 21123, 28068, 35331, 19828, 31228, 40521, 22107, 29791, 44826, 29834, 32665, 29559, 17398]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 36195, 32833, 30827, 34207, 31683, 24317, 27360, 24160, 24193, 30331, 33036, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [32833, 43613, 38446, 33826, 33484, 26239, 25220, 25945, 18601, 26306, 25025, 47079, 46714, 44211, 35416, 31502, 28019, 31192, 34713, 30791]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 29908, 28884, 27086, 34170, 23885, 34409, 31759, 29331, 29939]
Topic: 0. Top: [30791, 32833, 32665, 35416, 37692, 35657, 20528, 44211, 21123, 30597, 32135, 35538, 28068, 37130, 34170, 39872, 29939, 27086, 34531, 19656]
Topic: 1. Top: [36376, 32665, 32929, 42456, 31803, 26192, 33746, 33047, 48811, 26627, 21874, 28535, 25540, 28252, 29891, 45935, 26885, 27540, 27738, 27662]
Topic: 2. Top: [49838, 28100, 34287, 28095, 29939, 26190, 24123, 37130, 28019, 40409, 32833, 51400, 30119, 36268, 30627, 23120, 31964, 28992, 25538, 29972]
Topic: 3. Top: [29096, 30252, 29684, 31298, 34317, 30160, 39719, 17231, 29902, 47035, 28016, 35023, 33124, 34871, 45841, 26027, 29784, 26000, 17853, 27970]
Topic: 4. Top: [28172, 32254, 28629, 30887, 40736, 28453, 37712, 37631, 37492, 34012, 30656, 31133, 30429, 22028, 30795, 20581, 49897, 45080, 30100, 37017]
Topic: 5. Top: [28651, 37833, 30596, 17946, 31484, 21347, 33480, 43571, 32573, 25706, 29205, 39719, 40395, 30374, 27315, 32436, 46434, 24315, 36226, 29597]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 36928, 27540, 33799, 40999, 26072, 26993, 21129, 20197, 35189, 29237, 31620]
Topic: 7. Top: [33484, 27185, 28992, 20528, 20673, 42166, 32665, 39945, 25911, 28146, 28068, 34571, 46714, 29939, 22254, 34130, 26809, 27787, 26466, 42660]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 25706, 37833, 29453, 34507, 52298, 27315, 24315, 43184, 17905, 30340, 30655, 29331, 28049, 51694, 19933]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 28992, 42639, 33036, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [27587, 22099, 33707, 36303, 29592, 25943, 35657, 21123, 28068, 35331, 19828, 31228, 40521, 22107, 29791, 44826, 29834, 32665, 29559, 17398]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 36195, 32833, 30827, 34207, 31683, 24317, 27360, 24160, 24193, 30331, 33036, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [32833, 43613, 38446, 33826, 33484, 26239, 25220, 25945, 18601, 26306, 25025, 47079, 46714, 44211, 35416, 31502, 28019, 31192, 34713, 30791]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 29908, 28884, 27086, 34170, 23885, 34409, 31759, 29331, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.19165258246480754
sparse_theta_sp: -0.8944804715975408
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000
SUCCESS: more good topics
SUCCESS: less bad topics
SUCCESS: no bad topics!
num_topics: {'good': 16, 'bad': 0, 'not_good': 4, 'total_bad': 16}
10

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8f774ee0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f7b8fb32be0>}
Topic: 0. Top: [33484, 27185, 20673, 20528, 43613, 28992, 32665, 26239, 42166, 38446, 31502, 44211, 26809, 22254, 26466, 34170, 28019, 21001, 28068, 28146]
Topic: 1. Top: [36376, 32665, 32929, 42456, 31803, 26192, 33746, 33047, 48811, 26627, 21874, 28535, 25540, 28252, 29891, 45935, 26885, 27540, 27738, 27662]
Topic: 2. Top: [49838, 28100, 34287, 28095, 29939, 26190, 24123, 37130, 28019, 40409, 32833, 51400, 30119, 36268, 30627, 23120, 31964, 28992, 25538, 29972]
Topic: 3. Top: [21123, 32833, 35657, 32135, 39872, 46714, 44211, 26864, 35604, 25025, 26809, 34713, 34729, 27724, 30791, 31747, 27334, 32275, 25514, 30750]
Topic: 4. Top: [28172, 32254, 28629, 30887, 40736, 28453, 37712, 37631, 37492, 34012, 30656, 31133, 30429, 22028, 30795, 20581, 49897, 45080, 30100, 37017]
Topic: 5. Top: [28651, 37833, 30596, 17946, 31484, 21347, 33480, 43571, 32573, 25706, 29205, 39719, 40395, 30374, 27315, 32436, 46434, 24315, 36226, 29597]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 36928, 27540, 33799, 40999, 26072, 26993, 21129, 20197, 35189, 29237, 31620]
Topic: 7. Top: [30339, 29237, 33036, 33125, 34317, 32510, 29096, 33124, 30252, 31298, 34871, 30160, 28695, 29684, 33176, 20164, 29902, 29784, 39719, 26745]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 25706, 37833, 29453, 34507, 52298, 27315, 24315, 43184, 17905, 30340, 30655, 29331, 28049, 51694, 19933]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 28992, 42639, 33036, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [27587, 22099, 33707, 36303, 29592, 25943, 35657, 21123, 28068, 35331, 19828, 31228, 40521, 22107, 29791, 44826, 29834, 32665, 29559, 17398]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 36195, 32833, 30827, 34207, 31683, 24317, 27360, 24160, 24193, 30331, 33036, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [30791, 32833, 32665, 37130, 33826, 35416, 37692, 38446, 40029, 25945, 30597, 29939, 19656, 34531, 20528, 27300, 25220, 43613, 34170, 26306]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 29908, 28884, 27086, 34170, 23885, 34409, 31759, 29331, 29939]
Topic: 0. Top: [33484, 27185, 20673, 20528, 43613, 28992, 32665, 26239, 42166, 38446, 31502, 44211, 26809, 22254, 26466, 34170, 28019, 21001, 28068, 28146]
Topic: 1. Top: [36376, 32665, 32929, 42456, 31803, 26192, 33746, 33047, 48811, 26627, 21874, 28535, 25540, 28252, 29891, 45935, 26885, 27540, 27738, 27662]
Topic: 2. Top: [49838, 28100, 34287, 28095, 29939, 26190, 24123, 37130, 28019, 40409, 32833, 51400, 30119, 36268, 30627, 23120, 31964, 28992, 25538, 29972]
Topic: 3. Top: [21123, 32833, 35657, 32135, 39872, 46714, 44211, 26864, 35604, 25025, 26809, 34713, 34729, 27724, 30791, 31747, 27334, 32275, 25514, 30750]
Topic: 4. Top: [28172, 32254, 28629, 30887, 40736, 28453, 37712, 37631, 37492, 34012, 30656, 31133, 30429, 22028, 30795, 20581, 49897, 45080, 30100, 37017]
Topic: 5. Top: [28651, 37833, 30596, 17946, 31484, 21347, 33480, 43571, 32573, 25706, 29205, 39719, 40395, 30374, 27315, 32436, 46434, 24315, 36226, 29597]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 36928, 27540, 33799, 40999, 26072, 26993, 21129, 20197, 35189, 29237, 31620]
Topic: 7. Top: [30339, 29237, 33036, 33125, 34317, 32510, 29096, 33124, 30252, 31298, 34871, 30160, 28695, 29684, 33176, 20164, 29902, 29784, 39719, 26745]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 25706, 37833, 29453, 34507, 52298, 27315, 24315, 43184, 17905, 30340, 30655, 29331, 28049, 51694, 19933]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 28992, 42639, 33036, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [27587, 22099, 33707, 36303, 29592, 25943, 35657, 21123, 28068, 35331, 19828, 31228, 40521, 22107, 29791, 44826, 29834, 32665, 29559, 17398]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 36195, 32833, 30827, 34207, 31683, 24317, 27360, 24160, 24193, 30331, 33036, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [30791, 32833, 32665, 37130, 33826, 35416, 37692, 38446, 40029, 25945, 30597, 29939, 19656, 34531, 20528, 27300, 25220, 43613, 34170, 26306]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 29908, 28884, 27086, 34170, 23885, 34409, 31759, 29331, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.23956572808100943
sparse_theta_sp: -1.118100589496926
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000
SUCCESS: more good topics
DOWNFALL: more bad topics...
num_topics: {'good': 18, 'bad': 1, 'not_good': 2, 'total_bad': 17}
11

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b890b7b20>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f7b8efbed60>}
Topic: 0. Top: [33484, 27185, 20673, 20528, 43613, 28992, 32665, 26239, 42166, 38446, 31502, 44211, 26809, 22254, 26466, 34170, 28019, 21001, 28068, 28146]
Topic: 1. Top: [36376, 32665, 32929, 42456, 31803, 26192, 33746, 33047, 48811, 26627, 21874, 28535, 25540, 28252, 29891, 45935, 26885, 27540, 27738, 27662]
Topic: 2. Top: [49838, 28100, 34287, 28095, 29939, 26190, 24123, 37130, 28019, 40409, 32833, 51400, 30119, 36268, 30627, 23120, 31964, 28992, 25538, 29972]
Topic: 3. Top: [21123, 32833, 35657, 32135, 39872, 46714, 44211, 26864, 35604, 25025, 26809, 34713, 34729, 27724, 30791, 31747, 27334, 32275, 25514, 30750]
Topic: 4. Top: [28172, 32254, 28629, 30887, 40736, 28453, 37712, 37631, 37492, 34012, 30656, 31133, 30429, 22028, 30795, 20581, 49897, 45080, 30100, 37017]
Topic: 5. Top: [28651, 37833, 30596, 17946, 31484, 21347, 33480, 43571, 32573, 25706, 29205, 39719, 40395, 30374, 27315, 32436, 46434, 24315, 36226, 29597]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 36928, 27540, 33799, 40999, 26072, 26993, 21129, 20197, 35189, 29237, 31620]
Topic: 7. Top: [37692, 37130, 30597, 27300, 34531, 35842, 26306, 41831, 30627, 37974, 27066, 41785, 50488, 30791, 38446, 46951, 20528, 21650, 22980, 33826]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 25706, 37833, 29453, 34507, 52298, 27315, 24315, 43184, 17905, 30340, 30655, 29331, 28049, 51694, 19933]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 28992, 42639, 33036, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [27587, 22099, 33707, 36303, 29592, 25943, 35657, 21123, 28068, 35331, 19828, 31228, 40521, 22107, 29791, 44826, 29834, 32665, 29559, 17398]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 36195, 32833, 30827, 34207, 31683, 24317, 27360, 24160, 24193, 30331, 33036, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [30791, 25945, 35538, 32665, 43613, 25220, 33826, 26567, 38446, 25943, 32531, 35657, 44211, 25607, 28999, 34170, 31192, 16898, 21390, 30161]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 29908, 28884, 27086, 34170, 23885, 34409, 31759, 29331, 29939]
Topic: 0. Top: [33484, 27185, 20673, 20528, 43613, 28992, 32665, 26239, 42166, 38446, 31502, 44211, 26809, 22254, 26466, 34170, 28019, 21001, 28068, 28146]
Topic: 1. Top: [36376, 32665, 32929, 42456, 31803, 26192, 33746, 33047, 48811, 26627, 21874, 28535, 25540, 28252, 29891, 45935, 26885, 27540, 27738, 27662]
Topic: 2. Top: [49838, 28100, 34287, 28095, 29939, 26190, 24123, 37130, 28019, 40409, 32833, 51400, 30119, 36268, 30627, 23120, 31964, 28992, 25538, 29972]
Topic: 3. Top: [21123, 32833, 35657, 32135, 39872, 46714, 44211, 26864, 35604, 25025, 26809, 34713, 34729, 27724, 30791, 31747, 27334, 32275, 25514, 30750]
Topic: 4. Top: [28172, 32254, 28629, 30887, 40736, 28453, 37712, 37631, 37492, 34012, 30656, 31133, 30429, 22028, 30795, 20581, 49897, 45080, 30100, 37017]
Topic: 5. Top: [28651, 37833, 30596, 17946, 31484, 21347, 33480, 43571, 32573, 25706, 29205, 39719, 40395, 30374, 27315, 32436, 46434, 24315, 36226, 29597]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 36928, 27540, 33799, 40999, 26072, 26993, 21129, 20197, 35189, 29237, 31620]
Topic: 7. Top: [37692, 37130, 30597, 27300, 34531, 35842, 26306, 41831, 30627, 37974, 27066, 41785, 50488, 30791, 38446, 46951, 20528, 21650, 22980, 33826]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 25706, 37833, 29453, 34507, 52298, 27315, 24315, 43184, 17905, 30340, 30655, 29331, 28049, 51694, 19933]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 28992, 42639, 33036, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [27587, 22099, 33707, 36303, 29592, 25943, 35657, 21123, 28068, 35331, 19828, 31228, 40521, 22107, 29791, 44826, 29834, 32665, 29559, 17398]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 36195, 32833, 30827, 34207, 31683, 24317, 27360, 24160, 24193, 30331, 33036, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [30791, 25945, 35538, 32665, 43613, 25220, 33826, 26567, 38446, 25943, 32531, 35657, 44211, 25607, 28999, 34170, 31192, 16898, 21390, 30161]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 29908, 28884, 27086, 34170, 23885, 34409, 31759, 29331, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.47913145616201885
sparse_theta_sp: -2.236201178993852
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000
SUCCESS: more good topics
SUCCESS: less bad topics
SUCCESS: no bad topics!
num_topics: {'good': 19, 'bad': 0, 'not_good': 1, 'total_bad': 17}
12

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8b95cdf0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f7b71745310>}
Topic: 0. Top: [33484, 27185, 20673, 20528, 43613, 28992, 32665, 26239, 42166, 38446, 31502, 44211, 26809, 22254, 26466, 34170, 28019, 21001, 28068, 28146]
Topic: 1. Top: [36376, 32665, 32929, 42456, 31803, 26192, 33746, 33047, 48811, 26627, 21874, 28535, 25540, 28252, 29891, 45935, 26885, 27540, 27738, 27662]
Topic: 2. Top: [49838, 28100, 34287, 28095, 29939, 26190, 24123, 37130, 28019, 40409, 32833, 51400, 30119, 36268, 30627, 23120, 31964, 28992, 25538, 29972]
Topic: 3. Top: [21123, 32833, 35657, 32135, 39872, 46714, 44211, 26864, 35604, 25025, 26809, 34713, 34729, 27724, 30791, 31747, 27334, 32275, 25514, 30750]
Topic: 4. Top: [28172, 32254, 28629, 30887, 40736, 28453, 37712, 37631, 37492, 34012, 30656, 31133, 30429, 22028, 30795, 20581, 49897, 45080, 30100, 37017]
Topic: 5. Top: [28651, 37833, 30596, 17946, 31484, 21347, 33480, 43571, 32573, 25706, 29205, 39719, 40395, 30374, 27315, 32436, 46434, 24315, 36226, 29597]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 36928, 27540, 33799, 40999, 26072, 26993, 21129, 20197, 35189, 29237, 31620]
Topic: 7. Top: [30339, 47238, 33036, 34317, 33125, 29096, 29282, 30252, 32510, 31298, 33123, 29684, 33176, 34871, 28695, 29902, 33124, 26027, 30160, 29784]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 25706, 37833, 29453, 34507, 52298, 27315, 24315, 43184, 17905, 30340, 30655, 29331, 28049, 51694, 19933]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 28992, 42639, 33036, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [27587, 22099, 33707, 36303, 29592, 25943, 35657, 21123, 28068, 35331, 19828, 31228, 40521, 22107, 29791, 44826, 29834, 32665, 29559, 17398]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 36195, 32833, 30827, 34207, 31683, 24317, 27360, 24160, 24193, 30331, 33036, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [30791, 25945, 35538, 32665, 43613, 25220, 33826, 26567, 38446, 25943, 32531, 35657, 44211, 25607, 28999, 34170, 31192, 16898, 21390, 30161]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 29908, 28884, 27086, 34170, 23885, 34409, 31759, 29331, 29939]
Topic: 0. Top: [33484, 27185, 20673, 20528, 43613, 28992, 32665, 26239, 42166, 38446, 31502, 44211, 26809, 22254, 26466, 34170, 28019, 21001, 28068, 28146]
Topic: 1. Top: [36376, 32665, 32929, 42456, 31803, 26192, 33746, 33047, 48811, 26627, 21874, 28535, 25540, 28252, 29891, 45935, 26885, 27540, 27738, 27662]
Topic: 2. Top: [49838, 28100, 34287, 28095, 29939, 26190, 24123, 37130, 28019, 40409, 32833, 51400, 30119, 36268, 30627, 23120, 31964, 28992, 25538, 29972]
Topic: 3. Top: [21123, 32833, 35657, 32135, 39872, 46714, 44211, 26864, 35604, 25025, 26809, 34713, 34729, 27724, 30791, 31747, 27334, 32275, 25514, 30750]
Topic: 4. Top: [28172, 32254, 28629, 30887, 40736, 28453, 37712, 37631, 37492, 34012, 30656, 31133, 30429, 22028, 30795, 20581, 49897, 45080, 30100, 37017]
Topic: 5. Top: [28651, 37833, 30596, 17946, 31484, 21347, 33480, 43571, 32573, 25706, 29205, 39719, 40395, 30374, 27315, 32436, 46434, 24315, 36226, 29597]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 36928, 27540, 33799, 40999, 26072, 26993, 21129, 20197, 35189, 29237, 31620]
Topic: 7. Top: [30339, 47238, 33036, 34317, 33125, 29096, 29282, 30252, 32510, 31298, 33123, 29684, 33176, 34871, 28695, 29902, 33124, 26027, 30160, 29784]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 25706, 37833, 29453, 34507, 52298, 27315, 24315, 43184, 17905, 30340, 30655, 29331, 28049, 51694, 19933]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 28992, 42639, 33036, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [27587, 22099, 33707, 36303, 29592, 25943, 35657, 21123, 28068, 35331, 19828, 31228, 40521, 22107, 29791, 44826, 29834, 32665, 29559, 17398]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 36195, 32833, 30827, 34207, 31683, 24317, 27360, 24160, 24193, 30331, 33036, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [30791, 25945, 35538, 32665, 43613, 25220, 33826, 26567, 38446, 25943, 32531, 35657, 44211, 25607, 28999, 34170, 31192, 16898, 21390, 30161]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 29908, 28884, 27086, 34170, 23885, 34409, 31759, 29331, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.9582629123240377
sparse_theta_sp: -4.472402357987704
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000
DOWNFALL: more bad topics...
num_topics: {'good': 19, 'bad': 1, 'not_good': 1, 'total_bad': 18}
13

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b89766160>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f7b8faf1c70>}
Topic: 0. Top: [33484, 27185, 20673, 20528, 43613, 28992, 32665, 26239, 42166, 38446, 31502, 44211, 26809, 22254, 26466, 34170, 28019, 21001, 28068, 28146]
Topic: 1. Top: [36376, 32665, 32929, 42456, 31803, 26192, 33746, 33047, 48811, 26627, 21874, 28535, 25540, 28252, 29891, 45935, 26885, 27540, 27738, 27662]
Topic: 2. Top: [49838, 28100, 34287, 28095, 29939, 26190, 24123, 37130, 28019, 40409, 32833, 51400, 30119, 36268, 30627, 23120, 31964, 28992, 25538, 29972]
Topic: 3. Top: [21123, 32833, 35657, 32135, 39872, 46714, 44211, 26864, 35604, 25025, 26809, 34713, 34729, 27724, 30791, 31747, 27334, 32275, 25514, 30750]
Topic: 4. Top: [28172, 32254, 28629, 30887, 40736, 28453, 37712, 37631, 37492, 34012, 30656, 31133, 30429, 22028, 30795, 20581, 49897, 45080, 30100, 37017]
Topic: 5. Top: [28651, 37833, 30596, 17946, 31484, 21347, 33480, 43571, 32573, 25706, 29205, 39719, 40395, 30374, 27315, 32436, 46434, 24315, 36226, 29597]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 36928, 27540, 33799, 40999, 26072, 26993, 21129, 20197, 35189, 29237, 31620]
Topic: 7. Top: [30339, 29237, 47238, 33036, 33125, 34317, 29282, 32510, 29096, 30252, 33123, 31298, 33176, 29684, 34871, 33124, 29902, 28695, 30160, 28701]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 25706, 37833, 29453, 34507, 52298, 27315, 24315, 43184, 17905, 30340, 30655, 29331, 28049, 51694, 19933]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 28992, 42639, 33036, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [27587, 22099, 33707, 36303, 29592, 25943, 35657, 21123, 28068, 35331, 19828, 31228, 40521, 22107, 29791, 44826, 29834, 32665, 29559, 17398]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 36195, 32833, 30827, 34207, 31683, 24317, 27360, 24160, 24193, 30331, 33036, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [30791, 25945, 35538, 32665, 43613, 25220, 33826, 26567, 38446, 25943, 32531, 35657, 44211, 25607, 28999, 34170, 31192, 16898, 21390, 30161]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 29908, 28884, 27086, 34170, 23885, 34409, 31759, 29331, 29939]
Topic: 0. Top: [33484, 27185, 20673, 20528, 43613, 28992, 32665, 26239, 42166, 38446, 31502, 44211, 26809, 22254, 26466, 34170, 28019, 21001, 28068, 28146]
Topic: 1. Top: [36376, 32665, 32929, 42456, 31803, 26192, 33746, 33047, 48811, 26627, 21874, 28535, 25540, 28252, 29891, 45935, 26885, 27540, 27738, 27662]
Topic: 2. Top: [49838, 28100, 34287, 28095, 29939, 26190, 24123, 37130, 28019, 40409, 32833, 51400, 30119, 36268, 30627, 23120, 31964, 28992, 25538, 29972]
Topic: 3. Top: [21123, 32833, 35657, 32135, 39872, 46714, 44211, 26864, 35604, 25025, 26809, 34713, 34729, 27724, 30791, 31747, 27334, 32275, 25514, 30750]
Topic: 4. Top: [28172, 32254, 28629, 30887, 40736, 28453, 37712, 37631, 37492, 34012, 30656, 31133, 30429, 22028, 30795, 20581, 49897, 45080, 30100, 37017]
Topic: 5. Top: [28651, 37833, 30596, 17946, 31484, 21347, 33480, 43571, 32573, 25706, 29205, 39719, 40395, 30374, 27315, 32436, 46434, 24315, 36226, 29597]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 36928, 27540, 33799, 40999, 26072, 26993, 21129, 20197, 35189, 29237, 31620]
Topic: 7. Top: [30339, 29237, 47238, 33036, 33125, 34317, 29282, 32510, 29096, 30252, 33123, 31298, 33176, 29684, 34871, 33124, 29902, 28695, 30160, 28701]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 25706, 37833, 29453, 34507, 52298, 27315, 24315, 43184, 17905, 30340, 30655, 29331, 28049, 51694, 19933]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 28992, 42639, 33036, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [27587, 22099, 33707, 36303, 29592, 25943, 35657, 21123, 28068, 35331, 19828, 31228, 40521, 22107, 29791, 44826, 29834, 32665, 29559, 17398]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 36195, 32833, 30827, 34207, 31683, 24317, 27360, 24160, 24193, 30331, 33036, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [30791, 25945, 35538, 32665, 43613, 25220, 33826, 26567, 38446, 25943, 32531, 35657, 44211, 25607, 28999, 34170, 31192, 16898, 21390, 30161]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 29908, 28884, 27086, 34170, 23885, 34409, 31759, 29331, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.9582629123240377
sparse_theta_sp: -4.472402357987704
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000
num_topics: {'good': 19, 'bad': 1, 'not_good': 1, 'total_bad': 19}
14

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8907f070>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f7b892149d0>}
Topic: 0. Top: [33484, 27185, 20673, 20528, 43613, 28992, 32665, 26239, 42166, 38446, 31502, 44211, 26809, 22254, 26466, 34170, 28019, 21001, 28068, 28146]
Topic: 1. Top: [36376, 32665, 32929, 42456, 31803, 26192, 33746, 33047, 48811, 26627, 21874, 28535, 25540, 28252, 29891, 45935, 26885, 27540, 27738, 27662]
Topic: 2. Top: [49838, 28100, 34287, 28095, 29939, 26190, 24123, 37130, 28019, 40409, 32833, 51400, 30119, 36268, 30627, 23120, 31964, 28992, 25538, 29972]
Topic: 3. Top: [21123, 32833, 35657, 32135, 39872, 46714, 44211, 26864, 35604, 25025, 26809, 34713, 34729, 27724, 30791, 31747, 27334, 32275, 25514, 30750]
Topic: 4. Top: [28172, 32254, 28629, 30887, 40736, 28453, 37712, 37631, 37492, 34012, 30656, 31133, 30429, 22028, 30795, 20581, 49897, 45080, 30100, 37017]
Topic: 5. Top: [28651, 37833, 30596, 17946, 31484, 21347, 33480, 43571, 32573, 25706, 29205, 39719, 40395, 30374, 27315, 32436, 46434, 24315, 36226, 29597]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 36928, 27540, 33799, 40999, 26072, 26993, 21129, 20197, 35189, 29237, 31620]
Topic: 7. Top: [30339, 29237, 47238, 33036, 33125, 29282, 29096, 30252, 32510, 31298, 29684, 34871, 33176, 29902, 33124, 28695, 30160, 26027, 29784, 39719]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 25706, 37833, 29453, 34507, 52298, 27315, 24315, 43184, 17905, 30340, 30655, 29331, 28049, 51694, 19933]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 28992, 42639, 33036, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [27587, 22099, 33707, 36303, 29592, 25943, 35657, 21123, 28068, 35331, 19828, 31228, 40521, 22107, 29791, 44826, 29834, 32665, 29559, 17398]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 36195, 32833, 30827, 34207, 31683, 24317, 27360, 24160, 24193, 30331, 33036, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [30791, 25945, 35538, 32665, 43613, 25220, 33826, 26567, 38446, 25943, 32531, 35657, 44211, 25607, 28999, 34170, 31192, 16898, 21390, 30161]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 29908, 28884, 27086, 34170, 23885, 34409, 31759, 29331, 29939]
Topic: 0. Top: [33484, 27185, 20673, 20528, 43613, 28992, 32665, 26239, 42166, 38446, 31502, 44211, 26809, 22254, 26466, 34170, 28019, 21001, 28068, 28146]
Topic: 1. Top: [36376, 32665, 32929, 42456, 31803, 26192, 33746, 33047, 48811, 26627, 21874, 28535, 25540, 28252, 29891, 45935, 26885, 27540, 27738, 27662]
Topic: 2. Top: [49838, 28100, 34287, 28095, 29939, 26190, 24123, 37130, 28019, 40409, 32833, 51400, 30119, 36268, 30627, 23120, 31964, 28992, 25538, 29972]
Topic: 3. Top: [21123, 32833, 35657, 32135, 39872, 46714, 44211, 26864, 35604, 25025, 26809, 34713, 34729, 27724, 30791, 31747, 27334, 32275, 25514, 30750]
Topic: 4. Top: [28172, 32254, 28629, 30887, 40736, 28453, 37712, 37631, 37492, 34012, 30656, 31133, 30429, 22028, 30795, 20581, 49897, 45080, 30100, 37017]
Topic: 5. Top: [28651, 37833, 30596, 17946, 31484, 21347, 33480, 43571, 32573, 25706, 29205, 39719, 40395, 30374, 27315, 32436, 46434, 24315, 36226, 29597]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 36928, 27540, 33799, 40999, 26072, 26993, 21129, 20197, 35189, 29237, 31620]
Topic: 7. Top: [30339, 29237, 47238, 33036, 33125, 29282, 29096, 30252, 32510, 31298, 29684, 34871, 33176, 29902, 33124, 28695, 30160, 26027, 29784, 39719]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 25706, 37833, 29453, 34507, 52298, 27315, 24315, 43184, 17905, 30340, 30655, 29331, 28049, 51694, 19933]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 28992, 42639, 33036, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [27587, 22099, 33707, 36303, 29592, 25943, 35657, 21123, 28068, 35331, 19828, 31228, 40521, 22107, 29791, 44826, 29834, 32665, 29559, 17398]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 36195, 32833, 30827, 34207, 31683, 24317, 27360, 24160, 24193, 30331, 33036, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [30791, 25945, 35538, 32665, 43613, 25220, 33826, 26567, 38446, 25943, 32531, 35657, 44211, 25607, 28999, 34170, 31192, 16898, 21390, 30161]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 29908, 28884, 27086, 34170, 23885, 34409, 31759, 29331, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.9582629123240377
sparse_theta_sp: -4.472402357987704
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000
num_topics: {'good': 19, 'bad': 1, 'not_good': 1, 'total_bad': 20}
15

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b710dad60>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f7b89214f40>}
Topic: 0. Top: [33484, 27185, 20673, 20528, 43613, 28992, 32665, 26239, 42166, 38446, 31502, 44211, 26809, 22254, 26466, 34170, 28019, 21001, 28068, 28146]
Topic: 1. Top: [36376, 32665, 32929, 42456, 31803, 26192, 33746, 33047, 48811, 26627, 21874, 28535, 25540, 28252, 29891, 45935, 26885, 27540, 27738, 27662]
Topic: 2. Top: [49838, 28100, 34287, 28095, 29939, 26190, 24123, 37130, 28019, 40409, 32833, 51400, 30119, 36268, 30627, 23120, 31964, 28992, 25538, 29972]
Topic: 3. Top: [21123, 32833, 35657, 32135, 39872, 46714, 44211, 26864, 35604, 25025, 26809, 34713, 34729, 27724, 30791, 31747, 27334, 32275, 25514, 30750]
Topic: 4. Top: [28172, 32254, 28629, 30887, 40736, 28453, 37712, 37631, 37492, 34012, 30656, 31133, 30429, 22028, 30795, 20581, 49897, 45080, 30100, 37017]
Topic: 5. Top: [28651, 37833, 30596, 17946, 31484, 21347, 33480, 43571, 32573, 25706, 29205, 39719, 40395, 30374, 27315, 32436, 46434, 24315, 36226, 29597]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 36928, 27540, 33799, 40999, 26072, 26993, 21129, 20197, 35189, 29237, 31620]
Topic: 7. Top: [30339, 29237, 47238, 33036, 34317, 33125, 29282, 29096, 32510, 30252, 31298, 33123, 29684, 33176, 34871, 33124, 29902, 28695, 30160, 29784]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 25706, 37833, 29453, 34507, 52298, 27315, 24315, 43184, 17905, 30340, 30655, 29331, 28049, 51694, 19933]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 28992, 42639, 33036, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [27587, 22099, 33707, 36303, 29592, 25943, 35657, 21123, 28068, 35331, 19828, 31228, 40521, 22107, 29791, 44826, 29834, 32665, 29559, 17398]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 36195, 32833, 30827, 34207, 31683, 24317, 27360, 24160, 24193, 30331, 33036, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [30791, 25945, 35538, 32665, 43613, 25220, 33826, 26567, 38446, 25943, 32531, 35657, 44211, 25607, 28999, 34170, 31192, 16898, 21390, 30161]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 29908, 28884, 27086, 34170, 23885, 34409, 31759, 29331, 29939]
Topic: 0. Top: [33484, 27185, 20673, 20528, 43613, 28992, 32665, 26239, 42166, 38446, 31502, 44211, 26809, 22254, 26466, 34170, 28019, 21001, 28068, 28146]
Topic: 1. Top: [36376, 32665, 32929, 42456, 31803, 26192, 33746, 33047, 48811, 26627, 21874, 28535, 25540, 28252, 29891, 45935, 26885, 27540, 27738, 27662]
Topic: 2. Top: [49838, 28100, 34287, 28095, 29939, 26190, 24123, 37130, 28019, 40409, 32833, 51400, 30119, 36268, 30627, 23120, 31964, 28992, 25538, 29972]
Topic: 3. Top: [21123, 32833, 35657, 32135, 39872, 46714, 44211, 26864, 35604, 25025, 26809, 34713, 34729, 27724, 30791, 31747, 27334, 32275, 25514, 30750]
Topic: 4. Top: [28172, 32254, 28629, 30887, 40736, 28453, 37712, 37631, 37492, 34012, 30656, 31133, 30429, 22028, 30795, 20581, 49897, 45080, 30100, 37017]
Topic: 5. Top: [28651, 37833, 30596, 17946, 31484, 21347, 33480, 43571, 32573, 25706, 29205, 39719, 40395, 30374, 27315, 32436, 46434, 24315, 36226, 29597]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 36928, 27540, 33799, 40999, 26072, 26993, 21129, 20197, 35189, 29237, 31620]
Topic: 7. Top: [30339, 29237, 47238, 33036, 34317, 33125, 29282, 29096, 32510, 30252, 31298, 33123, 29684, 33176, 34871, 33124, 29902, 28695, 30160, 29784]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 25706, 37833, 29453, 34507, 52298, 27315, 24315, 43184, 17905, 30340, 30655, 29331, 28049, 51694, 19933]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 28992, 42639, 33036, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [27587, 22099, 33707, 36303, 29592, 25943, 35657, 21123, 28068, 35331, 19828, 31228, 40521, 22107, 29791, 44826, 29834, 32665, 29559, 17398]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 36195, 32833, 30827, 34207, 31683, 24317, 27360, 24160, 24193, 30331, 33036, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [30791, 25945, 35538, 32665, 43613, 25220, 33826, 26567, 38446, 25943, 32531, 35657, 44211, 25607, 28999, 34170, 31192, 16898, 21390, 30161]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 29908, 28884, 27086, 34170, 23885, 34409, 31759, 29331, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.9582629123240377
sparse_theta_sp: -4.472402357987704
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000
num_topics: {'good': 19, 'bad': 1, 'not_good': 1, 'total_bad': 21}
16

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8eaa88b0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f7b7167afd0>}
Topic: 0. Top: [33484, 27185, 20673, 20528, 43613, 28992, 32665, 26239, 42166, 38446, 31502, 44211, 26809, 22254, 26466, 34170, 28019, 21001, 28068, 28146]
Topic: 1. Top: [36376, 32665, 32929, 42456, 31803, 26192, 33746, 33047, 48811, 26627, 21874, 28535, 25540, 28252, 29891, 45935, 26885, 27540, 27738, 27662]
Topic: 2. Top: [49838, 28100, 34287, 28095, 29939, 26190, 24123, 37130, 28019, 40409, 32833, 51400, 30119, 36268, 30627, 23120, 31964, 28992, 25538, 29972]
Topic: 3. Top: [21123, 32833, 35657, 32135, 39872, 46714, 44211, 26864, 35604, 25025, 26809, 34713, 34729, 27724, 30791, 31747, 27334, 32275, 25514, 30750]
Topic: 4. Top: [28172, 32254, 28629, 30887, 40736, 28453, 37712, 37631, 37492, 34012, 30656, 31133, 30429, 22028, 30795, 20581, 49897, 45080, 30100, 37017]
Topic: 5. Top: [28651, 37833, 30596, 17946, 31484, 21347, 33480, 43571, 32573, 25706, 29205, 39719, 40395, 30374, 27315, 32436, 46434, 24315, 36226, 29597]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 36928, 27540, 33799, 40999, 26072, 26993, 21129, 20197, 35189, 29237, 31620]
Topic: 7. Top: [30339, 29237, 47238, 33036, 34317, 33125, 29282, 29096, 30252, 32510, 31298, 29684, 33176, 34871, 33124, 29902, 28695, 30160, 26027, 26745]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 25706, 37833, 29453, 34507, 52298, 27315, 24315, 43184, 17905, 30340, 30655, 29331, 28049, 51694, 19933]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 28992, 42639, 33036, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [27587, 22099, 33707, 36303, 29592, 25943, 35657, 21123, 28068, 35331, 19828, 31228, 40521, 22107, 29791, 44826, 29834, 32665, 29559, 17398]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 36195, 32833, 30827, 34207, 31683, 24317, 27360, 24160, 24193, 30331, 33036, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [30791, 25945, 35538, 32665, 43613, 25220, 33826, 26567, 38446, 25943, 32531, 35657, 44211, 25607, 28999, 34170, 31192, 16898, 21390, 30161]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 29908, 28884, 27086, 34170, 23885, 34409, 31759, 29331, 29939]
Topic: 0. Top: [33484, 27185, 20673, 20528, 43613, 28992, 32665, 26239, 42166, 38446, 31502, 44211, 26809, 22254, 26466, 34170, 28019, 21001, 28068, 28146]
Topic: 1. Top: [36376, 32665, 32929, 42456, 31803, 26192, 33746, 33047, 48811, 26627, 21874, 28535, 25540, 28252, 29891, 45935, 26885, 27540, 27738, 27662]
Topic: 2. Top: [49838, 28100, 34287, 28095, 29939, 26190, 24123, 37130, 28019, 40409, 32833, 51400, 30119, 36268, 30627, 23120, 31964, 28992, 25538, 29972]
Topic: 3. Top: [21123, 32833, 35657, 32135, 39872, 46714, 44211, 26864, 35604, 25025, 26809, 34713, 34729, 27724, 30791, 31747, 27334, 32275, 25514, 30750]
Topic: 4. Top: [28172, 32254, 28629, 30887, 40736, 28453, 37712, 37631, 37492, 34012, 30656, 31133, 30429, 22028, 30795, 20581, 49897, 45080, 30100, 37017]
Topic: 5. Top: [28651, 37833, 30596, 17946, 31484, 21347, 33480, 43571, 32573, 25706, 29205, 39719, 40395, 30374, 27315, 32436, 46434, 24315, 36226, 29597]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 36928, 27540, 33799, 40999, 26072, 26993, 21129, 20197, 35189, 29237, 31620]
Topic: 7. Top: [30339, 29237, 47238, 33036, 34317, 33125, 29282, 29096, 30252, 32510, 31298, 29684, 33176, 34871, 33124, 29902, 28695, 30160, 26027, 26745]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 25706, 37833, 29453, 34507, 52298, 27315, 24315, 43184, 17905, 30340, 30655, 29331, 28049, 51694, 19933]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 28992, 42639, 33036, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [27587, 22099, 33707, 36303, 29592, 25943, 35657, 21123, 28068, 35331, 19828, 31228, 40521, 22107, 29791, 44826, 29834, 32665, 29559, 17398]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 36195, 32833, 30827, 34207, 31683, 24317, 27360, 24160, 24193, 30331, 33036, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [30791, 25945, 35538, 32665, 43613, 25220, 33826, 26567, 38446, 25943, 32531, 35657, 44211, 25607, 28999, 34170, 31192, 16898, 21390, 30161]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 29908, 28884, 27086, 34170, 23885, 34409, 31759, 29331, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.9582629123240377
sparse_theta_sp: -4.472402357987704
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000
num_topics: {'good': 19, 'bad': 1, 'not_good': 1, 'total_bad': 22}
17

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b891b2250>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f7b8918e160>}
Topic: 0. Top: [33484, 27185, 20673, 20528, 43613, 28992, 32665, 26239, 42166, 38446, 31502, 44211, 26809, 22254, 26466, 34170, 28019, 21001, 28068, 28146]
Topic: 1. Top: [36376, 32665, 32929, 42456, 31803, 26192, 33746, 33047, 48811, 26627, 21874, 28535, 25540, 28252, 29891, 45935, 26885, 27540, 27738, 27662]
Topic: 2. Top: [49838, 28100, 34287, 28095, 29939, 26190, 24123, 37130, 28019, 40409, 32833, 51400, 30119, 36268, 30627, 23120, 31964, 28992, 25538, 29972]
Topic: 3. Top: [21123, 32833, 35657, 32135, 39872, 46714, 44211, 26864, 35604, 25025, 26809, 34713, 34729, 27724, 30791, 31747, 27334, 32275, 25514, 30750]
Topic: 4. Top: [28172, 32254, 28629, 30887, 40736, 28453, 37712, 37631, 37492, 34012, 30656, 31133, 30429, 22028, 30795, 20581, 49897, 45080, 30100, 37017]
Topic: 5. Top: [28651, 37833, 30596, 17946, 31484, 21347, 33480, 43571, 32573, 25706, 29205, 39719, 40395, 30374, 27315, 32436, 46434, 24315, 36226, 29597]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 36928, 27540, 33799, 40999, 26072, 26993, 21129, 20197, 35189, 29237, 31620]
Topic: 7. Top: [30339, 29237, 47238, 33036, 34317, 33125, 29282, 29096, 30252, 31298, 33123, 29684, 34871, 33176, 33124, 29902, 28695, 30160, 29784, 26027]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 25706, 37833, 29453, 34507, 52298, 27315, 24315, 43184, 17905, 30340, 30655, 29331, 28049, 51694, 19933]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 28992, 42639, 33036, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [27587, 22099, 33707, 36303, 29592, 25943, 35657, 21123, 28068, 35331, 19828, 31228, 40521, 22107, 29791, 44826, 29834, 32665, 29559, 17398]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 36195, 32833, 30827, 34207, 31683, 24317, 27360, 24160, 24193, 30331, 33036, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [30791, 25945, 35538, 32665, 43613, 25220, 33826, 26567, 38446, 25943, 32531, 35657, 44211, 25607, 28999, 34170, 31192, 16898, 21390, 30161]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 29908, 28884, 27086, 34170, 23885, 34409, 31759, 29331, 29939]
Topic: 0. Top: [33484, 27185, 20673, 20528, 43613, 28992, 32665, 26239, 42166, 38446, 31502, 44211, 26809, 22254, 26466, 34170, 28019, 21001, 28068, 28146]
Topic: 1. Top: [36376, 32665, 32929, 42456, 31803, 26192, 33746, 33047, 48811, 26627, 21874, 28535, 25540, 28252, 29891, 45935, 26885, 27540, 27738, 27662]
Topic: 2. Top: [49838, 28100, 34287, 28095, 29939, 26190, 24123, 37130, 28019, 40409, 32833, 51400, 30119, 36268, 30627, 23120, 31964, 28992, 25538, 29972]
Topic: 3. Top: [21123, 32833, 35657, 32135, 39872, 46714, 44211, 26864, 35604, 25025, 26809, 34713, 34729, 27724, 30791, 31747, 27334, 32275, 25514, 30750]
Topic: 4. Top: [28172, 32254, 28629, 30887, 40736, 28453, 37712, 37631, 37492, 34012, 30656, 31133, 30429, 22028, 30795, 20581, 49897, 45080, 30100, 37017]
Topic: 5. Top: [28651, 37833, 30596, 17946, 31484, 21347, 33480, 43571, 32573, 25706, 29205, 39719, 40395, 30374, 27315, 32436, 46434, 24315, 36226, 29597]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 36928, 27540, 33799, 40999, 26072, 26993, 21129, 20197, 35189, 29237, 31620]
Topic: 7. Top: [30339, 29237, 47238, 33036, 34317, 33125, 29282, 29096, 30252, 31298, 33123, 29684, 34871, 33176, 33124, 29902, 28695, 30160, 29784, 26027]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 25706, 37833, 29453, 34507, 52298, 27315, 24315, 43184, 17905, 30340, 30655, 29331, 28049, 51694, 19933]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 28992, 42639, 33036, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [27587, 22099, 33707, 36303, 29592, 25943, 35657, 21123, 28068, 35331, 19828, 31228, 40521, 22107, 29791, 44826, 29834, 32665, 29559, 17398]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 36195, 32833, 30827, 34207, 31683, 24317, 27360, 24160, 24193, 30331, 33036, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [30791, 25945, 35538, 32665, 43613, 25220, 33826, 26567, 38446, 25943, 32531, 35657, 44211, 25607, 28999, 34170, 31192, 16898, 21390, 30161]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 29908, 28884, 27086, 34170, 23885, 34409, 31759, 29331, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.9582629123240377
sparse_theta_sp: -4.472402357987704
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000
num_topics: {'good': 19, 'bad': 1, 'not_good': 1, 'total_bad': 23}
18

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8ba63bb0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f7b891b24c0>}
Topic: 0. Top: [33484, 27185, 20673, 20528, 43613, 28992, 32665, 26239, 42166, 38446, 31502, 44211, 26809, 22254, 26466, 34170, 28019, 21001, 28068, 28146]
Topic: 1. Top: [36376, 32665, 32929, 42456, 31803, 26192, 33746, 33047, 48811, 26627, 21874, 28535, 25540, 28252, 29891, 45935, 26885, 27540, 27738, 27662]
Topic: 2. Top: [49838, 28100, 34287, 28095, 29939, 26190, 24123, 37130, 28019, 40409, 32833, 51400, 30119, 36268, 30627, 23120, 31964, 28992, 25538, 29972]
Topic: 3. Top: [21123, 32833, 35657, 32135, 39872, 46714, 44211, 26864, 35604, 25025, 26809, 34713, 34729, 27724, 30791, 31747, 27334, 32275, 25514, 30750]
Topic: 4. Top: [28172, 32254, 28629, 30887, 40736, 28453, 37712, 37631, 37492, 34012, 30656, 31133, 30429, 22028, 30795, 20581, 49897, 45080, 30100, 37017]
Topic: 5. Top: [28651, 37833, 30596, 17946, 31484, 21347, 33480, 43571, 32573, 25706, 29205, 39719, 40395, 30374, 27315, 32436, 46434, 24315, 36226, 29597]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 36928, 27540, 33799, 40999, 26072, 26993, 21129, 20197, 35189, 29237, 31620]
Topic: 7. Top: [30339, 29237, 47238, 33036, 34317, 33125, 29282, 32510, 29096, 30252, 33123, 31298, 33176, 29684, 34871, 33124, 29902, 28695, 30160, 29784]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 25706, 37833, 29453, 34507, 52298, 27315, 24315, 43184, 17905, 30340, 30655, 29331, 28049, 51694, 19933]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 28992, 42639, 33036, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [27587, 22099, 33707, 36303, 29592, 25943, 35657, 21123, 28068, 35331, 19828, 31228, 40521, 22107, 29791, 44826, 29834, 32665, 29559, 17398]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 36195, 32833, 30827, 34207, 31683, 24317, 27360, 24160, 24193, 30331, 33036, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [30791, 25945, 35538, 32665, 43613, 25220, 33826, 26567, 38446, 25943, 32531, 35657, 44211, 25607, 28999, 34170, 31192, 16898, 21390, 30161]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 29908, 28884, 27086, 34170, 23885, 34409, 31759, 29331, 29939]
Topic: 0. Top: [33484, 27185, 20673, 20528, 43613, 28992, 32665, 26239, 42166, 38446, 31502, 44211, 26809, 22254, 26466, 34170, 28019, 21001, 28068, 28146]
Topic: 1. Top: [36376, 32665, 32929, 42456, 31803, 26192, 33746, 33047, 48811, 26627, 21874, 28535, 25540, 28252, 29891, 45935, 26885, 27540, 27738, 27662]
Topic: 2. Top: [49838, 28100, 34287, 28095, 29939, 26190, 24123, 37130, 28019, 40409, 32833, 51400, 30119, 36268, 30627, 23120, 31964, 28992, 25538, 29972]
Topic: 3. Top: [21123, 32833, 35657, 32135, 39872, 46714, 44211, 26864, 35604, 25025, 26809, 34713, 34729, 27724, 30791, 31747, 27334, 32275, 25514, 30750]
Topic: 4. Top: [28172, 32254, 28629, 30887, 40736, 28453, 37712, 37631, 37492, 34012, 30656, 31133, 30429, 22028, 30795, 20581, 49897, 45080, 30100, 37017]
Topic: 5. Top: [28651, 37833, 30596, 17946, 31484, 21347, 33480, 43571, 32573, 25706, 29205, 39719, 40395, 30374, 27315, 32436, 46434, 24315, 36226, 29597]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 36928, 27540, 33799, 40999, 26072, 26993, 21129, 20197, 35189, 29237, 31620]
Topic: 7. Top: [30339, 29237, 47238, 33036, 34317, 33125, 29282, 32510, 29096, 30252, 33123, 31298, 33176, 29684, 34871, 33124, 29902, 28695, 30160, 29784]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 25706, 37833, 29453, 34507, 52298, 27315, 24315, 43184, 17905, 30340, 30655, 29331, 28049, 51694, 19933]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 28992, 42639, 33036, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [27587, 22099, 33707, 36303, 29592, 25943, 35657, 21123, 28068, 35331, 19828, 31228, 40521, 22107, 29791, 44826, 29834, 32665, 29559, 17398]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 36195, 32833, 30827, 34207, 31683, 24317, 27360, 24160, 24193, 30331, 33036, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [30791, 25945, 35538, 32665, 43613, 25220, 33826, 26567, 38446, 25943, 32531, 35657, 44211, 25607, 28999, 34170, 31192, 16898, 21390, 30161]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 29908, 28884, 27086, 34170, 23885, 34409, 31759, 29331, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.9582629123240377
sparse_theta_sp: -4.472402357987704
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000
num_topics: {'good': 19, 'bad': 1, 'not_good': 1, 'total_bad': 24}
19

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8f9a6640>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer object at 0x7f7b8f7dcfd0>}
Topic: 0. Top: [33484, 27185, 20673, 20528, 43613, 28992, 32665, 26239, 42166, 38446, 31502, 44211, 26809, 22254, 26466, 34170, 28019, 21001, 28068, 28146]
Topic: 1. Top: [36376, 32665, 32929, 42456, 31803, 26192, 33746, 33047, 48811, 26627, 21874, 28535, 25540, 28252, 29891, 45935, 26885, 27540, 27738, 27662]
Topic: 2. Top: [49838, 28100, 34287, 28095, 29939, 26190, 24123, 37130, 28019, 40409, 32833, 51400, 30119, 36268, 30627, 23120, 31964, 28992, 25538, 29972]
Topic: 3. Top: [21123, 32833, 35657, 32135, 39872, 46714, 44211, 26864, 35604, 25025, 26809, 34713, 34729, 27724, 30791, 31747, 27334, 32275, 25514, 30750]
Topic: 4. Top: [28172, 32254, 28629, 30887, 40736, 28453, 37712, 37631, 37492, 34012, 30656, 31133, 30429, 22028, 30795, 20581, 49897, 45080, 30100, 37017]
Topic: 5. Top: [28651, 37833, 30596, 17946, 31484, 21347, 33480, 43571, 32573, 25706, 29205, 39719, 40395, 30374, 27315, 32436, 46434, 24315, 36226, 29597]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 36928, 27540, 33799, 40999, 26072, 26993, 21129, 20197, 35189, 29237, 31620]
Topic: 7. Top: [30339, 29237, 47238, 33036, 33125, 34317, 29282, 29096, 32510, 30252, 31298, 33123, 29684, 34871, 33176, 29902, 28695, 29784, 26027, 39719]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 25706, 37833, 29453, 34507, 52298, 27315, 24315, 43184, 17905, 30340, 30655, 29331, 28049, 51694, 19933]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 28992, 42639, 33036, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [27587, 22099, 33707, 36303, 29592, 25943, 35657, 21123, 28068, 35331, 19828, 31228, 40521, 22107, 29791, 44826, 29834, 32665, 29559, 17398]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 36195, 32833, 30827, 34207, 31683, 24317, 27360, 24160, 24193, 30331, 33036, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [30791, 25945, 35538, 32665, 43613, 25220, 33826, 26567, 38446, 25943, 32531, 35657, 44211, 25607, 28999, 34170, 31192, 16898, 21390, 30161]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 29908, 28884, 27086, 34170, 23885, 34409, 31759, 29331, 29939]
Topic: 0. Top: [33484, 27185, 20673, 20528, 43613, 28992, 32665, 26239, 42166, 38446, 31502, 44211, 26809, 22254, 26466, 34170, 28019, 21001, 28068, 28146]
Topic: 1. Top: [36376, 32665, 32929, 42456, 31803, 26192, 33746, 33047, 48811, 26627, 21874, 28535, 25540, 28252, 29891, 45935, 26885, 27540, 27738, 27662]
Topic: 2. Top: [49838, 28100, 34287, 28095, 29939, 26190, 24123, 37130, 28019, 40409, 32833, 51400, 30119, 36268, 30627, 23120, 31964, 28992, 25538, 29972]
Topic: 3. Top: [21123, 32833, 35657, 32135, 39872, 46714, 44211, 26864, 35604, 25025, 26809, 34713, 34729, 27724, 30791, 31747, 27334, 32275, 25514, 30750]
Topic: 4. Top: [28172, 32254, 28629, 30887, 40736, 28453, 37712, 37631, 37492, 34012, 30656, 31133, 30429, 22028, 30795, 20581, 49897, 45080, 30100, 37017]
Topic: 5. Top: [28651, 37833, 30596, 17946, 31484, 21347, 33480, 43571, 32573, 25706, 29205, 39719, 40395, 30374, 27315, 32436, 46434, 24315, 36226, 29597]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 36928, 27540, 33799, 40999, 26072, 26993, 21129, 20197, 35189, 29237, 31620]
Topic: 7. Top: [30339, 29237, 47238, 33036, 33125, 34317, 29282, 29096, 32510, 30252, 31298, 33123, 29684, 34871, 33176, 29902, 28695, 29784, 26027, 39719]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 25706, 37833, 29453, 34507, 52298, 27315, 24315, 43184, 17905, 30340, 30655, 29331, 28049, 51694, 19933]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 28992, 42639, 33036, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [27587, 22099, 33707, 36303, 29592, 25943, 35657, 21123, 28068, 35331, 19828, 31228, 40521, 22107, 29791, 44826, 29834, 32665, 29559, 17398]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 36195, 32833, 30827, 34207, 31683, 24317, 27360, 24160, 24193, 30331, 33036, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [30791, 25945, 35538, 32665, 43613, 25220, 33826, 26567, 38446, 25943, 32531, 35657, 44211, 25607, 28999, 34170, 31192, 16898, 21390, 30161]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 29908, 28884, 27086, 34170, 23885, 34409, 31759, 29331, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.9582629123240377
sparse_theta_sp: -4.472402357987704
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000
num_topics: {'good': 19, 'bad': 1, 'not_good': 1, 'total_bad': 25}
(1, 0, 0)
0
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
Topic: 0. Top: [32833, 40029, 33826, 30791, 37692, 28368, 19656, 28999, 27300, 35416, 28775, 25945, 25220, 41831, 26306, 29939, 33036, 37130, 38446, 27264]
Topic: 1. Top: [36195, 42454, 30130, 34207, 27360, 30827, 32833, 24160, 32028, 31683, 47035, 48735, 40820, 27934, 33726, 29464, 28122, 36226, 29858, 38105]
Topic: 2. Top: [43613, 30791, 32833, 32665, 27086, 44211, 33123, 33484, 31997, 21123, 35416, 35657, 32135, 25289, 29331, 20673, 34170, 23885, 39872, 38446]
Topic: 3. Top: [30339, 28016, 47238, 29237, 33036, 30252, 29096, 27030, 47035, 30887, 34317, 32254, 29684, 31298, 31397, 17231, 30795, 37492, 37631, 48735]
Topic: 4. Top: [28172, 35842, 28465, 22422, 28629, 27624, 21650, 49838, 36585, 29272, 30656, 40295, 24278, 40736, 31622, 17856, 27066, 29834, 34095, 52105]
Topic: 5. Top: [29385, 32833, 32942, 28820, 36874, 29939, 50360, 46187, 31059, 24494, 44833, 37553, 28019, 35189, 27643, 25902, 28992, 39575, 35113, 23798]
Topic: 6. Top: [29453, 36383, 29116, 26627, 31186, 29237, 29282, 32833, 40999, 51040, 32510, 35708, 34014, 51902, 32678, 51496, 35189, 29096, 28406, 36928]
Topic: 7. Top: [28884, 35023, 33036, 20164, 29939, 27187, 27587, 51610, 30152, 24317, 29085, 28701, 33006, 37168, 36515, 27970, 38087, 33124, 21347, 32510]
Topic: 8. Top: [33123, 33125, 47238, 29282, 28701, 30339, 33036, 26745, 32510, 28695, 34317, 33176, 29237, 33124, 34871, 29902, 31298, 52105, 30160, 29728]
Topic: 9. Top: [32833, 34364, 33123, 33036, 42030, 25342, 50442, 25025, 44121, 31777, 35416, 18601, 40029, 46714, 33176, 46583, 19656, 27624, 31683, 38753]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [20528, 22254, 28068, 33484, 29939, 34170, 32677, 50360, 29328, 29998, 27185, 37083, 27787, 25911, 28992, 49264, 42166, 28193, 39945, 32833]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [28651, 30339, 34089, 37833, 33036, 39719, 29237, 25706, 27532, 30596, 30066, 29282, 43571, 32510, 24315, 17946, 34317, 26129, 30252, 29096]
Topic: 15. Top: [35331, 27540, 31186, 32665, 52105, 30331, 39921, 42456, 27624, 22209, 20197, 27307, 43613, 50360, 32929, 37263, 32028, 19656, 25859, 43025]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [49838, 37130, 28100, 34287, 29939, 32833, 26190, 28095, 24123, 30627, 30597, 51400, 34531, 28019, 32942, 30119, 40409, 32717, 31192, 36268]
Topic: 0. Top: [32833, 40029, 33826, 30791, 37692, 28368, 19656, 28999, 27300, 35416, 28775, 25945, 25220, 41831, 26306, 29939, 33036, 37130, 38446, 27264]
Topic: 1. Top: [36195, 42454, 30130, 34207, 27360, 30827, 32833, 24160, 32028, 31683, 47035, 48735, 40820, 27934, 33726, 29464, 28122, 36226, 29858, 38105]
Topic: 2. Top: [43613, 30791, 32833, 32665, 27086, 44211, 33123, 33484, 31997, 21123, 35416, 35657, 32135, 25289, 29331, 20673, 34170, 23885, 39872, 38446]
Topic: 3. Top: [30339, 28016, 47238, 29237, 33036, 30252, 29096, 27030, 47035, 30887, 34317, 32254, 29684, 31298, 31397, 17231, 30795, 37492, 37631, 48735]
Topic: 4. Top: [28172, 35842, 28465, 22422, 28629, 27624, 21650, 49838, 36585, 29272, 30656, 40295, 24278, 40736, 31622, 17856, 27066, 29834, 34095, 52105]
Topic: 5. Top: [29385, 32833, 32942, 28820, 36874, 29939, 50360, 46187, 31059, 24494, 44833, 37553, 28019, 35189, 27643, 25902, 28992, 39575, 35113, 23798]
Topic: 6. Top: [29453, 36383, 29116, 26627, 31186, 29237, 29282, 32833, 40999, 51040, 32510, 35708, 34014, 51902, 32678, 51496, 35189, 29096, 28406, 36928]
Topic: 7. Top: [28884, 35023, 33036, 20164, 29939, 27187, 27587, 51610, 30152, 24317, 29085, 28701, 33006, 37168, 36515, 27970, 38087, 33124, 21347, 32510]
Topic: 8. Top: [33123, 33125, 47238, 29282, 28701, 30339, 33036, 26745, 32510, 28695, 34317, 33176, 29237, 33124, 34871, 29902, 31298, 52105, 30160, 29728]
Topic: 9. Top: [32833, 34364, 33123, 33036, 42030, 25342, 50442, 25025, 44121, 31777, 35416, 18601, 40029, 46714, 33176, 46583, 19656, 27624, 31683, 38753]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [20528, 22254, 28068, 33484, 29939, 34170, 32677, 50360, 29328, 29998, 27185, 37083, 27787, 25911, 28992, 49264, 42166, 28193, 39945, 32833]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [28651, 30339, 34089, 37833, 33036, 39719, 29237, 25706, 27532, 30596, 30066, 29282, 43571, 32510, 24315, 17946, 34317, 26129, 30252, 29096]
Topic: 15. Top: [35331, 27540, 31186, 32665, 52105, 30331, 39921, 42456, 27624, 22209, 20197, 27307, 43613, 50360, 32929, 37263, 32028, 19656, 25859, 43025]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [49838, 37130, 28100, 34287, 29939, 32833, 26190, 28095, 24123, 30627, 30597, 51400, 34531, 28019, 32942, 30119, 40409, 32717, 31192, 36268]
num_topics: {'good': 6, 'bad': 2, 'not_good': 14, 'total_bad': 2}
1

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8e94cac0>}
Topic: 0. Top: [29282, 33125, 33036, 32510, 30339, 28701, 28695, 34317, 34871, 20164, 26745, 17194, 30160, 33123, 33124, 47238, 29237, 33176, 33731, 35023]
Topic: 1. Top: [43613, 37130, 33484, 31997, 30627, 22254, 34170, 20673, 27185, 20528, 28068, 28992, 32665, 32677, 29939, 25289, 33826, 32833, 28100, 42166]
Topic: 2. Top: [39575, 28884, 50360, 38245, 34409, 20370, 31059, 27187, 31759, 25911, 24203, 43613, 29068, 30152, 35331, 32931, 24494, 29085, 29939, 31147]
Topic: 3. Top: [49838, 32833, 33123, 34287, 33036, 40029, 17856, 28172, 19656, 42030, 26190, 29939, 28100, 34364, 45727, 22422, 33176, 37130, 28095, 30444]
Topic: 4. Top: [52105, 19656, 30339, 21874, 42456, 33047, 32665, 27624, 33176, 47238, 28465, 29237, 29096, 29592, 27540, 33123, 31186, 36376, 32929, 35331]
Topic: 5. Top: [36383, 29453, 31186, 26627, 51040, 32833, 29116, 40999, 29237, 51902, 34014, 33799, 36928, 35708, 51496, 35750, 35189, 21129, 30130, 43613]
Topic: 6. Top: [32833, 30791, 21123, 35657, 27086, 43613, 35538, 32135, 32665, 33123, 35416, 26809, 28193, 36303, 28068, 22254, 32760, 29592, 19656, 29998]
Topic: 7. Top: [29237, 43571, 29096, 33125, 33036, 29902, 32510, 30596, 28701, 47035, 40395, 30339, 29597, 27970, 33124, 46434, 32711, 26745, 35057, 30876]
Topic: 8. Top: [32833, 30791, 38446, 40029, 35416, 25945, 44211, 20528, 46714, 32665, 29939, 33484, 37692, 19656, 33036, 26306, 45727, 25220, 39872, 29033]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [46583, 21394, 52456, 33761, 24452, 29205, 27624, 29393, 43332, 40157, 23739, 24625, 45519, 35494, 48872, 24932, 41048, 17398, 19900, 23664]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 27532, 24315, 26129, 17946, 30252, 30374, 30066, 31484, 34317, 29453, 25420, 32510, 21347]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [47238, 30339, 33123, 33036, 31298, 30252, 34317, 33176, 29237, 29684, 33124, 44121, 26745, 31397, 48735, 29096, 17231, 33125, 28695, 29282]
Topic: 0. Top: [29282, 33125, 33036, 32510, 30339, 28701, 28695, 34317, 34871, 20164, 26745, 17194, 30160, 33123, 33124, 47238, 29237, 33176, 33731, 35023]
Topic: 1. Top: [43613, 37130, 33484, 31997, 30627, 22254, 34170, 20673, 27185, 20528, 28068, 28992, 32665, 32677, 29939, 25289, 33826, 32833, 28100, 42166]
Topic: 2. Top: [39575, 28884, 50360, 38245, 34409, 20370, 31059, 27187, 31759, 25911, 24203, 43613, 29068, 30152, 35331, 32931, 24494, 29085, 29939, 31147]
Topic: 3. Top: [49838, 32833, 33123, 34287, 33036, 40029, 17856, 28172, 19656, 42030, 26190, 29939, 28100, 34364, 45727, 22422, 33176, 37130, 28095, 30444]
Topic: 4. Top: [52105, 19656, 30339, 21874, 42456, 33047, 32665, 27624, 33176, 47238, 28465, 29237, 29096, 29592, 27540, 33123, 31186, 36376, 32929, 35331]
Topic: 5. Top: [36383, 29453, 31186, 26627, 51040, 32833, 29116, 40999, 29237, 51902, 34014, 33799, 36928, 35708, 51496, 35750, 35189, 21129, 30130, 43613]
Topic: 6. Top: [32833, 30791, 21123, 35657, 27086, 43613, 35538, 32135, 32665, 33123, 35416, 26809, 28193, 36303, 28068, 22254, 32760, 29592, 19656, 29998]
Topic: 7. Top: [29237, 43571, 29096, 33125, 33036, 29902, 32510, 30596, 28701, 47035, 40395, 30339, 29597, 27970, 33124, 46434, 32711, 26745, 35057, 30876]
Topic: 8. Top: [32833, 30791, 38446, 40029, 35416, 25945, 44211, 20528, 46714, 32665, 29939, 33484, 37692, 19656, 33036, 26306, 45727, 25220, 39872, 29033]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [46583, 21394, 52456, 33761, 24452, 29205, 27624, 29393, 43332, 40157, 23739, 24625, 45519, 35494, 48872, 24932, 41048, 17398, 19900, 23664]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 27532, 24315, 26129, 17946, 30252, 30374, 30066, 31484, 34317, 29453, 25420, 32510, 21347]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [47238, 30339, 33123, 33036, 31298, 30252, 34317, 33176, 29237, 29684, 33124, 44121, 26745, 31397, 48735, 29096, 17231, 33125, 28695, 29282]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.0684473508802884
sparse_theta_sp: -0.319457311284836
decorrelation: 0.01
fix: 1000000000
SUCCESS: more good topics
DOWNFALL: more bad topics...
num_topics: {'good': 8, 'bad': 3, 'not_good': 12, 'total_bad': 5}
2

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8ba489a0>}
Topic: 0. Top: [49838, 28100, 32833, 26190, 29939, 28095, 32717, 40409, 37130, 42030, 51400, 28775, 19656, 25538, 40029, 33036, 29486, 30444, 36268, 28540]
Topic: 1. Top: [28172, 32833, 34364, 33036, 33123, 28629, 42030, 28701, 40295, 27624, 17856, 49838, 34095, 30152, 34130, 25025, 47238, 24278, 25342, 33176]
Topic: 2. Top: [36383, 51040, 40999, 32833, 29282, 27030, 51902, 29453, 28016, 51496, 22209, 34014, 33036, 49904, 30130, 29888, 26362, 31622, 28701, 32510]
Topic: 3. Top: [37833, 28651, 33036, 30596, 30339, 39719, 29453, 17946, 19828, 29259, 31484, 30066, 21347, 17905, 45841, 33480, 25706, 27985, 27970, 38087]
Topic: 4. Top: [30791, 32833, 44211, 21123, 35657, 32665, 32135, 43613, 27086, 35416, 38446, 35538, 33123, 40029, 25945, 19656, 39872, 26239, 34729, 25943]
Topic: 5. Top: [28651, 34089, 27532, 30339, 33036, 26129, 30252, 25706, 37833, 29096, 39719, 34507, 32510, 34317, 52298, 29282, 30876, 43184, 43571, 29237]
Topic: 6. Top: [43613, 33484, 31997, 22254, 39575, 25289, 50360, 29939, 32833, 26648, 20370, 20528, 38245, 32665, 28068, 34170, 27185, 49264, 29331, 20673]
Topic: 7. Top: [32833, 34287, 37692, 28019, 30627, 17856, 28999, 25466, 28368, 26306, 24123, 32942, 35416, 31964, 29939, 31192, 39661, 27264, 46951, 20528]
Topic: 8. Top: [29282, 29237, 33125, 32510, 28701, 20164, 30339, 34871, 28695, 33036, 29902, 33124, 28995, 29784, 26745, 35023, 27136, 33731, 30160, 34317]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [31186, 29116, 27540, 26627, 29453, 35750, 43613, 39921, 20197, 27624, 31620, 35331, 35189, 35708, 52105, 36985, 26993, 27307, 42456, 43025]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [47238, 30339, 33123, 33036, 34317, 30252, 31298, 33176, 29237, 29684, 26745, 33125, 33124, 44121, 29096, 31397, 48735, 17231, 29282, 52105]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [37130, 33826, 32833, 27624, 35842, 30597, 30791, 40029, 27066, 34531, 22422, 21650, 33123, 19656, 50488, 30119, 27300, 37974, 39575, 28068]
Topic: 0. Top: [49838, 28100, 32833, 26190, 29939, 28095, 32717, 40409, 37130, 42030, 51400, 28775, 19656, 25538, 40029, 33036, 29486, 30444, 36268, 28540]
Topic: 1. Top: [28172, 32833, 34364, 33036, 33123, 28629, 42030, 28701, 40295, 27624, 17856, 49838, 34095, 30152, 34130, 25025, 47238, 24278, 25342, 33176]
Topic: 2. Top: [36383, 51040, 40999, 32833, 29282, 27030, 51902, 29453, 28016, 51496, 22209, 34014, 33036, 49904, 30130, 29888, 26362, 31622, 28701, 32510]
Topic: 3. Top: [37833, 28651, 33036, 30596, 30339, 39719, 29453, 17946, 19828, 29259, 31484, 30066, 21347, 17905, 45841, 33480, 25706, 27985, 27970, 38087]
Topic: 4. Top: [30791, 32833, 44211, 21123, 35657, 32665, 32135, 43613, 27086, 35416, 38446, 35538, 33123, 40029, 25945, 19656, 39872, 26239, 34729, 25943]
Topic: 5. Top: [28651, 34089, 27532, 30339, 33036, 26129, 30252, 25706, 37833, 29096, 39719, 34507, 32510, 34317, 52298, 29282, 30876, 43184, 43571, 29237]
Topic: 6. Top: [43613, 33484, 31997, 22254, 39575, 25289, 50360, 29939, 32833, 26648, 20370, 20528, 38245, 32665, 28068, 34170, 27185, 49264, 29331, 20673]
Topic: 7. Top: [32833, 34287, 37692, 28019, 30627, 17856, 28999, 25466, 28368, 26306, 24123, 32942, 35416, 31964, 29939, 31192, 39661, 27264, 46951, 20528]
Topic: 8. Top: [29282, 29237, 33125, 32510, 28701, 20164, 30339, 34871, 28695, 33036, 29902, 33124, 28995, 29784, 26745, 35023, 27136, 33731, 30160, 34317]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [31186, 29116, 27540, 26627, 29453, 35750, 43613, 39921, 20197, 27624, 31620, 35331, 35189, 35708, 52105, 36985, 26993, 27307, 42456, 43025]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [47238, 30339, 33123, 33036, 34317, 30252, 31298, 33176, 29237, 29684, 26745, 33125, 33124, 44121, 29096, 31397, 48735, 17231, 29282, 52105]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [37130, 33826, 32833, 27624, 35842, 30597, 30791, 40029, 27066, 34531, 22422, 21650, 33123, 19656, 50488, 30119, 27300, 37974, 39575, 28068]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.07985524269366981
sparse_theta_sp: -0.37270019649897534
decorrelation: 0.01
fix: 1000000000
num_topics: {'good': 8, 'bad': 3, 'not_good': 12, 'total_bad': 8}
3

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8f7fdaf0>}
Topic: 0. Top: [29282, 29237, 32510, 33125, 33036, 29116, 30339, 30160, 26745, 28701, 32833, 32678, 20164, 28695, 33123, 17194, 28995, 39719, 36383, 31298]
Topic: 1. Top: [28172, 27624, 32833, 28629, 40295, 35842, 42030, 34095, 25025, 21394, 25342, 40736, 26483, 49838, 34364, 33036, 29272, 31133, 30429, 46583]
Topic: 2. Top: [42456, 30339, 30444, 29237, 35331, 36226, 52105, 28252, 40820, 19933, 33036, 27934, 22772, 31228, 27307, 31264, 47035, 26095, 29644, 28068]
Topic: 3. Top: [28651, 30339, 34089, 37833, 33036, 39719, 29237, 29282, 25706, 27532, 30066, 34317, 32510, 43571, 33125, 24315, 26129, 30252, 30596, 30374]
Topic: 4. Top: [30791, 32833, 21123, 44211, 35657, 32135, 40029, 35538, 35416, 25945, 32665, 33123, 27086, 25943, 26567, 19656, 36303, 29592, 34729, 27587]
Topic: 5. Top: [33123, 47238, 52105, 28701, 33176, 28695, 33125, 33036, 32510, 19656, 31298, 26745, 44121, 28995, 46780, 34871, 29282, 33124, 34317, 30339]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [49838, 32833, 37130, 28100, 29939, 34287, 33826, 40029, 19656, 37692, 28019, 30597, 28999, 26190, 33036, 35416, 34531, 28095, 30627, 31192]
Topic: 8. Top: [30339, 47238, 30252, 33036, 34317, 29237, 29684, 29096, 31298, 30887, 33123, 17231, 47035, 28016, 33124, 29902, 31397, 29282, 33176, 33125]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [33036, 35023, 21347, 20164, 32833, 31484, 28701, 19828, 32939, 29559, 33006, 27970, 48622, 30339, 27315, 33124, 29939, 27587, 28884, 30152]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [33484, 32833, 32665, 20528, 27185, 30791, 43613, 42166, 20673, 28992, 28068, 29939, 38446, 34170, 26239, 22254, 30627, 39872, 26306, 39945]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
Topic: 0. Top: [29282, 29237, 32510, 33125, 33036, 29116, 30339, 30160, 26745, 28701, 32833, 32678, 20164, 28695, 33123, 17194, 28995, 39719, 36383, 31298]
Topic: 1. Top: [28172, 27624, 32833, 28629, 40295, 35842, 42030, 34095, 25025, 21394, 25342, 40736, 26483, 49838, 34364, 33036, 29272, 31133, 30429, 46583]
Topic: 2. Top: [42456, 30339, 30444, 29237, 35331, 36226, 52105, 28252, 40820, 19933, 33036, 27934, 22772, 31228, 27307, 31264, 47035, 26095, 29644, 28068]
Topic: 3. Top: [28651, 30339, 34089, 37833, 33036, 39719, 29237, 29282, 25706, 27532, 30066, 34317, 32510, 43571, 33125, 24315, 26129, 30252, 30596, 30374]
Topic: 4. Top: [30791, 32833, 21123, 44211, 35657, 32135, 40029, 35538, 35416, 25945, 32665, 33123, 27086, 25943, 26567, 19656, 36303, 29592, 34729, 27587]
Topic: 5. Top: [33123, 47238, 52105, 28701, 33176, 28695, 33125, 33036, 32510, 19656, 31298, 26745, 44121, 28995, 46780, 34871, 29282, 33124, 34317, 30339]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [49838, 32833, 37130, 28100, 29939, 34287, 33826, 40029, 19656, 37692, 28019, 30597, 28999, 26190, 33036, 35416, 34531, 28095, 30627, 31192]
Topic: 8. Top: [30339, 47238, 30252, 33036, 34317, 29237, 29684, 29096, 31298, 30887, 33123, 17231, 47035, 28016, 33124, 29902, 31397, 29282, 33176, 33125]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [33036, 35023, 21347, 20164, 32833, 31484, 28701, 19828, 32939, 29559, 33006, 27970, 48622, 30339, 27315, 33124, 29939, 27587, 28884, 30152]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [33484, 32833, 32665, 20528, 27185, 30791, 43613, 42166, 20673, 28992, 28068, 29939, 38446, 34170, 26239, 22254, 30627, 39872, 26306, 39945]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.07985524269366981
sparse_theta_sp: -0.37270019649897534
decorrelation: 0.01
fix: 1000000000
SUCCESS: more good topics
num_topics: {'good': 10, 'bad': 3, 'not_good': 10, 'total_bad': 11}
4

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8bbe4160>}
Topic: 0. Top: [29237, 30339, 33125, 33036, 39719, 28651, 29282, 32510, 34317, 43571, 29096, 30596, 37833, 34871, 33124, 27970, 45841, 32939, 30160, 35023]
Topic: 1. Top: [30339, 47238, 33036, 30252, 33123, 29237, 31298, 34317, 29684, 33176, 28016, 29096, 48735, 17231, 44121, 29902, 33124, 31397, 29282, 33125]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [30791, 32833, 33484, 32665, 43613, 27185, 44211, 38446, 20528, 35416, 25945, 20673, 34170, 28992, 29939, 40029, 42166, 26466, 39872, 35657]
Topic: 4. Top: [28172, 37130, 32833, 35842, 27624, 33826, 22422, 40029, 30597, 19656, 33123, 37692, 21650, 33036, 34531, 27066, 27300, 28701, 45727, 29939]
Topic: 5. Top: [32833, 21123, 33036, 19656, 35538, 33123, 41831, 25220, 32135, 31374, 35657, 25025, 37974, 46714, 18601, 47079, 27624, 30791, 41106, 28775]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [29282, 33123, 28701, 33036, 26745, 32510, 33125, 28695, 28995, 34871, 33176, 33124, 30160, 47238, 29728, 20164, 32833, 17194, 34317, 29784]
Topic: 8. Top: [28651, 34089, 27532, 33036, 30339, 37833, 25706, 26129, 30066, 29453, 24315, 34507, 17905, 29331, 29282, 52298, 33176, 43184, 30252, 27315]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [27587, 22099, 33707, 29592, 32833, 36303, 19828, 25943, 33036, 35331, 29559, 35657, 40521, 28068, 30152, 32135, 22107, 31228, 48622, 29834]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [19656, 29237, 52105, 21874, 47238, 33047, 33125, 32510, 29282, 26627, 32665, 30339, 26192, 29902, 28465, 33123, 42456, 32677, 29096, 31803]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
Topic: 0. Top: [29237, 30339, 33125, 33036, 39719, 28651, 29282, 32510, 34317, 43571, 29096, 30596, 37833, 34871, 33124, 27970, 45841, 32939, 30160, 35023]
Topic: 1. Top: [30339, 47238, 33036, 30252, 33123, 29237, 31298, 34317, 29684, 33176, 28016, 29096, 48735, 17231, 44121, 29902, 33124, 31397, 29282, 33125]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [30791, 32833, 33484, 32665, 43613, 27185, 44211, 38446, 20528, 35416, 25945, 20673, 34170, 28992, 29939, 40029, 42166, 26466, 39872, 35657]
Topic: 4. Top: [28172, 37130, 32833, 35842, 27624, 33826, 22422, 40029, 30597, 19656, 33123, 37692, 21650, 33036, 34531, 27066, 27300, 28701, 45727, 29939]
Topic: 5. Top: [32833, 21123, 33036, 19656, 35538, 33123, 41831, 25220, 32135, 31374, 35657, 25025, 37974, 46714, 18601, 47079, 27624, 30791, 41106, 28775]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [29282, 33123, 28701, 33036, 26745, 32510, 33125, 28695, 28995, 34871, 33176, 33124, 30160, 47238, 29728, 20164, 32833, 17194, 34317, 29784]
Topic: 8. Top: [28651, 34089, 27532, 33036, 30339, 37833, 25706, 26129, 30066, 29453, 24315, 34507, 17905, 29331, 29282, 52298, 33176, 43184, 30252, 27315]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [27587, 22099, 33707, 29592, 32833, 36303, 19828, 25943, 33036, 35331, 29559, 35657, 40521, 28068, 30152, 32135, 22107, 31228, 48622, 29834]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [19656, 29237, 52105, 21874, 47238, 33047, 33125, 32510, 29282, 26627, 32665, 30339, 26192, 29902, 28465, 33123, 42456, 32677, 29096, 31803]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.09582629123240377
sparse_theta_sp: -0.4472402357987704
decorrelation: 0.01
fix: 1000000000
SUCCESS: more good topics
DOWNFALL: more bad topics...
num_topics: {'good': 11, 'bad': 4, 'not_good': 9, 'total_bad': 15}
5

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8f7fd730>}
Topic: 0. Top: [28172, 32833, 33123, 33036, 34364, 42030, 28701, 22422, 27624, 35842, 40029, 47238, 28629, 26745, 21580, 33176, 17856, 44121, 32510, 19656]
Topic: 1. Top: [30791, 32833, 40029, 35416, 32665, 19656, 43613, 44211, 35657, 33123, 21123, 32135, 25945, 38446, 33826, 30597, 28393, 25943, 37130, 33036]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [33036, 29237, 35023, 33125, 30339, 21347, 32939, 29784, 32510, 27970, 30152, 46434, 33124, 34871, 20164, 39719, 29939, 30374, 43571, 30160]
Topic: 4. Top: [28651, 34089, 37833, 25706, 27532, 30339, 33036, 39719, 24315, 26129, 30596, 29453, 30066, 34507, 30252, 29096, 43571, 34317, 29237, 32510]
Topic: 5. Top: [29282, 28701, 32510, 33125, 29237, 30160, 28695, 33036, 26745, 32678, 34871, 33124, 30339, 17194, 20164, 34317, 39719, 27136, 33176, 28995]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [47238, 33123, 52105, 19656, 29237, 30339, 33125, 29902, 32510, 29282, 33176, 21874, 31298, 34317, 33047, 28695, 29096, 29784, 29331, 28995]
Topic: 8. Top: [28884, 30339, 29085, 46583, 20164, 31298, 43931, 33036, 30130, 29205, 19900, 31931, 29116, 21394, 29275, 27624, 30490, 32833, 33731, 33096]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [30339, 47238, 33036, 29237, 30252, 28016, 34317, 31298, 29096, 29684, 33123, 30887, 33176, 33124, 47035, 27030, 17231, 31397, 48735, 29282]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [33484, 27185, 20528, 28068, 32833, 28992, 20673, 32665, 42166, 26239, 25911, 35842, 29939, 39945, 38446, 22254, 26306, 50488, 30627, 27787]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
Topic: 0. Top: [28172, 32833, 33123, 33036, 34364, 42030, 28701, 22422, 27624, 35842, 40029, 47238, 28629, 26745, 21580, 33176, 17856, 44121, 32510, 19656]
Topic: 1. Top: [30791, 32833, 40029, 35416, 32665, 19656, 43613, 44211, 35657, 33123, 21123, 32135, 25945, 38446, 33826, 30597, 28393, 25943, 37130, 33036]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [33036, 29237, 35023, 33125, 30339, 21347, 32939, 29784, 32510, 27970, 30152, 46434, 33124, 34871, 20164, 39719, 29939, 30374, 43571, 30160]
Topic: 4. Top: [28651, 34089, 37833, 25706, 27532, 30339, 33036, 39719, 24315, 26129, 30596, 29453, 30066, 34507, 30252, 29096, 43571, 34317, 29237, 32510]
Topic: 5. Top: [29282, 28701, 32510, 33125, 29237, 30160, 28695, 33036, 26745, 32678, 34871, 33124, 30339, 17194, 20164, 34317, 39719, 27136, 33176, 28995]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [47238, 33123, 52105, 19656, 29237, 30339, 33125, 29902, 32510, 29282, 33176, 21874, 31298, 34317, 33047, 28695, 29096, 29784, 29331, 28995]
Topic: 8. Top: [28884, 30339, 29085, 46583, 20164, 31298, 43931, 33036, 30130, 29205, 19900, 31931, 29116, 21394, 29275, 27624, 30490, 32833, 33731, 33096]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [30339, 47238, 33036, 29237, 30252, 28016, 34317, 31298, 29096, 29684, 33123, 30887, 33176, 33124, 47035, 27030, 17231, 31397, 48735, 29282]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [33484, 27185, 20528, 28068, 32833, 28992, 20673, 32665, 42166, 26239, 25911, 35842, 29939, 39945, 38446, 22254, 26306, 50488, 30627, 27787]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1064736569248931
sparse_theta_sp: -0.4969335953319671
decorrelation: 0.01
fix: 1000000000
num_topics: {'good': 11, 'bad': 4, 'not_good': 9, 'total_bad': 19}
6

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b714251c0>}
Topic: 0. Top: [32833, 30791, 21123, 35657, 44211, 38446, 30597, 25945, 35538, 27086, 32135, 33036, 26306, 29592, 33123, 26809, 36303, 26864, 27587, 34729]
Topic: 1. Top: [29282, 33123, 33125, 29237, 47238, 32510, 28701, 52105, 33176, 26745, 28695, 30339, 33036, 29902, 28995, 34871, 34317, 31298, 30160, 33124]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [33036, 30339, 29237, 33125, 35023, 29282, 32510, 39719, 19828, 45841, 30152, 32939, 21347, 44259, 20164, 27970, 29259, 29559, 25420, 30596]
Topic: 4. Top: [33484, 20528, 27185, 32833, 32665, 37692, 42166, 20673, 29939, 28068, 28992, 38446, 30627, 34170, 25911, 27300, 26239, 43613, 29331, 28019]
Topic: 5. Top: [28172, 32833, 34364, 42030, 33036, 28629, 33123, 17856, 25025, 28701, 27624, 25342, 18601, 34095, 30152, 21580, 29272, 40736, 30444, 24278]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [30791, 40029, 32833, 43613, 33826, 35416, 25943, 32665, 19656, 25220, 39872, 28393, 41831, 32135, 37974, 33123, 46583, 52456, 37130, 33707]
Topic: 8. Top: [28651, 34089, 37833, 30339, 25706, 26129, 33036, 29237, 39719, 43571, 24315, 30252, 29096, 34317, 29282, 32510, 34507, 30876, 29205, 33124]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [30066, 17905, 19933, 33036, 27532, 30444, 32833, 52298, 49904, 28049, 30339, 33176, 51694, 29331, 39329, 28623, 32678, 29068, 29674, 26466]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [30339, 47238, 33036, 30252, 29237, 28016, 34317, 31298, 29096, 29684, 30887, 27030, 33123, 31397, 33176, 47035, 30795, 48735, 17231, 33124]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
Topic: 0. Top: [32833, 30791, 21123, 35657, 44211, 38446, 30597, 25945, 35538, 27086, 32135, 33036, 26306, 29592, 33123, 26809, 36303, 26864, 27587, 34729]
Topic: 1. Top: [29282, 33123, 33125, 29237, 47238, 32510, 28701, 52105, 33176, 26745, 28695, 30339, 33036, 29902, 28995, 34871, 34317, 31298, 30160, 33124]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [33036, 30339, 29237, 33125, 35023, 29282, 32510, 39719, 19828, 45841, 30152, 32939, 21347, 44259, 20164, 27970, 29259, 29559, 25420, 30596]
Topic: 4. Top: [33484, 20528, 27185, 32833, 32665, 37692, 42166, 20673, 29939, 28068, 28992, 38446, 30627, 34170, 25911, 27300, 26239, 43613, 29331, 28019]
Topic: 5. Top: [28172, 32833, 34364, 42030, 33036, 28629, 33123, 17856, 25025, 28701, 27624, 25342, 18601, 34095, 30152, 21580, 29272, 40736, 30444, 24278]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [30791, 40029, 32833, 43613, 33826, 35416, 25943, 32665, 19656, 25220, 39872, 28393, 41831, 32135, 37974, 33123, 46583, 52456, 37130, 33707]
Topic: 8. Top: [28651, 34089, 37833, 30339, 25706, 26129, 33036, 29237, 39719, 43571, 24315, 30252, 29096, 34317, 29282, 32510, 34507, 30876, 29205, 33124]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [30066, 17905, 19933, 33036, 27532, 30444, 32833, 52298, 49904, 28049, 30339, 33176, 51694, 29331, 39329, 28623, 32678, 29068, 29674, 26466]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [30339, 47238, 33036, 30252, 29237, 28016, 34317, 31298, 29096, 29684, 30887, 27030, 33123, 31397, 33176, 47035, 30795, 48735, 17231, 33124]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1064736569248931
sparse_theta_sp: -0.4969335953319671
decorrelation: 0.01
fix: 1000000000
SUCCESS: less bad topics
num_topics: {'good': 11, 'bad': 1, 'not_good': 9, 'total_bad': 20}
7

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b71431580>}
Topic: 0. Top: [40029, 30791, 32833, 35416, 29939, 19656, 34170, 33826, 33036, 32665, 28393, 25943, 33123, 33176, 25220, 26745, 26567, 29282, 27136, 29766]
Topic: 1. Top: [19656, 32510, 52105, 31298, 26192, 47238, 26627, 32677, 21874, 32929, 27662, 32665, 29891, 33123, 33125, 29237, 29282, 36376, 30490, 31803]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [30339, 32254, 47238, 33036, 30887, 37631, 30252, 28016, 37492, 37712, 49897, 30444, 30795, 28453, 17400, 45183, 29096, 48735, 32449, 28633]
Topic: 4. Top: [29237, 30339, 33125, 29282, 47238, 34317, 33036, 33123, 32510, 26745, 33124, 34871, 30160, 28695, 31298, 30252, 29902, 29096, 33176, 29684]
Topic: 5. Top: [33484, 32833, 38446, 27185, 20528, 43613, 32665, 37692, 30597, 44211, 30791, 37130, 34531, 20673, 30627, 42166, 25945, 28992, 28019, 29331]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [28651, 34089, 37833, 33036, 39719, 25706, 30339, 27532, 30596, 30066, 24315, 17946, 26129, 30152, 19828, 35023, 30374, 29331, 21347, 31484]
Topic: 8. Top: [32833, 33036, 34364, 42030, 33123, 18601, 25342, 44121, 25025, 28585, 31374, 50442, 30444, 34130, 47238, 26745, 38753, 32510, 46714, 31777]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [21123, 32833, 35657, 32135, 35538, 27587, 30791, 26809, 36303, 44211, 26864, 33707, 22099, 34729, 35604, 27086, 31747, 29592, 46583, 30750]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [28172, 28701, 33123, 52105, 29282, 28995, 47238, 33176, 28695, 28465, 32510, 29331, 36585, 35842, 27624, 21580, 21874, 30152, 28629, 33125]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
Topic: 0. Top: [40029, 30791, 32833, 35416, 29939, 19656, 34170, 33826, 33036, 32665, 28393, 25943, 33123, 33176, 25220, 26745, 26567, 29282, 27136, 29766]
Topic: 1. Top: [19656, 32510, 52105, 31298, 26192, 47238, 26627, 32677, 21874, 32929, 27662, 32665, 29891, 33123, 33125, 29237, 29282, 36376, 30490, 31803]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [30339, 32254, 47238, 33036, 30887, 37631, 30252, 28016, 37492, 37712, 49897, 30444, 30795, 28453, 17400, 45183, 29096, 48735, 32449, 28633]
Topic: 4. Top: [29237, 30339, 33125, 29282, 47238, 34317, 33036, 33123, 32510, 26745, 33124, 34871, 30160, 28695, 31298, 30252, 29902, 29096, 33176, 29684]
Topic: 5. Top: [33484, 32833, 38446, 27185, 20528, 43613, 32665, 37692, 30597, 44211, 30791, 37130, 34531, 20673, 30627, 42166, 25945, 28992, 28019, 29331]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [28651, 34089, 37833, 33036, 39719, 25706, 30339, 27532, 30596, 30066, 24315, 17946, 26129, 30152, 19828, 35023, 30374, 29331, 21347, 31484]
Topic: 8. Top: [32833, 33036, 34364, 42030, 33123, 18601, 25342, 44121, 25025, 28585, 31374, 50442, 30444, 34130, 47238, 26745, 38753, 32510, 46714, 31777]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [21123, 32833, 35657, 32135, 35538, 27587, 30791, 26809, 36303, 44211, 26864, 33707, 22099, 34729, 35604, 27086, 31747, 29592, 46583, 30750]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [28172, 28701, 33123, 52105, 29282, 28995, 47238, 33176, 28695, 28465, 32510, 29331, 36585, 35842, 27624, 21580, 21874, 30152, 28629, 33125]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1064736569248931
sparse_theta_sp: -0.4969335953319671
decorrelation: 0.01
fix: 1000000000
SUCCESS: more good topics
DOWNFALL: more bad topics...
num_topics: {'good': 12, 'bad': 4, 'not_good': 8, 'total_bad': 24}
8

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b714251c0>}
Topic: 0. Top: [28651, 34089, 30339, 26129, 33036, 30252, 34507, 29096, 19933, 52298, 25706, 29282, 43184, 32510, 48735, 34317, 37833, 29226, 33124, 43571]
Topic: 1. Top: [29282, 33123, 33125, 29237, 28701, 32510, 33036, 26745, 47238, 28695, 34871, 34317, 33176, 33124, 30339, 28995, 30160, 29902, 17194, 29728]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [30339, 47238, 29237, 33036, 30252, 34317, 31298, 29096, 29684, 33123, 28016, 31397, 19656, 30887, 33176, 29902, 33125, 52105, 17231, 47035]
Topic: 4. Top: [32833, 40029, 19656, 33036, 33123, 33826, 35416, 45727, 28393, 22422, 25220, 32981, 28368, 25911, 25025, 31374, 29939, 27300, 42030, 33176]
Topic: 5. Top: [37833, 28651, 29237, 30596, 27532, 17946, 29453, 31484, 25706, 33036, 27970, 39719, 43571, 33480, 27315, 32573, 29331, 32939, 30339, 23907]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [30791, 32833, 33484, 32665, 27185, 38446, 20528, 43613, 37692, 25945, 34170, 30597, 44211, 29939, 20673, 28992, 30627, 42166, 35416, 34531]
Topic: 8. Top: [28172, 33123, 34364, 28629, 33036, 47238, 44121, 28701, 24278, 34095, 17856, 31298, 33176, 30429, 25342, 27624, 30444, 34130, 50442, 46780]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [21123, 32833, 35657, 32135, 35538, 27587, 30791, 26809, 36303, 44211, 26864, 33707, 22099, 34729, 35604, 27086, 31747, 29592, 46583, 30750]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [30339, 33036, 45841, 35023, 29259, 19828, 39719, 44259, 30374, 32510, 33125, 32678, 25420, 20164, 30066, 32939, 30152, 29559, 32833, 21347]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
Topic: 0. Top: [28651, 34089, 30339, 26129, 33036, 30252, 34507, 29096, 19933, 52298, 25706, 29282, 43184, 32510, 48735, 34317, 37833, 29226, 33124, 43571]
Topic: 1. Top: [29282, 33123, 33125, 29237, 28701, 32510, 33036, 26745, 47238, 28695, 34871, 34317, 33176, 33124, 30339, 28995, 30160, 29902, 17194, 29728]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [30339, 47238, 29237, 33036, 30252, 34317, 31298, 29096, 29684, 33123, 28016, 31397, 19656, 30887, 33176, 29902, 33125, 52105, 17231, 47035]
Topic: 4. Top: [32833, 40029, 19656, 33036, 33123, 33826, 35416, 45727, 28393, 22422, 25220, 32981, 28368, 25911, 25025, 31374, 29939, 27300, 42030, 33176]
Topic: 5. Top: [37833, 28651, 29237, 30596, 27532, 17946, 29453, 31484, 25706, 33036, 27970, 39719, 43571, 33480, 27315, 32573, 29331, 32939, 30339, 23907]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [30791, 32833, 33484, 32665, 27185, 38446, 20528, 43613, 37692, 25945, 34170, 30597, 44211, 29939, 20673, 28992, 30627, 42166, 35416, 34531]
Topic: 8. Top: [28172, 33123, 34364, 28629, 33036, 47238, 44121, 28701, 24278, 34095, 17856, 31298, 33176, 30429, 25342, 27624, 30444, 34130, 50442, 46780]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [21123, 32833, 35657, 32135, 35538, 27587, 30791, 26809, 36303, 44211, 26864, 33707, 22099, 34729, 35604, 27086, 31747, 29592, 46583, 30750]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [30339, 33036, 45841, 35023, 29259, 19828, 39719, 44259, 30374, 32510, 33125, 32678, 25420, 20164, 30066, 32939, 30152, 29559, 32833, 21347]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.11978286404050471
sparse_theta_sp: -0.559050294748463
decorrelation: 0.01
fix: 1000000000
SUCCESS: less bad topics
num_topics: {'good': 12, 'bad': 3, 'not_good': 8, 'total_bad': 27}
9

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8f181d30>}
Topic: 0. Top: [20528, 32833, 27185, 37692, 33484, 32665, 28068, 29939, 42166, 30627, 28992, 30791, 25911, 27300, 35842, 41831, 34170, 28368, 27264, 32677]
Topic: 1. Top: [32833, 30791, 40029, 35416, 33826, 33123, 19656, 38446, 33484, 25945, 43613, 33036, 33176, 28172, 30597, 44211, 45727, 25220, 28393, 32665]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [33125, 29282, 33123, 29237, 47238, 34317, 30339, 33036, 26745, 32510, 34871, 28695, 28701, 29902, 33124, 30160, 33176, 17194, 31298, 29784]
Topic: 4. Top: [30339, 47238, 30252, 33036, 48735, 30887, 29096, 28016, 31298, 47035, 29684, 29237, 32254, 30795, 37492, 33176, 37631, 28633, 34317, 31397]
Topic: 5. Top: [52105, 29282, 21874, 28465, 36585, 33123, 33047, 29644, 28172, 19656, 47238, 32510, 35842, 27624, 28701, 33036, 33176, 30656, 30444, 29331]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [29237, 30339, 30130, 27187, 32833, 32510, 40820, 36226, 26627, 27934, 28252, 33036, 42456, 25163, 29282, 30066, 34130, 31186, 35057, 28884]
Topic: 8. Top: [28651, 34089, 37833, 33036, 30339, 39719, 25706, 32510, 30596, 43571, 29237, 29282, 17946, 24315, 19828, 25420, 30374, 27970, 45841, 21347]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [21123, 32833, 35657, 32135, 35538, 27587, 30791, 26809, 36303, 44211, 26864, 33707, 22099, 34729, 35604, 27086, 31747, 29592, 46583, 30750]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [27532, 30655, 51694, 52298, 17905, 42892, 28049, 29453, 42560, 19933, 30778, 37833, 28623, 40295, 32597, 51608, 28322, 24325, 34089, 24985]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
Topic: 0. Top: [20528, 32833, 27185, 37692, 33484, 32665, 28068, 29939, 42166, 30627, 28992, 30791, 25911, 27300, 35842, 41831, 34170, 28368, 27264, 32677]
Topic: 1. Top: [32833, 30791, 40029, 35416, 33826, 33123, 19656, 38446, 33484, 25945, 43613, 33036, 33176, 28172, 30597, 44211, 45727, 25220, 28393, 32665]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [33125, 29282, 33123, 29237, 47238, 34317, 30339, 33036, 26745, 32510, 34871, 28695, 28701, 29902, 33124, 30160, 33176, 17194, 31298, 29784]
Topic: 4. Top: [30339, 47238, 30252, 33036, 48735, 30887, 29096, 28016, 31298, 47035, 29684, 29237, 32254, 30795, 37492, 33176, 37631, 28633, 34317, 31397]
Topic: 5. Top: [52105, 29282, 21874, 28465, 36585, 33123, 33047, 29644, 28172, 19656, 47238, 32510, 35842, 27624, 28701, 33036, 33176, 30656, 30444, 29331]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [29237, 30339, 30130, 27187, 32833, 32510, 40820, 36226, 26627, 27934, 28252, 33036, 42456, 25163, 29282, 30066, 34130, 31186, 35057, 28884]
Topic: 8. Top: [28651, 34089, 37833, 33036, 30339, 39719, 25706, 32510, 30596, 43571, 29237, 29282, 17946, 24315, 19828, 25420, 30374, 27970, 45841, 21347]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [21123, 32833, 35657, 32135, 35538, 27587, 30791, 26809, 36303, 44211, 26864, 33707, 22099, 34729, 35604, 27086, 31747, 29592, 46583, 30750]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [27532, 30655, 51694, 52298, 17905, 42892, 28049, 29453, 42560, 19933, 30778, 37833, 28623, 40295, 32597, 51608, 28322, 24325, 34089, 24985]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.11978286404050471
sparse_theta_sp: -0.559050294748463
decorrelation: 0.01
fix: 1000000000
SUCCESS: more good topics
num_topics: {'good': 13, 'bad': 3, 'not_good': 7, 'total_bad': 30}
10

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b716af820>}
Topic: 0. Top: [28172, 32833, 34364, 33036, 42030, 28629, 33123, 17856, 27624, 28701, 33176, 25342, 30152, 40029, 25025, 50442, 22422, 34095, 35416, 44121]
Topic: 1. Top: [33123, 47238, 33125, 28701, 52105, 33176, 31298, 32510, 29237, 28695, 30339, 28995, 29902, 34871, 29282, 33124, 29728, 26745, 34317, 19656]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [29282, 29237, 33036, 32510, 33125, 20164, 35023, 32678, 17194, 32833, 45841, 27136, 19828, 30339, 32939, 26745, 30160, 39719, 34317, 27754]
Topic: 4. Top: [28651, 30596, 30339, 17946, 39719, 31484, 21347, 30374, 37833, 33036, 46434, 33480, 27315, 40395, 27970, 30152, 25420, 32436, 44259, 33125]
Topic: 5. Top: [30791, 32665, 33484, 32833, 27185, 20528, 38446, 43613, 29939, 42166, 35416, 34170, 20673, 44211, 28068, 37692, 28992, 29331, 19656, 30627]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [30339, 47238, 33036, 29237, 30252, 28016, 34317, 29684, 29096, 30887, 47035, 31298, 27030, 31397, 30795, 17231, 32254, 29282, 33123, 17194]
Topic: 8. Top: [28651, 34089, 30339, 37833, 25706, 33036, 26129, 30252, 34507, 43571, 39719, 24315, 29096, 29237, 30066, 34317, 30876, 29205, 29282, 32510]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [21123, 32833, 35657, 32135, 35538, 27587, 30791, 26809, 36303, 44211, 26864, 33707, 22099, 34729, 35604, 27086, 31747, 29592, 46583, 30750]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [27532, 30655, 51694, 52298, 17905, 42892, 28049, 29453, 42560, 19933, 30778, 37833, 28623, 40295, 32597, 51608, 28322, 24325, 34089, 24985]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
Topic: 0. Top: [28172, 32833, 34364, 33036, 42030, 28629, 33123, 17856, 27624, 28701, 33176, 25342, 30152, 40029, 25025, 50442, 22422, 34095, 35416, 44121]
Topic: 1. Top: [33123, 47238, 33125, 28701, 52105, 33176, 31298, 32510, 29237, 28695, 30339, 28995, 29902, 34871, 29282, 33124, 29728, 26745, 34317, 19656]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [29282, 29237, 33036, 32510, 33125, 20164, 35023, 32678, 17194, 32833, 45841, 27136, 19828, 30339, 32939, 26745, 30160, 39719, 34317, 27754]
Topic: 4. Top: [28651, 30596, 30339, 17946, 39719, 31484, 21347, 30374, 37833, 33036, 46434, 33480, 27315, 40395, 27970, 30152, 25420, 32436, 44259, 33125]
Topic: 5. Top: [30791, 32665, 33484, 32833, 27185, 20528, 38446, 43613, 29939, 42166, 35416, 34170, 20673, 44211, 28068, 37692, 28992, 29331, 19656, 30627]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [30339, 47238, 33036, 29237, 30252, 28016, 34317, 29684, 29096, 30887, 47035, 31298, 27030, 31397, 30795, 17231, 32254, 29282, 33123, 17194]
Topic: 8. Top: [28651, 34089, 30339, 37833, 25706, 33036, 26129, 30252, 34507, 43571, 39719, 24315, 29096, 29237, 30066, 34317, 30876, 29205, 29282, 32510]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [21123, 32833, 35657, 32135, 35538, 27587, 30791, 26809, 36303, 44211, 26864, 33707, 22099, 34729, 35604, 27086, 31747, 29592, 46583, 30750]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [27532, 30655, 51694, 52298, 17905, 42892, 28049, 29453, 42560, 19933, 30778, 37833, 28623, 40295, 32597, 51608, 28322, 24325, 34089, 24985]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1368947017605768
sparse_theta_sp: -0.638914622569672
decorrelation: 0.01
fix: 1000000000
num_topics: {'good': 13, 'bad': 3, 'not_good': 7, 'total_bad': 33}
11

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b714b0eb0>}
Topic: 0. Top: [19656, 52105, 47238, 32665, 21874, 33047, 30339, 29237, 31803, 26627, 42456, 35331, 33123, 31186, 32929, 36376, 27540, 32510, 27624, 31622]
Topic: 1. Top: [32833, 30791, 33484, 32665, 27185, 20528, 38446, 35416, 43613, 40029, 29939, 19656, 33826, 37692, 25945, 34170, 44211, 20673, 42166, 45727]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [33036, 20164, 40820, 28748, 32678, 30444, 36226, 22209, 27934, 38087, 28872, 26095, 32833, 23862, 29834, 30339, 29282, 28016, 27643, 33096]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 43571, 17946, 24315, 29096, 26129, 30374, 19828, 21347, 31484, 25420, 30066, 48622]
Topic: 5. Top: [29282, 29237, 33125, 32510, 28701, 30339, 34317, 33036, 34871, 26745, 28695, 33124, 30160, 33176, 28995, 27136, 29902, 17194, 29728, 29784]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [28172, 33123, 34364, 32833, 28701, 33036, 47238, 28629, 32510, 28995, 17856, 33176, 21580, 26745, 22422, 42030, 52105, 30152, 44121, 31298]
Topic: 8. Top: [47238, 30339, 33036, 30252, 33123, 31298, 34317, 29237, 28016, 29096, 29684, 33176, 31397, 48735, 30887, 17231, 27030, 33124, 47035, 30795]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [21123, 32833, 35657, 32135, 35538, 27587, 30791, 26809, 36303, 44211, 26864, 33707, 22099, 34729, 35604, 27086, 31747, 29592, 46583, 30750]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [27532, 30655, 51694, 52298, 17905, 42892, 28049, 29453, 42560, 19933, 30778, 37833, 28623, 40295, 32597, 51608, 28322, 24325, 34089, 24985]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
Topic: 0. Top: [19656, 52105, 47238, 32665, 21874, 33047, 30339, 29237, 31803, 26627, 42456, 35331, 33123, 31186, 32929, 36376, 27540, 32510, 27624, 31622]
Topic: 1. Top: [32833, 30791, 33484, 32665, 27185, 20528, 38446, 35416, 43613, 40029, 29939, 19656, 33826, 37692, 25945, 34170, 44211, 20673, 42166, 45727]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [33036, 20164, 40820, 28748, 32678, 30444, 36226, 22209, 27934, 38087, 28872, 26095, 32833, 23862, 29834, 30339, 29282, 28016, 27643, 33096]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 43571, 17946, 24315, 29096, 26129, 30374, 19828, 21347, 31484, 25420, 30066, 48622]
Topic: 5. Top: [29282, 29237, 33125, 32510, 28701, 30339, 34317, 33036, 34871, 26745, 28695, 33124, 30160, 33176, 28995, 27136, 29902, 17194, 29728, 29784]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [28172, 33123, 34364, 32833, 28701, 33036, 47238, 28629, 32510, 28995, 17856, 33176, 21580, 26745, 22422, 42030, 52105, 30152, 44121, 31298]
Topic: 8. Top: [47238, 30339, 33036, 30252, 33123, 31298, 34317, 29237, 28016, 29096, 29684, 33176, 31397, 48735, 30887, 17231, 27030, 33124, 47035, 30795]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [21123, 32833, 35657, 32135, 35538, 27587, 30791, 26809, 36303, 44211, 26864, 33707, 22099, 34729, 35604, 27086, 31747, 29592, 46583, 30750]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [27532, 30655, 51694, 52298, 17905, 42892, 28049, 29453, 42560, 19933, 30778, 37833, 28623, 40295, 32597, 51608, 28322, 24325, 34089, 24985]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1368947017605768
sparse_theta_sp: -0.638914622569672
decorrelation: 0.01
fix: 1000000000
SUCCESS: less bad topics
num_topics: {'good': 13, 'bad': 2, 'not_good': 7, 'total_bad': 35}
12

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b7148d400>}
Topic: 0. Top: [47238, 30339, 30252, 33036, 33123, 31298, 29237, 33176, 34317, 28016, 29096, 29684, 30887, 48735, 31397, 30795, 17231, 44121, 37492, 37631]
Topic: 1. Top: [28172, 32833, 33036, 42030, 28629, 33123, 28701, 35842, 27624, 21580, 22422, 30152, 25025, 24278, 30656, 34095, 32510, 25342, 29272, 30444]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [19656, 52105, 47238, 33123, 29282, 33047, 32665, 26192, 32510, 26627, 33176, 45727, 32677, 29902, 31803, 28465, 27624, 29237, 32929, 27970]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 29237, 43571, 24315, 17946, 26129, 32510, 29096, 27970, 30252, 31484, 30066, 30374]
Topic: 5. Top: [33125, 29237, 29282, 30339, 32510, 28701, 33036, 28695, 34317, 47238, 26745, 33123, 34871, 33124, 30160, 29116, 31298, 29902, 20164, 28995]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [30791, 32833, 33484, 32665, 20528, 27185, 38446, 43613, 35416, 29939, 37692, 33826, 25945, 37130, 34170, 19656, 40029, 30597, 44211, 34531]
Topic: 8. Top: [45841, 33036, 29259, 35023, 29282, 39719, 20164, 47035, 27970, 33006, 32833, 38087, 27030, 44259, 30444, 33380, 31683, 33124, 28884, 32678]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [21123, 32833, 35657, 32135, 35538, 27587, 30791, 26809, 36303, 44211, 26864, 33707, 22099, 34729, 35604, 27086, 31747, 29592, 46583, 30750]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [27532, 30655, 51694, 52298, 17905, 42892, 28049, 29453, 42560, 19933, 30778, 37833, 28623, 40295, 32597, 51608, 28322, 24325, 34089, 24985]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
Topic: 0. Top: [47238, 30339, 30252, 33036, 33123, 31298, 29237, 33176, 34317, 28016, 29096, 29684, 30887, 48735, 31397, 30795, 17231, 44121, 37492, 37631]
Topic: 1. Top: [28172, 32833, 33036, 42030, 28629, 33123, 28701, 35842, 27624, 21580, 22422, 30152, 25025, 24278, 30656, 34095, 32510, 25342, 29272, 30444]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [19656, 52105, 47238, 33123, 29282, 33047, 32665, 26192, 32510, 26627, 33176, 45727, 32677, 29902, 31803, 28465, 27624, 29237, 32929, 27970]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 29237, 43571, 24315, 17946, 26129, 32510, 29096, 27970, 30252, 31484, 30066, 30374]
Topic: 5. Top: [33125, 29237, 29282, 30339, 32510, 28701, 33036, 28695, 34317, 47238, 26745, 33123, 34871, 33124, 30160, 29116, 31298, 29902, 20164, 28995]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [30791, 32833, 33484, 32665, 20528, 27185, 38446, 43613, 35416, 29939, 37692, 33826, 25945, 37130, 34170, 19656, 40029, 30597, 44211, 34531]
Topic: 8. Top: [45841, 33036, 29259, 35023, 29282, 39719, 20164, 47035, 27970, 33006, 32833, 38087, 27030, 44259, 30444, 33380, 31683, 33124, 28884, 32678]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [21123, 32833, 35657, 32135, 35538, 27587, 30791, 26809, 36303, 44211, 26864, 33707, 22099, 34729, 35604, 27086, 31747, 29592, 46583, 30750]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [27532, 30655, 51694, 52298, 17905, 42892, 28049, 29453, 42560, 19933, 30778, 37833, 28623, 40295, 32597, 51608, 28322, 24325, 34089, 24985]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1368947017605768
sparse_theta_sp: -0.638914622569672
decorrelation: 0.01
fix: 1000000000
num_topics: {'good': 13, 'bad': 2, 'not_good': 7, 'total_bad': 37}
13

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b7114a0d0>}
Topic: 0. Top: [52105, 29237, 19656, 33047, 21874, 26627, 32665, 47238, 29282, 32677, 32510, 29902, 31803, 30339, 32929, 26192, 31298, 27662, 42456, 29096]
Topic: 1. Top: [32833, 30791, 33484, 32665, 20528, 27185, 38446, 43613, 35416, 40029, 29939, 37692, 19656, 33826, 25945, 34170, 37130, 44211, 20673, 34531]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [28651, 34089, 37833, 30339, 39719, 33036, 29237, 25706, 30596, 43571, 24315, 32510, 26129, 17946, 27970, 31484, 29282, 33124, 29096, 30252]
Topic: 4. Top: [28172, 33123, 33036, 34364, 32833, 47238, 33176, 44121, 28701, 42030, 28995, 35416, 31298, 28629, 21580, 32510, 40029, 19656, 50442, 17856]
Topic: 5. Top: [29282, 33125, 33123, 29237, 47238, 30339, 32510, 26745, 34317, 33036, 28701, 28695, 33124, 34871, 30160, 33176, 29902, 29728, 29116, 17194]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [30339, 47238, 33036, 30252, 28016, 30887, 29237, 31298, 29096, 34317, 47035, 29684, 32254, 27030, 33176, 48735, 30795, 37492, 37631, 17231]
Topic: 8. Top: [33036, 19828, 30152, 32939, 46434, 48622, 29559, 29939, 40395, 45841, 30374, 32510, 38536, 25420, 30339, 20164, 29282, 29259, 33125, 44259]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [21123, 32833, 35657, 32135, 35538, 27587, 30791, 26809, 36303, 44211, 26864, 33707, 22099, 34729, 35604, 27086, 31747, 29592, 46583, 30750]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [27532, 30655, 51694, 52298, 17905, 42892, 28049, 29453, 42560, 19933, 30778, 37833, 28623, 40295, 32597, 51608, 28322, 24325, 34089, 24985]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
Topic: 0. Top: [52105, 29237, 19656, 33047, 21874, 26627, 32665, 47238, 29282, 32677, 32510, 29902, 31803, 30339, 32929, 26192, 31298, 27662, 42456, 29096]
Topic: 1. Top: [32833, 30791, 33484, 32665, 20528, 27185, 38446, 43613, 35416, 40029, 29939, 37692, 19656, 33826, 25945, 34170, 37130, 44211, 20673, 34531]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [28651, 34089, 37833, 30339, 39719, 33036, 29237, 25706, 30596, 43571, 24315, 32510, 26129, 17946, 27970, 31484, 29282, 33124, 29096, 30252]
Topic: 4. Top: [28172, 33123, 33036, 34364, 32833, 47238, 33176, 44121, 28701, 42030, 28995, 35416, 31298, 28629, 21580, 32510, 40029, 19656, 50442, 17856]
Topic: 5. Top: [29282, 33125, 33123, 29237, 47238, 30339, 32510, 26745, 34317, 33036, 28701, 28695, 33124, 34871, 30160, 33176, 29902, 29728, 29116, 17194]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [30339, 47238, 33036, 30252, 28016, 30887, 29237, 31298, 29096, 34317, 47035, 29684, 32254, 27030, 33176, 48735, 30795, 37492, 37631, 17231]
Topic: 8. Top: [33036, 19828, 30152, 32939, 46434, 48622, 29559, 29939, 40395, 45841, 30374, 32510, 38536, 25420, 30339, 20164, 29282, 29259, 33125, 44259]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [21123, 32833, 35657, 32135, 35538, 27587, 30791, 26809, 36303, 44211, 26864, 33707, 22099, 34729, 35604, 27086, 31747, 29592, 46583, 30750]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [27532, 30655, 51694, 52298, 17905, 42892, 28049, 29453, 42560, 19933, 30778, 37833, 28623, 40295, 32597, 51608, 28322, 24325, 34089, 24985]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1368947017605768
sparse_theta_sp: -0.638914622569672
decorrelation: 0.01
fix: 1000000000
num_topics: {'good': 13, 'bad': 2, 'not_good': 7, 'total_bad': 39}
14

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8b936af0>}
Topic: 0. Top: [33484, 38446, 27185, 20528, 32665, 32833, 25945, 37692, 44211, 30791, 20673, 42166, 28992, 26239, 34531, 29331, 26466, 28019, 34170, 39872]
Topic: 1. Top: [28651, 33036, 37833, 30339, 39719, 25706, 30596, 19828, 30066, 17946, 25420, 24315, 35023, 30152, 21347, 32939, 34089, 45841, 32510, 33125]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [30339, 47238, 33036, 30252, 31298, 28016, 48735, 29237, 29096, 30887, 33176, 29684, 32254, 30795, 37492, 37631, 33123, 27030, 33124, 30444]
Topic: 4. Top: [29237, 29282, 33125, 29096, 30339, 28651, 32510, 43571, 28701, 33036, 26745, 30160, 29902, 47238, 33124, 29116, 30876, 39719, 33731, 29597]
Topic: 5. Top: [29282, 34317, 30339, 33125, 47238, 33123, 32510, 34871, 29237, 33036, 17194, 28695, 30252, 33124, 26745, 17231, 29902, 31298, 26027, 35023]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [52105, 32665, 19656, 21874, 33047, 28465, 35331, 31186, 32929, 27624, 30656, 31803, 31622, 47238, 36585, 42456, 27662, 27540, 32677, 26627]
Topic: 8. Top: [33123, 28172, 28701, 33176, 33036, 32833, 28995, 28695, 32510, 26745, 47238, 34364, 40029, 29282, 52105, 35416, 30152, 30160, 31298, 21580]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [21123, 32833, 35657, 32135, 35538, 27587, 30791, 26809, 36303, 44211, 26864, 33707, 22099, 34729, 35604, 27086, 31747, 29592, 46583, 30750]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [27532, 30655, 51694, 52298, 17905, 42892, 28049, 29453, 42560, 19933, 30778, 37833, 28623, 40295, 32597, 51608, 28322, 24325, 34089, 24985]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
Topic: 0. Top: [33484, 38446, 27185, 20528, 32665, 32833, 25945, 37692, 44211, 30791, 20673, 42166, 28992, 26239, 34531, 29331, 26466, 28019, 34170, 39872]
Topic: 1. Top: [28651, 33036, 37833, 30339, 39719, 25706, 30596, 19828, 30066, 17946, 25420, 24315, 35023, 30152, 21347, 32939, 34089, 45841, 32510, 33125]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [30339, 47238, 33036, 30252, 31298, 28016, 48735, 29237, 29096, 30887, 33176, 29684, 32254, 30795, 37492, 37631, 33123, 27030, 33124, 30444]
Topic: 4. Top: [29237, 29282, 33125, 29096, 30339, 28651, 32510, 43571, 28701, 33036, 26745, 30160, 29902, 47238, 33124, 29116, 30876, 39719, 33731, 29597]
Topic: 5. Top: [29282, 34317, 30339, 33125, 47238, 33123, 32510, 34871, 29237, 33036, 17194, 28695, 30252, 33124, 26745, 17231, 29902, 31298, 26027, 35023]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [52105, 32665, 19656, 21874, 33047, 28465, 35331, 31186, 32929, 27624, 30656, 31803, 31622, 47238, 36585, 42456, 27662, 27540, 32677, 26627]
Topic: 8. Top: [33123, 28172, 28701, 33176, 33036, 32833, 28995, 28695, 32510, 26745, 47238, 34364, 40029, 29282, 52105, 35416, 30152, 30160, 31298, 21580]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [21123, 32833, 35657, 32135, 35538, 27587, 30791, 26809, 36303, 44211, 26864, 33707, 22099, 34729, 35604, 27086, 31747, 29592, 46583, 30750]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [27532, 30655, 51694, 52298, 17905, 42892, 28049, 29453, 42560, 19933, 30778, 37833, 28623, 40295, 32597, 51608, 28322, 24325, 34089, 24985]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1368947017605768
sparse_theta_sp: -0.638914622569672
decorrelation: 0.01
fix: 1000000000
DOWNFALL: more bad topics...
num_topics: {'good': 13, 'bad': 3, 'not_good': 7, 'total_bad': 42}
15

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b711390a0>}
Topic: 0. Top: [28651, 34089, 33036, 37833, 30339, 25706, 39719, 30596, 24315, 29096, 17946, 26129, 33125, 30066, 31484, 32510, 30374, 19828, 27970, 29205]
Topic: 1. Top: [28016, 47035, 27030, 36383, 30887, 33036, 49904, 32833, 29237, 29282, 45183, 27934, 40820, 33380, 30444, 30339, 29845, 51496, 28633, 32241]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [29282, 33125, 29237, 32510, 33123, 47238, 28701, 52105, 33036, 28695, 30339, 29902, 31298, 28995, 19656, 34871, 33176, 26745, 20164, 27970]
Topic: 4. Top: [29237, 30339, 34317, 29282, 33124, 35023, 32510, 30160, 43571, 30152, 26745, 26027, 38087, 32939, 34871, 39719, 33006, 44259, 33176, 28701]
Topic: 5. Top: [47238, 30339, 30252, 33036, 33123, 34317, 31298, 29684, 29237, 29096, 33176, 33124, 29116, 48735, 44121, 17231, 30795, 26745, 31397, 33125]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [32833, 30791, 33484, 32665, 20528, 27185, 38446, 35416, 43613, 29939, 37692, 37130, 40029, 19656, 33826, 25945, 34170, 30597, 44211, 34531]
Topic: 8. Top: [32833, 33036, 42030, 33123, 18601, 28585, 25342, 21580, 17856, 25025, 33176, 30444, 31374, 35416, 32510, 28701, 47238, 40736, 46714, 45727]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [21123, 32833, 35657, 32135, 35538, 27587, 30791, 26809, 36303, 44211, 26864, 33707, 22099, 34729, 35604, 27086, 31747, 29592, 46583, 30750]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [27532, 30655, 51694, 52298, 17905, 42892, 28049, 29453, 42560, 19933, 30778, 37833, 28623, 40295, 32597, 51608, 28322, 24325, 34089, 24985]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
Topic: 0. Top: [28651, 34089, 33036, 37833, 30339, 25706, 39719, 30596, 24315, 29096, 17946, 26129, 33125, 30066, 31484, 32510, 30374, 19828, 27970, 29205]
Topic: 1. Top: [28016, 47035, 27030, 36383, 30887, 33036, 49904, 32833, 29237, 29282, 45183, 27934, 40820, 33380, 30444, 30339, 29845, 51496, 28633, 32241]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [29282, 33125, 29237, 32510, 33123, 47238, 28701, 52105, 33036, 28695, 30339, 29902, 31298, 28995, 19656, 34871, 33176, 26745, 20164, 27970]
Topic: 4. Top: [29237, 30339, 34317, 29282, 33124, 35023, 32510, 30160, 43571, 30152, 26745, 26027, 38087, 32939, 34871, 39719, 33006, 44259, 33176, 28701]
Topic: 5. Top: [47238, 30339, 30252, 33036, 33123, 34317, 31298, 29684, 29237, 29096, 33176, 33124, 29116, 48735, 44121, 17231, 30795, 26745, 31397, 33125]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [32833, 30791, 33484, 32665, 20528, 27185, 38446, 35416, 43613, 29939, 37692, 37130, 40029, 19656, 33826, 25945, 34170, 30597, 44211, 34531]
Topic: 8. Top: [32833, 33036, 42030, 33123, 18601, 28585, 25342, 21580, 17856, 25025, 33176, 30444, 31374, 35416, 32510, 28701, 47238, 40736, 46714, 45727]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [21123, 32833, 35657, 32135, 35538, 27587, 30791, 26809, 36303, 44211, 26864, 33707, 22099, 34729, 35604, 27086, 31747, 29592, 46583, 30750]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [27532, 30655, 51694, 52298, 17905, 42892, 28049, 29453, 42560, 19933, 30778, 37833, 28623, 40295, 32597, 51608, 28322, 24325, 34089, 24985]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1368947017605768
sparse_theta_sp: -0.638914622569672
decorrelation: 0.01
fix: 1000000000
DOWNFALL: more bad topics...
num_topics: {'good': 13, 'bad': 4, 'not_good': 7, 'total_bad': 46}
16

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b714b0700>}
Topic: 0. Top: [28651, 30339, 34089, 37833, 39719, 33036, 29237, 25706, 30596, 43571, 32510, 17946, 24315, 30066, 26129, 30374, 34317, 29096, 27970, 25420]
Topic: 1. Top: [30791, 33484, 32665, 32833, 43613, 27185, 38446, 20528, 20673, 35416, 28992, 44211, 25945, 29939, 42166, 25220, 34170, 26239, 26567, 19656]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [29282, 33036, 32510, 20164, 28695, 28995, 28701, 32678, 30152, 32833, 29939, 30160, 27136, 27970, 33176, 31298, 33124, 32337, 38536, 31167]
Topic: 4. Top: [47238, 29237, 33123, 30339, 33125, 29282, 34317, 26745, 29902, 32510, 31298, 33176, 33036, 33124, 34871, 28701, 30252, 28695, 29096, 29684]
Topic: 5. Top: [28172, 32833, 34364, 42030, 33036, 28629, 18601, 33123, 17856, 25342, 25025, 28585, 27624, 34095, 29272, 21580, 30656, 40736, 24278, 30429]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [30339, 33036, 28016, 47238, 30887, 30252, 32254, 27030, 47035, 37492, 48735, 30795, 30444, 37631, 29096, 49897, 31298, 29684, 28633, 37712]
Topic: 8. Top: [32833, 37130, 35842, 37692, 30597, 33826, 27624, 40029, 34531, 33036, 27300, 22422, 19656, 21650, 27066, 30791, 50488, 26306, 33123, 41831]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [21123, 32833, 35657, 32135, 35538, 27587, 30791, 26809, 36303, 44211, 26864, 33707, 22099, 34729, 35604, 27086, 31747, 29592, 46583, 30750]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [27532, 30655, 51694, 52298, 17905, 42892, 28049, 29453, 42560, 19933, 30778, 37833, 28623, 40295, 32597, 51608, 28322, 24325, 34089, 24985]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
Topic: 0. Top: [28651, 30339, 34089, 37833, 39719, 33036, 29237, 25706, 30596, 43571, 32510, 17946, 24315, 30066, 26129, 30374, 34317, 29096, 27970, 25420]
Topic: 1. Top: [30791, 33484, 32665, 32833, 43613, 27185, 38446, 20528, 20673, 35416, 28992, 44211, 25945, 29939, 42166, 25220, 34170, 26239, 26567, 19656]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [29282, 33036, 32510, 20164, 28695, 28995, 28701, 32678, 30152, 32833, 29939, 30160, 27136, 27970, 33176, 31298, 33124, 32337, 38536, 31167]
Topic: 4. Top: [47238, 29237, 33123, 30339, 33125, 29282, 34317, 26745, 29902, 32510, 31298, 33176, 33036, 33124, 34871, 28701, 30252, 28695, 29096, 29684]
Topic: 5. Top: [28172, 32833, 34364, 42030, 33036, 28629, 18601, 33123, 17856, 25342, 25025, 28585, 27624, 34095, 29272, 21580, 30656, 40736, 24278, 30429]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [30339, 33036, 28016, 47238, 30887, 30252, 32254, 27030, 47035, 37492, 48735, 30795, 30444, 37631, 29096, 49897, 31298, 29684, 28633, 37712]
Topic: 8. Top: [32833, 37130, 35842, 37692, 30597, 33826, 27624, 40029, 34531, 33036, 27300, 22422, 19656, 21650, 27066, 30791, 50488, 26306, 33123, 41831]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [21123, 32833, 35657, 32135, 35538, 27587, 30791, 26809, 36303, 44211, 26864, 33707, 22099, 34729, 35604, 27086, 31747, 29592, 46583, 30750]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [27532, 30655, 51694, 52298, 17905, 42892, 28049, 29453, 42560, 19933, 30778, 37833, 28623, 40295, 32597, 51608, 28322, 24325, 34089, 24985]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1368947017605768
sparse_theta_sp: -0.638914622569672
decorrelation: 0.01
fix: 1000000000
SUCCESS: less bad topics
num_topics: {'good': 13, 'bad': 2, 'not_good': 7, 'total_bad': 48}
17

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b89449c10>}
Topic: 0. Top: [30339, 47238, 30252, 33036, 29237, 34317, 31298, 28016, 29096, 29684, 27030, 30887, 17231, 31397, 33123, 33176, 32254, 37492, 30795, 37631]
Topic: 1. Top: [28651, 34089, 30339, 26129, 33036, 37833, 25706, 30252, 34507, 29096, 43571, 29282, 29205, 30876, 32510, 30066, 33176, 33124, 48735, 34317]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [33123, 28701, 47238, 33036, 29282, 28172, 33176, 26745, 33125, 28695, 32510, 28995, 34871, 31298, 40029, 52105, 44121, 30160, 33124, 29784]
Topic: 4. Top: [52105, 19656, 21874, 32665, 47238, 29237, 33047, 32510, 28465, 36585, 29282, 27624, 31803, 31186, 29902, 31622, 32929, 30339, 26627, 29096]
Topic: 5. Top: [32833, 30791, 33484, 32665, 20528, 27185, 38446, 43613, 35416, 40029, 29939, 19656, 37692, 33826, 37130, 25945, 34170, 30597, 44211, 45727]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [30339, 33125, 39719, 33036, 28651, 29282, 29237, 45841, 32510, 20164, 35023, 30596, 34871, 37833, 34317, 25420, 21347, 17946, 19828, 29259]
Topic: 8. Top: [29237, 29282, 32510, 33036, 32678, 29116, 26745, 30160, 32833, 43571, 32711, 33125, 27136, 29902, 30130, 28016, 32939, 20814, 30152, 28995]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [21123, 32833, 35657, 32135, 35538, 27587, 30791, 26809, 36303, 44211, 26864, 33707, 22099, 34729, 35604, 27086, 31747, 29592, 46583, 30750]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [27532, 30655, 51694, 52298, 17905, 42892, 28049, 29453, 42560, 19933, 30778, 37833, 28623, 40295, 32597, 51608, 28322, 24325, 34089, 24985]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
Topic: 0. Top: [30339, 47238, 30252, 33036, 29237, 34317, 31298, 28016, 29096, 29684, 27030, 30887, 17231, 31397, 33123, 33176, 32254, 37492, 30795, 37631]
Topic: 1. Top: [28651, 34089, 30339, 26129, 33036, 37833, 25706, 30252, 34507, 29096, 43571, 29282, 29205, 30876, 32510, 30066, 33176, 33124, 48735, 34317]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [33123, 28701, 47238, 33036, 29282, 28172, 33176, 26745, 33125, 28695, 32510, 28995, 34871, 31298, 40029, 52105, 44121, 30160, 33124, 29784]
Topic: 4. Top: [52105, 19656, 21874, 32665, 47238, 29237, 33047, 32510, 28465, 36585, 29282, 27624, 31803, 31186, 29902, 31622, 32929, 30339, 26627, 29096]
Topic: 5. Top: [32833, 30791, 33484, 32665, 20528, 27185, 38446, 43613, 35416, 40029, 29939, 19656, 37692, 33826, 37130, 25945, 34170, 30597, 44211, 45727]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [30339, 33125, 39719, 33036, 28651, 29282, 29237, 45841, 32510, 20164, 35023, 30596, 34871, 37833, 34317, 25420, 21347, 17946, 19828, 29259]
Topic: 8. Top: [29237, 29282, 32510, 33036, 32678, 29116, 26745, 30160, 32833, 43571, 32711, 33125, 27136, 29902, 30130, 28016, 32939, 20814, 30152, 28995]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [21123, 32833, 35657, 32135, 35538, 27587, 30791, 26809, 36303, 44211, 26864, 33707, 22099, 34729, 35604, 27086, 31747, 29592, 46583, 30750]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [27532, 30655, 51694, 52298, 17905, 42892, 28049, 29453, 42560, 19933, 30778, 37833, 28623, 40295, 32597, 51608, 28322, 24325, 34089, 24985]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1368947017605768
sparse_theta_sp: -0.638914622569672
decorrelation: 0.01
fix: 1000000000
num_topics: {'good': 13, 'bad': 2, 'not_good': 7, 'total_bad': 50}
18

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8ed141c0>}
Topic: 0. Top: [33484, 27185, 20528, 38446, 32833, 37692, 32665, 28068, 42166, 20673, 28992, 29939, 34531, 30597, 37130, 27300, 30627, 25911, 26306, 35842]
Topic: 1. Top: [30791, 32833, 40029, 35416, 43613, 19656, 33826, 32665, 33123, 25945, 33036, 28393, 45727, 33176, 39872, 29939, 25220, 26567, 34170, 25943]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [28651, 30339, 34089, 37833, 33036, 39719, 25706, 29237, 30596, 43571, 32510, 24315, 17946, 29282, 30066, 26129, 33125, 25420, 30374, 21347]
Topic: 4. Top: [30339, 47238, 30252, 29237, 33036, 34317, 28016, 29096, 29684, 31298, 33176, 47035, 30887, 29282, 48735, 33123, 17231, 29902, 33124, 31397]
Topic: 5. Top: [29282, 29237, 33125, 32510, 33123, 30339, 33036, 47238, 28701, 26745, 34871, 28695, 29902, 20164, 28995, 34317, 31298, 30160, 33176, 17194]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [28172, 33123, 34364, 28701, 47238, 33036, 33176, 44121, 52105, 31298, 28629, 28995, 50442, 17856, 28695, 26745, 25342, 34095, 27624, 22422]
Topic: 8. Top: [33124, 26239, 33036, 32510, 28695, 32833, 30160, 40820, 27934, 34130, 28701, 36226, 38753, 30339, 26095, 34317, 30152, 38087, 29331, 46780]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [21123, 32833, 35657, 32135, 35538, 27587, 30791, 26809, 36303, 44211, 26864, 33707, 22099, 34729, 35604, 27086, 31747, 29592, 46583, 30750]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [27532, 30655, 51694, 52298, 17905, 42892, 28049, 29453, 42560, 19933, 30778, 37833, 28623, 40295, 32597, 51608, 28322, 24325, 34089, 24985]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
Topic: 0. Top: [33484, 27185, 20528, 38446, 32833, 37692, 32665, 28068, 42166, 20673, 28992, 29939, 34531, 30597, 37130, 27300, 30627, 25911, 26306, 35842]
Topic: 1. Top: [30791, 32833, 40029, 35416, 43613, 19656, 33826, 32665, 33123, 25945, 33036, 28393, 45727, 33176, 39872, 29939, 25220, 26567, 34170, 25943]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [28651, 30339, 34089, 37833, 33036, 39719, 25706, 29237, 30596, 43571, 32510, 24315, 17946, 29282, 30066, 26129, 33125, 25420, 30374, 21347]
Topic: 4. Top: [30339, 47238, 30252, 29237, 33036, 34317, 28016, 29096, 29684, 31298, 33176, 47035, 30887, 29282, 48735, 33123, 17231, 29902, 33124, 31397]
Topic: 5. Top: [29282, 29237, 33125, 32510, 33123, 30339, 33036, 47238, 28701, 26745, 34871, 28695, 29902, 20164, 28995, 34317, 31298, 30160, 33176, 17194]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [28172, 33123, 34364, 28701, 47238, 33036, 33176, 44121, 52105, 31298, 28629, 28995, 50442, 17856, 28695, 26745, 25342, 34095, 27624, 22422]
Topic: 8. Top: [33124, 26239, 33036, 32510, 28695, 32833, 30160, 40820, 27934, 34130, 28701, 36226, 38753, 30339, 26095, 34317, 30152, 38087, 29331, 46780]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [21123, 32833, 35657, 32135, 35538, 27587, 30791, 26809, 36303, 44211, 26864, 33707, 22099, 34729, 35604, 27086, 31747, 29592, 46583, 30750]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [27532, 30655, 51694, 52298, 17905, 42892, 28049, 29453, 42560, 19933, 30778, 37833, 28623, 40295, 32597, 51608, 28322, 24325, 34089, 24985]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1368947017605768
sparse_theta_sp: -0.638914622569672
decorrelation: 0.01
fix: 1000000000
DOWNFALL: more bad topics...
num_topics: {'good': 13, 'bad': 4, 'not_good': 7, 'total_bad': 54}
19

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b89449c10>}
Topic: 0. Top: [32833, 30791, 33484, 32665, 40029, 38446, 27185, 20528, 35416, 19656, 37130, 37692, 43613, 29939, 33826, 45727, 30597, 25945, 33123, 33036]
Topic: 1. Top: [28651, 34089, 37833, 30339, 39719, 25706, 29237, 43571, 33036, 17946, 24315, 26129, 29096, 29282, 32510, 34317, 30252, 30374, 34507, 30596]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [30339, 47238, 33036, 30252, 29237, 34317, 31298, 28016, 30887, 29684, 29096, 48735, 33123, 33176, 27030, 31397, 17231, 30795, 37492, 33124]
Topic: 4. Top: [28172, 34364, 35842, 27624, 28629, 32833, 33123, 17856, 29834, 21650, 42030, 28701, 34095, 22422, 33176, 24278, 25342, 30429, 49838, 40736]
Topic: 5. Top: [29282, 29237, 33125, 33123, 47238, 32510, 28701, 30339, 52105, 33176, 28695, 26745, 29902, 34317, 28995, 34871, 33036, 31298, 30160, 19656]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [33036, 19828, 30339, 20164, 29259, 21347, 32833, 44259, 45841, 29282, 33125, 27970, 32510, 29559, 35023, 25420, 31484, 32939, 33124, 38087]
Topic: 8. Top: [30152, 33036, 27187, 35023, 30130, 32833, 32711, 34130, 28884, 32939, 28748, 40395, 37202, 45183, 32510, 37168, 35388, 26691, 33124, 38753]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [21123, 32833, 35657, 32135, 35538, 27587, 30791, 26809, 36303, 44211, 26864, 33707, 22099, 34729, 35604, 27086, 31747, 29592, 46583, 30750]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [27532, 30655, 51694, 52298, 17905, 42892, 28049, 29453, 42560, 19933, 30778, 37833, 28623, 40295, 32597, 51608, 28322, 24325, 34089, 24985]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
Topic: 0. Top: [32833, 30791, 33484, 32665, 40029, 38446, 27185, 20528, 35416, 19656, 37130, 37692, 43613, 29939, 33826, 45727, 30597, 25945, 33123, 33036]
Topic: 1. Top: [28651, 34089, 37833, 30339, 39719, 25706, 29237, 43571, 33036, 17946, 24315, 26129, 29096, 29282, 32510, 34317, 30252, 30374, 34507, 30596]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [30339, 47238, 33036, 30252, 29237, 34317, 31298, 28016, 30887, 29684, 29096, 48735, 33123, 33176, 27030, 31397, 17231, 30795, 37492, 33124]
Topic: 4. Top: [28172, 34364, 35842, 27624, 28629, 32833, 33123, 17856, 29834, 21650, 42030, 28701, 34095, 22422, 33176, 24278, 25342, 30429, 49838, 40736]
Topic: 5. Top: [29282, 29237, 33125, 33123, 47238, 32510, 28701, 30339, 52105, 33176, 28695, 26745, 29902, 34317, 28995, 34871, 33036, 31298, 30160, 19656]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [33036, 19828, 30339, 20164, 29259, 21347, 32833, 44259, 45841, 29282, 33125, 27970, 32510, 29559, 35023, 25420, 31484, 32939, 33124, 38087]
Topic: 8. Top: [30152, 33036, 27187, 35023, 30130, 32833, 32711, 34130, 28884, 32939, 28748, 40395, 37202, 45183, 32510, 37168, 35388, 26691, 33124, 38753]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [21123, 32833, 35657, 32135, 35538, 27587, 30791, 26809, 36303, 44211, 26864, 33707, 22099, 34729, 35604, 27086, 31747, 29592, 46583, 30750]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [27532, 30655, 51694, 52298, 17905, 42892, 28049, 29453, 42560, 19933, 30778, 37833, 28623, 40295, 32597, 51608, 28322, 24325, 34089, 24985]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1368947017605768
sparse_theta_sp: -0.638914622569672
decorrelation: 0.01
fix: 1000000000
SUCCESS: less bad topics
num_topics: {'good': 13, 'bad': 1, 'not_good': 7, 'total_bad': 55}

In [31]:
1

1

In [32]:
! ls results/20newsgroups

ablation_study		      iterative_100.json	  plsa.json
bertopic		      iterative2_1000000000.json  plsa_with_cohs.json
bertopic.json		      iterative2_100000000.json   sparse.json
decorrelation.json	      iterative2_10000000.json	  sparse_with_cohs.json
decorrelation_with_cohs.json  iterative2_1000000.json	  tless.json
iterative_1000000.json	      iterative2_100000.json	  tless_with_cohs.json
iterative_100000.json	      lda.json
iterative_1000.json	      lda_with_cohs.json

In [117]:
! mkdir -p results/20newsgroups/ablation_study

In [118]:
results.keys()

dict_keys([(0, 1, 1), (1, 0, 1), (1, 1, 0), (1, 0, 0), (0, 1, 0), (0, 0, 1)])

In [33]:
for k, r in results.items():
    for s in r:
        s['scores']['coherence_20'] = float(s['scores']['coherence_20'])

In [120]:
'-'.join(str(i) for i in k)

'0-0-1'

In [34]:
for k, r in results.items():
    output_k = '-'.join(str(i) for i in k)
    with open(SAVE_FOLDER + f'/ablation_study/iterative_{DECORRELATION_TAU}_{output_k}.json', 'w') as f:
        f.write(
            json.dumps(r, indent=4)
        )

In [122]:
! ls results/20newsgroups/ablation_study

iterative_1000000_0-0-1.json  iterative_1000_1-0-0.json
iterative_1000000_0-1-0.json  iterative_1000_1-0-1.json
iterative_1000000_0-1-1.json  iterative_1000_1-1-0.json
iterative_1000000_1-0-0.json  iterative2_1000000_0-0-1.json
iterative_1000000_1-0-1.json  iterative2_1000000_0-1-0.json
iterative_1000000_1-1-0.json  iterative2_1000000_0-1-1.json
iterative_1000_0-0-1.json     iterative2_1000000_1-0-0.json
iterative_1000_0-1-0.json     iterative2_1000000_1-0-1.json
iterative_1000_0-1-1.json     iterative2_1000000_1-1-0.json

In [123]:
for k, r in results.items():
    print(k)
    print(r[-1]['scores'])
    print(r[-1]['num_topics'])
    print()

(0, 1, 1)
{'perplexity': 2298.86474609375, 'coherence_20': 1.7097599620715205, 'diversity_euclidean': 0.07696227654850847, 'diversity_jensenshannon': 0.75997374559108, 'diversity_hellinger': 0.8996516085590787, 'diversity_cosine': 0.8922071526632959}
{'good': 8, 'bad': 3, 'not_good': 12, 'total_bad': 68}

(1, 0, 1)
{'perplexity': 2464.59130859375, 'coherence_20': 1.8222803403386731, 'diversity_euclidean': 0.09665751707718807, 'diversity_jensenshannon': 0.7558104290820944, 'diversity_hellinger': 0.8931846991572905, 'diversity_cosine': 0.9294582819017179}
{'good': 19, 'bad': 1, 'not_good': 1, 'total_bad': 21}

(1, 1, 0)
{'perplexity': 2476.902099609375, 'coherence_20': 1.7674292440536103, 'diversity_euclidean': 0.09821210131545323, 'diversity_jensenshannon': 0.7519702519427854, 'diversity_hellinger': 0.8875734457352042, 'diversity_cosine': 0.9115068086898529}
{'good': 19, 'bad': 1, 'not_good': 1, 'total_bad': 12}

(1, 0, 0)
{'perplexity': 2399.752197265625, 'coherence_20': 1.5325914688550593, 'diversity_euclidean': 0.07490138772637295, 'diversity_jensenshannon': 0.7095305335488792, 'diversity_hellinger': 0.832024237302994, 'diversity_cosine': 0.8471760765519764}
{'good': 13, 'bad': 1, 'not_good': 7, 'total_bad': 55}

(0, 1, 0)
{'perplexity': 2328.061767578125, 'coherence_20': 1.8008291825808924, 'diversity_euclidean': 0.08520900327738347, 'diversity_jensenshannon': 0.7671476318157497, 'diversity_hellinger': 0.9083594872821399, 'diversity_cosine': 0.9088763072909929}
{'good': 9, 'bad': 3, 'not_good': 11, 'total_bad': 78}

(0, 0, 1)
{'perplexity': 2231.341552734375, 'coherence_20': 1.3688189898786884, 'diversity_euclidean': 0.06584085813975735, 'diversity_jensenshannon': 0.6905189220799871, 'diversity_hellinger': 0.8055085249051459, 'diversity_cosine': 0.8078962463747064}
{'good': 8, 'bad': 4, 'not_good': 12, 'total_bad': 63}

In [124]:
! ls $SAVE_FOLDER

ablation_study		iterative_100.json	    iterative2_100000.json
decorrelation.json	iterative2_1000000000.json  lda.json
iterative_1000000.json	iterative2_100000000.json   plsa.json
iterative_100000.json	iterative2_10000000.json    sparse.json
iterative_1000.json	iterative2_1000000.json     tless.json

In [107]:
! ls $SAVE_FOLDER

ablation_study		iterative_100.json	    iterative2_100000.json
decorrelation.json	iterative2_1000000000.json  lda.json
iterative_1000000.json	iterative2_100000000.json   plsa.json
iterative_100000.json	iterative2_10000000.json    sparse.json
iterative_1000.json	iterative2_1000000.json     tless.json

In [108]:
! tail -n 50 $SAVE_FOLDER/iterative2_1000000.json

            "17": 2.636592011876535,
            "18": 1.7554318141499257,
            "19": 1.640629444035244
        },
        "num_topics": {
            "good": 13,
            "bad": 4,
            "not_good": 7,
            "total_bad": 54
        }
    },
    {
        "scores": {
            "perplexity": 2399.75244140625,
            "coherence_20": 1.5422349498469412,
            "diversity_euclidean": 0.07473976332049242,
            "diversity_jensenshannon": 0.7098907759986864,
            "diversity_hellinger": 0.8325292643052555,
            "diversity_cosine": 0.8483379385827017
        },
        "topic_coherences": {
            "0": 1.00113211617019,
            "1": 1.3621768174895768,
            "2": 1.6694630947055196,
            "3": 0.901739498209401,
            "4": 0.9697594159537758,
            "5": 0.6067957005801524,
            "6": 1.8054658007396136,
            "7": 0.907673304571028,
            "8": 0.9312208318641825,
            "9": 1.6300267904928862,
            "10": 1.840761298075488,
            "11": 1.825026385744523,
            "12": 1.7073209789137267,
            "13": 1.8580910947101374,
            "14": 1.6809928119557065,
            "15": 2.0985972466959013,
            "16": 2.0158025400053132,
            "17": 2.636592011876535,
            "18": 1.7554318141499257,
            "19": 1.640629444035244
        },
        "num_topics": {
            "good": 13,
            "bad": 1,
            "not_good": 7,
            "total_bad": 55
        }
    }
]

In [109]:
! tail -n 50 $SAVE_FOLDER/iterative2_10000000.json

            "17": 2.636592011876535,
            "18": 1.7554318141499257,
            "19": 1.640629444035244
        },
        "num_topics": {
            "good": 13,
            "bad": 2,
            "not_good": 7,
            "total_bad": 45
        }
    },
    {
        "scores": {
            "perplexity": 2403.99267578125,
            "coherence_20": 1.573263970374759,
            "diversity_euclidean": 0.07375830564020532,
            "diversity_jensenshannon": 0.7124094332529214,
            "diversity_hellinger": 0.8359994991184351,
            "diversity_cosine": 0.855706460551422
        },
        "topic_coherences": {
            "0": 1.1082963221453308,
            "1": 1.4004677404363155,
            "2": 1.6549948867753843,
            "3": 0.9853736724876744,
            "4": 1.1166110279043346,
            "5": 0.6067957005801523,
            "6": 1.8054658007396136,
            "7": 1.0752934564635988,
            "8": 0.9390066126540663,
            "9": 1.6300267904928862,
            "10": 1.840761298075488,
            "11": 1.8250263857445232,
            "12": 1.7073209789137267,
            "13": 1.8580910947101374,
            "14": 1.6809928119557065,
            "15": 2.1822990173492216,
            "16": 2.0158025400053132,
            "17": 2.636592011876535,
            "18": 1.7554318141499257,
            "19": 1.640629444035244
        },
        "num_topics": {
            "good": 13,
            "bad": 1,
            "not_good": 7,
            "total_bad": 46
        }
    }
]

In [110]:
! tail -n 50 $SAVE_FOLDER/iterative2_100000000.json

            "17": 2.636592011876535,
            "18": 1.7554318141499257,
            "19": 1.640629444035244
        },
        "num_topics": {
            "good": 19,
            "bad": 1,
            "not_good": 1,
            "total_bad": 17
        }
    },
    {
        "scores": {
            "perplexity": 2536.84521484375,
            "coherence_20": 1.7657066593419635,
            "diversity_euclidean": 0.08474110227762996,
            "diversity_jensenshannon": 0.7364641673959812,
            "diversity_hellinger": 0.8673032015098073,
            "diversity_cosine": 0.8908660854388641
        },
        "topic_coherences": {
            "0": 1.6603571660847984,
            "1": 1.8608120102679044,
            "2": 0.6321317616434708,
            "3": 2.08647789775495,
            "4": 1.8032283276088727,
            "5": 1.696860620500633,
            "6": 1.8054658007396138,
            "7": 1.651973818044545,
            "8": 1.7787379471054157,
            "9": 1.6300267904928862,
            "10": 1.840761298075488,
            "11": 1.7128410994875463,
            "12": 1.7073209789137267,
            "13": 1.8580910947101374,
            "14": 1.6809928119557067,
            "15": 1.8595979533865477,
            "16": 2.0158025400053132,
            "17": 2.636592011876535,
            "18": 1.7554318141499257,
            "19": 1.640629444035244
        },
        "num_topics": {
            "good": 19,
            "bad": 1,
            "not_good": 1,
            "total_bad": 18
        }
    }
]

In [112]:
! tail -n 50 $SAVE_FOLDER/iterative2_1000000000.json

            "17": 2.636592011876535,
            "18": 1.7554318141499257,
            "19": 1.6167513780664968
        },
        "num_topics": {
            "good": 19,
            "bad": 1,
            "not_good": 1,
            "total_bad": 14
        }
    },
    {
        "scores": {
            "perplexity": 2509.298095703125,
            "coherence_20": 1.8004192080579677,
            "diversity_euclidean": 0.09672882730245023,
            "diversity_jensenshannon": 0.7499680063404501,
            "diversity_hellinger": 0.8856458799229798,
            "diversity_cosine": 0.9193192437631968
        },
        "topic_coherences": {
            "0": 1.6834217755146534,
            "1": 1.6636143961405991,
            "2": 1.9126025217315148,
            "3": 1.7636570949116437,
            "4": 1.6862600158085381,
            "5": 1.9193798353133522,
            "6": 2.2642665670036526,
            "7": 0.6104632760028169,
            "8": 2.091593575026202,
            "9": 1.8247858348648507,
            "10": 1.840761298075488,
            "11": 1.6209433277675254,
            "12": 1.7073209789137267,
            "13": 1.8580910947101374,
            "14": 1.780609558835392,
            "15": 1.7560352664409962,
            "16": 2.0158025400053132,
            "17": 2.636592011876535,
            "18": 1.7554318141499257,
            "19": 1.6167513780664968
        },
        "num_topics": {
            "good": 19,
            "bad": 1,
            "not_good": 1,
            "total_bad": 15
        }
    }
]

In [ ]:
DECORRELATION_TAUS = [100000, 1000000]  # Dangerous
DECORRELATION_TAUS = [10000000, 100000000, 1000000000]  # Dangerous

In [35]:
# DECORRELATION_TAU = 1000000
# DECORRELATION_TAU = 1000000000  # new best # TODO: maybe even higher?
DECORRELATION_TAU = 100000000

ALL_PARAMS = [
    # (0, 1, 1),
    (1, 0, 1),
    (1, 1, 0),

    (1, 0, 0),
    # (0, 1, 0),
    # (0, 0, 1),
]

In [36]:
results = dict()

DECORRELATOR_REGULARIZER_CLASS = DecorrelatorWithOtherPhiRegularizer2

#  Best: 100000000.0 55.63102213541697
# Close: 10000000.0 55.890380859375

for params in ALL_PARAMS:
    key = params
    results[key] = []

    print(key)

    prev_model = None
    good_topic_names = list()
    bad_topic_names = None
    not_good_topic_names = None
    bad_phi = None
    seed = 0

    while seed < MAX_NUM_TRAINS and len(good_topic_names) < NUM_TOPICS:
        print(seed)

        if seed == 0:
            prev_model = init_model_from_family(
                family=KnownModel.ARTM,
                dataset=dataset,
                main_modality=MAIN_MODALITY,
                num_topics=NUM_TOPICS,
                seed=seed,
                model_params={
                    'decorrelation_tau': 0.01,  # best values
                    'smooth_bcg_tau': 0.05,
                    'sparse_sp_tau': -0.05,
                }
            )

            for reg in prev_model.regularizers.data:
                print(f"{reg}: {prev_model.regularizers[reg].tau}")
    
            result = fit_and_compute_scores(prev_model, dataset)
            results[key].append(result)

            assert len(results[key]) == seed + 1
    
            
            good_topic_indices = [
                t for t, c in result['topic_coherences'].items() if t in TOPIC_INDICES and is_good(c)
            ]
            bad_topic_indices = [
                t for t, c in result['topic_coherences'].items() if t in TOPIC_INDICES and is_bad(c)
            ]
            not_good_topic_indices = [
                t for t in TOPIC_INDICES if t not in good_topic_indices
            ]
            
            phi = prev_model.get_phi()
            good_topic_names = [phi.columns[t] for t in good_topic_indices]
            bad_topic_names = [phi.columns[t] for t in bad_topic_indices]
            not_good_topic_names = [phi.columns[t] for t in not_good_topic_indices]

            assert len(good_topic_names) > 0
            assert len(bad_topic_names) > 0
            assert set(bad_topic_names) <= set(not_good_topic_names)
            assert not any(t in not_good_topic_names for t in good_topic_names)
            assert len(good_topic_names) + len(not_good_topic_names) == NUM_TOPICS

            assert 'num_topics' not in results[key][-1]

            results[key][-1]['num_topics'] = {
                'good': len(good_topic_names),
                'bad': len(bad_topic_names),
                'not_good': len(not_good_topic_names),
                'total_bad': len(bad_topic_names),
            }

            print(f"num_topics: {results[key][-1]['num_topics']}")

            seed += 1
            
            del result, phi
            model = None

        else:
            custom_regularizers = dict()
            
            if params[0]:
                fix_regularizer = FastFixPhiRegularizer(
                    name='fix',
                    parent_model=prev_model._model,
                    topic_names=good_topic_names,
                )
                custom_regularizers[fix_regularizer.name] = fix_regularizer
            else:
                fix_regularizer = None
            
            cur_bad_phi = prev_model._model.get_phi()[bad_topic_names]

            if bad_phi is None:
                bad_phi = cur_bad_phi
            else:
                # bad_phi.rename(
                #     columns={n: f'm1_{n}' for n in bad_topic_names}, inplace=True
                # )
                bad_phi = pd.concat([bad_phi, cur_bad_phi], axis=1)
    
            bad_phi = deepcopy(bad_phi)

            if params[1]:
                decorr_bad_regularizer = DECORRELATOR_REGULARIZER_CLASS(
                    name='ext_decorr_bad', tau=DECORRELATION_TAU,
                    topic_names=not_good_topic_names,
                    other_phi=bad_phi
                )
                custom_regularizers[decorr_bad_regularizer.name] = decorr_bad_regularizer
            else:
                decorr_bad_regularizer = None
            
            good_phi = prev_model._model.get_phi()[good_topic_names]
            good_phi = deepcopy(good_phi)

            if params[2]:
                decorr_good_regularizer = DECORRELATOR_REGULARIZER_CLASS(
                    name='ext_decorr_good', tau=DECORRELATION_TAU,
                    topic_names=not_good_topic_names,
                    other_phi=good_phi
                )
                custom_regularizers[decorr_good_regularizer.name] = decorr_good_regularizer
            else:
                decorr_good_regularizer = None
    
            new_model = init_model_from_family(
                family=KnownModel.ARTM,
                dataset=dataset,
                main_modality=MAIN_MODALITY,
                num_topics=NUM_TOPICS,
                seed=seed,
                specific_topic_names=not_good_topic_names,
                model_params={
                    'decorrelation_tau': 0.01,
                    'smooth_bcg_tau': 0.05,
                    'sparse_sp_tau': -0.05,
                }
            )
    
            new_result = fit_and_compute_scores(new_model, dataset, custom_regularizers=custom_regularizers)
            
            for reg in new_model.regularizers.data:
                print(f"{reg}: {new_model.regularizers[reg].tau}")
    
            for reg_name, reg in custom_regularizers.items():
                print(f"{reg_name}: {reg.tau}")
    
            
            results[key].append(new_result)

            assert len(results[key]) == seed + 1


            
            good_topic_indices = [
                t for t, c in new_result['topic_coherences'].items() if t in TOPIC_INDICES and is_good(c)
            ]
            bad_topic_indices = [
                t for t, c in new_result['topic_coherences'].items() if t in TOPIC_INDICES and is_bad(c)
            ]
            not_good_topic_indices = [
                t for t in TOPIC_INDICES if t not in good_topic_indices
            ]
            
            phi = new_model.get_phi()
            new_good_topic_names = [phi.columns[t] for t in good_topic_indices]
            new_bad_topic_names = [phi.columns[t] for t in bad_topic_indices]
            new_not_good_topic_names = [phi.columns[t] for t in not_good_topic_indices]

            # assert len(new_good_topic_names) > 0
            if len(new_good_topic_names) == 0:
                print('DOWNFALL: no good topics...')
            # assert len(new_bad_topic_names) > 0
            assert set(new_bad_topic_names) <= set(new_not_good_topic_names)
            assert not any(t in new_not_good_topic_names for t in new_good_topic_names)
            assert len(new_good_topic_names) + len(new_not_good_topic_names) == NUM_TOPICS

            # assert set(good_topic_names) <= set(new_good_topic_names)
            if not (set(good_topic_names) <= set(new_good_topic_names)):
                print('DOWNFALL: some good topics lost...')
            # assert len(new_bad_topic_names) <= len(bad_topic_names)

            if len(new_good_topic_names) > len(good_topic_names):
                print('SUCCESS: more good topics')
            if len(new_bad_topic_names) < len(bad_topic_names):
                print('SUCCESS: less bad topics')
            if len(new_bad_topic_names) > len(bad_topic_names):
                print('DOWNFALL: more bad topics...')
            if len(new_bad_topic_names) == 0:
                print('SUCCESS: no bad topics!')
    
            good_topic_names = new_good_topic_names
            bad_topic_names = new_bad_topic_names
            not_good_topic_names = new_not_good_topic_names

            
            assert 'num_topics' not in results[key][-1]

            results[key][-1]['num_topics'] = {
                'good': len(good_topic_names),
                'bad': len(bad_topic_names),
                'not_good': len(not_good_topic_names),
                'total_bad': bad_phi.shape[1] + len(bad_topic_names),
            }

            prev_model = new_model

            print(f"num_topics: {results[key][-1]['num_topics']}")

            seed += 1

(1, 0, 1)
0
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
Topic: 0. Top: [32833, 40029, 33826, 30791, 37692, 28368, 19656, 28999, 27300, 35416, 28775, 25945, 25220, 41831, 26306, 29939, 33036, 37130, 38446, 27264]
Topic: 1. Top: [36195, 42454, 30130, 34207, 27360, 30827, 32833, 24160, 32028, 31683, 47035, 48735, 40820, 27934, 33726, 29464, 28122, 36226, 29858, 38105]
Topic: 2. Top: [43613, 30791, 32833, 32665, 27086, 44211, 33123, 33484, 31997, 21123, 35416, 35657, 32135, 25289, 29331, 20673, 34170, 23885, 39872, 38446]
Topic: 3. Top: [30339, 28016, 47238, 29237, 33036, 30252, 29096, 27030, 47035, 30887, 34317, 32254, 29684, 31298, 31397, 17231, 30795, 37492, 37631, 48735]
Topic: 4. Top: [28172, 35842, 28465, 22422, 28629, 27624, 21650, 49838, 36585, 29272, 30656, 40295, 24278, 40736, 31622, 17856, 27066, 29834, 34095, 52105]
Topic: 5. Top: [29385, 32833, 32942, 28820, 36874, 29939, 50360, 46187, 31059, 24494, 44833, 37553, 28019, 35189, 27643, 25902, 28992, 39575, 35113, 23798]
Topic: 6. Top: [29453, 36383, 29116, 26627, 31186, 29237, 29282, 32833, 40999, 51040, 32510, 35708, 34014, 51902, 32678, 51496, 35189, 29096, 28406, 36928]
Topic: 7. Top: [28884, 35023, 33036, 20164, 29939, 27187, 27587, 51610, 30152, 24317, 29085, 28701, 33006, 37168, 36515, 27970, 38087, 33124, 21347, 32510]
Topic: 8. Top: [33123, 33125, 47238, 29282, 28701, 30339, 33036, 26745, 32510, 28695, 34317, 33176, 29237, 33124, 34871, 29902, 31298, 52105, 30160, 29728]
Topic: 9. Top: [32833, 34364, 33123, 33036, 42030, 25342, 50442, 25025, 44121, 31777, 35416, 18601, 40029, 46714, 33176, 46583, 19656, 27624, 31683, 38753]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [20528, 22254, 28068, 33484, 29939, 34170, 32677, 50360, 29328, 29998, 27185, 37083, 27787, 25911, 28992, 49264, 42166, 28193, 39945, 32833]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [28651, 30339, 34089, 37833, 33036, 39719, 29237, 25706, 27532, 30596, 30066, 29282, 43571, 32510, 24315, 17946, 34317, 26129, 30252, 29096]
Topic: 15. Top: [35331, 27540, 31186, 32665, 52105, 30331, 39921, 42456, 27624, 22209, 20197, 27307, 43613, 50360, 32929, 37263, 32028, 19656, 25859, 43025]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [49838, 37130, 28100, 34287, 29939, 32833, 26190, 28095, 24123, 30627, 30597, 51400, 34531, 28019, 32942, 30119, 40409, 32717, 31192, 36268]
Topic: 0. Top: [32833, 40029, 33826, 30791, 37692, 28368, 19656, 28999, 27300, 35416, 28775, 25945, 25220, 41831, 26306, 29939, 33036, 37130, 38446, 27264]
Topic: 1. Top: [36195, 42454, 30130, 34207, 27360, 30827, 32833, 24160, 32028, 31683, 47035, 48735, 40820, 27934, 33726, 29464, 28122, 36226, 29858, 38105]
Topic: 2. Top: [43613, 30791, 32833, 32665, 27086, 44211, 33123, 33484, 31997, 21123, 35416, 35657, 32135, 25289, 29331, 20673, 34170, 23885, 39872, 38446]
Topic: 3. Top: [30339, 28016, 47238, 29237, 33036, 30252, 29096, 27030, 47035, 30887, 34317, 32254, 29684, 31298, 31397, 17231, 30795, 37492, 37631, 48735]
Topic: 4. Top: [28172, 35842, 28465, 22422, 28629, 27624, 21650, 49838, 36585, 29272, 30656, 40295, 24278, 40736, 31622, 17856, 27066, 29834, 34095, 52105]
Topic: 5. Top: [29385, 32833, 32942, 28820, 36874, 29939, 50360, 46187, 31059, 24494, 44833, 37553, 28019, 35189, 27643, 25902, 28992, 39575, 35113, 23798]
Topic: 6. Top: [29453, 36383, 29116, 26627, 31186, 29237, 29282, 32833, 40999, 51040, 32510, 35708, 34014, 51902, 32678, 51496, 35189, 29096, 28406, 36928]
Topic: 7. Top: [28884, 35023, 33036, 20164, 29939, 27187, 27587, 51610, 30152, 24317, 29085, 28701, 33006, 37168, 36515, 27970, 38087, 33124, 21347, 32510]
Topic: 8. Top: [33123, 33125, 47238, 29282, 28701, 30339, 33036, 26745, 32510, 28695, 34317, 33176, 29237, 33124, 34871, 29902, 31298, 52105, 30160, 29728]
Topic: 9. Top: [32833, 34364, 33123, 33036, 42030, 25342, 50442, 25025, 44121, 31777, 35416, 18601, 40029, 46714, 33176, 46583, 19656, 27624, 31683, 38753]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [20528, 22254, 28068, 33484, 29939, 34170, 32677, 50360, 29328, 29998, 27185, 37083, 27787, 25911, 28992, 49264, 42166, 28193, 39945, 32833]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [28651, 30339, 34089, 37833, 33036, 39719, 29237, 25706, 27532, 30596, 30066, 29282, 43571, 32510, 24315, 17946, 34317, 26129, 30252, 29096]
Topic: 15. Top: [35331, 27540, 31186, 32665, 52105, 30331, 39921, 42456, 27624, 22209, 20197, 27307, 43613, 50360, 32929, 37263, 32028, 19656, 25859, 43025]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [49838, 37130, 28100, 34287, 29939, 32833, 26190, 28095, 24123, 30627, 30597, 51400, 34531, 28019, 32942, 30119, 40409, 32717, 31192, 36268]
num_topics: {'good': 6, 'bad': 2, 'not_good': 14, 'total_bad': 2}
1

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b89400b20>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f7b89425220>}
Topic: 0. Top: [29282, 33125, 33036, 32510, 30339, 28701, 28695, 34317, 34871, 20164, 26745, 17194, 33123, 30160, 33124, 29237, 47238, 33176, 33731, 35023]
Topic: 1. Top: [43613, 37130, 33484, 31997, 30627, 22254, 34170, 20673, 27185, 20528, 28992, 28068, 32677, 29939, 32665, 33826, 25289, 28100, 32833, 42166]
Topic: 2. Top: [39575, 28884, 50360, 38245, 34409, 20370, 31059, 27187, 31759, 25911, 24203, 29068, 43613, 30152, 35331, 32931, 24494, 29085, 31147, 29939]
Topic: 3. Top: [49838, 32833, 33123, 34287, 33036, 40029, 17856, 28172, 19656, 42030, 26190, 29939, 34364, 28100, 45727, 22422, 33176, 28095, 37130, 30444]
Topic: 4. Top: [52105, 19656, 30339, 21874, 42456, 33047, 32665, 27624, 33176, 47238, 28465, 29237, 29096, 29592, 27540, 33123, 31186, 32929, 36376, 35331]
Topic: 5. Top: [36383, 29453, 31186, 26627, 51040, 29116, 32833, 40999, 51902, 29237, 34014, 33799, 36928, 35708, 51496, 35750, 35189, 21129, 30130, 43613]
Topic: 6. Top: [32833, 30791, 21123, 35657, 27086, 35538, 43613, 32135, 32665, 33123, 35416, 26809, 28193, 36303, 28068, 22254, 32760, 29592, 19656, 29998]
Topic: 7. Top: [29237, 43571, 29096, 33125, 33036, 29902, 32510, 30596, 28701, 40395, 47035, 30339, 29597, 27970, 32711, 46434, 33124, 26745, 35057, 30876]
Topic: 8. Top: [32833, 30791, 38446, 40029, 25945, 35416, 44211, 20528, 46714, 32665, 29939, 33484, 37692, 19656, 33036, 26306, 45727, 25220, 39872, 29033]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 33036, 27643, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [46583, 21394, 52456, 33761, 24452, 29205, 27624, 29393, 43332, 40157, 23739, 24625, 45519, 35494, 48872, 41048, 24932, 17398, 29262, 29520]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 27532, 24315, 26129, 17946, 30374, 30252, 30066, 31484, 34317, 29453, 32510, 25420, 21347]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [47238, 30339, 33123, 33036, 31298, 30252, 34317, 33176, 29237, 29684, 33124, 44121, 26745, 31397, 48735, 29096, 17231, 33125, 28695, 29282]
Topic: 0. Top: [29282, 33125, 33036, 32510, 30339, 28701, 28695, 34317, 34871, 20164, 26745, 17194, 33123, 30160, 33124, 29237, 47238, 33176, 33731, 35023]
Topic: 1. Top: [43613, 37130, 33484, 31997, 30627, 22254, 34170, 20673, 27185, 20528, 28992, 28068, 32677, 29939, 32665, 33826, 25289, 28100, 32833, 42166]
Topic: 2. Top: [39575, 28884, 50360, 38245, 34409, 20370, 31059, 27187, 31759, 25911, 24203, 29068, 43613, 30152, 35331, 32931, 24494, 29085, 31147, 29939]
Topic: 3. Top: [49838, 32833, 33123, 34287, 33036, 40029, 17856, 28172, 19656, 42030, 26190, 29939, 34364, 28100, 45727, 22422, 33176, 28095, 37130, 30444]
Topic: 4. Top: [52105, 19656, 30339, 21874, 42456, 33047, 32665, 27624, 33176, 47238, 28465, 29237, 29096, 29592, 27540, 33123, 31186, 32929, 36376, 35331]
Topic: 5. Top: [36383, 29453, 31186, 26627, 51040, 29116, 32833, 40999, 51902, 29237, 34014, 33799, 36928, 35708, 51496, 35750, 35189, 21129, 30130, 43613]
Topic: 6. Top: [32833, 30791, 21123, 35657, 27086, 35538, 43613, 32135, 32665, 33123, 35416, 26809, 28193, 36303, 28068, 22254, 32760, 29592, 19656, 29998]
Topic: 7. Top: [29237, 43571, 29096, 33125, 33036, 29902, 32510, 30596, 28701, 40395, 47035, 30339, 29597, 27970, 32711, 46434, 33124, 26745, 35057, 30876]
Topic: 8. Top: [32833, 30791, 38446, 40029, 25945, 35416, 44211, 20528, 46714, 32665, 29939, 33484, 37692, 19656, 33036, 26306, 45727, 25220, 39872, 29033]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 33036, 27643, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [46583, 21394, 52456, 33761, 24452, 29205, 27624, 29393, 43332, 40157, 23739, 24625, 45519, 35494, 48872, 41048, 24932, 17398, 29262, 29520]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 27532, 24315, 26129, 17946, 30374, 30252, 30066, 31484, 34317, 29453, 32510, 25420, 21347]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [47238, 30339, 33123, 33036, 31298, 30252, 34317, 33176, 29237, 29684, 33124, 44121, 26745, 31397, 48735, 29096, 17231, 33125, 28695, 29282]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.0684473508802884
sparse_theta_sp: -0.319457311284836
decorrelation: 0.01
fix: 1000000000
ext_decorr_good: 100000000
SUCCESS: more good topics
DOWNFALL: more bad topics...
num_topics: {'good': 8, 'bad': 3, 'not_good': 12, 'total_bad': 5}
2

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b71774dc0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f7b8954ecd0>}
Topic: 0. Top: [49838, 28100, 26190, 32833, 28095, 29939, 32717, 40409, 37130, 42030, 51400, 28775, 25538, 19656, 40029, 29486, 33036, 36268, 28540, 30444]
Topic: 1. Top: [28172, 32833, 34364, 33036, 33123, 28629, 42030, 28701, 40295, 27624, 17856, 34095, 49838, 34130, 25025, 30152, 24278, 47238, 25342, 32510]
Topic: 2. Top: [36383, 51040, 40999, 32833, 29282, 27030, 51902, 29453, 28016, 51496, 22209, 34014, 49904, 33036, 30130, 29888, 26362, 31622, 28701, 30656]
Topic: 3. Top: [37833, 28651, 33036, 30596, 30339, 39719, 29453, 17946, 19828, 29259, 31484, 30066, 21347, 17905, 45841, 33480, 25706, 27985, 27970, 38087]
Topic: 4. Top: [30791, 32833, 44211, 21123, 35657, 32135, 32665, 27086, 43613, 35416, 38446, 35538, 33123, 40029, 25945, 39872, 19656, 26239, 34729, 25943]
Topic: 5. Top: [28651, 34089, 27532, 30339, 33036, 26129, 30252, 25706, 37833, 29096, 39719, 34507, 32510, 34317, 52298, 29282, 30876, 43184, 43571, 19933]
Topic: 6. Top: [43613, 33484, 31997, 22254, 39575, 25289, 50360, 29939, 26648, 32833, 20528, 20370, 38245, 32665, 28068, 34170, 27185, 49264, 24203, 20673]
Topic: 7. Top: [34287, 37692, 32833, 28019, 30627, 17856, 28999, 25466, 28368, 24123, 26306, 32942, 35416, 31964, 31192, 39661, 27264, 29939, 46951, 20528]
Topic: 8. Top: [29282, 29237, 33125, 32510, 28701, 20164, 30339, 34871, 28695, 33036, 29902, 33124, 28995, 29784, 35023, 26745, 27136, 30160, 33731, 34317]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 33036, 27643, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [31186, 29116, 27540, 26627, 29453, 35750, 43613, 39921, 20197, 31620, 27624, 35331, 35189, 35708, 36985, 52105, 26993, 27307, 42456, 43025]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [47238, 30339, 33123, 33036, 30252, 34317, 31298, 33176, 29237, 29684, 26745, 33125, 33124, 44121, 29096, 31397, 48735, 17231, 29282, 28695]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [37130, 33826, 35842, 27624, 32833, 30597, 30791, 40029, 27066, 34531, 21650, 22422, 33123, 19656, 50488, 30119, 27300, 37974, 39575, 28068]
Topic: 0. Top: [49838, 28100, 26190, 32833, 28095, 29939, 32717, 40409, 37130, 42030, 51400, 28775, 25538, 19656, 40029, 29486, 33036, 36268, 28540, 30444]
Topic: 1. Top: [28172, 32833, 34364, 33036, 33123, 28629, 42030, 28701, 40295, 27624, 17856, 34095, 49838, 34130, 25025, 30152, 24278, 47238, 25342, 32510]
Topic: 2. Top: [36383, 51040, 40999, 32833, 29282, 27030, 51902, 29453, 28016, 51496, 22209, 34014, 49904, 33036, 30130, 29888, 26362, 31622, 28701, 30656]
Topic: 3. Top: [37833, 28651, 33036, 30596, 30339, 39719, 29453, 17946, 19828, 29259, 31484, 30066, 21347, 17905, 45841, 33480, 25706, 27985, 27970, 38087]
Topic: 4. Top: [30791, 32833, 44211, 21123, 35657, 32135, 32665, 27086, 43613, 35416, 38446, 35538, 33123, 40029, 25945, 39872, 19656, 26239, 34729, 25943]
Topic: 5. Top: [28651, 34089, 27532, 30339, 33036, 26129, 30252, 25706, 37833, 29096, 39719, 34507, 32510, 34317, 52298, 29282, 30876, 43184, 43571, 19933]
Topic: 6. Top: [43613, 33484, 31997, 22254, 39575, 25289, 50360, 29939, 26648, 32833, 20528, 20370, 38245, 32665, 28068, 34170, 27185, 49264, 24203, 20673]
Topic: 7. Top: [34287, 37692, 32833, 28019, 30627, 17856, 28999, 25466, 28368, 24123, 26306, 32942, 35416, 31964, 31192, 39661, 27264, 29939, 46951, 20528]
Topic: 8. Top: [29282, 29237, 33125, 32510, 28701, 20164, 30339, 34871, 28695, 33036, 29902, 33124, 28995, 29784, 35023, 26745, 27136, 30160, 33731, 34317]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 33036, 27643, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [31186, 29116, 27540, 26627, 29453, 35750, 43613, 39921, 20197, 31620, 27624, 35331, 35189, 35708, 36985, 52105, 26993, 27307, 42456, 43025]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [47238, 30339, 33123, 33036, 30252, 34317, 31298, 33176, 29237, 29684, 26745, 33125, 33124, 44121, 29096, 31397, 48735, 17231, 29282, 28695]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [37130, 33826, 35842, 27624, 32833, 30597, 30791, 40029, 27066, 34531, 21650, 22422, 33123, 19656, 50488, 30119, 27300, 37974, 39575, 28068]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.07985524269366981
sparse_theta_sp: -0.37270019649897534
decorrelation: 0.01
fix: 1000000000
ext_decorr_good: 100000000
num_topics: {'good': 8, 'bad': 3, 'not_good': 12, 'total_bad': 8}
3

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8f744d00>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f7b71467550>}
Topic: 0. Top: [29282, 29237, 32510, 33125, 33036, 30339, 29116, 30160, 26745, 28701, 20164, 28695, 33123, 32678, 32833, 17194, 28995, 39719, 36383, 31298]
Topic: 1. Top: [28172, 27624, 32833, 28629, 40295, 35842, 42030, 34095, 25025, 21394, 49838, 40736, 25342, 34364, 26483, 29272, 31133, 33036, 30429, 46583]
Topic: 2. Top: [42456, 30339, 29237, 30444, 35331, 36226, 28252, 40820, 19933, 52105, 27934, 22772, 33036, 31228, 27307, 47035, 26095, 31264, 26584, 29644]
Topic: 3. Top: [28651, 30339, 34089, 37833, 33036, 39719, 29237, 29282, 25706, 27532, 30066, 34317, 32510, 43571, 33125, 24315, 30252, 26129, 30374, 29096]
Topic: 4. Top: [30791, 32833, 21123, 44211, 35657, 32135, 40029, 35538, 35416, 25945, 33123, 27086, 32665, 25943, 26567, 19656, 36303, 34729, 27587, 29592]
Topic: 5. Top: [33123, 47238, 52105, 28701, 33176, 28695, 33125, 33036, 32510, 19656, 31298, 26745, 44121, 46780, 28995, 34871, 33124, 34317, 29282, 30339]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 29237, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [49838, 37130, 32833, 28100, 29939, 34287, 33826, 40029, 37692, 19656, 30597, 28019, 28999, 26190, 33036, 34531, 28095, 35416, 30627, 31192]
Topic: 8. Top: [30339, 47238, 30252, 34317, 33036, 29237, 29684, 29096, 31298, 30887, 33123, 17231, 47035, 28016, 29902, 33124, 31397, 30795, 33125, 29282]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 33036, 27643, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [33036, 35023, 21347, 20164, 31484, 28701, 32833, 19828, 32939, 29559, 33006, 27970, 48622, 27315, 27587, 28884, 30339, 26027, 29939, 33124]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [33484, 32833, 32665, 20528, 27185, 30791, 43613, 42166, 20673, 28992, 28068, 29939, 38446, 34170, 26239, 22254, 30627, 39872, 26306, 39945]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
Topic: 0. Top: [29282, 29237, 32510, 33125, 33036, 30339, 29116, 30160, 26745, 28701, 20164, 28695, 33123, 32678, 32833, 17194, 28995, 39719, 36383, 31298]
Topic: 1. Top: [28172, 27624, 32833, 28629, 40295, 35842, 42030, 34095, 25025, 21394, 49838, 40736, 25342, 34364, 26483, 29272, 31133, 33036, 30429, 46583]
Topic: 2. Top: [42456, 30339, 29237, 30444, 35331, 36226, 28252, 40820, 19933, 52105, 27934, 22772, 33036, 31228, 27307, 47035, 26095, 31264, 26584, 29644]
Topic: 3. Top: [28651, 30339, 34089, 37833, 33036, 39719, 29237, 29282, 25706, 27532, 30066, 34317, 32510, 43571, 33125, 24315, 30252, 26129, 30374, 29096]
Topic: 4. Top: [30791, 32833, 21123, 44211, 35657, 32135, 40029, 35538, 35416, 25945, 33123, 27086, 32665, 25943, 26567, 19656, 36303, 34729, 27587, 29592]
Topic: 5. Top: [33123, 47238, 52105, 28701, 33176, 28695, 33125, 33036, 32510, 19656, 31298, 26745, 44121, 46780, 28995, 34871, 33124, 34317, 29282, 30339]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 29237, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [49838, 37130, 32833, 28100, 29939, 34287, 33826, 40029, 37692, 19656, 30597, 28019, 28999, 26190, 33036, 34531, 28095, 35416, 30627, 31192]
Topic: 8. Top: [30339, 47238, 30252, 34317, 33036, 29237, 29684, 29096, 31298, 30887, 33123, 17231, 47035, 28016, 29902, 33124, 31397, 30795, 33125, 29282]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 33036, 27643, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [33036, 35023, 21347, 20164, 31484, 28701, 32833, 19828, 32939, 29559, 33006, 27970, 48622, 27315, 27587, 28884, 30339, 26027, 29939, 33124]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [33484, 32833, 32665, 20528, 27185, 30791, 43613, 42166, 20673, 28992, 28068, 29939, 38446, 34170, 26239, 22254, 30627, 39872, 26306, 39945]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.07985524269366981
sparse_theta_sp: -0.37270019649897534
decorrelation: 0.01
fix: 1000000000
ext_decorr_good: 100000000
SUCCESS: more good topics
num_topics: {'good': 10, 'bad': 3, 'not_good': 10, 'total_bad': 11}
4

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b7165ca00>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f7b7167afd0>}
Topic: 0. Top: [29237, 30339, 33125, 33036, 39719, 28651, 29282, 32510, 34317, 43571, 30596, 29096, 37833, 34871, 27970, 33124, 45841, 32939, 35023, 30374]
Topic: 1. Top: [30339, 47238, 33036, 30252, 33123, 29237, 31298, 34317, 29684, 33176, 28016, 29096, 48735, 17231, 44121, 29902, 33124, 31397, 29282, 33125]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 28095, 29939, 37130, 28019, 32833, 40409, 51400, 30627, 30119, 31964, 36268, 23120, 28999, 17856, 25538]
Topic: 3. Top: [30791, 32833, 33484, 32665, 43613, 27185, 44211, 38446, 20528, 35416, 25945, 20673, 40029, 34170, 28992, 29939, 42166, 26466, 35657, 39872]
Topic: 4. Top: [28172, 37130, 32833, 35842, 27624, 33826, 22422, 40029, 30597, 21650, 33123, 19656, 37692, 33036, 34531, 27066, 27300, 28701, 45727, 50488]
Topic: 5. Top: [32833, 21123, 33036, 19656, 35538, 41831, 33123, 25220, 31374, 32135, 35657, 25025, 37974, 18601, 46714, 47079, 41106, 28775, 40029, 27624]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 29237, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [29282, 33123, 28701, 26745, 33036, 32510, 33125, 28695, 28995, 34871, 33176, 33124, 30160, 47238, 29728, 20164, 17194, 34317, 32833, 29237]
Topic: 8. Top: [28651, 34089, 27532, 33036, 37833, 25706, 30339, 26129, 30066, 24315, 29453, 34507, 17905, 29331, 52298, 29282, 43184, 30252, 27315, 33176]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 33036, 27643, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [27587, 22099, 33707, 29592, 36303, 19828, 25943, 32833, 35331, 33036, 29559, 40521, 35657, 22107, 31228, 32135, 28068, 48622, 30152, 29834]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [19656, 29237, 21874, 52105, 47238, 33047, 33125, 32510, 29282, 26627, 26192, 32665, 30339, 29902, 28465, 42456, 33123, 32677, 29096, 36585]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
Topic: 0. Top: [29237, 30339, 33125, 33036, 39719, 28651, 29282, 32510, 34317, 43571, 30596, 29096, 37833, 34871, 27970, 33124, 45841, 32939, 35023, 30374]
Topic: 1. Top: [30339, 47238, 33036, 30252, 33123, 29237, 31298, 34317, 29684, 33176, 28016, 29096, 48735, 17231, 44121, 29902, 33124, 31397, 29282, 33125]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 28095, 29939, 37130, 28019, 32833, 40409, 51400, 30627, 30119, 31964, 36268, 23120, 28999, 17856, 25538]
Topic: 3. Top: [30791, 32833, 33484, 32665, 43613, 27185, 44211, 38446, 20528, 35416, 25945, 20673, 40029, 34170, 28992, 29939, 42166, 26466, 35657, 39872]
Topic: 4. Top: [28172, 37130, 32833, 35842, 27624, 33826, 22422, 40029, 30597, 21650, 33123, 19656, 37692, 33036, 34531, 27066, 27300, 28701, 45727, 50488]
Topic: 5. Top: [32833, 21123, 33036, 19656, 35538, 41831, 33123, 25220, 31374, 32135, 35657, 25025, 37974, 18601, 46714, 47079, 41106, 28775, 40029, 27624]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 29237, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [29282, 33123, 28701, 26745, 33036, 32510, 33125, 28695, 28995, 34871, 33176, 33124, 30160, 47238, 29728, 20164, 17194, 34317, 32833, 29237]
Topic: 8. Top: [28651, 34089, 27532, 33036, 37833, 25706, 30339, 26129, 30066, 24315, 29453, 34507, 17905, 29331, 52298, 29282, 43184, 30252, 27315, 33176]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 33036, 27643, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [27587, 22099, 33707, 29592, 36303, 19828, 25943, 32833, 35331, 33036, 29559, 40521, 35657, 22107, 31228, 32135, 28068, 48622, 30152, 29834]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [19656, 29237, 21874, 52105, 47238, 33047, 33125, 32510, 29282, 26627, 26192, 32665, 30339, 29902, 28465, 42456, 33123, 32677, 29096, 36585]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.09582629123240377
sparse_theta_sp: -0.4472402357987704
decorrelation: 0.01
fix: 1000000000
ext_decorr_good: 100000000
DOWNFALL: more bad topics...
num_topics: {'good': 10, 'bad': 4, 'not_good': 10, 'total_bad': 15}
5

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b716be910>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f7b89400b20>}
Topic: 0. Top: [28172, 32833, 33123, 33036, 42030, 34364, 35842, 49838, 22422, 28701, 27624, 28629, 40295, 21650, 17856, 21580, 26745, 25342, 30444, 25025]
Topic: 1. Top: [32833, 49838, 37130, 40029, 28100, 29939, 30791, 34287, 19656, 35416, 33826, 33123, 37692, 30627, 30597, 33036, 28999, 21123, 28019, 26190]
Topic: 2. Top: [29282, 33125, 29237, 33123, 32510, 33036, 28701, 26745, 30339, 28695, 34871, 33124, 47238, 34317, 30160, 33176, 28995, 20164, 29902, 17194]
Topic: 3. Top: [30791, 32833, 33484, 38446, 44211, 32665, 43613, 25945, 35657, 27587, 34170, 26239, 20673, 33123, 26809, 46714, 28019, 35538, 32135, 32343]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 29237, 29096, 21347, 29453]
Topic: 5. Top: [29259, 19828, 27532, 40820, 28701, 17905, 30655, 29559, 32678, 22099, 48622, 45841, 25163, 42892, 32510, 34966, 27754, 26095, 17398, 35708]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 29237, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [19656, 47238, 52105, 21874, 33047, 33123, 28465, 32510, 32665, 42456, 30339, 26192, 31298, 29902, 33176, 36585, 27624, 29331, 30656, 31186]
Topic: 8. Top: [46583, 20164, 30339, 29085, 29275, 31298, 43931, 21394, 31931, 29205, 28884, 33707, 33036, 24684, 27624, 33096, 19900, 33761, 28830, 38087]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 33036, 27643, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [30339, 47238, 33036, 30252, 29237, 34317, 28016, 31298, 29096, 29684, 30887, 47035, 33176, 33123, 27030, 48735, 31397, 33124, 17231, 30795]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [20528, 27185, 28068, 28992, 42166, 33484, 32833, 32665, 39945, 27787, 25911, 26306, 29939, 35842, 29834, 52456, 22980, 39872, 22254, 49264]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
Topic: 0. Top: [28172, 32833, 33123, 33036, 42030, 34364, 35842, 49838, 22422, 28701, 27624, 28629, 40295, 21650, 17856, 21580, 26745, 25342, 30444, 25025]
Topic: 1. Top: [32833, 49838, 37130, 40029, 28100, 29939, 30791, 34287, 19656, 35416, 33826, 33123, 37692, 30627, 30597, 33036, 28999, 21123, 28019, 26190]
Topic: 2. Top: [29282, 33125, 29237, 33123, 32510, 33036, 28701, 26745, 30339, 28695, 34871, 33124, 47238, 34317, 30160, 33176, 28995, 20164, 29902, 17194]
Topic: 3. Top: [30791, 32833, 33484, 38446, 44211, 32665, 43613, 25945, 35657, 27587, 34170, 26239, 20673, 33123, 26809, 46714, 28019, 35538, 32135, 32343]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 29237, 29096, 21347, 29453]
Topic: 5. Top: [29259, 19828, 27532, 40820, 28701, 17905, 30655, 29559, 32678, 22099, 48622, 45841, 25163, 42892, 32510, 34966, 27754, 26095, 17398, 35708]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 29237, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [19656, 47238, 52105, 21874, 33047, 33123, 28465, 32510, 32665, 42456, 30339, 26192, 31298, 29902, 33176, 36585, 27624, 29331, 30656, 31186]
Topic: 8. Top: [46583, 20164, 30339, 29085, 29275, 31298, 43931, 21394, 31931, 29205, 28884, 33707, 33036, 24684, 27624, 33096, 19900, 33761, 28830, 38087]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 33036, 27643, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [30339, 47238, 33036, 30252, 29237, 34317, 28016, 31298, 29096, 29684, 30887, 47035, 33176, 33123, 27030, 48735, 31397, 33124, 17231, 30795]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [20528, 27185, 28068, 28992, 42166, 33484, 32833, 32665, 39945, 27787, 25911, 26306, 29939, 35842, 29834, 52456, 22980, 39872, 22254, 49264]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.09582629123240377
sparse_theta_sp: -0.4472402357987704
decorrelation: 0.01
fix: 1000000000
ext_decorr_good: 100000000
SUCCESS: more good topics
SUCCESS: less bad topics
num_topics: {'good': 11, 'bad': 3, 'not_good': 9, 'total_bad': 18}
6

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b890b6850>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f7b71641a00>}
Topic: 0. Top: [32833, 37130, 27185, 20528, 30791, 29939, 30627, 37692, 33826, 30597, 32665, 34531, 35416, 38446, 32677, 28999, 19656, 42166, 28068, 29331]
Topic: 1. Top: [29282, 33123, 33125, 29237, 28701, 47238, 32510, 26745, 30339, 28695, 34871, 28995, 33176, 52105, 33036, 34317, 29902, 30160, 17194, 33124]
Topic: 2. Top: [33484, 20673, 38446, 26239, 28992, 43613, 28019, 32665, 31502, 32833, 39945, 44211, 40820, 36226, 21001, 27985, 25391, 20528, 37027, 20164]
Topic: 3. Top: [33036, 35023, 33125, 19828, 29282, 32510, 29559, 29237, 29259, 30152, 45841, 20164, 30339, 48622, 29939, 44259, 31298, 32939, 28884, 33124]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 29237, 29096, 21347, 29453]
Topic: 5. Top: [49838, 28172, 34287, 32833, 28100, 26190, 29939, 42030, 40029, 28095, 17856, 19656, 31374, 32717, 33036, 30119, 33123, 40409, 24123, 27624]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 29237, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [30791, 32833, 21123, 35657, 40029, 32135, 32665, 25943, 44211, 35416, 35538, 43613, 33123, 39872, 26567, 19656, 36303, 28393, 27086, 33707]
Topic: 8. Top: [30339, 47238, 30252, 29096, 34317, 29237, 30887, 33036, 29684, 32254, 31298, 33123, 29902, 47035, 30795, 45934, 29592, 17231, 37492, 37712]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 33036, 27643, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [34364, 32833, 24278, 40295, 38753, 35185, 34130, 28585, 50442, 36922, 30429, 25342, 34095, 29393, 29397, 30444, 47238, 27624, 44121, 30806]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [33036, 33176, 48735, 31298, 44121, 29282, 27030, 47238, 28016, 33124, 52105, 30252, 31397, 30339, 33123, 34809, 29644, 22363, 28268, 26060]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
Topic: 0. Top: [32833, 37130, 27185, 20528, 30791, 29939, 30627, 37692, 33826, 30597, 32665, 34531, 35416, 38446, 32677, 28999, 19656, 42166, 28068, 29331]
Topic: 1. Top: [29282, 33123, 33125, 29237, 28701, 47238, 32510, 26745, 30339, 28695, 34871, 28995, 33176, 52105, 33036, 34317, 29902, 30160, 17194, 33124]
Topic: 2. Top: [33484, 20673, 38446, 26239, 28992, 43613, 28019, 32665, 31502, 32833, 39945, 44211, 40820, 36226, 21001, 27985, 25391, 20528, 37027, 20164]
Topic: 3. Top: [33036, 35023, 33125, 19828, 29282, 32510, 29559, 29237, 29259, 30152, 45841, 20164, 30339, 48622, 29939, 44259, 31298, 32939, 28884, 33124]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 29237, 29096, 21347, 29453]
Topic: 5. Top: [49838, 28172, 34287, 32833, 28100, 26190, 29939, 42030, 40029, 28095, 17856, 19656, 31374, 32717, 33036, 30119, 33123, 40409, 24123, 27624]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 29237, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [30791, 32833, 21123, 35657, 40029, 32135, 32665, 25943, 44211, 35416, 35538, 43613, 33123, 39872, 26567, 19656, 36303, 28393, 27086, 33707]
Topic: 8. Top: [30339, 47238, 30252, 29096, 34317, 29237, 30887, 33036, 29684, 32254, 31298, 33123, 29902, 47035, 30795, 45934, 29592, 17231, 37492, 37712]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 33036, 27643, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [34364, 32833, 24278, 40295, 38753, 35185, 34130, 28585, 50442, 36922, 30429, 25342, 34095, 29393, 29397, 30444, 47238, 27624, 44121, 30806]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [33036, 33176, 48735, 31298, 44121, 29282, 27030, 47238, 28016, 33124, 52105, 30252, 31397, 30339, 33123, 34809, 29644, 22363, 28268, 26060]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1064736569248931
sparse_theta_sp: -0.4969335953319671
decorrelation: 0.01
fix: 1000000000
ext_decorr_good: 100000000
SUCCESS: less bad topics
num_topics: {'good': 11, 'bad': 2, 'not_good': 9, 'total_bad': 20}
7

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8ed52be0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f7b8ef8d820>}
Topic: 0. Top: [30791, 32833, 40029, 35416, 32665, 19656, 28999, 33826, 29939, 43613, 34170, 20528, 25945, 33123, 25220, 28393, 26567, 29033, 45727, 33176]
Topic: 1. Top: [47238, 33123, 31298, 33176, 29237, 52105, 30339, 30252, 33125, 48735, 33036, 44121, 31397, 29902, 34317, 17231, 28695, 19656, 29684, 30490]
Topic: 2. Top: [29237, 33125, 29282, 30339, 32510, 34317, 34871, 26745, 20164, 33036, 33124, 28695, 30160, 39719, 17194, 32939, 29116, 27136, 29902, 45841]
Topic: 3. Top: [30339, 32254, 33036, 29096, 34317, 30252, 37712, 30887, 28453, 37631, 28016, 47238, 45183, 29684, 30416, 20581, 30795, 29237, 30082, 32449]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 29237, 29096, 21347, 29453]
Topic: 5. Top: [49838, 37130, 32833, 28100, 33484, 34287, 37692, 28019, 27185, 29939, 38446, 30627, 28992, 26190, 30597, 34531, 28095, 20673, 20528, 17856]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 29237, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [28701, 29282, 33036, 28995, 26745, 30160, 33124, 32510, 33123, 40029, 29784, 52105, 28695, 30152, 33714, 27970, 20164, 32337, 32833, 32681]
Topic: 8. Top: [32833, 34364, 33036, 42030, 33123, 40295, 25342, 18601, 25025, 28585, 34130, 44121, 50442, 38753, 30444, 26745, 31374, 47238, 46714, 31777]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 33036, 27643, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [32833, 21123, 35657, 44211, 26809, 32135, 35538, 27587, 26864, 32665, 36303, 33484, 30791, 29592, 34571, 46714, 38446, 33707, 20164, 34729]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [28172, 28465, 27624, 49838, 36585, 52105, 35842, 28629, 21874, 33123, 19656, 33047, 22422, 28701, 30656, 29331, 17856, 21650, 40736, 28995]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
Topic: 0. Top: [30791, 32833, 40029, 35416, 32665, 19656, 28999, 33826, 29939, 43613, 34170, 20528, 25945, 33123, 25220, 28393, 26567, 29033, 45727, 33176]
Topic: 1. Top: [47238, 33123, 31298, 33176, 29237, 52105, 30339, 30252, 33125, 48735, 33036, 44121, 31397, 29902, 34317, 17231, 28695, 19656, 29684, 30490]
Topic: 2. Top: [29237, 33125, 29282, 30339, 32510, 34317, 34871, 26745, 20164, 33036, 33124, 28695, 30160, 39719, 17194, 32939, 29116, 27136, 29902, 45841]
Topic: 3. Top: [30339, 32254, 33036, 29096, 34317, 30252, 37712, 30887, 28453, 37631, 28016, 47238, 45183, 29684, 30416, 20581, 30795, 29237, 30082, 32449]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 29237, 29096, 21347, 29453]
Topic: 5. Top: [49838, 37130, 32833, 28100, 33484, 34287, 37692, 28019, 27185, 29939, 38446, 30627, 28992, 26190, 30597, 34531, 28095, 20673, 20528, 17856]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 29237, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [28701, 29282, 33036, 28995, 26745, 30160, 33124, 32510, 33123, 40029, 29784, 52105, 28695, 30152, 33714, 27970, 20164, 32337, 32833, 32681]
Topic: 8. Top: [32833, 34364, 33036, 42030, 33123, 40295, 25342, 18601, 25025, 28585, 34130, 44121, 50442, 38753, 30444, 26745, 31374, 47238, 46714, 31777]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 33036, 27643, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [32833, 21123, 35657, 44211, 26809, 32135, 35538, 27587, 26864, 32665, 36303, 33484, 30791, 29592, 34571, 46714, 38446, 33707, 20164, 34729]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [28172, 28465, 27624, 49838, 36585, 52105, 35842, 28629, 21874, 33123, 19656, 33047, 22422, 28701, 30656, 29331, 17856, 21650, 40736, 28995]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1064736569248931
sparse_theta_sp: -0.4969335953319671
decorrelation: 0.01
fix: 1000000000
ext_decorr_good: 100000000
SUCCESS: more good topics
DOWNFALL: more bad topics...
num_topics: {'good': 12, 'bad': 4, 'not_good': 8, 'total_bad': 24}
8

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b89015a90>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f7b8e9cebb0>}
Topic: 0. Top: [47238, 33123, 29237, 33125, 29282, 30339, 31298, 29902, 32510, 33176, 28701, 34317, 26745, 52105, 30252, 34871, 33124, 28695, 33036, 17194]
Topic: 1. Top: [40029, 32833, 33176, 33036, 33123, 34364, 28393, 19656, 44121, 50442, 47238, 29784, 31298, 30490, 30444, 26745, 46714, 25025, 34871, 31777]
Topic: 2. Top: [27030, 32833, 40820, 32241, 21394, 28701, 26095, 27934, 25941, 29791, 30444, 49904, 28068, 24452, 18500, 22255, 28872, 30066, 19354, 27441]
Topic: 3. Top: [30339, 32254, 33036, 29096, 34317, 30252, 37712, 30887, 28453, 37631, 28016, 47238, 45183, 29684, 30416, 20581, 30795, 29237, 30082, 32449]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 29237, 29096, 21347, 29453]
Topic: 5. Top: [29237, 27624, 19656, 40295, 42456, 33047, 35057, 28252, 46583, 26627, 32665, 32929, 31186, 25540, 29282, 27540, 33746, 27835, 36226, 30655]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 29237, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [49838, 32833, 28100, 34287, 37130, 29939, 33826, 30627, 28019, 28095, 26190, 28999, 31192, 28775, 37692, 24123, 32677, 32135, 40409, 28992]
Topic: 8. Top: [28172, 35842, 33123, 22422, 37130, 27624, 30597, 42030, 21650, 33036, 17856, 19656, 27300, 27066, 49838, 45727, 29331, 25911, 31374, 34531]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 33036, 27643, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [30791, 32833, 33484, 32665, 43613, 27185, 44211, 20528, 35416, 35657, 38446, 25945, 26809, 34170, 42166, 20673, 19656, 32135, 33123, 21123]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [29282, 33036, 32510, 33125, 20164, 28701, 28695, 30152, 35023, 30160, 32678, 19828, 28995, 26745, 30339, 27136, 44259, 33124, 45841, 27970]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
Topic: 0. Top: [47238, 33123, 29237, 33125, 29282, 30339, 31298, 29902, 32510, 33176, 28701, 34317, 26745, 52105, 30252, 34871, 33124, 28695, 33036, 17194]
Topic: 1. Top: [40029, 32833, 33176, 33036, 33123, 34364, 28393, 19656, 44121, 50442, 47238, 29784, 31298, 30490, 30444, 26745, 46714, 25025, 34871, 31777]
Topic: 2. Top: [27030, 32833, 40820, 32241, 21394, 28701, 26095, 27934, 25941, 29791, 30444, 49904, 28068, 24452, 18500, 22255, 28872, 30066, 19354, 27441]
Topic: 3. Top: [30339, 32254, 33036, 29096, 34317, 30252, 37712, 30887, 28453, 37631, 28016, 47238, 45183, 29684, 30416, 20581, 30795, 29237, 30082, 32449]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 29237, 29096, 21347, 29453]
Topic: 5. Top: [29237, 27624, 19656, 40295, 42456, 33047, 35057, 28252, 46583, 26627, 32665, 32929, 31186, 25540, 29282, 27540, 33746, 27835, 36226, 30655]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 29237, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [49838, 32833, 28100, 34287, 37130, 29939, 33826, 30627, 28019, 28095, 26190, 28999, 31192, 28775, 37692, 24123, 32677, 32135, 40409, 28992]
Topic: 8. Top: [28172, 35842, 33123, 22422, 37130, 27624, 30597, 42030, 21650, 33036, 17856, 19656, 27300, 27066, 49838, 45727, 29331, 25911, 31374, 34531]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 33036, 27643, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [30791, 32833, 33484, 32665, 43613, 27185, 44211, 20528, 35416, 35657, 38446, 25945, 26809, 34170, 42166, 20673, 19656, 32135, 33123, 21123]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [29282, 33036, 32510, 33125, 20164, 28701, 28695, 30152, 35023, 30160, 32678, 19828, 28995, 26745, 30339, 27136, 44259, 33124, 45841, 27970]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.11978286404050471
sparse_theta_sp: -0.559050294748463
decorrelation: 0.01
fix: 1000000000
ext_decorr_good: 100000000
num_topics: {'good': 12, 'bad': 4, 'not_good': 8, 'total_bad': 28}
9

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b71641b20>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f7b8ea2f0d0>}
Topic: 0. Top: [20528, 27185, 28068, 42166, 32665, 28992, 32833, 26809, 29939, 33484, 25911, 39945, 29834, 30627, 27787, 34571, 26165, 35657, 49264, 22254]
Topic: 1. Top: [32833, 33484, 43613, 40029, 38446, 20673, 26239, 44211, 39872, 32665, 46714, 25025, 26306, 33123, 19656, 27587, 31502, 35416, 32135, 33176]
Topic: 2. Top: [28172, 34364, 28629, 27624, 33707, 34095, 34130, 38753, 24278, 32833, 35185, 40736, 49838, 17856, 30429, 21394, 29272, 31133, 21123, 42030]
Topic: 3. Top: [30339, 32254, 33036, 29096, 34317, 30252, 37712, 30887, 28453, 37631, 28016, 47238, 45183, 29684, 30416, 20581, 30795, 29237, 30082, 32449]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 29237, 29096, 21347, 29453]
Topic: 5. Top: [35842, 52105, 28465, 21650, 27624, 22422, 36585, 33123, 29282, 27066, 48735, 40295, 30656, 21874, 50488, 31301, 34966, 30036, 27937, 31669]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 29237, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [29237, 32510, 29282, 19656, 30339, 26627, 47238, 32677, 33125, 33047, 21874, 29902, 29096, 31186, 27187, 42456, 32665, 27540, 26192, 52105]
Topic: 8. Top: [33123, 47238, 33125, 29282, 29237, 33036, 28701, 33176, 32510, 30339, 26745, 31298, 28695, 34317, 34871, 33124, 30160, 28995, 20164, 29116]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 33036, 27643, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [30791, 32833, 37130, 35416, 40029, 19656, 30597, 35657, 33123, 33826, 32665, 28999, 34531, 25945, 38446, 32135, 44211, 29939, 37692, 28368]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [49838, 28100, 34287, 26190, 28095, 29939, 32833, 37130, 30119, 40409, 32717, 24123, 28775, 36268, 51400, 52215, 31374, 23120, 17856, 42030]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
Topic: 0. Top: [20528, 27185, 28068, 42166, 32665, 28992, 32833, 26809, 29939, 33484, 25911, 39945, 29834, 30627, 27787, 34571, 26165, 35657, 49264, 22254]
Topic: 1. Top: [32833, 33484, 43613, 40029, 38446, 20673, 26239, 44211, 39872, 32665, 46714, 25025, 26306, 33123, 19656, 27587, 31502, 35416, 32135, 33176]
Topic: 2. Top: [28172, 34364, 28629, 27624, 33707, 34095, 34130, 38753, 24278, 32833, 35185, 40736, 49838, 17856, 30429, 21394, 29272, 31133, 21123, 42030]
Topic: 3. Top: [30339, 32254, 33036, 29096, 34317, 30252, 37712, 30887, 28453, 37631, 28016, 47238, 45183, 29684, 30416, 20581, 30795, 29237, 30082, 32449]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 29237, 29096, 21347, 29453]
Topic: 5. Top: [35842, 52105, 28465, 21650, 27624, 22422, 36585, 33123, 29282, 27066, 48735, 40295, 30656, 21874, 50488, 31301, 34966, 30036, 27937, 31669]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 29237, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [29237, 32510, 29282, 19656, 30339, 26627, 47238, 32677, 33125, 33047, 21874, 29902, 29096, 31186, 27187, 42456, 32665, 27540, 26192, 52105]
Topic: 8. Top: [33123, 47238, 33125, 29282, 29237, 33036, 28701, 33176, 32510, 30339, 26745, 31298, 28695, 34317, 34871, 33124, 30160, 28995, 20164, 29116]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 33036, 27643, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [30791, 32833, 37130, 35416, 40029, 19656, 30597, 35657, 33123, 33826, 32665, 28999, 34531, 25945, 38446, 32135, 44211, 29939, 37692, 28368]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [49838, 28100, 34287, 26190, 28095, 29939, 32833, 37130, 30119, 40409, 32717, 24123, 28775, 36268, 51400, 52215, 31374, 23120, 17856, 42030]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.11978286404050471
sparse_theta_sp: -0.559050294748463
decorrelation: 0.01
fix: 1000000000
ext_decorr_good: 100000000
SUCCESS: less bad topics
num_topics: {'good': 12, 'bad': 1, 'not_good': 8, 'total_bad': 29}
10

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8f744370>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f7b890b6d00>}
Topic: 0. Top: [28172, 32833, 34364, 33036, 28701, 33123, 42030, 28629, 33176, 26745, 19656, 22422, 32510, 40029, 25342, 25025, 27624, 50442, 47238, 17856]
Topic: 1. Top: [33123, 47238, 31298, 52105, 48735, 28172, 27030, 44121, 34012, 30656, 33176, 32241, 40295, 31397, 30252, 21580, 49838, 29644, 28995, 32833]
Topic: 2. Top: [30791, 32833, 35657, 32665, 21123, 44211, 32135, 26809, 35538, 35416, 39872, 27086, 33123, 19656, 29592, 27587, 40029, 26864, 49264, 36303]
Topic: 3. Top: [30339, 32254, 33036, 29096, 34317, 30252, 37712, 30887, 28453, 37631, 28016, 47238, 45183, 29684, 30416, 20581, 30795, 29237, 30082, 32449]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 29237, 29096, 21347, 29453]
Topic: 5. Top: [33484, 20673, 27185, 42166, 28992, 26239, 46714, 38446, 32665, 20528, 21001, 43613, 39945, 28068, 29791, 37027, 27850, 27985, 20164, 32833]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 29237, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [29282, 29237, 33125, 30339, 47238, 32510, 33036, 33123, 34317, 26745, 28701, 28695, 33124, 34871, 30160, 33176, 29902, 31298, 17194, 20164]
Topic: 8. Top: [19656, 52105, 32665, 21874, 33047, 27624, 42456, 31186, 32929, 31803, 36376, 35331, 26192, 33746, 28252, 33176, 27540, 28535, 34130, 47238]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 33036, 27643, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [49838, 28100, 37130, 26190, 35842, 28095, 27066, 27624, 30119, 29939, 40409, 41831, 32717, 32833, 28068, 50488, 51400, 21650, 36268, 31374]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [32833, 37130, 30791, 40029, 33826, 28019, 37692, 35416, 30627, 34287, 29939, 19656, 28999, 38446, 30597, 34531, 31192, 20528, 28368, 43613]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
Topic: 0. Top: [28172, 32833, 34364, 33036, 28701, 33123, 42030, 28629, 33176, 26745, 19656, 22422, 32510, 40029, 25342, 25025, 27624, 50442, 47238, 17856]
Topic: 1. Top: [33123, 47238, 31298, 52105, 48735, 28172, 27030, 44121, 34012, 30656, 33176, 32241, 40295, 31397, 30252, 21580, 49838, 29644, 28995, 32833]
Topic: 2. Top: [30791, 32833, 35657, 32665, 21123, 44211, 32135, 26809, 35538, 35416, 39872, 27086, 33123, 19656, 29592, 27587, 40029, 26864, 49264, 36303]
Topic: 3. Top: [30339, 32254, 33036, 29096, 34317, 30252, 37712, 30887, 28453, 37631, 28016, 47238, 45183, 29684, 30416, 20581, 30795, 29237, 30082, 32449]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 29237, 29096, 21347, 29453]
Topic: 5. Top: [33484, 20673, 27185, 42166, 28992, 26239, 46714, 38446, 32665, 20528, 21001, 43613, 39945, 28068, 29791, 37027, 27850, 27985, 20164, 32833]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 29237, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [29282, 29237, 33125, 30339, 47238, 32510, 33036, 33123, 34317, 26745, 28701, 28695, 33124, 34871, 30160, 33176, 29902, 31298, 17194, 20164]
Topic: 8. Top: [19656, 52105, 32665, 21874, 33047, 27624, 42456, 31186, 32929, 31803, 36376, 35331, 26192, 33746, 28252, 33176, 27540, 28535, 34130, 47238]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 33036, 27643, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [49838, 28100, 37130, 26190, 35842, 28095, 27066, 27624, 30119, 29939, 40409, 41831, 32717, 32833, 28068, 50488, 51400, 21650, 36268, 31374]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [32833, 37130, 30791, 40029, 33826, 28019, 37692, 35416, 30627, 34287, 29939, 19656, 28999, 38446, 30597, 34531, 31192, 20528, 28368, 43613]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.11978286404050471
sparse_theta_sp: -0.559050294748463
decorrelation: 0.01
fix: 1000000000
ext_decorr_good: 100000000
DOWNFALL: more bad topics...
num_topics: {'good': 12, 'bad': 3, 'not_good': 8, 'total_bad': 32}
11

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8eb03cd0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f7b8bab5430>}
Topic: 0. Top: [49838, 37130, 28100, 34287, 26190, 28095, 29939, 24123, 31964, 32833, 28999, 40409, 30119, 28019, 37692, 51400, 36268, 32717, 32942, 23120]
Topic: 1. Top: [33036, 20164, 33125, 29282, 35023, 32510, 32833, 33124, 28701, 30339, 28884, 28695, 30152, 31298, 33176, 29784, 34871, 28393, 33123, 19828]
Topic: 2. Top: [32833, 30791, 39872, 27030, 32135, 33707, 40029, 46714, 32275, 42892, 46583, 32241, 31397, 35604, 35416, 32983, 25514, 21390, 38446, 19933]
Topic: 3. Top: [30339, 32254, 33036, 29096, 34317, 30252, 37712, 30887, 28453, 37631, 28016, 47238, 45183, 29684, 30416, 20581, 30795, 29237, 30082, 32449]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 29237, 29096, 21347, 29453]
Topic: 5. Top: [30791, 21123, 32833, 35657, 32665, 35538, 44211, 27086, 32135, 36303, 29592, 26809, 27587, 34729, 22099, 35416, 26864, 19656, 26567, 31747]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 29237, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [47238, 33123, 29237, 29282, 33125, 32510, 30339, 31298, 28701, 33176, 52105, 26745, 28172, 33036, 28695, 34317, 34871, 30160, 29902, 28995]
Topic: 8. Top: [40295, 34130, 35331, 29109, 38753, 26584, 25163, 31228, 43332, 28252, 43719, 37792, 29646, 17744, 29393, 43791, 36985, 32663, 37112, 19900]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 33036, 27643, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [33484, 27185, 20528, 32833, 38446, 32665, 28992, 20673, 42166, 34170, 44211, 30627, 43613, 28019, 29939, 26239, 37692, 30791, 30597, 17856]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [32833, 40029, 19656, 33123, 30791, 22422, 35842, 33826, 33036, 28393, 26745, 35416, 45727, 29033, 34317, 29282, 27624, 29939, 39575, 25911]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
Topic: 0. Top: [49838, 37130, 28100, 34287, 26190, 28095, 29939, 24123, 31964, 32833, 28999, 40409, 30119, 28019, 37692, 51400, 36268, 32717, 32942, 23120]
Topic: 1. Top: [33036, 20164, 33125, 29282, 35023, 32510, 32833, 33124, 28701, 30339, 28884, 28695, 30152, 31298, 33176, 29784, 34871, 28393, 33123, 19828]
Topic: 2. Top: [32833, 30791, 39872, 27030, 32135, 33707, 40029, 46714, 32275, 42892, 46583, 32241, 31397, 35604, 35416, 32983, 25514, 21390, 38446, 19933]
Topic: 3. Top: [30339, 32254, 33036, 29096, 34317, 30252, 37712, 30887, 28453, 37631, 28016, 47238, 45183, 29684, 30416, 20581, 30795, 29237, 30082, 32449]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 29237, 29096, 21347, 29453]
Topic: 5. Top: [30791, 21123, 32833, 35657, 32665, 35538, 44211, 27086, 32135, 36303, 29592, 26809, 27587, 34729, 22099, 35416, 26864, 19656, 26567, 31747]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 29237, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [47238, 33123, 29237, 29282, 33125, 32510, 30339, 31298, 28701, 33176, 52105, 26745, 28172, 33036, 28695, 34317, 34871, 30160, 29902, 28995]
Topic: 8. Top: [40295, 34130, 35331, 29109, 38753, 26584, 25163, 31228, 43332, 28252, 43719, 37792, 29646, 17744, 29393, 43791, 36985, 32663, 37112, 19900]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 33036, 27643, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [33484, 27185, 20528, 32833, 38446, 32665, 28992, 20673, 42166, 34170, 44211, 30627, 43613, 28019, 29939, 26239, 37692, 30791, 30597, 17856]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [32833, 40029, 19656, 33123, 30791, 22422, 35842, 33826, 33036, 28393, 26745, 35416, 45727, 29033, 34317, 29282, 27624, 29939, 39575, 25911]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.11978286404050471
sparse_theta_sp: -0.559050294748463
decorrelation: 0.01
fix: 1000000000
ext_decorr_good: 100000000
num_topics: {'good': 12, 'bad': 3, 'not_good': 8, 'total_bad': 35}
12

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8907cd60>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f7b8e935790>}
Topic: 0. Top: [47238, 33123, 29282, 33125, 29237, 33176, 30339, 32510, 33036, 28701, 31298, 26745, 34317, 28695, 34871, 29902, 52105, 33124, 30160, 17194]
Topic: 1. Top: [35842, 28068, 27066, 21650, 50488, 27624, 30119, 30656, 35331, 51997, 32833, 25025, 31301, 39575, 25911, 28465, 28701, 27787, 34130, 36585]
Topic: 2. Top: [28172, 34364, 32833, 33123, 28629, 49838, 42030, 28701, 17856, 25342, 22422, 33036, 34095, 27624, 28995, 44121, 40736, 47238, 24278, 31133]
Topic: 3. Top: [30339, 32254, 33036, 29096, 34317, 30252, 37712, 30887, 28453, 37631, 28016, 47238, 45183, 29684, 30416, 20581, 30795, 29237, 30082, 32449]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 29237, 29096, 21347, 29453]
Topic: 5. Top: [29237, 19828, 32510, 29259, 29282, 20164, 33125, 45841, 29559, 30339, 29939, 33036, 35023, 28884, 32678, 30152, 46583, 26072, 27587, 27754]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 29237, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [30791, 32833, 32665, 35657, 21123, 35416, 32135, 44211, 40029, 26809, 35538, 33123, 27086, 25945, 26567, 19656, 26864, 39872, 29592, 36303]
Topic: 8. Top: [37130, 24123, 28999, 28019, 20164, 30444, 31215, 35223, 22099, 40029, 24848, 33036, 33176, 27579, 25220, 35416, 28368, 17856, 49809, 25466]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 33036, 27643, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [33484, 27185, 38446, 32833, 20528, 20673, 28019, 34531, 43613, 32665, 26239, 28992, 30597, 30627, 34170, 37692, 44211, 42166, 31192, 26306]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [49838, 32833, 28100, 34287, 29939, 40029, 19656, 37130, 26190, 28095, 37692, 28775, 33826, 33123, 30627, 27300, 45727, 40409, 52215, 41831]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
Topic: 0. Top: [47238, 33123, 29282, 33125, 29237, 33176, 30339, 32510, 33036, 28701, 31298, 26745, 34317, 28695, 34871, 29902, 52105, 33124, 30160, 17194]
Topic: 1. Top: [35842, 28068, 27066, 21650, 50488, 27624, 30119, 30656, 35331, 51997, 32833, 25025, 31301, 39575, 25911, 28465, 28701, 27787, 34130, 36585]
Topic: 2. Top: [28172, 34364, 32833, 33123, 28629, 49838, 42030, 28701, 17856, 25342, 22422, 33036, 34095, 27624, 28995, 44121, 40736, 47238, 24278, 31133]
Topic: 3. Top: [30339, 32254, 33036, 29096, 34317, 30252, 37712, 30887, 28453, 37631, 28016, 47238, 45183, 29684, 30416, 20581, 30795, 29237, 30082, 32449]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 29237, 29096, 21347, 29453]
Topic: 5. Top: [29237, 19828, 32510, 29259, 29282, 20164, 33125, 45841, 29559, 30339, 29939, 33036, 35023, 28884, 32678, 30152, 46583, 26072, 27587, 27754]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 29237, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [30791, 32833, 32665, 35657, 21123, 35416, 32135, 44211, 40029, 26809, 35538, 33123, 27086, 25945, 26567, 19656, 26864, 39872, 29592, 36303]
Topic: 8. Top: [37130, 24123, 28999, 28019, 20164, 30444, 31215, 35223, 22099, 40029, 24848, 33036, 33176, 27579, 25220, 35416, 28368, 17856, 49809, 25466]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 33036, 27643, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [33484, 27185, 38446, 32833, 20528, 20673, 28019, 34531, 43613, 32665, 26239, 28992, 30597, 30627, 34170, 37692, 44211, 42166, 31192, 26306]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [49838, 32833, 28100, 34287, 29939, 40029, 19656, 37130, 26190, 28095, 37692, 28775, 33826, 33123, 30627, 27300, 45727, 40409, 52215, 41831]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.11978286404050471
sparse_theta_sp: -0.559050294748463
decorrelation: 0.01
fix: 1000000000
ext_decorr_good: 100000000
SUCCESS: less bad topics
num_topics: {'good': 12, 'bad': 1, 'not_good': 8, 'total_bad': 36}
13

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b89082dc0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f7b890932e0>}
Topic: 0. Top: [40295, 19828, 21123, 32833, 22099, 29559, 42892, 27587, 30655, 29791, 24640, 26864, 29674, 29581, 17398, 44826, 26809, 24452, 27724, 29592]
Topic: 1. Top: [49838, 32833, 37130, 28100, 29939, 34287, 40029, 19656, 33826, 37692, 33123, 33036, 30597, 30627, 28019, 26190, 35416, 28999, 28095, 34531]
Topic: 2. Top: [29237, 19656, 29282, 32510, 52105, 21874, 47238, 29096, 29902, 33047, 26627, 33123, 28465, 32677, 33125, 30339, 32665, 36585, 34317, 26192]
Topic: 3. Top: [30339, 32254, 33036, 29096, 34317, 30252, 37712, 30887, 28453, 37631, 28016, 47238, 45183, 29684, 30416, 20581, 30795, 29237, 30082, 32449]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 29237, 29096, 21347, 29453]
Topic: 5. Top: [28172, 34364, 33123, 28629, 49838, 33036, 47238, 17856, 24278, 22422, 34130, 28701, 34095, 40736, 32510, 26745, 38753, 30429, 25342, 35185]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 29237, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [48735, 31298, 47238, 33176, 33123, 29684, 44121, 30490, 30252, 29592, 17231, 30887, 46583, 34317, 34809, 22363, 21394, 28701, 25808, 52105]
Topic: 8. Top: [30791, 32833, 32665, 35657, 40029, 35416, 32135, 44211, 19656, 25945, 35538, 21123, 27086, 26567, 33123, 46714, 26809, 34729, 29592, 28393]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 33036, 27643, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [33484, 27185, 20528, 38446, 20673, 32833, 42166, 28992, 32665, 43613, 26239, 44211, 26306, 34170, 28068, 31502, 39945, 22254, 28019, 22980]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [29282, 33125, 33123, 29237, 47238, 33036, 30339, 28701, 32510, 26745, 28695, 33124, 34871, 30160, 33176, 17194, 20164, 31298, 34317, 29784]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
Topic: 0. Top: [40295, 19828, 21123, 32833, 22099, 29559, 42892, 27587, 30655, 29791, 24640, 26864, 29674, 29581, 17398, 44826, 26809, 24452, 27724, 29592]
Topic: 1. Top: [49838, 32833, 37130, 28100, 29939, 34287, 40029, 19656, 33826, 37692, 33123, 33036, 30597, 30627, 28019, 26190, 35416, 28999, 28095, 34531]
Topic: 2. Top: [29237, 19656, 29282, 32510, 52105, 21874, 47238, 29096, 29902, 33047, 26627, 33123, 28465, 32677, 33125, 30339, 32665, 36585, 34317, 26192]
Topic: 3. Top: [30339, 32254, 33036, 29096, 34317, 30252, 37712, 30887, 28453, 37631, 28016, 47238, 45183, 29684, 30416, 20581, 30795, 29237, 30082, 32449]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 29237, 29096, 21347, 29453]
Topic: 5. Top: [28172, 34364, 33123, 28629, 49838, 33036, 47238, 17856, 24278, 22422, 34130, 28701, 34095, 40736, 32510, 26745, 38753, 30429, 25342, 35185]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 29237, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [48735, 31298, 47238, 33176, 33123, 29684, 44121, 30490, 30252, 29592, 17231, 30887, 46583, 34317, 34809, 22363, 21394, 28701, 25808, 52105]
Topic: 8. Top: [30791, 32833, 32665, 35657, 40029, 35416, 32135, 44211, 19656, 25945, 35538, 21123, 27086, 26567, 33123, 46714, 26809, 34729, 29592, 28393]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 33036, 27643, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [33484, 27185, 20528, 38446, 20673, 32833, 42166, 28992, 32665, 43613, 26239, 44211, 26306, 34170, 28068, 31502, 39945, 22254, 28019, 22980]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [29282, 33125, 33123, 29237, 47238, 33036, 30339, 28701, 32510, 26745, 28695, 33124, 34871, 30160, 33176, 17194, 20164, 31298, 34317, 29784]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.11978286404050471
sparse_theta_sp: -0.559050294748463
decorrelation: 0.01
fix: 1000000000
ext_decorr_good: 100000000
DOWNFALL: more bad topics...
num_topics: {'good': 12, 'bad': 2, 'not_good': 8, 'total_bad': 38}
14

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b89496b50>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f7b8f744a90>}
Topic: 0. Top: [49838, 32833, 34287, 28100, 37692, 35842, 26190, 28992, 29939, 30627, 28068, 28095, 42030, 31374, 26306, 27624, 30119, 32717, 27066, 19656]
Topic: 1. Top: [37130, 32833, 33484, 33826, 30791, 40029, 29939, 43613, 38446, 28019, 32665, 35416, 27185, 30597, 34531, 28999, 19656, 33123, 20528, 20673]
Topic: 2. Top: [33484, 20528, 39945, 29272, 28068, 26809, 29791, 42892, 29834, 27678, 30152, 20164, 30655, 27587, 31228, 35331, 29875, 33707, 25604, 35657]
Topic: 3. Top: [30339, 32254, 33036, 29096, 34317, 30252, 37712, 30887, 28453, 37631, 28016, 47238, 45183, 29684, 30416, 20581, 30795, 29237, 30082, 32449]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 29237, 29096, 21347, 29453]
Topic: 5. Top: [29237, 32510, 29282, 30339, 45841, 35023, 19828, 20164, 29259, 33125, 33036, 34317, 27030, 31298, 39719, 17194, 29684, 32678, 46583, 28016]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 29237, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [19656, 52105, 21874, 32665, 33047, 32833, 22209, 28465, 29237, 36585, 30656, 32929, 31622, 32510, 47238, 31186, 42456, 30130, 40820, 29282]
Topic: 8. Top: [30791, 32833, 35657, 21123, 32135, 32665, 44211, 35538, 40029, 39872, 35416, 27086, 33123, 26809, 19656, 26567, 29592, 36303, 25945, 34729]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 33036, 27643, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [47238, 28172, 31298, 48735, 33176, 33123, 44121, 52105, 30444, 31397, 30252, 30490, 29684, 19656, 50442, 28701, 33036, 24278, 29592, 40295]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [33123, 29282, 33125, 28701, 26745, 47238, 33036, 28695, 34871, 29237, 33176, 32510, 34317, 28995, 30339, 33124, 30160, 29902, 29784, 29728]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
Topic: 0. Top: [49838, 32833, 34287, 28100, 37692, 35842, 26190, 28992, 29939, 30627, 28068, 28095, 42030, 31374, 26306, 27624, 30119, 32717, 27066, 19656]
Topic: 1. Top: [37130, 32833, 33484, 33826, 30791, 40029, 29939, 43613, 38446, 28019, 32665, 35416, 27185, 30597, 34531, 28999, 19656, 33123, 20528, 20673]
Topic: 2. Top: [33484, 20528, 39945, 29272, 28068, 26809, 29791, 42892, 29834, 27678, 30152, 20164, 30655, 27587, 31228, 35331, 29875, 33707, 25604, 35657]
Topic: 3. Top: [30339, 32254, 33036, 29096, 34317, 30252, 37712, 30887, 28453, 37631, 28016, 47238, 45183, 29684, 30416, 20581, 30795, 29237, 30082, 32449]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 29237, 29096, 21347, 29453]
Topic: 5. Top: [29237, 32510, 29282, 30339, 45841, 35023, 19828, 20164, 29259, 33125, 33036, 34317, 27030, 31298, 39719, 17194, 29684, 32678, 46583, 28016]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 29237, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [19656, 52105, 21874, 32665, 33047, 32833, 22209, 28465, 29237, 36585, 30656, 32929, 31622, 32510, 47238, 31186, 42456, 30130, 40820, 29282]
Topic: 8. Top: [30791, 32833, 35657, 21123, 32135, 32665, 44211, 35538, 40029, 39872, 35416, 27086, 33123, 26809, 19656, 26567, 29592, 36303, 25945, 34729]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 33036, 27643, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [47238, 28172, 31298, 48735, 33176, 33123, 44121, 52105, 30444, 31397, 30252, 30490, 29684, 19656, 50442, 28701, 33036, 24278, 29592, 40295]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [33123, 29282, 33125, 28701, 26745, 47238, 33036, 28695, 34871, 29237, 33176, 32510, 34317, 28995, 30339, 33124, 30160, 29902, 29784, 29728]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.11978286404050471
sparse_theta_sp: -0.559050294748463
decorrelation: 0.01
fix: 1000000000
ext_decorr_good: 100000000
DOWNFALL: more bad topics...
num_topics: {'good': 12, 'bad': 3, 'not_good': 8, 'total_bad': 41}
15

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8baddbe0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f7b8ed42d60>}
Topic: 0. Top: [29282, 33125, 33036, 32510, 20164, 35023, 27136, 33124, 28695, 28995, 19828, 29237, 28884, 44259, 29784, 30160, 28701, 27754, 19330, 27970]
Topic: 1. Top: [29237, 30339, 29282, 33125, 33123, 34317, 32510, 47238, 28701, 26745, 29902, 34871, 31298, 30160, 33036, 29684, 33124, 39719, 33176, 17231]
Topic: 2. Top: [30791, 32833, 21123, 44211, 35657, 32135, 35538, 33123, 26239, 43613, 38446, 25945, 27086, 26567, 35416, 32665, 36303, 27587, 34729, 39872]
Topic: 3. Top: [30339, 32254, 33036, 29096, 34317, 30252, 37712, 30887, 28453, 37631, 28016, 47238, 45183, 29684, 30416, 20581, 30795, 29237, 30082, 32449]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 29237, 29096, 21347, 29453]
Topic: 5. Top: [49838, 34287, 28100, 32833, 29939, 37130, 40029, 26190, 28095, 30597, 19656, 28999, 33123, 24123, 17856, 37692, 27300, 31964, 33036, 51400]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 29237, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [32833, 30791, 33484, 20528, 37130, 27185, 33826, 30627, 38446, 32665, 29939, 35416, 34170, 43613, 20673, 28992, 37692, 28019, 32677, 34531]
Topic: 8. Top: [32833, 18601, 42030, 40295, 28585, 33036, 25025, 21580, 47079, 45727, 22209, 37265, 30656, 35416, 25143, 25342, 31374, 46714, 36585, 33123]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 33036, 27643, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [47238, 33123, 28172, 52105, 33176, 31298, 28701, 19656, 44121, 33036, 28695, 26745, 33125, 46780, 32510, 28995, 21874, 48735, 29282, 27624]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [32665, 32833, 26809, 19656, 34571, 20164, 40029, 26165, 46714, 39945, 33707, 26864, 31353, 38087, 28068, 35331, 39329, 29939, 42166, 33036]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
Topic: 0. Top: [29282, 33125, 33036, 32510, 20164, 35023, 27136, 33124, 28695, 28995, 19828, 29237, 28884, 44259, 29784, 30160, 28701, 27754, 19330, 27970]
Topic: 1. Top: [29237, 30339, 29282, 33125, 33123, 34317, 32510, 47238, 28701, 26745, 29902, 34871, 31298, 30160, 33036, 29684, 33124, 39719, 33176, 17231]
Topic: 2. Top: [30791, 32833, 21123, 44211, 35657, 32135, 35538, 33123, 26239, 43613, 38446, 25945, 27086, 26567, 35416, 32665, 36303, 27587, 34729, 39872]
Topic: 3. Top: [30339, 32254, 33036, 29096, 34317, 30252, 37712, 30887, 28453, 37631, 28016, 47238, 45183, 29684, 30416, 20581, 30795, 29237, 30082, 32449]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 29237, 29096, 21347, 29453]
Topic: 5. Top: [49838, 34287, 28100, 32833, 29939, 37130, 40029, 26190, 28095, 30597, 19656, 28999, 33123, 24123, 17856, 37692, 27300, 31964, 33036, 51400]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 29237, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [32833, 30791, 33484, 20528, 37130, 27185, 33826, 30627, 38446, 32665, 29939, 35416, 34170, 43613, 20673, 28992, 37692, 28019, 32677, 34531]
Topic: 8. Top: [32833, 18601, 42030, 40295, 28585, 33036, 25025, 21580, 47079, 45727, 22209, 37265, 30656, 35416, 25143, 25342, 31374, 46714, 36585, 33123]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 33036, 27643, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [47238, 33123, 28172, 52105, 33176, 31298, 28701, 19656, 44121, 33036, 28695, 26745, 33125, 46780, 32510, 28995, 21874, 48735, 29282, 27624]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [32665, 32833, 26809, 19656, 34571, 20164, 40029, 26165, 46714, 39945, 33707, 26864, 31353, 38087, 28068, 35331, 39329, 29939, 42166, 33036]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.11978286404050471
sparse_theta_sp: -0.559050294748463
decorrelation: 0.01
fix: 1000000000
ext_decorr_good: 100000000
num_topics: {'good': 12, 'bad': 3, 'not_good': 8, 'total_bad': 44}
16

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8eb4a670>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f7b8badd310>}
Topic: 0. Top: [49838, 28172, 26190, 40029, 28100, 33826, 32833, 52215, 28629, 17856, 36268, 29939, 33123, 30656, 40736, 28540, 36226, 33176, 30152, 35416]
Topic: 1. Top: [33484, 27185, 20673, 26239, 38446, 42166, 28992, 31502, 43613, 32665, 20528, 21001, 46583, 41427, 44211, 52456, 28019, 28146, 33761, 26809]
Topic: 2. Top: [29282, 33125, 29237, 32510, 30339, 20164, 33124, 28695, 35023, 34871, 28701, 30160, 27136, 26745, 33036, 34317, 32939, 32833, 44259, 33731]
Topic: 3. Top: [30339, 32254, 33036, 29096, 34317, 30252, 37712, 30887, 28453, 37631, 28016, 47238, 45183, 29684, 30416, 20581, 30795, 29237, 30082, 32449]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 29237, 29096, 21347, 29453]
Topic: 5. Top: [30791, 32833, 32665, 35657, 35416, 32135, 21123, 44211, 40029, 19656, 25945, 33123, 26809, 35538, 43613, 25943, 27086, 39872, 26864, 26567]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 29237, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [29282, 47035, 27030, 30444, 36376, 28016, 33380, 32929, 17194, 52105, 26627, 34130, 29891, 34966, 26192, 49897, 29331, 45935, 33746, 32510]
Topic: 8. Top: [37130, 32833, 37692, 34287, 30627, 29939, 20528, 28100, 28019, 30597, 33826, 35842, 19656, 34531, 28775, 28368, 51400, 33036, 25911, 31192]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 33036, 27643, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [33123, 47238, 33176, 31298, 28701, 33125, 33036, 29237, 52105, 26745, 28695, 32510, 34317, 29902, 44121, 30252, 34871, 28995, 33124, 19656]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [35331, 32665, 40295, 40820, 42456, 28252, 25163, 28068, 31228, 30331, 42892, 29939, 30655, 28701, 26584, 25540, 43719, 25941, 21202, 25911]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
Topic: 0. Top: [49838, 28172, 26190, 40029, 28100, 33826, 32833, 52215, 28629, 17856, 36268, 29939, 33123, 30656, 40736, 28540, 36226, 33176, 30152, 35416]
Topic: 1. Top: [33484, 27185, 20673, 26239, 38446, 42166, 28992, 31502, 43613, 32665, 20528, 21001, 46583, 41427, 44211, 52456, 28019, 28146, 33761, 26809]
Topic: 2. Top: [29282, 33125, 29237, 32510, 30339, 20164, 33124, 28695, 35023, 34871, 28701, 30160, 27136, 26745, 33036, 34317, 32939, 32833, 44259, 33731]
Topic: 3. Top: [30339, 32254, 33036, 29096, 34317, 30252, 37712, 30887, 28453, 37631, 28016, 47238, 45183, 29684, 30416, 20581, 30795, 29237, 30082, 32449]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 29237, 29096, 21347, 29453]
Topic: 5. Top: [30791, 32833, 32665, 35657, 35416, 32135, 21123, 44211, 40029, 19656, 25945, 33123, 26809, 35538, 43613, 25943, 27086, 39872, 26864, 26567]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 29237, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [29282, 47035, 27030, 30444, 36376, 28016, 33380, 32929, 17194, 52105, 26627, 34130, 29891, 34966, 26192, 49897, 29331, 45935, 33746, 32510]
Topic: 8. Top: [37130, 32833, 37692, 34287, 30627, 29939, 20528, 28100, 28019, 30597, 33826, 35842, 19656, 34531, 28775, 28368, 51400, 33036, 25911, 31192]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 33036, 27643, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [33123, 47238, 33176, 31298, 28701, 33125, 33036, 29237, 52105, 26745, 28695, 32510, 34317, 29902, 44121, 30252, 34871, 28995, 33124, 19656]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [35331, 32665, 40295, 40820, 42456, 28252, 25163, 28068, 31228, 30331, 42892, 29939, 30655, 28701, 26584, 25540, 43719, 25941, 21202, 25911]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.11978286404050471
sparse_theta_sp: -0.559050294748463
decorrelation: 0.01
fix: 1000000000
ext_decorr_good: 100000000
SUCCESS: more good topics
num_topics: {'good': 13, 'bad': 3, 'not_good': 7, 'total_bad': 47}
17

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b71641df0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f7b8eb4a940>}
Topic: 0. Top: [32833, 33036, 42030, 33123, 18601, 25342, 47238, 44121, 31374, 50442, 25025, 28585, 17856, 30444, 31777, 46714, 33176, 35416, 28701, 26745]
Topic: 1. Top: [33484, 27185, 20673, 26239, 38446, 42166, 28992, 31502, 43613, 32665, 20528, 21001, 46583, 41427, 44211, 52456, 28019, 28146, 33761, 26809]
Topic: 2. Top: [28172, 34364, 27624, 28629, 49838, 52105, 19656, 24278, 34095, 35842, 22422, 30656, 36585, 40736, 31133, 35185, 32510, 28465, 33826, 29331]
Topic: 3. Top: [30339, 32254, 33036, 29096, 34317, 30252, 37712, 30887, 28453, 37631, 28016, 47238, 45183, 29684, 30416, 20581, 30795, 29237, 30082, 32449]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 29237, 29096, 21347, 29453]
Topic: 5. Top: [32833, 30791, 49838, 37130, 29939, 40029, 28100, 19656, 35416, 34287, 32665, 33123, 32135, 37692, 30627, 33826, 35657, 20528, 28019, 44211]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 29237, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [47238, 33123, 33125, 29237, 29282, 30339, 33176, 31298, 34317, 26745, 28701, 29902, 52105, 28695, 34871, 33124, 30252, 32510, 30160, 29728]
Topic: 8. Top: [28884, 30130, 27187, 34966, 30655, 22725, 19780, 32678, 34130, 42892, 27532, 47035, 36628, 32711, 19933, 26691, 30887, 35189, 32510, 30152]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 33036, 27643, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [27030, 40295, 28016, 33380, 32241, 29282, 30806, 48735, 33176, 47035, 29888, 35227, 32833, 32413, 49904, 29109, 30444, 31298, 34416, 45841]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [29282, 33036, 32510, 29237, 20164, 33125, 28701, 30339, 19828, 35023, 28695, 27136, 30160, 45841, 29259, 33124, 32939, 27970, 32678, 44259]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
Topic: 0. Top: [32833, 33036, 42030, 33123, 18601, 25342, 47238, 44121, 31374, 50442, 25025, 28585, 17856, 30444, 31777, 46714, 33176, 35416, 28701, 26745]
Topic: 1. Top: [33484, 27185, 20673, 26239, 38446, 42166, 28992, 31502, 43613, 32665, 20528, 21001, 46583, 41427, 44211, 52456, 28019, 28146, 33761, 26809]
Topic: 2. Top: [28172, 34364, 27624, 28629, 49838, 52105, 19656, 24278, 34095, 35842, 22422, 30656, 36585, 40736, 31133, 35185, 32510, 28465, 33826, 29331]
Topic: 3. Top: [30339, 32254, 33036, 29096, 34317, 30252, 37712, 30887, 28453, 37631, 28016, 47238, 45183, 29684, 30416, 20581, 30795, 29237, 30082, 32449]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 29237, 29096, 21347, 29453]
Topic: 5. Top: [32833, 30791, 49838, 37130, 29939, 40029, 28100, 19656, 35416, 34287, 32665, 33123, 32135, 37692, 30627, 33826, 35657, 20528, 28019, 44211]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 29237, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [47238, 33123, 33125, 29237, 29282, 30339, 33176, 31298, 34317, 26745, 28701, 29902, 52105, 28695, 34871, 33124, 30252, 32510, 30160, 29728]
Topic: 8. Top: [28884, 30130, 27187, 34966, 30655, 22725, 19780, 32678, 34130, 42892, 27532, 47035, 36628, 32711, 19933, 26691, 30887, 35189, 32510, 30152]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 33036, 27643, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [27030, 40295, 28016, 33380, 32241, 29282, 30806, 48735, 33176, 47035, 29888, 35227, 32833, 32413, 49904, 29109, 30444, 31298, 34416, 45841]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [29282, 33036, 32510, 29237, 20164, 33125, 28701, 30339, 19828, 35023, 28695, 27136, 30160, 45841, 29259, 33124, 32939, 27970, 32678, 44259]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1368947017605768
sparse_theta_sp: -0.638914622569672
decorrelation: 0.01
fix: 1000000000
ext_decorr_good: 100000000
num_topics: {'good': 13, 'bad': 3, 'not_good': 7, 'total_bad': 50}
18

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b893452b0>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f7b71767490>}
Topic: 0. Top: [30791, 32833, 35657, 21123, 32665, 44211, 32135, 35538, 35416, 40029, 25945, 26809, 19656, 39872, 27086, 27587, 26567, 26864, 29592, 36303]
Topic: 1. Top: [33484, 27185, 20673, 26239, 38446, 42166, 28992, 31502, 43613, 32665, 20528, 21001, 46583, 41427, 44211, 52456, 28019, 28146, 33761, 26809]
Topic: 2. Top: [49838, 32833, 28100, 42030, 35842, 26190, 27066, 33036, 31374, 21650, 27624, 32717, 30119, 28068, 50488, 25025, 29939, 51997, 29834, 18601]
Topic: 3. Top: [30339, 32254, 33036, 29096, 34317, 30252, 37712, 30887, 28453, 37631, 28016, 47238, 45183, 29684, 30416, 20581, 30795, 29237, 30082, 32449]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 29237, 29096, 21347, 29453]
Topic: 5. Top: [29237, 29282, 33125, 30339, 32510, 33036, 28701, 47238, 34317, 33123, 34871, 26745, 28695, 33124, 30160, 29902, 20164, 31298, 28995, 29784]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 29237, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [33123, 47238, 33176, 31298, 44121, 48735, 31397, 52105, 27030, 30252, 30444, 30490, 33036, 35094, 40295, 28237, 50442, 17231, 26916, 35416]
Topic: 8. Top: [37130, 32833, 34287, 29939, 33826, 37692, 30627, 40029, 30791, 20528, 28019, 19656, 35416, 28999, 30597, 34531, 28368, 31192, 28775, 31964]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 33036, 27643, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [28172, 28629, 17856, 34095, 40736, 24278, 29272, 31133, 33826, 30152, 32833, 22028, 28701, 27624, 30429, 28995, 42892, 24819, 21580, 30514]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [52105, 19656, 32665, 35331, 21874, 27624, 33047, 36585, 42456, 28465, 32929, 30656, 31186, 34130, 31622, 27540, 38753, 31803, 31301, 22209]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
Topic: 0. Top: [30791, 32833, 35657, 21123, 32665, 44211, 32135, 35538, 35416, 40029, 25945, 26809, 19656, 39872, 27086, 27587, 26567, 26864, 29592, 36303]
Topic: 1. Top: [33484, 27185, 20673, 26239, 38446, 42166, 28992, 31502, 43613, 32665, 20528, 21001, 46583, 41427, 44211, 52456, 28019, 28146, 33761, 26809]
Topic: 2. Top: [49838, 32833, 28100, 42030, 35842, 26190, 27066, 33036, 31374, 21650, 27624, 32717, 30119, 28068, 50488, 25025, 29939, 51997, 29834, 18601]
Topic: 3. Top: [30339, 32254, 33036, 29096, 34317, 30252, 37712, 30887, 28453, 37631, 28016, 47238, 45183, 29684, 30416, 20581, 30795, 29237, 30082, 32449]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 29237, 29096, 21347, 29453]
Topic: 5. Top: [29237, 29282, 33125, 30339, 32510, 33036, 28701, 47238, 34317, 33123, 34871, 26745, 28695, 33124, 30160, 29902, 20164, 31298, 28995, 29784]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 29237, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [33123, 47238, 33176, 31298, 44121, 48735, 31397, 52105, 27030, 30252, 30444, 30490, 33036, 35094, 40295, 28237, 50442, 17231, 26916, 35416]
Topic: 8. Top: [37130, 32833, 34287, 29939, 33826, 37692, 30627, 40029, 30791, 20528, 28019, 19656, 35416, 28999, 30597, 34531, 28368, 31192, 28775, 31964]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 33036, 27643, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [28172, 28629, 17856, 34095, 40736, 24278, 29272, 31133, 33826, 30152, 32833, 22028, 28701, 27624, 30429, 28995, 42892, 24819, 21580, 30514]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [52105, 19656, 32665, 35331, 21874, 27624, 33047, 36585, 42456, 28465, 32929, 30656, 31186, 34130, 31622, 27540, 38753, 31803, 31301, 22209]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1368947017605768
sparse_theta_sp: -0.638914622569672
decorrelation: 0.01
fix: 1000000000
ext_decorr_good: 100000000
SUCCESS: less bad topics
num_topics: {'good': 13, 'bad': 2, 'not_good': 7, 'total_bad': 52}
19

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8b899c10>, 'ext_decorr_good': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f7b71767100>}
Topic: 0. Top: [37130, 32833, 33826, 37692, 30627, 34287, 29939, 40029, 28019, 20528, 30597, 30791, 34531, 28999, 35416, 19656, 28368, 27300, 33123, 31964]
Topic: 1. Top: [33484, 27185, 20673, 26239, 38446, 42166, 28992, 31502, 43613, 32665, 20528, 21001, 46583, 41427, 44211, 52456, 28019, 28146, 33761, 26809]
Topic: 2. Top: [28172, 52105, 21874, 28465, 27624, 35842, 19656, 36585, 28629, 22422, 28701, 33047, 33123, 21650, 32510, 30656, 47238, 32665, 26627, 34095]
Topic: 3. Top: [30339, 32254, 33036, 29096, 34317, 30252, 37712, 30887, 28453, 37631, 28016, 47238, 45183, 29684, 30416, 20581, 30795, 29237, 30082, 32449]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 29237, 29096, 21347, 29453]
Topic: 5. Top: [47238, 29237, 33123, 33125, 30339, 31298, 33176, 29282, 34317, 32510, 28695, 33124, 26745, 29902, 30252, 52105, 28701, 30160, 34871, 29684]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 29237, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [29282, 33036, 20164, 32510, 33125, 28701, 32833, 30152, 32678, 34871, 35023, 45841, 44259, 19828, 30160, 28995, 29784, 32939, 27136, 27970]
Topic: 8. Top: [49838, 28100, 32833, 26190, 42030, 28095, 31374, 40409, 29939, 52215, 32717, 41831, 30119, 29486, 25025, 19656, 27458, 30444, 18601, 23120]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 33036, 27643, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [34364, 34130, 38753, 35185, 29272, 24278, 29397, 27187, 26691, 26172, 24684, 25604, 26584, 33176, 32275, 27934, 30490, 25941, 33036, 36985]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [30791, 32833, 35657, 32665, 21123, 32135, 44211, 35416, 35538, 19656, 40029, 25945, 26809, 39872, 27086, 33123, 25943, 29592, 26567, 36303]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
Topic: 0. Top: [37130, 32833, 33826, 37692, 30627, 34287, 29939, 40029, 28019, 20528, 30597, 30791, 34531, 28999, 35416, 19656, 28368, 27300, 33123, 31964]
Topic: 1. Top: [33484, 27185, 20673, 26239, 38446, 42166, 28992, 31502, 43613, 32665, 20528, 21001, 46583, 41427, 44211, 52456, 28019, 28146, 33761, 26809]
Topic: 2. Top: [28172, 52105, 21874, 28465, 27624, 35842, 19656, 36585, 28629, 22422, 28701, 33047, 33123, 21650, 32510, 30656, 47238, 32665, 26627, 34095]
Topic: 3. Top: [30339, 32254, 33036, 29096, 34317, 30252, 37712, 30887, 28453, 37631, 28016, 47238, 45183, 29684, 30416, 20581, 30795, 29237, 30082, 32449]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 24315, 17946, 26129, 30066, 27532, 43571, 30374, 31484, 29237, 29096, 21347, 29453]
Topic: 5. Top: [47238, 29237, 33123, 33125, 30339, 31298, 33176, 29282, 34317, 32510, 28695, 33124, 26745, 29902, 30252, 52105, 28701, 30160, 34871, 29684]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 27540, 36928, 33799, 29237, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [29282, 33036, 20164, 32510, 33125, 28701, 32833, 30152, 32678, 34871, 35023, 45841, 44259, 19828, 30160, 28995, 29784, 32939, 27136, 27970]
Topic: 8. Top: [49838, 28100, 32833, 26190, 42030, 28095, 31374, 40409, 29939, 52215, 32717, 41831, 30119, 29486, 25025, 19656, 27458, 30444, 18601, 23120]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 23798, 33036, 27643, 29453, 35189, 42639, 28992, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [34364, 34130, 38753, 35185, 29272, 24278, 29397, 27187, 26691, 26172, 24684, 25604, 26584, 33176, 32275, 27934, 30490, 25941, 33036, 36985]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [30791, 32833, 35657, 32665, 21123, 32135, 44211, 35416, 35538, 19656, 40029, 25945, 26809, 39872, 27086, 33123, 25943, 29592, 26567, 36303]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1368947017605768
sparse_theta_sp: -0.638914622569672
decorrelation: 0.01
fix: 1000000000
ext_decorr_good: 100000000
DOWNFALL: more bad topics...
num_topics: {'good': 13, 'bad': 3, 'not_good': 7, 'total_bad': 55}
(1, 1, 0)
0
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
Topic: 0. Top: [32833, 40029, 33826, 30791, 37692, 28368, 19656, 28999, 27300, 35416, 28775, 25945, 25220, 41831, 26306, 29939, 33036, 37130, 38446, 27264]
Topic: 1. Top: [36195, 42454, 30130, 34207, 27360, 30827, 32833, 24160, 32028, 31683, 47035, 48735, 40820, 27934, 33726, 29464, 28122, 36226, 29858, 38105]
Topic: 2. Top: [43613, 30791, 32833, 32665, 27086, 44211, 33123, 33484, 31997, 21123, 35416, 35657, 32135, 25289, 29331, 20673, 34170, 23885, 39872, 38446]
Topic: 3. Top: [30339, 28016, 47238, 29237, 33036, 30252, 29096, 27030, 47035, 30887, 34317, 32254, 29684, 31298, 31397, 17231, 30795, 37492, 37631, 48735]
Topic: 4. Top: [28172, 35842, 28465, 22422, 28629, 27624, 21650, 49838, 36585, 29272, 30656, 40295, 24278, 40736, 31622, 17856, 27066, 29834, 34095, 52105]
Topic: 5. Top: [29385, 32833, 32942, 28820, 36874, 29939, 50360, 46187, 31059, 24494, 44833, 37553, 28019, 35189, 27643, 25902, 28992, 39575, 35113, 23798]
Topic: 6. Top: [29453, 36383, 29116, 26627, 31186, 29237, 29282, 32833, 40999, 51040, 32510, 35708, 34014, 51902, 32678, 51496, 35189, 29096, 28406, 36928]
Topic: 7. Top: [28884, 35023, 33036, 20164, 29939, 27187, 27587, 51610, 30152, 24317, 29085, 28701, 33006, 37168, 36515, 27970, 38087, 33124, 21347, 32510]
Topic: 8. Top: [33123, 33125, 47238, 29282, 28701, 30339, 33036, 26745, 32510, 28695, 34317, 33176, 29237, 33124, 34871, 29902, 31298, 52105, 30160, 29728]
Topic: 9. Top: [32833, 34364, 33123, 33036, 42030, 25342, 50442, 25025, 44121, 31777, 35416, 18601, 40029, 46714, 33176, 46583, 19656, 27624, 31683, 38753]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [20528, 22254, 28068, 33484, 29939, 34170, 32677, 50360, 29328, 29998, 27185, 37083, 27787, 25911, 28992, 49264, 42166, 28193, 39945, 32833]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [28651, 30339, 34089, 37833, 33036, 39719, 29237, 25706, 27532, 30596, 30066, 29282, 43571, 32510, 24315, 17946, 34317, 26129, 30252, 29096]
Topic: 15. Top: [35331, 27540, 31186, 32665, 52105, 30331, 39921, 42456, 27624, 22209, 20197, 27307, 43613, 50360, 32929, 37263, 32028, 19656, 25859, 43025]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [49838, 37130, 28100, 34287, 29939, 32833, 26190, 28095, 24123, 30627, 30597, 51400, 34531, 28019, 32942, 30119, 40409, 32717, 31192, 36268]
Topic: 0. Top: [32833, 40029, 33826, 30791, 37692, 28368, 19656, 28999, 27300, 35416, 28775, 25945, 25220, 41831, 26306, 29939, 33036, 37130, 38446, 27264]
Topic: 1. Top: [36195, 42454, 30130, 34207, 27360, 30827, 32833, 24160, 32028, 31683, 47035, 48735, 40820, 27934, 33726, 29464, 28122, 36226, 29858, 38105]
Topic: 2. Top: [43613, 30791, 32833, 32665, 27086, 44211, 33123, 33484, 31997, 21123, 35416, 35657, 32135, 25289, 29331, 20673, 34170, 23885, 39872, 38446]
Topic: 3. Top: [30339, 28016, 47238, 29237, 33036, 30252, 29096, 27030, 47035, 30887, 34317, 32254, 29684, 31298, 31397, 17231, 30795, 37492, 37631, 48735]
Topic: 4. Top: [28172, 35842, 28465, 22422, 28629, 27624, 21650, 49838, 36585, 29272, 30656, 40295, 24278, 40736, 31622, 17856, 27066, 29834, 34095, 52105]
Topic: 5. Top: [29385, 32833, 32942, 28820, 36874, 29939, 50360, 46187, 31059, 24494, 44833, 37553, 28019, 35189, 27643, 25902, 28992, 39575, 35113, 23798]
Topic: 6. Top: [29453, 36383, 29116, 26627, 31186, 29237, 29282, 32833, 40999, 51040, 32510, 35708, 34014, 51902, 32678, 51496, 35189, 29096, 28406, 36928]
Topic: 7. Top: [28884, 35023, 33036, 20164, 29939, 27187, 27587, 51610, 30152, 24317, 29085, 28701, 33006, 37168, 36515, 27970, 38087, 33124, 21347, 32510]
Topic: 8. Top: [33123, 33125, 47238, 29282, 28701, 30339, 33036, 26745, 32510, 28695, 34317, 33176, 29237, 33124, 34871, 29902, 31298, 52105, 30160, 29728]
Topic: 9. Top: [32833, 34364, 33123, 33036, 42030, 25342, 50442, 25025, 44121, 31777, 35416, 18601, 40029, 46714, 33176, 46583, 19656, 27624, 31683, 38753]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [20528, 22254, 28068, 33484, 29939, 34170, 32677, 50360, 29328, 29998, 27185, 37083, 27787, 25911, 28992, 49264, 42166, 28193, 39945, 32833]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [28651, 30339, 34089, 37833, 33036, 39719, 29237, 25706, 27532, 30596, 30066, 29282, 43571, 32510, 24315, 17946, 34317, 26129, 30252, 29096]
Topic: 15. Top: [35331, 27540, 31186, 32665, 52105, 30331, 39921, 42456, 27624, 22209, 20197, 27307, 43613, 50360, 32929, 37263, 32028, 19656, 25859, 43025]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [49838, 37130, 28100, 34287, 29939, 32833, 26190, 28095, 24123, 30627, 30597, 51400, 34531, 28019, 32942, 30119, 40409, 32717, 31192, 36268]
num_topics: {'good': 6, 'bad': 2, 'not_good': 14, 'total_bad': 2}
1

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b71145f10>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f7b8eb66e50>}
Topic: 0. Top: [29282, 33125, 30339, 32510, 33036, 28701, 28695, 34317, 20164, 34871, 30160, 17194, 26745, 29237, 33124, 35023, 33731, 47238, 31298, 33176]
Topic: 1. Top: [43613, 33484, 37130, 31997, 22254, 30627, 34170, 20673, 27185, 20528, 28068, 32665, 28992, 25289, 32677, 33826, 32833, 29939, 42166, 29331]
Topic: 2. Top: [39575, 28884, 50360, 38245, 34409, 20370, 31059, 31759, 27187, 25911, 24203, 29068, 30152, 43613, 32931, 24494, 35331, 31147, 29085, 37868]
Topic: 3. Top: [49838, 32833, 34287, 40029, 33036, 17856, 33123, 19656, 42030, 28100, 37130, 29939, 26190, 45727, 28095, 28172, 22422, 34364, 33176, 30444]
Topic: 4. Top: [52105, 19656, 32665, 42456, 21874, 33047, 27624, 30339, 33176, 47238, 28465, 29237, 29096, 27540, 35331, 31186, 29592, 32929, 36376, 27187]
Topic: 5. Top: [36383, 29453, 31186, 26627, 51040, 32833, 40999, 29116, 29237, 51902, 34014, 33799, 36928, 35750, 51496, 43613, 35708, 35189, 30130, 21129]
Topic: 6. Top: [32833, 30791, 21123, 35657, 27086, 43613, 35538, 32135, 32665, 33123, 35416, 26809, 28193, 36303, 28068, 32760, 29592, 22254, 19656, 34729]
Topic: 7. Top: [29237, 43571, 29096, 33125, 30596, 29902, 33036, 40395, 47035, 29597, 46434, 32510, 32711, 28701, 27970, 30339, 35057, 30876, 33124, 29939]
Topic: 8. Top: [32833, 30791, 38446, 40029, 25945, 44211, 20528, 35416, 32665, 46714, 33484, 29939, 26306, 37692, 19656, 39872, 25220, 45727, 33036, 29033]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 33036, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [46583, 21394, 52456, 33761, 24452, 29205, 27624, 29393, 43332, 40157, 24625, 23739, 35494, 48872, 45519, 24932, 41048, 17398, 23664, 29520]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [28651, 34089, 37833, 30339, 33036, 25706, 39719, 27532, 24315, 26129, 17946, 30374, 30252, 31484, 30066, 34317, 29453, 32510, 25420, 29282]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [47238, 30339, 33123, 33036, 31298, 30252, 34317, 33176, 29237, 28172, 29684, 48735, 31397, 44121, 33124, 29096, 26745, 17231, 30795, 28016]
Topic: 0. Top: [29282, 33125, 30339, 32510, 33036, 28701, 28695, 34317, 20164, 34871, 30160, 17194, 26745, 29237, 33124, 35023, 33731, 47238, 31298, 33176]
Topic: 1. Top: [43613, 33484, 37130, 31997, 22254, 30627, 34170, 20673, 27185, 20528, 28068, 32665, 28992, 25289, 32677, 33826, 32833, 29939, 42166, 29331]
Topic: 2. Top: [39575, 28884, 50360, 38245, 34409, 20370, 31059, 31759, 27187, 25911, 24203, 29068, 30152, 43613, 32931, 24494, 35331, 31147, 29085, 37868]
Topic: 3. Top: [49838, 32833, 34287, 40029, 33036, 17856, 33123, 19656, 42030, 28100, 37130, 29939, 26190, 45727, 28095, 28172, 22422, 34364, 33176, 30444]
Topic: 4. Top: [52105, 19656, 32665, 42456, 21874, 33047, 27624, 30339, 33176, 47238, 28465, 29237, 29096, 27540, 35331, 31186, 29592, 32929, 36376, 27187]
Topic: 5. Top: [36383, 29453, 31186, 26627, 51040, 32833, 40999, 29116, 29237, 51902, 34014, 33799, 36928, 35750, 51496, 43613, 35708, 35189, 30130, 21129]
Topic: 6. Top: [32833, 30791, 21123, 35657, 27086, 43613, 35538, 32135, 32665, 33123, 35416, 26809, 28193, 36303, 28068, 32760, 29592, 22254, 19656, 34729]
Topic: 7. Top: [29237, 43571, 29096, 33125, 30596, 29902, 33036, 40395, 47035, 29597, 46434, 32510, 32711, 28701, 27970, 30339, 35057, 30876, 33124, 29939]
Topic: 8. Top: [32833, 30791, 38446, 40029, 25945, 44211, 20528, 35416, 32665, 46714, 33484, 29939, 26306, 37692, 19656, 39872, 25220, 45727, 33036, 29033]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 33036, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [46583, 21394, 52456, 33761, 24452, 29205, 27624, 29393, 43332, 40157, 24625, 23739, 35494, 48872, 45519, 24932, 41048, 17398, 23664, 29520]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [28651, 34089, 37833, 30339, 33036, 25706, 39719, 27532, 24315, 26129, 17946, 30374, 30252, 31484, 30066, 34317, 29453, 32510, 25420, 29282]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [47238, 30339, 33123, 33036, 31298, 30252, 34317, 33176, 29237, 28172, 29684, 48735, 31397, 44121, 33124, 29096, 26745, 17231, 30795, 28016]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.0684473508802884
sparse_theta_sp: -0.319457311284836
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000000
SUCCESS: more good topics
DOWNFALL: more bad topics...
num_topics: {'good': 8, 'bad': 3, 'not_good': 12, 'total_bad': 5}
2

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b89496880>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f7b89259250>}
Topic: 0. Top: [49838, 28100, 26190, 29939, 28095, 32833, 32717, 40409, 51400, 37130, 28775, 42030, 25538, 28992, 19656, 40029, 29486, 36268, 30444, 28540]
Topic: 1. Top: [28172, 34364, 32833, 28629, 42030, 40295, 27624, 33036, 49838, 17856, 34095, 34130, 28701, 24278, 25025, 30152, 25342, 40736, 21580, 38753]
Topic: 2. Top: [36383, 51040, 40999, 32833, 29453, 51902, 27030, 51496, 28016, 29282, 22209, 34014, 49904, 30130, 31622, 29888, 26362, 30656, 21129, 51331]
Topic: 3. Top: [37833, 28651, 30596, 33036, 29453, 30339, 17946, 39719, 19828, 29259, 31484, 17905, 30066, 21347, 33480, 45841, 27985, 25706, 27315, 38087]
Topic: 4. Top: [30791, 32833, 44211, 21123, 35657, 32665, 32135, 27086, 43613, 35538, 35416, 38446, 25945, 40029, 39872, 19656, 34729, 33123, 26567, 26239]
Topic: 5. Top: [28651, 34089, 27532, 30339, 26129, 33036, 25706, 37833, 30252, 39719, 29096, 34507, 32510, 34317, 52298, 30876, 43571, 43184, 24315, 29282]
Topic: 6. Top: [43613, 33484, 31997, 22254, 39575, 25289, 32833, 50360, 26648, 20528, 29939, 32665, 20370, 38245, 34170, 27185, 28068, 49264, 20673, 29331]
Topic: 7. Top: [37692, 34287, 32833, 28019, 30627, 17856, 28368, 26306, 25466, 28999, 24123, 32942, 29939, 35416, 39661, 46951, 31192, 27264, 20528, 31964]
Topic: 8. Top: [29237, 33125, 32510, 29282, 20164, 28701, 34871, 30339, 28695, 35023, 29902, 29784, 28995, 19656, 29116, 33731, 33124, 27136, 27970, 30160]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 33036, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [31186, 29116, 27540, 43613, 35750, 29453, 39921, 20197, 26627, 35331, 27624, 31620, 35708, 35189, 36985, 27307, 52105, 26993, 43025, 42456]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [47238, 30339, 33036, 30252, 33123, 31298, 34317, 29237, 33176, 29684, 29096, 48735, 44121, 26745, 17231, 33124, 31397, 33125, 29902, 30160]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [37130, 33826, 35842, 27624, 32833, 30597, 30791, 40029, 27066, 34531, 21650, 50488, 22422, 19656, 30119, 27300, 39575, 38446, 28068, 37974]
Topic: 0. Top: [49838, 28100, 26190, 29939, 28095, 32833, 32717, 40409, 51400, 37130, 28775, 42030, 25538, 28992, 19656, 40029, 29486, 36268, 30444, 28540]
Topic: 1. Top: [28172, 34364, 32833, 28629, 42030, 40295, 27624, 33036, 49838, 17856, 34095, 34130, 28701, 24278, 25025, 30152, 25342, 40736, 21580, 38753]
Topic: 2. Top: [36383, 51040, 40999, 32833, 29453, 51902, 27030, 51496, 28016, 29282, 22209, 34014, 49904, 30130, 31622, 29888, 26362, 30656, 21129, 51331]
Topic: 3. Top: [37833, 28651, 30596, 33036, 29453, 30339, 17946, 39719, 19828, 29259, 31484, 17905, 30066, 21347, 33480, 45841, 27985, 25706, 27315, 38087]
Topic: 4. Top: [30791, 32833, 44211, 21123, 35657, 32665, 32135, 27086, 43613, 35538, 35416, 38446, 25945, 40029, 39872, 19656, 34729, 33123, 26567, 26239]
Topic: 5. Top: [28651, 34089, 27532, 30339, 26129, 33036, 25706, 37833, 30252, 39719, 29096, 34507, 32510, 34317, 52298, 30876, 43571, 43184, 24315, 29282]
Topic: 6. Top: [43613, 33484, 31997, 22254, 39575, 25289, 32833, 50360, 26648, 20528, 29939, 32665, 20370, 38245, 34170, 27185, 28068, 49264, 20673, 29331]
Topic: 7. Top: [37692, 34287, 32833, 28019, 30627, 17856, 28368, 26306, 25466, 28999, 24123, 32942, 29939, 35416, 39661, 46951, 31192, 27264, 20528, 31964]
Topic: 8. Top: [29237, 33125, 32510, 29282, 20164, 28701, 34871, 30339, 28695, 35023, 29902, 29784, 28995, 19656, 29116, 33731, 33124, 27136, 27970, 30160]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 33036, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [31186, 29116, 27540, 43613, 35750, 29453, 39921, 20197, 26627, 35331, 27624, 31620, 35708, 35189, 36985, 27307, 52105, 26993, 43025, 42456]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [47238, 30339, 33036, 30252, 33123, 31298, 34317, 29237, 33176, 29684, 29096, 48735, 44121, 26745, 17231, 33124, 31397, 33125, 29902, 30160]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [37130, 33826, 35842, 27624, 32833, 30597, 30791, 40029, 27066, 34531, 21650, 50488, 22422, 19656, 30119, 27300, 39575, 38446, 28068, 37974]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.07985524269366981
sparse_theta_sp: -0.37270019649897534
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000000
SUCCESS: less bad topics
num_topics: {'good': 8, 'bad': 2, 'not_good': 12, 'total_bad': 7}
3

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b716a88b0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f7b8eafe040>}
Topic: 0. Top: [29237, 29282, 32510, 33125, 30160, 29116, 30339, 28701, 33036, 20164, 28695, 26745, 28995, 32678, 31298, 47238, 33123, 32833, 17194, 28016]
Topic: 1. Top: [28172, 27624, 28629, 35842, 40295, 42030, 32833, 34095, 25025, 21394, 25342, 40736, 26483, 27066, 49838, 21650, 31133, 18601, 29272, 30429]
Topic: 2. Top: [42456, 30339, 35331, 29237, 30444, 36226, 28252, 40820, 52105, 47035, 27934, 19933, 22772, 31264, 27307, 31228, 26095, 45080, 29644, 33096]
Topic: 3. Top: [28651, 30339, 34089, 37833, 33036, 39719, 29237, 25706, 29282, 27532, 30066, 32510, 34317, 33125, 43571, 30252, 24315, 29096, 33124, 26129]
Topic: 4. Top: [30791, 32833, 21123, 44211, 35657, 32135, 35538, 32665, 25945, 27086, 40029, 35416, 25943, 26567, 34729, 36303, 27587, 29592, 19656, 33707]
Topic: 5. Top: [52105, 19656, 21874, 47238, 33123, 34364, 33176, 33047, 31298, 44121, 32510, 28695, 46780, 29902, 27624, 28701, 34803, 28465, 33731, 30444]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 29237, 27540, 36928, 33799, 40999, 26993, 26072, 21129, 20197, 35189, 39921]
Topic: 7. Top: [49838, 37130, 32833, 28100, 29939, 34287, 33826, 40029, 37692, 28019, 30597, 28999, 19656, 26190, 30627, 34531, 28095, 31192, 28368, 35416]
Topic: 8. Top: [30339, 30887, 30252, 29096, 47238, 47035, 29684, 34317, 32254, 33036, 30795, 29237, 37492, 28016, 31298, 37631, 17231, 28453, 31397, 17400]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 33036, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [21347, 31484, 35023, 32833, 27315, 20164, 29939, 27587, 48622, 32436, 40395, 28701, 24317, 32939, 33036, 19828, 29559, 28748, 20813, 32905]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [33484, 32833, 32665, 20528, 27185, 42166, 20673, 28068, 30791, 28992, 29939, 43613, 34170, 38446, 22254, 39872, 30627, 26306, 39945, 29331]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 28884, 29908, 34170, 27086, 34409, 23885, 31759, 29331, 29939]
Topic: 0. Top: [29237, 29282, 32510, 33125, 30160, 29116, 30339, 28701, 33036, 20164, 28695, 26745, 28995, 32678, 31298, 47238, 33123, 32833, 17194, 28016]
Topic: 1. Top: [28172, 27624, 28629, 35842, 40295, 42030, 32833, 34095, 25025, 21394, 25342, 40736, 26483, 27066, 49838, 21650, 31133, 18601, 29272, 30429]
Topic: 2. Top: [42456, 30339, 35331, 29237, 30444, 36226, 28252, 40820, 52105, 47035, 27934, 19933, 22772, 31264, 27307, 31228, 26095, 45080, 29644, 33096]
Topic: 3. Top: [28651, 30339, 34089, 37833, 33036, 39719, 29237, 25706, 29282, 27532, 30066, 32510, 34317, 33125, 43571, 30252, 24315, 29096, 33124, 26129]
Topic: 4. Top: [30791, 32833, 21123, 44211, 35657, 32135, 35538, 32665, 25945, 27086, 40029, 35416, 25943, 26567, 34729, 36303, 27587, 29592, 19656, 33707]
Topic: 5. Top: [52105, 19656, 21874, 47238, 33123, 34364, 33176, 33047, 31298, 44121, 32510, 28695, 46780, 29902, 27624, 28701, 34803, 28465, 33731, 30444]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 29237, 27540, 36928, 33799, 40999, 26993, 26072, 21129, 20197, 35189, 39921]
Topic: 7. Top: [49838, 37130, 32833, 28100, 29939, 34287, 33826, 40029, 37692, 28019, 30597, 28999, 19656, 26190, 30627, 34531, 28095, 31192, 28368, 35416]
Topic: 8. Top: [30339, 30887, 30252, 29096, 47238, 47035, 29684, 34317, 32254, 33036, 30795, 29237, 37492, 28016, 31298, 37631, 17231, 28453, 31397, 17400]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 33036, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [21347, 31484, 35023, 32833, 27315, 20164, 29939, 27587, 48622, 32436, 40395, 28701, 24317, 32939, 33036, 19828, 29559, 28748, 20813, 32905]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [33484, 32833, 32665, 20528, 27185, 42166, 20673, 28068, 30791, 28992, 29939, 43613, 34170, 38446, 22254, 39872, 30627, 26306, 39945, 29331]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 28884, 29908, 34170, 27086, 34409, 23885, 31759, 29331, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.07985524269366981
sparse_theta_sp: -0.37270019649897534
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000000
SUCCESS: more good topics
num_topics: {'good': 10, 'bad': 2, 'not_good': 10, 'total_bad': 9}
4

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b71467550>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f7b8ef8d850>}
Topic: 0. Top: [28651, 29237, 30339, 39719, 33036, 33125, 32510, 37833, 29282, 43571, 34317, 29096, 30596, 27970, 34871, 45841, 35023, 33124, 32939, 25420]
Topic: 1. Top: [30339, 47238, 30252, 28016, 33036, 29237, 34317, 29684, 29096, 31298, 17231, 48735, 30887, 33176, 31397, 30795, 27030, 37492, 32254, 47035]
Topic: 2. Top: [49838, 28100, 34287, 28095, 26190, 24123, 29939, 40409, 30119, 28019, 36268, 37130, 23120, 51400, 28992, 25538, 32833, 30627, 29972, 32677]
Topic: 3. Top: [30791, 32833, 33484, 32665, 43613, 27185, 44211, 38446, 20528, 35416, 25945, 20673, 28992, 34170, 42166, 29939, 26466, 39872, 40029, 26809]
Topic: 4. Top: [37130, 32833, 33826, 35842, 37692, 27624, 30597, 22422, 40029, 19656, 21650, 34531, 27066, 27300, 29939, 28368, 50488, 25911, 28172, 45727]
Topic: 5. Top: [32833, 21123, 35538, 25220, 19656, 35657, 30791, 32135, 25025, 37974, 46714, 31374, 18601, 33036, 47079, 27624, 41106, 46583, 28775, 51997]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 29237, 27540, 36928, 33799, 40999, 26993, 26072, 21129, 20197, 35189, 39921]
Topic: 7. Top: [28701, 33123, 29282, 28995, 32510, 26745, 28695, 33036, 33125, 33176, 30160, 34871, 33124, 28172, 47238, 20164, 32833, 29728, 30152, 52105]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 33036, 29453, 37833, 25706, 52298, 30339, 27315, 34507, 24315, 43184, 30340, 17905, 30655, 29331, 48735]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 33036, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [27587, 22099, 33707, 36303, 29592, 21123, 32833, 35657, 25943, 35331, 28068, 19828, 40521, 32135, 22107, 31228, 29559, 32665, 29834, 30152]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [19656, 32665, 21874, 33047, 26627, 52105, 26192, 31803, 42456, 32677, 31622, 29237, 32929, 31186, 27540, 28465, 27624, 36585, 27662, 28252]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 28884, 29908, 34170, 27086, 34409, 23885, 31759, 29331, 29939]
Topic: 0. Top: [28651, 29237, 30339, 39719, 33036, 33125, 32510, 37833, 29282, 43571, 34317, 29096, 30596, 27970, 34871, 45841, 35023, 33124, 32939, 25420]
Topic: 1. Top: [30339, 47238, 30252, 28016, 33036, 29237, 34317, 29684, 29096, 31298, 17231, 48735, 30887, 33176, 31397, 30795, 27030, 37492, 32254, 47035]
Topic: 2. Top: [49838, 28100, 34287, 28095, 26190, 24123, 29939, 40409, 30119, 28019, 36268, 37130, 23120, 51400, 28992, 25538, 32833, 30627, 29972, 32677]
Topic: 3. Top: [30791, 32833, 33484, 32665, 43613, 27185, 44211, 38446, 20528, 35416, 25945, 20673, 28992, 34170, 42166, 29939, 26466, 39872, 40029, 26809]
Topic: 4. Top: [37130, 32833, 33826, 35842, 37692, 27624, 30597, 22422, 40029, 19656, 21650, 34531, 27066, 27300, 29939, 28368, 50488, 25911, 28172, 45727]
Topic: 5. Top: [32833, 21123, 35538, 25220, 19656, 35657, 30791, 32135, 25025, 37974, 46714, 31374, 18601, 33036, 47079, 27624, 41106, 46583, 28775, 51997]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 29237, 27540, 36928, 33799, 40999, 26993, 26072, 21129, 20197, 35189, 39921]
Topic: 7. Top: [28701, 33123, 29282, 28995, 32510, 26745, 28695, 33036, 33125, 33176, 30160, 34871, 33124, 28172, 47238, 20164, 32833, 29728, 30152, 52105]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 33036, 29453, 37833, 25706, 52298, 30339, 27315, 34507, 24315, 43184, 30340, 17905, 30655, 29331, 48735]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 33036, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [27587, 22099, 33707, 36303, 29592, 21123, 32833, 35657, 25943, 35331, 28068, 19828, 40521, 32135, 22107, 31228, 29559, 32665, 29834, 30152]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [19656, 32665, 21874, 33047, 26627, 52105, 26192, 31803, 42456, 32677, 31622, 29237, 32929, 31186, 27540, 28465, 27624, 36585, 27662, 28252]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 28884, 29908, 34170, 27086, 34409, 23885, 31759, 29331, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.09582629123240377
sparse_theta_sp: -0.4472402357987704
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000000
SUCCESS: more good topics
SUCCESS: less bad topics
num_topics: {'good': 11, 'bad': 1, 'not_good': 9, 'total_bad': 10}
5

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8eb8f610>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f7b8eb8f7c0>}
Topic: 0. Top: [28172, 32833, 34364, 42030, 27624, 28629, 35842, 49838, 40295, 22422, 21580, 17856, 21650, 25342, 34095, 25025, 28701, 30444, 33036, 29272]
Topic: 1. Top: [49838, 37130, 32833, 28100, 29939, 34287, 40029, 33826, 37692, 19656, 30597, 30627, 26190, 28019, 28095, 28999, 34531, 35416, 31192, 28775]
Topic: 2. Top: [29237, 29282, 33125, 32510, 30339, 33036, 39719, 34871, 28701, 20164, 34317, 33124, 27970, 30160, 35023, 28695, 29784, 32939, 26745, 28651]
Topic: 3. Top: [30791, 43613, 32833, 38446, 33484, 44211, 32665, 25945, 26239, 20673, 34170, 27086, 28019, 31502, 46714, 35416, 21001, 32343, 29331, 27985]
Topic: 4. Top: [21123, 30791, 32833, 35657, 35538, 32135, 39872, 26809, 36303, 32665, 35416, 33707, 29592, 26864, 35604, 26567, 31747, 26165, 34729, 46583]
Topic: 5. Top: [22099, 22209, 30119, 29592, 28701, 28872, 28068, 17398, 24452, 29259, 25284, 21394, 25709, 30469, 48622, 34966, 31228, 35708, 36252, 17905]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 29237, 27540, 36928, 33799, 40999, 26993, 26072, 21129, 20197, 35189, 39921]
Topic: 7. Top: [52105, 19656, 21874, 32665, 33047, 31803, 42456, 26627, 28465, 31186, 32929, 26192, 35331, 27624, 32677, 36585, 27540, 36376, 47238, 30656]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 33036, 29453, 37833, 25706, 52298, 30339, 27315, 34507, 24315, 43184, 30340, 17905, 30655, 29331, 48735]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 33036, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [30339, 47238, 30252, 28016, 29237, 33036, 47035, 29096, 34317, 30887, 29684, 31298, 17231, 27030, 33176, 31397, 48735, 30795, 33124, 27934]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [27185, 20528, 28992, 33484, 28068, 42166, 32833, 27787, 29939, 39945, 25911, 32665, 29834, 52456, 26306, 22254, 49264, 35842, 30627, 17905]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 28884, 29908, 34170, 27086, 34409, 23885, 31759, 29331, 29939]
Topic: 0. Top: [28172, 32833, 34364, 42030, 27624, 28629, 35842, 49838, 40295, 22422, 21580, 17856, 21650, 25342, 34095, 25025, 28701, 30444, 33036, 29272]
Topic: 1. Top: [49838, 37130, 32833, 28100, 29939, 34287, 40029, 33826, 37692, 19656, 30597, 30627, 26190, 28019, 28095, 28999, 34531, 35416, 31192, 28775]
Topic: 2. Top: [29237, 29282, 33125, 32510, 30339, 33036, 39719, 34871, 28701, 20164, 34317, 33124, 27970, 30160, 35023, 28695, 29784, 32939, 26745, 28651]
Topic: 3. Top: [30791, 43613, 32833, 38446, 33484, 44211, 32665, 25945, 26239, 20673, 34170, 27086, 28019, 31502, 46714, 35416, 21001, 32343, 29331, 27985]
Topic: 4. Top: [21123, 30791, 32833, 35657, 35538, 32135, 39872, 26809, 36303, 32665, 35416, 33707, 29592, 26864, 35604, 26567, 31747, 26165, 34729, 46583]
Topic: 5. Top: [22099, 22209, 30119, 29592, 28701, 28872, 28068, 17398, 24452, 29259, 25284, 21394, 25709, 30469, 48622, 34966, 31228, 35708, 36252, 17905]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 29237, 27540, 36928, 33799, 40999, 26993, 26072, 21129, 20197, 35189, 39921]
Topic: 7. Top: [52105, 19656, 21874, 32665, 33047, 31803, 42456, 26627, 28465, 31186, 32929, 26192, 35331, 27624, 32677, 36585, 27540, 36376, 47238, 30656]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 33036, 29453, 37833, 25706, 52298, 30339, 27315, 34507, 24315, 43184, 30340, 17905, 30655, 29331, 48735]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 33036, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [30339, 47238, 30252, 28016, 29237, 33036, 47035, 29096, 34317, 30887, 29684, 31298, 17231, 27030, 33176, 31397, 48735, 30795, 33124, 27934]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [27185, 20528, 28992, 33484, 28068, 42166, 32833, 27787, 29939, 39945, 25911, 32665, 29834, 52456, 26306, 22254, 49264, 35842, 30627, 17905]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 28884, 29908, 34170, 27086, 34409, 23885, 31759, 29331, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1064736569248931
sparse_theta_sp: -0.4969335953319671
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000000
SUCCESS: more good topics
num_topics: {'good': 12, 'bad': 1, 'not_good': 8, 'total_bad': 11}
6

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b7165c580>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f7b8e91dc10>}
Topic: 0. Top: [32833, 30791, 37130, 27185, 29939, 37692, 30627, 40029, 33826, 20528, 38446, 28999, 30597, 35416, 19656, 25945, 34531, 32665, 28019, 28368]
Topic: 1. Top: [52105, 29237, 47238, 19656, 32510, 29902, 21874, 33125, 28995, 33176, 33123, 33047, 31298, 28701, 40029, 28465, 27970, 29282, 34871, 28695]
Topic: 2. Top: [33484, 20673, 28992, 43613, 26239, 32665, 38446, 20528, 32833, 39945, 31502, 44211, 42166, 21001, 40820, 28019, 36226, 25391, 34170, 28146]
Topic: 3. Top: [28651, 29237, 30339, 39719, 33036, 33125, 37833, 32510, 43571, 35023, 30596, 29096, 45841, 20164, 19828, 27970, 30152, 32939, 25420, 34317]
Topic: 4. Top: [21123, 30791, 32833, 35657, 35538, 32135, 39872, 26809, 36303, 32665, 35416, 33707, 29592, 26864, 35604, 26567, 31747, 26165, 34729, 46583]
Topic: 5. Top: [49838, 28172, 34287, 32833, 28100, 26190, 42030, 28095, 17856, 29939, 31374, 28629, 32717, 30119, 52215, 40029, 40409, 36268, 27624, 30444]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 29237, 27540, 36928, 33799, 40999, 26993, 26072, 21129, 20197, 35189, 39921]
Topic: 7. Top: [35331, 32665, 27624, 28068, 52456, 21394, 31228, 36376, 33746, 48811, 35842, 45935, 41427, 27307, 26584, 31803, 31186, 26072, 37263, 23916]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 33036, 29453, 37833, 25706, 52298, 30339, 27315, 34507, 24315, 43184, 30340, 17905, 30655, 29331, 48735]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 33036, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [40295, 27030, 28016, 32241, 49904, 32833, 32678, 28872, 29939, 30806, 29109, 27587, 24452, 35708, 19933, 36922, 28259, 29226, 31683, 45189]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [30339, 30252, 47238, 28016, 33036, 29096, 30887, 29684, 29237, 47035, 34317, 31298, 31397, 32254, 30795, 17231, 37492, 37631, 48735, 33124]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 28884, 29908, 34170, 27086, 34409, 23885, 31759, 29331, 29939]
Topic: 0. Top: [32833, 30791, 37130, 27185, 29939, 37692, 30627, 40029, 33826, 20528, 38446, 28999, 30597, 35416, 19656, 25945, 34531, 32665, 28019, 28368]
Topic: 1. Top: [52105, 29237, 47238, 19656, 32510, 29902, 21874, 33125, 28995, 33176, 33123, 33047, 31298, 28701, 40029, 28465, 27970, 29282, 34871, 28695]
Topic: 2. Top: [33484, 20673, 28992, 43613, 26239, 32665, 38446, 20528, 32833, 39945, 31502, 44211, 42166, 21001, 40820, 28019, 36226, 25391, 34170, 28146]
Topic: 3. Top: [28651, 29237, 30339, 39719, 33036, 33125, 37833, 32510, 43571, 35023, 30596, 29096, 45841, 20164, 19828, 27970, 30152, 32939, 25420, 34317]
Topic: 4. Top: [21123, 30791, 32833, 35657, 35538, 32135, 39872, 26809, 36303, 32665, 35416, 33707, 29592, 26864, 35604, 26567, 31747, 26165, 34729, 46583]
Topic: 5. Top: [49838, 28172, 34287, 32833, 28100, 26190, 42030, 28095, 17856, 29939, 31374, 28629, 32717, 30119, 52215, 40029, 40409, 36268, 27624, 30444]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 29237, 27540, 36928, 33799, 40999, 26993, 26072, 21129, 20197, 35189, 39921]
Topic: 7. Top: [35331, 32665, 27624, 28068, 52456, 21394, 31228, 36376, 33746, 48811, 35842, 45935, 41427, 27307, 26584, 31803, 31186, 26072, 37263, 23916]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 33036, 29453, 37833, 25706, 52298, 30339, 27315, 34507, 24315, 43184, 30340, 17905, 30655, 29331, 48735]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 33036, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [40295, 27030, 28016, 32241, 49904, 32833, 32678, 28872, 29939, 30806, 29109, 27587, 24452, 35708, 19933, 36922, 28259, 29226, 31683, 45189]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [30339, 30252, 47238, 28016, 33036, 29096, 30887, 29684, 29237, 47035, 34317, 31298, 31397, 32254, 30795, 17231, 37492, 37631, 48735, 33124]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 28884, 29908, 34170, 27086, 34409, 23885, 31759, 29331, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.11978286404050471
sparse_theta_sp: -0.559050294748463
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000000
num_topics: {'good': 12, 'bad': 1, 'not_good': 8, 'total_bad': 12}
7

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b897453a0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f7b71669820>}
Topic: 0. Top: [30791, 28999, 32833, 40029, 29939, 52215, 33826, 25220, 19656, 27066, 32665, 50488, 34170, 52723, 28068, 35416, 37974, 20528, 25943, 28368]
Topic: 1. Top: [47238, 28016, 30339, 30252, 29237, 31298, 30887, 27030, 29684, 29096, 17231, 19656, 47035, 31397, 52105, 30444, 48735, 37492, 30795, 29902]
Topic: 2. Top: [29237, 28651, 30339, 39719, 33125, 32510, 33036, 43571, 29096, 34317, 29282, 37833, 45841, 34871, 20164, 27970, 32939, 30596, 30160, 25420]
Topic: 3. Top: [33484, 32254, 27185, 37712, 28453, 30339, 20581, 30082, 30416, 33096, 33036, 37482, 40499, 34317, 34571, 29262, 27678, 18981, 27660, 29096]
Topic: 4. Top: [21123, 30791, 32833, 35657, 35538, 32135, 39872, 26809, 36303, 32665, 35416, 33707, 29592, 26864, 35604, 26567, 31747, 26165, 34729, 46583]
Topic: 5. Top: [49838, 32833, 37130, 28100, 38446, 34287, 33484, 28019, 29939, 30627, 37692, 28992, 20528, 27185, 44211, 30597, 20673, 34531, 25945, 28095]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 29237, 27540, 36928, 33799, 40999, 26993, 26072, 21129, 20197, 35189, 39921]
Topic: 7. Top: [25052, 35023, 27187, 29597, 30130, 33006, 28884, 21100, 32343, 37168, 29085, 28252, 29008, 22786, 32174, 31298, 29559, 32470, 32483, 27835]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 33036, 29453, 37833, 25706, 52298, 30339, 27315, 34507, 24315, 43184, 30340, 17905, 30655, 29331, 48735]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 33036, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [32833, 42030, 20164, 46714, 18601, 25025, 21580, 47079, 37265, 28701, 28585, 35416, 30444, 40820, 30152, 40029, 25958, 32678, 19656, 29875]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [28172, 34364, 27624, 28629, 49838, 35842, 24278, 34095, 30656, 40736, 38753, 17856, 34130, 35185, 29834, 22422, 21650, 29272, 31133, 30429]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 28884, 29908, 34170, 27086, 34409, 23885, 31759, 29331, 29939]
Topic: 0. Top: [30791, 28999, 32833, 40029, 29939, 52215, 33826, 25220, 19656, 27066, 32665, 50488, 34170, 52723, 28068, 35416, 37974, 20528, 25943, 28368]
Topic: 1. Top: [47238, 28016, 30339, 30252, 29237, 31298, 30887, 27030, 29684, 29096, 17231, 19656, 47035, 31397, 52105, 30444, 48735, 37492, 30795, 29902]
Topic: 2. Top: [29237, 28651, 30339, 39719, 33125, 32510, 33036, 43571, 29096, 34317, 29282, 37833, 45841, 34871, 20164, 27970, 32939, 30596, 30160, 25420]
Topic: 3. Top: [33484, 32254, 27185, 37712, 28453, 30339, 20581, 30082, 30416, 33096, 33036, 37482, 40499, 34317, 34571, 29262, 27678, 18981, 27660, 29096]
Topic: 4. Top: [21123, 30791, 32833, 35657, 35538, 32135, 39872, 26809, 36303, 32665, 35416, 33707, 29592, 26864, 35604, 26567, 31747, 26165, 34729, 46583]
Topic: 5. Top: [49838, 32833, 37130, 28100, 38446, 34287, 33484, 28019, 29939, 30627, 37692, 28992, 20528, 27185, 44211, 30597, 20673, 34531, 25945, 28095]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 29237, 27540, 36928, 33799, 40999, 26993, 26072, 21129, 20197, 35189, 39921]
Topic: 7. Top: [25052, 35023, 27187, 29597, 30130, 33006, 28884, 21100, 32343, 37168, 29085, 28252, 29008, 22786, 32174, 31298, 29559, 32470, 32483, 27835]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 33036, 29453, 37833, 25706, 52298, 30339, 27315, 34507, 24315, 43184, 30340, 17905, 30655, 29331, 48735]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 33036, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [32833, 42030, 20164, 46714, 18601, 25025, 21580, 47079, 37265, 28701, 28585, 35416, 30444, 40820, 30152, 40029, 25958, 32678, 19656, 29875]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [28172, 34364, 27624, 28629, 49838, 35842, 24278, 34095, 30656, 40736, 38753, 17856, 34130, 35185, 29834, 22422, 21650, 29272, 31133, 30429]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 28884, 29908, 34170, 27086, 34409, 23885, 31759, 29331, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.11978286404050471
sparse_theta_sp: -0.559050294748463
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000000
SUCCESS: more good topics
SUCCESS: less bad topics
SUCCESS: no bad topics!
num_topics: {'good': 13, 'bad': 0, 'not_good': 7, 'total_bad': 12}
8

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b711c5130>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f7b711f2550>}
Topic: 0. Top: [30339, 47238, 29237, 30252, 29096, 29684, 28016, 34317, 31298, 17231, 33036, 29902, 48735, 47035, 30887, 31397, 33125, 33124, 33176, 33123]
Topic: 1. Top: [19656, 40029, 33176, 52105, 34364, 28995, 21580, 22209, 21874, 32833, 33123, 31298, 36585, 44121, 27624, 33036, 29784, 45727, 50442, 32510]
Topic: 2. Top: [28172, 28629, 35842, 21394, 34095, 32833, 29272, 27624, 40736, 29834, 28701, 26483, 42030, 40295, 49838, 30429, 30656, 40820, 22028, 31133]
Topic: 3. Top: [33484, 32254, 27185, 37712, 28453, 30339, 20581, 30082, 30416, 33096, 33036, 37482, 40499, 34317, 34571, 29262, 27678, 18981, 27660, 29096]
Topic: 4. Top: [21123, 30791, 32833, 35657, 35538, 32135, 39872, 26809, 36303, 32665, 35416, 33707, 29592, 26864, 35604, 26567, 31747, 26165, 34729, 46583]
Topic: 5. Top: [28651, 37833, 30596, 29237, 43571, 31484, 17946, 29597, 25706, 30876, 33480, 32573, 39719, 27970, 27934, 35057, 32343, 21347, 29205, 49444]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 29237, 27540, 36928, 33799, 40999, 26993, 26072, 21129, 20197, 35189, 39921]
Topic: 7. Top: [49838, 37130, 32833, 29939, 28100, 34287, 33826, 37692, 30627, 40029, 28019, 28999, 30597, 19656, 34531, 31192, 26190, 28095, 30791, 51400]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 33036, 29453, 37833, 25706, 52298, 30339, 27315, 34507, 24315, 43184, 30340, 17905, 30655, 29331, 48735]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 33036, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [43613, 33484, 32665, 30791, 38446, 44211, 20673, 32833, 20528, 28992, 25945, 26239, 27185, 42166, 34170, 31502, 21001, 28019, 27985, 49264]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [30339, 33036, 20164, 39719, 35023, 33125, 45841, 32510, 30152, 44259, 19828, 32939, 29282, 32678, 29259, 34317, 27754, 25420, 30160, 33124]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 28884, 29908, 34170, 27086, 34409, 23885, 31759, 29331, 29939]
Topic: 0. Top: [30339, 47238, 29237, 30252, 29096, 29684, 28016, 34317, 31298, 17231, 33036, 29902, 48735, 47035, 30887, 31397, 33125, 33124, 33176, 33123]
Topic: 1. Top: [19656, 40029, 33176, 52105, 34364, 28995, 21580, 22209, 21874, 32833, 33123, 31298, 36585, 44121, 27624, 33036, 29784, 45727, 50442, 32510]
Topic: 2. Top: [28172, 28629, 35842, 21394, 34095, 32833, 29272, 27624, 40736, 29834, 28701, 26483, 42030, 40295, 49838, 30429, 30656, 40820, 22028, 31133]
Topic: 3. Top: [33484, 32254, 27185, 37712, 28453, 30339, 20581, 30082, 30416, 33096, 33036, 37482, 40499, 34317, 34571, 29262, 27678, 18981, 27660, 29096]
Topic: 4. Top: [21123, 30791, 32833, 35657, 35538, 32135, 39872, 26809, 36303, 32665, 35416, 33707, 29592, 26864, 35604, 26567, 31747, 26165, 34729, 46583]
Topic: 5. Top: [28651, 37833, 30596, 29237, 43571, 31484, 17946, 29597, 25706, 30876, 33480, 32573, 39719, 27970, 27934, 35057, 32343, 21347, 29205, 49444]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 29237, 27540, 36928, 33799, 40999, 26993, 26072, 21129, 20197, 35189, 39921]
Topic: 7. Top: [49838, 37130, 32833, 29939, 28100, 34287, 33826, 37692, 30627, 40029, 28019, 28999, 30597, 19656, 34531, 31192, 26190, 28095, 30791, 51400]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 33036, 29453, 37833, 25706, 52298, 30339, 27315, 34507, 24315, 43184, 30340, 17905, 30655, 29331, 48735]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 33036, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [43613, 33484, 32665, 30791, 38446, 44211, 20673, 32833, 20528, 28992, 25945, 26239, 27185, 42166, 34170, 31502, 21001, 28019, 27985, 49264]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [30339, 33036, 20164, 39719, 35023, 33125, 45841, 32510, 30152, 44259, 19828, 32939, 29282, 32678, 29259, 34317, 27754, 25420, 30160, 33124]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 28884, 29908, 34170, 27086, 34409, 23885, 31759, 29331, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1368947017605768
sparse_theta_sp: -0.638914622569672
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000000
DOWNFALL: more bad topics...
num_topics: {'good': 13, 'bad': 2, 'not_good': 7, 'total_bad': 14}
9

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b711d6640>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f7b711c5c70>}
Topic: 0. Top: [28068, 35842, 21650, 20528, 27066, 50488, 39575, 32833, 25911, 28992, 29834, 27624, 27787, 52723, 31147, 45761, 29939, 52456, 42166, 51997]
Topic: 1. Top: [28172, 32833, 33484, 28629, 26239, 42030, 17856, 25025, 30152, 21580, 49838, 29272, 34095, 25342, 40736, 37265, 47079, 21001, 35416, 30429]
Topic: 2. Top: [29237, 30339, 30252, 47238, 28016, 29096, 29684, 33036, 31298, 30887, 17231, 34317, 30160, 47035, 43571, 33125, 46434, 45934, 33176, 33124]
Topic: 3. Top: [33484, 32254, 27185, 37712, 28453, 30339, 20581, 30082, 30416, 33096, 33036, 37482, 40499, 34317, 34571, 29262, 27678, 18981, 27660, 29096]
Topic: 4. Top: [21123, 30791, 32833, 35657, 35538, 32135, 39872, 26809, 36303, 32665, 35416, 33707, 29592, 26864, 35604, 26567, 31747, 26165, 34729, 46583]
Topic: 5. Top: [21874, 33047, 19656, 26627, 31803, 52105, 28465, 27624, 32665, 26192, 32929, 31622, 27030, 27540, 36585, 36376, 32677, 33746, 40295, 30656]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 29237, 27540, 36928, 33799, 40999, 26993, 26072, 21129, 20197, 35189, 39921]
Topic: 7. Top: [39719, 28651, 32510, 35023, 30596, 37833, 20164, 45841, 30152, 19828, 27970, 44259, 25420, 32939, 21347, 17946, 30374, 43571, 29096, 29559]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 33036, 29453, 37833, 25706, 52298, 30339, 27315, 34507, 24315, 43184, 30340, 17905, 30655, 29331, 48735]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 33036, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [32833, 30791, 37130, 38446, 37692, 28019, 33826, 29939, 30627, 28999, 25945, 44211, 32665, 30597, 35416, 40029, 34531, 31192, 19656, 28368]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [49838, 28100, 34287, 28095, 26190, 40409, 29939, 36268, 23120, 30119, 32717, 52215, 31374, 25538, 29972, 24123, 27321, 28540, 32833, 23333]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 28884, 29908, 34170, 27086, 34409, 23885, 31759, 29331, 29939]
Topic: 0. Top: [28068, 35842, 21650, 20528, 27066, 50488, 39575, 32833, 25911, 28992, 29834, 27624, 27787, 52723, 31147, 45761, 29939, 52456, 42166, 51997]
Topic: 1. Top: [28172, 32833, 33484, 28629, 26239, 42030, 17856, 25025, 30152, 21580, 49838, 29272, 34095, 25342, 40736, 37265, 47079, 21001, 35416, 30429]
Topic: 2. Top: [29237, 30339, 30252, 47238, 28016, 29096, 29684, 33036, 31298, 30887, 17231, 34317, 30160, 47035, 43571, 33125, 46434, 45934, 33176, 33124]
Topic: 3. Top: [33484, 32254, 27185, 37712, 28453, 30339, 20581, 30082, 30416, 33096, 33036, 37482, 40499, 34317, 34571, 29262, 27678, 18981, 27660, 29096]
Topic: 4. Top: [21123, 30791, 32833, 35657, 35538, 32135, 39872, 26809, 36303, 32665, 35416, 33707, 29592, 26864, 35604, 26567, 31747, 26165, 34729, 46583]
Topic: 5. Top: [21874, 33047, 19656, 26627, 31803, 52105, 28465, 27624, 32665, 26192, 32929, 31622, 27030, 27540, 36585, 36376, 32677, 33746, 40295, 30656]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 29237, 27540, 36928, 33799, 40999, 26993, 26072, 21129, 20197, 35189, 39921]
Topic: 7. Top: [39719, 28651, 32510, 35023, 30596, 37833, 20164, 45841, 30152, 19828, 27970, 44259, 25420, 32939, 21347, 17946, 30374, 43571, 29096, 29559]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 33036, 29453, 37833, 25706, 52298, 30339, 27315, 34507, 24315, 43184, 30340, 17905, 30655, 29331, 48735]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 33036, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [32833, 30791, 37130, 38446, 37692, 28019, 33826, 29939, 30627, 28999, 25945, 44211, 32665, 30597, 35416, 40029, 34531, 31192, 19656, 28368]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [49838, 28100, 34287, 28095, 26190, 40409, 29939, 36268, 23120, 30119, 32717, 52215, 31374, 25538, 29972, 24123, 27321, 28540, 32833, 23333]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 28884, 29908, 34170, 27086, 34409, 23885, 31759, 29331, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1368947017605768
sparse_theta_sp: -0.638914622569672
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000000
SUCCESS: more good topics
SUCCESS: less bad topics
SUCCESS: no bad topics!
num_topics: {'good': 14, 'bad': 0, 'not_good': 6, 'total_bad': 14}
10

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8f744a30>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f7b89496160>}
Topic: 0. Top: [28172, 32833, 34364, 28629, 42030, 17856, 25025, 25342, 29272, 34095, 24278, 30152, 40736, 49838, 50442, 30429, 31133, 28585, 33826, 20164]
Topic: 1. Top: [28651, 39719, 37833, 30596, 19828, 43571, 45841, 17946, 21347, 35023, 29259, 25420, 30374, 46434, 31484, 48622, 44259, 33036, 32939, 30152]
Topic: 2. Top: [37130, 32833, 30791, 29939, 37692, 20528, 33826, 30627, 30597, 28019, 28999, 34531, 19656, 32677, 35416, 28368, 31192, 27264, 27300, 32665]
Topic: 3. Top: [33484, 32254, 27185, 37712, 28453, 30339, 20581, 30082, 30416, 33096, 33036, 37482, 40499, 34317, 34571, 29262, 27678, 18981, 27660, 29096]
Topic: 4. Top: [21123, 30791, 32833, 35657, 35538, 32135, 39872, 26809, 36303, 32665, 35416, 33707, 29592, 26864, 35604, 26567, 31747, 26165, 34729, 46583]
Topic: 5. Top: [33484, 43613, 32665, 38446, 44211, 28992, 20673, 32833, 30791, 26239, 21001, 27185, 49264, 27985, 26466, 25514, 27587, 28019, 32074, 46714]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 29237, 27540, 36928, 33799, 40999, 26993, 26072, 21129, 20197, 35189, 39921]
Topic: 7. Top: [29237, 30339, 47238, 33125, 34317, 29282, 30252, 31298, 33036, 29096, 29684, 32510, 33123, 29902, 33124, 33176, 30160, 34871, 26745, 28695]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 33036, 29453, 37833, 25706, 52298, 30339, 27315, 34507, 24315, 43184, 30340, 17905, 30655, 29331, 48735]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 33036, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [35842, 27066, 50488, 21650, 27624, 28068, 39575, 26483, 21394, 34130, 28465, 30656, 17853, 40295, 52456, 45761, 17905, 32545, 37974, 25284]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [49838, 28100, 34287, 28095, 26190, 40409, 29939, 36268, 23120, 30119, 32717, 52215, 31374, 25538, 29972, 24123, 27321, 28540, 32833, 23333]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 28884, 29908, 34170, 27086, 34409, 23885, 31759, 29331, 29939]
Topic: 0. Top: [28172, 32833, 34364, 28629, 42030, 17856, 25025, 25342, 29272, 34095, 24278, 30152, 40736, 49838, 50442, 30429, 31133, 28585, 33826, 20164]
Topic: 1. Top: [28651, 39719, 37833, 30596, 19828, 43571, 45841, 17946, 21347, 35023, 29259, 25420, 30374, 46434, 31484, 48622, 44259, 33036, 32939, 30152]
Topic: 2. Top: [37130, 32833, 30791, 29939, 37692, 20528, 33826, 30627, 30597, 28019, 28999, 34531, 19656, 32677, 35416, 28368, 31192, 27264, 27300, 32665]
Topic: 3. Top: [33484, 32254, 27185, 37712, 28453, 30339, 20581, 30082, 30416, 33096, 33036, 37482, 40499, 34317, 34571, 29262, 27678, 18981, 27660, 29096]
Topic: 4. Top: [21123, 30791, 32833, 35657, 35538, 32135, 39872, 26809, 36303, 32665, 35416, 33707, 29592, 26864, 35604, 26567, 31747, 26165, 34729, 46583]
Topic: 5. Top: [33484, 43613, 32665, 38446, 44211, 28992, 20673, 32833, 30791, 26239, 21001, 27185, 49264, 27985, 26466, 25514, 27587, 28019, 32074, 46714]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 29237, 27540, 36928, 33799, 40999, 26993, 26072, 21129, 20197, 35189, 39921]
Topic: 7. Top: [29237, 30339, 47238, 33125, 34317, 29282, 30252, 31298, 33036, 29096, 29684, 32510, 33123, 29902, 33124, 33176, 30160, 34871, 26745, 28695]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 33036, 29453, 37833, 25706, 52298, 30339, 27315, 34507, 24315, 43184, 30340, 17905, 30655, 29331, 48735]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 33036, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [35842, 27066, 50488, 21650, 27624, 28068, 39575, 26483, 21394, 34130, 28465, 30656, 17853, 40295, 52456, 45761, 17905, 32545, 37974, 25284]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [49838, 28100, 34287, 28095, 26190, 40409, 29939, 36268, 23120, 30119, 32717, 52215, 31374, 25538, 29972, 24123, 27321, 28540, 32833, 23333]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 28884, 29908, 34170, 27086, 34409, 23885, 31759, 29331, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.15971048538733962
sparse_theta_sp: -0.7454003929979507
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000000
DOWNFALL: more bad topics...
num_topics: {'good': 14, 'bad': 1, 'not_good': 6, 'total_bad': 15}
11

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b713619a0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f7b8f970700>}
Topic: 0. Top: [32665, 52105, 21874, 35331, 31186, 19656, 33047, 31803, 26627, 32929, 31622, 42456, 32677, 27540, 30656, 28465, 33746, 27624, 36376, 28252]
Topic: 1. Top: [32833, 46714, 25025, 18601, 42030, 34713, 47079, 37974, 29272, 27724, 29875, 28585, 21580, 51997, 30152, 25465, 31502, 17856, 37265, 25143]
Topic: 2. Top: [28016, 27030, 30887, 30252, 40295, 47035, 29684, 31397, 30795, 17231, 29096, 48735, 37492, 30444, 37631, 49897, 49904, 32209, 28633, 22363]
Topic: 3. Top: [33484, 32254, 27185, 37712, 28453, 30339, 20581, 30082, 30416, 33096, 33036, 37482, 40499, 34317, 34571, 29262, 27678, 18981, 27660, 29096]
Topic: 4. Top: [21123, 30791, 32833, 35657, 35538, 32135, 39872, 26809, 36303, 32665, 35416, 33707, 29592, 26864, 35604, 26567, 31747, 26165, 34729, 46583]
Topic: 5. Top: [28651, 37833, 43571, 39719, 30374, 30596, 29096, 29597, 30876, 29237, 25706, 40395, 46434, 30152, 49444, 17946, 32573, 28701, 25420, 47035]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 29237, 27540, 36928, 33799, 40999, 26993, 26072, 21129, 20197, 35189, 39921]
Topic: 7. Top: [19828, 29259, 20164, 45841, 39719, 21347, 31484, 28172, 44259, 29559, 29939, 27970, 32678, 35023, 27754, 33036, 32510, 25052, 48622, 30152]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 33036, 29453, 37833, 25706, 52298, 30339, 27315, 34507, 24315, 43184, 30340, 17905, 30655, 29331, 48735]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 33036, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [32833, 30791, 37130, 38446, 20528, 33484, 37692, 32665, 28019, 29939, 33826, 30627, 43613, 44211, 25945, 28999, 30597, 34531, 27185, 28368]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [49838, 28100, 34287, 28095, 26190, 40409, 29939, 36268, 23120, 30119, 32717, 52215, 31374, 25538, 29972, 24123, 27321, 28540, 32833, 23333]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 28884, 29908, 34170, 27086, 34409, 23885, 31759, 29331, 29939]
Topic: 0. Top: [32665, 52105, 21874, 35331, 31186, 19656, 33047, 31803, 26627, 32929, 31622, 42456, 32677, 27540, 30656, 28465, 33746, 27624, 36376, 28252]
Topic: 1. Top: [32833, 46714, 25025, 18601, 42030, 34713, 47079, 37974, 29272, 27724, 29875, 28585, 21580, 51997, 30152, 25465, 31502, 17856, 37265, 25143]
Topic: 2. Top: [28016, 27030, 30887, 30252, 40295, 47035, 29684, 31397, 30795, 17231, 29096, 48735, 37492, 30444, 37631, 49897, 49904, 32209, 28633, 22363]
Topic: 3. Top: [33484, 32254, 27185, 37712, 28453, 30339, 20581, 30082, 30416, 33096, 33036, 37482, 40499, 34317, 34571, 29262, 27678, 18981, 27660, 29096]
Topic: 4. Top: [21123, 30791, 32833, 35657, 35538, 32135, 39872, 26809, 36303, 32665, 35416, 33707, 29592, 26864, 35604, 26567, 31747, 26165, 34729, 46583]
Topic: 5. Top: [28651, 37833, 43571, 39719, 30374, 30596, 29096, 29597, 30876, 29237, 25706, 40395, 46434, 30152, 49444, 17946, 32573, 28701, 25420, 47035]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 29237, 27540, 36928, 33799, 40999, 26993, 26072, 21129, 20197, 35189, 39921]
Topic: 7. Top: [19828, 29259, 20164, 45841, 39719, 21347, 31484, 28172, 44259, 29559, 29939, 27970, 32678, 35023, 27754, 33036, 32510, 25052, 48622, 30152]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 33036, 29453, 37833, 25706, 52298, 30339, 27315, 34507, 24315, 43184, 30340, 17905, 30655, 29331, 48735]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 33036, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [32833, 30791, 37130, 38446, 20528, 33484, 37692, 32665, 28019, 29939, 33826, 30627, 43613, 44211, 25945, 28999, 30597, 34531, 27185, 28368]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [49838, 28100, 34287, 28095, 26190, 40409, 29939, 36268, 23120, 30119, 32717, 52215, 31374, 25538, 29972, 24123, 27321, 28540, 32833, 23333]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 28884, 29908, 34170, 27086, 34409, 23885, 31759, 29331, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.15971048538733962
sparse_theta_sp: -0.7454003929979507
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000000
SUCCESS: less bad topics
SUCCESS: no bad topics!
num_topics: {'good': 14, 'bad': 0, 'not_good': 6, 'total_bad': 15}
12

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8eaa7a30>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f7b71669820>}
Topic: 0. Top: [28016, 30887, 30252, 29237, 27030, 29684, 29096, 17231, 31298, 31397, 49904, 30795, 29226, 48735, 37492, 45934, 30444, 37631, 27970, 27794]
Topic: 1. Top: [35331, 28068, 35842, 25025, 30656, 27624, 21394, 25911, 32665, 51997, 34130, 37974, 32833, 24684, 39575, 26584, 29939, 40295, 42456, 31228]
Topic: 2. Top: [28172, 34364, 28629, 27624, 17856, 42030, 22422, 34095, 32833, 49838, 25342, 31133, 21874, 24278, 40736, 30429, 21580, 37265, 36585, 52105]
Topic: 3. Top: [33484, 32254, 27185, 37712, 28453, 30339, 20581, 30082, 30416, 33096, 33036, 37482, 40499, 34317, 34571, 29262, 27678, 18981, 27660, 29096]
Topic: 4. Top: [21123, 30791, 32833, 35657, 35538, 32135, 39872, 26809, 36303, 32665, 35416, 33707, 29592, 26864, 35604, 26567, 31747, 26165, 34729, 46583]
Topic: 5. Top: [28651, 39719, 43571, 29096, 46434, 30152, 32939, 47035, 20164, 48622, 27754, 29597, 34871, 44259, 30160, 32711, 29939, 27780, 40395, 19330]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 29237, 27540, 36928, 33799, 40999, 26993, 26072, 21129, 20197, 35189, 39921]
Topic: 7. Top: [30596, 31484, 19828, 17946, 21347, 30374, 25420, 35023, 37833, 33006, 45841, 27315, 29559, 29259, 27970, 26004, 24317, 27587, 32436, 32833]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 33036, 29453, 37833, 25706, 52298, 30339, 27315, 34507, 24315, 43184, 30340, 17905, 30655, 29331, 48735]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 33036, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [32833, 30791, 37130, 38446, 20528, 33484, 32665, 37692, 28019, 43613, 33826, 29939, 30627, 44211, 28999, 30597, 25945, 34531, 27185, 28992]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [49838, 28100, 34287, 28095, 26190, 40409, 29939, 36268, 23120, 30119, 32717, 52215, 31374, 25538, 29972, 24123, 27321, 28540, 32833, 23333]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 28884, 29908, 34170, 27086, 34409, 23885, 31759, 29331, 29939]
Topic: 0. Top: [28016, 30887, 30252, 29237, 27030, 29684, 29096, 17231, 31298, 31397, 49904, 30795, 29226, 48735, 37492, 45934, 30444, 37631, 27970, 27794]
Topic: 1. Top: [35331, 28068, 35842, 25025, 30656, 27624, 21394, 25911, 32665, 51997, 34130, 37974, 32833, 24684, 39575, 26584, 29939, 40295, 42456, 31228]
Topic: 2. Top: [28172, 34364, 28629, 27624, 17856, 42030, 22422, 34095, 32833, 49838, 25342, 31133, 21874, 24278, 40736, 30429, 21580, 37265, 36585, 52105]
Topic: 3. Top: [33484, 32254, 27185, 37712, 28453, 30339, 20581, 30082, 30416, 33096, 33036, 37482, 40499, 34317, 34571, 29262, 27678, 18981, 27660, 29096]
Topic: 4. Top: [21123, 30791, 32833, 35657, 35538, 32135, 39872, 26809, 36303, 32665, 35416, 33707, 29592, 26864, 35604, 26567, 31747, 26165, 34729, 46583]
Topic: 5. Top: [28651, 39719, 43571, 29096, 46434, 30152, 32939, 47035, 20164, 48622, 27754, 29597, 34871, 44259, 30160, 32711, 29939, 27780, 40395, 19330]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 29237, 27540, 36928, 33799, 40999, 26993, 26072, 21129, 20197, 35189, 39921]
Topic: 7. Top: [30596, 31484, 19828, 17946, 21347, 30374, 25420, 35023, 37833, 33006, 45841, 27315, 29559, 29259, 27970, 26004, 24317, 27587, 32436, 32833]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 33036, 29453, 37833, 25706, 52298, 30339, 27315, 34507, 24315, 43184, 30340, 17905, 30655, 29331, 48735]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 33036, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [32833, 30791, 37130, 38446, 20528, 33484, 32665, 37692, 28019, 43613, 33826, 29939, 30627, 44211, 28999, 30597, 25945, 34531, 27185, 28992]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [49838, 28100, 34287, 28095, 26190, 40409, 29939, 36268, 23120, 30119, 32717, 52215, 31374, 25538, 29972, 24123, 27321, 28540, 32833, 23333]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 28884, 29908, 34170, 27086, 34409, 23885, 31759, 29331, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.15971048538733962
sparse_theta_sp: -0.7454003929979507
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000000
SUCCESS: no bad topics!
num_topics: {'good': 14, 'bad': 0, 'not_good': 6, 'total_bad': 15}
13

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8e8c0fa0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f7b716415e0>}
Topic: 0. Top: [40295, 32833, 35331, 30130, 29272, 19828, 31228, 48622, 29939, 29834, 28068, 30152, 26584, 22209, 29687, 29791, 24452, 43719, 29674, 22099]
Topic: 1. Top: [32833, 37130, 30791, 37692, 29939, 30627, 33826, 20528, 35416, 28019, 28999, 30597, 40029, 34531, 28368, 19656, 31192, 25945, 27300, 27264]
Topic: 2. Top: [26627, 21874, 19656, 33047, 32665, 32677, 31186, 52105, 28465, 31622, 27540, 32929, 31803, 26192, 31484, 36585, 27624, 29891, 27662, 30656]
Topic: 3. Top: [33484, 32254, 27185, 37712, 28453, 30339, 20581, 30082, 30416, 33096, 33036, 37482, 40499, 34317, 34571, 29262, 27678, 18981, 27660, 29096]
Topic: 4. Top: [21123, 30791, 32833, 35657, 35538, 32135, 39872, 26809, 36303, 32665, 35416, 33707, 29592, 26864, 35604, 26567, 31747, 26165, 34729, 46583]
Topic: 5. Top: [34364, 27030, 24278, 34130, 35185, 38753, 40820, 30806, 32241, 33380, 36226, 30429, 49838, 45183, 27934, 50442, 24684, 25163, 29888, 29397]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 29237, 27540, 36928, 33799, 40999, 26993, 26072, 21129, 20197, 35189, 39921]
Topic: 7. Top: [30339, 29237, 33036, 33125, 47238, 34317, 29282, 29096, 30252, 39719, 32510, 33124, 31298, 30160, 34871, 29684, 28651, 43571, 33176, 28701]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 33036, 29453, 37833, 25706, 52298, 30339, 27315, 34507, 24315, 43184, 30340, 17905, 30655, 29331, 48735]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 33036, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [33484, 43613, 38446, 44211, 20673, 28992, 26239, 32665, 32833, 31502, 21001, 41785, 28629, 28019, 27185, 32074, 20528, 27985, 32983, 41427]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [49838, 28100, 34287, 28095, 26190, 40409, 29939, 36268, 23120, 30119, 32717, 52215, 31374, 25538, 29972, 24123, 27321, 28540, 32833, 23333]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 28884, 29908, 34170, 27086, 34409, 23885, 31759, 29331, 29939]
Topic: 0. Top: [40295, 32833, 35331, 30130, 29272, 19828, 31228, 48622, 29939, 29834, 28068, 30152, 26584, 22209, 29687, 29791, 24452, 43719, 29674, 22099]
Topic: 1. Top: [32833, 37130, 30791, 37692, 29939, 30627, 33826, 20528, 35416, 28019, 28999, 30597, 40029, 34531, 28368, 19656, 31192, 25945, 27300, 27264]
Topic: 2. Top: [26627, 21874, 19656, 33047, 32665, 32677, 31186, 52105, 28465, 31622, 27540, 32929, 31803, 26192, 31484, 36585, 27624, 29891, 27662, 30656]
Topic: 3. Top: [33484, 32254, 27185, 37712, 28453, 30339, 20581, 30082, 30416, 33096, 33036, 37482, 40499, 34317, 34571, 29262, 27678, 18981, 27660, 29096]
Topic: 4. Top: [21123, 30791, 32833, 35657, 35538, 32135, 39872, 26809, 36303, 32665, 35416, 33707, 29592, 26864, 35604, 26567, 31747, 26165, 34729, 46583]
Topic: 5. Top: [34364, 27030, 24278, 34130, 35185, 38753, 40820, 30806, 32241, 33380, 36226, 30429, 49838, 45183, 27934, 50442, 24684, 25163, 29888, 29397]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 29237, 27540, 36928, 33799, 40999, 26993, 26072, 21129, 20197, 35189, 39921]
Topic: 7. Top: [30339, 29237, 33036, 33125, 47238, 34317, 29282, 29096, 30252, 39719, 32510, 33124, 31298, 30160, 34871, 29684, 28651, 43571, 33176, 28701]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 33036, 29453, 37833, 25706, 52298, 30339, 27315, 34507, 24315, 43184, 30340, 17905, 30655, 29331, 48735]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 33036, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [33484, 43613, 38446, 44211, 20673, 28992, 26239, 32665, 32833, 31502, 21001, 41785, 28629, 28019, 27185, 32074, 20528, 27985, 32983, 41427]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [49838, 28100, 34287, 28095, 26190, 40409, 29939, 36268, 23120, 30119, 32717, 52215, 31374, 25538, 29972, 24123, 27321, 28540, 32833, 23333]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 28884, 29908, 34170, 27086, 34409, 23885, 31759, 29331, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.15971048538733962
sparse_theta_sp: -0.7454003929979507
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000000
DOWNFALL: more bad topics...
num_topics: {'good': 14, 'bad': 1, 'not_good': 6, 'total_bad': 16}
14

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b890826a0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f7b71767550>}
Topic: 0. Top: [32833, 30791, 37130, 38446, 20528, 33484, 28019, 32665, 37692, 33826, 29939, 30627, 44211, 25945, 28999, 30597, 43613, 34531, 27185, 28992]
Topic: 1. Top: [28651, 29237, 39719, 30339, 43571, 33125, 32510, 37833, 33036, 30596, 27970, 29096, 32939, 35023, 44259, 19828, 20164, 45841, 25420, 30152]
Topic: 2. Top: [30152, 29834, 29272, 25025, 28172, 27587, 32833, 29875, 27575, 29791, 25337, 21580, 27724, 47079, 52190, 52723, 17856, 44826, 31228, 35657]
Topic: 3. Top: [33484, 32254, 27185, 37712, 28453, 30339, 20581, 30082, 30416, 33096, 33036, 37482, 40499, 34317, 34571, 29262, 27678, 18981, 27660, 29096]
Topic: 4. Top: [21123, 30791, 32833, 35657, 35538, 32135, 39872, 26809, 36303, 32665, 35416, 33707, 29592, 26864, 35604, 26567, 31747, 26165, 34729, 46583]
Topic: 5. Top: [27030, 26627, 47035, 33380, 29888, 28016, 32241, 30806, 28872, 26192, 28633, 45183, 49904, 48811, 31264, 24924, 30490, 30444, 17231, 29125]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 29237, 27540, 36928, 33799, 40999, 26993, 26072, 21129, 20197, 35189, 39921]
Topic: 7. Top: [32665, 52105, 21874, 22209, 35331, 31186, 33047, 19656, 32929, 30656, 31622, 27624, 42456, 28465, 36585, 30130, 27540, 27662, 31803, 32677]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 33036, 29453, 37833, 25706, 52298, 30339, 27315, 34507, 24315, 43184, 30340, 17905, 30655, 29331, 48735]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 33036, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [28172, 40295, 30887, 37492, 28016, 28629, 30252, 29684, 30795, 31298, 48735, 27794, 34095, 30429, 31397, 34012, 40736, 34809, 29096, 37631]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [49838, 28100, 34287, 28095, 26190, 40409, 29939, 36268, 23120, 30119, 32717, 52215, 31374, 25538, 29972, 24123, 27321, 28540, 32833, 23333]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 28884, 29908, 34170, 27086, 34409, 23885, 31759, 29331, 29939]
Topic: 0. Top: [32833, 30791, 37130, 38446, 20528, 33484, 28019, 32665, 37692, 33826, 29939, 30627, 44211, 25945, 28999, 30597, 43613, 34531, 27185, 28992]
Topic: 1. Top: [28651, 29237, 39719, 30339, 43571, 33125, 32510, 37833, 33036, 30596, 27970, 29096, 32939, 35023, 44259, 19828, 20164, 45841, 25420, 30152]
Topic: 2. Top: [30152, 29834, 29272, 25025, 28172, 27587, 32833, 29875, 27575, 29791, 25337, 21580, 27724, 47079, 52190, 52723, 17856, 44826, 31228, 35657]
Topic: 3. Top: [33484, 32254, 27185, 37712, 28453, 30339, 20581, 30082, 30416, 33096, 33036, 37482, 40499, 34317, 34571, 29262, 27678, 18981, 27660, 29096]
Topic: 4. Top: [21123, 30791, 32833, 35657, 35538, 32135, 39872, 26809, 36303, 32665, 35416, 33707, 29592, 26864, 35604, 26567, 31747, 26165, 34729, 46583]
Topic: 5. Top: [27030, 26627, 47035, 33380, 29888, 28016, 32241, 30806, 28872, 26192, 28633, 45183, 49904, 48811, 31264, 24924, 30490, 30444, 17231, 29125]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 29237, 27540, 36928, 33799, 40999, 26993, 26072, 21129, 20197, 35189, 39921]
Topic: 7. Top: [32665, 52105, 21874, 22209, 35331, 31186, 33047, 19656, 32929, 30656, 31622, 27624, 42456, 28465, 36585, 30130, 27540, 27662, 31803, 32677]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 33036, 29453, 37833, 25706, 52298, 30339, 27315, 34507, 24315, 43184, 30340, 17905, 30655, 29331, 48735]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 33036, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [28172, 40295, 30887, 37492, 28016, 28629, 30252, 29684, 30795, 31298, 48735, 27794, 34095, 30429, 31397, 34012, 40736, 34809, 29096, 37631]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [49838, 28100, 34287, 28095, 26190, 40409, 29939, 36268, 23120, 30119, 32717, 52215, 31374, 25538, 29972, 24123, 27321, 28540, 32833, 23333]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 28884, 29908, 34170, 27086, 34409, 23885, 31759, 29331, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.15971048538733962
sparse_theta_sp: -0.7454003929979507
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000000
SUCCESS: less bad topics
SUCCESS: no bad topics!
num_topics: {'good': 14, 'bad': 0, 'not_good': 6, 'total_bad': 16}
15

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b7141ce50>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f7b711f22b0>}
Topic: 0. Top: [30596, 29096, 43571, 35057, 29939, 27934, 40395, 26627, 37833, 30876, 27970, 29597, 40820, 45934, 27187, 25540, 28252, 25163, 46434, 27835]
Topic: 1. Top: [28016, 47035, 30252, 30887, 29684, 27030, 29237, 29096, 17231, 31298, 30339, 47238, 31397, 48735, 30444, 37492, 30795, 49904, 22363, 49897]
Topic: 2. Top: [28651, 39719, 45841, 35023, 21347, 17946, 30374, 37833, 30152, 29259, 20164, 25420, 31484, 44259, 43571, 33006, 19828, 48622, 27970, 32939]
Topic: 3. Top: [33484, 32254, 27185, 37712, 28453, 30339, 20581, 30082, 30416, 33096, 33036, 37482, 40499, 34317, 34571, 29262, 27678, 18981, 27660, 29096]
Topic: 4. Top: [21123, 30791, 32833, 35657, 35538, 32135, 39872, 26809, 36303, 32665, 35416, 33707, 29592, 26864, 35604, 26567, 31747, 26165, 34729, 46583]
Topic: 5. Top: [27587, 19828, 28748, 22209, 29559, 30656, 29939, 32833, 41427, 37988, 24317, 26004, 17398, 29328, 26407, 29687, 25420, 20350, 37202, 45138]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 29237, 27540, 36928, 33799, 40999, 26993, 26072, 21129, 20197, 35189, 39921]
Topic: 7. Top: [32833, 30791, 37130, 38446, 20528, 33484, 32665, 29939, 28019, 37692, 33826, 30627, 44211, 28999, 25945, 30597, 43613, 28992, 34531, 27185]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 33036, 29453, 37833, 25706, 52298, 30339, 27315, 34507, 24315, 43184, 30340, 17905, 30655, 29331, 48735]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 33036, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [28172, 28629, 27624, 40295, 17856, 22422, 34095, 32833, 24278, 42030, 29272, 49838, 21580, 35842, 36585, 31133, 40736, 30429, 35185, 25025]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [49838, 28100, 34287, 28095, 26190, 40409, 29939, 36268, 23120, 30119, 32717, 52215, 31374, 25538, 29972, 24123, 27321, 28540, 32833, 23333]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 28884, 29908, 34170, 27086, 34409, 23885, 31759, 29331, 29939]
Topic: 0. Top: [30596, 29096, 43571, 35057, 29939, 27934, 40395, 26627, 37833, 30876, 27970, 29597, 40820, 45934, 27187, 25540, 28252, 25163, 46434, 27835]
Topic: 1. Top: [28016, 47035, 30252, 30887, 29684, 27030, 29237, 29096, 17231, 31298, 30339, 47238, 31397, 48735, 30444, 37492, 30795, 49904, 22363, 49897]
Topic: 2. Top: [28651, 39719, 45841, 35023, 21347, 17946, 30374, 37833, 30152, 29259, 20164, 25420, 31484, 44259, 43571, 33006, 19828, 48622, 27970, 32939]
Topic: 3. Top: [33484, 32254, 27185, 37712, 28453, 30339, 20581, 30082, 30416, 33096, 33036, 37482, 40499, 34317, 34571, 29262, 27678, 18981, 27660, 29096]
Topic: 4. Top: [21123, 30791, 32833, 35657, 35538, 32135, 39872, 26809, 36303, 32665, 35416, 33707, 29592, 26864, 35604, 26567, 31747, 26165, 34729, 46583]
Topic: 5. Top: [27587, 19828, 28748, 22209, 29559, 30656, 29939, 32833, 41427, 37988, 24317, 26004, 17398, 29328, 26407, 29687, 25420, 20350, 37202, 45138]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 29237, 27540, 36928, 33799, 40999, 26993, 26072, 21129, 20197, 35189, 39921]
Topic: 7. Top: [32833, 30791, 37130, 38446, 20528, 33484, 32665, 29939, 28019, 37692, 33826, 30627, 44211, 28999, 25945, 30597, 43613, 28992, 34531, 27185]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 33036, 29453, 37833, 25706, 52298, 30339, 27315, 34507, 24315, 43184, 30340, 17905, 30655, 29331, 48735]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 33036, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [28172, 28629, 27624, 40295, 17856, 22422, 34095, 32833, 24278, 42030, 29272, 49838, 21580, 35842, 36585, 31133, 40736, 30429, 35185, 25025]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [49838, 28100, 34287, 28095, 26190, 40409, 29939, 36268, 23120, 30119, 32717, 52215, 31374, 25538, 29972, 24123, 27321, 28540, 32833, 23333]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 28884, 29908, 34170, 27086, 34409, 23885, 31759, 29331, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.15971048538733962
sparse_theta_sp: -0.7454003929979507
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000000
SUCCESS: no bad topics!
num_topics: {'good': 14, 'bad': 0, 'not_good': 6, 'total_bad': 16}
16

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8bb3f400>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f7b8bb45640>}
Topic: 0. Top: [28651, 37833, 30596, 43571, 39719, 17946, 31484, 25706, 30374, 30876, 47035, 33480, 29096, 27934, 32573, 24315, 49444, 29597, 29205, 40820]
Topic: 1. Top: [33484, 43613, 32665, 38446, 20528, 44211, 27185, 30791, 28992, 20673, 32833, 25945, 26239, 42166, 31502, 52456, 34170, 28068, 26466, 21001]
Topic: 2. Top: [29237, 33125, 20164, 32510, 35023, 30339, 19828, 32939, 34871, 27970, 44259, 45841, 39719, 21347, 30152, 29559, 29259, 29939, 32678, 29784]
Topic: 3. Top: [33484, 32254, 27185, 37712, 28453, 30339, 20581, 30082, 30416, 33096, 33036, 37482, 40499, 34317, 34571, 29262, 27678, 18981, 27660, 29096]
Topic: 4. Top: [21123, 30791, 32833, 35657, 35538, 32135, 39872, 26809, 36303, 32665, 35416, 33707, 29592, 26864, 35604, 26567, 31747, 26165, 34729, 46583]
Topic: 5. Top: [32833, 37130, 33826, 37692, 28999, 30597, 29939, 30791, 40029, 28019, 35416, 34531, 28368, 19656, 30627, 31192, 27300, 35842, 26306, 25911]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 29237, 27540, 36928, 33799, 40999, 26993, 26072, 21129, 20197, 35189, 39921]
Topic: 7. Top: [28016, 30252, 29684, 30887, 27030, 31298, 29096, 48735, 30444, 31397, 47035, 17231, 52105, 19656, 37492, 30795, 49897, 42456, 22363, 30490]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 33036, 29453, 37833, 25706, 52298, 30339, 27315, 34507, 24315, 43184, 30340, 17905, 30655, 29331, 48735]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 33036, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [28172, 34364, 28629, 40295, 34095, 24278, 29272, 49838, 40736, 17856, 30429, 35185, 25342, 31133, 27624, 42030, 29834, 34130, 21580, 27937]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [49838, 28100, 34287, 28095, 26190, 40409, 29939, 36268, 23120, 30119, 32717, 52215, 31374, 25538, 29972, 24123, 27321, 28540, 32833, 23333]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 28884, 29908, 34170, 27086, 34409, 23885, 31759, 29331, 29939]
Topic: 0. Top: [28651, 37833, 30596, 43571, 39719, 17946, 31484, 25706, 30374, 30876, 47035, 33480, 29096, 27934, 32573, 24315, 49444, 29597, 29205, 40820]
Topic: 1. Top: [33484, 43613, 32665, 38446, 20528, 44211, 27185, 30791, 28992, 20673, 32833, 25945, 26239, 42166, 31502, 52456, 34170, 28068, 26466, 21001]
Topic: 2. Top: [29237, 33125, 20164, 32510, 35023, 30339, 19828, 32939, 34871, 27970, 44259, 45841, 39719, 21347, 30152, 29559, 29259, 29939, 32678, 29784]
Topic: 3. Top: [33484, 32254, 27185, 37712, 28453, 30339, 20581, 30082, 30416, 33096, 33036, 37482, 40499, 34317, 34571, 29262, 27678, 18981, 27660, 29096]
Topic: 4. Top: [21123, 30791, 32833, 35657, 35538, 32135, 39872, 26809, 36303, 32665, 35416, 33707, 29592, 26864, 35604, 26567, 31747, 26165, 34729, 46583]
Topic: 5. Top: [32833, 37130, 33826, 37692, 28999, 30597, 29939, 30791, 40029, 28019, 35416, 34531, 28368, 19656, 30627, 31192, 27300, 35842, 26306, 25911]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 29237, 27540, 36928, 33799, 40999, 26993, 26072, 21129, 20197, 35189, 39921]
Topic: 7. Top: [28016, 30252, 29684, 30887, 27030, 31298, 29096, 48735, 30444, 31397, 47035, 17231, 52105, 19656, 37492, 30795, 49897, 42456, 22363, 30490]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 33036, 29453, 37833, 25706, 52298, 30339, 27315, 34507, 24315, 43184, 30340, 17905, 30655, 29331, 48735]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 33036, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [28172, 34364, 28629, 40295, 34095, 24278, 29272, 49838, 40736, 17856, 30429, 35185, 25342, 31133, 27624, 42030, 29834, 34130, 21580, 27937]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [49838, 28100, 34287, 28095, 26190, 40409, 29939, 36268, 23120, 30119, 32717, 52215, 31374, 25538, 29972, 24123, 27321, 28540, 32833, 23333]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 28884, 29908, 34170, 27086, 34409, 23885, 31759, 29331, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.15971048538733962
sparse_theta_sp: -0.7454003929979507
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000000
SUCCESS: more good topics
SUCCESS: no bad topics!
num_topics: {'good': 15, 'bad': 0, 'not_good': 5, 'total_bad': 16}
17

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8bb22190>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f7b716bbe20>}
Topic: 0. Top: [28651, 37833, 30596, 43571, 39719, 17946, 31484, 25706, 30374, 30876, 47035, 33480, 29096, 27934, 32573, 24315, 49444, 29597, 29205, 40820]
Topic: 1. Top: [32665, 35331, 27624, 31803, 19656, 42456, 33047, 31186, 36376, 28068, 31228, 33746, 27662, 35842, 28252, 52105, 32677, 27540, 32929, 37263]
Topic: 2. Top: [34364, 28016, 28172, 30887, 30252, 31397, 30444, 37492, 31298, 27030, 30795, 48735, 34095, 29684, 44121, 49897, 24278, 30429, 37631, 50442]
Topic: 3. Top: [33484, 32254, 27185, 37712, 28453, 30339, 20581, 30082, 30416, 33096, 33036, 37482, 40499, 34317, 34571, 29262, 27678, 18981, 27660, 29096]
Topic: 4. Top: [21123, 30791, 32833, 35657, 35538, 32135, 39872, 26809, 36303, 32665, 35416, 33707, 29592, 26864, 35604, 26567, 31747, 26165, 34729, 46583]
Topic: 5. Top: [32833, 30791, 37130, 38446, 20528, 33484, 28019, 32665, 37692, 29939, 44211, 33826, 43613, 30627, 25945, 28999, 30597, 28992, 35416, 34531]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 29237, 27540, 36928, 33799, 40999, 26993, 26072, 21129, 20197, 35189, 39921]
Topic: 7. Top: [28172, 22209, 28465, 30656, 36585, 31622, 29272, 21650, 21874, 30130, 21580, 35842, 28629, 27937, 22422, 31301, 29461, 29834, 52190, 52105]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 33036, 29453, 37833, 25706, 52298, 30339, 27315, 34507, 24315, 43184, 30340, 17905, 30655, 29331, 48735]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 33036, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [20164, 19828, 35023, 45841, 29259, 21347, 44259, 29939, 29559, 32678, 48622, 30152, 38536, 32939, 27970, 27780, 46434, 27587, 39719, 33006]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [49838, 28100, 34287, 28095, 26190, 40409, 29939, 36268, 23120, 30119, 32717, 52215, 31374, 25538, 29972, 24123, 27321, 28540, 32833, 23333]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 28884, 29908, 34170, 27086, 34409, 23885, 31759, 29331, 29939]
Topic: 0. Top: [28651, 37833, 30596, 43571, 39719, 17946, 31484, 25706, 30374, 30876, 47035, 33480, 29096, 27934, 32573, 24315, 49444, 29597, 29205, 40820]
Topic: 1. Top: [32665, 35331, 27624, 31803, 19656, 42456, 33047, 31186, 36376, 28068, 31228, 33746, 27662, 35842, 28252, 52105, 32677, 27540, 32929, 37263]
Topic: 2. Top: [34364, 28016, 28172, 30887, 30252, 31397, 30444, 37492, 31298, 27030, 30795, 48735, 34095, 29684, 44121, 49897, 24278, 30429, 37631, 50442]
Topic: 3. Top: [33484, 32254, 27185, 37712, 28453, 30339, 20581, 30082, 30416, 33096, 33036, 37482, 40499, 34317, 34571, 29262, 27678, 18981, 27660, 29096]
Topic: 4. Top: [21123, 30791, 32833, 35657, 35538, 32135, 39872, 26809, 36303, 32665, 35416, 33707, 29592, 26864, 35604, 26567, 31747, 26165, 34729, 46583]
Topic: 5. Top: [32833, 30791, 37130, 38446, 20528, 33484, 28019, 32665, 37692, 29939, 44211, 33826, 43613, 30627, 25945, 28999, 30597, 28992, 35416, 34531]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 29237, 27540, 36928, 33799, 40999, 26993, 26072, 21129, 20197, 35189, 39921]
Topic: 7. Top: [28172, 22209, 28465, 30656, 36585, 31622, 29272, 21650, 21874, 30130, 21580, 35842, 28629, 27937, 22422, 31301, 29461, 29834, 52190, 52105]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 33036, 29453, 37833, 25706, 52298, 30339, 27315, 34507, 24315, 43184, 30340, 17905, 30655, 29331, 48735]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 33036, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [20164, 19828, 35023, 45841, 29259, 21347, 44259, 29939, 29559, 32678, 48622, 30152, 38536, 32939, 27970, 27780, 46434, 27587, 39719, 33006]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [49838, 28100, 34287, 28095, 26190, 40409, 29939, 36268, 23120, 30119, 32717, 52215, 31374, 25538, 29972, 24123, 27321, 28540, 32833, 23333]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 28884, 29908, 34170, 27086, 34409, 23885, 31759, 29331, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.19165258246480754
sparse_theta_sp: -0.8944804715975408
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000000
SUCCESS: no bad topics!
num_topics: {'good': 15, 'bad': 0, 'not_good': 5, 'total_bad': 16}
18

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b714325e0>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f7b8ea2cfd0>}
Topic: 0. Top: [28651, 37833, 30596, 43571, 39719, 17946, 31484, 25706, 30374, 30876, 47035, 33480, 29096, 27934, 32573, 24315, 49444, 29597, 29205, 40820]
Topic: 1. Top: [30791, 32833, 33484, 43613, 32665, 20528, 38446, 44211, 28992, 20673, 25945, 27185, 29939, 26239, 30627, 49264, 34170, 41831, 42166, 52456]
Topic: 2. Top: [27030, 28016, 30887, 30444, 40295, 28585, 32833, 49897, 32241, 31397, 30795, 21394, 25342, 25025, 37492, 31777, 17400, 27794, 30806, 26362]
Topic: 3. Top: [33484, 32254, 27185, 37712, 28453, 30339, 20581, 30082, 30416, 33096, 33036, 37482, 40499, 34317, 34571, 29262, 27678, 18981, 27660, 29096]
Topic: 4. Top: [21123, 30791, 32833, 35657, 35538, 32135, 39872, 26809, 36303, 32665, 35416, 33707, 29592, 26864, 35604, 26567, 31747, 26165, 34729, 46583]
Topic: 5. Top: [29237, 35023, 32510, 33125, 19828, 20164, 27970, 29096, 34871, 30339, 44259, 19656, 29939, 21347, 45841, 29259, 29559, 31298, 29784, 32939]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 29237, 27540, 36928, 33799, 40999, 26993, 26072, 21129, 20197, 35189, 39921]
Topic: 7. Top: [37130, 33826, 30597, 37692, 28999, 34531, 28019, 31192, 27300, 28368, 31964, 26306, 32833, 29939, 32942, 25220, 40029, 35416, 51400, 17856]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 33036, 29453, 37833, 25706, 52298, 30339, 27315, 34507, 24315, 43184, 30340, 17905, 30655, 29331, 48735]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 33036, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [28172, 28629, 17856, 35842, 21580, 30656, 27624, 22209, 34095, 40736, 24278, 49838, 37265, 36585, 33826, 31133, 29272, 22028, 42030, 22422]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [49838, 28100, 34287, 28095, 26190, 40409, 29939, 36268, 23120, 30119, 32717, 52215, 31374, 25538, 29972, 24123, 27321, 28540, 32833, 23333]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 28884, 29908, 34170, 27086, 34409, 23885, 31759, 29331, 29939]
Topic: 0. Top: [28651, 37833, 30596, 43571, 39719, 17946, 31484, 25706, 30374, 30876, 47035, 33480, 29096, 27934, 32573, 24315, 49444, 29597, 29205, 40820]
Topic: 1. Top: [30791, 32833, 33484, 43613, 32665, 20528, 38446, 44211, 28992, 20673, 25945, 27185, 29939, 26239, 30627, 49264, 34170, 41831, 42166, 52456]
Topic: 2. Top: [27030, 28016, 30887, 30444, 40295, 28585, 32833, 49897, 32241, 31397, 30795, 21394, 25342, 25025, 37492, 31777, 17400, 27794, 30806, 26362]
Topic: 3. Top: [33484, 32254, 27185, 37712, 28453, 30339, 20581, 30082, 30416, 33096, 33036, 37482, 40499, 34317, 34571, 29262, 27678, 18981, 27660, 29096]
Topic: 4. Top: [21123, 30791, 32833, 35657, 35538, 32135, 39872, 26809, 36303, 32665, 35416, 33707, 29592, 26864, 35604, 26567, 31747, 26165, 34729, 46583]
Topic: 5. Top: [29237, 35023, 32510, 33125, 19828, 20164, 27970, 29096, 34871, 30339, 44259, 19656, 29939, 21347, 45841, 29259, 29559, 31298, 29784, 32939]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 29237, 27540, 36928, 33799, 40999, 26993, 26072, 21129, 20197, 35189, 39921]
Topic: 7. Top: [37130, 33826, 30597, 37692, 28999, 34531, 28019, 31192, 27300, 28368, 31964, 26306, 32833, 29939, 32942, 25220, 40029, 35416, 51400, 17856]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 33036, 29453, 37833, 25706, 52298, 30339, 27315, 34507, 24315, 43184, 30340, 17905, 30655, 29331, 48735]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 33036, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [28172, 28629, 17856, 35842, 21580, 30656, 27624, 22209, 34095, 40736, 24278, 49838, 37265, 36585, 33826, 31133, 29272, 22028, 42030, 22422]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [49838, 28100, 34287, 28095, 26190, 40409, 29939, 36268, 23120, 30119, 32717, 52215, 31374, 25538, 29972, 24123, 27321, 28540, 32833, 23333]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 28884, 29908, 34170, 27086, 34409, 23885, 31759, 29331, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.19165258246480754
sparse_theta_sp: -0.8944804715975408
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000000
SUCCESS: no bad topics!
num_topics: {'good': 15, 'bad': 0, 'not_good': 5, 'total_bad': 16}
19

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b89015250>, 'ext_decorr_bad': <__main__.DecorrelatorWithOtherPhiRegularizer2 object at 0x7f7b716be6d0>}
Topic: 0. Top: [28651, 37833, 30596, 43571, 39719, 17946, 31484, 25706, 30374, 30876, 47035, 33480, 29096, 27934, 32573, 24315, 49444, 29597, 29205, 40820]
Topic: 1. Top: [37130, 37692, 33826, 30627, 30791, 30597, 34531, 20528, 28368, 28019, 28999, 31192, 29939, 41831, 32833, 35842, 17856, 25220, 25911, 28775]
Topic: 2. Top: [28465, 21874, 35842, 32665, 26627, 27624, 28172, 31622, 36585, 30656, 32929, 52105, 31803, 27540, 21394, 33047, 31186, 27662, 32677, 26952]
Topic: 3. Top: [33484, 32254, 27185, 37712, 28453, 30339, 20581, 30082, 30416, 33096, 33036, 37482, 40499, 34317, 34571, 29262, 27678, 18981, 27660, 29096]
Topic: 4. Top: [21123, 30791, 32833, 35657, 35538, 32135, 39872, 26809, 36303, 32665, 35416, 33707, 29592, 26864, 35604, 26567, 31747, 26165, 34729, 46583]
Topic: 5. Top: [29237, 31298, 30252, 28016, 29684, 17231, 31397, 29096, 27030, 33176, 48735, 30444, 30490, 30795, 52105, 29902, 30887, 40295, 30160, 44121]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 29237, 27540, 36928, 33799, 40999, 26993, 26072, 21129, 20197, 35189, 39921]
Topic: 7. Top: [33484, 32833, 43613, 38446, 44211, 32665, 28992, 27185, 20673, 30791, 25945, 46714, 20528, 26239, 26306, 28019, 42166, 31502, 21001, 25025]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 33036, 29453, 37833, 25706, 52298, 30339, 27315, 34507, 24315, 43184, 30340, 17905, 30655, 29331, 48735]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 33036, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [34364, 35331, 34130, 38753, 29272, 35185, 24278, 45183, 26584, 24684, 26691, 31228, 29834, 30152, 29397, 17313, 43719, 25604, 28068, 52190]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [49838, 28100, 34287, 28095, 26190, 40409, 29939, 36268, 23120, 30119, 32717, 52215, 31374, 25538, 29972, 24123, 27321, 28540, 32833, 23333]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 28884, 29908, 34170, 27086, 34409, 23885, 31759, 29331, 29939]
Topic: 0. Top: [28651, 37833, 30596, 43571, 39719, 17946, 31484, 25706, 30374, 30876, 47035, 33480, 29096, 27934, 32573, 24315, 49444, 29597, 29205, 40820]
Topic: 1. Top: [37130, 37692, 33826, 30627, 30791, 30597, 34531, 20528, 28368, 28019, 28999, 31192, 29939, 41831, 32833, 35842, 17856, 25220, 25911, 28775]
Topic: 2. Top: [28465, 21874, 35842, 32665, 26627, 27624, 28172, 31622, 36585, 30656, 32929, 52105, 31803, 27540, 21394, 33047, 31186, 27662, 32677, 26952]
Topic: 3. Top: [33484, 32254, 27185, 37712, 28453, 30339, 20581, 30082, 30416, 33096, 33036, 37482, 40499, 34317, 34571, 29262, 27678, 18981, 27660, 29096]
Topic: 4. Top: [21123, 30791, 32833, 35657, 35538, 32135, 39872, 26809, 36303, 32665, 35416, 33707, 29592, 26864, 35604, 26567, 31747, 26165, 34729, 46583]
Topic: 5. Top: [29237, 31298, 30252, 28016, 29684, 17231, 31397, 29096, 27030, 33176, 48735, 30444, 30490, 30795, 52105, 29902, 30887, 40295, 30160, 44121]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 51902, 26627, 35750, 34014, 29237, 27540, 36928, 33799, 40999, 26993, 26072, 21129, 20197, 35189, 39921]
Topic: 7. Top: [33484, 32833, 43613, 38446, 44211, 32665, 28992, 27185, 20673, 30791, 25945, 46714, 20528, 26239, 26306, 28019, 42166, 31502, 21001, 25025]
Topic: 8. Top: [28651, 34089, 27532, 26129, 30066, 33036, 29453, 37833, 25706, 52298, 30339, 27315, 34507, 24315, 43184, 30340, 17905, 30655, 29331, 48735]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 27643, 23798, 35189, 29453, 33036, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [34364, 35331, 34130, 38753, 29272, 35185, 24278, 45183, 26584, 24684, 26691, 31228, 29834, 30152, 29397, 17313, 43719, 25604, 28068, 52190]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 42454, 32833, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 43832, 42590, 29858, 29398, 31264, 28122, 20877]
Topic: 15. Top: [49838, 28100, 34287, 28095, 26190, 40409, 29939, 36268, 23120, 30119, 32717, 52215, 31374, 25538, 29972, 24123, 27321, 28540, 32833, 23333]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 26648, 20370, 31059, 24203, 28884, 29908, 34170, 27086, 34409, 23885, 31759, 29331, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.19165258246480754
sparse_theta_sp: -0.8944804715975408
decorrelation: 0.01
fix: 1000000000
ext_decorr_bad: 100000000
SUCCESS: no bad topics!
num_topics: {'good': 15, 'bad': 0, 'not_good': 5, 'total_bad': 16}
(1, 0, 0)
0
No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.047913145616201885
sparse_theta_sp: -0.2236201178993852
decorrelation: 0.01
None
Topic: 0. Top: [32833, 40029, 33826, 30791, 37692, 28368, 19656, 28999, 27300, 35416, 28775, 25945, 25220, 41831, 26306, 29939, 33036, 37130, 38446, 27264]
Topic: 1. Top: [36195, 42454, 30130, 34207, 27360, 30827, 32833, 24160, 32028, 31683, 47035, 48735, 40820, 27934, 33726, 29464, 28122, 36226, 29858, 38105]
Topic: 2. Top: [43613, 30791, 32833, 32665, 27086, 44211, 33123, 33484, 31997, 21123, 35416, 35657, 32135, 25289, 29331, 20673, 34170, 23885, 39872, 38446]
Topic: 3. Top: [30339, 28016, 47238, 29237, 33036, 30252, 29096, 27030, 47035, 30887, 34317, 32254, 29684, 31298, 31397, 17231, 30795, 37492, 37631, 48735]
Topic: 4. Top: [28172, 35842, 28465, 22422, 28629, 27624, 21650, 49838, 36585, 29272, 30656, 40295, 24278, 40736, 31622, 17856, 27066, 29834, 34095, 52105]
Topic: 5. Top: [29385, 32833, 32942, 28820, 36874, 29939, 50360, 46187, 31059, 24494, 44833, 37553, 28019, 35189, 27643, 25902, 28992, 39575, 35113, 23798]
Topic: 6. Top: [29453, 36383, 29116, 26627, 31186, 29237, 29282, 32833, 40999, 51040, 32510, 35708, 34014, 51902, 32678, 51496, 35189, 29096, 28406, 36928]
Topic: 7. Top: [28884, 35023, 33036, 20164, 29939, 27187, 27587, 51610, 30152, 24317, 29085, 28701, 33006, 37168, 36515, 27970, 38087, 33124, 21347, 32510]
Topic: 8. Top: [33123, 33125, 47238, 29282, 28701, 30339, 33036, 26745, 32510, 28695, 34317, 33176, 29237, 33124, 34871, 29902, 31298, 52105, 30160, 29728]
Topic: 9. Top: [32833, 34364, 33123, 33036, 42030, 25342, 50442, 25025, 44121, 31777, 35416, 18601, 40029, 46714, 33176, 46583, 19656, 27624, 31683, 38753]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [20528, 22254, 28068, 33484, 29939, 34170, 32677, 50360, 29328, 29998, 27185, 37083, 27787, 25911, 28992, 49264, 42166, 28193, 39945, 32833]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [28651, 30339, 34089, 37833, 33036, 39719, 29237, 25706, 27532, 30596, 30066, 29282, 43571, 32510, 24315, 17946, 34317, 26129, 30252, 29096]
Topic: 15. Top: [35331, 27540, 31186, 32665, 52105, 30331, 39921, 42456, 27624, 22209, 20197, 27307, 43613, 50360, 32929, 37263, 32028, 19656, 25859, 43025]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [49838, 37130, 28100, 34287, 29939, 32833, 26190, 28095, 24123, 30627, 30597, 51400, 34531, 28019, 32942, 30119, 40409, 32717, 31192, 36268]
Topic: 0. Top: [32833, 40029, 33826, 30791, 37692, 28368, 19656, 28999, 27300, 35416, 28775, 25945, 25220, 41831, 26306, 29939, 33036, 37130, 38446, 27264]
Topic: 1. Top: [36195, 42454, 30130, 34207, 27360, 30827, 32833, 24160, 32028, 31683, 47035, 48735, 40820, 27934, 33726, 29464, 28122, 36226, 29858, 38105]
Topic: 2. Top: [43613, 30791, 32833, 32665, 27086, 44211, 33123, 33484, 31997, 21123, 35416, 35657, 32135, 25289, 29331, 20673, 34170, 23885, 39872, 38446]
Topic: 3. Top: [30339, 28016, 47238, 29237, 33036, 30252, 29096, 27030, 47035, 30887, 34317, 32254, 29684, 31298, 31397, 17231, 30795, 37492, 37631, 48735]
Topic: 4. Top: [28172, 35842, 28465, 22422, 28629, 27624, 21650, 49838, 36585, 29272, 30656, 40295, 24278, 40736, 31622, 17856, 27066, 29834, 34095, 52105]
Topic: 5. Top: [29385, 32833, 32942, 28820, 36874, 29939, 50360, 46187, 31059, 24494, 44833, 37553, 28019, 35189, 27643, 25902, 28992, 39575, 35113, 23798]
Topic: 6. Top: [29453, 36383, 29116, 26627, 31186, 29237, 29282, 32833, 40999, 51040, 32510, 35708, 34014, 51902, 32678, 51496, 35189, 29096, 28406, 36928]
Topic: 7. Top: [28884, 35023, 33036, 20164, 29939, 27187, 27587, 51610, 30152, 24317, 29085, 28701, 33006, 37168, 36515, 27970, 38087, 33124, 21347, 32510]
Topic: 8. Top: [33123, 33125, 47238, 29282, 28701, 30339, 33036, 26745, 32510, 28695, 34317, 33176, 29237, 33124, 34871, 29902, 31298, 52105, 30160, 29728]
Topic: 9. Top: [32833, 34364, 33123, 33036, 42030, 25342, 50442, 25025, 44121, 31777, 35416, 18601, 40029, 46714, 33176, 46583, 19656, 27624, 31683, 38753]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [20528, 22254, 28068, 33484, 29939, 34170, 32677, 50360, 29328, 29998, 27185, 37083, 27787, 25911, 28992, 49264, 42166, 28193, 39945, 32833]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [28651, 30339, 34089, 37833, 33036, 39719, 29237, 25706, 27532, 30596, 30066, 29282, 43571, 32510, 24315, 17946, 34317, 26129, 30252, 29096]
Topic: 15. Top: [35331, 27540, 31186, 32665, 52105, 30331, 39921, 42456, 27624, 22209, 20197, 27307, 43613, 50360, 32929, 37263, 32028, 19656, 25859, 43025]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [49838, 37130, 28100, 34287, 29939, 32833, 26190, 28095, 24123, 30627, 30597, 51400, 34531, 28019, 32942, 30119, 40409, 32717, 31192, 36268]
num_topics: {'good': 6, 'bad': 2, 'not_good': 14, 'total_bad': 2}
1

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b71213220>}
Topic: 0. Top: [29282, 33125, 33036, 32510, 30339, 28701, 28695, 34317, 34871, 20164, 26745, 17194, 30160, 33123, 33124, 47238, 29237, 33176, 33731, 35023]
Topic: 1. Top: [43613, 37130, 33484, 31997, 30627, 22254, 34170, 20673, 27185, 20528, 28068, 28992, 32665, 32677, 29939, 25289, 33826, 32833, 28100, 42166]
Topic: 2. Top: [39575, 28884, 50360, 38245, 34409, 20370, 31059, 27187, 31759, 25911, 24203, 43613, 29068, 30152, 35331, 32931, 24494, 29085, 29939, 31147]
Topic: 3. Top: [49838, 32833, 33123, 34287, 33036, 40029, 17856, 28172, 19656, 42030, 26190, 29939, 28100, 34364, 45727, 22422, 33176, 37130, 28095, 30444]
Topic: 4. Top: [52105, 19656, 30339, 21874, 42456, 33047, 32665, 27624, 33176, 47238, 28465, 29237, 29096, 29592, 27540, 33123, 31186, 36376, 32929, 35331]
Topic: 5. Top: [36383, 29453, 31186, 26627, 51040, 32833, 29116, 40999, 29237, 51902, 34014, 33799, 36928, 35708, 51496, 35750, 35189, 21129, 30130, 43613]
Topic: 6. Top: [32833, 30791, 21123, 35657, 27086, 43613, 35538, 32135, 32665, 33123, 35416, 26809, 28193, 36303, 28068, 22254, 32760, 29592, 19656, 29998]
Topic: 7. Top: [29237, 43571, 29096, 33125, 33036, 29902, 32510, 30596, 28701, 47035, 40395, 30339, 29597, 27970, 33124, 46434, 32711, 26745, 35057, 30876]
Topic: 8. Top: [32833, 30791, 38446, 40029, 35416, 25945, 44211, 20528, 46714, 32665, 29939, 33484, 37692, 19656, 33036, 26306, 45727, 25220, 39872, 29033]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [46583, 21394, 52456, 33761, 24452, 29205, 27624, 29393, 43332, 40157, 23739, 24625, 45519, 35494, 48872, 24932, 41048, 17398, 19900, 23664]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 27532, 24315, 26129, 17946, 30252, 30374, 30066, 31484, 34317, 29453, 25420, 32510, 21347]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [47238, 30339, 33123, 33036, 31298, 30252, 34317, 33176, 29237, 29684, 33124, 44121, 26745, 31397, 48735, 29096, 17231, 33125, 28695, 29282]
Topic: 0. Top: [29282, 33125, 33036, 32510, 30339, 28701, 28695, 34317, 34871, 20164, 26745, 17194, 30160, 33123, 33124, 47238, 29237, 33176, 33731, 35023]
Topic: 1. Top: [43613, 37130, 33484, 31997, 30627, 22254, 34170, 20673, 27185, 20528, 28068, 28992, 32665, 32677, 29939, 25289, 33826, 32833, 28100, 42166]
Topic: 2. Top: [39575, 28884, 50360, 38245, 34409, 20370, 31059, 27187, 31759, 25911, 24203, 43613, 29068, 30152, 35331, 32931, 24494, 29085, 29939, 31147]
Topic: 3. Top: [49838, 32833, 33123, 34287, 33036, 40029, 17856, 28172, 19656, 42030, 26190, 29939, 28100, 34364, 45727, 22422, 33176, 37130, 28095, 30444]
Topic: 4. Top: [52105, 19656, 30339, 21874, 42456, 33047, 32665, 27624, 33176, 47238, 28465, 29237, 29096, 29592, 27540, 33123, 31186, 36376, 32929, 35331]
Topic: 5. Top: [36383, 29453, 31186, 26627, 51040, 32833, 29116, 40999, 29237, 51902, 34014, 33799, 36928, 35708, 51496, 35750, 35189, 21129, 30130, 43613]
Topic: 6. Top: [32833, 30791, 21123, 35657, 27086, 43613, 35538, 32135, 32665, 33123, 35416, 26809, 28193, 36303, 28068, 22254, 32760, 29592, 19656, 29998]
Topic: 7. Top: [29237, 43571, 29096, 33125, 33036, 29902, 32510, 30596, 28701, 47035, 40395, 30339, 29597, 27970, 33124, 46434, 32711, 26745, 35057, 30876]
Topic: 8. Top: [32833, 30791, 38446, 40029, 35416, 25945, 44211, 20528, 46714, 32665, 29939, 33484, 37692, 19656, 33036, 26306, 45727, 25220, 39872, 29033]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [46583, 21394, 52456, 33761, 24452, 29205, 27624, 29393, 43332, 40157, 23739, 24625, 45519, 35494, 48872, 24932, 41048, 17398, 19900, 23664]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 27532, 24315, 26129, 17946, 30252, 30374, 30066, 31484, 34317, 29453, 25420, 32510, 21347]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [47238, 30339, 33123, 33036, 31298, 30252, 34317, 33176, 29237, 29684, 33124, 44121, 26745, 31397, 48735, 29096, 17231, 33125, 28695, 29282]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.0684473508802884
sparse_theta_sp: -0.319457311284836
decorrelation: 0.01
fix: 1000000000
SUCCESS: more good topics
DOWNFALL: more bad topics...
num_topics: {'good': 8, 'bad': 3, 'not_good': 12, 'total_bad': 5}
2

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8bb45490>}
Topic: 0. Top: [49838, 28100, 32833, 26190, 29939, 28095, 32717, 40409, 37130, 42030, 51400, 28775, 19656, 25538, 40029, 33036, 29486, 30444, 36268, 28540]
Topic: 1. Top: [28172, 32833, 34364, 33036, 33123, 28629, 42030, 28701, 40295, 27624, 17856, 49838, 34095, 30152, 34130, 25025, 47238, 24278, 25342, 33176]
Topic: 2. Top: [36383, 51040, 40999, 32833, 29282, 27030, 51902, 29453, 28016, 51496, 22209, 34014, 33036, 49904, 30130, 29888, 26362, 31622, 28701, 32510]
Topic: 3. Top: [37833, 28651, 33036, 30596, 30339, 39719, 29453, 17946, 19828, 29259, 31484, 30066, 21347, 17905, 45841, 33480, 25706, 27985, 27970, 38087]
Topic: 4. Top: [30791, 32833, 44211, 21123, 35657, 32665, 32135, 43613, 27086, 35416, 38446, 35538, 33123, 40029, 25945, 19656, 39872, 26239, 34729, 25943]
Topic: 5. Top: [28651, 34089, 27532, 30339, 33036, 26129, 30252, 25706, 37833, 29096, 39719, 34507, 32510, 34317, 52298, 29282, 30876, 43184, 43571, 29237]
Topic: 6. Top: [43613, 33484, 31997, 22254, 39575, 25289, 50360, 29939, 32833, 26648, 20370, 20528, 38245, 32665, 28068, 34170, 27185, 49264, 29331, 20673]
Topic: 7. Top: [32833, 34287, 37692, 28019, 30627, 17856, 28999, 25466, 28368, 26306, 24123, 32942, 35416, 31964, 29939, 31192, 39661, 27264, 46951, 20528]
Topic: 8. Top: [29282, 29237, 33125, 32510, 28701, 20164, 30339, 34871, 28695, 33036, 29902, 33124, 28995, 29784, 26745, 35023, 27136, 33731, 30160, 34317]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [31186, 29116, 27540, 26627, 29453, 35750, 43613, 39921, 20197, 27624, 31620, 35331, 35189, 35708, 52105, 36985, 26993, 27307, 42456, 43025]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [47238, 30339, 33123, 33036, 34317, 30252, 31298, 33176, 29237, 29684, 26745, 33125, 33124, 44121, 29096, 31397, 48735, 17231, 29282, 52105]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [37130, 33826, 32833, 27624, 35842, 30597, 30791, 40029, 27066, 34531, 22422, 21650, 33123, 19656, 50488, 30119, 27300, 37974, 39575, 28068]
Topic: 0. Top: [49838, 28100, 32833, 26190, 29939, 28095, 32717, 40409, 37130, 42030, 51400, 28775, 19656, 25538, 40029, 33036, 29486, 30444, 36268, 28540]
Topic: 1. Top: [28172, 32833, 34364, 33036, 33123, 28629, 42030, 28701, 40295, 27624, 17856, 49838, 34095, 30152, 34130, 25025, 47238, 24278, 25342, 33176]
Topic: 2. Top: [36383, 51040, 40999, 32833, 29282, 27030, 51902, 29453, 28016, 51496, 22209, 34014, 33036, 49904, 30130, 29888, 26362, 31622, 28701, 32510]
Topic: 3. Top: [37833, 28651, 33036, 30596, 30339, 39719, 29453, 17946, 19828, 29259, 31484, 30066, 21347, 17905, 45841, 33480, 25706, 27985, 27970, 38087]
Topic: 4. Top: [30791, 32833, 44211, 21123, 35657, 32665, 32135, 43613, 27086, 35416, 38446, 35538, 33123, 40029, 25945, 19656, 39872, 26239, 34729, 25943]
Topic: 5. Top: [28651, 34089, 27532, 30339, 33036, 26129, 30252, 25706, 37833, 29096, 39719, 34507, 32510, 34317, 52298, 29282, 30876, 43184, 43571, 29237]
Topic: 6. Top: [43613, 33484, 31997, 22254, 39575, 25289, 50360, 29939, 32833, 26648, 20370, 20528, 38245, 32665, 28068, 34170, 27185, 49264, 29331, 20673]
Topic: 7. Top: [32833, 34287, 37692, 28019, 30627, 17856, 28999, 25466, 28368, 26306, 24123, 32942, 35416, 31964, 29939, 31192, 39661, 27264, 46951, 20528]
Topic: 8. Top: [29282, 29237, 33125, 32510, 28701, 20164, 30339, 34871, 28695, 33036, 29902, 33124, 28995, 29784, 26745, 35023, 27136, 33731, 30160, 34317]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [31186, 29116, 27540, 26627, 29453, 35750, 43613, 39921, 20197, 27624, 31620, 35331, 35189, 35708, 52105, 36985, 26993, 27307, 42456, 43025]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [47238, 30339, 33123, 33036, 34317, 30252, 31298, 33176, 29237, 29684, 26745, 33125, 33124, 44121, 29096, 31397, 48735, 17231, 29282, 52105]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [37130, 33826, 32833, 27624, 35842, 30597, 30791, 40029, 27066, 34531, 22422, 21650, 33123, 19656, 50488, 30119, 27300, 37974, 39575, 28068]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.07985524269366981
sparse_theta_sp: -0.37270019649897534
decorrelation: 0.01
fix: 1000000000
num_topics: {'good': 8, 'bad': 3, 'not_good': 12, 'total_bad': 8}
3

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8edae220>}
Topic: 0. Top: [29282, 29237, 32510, 33125, 33036, 29116, 30339, 30160, 26745, 28701, 32833, 32678, 20164, 28695, 33123, 17194, 28995, 39719, 36383, 31298]
Topic: 1. Top: [28172, 27624, 32833, 28629, 40295, 35842, 42030, 34095, 25025, 21394, 25342, 40736, 26483, 49838, 34364, 33036, 29272, 31133, 30429, 46583]
Topic: 2. Top: [42456, 30339, 30444, 29237, 35331, 36226, 52105, 28252, 40820, 19933, 33036, 27934, 22772, 31228, 27307, 31264, 47035, 26095, 29644, 28068]
Topic: 3. Top: [28651, 30339, 34089, 37833, 33036, 39719, 29237, 29282, 25706, 27532, 30066, 34317, 32510, 43571, 33125, 24315, 26129, 30252, 30596, 30374]
Topic: 4. Top: [30791, 32833, 21123, 44211, 35657, 32135, 40029, 35538, 35416, 25945, 32665, 33123, 27086, 25943, 26567, 19656, 36303, 29592, 34729, 27587]
Topic: 5. Top: [33123, 47238, 52105, 28701, 33176, 28695, 33125, 33036, 32510, 19656, 31298, 26745, 44121, 28995, 46780, 34871, 29282, 33124, 34317, 30339]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [49838, 32833, 37130, 28100, 29939, 34287, 33826, 40029, 19656, 37692, 28019, 30597, 28999, 26190, 33036, 35416, 34531, 28095, 30627, 31192]
Topic: 8. Top: [30339, 47238, 30252, 33036, 34317, 29237, 29684, 29096, 31298, 30887, 33123, 17231, 47035, 28016, 33124, 29902, 31397, 29282, 33176, 33125]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [33036, 35023, 21347, 20164, 32833, 31484, 28701, 19828, 32939, 29559, 33006, 27970, 48622, 30339, 27315, 33124, 29939, 27587, 28884, 30152]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [33484, 32833, 32665, 20528, 27185, 30791, 43613, 42166, 20673, 28992, 28068, 29939, 38446, 34170, 26239, 22254, 30627, 39872, 26306, 39945]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
Topic: 0. Top: [29282, 29237, 32510, 33125, 33036, 29116, 30339, 30160, 26745, 28701, 32833, 32678, 20164, 28695, 33123, 17194, 28995, 39719, 36383, 31298]
Topic: 1. Top: [28172, 27624, 32833, 28629, 40295, 35842, 42030, 34095, 25025, 21394, 25342, 40736, 26483, 49838, 34364, 33036, 29272, 31133, 30429, 46583]
Topic: 2. Top: [42456, 30339, 30444, 29237, 35331, 36226, 52105, 28252, 40820, 19933, 33036, 27934, 22772, 31228, 27307, 31264, 47035, 26095, 29644, 28068]
Topic: 3. Top: [28651, 30339, 34089, 37833, 33036, 39719, 29237, 29282, 25706, 27532, 30066, 34317, 32510, 43571, 33125, 24315, 26129, 30252, 30596, 30374]
Topic: 4. Top: [30791, 32833, 21123, 44211, 35657, 32135, 40029, 35538, 35416, 25945, 32665, 33123, 27086, 25943, 26567, 19656, 36303, 29592, 34729, 27587]
Topic: 5. Top: [33123, 47238, 52105, 28701, 33176, 28695, 33125, 33036, 32510, 19656, 31298, 26745, 44121, 28995, 46780, 34871, 29282, 33124, 34317, 30339]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [49838, 32833, 37130, 28100, 29939, 34287, 33826, 40029, 19656, 37692, 28019, 30597, 28999, 26190, 33036, 35416, 34531, 28095, 30627, 31192]
Topic: 8. Top: [30339, 47238, 30252, 33036, 34317, 29237, 29684, 29096, 31298, 30887, 33123, 17231, 47035, 28016, 33124, 29902, 31397, 29282, 33176, 33125]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [33036, 35023, 21347, 20164, 32833, 31484, 28701, 19828, 32939, 29559, 33006, 27970, 48622, 30339, 27315, 33124, 29939, 27587, 28884, 30152]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [33484, 32833, 32665, 20528, 27185, 30791, 43613, 42166, 20673, 28992, 28068, 29939, 38446, 34170, 26239, 22254, 30627, 39872, 26306, 39945]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.07985524269366981
sparse_theta_sp: -0.37270019649897534
decorrelation: 0.01
fix: 1000000000
SUCCESS: more good topics
num_topics: {'good': 10, 'bad': 3, 'not_good': 10, 'total_bad': 11}
4

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8edae2b0>}
Topic: 0. Top: [29237, 30339, 33125, 33036, 39719, 28651, 29282, 32510, 34317, 43571, 29096, 30596, 37833, 34871, 33124, 27970, 45841, 32939, 30160, 35023]
Topic: 1. Top: [30339, 47238, 33036, 30252, 33123, 29237, 31298, 34317, 29684, 33176, 28016, 29096, 48735, 17231, 44121, 29902, 33124, 31397, 29282, 33125]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [30791, 32833, 33484, 32665, 43613, 27185, 44211, 38446, 20528, 35416, 25945, 20673, 34170, 28992, 29939, 40029, 42166, 26466, 39872, 35657]
Topic: 4. Top: [28172, 37130, 32833, 35842, 27624, 33826, 22422, 40029, 30597, 19656, 33123, 37692, 21650, 33036, 34531, 27066, 27300, 28701, 45727, 29939]
Topic: 5. Top: [32833, 21123, 33036, 19656, 35538, 33123, 41831, 25220, 32135, 31374, 35657, 25025, 37974, 46714, 18601, 47079, 27624, 30791, 41106, 28775]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [29282, 33123, 28701, 33036, 26745, 32510, 33125, 28695, 28995, 34871, 33176, 33124, 30160, 47238, 29728, 20164, 32833, 17194, 34317, 29784]
Topic: 8. Top: [28651, 34089, 27532, 33036, 30339, 37833, 25706, 26129, 30066, 29453, 24315, 34507, 17905, 29331, 29282, 52298, 33176, 43184, 30252, 27315]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [27587, 22099, 33707, 29592, 32833, 36303, 19828, 25943, 33036, 35331, 29559, 35657, 40521, 28068, 30152, 32135, 22107, 31228, 48622, 29834]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [19656, 29237, 52105, 21874, 47238, 33047, 33125, 32510, 29282, 26627, 32665, 30339, 26192, 29902, 28465, 33123, 42456, 32677, 29096, 31803]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
Topic: 0. Top: [29237, 30339, 33125, 33036, 39719, 28651, 29282, 32510, 34317, 43571, 29096, 30596, 37833, 34871, 33124, 27970, 45841, 32939, 30160, 35023]
Topic: 1. Top: [30339, 47238, 33036, 30252, 33123, 29237, 31298, 34317, 29684, 33176, 28016, 29096, 48735, 17231, 44121, 29902, 33124, 31397, 29282, 33125]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [30791, 32833, 33484, 32665, 43613, 27185, 44211, 38446, 20528, 35416, 25945, 20673, 34170, 28992, 29939, 40029, 42166, 26466, 39872, 35657]
Topic: 4. Top: [28172, 37130, 32833, 35842, 27624, 33826, 22422, 40029, 30597, 19656, 33123, 37692, 21650, 33036, 34531, 27066, 27300, 28701, 45727, 29939]
Topic: 5. Top: [32833, 21123, 33036, 19656, 35538, 33123, 41831, 25220, 32135, 31374, 35657, 25025, 37974, 46714, 18601, 47079, 27624, 30791, 41106, 28775]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [29282, 33123, 28701, 33036, 26745, 32510, 33125, 28695, 28995, 34871, 33176, 33124, 30160, 47238, 29728, 20164, 32833, 17194, 34317, 29784]
Topic: 8. Top: [28651, 34089, 27532, 33036, 30339, 37833, 25706, 26129, 30066, 29453, 24315, 34507, 17905, 29331, 29282, 52298, 33176, 43184, 30252, 27315]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [27587, 22099, 33707, 29592, 32833, 36303, 19828, 25943, 33036, 35331, 29559, 35657, 40521, 28068, 30152, 32135, 22107, 31228, 48622, 29834]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [19656, 29237, 52105, 21874, 47238, 33047, 33125, 32510, 29282, 26627, 32665, 30339, 26192, 29902, 28465, 33123, 42456, 32677, 29096, 31803]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.09582629123240377
sparse_theta_sp: -0.4472402357987704
decorrelation: 0.01
fix: 1000000000
SUCCESS: more good topics
DOWNFALL: more bad topics...
num_topics: {'good': 11, 'bad': 4, 'not_good': 9, 'total_bad': 15}
5

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8f92d100>}
Topic: 0. Top: [28172, 32833, 33123, 33036, 34364, 42030, 28701, 22422, 27624, 35842, 40029, 47238, 28629, 26745, 21580, 33176, 17856, 44121, 32510, 19656]
Topic: 1. Top: [30791, 32833, 40029, 35416, 32665, 19656, 43613, 44211, 35657, 33123, 21123, 32135, 25945, 38446, 33826, 30597, 28393, 25943, 37130, 33036]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [33036, 29237, 35023, 33125, 30339, 21347, 32939, 29784, 32510, 27970, 30152, 46434, 33124, 34871, 20164, 39719, 29939, 30374, 43571, 30160]
Topic: 4. Top: [28651, 34089, 37833, 25706, 27532, 30339, 33036, 39719, 24315, 26129, 30596, 29453, 30066, 34507, 30252, 29096, 43571, 34317, 29237, 32510]
Topic: 5. Top: [29282, 28701, 32510, 33125, 29237, 30160, 28695, 33036, 26745, 32678, 34871, 33124, 30339, 17194, 20164, 34317, 39719, 27136, 33176, 28995]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [47238, 33123, 52105, 19656, 29237, 30339, 33125, 29902, 32510, 29282, 33176, 21874, 31298, 34317, 33047, 28695, 29096, 29784, 29331, 28995]
Topic: 8. Top: [28884, 30339, 29085, 46583, 20164, 31298, 43931, 33036, 30130, 29205, 19900, 31931, 29116, 21394, 29275, 27624, 30490, 32833, 33731, 33096]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [30339, 47238, 33036, 29237, 30252, 28016, 34317, 31298, 29096, 29684, 33123, 30887, 33176, 33124, 47035, 27030, 17231, 31397, 48735, 29282]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [33484, 27185, 20528, 28068, 32833, 28992, 20673, 32665, 42166, 26239, 25911, 35842, 29939, 39945, 38446, 22254, 26306, 50488, 30627, 27787]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
Topic: 0. Top: [28172, 32833, 33123, 33036, 34364, 42030, 28701, 22422, 27624, 35842, 40029, 47238, 28629, 26745, 21580, 33176, 17856, 44121, 32510, 19656]
Topic: 1. Top: [30791, 32833, 40029, 35416, 32665, 19656, 43613, 44211, 35657, 33123, 21123, 32135, 25945, 38446, 33826, 30597, 28393, 25943, 37130, 33036]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [33036, 29237, 35023, 33125, 30339, 21347, 32939, 29784, 32510, 27970, 30152, 46434, 33124, 34871, 20164, 39719, 29939, 30374, 43571, 30160]
Topic: 4. Top: [28651, 34089, 37833, 25706, 27532, 30339, 33036, 39719, 24315, 26129, 30596, 29453, 30066, 34507, 30252, 29096, 43571, 34317, 29237, 32510]
Topic: 5. Top: [29282, 28701, 32510, 33125, 29237, 30160, 28695, 33036, 26745, 32678, 34871, 33124, 30339, 17194, 20164, 34317, 39719, 27136, 33176, 28995]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [47238, 33123, 52105, 19656, 29237, 30339, 33125, 29902, 32510, 29282, 33176, 21874, 31298, 34317, 33047, 28695, 29096, 29784, 29331, 28995]
Topic: 8. Top: [28884, 30339, 29085, 46583, 20164, 31298, 43931, 33036, 30130, 29205, 19900, 31931, 29116, 21394, 29275, 27624, 30490, 32833, 33731, 33096]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [30339, 47238, 33036, 29237, 30252, 28016, 34317, 31298, 29096, 29684, 33123, 30887, 33176, 33124, 47035, 27030, 17231, 31397, 48735, 29282]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [33484, 27185, 20528, 28068, 32833, 28992, 20673, 32665, 42166, 26239, 25911, 35842, 29939, 39945, 38446, 22254, 26306, 50488, 30627, 27787]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1064736569248931
sparse_theta_sp: -0.4969335953319671
decorrelation: 0.01
fix: 1000000000
num_topics: {'good': 11, 'bad': 4, 'not_good': 9, 'total_bad': 19}
6

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8bc1c460>}
Topic: 0. Top: [32833, 30791, 21123, 35657, 44211, 38446, 30597, 25945, 35538, 27086, 32135, 33036, 26306, 29592, 33123, 26809, 36303, 26864, 27587, 34729]
Topic: 1. Top: [29282, 33123, 33125, 29237, 47238, 32510, 28701, 52105, 33176, 26745, 28695, 30339, 33036, 29902, 28995, 34871, 34317, 31298, 30160, 33124]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [33036, 30339, 29237, 33125, 35023, 29282, 32510, 39719, 19828, 45841, 30152, 32939, 21347, 44259, 20164, 27970, 29259, 29559, 25420, 30596]
Topic: 4. Top: [33484, 20528, 27185, 32833, 32665, 37692, 42166, 20673, 29939, 28068, 28992, 38446, 30627, 34170, 25911, 27300, 26239, 43613, 29331, 28019]
Topic: 5. Top: [28172, 32833, 34364, 42030, 33036, 28629, 33123, 17856, 25025, 28701, 27624, 25342, 18601, 34095, 30152, 21580, 29272, 40736, 30444, 24278]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [30791, 40029, 32833, 43613, 33826, 35416, 25943, 32665, 19656, 25220, 39872, 28393, 41831, 32135, 37974, 33123, 46583, 52456, 37130, 33707]
Topic: 8. Top: [28651, 34089, 37833, 30339, 25706, 26129, 33036, 29237, 39719, 43571, 24315, 30252, 29096, 34317, 29282, 32510, 34507, 30876, 29205, 33124]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [30066, 17905, 19933, 33036, 27532, 30444, 32833, 52298, 49904, 28049, 30339, 33176, 51694, 29331, 39329, 28623, 32678, 29068, 29674, 26466]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [30339, 47238, 33036, 30252, 29237, 28016, 34317, 31298, 29096, 29684, 30887, 27030, 33123, 31397, 33176, 47035, 30795, 48735, 17231, 33124]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
Topic: 0. Top: [32833, 30791, 21123, 35657, 44211, 38446, 30597, 25945, 35538, 27086, 32135, 33036, 26306, 29592, 33123, 26809, 36303, 26864, 27587, 34729]
Topic: 1. Top: [29282, 33123, 33125, 29237, 47238, 32510, 28701, 52105, 33176, 26745, 28695, 30339, 33036, 29902, 28995, 34871, 34317, 31298, 30160, 33124]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [33036, 30339, 29237, 33125, 35023, 29282, 32510, 39719, 19828, 45841, 30152, 32939, 21347, 44259, 20164, 27970, 29259, 29559, 25420, 30596]
Topic: 4. Top: [33484, 20528, 27185, 32833, 32665, 37692, 42166, 20673, 29939, 28068, 28992, 38446, 30627, 34170, 25911, 27300, 26239, 43613, 29331, 28019]
Topic: 5. Top: [28172, 32833, 34364, 42030, 33036, 28629, 33123, 17856, 25025, 28701, 27624, 25342, 18601, 34095, 30152, 21580, 29272, 40736, 30444, 24278]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [30791, 40029, 32833, 43613, 33826, 35416, 25943, 32665, 19656, 25220, 39872, 28393, 41831, 32135, 37974, 33123, 46583, 52456, 37130, 33707]
Topic: 8. Top: [28651, 34089, 37833, 30339, 25706, 26129, 33036, 29237, 39719, 43571, 24315, 30252, 29096, 34317, 29282, 32510, 34507, 30876, 29205, 33124]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [30066, 17905, 19933, 33036, 27532, 30444, 32833, 52298, 49904, 28049, 30339, 33176, 51694, 29331, 39329, 28623, 32678, 29068, 29674, 26466]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [30339, 47238, 33036, 30252, 29237, 28016, 34317, 31298, 29096, 29684, 30887, 27030, 33123, 31397, 33176, 47035, 30795, 48735, 17231, 33124]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1064736569248931
sparse_theta_sp: -0.4969335953319671
decorrelation: 0.01
fix: 1000000000
SUCCESS: less bad topics
num_topics: {'good': 11, 'bad': 1, 'not_good': 9, 'total_bad': 20}
7

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b711f22b0>}
Topic: 0. Top: [40029, 30791, 32833, 35416, 29939, 19656, 34170, 33826, 33036, 32665, 28393, 25943, 33123, 33176, 25220, 26745, 26567, 29282, 27136, 29766]
Topic: 1. Top: [19656, 32510, 52105, 31298, 26192, 47238, 26627, 32677, 21874, 32929, 27662, 32665, 29891, 33123, 33125, 29237, 29282, 36376, 30490, 31803]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [30339, 32254, 47238, 33036, 30887, 37631, 30252, 28016, 37492, 37712, 49897, 30444, 30795, 28453, 17400, 45183, 29096, 48735, 32449, 28633]
Topic: 4. Top: [29237, 30339, 33125, 29282, 47238, 34317, 33036, 33123, 32510, 26745, 33124, 34871, 30160, 28695, 31298, 30252, 29902, 29096, 33176, 29684]
Topic: 5. Top: [33484, 32833, 38446, 27185, 20528, 43613, 32665, 37692, 30597, 44211, 30791, 37130, 34531, 20673, 30627, 42166, 25945, 28992, 28019, 29331]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [28651, 34089, 37833, 33036, 39719, 25706, 30339, 27532, 30596, 30066, 24315, 17946, 26129, 30152, 19828, 35023, 30374, 29331, 21347, 31484]
Topic: 8. Top: [32833, 33036, 34364, 42030, 33123, 18601, 25342, 44121, 25025, 28585, 31374, 50442, 30444, 34130, 47238, 26745, 38753, 32510, 46714, 31777]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [21123, 32833, 35657, 32135, 35538, 27587, 30791, 26809, 36303, 44211, 26864, 33707, 22099, 34729, 35604, 27086, 31747, 29592, 46583, 30750]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [28172, 28701, 33123, 52105, 29282, 28995, 47238, 33176, 28695, 28465, 32510, 29331, 36585, 35842, 27624, 21580, 21874, 30152, 28629, 33125]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
Topic: 0. Top: [40029, 30791, 32833, 35416, 29939, 19656, 34170, 33826, 33036, 32665, 28393, 25943, 33123, 33176, 25220, 26745, 26567, 29282, 27136, 29766]
Topic: 1. Top: [19656, 32510, 52105, 31298, 26192, 47238, 26627, 32677, 21874, 32929, 27662, 32665, 29891, 33123, 33125, 29237, 29282, 36376, 30490, 31803]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [30339, 32254, 47238, 33036, 30887, 37631, 30252, 28016, 37492, 37712, 49897, 30444, 30795, 28453, 17400, 45183, 29096, 48735, 32449, 28633]
Topic: 4. Top: [29237, 30339, 33125, 29282, 47238, 34317, 33036, 33123, 32510, 26745, 33124, 34871, 30160, 28695, 31298, 30252, 29902, 29096, 33176, 29684]
Topic: 5. Top: [33484, 32833, 38446, 27185, 20528, 43613, 32665, 37692, 30597, 44211, 30791, 37130, 34531, 20673, 30627, 42166, 25945, 28992, 28019, 29331]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [28651, 34089, 37833, 33036, 39719, 25706, 30339, 27532, 30596, 30066, 24315, 17946, 26129, 30152, 19828, 35023, 30374, 29331, 21347, 31484]
Topic: 8. Top: [32833, 33036, 34364, 42030, 33123, 18601, 25342, 44121, 25025, 28585, 31374, 50442, 30444, 34130, 47238, 26745, 38753, 32510, 46714, 31777]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [21123, 32833, 35657, 32135, 35538, 27587, 30791, 26809, 36303, 44211, 26864, 33707, 22099, 34729, 35604, 27086, 31747, 29592, 46583, 30750]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [28172, 28701, 33123, 52105, 29282, 28995, 47238, 33176, 28695, 28465, 32510, 29331, 36585, 35842, 27624, 21580, 21874, 30152, 28629, 33125]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1064736569248931
sparse_theta_sp: -0.4969335953319671
decorrelation: 0.01
fix: 1000000000
SUCCESS: more good topics
DOWNFALL: more bad topics...
num_topics: {'good': 12, 'bad': 4, 'not_good': 8, 'total_bad': 24}
8

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8bc1d310>}
Topic: 0. Top: [28651, 34089, 30339, 26129, 33036, 30252, 34507, 29096, 19933, 52298, 25706, 29282, 43184, 32510, 48735, 34317, 37833, 29226, 33124, 43571]
Topic: 1. Top: [29282, 33123, 33125, 29237, 28701, 32510, 33036, 26745, 47238, 28695, 34871, 34317, 33176, 33124, 30339, 28995, 30160, 29902, 17194, 29728]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [30339, 47238, 29237, 33036, 30252, 34317, 31298, 29096, 29684, 33123, 28016, 31397, 19656, 30887, 33176, 29902, 33125, 52105, 17231, 47035]
Topic: 4. Top: [32833, 40029, 19656, 33036, 33123, 33826, 35416, 45727, 28393, 22422, 25220, 32981, 28368, 25911, 25025, 31374, 29939, 27300, 42030, 33176]
Topic: 5. Top: [37833, 28651, 29237, 30596, 27532, 17946, 29453, 31484, 25706, 33036, 27970, 39719, 43571, 33480, 27315, 32573, 29331, 32939, 30339, 23907]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [30791, 32833, 33484, 32665, 27185, 38446, 20528, 43613, 37692, 25945, 34170, 30597, 44211, 29939, 20673, 28992, 30627, 42166, 35416, 34531]
Topic: 8. Top: [28172, 33123, 34364, 28629, 33036, 47238, 44121, 28701, 24278, 34095, 17856, 31298, 33176, 30429, 25342, 27624, 30444, 34130, 50442, 46780]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [21123, 32833, 35657, 32135, 35538, 27587, 30791, 26809, 36303, 44211, 26864, 33707, 22099, 34729, 35604, 27086, 31747, 29592, 46583, 30750]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [30339, 33036, 45841, 35023, 29259, 19828, 39719, 44259, 30374, 32510, 33125, 32678, 25420, 20164, 30066, 32939, 30152, 29559, 32833, 21347]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
Topic: 0. Top: [28651, 34089, 30339, 26129, 33036, 30252, 34507, 29096, 19933, 52298, 25706, 29282, 43184, 32510, 48735, 34317, 37833, 29226, 33124, 43571]
Topic: 1. Top: [29282, 33123, 33125, 29237, 28701, 32510, 33036, 26745, 47238, 28695, 34871, 34317, 33176, 33124, 30339, 28995, 30160, 29902, 17194, 29728]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [30339, 47238, 29237, 33036, 30252, 34317, 31298, 29096, 29684, 33123, 28016, 31397, 19656, 30887, 33176, 29902, 33125, 52105, 17231, 47035]
Topic: 4. Top: [32833, 40029, 19656, 33036, 33123, 33826, 35416, 45727, 28393, 22422, 25220, 32981, 28368, 25911, 25025, 31374, 29939, 27300, 42030, 33176]
Topic: 5. Top: [37833, 28651, 29237, 30596, 27532, 17946, 29453, 31484, 25706, 33036, 27970, 39719, 43571, 33480, 27315, 32573, 29331, 32939, 30339, 23907]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [30791, 32833, 33484, 32665, 27185, 38446, 20528, 43613, 37692, 25945, 34170, 30597, 44211, 29939, 20673, 28992, 30627, 42166, 35416, 34531]
Topic: 8. Top: [28172, 33123, 34364, 28629, 33036, 47238, 44121, 28701, 24278, 34095, 17856, 31298, 33176, 30429, 25342, 27624, 30444, 34130, 50442, 46780]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [21123, 32833, 35657, 32135, 35538, 27587, 30791, 26809, 36303, 44211, 26864, 33707, 22099, 34729, 35604, 27086, 31747, 29592, 46583, 30750]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [30339, 33036, 45841, 35023, 29259, 19828, 39719, 44259, 30374, 32510, 33125, 32678, 25420, 20164, 30066, 32939, 30152, 29559, 32833, 21347]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.11978286404050471
sparse_theta_sp: -0.559050294748463
decorrelation: 0.01
fix: 1000000000
SUCCESS: less bad topics
num_topics: {'good': 12, 'bad': 3, 'not_good': 8, 'total_bad': 27}
9

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8bc19b50>}
Topic: 0. Top: [20528, 32833, 27185, 37692, 33484, 32665, 28068, 29939, 42166, 30627, 28992, 30791, 25911, 27300, 35842, 41831, 34170, 28368, 27264, 32677]
Topic: 1. Top: [32833, 30791, 40029, 35416, 33826, 33123, 19656, 38446, 33484, 25945, 43613, 33036, 33176, 28172, 30597, 44211, 45727, 25220, 28393, 32665]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [33125, 29282, 33123, 29237, 47238, 34317, 30339, 33036, 26745, 32510, 34871, 28695, 28701, 29902, 33124, 30160, 33176, 17194, 31298, 29784]
Topic: 4. Top: [30339, 47238, 30252, 33036, 48735, 30887, 29096, 28016, 31298, 47035, 29684, 29237, 32254, 30795, 37492, 33176, 37631, 28633, 34317, 31397]
Topic: 5. Top: [52105, 29282, 21874, 28465, 36585, 33123, 33047, 29644, 28172, 19656, 47238, 32510, 35842, 27624, 28701, 33036, 33176, 30656, 30444, 29331]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [29237, 30339, 30130, 27187, 32833, 32510, 40820, 36226, 26627, 27934, 28252, 33036, 42456, 25163, 29282, 30066, 34130, 31186, 35057, 28884]
Topic: 8. Top: [28651, 34089, 37833, 33036, 30339, 39719, 25706, 32510, 30596, 43571, 29237, 29282, 17946, 24315, 19828, 25420, 30374, 27970, 45841, 21347]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [21123, 32833, 35657, 32135, 35538, 27587, 30791, 26809, 36303, 44211, 26864, 33707, 22099, 34729, 35604, 27086, 31747, 29592, 46583, 30750]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [27532, 30655, 51694, 52298, 17905, 42892, 28049, 29453, 42560, 19933, 30778, 37833, 28623, 40295, 32597, 51608, 28322, 24325, 34089, 24985]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
Topic: 0. Top: [20528, 32833, 27185, 37692, 33484, 32665, 28068, 29939, 42166, 30627, 28992, 30791, 25911, 27300, 35842, 41831, 34170, 28368, 27264, 32677]
Topic: 1. Top: [32833, 30791, 40029, 35416, 33826, 33123, 19656, 38446, 33484, 25945, 43613, 33036, 33176, 28172, 30597, 44211, 45727, 25220, 28393, 32665]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [33125, 29282, 33123, 29237, 47238, 34317, 30339, 33036, 26745, 32510, 34871, 28695, 28701, 29902, 33124, 30160, 33176, 17194, 31298, 29784]
Topic: 4. Top: [30339, 47238, 30252, 33036, 48735, 30887, 29096, 28016, 31298, 47035, 29684, 29237, 32254, 30795, 37492, 33176, 37631, 28633, 34317, 31397]
Topic: 5. Top: [52105, 29282, 21874, 28465, 36585, 33123, 33047, 29644, 28172, 19656, 47238, 32510, 35842, 27624, 28701, 33036, 33176, 30656, 30444, 29331]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [29237, 30339, 30130, 27187, 32833, 32510, 40820, 36226, 26627, 27934, 28252, 33036, 42456, 25163, 29282, 30066, 34130, 31186, 35057, 28884]
Topic: 8. Top: [28651, 34089, 37833, 33036, 30339, 39719, 25706, 32510, 30596, 43571, 29237, 29282, 17946, 24315, 19828, 25420, 30374, 27970, 45841, 21347]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [21123, 32833, 35657, 32135, 35538, 27587, 30791, 26809, 36303, 44211, 26864, 33707, 22099, 34729, 35604, 27086, 31747, 29592, 46583, 30750]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [27532, 30655, 51694, 52298, 17905, 42892, 28049, 29453, 42560, 19933, 30778, 37833, 28623, 40295, 32597, 51608, 28322, 24325, 34089, 24985]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.11978286404050471
sparse_theta_sp: -0.559050294748463
decorrelation: 0.01
fix: 1000000000
SUCCESS: more good topics
num_topics: {'good': 13, 'bad': 3, 'not_good': 7, 'total_bad': 30}
10

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b7136adf0>}
Topic: 0. Top: [28172, 32833, 34364, 33036, 42030, 28629, 33123, 17856, 27624, 28701, 33176, 25342, 30152, 40029, 25025, 50442, 22422, 34095, 35416, 44121]
Topic: 1. Top: [33123, 47238, 33125, 28701, 52105, 33176, 31298, 32510, 29237, 28695, 30339, 28995, 29902, 34871, 29282, 33124, 29728, 26745, 34317, 19656]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [29282, 29237, 33036, 32510, 33125, 20164, 35023, 32678, 17194, 32833, 45841, 27136, 19828, 30339, 32939, 26745, 30160, 39719, 34317, 27754]
Topic: 4. Top: [28651, 30596, 30339, 17946, 39719, 31484, 21347, 30374, 37833, 33036, 46434, 33480, 27315, 40395, 27970, 30152, 25420, 32436, 44259, 33125]
Topic: 5. Top: [30791, 32665, 33484, 32833, 27185, 20528, 38446, 43613, 29939, 42166, 35416, 34170, 20673, 44211, 28068, 37692, 28992, 29331, 19656, 30627]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [30339, 47238, 33036, 29237, 30252, 28016, 34317, 29684, 29096, 30887, 47035, 31298, 27030, 31397, 30795, 17231, 32254, 29282, 33123, 17194]
Topic: 8. Top: [28651, 34089, 30339, 37833, 25706, 33036, 26129, 30252, 34507, 43571, 39719, 24315, 29096, 29237, 30066, 34317, 30876, 29205, 29282, 32510]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [21123, 32833, 35657, 32135, 35538, 27587, 30791, 26809, 36303, 44211, 26864, 33707, 22099, 34729, 35604, 27086, 31747, 29592, 46583, 30750]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [27532, 30655, 51694, 52298, 17905, 42892, 28049, 29453, 42560, 19933, 30778, 37833, 28623, 40295, 32597, 51608, 28322, 24325, 34089, 24985]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
Topic: 0. Top: [28172, 32833, 34364, 33036, 42030, 28629, 33123, 17856, 27624, 28701, 33176, 25342, 30152, 40029, 25025, 50442, 22422, 34095, 35416, 44121]
Topic: 1. Top: [33123, 47238, 33125, 28701, 52105, 33176, 31298, 32510, 29237, 28695, 30339, 28995, 29902, 34871, 29282, 33124, 29728, 26745, 34317, 19656]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [29282, 29237, 33036, 32510, 33125, 20164, 35023, 32678, 17194, 32833, 45841, 27136, 19828, 30339, 32939, 26745, 30160, 39719, 34317, 27754]
Topic: 4. Top: [28651, 30596, 30339, 17946, 39719, 31484, 21347, 30374, 37833, 33036, 46434, 33480, 27315, 40395, 27970, 30152, 25420, 32436, 44259, 33125]
Topic: 5. Top: [30791, 32665, 33484, 32833, 27185, 20528, 38446, 43613, 29939, 42166, 35416, 34170, 20673, 44211, 28068, 37692, 28992, 29331, 19656, 30627]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [30339, 47238, 33036, 29237, 30252, 28016, 34317, 29684, 29096, 30887, 47035, 31298, 27030, 31397, 30795, 17231, 32254, 29282, 33123, 17194]
Topic: 8. Top: [28651, 34089, 30339, 37833, 25706, 33036, 26129, 30252, 34507, 43571, 39719, 24315, 29096, 29237, 30066, 34317, 30876, 29205, 29282, 32510]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [21123, 32833, 35657, 32135, 35538, 27587, 30791, 26809, 36303, 44211, 26864, 33707, 22099, 34729, 35604, 27086, 31747, 29592, 46583, 30750]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [27532, 30655, 51694, 52298, 17905, 42892, 28049, 29453, 42560, 19933, 30778, 37833, 28623, 40295, 32597, 51608, 28322, 24325, 34089, 24985]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1368947017605768
sparse_theta_sp: -0.638914622569672
decorrelation: 0.01
fix: 1000000000
num_topics: {'good': 13, 'bad': 3, 'not_good': 7, 'total_bad': 33}
11

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b89082e80>}
Topic: 0. Top: [19656, 52105, 47238, 32665, 21874, 33047, 30339, 29237, 31803, 26627, 42456, 35331, 33123, 31186, 32929, 36376, 27540, 32510, 27624, 31622]
Topic: 1. Top: [32833, 30791, 33484, 32665, 27185, 20528, 38446, 35416, 43613, 40029, 29939, 19656, 33826, 37692, 25945, 34170, 44211, 20673, 42166, 45727]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [33036, 20164, 40820, 28748, 32678, 30444, 36226, 22209, 27934, 38087, 28872, 26095, 32833, 23862, 29834, 30339, 29282, 28016, 27643, 33096]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 43571, 17946, 24315, 29096, 26129, 30374, 19828, 21347, 31484, 25420, 30066, 48622]
Topic: 5. Top: [29282, 29237, 33125, 32510, 28701, 30339, 34317, 33036, 34871, 26745, 28695, 33124, 30160, 33176, 28995, 27136, 29902, 17194, 29728, 29784]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [28172, 33123, 34364, 32833, 28701, 33036, 47238, 28629, 32510, 28995, 17856, 33176, 21580, 26745, 22422, 42030, 52105, 30152, 44121, 31298]
Topic: 8. Top: [47238, 30339, 33036, 30252, 33123, 31298, 34317, 29237, 28016, 29096, 29684, 33176, 31397, 48735, 30887, 17231, 27030, 33124, 47035, 30795]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [21123, 32833, 35657, 32135, 35538, 27587, 30791, 26809, 36303, 44211, 26864, 33707, 22099, 34729, 35604, 27086, 31747, 29592, 46583, 30750]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [27532, 30655, 51694, 52298, 17905, 42892, 28049, 29453, 42560, 19933, 30778, 37833, 28623, 40295, 32597, 51608, 28322, 24325, 34089, 24985]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
Topic: 0. Top: [19656, 52105, 47238, 32665, 21874, 33047, 30339, 29237, 31803, 26627, 42456, 35331, 33123, 31186, 32929, 36376, 27540, 32510, 27624, 31622]
Topic: 1. Top: [32833, 30791, 33484, 32665, 27185, 20528, 38446, 35416, 43613, 40029, 29939, 19656, 33826, 37692, 25945, 34170, 44211, 20673, 42166, 45727]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [33036, 20164, 40820, 28748, 32678, 30444, 36226, 22209, 27934, 38087, 28872, 26095, 32833, 23862, 29834, 30339, 29282, 28016, 27643, 33096]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 43571, 17946, 24315, 29096, 26129, 30374, 19828, 21347, 31484, 25420, 30066, 48622]
Topic: 5. Top: [29282, 29237, 33125, 32510, 28701, 30339, 34317, 33036, 34871, 26745, 28695, 33124, 30160, 33176, 28995, 27136, 29902, 17194, 29728, 29784]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [28172, 33123, 34364, 32833, 28701, 33036, 47238, 28629, 32510, 28995, 17856, 33176, 21580, 26745, 22422, 42030, 52105, 30152, 44121, 31298]
Topic: 8. Top: [47238, 30339, 33036, 30252, 33123, 31298, 34317, 29237, 28016, 29096, 29684, 33176, 31397, 48735, 30887, 17231, 27030, 33124, 47035, 30795]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [21123, 32833, 35657, 32135, 35538, 27587, 30791, 26809, 36303, 44211, 26864, 33707, 22099, 34729, 35604, 27086, 31747, 29592, 46583, 30750]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [27532, 30655, 51694, 52298, 17905, 42892, 28049, 29453, 42560, 19933, 30778, 37833, 28623, 40295, 32597, 51608, 28322, 24325, 34089, 24985]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1368947017605768
sparse_theta_sp: -0.638914622569672
decorrelation: 0.01
fix: 1000000000
SUCCESS: less bad topics
num_topics: {'good': 13, 'bad': 2, 'not_good': 7, 'total_bad': 35}
12

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b716c2d60>}
Topic: 0. Top: [47238, 30339, 30252, 33036, 33123, 31298, 29237, 33176, 34317, 28016, 29096, 29684, 30887, 48735, 31397, 30795, 17231, 44121, 37492, 37631]
Topic: 1. Top: [28172, 32833, 33036, 42030, 28629, 33123, 28701, 35842, 27624, 21580, 22422, 30152, 25025, 24278, 30656, 34095, 32510, 25342, 29272, 30444]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [19656, 52105, 47238, 33123, 29282, 33047, 32665, 26192, 32510, 26627, 33176, 45727, 32677, 29902, 31803, 28465, 27624, 29237, 32929, 27970]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 29237, 43571, 24315, 17946, 26129, 32510, 29096, 27970, 30252, 31484, 30066, 30374]
Topic: 5. Top: [33125, 29237, 29282, 30339, 32510, 28701, 33036, 28695, 34317, 47238, 26745, 33123, 34871, 33124, 30160, 29116, 31298, 29902, 20164, 28995]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [30791, 32833, 33484, 32665, 20528, 27185, 38446, 43613, 35416, 29939, 37692, 33826, 25945, 37130, 34170, 19656, 40029, 30597, 44211, 34531]
Topic: 8. Top: [45841, 33036, 29259, 35023, 29282, 39719, 20164, 47035, 27970, 33006, 32833, 38087, 27030, 44259, 30444, 33380, 31683, 33124, 28884, 32678]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [21123, 32833, 35657, 32135, 35538, 27587, 30791, 26809, 36303, 44211, 26864, 33707, 22099, 34729, 35604, 27086, 31747, 29592, 46583, 30750]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [27532, 30655, 51694, 52298, 17905, 42892, 28049, 29453, 42560, 19933, 30778, 37833, 28623, 40295, 32597, 51608, 28322, 24325, 34089, 24985]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
Topic: 0. Top: [47238, 30339, 30252, 33036, 33123, 31298, 29237, 33176, 34317, 28016, 29096, 29684, 30887, 48735, 31397, 30795, 17231, 44121, 37492, 37631]
Topic: 1. Top: [28172, 32833, 33036, 42030, 28629, 33123, 28701, 35842, 27624, 21580, 22422, 30152, 25025, 24278, 30656, 34095, 32510, 25342, 29272, 30444]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [19656, 52105, 47238, 33123, 29282, 33047, 32665, 26192, 32510, 26627, 33176, 45727, 32677, 29902, 31803, 28465, 27624, 29237, 32929, 27970]
Topic: 4. Top: [28651, 34089, 37833, 30339, 33036, 39719, 25706, 30596, 29237, 43571, 24315, 17946, 26129, 32510, 29096, 27970, 30252, 31484, 30066, 30374]
Topic: 5. Top: [33125, 29237, 29282, 30339, 32510, 28701, 33036, 28695, 34317, 47238, 26745, 33123, 34871, 33124, 30160, 29116, 31298, 29902, 20164, 28995]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [30791, 32833, 33484, 32665, 20528, 27185, 38446, 43613, 35416, 29939, 37692, 33826, 25945, 37130, 34170, 19656, 40029, 30597, 44211, 34531]
Topic: 8. Top: [45841, 33036, 29259, 35023, 29282, 39719, 20164, 47035, 27970, 33006, 32833, 38087, 27030, 44259, 30444, 33380, 31683, 33124, 28884, 32678]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [21123, 32833, 35657, 32135, 35538, 27587, 30791, 26809, 36303, 44211, 26864, 33707, 22099, 34729, 35604, 27086, 31747, 29592, 46583, 30750]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [27532, 30655, 51694, 52298, 17905, 42892, 28049, 29453, 42560, 19933, 30778, 37833, 28623, 40295, 32597, 51608, 28322, 24325, 34089, 24985]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1368947017605768
sparse_theta_sp: -0.638914622569672
decorrelation: 0.01
fix: 1000000000
num_topics: {'good': 13, 'bad': 2, 'not_good': 7, 'total_bad': 37}
13

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8eb25bb0>}
Topic: 0. Top: [52105, 29237, 19656, 33047, 21874, 26627, 32665, 47238, 29282, 32677, 32510, 29902, 31803, 30339, 32929, 26192, 31298, 27662, 42456, 29096]
Topic: 1. Top: [32833, 30791, 33484, 32665, 20528, 27185, 38446, 43613, 35416, 40029, 29939, 37692, 19656, 33826, 25945, 34170, 37130, 44211, 20673, 34531]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [28651, 34089, 37833, 30339, 39719, 33036, 29237, 25706, 30596, 43571, 24315, 32510, 26129, 17946, 27970, 31484, 29282, 33124, 29096, 30252]
Topic: 4. Top: [28172, 33123, 33036, 34364, 32833, 47238, 33176, 44121, 28701, 42030, 28995, 35416, 31298, 28629, 21580, 32510, 40029, 19656, 50442, 17856]
Topic: 5. Top: [29282, 33125, 33123, 29237, 47238, 30339, 32510, 26745, 34317, 33036, 28701, 28695, 33124, 34871, 30160, 33176, 29902, 29728, 29116, 17194]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [30339, 47238, 33036, 30252, 28016, 30887, 29237, 31298, 29096, 34317, 47035, 29684, 32254, 27030, 33176, 48735, 30795, 37492, 37631, 17231]
Topic: 8. Top: [33036, 19828, 30152, 32939, 46434, 48622, 29559, 29939, 40395, 45841, 30374, 32510, 38536, 25420, 30339, 20164, 29282, 29259, 33125, 44259]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [21123, 32833, 35657, 32135, 35538, 27587, 30791, 26809, 36303, 44211, 26864, 33707, 22099, 34729, 35604, 27086, 31747, 29592, 46583, 30750]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [27532, 30655, 51694, 52298, 17905, 42892, 28049, 29453, 42560, 19933, 30778, 37833, 28623, 40295, 32597, 51608, 28322, 24325, 34089, 24985]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
Topic: 0. Top: [52105, 29237, 19656, 33047, 21874, 26627, 32665, 47238, 29282, 32677, 32510, 29902, 31803, 30339, 32929, 26192, 31298, 27662, 42456, 29096]
Topic: 1. Top: [32833, 30791, 33484, 32665, 20528, 27185, 38446, 43613, 35416, 40029, 29939, 37692, 19656, 33826, 25945, 34170, 37130, 44211, 20673, 34531]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [28651, 34089, 37833, 30339, 39719, 33036, 29237, 25706, 30596, 43571, 24315, 32510, 26129, 17946, 27970, 31484, 29282, 33124, 29096, 30252]
Topic: 4. Top: [28172, 33123, 33036, 34364, 32833, 47238, 33176, 44121, 28701, 42030, 28995, 35416, 31298, 28629, 21580, 32510, 40029, 19656, 50442, 17856]
Topic: 5. Top: [29282, 33125, 33123, 29237, 47238, 30339, 32510, 26745, 34317, 33036, 28701, 28695, 33124, 34871, 30160, 33176, 29902, 29728, 29116, 17194]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [30339, 47238, 33036, 30252, 28016, 30887, 29237, 31298, 29096, 34317, 47035, 29684, 32254, 27030, 33176, 48735, 30795, 37492, 37631, 17231]
Topic: 8. Top: [33036, 19828, 30152, 32939, 46434, 48622, 29559, 29939, 40395, 45841, 30374, 32510, 38536, 25420, 30339, 20164, 29282, 29259, 33125, 44259]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [21123, 32833, 35657, 32135, 35538, 27587, 30791, 26809, 36303, 44211, 26864, 33707, 22099, 34729, 35604, 27086, 31747, 29592, 46583, 30750]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [27532, 30655, 51694, 52298, 17905, 42892, 28049, 29453, 42560, 19933, 30778, 37833, 28623, 40295, 32597, 51608, 28322, 24325, 34089, 24985]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1368947017605768
sparse_theta_sp: -0.638914622569672
decorrelation: 0.01
fix: 1000000000
num_topics: {'good': 13, 'bad': 2, 'not_good': 7, 'total_bad': 39}
14

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8baa95b0>}
Topic: 0. Top: [33484, 38446, 27185, 20528, 32665, 32833, 25945, 37692, 44211, 30791, 20673, 42166, 28992, 26239, 34531, 29331, 26466, 28019, 34170, 39872]
Topic: 1. Top: [28651, 33036, 37833, 30339, 39719, 25706, 30596, 19828, 30066, 17946, 25420, 24315, 35023, 30152, 21347, 32939, 34089, 45841, 32510, 33125]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [30339, 47238, 33036, 30252, 31298, 28016, 48735, 29237, 29096, 30887, 33176, 29684, 32254, 30795, 37492, 37631, 33123, 27030, 33124, 30444]
Topic: 4. Top: [29237, 29282, 33125, 29096, 30339, 28651, 32510, 43571, 28701, 33036, 26745, 30160, 29902, 47238, 33124, 29116, 30876, 39719, 33731, 29597]
Topic: 5. Top: [29282, 34317, 30339, 33125, 47238, 33123, 32510, 34871, 29237, 33036, 17194, 28695, 30252, 33124, 26745, 17231, 29902, 31298, 26027, 35023]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [52105, 32665, 19656, 21874, 33047, 28465, 35331, 31186, 32929, 27624, 30656, 31803, 31622, 47238, 36585, 42456, 27662, 27540, 32677, 26627]
Topic: 8. Top: [33123, 28172, 28701, 33176, 33036, 32833, 28995, 28695, 32510, 26745, 47238, 34364, 40029, 29282, 52105, 35416, 30152, 30160, 31298, 21580]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [21123, 32833, 35657, 32135, 35538, 27587, 30791, 26809, 36303, 44211, 26864, 33707, 22099, 34729, 35604, 27086, 31747, 29592, 46583, 30750]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [27532, 30655, 51694, 52298, 17905, 42892, 28049, 29453, 42560, 19933, 30778, 37833, 28623, 40295, 32597, 51608, 28322, 24325, 34089, 24985]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
Topic: 0. Top: [33484, 38446, 27185, 20528, 32665, 32833, 25945, 37692, 44211, 30791, 20673, 42166, 28992, 26239, 34531, 29331, 26466, 28019, 34170, 39872]
Topic: 1. Top: [28651, 33036, 37833, 30339, 39719, 25706, 30596, 19828, 30066, 17946, 25420, 24315, 35023, 30152, 21347, 32939, 34089, 45841, 32510, 33125]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [30339, 47238, 33036, 30252, 31298, 28016, 48735, 29237, 29096, 30887, 33176, 29684, 32254, 30795, 37492, 37631, 33123, 27030, 33124, 30444]
Topic: 4. Top: [29237, 29282, 33125, 29096, 30339, 28651, 32510, 43571, 28701, 33036, 26745, 30160, 29902, 47238, 33124, 29116, 30876, 39719, 33731, 29597]
Topic: 5. Top: [29282, 34317, 30339, 33125, 47238, 33123, 32510, 34871, 29237, 33036, 17194, 28695, 30252, 33124, 26745, 17231, 29902, 31298, 26027, 35023]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [52105, 32665, 19656, 21874, 33047, 28465, 35331, 31186, 32929, 27624, 30656, 31803, 31622, 47238, 36585, 42456, 27662, 27540, 32677, 26627]
Topic: 8. Top: [33123, 28172, 28701, 33176, 33036, 32833, 28995, 28695, 32510, 26745, 47238, 34364, 40029, 29282, 52105, 35416, 30152, 30160, 31298, 21580]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [21123, 32833, 35657, 32135, 35538, 27587, 30791, 26809, 36303, 44211, 26864, 33707, 22099, 34729, 35604, 27086, 31747, 29592, 46583, 30750]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [27532, 30655, 51694, 52298, 17905, 42892, 28049, 29453, 42560, 19933, 30778, 37833, 28623, 40295, 32597, 51608, 28322, 24325, 34089, 24985]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1368947017605768
sparse_theta_sp: -0.638914622569672
decorrelation: 0.01
fix: 1000000000
DOWNFALL: more bad topics...
num_topics: {'good': 13, 'bad': 3, 'not_good': 7, 'total_bad': 42}
15

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8bb455b0>}
Topic: 0. Top: [28651, 34089, 33036, 37833, 30339, 25706, 39719, 30596, 24315, 29096, 17946, 26129, 33125, 30066, 31484, 32510, 30374, 19828, 27970, 29205]
Topic: 1. Top: [28016, 47035, 27030, 36383, 30887, 33036, 49904, 32833, 29237, 29282, 45183, 27934, 40820, 33380, 30444, 30339, 29845, 51496, 28633, 32241]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [29282, 33125, 29237, 32510, 33123, 47238, 28701, 52105, 33036, 28695, 30339, 29902, 31298, 28995, 19656, 34871, 33176, 26745, 20164, 27970]
Topic: 4. Top: [29237, 30339, 34317, 29282, 33124, 35023, 32510, 30160, 43571, 30152, 26745, 26027, 38087, 32939, 34871, 39719, 33006, 44259, 33176, 28701]
Topic: 5. Top: [47238, 30339, 30252, 33036, 33123, 34317, 31298, 29684, 29237, 29096, 33176, 33124, 29116, 48735, 44121, 17231, 30795, 26745, 31397, 33125]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [32833, 30791, 33484, 32665, 20528, 27185, 38446, 35416, 43613, 29939, 37692, 37130, 40029, 19656, 33826, 25945, 34170, 30597, 44211, 34531]
Topic: 8. Top: [32833, 33036, 42030, 33123, 18601, 28585, 25342, 21580, 17856, 25025, 33176, 30444, 31374, 35416, 32510, 28701, 47238, 40736, 46714, 45727]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [21123, 32833, 35657, 32135, 35538, 27587, 30791, 26809, 36303, 44211, 26864, 33707, 22099, 34729, 35604, 27086, 31747, 29592, 46583, 30750]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [27532, 30655, 51694, 52298, 17905, 42892, 28049, 29453, 42560, 19933, 30778, 37833, 28623, 40295, 32597, 51608, 28322, 24325, 34089, 24985]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
Topic: 0. Top: [28651, 34089, 33036, 37833, 30339, 25706, 39719, 30596, 24315, 29096, 17946, 26129, 33125, 30066, 31484, 32510, 30374, 19828, 27970, 29205]
Topic: 1. Top: [28016, 47035, 27030, 36383, 30887, 33036, 49904, 32833, 29237, 29282, 45183, 27934, 40820, 33380, 30444, 30339, 29845, 51496, 28633, 32241]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [29282, 33125, 29237, 32510, 33123, 47238, 28701, 52105, 33036, 28695, 30339, 29902, 31298, 28995, 19656, 34871, 33176, 26745, 20164, 27970]
Topic: 4. Top: [29237, 30339, 34317, 29282, 33124, 35023, 32510, 30160, 43571, 30152, 26745, 26027, 38087, 32939, 34871, 39719, 33006, 44259, 33176, 28701]
Topic: 5. Top: [47238, 30339, 30252, 33036, 33123, 34317, 31298, 29684, 29237, 29096, 33176, 33124, 29116, 48735, 44121, 17231, 30795, 26745, 31397, 33125]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [32833, 30791, 33484, 32665, 20528, 27185, 38446, 35416, 43613, 29939, 37692, 37130, 40029, 19656, 33826, 25945, 34170, 30597, 44211, 34531]
Topic: 8. Top: [32833, 33036, 42030, 33123, 18601, 28585, 25342, 21580, 17856, 25025, 33176, 30444, 31374, 35416, 32510, 28701, 47238, 40736, 46714, 45727]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [21123, 32833, 35657, 32135, 35538, 27587, 30791, 26809, 36303, 44211, 26864, 33707, 22099, 34729, 35604, 27086, 31747, 29592, 46583, 30750]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [27532, 30655, 51694, 52298, 17905, 42892, 28049, 29453, 42560, 19933, 30778, 37833, 28623, 40295, 32597, 51608, 28322, 24325, 34089, 24985]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1368947017605768
sparse_theta_sp: -0.638914622569672
decorrelation: 0.01
fix: 1000000000
DOWNFALL: more bad topics...
num_topics: {'good': 13, 'bad': 4, 'not_good': 7, 'total_bad': 46}
16

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8e8cdeb0>}
Topic: 0. Top: [28651, 30339, 34089, 37833, 39719, 33036, 29237, 25706, 30596, 43571, 32510, 17946, 24315, 30066, 26129, 30374, 34317, 29096, 27970, 25420]
Topic: 1. Top: [30791, 33484, 32665, 32833, 43613, 27185, 38446, 20528, 20673, 35416, 28992, 44211, 25945, 29939, 42166, 25220, 34170, 26239, 26567, 19656]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [29282, 33036, 32510, 20164, 28695, 28995, 28701, 32678, 30152, 32833, 29939, 30160, 27136, 27970, 33176, 31298, 33124, 32337, 38536, 31167]
Topic: 4. Top: [47238, 29237, 33123, 30339, 33125, 29282, 34317, 26745, 29902, 32510, 31298, 33176, 33036, 33124, 34871, 28701, 30252, 28695, 29096, 29684]
Topic: 5. Top: [28172, 32833, 34364, 42030, 33036, 28629, 18601, 33123, 17856, 25342, 25025, 28585, 27624, 34095, 29272, 21580, 30656, 40736, 24278, 30429]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [30339, 33036, 28016, 47238, 30887, 30252, 32254, 27030, 47035, 37492, 48735, 30795, 30444, 37631, 29096, 49897, 31298, 29684, 28633, 37712]
Topic: 8. Top: [32833, 37130, 35842, 37692, 30597, 33826, 27624, 40029, 34531, 33036, 27300, 22422, 19656, 21650, 27066, 30791, 50488, 26306, 33123, 41831]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [21123, 32833, 35657, 32135, 35538, 27587, 30791, 26809, 36303, 44211, 26864, 33707, 22099, 34729, 35604, 27086, 31747, 29592, 46583, 30750]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [27532, 30655, 51694, 52298, 17905, 42892, 28049, 29453, 42560, 19933, 30778, 37833, 28623, 40295, 32597, 51608, 28322, 24325, 34089, 24985]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
Topic: 0. Top: [28651, 30339, 34089, 37833, 39719, 33036, 29237, 25706, 30596, 43571, 32510, 17946, 24315, 30066, 26129, 30374, 34317, 29096, 27970, 25420]
Topic: 1. Top: [30791, 33484, 32665, 32833, 43613, 27185, 38446, 20528, 20673, 35416, 28992, 44211, 25945, 29939, 42166, 25220, 34170, 26239, 26567, 19656]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [29282, 33036, 32510, 20164, 28695, 28995, 28701, 32678, 30152, 32833, 29939, 30160, 27136, 27970, 33176, 31298, 33124, 32337, 38536, 31167]
Topic: 4. Top: [47238, 29237, 33123, 30339, 33125, 29282, 34317, 26745, 29902, 32510, 31298, 33176, 33036, 33124, 34871, 28701, 30252, 28695, 29096, 29684]
Topic: 5. Top: [28172, 32833, 34364, 42030, 33036, 28629, 18601, 33123, 17856, 25342, 25025, 28585, 27624, 34095, 29272, 21580, 30656, 40736, 24278, 30429]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [30339, 33036, 28016, 47238, 30887, 30252, 32254, 27030, 47035, 37492, 48735, 30795, 30444, 37631, 29096, 49897, 31298, 29684, 28633, 37712]
Topic: 8. Top: [32833, 37130, 35842, 37692, 30597, 33826, 27624, 40029, 34531, 33036, 27300, 22422, 19656, 21650, 27066, 30791, 50488, 26306, 33123, 41831]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [21123, 32833, 35657, 32135, 35538, 27587, 30791, 26809, 36303, 44211, 26864, 33707, 22099, 34729, 35604, 27086, 31747, 29592, 46583, 30750]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [27532, 30655, 51694, 52298, 17905, 42892, 28049, 29453, 42560, 19933, 30778, 37833, 28623, 40295, 32597, 51608, 28322, 24325, 34089, 24985]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1368947017605768
sparse_theta_sp: -0.638914622569672
decorrelation: 0.01
fix: 1000000000
SUCCESS: less bad topics
num_topics: {'good': 13, 'bad': 2, 'not_good': 7, 'total_bad': 48}
17

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8bb455b0>}
Topic: 0. Top: [30339, 47238, 30252, 33036, 29237, 34317, 31298, 28016, 29096, 29684, 27030, 30887, 17231, 31397, 33123, 33176, 32254, 37492, 30795, 37631]
Topic: 1. Top: [28651, 34089, 30339, 26129, 33036, 37833, 25706, 30252, 34507, 29096, 43571, 29282, 29205, 30876, 32510, 30066, 33176, 33124, 48735, 34317]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [33123, 28701, 47238, 33036, 29282, 28172, 33176, 26745, 33125, 28695, 32510, 28995, 34871, 31298, 40029, 52105, 44121, 30160, 33124, 29784]
Topic: 4. Top: [52105, 19656, 21874, 32665, 47238, 29237, 33047, 32510, 28465, 36585, 29282, 27624, 31803, 31186, 29902, 31622, 32929, 30339, 26627, 29096]
Topic: 5. Top: [32833, 30791, 33484, 32665, 20528, 27185, 38446, 43613, 35416, 40029, 29939, 19656, 37692, 33826, 37130, 25945, 34170, 30597, 44211, 45727]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [30339, 33125, 39719, 33036, 28651, 29282, 29237, 45841, 32510, 20164, 35023, 30596, 34871, 37833, 34317, 25420, 21347, 17946, 19828, 29259]
Topic: 8. Top: [29237, 29282, 32510, 33036, 32678, 29116, 26745, 30160, 32833, 43571, 32711, 33125, 27136, 29902, 30130, 28016, 32939, 20814, 30152, 28995]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [21123, 32833, 35657, 32135, 35538, 27587, 30791, 26809, 36303, 44211, 26864, 33707, 22099, 34729, 35604, 27086, 31747, 29592, 46583, 30750]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [27532, 30655, 51694, 52298, 17905, 42892, 28049, 29453, 42560, 19933, 30778, 37833, 28623, 40295, 32597, 51608, 28322, 24325, 34089, 24985]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
Topic: 0. Top: [30339, 47238, 30252, 33036, 29237, 34317, 31298, 28016, 29096, 29684, 27030, 30887, 17231, 31397, 33123, 33176, 32254, 37492, 30795, 37631]
Topic: 1. Top: [28651, 34089, 30339, 26129, 33036, 37833, 25706, 30252, 34507, 29096, 43571, 29282, 29205, 30876, 32510, 30066, 33176, 33124, 48735, 34317]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [33123, 28701, 47238, 33036, 29282, 28172, 33176, 26745, 33125, 28695, 32510, 28995, 34871, 31298, 40029, 52105, 44121, 30160, 33124, 29784]
Topic: 4. Top: [52105, 19656, 21874, 32665, 47238, 29237, 33047, 32510, 28465, 36585, 29282, 27624, 31803, 31186, 29902, 31622, 32929, 30339, 26627, 29096]
Topic: 5. Top: [32833, 30791, 33484, 32665, 20528, 27185, 38446, 43613, 35416, 40029, 29939, 19656, 37692, 33826, 37130, 25945, 34170, 30597, 44211, 45727]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [30339, 33125, 39719, 33036, 28651, 29282, 29237, 45841, 32510, 20164, 35023, 30596, 34871, 37833, 34317, 25420, 21347, 17946, 19828, 29259]
Topic: 8. Top: [29237, 29282, 32510, 33036, 32678, 29116, 26745, 30160, 32833, 43571, 32711, 33125, 27136, 29902, 30130, 28016, 32939, 20814, 30152, 28995]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [21123, 32833, 35657, 32135, 35538, 27587, 30791, 26809, 36303, 44211, 26864, 33707, 22099, 34729, 35604, 27086, 31747, 29592, 46583, 30750]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [27532, 30655, 51694, 52298, 17905, 42892, 28049, 29453, 42560, 19933, 30778, 37833, 28623, 40295, 32597, 51608, 28322, 24325, 34089, 24985]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1368947017605768
sparse_theta_sp: -0.638914622569672
decorrelation: 0.01
fix: 1000000000
num_topics: {'good': 13, 'bad': 2, 'not_good': 7, 'total_bad': 50}
18

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8f81c310>}
Topic: 0. Top: [33484, 27185, 20528, 38446, 32833, 37692, 32665, 28068, 42166, 20673, 28992, 29939, 34531, 30597, 37130, 27300, 30627, 25911, 26306, 35842]
Topic: 1. Top: [30791, 32833, 40029, 35416, 43613, 19656, 33826, 32665, 33123, 25945, 33036, 28393, 45727, 33176, 39872, 29939, 25220, 26567, 34170, 25943]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [28651, 30339, 34089, 37833, 33036, 39719, 25706, 29237, 30596, 43571, 32510, 24315, 17946, 29282, 30066, 26129, 33125, 25420, 30374, 21347]
Topic: 4. Top: [30339, 47238, 30252, 29237, 33036, 34317, 28016, 29096, 29684, 31298, 33176, 47035, 30887, 29282, 48735, 33123, 17231, 29902, 33124, 31397]
Topic: 5. Top: [29282, 29237, 33125, 32510, 33123, 30339, 33036, 47238, 28701, 26745, 34871, 28695, 29902, 20164, 28995, 34317, 31298, 30160, 33176, 17194]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [28172, 33123, 34364, 28701, 47238, 33036, 33176, 44121, 52105, 31298, 28629, 28995, 50442, 17856, 28695, 26745, 25342, 34095, 27624, 22422]
Topic: 8. Top: [33124, 26239, 33036, 32510, 28695, 32833, 30160, 40820, 27934, 34130, 28701, 36226, 38753, 30339, 26095, 34317, 30152, 38087, 29331, 46780]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [21123, 32833, 35657, 32135, 35538, 27587, 30791, 26809, 36303, 44211, 26864, 33707, 22099, 34729, 35604, 27086, 31747, 29592, 46583, 30750]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [27532, 30655, 51694, 52298, 17905, 42892, 28049, 29453, 42560, 19933, 30778, 37833, 28623, 40295, 32597, 51608, 28322, 24325, 34089, 24985]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
Topic: 0. Top: [33484, 27185, 20528, 38446, 32833, 37692, 32665, 28068, 42166, 20673, 28992, 29939, 34531, 30597, 37130, 27300, 30627, 25911, 26306, 35842]
Topic: 1. Top: [30791, 32833, 40029, 35416, 43613, 19656, 33826, 32665, 33123, 25945, 33036, 28393, 45727, 33176, 39872, 29939, 25220, 26567, 34170, 25943]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [28651, 30339, 34089, 37833, 33036, 39719, 25706, 29237, 30596, 43571, 32510, 24315, 17946, 29282, 30066, 26129, 33125, 25420, 30374, 21347]
Topic: 4. Top: [30339, 47238, 30252, 29237, 33036, 34317, 28016, 29096, 29684, 31298, 33176, 47035, 30887, 29282, 48735, 33123, 17231, 29902, 33124, 31397]
Topic: 5. Top: [29282, 29237, 33125, 32510, 33123, 30339, 33036, 47238, 28701, 26745, 34871, 28695, 29902, 20164, 28995, 34317, 31298, 30160, 33176, 17194]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [28172, 33123, 34364, 28701, 47238, 33036, 33176, 44121, 52105, 31298, 28629, 28995, 50442, 17856, 28695, 26745, 25342, 34095, 27624, 22422]
Topic: 8. Top: [33124, 26239, 33036, 32510, 28695, 32833, 30160, 40820, 27934, 34130, 28701, 36226, 38753, 30339, 26095, 34317, 30152, 38087, 29331, 46780]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [21123, 32833, 35657, 32135, 35538, 27587, 30791, 26809, 36303, 44211, 26864, 33707, 22099, 34729, 35604, 27086, 31747, 29592, 46583, 30750]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [27532, 30655, 51694, 52298, 17905, 42892, 28049, 29453, 42560, 19933, 30778, 37833, 28623, 40295, 32597, 51608, 28322, 24325, 34089, 24985]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1368947017605768
sparse_theta_sp: -0.638914622569672
decorrelation: 0.01
fix: 1000000000
DOWNFALL: more bad topics...
num_topics: {'good': 13, 'bad': 4, 'not_good': 7, 'total_bad': 54}
19

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning:

Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!

{'fix': <__main__.FastFixPhiRegularizer object at 0x7f7b8ea2cca0>}
Topic: 0. Top: [32833, 30791, 33484, 32665, 40029, 38446, 27185, 20528, 35416, 19656, 37130, 37692, 43613, 29939, 33826, 45727, 30597, 25945, 33123, 33036]
Topic: 1. Top: [28651, 34089, 37833, 30339, 39719, 25706, 29237, 43571, 33036, 17946, 24315, 26129, 29096, 29282, 32510, 34317, 30252, 30374, 34507, 30596]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [30339, 47238, 33036, 30252, 29237, 34317, 31298, 28016, 30887, 29684, 29096, 48735, 33123, 33176, 27030, 31397, 17231, 30795, 37492, 33124]
Topic: 4. Top: [28172, 34364, 35842, 27624, 28629, 32833, 33123, 17856, 29834, 21650, 42030, 28701, 34095, 22422, 33176, 24278, 25342, 30429, 49838, 40736]
Topic: 5. Top: [29282, 29237, 33125, 33123, 47238, 32510, 28701, 30339, 52105, 33176, 28695, 26745, 29902, 34317, 28995, 34871, 33036, 31298, 30160, 19656]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [33036, 19828, 30339, 20164, 29259, 21347, 32833, 44259, 45841, 29282, 33125, 27970, 32510, 29559, 35023, 25420, 31484, 32939, 33124, 38087]
Topic: 8. Top: [30152, 33036, 27187, 35023, 30130, 32833, 32711, 34130, 28884, 32939, 28748, 40395, 37202, 45183, 32510, 37168, 35388, 26691, 33124, 38753]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [21123, 32833, 35657, 32135, 35538, 27587, 30791, 26809, 36303, 44211, 26864, 33707, 22099, 34729, 35604, 27086, 31747, 29592, 46583, 30750]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [27532, 30655, 51694, 52298, 17905, 42892, 28049, 29453, 42560, 19933, 30778, 37833, 28623, 40295, 32597, 51608, 28322, 24325, 34089, 24985]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
Topic: 0. Top: [32833, 30791, 33484, 32665, 40029, 38446, 27185, 20528, 35416, 19656, 37130, 37692, 43613, 29939, 33826, 45727, 30597, 25945, 33123, 33036]
Topic: 1. Top: [28651, 34089, 37833, 30339, 39719, 25706, 29237, 43571, 33036, 17946, 24315, 26129, 29096, 29282, 32510, 34317, 30252, 30374, 34507, 30596]
Topic: 2. Top: [49838, 28100, 34287, 24123, 26190, 29939, 28095, 32833, 28019, 37130, 40409, 51400, 30119, 36268, 30627, 23120, 31964, 25538, 29972, 17856]
Topic: 3. Top: [30339, 47238, 33036, 30252, 29237, 34317, 31298, 28016, 30887, 29684, 29096, 48735, 33123, 33176, 27030, 31397, 17231, 30795, 37492, 33124]
Topic: 4. Top: [28172, 34364, 35842, 27624, 28629, 32833, 33123, 17856, 29834, 21650, 42030, 28701, 34095, 22422, 33176, 24278, 25342, 30429, 49838, 40736]
Topic: 5. Top: [29282, 29237, 33125, 33123, 47238, 32510, 28701, 30339, 52105, 33176, 28695, 26745, 29902, 34317, 28995, 34871, 33036, 31298, 30160, 19656]
Topic: 6. Top: [36383, 31186, 29453, 29116, 51040, 26627, 51902, 35750, 34014, 27540, 36928, 29237, 33799, 40999, 26993, 20197, 26072, 21129, 31620, 35189]
Topic: 7. Top: [33036, 19828, 30339, 20164, 29259, 21347, 32833, 44259, 45841, 29282, 33125, 27970, 32510, 29559, 35023, 25420, 31484, 32939, 33124, 38087]
Topic: 8. Top: [30152, 33036, 27187, 35023, 30130, 32833, 32711, 34130, 28884, 32939, 28748, 40395, 37202, 45183, 32510, 37168, 35388, 26691, 33124, 38753]
Topic: 9. Top: [29385, 32833, 32942, 28820, 36874, 29939, 26627, 28019, 44833, 37553, 33036, 27643, 23798, 35189, 29453, 28992, 42639, 25950, 25902, 46187]
Topic: 10. Top: [38537, 30869, 30391, 37038, 18311, 26379, 28585, 28731, 25196, 32913, 18601, 32126, 27179, 31186, 25998, 29125, 25273, 38759, 33654, 29597]
Topic: 11. Top: [21123, 32833, 35657, 32135, 35538, 27587, 30791, 26809, 36303, 44211, 26864, 33707, 22099, 34729, 35604, 27086, 31747, 29592, 46583, 30750]
Topic: 12. Top: [19900, 21915, 43613, 31803, 26616, 39625, 32665, 31412, 29791, 46714, 32237, 42166, 23884, 31381, 27323, 16955, 26303, 20141, 10906, 27643]
Topic: 13. Top: [31855, 31472, 24053, 20243, 30883, 42030, 28828, 23267, 36287, 13261, 22269, 29100, 27378, 21131, 18904, 28824, 27220, 31402, 45596, 30490]
Topic: 14. Top: [32028, 32833, 42454, 36195, 30827, 34207, 31683, 24317, 27360, 24160, 33036, 24193, 30331, 42590, 43832, 29858, 31264, 29398, 28122, 20877]
Topic: 15. Top: [27532, 30655, 51694, 52298, 17905, 42892, 28049, 29453, 42560, 19933, 30778, 37833, 28623, 40295, 32597, 51608, 28322, 24325, 34089, 24985]
Topic: 16. Top: [37154, 31055, 22986, 34085, 26128, 30110, 33941, 29939, 32489, 28992, 36334, 19730, 27902, 52105, 28867, 35364, 32038, 36585, 30490, 29331]
Topic: 17. Top: [32254, 30220, 29396, 26587, 36022, 25783, 29237, 36301, 36792, 18311, 37318, 25273, 29386, 26627, 36376, 17905, 22424, 23396, 24023, 29597]
Topic: 18. Top: [34687, 23755, 28828, 30497, 30086, 29766, 29319, 30736, 52105, 45004, 27689, 23606, 47946, 33887, 27624, 29212, 28947, 29644, 20124, 31854]
Topic: 19. Top: [43613, 31997, 39575, 22254, 38245, 25289, 50360, 20370, 26648, 31059, 24203, 27086, 29908, 34170, 28884, 34409, 23885, 29331, 31759, 29939]
smooth_phi_bcg: 1.0591326925686735
smooth_theta_bcg: 4.943181553565358
sparse_phi_sp: -0.1368947017605768
sparse_theta_sp: -0.638914622569672
decorrelation: 0.01
fix: 1000000000
SUCCESS: less bad topics
num_topics: {'good': 13, 'bad': 1, 'not_good': 7, 'total_bad': 55}

In [136]:
1

1

In [128]:
! ls results/20newsgroups/ablation_study/

iterative_1000000_0-0-1.json  iterative_1000_1-0-0.json
iterative_1000000_0-1-0.json  iterative_1000_1-0-1.json
iterative_1000000_0-1-1.json  iterative_1000_1-1-0.json
iterative_1000000_1-0-0.json  iterative2_1000000_0-0-1.json
iterative_1000000_1-0-1.json  iterative2_1000000_0-1-0.json
iterative_1000000_1-1-0.json  iterative2_1000000_0-1-1.json
iterative_1000_0-0-1.json     iterative2_1000000_1-0-0.json
iterative_1000_0-1-0.json     iterative2_1000000_1-0-1.json
iterative_1000_0-1-1.json     iterative2_1000000_1-1-0.json

In [129]:
DECORRELATION_TAU

1000000000

In [130]:
results.keys()

dict_keys([(0, 1, 1), (1, 0, 1), (1, 1, 0), (1, 0, 0), (0, 1, 0), (0, 0, 1)])

In [37]:
for k, r in results.items():
    for s in r:
        s['scores']['coherence_20'] = float(s['scores']['coherence_20'])

In [38]:
for k, r in results.items():
    output_k = '-'.join(str(i) for i in k)
    with open(SAVE_FOLDER + f'/ablation_study/iterative2_{DECORRELATION_TAU}_{output_k}.json', 'w') as f:
        f.write(
            json.dumps(r, indent=4)
        )

In [133]:
! ls results/20newsgroups/ablation_study

iterative_1000000_0-0-1.json  iterative2_1000000000_0-0-1.json
iterative_1000000_0-1-0.json  iterative2_1000000000_0-1-0.json
iterative_1000000_0-1-1.json  iterative2_1000000000_0-1-1.json
iterative_1000000_1-0-0.json  iterative2_1000000000_1-0-0.json
iterative_1000000_1-0-1.json  iterative2_1000000000_1-0-1.json
iterative_1000000_1-1-0.json  iterative2_1000000000_1-1-0.json
iterative_1000_0-0-1.json     iterative2_1000000_0-0-1.json
iterative_1000_0-1-0.json     iterative2_1000000_0-1-0.json
iterative_1000_0-1-1.json     iterative2_1000000_0-1-1.json
iterative_1000_1-0-0.json     iterative2_1000000_1-0-0.json
iterative_1000_1-0-1.json     iterative2_1000000_1-0-1.json
iterative_1000_1-1-0.json     iterative2_1000000_1-1-0.json

In [134]:
for k, r in results.items():
    print(k)
    print(r[-1]['scores'])
    print(r[-1]['num_topics'])
    print()

(0, 1, 1)
{'perplexity': 2378.796630859375, 'coherence_20': 1.7140309294414489, 'diversity_euclidean': 0.06756999250647623, 'diversity_jensenshannon': 0.7658887477473149, 'diversity_hellinger': 0.9073563482705373, 'diversity_cosine': 0.9247700426211884}
{'good': 12, 'bad': 4, 'not_good': 8, 'total_bad': 85}

(1, 0, 1)
{'perplexity': 2478.213623046875, 'coherence_20': 1.8082727927394142, 'diversity_euclidean': 0.08448469964980418, 'diversity_jensenshannon': 0.7407933136237574, 'diversity_hellinger': 0.8731731292801453, 'diversity_cosine': 0.9070294785718593}
{'good': 19, 'bad': 1, 'not_good': 1, 'total_bad': 24}

(1, 1, 0)
{'perplexity': 2534.749755859375, 'coherence_20': 1.8346049911182514, 'diversity_euclidean': 0.0876718756558992, 'diversity_jensenshannon': 0.7408455109076264, 'diversity_hellinger': 0.8738754706112992, 'diversity_cosine': 0.8998250257543015}
{'good': 18, 'bad': 0, 'not_good': 2, 'total_bad': 2}

(1, 0, 0)
{'perplexity': 2399.751953125, 'coherence_20': 1.5325914688550593, 'diversity_euclidean': 0.0749013857093883, 'diversity_jensenshannon': 0.7095305134817659, 'diversity_hellinger': 0.8320241982890605, 'diversity_cosine': 0.8471760260568955}
{'good': 13, 'bad': 1, 'not_good': 7, 'total_bad': 55}

(0, 1, 0)
{'perplexity': 2318.733154296875, 'coherence_20': 1.7455727102519596, 'diversity_euclidean': 0.07087609805296091, 'diversity_jensenshannon': 0.7629001973842174, 'diversity_hellinger': 0.9032921905148547, 'diversity_cosine': 0.9194758155231888}
{'good': 11, 'bad': 3, 'not_good': 9, 'total_bad': 93}

(0, 0, 1)
{'perplexity': 2222.51220703125, 'coherence_20': 1.2932352991613913, 'diversity_euclidean': 0.06149625611211266, 'diversity_jensenshannon': 0.6759768715723362, 'diversity_hellinger': 0.7871119058696353, 'diversity_cosine': 0.7719718921251675}
{'good': 4, 'bad': 4, 'not_good': 16, 'total_bad': 83}