# TopicBank: Bank Creation Experiment

Here we are going to collect interpretable topics (automatically, using topic coherence) from multiple model training.
These topics constitute *topic bank*.
And then the topic bank is going to be used for estimating topic models quality in the notebook [TopicBank-Experiment: Model Validation](TopicBank-Experiment-ModelValidation.ipynb).

The process is repeated for several datasets (some of them are already downloadable using [TopicNet](https://github.com/machine-intelligence-laboratory/TopicNet) library).

# Contents<a id="contents"></a>

* [Data](#data)
    * [Coocs](#coocs)
        * [Lower Memory Consumption (or a Bit of Shamanism. Part 1)](#optimizing-memory)
    * [Documents for Coherence Scores](#docs-for-cohs)
        * [Lower Time Consumption in Case of Big Datasets (or a Bit of Shamanism. Part 2)](#optimizing-time)
* [Experiment](#experiment)
    * [Scores](#scores)
    * [Bank Creation](#bank-creation)
* [Postprocessing](#postprocessing)

In [1]:
# General imports

import dill
import itertools
import json
import numpy as np
import os
import pandas as pd
import sys
import time

from enum import Enum
from scipy.stats import gaussian_kde
from matplotlib import pyplot as plt
from tqdm import tqdm
from typing import (
    Dict,
    Iterable,
)

%matplotlib inline

In [2]:
# Making `topnum` module visible for Python

sys.path.insert(0, '../OptimalNumberOfTopics')

In [3]:
# Optimal number of topics

from topicnet.cooking_machine import Dataset

from topnum.data.vowpal_wabbit_text_collection import VowpalWabbitTextCollection
from topnum.scores import (
    PerplexityScore,
    SparsityPhiScore,
    SparsityThetaScore,
)
from topnum.scores.diversity_score import DiversityScore, KNOWN_METRICS
from topnum.scores._base_coherence_score import (
    SpecificityEstimationMethod,
    TextType,
    WordTopicRelatednessType,
)
from topnum.regularizers import (
    FastFixPhiRegularizer, DecorrelateWithOtherPhiRegularizer, DecorrelateWithOtherPhiRegularizer2
)
from topnum.scores.intratext_coherence_score import (
    IntratextCoherenceScore,
    ComputationMethod,
    WordTopicRelatednessType,
)
from topnum.search_methods import TopicBankMethod
from topnum.search_methods.topic_bank.topic_bank import TopicBank
from topnum.search_methods.topic_bank.one_model_train_funcs import (
    default_train_func,

    # Functions below are not used (but could have been)

#     regularization_train_func,
#     specific_initial_phi_train_func,
#     background_topics_train_func,

)

## Data<a id="data"></a>

<div style="text-align: right">Back to <a href=#contents>Contents</a></div>

Loading data from disk, creating batches, dictionary, gathering cooccurrence statistics...

In [4]:
DATA_FOLDER_PATH = '/data_mil/shared/CompressaAI/iterative/data/noow'

In [5]:
sorted(os.listdir(DATA_FOLDER_PATH))

['20_Newsgroups_NOOW.csv',
 '20_Newsgroups_NOOW__internals',
 '20_Newsgroups__internals',
 'MKB_10_NOOW.csv',
 'MKB_10_NOOW__internals',
 'MKB_10__internals',
 'Post_Science_NOOW.csv',
 'Post_Science_NOOW__internals',
 'Post_Science_NOOW_fixed.csv',
 'Post_Science_NOOW_fixed__internals',
 'Post_Science__internals',
 'WikiRef_220_NOOW.csv',
 '_20_Newsgroups.csv',
 '_20_Newsgroups__internals',
 '_Lenta.csv']

In [6]:
class DatasetName(Enum):
    POSTNAUKA = 'Post_Science'
    # REUTERS = 'Reuters'
    # BROWN = 'Brown'
    # TWENTY_NEWSGROUPS = '20NG_natural_order'

In [7]:
DATASET_NAME_TO_DATASET_FILE_PATH = {
    DatasetName.POSTNAUKA: os.path.join(
        DATA_FOLDER_PATH, 'Post_Science_NOOW_fixed.csv'
    ),
    # DatasetName.REUTERS: os.path.join(
    #     DATA_FOLDER_PATH, 'Reuters.csv'
    # ),
    # DatasetName.BROWN: os.path.join(
    #     DATA_FOLDER_PATH, 'Brown.csv'
    # ),
    # DatasetName.TWENTY_NEWSGROUPS: os.path.join(
    #     DATA_FOLDER_PATH, '20NG_natural_order.csv'
    # ),
    # DatasetName.AG_NEWS: os.path.join(
    #     DATA_FOLDER_PATH, 'AG_News.csv'
    # ),
    # DatasetName.WATAN: os.path.join(
    #     DATA_FOLDER_PATH, 'Watan2004.csv'
    # ),
    # DatasetName.HABRAHABR: os.path.join(
    #     DATA_FOLDER_PATH, 'Habrahabr.csv'
    # ),
}

In [8]:
DATASET_NAME = DatasetName.POSTNAUKA  # select a dataset here

DATASET_FILE_PATH = DATASET_NAME_TO_DATASET_FILE_PATH[DATASET_NAME]

Checking if all OK with data, what modalities does the collection have.

In [9]:
! head -n 2 $DATASET_FILE_PATH

id,raw_text,vw_text
29998.txt,материал отрицательный показатель преломление физик виктор веселаго распространение свет вещество фазовый групповой скорость метаматериалы различаться фазовый групповой скорость каков физика распространение свет вещество находить применение материал отрицательный показатель преломление рассказывать доктор физикоматематический наука виктор веселаго скорость распространяться энергия вещество обычно говорить излучение распространяться вещество со скорость n раз маленький n коэффициент преломление вещество коэффициент преломление n отношение скорость свет скорость распространение излучение вещество обычно уточняться распространяться распространение энергия распространение импульс происходить различный закон энергия распространяться со скорость называться групповой скорость много скорость свет эйнштейн сформулировать самый больший скорость излучение скорость свет кмс импульс распространяться фазовый скорость сколь угодно много скорость свет скорость входить соотношение emc фазовый групповой оказываться здесь величина заменять произведение фазовый скорость групповой post id отрицательный преломление свет притягивать объект излучатель внутри вещество возможный явление чемто новый впервые указывать статья оказываться материал обладать отрицательный преломление описываться отрицательный коэффициент преломление n отношение скорость свет пустота скорость свет вещество излучатель освещать приемник внутри вещество приемник притягиваться излучатель отрицательный скорость положительный скорость излучатель приемник наоборот отрицательный классический школьный опыт брать вода пускать луч свет преломляться внутри вода идти угол идти поверхность вместо вода использовать вещество отрицательный преломление отклоняться налево направо комбинировать вещество отрицательный положительный преломление организовывать прохождение луч свет через набор материальный среда определенный закон както повертываться извиваться обычно привязывать эффект шапкиневидимка иметься эксперимент иметься некий объект сделать невидимый свет проходить вокруг объект наблюдатель кажется объект хотя дело практический применение далеко кроме явление связывать отрицательный преломление наблюдаться область электромагнитный излучение акустика распространение разный род колебание,29998.txt |@word материал отрицательный показатель преломление физик виктор веселаго распространение свет вещество фазовый групповой скорость метаматериалы различаться фазовый групповой скорость каков физика распространение свет вещество находить применение материал отрицательный показатель преломление рассказывать доктор физикоматематический наука виктор веселаго скорость распространяться энергия вещество обычно говорить излучение распространяться вещество со скорость n раз маленький n коэффициент преломление вещество коэффициент преломление n отношение скорость свет скорость распространение излучение вещество обычно уточняться распространяться распространение энергия распространение импульс происходить различный закон энергия распространяться со скорость называться групповой скорость много скорость свет эйнштейн сформулировать самый больший скорость излучение скорость свет кмс импульс распространяться фазовый скорость сколь угодно много скорость свет скорость входить соотношение emc фазовый групповой оказываться здесь величина заменять произведение фазовый скорость групповой post id отрицательный преломление свет притягивать объект излучатель внутри вещество возможный явление чемто новый впервые указывать статья оказываться материал обладать отрицательный преломление описываться отрицательный коэффициент преломление n отношение скорость свет пустота скорость свет вещество излучатель освещать приемник внутри вещество приемник притягиваться излучатель отрицательный скорость положительный скорость излучатель приемник наоборот отрицательный классический школьный опыт брать вода пускать луч свет преломляться внутри вода идти угол идти поверхность вместо вода использовать вещество отрицательный преломление отклоняться налево направо комбинировать вещество отрицательный положительный преломление организовывать прохождение луч свет через набор материальный среда определенный закон както повертываться извиваться обычно привязывать эффект шапкиневидимка иметься эксперимент иметься некий объект сделать невидимый свет проходить вокруг объект наблюдатель кажется объект хотя дело практический применение далеко кроме явление связывать отрицательный преломление наблюдаться область электромагнитный излучение акустика распространение разный род колебание

In [10]:
def get_dataset_internals_folder_path(dataset_name: DatasetName) -> str:
    return os.path.join(DATA_FOLDER_PATH, dataset_name.value + '__internals')

In [11]:
DATASET_INTERNALS_FOLDER_PATH = get_dataset_internals_folder_path(DATASET_NAME)

In [12]:
DATASET_INTERNALS_FOLDER_PATH

'/data_mil/shared/CompressaAI/iterative/data/noow/Post_Science__internals'

In [13]:
%%time

# If using really big datasets (like Habrahabr),
# one may need to set this equal `False`
KEEP_DATASET_IN_MEMORY = True

DATASET = Dataset(
    DATASET_FILE_PATH,
    internals_folder_path=DATASET_INTERNALS_FOLDER_PATH,
    keep_in_memory=KEEP_DATASET_IN_MEMORY,
)

CPU times: user 1.32 s, sys: 119 ms, total: 1.43 s
Wall time: 1.35 s

Looking what is inside dataset's folder

In [14]:
DATASET

In [15]:
DATASET.get_possible_modalities()

{'@word'}

In [16]:
MAIN_MODALITY = '@word'

In [17]:
dictionary = DATASET.get_dictionary()

print(dictionary)

for modality in DATASET.get_possible_modalities():
    if modality not in [MAIN_MODALITY]:
        dictionary.filter(class_id=modality, max_df=0, inplace=True)

artm.Dictionary(name=2901dd17-5ad8-409a-bf5d-782758d4d009, num_entries=82162)

In [18]:
dictionary

artm.Dictionary(name=2901dd17-5ad8-409a-bf5d-782758d4d009, num_entries=82162)

In [19]:
dictionary.filter(min_df=5, max_df_rate=0.5)

artm.Dictionary(name=2901dd17-5ad8-409a-bf5d-782758d4d009, num_entries=19537)

In [20]:
DATASET._cached_dict = dictionary

In [21]:
DATASET.get_dictionary()

artm.Dictionary(name=2901dd17-5ad8-409a-bf5d-782758d4d009, num_entries=19537)

In [22]:
os.listdir(DATASET_INTERNALS_FOLDER_PATH)

['_result', 'result2', 'dict.dict', 'batches', 'vw.txt']

Creating batches

In [23]:
DATASET.get_batch_vectorizer()

artm.BatchVectorizer(data_path="/data_mil/shared/CompressaAI/iterative/data/noow/Post_Science__internals/batches", num_batches=4)

In [24]:
os.listdir(DATASET_INTERNALS_FOLDER_PATH)

['_result', 'result2', 'dict.dict', 'batches', 'vw.txt']

In [25]:
if KEEP_DATASET_IN_MEMORY:
    DOCUMENTS = list(DATASET._data.index)
else:
    DOCUMENTS = list(DATASET._data_index)

NUM_DOCUMENTS = len(DOCUMENTS)

print(f'Num documents: {NUM_DOCUMENTS}')

Num documents: 3446

Let's look at some text samples

In [26]:
DATASET._data.head()

,id,raw_text,vw_text
id,,,
29998.txt,29998.txt,материал отрицательный показатель преломление ...,29998.txt |@word материал отрицательный показа...
7770.txt,7770.txt,культурный код экономика экономист александр а...,7770.txt |@word культурный код экономика эконо...
32230.txt,32230.txt,faq наука третий класс факт эксперимент резуль...,32230.txt |@word faq наука третий класс факт э...
27293.txt,27293.txt,обрушение волна поверхность жидкость математик...,27293.txt |@word обрушение волна поверхность ж...
481.txt,481.txt,существовать ли суперсимметрия мир элементарны...,481.txt |@word существовать ли суперсимметрия ...

In [27]:
MAIN_MODALITY

'@word'

In [28]:
import scipy

from typing import List

from topicnet.cooking_machine.models.base_regularizer import BaseRegularizer
from topicnet.cooking_machine.models.thetaless_regularizer import (
    dataset2sparse_matrix,
)
from topicnet.cooking_machine.models import (
    BaseScore as BaseTopicNetScore,
    TopicModel
)

In [29]:
def calc_doc_occurrences(dataset, modality):
    """
    :param n_dw_matrix: sparse document-word matrix, shape is D x W
    :return: sparse matrix of co-occurrences

    doc_occurrences[w1, w2] = the number of the documents
    where there are w1 and w2
    """
    n_dw_matrix = dataset2sparse_matrix(dataset, modality, modalities_to_use=[modality])
    matrix = (scipy.sparse.csc_matrix(n_dw_matrix) > 0).astype(int)
    co_occurrences = matrix.T * matrix

    return co_occurrences.diagonal(), co_occurrences


def create_pmi_top_function(
    doc_occurrences, doc_co_occurrences,
    documents_number, top_sizes,
    topic_indices=None,
    co_occurrences_smooth=1.
):
    """
    :param doc_occurrences: array of doc occurrences of words
    :param doc_co_occurrences: sparse matrix of doc co-occurrences of words
    :param documents_number: number of the documents
    :param top_sizes: list of top values to calculate top-pmi for
    :param co_occurrences_smooth: constant to smooth co-occurrences in log
    :return: function which takes phi and theta and returns
    pair of two arrays: pmi-s of the tops and ppmi-s of the tops

    pmi[i] - pmi(top of size top_sizes[i])
    ppmi[i] - ppmi(top of size top_sizes[i])

    pmi(words) = sum_{u in words, v in words, u != v}
    log(
        (doc_co_occurrences[u, v] * documents_number + co_occurrences_smooth)
        / doc_occurrences[u] / doc_occurrences[v]
    )

    ppmi(words) = sum_{u in words, v in words, u != v}
    max(log(
        (doc_co_occurrences[u, v] * documents_number + co_occurrences_smooth)
        / doc_occurrences[u] / doc_occurrences[v]
    ), 0)

    """
    def func(phi):
        T, W = phi.shape
        # T = len(topic_indices)
        topic_indices = list(range(T))

        max_top_size = max(top_sizes)
        topic_pmis, topic_ppmis = dict(), dict()
        pmi, ppmi = np.zeros(max_top_size), np.zeros(max_top_size)
        tops = np.argpartition(phi, -max_top_size, axis=1)[:, -max_top_size:]
        
        for t in topic_indices:
            top = sorted(tops[t], key=lambda w: - phi[t, w])
            # print(top, phi.shape, doc_co_occurrences.shape)
            co_occurrences = doc_co_occurrences[top, :][:, top].todense()
            occurrences = doc_occurrences[top]
            values = np.log(
                (co_occurrences * documents_number + co_occurrences_smooth)
                / (occurrences[:, np.newaxis] * occurrences[np.newaxis, :] + co_occurrences_smooth)
            )
            diag = np.diag_indices(len(values))
            # values.cumsum(axis=0).cumsum(axis=1)[diag] - values[diag].cumsum()

            current_pmi = np.array(
               values.cumsum(axis=0).cumsum(axis=1)[diag] - values[diag].cumsum()
            ).ravel()
            topic_pmis[t] = current_pmi
            pmi += current_pmi

            values[values < 0.] = 0.
            current_ppmi = np.array(
               values.cumsum(axis=0).cumsum(axis=1)[diag] - values[diag].cumsum()
            ).ravel()
            topic_ppmis[t] = current_ppmi
            ppmi += current_ppmi
            
        sizes = np.arange(2, max_top_size + 1)
        pmi[1:] /= (T * sizes * (sizes - 1))
        ppmi[1:] /= (T * sizes * (sizes - 1))
        indices = np.array(top_sizes) - 1

        for t in topic_indices:
            topic_pmis[t][1:] /= (sizes * (sizes - 1))
            topic_ppmis[t][1:] /= (sizes * (sizes - 1))

        result_topic_pmis = {t: p[indices] for t, p in topic_pmis.items()}
        result_topic_ppmis = {t: p[indices] for t, p in topic_ppmis.items()}

        return pmi[indices], ppmi[indices], result_topic_pmis, result_topic_ppmis

    return func

In [30]:
%%time

occurences, co_occurences = calc_doc_occurrences(DATASET, MAIN_MODALITY)

CPU times: user 6.43 s, sys: 286 ms, total: 6.72 s
Wall time: 6.64 s

In [31]:
calc_pmi = create_pmi_top_function(
    occurences, co_occurences,
    DATASET.get_dataset().shape[0], [20],
    topic_indices=[0, 1, 2],
    co_occurrences_smooth=1e-2,
)

In [32]:
import copy


class TopTokenCoherence(BaseTopicNetScore):
    def __init__(self, name, func):
        super().__init__()

        self._name = name
        self.calc_pmi = func

    @property
    def name(self):
        return self._name

    def call(self, model: TopicModel):
        values = self.calc_pmi(model.get_phi_dense()[0].T)

        return values[1]

    def call_by_topic(self, model: TopicModel):
        values = self.calc_pmi(model.get_phi_dense()[0].T)

        return values[3]

    def compute(
            self,
            model,
            topics: List[str] = None,
            documents: List[str] = None) -> Dict[str, float]:

        values = self.call_by_topic(model)

        phi = model.get_phi()

        if topics is None:
            topics = list(phi.columns)

            if hasattr(model, 'has_bcg'):
                print(f'Detected bcg topics! Skipping for coherence computation (and will have {len(topics) - 1} topics).')

                topics = topics[:-1]
        else:
            assert False

        index2topic = {phi.columns.get_loc(t): t for t in topics}
        topic2index = {t: i for i, t in index2topic.items()}

        if hasattr(model, 'has_bcg'):
            assert list(index2topic.keys()) == list(values.keys())[:-1]
        else:
            assert list(index2topic.keys()) == list(values.keys())

        result = {
            t: float(values[topic2index[t]])
            for t in topics
        }

        assert len(result) == len(index2topic)

        return result

    def _attach(self, model: TopicModel):
        if self._name in model.custom_scores:
            print(
                f'Score with such name "{self._name}" already attached to model!'
                f' So rewriting it...'
                f' All model\'s custom scores: {list(model.custom_scores.keys())}'
            )

        # TODO: TopicModel should provide ability to add custom scores
        model.custom_scores[self.name] = copy.deepcopy(self)

## Experiment<a id="experiment"></a>

Finally we are getting to the main part!)

### Scores (for Topics and Models)<a id="scores"></a>

<div style="text-align: right">Back to <a href=#contents>Contents</a></div>

Here we define a lot of scores (which mainly differ in initial parameters).

In [33]:
ONE_MODEL_NUM_TOPICS = 20
NUM_TOP_WORDS = 20

In [34]:
top = NUM_TOP_WORDS
target_topic_indices = list(range(ONE_MODEL_NUM_TOPICS))

coherence_score = TopTokenCoherence(
    name=f'coherence_{top}',
    func=create_pmi_top_function(
        occurences, co_occurences,
        DATASET.get_dataset().shape[0], [top],
        # topic_indices=target_topic_indices,
        co_occurrences_smooth=1e-2,
    )
)

intra_coherence_score = IntratextCoherenceScore(
    name='toplen_ptw',
    data=DATASET,
    computation_method=ComputationMethod.SEGMENT_LENGTH,
    word_topic_relatedness=WordTopicRelatednessType.PTW,
    should_compute=False,
)

diversity_scores = [
    DiversityScore(
        name=f'diversity_{metric}',
        metric=metric,
        class_ids=MAIN_MODALITY,
    )

    for metric in KNOWN_METRICS
]

Other coherence score variations

And a pair of default ARTM scores (these ones are fast)

In [35]:
other_scores = [
    PerplexityScore(
        name='perplexity'
    ),
]

### Bank Creation<a id="bank-creation"></a>

<div style="text-align: right">Back to <a href=#contents>Contents</a></div>

Here we finally run the experiment!

In [36]:
NUM_ITERATIONS = 20

In [37]:
seed = 0

In [46]:
# We use only one train function here
# Other variations are also possible
# It would be even better to make bank using several train functions
# However, it would also take way more time 

TRAIN_FUNCS = default_train_func  # default train func

In [47]:
DATASET_INTERNALS_FOLDER_PATH

'/data_mil/shared/CompressaAI/iterative/data/noow/Post_Science__internals'

In [48]:
SEARCH_RESULTS_FOLDER_PATH = os.path.join(
    DATASET_INTERNALS_FOLDER_PATH, 'result'
)

# File with some info about the process
SEARCH_RESULT_FILE_PATH = os.path.join(
    SEARCH_RESULTS_FOLDER_PATH, f'search_result__{seed}.json'
)

# Bank, with topics and their score values
BANK_FOLDER_PATH = os.path.join(
    SEARCH_RESULTS_FOLDER_PATH, f'bank__{seed}'
)

! ls -alh ./Post_Science__internals

In [49]:
SEARCH_RESULTS_FOLDER_PATH

'/data_mil/shared/CompressaAI/iterative/data/noow/Post_Science__internals/result'

In [50]:
! ls $SEARCH_RESULTS_FOLDER_PATH

ls: cannot access '/data_mil/shared/CompressaAI/iterative/data/noow/Post_Science__internals/result': No such file or directory

In [51]:
BANK_FOLDER_PATH

'/data_mil/shared/CompressaAI/iterative/data/noow/Post_Science__internals/result/bank__0'

In [52]:
os.makedirs(SEARCH_RESULTS_FOLDER_PATH, exist_ok=True)
os.makedirs(BANK_FOLDER_PATH, exist_ok=True)

In [53]:
seed

0

In [37]:
from topnum.model_constructor import init_model_from_family

model = init_model_from_family(
    family='PLSA',
    dataset=DATASET,
    main_modality=MAIN_MODALITY,
    num_topics=10,
    seed=42,
)

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

In [38]:
model.get_phi().shape

(19186, 10)

In [38]:
from topnum.search_methods.topic_bank.one_model_train_funcs import (default_train_func, _get_topic_model)

In [39]:
model = _get_topic_model(DATASET, num_topics=10)

In [40]:
model.get_phi().shape

(53095, 10)

In [41]:
dictionary = DATASET.get_dictionary()

In [42]:
dictionary

artm.Dictionary(name=475dc0db-1744-492d-8221-1ef62a29a4cf, num_entries=53095)

In [39]:
# https://github.com/machine-intelligence-laboratory/OptimalNumberOfTopics/blob/master/topnum/model_constructor.py#L120C5-L122C73

dictionary = DATASET.get_dictionary()

print(dictionary)

for modality in DATASET.get_possible_modalities():
    if modality not in [MAIN_MODALITY]:
        dictionary.filter(class_id=modality, max_df=0, inplace=True)

artm.Dictionary(name=254bd7ab-7b17-481c-9572-6f2457b051a7, num_entries=53095)

In [40]:
print(dictionary)

artm.Dictionary(name=254bd7ab-7b17-481c-9572-6f2457b051a7, num_entries=19186)

In [41]:
DATASET._cached_dict = dictionary

In [42]:
DATASET.get_dictionary()

artm.Dictionary(name=254bd7ab-7b17-481c-9572-6f2457b051a7, num_entries=19186)

One cay vary some parameters below (for example `max_num_models` and `num_fit_iterations`).

In [54]:
optimizer = TopicBankMethod(
    data        = DATASET,
    main_modality = MAIN_MODALITY,
    
    min_df_rate = 0.0,  # dictionary filtering has already been done little earlier
    max_df_rate = 1.0,  #   so we don't want these parameters to have any effect

    main_topic_score   = intra_coherence_score,  # coherence_score,
    other_topic_scores = [coherence_score],
    other_scores       = [coherence_score] + diversity_scores + other_scores,
   # documents          = TEST_DOCUMENTS,

    start_model_number   = 0,
    max_num_models       = 20,
    one_model_num_topics = ONE_MODEL_NUM_TOPICS,  # 100,
    num_fit_iterations   = NUM_ITERATIONS,  # 100,  # 100 should be enough;
                                 # however, for big data better to reduce this one
                                 # (otherwise the process will be too slow)

    topic_score_threshold_percentile = 90,

    save_bank         = True,
    save_model_topics = True,
    save_file_path    = SEARCH_RESULT_FILE_PATH,
    bank_folder_path  = BANK_FOLDER_PATH,

    train_funcs = TRAIN_FUNCS,
    
    verbose = True,
)

# TODO: use Holdout Perplexity as Stop score

In [55]:
optimizer._result.keys()

dict_keys(['optimum', 'optimum_std', 'bank_scores', 'bank_topic_scores', 'model_scores', 'model_topic_scores', 'num_bank_topics', 'num_model_topics'])

Checking file paths

! ls ./Post_Science__internals

In [56]:
optimizer._save_file_path

'/data_mil/shared/CompressaAI/iterative/data/noow/Post_Science__internals/result/search_result__0.json'

In [57]:
optimizer._topic_bank._path

'/data_mil/shared/CompressaAI/iterative/data/noow/Post_Science__internals/result/bank__0'

Fulfilling the search (get ready for a really long process!):

In [58]:
%%time

optimizer.search_for_optimum(DATASET)

  0%|                                                        | 0/20 [00:00<?, ?it/s]
  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████▌                        | 1/2 [00:03<00:03,  3.53s/it]
100%|█████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.85s/it]
!!! Bank Phi: [[8.24879123e-11 0.00000000e+00]
 [6.91189372e-09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.20617991e-09]].
!!! Bank model Phi: [[1.7454794e-09 3.3315755e-09]
 [1.1203075e-08 7.0101908e-10]
 [2.0083948e-10 4.7927644e-09]
 ...
 [4.6382178e-09 5.3519282e-09]
 [1.6459716e-11 5.9757088e-09]
 [3.6669872e-09 2.5503558e-08]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[8.24879123e-11 0.00000000e+00]
 [6.91189372e-09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.20617991e-09]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 8.3503792e-06]
 [4.4969144e-09 0.0000000e+00 8.3502337e-06]
 [0.0000000e+00 0.0000000e+00 8.3503792e-06]
 ...
 [0.0000000e+00 0.0000000e+00 1.0916711e-05]
 [0.0000000e+00 0.0000000e+00 8.8636452e-06]
 [0.0000000e+00 0.0000000e+00 1.9642241e-05]].
Bank scores: {'perplexity_score': 23124.765625, 'coherence_20': 1.108715281159298, 'diversity_euclidean': 0.06128161394476187, 'diversity_jensenshannon': 0.6049273128020183, 'diversity_hellinger': 0.7027380289919795, 'diversity_cosine': 0.8045688381391027, 'perplexity': 23124.765625, 'ppl_fair': 23124.765625, 'ppl_cheatty': 4137.58447265625}
  5%|██▍                                             | 1/20 [00:40<12:43, 40.17s/it]
  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████▌                        | 1/2 [00:03<00:03,  3.39s/it]
100%|█████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.79s/it]
Creating first level with 2 topics. Dictionary: artm.Dictionary(name=51ca6d9b-c2ec-4475-b5f2-cc8f6f147d1d, num_entries=19537).
Copying phi for the first level. Phi shape: (19537, 2). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           )
Creating second level with 20 topics
Copying phi for the second level. Phi shape: (19537, 20). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           names=['modality', 'token'])
!!! Bank Phi: [[8.24879123e-11 0.00000000e+00]
 [6.91189372e-09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.20617991e-09]].
!!! Bank model Phi: [[1.7454793e-09 3.3315759e-09]
 [1.1203075e-08 7.0101908e-10]
 [2.0083948e-10 4.7927644e-09]
 ...
 [4.6382183e-09 5.3519282e-09]
 [1.6459714e-11 5.9757088e-09]
 [3.6669872e-09 2.5503558e-08]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[8.24879123e-11 0.00000000e+00]
 [6.91189372e-09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.20617991e-09]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 8.3503792e-06]
 [4.4969144e-09 0.0000000e+00 8.3502337e-06]
 [0.0000000e+00 0.0000000e+00 8.3503792e-06]
 ...
 [0.0000000e+00 0.0000000e+00 1.0916711e-05]
 [0.0000000e+00 0.0000000e+00 8.8636452e-06]
 [0.0000000e+00 0.0000000e+00 1.9642241e-05]].
Bank scores: {'perplexity_score': 23124.765625, 'coherence_20': 1.108715281159298, 'diversity_euclidean': 0.061281613944761996, 'diversity_jensenshannon': 0.6049273128025354, 'diversity_hellinger': 0.7027380289921429, 'diversity_cosine': 0.8045688381391178, 'perplexity': 23124.765625, 'ppl_fair': 23124.765625, 'ppl_cheatty': 4137.58447265625}
 10%|████▊                                           | 2/20 [01:29<13:42, 45.71s/it]
  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████▌                        | 1/2 [00:03<00:03,  3.43s/it]
100%|█████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.82s/it]
Creating first level with 2 topics. Dictionary: artm.Dictionary(name=51ca6d9b-c2ec-4475-b5f2-cc8f6f147d1d, num_entries=19537).
Copying phi for the first level. Phi shape: (19537, 2). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           )
Creating second level with 20 topics
Copying phi for the second level. Phi shape: (19537, 20). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           names=['modality', 'token'])
!!! Bank Phi: [[8.24879123e-11 0.00000000e+00]
 [6.91189372e-09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.20617991e-09]].
!!! Bank model Phi: [[1.7454794e-09 3.3315759e-09]
 [1.1203075e-08 7.0101908e-10]
 [2.0083948e-10 4.7927644e-09]
 ...
 [4.6382178e-09 5.3519282e-09]
 [1.6459716e-11 5.9757088e-09]
 [3.6669872e-09 2.5503558e-08]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[8.24879123e-11 0.00000000e+00]
 [6.91189372e-09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.20617991e-09]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 8.3503792e-06]
 [4.4969144e-09 0.0000000e+00 8.3502337e-06]
 [0.0000000e+00 0.0000000e+00 8.3503792e-06]
 ...
 [0.0000000e+00 0.0000000e+00 1.0916711e-05]
 [0.0000000e+00 0.0000000e+00 8.8636452e-06]
 [0.0000000e+00 0.0000000e+00 1.9642241e-05]].
Bank scores: {'perplexity_score': 23124.765625, 'coherence_20': 1.108715281159298, 'diversity_euclidean': 0.06128161394476197, 'diversity_jensenshannon': 0.6049273128023913, 'diversity_hellinger': 0.7027380289917406, 'diversity_cosine': 0.8045688381391177, 'perplexity': 23124.765625, 'ppl_fair': 23124.765625, 'ppl_cheatty': 4137.58447265625}
 15%|███████▏                                        | 3/20 [02:20<13:32, 47.81s/it]
  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████▌                        | 1/2 [00:03<00:03,  3.33s/it]
100%|█████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.76s/it]
Creating first level with 2 topics. Dictionary: artm.Dictionary(name=51ca6d9b-c2ec-4475-b5f2-cc8f6f147d1d, num_entries=19537).
Copying phi for the first level. Phi shape: (19537, 2). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           )
Creating second level with 20 topics
Copying phi for the second level. Phi shape: (19537, 20). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           names=['modality', 'token'])
!!! Bank Phi: [[8.24879123e-11 0.00000000e+00]
 [6.91189372e-09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.20617991e-09]].
!!! Bank model Phi: [[1.7454793e-09 3.3315759e-09]
 [1.1203075e-08 7.0101908e-10]
 [2.0083950e-10 4.7927644e-09]
 ...
 [4.6382178e-09 5.3519282e-09]
 [1.6459716e-11 5.9757088e-09]
 [3.6669872e-09 2.5503558e-08]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[8.24879123e-11 0.00000000e+00]
 [6.91189372e-09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.20617991e-09]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 8.3503792e-06]
 [4.4969144e-09 0.0000000e+00 8.3502337e-06]
 [0.0000000e+00 0.0000000e+00 8.3503792e-06]
 ...
 [0.0000000e+00 0.0000000e+00 1.0916711e-05]
 [0.0000000e+00 0.0000000e+00 8.8636452e-06]
 [0.0000000e+00 0.0000000e+00 1.9642241e-05]].
Bank scores: {'perplexity_score': 23124.765625, 'coherence_20': 1.108715281159298, 'diversity_euclidean': 0.06128161394476194, 'diversity_jensenshannon': 0.604927312802019, 'diversity_hellinger': 0.7027380289914511, 'diversity_cosine': 0.8045688381391175, 'perplexity': 23124.765625, 'ppl_fair': 23124.765625, 'ppl_cheatty': 4137.58447265625}
 20%|█████████▌                                      | 4/20 [03:09<12:54, 48.38s/it]
  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████▌                        | 1/2 [00:03<00:03,  3.48s/it]
100%|█████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.84s/it]
Creating first level with 2 topics. Dictionary: artm.Dictionary(name=51ca6d9b-c2ec-4475-b5f2-cc8f6f147d1d, num_entries=19537).
Copying phi for the first level. Phi shape: (19537, 2). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           )
Creating second level with 20 topics
Copying phi for the second level. Phi shape: (19537, 20). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           names=['modality', 'token'])
!!! Bank Phi: [[8.24879123e-11 0.00000000e+00]
 [6.91189372e-09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.20617991e-09]].
!!! Bank model Phi: [[1.7454794e-09 3.3315759e-09]
 [1.1203075e-08 7.0101908e-10]
 [2.0083950e-10 4.7927644e-09]
 ...
 [4.6382183e-09 5.3519282e-09]
 [1.6459716e-11 5.9757088e-09]
 [3.6669872e-09 2.5503558e-08]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[8.24879123e-11 0.00000000e+00]
 [6.91189372e-09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.20617991e-09]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 8.3503792e-06]
 [4.4969144e-09 0.0000000e+00 8.3502337e-06]
 [0.0000000e+00 0.0000000e+00 8.3503792e-06]
 ...
 [0.0000000e+00 0.0000000e+00 1.0916711e-05]
 [0.0000000e+00 0.0000000e+00 8.8636452e-06]
 [0.0000000e+00 0.0000000e+00 1.9642241e-05]].
Bank scores: {'perplexity_score': 23124.765625, 'coherence_20': 1.108715281159298, 'diversity_euclidean': 0.06128161394476193, 'diversity_jensenshannon': 0.6049273128023623, 'diversity_hellinger': 0.7027380289918433, 'diversity_cosine': 0.8045688381391175, 'perplexity': 23124.765625, 'ppl_fair': 23124.765625, 'ppl_cheatty': 4137.58447265625}
 25%|████████████                                    | 5/20 [03:59<12:12, 48.86s/it]
  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████▌                        | 1/2 [00:03<00:03,  3.36s/it]
100%|█████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.78s/it]
Creating first level with 2 topics. Dictionary: artm.Dictionary(name=51ca6d9b-c2ec-4475-b5f2-cc8f6f147d1d, num_entries=19537).
Copying phi for the first level. Phi shape: (19537, 2). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           )
Creating second level with 20 topics
Copying phi for the second level. Phi shape: (19537, 20). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           names=['modality', 'token'])
!!! Bank Phi: [[8.24879123e-11 0.00000000e+00]
 [6.91189372e-09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.20617991e-09]].
!!! Bank model Phi: [[1.7454794e-09 3.3315759e-09]
 [1.1203075e-08 7.0101908e-10]
 [2.0083954e-10 4.7927644e-09]
 ...
 [4.6382183e-09 5.3519278e-09]
 [1.6459714e-11 5.9757088e-09]
 [3.6669880e-09 2.5503558e-08]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[8.24879123e-11 0.00000000e+00]
 [6.91189372e-09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.20617991e-09]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 8.3503792e-06]
 [4.4969144e-09 0.0000000e+00 8.3502337e-06]
 [0.0000000e+00 0.0000000e+00 8.3503792e-06]
 ...
 [0.0000000e+00 0.0000000e+00 1.0916711e-05]
 [0.0000000e+00 0.0000000e+00 8.8636452e-06]
 [0.0000000e+00 0.0000000e+00 1.9642241e-05]].
Bank scores: {'perplexity_score': 23124.765625, 'coherence_20': 1.108715281159298, 'diversity_euclidean': 0.06128161394476193, 'diversity_jensenshannon': 0.6049273128011523, 'diversity_hellinger': 0.702738028991041, 'diversity_cosine': 0.8045688381391033, 'perplexity': 23124.765625, 'ppl_fair': 23124.765625, 'ppl_cheatty': 4137.58447265625}
 30%|██████████████▍                                 | 6/20 [04:48<11:28, 49.16s/it]
  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████▌                        | 1/2 [00:03<00:03,  3.41s/it]
100%|█████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.81s/it]
Creating first level with 2 topics. Dictionary: artm.Dictionary(name=51ca6d9b-c2ec-4475-b5f2-cc8f6f147d1d, num_entries=19537).
Copying phi for the first level. Phi shape: (19537, 2). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           )
Creating second level with 20 topics
Copying phi for the second level. Phi shape: (19537, 20). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           names=['modality', 'token'])
!!! Bank Phi: [[8.24879123e-11 0.00000000e+00]
 [6.91189372e-09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.20617991e-09]].
!!! Bank model Phi: [[1.7454794e-09 3.3315759e-09]
 [1.1203075e-08 7.0101908e-10]
 [2.0083954e-10 4.7927644e-09]
 ...
 [4.6382183e-09 5.3519278e-09]
 [1.6459714e-11 5.9757088e-09]
 [3.6669880e-09 2.5503558e-08]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[8.24879123e-11 0.00000000e+00]
 [6.91189372e-09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.20617991e-09]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 8.3503792e-06]
 [4.4969144e-09 0.0000000e+00 8.3502337e-06]
 [0.0000000e+00 0.0000000e+00 8.3503792e-06]
 ...
 [0.0000000e+00 0.0000000e+00 1.0916711e-05]
 [0.0000000e+00 0.0000000e+00 8.8636452e-06]
 [0.0000000e+00 0.0000000e+00 1.9642241e-05]].
Bank scores: {'perplexity_score': 23124.765625, 'coherence_20': 1.108715281159298, 'diversity_euclidean': 0.06128161394476197, 'diversity_jensenshannon': 0.6049273128013946, 'diversity_hellinger': 0.7027380289910712, 'diversity_cosine': 0.8045688381391034, 'perplexity': 23124.765625, 'ppl_fair': 23124.765625, 'ppl_cheatty': 4137.58447265625}
 35%|████████████████▊                               | 7/20 [05:39<10:43, 49.53s/it]
  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████▌                        | 1/2 [00:03<00:03,  3.41s/it]
100%|█████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.81s/it]
Creating first level with 2 topics. Dictionary: artm.Dictionary(name=51ca6d9b-c2ec-4475-b5f2-cc8f6f147d1d, num_entries=19537).
Copying phi for the first level. Phi shape: (19537, 2). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           )
Creating second level with 20 topics
Copying phi for the second level. Phi shape: (19537, 20). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           names=['modality', 'token'])
!!! Bank Phi: [[8.24879123e-11 0.00000000e+00]
 [6.91189372e-09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.20617991e-09]].
!!! Bank model Phi: [[1.7454794e-09 3.3315755e-09]
 [1.1203075e-08 7.0101908e-10]
 [2.0083948e-10 4.7927644e-09]
 ...
 [4.6382183e-09 5.3519278e-09]
 [1.6459716e-11 5.9757088e-09]
 [3.6669883e-09 2.5503558e-08]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[8.24879123e-11 0.00000000e+00]
 [6.91189372e-09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.20617991e-09]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 8.3503792e-06]
 [4.4969144e-09 0.0000000e+00 8.3502337e-06]
 [0.0000000e+00 0.0000000e+00 8.3503792e-06]
 ...
 [0.0000000e+00 0.0000000e+00 1.0916711e-05]
 [0.0000000e+00 0.0000000e+00 8.8636452e-06]
 [0.0000000e+00 0.0000000e+00 1.9642241e-05]].
Bank scores: {'perplexity_score': 23124.765625, 'coherence_20': 1.108715281159298, 'diversity_euclidean': 0.06128161394476407, 'diversity_jensenshannon': 0.6049273128021715, 'diversity_hellinger': 0.7027380289929257, 'diversity_cosine': 0.8045688381391276, 'perplexity': 23124.765625, 'ppl_fair': 23124.765625, 'ppl_cheatty': 4137.58447265625}
 40%|███████████████████▏                            | 8/20 [06:29<09:56, 49.71s/it]
  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████▌                        | 1/2 [00:03<00:03,  3.38s/it]
100%|█████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.79s/it]
Creating first level with 2 topics. Dictionary: artm.Dictionary(name=51ca6d9b-c2ec-4475-b5f2-cc8f6f147d1d, num_entries=19537).
Copying phi for the first level. Phi shape: (19537, 2). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           )
Creating second level with 20 topics
Copying phi for the second level. Phi shape: (19537, 20). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           names=['modality', 'token'])
!!! Bank Phi: [[8.24879123e-11 0.00000000e+00]
 [6.91189372e-09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.20617991e-09]].
!!! Bank model Phi: [[1.7454794e-09 3.3315759e-09]
 [1.1203075e-08 7.0101908e-10]
 [2.0083954e-10 4.7927644e-09]
 ...
 [4.6382183e-09 5.3519278e-09]
 [1.6459714e-11 5.9757088e-09]
 [3.6669883e-09 2.5503558e-08]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[8.24879123e-11 0.00000000e+00]
 [6.91189372e-09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.20617991e-09]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 8.3503792e-06]
 [4.4969144e-09 0.0000000e+00 8.3502337e-06]
 [0.0000000e+00 0.0000000e+00 8.3503792e-06]
 ...
 [0.0000000e+00 0.0000000e+00 1.0916710e-05]
 [0.0000000e+00 0.0000000e+00 8.8636452e-06]
 [0.0000000e+00 0.0000000e+00 1.9642241e-05]].
Bank scores: {'perplexity_score': 23124.765625, 'coherence_20': 1.108715281159298, 'diversity_euclidean': 0.06128161394476193, 'diversity_jensenshannon': 0.6049273128012509, 'diversity_hellinger': 0.7027380289909542, 'diversity_cosine': 0.8045688381391032, 'perplexity': 23124.765625, 'ppl_fair': 23124.765625, 'ppl_cheatty': 4137.58447265625}
 45%|█████████████████████▌                          | 9/20 [07:18<09:04, 49.45s/it]
  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████▌                        | 1/2 [00:03<00:03,  3.36s/it]
100%|█████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.77s/it]
Creating first level with 2 topics. Dictionary: artm.Dictionary(name=51ca6d9b-c2ec-4475-b5f2-cc8f6f147d1d, num_entries=19537).
Copying phi for the first level. Phi shape: (19537, 2). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           )
Creating second level with 20 topics
Copying phi for the second level. Phi shape: (19537, 20). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           names=['modality', 'token'])
!!! Bank Phi: [[8.24879123e-11 0.00000000e+00]
 [6.91189372e-09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.20617991e-09]].
!!! Bank model Phi: [[1.7454794e-09 3.3315759e-09]
 [1.1203075e-08 7.0101908e-10]
 [2.0083948e-10 4.7927644e-09]
 ...
 [4.6382183e-09 5.3519282e-09]
 [1.6459714e-11 5.9757088e-09]
 [3.6669872e-09 2.5503558e-08]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[8.24879123e-11 0.00000000e+00]
 [6.91189372e-09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.20617991e-09]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 8.3503783e-06]
 [4.4969144e-09 0.0000000e+00 8.3502318e-06]
 [0.0000000e+00 0.0000000e+00 8.3503783e-06]
 ...
 [0.0000000e+00 0.0000000e+00 1.0916710e-05]
 [0.0000000e+00 0.0000000e+00 8.8636443e-06]
 [0.0000000e+00 0.0000000e+00 1.9642239e-05]].
Bank scores: {'perplexity_score': 23124.765625, 'coherence_20': 1.108715281159298, 'diversity_euclidean': 0.06128161394476191, 'diversity_jensenshannon': 0.6049273128023135, 'diversity_hellinger': 0.7027380289919261, 'diversity_cosine': 0.804568838139117, 'perplexity': 23124.765625, 'ppl_fair': 23124.765625, 'ppl_cheatty': 4137.58447265625}
 50%|███████████████████████▌                       | 10/20 [08:07<08:15, 49.56s/it]
  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████▌                        | 1/2 [00:03<00:03,  3.43s/it]
100%|█████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.81s/it]
Creating first level with 2 topics. Dictionary: artm.Dictionary(name=51ca6d9b-c2ec-4475-b5f2-cc8f6f147d1d, num_entries=19537).
Copying phi for the first level. Phi shape: (19537, 2). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           )
Creating second level with 20 topics
Copying phi for the second level. Phi shape: (19537, 20). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           names=['modality', 'token'])
!!! Bank Phi: [[8.24879123e-11 0.00000000e+00]
 [6.91189372e-09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.20617991e-09]].
!!! Bank model Phi: [[1.7454793e-09 3.3315759e-09]
 [1.1203075e-08 7.0101913e-10]
 [2.0083948e-10 4.7927644e-09]
 ...
 [4.6382178e-09 5.3519282e-09]
 [1.6459716e-11 5.9757088e-09]
 [3.6669872e-09 2.5503558e-08]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[8.24879123e-11 0.00000000e+00]
 [6.91189372e-09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.20617991e-09]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 8.3503792e-06]
 [4.4969144e-09 0.0000000e+00 8.3502337e-06]
 [0.0000000e+00 0.0000000e+00 8.3503792e-06]
 ...
 [0.0000000e+00 0.0000000e+00 1.0916710e-05]
 [0.0000000e+00 0.0000000e+00 8.8636452e-06]
 [0.0000000e+00 0.0000000e+00 1.9642241e-05]].
Bank scores: {'perplexity_score': 23124.765625, 'coherence_20': 1.108715281159298, 'diversity_euclidean': 0.061281613945841626, 'diversity_jensenshannon': 0.6049273127988266, 'diversity_hellinger': 0.7027380290187945, 'diversity_cosine': 0.8045688381213456, 'perplexity': 23124.765625, 'ppl_fair': 23124.765625, 'ppl_cheatty': 4137.58447265625}
 55%|█████████████████████████▊                     | 11/20 [08:57<07:27, 49.71s/it]
  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████▌                        | 1/2 [00:03<00:03,  3.37s/it]
100%|█████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.78s/it]
Creating first level with 2 topics. Dictionary: artm.Dictionary(name=51ca6d9b-c2ec-4475-b5f2-cc8f6f147d1d, num_entries=19537).
Copying phi for the first level. Phi shape: (19537, 2). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           )
Creating second level with 20 topics
Copying phi for the second level. Phi shape: (19537, 20). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           names=['modality', 'token'])
!!! Bank Phi: [[8.24879123e-11 0.00000000e+00]
 [6.91189372e-09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.20617991e-09]].
!!! Bank model Phi: [[1.7454793e-09 3.3315759e-09]
 [1.1203075e-08 7.0101908e-10]
 [2.0083950e-10 4.7927644e-09]
 ...
 [4.6382178e-09 5.3519282e-09]
 [1.6459716e-11 5.9757088e-09]
 [3.6669872e-09 2.5503558e-08]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[8.24879123e-11 0.00000000e+00]
 [6.91189372e-09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.20617991e-09]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 8.3503792e-06]
 [4.4969144e-09 0.0000000e+00 8.3502337e-06]
 [0.0000000e+00 0.0000000e+00 8.3503792e-06]
 ...
 [0.0000000e+00 0.0000000e+00 1.0916711e-05]
 [0.0000000e+00 0.0000000e+00 8.8636452e-06]
 [0.0000000e+00 0.0000000e+00 1.9642241e-05]].
Bank scores: {'perplexity_score': 23124.765625, 'coherence_20': 1.108715281159298, 'diversity_euclidean': 0.06128161394476188, 'diversity_jensenshannon': 0.6049273128015165, 'diversity_hellinger': 0.7027380289913433, 'diversity_cosine': 0.804568838139103, 'perplexity': 23124.765625, 'ppl_fair': 23124.765625, 'ppl_cheatty': 4137.58447265625}
 60%|████████████████████████████▏                  | 12/20 [09:47<06:36, 49.59s/it]
  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████▌                        | 1/2 [00:03<00:03,  3.42s/it]
100%|█████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.80s/it]
Creating first level with 2 topics. Dictionary: artm.Dictionary(name=51ca6d9b-c2ec-4475-b5f2-cc8f6f147d1d, num_entries=19537).
Copying phi for the first level. Phi shape: (19537, 2). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           )
Creating second level with 20 topics
Copying phi for the second level. Phi shape: (19537, 20). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           names=['modality', 'token'])
!!! Bank Phi: [[8.24879123e-11 0.00000000e+00]
 [6.91189372e-09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.20617991e-09]].
!!! Bank model Phi: [[1.7454793e-09 3.3315759e-09]
 [1.1203075e-08 7.0101908e-10]
 [2.0083948e-10 4.7927644e-09]
 ...
 [4.6382178e-09 5.3519282e-09]
 [1.6459716e-11 5.9757088e-09]
 [3.6669872e-09 2.5503558e-08]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[8.24879123e-11 0.00000000e+00]
 [6.91189372e-09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.20617991e-09]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 8.3503792e-06]
 [4.4969144e-09 0.0000000e+00 8.3502337e-06]
 [0.0000000e+00 0.0000000e+00 8.3503792e-06]
 ...
 [0.0000000e+00 0.0000000e+00 1.0916711e-05]
 [0.0000000e+00 0.0000000e+00 8.8636452e-06]
 [0.0000000e+00 0.0000000e+00 1.9642241e-05]].
Bank scores: {'perplexity_score': 23124.765625, 'coherence_20': 1.108715281159298, 'diversity_euclidean': 0.061281613944761906, 'diversity_jensenshannon': 0.6049273128022058, 'diversity_hellinger': 0.7027380289914631, 'diversity_cosine': 0.8045688381391174, 'perplexity': 23124.765625, 'ppl_fair': 23124.765625, 'ppl_cheatty': 4137.58447265625}
 65%|██████████████████████████████▌                | 13/20 [10:36<05:46, 49.52s/it]
  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████▌                        | 1/2 [00:03<00:03,  3.47s/it]
100%|█████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.83s/it]
Creating first level with 2 topics. Dictionary: artm.Dictionary(name=51ca6d9b-c2ec-4475-b5f2-cc8f6f147d1d, num_entries=19537).
Copying phi for the first level. Phi shape: (19537, 2). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           )
Creating second level with 20 topics
Copying phi for the second level. Phi shape: (19537, 20). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           names=['modality', 'token'])
!!! Bank Phi: [[8.24879123e-11 0.00000000e+00]
 [6.91189372e-09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.20617991e-09]].
!!! Bank model Phi: [[1.7454794e-09 3.3315759e-09]
 [1.1203075e-08 7.0101908e-10]
 [2.0083954e-10 4.7927644e-09]
 ...
 [4.6382183e-09 5.3519278e-09]
 [1.6459714e-11 5.9757088e-09]
 [3.6669883e-09 2.5503558e-08]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[8.24879123e-11 0.00000000e+00]
 [6.91189372e-09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.20617991e-09]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 8.3503792e-06]
 [4.4969144e-09 0.0000000e+00 8.3502337e-06]
 [0.0000000e+00 0.0000000e+00 8.3503792e-06]
 ...
 [0.0000000e+00 0.0000000e+00 1.0916711e-05]
 [0.0000000e+00 0.0000000e+00 8.8636452e-06]
 [0.0000000e+00 0.0000000e+00 1.9642241e-05]].
Bank scores: {'perplexity_score': 23124.765625, 'coherence_20': 1.108715281159298, 'diversity_euclidean': 0.06128161394476191, 'diversity_jensenshannon': 0.6049273128011301, 'diversity_hellinger': 0.7027380289907055, 'diversity_cosine': 0.8045688381391031, 'perplexity': 23124.765625, 'ppl_fair': 23124.765625, 'ppl_cheatty': 4137.58447265625}
 70%|████████████████████████████████▉              | 14/20 [11:26<04:58, 49.71s/it]
  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████▌                        | 1/2 [00:03<00:03,  3.45s/it]
100%|█████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.82s/it]
Creating first level with 2 topics. Dictionary: artm.Dictionary(name=51ca6d9b-c2ec-4475-b5f2-cc8f6f147d1d, num_entries=19537).
Copying phi for the first level. Phi shape: (19537, 2). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           )
Creating second level with 20 topics
Copying phi for the second level. Phi shape: (19537, 20). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           names=['modality', 'token'])
!!! Bank Phi: [[8.24879123e-11 0.00000000e+00]
 [6.91189372e-09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.20617991e-09]].
!!! Bank model Phi: [[1.7454794e-09 3.3315759e-09]
 [1.1203075e-08 7.0101908e-10]
 [2.0083954e-10 4.7927644e-09]
 ...
 [4.6382183e-09 5.3519278e-09]
 [1.6459714e-11 5.9757088e-09]
 [3.6669883e-09 2.5503558e-08]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[8.24879123e-11 0.00000000e+00]
 [6.91189372e-09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.20617991e-09]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 8.3503792e-06]
 [4.4969144e-09 0.0000000e+00 8.3502337e-06]
 [0.0000000e+00 0.0000000e+00 8.3503792e-06]
 ...
 [0.0000000e+00 0.0000000e+00 1.0916710e-05]
 [0.0000000e+00 0.0000000e+00 8.8636452e-06]
 [0.0000000e+00 0.0000000e+00 1.9642241e-05]].
Bank scores: {'perplexity_score': 23124.765625, 'coherence_20': 1.108715281159298, 'diversity_euclidean': 0.06128161394476191, 'diversity_jensenshannon': 0.6049273128013115, 'diversity_hellinger': 0.7027380289909466, 'diversity_cosine': 0.8045688381391031, 'perplexity': 23124.765625, 'ppl_fair': 23124.765625, 'ppl_cheatty': 4137.58447265625}
 75%|███████████████████████████████████▎           | 15/20 [12:16<04:08, 49.71s/it]
  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████▌                        | 1/2 [00:03<00:03,  3.49s/it]
100%|█████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.85s/it]
Creating first level with 2 topics. Dictionary: artm.Dictionary(name=51ca6d9b-c2ec-4475-b5f2-cc8f6f147d1d, num_entries=19537).
Copying phi for the first level. Phi shape: (19537, 2). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           )
Creating second level with 20 topics
Copying phi for the second level. Phi shape: (19537, 20). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           names=['modality', 'token'])
!!! Bank Phi: [[8.24879123e-11 0.00000000e+00]
 [6.91189372e-09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.20617991e-09]].
!!! Bank model Phi: [[1.7454794e-09 3.3315759e-09]
 [1.1203075e-08 7.0101908e-10]
 [2.0083950e-10 4.7927644e-09]
 ...
 [4.6382183e-09 5.3519278e-09]
 [1.6459714e-11 5.9757088e-09]
 [3.6669883e-09 2.5503558e-08]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[8.24879123e-11 0.00000000e+00]
 [6.91189372e-09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.20617991e-09]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 8.3503792e-06]
 [4.4969144e-09 0.0000000e+00 8.3502337e-06]
 [0.0000000e+00 0.0000000e+00 8.3503792e-06]
 ...
 [0.0000000e+00 0.0000000e+00 1.0916711e-05]
 [0.0000000e+00 0.0000000e+00 8.8636452e-06]
 [0.0000000e+00 0.0000000e+00 1.9642241e-05]].
Bank scores: {'perplexity_score': 23124.765625, 'coherence_20': 1.108715281159298, 'diversity_euclidean': 0.06128161394476196, 'diversity_jensenshannon': 0.604927312801761, 'diversity_hellinger': 0.702738028991268, 'diversity_cosine': 0.8045688381391175, 'perplexity': 23124.765625, 'ppl_fair': 23124.765625, 'ppl_cheatty': 4137.58447265625}
 80%|█████████████████████████████████████▌         | 16/20 [13:06<03:19, 49.85s/it]
  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████▌                        | 1/2 [00:03<00:03,  3.37s/it]
100%|█████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.78s/it]
Creating first level with 2 topics. Dictionary: artm.Dictionary(name=51ca6d9b-c2ec-4475-b5f2-cc8f6f147d1d, num_entries=19537).
Copying phi for the first level. Phi shape: (19537, 2). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           )
Creating second level with 20 topics
Copying phi for the second level. Phi shape: (19537, 20). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           names=['modality', 'token'])
!!! Bank Phi: [[8.24879123e-11 0.00000000e+00]
 [6.91189372e-09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.20617991e-09]].
!!! Bank model Phi: [[1.7454794e-09 3.3315759e-09]
 [1.1203075e-08 7.0101908e-10]
 [2.0083954e-10 4.7927644e-09]
 ...
 [4.6382183e-09 5.3519278e-09]
 [1.6459714e-11 5.9757088e-09]
 [3.6669880e-09 2.5503558e-08]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[8.24879123e-11 0.00000000e+00]
 [6.91189372e-09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.20617991e-09]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 8.3503783e-06]
 [4.4969144e-09 0.0000000e+00 8.3502327e-06]
 [0.0000000e+00 0.0000000e+00 8.3503783e-06]
 ...
 [0.0000000e+00 0.0000000e+00 1.0916711e-05]
 [0.0000000e+00 0.0000000e+00 8.8636452e-06]
 [0.0000000e+00 0.0000000e+00 1.9642241e-05]].
Bank scores: {'perplexity_score': 23124.765625, 'coherence_20': 1.108715281159298, 'diversity_euclidean': 0.06128161394476198, 'diversity_jensenshannon': 0.604927312801207, 'diversity_hellinger': 0.7027380289911624, 'diversity_cosine': 0.8045688381391035, 'perplexity': 23124.765625, 'ppl_fair': 23124.765625, 'ppl_cheatty': 4137.58447265625}
 85%|███████████████████████████████████████▉       | 17/20 [13:55<02:28, 49.65s/it]
  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████▌                        | 1/2 [00:03<00:03,  3.38s/it]
100%|█████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.78s/it]
Creating first level with 2 topics. Dictionary: artm.Dictionary(name=51ca6d9b-c2ec-4475-b5f2-cc8f6f147d1d, num_entries=19537).
Copying phi for the first level. Phi shape: (19537, 2). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           )
Creating second level with 20 topics
Copying phi for the second level. Phi shape: (19537, 20). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           names=['modality', 'token'])
!!! Bank Phi: [[8.24879123e-11 0.00000000e+00]
 [6.91189372e-09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.20617991e-09]].
!!! Bank model Phi: [[1.7454793e-09 3.3315759e-09]
 [1.1203075e-08 7.0101908e-10]
 [2.0083950e-10 4.7927644e-09]
 ...
 [4.6382183e-09 5.3519282e-09]
 [1.6459717e-11 5.9757088e-09]
 [3.6669876e-09 2.5503558e-08]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[8.24879123e-11 0.00000000e+00]
 [6.91189372e-09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.20617991e-09]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 8.3503792e-06]
 [4.4969144e-09 0.0000000e+00 8.3502337e-06]
 [0.0000000e+00 0.0000000e+00 8.3503792e-06]
 ...
 [0.0000000e+00 0.0000000e+00 1.0916710e-05]
 [0.0000000e+00 0.0000000e+00 8.8636452e-06]
 [0.0000000e+00 0.0000000e+00 1.9642241e-05]].
Bank scores: {'perplexity_score': 23124.765625, 'coherence_20': 1.108715281159298, 'diversity_euclidean': 0.06128161394476196, 'diversity_jensenshannon': 0.6049273128023781, 'diversity_hellinger': 0.7027380289918433, 'diversity_cosine': 0.8045688381391177, 'perplexity': 23124.765625, 'ppl_fair': 23124.765625, 'ppl_cheatty': 4137.58447265625}
 90%|██████████████████████████████████████████▎    | 18/20 [14:46<01:39, 49.94s/it]
  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████▌                        | 1/2 [00:03<00:03,  3.42s/it]
100%|█████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.80s/it]
Creating first level with 2 topics. Dictionary: artm.Dictionary(name=51ca6d9b-c2ec-4475-b5f2-cc8f6f147d1d, num_entries=19537).
Copying phi for the first level. Phi shape: (19537, 2). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           )
Creating second level with 20 topics
Copying phi for the second level. Phi shape: (19537, 20). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           names=['modality', 'token'])
!!! Bank Phi: [[8.24879123e-11 0.00000000e+00]
 [6.91189372e-09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.20617991e-09]].
!!! Bank model Phi: [[1.7454793e-09 3.3315759e-09]
 [1.1203075e-08 7.0101908e-10]
 [2.0083948e-10 4.7927644e-09]
 ...
 [4.6382187e-09 5.3519278e-09]
 [1.6459714e-11 5.9757088e-09]
 [3.6669872e-09 2.5503558e-08]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[8.24879123e-11 0.00000000e+00]
 [6.91189372e-09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.20617991e-09]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 8.3503792e-06]
 [4.4969144e-09 0.0000000e+00 8.3502337e-06]
 [0.0000000e+00 0.0000000e+00 8.3503792e-06]
 ...
 [0.0000000e+00 0.0000000e+00 1.0916711e-05]
 [0.0000000e+00 0.0000000e+00 8.8636452e-06]
 [0.0000000e+00 0.0000000e+00 1.9642241e-05]].
Bank scores: {'perplexity_score': 23124.765625, 'coherence_20': 1.108715281159298, 'diversity_euclidean': 0.06128161394476192, 'diversity_jensenshannon': 0.6049273128024786, 'diversity_hellinger': 0.7027380289923382, 'diversity_cosine': 0.804568838139117, 'perplexity': 23124.765625, 'ppl_fair': 23124.765625, 'ppl_cheatty': 4137.58447265625}
 95%|████████████████████████████████████████████▋  | 19/20 [15:36<00:49, 49.89s/it]
  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████▌                        | 1/2 [00:03<00:03,  3.41s/it]
100%|█████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.80s/it]
Creating first level with 2 topics. Dictionary: artm.Dictionary(name=51ca6d9b-c2ec-4475-b5f2-cc8f6f147d1d, num_entries=19537).
Copying phi for the first level. Phi shape: (19537, 2). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           )
Creating second level with 20 topics
Copying phi for the second level. Phi shape: (19537, 20). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           names=['modality', 'token'])
!!! Bank Phi: [[8.24879123e-11 0.00000000e+00]
 [6.91189372e-09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.20617991e-09]].
!!! Bank model Phi: [[1.7454793e-09 3.3315759e-09]
 [1.1203075e-08 7.0101908e-10]
 [2.0083948e-10 4.7927644e-09]
 ...
 [4.6382178e-09 5.3519282e-09]
 [1.6459714e-11 5.9757088e-09]
 [3.6669872e-09 2.5503558e-08]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[8.24879123e-11 0.00000000e+00]
 [6.91189372e-09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.20617991e-09]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 8.3503792e-06]
 [4.4969144e-09 0.0000000e+00 8.3502337e-06]
 [0.0000000e+00 0.0000000e+00 8.3503792e-06]
 ...
 [0.0000000e+00 0.0000000e+00 1.0916710e-05]
 [0.0000000e+00 0.0000000e+00 8.8636452e-06]
 [0.0000000e+00 0.0000000e+00 1.9642241e-05]].
Bank scores: {'perplexity_score': 23124.765625, 'coherence_20': 1.108715281159298, 'diversity_euclidean': 0.061281613944762, 'diversity_jensenshannon': 0.6049273128024573, 'diversity_hellinger': 0.7027380289922203, 'diversity_cosine': 0.8045688381391178, 'perplexity': 23124.765625, 'ppl_fair': 23124.765625, 'ppl_cheatty': 4137.58447265625}
100%|███████████████████████████████████████████████| 20/20 [16:25<00:00, 49.26s/it]
CPU times: user 28min 27s, sys: 38.7 s, total: 29min 6s
Wall time: 16min 25s

In [61]:
len(optimizer._documents)

100

What topics we have in bank

In [59]:
optimizer._topic_bank.view_topics().head()

                         topic_0  topic_1
@word дублирование  8.248791e-11      0.0
      проучиться    6.911894e-09      0.0
      гимнастика    0.000000e+00      0.0
      софист        0.000000e+00      0.0
      парижанин     0.000000e+00      0.0

In [50]:
bank_topics = optimizer._topic_bank.view_topics()

In [51]:
bank_topics.shape

(19186, 8)

In [52]:
bank_topics.head()

                     topic_0   topic_1   topic_2       topic_3       topic_4  \
@word инвалидность  0.000005  0.000000  0.000000  2.189531e-14  2.561799e-06
      мазка         0.000011  0.000024  0.000000  0.000000e+00  1.806412e-08
      professor     0.000000  0.000015  0.000020  6.220338e-14  0.000000e+00
      умно          0.000000  0.000000  0.000011  2.613295e-16  0.000000e+00
      игил          0.000000  0.000000  0.000000  0.000000e+00  0.000000e+00

                         topic_5       topic_6       topic_7
@word инвалидность  1.603085e-08  0.000000e+00  3.835127e-11
      мазка         0.000000e+00  0.000000e+00  0.000000e+00
      professor     0.000000e+00  1.418952e-07  0.000000e+00
      умно          0.000000e+00  0.000000e+00  0.000000e+00
      игил          7.317492e-13  1.239376e-13  0.000000e+00

In [53]:
bank_topics['topic_7'].sort_values(ascending=False)[:20]

@word  женщина         0.015624
       мужчина         0.009646
       животное        0.007323
       группа          0.006627
       вид             0.006488
       самец           0.006145
       самка           0.005499
       поведение       0.004960
       большой         0.004550
       сон             0.004252
       эволюция        0.004244
       признак         0.003649
       обезьяна        0.003567
       жить            0.003537
       ген             0.003508
       ребёнок         0.003389
       шимпанзе        0.003304
       некоторый       0.003303
       неандерталец    0.003157
       раса            0.003151
Name: topic_7, dtype: float64

And topic scores

In [54]:
optimizer._topic_bank.view_topic_scores()

,topic_0,topic_1,topic_2,topic_3,topic_4,topic_5,topic_6,topic_7
kernel_size,2856.000000,2425.000000,2598.000000,3092.000000,3122.000000,3179.000000,3089.000000,3010.000000
coherence_20,1.181293,0.940944,0.927175,0.858446,0.960241,0.942290,1.144227,0.891899
distance_to_nearest,0.790259,0.661715,0.709441,0.793903,0.678832,0.795731,0.782820,0.770218

All models are also saved (topics as $\Phi$ matrices and topic score values)

In [55]:
! ls $optimizer._topic_bank._path

model_0__phi.bin	    model_19__topic_scores.bin
model_0__topic_scores.bin   model_1__phi.bin
model_10__phi.bin	    model_1__topic_scores.bin
model_10__topic_scores.bin  model_2__phi.bin
model_11__phi.bin	    model_2__topic_scores.bin
model_11__topic_scores.bin  model_3__phi.bin
model_12__phi.bin	    model_3__topic_scores.bin
model_12__topic_scores.bin  model_4__phi.bin
model_13__phi.bin	    model_4__topic_scores.bin
model_13__topic_scores.bin  model_5__phi.bin
model_14__phi.bin	    model_5__topic_scores.bin
model_14__topic_scores.bin  model_6__phi.bin
model_15__phi.bin	    model_6__topic_scores.bin
model_15__topic_scores.bin  model_7__phi.bin
model_16__phi.bin	    model_7__topic_scores.bin
model_16__topic_scores.bin  model_8__phi.bin
model_17__phi.bin	    model_8__topic_scores.bin
model_17__topic_scores.bin  model_9__phi.bin
model_18__phi.bin	    model_9__topic_scores.bin
model_18__topic_scores.bin  topics.bin
model_19__phi.bin	    topic_scores.bin

In [56]:
optimizer._result.keys()

dict_keys(['optimum', 'optimum_std', 'bank_scores', 'bank_topic_scores', 'model_scores', 'model_topic_scores', 'num_bank_topics', 'num_model_topics'])

In [57]:
optimizer._result['num_bank_topics']

[2, 3, 4, 4, 4, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 8, 8, 8]

In [58]:
len(optimizer._result['bank_topic_scores'])

20

In [59]:
optimizer._result

{'optimum': 8,
 'optimum_std': 5.0,
 'bank_scores': [{'perplexity_score': 27600.54296875,
   'coherence_20': 1.1177666958123678,
   'diversity_euclidean': 0.04971374671297815,
   'diversity_jensenshannon': 0.5967539527734701,
   'diversity_hellinger': 0.6922578888429283,
   'diversity_cosine': 0.746649317119927,
   'perplexity': 27600.54296875,
   'ppl_fair': 27600.54296875,
   'ppl_cheatty': 4970.97119140625},
  {'perplexity_score': 12274.9267578125,
   'coherence_20': 1.0511303118773,
   'diversity_euclidean': 0.045677036265274085,
   'diversity_jensenshannon': 0.6265346154678154,
   'diversity_hellinger': 0.7277956636084046,
   'diversity_cosine': 0.763120532644456,
   'perplexity': 12274.9267578125,
   'ppl_fair': 12274.9267578125,
   'ppl_cheatty': 4744.744140625},
  {'perplexity_score': 10446.2529296875,
   'coherence_20': 0.9918173215187528,
   'diversity_euclidean': 0.046234306391336584,
   'diversity_jensenshannon': 0.6043805692629273,
   'diversity_hellinger': 0.699363325018506,
   'diversity_cosine': 0.7323395858081453,
   'perplexity': 10446.2529296875,
   'ppl_fair': 10446.2529296875,
   'ppl_cheatty': 4532.6171875},
  {'perplexity_score': 10446.2529296875,
   'coherence_20': 0.9918173215187528,
   'diversity_euclidean': 0.046234306391336584,
   'diversity_jensenshannon': 0.6043805692629427,
   'diversity_hellinger': 0.6993633250185617,
   'diversity_cosine': 0.7323395858081456,
   'perplexity': 10446.2529296875,
   'ppl_fair': 10446.2529296875,
   'ppl_cheatty': 4532.6171875},
  {'perplexity_score': 10446.2529296875,
   'coherence_20': 0.9918173215187528,
   'diversity_euclidean': 0.046234306390682045,
   'diversity_jensenshannon': 0.6043805692532885,
   'diversity_hellinger': 0.6993633250185184,
   'diversity_cosine': 0.7323395857697993,
   'perplexity': 10446.2529296875,
   'ppl_fair': 10446.2529296875,
   'ppl_cheatty': 4532.6171875},
  {'perplexity_score': 6843.10986328125,
   'coherence_20': 0.9511743164058972,
   'diversity_euclidean': 0.04769058422596907,
   'diversity_jensenshannon': 0.6106950551408163,
   'diversity_hellinger': 0.7048924370950513,
   'diversity_cosine': 0.7582787657483796,
   'perplexity': 6843.10986328125,
   'ppl_fair': 6843.10986328125,
   'ppl_cheatty': 4320.27685546875},
  {'perplexity_score': 6843.10986328125,
   'coherence_20': 0.9511743164058972,
   'diversity_euclidean': 0.047690584225969196,
   'diversity_jensenshannon': 0.6106950551408777,
   'diversity_hellinger': 0.704892437095326,
   'diversity_cosine': 0.7582787657483806,
   'perplexity': 6843.10986328125,
   'ppl_fair': 6843.10986328125,
   'ppl_cheatty': 4320.27685546875},
  {'perplexity_score': 8327.701171875,
   'coherence_20': 0.9582381512773772,
   'diversity_euclidean': 0.049061139220402825,
   'diversity_jensenshannon': 0.5999070144726664,
   'diversity_hellinger': 0.6909743050061313,
   'diversity_cosine': 0.746515439526742,
   'perplexity': 8327.701171875,
   'ppl_fair': 8327.701171875,
   'ppl_cheatty': 4438.490234375},
  {'perplexity_score': 8327.701171875,
   'coherence_20': 0.9582381512773772,
   'diversity_euclidean': 0.0490611392204029,
   'diversity_jensenshannon': 0.5999070144727574,
   'diversity_hellinger': 0.6909743050061739,
   'diversity_cosine': 0.7465154395267445,
   'perplexity': 8327.701171875,
   'ppl_fair': 8327.701171875,
   'ppl_cheatty': 4438.490234375},
  {'perplexity_score': 8327.701171875,
   'coherence_20': 0.9582381512773772,
   'diversity_euclidean': 0.04906113922040289,
   'diversity_jensenshannon': 0.5999070144727433,
   'diversity_hellinger': 0.6909743050062099,
   'diversity_cosine': 0.746515439526742,
   'perplexity': 8327.701171875,
   'ppl_fair': 8327.701171875,
   'ppl_cheatty': 4438.490234375},
  {'perplexity_score': 8327.701171875,
   'coherence_20': 0.9582381512773772,
   'diversity_euclidean': 0.0490611392204029,
   'diversity_jensenshannon': 0.5999070144727477,
   'diversity_hellinger': 0.6909743050061758,
   'diversity_cosine': 0.7465154395267445,
   'perplexity': 8327.701171875,
   'ppl_fair': 8327.701171875,
   'ppl_cheatty': 4438.490234375},
  {'perplexity_score': 8327.701171875,
   'coherence_20': 0.9582381512773772,
   'diversity_euclidean': 0.04906113922040282,
   'diversity_jensenshannon': 0.5999070144727668,
   'diversity_hellinger': 0.6909743050059738,
   'diversity_cosine': 0.7465154395267476,
   'perplexity': 8327.701171875,
   'ppl_fair': 8327.701171875,
   'ppl_cheatty': 4438.490234375},
  {'perplexity_score': 6708.66259765625,
   'coherence_20': 0.9559598111518087,
   'diversity_euclidean': 0.04799023299603226,
   'diversity_jensenshannon': 0.6021340281353051,
   'diversity_hellinger': 0.693280529776386,
   'diversity_cosine': 0.7505952563472144,
   'perplexity': 6708.66259765625,
   'ppl_fair': 6708.66259765625,
   'ppl_cheatty': 4295.6904296875},
  {'perplexity_score': 6708.66259765625,
   'coherence_20': 0.9559598111518087,
   'diversity_euclidean': 0.04799023299603226,
   'diversity_jensenshannon': 0.6021340281353107,
   'diversity_hellinger': 0.6932805297764073,
   'diversity_cosine': 0.7505952563472144,
   'perplexity': 6708.66259765625,
   'ppl_fair': 6708.66259765625,
   'ppl_cheatty': 4295.6904296875},
  {'perplexity_score': 6708.66259765625,
   'coherence_20': 0.9559598111518087,
   'diversity_euclidean': 0.04799023299603226,
   'diversity_jensenshannon': 0.6021340281353104,
   'diversity_hellinger': 0.6932805297764117,
   'diversity_cosine': 0.7505952563472144,
   'perplexity': 6708.66259765625,
   'ppl_fair': 6708.66259765625,
   'ppl_cheatty': 4295.6904296875},
  {'perplexity_score': 6708.66259765625,
   'coherence_20': 0.9559598111518087,
   'diversity_euclidean': 0.04799023299601176,
   'diversity_jensenshannon': 0.602134028134023,
   'diversity_hellinger': 0.6932805297739685,
   'diversity_cosine': 0.7505952563464715,
   'perplexity': 6708.66259765625,
   'ppl_fair': 6708.66259765625,
   'ppl_cheatty': 4295.6904296875},
  {'perplexity_score': 6798.5283203125,
   'coherence_20': 0.9935164476710492,
   'diversity_euclidean': 0.04762086947516285,
   'diversity_jensenshannon': 0.6040854257925821,
   'diversity_hellinger': 0.695392689733443,
   'diversity_cosine': 0.745615640340426,
   'perplexity': 6798.5283203125,
   'ppl_fair': 6798.5283203125,
   'ppl_cheatty': 4331.3974609375},
  {'perplexity_score': 6107.216796875,
   'coherence_20': 0.98081432765508,
   'diversity_euclidean': 0.0472204286629127,
   'diversity_jensenshannon': 0.6019874723800872,
   'diversity_hellinger': 0.6929206053599063,
   'diversity_cosine': 0.7453124228974204,
   'perplexity': 6107.216796875,
   'ppl_fair': 6107.216796875,
   'ppl_cheatty': 4218.52294921875},
  {'perplexity_score': 6107.216796875,
   'coherence_20': 0.98081432765508,
   'diversity_euclidean': 0.0472204286629127,
   'diversity_jensenshannon': 0.6019874723801105,
   'diversity_hellinger': 0.6929206053599518,
   'diversity_cosine': 0.7453124228974204,
   'perplexity': 6107.216796875,
   'ppl_fair': 6107.216796875,
   'ppl_cheatty': 4218.52294921875},
  {'perplexity_score': 6107.216796875,
   'coherence_20': 0.98081432765508,
   'diversity_euclidean': 0.04722042866291265,
   'diversity_jensenshannon': 0.6019874723801198,
   'diversity_hellinger': 0.6929206053597949,
   'diversity_cosine': 0.7453124228974252,
   'perplexity': 6107.216796875,
   'ppl_fair': 6107.216796875,
   'ppl_cheatty': 4218.52294921875}],
 'bank_topic_scores': [[{'kernel_size': 2540,
    'coherence_20': 1.054240465084224,
    'distance_to_nearest': 0.0},
   {'kernel_size': 2856,
    'coherence_20': 1.1812929265405114,
    'distance_to_nearest': 0.79025919077267}],
  [{'kernel_size': 2540,
    'coherence_20': 1.054240465084224,
    'distance_to_nearest': 0.0},
   {'kernel_size': 2856,
    'coherence_20': 1.1812929265405114,
    'distance_to_nearest': 0.79025919077267},
   {'kernel_size': 3455,
    'coherence_20': 0.9178575440071646,
    'distance_to_nearest': 0.8382437670066345}],
  [{'kernel_size': 2856,
    'coherence_20': 1.1812929265405114,
    'distance_to_nearest': 0.79025919077267},
   {'kernel_size': 3455,
    'coherence_20': 0.9178575440071646,
    'distance_to_nearest': 0.8382437670066345},
   {'kernel_size': 2425,
    'coherence_20': 0.9409436630681554,
    'distance_to_nearest': 0.6617147426494687},
   {'kernel_size': 2598,
    'coherence_20': 0.9271751524591798,
    'distance_to_nearest': 0.7094405645172381}],
  [{'kernel_size': 2856,
    'coherence_20': 1.1812929265405114,
    'distance_to_nearest': 0.79025919077267},
   {'kernel_size': 3455,
    'coherence_20': 0.9178575440071646,
    'distance_to_nearest': 0.8382437670066345},
   {'kernel_size': 2425,
    'coherence_20': 0.9409436630681554,
    'distance_to_nearest': 0.6617147426494687},
   {'kernel_size': 2598,
    'coherence_20': 0.9271751524591798,
    'distance_to_nearest': 0.7094405645172381}],
  [{'kernel_size': 2856,
    'coherence_20': 1.1812929265405114,
    'distance_to_nearest': 0.79025919077267},
   {'kernel_size': 3455,
    'coherence_20': 0.9178575440071646,
    'distance_to_nearest': 0.8382437670066345},
   {'kernel_size': 2425,
    'coherence_20': 0.9409436630681554,
    'distance_to_nearest': 0.6617147426494687},
   {'kernel_size': 2598,
    'coherence_20': 0.9271751524591798,
    'distance_to_nearest': 0.7094405645172381}],
  [{'kernel_size': 2856,
    'coherence_20': 1.1812929265405114,
    'distance_to_nearest': 0.79025919077267},
   {'kernel_size': 3455,
    'coherence_20': 0.9178575440071646,
    'distance_to_nearest': 0.8382437670066345},
   {'kernel_size': 2425,
    'coherence_20': 0.9409436630681554,
    'distance_to_nearest': 0.6617147426494687},
   {'kernel_size': 2598,
    'coherence_20': 0.9271751524591798,
    'distance_to_nearest': 0.7094405645172381},
   {'kernel_size': 3172,
    'coherence_20': 0.8813308166660884,
    'distance_to_nearest': 0.7961549458942572},
   {'kernel_size': 3092,
    'coherence_20': 0.8584457956942841,
    'distance_to_nearest': 0.7939027411916018}],
  [{'kernel_size': 2856,
    'coherence_20': 1.1812929265405114,
    'distance_to_nearest': 0.79025919077267},
   {'kernel_size': 3455,
    'coherence_20': 0.9178575440071646,
    'distance_to_nearest': 0.8382437670066345},
   {'kernel_size': 2425,
    'coherence_20': 0.9409436630681554,
    'distance_to_nearest': 0.6617147426494687},
   {'kernel_size': 2598,
    'coherence_20': 0.9271751524591798,
    'distance_to_nearest': 0.7094405645172381},
   {'kernel_size': 3172,
    'coherence_20': 0.8813308166660884,
    'distance_to_nearest': 0.7961549458942572},
   {'kernel_size': 3092,
    'coherence_20': 0.8584457956942841,
    'distance_to_nearest': 0.7939027411916018}],
  [{'kernel_size': 2856,
    'coherence_20': 1.1812929265405114,
    'distance_to_nearest': 0.79025919077267},
   {'kernel_size': 2425,
    'coherence_20': 0.9409436630681554,
    'distance_to_nearest': 0.6617147426494687},
   {'kernel_size': 2598,
    'coherence_20': 0.9271751524591798,
    'distance_to_nearest': 0.7094405645172381},
   {'kernel_size': 3172,
    'coherence_20': 0.8813308166660884,
    'distance_to_nearest': 0.7961549458942572},
   {'kernel_size': 3092,
    'coherence_20': 0.8584457956942841,
    'distance_to_nearest': 0.7939027411916018},
   {'kernel_size': 3122,
    'coherence_20': 0.9602405532360441,
    'distance_to_nearest': 0.6788318778107343}],
  [{'kernel_size': 2856,
    'coherence_20': 1.1812929265405114,
    'distance_to_nearest': 0.79025919077267},
   {'kernel_size': 2425,
    'coherence_20': 0.9409436630681554,
    'distance_to_nearest': 0.6617147426494687},
   {'kernel_size': 2598,
    'coherence_20': 0.9271751524591798,
    'distance_to_nearest': 0.7094405645172381},
   {'kernel_size': 3172,
    'coherence_20': 0.8813308166660884,
    'distance_to_nearest': 0.7961549458942572},
   {'kernel_size': 3092,
    'coherence_20': 0.8584457956942841,
    'distance_to_nearest': 0.7939027411916018},
   {'kernel_size': 3122,
    'coherence_20': 0.9602405532360441,
    'distance_to_nearest': 0.6788318778107343}],
  [{'kernel_size': 2856,
    'coherence_20': 1.1812929265405114,
    'distance_to_nearest': 0.79025919077267},
   {'kernel_size': 2425,
    'coherence_20': 0.9409436630681554,
    'distance_to_nearest': 0.6617147426494687},
   {'kernel_size': 2598,
    'coherence_20': 0.9271751524591798,
    'distance_to_nearest': 0.7094405645172381},
   {'kernel_size': 3172,
    'coherence_20': 0.8813308166660884,
    'distance_to_nearest': 0.7961549458942572},
   {'kernel_size': 3092,
    'coherence_20': 0.8584457956942841,
    'distance_to_nearest': 0.7939027411916018},
   {'kernel_size': 3122,
    'coherence_20': 0.9602405532360441,
    'distance_to_nearest': 0.6788318778107343}],
  [{'kernel_size': 2856,
    'coherence_20': 1.1812929265405114,
    'distance_to_nearest': 0.79025919077267},
   {'kernel_size': 2425,
    'coherence_20': 0.9409436630681554,
    'distance_to_nearest': 0.6617147426494687},
   {'kernel_size': 2598,
    'coherence_20': 0.9271751524591798,
    'distance_to_nearest': 0.7094405645172381},
   {'kernel_size': 3172,
    'coherence_20': 0.8813308166660884,
    'distance_to_nearest': 0.7961549458942572},
   {'kernel_size': 3092,
    'coherence_20': 0.8584457956942841,
    'distance_to_nearest': 0.7939027411916018},
   {'kernel_size': 3122,
    'coherence_20': 0.9602405532360441,
    'distance_to_nearest': 0.6788318778107343}],
  [{'kernel_size': 2856,
    'coherence_20': 1.1812929265405114,
    'distance_to_nearest': 0.79025919077267},
   {'kernel_size': 2425,
    'coherence_20': 0.9409436630681554,
    'distance_to_nearest': 0.6617147426494687},
   {'kernel_size': 2598,
    'coherence_20': 0.9271751524591798,
    'distance_to_nearest': 0.7094405645172381},
   {'kernel_size': 3172,
    'coherence_20': 0.8813308166660884,
    'distance_to_nearest': 0.7961549458942572},
   {'kernel_size': 3092,
    'coherence_20': 0.8584457956942841,
    'distance_to_nearest': 0.7939027411916018},
   {'kernel_size': 3122,
    'coherence_20': 0.9602405532360441,
    'distance_to_nearest': 0.6788318778107343}],
  [{'kernel_size': 2856,
    'coherence_20': 1.1812929265405114,
    'distance_to_nearest': 0.79025919077267},
   {'kernel_size': 2425,
    'coherence_20': 0.9409436630681554,
    'distance_to_nearest': 0.6617147426494687},
   {'kernel_size': 2598,
    'coherence_20': 0.9271751524591798,
    'distance_to_nearest': 0.7094405645172381},
   {'kernel_size': 3172,
    'coherence_20': 0.8813308166660884,
    'distance_to_nearest': 0.7961549458942572},
   {'kernel_size': 3092,
    'coherence_20': 0.8584457956942841,
    'distance_to_nearest': 0.7939027411916018},
   {'kernel_size': 3122,
    'coherence_20': 0.9602405532360441,
    'distance_to_nearest': 0.6788318778107343},
   {'kernel_size': 3179,
    'coherence_20': 0.9422897703983983,
    'distance_to_nearest': 0.7957309116542446}],
  [{'kernel_size': 2856,
    'coherence_20': 1.1812929265405114,
    'distance_to_nearest': 0.79025919077267},
   {'kernel_size': 2425,
    'coherence_20': 0.9409436630681554,
    'distance_to_nearest': 0.6617147426494687},
   {'kernel_size': 2598,
    'coherence_20': 0.9271751524591798,
    'distance_to_nearest': 0.7094405645172381},
   {'kernel_size': 3172,
    'coherence_20': 0.8813308166660884,
    'distance_to_nearest': 0.7961549458942572},
   {'kernel_size': 3092,
    'coherence_20': 0.8584457956942841,
    'distance_to_nearest': 0.7939027411916018},
   {'kernel_size': 3122,
    'coherence_20': 0.9602405532360441,
    'distance_to_nearest': 0.6788318778107343},
   {'kernel_size': 3179,
    'coherence_20': 0.9422897703983983,
    'distance_to_nearest': 0.7957309116542446}],
  [{'kernel_size': 2856,
    'coherence_20': 1.1812929265405114,
    'distance_to_nearest': 0.79025919077267},
   {'kernel_size': 2425,
    'coherence_20': 0.9409436630681554,
    'distance_to_nearest': 0.6617147426494687},
   {'kernel_size': 2598,
    'coherence_20': 0.9271751524591798,
    'distance_to_nearest': 0.7094405645172381},
   {'kernel_size': 3172,
    'coherence_20': 0.8813308166660884,
    'distance_to_nearest': 0.7961549458942572},
   {'kernel_size': 3092,
    'coherence_20': 0.8584457956942841,
    'distance_to_nearest': 0.7939027411916018},
   {'kernel_size': 3122,
    'coherence_20': 0.9602405532360441,
    'distance_to_nearest': 0.6788318778107343},
   {'kernel_size': 3179,
    'coherence_20': 0.9422897703983983,
    'distance_to_nearest': 0.7957309116542446}],
  [{'kernel_size': 2856,
    'coherence_20': 1.1812929265405114,
    'distance_to_nearest': 0.79025919077267},
   {'kernel_size': 2425,
    'coherence_20': 0.9409436630681554,
    'distance_to_nearest': 0.6617147426494687},
   {'kernel_size': 2598,
    'coherence_20': 0.9271751524591798,
    'distance_to_nearest': 0.7094405645172381},
   {'kernel_size': 3172,
    'coherence_20': 0.8813308166660884,
    'distance_to_nearest': 0.7961549458942572},
   {'kernel_size': 3092,
    'coherence_20': 0.8584457956942841,
    'distance_to_nearest': 0.7939027411916018},
   {'kernel_size': 3122,
    'coherence_20': 0.9602405532360441,
    'distance_to_nearest': 0.6788318778107343},
   {'kernel_size': 3179,
    'coherence_20': 0.9422897703983983,
    'distance_to_nearest': 0.7957309116542446}],
  [{'kernel_size': 2856,
    'coherence_20': 1.1812929265405114,
    'distance_to_nearest': 0.79025919077267},
   {'kernel_size': 2425,
    'coherence_20': 0.9409436630681554,
    'distance_to_nearest': 0.6617147426494687},
   {'kernel_size': 2598,
    'coherence_20': 0.9271751524591798,
    'distance_to_nearest': 0.7094405645172381},
   {'kernel_size': 3092,
    'coherence_20': 0.8584457956942841,
    'distance_to_nearest': 0.7939027411916018},
   {'kernel_size': 3122,
    'coherence_20': 0.9602405532360441,
    'distance_to_nearest': 0.6788318778107343},
   {'kernel_size': 3179,
    'coherence_20': 0.9422897703983983,
    'distance_to_nearest': 0.7957309116542446},
   {'kernel_size': 3089,
    'coherence_20': 1.1442272723007718,
    'distance_to_nearest': 0.7828204631729808}],
  [{'kernel_size': 2856,
    'coherence_20': 1.1812929265405114,
    'distance_to_nearest': 0.79025919077267},
   {'kernel_size': 2425,
    'coherence_20': 0.9409436630681554,
    'distance_to_nearest': 0.6617147426494687},
   {'kernel_size': 2598,
    'coherence_20': 0.9271751524591798,
    'distance_to_nearest': 0.7094405645172381},
   {'kernel_size': 3092,
    'coherence_20': 0.8584457956942841,
    'distance_to_nearest': 0.7939027411916018},
   {'kernel_size': 3122,
    'coherence_20': 0.9602405532360441,
    'distance_to_nearest': 0.6788318778107343},
   {'kernel_size': 3179,
    'coherence_20': 0.9422897703983983,
    'distance_to_nearest': 0.7957309116542446},
   {'kernel_size': 3089,
    'coherence_20': 1.1442272723007718,
    'distance_to_nearest': 0.7828204631729808},
   {'kernel_size': 3010,
    'coherence_20': 0.8918994875432961,
    'distance_to_nearest': 0.7702181041170648}],
  [{'kernel_size': 2856,
    'coherence_20': 1.1812929265405114,
    'distance_to_nearest': 0.79025919077267},
   {'kernel_size': 2425,
    'coherence_20': 0.9409436630681554,
    'distance_to_nearest': 0.6617147426494687},
   {'kernel_size': 2598,
    'coherence_20': 0.9271751524591798,
    'distance_to_nearest': 0.7094405645172381},
   {'kernel_size': 3092,
    'coherence_20': 0.8584457956942841,
    'distance_to_nearest': 0.7939027411916018},
   {'kernel_size': 3122,
    'coherence_20': 0.9602405532360441,
    'distance_to_nearest': 0.6788318778107343},
   {'kernel_size': 3179,
    'coherence_20': 0.9422897703983983,
    'distance_to_nearest': 0.7957309116542446},
   {'kernel_size': 3089,
    'coherence_20': 1.1442272723007718,
    'distance_to_nearest': 0.7828204631729808},
   {'kernel_size': 3010,
    'coherence_20': 0.8918994875432961,
    'distance_to_nearest': 0.7702181041170648}],
  [{'kernel_size': 2856,
    'coherence_20': 1.1812929265405114,
    'distance_to_nearest': 0.79025919077267},
   {'kernel_size': 2425,
    'coherence_20': 0.9409436630681554,
    'distance_to_nearest': 0.6617147426494687},

In [60]:
optimizer._result['bank_topic_scores']

[[{'kernel_size': 2540,
   'coherence_20': 1.054240465084224,
   'distance_to_nearest': 0.0},
  {'kernel_size': 2856,
   'coherence_20': 1.1812929265405114,
   'distance_to_nearest': 0.79025919077267}],
 [{'kernel_size': 2540,
   'coherence_20': 1.054240465084224,
   'distance_to_nearest': 0.0},
  {'kernel_size': 2856,
   'coherence_20': 1.1812929265405114,
   'distance_to_nearest': 0.79025919077267},
  {'kernel_size': 3455,
   'coherence_20': 0.9178575440071646,
   'distance_to_nearest': 0.8382437670066345}],
 [{'kernel_size': 2856,
   'coherence_20': 1.1812929265405114,
   'distance_to_nearest': 0.79025919077267},
  {'kernel_size': 3455,
   'coherence_20': 0.9178575440071646,
   'distance_to_nearest': 0.8382437670066345},
  {'kernel_size': 2425,
   'coherence_20': 0.9409436630681554,
   'distance_to_nearest': 0.6617147426494687},
  {'kernel_size': 2598,
   'coherence_20': 0.9271751524591798,
   'distance_to_nearest': 0.7094405645172381}],
 [{'kernel_size': 2856,
   'coherence_20': 1.1812929265405114,
   'distance_to_nearest': 0.79025919077267},
  {'kernel_size': 3455,
   'coherence_20': 0.9178575440071646,
   'distance_to_nearest': 0.8382437670066345},
  {'kernel_size': 2425,
   'coherence_20': 0.9409436630681554,
   'distance_to_nearest': 0.6617147426494687},
  {'kernel_size': 2598,
   'coherence_20': 0.9271751524591798,
   'distance_to_nearest': 0.7094405645172381}],
 [{'kernel_size': 2856,
   'coherence_20': 1.1812929265405114,
   'distance_to_nearest': 0.79025919077267},
  {'kernel_size': 3455,
   'coherence_20': 0.9178575440071646,
   'distance_to_nearest': 0.8382437670066345},
  {'kernel_size': 2425,
   'coherence_20': 0.9409436630681554,
   'distance_to_nearest': 0.6617147426494687},
  {'kernel_size': 2598,
   'coherence_20': 0.9271751524591798,
   'distance_to_nearest': 0.7094405645172381}],
 [{'kernel_size': 2856,
   'coherence_20': 1.1812929265405114,
   'distance_to_nearest': 0.79025919077267},
  {'kernel_size': 3455,
   'coherence_20': 0.9178575440071646,
   'distance_to_nearest': 0.8382437670066345},
  {'kernel_size': 2425,
   'coherence_20': 0.9409436630681554,
   'distance_to_nearest': 0.6617147426494687},
  {'kernel_size': 2598,
   'coherence_20': 0.9271751524591798,
   'distance_to_nearest': 0.7094405645172381},
  {'kernel_size': 3172,
   'coherence_20': 0.8813308166660884,
   'distance_to_nearest': 0.7961549458942572},
  {'kernel_size': 3092,
   'coherence_20': 0.8584457956942841,
   'distance_to_nearest': 0.7939027411916018}],
 [{'kernel_size': 2856,
   'coherence_20': 1.1812929265405114,
   'distance_to_nearest': 0.79025919077267},
  {'kernel_size': 3455,
   'coherence_20': 0.9178575440071646,
   'distance_to_nearest': 0.8382437670066345},
  {'kernel_size': 2425,
   'coherence_20': 0.9409436630681554,
   'distance_to_nearest': 0.6617147426494687},
  {'kernel_size': 2598,
   'coherence_20': 0.9271751524591798,
   'distance_to_nearest': 0.7094405645172381},
  {'kernel_size': 3172,
   'coherence_20': 0.8813308166660884,
   'distance_to_nearest': 0.7961549458942572},
  {'kernel_size': 3092,
   'coherence_20': 0.8584457956942841,
   'distance_to_nearest': 0.7939027411916018}],
 [{'kernel_size': 2856,
   'coherence_20': 1.1812929265405114,
   'distance_to_nearest': 0.79025919077267},
  {'kernel_size': 2425,
   'coherence_20': 0.9409436630681554,
   'distance_to_nearest': 0.6617147426494687},
  {'kernel_size': 2598,
   'coherence_20': 0.9271751524591798,
   'distance_to_nearest': 0.7094405645172381},
  {'kernel_size': 3172,
   'coherence_20': 0.8813308166660884,
   'distance_to_nearest': 0.7961549458942572},
  {'kernel_size': 3092,
   'coherence_20': 0.8584457956942841,
   'distance_to_nearest': 0.7939027411916018},
  {'kernel_size': 3122,
   'coherence_20': 0.9602405532360441,
   'distance_to_nearest': 0.6788318778107343}],
 [{'kernel_size': 2856,
   'coherence_20': 1.1812929265405114,
   'distance_to_nearest': 0.79025919077267},
  {'kernel_size': 2425,
   'coherence_20': 0.9409436630681554,
   'distance_to_nearest': 0.6617147426494687},
  {'kernel_size': 2598,
   'coherence_20': 0.9271751524591798,
   'distance_to_nearest': 0.7094405645172381},
  {'kernel_size': 3172,
   'coherence_20': 0.8813308166660884,
   'distance_to_nearest': 0.7961549458942572},
  {'kernel_size': 3092,
   'coherence_20': 0.8584457956942841,
   'distance_to_nearest': 0.7939027411916018},
  {'kernel_size': 3122,
   'coherence_20': 0.9602405532360441,
   'distance_to_nearest': 0.6788318778107343}],
 [{'kernel_size': 2856,
   'coherence_20': 1.1812929265405114,
   'distance_to_nearest': 0.79025919077267},
  {'kernel_size': 2425,
   'coherence_20': 0.9409436630681554,
   'distance_to_nearest': 0.6617147426494687},
  {'kernel_size': 2598,
   'coherence_20': 0.9271751524591798,
   'distance_to_nearest': 0.7094405645172381},
  {'kernel_size': 3172,
   'coherence_20': 0.8813308166660884,
   'distance_to_nearest': 0.7961549458942572},
  {'kernel_size': 3092,
   'coherence_20': 0.8584457956942841,
   'distance_to_nearest': 0.7939027411916018},
  {'kernel_size': 3122,
   'coherence_20': 0.9602405532360441,
   'distance_to_nearest': 0.6788318778107343}],
 [{'kernel_size': 2856,
   'coherence_20': 1.1812929265405114,
   'distance_to_nearest': 0.79025919077267},
  {'kernel_size': 2425,
   'coherence_20': 0.9409436630681554,
   'distance_to_nearest': 0.6617147426494687},
  {'kernel_size': 2598,
   'coherence_20': 0.9271751524591798,
   'distance_to_nearest': 0.7094405645172381},
  {'kernel_size': 3172,
   'coherence_20': 0.8813308166660884,
   'distance_to_nearest': 0.7961549458942572},
  {'kernel_size': 3092,
   'coherence_20': 0.8584457956942841,
   'distance_to_nearest': 0.7939027411916018},
  {'kernel_size': 3122,
   'coherence_20': 0.9602405532360441,
   'distance_to_nearest': 0.6788318778107343}],
 [{'kernel_size': 2856,
   'coherence_20': 1.1812929265405114,
   'distance_to_nearest': 0.79025919077267},
  {'kernel_size': 2425,
   'coherence_20': 0.9409436630681554,
   'distance_to_nearest': 0.6617147426494687},
  {'kernel_size': 2598,
   'coherence_20': 0.9271751524591798,
   'distance_to_nearest': 0.7094405645172381},
  {'kernel_size': 3172,
   'coherence_20': 0.8813308166660884,
   'distance_to_nearest': 0.7961549458942572},
  {'kernel_size': 3092,
   'coherence_20': 0.8584457956942841,
   'distance_to_nearest': 0.7939027411916018},
  {'kernel_size': 3122,
   'coherence_20': 0.9602405532360441,
   'distance_to_nearest': 0.6788318778107343}],
 [{'kernel_size': 2856,
   'coherence_20': 1.1812929265405114,
   'distance_to_nearest': 0.79025919077267},
  {'kernel_size': 2425,
   'coherence_20': 0.9409436630681554,
   'distance_to_nearest': 0.6617147426494687},
  {'kernel_size': 2598,
   'coherence_20': 0.9271751524591798,
   'distance_to_nearest': 0.7094405645172381},
  {'kernel_size': 3172,
   'coherence_20': 0.8813308166660884,
   'distance_to_nearest': 0.7961549458942572},
  {'kernel_size': 3092,
   'coherence_20': 0.8584457956942841,
   'distance_to_nearest': 0.7939027411916018},
  {'kernel_size': 3122,
   'coherence_20': 0.9602405532360441,
   'distance_to_nearest': 0.6788318778107343},
  {'kernel_size': 3179,
   'coherence_20': 0.9422897703983983,
   'distance_to_nearest': 0.7957309116542446}],
 [{'kernel_size': 2856,
   'coherence_20': 1.1812929265405114,
   'distance_to_nearest': 0.79025919077267},
  {'kernel_size': 2425,
   'coherence_20': 0.9409436630681554,
   'distance_to_nearest': 0.6617147426494687},
  {'kernel_size': 2598,
   'coherence_20': 0.9271751524591798,
   'distance_to_nearest': 0.7094405645172381},
  {'kernel_size': 3172,
   'coherence_20': 0.8813308166660884,
   'distance_to_nearest': 0.7961549458942572},
  {'kernel_size': 3092,
   'coherence_20': 0.8584457956942841,
   'distance_to_nearest': 0.7939027411916018},
  {'kernel_size': 3122,
   'coherence_20': 0.9602405532360441,
   'distance_to_nearest': 0.6788318778107343},
  {'kernel_size': 3179,
   'coherence_20': 0.9422897703983983,
   'distance_to_nearest': 0.7957309116542446}],
 [{'kernel_size': 2856,
   'coherence_20': 1.1812929265405114,
   'distance_to_nearest': 0.79025919077267},
  {'kernel_size': 2425,
   'coherence_20': 0.9409436630681554,
   'distance_to_nearest': 0.6617147426494687},
  {'kernel_size': 2598,
   'coherence_20': 0.9271751524591798,
   'distance_to_nearest': 0.7094405645172381},
  {'kernel_size': 3172,
   'coherence_20': 0.8813308166660884,
   'distance_to_nearest': 0.7961549458942572},
  {'kernel_size': 3092,
   'coherence_20': 0.8584457956942841,
   'distance_to_nearest': 0.7939027411916018},
  {'kernel_size': 3122,
   'coherence_20': 0.9602405532360441,
   'distance_to_nearest': 0.6788318778107343},
  {'kernel_size': 3179,
   'coherence_20': 0.9422897703983983,
   'distance_to_nearest': 0.7957309116542446}],
 [{'kernel_size': 2856,
   'coherence_20': 1.1812929265405114,
   'distance_to_nearest': 0.79025919077267},
  {'kernel_size': 2425,
   'coherence_20': 0.9409436630681554,
   'distance_to_nearest': 0.6617147426494687},
  {'kernel_size': 2598,
   'coherence_20': 0.9271751524591798,
   'distance_to_nearest': 0.7094405645172381},
  {'kernel_size': 3172,
   'coherence_20': 0.8813308166660884,
   'distance_to_nearest': 0.7961549458942572},
  {'kernel_size': 3092,
   'coherence_20': 0.8584457956942841,
   'distance_to_nearest': 0.7939027411916018},
  {'kernel_size': 3122,
   'coherence_20': 0.9602405532360441,
   'distance_to_nearest': 0.6788318778107343},
  {'kernel_size': 3179,
   'coherence_20': 0.9422897703983983,
   'distance_to_nearest': 0.7957309116542446}],
 [{'kernel_size': 2856,
   'coherence_20': 1.1812929265405114,
   'distance_to_nearest': 0.79025919077267},
  {'kernel_size': 2425,
   'coherence_20': 0.9409436630681554,
   'distance_to_nearest': 0.6617147426494687},
  {'kernel_size': 2598,
   'coherence_20': 0.9271751524591798,
   'distance_to_nearest': 0.7094405645172381},
  {'kernel_size': 3092,
   'coherence_20': 0.8584457956942841,
   'distance_to_nearest': 0.7939027411916018},
  {'kernel_size': 3122,
   'coherence_20': 0.9602405532360441,
   'distance_to_nearest': 0.6788318778107343},
  {'kernel_size': 3179,
   'coherence_20': 0.9422897703983983,
   'distance_to_nearest': 0.7957309116542446},
  {'kernel_size': 3089,
   'coherence_20': 1.1442272723007718,
   'distance_to_nearest': 0.7828204631729808}],
 [{'kernel_size': 2856,
   'coherence_20': 1.1812929265405114,
   'distance_to_nearest': 0.79025919077267},
  {'kernel_size': 2425,
   'coherence_20': 0.9409436630681554,
   'distance_to_nearest': 0.6617147426494687},
  {'kernel_size': 2598,
   'coherence_20': 0.9271751524591798,
   'distance_to_nearest': 0.7094405645172381},
  {'kernel_size': 3092,
   'coherence_20': 0.8584457956942841,
   'distance_to_nearest': 0.7939027411916018},
  {'kernel_size': 3122,
   'coherence_20': 0.9602405532360441,
   'distance_to_nearest': 0.6788318778107343},
  {'kernel_size': 3179,
   'coherence_20': 0.9422897703983983,
   'distance_to_nearest': 0.7957309116542446},
  {'kernel_size': 3089,
   'coherence_20': 1.1442272723007718,
   'distance_to_nearest': 0.7828204631729808},
  {'kernel_size': 3010,
   'coherence_20': 0.8918994875432961,
   'distance_to_nearest': 0.7702181041170648}],
 [{'kernel_size': 2856,
   'coherence_20': 1.1812929265405114,
   'distance_to_nearest': 0.79025919077267},
  {'kernel_size': 2425,
   'coherence_20': 0.9409436630681554,
   'distance_to_nearest': 0.6617147426494687},
  {'kernel_size': 2598,
   'coherence_20': 0.9271751524591798,
   'distance_to_nearest': 0.7094405645172381},
  {'kernel_size': 3092,
   'coherence_20': 0.8584457956942841,
   'distance_to_nearest': 0.7939027411916018},
  {'kernel_size': 3122,
   'coherence_20': 0.9602405532360441,
   'distance_to_nearest': 0.6788318778107343},
  {'kernel_size': 3179,
   'coherence_20': 0.9422897703983983,
   'distance_to_nearest': 0.7957309116542446},
  {'kernel_size': 3089,
   'coherence_20': 1.1442272723007718,
   'distance_to_nearest': 0.7828204631729808},
  {'kernel_size': 3010,
   'coherence_20': 0.8918994875432961,
   'distance_to_nearest': 0.7702181041170648}],
 [{'kernel_size': 2856,
   'coherence_20': 1.1812929265405114,
   'distance_to_nearest': 0.79025919077267},
  {'kernel_size': 2425,
   'coherence_20': 0.9409436630681554,
   'distance_to_nearest': 0.6617147426494687},
  {'kernel_size': 2598,
   'coherence_20': 0.9271751524591798,
   'distance_to_nearest': 0.7094405645172381},
  {'kernel_size': 3092,
   'coherence_20': 0.8584457956942841,
   'distance_to_nearest': 0.7939027411916018},
  {'kernel_size': 3122,
   'coherence_20': 0.9602405532360441,
   'distance_to_nearest': 0.6788318778107343},
  {'kernel_size': 3179,
   'coherence_20': 0.9422897703983983,
   'distance_to_nearest': 0.7957309116542446},
  {'kernel_size': 3089,
   'coherence_20': 1.1442272723007718,
   'distance_to_nearest': 0.7828204631729808},
  {'kernel_size': 3010,
   'coherence_20': 0.8918994875432961,
   'distance_to_nearest': 0.7702181041170648}]]

In [61]:
optimizer._result['model_scores'][0]

{'perplexity_score': 2983.59326171875,
 'coherence_20': 0.705566582121322,
 'diversity_euclidean': 0.04656994985355387,
 'diversity_jensenshannon': 0.5982341411716676,
 'diversity_hellinger': 0.6850917867989588,
 'diversity_cosine': 0.7077267888360923,
 'perplexity': 2983.59326171875}

In [62]:
sum(s['coherence_20'] for s in optimizer._result['bank_topic_scores'][-1]) / 8

0.9808143276550801

In [63]:
len(optimizer._result['bank_scores'])

20

In [64]:
optimizer._result['bank_scores'][-1]

{'perplexity_score': 6107.216796875,
 'coherence_20': 0.98081432765508,
 'diversity_euclidean': 0.04722042866291265,
 'diversity_jensenshannon': 0.6019874723801198,
 'diversity_hellinger': 0.6929206053597949,
 'diversity_cosine': 0.7453124228974252,
 'perplexity': 6107.216796875,
 'ppl_fair': 6107.216796875,
 'ppl_cheatty': 4218.52294921875}

In [133]:
# Real-fixing bank topics

In [85]:
from topnum.search_methods.topic_bank.one_model_train_funcs import _get_topic_model

In [86]:
model

Model(id=--12h57m59s_22d03m2024y---, parent_id=None, experiment_id=None)

In [115]:
phi = model.get_phi()
phi = phi.iloc[phi.index.get_level_values(0).isin([MAIN_MODALITY])]

word2index = {
    word: index for index, word in enumerate(phi.index)
}

bank_phi = optimizer._get_phi(optimizer._topic_bank.topics, word2index)
bank_model = _get_topic_model(
    optimizer._dataset,
    phi=bank_phi,
    scores=optimizer._all_model_scores,
    num_safe_fit_iterations=1
)

In [126]:
bank_phi['topic_7'].sort_values(ascending=False)

@word  женщина        0.015624
       мужчина        0.009646
       животное       0.007323
       группа         0.006627
       вид            0.006488
                        ...
       косить         0.000000
       отдалять       0.000000
       натянутый      0.000000
       драматичный    0.000000
       аврелий        0.000000
Name: topic_7, Length: 19186, dtype: float64

In [122]:
bank_topics['topic_7'].sort_values(ascending=False)

@word  женщина        0.015624
       мужчина        0.009646
       животное       0.007323
       группа         0.006627
       вид            0.006488
                        ...
       косить         0.000000
       отдалять       0.000000
       натянутый      0.000000
       драматичный    0.000000
       аврелий        0.000000
Name: topic_7, Length: 19186, dtype: float64

In [123]:
bank_model.get_phi()['topic_7'].sort_values(ascending=False)

modality  token
@word     ребёнок        0.008598
          группа         0.006715
          вид            0.006035
          женщина        0.005993
          мозг           0.005540
                           ...
          схватывание    0.000000
          немецк         0.000000
          предвзятый     0.000000
          умник          0.000000
          аврелий        0.000000
Name: topic_7, Length: 19186, dtype: float32

In [125]:
class FastFixPhiRegularizer(BaseRegularizer):
    _VERY_BIG_TAU = 10 ** 9

    def __init__(self, name: str, phi, topic_names: List[str]):
        super().__init__(name, tau=self._VERY_BIG_TAU)

        self._topic_names = topic_names
        self._topic_indices = None
        self._phi = phi

    def grad(self, pwt, nwt):
        # print('Fixing')

        rwt = np.zeros_like(pwt)
        parent_phi = self._phi
        
        rwt[:, self._topic_indices] += parent_phi.values[:, self._topic_indices]

        return self.tau * rwt

    def attach(self, model):
        super().attach(model)
        
        phi = self._model.get_phi()
        self._topic_indices = [
            phi.columns.get_loc(topic_name)
            for topic_name in self._topic_names
        ]

In [127]:
regularizer = FastFixPhiRegularizer(
    name='fix',
    phi=bank_phi,
    topic_names=bank_phi.columns,
)

In [128]:
bank_model._fit(
    optimizer._dataset.get_batch_vectorizer(),
    num_iterations=10,
    custom_regularizers={
        regularizer.name: regularizer,
    }
)

In [129]:
bank_model.get_phi()['topic_7'].sort_values(ascending=False)

modality  token
@word     женщина        0.015622
          мужчина        0.009645
          животное       0.007322
          группа         0.006628
          вид            0.006488
                           ...
          полимер        0.000000
          разлагаться    0.000000
          микросхема     0.000000
          принтер        0.000000
          аврелий        0.000000
Name: topic_7, Length: 19186, dtype: float32

In [131]:
coherence_score.call_by_topic(bank_model)

{0: array([1.18129293]),
 1: array([0.94094366]),
 2: array([0.92717515]),
 3: array([0.8584458]),
 4: array([0.96024055]),
 5: array([0.94228977]),
 6: array([1.14422727]),
 7: array([0.89189949])}

In [132]:
coherence_score.call(bank_model)

array([0.98081433])

In [135]:
optimizer._result['bank_scores'][-1]

{'perplexity_score': 3875.74169921875,
 'coherence_20': 0.564805432002065,
 'diversity_euclidean': 0.03567965163581824,
 'diversity_jensenshannon': 0.5957037221303795,
 'diversity_hellinger': 0.6853192252936954,
 'diversity_cosine': 0.6242113090660045,
 'perplexity': 3875.74169921875}

In [136]:
optimizer._get_default_scores(bank_model)

{'perplexity_score': 5749.072265625,
 'coherence_20': 0.98081432765508,
 'diversity_euclidean': 0.04722044093307479,
 'diversity_jensenshannon': 0.6019876723935436,
 'diversity_hellinger': 0.6929207704718845,
 'diversity_cosine': 0.745312495094132,
 'perplexity': 5749.072265625}

In [78]:
model = init_model_from_family('ARTM', DATASET, MAIN_MODALITY, 2, 0)

No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

In [80]:
m._fit(DATASET.get_batch_vectorizer(), 2)

In [82]:
m.get_phi()

                        topic_0   topic_1  background_2
modality token
@word    инвалидность  0.000000  0.000000      0.000011
         мазка         0.000000  0.000000      0.000011
         professor     0.000000  0.000000      0.000011
         умно          0.000000  0.000000      0.000011
         игил          0.000000  0.000000      0.000011
...                         ...       ...           ...
         милосердие    0.000000  0.000000      0.000015
         поверка       0.000000  0.000000      0.000015
         вто           0.000083  0.000000      0.000025
         слоить        0.000003  0.000012      0.000076
         акт           0.000210  0.000083      0.000123

[19186 rows x 3 columns]

In [38]:
import artm
from topnum.model_constructor import KnownModel, init_plsa
from topicnet.cooking_machine.rel_toolbox_lite import (
    count_vocab_size,
    transform_regularizer,
)
from topicnet.cooking_machine.model_constructor import (
    add_standard_scores,
    create_default_topics,
    init_model,
)

def init_model_from_family(
        family: str or KnownModel,
        dataset: Dataset,
        main_modality: str,
        num_topics: int,
        seed: int,
        specific_topic_names = None,
        modalities_to_use: List[str] = None,
        num_processors: int = 3,
        model_params: dict = None,
):
    """
    Returns
    -------
    model: TopicModel() instance
    """
    if isinstance(family, KnownModel):
        family = family.value

    if modalities_to_use is None:
        modalities_to_use = [main_modality]

    custom_regs = {}

    if family == "LDA":
        model = init_lda(
            dataset, modalities_to_use, main_modality, num_topics, model_params
        )
    elif family == "PLSA":
        model = init_plsa(
            dataset, modalities_to_use, main_modality, num_topics
        )
    elif family == "TARTM":
        model, custom_regs = init_thetaless(
            dataset, modalities_to_use, main_modality, num_topics, model_params
        )
    elif family == "sparse":
        model = init_bcg_sparse_model(
            dataset, modalities_to_use, main_modality, num_topics, 1, model_params
        )
    elif family == "decorrelation":
        model = init_decorrelated_plsa(
            dataset, modalities_to_use, main_modality, num_topics, model_params
        )
    elif family == "ARTM":
        model = init_baseline_artm(
            dataset, modalities_to_use, main_modality, num_topics, 1, specific_topic_names, model_params
        )
    else:
        raise ValueError(f'family: {family}')

    model.num_processors = num_processors

    if seed is not None:
        model.seed = seed

    dictionary = dataset.get_dictionary()

    # TODO: maybe this cycle is not necessary
    for modality in dataset.get_possible_modalities():
        if modality not in modalities_to_use:
            dictionary.filter(class_id=modality, max_df=0, inplace=True)

    model.initialize(dictionary)
    add_standard_scores(model, dictionary, main_modality=main_modality,
                        all_modalities=modalities_to_use)

    model = TopicModel(
        artm_model=model,
        custom_regularizers=custom_regs
    )
    model.has_bcg = True  # TODO: only if init_bcg_sparse_model

    return model


def init_bcg_sparse_model(
        dataset,
        modalities_to_use,
        main_modality,
        specific_topics,
        bcg_topics,
        specific_topic_names = None,
        model_params: dict = None
):
    """
    Creates simple artm model with standard scores.

    Parameters
    ----------
    dataset : Dataset
    modalities_to_use : list of str or dict
    main_modality : str
    specific_topics : int
    bcg_topics : int

    Returns
    -------
    model: artm.ARTM() instance
    """
    if model_params is None:
        model_params = dict()

    model = init_plsa(
        dataset, modalities_to_use, main_modality, specific_topics, bcg_topics
    )
    background_topic_names = model.topic_names[-bcg_topics:]

    if specific_topic_names is None:
        print('No spec topics')
        specific_topic_names = model.topic_names[:-bcg_topics]

    dictionary = dataset.get_dictionary()
    baseline_class_ids = {class_id: 1 for class_id in modalities_to_use}
    data_stats = count_vocab_size(dictionary, baseline_class_ids)

    # all coefficients are relative
    regularizers = [
        artm.SmoothSparsePhiRegularizer(
             name='smooth_phi_bcg',
             topic_names=background_topic_names,
             tau=model_params.get("smooth_bcg_tau", 0.1),
             class_ids=[main_modality],
        ),
        artm.SmoothSparseThetaRegularizer(
             name='smooth_theta_bcg',
             topic_names=background_topic_names,
             tau=model_params.get("smooth_bcg_tau", 0.1),
        ),
        artm.SmoothSparsePhiRegularizer(
             name='sparse_phi_sp',
             topic_names=specific_topic_names,
             tau=model_params.get("sparse_sp_tau", -0.05),
             class_ids=[main_modality],
            ),
        artm.SmoothSparseThetaRegularizer(
             name='sparse_theta_sp',
             topic_names=specific_topic_names,
             tau=model_params.get("sparse_sp_tau", -0.05),
        ),
    ]
    for reg in regularizers:
        model.regularizers.add(transform_regularizer(
            data_stats,
            reg,
            model.class_ids,
            n_topics=len(reg.topic_names)
        ))

    return model


def init_baseline_artm(
        dataset,
        modalities_to_use,
        main_modality,
        num_topics,
        bcg_topics,
        specific_topic_names = None,
        model_params: dict = None,
):
    """
    Creates simple artm model with standard scores.

    Parameters
    ----------
    dataset : Dataset
    modalities_to_use : list of str
    main_modality : str
    num_topics : int

    Returns
    -------
    model: artm.ARTM() instance
    """
    if model_params is None:
        model_params = dict()

    model = init_bcg_sparse_model(
        dataset, modalities_to_use, main_modality, num_topics, bcg_topics, specific_topic_names, model_params
    )

    if specific_topic_names is None:
        print('No spec topics')
        specific_topic_names = model.topic_names[:-bcg_topics]

    model.regularizers.add(
        artm.DecorrelatorPhiRegularizer(
            gamma=0,
            tau=model_params.get('decorrelation_tau', 0.01),
            name='decorrelation',
            topic_names=specific_topic_names,
            class_ids=modalities_to_use,
        )
    )

    return model

In [39]:
def artm_train_func(
        dataset: Dataset,
        model_number: int,
        num_topics: int,
        num_fit_iterations: int,
        scores: List = None,
        **kwargs) -> TopicModel:
    """

    Additional Parameters
    ---------------------
    kwargs
        Some params for `_get_topic_model`, such as `cache_theta` and `num_processors`
    """

    topic_model = init_model_from_family(
        family='ARTM',
        dataset=DATASET,
        main_modality=MAIN_MODALITY,
        num_topics=ONE_MODEL_NUM_TOPICS,
        seed=model_number,
        model_params={
            'decorrelation_tau': 0.01,  # best values
            'smooth_bcg_tau': 0.05,
            'sparse_sp_tau': -0.05,
        }
    )

    num_fit_iterations_with_scores = 1

    topic_model._fit(
        dataset.get_batch_vectorizer(),
        num_iterations=max(0, num_fit_iterations - num_fit_iterations_with_scores)
    )
    _fit_model_with_scores(
        topic_model,
        DATASET,
        scores,
        num_fit_iterations=num_fit_iterations_with_scores
    )

    return topic_model


def _fit_model_with_scores(
        topic_model: TopicModel,
        dataset: Dataset,
        scores: List = None,
        num_fit_iterations: int = 1):

    if scores is not None:
        for score in scores:
            score._attach(topic_model)

    topic_model._fit(
        dataset.get_batch_vectorizer(),
        num_iterations=num_fit_iterations
    )

### Bank Creation<a id="bank-creation"></a>

<div style="text-align: right">Back to <a href=#contents>Contents</a></div>

Here we finally run the experiment!

In [40]:
NUM_ITERATIONS = 20

In [41]:
seed = 0

In [42]:
# We use only one train function here
# Other variations are also possible
# It would be even better to make bank using several train functions
# However, it would also take way more time 

TRAIN_FUNCS = artm_train_func  # default train func

In [43]:
DATASET_INTERNALS_FOLDER_PATH

'/data_mil/shared/CompressaAI/iterative/data/noow/Post_Science__internals'

In [44]:
! ls $DATASET_INTERNALS_FOLDER_PATH

batches  dict.dict  _result  result2  vw.txt

In [45]:
! mv $DATASET_INTERNALS_FOLDER_PATH/result $DATASET_INTERNALS_FOLDER_PATH/_result

mv: cannot stat '/data_mil/shared/CompressaAI/iterative/data/noow/Post_Science__internals/result': No such file or directory

In [46]:
! ls $DATASET_INTERNALS_FOLDER_PATH

batches  dict.dict  _result  result2  vw.txt

In [47]:
SEARCH_RESULTS_FOLDER_PATH = os.path.join(
    DATASET_INTERNALS_FOLDER_PATH, 'result2'
)

# File with some info about the process
SEARCH_RESULT_FILE_PATH = os.path.join(
    SEARCH_RESULTS_FOLDER_PATH, f'search_result__{seed}.json'
)

# Bank, with topics and their score values
BANK_FOLDER_PATH = os.path.join(
    SEARCH_RESULTS_FOLDER_PATH, f'bank__{seed}'
)

In [48]:
SEARCH_RESULTS_FOLDER_PATH

'/data_mil/shared/CompressaAI/iterative/data/noow/Post_Science__internals/result2'

In [49]:
! ls /data_mil/shared/CompressaAI/iterative/data/noow/Post_Science__internals

batches  dict.dict  _result  result2  vw.txt

In [50]:
! mv /data_mil/shared/CompressaAI/iterative/data/noow/Post_Science__internals/result2 /data_mil/shared/CompressaAI/iterative/data/noow/Post_Science__internals/_result2

In [51]:
! ls /data_mil/shared/CompressaAI/iterative/data/noow/Post_Science__internals

batches  dict.dict  _result  _result2  vw.txt

In [67]:
! ls $SEARCH_RESULTS_FOLDER_PATH

bank__0  search_result__0.json

! rm -r $SEARCH_RESULTS_FOLDER_PATH

In [52]:
BANK_FOLDER_PATH

'/data_mil/shared/CompressaAI/iterative/data/noow/Post_Science__internals/result2/bank__0'

In [69]:
os.makedirs(SEARCH_RESULTS_FOLDER_PATH, exist_ok=True)
os.makedirs(BANK_FOLDER_PATH, exist_ok=True)

In [54]:
seed

0

In [39]:
# https://github.com/machine-intelligence-laboratory/OptimalNumberOfTopics/blob/master/topnum/model_constructor.py#L120C5-L122C73

dictionary = DATASET.get_dictionary()

print(dictionary)

for modality in DATASET.get_possible_modalities():
    if modality not in [MAIN_MODALITY]:
        dictionary.filter(class_id=modality, max_df=0, inplace=True)

artm.Dictionary(name=d94d49a7-9d23-4f72-b02b-d89dfec6fdee, num_entries=53095)

In [40]:
print(dictionary)

artm.Dictionary(name=d94d49a7-9d23-4f72-b02b-d89dfec6fdee, num_entries=19186)

In [41]:
DATASET._cached_dict = dictionary

In [55]:
DATASET.get_dictionary()

artm.Dictionary(name=2901dd17-5ad8-409a-bf5d-782758d4d009, num_entries=19537)

In [56]:
DATASET.get_dictionary()

artm.Dictionary(name=2901dd17-5ad8-409a-bf5d-782758d4d009, num_entries=19537)

One cay vary some parameters below (for example `max_num_models` and `num_fit_iterations`).

In [57]:
len(DOCUMENTS), DATASET._data.shape

(3446, (3446, 3))

In [58]:
ONE_MODEL_NUM_TOPICS

20

In [59]:
NUM_ITERATIONS

20

In [70]:
optimizer = TopicBankMethod(
    data        = DATASET,
    main_modality = MAIN_MODALITY,
    
    min_df_rate = 0.0,  # dictionary filtering has already been done little earlier
    max_df_rate = 1.0,  #   so we don't want these parameters to have any effect

    main_topic_score   = intra_coherence_score,  # coherence_score,
    other_topic_scores = [coherence_score],
    other_scores       = [coherence_score] + diversity_scores + other_scores,
    documents          = DOCUMENTS,

    start_model_number   = 0,
    max_num_models       = 20,
    one_model_num_topics = ONE_MODEL_NUM_TOPICS,  # 100,
    num_fit_iterations   = NUM_ITERATIONS,  # 100,  # 100 should be enough;
                                 # however, for big data better to reduce this one
                                 # (otherwise the process will be too slow)
    #                                  70%                    75%                   80%
    topic_score_threshold_percentile = 2.3394925682940233,  # 2.435017475164776,  # 2.5432101128006273,  # DIFF ALSO HERE

    save_bank         = True,
    save_model_topics = True,
    save_file_path    = SEARCH_RESULT_FILE_PATH,
    bank_folder_path  = BANK_FOLDER_PATH,

    train_funcs = TRAIN_FUNCS,
    
    verbose = True,
)

# TODO: use Holdout Perplexity as Stop score

/home/alekseev_v/projects/iterative/../OptimalNumberOfTopics/topnum/search_methods/topic_bank/topic_bank_method.py:218: UserWarning: topic_score_threshold_percentile 2.3394925682940233 is less than one! It is expected to be in [0, 100]. Are you sure you want to proceed (yes/no)?
  warnings.warn(

In [71]:
optimizer._result.keys()

dict_keys(['optimum', 'optimum_std', 'bank_scores', 'bank_topic_scores', 'model_scores', 'model_topic_scores', 'num_bank_topics', 'num_model_topics'])

Checking file paths

! ls ./Post_Science__internals

In [72]:
optimizer._save_file_path

'/data_mil/shared/CompressaAI/iterative/data/noow/Post_Science__internals/result2/search_result__0.json'

In [73]:
optimizer._topic_bank._path

'/data_mil/shared/CompressaAI/iterative/data/noow/Post_Science__internals/result2/bank__0'

Fulfilling the search (get ready for a really long process!):

In [74]:
%%time

optimizer.search_for_optimum(DATASET)

  0%|                                                        | 0/20 [00:00<?, ?it/s]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).

  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████                        | 1/2 [01:42<01:42, 102.67s/it]Detected bcg topics! Skipping for coherence computation (and will have 20 topics).

100%|█████████████████████████████████████████████████| 2/2 [01:42<00:00, 51.42s/it]
Using absoulte threshold: 2.3394925682940233.
Eliminating bcg topic before Hier. Cur |T| is 21, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'background_20'],
      dtype='object').
Now |T| is 20, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19'],
      dtype='object').
Skipping saving scores for bcg topic
!!! Bank Phi: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 ...
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]].
!!! Bank model Phi: [[2.4751853e-10 2.5639957e-11 4.7218074e-09]
 [8.0890028e-10 7.2040637e-11 4.1144106e-09]
 [3.7410478e-12 3.2820670e-11 4.9582534e-09]
 ...
 [3.9602310e-10 4.5387447e-11 9.5484545e-09]
 [7.9050612e-12 3.5574169e-10 5.6303269e-09]
 [1.4837874e-09 2.7969599e-10 2.5209514e-08]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 ...
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 8.6239379e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 8.6239379e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 8.6239379e-06]
 ...
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 1.1274344e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 9.1540196e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 2.0285726e-05]].
Bank scores: {'perplexity_score': 28439.177734375, 'coherence_20': 0.9567557076597479, 'diversity_euclidean': 0.07520688316023542, 'diversity_jensenshannon': 0.6518311789823222, 'diversity_hellinger': 0.7552062776689774, 'diversity_cosine': 0.8216776639936949, 'perplexity': 28439.177734375, 'ppl_fair': 28439.177734375, 'ppl_cheatty': 4144.4482421875}
  5%|██▎                                            | 1/20 [02:35<49:10, 155.29s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).

  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████                        | 1/2 [01:42<01:42, 102.59s/it]Detected bcg topics! Skipping for coherence computation (and will have 20 topics).

100%|█████████████████████████████████████████████████| 2/2 [01:42<00:00, 51.38s/it]
Using absoulte threshold: 2.3394925682940233.
Eliminating bcg topic before Hier. Cur |T| is 21, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'background_20'],
      dtype='object').
Now |T| is 20, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19'],
      dtype='object').
Creating first level with 3 topics. Dictionary: artm.Dictionary(name=2901dd17-5ad8-409a-bf5d-782758d4d009, num_entries=19537).
Copying phi for the first level. Phi shape: (19537, 3). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           )
Creating second level with 20 topics
Copying phi for the second level. Phi shape: (19537, 20). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic
!!! Bank Phi: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 ...
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]].
!!! Bank model Phi: [[2.4751848e-10 2.5639952e-11 4.7218074e-09]
 [8.0890017e-10 7.2040658e-11 4.1144106e-09]
 [3.7410478e-12 3.2820673e-11 4.9582534e-09]
 ...
 [3.9602319e-10 4.5387447e-11 9.5484536e-09]
 [7.9050603e-12 3.5574163e-10 5.6303269e-09]
 [1.4837878e-09 2.7969604e-10 2.5209514e-08]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 ...
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 8.6239379e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 8.6239379e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 8.6239379e-06]
 ...
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 1.1274344e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 9.1540196e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 2.0285726e-05]].
Bank scores: {'perplexity_score': 28439.177734375, 'coherence_20': 0.9567557076597479, 'diversity_euclidean': 0.07520688316023438, 'diversity_jensenshannon': 0.6518311789829264, 'diversity_hellinger': 0.7552062776686018, 'diversity_cosine': 0.8216776639937158, 'perplexity': 28439.177734375, 'ppl_fair': 28439.177734375, 'ppl_cheatty': 4144.4482421875}
 10%|████▋                                          | 2/20 [05:17<47:51, 159.53s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).

  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████                        | 1/2 [01:43<01:43, 103.11s/it]Detected bcg topics! Skipping for coherence computation (and will have 20 topics).

100%|█████████████████████████████████████████████████| 2/2 [01:43<00:00, 51.64s/it]
Using absoulte threshold: 2.3394925682940233.
Eliminating bcg topic before Hier. Cur |T| is 21, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'background_20'],
      dtype='object').
Now |T| is 20, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19'],
      dtype='object').
Creating first level with 3 topics. Dictionary: artm.Dictionary(name=2901dd17-5ad8-409a-bf5d-782758d4d009, num_entries=19537).
Copying phi for the first level. Phi shape: (19537, 3). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           )
Creating second level with 20 topics
Copying phi for the second level. Phi shape: (19537, 20). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic
!!! Bank Phi: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 ...
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]].
!!! Bank model Phi: [[2.4751851e-10 2.5639962e-11 4.7218074e-09]
 [8.0890000e-10 7.2040630e-11 4.1144110e-09]
 [3.7410483e-12 3.2820670e-11 4.9582534e-09]
 ...
 [3.9602313e-10 4.5387454e-11 9.5484545e-09]
 [7.9050603e-12 3.5574177e-10 5.6303264e-09]
 [1.4837874e-09 2.7969602e-10 2.5209514e-08]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 ...
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 8.6239379e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 8.6239379e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 8.6239379e-06]
 ...
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 1.1274344e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 9.1540196e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 2.0285726e-05]].
Bank scores: {'perplexity_score': 28439.177734375, 'coherence_20': 0.9567557076597479, 'diversity_euclidean': 0.07520688316023437, 'diversity_jensenshannon': 0.6518311789822113, 'diversity_hellinger': 0.7552062776676953, 'diversity_cosine': 0.8216776639937157, 'perplexity': 28439.177734375, 'ppl_fair': 28439.177734375, 'ppl_cheatty': 4144.4482421875}
 15%|███████                                        | 3/20 [08:00<45:34, 160.86s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).

  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████                        | 1/2 [01:42<01:42, 102.90s/it]Detected bcg topics! Skipping for coherence computation (and will have 20 topics).

100%|█████████████████████████████████████████████████| 2/2 [01:43<00:00, 51.53s/it]
Using absoulte threshold: 2.3394925682940233.
Eliminating bcg topic before Hier. Cur |T| is 21, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'background_20'],
      dtype='object').
Now |T| is 20, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19'],
      dtype='object').
Creating first level with 3 topics. Dictionary: artm.Dictionary(name=2901dd17-5ad8-409a-bf5d-782758d4d009, num_entries=19537).
Copying phi for the first level. Phi shape: (19537, 3). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           )
Creating second level with 20 topics
Copying phi for the second level. Phi shape: (19537, 20). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic
!!! Bank Phi: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]].
!!! Bank model Phi: [[1.2605079e-10 1.2740667e-12 4.4435193e-09 3.9870562e-10 2.6393053e-11]
 [1.8506374e-10 8.6457811e-12 3.7878283e-09 4.4770404e-10 5.6712790e-10]
 [4.6583386e-13 3.9506562e-12 4.9000550e-09 9.0783152e-11 4.1653828e-13]
 ...
 [7.8524853e-11 2.4374678e-12 9.0339247e-09 6.4778893e-10 2.2912867e-10]
 [6.5386151e-13 2.0442422e-11 4.6733333e-09 1.2975228e-09 3.5391544e-12]
 [2.9732880e-10 1.2522385e-10 2.6273993e-08 1.2278219e-10 1.5744592e-10]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  9.5796377e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  9.5796377e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  9.5796377e-06]
 ...
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  1.2523760e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  1.0168463e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  2.2533774e-05]].
Bank scores: {'perplexity_score': 19434.2578125, 'coherence_20': 0.881855837365757, 'diversity_euclidean': 0.07119229092244327, 'diversity_jensenshannon': 0.6304273795383887, 'diversity_hellinger': 0.7295773054637931, 'diversity_cosine': 0.7859189069502196, 'perplexity': 19434.2578125, 'ppl_fair': 19434.2578125, 'ppl_cheatty': 3849.77587890625}
 20%|█████████▍                                     | 4/20 [10:44<43:17, 162.34s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).

  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████                        | 1/2 [01:43<01:43, 103.12s/it]Detected bcg topics! Skipping for coherence computation (and will have 20 topics).

100%|█████████████████████████████████████████████████| 2/2 [01:43<00:00, 51.64s/it]
Using absoulte threshold: 2.3394925682940233.
Eliminating bcg topic before Hier. Cur |T| is 21, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'background_20'],
      dtype='object').
Now |T| is 20, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19'],
      dtype='object').
Creating first level with 5 topics. Dictionary: artm.Dictionary(name=2901dd17-5ad8-409a-bf5d-782758d4d009, num_entries=19537).
Copying phi for the first level. Phi shape: (19537, 5). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           )
Creating second level with 20 topics
Copying phi for the second level. Phi shape: (19537, 20). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic
!!! Bank Phi: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]].
!!! Bank model Phi: [[1.2002603e-10 6.3453263e-13 4.4439870e-09 4.1340364e-10 1.7825477e-11]
 [6.5575168e-10 9.4000068e-12 3.4803560e-09 8.5073454e-10 1.9582652e-13]
 [1.0147421e-12 2.6725102e-12 4.8743560e-09 1.1754690e-10 4.0937333e-14]
 ...
 [1.4641022e-10 1.8865660e-12 8.8820631e-09 9.2167746e-10 3.9712591e-11]
 [1.5818833e-12 1.0917315e-11 4.5922208e-09 1.3897665e-09 9.5600958e-13]
 [3.5550352e-10 5.3496998e-11 2.6200327e-08 1.2545309e-10 2.4176297e-10]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  9.4932184e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  9.4932184e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  9.4932184e-06]
 ...
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  1.2410781e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  1.0076731e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  2.2330498e-05]].
Bank scores: {'perplexity_score': 19913.849609375, 'coherence_20': 0.7898808418093549, 'diversity_euclidean': 0.06689378230169848, 'diversity_jensenshannon': 0.623212207226943, 'diversity_hellinger': 0.7217607317325911, 'diversity_cosine': 0.7391438409228389, 'perplexity': 19913.849609375, 'ppl_fair': 19913.849609375, 'ppl_cheatty': 3889.375}
 25%|███████████▊                                   | 5/20 [13:30<40:51, 163.44s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).

  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████                        | 1/2 [01:43<01:43, 103.38s/it]Detected bcg topics! Skipping for coherence computation (and will have 20 topics).

100%|█████████████████████████████████████████████████| 2/2 [01:43<00:00, 51.78s/it]
Using absoulte threshold: 2.3394925682940233.
Eliminating bcg topic before Hier. Cur |T| is 21, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'background_20'],
      dtype='object').
Now |T| is 20, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19'],
      dtype='object').
Creating first level with 5 topics. Dictionary: artm.Dictionary(name=2901dd17-5ad8-409a-bf5d-782758d4d009, num_entries=19537).
Copying phi for the first level. Phi shape: (19537, 5). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           )
Creating second level with 20 topics
Copying phi for the second level. Phi shape: (19537, 20). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic
!!! Bank Phi: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]].
!!! Bank model Phi: [[1.2002606e-10 6.3453274e-13 4.4439861e-09 4.1340367e-10 1.7825477e-11]
 [6.5575156e-10 9.4000068e-12 3.4803558e-09 8.5073470e-10 1.9582658e-13]
 [1.0147417e-12 2.6725098e-12 4.8743556e-09 1.1754693e-10 4.0937353e-14]
 ...
 [1.4641022e-10 1.8865662e-12 8.8820631e-09 9.2167757e-10 3.9712601e-11]
 [1.5818824e-12 1.0917316e-11 4.5922208e-09 1.3897666e-09 9.5600936e-13]
 [3.5550343e-10 5.3497005e-11 2.6200327e-08 1.2545309e-10 2.4176294e-10]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  9.4932184e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  9.4932184e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  9.4932184e-06]
 ...
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  1.2410781e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  1.0076731e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  2.2330492e-05]].
Bank scores: {'perplexity_score': 19913.849609375, 'coherence_20': 0.7898808418093549, 'diversity_euclidean': 0.06689378230169771, 'diversity_jensenshannon': 0.6232122072267057, 'diversity_hellinger': 0.7217607317326232, 'diversity_cosine': 0.7391438409228032, 'perplexity': 19913.849609375, 'ppl_fair': 19913.849609375, 'ppl_cheatty': 3889.375}
 30%|██████████████                                 | 6/20 [16:13<38:08, 163.46s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).

  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████                        | 1/2 [01:43<01:43, 103.44s/it]Detected bcg topics! Skipping for coherence computation (and will have 20 topics).

100%|█████████████████████████████████████████████████| 2/2 [01:43<00:00, 51.80s/it]
Using absoulte threshold: 2.3394925682940233.
Eliminating bcg topic before Hier. Cur |T| is 21, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'background_20'],
      dtype='object').
Now |T| is 20, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19'],
      dtype='object').
Creating first level with 5 topics. Dictionary: artm.Dictionary(name=2901dd17-5ad8-409a-bf5d-782758d4d009, num_entries=19537).
Copying phi for the first level. Phi shape: (19537, 5). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           )
Creating second level with 20 topics
Copying phi for the second level. Phi shape: (19537, 20). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic
!!! Bank Phi: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]].
!!! Bank model Phi: [[1.2002610e-10 6.3453285e-13 4.4439870e-09 4.1340373e-10 1.7825479e-11]
 [6.5575168e-10 9.4000051e-12 3.4803562e-09 8.5073443e-10 1.9582659e-13]
 [1.0147417e-12 2.6725087e-12 4.8743556e-09 1.1754686e-10 4.0937343e-14]
 ...
 [1.4641023e-10 1.8865662e-12 8.8820631e-09 9.2167779e-10 3.9712601e-11]
 [1.5818834e-12 1.0917318e-11 4.5922213e-09 1.3897664e-09 9.5600936e-13]
 [3.5550346e-10 5.3497005e-11 2.6200327e-08 1.2545309e-10 2.4176292e-10]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  9.4932184e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  9.4932184e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  9.4932184e-06]
 ...
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  1.2410781e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  1.0076731e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  2.2330492e-05]].
Bank scores: {'perplexity_score': 19913.849609375, 'coherence_20': 0.7898808418093549, 'diversity_euclidean': 0.06689378230168672, 'diversity_jensenshannon': 0.6232122072254038, 'diversity_hellinger': 0.7217607317305894, 'diversity_cosine': 0.7391438409225268, 'perplexity': 19913.849609375, 'ppl_fair': 19913.849609375, 'ppl_cheatty': 3889.375}
 35%|████████████████▍                              | 7/20 [18:58<35:30, 163.85s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).

  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████                        | 1/2 [01:43<01:43, 103.96s/it]Detected bcg topics! Skipping for coherence computation (and will have 20 topics).

100%|█████████████████████████████████████████████████| 2/2 [01:44<00:00, 52.06s/it]
Using absoulte threshold: 2.3394925682940233.
Eliminating bcg topic before Hier. Cur |T| is 21, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'background_20'],
      dtype='object').
Now |T| is 20, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19'],
      dtype='object').
Creating first level with 5 topics. Dictionary: artm.Dictionary(name=2901dd17-5ad8-409a-bf5d-782758d4d009, num_entries=19537).
Copying phi for the first level. Phi shape: (19537, 5). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           )
Creating second level with 20 topics
Copying phi for the second level. Phi shape: (19537, 20). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic
!!! Bank Phi: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]].
!!! Bank model Phi: [[1.2002607e-10 6.3453285e-13 4.4439861e-09 4.1340381e-10 1.7825479e-11]
 [6.5575179e-10 9.4000077e-12 3.4803562e-09 8.5073421e-10 1.9582660e-13]
 [1.0147422e-12 2.6725102e-12 4.8743551e-09 1.1754690e-10 4.0937353e-14]
 ...
 [1.4641020e-10 1.8865662e-12 8.8820631e-09 9.2167768e-10 3.9712601e-11]
 [1.5818826e-12 1.0917316e-11 4.5922213e-09 1.3897664e-09 9.5600958e-13]
 [3.5550338e-10 5.3497005e-11 2.6200327e-08 1.2545308e-10 2.4176294e-10]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  9.4932184e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  9.4932184e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  9.4932184e-06]
 ...
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  1.2410781e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  1.0076731e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  2.2330492e-05]].
Bank scores: {'perplexity_score': 19913.849609375, 'coherence_20': 0.7898808418093549, 'diversity_euclidean': 0.06689378230169774, 'diversity_jensenshannon': 0.6232122072266987, 'diversity_hellinger': 0.7217607317327903, 'diversity_cosine': 0.7391438409228034, 'perplexity': 19913.849609375, 'ppl_fair': 19913.849609375, 'ppl_cheatty': 3889.375}
 40%|██████████████████▊                            | 8/20 [21:43<32:50, 164.18s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).

  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████                        | 1/2 [01:43<01:43, 103.69s/it]Detected bcg topics! Skipping for coherence computation (and will have 20 topics).

100%|█████████████████████████████████████████████████| 2/2 [01:43<00:00, 51.93s/it]
Using absoulte threshold: 2.3394925682940233.
Eliminating bcg topic before Hier. Cur |T| is 21, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'background_20'],
      dtype='object').
Now |T| is 20, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19'],
      dtype='object').
Creating first level with 5 topics. Dictionary: artm.Dictionary(name=2901dd17-5ad8-409a-bf5d-782758d4d009, num_entries=19537).
Copying phi for the first level. Phi shape: (19537, 5). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           )
Creating second level with 20 topics
Copying phi for the second level. Phi shape: (19537, 20). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic
!!! Bank Phi: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]].
!!! Bank model Phi: [[1.20026059e-10 6.34532737e-13 4.44398696e-09 4.13403645e-10
  1.78254772e-11]
 [6.55751675e-10 9.40000421e-12 3.48035623e-09 8.50734372e-10
  1.95826577e-13]
 [1.01474189e-12 2.67250935e-12 4.87435559e-09 1.17546944e-10
  4.09373395e-14]
 ...
 [1.46410203e-10 1.88656599e-12 8.88206309e-09 9.21677457e-10
  3.97126013e-11]
 [1.58188306e-12 1.09173165e-11 4.59222083e-09 1.38976641e-09
  9.56009469e-13]
 [3.55503460e-10 5.34970124e-11 2.62003272e-08 1.25453092e-10
  2.41762971e-10]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  9.4932184e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  9.4932184e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  9.4932184e-06]
 ...
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  1.2410781e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  1.0076731e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  2.2330492e-05]].
Bank scores: {'perplexity_score': 19913.849609375, 'coherence_20': 0.7898808418093549, 'diversity_euclidean': 0.06689378230169771, 'diversity_jensenshannon': 0.6232122072266483, 'diversity_hellinger': 0.7217607317324921, 'diversity_cosine': 0.7391438409228032, 'perplexity': 19913.849609375, 'ppl_fair': 19913.849609375, 'ppl_cheatty': 3889.375}
 45%|█████████████████████▏                         | 9/20 [24:27<30:07, 164.28s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).

  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████                        | 1/2 [01:44<01:44, 104.22s/it]Detected bcg topics! Skipping for coherence computation (and will have 20 topics).

100%|█████████████████████████████████████████████████| 2/2 [01:44<00:00, 52.19s/it]
Using absoulte threshold: 2.3394925682940233.
Eliminating bcg topic before Hier. Cur |T| is 21, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'background_20'],
      dtype='object').
Now |T| is 20, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19'],
      dtype='object').
Creating first level with 5 topics. Dictionary: artm.Dictionary(name=2901dd17-5ad8-409a-bf5d-782758d4d009, num_entries=19537).
Copying phi for the first level. Phi shape: (19537, 5). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           )
Creating second level with 20 topics
Copying phi for the second level. Phi shape: (19537, 20). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic
!!! Bank Phi: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]].
!!! Bank model Phi: [[1.2002607e-10 6.3453279e-13 4.4439870e-09 4.1340370e-10 1.7825477e-11]
 [6.5575173e-10 9.4000025e-12 3.4803558e-09 8.5073421e-10 1.9582658e-13]
 [1.0147415e-12 2.6725085e-12 4.8743560e-09 1.1754686e-10 4.0937340e-14]
 ...
 [1.4641023e-10 1.8865662e-12 8.8820631e-09 9.2167768e-10 3.9712601e-11]
 [1.5818837e-12 1.0917318e-11 4.5922208e-09 1.3897664e-09 9.5600947e-13]
 [3.5550343e-10 5.3497009e-11 2.6200327e-08 1.2545311e-10 2.4176294e-10]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  9.4932193e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  9.4932193e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  9.4932193e-06]
 ...
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  1.2410782e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  1.0076732e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  2.2330500e-05]].
Bank scores: {'perplexity_score': 19913.849609375, 'coherence_20': 0.7898808418093549, 'diversity_euclidean': 0.06689378230169704, 'diversity_jensenshannon': 0.6232122072264024, 'diversity_hellinger': 0.7217607317326376, 'diversity_cosine': 0.7391438409227825, 'perplexity': 19913.849609375, 'ppl_fair': 19913.849609375, 'ppl_cheatty': 3889.375}
 50%|███████████████████████                       | 10/20 [27:14<27:29, 164.91s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).

  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████                        | 1/2 [01:43<01:43, 103.84s/it]Detected bcg topics! Skipping for coherence computation (and will have 20 topics).

100%|█████████████████████████████████████████████████| 2/2 [01:44<00:00, 52.01s/it]
Using absoulte threshold: 2.3394925682940233.
Eliminating bcg topic before Hier. Cur |T| is 21, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'background_20'],
      dtype='object').
Now |T| is 20, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19'],
      dtype='object').
Creating first level with 5 topics. Dictionary: artm.Dictionary(name=2901dd17-5ad8-409a-bf5d-782758d4d009, num_entries=19537).
Copying phi for the first level. Phi shape: (19537, 5). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           )
Creating second level with 20 topics
Copying phi for the second level. Phi shape: (19537, 20). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic
!!! Bank Phi: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]].
!!! Bank model Phi: [[1.2002607e-10 6.3453279e-13 4.4439861e-09 4.1340378e-10 1.7825475e-11]
 [6.5575179e-10 9.4000059e-12 3.4803562e-09 8.5073432e-10 1.9582658e-13]
 [1.0147422e-12 2.6725109e-12 4.8743560e-09 1.1754690e-10 4.0937363e-14]
 ...
 [1.4641023e-10 1.8865662e-12 8.8820631e-09 9.2167779e-10 3.9712605e-11]
 [1.5818826e-12 1.0917315e-11 4.5922213e-09 1.3897664e-09 9.5600958e-13]
 [3.5550338e-10 5.3497005e-11 2.6200329e-08 1.2545308e-10 2.4176294e-10]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  9.4932184e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  9.4932184e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  9.4932184e-06]
 ...
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  1.2410781e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  1.0076731e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  2.2330498e-05]].
Bank scores: {'perplexity_score': 19913.849609375, 'coherence_20': 0.7898808418093549, 'diversity_euclidean': 0.06689378230169768, 'diversity_jensenshannon': 0.6232122072265969, 'diversity_hellinger': 0.7217607317326011, 'diversity_cosine': 0.7391438409228017, 'perplexity': 19913.849609375, 'ppl_fair': 19913.849609375, 'ppl_cheatty': 3889.375244140625}
 55%|█████████████████████████▎                    | 11/20 [29:59<24:44, 164.95s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).

  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████                        | 1/2 [01:43<01:43, 103.96s/it]Detected bcg topics! Skipping for coherence computation (and will have 20 topics).

100%|█████████████████████████████████████████████████| 2/2 [01:44<00:00, 52.07s/it]
Using absoulte threshold: 2.3394925682940233.
Eliminating bcg topic before Hier. Cur |T| is 21, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'background_20'],
      dtype='object').
Now |T| is 20, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19'],
      dtype='object').
Creating first level with 5 topics. Dictionary: artm.Dictionary(name=2901dd17-5ad8-409a-bf5d-782758d4d009, num_entries=19537).
Copying phi for the first level. Phi shape: (19537, 5). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           )
Creating second level with 20 topics
Copying phi for the second level. Phi shape: (19537, 20). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic
!!! Bank Phi: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]].
!!! Bank model Phi: [[1.2002607e-10 6.3453274e-13 4.4439861e-09 4.1340381e-10 1.7825479e-11]
 [6.5575190e-10 9.4000068e-12 3.4803562e-09 8.5073432e-10 1.9582660e-13]
 [1.0147422e-12 2.6725100e-12 4.8743551e-09 1.1754690e-10 4.0937367e-14]
 ...
 [1.4641022e-10 1.8865660e-12 8.8820631e-09 9.2167779e-10 3.9712615e-11]
 [1.5818831e-12 1.0917315e-11 4.5922213e-09 1.3897663e-09 9.5600958e-13]
 [3.5550338e-10 5.3496998e-11 2.6200327e-08 1.2545309e-10 2.4176294e-10]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  9.4932184e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  9.4932184e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  9.4932184e-06]
 ...
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  1.2410781e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  1.0076731e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  2.2330498e-05]].
Bank scores: {'perplexity_score': 19913.849609375, 'coherence_20': 0.7898808418093549, 'diversity_euclidean': 0.06689378230169703, 'diversity_jensenshannon': 0.6232122072265787, 'diversity_hellinger': 0.7217607317328995, 'diversity_cosine': 0.7391438409227991, 'perplexity': 19913.849609375, 'ppl_fair': 19913.849609375, 'ppl_cheatty': 3889.375244140625}
 60%|███████████████████████████▌                  | 12/20 [32:43<21:58, 164.83s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).

  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████                        | 1/2 [01:43<01:43, 103.57s/it]Detected bcg topics! Skipping for coherence computation (and will have 20 topics).

100%|█████████████████████████████████████████████████| 2/2 [01:43<00:00, 51.87s/it]
Using absoulte threshold: 2.3394925682940233.
Eliminating bcg topic before Hier. Cur |T| is 21, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'background_20'],
      dtype='object').
Now |T| is 20, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19'],
      dtype='object').
Creating first level with 5 topics. Dictionary: artm.Dictionary(name=2901dd17-5ad8-409a-bf5d-782758d4d009, num_entries=19537).
Copying phi for the first level. Phi shape: (19537, 5). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           )
Creating second level with 20 topics
Copying phi for the second level. Phi shape: (19537, 20). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic
!!! Bank Phi: [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]].
!!! Bank model Phi: [[7.98902069e-13 4.61772309e-09 1.77172388e-10 6.52499513e-11
  1.25333036e-10 9.77160800e-12]
 [4.49227391e-11 3.47690410e-09 8.54894974e-11 9.82667506e-13
  1.31681588e-09 7.16187248e-11]
 [4.65707854e-12 4.75794470e-09 2.28793970e-10 2.20553298e-13
  9.10872940e-13 3.43153435e-12]
 ...
 [9.17221368e-11 8.00678368e-09 1.37894612e-10 2.12703449e-11
  1.20806887e-09 5.27084709e-10]
 [1.00307306e-12 5.38085354e-09 6.09708950e-10 1.00169805e-13
  1.05857630e-12 2.62239471e-12]
 [2.00846495e-09 8.23664603e-09 2.60635313e-09 2.28175673e-11
  3.94446920e-10 1.37197693e-08]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 9.9941117e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 9.9941117e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 9.9941117e-06]
 ...
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.3065614e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.0608412e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 2.3508723e-05]].
Bank scores: {'perplexity_score': 16017.2265625, 'coherence_20': 0.7282088768668022, 'diversity_euclidean': 0.06413805607660919, 'diversity_jensenshannon': 0.6174077723200178, 'diversity_hellinger': 0.7146702985426139, 'diversity_cosine': 0.7347939170422457, 'perplexity': 16017.2265625, 'ppl_fair': 16017.2265625, 'ppl_cheatty': 3733.1591796875}
 65%|█████████████████████████████▉                | 13/20 [35:32<19:23, 166.16s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).

  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████                        | 1/2 [01:44<01:44, 104.23s/it]Detected bcg topics! Skipping for coherence computation (and will have 20 topics).

100%|█████████████████████████████████████████████████| 2/2 [01:44<00:00, 52.20s/it]
Using absoulte threshold: 2.3394925682940233.
Eliminating bcg topic before Hier. Cur |T| is 21, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'background_20'],
      dtype='object').
Now |T| is 20, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19'],
      dtype='object').
Creating first level with 6 topics. Dictionary: artm.Dictionary(name=2901dd17-5ad8-409a-bf5d-782758d4d009, num_entries=19537).
Copying phi for the first level. Phi shape: (19537, 6). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           )
Creating second level with 20 topics
Copying phi for the second level. Phi shape: (19537, 20). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic
!!! Bank Phi: [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]].
!!! Bank model Phi: [[7.9890196e-13 4.6177226e-09 1.7717235e-10 6.5249930e-11 1.2533298e-10
  9.7716071e-12]
 [4.4922729e-11 3.4769041e-09 8.5489511e-11 9.8266740e-13 1.3168158e-09
  7.1618718e-11]
 [4.6570785e-12 4.7579447e-09 2.2879400e-10 2.2055326e-13 9.1087294e-13
  3.4315348e-12]
 ...
 [9.1722123e-11 8.0067837e-09 1.3789461e-10 2.1270347e-11 1.2080689e-09
  5.2708471e-10]
 [1.0030727e-12 5.3808535e-09 6.0970895e-10 1.0016979e-13 1.0585760e-12
  2.6223951e-12]
 [2.0084649e-09 8.2366460e-09 2.6063527e-09 2.2817571e-11 3.9444692e-10
  1.3719769e-08]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 9.9941117e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 9.9941117e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 9.9941117e-06]
 ...
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.3065614e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.0608412e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 2.3508723e-05]].
Bank scores: {'perplexity_score': 16017.2265625, 'coherence_20': 0.7282088768668022, 'diversity_euclidean': 0.06413805607661302, 'diversity_jensenshannon': 0.617407772320026, 'diversity_hellinger': 0.7146702985427376, 'diversity_cosine': 0.7347939170421185, 'perplexity': 16017.2265625, 'ppl_fair': 16017.2265625, 'ppl_cheatty': 3733.1591796875}
 70%|████████████████████████████████▏             | 14/20 [38:18<16:35, 166.00s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).

  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████                        | 1/2 [01:44<01:44, 104.08s/it]Detected bcg topics! Skipping for coherence computation (and will have 20 topics).

100%|█████████████████████████████████████████████████| 2/2 [01:44<00:00, 52.12s/it]
Using absoulte threshold: 2.3394925682940233.
Eliminating bcg topic before Hier. Cur |T| is 21, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'background_20'],
      dtype='object').
Now |T| is 20, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19'],
      dtype='object').
Creating first level with 6 topics. Dictionary: artm.Dictionary(name=2901dd17-5ad8-409a-bf5d-782758d4d009, num_entries=19537).
Copying phi for the first level. Phi shape: (19537, 6). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           )
Creating second level with 20 topics
Copying phi for the second level. Phi shape: (19537, 20). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic
!!! Bank Phi: [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]].
!!! Bank model Phi: [[7.9890229e-13 4.6177231e-09 1.7717233e-10 6.5249951e-11 1.2533302e-10
  9.7716080e-12]
 [4.4922739e-11 3.4769041e-09 8.5489484e-11 9.8266761e-13 1.3168158e-09
  7.1618725e-11]
 [4.6570781e-12 4.7579447e-09 2.2879397e-10 2.2055323e-13 9.1087283e-13
  3.4315346e-12]
 ...
 [9.1722123e-11 8.0067837e-09 1.3789458e-10 2.1270341e-11 1.2080688e-09
  5.2708460e-10]
 [1.0030728e-12 5.3808535e-09 6.0970889e-10 1.0016980e-13 1.0585759e-12
  2.6223945e-12]
 [2.0084649e-09 8.2366460e-09 2.6063531e-09 2.2817571e-11 3.9444692e-10
  1.3719769e-08]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 9.9941117e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 9.9941117e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 9.9941117e-06]
 ...
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.3065614e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.0608412e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 2.3508723e-05]].
Bank scores: {'perplexity_score': 16017.2265625, 'coherence_20': 0.7282088768668022, 'diversity_euclidean': 0.06413805607661303, 'diversity_jensenshannon': 0.6174077723200176, 'diversity_hellinger': 0.7146702985426762, 'diversity_cosine': 0.7347939170421185, 'perplexity': 16017.2265625, 'ppl_fair': 16017.2265625, 'ppl_cheatty': 3733.1591796875}
 75%|██████████████████████████████████▌           | 15/20 [41:03<13:49, 165.82s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).

  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████                        | 1/2 [01:43<01:43, 103.79s/it]Detected bcg topics! Skipping for coherence computation (and will have 20 topics).

100%|█████████████████████████████████████████████████| 2/2 [01:43<00:00, 51.97s/it]
Using absoulte threshold: 2.3394925682940233.
Eliminating bcg topic before Hier. Cur |T| is 21, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'background_20'],
      dtype='object').
Now |T| is 20, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19'],
      dtype='object').
Creating first level with 6 topics. Dictionary: artm.Dictionary(name=2901dd17-5ad8-409a-bf5d-782758d4d009, num_entries=19537).
Copying phi for the first level. Phi shape: (19537, 6). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           )
Creating second level with 20 topics
Copying phi for the second level. Phi shape: (19537, 20). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic
!!! Bank Phi: [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]].
!!! Bank model Phi: [[7.9890185e-13 4.6177231e-09 1.7717236e-10 6.5249930e-11 1.2533302e-10
  9.7716080e-12]
 [4.4922729e-11 3.4769041e-09 8.5489539e-11 9.8266751e-13 1.3168159e-09
  7.1618746e-11]
 [4.6570790e-12 4.7579447e-09 2.2879397e-10 2.2055328e-13 9.1087316e-13
  3.4315350e-12]
 ...
 [9.1722137e-11 8.0067837e-09 1.3789458e-10 2.1270341e-11 1.2080688e-09
  5.2708476e-10]
 [1.0030728e-12 5.3808535e-09 6.0970889e-10 1.0016980e-13 1.0585760e-12
  2.6223941e-12]
 [2.0084649e-09 8.2366460e-09 2.6063531e-09 2.2817567e-11 3.9444681e-10
  1.3719769e-08]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 9.9941126e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 9.9941126e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 9.9941126e-06]
 ...
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.3065615e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.0608413e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 2.3508725e-05]].
Bank scores: {'perplexity_score': 16017.2265625, 'coherence_20': 0.7282088768668022, 'diversity_euclidean': 0.06413805607661141, 'diversity_jensenshannon': 0.6174077723197805, 'diversity_hellinger': 0.7146702985427907, 'diversity_cosine': 0.7347939170420388, 'perplexity': 16017.2265625, 'ppl_fair': 16017.2265625, 'ppl_cheatty': 3733.1591796875}
 80%|████████████████████████████████████▊         | 16/20 [43:48<11:02, 165.57s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).

  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████                        | 1/2 [01:43<01:43, 103.46s/it]Detected bcg topics! Skipping for coherence computation (and will have 20 topics).

100%|█████████████████████████████████████████████████| 2/2 [01:43<00:00, 51.81s/it]
Using absoulte threshold: 2.3394925682940233.
Eliminating bcg topic before Hier. Cur |T| is 21, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'background_20'],
      dtype='object').
Now |T| is 20, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19'],
      dtype='object').
Creating first level with 6 topics. Dictionary: artm.Dictionary(name=2901dd17-5ad8-409a-bf5d-782758d4d009, num_entries=19537).
Copying phi for the first level. Phi shape: (19537, 6). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           )
Creating second level with 20 topics
Copying phi for the second level. Phi shape: (19537, 20). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic
!!! Bank Phi: [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]].
!!! Bank model Phi: [[7.9890212e-13 4.6177231e-09 1.7717236e-10 6.5249944e-11 1.2533302e-10
  9.7716097e-12]
 [4.4922725e-11 3.4769041e-09 8.5489539e-11 9.8266740e-13 1.3168159e-09
  7.1618739e-11]
 [4.6570790e-12 4.7579447e-09 2.2879401e-10 2.2055330e-13 9.1087337e-13
  3.4315346e-12]
 ...
 [9.1722158e-11 8.0067837e-09 1.3789457e-10 2.1270345e-11 1.2080690e-09
  5.2708476e-10]
 [1.0030727e-12 5.3808535e-09 6.0970884e-10 1.0016980e-13 1.0585762e-12
  2.6223951e-12]
 [2.0084649e-09 8.2366451e-09 2.6063531e-09 2.2817566e-11 3.9444686e-10
  1.3719769e-08]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 9.9941117e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 9.9941117e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 9.9941117e-06]
 ...
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.3065614e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.0608412e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 2.3508723e-05]].
Bank scores: {'perplexity_score': 16017.2265625, 'coherence_20': 0.7282088768668022, 'diversity_euclidean': 0.0641380560766092, 'diversity_jensenshannon': 0.6174077723199676, 'diversity_hellinger': 0.7146702985428188, 'diversity_cosine': 0.7347939170422421, 'perplexity': 16017.2265625, 'ppl_fair': 16017.2265625, 'ppl_cheatty': 3733.1591796875}
 85%|███████████████████████████████████████       | 17/20 [46:33<08:15, 165.27s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).

  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████                        | 1/2 [01:44<01:44, 104.05s/it]Detected bcg topics! Skipping for coherence computation (and will have 20 topics).

100%|█████████████████████████████████████████████████| 2/2 [01:44<00:00, 52.10s/it]
Using absoulte threshold: 2.3394925682940233.
Eliminating bcg topic before Hier. Cur |T| is 21, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'background_20'],
      dtype='object').
Now |T| is 20, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19'],
      dtype='object').
Creating first level with 6 topics. Dictionary: artm.Dictionary(name=2901dd17-5ad8-409a-bf5d-782758d4d009, num_entries=19537).
Copying phi for the first level. Phi shape: (19537, 6). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           )
Creating second level with 20 topics
Copying phi for the second level. Phi shape: (19537, 20). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic
!!! Bank Phi: [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]].
!!! Bank model Phi: [[7.9890218e-13 4.6177235e-09 1.7717235e-10 6.5249937e-11 1.2533301e-10
  9.7716071e-12]
 [4.4922722e-11 3.4769043e-09 8.5489525e-11 9.8266772e-13 1.3168158e-09
  7.1618753e-11]
 [4.6570790e-12 4.7579447e-09 2.2879384e-10 2.2055333e-13 9.1087283e-13
  3.4315344e-12]
 ...
 [9.1722178e-11 8.0067837e-09 1.3789458e-10 2.1270347e-11 1.2080691e-09
  5.2708460e-10]
 [1.0030732e-12 5.3808535e-09 6.0970889e-10 1.0016983e-13 1.0585754e-12
  2.6223956e-12]
 [2.0084649e-09 8.2366469e-09 2.6063525e-09 2.2817569e-11 3.9444689e-10
  1.3719769e-08]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]].
!!! Bank model Phi: [[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 9.99411077e-06]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 9.99411077e-06]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 9.99411077e-06]
 ...
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.30656135e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.06084117e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 2.35087209e-05]].
Bank scores: {'perplexity_score': 16017.2265625, 'coherence_20': 0.7282088768668022, 'diversity_euclidean': 0.06413805607661129, 'diversity_jensenshannon': 0.6174077723196938, 'diversity_hellinger': 0.714670298542683, 'diversity_cosine': 0.7347939170420371, 'perplexity': 16017.2265625, 'ppl_fair': 16017.2265625, 'ppl_cheatty': 3733.1591796875}
 90%|█████████████████████████████████████████▍    | 18/20 [49:18<05:30, 165.21s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).

  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████                        | 1/2 [01:43<01:43, 103.91s/it]Detected bcg topics! Skipping for coherence computation (and will have 20 topics).

100%|█████████████████████████████████████████████████| 2/2 [01:44<00:00, 52.04s/it]
Using absoulte threshold: 2.3394925682940233.
Eliminating bcg topic before Hier. Cur |T| is 21, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'background_20'],
      dtype='object').
Now |T| is 20, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19'],
      dtype='object').
Creating first level with 6 topics. Dictionary: artm.Dictionary(name=2901dd17-5ad8-409a-bf5d-782758d4d009, num_entries=19537).
Copying phi for the first level. Phi shape: (19537, 6). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           )
Creating second level with 20 topics
Copying phi for the second level. Phi shape: (19537, 20). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic
!!! Bank Phi: [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]].
!!! Bank model Phi: [[7.98902177e-13 4.61772309e-09 1.77172388e-10 6.52499513e-11
  1.25332994e-10 9.77160974e-12]
 [4.49227357e-11 3.47690410e-09 8.54895529e-11 9.82668048e-13
  1.31681577e-09 7.16187665e-11]
 [4.65707898e-12 4.75794470e-09 2.28793914e-10 2.20553312e-13
  9.10872831e-13 3.43153435e-12]
 ...
 [9.17221576e-11 8.00678368e-09 1.37894585e-10 2.12703466e-11
  1.20806898e-09 5.27084598e-10]
 [1.00307306e-12 5.38085354e-09 6.09708783e-10 1.00169805e-13
  1.05857608e-12 2.62239449e-12]
 [2.00846495e-09 8.23664603e-09 2.60635269e-09 2.28175638e-11
  3.94446920e-10 1.37197693e-08]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 9.9941117e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 9.9941117e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 9.9941117e-06]
 ...
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.3065614e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.0608412e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 2.3508723e-05]].
Bank scores: {'perplexity_score': 16017.2265625, 'coherence_20': 0.7282088768668022, 'diversity_euclidean': 0.0641380560766113, 'diversity_jensenshannon': 0.6174077723197019, 'diversity_hellinger': 0.7146702985426278, 'diversity_cosine': 0.734793917042038, 'perplexity': 16017.2265625, 'ppl_fair': 16017.2265625, 'ppl_cheatty': 3733.1591796875}
 95%|███████████████████████████████████████████▋  | 19/20 [52:04<02:45, 165.53s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).

  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████                        | 1/2 [01:44<01:44, 104.62s/it]Detected bcg topics! Skipping for coherence computation (and will have 20 topics).

100%|█████████████████████████████████████████████████| 2/2 [01:44<00:00, 52.39s/it]
Using absoulte threshold: 2.3394925682940233.
Eliminating bcg topic before Hier. Cur |T| is 21, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'background_20'],
      dtype='object').
Now |T| is 20, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19'],
      dtype='object').
Creating first level with 6 topics. Dictionary: artm.Dictionary(name=2901dd17-5ad8-409a-bf5d-782758d4d009, num_entries=19537).
Copying phi for the first level. Phi shape: (19537, 6). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           )
Creating second level with 20 topics
Copying phi for the second level. Phi shape: (19537, 20). First words: MultiIndex([('@word',  'дублирование'),
            ('@word',    'проучиться'),
            ('@word',    'гимнастика'),
            ('@word',        'софист'),
            ('@word',     'парижанин'),
            ('@word',        'жадный'),
            ('@word',         'антиd'),
            ('@word',          'volk'),
            ('@word',        'огонек'),
            ('@word', 'несторианский')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic
!!! Bank Phi: [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]].
!!! Bank model Phi: [[7.98902177e-13 4.61772354e-09 1.77172346e-10 6.52499443e-11
  1.25333008e-10 9.77160713e-12]
 [4.49227357e-11 3.47690410e-09 8.54895252e-11 9.82667723e-13
  1.31681577e-09 7.16187526e-11]
 [4.65707898e-12 4.75794470e-09 2.28793887e-10 2.20553298e-13
  9.10872831e-13 3.43153435e-12]
 ...
 [9.17221646e-11 8.00678368e-09 1.37894543e-10 2.12703501e-11
  1.20806898e-09 5.27084709e-10]
 [1.00307306e-12 5.38085354e-09 6.09708839e-10 1.00169845e-13
  1.05857532e-12 2.62239557e-12]
 [2.00846495e-09 8.23664692e-09 2.60635247e-09 2.28175690e-11
  3.94446892e-10 1.37197693e-08]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 9.9941117e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 9.9941117e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 9.9941117e-06]
 ...
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.3065614e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.0608412e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 2.3508723e-05]].
Bank scores: {'perplexity_score': 16017.2265625, 'coherence_20': 0.7282088768668022, 'diversity_euclidean': 0.06413805607661366, 'diversity_jensenshannon': 0.6174077723201977, 'diversity_hellinger': 0.7146702985437808, 'diversity_cosine': 0.7347939170421168, 'perplexity': 16017.2265625, 'ppl_fair': 16017.2265625, 'ppl_cheatty': 3733.1591796875}
100%|██████████████████████████████████████████████| 20/20 [54:51<00:00, 164.59s/it]
CPU times: user 1h 16min 41s, sys: 3min 10s, total: 1h 19min 52s
Wall time: 54min 51s

In [75]:
optimizer._main_modality

'@word'

What topics we have in bank

In [76]:
optimizer._topic_bank.view_topics().head()

                    topic_0  topic_1  topic_2  topic_3  topic_4  topic_5
@word дублирование      0.0      0.0      0.0      0.0      0.0      0.0
      проучиться        0.0      0.0      0.0      0.0      0.0      0.0
      гимнастика        0.0      0.0      0.0      0.0      0.0      0.0
      софист            0.0      0.0      0.0      0.0      0.0      0.0
      парижанин         0.0      0.0      0.0      0.0      0.0      0.0

In [77]:
bank_topics = optimizer._topic_bank.view_topics()

In [78]:
bank_topics.shape

(19537, 6)

In [79]:
bank_topics.head()

                    topic_0  topic_1  topic_2  topic_3  topic_4  topic_5
@word дублирование      0.0      0.0      0.0      0.0      0.0      0.0
      проучиться        0.0      0.0      0.0      0.0      0.0      0.0
      гимнастика        0.0      0.0      0.0      0.0      0.0      0.0
      софист            0.0      0.0      0.0      0.0      0.0      0.0
      парижанин         0.0      0.0      0.0      0.0      0.0      0.0

In [86]:
bank_topics['topic_1'].sort_values(ascending=False)[:20]  # TODO: Всё равно какая-то "полуфоновая" тема попала в банк

@word  говорить      0.013766
       там           0.011863
       понимать      0.011178
       знать         0.011130
       сейчас        0.010280
       дело          0.009853
       конечно       0.009372
       делать        0.009064
       надо          0.008819
       должный       0.008294
       чтото         0.007880
       вещь          0.007748
       вообще        0.007538
       заниматься    0.007420
       хорошо        0.006877
       разный        0.006778
       сделать       0.006634
       какието       0.006623
       даже          0.006439
       хотеть        0.006165
Name: topic_1, dtype: float64

And topic scores

In [87]:
optimizer._topic_bank.view_topic_scores()

,topic_0,topic_1,topic_2,topic_3,topic_4,topic_5
kernel_size,1683.000000,1591.000000,1655.000000,1833.000000,1981.000000,1964.000000
toplen_ptw,2.390119,3.234490,2.531433,2.418970,3.008297,3.044554
coherence_20,1.180297,0.439105,0.442914,0.636223,0.931885,0.738829
distance_to_nearest,0.837881,0.852757,0.797195,0.732147,0.693357,0.792311

All models are also saved (topics as $\Phi$ matrices and topic score values)

In [89]:
! ls $optimizer._topic_bank._path

model_0__phi.bin	    model_19__topic_scores.bin
model_0__topic_scores.bin   model_1__phi.bin
model_10__phi.bin	    model_1__topic_scores.bin
model_10__topic_scores.bin  model_2__phi.bin
model_11__phi.bin	    model_2__topic_scores.bin
model_11__topic_scores.bin  model_3__phi.bin
model_12__phi.bin	    model_3__topic_scores.bin
model_12__topic_scores.bin  model_4__phi.bin
model_13__phi.bin	    model_4__topic_scores.bin
model_13__topic_scores.bin  model_5__phi.bin
model_14__phi.bin	    model_5__topic_scores.bin
model_14__topic_scores.bin  model_6__phi.bin
model_15__phi.bin	    model_6__topic_scores.bin
model_15__topic_scores.bin  model_7__phi.bin
model_16__phi.bin	    model_7__topic_scores.bin
model_16__topic_scores.bin  model_8__phi.bin
model_17__phi.bin	    model_8__topic_scores.bin
model_17__topic_scores.bin  model_9__phi.bin
model_18__phi.bin	    model_9__topic_scores.bin
model_18__topic_scores.bin  topics.bin
model_19__phi.bin	    topic_scores.bin

In [90]:
optimizer._result.keys()

dict_keys(['optimum', 'optimum_std', 'bank_scores', 'bank_topic_scores', 'model_scores', 'model_topic_scores', 'num_bank_topics', 'num_model_topics'])

In [91]:
optimizer._result['num_bank_topics']

[3, 3, 3, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6]

In [92]:
len(optimizer._result['bank_topic_scores'])

20

In [93]:
optimizer._result

{'optimum': 6,
 'optimum_std': 0.0,
 'bank_scores': [{'perplexity_score': 28439.177734375,
   'coherence_20': 0.9567557076597479,
   'diversity_euclidean': 0.07520688316023542,
   'diversity_jensenshannon': 0.6518311789823222,
   'diversity_hellinger': 0.7552062776689774,
   'diversity_cosine': 0.8216776639936949,
   'perplexity': 28439.177734375,
   'ppl_fair': 28439.177734375,
   'ppl_cheatty': 4144.4482421875},
  {'perplexity_score': 28439.177734375,
   'coherence_20': 0.9567557076597479,
   'diversity_euclidean': 0.07520688316023438,
   'diversity_jensenshannon': 0.6518311789829264,
   'diversity_hellinger': 0.7552062776686018,
   'diversity_cosine': 0.8216776639937158,
   'perplexity': 28439.177734375,
   'ppl_fair': 28439.177734375,
   'ppl_cheatty': 4144.4482421875},
  {'perplexity_score': 28439.177734375,
   'coherence_20': 0.9567557076597479,
   'diversity_euclidean': 0.07520688316023437,
   'diversity_jensenshannon': 0.6518311789822113,
   'diversity_hellinger': 0.7552062776676953,
   'diversity_cosine': 0.8216776639937157,
   'perplexity': 28439.177734375,
   'ppl_fair': 28439.177734375,
   'ppl_cheatty': 4144.4482421875},
  {'perplexity_score': 19434.2578125,
   'coherence_20': 0.881855837365757,
   'diversity_euclidean': 0.07119229092244327,
   'diversity_jensenshannon': 0.6304273795383887,
   'diversity_hellinger': 0.7295773054637931,
   'diversity_cosine': 0.7859189069502196,
   'perplexity': 19434.2578125,
   'ppl_fair': 19434.2578125,
   'ppl_cheatty': 3849.77587890625},
  {'perplexity_score': 19913.849609375,
   'coherence_20': 0.7898808418093549,
   'diversity_euclidean': 0.06689378230169848,
   'diversity_jensenshannon': 0.623212207226943,
   'diversity_hellinger': 0.7217607317325911,
   'diversity_cosine': 0.7391438409228389,
   'perplexity': 19913.849609375,
   'ppl_fair': 19913.849609375,
   'ppl_cheatty': 3889.375},
  {'perplexity_score': 19913.849609375,
   'coherence_20': 0.7898808418093549,
   'diversity_euclidean': 0.06689378230169771,
   'diversity_jensenshannon': 0.6232122072267057,
   'diversity_hellinger': 0.7217607317326232,
   'diversity_cosine': 0.7391438409228032,
   'perplexity': 19913.849609375,
   'ppl_fair': 19913.849609375,
   'ppl_cheatty': 3889.375},
  {'perplexity_score': 19913.849609375,
   'coherence_20': 0.7898808418093549,
   'diversity_euclidean': 0.06689378230168672,
   'diversity_jensenshannon': 0.6232122072254038,
   'diversity_hellinger': 0.7217607317305894,
   'diversity_cosine': 0.7391438409225268,
   'perplexity': 19913.849609375,
   'ppl_fair': 19913.849609375,
   'ppl_cheatty': 3889.375},
  {'perplexity_score': 19913.849609375,
   'coherence_20': 0.7898808418093549,
   'diversity_euclidean': 0.06689378230169774,
   'diversity_jensenshannon': 0.6232122072266987,
   'diversity_hellinger': 0.7217607317327903,
   'diversity_cosine': 0.7391438409228034,
   'perplexity': 19913.849609375,
   'ppl_fair': 19913.849609375,
   'ppl_cheatty': 3889.375},
  {'perplexity_score': 19913.849609375,
   'coherence_20': 0.7898808418093549,
   'diversity_euclidean': 0.06689378230169771,
   'diversity_jensenshannon': 0.6232122072266483,
   'diversity_hellinger': 0.7217607317324921,
   'diversity_cosine': 0.7391438409228032,
   'perplexity': 19913.849609375,
   'ppl_fair': 19913.849609375,
   'ppl_cheatty': 3889.375},
  {'perplexity_score': 19913.849609375,
   'coherence_20': 0.7898808418093549,
   'diversity_euclidean': 0.06689378230169704,
   'diversity_jensenshannon': 0.6232122072264024,
   'diversity_hellinger': 0.7217607317326376,
   'diversity_cosine': 0.7391438409227825,
   'perplexity': 19913.849609375,
   'ppl_fair': 19913.849609375,
   'ppl_cheatty': 3889.375},
  {'perplexity_score': 19913.849609375,
   'coherence_20': 0.7898808418093549,
   'diversity_euclidean': 0.06689378230169768,
   'diversity_jensenshannon': 0.6232122072265969,
   'diversity_hellinger': 0.7217607317326011,
   'diversity_cosine': 0.7391438409228017,
   'perplexity': 19913.849609375,
   'ppl_fair': 19913.849609375,
   'ppl_cheatty': 3889.375244140625},
  {'perplexity_score': 19913.849609375,
   'coherence_20': 0.7898808418093549,
   'diversity_euclidean': 0.06689378230169703,
   'diversity_jensenshannon': 0.6232122072265787,
   'diversity_hellinger': 0.7217607317328995,
   'diversity_cosine': 0.7391438409227991,
   'perplexity': 19913.849609375,
   'ppl_fair': 19913.849609375,
   'ppl_cheatty': 3889.375244140625},
  {'perplexity_score': 16017.2265625,
   'coherence_20': 0.7282088768668022,
   'diversity_euclidean': 0.06413805607660919,
   'diversity_jensenshannon': 0.6174077723200178,
   'diversity_hellinger': 0.7146702985426139,
   'diversity_cosine': 0.7347939170422457,
   'perplexity': 16017.2265625,
   'ppl_fair': 16017.2265625,
   'ppl_cheatty': 3733.1591796875},
  {'perplexity_score': 16017.2265625,
   'coherence_20': 0.7282088768668022,
   'diversity_euclidean': 0.06413805607661302,
   'diversity_jensenshannon': 0.617407772320026,
   'diversity_hellinger': 0.7146702985427376,
   'diversity_cosine': 0.7347939170421185,
   'perplexity': 16017.2265625,
   'ppl_fair': 16017.2265625,
   'ppl_cheatty': 3733.1591796875},
  {'perplexity_score': 16017.2265625,
   'coherence_20': 0.7282088768668022,
   'diversity_euclidean': 0.06413805607661303,
   'diversity_jensenshannon': 0.6174077723200176,
   'diversity_hellinger': 0.7146702985426762,
   'diversity_cosine': 0.7347939170421185,
   'perplexity': 16017.2265625,
   'ppl_fair': 16017.2265625,
   'ppl_cheatty': 3733.1591796875},
  {'perplexity_score': 16017.2265625,
   'coherence_20': 0.7282088768668022,
   'diversity_euclidean': 0.06413805607661141,
   'diversity_jensenshannon': 0.6174077723197805,
   'diversity_hellinger': 0.7146702985427907,
   'diversity_cosine': 0.7347939170420388,
   'perplexity': 16017.2265625,
   'ppl_fair': 16017.2265625,
   'ppl_cheatty': 3733.1591796875},
  {'perplexity_score': 16017.2265625,
   'coherence_20': 0.7282088768668022,
   'diversity_euclidean': 0.0641380560766092,
   'diversity_jensenshannon': 0.6174077723199676,
   'diversity_hellinger': 0.7146702985428188,
   'diversity_cosine': 0.7347939170422421,
   'perplexity': 16017.2265625,
   'ppl_fair': 16017.2265625,
   'ppl_cheatty': 3733.1591796875},
  {'perplexity_score': 16017.2265625,
   'coherence_20': 0.7282088768668022,
   'diversity_euclidean': 0.06413805607661129,
   'diversity_jensenshannon': 0.6174077723196938,
   'diversity_hellinger': 0.714670298542683,
   'diversity_cosine': 0.7347939170420371,
   'perplexity': 16017.2265625,
   'ppl_fair': 16017.2265625,
   'ppl_cheatty': 3733.1591796875},
  {'perplexity_score': 16017.2265625,
   'coherence_20': 0.7282088768668022,
   'diversity_euclidean': 0.0641380560766113,
   'diversity_jensenshannon': 0.6174077723197019,
   'diversity_hellinger': 0.7146702985426278,
   'diversity_cosine': 0.734793917042038,
   'perplexity': 16017.2265625,
   'ppl_fair': 16017.2265625,
   'ppl_cheatty': 3733.1591796875},
  {'perplexity_score': 16017.2265625,
   'coherence_20': 0.7282088768668022,
   'diversity_euclidean': 0.06413805607661366,
   'diversity_jensenshannon': 0.6174077723201977,
   'diversity_hellinger': 0.7146702985437808,
   'diversity_cosine': 0.7347939170421168,
   'perplexity': 16017.2265625,
   'ppl_fair': 16017.2265625,
   'ppl_cheatty': 3733.1591796875}],
 'bank_topic_scores': [[{'kernel_size': 1676,
    'toplen_ptw': 2.9137328999468073,
    'coherence_20': 1.2508650222621893,
    'distance_to_nearest': 0.0},
   {'kernel_size': 1683,
    'toplen_ptw': 2.390118941026358,
    'coherence_20': 1.180296731842603,
    'distance_to_nearest': 0.8378806766600361},
   {'kernel_size': 1591,
    'toplen_ptw': 3.234490197330379,
    'coherence_20': 0.43910536887445184,
    'distance_to_nearest': 0.8527573519638529}],
  [{'kernel_size': 1676,
    'toplen_ptw': 2.9137328999468073,
    'coherence_20': 1.2508650222621893,
    'distance_to_nearest': 0.0},
   {'kernel_size': 1683,
    'toplen_ptw': 2.390118941026358,
    'coherence_20': 1.180296731842603,
    'distance_to_nearest': 0.8378806766600361},
   {'kernel_size': 1591,
    'toplen_ptw': 3.234490197330379,
    'coherence_20': 0.43910536887445184,
    'distance_to_nearest': 0.8527573519638529}],
  [{'kernel_size': 1676,
    'toplen_ptw': 2.9137328999468073,
    'coherence_20': 1.2508650222621893,
    'distance_to_nearest': 0.0},
   {'kernel_size': 1683,
    'toplen_ptw': 2.390118941026358,
    'coherence_20': 1.180296731842603,
    'distance_to_nearest': 0.8378806766600361},
   {'kernel_size': 1591,
    'toplen_ptw': 3.234490197330379,
    'coherence_20': 0.43910536887445184,
    'distance_to_nearest': 0.8527573519638529}],
  [{'kernel_size': 1676,
    'toplen_ptw': 2.9137328999468073,
    'coherence_20': 1.2508650222621893,
    'distance_to_nearest': 0.0},
   {'kernel_size': 1683,
    'toplen_ptw': 2.390118941026358,
    'coherence_20': 1.180296731842603,
    'distance_to_nearest': 0.8378806766600361},
   {'kernel_size': 1591,
    'toplen_ptw': 3.234490197330379,
    'coherence_20': 0.43910536887445184,
    'distance_to_nearest': 0.8527573519638529},
   {'kernel_size': 1655,
    'toplen_ptw': 2.5314330221922066,
    'coherence_20': 0.44291428766950486,
    'distance_to_nearest': 0.7971954333613831},
   {'kernel_size': 1797,
    'toplen_ptw': 2.5807286388221415,
    'coherence_20': 1.0960977761800366,
    'distance_to_nearest': 0.7677058220180578}],
  [{'kernel_size': 1676,
    'toplen_ptw': 2.9137328999468073,
    'coherence_20': 1.2508650222621893,
    'distance_to_nearest': 0.0},
   {'kernel_size': 1683,
    'toplen_ptw': 2.390118941026358,
    'coherence_20': 1.180296731842603,
    'distance_to_nearest': 0.8378806766600361},
   {'kernel_size': 1591,
    'toplen_ptw': 3.234490197330379,
    'coherence_20': 0.43910536887445184,
    'distance_to_nearest': 0.8527573519638529},
   {'kernel_size': 1655,
    'toplen_ptw': 2.5314330221922066,
    'coherence_20': 0.44291428766950486,
    'distance_to_nearest': 0.7971954333613831},
   {'kernel_size': 1833,
    'toplen_ptw': 2.4189702600089356,
    'coherence_20': 0.6362227983980256,
    'distance_to_nearest': 0.7321468671191989}],
  [{'kernel_size': 1676,
    'toplen_ptw': 2.9137328999468073,
    'coherence_20': 1.2508650222621893,
    'distance_to_nearest': 0.0},
   {'kernel_size': 1683,
    'toplen_ptw': 2.390118941026358,
    'coherence_20': 1.180296731842603,
    'distance_to_nearest': 0.8378806766600361},
   {'kernel_size': 1591,
    'toplen_ptw': 3.234490197330379,
    'coherence_20': 0.43910536887445184,
    'distance_to_nearest': 0.8527573519638529},
   {'kernel_size': 1655,
    'toplen_ptw': 2.5314330221922066,
    'coherence_20': 0.44291428766950486,
    'distance_to_nearest': 0.7971954333613831},
   {'kernel_size': 1833,
    'toplen_ptw': 2.4189702600089356,
    'coherence_20': 0.6362227983980256,
    'distance_to_nearest': 0.7321468671191989}],
  [{'kernel_size': 1676,
    'toplen_ptw': 2.9137328999468073,
    'coherence_20': 1.2508650222621893,
    'distance_to_nearest': 0.0},
   {'kernel_size': 1683,
    'toplen_ptw': 2.390118941026358,
    'coherence_20': 1.180296731842603,
    'distance_to_nearest': 0.8378806766600361},
   {'kernel_size': 1591,
    'toplen_ptw': 3.234490197330379,
    'coherence_20': 0.43910536887445184,
    'distance_to_nearest': 0.8527573519638529},
   {'kernel_size': 1655,
    'toplen_ptw': 2.5314330221922066,
    'coherence_20': 0.44291428766950486,
    'distance_to_nearest': 0.7971954333613831},
   {'kernel_size': 1833,
    'toplen_ptw': 2.4189702600089356,
    'coherence_20': 0.6362227983980256,
    'distance_to_nearest': 0.7321468671191989}],
  [{'kernel_size': 1676,
    'toplen_ptw': 2.9137328999468073,
    'coherence_20': 1.2508650222621893,
    'distance_to_nearest': 0.0},
   {'kernel_size': 1683,
    'toplen_ptw': 2.390118941026358,
    'coherence_20': 1.180296731842603,
    'distance_to_nearest': 0.8378806766600361},
   {'kernel_size': 1591,
    'toplen_ptw': 3.234490197330379,
    'coherence_20': 0.43910536887445184,
    'distance_to_nearest': 0.8527573519638529},
   {'kernel_size': 1655,
    'toplen_ptw': 2.5314330221922066,
    'coherence_20': 0.44291428766950486,
    'distance_to_nearest': 0.7971954333613831},
   {'kernel_size': 1833,
    'toplen_ptw': 2.4189702600089356,
    'coherence_20': 0.6362227983980256,
    'distance_to_nearest': 0.7321468671191989}],
  [{'kernel_size': 1676,
    'toplen_ptw': 2.9137328999468073,
    'coherence_20': 1.2508650222621893,
    'distance_to_nearest': 0.0},
   {'kernel_size': 1683,
    'toplen_ptw': 2.390118941026358,
    'coherence_20': 1.180296731842603,
    'distance_to_nearest': 0.8378806766600361},
   {'kernel_size': 1591,
    'toplen_ptw': 3.234490197330379,
    'coherence_20': 0.43910536887445184,
    'distance_to_nearest': 0.8527573519638529},
   {'kernel_size': 1655,
    'toplen_ptw': 2.5314330221922066,
    'coherence_20': 0.44291428766950486,
    'distance_to_nearest': 0.7971954333613831},
   {'kernel_size': 1833,
    'toplen_ptw': 2.4189702600089356,
    'coherence_20': 0.6362227983980256,
    'distance_to_nearest': 0.7321468671191989}],
  [{'kernel_size': 1676,
    'toplen_ptw': 2.9137328999468073,
    'coherence_20': 1.2508650222621893,
    'distance_to_nearest': 0.0},
   {'kernel_size': 1683,
    'toplen_ptw': 2.390118941026358,
    'coherence_20': 1.180296731842603,
    'distance_to_nearest': 0.8378806766600361},
   {'kernel_size': 1591,
    'toplen_ptw': 3.234490197330379,
    'coherence_20': 0.43910536887445184,
    'distance_to_nearest': 0.8527573519638529},
   {'kernel_size': 1655,
    'toplen_ptw': 2.5314330221922066,
    'coherence_20': 0.44291428766950486,
    'distance_to_nearest': 0.7971954333613831},
   {'kernel_size': 1833,
    'toplen_ptw': 2.4189702600089356,
    'coherence_20': 0.6362227983980256,
    'distance_to_nearest': 0.7321468671191989}],
  [{'kernel_size': 1676,
    'toplen_ptw': 2.9137328999468073,
    'coherence_20': 1.2508650222621893,
    'distance_to_nearest': 0.0},
   {'kernel_size': 1683,
    'toplen_ptw': 2.390118941026358,
    'coherence_20': 1.180296731842603,
    'distance_to_nearest': 0.8378806766600361},
   {'kernel_size': 1591,
    'toplen_ptw': 3.234490197330379,
    'coherence_20': 0.43910536887445184,
    'distance_to_nearest': 0.8527573519638529},
   {'kernel_size': 1655,
    'toplen_ptw': 2.5314330221922066,
    'coherence_20': 0.44291428766950486,
    'distance_to_nearest': 0.7971954333613831},
   {'kernel_size': 1833,
    'toplen_ptw': 2.4189702600089356,
    'coherence_20': 0.6362227983980256,
    'distance_to_nearest': 0.7321468671191989}],
  [{'kernel_size': 1676,
    'toplen_ptw': 2.9137328999468073,
    'coherence_20': 1.2508650222621893,
    'distance_to_nearest': 0.0},
   {'kernel_size': 1683,
    'toplen_ptw': 2.390118941026358,
    'coherence_20': 1.180296731842603,
    'distance_to_nearest': 0.8378806766600361},
   {'kernel_size': 1591,
    'toplen_ptw': 3.234490197330379,
    'coherence_20': 0.43910536887445184,
    'distance_to_nearest': 0.8527573519638529},
   {'kernel_size': 1655,
    'toplen_ptw': 2.5314330221922066,
    'coherence_20': 0.44291428766950486,
    'distance_to_nearest': 0.7971954333613831},
   {'kernel_size': 1833,
    'toplen_ptw': 2.4189702600089356,
    'coherence_20': 0.6362227983980256,
    'distance_to_nearest': 0.7321468671191989}],
  [{'kernel_size': 1683,
    'toplen_ptw': 2.390118941026358,
    'coherence_20': 1.180296731842603,
    'distance_to_nearest': 0.8378806766600361},
   {'kernel_size': 1591,
    'toplen_ptw': 3.234490197330379,
    'coherence_20': 0.43910536887445184,
    'distance_to_nearest': 0.8527573519638529},
   {'kernel_size': 1655,
    'toplen_ptw': 2.5314330221922066,
    'coherence_20': 0.44291428766950486,
    'distance_to_nearest': 0.7971954333613831},
   {'kernel_size': 1833,
    'toplen_ptw': 2.4189702600089356,
    'coherence_20': 0.6362227983980256,
    'distance_to_nearest': 0.7321468671191989},
   {'kernel_size': 1981,
    'toplen_ptw': 3.008296869976122,
    'coherence_20': 0.931885135272484,
    'distance_to_nearest': 0.693357496447894},
   {'kernel_size': 1964,
    'toplen_ptw': 3.044553735842425,
    'coherence_20': 0.7388289391437444,
    'distance_to_nearest': 0.7923110101381673}],
  [{'kernel_size': 1683,
    'toplen_ptw': 2.390118941026358,
    'coherence_20': 1.180296731842603,
    'distance_to_nearest': 0.8378806766600361},
   {'kernel_size': 1591,
    'toplen_ptw': 3.234490197330379,
    'coherence_20': 0.43910536887445184,
    'distance_to_nearest': 0.8527573519638529},
   {'kernel_size': 1655,
    'toplen_ptw': 2.5314330221922066,
    'coherence_20': 0.44291428766950486,
    'distance_to_nearest': 0.7971954333613831},
   {'kernel_size': 1833,
    'toplen_ptw': 2.4189702600089356,
    'coherence_20': 0.6362227983980256,
    'distance_to_nearest': 0.7321468671191989},
   {'kernel_size': 1981,
    'toplen_ptw': 3.008296869976122,
    'coherence_20': 0.931885135272484,
    'distance_to_nearest': 0.693357496447894},
   {'kernel_size': 1964,
    'toplen_ptw': 3.044553735842425,
    'coherence_20': 0.7388289391437444,
    'distance_to_nearest': 0.7923110101381673}],
  [{'kernel_size': 1683,
    'toplen_ptw': 2.390118941026358,
    'coherence_20': 1.180296731842603,
    'distance_to_nearest': 0.8378806766600361},
   {'kernel_size': 1591,
    'toplen_ptw': 3.234490197330379,
    'coherence_20': 0.43910536887445184,
    'distance_to_nearest': 0.8527573519638529},
   {'kernel_size': 1655,
    'toplen_ptw': 2.5314330221922066,
    'coherence_20': 0.44291428766950486,
    'distance_to_nearest': 0.7971954333613831},
   {'kernel_size': 1833,
    'toplen_ptw': 2.4189702600089356,
    'coherence_20': 0.6362227983980256,
    'distance_to_nearest': 0.7321468671191989},
   {'kernel_size': 1981,
    'toplen_ptw': 3.008296869976122,
    'coherence_20': 0.931885135272484,
    'distance_to_nearest': 0.693357496447894},
   {'kernel_size': 1964,
    'toplen_ptw': 3.044553735842425,
    'coherence_20': 0.7388289391437444,
    'distance_to_nearest': 0.7923110101381673}],
  [{'kernel_size': 1683,
    'toplen_ptw': 2.390118941026358,
    'coherence_20': 1.180296731842603,
    'distance_to_nearest': 0.8378806766600361},
   {'kernel_size': 1591,
    'toplen_ptw': 3.234490197330379,
    'coherence_20': 0.43910536887445184,
    'distance_to_nearest': 0.8527573519638529},
   {'kernel_size': 1655,
    'toplen_ptw': 2.5314330221922066,
    'coherence_20': 0.44291428766950486,
    'distance_to_nearest': 0.7971954333613831},
   {'kernel_size': 1833,
    'toplen_ptw': 2.4189702600089356,
    'coherence_20': 0.6362227983980256,
    'distance_to_nearest': 0.7321468671191989},
   {'kernel_size': 1981,
    'toplen_ptw': 3.008296869976122,
    'coherence_20': 0.931885135272484,
    'distance_to_nearest': 0.693357496447894},
   {'kernel_size': 1964,
    'toplen_ptw': 3.044553735842425,
    'coherence_20': 0.7388289391437444,
    'distance_to_nearest': 0.7923110101381673}],
  [{'kernel_size': 1683,
    'toplen_ptw': 2.390118941026358,
    'coherence_20': 1.180296731842603,
    'distance_to_nearest': 0.8378806766600361},
   {'kernel_size': 1591,
    'toplen_ptw': 3.234490197330379,
    'coherence_20': 0.43910536887445184,
    'distance_to_nearest': 0.8527573519638529},
   {'kernel_size': 1655,
    'toplen_ptw': 2.5314330221922066,
    'coherence_20': 0.44291428766950486,
    'distance_to_nearest': 0.7971954333613831},
   {'kernel_size': 1833,
    'toplen_ptw': 2.4189702600089356,
    'coherence_20': 0.6362227983980256,
    'distance_to_nearest': 0.7321468671191989},
   {'kernel_size': 1981,
    'toplen_ptw': 3.008296869976122,
    'coherence_20': 0.931885135272484,
    'distance_to_nearest': 0.693357496447894},
   {'kernel_size': 1964,
    'toplen_ptw': 3.044553735842425,
    'coherence_20': 0.7388289391437444,
    'distance_to_nearest': 0.7923110101381673}],
  [{'kernel_size': 1683,
    'toplen_ptw': 2.390118941026358,
    'coherence_20': 1.180296731842603,
    'distance_to_nearest': 0.8378806766600361},
   {'kernel_size': 1591,

In [94]:
len(optimizer._result['bank_topic_scores'])

20

In [95]:
[len(s) for s in optimizer._result['bank_topic_scores']]

[3, 3, 3, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6]

In [96]:
optimizer._result['bank_topic_scores']

[[{'kernel_size': 1676,
   'toplen_ptw': 2.9137328999468073,
   'coherence_20': 1.2508650222621893,
   'distance_to_nearest': 0.0},
  {'kernel_size': 1683,
   'toplen_ptw': 2.390118941026358,
   'coherence_20': 1.180296731842603,
   'distance_to_nearest': 0.8378806766600361},
  {'kernel_size': 1591,
   'toplen_ptw': 3.234490197330379,
   'coherence_20': 0.43910536887445184,
   'distance_to_nearest': 0.8527573519638529}],
 [{'kernel_size': 1676,
   'toplen_ptw': 2.9137328999468073,
   'coherence_20': 1.2508650222621893,
   'distance_to_nearest': 0.0},
  {'kernel_size': 1683,
   'toplen_ptw': 2.390118941026358,
   'coherence_20': 1.180296731842603,
   'distance_to_nearest': 0.8378806766600361},
  {'kernel_size': 1591,
   'toplen_ptw': 3.234490197330379,
   'coherence_20': 0.43910536887445184,
   'distance_to_nearest': 0.8527573519638529}],
 [{'kernel_size': 1676,
   'toplen_ptw': 2.9137328999468073,
   'coherence_20': 1.2508650222621893,
   'distance_to_nearest': 0.0},
  {'kernel_size': 1683,
   'toplen_ptw': 2.390118941026358,
   'coherence_20': 1.180296731842603,
   'distance_to_nearest': 0.8378806766600361},
  {'kernel_size': 1591,
   'toplen_ptw': 3.234490197330379,
   'coherence_20': 0.43910536887445184,
   'distance_to_nearest': 0.8527573519638529}],
 [{'kernel_size': 1676,
   'toplen_ptw': 2.9137328999468073,
   'coherence_20': 1.2508650222621893,
   'distance_to_nearest': 0.0},
  {'kernel_size': 1683,
   'toplen_ptw': 2.390118941026358,
   'coherence_20': 1.180296731842603,
   'distance_to_nearest': 0.8378806766600361},
  {'kernel_size': 1591,
   'toplen_ptw': 3.234490197330379,
   'coherence_20': 0.43910536887445184,
   'distance_to_nearest': 0.8527573519638529},
  {'kernel_size': 1655,
   'toplen_ptw': 2.5314330221922066,
   'coherence_20': 0.44291428766950486,
   'distance_to_nearest': 0.7971954333613831},
  {'kernel_size': 1797,
   'toplen_ptw': 2.5807286388221415,
   'coherence_20': 1.0960977761800366,
   'distance_to_nearest': 0.7677058220180578}],
 [{'kernel_size': 1676,
   'toplen_ptw': 2.9137328999468073,
   'coherence_20': 1.2508650222621893,
   'distance_to_nearest': 0.0},
  {'kernel_size': 1683,
   'toplen_ptw': 2.390118941026358,
   'coherence_20': 1.180296731842603,
   'distance_to_nearest': 0.8378806766600361},
  {'kernel_size': 1591,
   'toplen_ptw': 3.234490197330379,
   'coherence_20': 0.43910536887445184,
   'distance_to_nearest': 0.8527573519638529},
  {'kernel_size': 1655,
   'toplen_ptw': 2.5314330221922066,
   'coherence_20': 0.44291428766950486,
   'distance_to_nearest': 0.7971954333613831},
  {'kernel_size': 1833,
   'toplen_ptw': 2.4189702600089356,
   'coherence_20': 0.6362227983980256,
   'distance_to_nearest': 0.7321468671191989}],
 [{'kernel_size': 1676,
   'toplen_ptw': 2.9137328999468073,
   'coherence_20': 1.2508650222621893,
   'distance_to_nearest': 0.0},
  {'kernel_size': 1683,
   'toplen_ptw': 2.390118941026358,
   'coherence_20': 1.180296731842603,
   'distance_to_nearest': 0.8378806766600361},
  {'kernel_size': 1591,
   'toplen_ptw': 3.234490197330379,
   'coherence_20': 0.43910536887445184,
   'distance_to_nearest': 0.8527573519638529},
  {'kernel_size': 1655,
   'toplen_ptw': 2.5314330221922066,
   'coherence_20': 0.44291428766950486,
   'distance_to_nearest': 0.7971954333613831},
  {'kernel_size': 1833,
   'toplen_ptw': 2.4189702600089356,
   'coherence_20': 0.6362227983980256,
   'distance_to_nearest': 0.7321468671191989}],
 [{'kernel_size': 1676,
   'toplen_ptw': 2.9137328999468073,
   'coherence_20': 1.2508650222621893,
   'distance_to_nearest': 0.0},
  {'kernel_size': 1683,
   'toplen_ptw': 2.390118941026358,
   'coherence_20': 1.180296731842603,
   'distance_to_nearest': 0.8378806766600361},
  {'kernel_size': 1591,
   'toplen_ptw': 3.234490197330379,
   'coherence_20': 0.43910536887445184,
   'distance_to_nearest': 0.8527573519638529},
  {'kernel_size': 1655,
   'toplen_ptw': 2.5314330221922066,
   'coherence_20': 0.44291428766950486,
   'distance_to_nearest': 0.7971954333613831},
  {'kernel_size': 1833,
   'toplen_ptw': 2.4189702600089356,
   'coherence_20': 0.6362227983980256,
   'distance_to_nearest': 0.7321468671191989}],
 [{'kernel_size': 1676,
   'toplen_ptw': 2.9137328999468073,
   'coherence_20': 1.2508650222621893,
   'distance_to_nearest': 0.0},
  {'kernel_size': 1683,
   'toplen_ptw': 2.390118941026358,
   'coherence_20': 1.180296731842603,
   'distance_to_nearest': 0.8378806766600361},
  {'kernel_size': 1591,
   'toplen_ptw': 3.234490197330379,
   'coherence_20': 0.43910536887445184,
   'distance_to_nearest': 0.8527573519638529},
  {'kernel_size': 1655,
   'toplen_ptw': 2.5314330221922066,
   'coherence_20': 0.44291428766950486,
   'distance_to_nearest': 0.7971954333613831},
  {'kernel_size': 1833,
   'toplen_ptw': 2.4189702600089356,
   'coherence_20': 0.6362227983980256,
   'distance_to_nearest': 0.7321468671191989}],
 [{'kernel_size': 1676,
   'toplen_ptw': 2.9137328999468073,
   'coherence_20': 1.2508650222621893,
   'distance_to_nearest': 0.0},
  {'kernel_size': 1683,
   'toplen_ptw': 2.390118941026358,
   'coherence_20': 1.180296731842603,
   'distance_to_nearest': 0.8378806766600361},
  {'kernel_size': 1591,
   'toplen_ptw': 3.234490197330379,
   'coherence_20': 0.43910536887445184,
   'distance_to_nearest': 0.8527573519638529},
  {'kernel_size': 1655,
   'toplen_ptw': 2.5314330221922066,
   'coherence_20': 0.44291428766950486,
   'distance_to_nearest': 0.7971954333613831},
  {'kernel_size': 1833,
   'toplen_ptw': 2.4189702600089356,
   'coherence_20': 0.6362227983980256,
   'distance_to_nearest': 0.7321468671191989}],
 [{'kernel_size': 1676,
   'toplen_ptw': 2.9137328999468073,
   'coherence_20': 1.2508650222621893,
   'distance_to_nearest': 0.0},
  {'kernel_size': 1683,
   'toplen_ptw': 2.390118941026358,
   'coherence_20': 1.180296731842603,
   'distance_to_nearest': 0.8378806766600361},
  {'kernel_size': 1591,
   'toplen_ptw': 3.234490197330379,
   'coherence_20': 0.43910536887445184,
   'distance_to_nearest': 0.8527573519638529},
  {'kernel_size': 1655,
   'toplen_ptw': 2.5314330221922066,
   'coherence_20': 0.44291428766950486,
   'distance_to_nearest': 0.7971954333613831},
  {'kernel_size': 1833,
   'toplen_ptw': 2.4189702600089356,
   'coherence_20': 0.6362227983980256,
   'distance_to_nearest': 0.7321468671191989}],
 [{'kernel_size': 1676,
   'toplen_ptw': 2.9137328999468073,
   'coherence_20': 1.2508650222621893,
   'distance_to_nearest': 0.0},
  {'kernel_size': 1683,
   'toplen_ptw': 2.390118941026358,
   'coherence_20': 1.180296731842603,
   'distance_to_nearest': 0.8378806766600361},
  {'kernel_size': 1591,
   'toplen_ptw': 3.234490197330379,
   'coherence_20': 0.43910536887445184,
   'distance_to_nearest': 0.8527573519638529},
  {'kernel_size': 1655,
   'toplen_ptw': 2.5314330221922066,
   'coherence_20': 0.44291428766950486,
   'distance_to_nearest': 0.7971954333613831},
  {'kernel_size': 1833,
   'toplen_ptw': 2.4189702600089356,
   'coherence_20': 0.6362227983980256,
   'distance_to_nearest': 0.7321468671191989}],
 [{'kernel_size': 1676,
   'toplen_ptw': 2.9137328999468073,
   'coherence_20': 1.2508650222621893,
   'distance_to_nearest': 0.0},
  {'kernel_size': 1683,
   'toplen_ptw': 2.390118941026358,
   'coherence_20': 1.180296731842603,
   'distance_to_nearest': 0.8378806766600361},
  {'kernel_size': 1591,
   'toplen_ptw': 3.234490197330379,
   'coherence_20': 0.43910536887445184,
   'distance_to_nearest': 0.8527573519638529},
  {'kernel_size': 1655,
   'toplen_ptw': 2.5314330221922066,
   'coherence_20': 0.44291428766950486,
   'distance_to_nearest': 0.7971954333613831},
  {'kernel_size': 1833,
   'toplen_ptw': 2.4189702600089356,
   'coherence_20': 0.6362227983980256,
   'distance_to_nearest': 0.7321468671191989}],
 [{'kernel_size': 1683,
   'toplen_ptw': 2.390118941026358,
   'coherence_20': 1.180296731842603,
   'distance_to_nearest': 0.8378806766600361},
  {'kernel_size': 1591,
   'toplen_ptw': 3.234490197330379,
   'coherence_20': 0.43910536887445184,
   'distance_to_nearest': 0.8527573519638529},
  {'kernel_size': 1655,
   'toplen_ptw': 2.5314330221922066,
   'coherence_20': 0.44291428766950486,
   'distance_to_nearest': 0.7971954333613831},
  {'kernel_size': 1833,
   'toplen_ptw': 2.4189702600089356,
   'coherence_20': 0.6362227983980256,
   'distance_to_nearest': 0.7321468671191989},
  {'kernel_size': 1981,
   'toplen_ptw': 3.008296869976122,
   'coherence_20': 0.931885135272484,
   'distance_to_nearest': 0.693357496447894},
  {'kernel_size': 1964,
   'toplen_ptw': 3.044553735842425,
   'coherence_20': 0.7388289391437444,
   'distance_to_nearest': 0.7923110101381673}],
 [{'kernel_size': 1683,
   'toplen_ptw': 2.390118941026358,
   'coherence_20': 1.180296731842603,
   'distance_to_nearest': 0.8378806766600361},
  {'kernel_size': 1591,
   'toplen_ptw': 3.234490197330379,
   'coherence_20': 0.43910536887445184,
   'distance_to_nearest': 0.8527573519638529},
  {'kernel_size': 1655,
   'toplen_ptw': 2.5314330221922066,
   'coherence_20': 0.44291428766950486,
   'distance_to_nearest': 0.7971954333613831},
  {'kernel_size': 1833,
   'toplen_ptw': 2.4189702600089356,
   'coherence_20': 0.6362227983980256,
   'distance_to_nearest': 0.7321468671191989},
  {'kernel_size': 1981,
   'toplen_ptw': 3.008296869976122,
   'coherence_20': 0.931885135272484,
   'distance_to_nearest': 0.693357496447894},
  {'kernel_size': 1964,
   'toplen_ptw': 3.044553735842425,
   'coherence_20': 0.7388289391437444,
   'distance_to_nearest': 0.7923110101381673}],
 [{'kernel_size': 1683,
   'toplen_ptw': 2.390118941026358,
   'coherence_20': 1.180296731842603,
   'distance_to_nearest': 0.8378806766600361},
  {'kernel_size': 1591,
   'toplen_ptw': 3.234490197330379,
   'coherence_20': 0.43910536887445184,
   'distance_to_nearest': 0.8527573519638529},
  {'kernel_size': 1655,
   'toplen_ptw': 2.5314330221922066,
   'coherence_20': 0.44291428766950486,
   'distance_to_nearest': 0.7971954333613831},
  {'kernel_size': 1833,
   'toplen_ptw': 2.4189702600089356,
   'coherence_20': 0.6362227983980256,
   'distance_to_nearest': 0.7321468671191989},
  {'kernel_size': 1981,
   'toplen_ptw': 3.008296869976122,
   'coherence_20': 0.931885135272484,
   'distance_to_nearest': 0.693357496447894},
  {'kernel_size': 1964,
   'toplen_ptw': 3.044553735842425,
   'coherence_20': 0.7388289391437444,
   'distance_to_nearest': 0.7923110101381673}],
 [{'kernel_size': 1683,
   'toplen_ptw': 2.390118941026358,
   'coherence_20': 1.180296731842603,
   'distance_to_nearest': 0.8378806766600361},
  {'kernel_size': 1591,
   'toplen_ptw': 3.234490197330379,
   'coherence_20': 0.43910536887445184,
   'distance_to_nearest': 0.8527573519638529},
  {'kernel_size': 1655,
   'toplen_ptw': 2.5314330221922066,
   'coherence_20': 0.44291428766950486,
   'distance_to_nearest': 0.7971954333613831},
  {'kernel_size': 1833,
   'toplen_ptw': 2.4189702600089356,
   'coherence_20': 0.6362227983980256,
   'distance_to_nearest': 0.7321468671191989},
  {'kernel_size': 1981,
   'toplen_ptw': 3.008296869976122,
   'coherence_20': 0.931885135272484,
   'distance_to_nearest': 0.693357496447894},
  {'kernel_size': 1964,
   'toplen_ptw': 3.044553735842425,
   'coherence_20': 0.7388289391437444,
   'distance_to_nearest': 0.7923110101381673}],
 [{'kernel_size': 1683,
   'toplen_ptw': 2.390118941026358,
   'coherence_20': 1.180296731842603,
   'distance_to_nearest': 0.8378806766600361},
  {'kernel_size': 1591,
   'toplen_ptw': 3.234490197330379,
   'coherence_20': 0.43910536887445184,
   'distance_to_nearest': 0.8527573519638529},
  {'kernel_size': 1655,
   'toplen_ptw': 2.5314330221922066,
   'coherence_20': 0.44291428766950486,
   'distance_to_nearest': 0.7971954333613831},
  {'kernel_size': 1833,
   'toplen_ptw': 2.4189702600089356,
   'coherence_20': 0.6362227983980256,
   'distance_to_nearest': 0.7321468671191989},
  {'kernel_size': 1981,
   'toplen_ptw': 3.008296869976122,
   'coherence_20': 0.931885135272484,
   'distance_to_nearest': 0.693357496447894},
  {'kernel_size': 1964,
   'toplen_ptw': 3.044553735842425,
   'coherence_20': 0.7388289391437444,
   'distance_to_nearest': 0.7923110101381673}],
 [{'kernel_size': 1683,
   'toplen_ptw': 2.390118941026358,
   'coherence_20': 1.180296731842603,
   'distance_to_nearest': 0.8378806766600361},
  {'kernel_size': 1591,
   'toplen_ptw': 3.234490197330379,
   'coherence_20': 0.43910536887445184,
   'distance_to_nearest': 0.8527573519638529},
  {'kernel_size': 1655,
   'toplen_ptw': 2.5314330221922066,
   'coherence_20': 0.44291428766950486,
   'distance_to_nearest': 0.7971954333613831},
  {'kernel_size': 1833,
   'toplen_ptw': 2.4189702600089356,
   'coherence_20': 0.6362227983980256,
   'distance_to_nearest': 0.7321468671191989},
  {'kernel_size': 1981,
   'toplen_ptw': 3.008296869976122,
   'coherence_20': 0.931885135272484,
   'distance_to_nearest': 0.693357496447894},
  {'kernel_size': 1964,
   'toplen_ptw': 3.044553735842425,
   'coherence_20': 0.7388289391437444,
   'distance_to_nearest': 0.7923110101381673}],
 [{'kernel_size': 1683,
   'toplen_ptw': 2.390118941026358,
   'coherence_20': 1.180296731842603,
   'distance_to_nearest': 0.8378806766600361},
  {'kernel_size': 1591,
   'toplen_ptw': 3.234490197330379,
   'coherence_20': 0.43910536887445184,
   'distance_to_nearest': 0.8527573519638529},
  {'kernel_size': 1655,
   'toplen_ptw': 2.5314330221922066,
   'coherence_20': 0.44291428766950486,
   'distance_to_nearest': 0.7971954333613831},
  {'kernel_size': 1833,
   'toplen_ptw': 2.4189702600089356,
   'coherence_20': 0.6362227983980256,
   'distance_to_nearest': 0.7321468671191989},
  {'kernel_size': 1981,
   'toplen_ptw': 3.008296869976122,
   'coherence_20': 0.931885135272484,
   'distance_to_nearest': 0.693357496447894},
  {'kernel_size': 1964,
   'toplen_ptw': 3.044553735842425,
   'coherence_20': 0.7388289391437444,
   'distance_to_nearest': 0.7923110101381673}],
 [{'kernel_size': 1683,
   'toplen_ptw': 2.390118941026358,
   'coherence_20': 1.180296731842603,
   'distance_to_nearest': 0.8378806766600361},
  {'kernel_size': 1591,
   'toplen_ptw': 3.234490197330379,
   'coherence_20': 0.43910536887445184,
   'distance_to_nearest': 0.8527573519638529},
  {'kernel_size': 1655,
   'toplen_ptw': 2.5314330221922066,
   'coherence_20': 0.44291428766950486,
   'distance_to_nearest': 0.7971954333613831},
  {'kernel_size': 1833,
   'toplen_ptw': 2.4189702600089356,
   'coherence_20': 0.6362227983980256,
   'distance_to_nearest': 0.7321468671191989},
  {'kernel_size': 1981,
   'toplen_ptw': 3.008296869976122,
   'coherence_20': 0.931885135272484,
   'distance_to_nearest': 0.693357496447894},
  {'kernel_size': 1964,
   'toplen_ptw': 3.044553735842425,
   'coherence_20': 0.7388289391437444,
   'distance_to_nearest': 0.7923110101381673}]]

In [97]:
optimizer._result['model_scores'][0]

{'perplexity_score': 2774.172119140625,
 'coherence_20': 0.7917501820424284,
 'diversity_euclidean': 0.0697766256356419,
 'diversity_jensenshannon': 0.6568446692721249,
 'diversity_hellinger': 0.7646332792232048,
 'diversity_cosine': 0.811718425985906,
 'perplexity': 2774.172119140625,
 'toplen_ptw': 2.0139480500213662}

In [98]:
sum(s['coherence_20'] for s in optimizer._result['bank_topic_scores'][-1]) / 14

0.3120895186572009

In [99]:
len(optimizer._result['bank_scores'])

20

In [100]:
optimizer._result['bank_scores'][-1]

{'perplexity_score': 16017.2265625,
 'coherence_20': 0.7282088768668022,
 'diversity_euclidean': 0.06413805607661366,
 'diversity_jensenshannon': 0.6174077723201977,
 'diversity_hellinger': 0.7146702985437808,
 'diversity_cosine': 0.7347939170421168,
 'perplexity': 16017.2265625,
 'ppl_fair': 16017.2265625,
 'ppl_cheatty': 3733.1591796875}

In [101]:
optimizer._result['model_topic_scores']

[[{'kernel_size': 1994,
   'toplen_ptw': 2.0103522136784897,
   'coherence_20': 0.5030885868011427},
  {'kernel_size': 2247,
   'toplen_ptw': 2.1518301958752915,
   'coherence_20': 0.5542258711717113},
  {'kernel_size': 1727,
   'toplen_ptw': 2.111886926248693,
   'coherence_20': 0.46083629281021266},
  {'kernel_size': 2437,
   'toplen_ptw': 1.9120912737809934,
   'coherence_20': 0.7784617214308792},
  {'kernel_size': 2092,
   'toplen_ptw': 2.053203908557405,
   'coherence_20': 0.6874723289012623},
  {'kernel_size': 1676,
   'toplen_ptw': 2.9137328999468073,
   'coherence_20': 1.2508650222621893,
   'distance_to_nearest': 0.0},
  {'kernel_size': 1924,
   'toplen_ptw': 1.7453635506232241,
   'coherence_20': 0.765747875827312},
  {'kernel_size': 1916,
   'toplen_ptw': 1.6741463062821191,
   'coherence_20': 0.7355746840071614},
  {'kernel_size': 2123,
   'toplen_ptw': 2.0139480500213662,
   'coherence_20': 0.8050386426539775},
  {'kernel_size': 2528,
   'toplen_ptw': 1.877373249189409,
   'coherence_20': 0.8074832951131057},
  {'kernel_size': 2165,
   'toplen_ptw': 1.8258875214665433,
   'coherence_20': 0.5114946189954674},
  {'kernel_size': 1503,
   'toplen_ptw': 2.171944959412385,
   'coherence_20': 1.4230164281743303},
  {'kernel_size': 2509,
   'toplen_ptw': 1.8563396719736374,
   'coherence_20': 1.1406572844959169},
  {'kernel_size': 1923,
   'toplen_ptw': 1.9532594735676392,
   'coherence_20': 0.9206501725778948},
  {'kernel_size': 1889,
   'toplen_ptw': 1.9823277716494796,
   'coherence_20': 0.5694339201692713},
  {'kernel_size': 2197,
   'toplen_ptw': 2.0355448954908963,
   'coherence_20': 0.915493440556285},
  {'kernel_size': 1683,
   'toplen_ptw': 2.390118941026358,
   'coherence_20': 1.180296731842603,
   'distance_to_nearest': 0.8378806766600361},
  {'kernel_size': 1725,
   'toplen_ptw': 2.0922677981912776,
   'coherence_20': 0.8075261132335527},
  {'kernel_size': 1770,
   'toplen_ptw': 2.013559235257661,
   'coherence_20': 0.868654029615445},
  {'kernel_size': 1591,
   'toplen_ptw': 3.234490197330379,
   'coherence_20': 0.43910536887445184,
   'distance_to_nearest': 0.8527573519638529}],
 [{'kernel_size': 1670,
   'toplen_ptw': 2.3925222447200833,
   'coherence_20': 1.4956720326002504},
  {'kernel_size': 1942,
   'toplen_ptw': 2.1634293400821507,
   'coherence_20': 0.6224321645152805},
  {'kernel_size': 1831,
   'toplen_ptw': 2.056983646451773,
   'coherence_20': 0.7644557910064511},
  {'kernel_size': 1991,
   'toplen_ptw': 1.8082648103697558,
   'coherence_20': 0.5166356190801648},
  {'kernel_size': 1918,
   'toplen_ptw': 1.7875011847405415,
   'coherence_20': 0.60109712779559},
  {'kernel_size': 1736,
   'toplen_ptw': 3.2265986439706724,
   'coherence_20': 0.38202773585391775},
  {'kernel_size': 1937,
   'toplen_ptw': 1.7699708181952847,
   'coherence_20': 0.447936082641748},
  {'kernel_size': 2227,
   'toplen_ptw': 1.8684101120288938,
   'coherence_20': 0.8519537541004771},
  {'kernel_size': 1960,
   'toplen_ptw': 2.2264600084551294,
   'coherence_20': 0.5282651536885317},
  {'kernel_size': 2485,
   'toplen_ptw': 1.8397718461185335,
   'coherence_20': 0.6910176866653678},
  {'kernel_size': 2228,
   'toplen_ptw': 1.7013202635799998,
   'coherence_20': 0.8846163310236639},
  {'kernel_size': 2046,
   'toplen_ptw': 1.838835808750561,
   'coherence_20': 0.6949047557973493},
  {'kernel_size': 2393,
   'toplen_ptw': 2.026816839833403,
   'coherence_20': 0.44074938187794893},
  {'kernel_size': 2068,
   'toplen_ptw': 1.8438211670461768,
   'coherence_20': 0.6291995595083893},
  {'kernel_size': 1876,
   'toplen_ptw': 3.217138948096303,
   'coherence_20': 1.2638018897281007},
  {'kernel_size': 1862,
   'toplen_ptw': 2.2891203704606777,
   'coherence_20': 1.0290901648714972},
  {'kernel_size': 2677,
   'toplen_ptw': 1.8613682968504115,
   'coherence_20': 0.8209982385059637},
  {'kernel_size': 1575,
   'toplen_ptw': 1.858207458316498,
   'coherence_20': 1.143620075536856},
  {'kernel_size': 2018,
   'toplen_ptw': 2.1672586050339873,
   'coherence_20': 0.5915346564580787},
  {'kernel_size': 1810,
   'toplen_ptw': 2.0891123447769453,
   'coherence_20': 0.7847601806612766}],
 [{'kernel_size': 2067,
   'toplen_ptw': 2.511231370828444,
   'coherence_20': 0.448754849792106},
  {'kernel_size': 1671,
   'toplen_ptw': 2.036465414674727,
   'coherence_20': 0.7920771558652627},
  {'kernel_size': 2330,
   'toplen_ptw': 2.095290558911173,
   'coherence_20': 0.8706241291846439},
  {'kernel_size': 2033,
   'toplen_ptw': 2.2393209109843197,
   'coherence_20': 0.43629879579059966},
  {'kernel_size': 2087,
   'toplen_ptw': 1.8026227950073959,
   'coherence_20': 0.5849198513950984},
  {'kernel_size': 2225,
   'toplen_ptw': 1.7219141775203648,
   'coherence_20': 0.855723983587484},
  {'kernel_size': 1963,
   'toplen_ptw': 2.1964140435366977,
   'coherence_20': 0.5987468881849466},
  {'kernel_size': 1696,
   'toplen_ptw': 1.9701108020441425,
   'coherence_20': 0.8282273177326441},
  {'kernel_size': 1851,
   'toplen_ptw': 1.8842384430974066,
   'coherence_20': 0.5012940653589399},
  {'kernel_size': 2285,
   'toplen_ptw': 1.6959351299622858,
   'coherence_20': 0.8257762028854446},
  {'kernel_size': 1818,
   'toplen_ptw': 1.8565121736975632,
   'coherence_20': 0.5348136792521453},
  {'kernel_size': 1905,
   'toplen_ptw': 2.146543730884036,
   'coherence_20': 0.7847601806612766},
  {'kernel_size': 2444,
   'toplen_ptw': 2.089171158422543,
   'coherence_20': 0.7158100131425837},
  {'kernel_size': 1595,
   'toplen_ptw': 2.701837189478643,
   'coherence_20': 1.2077964881010124},
  {'kernel_size': 2399,
   'toplen_ptw': 1.8403971524524672,
   'coherence_20': 1.0929768105316378},
  {'kernel_size': 2303,
   'toplen_ptw': 2.1368689929977798,
   'coherence_20': 0.6538596545750571},
  {'kernel_size': 2121,
   'toplen_ptw': 1.7767650255848626,
   'coherence_20': 0.5160996597047304},
  {'kernel_size': 1734,
   'toplen_ptw': 1.7639189954731007,
   'coherence_20': 1.255248243797851},
  {'kernel_size': 1845,
   'toplen_ptw': 2.3336035096014074,
   'coherence_20': 0.4046955199822677},
  {'kernel_size': 1910,
   'toplen_ptw': 2.5888823239843295,
   'coherence_20': 1.0609143681675686}],
 [{'kernel_size': 2074,
   'toplen_ptw': 2.07449158507087,
   'coherence_20': 0.7017284948237033},
  {'kernel_size': 2019,
   'toplen_ptw': 2.0426562088688645,
   'coherence_20': 0.691799790980106},
  {'kernel_size': 2061,
   'toplen_ptw': 1.7668990384291243,
   'coherence_20': 0.8106710795285025},
  {'kernel_size': 2250,
   'toplen_ptw': 1.7752985138481614,
   'coherence_20': 0.6044054706158458},
  {'kernel_size': 2077,
   'toplen_ptw': 1.784602897435866,
   'coherence_20': 0.6043488471123254},
  {'kernel_size': 1670,
   'toplen_ptw': 2.6400308547707767,
   'coherence_20': 0.42620159344431824},
  {'kernel_size': 2496,
   'toplen_ptw': 1.7426100374667053,
   'coherence_20': 0.6034416642985151},
  {'kernel_size': 1809,
   'toplen_ptw': 1.9601682181456532,
   'coherence_20': 0.6496830595307124},
  {'kernel_size': 1824,
   'toplen_ptw': 2.5779931293018437,
   'coherence_20': 1.2684661617682425},
  {'kernel_size': 1816,
   'toplen_ptw': 1.95455328845928,
   'coherence_20': 0.6636101839904354},
  {'kernel_size': 2188,
   'toplen_ptw': 1.689653666860239,
   'coherence_20': 0.5418867824783645},
  {'kernel_size': 2132,
   'toplen_ptw': 2.0453393455111346,
   'coherence_20': 0.5710610995795833},
  {'kernel_size': 2182,
   'toplen_ptw': 1.8484830347849144,
   'coherence_20': 0.8796152294329449},
  {'kernel_size': 1888,
   'toplen_ptw': 2.045241642740371,
   'coherence_20': 0.7908219657183452},
  {'kernel_size': 2498,
   'toplen_ptw': 1.8933790476366146,
   'coherence_20': 0.5532741239543904},
  {'kernel_size': 1655,
   'toplen_ptw': 2.5314330221922066,
   'coherence_20': 0.44291428766950486,
   'distance_to_nearest': 0.7971954333613831},
  {'kernel_size': 2469,
   'toplen_ptw': 2.0644253072293846,
   'coherence_20': 1.0164407674612512},
  {'kernel_size': 1888,
   'toplen_ptw': 2.228717129374876,
   'coherence_20': 0.7847601806612766},
  {'kernel_size': 1807,
   'toplen_ptw': 2.393237201285678,
   'coherence_20': 0.924113223693337},
  {'kernel_size': 1797,
   'toplen_ptw': 2.5807286388221415,
   'coherence_20': 1.0960977761800366,
   'distance_to_nearest': 0.7677058220180578}],
 [{'kernel_size': 2124,
   'toplen_ptw': 1.8946039183044223,
   'coherence_20': 0.6743083022026773},
  {'kernel_size': 1932,
   'toplen_ptw': 1.8429832198159057,
   'coherence_20': 0.5936933677051615},
  {'kernel_size': 2443,
   'toplen_ptw': 2.126914201263218,
   'coherence_20': 0.8451612688741172},
  {'kernel_size': 1843,
   'toplen_ptw': 2.412088752602196,
   'coherence_20': 1.1680687720793599},
  {'kernel_size': 2027,
   'toplen_ptw': 2.561750060219788,
   'coherence_20': 0.3997708977715089},
  {'kernel_size': 1783,
   'toplen_ptw': 1.7947800319809932,
   'coherence_20': 0.6140625402905662},
  {'kernel_size': 1945,
   'toplen_ptw': 2.1730231779958586,
   'coherence_20': 0.6778936844684429},
  {'kernel_size': 2048,
   'toplen_ptw': 1.9360968258100344,
   'coherence_20': 0.41995834475641575},
  {'kernel_size': 2053,
   'toplen_ptw': 1.6451237553999198,
   'coherence_20': 0.893308655092847},
  {'kernel_size': 2156,
   'toplen_ptw': 1.9274262770234112,
   'coherence_20': 0.555243550943771},
  {'kernel_size': 1833,
   'toplen_ptw': 2.4189702600089356,
   'coherence_20': 0.6362227983980256,
   'distance_to_nearest': 0.7321468671191989},
  {'kernel_size': 1646,
   'toplen_ptw': 2.013623181731799,
   'coherence_20': 1.117538939397475},
  {'kernel_size': 1937,
   'toplen_ptw': 1.9945914965453595,
   'coherence_20': 0.7214962892539333},
  {'kernel_size': 2495,
   'toplen_ptw': 1.9499104888192602,
   'coherence_20': 1.0023328300629422},
  {'kernel_size': 1897,
   'toplen_ptw': 2.337633045924109,
   'coherence_20': 0.4899510573195033},
  {'kernel_size': 2202,
   'toplen_ptw': 1.8916287996690466,
   'coherence_20': 0.800666153373918},
  {'kernel_size': 1987,
   'toplen_ptw': 2.120937656560345,
   'coherence_20': 0.8907181577123694},
  {'kernel_size': 1619,
   'toplen_ptw': 2.6083734215125736,
   'coherence_20': 1.2470573564284693},
  {'kernel_size': 1774,
   'toplen_ptw': 2.1587775881219717,
   'coherence_20': 0.9394945469913535},
  {'kernel_size': 2247,
   'toplen_ptw': 2.0299670213911134,
   'coherence_20': 0.5777001491069772}],
 [{'kernel_size': 2037,
   'toplen_ptw': 1.7655775936189189,
   'coherence_20': 0.6496348280647746},
  {'kernel_size': 1646,
   'toplen_ptw': 2.5385468237752358,
   'coherence_20': 0.41033445355709636},
  {'kernel_size': 1646,
   'toplen_ptw': 2.177847267928625,
   'coherence_20': 0.7477373694107972},
  {'kernel_size': 1793,
   'toplen_ptw': 2.1603292045184737,
   'coherence_20': 0.4667461832169932},
  {'kernel_size': 1844,
   'toplen_ptw': 1.8951907665262173,
   'coherence_20': 0.7054113586362807},
  {'kernel_size': 2367,
   'toplen_ptw': 1.8834005503914566,
   'coherence_20': 0.8257155401025114},
  {'kernel_size': 1809,
   'toplen_ptw': 2.172708458555898,
   'coherence_20': 0.7229958180440845},
  {'kernel_size': 2601,
   'toplen_ptw': 1.9007799793101128,
   'coherence_20': 0.9564451977579198},
  {'kernel_size': 1934,
   'toplen_ptw': 2.186842073079013,
   'coherence_20': 0.6895873716056875},
  {'kernel_size': 2251,
   'toplen_ptw': 2.091246473156176,
   'coherence_20': 0.5455165738551331},
  {'kernel_size': 1644,
   'toplen_ptw': 2.9971805610187925,
   'coherence_20': 1.1683945074643751},
  {'kernel_size': 2212,
   'toplen_ptw': 1.950772929501843,
   'coherence_20': 0.5295427506052311},
  {'kernel_size': 1938,
   'toplen_ptw': 1.806035203512054,
   'coherence_20': 0.7070942016727896},
  {'kernel_size': 1858,
   'toplen_ptw': 2.2629438152214547,
   'coherence_20': 0.58843699940341},
  {'kernel_size': 2335,
   'toplen_ptw': 1.8115940938632942,
   'coherence_20': 0.7678439666473789},
  {'kernel_size': 2051,
   'toplen_ptw': 1.8339662793412845,
   'coherence_20': 0.731710488282005},
  {'kernel_size': 2237,
   'toplen_ptw': 1.8221606993074615,
   'coherence_20': 0.5912317120557113},
  {'kernel_size': 1832,
   'toplen_ptw': 2.6617902442497328,
   'coherence_20': 1.0128247084479338},
  {'kernel_size': 2190,
   'toplen_ptw': 1.631973078076399,
   'coherence_20': 0.8237030593108302},
  {'kernel_size': 1634,
   'toplen_ptw': 1.992950853598818,
   'coherence_20': 1.0986432146751794}],
 [{'kernel_size': 1862,
   'toplen_ptw': 1.9140394717232245,
   'coherence_20': 0.6717611215110315},
  {'kernel_size': 2065,
   'toplen_ptw': 1.8116835834112737,
   'coherence_20': 0.8073626880924841},
  {'kernel_size': 2005,
   'toplen_ptw': 1.755249555351755,
   'coherence_20': 0.5815652923768178},
  {'kernel_size': 1906,
   'toplen_ptw': 1.7678190135797005,
   'coherence_20': 0.6539074346775802},
  {'kernel_size': 1998,
   'toplen_ptw': 1.7555497968824487,
   'coherence_20': 0.7144455828543929},
  {'kernel_size': 1751,
   'toplen_ptw': 2.6875216791916987,
   'coherence_20': 1.263801889728101},
  {'kernel_size': 2398,
   'toplen_ptw': 1.8706665573570813,
   'coherence_20': 0.621293594539277},
  {'kernel_size': 2180,
   'toplen_ptw': 1.910487452430012,
   'coherence_20': 0.5224359468274921},
  {'kernel_size': 1684,
   'toplen_ptw': 3.1076975585835154,
   'coherence_20': 0.3744724326402786},
  {'kernel_size': 1828,
   'toplen_ptw': 2.420455483008565,
   'coherence_20': 0.4835402134026235},
  {'kernel_size': 1840,
   'toplen_ptw': 1.8165330440618435,
   'coherence_20': 0.42712230511710614},
  {'kernel_size': 1837,
   'toplen_ptw': 2.3250602669868683,
   'coherence_20': 0.8659736010725031},
  {'kernel_size': 2301,
   'toplen_ptw': 2.2771397414389885,
   'coherence_20': 0.545922113769625},
  {'kernel_size': 1605,
   'toplen_ptw': 2.4601404375676283,
   'coherence_20': 1.0994066268816909},
  {'kernel_size': 1525,
   'toplen_ptw': 1.8068618421901257,
   'coherence_20': 0.8328703675176922},
  {'kernel_size': 2178,
   'toplen_ptw': 1.911987859131033,
   'coherence_20': 0.7427970683481553},
  {'kernel_size': 2403,
   'toplen_ptw': 2.066354639528915,
   'coherence_20': 0.9733191283177919},
  {'kernel_size': 1885,
   'toplen_ptw': 2.0509575107638374,
   'coherence_20': 0.9506670601699574},
  {'kernel_size': 1790,
   'toplen_ptw': 2.1339745604246905,
   'coherence_20': 0.8026195334131566},
  {'kernel_size': 2446,
   'toplen_ptw': 1.9682312861274514,
   'coherence_20': 0.938911647869319}],
 [{'kernel_size': 1766,
   'toplen_ptw': 2.044135028419924,
   'coherence_20': 0.5619673798377735},
  {'kernel_size': 1872,
   'toplen_ptw': 1.860019039903365,
   'coherence_20': 1.0799336222660294},
  {'kernel_size': 2054,
   'toplen_ptw': 1.7791353410717965,
   'coherence_20': 0.47079602399738035},
  {'kernel_size': 2656,
   'toplen_ptw': 1.8952701191118815,
   'coherence_20': 1.089748154686178},
  {'kernel_size': 1783,
   'toplen_ptw': 2.048216257306085,
   'coherence_20': 0.6805414784901312},
  {'kernel_size': 1729,
   'toplen_ptw': 2.48233119130162,
   'coherence_20': 0.6936703776584378},
  {'kernel_size': 2114,
   'toplen_ptw': 1.8738111984828973,
   'coherence_20': 0.6754830314642756},
  {'kernel_size': 1782,
   'toplen_ptw': 1.7260290141970576,
   'coherence_20': 0.9892003843868793},
  {'kernel_size': 2166,
   'toplen_ptw': 1.732359817776306,
   'coherence_20': 0.844321105458491},
  {'kernel_size': 1541,
   'toplen_ptw': 1.9795822361827597,
   'coherence_20': 0.837982552016571},
  {'kernel_size': 1721,
   'toplen_ptw': 2.0826809154328294,
   'coherence_20': 1.207964097038025},
  {'kernel_size': 2272,
   'toplen_ptw': 2.284126737389546,
   'coherence_20': 0.5159029480095179},
  {'kernel_size': 2096,
   'toplen_ptw': 2.608761821740391,
   'coherence_20': 0.435825479446882},
  {'kernel_size': 1791,
   'toplen_ptw': 2.1145567989149563,
   'coherence_20': 0.67761966683784},
  {'kernel_size': 1847,
   'toplen_ptw': 2.0672209049581247,
   'coherence_20': 1.1302145669876906},
  {'kernel_size': 2465,
   'toplen_ptw': 2.1153294984683058,
   'coherence_20': 0.8456668046296907},
  {'kernel_size': 2310,
   'toplen_ptw': 1.9453748544743243,
   'coherence_20': 0.7124737788022296},
  {'kernel_size': 2069,
   'toplen_ptw': 2.176186142808583,
   'coherence_20': 0.5870612368005964},
  {'kernel_size': 2049,
   'toplen_ptw': 2.1301563750209915,
   'coherence_20': 0.42648620009872623},
  {'kernel_size': 1697,
   'toplen_ptw': 2.193313216393718,
   'coherence_20': 0.9062742466384266}],
 [{'kernel_size': 1876,
   'toplen_ptw': 1.980693540439199,
   'coherence_20': 0.8110825080263447},
  {'kernel_size': 1979,
   'toplen_ptw': 1.8099434348400032,
   'coherence_20': 1.0781567582760532},
  {'kernel_size': 2057,
   'toplen_ptw': 1.8922751018077717,
   'coherence_20': 1.0307953871288216},
  {'kernel_size': 2449,
   'toplen_ptw': 1.9669144723318546,
   'coherence_20': 0.8534622752078083},
  {'kernel_size': 2028,
   'toplen_ptw': 2.14902363355148,
   'coherence_20': 0.4132653477815731},
  {'kernel_size': 1895,
   'toplen_ptw': 2.4292918638104775,
   'coherence_20': 1.029618839670958},
  {'kernel_size': 1901,
   'toplen_ptw': 2.909340110329061,
   'coherence_20': 0.5020265148989846},
  {'kernel_size': 2195,
   'toplen_ptw': 2.0496451028172595,
   'coherence_20': 0.4797943128039228},
  {'kernel_size': 1629,
   'toplen_ptw': 1.8456892643611782,
   'coherence_20': 0.613073654333347},
  {'kernel_size': 2441,
   'toplen_ptw': 1.8050093963444942,
   'coherence_20': 0.7687357118965222},
  {'kernel_size': 2444,
   'toplen_ptw': 1.8347645550547846,
   'coherence_20': 0.9961711735177163},
  {'kernel_size': 1856,
   'toplen_ptw': 2.086613641173254,
   'coherence_20': 0.6260382401948604},
  {'kernel_size': 1910,
   'toplen_ptw': 2.308805431717426,
   'coherence_20': 1.0751397575052681},
  {'kernel_size': 2057,
   'toplen_ptw': 1.9669113059321734,
   'coherence_20': 0.517955356281521},
  {'kernel_size': 2080,
   'toplen_ptw': 1.6968988111195875,
   'coherence_20': 0.540280220713305},
  {'kernel_size': 2104,
   'toplen_ptw': 1.9328026873800106,
   'coherence_20': 0.5507431444780608},
  {'kernel_size': 2172,
   'toplen_ptw': 2.0525652948202486,
   'coherence_20': 0.807569560428652},
  {'kernel_size': 2106,
   'toplen_ptw': 1.9230081570054747,
   'coherence_20': 0.5687175558819604},
  {'kernel_size': 1701,
   'toplen_ptw': 3.0347519703383323,
   'coherence_20': 1.2264584102229057},
  {'kernel_size': 1841,
   'toplen_ptw': 2.0087501643620134,
   'coherence_20': 0.6587053303949284}],
 [{'kernel_size': 1702,
   'toplen_ptw': 2.084291860376383,
   'coherence_20': 0.769897504719885},
  {'kernel_size': 2213,
   'toplen_ptw': 2.0238690635747996,
   'coherence_20': 0.5025861787394876},
  {'kernel_size': 1925,
   'toplen_ptw': 2.1838656806929624,
   'coherence_20': 0.7518737863470601},
  {'kernel_size': 1554,
   'toplen_ptw': 1.7454787206165978,
   'coherence_20': 0.9147366064439402},
  {'kernel_size': 2320,
   'toplen_ptw': 1.9402137640364714,
   'coherence_20': 0.9949683010151695},
  {'kernel_size': 1761,
   'toplen_ptw': 2.6014991273762758,
   'coherence_20': 1.1952513783205414},
  {'kernel_size': 2271,
   'toplen_ptw': 1.8480649919282859,
   'coherence_20': 0.7563604965639763},
  {'kernel_size': 1966,
   'toplen_ptw': 1.7253680541161294,
   'coherence_20': 0.6888157192407841},
  {'kernel_size': 2113,
   'toplen_ptw': 2.0442288637798183,
   'coherence_20': 0.6885989385709799},
  {'kernel_size': 1724,
   'toplen_ptw': 3.064833960708721,
   'coherence_20': 1.206703084267664},
  {'kernel_size': 1887,
   'toplen_ptw': 2.170075318220486,
   'coherence_20': 0.7191164841538964},
  {'kernel_size': 1877,
   'toplen_ptw': 2.236908561677502,
   'coherence_20': 0.4520566991087533},
  {'kernel_size': 2468,
   'toplen_ptw': 1.9244380569186659,
   'coherence_20': 0.5850900387518067},
  {'kernel_size': 2155,
   'toplen_ptw': 1.7200566910104935,
   'coherence_20': 0.8248444146224149},
  {'kernel_size': 2003,
   'toplen_ptw': 1.8259432227878405,
   'coherence_20': 0.7035879158691474},
  {'kernel_size': 1743,
   'toplen_ptw': 2.8460548817861056,
   'coherence_20': 0.3769918925482554},
  {'kernel_size': 2073,

In [133]:
# Real-fixing bank topics

In [225]:
from topnum.search_methods.topic_bank.one_model_train_funcs import _get_topic_model, init_phi_utils

In [574]:
from topicnet.cooking_machine.model_constructor import (
    add_standard_scores,
    create_default_topics,
    init_model,
)

def _get_topic_model_dev(
        dataset: Dataset,
        phi: pd.DataFrame = None,
        num_topics: int = None,
        seed: int = None,
        scores: List = None,
        num_safe_fit_iterations: int = 3,
        num_processors: int = 3,
        cache_theta: bool = False) -> TopicModel:

    dictionary = dataset.get_dictionary()

    # for modality in dataset.get_possible_modalities():
    #     if modality not in modalities_to_use:
    #         dictionary.filter(class_id=modality, max_df=0, inplace=True)

    if num_topics is not None and phi is not None:
        assert num_topics >= phi.shape[1]
    elif num_topics is None and phi is not None:
        num_topics = phi.shape[1]
    elif num_topics is None and phi is None:
        raise ValueError()

    topic_names = [f'topic_{i}' for i in range(num_topics)]

    # if seed is None:
    #     artm_model = artm.ARTM(topic_names=topic_names)
    # else:
    #     artm_model = artm.ARTM(topic_names=topic_names, seed=seed)

    if seed is None:
        artm_model = artm.ARTM(topic_names=topic_names, class_ids={MAIN_MODALITY: 1})  # TODO: not list, but dict!!!
    else:
        artm_model = artm.ARTM(topic_names=topic_names, seed=seed, class_ids={MAIN_MODALITY: 1})

    # artm_model = init_model(topic_names, class_ids=[MAIN_MODALITY])

    # artm_model = init_plsa(DATASET, [MAIN_MODALITY], MAIN_MODALITY, 5)

    artm_model.num_processors = num_processors
    artm_model.initialize(dictionary)

    """
    if phi is None:
        pass
    elif num_safe_fit_iterations is not None and num_safe_fit_iterations > 0:
        init_phi_utils._safe_copy_phi(artm_model, phi, dataset, num_safe_fit_iterations)
    else:
        init_phi_utils._copy_phi(artm_model, phi)
    """
    # this breaks smth in ARTM
    # test_ppl@word [1827.4515380859375, 2707.63623046875, 2707.67919921875, 2707.679443359375, 2707.679443359375]
    # test_ppl@word_with_d [4073.36328125, 6035.2822265625, 6035.3779296875, 6035.37841796875, 6035.37841796875]
    # test_ppl@all [1827.4515380859375, 2707.63623046875, 2707.67919921875, 2707.679443359375, 2707.679443359375]
    # test_ppl@all_2 [1827.4515380859375, 2707.63623046875, 2707.67919921875, 2707.679443359375, 2707.679443359375]
    # test_ppl@all_2_with_d [4073.36328125, 6035.2822265625, 6035.3779296875, 6035.37841796875, 6035.37841796875]
    
    topic_model = TopicModel(
        artm_model=artm_model,
        model_id='0',
        cache_theta=cache_theta,
        theta_columns_naming='title'
    )

    if scores is not None:
        for score in scores:
            score._attach(topic_model)

    return topic_model

In [227]:
model = artm_train_func(DATASET, 1, 2, 1)

No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

In [424]:
DATASET.get_dictionary()

artm.Dictionary(name=6231af29-73db-42d7-a978-1e0c744be737, num_entries=19186)

In [425]:
optimizer._dataset.get_dictionary()

artm.Dictionary(name=6231af29-73db-42d7-a978-1e0c744be737, num_entries=19186)

In [588]:
phi = model.get_phi()
phi = phi.iloc[phi.index.get_level_values(0).isin([MAIN_MODALITY])]

word2index = {
    word: index for index, word in enumerate(phi.index)
}

bank_phi = optimizer._get_phi(optimizer._topic_bank.topics, word2index)
# bank_model = _get_topic_model_dev(  #_get_topic_model( _get_topic_model_dev
#     optimizer._dataset,
#     phi=bank_phi,
#     scores=optimizer._all_model_scores,
#     num_safe_fit_iterations=1,
# )
bank_model = init_model_from_family('sparse', DATASET, MAIN_MODALITY, 5, 0)


"""
_bank_model = init_plsa(DATASET, [MAIN_MODALITY], MAIN_MODALITY, 5)
_bank_model.num_processors = 3
# _bank_model.seed = seed
dictionary = DATASET.get_dictionary()

# TODO: maybe this cycle is not necessary
# for modality in DATASET.get_possible_modalities():
#     if modality not in [MAIN_MODALITY]:
#         dictionary.filter(class_id=modality, max_df=0, inplace=True)

_bank_model.initialize(dictionary)
# add_standard_scores(model, dictionary, main_modality=main_modality,
#                     all_modalities=modalities_to_use)

bank_model = TopicModel(
    artm_model=_bank_model,
    # custom_regularizers=custom_regs
)
"""

No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

'\n_bank_model = init_plsa(DATASET, [MAIN_MODALITY], MAIN_MODALITY, 5)\n_bank_model.num_processors = 3\n# _bank_model.seed = seed\ndictionary = DATASET.get_dictionary()\n\n# TODO: maybe this cycle is not necessary\n# for modality in DATASET.get_possible_modalities():\n#     if modality not in [MAIN_MODALITY]:\n#         dictionary.filter(class_id=modality, max_df=0, inplace=True)\n\n_bank_model.initialize(dictionary)\n# add_standard_scores(model, dictionary, main_modality=main_modality,\n#                     all_modalities=modalities_to_use)\n\nbank_model = TopicModel(\n    artm_model=_bank_model,\n    # custom_regularizers=custom_regs\n)\n'

In [589]:
bank_model._model.class_ids

{'@word': 1}

In [590]:
bank_model._model.regularizers

[smooth_phi_bcg, smooth_theta_bcg, sparse_phi_sp, sparse_theta_sp]

In [591]:
bank_model._fit(
    optimizer._dataset.get_batch_vectorizer(),
    num_iterations=2,
)

In [592]:
for m in DATASET.get_possible_modalities():
    bank_model._model.scores.add(
        artm.scores.PerplexityScore(
            name=f'test_ppl{m}',
            class_ids=[m]
        )
    )
    bank_model._model.scores.add(
        artm.scores.PerplexityScore(
            name=f'test_ppl{m}_with_d',
            class_ids=[m],
            dictionary=DATASET.get_dictionary()
        )
    )

bank_model._model.scores.add(
    artm.scores.PerplexityScore(
        name=f'test_ppl@all',
        class_ids=list(DATASET.get_possible_modalities()),
    )
)
bank_model._model.scores.add(
    artm.scores.PerplexityScore(
        name=f'test_ppl@all_2',
   )
)
bank_model._model.scores.add(
    artm.scores.PerplexityScore(
        name=f'test_ppl@all_2_with_d',
        dictionary=DATASET.get_dictionary()
   )
)

In [593]:
bank_phi['topic_4'].sort_values(ascending=False)

@word  клетка             0.030503
       ген                0.012852
       организм           0.009684
       днк                0.009340
       пациент            0.009092
                            ...
       камень             0.000000
       встревожить        0.000000
       технологический    0.000000
       летопись           0.000000
       аврелий            0.000000
Name: topic_4, Length: 19186, dtype: float64

In [594]:
bank_topics['topic_4'].sort_values(ascending=False)

@word  клетка             0.030503
       ген                0.012852
       организм           0.009684
       днк                0.009340
       пациент            0.009092
                            ...
       камень             0.000000
       встревожить        0.000000
       технологический    0.000000
       летопись           0.000000
       аврелий            0.000000
Name: topic_4, Length: 19186, dtype: float64

In [595]:
bank_model.get_phi()['topic_4'].sort_values(ascending=False)

modality  token
@word     язык                 0.015199
          книга                0.008724
          государство          0.007782
          вопрос               0.007237
          общество             0.004902
                                 ...
          жорж                 0.000000
          пешеход              0.000000
          скучать              0.000000
          восстановительный    0.000000
          аврелий              0.000000
Name: topic_4, Length: 19186, dtype: float32

In [596]:
class FastFixPhiRegularizer(BaseRegularizer):
    _VERY_BIG_TAU = 10 ** 9  # 10 ** 9

    def __init__(self, name: str, phi, topic_names: List[str]):
        super().__init__(name, tau=self._VERY_BIG_TAU)

        self._topic_names = topic_names
        self._topic_indices = None
        self._phi = phi

    def grad(self, pwt, nwt):
        # print('Fixing')

        rwt = np.zeros_like(pwt)
        parent_phi = self._phi
        
        rwt[:, self._topic_indices] += parent_phi.values[:, self._topic_indices]

        return self.tau * rwt

    def attach(self, model):
        super().attach(model)
        
        phi = self._model.get_phi()
        self._topic_indices = [
            phi.columns.get_loc(topic_name)
            for topic_name in self._topic_names
        ]

In [600]:
bank_model._fit(
    optimizer._dataset.get_batch_vectorizer(),
    num_iterations=5,
    custom_regularizers={
        'fix': FastFixPhiRegularizer(
            name='fix',
            phi=bank_phi,
            topic_names=bank_phi.columns,
        ),
    }
)

In [601]:
bank_model.get_phi()['topic_4'].sort_values(ascending=False)

modality  token
@word     клетка             0.030503
          ген                0.012852
          организм           0.009684
          днк                0.009340
          пациент            0.009092
                               ...
          камень             0.000000
          встревожить        0.000000
          технологический    0.000000
          летопись           0.000000
          аврелий            0.000000
Name: topic_4, Length: 19186, dtype: float32

In [602]:
for m in DATASET.get_possible_modalities():
    print(f'test_ppl{m}', bank_model.scores[f'test_ppl{m}'])
    print(f'test_ppl{m}_with_d', bank_model.scores[f'test_ppl{m}_with_d'])


print(f'test_ppl@all', bank_model.scores[f'test_ppl@all'])
print(f'test_ppl@all_2', bank_model.scores[f'test_ppl@all_2'])
print(f'test_ppl@all_2_with_d', bank_model.scores[f'test_ppl@all_2_with_d'])

test_ppl@title [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@title_with_d [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@2gramm [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@2gramm_with_d [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@author [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@author_with_d [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@snippet [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@snippet_with_d [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@post_tag [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@post_tag_with_d [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@word [5297.6376953125, 5158.78857421875, 4709.48095703125, 4687.263671875, 4683.79833984375, 4682.92138671875, 4682.62109375, 4682.52197265625, 4682.48974609375, 4682.478515625]
test_ppl@word_with_d [5297.6376953125, 5158.78857421875, 4709.48095703125, 4687.263671875, 4683.79833984375, 4682.92138671875, 4682.62109375, 4682.52197265625, 4682.48974609375, 4682.478515625]
test_ppl@3gramm [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@3gramm_with_d [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@all [5297.6376953125, 5158.78857421875, 4709.48095703125, 4687.263671875, 4683.79833984375, 4682.92138671875, 4682.62109375, 4682.52197265625, 4682.48974609375, 4682.478515625]
test_ppl@all_2 [5297.6376953125, 5158.78857421875, 4709.48095703125, 4687.263671875, 4683.79833984375, 4682.92138671875, 4682.62109375, 4682.52197265625, 4682.48974609375, 4682.478515625]
test_ppl@all_2_with_d [5297.6376953125, 5158.78857421875, 4709.48095703125, 4687.263671875, 4683.79833984375, 4682.92138671875, 4682.62109375, 4682.52197265625, 4682.48974609375, 4682.478515625]

In [475]:
bank_model.scores['perplexity_from_start']

KeyError: 'perplexity_from_start'

In [ ]:
DATASET.get_possible_modalities()

In [191]:
bank_model.get_phi()['topic_2'].sort_values(ascending=False)

modality  token
@word     звезда            0.021522
          вселенная         0.016877
          галактика         0.016023
          земля             0.010558
          солнце            0.009292
                              ...
          марш              0.000000
          феминистка        0.000000
          возобновляться    0.000000
          обвал             0.000000
          акт               0.000000
Name: topic_2, Length: 19186, dtype: float32

In [192]:
coherence_score.call_by_topic(bank_model)

{0: array([1.30200985]),
 1: array([1.08845739]),
 2: array([1.0168754]),
 3: array([1.15621355]),
 4: array([1.28988277])}

In [193]:
coherence_score.call(bank_model)

array([1.17068779])

In [194]:
optimizer._result['bank_scores'][-1]

{'perplexity_score': 2707.664306640625,
 'coherence_20': 1.1706877915144434,
 'diversity_euclidean': 0.06451756106182875,
 'diversity_jensenshannon': 0.6715327504064806,
 'diversity_hellinger': 0.7877305942486647,
 'diversity_cosine': 0.8494073511502591,
 'perplexity': 2707.664306640625}

In [195]:
optimizer._get_default_scores(bank_model)

{'perplexity_score': 2707.679443359375,
 'coherence_20': 1.1706877915144434,
 'diversity_euclidean': 0.0645175614263375,
 'diversity_jensenshannon': 0.6715327515781992,
 'diversity_hellinger': 0.7877305960342527,
 'diversity_cosine': 0.8494073528332182,
 'perplexity': 2707.679443359375}

In [196]:
bank_topics.shape

(19186, 5)

In [416]:
model = init_model_from_family('PLSA', DATASET, MAIN_MODALITY, 5, 0)

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

In [417]:
model.get_phi().shape

(19186, 5)

In [418]:
for m in DATASET.get_possible_modalities():
    model._model.scores.add(
        artm.scores.PerplexityScore(
            name=f'test_ppl{m}',
            class_ids=[m]
        )
    )
    model._model.scores.add(
        artm.scores.PerplexityScore(
            name=f'test_ppl{m}_with_d',
            class_ids=[m],
            dictionary=DATASET.get_dictionary()
        )
    )

model._model.scores.add(
    artm.scores.PerplexityScore(
        name=f'test_ppl@all',
        class_ids=DATASET.get_possible_modalities(),
    )
)
model._model.scores.add(
    artm.scores.PerplexityScore(
        name=f'test_ppl@all_2',
   )
)
model._model.scores.add(
    artm.scores.PerplexityScore(
        name=f'test_ppl@all_2_with_d',
        dictionary=DATASET.get_dictionary()
   )
)

In [419]:
model._fit(DATASET.get_batch_vectorizer(), 20)

In [420]:
for m in DATASET.get_possible_modalities():
    print(f'test_ppl{m}', model.scores[f'test_ppl{m}'])
    print(f'test_ppl{m}_with_d', model.scores[f'test_ppl{m}_with_d'])


print(f'test_ppl@all', model.scores[f'test_ppl@all'])
print(f'test_ppl@all_2', model.scores[f'test_ppl@all_2'])
print(f'test_ppl@all_2_with_d', model.scores[f'test_ppl@all_2_with_d'])

test_ppl@title [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@title_with_d [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@2gramm [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@2gramm_with_d [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@author [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@author_with_d [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@snippet [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@snippet_with_d [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@post_tag [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@post_tag_with_d [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@word [18982.515625, 5344.19189453125, 5225.41015625, 4953.0224609375, 4654.1123046875, 4462.4375, 4331.3232421875, 4235.84521484375, 4167.56640625, 4119.76123046875, 4086.258056640625, 4062.859375, 4046.390380859375, 4034.490234375, 4025.72021484375, 4019.29052734375, 4014.560302734375, 4010.853515625, 4007.927734375, 4005.75537109375]
test_ppl@word_with_d [18982.515625, 5344.19189453125, 5225.41015625, 4953.0224609375, 4654.1123046875, 4462.4375, 4331.3232421875, 4235.84521484375, 4167.56640625, 4119.76123046875, 4086.258056640625, 4062.859375, 4046.390380859375, 4034.490234375, 4025.72021484375, 4019.29052734375, 4014.560302734375, 4010.853515625, 4007.927734375, 4005.75537109375]
test_ppl@3gramm [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@3gramm_with_d [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@all [18982.515625, 5344.19189453125, 5225.41015625, 4953.0224609375, 4654.1123046875, 4462.4375, 4331.3232421875, 4235.84521484375, 4167.56640625, 4119.76123046875, 4086.258056640625, 4062.859375, 4046.390380859375, 4034.490234375, 4025.72021484375, 4019.29052734375, 4014.560302734375, 4010.853515625, 4007.927734375, 4005.75537109375]
test_ppl@all_2 [18982.515625, 5344.19189453125, 5225.41015625, 4953.0224609375, 4654.1123046875, 4462.4375, 4331.3232421875, 4235.84521484375, 4167.56640625, 4119.76123046875, 4086.258056640625, 4062.859375, 4046.390380859375, 4034.490234375, 4025.72021484375, 4019.29052734375, 4014.560302734375, 4010.853515625, 4007.927734375, 4005.75537109375]
test_ppl@all_2_with_d [18982.515625, 5344.19189453125, 5225.41015625, 4953.0224609375, 4654.1123046875, 4462.4375, 4331.3232421875, 4235.84521484375, 4167.56640625, 4119.76123046875, 4086.258056640625, 4062.859375, 4046.390380859375, 4034.490234375, 4025.72021484375, 4019.29052734375, 4014.560302734375, 4010.853515625, 4007.927734375, 4005.75537109375]

In [421]:
model._fit(
    DATASET.get_batch_vectorizer(),
    num_iterations=20,
    custom_regularizers={
        'fix': FastFixPhiRegularizer(
            name='fix',
            phi=bank_phi,
            topic_names=bank_phi.columns,
        ),
    }
)

In [422]:
for m in DATASET.get_possible_modalities():
    print(f'test_ppl{m}', model.scores[f'test_ppl{m}'])
    print(f'test_ppl{m}_with_d', model.scores[f'test_ppl{m}_with_d'])


print(f'test_ppl@all', model.scores[f'test_ppl@all'])
print(f'test_ppl@all_2', model.scores[f'test_ppl@all_2'])
print(f'test_ppl@all_2_with_d', model.scores[f'test_ppl@all_2_with_d'])

test_ppl@title [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@title_with_d [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@2gramm [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@2gramm_with_d [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@author [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@author_with_d [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@snippet [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@snippet_with_d [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@post_tag [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@post_tag_with_d [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@word [18982.515625, 5344.19189453125, 5225.41015625, 4953.0224609375, 4654.1123046875, 4462.4375, 4331.3232421875, 4235.84521484375, 4167.56640625, 4119.76123046875, 4086.258056640625, 4062.859375, 4046.390380859375, 4034.490234375, 4025.72021484375, 4019.29052734375, 4014.560302734375, 4010.853515625, 4007.927734375, 4005.75537109375, 4003.997802734375, 24196.91796875, 23968.0, 23750.837890625, 23556.845703125, 23387.771484375, 23242.3046875, 23115.556640625, 23003.33984375, 22902.7109375, 22813.455078125, 22736.119140625, 22669.6171875, 22611.533203125, 22560.84375, 22516.939453125, 22478.94921875, 22446.25, 22418.119140625, 22394.51953125]
test_ppl@word_with_d [18982.515625, 5344.19189453125, 5225.41015625, 4953.0224609375, 4654.1123046875, 4462.4375, 4331.3232421875, 4235.84521484375, 4167.56640625, 4119.76123046875, 4086.258056640625, 4062.859375, 4046.390380859375, 4034.490234375, 4025.72021484375, 4019.29052734375, 4014.560302734375, 4010.853515625, 4007.927734375, 4005.75537109375, 4003.997802734375, 24196.91796875, 23968.0, 23750.837890625, 23556.845703125, 23387.771484375, 23242.3046875, 23115.556640625, 23003.33984375, 22902.7109375, 22813.455078125, 22736.119140625, 22669.6171875, 22611.533203125, 22560.84375, 22516.939453125, 22478.94921875, 22446.25, 22418.119140625, 22394.51953125]
test_ppl@3gramm [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@3gramm_with_d [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@all [18982.515625, 5344.19189453125, 5225.41015625, 4953.0224609375, 4654.1123046875, 4462.4375, 4331.3232421875, 4235.84521484375, 4167.56640625, 4119.76123046875, 4086.258056640625, 4062.859375, 4046.390380859375, 4034.490234375, 4025.72021484375, 4019.29052734375, 4014.560302734375, 4010.853515625, 4007.927734375, 4005.75537109375, 4003.997802734375, 24196.91796875, 23968.0, 23750.837890625, 23556.845703125, 23387.771484375, 23242.3046875, 23115.556640625, 23003.33984375, 22902.7109375, 22813.455078125, 22736.119140625, 22669.6171875, 22611.533203125, 22560.84375, 22516.939453125, 22478.94921875, 22446.25, 22418.119140625, 22394.51953125]
test_ppl@all_2 [18982.515625, 5344.19189453125, 5225.41015625, 4953.0224609375, 4654.1123046875, 4462.4375, 4331.3232421875, 4235.84521484375, 4167.56640625, 4119.76123046875, 4086.258056640625, 4062.859375, 4046.390380859375, 4034.490234375, 4025.72021484375, 4019.29052734375, 4014.560302734375, 4010.853515625, 4007.927734375, 4005.75537109375, 4003.997802734375, 24196.91796875, 23968.0, 23750.837890625, 23556.845703125, 23387.771484375, 23242.3046875, 23115.556640625, 23003.33984375, 22902.7109375, 22813.455078125, 22736.119140625, 22669.6171875, 22611.533203125, 22560.84375, 22516.939453125, 22478.94921875, 22446.25, 22418.119140625, 22394.51953125]
test_ppl@all_2_with_d [18982.515625, 5344.19189453125, 5225.41015625, 4953.0224609375, 4654.1123046875, 4462.4375, 4331.3232421875, 4235.84521484375, 4167.56640625, 4119.76123046875, 4086.258056640625, 4062.859375, 4046.390380859375, 4034.490234375, 4025.72021484375, 4019.29052734375, 4014.560302734375, 4010.853515625, 4007.927734375, 4005.75537109375, 4003.997802734375, 24196.91796875, 23968.0, 23750.837890625, 23556.845703125, 23387.771484375, 23242.3046875, 23115.556640625, 23003.33984375, 22902.7109375, 22813.455078125, 22736.119140625, 22669.6171875, 22611.533203125, 22560.84375, 22516.939453125, 22478.94921875, 22446.25, 22418.119140625, 22394.51953125]

In [412]:
bank_phi['topic_2'].sort_values(ascending=False)

@word  звезда            0.021526
       вселенная         0.016880
       галактика         0.016026
       земля             0.010559
       солнце            0.009293
                           ...
       марш              0.000000
       феминистка        0.000000
       возобновляться    0.000000
       обвал             0.000000
       акт               0.000000
Name: topic_2, Length: 19186, dtype: float64

In [413]:
model.get_phi()['topic_2'].sort_values(ascending=False)

modality  token
@word     звезда            0.021526
          вселенная         0.016880
          галактика         0.016026
          земля             0.010559
          солнце            0.009293
                              ...
          марш              0.000000
          феминистка        0.000000
          возобновляться    0.000000
          обвал             0.000000
          акт               0.000000
Name: topic_2, Length: 19186, dtype: float32

In [415]:
model.get_phi()['background_5'].sort_values(ascending=False)

modality  token
@word     говорить      0.002969
          язык          0.002913
          книга         0.002437
          большой       0.002309
          слово         0.002295
                          ...
          шриффер       0.000007
          кваркова      0.000007
          килопарсек    0.000007
          оннести       0.000007
          камерлинг     0.000006
Name: background_5, Length: 19186, dtype: float32

In [384]:
model._fit(
    DATASET.get_batch_vectorizer(),
    num_iterations=10,
    custom_regularizers={
        'fix': FastFixPhiRegularizer(
            name='fix',
            phi=bank_phi,
            topic_names=bank_phi.columns,
        ),
    }
)

In [385]:
for m in DATASET.get_possible_modalities():
    print(f'test_ppl{m}', model.scores[f'test_ppl{m}'])
    print(f'test_ppl{m}_with_d', model.scores[f'test_ppl{m}_with_d'])


print(f'test_ppl@all', model.scores[f'test_ppl@all'])
print(f'test_ppl@all_2', model.scores[f'test_ppl@all_2'])
print(f'test_ppl@all_2_with_d', model.scores[f'test_ppl@all_2_with_d'])

test_ppl@title [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@title_with_d [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@2gramm [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@2gramm_with_d [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@author [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@author_with_d [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@snippet [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@snippet_with_d [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@post_tag [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@post_tag_with_d [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@word [18982.515625, 5344.19189453125, 5225.41064453125, 4953.0224609375, 4654.1123046875, 4462.4375, 4331.3232421875, 4235.84521484375, 4167.56591796875, 4119.76171875, 4086.258056640625, 24226.58203125, 23947.90625, 23669.130859375, 23406.2265625, 23166.892578125, 22955.984375, 22772.5078125, 22614.47265625, 22479.451171875, 22364.6015625, 22270.189453125, 22196.77734375, 22139.984375, 22093.416015625, 22055.505859375, 22025.869140625, 22002.611328125, 21984.099609375, 21968.564453125, 21954.888671875, 6131.7958984375, 6109.703125, 6097.63037109375, 6090.6689453125, 6086.68798828125, 6084.2587890625, 6082.62890625, 6081.43994140625, 6080.51220703125]
test_ppl@word_with_d [18982.515625, 5344.19189453125, 5225.41064453125, 4953.0224609375, 4654.1123046875, 4462.4375, 4331.3232421875, 4235.84521484375, 4167.56591796875, 4119.76171875, 4086.258056640625, 24226.58203125, 23947.90625, 23669.130859375, 23406.2265625, 23166.892578125, 22955.984375, 22772.5078125, 22614.47265625, 22479.451171875, 22364.6015625, 22270.189453125, 22196.77734375, 22139.984375, 22093.416015625, 22055.505859375, 22025.869140625, 22002.611328125, 21984.099609375, 21968.564453125, 21954.888671875, 6131.7958984375, 6109.703125, 6097.63037109375, 6090.6689453125, 6086.68798828125, 6084.2587890625, 6082.62890625, 6081.43994140625, 6080.51220703125]
test_ppl@3gramm [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@3gramm_with_d [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@all [18982.515625, 5344.19189453125, 5225.41064453125, 4953.0224609375, 4654.1123046875, 4462.4375, 4331.3232421875, 4235.84521484375, 4167.56591796875, 4119.76171875, 4086.258056640625, 24226.58203125, 23947.90625, 23669.130859375, 23406.2265625, 23166.892578125, 22955.984375, 22772.5078125, 22614.47265625, 22479.451171875, 22364.6015625, 22270.189453125, 22196.77734375, 22139.984375, 22093.416015625, 22055.505859375, 22025.869140625, 22002.611328125, 21984.099609375, 21968.564453125, 21954.888671875, 6131.7958984375, 6109.703125, 6097.63037109375, 6090.6689453125, 6086.68798828125, 6084.2587890625, 6082.62890625, 6081.43994140625, 6080.51220703125]
test_ppl@all_2 [18982.515625, 5344.19189453125, 5225.41064453125, 4953.0224609375, 4654.1123046875, 4462.4375, 4331.3232421875, 4235.84521484375, 4167.56591796875, 4119.76171875, 4086.258056640625, 24226.58203125, 23947.90625, 23669.130859375, 23406.2265625, 23166.892578125, 22955.984375, 22772.5078125, 22614.47265625, 22479.451171875, 22364.6015625, 22270.189453125, 22196.77734375, 22139.984375, 22093.416015625, 22055.505859375, 22025.869140625, 22002.611328125, 21984.099609375, 21968.564453125, 21954.888671875, 6131.7958984375, 6109.703125, 6097.63037109375, 6090.6689453125, 6086.68798828125, 6084.2587890625, 6082.62890625, 6081.43994140625, 6080.51220703125]
test_ppl@all_2_with_d [18982.515625, 5344.19189453125, 5225.41064453125, 4953.0224609375, 4654.1123046875, 4462.4375, 4331.3232421875, 4235.84521484375, 4167.56591796875, 4119.76171875, 4086.258056640625, 24226.58203125, 23947.90625, 23669.130859375, 23406.2265625, 23166.892578125, 22955.984375, 22772.5078125, 22614.47265625, 22479.451171875, 22364.6015625, 22270.189453125, 22196.77734375, 22139.984375, 22093.416015625, 22055.505859375, 22025.869140625, 22002.611328125, 21984.099609375, 21968.564453125, 21954.888671875, 6131.7958984375, 6109.703125, 6097.63037109375, 6090.6689453125, 6086.68798828125, 6084.2587890625, 6082.62890625, 6081.43994140625, 6080.51220703125]

In [386]:
bank_phi['topic_2'].sort_values(ascending=False)

@word  звезда            0.021526
       вселенная         0.016880
       галактика         0.016026
       земля             0.010559
       солнце            0.009293
                           ...
       марш              0.000000
       феминистка        0.000000
       возобновляться    0.000000
       обвал             0.000000
       акт               0.000000
Name: topic_2, Length: 19186, dtype: float64

In [387]:
model.get_phi()['topic_2'].sort_values(ascending=False)

modality  token
@word     звезда           0.018555
          вселенная        0.014553
          галактика        0.013789
          земля            0.009610
          объект           0.008414
                             ...
          схватка          0.000000
          стратегически    0.000000
          вырабатывать     0.000000
          стул             0.000000
          акт              0.000000
Name: topic_2, Length: 19186, dtype: float32

In [113]:
model.scores['PerplexityScore@word']

[19895.9453125,
 5456.2392578125,
 5297.1337890625,
 5065.22119140625,
 4837.330078125,
 4680.2939453125,
 4590.2880859375,
 4540.271484375,
 4511.2646484375,
 4493.751953125,
 4482.685546875,
 4475.7783203125,
 4471.40087890625,
 4468.5302734375,
 4466.552734375,
 4465.248046875,
 4464.421875,
 4463.90576171875,
 4463.64404296875,
 4463.5302734375,
 4463.5283203125,
 5405.4609375,
 4719.11279296875,
 4688.26416015625,
 4683.736328125,
 4682.79052734375,
 4682.53857421875,
 4682.48193359375,
 4682.46923828125,
 4682.4638671875,
 4682.4619140625,
 4682.4658203125,
 4682.46875,
 4682.46875,
 4682.47021484375,
 4682.4697265625,
 4682.470703125,
 4682.470703125,
 4682.47021484375,
 4682.470703125,
 4682.470703125,
 4682.47119140625,
 4682.47119140625,
 4682.47119140625]

In [108]:
bank_model.get_phi()['topic_0'].sort_values(ascending=False)[:10]

modality  token
@word     caption              0.025622
          align                0.012789
          width                0.012788
          attachment           0.012606
          свет                 0.012437
          aligncenter          0.007243
          рис                  0.006824
          устройство           0.006685
          сверхпроводимость    0.005892
          святилище            0.005607
Name: topic_0, dtype: float32

In [114]:
model.get_phi()['topic_0'].sort_values(ascending=False)[:10]

modality  token
@word     caption              0.025624
          align                0.012790
          width                0.012790
          attachment           0.012607
          свет                 0.012438
          aligncenter          0.007243
          рис                  0.006825
          устройство           0.006685
          сверхпроводимость    0.005892
          святилище            0.005608
Name: topic_0, dtype: float32

In [115]:
model.get_phi().head()

                       topic_0  topic_1  topic_2   topic_3  topic_4  \
modality token
@word    инвалидность      0.0      0.0      0.0  0.000000      0.0
         мазка             0.0      0.0      0.0  0.000000      0.0
         professor         0.0      0.0      0.0  0.000017      0.0
         умно              0.0      0.0      0.0  0.000000      0.0
         игил              0.0      0.0      0.0  0.000000      0.0

                       background_5
modality token
@word    инвалидность      0.000010
         мазка             0.000010
         professor         0.000009
         умно              0.000010
         игил              0.000010

In [116]:
model = init_model_from_family('PLSA', DATASET, MAIN_MODALITY, 5, 0)

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

In [117]:
model._fit(
    DATASET.get_batch_vectorizer(),
    num_iterations=20,
    custom_regularizers={
        regularizer.name: regularizer,
    }
)

In [118]:
model.scores['PerplexityScore@word']

[18982.515625,
 24645.68359375,
 23630.40234375,
 22722.39453125,
 22194.84765625,
 21943.359375,
 21827.154296875,
 21770.6875,
 21740.708984375,
 21723.21875,
 21712.1875,
 21704.763671875,
 21699.482421875,
 21695.611328125,
 21692.720703125,
 21690.517578125,
 21688.822265625,
 21687.4921875,
 21686.439453125,
 21685.58984375]

In [130]:
model.scores['PerplexityScore@all']

[18982.515625,
 24645.68359375,
 23630.40234375,
 22722.39453125,
 22194.84765625,
 21943.359375,
 21827.154296875,
 21770.6875,
 21740.708984375,
 21723.21875,
 21712.1875,
 21704.763671875,
 21699.482421875,
 21695.611328125,
 21692.720703125,
 21690.517578125,
 21688.822265625,
 21687.4921875,
 21686.439453125,
 21685.58984375]

In [125]:
bank_model.get_phi()['topic_1'].sort_values(ascending=False)[:10]

modality  token
@word     право        0.019665
          закон        0.009846
          сталин       0.008532
          власть       0.007165
          история      0.006088
          суд          0.005563
          церковь      0.005529
          бог          0.005110
          отношение    0.004377
          должный      0.004363
Name: topic_1, dtype: float32

In [126]:
model.get_phi()['topic_1'].sort_values(ascending=False)[:10]

modality  token
@word     право        0.019660
          закон        0.009844
          сталин       0.008530
          власть       0.007163
          история      0.006086
          суд          0.005561
          церковь      0.005527
          бог          0.005108
          отношение    0.004376
          должный      0.004363
Name: topic_1, dtype: float32

In [121]:
model.get_phi().head()

                            topic_0       topic_1       topic_2       topic_3  \
modality token
@word    инвалидность  0.000000e+00  4.833264e-09  0.000000e+00  0.000000e+00
         мазка         0.000000e+00  2.413737e-09  1.678086e-09  5.836904e-16
         professor     0.000000e+00  0.000000e+00  0.000000e+00  1.689069e-05
         умно          1.873608e-14  4.886941e-09  0.000000e+00  1.101553e-10
         игил          0.000000e+00  4.997070e-09  0.000000e+00  0.000000e+00

                            topic_4
modality token
@word    инвалидность  1.638571e-10
         мазка         9.061746e-10
         professor     0.000000e+00
         умно          0.000000e+00
         игил          0.000000e+00

In [123]:
bank_model.get_phi().index

MultiIndex([('@word',   'инвалидность'),
            ('@word',          'мазка'),
            ('@word',      'professor'),
            ('@word',           'умно'),
            ('@word',           'игил'),
            ('@word',        'стучать'),
            ('@word',   'медлительный'),
            ('@word',    'газопылевой'),
            ('@word',       'разогрев'),
            ('@word',       'загрузка'),
            ...
            ('@word',           'зять'),
            ('@word', 'ниспровержение'),
            ('@word',        'пометка'),
            ('@word',       'франциск'),
            ('@word',           'wall'),
            ('@word',     'милосердие'),
            ('@word',        'поверка'),
            ('@word',            'вто'),
            ('@word',         'слоить'),
            ('@word',            'акт')],
           names=['modality', 'token'], length=19186)

In [122]:
model.get_phi().index

MultiIndex([('@word',   'инвалидность'),
            ('@word',          'мазка'),
            ('@word',      'professor'),
            ('@word',           'умно'),
            ('@word',           'игил'),
            ('@word',        'стучать'),
            ('@word',   'медлительный'),
            ('@word',    'газопылевой'),
            ('@word',       'разогрев'),
            ('@word',       'загрузка'),
            ...
            ('@word',           'зять'),
            ('@word', 'ниспровержение'),
            ('@word',        'пометка'),
            ('@word',       'франциск'),
            ('@word',           'wall'),
            ('@word',     'милосердие'),
            ('@word',        'поверка'),
            ('@word',            'вто'),
            ('@word',         'слоить'),
            ('@word',            'акт')],
           names=['modality', 'token'], length=19186)

In [173]:
all(bank_model.get_phi().index == model.get_phi().index)

True

In [124]:
optimizer._get_default_scores(model)

KeyError: 'perplexity_score'

In [144]:
bank_model.scores['perplexity_score']

[1836.541748046875,
 2707.664306640625,
 2707.67919921875,
 2707.679443359375,
 2707.679443359375,
 2707.679443359375,
 2707.679443359375,
 2707.679443359375]

In [147]:
bank_model.scores[f'PerplexityScore{modality}']

[nan, nan, nan, nan, nan, nan, nan]

In [150]:
bank_model.scores[f'test_ppl']

[2707.679443359375,
 2707.679443359375,
 2707.679443359375,
 2707.679443359375,
 2707.679443359375]

In [134]:
np.allclose(model.get_phi().values, bank_model.get_phi().values, atol=1e-5)

True

In [157]:
# model._model.scores.add(
#     artm.scores.PerplexityScore(name='test_ppl', class_ids=None)
# )
# model._model.scores.add(
#     artm.scores.PerplexityScore(name='test_ppl2', class_ids=None, dictionary=DATASET.get_dictionary())
# )
model._model.scores.add(
    artm.scores.PerplexityScore(name='test_ppl3', dictionary=DATASET.get_dictionary())
)
model._fit(
    DATASET.get_batch_vectorizer(),
    num_iterations=5,
    custom_regularizers={
        regularizer.name: regularizer,
    }
)

In [174]:
for m in DATASET.get_possible_modalities():
    model._model.scores.add(
        artm.scores.PerplexityScore(
            name=f'test_ppl{m}',
            class_ids=[m]
        )
    )
    model._model.scores.add(
        artm.scores.PerplexityScore(
            name=f'test_ppl{m}_with_d',
            class_ids=[m],
            dictionary=DATASET.get_dictionary()
        )
    )

model._model.scores.add(
    artm.scores.PerplexityScore(
        name=f'test_ppl@all',
        class_ids=DATASET.get_possible_modalities(),
    )
)
model._model.scores.add(
    artm.scores.PerplexityScore(
        name=f'test_ppl@all_2',
   )
)
model._model.scores.add(
    artm.scores.PerplexityScore(
        name=f'test_ppl@all_2_with_d',
        dictionary=DATASET.get_dictionary()
   )
)

In [175]:
model._fit(
    DATASET.get_batch_vectorizer(),
    num_iterations=5,
    custom_regularizers={
        regularizer.name: regularizer,
    }
)

In [143]:
model.scores['test_ppl']

[21684.888671875,
 21684.30078125,
 21683.7890625,
 21683.34375,
 21682.94921875,
 21682.603515625,
 21682.29296875,
 21682.017578125,
 21681.7734375,
 21681.55859375,
 21681.365234375,
 21681.1953125,
 21681.041015625,
 21680.896484375,
 21680.759765625,
 21680.634765625,
 21680.515625,
 21680.396484375,
 21680.28125,
 21680.1640625]

In [156]:
model.scores['test_ppl2']

[21680.048828125,
 21679.92578125,
 21679.798828125,
 21679.6640625,
 21679.521484375,
 21679.37109375,
 21679.2109375,
 21679.03515625,
 21678.841796875,
 21678.62109375,
 21678.357421875,
 21678.060546875,
 21677.73046875,
 21677.384765625,
 21677.048828125,
 21676.75390625,
 21676.513671875,
 21676.330078125,
 21676.201171875,
 21676.1015625]

In [158]:
model.scores['test_ppl3']

[21676.0234375, 21675.96484375, 21675.912109375, 21675.875, 21675.837890625]

In [154]:
for m in DATASET.get_possible_modalities():
    print(f'test_ppl{m}', bank_model.scores[f'test_ppl{m}'])
    print(f'test_ppl{m}_with_d', bank_model.scores[f'test_ppl{m}_with_d'])


print(f'test_ppl@all', bank_model.scores[f'test_ppl@all'])
print(f'test_ppl@all_2', bank_model.scores[f'test_ppl@all_2'])
print(f'test_ppl@all_2_with_d', bank_model.scores[f'test_ppl@all_2_with_d'])

test_ppl@title [nan, nan, nan, nan, nan]
test_ppl@title_with_d [nan, nan, nan, nan, nan]
test_ppl@2gramm [nan, nan, nan, nan, nan]
test_ppl@2gramm_with_d [nan, nan, nan, nan, nan]
test_ppl@author [nan, nan, nan, nan, nan]
test_ppl@author_with_d [nan, nan, nan, nan, nan]
test_ppl@snippet [nan, nan, nan, nan, nan]
test_ppl@snippet_with_d [nan, nan, nan, nan, nan]
test_ppl@post_tag [nan, nan, nan, nan, nan]
test_ppl@post_tag_with_d [nan, nan, nan, nan, nan]
test_ppl@word [nan, nan, nan, nan, nan]
test_ppl@word_with_d [nan, nan, nan, nan, nan]
test_ppl@3gramm [nan, nan, nan, nan, nan]
test_ppl@3gramm_with_d [nan, nan, nan, nan, nan]
test_ppl@all [nan, nan, nan, nan, nan]
test_ppl@all_2 [2707.679443359375, 2707.679443359375, 2707.679443359375, 2707.679443359375, 2707.679443359375]
test_ppl@all_2_with_d [6035.37841796875, 6035.37841796875, 6035.37841796875, 6035.37841796875, 6035.37841796875]

In [ ]:
# WTF???? all_2 vs all_2_with_d

In [176]:
for m in DATASET.get_possible_modalities():
    print(f'test_ppl{m}', model.scores[f'test_ppl{m}'])
    print(f'test_ppl{m}_with_d', model.scores[f'test_ppl{m}_with_d'])


print(f'test_ppl@all', model.scores[f'test_ppl@all'])
print(f'test_ppl@all_2', model.scores[f'test_ppl@all_2'])
print(f'test_ppl@all_2_with_d', model.scores[f'test_ppl@all_2_with_d'])

test_ppl@title [nan, nan, nan, nan, nan]
test_ppl@title_with_d [nan, nan, nan, nan, nan]
test_ppl@2gramm [nan, nan, nan, nan, nan]
test_ppl@2gramm_with_d [nan, nan, nan, nan, nan]
test_ppl@author [nan, nan, nan, nan, nan]
test_ppl@author_with_d [nan, nan, nan, nan, nan]
test_ppl@snippet [nan, nan, nan, nan, nan]
test_ppl@snippet_with_d [nan, nan, nan, nan, nan]
test_ppl@post_tag [nan, nan, nan, nan, nan]
test_ppl@post_tag_with_d [nan, nan, nan, nan, nan]
test_ppl@word [21675.8046875, 21675.7734375, 21675.744140625, 21675.7109375, 21675.67578125]
test_ppl@word_with_d [21675.8046875, 21675.7734375, 21675.744140625, 21675.7109375, 21675.67578125]
test_ppl@3gramm [nan, nan, nan, nan, nan]
test_ppl@3gramm_with_d [nan, nan, nan, nan, nan]
test_ppl@all [21675.8046875, 21675.7734375, 21675.744140625, 21675.7109375, 21675.67578125]
test_ppl@all_2 [21675.8046875, 21675.7734375, 21675.744140625, 21675.7109375, 21675.67578125]
test_ppl@all_2_with_d [21675.8046875, 21675.7734375, 21675.744140625, 21675.7109375, 21675.67578125]

In [159]:
np.allclose(model.get_phi().values, bank_model.get_phi().values, atol=1e-5)

True

In [163]:
np.allclose(model.get_theta(dataset=DATASET).values, bank_model.get_theta(dataset=DATASET).values, atol=1e-2)

False

In [166]:
model.get_theta(dataset=DATASET).head()

,2001.txt,2002.txt,2003.txt,2004.txt,2005.txt,2006.txt,2007.txt,2008.txt,2009.txt,2010.txt,...,991.txt,992.txt,993.txt,994.txt,995.txt,996.txt,997.txt,998.txt,999.txt,1000.txt
topic_0,0.056126,0.051794,0.027882,0.014199,0.043396,0.055867,0.077195,0.026650,0.108815,0.070042,...,0.046440,0.093659,0.037586,0.064593,0.000370,0.101226,0.006319,0.067003,0.146280,0.014262
topic_1,0.450934,0.030464,0.715602,0.750854,0.780230,0.683530,0.045779,0.174325,0.094343,0.779998,...,0.304143,0.398997,0.493840,0.040556,0.026051,0.104955,0.090535,0.459343,0.388860,0.046970
topic_2,0.456754,0.081020,0.108327,0.098719,0.082993,0.080848,0.186471,0.160910,0.130105,0.052453,...,0.252047,0.008952,0.303512,0.072870,0.883414,0.141408,0.106314,0.130316,0.053466,0.427126
topic_3,0.001702,0.121700,0.009623,0.045128,0.014734,0.064188,0.183776,0.140578,0.059057,0.026539,...,0.050335,0.154085,0.091995,0.060165,0.090149,0.129368,0.087532,0.112709,0.094390,0.501772
topic_4,0.034484,0.715021,0.138565,0.091100,0.078646,0.115567,0.506779,0.497538,0.607680,0.070969,...,0.347036,0.344307,0.073068,0.761816,0.000015,0.523044,0.709301,0.230629,0.317003,0.009870

In [168]:
model._cache_theta

False

In [170]:
model._model.transform(DATASET.get_batch_vectorizer())

,2001.txt,2002.txt,2003.txt,2004.txt,2005.txt,2006.txt,2007.txt,2008.txt,2009.txt,2010.txt,...,991.txt,992.txt,993.txt,994.txt,995.txt,996.txt,997.txt,998.txt,999.txt,1000.txt
topic_0,0.056126,0.051794,0.027882,0.014199,0.043396,0.055867,0.077195,0.026650,0.108815,0.070042,...,0.046440,0.093659,0.037586,0.064593,0.000370,0.101226,0.006319,0.067003,0.146280,0.014262
topic_1,0.450934,0.030464,0.715602,0.750854,0.780230,0.683530,0.045779,0.174325,0.094343,0.779998,...,0.304143,0.398997,0.493840,0.040556,0.026051,0.104955,0.090535,0.459343,0.388860,0.046970
topic_2,0.456754,0.081020,0.108327,0.098719,0.082993,0.080848,0.186471,0.160910,0.130105,0.052453,...,0.252047,0.008952,0.303512,0.072870,0.883414,0.141408,0.106314,0.130316,0.053466,0.427126
topic_3,0.001702,0.121700,0.009623,0.045128,0.014734,0.064188,0.183776,0.140578,0.059057,0.026539,...,0.050335,0.154085,0.091995,0.060165,0.090149,0.129368,0.087532,0.112709,0.094390,0.501772
topic_4,0.034484,0.715021,0.138565,0.091100,0.078646,0.115567,0.506779,0.497538,0.607680,0.070969,...,0.347036,0.344307,0.073068,0.761816,0.000015,0.523044,0.709301,0.230629,0.317003,0.009870

In [167]:
bank_model.get_theta(dataset=DATASET).head()

,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,...,990,991,992,993,994,995,996,997,998,999
topic_0,0.101861,0.074489,0.049455,0.022172,0.054905,0.070409,0.101073,0.037551,0.134165,0.113353,...,0.070619,0.112992,0.051316,0.073642,0.000986,0.127711,0.011525,0.099503,0.197428,0.015720
topic_1,0.655863,0.000609,0.372001,0.575786,0.645551,0.599838,0.032964,0.064134,0.050619,0.640101,...,0.185637,0.275330,0.352115,0.023438,0.018515,0.040171,0.048147,0.304867,0.152107,0.015568
topic_2,0.055471,0.127861,0.242632,0.168248,0.112799,0.103563,0.227997,0.224257,0.158512,0.091768,...,0.374002,0.016707,0.380625,0.084925,0.889346,0.168104,0.144765,0.185562,0.086654,0.441052
topic_3,0.027465,0.175088,0.037685,0.078449,0.029023,0.080083,0.235881,0.200229,0.075055,0.041916,...,0.081005,0.197989,0.120509,0.075768,0.091138,0.174744,0.105661,0.166301,0.153787,0.515394
topic_4,0.159340,0.621953,0.298227,0.155344,0.157723,0.146106,0.402084,0.473828,0.581650,0.112861,...,0.288736,0.396982,0.095435,0.742226,0.000015,0.489270,0.689901,0.243766,0.410024,0.012266

In [169]:
bank_model._cache_theta

False

In [171]:
bank_model._model.transform(DATASET.get_batch_vectorizer())

,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,...,990,991,992,993,994,995,996,997,998,999
topic_0,0.101861,0.074489,0.049455,0.022172,0.054905,0.070409,0.101073,0.037551,0.134165,0.113353,...,0.070619,0.112992,0.051316,0.073642,0.000986,0.127711,0.011525,0.099503,0.197428,0.015720
topic_1,0.655863,0.000609,0.372001,0.575786,0.645551,0.599838,0.032964,0.064134,0.050619,0.640101,...,0.185637,0.275330,0.352115,0.023438,0.018515,0.040171,0.048147,0.304867,0.152107,0.015568
topic_2,0.055471,0.127861,0.242632,0.168248,0.112799,0.103563,0.227997,0.224257,0.158512,0.091768,...,0.374002,0.016707,0.380625,0.084925,0.889346,0.168104,0.144765,0.185562,0.086654,0.441052
topic_3,0.027465,0.175088,0.037685,0.078449,0.029023,0.080083,0.235881,0.200229,0.075055,0.041916,...,0.081005,0.197989,0.120509,0.075768,0.091138,0.174744,0.105661,0.166301,0.153787,0.515394
topic_4,0.159340,0.621953,0.298227,0.155344,0.157723,0.146106,0.402084,0.473828,0.581650,0.112861,...,0.288736,0.396982,0.095435,0.742226,0.000015,0.489270,0.689901,0.243766,0.410024,0.012266