# TopicBank: Bank Creation Experiment

Here we are going to collect interpretable topics (automatically, using topic coherence) from multiple model training.
These topics constitute *topic bank*.
And then the topic bank is going to be used for estimating topic models quality in the notebook [TopicBank-Experiment: Model Validation](TopicBank-Experiment-ModelValidation.ipynb).

The process is repeated for several datasets (some of them are already downloadable using [TopicNet](https://github.com/machine-intelligence-laboratory/TopicNet) library).

# Contents<a id="contents"></a>

* [Data](#data)
    * [Coocs](#coocs)
        * [Lower Memory Consumption (or a Bit of Shamanism. Part 1)](#optimizing-memory)
    * [Documents for Coherence Scores](#docs-for-cohs)
        * [Lower Time Consumption in Case of Big Datasets (or a Bit of Shamanism. Part 2)](#optimizing-time)
* [Experiment](#experiment)
    * [Scores](#scores)
    * [Bank Creation](#bank-creation)
* [Postprocessing](#postprocessing)

In [2]:
# General imports

import dill
import itertools
import json
import numpy as np
import os
import pandas as pd
import sys
import time

from enum import Enum
from scipy.stats import gaussian_kde
from matplotlib import pyplot as plt
from tqdm import tqdm
from typing import (
    Dict,
    Iterable,
)

%matplotlib inline

In [3]:
# Making `topnum` module visible for Python

sys.path.insert(0, '../OptimalNumberOfTopics')

In [56]:
# Optimal number of topics

from topicnet.cooking_machine import Dataset

from topnum.data.vowpal_wabbit_text_collection import VowpalWabbitTextCollection
from topnum.scores import (
    PerplexityScore,
    SparsityPhiScore,
    SparsityThetaScore,
)
from topnum.scores.diversity_score import DiversityScore, KNOWN_METRICS
from topnum.scores._base_coherence_score import (
    SpecificityEstimationMethod,
    TextType,
    WordTopicRelatednessType,
)
from topnum.regularizers import (
    FastFixPhiRegularizer, DecorrelateWithOtherPhiRegularizer, DecorrelateWithOtherPhiRegularizer2
)
from topnum.scores.intratext_coherence_score import (
    IntratextCoherenceScore,
    ComputationMethod,
    WordTopicRelatednessType,
)
from topnum.search_methods import TopicBankMethod
from topnum.search_methods.topic_bank.topic_bank import TopicBank
from topnum.search_methods.topic_bank.one_model_train_funcs import (
    default_train_func,

    # Functions below are not used (but could have been)

#     regularization_train_func,
#     specific_initial_phi_train_func,
#     background_topics_train_func,

)

## Data<a id="data"></a>

<div style="text-align: right">Back to <a href=#contents>Contents</a></div>

Loading data from disk, creating batches, dictionary, gathering cooccurrence statistics...

In [5]:
DATA_FOLDER_PATH = '/data_mil/shared/CompressaAI/iterative/data/noow'

In [6]:
sorted(os.listdir(DATA_FOLDER_PATH))

['20_Newsgroups_NOOW.csv',
 '20_Newsgroups_NOOW__internals',
 'MKB_10_NOOW.csv',
 'MKB_10_NOOW__internals',
 'MKB_10__internals',
 'Post_Science_NOOW.csv',
 'Post_Science_NOOW__internals',
 'Post_Science_NOOW_fixed.csv',
 'Post_Science_NOOW_fixed__internals',
 'Post_Science__internals',
 'WikiRef_220_NOOW.csv',
 '_20_Newsgroups.csv',
 '_20_Newsgroups__internals',
 '_Lenta.csv']

In [7]:
class DatasetName(Enum):
    POSTNAUKA = 'Post_Science'
    # REUTERS = 'Reuters'
    # BROWN = 'Brown'
    TWENTY_NEWSGROUPS = '20_Newsgroups'

In [8]:
DATASET_NAME_TO_DATASET_FILE_PATH = {
    DatasetName.POSTNAUKA: os.path.join(
        DATA_FOLDER_PATH, 'postnauka.csv'
    ),
    # DatasetName.REUTERS: os.path.join(
    #     DATA_FOLDER_PATH, 'Reuters.csv'
    # ),
    # DatasetName.BROWN: os.path.join(
    #     DATA_FOLDER_PATH, 'Brown.csv'
    # ),
    DatasetName.TWENTY_NEWSGROUPS: os.path.join(
        DATA_FOLDER_PATH, '20_Newsgroups_NOOW.csv'
    ),
    # DatasetName.AG_NEWS: os.path.join(
    #     DATA_FOLDER_PATH, 'AG_News.csv'
    # ),
    # DatasetName.WATAN: os.path.join(
    #     DATA_FOLDER_PATH, 'Watan2004.csv'
    # ),
    # DatasetName.HABRAHABR: os.path.join(
    #     DATA_FOLDER_PATH, 'Habrahabr.csv'
    # ),
}

In [9]:
DATASET_NAME = DatasetName.TWENTY_NEWSGROUPS  # select a dataset here

DATASET_FILE_PATH = DATASET_NAME_TO_DATASET_FILE_PATH[DATASET_NAME]

Checking if all OK with data, what modalities does the collection have.

In [10]:
! head -n 2 $DATASET_FILE_PATH

raw_text,id,vw_text
"I was wondering if anyone out there could enlighten me on this car I saw

In [11]:
def get_dataset_internals_folder_path(dataset_name: DatasetName) -> str:
    return os.path.join(DATA_FOLDER_PATH, dataset_name.value + '__internals')

In [12]:
DATASET_INTERNALS_FOLDER_PATH = get_dataset_internals_folder_path(DATASET_NAME)

In [13]:
DATASET_INTERNALS_FOLDER_PATH

'/data_mil/shared/CompressaAI/iterative/data/noow/20_Newsgroups__internals'

In [14]:
%%time

# If using really big datasets (like Habrahabr),
# one may need to set this equal `False`
KEEP_DATASET_IN_MEMORY = True

DATASET = Dataset(
    DATASET_FILE_PATH,
    internals_folder_path=DATASET_INTERNALS_FOLDER_PATH,
    keep_in_memory=KEEP_DATASET_IN_MEMORY,
)

CPU times: user 3.21 s, sys: 297 ms, total: 3.51 s
Wall time: 1.58 s

Looking what is inside dataset's folder

In [15]:
os.listdir(DATASET_INTERNALS_FOLDER_PATH)

['dict.dict', 'batches', 'vw.txt']

In [17]:
DATASET.get_possible_modalities()

{'@lemmatized'}

In [18]:
MAIN_MODALITY = '@lemmatized'

In [19]:
dictionary = DATASET.get_dictionary()

print(dictionary)

for modality in DATASET.get_possible_modalities():
    if modality not in [MAIN_MODALITY]:
        dictionary.filter(class_id=modality, max_df=0, inplace=True)

print(dictionary)

artm.Dictionary(name=7c5c8f34-b670-4348-a275-21f2f47a0094, num_entries=52744)
artm.Dictionary(name=7c5c8f34-b670-4348-a275-21f2f47a0094, num_entries=52744)

In [20]:
DATASET._cached_dict = dictionary

Creating batches

In [21]:
DATASET.get_batch_vectorizer()

artm.BatchVectorizer(data_path="/data_mil/shared/CompressaAI/iterative/data/noow/20_Newsgroups__internals/batches", num_batches=12)

In [22]:
os.listdir(DATASET_INTERNALS_FOLDER_PATH)

['dict.dict', 'batches', 'vw.txt']

In [23]:
if KEEP_DATASET_IN_MEMORY:
    DOCUMENTS = list(DATASET._data.index)
else:
    DOCUMENTS = list(DATASET._data_index)

NUM_DOCUMENTS = len(DOCUMENTS)

print(f'Num documents: {NUM_DOCUMENTS}')

Num documents: 11301

Let's look at some text samples

In [24]:
DATASET._data.head()

,raw_text,id,vw_text
id,,,
rec_autos_102994,I was wondering if anyone out there could enli...,rec_autos_102994,rec_autos_102994 |@lemmatized wonder anyone co...
comp_sys_mac_hardware_51861,A fair number of brave souls who upgraded thei...,comp_sys_mac_hardware_51861,comp_sys_mac_hardware_51861 |@lemmatized fair ...
comp_sys_mac_hardware_51879,"well folks, my mac plus finally gave up the gh...",comp_sys_mac_hardware_51879,comp_sys_mac_hardware_51879 |@lemmatized well ...
comp_graphics_38242,\nDo you have Weitek's address/phone number? ...,comp_graphics_38242,comp_graphics_38242 |@lemmatized weitek addres...
sci_space_60880,"From article <C5owCB.n3p@world.std.com>, by to...",sci_space_60880,sci_space_60880 |@lemmatized article tom baker...

In [25]:
DATASET.get_possible_modalities()

{'@lemmatized'}

In [26]:
MAIN_MODALITY = '@lemmatized'

In [27]:
import scipy

from typing import List

from topicnet.cooking_machine.models.base_regularizer import BaseRegularizer
from topicnet.cooking_machine.models.thetaless_regularizer import (
    dataset2sparse_matrix,
)
from topicnet.cooking_machine.models import (
    BaseScore as BaseTopicNetScore,
    TopicModel
)

In [28]:
def calc_doc_occurrences(dataset, modality):
    """
    :param n_dw_matrix: sparse document-word matrix, shape is D x W
    :return: sparse matrix of co-occurrences

    doc_occurrences[w1, w2] = the number of the documents
    where there are w1 and w2
    """
    n_dw_matrix = dataset2sparse_matrix(dataset, modality, modalities_to_use=[modality])
    matrix = (scipy.sparse.csc_matrix(n_dw_matrix) > 0).astype(int)
    co_occurrences = matrix.T * matrix

    return co_occurrences.diagonal(), co_occurrences


def create_pmi_top_function(
    doc_occurrences, doc_co_occurrences,
    documents_number, top_sizes,
    topic_indices=None,
    co_occurrences_smooth=1.
):
    """
    :param doc_occurrences: array of doc occurrences of words
    :param doc_co_occurrences: sparse matrix of doc co-occurrences of words
    :param documents_number: number of the documents
    :param top_sizes: list of top values to calculate top-pmi for
    :param co_occurrences_smooth: constant to smooth co-occurrences in log
    :return: function which takes phi and theta and returns
    pair of two arrays: pmi-s of the tops and ppmi-s of the tops

    pmi[i] - pmi(top of size top_sizes[i])
    ppmi[i] - ppmi(top of size top_sizes[i])

    pmi(words) = sum_{u in words, v in words, u != v}
    log(
        (doc_co_occurrences[u, v] * documents_number + co_occurrences_smooth)
        / doc_occurrences[u] / doc_occurrences[v]
    )

    ppmi(words) = sum_{u in words, v in words, u != v}
    max(log(
        (doc_co_occurrences[u, v] * documents_number + co_occurrences_smooth)
        / doc_occurrences[u] / doc_occurrences[v]
    ), 0)

    """
    def func(phi):
        T, W = phi.shape
        # T = len(topic_indices)
        topic_indices = list(range(T))

        max_top_size = max(top_sizes)
        topic_pmis, topic_ppmis = dict(), dict()
        pmi, ppmi = np.zeros(max_top_size), np.zeros(max_top_size)
        tops = np.argpartition(phi, -max_top_size, axis=1)[:, -max_top_size:]
        
        for t in topic_indices:
            top = sorted(tops[t], key=lambda w: - phi[t, w])
            # print(top, phi.shape, doc_co_occurrences.shape)
            co_occurrences = doc_co_occurrences[top, :][:, top].todense()
            occurrences = doc_occurrences[top]
            values = np.log(
                (co_occurrences * documents_number + co_occurrences_smooth)
                / (occurrences[:, np.newaxis] * occurrences[np.newaxis, :] + co_occurrences_smooth)
            )
            diag = np.diag_indices(len(values))
            # values.cumsum(axis=0).cumsum(axis=1)[diag] - values[diag].cumsum()

            current_pmi = np.array(
               values.cumsum(axis=0).cumsum(axis=1)[diag] - values[diag].cumsum()
            ).ravel()
            topic_pmis[t] = current_pmi
            pmi += current_pmi

            values[values < 0.] = 0.
            current_ppmi = np.array(
               values.cumsum(axis=0).cumsum(axis=1)[diag] - values[diag].cumsum()
            ).ravel()
            topic_ppmis[t] = current_ppmi
            ppmi += current_ppmi
            
        sizes = np.arange(2, max_top_size + 1)
        pmi[1:] /= (T * sizes * (sizes - 1))
        ppmi[1:] /= (T * sizes * (sizes - 1))
        indices = np.array(top_sizes) - 1

        for t in topic_indices:
            topic_pmis[t][1:] /= (sizes * (sizes - 1))
            topic_ppmis[t][1:] /= (sizes * (sizes - 1))

        result_topic_pmis = {t: p[indices] for t, p in topic_pmis.items()}
        result_topic_ppmis = {t: p[indices] for t, p in topic_ppmis.items()}

        return pmi[indices], ppmi[indices], result_topic_pmis, result_topic_ppmis

    return func

In [29]:
%%time

occurences, co_occurences = calc_doc_occurrences(DATASET, MAIN_MODALITY)

CPU times: user 3.15 s, sys: 119 ms, total: 3.27 s
Wall time: 3.23 s

In [30]:
calc_pmi = create_pmi_top_function(
    occurences, co_occurences,
    DATASET.get_dataset().shape[0], [20],
    topic_indices=[0, 1, 2],
    co_occurrences_smooth=1e-2,
)

In [31]:
import copy


class TopTokenCoherence(BaseTopicNetScore):
    def __init__(self, name, func):
        super().__init__()

        self._name = name
        self.calc_pmi = func

    @property
    def name(self):
        return self._name

    def call(self, model: TopicModel):
        values = self.calc_pmi(model.get_phi_dense()[0].T)

        return values[1]

    def call_by_topic(self, model: TopicModel):
        values = self.calc_pmi(model.get_phi_dense()[0].T)

        return values[3]

    def compute(
            self,
            model,
            topics: List[str] = None,
            documents: List[str] = None) -> Dict[str, float]:

        values = self.call_by_topic(model)

        phi = model.get_phi()

        if topics is None:
            topics = list(phi.columns)

            if hasattr(model, 'has_bcg'):
                print(f'Detected bcg topics! Skipping for coherence computation (and will have {len(topics) - 1} topics).')

                topics = topics[:-1]
        else:
            assert False

        index2topic = {phi.columns.get_loc(t): t for t in topics}
        topic2index = {t: i for i, t in index2topic.items()}

        if hasattr(model, 'has_bcg'):
            assert list(index2topic.keys()) == list(values.keys())[:-1]
        else:
            assert list(index2topic.keys()) == list(values.keys())

        result = {
            t: float(values[topic2index[t]])
            for t in topics
        }

        assert len(result) == len(index2topic)

        return result

    def _attach(self, model: TopicModel):
        if self._name in model.custom_scores:
            print(
                f'Score with such name "{self._name}" already attached to model!'
                f' So rewriting it...'
                f' All model\'s custom scores: {list(model.custom_scores.keys())}'
            )

        # TODO: TopicModel should provide ability to add custom scores
        model.custom_scores[self.name] = copy.deepcopy(self)

## Experiment<a id="experiment"></a>

Finally we are getting to the main part!)

### Scores (for Topics and Models)<a id="scores"></a>

<div style="text-align: right">Back to <a href=#contents>Contents</a></div>

Here we define a lot of scores (which mainly differ in initial parameters).

In [32]:
ONE_MODEL_NUM_TOPICS = 20
NUM_TOP_WORDS = 20

In [33]:
top = NUM_TOP_WORDS
target_topic_indices = list(range(ONE_MODEL_NUM_TOPICS))

coherence_score = TopTokenCoherence(
    name=f'coherence_{top}',
    func=create_pmi_top_function(
        occurences, co_occurences,
        DATASET.get_dataset().shape[0], [top],
        # topic_indices=target_topic_indices,
        co_occurrences_smooth=1e-2,
    )
)

intra_coherence_score = IntratextCoherenceScore(
    name='toplen_ptw',
    data=DATASET,
    computation_method=ComputationMethod.SEGMENT_LENGTH,
    word_topic_relatedness=WordTopicRelatednessType.PTW,
    should_compute=False,
)

diversity_scores = [
    DiversityScore(
        name=f'diversity_{metric}',
        metric=metric,
        class_ids=MAIN_MODALITY,
    )

    for metric in KNOWN_METRICS
]

Other coherence score variations

And a pair of default ARTM scores (these ones are fast)

In [34]:
other_scores = [
    PerplexityScore(
        name='perplexity'
    ),
]

### Bank Creation<a id="bank-creation"></a>

<div style="text-align: right">Back to <a href=#contents>Contents</a></div>

Here we finally run the experiment!

In [35]:
NUM_ITERATIONS = 20

In [36]:
seed = 0

In [227]:
# We use only one train function here
# Other variations are also possible
# It would be even better to make bank using several train functions
# However, it would also take way more time 

TRAIN_FUNCS = default_train_func  # default train func

In [228]:
DATASET_INTERNALS_FOLDER_PATH

'./20_Newsgroups__internals'

In [229]:
SEARCH_RESULTS_FOLDER_PATH = os.path.join(
    DATASET_INTERNALS_FOLDER_PATH, 'result'
)

# File with some info about the process
SEARCH_RESULT_FILE_PATH = os.path.join(
    SEARCH_RESULTS_FOLDER_PATH, f'search_result__{seed}.json'
)

# Bank, with topics and their score values
BANK_FOLDER_PATH = os.path.join(
    SEARCH_RESULTS_FOLDER_PATH, f'bank__{seed}'
)

In [230]:
! echo $DATASET_INTERNALS_FOLDER_PATH
! ls -alh $DATASET_INTERNALS_FOLDER_PATH

./20_Newsgroups__internals
total 12M
drwxrwxr-x 3 alekseev_v mil_lab 4,0K мар 23 17:16 .
drwxrwxr-x 6 alekseev_v mil_lab 4,0K мар 23 17:16 ..
drwxrwxr-x 2 alekseev_v mil_lab 4,0K мар 23 15:06 batches
-rw-rw-r-- 1 alekseev_v mil_lab 2,7M мар 23 15:06 dict.dict
-rw-rw-r-- 1 alekseev_v mil_lab 8,6M мар 23 15:06 vw.txt

In [231]:
SEARCH_RESULTS_FOLDER_PATH

'./20_Newsgroups__internals/result'

In [232]:
! ls $SEARCH_RESULTS_FOLDER_PATH

ls: cannot access './20_Newsgroups__internals/result': No such file or directory

In [233]:
BANK_FOLDER_PATH

'./20_Newsgroups__internals/result/bank__0'

In [234]:
os.makedirs(SEARCH_RESULTS_FOLDER_PATH, exist_ok=True)
os.makedirs(BANK_FOLDER_PATH, exist_ok=True)

In [235]:
seed

0

In [42]:
from topnum.model_constructor import init_model_from_family

model = init_model_from_family(
    family='PLSA',
    dataset=DATASET,
    main_modality=MAIN_MODALITY,
    num_topics=10,
    seed=42,
)

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

In [43]:
model.get_phi().shape

(52744, 10)

In [44]:
from topnum.search_methods.topic_bank.one_model_train_funcs import (default_train_func, _get_topic_model)

In [47]:
model = _get_topic_model(DATASET, MAIN_MODALITY, num_topics=10)

In [48]:
model.get_phi().shape

(52744, 10)

In [49]:
dictionary = DATASET.get_dictionary()

In [50]:
dictionary

artm.Dictionary(name=ed4c5149-fc08-4aa4-a871-43e8e3726b8f, num_entries=74043)

In [236]:
# https://github.com/machine-intelligence-laboratory/OptimalNumberOfTopics/blob/master/topnum/model_constructor.py#L120C5-L122C73

dictionary = DATASET.get_dictionary()

print(dictionary)

for modality in DATASET.get_possible_modalities():
    if modality not in [MAIN_MODALITY]:
        dictionary.filter(class_id=modality, max_df=0, inplace=True)

artm.Dictionary(name=25ea49d0-9244-4010-9ad4-579e1997c8f5, num_entries=52744)

In [133]:
print(dictionary)

artm.Dictionary(name=2add8e57-4e14-4899-ac41-8f1800224d51, num_entries=52744)

In [134]:
len(DATASET._data)

11301

In [135]:
len(DATASET._data)

11301

In [136]:
# dictionary.filter(min_df=5, max_df_rate=0.5)

artm.Dictionary(name=2add8e57-4e14-4899-ac41-8f1800224d51, num_entries=12269)

In [170]:
DATASET._cached_dict = dictionary

In [222]:
DATASET.get_dictionary()

artm.Dictionary(name=25ea49d0-9244-4010-9ad4-579e1997c8f5, num_entries=52744)

One cay vary some parameters below (for example `max_num_models` and `num_fit_iterations`).

In [237]:
optimizer = TopicBankMethod(
    data        = DATASET,
    main_modality = MAIN_MODALITY,
    
    min_df_rate = 0.0,  # dictionary filtering has already been done little earlier
    max_df_rate = 1.0,  #   so we don't want these parameters to have any effect

    main_topic_score   = coherence_score,
    other_topic_scores = [],
    other_scores       = [coherence_score] + diversity_scores + other_scores,
   # documents          = TEST_DOCUMENTS,

    start_model_number   = 0,
    max_num_models       = 20,
    one_model_num_topics = ONE_MODEL_NUM_TOPICS,  # 100,
    num_fit_iterations   = NUM_ITERATIONS,  # 100,  # 100 should be enough;
                                 # however, for big data better to reduce this one
                                 # (otherwise the process will be too slow)

    topic_score_threshold_percentile = 90,

    save_bank         = True,
    save_model_topics = True,
    save_file_path    = SEARCH_RESULT_FILE_PATH,
    bank_folder_path  = BANK_FOLDER_PATH,

    train_funcs = TRAIN_FUNCS,
    
    verbose = True,
)

# TODO: use Holdout Perplexity as Stop score

In [238]:
optimizer._result.keys()

dict_keys(['optimum', 'optimum_std', 'bank_scores', 'bank_topic_scores', 'model_scores', 'model_topic_scores', 'num_bank_topics', 'num_model_topics'])

Checking file paths

In [239]:
! echo $DATASET_INTERNALS_FOLDER_PATH
! ls $DATASET_INTERNALS_FOLDER_PATH

./20_Newsgroups__internals
batches  dict.dict  result  vw.txt

In [240]:
optimizer._save_file_path

'./20_Newsgroups__internals/result/search_result__0.json'

In [241]:
optimizer._topic_bank._path

'./20_Newsgroups__internals/result/bank__0'

Fulfilling the search (get ready for a really long process!):

In [242]:
%%time

optimizer.search_for_optimum(DATASET)

  0%|                                                        | 0/20 [00:00<?, ?it/s]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.99it/s]

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 33887.86328125, 'coherence_20': 2.143789628708131, 'diversity_euclidean': 0.05341330761928905, 'diversity_jensenshannon': 0.6766701845333501, 'diversity_hellinger': 0.79047033745248, 'diversity_cosine': 0.8464355099609286, 'perplexity': 33887.86328125, 'ppl_fair': 33887.86328125, 'ppl_cheatty': 4493.0029296875}
  5%|██▍                                             | 1/20 [00:37<11:44, 37.06s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.44it/s]

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 24307.318359375, 'coherence_20': 1.9844211806263499, 'diversity_euclidean': 0.055584392872178895, 'diversity_jensenshannon': 0.7065315808048284, 'diversity_hellinger': 0.8268121742258213, 'diversity_cosine': 0.8739049313866097, 'perplexity': 24307.318359375, 'ppl_fair': 24307.318359375, 'ppl_cheatty': 4190.05908203125}
 10%|████▊                                           | 2/20 [01:27<13:33, 45.20s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.91it/s]

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 24307.318359375, 'coherence_20': 1.9844211806263499, 'diversity_euclidean': 0.05558439287217822, 'diversity_jensenshannon': 0.7065315808045934, 'diversity_hellinger': 0.8268121742255166, 'diversity_cosine': 0.8739049313865842, 'perplexity': 24307.318359375, 'ppl_fair': 24307.318359375, 'ppl_cheatty': 4190.05908203125}
 15%|███████▏                                        | 3/20 [02:15<13:03, 46.08s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.84it/s]

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 24307.318359375, 'coherence_20': 1.9844211806263499, 'diversity_euclidean': 0.055584392872176945, 'diversity_jensenshannon': 0.7065315808043017, 'diversity_hellinger': 0.8268121742255484, 'diversity_cosine': 0.8739049313865697, 'perplexity': 24307.318359375, 'ppl_fair': 24307.318359375, 'ppl_cheatty': 4190.05908203125}
 20%|█████████▌                                      | 4/20 [03:02<12:28, 46.80s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.74it/s]

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 24307.318359375, 'coherence_20': 1.9844211806263499, 'diversity_euclidean': 0.055584392872176945, 'diversity_jensenshannon': 0.706531580804283, 'diversity_hellinger': 0.8268121742255042, 'diversity_cosine': 0.8739049313865697, 'perplexity': 24307.318359375, 'ppl_fair': 24307.318359375, 'ppl_cheatty': 4190.05908203125}
 25%|████████████                                    | 5/20 [03:50<11:47, 47.17s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.96it/s]

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 24307.318359375, 'coherence_20': 1.9844211806263499, 'diversity_euclidean': 0.055584392872176945, 'diversity_jensenshannon': 0.7065315808043132, 'diversity_hellinger': 0.8268121742254984, 'diversity_cosine': 0.8739049313865697, 'perplexity': 24307.318359375, 'ppl_fair': 24307.318359375, 'ppl_cheatty': 4190.05908203125}
 30%|██████████████▍                                 | 6/20 [04:39<11:08, 47.73s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.66it/s]

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 24307.318359375, 'coherence_20': 1.9844211806263499, 'diversity_euclidean': 0.05558439287217721, 'diversity_jensenshannon': 0.706531580804482, 'diversity_hellinger': 0.8268121742256717, 'diversity_cosine': 0.8739049313865817, 'perplexity': 24307.318359375, 'ppl_fair': 24307.318359375, 'ppl_cheatty': 4190.05908203125}
 35%|████████████████▊                               | 7/20 [05:28<10:26, 48.20s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.86it/s]

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 24307.318359375, 'coherence_20': 1.9844211806263499, 'diversity_euclidean': 0.055584392872177195, 'diversity_jensenshannon': 0.7065315808044709, 'diversity_hellinger': 0.8268121742254831, 'diversity_cosine': 0.8739049313865817, 'perplexity': 24307.318359375, 'ppl_fair': 24307.318359375, 'ppl_cheatty': 4190.05908203125}
 40%|███████████████████▏                            | 8/20 [06:17<09:42, 48.51s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.77it/s]

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 24307.318359375, 'coherence_20': 1.9844211806263499, 'diversity_euclidean': 0.05558439287217796, 'diversity_jensenshannon': 0.7065315808044267, 'diversity_hellinger': 0.8268121742254806, 'diversity_cosine': 0.8739049313865723, 'perplexity': 24307.318359375, 'ppl_fair': 24307.318359375, 'ppl_cheatty': 4190.05908203125}
 45%|█████████████████████▌                          | 9/20 [07:08<09:01, 49.22s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.86it/s]

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 24307.318359375, 'coherence_20': 1.9844211806263499, 'diversity_euclidean': 0.05558439287217796, 'diversity_jensenshannon': 0.7065315808044321, 'diversity_hellinger': 0.8268121742255085, 'diversity_cosine': 0.8739049313865724, 'perplexity': 24307.318359375, 'ppl_fair': 24307.318359375, 'ppl_cheatty': 4190.05908203125}
 50%|███████████████████████▌                       | 10/20 [07:57<08:11, 49.18s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.93it/s]

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 24307.318359375, 'coherence_20': 1.9844211806263499, 'diversity_euclidean': 0.05558439287217796, 'diversity_jensenshannon': 0.7065315808044391, 'diversity_hellinger': 0.8268121742255725, 'diversity_cosine': 0.8739049313865724, 'perplexity': 24307.318359375, 'ppl_fair': 24307.318359375, 'ppl_cheatty': 4190.05908203125}
 55%|█████████████████████████▊                     | 11/20 [08:45<07:19, 48.85s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.91it/s]

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 20406.341796875, 'coherence_20': 2.2902439616534376, 'diversity_euclidean': 0.0529993253962619, 'diversity_jensenshannon': 0.7384915005805835, 'diversity_hellinger': 0.8695520055818902, 'diversity_cosine': 0.882407099262262, 'perplexity': 20406.341796875, 'ppl_fair': 20406.341796875, 'ppl_cheatty': 4056.141357421875}
 60%|████████████████████████████▏                  | 12/20 [09:36<06:34, 49.28s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.87it/s]

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 20406.341796875, 'coherence_20': 2.2902439616534376, 'diversity_euclidean': 0.0529993253962619, 'diversity_jensenshannon': 0.7384915005805913, 'diversity_hellinger': 0.8695520055818896, 'diversity_cosine': 0.882407099262262, 'perplexity': 20406.341796875, 'ppl_fair': 20406.341796875, 'ppl_cheatty': 4056.141357421875}
 65%|██████████████████████████████▌                | 13/20 [10:27<05:50, 50.01s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.74it/s]

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 20406.341796875, 'coherence_20': 2.2902439616534376, 'diversity_euclidean': 0.05299932539626162, 'diversity_jensenshannon': 0.7384915005805488, 'diversity_hellinger': 0.8695520055818751, 'diversity_cosine': 0.8824070992622611, 'perplexity': 20406.341796875, 'ppl_fair': 20406.341796875, 'ppl_cheatty': 4056.141357421875}
 70%|████████████████████████████████▉              | 14/20 [11:19<05:03, 50.51s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.92it/s]

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 20406.341796875, 'coherence_20': 2.2902439616534376, 'diversity_euclidean': 0.05299932539626162, 'diversity_jensenshannon': 0.7384915005805318, 'diversity_hellinger': 0.8695520055818692, 'diversity_cosine': 0.8824070992622611, 'perplexity': 20406.341796875, 'ppl_fair': 20406.341796875, 'ppl_cheatty': 4056.141357421875}
 75%|███████████████████████████████████▎           | 15/20 [12:08<04:10, 50.10s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.84it/s]

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 20406.341796875, 'coherence_20': 2.2902439616534376, 'diversity_euclidean': 0.0529993253962619, 'diversity_jensenshannon': 0.7384915005805809, 'diversity_hellinger': 0.869552005581881, 'diversity_cosine': 0.882407099262262, 'perplexity': 20406.341796875, 'ppl_fair': 20406.341796875, 'ppl_cheatty': 4056.141357421875}
 80%|█████████████████████████████████████▌         | 16/20 [13:00<03:22, 50.62s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.89it/s]

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 20406.341796875, 'coherence_20': 2.2902439616534376, 'diversity_euclidean': 0.0529993253962619, 'diversity_jensenshannon': 0.7384915005805915, 'diversity_hellinger': 0.8695520055819145, 'diversity_cosine': 0.882407099262262, 'perplexity': 20406.341796875, 'ppl_fair': 20406.341796875, 'ppl_cheatty': 4056.141357421875}
 85%|███████████████████████████████████████▉       | 17/20 [13:52<02:32, 50.95s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.92it/s]

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 20406.341796875, 'coherence_20': 2.2902439616534376, 'diversity_euclidean': 0.0529993253971461, 'diversity_jensenshannon': 0.7384915005771474, 'diversity_hellinger': 0.8695520056003677, 'diversity_cosine': 0.8824070992460776, 'perplexity': 20406.341796875, 'ppl_fair': 20406.341796875, 'ppl_cheatty': 4056.141357421875}
 90%|██████████████████████████████████████████▎    | 18/20 [14:44<01:42, 51.20s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.85it/s]

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 20406.341796875, 'coherence_20': 2.2902439616534376, 'diversity_euclidean': 0.0529993253962619, 'diversity_jensenshannon': 0.7384915005805848, 'diversity_hellinger': 0.8695520055818742, 'diversity_cosine': 0.882407099262262, 'perplexity': 20406.341796875, 'ppl_fair': 20406.341796875, 'ppl_cheatty': 4056.141357421875}
 95%|████████████████████████████████████████████▋  | 19/20 [15:35<00:51, 51.29s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.62it/s]

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 20406.341796875, 'coherence_20': 2.2902439616534376, 'diversity_euclidean': 0.0529993253962619, 'diversity_jensenshannon': 0.7384915005805817, 'diversity_hellinger': 0.8695520055818792, 'diversity_cosine': 0.882407099262262, 'perplexity': 20406.341796875, 'ppl_fair': 20406.341796875, 'ppl_cheatty': 4056.141357421875}
100%|███████████████████████████████████████████████| 20/20 [16:27<00:00, 49.36s/it]
CPU times: user 24min 7s, sys: 46.4 s, total: 24min 53s
Wall time: 16min 27s

What topics we have in bank

In [244]:
optimizer._topic_bank.view_topics().head()

                        topic_0  topic_1  topic_2  topic_3
@lemmatized ingolf          0.0      0.0      0.0      0.0
            tcshrc          0.0      0.0      0.0      0.0
            ftek            0.0      0.0      0.0      0.0
            chewer          0.0      0.0      0.0      0.0
            petroglyph      0.0      0.0      0.0      0.0

In [245]:
bank_topics = optimizer._topic_bank.view_topics()

In [246]:
bank_topics.shape

(52744, 4)

In [247]:
bank_topics.head()

                        topic_0  topic_1  topic_2  topic_3
@lemmatized ingolf          0.0      0.0      0.0      0.0
            tcshrc          0.0      0.0      0.0      0.0
            ftek            0.0      0.0      0.0      0.0
            chewer          0.0      0.0      0.0      0.0
            petroglyph      0.0      0.0      0.0      0.0

In [249]:
bank_topics['topic_3'].sort_values(ascending=False)[:20]

@lemmatized  msg      0.009260
             bos      0.007669
             min      0.006862
             water    0.005958
             det      0.005838
             food     0.005613
             tor      0.005552
             van      0.005420
             la       0.005361
             que      0.005254
             chi      0.005209
             nj       0.004942
             pit      0.004643
             cal      0.004550
             buf      0.004116
             nyi      0.003989
             tb       0.003969
             nyr      0.003842
             dept     0.003741
             mon      0.003631
Name: topic_3, dtype: float64

And topic scores

In [250]:
optimizer._topic_bank.view_topic_scores()

                         topic_0      topic_1      topic_2      topic_3
kernel_size          6290.000000  5987.000000  4904.000000  6419.000000
coherence_20            1.936586     2.350994     1.665684     3.207712
distance_to_nearest     0.000000     0.867080     0.906865     0.916330

All models are also saved (topics as $\Phi$ matrices and topic score values)

In [251]:
! ls $optimizer._topic_bank._path

model_0__phi.bin	    model_19__topic_scores.bin
model_0__topic_scores.bin   model_1__phi.bin
model_10__phi.bin	    model_1__topic_scores.bin
model_10__topic_scores.bin  model_2__phi.bin
model_11__phi.bin	    model_2__topic_scores.bin
model_11__topic_scores.bin  model_3__phi.bin
model_12__phi.bin	    model_3__topic_scores.bin
model_12__topic_scores.bin  model_4__phi.bin
model_13__phi.bin	    model_4__topic_scores.bin
model_13__topic_scores.bin  model_5__phi.bin
model_14__phi.bin	    model_5__topic_scores.bin
model_14__topic_scores.bin  model_6__phi.bin
model_15__phi.bin	    model_6__topic_scores.bin
model_15__topic_scores.bin  model_7__phi.bin
model_16__phi.bin	    model_7__topic_scores.bin
model_16__topic_scores.bin  model_8__phi.bin
model_17__phi.bin	    model_8__topic_scores.bin
model_17__topic_scores.bin  model_9__phi.bin
model_18__phi.bin	    model_9__topic_scores.bin
model_18__topic_scores.bin  topics.bin
model_19__phi.bin	    topic_scores.bin

In [252]:
optimizer._result.keys()

dict_keys(['optimum', 'optimum_std', 'bank_scores', 'bank_topic_scores', 'model_scores', 'model_topic_scores', 'num_bank_topics', 'num_model_topics'])

In [253]:
optimizer._result['num_bank_topics']

[2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4]

In [254]:
len(optimizer._result['bank_topic_scores'])

20

In [255]:
optimizer._result

{'optimum': 4,
 'optimum_std': 5.0,
 'bank_scores': [{'perplexity_score': 33887.86328125,
   'coherence_20': 2.143789628708131,
   'diversity_euclidean': 0.05341330761928905,
   'diversity_jensenshannon': 0.6766701845333501,
   'diversity_hellinger': 0.79047033745248,
   'diversity_cosine': 0.8464355099609286,
   'perplexity': 33887.86328125,
   'ppl_fair': 33887.86328125,
   'ppl_cheatty': 4493.0029296875},
  {'perplexity_score': 24307.318359375,
   'coherence_20': 1.9844211806263499,
   'diversity_euclidean': 0.055584392872178895,
   'diversity_jensenshannon': 0.7065315808048284,
   'diversity_hellinger': 0.8268121742258213,
   'diversity_cosine': 0.8739049313866097,
   'perplexity': 24307.318359375,
   'ppl_fair': 24307.318359375,
   'ppl_cheatty': 4190.05908203125},
  {'perplexity_score': 24307.318359375,
   'coherence_20': 1.9844211806263499,
   'diversity_euclidean': 0.05558439287217822,
   'diversity_jensenshannon': 0.7065315808045934,
   'diversity_hellinger': 0.8268121742255166,
   'diversity_cosine': 0.8739049313865842,
   'perplexity': 24307.318359375,
   'ppl_fair': 24307.318359375,
   'ppl_cheatty': 4190.05908203125},
  {'perplexity_score': 24307.318359375,
   'coherence_20': 1.9844211806263499,
   'diversity_euclidean': 0.055584392872176945,
   'diversity_jensenshannon': 0.7065315808043017,
   'diversity_hellinger': 0.8268121742255484,
   'diversity_cosine': 0.8739049313865697,
   'perplexity': 24307.318359375,
   'ppl_fair': 24307.318359375,
   'ppl_cheatty': 4190.05908203125},
  {'perplexity_score': 24307.318359375,
   'coherence_20': 1.9844211806263499,
   'diversity_euclidean': 0.055584392872176945,
   'diversity_jensenshannon': 0.706531580804283,
   'diversity_hellinger': 0.8268121742255042,
   'diversity_cosine': 0.8739049313865697,
   'perplexity': 24307.318359375,
   'ppl_fair': 24307.318359375,
   'ppl_cheatty': 4190.05908203125},
  {'perplexity_score': 24307.318359375,
   'coherence_20': 1.9844211806263499,
   'diversity_euclidean': 0.055584392872176945,
   'diversity_jensenshannon': 0.7065315808043132,
   'diversity_hellinger': 0.8268121742254984,
   'diversity_cosine': 0.8739049313865697,
   'perplexity': 24307.318359375,
   'ppl_fair': 24307.318359375,
   'ppl_cheatty': 4190.05908203125},
  {'perplexity_score': 24307.318359375,
   'coherence_20': 1.9844211806263499,
   'diversity_euclidean': 0.05558439287217721,
   'diversity_jensenshannon': 0.706531580804482,
   'diversity_hellinger': 0.8268121742256717,
   'diversity_cosine': 0.8739049313865817,
   'perplexity': 24307.318359375,
   'ppl_fair': 24307.318359375,
   'ppl_cheatty': 4190.05908203125},
  {'perplexity_score': 24307.318359375,
   'coherence_20': 1.9844211806263499,
   'diversity_euclidean': 0.055584392872177195,
   'diversity_jensenshannon': 0.7065315808044709,
   'diversity_hellinger': 0.8268121742254831,
   'diversity_cosine': 0.8739049313865817,
   'perplexity': 24307.318359375,
   'ppl_fair': 24307.318359375,
   'ppl_cheatty': 4190.05908203125},
  {'perplexity_score': 24307.318359375,
   'coherence_20': 1.9844211806263499,
   'diversity_euclidean': 0.05558439287217796,
   'diversity_jensenshannon': 0.7065315808044267,
   'diversity_hellinger': 0.8268121742254806,
   'diversity_cosine': 0.8739049313865723,
   'perplexity': 24307.318359375,
   'ppl_fair': 24307.318359375,
   'ppl_cheatty': 4190.05908203125},
  {'perplexity_score': 24307.318359375,
   'coherence_20': 1.9844211806263499,
   'diversity_euclidean': 0.05558439287217796,
   'diversity_jensenshannon': 0.7065315808044321,
   'diversity_hellinger': 0.8268121742255085,
   'diversity_cosine': 0.8739049313865724,
   'perplexity': 24307.318359375,
   'ppl_fair': 24307.318359375,
   'ppl_cheatty': 4190.05908203125},
  {'perplexity_score': 24307.318359375,
   'coherence_20': 1.9844211806263499,
   'diversity_euclidean': 0.05558439287217796,
   'diversity_jensenshannon': 0.7065315808044391,
   'diversity_hellinger': 0.8268121742255725,
   'diversity_cosine': 0.8739049313865724,
   'perplexity': 24307.318359375,
   'ppl_fair': 24307.318359375,
   'ppl_cheatty': 4190.05908203125},
  {'perplexity_score': 20406.341796875,
   'coherence_20': 2.2902439616534376,
   'diversity_euclidean': 0.0529993253962619,
   'diversity_jensenshannon': 0.7384915005805835,
   'diversity_hellinger': 0.8695520055818902,
   'diversity_cosine': 0.882407099262262,
   'perplexity': 20406.341796875,
   'ppl_fair': 20406.341796875,
   'ppl_cheatty': 4056.141357421875},
  {'perplexity_score': 20406.341796875,
   'coherence_20': 2.2902439616534376,
   'diversity_euclidean': 0.0529993253962619,
   'diversity_jensenshannon': 0.7384915005805913,
   'diversity_hellinger': 0.8695520055818896,
   'diversity_cosine': 0.882407099262262,
   'perplexity': 20406.341796875,
   'ppl_fair': 20406.341796875,
   'ppl_cheatty': 4056.141357421875},
  {'perplexity_score': 20406.341796875,
   'coherence_20': 2.2902439616534376,
   'diversity_euclidean': 0.05299932539626162,
   'diversity_jensenshannon': 0.7384915005805488,
   'diversity_hellinger': 0.8695520055818751,
   'diversity_cosine': 0.8824070992622611,
   'perplexity': 20406.341796875,
   'ppl_fair': 20406.341796875,
   'ppl_cheatty': 4056.141357421875},
  {'perplexity_score': 20406.341796875,
   'coherence_20': 2.2902439616534376,
   'diversity_euclidean': 0.05299932539626162,
   'diversity_jensenshannon': 0.7384915005805318,
   'diversity_hellinger': 0.8695520055818692,
   'diversity_cosine': 0.8824070992622611,
   'perplexity': 20406.341796875,
   'ppl_fair': 20406.341796875,
   'ppl_cheatty': 4056.141357421875},
  {'perplexity_score': 20406.341796875,
   'coherence_20': 2.2902439616534376,
   'diversity_euclidean': 0.0529993253962619,
   'diversity_jensenshannon': 0.7384915005805809,
   'diversity_hellinger': 0.869552005581881,
   'diversity_cosine': 0.882407099262262,
   'perplexity': 20406.341796875,
   'ppl_fair': 20406.341796875,
   'ppl_cheatty': 4056.141357421875},
  {'perplexity_score': 20406.341796875,
   'coherence_20': 2.2902439616534376,
   'diversity_euclidean': 0.0529993253962619,
   'diversity_jensenshannon': 0.7384915005805915,
   'diversity_hellinger': 0.8695520055819145,
   'diversity_cosine': 0.882407099262262,
   'perplexity': 20406.341796875,
   'ppl_fair': 20406.341796875,
   'ppl_cheatty': 4056.141357421875},
  {'perplexity_score': 20406.341796875,
   'coherence_20': 2.2902439616534376,
   'diversity_euclidean': 0.0529993253971461,
   'diversity_jensenshannon': 0.7384915005771474,
   'diversity_hellinger': 0.8695520056003677,
   'diversity_cosine': 0.8824070992460776,
   'perplexity': 20406.341796875,
   'ppl_fair': 20406.341796875,
   'ppl_cheatty': 4056.141357421875},
  {'perplexity_score': 20406.341796875,
   'coherence_20': 2.2902439616534376,
   'diversity_euclidean': 0.0529993253962619,
   'diversity_jensenshannon': 0.7384915005805848,
   'diversity_hellinger': 0.8695520055818742,
   'diversity_cosine': 0.882407099262262,
   'perplexity': 20406.341796875,
   'ppl_fair': 20406.341796875,
   'ppl_cheatty': 4056.141357421875},
  {'perplexity_score': 20406.341796875,
   'coherence_20': 2.2902439616534376,
   'diversity_euclidean': 0.0529993253962619,
   'diversity_jensenshannon': 0.7384915005805817,
   'diversity_hellinger': 0.8695520055818792,
   'diversity_cosine': 0.882407099262262,
   'perplexity': 20406.341796875,
   'ppl_fair': 20406.341796875,
   'ppl_cheatty': 4056.141357421875}],
 'bank_topic_scores': [[{'kernel_size': 6290,
    'coherence_20': 1.9365857260048487,
    'distance_to_nearest': 0.0},
   {'kernel_size': 5987,
    'coherence_20': 2.350993531411413,
    'distance_to_nearest': 0.8670798186186544}],
  [{'kernel_size': 6290,
    'coherence_20': 1.9365857260048487,
    'distance_to_nearest': 0.0},
   {'kernel_size': 5987,
    'coherence_20': 2.350993531411413,
    'distance_to_nearest': 0.8670798186186544},
   {'kernel_size': 4904,
    'coherence_20': 1.665684284462788,
    'distance_to_nearest': 0.9068645569155264}],
  [{'kernel_size': 6290,
    'coherence_20': 1.9365857260048487,
    'distance_to_nearest': 0.0},
   {'kernel_size': 5987,
    'coherence_20': 2.350993531411413,
    'distance_to_nearest': 0.8670798186186544},
   {'kernel_size': 4904,
    'coherence_20': 1.665684284462788,
    'distance_to_nearest': 0.9068645569155264}],
  [{'kernel_size': 6290,
    'coherence_20': 1.9365857260048487,
    'distance_to_nearest': 0.0},
   {'kernel_size': 5987,
    'coherence_20': 2.350993531411413,
    'distance_to_nearest': 0.8670798186186544},
   {'kernel_size': 4904,
    'coherence_20': 1.665684284462788,
    'distance_to_nearest': 0.9068645569155264}],
  [{'kernel_size': 6290,
    'coherence_20': 1.9365857260048487,
    'distance_to_nearest': 0.0},
   {'kernel_size': 5987,
    'coherence_20': 2.350993531411413,
    'distance_to_nearest': 0.8670798186186544},
   {'kernel_size': 4904,
    'coherence_20': 1.665684284462788,
    'distance_to_nearest': 0.9068645569155264}],
  [{'kernel_size': 6290,
    'coherence_20': 1.9365857260048487,
    'distance_to_nearest': 0.0},
   {'kernel_size': 5987,
    'coherence_20': 2.350993531411413,
    'distance_to_nearest': 0.8670798186186544},
   {'kernel_size': 4904,
    'coherence_20': 1.665684284462788,
    'distance_to_nearest': 0.9068645569155264}],
  [{'kernel_size': 6290,
    'coherence_20': 1.9365857260048487,
    'distance_to_nearest': 0.0},
   {'kernel_size': 5987,
    'coherence_20': 2.350993531411413,
    'distance_to_nearest': 0.8670798186186544},
   {'kernel_size': 4904,
    'coherence_20': 1.665684284462788,
    'distance_to_nearest': 0.9068645569155264}],
  [{'kernel_size': 6290,
    'coherence_20': 1.9365857260048487,
    'distance_to_nearest': 0.0},
   {'kernel_size': 5987,
    'coherence_20': 2.350993531411413,
    'distance_to_nearest': 0.8670798186186544},
   {'kernel_size': 4904,
    'coherence_20': 1.665684284462788,
    'distance_to_nearest': 0.9068645569155264}],
  [{'kernel_size': 6290,
    'coherence_20': 1.9365857260048487,
    'distance_to_nearest': 0.0},
   {'kernel_size': 5987,
    'coherence_20': 2.350993531411413,
    'distance_to_nearest': 0.8670798186186544},
   {'kernel_size': 4904,
    'coherence_20': 1.665684284462788,
    'distance_to_nearest': 0.9068645569155264}],
  [{'kernel_size': 6290,
    'coherence_20': 1.9365857260048487,
    'distance_to_nearest': 0.0},
   {'kernel_size': 5987,
    'coherence_20': 2.350993531411413,
    'distance_to_nearest': 0.8670798186186544},
   {'kernel_size': 4904,
    'coherence_20': 1.665684284462788,
    'distance_to_nearest': 0.9068645569155264}],
  [{'kernel_size': 6290,
    'coherence_20': 1.9365857260048487,
    'distance_to_nearest': 0.0},
   {'kernel_size': 5987,
    'coherence_20': 2.350993531411413,
    'distance_to_nearest': 0.8670798186186544},
   {'kernel_size': 4904,
    'coherence_20': 1.665684284462788,
    'distance_to_nearest': 0.9068645569155264}],
  [{'kernel_size': 6290,
    'coherence_20': 1.9365857260048487,
    'distance_to_nearest': 0.0},
   {'kernel_size': 5987,
    'coherence_20': 2.350993531411413,
    'distance_to_nearest': 0.8670798186186544},
   {'kernel_size': 4904,
    'coherence_20': 1.665684284462788,
    'distance_to_nearest': 0.9068645569155264},
   {'kernel_size': 6419,
    'coherence_20': 3.2077123047347023,
    'distance_to_nearest': 0.9163295596263876}],
  [{'kernel_size': 6290,
    'coherence_20': 1.9365857260048487,
    'distance_to_nearest': 0.0},
   {'kernel_size': 5987,
    'coherence_20': 2.350993531411413,
    'distance_to_nearest': 0.8670798186186544},
   {'kernel_size': 4904,
    'coherence_20': 1.665684284462788,
    'distance_to_nearest': 0.9068645569155264},
   {'kernel_size': 6419,
    'coherence_20': 3.2077123047347023,
    'distance_to_nearest': 0.9163295596263876}],
  [{'kernel_size': 6290,
    'coherence_20': 1.9365857260048487,
    'distance_to_nearest': 0.0},
   {'kernel_size': 5987,
    'coherence_20': 2.350993531411413,
    'distance_to_nearest': 0.8670798186186544},
   {'kernel_size': 4904,
    'coherence_20': 1.665684284462788,
    'distance_to_nearest': 0.9068645569155264},
   {'kernel_size': 6419,
    'coherence_20': 3.2077123047347023,
    'distance_to_nearest': 0.9163295596263876}],
  [{'kernel_size': 6290,
    'coherence_20': 1.9365857260048487,
    'distance_to_nearest': 0.0},
   {'kernel_size': 5987,
    'coherence_20': 2.350993531411413,
    'distance_to_nearest': 0.8670798186186544},
   {'kernel_size': 4904,
    'coherence_20': 1.665684284462788,
    'distance_to_nearest': 0.9068645569155264},
   {'kernel_size': 6419,
    'coherence_20': 3.2077123047347023,
    'distance_to_nearest': 0.9163295596263876}],
  [{'kernel_size': 6290,
    'coherence_20': 1.9365857260048487,
    'distance_to_nearest': 0.0},
   {'kernel_size': 5987,
    'coherence_20': 2.350993531411413,
    'distance_to_nearest': 0.8670798186186544},
   {'kernel_size': 4904,
    'coherence_20': 1.665684284462788,
    'distance_to_nearest': 0.9068645569155264},
   {'kernel_size': 6419,
    'coherence_20': 3.2077123047347023,
    'distance_to_nearest': 0.9163295596263876}],
  [{'kernel_size': 6290,
    'coherence_20': 1.9365857260048487,
    'distance_to_nearest': 0.0},
   {'kernel_size': 5987,
    'coherence_20': 2.350993531411413,
    'distance_to_nearest': 0.8670798186186544},
   {'kernel_size': 4904,
    'coherence_20': 1.665684284462788,
    'distance_to_nearest': 0.9068645569155264},
   {'kernel_size': 6419,
    'coherence_20': 3.2077123047347023,
    'distance_to_nearest': 0.9163295596263876}],
  [{'kernel_size': 6290,
    'coherence_20': 1.9365857260048487,
    'distance_to_nearest': 0.0},
   {'kernel_size': 5987,
    'coherence_20': 2.350993531411413,
    'distance_to_nearest': 0.8670798186186544},
   {'kernel_size': 4904,
    'coherence_20': 1.665684284462788,
    'distance_to_nearest': 0.9068645569155264},
   {'kernel_size': 6419,
    'coherence_20': 3.2077123047347023,
    'distance_to_nearest': 0.9163295596263876}],
  [{'kernel_size': 6290,
    'coherence_20': 1.9365857260048487,
    'distance_to_nearest': 0.0},
   {'kernel_size': 5987,
    'coherence_20': 2.350993531411413,
    'distance_to_nearest': 0.8670798186186544},
   {'kernel_size': 4904,
    'coherence_20': 1.665684284462788,
    'distance_to_nearest': 0.9068645569155264},
   {'kernel_size': 6419,
    'coherence_20': 3.2077123047347023,
    'distance_to_nearest': 0.9163295596263876}],
  [{'kernel_size': 6290,
    'coherence_20': 1.9365857260048487,
    'distance_to_nearest': 0.0},
   {'kernel_size': 5987,
    'coherence_20': 2.350993531411413,
    'distance_to_nearest': 0.8670798186186544},
   {'kernel_size': 4904,
    'coherence_20': 1.665684284462788,
    'distance_to_nearest': 0.9068645569155264},
   {'kernel_size': 6419,
    'coherence_20': 3.2077123047347023,
    'distance_to_nearest': 0.9163295596263876}]],
 'model_scores': [{'perplexity_score': 2019.2904052734375,
   'coherence_20': 1.0763733292344704,
   'diversity_euclidean': 0.06002123411499822,
   'diversity_jensenshannon': 0.6703556612184317,
   'diversity_hellinger': 0.7769730574359373,
   'diversity_cosine': 0.7605662490558308,
   'perplexity': 2019.2904052734375},
  {'perplexity_score': 1995.385986328125,
   'coherence_20': 1.307914158119003,
   'diversity_euclidean': 0.06057003777969821,
   'diversity_jensenshannon': 0.6752988023741286,
   'diversity_hellinger': 0.7832085694658533,
   'diversity_cosine': 0.7784690054660054,
   'perplexity': 1995.385986328125},
  {'perplexity_score': 1958.0794677734375,
   'coherence_20': 1.2432664456997378,
   'diversity_euclidean': 0.060215059183712456,
   'diversity_jensenshannon': 0.6700086307205037,
   'diversity_hellinger': 0.7770592577645057,
   'diversity_cosine': 0.7596633181061738,
   'perplexity': 1958.0794677734375},
  {'perplexity_score': 2024.3011474609375,
   'coherence_20': 1.1689093050993415,
   'diversity_euclidean': 0.05994311051596862,
   'diversity_jensenshannon': 0.6689217225322689,
   'diversity_hellinger': 0.7757553801541559,
   'diversity_cosine': 0.7539496518170561,
   'perplexity': 2024.3011474609375},
  {'perplexity_score': 2066.39501953125,
   'coherence_20': 1.1478380174508425,
   'diversity_euclidean': 0.06047816533144437,
   'diversity_jensenshannon': 0.6692641370851833,
   'diversity_hellinger': 0.7750338946078551,
   'diversity_cosine': 0.7520911133198186,
   'perplexity': 2066.39501953125},
  {'perplexity_score': 2007.6845703125,
   'coherence_20': 1.1840291027535648,
   'diversity_euclidean': 0.05953642270346078,
   'diversity_jensenshannon': 0.666180663393972,
   'diversity_hellinger': 0.7716316640162743,
   'diversity_cosine': 0.7536297808865542,
   'perplexity': 2007.6845703125},
  {'perplexity_score': 1998.599609375,
   'coherence_20': 1.3020139171648393,
   'diversity_euclidean': 0.0594250165652698,
   'diversity_jensenshannon': 0.670237357516293,
   'diversity_hellinger': 0.777221427130704,
   'diversity_cosine': 0.756808289357464,
   'perplexity': 1998.599609375},
  {'perplexity_score': 2018.6123046875,
   'coherence_20': 1.1376124622764847,
   'diversity_euclidean': 0.05939696736158781,
   'diversity_jensenshannon': 0.6682796695577389,
   'diversity_hellinger': 0.7744883383048309,
   'diversity_cosine': 0.7588926936121003,
   'perplexity': 2018.6123046875},
  {'perplexity_score': 2031.153076171875,
   'coherence_20': 1.133575080544464,
   'diversity_euclidean': 0.06006439609081358,
   'diversity_jensenshannon': 0.6593992177622303,
   'diversity_hellinger': 0.7628020316551289,
   'diversity_cosine': 0.74451329883066,
   'perplexity': 2031.153076171875},
  {'perplexity_score': 2019.326904296875,
   'coherence_20': 1.3111070830863358,
   'diversity_euclidean': 0.05907083184002629,
   'diversity_jensenshannon': 0.6707415280276212,
   'diversity_hellinger': 0.7779644572921025,
   'diversity_cosine': 0.765787202196942,
   'perplexity': 2019.326904296875},
  {'perplexity_score': 2002.8734130859375,
   'coherence_20': 1.1592309548398148,
   'diversity_euclidean': 0.06149881443437038,
   'diversity_jensenshannon': 0.6714453951074404,
   'diversity_hellinger': 0.7781423151045727,
   'diversity_cosine': 0.7674715404364016,
   'perplexity': 2002.8734130859375},
  {'perplexity_score': 2012.3387451171875,
   'coherence_20': 1.253084405363488,
   'diversity_euclidean': 0.060463112082962525,
   'diversity_jensenshannon': 0.6785185019968609,
   'diversity_hellinger': 0.7871574956309914,
   'diversity_cosine': 0.7847807011713057,
   'perplexity': 2012.3387451171875},
  {'perplexity_score': 2023.60400390625,
   'coherence_20': 1.1676256914578065,
   'diversity_euclidean': 0.05992895118146357,
   'diversity_jensenshannon': 0.6723259814023025,
   'diversity_hellinger': 0.7790827770913806,
   'diversity_cosine': 0.7681378314693983,
   'perplexity': 2023.60400390625},
  {'perplexity_score': 1990.8211669921875,
   'coherence_20': 1.0487207275780173,
   'diversity_euclidean': 0.0572978037529394,
   'diversity_jensenshannon': 0.6647815300513481,
   'diversity_hellinger': 0.7712823449899029,
   'diversity_cosine': 0.7363862962675285,
   'perplexity': 1990.8211669921875},
  {'perplexity_score': 2014.4373779296875,
   'coherence_20': 1.144087547978676,
   'diversity_euclidean': 0.05992714347632713,
   'diversity_jensenshannon': 0.6583176770830285,
   'diversity_hellinger': 0.7623984860060132,
   'diversity_cosine': 0.7338818098733966,
   'perplexity': 2014.4373779296875},
  {'perplexity_score': 2017.152099609375,
   'coherence_20': 1.1536871559709736,
   'diversity_euclidean': 0.06060427035826908,
   'diversity_jensenshannon': 0.6730310362110099,
   'diversity_hellinger': 0.7798738437825256,
   'diversity_cosine': 0.7652116522305122,
   'perplexity': 2017.152099609375},
  {'perplexity_score': 2043.8541259765625,
   'coherence_20': 1.1473924857155202,
   'diversity_euclidean': 0.05862215711539558,
   'diversity_jensenshannon': 0.6638702086120966,
   'diversity_hellinger': 0.7684329059616057,
   'diversity_cosine': 0.7502455586264344,
   'perplexity': 2043.8541259765625},

In [256]:
optimizer._result['bank_topic_scores'][0]

[{'kernel_size': 6290,
  'coherence_20': 1.9365857260048487,
  'distance_to_nearest': 0.0},
 {'kernel_size': 5987,
  'coherence_20': 2.350993531411413,
  'distance_to_nearest': 0.8670798186186544}]

In [257]:
optimizer._result['model_topic_scores']

[[{'kernel_size': 4766, 'coherence_20': 0.5621840561052343},
  {'kernel_size': 4334, 'coherence_20': 1.0198652520374296},
  {'kernel_size': 4496, 'coherence_20': 1.2526309915636804},
  {'kernel_size': 4003, 'coherence_20': 0.9559712349724628},
  {'kernel_size': 5091, 'coherence_20': 0.7483706069195322},
  {'kernel_size': 7320, 'coherence_20': 1.5258045018704882},
  {'kernel_size': 3735, 'coherence_20': 1.0869406650083322},
  {'kernel_size': 5614, 'coherence_20': 0.8574644195284007},
  {'kernel_size': 1953, 'coherence_20': 0.6234681445380453},
  {'kernel_size': 4589, 'coherence_20': 0.8684110125492415},
  {'kernel_size': 5111, 'coherence_20': 1.2688142947197127},
  {'kernel_size': 5474, 'coherence_20': 1.400341755763377},
  {'kernel_size': 3020, 'coherence_20': 1.1558650335344032},
  {'kernel_size': 4058, 'coherence_20': 1.2121665926026541},
  {'kernel_size': 4130, 'coherence_20': 1.0658059934606086},
  {'kernel_size': 4356, 'coherence_20': 0.9389828616117071},
  {'kernel_size': 6290,
   'coherence_20': 1.9365857260048487,
   'distance_to_nearest': 0.0},
  {'kernel_size': 5987,
   'coherence_20': 2.350993531411413,
   'distance_to_nearest': 0.8670798186186544},
  {'kernel_size': 5787, 'coherence_20': 1.730936597751668},
  {'kernel_size': 2814, 'coherence_20': 1.055945339153518}],
 [{'kernel_size': 2016, 'coherence_20': 0.5874405512998497},
  {'kernel_size': 3979, 'coherence_20': 1.4888008966637574},
  {'kernel_size': 4963, 'coherence_20': 1.256679555881426},
  {'kernel_size': 3026, 'coherence_20': 0.6230962891046478},
  {'kernel_size': 4189, 'coherence_20': 0.8075424475260733},
  {'kernel_size': 4250, 'coherence_20': 1.4071958638172284},
  {'kernel_size': 3430, 'coherence_20': 1.3807235054341533},
  {'kernel_size': 4129, 'coherence_20': 0.8408776292973266},
  {'kernel_size': 4931, 'coherence_20': 0.9668702932339769},
  {'kernel_size': 4682, 'coherence_20': 1.6386439825004584},
  {'kernel_size': 3181, 'coherence_20': 0.9887854280371062},
  {'kernel_size': 6126, 'coherence_20': 1.6529658439482602},
  {'kernel_size': 4904,
   'coherence_20': 1.665684284462788,
   'distance_to_nearest': 0.9068645569155264},
  {'kernel_size': 3957, 'coherence_20': 1.5289063693135032},
  {'kernel_size': 5670, 'coherence_20': 1.3591487603565802},
  {'kernel_size': 4562, 'coherence_20': 0.6381383560935155},
  {'kernel_size': 4666, 'coherence_20': 1.3853028178115974},
  {'kernel_size': 4267, 'coherence_20': 1.0658085697457458},
  {'kernel_size': 6387, 'coherence_20': 2.0307152755009827},
  {'kernel_size': 5507, 'coherence_20': 0.7965937973196743}],
 [{'kernel_size': 4143, 'coherence_20': 1.4987156992000525},
  {'kernel_size': 5339, 'coherence_20': 0.6859271307566073},
  {'kernel_size': 4830, 'coherence_20': 1.7806462536805598},
  {'kernel_size': 5500, 'coherence_20': 1.2970367343953444},
  {'kernel_size': 3507, 'coherence_20': 1.1386680641425373},
  {'kernel_size': 3933, 'coherence_20': 1.1894961570041314},
  {'kernel_size': 4089, 'coherence_20': 1.3489913182339661},
  {'kernel_size': 2740, 'coherence_20': 0.5386068706892319},
  {'kernel_size': 4608, 'coherence_20': 2.0317524697355593},
  {'kernel_size': 6183, 'coherence_20': 0.9804953308834277},
  {'kernel_size': 3149, 'coherence_20': 1.8169771090389824},
  {'kernel_size': 6023, 'coherence_20': 2.061658449258948},
  {'kernel_size': 3650, 'coherence_20': 0.8077292348927955},
  {'kernel_size': 4094, 'coherence_20': 0.6823925768160031},
  {'kernel_size': 7155, 'coherence_20': 1.5431482866341},
  {'kernel_size': 2869, 'coherence_20': 0.6745169901238024},
  {'kernel_size': 5555, 'coherence_20': 1.457151537764801},
  {'kernel_size': 2759, 'coherence_20': 0.6632084455516286},
  {'kernel_size': 4343, 'coherence_20': 1.4700526229085547},
  {'kernel_size': 3167, 'coherence_20': 0.9241564168795247}],
 [{'kernel_size': 5161, 'coherence_20': 0.7150412483904646},
  {'kernel_size': 5602, 'coherence_20': 0.7347449318085851},
  {'kernel_size': 5130, 'coherence_20': 2.2362153419750834},
  {'kernel_size': 3176, 'coherence_20': 0.6713316041696273},
  {'kernel_size': 3747, 'coherence_20': 0.8892003270457194},
  {'kernel_size': 5722, 'coherence_20': 0.7189144282967648},
  {'kernel_size': 5350, 'coherence_20': 1.0139341812596299},
  {'kernel_size': 4338, 'coherence_20': 1.346278546839801},
  {'kernel_size': 4204, 'coherence_20': 1.2174740445665004},
  {'kernel_size': 2810, 'coherence_20': 0.8114785565781277},
  {'kernel_size': 3974, 'coherence_20': 1.1203445656321824},
  {'kernel_size': 2843, 'coherence_20': 0.5492513588404316},
  {'kernel_size': 4430, 'coherence_20': 1.637500610466618},
  {'kernel_size': 6934, 'coherence_20': 1.815366279680369},
  {'kernel_size': 3179, 'coherence_20': 1.0721686056575084},
  {'kernel_size': 5340, 'coherence_20': 1.2482212001296877},
  {'kernel_size': 4060, 'coherence_20': 1.5659294669932653},
  {'kernel_size': 3342, 'coherence_20': 1.5102624437585996},
  {'kernel_size': 5892, 'coherence_20': 1.327707686265835},
  {'kernel_size': 3846, 'coherence_20': 1.50761325841962}],
 [{'kernel_size': 4188, 'coherence_20': 1.049144287857619},
  {'kernel_size': 3416, 'coherence_20': 0.6037243035575556},
  {'kernel_size': 4780, 'coherence_20': 1.8784311437063315},
  {'kernel_size': 5499, 'coherence_20': 0.9408100831605126},
  {'kernel_size': 3972, 'coherence_20': 0.6252739989815422},
  {'kernel_size': 5089, 'coherence_20': 1.1803805938659495},
  {'kernel_size': 3743, 'coherence_20': 1.1493032086651938},
  {'kernel_size': 4873, 'coherence_20': 1.5965544715166822},
  {'kernel_size': 3236, 'coherence_20': 0.8650963333658729},
  {'kernel_size': 3468, 'coherence_20': 1.4537910341846587},
  {'kernel_size': 4469, 'coherence_20': 1.1463728262364912},
  {'kernel_size': 4456, 'coherence_20': 1.3212553848971282},
  {'kernel_size': 4099, 'coherence_20': 0.8692473249259863},
  {'kernel_size': 4309, 'coherence_20': 0.8201092191414795},
  {'kernel_size': 6286, 'coherence_20': 1.5782045151490263},
  {'kernel_size': 2450, 'coherence_20': 0.5543591538879561},
  {'kernel_size': 4021, 'coherence_20': 1.436859562403072},
  {'kernel_size': 4971, 'coherence_20': 1.6001809455410623},
  {'kernel_size': 3659, 'coherence_20': 0.5929936188920603},
  {'kernel_size': 5926, 'coherence_20': 1.3907593089928918}],
 [{'kernel_size': 5605, 'coherence_20': 1.194547382206017},
  {'kernel_size': 3457, 'coherence_20': 1.2562203775565257},
  {'kernel_size': 2285, 'coherence_20': 0.6176646007739754},
  {'kernel_size': 3466, 'coherence_20': 0.9871353028316515},
  {'kernel_size': 5697, 'coherence_20': 1.3546026138500242},
  {'kernel_size': 4321, 'coherence_20': 1.5725955561553684},
  {'kernel_size': 5627, 'coherence_20': 1.1606065098728378},
  {'kernel_size': 3119, 'coherence_20': 0.595445867323855},
  {'kernel_size': 3649, 'coherence_20': 1.3512553806062741},
  {'kernel_size': 4248, 'coherence_20': 1.600275721490764},
  {'kernel_size': 7470, 'coherence_20': 2.5479222083670066},
  {'kernel_size': 4079, 'coherence_20': 1.1735108233011124},
  {'kernel_size': 2791, 'coherence_20': 0.9793475801655092},
  {'kernel_size': 7065, 'coherence_20': 0.9144471358296881},
  {'kernel_size': 4863, 'coherence_20': 0.7258137390608833},
  {'kernel_size': 4403, 'coherence_20': 1.9022295777288258},
  {'kernel_size': 5151, 'coherence_20': 1.519960462020673},
  {'kernel_size': 5363, 'coherence_20': 0.792994235299191},
  {'kernel_size': 3614, 'coherence_20': 0.7999161172972445},
  {'kernel_size': 4357, 'coherence_20': 1.3356490057362767}],
 [{'kernel_size': 4128, 'coherence_20': 1.2717331859161538},
  {'kernel_size': 5713, 'coherence_20': 1.603644507955442},
  {'kernel_size': 3216, 'coherence_20': 1.332294648413525},
  {'kernel_size': 3759, 'coherence_20': 0.8687036705888889},
  {'kernel_size': 3078, 'coherence_20': 1.026239226837248},
  {'kernel_size': 6895, 'coherence_20': 1.4054094346768193},
  {'kernel_size': 5846, 'coherence_20': 2.231110209558989},
  {'kernel_size': 4967, 'coherence_20': 1.2093037668382665},
  {'kernel_size': 3996, 'coherence_20': 1.1463728262364914},
  {'kernel_size': 4496, 'coherence_20': 1.8724245165810849},
  {'kernel_size': 2957, 'coherence_20': 0.6355026741498335},
  {'kernel_size': 3209, 'coherence_20': 1.4640359039552235},
  {'kernel_size': 3431, 'coherence_20': 0.873464746075933},
  {'kernel_size': 3313, 'coherence_20': 0.5015957269952235},
  {'kernel_size': 4506, 'coherence_20': 0.7042150973951395},
  {'kernel_size': 3539, 'coherence_20': 0.779450223594143},
  {'kernel_size': 4487, 'coherence_20': 1.3930404094874145},
  {'kernel_size': 5710, 'coherence_20': 1.643218384555204},
  {'kernel_size': 4852, 'coherence_20': 1.9762482001275703},
  {'kernel_size': 4883, 'coherence_20': 1.3768087297088905}],
 [{'kernel_size': 4933, 'coherence_20': 1.1426756289166702},
  {'kernel_size': 6043, 'coherence_20': 1.5711770209644598},
  {'kernel_size': 3954, 'coherence_20': 1.1325492956362992},
  {'kernel_size': 4129, 'coherence_20': 1.8973196443345721},
  {'kernel_size': 5339, 'coherence_20': 1.2427406114948343},
  {'kernel_size': 3174, 'coherence_20': 0.6217436103569336},
  {'kernel_size': 5923, 'coherence_20': 1.0569277719172445},
  {'kernel_size': 5815, 'coherence_20': 1.2086289007307112},
  {'kernel_size': 5933, 'coherence_20': 0.7685953932842243},
  {'kernel_size': 2530, 'coherence_20': 0.6257003847298652},
  {'kernel_size': 4342, 'coherence_20': 1.3942462167195624},
  {'kernel_size': 5286, 'coherence_20': 0.8411796750503829},
  {'kernel_size': 4682, 'coherence_20': 1.4285063265272402},
  {'kernel_size': 3370, 'coherence_20': 0.6115573736824849},
  {'kernel_size': 4030, 'coherence_20': 1.0992910098647843},
  {'kernel_size': 6932, 'coherence_20': 2.063578547479797},
  {'kernel_size': 5107, 'coherence_20': 1.1668815023893477},
  {'kernel_size': 2918, 'coherence_20': 0.8833613634791032},
  {'kernel_size': 3369, 'coherence_20': 1.3088688897774274},
  {'kernel_size': 4592, 'coherence_20': 1.034397873691758}],
 [{'kernel_size': 4062, 'coherence_20': 1.2254942169678296},
  {'kernel_size': 4495, 'coherence_20': 0.6679518436289797},
  {'kernel_size': 4960, 'coherence_20': 1.6828281185438072},
  {'kernel_size': 3218, 'coherence_20': 0.684798650059646},
  {'kernel_size': 2963, 'coherence_20': 0.9947321800574053},
  {'kernel_size': 4476, 'coherence_20': 1.5290696524523208},
  {'kernel_size': 4885, 'coherence_20': 1.059760305480202},
  {'kernel_size': 5055, 'coherence_20': 1.3926578897085955},
  {'kernel_size': 5676, 'coherence_20': 0.7214542147867105},
  {'kernel_size': 6110, 'coherence_20': 1.6204173024198811},
  {'kernel_size': 4648, 'coherence_20': 0.7850954124843751},
  {'kernel_size': 4324, 'coherence_20': 0.7689585601066912},
  {'kernel_size': 5340, 'coherence_20': 0.7933434109058504},
  {'kernel_size': 4404, 'coherence_20': 1.2073898556087261},
  {'kernel_size': 2757, 'coherence_20': 0.6056959553030176},
  {'kernel_size': 3834, 'coherence_20': 0.9116720669459549},
  {'kernel_size': 5517, 'coherence_20': 1.5189617593108677},
  {'kernel_size': 7132, 'coherence_20': 1.584402187173207},
  {'kernel_size': 4467, 'coherence_20': 1.315453633032395},
  {'kernel_size': 3439, 'coherence_20': 1.5854799337961685}],
 [{'kernel_size': 3579, 'coherence_20': 1.5435470385104475},
  {'kernel_size': 5186, 'coherence_20': 2.27357525497698},
  {'kernel_size': 6468, 'coherence_20': 2.4524797439638224},
  {'kernel_size': 2298, 'coherence_20': 0.6017906294019835},
  {'kernel_size': 4216, 'coherence_20': 1.3237581790853068},
  {'kernel_size': 4315, 'coherence_20': 0.7793760050636548},
  {'kernel_size': 2927, 'coherence_20': 0.6712954839917286},
  {'kernel_size': 3962, 'coherence_20': 1.0447620513764675},
  {'kernel_size': 3304, 'coherence_20': 1.298455987087365},
  {'kernel_size': 5555, 'coherence_20': 1.056033700618839},
  {'kernel_size': 5595, 'coherence_20': 1.3951904489785172},
  {'kernel_size': 4803, 'coherence_20': 1.0040969189642501},
  {'kernel_size': 5613, 'coherence_20': 1.5947026365960597},
  {'kernel_size': 5333, 'coherence_20': 1.2966655198702268},
  {'kernel_size': 5664, 'coherence_20': 2.079213849153134},
  {'kernel_size': 6511, 'coherence_20': 1.3399103863794153},
  {'kernel_size': 3845, 'coherence_20': 0.7278937820543459},
  {'kernel_size': 4146, 'coherence_20': 1.3775011128275643},
  {'kernel_size': 3922, 'coherence_20': 1.5607915753050374},
  {'kernel_size': 5831, 'coherence_20': 0.7414641809003026}],
 [{'kernel_size': 3911, 'coherence_20': 0.7479570405607877},
  {'kernel_size': 5723, 'coherence_20': 2.4014608706780587},
  {'kernel_size': 4041, 'coherence_20': 1.4063740140126164},
  {'kernel_size': 4358, 'coherence_20': 1.2322323899224896},
  {'kernel_size': 6230, 'coherence_20': 1.9051498889120568},
  {'kernel_size': 3740, 'coherence_20': 1.6587103416892939},
  {'kernel_size': 3074, 'coherence_20': 0.6362997344665144},
  {'kernel_size': 2730, 'coherence_20': 0.6729189022585949},
  {'kernel_size': 4289, 'coherence_20': 1.180379318693548},
  {'kernel_size': 5649, 'coherence_20': 1.0701426712616589},
  {'kernel_size': 4008, 'coherence_20': 1.0125072806427122},
  {'kernel_size': 6713, 'coherence_20': 1.1704020078116437},
  {'kernel_size': 4934, 'coherence_20': 0.6261392928085487},
  {'kernel_size': 2748, 'coherence_20': 0.6042379064338355},
  {'kernel_size': 4535, 'coherence_20': 1.244171975256462},
  {'kernel_size': 2950, 'coherence_20': 1.0490732612207057},
  {'kernel_size': 6138, 'coherence_20': 1.390730586402039},
  {'kernel_size': 4925, 'coherence_20': 1.148059901867986},
  {'kernel_size': 5409, 'coherence_20': 0.901207941361675},
  {'kernel_size': 4577, 'coherence_20': 1.6300267904928867}],
 [{'kernel_size': 3837, 'coherence_20': 1.2971184286800312},
  {'kernel_size': 4721, 'coherence_20': 0.7504525511840929},
  {'kernel_size': 5607, 'coherence_20': 1.1549922296422215},
  {'kernel_size': 2930, 'coherence_20': 1.038652380747021},
  {'kernel_size': 4205, 'coherence_20': 1.2090503820469447},
  {'kernel_size': 5076, 'coherence_20': 0.8393059752242287},
  {'kernel_size': 4663, 'coherence_20': 1.4318211552882365},
  {'kernel_size': 6341, 'coherence_20': 1.6746904283026363},
  {'kernel_size': 6419,
   'coherence_20': 3.2077123047347023,
   'distance_to_nearest': 0.9163295596263876},
  {'kernel_size': 4054, 'coherence_20': 1.1386710832849112},
  {'kernel_size': 4842, 'coherence_20': 0.9384238356828722},
  {'kernel_size': 6351, 'coherence_20': 1.504475275783582},
  {'kernel_size': 5487, 'coherence_20': 0.744675802452104},
  {'kernel_size': 5229, 'coherence_20': 1.5084758276599164},
  {'kernel_size': 4255, 'coherence_20': 1.1794429920120442},
  {'kernel_size': 1696, 'coherence_20': 0.6009113635147818},
  {'kernel_size': 5916, 'coherence_20': 1.5277088812816744},
  {'kernel_size': 6110, 'coherence_20': 1.6309423929435811},
  {'kernel_size': 4192, 'coherence_20': 1.4306995663477622},
  {'kernel_size': 5755, 'coherence_20': 1.3443378794208667}],
 [{'kernel_size': 3327, 'coherence_20': 0.735235967871504},
  {'kernel_size': 6177, 'coherence_20': 1.3526022547435417},
  {'kernel_size': 3894, 'coherence_20': 0.6699416969515524},
  {'kernel_size': 6231, 'coherence_20': 1.0374623391982014},
  {'kernel_size': 5822, 'coherence_20': 1.3101475900318857},
  {'kernel_size': 5289, 'coherence_20': 1.7732590233591063},
  {'kernel_size': 4726, 'coherence_20': 1.0121157005390413},
  {'kernel_size': 4696, 'coherence_20': 1.1708025723705815},
  {'kernel_size': 4908, 'coherence_20': 1.1644488105450315},
  {'kernel_size': 3982, 'coherence_20': 0.9300880219672762},
  {'kernel_size': 1973, 'coherence_20': 0.6275026245138077},
  {'kernel_size': 3507, 'coherence_20': 1.4560691250761402},
  {'kernel_size': 4859, 'coherence_20': 1.4086809094898725},
  {'kernel_size': 5259, 'coherence_20': 1.129685823698024},
  {'kernel_size': 4857, 'coherence_20': 1.924826891466576},
  {'kernel_size': 2814, 'coherence_20': 0.8301550849284137},
  {'kernel_size': 5053, 'coherence_20': 0.9259031767564398},
  {'kernel_size': 3511, 'coherence_20': 1.3939020198250995},
  {'kernel_size': 5325, 'coherence_20': 1.2509004469517082},
  {'kernel_size': 4049, 'coherence_20': 1.2266787616782389}],
 [{'kernel_size': 4732, 'coherence_20': 0.9050608999935272},
  {'kernel_size': 3868, 'coherence_20': 1.2226238320427225},
  {'kernel_size': 3746, 'coherence_20': 0.8473127939342597},
  {'kernel_size': 5622, 'coherence_20': 2.5604959708206745},
  {'kernel_size': 2996, 'coherence_20': 0.6383386356311291},
  {'kernel_size': 3438, 'coherence_20': 0.5836587015036074},
  {'kernel_size': 3926, 'coherence_20': 0.9836334508100988},
  {'kernel_size': 3527, 'coherence_20': 0.8230626918945979},
  {'kernel_size': 5659, 'coherence_20': 1.352184618857007},
  {'kernel_size': 5170, 'coherence_20': 0.9739139379587516},
  {'kernel_size': 4537, 'coherence_20': 1.3647557474874026},
  {'kernel_size': 4581, 'coherence_20': 1.5102624437585996},
  {'kernel_size': 3119, 'coherence_20': 1.822369215272226},
  {'kernel_size': 7011, 'coherence_20': 1.500980578424434},
  {'kernel_size': 4656, 'coherence_20': 0.6463166661391256},
  {'kernel_size': 5459, 'coherence_20': 0.8073476581062999},
  {'kernel_size': 6265, 'coherence_20': 1.055874214852745},
  {'kernel_size': 3866, 'coherence_20': 1.0415672403032898},
  {'kernel_size': 4942, 'coherence_20': 1.1340351964469841},
  {'kernel_size': 6454, 'coherence_20': 1.9029969825915538}],
 [{'kernel_size': 7045, 'coherence_20': 2.28471128743316},
  {'kernel_size': 3954, 'coherence_20': 1.0926938724550188},
  {'kernel_size': 5661, 'coherence_20': 1.4819175779630975},
  {'kernel_size': 5874, 'coherence_20': 2.2237503880273057},
  {'kernel_size': 5253, 'coherence_20': 1.3917504429809777},
  {'kernel_size': 3953, 'coherence_20': 0.7116481858097339},
  {'kernel_size': 2878, 'coherence_20': 0.6368880619395431},
  {'kernel_size': 5955, 'coherence_20': 1.4486456243659145},
  {'kernel_size': 3105, 'coherence_20': 0.7580447210859924},
  {'kernel_size': 4067, 'coherence_20': 1.3141774655033924},
  {'kernel_size': 6164, 'coherence_20': 0.804842669334949},
  {'kernel_size': 4232, 'coherence_20': 1.195481223502333},
  {'kernel_size': 6031, 'coherence_20': 0.5452360359339299},
  {'kernel_size': 3220, 'coherence_20': 1.0734275507905813},
  {'kernel_size': 5132, 'coherence_20': 1.643925020129834},
  {'kernel_size': 2605, 'coherence_20': 1.4945935624239033},
  {'kernel_size': 5527, 'coherence_20': 0.720115304665345},
  {'kernel_size': 5939, 'coherence_20': 0.8899874387917244},
  {'kernel_size': 4766, 'coherence_20': 1.391386612517777},
  {'kernel_size': 3648, 'coherence_20': 0.5757256921527965}],
 [{'kernel_size': 4991, 'coherence_20': 1.3456991374269471},
  {'kernel_size': 6030, 'coherence_20': 1.326053645192316},
  {'kernel_size': 3839, 'coherence_20': 1.4202579227637764},
  {'kernel_size': 4553, 'coherence_20': 1.3284500960997716},
  {'kernel_size': 1963, 'coherence_20': 0.6210400838952015},
  {'kernel_size': 4040, 'coherence_20': 0.9053343842079609},
  {'kernel_size': 4613, 'coherence_20': 1.2753304775292436},
  {'kernel_size': 4582, 'coherence_20': 0.9699692283797692},
  {'kernel_size': 5157, 'coherence_20': 1.2410297432414676},
  {'kernel_size': 4991, 'coherence_20': 0.7763379953041643},
  {'kernel_size': 7685, 'coherence_20': 2.229633924240741},
  {'kernel_size': 5808, 'coherence_20': 0.6469901103343341},
  {'kernel_size': 3121, 'coherence_20': 0.9309499295911958},
  {'kernel_size': 3070, 'coherence_20': 0.8038318514734355},
  {'kernel_size': 4621, 'coherence_20': 1.0160943763119894},
  {'kernel_size': 4615, 'coherence_20': 1.8494967551847696},
  {'kernel_size': 5303, 'coherence_20': 1.433531210866541},
  {'kernel_size': 5910, 'coherence_20': 1.0663445687004796},
  {'kernel_size': 4199, 'coherence_20': 0.7682336525282815},
  {'kernel_size': 3631, 'coherence_20': 1.4656878180835993}],
 [{'kernel_size': 5841, 'coherence_20': 2.461134897729597},
  {'kernel_size': 8001, 'coherence_20': 1.7120040537274412},
  {'kernel_size': 3114, 'coherence_20': 0.7427236566641907},
  {'kernel_size': 5518, 'coherence_20': 1.3854336146937818},
  {'kernel_size': 2911, 'coherence_20': 0.6791169868425702},

In [258]:
optimizer._result['model_scores'][0]

{'perplexity_score': 2019.2904052734375,
 'coherence_20': 1.0763733292344704,
 'diversity_euclidean': 0.06002123411499822,
 'diversity_jensenshannon': 0.6703556612184317,
 'diversity_hellinger': 0.7769730574359373,
 'diversity_cosine': 0.7605662490558308,
 'perplexity': 2019.2904052734375}

In [259]:
optimizer._result['model_scores'][1]

{'perplexity_score': 1995.385986328125,
 'coherence_20': 1.307914158119003,
 'diversity_euclidean': 0.06057003777969821,
 'diversity_jensenshannon': 0.6752988023741286,
 'diversity_hellinger': 0.7832085694658533,
 'diversity_cosine': 0.7784690054660054,
 'perplexity': 1995.385986328125}

In [261]:
sum(s['coherence_20'] for s in optimizer._result['bank_topic_scores'][-1]) / 4

2.290243961653438

In [262]:
len(optimizer._result['bank_scores'])

20

In [263]:
optimizer._result['bank_scores'][-1]

{'perplexity_score': 20406.341796875,
 'coherence_20': 2.2902439616534376,
 'diversity_euclidean': 0.0529993253962619,
 'diversity_jensenshannon': 0.7384915005805817,
 'diversity_hellinger': 0.8695520055818792,
 'diversity_cosine': 0.882407099262262,
 'perplexity': 20406.341796875,
 'ppl_fair': 20406.341796875,
 'ppl_cheatty': 4056.141357421875}

In [264]:
optimizer._result['bank_topic_scores'][-1]

[{'kernel_size': 6290,
  'coherence_20': 1.9365857260048487,
  'distance_to_nearest': 0.0},
 {'kernel_size': 5987,
  'coherence_20': 2.350993531411413,
  'distance_to_nearest': 0.8670798186186544},
 {'kernel_size': 4904,
  'coherence_20': 1.665684284462788,
  'distance_to_nearest': 0.9068645569155264},
 {'kernel_size': 6419,
  'coherence_20': 3.2077123047347023,
  'distance_to_nearest': 0.9163295596263876}]

In [133]:
# Real-fixing bank topics

In [85]:
from topnum.search_methods.topic_bank.one_model_train_funcs import _get_topic_model

In [86]:
model

Model(id=--12h57m59s_22d03m2024y---, parent_id=None, experiment_id=None)

In [115]:
phi = model.get_phi()
phi = phi.iloc[phi.index.get_level_values(0).isin([MAIN_MODALITY])]

word2index = {
    word: index for index, word in enumerate(phi.index)
}

bank_phi = optimizer._get_phi(optimizer._topic_bank.topics, word2index)
bank_model = _get_topic_model(
    optimizer._dataset,
    phi=bank_phi,
    scores=optimizer._all_model_scores,
    num_safe_fit_iterations=1
)

In [126]:
bank_phi['topic_7'].sort_values(ascending=False)

@word  женщина        0.015624
       мужчина        0.009646
       животное       0.007323
       группа         0.006627
       вид            0.006488
                        ...
       косить         0.000000
       отдалять       0.000000
       натянутый      0.000000
       драматичный    0.000000
       аврелий        0.000000
Name: topic_7, Length: 19186, dtype: float64

In [122]:
bank_topics['topic_7'].sort_values(ascending=False)

@word  женщина        0.015624
       мужчина        0.009646
       животное       0.007323
       группа         0.006627
       вид            0.006488
                        ...
       косить         0.000000
       отдалять       0.000000
       натянутый      0.000000
       драматичный    0.000000
       аврелий        0.000000
Name: topic_7, Length: 19186, dtype: float64

In [123]:
bank_model.get_phi()['topic_7'].sort_values(ascending=False)

modality  token
@word     ребёнок        0.008598
          группа         0.006715
          вид            0.006035
          женщина        0.005993
          мозг           0.005540
                           ...
          схватывание    0.000000
          немецк         0.000000
          предвзятый     0.000000
          умник          0.000000
          аврелий        0.000000
Name: topic_7, Length: 19186, dtype: float32

In [125]:
class FastFixPhiRegularizer(BaseRegularizer):
    _VERY_BIG_TAU = 10 ** 9

    def __init__(self, name: str, phi, topic_names: List[str]):
        super().__init__(name, tau=self._VERY_BIG_TAU)

        self._topic_names = topic_names
        self._topic_indices = None
        self._phi = phi

    def grad(self, pwt, nwt):
        # print('Fixing')

        rwt = np.zeros_like(pwt)
        parent_phi = self._phi
        
        rwt[:, self._topic_indices] += parent_phi.values[:, self._topic_indices]

        return self.tau * rwt

    def attach(self, model):
        super().attach(model)
        
        phi = self._model.get_phi()
        self._topic_indices = [
            phi.columns.get_loc(topic_name)
            for topic_name in self._topic_names
        ]

In [127]:
regularizer = FastFixPhiRegularizer(
    name='fix',
    phi=bank_phi,
    topic_names=bank_phi.columns,
)

In [128]:
bank_model._fit(
    optimizer._dataset.get_batch_vectorizer(),
    num_iterations=10,
    custom_regularizers={
        regularizer.name: regularizer,
    }
)

In [129]:
bank_model.get_phi()['topic_7'].sort_values(ascending=False)

modality  token
@word     женщина        0.015622
          мужчина        0.009645
          животное       0.007322
          группа         0.006628
          вид            0.006488
                           ...
          полимер        0.000000
          разлагаться    0.000000
          микросхема     0.000000
          принтер        0.000000
          аврелий        0.000000
Name: topic_7, Length: 19186, dtype: float32

In [131]:
coherence_score.call_by_topic(bank_model)

{0: array([1.18129293]),
 1: array([0.94094366]),
 2: array([0.92717515]),
 3: array([0.8584458]),
 4: array([0.96024055]),
 5: array([0.94228977]),
 6: array([1.14422727]),
 7: array([0.89189949])}

In [132]:
coherence_score.call(bank_model)

array([0.98081433])

In [135]:
optimizer._result['bank_scores'][-1]

{'perplexity_score': 3875.74169921875,
 'coherence_20': 0.564805432002065,
 'diversity_euclidean': 0.03567965163581824,
 'diversity_jensenshannon': 0.5957037221303795,
 'diversity_hellinger': 0.6853192252936954,
 'diversity_cosine': 0.6242113090660045,
 'perplexity': 3875.74169921875}

In [136]:
optimizer._get_default_scores(bank_model)

{'perplexity_score': 5749.072265625,
 'coherence_20': 0.98081432765508,
 'diversity_euclidean': 0.04722044093307479,
 'diversity_jensenshannon': 0.6019876723935436,
 'diversity_hellinger': 0.6929207704718845,
 'diversity_cosine': 0.745312495094132,
 'perplexity': 5749.072265625}

In [78]:
model = init_model_from_family('ARTM', DATASET, MAIN_MODALITY, 2, 0)

No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

In [80]:
m._fit(DATASET.get_batch_vectorizer(), 2)

In [82]:
m.get_phi()

                        topic_0   topic_1  background_2
modality token
@word    инвалидность  0.000000  0.000000      0.000011
         мазка         0.000000  0.000000      0.000011
         professor     0.000000  0.000000      0.000011
         умно          0.000000  0.000000      0.000011
         игил          0.000000  0.000000      0.000011
...                         ...       ...           ...
         милосердие    0.000000  0.000000      0.000015
         поверка       0.000000  0.000000      0.000015
         вто           0.000083  0.000000      0.000025
         слоить        0.000003  0.000012      0.000076
         акт           0.000210  0.000083      0.000123

[19186 rows x 3 columns]

In [37]:
import artm
from topnum.model_constructor import KnownModel, init_plsa
from topicnet.cooking_machine.rel_toolbox_lite import (
    count_vocab_size,
    transform_regularizer,
)
from topicnet.cooking_machine.model_constructor import (
    add_standard_scores,
    create_default_topics,
    init_model,
)

def init_model_from_family(
        family: str or KnownModel,
        dataset: Dataset,
        main_modality: str,
        num_topics: int,
        seed: int,
        specific_topic_names = None,
        modalities_to_use: List[str] = None,
        num_processors: int = 3,
        model_params: dict = None,
):
    """
    Returns
    -------
    model: TopicModel() instance
    """
    if isinstance(family, KnownModel):
        family = family.value

    if modalities_to_use is None:
        modalities_to_use = [main_modality]

    custom_regs = {}

    if family == "LDA":
        model = init_lda(
            dataset, modalities_to_use, main_modality, num_topics, model_params
        )
    elif family == "PLSA":
        model = init_plsa(
            dataset, modalities_to_use, main_modality, num_topics
        )
    elif family == "TARTM":
        model, custom_regs = init_thetaless(
            dataset, modalities_to_use, main_modality, num_topics, model_params
        )
    elif family == "sparse":
        model = init_bcg_sparse_model(
            dataset, modalities_to_use, main_modality, num_topics, 1, model_params
        )
    elif family == "decorrelation":
        model = init_decorrelated_plsa(
            dataset, modalities_to_use, main_modality, num_topics, model_params
        )
    elif family == "ARTM":
        model = init_baseline_artm(
            dataset, modalities_to_use, main_modality, num_topics, 1, specific_topic_names, model_params
        )
    else:
        raise ValueError(f'family: {family}')

    model.num_processors = num_processors

    if seed is not None:
        model.seed = seed

    dictionary = dataset.get_dictionary()

    # TODO: maybe this cycle is not necessary
    for modality in dataset.get_possible_modalities():
        if modality not in modalities_to_use:
            dictionary.filter(class_id=modality, max_df=0, inplace=True)

    model.initialize(dictionary)
    add_standard_scores(model, dictionary, main_modality=main_modality,
                        all_modalities=modalities_to_use)

    model = TopicModel(
        artm_model=model,
        custom_regularizers=custom_regs
    )
    model.has_bcg = True  # TODO: only if init_bcg_sparse_model

    return model


def init_bcg_sparse_model(
        dataset,
        modalities_to_use,
        main_modality,
        specific_topics,
        bcg_topics,
        specific_topic_names = None,
        model_params: dict = None
):
    """
    Creates simple artm model with standard scores.

    Parameters
    ----------
    dataset : Dataset
    modalities_to_use : list of str or dict
    main_modality : str
    specific_topics : int
    bcg_topics : int

    Returns
    -------
    model: artm.ARTM() instance
    """
    if model_params is None:
        model_params = dict()

    model = init_plsa(
        dataset, modalities_to_use, main_modality, specific_topics, bcg_topics
    )
    background_topic_names = model.topic_names[-bcg_topics:]

    if specific_topic_names is None:
        print('No spec topics')
        specific_topic_names = model.topic_names[:-bcg_topics]

    dictionary = dataset.get_dictionary()
    baseline_class_ids = {class_id: 1 for class_id in modalities_to_use}
    data_stats = count_vocab_size(dictionary, baseline_class_ids)

    # all coefficients are relative
    regularizers = [
        artm.SmoothSparsePhiRegularizer(
             name='smooth_phi_bcg',
             topic_names=background_topic_names,
             tau=model_params.get("smooth_bcg_tau", 0.1),
             class_ids=[main_modality],
        ),
        artm.SmoothSparseThetaRegularizer(
             name='smooth_theta_bcg',
             topic_names=background_topic_names,
             tau=model_params.get("smooth_bcg_tau", 0.1),
        ),
        artm.SmoothSparsePhiRegularizer(
             name='sparse_phi_sp',
             topic_names=specific_topic_names,
             tau=model_params.get("sparse_sp_tau", -0.05),
             class_ids=[main_modality],
            ),
        artm.SmoothSparseThetaRegularizer(
             name='sparse_theta_sp',
             topic_names=specific_topic_names,
             tau=model_params.get("sparse_sp_tau", -0.05),
        ),
    ]
    for reg in regularizers:
        model.regularizers.add(transform_regularizer(
            data_stats,
            reg,
            model.class_ids,
            n_topics=len(reg.topic_names)
        ))

    return model


def init_baseline_artm(
        dataset,
        modalities_to_use,
        main_modality,
        num_topics,
        bcg_topics,
        specific_topic_names = None,
        model_params: dict = None,
):
    """
    Creates simple artm model with standard scores.

    Parameters
    ----------
    dataset : Dataset
    modalities_to_use : list of str
    main_modality : str
    num_topics : int

    Returns
    -------
    model: artm.ARTM() instance
    """
    if model_params is None:
        model_params = dict()

    model = init_bcg_sparse_model(
        dataset, modalities_to_use, main_modality, num_topics, bcg_topics, specific_topic_names, model_params
    )

    if specific_topic_names is None:
        print('No spec topics')
        specific_topic_names = model.topic_names[:-bcg_topics]

    model.regularizers.add(
        artm.DecorrelatorPhiRegularizer(
            gamma=0,
            tau=model_params.get('decorrelation_tau', 0.01),
            name='decorrelation',
            topic_names=specific_topic_names,
            class_ids=modalities_to_use,
        )
    )

    return model

In [38]:
def artm_train_func(
        dataset: Dataset,
        model_number: int,
        num_topics: int,
        num_fit_iterations: int,
        scores: List = None,
        **kwargs) -> TopicModel:
    """

    Additional Parameters
    ---------------------
    kwargs
        Some params for `_get_topic_model`, such as `cache_theta` and `num_processors`
    """

    topic_model = init_model_from_family(
        family='ARTM',
        dataset=DATASET,
        main_modality=MAIN_MODALITY,
        num_topics=ONE_MODEL_NUM_TOPICS,
        seed=model_number,
        model_params={
            'decorrelation_tau': 0.01,  # best values
            'smooth_bcg_tau': 0.05,
            'sparse_sp_tau': -0.05,
        }
    )

    num_fit_iterations_with_scores = 1

    topic_model._fit(
        dataset.get_batch_vectorizer(),
        num_iterations=max(0, num_fit_iterations - num_fit_iterations_with_scores)
    )
    _fit_model_with_scores(
        topic_model,
        DATASET,
        scores,
        num_fit_iterations=num_fit_iterations_with_scores
    )

    return topic_model


def _fit_model_with_scores(
        topic_model: TopicModel,
        dataset: Dataset,
        scores: List = None,
        num_fit_iterations: int = 1):

    if scores is not None:
        for score in scores:
            score._attach(topic_model)

    topic_model._fit(
        dataset.get_batch_vectorizer(),
        num_iterations=num_fit_iterations
    )

### Bank Creation<a id="bank-creation"></a>

<div style="text-align: right">Back to <a href=#contents>Contents</a></div>

Here we finally run the experiment!

In [39]:
NUM_ITERATIONS = 20

In [40]:
seed = 0

In [41]:
# We use only one train function here
# Other variations are also possible
# It would be even better to make bank using several train functions
# However, it would also take way more time 

TRAIN_FUNCS = artm_train_func  # default train func

In [42]:
DATASET_INTERNALS_FOLDER_PATH

'/data_mil/shared/CompressaAI/iterative/data/noow/20_Newsgroups__internals'

In [45]:
SEARCH_RESULTS_FOLDER_PATH = os.path.join(
    DATASET_INTERNALS_FOLDER_PATH, 'result2'
)

# File with some info about the process
SEARCH_RESULT_FILE_PATH = os.path.join(
    SEARCH_RESULTS_FOLDER_PATH, f'search_result__{seed}.json'
)

# Bank, with topics and their score values
BANK_FOLDER_PATH = os.path.join(
    SEARCH_RESULTS_FOLDER_PATH, f'bank__{seed}'
)

In [75]:
SEARCH_RESULTS_FOLDER_PATH

'/data_mil/shared/CompressaAI/iterative/data/noow/20_Newsgroups__internals/result2'

! rm -r $SEARCH_RESULTS_FOLDER_PATH

In [76]:
! ls /data_mil/shared/CompressaAI/iterative/data/noow/20_Newsgroups__internals

batches  dict.dict  result2  vw.txt

In [77]:
! mv /data_mil/shared/CompressaAI/iterative/data/noow/20_Newsgroups__internals/result2 /data_mil/shared/CompressaAI/iterative/data/noow/20_Newsgroups__internals/_result2

In [47]:
BANK_FOLDER_PATH

'/data_mil/shared/CompressaAI/iterative/data/noow/20_Newsgroups__internals/result2/bank__0'

In [80]:
os.makedirs(SEARCH_RESULTS_FOLDER_PATH, exist_ok=True)
os.makedirs(BANK_FOLDER_PATH, exist_ok=True)

In [79]:
BANK_FOLDER_PATH

'/data_mil/shared/CompressaAI/iterative/data/noow/20_Newsgroups__internals/result2/bank__0'

In [49]:
seed

0

# https://github.com/machine-intelligence-laboratory/OptimalNumberOfTopics/blob/master/topnum/model_constructor.py#L120C5-L122C73

dictionary = DATASET.get_dictionary()

print(dictionary)

for modality in DATASET.get_possible_modalities():
    if modality not in [MAIN_MODALITY]:
        dictionary.filter(class_id=modality, max_df=0, inplace=True)

In [74]:
print(dictionary)

artm.Dictionary(name=7c5c8f34-b670-4348-a275-21f2f47a0094, num_entries=52744)

DATASET._cached_dict = dictionary

DATASET.get_dictionary()

One cay vary some parameters below (for example `max_num_models` and `num_fit_iterations`).

In [82]:
optimizer = TopicBankMethod(
    data        = DATASET,
    main_modality = MAIN_MODALITY,
    
    min_df_rate = 0.0,  # dictionary filtering has already been done little earlier
    max_df_rate = 1.0,  #   so we don't want these parameters to have any effect

    main_topic_score   = intra_coherence_score,  # coherence_score,
    other_topic_scores = [coherence_score],
    other_scores       = [coherence_score] + diversity_scores + other_scores,
    documents          = DOCUMENTS,

    start_model_number   = 0,
    max_num_models       = 20,
    one_model_num_topics = ONE_MODEL_NUM_TOPICS,  # 100,
    num_fit_iterations   = NUM_ITERATIONS,  # 100,  # 100 should be enough;
                                 # however, for big data better to reduce this one
                                 # (otherwise the process will be too slow)
    #                                  70%                    80%
    topic_score_threshold_percentile = 2.7242325146624466,  # 3.040353129463432,  # DIFF ALSO HERE

    save_bank         = True,
    save_model_topics = True,
    save_file_path    = SEARCH_RESULT_FILE_PATH,
    bank_folder_path  = BANK_FOLDER_PATH,

    train_funcs = TRAIN_FUNCS,
    
    verbose = True,
)

# TODO: use Holdout Perplexity as Stop score

In [83]:
optimizer._result.keys()

dict_keys(['optimum', 'optimum_std', 'bank_scores', 'bank_topic_scores', 'model_scores', 'model_topic_scores', 'num_bank_topics', 'num_model_topics'])

Checking file paths

! ls ./Post_Science__internals

In [84]:
optimizer._save_file_path

'/data_mil/shared/CompressaAI/iterative/data/noow/20_Newsgroups__internals/result2/search_result__0.json'

In [85]:
optimizer._topic_bank._path

'/data_mil/shared/CompressaAI/iterative/data/noow/20_Newsgroups__internals/result2/bank__0'

Fulfilling the search (get ready for a really long process!):

In [ ]:
%%time

optimizer.search_for_optimum(DATASET)

  0%|                                                        | 0/20 [00:00<?, ?it/s]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).

  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████                        | 1/2 [03:15<03:15, 195.69s/it]Detected bcg topics! Skipping for coherence computation (and will have 20 topics).

100%|█████████████████████████████████████████████████| 2/2 [03:16<00:00, 98.02s/it]
Using absoulte threshold: 2.7242325146624466.
Skipping saving scores for bcg topic
!!! Bank Phi: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 ...
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]].
!!! Bank model Phi: [[2.3129558e-10 1.7799420e-11 7.3182476e-12 7.4339329e-10]
 [9.5652342e-10 0.0000000e+00 1.6966954e-11 2.6152797e-11]
 [9.9790454e-10 6.3112588e-14 1.6708952e-12 0.0000000e+00]
 ...
 [9.9955477e-10 2.4380372e-16 0.0000000e+00 8.3742766e-14]
 [9.9953490e-10 0.0000000e+00 0.0000000e+00 1.0384085e-13]
 [9.9957809e-10 0.0000000e+00 0.0000000e+00 6.0722098e-14]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 ...
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 3.6663791e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 3.6663791e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 3.6663791e-06]
 ...
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 3.6663791e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 3.6663791e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 3.6663791e-06]].
Bank scores: {'perplexity_score': 32739.00390625, 'coherence_20': 1.3896053784454143, 'diversity_euclidean': 0.08200421403563253, 'diversity_jensenshannon': 0.7221991425415712, 'diversity_hellinger': 0.8463170087111718, 'diversity_cosine': 0.8610930598620632, 'perplexity': 32739.00390625, 'ppl_fair': 32739.00390625, 'ppl_cheatty': 4032.428466796875}
  5%|██▎                                          | 1/20 [04:11<1:19:36, 251.38s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).

  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████                        | 1/2 [03:12<03:12, 192.21s/it]Detected bcg topics! Skipping for coherence computation (and will have 20 topics).

100%|█████████████████████████████████████████████████| 2/2 [03:12<00:00, 96.28s/it]
Using absoulte threshold: 2.7242325146624466.
Creating first level with 4 topics. Dictionary: artm.Dictionary(name=7c5c8f34-b670-4348-a275-21f2f47a0094, num_entries=52744).
Copying phi for the first level. Phi shape: (52744, 4). First words: MultiIndex([('@lemmatized',       'willow'),
            ('@lemmatized',        'bodin'),
            ('@lemmatized',     'aneurysm'),
            ('@lemmatized',       'millie'),
            ('@lemmatized',   'paroxysmal'),
            ('@lemmatized', 'intracranial'),
            ('@lemmatized',        'ofthe'),
            ('@lemmatized',      'kneecap'),
            ('@lemmatized',       'alesis'),
            ('@lemmatized',     'libertae')],
           )
Creating second level with 21 topics
Copying phi for the second level. Phi shape: (52744, 21). First words: MultiIndex([('@lemmatized',       'willow'),
            ('@lemmatized',        'bodin'),
            ('@lemmatized',     'aneurysm'),
            ('@lemmatized',       'millie'),
            ('@lemmatized',   'paroxysmal'),
            ('@lemmatized', 'intracranial'),
            ('@lemmatized',        'ofthe'),
            ('@lemmatized',      'kneecap'),
            ('@lemmatized',       'alesis'),
            ('@lemmatized',     'libertae')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic
!!! Bank Phi: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 ...
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]].
!!! Bank model Phi: [[2.31295372e-10 1.77994269e-11 7.31824757e-12 7.43393513e-10]
 [9.56523416e-10 0.00000000e+00 1.69670007e-11 2.61528681e-11]
 [9.97904537e-10 6.31126824e-14 1.67089866e-12 0.00000000e+00]
 ...
 [9.99554772e-10 2.43804034e-16 0.00000000e+00 8.37430236e-14]
 [9.99534899e-10 0.00000000e+00 0.00000000e+00 1.03841144e-13]
 [9.99577976e-10 0.00000000e+00 0.00000000e+00 6.07222809e-14]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 ...
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 3.6663791e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 3.6663791e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 3.6663791e-06]
 ...
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 3.6663791e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 3.6663791e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 3.6663791e-06]].
Bank scores: {'perplexity_score': 32739.00390625, 'coherence_20': 1.3896053784454143, 'diversity_euclidean': 0.08200421403517877, 'diversity_jensenshannon': 0.7221991425380287, 'diversity_hellinger': 0.846317008711511, 'diversity_cosine': 0.8610930598504266, 'perplexity': 32739.00390625, 'ppl_fair': 32739.00390625, 'ppl_cheatty': 4032.428466796875}
 10%|████▌                                        | 2/20 [08:27<1:16:10, 253.91s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).

  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████                        | 1/2 [03:14<03:14, 194.49s/it]Detected bcg topics! Skipping for coherence computation (and will have 20 topics).

100%|█████████████████████████████████████████████████| 2/2 [03:14<00:00, 97.42s/it]
Using absoulte threshold: 2.7242325146624466.
Creating first level with 4 topics. Dictionary: artm.Dictionary(name=7c5c8f34-b670-4348-a275-21f2f47a0094, num_entries=52744).
Copying phi for the first level. Phi shape: (52744, 4). First words: MultiIndex([('@lemmatized',       'willow'),
            ('@lemmatized',        'bodin'),
            ('@lemmatized',     'aneurysm'),
            ('@lemmatized',       'millie'),
            ('@lemmatized',   'paroxysmal'),
            ('@lemmatized', 'intracranial'),
            ('@lemmatized',        'ofthe'),
            ('@lemmatized',      'kneecap'),
            ('@lemmatized',       'alesis'),
            ('@lemmatized',     'libertae')],
           )
Creating second level with 21 topics
Copying phi for the second level. Phi shape: (52744, 21). First words: MultiIndex([('@lemmatized',       'willow'),
            ('@lemmatized',        'bodin'),
            ('@lemmatized',     'aneurysm'),
            ('@lemmatized',       'millie'),
            ('@lemmatized',   'paroxysmal'),
            ('@lemmatized', 'intracranial'),
            ('@lemmatized',        'ofthe'),
            ('@lemmatized',      'kneecap'),
            ('@lemmatized',       'alesis'),
            ('@lemmatized',     'libertae')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic
!!! Bank Phi: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]].
!!! Bank model Phi: [[2.3755867e-10 2.3374934e-11 6.8052937e-12 7.3209455e-10 0.0000000e+00]
 [8.3058554e-10 0.0000000e+00 7.1458815e-12 1.7051180e-11 1.4490338e-10]
 [9.9884578e-10 5.5550653e-14 7.5893518e-13 0.0000000e+00 0.0000000e+00]
 ...
 [9.9956488e-10 0.0000000e+00 0.0000000e+00 2.7527090e-14 6.7861969e-14]
 [9.9962594e-10 0.0000000e+00 0.0000000e+00 3.4136299e-14 1.0377047e-16]
 [9.9963426e-10 0.0000000e+00 0.0000000e+00 1.9960885e-14 6.1317846e-15]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  4.0001714e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  4.0001714e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  4.0001714e-06]
 ...
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  4.0001714e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  4.0001714e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  4.0001714e-06]].
Bank scores: {'perplexity_score': 22313.8359375, 'coherence_20': 1.559244214684277, 'diversity_euclidean': 0.07841112370273699, 'diversity_jensenshannon': 0.7196000541231238, 'diversity_hellinger': 0.8432154865129015, 'diversity_cosine': 0.8687518872642788, 'perplexity': 22313.8359375, 'ppl_fair': 22313.8359375, 'ppl_cheatty': 3793.111572265625}
 15%|██████▊                                      | 3/20 [12:47<1:12:47, 256.91s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).

  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████                        | 1/2 [03:14<03:14, 194.13s/it]Detected bcg topics! Skipping for coherence computation (and will have 20 topics).

100%|█████████████████████████████████████████████████| 2/2 [03:14<00:00, 97.24s/it]
Using absoulte threshold: 2.7242325146624466.
Creating first level with 5 topics. Dictionary: artm.Dictionary(name=7c5c8f34-b670-4348-a275-21f2f47a0094, num_entries=52744).
Copying phi for the first level. Phi shape: (52744, 5). First words: MultiIndex([('@lemmatized',       'willow'),
            ('@lemmatized',        'bodin'),
            ('@lemmatized',     'aneurysm'),
            ('@lemmatized',       'millie'),
            ('@lemmatized',   'paroxysmal'),
            ('@lemmatized', 'intracranial'),
            ('@lemmatized',        'ofthe'),
            ('@lemmatized',      'kneecap'),
            ('@lemmatized',       'alesis'),
            ('@lemmatized',     'libertae')],
           )
Creating second level with 21 topics
Copying phi for the second level. Phi shape: (52744, 21). First words: MultiIndex([('@lemmatized',       'willow'),
            ('@lemmatized',        'bodin'),
            ('@lemmatized',     'aneurysm'),
            ('@lemmatized',       'millie'),
            ('@lemmatized',   'paroxysmal'),
            ('@lemmatized', 'intracranial'),
            ('@lemmatized',        'ofthe'),
            ('@lemmatized',      'kneecap'),
            ('@lemmatized',       'alesis'),
            ('@lemmatized',     'libertae')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic
!!! Bank Phi: [[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  1.49941498e-05 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.50408341e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.50408341e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.50408341e-05]].
!!! Bank model Phi: [[6.5072607e-11 1.8814149e-12 0.0000000e+00 ... 0.0000000e+00
  2.6969335e-10 4.5776225e-13]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  1.4992821e-05 0.0000000e+00]
 [9.9806241e-10 0.0000000e+00 5.9848312e-13 ... 0.0000000e+00
  4.4882926e-13 6.4424572e-13]
 ...
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.5039565e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.5039565e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.5039565e-05]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  1.49941498e-05 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.50408341e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.50408341e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.50408341e-05]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 4.8123356e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 1.4993921e-05
  0.0000000e+00 3.4755806e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 4.8123356e-06]
 ...
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  1.5040478e-05 3.3622030e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  1.5040478e-05 3.3622030e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  1.5040478e-05 3.3622030e-06]].
Bank scores: {'perplexity_score': 9888.765625, 'coherence_20': 1.4330588372817628, 'diversity_euclidean': 0.07849906563624495, 'diversity_jensenshannon': 0.7172351112952651, 'diversity_hellinger': 0.8407884846420863, 'diversity_cosine': 0.866761334316723, 'perplexity': 9888.765625, 'ppl_fair': 9888.765625, 'ppl_cheatty': 3427.144775390625}
 20%|█████████                                    | 4/20 [17:10<1:09:11, 259.48s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).

  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████                        | 1/2 [03:13<03:13, 193.47s/it]Detected bcg topics! Skipping for coherence computation (and will have 20 topics).

100%|█████████████████████████████████████████████████| 2/2 [03:13<00:00, 96.92s/it]
Using absoulte threshold: 2.7242325146624466.
Creating first level with 7 topics. Dictionary: artm.Dictionary(name=7c5c8f34-b670-4348-a275-21f2f47a0094, num_entries=52744).
Copying phi for the first level. Phi shape: (52744, 7). First words: MultiIndex([('@lemmatized',       'willow'),
            ('@lemmatized',        'bodin'),
            ('@lemmatized',     'aneurysm'),
            ('@lemmatized',       'millie'),
            ('@lemmatized',   'paroxysmal'),
            ('@lemmatized', 'intracranial'),
            ('@lemmatized',        'ofthe'),
            ('@lemmatized',      'kneecap'),
            ('@lemmatized',       'alesis'),
            ('@lemmatized',     'libertae')],
           )
Creating second level with 21 topics
Copying phi for the second level. Phi shape: (52744, 21). First words: MultiIndex([('@lemmatized',       'willow'),
            ('@lemmatized',        'bodin'),
            ('@lemmatized',     'aneurysm'),
            ('@lemmatized',       'millie'),
            ('@lemmatized',   'paroxysmal'),
            ('@lemmatized', 'intracranial'),
            ('@lemmatized',        'ofthe'),
            ('@lemmatized',      'kneecap'),
            ('@lemmatized',       'alesis'),
            ('@lemmatized',     'libertae')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic
!!! Bank Phi: [[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  1.49941498e-05 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.50408341e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.50408341e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.50408341e-05]].
!!! Bank model Phi: [[6.5072496e-11 1.8814121e-12 0.0000000e+00 ... 0.0000000e+00
  2.6969291e-10 4.5776181e-13]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  1.4992821e-05 0.0000000e+00]
 [9.9806241e-10 0.0000000e+00 5.9848269e-13 ... 0.0000000e+00
  4.4882877e-13 6.4424545e-13]
 ...
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.5039565e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.5039565e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.5039565e-05]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  1.49941498e-05 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.50408341e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.50408341e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.50408341e-05]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 4.8123356e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 1.4993921e-05
  0.0000000e+00 3.4755806e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 4.8123356e-06]
 ...
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  1.5040478e-05 3.3622030e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  1.5040478e-05 3.3622030e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  1.5040478e-05 3.3622030e-06]].
Bank scores: {'perplexity_score': 9888.765625, 'coherence_20': 1.4330588372817628, 'diversity_euclidean': 0.07849906563635034, 'diversity_jensenshannon': 0.7172351112951487, 'diversity_hellinger': 0.840788484638804, 'diversity_cosine': 0.8667613343170243, 'perplexity': 9888.765625, 'ppl_fair': 9888.765625, 'ppl_cheatty': 3427.144775390625}
 25%|███████████▎                                 | 5/20 [21:29<1:04:49, 259.29s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).

  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████                        | 1/2 [03:14<03:14, 194.09s/it]Detected bcg topics! Skipping for coherence computation (and will have 20 topics).

100%|█████████████████████████████████████████████████| 2/2 [03:14<00:00, 97.22s/it]
Using absoulte threshold: 2.7242325146624466.
Creating first level with 7 topics. Dictionary: artm.Dictionary(name=7c5c8f34-b670-4348-a275-21f2f47a0094, num_entries=52744).
Copying phi for the first level. Phi shape: (52744, 7). First words: MultiIndex([('@lemmatized',       'willow'),
            ('@lemmatized',        'bodin'),
            ('@lemmatized',     'aneurysm'),
            ('@lemmatized',       'millie'),
            ('@lemmatized',   'paroxysmal'),
            ('@lemmatized', 'intracranial'),
            ('@lemmatized',        'ofthe'),
            ('@lemmatized',      'kneecap'),
            ('@lemmatized',       'alesis'),
            ('@lemmatized',     'libertae')],
           )
Creating second level with 21 topics
Copying phi for the second level. Phi shape: (52744, 21). First words: MultiIndex([('@lemmatized',       'willow'),
            ('@lemmatized',        'bodin'),
            ('@lemmatized',     'aneurysm'),
            ('@lemmatized',       'millie'),
            ('@lemmatized',   'paroxysmal'),
            ('@lemmatized', 'intracranial'),
            ('@lemmatized',        'ofthe'),
            ('@lemmatized',      'kneecap'),
            ('@lemmatized',       'alesis'),
            ('@lemmatized',     'libertae')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic
!!! Bank Phi: [[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  1.49941498e-05 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.50408341e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.50408341e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.50408341e-05]].
!!! Bank model Phi: [[6.5072614e-11 1.8814149e-12 0.0000000e+00 ... 0.0000000e+00
  2.6969332e-10 4.5776230e-13]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  1.4992821e-05 0.0000000e+00]
 [9.9806241e-10 0.0000000e+00 5.9848301e-13 ... 0.0000000e+00
  4.4882915e-13 6.4424551e-13]
 ...
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.5039565e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.5039565e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.5039565e-05]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  1.49941498e-05 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.50408341e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.50408341e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.50408341e-05]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 4.8123356e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 1.4993921e-05
  0.0000000e+00 3.4755806e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 4.8123356e-06]
 ...
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  1.5040478e-05 3.3622030e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  1.5040478e-05 3.3622030e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  1.5040478e-05 3.3622030e-06]].
Bank scores: {'perplexity_score': 9888.765625, 'coherence_20': 1.4330588372817628, 'diversity_euclidean': 0.0784990656362227, 'diversity_jensenshannon': 0.7172351112945621, 'diversity_hellinger': 0.8407884846404905, 'diversity_cosine': 0.8667613343165778, 'perplexity': 9888.765625, 'ppl_fair': 9888.765625, 'ppl_cheatty': 3427.144775390625}
 30%|█████████████▌                               | 6/20 [25:50<1:00:34, 259.58s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).

  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████                        | 1/2 [03:14<03:14, 194.04s/it]Detected bcg topics! Skipping for coherence computation (and will have 20 topics).

100%|█████████████████████████████████████████████████| 2/2 [03:14<00:00, 97.19s/it]
Using absoulte threshold: 2.7242325146624466.
Creating first level with 7 topics. Dictionary: artm.Dictionary(name=7c5c8f34-b670-4348-a275-21f2f47a0094, num_entries=52744).
Copying phi for the first level. Phi shape: (52744, 7). First words: MultiIndex([('@lemmatized',       'willow'),
            ('@lemmatized',        'bodin'),
            ('@lemmatized',     'aneurysm'),
            ('@lemmatized',       'millie'),
            ('@lemmatized',   'paroxysmal'),
            ('@lemmatized', 'intracranial'),
            ('@lemmatized',        'ofthe'),
            ('@lemmatized',      'kneecap'),
            ('@lemmatized',       'alesis'),
            ('@lemmatized',     'libertae')],
           )
Creating second level with 21 topics
Copying phi for the second level. Phi shape: (52744, 21). First words: MultiIndex([('@lemmatized',       'willow'),
            ('@lemmatized',        'bodin'),
            ('@lemmatized',     'aneurysm'),
            ('@lemmatized',       'millie'),
            ('@lemmatized',   'paroxysmal'),
            ('@lemmatized', 'intracranial'),
            ('@lemmatized',        'ofthe'),
            ('@lemmatized',      'kneecap'),
            ('@lemmatized',       'alesis'),
            ('@lemmatized',     'libertae')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic
!!! Bank Phi: [[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 1.49941498e-05
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  1.50408341e-05 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  1.50408341e-05 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  1.50408341e-05 0.00000000e+00]].
!!! Bank model Phi: [[2.95909944e-14 0.00000000e+00 3.09707446e-12 ... 7.49774483e-13
  9.91345450e-10 4.34710124e-12]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 1.49926937e-05
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 8.73307926e-10 0.00000000e+00 ... 1.08618335e-13
  4.67293565e-12 1.21659002e-10]
 ...
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  1.50392707e-05 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  1.50392707e-05 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  1.50392707e-05 0.00000000e+00]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 1.49941498e-05
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  1.50408341e-05 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  1.50408341e-05 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  1.50408341e-05 0.00000000e+00]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 4.4443013e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 3.2047369e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 4.4443013e-06]
 ...
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 1.5040479e-05
  0.0000000e+00 3.1020711e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 1.5040479e-05
  0.0000000e+00 3.1020711e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 1.5040479e-05
  0.0000000e+00 3.1020711e-06]].
Bank scores: {'perplexity_score': 9784.95703125, 'coherence_20': 1.4562664015395566, 'diversity_euclidean': 0.07527089951916563, 'diversity_jensenshannon': 0.7202812068551567, 'diversity_hellinger': 0.8456859225164308, 'diversity_cosine': 0.8672235294385631, 'perplexity': 9784.95703125, 'ppl_fair': 9784.95703125, 'ppl_cheatty': 3442.1328125}
 35%|████████████████▍                              | 7/20 [30:15<56:39, 261.47s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).

  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████                        | 1/2 [03:13<03:13, 193.96s/it]Detected bcg topics! Skipping for coherence computation (and will have 20 topics).

100%|█████████████████████████████████████████████████| 2/2 [03:14<00:00, 97.15s/it]
Using absoulte threshold: 2.7242325146624466.
Creating first level with 7 topics. Dictionary: artm.Dictionary(name=7c5c8f34-b670-4348-a275-21f2f47a0094, num_entries=52744).
Copying phi for the first level. Phi shape: (52744, 7). First words: MultiIndex([('@lemmatized',       'willow'),
            ('@lemmatized',        'bodin'),
            ('@lemmatized',     'aneurysm'),
            ('@lemmatized',       'millie'),
            ('@lemmatized',   'paroxysmal'),
            ('@lemmatized', 'intracranial'),
            ('@lemmatized',        'ofthe'),
            ('@lemmatized',      'kneecap'),
            ('@lemmatized',       'alesis'),
            ('@lemmatized',     'libertae')],
           )
Creating second level with 21 topics
Copying phi for the second level. Phi shape: (52744, 21). First words: MultiIndex([('@lemmatized',       'willow'),
            ('@lemmatized',        'bodin'),
            ('@lemmatized',     'aneurysm'),
            ('@lemmatized',       'millie'),
            ('@lemmatized',   'paroxysmal'),
            ('@lemmatized', 'intracranial'),
            ('@lemmatized',        'ofthe'),
            ('@lemmatized',      'kneecap'),
            ('@lemmatized',       'alesis'),
            ('@lemmatized',     'libertae')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic
!!! Bank Phi: [[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 1.49941498e-05
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 6.64047548e-06]
 ...
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]].
!!! Bank model Phi: [[2.1962848e-14 0.0000000e+00 5.8446561e-14 ... 1.5353232e-13
  9.3665276e-10 6.3004435e-11]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 1.4991541e-05
  0.0000000e+00 0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 6.6402963e-06]
 ...
 [9.9996789e-10 0.0000000e+00 0.0000000e+00 ... 2.9371293e-15
  1.0498275e-16 0.0000000e+00]
 [9.9996977e-10 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 0.0000000e+00]
 [9.9997222e-10 0.0000000e+00 0.0000000e+00 ... 2.6537209e-16
  0.0000000e+00 0.0000000e+00]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 1.49941498e-05
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 6.64047548e-06]
 ...
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 4.4622066e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 3.2176899e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  6.6402035e-06 3.7970747e-06]
 ...
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 4.4622066e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 4.4622066e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 4.4622066e-06]].
Bank scores: {'perplexity_score': 11263.4912109375, 'coherence_20': 1.3719767145389439, 'diversity_euclidean': 0.07234430920869535, 'diversity_jensenshannon': 0.699040359319785, 'diversity_hellinger': 0.8178079641203966, 'diversity_cosine': 0.8202842396546204, 'perplexity': 11263.4912109375, 'ppl_fair': 11263.4912109375, 'ppl_cheatty': 3498.62841796875}
 40%|██████████████████▊                            | 8/20 [34:41<52:34, 262.87s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).

  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████                        | 1/2 [03:13<03:13, 193.48s/it]Detected bcg topics! Skipping for coherence computation (and will have 20 topics).

100%|█████████████████████████████████████████████████| 2/2 [03:13<00:00, 96.92s/it]
Using absoulte threshold: 2.7242325146624466.
Creating first level with 7 topics. Dictionary: artm.Dictionary(name=7c5c8f34-b670-4348-a275-21f2f47a0094, num_entries=52744).
Copying phi for the first level. Phi shape: (52744, 7). First words: MultiIndex([('@lemmatized',       'willow'),
            ('@lemmatized',        'bodin'),
            ('@lemmatized',     'aneurysm'),
            ('@lemmatized',       'millie'),
            ('@lemmatized',   'paroxysmal'),
            ('@lemmatized', 'intracranial'),
            ('@lemmatized',        'ofthe'),
            ('@lemmatized',      'kneecap'),
            ('@lemmatized',       'alesis'),
            ('@lemmatized',     'libertae')],
           )
Creating second level with 21 topics
Copying phi for the second level. Phi shape: (52744, 21). First words: MultiIndex([('@lemmatized',       'willow'),
            ('@lemmatized',        'bodin'),
            ('@lemmatized',     'aneurysm'),
            ('@lemmatized',       'millie'),
            ('@lemmatized',   'paroxysmal'),
            ('@lemmatized', 'intracranial'),
            ('@lemmatized',        'ofthe'),
            ('@lemmatized',      'kneecap'),
            ('@lemmatized',       'alesis'),
            ('@lemmatized',     'libertae')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic
!!! Bank Phi: [[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 1.49941498e-05
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 6.64047548e-06]
 ...
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]].
!!! Bank model Phi: [[2.1962856e-14 0.0000000e+00 5.8446534e-14 ... 1.5353223e-13
  9.3665264e-10 6.3004477e-11]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 1.4991541e-05
  0.0000000e+00 0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 6.6402963e-06]
 ...
 [9.9996789e-10 0.0000000e+00 0.0000000e+00 ... 2.9371335e-15
  1.0498291e-16 0.0000000e+00]
 [9.9996977e-10 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 0.0000000e+00]
 [9.9997222e-10 0.0000000e+00 0.0000000e+00 ... 2.6537246e-16
  0.0000000e+00 0.0000000e+00]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 1.49941498e-05
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 6.64047548e-06]
 ...
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 4.4622066e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 3.2176899e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  6.6402035e-06 3.7970747e-06]
 ...
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 4.4622066e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 4.4622066e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 4.4622066e-06]].
Bank scores: {'perplexity_score': 11263.4912109375, 'coherence_20': 1.3719767145389439, 'diversity_euclidean': 0.07234430920869539, 'diversity_jensenshannon': 0.6990403593198724, 'diversity_hellinger': 0.8178079641206247, 'diversity_cosine': 0.8202842396546204, 'perplexity': 11263.4912109375, 'ppl_fair': 11263.4912109375, 'ppl_cheatty': 3498.62841796875}
 45%|█████████████████████▏                         | 9/20 [39:01<48:03, 262.16s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).

  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████                        | 1/2 [03:15<03:15, 195.34s/it]Detected bcg topics! Skipping for coherence computation (and will have 20 topics).

100%|█████████████████████████████████████████████████| 2/2 [03:15<00:00, 97.85s/it]
Using absoulte threshold: 2.7242325146624466.
Creating first level with 7 topics. Dictionary: artm.Dictionary(name=7c5c8f34-b670-4348-a275-21f2f47a0094, num_entries=52744).
Copying phi for the first level. Phi shape: (52744, 7). First words: MultiIndex([('@lemmatized',       'willow'),
            ('@lemmatized',        'bodin'),
            ('@lemmatized',     'aneurysm'),
            ('@lemmatized',       'millie'),
            ('@lemmatized',   'paroxysmal'),
            ('@lemmatized', 'intracranial'),
            ('@lemmatized',        'ofthe'),
            ('@lemmatized',      'kneecap'),
            ('@lemmatized',       'alesis'),
            ('@lemmatized',     'libertae')],
           )
Creating second level with 21 topics
Copying phi for the second level. Phi shape: (52744, 21). First words: MultiIndex([('@lemmatized',       'willow'),
            ('@lemmatized',        'bodin'),
            ('@lemmatized',     'aneurysm'),
            ('@lemmatized',       'millie'),
            ('@lemmatized',   'paroxysmal'),
            ('@lemmatized', 'intracranial'),
            ('@lemmatized',        'ofthe'),
            ('@lemmatized',      'kneecap'),
            ('@lemmatized',       'alesis'),
            ('@lemmatized',     'libertae')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic
!!! Bank Phi: [[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 1.49941498e-05
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 6.64047548e-06]
 ...
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]].
!!! Bank model Phi: [[2.1962846e-14 0.0000000e+00 5.8446547e-14 ... 1.5353235e-13
  9.3665276e-10 6.3004456e-11]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 1.4991541e-05
  0.0000000e+00 0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 6.6402963e-06]
 ...
 [9.9996800e-10 0.0000000e+00 0.0000000e+00 ... 2.9371338e-15
  1.0498293e-16 0.0000000e+00]
 [9.9996977e-10 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 0.0000000e+00]
 [9.9997222e-10 0.0000000e+00 0.0000000e+00 ... 2.6537235e-16
  0.0000000e+00 0.0000000e+00]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 1.49941498e-05
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 6.64047548e-06]
 ...
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 4.4622075e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 3.2176904e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  6.6402035e-06 3.7970754e-06]
 ...
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 4.4622070e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 4.4622070e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 4.4622070e-06]].
Bank scores: {'perplexity_score': 11263.4912109375, 'coherence_20': 1.3719767145389439, 'diversity_euclidean': 0.07234430920869243, 'diversity_jensenshannon': 0.699040359320148, 'diversity_hellinger': 0.8178079641205162, 'diversity_cosine': 0.8202842396547031, 'perplexity': 11263.4912109375, 'ppl_fair': 11263.4912109375, 'ppl_cheatty': 3498.628173828125}
 50%|███████████████████████                       | 10/20 [43:24<43:43, 262.36s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).

  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████                        | 1/2 [03:15<03:15, 195.55s/it]Detected bcg topics! Skipping for coherence computation (and will have 20 topics).

100%|█████████████████████████████████████████████████| 2/2 [03:15<00:00, 97.95s/it]
Using absoulte threshold: 2.7242325146624466.
Creating first level with 7 topics. Dictionary: artm.Dictionary(name=7c5c8f34-b670-4348-a275-21f2f47a0094, num_entries=52744).
Copying phi for the first level. Phi shape: (52744, 7). First words: MultiIndex([('@lemmatized',       'willow'),
            ('@lemmatized',        'bodin'),
            ('@lemmatized',     'aneurysm'),
            ('@lemmatized',       'millie'),
            ('@lemmatized',   'paroxysmal'),
            ('@lemmatized', 'intracranial'),
            ('@lemmatized',        'ofthe'),
            ('@lemmatized',      'kneecap'),
            ('@lemmatized',       'alesis'),
            ('@lemmatized',     'libertae')],
           )
Creating second level with 21 topics
Copying phi for the second level. Phi shape: (52744, 21). First words: MultiIndex([('@lemmatized',       'willow'),
            ('@lemmatized',        'bodin'),
            ('@lemmatized',     'aneurysm'),
            ('@lemmatized',       'millie'),
            ('@lemmatized',   'paroxysmal'),
            ('@lemmatized', 'intracranial'),
            ('@lemmatized',        'ofthe'),
            ('@lemmatized',      'kneecap'),
            ('@lemmatized',       'alesis'),
            ('@lemmatized',     'libertae')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic
!!! Bank Phi: [[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 1.49941498e-05
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 6.64047548e-06]
 ...
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]].
!!! Bank model Phi: [[2.1962860e-14 0.0000000e+00 5.8446547e-14 ... 1.5353226e-13
  9.3665276e-10 6.3004456e-11]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 1.4991541e-05
  0.0000000e+00 0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 6.6402963e-06]
 ...
 [9.9996800e-10 0.0000000e+00 0.0000000e+00 ... 2.9371338e-15
  1.0498297e-16 0.0000000e+00]
 [9.9996977e-10 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 0.0000000e+00]
 [9.9997222e-10 0.0000000e+00 0.0000000e+00 ... 2.6537240e-16
  0.0000000e+00 0.0000000e+00]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 1.49941498e-05
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 6.64047548e-06]
 ...
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 4.4622066e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 3.2176899e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  6.6402035e-06 3.7970747e-06]
 ...
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 4.4622066e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 4.4622066e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 4.4622066e-06]].
Bank scores: {'perplexity_score': 11263.4912109375, 'coherence_20': 1.3719767145389439, 'diversity_euclidean': 0.07234430920869245, 'diversity_jensenshannon': 0.6990403593201708, 'diversity_hellinger': 0.8178079641205679, 'diversity_cosine': 0.8202842396547031, 'perplexity': 11263.4912109375, 'ppl_fair': 11263.4912109375, 'ppl_cheatty': 3498.62841796875}
 55%|█████████████████████████▎                    | 11/20 [47:46<39:20, 262.33s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).
Detected bcg topics! Skipping for diversity computation (and now 20 topics).

  0%|                                                         | 0/2 [00:00<?, ?it/s]

In [89]:
1

1

In [57]:
optimizer._main_modality

'@lemmatized'

What topics we have in bank

In [94]:
optimizer._topic_bank.view_topics().head()

                        topic_0  topic_1  topic_2  topic_3   topic_4  topic_5  \
@lemmatized willow          0.0      0.0      0.0      0.0  0.000000      0.0
            bodin           0.0      0.0      0.0      0.0  0.000015      0.0
            aneurysm        0.0      0.0      0.0      0.0  0.000000      0.0
            millie          0.0      0.0      0.0      0.0  0.000000      0.0
            paroxysmal      0.0      0.0      0.0      0.0  0.000000      0.0

                         topic_6  topic_7
@lemmatized willow      0.000000      0.0
            bodin       0.000000      0.0
            aneurysm    0.000007      0.0
            millie      0.000018      0.0
            paroxysmal  0.000007      0.0

In [95]:
bank_topics = optimizer._topic_bank.view_topics()

In [96]:
bank_topics.shape

(52744, 8)

In [97]:
bank_topics.head()

                        topic_0  topic_1  topic_2  topic_3   topic_4  topic_5  \
@lemmatized willow          0.0      0.0      0.0      0.0  0.000000      0.0
            bodin           0.0      0.0      0.0      0.0  0.000015      0.0
            aneurysm        0.0      0.0      0.0      0.0  0.000000      0.0
            millie          0.0      0.0      0.0      0.0  0.000000      0.0
            paroxysmal      0.0      0.0      0.0      0.0  0.000000      0.0

                         topic_6  topic_7
@lemmatized willow      0.000000      0.0
            bodin       0.000000      0.0
            aneurysm    0.000007      0.0
            millie      0.000018      0.0
            paroxysmal  0.000007      0.0

In [104]:
bank_topics['topic_0'].sort_values(ascending=False)[:20]  # TODO: bcg-like

@lemmatized  db        0.031429
             pt        0.016703
             period    0.014349
             la        0.013736
             hit       0.009482
             power     0.008324
             play      0.008176
             pp        0.008104
             bos       0.007402
             mov       0.007126
             van       0.007105
             second    0.006753
             third     0.006456
             bh        0.006379
             min       0.006132
             det       0.005971
             cal       0.005963
             al        0.005903
             pit       0.005642
             first     0.005605
Name: topic_0, dtype: float64

In [103]:
bank_topics['topic_5'].sort_values(ascending=False)[:20]  # TODO: bcg-like

@lemmatized  go        0.022738
             say       0.021706
             one       0.013934
             come      0.012467
             know      0.009830
             get       0.009252
             take      0.008439
             tell      0.008243
             start     0.007976
             year      0.007179
             u         0.007055
             people    0.006801
             day       0.006776
             time      0.006632
             back      0.006428
             happen    0.006145
             leave     0.006062
             see       0.005937
             home      0.005923
             hit       0.005790
Name: topic_5, dtype: float64

And topic scores

In [107]:
bank_topics['topic_6'].sort_values(ascending=False)[:20]  # TODO: bcg-like (типа общего "фонового" абзаца, который есть во многих письмах)

@lemmatized  get       0.022655
             go        0.017787
             good      0.012914
             think     0.011078
             car       0.010986
             like      0.010905
             time      0.010537
             one       0.010172
             well      0.009536
             year      0.009035
             take      0.009028
             back      0.007318
             much      0.007172
             see       0.006931
             really    0.006620
             run       0.006475
             even      0.006210
             thing     0.006190
             look      0.006186
             make      0.006077
Name: topic_6, dtype: float64

In [108]:
bank_topics['topic_7'].sort_values(ascending=False)[:20]

@lemmatized  window         0.016274
             file           0.015884
             use            0.015518
             image          0.010950
             program        0.010810
             available      0.007733
             version        0.007595
             ftp            0.006977
             server         0.006973
             display        0.006798
             application    0.006329
             graphic        0.006263
             edu            0.006021
             run            0.005993
             widget         0.005906
             set            0.005507
             get            0.005480
             software       0.005282
             also           0.005168
             color          0.005142
Name: topic_7, dtype: float64

In [109]:
optimizer._topic_bank.view_topic_scores()  # TODO: background topic in bank (but its Newman's score in lower)

,topic_0,topic_1,topic_2,topic_3,topic_4,topic_5,topic_6,topic_7
kernel_size,2385.000000,3711.000000,3163.000000,4126.000000,2271.000000,2806.000000,2807.000000,3503.000000
toplen_ptw,2.765323,2.867601,2.948222,2.767973,3.330389,2.948513,4.151473,2.938516
coherence_20,1.858091,1.321134,1.755432,2.237800,1.022701,0.786218,0.622462,1.281036
distance_to_nearest,0.965321,0.794300,0.905060,0.850112,0.853044,0.668319,0.651415,0.814150

All models are also saved (topics as $\Phi$ matrices and topic score values)

In [110]:
! ls $optimizer._topic_bank._path

model_0__phi.bin	    model_19__topic_scores.bin
model_0__topic_scores.bin   model_1__phi.bin
model_10__phi.bin	    model_1__topic_scores.bin
model_10__topic_scores.bin  model_2__phi.bin
model_11__phi.bin	    model_2__topic_scores.bin
model_11__topic_scores.bin  model_3__phi.bin
model_12__phi.bin	    model_3__topic_scores.bin
model_12__topic_scores.bin  model_4__phi.bin
model_13__phi.bin	    model_4__topic_scores.bin
model_13__topic_scores.bin  model_5__phi.bin
model_14__phi.bin	    model_5__topic_scores.bin
model_14__topic_scores.bin  model_6__phi.bin
model_15__phi.bin	    model_6__topic_scores.bin
model_15__topic_scores.bin  model_7__phi.bin
model_16__phi.bin	    model_7__topic_scores.bin
model_16__topic_scores.bin  model_8__phi.bin
model_17__phi.bin	    model_8__topic_scores.bin
model_17__topic_scores.bin  model_9__phi.bin
model_18__phi.bin	    model_9__topic_scores.bin
model_18__topic_scores.bin  topics.bin
model_19__phi.bin	    topic_scores.bin

In [111]:
optimizer._result.keys()

dict_keys(['optimum', 'optimum_std', 'bank_scores', 'bank_topic_scores', 'model_scores', 'model_topic_scores', 'num_bank_topics', 'num_model_topics'])

In [112]:
len(optimizer._result['num_bank_topics'])

20

In [113]:
optimizer._result['num_bank_topics']

[4, 4, 5, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8]

In [114]:
len(optimizer._result['bank_topic_scores'])

20

In [73]:
1

1

In [72]:
optimizer._result

{'optimum': 3,
 'optimum_std': 10.0,
 'bank_scores': [{'perplexity_score': 121752.9921875,
   'coherence_20': 0.6237645959171805,
   'diversity_euclidean': nan,
   'diversity_jensenshannon': nan,
   'diversity_hellinger': nan,
   'diversity_cosine': nan,
   'perplexity': 121752.9921875,
   'ppl_fair': 121752.9921875,
   'ppl_cheatty': 4886.2919921875},
  {'perplexity_score': 38073.5078125,
   'coherence_20': 1.1540840587363426,
   'diversity_euclidean': 0.08476227429474838,
   'diversity_jensenshannon': 0.7291129947578447,
   'diversity_hellinger': 0.8495427002760296,
   'diversity_cosine': 0.8837066171867015,
   'perplexity': 38073.5078125,
   'ppl_fair': 38073.5078125,
   'ppl_cheatty': 4272.0791015625},
  {'perplexity_score': 38073.5078125,
   'coherence_20': 1.1540840587363426,
   'diversity_euclidean': 0.08476227429476624,
   'diversity_jensenshannon': 0.7291129947581968,
   'diversity_hellinger': 0.8495427002760009,
   'diversity_cosine': 0.8837066171867277,
   'perplexity': 38073.5078125,
   'ppl_fair': 38073.5078125,
   'ppl_cheatty': 4272.0791015625},
  {'perplexity_score': 38073.5078125,
   'coherence_20': 1.1540840587363426,
   'diversity_euclidean': 0.08476227429474832,
   'diversity_jensenshannon': 0.7291129947577569,
   'diversity_hellinger': 0.849542700275982,
   'diversity_cosine': 0.8837066171867001,
   'perplexity': 38073.5078125,
   'ppl_fair': 38073.5078125,
   'ppl_cheatty': 4272.0791015625},
  {'perplexity_score': 38073.5078125,
   'coherence_20': 1.1540840587363426,
   'diversity_euclidean': 0.08476227429476624,
   'diversity_jensenshannon': 0.7291129947582452,
   'diversity_hellinger': 0.8495427002761341,
   'diversity_cosine': 0.8837066171867277,
   'perplexity': 38073.5078125,
   'ppl_fair': 38073.5078125,
   'ppl_cheatty': 4272.0791015625},
  {'perplexity_score': 38073.5078125,
   'coherence_20': 1.1540840587363426,
   'diversity_euclidean': 0.08476227429476624,
   'diversity_jensenshannon': 0.7291129947581596,
   'diversity_hellinger': 0.8495427002759642,
   'diversity_cosine': 0.8837066171867277,
   'perplexity': 38073.5078125,
   'ppl_fair': 38073.5078125,
   'ppl_cheatty': 4272.0791015625},
  {'perplexity_score': 38073.5078125,
   'coherence_20': 1.1540840587363426,
   'diversity_euclidean': 0.0847622742947662,
   'diversity_jensenshannon': 0.7291129947581894,
   'diversity_hellinger': 0.8495427002757099,
   'diversity_cosine': 0.8837066171867276,
   'perplexity': 38073.5078125,
   'ppl_fair': 38073.5078125,
   'ppl_cheatty': 4272.0791015625},
  {'perplexity_score': 38073.5078125,
   'coherence_20': 1.1540840587363426,
   'diversity_euclidean': 0.0847622742947483,
   'diversity_jensenshannon': 0.7291129947577065,
   'diversity_hellinger': 0.8495427002757513,
   'diversity_cosine': 0.8837066171867,
   'perplexity': 38073.5078125,
   'ppl_fair': 38073.5078125,
   'ppl_cheatty': 4272.0791015625},
  {'perplexity_score': 38073.5078125,
   'coherence_20': 1.1540840587363426,
   'diversity_euclidean': 0.0847622742947662,
   'diversity_jensenshannon': 0.7291129947582197,
   'diversity_hellinger': 0.849542700275881,
   'diversity_cosine': 0.8837066171867276,
   'perplexity': 38073.5078125,
   'ppl_fair': 38073.5078125,
   'ppl_cheatty': 4272.07958984375},
  {'perplexity_score': 38073.5078125,
   'coherence_20': 1.1540840587363426,
   'diversity_euclidean': 0.08476227429476624,
   'diversity_jensenshannon': 0.7291129947581635,
   'diversity_hellinger': 0.8495427002760652,
   'diversity_cosine': 0.8837066171867277,
   'perplexity': 38073.5078125,
   'ppl_fair': 38073.5078125,
   'ppl_cheatty': 4272.0791015625},
  {'perplexity_score': 38073.5078125,
   'coherence_20': 1.1540840587363426,
   'diversity_euclidean': 0.08476227429476624,
   'diversity_jensenshannon': 0.7291129947581906,
   'diversity_hellinger': 0.849542700276032,
   'diversity_cosine': 0.8837066171867277,
   'perplexity': 38073.5078125,
   'ppl_fair': 38073.5078125,
   'ppl_cheatty': 4272.0791015625},
  {'perplexity_score': 38073.5078125,
   'coherence_20': 1.1540840587363426,
   'diversity_euclidean': 0.0847622742947483,
   'diversity_jensenshannon': 0.7291129947577834,
   'diversity_hellinger': 0.8495427002758761,
   'diversity_cosine': 0.8837066171867001,
   'perplexity': 38073.5078125,
   'ppl_fair': 38073.5078125,
   'ppl_cheatty': 4272.0791015625},
  {'perplexity_score': 38073.5078125,
   'coherence_20': 1.1540840587363426,
   'diversity_euclidean': 0.08476227429475053,
   'diversity_jensenshannon': 0.7291129947588564,
   'diversity_hellinger': 0.8495427002766652,
   'diversity_cosine': 0.8837066171868567,
   'perplexity': 38073.5078125,
   'ppl_fair': 38073.5078125,
   'ppl_cheatty': 4272.0791015625},
  {'perplexity_score': 38073.5078125,
   'coherence_20': 1.1540840587363426,
   'diversity_euclidean': 0.0847622742947662,
   'diversity_jensenshannon': 0.7291129947581206,
   'diversity_hellinger': 0.8495427002756624,
   'diversity_cosine': 0.8837066171867276,
   'perplexity': 38073.5078125,
   'ppl_fair': 38073.5078125,
   'ppl_cheatty': 4272.0791015625},
  {'perplexity_score': 38073.5078125,
   'coherence_20': 1.1540840587363426,
   'diversity_euclidean': 0.08476227429476624,
   'diversity_jensenshannon': 0.7291129947582614,
   'diversity_hellinger': 0.8495427002760673,
   'diversity_cosine': 0.8837066171867277,
   'perplexity': 38073.5078125,
   'ppl_fair': 38073.5078125,
   'ppl_cheatty': 4272.0791015625},
  {'perplexity_score': 38073.5078125,
   'coherence_20': 1.1540840587363426,
   'diversity_euclidean': 0.08476227429475053,
   'diversity_jensenshannon': 0.7291129947589243,
   'diversity_hellinger': 0.8495427002766643,
   'diversity_cosine': 0.8837066171868567,
   'perplexity': 38073.5078125,
   'ppl_fair': 38073.5078125,
   'ppl_cheatty': 4272.0791015625},
  {'perplexity_score': 38073.5078125,
   'coherence_20': 1.1540840587363426,
   'diversity_euclidean': 0.08476227429476624,
   'diversity_jensenshannon': 0.7291129947582848,
   'diversity_hellinger': 0.8495427002760642,
   'diversity_cosine': 0.8837066171867277,
   'perplexity': 38073.5078125,
   'ppl_fair': 38073.5078125,
   'ppl_cheatty': 4272.0791015625},
  {'perplexity_score': 38073.5078125,
   'coherence_20': 1.1540840587363426,
   'diversity_euclidean': 0.0847622742947483,
   'diversity_jensenshannon': 0.729112994757663,
   'diversity_hellinger': 0.8495427002757978,
   'diversity_cosine': 0.8837066171867,
   'perplexity': 38073.5078125,
   'ppl_fair': 38073.5078125,
   'ppl_cheatty': 4272.0791015625},
  {'perplexity_score': 38073.5078125,
   'coherence_20': 1.1540840587363426,
   'diversity_euclidean': 0.08476227429474818,
   'diversity_jensenshannon': 0.7291129947576039,
   'diversity_hellinger': 0.8495427002761139,
   'diversity_cosine': 0.8837066171866943,
   'perplexity': 38073.5078125,
   'ppl_fair': 38073.5078125,
   'ppl_cheatty': 4272.0791015625},
  {'perplexity_score': 38073.5078125,
   'coherence_20': 1.1540840587363426,
   'diversity_euclidean': 0.0847622742947662,
   'diversity_jensenshannon': 0.7291129947581124,
   'diversity_hellinger': 0.8495427002757646,
   'diversity_cosine': 0.8837066171867276,
   'perplexity': 38073.5078125,
   'ppl_fair': 38073.5078125,
   'ppl_cheatty': 4272.0791015625}],
 'bank_topic_scores': [[{'kernel_size': 2094,
    'toplen_ptw': 5.780027821875345,
    'coherence_20': 0.6237645959171805,
    'distance_to_nearest': 0.0}],
  [{'kernel_size': 2094,
    'toplen_ptw': 5.780027821875345,
    'coherence_20': 0.6237645959171805,
    'distance_to_nearest': 0.0},
   {'kernel_size': 2288,
    'toplen_ptw': 3.454019090863184,
    'coherence_20': 1.0259572038511215,
    'distance_to_nearest': 0.9011804164897276},
   {'kernel_size': 3070,
    'toplen_ptw': 3.2837521217785497,
    'coherence_20': 1.8125303764407255,
    'distance_to_nearest': 0.933041429026246}],
  [{'kernel_size': 2094,
    'toplen_ptw': 5.780027821875345,
    'coherence_20': 0.6237645959171805,
    'distance_to_nearest': 0.0},
   {'kernel_size': 2288,
    'toplen_ptw': 3.454019090863184,
    'coherence_20': 1.0259572038511215,
    'distance_to_nearest': 0.9011804164897276},
   {'kernel_size': 3070,
    'toplen_ptw': 3.2837521217785497,
    'coherence_20': 1.8125303764407255,
    'distance_to_nearest': 0.933041429026246}],
  [{'kernel_size': 2094,
    'toplen_ptw': 5.780027821875345,
    'coherence_20': 0.6237645959171805,
    'distance_to_nearest': 0.0},
   {'kernel_size': 2288,
    'toplen_ptw': 3.454019090863184,
    'coherence_20': 1.0259572038511215,
    'distance_to_nearest': 0.9011804164897276},
   {'kernel_size': 3070,
    'toplen_ptw': 3.2837521217785497,
    'coherence_20': 1.8125303764407255,
    'distance_to_nearest': 0.933041429026246}],
  [{'kernel_size': 2094,
    'toplen_ptw': 5.780027821875345,
    'coherence_20': 0.6237645959171805,
    'distance_to_nearest': 0.0},
   {'kernel_size': 2288,
    'toplen_ptw': 3.454019090863184,
    'coherence_20': 1.0259572038511215,
    'distance_to_nearest': 0.9011804164897276},
   {'kernel_size': 3070,
    'toplen_ptw': 3.2837521217785497,
    'coherence_20': 1.8125303764407255,
    'distance_to_nearest': 0.933041429026246}],
  [{'kernel_size': 2094,
    'toplen_ptw': 5.780027821875345,
    'coherence_20': 0.6237645959171805,
    'distance_to_nearest': 0.0},
   {'kernel_size': 2288,
    'toplen_ptw': 3.454019090863184,
    'coherence_20': 1.0259572038511215,
    'distance_to_nearest': 0.9011804164897276},
   {'kernel_size': 3070,
    'toplen_ptw': 3.2837521217785497,
    'coherence_20': 1.8125303764407255,
    'distance_to_nearest': 0.933041429026246}],
  [{'kernel_size': 2094,
    'toplen_ptw': 5.780027821875345,
    'coherence_20': 0.6237645959171805,
    'distance_to_nearest': 0.0},
   {'kernel_size': 2288,
    'toplen_ptw': 3.454019090863184,
    'coherence_20': 1.0259572038511215,
    'distance_to_nearest': 0.9011804164897276},
   {'kernel_size': 3070,
    'toplen_ptw': 3.2837521217785497,
    'coherence_20': 1.8125303764407255,
    'distance_to_nearest': 0.933041429026246}],
  [{'kernel_size': 2094,
    'toplen_ptw': 5.780027821875345,
    'coherence_20': 0.6237645959171805,
    'distance_to_nearest': 0.0},
   {'kernel_size': 2288,
    'toplen_ptw': 3.454019090863184,
    'coherence_20': 1.0259572038511215,
    'distance_to_nearest': 0.9011804164897276},
   {'kernel_size': 3070,
    'toplen_ptw': 3.2837521217785497,
    'coherence_20': 1.8125303764407255,
    'distance_to_nearest': 0.933041429026246}],
  [{'kernel_size': 2094,
    'toplen_ptw': 5.780027821875345,
    'coherence_20': 0.6237645959171805,
    'distance_to_nearest': 0.0},
   {'kernel_size': 2288,
    'toplen_ptw': 3.454019090863184,
    'coherence_20': 1.0259572038511215,
    'distance_to_nearest': 0.9011804164897276},
   {'kernel_size': 3070,
    'toplen_ptw': 3.2837521217785497,
    'coherence_20': 1.8125303764407255,
    'distance_to_nearest': 0.933041429026246}],
  [{'kernel_size': 2094,
    'toplen_ptw': 5.780027821875345,
    'coherence_20': 0.6237645959171805,
    'distance_to_nearest': 0.0},
   {'kernel_size': 2288,
    'toplen_ptw': 3.454019090863184,
    'coherence_20': 1.0259572038511215,
    'distance_to_nearest': 0.9011804164897276},
   {'kernel_size': 3070,
    'toplen_ptw': 3.2837521217785497,
    'coherence_20': 1.8125303764407255,
    'distance_to_nearest': 0.933041429026246}],
  [{'kernel_size': 2094,
    'toplen_ptw': 5.780027821875345,
    'coherence_20': 0.6237645959171805,
    'distance_to_nearest': 0.0},
   {'kernel_size': 2288,
    'toplen_ptw': 3.454019090863184,
    'coherence_20': 1.0259572038511215,
    'distance_to_nearest': 0.9011804164897276},
   {'kernel_size': 3070,
    'toplen_ptw': 3.2837521217785497,
    'coherence_20': 1.8125303764407255,
    'distance_to_nearest': 0.933041429026246}],
  [{'kernel_size': 2094,
    'toplen_ptw': 5.780027821875345,
    'coherence_20': 0.6237645959171805,
    'distance_to_nearest': 0.0},
   {'kernel_size': 2288,
    'toplen_ptw': 3.454019090863184,
    'coherence_20': 1.0259572038511215,
    'distance_to_nearest': 0.9011804164897276},
   {'kernel_size': 3070,
    'toplen_ptw': 3.2837521217785497,
    'coherence_20': 1.8125303764407255,
    'distance_to_nearest': 0.933041429026246}],
  [{'kernel_size': 2094,
    'toplen_ptw': 5.780027821875345,
    'coherence_20': 0.6237645959171805,
    'distance_to_nearest': 0.0},
   {'kernel_size': 2288,
    'toplen_ptw': 3.454019090863184,
    'coherence_20': 1.0259572038511215,
    'distance_to_nearest': 0.9011804164897276},
   {'kernel_size': 3070,
    'toplen_ptw': 3.2837521217785497,
    'coherence_20': 1.8125303764407255,
    'distance_to_nearest': 0.933041429026246}],
  [{'kernel_size': 2094,
    'toplen_ptw': 5.780027821875345,
    'coherence_20': 0.6237645959171805,
    'distance_to_nearest': 0.0},
   {'kernel_size': 2288,
    'toplen_ptw': 3.454019090863184,
    'coherence_20': 1.0259572038511215,
    'distance_to_nearest': 0.9011804164897276},
   {'kernel_size': 3070,
    'toplen_ptw': 3.2837521217785497,
    'coherence_20': 1.8125303764407255,
    'distance_to_nearest': 0.933041429026246}],
  [{'kernel_size': 2094,
    'toplen_ptw': 5.780027821875345,
    'coherence_20': 0.6237645959171805,
    'distance_to_nearest': 0.0},
   {'kernel_size': 2288,
    'toplen_ptw': 3.454019090863184,
    'coherence_20': 1.0259572038511215,
    'distance_to_nearest': 0.9011804164897276},
   {'kernel_size': 3070,
    'toplen_ptw': 3.2837521217785497,
    'coherence_20': 1.8125303764407255,
    'distance_to_nearest': 0.933041429026246}],
  [{'kernel_size': 2094,
    'toplen_ptw': 5.780027821875345,
    'coherence_20': 0.6237645959171805,
    'distance_to_nearest': 0.0},
   {'kernel_size': 2288,
    'toplen_ptw': 3.454019090863184,
    'coherence_20': 1.0259572038511215,
    'distance_to_nearest': 0.9011804164897276},
   {'kernel_size': 3070,
    'toplen_ptw': 3.2837521217785497,
    'coherence_20': 1.8125303764407255,
    'distance_to_nearest': 0.933041429026246}],
  [{'kernel_size': 2094,
    'toplen_ptw': 5.780027821875345,
    'coherence_20': 0.6237645959171805,
    'distance_to_nearest': 0.0},
   {'kernel_size': 2288,
    'toplen_ptw': 3.454019090863184,
    'coherence_20': 1.0259572038511215,
    'distance_to_nearest': 0.9011804164897276},
   {'kernel_size': 3070,
    'toplen_ptw': 3.2837521217785497,
    'coherence_20': 1.8125303764407255,
    'distance_to_nearest': 0.933041429026246}],
  [{'kernel_size': 2094,
    'toplen_ptw': 5.780027821875345,
    'coherence_20': 0.6237645959171805,
    'distance_to_nearest': 0.0},
   {'kernel_size': 2288,
    'toplen_ptw': 3.454019090863184,
    'coherence_20': 1.0259572038511215,
    'distance_to_nearest': 0.9011804164897276},
   {'kernel_size': 3070,
    'toplen_ptw': 3.2837521217785497,
    'coherence_20': 1.8125303764407255,
    'distance_to_nearest': 0.933041429026246}],
  [{'kernel_size': 2094,
    'toplen_ptw': 5.780027821875345,
    'coherence_20': 0.6237645959171805,
    'distance_to_nearest': 0.0},
   {'kernel_size': 2288,
    'toplen_ptw': 3.454019090863184,
    'coherence_20': 1.0259572038511215,
    'distance_to_nearest': 0.9011804164897276},
   {'kernel_size': 3070,
    'toplen_ptw': 3.2837521217785497,
    'coherence_20': 1.8125303764407255,
    'distance_to_nearest': 0.933041429026246}],
  [{'kernel_size': 2094,
    'toplen_ptw': 5.780027821875345,
    'coherence_20': 0.6237645959171805,
    'distance_to_nearest': 0.0},
   {'kernel_size': 2288,
    'toplen_ptw': 3.454019090863184,
    'coherence_20': 1.0259572038511215,
    'distance_to_nearest': 0.9011804164897276},
   {'kernel_size': 3070,
    'toplen_ptw': 3.2837521217785497,
    'coherence_20': 1.8125303764407255,
    'distance_to_nearest': 0.933041429026246}]],
 'model_scores': [{'perplexity_score': 2236.7939453125,
   'coherence_20': 1.4186014117067525,
   'diversity_euclidean': 0.0694170676177584,
   'diversity_jensenshannon': 0.6988120155173883,
   'diversity_hellinger': 0.8168113732509762,
   'diversity_cosine': 0.830776187490429,
   'perplexity': 2236.7939453125,
   'toplen_ptw': 2.2428102331033792},
  {'perplexity_score': 2242.626953125,
   'coherence_20': 1.3905626455280915,
   'diversity_euclidean': 0.06675183480260802,
   'diversity_jensenshannon': 0.694907627330372,
   'diversity_hellinger': 0.8114778857005891,
   'diversity_cosine': 0.8170634573149258,
   'perplexity': 2242.626953125,
   'toplen_ptw': 2.2064072090139097},
  {'perplexity_score': 2200.653076171875,
   'coherence_20': 1.4270198489690797,
   'diversity_euclidean': 0.06751942604835513,
   'diversity_jensenshannon': 0.6904592650773428,
   'diversity_hellinger': 0.8058820266066014,
   'diversity_cosine': 0.8181786720869507,
   'perplexity': 2200.653076171875,
   'toplen_ptw': 2.4036182756825384},
  {'perplexity_score': 2245.269287109375,
   'coherence_20': 1.2660138915915904,
   'diversity_euclidean': 0.06482438703013739,
   'diversity_jensenshannon': 0.6903800908814957,
   'diversity_hellinger': 0.8063132110999701,
   'diversity_cosine': 0.8039133059832373,
   'perplexity': 2245.269287109375,
   'toplen_ptw': 2.324590761714104},
  {'perplexity_score': 2275.25,
   'coherence_20': 1.3597500547979653,
   'diversity_euclidean': 0.06556118320200834,
   'diversity_jensenshannon': 0.689424660631407,
   'diversity_hellinger': 0.8049771005317994,
   'diversity_cosine': 0.7992339101670722,
   'perplexity': 2275.25,
   'toplen_ptw': 2.1766896262641082},
  {'perplexity_score': 2229.324951171875,
   'coherence_20': 1.2453819589817474,
   'diversity_euclidean': 0.06576473147410858,
   'diversity_jensenshannon': 0.6867712892949984,
   'diversity_hellinger': 0.8012168378732674,
   'diversity_cosine': 0.8016107600625796,
   'perplexity': 2229.324951171875,
   'toplen_ptw': 2.2905799843239385},
  {'perplexity_score': 2237.661376953125,
   'coherence_20': 1.49946069620671,
   'diversity_euclidean': 0.06871791047200743,
   'diversity_jensenshannon': 0.6924754785398749,
   'diversity_hellinger': 0.8087258230269586,
   'diversity_cosine': 0.8211802765472076,
   'perplexity': 2237.661376953125,
   'toplen_ptw': 2.2880525095511484},
  {'perplexity_score': 2250.6630859375,
   'coherence_20': 1.3251132005708592,
   'diversity_euclidean': 0.06630322729052766,
   'diversity_jensenshannon': 0.6914353750643452,
   'diversity_hellinger': 0.8075575547934816,
   'diversity_cosine': 0.8112608299524329,
   'perplexity': 2250.6630859375,
   'toplen_ptw': 2.205654719915217},
  {'perplexity_score': 2255.335205078125,
   'coherence_20': 1.3949366243626748,
   'diversity_euclidean': 0.06922358237527423,
   'diversity_jensenshannon': 0.6842852459159862,
   'diversity_hellinger': 0.7979253680774898,
   'diversity_cosine': 0.8115982683983374,
   'perplexity': 2255.335205078125,
   'toplen_ptw': 2.2478351900122373},
  {'perplexity_score': 2262.2431640625,
   'coherence_20': 1.3965175049930192,
   'diversity_euclidean': 0.06660763308941305,
   'diversity_jensenshannon': 0.6936900585263401,
   'diversity_hellinger': 0.8109075987193912,
   'diversity_cosine': 0.823301167387804,
   'perplexity': 2262.2431640625,
   'toplen_ptw': 2.076218802319672},
  {'perplexity_score': 2224.421875,
   'coherence_20': 1.2318741574754462,
   'diversity_euclidean': 0.0687277582164743,
   'diversity_jensenshannon': 0.6904328945256879,
   'diversity_hellinger': 0.8055264424937999,
   'diversity_cosine': 0.8149765106530201,
   'perplexity': 2224.421875,
   'toplen_ptw': 2.2493434747351486},
  {'perplexity_score': 2262.1875,
   'coherence_20': 1.3674064044001586,
   'diversity_euclidean': 0.06596539819824336,
   'diversity_jensenshannon': 0.6966296300817248,
   'diversity_hellinger': 0.8146153007313494,
   'diversity_cosine': 0.8174383474072138,
   'perplexity': 2262.1875,
   'toplen_ptw': 2.298105799943232},
  {'perplexity_score': 2275.450927734375,
   'coherence_20': 1.3168409994753072,
   'diversity_euclidean': 0.06744338644058828,
   'diversity_jensenshannon': 0.6968785641053167,
   'diversity_hellinger': 0.8138236189981242,
   'diversity_cosine': 0.8262166811651217,
   'perplexity': 2275.450927734375,

In [299]:
optimizer._result['bank_topic_scores']

[[{'kernel_size': 3019,
   'coherence_20': 1.1491291917105928,
   'distance_to_nearest': 0.0},
  {'kernel_size': 4131,
   'coherence_20': 1.5517711527505458,
   'distance_to_nearest': 0.9012677929970639},
  {'kernel_size': 3712,
   'coherence_20': 1.405924126520918,
   'distance_to_nearest': 0.8186488736472473},
  {'kernel_size': 3833,
   'coherence_20': 1.0506564618250258,
   'distance_to_nearest': 0.8774752086950317},
  {'kernel_size': 3332,
   'coherence_20': 1.1270220165324627,
   'distance_to_nearest': 0.8769032208946992},
  {'kernel_size': 3171,
   'coherence_20': 1.5564847213025248,
   'distance_to_nearest': 0.8285869353518943},
  {'kernel_size': 3013,
   'coherence_20': 1.3764434481297354,
   'distance_to_nearest': 0.8604233537632775},
  {'kernel_size': 3469,
   'coherence_20': 0.9760657812912945,
   'distance_to_nearest': 0.8090433428976028},
  {'kernel_size': 3119,
   'coherence_20': 0.7385423660674926,
   'distance_to_nearest': 0.8300004886500197},
  {'kernel_size': 4038,
   'coherence_20': 1.840761298075488,
   'distance_to_nearest': 0.8170905216863902},
  {'kernel_size': 4339,
   'coherence_20': 1.330514926154629,
   'distance_to_nearest': 0.8128412106621422},
  {'kernel_size': 2423,
   'coherence_20': 1.7073209789137267,
   'distance_to_nearest': 0.8367010948232775},
  {'kernel_size': 2385,
   'coherence_20': 1.8580910947101374,
   'distance_to_nearest': 0.9581306806634664},
  {'kernel_size': 3711,
   'coherence_20': 1.3211340090044137,
   'distance_to_nearest': 0.7705584209005232},
  {'kernel_size': 3832,
   'coherence_20': 1.4857567187040455,
   'distance_to_nearest': 0.8605028553117803},
  {'kernel_size': 4053,
   'coherence_20': 2.0158025400053132,
   'distance_to_nearest': 0.8516365074866467},
  {'kernel_size': 4162,
   'coherence_20': 2.636592011876535,
   'distance_to_nearest': 0.8305899410313415},
  {'kernel_size': 3163,
   'coherence_20': 1.7554318141499257,
   'distance_to_nearest': 0.8911253286453286},
  {'kernel_size': 2025,
   'coherence_20': 1.4312786968925868,
   'distance_to_nearest': 0.8158041536443097}],
 [{'kernel_size': 3019,
   'coherence_20': 1.1491291917105928,
   'distance_to_nearest': 0.0},
  {'kernel_size': 4131,
   'coherence_20': 1.5517711527505458,
   'distance_to_nearest': 0.9012677929970639},
  {'kernel_size': 3712,
   'coherence_20': 1.405924126520918,
   'distance_to_nearest': 0.8186488736472473},
  {'kernel_size': 3833,
   'coherence_20': 1.0506564618250258,
   'distance_to_nearest': 0.8774752086950317},
  {'kernel_size': 3332,
   'coherence_20': 1.1270220165324627,
   'distance_to_nearest': 0.8769032208946992},
  {'kernel_size': 3171,
   'coherence_20': 1.5564847213025248,
   'distance_to_nearest': 0.8285869353518943},
  {'kernel_size': 3013,
   'coherence_20': 1.3764434481297354,
   'distance_to_nearest': 0.8604233537632775},
  {'kernel_size': 3469,
   'coherence_20': 0.9760657812912945,
   'distance_to_nearest': 0.8090433428976028},
  {'kernel_size': 3119,
   'coherence_20': 0.7385423660674926,
   'distance_to_nearest': 0.8300004886500197},
  {'kernel_size': 4038,
   'coherence_20': 1.840761298075488,
   'distance_to_nearest': 0.8170905216863902},
  {'kernel_size': 4339,
   'coherence_20': 1.330514926154629,
   'distance_to_nearest': 0.8128412106621422},
  {'kernel_size': 2423,
   'coherence_20': 1.7073209789137267,
   'distance_to_nearest': 0.8367010948232775},
  {'kernel_size': 2385,
   'coherence_20': 1.8580910947101374,
   'distance_to_nearest': 0.9581306806634664},
  {'kernel_size': 3711,
   'coherence_20': 1.3211340090044137,
   'distance_to_nearest': 0.7705584209005232},
  {'kernel_size': 3832,
   'coherence_20': 1.4857567187040455,
   'distance_to_nearest': 0.8605028553117803},
  {'kernel_size': 4053,
   'coherence_20': 2.0158025400053132,
   'distance_to_nearest': 0.8516365074866467},
  {'kernel_size': 4162,
   'coherence_20': 2.636592011876535,
   'distance_to_nearest': 0.8305899410313415},
  {'kernel_size': 3163,
   'coherence_20': 1.7554318141499257,
   'distance_to_nearest': 0.8911253286453286},
  {'kernel_size': 2025,
   'coherence_20': 1.4312786968925868,
   'distance_to_nearest': 0.8158041536443097}],
 [{'kernel_size': 3019,
   'coherence_20': 1.1491291917105928,
   'distance_to_nearest': 0.0},
  {'kernel_size': 4131,
   'coherence_20': 1.5517711527505458,
   'distance_to_nearest': 0.9012677929970639},
  {'kernel_size': 3712,
   'coherence_20': 1.405924126520918,
   'distance_to_nearest': 0.8186488736472473},
  {'kernel_size': 3833,
   'coherence_20': 1.0506564618250258,
   'distance_to_nearest': 0.8774752086950317},
  {'kernel_size': 3332,
   'coherence_20': 1.1270220165324627,
   'distance_to_nearest': 0.8769032208946992},
  {'kernel_size': 3171,
   'coherence_20': 1.5564847213025248,
   'distance_to_nearest': 0.8285869353518943},
  {'kernel_size': 3013,
   'coherence_20': 1.3764434481297354,
   'distance_to_nearest': 0.8604233537632775},
  {'kernel_size': 3469,
   'coherence_20': 0.9760657812912945,
   'distance_to_nearest': 0.8090433428976028},
  {'kernel_size': 3119,
   'coherence_20': 0.7385423660674926,
   'distance_to_nearest': 0.8300004886500197},
  {'kernel_size': 4038,
   'coherence_20': 1.840761298075488,
   'distance_to_nearest': 0.8170905216863902},
  {'kernel_size': 4339,
   'coherence_20': 1.330514926154629,
   'distance_to_nearest': 0.8128412106621422},
  {'kernel_size': 2423,
   'coherence_20': 1.7073209789137267,
   'distance_to_nearest': 0.8367010948232775},
  {'kernel_size': 2385,
   'coherence_20': 1.8580910947101374,
   'distance_to_nearest': 0.9581306806634664},
  {'kernel_size': 3711,
   'coherence_20': 1.3211340090044137,
   'distance_to_nearest': 0.7705584209005232},
  {'kernel_size': 3832,
   'coherence_20': 1.4857567187040455,
   'distance_to_nearest': 0.8605028553117803},
  {'kernel_size': 4053,
   'coherence_20': 2.0158025400053132,
   'distance_to_nearest': 0.8516365074866467},
  {'kernel_size': 4162,
   'coherence_20': 2.636592011876535,
   'distance_to_nearest': 0.8305899410313415},
  {'kernel_size': 3163,
   'coherence_20': 1.7554318141499257,
   'distance_to_nearest': 0.8911253286453286},
  {'kernel_size': 2025,
   'coherence_20': 1.4312786968925868,
   'distance_to_nearest': 0.8158041536443097}],
 [{'kernel_size': 3019,
   'coherence_20': 1.1491291917105928,
   'distance_to_nearest': 0.0},
  {'kernel_size': 4131,
   'coherence_20': 1.5517711527505458,
   'distance_to_nearest': 0.9012677929970639},
  {'kernel_size': 3712,
   'coherence_20': 1.405924126520918,
   'distance_to_nearest': 0.8186488736472473},
  {'kernel_size': 3833,
   'coherence_20': 1.0506564618250258,
   'distance_to_nearest': 0.8774752086950317},
  {'kernel_size': 3332,
   'coherence_20': 1.1270220165324627,
   'distance_to_nearest': 0.8769032208946992},
  {'kernel_size': 3171,
   'coherence_20': 1.5564847213025248,
   'distance_to_nearest': 0.8285869353518943},
  {'kernel_size': 3013,
   'coherence_20': 1.3764434481297354,
   'distance_to_nearest': 0.8604233537632775},
  {'kernel_size': 3469,
   'coherence_20': 0.9760657812912945,
   'distance_to_nearest': 0.8090433428976028},
  {'kernel_size': 3119,
   'coherence_20': 0.7385423660674926,
   'distance_to_nearest': 0.8300004886500197},
  {'kernel_size': 4038,
   'coherence_20': 1.840761298075488,
   'distance_to_nearest': 0.8170905216863902},
  {'kernel_size': 4339,
   'coherence_20': 1.330514926154629,
   'distance_to_nearest': 0.8128412106621422},
  {'kernel_size': 2423,
   'coherence_20': 1.7073209789137267,
   'distance_to_nearest': 0.8367010948232775},
  {'kernel_size': 2385,
   'coherence_20': 1.8580910947101374,
   'distance_to_nearest': 0.9581306806634664},
  {'kernel_size': 3711,
   'coherence_20': 1.3211340090044137,
   'distance_to_nearest': 0.7705584209005232},
  {'kernel_size': 3832,
   'coherence_20': 1.4857567187040455,
   'distance_to_nearest': 0.8605028553117803},
  {'kernel_size': 4053,
   'coherence_20': 2.0158025400053132,
   'distance_to_nearest': 0.8516365074866467},
  {'kernel_size': 4162,
   'coherence_20': 2.636592011876535,
   'distance_to_nearest': 0.8305899410313415},
  {'kernel_size': 3163,
   'coherence_20': 1.7554318141499257,
   'distance_to_nearest': 0.8911253286453286},
  {'kernel_size': 2025,
   'coherence_20': 1.4312786968925868,
   'distance_to_nearest': 0.8158041536443097}],
 [{'kernel_size': 3019,
   'coherence_20': 1.1491291917105928,
   'distance_to_nearest': 0.0},
  {'kernel_size': 4131,
   'coherence_20': 1.5517711527505458,
   'distance_to_nearest': 0.9012677929970639},
  {'kernel_size': 3712,
   'coherence_20': 1.405924126520918,
   'distance_to_nearest': 0.8186488736472473},
  {'kernel_size': 3833,
   'coherence_20': 1.0506564618250258,
   'distance_to_nearest': 0.8774752086950317},
  {'kernel_size': 3332,
   'coherence_20': 1.1270220165324627,
   'distance_to_nearest': 0.8769032208946992},
  {'kernel_size': 3171,
   'coherence_20': 1.5564847213025248,
   'distance_to_nearest': 0.8285869353518943},
  {'kernel_size': 3013,
   'coherence_20': 1.3764434481297354,
   'distance_to_nearest': 0.8604233537632775},
  {'kernel_size': 3469,
   'coherence_20': 0.9760657812912945,
   'distance_to_nearest': 0.8090433428976028},
  {'kernel_size': 3119,
   'coherence_20': 0.7385423660674926,
   'distance_to_nearest': 0.8300004886500197},
  {'kernel_size': 4038,
   'coherence_20': 1.840761298075488,
   'distance_to_nearest': 0.8170905216863902},
  {'kernel_size': 4339,
   'coherence_20': 1.330514926154629,
   'distance_to_nearest': 0.8128412106621422},
  {'kernel_size': 2423,
   'coherence_20': 1.7073209789137267,
   'distance_to_nearest': 0.8367010948232775},
  {'kernel_size': 2385,
   'coherence_20': 1.8580910947101374,
   'distance_to_nearest': 0.9581306806634664},
  {'kernel_size': 3711,
   'coherence_20': 1.3211340090044137,
   'distance_to_nearest': 0.7705584209005232},
  {'kernel_size': 3832,
   'coherence_20': 1.4857567187040455,
   'distance_to_nearest': 0.8605028553117803},
  {'kernel_size': 4053,
   'coherence_20': 2.0158025400053132,
   'distance_to_nearest': 0.8516365074866467},
  {'kernel_size': 4162,
   'coherence_20': 2.636592011876535,
   'distance_to_nearest': 0.8305899410313415},
  {'kernel_size': 3163,
   'coherence_20': 1.7554318141499257,
   'distance_to_nearest': 0.8911253286453286},
  {'kernel_size': 2025,
   'coherence_20': 1.4312786968925868,
   'distance_to_nearest': 0.8158041536443097}],
 [{'kernel_size': 3019,
   'coherence_20': 1.1491291917105928,
   'distance_to_nearest': 0.0},
  {'kernel_size': 4131,
   'coherence_20': 1.5517711527505458,
   'distance_to_nearest': 0.9012677929970639},
  {'kernel_size': 3712,
   'coherence_20': 1.405924126520918,
   'distance_to_nearest': 0.8186488736472473},
  {'kernel_size': 3833,
   'coherence_20': 1.0506564618250258,
   'distance_to_nearest': 0.8774752086950317},
  {'kernel_size': 3332,
   'coherence_20': 1.1270220165324627,
   'distance_to_nearest': 0.8769032208946992},
  {'kernel_size': 3171,
   'coherence_20': 1.5564847213025248,
   'distance_to_nearest': 0.8285869353518943},
  {'kernel_size': 3013,
   'coherence_20': 1.3764434481297354,
   'distance_to_nearest': 0.8604233537632775},
  {'kernel_size': 3469,
   'coherence_20': 0.9760657812912945,
   'distance_to_nearest': 0.8090433428976028},
  {'kernel_size': 3119,
   'coherence_20': 0.7385423660674926,
   'distance_to_nearest': 0.8300004886500197},
  {'kernel_size': 4038,
   'coherence_20': 1.840761298075488,
   'distance_to_nearest': 0.8170905216863902},
  {'kernel_size': 4339,
   'coherence_20': 1.330514926154629,
   'distance_to_nearest': 0.8128412106621422},
  {'kernel_size': 2423,
   'coherence_20': 1.7073209789137267,
   'distance_to_nearest': 0.8367010948232775},
  {'kernel_size': 2385,
   'coherence_20': 1.8580910947101374,
   'distance_to_nearest': 0.9581306806634664},
  {'kernel_size': 3711,
   'coherence_20': 1.3211340090044137,
   'distance_to_nearest': 0.7705584209005232},
  {'kernel_size': 3832,
   'coherence_20': 1.4857567187040455,
   'distance_to_nearest': 0.8605028553117803},
  {'kernel_size': 4053,
   'coherence_20': 2.0158025400053132,
   'distance_to_nearest': 0.8516365074866467},
  {'kernel_size': 4162,
   'coherence_20': 2.636592011876535,
   'distance_to_nearest': 0.8305899410313415},
  {'kernel_size': 3163,
   'coherence_20': 1.7554318141499257,
   'distance_to_nearest': 0.8911253286453286},
  {'kernel_size': 2025,
   'coherence_20': 1.4312786968925868,
   'distance_to_nearest': 0.8158041536443097}],
 [{'kernel_size': 3019,
   'coherence_20': 1.1491291917105928,
   'distance_to_nearest': 0.0},
  {'kernel_size': 4131,
   'coherence_20': 1.5517711527505458,
   'distance_to_nearest': 0.9012677929970639},
  {'kernel_size': 3712,
   'coherence_20': 1.405924126520918,
   'distance_to_nearest': 0.8186488736472473},
  {'kernel_size': 3833,
   'coherence_20': 1.0506564618250258,
   'distance_to_nearest': 0.8774752086950317},
  {'kernel_size': 3332,
   'coherence_20': 1.1270220165324627,
   'distance_to_nearest': 0.8769032208946992},
  {'kernel_size': 3171,
   'coherence_20': 1.5564847213025248,
   'distance_to_nearest': 0.8285869353518943},
  {'kernel_size': 3013,
   'coherence_20': 1.3764434481297354,
   'distance_to_nearest': 0.8604233537632775},
  {'kernel_size': 3469,
   'coherence_20': 0.9760657812912945,
   'distance_to_nearest': 0.8090433428976028},
  {'kernel_size': 3119,
   'coherence_20': 0.7385423660674926,
   'distance_to_nearest': 0.8300004886500197},
  {'kernel_size': 4038,
   'coherence_20': 1.840761298075488,
   'distance_to_nearest': 0.8170905216863902},
  {'kernel_size': 4339,
   'coherence_20': 1.330514926154629,
   'distance_to_nearest': 0.8128412106621422},
  {'kernel_size': 2385,
   'coherence_20': 1.8580910947101374,
   'distance_to_nearest': 0.9581306806634664},
  {'kernel_size': 3711,
   'coherence_20': 1.3211340090044137,
   'distance_to_nearest': 0.7705584209005232},
  {'kernel_size': 3832,
   'coherence_20': 1.4857567187040455,
   'distance_to_nearest': 0.8605028553117803},
  {'kernel_size': 4053,
   'coherence_20': 2.0158025400053132,
   'distance_to_nearest': 0.8516365074866467},
  {'kernel_size': 4162,
   'coherence_20': 2.636592011876535,
   'distance_to_nearest': 0.8305899410313415},
  {'kernel_size': 3163,
   'coherence_20': 1.7554318141499257,
   'distance_to_nearest': 0.8911253286453286},
  {'kernel_size': 2025,
   'coherence_20': 1.4312786968925868,
   'distance_to_nearest': 0.8158041536443097},
  {'kernel_size': 2472,
   'coherence_20': 2.145491929149199,
   'distance_to_nearest': 0.5898065778437495}],
 [{'kernel_size': 3019,
   'coherence_20': 1.1491291917105928,
   'distance_to_nearest': 0.0},
  {'kernel_size': 4131,
   'coherence_20': 1.5517711527505458,
   'distance_to_nearest': 0.9012677929970639},
  {'kernel_size': 3712,
   'coherence_20': 1.405924126520918,
   'distance_to_nearest': 0.8186488736472473},
  {'kernel_size': 3833,
   'coherence_20': 1.0506564618250258,
   'distance_to_nearest': 0.8774752086950317},
  {'kernel_size': 3332,
   'coherence_20': 1.1270220165324627,
   'distance_to_nearest': 0.8769032208946992},
  {'kernel_size': 3171,
   'coherence_20': 1.5564847213025248,
   'distance_to_nearest': 0.8285869353518943},
  {'kernel_size': 3013,
   'coherence_20': 1.3764434481297354,
   'distance_to_nearest': 0.8604233537632775},
  {'kernel_size': 3469,
   'coherence_20': 0.9760657812912945,
   'distance_to_nearest': 0.8090433428976028},
  {'kernel_size': 3119,
   'coherence_20': 0.7385423660674926,
   'distance_to_nearest': 0.8300004886500197},
  {'kernel_size': 4038,
   'coherence_20': 1.840761298075488,
   'distance_to_nearest': 0.8170905216863902},
  {'kernel_size': 4339,
   'coherence_20': 1.330514926154629,
   'distance_to_nearest': 0.8128412106621422},
  {'kernel_size': 2385,
   'coherence_20': 1.8580910947101374,
   'distance_to_nearest': 0.9581306806634664},
  {'kernel_size': 3711,
   'coherence_20': 1.3211340090044137,
   'distance_to_nearest': 0.7705584209005232},
  {'kernel_size': 3832,
   'coherence_20': 1.4857567187040455,
   'distance_to_nearest': 0.8605028553117803},
  {'kernel_size': 4053,
   'coherence_20': 2.0158025400053132,
   'distance_to_nearest': 0.8516365074866467},
  {'kernel_size': 4162,
   'coherence_20': 2.636592011876535,
   'distance_to_nearest': 0.8305899410313415},
  {'kernel_size': 3163,
   'coherence_20': 1.7554318141499257,
   'distance_to_nearest': 0.8911253286453286},
  {'kernel_size': 2025,
   'coherence_20': 1.4312786968925868,
   'distance_to_nearest': 0.8158041536443097},
  {'kernel_size': 2472,
   'coherence_20': 2.145491929149199,
   'distance_to_nearest': 0.5898065778437495}],
 [{'kernel_size': 3019,
   'coherence_20': 1.1491291917105928,
   'distance_to_nearest': 0.0},
  {'kernel_size': 4131,
   'coherence_20': 1.5517711527505458,
   'distance_to_nearest': 0.9012677929970639},
  {'kernel_size': 3833,
   'coherence_20': 1.0506564618250258,
   'distance_to_nearest': 0.8774752086950317},
  {'kernel_size': 3332,
   'coherence_20': 1.1270220165324627,
   'distance_to_nearest': 0.8769032208946992},
  {'kernel_size': 3171,
   'coherence_20': 1.5564847213025248,
   'distance_to_nearest': 0.8285869353518943},
  {'kernel_size': 3013,
   'coherence_20': 1.3764434481297354,
   'distance_to_nearest': 0.8604233537632775},
  {'kernel_size': 3469,
   'coherence_20': 0.9760657812912945,
   'distance_to_nearest': 0.8090433428976028},
  {'kernel_size': 3119,
   'coherence_20': 0.7385423660674926,
   'distance_to_nearest': 0.8300004886500197},
  {'kernel_size': 4038,
   'coherence_20': 1.840761298075488,
   'distance_to_nearest': 0.8170905216863902},
  {'kernel_size': 4339,
   'coherence_20': 1.330514926154629,
   'distance_to_nearest': 0.8128412106621422},
  {'kernel_size': 2385,
   'coherence_20': 1.8580910947101374,
   'distance_to_nearest': 0.9581306806634664},
  {'kernel_size': 3711,
   'coherence_20': 1.3211340090044137,
   'distance_to_nearest': 0.7705584209005232},
  {'kernel_size': 3832,
   'coherence_20': 1.4857567187040455,
   'distance_to_nearest': 0.8605028553117803},
  {'kernel_size': 4053,
   'coherence_20': 2.0158025400053132,
   'distance_to_nearest': 0.8516365074866467},
  {'kernel_size': 4162,
   'coherence_20': 2.636592011876535,
   'distance_to_nearest': 0.8305899410313415},
  {'kernel_size': 3163,
   'coherence_20': 1.7554318141499257,
   'distance_to_nearest': 0.8911253286453286},
  {'kernel_size': 2025,
   'coherence_20': 1.4312786968925868,
   'distance_to_nearest': 0.8158041536443097},
  {'kernel_size': 2472,
   'coherence_20': 2.145491929149199,
   'distance_to_nearest': 0.5898065778437495},
  {'kernel_size': 3185,
   'coherence_20': 1.645622315864888,
   'distance_to_nearest': 0.5872697762398518}],
 [{'kernel_size': 3019,
   'coherence_20': 1.1491291917105928,
   'distance_to_nearest': 0.0},
  {'kernel_size': 4131,
   'coherence_20': 1.5517711527505458,
   'distance_to_nearest': 0.9012677929970639},
  {'kernel_size': 3833,
   'coherence_20': 1.0506564618250258,
   'distance_to_nearest': 0.8774752086950317},
  {'kernel_size': 3332,
   'coherence_20': 1.1270220165324627,
   'distance_to_nearest': 0.8769032208946992},
  {'kernel_size': 3171,
   'coherence_20': 1.5564847213025248,
   'distance_to_nearest': 0.8285869353518943},
  {'kernel_size': 3013,
   'coherence_20': 1.3764434481297354,
   'distance_to_nearest': 0.8604233537632775},
  {'kernel_size': 3469,
   'coherence_20': 0.9760657812912945,
   'distance_to_nearest': 0.8090433428976028},
  {'kernel_size': 3119,
   'coherence_20': 0.7385423660674926,
   'distance_to_nearest': 0.8300004886500197},
  {'kernel_size': 4038,
   'coherence_20': 1.840761298075488,
   'distance_to_nearest': 0.8170905216863902},
  {'kernel_size': 4339,
   'coherence_20': 1.330514926154629,
   'distance_to_nearest': 0.8128412106621422},
  {'kernel_size': 2385,
   'coherence_20': 1.8580910947101374,
   'distance_to_nearest': 0.9581306806634664},
  {'kernel_size': 3711,
   'coherence_20': 1.3211340090044137,
   'distance_to_nearest': 0.7705584209005232},
  {'kernel_size': 3832,

In [300]:
optimizer._result['model_scores'][0]

{'perplexity_score': 2236.79248046875,
 'coherence_20': 1.4186014117067525,
 'diversity_euclidean': 0.06941780342829489,
 'diversity_jensenshannon': 0.6988145688602007,
 'diversity_hellinger': 0.8168150964236229,
 'diversity_cosine': 0.8307823697793519,
 'perplexity': 2236.79248046875}

In [301]:
sum(s['coherence_20'] for s in optimizer._result['bank_topic_scores'][-1]) / 20

1.7406289526201006

In [302]:
len(optimizer._result['bank_scores'])

20

In [303]:
optimizer._result['bank_scores'][-1]

{'perplexity_score': 3493.57763671875,
 'coherence_20': 1.7406289526201009,
 'diversity_euclidean': 0.07031903413950691,
 'diversity_jensenshannon': 0.7133993431150941,
 'diversity_hellinger': 0.8377069027035076,
 'diversity_cosine': 0.8598855331795965,
 'perplexity': 3493.57763671875,
 'ppl_fair': 3493.57763671875,
 'ppl_cheatty': 2539.317626953125}

In [304]:
optimizer._result['model_topic_scores']

[[{'kernel_size': 3019,
   'coherence_20': 1.1491291917105928,
   'distance_to_nearest': 0.0},
  {'kernel_size': 4131,
   'coherence_20': 1.5517711527505458,
   'distance_to_nearest': 0.9012677929970639},
  {'kernel_size': 3712,
   'coherence_20': 1.405924126520918,
   'distance_to_nearest': 0.8186488736472473},
  {'kernel_size': 3833,
   'coherence_20': 1.0506564618250258,
   'distance_to_nearest': 0.8774752086950317},
  {'kernel_size': 3332,
   'coherence_20': 1.1270220165324627,
   'distance_to_nearest': 0.8769032208946992},
  {'kernel_size': 3171,
   'coherence_20': 1.5564847213025248,
   'distance_to_nearest': 0.8285869353518943},
  {'kernel_size': 3013,
   'coherence_20': 1.3764434481297354,
   'distance_to_nearest': 0.8604233537632775},
  {'kernel_size': 3469,
   'coherence_20': 0.9760657812912945,
   'distance_to_nearest': 0.8090433428976028},
  {'kernel_size': 2094, 'coherence_20': 0.6237645959171805},
  {'kernel_size': 3119,
   'coherence_20': 0.7385423660674926,
   'distance_to_nearest': 0.8300004886500197},
  {'kernel_size': 4038,
   'coherence_20': 1.840761298075488,
   'distance_to_nearest': 0.8170905216863902},
  {'kernel_size': 4339,
   'coherence_20': 1.330514926154629,
   'distance_to_nearest': 0.8128412106621422},
  {'kernel_size': 2423,
   'coherence_20': 1.7073209789137267,
   'distance_to_nearest': 0.8367010948232775},
  {'kernel_size': 2385,
   'coherence_20': 1.8580910947101374,
   'distance_to_nearest': 0.9581306806634664},
  {'kernel_size': 3711,
   'coherence_20': 1.3211340090044137,
   'distance_to_nearest': 0.7705584209005232},
  {'kernel_size': 3832,
   'coherence_20': 1.4857567187040455,
   'distance_to_nearest': 0.8605028553117803},
  {'kernel_size': 4053,
   'coherence_20': 2.0158025400053132,
   'distance_to_nearest': 0.8516365074866467},
  {'kernel_size': 4162,
   'coherence_20': 2.636592011876535,
   'distance_to_nearest': 0.8305899410313415},
  {'kernel_size': 3163,
   'coherence_20': 1.7554318141499257,
   'distance_to_nearest': 0.8911253286453286},
  {'kernel_size': 2025,
   'coherence_20': 1.4312786968925868,
   'distance_to_nearest': 0.8158041536443097}],
 [{'kernel_size': 2506, 'coherence_20': 0.627826313051237},
  {'kernel_size': 3556, 'coherence_20': 1.389634016860818},
  {'kernel_size': 3937, 'coherence_20': 1.3843245458988291},
  {'kernel_size': 2929, 'coherence_20': 0.5464347524707991},
  {'kernel_size': 3268, 'coherence_20': 0.9120466670643614},
  {'kernel_size': 3475, 'coherence_20': 1.5089708234652888},
  {'kernel_size': 3239, 'coherence_20': 1.4116384677400873},
  {'kernel_size': 3283, 'coherence_20': 0.8574816035124672},
  {'kernel_size': 3662, 'coherence_20': 1.0897279378324427},
  {'kernel_size': 3198, 'coherence_20': 1.8032848505598649},
  {'kernel_size': 2288, 'coherence_20': 1.0259572038511215},
  {'kernel_size': 3098, 'coherence_20': 3.6148133798456175},
  {'kernel_size': 3070, 'coherence_20': 1.8125303764407255},
  {'kernel_size': 3358, 'coherence_20': 1.391491274195365},
  {'kernel_size': 3539, 'coherence_20': 1.40933005124635},
  {'kernel_size': 3323, 'coherence_20': 0.9372769123188911},
  {'kernel_size': 4371, 'coherence_20': 1.6070764582212957},
  {'kernel_size': 4290, 'coherence_20': 2.2133516704858605},
  {'kernel_size': 3937, 'coherence_20': 2.3337578327353596},
  {'kernel_size': 2993, 'coherence_20': 0.7146943248510973}],
 [{'kernel_size': 3154, 'coherence_20': 1.7300523146588405},
  {'kernel_size': 3787, 'coherence_20': 1.0553448061529902},
  {'kernel_size': 3418, 'coherence_20': 1.9563085816159047},
  {'kernel_size': 4318, 'coherence_20': 1.6460933884449667},
  {'kernel_size': 2896, 'coherence_20': 1.4161646131279229},
  {'kernel_size': 3273, 'coherence_20': 1.2796741260477416},
  {'kernel_size': 3768, 'coherence_20': 1.4898214631509419},
  {'kernel_size': 2662, 'coherence_20': 1.327655227966092},
  {'kernel_size': 4126, 'coherence_20': 2.237799559639728},
  {'kernel_size': 3202, 'coherence_20': 1.1205686168189006},
  {'kernel_size': 2476, 'coherence_20': 1.9824795351569895},
  {'kernel_size': 3739, 'coherence_20': 2.159035393982212},
  {'kernel_size': 3234, 'coherence_20': 0.9101295556236955},
  {'kernel_size': 3367, 'coherence_20': 0.6963804548739299},
  {'kernel_size': 3894, 'coherence_20': 1.4378750848102366},
  {'kernel_size': 2764, 'coherence_20': 0.6903762780733693},
  {'kernel_size': 3656, 'coherence_20': 2.8450990542764627},
  {'kernel_size': 2689, 'coherence_20': 0.659707632196525},
  {'kernel_size': 3498, 'coherence_20': 1.4997770737445035},
  {'kernel_size': 2896, 'coherence_20': 1.0952870420698153}],
 [{'kernel_size': 3375, 'coherence_20': 0.6960019693909996},
  {'kernel_size': 3328, 'coherence_20': 0.9826551487133159},
  {'kernel_size': 4761, 'coherence_20': 2.6932639343318043},
  {'kernel_size': 3266, 'coherence_20': 1.0603381812985166},
  {'kernel_size': 3152, 'coherence_20': 0.8306608817402165},
  {'kernel_size': 2954, 'coherence_20': 0.6428858120695048},
  {'kernel_size': 3815, 'coherence_20': 1.3628911465676905},
  {'kernel_size': 2494, 'coherence_20': 1.1609517143822183},
  {'kernel_size': 3194, 'coherence_20': 0.8646018092687187},
  {'kernel_size': 2271, 'coherence_20': 1.0227011076551349},
  {'kernel_size': 3364, 'coherence_20': 1.319538103287363},
  {'kernel_size': 3584, 'coherence_20': 1.1936097285581133},
  {'kernel_size': 3390, 'coherence_20': 2.0187664268637837},
  {'kernel_size': 4860, 'coherence_20': 2.1836615240564687},
  {'kernel_size': 2795, 'coherence_20': 1.212489679895818},
  {'kernel_size': 3482, 'coherence_20': 1.4775612117653296},
  {'kernel_size': 3114, 'coherence_20': 1.7224649042385982},
  {'kernel_size': 3386, 'coherence_20': 1.4961358648505396},
  {'kernel_size': 3230, 'coherence_20': 1.3263102296350275},
  {'kernel_size': 3297, 'coherence_20': 1.7760545504883896}],
 [{'kernel_size': 3862, 'coherence_20': 1.43239021790752},
  {'kernel_size': 3991, 'coherence_20': 1.0313114942828805},
  {'kernel_size': 4753, 'coherence_20': 1.953560204687862},
  {'kernel_size': 3598, 'coherence_20': 1.340293870536816},
  {'kernel_size': 2757, 'coherence_20': 0.7413375459664112},
  {'kernel_size': 3867, 'coherence_20': 1.423906750186859},
  {'kernel_size': 2892, 'coherence_20': 1.3149631405634445},
  {'kernel_size': 3245, 'coherence_20': 1.1632733914307363},
  {'kernel_size': 2777, 'coherence_20': 0.8146373023220627},
  {'kernel_size': 3206, 'coherence_20': 1.5876322245680003},
  {'kernel_size': 3921, 'coherence_20': 1.345827841473774},
  {'kernel_size': 4302, 'coherence_20': 1.510447688987818},
  {'kernel_size': 2459, 'coherence_20': 1.443247757745759},
  {'kernel_size': 3479, 'coherence_20': 0.897384377807739},
  {'kernel_size': 3730, 'coherence_20': 1.5714966573530043},
  {'kernel_size': 2392, 'coherence_20': 0.8405572502429983},
  {'kernel_size': 3360, 'coherence_20': 1.562273635871329},
  {'kernel_size': 3468, 'coherence_20': 1.9989662967002841},
  {'kernel_size': 2405, 'coherence_20': 0.7058298633435319},
  {'kernel_size': 3523, 'coherence_20': 1.3736722681221567}],
 [{'kernel_size': 3738, 'coherence_20': 1.1656607746842447},
  {'kernel_size': 3024, 'coherence_20': 1.32510314327925},
  {'kernel_size': 2199, 'coherence_20': 0.6414513261579781},
  {'kernel_size': 2822, 'coherence_20': 1.0290966926062803},
  {'kernel_size': 3584, 'coherence_20': 1.5295482079058156},
  {'kernel_size': 3064, 'coherence_20': 1.9493615911221043},
  {'kernel_size': 3891, 'coherence_20': 1.1113136715040774},
  {'kernel_size': 2902, 'coherence_20': 1.1132748883664612},
  {'kernel_size': 2861, 'coherence_20': 1.3954178196358995},
  {'kernel_size': 3390, 'coherence_20': 1.6510414251845873},
  {'kernel_size': 4465, 'coherence_20': 2.2693575602353886},
  {'kernel_size': 3516, 'coherence_20': 1.3657704954053274},
  {'kernel_size': 2198, 'coherence_20': 1.127634205061124},
  {'kernel_size': 3309, 'coherence_20': 0.8317919074352915},
  {'kernel_size': 3199, 'coherence_20': 1.0502597856331937},
  {'kernel_size': 3688, 'coherence_20': 1.793817385024687},
  {'kernel_size': 3402, 'coherence_20': 1.482383947188184},
  {'kernel_size': 3849, 'coherence_20': 0.8357715228717826},
  {'kernel_size': 3403, 'coherence_20': 0.9030790350542243},
  {'kernel_size': 3649, 'coherence_20': 1.5704194681079167}],
 [{'kernel_size': 3520, 'coherence_20': 1.50278552756288},
  {'kernel_size': 3923, 'coherence_20': 1.754539249582399},
  {'kernel_size': 2752, 'coherence_20': 1.4961358648505398},
  {'kernel_size': 3179, 'coherence_20': 0.9467428379847904},
  {'kernel_size': 2305, 'coherence_20': 1.0937993599028726},
  {'kernel_size': 3732, 'coherence_20': 1.1972046416589337},
  {'kernel_size': 3751, 'coherence_20': 2.7374520272921847},
  {'kernel_size': 2871, 'coherence_20': 1.2737566416917816},
  {'kernel_size': 3298, 'coherence_20': 1.2213352114171192},
  {'kernel_size': 2907, 'coherence_20': 1.6365561527950867},
  {'kernel_size': 2675, 'coherence_20': 0.6318088871373784},
  {'kernel_size': 2472,
   'coherence_20': 2.145491929149199,
   'distance_to_nearest': 0.5898065778437495},
  {'kernel_size': 2900, 'coherence_20': 1.0023656247767023},
  {'kernel_size': 3380, 'coherence_20': 0.9439213179317059},
  {'kernel_size': 3870, 'coherence_20': 1.6895609557337958},
  {'kernel_size': 2807, 'coherence_20': 0.7862175457217373},
  {'kernel_size': 4067, 'coherence_20': 1.6775856206326083},
  {'kernel_size': 4017, 'coherence_20': 1.5932852232908272},
  {'kernel_size': 5164, 'coherence_20': 2.4302751265277256},
  {'kernel_size': 3785, 'coherence_20': 1.5541687560273822}],
 [{'kernel_size': 3276, 'coherence_20': 1.1778174740319045},
  {'kernel_size': 3750, 'coherence_20': 1.6566040531511643},
  {'kernel_size': 3622, 'coherence_20': 0.900681084864304},
  {'kernel_size': 2256, 'coherence_20': 2.3072600451975833},
  {'kernel_size': 3663, 'coherence_20': 1.6505477920621505},
  {'kernel_size': 2543, 'coherence_20': 0.9838737391828195},
  {'kernel_size': 3705, 'coherence_20': 1.454750276467569},
  {'kernel_size': 3974, 'coherence_20': 1.5205557130303942},
  {'kernel_size': 3878, 'coherence_20': 0.9409128592418319},
  {'kernel_size': 2807, 'coherence_20': 0.6224618708915302},
  {'kernel_size': 3699, 'coherence_20': 1.6758297058902554},
  {'kernel_size': 3607, 'coherence_20': 2.084731150914494},
  {'kernel_size': 4117, 'coherence_20': 1.314672825366162},
  {'kernel_size': 2771, 'coherence_20': 0.6973515127800067},
  {'kernel_size': 3510, 'coherence_20': 1.3355535757755566},
  {'kernel_size': 3646, 'coherence_20': 1.5730387256620628},
  {'kernel_size': 3477, 'coherence_20': 1.2330813353427472},
  {'kernel_size': 2492, 'coherence_20': 0.8833613634791034},
  {'kernel_size': 2907, 'coherence_20': 1.5157304154726292},
  {'kernel_size': 3147, 'coherence_20': 1.232343159883914}],
 [{'kernel_size': 3452, 'coherence_20': 1.423382998939199},
  {'kernel_size': 3617, 'coherence_20': 1.0041396783710501},
  {'kernel_size': 4020, 'coherence_20': 1.7008978108592452},
  {'kernel_size': 2814, 'coherence_20': 0.661524079598271},
  {'kernel_size': 2592, 'coherence_20': 1.0401263528311282},
  {'kernel_size': 4693, 'coherence_20': 1.7613407887162003},
  {'kernel_size': 3203, 'coherence_20': 1.1185600139934697},
  {'kernel_size': 3480, 'coherence_20': 1.3664902497861506},
  {'kernel_size': 2966, 'coherence_20': 0.6791196814510065},
  {'kernel_size': 4155, 'coherence_20': 1.998064081741149},
  {'kernel_size': 3458, 'coherence_20': 0.9960692118622646},
  {'kernel_size': 3148, 'coherence_20': 1.1741369795320236},
  {'kernel_size': 3234, 'coherence_20': 1.8244653655226042},
  {'kernel_size': 2578, 'coherence_20': 2.0576364406301355},
  {'kernel_size': 2630, 'coherence_20': 0.637514365325148},
  {'kernel_size': 3290, 'coherence_20': 1.0485252952285227},
  {'kernel_size': 3185,
   'coherence_20': 1.645622315864888,
   'distance_to_nearest': 0.5872697762398518},
  {'kernel_size': 4565, 'coherence_20': 1.5890853512940628},
  {'kernel_size': 3400, 'coherence_20': 1.5726445344130426},
  {'kernel_size': 2996, 'coherence_20': 1.4435059404827657}],
 [{'kernel_size': 3208, 'coherence_20': 1.5435470385104475},
  {'kernel_size': 2982, 'coherence_20': 2.8002293215915417},
  {'kernel_size': 4337, 'coherence_20': 1.4582412463672703},
  {'kernel_size': 2710, 'coherence_20': 0.6179433310337522},
  {'kernel_size': 3194, 'coherence_20': 1.2491306448981692},
  {'kernel_size': 3138, 'coherence_20': 0.9478995084976264},
  {'kernel_size': 2426, 'coherence_20': 1.022410370024671},
  {'kernel_size': 3289, 'coherence_20': 1.0578669023294713},
  {'kernel_size': 2480, 'coherence_20': 1.878396846423442},
  {'kernel_size': 4233, 'coherence_20': 1.1961865248666212},
  {'kernel_size': 4223, 'coherence_20': 2.095936989943411},
  {'kernel_size': 3153, 'coherence_20': 1.0788982834352272},
  {'kernel_size': 3931, 'coherence_20': 1.8752903953474893},
  {'kernel_size': 3765, 'coherence_20': 1.3549729588720636},
  {'kernel_size': 3792, 'coherence_20': 2.173903418416384},
  {'kernel_size': 3423, 'coherence_20': 0.9972794077718389},
  {'kernel_size': 3327, 'coherence_20': 0.7981902120868334},
  {'kernel_size': 3364, 'coherence_20': 1.4380620511139746},
  {'kernel_size': 3386, 'coherence_20': 1.5782952670871626},
  {'kernel_size': 3957, 'coherence_20': 2.1236812475824602}],
 [{'kernel_size': 3133, 'coherence_20': 0.964872250777415},
  {'kernel_size': 3821, 'coherence_20': 2.8176495218534057},
  {'kernel_size': 4149, 'coherence_20': 1.4349205927175597},
  {'kernel_size': 3827, 'coherence_20': 1.0695235557385931},
  {'kernel_size': 4214, 'coherence_20': 2.0406094852353944},
  {'kernel_size': 2690, 'coherence_20': 1.8906823663679817},
  {'kernel_size': 3686, 'coherence_20': 1.3857474338748121},
  {'kernel_size': 2877, 'coherence_20': 0.6747570022104338},
  {'kernel_size': 3551, 'coherence_20': 1.4929160901149807},
  {'kernel_size': 3872, 'coherence_20': 1.1479853288487383},
  {'kernel_size': 3497, 'coherence_20': 1.1846360701609882},
  {'kernel_size': 3082, 'coherence_20': 1.1815384553617887},
  {'kernel_size': 2899, 'coherence_20': 0.807217579495253},
  {'kernel_size': 2732, 'coherence_20': 0.6305364333953664},
  {'kernel_size': 3154, 'coherence_20': 1.2982381778362677},
  {'kernel_size': 2648, 'coherence_20': 0.9994497445632275},
  {'kernel_size': 3819, 'coherence_20': 1.480917203942235},
  {'kernel_size': 3715, 'coherence_20': 1.2791122447899042},
  {'kernel_size': 3628, 'coherence_20': 0.9370333368800818},
  {'kernel_size': 3330, 'coherence_20': 1.7944922551814504}],
 [{'kernel_size': 2868, 'coherence_20': 1.2870856559806614},
  {'kernel_size': 3200, 'coherence_20': 1.3207183694670193},
  {'kernel_size': 3230, 'coherence_20': 0.8935378330144694},
  {'kernel_size': 2776, 'coherence_20': 1.3717125386540037},
  {'kernel_size': 4102, 'coherence_20': 1.4835477118696752},
  {'kernel_size': 3678, 'coherence_20': 0.8021899442517477},
  {'kernel_size': 2836, 'coherence_20': 0.5924018438240173},
  {'kernel_size': 4245, 'coherence_20': 2.0928912261242654},
  {'kernel_size': 3065,
   'coherence_20': 4.460776582752002,
   'distance_to_nearest': 0.8923792805276536},
  {'kernel_size': 2999, 'coherence_20': 1.0409971966992044},
  {'kernel_size': 3401, 'coherence_20': 1.534823089716246},
  {'kernel_size': 4184, 'coherence_20': 1.8406259366563278},
  {'kernel_size': 3663, 'coherence_20': 0.9289433464493734},
  {'kernel_size': 3524, 'coherence_20': 1.428455545826921},
  {'kernel_size': 2715, 'coherence_20': 0.9658106236696685},
  {'kernel_size': 2878, 'coherence_20': 1.1698224195957678},
  {'kernel_size': 4225, 'coherence_20': 1.3631002701463135},
  {'kernel_size': 4509, 'coherence_20': 1.8529328918693466},
  {'kernel_size': 3468, 'coherence_20': 1.4522358909214026},
  {'kernel_size': 2946, 'coherence_20': 1.976617214093152}],
 [{'kernel_size': 2718, 'coherence_20': 0.724210328261052},
  {'kernel_size': 4236, 'coherence_20': 1.4334479970563692},
  {'kernel_size': 3056, 'coherence_20': 0.7569550077718493},
  {'kernel_size': 2537, 'coherence_20': 1.0246047547185213},
  {'kernel_size': 4159, 'coherence_20': 1.571245981526027},
  {'kernel_size': 3193, 'coherence_20': 1.849459903147076},
  {'kernel_size': 3712, 'coherence_20': 1.2045838445507508},
  {'kernel_size': 4675, 'coherence_20': 1.4929863283535054},
  {'kernel_size': 3882, 'coherence_20': 1.3637262991626382},
  {'kernel_size': 3520, 'coherence_20': 0.7592497658436266},
  {'kernel_size': 2223, 'coherence_20': 0.6419071504528081},
  {'kernel_size': 3032, 'coherence_20': 1.4941589951129692},
  {'kernel_size': 3351, 'coherence_20': 1.3002609165675614},
  {'kernel_size': 2824, 'coherence_20': 1.1828369624783277},
  {'kernel_size': 3861, 'coherence_20': 2.3240257393235084},
  {'kernel_size': 3297, 'coherence_20': 1.5518893499525677},
  {'kernel_size': 3641, 'coherence_20': 1.093518387889452},
  {'kernel_size': 3475, 'coherence_20': 1.5724834620681805},
  {'kernel_size': 3614, 'coherence_20': 1.333421082383053},
  {'kernel_size': 3549, 'coherence_20': 1.254864778504165}],
 [{'kernel_size': 3352, 'coherence_20': 1.2534718087106265},
  {'kernel_size': 2924, 'coherence_20': 1.2702038832317397},
  {'kernel_size': 3090, 'coherence_20': 0.8225339537041465},
  {'kernel_size': 3894, 'coherence_20': 2.491060408074605},
  {'kernel_size': 2269, 'coherence_20': 0.9797640512437862},
  {'kernel_size': 2626, 'coherence_20': 0.6126933439516055},
  {'kernel_size': 3249, 'coherence_20': 1.039686442249457},
  {'kernel_size': 3424, 'coherence_20': 0.9206754359612956},
  {'kernel_size': 3728,
   'coherence_20': 1.5129065552986278,
   'distance_to_nearest': 0.7653279228400567},
  {'kernel_size': 3021, 'coherence_20': 1.3388642082997657},
  {'kernel_size': 2966, 'coherence_20': 1.8149278029662061},
  {'kernel_size': 3024, 'coherence_20': 1.6300267904928867},
  {'kernel_size': 2802, 'coherence_20': 1.9198499321228757},
  {'kernel_size': 3777, 'coherence_20': 1.730872738965084},
  {'kernel_size': 3522, 'coherence_20': 1.0805991320361101},
  {'kernel_size': 3644, 'coherence_20': 0.8431755453347759},
  {'kernel_size': 3755, 'coherence_20': 1.2629068269355868},
  {'kernel_size': 3254, 'coherence_20': 1.1839908189309014},
  {'kernel_size': 4349, 'coherence_20': 1.5544700223676087},
  {'kernel_size': 4575, 'coherence_20': 2.03696035327588}],
 [{'kernel_size': 3712, 'coherence_20': 2.2875406047479148},
  {'kernel_size': 2941, 'coherence_20': 1.1876313957134998},
  {'kernel_size': 4063, 'coherence_20': 1.6368053726188139},
  {'kernel_size': 4182, 'coherence_20': 2.907805044109926},
  {'kernel_size': 4338, 'coherence_20': 1.453719713570037},
  {'kernel_size': 3332, 'coherence_20': 0.9853017860558071},
  {'kernel_size': 2934, 'coherence_20': 0.6550073593723996},
  {'kernel_size': 3941, 'coherence_20': 1.4757066562301477},
  {'kernel_size': 2920, 'coherence_20': 1.264333245973791},
  {'kernel_size': 3346, 'coherence_20': 1.4623624109404119},
  {'kernel_size': 4327, 'coherence_20': 1.0266575112012786},
  {'kernel_size': 3102, 'coherence_20': 1.297605449008695},
  {'kernel_size': 2537, 'coherence_20': 0.9591847343651783},
  {'kernel_size': 2671, 'coherence_20': 1.2665581512305717},
  {'kernel_size': 4204, 'coherence_20': 1.6697669291966981},
  {'kernel_size': 2170, 'coherence_20': 1.7366366768210553},
  {'kernel_size': 4189, 'coherence_20': 1.1538853428335445},
  {'kernel_size': 3647, 'coherence_20': 1.0253611330834271},
  {'kernel_size': 3588, 'coherence_20': 1.471972798689753},
  {'kernel_size': 2936, 'coherence_20': 0.6757879163999326}],
 [{'kernel_size': 3394, 'coherence_20': 1.1947396786222828},
  {'kernel_size': 3812, 'coherence_20': 1.459182647456126},
  {'kernel_size': 3815, 'coherence_20': 1.6173356424146121},
  {'kernel_size': 3705, 'coherence_20': 1.0278128424861075},
  {'kernel_size': 2643, 'coherence_20': 0.7883315454540667},
  {'kernel_size': 1974, 'coherence_20': 2.195798572530547},
  {'kernel_size': 3503, 'coherence_20': 1.2810358524133383},
  {'kernel_size': 3620, 'coherence_20': 1.0784602018449065},
  {'kernel_size': 3632, 'coherence_20': 1.3607316918278338},
  {'kernel_size': 3444, 'coherence_20': 1.1287998916722426},

In [312]:
! echo $SEARCH_RESULTS_FOLDER_PATH
! ls $SEARCH_RESULTS_FOLDER_PATH

./20_Newsgroups__internals/result2
bank__0  search_result__0.json

In [133]:
# Real-fixing bank topics

In [225]:
from topnum.search_methods.topic_bank.one_model_train_funcs import _get_topic_model, init_phi_utils

In [574]:
from topicnet.cooking_machine.model_constructor import (
    add_standard_scores,
    create_default_topics,
    init_model,
)

def _get_topic_model_dev(
        dataset: Dataset,
        phi: pd.DataFrame = None,
        num_topics: int = None,
        seed: int = None,
        scores: List = None,
        num_safe_fit_iterations: int = 3,
        num_processors: int = 3,
        cache_theta: bool = False) -> TopicModel:

    dictionary = dataset.get_dictionary()

    # for modality in dataset.get_possible_modalities():
    #     if modality not in modalities_to_use:
    #         dictionary.filter(class_id=modality, max_df=0, inplace=True)

    if num_topics is not None and phi is not None:
        assert num_topics >= phi.shape[1]
    elif num_topics is None and phi is not None:
        num_topics = phi.shape[1]
    elif num_topics is None and phi is None:
        raise ValueError()

    topic_names = [f'topic_{i}' for i in range(num_topics)]

    # if seed is None:
    #     artm_model = artm.ARTM(topic_names=topic_names)
    # else:
    #     artm_model = artm.ARTM(topic_names=topic_names, seed=seed)

    if seed is None:
        artm_model = artm.ARTM(topic_names=topic_names, class_ids={MAIN_MODALITY: 1})  # TODO: not list, but dict!!!
    else:
        artm_model = artm.ARTM(topic_names=topic_names, seed=seed, class_ids={MAIN_MODALITY: 1})

    # artm_model = init_model(topic_names, class_ids=[MAIN_MODALITY])

    # artm_model = init_plsa(DATASET, [MAIN_MODALITY], MAIN_MODALITY, 5)

    artm_model.num_processors = num_processors
    artm_model.initialize(dictionary)

    """
    if phi is None:
        pass
    elif num_safe_fit_iterations is not None and num_safe_fit_iterations > 0:
        init_phi_utils._safe_copy_phi(artm_model, phi, dataset, num_safe_fit_iterations)
    else:
        init_phi_utils._copy_phi(artm_model, phi)
    """
    # this breaks smth in ARTM
    # test_ppl@word [1827.4515380859375, 2707.63623046875, 2707.67919921875, 2707.679443359375, 2707.679443359375]
    # test_ppl@word_with_d [4073.36328125, 6035.2822265625, 6035.3779296875, 6035.37841796875, 6035.37841796875]
    # test_ppl@all [1827.4515380859375, 2707.63623046875, 2707.67919921875, 2707.679443359375, 2707.679443359375]
    # test_ppl@all_2 [1827.4515380859375, 2707.63623046875, 2707.67919921875, 2707.679443359375, 2707.679443359375]
    # test_ppl@all_2_with_d [4073.36328125, 6035.2822265625, 6035.3779296875, 6035.37841796875, 6035.37841796875]
    
    topic_model = TopicModel(
        artm_model=artm_model,
        model_id='0',
        cache_theta=cache_theta,
        theta_columns_naming='title'
    )

    if scores is not None:
        for score in scores:
            score._attach(topic_model)

    return topic_model

In [227]:
model = artm_train_func(DATASET, 1, 2, 1)

No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

In [424]:
DATASET.get_dictionary()

artm.Dictionary(name=6231af29-73db-42d7-a978-1e0c744be737, num_entries=19186)

In [425]:
optimizer._dataset.get_dictionary()

artm.Dictionary(name=6231af29-73db-42d7-a978-1e0c744be737, num_entries=19186)

In [588]:
phi = model.get_phi()
phi = phi.iloc[phi.index.get_level_values(0).isin([MAIN_MODALITY])]

word2index = {
    word: index for index, word in enumerate(phi.index)
}

bank_phi = optimizer._get_phi(optimizer._topic_bank.topics, word2index)
# bank_model = _get_topic_model_dev(  #_get_topic_model( _get_topic_model_dev
#     optimizer._dataset,
#     phi=bank_phi,
#     scores=optimizer._all_model_scores,
#     num_safe_fit_iterations=1,
# )
bank_model = init_model_from_family('sparse', DATASET, MAIN_MODALITY, 5, 0)


"""
_bank_model = init_plsa(DATASET, [MAIN_MODALITY], MAIN_MODALITY, 5)
_bank_model.num_processors = 3
# _bank_model.seed = seed
dictionary = DATASET.get_dictionary()

# TODO: maybe this cycle is not necessary
# for modality in DATASET.get_possible_modalities():
#     if modality not in [MAIN_MODALITY]:
#         dictionary.filter(class_id=modality, max_df=0, inplace=True)

_bank_model.initialize(dictionary)
# add_standard_scores(model, dictionary, main_modality=main_modality,
#                     all_modalities=modalities_to_use)

bank_model = TopicModel(
    artm_model=_bank_model,
    # custom_regularizers=custom_regs
)
"""

No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

'\n_bank_model = init_plsa(DATASET, [MAIN_MODALITY], MAIN_MODALITY, 5)\n_bank_model.num_processors = 3\n# _bank_model.seed = seed\ndictionary = DATASET.get_dictionary()\n\n# TODO: maybe this cycle is not necessary\n# for modality in DATASET.get_possible_modalities():\n#     if modality not in [MAIN_MODALITY]:\n#         dictionary.filter(class_id=modality, max_df=0, inplace=True)\n\n_bank_model.initialize(dictionary)\n# add_standard_scores(model, dictionary, main_modality=main_modality,\n#                     all_modalities=modalities_to_use)\n\nbank_model = TopicModel(\n    artm_model=_bank_model,\n    # custom_regularizers=custom_regs\n)\n'

In [589]:
bank_model._model.class_ids

{'@word': 1}

In [590]:
bank_model._model.regularizers

[smooth_phi_bcg, smooth_theta_bcg, sparse_phi_sp, sparse_theta_sp]

In [591]:
bank_model._fit(
    optimizer._dataset.get_batch_vectorizer(),
    num_iterations=2,
)

In [592]:
for m in DATASET.get_possible_modalities():
    bank_model._model.scores.add(
        artm.scores.PerplexityScore(
            name=f'test_ppl{m}',
            class_ids=[m]
        )
    )
    bank_model._model.scores.add(
        artm.scores.PerplexityScore(
            name=f'test_ppl{m}_with_d',
            class_ids=[m],
            dictionary=DATASET.get_dictionary()
        )
    )

bank_model._model.scores.add(
    artm.scores.PerplexityScore(
        name=f'test_ppl@all',
        class_ids=list(DATASET.get_possible_modalities()),
    )
)
bank_model._model.scores.add(
    artm.scores.PerplexityScore(
        name=f'test_ppl@all_2',
   )
)
bank_model._model.scores.add(
    artm.scores.PerplexityScore(
        name=f'test_ppl@all_2_with_d',
        dictionary=DATASET.get_dictionary()
   )
)

In [593]:
bank_phi['topic_4'].sort_values(ascending=False)

@word  клетка             0.030503
       ген                0.012852
       организм           0.009684
       днк                0.009340
       пациент            0.009092
                            ...
       камень             0.000000
       встревожить        0.000000
       технологический    0.000000
       летопись           0.000000
       аврелий            0.000000
Name: topic_4, Length: 19186, dtype: float64

In [594]:
bank_topics['topic_4'].sort_values(ascending=False)

@word  клетка             0.030503
       ген                0.012852
       организм           0.009684
       днк                0.009340
       пациент            0.009092
                            ...
       камень             0.000000
       встревожить        0.000000
       технологический    0.000000
       летопись           0.000000
       аврелий            0.000000
Name: topic_4, Length: 19186, dtype: float64

In [595]:
bank_model.get_phi()['topic_4'].sort_values(ascending=False)

modality  token
@word     язык                 0.015199
          книга                0.008724
          государство          0.007782
          вопрос               0.007237
          общество             0.004902
                                 ...
          жорж                 0.000000
          пешеход              0.000000
          скучать              0.000000
          восстановительный    0.000000
          аврелий              0.000000
Name: topic_4, Length: 19186, dtype: float32

In [596]:
class FastFixPhiRegularizer(BaseRegularizer):
    _VERY_BIG_TAU = 10 ** 9  # 10 ** 9

    def __init__(self, name: str, phi, topic_names: List[str]):
        super().__init__(name, tau=self._VERY_BIG_TAU)

        self._topic_names = topic_names
        self._topic_indices = None
        self._phi = phi

    def grad(self, pwt, nwt):
        # print('Fixing')

        rwt = np.zeros_like(pwt)
        parent_phi = self._phi
        
        rwt[:, self._topic_indices] += parent_phi.values[:, self._topic_indices]

        return self.tau * rwt

    def attach(self, model):
        super().attach(model)
        
        phi = self._model.get_phi()
        self._topic_indices = [
            phi.columns.get_loc(topic_name)
            for topic_name in self._topic_names
        ]

In [600]:
bank_model._fit(
    optimizer._dataset.get_batch_vectorizer(),
    num_iterations=5,
    custom_regularizers={
        'fix': FastFixPhiRegularizer(
            name='fix',
            phi=bank_phi,
            topic_names=bank_phi.columns,
        ),
    }
)

In [601]:
bank_model.get_phi()['topic_4'].sort_values(ascending=False)

modality  token
@word     клетка             0.030503
          ген                0.012852
          организм           0.009684
          днк                0.009340
          пациент            0.009092
                               ...
          камень             0.000000
          встревожить        0.000000
          технологический    0.000000
          летопись           0.000000
          аврелий            0.000000
Name: topic_4, Length: 19186, dtype: float32

In [602]:
for m in DATASET.get_possible_modalities():
    print(f'test_ppl{m}', bank_model.scores[f'test_ppl{m}'])
    print(f'test_ppl{m}_with_d', bank_model.scores[f'test_ppl{m}_with_d'])


print(f'test_ppl@all', bank_model.scores[f'test_ppl@all'])
print(f'test_ppl@all_2', bank_model.scores[f'test_ppl@all_2'])
print(f'test_ppl@all_2_with_d', bank_model.scores[f'test_ppl@all_2_with_d'])

test_ppl@title [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@title_with_d [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@2gramm [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@2gramm_with_d [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@author [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@author_with_d [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@snippet [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@snippet_with_d [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@post_tag [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@post_tag_with_d [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@word [5297.6376953125, 5158.78857421875, 4709.48095703125, 4687.263671875, 4683.79833984375, 4682.92138671875, 4682.62109375, 4682.52197265625, 4682.48974609375, 4682.478515625]
test_ppl@word_with_d [5297.6376953125, 5158.78857421875, 4709.48095703125, 4687.263671875, 4683.79833984375, 4682.92138671875, 4682.62109375, 4682.52197265625, 4682.48974609375, 4682.478515625]
test_ppl@3gramm [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@3gramm_with_d [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@all [5297.6376953125, 5158.78857421875, 4709.48095703125, 4687.263671875, 4683.79833984375, 4682.92138671875, 4682.62109375, 4682.52197265625, 4682.48974609375, 4682.478515625]
test_ppl@all_2 [5297.6376953125, 5158.78857421875, 4709.48095703125, 4687.263671875, 4683.79833984375, 4682.92138671875, 4682.62109375, 4682.52197265625, 4682.48974609375, 4682.478515625]
test_ppl@all_2_with_d [5297.6376953125, 5158.78857421875, 4709.48095703125, 4687.263671875, 4683.79833984375, 4682.92138671875, 4682.62109375, 4682.52197265625, 4682.48974609375, 4682.478515625]

In [475]:
bank_model.scores['perplexity_from_start']

KeyError: 'perplexity_from_start'

In [ ]:
DATASET.get_possible_modalities()

In [191]:
bank_model.get_phi()['topic_2'].sort_values(ascending=False)

modality  token
@word     звезда            0.021522
          вселенная         0.016877
          галактика         0.016023
          земля             0.010558
          солнце            0.009292
                              ...
          марш              0.000000
          феминистка        0.000000
          возобновляться    0.000000
          обвал             0.000000
          акт               0.000000
Name: topic_2, Length: 19186, dtype: float32

In [192]:
coherence_score.call_by_topic(bank_model)

{0: array([1.30200985]),
 1: array([1.08845739]),
 2: array([1.0168754]),
 3: array([1.15621355]),
 4: array([1.28988277])}

In [193]:
coherence_score.call(bank_model)

array([1.17068779])

In [194]:
optimizer._result['bank_scores'][-1]

{'perplexity_score': 2707.664306640625,
 'coherence_20': 1.1706877915144434,
 'diversity_euclidean': 0.06451756106182875,
 'diversity_jensenshannon': 0.6715327504064806,
 'diversity_hellinger': 0.7877305942486647,
 'diversity_cosine': 0.8494073511502591,
 'perplexity': 2707.664306640625}

In [195]:
optimizer._get_default_scores(bank_model)

{'perplexity_score': 2707.679443359375,
 'coherence_20': 1.1706877915144434,
 'diversity_euclidean': 0.0645175614263375,
 'diversity_jensenshannon': 0.6715327515781992,
 'diversity_hellinger': 0.7877305960342527,
 'diversity_cosine': 0.8494073528332182,
 'perplexity': 2707.679443359375}

In [196]:
bank_topics.shape

(19186, 5)

In [416]:
model = init_model_from_family('PLSA', DATASET, MAIN_MODALITY, 5, 0)

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

In [417]:
model.get_phi().shape

(19186, 5)

In [418]:
for m in DATASET.get_possible_modalities():
    model._model.scores.add(
        artm.scores.PerplexityScore(
            name=f'test_ppl{m}',
            class_ids=[m]
        )
    )
    model._model.scores.add(
        artm.scores.PerplexityScore(
            name=f'test_ppl{m}_with_d',
            class_ids=[m],
            dictionary=DATASET.get_dictionary()
        )
    )

model._model.scores.add(
    artm.scores.PerplexityScore(
        name=f'test_ppl@all',
        class_ids=DATASET.get_possible_modalities(),
    )
)
model._model.scores.add(
    artm.scores.PerplexityScore(
        name=f'test_ppl@all_2',
   )
)
model._model.scores.add(
    artm.scores.PerplexityScore(
        name=f'test_ppl@all_2_with_d',
        dictionary=DATASET.get_dictionary()
   )
)

In [419]:
model._fit(DATASET.get_batch_vectorizer(), 20)

In [420]:
for m in DATASET.get_possible_modalities():
    print(f'test_ppl{m}', model.scores[f'test_ppl{m}'])
    print(f'test_ppl{m}_with_d', model.scores[f'test_ppl{m}_with_d'])


print(f'test_ppl@all', model.scores[f'test_ppl@all'])
print(f'test_ppl@all_2', model.scores[f'test_ppl@all_2'])
print(f'test_ppl@all_2_with_d', model.scores[f'test_ppl@all_2_with_d'])

test_ppl@title [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@title_with_d [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@2gramm [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@2gramm_with_d [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@author [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@author_with_d [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@snippet [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@snippet_with_d [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@post_tag [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@post_tag_with_d [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@word [18982.515625, 5344.19189453125, 5225.41015625, 4953.0224609375, 4654.1123046875, 4462.4375, 4331.3232421875, 4235.84521484375, 4167.56640625, 4119.76123046875, 4086.258056640625, 4062.859375, 4046.390380859375, 4034.490234375, 4025.72021484375, 4019.29052734375, 4014.560302734375, 4010.853515625, 4007.927734375, 4005.75537109375]
test_ppl@word_with_d [18982.515625, 5344.19189453125, 5225.41015625, 4953.0224609375, 4654.1123046875, 4462.4375, 4331.3232421875, 4235.84521484375, 4167.56640625, 4119.76123046875, 4086.258056640625, 4062.859375, 4046.390380859375, 4034.490234375, 4025.72021484375, 4019.29052734375, 4014.560302734375, 4010.853515625, 4007.927734375, 4005.75537109375]
test_ppl@3gramm [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@3gramm_with_d [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@all [18982.515625, 5344.19189453125, 5225.41015625, 4953.0224609375, 4654.1123046875, 4462.4375, 4331.3232421875, 4235.84521484375, 4167.56640625, 4119.76123046875, 4086.258056640625, 4062.859375, 4046.390380859375, 4034.490234375, 4025.72021484375, 4019.29052734375, 4014.560302734375, 4010.853515625, 4007.927734375, 4005.75537109375]
test_ppl@all_2 [18982.515625, 5344.19189453125, 5225.41015625, 4953.0224609375, 4654.1123046875, 4462.4375, 4331.3232421875, 4235.84521484375, 4167.56640625, 4119.76123046875, 4086.258056640625, 4062.859375, 4046.390380859375, 4034.490234375, 4025.72021484375, 4019.29052734375, 4014.560302734375, 4010.853515625, 4007.927734375, 4005.75537109375]
test_ppl@all_2_with_d [18982.515625, 5344.19189453125, 5225.41015625, 4953.0224609375, 4654.1123046875, 4462.4375, 4331.3232421875, 4235.84521484375, 4167.56640625, 4119.76123046875, 4086.258056640625, 4062.859375, 4046.390380859375, 4034.490234375, 4025.72021484375, 4019.29052734375, 4014.560302734375, 4010.853515625, 4007.927734375, 4005.75537109375]

In [421]:
model._fit(
    DATASET.get_batch_vectorizer(),
    num_iterations=20,
    custom_regularizers={
        'fix': FastFixPhiRegularizer(
            name='fix',
            phi=bank_phi,
            topic_names=bank_phi.columns,
        ),
    }
)

In [422]:
for m in DATASET.get_possible_modalities():
    print(f'test_ppl{m}', model.scores[f'test_ppl{m}'])
    print(f'test_ppl{m}_with_d', model.scores[f'test_ppl{m}_with_d'])


print(f'test_ppl@all', model.scores[f'test_ppl@all'])
print(f'test_ppl@all_2', model.scores[f'test_ppl@all_2'])
print(f'test_ppl@all_2_with_d', model.scores[f'test_ppl@all_2_with_d'])

test_ppl@title [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@title_with_d [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@2gramm [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@2gramm_with_d [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@author [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@author_with_d [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@snippet [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@snippet_with_d [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@post_tag [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@post_tag_with_d [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@word [18982.515625, 5344.19189453125, 5225.41015625, 4953.0224609375, 4654.1123046875, 4462.4375, 4331.3232421875, 4235.84521484375, 4167.56640625, 4119.76123046875, 4086.258056640625, 4062.859375, 4046.390380859375, 4034.490234375, 4025.72021484375, 4019.29052734375, 4014.560302734375, 4010.853515625, 4007.927734375, 4005.75537109375, 4003.997802734375, 24196.91796875, 23968.0, 23750.837890625, 23556.845703125, 23387.771484375, 23242.3046875, 23115.556640625, 23003.33984375, 22902.7109375, 22813.455078125, 22736.119140625, 22669.6171875, 22611.533203125, 22560.84375, 22516.939453125, 22478.94921875, 22446.25, 22418.119140625, 22394.51953125]
test_ppl@word_with_d [18982.515625, 5344.19189453125, 5225.41015625, 4953.0224609375, 4654.1123046875, 4462.4375, 4331.3232421875, 4235.84521484375, 4167.56640625, 4119.76123046875, 4086.258056640625, 4062.859375, 4046.390380859375, 4034.490234375, 4025.72021484375, 4019.29052734375, 4014.560302734375, 4010.853515625, 4007.927734375, 4005.75537109375, 4003.997802734375, 24196.91796875, 23968.0, 23750.837890625, 23556.845703125, 23387.771484375, 23242.3046875, 23115.556640625, 23003.33984375, 22902.7109375, 22813.455078125, 22736.119140625, 22669.6171875, 22611.533203125, 22560.84375, 22516.939453125, 22478.94921875, 22446.25, 22418.119140625, 22394.51953125]
test_ppl@3gramm [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@3gramm_with_d [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@all [18982.515625, 5344.19189453125, 5225.41015625, 4953.0224609375, 4654.1123046875, 4462.4375, 4331.3232421875, 4235.84521484375, 4167.56640625, 4119.76123046875, 4086.258056640625, 4062.859375, 4046.390380859375, 4034.490234375, 4025.72021484375, 4019.29052734375, 4014.560302734375, 4010.853515625, 4007.927734375, 4005.75537109375, 4003.997802734375, 24196.91796875, 23968.0, 23750.837890625, 23556.845703125, 23387.771484375, 23242.3046875, 23115.556640625, 23003.33984375, 22902.7109375, 22813.455078125, 22736.119140625, 22669.6171875, 22611.533203125, 22560.84375, 22516.939453125, 22478.94921875, 22446.25, 22418.119140625, 22394.51953125]
test_ppl@all_2 [18982.515625, 5344.19189453125, 5225.41015625, 4953.0224609375, 4654.1123046875, 4462.4375, 4331.3232421875, 4235.84521484375, 4167.56640625, 4119.76123046875, 4086.258056640625, 4062.859375, 4046.390380859375, 4034.490234375, 4025.72021484375, 4019.29052734375, 4014.560302734375, 4010.853515625, 4007.927734375, 4005.75537109375, 4003.997802734375, 24196.91796875, 23968.0, 23750.837890625, 23556.845703125, 23387.771484375, 23242.3046875, 23115.556640625, 23003.33984375, 22902.7109375, 22813.455078125, 22736.119140625, 22669.6171875, 22611.533203125, 22560.84375, 22516.939453125, 22478.94921875, 22446.25, 22418.119140625, 22394.51953125]
test_ppl@all_2_with_d [18982.515625, 5344.19189453125, 5225.41015625, 4953.0224609375, 4654.1123046875, 4462.4375, 4331.3232421875, 4235.84521484375, 4167.56640625, 4119.76123046875, 4086.258056640625, 4062.859375, 4046.390380859375, 4034.490234375, 4025.72021484375, 4019.29052734375, 4014.560302734375, 4010.853515625, 4007.927734375, 4005.75537109375, 4003.997802734375, 24196.91796875, 23968.0, 23750.837890625, 23556.845703125, 23387.771484375, 23242.3046875, 23115.556640625, 23003.33984375, 22902.7109375, 22813.455078125, 22736.119140625, 22669.6171875, 22611.533203125, 22560.84375, 22516.939453125, 22478.94921875, 22446.25, 22418.119140625, 22394.51953125]

In [412]:
bank_phi['topic_2'].sort_values(ascending=False)

@word  звезда            0.021526
       вселенная         0.016880
       галактика         0.016026
       земля             0.010559
       солнце            0.009293
                           ...
       марш              0.000000
       феминистка        0.000000
       возобновляться    0.000000
       обвал             0.000000
       акт               0.000000
Name: topic_2, Length: 19186, dtype: float64

In [413]:
model.get_phi()['topic_2'].sort_values(ascending=False)

modality  token
@word     звезда            0.021526
          вселенная         0.016880
          галактика         0.016026
          земля             0.010559
          солнце            0.009293
                              ...
          марш              0.000000
          феминистка        0.000000
          возобновляться    0.000000
          обвал             0.000000
          акт               0.000000
Name: topic_2, Length: 19186, dtype: float32

In [415]:
model.get_phi()['background_5'].sort_values(ascending=False)

modality  token
@word     говорить      0.002969
          язык          0.002913
          книга         0.002437
          большой       0.002309
          слово         0.002295
                          ...
          шриффер       0.000007
          кваркова      0.000007
          килопарсек    0.000007
          оннести       0.000007
          камерлинг     0.000006
Name: background_5, Length: 19186, dtype: float32

In [384]:
model._fit(
    DATASET.get_batch_vectorizer(),
    num_iterations=10,
    custom_regularizers={
        'fix': FastFixPhiRegularizer(
            name='fix',
            phi=bank_phi,
            topic_names=bank_phi.columns,
        ),
    }
)

In [385]:
for m in DATASET.get_possible_modalities():
    print(f'test_ppl{m}', model.scores[f'test_ppl{m}'])
    print(f'test_ppl{m}_with_d', model.scores[f'test_ppl{m}_with_d'])


print(f'test_ppl@all', model.scores[f'test_ppl@all'])
print(f'test_ppl@all_2', model.scores[f'test_ppl@all_2'])
print(f'test_ppl@all_2_with_d', model.scores[f'test_ppl@all_2_with_d'])

test_ppl@title [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@title_with_d [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@2gramm [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@2gramm_with_d [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@author [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@author_with_d [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@snippet [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@snippet_with_d [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@post_tag [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@post_tag_with_d [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@word [18982.515625, 5344.19189453125, 5225.41064453125, 4953.0224609375, 4654.1123046875, 4462.4375, 4331.3232421875, 4235.84521484375, 4167.56591796875, 4119.76171875, 4086.258056640625, 24226.58203125, 23947.90625, 23669.130859375, 23406.2265625, 23166.892578125, 22955.984375, 22772.5078125, 22614.47265625, 22479.451171875, 22364.6015625, 22270.189453125, 22196.77734375, 22139.984375, 22093.416015625, 22055.505859375, 22025.869140625, 22002.611328125, 21984.099609375, 21968.564453125, 21954.888671875, 6131.7958984375, 6109.703125, 6097.63037109375, 6090.6689453125, 6086.68798828125, 6084.2587890625, 6082.62890625, 6081.43994140625, 6080.51220703125]
test_ppl@word_with_d [18982.515625, 5344.19189453125, 5225.41064453125, 4953.0224609375, 4654.1123046875, 4462.4375, 4331.3232421875, 4235.84521484375, 4167.56591796875, 4119.76171875, 4086.258056640625, 24226.58203125, 23947.90625, 23669.130859375, 23406.2265625, 23166.892578125, 22955.984375, 22772.5078125, 22614.47265625, 22479.451171875, 22364.6015625, 22270.189453125, 22196.77734375, 22139.984375, 22093.416015625, 22055.505859375, 22025.869140625, 22002.611328125, 21984.099609375, 21968.564453125, 21954.888671875, 6131.7958984375, 6109.703125, 6097.63037109375, 6090.6689453125, 6086.68798828125, 6084.2587890625, 6082.62890625, 6081.43994140625, 6080.51220703125]
test_ppl@3gramm [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@3gramm_with_d [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
test_ppl@all [18982.515625, 5344.19189453125, 5225.41064453125, 4953.0224609375, 4654.1123046875, 4462.4375, 4331.3232421875, 4235.84521484375, 4167.56591796875, 4119.76171875, 4086.258056640625, 24226.58203125, 23947.90625, 23669.130859375, 23406.2265625, 23166.892578125, 22955.984375, 22772.5078125, 22614.47265625, 22479.451171875, 22364.6015625, 22270.189453125, 22196.77734375, 22139.984375, 22093.416015625, 22055.505859375, 22025.869140625, 22002.611328125, 21984.099609375, 21968.564453125, 21954.888671875, 6131.7958984375, 6109.703125, 6097.63037109375, 6090.6689453125, 6086.68798828125, 6084.2587890625, 6082.62890625, 6081.43994140625, 6080.51220703125]
test_ppl@all_2 [18982.515625, 5344.19189453125, 5225.41064453125, 4953.0224609375, 4654.1123046875, 4462.4375, 4331.3232421875, 4235.84521484375, 4167.56591796875, 4119.76171875, 4086.258056640625, 24226.58203125, 23947.90625, 23669.130859375, 23406.2265625, 23166.892578125, 22955.984375, 22772.5078125, 22614.47265625, 22479.451171875, 22364.6015625, 22270.189453125, 22196.77734375, 22139.984375, 22093.416015625, 22055.505859375, 22025.869140625, 22002.611328125, 21984.099609375, 21968.564453125, 21954.888671875, 6131.7958984375, 6109.703125, 6097.63037109375, 6090.6689453125, 6086.68798828125, 6084.2587890625, 6082.62890625, 6081.43994140625, 6080.51220703125]
test_ppl@all_2_with_d [18982.515625, 5344.19189453125, 5225.41064453125, 4953.0224609375, 4654.1123046875, 4462.4375, 4331.3232421875, 4235.84521484375, 4167.56591796875, 4119.76171875, 4086.258056640625, 24226.58203125, 23947.90625, 23669.130859375, 23406.2265625, 23166.892578125, 22955.984375, 22772.5078125, 22614.47265625, 22479.451171875, 22364.6015625, 22270.189453125, 22196.77734375, 22139.984375, 22093.416015625, 22055.505859375, 22025.869140625, 22002.611328125, 21984.099609375, 21968.564453125, 21954.888671875, 6131.7958984375, 6109.703125, 6097.63037109375, 6090.6689453125, 6086.68798828125, 6084.2587890625, 6082.62890625, 6081.43994140625, 6080.51220703125]

In [386]:
bank_phi['topic_2'].sort_values(ascending=False)

@word  звезда            0.021526
       вселенная         0.016880
       галактика         0.016026
       земля             0.010559
       солнце            0.009293
                           ...
       марш              0.000000
       феминистка        0.000000
       возобновляться    0.000000
       обвал             0.000000
       акт               0.000000
Name: topic_2, Length: 19186, dtype: float64

In [387]:
model.get_phi()['topic_2'].sort_values(ascending=False)

modality  token
@word     звезда           0.018555
          вселенная        0.014553
          галактика        0.013789
          земля            0.009610
          объект           0.008414
                             ...
          схватка          0.000000
          стратегически    0.000000
          вырабатывать     0.000000
          стул             0.000000
          акт              0.000000
Name: topic_2, Length: 19186, dtype: float32

In [113]:
model.scores['PerplexityScore@word']

[19895.9453125,
 5456.2392578125,
 5297.1337890625,
 5065.22119140625,
 4837.330078125,
 4680.2939453125,
 4590.2880859375,
 4540.271484375,
 4511.2646484375,
 4493.751953125,
 4482.685546875,
 4475.7783203125,
 4471.40087890625,
 4468.5302734375,
 4466.552734375,
 4465.248046875,
 4464.421875,
 4463.90576171875,
 4463.64404296875,
 4463.5302734375,
 4463.5283203125,
 5405.4609375,
 4719.11279296875,
 4688.26416015625,
 4683.736328125,
 4682.79052734375,
 4682.53857421875,
 4682.48193359375,
 4682.46923828125,
 4682.4638671875,
 4682.4619140625,
 4682.4658203125,
 4682.46875,
 4682.46875,
 4682.47021484375,
 4682.4697265625,
 4682.470703125,
 4682.470703125,
 4682.47021484375,
 4682.470703125,
 4682.470703125,
 4682.47119140625,
 4682.47119140625,
 4682.47119140625]

In [108]:
bank_model.get_phi()['topic_0'].sort_values(ascending=False)[:10]

modality  token
@word     caption              0.025622
          align                0.012789
          width                0.012788
          attachment           0.012606
          свет                 0.012437
          aligncenter          0.007243
          рис                  0.006824
          устройство           0.006685
          сверхпроводимость    0.005892
          святилище            0.005607
Name: topic_0, dtype: float32

In [114]:
model.get_phi()['topic_0'].sort_values(ascending=False)[:10]

modality  token
@word     caption              0.025624
          align                0.012790
          width                0.012790
          attachment           0.012607
          свет                 0.012438
          aligncenter          0.007243
          рис                  0.006825
          устройство           0.006685
          сверхпроводимость    0.005892
          святилище            0.005608
Name: topic_0, dtype: float32

In [115]:
model.get_phi().head()

                       topic_0  topic_1  topic_2   topic_3  topic_4  \
modality token
@word    инвалидность      0.0      0.0      0.0  0.000000      0.0
         мазка             0.0      0.0      0.0  0.000000      0.0
         professor         0.0      0.0      0.0  0.000017      0.0
         умно              0.0      0.0      0.0  0.000000      0.0
         игил              0.0      0.0      0.0  0.000000      0.0

                       background_5
modality token
@word    инвалидность      0.000010
         мазка             0.000010
         professor         0.000009
         умно              0.000010
         игил              0.000010

In [116]:
model = init_model_from_family('PLSA', DATASET, MAIN_MODALITY, 5, 0)

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

In [117]:
model._fit(
    DATASET.get_batch_vectorizer(),
    num_iterations=20,
    custom_regularizers={
        regularizer.name: regularizer,
    }
)

In [118]:
model.scores['PerplexityScore@word']

[18982.515625,
 24645.68359375,
 23630.40234375,
 22722.39453125,
 22194.84765625,
 21943.359375,
 21827.154296875,
 21770.6875,
 21740.708984375,
 21723.21875,
 21712.1875,
 21704.763671875,
 21699.482421875,
 21695.611328125,
 21692.720703125,
 21690.517578125,
 21688.822265625,
 21687.4921875,
 21686.439453125,
 21685.58984375]

In [130]:
model.scores['PerplexityScore@all']

[18982.515625,
 24645.68359375,
 23630.40234375,
 22722.39453125,
 22194.84765625,
 21943.359375,
 21827.154296875,
 21770.6875,
 21740.708984375,
 21723.21875,
 21712.1875,
 21704.763671875,
 21699.482421875,
 21695.611328125,
 21692.720703125,
 21690.517578125,
 21688.822265625,
 21687.4921875,
 21686.439453125,
 21685.58984375]

In [125]:
bank_model.get_phi()['topic_1'].sort_values(ascending=False)[:10]

modality  token
@word     право        0.019665
          закон        0.009846
          сталин       0.008532
          власть       0.007165
          история      0.006088
          суд          0.005563
          церковь      0.005529
          бог          0.005110
          отношение    0.004377
          должный      0.004363
Name: topic_1, dtype: float32

In [126]:
model.get_phi()['topic_1'].sort_values(ascending=False)[:10]

modality  token
@word     право        0.019660
          закон        0.009844
          сталин       0.008530
          власть       0.007163
          история      0.006086
          суд          0.005561
          церковь      0.005527
          бог          0.005108
          отношение    0.004376
          должный      0.004363
Name: topic_1, dtype: float32

In [121]:
model.get_phi().head()

                            topic_0       topic_1       topic_2       topic_3  \
modality token
@word    инвалидность  0.000000e+00  4.833264e-09  0.000000e+00  0.000000e+00
         мазка         0.000000e+00  2.413737e-09  1.678086e-09  5.836904e-16
         professor     0.000000e+00  0.000000e+00  0.000000e+00  1.689069e-05
         умно          1.873608e-14  4.886941e-09  0.000000e+00  1.101553e-10
         игил          0.000000e+00  4.997070e-09  0.000000e+00  0.000000e+00

                            topic_4
modality token
@word    инвалидность  1.638571e-10
         мазка         9.061746e-10
         professor     0.000000e+00
         умно          0.000000e+00
         игил          0.000000e+00

In [123]:
bank_model.get_phi().index

MultiIndex([('@word',   'инвалидность'),
            ('@word',          'мазка'),
            ('@word',      'professor'),
            ('@word',           'умно'),
            ('@word',           'игил'),
            ('@word',        'стучать'),
            ('@word',   'медлительный'),
            ('@word',    'газопылевой'),
            ('@word',       'разогрев'),
            ('@word',       'загрузка'),
            ...
            ('@word',           'зять'),
            ('@word', 'ниспровержение'),
            ('@word',        'пометка'),
            ('@word',       'франциск'),
            ('@word',           'wall'),
            ('@word',     'милосердие'),
            ('@word',        'поверка'),
            ('@word',            'вто'),
            ('@word',         'слоить'),
            ('@word',            'акт')],
           names=['modality', 'token'], length=19186)

In [122]:
model.get_phi().index

MultiIndex([('@word',   'инвалидность'),
            ('@word',          'мазка'),
            ('@word',      'professor'),
            ('@word',           'умно'),
            ('@word',           'игил'),
            ('@word',        'стучать'),
            ('@word',   'медлительный'),
            ('@word',    'газопылевой'),
            ('@word',       'разогрев'),
            ('@word',       'загрузка'),
            ...
            ('@word',           'зять'),
            ('@word', 'ниспровержение'),
            ('@word',        'пометка'),
            ('@word',       'франциск'),
            ('@word',           'wall'),
            ('@word',     'милосердие'),
            ('@word',        'поверка'),
            ('@word',            'вто'),
            ('@word',         'слоить'),
            ('@word',            'акт')],
           names=['modality', 'token'], length=19186)

In [173]:
all(bank_model.get_phi().index == model.get_phi().index)

True

In [124]:
optimizer._get_default_scores(model)

KeyError: 'perplexity_score'

In [144]:
bank_model.scores['perplexity_score']

[1836.541748046875,
 2707.664306640625,
 2707.67919921875,
 2707.679443359375,
 2707.679443359375,
 2707.679443359375,
 2707.679443359375,
 2707.679443359375]

In [147]:
bank_model.scores[f'PerplexityScore{modality}']

[nan, nan, nan, nan, nan, nan, nan]

In [150]:
bank_model.scores[f'test_ppl']

[2707.679443359375,
 2707.679443359375,
 2707.679443359375,
 2707.679443359375,
 2707.679443359375]

In [134]:
np.allclose(model.get_phi().values, bank_model.get_phi().values, atol=1e-5)

True

In [157]:
# model._model.scores.add(
#     artm.scores.PerplexityScore(name='test_ppl', class_ids=None)
# )
# model._model.scores.add(
#     artm.scores.PerplexityScore(name='test_ppl2', class_ids=None, dictionary=DATASET.get_dictionary())
# )
model._model.scores.add(
    artm.scores.PerplexityScore(name='test_ppl3', dictionary=DATASET.get_dictionary())
)
model._fit(
    DATASET.get_batch_vectorizer(),
    num_iterations=5,
    custom_regularizers={
        regularizer.name: regularizer,
    }
)

In [174]:
for m in DATASET.get_possible_modalities():
    model._model.scores.add(
        artm.scores.PerplexityScore(
            name=f'test_ppl{m}',
            class_ids=[m]
        )
    )
    model._model.scores.add(
        artm.scores.PerplexityScore(
            name=f'test_ppl{m}_with_d',
            class_ids=[m],
            dictionary=DATASET.get_dictionary()
        )
    )

model._model.scores.add(
    artm.scores.PerplexityScore(
        name=f'test_ppl@all',
        class_ids=DATASET.get_possible_modalities(),
    )
)
model._model.scores.add(
    artm.scores.PerplexityScore(
        name=f'test_ppl@all_2',
   )
)
model._model.scores.add(
    artm.scores.PerplexityScore(
        name=f'test_ppl@all_2_with_d',
        dictionary=DATASET.get_dictionary()
   )
)

In [175]:
model._fit(
    DATASET.get_batch_vectorizer(),
    num_iterations=5,
    custom_regularizers={
        regularizer.name: regularizer,
    }
)

In [143]:
model.scores['test_ppl']

[21684.888671875,
 21684.30078125,
 21683.7890625,
 21683.34375,
 21682.94921875,
 21682.603515625,
 21682.29296875,
 21682.017578125,
 21681.7734375,
 21681.55859375,
 21681.365234375,
 21681.1953125,
 21681.041015625,
 21680.896484375,
 21680.759765625,
 21680.634765625,
 21680.515625,
 21680.396484375,
 21680.28125,
 21680.1640625]

In [156]:
model.scores['test_ppl2']

[21680.048828125,
 21679.92578125,
 21679.798828125,
 21679.6640625,
 21679.521484375,
 21679.37109375,
 21679.2109375,
 21679.03515625,
 21678.841796875,
 21678.62109375,
 21678.357421875,
 21678.060546875,
 21677.73046875,
 21677.384765625,
 21677.048828125,
 21676.75390625,
 21676.513671875,
 21676.330078125,
 21676.201171875,
 21676.1015625]

In [158]:
model.scores['test_ppl3']

[21676.0234375, 21675.96484375, 21675.912109375, 21675.875, 21675.837890625]

In [154]:
for m in DATASET.get_possible_modalities():
    print(f'test_ppl{m}', bank_model.scores[f'test_ppl{m}'])
    print(f'test_ppl{m}_with_d', bank_model.scores[f'test_ppl{m}_with_d'])


print(f'test_ppl@all', bank_model.scores[f'test_ppl@all'])
print(f'test_ppl@all_2', bank_model.scores[f'test_ppl@all_2'])
print(f'test_ppl@all_2_with_d', bank_model.scores[f'test_ppl@all_2_with_d'])

test_ppl@title [nan, nan, nan, nan, nan]
test_ppl@title_with_d [nan, nan, nan, nan, nan]
test_ppl@2gramm [nan, nan, nan, nan, nan]
test_ppl@2gramm_with_d [nan, nan, nan, nan, nan]
test_ppl@author [nan, nan, nan, nan, nan]
test_ppl@author_with_d [nan, nan, nan, nan, nan]
test_ppl@snippet [nan, nan, nan, nan, nan]
test_ppl@snippet_with_d [nan, nan, nan, nan, nan]
test_ppl@post_tag [nan, nan, nan, nan, nan]
test_ppl@post_tag_with_d [nan, nan, nan, nan, nan]
test_ppl@word [nan, nan, nan, nan, nan]
test_ppl@word_with_d [nan, nan, nan, nan, nan]
test_ppl@3gramm [nan, nan, nan, nan, nan]
test_ppl@3gramm_with_d [nan, nan, nan, nan, nan]
test_ppl@all [nan, nan, nan, nan, nan]
test_ppl@all_2 [2707.679443359375, 2707.679443359375, 2707.679443359375, 2707.679443359375, 2707.679443359375]
test_ppl@all_2_with_d [6035.37841796875, 6035.37841796875, 6035.37841796875, 6035.37841796875, 6035.37841796875]

In [ ]:
# WTF???? all_2 vs all_2_with_d

In [176]:
for m in DATASET.get_possible_modalities():
    print(f'test_ppl{m}', model.scores[f'test_ppl{m}'])
    print(f'test_ppl{m}_with_d', model.scores[f'test_ppl{m}_with_d'])


print(f'test_ppl@all', model.scores[f'test_ppl@all'])
print(f'test_ppl@all_2', model.scores[f'test_ppl@all_2'])
print(f'test_ppl@all_2_with_d', model.scores[f'test_ppl@all_2_with_d'])

test_ppl@title [nan, nan, nan, nan, nan]
test_ppl@title_with_d [nan, nan, nan, nan, nan]
test_ppl@2gramm [nan, nan, nan, nan, nan]
test_ppl@2gramm_with_d [nan, nan, nan, nan, nan]
test_ppl@author [nan, nan, nan, nan, nan]
test_ppl@author_with_d [nan, nan, nan, nan, nan]
test_ppl@snippet [nan, nan, nan, nan, nan]
test_ppl@snippet_with_d [nan, nan, nan, nan, nan]
test_ppl@post_tag [nan, nan, nan, nan, nan]
test_ppl@post_tag_with_d [nan, nan, nan, nan, nan]
test_ppl@word [21675.8046875, 21675.7734375, 21675.744140625, 21675.7109375, 21675.67578125]
test_ppl@word_with_d [21675.8046875, 21675.7734375, 21675.744140625, 21675.7109375, 21675.67578125]
test_ppl@3gramm [nan, nan, nan, nan, nan]
test_ppl@3gramm_with_d [nan, nan, nan, nan, nan]
test_ppl@all [21675.8046875, 21675.7734375, 21675.744140625, 21675.7109375, 21675.67578125]
test_ppl@all_2 [21675.8046875, 21675.7734375, 21675.744140625, 21675.7109375, 21675.67578125]
test_ppl@all_2_with_d [21675.8046875, 21675.7734375, 21675.744140625, 21675.7109375, 21675.67578125]

In [159]:
np.allclose(model.get_phi().values, bank_model.get_phi().values, atol=1e-5)

True

In [163]:
np.allclose(model.get_theta(dataset=DATASET).values, bank_model.get_theta(dataset=DATASET).values, atol=1e-2)

False

In [166]:
model.get_theta(dataset=DATASET).head()

,2001.txt,2002.txt,2003.txt,2004.txt,2005.txt,2006.txt,2007.txt,2008.txt,2009.txt,2010.txt,...,991.txt,992.txt,993.txt,994.txt,995.txt,996.txt,997.txt,998.txt,999.txt,1000.txt
topic_0,0.056126,0.051794,0.027882,0.014199,0.043396,0.055867,0.077195,0.026650,0.108815,0.070042,...,0.046440,0.093659,0.037586,0.064593,0.000370,0.101226,0.006319,0.067003,0.146280,0.014262
topic_1,0.450934,0.030464,0.715602,0.750854,0.780230,0.683530,0.045779,0.174325,0.094343,0.779998,...,0.304143,0.398997,0.493840,0.040556,0.026051,0.104955,0.090535,0.459343,0.388860,0.046970
topic_2,0.456754,0.081020,0.108327,0.098719,0.082993,0.080848,0.186471,0.160910,0.130105,0.052453,...,0.252047,0.008952,0.303512,0.072870,0.883414,0.141408,0.106314,0.130316,0.053466,0.427126
topic_3,0.001702,0.121700,0.009623,0.045128,0.014734,0.064188,0.183776,0.140578,0.059057,0.026539,...,0.050335,0.154085,0.091995,0.060165,0.090149,0.129368,0.087532,0.112709,0.094390,0.501772
topic_4,0.034484,0.715021,0.138565,0.091100,0.078646,0.115567,0.506779,0.497538,0.607680,0.070969,...,0.347036,0.344307,0.073068,0.761816,0.000015,0.523044,0.709301,0.230629,0.317003,0.009870

In [168]:
model._cache_theta

False

In [170]:
model._model.transform(DATASET.get_batch_vectorizer())

,2001.txt,2002.txt,2003.txt,2004.txt,2005.txt,2006.txt,2007.txt,2008.txt,2009.txt,2010.txt,...,991.txt,992.txt,993.txt,994.txt,995.txt,996.txt,997.txt,998.txt,999.txt,1000.txt
topic_0,0.056126,0.051794,0.027882,0.014199,0.043396,0.055867,0.077195,0.026650,0.108815,0.070042,...,0.046440,0.093659,0.037586,0.064593,0.000370,0.101226,0.006319,0.067003,0.146280,0.014262
topic_1,0.450934,0.030464,0.715602,0.750854,0.780230,0.683530,0.045779,0.174325,0.094343,0.779998,...,0.304143,0.398997,0.493840,0.040556,0.026051,0.104955,0.090535,0.459343,0.388860,0.046970
topic_2,0.456754,0.081020,0.108327,0.098719,0.082993,0.080848,0.186471,0.160910,0.130105,0.052453,...,0.252047,0.008952,0.303512,0.072870,0.883414,0.141408,0.106314,0.130316,0.053466,0.427126
topic_3,0.001702,0.121700,0.009623,0.045128,0.014734,0.064188,0.183776,0.140578,0.059057,0.026539,...,0.050335,0.154085,0.091995,0.060165,0.090149,0.129368,0.087532,0.112709,0.094390,0.501772
topic_4,0.034484,0.715021,0.138565,0.091100,0.078646,0.115567,0.506779,0.497538,0.607680,0.070969,...,0.347036,0.344307,0.073068,0.761816,0.000015,0.523044,0.709301,0.230629,0.317003,0.009870

In [167]:
bank_model.get_theta(dataset=DATASET).head()

,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,...,990,991,992,993,994,995,996,997,998,999
topic_0,0.101861,0.074489,0.049455,0.022172,0.054905,0.070409,0.101073,0.037551,0.134165,0.113353,...,0.070619,0.112992,0.051316,0.073642,0.000986,0.127711,0.011525,0.099503,0.197428,0.015720
topic_1,0.655863,0.000609,0.372001,0.575786,0.645551,0.599838,0.032964,0.064134,0.050619,0.640101,...,0.185637,0.275330,0.352115,0.023438,0.018515,0.040171,0.048147,0.304867,0.152107,0.015568
topic_2,0.055471,0.127861,0.242632,0.168248,0.112799,0.103563,0.227997,0.224257,0.158512,0.091768,...,0.374002,0.016707,0.380625,0.084925,0.889346,0.168104,0.144765,0.185562,0.086654,0.441052
topic_3,0.027465,0.175088,0.037685,0.078449,0.029023,0.080083,0.235881,0.200229,0.075055,0.041916,...,0.081005,0.197989,0.120509,0.075768,0.091138,0.174744,0.105661,0.166301,0.153787,0.515394
topic_4,0.159340,0.621953,0.298227,0.155344,0.157723,0.146106,0.402084,0.473828,0.581650,0.112861,...,0.288736,0.396982,0.095435,0.742226,0.000015,0.489270,0.689901,0.243766,0.410024,0.012266

In [169]:
bank_model._cache_theta

False

In [171]:
bank_model._model.transform(DATASET.get_batch_vectorizer())

,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,...,990,991,992,993,994,995,996,997,998,999
topic_0,0.101861,0.074489,0.049455,0.022172,0.054905,0.070409,0.101073,0.037551,0.134165,0.113353,...,0.070619,0.112992,0.051316,0.073642,0.000986,0.127711,0.011525,0.099503,0.197428,0.015720
topic_1,0.655863,0.000609,0.372001,0.575786,0.645551,0.599838,0.032964,0.064134,0.050619,0.640101,...,0.185637,0.275330,0.352115,0.023438,0.018515,0.040171,0.048147,0.304867,0.152107,0.015568
topic_2,0.055471,0.127861,0.242632,0.168248,0.112799,0.103563,0.227997,0.224257,0.158512,0.091768,...,0.374002,0.016707,0.380625,0.084925,0.889346,0.168104,0.144765,0.185562,0.086654,0.441052
topic_3,0.027465,0.175088,0.037685,0.078449,0.029023,0.080083,0.235881,0.200229,0.075055,0.041916,...,0.081005,0.197989,0.120509,0.075768,0.091138,0.174744,0.105661,0.166301,0.153787,0.515394
topic_4,0.159340,0.621953,0.298227,0.155344,0.157723,0.146106,0.402084,0.473828,0.581650,0.112861,...,0.288736,0.396982,0.095435,0.742226,0.000015,0.489270,0.689901,0.243766,0.410024,0.012266