# TopicBank: Bank Creation Experiment

Here we are going to collect interpretable topics (automatically, using topic coherence) from multiple model training.
These topics constitute *topic bank*.
And then the topic bank is going to be used for estimating topic models quality in the notebook [TopicBank-Experiment: Model Validation](TopicBank-Experiment-ModelValidation.ipynb).

The process is repeated for several datasets (some of them are already downloadable using [TopicNet](https://github.com/machine-intelligence-laboratory/TopicNet) library).

# Contents<a id="contents"></a>

* [Data](#data)
    * [Coocs](#coocs)
        * [Lower Memory Consumption (or a Bit of Shamanism. Part 1)](#optimizing-memory)
    * [Documents for Coherence Scores](#docs-for-cohs)
        * [Lower Time Consumption in Case of Big Datasets (or a Bit of Shamanism. Part 2)](#optimizing-time)
* [Experiment](#experiment)
    * [Scores](#scores)
    * [Bank Creation](#bank-creation)
* [Postprocessing](#postprocessing)

In [1]:
# General imports

import dill
import itertools
import json
import numpy as np
import os
import pandas as pd
import sys

from enum import Enum
from scipy.stats import gaussian_kde
from matplotlib import pyplot as plt
from tqdm import tqdm
from typing import (
    Dict,
    Iterable,
)

%matplotlib inline

In [2]:
# Making `topnum` module visible for Python

sys.path.insert(0, '../OptimalNumberOfTopics')

In [3]:
# Optimal number of topics

from topicnet.cooking_machine import Dataset

from topnum.data.vowpal_wabbit_text_collection import VowpalWabbitTextCollection
from topnum.scores import (
    PerplexityScore,
    SparsityPhiScore,
    SparsityThetaScore,
)
from topnum.scores.diversity_score import DiversityScore, KNOWN_METRICS
from topnum.scores._base_coherence_score import (
    SpecificityEstimationMethod,
    TextType,
    WordTopicRelatednessType,
)
from topnum.regularizers import (
    FastFixPhiRegularizer, DecorrelateWithOtherPhiRegularizer, DecorrelateWithOtherPhiRegularizer2
)
from topnum.scores.intratext_coherence_score import (
    IntratextCoherenceScore,
    ComputationMethod,
    WordTopicRelatednessType,
)
from topnum.search_methods import TopicBankMethod
from topnum.search_methods.topic_bank.topic_bank import TopicBank
from topnum.search_methods.topic_bank.one_model_train_funcs import (
    default_train_func,

    # Functions below are not used (but could have been)

#     regularization_train_func,
#     specific_initial_phi_train_func,
#     background_topics_train_func,

)

## Data<a id="data"></a>

<div style="text-align: right">Back to <a href=#contents>Contents</a></div>

Loading data from disk, creating batches, dictionary, gathering cooccurrence statistics...

In [4]:
DATA_FOLDER_PATH = '/data_mil/shared/CompressaAI/iterative/data/noow'

In [5]:
sorted(os.listdir(DATA_FOLDER_PATH))

['20_Newsgroups_NOOW.csv',
 '20_Newsgroups_NOOW__internals',
 '20_Newsgroups__internals',
 'MKB_10_NOOW.csv',
 'MKB_10_NOOW__internals',
 'MKB_10__internals',
 'Post_Science_NOOW.csv',
 'Post_Science_NOOW__internals',
 'Post_Science_NOOW_fixed.csv',
 'Post_Science_NOOW_fixed__internals',
 'Post_Science__internals',
 'WikiRef_220_NOOW.csv',
 '_20_Newsgroups.csv',
 '_20_Newsgroups__internals',
 '_Lenta.csv']

In [6]:
class DatasetName(Enum):
    POSTNAUKA = 'Post_Science'
    # REUTERS = 'Reuters'
    # BROWN = 'Brown'
    TWENTY_NEWSGROUPS = '20_Newsgroups'
    GOOD_RU_WIKI = 'Good_RU_Wiki'
    MKB10 = 'MKB_10'

In [7]:
DATASET_NAME_TO_DATASET_FILE_PATH = {
    DatasetName.POSTNAUKA: os.path.join(
        DATA_FOLDER_PATH, 'postnauka.csv'
    ),
    # DatasetName.REUTERS: os.path.join(
    #     DATA_FOLDER_PATH, 'Reuters.csv'
    # ),
    # DatasetName.BROWN: os.path.join(
    #     DATA_FOLDER_PATH, 'Brown.csv'
    # ),
    DatasetName.TWENTY_NEWSGROUPS: os.path.join(
        DATA_FOLDER_PATH, '20NG.csv'
    ),
    # DatasetName.AG_NEWS: os.path.join(
    #     DATA_FOLDER_PATH, 'AG_News.csv'
    # ),
    # DatasetName.WATAN: os.path.join(
    #     DATA_FOLDER_PATH, 'Watan2004.csv'
    # ),
    # DatasetName.HABRAHABR: os.path.join(
    #     DATA_FOLDER_PATH, 'Habrahabr.csv'
    # ),
    DatasetName.GOOD_RU_WIKI: os.path.join(
        DATA_FOLDER_PATH, 'ruwiki_good.txt'
    ),
    DatasetName.MKB10: os.path.join(
        DATA_FOLDER_PATH, 'MKB_10_NOOW.csv'
    ),
}

In [8]:
DATASET_NAME = DatasetName.MKB10  # select a dataset here

DATASET_FILE_PATH = DATASET_NAME_TO_DATASET_FILE_PATH[DATASET_NAME]

Checking if all OK with data, what modalities does the collection have.

In [9]:
! head -n 2 $DATASET_FILE_PATH

id,raw_text,vw_text
«Бедная_симптомами»_шизофрения,"«Бе́дная симпто́мами» шизофрени́я — подтип шизотипического расстройства в российской версии МКБ-10[1] (ранее считавшийся «простым вариантом вялопротекающей шизофрении»[2][3] и «первичным дефект-психозом»[4][3]), проявляющийся преимущественно негативными симптомами (апатией, астеническим дефектом, суженным или уплощённым аффектом, социальной аутизацией, но без бреда и галлюцинаций).

In [10]:
def get_dataset_internals_folder_path(dataset_name: DatasetName) -> str:
    return os.path.join(DATA_FOLDER_PATH, dataset_name.value + '__internals')

In [11]:
DATASET_INTERNALS_FOLDER_PATH = get_dataset_internals_folder_path(DATASET_NAME)

In [12]:
DATASET_INTERNALS_FOLDER_PATH

'/data_mil/shared/CompressaAI/iterative/data/noow/MKB_10__internals'

In [13]:
%%time

# If using really big datasets (like Habrahabr),
# one may need to set this equal `False`
KEEP_DATASET_IN_MEMORY = True

DATASET = Dataset(
    DATASET_FILE_PATH,
    internals_folder_path=DATASET_INTERNALS_FOLDER_PATH,
    keep_in_memory=KEEP_DATASET_IN_MEMORY,
)

CPU times: user 1.67 s, sys: 167 ms, total: 1.84 s
Wall time: 1.81 s

Looking what is inside dataset's folder

In [14]:
os.listdir(DATASET_INTERNALS_FOLDER_PATH)

['_result2', 'result2', 'dict.dict', 'batches', 'vw.txt']

In [15]:
MAIN_MODALITY = '@text'

In [16]:
DATASET.get_dictionary()

artm.Dictionary(name=8b6b94ce-8444-492f-850a-42f0a4c559e1, num_entries=244551)

In [17]:
dictionary = DATASET.get_dictionary()

In [18]:
print(dictionary)

for modality in DATASET.get_possible_modalities():
    if modality not in [MAIN_MODALITY]:
        dictionary.filter(class_id=modality, max_df=0, inplace=True)

artm.Dictionary(name=8b6b94ce-8444-492f-850a-42f0a4c559e1, num_entries=244551)

In [19]:
dictionary

artm.Dictionary(name=8b6b94ce-8444-492f-850a-42f0a4c559e1, num_entries=46873)

In [20]:
dictionary.filter(min_df=2, max_df_rate=0.5)

artm.Dictionary(name=8b6b94ce-8444-492f-850a-42f0a4c559e1, num_entries=22608)

In [21]:
DATASET._cached_dict = dictionary

In [22]:
DATASET.get_dictionary()

artm.Dictionary(name=8b6b94ce-8444-492f-850a-42f0a4c559e1, num_entries=22608)

Creating batches

In [23]:
DATASET.get_batch_vectorizer()

artm.BatchVectorizer(data_path="/data_mil/shared/CompressaAI/iterative/data/noow/MKB_10__internals/batches", num_batches=3)

In [24]:
os.listdir(DATASET_INTERNALS_FOLDER_PATH)

['_result2', 'result2', 'dict.dict', 'batches', 'vw.txt']

In [25]:
if KEEP_DATASET_IN_MEMORY:
    DOCUMENTS = list(DATASET._data.index)
else:
    DOCUMENTS = list(DATASET._data_index)

NUM_DOCUMENTS = len(DOCUMENTS)

print(f'Num documents: {NUM_DOCUMENTS}')

Num documents: 2036

Let's look at some text samples

In [26]:
DATASET._data.head()

,id,raw_text,vw_text
id,,,
«Бедная_симптомами»_шизофрения,«Бедная_симптомами»_шизофрения,«Бе́дная симпто́мами» шизофрени́я — подтип шиз...,«Бедная_симптомами»_шизофрения |@text бедный с...
"46,XX/46,XY","46,XX/46,XY","46,XX/46,XY (тетрагаметный химеризм) — это раз...","46,XX/46,XY |@text <person> химеризм разновидн..."
"Синдром_48,_XXXY","Синдром_48,_XXXY","Синдром 48, XXXY — это генетическое состояние,...","Синдром_48,_XXXY |@text синдром xxxy генетичес..."
"Синдром_48,_XXYY","Синдром_48,_XXYY","Синдром 48, XXYY — это аномалия хромосом, при ...","Синдром_48,_XXYY |@text синдром xxyy аномалия ..."
"Синдром_48,_XYYY","Синдром_48,_XYYY","Синдром 48, XYYY — чрезвычайно редкая анеуплои...","Синдром_48,_XYYY |@text синдром xyyy чрезвычаи..."

In [27]:
DATASET.get_possible_modalities()

{'@letter', '@ngram', '@text'}

In [28]:
MAIN_MODALITY = '@text'

In [29]:
DATASET.get_dictionary()

artm.Dictionary(name=8b6b94ce-8444-492f-850a-42f0a4c559e1, num_entries=22608)

In [30]:
dictionary = DATASET.get_dictionary()

In [23]:
print(dictionary)

for modality in DATASET.get_possible_modalities():
    if modality not in [MAIN_MODALITY]:
        dictionary.filter(class_id=modality, max_df=0, inplace=True)

artm.Dictionary(name=1e4e5328-9ae6-43a9-9147-27a7003c3c5d, num_entries=244551)

In [24]:
dictionary.filter(min_df=2, max_df_rate=0.5)

artm.Dictionary(name=1e4e5328-9ae6-43a9-9147-27a7003c3c5d, num_entries=22608)

In [25]:
DATASET._cached_dict = dictionary

In [31]:
DATASET.get_dictionary()

artm.Dictionary(name=4aca0b61-8b11-4006-ae33-fce4bd3dd02f, num_entries=22608)

In [30]:
import scipy

from typing import List

from topicnet.cooking_machine.models.base_regularizer import BaseRegularizer
from topicnet.cooking_machine.models.thetaless_regularizer import (
    dataset2sparse_matrix,
)
from topicnet.cooking_machine.models import (
    BaseScore as BaseTopicNetScore,
    TopicModel
)

In [31]:
def calc_doc_occurrences(dataset, modality):
    """
    :param n_dw_matrix: sparse document-word matrix, shape is D x W
    :return: sparse matrix of co-occurrences

    doc_occurrences[w1, w2] = the number of the documents
    where there are w1 and w2
    """
    n_dw_matrix = dataset2sparse_matrix(dataset, modality, modalities_to_use=[modality])
    matrix = (scipy.sparse.csc_matrix(n_dw_matrix) > 0).astype(int)
    co_occurrences = matrix.T * matrix

    return co_occurrences.diagonal(), co_occurrences


def create_pmi_top_function(
    doc_occurrences, doc_co_occurrences,
    documents_number, top_sizes,
    topic_indices=None,
    co_occurrences_smooth=1.
):
    """
    :param doc_occurrences: array of doc occurrences of words
    :param doc_co_occurrences: sparse matrix of doc co-occurrences of words
    :param documents_number: number of the documents
    :param top_sizes: list of top values to calculate top-pmi for
    :param co_occurrences_smooth: constant to smooth co-occurrences in log
    :return: function which takes phi and theta and returns
    pair of two arrays: pmi-s of the tops and ppmi-s of the tops

    pmi[i] - pmi(top of size top_sizes[i])
    ppmi[i] - ppmi(top of size top_sizes[i])

    pmi(words) = sum_{u in words, v in words, u != v}
    log(
        (doc_co_occurrences[u, v] * documents_number + co_occurrences_smooth)
        / doc_occurrences[u] / doc_occurrences[v]
    )

    ppmi(words) = sum_{u in words, v in words, u != v}
    max(log(
        (doc_co_occurrences[u, v] * documents_number + co_occurrences_smooth)
        / doc_occurrences[u] / doc_occurrences[v]
    ), 0)

    """
    def func(phi):
        T, W = phi.shape
        # T = len(topic_indices)
        topic_indices = list(range(T))

        max_top_size = max(top_sizes)
        topic_pmis, topic_ppmis = dict(), dict()
        pmi, ppmi = np.zeros(max_top_size), np.zeros(max_top_size)
        tops = np.argpartition(phi, -max_top_size, axis=1)[:, -max_top_size:]
        
        for t in topic_indices:
            top = sorted(tops[t], key=lambda w: - phi[t, w])
            # print(top, phi.shape, doc_co_occurrences.shape)
            co_occurrences = doc_co_occurrences[top, :][:, top].todense()
            occurrences = doc_occurrences[top]
            values = np.log(
                (co_occurrences * documents_number + co_occurrences_smooth)
                / (occurrences[:, np.newaxis] * occurrences[np.newaxis, :] + co_occurrences_smooth)
            )
            diag = np.diag_indices(len(values))
            # values.cumsum(axis=0).cumsum(axis=1)[diag] - values[diag].cumsum()

            current_pmi = np.array(
               values.cumsum(axis=0).cumsum(axis=1)[diag] - values[diag].cumsum()
            ).ravel()
            topic_pmis[t] = current_pmi
            pmi += current_pmi

            values[values < 0.] = 0.
            current_ppmi = np.array(
               values.cumsum(axis=0).cumsum(axis=1)[diag] - values[diag].cumsum()
            ).ravel()
            topic_ppmis[t] = current_ppmi
            ppmi += current_ppmi
            
        sizes = np.arange(2, max_top_size + 1)
        pmi[1:] /= (T * sizes * (sizes - 1))
        ppmi[1:] /= (T * sizes * (sizes - 1))
        indices = np.array(top_sizes) - 1

        for t in topic_indices:
            topic_pmis[t][1:] /= (sizes * (sizes - 1))
            topic_ppmis[t][1:] /= (sizes * (sizes - 1))

        result_topic_pmis = {t: p[indices] for t, p in topic_pmis.items()}
        result_topic_ppmis = {t: p[indices] for t, p in topic_ppmis.items()}

        return pmi[indices], ppmi[indices], result_topic_pmis, result_topic_ppmis

    return func

In [32]:
%%time

occurences, co_occurences = calc_doc_occurrences(DATASET, MAIN_MODALITY)

CPU times: user 4.45 s, sys: 131 ms, total: 4.58 s
Wall time: 4.53 s

In [33]:
co_occurences.shape

(22608, 22608)

In [34]:
calc_pmi = create_pmi_top_function(
    occurences, co_occurences,
    DATASET.get_dataset().shape[0], [20],
    topic_indices=[0, 1, 2],
    co_occurrences_smooth=1e-2,
)

In [35]:
import copy


class TopTokenCoherence(BaseTopicNetScore):
    def __init__(self, name, func):
        super().__init__()

        self._name = name
        self.calc_pmi = func

    @property
    def name(self):
        return self._name

    def call(self, model: TopicModel):
        values = self.calc_pmi(model.get_phi_dense()[0].T)

        return values[1]

    def call_by_topic(self, model: TopicModel):
        values = self.calc_pmi(model.get_phi_dense()[0].T)

        return values[3]

    def compute(
            self,
            model,
            topics: List[str] = None,
            documents: List[str] = None) -> Dict[str, float]:

        values = self.call_by_topic(model)

        phi = model.get_phi()

        if topics is None:
            topics = list(phi.columns)

            if hasattr(model, 'has_bcg'):
                print(f'Detected bcg topics! Skipping for coherence computation (and will have {len(topics) - 1} topics).')

                topics = topics[:-1]
        else:
            assert False

        index2topic = {phi.columns.get_loc(t): t for t in topics}
        topic2index = {t: i for i, t in index2topic.items()}

        if hasattr(model, 'has_bcg'):
            assert list(index2topic.keys()) == list(values.keys())[:-1]
        else:
            assert list(index2topic.keys()) == list(values.keys())

        result = {
            t: float(values[topic2index[t]])
            for t in topics
        }

        assert len(result) == len(index2topic)

        return result

    def _attach(self, model: TopicModel):
        if self._name in model.custom_scores:
            print(
                f'Score with such name "{self._name}" already attached to model!'
                f' So rewriting it...'
                f' All model\'s custom scores: {list(model.custom_scores.keys())}'
            )

        # TODO: TopicModel should provide ability to add custom scores
        model.custom_scores[self.name] = copy.deepcopy(self)

## Experiment<a id="experiment"></a>

Finally we are getting to the main part!)

### Scores (for Topics and Models)<a id="scores"></a>

<div style="text-align: right">Back to <a href=#contents>Contents</a></div>

Here we define a lot of scores (which mainly differ in initial parameters).

In [36]:
ONE_MODEL_NUM_TOPICS = 50
NUM_TOP_WORDS = 20

In [37]:
top = NUM_TOP_WORDS
target_topic_indices = list(range(ONE_MODEL_NUM_TOPICS))

coherence_score = TopTokenCoherence(
    name=f'coherence_{top}',
    func=create_pmi_top_function(
        occurences, co_occurences,
        DATASET.get_dataset().shape[0], [top],
        # topic_indices=target_topic_indices,
        co_occurrences_smooth=1e-2,
    )
)

intra_coherence_score = IntratextCoherenceScore(
    name='toplen_ptw',
    data=DATASET,
    computation_method=ComputationMethod.SEGMENT_LENGTH,
    word_topic_relatedness=WordTopicRelatednessType.PTW,
    should_compute=False,
)

diversity_scores = [
    DiversityScore(
        name=f'diversity_{metric}',
        metric=metric,
        class_ids=MAIN_MODALITY,
    )

    for metric in KNOWN_METRICS
]

Other coherence score variations

And a pair of default ARTM scores (these ones are fast)

In [38]:
other_scores = [
    PerplexityScore(
        name='perplexity'
    ),
]

### Bank Creation<a id="bank-creation"></a>

<div style="text-align: right">Back to <a href=#contents>Contents</a></div>

Here we finally run the experiment!

In [39]:
NUM_ITERATIONS = 20

In [40]:
seed = 0

In [39]:
# We use only one train function here
# Other variations are also possible
# It would be even better to make bank using several train functions
# However, it would also take way more time 

TRAIN_FUNCS = default_train_func  # default train func

In [40]:
DATASET_INTERNALS_FOLDER_PATH

'./MKB_10__internals'

In [41]:
SEARCH_RESULTS_FOLDER_PATH = os.path.join(
    DATASET_INTERNALS_FOLDER_PATH, 'result'
)

# File with some info about the process
SEARCH_RESULT_FILE_PATH = os.path.join(
    SEARCH_RESULTS_FOLDER_PATH, f'search_result__{seed}.json'
)

# Bank, with topics and their score values
BANK_FOLDER_PATH = os.path.join(
    SEARCH_RESULTS_FOLDER_PATH, f'bank__{seed}'
)

In [42]:
! echo $DATASET_INTERNALS_FOLDER_PATH
! ls -alh $DATASET_INTERNALS_FOLDER_PATH

./MKB_10__internals
total 50M
drwxrwxr-x  3 alekseev_v mil_lab 4,0K мар 26 18:06 .
drwxrwxr-x 10 alekseev_v mil_lab 4,0K мар 26 18:06 ..
drwxrwxr-x  2 alekseev_v mil_lab 4,0K мар 26 18:06 batches
-rw-rw-r--  1 alekseev_v mil_lab  14M мар 26 18:06 dict.dict
-rw-rw-r--  1 alekseev_v mil_lab  36M мар 26 18:06 vw.txt

In [43]:
SEARCH_RESULTS_FOLDER_PATH

'./MKB_10__internals/result'

In [44]:
! ls $SEARCH_RESULTS_FOLDER_PATH

ls: cannot access './MKB_10__internals/result': No such file or directory

In [45]:
BANK_FOLDER_PATH

'./MKB_10__internals/result/bank__0'

In [46]:
os.makedirs(SEARCH_RESULTS_FOLDER_PATH, exist_ok=True)
os.makedirs(BANK_FOLDER_PATH, exist_ok=True)

In [47]:
seed

0

One cay vary some parameters below (for example `max_num_models` and `num_fit_iterations`).

In [48]:
optimizer = TopicBankMethod(
    data        = DATASET,
    main_modality = MAIN_MODALITY,
    
    min_df_rate = 0.0,  # dictionary filtering has already been done little earlier
    max_df_rate = 1.0,  #   so we don't want these parameters to have any effect

    main_topic_score   = coherence_score,
    other_topic_scores = [],
    other_scores       = [coherence_score] + diversity_scores + other_scores,
   # documents          = TEST_DOCUMENTS,

    start_model_number   = 0,
    max_num_models       = 20,
    one_model_num_topics = ONE_MODEL_NUM_TOPICS,  # 100,
    num_fit_iterations   = NUM_ITERATIONS,  # 100,  # 100 should be enough;
                                 # however, for big data better to reduce this one
                                 # (otherwise the process will be too slow)

    topic_score_threshold_percentile = 90,

    save_bank         = True,
    save_model_topics = True,
    save_file_path    = SEARCH_RESULT_FILE_PATH,
    bank_folder_path  = BANK_FOLDER_PATH,

    train_funcs = TRAIN_FUNCS,
    
    verbose = True,
)

# TODO: use Holdout Perplexity as Stop score

In [49]:
optimizer._result.keys()

dict_keys(['optimum', 'optimum_std', 'bank_scores', 'bank_topic_scores', 'model_scores', 'model_topic_scores', 'num_bank_topics', 'num_model_topics'])

Checking file paths

In [50]:
! echo $DATASET_INTERNALS_FOLDER_PATH
! ls $DATASET_INTERNALS_FOLDER_PATH

./MKB_10__internals
batches  dict.dict  result  vw.txt

In [51]:
optimizer._save_file_path

'./MKB_10__internals/result/search_result__0.json'

In [52]:
optimizer._topic_bank._path

'./MKB_10__internals/result/bank__0'

Fulfilling the search (get ready for a really long process!):

In [53]:
%%time

optimizer.search_for_optimum(DATASET)

  0%|                                                        | 0/20 [00:00<?, ?it/s]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.68it/s]

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 21241.265625, 'coherence_20': 0.8081201365408722, 'diversity_euclidean': 0.05506040320149122, 'diversity_jensenshannon': 0.6354163678904116, 'diversity_hellinger': 0.7312635303582865, 'diversity_cosine': 0.7721177167251074, 'perplexity': 21241.265625, 'ppl_fair': 21241.265625, 'ppl_cheatty': 4079.3203125}
  5%|██▍                                             | 1/20 [00:34<11:00, 34.75s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.83it/s]

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 21241.265625, 'coherence_20': 0.8081201365408722, 'diversity_euclidean': 0.05506040320149122, 'diversity_jensenshannon': 0.6354163678903747, 'diversity_hellinger': 0.7312635303582171, 'diversity_cosine': 0.7721177167251073, 'perplexity': 21241.265625, 'ppl_fair': 21241.265625, 'ppl_cheatty': 4079.3203125}
 10%|████▊                                           | 2/20 [01:18<12:00, 40.01s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.49it/s]

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 14910.55859375, 'coherence_20': 0.8319214169868356, 'diversity_euclidean': 0.050882752798304065, 'diversity_jensenshannon': 0.5908506303660231, 'diversity_hellinger': 0.6754768331753311, 'diversity_cosine': 0.678184586982741, 'perplexity': 14910.55859375, 'ppl_fair': 14910.55859375, 'ppl_cheatty': 3891.197998046875}
 15%|███████▏                                        | 3/20 [02:02<11:51, 41.85s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.51it/s]

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 10540.126953125, 'coherence_20': 0.8607254209834689, 'diversity_euclidean': 0.056005511239171656, 'diversity_jensenshannon': 0.6203031231775662, 'diversity_hellinger': 0.7149328174444869, 'diversity_cosine': 0.7388865883514599, 'perplexity': 10540.126953125, 'ppl_fair': 10540.126953125, 'ppl_cheatty': 3703.18603515625}
 20%|█████████▌                                      | 4/20 [02:46<11:25, 42.82s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.16it/s]

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 10540.126953125, 'coherence_20': 0.8607254209834689, 'diversity_euclidean': 0.056005511239171656, 'diversity_jensenshannon': 0.6203031231775654, 'diversity_hellinger': 0.7149328174444802, 'diversity_cosine': 0.7388865883514599, 'perplexity': 10540.126953125, 'ppl_fair': 10540.126953125, 'ppl_cheatty': 3703.18603515625}
 25%|████████████                                    | 5/20 [03:30<10:49, 43.29s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.21it/s]

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 10540.126953125, 'coherence_20': 0.8607254209834689, 'diversity_euclidean': 0.05600551123917205, 'diversity_jensenshannon': 0.6203031231778118, 'diversity_hellinger': 0.7149328174447565, 'diversity_cosine': 0.7388865883514625, 'perplexity': 10540.126953125, 'ppl_fair': 10540.126953125, 'ppl_cheatty': 3703.18603515625}
 30%|██████████████▍                                 | 6/20 [04:15<10:10, 43.59s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.24it/s]

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 8085.08203125, 'coherence_20': 0.8394475223200253, 'diversity_euclidean': 0.05665779232180361, 'diversity_jensenshannon': 0.6221001896211437, 'diversity_hellinger': 0.7183953362601536, 'diversity_cosine': 0.7509117236751133, 'perplexity': 8085.08203125, 'ppl_fair': 8085.08203125, 'ppl_cheatty': 3604.729736328125}
 35%|████████████████▊                               | 7/20 [05:00<09:32, 44.07s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.85it/s]

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 8085.08203125, 'coherence_20': 0.8394475223200253, 'diversity_euclidean': 0.056657792321794395, 'diversity_jensenshannon': 0.6221001896196284, 'diversity_hellinger': 0.7183953362607316, 'diversity_cosine': 0.7509117236734641, 'perplexity': 8085.08203125, 'ppl_fair': 8085.08203125, 'ppl_cheatty': 3604.7294921875}
 40%|███████████████████▏                            | 8/20 [05:44<08:50, 44.21s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.23it/s]

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 8085.08203125, 'coherence_20': 0.8394475223200253, 'diversity_euclidean': 0.0566577923218046, 'diversity_jensenshannon': 0.622100189621167, 'diversity_hellinger': 0.7183953362607198, 'diversity_cosine': 0.7509117236751122, 'perplexity': 8085.08203125, 'ppl_fair': 8085.08203125, 'ppl_cheatty': 3604.729736328125}
 45%|█████████████████████▌                          | 9/20 [06:29<08:08, 44.38s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.24it/s]

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 6776.9052734375, 'coherence_20': 0.8462748392332191, 'diversity_euclidean': 0.05650286551732751, 'diversity_jensenshannon': 0.6213988557024575, 'diversity_hellinger': 0.7187754072059847, 'diversity_cosine': 0.7587374014533105, 'perplexity': 6776.9052734375, 'ppl_fair': 6776.9052734375, 'ppl_cheatty': 3492.67138671875}
 50%|███████████████████████▌                       | 10/20 [07:15<07:28, 44.80s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.17it/s]

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 6776.9052734375, 'coherence_20': 0.8462748392332191, 'diversity_euclidean': 0.05650286551732751, 'diversity_jensenshannon': 0.6213988557024624, 'diversity_hellinger': 0.7187754072059748, 'diversity_cosine': 0.7587374014533104, 'perplexity': 6776.9052734375, 'ppl_fair': 6776.9052734375, 'ppl_cheatty': 3492.671142578125}
 55%|█████████████████████████▊                     | 11/20 [08:00<06:43, 44.88s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.22it/s]

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 6776.9052734375, 'coherence_20': 0.8462748392332191, 'diversity_euclidean': 0.05650286551732751, 'diversity_jensenshannon': 0.621398855702462, 'diversity_hellinger': 0.7187754072059737, 'diversity_cosine': 0.7587374014533104, 'perplexity': 6776.9052734375, 'ppl_fair': 6776.9052734375, 'ppl_cheatty': 3492.67138671875}
 60%|████████████████████████████▏                  | 12/20 [08:45<05:59, 44.98s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.21it/s]

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 6776.9052734375, 'coherence_20': 0.8462748392332191, 'diversity_euclidean': 0.05650286551732662, 'diversity_jensenshannon': 0.6213988557023435, 'diversity_hellinger': 0.7187754072054063, 'diversity_cosine': 0.7587374014533048, 'perplexity': 6776.9052734375, 'ppl_fair': 6776.9052734375, 'ppl_cheatty': 3492.671142578125}
 65%|██████████████████████████████▌                | 13/20 [09:30<05:15, 45.02s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.22it/s]

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 6776.9052734375, 'coherence_20': 0.8462748392332191, 'diversity_euclidean': 0.05650286551732782, 'diversity_jensenshannon': 0.6213988557025226, 'diversity_hellinger': 0.7187754072060137, 'diversity_cosine': 0.7587374014533451, 'perplexity': 6776.9052734375, 'ppl_fair': 6776.9052734375, 'ppl_cheatty': 3492.67138671875}
 70%|████████████████████████████████▉              | 14/20 [10:15<04:30, 45.13s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.21it/s]

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 6776.9052734375, 'coherence_20': 0.8462748392332191, 'diversity_euclidean': 0.05650286551732937, 'diversity_jensenshannon': 0.6213988557023938, 'diversity_hellinger': 0.7187754072067657, 'diversity_cosine': 0.7587374014532831, 'perplexity': 6776.9052734375, 'ppl_fair': 6776.9052734375, 'ppl_cheatty': 3492.67138671875}
 75%|███████████████████████████████████▎           | 15/20 [11:01<03:46, 45.23s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.23it/s]

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 6776.9052734375, 'coherence_20': 0.8462748392332191, 'diversity_euclidean': 0.05650286551732751, 'diversity_jensenshannon': 0.6213988557024577, 'diversity_hellinger': 0.7187754072059778, 'diversity_cosine': 0.7587374014533105, 'perplexity': 6776.9052734375, 'ppl_fair': 6776.9052734375, 'ppl_cheatty': 3492.67138671875}
 80%|█████████████████████████████████████▌         | 16/20 [11:46<03:01, 45.30s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.22it/s]

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 6776.9052734375, 'coherence_20': 0.8462748392332191, 'diversity_euclidean': 0.05650286551732937, 'diversity_jensenshannon': 0.6213988557023914, 'diversity_hellinger': 0.718775407206764, 'diversity_cosine': 0.7587374014532831, 'perplexity': 6776.9052734375, 'ppl_fair': 6776.9052734375, 'ppl_cheatty': 3492.67138671875}
 85%|███████████████████████████████████████▉       | 17/20 [12:31<02:15, 45.20s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.20it/s]

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 6776.9052734375, 'coherence_20': 0.8462748392332191, 'diversity_euclidean': 0.056502865517326945, 'diversity_jensenshannon': 0.6213988557023823, 'diversity_hellinger': 0.7187754072054094, 'diversity_cosine': 0.7587374014533397, 'perplexity': 6776.9052734375, 'ppl_fair': 6776.9052734375, 'ppl_cheatty': 3492.67138671875}
 90%|██████████████████████████████████████████▎    | 18/20 [13:16<01:30, 45.16s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.19it/s]

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 6776.9052734375, 'coherence_20': 0.8462748392332191, 'diversity_euclidean': 0.05650286551732751, 'diversity_jensenshannon': 0.6213988557024607, 'diversity_hellinger': 0.7187754072059701, 'diversity_cosine': 0.7587374014533104, 'perplexity': 6776.9052734375, 'ppl_fair': 6776.9052734375, 'ppl_cheatty': 3492.67138671875}
 95%|████████████████████████████████████████████▋  | 19/20 [14:02<00:45, 45.19s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.23it/s]

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 6776.9052734375, 'coherence_20': 0.8462748392332191, 'diversity_euclidean': 0.05650286551732751, 'diversity_jensenshannon': 0.6213988557024641, 'diversity_hellinger': 0.7187754072059787, 'diversity_cosine': 0.7587374014533104, 'perplexity': 6776.9052734375, 'ppl_fair': 6776.9052734375, 'ppl_cheatty': 3492.67138671875}
100%|███████████████████████████████████████████████| 20/20 [14:47<00:00, 44.38s/it]
CPU times: user 22min 52s, sys: 44.7 s, total: 23min 37s
Wall time: 14min 47s

What topics we have in bank

In [54]:
optimizer._topic_bank.view_topics().head()

                     topic_0  topic_1       topic_2  topic_3  topic_4  topic_5
@text cdk                0.0      0.0  0.000000e+00      0.0      0.0      0.0
      внутриядерный      0.0      0.0  0.000000e+00      0.0      0.0      0.0
      соотнесение        0.0      0.0  0.000000e+00      0.0      0.0      0.0
      ангиоматозный      0.0      0.0  0.000000e+00      0.0      0.0      0.0
      хориоменингит      0.0      0.0  2.496385e-10      0.0      0.0      0.0

In [55]:
bank_topics = optimizer._topic_bank.view_topics()

In [56]:
bank_topics.shape

(22608, 6)

In [57]:
bank_topics.head()

                     topic_0  topic_1       topic_2  topic_3  topic_4  topic_5
@text cdk                0.0      0.0  0.000000e+00      0.0      0.0      0.0
      внутриядерный      0.0      0.0  0.000000e+00      0.0      0.0      0.0
      соотнесение        0.0      0.0  0.000000e+00      0.0      0.0      0.0
      ангиоматозный      0.0      0.0  0.000000e+00      0.0      0.0      0.0
      хориоменингит      0.0      0.0  2.496385e-10      0.0      0.0      0.0

In [60]:
bank_topics['topic_5'].sort_values(ascending=False)[:20]

@text  сустав           0.023555
       перелом          0.014489
       позвоночник      0.007490
       мышца            0.006477
       повреждение      0.006326
       артрит           0.006243
       травма           0.005468
       бедро            0.005148
       метод            0.004821
       нагрузка         0.004438
       головка          0.004422
       вывих            0.004291
       ткань            0.004209
       боль             0.004062
       нарушение        0.003741
       движение         0.003654
       тазобедренный    0.003606
       деформация       0.003596
       позвонок         0.003568
       положение        0.003560
Name: topic_5, dtype: float64

And topic scores

In [59]:
optimizer._topic_bank.view_topic_scores()

,topic_0,topic_1,topic_2,topic_3,topic_4,topic_5
kernel_size,3076.000000,3056.000000,2987.000000,2784.000000,2726.000000,2846.000000
coherence_20,0.822205,0.794035,0.879524,0.947137,0.754336,0.880411
distance_to_nearest,0.000000,0.839263,0.761336,0.822013,0.762815,0.764102

All models are also saved (topics as $\Phi$ matrices and topic score values)

In [69]:
! ls $optimizer._topic_bank._path

model_0__phi.bin	    model_19__topic_scores.bin
model_0__topic_scores.bin   model_1__phi.bin
model_10__phi.bin	    model_1__topic_scores.bin
model_10__topic_scores.bin  model_2__phi.bin
model_11__phi.bin	    model_2__topic_scores.bin
model_11__topic_scores.bin  model_3__phi.bin
model_12__phi.bin	    model_3__topic_scores.bin
model_12__topic_scores.bin  model_4__phi.bin
model_13__phi.bin	    model_4__topic_scores.bin
model_13__topic_scores.bin  model_5__phi.bin
model_14__phi.bin	    model_5__topic_scores.bin
model_14__topic_scores.bin  model_6__phi.bin
model_15__phi.bin	    model_6__topic_scores.bin
model_15__topic_scores.bin  model_7__phi.bin
model_16__phi.bin	    model_7__topic_scores.bin
model_16__topic_scores.bin  model_8__phi.bin
model_17__phi.bin	    model_8__topic_scores.bin
model_17__topic_scores.bin  model_9__phi.bin
model_18__phi.bin	    model_9__topic_scores.bin
model_18__topic_scores.bin  topics.bin
model_19__phi.bin	    topic_scores.bin

In [61]:
optimizer._result.keys()

dict_keys(['optimum', 'optimum_std', 'bank_scores', 'bank_topic_scores', 'model_scores', 'model_topic_scores', 'num_bank_topics', 'num_model_topics'])

In [62]:
optimizer._result['num_bank_topics']

[2, 2, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6]

In [63]:
len(optimizer._result['bank_topic_scores'])

20

In [64]:
optimizer._result

{'optimum': 6,
 'optimum_std': 0.0,
 'bank_scores': [{'perplexity_score': 21241.265625,
   'coherence_20': 0.8081201365408722,
   'diversity_euclidean': 0.05506040320149122,
   'diversity_jensenshannon': 0.6354163678904116,
   'diversity_hellinger': 0.7312635303582865,
   'diversity_cosine': 0.7721177167251074,
   'perplexity': 21241.265625,
   'ppl_fair': 21241.265625,
   'ppl_cheatty': 4079.3203125},
  {'perplexity_score': 21241.265625,
   'coherence_20': 0.8081201365408722,
   'diversity_euclidean': 0.05506040320149122,
   'diversity_jensenshannon': 0.6354163678903747,
   'diversity_hellinger': 0.7312635303582171,
   'diversity_cosine': 0.7721177167251073,
   'perplexity': 21241.265625,
   'ppl_fair': 21241.265625,
   'ppl_cheatty': 4079.3203125},
  {'perplexity_score': 14910.55859375,
   'coherence_20': 0.8319214169868356,
   'diversity_euclidean': 0.050882752798304065,
   'diversity_jensenshannon': 0.5908506303660231,
   'diversity_hellinger': 0.6754768331753311,
   'diversity_cosine': 0.678184586982741,
   'perplexity': 14910.55859375,
   'ppl_fair': 14910.55859375,
   'ppl_cheatty': 3891.197998046875},
  {'perplexity_score': 10540.126953125,
   'coherence_20': 0.8607254209834689,
   'diversity_euclidean': 0.056005511239171656,
   'diversity_jensenshannon': 0.6203031231775662,
   'diversity_hellinger': 0.7149328174444869,
   'diversity_cosine': 0.7388865883514599,
   'perplexity': 10540.126953125,
   'ppl_fair': 10540.126953125,
   'ppl_cheatty': 3703.18603515625},
  {'perplexity_score': 10540.126953125,
   'coherence_20': 0.8607254209834689,
   'diversity_euclidean': 0.056005511239171656,
   'diversity_jensenshannon': 0.6203031231775654,
   'diversity_hellinger': 0.7149328174444802,
   'diversity_cosine': 0.7388865883514599,
   'perplexity': 10540.126953125,
   'ppl_fair': 10540.126953125,
   'ppl_cheatty': 3703.18603515625},
  {'perplexity_score': 10540.126953125,
   'coherence_20': 0.8607254209834689,
   'diversity_euclidean': 0.05600551123917205,
   'diversity_jensenshannon': 0.6203031231778118,
   'diversity_hellinger': 0.7149328174447565,
   'diversity_cosine': 0.7388865883514625,
   'perplexity': 10540.126953125,
   'ppl_fair': 10540.126953125,
   'ppl_cheatty': 3703.18603515625},
  {'perplexity_score': 8085.08203125,
   'coherence_20': 0.8394475223200253,
   'diversity_euclidean': 0.05665779232180361,
   'diversity_jensenshannon': 0.6221001896211437,
   'diversity_hellinger': 0.7183953362601536,
   'diversity_cosine': 0.7509117236751133,
   'perplexity': 8085.08203125,
   'ppl_fair': 8085.08203125,
   'ppl_cheatty': 3604.729736328125},
  {'perplexity_score': 8085.08203125,
   'coherence_20': 0.8394475223200253,
   'diversity_euclidean': 0.056657792321794395,
   'diversity_jensenshannon': 0.6221001896196284,
   'diversity_hellinger': 0.7183953362607316,
   'diversity_cosine': 0.7509117236734641,
   'perplexity': 8085.08203125,
   'ppl_fair': 8085.08203125,
   'ppl_cheatty': 3604.7294921875},
  {'perplexity_score': 8085.08203125,
   'coherence_20': 0.8394475223200253,
   'diversity_euclidean': 0.0566577923218046,
   'diversity_jensenshannon': 0.622100189621167,
   'diversity_hellinger': 0.7183953362607198,
   'diversity_cosine': 0.7509117236751122,
   'perplexity': 8085.08203125,
   'ppl_fair': 8085.08203125,
   'ppl_cheatty': 3604.729736328125},
  {'perplexity_score': 6776.9052734375,
   'coherence_20': 0.8462748392332191,
   'diversity_euclidean': 0.05650286551732751,
   'diversity_jensenshannon': 0.6213988557024575,
   'diversity_hellinger': 0.7187754072059847,
   'diversity_cosine': 0.7587374014533105,
   'perplexity': 6776.9052734375,
   'ppl_fair': 6776.9052734375,
   'ppl_cheatty': 3492.67138671875},
  {'perplexity_score': 6776.9052734375,
   'coherence_20': 0.8462748392332191,
   'diversity_euclidean': 0.05650286551732751,
   'diversity_jensenshannon': 0.6213988557024624,
   'diversity_hellinger': 0.7187754072059748,
   'diversity_cosine': 0.7587374014533104,
   'perplexity': 6776.9052734375,
   'ppl_fair': 6776.9052734375,
   'ppl_cheatty': 3492.671142578125},
  {'perplexity_score': 6776.9052734375,
   'coherence_20': 0.8462748392332191,
   'diversity_euclidean': 0.05650286551732751,
   'diversity_jensenshannon': 0.621398855702462,
   'diversity_hellinger': 0.7187754072059737,
   'diversity_cosine': 0.7587374014533104,
   'perplexity': 6776.9052734375,
   'ppl_fair': 6776.9052734375,
   'ppl_cheatty': 3492.67138671875},
  {'perplexity_score': 6776.9052734375,
   'coherence_20': 0.8462748392332191,
   'diversity_euclidean': 0.05650286551732662,
   'diversity_jensenshannon': 0.6213988557023435,
   'diversity_hellinger': 0.7187754072054063,
   'diversity_cosine': 0.7587374014533048,
   'perplexity': 6776.9052734375,
   'ppl_fair': 6776.9052734375,
   'ppl_cheatty': 3492.671142578125},
  {'perplexity_score': 6776.9052734375,
   'coherence_20': 0.8462748392332191,
   'diversity_euclidean': 0.05650286551732782,
   'diversity_jensenshannon': 0.6213988557025226,
   'diversity_hellinger': 0.7187754072060137,
   'diversity_cosine': 0.7587374014533451,
   'perplexity': 6776.9052734375,
   'ppl_fair': 6776.9052734375,
   'ppl_cheatty': 3492.67138671875},
  {'perplexity_score': 6776.9052734375,
   'coherence_20': 0.8462748392332191,
   'diversity_euclidean': 0.05650286551732937,
   'diversity_jensenshannon': 0.6213988557023938,
   'diversity_hellinger': 0.7187754072067657,
   'diversity_cosine': 0.7587374014532831,
   'perplexity': 6776.9052734375,
   'ppl_fair': 6776.9052734375,
   'ppl_cheatty': 3492.67138671875},
  {'perplexity_score': 6776.9052734375,
   'coherence_20': 0.8462748392332191,
   'diversity_euclidean': 0.05650286551732751,
   'diversity_jensenshannon': 0.6213988557024577,
   'diversity_hellinger': 0.7187754072059778,
   'diversity_cosine': 0.7587374014533105,
   'perplexity': 6776.9052734375,
   'ppl_fair': 6776.9052734375,
   'ppl_cheatty': 3492.67138671875},
  {'perplexity_score': 6776.9052734375,
   'coherence_20': 0.8462748392332191,
   'diversity_euclidean': 0.05650286551732937,
   'diversity_jensenshannon': 0.6213988557023914,
   'diversity_hellinger': 0.718775407206764,
   'diversity_cosine': 0.7587374014532831,
   'perplexity': 6776.9052734375,
   'ppl_fair': 6776.9052734375,
   'ppl_cheatty': 3492.67138671875},
  {'perplexity_score': 6776.9052734375,
   'coherence_20': 0.8462748392332191,
   'diversity_euclidean': 0.056502865517326945,
   'diversity_jensenshannon': 0.6213988557023823,
   'diversity_hellinger': 0.7187754072054094,
   'diversity_cosine': 0.7587374014533397,
   'perplexity': 6776.9052734375,
   'ppl_fair': 6776.9052734375,
   'ppl_cheatty': 3492.67138671875},
  {'perplexity_score': 6776.9052734375,
   'coherence_20': 0.8462748392332191,
   'diversity_euclidean': 0.05650286551732751,
   'diversity_jensenshannon': 0.6213988557024607,
   'diversity_hellinger': 0.7187754072059701,
   'diversity_cosine': 0.7587374014533104,
   'perplexity': 6776.9052734375,
   'ppl_fair': 6776.9052734375,
   'ppl_cheatty': 3492.67138671875},
  {'perplexity_score': 6776.9052734375,
   'coherence_20': 0.8462748392332191,
   'diversity_euclidean': 0.05650286551732751,
   'diversity_jensenshannon': 0.6213988557024641,
   'diversity_hellinger': 0.7187754072059787,
   'diversity_cosine': 0.7587374014533104,
   'perplexity': 6776.9052734375,
   'ppl_fair': 6776.9052734375,
   'ppl_cheatty': 3492.67138671875}],
 'bank_topic_scores': [[{'kernel_size': 3076,
    'coherence_20': 0.8222052116329212,
    'distance_to_nearest': 0.0},
   {'kernel_size': 3056,
    'coherence_20': 0.7940350614488233,
    'distance_to_nearest': 0.8392634795276617}],
  [{'kernel_size': 3076,
    'coherence_20': 0.8222052116329212,
    'distance_to_nearest': 0.0},
   {'kernel_size': 3056,
    'coherence_20': 0.7940350614488233,
    'distance_to_nearest': 0.8392634795276617}],
  [{'kernel_size': 3076,
    'coherence_20': 0.8222052116329212,
    'distance_to_nearest': 0.0},
   {'kernel_size': 3056,
    'coherence_20': 0.7940350614488233,
    'distance_to_nearest': 0.8392634795276617},
   {'kernel_size': 2987,
    'coherence_20': 0.8795239778787624,
    'distance_to_nearest': 0.761336366429392}],
  [{'kernel_size': 3076,
    'coherence_20': 0.8222052116329212,
    'distance_to_nearest': 0.0},
   {'kernel_size': 3056,
    'coherence_20': 0.7940350614488233,
    'distance_to_nearest': 0.8392634795276617},
   {'kernel_size': 2987,
    'coherence_20': 0.8795239778787624,
    'distance_to_nearest': 0.761336366429392},
   {'kernel_size': 2784,
    'coherence_20': 0.9471374329733692,
    'distance_to_nearest': 0.8220129884323184}],
  [{'kernel_size': 3076,
    'coherence_20': 0.8222052116329212,
    'distance_to_nearest': 0.0},
   {'kernel_size': 3056,
    'coherence_20': 0.7940350614488233,
    'distance_to_nearest': 0.8392634795276617},
   {'kernel_size': 2987,
    'coherence_20': 0.8795239778787624,
    'distance_to_nearest': 0.761336366429392},
   {'kernel_size': 2784,
    'coherence_20': 0.9471374329733692,
    'distance_to_nearest': 0.8220129884323184}],
  [{'kernel_size': 3076,
    'coherence_20': 0.8222052116329212,
    'distance_to_nearest': 0.0},
   {'kernel_size': 3056,
    'coherence_20': 0.7940350614488233,
    'distance_to_nearest': 0.8392634795276617},
   {'kernel_size': 2987,
    'coherence_20': 0.8795239778787624,
    'distance_to_nearest': 0.761336366429392},
   {'kernel_size': 2784,
    'coherence_20': 0.9471374329733692,
    'distance_to_nearest': 0.8220129884323184}],
  [{'kernel_size': 3076,
    'coherence_20': 0.8222052116329212,
    'distance_to_nearest': 0.0},
   {'kernel_size': 3056,
    'coherence_20': 0.7940350614488233,
    'distance_to_nearest': 0.8392634795276617},
   {'kernel_size': 2987,
    'coherence_20': 0.8795239778787624,
    'distance_to_nearest': 0.761336366429392},
   {'kernel_size': 2784,
    'coherence_20': 0.9471374329733692,
    'distance_to_nearest': 0.8220129884323184},
   {'kernel_size': 2726,
    'coherence_20': 0.7543359276662507,
    'distance_to_nearest': 0.7628150889638984}],
  [{'kernel_size': 3076,
    'coherence_20': 0.8222052116329212,
    'distance_to_nearest': 0.0},
   {'kernel_size': 3056,
    'coherence_20': 0.7940350614488233,
    'distance_to_nearest': 0.8392634795276617},
   {'kernel_size': 2987,
    'coherence_20': 0.8795239778787624,
    'distance_to_nearest': 0.761336366429392},
   {'kernel_size': 2784,
    'coherence_20': 0.9471374329733692,
    'distance_to_nearest': 0.8220129884323184},
   {'kernel_size': 2726,
    'coherence_20': 0.7543359276662507,
    'distance_to_nearest': 0.7628150889638984}],
  [{'kernel_size': 3076,
    'coherence_20': 0.8222052116329212,
    'distance_to_nearest': 0.0},
   {'kernel_size': 3056,
    'coherence_20': 0.7940350614488233,
    'distance_to_nearest': 0.8392634795276617},
   {'kernel_size': 2987,
    'coherence_20': 0.8795239778787624,
    'distance_to_nearest': 0.761336366429392},
   {'kernel_size': 2784,
    'coherence_20': 0.9471374329733692,
    'distance_to_nearest': 0.8220129884323184},
   {'kernel_size': 2726,
    'coherence_20': 0.7543359276662507,
    'distance_to_nearest': 0.7628150889638984}],
  [{'kernel_size': 3076,
    'coherence_20': 0.8222052116329212,
    'distance_to_nearest': 0.0},
   {'kernel_size': 3056,
    'coherence_20': 0.7940350614488233,
    'distance_to_nearest': 0.8392634795276617},
   {'kernel_size': 2987,
    'coherence_20': 0.8795239778787624,
    'distance_to_nearest': 0.761336366429392},
   {'kernel_size': 2784,
    'coherence_20': 0.9471374329733692,
    'distance_to_nearest': 0.8220129884323184},
   {'kernel_size': 2726,
    'coherence_20': 0.7543359276662507,
    'distance_to_nearest': 0.7628150889638984},
   {'kernel_size': 2846,
    'coherence_20': 0.8804114237991888,
    'distance_to_nearest': 0.7641020653014313}],
  [{'kernel_size': 3076,
    'coherence_20': 0.8222052116329212,
    'distance_to_nearest': 0.0},
   {'kernel_size': 3056,
    'coherence_20': 0.7940350614488233,
    'distance_to_nearest': 0.8392634795276617},
   {'kernel_size': 2987,
    'coherence_20': 0.8795239778787624,
    'distance_to_nearest': 0.761336366429392},
   {'kernel_size': 2784,
    'coherence_20': 0.9471374329733692,
    'distance_to_nearest': 0.8220129884323184},
   {'kernel_size': 2726,
    'coherence_20': 0.7543359276662507,
    'distance_to_nearest': 0.7628150889638984},
   {'kernel_size': 2846,
    'coherence_20': 0.8804114237991888,
    'distance_to_nearest': 0.7641020653014313}],
  [{'kernel_size': 3076,
    'coherence_20': 0.8222052116329212,
    'distance_to_nearest': 0.0},
   {'kernel_size': 3056,
    'coherence_20': 0.7940350614488233,
    'distance_to_nearest': 0.8392634795276617},
   {'kernel_size': 2987,
    'coherence_20': 0.8795239778787624,
    'distance_to_nearest': 0.761336366429392},
   {'kernel_size': 2784,
    'coherence_20': 0.9471374329733692,
    'distance_to_nearest': 0.8220129884323184},
   {'kernel_size': 2726,
    'coherence_20': 0.7543359276662507,
    'distance_to_nearest': 0.7628150889638984},
   {'kernel_size': 2846,
    'coherence_20': 0.8804114237991888,
    'distance_to_nearest': 0.7641020653014313}],
  [{'kernel_size': 3076,
    'coherence_20': 0.8222052116329212,
    'distance_to_nearest': 0.0},
   {'kernel_size': 3056,
    'coherence_20': 0.7940350614488233,
    'distance_to_nearest': 0.8392634795276617},
   {'kernel_size': 2987,
    'coherence_20': 0.8795239778787624,
    'distance_to_nearest': 0.761336366429392},
   {'kernel_size': 2784,
    'coherence_20': 0.9471374329733692,
    'distance_to_nearest': 0.8220129884323184},
   {'kernel_size': 2726,
    'coherence_20': 0.7543359276662507,
    'distance_to_nearest': 0.7628150889638984},
   {'kernel_size': 2846,
    'coherence_20': 0.8804114237991888,
    'distance_to_nearest': 0.7641020653014313}],
  [{'kernel_size': 3076,
    'coherence_20': 0.8222052116329212,
    'distance_to_nearest': 0.0},
   {'kernel_size': 3056,
    'coherence_20': 0.7940350614488233,
    'distance_to_nearest': 0.8392634795276617},
   {'kernel_size': 2987,
    'coherence_20': 0.8795239778787624,
    'distance_to_nearest': 0.761336366429392},
   {'kernel_size': 2784,
    'coherence_20': 0.9471374329733692,
    'distance_to_nearest': 0.8220129884323184},
   {'kernel_size': 2726,
    'coherence_20': 0.7543359276662507,
    'distance_to_nearest': 0.7628150889638984},
   {'kernel_size': 2846,
    'coherence_20': 0.8804114237991888,
    'distance_to_nearest': 0.7641020653014313}],
  [{'kernel_size': 3076,
    'coherence_20': 0.8222052116329212,
    'distance_to_nearest': 0.0},
   {'kernel_size': 3056,
    'coherence_20': 0.7940350614488233,
    'distance_to_nearest': 0.8392634795276617},
   {'kernel_size': 2987,
    'coherence_20': 0.8795239778787624,
    'distance_to_nearest': 0.761336366429392},
   {'kernel_size': 2784,
    'coherence_20': 0.9471374329733692,
    'distance_to_nearest': 0.8220129884323184},
   {'kernel_size': 2726,
    'coherence_20': 0.7543359276662507,
    'distance_to_nearest': 0.7628150889638984},
   {'kernel_size': 2846,
    'coherence_20': 0.8804114237991888,
    'distance_to_nearest': 0.7641020653014313}],
  [{'kernel_size': 3076,
    'coherence_20': 0.8222052116329212,
    'distance_to_nearest': 0.0},
   {'kernel_size': 3056,
    'coherence_20': 0.7940350614488233,
    'distance_to_nearest': 0.8392634795276617},
   {'kernel_size': 2987,
    'coherence_20': 0.8795239778787624,
    'distance_to_nearest': 0.761336366429392},
   {'kernel_size': 2784,
    'coherence_20': 0.9471374329733692,
    'distance_to_nearest': 0.8220129884323184},
   {'kernel_size': 2726,
    'coherence_20': 0.7543359276662507,
    'distance_to_nearest': 0.7628150889638984},
   {'kernel_size': 2846,
    'coherence_20': 0.8804114237991888,
    'distance_to_nearest': 0.7641020653014313}],
  [{'kernel_size': 3076,
    'coherence_20': 0.8222052116329212,
    'distance_to_nearest': 0.0},
   {'kernel_size': 3056,
    'coherence_20': 0.7940350614488233,
    'distance_to_nearest': 0.8392634795276617},
   {'kernel_size': 2987,
    'coherence_20': 0.8795239778787624,
    'distance_to_nearest': 0.761336366429392},
   {'kernel_size': 2784,
    'coherence_20': 0.9471374329733692,
    'distance_to_nearest': 0.8220129884323184},
   {'kernel_size': 2726,
    'coherence_20': 0.7543359276662507,
    'distance_to_nearest': 0.7628150889638984},
   {'kernel_size': 2846,
    'coherence_20': 0.8804114237991888,
    'distance_to_nearest': 0.7641020653014313}],
  [{'kernel_size': 3076,
    'coherence_20': 0.8222052116329212,
    'distance_to_nearest': 0.0},
   {'kernel_size': 3056,
    'coherence_20': 0.7940350614488233,
    'distance_to_nearest': 0.8392634795276617},
   {'kernel_size': 2987,
    'coherence_20': 0.8795239778787624,
    'distance_to_nearest': 0.761336366429392},
   {'kernel_size': 2784,
    'coherence_20': 0.9471374329733692,
    'distance_to_nearest': 0.8220129884323184},
   {'kernel_size': 2726,
    'coherence_20': 0.7543359276662507,
    'distance_to_nearest': 0.7628150889638984},
   {'kernel_size': 2846,
    'coherence_20': 0.8804114237991888,
    'distance_to_nearest': 0.7641020653014313}],
  [{'kernel_size': 3076,
    'coherence_20': 0.8222052116329212,
    'distance_to_nearest': 0.0},
   {'kernel_size': 3056,
    'coherence_20': 0.7940350614488233,
    'distance_to_nearest': 0.8392634795276617},
   {'kernel_size': 2987,
    'coherence_20': 0.8795239778787624,
    'distance_to_nearest': 0.761336366429392},
   {'kernel_size': 2784,
    'coherence_20': 0.9471374329733692,
    'distance_to_nearest': 0.8220129884323184},
   {'kernel_size': 2726,
    'coherence_20': 0.7543359276662507,
    'distance_to_nearest': 0.7628150889638984},
   {'kernel_size': 2846,
    'coherence_20': 0.8804114237991888,
    'distance_to_nearest': 0.7641020653014313}],
  [{'kernel_size': 3076,
    'coherence_20': 0.8222052116329212,
    'distance_to_nearest': 0.0},
   {'kernel_size': 3056,
    'coherence_20': 0.7940350614488233,
    'distance_to_nearest': 0.8392634795276617},
   {'kernel_size': 2987,
    'coherence_20': 0.8795239778787624,
    'distance_to_nearest': 0.761336366429392},
   {'kernel_size': 2784,
    'coherence_20': 0.9471374329733692,
    'distance_to_nearest': 0.8220129884323184},
   {'kernel_size': 2726,
    'coherence_20': 0.7543359276662507,
    'distance_to_nearest': 0.7628150889638984},
   {'kernel_size': 2846,
    'coherence_20': 0.8804114237991888,
    'distance_to_nearest': 0.7641020653014313}]],
 'model_scores': [{'perplexity_score': 2183.57958984375,
   'coherence_20': 0.5553686071210906,
   'diversity_euclidean': 0.04994020510914676,
   'diversity_jensenshannon': 0.5937372211329287,
   'diversity_hellinger': 0.6835495593998556,
   'diversity_cosine': 0.6570792337263397,
   'perplexity': 2183.57958984375},
  {'perplexity_score': 2182.065185546875,
   'coherence_20': 0.5680720371310215,
   'diversity_euclidean': 0.05442068104726088,
   'diversity_jensenshannon': 0.5973725631226747,
   'diversity_hellinger': 0.6877445417877905,
   'diversity_cosine': 0.6964043550767838,
   'perplexity': 2182.065185546875},
  {'perplexity_score': 2160.20263671875,
   'coherence_20': 0.5557402402433392,
   'diversity_euclidean': 0.05219890680903067,
   'diversity_jensenshannon': 0.5977495163128982,
   'diversity_hellinger': 0.6879514693148701,
   'diversity_cosine': 0.683016948130287,
   'perplexity': 2160.20263671875},
  {'perplexity_score': 2158.900390625,
   'coherence_20': 0.5670247870000962,
   'diversity_euclidean': 0.053870415907810956,
   'diversity_jensenshannon': 0.6057371047128031,
   'diversity_hellinger': 0.6978361430978354,
   'diversity_cosine': 0.7023932542083897,
   'perplexity': 2158.900390625},
  {'perplexity_score': 2199.763427734375,
   'coherence_20': 0.5553151756525991,
   'diversity_euclidean': 0.05149166845424965,
   'diversity_jensenshannon': 0.5954730766001558,
   'diversity_hellinger': 0.6851660758386889,
   'diversity_cosine': 0.670250696070002,
   'perplexity': 2199.763427734375},
  {'perplexity_score': 2184.378173828125,
   'coherence_20': 0.5685118821015436,

In [65]:
optimizer._result['bank_topic_scores'][0]

[{'kernel_size': 3076,
  'coherence_20': 0.8222052116329212,
  'distance_to_nearest': 0.0},
 {'kernel_size': 3056,
  'coherence_20': 0.7940350614488233,
  'distance_to_nearest': 0.8392634795276617}]

In [66]:
optimizer._result['model_topic_scores']

[[{'kernel_size': 3208, 'coherence_20': 0.42962387858537326},
  {'kernel_size': 2656, 'coherence_20': 0.7701415600860497},
  {'kernel_size': 3039, 'coherence_20': 0.40759208792425244},
  {'kernel_size': 2954, 'coherence_20': 0.649953932720543},
  {'kernel_size': 2633, 'coherence_20': 0.49802769849553535},
  {'kernel_size': 2987, 'coherence_20': 0.4887999883090705},
  {'kernel_size': 3076,
   'coherence_20': 0.8222052116329212,
   'distance_to_nearest': 0.0},
  {'kernel_size': 3598, 'coherence_20': 0.5338939890004764},
  {'kernel_size': 2839, 'coherence_20': 0.7126840568737308},
  {'kernel_size': 2967, 'coherence_20': 0.5541666824798857},
  {'kernel_size': 3257, 'coherence_20': 0.6344829013287363},
  {'kernel_size': 2618, 'coherence_20': 0.4364507624526562},
  {'kernel_size': 2618, 'coherence_20': 0.7874127543914287},
  {'kernel_size': 2981, 'coherence_20': 0.6213442459066951},
  {'kernel_size': 2569, 'coherence_20': 0.37798571771838246},
  {'kernel_size': 2926, 'coherence_20': 0.48500124462101596},
  {'kernel_size': 3056,
   'coherence_20': 0.7940350614488233,
   'distance_to_nearest': 0.8392634795276617},
  {'kernel_size': 3196, 'coherence_20': 0.6018775126751085},
  {'kernel_size': 3083, 'coherence_20': 0.5565705317622954},
  {'kernel_size': 3198, 'coherence_20': 0.5121320595317724}],
 [{'kernel_size': 3040, 'coherence_20': 0.7627239882615724},
  {'kernel_size': 2968, 'coherence_20': 0.6071893841189011},
  {'kernel_size': 2952, 'coherence_20': 0.3411872834044675},
  {'kernel_size': 2838, 'coherence_20': 0.4467820828340276},
  {'kernel_size': 2906, 'coherence_20': 0.5133054280900867},
  {'kernel_size': 2900, 'coherence_20': 0.5884674679701702},
  {'kernel_size': 3044, 'coherence_20': 0.7566166592486294},
  {'kernel_size': 3129, 'coherence_20': 0.4734190345238171},
  {'kernel_size': 2948, 'coherence_20': 0.5709806439030034},
  {'kernel_size': 2713, 'coherence_20': 0.6958666641224664},
  {'kernel_size': 2883, 'coherence_20': 0.5061710203348446},
  {'kernel_size': 2705, 'coherence_20': 0.7462137316823558},
  {'kernel_size': 3224, 'coherence_20': 0.8343641651596831},
  {'kernel_size': 2994, 'coherence_20': 0.5651634303590395},
  {'kernel_size': 2721, 'coherence_20': 0.6783977585819944},
  {'kernel_size': 3171, 'coherence_20': 0.4842819292557047},
  {'kernel_size': 2675, 'coherence_20': 0.49264268632429903},
  {'kernel_size': 2882, 'coherence_20': 0.45233410584274264},
  {'kernel_size': 2856, 'coherence_20': 0.7222533186553418},
  {'kernel_size': 3194, 'coherence_20': 0.4631118481766318}],
 [{'kernel_size': 2942, 'coherence_20': 0.5273192179072478},
  {'kernel_size': 2878, 'coherence_20': 0.4560709941717536},
  {'kernel_size': 2939, 'coherence_20': 0.487859585128513},
  {'kernel_size': 2838, 'coherence_20': 0.7671496414768496},
  {'kernel_size': 3148, 'coherence_20': 0.3863527192969232},
  {'kernel_size': 2978, 'coherence_20': 0.49826597310962606},
  {'kernel_size': 2932, 'coherence_20': 0.6392971544587822},
  {'kernel_size': 2989, 'coherence_20': 0.5877922663634493},
  {'kernel_size': 2826, 'coherence_20': 0.5182698656838342},
  {'kernel_size': 2652, 'coherence_20': 0.6300586564716256},
  {'kernel_size': 2658, 'coherence_20': 0.6321741710189025},
  {'kernel_size': 2725, 'coherence_20': 0.5046610538310539},
  {'kernel_size': 2987,
   'coherence_20': 0.8795239778787624,
   'distance_to_nearest': 0.761336366429392},
  {'kernel_size': 3208, 'coherence_20': 0.8462121149082416},
  {'kernel_size': 2843, 'coherence_20': 0.4922270828246204},
  {'kernel_size': 3027, 'coherence_20': 0.5841612625794307},
  {'kernel_size': 2770, 'coherence_20': 0.4927111277681048},
  {'kernel_size': 3192, 'coherence_20': 0.6190831086477078},
  {'kernel_size': 3220, 'coherence_20': 0.5042076821081073},
  {'kernel_size': 2739, 'coherence_20': 0.7545327376994595}],
 [{'kernel_size': 2975, 'coherence_20': 0.8004363303114101},
  {'kernel_size': 2926, 'coherence_20': 0.4496730868824798},
  {'kernel_size': 2808, 'coherence_20': 0.7916718826370694},
  {'kernel_size': 2879, 'coherence_20': 0.6437873761114902},
  {'kernel_size': 3252, 'coherence_20': 0.549897581841685},
  {'kernel_size': 3184, 'coherence_20': 0.7746674956240681},
  {'kernel_size': 2780, 'coherence_20': 0.5336606365953984},
  {'kernel_size': 3292, 'coherence_20': 0.6435484336013056},
  {'kernel_size': 3064, 'coherence_20': 0.6842606836607826},
  {'kernel_size': 2492, 'coherence_20': 0.44033301015899007},
  {'kernel_size': 3135, 'coherence_20': 0.47319401809542233},
  {'kernel_size': 2950, 'coherence_20': 0.7066316876220134},
  {'kernel_size': 2647, 'coherence_20': 0.7681838959149119},
  {'kernel_size': 3161, 'coherence_20': 0.5168977963612537},
  {'kernel_size': 2833, 'coherence_20': 0.5391795378846858},
  {'kernel_size': 2383, 'coherence_20': 0.5688216244364873},
  {'kernel_size': 2880, 'coherence_20': 0.5652279495637049},
  {'kernel_size': 2840, 'coherence_20': 0.5172981357934358},
  {'kernel_size': 2784,
   'coherence_20': 0.9471374329733692,
   'distance_to_nearest': 0.8220129884323184},
  {'kernel_size': 3030, 'coherence_20': 0.46188964593958043}],
 [{'kernel_size': 2800, 'coherence_20': 0.4270781626856173},
  {'kernel_size': 3076, 'coherence_20': 0.8730558241986146},
  {'kernel_size': 2968, 'coherence_20': 0.5720245774097046},
  {'kernel_size': 2879, 'coherence_20': 0.5094911535071525},
  {'kernel_size': 2911, 'coherence_20': 0.7766284281920489},
  {'kernel_size': 3254, 'coherence_20': 0.779048349521672},
  {'kernel_size': 2745, 'coherence_20': 0.4896664497294459},
  {'kernel_size': 3012, 'coherence_20': 0.5447003315159206},
  {'kernel_size': 2813, 'coherence_20': 0.5605426004935995},
  {'kernel_size': 3046, 'coherence_20': 0.5590798504093699},
  {'kernel_size': 3155, 'coherence_20': 0.6294632807433939},
  {'kernel_size': 2965, 'coherence_20': 0.6466164495372841},
  {'kernel_size': 3078, 'coherence_20': 0.5515505008958282},
  {'kernel_size': 3166, 'coherence_20': 0.3456959201077594},
  {'kernel_size': 3129, 'coherence_20': 0.7448751092640207},
  {'kernel_size': 2875, 'coherence_20': 0.49992732490298186},
  {'kernel_size': 2692, 'coherence_20': 0.5194555489147279},
  {'kernel_size': 2807, 'coherence_20': 0.7332557535194492},
  {'kernel_size': 2598, 'coherence_20': 0.43045073825022556},
  {'kernel_size': 2785, 'coherence_20': 0.5238941999364215}],
 [{'kernel_size': 2973, 'coherence_20': 0.6383278238115404},
  {'kernel_size': 2915, 'coherence_20': 0.6982045346476534},
  {'kernel_size': 2984, 'coherence_20': 0.5561135815378115},
  {'kernel_size': 2838, 'coherence_20': 0.569809325320072},
  {'kernel_size': 2642, 'coherence_20': 0.5672144388830151},
  {'kernel_size': 2913, 'coherence_20': 0.5219923777776749},
  {'kernel_size': 3091, 'coherence_20': 0.40663744384776795},
  {'kernel_size': 2526, 'coherence_20': 0.4629189981933639},
  {'kernel_size': 2630, 'coherence_20': 0.44929859425468327},
  {'kernel_size': 3077, 'coherence_20': 0.4705465077354253},
  {'kernel_size': 2860, 'coherence_20': 0.7218353599069234},
  {'kernel_size': 2621, 'coherence_20': 0.6053501357342366},
  {'kernel_size': 2977, 'coherence_20': 0.4861430978422706},
  {'kernel_size': 3171, 'coherence_20': 0.5851871598842826},
  {'kernel_size': 3033, 'coherence_20': 0.7334530878752803},
  {'kernel_size': 3049, 'coherence_20': 0.5541288157899437},
  {'kernel_size': 3202, 'coherence_20': 0.830274350839313},
  {'kernel_size': 2758, 'coherence_20': 0.6258122761467004},
  {'kernel_size': 3039, 'coherence_20': 0.7721077885496346},
  {'kernel_size': 3258, 'coherence_20': 0.5076517960405232}],
 [{'kernel_size': 3101, 'coherence_20': 0.4487837915871303},
  {'kernel_size': 2546, 'coherence_20': 0.4786515711476143},
  {'kernel_size': 3278, 'coherence_20': 0.4911241320796483},
  {'kernel_size': 2902, 'coherence_20': 0.521932266651629},
  {'kernel_size': 3199, 'coherence_20': 0.7782710985227281},
  {'kernel_size': 2655, 'coherence_20': 0.6855004761478242},
  {'kernel_size': 2791, 'coherence_20': 0.7461129562473117},
  {'kernel_size': 3215, 'coherence_20': 0.473384053212514},
  {'kernel_size': 2966, 'coherence_20': 0.4808356492665063},
  {'kernel_size': 2749, 'coherence_20': 0.5658120687788545},
  {'kernel_size': 2639, 'coherence_20': 0.428026659711475},
  {'kernel_size': 2846, 'coherence_20': 0.514924913867286},
  {'kernel_size': 2869, 'coherence_20': 0.48582745692219265},
  {'kernel_size': 2920, 'coherence_20': 0.5577400431059907},
  {'kernel_size': 3002, 'coherence_20': 0.5656676386014815},
  {'kernel_size': 3071, 'coherence_20': 0.6529201893160282},
  {'kernel_size': 2782, 'coherence_20': 0.5741055799616075},
  {'kernel_size': 3305, 'coherence_20': 0.34579494289872303},
  {'kernel_size': 2953, 'coherence_20': 0.6326409674441275},
  {'kernel_size': 2726,
   'coherence_20': 0.7543359276662507,
   'distance_to_nearest': 0.7628150889638984}],
 [{'kernel_size': 2752, 'coherence_20': 1.047368002624877},
  {'kernel_size': 2910, 'coherence_20': 0.5225634415300174},
  {'kernel_size': 3240, 'coherence_20': 0.45743731011686195},
  {'kernel_size': 2639, 'coherence_20': 0.4064026727104663},
  {'kernel_size': 2839, 'coherence_20': 0.5038907284699086},
  {'kernel_size': 2716, 'coherence_20': 0.7484608871132239},
  {'kernel_size': 2954, 'coherence_20': 0.6786358164974955},
  {'kernel_size': 3106, 'coherence_20': 0.5975878464132679},
  {'kernel_size': 2880, 'coherence_20': 0.6945778733111028},
  {'kernel_size': 3363, 'coherence_20': 0.5404160366791895},
  {'kernel_size': 3072, 'coherence_20': 0.5890355281603761},
  {'kernel_size': 3187, 'coherence_20': 0.30891215117868026},
  {'kernel_size': 2732, 'coherence_20': 0.5048055463416965},
  {'kernel_size': 2919, 'coherence_20': 0.45743680355878097},
  {'kernel_size': 2766, 'coherence_20': 0.5676646083702034},
  {'kernel_size': 2726, 'coherence_20': 0.6218177852476944},
  {'kernel_size': 2833, 'coherence_20': 0.78850073862036},
  {'kernel_size': 3267, 'coherence_20': 0.5299823011049999},
  {'kernel_size': 2619, 'coherence_20': 0.8106929840245337},
  {'kernel_size': 2573, 'coherence_20': 0.4422652586679409}],
 [{'kernel_size': 3206, 'coherence_20': 0.6223028270991585},
  {'kernel_size': 2900, 'coherence_20': 0.48258872401098046},
  {'kernel_size': 3044, 'coherence_20': 0.6599653193371181},
  {'kernel_size': 2997, 'coherence_20': 0.5080533024750831},
  {'kernel_size': 2729, 'coherence_20': 0.7174595015924761},
  {'kernel_size': 3121, 'coherence_20': 0.6287512420550649},
  {'kernel_size': 3288, 'coherence_20': 0.6699084531002716},
  {'kernel_size': 2900, 'coherence_20': 0.6932752624970011},
  {'kernel_size': 3210, 'coherence_20': 0.6037418372413446},
  {'kernel_size': 3436, 'coherence_20': 0.5124305877817199},
  {'kernel_size': 2642, 'coherence_20': 0.4842682011978738},
  {'kernel_size': 2884, 'coherence_20': 0.45160743755656985},
  {'kernel_size': 3227, 'coherence_20': 0.7532612509716657},
  {'kernel_size': 2882, 'coherence_20': 0.3814615222232939},
  {'kernel_size': 2733, 'coherence_20': 0.60711624088068},
  {'kernel_size': 2710, 'coherence_20': 0.6019003197496781},
  {'kernel_size': 2955, 'coherence_20': 0.4168534305864538},
  {'kernel_size': 2885, 'coherence_20': 0.47742803505400955},
  {'kernel_size': 2757, 'coherence_20': 0.6492058858365237},
  {'kernel_size': 2661, 'coherence_20': 0.51487633469698}],
 [{'kernel_size': 2729, 'coherence_20': 0.4523951509755763},
  {'kernel_size': 2825, 'coherence_20': 0.6735675870519031},
  {'kernel_size': 2761, 'coherence_20': 0.7454391341683612},
  {'kernel_size': 2942, 'coherence_20': 0.47387981050983763},
  {'kernel_size': 2945, 'coherence_20': 0.3961218416448801},
  {'kernel_size': 2684, 'coherence_20': 0.6863968923100046},
  {'kernel_size': 2953, 'coherence_20': 0.5473891774424847},
  {'kernel_size': 3141, 'coherence_20': 0.6279373120243827},
  {'kernel_size': 2668, 'coherence_20': 0.5842306136760664},
  {'kernel_size': 3132, 'coherence_20': 0.7832834678377089},
  {'kernel_size': 2779, 'coherence_20': 0.5806367175627681},
  {'kernel_size': 2752, 'coherence_20': 0.6471954018387578},
  {'kernel_size': 3277, 'coherence_20': 0.5727475969960437},
  {'kernel_size': 3036, 'coherence_20': 0.6294886948053474},
  {'kernel_size': 2783, 'coherence_20': 0.6237713422324668},
  {'kernel_size': 2846,
   'coherence_20': 0.8804114237991888,
   'distance_to_nearest': 0.7641020653014313},
  {'kernel_size': 2588, 'coherence_20': 0.6737248271346272},
  {'kernel_size': 2970, 'coherence_20': 0.605958658568665},
  {'kernel_size': 2838, 'coherence_20': 0.43455911918370094},
  {'kernel_size': 2930, 'coherence_20': 0.5322384121571735}],
 [{'kernel_size': 2947, 'coherence_20': 0.4038129333773847},
  {'kernel_size': 3237, 'coherence_20': 0.4085848443740604},
  {'kernel_size': 3242, 'coherence_20': 0.41100031437829776},
  {'kernel_size': 2793, 'coherence_20': 0.38472321001076265},
  {'kernel_size': 3308, 'coherence_20': 0.6086661531022883},
  {'kernel_size': 3069, 'coherence_20': 0.8571379065062633},
  {'kernel_size': 2888, 'coherence_20': 0.3677818817007966},
  {'kernel_size': 2974, 'coherence_20': 0.6209315085447774},
  {'kernel_size': 3168, 'coherence_20': 0.7009309361259541},
  {'kernel_size': 2868, 'coherence_20': 0.6101584200156448},
  {'kernel_size': 2737, 'coherence_20': 0.5309149506867048},
  {'kernel_size': 3119, 'coherence_20': 0.9002971471793844},
  {'kernel_size': 2770, 'coherence_20': 0.574998301652173},
  {'kernel_size': 2986, 'coherence_20': 0.4986859546665522},
  {'kernel_size': 3020, 'coherence_20': 0.5462438037257712},
  {'kernel_size': 2640, 'coherence_20': 0.4106340126398557},
  {'kernel_size': 3382, 'coherence_20': 0.5497109629304763},
  {'kernel_size': 2969, 'coherence_20': 0.37017166809393864},
  {'kernel_size': 2820, 'coherence_20': 0.637028994335065},
  {'kernel_size': 2683, 'coherence_20': 0.8019343307926962}],
 [{'kernel_size': 2959, 'coherence_20': 0.5713488266789257},
  {'kernel_size': 3129, 'coherence_20': 0.681591700224658},
  {'kernel_size': 2708, 'coherence_20': 0.5787613767148336},
  {'kernel_size': 2715, 'coherence_20': 0.5463007347567829},
  {'kernel_size': 2679, 'coherence_20': 0.6406906027617022},
  {'kernel_size': 2836, 'coherence_20': 0.5779406259448922},
  {'kernel_size': 2476, 'coherence_20': 0.4723792080078336},
  {'kernel_size': 2722, 'coherence_20': 0.7676257377791097},
  {'kernel_size': 3431, 'coherence_20': 0.6088310010006415},
  {'kernel_size': 2657, 'coherence_20': 0.49836943861392236},
  {'kernel_size': 2750, 'coherence_20': 0.453761972819428},
  {'kernel_size': 2909, 'coherence_20': 0.5091889590363284},
  {'kernel_size': 2770, 'coherence_20': 0.487717615901293},
  {'kernel_size': 2978, 'coherence_20': 0.5484601929765794},
  {'kernel_size': 2786, 'coherence_20': 0.8314952322858998},
  {'kernel_size': 3208, 'coherence_20': 0.8493655197052012},
  {'kernel_size': 2731, 'coherence_20': 0.5450777464712148},
  {'kernel_size': 2879, 'coherence_20': 0.5773095409279496},
  {'kernel_size': 3124, 'coherence_20': 0.7857794247137175},
  {'kernel_size': 2897, 'coherence_20': 0.6255021044799908}],
 [{'kernel_size': 2857, 'coherence_20': 0.5669245716305263},
  {'kernel_size': 2721, 'coherence_20': 0.7535781039822916},
  {'kernel_size': 3034, 'coherence_20': 0.6628424226066171},
  {'kernel_size': 2865, 'coherence_20': 0.46885489863022484},
  {'kernel_size': 3115, 'coherence_20': 0.4563631295152932},
  {'kernel_size': 3210, 'coherence_20': 0.634243682154281},
  {'kernel_size': 3157, 'coherence_20': 0.6995331514205193},
  {'kernel_size': 3144, 'coherence_20': 0.676750433591075},
  {'kernel_size': 2809, 'coherence_20': 0.5176246477914581},
  {'kernel_size': 2665, 'coherence_20': 0.7745729222002105},
  {'kernel_size': 2982, 'coherence_20': 0.44667359405289486},
  {'kernel_size': 3194, 'coherence_20': 0.6332488701935625},
  {'kernel_size': 2905, 'coherence_20': 0.7710957521820377},
  {'kernel_size': 2611, 'coherence_20': 0.46765524413190657},
  {'kernel_size': 2957, 'coherence_20': 0.45689740744382273},
  {'kernel_size': 2469, 'coherence_20': 0.5734461029850816},
  {'kernel_size': 2990, 'coherence_20': 0.5067107008906853},
  {'kernel_size': 2963, 'coherence_20': 0.42480213153027896},
  {'kernel_size': 2996, 'coherence_20': 0.5674477805567942},
  {'kernel_size': 2964, 'coherence_20': 0.6397990250669792}],
 [{'kernel_size': 2715, 'coherence_20': 0.5836548204523587},
  {'kernel_size': 2905, 'coherence_20': 0.6191116346046748},
  {'kernel_size': 2959, 'coherence_20': 0.7004812591828847},
  {'kernel_size': 2932, 'coherence_20': 0.4967689370174988},
  {'kernel_size': 2560, 'coherence_20': 0.47261520423815995},
  {'kernel_size': 2962, 'coherence_20': 0.6801682910647336},
  {'kernel_size': 2908, 'coherence_20': 0.4203229257061402},
  {'kernel_size': 3205, 'coherence_20': 0.5516025204831897},
  {'kernel_size': 3188, 'coherence_20': 0.5174499466733419},
  {'kernel_size': 3071, 'coherence_20': 0.5025495848713364},
  {'kernel_size': 3049, 'coherence_20': 0.6359189554015446},
  {'kernel_size': 2764, 'coherence_20': 0.6578196300656834},
  {'kernel_size': 2880, 'coherence_20': 0.6055910878750667},
  {'kernel_size': 2887, 'coherence_20': 0.581242110634799},
  {'kernel_size': 3252, 'coherence_20': 0.5443569480829908},
  {'kernel_size': 2735, 'coherence_20': 0.7610185326907799},
  {'kernel_size': 2664, 'coherence_20': 0.5955249053932843},
  {'kernel_size': 2766, 'coherence_20': 0.4446744558165994},
  {'kernel_size': 3091, 'coherence_20': 0.6379131686898538},
  {'kernel_size': 2773, 'coherence_20': 0.5975201743104283}],
 [{'kernel_size': 2644, 'coherence_20': 0.7131784990863359},
  {'kernel_size': 3023, 'coherence_20': 0.40818207718882515},
  {'kernel_size': 2850, 'coherence_20': 0.47920553053442444},
  {'kernel_size': 2899, 'coherence_20': 0.5974583673775132},
  {'kernel_size': 2866, 'coherence_20': 0.8403551717453014},
  {'kernel_size': 2914, 'coherence_20': 0.48107426542244663},
  {'kernel_size': 2929, 'coherence_20': 0.6007618678970905},
  {'kernel_size': 2782, 'coherence_20': 0.5706394797602232},
  {'kernel_size': 2915, 'coherence_20': 0.5338356131039321},
  {'kernel_size': 2969, 'coherence_20': 0.4929218838551522},
  {'kernel_size': 3026, 'coherence_20': 0.6736888249297911},
  {'kernel_size': 3559, 'coherence_20': 0.5055047926809345},
  {'kernel_size': 2832, 'coherence_20': 0.40886361902806106},
  {'kernel_size': 3549, 'coherence_20': 0.642379650644745},
  {'kernel_size': 2613, 'coherence_20': 0.46580710475491094},
  {'kernel_size': 3175, 'coherence_20': 0.5080922190024306},
  {'kernel_size': 2797, 'coherence_20': 0.7528135140043106},
  {'kernel_size': 2962, 'coherence_20': 0.39423671875038085},
  {'kernel_size': 2812, 'coherence_20': 0.49665989016737583},
  {'kernel_size': 2826, 'coherence_20': 0.671838245401157}],
 [{'kernel_size': 2793, 'coherence_20': 0.590931232903191},
  {'kernel_size': 3147, 'coherence_20': 0.4496275449778878},
  {'kernel_size': 2656, 'coherence_20': 0.4980276984955354},
  {'kernel_size': 2920, 'coherence_20': 0.504890254881141},
  {'kernel_size': 3161, 'coherence_20': 0.8357395108202149},
  {'kernel_size': 3085, 'coherence_20': 0.5797379198131906},
  {'kernel_size': 2632, 'coherence_20': 0.42927151709749256},
  {'kernel_size': 3090, 'coherence_20': 0.6359746300941836},
  {'kernel_size': 3069, 'coherence_20': 0.3705442240954028},
  {'kernel_size': 2922, 'coherence_20': 0.8305650665422324},
  {'kernel_size': 2840, 'coherence_20': 0.5166334286460038},
  {'kernel_size': 2800, 'coherence_20': 0.7396967443716884},
  {'kernel_size': 2798, 'coherence_20': 0.72358452368945},
  {'kernel_size': 3057, 'coherence_20': 0.5077387470697939},
  {'kernel_size': 2870, 'coherence_20': 0.6445570217119967},
  {'kernel_size': 2869, 'coherence_20': 0.4014985648415052},
  {'kernel_size': 2803, 'coherence_20': 0.7244851521151825},
  {'kernel_size': 2861, 'coherence_20': 0.5435291106154692},
  {'kernel_size': 2908, 'coherence_20': 0.5704872835998546},
  {'kernel_size': 3067, 'coherence_20': 0.6114406310491602}],
 [{'kernel_size': 2734, 'coherence_20': 0.6131374605283242},
  {'kernel_size': 2858, 'coherence_20': 0.37541926040156665},

In [67]:
optimizer._result['model_scores'][0]

{'perplexity_score': 2183.57958984375,
 'coherence_20': 0.5553686071210906,
 'diversity_euclidean': 0.04994020510914676,
 'diversity_jensenshannon': 0.5937372211329287,
 'diversity_hellinger': 0.6835495593998556,
 'diversity_cosine': 0.6570792337263397,
 'perplexity': 2183.57958984375}

In [68]:
optimizer._result['model_scores'][1]

{'perplexity_score': 2182.065185546875,
 'coherence_20': 0.5680720371310215,
 'diversity_euclidean': 0.05442068104726088,
 'diversity_jensenshannon': 0.5973725631226747,
 'diversity_hellinger': 0.6877445417877905,
 'diversity_cosine': 0.6964043550767838,
 'perplexity': 2182.065185546875}

In [69]:
sum(s['coherence_20'] for s in optimizer._result['bank_topic_scores'][-1]) / 6

0.8462748392332192

In [70]:
len(optimizer._result['bank_scores'])

20

In [71]:
optimizer._result['bank_scores'][-1]

{'perplexity_score': 6776.9052734375,
 'coherence_20': 0.8462748392332191,
 'diversity_euclidean': 0.05650286551732751,
 'diversity_jensenshannon': 0.6213988557024641,
 'diversity_hellinger': 0.7187754072059787,
 'diversity_cosine': 0.7587374014533104,
 'perplexity': 6776.9052734375,
 'ppl_fair': 6776.9052734375,
 'ppl_cheatty': 3492.67138671875}

In [264]:
optimizer._result['bank_topic_scores'][-1]

[{'kernel_size': 6290,
  'coherence_20': 1.9365857260048487,
  'distance_to_nearest': 0.0},
 {'kernel_size': 5987,
  'coherence_20': 2.350993531411413,
  'distance_to_nearest': 0.8670798186186544},
 {'kernel_size': 4904,
  'coherence_20': 1.665684284462788,
  'distance_to_nearest': 0.9068645569155264},
 {'kernel_size': 6419,
  'coherence_20': 3.2077123047347023,
  'distance_to_nearest': 0.9163295596263876}]

In [41]:
import artm
from topnum.model_constructor import KnownModel, init_plsa
from topicnet.cooking_machine.rel_toolbox_lite import (
    count_vocab_size,
    transform_regularizer,
)
from topicnet.cooking_machine.model_constructor import (
    add_standard_scores,
    create_default_topics,
    init_model,
)

def init_model_from_family(
        family: str or KnownModel,
        dataset: Dataset,
        main_modality: str,
        num_topics: int,
        seed: int,
        specific_topic_names = None,
        modalities_to_use: List[str] = None,
        num_processors: int = 3,
        model_params: dict = None,
):
    """
    Returns
    -------
    model: TopicModel() instance
    """
    if isinstance(family, KnownModel):
        family = family.value

    if modalities_to_use is None:
        modalities_to_use = [main_modality]

    custom_regs = {}

    if family == "LDA":
        model = init_lda(
            dataset, modalities_to_use, main_modality, num_topics, model_params
        )
    elif family == "PLSA":
        model = init_plsa(
            dataset, modalities_to_use, main_modality, num_topics
        )
    elif family == "TARTM":
        model, custom_regs = init_thetaless(
            dataset, modalities_to_use, main_modality, num_topics, model_params
        )
    elif family == "sparse":
        model = init_bcg_sparse_model(
            dataset, modalities_to_use, main_modality, num_topics, 1, model_params
        )
    elif family == "decorrelation":
        model = init_decorrelated_plsa(
            dataset, modalities_to_use, main_modality, num_topics, model_params
        )
    elif family == "ARTM":
        model = init_baseline_artm(
            dataset, modalities_to_use, main_modality, num_topics, 1, specific_topic_names, model_params
        )
    else:
        raise ValueError(f'family: {family}')

    model.num_processors = num_processors

    if seed is not None:
        model.seed = seed

    dictionary = dataset.get_dictionary()

    # TODO: maybe this cycle is not necessary
    for modality in dataset.get_possible_modalities():
        if modality not in modalities_to_use:
            dictionary.filter(class_id=modality, max_df=0, inplace=True)

    model.initialize(dictionary)
    add_standard_scores(model, dictionary, main_modality=main_modality,
                        all_modalities=modalities_to_use)

    model = TopicModel(
        artm_model=model,
        custom_regularizers=custom_regs
    )
    model.has_bcg = True  # TODO: only if init_bcg_sparse_model

    return model


def init_bcg_sparse_model(
        dataset,
        modalities_to_use,
        main_modality,
        specific_topics,
        bcg_topics,
        specific_topic_names = None,
        model_params: dict = None
):
    """
    Creates simple artm model with standard scores.

    Parameters
    ----------
    dataset : Dataset
    modalities_to_use : list of str or dict
    main_modality : str
    specific_topics : int
    bcg_topics : int

    Returns
    -------
    model: artm.ARTM() instance
    """
    if model_params is None:
        model_params = dict()

    model = init_plsa(
        dataset, modalities_to_use, main_modality, specific_topics, bcg_topics
    )
    background_topic_names = model.topic_names[-bcg_topics:]

    if specific_topic_names is None:
        print('No spec topics')
        specific_topic_names = model.topic_names[:-bcg_topics]

    dictionary = dataset.get_dictionary()
    baseline_class_ids = {class_id: 1 for class_id in modalities_to_use}
    data_stats = count_vocab_size(dictionary, baseline_class_ids)

    # all coefficients are relative
    regularizers = [
        artm.SmoothSparsePhiRegularizer(
             name='smooth_phi_bcg',
             topic_names=background_topic_names,
             tau=model_params.get("smooth_bcg_tau", 0.1),
             class_ids=[main_modality],
        ),
        artm.SmoothSparseThetaRegularizer(
             name='smooth_theta_bcg',
             topic_names=background_topic_names,
             tau=model_params.get("smooth_bcg_tau", 0.1),
        ),
        artm.SmoothSparsePhiRegularizer(
             name='sparse_phi_sp',
             topic_names=specific_topic_names,
             tau=model_params.get("sparse_sp_tau", -0.05),
             class_ids=[main_modality],
            ),
        artm.SmoothSparseThetaRegularizer(
             name='sparse_theta_sp',
             topic_names=specific_topic_names,
             tau=model_params.get("sparse_sp_tau", -0.05),
        ),
    ]
    for reg in regularizers:
        model.regularizers.add(transform_regularizer(
            data_stats,
            reg,
            model.class_ids,
            n_topics=len(reg.topic_names)
        ))

    return model


def init_baseline_artm(
        dataset,
        modalities_to_use,
        main_modality,
        num_topics,
        bcg_topics,
        specific_topic_names = None,
        model_params: dict = None,
):
    """
    Creates simple artm model with standard scores.

    Parameters
    ----------
    dataset : Dataset
    modalities_to_use : list of str
    main_modality : str
    num_topics : int

    Returns
    -------
    model: artm.ARTM() instance
    """
    if model_params is None:
        model_params = dict()

    model = init_bcg_sparse_model(
        dataset, modalities_to_use, main_modality, num_topics, bcg_topics, specific_topic_names, model_params
    )

    if specific_topic_names is None:
        print('No spec topics')
        specific_topic_names = model.topic_names[:-bcg_topics]

    model.regularizers.add(
        artm.DecorrelatorPhiRegularizer(
            gamma=0,
            tau=model_params.get('decorrelation_tau', 0.01),
            name='decorrelation',
            topic_names=specific_topic_names,
            class_ids=modalities_to_use,
        )
    )

    return model

In [42]:
def artm_train_func(
        dataset: Dataset,
        model_number: int,
        num_topics: int,
        num_fit_iterations: int,
        scores: List = None,
        **kwargs) -> TopicModel:
    """

    Additional Parameters
    ---------------------
    kwargs
        Some params for `_get_topic_model`, such as `cache_theta` and `num_processors`
    """

    topic_model = init_model_from_family(
        family='ARTM',
        dataset=DATASET,
        main_modality=MAIN_MODALITY,
        num_topics=ONE_MODEL_NUM_TOPICS,
        seed=model_number,
        model_params={
            'decorrelation_tau': 0.01,  # best values
            'smooth_bcg_tau': 0.05,
            'sparse_sp_tau': -0.05,
        }
    )

    num_fit_iterations_with_scores = 1

    topic_model._fit(
        dataset.get_batch_vectorizer(),
        num_iterations=max(0, num_fit_iterations - num_fit_iterations_with_scores)
    )
    _fit_model_with_scores(
        topic_model,
        DATASET,
        scores,
        num_fit_iterations=num_fit_iterations_with_scores
    )

    return topic_model


def _fit_model_with_scores(
        topic_model: TopicModel,
        dataset: Dataset,
        scores: List = None,
        num_fit_iterations: int = 1):

    if scores is not None:
        for score in scores:
            score._attach(topic_model)

    topic_model._fit(
        dataset.get_batch_vectorizer(),
        num_iterations=num_fit_iterations
    )

### Bank Creation<a id="bank-creation"></a>

<div style="text-align: right">Back to <a href=#contents>Contents</a></div>

Here we finally run the experiment!

In [43]:
NUM_ITERATIONS = 20

In [44]:
seed = 0

In [45]:
# We use only one train function here
# Other variations are also possible
# It would be even better to make bank using several train functions
# However, it would also take way more time 

TRAIN_FUNCS = artm_train_func  # default train func

In [46]:
DATASET_INTERNALS_FOLDER_PATH

'/data_mil/shared/CompressaAI/iterative/data/noow/MKB_10__internals'

! mv /data_mil/shared/CompressaAI/iterative/data/noow/MKB_10__internals/result2 /data_mil/shared/CompressaAI/iterative/data/noow/MKB_10__internals/_result2

In [47]:
! ls /data_mil/shared/CompressaAI/iterative/data/noow/MKB_10__internals

batches  dict.dict  _result2  result2  vw.txt

In [48]:
SEARCH_RESULTS_FOLDER_PATH = os.path.join(
    DATASET_INTERNALS_FOLDER_PATH, 'result2_50'
)

# File with some info about the process
SEARCH_RESULT_FILE_PATH = os.path.join(
    SEARCH_RESULTS_FOLDER_PATH, f'search_result__{seed}.json'
)

# Bank, with topics and their score values
BANK_FOLDER_PATH = os.path.join(
    SEARCH_RESULTS_FOLDER_PATH, f'bank__{seed}'
)

In [49]:
SEARCH_RESULTS_FOLDER_PATH

'/data_mil/shared/CompressaAI/iterative/data/noow/MKB_10__internals/result2_50'

In [50]:
! ls $SEARCH_RESULTS_FOLDER_PATH

ls: cannot access '/data_mil/shared/CompressaAI/iterative/data/noow/MKB_10__internals/result2_50': No such file or directory

In [107]:
import json

In [108]:
d = json.loads(open(SEARCH_RESULTS_FOLDER_PATH + '/search_result__0.json').read())

In [110]:
d.keys()

dict_keys(['optimum', 'optimum_std', 'bank_scores', 'bank_topic_scores', 'model_scores', 'model_topic_scores', 'num_bank_topics', 'num_model_topics'])

In [112]:
len(d['bank_scores']), len(d['bank_topic_scores']), len(d['model_scores']), len(d['model_topic_scores']), len(d['num_bank_topics']), len(d['num_model_topics'])

(17, 17, 18, 17, 17, 18)

In [113]:
del d['model_scores'][-1]
del d['num_model_topics'][-1]

In [114]:
len(d['bank_scores']), len(d['bank_topic_scores']), len(d['model_scores']), len(d['model_topic_scores']), len(d['num_bank_topics']), len(d['num_model_topics'])

(17, 17, 17, 17, 17, 17)

In [115]:
with open(SEARCH_RESULTS_FOLDER_PATH + '/search_result__0.json', 'w') as f:
    f.write(json.dumps(d))

! rm -r $SEARCH_RESULTS_FOLDER_PATH

In [51]:
BANK_FOLDER_PATH

'/data_mil/shared/CompressaAI/iterative/data/noow/MKB_10__internals/result2_50/bank__0'

In [52]:
os.makedirs(SEARCH_RESULTS_FOLDER_PATH, exist_ok=True)
os.makedirs(BANK_FOLDER_PATH, exist_ok=True)

In [53]:
seed

0

In [56]:
! ls /data_mil/shared/CompressaAI/iterative/data/noow/Post_Science__internals

batches  dict.dict  _result  _result2  result2	result2_50  vw.txt

One cay vary some parameters below (for example `max_num_models` and `num_fit_iterations`).

In [54]:
optimizer = TopicBankMethod(
    data        = DATASET,
    main_modality = MAIN_MODALITY,
    
    min_df_rate = 0.0,  # dictionary filtering has already been done little earlier
    max_df_rate = 1.0,  #   so we don't want these parameters to have any effect

    main_topic_score   = intra_coherence_score,  # coherence_score,
    other_topic_scores = [coherence_score],
    other_scores       = [coherence_score] + diversity_scores + other_scores,
    documents          = DOCUMENTS,

    start_model_number   = 0,
    max_num_models       = 20,
    one_model_num_topics = ONE_MODEL_NUM_TOPICS,  # 100,
    num_fit_iterations   = NUM_ITERATIONS,  # 100,  # 100 should be enough;
                                 # however, for big data better to reduce this one
                                 # (otherwise the process will be too slow)
    topic_score_threshold_percentile = 1.5041606723306686,

    save_bank         = True,
    save_model_topics = True,
    save_file_path    = SEARCH_RESULT_FILE_PATH,
    bank_folder_path  = BANK_FOLDER_PATH,

    train_funcs = TRAIN_FUNCS,
    
    verbose = True,
)

# TODO: use Holdout Perplexity as Stop score

/home/alekseev_v/projects/iterative/../OptimalNumberOfTopics/topnum/search_methods/topic_bank/topic_bank_method.py:218: UserWarning: topic_score_threshold_percentile 1.5041606723306686 is less than one! It is expected to be in [0, 100]. Are you sure you want to proceed (yes/no)?
  warnings.warn(

In [57]:
optimizer._result

{'optimum': None,
 'optimum_std': None,
 'bank_scores': [],
 'bank_topic_scores': [],
 'model_scores': [],
 'model_topic_scores': [],
 'num_bank_topics': [],
 'num_model_topics': []}

len(optimizer._result['num_model_topics'])

Checking file paths

! ls ./Post_Science__internals

In [58]:
optimizer._save_file_path

'/data_mil/shared/CompressaAI/iterative/data/noow/MKB_10__internals/result2_50/search_result__0.json'

In [59]:
optimizer._topic_bank._path

'/data_mil/shared/CompressaAI/iterative/data/noow/MKB_10__internals/result2_50/bank__0'

Fulfilling the search (get ready for a really long process!):

In [60]:
%%time

optimizer.search_for_optimum(DATASET)

  0%|                                                        | 0/20 [00:00<?, ?it/s]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████                        | 1/2 [02:41<02:41, 161.50s/it]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 2/2 [02:41<00:00, 80.88s/it]
Using absoulte threshold: 1.5041606723306686.
Eliminating bcg topic before Hier. Cur |T| is 51, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'topic_20', 'topic_21', 'topic_22', 'topic_23',
       'topic_24', 'topic_25', 'topic_26', 'topic_27', 'topic_28', 'topic_29',
       'topic_30', 'topic_31', 'topic_32', 'topic_33', 'topic_34', 'topic_35',
       'topic_36', 'topic_37', 'topic_38', 'topic_39', 'topic_40', 'topic_41',
       'topic_42', 'topic_43', 'topic_44', 'topic_45', 'topic_46', 'topic_47',
       'topic_48', 'topic_49', 'background_50'],
      dtype='object').
Now |T| is 50, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'topic_20', 'topic_21', 'topic_22', 'topic_23',
       'topic_24', 'topic_25', 'topic_26', 'topic_27', 'topic_28', 'topic_29',
       'topic_30', 'topic_31', 'topic_32', 'topic_33', 'topic_34', 'topic_35',
       'topic_36', 'topic_37', 'topic_38', 'topic_39', 'topic_40', 'topic_41',
       'topic_42', 'topic_43', 'topic_44', 'topic_45', 'topic_46', 'topic_47',
       'topic_48', 'topic_49'],
      dtype='object').
Skipping saving scores for bcg topic
!!! Bank Phi: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.9998887e-09]
 [3.6460795e-16 5.3412064e-15 1.4010391e-09 ... 2.4542096e-12
  2.1238453e-13 1.6178517e-10]
 [5.7825876e-11 3.5670785e-13 1.4697234e-10 ... 4.0462685e-13
  5.2451212e-12 3.7991756e-09]
 ...
 [1.9733823e-09 2.4617216e-11 6.5242862e-14 ... 1.0352724e-15
  0.0000000e+00 4.6249289e-13]
 [2.3012989e-09 6.3966038e-10 8.6911755e-15 ... 4.3578235e-13
  6.3609061e-15 5.2149165e-13]
 [1.9132644e-09 5.5868945e-11 2.0574655e-13 ... 1.7700930e-13
  5.3047950e-15 1.8597875e-12]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 9.3980589e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 9.3980589e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 4.1422267e-05]
 ...
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 9.3980589e-06]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.0923021e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 9.3980589e-06]].
Bank scores: {'perplexity_score': 10208.076171875, 'coherence_20': 0.9029355309585569, 'diversity_euclidean': 0.08571874142455244, 'diversity_jensenshannon': 0.6958946137026836, 'diversity_hellinger': 0.815535452567058, 'diversity_cosine': 0.8605912413357668, 'perplexity': 10208.076171875, 'ppl_fair': 10208.076171875, 'ppl_cheatty': 3478.7275390625}
  5%|██▎                                          | 1/20 [04:02<1:16:51, 242.74s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████                        | 1/2 [02:42<02:42, 162.46s/it]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 2/2 [02:42<00:00, 81.36s/it]
Using absoulte threshold: 1.5041606723306686.
Eliminating bcg topic before Hier. Cur |T| is 51, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'topic_20', 'topic_21', 'topic_22', 'topic_23',
       'topic_24', 'topic_25', 'topic_26', 'topic_27', 'topic_28', 'topic_29',
       'topic_30', 'topic_31', 'topic_32', 'topic_33', 'topic_34', 'topic_35',
       'topic_36', 'topic_37', 'topic_38', 'topic_39', 'topic_40', 'topic_41',
       'topic_42', 'topic_43', 'topic_44', 'topic_45', 'topic_46', 'topic_47',
       'topic_48', 'topic_49', 'background_50'],
      dtype='object').
Now |T| is 50, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'topic_20', 'topic_21', 'topic_22', 'topic_23',
       'topic_24', 'topic_25', 'topic_26', 'topic_27', 'topic_28', 'topic_29',
       'topic_30', 'topic_31', 'topic_32', 'topic_33', 'topic_34', 'topic_35',
       'topic_36', 'topic_37', 'topic_38', 'topic_39', 'topic_40', 'topic_41',
       'topic_42', 'topic_43', 'topic_44', 'topic_45', 'topic_46', 'topic_47',
       'topic_48', 'topic_49'],
      dtype='object').
Creating first level with 10 topics. Dictionary: artm.Dictionary(name=8b6b94ce-8444-492f-850a-42f0a4c559e1, num_entries=22608).
Copying phi for the first level. Phi shape: (22608, 10). First words: MultiIndex([('@text',           'tsd'),
            ('@text',        'кратер'),
            ('@text',           'cdk'),
            ('@text', 'внутриядерный'),
            ('@text',    'прибрежный'),
            ('@text',   'соотнесение'),
            ('@text', 'ангиоматозный'),
            ('@text',       'либерия'),
            ('@text', 'хориоменингит'),
            ('@text', 'герминативный')],
           )
Creating second level with 50 topics
Copying phi for the second level. Phi shape: (22608, 50). First words: MultiIndex([('@text',           'tsd'),
            ('@text',        'кратер'),
            ('@text',           'cdk'),
            ('@text', 'внутриядерный'),
            ('@text',    'прибрежный'),
            ('@text',   'соотнесение'),
            ('@text', 'ангиоматозный'),
            ('@text',       'либерия'),
            ('@text', 'хориоменингит'),
            ('@text', 'герминативный')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic
!!! Bank Phi: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]].
!!! Bank model Phi: [[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.29542413e-16 6.85318968e-10 ... 1.92314020e-14
  3.77794254e-11 1.65416234e-14]
 [6.34682020e-12 7.03725137e-14 1.26474204e-11 ... 2.89211353e-16
  1.74604309e-13 5.15861767e-13]
 ...
 [1.97575067e-09 2.22079733e-11 2.19179618e-14 ... 0.00000000e+00
  0.00000000e+00 4.58089225e-15]
 [2.44296494e-09 4.71058581e-10 2.90391715e-15 ... 6.06389175e-11
  2.66195694e-16 2.70418030e-14]
 [1.93332284e-09 4.96572193e-11 7.05514274e-14 ... 2.49276672e-15
  0.00000000e+00 1.72528279e-14]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.0415927e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.0415927e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 4.5908550e-05]
 ...
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.0415927e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.2106051e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.0415927e-05]].
Bank scores: {'perplexity_score': 7535.35888671875, 'coherence_20': 0.8556934598538212, 'diversity_euclidean': 0.08464793929632777, 'diversity_jensenshannon': 0.6931204795944944, 'diversity_hellinger': 0.8120797974516304, 'diversity_cosine': 0.8563001399316005, 'perplexity': 7535.35888671875, 'ppl_fair': 7535.35888671875, 'ppl_cheatty': 3284.724365234375}
 10%|████▌                                        | 2/20 [08:20<1:15:29, 251.64s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████                        | 1/2 [02:42<02:42, 162.43s/it]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 2/2 [02:42<00:00, 81.35s/it]
Using absoulte threshold: 1.5041606723306686.
Eliminating bcg topic before Hier. Cur |T| is 51, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'topic_20', 'topic_21', 'topic_22', 'topic_23',
       'topic_24', 'topic_25', 'topic_26', 'topic_27', 'topic_28', 'topic_29',
       'topic_30', 'topic_31', 'topic_32', 'topic_33', 'topic_34', 'topic_35',
       'topic_36', 'topic_37', 'topic_38', 'topic_39', 'topic_40', 'topic_41',
       'topic_42', 'topic_43', 'topic_44', 'topic_45', 'topic_46', 'topic_47',
       'topic_48', 'topic_49', 'background_50'],
      dtype='object').
Now |T| is 50, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'topic_20', 'topic_21', 'topic_22', 'topic_23',
       'topic_24', 'topic_25', 'topic_26', 'topic_27', 'topic_28', 'topic_29',
       'topic_30', 'topic_31', 'topic_32', 'topic_33', 'topic_34', 'topic_35',
       'topic_36', 'topic_37', 'topic_38', 'topic_39', 'topic_40', 'topic_41',
       'topic_42', 'topic_43', 'topic_44', 'topic_45', 'topic_46', 'topic_47',
       'topic_48', 'topic_49'],
      dtype='object').
Creating first level with 13 topics. Dictionary: artm.Dictionary(name=8b6b94ce-8444-492f-850a-42f0a4c559e1, num_entries=22608).
Copying phi for the first level. Phi shape: (22608, 13). First words: MultiIndex([('@text',           'tsd'),
            ('@text',        'кратер'),
            ('@text',           'cdk'),
            ('@text', 'внутриядерный'),
            ('@text',    'прибрежный'),
            ('@text',   'соотнесение'),
            ('@text', 'ангиоматозный'),
            ('@text',       'либерия'),
            ('@text', 'хориоменингит'),
            ('@text', 'герминативный')],
           )
Creating second level with 50 topics
Copying phi for the second level. Phi shape: (22608, 50). First words: MultiIndex([('@text',           'tsd'),
            ('@text',        'кратер'),
            ('@text',           'cdk'),
            ('@text', 'внутриядерный'),
            ('@text',    'прибрежный'),
            ('@text',   'соотнесение'),
            ('@text', 'ангиоматозный'),
            ('@text',       'либерия'),
            ('@text', 'хориоменингит'),
            ('@text', 'герминативный')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic
!!! Bank Phi: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 0.0000000e+00]
 [2.6809069e-16 0.0000000e+00 1.5584764e-11 ... 1.7660434e-14
  1.2344372e-13 1.8395450e-09]
 [3.3953729e-10 5.3387150e-13 6.5154639e-11 ... 2.2228262e-14
  1.2237876e-12 8.9784713e-10]
 ...
 [1.9743420e-09 2.4782698e-11 2.4189823e-14 ... 0.0000000e+00
  3.0092114e-15 5.1172451e-13]
 [2.3876217e-09 6.0037830e-10 1.6523683e-15 ... 5.6206945e-14
  1.6086755e-14 1.2764115e-12]
 [1.9346542e-09 5.4011039e-11 7.8409494e-14 ... 0.0000000e+00
  7.5182153e-15 1.8994318e-12]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.0179524e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.0179524e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 4.4866592e-05]
 ...
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.0179524e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.1831289e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.0179524e-05]].
Bank scores: {'perplexity_score': 7493.7353515625, 'coherence_20': 0.8564703841026554, 'diversity_euclidean': 0.08586048198825141, 'diversity_jensenshannon': 0.6913761821228219, 'diversity_hellinger': 0.8099243323915234, 'diversity_cosine': 0.8533404388951302, 'perplexity': 7493.7353515625, 'ppl_fair': 7493.7353515625, 'ppl_cheatty': 3270.56982421875}
 15%|██████▊                                      | 3/20 [12:32<1:11:18, 251.66s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████                        | 1/2 [02:43<02:43, 163.48s/it]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 2/2 [02:43<00:00, 81.87s/it]
Using absoulte threshold: 1.5041606723306686.
Eliminating bcg topic before Hier. Cur |T| is 51, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'topic_20', 'topic_21', 'topic_22', 'topic_23',
       'topic_24', 'topic_25', 'topic_26', 'topic_27', 'topic_28', 'topic_29',
       'topic_30', 'topic_31', 'topic_32', 'topic_33', 'topic_34', 'topic_35',
       'topic_36', 'topic_37', 'topic_38', 'topic_39', 'topic_40', 'topic_41',
       'topic_42', 'topic_43', 'topic_44', 'topic_45', 'topic_46', 'topic_47',
       'topic_48', 'topic_49', 'background_50'],
      dtype='object').
Now |T| is 50, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'topic_20', 'topic_21', 'topic_22', 'topic_23',
       'topic_24', 'topic_25', 'topic_26', 'topic_27', 'topic_28', 'topic_29',
       'topic_30', 'topic_31', 'topic_32', 'topic_33', 'topic_34', 'topic_35',
       'topic_36', 'topic_37', 'topic_38', 'topic_39', 'topic_40', 'topic_41',
       'topic_42', 'topic_43', 'topic_44', 'topic_45', 'topic_46', 'topic_47',
       'topic_48', 'topic_49'],
      dtype='object').
Creating first level with 13 topics. Dictionary: artm.Dictionary(name=8b6b94ce-8444-492f-850a-42f0a4c559e1, num_entries=22608).
Copying phi for the first level. Phi shape: (22608, 13). First words: MultiIndex([('@text',           'tsd'),
            ('@text',        'кратер'),
            ('@text',           'cdk'),
            ('@text', 'внутриядерный'),
            ('@text',    'прибрежный'),
            ('@text',   'соотнесение'),
            ('@text', 'ангиоматозный'),
            ('@text',       'либерия'),
            ('@text', 'хориоменингит'),
            ('@text', 'герминативный')],
           )
Creating second level with 50 topics
Copying phi for the second level. Phi shape: (22608, 50). First words: MultiIndex([('@text',           'tsd'),
            ('@text',        'кратер'),
            ('@text',           'cdk'),
            ('@text', 'внутриядерный'),
            ('@text',    'прибрежный'),
            ('@text',   'соотнесение'),
            ('@text', 'ангиоматозный'),
            ('@text',       'либерия'),
            ('@text', 'хориоменингит'),
            ('@text', 'герминативный')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic
!!! Bank Phi: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]].
!!! Bank model Phi: [[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.11989131e-13 6.31927236e-15 ... 0.00000000e+00
  8.82937861e-14 0.00000000e+00]
 [1.19332105e-11 3.21683890e-12 5.38262651e-16 ... 2.38252191e-12
  2.27935004e-08 5.96972761e-14]
 ...
 [1.69235292e-09 1.06952546e-14 6.93819134e-13 ... 3.54018289e-15
  2.34364167e-10 7.21993160e-11]
 [2.88749957e-09 1.82506801e-14 6.25354125e-14 ... 2.81430593e-15
  4.72178859e-11 6.21723437e-11]
 [1.39270495e-09 1.91109911e-14 1.81733394e-12 ... 1.06000312e-14
  4.34009800e-10 1.70286840e-10]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.1238422e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.1238422e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 4.9533730e-05]
 ...
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.1238422e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.3062008e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.1238422e-05]].
Bank scores: {'perplexity_score': 6346.06884765625, 'coherence_20': 0.8621776771108957, 'diversity_euclidean': 0.08326931989662281, 'diversity_jensenshannon': 0.6884429447844626, 'diversity_hellinger': 0.8064359204497298, 'diversity_cosine': 0.8490568636221048, 'perplexity': 6346.06884765625, 'ppl_fair': 6346.06884765625, 'ppl_cheatty': 3154.244873046875}
 20%|█████████                                    | 4/20 [16:52<1:08:00, 255.01s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████                        | 1/2 [02:43<02:43, 163.77s/it]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 2/2 [02:44<00:00, 82.02s/it]
Using absoulte threshold: 1.5041606723306686.
Eliminating bcg topic before Hier. Cur |T| is 51, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'topic_20', 'topic_21', 'topic_22', 'topic_23',
       'topic_24', 'topic_25', 'topic_26', 'topic_27', 'topic_28', 'topic_29',
       'topic_30', 'topic_31', 'topic_32', 'topic_33', 'topic_34', 'topic_35',
       'topic_36', 'topic_37', 'topic_38', 'topic_39', 'topic_40', 'topic_41',
       'topic_42', 'topic_43', 'topic_44', 'topic_45', 'topic_46', 'topic_47',
       'topic_48', 'topic_49', 'background_50'],
      dtype='object').
Now |T| is 50, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'topic_20', 'topic_21', 'topic_22', 'topic_23',
       'topic_24', 'topic_25', 'topic_26', 'topic_27', 'topic_28', 'topic_29',
       'topic_30', 'topic_31', 'topic_32', 'topic_33', 'topic_34', 'topic_35',
       'topic_36', 'topic_37', 'topic_38', 'topic_39', 'topic_40', 'topic_41',
       'topic_42', 'topic_43', 'topic_44', 'topic_45', 'topic_46', 'topic_47',
       'topic_48', 'topic_49'],
      dtype='object').
Creating first level with 15 topics. Dictionary: artm.Dictionary(name=8b6b94ce-8444-492f-850a-42f0a4c559e1, num_entries=22608).
Copying phi for the first level. Phi shape: (22608, 15). First words: MultiIndex([('@text',           'tsd'),
            ('@text',        'кратер'),
            ('@text',           'cdk'),
            ('@text', 'внутриядерный'),
            ('@text',    'прибрежный'),
            ('@text',   'соотнесение'),
            ('@text', 'ангиоматозный'),
            ('@text',       'либерия'),
            ('@text', 'хориоменингит'),
            ('@text', 'герминативный')],
           )
Creating second level with 50 topics
Copying phi for the second level. Phi shape: (22608, 50). First words: MultiIndex([('@text',           'tsd'),
            ('@text',        'кратер'),
            ('@text',           'cdk'),
            ('@text', 'внутриядерный'),
            ('@text',    'прибрежный'),
            ('@text',   'соотнесение'),
            ('@text', 'ангиоматозный'),
            ('@text',       'либерия'),
            ('@text', 'хориоменингит'),
            ('@text', 'герминативный')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic
!!! Bank Phi: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 0.0000000e+00]
 [0.0000000e+00 2.1198927e-13 6.3192728e-15 ... 0.0000000e+00
  8.8293806e-14 0.0000000e+00]
 [1.1933227e-11 3.2168372e-12 5.3826270e-16 ... 2.3825219e-12
  2.2793500e-08 5.9697276e-14]
 ...
 [1.6923526e-09 1.0695249e-14 6.9381903e-13 ... 3.5401842e-15
  2.3436422e-10 7.2199302e-11]
 [2.8874998e-09 1.8250672e-14 6.2535413e-14 ... 2.8143064e-15
  4.7217886e-11 6.2172323e-11]
 [1.3927051e-09 1.9110984e-14 1.8173338e-12 ... 1.0600035e-14
  4.3400988e-10 1.7028680e-10]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.1238422e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.1238422e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 4.9533726e-05]
 ...
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.1238422e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.3062007e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.1238422e-05]].
Bank scores: {'perplexity_score': 6346.06884765625, 'coherence_20': 0.8621776771108957, 'diversity_euclidean': 0.08326931989653745, 'diversity_jensenshannon': 0.68844294478395, 'diversity_hellinger': 0.8064359204454622, 'diversity_cosine': 0.8490568636218739, 'perplexity': 6346.06884765625, 'ppl_fair': 6346.06884765625, 'ppl_cheatty': 3154.2451171875}
 25%|███████████▎                                 | 5/20 [21:07<1:03:43, 254.92s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████                        | 1/2 [02:45<02:45, 165.21s/it]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 2/2 [02:45<00:00, 82.74s/it]
Using absoulte threshold: 1.5041606723306686.
Eliminating bcg topic before Hier. Cur |T| is 51, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'topic_20', 'topic_21', 'topic_22', 'topic_23',
       'topic_24', 'topic_25', 'topic_26', 'topic_27', 'topic_28', 'topic_29',
       'topic_30', 'topic_31', 'topic_32', 'topic_33', 'topic_34', 'topic_35',
       'topic_36', 'topic_37', 'topic_38', 'topic_39', 'topic_40', 'topic_41',
       'topic_42', 'topic_43', 'topic_44', 'topic_45', 'topic_46', 'topic_47',
       'topic_48', 'topic_49', 'background_50'],
      dtype='object').
Now |T| is 50, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'topic_20', 'topic_21', 'topic_22', 'topic_23',
       'topic_24', 'topic_25', 'topic_26', 'topic_27', 'topic_28', 'topic_29',
       'topic_30', 'topic_31', 'topic_32', 'topic_33', 'topic_34', 'topic_35',
       'topic_36', 'topic_37', 'topic_38', 'topic_39', 'topic_40', 'topic_41',
       'topic_42', 'topic_43', 'topic_44', 'topic_45', 'topic_46', 'topic_47',
       'topic_48', 'topic_49'],
      dtype='object').
Creating first level with 15 topics. Dictionary: artm.Dictionary(name=8b6b94ce-8444-492f-850a-42f0a4c559e1, num_entries=22608).
Copying phi for the first level. Phi shape: (22608, 15). First words: MultiIndex([('@text',           'tsd'),
            ('@text',        'кратер'),
            ('@text',           'cdk'),
            ('@text', 'внутриядерный'),
            ('@text',    'прибрежный'),
            ('@text',   'соотнесение'),
            ('@text', 'ангиоматозный'),
            ('@text',       'либерия'),
            ('@text', 'хориоменингит'),
            ('@text', 'герминативный')],
           )
Creating second level with 50 topics
Copying phi for the second level. Phi shape: (22608, 50). First words: MultiIndex([('@text',           'tsd'),
            ('@text',        'кратер'),
            ('@text',           'cdk'),
            ('@text', 'внутриядерный'),
            ('@text',    'прибрежный'),
            ('@text',   'соотнесение'),
            ('@text', 'ангиоматозный'),
            ('@text',       'либерия'),
            ('@text', 'хориоменингит'),
            ('@text', 'герминативный')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic
!!! Bank Phi: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 0.0000000e+00]
 [0.0000000e+00 4.6962343e-12 2.6360690e-13 ... 1.0210013e-15
  1.8530490e-13 3.6378252e-13]
 [1.4469811e-10 2.5749894e-11 3.3435601e-15 ... 2.0192648e-08
  1.6489715e-12 2.0642731e-10]
 ...
 [1.5254298e-09 1.8358762e-14 5.5842836e-13 ... 3.4102385e-10
  1.2534354e-10 7.2917826e-12]
 [2.8210705e-09 3.4138630e-14 4.5676181e-14 ... 1.1665550e-10
  4.7846248e-11 9.8109186e-12]
 [1.0808079e-09 2.5750381e-14 1.2607799e-12 ... 7.2108869e-10
  1.8123050e-10 1.4470963e-11]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.1197182e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.1197182e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 4.9351955e-05]
 ...
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.1197182e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.3014077e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.1197182e-05]].
Bank scores: {'perplexity_score': 6578.611328125, 'coherence_20': 0.8636883273746088, 'diversity_euclidean': 0.08303577074911449, 'diversity_jensenshannon': 0.6852298806159961, 'diversity_hellinger': 0.8020148973018217, 'diversity_cosine': 0.8410535532397364, 'perplexity': 6578.611328125, 'ppl_fair': 6578.611328125, 'ppl_cheatty': 3181.440673828125}
 30%|█████████████▌                               | 6/20 [25:30<1:00:07, 257.67s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████                        | 1/2 [02:43<02:43, 163.77s/it]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 2/2 [02:44<00:00, 82.01s/it]
Using absoulte threshold: 1.5041606723306686.
Eliminating bcg topic before Hier. Cur |T| is 51, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'topic_20', 'topic_21', 'topic_22', 'topic_23',
       'topic_24', 'topic_25', 'topic_26', 'topic_27', 'topic_28', 'topic_29',
       'topic_30', 'topic_31', 'topic_32', 'topic_33', 'topic_34', 'topic_35',
       'topic_36', 'topic_37', 'topic_38', 'topic_39', 'topic_40', 'topic_41',
       'topic_42', 'topic_43', 'topic_44', 'topic_45', 'topic_46', 'topic_47',
       'topic_48', 'topic_49', 'background_50'],
      dtype='object').
Now |T| is 50, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'topic_20', 'topic_21', 'topic_22', 'topic_23',
       'topic_24', 'topic_25', 'topic_26', 'topic_27', 'topic_28', 'topic_29',
       'topic_30', 'topic_31', 'topic_32', 'topic_33', 'topic_34', 'topic_35',
       'topic_36', 'topic_37', 'topic_38', 'topic_39', 'topic_40', 'topic_41',
       'topic_42', 'topic_43', 'topic_44', 'topic_45', 'topic_46', 'topic_47',
       'topic_48', 'topic_49'],
      dtype='object').
Creating first level with 15 topics. Dictionary: artm.Dictionary(name=8b6b94ce-8444-492f-850a-42f0a4c559e1, num_entries=22608).
Copying phi for the first level. Phi shape: (22608, 15). First words: MultiIndex([('@text',           'tsd'),
            ('@text',        'кратер'),
            ('@text',           'cdk'),
            ('@text', 'внутриядерный'),
            ('@text',    'прибрежный'),
            ('@text',   'соотнесение'),
            ('@text', 'ангиоматозный'),
            ('@text',       'либерия'),
            ('@text', 'хориоменингит'),
            ('@text', 'герминативный')],
           )
Creating second level with 50 topics
Copying phi for the second level. Phi shape: (22608, 50). First words: MultiIndex([('@text',           'tsd'),
            ('@text',        'кратер'),
            ('@text',           'cdk'),
            ('@text', 'внутриядерный'),
            ('@text',    'прибрежный'),
            ('@text',   'соотнесение'),
            ('@text', 'ангиоматозный'),
            ('@text',       'либерия'),
            ('@text', 'хориоменингит'),
            ('@text', 'герминативный')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic
!!! Bank Phi: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 0.0000000e+00]
 [0.0000000e+00 3.7687770e-12 3.1422784e-13 ... 1.5040618e-14
  4.0450979e-13 2.4313164e-15]
 [1.0202468e-10 3.3251433e-11 4.0140044e-15 ... 7.0181480e-13
  2.1279493e-10 2.3994124e-09]
 ...
 [1.5873257e-09 1.4694472e-14 5.6872562e-13 ... 1.1737218e-10
  6.5202808e-12 1.2401818e-14]
 [2.8555494e-09 2.9407619e-14 2.9388672e-14 ... 3.7449686e-11
  6.4079267e-12 2.5109699e-13]
 [1.1651692e-09 2.1926825e-14 1.3303947e-12 ... 1.7822940e-10
  1.3639243e-11 3.4298810e-14]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.1689096e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.1689097e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 5.1520085e-05]
 ...
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.1689096e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.3585811e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.1689096e-05]].
Bank scores: {'perplexity_score': 6118.68994140625, 'coherence_20': 0.8546732017606098, 'diversity_euclidean': 0.08212281303395592, 'diversity_jensenshannon': 0.6835229238937232, 'diversity_hellinger': 0.799835023034149, 'diversity_cosine': 0.8371435015385994, 'perplexity': 6118.68994140625, 'ppl_fair': 6118.68994140625, 'ppl_cheatty': 3118.886474609375}
 35%|████████████████▍                              | 7/20 [29:49<55:55, 258.12s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████                        | 1/2 [02:42<02:42, 162.86s/it]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 2/2 [02:43<00:00, 81.57s/it]
Using absoulte threshold: 1.5041606723306686.
Eliminating bcg topic before Hier. Cur |T| is 51, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'topic_20', 'topic_21', 'topic_22', 'topic_23',
       'topic_24', 'topic_25', 'topic_26', 'topic_27', 'topic_28', 'topic_29',
       'topic_30', 'topic_31', 'topic_32', 'topic_33', 'topic_34', 'topic_35',
       'topic_36', 'topic_37', 'topic_38', 'topic_39', 'topic_40', 'topic_41',
       'topic_42', 'topic_43', 'topic_44', 'topic_45', 'topic_46', 'topic_47',
       'topic_48', 'topic_49', 'background_50'],
      dtype='object').
Now |T| is 50, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'topic_20', 'topic_21', 'topic_22', 'topic_23',
       'topic_24', 'topic_25', 'topic_26', 'topic_27', 'topic_28', 'topic_29',
       'topic_30', 'topic_31', 'topic_32', 'topic_33', 'topic_34', 'topic_35',
       'topic_36', 'topic_37', 'topic_38', 'topic_39', 'topic_40', 'topic_41',
       'topic_42', 'topic_43', 'topic_44', 'topic_45', 'topic_46', 'topic_47',
       'topic_48', 'topic_49'],
      dtype='object').
Creating first level with 16 topics. Dictionary: artm.Dictionary(name=8b6b94ce-8444-492f-850a-42f0a4c559e1, num_entries=22608).
Copying phi for the first level. Phi shape: (22608, 16). First words: MultiIndex([('@text',           'tsd'),
            ('@text',        'кратер'),
            ('@text',           'cdk'),
            ('@text', 'внутриядерный'),
            ('@text',    'прибрежный'),
            ('@text',   'соотнесение'),
            ('@text', 'ангиоматозный'),
            ('@text',       'либерия'),
            ('@text', 'хориоменингит'),
            ('@text', 'герминативный')],
           )
Creating second level with 50 topics
Copying phi for the second level. Phi shape: (22608, 50). First words: MultiIndex([('@text',           'tsd'),
            ('@text',        'кратер'),
            ('@text',           'cdk'),
            ('@text', 'внутриядерный'),
            ('@text',    'прибрежный'),
            ('@text',   'соотнесение'),
            ('@text', 'ангиоматозный'),
            ('@text',       'либерия'),
            ('@text', 'хориоменингит'),
            ('@text', 'герминативный')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic
!!! Bank Phi: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]].
!!! Bank model Phi: [[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 3.76877826e-12 3.14227919e-13 ... 1.50406217e-14
  4.04509976e-13 2.43131723e-15]
 [1.02024666e-10 3.32514259e-11 4.01400401e-15 ... 7.01814800e-13
  2.12794990e-10 2.39941267e-09]
 ...
 [1.58732572e-09 1.46944682e-14 5.68725785e-13 ... 1.17372168e-10
  6.52027781e-12 1.24018261e-14]
 [2.85554935e-09 2.94076083e-14 2.93886822e-14 ... 3.74496753e-11
  6.40791977e-12 2.51097022e-13]
 [1.16516885e-09 2.19268116e-14 1.33039521e-12 ... 1.78229306e-10
  1.36392330e-11 3.42988204e-14]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.1689097e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.1689096e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 5.1520103e-05]
 ...
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.1689096e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.3585809e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.1689096e-05]].
Bank scores: {'perplexity_score': 6118.68994140625, 'coherence_20': 0.8546732017606098, 'diversity_euclidean': 0.08212281303395591, 'diversity_jensenshannon': 0.6835229238937127, 'diversity_hellinger': 0.799835023034147, 'diversity_cosine': 0.8371435015385986, 'perplexity': 6118.68994140625, 'ppl_fair': 6118.68994140625, 'ppl_cheatty': 3118.886474609375}
 40%|██████████████████▊                            | 8/20 [34:04<51:26, 257.19s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████                        | 1/2 [02:43<02:43, 163.50s/it]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 2/2 [02:43<00:00, 81.87s/it]
Using absoulte threshold: 1.5041606723306686.
Eliminating bcg topic before Hier. Cur |T| is 51, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'topic_20', 'topic_21', 'topic_22', 'topic_23',
       'topic_24', 'topic_25', 'topic_26', 'topic_27', 'topic_28', 'topic_29',
       'topic_30', 'topic_31', 'topic_32', 'topic_33', 'topic_34', 'topic_35',
       'topic_36', 'topic_37', 'topic_38', 'topic_39', 'topic_40', 'topic_41',
       'topic_42', 'topic_43', 'topic_44', 'topic_45', 'topic_46', 'topic_47',
       'topic_48', 'topic_49', 'background_50'],
      dtype='object').
Now |T| is 50, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'topic_20', 'topic_21', 'topic_22', 'topic_23',
       'topic_24', 'topic_25', 'topic_26', 'topic_27', 'topic_28', 'topic_29',
       'topic_30', 'topic_31', 'topic_32', 'topic_33', 'topic_34', 'topic_35',
       'topic_36', 'topic_37', 'topic_38', 'topic_39', 'topic_40', 'topic_41',
       'topic_42', 'topic_43', 'topic_44', 'topic_45', 'topic_46', 'topic_47',
       'topic_48', 'topic_49'],
      dtype='object').
Creating first level with 16 topics. Dictionary: artm.Dictionary(name=8b6b94ce-8444-492f-850a-42f0a4c559e1, num_entries=22608).
Copying phi for the first level. Phi shape: (22608, 16). First words: MultiIndex([('@text',           'tsd'),
            ('@text',        'кратер'),
            ('@text',           'cdk'),
            ('@text', 'внутриядерный'),
            ('@text',    'прибрежный'),
            ('@text',   'соотнесение'),
            ('@text', 'ангиоматозный'),
            ('@text',       'либерия'),
            ('@text', 'хориоменингит'),
            ('@text', 'герминативный')],
           )
Creating second level with 50 topics
Copying phi for the second level. Phi shape: (22608, 50). First words: MultiIndex([('@text',           'tsd'),
            ('@text',        'кратер'),
            ('@text',           'cdk'),
            ('@text', 'внутриядерный'),
            ('@text',    'прибрежный'),
            ('@text',   'соотнесение'),
            ('@text', 'ангиоматозный'),
            ('@text',       'либерия'),
            ('@text', 'хориоменингит'),
            ('@text', 'герминативный')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic
!!! Bank Phi: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]].
!!! Bank model Phi: [[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 3.76877739e-12 3.14227919e-13 ... 1.50406184e-14
  4.04509895e-13 2.43131723e-15]
 [1.02024666e-10 3.32514363e-11 4.01400443e-15 ... 7.01814800e-13
  2.12794948e-10 2.39941156e-09]
 ...
 [1.58732572e-09 1.46944699e-14 5.68725785e-13 ... 1.17372181e-10
  6.52027954e-12 1.24018261e-14]
 [2.85554935e-09 2.94076185e-14 2.93886890e-14 ... 3.74496788e-11
  6.40792107e-12 2.51097022e-13]
 [1.16516907e-09 2.19268166e-14 1.33039532e-12 ... 1.78229334e-10
  1.36392364e-11 3.42988204e-14]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.1689098e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.1689099e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 5.1520092e-05]
 ...
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.1689098e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.3585811e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.1689098e-05]].
Bank scores: {'perplexity_score': 6118.68994140625, 'coherence_20': 0.8546732017606098, 'diversity_euclidean': 0.08212281303395602, 'diversity_jensenshannon': 0.6835229238937334, 'diversity_hellinger': 0.7998350230341433, 'diversity_cosine': 0.8371435015386036, 'perplexity': 6118.68994140625, 'ppl_fair': 6118.68994140625, 'ppl_cheatty': 3118.886474609375}
 45%|█████████████████████▏                         | 9/20 [38:21<47:08, 257.16s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████                        | 1/2 [02:43<02:43, 163.61s/it]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 2/2 [02:43<00:00, 81.94s/it]
Using absoulte threshold: 1.5041606723306686.
Eliminating bcg topic before Hier. Cur |T| is 51, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'topic_20', 'topic_21', 'topic_22', 'topic_23',
       'topic_24', 'topic_25', 'topic_26', 'topic_27', 'topic_28', 'topic_29',
       'topic_30', 'topic_31', 'topic_32', 'topic_33', 'topic_34', 'topic_35',
       'topic_36', 'topic_37', 'topic_38', 'topic_39', 'topic_40', 'topic_41',
       'topic_42', 'topic_43', 'topic_44', 'topic_45', 'topic_46', 'topic_47',
       'topic_48', 'topic_49', 'background_50'],
      dtype='object').
Now |T| is 50, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'topic_20', 'topic_21', 'topic_22', 'topic_23',
       'topic_24', 'topic_25', 'topic_26', 'topic_27', 'topic_28', 'topic_29',
       'topic_30', 'topic_31', 'topic_32', 'topic_33', 'topic_34', 'topic_35',
       'topic_36', 'topic_37', 'topic_38', 'topic_39', 'topic_40', 'topic_41',
       'topic_42', 'topic_43', 'topic_44', 'topic_45', 'topic_46', 'topic_47',
       'topic_48', 'topic_49'],
      dtype='object').
Creating first level with 16 topics. Dictionary: artm.Dictionary(name=8b6b94ce-8444-492f-850a-42f0a4c559e1, num_entries=22608).
Copying phi for the first level. Phi shape: (22608, 16). First words: MultiIndex([('@text',           'tsd'),
            ('@text',        'кратер'),
            ('@text',           'cdk'),
            ('@text', 'внутриядерный'),
            ('@text',    'прибрежный'),
            ('@text',   'соотнесение'),
            ('@text', 'ангиоматозный'),
            ('@text',       'либерия'),
            ('@text', 'хориоменингит'),
            ('@text', 'герминативный')],
           )
Creating second level with 50 topics
Copying phi for the second level. Phi shape: (22608, 50). First words: MultiIndex([('@text',           'tsd'),
            ('@text',        'кратер'),
            ('@text',           'cdk'),
            ('@text', 'внутриядерный'),
            ('@text',    'прибрежный'),
            ('@text',   'соотнесение'),
            ('@text', 'ангиоматозный'),
            ('@text',       'либерия'),
            ('@text', 'хориоменингит'),
            ('@text', 'герминативный')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic
!!! Bank Phi: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 0.0000000e+00]
 [0.0000000e+00 3.3260291e-12 3.3209850e-13 ... 4.0163722e-13
  2.6731996e-15 0.0000000e+00]
 [7.4218465e-11 3.0441694e-11 3.7446420e-15 ... 1.9295690e-10
  1.7283336e-09 0.0000000e+00]
 ...
 [1.6697880e-09 1.8981082e-14 6.9317241e-13 ... 7.9593589e-12
  1.4080484e-14 1.3330571e-12]
 [2.8830061e-09 3.6065118e-14 3.5923423e-14 ... 7.0394263e-12
  2.6658190e-13 7.4226150e-13]
 [1.2744947e-09 2.9472318e-14 1.6920550e-12 ... 1.7271651e-11
  3.9813683e-14 1.4686486e-12]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.1718882e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.1718882e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 5.1651386e-05]
 ...
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.1718882e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.3620430e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.1718882e-05]].
Bank scores: {'perplexity_score': 6009.52392578125, 'coherence_20': 0.879793557002632, 'diversity_euclidean': 0.08452294768902084, 'diversity_jensenshannon': 0.68371145159391, 'diversity_hellinger': 0.8002430413874075, 'diversity_cosine': 0.8376841407387182, 'perplexity': 6009.52392578125, 'ppl_fair': 6009.52392578125, 'ppl_cheatty': 3091.91357421875}
 50%|███████████████████████                       | 10/20 [42:45<43:11, 259.17s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████                        | 1/2 [02:43<02:43, 163.88s/it]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 2/2 [02:44<00:00, 82.08s/it]
Using absoulte threshold: 1.5041606723306686.
Eliminating bcg topic before Hier. Cur |T| is 51, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'topic_20', 'topic_21', 'topic_22', 'topic_23',
       'topic_24', 'topic_25', 'topic_26', 'topic_27', 'topic_28', 'topic_29',
       'topic_30', 'topic_31', 'topic_32', 'topic_33', 'topic_34', 'topic_35',
       'topic_36', 'topic_37', 'topic_38', 'topic_39', 'topic_40', 'topic_41',
       'topic_42', 'topic_43', 'topic_44', 'topic_45', 'topic_46', 'topic_47',
       'topic_48', 'topic_49', 'background_50'],
      dtype='object').
Now |T| is 50, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'topic_20', 'topic_21', 'topic_22', 'topic_23',
       'topic_24', 'topic_25', 'topic_26', 'topic_27', 'topic_28', 'topic_29',
       'topic_30', 'topic_31', 'topic_32', 'topic_33', 'topic_34', 'topic_35',
       'topic_36', 'topic_37', 'topic_38', 'topic_39', 'topic_40', 'topic_41',
       'topic_42', 'topic_43', 'topic_44', 'topic_45', 'topic_46', 'topic_47',
       'topic_48', 'topic_49'],
      dtype='object').
Creating first level with 17 topics. Dictionary: artm.Dictionary(name=8b6b94ce-8444-492f-850a-42f0a4c559e1, num_entries=22608).
Copying phi for the first level. Phi shape: (22608, 17). First words: MultiIndex([('@text',           'tsd'),
            ('@text',        'кратер'),
            ('@text',           'cdk'),
            ('@text', 'внутриядерный'),
            ('@text',    'прибрежный'),
            ('@text',   'соотнесение'),
            ('@text', 'ангиоматозный'),
            ('@text',       'либерия'),
            ('@text', 'хориоменингит'),
            ('@text', 'герминативный')],
           )
Creating second level with 50 topics
Copying phi for the second level. Phi shape: (22608, 50). First words: MultiIndex([('@text',           'tsd'),
            ('@text',        'кратер'),
            ('@text',           'cdk'),
            ('@text', 'внутриядерный'),
            ('@text',    'прибрежный'),
            ('@text',   'соотнесение'),
            ('@text', 'ангиоматозный'),
            ('@text',       'либерия'),
            ('@text', 'хориоменингит'),
            ('@text', 'герминативный')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic
!!! Bank Phi: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 0.0000000e+00]
 [1.6261509e-13 6.5605100e-16 7.9169805e-14 ... 3.0617938e-16
  0.0000000e+00 7.6882767e-16]
 [7.7946698e-11 2.2034042e-15 2.4012403e-11 ... 6.5383549e-13
  1.5424510e-12 4.8625770e-10]
 ...
 [1.8830349e-13 9.4617127e-12 1.6919910e-14 ... 9.7513381e-15
  4.0757367e-12 4.2838992e-15]
 [9.6994373e-14 3.7688058e-11 1.1801191e-15 ... 1.4804610e-12
  3.1644850e-11 3.7179132e-14]
 [5.1335882e-14 6.1721440e-12 1.5062897e-14 ... 8.4181802e-15
  5.9274664e-12 1.7072518e-15]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.1544135e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.1544135e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 5.0881183e-05]
 ...
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.1544135e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.3417328e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.1544135e-05]].
Bank scores: {'perplexity_score': 6245.0927734375, 'coherence_20': 0.8589753599319219, 'diversity_euclidean': 0.08626277817878962, 'diversity_jensenshannon': 0.6799617278506102, 'diversity_hellinger': 0.7956372749668716, 'diversity_cosine': 0.8371857545824827, 'perplexity': 6245.0927734375, 'ppl_fair': 6245.0927734375, 'ppl_cheatty': 3121.1064453125}
 55%|█████████████████████████▎                    | 11/20 [47:08<39:05, 260.57s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████                        | 1/2 [02:46<02:46, 166.13s/it]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 2/2 [02:46<00:00, 83.20s/it]
Using absoulte threshold: 1.5041606723306686.
Eliminating bcg topic before Hier. Cur |T| is 51, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'topic_20', 'topic_21', 'topic_22', 'topic_23',
       'topic_24', 'topic_25', 'topic_26', 'topic_27', 'topic_28', 'topic_29',
       'topic_30', 'topic_31', 'topic_32', 'topic_33', 'topic_34', 'topic_35',
       'topic_36', 'topic_37', 'topic_38', 'topic_39', 'topic_40', 'topic_41',
       'topic_42', 'topic_43', 'topic_44', 'topic_45', 'topic_46', 'topic_47',
       'topic_48', 'topic_49', 'background_50'],
      dtype='object').
Now |T| is 50, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'topic_20', 'topic_21', 'topic_22', 'topic_23',
       'topic_24', 'topic_25', 'topic_26', 'topic_27', 'topic_28', 'topic_29',
       'topic_30', 'topic_31', 'topic_32', 'topic_33', 'topic_34', 'topic_35',
       'topic_36', 'topic_37', 'topic_38', 'topic_39', 'topic_40', 'topic_41',
       'topic_42', 'topic_43', 'topic_44', 'topic_45', 'topic_46', 'topic_47',
       'topic_48', 'topic_49'],
      dtype='object').
Creating first level with 17 topics. Dictionary: artm.Dictionary(name=8b6b94ce-8444-492f-850a-42f0a4c559e1, num_entries=22608).
Copying phi for the first level. Phi shape: (22608, 17). First words: MultiIndex([('@text',           'tsd'),
            ('@text',        'кратер'),
            ('@text',           'cdk'),
            ('@text', 'внутриядерный'),
            ('@text',    'прибрежный'),
            ('@text',   'соотнесение'),
            ('@text', 'ангиоматозный'),
            ('@text',       'либерия'),
            ('@text', 'хориоменингит'),
            ('@text', 'герминативный')],
           )
Creating second level with 50 topics
Copying phi for the second level. Phi shape: (22608, 50). First words: MultiIndex([('@text',           'tsd'),
            ('@text',        'кратер'),
            ('@text',           'cdk'),
            ('@text', 'внутриядерный'),
            ('@text',    'прибрежный'),
            ('@text',   'соотнесение'),
            ('@text', 'ангиоматозный'),
            ('@text',       'либерия'),
            ('@text', 'хориоменингит'),
            ('@text', 'герминативный')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic
!!! Bank Phi: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 0.0000000e+00]
 [1.6261513e-13 6.5605142e-16 7.9169805e-14 ... 3.0617954e-16
  0.0000000e+00 7.6882767e-16]
 [7.7946739e-11 2.2034080e-15 2.4012400e-11 ... 6.5383598e-13
  1.5424525e-12 4.8625781e-10]
 ...
 [1.8830341e-13 9.4617023e-12 1.6919895e-14 ... 9.7513338e-15
  4.0757345e-12 4.2838979e-15]
 [9.6994312e-14 3.7688023e-11 1.1801179e-15 ... 1.4804610e-12
  3.1644840e-11 3.7179115e-14]
 [5.1335865e-14 6.1721362e-12 1.5062883e-14 ... 8.4181793e-15
  5.9274651e-12 1.7072516e-15]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.1544135e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.1544135e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 5.0881190e-05]
 ...
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.1544135e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.3417328e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.1544135e-05]].
Bank scores: {'perplexity_score': 6245.0927734375, 'coherence_20': 0.8589753599319219, 'diversity_euclidean': 0.08626277817878955, 'diversity_jensenshannon': 0.6799617278506084, 'diversity_hellinger': 0.7956372749666923, 'diversity_cosine': 0.8371857545824846, 'perplexity': 6245.0927734375, 'ppl_fair': 6245.0927734375, 'ppl_cheatty': 3121.1064453125}
 60%|███████████████████████████▌                  | 12/20 [51:29<34:44, 260.52s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████                        | 1/2 [02:44<02:44, 164.99s/it]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 2/2 [02:45<00:00, 82.63s/it]
Using absoulte threshold: 1.5041606723306686.
Eliminating bcg topic before Hier. Cur |T| is 51, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'topic_20', 'topic_21', 'topic_22', 'topic_23',
       'topic_24', 'topic_25', 'topic_26', 'topic_27', 'topic_28', 'topic_29',
       'topic_30', 'topic_31', 'topic_32', 'topic_33', 'topic_34', 'topic_35',
       'topic_36', 'topic_37', 'topic_38', 'topic_39', 'topic_40', 'topic_41',
       'topic_42', 'topic_43', 'topic_44', 'topic_45', 'topic_46', 'topic_47',
       'topic_48', 'topic_49', 'background_50'],
      dtype='object').
Now |T| is 50, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'topic_20', 'topic_21', 'topic_22', 'topic_23',
       'topic_24', 'topic_25', 'topic_26', 'topic_27', 'topic_28', 'topic_29',
       'topic_30', 'topic_31', 'topic_32', 'topic_33', 'topic_34', 'topic_35',
       'topic_36', 'topic_37', 'topic_38', 'topic_39', 'topic_40', 'topic_41',
       'topic_42', 'topic_43', 'topic_44', 'topic_45', 'topic_46', 'topic_47',
       'topic_48', 'topic_49'],
      dtype='object').
Creating first level with 17 topics. Dictionary: artm.Dictionary(name=8b6b94ce-8444-492f-850a-42f0a4c559e1, num_entries=22608).
Copying phi for the first level. Phi shape: (22608, 17). First words: MultiIndex([('@text',           'tsd'),
            ('@text',        'кратер'),
            ('@text',           'cdk'),
            ('@text', 'внутриядерный'),
            ('@text',    'прибрежный'),
            ('@text',   'соотнесение'),
            ('@text', 'ангиоматозный'),
            ('@text',       'либерия'),
            ('@text', 'хориоменингит'),
            ('@text', 'герминативный')],
           )
Creating second level with 50 topics
Copying phi for the second level. Phi shape: (22608, 50). First words: MultiIndex([('@text',           'tsd'),
            ('@text',        'кратер'),
            ('@text',           'cdk'),
            ('@text', 'внутриядерный'),
            ('@text',    'прибрежный'),
            ('@text',   'соотнесение'),
            ('@text', 'ангиоматозный'),
            ('@text',       'либерия'),
            ('@text', 'хориоменингит'),
            ('@text', 'герминативный')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic
!!! Bank Phi: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 0.0000000e+00]
 [1.6261511e-13 6.5605126e-16 7.9169805e-14 ... 3.0617946e-16
  0.0000000e+00 7.6882782e-16]
 [7.7946712e-11 2.2034084e-15 2.4012395e-11 ... 6.5383609e-13
  1.5424519e-12 4.8625792e-10]
 ...
 [1.8830360e-13 9.4617118e-12 1.6919910e-14 ... 9.7513364e-15
  4.0757371e-12 4.2838992e-15]
 [9.6994380e-14 3.7688044e-11 1.1801187e-15 ... 1.4804610e-12
  3.1644846e-11 3.7179122e-14]
 [5.1335902e-14 6.1721418e-12 1.5062895e-14 ... 8.4181793e-15
  5.9274677e-12 1.7072518e-15]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.1544137e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.1544137e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 5.0881190e-05]
 ...
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.1544137e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.3417330e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.1544137e-05]].
Bank scores: {'perplexity_score': 6245.0927734375, 'coherence_20': 0.8589753599319219, 'diversity_euclidean': 0.08626277817878966, 'diversity_jensenshannon': 0.6799617278506221, 'diversity_hellinger': 0.7956372749668743, 'diversity_cosine': 0.8371857545824827, 'perplexity': 6245.0927734375, 'ppl_fair': 6245.0927734375, 'ppl_cheatty': 3121.106689453125}
 65%|█████████████████████████████▉                | 13/20 [55:48<30:21, 260.20s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████                        | 1/2 [02:44<02:44, 164.59s/it]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 2/2 [02:44<00:00, 82.43s/it]
Using absoulte threshold: 1.5041606723306686.
Eliminating bcg topic before Hier. Cur |T| is 51, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'topic_20', 'topic_21', 'topic_22', 'topic_23',
       'topic_24', 'topic_25', 'topic_26', 'topic_27', 'topic_28', 'topic_29',
       'topic_30', 'topic_31', 'topic_32', 'topic_33', 'topic_34', 'topic_35',
       'topic_36', 'topic_37', 'topic_38', 'topic_39', 'topic_40', 'topic_41',
       'topic_42', 'topic_43', 'topic_44', 'topic_45', 'topic_46', 'topic_47',
       'topic_48', 'topic_49', 'background_50'],
      dtype='object').
Now |T| is 50, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'topic_20', 'topic_21', 'topic_22', 'topic_23',
       'topic_24', 'topic_25', 'topic_26', 'topic_27', 'topic_28', 'topic_29',
       'topic_30', 'topic_31', 'topic_32', 'topic_33', 'topic_34', 'topic_35',
       'topic_36', 'topic_37', 'topic_38', 'topic_39', 'topic_40', 'topic_41',
       'topic_42', 'topic_43', 'topic_44', 'topic_45', 'topic_46', 'topic_47',
       'topic_48', 'topic_49'],
      dtype='object').
Creating first level with 17 topics. Dictionary: artm.Dictionary(name=8b6b94ce-8444-492f-850a-42f0a4c559e1, num_entries=22608).
Copying phi for the first level. Phi shape: (22608, 17). First words: MultiIndex([('@text',           'tsd'),
            ('@text',        'кратер'),
            ('@text',           'cdk'),
            ('@text', 'внутриядерный'),
            ('@text',    'прибрежный'),
            ('@text',   'соотнесение'),
            ('@text', 'ангиоматозный'),
            ('@text',       'либерия'),
            ('@text', 'хориоменингит'),
            ('@text', 'герминативный')],
           )
Creating second level with 50 topics
Copying phi for the second level. Phi shape: (22608, 50). First words: MultiIndex([('@text',           'tsd'),
            ('@text',        'кратер'),
            ('@text',           'cdk'),
            ('@text', 'внутриядерный'),
            ('@text',    'прибрежный'),
            ('@text',   'соотнесение'),
            ('@text', 'ангиоматозный'),
            ('@text',       'либерия'),
            ('@text', 'хориоменингит'),
            ('@text', 'герминативный')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic
!!! Bank Phi: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 0.0000000e+00]
 [1.4728391e-12 4.7476861e-13 7.4187083e-14 ... 5.7329239e-13
  0.0000000e+00 2.2085818e-11]
 [2.9567419e-15 0.0000000e+00 2.7526372e-14 ... 8.3385826e-10
  6.5962029e-16 2.2154817e-08]
 ...
 [1.1557531e-13 4.3127498e-12 8.3972627e-15 ... 1.9727605e-15
  4.1005746e-16 1.4097088e-13]
 [5.0235268e-14 2.1414754e-11 6.0752898e-16 ... 3.3416707e-14
  4.1147781e-16 1.9175137e-14]
 [2.9932840e-14 2.7042643e-12 7.2211083e-15 ... 2.6879718e-15
  1.5772803e-16 6.2021358e-14]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.1697695e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.1697696e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 5.1558003e-05]
 ...
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.1697695e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.3595804e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.1697695e-05]].
Bank scores: {'perplexity_score': 6192.32958984375, 'coherence_20': 0.879015619821203, 'diversity_euclidean': 0.08419977046175997, 'diversity_jensenshannon': 0.6718767097760334, 'diversity_hellinger': 0.7857481543977852, 'diversity_cosine': 0.8243398060364351, 'perplexity': 6192.32958984375, 'ppl_fair': 6192.32958984375, 'ppl_cheatty': 3092.301513671875}
 70%|██████████████████████████████▊             | 14/20 [1:00:16<26:14, 262.45s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████                        | 1/2 [02:43<02:43, 163.74s/it]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 2/2 [02:44<00:00, 82.00s/it]
Using absoulte threshold: 1.5041606723306686.
Eliminating bcg topic before Hier. Cur |T| is 51, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'topic_20', 'topic_21', 'topic_22', 'topic_23',
       'topic_24', 'topic_25', 'topic_26', 'topic_27', 'topic_28', 'topic_29',
       'topic_30', 'topic_31', 'topic_32', 'topic_33', 'topic_34', 'topic_35',
       'topic_36', 'topic_37', 'topic_38', 'topic_39', 'topic_40', 'topic_41',
       'topic_42', 'topic_43', 'topic_44', 'topic_45', 'topic_46', 'topic_47',
       'topic_48', 'topic_49', 'background_50'],
      dtype='object').
Now |T| is 50, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'topic_20', 'topic_21', 'topic_22', 'topic_23',
       'topic_24', 'topic_25', 'topic_26', 'topic_27', 'topic_28', 'topic_29',
       'topic_30', 'topic_31', 'topic_32', 'topic_33', 'topic_34', 'topic_35',
       'topic_36', 'topic_37', 'topic_38', 'topic_39', 'topic_40', 'topic_41',
       'topic_42', 'topic_43', 'topic_44', 'topic_45', 'topic_46', 'topic_47',
       'topic_48', 'topic_49'],
      dtype='object').
Creating first level with 18 topics. Dictionary: artm.Dictionary(name=8b6b94ce-8444-492f-850a-42f0a4c559e1, num_entries=22608).
Copying phi for the first level. Phi shape: (22608, 18). First words: MultiIndex([('@text',           'tsd'),
            ('@text',        'кратер'),
            ('@text',           'cdk'),
            ('@text', 'внутриядерный'),
            ('@text',    'прибрежный'),
            ('@text',   'соотнесение'),
            ('@text', 'ангиоматозный'),
            ('@text',       'либерия'),
            ('@text', 'хориоменингит'),
            ('@text', 'герминативный')],
           )
Creating second level with 50 topics
Copying phi for the second level. Phi shape: (22608, 50). First words: MultiIndex([('@text',           'tsd'),
            ('@text',        'кратер'),
            ('@text',           'cdk'),
            ('@text', 'внутриядерный'),
            ('@text',    'прибрежный'),
            ('@text',   'соотнесение'),
            ('@text', 'ангиоматозный'),
            ('@text',       'либерия'),
            ('@text', 'хориоменингит'),
            ('@text', 'герминативный')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic
!!! Bank Phi: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 0.0000000e+00]
 [1.4728398e-12 4.7476888e-13 7.4187205e-14 ... 5.7329272e-13
  0.0000000e+00 2.2085792e-11]
 [2.9567440e-15 0.0000000e+00 2.7526387e-14 ... 8.3385915e-10
  6.5962151e-16 2.2154813e-08]
 ...
 [1.1557557e-13 4.3127559e-12 8.3972729e-15 ... 1.9727618e-15
  4.1005768e-16 1.4097057e-13]
 [5.0235339e-14 2.1414773e-11 6.0752946e-16 ... 3.3416724e-14
  4.1147783e-16 1.9175086e-14]
 [2.9932908e-14 2.7042691e-12 7.2211160e-15 ... 2.6879739e-15
  1.5772810e-16 6.2021223e-14]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]].
!!! Bank model Phi: [[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.16976935e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.16976935e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 5.15579777e-05]
 ...
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.16976935e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.35958035e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.16976935e-05]].
Bank scores: {'perplexity_score': 6192.32958984375, 'coherence_20': 0.879015619821203, 'diversity_euclidean': 0.08419977046176003, 'diversity_jensenshannon': 0.6718767097760489, 'diversity_hellinger': 0.7857481543977705, 'diversity_cosine': 0.8243398060364361, 'perplexity': 6192.32958984375, 'ppl_fair': 6192.32958984375, 'ppl_cheatty': 3092.301513671875}
 75%|█████████████████████████████████           | 15/20 [1:04:34<21:44, 261.00s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████                        | 1/2 [02:43<02:43, 163.69s/it]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 2/2 [02:43<00:00, 81.98s/it]
Using absoulte threshold: 1.5041606723306686.
Eliminating bcg topic before Hier. Cur |T| is 51, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'topic_20', 'topic_21', 'topic_22', 'topic_23',
       'topic_24', 'topic_25', 'topic_26', 'topic_27', 'topic_28', 'topic_29',
       'topic_30', 'topic_31', 'topic_32', 'topic_33', 'topic_34', 'topic_35',
       'topic_36', 'topic_37', 'topic_38', 'topic_39', 'topic_40', 'topic_41',
       'topic_42', 'topic_43', 'topic_44', 'topic_45', 'topic_46', 'topic_47',
       'topic_48', 'topic_49', 'background_50'],
      dtype='object').
Now |T| is 50, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'topic_20', 'topic_21', 'topic_22', 'topic_23',
       'topic_24', 'topic_25', 'topic_26', 'topic_27', 'topic_28', 'topic_29',
       'topic_30', 'topic_31', 'topic_32', 'topic_33', 'topic_34', 'topic_35',
       'topic_36', 'topic_37', 'topic_38', 'topic_39', 'topic_40', 'topic_41',
       'topic_42', 'topic_43', 'topic_44', 'topic_45', 'topic_46', 'topic_47',
       'topic_48', 'topic_49'],
      dtype='object').
Creating first level with 18 topics. Dictionary: artm.Dictionary(name=8b6b94ce-8444-492f-850a-42f0a4c559e1, num_entries=22608).
Copying phi for the first level. Phi shape: (22608, 18). First words: MultiIndex([('@text',           'tsd'),
            ('@text',        'кратер'),
            ('@text',           'cdk'),
            ('@text', 'внутриядерный'),
            ('@text',    'прибрежный'),
            ('@text',   'соотнесение'),
            ('@text', 'ангиоматозный'),
            ('@text',       'либерия'),
            ('@text', 'хориоменингит'),
            ('@text', 'герминативный')],
           )
Creating second level with 50 topics
Copying phi for the second level. Phi shape: (22608, 50). First words: MultiIndex([('@text',           'tsd'),
            ('@text',        'кратер'),
            ('@text',           'cdk'),
            ('@text', 'внутриядерный'),
            ('@text',    'прибрежный'),
            ('@text',   'соотнесение'),
            ('@text', 'ангиоматозный'),
            ('@text',       'либерия'),
            ('@text', 'хориоменингит'),
            ('@text', 'герминативный')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic
!!! Bank Phi: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]].
!!! Bank model Phi: [[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [2.65792904e-16 1.40873993e-16 1.04811698e-15 ... 0.00000000e+00
  1.64871941e-13 0.00000000e+00]
 [1.31460530e-13 6.10393626e-14 2.02879172e-15 ... 0.00000000e+00
  5.90721032e-15 5.39777082e-15]
 ...
 [7.26464722e-10 8.69664058e-15 1.40311592e-14 ... 8.89792441e-15
  1.07172181e-12 4.21093282e-12]
 [1.00653035e-10 5.34604252e-15 2.77197779e-15 ... 2.29389143e-15
  1.07629790e-12 3.21860458e-13]
 [2.35532954e-10 6.99263899e-15 1.43936936e-14 ... 5.07550993e-15
  3.38852346e-13 5.08760005e-12]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.2455394e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.2455395e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 5.4897580e-05]
 ...
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.2455395e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.4476451e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.2455395e-05]].
Bank scores: {'perplexity_score': 5572.3994140625, 'coherence_20': 0.8986363828762871, 'diversity_euclidean': 0.08671431828284885, 'diversity_jensenshannon': 0.6755251142945379, 'diversity_hellinger': 0.7901147401208509, 'diversity_cosine': 0.834609624782907, 'perplexity': 5572.3994140625, 'ppl_fair': 5572.3994140625, 'ppl_cheatty': 3008.926025390625}
 80%|███████████████████████████████████▏        | 16/20 [1:09:08<17:40, 265.16s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████                        | 1/2 [02:43<02:43, 163.86s/it]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 2/2 [02:44<00:00, 82.06s/it]
Using absoulte threshold: 1.5041606723306686.
Eliminating bcg topic before Hier. Cur |T| is 51, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'topic_20', 'topic_21', 'topic_22', 'topic_23',
       'topic_24', 'topic_25', 'topic_26', 'topic_27', 'topic_28', 'topic_29',
       'topic_30', 'topic_31', 'topic_32', 'topic_33', 'topic_34', 'topic_35',
       'topic_36', 'topic_37', 'topic_38', 'topic_39', 'topic_40', 'topic_41',
       'topic_42', 'topic_43', 'topic_44', 'topic_45', 'topic_46', 'topic_47',
       'topic_48', 'topic_49', 'background_50'],
      dtype='object').
Now |T| is 50, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'topic_20', 'topic_21', 'topic_22', 'topic_23',
       'topic_24', 'topic_25', 'topic_26', 'topic_27', 'topic_28', 'topic_29',
       'topic_30', 'topic_31', 'topic_32', 'topic_33', 'topic_34', 'topic_35',
       'topic_36', 'topic_37', 'topic_38', 'topic_39', 'topic_40', 'topic_41',
       'topic_42', 'topic_43', 'topic_44', 'topic_45', 'topic_46', 'topic_47',
       'topic_48', 'topic_49'],
      dtype='object').
Creating first level with 20 topics. Dictionary: artm.Dictionary(name=8b6b94ce-8444-492f-850a-42f0a4c559e1, num_entries=22608).
Copying phi for the first level. Phi shape: (22608, 20). First words: MultiIndex([('@text',           'tsd'),
            ('@text',        'кратер'),
            ('@text',           'cdk'),
            ('@text', 'внутриядерный'),
            ('@text',    'прибрежный'),
            ('@text',   'соотнесение'),
            ('@text', 'ангиоматозный'),
            ('@text',       'либерия'),
            ('@text', 'хориоменингит'),
            ('@text', 'герминативный')],
           )
Creating second level with 50 topics
Copying phi for the second level. Phi shape: (22608, 50). First words: MultiIndex([('@text',           'tsd'),
            ('@text',        'кратер'),
            ('@text',           'cdk'),
            ('@text', 'внутриядерный'),
            ('@text',    'прибрежный'),
            ('@text',   'соотнесение'),
            ('@text', 'ангиоматозный'),
            ('@text',       'либерия'),
            ('@text', 'хориоменингит'),
            ('@text', 'герминативный')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic
!!! Bank Phi: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]].
!!! Bank model Phi: [[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [7.20337571e-16 0.00000000e+00 1.13816874e-13 ... 1.98537342e-09
  0.00000000e+00 0.00000000e+00]
 [3.37181184e-14 1.94674270e-16 2.02307890e-16 ... 4.07987903e-15
  8.09207475e-12 7.90876804e-13]
 ...
 [4.89817797e-10 1.38654042e-14 5.16000295e-16 ... 1.42775461e-15
  1.23834424e-11 2.44331860e-10]
 [3.85126028e-11 2.66571382e-14 0.00000000e+00 ... 4.84228407e-16
  8.72496519e-12 1.39266211e-11]
 [1.19850713e-10 5.77130134e-15 5.39067173e-16 ... 3.12078490e-16
  1.13676455e-11 1.28325114e-10]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.3117168e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.3117168e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 5.7814381e-05]
 ...
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.3117168e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.5245606e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.3117168e-05]].
Bank scores: {'perplexity_score': 5099.79833984375, 'coherence_20': 0.8789142342668147, 'diversity_euclidean': 0.0864614383900119, 'diversity_jensenshannon': 0.6791605191890726, 'diversity_hellinger': 0.7944052844625875, 'diversity_cosine': 0.8400400480750483, 'perplexity': 5099.79833984375, 'ppl_fair': 5099.79833984375, 'ppl_cheatty': 2982.079833984375}
 85%|█████████████████████████████████████▍      | 17/20 [1:13:41<13:21, 267.25s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████                        | 1/2 [02:43<02:43, 163.71s/it]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 2/2 [02:43<00:00, 82.00s/it]
Using absoulte threshold: 1.5041606723306686.
Eliminating bcg topic before Hier. Cur |T| is 51, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'topic_20', 'topic_21', 'topic_22', 'topic_23',
       'topic_24', 'topic_25', 'topic_26', 'topic_27', 'topic_28', 'topic_29',
       'topic_30', 'topic_31', 'topic_32', 'topic_33', 'topic_34', 'topic_35',
       'topic_36', 'topic_37', 'topic_38', 'topic_39', 'topic_40', 'topic_41',
       'topic_42', 'topic_43', 'topic_44', 'topic_45', 'topic_46', 'topic_47',
       'topic_48', 'topic_49', 'background_50'],
      dtype='object').
Now |T| is 50, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'topic_20', 'topic_21', 'topic_22', 'topic_23',
       'topic_24', 'topic_25', 'topic_26', 'topic_27', 'topic_28', 'topic_29',
       'topic_30', 'topic_31', 'topic_32', 'topic_33', 'topic_34', 'topic_35',
       'topic_36', 'topic_37', 'topic_38', 'topic_39', 'topic_40', 'topic_41',
       'topic_42', 'topic_43', 'topic_44', 'topic_45', 'topic_46', 'topic_47',
       'topic_48', 'topic_49'],
      dtype='object').
Creating first level with 21 topics. Dictionary: artm.Dictionary(name=8b6b94ce-8444-492f-850a-42f0a4c559e1, num_entries=22608).
Copying phi for the first level. Phi shape: (22608, 21). First words: MultiIndex([('@text',           'tsd'),
            ('@text',        'кратер'),
            ('@text',           'cdk'),
            ('@text', 'внутриядерный'),
            ('@text',    'прибрежный'),
            ('@text',   'соотнесение'),
            ('@text', 'ангиоматозный'),
            ('@text',       'либерия'),
            ('@text', 'хориоменингит'),
            ('@text', 'герминативный')],
           )
Creating second level with 50 topics
Copying phi for the second level. Phi shape: (22608, 50). First words: MultiIndex([('@text',           'tsd'),
            ('@text',        'кратер'),
            ('@text',           'cdk'),
            ('@text', 'внутриядерный'),
            ('@text',    'прибрежный'),
            ('@text',   'соотнесение'),
            ('@text', 'ангиоматозный'),
            ('@text',       'либерия'),
            ('@text', 'хориоменингит'),
            ('@text', 'герминативный')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic
!!! Bank Phi: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 0.0000000e+00]
 [7.2033746e-16 0.0000000e+00 1.1381690e-13 ... 1.9853734e-09
  0.0000000e+00 0.0000000e+00]
 [3.3718145e-14 1.9467438e-16 2.0230794e-16 ... 4.0798841e-15
  8.0920739e-12 7.9087691e-13]
 ...
 [4.8981730e-10 1.3865412e-14 5.1600014e-16 ... 1.4277549e-15
  1.2383442e-11 2.4433175e-10]
 [3.8512579e-11 2.6657148e-14 0.0000000e+00 ... 4.8422846e-16
  8.7249652e-12 1.3926617e-11]
 [1.1985057e-10 5.7713026e-15 5.3906717e-16 ... 3.1207854e-16
  1.1367645e-11 1.2832505e-10]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.3117168e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.3117168e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 5.7814381e-05]
 ...
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.3117168e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.5245606e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.3117168e-05]].
Bank scores: {'perplexity_score': 5099.79833984375, 'coherence_20': 0.8789142342668147, 'diversity_euclidean': 0.08646143839018196, 'diversity_jensenshannon': 0.6791605191910739, 'diversity_hellinger': 0.7944052844625914, 'diversity_cosine': 0.8400400480832232, 'perplexity': 5099.79833984375, 'ppl_fair': 5099.79833984375, 'ppl_cheatty': 2982.079833984375}
 90%|███████████████████████████████████████▌    | 18/20 [1:17:58<08:48, 264.37s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████                        | 1/2 [02:44<02:44, 164.05s/it]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 2/2 [02:44<00:00, 82.16s/it]
Using absoulte threshold: 1.5041606723306686.
Eliminating bcg topic before Hier. Cur |T| is 51, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'topic_20', 'topic_21', 'topic_22', 'topic_23',
       'topic_24', 'topic_25', 'topic_26', 'topic_27', 'topic_28', 'topic_29',
       'topic_30', 'topic_31', 'topic_32', 'topic_33', 'topic_34', 'topic_35',
       'topic_36', 'topic_37', 'topic_38', 'topic_39', 'topic_40', 'topic_41',
       'topic_42', 'topic_43', 'topic_44', 'topic_45', 'topic_46', 'topic_47',
       'topic_48', 'topic_49', 'background_50'],
      dtype='object').
Now |T| is 50, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'topic_20', 'topic_21', 'topic_22', 'topic_23',
       'topic_24', 'topic_25', 'topic_26', 'topic_27', 'topic_28', 'topic_29',
       'topic_30', 'topic_31', 'topic_32', 'topic_33', 'topic_34', 'topic_35',
       'topic_36', 'topic_37', 'topic_38', 'topic_39', 'topic_40', 'topic_41',
       'topic_42', 'topic_43', 'topic_44', 'topic_45', 'topic_46', 'topic_47',
       'topic_48', 'topic_49'],
      dtype='object').
Creating first level with 21 topics. Dictionary: artm.Dictionary(name=8b6b94ce-8444-492f-850a-42f0a4c559e1, num_entries=22608).
Copying phi for the first level. Phi shape: (22608, 21). First words: MultiIndex([('@text',           'tsd'),
            ('@text',        'кратер'),
            ('@text',           'cdk'),
            ('@text', 'внутриядерный'),
            ('@text',    'прибрежный'),
            ('@text',   'соотнесение'),
            ('@text', 'ангиоматозный'),
            ('@text',       'либерия'),
            ('@text', 'хориоменингит'),
            ('@text', 'герминативный')],
           )
Creating second level with 50 topics
Copying phi for the second level. Phi shape: (22608, 50). First words: MultiIndex([('@text',           'tsd'),
            ('@text',        'кратер'),
            ('@text',           'cdk'),
            ('@text', 'внутриядерный'),
            ('@text',    'прибрежный'),
            ('@text',   'соотнесение'),
            ('@text', 'ангиоматозный'),
            ('@text',       'либерия'),
            ('@text', 'хориоменингит'),
            ('@text', 'герминативный')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic
!!! Bank Phi: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]].
!!! Bank model Phi: [[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [1.60436119e-15 0.00000000e+00 1.84751899e-13 ... 0.00000000e+00
  0.00000000e+00 1.09531491e-13]
 [8.99794037e-15 0.00000000e+00 1.05946285e-16 ... 1.05366913e-11
  7.50407494e-13 9.43275388e-11]
 ...
 [5.05943232e-10 1.07598968e-14 4.71504913e-16 ... 1.26587525e-11
  2.07707990e-10 2.56518931e-14]
 [4.58665432e-11 2.41251602e-14 0.00000000e+00 ... 9.86629875e-12
  1.40474533e-11 5.95834485e-14]
 [1.29179778e-10 4.67864916e-15 5.21910944e-16 ... 1.20489391e-11
  1.14694074e-10 2.73453559e-14]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.3365047e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.3365047e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 5.8906888e-05]
 ...
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.3365047e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.5533706e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.3365047e-05]].
Bank scores: {'perplexity_score': 4968.677734375, 'coherence_20': 0.8816700278728158, 'diversity_euclidean': 0.08627713019745334, 'diversity_jensenshannon': 0.6782049712644823, 'diversity_hellinger': 0.7934022660425308, 'diversity_cosine': 0.839108778186396, 'perplexity': 4968.677734375, 'ppl_fair': 4968.677734375, 'ppl_cheatty': 2955.516845703125}
 95%|█████████████████████████████████████████▊  | 19/20 [1:22:23<04:24, 264.35s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/2 [00:00<?, ?it/s]
 50%|████████████████████████                        | 1/2 [02:43<02:43, 163.44s/it]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 2/2 [02:43<00:00, 81.86s/it]
Using absoulte threshold: 1.5041606723306686.
Eliminating bcg topic before Hier. Cur |T| is 51, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'topic_20', 'topic_21', 'topic_22', 'topic_23',
       'topic_24', 'topic_25', 'topic_26', 'topic_27', 'topic_28', 'topic_29',
       'topic_30', 'topic_31', 'topic_32', 'topic_33', 'topic_34', 'topic_35',
       'topic_36', 'topic_37', 'topic_38', 'topic_39', 'topic_40', 'topic_41',
       'topic_42', 'topic_43', 'topic_44', 'topic_45', 'topic_46', 'topic_47',
       'topic_48', 'topic_49', 'background_50'],
      dtype='object').
Now |T| is 50, topics are: Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11',
       'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17',
       'topic_18', 'topic_19', 'topic_20', 'topic_21', 'topic_22', 'topic_23',
       'topic_24', 'topic_25', 'topic_26', 'topic_27', 'topic_28', 'topic_29',
       'topic_30', 'topic_31', 'topic_32', 'topic_33', 'topic_34', 'topic_35',
       'topic_36', 'topic_37', 'topic_38', 'topic_39', 'topic_40', 'topic_41',
       'topic_42', 'topic_43', 'topic_44', 'topic_45', 'topic_46', 'topic_47',
       'topic_48', 'topic_49'],
      dtype='object').
Creating first level with 22 topics. Dictionary: artm.Dictionary(name=8b6b94ce-8444-492f-850a-42f0a4c559e1, num_entries=22608).
Copying phi for the first level. Phi shape: (22608, 22). First words: MultiIndex([('@text',           'tsd'),
            ('@text',        'кратер'),
            ('@text',           'cdk'),
            ('@text', 'внутриядерный'),
            ('@text',    'прибрежный'),
            ('@text',   'соотнесение'),
            ('@text', 'ангиоматозный'),
            ('@text',       'либерия'),
            ('@text', 'хориоменингит'),
            ('@text', 'герминативный')],
           )
Creating second level with 50 topics
Copying phi for the second level. Phi shape: (22608, 50). First words: MultiIndex([('@text',           'tsd'),
            ('@text',        'кратер'),
            ('@text',           'cdk'),
            ('@text', 'внутриядерный'),
            ('@text',    'прибрежный'),
            ('@text',   'соотнесение'),
            ('@text', 'ангиоматозный'),
            ('@text',       'либерия'),
            ('@text', 'хориоменингит'),
            ('@text', 'герминативный')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic
!!! Bank Phi: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]].
!!! Bank model Phi: [[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 0.0000000e+00]
 [1.6043608e-15 0.0000000e+00 1.8475197e-13 ... 0.0000000e+00
  0.0000000e+00 1.0953149e-13]
 [8.9979454e-15 0.0000000e+00 1.0594620e-16 ... 1.0536701e-11
  7.5040793e-13 9.4327511e-11]
 ...
 [5.0594384e-10 1.0759896e-14 4.7150475e-16 ... 1.2658741e-11
  2.0770788e-10 2.5651898e-14]
 [4.5866616e-11 2.4125164e-14 0.0000000e+00 ... 9.8662961e-12
  1.4047454e-11 5.9583469e-14]
 [1.2918001e-10 4.6786492e-15 5.2191105e-16 ... 1.2048935e-11
  1.1469406e-10 2.7345352e-14]].

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

!!! Bank Phi: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]].
!!! Bank model Phi: [[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.33650465e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.33650465e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 5.89069023e-05]
 ...
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.33650465e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.55337057e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.33650465e-05]].
Bank scores: {'perplexity_score': 4968.677734375, 'coherence_20': 0.8816700278728158, 'diversity_euclidean': 0.08627713019802963, 'diversity_jensenshannon': 0.6782049712711382, 'diversity_hellinger': 0.7934022660457823, 'diversity_cosine': 0.8391087782048462, 'perplexity': 4968.677734375, 'ppl_fair': 4968.677734375, 'ppl_cheatty': 2955.516845703125}
100%|████████████████████████████████████████████| 20/20 [1:26:41<00:00, 260.06s/it]
CPU times: user 1h 45min 51s, sys: 3min 17s, total: 1h 49min 9s
Wall time: 1h 26min 41s

In [61]:
len(optimizer._result['model_scores'])

20

In [62]:
len(optimizer._result['num_model_topics'])

20

In [63]:
len(optimizer._result['model_topic_scores'])

20

In [64]:
optimizer._last_bank_phi.shape

(22608, 22)

In [65]:
optimizer._last_bank_phi['topic_5'].sort_values(ascending=False)[:10]

@text  кожа         0.054675
       личинка      0.018099
       поражение    0.010705
       кожный       0.008399
       зуд          0.007570
       больной      0.007170
       участок      0.006185
       очаг         0.005644
       чесотка      0.005298
       мм           0.005109
Name: topic_5, dtype: float64

In [77]:
optimizer._last_model_phi.shape

(22608, 21)

In [100]:
optimizer._last_model_phi['topic_20'].sort_values(ascending=False)[:10]

KeyError: 'topic_20'

In [66]:
optimizer._main_modality

'@text'

What topics we have in bank

In [67]:
optimizer._topic_bank.view_topics().head()

                     topic_0  topic_1  topic_2  topic_3  topic_4  topic_5  \
@text tsd                0.0      0.0      0.0      0.0      0.0      0.0
      кратер             0.0      0.0      0.0      0.0      0.0      0.0
      cdk                0.0      0.0      0.0      0.0      0.0      0.0
      внутриядерный      0.0      0.0      0.0      0.0      0.0      0.0
      прибрежный         0.0      0.0      0.0      0.0      0.0      0.0

                     topic_6  topic_7  topic_8  topic_9  ...  topic_12  \
@text tsd                0.0      0.0      0.0      0.0  ...  0.000000
      кратер             0.0      0.0      0.0      0.0  ...  0.000000
      cdk                0.0      0.0      0.0      0.0  ...  0.000000
      внутриядерный      0.0      0.0      0.0      0.0  ...  0.000000
      прибрежный         0.0      0.0      0.0      0.0  ...  0.000029

                     topic_13  topic_14  topic_15  topic_16  topic_17  \
@text tsd                 0.0       0.0       0.0       0.0       0.0
      кратер              0.0       0.0       0.0       0.0       0.0
      cdk                 0.0       0.0       0.0       0.0       0.0
      внутриядерный       0.0       0.0       0.0       0.0       0.0
      прибрежный          0.0       0.0       0.0       0.0       0.0

                     topic_18  topic_19  topic_20  topic_21
@text tsd                 0.0       0.0       0.0       0.0
      кратер              0.0       0.0       0.0       0.0
      cdk                 0.0       0.0       0.0       0.0
      внутриядерный       0.0       0.0       0.0       0.0
      прибрежный          0.0       0.0       0.0       0.0

[5 rows x 22 columns]

In [68]:
bank_topics = optimizer._topic_bank.view_topics()

In [69]:
bank_topics.shape

(22608, 22)

In [70]:
bank_topics.head()

                     topic_0  topic_1  topic_2  topic_3  topic_4  topic_5  \
@text tsd                0.0      0.0      0.0      0.0      0.0      0.0
      кратер             0.0      0.0      0.0      0.0      0.0      0.0
      cdk                0.0      0.0      0.0      0.0      0.0      0.0
      внутриядерный      0.0      0.0      0.0      0.0      0.0      0.0
      прибрежный         0.0      0.0      0.0      0.0      0.0      0.0

                     topic_6  topic_7  topic_8  topic_9  ...  topic_12  \
@text tsd                0.0      0.0      0.0      0.0  ...  0.000000
      кратер             0.0      0.0      0.0      0.0  ...  0.000000
      cdk                0.0      0.0      0.0      0.0  ...  0.000000
      внутриядерный      0.0      0.0      0.0      0.0  ...  0.000000
      прибрежный         0.0      0.0      0.0      0.0  ...  0.000029

                     topic_13  topic_14  topic_15  topic_16  topic_17  \
@text tsd                 0.0       0.0       0.0       0.0       0.0
      кратер              0.0       0.0       0.0       0.0       0.0
      cdk                 0.0       0.0       0.0       0.0       0.0
      внутриядерный       0.0       0.0       0.0       0.0       0.0
      прибрежный          0.0       0.0       0.0       0.0       0.0

                     topic_18  topic_19  topic_20  topic_21
@text tsd                 0.0       0.0       0.0       0.0
      кратер              0.0       0.0       0.0       0.0
      cdk                 0.0       0.0       0.0       0.0
      внутриядерный       0.0       0.0       0.0       0.0
      прибрежный          0.0       0.0       0.0       0.0

[5 rows x 22 columns]

In [91]:
bank_topics['topic_9'].sort_values(ascending=False)[:20]

@text  шизофрения       0.035374
       расстроиство     0.033300
       психоз           0.016961
       психический      0.012308
       мкб              0.012198
       симптом          0.011537
       галлюцинация     0.009367
       тип              0.008771
       диагноз          0.008565
       больной          0.007930
       бредовый         0.007373
       синдром          0.007281
       бред             0.007187
       код              0.007094
       состояние        0.006965
       психотический    0.006181
       форма            0.005976
       критерий         0.005362
       классификация    0.004800
       наблюдаться      0.004657
Name: topic_9, dtype: float64

In [92]:
bank_topics['topic_12'].sort_values(ascending=False)[:20]  # TODO: темы похожи (одинаковые топ слова, но в разном порядке (другие вероятности)

@text  опухоль              0.050720
       ткань                0.012181
       клетка               0.011771
       новообразование      0.010778
       узел                 0.009346
       опухолей             0.008378
       метастаз             0.008245
       удаление             0.008207
       злокачественный      0.008163
       лучевой              0.007778
       размер               0.006872
       больной              0.006736
       хирургический        0.006445
       легкое               0.006054
       иметь                0.005986
       метод                0.005918
       терапия              0.005883
       образование          0.005645
       встречаться          0.005571
       доброкачественный    0.005536
Name: topic_12, dtype: float64

In [102]:
bank_topics['topic_17'].sort_values(ascending=False)[:20]

@text  беременность     0.019964
       матка            0.019931
       женщина          0.015865
       плод             0.014249
       половый          0.011765
       ребенок          0.009125
       орган            0.008738
       яичко            0.007882
       роды             0.007390
       новорожденный    0.007344
       мужчина          0.007085
       время            0.006887
       мужской          0.006877
       шеик             0.006860
       уровень          0.006226
       врожденный       0.005947
       изз              0.005623
       порок            0.005617
       андроген         0.005448
       матерь           0.005439
Name: topic_17, dtype: float64

In [103]:
bank_topics['topic_20'].sort_values(ascending=False)[:20]

@text  ребенок          0.034443
       беременность     0.019361
       плод             0.017368
       новорожденный    0.013260
       врожденный       0.011663
       рождение         0.010069
       порок            0.009937
       время            0.009685
       жизнь            0.009242
       неделя           0.009239
       аномалия         0.008434
       матерь           0.008326
       роды             0.007749
       ранний           0.007562
       фактор           0.007397
       изз              0.007185
       иметь            0.006883
       женщина          0.006883
       уровень          0.006600
       возраст          0.006398
Name: topic_20, dtype: float64

In [109]:
bank_topics['topic_21'].sort_values(ascending=False)[:20]

@text  кишка         0.031886
       желудок       0.023708
       кишечник      0.017915
       болезнь       0.014007
       пищевод       0.011376
       диарея        0.009720
       пища          0.009440
       слизистой     0.008728
       оболочка      0.007721
       живот         0.007675
       прием         0.007374
       толстой       0.007104
       кишечный      0.006796
       больной       0.006700
       гастрит       0.006146
       колит         0.005943
       тонкой        0.005751
       отдел         0.005686
       нарушение     0.005593
       альцгеимер    0.005177
Name: topic_21, dtype: float64

And topic scores

In [107]:
optimizer._topic_bank.view_topic_scores()

,topic_0,topic_1,topic_2,topic_3,topic_4,topic_5,topic_6,topic_7,topic_8,topic_9,...,topic_12,topic_13,topic_14,topic_15,topic_16,topic_17,topic_18,topic_19,topic_20,topic_21
kernel_size,1846.000000,1856.000000,1789.000000,1564.000000,2147.000000,2219.000000,2202.000000,2166.000000,2151.000000,2175.000000,...,1836.000000,2086.000000,1784.000000,1669.000000,1781.000000,1768.000000,2254.000000,2504.000000,1697.000000,1856.000000
toplen_ptw,1.557893,1.523160,1.549125,2.121773,1.512437,1.600360,1.659930,1.624002,1.513325,1.655525,...,1.740880,1.711241,1.513070,1.521442,1.586590,1.563646,1.627477,1.690362,1.629165,1.515355
coherence_20,1.073899,0.671336,0.640791,0.758033,0.945883,0.758087,0.789218,1.270597,0.770387,0.870748,...,0.718668,1.279343,0.886291,1.461477,0.463231,0.757047,0.923096,0.818991,0.651868,0.939542
distance_to_nearest,0.853231,0.853678,0.840626,0.886784,0.828691,0.808672,0.625120,0.836021,0.819530,0.829518,...,0.520315,0.571698,0.828560,0.609565,0.859343,0.837936,0.523537,0.852614,0.599001,0.706895

All models are also saved (topics as $\Phi$ matrices and topic score values)

In [110]:
optimizer._topic_bank._path

'/data_mil/shared/CompressaAI/iterative/data/noow/MKB_10__internals/result2_50/bank__0'

In [111]:
! ls $optimizer._topic_bank._path

model_0__phi.bin	    model_19__topic_scores.bin
model_0__topic_scores.bin   model_1__phi.bin
model_10__phi.bin	    model_1__topic_scores.bin
model_10__topic_scores.bin  model_2__phi.bin
model_11__phi.bin	    model_2__topic_scores.bin
model_11__topic_scores.bin  model_3__phi.bin
model_12__phi.bin	    model_3__topic_scores.bin
model_12__topic_scores.bin  model_4__phi.bin
model_13__phi.bin	    model_4__topic_scores.bin
model_13__topic_scores.bin  model_5__phi.bin
model_14__phi.bin	    model_5__topic_scores.bin
model_14__topic_scores.bin  model_6__phi.bin
model_15__phi.bin	    model_6__topic_scores.bin
model_15__topic_scores.bin  model_7__phi.bin
model_16__phi.bin	    model_7__topic_scores.bin
model_16__topic_scores.bin  model_8__phi.bin
model_17__phi.bin	    model_8__topic_scores.bin
model_17__topic_scores.bin  model_9__phi.bin
model_18__phi.bin	    model_9__topic_scores.bin
model_18__topic_scores.bin  topics.bin
model_19__phi.bin	    topic_scores.bin

In [112]:
optimizer._result.keys()

dict_keys(['optimum', 'optimum_std', 'bank_scores', 'bank_topic_scores', 'model_scores', 'model_topic_scores', 'num_bank_topics', 'num_model_topics'])

In [113]:
optimizer._result['num_bank_topics']

[10,
 13,
 13,
 15,
 15,
 15,
 16,
 16,
 16,
 17,
 17,
 17,
 17,
 18,
 18,
 20,
 21,
 21,
 22,
 22]

In [114]:
len(optimizer._result['bank_topic_scores'])

20

In [115]:
optimizer._result

{'optimum': 22,
 'optimum_std': 15.0,
 'bank_scores': [{'perplexity_score': 10208.076171875,
   'coherence_20': 0.9029355309585569,
   'diversity_euclidean': 0.08571874142455244,
   'diversity_jensenshannon': 0.6958946137026836,
   'diversity_hellinger': 0.815535452567058,
   'diversity_cosine': 0.8605912413357668,
   'perplexity': 10208.076171875,
   'ppl_fair': 10208.076171875,
   'ppl_cheatty': 3478.7275390625},
  {'perplexity_score': 7535.35888671875,
   'coherence_20': 0.8556934598538212,
   'diversity_euclidean': 0.08464793929632777,
   'diversity_jensenshannon': 0.6931204795944944,
   'diversity_hellinger': 0.8120797974516304,
   'diversity_cosine': 0.8563001399316005,
   'perplexity': 7535.35888671875,
   'ppl_fair': 7535.35888671875,
   'ppl_cheatty': 3284.724365234375},
  {'perplexity_score': 7493.7353515625,
   'coherence_20': 0.8564703841026554,
   'diversity_euclidean': 0.08586048198825141,
   'diversity_jensenshannon': 0.6913761821228219,
   'diversity_hellinger': 0.8099243323915234,
   'diversity_cosine': 0.8533404388951302,
   'perplexity': 7493.7353515625,
   'ppl_fair': 7493.7353515625,
   'ppl_cheatty': 3270.56982421875},
  {'perplexity_score': 6346.06884765625,
   'coherence_20': 0.8621776771108957,
   'diversity_euclidean': 0.08326931989662281,
   'diversity_jensenshannon': 0.6884429447844626,
   'diversity_hellinger': 0.8064359204497298,
   'diversity_cosine': 0.8490568636221048,
   'perplexity': 6346.06884765625,
   'ppl_fair': 6346.06884765625,
   'ppl_cheatty': 3154.244873046875},
  {'perplexity_score': 6346.06884765625,
   'coherence_20': 0.8621776771108957,
   'diversity_euclidean': 0.08326931989653745,
   'diversity_jensenshannon': 0.68844294478395,
   'diversity_hellinger': 0.8064359204454622,
   'diversity_cosine': 0.8490568636218739,
   'perplexity': 6346.06884765625,
   'ppl_fair': 6346.06884765625,
   'ppl_cheatty': 3154.2451171875},
  {'perplexity_score': 6578.611328125,
   'coherence_20': 0.8636883273746088,
   'diversity_euclidean': 0.08303577074911449,
   'diversity_jensenshannon': 0.6852298806159961,
   'diversity_hellinger': 0.8020148973018217,
   'diversity_cosine': 0.8410535532397364,
   'perplexity': 6578.611328125,
   'ppl_fair': 6578.611328125,
   'ppl_cheatty': 3181.440673828125},
  {'perplexity_score': 6118.68994140625,
   'coherence_20': 0.8546732017606098,
   'diversity_euclidean': 0.08212281303395592,
   'diversity_jensenshannon': 0.6835229238937232,
   'diversity_hellinger': 0.799835023034149,
   'diversity_cosine': 0.8371435015385994,
   'perplexity': 6118.68994140625,
   'ppl_fair': 6118.68994140625,
   'ppl_cheatty': 3118.886474609375},
  {'perplexity_score': 6118.68994140625,
   'coherence_20': 0.8546732017606098,
   'diversity_euclidean': 0.08212281303395591,
   'diversity_jensenshannon': 0.6835229238937127,
   'diversity_hellinger': 0.799835023034147,
   'diversity_cosine': 0.8371435015385986,
   'perplexity': 6118.68994140625,
   'ppl_fair': 6118.68994140625,
   'ppl_cheatty': 3118.886474609375},
  {'perplexity_score': 6118.68994140625,
   'coherence_20': 0.8546732017606098,
   'diversity_euclidean': 0.08212281303395602,
   'diversity_jensenshannon': 0.6835229238937334,
   'diversity_hellinger': 0.7998350230341433,
   'diversity_cosine': 0.8371435015386036,
   'perplexity': 6118.68994140625,
   'ppl_fair': 6118.68994140625,
   'ppl_cheatty': 3118.886474609375},
  {'perplexity_score': 6009.52392578125,
   'coherence_20': 0.879793557002632,
   'diversity_euclidean': 0.08452294768902084,
   'diversity_jensenshannon': 0.68371145159391,
   'diversity_hellinger': 0.8002430413874075,
   'diversity_cosine': 0.8376841407387182,
   'perplexity': 6009.52392578125,
   'ppl_fair': 6009.52392578125,
   'ppl_cheatty': 3091.91357421875},
  {'perplexity_score': 6245.0927734375,
   'coherence_20': 0.8589753599319219,
   'diversity_euclidean': 0.08626277817878962,
   'diversity_jensenshannon': 0.6799617278506102,
   'diversity_hellinger': 0.7956372749668716,
   'diversity_cosine': 0.8371857545824827,
   'perplexity': 6245.0927734375,
   'ppl_fair': 6245.0927734375,
   'ppl_cheatty': 3121.1064453125},
  {'perplexity_score': 6245.0927734375,
   'coherence_20': 0.8589753599319219,
   'diversity_euclidean': 0.08626277817878955,
   'diversity_jensenshannon': 0.6799617278506084,
   'diversity_hellinger': 0.7956372749666923,
   'diversity_cosine': 0.8371857545824846,
   'perplexity': 6245.0927734375,
   'ppl_fair': 6245.0927734375,
   'ppl_cheatty': 3121.1064453125},
  {'perplexity_score': 6245.0927734375,
   'coherence_20': 0.8589753599319219,
   'diversity_euclidean': 0.08626277817878966,
   'diversity_jensenshannon': 0.6799617278506221,
   'diversity_hellinger': 0.7956372749668743,
   'diversity_cosine': 0.8371857545824827,
   'perplexity': 6245.0927734375,
   'ppl_fair': 6245.0927734375,
   'ppl_cheatty': 3121.106689453125},
  {'perplexity_score': 6192.32958984375,
   'coherence_20': 0.879015619821203,
   'diversity_euclidean': 0.08419977046175997,
   'diversity_jensenshannon': 0.6718767097760334,
   'diversity_hellinger': 0.7857481543977852,
   'diversity_cosine': 0.8243398060364351,
   'perplexity': 6192.32958984375,
   'ppl_fair': 6192.32958984375,
   'ppl_cheatty': 3092.301513671875},
  {'perplexity_score': 6192.32958984375,
   'coherence_20': 0.879015619821203,
   'diversity_euclidean': 0.08419977046176003,
   'diversity_jensenshannon': 0.6718767097760489,
   'diversity_hellinger': 0.7857481543977705,
   'diversity_cosine': 0.8243398060364361,
   'perplexity': 6192.32958984375,
   'ppl_fair': 6192.32958984375,
   'ppl_cheatty': 3092.301513671875},
  {'perplexity_score': 5572.3994140625,
   'coherence_20': 0.8986363828762871,
   'diversity_euclidean': 0.08671431828284885,
   'diversity_jensenshannon': 0.6755251142945379,
   'diversity_hellinger': 0.7901147401208509,
   'diversity_cosine': 0.834609624782907,
   'perplexity': 5572.3994140625,
   'ppl_fair': 5572.3994140625,
   'ppl_cheatty': 3008.926025390625},
  {'perplexity_score': 5099.79833984375,
   'coherence_20': 0.8789142342668147,
   'diversity_euclidean': 0.0864614383900119,
   'diversity_jensenshannon': 0.6791605191890726,
   'diversity_hellinger': 0.7944052844625875,
   'diversity_cosine': 0.8400400480750483,
   'perplexity': 5099.79833984375,
   'ppl_fair': 5099.79833984375,
   'ppl_cheatty': 2982.079833984375},
  {'perplexity_score': 5099.79833984375,
   'coherence_20': 0.8789142342668147,
   'diversity_euclidean': 0.08646143839018196,
   'diversity_jensenshannon': 0.6791605191910739,
   'diversity_hellinger': 0.7944052844625914,
   'diversity_cosine': 0.8400400480832232,
   'perplexity': 5099.79833984375,
   'ppl_fair': 5099.79833984375,
   'ppl_cheatty': 2982.079833984375},
  {'perplexity_score': 4968.677734375,
   'coherence_20': 0.8816700278728158,
   'diversity_euclidean': 0.08627713019745334,
   'diversity_jensenshannon': 0.6782049712644823,
   'diversity_hellinger': 0.7934022660425308,
   'diversity_cosine': 0.839108778186396,
   'perplexity': 4968.677734375,
   'ppl_fair': 4968.677734375,
   'ppl_cheatty': 2955.516845703125},
  {'perplexity_score': 4968.677734375,
   'coherence_20': 0.8816700278728158,
   'diversity_euclidean': 0.08627713019802963,
   'diversity_jensenshannon': 0.6782049712711382,
   'diversity_hellinger': 0.7934022660457823,
   'diversity_cosine': 0.8391087782048462,
   'perplexity': 4968.677734375,
   'ppl_fair': 4968.677734375,
   'ppl_cheatty': 2955.516845703125}],
 'bank_topic_scores': [[{'kernel_size': 2154,
    'toplen_ptw': 2.015649170390005,
    'coherence_20': 1.113181347952901,
    'distance_to_nearest': 0.0},
   {'kernel_size': 2651,
    'toplen_ptw': 1.5412601460355986,
    'coherence_20': 1.072577222382621,
    'distance_to_nearest': 0.8186219502701212},
   {'kernel_size': 1672,
    'toplen_ptw': 1.6631750581687808,
    'coherence_20': 0.5313094624011118,
    'distance_to_nearest': 0.8962990941440684},
   {'kernel_size': 1925,
    'toplen_ptw': 1.7646417902907658,
    'coherence_20': 1.199071381252546,
    'distance_to_nearest': 0.8778856004192823},
   {'kernel_size': 2008,
    'toplen_ptw': 1.5322908701124056,
    'coherence_20': 0.7791184792768634,
    'distance_to_nearest': 0.8610679230361519},
   {'kernel_size': 1846,
    'toplen_ptw': 1.5578934960149249,
    'coherence_20': 1.0738992225828186,
    'distance_to_nearest': 0.8532305540762364},
   {'kernel_size': 2090,
    'toplen_ptw': 1.578243992347437,
    'coherence_20': 1.1900382237632119,
    'distance_to_nearest': 0.8474864298701021},
   {'kernel_size': 1856,
    'toplen_ptw': 1.5231604269183006,
    'coherence_20': 0.6713359964863848,
    'distance_to_nearest': 0.8536780827866972},
   {'kernel_size': 1789,
    'toplen_ptw': 1.549124597367354,
    'coherence_20': 0.6407910018185659,
    'distance_to_nearest': 0.8406258777117888},
   {'kernel_size': 1564,
    'toplen_ptw': 2.1217734704660223,
    'coherence_20': 0.7580329716685439,
    'distance_to_nearest': 0.886783824903096}],
  [{'kernel_size': 2154,
    'toplen_ptw': 2.015649170390005,
    'coherence_20': 1.113181347952901,
    'distance_to_nearest': 0.0},
   {'kernel_size': 2651,
    'toplen_ptw': 1.5412601460355986,
    'coherence_20': 1.072577222382621,
    'distance_to_nearest': 0.8186219502701212},
   {'kernel_size': 1672,
    'toplen_ptw': 1.6631750581687808,
    'coherence_20': 0.5313094624011118,
    'distance_to_nearest': 0.8962990941440684},
   {'kernel_size': 2008,
    'toplen_ptw': 1.5322908701124056,
    'coherence_20': 0.7791184792768634,
    'distance_to_nearest': 0.8610679230361519},
   {'kernel_size': 1846,
    'toplen_ptw': 1.5578934960149249,
    'coherence_20': 1.0738992225828186,
    'distance_to_nearest': 0.8532305540762364},
   {'kernel_size': 2090,
    'toplen_ptw': 1.578243992347437,
    'coherence_20': 1.1900382237632119,
    'distance_to_nearest': 0.8474864298701021},
   {'kernel_size': 1856,
    'toplen_ptw': 1.5231604269183006,
    'coherence_20': 0.6713359964863848,
    'distance_to_nearest': 0.8536780827866972},
   {'kernel_size': 1789,
    'toplen_ptw': 1.549124597367354,
    'coherence_20': 0.6407910018185659,
    'distance_to_nearest': 0.8406258777117888},
   {'kernel_size': 1564,
    'toplen_ptw': 2.1217734704660223,
    'coherence_20': 0.7580329716685439,
    'distance_to_nearest': 0.886783824903096},
   {'kernel_size': 1820,
    'toplen_ptw': 1.8246381120625754,
    'coherence_20': 0.9459339795102736,
    'distance_to_nearest': 0.7450815680549316},
   {'kernel_size': 2147,
    'toplen_ptw': 1.5124372417013876,
    'coherence_20': 0.9458827707999328,
    'distance_to_nearest': 0.8286905142685941},
   {'kernel_size': 2219,
    'toplen_ptw': 1.6003595429744977,
    'coherence_20': 0.7580874685949364,
    'distance_to_nearest': 0.8086723632904976},
   {'kernel_size': 2150,
    'toplen_ptw': 1.5183028418746252,
    'coherence_20': 0.6438268308615106,
    'distance_to_nearest': 0.8428164350799021}],
  [{'kernel_size': 2154,
    'toplen_ptw': 2.015649170390005,
    'coherence_20': 1.113181347952901,
    'distance_to_nearest': 0.0},
   {'kernel_size': 2651,
    'toplen_ptw': 1.5412601460355986,
    'coherence_20': 1.072577222382621,
    'distance_to_nearest': 0.8186219502701212},
   {'kernel_size': 1672,
    'toplen_ptw': 1.6631750581687808,
    'coherence_20': 0.5313094624011118,
    'distance_to_nearest': 0.8962990941440684},
   {'kernel_size': 1846,
    'toplen_ptw': 1.5578934960149249,
    'coherence_20': 1.0738992225828186,
    'distance_to_nearest': 0.8532305540762364},
   {'kernel_size': 2090,
    'toplen_ptw': 1.578243992347437,
    'coherence_20': 1.1900382237632119,
    'distance_to_nearest': 0.8474864298701021},
   {'kernel_size': 1856,
    'toplen_ptw': 1.5231604269183006,
    'coherence_20': 0.6713359964863848,
    'distance_to_nearest': 0.8536780827866972},
   {'kernel_size': 1789,
    'toplen_ptw': 1.549124597367354,
    'coherence_20': 0.6407910018185659,
    'distance_to_nearest': 0.8406258777117888},
   {'kernel_size': 1564,
    'toplen_ptw': 2.1217734704660223,
    'coherence_20': 0.7580329716685439,
    'distance_to_nearest': 0.886783824903096},
   {'kernel_size': 1820,
    'toplen_ptw': 1.8246381120625754,
    'coherence_20': 0.9459339795102736,
    'distance_to_nearest': 0.7450815680549316},
   {'kernel_size': 2147,
    'toplen_ptw': 1.5124372417013876,
    'coherence_20': 0.9458827707999328,
    'distance_to_nearest': 0.8286905142685941},
   {'kernel_size': 2219,
    'toplen_ptw': 1.6003595429744977,
    'coherence_20': 0.7580874685949364,
    'distance_to_nearest': 0.8086723632904976},
   {'kernel_size': 2150,
    'toplen_ptw': 1.5183028418746252,
    'coherence_20': 0.6438268308615106,
    'distance_to_nearest': 0.8428164350799021},
   {'kernel_size': 2202,
    'toplen_ptw': 1.6599296894048055,
    'coherence_20': 0.7892184945117068,
    'distance_to_nearest': 0.6251197500789684}],
  [{'kernel_size': 2651,
    'toplen_ptw': 1.5412601460355986,
    'coherence_20': 1.072577222382621,
    'distance_to_nearest': 0.8186219502701212},
   {'kernel_size': 1672,
    'toplen_ptw': 1.6631750581687808,
    'coherence_20': 0.5313094624011118,
    'distance_to_nearest': 0.8962990941440684},
   {'kernel_size': 1846,
    'toplen_ptw': 1.5578934960149249,
    'coherence_20': 1.0738992225828186,
    'distance_to_nearest': 0.8532305540762364},
   {'kernel_size': 2090,
    'toplen_ptw': 1.578243992347437,
    'coherence_20': 1.1900382237632119,
    'distance_to_nearest': 0.8474864298701021},
   {'kernel_size': 1856,
    'toplen_ptw': 1.5231604269183006,
    'coherence_20': 0.6713359964863848,
    'distance_to_nearest': 0.8536780827866972},
   {'kernel_size': 1789,
    'toplen_ptw': 1.549124597367354,
    'coherence_20': 0.6407910018185659,
    'distance_to_nearest': 0.8406258777117888},
   {'kernel_size': 1564,
    'toplen_ptw': 2.1217734704660223,
    'coherence_20': 0.7580329716685439,
    'distance_to_nearest': 0.886783824903096},
   {'kernel_size': 1820,
    'toplen_ptw': 1.8246381120625754,
    'coherence_20': 0.9459339795102736,
    'distance_to_nearest': 0.7450815680549316},
   {'kernel_size': 2147,
    'toplen_ptw': 1.5124372417013876,
    'coherence_20': 0.9458827707999328,
    'distance_to_nearest': 0.8286905142685941},
   {'kernel_size': 2219,
    'toplen_ptw': 1.6003595429744977,
    'coherence_20': 0.7580874685949364,
    'distance_to_nearest': 0.8086723632904976},
   {'kernel_size': 2150,
    'toplen_ptw': 1.5183028418746252,
    'coherence_20': 0.6438268308615106,
    'distance_to_nearest': 0.8428164350799021},
   {'kernel_size': 2202,
    'toplen_ptw': 1.6599296894048055,
    'coherence_20': 0.7892184945117068,
    'distance_to_nearest': 0.6251197500789684},
   {'kernel_size': 2166,
    'toplen_ptw': 1.6240020068576535,
    'coherence_20': 1.2705966165361997,
    'distance_to_nearest': 0.8360207518374949},
   {'kernel_size': 2151,
    'toplen_ptw': 1.5133249127914188,
    'coherence_20': 0.7703870227165519,
    'distance_to_nearest': 0.8195301545614877},
   {'kernel_size': 2175,
    'toplen_ptw': 1.655524671017916,
    'coherence_20': 0.8707478720290649,
    'distance_to_nearest': 0.8295177775801247}],
  [{'kernel_size': 2651,
    'toplen_ptw': 1.5412601460355986,
    'coherence_20': 1.072577222382621,
    'distance_to_nearest': 0.8186219502701212},
   {'kernel_size': 1672,
    'toplen_ptw': 1.6631750581687808,
    'coherence_20': 0.5313094624011118,
    'distance_to_nearest': 0.8962990941440684},
   {'kernel_size': 1846,
    'toplen_ptw': 1.5578934960149249,
    'coherence_20': 1.0738992225828186,
    'distance_to_nearest': 0.8532305540762364},
   {'kernel_size': 2090,
    'toplen_ptw': 1.578243992347437,
    'coherence_20': 1.1900382237632119,
    'distance_to_nearest': 0.8474864298701021},
   {'kernel_size': 1856,
    'toplen_ptw': 1.5231604269183006,
    'coherence_20': 0.6713359964863848,
    'distance_to_nearest': 0.8536780827866972},
   {'kernel_size': 1789,
    'toplen_ptw': 1.549124597367354,
    'coherence_20': 0.6407910018185659,
    'distance_to_nearest': 0.8406258777117888},
   {'kernel_size': 1564,
    'toplen_ptw': 2.1217734704660223,
    'coherence_20': 0.7580329716685439,
    'distance_to_nearest': 0.886783824903096},
   {'kernel_size': 1820,
    'toplen_ptw': 1.8246381120625754,
    'coherence_20': 0.9459339795102736,
    'distance_to_nearest': 0.7450815680549316},
   {'kernel_size': 2147,
    'toplen_ptw': 1.5124372417013876,
    'coherence_20': 0.9458827707999328,
    'distance_to_nearest': 0.8286905142685941},
   {'kernel_size': 2219,
    'toplen_ptw': 1.6003595429744977,
    'coherence_20': 0.7580874685949364,
    'distance_to_nearest': 0.8086723632904976},
   {'kernel_size': 2150,
    'toplen_ptw': 1.5183028418746252,
    'coherence_20': 0.6438268308615106,
    'distance_to_nearest': 0.8428164350799021},
   {'kernel_size': 2202,
    'toplen_ptw': 1.6599296894048055,
    'coherence_20': 0.7892184945117068,
    'distance_to_nearest': 0.6251197500789684},
   {'kernel_size': 2166,
    'toplen_ptw': 1.6240020068576535,
    'coherence_20': 1.2705966165361997,
    'distance_to_nearest': 0.8360207518374949},
   {'kernel_size': 2151,
    'toplen_ptw': 1.5133249127914188,
    'coherence_20': 0.7703870227165519,
    'distance_to_nearest': 0.8195301545614877},
   {'kernel_size': 2175,
    'toplen_ptw': 1.655524671017916,
    'coherence_20': 0.8707478720290649,
    'distance_to_nearest': 0.8295177775801247}],
  [{'kernel_size': 2651,
    'toplen_ptw': 1.5412601460355986,
    'coherence_20': 1.072577222382621,
    'distance_to_nearest': 0.8186219502701212},
   {'kernel_size': 1672,
    'toplen_ptw': 1.6631750581687808,
    'coherence_20': 0.5313094624011118,
    'distance_to_nearest': 0.8962990941440684},
   {'kernel_size': 1846,
    'toplen_ptw': 1.5578934960149249,
    'coherence_20': 1.0738992225828186,
    'distance_to_nearest': 0.8532305540762364},
   {'kernel_size': 2090,
    'toplen_ptw': 1.578243992347437,
    'coherence_20': 1.1900382237632119,
    'distance_to_nearest': 0.8474864298701021},
   {'kernel_size': 1856,
    'toplen_ptw': 1.5231604269183006,
    'coherence_20': 0.6713359964863848,
    'distance_to_nearest': 0.8536780827866972},
   {'kernel_size': 1789,
    'toplen_ptw': 1.549124597367354,
    'coherence_20': 0.6407910018185659,
    'distance_to_nearest': 0.8406258777117888},
   {'kernel_size': 1564,
    'toplen_ptw': 2.1217734704660223,
    'coherence_20': 0.7580329716685439,
    'distance_to_nearest': 0.886783824903096},
   {'kernel_size': 1820,
    'toplen_ptw': 1.8246381120625754,
    'coherence_20': 0.9459339795102736,
    'distance_to_nearest': 0.7450815680549316},
   {'kernel_size': 2147,
    'toplen_ptw': 1.5124372417013876,
    'coherence_20': 0.9458827707999328,
    'distance_to_nearest': 0.8286905142685941},
   {'kernel_size': 2219,
    'toplen_ptw': 1.6003595429744977,
    'coherence_20': 0.7580874685949364,
    'distance_to_nearest': 0.8086723632904976},
   {'kernel_size': 2202,
    'toplen_ptw': 1.6599296894048055,
    'coherence_20': 0.7892184945117068,
    'distance_to_nearest': 0.6251197500789684},
   {'kernel_size': 2166,
    'toplen_ptw': 1.6240020068576535,
    'coherence_20': 1.2705966165361997,
    'distance_to_nearest': 0.8360207518374949},
   {'kernel_size': 2151,
    'toplen_ptw': 1.5133249127914188,
    'coherence_20': 0.7703870227165519,
    'distance_to_nearest': 0.8195301545614877},
   {'kernel_size': 2175,
    'toplen_ptw': 1.655524671017916,
    'coherence_20': 0.8707478720290649,
    'distance_to_nearest': 0.8295177775801247},
   {'kernel_size': 2119,
    'toplen_ptw': 1.7341354303848573,
    'coherence_20': 0.6664865848172079,
    'distance_to_nearest': 0.6064053665075142}],
  [{'kernel_size': 2651,
    'toplen_ptw': 1.5412601460355986,
    'coherence_20': 1.072577222382621,
    'distance_to_nearest': 0.8186219502701212},
   {'kernel_size': 1672,
    'toplen_ptw': 1.6631750581687808,
    'coherence_20': 0.5313094624011118,
    'distance_to_nearest': 0.8962990941440684},
   {'kernel_size': 1846,
    'toplen_ptw': 1.5578934960149249,

In [103]:
optimizer._result['bank_topic_scores']

[[{'kernel_size': 2491,
   'coherence_20': 0.9428906252054199,
   'distance_to_nearest': 0.0},
  {'kernel_size': 2350,
   'coherence_20': 0.8066311856951885,
   'distance_to_nearest': 0.8726516982760463},
  {'kernel_size': 2420,
   'coherence_20': 0.9410456312491235,
   'distance_to_nearest': 0.8250411933273305},
  {'kernel_size': 2226,
   'coherence_20': 0.7419371396049255,
   'distance_to_nearest': 0.7790961962327442},
  {'kernel_size': 2477,
   'coherence_20': 0.7897800173209952,
   'distance_to_nearest': 0.8302451060089555},
  {'kernel_size': 2029,
   'coherence_20': 0.9042007921953766,
   'distance_to_nearest': 0.8149875113566727},
  {'kernel_size': 2081,
   'coherence_20': 1.1650692321395308,
   'distance_to_nearest': 0.8180900833750091}],
 [{'kernel_size': 2491,
   'coherence_20': 0.9428906252054199,
   'distance_to_nearest': 0.0},
  {'kernel_size': 2350,
   'coherence_20': 0.8066311856951885,
   'distance_to_nearest': 0.8726516982760463},
  {'kernel_size': 2420,
   'coherence_20': 0.9410456312491235,
   'distance_to_nearest': 0.8250411933273305},
  {'kernel_size': 2226,
   'coherence_20': 0.7419371396049255,
   'distance_to_nearest': 0.7790961962327442},
  {'kernel_size': 2477,
   'coherence_20': 0.7897800173209952,
   'distance_to_nearest': 0.8302451060089555},
  {'kernel_size': 2029,
   'coherence_20': 0.9042007921953766,
   'distance_to_nearest': 0.8149875113566727},
  {'kernel_size': 2081,
   'coherence_20': 1.1650692321395308,
   'distance_to_nearest': 0.8180900833750091}],
 [{'kernel_size': 2491,
   'coherence_20': 0.9428906252054199,
   'distance_to_nearest': 0.0},
  {'kernel_size': 2350,
   'coherence_20': 0.8066311856951885,
   'distance_to_nearest': 0.8726516982760463},
  {'kernel_size': 2420,
   'coherence_20': 0.9410456312491235,
   'distance_to_nearest': 0.8250411933273305},
  {'kernel_size': 2226,
   'coherence_20': 0.7419371396049255,
   'distance_to_nearest': 0.7790961962327442},
  {'kernel_size': 2477,
   'coherence_20': 0.7897800173209952,
   'distance_to_nearest': 0.8302451060089555},
  {'kernel_size': 2029,
   'coherence_20': 0.9042007921953766,
   'distance_to_nearest': 0.8149875113566727},
  {'kernel_size': 2081,
   'coherence_20': 1.1650692321395308,
   'distance_to_nearest': 0.8180900833750091}],
 [{'kernel_size': 2491,
   'coherence_20': 0.9428906252054199,
   'distance_to_nearest': 0.0},
  {'kernel_size': 2350,
   'coherence_20': 0.8066311856951885,
   'distance_to_nearest': 0.8726516982760463},
  {'kernel_size': 2420,
   'coherence_20': 0.9410456312491235,
   'distance_to_nearest': 0.8250411933273305},
  {'kernel_size': 2226,
   'coherence_20': 0.7419371396049255,
   'distance_to_nearest': 0.7790961962327442},
  {'kernel_size': 2477,
   'coherence_20': 0.7897800173209952,
   'distance_to_nearest': 0.8302451060089555},
  {'kernel_size': 2029,
   'coherence_20': 0.9042007921953766,
   'distance_to_nearest': 0.8149875113566727},
  {'kernel_size': 2081,
   'coherence_20': 1.1650692321395308,
   'distance_to_nearest': 0.8180900833750091}],
 [{'kernel_size': 2491,
   'coherence_20': 0.9428906252054199,
   'distance_to_nearest': 0.0},
  {'kernel_size': 2350,
   'coherence_20': 0.8066311856951885,
   'distance_to_nearest': 0.8726516982760463},
  {'kernel_size': 2420,
   'coherence_20': 0.9410456312491235,
   'distance_to_nearest': 0.8250411933273305},
  {'kernel_size': 2226,
   'coherence_20': 0.7419371396049255,
   'distance_to_nearest': 0.7790961962327442},
  {'kernel_size': 2477,
   'coherence_20': 0.7897800173209952,
   'distance_to_nearest': 0.8302451060089555},
  {'kernel_size': 2029,
   'coherence_20': 0.9042007921953766,
   'distance_to_nearest': 0.8149875113566727},
  {'kernel_size': 2081,
   'coherence_20': 1.1650692321395308,
   'distance_to_nearest': 0.8180900833750091}],
 [{'kernel_size': 2491,
   'coherence_20': 0.9428906252054199,
   'distance_to_nearest': 0.0},
  {'kernel_size': 2350,
   'coherence_20': 0.8066311856951885,
   'distance_to_nearest': 0.8726516982760463},
  {'kernel_size': 2420,
   'coherence_20': 0.9410456312491235,
   'distance_to_nearest': 0.8250411933273305},
  {'kernel_size': 2226,
   'coherence_20': 0.7419371396049255,
   'distance_to_nearest': 0.7790961962327442},
  {'kernel_size': 2477,
   'coherence_20': 0.7897800173209952,
   'distance_to_nearest': 0.8302451060089555},
  {'kernel_size': 2029,
   'coherence_20': 0.9042007921953766,
   'distance_to_nearest': 0.8149875113566727},
  {'kernel_size': 2081,
   'coherence_20': 1.1650692321395308,
   'distance_to_nearest': 0.8180900833750091}],
 [{'kernel_size': 2491,
   'coherence_20': 0.9428906252054199,
   'distance_to_nearest': 0.0},
  {'kernel_size': 2350,
   'coherence_20': 0.8066311856951885,
   'distance_to_nearest': 0.8726516982760463},
  {'kernel_size': 2420,
   'coherence_20': 0.9410456312491235,
   'distance_to_nearest': 0.8250411933273305},
  {'kernel_size': 2226,
   'coherence_20': 0.7419371396049255,
   'distance_to_nearest': 0.7790961962327442},
  {'kernel_size': 2477,
   'coherence_20': 0.7897800173209952,
   'distance_to_nearest': 0.8302451060089555},
  {'kernel_size': 2029,
   'coherence_20': 0.9042007921953766,
   'distance_to_nearest': 0.8149875113566727},
  {'kernel_size': 2081,
   'coherence_20': 1.1650692321395308,
   'distance_to_nearest': 0.8180900833750091},
  {'kernel_size': 2400,
   'coherence_20': 0.8642075582476475,
   'distance_to_nearest': 0.776614379767758}],
 [{'kernel_size': 2491,
   'coherence_20': 0.9428906252054199,
   'distance_to_nearest': 0.0},
  {'kernel_size': 2350,
   'coherence_20': 0.8066311856951885,
   'distance_to_nearest': 0.8726516982760463},
  {'kernel_size': 2420,
   'coherence_20': 0.9410456312491235,
   'distance_to_nearest': 0.8250411933273305},
  {'kernel_size': 2477,
   'coherence_20': 0.7897800173209952,
   'distance_to_nearest': 0.8302451060089555},
  {'kernel_size': 2029,
   'coherence_20': 0.9042007921953766,
   'distance_to_nearest': 0.8149875113566727},
  {'kernel_size': 2400,
   'coherence_20': 0.8642075582476475,
   'distance_to_nearest': 0.776614379767758},
  {'kernel_size': 2244,
   'coherence_20': 1.1170993178221873,
   'distance_to_nearest': 0.5223564992652845},
  {'kernel_size': 1965,
   'coherence_20': 1.0751789683259085,
   'distance_to_nearest': 0.7799854146471481},
  {'kernel_size': 2235,
   'coherence_20': 0.8562292729874569,
   'distance_to_nearest': 0.8125217298340472}],
 [{'kernel_size': 2491,
   'coherence_20': 0.9428906252054199,
   'distance_to_nearest': 0.0},
  {'kernel_size': 2350,
   'coherence_20': 0.8066311856951885,
   'distance_to_nearest': 0.8726516982760463},
  {'kernel_size': 2420,
   'coherence_20': 0.9410456312491235,
   'distance_to_nearest': 0.8250411933273305},
  {'kernel_size': 2477,
   'coherence_20': 0.7897800173209952,
   'distance_to_nearest': 0.8302451060089555},
  {'kernel_size': 2029,
   'coherence_20': 0.9042007921953766,
   'distance_to_nearest': 0.8149875113566727},
  {'kernel_size': 2400,
   'coherence_20': 0.8642075582476475,
   'distance_to_nearest': 0.776614379767758},
  {'kernel_size': 2244,
   'coherence_20': 1.1170993178221873,
   'distance_to_nearest': 0.5223564992652845},
  {'kernel_size': 1965,
   'coherence_20': 1.0751789683259085,
   'distance_to_nearest': 0.7799854146471481},
  {'kernel_size': 2235,
   'coherence_20': 0.8562292729874569,
   'distance_to_nearest': 0.8125217298340472}],
 [{'kernel_size': 2491,
   'coherence_20': 0.9428906252054199,
   'distance_to_nearest': 0.0},
  {'kernel_size': 2350,
   'coherence_20': 0.8066311856951885,
   'distance_to_nearest': 0.8726516982760463},
  {'kernel_size': 2420,
   'coherence_20': 0.9410456312491235,
   'distance_to_nearest': 0.8250411933273305},
  {'kernel_size': 2029,
   'coherence_20': 0.9042007921953766,
   'distance_to_nearest': 0.8149875113566727},
  {'kernel_size': 2400,
   'coherence_20': 0.8642075582476475,
   'distance_to_nearest': 0.776614379767758},
  {'kernel_size': 2244,
   'coherence_20': 1.1170993178221873,
   'distance_to_nearest': 0.5223564992652845},
  {'kernel_size': 1965,
   'coherence_20': 1.0751789683259085,
   'distance_to_nearest': 0.7799854146471481},
  {'kernel_size': 2235,
   'coherence_20': 0.8562292729874569,
   'distance_to_nearest': 0.8125217298340472},
  {'kernel_size': 1891,
   'coherence_20': 1.046275574065261,
   'distance_to_nearest': 0.6803869495746948}],
 [{'kernel_size': 2350,
   'coherence_20': 0.8066311856951885,
   'distance_to_nearest': 0.8726516982760463},
  {'kernel_size': 2420,
   'coherence_20': 0.9410456312491235,
   'distance_to_nearest': 0.8250411933273305},
  {'kernel_size': 2029,
   'coherence_20': 0.9042007921953766,
   'distance_to_nearest': 0.8149875113566727},
  {'kernel_size': 2400,
   'coherence_20': 0.8642075582476475,
   'distance_to_nearest': 0.776614379767758},
  {'kernel_size': 2244,
   'coherence_20': 1.1170993178221873,
   'distance_to_nearest': 0.5223564992652845},
  {'kernel_size': 1965,
   'coherence_20': 1.0751789683259085,
   'distance_to_nearest': 0.7799854146471481},
  {'kernel_size': 2235,
   'coherence_20': 0.8562292729874569,
   'distance_to_nearest': 0.8125217298340472},
  {'kernel_size': 1891,
   'coherence_20': 1.046275574065261,
   'distance_to_nearest': 0.6803869495746948},
  {'kernel_size': 2107,
   'coherence_20': 1.009725540462603,
   'distance_to_nearest': 0.5432995913789495},
  {'kernel_size': 2543,
   'coherence_20': 0.9837129779636765,
   'distance_to_nearest': 0.7774686433863054}],
 [{'kernel_size': 2350,
   'coherence_20': 0.8066311856951885,
   'distance_to_nearest': 0.8726516982760463},
  {'kernel_size': 2420,
   'coherence_20': 0.9410456312491235,
   'distance_to_nearest': 0.8250411933273305},
  {'kernel_size': 2029,
   'coherence_20': 0.9042007921953766,
   'distance_to_nearest': 0.8149875113566727},
  {'kernel_size': 2400,
   'coherence_20': 0.8642075582476475,
   'distance_to_nearest': 0.776614379767758},
  {'kernel_size': 2244,
   'coherence_20': 1.1170993178221873,
   'distance_to_nearest': 0.5223564992652845},
  {'kernel_size': 1965,
   'coherence_20': 1.0751789683259085,
   'distance_to_nearest': 0.7799854146471481},
  {'kernel_size': 2235,
   'coherence_20': 0.8562292729874569,
   'distance_to_nearest': 0.8125217298340472},
  {'kernel_size': 1891,
   'coherence_20': 1.046275574065261,
   'distance_to_nearest': 0.6803869495746948},
  {'kernel_size': 2107,
   'coherence_20': 1.009725540462603,
   'distance_to_nearest': 0.5432995913789495},
  {'kernel_size': 2543,
   'coherence_20': 0.9837129779636765,
   'distance_to_nearest': 0.7774686433863054},
  {'kernel_size': 2675,
   'coherence_20': 0.9295829044469002,
   'distance_to_nearest': 0.8306655193248751}],
 [{'kernel_size': 2350,
   'coherence_20': 0.8066311856951885,
   'distance_to_nearest': 0.8726516982760463},
  {'kernel_size': 2420,
   'coherence_20': 0.9410456312491235,
   'distance_to_nearest': 0.8250411933273305},
  {'kernel_size': 2029,
   'coherence_20': 0.9042007921953766,
   'distance_to_nearest': 0.8149875113566727},
  {'kernel_size': 2400,
   'coherence_20': 0.8642075582476475,
   'distance_to_nearest': 0.776614379767758},
  {'kernel_size': 2244,
   'coherence_20': 1.1170993178221873,
   'distance_to_nearest': 0.5223564992652845},
  {'kernel_size': 1965,
   'coherence_20': 1.0751789683259085,
   'distance_to_nearest': 0.7799854146471481},
  {'kernel_size': 2235,
   'coherence_20': 0.8562292729874569,
   'distance_to_nearest': 0.8125217298340472},
  {'kernel_size': 1891,
   'coherence_20': 1.046275574065261,
   'distance_to_nearest': 0.6803869495746948},
  {'kernel_size': 2107,
   'coherence_20': 1.009725540462603,
   'distance_to_nearest': 0.5432995913789495},
  {'kernel_size': 2543,
   'coherence_20': 0.9837129779636765,
   'distance_to_nearest': 0.7774686433863054},
  {'kernel_size': 2675,
   'coherence_20': 0.9295829044469002,
   'distance_to_nearest': 0.8306655193248751},
  {'kernel_size': 1983,
   'coherence_20': 0.8993372088448052,
   'distance_to_nearest': 0.5310705753378592}],
 [{'kernel_size': 2350,
   'coherence_20': 0.8066311856951885,
   'distance_to_nearest': 0.8726516982760463},
  {'kernel_size': 2420,
   'coherence_20': 0.9410456312491235,
   'distance_to_nearest': 0.8250411933273305},
  {'kernel_size': 2029,
   'coherence_20': 0.9042007921953766,
   'distance_to_nearest': 0.8149875113566727},
  {'kernel_size': 2400,
   'coherence_20': 0.8642075582476475,
   'distance_to_nearest': 0.776614379767758},
  {'kernel_size': 2244,
   'coherence_20': 1.1170993178221873,
   'distance_to_nearest': 0.5223564992652845},
  {'kernel_size': 1965,
   'coherence_20': 1.0751789683259085,
   'distance_to_nearest': 0.7799854146471481},
  {'kernel_size': 2235,
   'coherence_20': 0.8562292729874569,
   'distance_to_nearest': 0.8125217298340472},
  {'kernel_size': 1891,
   'coherence_20': 1.046275574065261,
   'distance_to_nearest': 0.6803869495746948},
  {'kernel_size': 2107,
   'coherence_20': 1.009725540462603,
   'distance_to_nearest': 0.5432995913789495},
  {'kernel_size': 2543,
   'coherence_20': 0.9837129779636765,
   'distance_to_nearest': 0.7774686433863054},
  {'kernel_size': 2675,
   'coherence_20': 0.9295829044469002,
   'distance_to_nearest': 0.8306655193248751},
  {'kernel_size': 1983,
   'coherence_20': 0.8993372088448052,
   'distance_to_nearest': 0.5310705753378592}],
 [{'kernel_size': 2350,
   'coherence_20': 0.8066311856951885,
   'distance_to_nearest': 0.8726516982760463},
  {'kernel_size': 2420,
   'coherence_20': 0.9410456312491235,
   'distance_to_nearest': 0.8250411933273305},
  {'kernel_size': 2029,
   'coherence_20': 0.9042007921953766,
   'distance_to_nearest': 0.8149875113566727},
  {'kernel_size': 2400,
   'coherence_20': 0.8642075582476475,
   'distance_to_nearest': 0.776614379767758},
  {'kernel_size': 2244,
   'coherence_20': 1.1170993178221873,
   'distance_to_nearest': 0.5223564992652845},
  {'kernel_size': 1965,
   'coherence_20': 1.0751789683259085,
   'distance_to_nearest': 0.7799854146471481},
  {'kernel_size': 2235,
   'coherence_20': 0.8562292729874569,
   'distance_to_nearest': 0.8125217298340472},
  {'kernel_size': 1891,
   'coherence_20': 1.046275574065261,
   'distance_to_nearest': 0.6803869495746948},
  {'kernel_size': 2107,
   'coherence_20': 1.009725540462603,
   'distance_to_nearest': 0.5432995913789495},
  {'kernel_size': 2543,
   'coherence_20': 0.9837129779636765,
   'distance_to_nearest': 0.7774686433863054},
  {'kernel_size': 2675,
   'coherence_20': 0.9295829044469002,
   'distance_to_nearest': 0.8306655193248751},
  {'kernel_size': 1983,
   'coherence_20': 0.8993372088448052,
   'distance_to_nearest': 0.5310705753378592}],
 [{'kernel_size': 2350,
   'coherence_20': 0.8066311856951885,
   'distance_to_nearest': 0.8726516982760463},
  {'kernel_size': 2420,
   'coherence_20': 0.9410456312491235,
   'distance_to_nearest': 0.8250411933273305},
  {'kernel_size': 2029,
   'coherence_20': 0.9042007921953766,
   'distance_to_nearest': 0.8149875113566727},
  {'kernel_size': 2400,
   'coherence_20': 0.8642075582476475,
   'distance_to_nearest': 0.776614379767758},
  {'kernel_size': 2244,
   'coherence_20': 1.1170993178221873,
   'distance_to_nearest': 0.5223564992652845},
  {'kernel_size': 1965,
   'coherence_20': 1.0751789683259085,
   'distance_to_nearest': 0.7799854146471481},
  {'kernel_size': 2235,
   'coherence_20': 0.8562292729874569,
   'distance_to_nearest': 0.8125217298340472},
  {'kernel_size': 1891,
   'coherence_20': 1.046275574065261,
   'distance_to_nearest': 0.6803869495746948},
  {'kernel_size': 2107,
   'coherence_20': 1.009725540462603,
   'distance_to_nearest': 0.5432995913789495},
  {'kernel_size': 2543,
   'coherence_20': 0.9837129779636765,
   'distance_to_nearest': 0.7774686433863054},
  {'kernel_size': 2675,
   'coherence_20': 0.9295829044469002,
   'distance_to_nearest': 0.8306655193248751},
  {'kernel_size': 1983,
   'coherence_20': 0.8993372088448052,
   'distance_to_nearest': 0.5310705753378592},
  {'kernel_size': 2074,
   'coherence_20': 0.7584787624930505,
   'distance_to_nearest': 0.8086912686687325}],
 [{'kernel_size': 2350,
   'coherence_20': 0.8066311856951885,
   'distance_to_nearest': 0.8726516982760463},
  {'kernel_size': 2420,
   'coherence_20': 0.9410456312491235,
   'distance_to_nearest': 0.8250411933273305},
  {'kernel_size': 2029,
   'coherence_20': 0.9042007921953766,
   'distance_to_nearest': 0.8149875113566727},
  {'kernel_size': 2400,
   'coherence_20': 0.8642075582476475,
   'distance_to_nearest': 0.776614379767758},
  {'kernel_size': 2244,
   'coherence_20': 1.1170993178221873,
   'distance_to_nearest': 0.5223564992652845},
  {'kernel_size': 1965,
   'coherence_20': 1.0751789683259085,
   'distance_to_nearest': 0.7799854146471481},
  {'kernel_size': 2235,
   'coherence_20': 0.8562292729874569,
   'distance_to_nearest': 0.8125217298340472},
  {'kernel_size': 1891,
   'coherence_20': 1.046275574065261,
   'distance_to_nearest': 0.6803869495746948},
  {'kernel_size': 2107,
   'coherence_20': 1.009725540462603,
   'distance_to_nearest': 0.5432995913789495},
  {'kernel_size': 2543,
   'coherence_20': 0.9837129779636765,
   'distance_to_nearest': 0.7774686433863054},
  {'kernel_size': 2675,
   'coherence_20': 0.9295829044469002,
   'distance_to_nearest': 0.8306655193248751},
  {'kernel_size': 1983,
   'coherence_20': 0.8993372088448052,
   'distance_to_nearest': 0.5310705753378592},
  {'kernel_size': 2074,
   'coherence_20': 0.7584787624930505,
   'distance_to_nearest': 0.8086912686687325},
  {'kernel_size': 2388,
   'coherence_20': 0.819846610609072,
   'distance_to_nearest': 0.6986702975614494},
  {'kernel_size': 2237,
   'coherence_20': 0.7534117421163776,
   'distance_to_nearest': 0.6145524559482862}],
 [{'kernel_size': 2350,
   'coherence_20': 0.8066311856951885,
   'distance_to_nearest': 0.8726516982760463},
  {'kernel_size': 2420,
   'coherence_20': 0.9410456312491235,
   'distance_to_nearest': 0.8250411933273305},
  {'kernel_size': 2029,
   'coherence_20': 0.9042007921953766,
   'distance_to_nearest': 0.8149875113566727},
  {'kernel_size': 2400,
   'coherence_20': 0.8642075582476475,
   'distance_to_nearest': 0.776614379767758},
  {'kernel_size': 2244,
   'coherence_20': 1.1170993178221873,
   'distance_to_nearest': 0.5223564992652845},
  {'kernel_size': 1965,
   'coherence_20': 1.0751789683259085,
   'distance_to_nearest': 0.7799854146471481},
  {'kernel_size': 2235,
   'coherence_20': 0.8562292729874569,
   'distance_to_nearest': 0.8125217298340472},
  {'kernel_size': 1891,
   'coherence_20': 1.046275574065261,
   'distance_to_nearest': 0.6803869495746948},
  {'kernel_size': 2107,
   'coherence_20': 1.009725540462603,
   'distance_to_nearest': 0.5432995913789495},
  {'kernel_size': 2543,
   'coherence_20': 0.9837129779636765,
   'distance_to_nearest': 0.7774686433863054},
  {'kernel_size': 2675,
   'coherence_20': 0.9295829044469002,
   'distance_to_nearest': 0.8306655193248751},
  {'kernel_size': 1983,
   'coherence_20': 0.8993372088448052,
   'distance_to_nearest': 0.5310705753378592},
  {'kernel_size': 2074,
   'coherence_20': 0.7584787624930505,
   'distance_to_nearest': 0.8086912686687325},
  {'kernel_size': 2388,
   'coherence_20': 0.819846610609072,
   'distance_to_nearest': 0.6986702975614494},
  {'kernel_size': 2237,
   'coherence_20': 0.7534117421163776,
   'distance_to_nearest': 0.6145524559482862}],
 [{'kernel_size': 2350,
   'coherence_20': 0.8066311856951885,
   'distance_to_nearest': 0.8726516982760463},
  {'kernel_size': 2420,
   'coherence_20': 0.9410456312491235,
   'distance_to_nearest': 0.8250411933273305},
  {'kernel_size': 2029,
   'coherence_20': 0.9042007921953766,
   'distance_to_nearest': 0.8149875113566727},
  {'kernel_size': 2400,
   'coherence_20': 0.8642075582476475,
   'distance_to_nearest': 0.776614379767758},
  {'kernel_size': 2244,
   'coherence_20': 1.1170993178221873,
   'distance_to_nearest': 0.5223564992652845},
  {'kernel_size': 1965,
   'coherence_20': 1.0751789683259085,
   'distance_to_nearest': 0.7799854146471481},
  {'kernel_size': 2235,

In [70]:
optimizer._result['model_scores'][0]

{'perplexity_score': 2469.907958984375,
 'coherence_20': 0.6578056100721843,
 'diversity_euclidean': 0.06349389886462474,
 'diversity_jensenshannon': 0.6449992875008204,
 'diversity_hellinger': 0.7516691302395535,
 'diversity_cosine': 0.756782482618852,
 'perplexity': 2469.907958984375,
 'toplen_ptw': 1.9238749136164537}

In [106]:
sum(s['coherence_20'] for s in optimizer._result['bank_topic_scores'][-1]) / 15

0.9176642698349756

In [107]:
len(optimizer._result['bank_scores'])

20

In [71]:
optimizer._result['bank_scores'][-1]

{'perplexity_score': 12221.890625,
 'coherence_20': 0.6718641772061521,
 'diversity_euclidean': 0.06576941292291526,
 'diversity_jensenshannon': 0.6676788479543315,
 'diversity_hellinger': 0.7770605597872213,
 'diversity_cosine': 0.7880633030029592,
 'perplexity': 12221.890625,
 'ppl_fair': 12221.890625,
 'ppl_cheatty': 3699.527099609375}

In [73]:
len(optimizer._result['model_topic_scores'])

20

In [72]:
optimizer._result['model_topic_scores']

[[{'kernel_size': 2696,
   'toplen_ptw': 1.8130768133024986,
   'coherence_20': 0.4706941705736568},
  {'kernel_size': 2491,
   'toplen_ptw': 2.519329408771957,
   'coherence_20': 0.9428906252054199},
  {'kernel_size': 2188,
   'toplen_ptw': 2.5845020005647212,
   'coherence_20': 0.5852568483608062,
   'distance_to_nearest': 0.0},
  {'kernel_size': 2350,
   'toplen_ptw': 2.1494913590661584,
   'coherence_20': 0.8066311856951885},
  {'kernel_size': 1888,
   'toplen_ptw': 2.7193500221986606,
   'coherence_20': 0.5145335828913602,
   'distance_to_nearest': 0.8578327232484866},
  {'kernel_size': 2534,
   'toplen_ptw': 1.7107248346458916,
   'coherence_20': 0.4281253550341447},
  {'kernel_size': 2420,
   'toplen_ptw': 1.5977452848835931,
   'coherence_20': 0.9410456312491235},
  {'kernel_size': 3052,
   'toplen_ptw': 1.9238749136164537,
   'coherence_20': 0.618962659949188},
  {'kernel_size': 2405,
   'toplen_ptw': 1.541605040082251,
   'coherence_20': 0.6391091533344201},
  {'kernel_size': 2226,
   'toplen_ptw': 1.8249809773374501,
   'coherence_20': 0.7419371396049255},
  {'kernel_size': 2477,
   'toplen_ptw': 1.8165317821323836,
   'coherence_20': 0.7897800173209952},
  {'kernel_size': 2260,
   'toplen_ptw': 2.0263739367705136,
   'coherence_20': 0.5274397261902023},
  {'kernel_size': 2029,
   'toplen_ptw': 2.2005966914415467,
   'coherence_20': 0.9042007921953766},
  {'kernel_size': 2430,
   'toplen_ptw': 1.8875380292334554,
   'coherence_20': 0.6611683459869104},
  {'kernel_size': 2071,
   'toplen_ptw': 2.54114869433095,
   'coherence_20': 0.46222355277065214,
   'distance_to_nearest': 0.8336977646887536},
  {'kernel_size': 2240,
   'toplen_ptw': 2.43376610084018,
   'coherence_20': 0.654442874157458},
  {'kernel_size': 2081,
   'toplen_ptw': 2.365410540530138,
   'coherence_20': 1.1650692321395308},
  {'kernel_size': 2684,
   'toplen_ptw': 1.9283802575091593,
   'coherence_20': 0.6078315922424556},
  {'kernel_size': 2448,
   'toplen_ptw': 1.8220762151382022,
   'coherence_20': 0.6717131127403222},
  {'kernel_size': 2529,
   'toplen_ptw': 1.873266190101731,
   'coherence_20': 0.6701780840189774}],
 [{'kernel_size': 2342,
   'toplen_ptw': 2.163929966898169,
   'coherence_20': 0.8653538553903966},
  {'kernel_size': 2446,
   'toplen_ptw': 1.7978537547807614,
   'coherence_20': 0.6949533075788104},
  {'kernel_size': 1709,
   'toplen_ptw': 1.8306746809178163,
   'coherence_20': 0.9185699790493588},
  {'kernel_size': 2393,
   'toplen_ptw': 1.9094023065947832,
   'coherence_20': 0.4935055915814013},
  {'kernel_size': 2380,
   'toplen_ptw': 1.8823275177958956,
   'coherence_20': 0.6071097859750845},
  {'kernel_size': 2027,
   'toplen_ptw': 2.0342312363162134,
   'coherence_20': 0.6603567718726878},
  {'kernel_size': 2606,
   'toplen_ptw': 3.1147870935765867,
   'coherence_20': 0.9857835131820186,
   'distance_to_nearest': 0.8459942447329831},
  {'kernel_size': 2490,
   'toplen_ptw': 1.9713680551048356,
   'coherence_20': 0.4578672518788311},
  {'kernel_size': 2258,
   'toplen_ptw': 2.0032415138728994,
   'coherence_20': 0.6512808471865634},
  {'kernel_size': 2283,
   'toplen_ptw': 1.9665474467786686,
   'coherence_20': 0.7572816998111418},
  {'kernel_size': 2537,
   'toplen_ptw': 1.989151972955966,
   'coherence_20': 0.5670111889285344},
  {'kernel_size': 2132,
   'toplen_ptw': 1.9200864459914087,
   'coherence_20': 0.6812186526353304},
  {'kernel_size': 2348,
   'toplen_ptw': 2.667407370709616,
   'coherence_20': 0.8115233888259231,
   'distance_to_nearest': 0.8166264333781732},
  {'kernel_size': 2558,
   'toplen_ptw': 1.8707782262415622,
   'coherence_20': 0.7610970612530876},
  {'kernel_size': 2106,
   'toplen_ptw': 1.9242509682899658,
   'coherence_20': 0.47092330045036307},
  {'kernel_size': 2577,
   'toplen_ptw': 1.996066918106752,
   'coherence_20': 0.5397687058027307},
  {'kernel_size': 2408,
   'toplen_ptw': 2.628524242184127,
   'coherence_20': 0.5241395603934678},
  {'kernel_size': 2172,
   'toplen_ptw': 2.019245718381617,
   'coherence_20': 0.5200824457364535},
  {'kernel_size': 2230,
   'toplen_ptw': 1.8244794821324486,
   'coherence_20': 0.6775672405595051},
  {'kernel_size': 2616,
   'toplen_ptw': 1.5639096373257246,
   'coherence_20': 0.5277662509793797}],
 [{'kernel_size': 2422,
   'toplen_ptw': 2.305789956740015,
   'coherence_20': 0.7210789194645815},
  {'kernel_size': 2090,
   'toplen_ptw': 1.7347698654444084,
   'coherence_20': 0.609211094332023},
  {'kernel_size': 2164,
   'toplen_ptw': 1.874882497609396,
   'coherence_20': 0.652958721691772},
  {'kernel_size': 2077,
   'toplen_ptw': 1.926046380121275,
   'coherence_20': 0.738720701077765},
  {'kernel_size': 2496,
   'toplen_ptw': 1.795720789108593,
   'coherence_20': 0.466820973228749},
  {'kernel_size': 2362,
   'toplen_ptw': 2.182803175817249,
   'coherence_20': 0.6148220076593477},
  {'kernel_size': 2230,
   'toplen_ptw': 2.073410875884839,
   'coherence_20': 0.6953633634264452},
  {'kernel_size': 2363,
   'toplen_ptw': 1.7920021329614095,
   'coherence_20': 0.6762762546979608},
  {'kernel_size': 2320,
   'toplen_ptw': 1.7474051410932991,
   'coherence_20': 0.6199433559649631},
  {'kernel_size': 2059,
   'toplen_ptw': 2.222382959109547,
   'coherence_20': 0.7397000744840542},
  {'kernel_size': 2287,
   'toplen_ptw': 2.1015534838423227,
   'coherence_20': 0.6507439376456833},
  {'kernel_size': 2264,
   'toplen_ptw': 1.7821829782239016,
   'coherence_20': 0.5539765614301023},
  {'kernel_size': 2655,
   'toplen_ptw': 1.8353653565750472,
   'coherence_20': 1.0502785617703823},
  {'kernel_size': 2055,
   'toplen_ptw': 2.5981823963441713,
   'coherence_20': 1.1682398214090406},
  {'kernel_size': 2106,
   'toplen_ptw': 1.8944464716643035,
   'coherence_20': 0.6408063221594429},
  {'kernel_size': 2821,
   'toplen_ptw': 3.232937848242236,
   'coherence_20': 0.7785241764872368},
  {'kernel_size': 2311,
   'toplen_ptw': 2.6086101270610857,
   'coherence_20': 0.5406966068778782},
  {'kernel_size': 2278,
   'toplen_ptw': 2.159495162029417,
   'coherence_20': 0.6729041881240434},
  {'kernel_size': 2708,
   'toplen_ptw': 1.7564710427979942,
   'coherence_20': 0.6251998253073305},
  {'kernel_size': 2113,
   'toplen_ptw': 2.087771245403929,
   'coherence_20': 1.13514164228746}],
 [{'kernel_size': 2141,
   'toplen_ptw': 2.151610578478483,
   'coherence_20': 0.9744968118870956},
  {'kernel_size': 2489,
   'toplen_ptw': 2.2309074705123395,
   'coherence_20': 0.5268268743845465},
  {'kernel_size': 2370,
   'toplen_ptw': 2.1818171562378317,
   'coherence_20': 0.8617100239449127},
  {'kernel_size': 2285,
   'toplen_ptw': 1.7097505088789817,
   'coherence_20': 0.7329519905688},
  {'kernel_size': 2032,
   'toplen_ptw': 2.2103760101459544,
   'coherence_20': 0.6366198264668635},
  {'kernel_size': 2476,
   'toplen_ptw': 2.873043087376078,
   'coherence_20': 0.7133987852123119},
  {'kernel_size': 2077,
   'toplen_ptw': 1.938670767989799,
   'coherence_20': 0.7367408559652168},
  {'kernel_size': 2780,
   'toplen_ptw': 2.0084308033541145,
   'coherence_20': 0.7162884512724272},
  {'kernel_size': 2426,
   'toplen_ptw': 1.7975846779302949,
   'coherence_20': 0.8147485048270239},
  {'kernel_size': 2111,
   'toplen_ptw': 3.138581341109624,
   'coherence_20': 0.553187211220035},
  {'kernel_size': 2505,
   'toplen_ptw': 1.6177917806678537,
   'coherence_20': 0.6555693568450079},
  {'kernel_size': 2252,
   'toplen_ptw': 1.8995457963547346,
   'coherence_20': 0.7370637560003207},
  {'kernel_size': 2311,
   'toplen_ptw': 1.9794950171549428,
   'coherence_20': 0.6595963946493701},
  {'kernel_size': 2570,
   'toplen_ptw': 1.524354747403227,
   'coherence_20': 0.6293131598682874},
  {'kernel_size': 2377,
   'toplen_ptw': 2.012134255517803,
   'coherence_20': 0.4497525553194274},
  {'kernel_size': 2225,
   'toplen_ptw': 2.3831047937835863,
   'coherence_20': 0.5573360031767419},
  {'kernel_size': 2155,
   'toplen_ptw': 2.2605972724682477,
   'coherence_20': 0.621152406571736},
  {'kernel_size': 2317,
   'toplen_ptw': 2.06242828704221,
   'coherence_20': 0.6498698319139473},
  {'kernel_size': 2179,
   'toplen_ptw': 2.1713514460851657,
   'coherence_20': 0.972800217594378},
  {'kernel_size': 2354,
   'toplen_ptw': 1.8711543857669644,
   'coherence_20': 0.5990846440186091}],
 [{'kernel_size': 2306,
   'toplen_ptw': 1.8752539378986088,
   'coherence_20': 0.48903321115989484},
  {'kernel_size': 2658,
   'toplen_ptw': 2.127931308170764,
   'coherence_20': 0.9554065662729972},
  {'kernel_size': 2456,
   'toplen_ptw': 1.8485854701886721,
   'coherence_20': 0.6569258084668808},
  {'kernel_size': 2470,
   'toplen_ptw': 2.056863259774557,
   'coherence_20': 0.5580094620578002},
  {'kernel_size': 2203,
   'toplen_ptw': 1.8190535211549745,
   'coherence_20': 0.5081260019462712},
  {'kernel_size': 2320,
   'toplen_ptw': 1.6799885227887805,
   'coherence_20': 0.6400392824941111},
  {'kernel_size': 2274,
   'toplen_ptw': 1.812727119141242,
   'coherence_20': 0.4995392514333278},
  {'kernel_size': 2020,
   'toplen_ptw': 1.916408622440819,
   'coherence_20': 0.6156773009971551},
  {'kernel_size': 2145,
   'toplen_ptw': 2.1033307631978513,
   'coherence_20': 0.5652122567522277},
  {'kernel_size': 2425,
   'toplen_ptw': 1.5930064341420966,
   'coherence_20': 0.7399134739515556},
  {'kernel_size': 2129,
   'toplen_ptw': 2.2090052695841957,
   'coherence_20': 0.8517489835331927},
  {'kernel_size': 2251,
   'toplen_ptw': 1.8861518965419863,
   'coherence_20': 0.7750950713837468},
  {'kernel_size': 2750,
   'toplen_ptw': 1.983748788229375,
   'coherence_20': 0.5359304380410814},
  {'kernel_size': 2473,
   'toplen_ptw': 1.866678746448657,
   'coherence_20': 0.4082815674877905},
  {'kernel_size': 2685,
   'toplen_ptw': 3.036466339911837,
   'coherence_20': 0.6811707884287551},
  {'kernel_size': 2317,
   'toplen_ptw': 1.6861346744101686,
   'coherence_20': 0.4421795434628226},
  {'kernel_size': 2242,
   'toplen_ptw': 2.134203245966476,
   'coherence_20': 0.8398903917303375},
  {'kernel_size': 2119,
   'toplen_ptw': 2.397965435766822,
   'coherence_20': 0.7483855531416314},
  {'kernel_size': 2075,
   'toplen_ptw': 2.8265438466621013,
   'coherence_20': 0.43817577026656446},
  {'kernel_size': 2612,
   'toplen_ptw': 1.5262756029823634,
   'coherence_20': 0.616725619388275}],
 [{'kernel_size': 2382,
   'toplen_ptw': 1.6114234994169185,
   'coherence_20': 0.6928692369366901},
  {'kernel_size': 2321,
   'toplen_ptw': 1.8385684123732018,
   'coherence_20': 0.8459745797737116},
  {'kernel_size': 2238,
   'toplen_ptw': 1.8855524252413864,
   'coherence_20': 0.675020584063716},
  {'kernel_size': 2209,
   'toplen_ptw': 2.0679006065177528,
   'coherence_20': 0.5552257892355542},
  {'kernel_size': 2143,
   'toplen_ptw': 2.377406103494036,
   'coherence_20': 0.6367746041467038},
  {'kernel_size': 2293,
   'toplen_ptw': 1.9786135814509893,
   'coherence_20': 0.6021682948873679},
  {'kernel_size': 2517,
   'toplen_ptw': 2.259193555854185,
   'coherence_20': 0.4619729450811841},
  {'kernel_size': 1928,
   'toplen_ptw': 1.8829367771100403,
   'coherence_20': 0.5219714530115261},
  {'kernel_size': 1919,
   'toplen_ptw': 2.823777665607526,
   'coherence_20': 0.518824799928942},
  {'kernel_size': 2596,
   'toplen_ptw': 1.5519514714768052,
   'coherence_20': 0.4698796519435349},
  {'kernel_size': 2323,
   'toplen_ptw': 2.919050344432382,
   'coherence_20': 0.8941457220779288},
  {'kernel_size': 1836,
   'toplen_ptw': 2.1134613748765774,
   'coherence_20': 0.7064558353507718},
  {'kernel_size': 2448,
   'toplen_ptw': 1.738049234247813,
   'coherence_20': 0.6680000182478297},
  {'kernel_size': 2287,
   'toplen_ptw': 2.218229811401305,
   'coherence_20': 0.6598919233119608},
  {'kernel_size': 2378,
   'toplen_ptw': 1.6351349241784294,
   'coherence_20': 1.1103084679003998},
  {'kernel_size': 2431,
   'toplen_ptw': 1.790634906482596,
   'coherence_20': 0.5129554590588329},
  {'kernel_size': 2379,
   'toplen_ptw': 2.835453478078353,
   'coherence_20': 0.9962215241844933},
  {'kernel_size': 2137,
   'toplen_ptw': 2.023269932716455,
   'coherence_20': 0.7028272535377733},
  {'kernel_size': 2610,
   'toplen_ptw': 1.6506203330594924,
   'coherence_20': 0.873770243279383},
  {'kernel_size': 2884,
   'toplen_ptw': 2.2517377058064056,
   'coherence_20': 0.5045709295878826}],
 [{'kernel_size': 2362,
   'toplen_ptw': 2.0793166027375025,
   'coherence_20': 0.5149733716405174},
  {'kernel_size': 2097,
   'toplen_ptw': 2.3656277343819236,
   'coherence_20': 0.5427892059062311},
  {'kernel_size': 2774,
   'toplen_ptw': 2.0934773162159686,
   'coherence_20': 0.6842088632081852},
  {'kernel_size': 2097,
   'toplen_ptw': 1.8084267342777025,
   'coherence_20': 0.5964976244250233},
  {'kernel_size': 2704,
   'toplen_ptw': 2.964242461728366,
   'coherence_20': 0.7782710985227281},
  {'kernel_size': 2356,
   'toplen_ptw': 2.256236309942394,
   'coherence_20': 0.723211293069089},
  {'kernel_size': 2212,
   'toplen_ptw': 2.116541736139148,
   'coherence_20': 0.8566705834654047},
  {'kernel_size': 2400,
   'toplen_ptw': 2.0252501906057723,
   'coherence_20': 0.8642075582476475},
  {'kernel_size': 2206,
   'toplen_ptw': 1.9592547276220644,
   'coherence_20': 0.5705554347500877},
  {'kernel_size': 2395,
   'toplen_ptw': 1.972645657176022,
   'coherence_20': 0.6133238751654682},
  {'kernel_size': 1911,
   'toplen_ptw': 2.738975521582158,
   'coherence_20': 0.4451442727372301},
  {'kernel_size': 2448,
   'toplen_ptw': 1.6747179235176666,
   'coherence_20': 0.5328736208983712},
  {'kernel_size': 2209,
   'toplen_ptw': 1.7436827002263597,
   'coherence_20': 0.5778055612208597},
  {'kernel_size': 2231,
   'toplen_ptw': 2.0001283753546364,
   'coherence_20': 0.7001128413043636},
  {'kernel_size': 2245,
   'toplen_ptw': 2.035395314258861,
   'coherence_20': 0.7647076381880197},
  {'kernel_size': 2399,
   'toplen_ptw': 1.80894103031029,
   'coherence_20': 0.7493690657597257},
  {'kernel_size': 2377,
   'toplen_ptw': 1.8567443672748931,
   'coherence_20': 0.6040731960665635},
  {'kernel_size': 2489,
   'toplen_ptw': 1.5582337840415479,
   'coherence_20': 0.5262192763208874},
  {'kernel_size': 2585,
   'toplen_ptw': 2.712646758763995,
   'coherence_20': 0.8745198962898141},
  {'kernel_size': 1952,
   'toplen_ptw': 1.9520598600789527,
   'coherence_20': 0.6215131006641905}],
 [{'kernel_size': 2244,
   'toplen_ptw': 1.862508367602715,
   'coherence_20': 1.1170993178221873},
  {'kernel_size': 2127,
   'toplen_ptw': 2.221702801269295,
   'coherence_20': 0.7626959239474703},
  {'kernel_size': 1965,
   'toplen_ptw': 2.133271712527481,
   'coherence_20': 1.0751789683259085},
  {'kernel_size': 1882,
   'toplen_ptw': 2.2558979346060086,
   'coherence_20': 0.5113573891326446},
  {'kernel_size': 2251,
   'toplen_ptw': 2.3858384125246004,
   'coherence_20': 0.6345315648179809},
  {'kernel_size': 2001,
   'toplen_ptw': 1.9681641558834122,
   'coherence_20': 0.7798988590765501},
  {'kernel_size': 2549,
   'toplen_ptw': 1.6375003309046243,
   'coherence_20': 0.6561899716840549},
  {'kernel_size': 2085,
   'toplen_ptw': 1.856012624992399,
   'coherence_20': 0.6749503428758131},
  {'kernel_size': 2367,
   'toplen_ptw': 1.6652650318018969,
   'coherence_20': 0.6609307891754028},
  {'kernel_size': 2705,
   'toplen_ptw': 1.5164763604737812,
   'coherence_20': 0.6255699300442664},
  {'kernel_size': 2840,
   'toplen_ptw': 3.12160812006116,
   'coherence_20': 0.7340285222344926},
  {'kernel_size': 2393,
   'toplen_ptw': 2.0363662426418747,
   'coherence_20': 0.35762090932025237},
  {'kernel_size': 2285,
   'toplen_ptw': 1.9171202175660471,
   'coherence_20': 0.6371244195983947},
  {'kernel_size': 2235,
   'toplen_ptw': 1.8521781597315676,
   'coherence_20': 0.8562292729874569},
  {'kernel_size': 2309,
   'toplen_ptw': 2.1454500001706407,
   'coherence_20': 0.690428472257142},
  {'kernel_size': 2282,
   'toplen_ptw': 1.9482970467621747,
   'coherence_20': 0.6456012675313907},
  {'kernel_size': 2325,
   'toplen_ptw': 1.887827022836333,
   'coherence_20': 0.5077482593861967},
  {'kernel_size': 2434,
   'toplen_ptw': 2.0669272237011236,
   'coherence_20': 0.8434905720936103},
  {'kernel_size': 2028,
   'toplen_ptw': 2.337249356383945,
   'coherence_20': 0.86203892756161},
  {'kernel_size': 2223,
   'toplen_ptw': 2.5040392833897416,
   'coherence_20': 0.45388156116767037}],
 [{'kernel_size': 2295,
   'toplen_ptw': 2.2942642846819807,
   'coherence_20': 0.7204185971342963},
  {'kernel_size': 2336,
   'toplen_ptw': 1.9981239599957183,
   'coherence_20': 0.469019490301435},
  {'kernel_size': 2764,
   'toplen_ptw': 1.9076532110844728,
   'coherence_20': 0.664046342557792},
  {'kernel_size': 2303,
   'toplen_ptw': 1.788767017563077,
   'coherence_20': 0.6200272285359754},
  {'kernel_size': 2474,
   'toplen_ptw': 1.844555651467763,
   'coherence_20': 0.4171958625995248},
  {'kernel_size': 2454,
   'toplen_ptw': 1.8306371693368797,
   'coherence_20': 0.8122759191606079},
  {'kernel_size': 2209,
   'toplen_ptw': 2.7223371916283914,
   'coherence_20': 0.7191824125613963},
  {'kernel_size': 2239,
   'toplen_ptw': 1.8676686929489887,
   'coherence_20': 0.7847585074345937},
  {'kernel_size': 2353,
   'toplen_ptw': 2.0136278279961988,
   'coherence_20': 0.6638047226348822},
  {'kernel_size': 2685,
   'toplen_ptw': 1.7094938249220666,
   'coherence_20': 0.5295417162227567},
  {'kernel_size': 2097,
   'toplen_ptw': 2.5507841912691407,
   'coherence_20': 0.47806831982206127},
  {'kernel_size': 2288,
   'toplen_ptw': 1.641563121396751,
   'coherence_20': 0.8053112699044995},
  {'kernel_size': 2521,
   'toplen_ptw': 2.369118898306913,
   'coherence_20': 0.8624460108643169},
  {'kernel_size': 2036,
   'toplen_ptw': 2.484370937156104,
   'coherence_20': 0.8843190692998462},
  {'kernel_size': 2167,
   'toplen_ptw': 1.7943862227123109,
   'coherence_20': 0.7154722716320479},
  {'kernel_size': 2262,
   'toplen_ptw': 2.098071830161201,
   'coherence_20': 0.7333890738675947},
  {'kernel_size': 2250,
   'toplen_ptw': 1.9006591211750867,
   'coherence_20': 0.5843855811319489},
  {'kernel_size': 2446,
   'toplen_ptw': 2.487072079985247,
   'coherence_20': 0.5048065787380108},
  {'kernel_size': 2014,
   'toplen_ptw': 1.9374740809731734,
   'coherence_20': 0.9472912634231049},
  {'kernel_size': 1988,
   'toplen_ptw': 2.26867940603428,
   'coherence_20': 0.6680866129882908}],
 [{'kernel_size': 2115,
   'toplen_ptw': 2.6633377061439183,
   'coherence_20': 0.4272889416178157},
  {'kernel_size': 2275,
   'toplen_ptw': 2.0113028362334986,
   'coherence_20': 0.6237063606104587},
  {'kernel_size': 1984,
   'toplen_ptw': 2.290318043978741,
   'coherence_20': 0.8830299277587506},
  {'kernel_size': 2238,
   'toplen_ptw': 1.8820025299177625,
   'coherence_20': 0.6815683114518074},
  {'kernel_size': 2412,
   'toplen_ptw': 2.2684564348198517,
   'coherence_20': 0.4770071288565366},
  {'kernel_size': 2208,
   'toplen_ptw': 2.781845299818841,
   'coherence_20': 1.133255751171514},
  {'kernel_size': 2491,
   'toplen_ptw': 1.7833813226078825,
   'coherence_20': 0.6438743571113338},
  {'kernel_size': 2441,
   'toplen_ptw': 2.3029551043230163,
   'coherence_20': 0.7412524290256408},
  {'kernel_size': 2109,
   'toplen_ptw': 2.3168134960292655,
   'coherence_20': 0.6590706400964759},
  {'kernel_size': 2308,
   'toplen_ptw': 1.6265869532085064,
   'coherence_20': 0.9202651602558044},
  {'kernel_size': 2461,
   'toplen_ptw': 1.6745217510167054,
   'coherence_20': 0.7084343184592141},
  {'kernel_size': 2418,
   'toplen_ptw': 1.996411308827184,
   'coherence_20': 0.65944186572251},
  {'kernel_size': 2654,
   'toplen_ptw': 2.4019272040974315,
   'coherence_20': 0.6404711659235856},
  {'kernel_size': 2552,
   'toplen_ptw': 2.4911697359972345,
   'coherence_20': 0.7057234599619779},
  {'kernel_size': 2084,
   'toplen_ptw': 1.8224533798023022,
   'coherence_20': 0.7518313334084953},
  {'kernel_size': 2286,
   'toplen_ptw': 1.8223719490639512,
   'coherence_20': 0.9076688640928124},
  {'kernel_size': 1891,
   'toplen_ptw': 2.087620893947733,

In [76]:
for m in optimizer._result['model_topic_scores']:
    print(len([
        v for v in m
        if v['toplen_ptw'] >= 2.5358203425535235
    ]))

3
3
3
2
2
3
3
1
2
2
1
2
2
3
2
3
1
2
2
3

In [109]:
! echo $SEARCH_RESULTS_FOLDER_PATH
! ls $SEARCH_RESULTS_FOLDER_PATH

./MKB_10__internals/result2
bank__0  search_result__0.json

In [124]:
! ls Good_RU_Wiki__internals

batches  dict.dict  result  result2  vw.txt