# TopicBank: Bank Creation Experiment

Here we are going to collect interpretable topics (automatically, using topic coherence) from multiple model training.
These topics constitute *topic bank*.
And then the topic bank is going to be used for estimating topic models quality in the notebook [TopicBank-Experiment: Model Validation](TopicBank-Experiment-ModelValidation.ipynb).

The process is repeated for several datasets (some of them are already downloadable using [TopicNet](https://github.com/machine-intelligence-laboratory/TopicNet) library).

# Contents<a id="contents"></a>

* [Data](#data)
    * [Coocs](#coocs)
        * [Lower Memory Consumption (or a Bit of Shamanism. Part 1)](#optimizing-memory)
    * [Documents for Coherence Scores](#docs-for-cohs)
        * [Lower Time Consumption in Case of Big Datasets (or a Bit of Shamanism. Part 2)](#optimizing-time)
* [Experiment](#experiment)
    * [Scores](#scores)
    * [Bank Creation](#bank-creation)
* [Postprocessing](#postprocessing)

In [1]:
# General imports

import dill
import itertools
import json
import numpy as np
import os
import pandas as pd
import sys

from enum import Enum
from scipy.stats import gaussian_kde
from matplotlib import pyplot as plt
from tqdm import tqdm
from typing import (
    Dict,
    Iterable,
)

%matplotlib inline

In [2]:
# Making `topnum` module visible for Python

sys.path.insert(0, '../OptimalNumberOfTopics')

In [3]:
# Optimal number of topics

from topicnet.cooking_machine import Dataset

from topnum.data.vowpal_wabbit_text_collection import VowpalWabbitTextCollection
from topnum.scores import (
    PerplexityScore,
    SparsityPhiScore,
    SparsityThetaScore,
)
from topnum.scores.diversity_score import DiversityScore, KNOWN_METRICS
from topnum.scores._base_coherence_score import (
    SpecificityEstimationMethod,
    TextType,
    WordTopicRelatednessType,
)
from topnum.scores.intratext_coherence_score import ComputationMethod
from topnum.search_methods import TopicBankMethod
from topnum.search_methods.topic_bank.topic_bank import TopicBank
from topnum.search_methods.topic_bank.one_model_train_funcs import (
    default_train_func,

    # Functions below are not used (but could have been)

#     regularization_train_func,
#     specific_initial_phi_train_func,
#     background_topics_train_func,

)

## Data<a id="data"></a>

<div style="text-align: right">Back to <a href=#contents>Contents</a></div>

Loading data from disk, creating batches, dictionary, gathering cooccurrence statistics...

In [4]:
DATA_FOLDER_PATH = '/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/dataset_manager'

In [5]:
sorted(os.listdir(DATA_FOLDER_PATH))

['20NG.csv',
 '20NG__internals',
 'Brown',
 'Brown_BOW.csv',
 'Brown_NOOW.csv',
 'MKB10.csv',
 'MKB10__internals',
 'RTL_Wiki.csv',
 'RTL_Wiki_person.csv',
 'RTL_Wiki_person__internals',
 'Reuters',
 'Reuters_BOW.csv',
 'Reuters_NOOW.csv',
 'WikiRef-220',
 '__init__.py',
 '__pycache__',
 'api.py',
 'postnauka.csv',
 'postnauka__internals',
 'ruwiki_good.txt',
 'ruwiki_good__internals',
 'wiki_ref220_bow.csv',
 'wiki_ref220_natural_order.csv']

In [6]:
class DatasetName(Enum):
    POSTNAUKA = 'Post_Science'
    # REUTERS = 'Reuters'
    # BROWN = 'Brown'
    TWENTY_NEWSGROUPS = '20_Newsgroups'
    GOOD_RU_WIKI = 'Good_RU_Wiki'
    RTL_WIKI_PERSON = 'RTL_Wiki_Person'

In [7]:
DATASET_NAME_TO_DATASET_FILE_PATH = {
    DatasetName.POSTNAUKA: os.path.join(
        DATA_FOLDER_PATH, 'postnauka.csv'
    ),
    # DatasetName.REUTERS: os.path.join(
    #     DATA_FOLDER_PATH, 'Reuters.csv'
    # ),
    # DatasetName.BROWN: os.path.join(
    #     DATA_FOLDER_PATH, 'Brown.csv'
    # ),
    DatasetName.TWENTY_NEWSGROUPS: os.path.join(
        DATA_FOLDER_PATH, '20NG.csv'
    ),
    # DatasetName.AG_NEWS: os.path.join(
    #     DATA_FOLDER_PATH, 'AG_News.csv'
    # ),
    # DatasetName.WATAN: os.path.join(
    #     DATA_FOLDER_PATH, 'Watan2004.csv'
    # ),
    # DatasetName.HABRAHABR: os.path.join(
    #     DATA_FOLDER_PATH, 'Habrahabr.csv'
    # ),
    DatasetName.GOOD_RU_WIKI: os.path.join(
        DATA_FOLDER_PATH, 'ruwiki_good.txt'
    ),
    DatasetName.RTL_WIKI_PERSON: os.path.join(
        DATA_FOLDER_PATH, 'RTL_Wiki_person.csv'
    ),
}

In [8]:
DATASET_NAME = DatasetName.RTL_WIKI_PERSON  # select a dataset here

DATASET_FILE_PATH = DATASET_NAME_TO_DATASET_FILE_PATH[DATASET_NAME]

Checking if all OK with data, what modalities does the collection have.

In [9]:
! head -n 2 $DATASET_FILE_PATH

,id,raw_text,vw_text
0,İsmet_İnönü,"Mustafa İsmet İnönü (September 24 1884 – December 25, 1973) was a Turkish Army General, TSK Genel Kurmay Baskanlari  Prime Minister and the second President of the Republic of Turkey. He is widely referred to as ""Milli Şef"" (National Chief), a title he bestowed upon himself  when he was elected as the President of Turkey in 1938.  Family and early life He was born in İzmir to a family originally from Malatya with mixed Turkish-Kurdish heritage. The Young Turks – Children of the Borderlands? - Erik Jan Zürcher (Universiteit Leiden)  Ismet Inonu: The Making of a Turkish Statesman - Metin Heper / Brill Academic Publishers  His father was Hacı Reşid Bey, a member of the Ottoman bureaucracy, an examining magistrate born in Malatya, and his mother was Cevriye Hanım, daughter of Russo-Turkish War refugees from Bulgaria. Due to his father's assignments, the family moved from one city to another. Thus, İsmet İnönü completed his primary education in Sivas.  For more than half his life, İsmet İnönü was known as İsmet Pasha. He changed his name in the early 1930s when President Atatürk decreed that all his countrymen had to have surnames. İsmet Pasha decided to take as his surname ""İnönü"", from the Central Anatolian town where he commanded the Turkish forces in his greatest battles as a general, known as the First Battle of İnönü and Second Battle of İnönü, victories which played an important role in the Turkish War of Independence.  His son, Erdal İnönü, was a Wigner medal winner mathematical physicist and a former deputy prime minister of Turkey, as well as the former leader of the Social Democracy Party and the Social Democratic Populist Party, and the honorary leader of the Social Democratic People's Party.  Early military career İnönü graduated from the Military Academy in 1903 as gunnery officer, and received his first military assignment in the Ottoman army. He joined the Committee of Union and Progress. He won his first military victories by suppressing two major revolts against the struggling Ottoman Empire, first in Rumelia and later in Yemen, whose leader was Yahya Muhammad Hamid ed-Din. He served as a military officer during the Balkan Wars on the Ottoman-Bulgarian front. During World War I, he served as a miralay (colonel) on the Ottoman eastern front in Syria, and was later appointed as the commander of the western fronts. He worked together with Mustafa Kemal Pasha during his assignment at the Caucasus front.  Independence war After losing the Battle of Megiddo against General Edmund Allenby during the last days of World War I, he went to Anatolia to join the Turkish nationalist movement and was appointed the commander of the Turkish Western Army, a position in which he remained during the Turkish War of Independence. He was promoted to brigadier general after the ""Battles of İnönü"", in which he successfully defeated the Greek Army in western Anatolia. During the Turkish War of Independence he was also a member of the Turkish Grand National Assembly in Ankara.  İnönü was replaced by Fevzi Paşa as the Chief of Staff of the Turkish Army after the Turkish army lost a battle against the advancing Greek Army in July 1921, as a result of which the cities Afyon, Kütahya and Eskişehir were lost. Later, he was appointed as the chief negotiator of the Turkish delegation at the Treaty of Lausanne.  He became famous for his resolve and stubbornness in defending Turkey's demands while conceding very little to the other side at the negotiating table, causing the peace conference to last longer than expected.  Partially deaf, İnönü simply turned off his hearing aid when the British foreign secretary, Lord Curzon, launched into lengthy speeches opposing Turkish demands for recognition of the national pact, and then would restate the Turkish position as if the British foreign secretary had not said a thing.  Political career İnönü later served as the Prime Minister of Turkey for several terms, maintaining the system that Atatürk had put in place. He acted after every major crisis (such as the rebellion of Sheikh Said or the attempted assassination of Atatürk in İzmir) to restore peace in the country. He tried to manage the economy with heavy-handed government intervention, especially after the 1929 economic crisis, by implementing an economic plan inspired by the Five Year Plan of the Soviet Union. In doing so, he took much private property under government control. Due to his efforts, to this day, more than 70% of land in Turkey is still owned by the state, resembling the now-defunct Soviet Union. Desiring a more liberal economic system, Atatürk forced Inönü , from the government leadership in 1937 and appointed Celal Bayar, the founder of the first Turkish bank Türkiye İş Bankası as Prime Minister.  ""National Chief"" period Churchill secretly meets with Inönü inside a train wagon at the Yenice Station 23 kilometers outside of Adana, Turkey, on January 30, 1943 After the death of Atatürk, Inönü was viewed as the most appropriate candidate to succeed him, and was elected the second President of the Republic of Turkey and enjoyed the official title of ""Milli Şef"", i.e. ""National Chief"".  World War II broke out in the first year of his presidency, and both the Allies and the Axis pressured Inönü to bring Turkey into the war on their side. The Germans sent Franz von Papen to Ankara, while Winston Churchill secretly met with Inönü inside a train wagon near Adana on January 30, 1943. Inönü later met with Franklin D. Roosevelt and Winston Churchill at the Second Cairo Conference on December 4-6, 1943. Until 1941, both Roosevelt and Churchill thought that Turkey's continuing neutrality would serve the interests of the Allies by blocking the Axis from reaching the strategic oil reserves of the Middle East. But the early victories of the Axis up to the end of 1942 caused Roosevelt and Churchill to re-evaluate a possible Turkish participation in the war on the side of the Allies. Turkey had maintained a decently-sized Army and Air Force throughout the war, and Churchill wanted the Turks to open a new front in the Balkans. Roosevelt, on the other hand, still believed that a Turkish attack would be too risky, and an eventual Turkish failure would have disastrous effects for the Allies. Inönü knew very well the hardships which his country had suffered during decades of incessant war between 1908 and 1922 and was determined to keep Turkey out of another war as long as he could. The young Turkish Republic was still re-building, recovering from the losses due to earlier wars, and lacked any modern weapons and the infrastructure to enter a war to be fought along and possibly within its borders. Inönü also wanted assurances on financial and military aid for Turkey, as well as a guarantee that the United States and the United Kingdom would stand beside Turkey in the event of a Soviet invasion of the Turkish Straits after the war. The fear of Soviet invasion and Stalin's unconcealed desire to control the Turkish Straits eventually caused Turkey to give up its principle of neutrality in foreign relations and join NATO in 1952.  The economic conditions in Turkey during his Presidency can be described as ""depression"", as evidenced by the negative economic growth between 1938 to 1950 http://www.ggdc.net/Maddison/Historical_Statistics/horizontal-file_03-2007.xls , which may explain why he could not win any democratic elections (in 1950, 1954, 1957, 1961, 1965 and 1969) in his country. Yet, overcoming strong opposition within his own party, he still switched Turkey to a multi-party democracy which allowed the previously mentioned elections to be held in the first place. He probably is the only leader in the World History who gave up absolute ruling power and continue as the leader of the opposition party. It may be that Inönü's greatest political achievement was keeping his country out of World War II until February 1945, when Turkey entered the war on the side of the Allies against Germany and Japan.  Multi party period İnönü's tomb at Anıtkabir  Under international pressure to transform the country to a democratic state, Inönü resided over the infamous 1946 elections, in which votes were cast in the open with onlookers (most probably secret police) able to observe to which party the voters had cast their votes and ballots were tallied behind closed doors by only his own party's officials. In 1950, his party lost the first free elections in Turkish history, and Inönü presided over the peaceful transfer of power to the Democratic Party of Adnan Menderes. İnönü served for ten years as the leader of the opposition before returning to power as Prime Minister after the 1961 election, held after the military coup-d'etat in 1960 in which he allegedly conspired. Although the opposition was imprisoned during the 1961 elections, he still did not win a majority and had to form coalition governments until the 1965 elections. He lost both the 1965 and 1969 general elections to Süleyman Demirel and then in 1972 he lost his party's leadership race to Bülent Ecevit.  Ismet Inönü was by the standards of his time a highly educated man, speaking Arabic, English, French and German in addition to his native Turkish.  İnönü died in 1973. He was interred next to Atatürk's mausoleum at Anıtkabir in Ankara and a massive tomb was constructed there.  Legacy İnönü University in Malatya is named after him, as is a stadium in Istanbul, home of the Beşiktaş football club.  Media  Image:IsmetInonu1963.ogg (The sound file of the message by President İsmet İnönü on Kemal Atatürk, November 10, 1963) Image:IsmetInonu1963 text.pdf (The Text of the message by President İsmet İnönü on Atatürk)  See also Pembe Köşk - Private home from 1925 to 1973 Çankaya Köşkü - The Presidency of the Republic of Turkey  References",İsmet_İnönü |@lemmatized mustafa:2 smet:7 nönü:18 september:1 december:2 turkish:25 army:8 general:5 tsk:1 genel:1 kurmay:1 baskanlari:1 prime:5 minister:5 second:4 president:6 republic:4 turkey:19 widely:1 refer:1 milli:2 şef:2 national:5 chief:5 title:2 bestow:1 upon:1 elect:2 family:3 early:5 life:2 bear:2 zmir:2 originally:1 malatya:3 mixed:1 kurdish:1 heritage:1 young:2 turk:2 child:1 borderland:1 erik:1 jan:1 zürcher:1 universiteit:1 leiden:1 ismet:2 inonu:1 making:1 statesman:1 metin:1 heper:1 brill:1 academic:1 publisher:1 father:2 hacı:1 reşid:1 bey:1 member:2 ottoman:5 bureaucracy:1 examine:1 magistrate:1 mother:1 cevriye:1 hanım:1 daughter:1 russo:1 war:19 refugee:1 bulgaria:1 due:3 assignment:3 move:1 one:1 city:2 another:2 thus:1 complete:1 primary:1 education:1 siva:1 half:1 know:3 pasha:3 change:1 name:2 atatürk:8 decree:1 countryman:1 surname:2 decide:1 take:2 central:1 anatolian:1 town:1 command:1 force:3 great:2 battle:6 first:8 victory:3 play:1 important:1 role:1 independence:4 son:1 erdal:1 wigner:1 medal:1 winner:1 mathematical:1 physicist:1 former:2 deputy:1 well:3 leader:6 social:3 democracy:2 party:12 democratic:5 populist:1 honorary:1 people:1 military:7 career:2 graduate:1 academy:1 gunnery:1 officer:2 receive:1 join:3 committee:1 union:3 progress:1 win:3 suppress:1 two:1 major:2 revolt:1 struggle:1 empire:1 rumelia:1 later:5 yemen:1 whose:1 yahya:1 muhammad:1 hamid:1 ed:1 din:1 serve:5 balkan:2 bulgarian:1 front:5 world:5 miralay:1 colonel:1 eastern:1 syria:1 appoint:4 commander:2 western:3 work:1 together:1 kemal:2 caucasus:1 lose:6 megiddo:1 edmund:1 allenby:1 last:2 day:2 go:1 anatolia:2 nationalist:1 movement:1 position:2 remain:1 promote:1 brigadier:1 successfully:1 defeat:1 greek:2 also:3 grand:1 assembly:1 ankara:3 replace:1 fevzi:1 paşa:1 staff:1 advance:1 july:1 result:1 afyon:1 kütahya:1 eskişehir:1 negotiator:1 delegation:1 treaty:1 lausanne:1 become:1 famous:1 resolve:1 stubbornness:1 defend:1 demand:2 concede:1 little:1 side:4 negotiating:1 table:1 cause:3 peace:2 conference:2 long:2 expect:1 partially:1 deaf:1 simply:1 turn:1 hearing:1 aid:2 british:2 foreign:3 secretary:2 lord:1 curzon:1 launch:1 lengthy:1 speech:1 oppose:1 recognition:1 pact:1 would:5 restate:1 say:2 thing:1 political:2 several:1 term:1 maintain:2 system:2 put:1 place:2 act:1 every:1 crisis:2 rebellion:1 sheikh:1 attempted:1 assassination:1 restore:1 country:5 try:1 manage:1 economy:1 heavy:1 handed:1 government:4 intervention:1 especially:1 economic:5 implement:1 plan:2 inspire:1 five:1 year:3 soviet:4 much:1 private:2 property:1 control:2 effort:1 land:1 still:5 state:3 resemble:1 defunct:1 desire:2 liberal:1 inönü:12 leadership:2 celal:1 bayar:1 founder:1 bank:1 türkiye:1 ş:1 bankası:1 period:2 churchill:6 secretly:2 meet:3 inside:2 train:2 wagon:2 yenice:1 station:1 kilometer:1 outside:1 adana:2 january:2 death:1 view:1 appropriate:1 candidate:1 succeed:1 enjoy:1 official:2 e:1 ii:2 break:1 presidency:3 ally:5 axis:3 pressure:2 bring:1 german:2 send:1 franz:1 von:1 papen:1 winston:2 near:1 franklin:1 roosevelt:4 cairo:1 think:1 continue:2 neutrality:2 interest:1 block:1 reach:1 strategic:1 oil:1 reserve:1 middle:1 east:1 end:1 evaluate:1 possible:1 participation:1 decently:1 size:1 air:1 throughout:1 want:2 open:2 new:1 hand:1 believe:1 attack:1 risky:1 eventual:1 failure:1 disastrous:1 effect:1 hardship:1 suffer:1 decade:1 incessant:1 determine:1 keep:2 could:2 building:1 recover:1 loss:1 lack:1 modern:1 weapon:1 infrastructure:1 enter:2 fight:1 along:1 possibly:1 within:2 border:1 assurance:1 financial:1 guarantee:1 united:2 kingdom:1 stand:1 beside:1 event:1 invasion:2 strait:2 fear:1 stalin:1 unconcealed:1 eventually:1 give:2 principle:1 relation:1 nato:1 condition:1 describe:1 depression:1 evidence:1 negative:1 growth:1 http:1 www:1 ggdc:1 net:1 maddison:1 horizontal:1 xl:1 may:2 explain:1 election:8 yet:1 overcome:1 strong:1 opposition:4 switch:1 multi:2 allow:1 previously:1 mention:1 hold:2 probably:2 history:2 absolute:1 ruling:1 power:3 achievement:1 february:1 germany:1 japan:1 tomb:2 anıtkabir:2 international:1 transform:1 reside:1 infamous:1 vote:2 cast:2 onlooker:1 secret:1 police:1 able:1 observe:1 voter:1 ballot:1 tally:1 behind:1 closed:1 door:1 free:1 preside:1 peaceful:1 transfer:1 adnan:1 menderes:1 ten:1 return:1 coup:1 etat:1 allegedly:1 conspire:1 although:1 imprison:1 majority:1 form:1 coalition:1 süleyman:1 demirel:1 race:1 bülent:1 ecevit:1 standard:1 time:1 highly:1 educate:1 man:1 speak:1 arabic:1 english:1 french:1 addition:1 native:1 die:1 inter:1 next:1 mausoleum:1 massive:1 construct:1 legacy:1 university:1 stadium:1 istanbul:1 home:2 beşiktaş:1 football:1 club:1 medium:1 image:2 ogg:1 sound:1 file:1 message:2 november:1 text:2 pdf:1 see:1 pembe:1 köşk:1 çankaya:1 köşkü:1 reference:1  |@bigram smet_nönü:5 september_december:1 turkish_army:3 army_general:1 prime_minister:5 second_president:2 president_republic:2 republic_turkey:3 bestow_upon:1 elect_president:1 early_life:1 life_bear:1 family_originally:1 academic_publisher:1 turkish_war:4 family_move:1 change_name:1 decide_take:1 great_battle:1 first_battle:1 second_battle:1 play_important:1 important_role:1 war_independence:3 former_deputy:1 deputy_prime:1 social_democracy:1 social_democratic:2 people_party:1 military_career:1 military_academy:1 receive_first:1 ottoman_army:1 army_join:1 win_first:1 military_victory:1 two_major:1 ottoman_empire:1 serve_military:1 military_officer:1 balkan_war:1 world_war:4 war_serve:1 eastern_front:1 later_appoint:2 appoint_commander:2 western_front:1 work_together:1 lose_battle:2 last_day:1 promote_brigadier:1 brigadier_general:1 also_member:1 grand_national:1 national_assembly:1 chief_staff:1 appoint_chief:1 become_famous:1 peace_conference:1 last_long:1 british_foreign:2 foreign_secretary:2 secretary_lord:1 say_thing:1 political_career:1 later_serve:1 serve_prime:1 put_place:1 every_major:1 attempted_assassination:1 government_intervention:1 economic_crisis:1 five_year:1 year_plan:1 soviet_union:2 take_much:1 private_property:1 government_control:1 economic_system:1 founder_first:1 minister_national:1 official_title:1 war_ii:2 ii_break:1 first_year:1 franz_von:1 winston_churchill:2 later_meet:1 franklin_roosevelt:1 would_serve:1 middle_east:1 army_air:1 air_force:1 throughout_war:1 open_new:1 still_believe:1 know_well:1 country_suffer:1 enter_war:2 war_fight:1 united_state:1 state_united:1 united_kingdom:1 would_stand:1 soviet_invasion:2 foreign_relation:1 economic_growth:1 http_www:1 may_explain:1 could_win:1 strong_opposition:1 within_party:1 previously_mention:1 election_hold:2 hold_first:1 first_place:1 world_history:1 leader_opposition:2 opposition_party:1 country_world:1 democratic_state:1 election_vote:1 secret_police:1 behind_closed:1 closed_door:1 party_official:1 party_lose:1 lose_first:1 free_election:1 transfer_power:1 democratic_party:1 ten_year:1 return_power:1 military_coup:1 coup_etat:1 form_coalition:1 coalition_government:1 general_election:1 party_leadership:1 standard_time:1 english_french:1 french_german:1 football_club:1 see_also:1

In [10]:
def get_dataset_internals_folder_path(dataset_name: DatasetName) -> str:
    return os.path.join('.', dataset_name.value + '__internals')

In [11]:
DATASET_INTERNALS_FOLDER_PATH = get_dataset_internals_folder_path(DATASET_NAME)

In [12]:
DATASET_INTERNALS_FOLDER_PATH

'./RTL_Wiki_Person__internals'

In [13]:
%%time

# If using really big datasets (like Habrahabr),
# one may need to set this equal `False`
KEEP_DATASET_IN_MEMORY = True

DATASET = Dataset(
    DATASET_FILE_PATH,
    internals_folder_path=DATASET_INTERNALS_FOLDER_PATH,
    keep_in_memory=KEEP_DATASET_IN_MEMORY,
)

CPU times: user 809 ms, sys: 120 ms, total: 930 ms
Wall time: 885 ms

Looking what is inside dataset's folder

In [14]:
os.listdir(DATASET_INTERNALS_FOLDER_PATH)

['vw.txt', 'result2', 'batches', 'dict.dict', 'result']

Creating batches

In [15]:
DATASET.get_batch_vectorizer()

artm.BatchVectorizer(data_path="./RTL_Wiki_Person__internals/batches", num_batches=2)

In [16]:
os.listdir(DATASET_INTERNALS_FOLDER_PATH)

['vw.txt', 'result2', 'batches', 'dict.dict', 'result']

In [17]:
if KEEP_DATASET_IN_MEMORY:
    DOCUMENTS = list(DATASET._data.index)
else:
    DOCUMENTS = list(DATASET._data_index)

NUM_DOCUMENTS = len(DOCUMENTS)

print(f'Num documents: {NUM_DOCUMENTS}')

Num documents: 1201

Let's look at some text samples

In [18]:
DATASET._data.head()

,Unnamed: 0,id,raw_text,vw_text
id,,,,
İsmet_İnönü,0,İsmet_İnönü,Mustafa İsmet İnönü (September 24 1884 – Decem...,İsmet_İnönü |@lemmatized mustafa:2 smet:7 nönü...
Clara_Petacci,1,Clara_Petacci,Clara Petacci (Claretta Petacci) (28 February ...,Clara_Petacci |@lemmatized clara:5 petacci:15 ...
Jack_Ruby,2,Jack_Ruby,"Jacob Rubenstein (March 25, 1911 – January 3, ...",Jack_Ruby |@lemmatized jacob:2 rubenstein:5 ma...
Knud_Rasmussen,3,Knud_Rasmussen,"Knud Johan Victor Rasmussen (June 7, 1879–Dece...",Knud_Rasmussen |@lemmatized knud:15 johan:3 vi...
Gerald_Schroeder,4,Gerald_Schroeder,"Gerald L. Schroeder is a scientist, author, an...",Gerald_Schroeder |@lemmatized gerald:4 l:1 sch...

In [19]:
DATASET.get_possible_modalities()

{'@bigram', '@lemmatized'}

In [20]:
MAIN_MODALITY = '@lemmatized'

In [21]:
DATASET.get_dictionary()

artm.Dictionary(name=68b4bcd8-474f-49ce-9b78-de418b7c1481, num_entries=124241)

In [22]:
dictionary = DATASET.get_dictionary()

In [23]:
print(dictionary)

for modality in DATASET.get_possible_modalities():
    if modality not in [MAIN_MODALITY]:
        dictionary.filter(class_id=modality, max_df=0, inplace=True)

artm.Dictionary(name=68b4bcd8-474f-49ce-9b78-de418b7c1481, num_entries=124241)

In [24]:
dictionary.filter(min_df=2, max_df_rate=0.5)

artm.Dictionary(name=68b4bcd8-474f-49ce-9b78-de418b7c1481, num_entries=37739)

In [25]:
DATASET._cached_dict = dictionary

In [26]:
DATASET.get_dictionary()

artm.Dictionary(name=68b4bcd8-474f-49ce-9b78-de418b7c1481, num_entries=37739)

In [27]:
import scipy

from typing import List

from topicnet.cooking_machine.models.base_regularizer import BaseRegularizer
from topicnet.cooking_machine.models.thetaless_regularizer import (
    dataset2sparse_matrix,
)
from topicnet.cooking_machine.models import (
    BaseScore as BaseTopicNetScore,
    TopicModel
)

In [28]:
def calc_doc_occurrences(dataset, modality):
    """
    :param n_dw_matrix: sparse document-word matrix, shape is D x W
    :return: sparse matrix of co-occurrences

    doc_occurrences[w1, w2] = the number of the documents
    where there are w1 and w2
    """
    n_dw_matrix = dataset2sparse_matrix(dataset, modality, modalities_to_use=[modality])
    matrix = (scipy.sparse.csc_matrix(n_dw_matrix) > 0).astype(int)
    co_occurrences = matrix.T * matrix

    return co_occurrences.diagonal(), co_occurrences


def create_pmi_top_function(
    doc_occurrences, doc_co_occurrences,
    documents_number, top_sizes,
    topic_indices=None,
    co_occurrences_smooth=1.
):
    """
    :param doc_occurrences: array of doc occurrences of words
    :param doc_co_occurrences: sparse matrix of doc co-occurrences of words
    :param documents_number: number of the documents
    :param top_sizes: list of top values to calculate top-pmi for
    :param co_occurrences_smooth: constant to smooth co-occurrences in log
    :return: function which takes phi and theta and returns
    pair of two arrays: pmi-s of the tops and ppmi-s of the tops

    pmi[i] - pmi(top of size top_sizes[i])
    ppmi[i] - ppmi(top of size top_sizes[i])

    pmi(words) = sum_{u in words, v in words, u != v}
    log(
        (doc_co_occurrences[u, v] * documents_number + co_occurrences_smooth)
        / doc_occurrences[u] / doc_occurrences[v]
    )

    ppmi(words) = sum_{u in words, v in words, u != v}
    max(log(
        (doc_co_occurrences[u, v] * documents_number + co_occurrences_smooth)
        / doc_occurrences[u] / doc_occurrences[v]
    ), 0)

    """
    def func(phi):
        T, W = phi.shape
        # T = len(topic_indices)
        topic_indices = list(range(T))

        max_top_size = max(top_sizes)
        topic_pmis, topic_ppmis = dict(), dict()
        pmi, ppmi = np.zeros(max_top_size), np.zeros(max_top_size)
        tops = np.argpartition(phi, -max_top_size, axis=1)[:, -max_top_size:]
        
        for t in topic_indices:
            top = sorted(tops[t], key=lambda w: - phi[t, w])
            # print(top, phi.shape, doc_co_occurrences.shape)
            co_occurrences = doc_co_occurrences[top, :][:, top].todense()
            occurrences = doc_occurrences[top]
            values = np.log(
                (co_occurrences * documents_number + co_occurrences_smooth)
                / (occurrences[:, np.newaxis] * occurrences[np.newaxis, :] + co_occurrences_smooth)
            )
            diag = np.diag_indices(len(values))
            # values.cumsum(axis=0).cumsum(axis=1)[diag] - values[diag].cumsum()

            current_pmi = np.array(
               values.cumsum(axis=0).cumsum(axis=1)[diag] - values[diag].cumsum()
            ).ravel()
            topic_pmis[t] = current_pmi
            pmi += current_pmi

            values[values < 0.] = 0.
            current_ppmi = np.array(
               values.cumsum(axis=0).cumsum(axis=1)[diag] - values[diag].cumsum()
            ).ravel()
            topic_ppmis[t] = current_ppmi
            ppmi += current_ppmi
            
        sizes = np.arange(2, max_top_size + 1)
        pmi[1:] /= (T * sizes * (sizes - 1))
        ppmi[1:] /= (T * sizes * (sizes - 1))
        indices = np.array(top_sizes) - 1

        for t in topic_indices:
            topic_pmis[t][1:] /= (sizes * (sizes - 1))
            topic_ppmis[t][1:] /= (sizes * (sizes - 1))

        result_topic_pmis = {t: p[indices] for t, p in topic_pmis.items()}
        result_topic_ppmis = {t: p[indices] for t, p in topic_ppmis.items()}

        return pmi[indices], ppmi[indices], result_topic_pmis, result_topic_ppmis

    return func

In [29]:
%%time

occurences, co_occurences = calc_doc_occurrences(DATASET, MAIN_MODALITY)

CPU times: user 6.59 s, sys: 232 ms, total: 6.82 s
Wall time: 6.75 s

In [30]:
co_occurences.shape

(37739, 37739)

In [31]:
calc_pmi = create_pmi_top_function(
    occurences, co_occurences,
    DATASET.get_dataset().shape[0], [20],
    topic_indices=[0, 1, 2],
    co_occurrences_smooth=1e-2,
)

In [32]:
import copy


class TopTokenCoherence(BaseTopicNetScore):
    def __init__(self, name, func):
        super().__init__()

        self._name = name
        self.calc_pmi = func

    @property
    def name(self):
        return self._name

    def call(self, model: TopicModel):
        values = self.calc_pmi(model.get_phi_dense()[0].T)

        return values[1]

    def call_by_topic(self, model: TopicModel):
        values = self.calc_pmi(model.get_phi_dense()[0].T)

        return values[3]

    def compute(
            self,
            model,
            topics: List[str] = None,
            documents: List[str] = None) -> Dict[str, float]:

        values = self.call_by_topic(model)

        phi = model.get_phi()

        if topics is None:
            topics = list(phi.columns)

            if hasattr(model, 'has_bcg'):
                print(f'Detected bcg topics! Skipping for coherence computation (and will have {len(topics) - 1} topics).')

                topics = topics[:-1]
        else:
            assert False

        index2topic = {phi.columns.get_loc(t): t for t in topics}
        topic2index = {t: i for i, t in index2topic.items()}

        if hasattr(model, 'has_bcg'):
            assert list(index2topic.keys()) == list(values.keys())[:-1]
        else:
            assert list(index2topic.keys()) == list(values.keys())

        result = {
            t: float(values[topic2index[t]])
            for t in topics
        }

        assert len(result) == len(index2topic)

        return result

    def _attach(self, model: TopicModel):
        if self._name in model.custom_scores:
            print(
                f'Score with such name "{self._name}" already attached to model!'
                f' So rewriting it...'
                f' All model\'s custom scores: {list(model.custom_scores.keys())}'
            )

        # TODO: TopicModel should provide ability to add custom scores
        model.custom_scores[self.name] = copy.deepcopy(self)

## Experiment<a id="experiment"></a>

Finally we are getting to the main part!)

### Scores (for Topics and Models)<a id="scores"></a>

<div style="text-align: right">Back to <a href=#contents>Contents</a></div>

Here we define a lot of scores (which mainly differ in initial parameters).

In [33]:
ONE_MODEL_NUM_TOPICS = 50
NUM_TOP_WORDS = 20

In [34]:
top = NUM_TOP_WORDS
target_topic_indices = list(range(ONE_MODEL_NUM_TOPICS))

coherence_score = TopTokenCoherence(
    name=f'coherence_{top}',
    func=create_pmi_top_function(
        occurences, co_occurences,
        DATASET.get_dataset().shape[0], [top],
        # topic_indices=target_topic_indices,
        co_occurrences_smooth=1e-2,
    )
)

diversity_scores = [
    DiversityScore(
        name=f'diversity_{metric}',
        metric=metric,
        class_ids=MAIN_MODALITY,
    )

    for metric in KNOWN_METRICS
]

Other coherence score variations

And a pair of default ARTM scores (these ones are fast)

In [35]:
other_scores = [
    PerplexityScore(
        name='perplexity'
    ),
]

### Bank Creation<a id="bank-creation"></a>

<div style="text-align: right">Back to <a href=#contents>Contents</a></div>

Here we finally run the experiment!

In [36]:
NUM_ITERATIONS = 20

In [37]:
seed = 0

In [38]:
# We use only one train function here
# Other variations are also possible
# It would be even better to make bank using several train functions
# However, it would also take way more time 

TRAIN_FUNCS = default_train_func  # default train func

In [39]:
DATASET_INTERNALS_FOLDER_PATH

'./RTL_Wiki_Person__internals'

In [40]:
SEARCH_RESULTS_FOLDER_PATH = os.path.join(
    DATASET_INTERNALS_FOLDER_PATH, 'result_50'
)

# File with some info about the process
SEARCH_RESULT_FILE_PATH = os.path.join(
    SEARCH_RESULTS_FOLDER_PATH, f'search_result__{seed}.json'
)

# Bank, with topics and their score values
BANK_FOLDER_PATH = os.path.join(
    SEARCH_RESULTS_FOLDER_PATH, f'bank__{seed}'
)

In [41]:
! echo $DATASET_INTERNALS_FOLDER_PATH
! ls -alh $DATASET_INTERNALS_FOLDER_PATH

./RTL_Wiki_Person__internals
total 17M
drwxrwxr-x  5 alekseev_v mil_lab 4,0K мар 28 02:01 .
drwxrwxr-x 11 alekseev_v mil_lab 4,0K мар 27 23:57 ..
drwxrwxr-x  2 alekseev_v mil_lab 4,0K мар 25 15:05 batches
-rw-rw-r--  1 alekseev_v mil_lab 4,5M мар 25 15:05 dict.dict
drwxrwxr-x  3 alekseev_v mil_lab 4,0K мар 25 15:06 result
drwxrwxr-x  3 alekseev_v mil_lab 4,0K мар 25 15:42 result2
-rw-rw-r--  1 alekseev_v mil_lab  12M мар 25 15:05 vw.txt

In [42]:
SEARCH_RESULTS_FOLDER_PATH

'./RTL_Wiki_Person__internals/result_50'

In [43]:
! ls $SEARCH_RESULTS_FOLDER_PATH

ls: cannot access './RTL_Wiki_Person__internals/result_50': No such file or directory

In [44]:
BANK_FOLDER_PATH

'./RTL_Wiki_Person__internals/result_50/bank__0'

In [45]:
os.makedirs(SEARCH_RESULTS_FOLDER_PATH, exist_ok=True)
os.makedirs(BANK_FOLDER_PATH, exist_ok=True)

In [46]:
seed

0

One cay vary some parameters below (for example `max_num_models` and `num_fit_iterations`).

In [47]:
optimizer = TopicBankMethod(
    data        = DATASET,
    main_modality = MAIN_MODALITY,
    
    min_df_rate = 0.0,  # dictionary filtering has already been done little earlier
    max_df_rate = 1.0,  #   so we don't want these parameters to have any effect

    main_topic_score   = coherence_score,
    other_topic_scores = [],
    other_scores       = [coherence_score] + diversity_scores + other_scores,
   # documents          = TEST_DOCUMENTS,

    start_model_number   = 0,
    max_num_models       = 20,
    one_model_num_topics = ONE_MODEL_NUM_TOPICS,  # 100,
    num_fit_iterations   = NUM_ITERATIONS,  # 100,  # 100 should be enough;
                                 # however, for big data better to reduce this one
                                 # (otherwise the process will be too slow)

    topic_score_threshold_percentile = 90,

    save_bank         = True,
    save_model_topics = True,
    save_file_path    = SEARCH_RESULT_FILE_PATH,
    bank_folder_path  = BANK_FOLDER_PATH,

    train_funcs = TRAIN_FUNCS,
    
    verbose = True,
)

# TODO: use Holdout Perplexity as Stop score

In [48]:
optimizer._result.keys()

dict_keys(['optimum', 'optimum_std', 'bank_scores', 'bank_topic_scores', 'model_scores', 'model_topic_scores', 'num_bank_topics', 'num_model_topics'])

Checking file paths

In [49]:
! echo $DATASET_INTERNALS_FOLDER_PATH
! ls $DATASET_INTERNALS_FOLDER_PATH

./RTL_Wiki_Person__internals
batches  dict.dict  result  result2  result_50	vw.txt

In [50]:
optimizer._save_file_path

'./RTL_Wiki_Person__internals/result_50/search_result__0.json'

In [51]:
optimizer._topic_bank._path

'./RTL_Wiki_Person__internals/result_50/bank__0'

Fulfilling the search (get ready for a really long process!):

In [52]:
%%time

optimizer.search_for_optimum(DATASET)

  0%|                                                        | 0/20 [00:00<?, ?it/s]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.86it/s]

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 23878.166015625, 'coherence_20': 1.229698071524603, 'diversity_euclidean': 0.0582555565105075, 'diversity_jensenshannon': 0.6403552575649625, 'diversity_hellinger': 0.74680146288752, 'diversity_cosine': 0.8519951977197273, 'perplexity': 23878.166015625, 'ppl_fair': 23878.166015625, 'ppl_cheatty': 6565.55517578125}
  5%|██▍                                             | 1/20 [01:06<21:12, 66.95s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.56it/s]
Creating first level with 5 topics. Dictionary: artm.Dictionary(name=68b4bcd8-474f-49ce-9b78-de418b7c1481, num_entries=37739).
Copying phi for the first level. Phi shape: (37739, 5). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           )
Creating second level with 50 topics
Copying phi for the second level. Phi shape: (37739, 50). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           names=['modality', 'token'])

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 23878.166015625, 'coherence_20': 1.229698071524603, 'diversity_euclidean': 0.0582555565105075, 'diversity_jensenshannon': 0.6403552575649625, 'diversity_hellinger': 0.74680146288752, 'diversity_cosine': 0.8519951977197273, 'perplexity': 23878.166015625, 'ppl_fair': 23878.166015625, 'ppl_cheatty': 6565.55517578125}
 10%|████▊                                           | 2/20 [02:25<22:09, 73.88s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.22it/s]
Creating first level with 5 topics. Dictionary: artm.Dictionary(name=68b4bcd8-474f-49ce-9b78-de418b7c1481, num_entries=37739).
Copying phi for the first level. Phi shape: (37739, 5). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           )
Creating second level with 50 topics
Copying phi for the second level. Phi shape: (37739, 50). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           names=['modality', 'token'])

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 23878.166015625, 'coherence_20': 1.229698071524603, 'diversity_euclidean': 0.0582555565105075, 'diversity_jensenshannon': 0.6403552575649625, 'diversity_hellinger': 0.74680146288752, 'diversity_cosine': 0.8519951977197273, 'perplexity': 23878.166015625, 'ppl_fair': 23878.166015625, 'ppl_cheatty': 6565.55517578125}
 15%|███████▏                                        | 3/20 [03:51<22:30, 79.47s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.28it/s]
Creating first level with 5 topics. Dictionary: artm.Dictionary(name=68b4bcd8-474f-49ce-9b78-de418b7c1481, num_entries=37739).
Copying phi for the first level. Phi shape: (37739, 5). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           )
Creating second level with 50 topics
Copying phi for the second level. Phi shape: (37739, 50). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           names=['modality', 'token'])

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 22487.36328125, 'coherence_20': 1.1942991103310634, 'diversity_euclidean': 0.06627762974721398, 'diversity_jensenshannon': 0.6611434795460907, 'diversity_hellinger': 0.7725314181612654, 'diversity_cosine': 0.8491310464160697, 'perplexity': 22487.36328125, 'ppl_fair': 22487.36328125, 'ppl_cheatty': 6427.033203125}
 20%|█████████▌                                      | 4/20 [05:15<21:36, 81.00s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.53it/s]
Creating first level with 6 topics. Dictionary: artm.Dictionary(name=68b4bcd8-474f-49ce-9b78-de418b7c1481, num_entries=37739).
Copying phi for the first level. Phi shape: (37739, 6). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           )
Creating second level with 50 topics
Copying phi for the second level. Phi shape: (37739, 50). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           names=['modality', 'token'])

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 22487.36328125, 'coherence_20': 1.1942991103310634, 'diversity_euclidean': 0.06627762974721398, 'diversity_jensenshannon': 0.6611434795460907, 'diversity_hellinger': 0.7725314181612654, 'diversity_cosine': 0.8491310464160697, 'perplexity': 22487.36328125, 'ppl_fair': 22487.36328125, 'ppl_cheatty': 6427.033203125}
 25%|████████████                                    | 5/20 [06:33<20:02, 80.16s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.53it/s]
Creating first level with 6 topics. Dictionary: artm.Dictionary(name=68b4bcd8-474f-49ce-9b78-de418b7c1481, num_entries=37739).
Copying phi for the first level. Phi shape: (37739, 6). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           )
Creating second level with 50 topics
Copying phi for the second level. Phi shape: (37739, 50). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           names=['modality', 'token'])

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 19128.2890625, 'coherence_20': 1.151999215668335, 'diversity_euclidean': 0.0675270493926133, 'diversity_jensenshannon': 0.6725448126230565, 'diversity_hellinger': 0.7855662025219016, 'diversity_cosine': 0.8670391618163544, 'perplexity': 19128.2890625, 'ppl_fair': 19128.2890625, 'ppl_cheatty': 6197.19140625}
 30%|██████████████▍                                 | 6/20 [07:54<18:43, 80.24s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.51it/s]
Creating first level with 7 topics. Dictionary: artm.Dictionary(name=68b4bcd8-474f-49ce-9b78-de418b7c1481, num_entries=37739).
Copying phi for the first level. Phi shape: (37739, 7). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           )
Creating second level with 50 topics
Copying phi for the second level. Phi shape: (37739, 50). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           names=['modality', 'token'])

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 19128.2890625, 'coherence_20': 1.151999215668335, 'diversity_euclidean': 0.0675270493926133, 'diversity_jensenshannon': 0.6725448126230565, 'diversity_hellinger': 0.7855662025219016, 'diversity_cosine': 0.8670391618163544, 'perplexity': 19128.2890625, 'ppl_fair': 19128.2890625, 'ppl_cheatty': 6197.19140625}
 35%|████████████████▊                               | 7/20 [09:13<17:20, 80.01s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.53it/s]
Creating first level with 7 topics. Dictionary: artm.Dictionary(name=68b4bcd8-474f-49ce-9b78-de418b7c1481, num_entries=37739).
Copying phi for the first level. Phi shape: (37739, 7). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           )
Creating second level with 50 topics
Copying phi for the second level. Phi shape: (37739, 50). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           names=['modality', 'token'])

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 19128.2890625, 'coherence_20': 1.151999215668335, 'diversity_euclidean': 0.0675270493926133, 'diversity_jensenshannon': 0.6725448126230565, 'diversity_hellinger': 0.7855662025219016, 'diversity_cosine': 0.8670391618163544, 'perplexity': 19128.2890625, 'ppl_fair': 19128.2890625, 'ppl_cheatty': 6197.19140625}
 40%|███████████████████▏                            | 8/20 [10:35<16:06, 80.50s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.28it/s]
Creating first level with 7 topics. Dictionary: artm.Dictionary(name=68b4bcd8-474f-49ce-9b78-de418b7c1481, num_entries=37739).
Copying phi for the first level. Phi shape: (37739, 7). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           )
Creating second level with 50 topics
Copying phi for the second level. Phi shape: (37739, 50). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           names=['modality', 'token'])

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 19128.2890625, 'coherence_20': 1.151999215668335, 'diversity_euclidean': 0.0675270493926133, 'diversity_jensenshannon': 0.6725448126230565, 'diversity_hellinger': 0.7855662025219016, 'diversity_cosine': 0.8670391618163544, 'perplexity': 19128.2890625, 'ppl_fair': 19128.2890625, 'ppl_cheatty': 6197.19140625}
 45%|█████████████████████▌                          | 9/20 [12:05<15:19, 83.64s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.25it/s]
Creating first level with 7 topics. Dictionary: artm.Dictionary(name=68b4bcd8-474f-49ce-9b78-de418b7c1481, num_entries=37739).
Copying phi for the first level. Phi shape: (37739, 7). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           )
Creating second level with 50 topics
Copying phi for the second level. Phi shape: (37739, 50). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           names=['modality', 'token'])

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 19128.2890625, 'coherence_20': 1.151999215668335, 'diversity_euclidean': 0.0675270493926133, 'diversity_jensenshannon': 0.6725448126230565, 'diversity_hellinger': 0.7855662025219016, 'diversity_cosine': 0.8670391618163544, 'perplexity': 19128.2890625, 'ppl_fair': 19128.2890625, 'ppl_cheatty': 6197.19140625}
 50%|███████████████████████▌                       | 10/20 [13:35<14:15, 85.56s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.29it/s]
Creating first level with 7 topics. Dictionary: artm.Dictionary(name=68b4bcd8-474f-49ce-9b78-de418b7c1481, num_entries=37739).
Copying phi for the first level. Phi shape: (37739, 7). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           )
Creating second level with 50 topics
Copying phi for the second level. Phi shape: (37739, 50). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           names=['modality', 'token'])

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 19128.2890625, 'coherence_20': 1.151999215668335, 'diversity_euclidean': 0.0675270493926133, 'diversity_jensenshannon': 0.6725448126230565, 'diversity_hellinger': 0.7855662025219016, 'diversity_cosine': 0.8670391618163544, 'perplexity': 19128.2890625, 'ppl_fair': 19128.2890625, 'ppl_cheatty': 6197.19140625}
 55%|█████████████████████████▊                     | 11/20 [14:59<12:44, 84.97s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.56it/s]
Creating first level with 7 topics. Dictionary: artm.Dictionary(name=68b4bcd8-474f-49ce-9b78-de418b7c1481, num_entries=37739).
Copying phi for the first level. Phi shape: (37739, 7). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           )
Creating second level with 50 topics
Copying phi for the second level. Phi shape: (37739, 50). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           names=['modality', 'token'])

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 19128.2890625, 'coherence_20': 1.151999215668335, 'diversity_euclidean': 0.0675270493926133, 'diversity_jensenshannon': 0.6725448126230565, 'diversity_hellinger': 0.7855662025219016, 'diversity_cosine': 0.8670391618163544, 'perplexity': 19128.2890625, 'ppl_fair': 19128.2890625, 'ppl_cheatty': 6197.19140625}
 60%|████████████████████████████▏                  | 12/20 [16:18<11:04, 83.10s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.44it/s]
Creating first level with 7 topics. Dictionary: artm.Dictionary(name=68b4bcd8-474f-49ce-9b78-de418b7c1481, num_entries=37739).
Copying phi for the first level. Phi shape: (37739, 7). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           )
Creating second level with 50 topics
Copying phi for the second level. Phi shape: (37739, 50). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           names=['modality', 'token'])

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 19128.2890625, 'coherence_20': 1.151999215668335, 'diversity_euclidean': 0.0675270493926133, 'diversity_jensenshannon': 0.6725448126230565, 'diversity_hellinger': 0.7855662025219016, 'diversity_cosine': 0.8670391618163544, 'perplexity': 19128.2890625, 'ppl_fair': 19128.2890625, 'ppl_cheatty': 6197.19140625}
 65%|██████████████████████████████▌                | 13/20 [17:37<09:33, 81.88s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.55it/s]
Creating first level with 7 topics. Dictionary: artm.Dictionary(name=68b4bcd8-474f-49ce-9b78-de418b7c1481, num_entries=37739).
Copying phi for the first level. Phi shape: (37739, 7). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           )
Creating second level with 50 topics
Copying phi for the second level. Phi shape: (37739, 50). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           names=['modality', 'token'])

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 19128.2890625, 'coherence_20': 1.151999215668335, 'diversity_euclidean': 0.0675270493926133, 'diversity_jensenshannon': 0.6725448126230565, 'diversity_hellinger': 0.7855662025219016, 'diversity_cosine': 0.8670391618163544, 'perplexity': 19128.2890625, 'ppl_fair': 19128.2890625, 'ppl_cheatty': 6197.19140625}
 70%|████████████████████████████████▉              | 14/20 [18:55<08:05, 80.88s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.57it/s]
Creating first level with 7 topics. Dictionary: artm.Dictionary(name=68b4bcd8-474f-49ce-9b78-de418b7c1481, num_entries=37739).
Copying phi for the first level. Phi shape: (37739, 7). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           )
Creating second level with 50 topics
Copying phi for the second level. Phi shape: (37739, 50). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           names=['modality', 'token'])

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 19128.2890625, 'coherence_20': 1.151999215668335, 'diversity_euclidean': 0.0675270493926133, 'diversity_jensenshannon': 0.6725448126230565, 'diversity_hellinger': 0.7855662025219016, 'diversity_cosine': 0.8670391618163544, 'perplexity': 19128.2890625, 'ppl_fair': 19128.2890625, 'ppl_cheatty': 6197.19140625}
 75%|███████████████████████████████████▎           | 15/20 [20:14<06:40, 80.20s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.54it/s]
Creating first level with 7 topics. Dictionary: artm.Dictionary(name=68b4bcd8-474f-49ce-9b78-de418b7c1481, num_entries=37739).
Copying phi for the first level. Phi shape: (37739, 7). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           )
Creating second level with 50 topics
Copying phi for the second level. Phi shape: (37739, 50). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           names=['modality', 'token'])

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 19128.2890625, 'coherence_20': 1.151999215668335, 'diversity_euclidean': 0.0675270493926133, 'diversity_jensenshannon': 0.6725448126230565, 'diversity_hellinger': 0.7855662025219016, 'diversity_cosine': 0.8670391618163544, 'perplexity': 19128.2890625, 'ppl_fair': 19128.2890625, 'ppl_cheatty': 6197.19140625}
 80%|█████████████████████████████████████▌         | 16/20 [21:33<05:18, 79.72s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.55it/s]
Creating first level with 7 topics. Dictionary: artm.Dictionary(name=68b4bcd8-474f-49ce-9b78-de418b7c1481, num_entries=37739).
Copying phi for the first level. Phi shape: (37739, 7). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           )
Creating second level with 50 topics
Copying phi for the second level. Phi shape: (37739, 50). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           names=['modality', 'token'])

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 19128.2890625, 'coherence_20': 1.151999215668335, 'diversity_euclidean': 0.0675270493926133, 'diversity_jensenshannon': 0.6725448126230565, 'diversity_hellinger': 0.7855662025219016, 'diversity_cosine': 0.8670391618163544, 'perplexity': 19128.2890625, 'ppl_fair': 19128.2890625, 'ppl_cheatty': 6197.19140625}
 85%|███████████████████████████████████████▉       | 17/20 [22:51<03:57, 79.31s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.55it/s]
Creating first level with 7 topics. Dictionary: artm.Dictionary(name=68b4bcd8-474f-49ce-9b78-de418b7c1481, num_entries=37739).
Copying phi for the first level. Phi shape: (37739, 7). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           )
Creating second level with 50 topics
Copying phi for the second level. Phi shape: (37739, 50). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           names=['modality', 'token'])

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 19128.2890625, 'coherence_20': 1.151999215668335, 'diversity_euclidean': 0.0675270493926133, 'diversity_jensenshannon': 0.6725448126230565, 'diversity_hellinger': 0.7855662025219016, 'diversity_cosine': 0.8670391618163544, 'perplexity': 19128.2890625, 'ppl_fair': 19128.2890625, 'ppl_cheatty': 6197.19140625}
 90%|██████████████████████████████████████████▎    | 18/20 [24:16<02:41, 80.94s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.30it/s]
Creating first level with 7 topics. Dictionary: artm.Dictionary(name=68b4bcd8-474f-49ce-9b78-de418b7c1481, num_entries=37739).
Copying phi for the first level. Phi shape: (37739, 7). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           )
Creating second level with 50 topics
Copying phi for the second level. Phi shape: (37739, 50). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           names=['modality', 'token'])

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 19128.2890625, 'coherence_20': 1.151999215668335, 'diversity_euclidean': 0.0675270493926133, 'diversity_jensenshannon': 0.6725448126230565, 'diversity_hellinger': 0.7855662025219016, 'diversity_cosine': 0.8670391618163544, 'perplexity': 19128.2890625, 'ppl_fair': 19128.2890625, 'ppl_cheatty': 6197.19140625}
 95%|████████████████████████████████████████████▋  | 19/20 [25:45<01:23, 83.50s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.54it/s]
Creating first level with 7 topics. Dictionary: artm.Dictionary(name=68b4bcd8-474f-49ce-9b78-de418b7c1481, num_entries=37739).
Copying phi for the first level. Phi shape: (37739, 7). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           )
Creating second level with 50 topics
Copying phi for the second level. Phi shape: (37739, 50). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           names=['modality', 'token'])

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 17225.158203125, 'coherence_20': 1.1539726713344447, 'diversity_euclidean': 0.06532281912944632, 'diversity_jensenshannon': 0.6669165021161831, 'diversity_hellinger': 0.7783840409048797, 'diversity_cosine': 0.8626256927229845, 'perplexity': 17225.158203125, 'ppl_fair': 17225.158203125, 'ppl_cheatty': 6089.13037109375}
100%|███████████████████████████████████████████████| 20/20 [27:07<00:00, 81.39s/it]
CPU times: user 31min 11s, sys: 56.2 s, total: 32min 7s
Wall time: 27min 7s

What topics we have in bank

In [53]:
optimizer._topic_bank.view_topics().head()

                           topic_0  topic_1  topic_2  topic_3  topic_4  \
@lemmatized hazardous          0.0      0.0      0.0      0.0      0.0
            expostulation      0.0      0.0      0.0      0.0      0.0
            hearse             0.0      0.0      0.0      0.0      0.0
            valkyrie           0.0      0.0      0.0      0.0      0.0
            sagebrush          0.0      0.0      0.0      0.0      0.0

                           topic_5  topic_6  topic_7
@lemmatized hazardous          0.0      0.0      0.0
            expostulation      0.0      0.0      0.0
            hearse             0.0      0.0      0.0
            valkyrie           0.0      0.0      0.0
            sagebrush          0.0      0.0      0.0

In [54]:
bank_topics = optimizer._topic_bank.view_topics()

In [55]:
bank_topics.shape

(37739, 8)

In [56]:
bank_topics.head()

                           topic_0  topic_1  topic_2  topic_3  topic_4  \
@lemmatized hazardous          0.0      0.0      0.0      0.0      0.0
            expostulation      0.0      0.0      0.0      0.0      0.0
            hearse             0.0      0.0      0.0      0.0      0.0
            valkyrie           0.0      0.0      0.0      0.0      0.0
            sagebrush          0.0      0.0      0.0      0.0      0.0

                           topic_5  topic_6  topic_7
@lemmatized hazardous          0.0      0.0      0.0
            expostulation      0.0      0.0      0.0
            hearse             0.0      0.0      0.0
            valkyrie           0.0      0.0      0.0
            sagebrush          0.0      0.0      0.0

In [57]:
bank_topics['topic_0'].sort_values(ascending=False)[:20]

@lemmatized  constantine    0.017840
             roman          0.013013
             emperor        0.012049
             empire         0.008822
             augustus       0.007161
             diocletian     0.006886
             p              0.006624
             rome           0.006320
             barnes         0.006038
             julian         0.006024
             eusebius       0.005116
             reign          0.004948
             domitian       0.004876
             constantius    0.004788
             christian      0.004071
             army           0.003807
             hadrian        0.003765
             justinian      0.003478
             city           0.003428
             military       0.003293
Name: topic_0, dtype: float64

And topic scores

In [58]:
optimizer._topic_bank.view_topic_scores()

,topic_0,topic_1,topic_2,topic_3,topic_4,topic_5,topic_6,topic_7
kernel_size,4118.000000,4699.000000,4803.000000,5443.000000,5565.000000,2541.000000,4029.000000,4762.000000
coherence_20,1.131275,1.083500,1.043963,1.088446,1.801306,1.017304,0.898200,1.167787
distance_to_nearest,0.000000,0.874184,0.788165,0.841812,0.710506,0.866538,0.877169,0.805760

All models are also saved (topics as $\Phi$ matrices and topic score values)

In [59]:
! ls $optimizer._topic_bank._path

model_0__phi.bin	    model_19__topic_scores.bin
model_0__topic_scores.bin   model_1__phi.bin
model_10__phi.bin	    model_1__topic_scores.bin
model_10__topic_scores.bin  model_2__phi.bin
model_11__phi.bin	    model_2__topic_scores.bin
model_11__topic_scores.bin  model_3__phi.bin
model_12__phi.bin	    model_3__topic_scores.bin
model_12__topic_scores.bin  model_4__phi.bin
model_13__phi.bin	    model_4__topic_scores.bin
model_13__topic_scores.bin  model_5__phi.bin
model_14__phi.bin	    model_5__topic_scores.bin
model_14__topic_scores.bin  model_6__phi.bin
model_15__phi.bin	    model_6__topic_scores.bin
model_15__topic_scores.bin  model_7__phi.bin
model_16__phi.bin	    model_7__topic_scores.bin
model_16__topic_scores.bin  model_8__phi.bin
model_17__phi.bin	    model_8__topic_scores.bin
model_17__topic_scores.bin  model_9__phi.bin
model_18__phi.bin	    model_9__topic_scores.bin
model_18__topic_scores.bin  topics.bin
model_19__phi.bin	    topic_scores.bin

In [60]:
optimizer._result.keys()

dict_keys(['optimum', 'optimum_std', 'bank_scores', 'bank_topic_scores', 'model_scores', 'model_topic_scores', 'num_bank_topics', 'num_model_topics'])

In [61]:
optimizer._result['num_bank_topics']

[5, 5, 5, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 8]

In [62]:
len(optimizer._result['bank_topic_scores'])

20

In [63]:
import artm
from topnum.model_constructor import KnownModel, init_plsa
from topicnet.cooking_machine.rel_toolbox_lite import (
    count_vocab_size,
    transform_regularizer,
)
from topicnet.cooking_machine.model_constructor import (
    add_standard_scores,
    create_default_topics,
    init_model,
)

def init_model_from_family(
        family: str or KnownModel,
        dataset: Dataset,
        main_modality: str,
        num_topics: int,
        seed: int,
        specific_topic_names = None,
        modalities_to_use: List[str] = None,
        num_processors: int = 3,
        model_params: dict = None,
):
    """
    Returns
    -------
    model: TopicModel() instance
    """
    if isinstance(family, KnownModel):
        family = family.value

    if modalities_to_use is None:
        modalities_to_use = [main_modality]

    custom_regs = {}

    if family == "LDA":
        model = init_lda(
            dataset, modalities_to_use, main_modality, num_topics, model_params
        )
    elif family == "PLSA":
        model = init_plsa(
            dataset, modalities_to_use, main_modality, num_topics
        )
    elif family == "TARTM":
        model, custom_regs = init_thetaless(
            dataset, modalities_to_use, main_modality, num_topics, model_params
        )
    elif family == "sparse":
        model = init_bcg_sparse_model(
            dataset, modalities_to_use, main_modality, num_topics, 1, model_params
        )
    elif family == "decorrelation":
        model = init_decorrelated_plsa(
            dataset, modalities_to_use, main_modality, num_topics, model_params
        )
    elif family == "ARTM":
        model = init_baseline_artm(
            dataset, modalities_to_use, main_modality, num_topics, 1, specific_topic_names, model_params
        )
    else:
        raise ValueError(f'family: {family}')

    model.num_processors = num_processors

    if seed is not None:
        model.seed = seed

    dictionary = dataset.get_dictionary()

    # TODO: maybe this cycle is not necessary
    for modality in dataset.get_possible_modalities():
        if modality not in modalities_to_use:
            dictionary.filter(class_id=modality, max_df=0, inplace=True)

    model.initialize(dictionary)
    add_standard_scores(model, dictionary, main_modality=main_modality,
                        all_modalities=modalities_to_use)

    model = TopicModel(
        artm_model=model,
        custom_regularizers=custom_regs
    )
    model.has_bcg = True  # TODO: only if init_bcg_sparse_model

    return model


def init_bcg_sparse_model(
        dataset,
        modalities_to_use,
        main_modality,
        specific_topics,
        bcg_topics,
        specific_topic_names = None,
        model_params: dict = None
):
    """
    Creates simple artm model with standard scores.

    Parameters
    ----------
    dataset : Dataset
    modalities_to_use : list of str or dict
    main_modality : str
    specific_topics : int
    bcg_topics : int

    Returns
    -------
    model: artm.ARTM() instance
    """
    if model_params is None:
        model_params = dict()

    model = init_plsa(
        dataset, modalities_to_use, main_modality, specific_topics, bcg_topics
    )
    background_topic_names = model.topic_names[-bcg_topics:]

    if specific_topic_names is None:
        print('No spec topics')
        specific_topic_names = model.topic_names[:-bcg_topics]

    dictionary = dataset.get_dictionary()
    baseline_class_ids = {class_id: 1 for class_id in modalities_to_use}
    data_stats = count_vocab_size(dictionary, baseline_class_ids)

    # all coefficients are relative
    regularizers = [
        artm.SmoothSparsePhiRegularizer(
             name='smooth_phi_bcg',
             topic_names=background_topic_names,
             tau=model_params.get("smooth_bcg_tau", 0.1),
             class_ids=[main_modality],
        ),
        artm.SmoothSparseThetaRegularizer(
             name='smooth_theta_bcg',
             topic_names=background_topic_names,
             tau=model_params.get("smooth_bcg_tau", 0.1),
        ),
        artm.SmoothSparsePhiRegularizer(
             name='sparse_phi_sp',
             topic_names=specific_topic_names,
             tau=model_params.get("sparse_sp_tau", -0.05),
             class_ids=[main_modality],
            ),
        artm.SmoothSparseThetaRegularizer(
             name='sparse_theta_sp',
             topic_names=specific_topic_names,
             tau=model_params.get("sparse_sp_tau", -0.05),
        ),
    ]
    for reg in regularizers:
        model.regularizers.add(transform_regularizer(
            data_stats,
            reg,
            model.class_ids,
            n_topics=len(reg.topic_names)
        ))

    return model


def init_baseline_artm(
        dataset,
        modalities_to_use,
        main_modality,
        num_topics,
        bcg_topics,
        specific_topic_names = None,
        model_params: dict = None,
):
    """
    Creates simple artm model with standard scores.

    Parameters
    ----------
    dataset : Dataset
    modalities_to_use : list of str
    main_modality : str
    num_topics : int

    Returns
    -------
    model: artm.ARTM() instance
    """
    if model_params is None:
        model_params = dict()

    model = init_bcg_sparse_model(
        dataset, modalities_to_use, main_modality, num_topics, bcg_topics, specific_topic_names, model_params
    )

    if specific_topic_names is None:
        print('No spec topics')
        specific_topic_names = model.topic_names[:-bcg_topics]

    model.regularizers.add(
        artm.DecorrelatorPhiRegularizer(
            gamma=0,
            tau=model_params.get('decorrelation_tau', 0.01),
            name='decorrelation',
            topic_names=specific_topic_names,
            class_ids=modalities_to_use,
        )
    )

    return model

In [64]:
def artm_train_func(
        dataset: Dataset,
        model_number: int,
        num_topics: int,
        num_fit_iterations: int,
        scores: List = None,
        **kwargs) -> TopicModel:
    """

    Additional Parameters
    ---------------------
    kwargs
        Some params for `_get_topic_model`, such as `cache_theta` and `num_processors`
    """

    topic_model = init_model_from_family(
        family='ARTM',
        dataset=DATASET,
        main_modality=MAIN_MODALITY,
        num_topics=ONE_MODEL_NUM_TOPICS,
        seed=model_number,
        model_params={
            'decorrelation_tau': 0.01,  # best values
            'smooth_bcg_tau': 0.05,
            'sparse_sp_tau': -0.05,
        }
    )

    num_fit_iterations_with_scores = 1

    topic_model._fit(
        dataset.get_batch_vectorizer(),
        num_iterations=max(0, num_fit_iterations - num_fit_iterations_with_scores)
    )
    _fit_model_with_scores(
        topic_model,
        DATASET,
        scores,
        num_fit_iterations=num_fit_iterations_with_scores
    )

    return topic_model


def _fit_model_with_scores(
        topic_model: TopicModel,
        dataset: Dataset,
        scores: List = None,
        num_fit_iterations: int = 1):

    if scores is not None:
        for score in scores:
            score._attach(topic_model)

    topic_model._fit(
        dataset.get_batch_vectorizer(),
        num_iterations=num_fit_iterations
    )

### Bank Creation<a id="bank-creation"></a>

<div style="text-align: right">Back to <a href=#contents>Contents</a></div>

Here we finally run the experiment!

In [65]:
NUM_ITERATIONS = 20

In [66]:
seed = 0

In [67]:
# We use only one train function here
# Other variations are also possible
# It would be even better to make bank using several train functions
# However, it would also take way more time 

TRAIN_FUNCS = artm_train_func  # default train func

In [68]:
DATASET_INTERNALS_FOLDER_PATH

'./RTL_Wiki_Person__internals'

In [69]:
SEARCH_RESULTS_FOLDER_PATH = os.path.join(
    DATASET_INTERNALS_FOLDER_PATH, 'result2_50'
)

# File with some info about the process
SEARCH_RESULT_FILE_PATH = os.path.join(
    SEARCH_RESULTS_FOLDER_PATH, f'search_result__{seed}.json'
)

# Bank, with topics and their score values
BANK_FOLDER_PATH = os.path.join(
    SEARCH_RESULTS_FOLDER_PATH, f'bank__{seed}'
)

In [70]:
SEARCH_RESULTS_FOLDER_PATH

'./RTL_Wiki_Person__internals/result2_50'

! rm -r $SEARCH_RESULTS_FOLDER_PATH

In [71]:
BANK_FOLDER_PATH

'./RTL_Wiki_Person__internals/result2_50/bank__0'

In [72]:
os.makedirs(SEARCH_RESULTS_FOLDER_PATH, exist_ok=True)
os.makedirs(BANK_FOLDER_PATH, exist_ok=True)

In [73]:
seed

0

One cay vary some parameters below (for example `max_num_models` and `num_fit_iterations`).

In [74]:
optimizer = TopicBankMethod(
    data        = DATASET,
    main_modality = MAIN_MODALITY,
    
    min_df_rate = 0.0,  # dictionary filtering has already been done little earlier
    max_df_rate = 1.0,  #   so we don't want these parameters to have any effect

    main_topic_score   = coherence_score,
    other_topic_scores = [],
    other_scores       = [coherence_score] + diversity_scores + other_scores,
   # documents          = TEST_DOCUMENTS,

    start_model_number   = 0,
    max_num_models       = 20,
    one_model_num_topics = ONE_MODEL_NUM_TOPICS,  # 100,
    num_fit_iterations   = NUM_ITERATIONS,  # 100,  # 100 should be enough;
                                 # however, for big data better to reduce this one
                                 # (otherwise the process will be too slow)

    topic_score_threshold_percentile = 0.7938587462014927,  # DIFF ALSO HERE

    save_bank         = True,
    save_model_topics = True,
    save_file_path    = SEARCH_RESULT_FILE_PATH,
    bank_folder_path  = BANK_FOLDER_PATH,

    train_funcs = TRAIN_FUNCS,
    
    verbose = True,
)

# TODO: use Holdout Perplexity as Stop score

/home/alekseev_v/projects/iterative/../OptimalNumberOfTopics/topnum/search_methods/topic_bank/topic_bank_method.py:208: UserWarning: topic_score_threshold_percentile 0.7938587462014927 is less than one! It is expected to be in [0, 100]. Are you sure you want to proceed (yes/no)?
  warnings.warn(

In [75]:
optimizer._result.keys()

dict_keys(['optimum', 'optimum_std', 'bank_scores', 'bank_topic_scores', 'model_scores', 'model_topic_scores', 'num_bank_topics', 'num_model_topics'])

Checking file paths

In [76]:
! ls ./Post_Science__internals

batches    _result  _result2  result2_50  result_unfiltered_dict
dict.dict  result   result2   result_50   vw.txt

In [77]:
optimizer._save_file_path

'./RTL_Wiki_Person__internals/result2_50/search_result__0.json'

In [78]:
optimizer._topic_bank._path

'./RTL_Wiki_Person__internals/result2_50/bank__0'

Fulfilling the search (get ready for a really long process!):

In [79]:
%%time

optimizer.search_for_optimum(DATASET)

  0%|                                                        | 0/20 [00:00<?, ?it/s]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/1 [00:00<?, ?it/s]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.85it/s]
Using absoulte threshold: 0.7938587462014927.
Skipping saving scores for bcg topic

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 16077.958984375, 'coherence_20': 1.1225033344850237, 'diversity_euclidean': 0.06877371410525385, 'diversity_jensenshannon': 0.687365105375971, 'diversity_hellinger': 0.804517438601834, 'diversity_cosine': 0.8903542350272428, 'perplexity': 16077.958984375, 'ppl_fair': 16077.958984375, 'ppl_cheatty': 5728.96484375}
  5%|██▎                                            | 1/20 [01:42<32:29, 102.60s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/1 [00:00<?, ?it/s]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.04it/s]
Using absoulte threshold: 0.7938587462014927.
Creating first level with 11 topics. Dictionary: artm.Dictionary(name=68b4bcd8-474f-49ce-9b78-de418b7c1481, num_entries=37739).
Copying phi for the first level. Phi shape: (37739, 11). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           )
Creating second level with 51 topics
Copying phi for the second level. Phi shape: (37739, 51). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 16077.958984375, 'coherence_20': 1.1225033344850237, 'diversity_euclidean': 0.06877371410525385, 'diversity_jensenshannon': 0.687365105375971, 'diversity_hellinger': 0.804517438601834, 'diversity_cosine': 0.8903542350272428, 'perplexity': 16077.958984375, 'ppl_fair': 16077.958984375, 'ppl_cheatty': 5728.96484375}
 10%|████▊                                           | 2/20 [03:20<29:52, 99.56s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/1 [00:00<?, ?it/s]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.86it/s]
Using absoulte threshold: 0.7938587462014927.
Creating first level with 11 topics. Dictionary: artm.Dictionary(name=68b4bcd8-474f-49ce-9b78-de418b7c1481, num_entries=37739).
Copying phi for the first level. Phi shape: (37739, 11). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           )
Creating second level with 51 topics
Copying phi for the second level. Phi shape: (37739, 51). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 16077.958984375, 'coherence_20': 1.1225033344850237, 'diversity_euclidean': 0.06877371410525385, 'diversity_jensenshannon': 0.687365105375971, 'diversity_hellinger': 0.804517438601834, 'diversity_cosine': 0.8903542350272428, 'perplexity': 16077.958984375, 'ppl_fair': 16077.958984375, 'ppl_cheatty': 5728.96484375}
 15%|███████▏                                        | 3/20 [05:00<28:18, 99.89s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/1 [00:00<?, ?it/s]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.76it/s]
Using absoulte threshold: 0.7938587462014927.
Creating first level with 11 topics. Dictionary: artm.Dictionary(name=68b4bcd8-474f-49ce-9b78-de418b7c1481, num_entries=37739).
Copying phi for the first level. Phi shape: (37739, 11). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           )
Creating second level with 51 topics
Copying phi for the second level. Phi shape: (37739, 51). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 15295.3505859375, 'coherence_20': 1.0913945267901033, 'diversity_euclidean': 0.07303163833524239, 'diversity_jensenshannon': 0.6930954661913941, 'diversity_hellinger': 0.811946775922991, 'diversity_cosine': 0.8920698213991594, 'perplexity': 15295.3505859375, 'ppl_fair': 15295.3505859375, 'ppl_cheatty': 5617.498046875}
 20%|█████████▍                                     | 4/20 [06:58<28:33, 107.12s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/1 [00:00<?, ?it/s]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.78it/s]
Using absoulte threshold: 0.7938587462014927.
Creating first level with 12 topics. Dictionary: artm.Dictionary(name=68b4bcd8-474f-49ce-9b78-de418b7c1481, num_entries=37739).
Copying phi for the first level. Phi shape: (37739, 12). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           )
Creating second level with 51 topics
Copying phi for the second level. Phi shape: (37739, 51). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 13889.2333984375, 'coherence_20': 1.0743054059557282, 'diversity_euclidean': 0.0728672063689704, 'diversity_jensenshannon': 0.6914875281605614, 'diversity_hellinger': 0.8100414254153561, 'diversity_cosine': 0.8938906715015421, 'perplexity': 13889.2333984375, 'ppl_fair': 13889.2333984375, 'ppl_cheatty': 5508.8828125}
 25%|███████████▊                                   | 5/20 [08:40<26:19, 105.28s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/1 [00:00<?, ?it/s]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.05it/s]
Using absoulte threshold: 0.7938587462014927.
Creating first level with 13 topics. Dictionary: artm.Dictionary(name=68b4bcd8-474f-49ce-9b78-de418b7c1481, num_entries=37739).
Copying phi for the first level. Phi shape: (37739, 13). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           )
Creating second level with 51 topics
Copying phi for the second level. Phi shape: (37739, 51). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 12954.525390625, 'coherence_20': 1.0723075319803936, 'diversity_euclidean': 0.06917390259235667, 'diversity_jensenshannon': 0.6780474555774554, 'diversity_hellinger': 0.7933355700885665, 'diversity_cosine': 0.8746197119999312, 'perplexity': 12954.525390625, 'ppl_fair': 12954.525390625, 'ppl_cheatty': 5444.82177734375}
 30%|██████████████                                 | 6/20 [10:40<25:45, 110.38s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/1 [00:00<?, ?it/s]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.79it/s]
Using absoulte threshold: 0.7938587462014927.
Creating first level with 14 topics. Dictionary: artm.Dictionary(name=68b4bcd8-474f-49ce-9b78-de418b7c1481, num_entries=37739).
Copying phi for the first level. Phi shape: (37739, 14). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           )
Creating second level with 51 topics
Copying phi for the second level. Phi shape: (37739, 51). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 12954.525390625, 'coherence_20': 1.0723075319803936, 'diversity_euclidean': 0.06917390259235667, 'diversity_jensenshannon': 0.6780474555774554, 'diversity_hellinger': 0.7933355700885665, 'diversity_cosine': 0.8746197119999312, 'perplexity': 12954.525390625, 'ppl_fair': 12954.525390625, 'ppl_cheatty': 5444.82177734375}
 35%|████████████████▍                              | 7/20 [12:35<24:13, 111.77s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/1 [00:00<?, ?it/s]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.04it/s]
Using absoulte threshold: 0.7938587462014927.
Creating first level with 14 topics. Dictionary: artm.Dictionary(name=68b4bcd8-474f-49ce-9b78-de418b7c1481, num_entries=37739).
Copying phi for the first level. Phi shape: (37739, 14). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           )
Creating second level with 51 topics
Copying phi for the second level. Phi shape: (37739, 51). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 13016.353515625, 'coherence_20': 1.1044389832629495, 'diversity_euclidean': 0.0696202510374661, 'diversity_jensenshannon': 0.6796310563559566, 'diversity_hellinger': 0.7955621724209297, 'diversity_cosine': 0.8753912467258014, 'perplexity': 13016.353515625, 'ppl_fair': 13016.353515625, 'ppl_cheatty': 5490.9599609375}
 40%|██████████████████▊                            | 8/20 [14:21<22:00, 110.04s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/1 [00:00<?, ?it/s]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.03it/s]
Using absoulte threshold: 0.7938587462014927.
Creating first level with 14 topics. Dictionary: artm.Dictionary(name=68b4bcd8-474f-49ce-9b78-de418b7c1481, num_entries=37739).
Copying phi for the first level. Phi shape: (37739, 14). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           )
Creating second level with 51 topics
Copying phi for the second level. Phi shape: (37739, 51). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 13206.0322265625, 'coherence_20': 1.1583876240487163, 'diversity_euclidean': 0.07096431241664203, 'diversity_jensenshannon': 0.6780154043843674, 'diversity_hellinger': 0.7943798148347189, 'diversity_cosine': 0.8746746129180473, 'perplexity': 13206.0322265625, 'ppl_fair': 13206.0322265625, 'ppl_cheatty': 5527.9228515625}
 45%|█████████████████████▏                         | 9/20 [16:08<20:00, 109.14s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/1 [00:00<?, ?it/s]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.03it/s]
Using absoulte threshold: 0.7938587462014927.
Creating first level with 14 topics. Dictionary: artm.Dictionary(name=68b4bcd8-474f-49ce-9b78-de418b7c1481, num_entries=37739).
Copying phi for the first level. Phi shape: (37739, 14). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           )
Creating second level with 51 topics
Copying phi for the second level. Phi shape: (37739, 51). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 12344.1923828125, 'coherence_20': 1.1434658612491186, 'diversity_euclidean': 0.07173208026707717, 'diversity_jensenshannon': 0.684750209300096, 'diversity_hellinger': 0.8026135056875996, 'diversity_cosine': 0.8810206585783182, 'perplexity': 12344.1923828125, 'ppl_fair': 12344.1923828125, 'ppl_cheatty': 5403.87451171875}
 50%|███████████████████████                       | 10/20 [17:54<17:59, 107.93s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/1 [00:00<?, ?it/s]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.87it/s]
Using absoulte threshold: 0.7938587462014927.
Creating first level with 15 topics. Dictionary: artm.Dictionary(name=68b4bcd8-474f-49ce-9b78-de418b7c1481, num_entries=37739).
Copying phi for the first level. Phi shape: (37739, 15). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           )
Creating second level with 51 topics
Copying phi for the second level. Phi shape: (37739, 51). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 13745.7548828125, 'coherence_20': 1.1603842971196152, 'diversity_euclidean': 0.07057460933694086, 'diversity_jensenshannon': 0.685343850321118, 'diversity_hellinger': 0.8041030516608872, 'diversity_cosine': 0.8749020641187326, 'perplexity': 13745.7548828125, 'ppl_fair': 13745.7548828125, 'ppl_cheatty': 5540.32275390625}
 55%|█████████████████████████▎                    | 11/20 [19:53<16:42, 111.40s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/1 [00:00<?, ?it/s]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.03it/s]
Using absoulte threshold: 0.7938587462014927.
Creating first level with 16 topics. Dictionary: artm.Dictionary(name=68b4bcd8-474f-49ce-9b78-de418b7c1481, num_entries=37739).
Copying phi for the first level. Phi shape: (37739, 16). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           )
Creating second level with 51 topics
Copying phi for the second level. Phi shape: (37739, 51). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 13745.7548828125, 'coherence_20': 1.1603842971196152, 'diversity_euclidean': 0.07057460933694086, 'diversity_jensenshannon': 0.685343850321118, 'diversity_hellinger': 0.8041030516608872, 'diversity_cosine': 0.8749020641187326, 'perplexity': 13745.7548828125, 'ppl_fair': 13745.7548828125, 'ppl_cheatty': 5540.32275390625}
 60%|███████████████████████████▌                  | 12/20 [21:42<14:44, 110.55s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/1 [00:00<?, ?it/s]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.71it/s]
Using absoulte threshold: 0.7938587462014927.
Creating first level with 16 topics. Dictionary: artm.Dictionary(name=68b4bcd8-474f-49ce-9b78-de418b7c1481, num_entries=37739).
Copying phi for the first level. Phi shape: (37739, 16). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           )
Creating second level with 51 topics
Copying phi for the second level. Phi shape: (37739, 51). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 13745.7548828125, 'coherence_20': 1.1603842971196152, 'diversity_euclidean': 0.07057460933694086, 'diversity_jensenshannon': 0.685343850321118, 'diversity_hellinger': 0.8041030516608872, 'diversity_cosine': 0.8749020641187326, 'perplexity': 13745.7548828125, 'ppl_fair': 13745.7548828125, 'ppl_cheatty': 5540.32275390625}
 65%|█████████████████████████████▉                | 13/20 [23:25<12:39, 108.47s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/1 [00:00<?, ?it/s]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.84it/s]
Using absoulte threshold: 0.7938587462014927.
Creating first level with 16 topics. Dictionary: artm.Dictionary(name=68b4bcd8-474f-49ce-9b78-de418b7c1481, num_entries=37739).
Copying phi for the first level. Phi shape: (37739, 16). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           )
Creating second level with 51 topics
Copying phi for the second level. Phi shape: (37739, 51). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 13745.7548828125, 'coherence_20': 1.1603842971196152, 'diversity_euclidean': 0.07057460933694086, 'diversity_jensenshannon': 0.685343850321118, 'diversity_hellinger': 0.8041030516608872, 'diversity_cosine': 0.8749020641187326, 'perplexity': 13745.7548828125, 'ppl_fair': 13745.7548828125, 'ppl_cheatty': 5540.32275390625}
 70%|████████████████████████████████▏             | 14/20 [25:19<11:00, 110.08s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/1 [00:00<?, ?it/s]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.00it/s]
Using absoulte threshold: 0.7938587462014927.
Creating first level with 16 topics. Dictionary: artm.Dictionary(name=68b4bcd8-474f-49ce-9b78-de418b7c1481, num_entries=37739).
Copying phi for the first level. Phi shape: (37739, 16). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           )
Creating second level with 51 topics
Copying phi for the second level. Phi shape: (37739, 51). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 10600.2822265625, 'coherence_20': 1.1234509349701638, 'diversity_euclidean': 0.06990920633726874, 'diversity_jensenshannon': 0.6881067186156501, 'diversity_hellinger': 0.8069051467721298, 'diversity_cosine': 0.8776462960785973, 'perplexity': 10600.2822265625, 'ppl_fair': 10600.2822265625, 'ppl_cheatty': 5218.529296875}
 75%|██████████████████████████████████▌           | 15/20 [27:30<09:41, 116.38s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/1 [00:00<?, ?it/s]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.01it/s]
Using absoulte threshold: 0.7938587462014927.
Creating first level with 19 topics. Dictionary: artm.Dictionary(name=68b4bcd8-474f-49ce-9b78-de418b7c1481, num_entries=37739).
Copying phi for the first level. Phi shape: (37739, 19). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           )
Creating second level with 51 topics
Copying phi for the second level. Phi shape: (37739, 51). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 9854.8779296875, 'coherence_20': 1.1085728793951963, 'diversity_euclidean': 0.06930867360664636, 'diversity_jensenshannon': 0.6869296830683488, 'diversity_hellinger': 0.8053802860289481, 'diversity_cosine': 0.878448237604009, 'perplexity': 9854.8779296875, 'ppl_fair': 9854.8779296875, 'ppl_cheatty': 5139.45361328125}
 80%|████████████████████████████████████▊         | 16/20 [29:24<07:42, 115.58s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/1 [00:00<?, ?it/s]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.02it/s]
Using absoulte threshold: 0.7938587462014927.
Creating first level with 20 topics. Dictionary: artm.Dictionary(name=68b4bcd8-474f-49ce-9b78-de418b7c1481, num_entries=37739).
Copying phi for the first level. Phi shape: (37739, 20). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           )
Creating second level with 51 topics
Copying phi for the second level. Phi shape: (37739, 51). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 9854.8779296875, 'coherence_20': 1.1085728793951963, 'diversity_euclidean': 0.06930867360664636, 'diversity_jensenshannon': 0.6869296830683488, 'diversity_hellinger': 0.8053802860289481, 'diversity_cosine': 0.878448237604009, 'perplexity': 9854.8779296875, 'ppl_fair': 9854.8779296875, 'ppl_cheatty': 5139.45361328125}
 85%|███████████████████████████████████████       | 17/20 [31:14<05:42, 114.12s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/1 [00:00<?, ?it/s]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.97it/s]
Using absoulte threshold: 0.7938587462014927.
Creating first level with 20 topics. Dictionary: artm.Dictionary(name=68b4bcd8-474f-49ce-9b78-de418b7c1481, num_entries=37739).
Copying phi for the first level. Phi shape: (37739, 20). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           )
Creating second level with 51 topics
Copying phi for the second level. Phi shape: (37739, 51). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 9492.37109375, 'coherence_20': 1.0967409799884282, 'diversity_euclidean': 0.06884468919017744, 'diversity_jensenshannon': 0.6858695825538061, 'diversity_hellinger': 0.8040435784546612, 'diversity_cosine': 0.8783290812834309, 'perplexity': 9492.37109375, 'ppl_fair': 9492.37109375, 'ppl_cheatty': 5078.76904296875}
 90%|█████████████████████████████████████████▍    | 18/20 [33:18<03:53, 116.83s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/1 [00:00<?, ?it/s]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.02it/s]
Using absoulte threshold: 0.7938587462014927.
Creating first level with 21 topics. Dictionary: artm.Dictionary(name=68b4bcd8-474f-49ce-9b78-de418b7c1481, num_entries=37739).
Copying phi for the first level. Phi shape: (37739, 21). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           )
Creating second level with 51 topics
Copying phi for the second level. Phi shape: (37739, 51). First words: MultiIndex([('@lemmatized',     'hazardous'),
            ('@lemmatized', 'expostulation'),
            ('@lemmatized',        'hearse'),
            ('@lemmatized',      'valkyrie'),
            ('@lemmatized',     'sagebrush'),
            ('@lemmatized',        'oldham'),
            ('@lemmatized',   'indefinable'),
            ('@lemmatized',       'bellboy'),
            ('@lemmatized',      'katherin'),
            ('@lemmatized',     'deathdate')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 9192.8720703125, 'coherence_20': 1.0773131766905026, 'diversity_euclidean': 0.06746011408265991, 'diversity_jensenshannon': 0.6825363424503622, 'diversity_hellinger': 0.7998098519245985, 'diversity_cosine': 0.875497499598681, 'perplexity': 9192.8720703125, 'ppl_fair': 9192.8720703125, 'ppl_cheatty': 5054.6123046875}
100%|██████████████████████████████████████████████| 20/20 [37:03<00:00, 111.16s/it]
CPU times: user 42min 39s, sys: 1min 14s, total: 43min 54s
Wall time: 37min 3s

In [82]:
optimizer._main_modality

'@lemmatized'

What topics we have in bank

In [83]:
optimizer._topic_bank.view_topics().head()

                           topic_0  topic_1  topic_2  topic_3  topic_4  \
@lemmatized hazardous          0.0      0.0      0.0      0.0      0.0
            expostulation      0.0      0.0      0.0      0.0      0.0
            hearse             0.0      0.0      0.0      0.0      0.0
            valkyrie           0.0      0.0      0.0      0.0      0.0
            sagebrush          0.0      0.0      0.0      0.0      0.0

                           topic_5  topic_6  topic_7  topic_8   topic_9  ...  \
@lemmatized hazardous          0.0      0.0      0.0      0.0  0.000000  ...
            expostulation      0.0      0.0      0.0      0.0  0.000000  ...
            hearse             0.0      0.0      0.0      0.0  0.000019  ...
            valkyrie           0.0      0.0      0.0      0.0  0.000000  ...
            sagebrush          0.0      0.0      0.0      0.0  0.000000  ...

                           topic_11  topic_12  topic_13  topic_14  topic_15  \
@lemmatized hazardous           0.0       0.0       0.0       0.0       0.0
            expostulation       0.0       0.0       0.0       0.0       0.0
            hearse              0.0       0.0       0.0       0.0       0.0
            valkyrie            0.0       0.0       0.0       0.0       0.0
            sagebrush           0.0       0.0       0.0       0.0       0.0

                           topic_16  topic_17  topic_18  topic_19  topic_20
@lemmatized hazardous           0.0       0.0  0.000000       0.0       0.0
            expostulation       0.0       0.0  0.000044       0.0       0.0
            hearse              0.0       0.0  0.000000       0.0       0.0
            valkyrie            0.0       0.0  0.000000       0.0       0.0
            sagebrush           0.0       0.0  0.000000       0.0       0.0

[5 rows x 21 columns]

In [84]:
bank_topics = optimizer._topic_bank.view_topics()

In [85]:
bank_topics.shape

(37739, 21)

In [86]:
bank_topics.head()

                           topic_0  topic_1  topic_2  topic_3  topic_4  \
@lemmatized hazardous          0.0      0.0      0.0      0.0      0.0
            expostulation      0.0      0.0      0.0      0.0      0.0
            hearse             0.0      0.0      0.0      0.0      0.0
            valkyrie           0.0      0.0      0.0      0.0      0.0
            sagebrush          0.0      0.0      0.0      0.0      0.0

                           topic_5  topic_6  topic_7  topic_8   topic_9  ...  \
@lemmatized hazardous          0.0      0.0      0.0      0.0  0.000000  ...
            expostulation      0.0      0.0      0.0      0.0  0.000000  ...
            hearse             0.0      0.0      0.0      0.0  0.000019  ...
            valkyrie           0.0      0.0      0.0      0.0  0.000000  ...
            sagebrush          0.0      0.0      0.0      0.0  0.000000  ...

                           topic_11  topic_12  topic_13  topic_14  topic_15  \
@lemmatized hazardous           0.0       0.0       0.0       0.0       0.0
            expostulation       0.0       0.0       0.0       0.0       0.0
            hearse              0.0       0.0       0.0       0.0       0.0
            valkyrie            0.0       0.0       0.0       0.0       0.0
            sagebrush           0.0       0.0       0.0       0.0       0.0

                           topic_16  topic_17  topic_18  topic_19  topic_20
@lemmatized hazardous           0.0       0.0  0.000000       0.0       0.0
            expostulation       0.0       0.0  0.000044       0.0       0.0
            hearse              0.0       0.0  0.000000       0.0       0.0
            valkyrie            0.0       0.0  0.000000       0.0       0.0
            sagebrush           0.0       0.0  0.000000       0.0       0.0

[5 rows x 21 columns]

In [87]:
bank_topics['topic_7'].sort_values(ascending=False)[:20]

@lemmatized  emperor      0.055042
             imperial     0.032100
             japan        0.024586
             prince       0.023391
             daughter     0.016073
             japanese     0.015144
             princess     0.014929
             fujiwara     0.014755
             p            0.013037
             reign        0.012029
             donaldson    0.009103
             court        0.008996
             empress      0.008289
             brown        0.008168
             minamoto     0.008114
             varley       0.007744
             throne       0.007293
             titsingh     0.007006
             pp           0.006618
             month        0.005856
Name: topic_7, dtype: float64

And topic scores

In [88]:
optimizer._topic_bank.view_topic_scores()

,topic_0,topic_1,topic_2,topic_3,topic_4,topic_5,topic_6,topic_7,topic_8,topic_9,...,topic_11,topic_12,topic_13,topic_14,topic_15,topic_16,topic_17,topic_18,topic_19,topic_20
kernel_size,3669.000000,3826.000000,3891.000000,3566.000000,3153.000000,4026.000000,3564.000000,1701.000000,4146.000000,3762.000000,...,2869.000000,3096.000000,3406.000000,3213.000000,3485.000000,2956.000000,3598.000000,4309.000000,3316.000000,4387.000000
coherence_20,1.149359,1.094059,1.510019,1.042494,0.806954,1.897256,0.971696,1.017304,0.869236,0.925371,...,1.592502,0.934561,1.191814,1.079696,0.898798,1.046236,0.834385,0.825890,0.860103,0.947832
distance_to_nearest,0.000000,0.829735,0.843415,0.816017,0.810174,0.762359,0.838471,0.896446,0.818576,0.795369,...,0.516390,0.882426,0.582541,0.521878,0.791107,0.838275,0.619696,0.837643,0.805003,0.691188

All models are also saved (topics as $\Phi$ matrices and topic score values)

In [89]:
! ls $optimizer._topic_bank._path

model_0__phi.bin	    model_19__topic_scores.bin
model_0__topic_scores.bin   model_1__phi.bin
model_10__phi.bin	    model_1__topic_scores.bin
model_10__topic_scores.bin  model_2__phi.bin
model_11__phi.bin	    model_2__topic_scores.bin
model_11__topic_scores.bin  model_3__phi.bin
model_12__phi.bin	    model_3__topic_scores.bin
model_12__topic_scores.bin  model_4__phi.bin
model_13__phi.bin	    model_4__topic_scores.bin
model_13__topic_scores.bin  model_5__phi.bin
model_14__phi.bin	    model_5__topic_scores.bin
model_14__topic_scores.bin  model_6__phi.bin
model_15__phi.bin	    model_6__topic_scores.bin
model_15__topic_scores.bin  model_7__phi.bin
model_16__phi.bin	    model_7__topic_scores.bin
model_16__topic_scores.bin  model_8__phi.bin
model_17__phi.bin	    model_8__topic_scores.bin
model_17__topic_scores.bin  model_9__phi.bin
model_18__phi.bin	    model_9__topic_scores.bin
model_18__topic_scores.bin  topics.bin
model_19__phi.bin	    topic_scores.bin

In [90]:
optimizer._result.keys()

dict_keys(['optimum', 'optimum_std', 'bank_scores', 'bank_topic_scores', 'model_scores', 'model_topic_scores', 'num_bank_topics', 'num_model_topics'])

In [91]:
optimizer._result['num_bank_topics']

[11,
 11,
 11,
 12,
 13,
 14,
 14,
 14,
 14,
 15,
 16,
 16,
 16,
 16,
 19,
 20,
 20,
 21,
 21,
 21]

In [92]:
len(optimizer._result['bank_topic_scores'])

20

In [93]:
optimizer._result

{'optimum': 21,
 'optimum_std': 0.0,
 'bank_scores': [{'perplexity_score': 16077.958984375,
   'coherence_20': 1.1225033344850237,
   'diversity_euclidean': 0.06877371410525385,
   'diversity_jensenshannon': 0.687365105375971,
   'diversity_hellinger': 0.804517438601834,
   'diversity_cosine': 0.8903542350272428,
   'perplexity': 16077.958984375,
   'ppl_fair': 16077.958984375,
   'ppl_cheatty': 5728.96484375},
  {'perplexity_score': 16077.958984375,
   'coherence_20': 1.1225033344850237,
   'diversity_euclidean': 0.06877371410525385,
   'diversity_jensenshannon': 0.687365105375971,
   'diversity_hellinger': 0.804517438601834,
   'diversity_cosine': 0.8903542350272428,
   'perplexity': 16077.958984375,
   'ppl_fair': 16077.958984375,
   'ppl_cheatty': 5728.96484375},
  {'perplexity_score': 16077.958984375,
   'coherence_20': 1.1225033344850237,
   'diversity_euclidean': 0.06877371410525385,
   'diversity_jensenshannon': 0.687365105375971,
   'diversity_hellinger': 0.804517438601834,
   'diversity_cosine': 0.8903542350272428,
   'perplexity': 16077.958984375,
   'ppl_fair': 16077.958984375,
   'ppl_cheatty': 5728.96484375},
  {'perplexity_score': 15295.3505859375,
   'coherence_20': 1.0913945267901033,
   'diversity_euclidean': 0.07303163833524239,
   'diversity_jensenshannon': 0.6930954661913941,
   'diversity_hellinger': 0.811946775922991,
   'diversity_cosine': 0.8920698213991594,
   'perplexity': 15295.3505859375,
   'ppl_fair': 15295.3505859375,
   'ppl_cheatty': 5617.498046875},
  {'perplexity_score': 13889.2333984375,
   'coherence_20': 1.0743054059557282,
   'diversity_euclidean': 0.0728672063689704,
   'diversity_jensenshannon': 0.6914875281605614,
   'diversity_hellinger': 0.8100414254153561,
   'diversity_cosine': 0.8938906715015421,
   'perplexity': 13889.2333984375,
   'ppl_fair': 13889.2333984375,
   'ppl_cheatty': 5508.8828125},
  {'perplexity_score': 12954.525390625,
   'coherence_20': 1.0723075319803936,
   'diversity_euclidean': 0.06917390259235667,
   'diversity_jensenshannon': 0.6780474555774554,
   'diversity_hellinger': 0.7933355700885665,
   'diversity_cosine': 0.8746197119999312,
   'perplexity': 12954.525390625,
   'ppl_fair': 12954.525390625,
   'ppl_cheatty': 5444.82177734375},
  {'perplexity_score': 12954.525390625,
   'coherence_20': 1.0723075319803936,
   'diversity_euclidean': 0.06917390259235667,
   'diversity_jensenshannon': 0.6780474555774554,
   'diversity_hellinger': 0.7933355700885665,
   'diversity_cosine': 0.8746197119999312,
   'perplexity': 12954.525390625,
   'ppl_fair': 12954.525390625,
   'ppl_cheatty': 5444.82177734375},
  {'perplexity_score': 13016.353515625,
   'coherence_20': 1.1044389832629495,
   'diversity_euclidean': 0.0696202510374661,
   'diversity_jensenshannon': 0.6796310563559566,
   'diversity_hellinger': 0.7955621724209297,
   'diversity_cosine': 0.8753912467258014,
   'perplexity': 13016.353515625,
   'ppl_fair': 13016.353515625,
   'ppl_cheatty': 5490.9599609375},
  {'perplexity_score': 13206.0322265625,
   'coherence_20': 1.1583876240487163,
   'diversity_euclidean': 0.07096431241664203,
   'diversity_jensenshannon': 0.6780154043843674,
   'diversity_hellinger': 0.7943798148347189,
   'diversity_cosine': 0.8746746129180473,
   'perplexity': 13206.0322265625,
   'ppl_fair': 13206.0322265625,
   'ppl_cheatty': 5527.9228515625},
  {'perplexity_score': 12344.1923828125,
   'coherence_20': 1.1434658612491186,
   'diversity_euclidean': 0.07173208026707717,
   'diversity_jensenshannon': 0.684750209300096,
   'diversity_hellinger': 0.8026135056875996,
   'diversity_cosine': 0.8810206585783182,
   'perplexity': 12344.1923828125,
   'ppl_fair': 12344.1923828125,
   'ppl_cheatty': 5403.87451171875},
  {'perplexity_score': 13745.7548828125,
   'coherence_20': 1.1603842971196152,
   'diversity_euclidean': 0.07057460933694086,
   'diversity_jensenshannon': 0.685343850321118,
   'diversity_hellinger': 0.8041030516608872,
   'diversity_cosine': 0.8749020641187326,
   'perplexity': 13745.7548828125,
   'ppl_fair': 13745.7548828125,
   'ppl_cheatty': 5540.32275390625},
  {'perplexity_score': 13745.7548828125,
   'coherence_20': 1.1603842971196152,
   'diversity_euclidean': 0.07057460933694086,
   'diversity_jensenshannon': 0.685343850321118,
   'diversity_hellinger': 0.8041030516608872,
   'diversity_cosine': 0.8749020641187326,
   'perplexity': 13745.7548828125,
   'ppl_fair': 13745.7548828125,
   'ppl_cheatty': 5540.32275390625},
  {'perplexity_score': 13745.7548828125,
   'coherence_20': 1.1603842971196152,
   'diversity_euclidean': 0.07057460933694086,
   'diversity_jensenshannon': 0.685343850321118,
   'diversity_hellinger': 0.8041030516608872,
   'diversity_cosine': 0.8749020641187326,
   'perplexity': 13745.7548828125,
   'ppl_fair': 13745.7548828125,
   'ppl_cheatty': 5540.32275390625},
  {'perplexity_score': 13745.7548828125,
   'coherence_20': 1.1603842971196152,
   'diversity_euclidean': 0.07057460933694086,
   'diversity_jensenshannon': 0.685343850321118,
   'diversity_hellinger': 0.8041030516608872,
   'diversity_cosine': 0.8749020641187326,
   'perplexity': 13745.7548828125,
   'ppl_fair': 13745.7548828125,
   'ppl_cheatty': 5540.32275390625},
  {'perplexity_score': 10600.2822265625,
   'coherence_20': 1.1234509349701638,
   'diversity_euclidean': 0.06990920633726874,
   'diversity_jensenshannon': 0.6881067186156501,
   'diversity_hellinger': 0.8069051467721298,
   'diversity_cosine': 0.8776462960785973,
   'perplexity': 10600.2822265625,
   'ppl_fair': 10600.2822265625,
   'ppl_cheatty': 5218.529296875},
  {'perplexity_score': 9854.8779296875,
   'coherence_20': 1.1085728793951963,
   'diversity_euclidean': 0.06930867360664636,
   'diversity_jensenshannon': 0.6869296830683488,
   'diversity_hellinger': 0.8053802860289481,
   'diversity_cosine': 0.878448237604009,
   'perplexity': 9854.8779296875,
   'ppl_fair': 9854.8779296875,
   'ppl_cheatty': 5139.45361328125},
  {'perplexity_score': 9854.8779296875,
   'coherence_20': 1.1085728793951963,
   'diversity_euclidean': 0.06930867360664636,
   'diversity_jensenshannon': 0.6869296830683488,
   'diversity_hellinger': 0.8053802860289481,
   'diversity_cosine': 0.878448237604009,
   'perplexity': 9854.8779296875,
   'ppl_fair': 9854.8779296875,
   'ppl_cheatty': 5139.45361328125},
  {'perplexity_score': 9492.37109375,
   'coherence_20': 1.0967409799884282,
   'diversity_euclidean': 0.06884468919017744,
   'diversity_jensenshannon': 0.6858695825538061,
   'diversity_hellinger': 0.8040435784546612,
   'diversity_cosine': 0.8783290812834309,
   'perplexity': 9492.37109375,
   'ppl_fair': 9492.37109375,
   'ppl_cheatty': 5078.76904296875},
  {'perplexity_score': 9492.37109375,
   'coherence_20': 1.0967409799884282,
   'diversity_euclidean': 0.06884468919017744,
   'diversity_jensenshannon': 0.6858695825538061,
   'diversity_hellinger': 0.8040435784546612,
   'diversity_cosine': 0.8783290812834309,
   'perplexity': 9492.37109375,
   'ppl_fair': 9492.37109375,
   'ppl_cheatty': 5078.76904296875},
  {'perplexity_score': 9192.8720703125,
   'coherence_20': 1.0773131766905026,
   'diversity_euclidean': 0.06746011408265991,
   'diversity_jensenshannon': 0.6825363424503622,
   'diversity_hellinger': 0.7998098519245985,
   'diversity_cosine': 0.875497499598681,
   'perplexity': 9192.8720703125,
   'ppl_fair': 9192.8720703125,
   'ppl_cheatty': 5054.6123046875}],
 'bank_topic_scores': [[{'kernel_size': 3669,
    'coherence_20': 1.149358735569971,
    'distance_to_nearest': 0.0},
   {'kernel_size': 3826,
    'coherence_20': 1.0940593226519857,
    'distance_to_nearest': 0.8297350277944032},
   {'kernel_size': 2306,
    'coherence_20': 1.1740822671595732,
    'distance_to_nearest': 0.9141673378661013},
   {'kernel_size': 3490,
    'coherence_20': 1.0702254526038417,
    'distance_to_nearest': 0.9036188885034283},
   {'kernel_size': 3277,
    'coherence_20': 0.8372213061875133,
    'distance_to_nearest': 0.8369490437335917},
   {'kernel_size': 3891,
    'coherence_20': 1.510018973038721,
    'distance_to_nearest': 0.8434147923466643},
   {'kernel_size': 2925,
    'coherence_20': 0.7941706697558051,
    'distance_to_nearest': 0.8281433389755726},
   {'kernel_size': 3566,
    'coherence_20': 1.0424944557666154,
    'distance_to_nearest': 0.8160167830892179},
   {'kernel_size': 3153,
    'coherence_20': 0.8069537544283898,
    'distance_to_nearest': 0.8101736562618436},
   {'kernel_size': 4026,
    'coherence_20': 1.8972562345962294,
    'distance_to_nearest': 0.7623591891711462},
   {'kernel_size': 3564,
    'coherence_20': 0.9716955075766139,
    'distance_to_nearest': 0.8384707456613465}],
  [{'kernel_size': 3669,
    'coherence_20': 1.149358735569971,
    'distance_to_nearest': 0.0},
   {'kernel_size': 3826,
    'coherence_20': 1.0940593226519857,
    'distance_to_nearest': 0.8297350277944032},
   {'kernel_size': 2306,
    'coherence_20': 1.1740822671595732,
    'distance_to_nearest': 0.9141673378661013},
   {'kernel_size': 3490,
    'coherence_20': 1.0702254526038417,
    'distance_to_nearest': 0.9036188885034283},
   {'kernel_size': 3277,
    'coherence_20': 0.8372213061875133,
    'distance_to_nearest': 0.8369490437335917},
   {'kernel_size': 3891,
    'coherence_20': 1.510018973038721,
    'distance_to_nearest': 0.8434147923466643},
   {'kernel_size': 2925,
    'coherence_20': 0.7941706697558051,
    'distance_to_nearest': 0.8281433389755726},
   {'kernel_size': 3566,
    'coherence_20': 1.0424944557666154,
    'distance_to_nearest': 0.8160167830892179},
   {'kernel_size': 3153,
    'coherence_20': 0.8069537544283898,
    'distance_to_nearest': 0.8101736562618436},
   {'kernel_size': 4026,
    'coherence_20': 1.8972562345962294,
    'distance_to_nearest': 0.7623591891711462},
   {'kernel_size': 3564,
    'coherence_20': 0.9716955075766139,
    'distance_to_nearest': 0.8384707456613465}],
  [{'kernel_size': 3669,
    'coherence_20': 1.149358735569971,
    'distance_to_nearest': 0.0},
   {'kernel_size': 3826,
    'coherence_20': 1.0940593226519857,
    'distance_to_nearest': 0.8297350277944032},
   {'kernel_size': 2306,
    'coherence_20': 1.1740822671595732,
    'distance_to_nearest': 0.9141673378661013},
   {'kernel_size': 3490,
    'coherence_20': 1.0702254526038417,
    'distance_to_nearest': 0.9036188885034283},
   {'kernel_size': 3277,
    'coherence_20': 0.8372213061875133,
    'distance_to_nearest': 0.8369490437335917},
   {'kernel_size': 3891,
    'coherence_20': 1.510018973038721,
    'distance_to_nearest': 0.8434147923466643},
   {'kernel_size': 2925,
    'coherence_20': 0.7941706697558051,
    'distance_to_nearest': 0.8281433389755726},
   {'kernel_size': 3566,
    'coherence_20': 1.0424944557666154,
    'distance_to_nearest': 0.8160167830892179},
   {'kernel_size': 3153,
    'coherence_20': 0.8069537544283898,
    'distance_to_nearest': 0.8101736562618436},
   {'kernel_size': 4026,
    'coherence_20': 1.8972562345962294,
    'distance_to_nearest': 0.7623591891711462},
   {'kernel_size': 3564,
    'coherence_20': 0.9716955075766139,
    'distance_to_nearest': 0.8384707456613465}],
  [{'kernel_size': 3669,
    'coherence_20': 1.149358735569971,
    'distance_to_nearest': 0.0},
   {'kernel_size': 3826,
    'coherence_20': 1.0940593226519857,
    'distance_to_nearest': 0.8297350277944032},
   {'kernel_size': 3490,
    'coherence_20': 1.0702254526038417,
    'distance_to_nearest': 0.9036188885034283},
   {'kernel_size': 3277,
    'coherence_20': 0.8372213061875133,
    'distance_to_nearest': 0.8369490437335917},
   {'kernel_size': 3891,
    'coherence_20': 1.510018973038721,
    'distance_to_nearest': 0.8434147923466643},
   {'kernel_size': 2925,
    'coherence_20': 0.7941706697558051,
    'distance_to_nearest': 0.8281433389755726},
   {'kernel_size': 3566,
    'coherence_20': 1.0424944557666154,
    'distance_to_nearest': 0.8160167830892179},
   {'kernel_size': 3153,
    'coherence_20': 0.8069537544283898,
    'distance_to_nearest': 0.8101736562618436},
   {'kernel_size': 4026,
    'coherence_20': 1.8972562345962294,
    'distance_to_nearest': 0.7623591891711462},
   {'kernel_size': 3564,
    'coherence_20': 0.9716955075766139,
    'distance_to_nearest': 0.8384707456613465},
   {'kernel_size': 3165,
    'coherence_20': 0.9059756049421909,
    'distance_to_nearest': 0.5153602642523841},
   {'kernel_size': 1701,
    'coherence_20': 1.0173043043633647,
    'distance_to_nearest': 0.8964464055369347}],
  [{'kernel_size': 3669,
    'coherence_20': 1.149358735569971,
    'distance_to_nearest': 0.0},
   {'kernel_size': 3826,
    'coherence_20': 1.0940593226519857,
    'distance_to_nearest': 0.8297350277944032},
   {'kernel_size': 3490,
    'coherence_20': 1.0702254526038417,
    'distance_to_nearest': 0.9036188885034283},
   {'kernel_size': 3277,
    'coherence_20': 0.8372213061875133,
    'distance_to_nearest': 0.8369490437335917},
   {'kernel_size': 3891,
    'coherence_20': 1.510018973038721,
    'distance_to_nearest': 0.8434147923466643},
   {'kernel_size': 2925,
    'coherence_20': 0.7941706697558051,
    'distance_to_nearest': 0.8281433389755726},
   {'kernel_size': 3566,
    'coherence_20': 1.0424944557666154,
    'distance_to_nearest': 0.8160167830892179},
   {'kernel_size': 3153,
    'coherence_20': 0.8069537544283898,
    'distance_to_nearest': 0.8101736562618436},
   {'kernel_size': 4026,
    'coherence_20': 1.8972562345962294,
    'distance_to_nearest': 0.7623591891711462},
   {'kernel_size': 3564,
    'coherence_20': 0.9716955075766139,
    'distance_to_nearest': 0.8384707456613465},
   {'kernel_size': 3165,
    'coherence_20': 0.9059756049421909,
    'distance_to_nearest': 0.5153602642523841},
   {'kernel_size': 1701,
    'coherence_20': 1.0173043043633647,
    'distance_to_nearest': 0.8964464055369347},
   {'kernel_size': 4146,
    'coherence_20': 0.8692359559432287,
    'distance_to_nearest': 0.8185755560490198}],
  [{'kernel_size': 3669,
    'coherence_20': 1.149358735569971,
    'distance_to_nearest': 0.0},
   {'kernel_size': 3826,
    'coherence_20': 1.0940593226519857,
    'distance_to_nearest': 0.8297350277944032},
   {'kernel_size': 3277,
    'coherence_20': 0.8372213061875133,
    'distance_to_nearest': 0.8369490437335917},
   {'kernel_size': 3891,
    'coherence_20': 1.510018973038721,
    'distance_to_nearest': 0.8434147923466643},
   {'kernel_size': 3566,
    'coherence_20': 1.0424944557666154,
    'distance_to_nearest': 0.8160167830892179},
   {'kernel_size': 3153,
    'coherence_20': 0.8069537544283898,
    'distance_to_nearest': 0.8101736562618436},
   {'kernel_size': 4026,
    'coherence_20': 1.8972562345962294,
    'distance_to_nearest': 0.7623591891711462},
   {'kernel_size': 3564,
    'coherence_20': 0.9716955075766139,
    'distance_to_nearest': 0.8384707456613465},
   {'kernel_size': 3165,
    'coherence_20': 0.9059756049421909,
    'distance_to_nearest': 0.5153602642523841},
   {'kernel_size': 1701,
    'coherence_20': 1.0173043043633647,
    'distance_to_nearest': 0.8964464055369347},
   {'kernel_size': 4146,
    'coherence_20': 0.8692359559432287,
    'distance_to_nearest': 0.8185755560490198},
   {'kernel_size': 3613,
    'coherence_20': 0.8573492199155398,
    'distance_to_nearest': 0.5057787089690937},
   {'kernel_size': 3762,
    'coherence_20': 0.9253711681721909,
    'distance_to_nearest': 0.7953685305484234},
   {'kernel_size': 3918,
    'coherence_20': 1.1280109045729594,
    'distance_to_nearest': 0.8157644395371685}],
  [{'kernel_size': 3669,
    'coherence_20': 1.149358735569971,
    'distance_to_nearest': 0.0},
   {'kernel_size': 3826,
    'coherence_20': 1.0940593226519857,
    'distance_to_nearest': 0.8297350277944032},
   {'kernel_size': 3277,
    'coherence_20': 0.8372213061875133,
    'distance_to_nearest': 0.8369490437335917},
   {'kernel_size': 3891,
    'coherence_20': 1.510018973038721,
    'distance_to_nearest': 0.8434147923466643},
   {'kernel_size': 3566,
    'coherence_20': 1.0424944557666154,
    'distance_to_nearest': 0.8160167830892179},
   {'kernel_size': 3153,
    'coherence_20': 0.8069537544283898,
    'distance_to_nearest': 0.8101736562618436},
   {'kernel_size': 4026,
    'coherence_20': 1.8972562345962294,
    'distance_to_nearest': 0.7623591891711462},
   {'kernel_size': 3564,
    'coherence_20': 0.9716955075766139,
    'distance_to_nearest': 0.8384707456613465},
   {'kernel_size': 3165,
    'coherence_20': 0.9059756049421909,
    'distance_to_nearest': 0.5153602642523841},
   {'kernel_size': 1701,
    'coherence_20': 1.0173043043633647,
    'distance_to_nearest': 0.8964464055369347},
   {'kernel_size': 4146,
    'coherence_20': 0.8692359559432287,
    'distance_to_nearest': 0.8185755560490198},
   {'kernel_size': 3613,
    'coherence_20': 0.8573492199155398,
    'distance_to_nearest': 0.5057787089690937},
   {'kernel_size': 3762,
    'coherence_20': 0.9253711681721909,
    'distance_to_nearest': 0.7953685305484234},
   {'kernel_size': 3918,
    'coherence_20': 1.1280109045729594,
    'distance_to_nearest': 0.8157644395371685}],
  [{'kernel_size': 3669,
    'coherence_20': 1.149358735569971,
    'distance_to_nearest': 0.0},
   {'kernel_size': 3826,
    'coherence_20': 1.0940593226519857,
    'distance_to_nearest': 0.8297350277944032},
   {'kernel_size': 3277,
    'coherence_20': 0.8372213061875133,
    'distance_to_nearest': 0.8369490437335917},
   {'kernel_size': 3891,
    'coherence_20': 1.510018973038721,
    'distance_to_nearest': 0.8434147923466643},
   {'kernel_size': 3566,
    'coherence_20': 1.0424944557666154,
    'distance_to_nearest': 0.8160167830892179},
   {'kernel_size': 3153,
    'coherence_20': 0.8069537544283898,
    'distance_to_nearest': 0.8101736562618436},
   {'kernel_size': 4026,
    'coherence_20': 1.8972562345962294,
    'distance_to_nearest': 0.7623591891711462},
   {'kernel_size': 3564,
    'coherence_20': 0.9716955075766139,
    'distance_to_nearest': 0.8384707456613465},
   {'kernel_size': 1701,
    'coherence_20': 1.0173043043633647,
    'distance_to_nearest': 0.8964464055369347},
   {'kernel_size': 4146,
    'coherence_20': 0.8692359559432287,
    'distance_to_nearest': 0.8185755560490198},
   {'kernel_size': 3613,
    'coherence_20': 0.8573492199155398,
    'distance_to_nearest': 0.5057787089690937},
   {'kernel_size': 3762,
    'coherence_20': 0.9253711681721909,
    'distance_to_nearest': 0.7953685305484234},
   {'kernel_size': 3918,
    'coherence_20': 1.1280109045729594,
    'distance_to_nearest': 0.8157644395371685},
   {'kernel_size': 3195,
    'coherence_20': 1.3558159228979751,
    'distance_to_nearest': 0.8453092019024341}],
  [{'kernel_size': 3669,
    'coherence_20': 1.149358735569971,
    'distance_to_nearest': 0.0},
   {'kernel_size': 3826,
    'coherence_20': 1.0940593226519857,
    'distance_to_nearest': 0.8297350277944032},
   {'kernel_size': 3891,
    'coherence_20': 1.510018973038721,
    'distance_to_nearest': 0.8434147923466643},
   {'kernel_size': 3566,
    'coherence_20': 1.0424944557666154,
    'distance_to_nearest': 0.8160167830892179},
   {'kernel_size': 3153,
    'coherence_20': 0.8069537544283898,
    'distance_to_nearest': 0.8101736562618436},
   {'kernel_size': 4026,
    'coherence_20': 1.8972562345962294,
    'distance_to_nearest': 0.7623591891711462},
   {'kernel_size': 3564,
    'coherence_20': 0.9716955075766139,
    'distance_to_nearest': 0.8384707456613465},
   {'kernel_size': 1701,
    'coherence_20': 1.0173043043633647,
    'distance_to_nearest': 0.8964464055369347},
   {'kernel_size': 4146,
    'coherence_20': 0.8692359559432287,
    'distance_to_nearest': 0.8185755560490198},
   {'kernel_size': 3613,
    'coherence_20': 0.8573492199155398,
    'distance_to_nearest': 0.5057787089690937},
   {'kernel_size': 3762,
    'coherence_20': 0.9253711681721909,
    'distance_to_nearest': 0.7953685305484234},
   {'kernel_size': 3918,
    'coherence_20': 1.1280109045729594,
    'distance_to_nearest': 0.8157644395371685},
   {'kernel_size': 3195,
    'coherence_20': 1.3558159228979751,

In [94]:
optimizer._result['bank_topic_scores']

[[{'kernel_size': 3669,
   'coherence_20': 1.149358735569971,
   'distance_to_nearest': 0.0},
  {'kernel_size': 3826,
   'coherence_20': 1.0940593226519857,
   'distance_to_nearest': 0.8297350277944032},
  {'kernel_size': 2306,
   'coherence_20': 1.1740822671595732,
   'distance_to_nearest': 0.9141673378661013},
  {'kernel_size': 3490,
   'coherence_20': 1.0702254526038417,
   'distance_to_nearest': 0.9036188885034283},
  {'kernel_size': 3277,
   'coherence_20': 0.8372213061875133,
   'distance_to_nearest': 0.8369490437335917},
  {'kernel_size': 3891,
   'coherence_20': 1.510018973038721,
   'distance_to_nearest': 0.8434147923466643},
  {'kernel_size': 2925,
   'coherence_20': 0.7941706697558051,
   'distance_to_nearest': 0.8281433389755726},
  {'kernel_size': 3566,
   'coherence_20': 1.0424944557666154,
   'distance_to_nearest': 0.8160167830892179},
  {'kernel_size': 3153,
   'coherence_20': 0.8069537544283898,
   'distance_to_nearest': 0.8101736562618436},
  {'kernel_size': 4026,
   'coherence_20': 1.8972562345962294,
   'distance_to_nearest': 0.7623591891711462},
  {'kernel_size': 3564,
   'coherence_20': 0.9716955075766139,
   'distance_to_nearest': 0.8384707456613465}],
 [{'kernel_size': 3669,
   'coherence_20': 1.149358735569971,
   'distance_to_nearest': 0.0},
  {'kernel_size': 3826,
   'coherence_20': 1.0940593226519857,
   'distance_to_nearest': 0.8297350277944032},
  {'kernel_size': 2306,
   'coherence_20': 1.1740822671595732,
   'distance_to_nearest': 0.9141673378661013},
  {'kernel_size': 3490,
   'coherence_20': 1.0702254526038417,
   'distance_to_nearest': 0.9036188885034283},
  {'kernel_size': 3277,
   'coherence_20': 0.8372213061875133,
   'distance_to_nearest': 0.8369490437335917},
  {'kernel_size': 3891,
   'coherence_20': 1.510018973038721,
   'distance_to_nearest': 0.8434147923466643},
  {'kernel_size': 2925,
   'coherence_20': 0.7941706697558051,
   'distance_to_nearest': 0.8281433389755726},
  {'kernel_size': 3566,
   'coherence_20': 1.0424944557666154,
   'distance_to_nearest': 0.8160167830892179},
  {'kernel_size': 3153,
   'coherence_20': 0.8069537544283898,
   'distance_to_nearest': 0.8101736562618436},
  {'kernel_size': 4026,
   'coherence_20': 1.8972562345962294,
   'distance_to_nearest': 0.7623591891711462},
  {'kernel_size': 3564,
   'coherence_20': 0.9716955075766139,
   'distance_to_nearest': 0.8384707456613465}],
 [{'kernel_size': 3669,
   'coherence_20': 1.149358735569971,
   'distance_to_nearest': 0.0},
  {'kernel_size': 3826,
   'coherence_20': 1.0940593226519857,
   'distance_to_nearest': 0.8297350277944032},
  {'kernel_size': 2306,
   'coherence_20': 1.1740822671595732,
   'distance_to_nearest': 0.9141673378661013},
  {'kernel_size': 3490,
   'coherence_20': 1.0702254526038417,
   'distance_to_nearest': 0.9036188885034283},
  {'kernel_size': 3277,
   'coherence_20': 0.8372213061875133,
   'distance_to_nearest': 0.8369490437335917},
  {'kernel_size': 3891,
   'coherence_20': 1.510018973038721,
   'distance_to_nearest': 0.8434147923466643},
  {'kernel_size': 2925,
   'coherence_20': 0.7941706697558051,
   'distance_to_nearest': 0.8281433389755726},
  {'kernel_size': 3566,
   'coherence_20': 1.0424944557666154,
   'distance_to_nearest': 0.8160167830892179},
  {'kernel_size': 3153,
   'coherence_20': 0.8069537544283898,
   'distance_to_nearest': 0.8101736562618436},
  {'kernel_size': 4026,
   'coherence_20': 1.8972562345962294,
   'distance_to_nearest': 0.7623591891711462},
  {'kernel_size': 3564,
   'coherence_20': 0.9716955075766139,
   'distance_to_nearest': 0.8384707456613465}],
 [{'kernel_size': 3669,
   'coherence_20': 1.149358735569971,
   'distance_to_nearest': 0.0},
  {'kernel_size': 3826,
   'coherence_20': 1.0940593226519857,
   'distance_to_nearest': 0.8297350277944032},
  {'kernel_size': 3490,
   'coherence_20': 1.0702254526038417,
   'distance_to_nearest': 0.9036188885034283},
  {'kernel_size': 3277,
   'coherence_20': 0.8372213061875133,
   'distance_to_nearest': 0.8369490437335917},
  {'kernel_size': 3891,
   'coherence_20': 1.510018973038721,
   'distance_to_nearest': 0.8434147923466643},
  {'kernel_size': 2925,
   'coherence_20': 0.7941706697558051,
   'distance_to_nearest': 0.8281433389755726},
  {'kernel_size': 3566,
   'coherence_20': 1.0424944557666154,
   'distance_to_nearest': 0.8160167830892179},
  {'kernel_size': 3153,
   'coherence_20': 0.8069537544283898,
   'distance_to_nearest': 0.8101736562618436},
  {'kernel_size': 4026,
   'coherence_20': 1.8972562345962294,
   'distance_to_nearest': 0.7623591891711462},
  {'kernel_size': 3564,
   'coherence_20': 0.9716955075766139,
   'distance_to_nearest': 0.8384707456613465},
  {'kernel_size': 3165,
   'coherence_20': 0.9059756049421909,
   'distance_to_nearest': 0.5153602642523841},
  {'kernel_size': 1701,
   'coherence_20': 1.0173043043633647,
   'distance_to_nearest': 0.8964464055369347}],
 [{'kernel_size': 3669,
   'coherence_20': 1.149358735569971,
   'distance_to_nearest': 0.0},
  {'kernel_size': 3826,
   'coherence_20': 1.0940593226519857,
   'distance_to_nearest': 0.8297350277944032},
  {'kernel_size': 3490,
   'coherence_20': 1.0702254526038417,
   'distance_to_nearest': 0.9036188885034283},
  {'kernel_size': 3277,
   'coherence_20': 0.8372213061875133,
   'distance_to_nearest': 0.8369490437335917},
  {'kernel_size': 3891,
   'coherence_20': 1.510018973038721,
   'distance_to_nearest': 0.8434147923466643},
  {'kernel_size': 2925,
   'coherence_20': 0.7941706697558051,
   'distance_to_nearest': 0.8281433389755726},
  {'kernel_size': 3566,
   'coherence_20': 1.0424944557666154,
   'distance_to_nearest': 0.8160167830892179},
  {'kernel_size': 3153,
   'coherence_20': 0.8069537544283898,
   'distance_to_nearest': 0.8101736562618436},
  {'kernel_size': 4026,
   'coherence_20': 1.8972562345962294,
   'distance_to_nearest': 0.7623591891711462},
  {'kernel_size': 3564,
   'coherence_20': 0.9716955075766139,
   'distance_to_nearest': 0.8384707456613465},
  {'kernel_size': 3165,
   'coherence_20': 0.9059756049421909,
   'distance_to_nearest': 0.5153602642523841},
  {'kernel_size': 1701,
   'coherence_20': 1.0173043043633647,
   'distance_to_nearest': 0.8964464055369347},
  {'kernel_size': 4146,
   'coherence_20': 0.8692359559432287,
   'distance_to_nearest': 0.8185755560490198}],
 [{'kernel_size': 3669,
   'coherence_20': 1.149358735569971,
   'distance_to_nearest': 0.0},
  {'kernel_size': 3826,
   'coherence_20': 1.0940593226519857,
   'distance_to_nearest': 0.8297350277944032},
  {'kernel_size': 3277,
   'coherence_20': 0.8372213061875133,
   'distance_to_nearest': 0.8369490437335917},
  {'kernel_size': 3891,
   'coherence_20': 1.510018973038721,
   'distance_to_nearest': 0.8434147923466643},
  {'kernel_size': 3566,
   'coherence_20': 1.0424944557666154,
   'distance_to_nearest': 0.8160167830892179},
  {'kernel_size': 3153,
   'coherence_20': 0.8069537544283898,
   'distance_to_nearest': 0.8101736562618436},
  {'kernel_size': 4026,
   'coherence_20': 1.8972562345962294,
   'distance_to_nearest': 0.7623591891711462},
  {'kernel_size': 3564,
   'coherence_20': 0.9716955075766139,
   'distance_to_nearest': 0.8384707456613465},
  {'kernel_size': 3165,
   'coherence_20': 0.9059756049421909,
   'distance_to_nearest': 0.5153602642523841},
  {'kernel_size': 1701,
   'coherence_20': 1.0173043043633647,
   'distance_to_nearest': 0.8964464055369347},
  {'kernel_size': 4146,
   'coherence_20': 0.8692359559432287,
   'distance_to_nearest': 0.8185755560490198},
  {'kernel_size': 3613,
   'coherence_20': 0.8573492199155398,
   'distance_to_nearest': 0.5057787089690937},
  {'kernel_size': 3762,
   'coherence_20': 0.9253711681721909,
   'distance_to_nearest': 0.7953685305484234},
  {'kernel_size': 3918,
   'coherence_20': 1.1280109045729594,
   'distance_to_nearest': 0.8157644395371685}],
 [{'kernel_size': 3669,
   'coherence_20': 1.149358735569971,
   'distance_to_nearest': 0.0},
  {'kernel_size': 3826,
   'coherence_20': 1.0940593226519857,
   'distance_to_nearest': 0.8297350277944032},
  {'kernel_size': 3277,
   'coherence_20': 0.8372213061875133,
   'distance_to_nearest': 0.8369490437335917},
  {'kernel_size': 3891,
   'coherence_20': 1.510018973038721,
   'distance_to_nearest': 0.8434147923466643},
  {'kernel_size': 3566,
   'coherence_20': 1.0424944557666154,
   'distance_to_nearest': 0.8160167830892179},
  {'kernel_size': 3153,
   'coherence_20': 0.8069537544283898,
   'distance_to_nearest': 0.8101736562618436},
  {'kernel_size': 4026,
   'coherence_20': 1.8972562345962294,
   'distance_to_nearest': 0.7623591891711462},
  {'kernel_size': 3564,
   'coherence_20': 0.9716955075766139,
   'distance_to_nearest': 0.8384707456613465},
  {'kernel_size': 3165,
   'coherence_20': 0.9059756049421909,
   'distance_to_nearest': 0.5153602642523841},
  {'kernel_size': 1701,
   'coherence_20': 1.0173043043633647,
   'distance_to_nearest': 0.8964464055369347},
  {'kernel_size': 4146,
   'coherence_20': 0.8692359559432287,
   'distance_to_nearest': 0.8185755560490198},
  {'kernel_size': 3613,
   'coherence_20': 0.8573492199155398,
   'distance_to_nearest': 0.5057787089690937},
  {'kernel_size': 3762,
   'coherence_20': 0.9253711681721909,
   'distance_to_nearest': 0.7953685305484234},
  {'kernel_size': 3918,
   'coherence_20': 1.1280109045729594,
   'distance_to_nearest': 0.8157644395371685}],
 [{'kernel_size': 3669,
   'coherence_20': 1.149358735569971,
   'distance_to_nearest': 0.0},
  {'kernel_size': 3826,
   'coherence_20': 1.0940593226519857,
   'distance_to_nearest': 0.8297350277944032},
  {'kernel_size': 3277,
   'coherence_20': 0.8372213061875133,
   'distance_to_nearest': 0.8369490437335917},
  {'kernel_size': 3891,
   'coherence_20': 1.510018973038721,
   'distance_to_nearest': 0.8434147923466643},
  {'kernel_size': 3566,
   'coherence_20': 1.0424944557666154,
   'distance_to_nearest': 0.8160167830892179},
  {'kernel_size': 3153,
   'coherence_20': 0.8069537544283898,
   'distance_to_nearest': 0.8101736562618436},
  {'kernel_size': 4026,
   'coherence_20': 1.8972562345962294,
   'distance_to_nearest': 0.7623591891711462},
  {'kernel_size': 3564,
   'coherence_20': 0.9716955075766139,
   'distance_to_nearest': 0.8384707456613465},
  {'kernel_size': 1701,
   'coherence_20': 1.0173043043633647,
   'distance_to_nearest': 0.8964464055369347},
  {'kernel_size': 4146,
   'coherence_20': 0.8692359559432287,
   'distance_to_nearest': 0.8185755560490198},
  {'kernel_size': 3613,
   'coherence_20': 0.8573492199155398,
   'distance_to_nearest': 0.5057787089690937},
  {'kernel_size': 3762,
   'coherence_20': 0.9253711681721909,
   'distance_to_nearest': 0.7953685305484234},
  {'kernel_size': 3918,
   'coherence_20': 1.1280109045729594,
   'distance_to_nearest': 0.8157644395371685},
  {'kernel_size': 3195,
   'coherence_20': 1.3558159228979751,
   'distance_to_nearest': 0.8453092019024341}],
 [{'kernel_size': 3669,
   'coherence_20': 1.149358735569971,
   'distance_to_nearest': 0.0},
  {'kernel_size': 3826,
   'coherence_20': 1.0940593226519857,
   'distance_to_nearest': 0.8297350277944032},
  {'kernel_size': 3891,
   'coherence_20': 1.510018973038721,
   'distance_to_nearest': 0.8434147923466643},
  {'kernel_size': 3566,
   'coherence_20': 1.0424944557666154,
   'distance_to_nearest': 0.8160167830892179},
  {'kernel_size': 3153,
   'coherence_20': 0.8069537544283898,
   'distance_to_nearest': 0.8101736562618436},
  {'kernel_size': 4026,
   'coherence_20': 1.8972562345962294,
   'distance_to_nearest': 0.7623591891711462},
  {'kernel_size': 3564,
   'coherence_20': 0.9716955075766139,
   'distance_to_nearest': 0.8384707456613465},
  {'kernel_size': 1701,
   'coherence_20': 1.0173043043633647,
   'distance_to_nearest': 0.8964464055369347},
  {'kernel_size': 4146,
   'coherence_20': 0.8692359559432287,
   'distance_to_nearest': 0.8185755560490198},
  {'kernel_size': 3613,
   'coherence_20': 0.8573492199155398,
   'distance_to_nearest': 0.5057787089690937},
  {'kernel_size': 3762,
   'coherence_20': 0.9253711681721909,
   'distance_to_nearest': 0.7953685305484234},
  {'kernel_size': 3918,
   'coherence_20': 1.1280109045729594,
   'distance_to_nearest': 0.8157644395371685},
  {'kernel_size': 3195,
   'coherence_20': 1.3558159228979751,
   'distance_to_nearest': 0.8453092019024341},
  {'kernel_size': 2869,
   'coherence_20': 1.5925022771882447,
   'distance_to_nearest': 0.5163896602802551}],
 [{'kernel_size': 3669,
   'coherence_20': 1.149358735569971,
   'distance_to_nearest': 0.0},
  {'kernel_size': 3826,
   'coherence_20': 1.0940593226519857,
   'distance_to_nearest': 0.8297350277944032},
  {'kernel_size': 3891,
   'coherence_20': 1.510018973038721,
   'distance_to_nearest': 0.8434147923466643},
  {'kernel_size': 3566,
   'coherence_20': 1.0424944557666154,
   'distance_to_nearest': 0.8160167830892179},
  {'kernel_size': 3153,
   'coherence_20': 0.8069537544283898,
   'distance_to_nearest': 0.8101736562618436},
  {'kernel_size': 4026,
   'coherence_20': 1.8972562345962294,
   'distance_to_nearest': 0.7623591891711462},
  {'kernel_size': 3564,
   'coherence_20': 0.9716955075766139,
   'distance_to_nearest': 0.8384707456613465},
  {'kernel_size': 1701,
   'coherence_20': 1.0173043043633647,
   'distance_to_nearest': 0.8964464055369347},
  {'kernel_size': 4146,
   'coherence_20': 0.8692359559432287,
   'distance_to_nearest': 0.8185755560490198},
  {'kernel_size': 3613,
   'coherence_20': 0.8573492199155398,
   'distance_to_nearest': 0.5057787089690937},
  {'kernel_size': 3762,
   'coherence_20': 0.9253711681721909,
   'distance_to_nearest': 0.7953685305484234},
  {'kernel_size': 3918,
   'coherence_20': 1.1280109045729594,
   'distance_to_nearest': 0.8157644395371685},
  {'kernel_size': 3195,
   'coherence_20': 1.3558159228979751,
   'distance_to_nearest': 0.8453092019024341},
  {'kernel_size': 2869,
   'coherence_20': 1.5925022771882447,
   'distance_to_nearest': 0.5163896602802551},
  {'kernel_size': 3096,
   'coherence_20': 0.9345611820547499,
   'distance_to_nearest': 0.8824258051780441}],
 [{'kernel_size': 3669,
   'coherence_20': 1.149358735569971,
   'distance_to_nearest': 0.0},
  {'kernel_size': 3826,
   'coherence_20': 1.0940593226519857,
   'distance_to_nearest': 0.8297350277944032},
  {'kernel_size': 3891,
   'coherence_20': 1.510018973038721,
   'distance_to_nearest': 0.8434147923466643},
  {'kernel_size': 3566,
   'coherence_20': 1.0424944557666154,
   'distance_to_nearest': 0.8160167830892179},
  {'kernel_size': 3153,
   'coherence_20': 0.8069537544283898,
   'distance_to_nearest': 0.8101736562618436},
  {'kernel_size': 4026,
   'coherence_20': 1.8972562345962294,
   'distance_to_nearest': 0.7623591891711462},
  {'kernel_size': 3564,
   'coherence_20': 0.9716955075766139,
   'distance_to_nearest': 0.8384707456613465},
  {'kernel_size': 1701,
   'coherence_20': 1.0173043043633647,
   'distance_to_nearest': 0.8964464055369347},
  {'kernel_size': 4146,
   'coherence_20': 0.8692359559432287,
   'distance_to_nearest': 0.8185755560490198},
  {'kernel_size': 3762,
   'coherence_20': 0.9253711681721909,
   'distance_to_nearest': 0.7953685305484234},
  {'kernel_size': 3918,
   'coherence_20': 1.1280109045729594,
   'distance_to_nearest': 0.8157644395371685},
  {'kernel_size': 3195,
   'coherence_20': 1.3558159228979751,
   'distance_to_nearest': 0.8453092019024341},
  {'kernel_size': 2869,
   'coherence_20': 1.5925022771882447,
   'distance_to_nearest': 0.5163896602802551},
  {'kernel_size': 3096,
   'coherence_20': 0.9345611820547499,
   'distance_to_nearest': 0.8824258051780441},
  {'kernel_size': 3406,
   'coherence_20': 1.191813786432536,
   'distance_to_nearest': 0.5825411765774876},
  {'kernel_size': 3213,
   'coherence_20': 1.0796962686600688,
   'distance_to_nearest': 0.5218784176386061}],
 [{'kernel_size': 3669,
   'coherence_20': 1.149358735569971,
   'distance_to_nearest': 0.0},
  {'kernel_size': 3826,
   'coherence_20': 1.0940593226519857,
   'distance_to_nearest': 0.8297350277944032},
  {'kernel_size': 3891,
   'coherence_20': 1.510018973038721,
   'distance_to_nearest': 0.8434147923466643},
  {'kernel_size': 3566,
   'coherence_20': 1.0424944557666154,
   'distance_to_nearest': 0.8160167830892179},
  {'kernel_size': 3153,
   'coherence_20': 0.8069537544283898,
   'distance_to_nearest': 0.8101736562618436},
  {'kernel_size': 4026,
   'coherence_20': 1.8972562345962294,
   'distance_to_nearest': 0.7623591891711462},
  {'kernel_size': 3564,
   'coherence_20': 0.9716955075766139,
   'distance_to_nearest': 0.8384707456613465},
  {'kernel_size': 1701,
   'coherence_20': 1.0173043043633647,
   'distance_to_nearest': 0.8964464055369347},
  {'kernel_size': 4146,
   'coherence_20': 0.8692359559432287,
   'distance_to_nearest': 0.8185755560490198},
  {'kernel_size': 3762,
   'coherence_20': 0.9253711681721909,
   'distance_to_nearest': 0.7953685305484234},
  {'kernel_size': 3918,
   'coherence_20': 1.1280109045729594,
   'distance_to_nearest': 0.8157644395371685},
  {'kernel_size': 3195,
   'coherence_20': 1.3558159228979751,
   'distance_to_nearest': 0.8453092019024341},
  {'kernel_size': 2869,
   'coherence_20': 1.5925022771882447,
   'distance_to_nearest': 0.5163896602802551},
  {'kernel_size': 3096,
   'coherence_20': 0.9345611820547499,
   'distance_to_nearest': 0.8824258051780441},
  {'kernel_size': 3406,
   'coherence_20': 1.191813786432536,
   'distance_to_nearest': 0.5825411765774876},
  {'kernel_size': 3213,
   'coherence_20': 1.0796962686600688,
   'distance_to_nearest': 0.5218784176386061}],
 [{'kernel_size': 3669,
   'coherence_20': 1.149358735569971,
   'distance_to_nearest': 0.0},
  {'kernel_size': 3826,
   'coherence_20': 1.0940593226519857,
   'distance_to_nearest': 0.8297350277944032},
  {'kernel_size': 3891,
   'coherence_20': 1.510018973038721,
   'distance_to_nearest': 0.8434147923466643},
  {'kernel_size': 3566,
   'coherence_20': 1.0424944557666154,
   'distance_to_nearest': 0.8160167830892179},
  {'kernel_size': 3153,
   'coherence_20': 0.8069537544283898,
   'distance_to_nearest': 0.8101736562618436},
  {'kernel_size': 4026,
   'coherence_20': 1.8972562345962294,
   'distance_to_nearest': 0.7623591891711462},
  {'kernel_size': 3564,
   'coherence_20': 0.9716955075766139,
   'distance_to_nearest': 0.8384707456613465},
  {'kernel_size': 1701,
   'coherence_20': 1.0173043043633647,
   'distance_to_nearest': 0.8964464055369347},
  {'kernel_size': 4146,
   'coherence_20': 0.8692359559432287,
   'distance_to_nearest': 0.8185755560490198},
  {'kernel_size': 3762,
   'coherence_20': 0.9253711681721909,
   'distance_to_nearest': 0.7953685305484234},
  {'kernel_size': 3918,
   'coherence_20': 1.1280109045729594,
   'distance_to_nearest': 0.8157644395371685},
  {'kernel_size': 3195,
   'coherence_20': 1.3558159228979751,
   'distance_to_nearest': 0.8453092019024341},
  {'kernel_size': 2869,
   'coherence_20': 1.5925022771882447,
   'distance_to_nearest': 0.5163896602802551},
  {'kernel_size': 3096,
   'coherence_20': 0.9345611820547499,
   'distance_to_nearest': 0.8824258051780441},
  {'kernel_size': 3406,
   'coherence_20': 1.191813786432536,
   'distance_to_nearest': 0.5825411765774876},
  {'kernel_size': 3213,
   'coherence_20': 1.0796962686600688,
   'distance_to_nearest': 0.5218784176386061}],
 [{'kernel_size': 3669,
   'coherence_20': 1.149358735569971,
   'distance_to_nearest': 0.0},
  {'kernel_size': 3826,
   'coherence_20': 1.0940593226519857,
   'distance_to_nearest': 0.8297350277944032},
  {'kernel_size': 3891,
   'coherence_20': 1.510018973038721,
   'distance_to_nearest': 0.8434147923466643},
  {'kernel_size': 3566,
   'coherence_20': 1.0424944557666154,
   'distance_to_nearest': 0.8160167830892179},
  {'kernel_size': 3153,
   'coherence_20': 0.8069537544283898,
   'distance_to_nearest': 0.8101736562618436},
  {'kernel_size': 4026,
   'coherence_20': 1.8972562345962294,
   'distance_to_nearest': 0.7623591891711462},
  {'kernel_size': 3564,
   'coherence_20': 0.9716955075766139,

In [95]:
optimizer._result['model_scores'][0]

{'perplexity_score': 3041.67138671875,
 'coherence_20': 0.5898700966827493,
 'diversity_euclidean': 0.062318714185795654,
 'diversity_jensenshannon': 0.6669767696232136,
 'diversity_hellinger': 0.7785279346901158,
 'diversity_cosine': 0.8602338865058863,
 'perplexity': 3041.67138671875}

In [126]:
sum(s['coherence_20'] for s in optimizer._result['bank_topic_scores'][-1]) / 10

0.9058404227165608

In [127]:
len(optimizer._result['bank_scores'])

20

In [128]:
optimizer._result['bank_scores'][-1]

{'perplexity_score': 13329.8876953125,
 'coherence_20': 0.9058404227165606,
 'diversity_euclidean': 0.05184720024244504,
 'diversity_jensenshannon': 0.6500697527850625,
 'diversity_hellinger': 0.7586476679507803,
 'diversity_cosine': 0.8126390939253648,
 'perplexity': 13329.8876953125,
 'ppl_fair': 13329.8876953125,
 'ppl_cheatty': 5741.56787109375}

In [129]:
optimizer._result['model_topic_scores']

[[{'kernel_size': 3810, 'coherence_20': 0.5225908625149936},
  {'kernel_size': 3895, 'coherence_20': 0.5331450869041109},
  {'kernel_size': 3987,
   'coherence_20': 1.284041737255726,
   'distance_to_nearest': 0.0},
  {'kernel_size': 3896, 'coherence_20': 0.5261857613384362},
  {'kernel_size': 3860, 'coherence_20': 0.3796521580255667},
  {'kernel_size': 3654, 'coherence_20': 0.5656146718404065},
  {'kernel_size': 3844, 'coherence_20': 0.44309547614289096},
  {'kernel_size': 3919, 'coherence_20': 0.5484668820539618},
  {'kernel_size': 4084, 'coherence_20': 0.5739931717770947},
  {'kernel_size': 2794, 'coherence_20': 0.5111064072825383},
  {'kernel_size': 4275, 'coherence_20': 0.5617371534777974},
  {'kernel_size': 3470, 'coherence_20': 0.6047710619718488},
  {'kernel_size': 3392, 'coherence_20': 0.6510584572257663},
  {'kernel_size': 3715,
   'coherence_20': 0.9103697786572175,
   'distance_to_nearest': 0.8389113266096888},
  {'kernel_size': 3735,
   'coherence_20': 0.7229039920008129,
   'distance_to_nearest': 0.8608185493321843},
  {'kernel_size': 3970,
   'coherence_20': 1.0416092968651998,
   'distance_to_nearest': 0.8743664527246292},
  {'kernel_size': 3651, 'coherence_20': 0.46811039620591643},
  {'kernel_size': 3609, 'coherence_20': 0.5962910863766723},
  {'kernel_size': 3740, 'coherence_20': 0.5783138756166647},
  {'kernel_size': 3564, 'coherence_20': 0.6976794919725269}],
 [{'kernel_size': 3828, 'coherence_20': 0.44106161785480386},
  {'kernel_size': 4067,
   'coherence_20': 0.7327664197315834,
   'distance_to_nearest': 0.8375291531011442},
  {'kernel_size': 3894, 'coherence_20': 0.5489067505186181},
  {'kernel_size': 3885, 'coherence_20': 0.42642241463442676},
  {'kernel_size': 4015, 'coherence_20': 0.5078624192050143},
  {'kernel_size': 3896, 'coherence_20': 0.5525580619860339},
  {'kernel_size': 3437, 'coherence_20': 0.6379665042572684},
  {'kernel_size': 4010, 'coherence_20': 0.4570750753245133},
  {'kernel_size': 4169, 'coherence_20': 0.6303872056714687},
  {'kernel_size': 3889, 'coherence_20': 1.5569487421316868},
  {'kernel_size': 3720, 'coherence_20': 0.5544740108451999},
  {'kernel_size': 4183, 'coherence_20': 0.7408619505030617},
  {'kernel_size': 3989, 'coherence_20': 0.6768216538855591},
  {'kernel_size': 3611, 'coherence_20': 0.7787406685929378},
  {'kernel_size': 3624, 'coherence_20': 1.088527865124105},
  {'kernel_size': 4130, 'coherence_20': 0.4715493692281731},
  {'kernel_size': 3991, 'coherence_20': 0.6872737762711087},
  {'kernel_size': 3508, 'coherence_20': 0.4102038751402569},
  {'kernel_size': 3957, 'coherence_20': 0.8957730240763879},
  {'kernel_size': 2663, 'coherence_20': 0.6791643502675384}],
 [{'kernel_size': 4178, 'coherence_20': 0.598795164772999},
  {'kernel_size': 3645, 'coherence_20': 0.5381166123573388},
  {'kernel_size': 3043, 'coherence_20': 0.9855507468269424},
  {'kernel_size': 3987, 'coherence_20': 0.562749567247383},
  {'kernel_size': 3825, 'coherence_20': 0.6474789824920691},
  {'kernel_size': 4057, 'coherence_20': 0.8522077140485115},
  {'kernel_size': 4508, 'coherence_20': 0.48743067628233144},
  {'kernel_size': 4045, 'coherence_20': 0.44174586034060287},
  {'kernel_size': 3485, 'coherence_20': 0.4963533961273581},
  {'kernel_size': 3363, 'coherence_20': 0.7807752784957993},
  {'kernel_size': 3686, 'coherence_20': 1.2219263690969275},
  {'kernel_size': 3774, 'coherence_20': 0.41150240264741905},
  {'kernel_size': 3380, 'coherence_20': 1.1877568770364013},
  {'kernel_size': 3676, 'coherence_20': 0.6797394054261952},
  {'kernel_size': 3832, 'coherence_20': 0.5849001653432634},
  {'kernel_size': 4021, 'coherence_20': 0.6254463167544662},
  {'kernel_size': 3763, 'coherence_20': 0.7164260736103736},
  {'kernel_size': 3889, 'coherence_20': 0.730915924306012},
  {'kernel_size': 3855, 'coherence_20': 0.5429353836335077},
  {'kernel_size': 3967, 'coherence_20': 0.5169923019788246}],
 [{'kernel_size': 3675, 'coherence_20': 0.4831046344400839},
  {'kernel_size': 3787, 'coherence_20': 0.4243032205021979},
  {'kernel_size': 4145, 'coherence_20': 0.5889700339781011},
  {'kernel_size': 4269, 'coherence_20': 0.5556636324296075},
  {'kernel_size': 3850, 'coherence_20': 0.5342278980743531},
  {'kernel_size': 3860, 'coherence_20': 1.3506456803629192},
  {'kernel_size': 3847, 'coherence_20': 0.5269218086528131},
  {'kernel_size': 3029, 'coherence_20': 0.6289457702136791},
  {'kernel_size': 3890, 'coherence_20': 0.6615200925977052},
  {'kernel_size': 4179, 'coherence_20': 0.6590229849217536},
  {'kernel_size': 3916, 'coherence_20': 0.7392126391172149},
  {'kernel_size': 3867, 'coherence_20': 0.5140361137735603},
  {'kernel_size': 4054, 'coherence_20': 0.6178876045758358},
  {'kernel_size': 3718, 'coherence_20': 0.689857406710646},
  {'kernel_size': 3545, 'coherence_20': 0.7520113288455655},
  {'kernel_size': 3513, 'coherence_20': 0.9978607575474957},
  {'kernel_size': 3900, 'coherence_20': 0.4491783278216115},
  {'kernel_size': 4129, 'coherence_20': 0.3538506667336539},
  {'kernel_size': 3834, 'coherence_20': 0.4585006655160553},
  {'kernel_size': 3939, 'coherence_20': 1.6856535377715907}],
 [{'kernel_size': 4039, 'coherence_20': 0.6527693180581653},
  {'kernel_size': 4063, 'coherence_20': 0.6212141207288859},
  {'kernel_size': 4045,
   'coherence_20': 0.9727629773002542,
   'distance_to_nearest': 0.7660882278444439},
  {'kernel_size': 3316, 'coherence_20': 0.4819448187601827},
  {'kernel_size': 3081, 'coherence_20': 0.7351537751874048},
  {'kernel_size': 3520, 'coherence_20': 0.7845233946280211},
  {'kernel_size': 3693, 'coherence_20': 0.5126247155452416},
  {'kernel_size': 3749, 'coherence_20': 0.4046712727050885},
  {'kernel_size': 3716, 'coherence_20': 0.4007975688378578},
  {'kernel_size': 3587, 'coherence_20': 0.5218953769255785},
  {'kernel_size': 3846, 'coherence_20': 0.6258086900153723},
  {'kernel_size': 3795, 'coherence_20': 0.44681416692151166},
  {'kernel_size': 4027, 'coherence_20': 0.574340828353412},
  {'kernel_size': 3760, 'coherence_20': 0.5593156231825795},
  {'kernel_size': 4143, 'coherence_20': 0.6076062606425775},
  {'kernel_size': 3871, 'coherence_20': 0.6948878748480405},
  {'kernel_size': 3672, 'coherence_20': 0.6371368099405965},
  {'kernel_size': 3710, 'coherence_20': 1.04602521224431},
  {'kernel_size': 3585, 'coherence_20': 0.5318174711020972},
  {'kernel_size': 3688, 'coherence_20': 1.3943025167171033}],
 [{'kernel_size': 3213, 'coherence_20': 0.8116092060459078},
  {'kernel_size': 4055, 'coherence_20': 0.5584894955291407},
  {'kernel_size': 3007, 'coherence_20': 0.6181500771726577},
  {'kernel_size': 3939, 'coherence_20': 0.635656743205073},
  {'kernel_size': 4352, 'coherence_20': 0.548388444390322},
  {'kernel_size': 3906, 'coherence_20': 0.4552833018883328},
  {'kernel_size': 3830, 'coherence_20': 0.9712089285836378},
  {'kernel_size': 3690, 'coherence_20': 0.5280094613612604},
  {'kernel_size': 3625, 'coherence_20': 0.4913940890046831},
  {'kernel_size': 3518, 'coherence_20': 0.5456889861541903},
  {'kernel_size': 3951, 'coherence_20': 0.6386042241818731},
  {'kernel_size': 4091, 'coherence_20': 0.9782726870538868},
  {'kernel_size': 3938, 'coherence_20': 0.518563002194695},
  {'kernel_size': 3895, 'coherence_20': 0.5818816021328943},
  {'kernel_size': 3427, 'coherence_20': 0.8809116934947679},
  {'kernel_size': 3861, 'coherence_20': 0.5602352565891381},
  {'kernel_size': 3974, 'coherence_20': 0.5464902712194437},
  {'kernel_size': 3837, 'coherence_20': 0.8533918296670424},
  {'kernel_size': 3784, 'coherence_20': 0.43206286444198694},
  {'kernel_size': 3607, 'coherence_20': 0.6467267388655009}],
 [{'kernel_size': 4378, 'coherence_20': 0.5640888290321826},
  {'kernel_size': 3950, 'coherence_20': 0.6568326303268947},
  {'kernel_size': 3789, 'coherence_20': 0.5365878902731025},
  {'kernel_size': 3721, 'coherence_20': 0.6292605094384683},
  {'kernel_size': 3769, 'coherence_20': 0.42558147347446135},
  {'kernel_size': 3447, 'coherence_20': 0.6184848713205785},
  {'kernel_size': 4274, 'coherence_20': 0.47989668983368633},
  {'kernel_size': 3832, 'coherence_20': 0.8973138770837534},
  {'kernel_size': 3966, 'coherence_20': 0.48682484916205565},
  {'kernel_size': 3995, 'coherence_20': 0.5068636662880148},
  {'kernel_size': 3604, 'coherence_20': 0.43672790095967123},
  {'kernel_size': 3808, 'coherence_20': 0.6824286175918475},
  {'kernel_size': 3557, 'coherence_20': 0.709811749151446},
  {'kernel_size': 2809, 'coherence_20': 0.7383277080212547},
  {'kernel_size': 3729, 'coherence_20': 0.7839553181739237},
  {'kernel_size': 3855, 'coherence_20': 0.7895368740221493},
  {'kernel_size': 3744, 'coherence_20': 0.5320672208126617},
  {'kernel_size': 4110, 'coherence_20': 0.6253574506361504},
  {'kernel_size': 3926, 'coherence_20': 0.9602524828117974},
  {'kernel_size': 3686, 'coherence_20': 0.5145527613904912}],
 [{'kernel_size': 3732, 'coherence_20': 0.7747397801255682},
  {'kernel_size': 3601, 'coherence_20': 1.0663369595402357},
  {'kernel_size': 3805, 'coherence_20': 0.47089334419932477},
  {'kernel_size': 3769, 'coherence_20': 0.5069736521867031},
  {'kernel_size': 3788, 'coherence_20': 0.493257973619543},
  {'kernel_size': 3882, 'coherence_20': 0.4079001746009254},
  {'kernel_size': 4086, 'coherence_20': 0.6237326854482836},
  {'kernel_size': 3919, 'coherence_20': 0.6202987678171337},
  {'kernel_size': 3399, 'coherence_20': 0.7870589032506123},
  {'kernel_size': 4104, 'coherence_20': 0.5202264892932144},
  {'kernel_size': 3541, 'coherence_20': 0.5314672669776813},
  {'kernel_size': 4051, 'coherence_20': 1.0406543466683416},
  {'kernel_size': 3694, 'coherence_20': 0.6218681912453986},
  {'kernel_size': 3697, 'coherence_20': 0.5160570677202646},
  {'kernel_size': 4103, 'coherence_20': 0.6068697620521412},
  {'kernel_size': 3607, 'coherence_20': 0.7003394385740965},
  {'kernel_size': 3945, 'coherence_20': 0.4491917600546622},
  {'kernel_size': 4111, 'coherence_20': 0.7051250467000316},
  {'kernel_size': 3878, 'coherence_20': 0.6326834651459782},
  {'kernel_size': 2887, 'coherence_20': 0.6383905792266019}],
 [{'kernel_size': 3465, 'coherence_20': 1.0368209290066903},
  {'kernel_size': 3787, 'coherence_20': 0.8218863745148567},
  {'kernel_size': 3924, 'coherence_20': 0.4581073402023177},
  {'kernel_size': 3388, 'coherence_20': 0.45912130298956066},
  {'kernel_size': 4059, 'coherence_20': 0.6083193226126178},
  {'kernel_size': 3626, 'coherence_20': 0.8912166817273709},
  {'kernel_size': 4295, 'coherence_20': 0.6347713461483303},
  {'kernel_size': 2821,
   'coherence_20': 0.7763449707418218,
   'distance_to_nearest': 0.8655224863232},
  {'kernel_size': 3632, 'coherence_20': 0.5587937998787308},
  {'kernel_size': 3583, 'coherence_20': 0.6106452740628856},
  {'kernel_size': 4408, 'coherence_20': 0.5498515549498919},
  {'kernel_size': 3956, 'coherence_20': 0.514471095605828},
  {'kernel_size': 3874, 'coherence_20': 0.43815678980584083},
  {'kernel_size': 3880, 'coherence_20': 0.8309212360875134},
  {'kernel_size': 3934, 'coherence_20': 0.6997464106886786},
  {'kernel_size': 3905, 'coherence_20': 0.5397265548972031},
  {'kernel_size': 4090, 'coherence_20': 0.43008498559277564},
  {'kernel_size': 3823, 'coherence_20': 0.442819109978498},
  {'kernel_size': 4034, 'coherence_20': 0.5853625627271791},
  {'kernel_size': 3575, 'coherence_20': 0.5627940865525398}],
 [{'kernel_size': 4069, 'coherence_20': 0.5519107818581486},
  {'kernel_size': 3753, 'coherence_20': 0.6360004845055972},
  {'kernel_size': 4513, 'coherence_20': 0.4179963924721531},
  {'kernel_size': 3702, 'coherence_20': 0.46163351628848615},
  {'kernel_size': 3872, 'coherence_20': 0.4919763842353582},
  {'kernel_size': 4100, 'coherence_20': 0.6297793566389219},
  {'kernel_size': 3839, 'coherence_20': 0.5024710981482737},
  {'kernel_size': 3795, 'coherence_20': 1.1848315304935597},
  {'kernel_size': 2699, 'coherence_20': 0.6499095350129194},
  {'kernel_size': 4357, 'coherence_20': 0.5831087799769489},
  {'kernel_size': 4079, 'coherence_20': 0.48670860560824564},
  {'kernel_size': 3854, 'coherence_20': 0.45480271547853973},
  {'kernel_size': 3947, 'coherence_20': 0.6702267890969852},
  {'kernel_size': 3931, 'coherence_20': 0.4075837562677955},
  {'kernel_size': 3603, 'coherence_20': 0.5815680727904765},
  {'kernel_size': 3918,
   'coherence_20': 0.7995905134800576,
   'distance_to_nearest': 0.8141127776215409},
  {'kernel_size': 4056, 'coherence_20': 0.5254932860791184},
  {'kernel_size': 4078, 'coherence_20': 0.625656292778972},
  {'kernel_size': 3897, 'coherence_20': 0.94843522812917},
  {'kernel_size': 3484, 'coherence_20': 0.7368992863179382}],
 [{'kernel_size': 3640, 'coherence_20': 0.5528205877190815},
  {'kernel_size': 3832, 'coherence_20': 0.8282478845290367},
  {'kernel_size': 4104, 'coherence_20': 0.8069240925114898},
  {'kernel_size': 3622, 'coherence_20': 1.0389759763273663},
  {'kernel_size': 4087, 'coherence_20': 0.46733115867372926},
  {'kernel_size': 3194, 'coherence_20': 0.816230326956684},
  {'kernel_size': 4171, 'coherence_20': 0.5932650131542504},
  {'kernel_size': 3902, 'coherence_20': 0.4600359437401731},
  {'kernel_size': 3702, 'coherence_20': 0.7272922609262789},
  {'kernel_size': 4322, 'coherence_20': 0.42832662374303926},
  {'kernel_size': 3569,
   'coherence_20': 0.7820075760413158,
   'distance_to_nearest': 0.6797221326218758},
  {'kernel_size': 3506, 'coherence_20': 0.5674099436672796},
  {'kernel_size': 3351, 'coherence_20': 0.4445388609850329},
  {'kernel_size': 3481, 'coherence_20': 0.5430048845234163},
  {'kernel_size': 3557, 'coherence_20': 0.6844299243930583},
  {'kernel_size': 3961, 'coherence_20': 0.5112796489579948},
  {'kernel_size': 3851, 'coherence_20': 0.5356090279495954},
  {'kernel_size': 3663, 'coherence_20': 0.509153739537626},
  {'kernel_size': 3918, 'coherence_20': 1.0453528950495272},
  {'kernel_size': 4087, 'coherence_20': 0.6564213229689195}],
 [{'kernel_size': 3763, 'coherence_20': 0.7453852727246247},
  {'kernel_size': 3792, 'coherence_20': 0.5983008588006337},
  {'kernel_size': 4026, 'coherence_20': 0.7576092523251606},
  {'kernel_size': 3254, 'coherence_20': 0.46429114763072543},
  {'kernel_size': 3542, 'coherence_20': 0.7332807319697603},
  {'kernel_size': 3542, 'coherence_20': 0.675266817237783},
  {'kernel_size': 3986, 'coherence_20': 0.47340673490551816},
  {'kernel_size': 3931, 'coherence_20': 0.6149528708729993},
  {'kernel_size': 3833, 'coherence_20': 0.6438903096725612},
  {'kernel_size': 3493, 'coherence_20': 1.5412907625579608},
  {'kernel_size': 3897, 'coherence_20': 0.5218714552334861},
  {'kernel_size': 3965, 'coherence_20': 0.36337473089244504},
  {'kernel_size': 3365, 'coherence_20': 0.6702872515937011},
  {'kernel_size': 3680, 'coherence_20': 0.40599743793039783},
  {'kernel_size': 4137, 'coherence_20': 0.5317751777537818},
  {'kernel_size': 3820, 'coherence_20': 0.6484530071296591},
  {'kernel_size': 3979, 'coherence_20': 0.3912140448532853},
  {'kernel_size': 3825, 'coherence_20': 0.5633109497626448},
  {'kernel_size': 3213, 'coherence_20': 0.4083296823820877},
  {'kernel_size': 3594,
   'coherence_20': 1.0632176527869015,
   'distance_to_nearest': 0.512942896142544}],
 [{'kernel_size': 4430, 'coherence_20': 0.6210189759093392},
  {'kernel_size': 4062, 'coherence_20': 0.42244833677360233},
  {'kernel_size': 4035, 'coherence_20': 0.7148880393516287},
  {'kernel_size': 3707, 'coherence_20': 0.861145984447935},
  {'kernel_size': 4155, 'coherence_20': 0.5031512513677524},
  {'kernel_size': 4088, 'coherence_20': 0.9789608655464466},
  {'kernel_size': 4006, 'coherence_20': 0.4533023288378667},
  {'kernel_size': 3882, 'coherence_20': 0.7644801267827945},
  {'kernel_size': 4077, 'coherence_20': 0.5661710157058601},
  {'kernel_size': 4114, 'coherence_20': 0.5226926298571258},
  {'kernel_size': 3697, 'coherence_20': 0.5309551936994685},
  {'kernel_size': 3218, 'coherence_20': 0.6680701445821756},
  {'kernel_size': 3665, 'coherence_20': 0.4795341624472826},
  {'kernel_size': 3791, 'coherence_20': 0.6298559917088357},
  {'kernel_size': 3888, 'coherence_20': 0.5536535123343636},
  {'kernel_size': 3735, 'coherence_20': 0.4829902364574231},
  {'kernel_size': 3956, 'coherence_20': 0.8435376559458758},
  {'kernel_size': 3666, 'coherence_20': 0.5847799630324549},
  {'kernel_size': 3464, 'coherence_20': 0.4694361862554589},
  {'kernel_size': 3814, 'coherence_20': 1.0879376584720868}],
 [{'kernel_size': 3658, 'coherence_20': 0.6231571603430881},
  {'kernel_size': 3749, 'coherence_20': 0.4549616043875508},
  {'kernel_size': 4160,
   'coherence_20': 0.7482898099653809,
   'distance_to_nearest': 0.7455967832752015},
  {'kernel_size': 3787, 'coherence_20': 0.5754496534041686},
  {'kernel_size': 3728, 'coherence_20': 0.48267868734721747},
  {'kernel_size': 3223, 'coherence_20': 0.516507295932109},
  {'kernel_size': 3585, 'coherence_20': 0.8725552268315139},
  {'kernel_size': 3458, 'coherence_20': 1.5924521289569302},
  {'kernel_size': 3861, 'coherence_20': 0.5103621035223012},
  {'kernel_size': 3782, 'coherence_20': 0.5720762517797007},
  {'kernel_size': 4094, 'coherence_20': 0.7795933136652584},
  {'kernel_size': 3992, 'coherence_20': 0.5881912713948532},
  {'kernel_size': 3749, 'coherence_20': 1.2847859352764686},
  {'kernel_size': 3054, 'coherence_20': 0.6778845991451188},
  {'kernel_size': 4029, 'coherence_20': 0.6923039953299563},
  {'kernel_size': 4062, 'coherence_20': 0.5105991819640876},
  {'kernel_size': 3639, 'coherence_20': 0.6481260426687158},
  {'kernel_size': 3812, 'coherence_20': 0.7579155319490068},
  {'kernel_size': 3721, 'coherence_20': 0.5746367053061961},
  {'kernel_size': 4124, 'coherence_20': 0.4825548729703502}],
 [{'kernel_size': 4360, 'coherence_20': 0.5491591079438338},
  {'kernel_size': 3387, 'coherence_20': 0.42904906596114106},
  {'kernel_size': 3526, 'coherence_20': 0.6612592510936444},
  {'kernel_size': 3559, 'coherence_20': 1.2712758218416602},
  {'kernel_size': 4152, 'coherence_20': 0.6379570122770551},
  {'kernel_size': 3775, 'coherence_20': 0.47285862522895106},
  {'kernel_size': 3693, 'coherence_20': 0.5364554583123545},
  {'kernel_size': 4061, 'coherence_20': 0.5227327917779301},
  {'kernel_size': 3170, 'coherence_20': 0.6967691050592921},
  {'kernel_size': 3367,
   'coherence_20': 0.909087107933306,
   'distance_to_nearest': 0.5808406101314469},
  {'kernel_size': 3587, 'coherence_20': 0.7833199162892803},
  {'kernel_size': 3662, 'coherence_20': 1.0998048336131596},
  {'kernel_size': 3900, 'coherence_20': 0.5110951799889307},
  {'kernel_size': 3668, 'coherence_20': 0.4017429139659767},
  {'kernel_size': 4166, 'coherence_20': 0.5319221940278723},
  {'kernel_size': 4356, 'coherence_20': 0.4009940377335449},
  {'kernel_size': 4097, 'coherence_20': 0.576335605395472},
  {'kernel_size': 3960, 'coherence_20': 1.2787270137459632},
  {'kernel_size': 3845, 'coherence_20': 0.5504883073975602},
  {'kernel_size': 3779, 'coherence_20': 0.664791101257335}],
 [{'kernel_size': 4388, 'coherence_20': 0.3999436782174392},
  {'kernel_size': 3968, 'coherence_20': 0.5837656776447016},
  {'kernel_size': 4190, 'coherence_20': 0.4757448810207889},
  {'kernel_size': 4103, 'coherence_20': 0.6881480675321654},
  {'kernel_size': 3533, 'coherence_20': 0.5956594701522606},
  {'kernel_size': 4096, 'coherence_20': 0.45924228384351595},
  {'kernel_size': 3682, 'coherence_20': 0.9584369081931046},
  {'kernel_size': 3496, 'coherence_20': 1.126641154687045},
  {'kernel_size': 3954, 'coherence_20': 0.7671840878097023},
  {'kernel_size': 3470, 'coherence_20': 1.6120754079057582},
  {'kernel_size': 4161, 'coherence_20': 0.7698412403948897},
  {'kernel_size': 3821, 'coherence_20': 0.41527076457631734},
  {'kernel_size': 3899, 'coherence_20': 0.49673258431847506},
  {'kernel_size': 3753, 'coherence_20': 0.685603904832769},
  {'kernel_size': 3424, 'coherence_20': 0.5546698614070789},
  {'kernel_size': 3496, 'coherence_20': 0.48722162503166483},
  {'kernel_size': 3764, 'coherence_20': 0.4037830315915261},
  {'kernel_size': 4243, 'coherence_20': 0.6290594380826326},

In [130]:
! echo $SEARCH_RESULTS_FOLDER_PATH
! ls $SEARCH_RESULTS_FOLDER_PATH

./RTL_Wiki_Person__internals/result2
bank__0  search_result__0.json

In [131]:
! ls Good_RU_Wiki__internals

batches  dict.dict  result  result2  vw.txt

In [96]:
optimizer._save_file_path

'./RTL_Wiki_Person__internals/result2_50/search_result__0.json'