# TopicBank: Bank Creation Experiment

Here we are going to collect interpretable topics (automatically, using topic coherence) from multiple model training.
These topics constitute *topic bank*.
And then the topic bank is going to be used for estimating topic models quality in the notebook [TopicBank-Experiment: Model Validation](TopicBank-Experiment-ModelValidation.ipynb).

The process is repeated for several datasets (some of them are already downloadable using [TopicNet](https://github.com/machine-intelligence-laboratory/TopicNet) library).

# Contents<a id="contents"></a>

* [Data](#data)
    * [Coocs](#coocs)
        * [Lower Memory Consumption (or a Bit of Shamanism. Part 1)](#optimizing-memory)
    * [Documents for Coherence Scores](#docs-for-cohs)
        * [Lower Time Consumption in Case of Big Datasets (or a Bit of Shamanism. Part 2)](#optimizing-time)
* [Experiment](#experiment)
    * [Scores](#scores)
    * [Bank Creation](#bank-creation)
* [Postprocessing](#postprocessing)

In [1]:
# General imports

import dill
import itertools
import json
import numpy as np
import os
import pandas as pd
import sys

from enum import Enum
from scipy.stats import gaussian_kde
from matplotlib import pyplot as plt
from tqdm import tqdm
from typing import (
    Dict,
    Iterable,
)

%matplotlib inline

In [2]:
# Making `topnum` module visible for Python

sys.path.insert(0, '../OptimalNumberOfTopics')

In [3]:
# Optimal number of topics

from topicnet.cooking_machine import Dataset

from topnum.data.vowpal_wabbit_text_collection import VowpalWabbitTextCollection
from topnum.scores import (
    PerplexityScore,
    SparsityPhiScore,
    SparsityThetaScore,
)
from topnum.scores.diversity_score import DiversityScore, KNOWN_METRICS
from topnum.scores._base_coherence_score import (
    SpecificityEstimationMethod,
    TextType,
    WordTopicRelatednessType,
)
from topnum.scores.intratext_coherence_score import ComputationMethod
from topnum.search_methods import TopicBankMethod
from topnum.search_methods.topic_bank.topic_bank import TopicBank
from topnum.search_methods.topic_bank.one_model_train_funcs import (
    default_train_func,

    # Functions below are not used (but could have been)

#     regularization_train_func,
#     specific_initial_phi_train_func,
#     background_topics_train_func,

)

## Data<a id="data"></a>

<div style="text-align: right">Back to <a href=#contents>Contents</a></div>

Loading data from disk, creating batches, dictionary, gathering cooccurrence statistics...

In [4]:
DATA_FOLDER_PATH = '/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/dataset_manager'

In [5]:
sorted(os.listdir(DATA_FOLDER_PATH))

['20NG.csv',
 '20NG__internals',
 'Brown',
 'Brown_BOW.csv',
 'Brown_NOOW.csv',
 'MKB10.csv',
 'MKB10__internals',
 'RTL_Wiki.csv',
 'RTL_Wiki_person.csv',
 'RTL_Wiki_person__internals',
 'Reuters',
 'Reuters_BOW.csv',
 'Reuters_NOOW.csv',
 'WikiRef-220',
 '__init__.py',
 '__pycache__',
 'api.py',
 'postnauka.csv',
 'postnauka__internals',
 'ruwiki_good.txt',
 'ruwiki_good__internals',
 'wiki_ref220_bow.csv',
 'wiki_ref220_natural_order.csv']

In [6]:
class DatasetName(Enum):
    POSTNAUKA = 'Post_Science'
    # REUTERS = 'Reuters'
    # BROWN = 'Brown'
    TWENTY_NEWSGROUPS = '20_Newsgroups'
    GOOD_RU_WIKI = 'Good_RU_Wiki'

In [7]:
DATASET_NAME_TO_DATASET_FILE_PATH = {
    DatasetName.POSTNAUKA: os.path.join(
        DATA_FOLDER_PATH, 'postnauka.csv'
    ),
    # DatasetName.REUTERS: os.path.join(
    #     DATA_FOLDER_PATH, 'Reuters.csv'
    # ),
    # DatasetName.BROWN: os.path.join(
    #     DATA_FOLDER_PATH, 'Brown.csv'
    # ),
    DatasetName.TWENTY_NEWSGROUPS: os.path.join(
        DATA_FOLDER_PATH, '20NG.csv'
    ),
    # DatasetName.AG_NEWS: os.path.join(
    #     DATA_FOLDER_PATH, 'AG_News.csv'
    # ),
    # DatasetName.WATAN: os.path.join(
    #     DATA_FOLDER_PATH, 'Watan2004.csv'
    # ),
    # DatasetName.HABRAHABR: os.path.join(
    #     DATA_FOLDER_PATH, 'Habrahabr.csv'
    # ),
    DatasetName.GOOD_RU_WIKI: os.path.join(
        DATA_FOLDER_PATH, 'ruwiki_good.txt'
    ),
}

In [8]:
DATASET_NAME = DatasetName.GOOD_RU_WIKI  # select a dataset here

DATASET_FILE_PATH = DATASET_NAME_TO_DATASET_FILE_PATH[DATASET_NAME]

Checking if all OK with data, what modalities does the collection have.

In [9]:
! head -n 2 $DATASET_FILE_PATH

Санкт-Петербург |@lemmatized год:301 петроград:7 ленинград:18 численность:14 население:33 город:212 россия:32 .:677 федеральный:15 значение:8 административный:5 центр:29 округа:3 ленинградский:16 область:6 основать:5 царь:3 <person>:195 являться:34 столица:19 российский:35 государство:9 назвать:4 честь:6 святой:11 небесный:2 покровитель:2 основатель:3 время:17 стать:25 большой:23 ассоциироваться:1 имя:34 исторически:1 культурно:1 связать:2 рождение:1 империя:7 вхождение:1 современный:7 история:11 роль:5 европейский:3 великий:5 держава:1 расположить:11 страна:16 побережье:4 финский:16 залив:15 устье:4 река:21 нева:31 находиться:17 конституционный:1 суд:5 федерация:14 геральдический:2 совет:8 президент:1 орган:6 власть:11 межпарламентский:3 ассамблея:3 снг:2 разместить:1 главный:9 командование:2 флот:1 штаб:2 западный:8 военный:8 вооружённый:3 сила:6 быть:74 революция:6 февральский:2 октябрьский:6 ход:4 отечественный:4 война:10 блокада:7 результат:12 миллион:37 человек:39 погибнуть:4 объявить:1 герой:4 состояние:9 состав:8 воинский:2 слава:1 кронштадт:3 колпино:3 чело:2 северный:15 мир:10 миллионник:1 полностью:6 европа:12 житель:17 инновационный:1 сценарий:1 стратегия:2 развитие:15 предполагать:1 что:10 составить:27 городской:20 агломерация:2 площадь:29 расширение:2 москва:11 второе:3 важный:8 экономический:10 научный:6 культурный:12 крупный:26 транспортный:7 узел:4 исторический:8 связанный:6 комплекс:6 памятник:15 входить:2 список:5 объект:10 всемирный:3 наследие:8 юнеско:3 туризм:3 наиболее:5 значимый:1 эрмитаж:2 кунсткамера:3 мариинский:5 театр:14 национальный:8 библиотека:5 русский:18 музей:14 петропавловский:11 крепость:12 исаакиевский:6 собор:26 проспект:24 сохранение:3 направить:1 программа:3 посетить:3 турист:7 предел:2 приневский:1 низменность:1 координата:1 занимать:5 прилегать:1 невский:18 губа:9 многочисленный:4 остров:29 дельта:6 протянуться:1 километр:5 высота:7 уровень:10 море:5 район:16 север:3 юг:5 высокий:14 место:22 черта:5 дудергофский:2 красный:3 село:3 максимальный:1 территория:22 нулевой:2 отметка:2 система:8 отсчёт:2 глубина:1 служащий:2 исходный:1 пункт:2 нивелирный:1 сеть:8 начало:12 xx:6 век:26 проходить:7 обсерватория:4 меридиан:1 использоваться:2 качество:6 географический:3 долгота:1 карта:1 протяжённость:3 водоток:1 достигать:1 водный:9 поверхность:5 составлять:22 существование:2 гидрологический:1 претерпеть:1 существенный:3 изменение:3 строительство:13 низок:1 болотистый:1 потребовать:1 сооружение:12 канал:18 пруд:1 осушение:1 вынуть:1 земля:5 повышение:2 конец:4 xix:5 состоять:3 образующая:1 мера:4 многие:8 водоём:2 терять:1 первоначальный:5 загрязняться:1 засыпаться:1 засыпка:1 проток:1 рукав:3 сократиться:2 основный:8 магистраль:3 впадать:1 относиться:2 балтийский:11 значительный:11 малый:4 средний:6 невки:2 фонтанка:3 мойка:2 екатерингофка:1 крестовка:1 карповка:1 ждановка:1 пряжка:1 кронверкский:1 пролив:1 морской:19 обводный:1 основной:4 приток:2 слева:2 ижора:2 славянка:1 мурзинка:1 справа:2 охт:2 чёрный:2 речка:1 васильевский:12 петроградский:3 крестовский:5 декабрист:1 котлин:2 перекинуть:1 мост:11 считать:5 промышленный:10 предприятие:19 пешеходный:1 разводный:1 количество:10 часть:18 некогда:1 пригород:4 пушкин:3 петергоф:5 павловск:2 длинный:2 обуховский:3 вантовый:2 полный:3 длина:2 мостовый:1 переход:1 широкий:3 синий:1 полоса:1 линия:4 железный:8 дорога:12 левобережье:1 превышать:4 подверженный:1 опасность:2 наводнение:14 главное:3 образ:5 ветровый:1 нагон:1 вод:13 восточный:4 катастрофический:1 характер:2 носить:1 подъесть:1 выше:4 ординар:3 затопить:1 трехсотлетний:1 петербург:30 зарегистрировать:7 разный:3 источник:7 опасный:2 подняться:5 сантиметр:5 кронштадтский:3 футшток:1 вступить:5 строить:5 защитный:1 дамба:4 впервые:4 задействовать:1 закрыть:1 прогноз:1 специалист:1 пятёрка:1 величина:5 наблюдение:2 вода:9 мочь:6 уйти:4 предотвратить:1 ущерб:2 миллиард:7 рубль:15 климат:3 умеренный:1 переходный:1 умеренно:2 континентальный:2 тип:1 объясняться:1 положение:1 атмосферный:2 циркуляция:1 характерный:4 обусловливаться:1 сравнительно:1 небольшой:2 поступать:1 земной:1 атмосфера:2 солнечный:6 тепло:2 классификация:1 кеппена:1 классифицироваться:1 как:23 влажный:2 влияние:1 циклон:1 давать:4 жаркое:1 короткий:1 лето:1 холодный:1 сырой:1 зима:1 суммарный:4 радиация:5 маленький:3 украина:1 вдвое:1 азия:1 бывать:1 среднее:5 протяжение:2 преобладать:6 облачный:1 пасмурный:1 погода:1 рассеянный:1 освещение:1 продолжительность:3 меняться:1 часы:2 минута:3 наблюдаться:4 называть:4 белые:1 ночь:5 наступать:1 заканчиваться:1 когда:2 солнце:1 опускаться:1 горизонт:1 вечерний:2 сумерки:1 практически:3 сливаться:1 утренний:1 сложность:1 годовой:2 амплитуда:1 сумма:2 прямая:4 горизонтальный:1 ясный:1 небо:1 мдж:3 облачность:1 уменьшать:1 приход:1 среднегодовой:1 частый:1 смена:3 воздушный:2 масса:1 обусловить:1 степень:1 циклонический:1 деятельность:3 летом:2 ветер:1 зимой:1 петербургский:18 метеостанция:1 располагать:1 дать:3 температура:1 период:5 низкий:2 зелёный:2 насаждение:3 приходиться:4 тысяча:53 га:1 парковый:4 сад:4 сквер:1 бульвар:1 озеленить:1 улица:11 парка:5 различный:5 ландшафтный:1 условие:4 нижний:1 верхний:1 терраса:1 стрельна:2 моренный:1 равнина:1 холм:1 шуваловский:1 парк:5 осиновый:1 роща:1 основа:5 ряд:7 естественный:2 леса:1 пора:1 сохранить:1 породный:1 сосновка:1 удельный:2 создать:8 послевоенный:1 разбитый:1 где:6 древесный:1 растительность:1 фактически:1 отсутствовать:1 московский:15 победа:3 приморский:5 окраина:6 сохраниться:3 лесной:6 массив:1 остаться:3 подзона:1 южный:7 тайга:1 юнтоловский:2 дача:1 ржевский:1 лесопарк:1 островок:1 вдоль:2 охта:3 таллинский:2 шоссе:12 дорогой:1 существовать:2 семь:2 особо:2 охранять:2 природный:4 государственный:32 заказник:2 природа:2 комаровский:1 берег:3 стрельнинский:1 сергиевка:1 генеральный:10 план:11 планироваться:2 появление:3 министерство:4 ресурс:1 экология:1 экологический:2 рейтинг:6 занять:3 действовать:17 автоматический:1 станция:12 мониторинг:1 воздух:1 выброс:5 тонна:8 вредный:2 вещество:2 душить:2 килограмм:1 единица:3 транспорт:9 сравнение:2 предыдущий:4 увеличиться:1 стационарный:2 неудовлетворительный:2 загрязнить:1 сток:1 нея:2 сливать:1 отход:5 сотня:1 активно:2 транспортироваться:1 нефтепродукт:3 ежегодно:1 попадать:1 загрязнять:1 комитет:4 природопользование:1 фиксировать:1 акватория:2 разлив:1 роспотребнадзор:1 пляж:1 признать:2 пригодный:1 купание:1 образоваться:2 твёрдый:1 бытовой:2 промышленность:7 разнообразный:2 производство:6 представлять:1 серьёзный:1 окружающий:1 iii:1 класс:1 свозиться:1 утилизация:1 токсичный:1 продукт:6 химический:4 медицинский:4 полигон:1 бора:1 тосненский:1 ввод:2 защита:4 произойти:4 уменьшение:1 водообмен:1 частью:2 дополнительный:3 вклад:2 увеличение:1 концентрация:1 биоген:1 совокупность:2 неудачный:2 выбор:3 очистный:5 загрязнённость:1 грунт:2 некоторый:7 беспокойство:1 вызывать:1 начаться:10 постепенный:1 заболачивание:1 мелководный:1 гниение:1 остаток:1 растение:1 привести:2 эвтрофикация:1 исключение:2 обширный:3 участок:2 захоронить:1 соединение:1 пребывание:1 прослеживаться:1 таяние:1 ледник:1 покрывать:1 примерно:1 лёд:2 отступить:1 вслед:1 прислать:1 сведение:1 славянин:1 ильменский:1 словено:1 кривич:1 известный:4 viii:2 ix:2 заниматься:2 подсечный:1 земледелие:1 скотоводство:1 охота:1 рыбалка:1 совершать:1 набег:1 народ:1 войти:4 древнерусский:1 великое:5 новгород:1 название:23 водскай:1 пятина:1 местность:1 именоваться:1 карельский:1 ижорский:4 xiii:1 путь:5 варяг:1 грек:1 скандинавия:2 византия:1 новгородский:4 республика:4 постоянно:2 вести:1 швед:2 впадение:2 состояться:3 сражение:1 ополчение:1 князь:1 шведский:3 войско:2 построить:17 ландскрон:2 спустя:1 взять:2 объединить:1 дружина:1 новгородец:1 местный:2 карел:1 срыть:1 основание:4 бывший:3 долгий:2 торжище:1 есть:3 рынок:6 xv:1 присоединить:1 княжество:1 поражение:1 швеция:4 столбовский:1 ингерманландия:1 торговый:4 ниена:2 ниеншанца:1 долина:1 отвоевать:1 ништадтский:1 мирный:1 договор:1 неподалёку:1 заложить:2 днём:1 датироваться:1 закладка:1 первое:7 заячий:2 огонь:2 орудие:2 перекрывать:1 фарватер:1 рубеж:1 новый:14 придавать:1 стратегический:1 обеспечение:1 четверть:2 xviii:9 писаться:1 сан:4 бурх:3 специальный:4 акт:2 определять:3 письмо:2 официальный:7 газета:6 ведомость:5 упоминаться:3 соответствие:5 голландский:3 вариант:6 написание:3 зафиксировать:1 десять:1 гостиный:2 двор:6 троицкий:1 церковь:12 множество:2 служебный:1 здание:29 ремесленный:1 слобода:2 адмиралтейский:6 верфь:5 открытый:8 сторона:8 левый:1 дальнейший:3 галерный:1 зимний:6 летний:3 дворец:31 провозгласить:1 лицо:3 царский:6 селиться:1 немой:4 переехать:2 правительствующий:1 сенат:3 указ:9 создаваться:3 инженерный:3 артиллерийский:3 школа:5 издать:3 создание:4 начать:8 застраиваться:2 выборгский:5 развернуть:1 пригородный:1 екатерингоф:1 госпиталь:2 смольный:8 литейный:4 водяной:1 пильный:1 мельница:2 кирпичный:1 восковыя:1 пороховой:2 оружейный:1 шпалерный:1 кожевенный:1 завод:20 пищевой:4 перевести:1 монетный:1 академия:17 наука:7 выходить:1 пожар:3 середина:10 петровский:3 ветхий:2 уничтожить:2 выгореть:1 деревянный:1 императрица:1 комиссия:4 строение:4 возглавлять:2 еропкина:1 утверждаться:1 идея:2 трехлучевой:1 адмиралтейство:7 становиться:3 композиционный:1 отводиться:1 целый:2 учебный:7 заведение:8 институт:13 благородный:1 девица:1 императорский:2 художество:3 горный:2 училище:7 народный:3 подготовка:1 учитель:1 пришлый:1 каменный:2 регулировать:1 застройка:8 набережная:4 малое:4 формирование:3 архитектурный:8 ансамбль:8 центральный:9 гранитный:1 обогнать:1 православный:5 иноверческий:1 насчитываться:2 переулок:1 дом:20 замостить:1 булыжник:1 покрыть:2 поперечный:1 доска:1 заведовать:1 всесословный:2 путём:1 дума:2 корпус:4 инженер:2 сообщение:4 родить:2 образование:9 царскосельский:2 лицей:2 разрушительный:1 подсчёт:1 материальный:1 оцениваться:1 многий:1 сенатский:3 совершить:1 попытка:2 переворот:1 цель:1 упразднение:1 самодержавие:1 половина:3 закончить:3 оформление:1 дворцовый:4 александринский:4 михайловский:6 стрелка:4 трудиться:1 реконструкция:3 синод:2 дж:3 кваренга:2 проект:4 де:2 томон:2 биржа:6 ростральный:1 колонна:2 казанский:5 казначейство:1 монферран:2 александровский:4 фабрика:3 банк:5 столетие:1 путиловский:1 расти:3 индустриальный:2 жилой:3 нарвский:1 застава:1 формироваться:4 плотный:1 многоэтажный:1 доходный:5 пустить:1 паровой:2 машина:4 спустить:2 пароход:1 чугунолитейный:1 выпуск:2 подвижный:1 выпустить:1 паровоз:1 событие:7 поезд:3 вскоре:2 регулярный:1 вокзал:9 николаевский:1 варшавский:1 финляндский:3 завершить:1 постройка:2 километровый:1 порт:10 гутуевский:1 водоснабжение:3 прокладываться:1 водопровод:1 появиться:4 телефонный:2 аппарат:1 поздний:5 трамвай:2 открыться:2 пулковский:5 общество:2 свыше:5 двадцать:1 перепись:3 мировой:6 превысить:2 лондон:2 париж:2 считаться:1 кровавый:1 воскресение:1 парламент:1 объесть:7 достигнуть:1 занятый:1 продукция:7 электрический:2 изделие:6 текстиль:1 энергооснащённость:1 столичный:2 индустрия:2 обеспечивать:3 электроустановка:1 тэц:10 обучаться:1 студент:1 сильно:1 повлиять:1 судьба:1 волна:1 антигерманский:1 настроение:1 ii:5 переименовать:3 измениться:1 смысл:1 называться:3 проблема:1 снабжение:1 обычный:1 явление:2 очередь:3 волнение:1 завершиться:1 отречение:1 император:4 падение:1 монархия:1 временной:1 правительство:7 социалистический:1 перейти:1 рука:1 большевик:1 советский:5 гражданский:2 близость:1 фронт:3 германский:1 армия:1 лишиться:1 статус:3 смерть:2 всесоюзный:2 съезд:4 ссср:5 удовлетворить:2 просьба:2 петросовет:2 постановление:3 революционный:1 рабочий:1 переселить:1 урегулирование:1 начинаться:4 жилищный:3 жилмассив:2 благоустроить:1 выход:2 оконечность:2 стадион:7 киров:6 рсфср:7 выделить:1 отдельный:1 республиканский:1 подчинение:1 разработать:2 предусматривать:2 направление:2 граница:1 пересечение:1 международный:21 дуговой:1 утвердить:3 квартал:2 ивановский:1 культура:12 иметься:5 аэропорт:4 пулково:5 жертва:2 убийство:1 секретарь:1 обком:1 горком:1 вкп:2 член:1 политбюро:1 цк:1 положить:2 кировский:3 поток:1 террор:1 приходить:1 героизм:1 стойкость:1 ленинградец:5 проявиться:1 противник:1 выйти:2 ладожский:3 озеро:2 захватить:1 шлиссельбург:1 контроль:2 исток:1 блокировать:1 суши:1 гитлеровский:1 германия:3 финляндия:3 удержать:1 оказать:2 огромный:2 помощь:2 нюрнбергский:1 процесс:2 фигурировать:1 бомбёжка:1 артобстрел:1 остальной:2 умереть:1 голод:2 энциклопедия:1 свет:2 издательство:1 оборона:2 рф:7 цифра:1 существенно:1 занизить:1 поскольку:2 учесть:1 неопознанный:1 блокадник:1 погибший:1 умерший:1 эвакуация:1 встречный:1 наступление:1 волховский:1 блокадный:1 кольцо:1 прорвать:1 снятой:1 снятие:1 восстановление:1 концертный:4 сезон:2 зал:3 филармония:1 предлагаться:1 развивать:1 приблизительно:1 равный:2 новое:6 калинин:2 комсомольский:1 облик:3 обрести:1 стачка:2 среднеохтинский:1 запустить:1 аэровокзал:1 сдать:1 эксплуатация:5 метрополитен:6 возобновить:2 традиция:2 полуденный:2 выстрел:2 пушка:1 нарышкина:2 бастион:2 прервать:1 марсовый:1 зажечь:1 вечный:2 судостроительный:3 атомный:2 ледокол:2 трактор:2 кировец:1 мемориал:1 пискаревский:1 кладбище:2 аптекарский:1 возвести:1 метровый:1 телебашня:1 телецентр:1 домостроительный:1 комбинат:2 массовый:5 хрущёвка:2 корабль:3 присвоить:1 звание:1 приказ:1 верховный:3 главнокомандующий:1 одобрить:1 намывной:1 новоизмайловский:1 гагарин:1 космонавт:1 купчиный:1 автовый:2 дачный:1 гражданка:1 полюстровый:2 юбилей:2 спорт:7 юбилейный:3 урицк:1 сосновый:1 поляна:1 весёлый:1 посёлок:1 муринский:1 ручей:1 комендантский:1 аэродром:1 купчина:1 шуваловый:1 озерко:1 ржевка:1 защитить:1 гавань:2 родиться:1 внести:4 референдум:1 горожанин:3 высказаться:2 возвращение:3 президиум:2 возвратить:3 конституция:3 депутат:4 всенародный:1 голосование:2 подтвердить:2 наименование:5 собчак:2 избранный:3 мэр:3 исполнительный:5 передать:1 администрация:3 губернатор:6 должность:1 упразднить:1 игра:2 воля:2 авария:1 мужество:1 прекратить:1 движение:1 установить:1 отреставрировать:1 восстановить:1 константиновский:2 храм:4 спас:2 кровь:3 перерыв:1 церковный:1 служба:2 пройти:2 ледовый:2 чемпионат:2 хоккей:1 кольцевой:2 автомобильный:6 пышно:1 отпраздновать:1 законодательный:6 собрание:5 определить:2 будущее:1 проводиться:4 ежегодный:1 саммит:2 форум:2 политический:3 мероприятие:2 получить:6 неофициальный:5 давос:1 поменять:1 формат:1 руководитель:2 иностранный:3 компания:6 глава:2 лидер:1 председатель:2 министр:1 восьмёрка:1 назначить:1 беглов:2 временно:1 исполнять:1 обязанность:1 футбольный:1 матч:4 групповой:2 этап:2 финал:2 кубок:1 конфедерация:1 фифа:1 футбол:1 сыграть:3 полуфинал:1 третье:1 провести:2 нидерландский:1 форма:4 тпитербурхъ:1 апостол:2 первоначально:1 распространиться:1 устанавливать:1 иноязычный:1 окружение:1 использовать:3 немецкий:2 английский:1 язык:2 равно:1 сподвижник:1 владеть:1 разнобой:2 именование:1 касаться:1 компонент:1 санкт:1 сант:1 нередко:1 родительный:1 падеж:1 питер:1 бурк:1 топоним:5 записать:1 слово:2 встречаться:3 следующий:2 санктъпетерсъбурк:1 сантпитербурх:1 питербурх:2 санктпетерзбурк:1 санктъ:1 санктпитербурх:1 xii:1 сантъпитербург:1 санктпитерзбурк:1 санктъпетерзбурк:1 vi:1 чаща:1 санктъпитербурх:1 начинать:2 вместо:2 позволять:1 широко:1 употребляться:2 настоящее:1 распространение:2 установиться:1 чисто:1 употребление:2 просторечие:1 инициатива:1 организатор:1 скончаться:1 опрос:4 участвовать:2 продолжать:2 ст:1 поправка:1 опубликование:1 инициатор:1 решающий:2 впоследствии:2 достижение:1 увековечить:1 установленный:2 надеяться:1 банковский:1 туристический:3 балтика:2 оптимизм:1 оценивать:1 возможность:1 перенос:1 xxi:1 старший:4 поколение:1 молодёжь:1 коммунистический:1 просоветский:1 взгляд:1 группа:4 прежний:2 организация:9 зоопарк:2 ленэнерго:1 астероид:1 петрополитать:1 астроном:1 симеизский:1 зависимость:1 петроградец:2 петроградка:1 ленинградка:1 петербуржец:5 петербуржка:1 санктпетербуржец:2 питерец:2 идентифицировать:1 понятие:1 опросить:1 осуществляться:3 устав:3 должностной:1 избирать:2 гражданин:2 проживать:3 обладать:3 закон:2 активный:3 избирательный:2 право:3 всеобщий:1 прямой:1 тайный:1 срок:2 осуществлять:4 иной:3 размещаться:2 пропорциональный:1 сформировать:2 созыв:1 присутствовать:1 фракция:1 единый:1 справедливый:1 кпрф:1 лдпр:1 партия:1 рост:3 яблоко:1 осуществление:1 исполнение:2 бюджет:2 расходование:1 средство:2 внебюджетный:1 фонд:1 контрольный:1 счётный:1 палата:1 судебный:1 уставный:1 судья:1 муниципальный:2 налог:3 прибыль:1 доход:2 физический:3 акциз:1 имущество:2 использование:2 собственность:3 статья:3 расход:2 экономика:4 здравоохранение:9 социальный:1 политика:2 хозяйство:4 общегосударственный:1 вопрос:1 кинематография:1 долг:1 иметь:3 внешний:1 периодически:1 побратим:1 консульство:3 почётный:2 представительство:4 участник:1 банка:2 филиал:2 евразийский:3 сообщество:1 субъект:2 автономия:1 объединение:7 землячество:1 герб:3 дополнить:1 отменяться:1 вновь:1 ввести:4 старый:4 символ:8 флаг:3 регистр:1 присвоение:1 регистрационный:1 номер:2 изобразить:1 скипетр:1 якорь:2 речной:5 прообраз:1 послужить:1 ватикан:1 обозначать:1 конституционно:1 правовой:1 единство:2 достояние:1 девять:1 месяц:2 соответствующий:1 решение:2 гимн:2 музыка:1 балет:5 медный:4 всадник:4 глиэра:1 редакция:1 корчмара:1 согласно:3 кораблик:1 шпиль:2 ангел:1 пушечный:1 сигнальный:1 помимо:3 общероссийский:1 праздник:3 отмечаться:3 памятный:1 дата:2 <tag>:3 стамбул:1 миллионер:1 устойчивый:1 депопуляция:1 прирост:3 счёт:1 превышение:1 миграционный:1 убыль:1 итог:3 росстат:2 показатель:7 рождаемость:1 смертность:2 всероссийский:3 мужчина:3 женщина:3 ожидать:1 жизнь:4 пенсионер:1 инвалид:1 возраст:1 представитель:2 национальность:2 народность:2 указать:1 украинец:1 белорус:1 татарин:1 еврей:1 узбек:1 армянин:1 азербайджанец:1 таджик:1 грузин:1 молдаванин:1 казах:1 финн:1 неоконченный:1 неграмотный:1 регистрировать:1 безработица:1 экономически:1 номинальный:1 заработный:2 плат:2 начислить:1 прожиточный:1 минимум:1 расчёт:1 валовый:2 региональный:6 врп:2 триллион:3 вид:5 скобка:1 доля:9 финансовый:2 валютный:1 товарный:2 пао:2 сырьевой:1 втб:1 таврический:2 балтинвестбанк:1 регион:2 оценка:2 mercer:1 привлечь:1 порядок:2 стадия:1 реализация:3 инвестиционный:1 отгрузить:2 структура:3 оборудование:8 включая:2 напиток:3 табак:1 металлургия:2 готовый:1 металлический:2 тяжёлый:1 работать:9 вмф:3 танкер:1 подводный:1 лодка:1 средне:1 катер:1 тральщик:1 морфлот:2 машиностроение:2 компрессор:1 компрессорный:2 нефтегазовый:1 газовый:1 гидравлический:1 турбина:1 электросила:1 электромашина:1 генератор:1 электропульт:1 аппаратура:2 севкабель:1 силовой:1 кабель:1 прокат:1 металлопродукция:1 сельскохозяйственный:1 техника:1 арсенал:1 космический:1 спутник:1 установка:1 прокатный:1 реактор:1 ленинец:1 авиация:1 вооружение:2 радиоэлектронный:2 рентгеновский:1 трубка:1 комплектовать:1 оптический:1 прибор:1 развитый:4 вагонмаш:1 пассажирский:8 вагон:1 электровагон:1 ford:1 toyota:1 general:1 motors:1 scania:1 nissan:1 hyundai:1 motor:1 man:1 собрать:1 автомобиль:1 продавать:1 отрасль:2 трубный:1 северсталь:1 цветной:1 выборжец:1 вмп:1 лёгкий:1 полиграфический:1 пивоваренный:2 пиво:1 безалкогольный:1 минеральный:2 пивзавод:1 heineken:1 хлебозавод:1 хлебобулочный:1 мучнистый:1 кондитерский:2 принадлежать:3 fazer:1 конфета:1 шоколад:1 мясокомбинат:2 парнас:1 колбасный:1 мясной:1 консервы:1 полуфабрикат:1 круп:1 мука:1 молочный:1 петмол:1 danone:1 рыбный:1 работник:3 оперативный:1 статистический:1 отчётность:1 среднемесячный:1 оборот:4 розничный:3 торговля:5 табачный:1 непродовольственный:1 товар:2 платный:1 услуга:1 потребительский:1 работа:6 занятой:2 внутренний:4 включать:4 продовольственный:1 повседневный:1 спрос:1 реализовать:1 общественный:4 питание:1 обслуживание:3 мелкорозничный:1 специализировать:1 сельхозпродукция:1 представить:3 ашан:1 руока:1 spar:1 metro:1 prisma:1 кей:1 лента:1 дикси:1 магнит:1 пятёрочка:1 карусель:1 перекрёсток:1 принадлежащий:1 retail:1 group:1 межрегиональный:1 семья:1 верный:1 норма:1 нетто:1 азбука:1 вкус:2 полушка:1 лайм:1 лэнд:1 риомаг

In [10]:
def get_dataset_internals_folder_path(dataset_name: DatasetName) -> str:
    return os.path.join('.', dataset_name.value + '__internals')

In [11]:
DATASET_INTERNALS_FOLDER_PATH = get_dataset_internals_folder_path(DATASET_NAME)

In [12]:
DATASET_INTERNALS_FOLDER_PATH

'./Good_RU_Wiki__internals'

In [13]:
%%time

# If using really big datasets (like Habrahabr),
# one may need to set this equal `False`
KEEP_DATASET_IN_MEMORY = True

DATASET = Dataset(
    DATASET_FILE_PATH,
    internals_folder_path=DATASET_INTERNALS_FOLDER_PATH,
    keep_in_memory=KEEP_DATASET_IN_MEMORY,
)

CPU times: user 5.67 s, sys: 722 ms, total: 6.39 s
Wall time: 6.31 s

Looking what is inside dataset's folder

In [14]:
os.listdir(DATASET_INTERNALS_FOLDER_PATH)

['vw.txt',
 'result_50',
 'result2_50',
 'result2',
 'batches',
 'dict.dict',
 'result']

Creating batches

In [15]:
DATASET.get_batch_vectorizer()

artm.BatchVectorizer(data_path="./Good_RU_Wiki__internals/batches", num_batches=9)

In [16]:
os.listdir(DATASET_INTERNALS_FOLDER_PATH)

['vw.txt',
 'result_50',
 'result2_50',
 'result2',
 'batches',
 'dict.dict',
 'result']

In [17]:
if KEEP_DATASET_IN_MEMORY:
    DOCUMENTS = list(DATASET._data.index)
else:
    DOCUMENTS = list(DATASET._data_index)

NUM_DOCUMENTS = len(DOCUMENTS)

print(f'Num documents: {NUM_DOCUMENTS}')

Num documents: 8603

Let's look at some text samples

In [18]:
DATASET._data.head()

,vw_text,raw_text,id
id,,,
Санкт-Петербург,Санкт-Петербург |@lemmatized год:301 петроград...,,Санкт-Петербург
Дворцовая_площадь,Дворцовая_площадь |@lemmatized дворцовый:43 пл...,,Дворцовая_площадь
Греко-персидские_войны,Греко-персидские_войны |@lemmatized грёкий:23 ...,,Греко-персидские_войны
Тихий_океан,Тихий_океан |@lemmatized тихий:92 океан:174 ус...,,Тихий_океан
Атлантический_океан,Атлантический_океан |@lemmatized атлантический...,,Атлантический_океан

In [19]:
DATASET.get_possible_modalities()

{'@categories', '@lemmatized', '@ngramms'}

In [20]:
MAIN_MODALITY = '@lemmatized'

In [21]:
DATASET.get_dictionary()

artm.Dictionary(name=c8880f58-b4a8-459d-939b-6d4e17581a43, num_entries=892938)

In [22]:
dictionary = DATASET.get_dictionary()

In [23]:
print(dictionary)

for modality in DATASET.get_possible_modalities():
    if modality not in [MAIN_MODALITY]:
        dictionary.filter(class_id=modality, max_df=0, inplace=True)

artm.Dictionary(name=c8880f58-b4a8-459d-939b-6d4e17581a43, num_entries=892938)

In [24]:
dictionary.filter(min_df=5, max_df_rate=0.5)

artm.Dictionary(name=c8880f58-b4a8-459d-939b-6d4e17581a43, num_entries=61688)

In [25]:
DATASET._cached_dict = dictionary

In [26]:
DATASET.get_dictionary()

artm.Dictionary(name=c8880f58-b4a8-459d-939b-6d4e17581a43, num_entries=61688)

In [27]:
import scipy

from typing import List

from topicnet.cooking_machine.models.base_regularizer import BaseRegularizer
from topicnet.cooking_machine.models.thetaless_regularizer import (
    dataset2sparse_matrix,
)
from topicnet.cooking_machine.models import (
    BaseScore as BaseTopicNetScore,
    TopicModel
)

In [28]:
def calc_doc_occurrences(dataset, modality):
    """
    :param n_dw_matrix: sparse document-word matrix, shape is D x W
    :return: sparse matrix of co-occurrences

    doc_occurrences[w1, w2] = the number of the documents
    where there are w1 and w2
    """
    n_dw_matrix = dataset2sparse_matrix(dataset, modality, modalities_to_use=[modality])
    matrix = (scipy.sparse.csc_matrix(n_dw_matrix) > 0).astype(int)
    co_occurrences = matrix.T * matrix

    return co_occurrences.diagonal(), co_occurrences


def create_pmi_top_function(
    doc_occurrences, doc_co_occurrences,
    documents_number, top_sizes,
    topic_indices=None,
    co_occurrences_smooth=1.
):
    """
    :param doc_occurrences: array of doc occurrences of words
    :param doc_co_occurrences: sparse matrix of doc co-occurrences of words
    :param documents_number: number of the documents
    :param top_sizes: list of top values to calculate top-pmi for
    :param co_occurrences_smooth: constant to smooth co-occurrences in log
    :return: function which takes phi and theta and returns
    pair of two arrays: pmi-s of the tops and ppmi-s of the tops

    pmi[i] - pmi(top of size top_sizes[i])
    ppmi[i] - ppmi(top of size top_sizes[i])

    pmi(words) = sum_{u in words, v in words, u != v}
    log(
        (doc_co_occurrences[u, v] * documents_number + co_occurrences_smooth)
        / doc_occurrences[u] / doc_occurrences[v]
    )

    ppmi(words) = sum_{u in words, v in words, u != v}
    max(log(
        (doc_co_occurrences[u, v] * documents_number + co_occurrences_smooth)
        / doc_occurrences[u] / doc_occurrences[v]
    ), 0)

    """
    def func(phi):
        T, W = phi.shape
        # T = len(topic_indices)
        topic_indices = list(range(T))

        max_top_size = max(top_sizes)
        topic_pmis, topic_ppmis = dict(), dict()
        pmi, ppmi = np.zeros(max_top_size), np.zeros(max_top_size)
        tops = np.argpartition(phi, -max_top_size, axis=1)[:, -max_top_size:]
        
        for t in topic_indices:
            top = sorted(tops[t], key=lambda w: - phi[t, w])
            # print(top, phi.shape, doc_co_occurrences.shape)
            co_occurrences = doc_co_occurrences[top, :][:, top].todense()
            occurrences = doc_occurrences[top]
            values = np.log(
                (co_occurrences * documents_number + co_occurrences_smooth)
                / (occurrences[:, np.newaxis] * occurrences[np.newaxis, :] + co_occurrences_smooth)
            )
            diag = np.diag_indices(len(values))
            # values.cumsum(axis=0).cumsum(axis=1)[diag] - values[diag].cumsum()

            current_pmi = np.array(
               values.cumsum(axis=0).cumsum(axis=1)[diag] - values[diag].cumsum()
            ).ravel()
            topic_pmis[t] = current_pmi
            pmi += current_pmi

            values[values < 0.] = 0.
            current_ppmi = np.array(
               values.cumsum(axis=0).cumsum(axis=1)[diag] - values[diag].cumsum()
            ).ravel()
            topic_ppmis[t] = current_ppmi
            ppmi += current_ppmi
            
        sizes = np.arange(2, max_top_size + 1)
        pmi[1:] /= (T * sizes * (sizes - 1))
        ppmi[1:] /= (T * sizes * (sizes - 1))
        indices = np.array(top_sizes) - 1

        for t in topic_indices:
            topic_pmis[t][1:] /= (sizes * (sizes - 1))
            topic_ppmis[t][1:] /= (sizes * (sizes - 1))

        result_topic_pmis = {t: p[indices] for t, p in topic_pmis.items()}
        result_topic_ppmis = {t: p[indices] for t, p in topic_ppmis.items()}

        return pmi[indices], ppmi[indices], result_topic_pmis, result_topic_ppmis

    return func

In [29]:
%%time

occurences, co_occurences = calc_doc_occurrences(DATASET, MAIN_MODALITY)

CPU times: user 47.1 s, sys: 1.3 s, total: 48.4 s
Wall time: 47.9 s

In [30]:
co_occurences.shape

(61688, 61688)

In [31]:
calc_pmi = create_pmi_top_function(
    occurences, co_occurences,
    DATASET.get_dataset().shape[0], [20],
    topic_indices=[0, 1, 2],
    co_occurrences_smooth=1e-2,
)

In [32]:
import copy


class TopTokenCoherence(BaseTopicNetScore):
    def __init__(self, name, func):
        super().__init__()

        self._name = name
        self.calc_pmi = func

    @property
    def name(self):
        return self._name

    def call(self, model: TopicModel):
        values = self.calc_pmi(model.get_phi_dense()[0].T)

        return values[1]

    def call_by_topic(self, model: TopicModel):
        values = self.calc_pmi(model.get_phi_dense()[0].T)

        return values[3]

    def compute(
            self,
            model,
            topics: List[str] = None,
            documents: List[str] = None) -> Dict[str, float]:

        values = self.call_by_topic(model)

        phi = model.get_phi()

        if topics is None:
            topics = list(phi.columns)

            if hasattr(model, 'has_bcg'):
                print(f'Detected bcg topics! Skipping for coherence computation (and will have {len(topics) - 1} topics).')

                topics = topics[:-1]
        else:
            assert False

        index2topic = {phi.columns.get_loc(t): t for t in topics}
        topic2index = {t: i for i, t in index2topic.items()}

        if hasattr(model, 'has_bcg'):
            assert list(index2topic.keys()) == list(values.keys())[:-1]
        else:
            assert list(index2topic.keys()) == list(values.keys())

        result = {
            t: float(values[topic2index[t]])
            for t in topics
        }

        assert len(result) == len(index2topic)

        return result

    def _attach(self, model: TopicModel):
        if self._name in model.custom_scores:
            print(
                f'Score with such name "{self._name}" already attached to model!'
                f' So rewriting it...'
                f' All model\'s custom scores: {list(model.custom_scores.keys())}'
            )

        # TODO: TopicModel should provide ability to add custom scores
        model.custom_scores[self.name] = copy.deepcopy(self)

## Experiment<a id="experiment"></a>

Finally we are getting to the main part!)

### Scores (for Topics and Models)<a id="scores"></a>

<div style="text-align: right">Back to <a href=#contents>Contents</a></div>

Here we define a lot of scores (which mainly differ in initial parameters).

In [33]:
ONE_MODEL_NUM_TOPICS = 50
NUM_TOP_WORDS = 20

In [34]:
top = NUM_TOP_WORDS
target_topic_indices = list(range(ONE_MODEL_NUM_TOPICS))

coherence_score = TopTokenCoherence(
    name=f'coherence_{top}',
    func=create_pmi_top_function(
        occurences, co_occurences,
        DATASET.get_dataset().shape[0], [top],
        # topic_indices=target_topic_indices,
        co_occurrences_smooth=1e-2,
    )
)

diversity_scores = [
    DiversityScore(
        name=f'diversity_{metric}',
        metric=metric,
        class_ids=MAIN_MODALITY,
    )

    for metric in KNOWN_METRICS
]

Other coherence score variations

And a pair of default ARTM scores (these ones are fast)

In [35]:
other_scores = [
    PerplexityScore(
        name='perplexity'
    ),
]

### Bank Creation<a id="bank-creation"></a>

<div style="text-align: right">Back to <a href=#contents>Contents</a></div>

Here we finally run the experiment!

In [36]:
NUM_ITERATIONS = 10

In [37]:
seed = 0

In [38]:
# We use only one train function here
# Other variations are also possible
# It would be even better to make bank using several train functions
# However, it would also take way more time 

TRAIN_FUNCS = default_train_func  # default train func

In [39]:
DATASET_INTERNALS_FOLDER_PATH

'./Good_RU_Wiki__internals'

In [40]:
SEARCH_RESULTS_FOLDER_PATH = os.path.join(
    DATASET_INTERNALS_FOLDER_PATH, 'result_50'
)

# File with some info about the process
SEARCH_RESULT_FILE_PATH = os.path.join(
    SEARCH_RESULTS_FOLDER_PATH, f'search_result__{seed}.json'
)

# Bank, with topics and their score values
BANK_FOLDER_PATH = os.path.join(
    SEARCH_RESULTS_FOLDER_PATH, f'bank__{seed}'
)

In [41]:
! echo $DATASET_INTERNALS_FOLDER_PATH
! ls -alh $DATASET_INTERNALS_FOLDER_PATH

./Good_RU_Wiki__internals
total 248M
drwxrwxr-x  7 alekseev_v mil_lab 4,0K мар 27 18:18 .
drwxrwxr-x 11 alekseev_v mil_lab 4,0K мар 27 18:18 ..
drwxrwxr-x  2 alekseev_v mil_lab 4,0K мар 24 10:57 batches
-rw-rw-r--  1 alekseev_v mil_lab  49M мар 24 10:57 dict.dict
drwxrwxr-x  3 alekseev_v mil_lab 4,0K мар 24 11:04 result
drwxrwxr-x  3 alekseev_v mil_lab 4,0K мар 24 12:21 result2
drwxrwxr-x  3 alekseev_v mil_lab 4,0K мар 27 16:00 result2_50
drwxrwxr-x  3 alekseev_v mil_lab 4,0K мар 27 17:47 result_50
-rw-rw-r--  1 alekseev_v mil_lab 200M мар 24 10:57 vw.txt

In [42]:
SEARCH_RESULTS_FOLDER_PATH

'./Good_RU_Wiki__internals/result_50'

! rm -r $SEARCH_RESULTS_FOLDER_PATH

In [45]:
! ls $SEARCH_RESULTS_FOLDER_PATH

ls: cannot access './Good_RU_Wiki__internals/result_50': No such file or directory

In [46]:
BANK_FOLDER_PATH

'./Good_RU_Wiki__internals/result_50/bank__0'

In [47]:
os.makedirs(SEARCH_RESULTS_FOLDER_PATH, exist_ok=True)
os.makedirs(BANK_FOLDER_PATH, exist_ok=True)

In [48]:
seed

0

In [49]:
ONE_MODEL_NUM_TOPICS

50

One cay vary some parameters below (for example `max_num_models` and `num_fit_iterations`).

In [50]:
optimizer = TopicBankMethod(
    data        = DATASET,
    main_modality = MAIN_MODALITY,
    
    min_df_rate = 0.0,  # dictionary filtering has already been done little earlier
    max_df_rate = 1.0,  #   so we don't want these parameters to have any effect

    main_topic_score   = coherence_score,
    other_topic_scores = [],
    other_scores       = [coherence_score] + diversity_scores + other_scores,
   # documents          = TEST_DOCUMENTS,

    start_model_number   = 0,
    max_num_models       = 20,
    one_model_num_topics = ONE_MODEL_NUM_TOPICS,  # 100,
    num_fit_iterations   = NUM_ITERATIONS,  # 100,  # 100 should be enough;
                                 # however, for big data better to reduce this one
                                 # (otherwise the process will be too slow)

    topic_score_threshold_percentile = 90,

    save_bank         = True,
    save_model_topics = True,
    save_file_path    = SEARCH_RESULT_FILE_PATH,
    bank_folder_path  = BANK_FOLDER_PATH,

    train_funcs = TRAIN_FUNCS,
    
    verbose = True,
)

# TODO: use Holdout Perplexity as Stop score

In [51]:
optimizer._result.keys()

dict_keys(['optimum', 'optimum_std', 'bank_scores', 'bank_topic_scores', 'model_scores', 'model_topic_scores', 'num_bank_topics', 'num_model_topics'])

Checking file paths

In [52]:
! echo $DATASET_INTERNALS_FOLDER_PATH
! ls $DATASET_INTERNALS_FOLDER_PATH

./Good_RU_Wiki__internals
batches  dict.dict  result  result2  result2_50  result_50  vw.txt

In [53]:
optimizer._save_file_path

'./Good_RU_Wiki__internals/result_50/search_result__0.json'

In [54]:
optimizer._topic_bank._path

'./Good_RU_Wiki__internals/result_50/bank__0'

Fulfilling the search (get ready for a really long process!):

! rm -r ./Good_RU_Wiki__internals/result_50

In [55]:
%%time

optimizer.search_for_optimum(DATASET)

  0%|                                                        | 0/20 [00:00<?, ?it/s]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.50it/s]

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 23701.962890625, 'coherence_20': 1.271056255022922, 'diversity_euclidean': 0.06817160745189306, 'diversity_jensenshannon': 0.684349668889001, 'diversity_hellinger': 0.7904835425832982, 'diversity_cosine': 0.8860105268866816, 'perplexity': 23701.962890625, 'ppl_fair': 23701.962890625, 'ppl_cheatty': 8288.0302734375}
  5%|██▎                                            | 1/20 [03:05<58:47, 185.65s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.25it/s]
Creating first level with 5 topics. Dictionary: artm.Dictionary(name=c8880f58-b4a8-459d-939b-6d4e17581a43, num_entries=61688).
Copying phi for the first level. Phi shape: (61688, 5). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           )
Creating second level with 50 topics
Copying phi for the second level. Phi shape: (61688, 50). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           names=['modality', 'token'])

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 23701.962890625, 'coherence_20': 1.271056255022922, 'diversity_euclidean': 0.06817160745187226, 'diversity_jensenshannon': 0.6843496688865095, 'diversity_hellinger': 0.790483542581285, 'diversity_cosine': 0.8860105268855312, 'perplexity': 23701.962890625, 'ppl_fair': 23701.962890625, 'ppl_cheatty': 8288.0302734375}
 10%|████▌                                        | 2/20 [07:17<1:07:23, 224.65s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.44it/s]
Creating first level with 5 topics. Dictionary: artm.Dictionary(name=c8880f58-b4a8-459d-939b-6d4e17581a43, num_entries=61688).
Copying phi for the first level. Phi shape: (61688, 5). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           )
Creating second level with 50 topics
Copying phi for the second level. Phi shape: (61688, 50). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           names=['modality', 'token'])

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 20840.115234375, 'coherence_20': 1.3105229372443379, 'diversity_euclidean': 0.06779818155731318, 'diversity_jensenshannon': 0.6847988106758301, 'diversity_hellinger': 0.7903959988756799, 'diversity_cosine': 0.8946042031637098, 'perplexity': 20840.115234375, 'ppl_fair': 20840.115234375, 'ppl_cheatty': 8016.89794921875}
 15%|██████▊                                      | 3/20 [11:23<1:06:21, 234.19s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.39it/s]
Creating first level with 6 topics. Dictionary: artm.Dictionary(name=c8880f58-b4a8-459d-939b-6d4e17581a43, num_entries=61688).
Copying phi for the first level. Phi shape: (61688, 6). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           )
Creating second level with 50 topics
Copying phi for the second level. Phi shape: (61688, 50). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           names=['modality', 'token'])

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 16605.404296875, 'coherence_20': 1.3669717987523746, 'diversity_euclidean': 0.06783939413207621, 'diversity_jensenshannon': 0.6882966528869119, 'diversity_hellinger': 0.7948444346135022, 'diversity_cosine': 0.8959400897904933, 'perplexity': 16605.404296875, 'ppl_fair': 16605.404296875, 'ppl_cheatty': 7658.2080078125}
 20%|█████████                                    | 4/20 [15:35<1:04:19, 241.20s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.49it/s]
Creating first level with 8 topics. Dictionary: artm.Dictionary(name=c8880f58-b4a8-459d-939b-6d4e17581a43, num_entries=61688).
Copying phi for the first level. Phi shape: (61688, 8). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           )
Creating second level with 50 topics
Copying phi for the second level. Phi shape: (61688, 50). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           names=['modality', 'token'])

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 16605.404296875, 'coherence_20': 1.3669717987523746, 'diversity_euclidean': 0.06783939413203365, 'diversity_jensenshannon': 0.6882966528836587, 'diversity_hellinger': 0.794844434612453, 'diversity_cosine': 0.8959400897869882, 'perplexity': 16605.404296875, 'ppl_fair': 16605.404296875, 'ppl_cheatty': 7658.2080078125}
 25%|███████████▎                                 | 5/20 [19:45<1:01:07, 244.48s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.42it/s]
Creating first level with 8 topics. Dictionary: artm.Dictionary(name=c8880f58-b4a8-459d-939b-6d4e17581a43, num_entries=61688).
Copying phi for the first level. Phi shape: (61688, 8). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           )
Creating second level with 50 topics
Copying phi for the second level. Phi shape: (61688, 50). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           names=['modality', 'token'])

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 16605.404296875, 'coherence_20': 1.3669717987523746, 'diversity_euclidean': 0.06783939413204165, 'diversity_jensenshannon': 0.6882966528846979, 'diversity_hellinger': 0.7948444346143998, 'diversity_cosine': 0.8959400897872248, 'perplexity': 16605.404296875, 'ppl_fair': 16605.404296875, 'ppl_cheatty': 7658.2080078125}
 30%|██████████████                                 | 6/20 [23:52<57:17, 245.52s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.36it/s]
Creating first level with 8 topics. Dictionary: artm.Dictionary(name=c8880f58-b4a8-459d-939b-6d4e17581a43, num_entries=61688).
Copying phi for the first level. Phi shape: (61688, 8). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           )
Creating second level with 50 topics
Copying phi for the second level. Phi shape: (61688, 50). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           names=['modality', 'token'])

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 16605.404296875, 'coherence_20': 1.3669717987523746, 'diversity_euclidean': 0.0678393941320341, 'diversity_jensenshannon': 0.6882966528839398, 'diversity_hellinger': 0.7948444346123384, 'diversity_cosine': 0.8959400897871371, 'perplexity': 16605.404296875, 'ppl_fair': 16605.404296875, 'ppl_cheatty': 7658.2080078125}
 35%|████████████████▍                              | 7/20 [28:01<53:25, 246.59s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.45it/s]
Creating first level with 8 topics. Dictionary: artm.Dictionary(name=c8880f58-b4a8-459d-939b-6d4e17581a43, num_entries=61688).
Copying phi for the first level. Phi shape: (61688, 8). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           )
Creating second level with 50 topics
Copying phi for the second level. Phi shape: (61688, 50). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           names=['modality', 'token'])

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 16605.404296875, 'coherence_20': 1.3669717987523746, 'diversity_euclidean': 0.06783939413202508, 'diversity_jensenshannon': 0.6882966528845964, 'diversity_hellinger': 0.7948444346127023, 'diversity_cosine': 0.8959400897875743, 'perplexity': 16605.404296875, 'ppl_fair': 16605.404296875, 'ppl_cheatty': 7658.2080078125}
 40%|██████████████████▊                            | 8/20 [32:11<49:30, 247.58s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.39it/s]
Creating first level with 8 topics. Dictionary: artm.Dictionary(name=c8880f58-b4a8-459d-939b-6d4e17581a43, num_entries=61688).
Copying phi for the first level. Phi shape: (61688, 8). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           )
Creating second level with 50 topics
Copying phi for the second level. Phi shape: (61688, 50). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           names=['modality', 'token'])

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 16605.404296875, 'coherence_20': 1.3669717987523746, 'diversity_euclidean': 0.06783939413159087, 'diversity_jensenshannon': 0.6882966528816654, 'diversity_hellinger': 0.7948444345942505, 'diversity_cosine': 0.8959400897860439, 'perplexity': 16605.404296875, 'ppl_fair': 16605.404296875, 'ppl_cheatty': 7658.2080078125}
 45%|█████████████████████▏                         | 9/20 [36:20<45:29, 248.11s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.50it/s]
Creating first level with 8 topics. Dictionary: artm.Dictionary(name=c8880f58-b4a8-459d-939b-6d4e17581a43, num_entries=61688).
Copying phi for the first level. Phi shape: (61688, 8). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           )
Creating second level with 50 topics
Copying phi for the second level. Phi shape: (61688, 50). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           names=['modality', 'token'])

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 13392.326171875, 'coherence_20': 1.3375176926823187, 'diversity_euclidean': 0.06688537873204287, 'diversity_jensenshannon': 0.6863727900934599, 'diversity_hellinger': 0.7918658817916197, 'diversity_cosine': 0.9004167519790243, 'perplexity': 13392.326171875, 'ppl_fair': 13392.326171875, 'ppl_cheatty': 7469.79736328125}
 50%|███████████████████████                       | 10/20 [40:31<41:29, 248.98s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.50it/s]
Creating first level with 9 topics. Dictionary: artm.Dictionary(name=c8880f58-b4a8-459d-939b-6d4e17581a43, num_entries=61688).
Copying phi for the first level. Phi shape: (61688, 9). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           )
Creating second level with 50 topics
Copying phi for the second level. Phi shape: (61688, 50). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           names=['modality', 'token'])

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 13392.326171875, 'coherence_20': 1.3375176926823187, 'diversity_euclidean': 0.06688537873290928, 'diversity_jensenshannon': 0.6863727900931127, 'diversity_hellinger': 0.7918658818032699, 'diversity_cosine': 0.9004167519623034, 'perplexity': 13392.326171875, 'ppl_fair': 13392.326171875, 'ppl_cheatty': 7469.79736328125}
 55%|█████████████████████████▎                    | 11/20 [44:37<37:11, 247.96s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.42it/s]
Creating first level with 9 topics. Dictionary: artm.Dictionary(name=c8880f58-b4a8-459d-939b-6d4e17581a43, num_entries=61688).
Copying phi for the first level. Phi shape: (61688, 9). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           )
Creating second level with 50 topics
Copying phi for the second level. Phi shape: (61688, 50). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           names=['modality', 'token'])

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 13392.326171875, 'coherence_20': 1.3375176926823187, 'diversity_euclidean': 0.06688537873222258, 'diversity_jensenshannon': 0.6863727900939307, 'diversity_hellinger': 0.7918658818003819, 'diversity_cosine': 0.9004167519777568, 'perplexity': 13392.326171875, 'ppl_fair': 13392.326171875, 'ppl_cheatty': 7469.79736328125}
 60%|███████████████████████████▌                  | 12/20 [48:43<33:00, 247.56s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.49it/s]
Creating first level with 9 topics. Dictionary: artm.Dictionary(name=c8880f58-b4a8-459d-939b-6d4e17581a43, num_entries=61688).
Copying phi for the first level. Phi shape: (61688, 9). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           )
Creating second level with 50 topics
Copying phi for the second level. Phi shape: (61688, 50). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           names=['modality', 'token'])

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 13392.326171875, 'coherence_20': 1.3375176926823187, 'diversity_euclidean': 0.06688537873298397, 'diversity_jensenshannon': 0.6863727900921055, 'diversity_hellinger': 0.7918658818065725, 'diversity_cosine': 0.9004167519609498, 'perplexity': 13392.326171875, 'ppl_fair': 13392.326171875, 'ppl_cheatty': 7469.79736328125}
 65%|█████████████████████████████▉                | 13/20 [52:48<28:46, 246.59s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.48it/s]
Creating first level with 9 topics. Dictionary: artm.Dictionary(name=c8880f58-b4a8-459d-939b-6d4e17581a43, num_entries=61688).
Copying phi for the first level. Phi shape: (61688, 9). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           )
Creating second level with 50 topics
Copying phi for the second level. Phi shape: (61688, 50). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           names=['modality', 'token'])

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 13392.326171875, 'coherence_20': 1.3375176926823187, 'diversity_euclidean': 0.0668853787322219, 'diversity_jensenshannon': 0.6863727900938426, 'diversity_hellinger': 0.7918658817998335, 'diversity_cosine': 0.9004167519777427, 'perplexity': 13392.326171875, 'ppl_fair': 13392.326171875, 'ppl_cheatty': 7469.79736328125}
 70%|████████████████████████████████▏             | 14/20 [56:57<24:44, 247.39s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.49it/s]
Creating first level with 9 topics. Dictionary: artm.Dictionary(name=c8880f58-b4a8-459d-939b-6d4e17581a43, num_entries=61688).
Copying phi for the first level. Phi shape: (61688, 9). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           )
Creating second level with 50 topics
Copying phi for the second level. Phi shape: (61688, 50). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           names=['modality', 'token'])

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 13392.326171875, 'coherence_20': 1.3375176926823187, 'diversity_euclidean': 0.06688537873214415, 'diversity_jensenshannon': 0.6863727900937194, 'diversity_hellinger': 0.7918658817968767, 'diversity_cosine': 0.9004167519780503, 'perplexity': 13392.326171875, 'ppl_fair': 13392.326171875, 'ppl_cheatty': 7469.79736328125}
 75%|█████████████████████████████████           | 15/20 [1:01:04<20:36, 247.39s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.49it/s]
Creating first level with 9 topics. Dictionary: artm.Dictionary(name=c8880f58-b4a8-459d-939b-6d4e17581a43, num_entries=61688).
Copying phi for the first level. Phi shape: (61688, 9). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           )
Creating second level with 50 topics
Copying phi for the second level. Phi shape: (61688, 50). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           names=['modality', 'token'])

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 13392.326171875, 'coherence_20': 1.3375176926823187, 'diversity_euclidean': 0.0668853787309232, 'diversity_jensenshannon': 0.686372790091995, 'diversity_hellinger': 0.7918658817814488, 'diversity_cosine': 0.9004167519779563, 'perplexity': 13392.326171875, 'ppl_fair': 13392.326171875, 'ppl_cheatty': 7469.79736328125}
 80%|███████████████████████████████████▏        | 16/20 [1:05:12<16:29, 247.40s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.50it/s]
Creating first level with 9 topics. Dictionary: artm.Dictionary(name=c8880f58-b4a8-459d-939b-6d4e17581a43, num_entries=61688).
Copying phi for the first level. Phi shape: (61688, 9). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           )
Creating second level with 50 topics
Copying phi for the second level. Phi shape: (61688, 50). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           names=['modality', 'token'])

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 13392.326171875, 'coherence_20': 1.3375176926823187, 'diversity_euclidean': 0.06688537873282732, 'diversity_jensenshannon': 0.6863727900924159, 'diversity_hellinger': 0.7918658818021704, 'diversity_cosine': 0.900416751961974, 'perplexity': 13392.326171875, 'ppl_fair': 13392.326171875, 'ppl_cheatty': 7469.79736328125}
 85%|█████████████████████████████████████▍      | 17/20 [1:09:19<12:22, 247.45s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.42it/s]
Creating first level with 9 topics. Dictionary: artm.Dictionary(name=c8880f58-b4a8-459d-939b-6d4e17581a43, num_entries=61688).
Copying phi for the first level. Phi shape: (61688, 9). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           )
Creating second level with 50 topics
Copying phi for the second level. Phi shape: (61688, 50). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           names=['modality', 'token'])

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 12935.0205078125, 'coherence_20': 1.325640369792121, 'diversity_euclidean': 0.06571734438226805, 'diversity_jensenshannon': 0.6800217140392609, 'diversity_hellinger': 0.7841219651265123, 'diversity_cosine': 0.8840728042243101, 'perplexity': 12935.0205078125, 'ppl_fair': 12935.0205078125, 'ppl_cheatty': 7393.04638671875}
 90%|███████████████████████████████████████▌    | 18/20 [1:13:33<08:18, 249.30s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.42it/s]
Creating first level with 10 topics. Dictionary: artm.Dictionary(name=c8880f58-b4a8-459d-939b-6d4e17581a43, num_entries=61688).
Copying phi for the first level. Phi shape: (61688, 10). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           )
Creating second level with 50 topics
Copying phi for the second level. Phi shape: (61688, 50). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           names=['modality', 'token'])

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 12935.0205078125, 'coherence_20': 1.325640369792121, 'diversity_euclidean': 0.06571734438226257, 'diversity_jensenshannon': 0.6800217140394483, 'diversity_hellinger': 0.7841219651265428, 'diversity_cosine': 0.8840728042250905, 'perplexity': 12935.0205078125, 'ppl_fair': 12935.0205078125, 'ppl_cheatty': 7393.04638671875}
 95%|█████████████████████████████████████████▊  | 19/20 [1:17:43<04:09, 249.40s/it]
  0%|                                                         | 0/1 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.51it/s]
Creating first level with 10 topics. Dictionary: artm.Dictionary(name=c8880f58-b4a8-459d-939b-6d4e17581a43, num_entries=61688).
Copying phi for the first level. Phi shape: (61688, 10). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           )
Creating second level with 50 topics
Copying phi for the second level. Phi shape: (61688, 50). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           names=['modality', 'token'])

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 12935.0205078125, 'coherence_20': 1.325640369792121, 'diversity_euclidean': 0.0657173443822478, 'diversity_jensenshannon': 0.6800217140392175, 'diversity_hellinger': 0.7841219651260267, 'diversity_cosine': 0.884072804224423, 'perplexity': 12935.0205078125, 'ppl_fair': 12935.0205078125, 'ppl_cheatty': 7393.0458984375}
100%|████████████████████████████████████████████| 20/20 [1:21:58<00:00, 245.95s/it]
CPU times: user 2h 26min 43s, sys: 3min 38s, total: 2h 30min 21s
Wall time: 1h 21min 59s

What topics we have in bank

In [57]:
optimizer._topic_bank.view_topics().head()

                                   topic_0  topic_1   topic_2       topic_3  \
@lemmatized рлэ               0.000000e+00      0.0  0.000000  0.000000e+00
            локационный       1.026262e-15      0.0  0.000005  0.000000e+00
            неподверженность  0.000000e+00      0.0  0.000020  0.000000e+00
            даякский          1.499791e-10      0.0  0.000000  1.916781e-16
            рэдкот            0.000000e+00      0.0  0.000000  0.000000e+00

                              topic_4       topic_5   topic_6       topic_7  \
@lemmatized рлэ                   0.0  0.000000e+00  0.000000  0.000000e+00
            локационный           0.0  1.051820e-14  0.000000  1.111689e-15
            неподверженность      0.0  0.000000e+00  0.000000  0.000000e+00
            даякский              0.0  0.000000e+00  0.000014  0.000000e+00
            рэдкот                0.0  0.000000e+00  0.000000  0.000000e+00

                              topic_8  topic_9
@lemmatized рлэ                   0.0      0.0
            локационный           0.0      0.0
            неподверженность      0.0      0.0
            даякский              0.0      0.0
            рэдкот                0.0      0.0

In [58]:
bank_topics = optimizer._topic_bank.view_topics()

In [59]:
bank_topics.shape

(61688, 10)

In [60]:
bank_topics.head()

                                   topic_0  topic_1   topic_2       topic_3  \
@lemmatized рлэ               0.000000e+00      0.0  0.000000  0.000000e+00
            локационный       1.026262e-15      0.0  0.000005  0.000000e+00
            неподверженность  0.000000e+00      0.0  0.000020  0.000000e+00
            даякский          1.499791e-10      0.0  0.000000  1.916781e-16
            рэдкот            0.000000e+00      0.0  0.000000  0.000000e+00

                              topic_4       topic_5   topic_6       topic_7  \
@lemmatized рлэ                   0.0  0.000000e+00  0.000000  0.000000e+00
            локационный           0.0  1.051820e-14  0.000000  1.111689e-15
            неподверженность      0.0  0.000000e+00  0.000000  0.000000e+00
            даякский              0.0  0.000000e+00  0.000014  0.000000e+00
            рэдкот                0.0  0.000000e+00  0.000000  0.000000e+00

                              topic_8  topic_9
@lemmatized рлэ                   0.0      0.0
            локационный           0.0      0.0
            неподверженность      0.0      0.0
            даякский              0.0      0.0
            рэдкот                0.0      0.0

In [63]:
bank_topics['topic_6'].sort_values(ascending=False)[:20]

@lemmatized  сербский       0.018557
             серб           0.013351
             хорватский     0.010837
             сербия         0.008925
             хорватия       0.008571
             территория     0.008101
             гонконг        0.007632
             югославия      0.006734
             болгарский     0.006306
             босния         0.005951
             болгария       0.005526
             страна         0.005063
             блюдо          0.004687
             югославский    0.004676
             население      0.004452
             хорват         0.004188
             республика     0.003726
             кухня          0.003415
             местный        0.003392
             герцеговина    0.003382
Name: topic_6, dtype: float64

And topic scores

In [64]:
optimizer._topic_bank.view_topic_scores()

,topic_0,topic_1,topic_2,topic_3,topic_4,topic_5,topic_6,topic_7,topic_8,topic_9
kernel_size,4340.000000,4340.000000,5921.000000,4604.000000,4449.000000,5229.000000,5372.000000,4399.000000,6615.000000,5655.000000
coherence_20,1.504778,1.177245,1.148254,1.300758,1.224246,1.507856,1.413234,1.659403,1.101885,1.218744
distance_to_nearest,0.000000,0.938270,0.911490,0.874375,0.665535,0.847624,0.871184,0.877588,0.865746,0.727888

All models are also saved (topics as $\Phi$ matrices and topic score values)

In [65]:
! ls $optimizer._topic_bank._path

model_0__phi.bin	    model_19__topic_scores.bin
model_0__topic_scores.bin   model_1__phi.bin
model_10__phi.bin	    model_1__topic_scores.bin
model_10__topic_scores.bin  model_2__phi.bin
model_11__phi.bin	    model_2__topic_scores.bin
model_11__topic_scores.bin  model_3__phi.bin
model_12__phi.bin	    model_3__topic_scores.bin
model_12__topic_scores.bin  model_4__phi.bin
model_13__phi.bin	    model_4__topic_scores.bin
model_13__topic_scores.bin  model_5__phi.bin
model_14__phi.bin	    model_5__topic_scores.bin
model_14__topic_scores.bin  model_6__phi.bin
model_15__phi.bin	    model_6__topic_scores.bin
model_15__topic_scores.bin  model_7__phi.bin
model_16__phi.bin	    model_7__topic_scores.bin
model_16__topic_scores.bin  model_8__phi.bin
model_17__phi.bin	    model_8__topic_scores.bin
model_17__topic_scores.bin  model_9__phi.bin
model_18__phi.bin	    model_9__topic_scores.bin
model_18__topic_scores.bin  topics.bin
model_19__phi.bin	    topic_scores.bin

In [59]:
optimizer._result.keys()

dict_keys(['optimum', 'optimum_std', 'bank_scores', 'bank_topic_scores', 'model_scores', 'model_topic_scores', 'num_bank_topics', 'num_model_topics'])

In [60]:
optimizer._result['num_bank_topics']

[5]

In [61]:
len(optimizer._result['bank_topic_scores'])

1

In [66]:
import artm
from topnum.model_constructor import KnownModel, init_plsa
from topicnet.cooking_machine.rel_toolbox_lite import (
    count_vocab_size,
    transform_regularizer,
)
from topicnet.cooking_machine.model_constructor import (
    add_standard_scores,
    create_default_topics,
    init_model,
)

def init_model_from_family(
        family: str or KnownModel,
        dataset: Dataset,
        main_modality: str,
        num_topics: int,
        seed: int,
        specific_topic_names = None,
        modalities_to_use: List[str] = None,
        num_processors: int = 3,
        model_params: dict = None,
):
    """
    Returns
    -------
    model: TopicModel() instance
    """
    if isinstance(family, KnownModel):
        family = family.value

    if modalities_to_use is None:
        modalities_to_use = [main_modality]

    custom_regs = {}

    if family == "LDA":
        model = init_lda(
            dataset, modalities_to_use, main_modality, num_topics, model_params
        )
    elif family == "PLSA":
        model = init_plsa(
            dataset, modalities_to_use, main_modality, num_topics
        )
    elif family == "TARTM":
        model, custom_regs = init_thetaless(
            dataset, modalities_to_use, main_modality, num_topics, model_params
        )
    elif family == "sparse":
        model = init_bcg_sparse_model(
            dataset, modalities_to_use, main_modality, num_topics, 1, model_params
        )
    elif family == "decorrelation":
        model = init_decorrelated_plsa(
            dataset, modalities_to_use, main_modality, num_topics, model_params
        )
    elif family == "ARTM":
        model = init_baseline_artm(
            dataset, modalities_to_use, main_modality, num_topics, 1, specific_topic_names, model_params
        )
    else:
        raise ValueError(f'family: {family}')

    model.num_processors = num_processors

    if seed is not None:
        model.seed = seed

    dictionary = dataset.get_dictionary()

    # TODO: maybe this cycle is not necessary
    for modality in dataset.get_possible_modalities():
        if modality not in modalities_to_use:
            dictionary.filter(class_id=modality, max_df=0, inplace=True)

    model.initialize(dictionary)
    add_standard_scores(model, dictionary, main_modality=main_modality,
                        all_modalities=modalities_to_use)

    model = TopicModel(
        artm_model=model,
        custom_regularizers=custom_regs
    )
    model.has_bcg = True  # TODO: only if init_bcg_sparse_model

    return model


def init_bcg_sparse_model(
        dataset,
        modalities_to_use,
        main_modality,
        specific_topics,
        bcg_topics,
        specific_topic_names = None,
        model_params: dict = None
):
    """
    Creates simple artm model with standard scores.

    Parameters
    ----------
    dataset : Dataset
    modalities_to_use : list of str or dict
    main_modality : str
    specific_topics : int
    bcg_topics : int

    Returns
    -------
    model: artm.ARTM() instance
    """
    if model_params is None:
        model_params = dict()

    model = init_plsa(
        dataset, modalities_to_use, main_modality, specific_topics, bcg_topics
    )
    background_topic_names = model.topic_names[-bcg_topics:]

    if specific_topic_names is None:
        print('No spec topics')
        specific_topic_names = model.topic_names[:-bcg_topics]

    dictionary = dataset.get_dictionary()
    baseline_class_ids = {class_id: 1 for class_id in modalities_to_use}
    data_stats = count_vocab_size(dictionary, baseline_class_ids)

    # all coefficients are relative
    regularizers = [
        artm.SmoothSparsePhiRegularizer(
             name='smooth_phi_bcg',
             topic_names=background_topic_names,
             tau=model_params.get("smooth_bcg_tau", 0.1),
             class_ids=[main_modality],
        ),
        artm.SmoothSparseThetaRegularizer(
             name='smooth_theta_bcg',
             topic_names=background_topic_names,
             tau=model_params.get("smooth_bcg_tau", 0.1),
        ),
        artm.SmoothSparsePhiRegularizer(
             name='sparse_phi_sp',
             topic_names=specific_topic_names,
             tau=model_params.get("sparse_sp_tau", -0.05),
             class_ids=[main_modality],
            ),
        artm.SmoothSparseThetaRegularizer(
             name='sparse_theta_sp',
             topic_names=specific_topic_names,
             tau=model_params.get("sparse_sp_tau", -0.05),
        ),
    ]
    for reg in regularizers:
        model.regularizers.add(transform_regularizer(
            data_stats,
            reg,
            model.class_ids,
            n_topics=len(reg.topic_names)
        ))

    return model


def init_baseline_artm(
        dataset,
        modalities_to_use,
        main_modality,
        num_topics,
        bcg_topics,
        specific_topic_names = None,
        model_params: dict = None,
):
    """
    Creates simple artm model with standard scores.

    Parameters
    ----------
    dataset : Dataset
    modalities_to_use : list of str
    main_modality : str
    num_topics : int

    Returns
    -------
    model: artm.ARTM() instance
    """
    if model_params is None:
        model_params = dict()

    model = init_bcg_sparse_model(
        dataset, modalities_to_use, main_modality, num_topics, bcg_topics, specific_topic_names, model_params
    )

    if specific_topic_names is None:
        print('No spec topics')
        specific_topic_names = model.topic_names[:-bcg_topics]

    model.regularizers.add(
        artm.DecorrelatorPhiRegularizer(
            gamma=0,
            tau=model_params.get('decorrelation_tau', 0.01),
            name='decorrelation',
            topic_names=specific_topic_names,
            class_ids=modalities_to_use,
        )
    )

    return model

In [67]:
def artm_train_func(
        dataset: Dataset,
        model_number: int,
        num_topics: int,
        num_fit_iterations: int,
        scores: List = None,
        **kwargs) -> TopicModel:
    """

    Additional Parameters
    ---------------------
    kwargs
        Some params for `_get_topic_model`, such as `cache_theta` and `num_processors`
    """

    topic_model = init_model_from_family(
        family='ARTM',
        dataset=DATASET,
        main_modality=MAIN_MODALITY,
        num_topics=ONE_MODEL_NUM_TOPICS,
        seed=model_number,
        model_params={
            'decorrelation_tau': 0.01,  # best values
            'smooth_bcg_tau': 0.05,
            'sparse_sp_tau': -0.05,
        }
    )

    num_fit_iterations_with_scores = 1

    topic_model._fit(
        dataset.get_batch_vectorizer(),
        num_iterations=max(0, num_fit_iterations - num_fit_iterations_with_scores)
    )
    _fit_model_with_scores(
        topic_model,
        DATASET,
        scores,
        num_fit_iterations=num_fit_iterations_with_scores
    )

    return topic_model


def _fit_model_with_scores(
        topic_model: TopicModel,
        dataset: Dataset,
        scores: List = None,
        num_fit_iterations: int = 1):

    if scores is not None:
        for score in scores:
            score._attach(topic_model)

    topic_model._fit(
        dataset.get_batch_vectorizer(),
        num_iterations=num_fit_iterations
    )

### Bank Creation<a id="bank-creation"></a>

<div style="text-align: right">Back to <a href=#contents>Contents</a></div>

Here we finally run the experiment!

In [69]:
ONE_MODEL_NUM_TOPICS

50

In [70]:
NUM_ITERATIONS = 10

In [71]:
seed = 0

In [72]:
# We use only one train function here
# Other variations are also possible
# It would be even better to make bank using several train functions
# However, it would also take way more time 

TRAIN_FUNCS = artm_train_func  # default train func

In [67]:
DATASET_INTERNALS_FOLDER_PATH

'./Good_RU_Wiki__internals'

In [73]:
SEARCH_RESULTS_FOLDER_PATH = os.path.join(
    DATASET_INTERNALS_FOLDER_PATH, 'result2_50'
)

# File with some info about the process
SEARCH_RESULT_FILE_PATH = os.path.join(
    SEARCH_RESULTS_FOLDER_PATH, f'search_result__{seed}.json'
)

# Bank, with topics and their score values
BANK_FOLDER_PATH = os.path.join(
    SEARCH_RESULTS_FOLDER_PATH, f'bank__{seed}'
)

In [74]:
SEARCH_RESULTS_FOLDER_PATH

'./Good_RU_Wiki__internals/result2_50'

! rm -r $SEARCH_RESULTS_FOLDER_PATH

! rm -r ./Good_RU_Wiki__internals/result2_50

In [78]:
BANK_FOLDER_PATH

'./Good_RU_Wiki__internals/result2_50/bank__0'

In [76]:
! ls $BANK_FOLDER_PATH

model_0__phi.bin	    model_4__phi.bin
model_0__topic_scores.bin   model_4__topic_scores.bin
model_10__phi.bin	    model_5__phi.bin
model_10__topic_scores.bin  model_5__topic_scores.bin
model_11__phi.bin	    model_6__phi.bin
model_11__topic_scores.bin  model_6__topic_scores.bin
model_12__phi.bin	    model_7__phi.bin
model_12__topic_scores.bin  model_7__topic_scores.bin
model_1__phi.bin	    model_8__phi.bin
model_1__topic_scores.bin   model_8__topic_scores.bin
model_2__phi.bin	    model_9__phi.bin
model_2__topic_scores.bin   model_9__topic_scores.bin
model_3__phi.bin	    topics.bin
model_3__topic_scores.bin   topic_scores.bin

In [79]:
os.makedirs(SEARCH_RESULTS_FOLDER_PATH, exist_ok=True)
os.makedirs(BANK_FOLDER_PATH, exist_ok=True)

In [80]:
seed

0

One cay vary some parameters below (for example `max_num_models` and `num_fit_iterations`).

In [83]:
optimizer = TopicBankMethod(
    data        = DATASET,
    main_modality = MAIN_MODALITY,
    
    min_df_rate = 0.0,  # dictionary filtering has already been done little earlier
    max_df_rate = 1.0,  #   so we don't want these parameters to have any effect

    main_topic_score   = coherence_score,
    other_topic_scores = [],
    other_scores       = [coherence_score] + diversity_scores + other_scores,
   # documents          = TEST_DOCUMENTS,

    start_model_number   = 0,
    max_num_models       = 20,
    one_model_num_topics = ONE_MODEL_NUM_TOPICS,  # 100,
    num_fit_iterations   = NUM_ITERATIONS,  # 100,  # 100 should be enough;
                                 # however, for big data better to reduce this one
                                 # (otherwise the process will be too slow)

    topic_score_threshold_percentile = 0.9918260892662304,  # DIFF ALSO HERE

    save_bank         = True,
    save_model_topics = True,
    save_file_path    = SEARCH_RESULT_FILE_PATH,
    bank_folder_path  = BANK_FOLDER_PATH,

    train_funcs = TRAIN_FUNCS,
    
    verbose = True,
)

# TODO: use Holdout Perplexity as Stop score

/home/alekseev_v/projects/iterative/../OptimalNumberOfTopics/topnum/search_methods/topic_bank/topic_bank_method.py:208: UserWarning: topic_score_threshold_percentile 0.9918260892662304 is less than one! It is expected to be in [0, 100]. Are you sure you want to proceed (yes/no)?
  warnings.warn(

In [84]:
optimizer._result.keys()

dict_keys(['optimum', 'optimum_std', 'bank_scores', 'bank_topic_scores', 'model_scores', 'model_topic_scores', 'num_bank_topics', 'num_model_topics'])

Checking file paths

In [85]:
! ls ./Post_Science__internals

batches    _result  _result2  result2_50  result_unfiltered_dict
dict.dict  result   result2   result_50   vw.txt

In [86]:
optimizer._save_file_path

'./Good_RU_Wiki__internals/result2_50/search_result__0.json'

In [87]:
optimizer._topic_bank._path

'./Good_RU_Wiki__internals/result2_50/bank__0'

Fulfilling the search (get ready for a really long process!):

In [88]:
%%time

optimizer.search_for_optimum(DATASET)

  0%|                                                        | 0/20 [00:00<?, ?it/s]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/1 [00:00<?, ?it/s]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.58it/s]
Using absoulte threshold: 0.9918260892662304.
Skipping saving scores for bcg topic

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 15662.7099609375, 'coherence_20': 1.1425703063188861, 'diversity_euclidean': 0.07887198216968297, 'diversity_jensenshannon': 0.6946457152370844, 'diversity_hellinger': 0.806890043129983, 'diversity_cosine': 0.9036317622655906, 'perplexity': 15662.7099609375, 'ppl_fair': 15662.7099609375, 'ppl_cheatty': 7013.5810546875}
  5%|██▎                                          | 1/20 [04:04<1:17:16, 244.00s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/1 [00:00<?, ?it/s]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.55it/s]
Using absoulte threshold: 0.9918260892662304.
Creating first level with 12 topics. Dictionary: artm.Dictionary(name=c8880f58-b4a8-459d-939b-6d4e17581a43, num_entries=61688).
Copying phi for the first level. Phi shape: (61688, 12). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           )
Creating second level with 51 topics
Copying phi for the second level. Phi shape: (61688, 51). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 10857.9970703125, 'coherence_20': 1.1651623256721328, 'diversity_euclidean': 0.07557170036957797, 'diversity_jensenshannon': 0.7022925707787939, 'diversity_hellinger': 0.8176427645234533, 'diversity_cosine': 0.9145419603471815, 'perplexity': 10857.9970703125, 'ppl_fair': 10857.9970703125, 'ppl_cheatty': 6368.2119140625}
 10%|████▌                                        | 2/20 [09:10<1:24:11, 280.63s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/1 [00:00<?, ?it/s]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.58it/s]
Using absoulte threshold: 0.9918260892662304.
Creating first level with 17 topics. Dictionary: artm.Dictionary(name=c8880f58-b4a8-459d-939b-6d4e17581a43, num_entries=61688).
Copying phi for the first level. Phi shape: (61688, 17). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           )
Creating second level with 51 topics
Copying phi for the second level. Phi shape: (61688, 51). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 9896.5439453125, 'coherence_20': 1.1618179902894068, 'diversity_euclidean': 0.07639010707158203, 'diversity_jensenshannon': 0.7071031854133308, 'diversity_hellinger': 0.8238560842220494, 'diversity_cosine': 0.9223522845629262, 'perplexity': 9896.5439453125, 'ppl_fair': 9896.5439453125, 'ppl_cheatty': 6181.224609375}
 15%|██████▊                                      | 3/20 [14:29<1:24:27, 298.11s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/1 [00:00<?, ?it/s]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.54it/s]
Using absoulte threshold: 0.9918260892662304.
Creating first level with 18 topics. Dictionary: artm.Dictionary(name=c8880f58-b4a8-459d-939b-6d4e17581a43, num_entries=61688).
Copying phi for the first level. Phi shape: (61688, 18). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           )
Creating second level with 51 topics
Copying phi for the second level. Phi shape: (61688, 51). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 11542.189453125, 'coherence_20': 1.2228724921271918, 'diversity_euclidean': 0.07919189673681822, 'diversity_jensenshannon': 0.7071739242875812, 'diversity_hellinger': 0.8244407629229179, 'diversity_cosine': 0.9160124747323241, 'perplexity': 11542.189453125, 'ppl_fair': 11542.189453125, 'ppl_cheatty': 6426.701171875}
 20%|█████████                                    | 4/20 [19:59<1:22:51, 310.69s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/1 [00:00<?, ?it/s]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.60it/s]
Using absoulte threshold: 0.9918260892662304.
Creating first level with 18 topics. Dictionary: artm.Dictionary(name=c8880f58-b4a8-459d-939b-6d4e17581a43, num_entries=61688).
Copying phi for the first level. Phi shape: (61688, 18). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           )
Creating second level with 51 topics
Copying phi for the second level. Phi shape: (61688, 51). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 11476.1064453125, 'coherence_20': 1.2279017648292383, 'diversity_euclidean': 0.07670431294035923, 'diversity_jensenshannon': 0.7023546612661073, 'diversity_hellinger': 0.8181596415832857, 'diversity_cosine': 0.907107152316396, 'perplexity': 11476.1064453125, 'ppl_fair': 11476.1064453125, 'ppl_cheatty': 6326.474609375}
 25%|███████████▎                                 | 5/20 [25:14<1:18:04, 312.33s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/1 [00:00<?, ?it/s]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.53it/s]
Using absoulte threshold: 0.9918260892662304.
Creating first level with 18 topics. Dictionary: artm.Dictionary(name=c8880f58-b4a8-459d-939b-6d4e17581a43, num_entries=61688).
Copying phi for the first level. Phi shape: (61688, 18). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           )
Creating second level with 51 topics
Copying phi for the second level. Phi shape: (61688, 51). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 11476.1064453125, 'coherence_20': 1.2279017648292383, 'diversity_euclidean': 0.07670431294031811, 'diversity_jensenshannon': 0.7023546612665723, 'diversity_hellinger': 0.8181596415832155, 'diversity_cosine': 0.9071071523169201, 'perplexity': 11476.1064453125, 'ppl_fair': 11476.1064453125, 'ppl_cheatty': 6326.474609375}
 30%|█████████████▌                               | 6/20 [30:16<1:12:01, 308.69s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/1 [00:00<?, ?it/s]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.52it/s]
Using absoulte threshold: 0.9918260892662304.
Creating first level with 18 topics. Dictionary: artm.Dictionary(name=c8880f58-b4a8-459d-939b-6d4e17581a43, num_entries=61688).
Copying phi for the first level. Phi shape: (61688, 18). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           )
Creating second level with 51 topics
Copying phi for the second level. Phi shape: (61688, 51). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 11476.1064453125, 'coherence_20': 1.2279017648292383, 'diversity_euclidean': 0.07670431294035776, 'diversity_jensenshannon': 0.7023546612665073, 'diversity_hellinger': 0.8181596415822796, 'diversity_cosine': 0.9071071523165727, 'perplexity': 11476.1064453125, 'ppl_fair': 11476.1064453125, 'ppl_cheatty': 6326.474609375}
 35%|███████████████▋                             | 7/20 [35:19<1:06:31, 307.05s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/1 [00:00<?, ?it/s]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.49it/s]
Using absoulte threshold: 0.9918260892662304.
Creating first level with 18 topics. Dictionary: artm.Dictionary(name=c8880f58-b4a8-459d-939b-6d4e17581a43, num_entries=61688).
Copying phi for the first level. Phi shape: (61688, 18). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           )
Creating second level with 51 topics
Copying phi for the second level. Phi shape: (61688, 51). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 12375.1484375, 'coherence_20': 1.243923076510148, 'diversity_euclidean': 0.07250389479571878, 'diversity_jensenshannon': 0.6988500210987204, 'diversity_hellinger': 0.8137566176236835, 'diversity_cosine': 0.8959202664666673, 'perplexity': 12375.1484375, 'ppl_fair': 12375.1484375, 'ppl_cheatty': 6512.36279296875}
 40%|██████████████████                           | 8/20 [40:59<1:03:29, 317.48s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/1 [00:00<?, ?it/s]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.46it/s]
Using absoulte threshold: 0.9918260892662304.
Creating first level with 19 topics. Dictionary: artm.Dictionary(name=c8880f58-b4a8-459d-939b-6d4e17581a43, num_entries=61688).
Copying phi for the first level. Phi shape: (61688, 19). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           )
Creating second level with 51 topics
Copying phi for the second level. Phi shape: (61688, 51). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 12375.1484375, 'coherence_20': 1.243923076510148, 'diversity_euclidean': 0.07250389479559613, 'diversity_jensenshannon': 0.6988500210985845, 'diversity_hellinger': 0.8137566176194528, 'diversity_cosine': 0.8959202664680485, 'perplexity': 12375.1484375, 'ppl_fair': 12375.1484375, 'ppl_cheatty': 6512.36279296875}
 45%|█████████████████████▏                         | 9/20 [46:09<57:46, 315.13s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/1 [00:00<?, ?it/s]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.45it/s]
Using absoulte threshold: 0.9918260892662304.
Creating first level with 19 topics. Dictionary: artm.Dictionary(name=c8880f58-b4a8-459d-939b-6d4e17581a43, num_entries=61688).
Copying phi for the first level. Phi shape: (61688, 19). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           )
Creating second level with 51 topics
Copying phi for the second level. Phi shape: (61688, 51). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 12375.1484375, 'coherence_20': 1.243923076510148, 'diversity_euclidean': 0.0725038947956197, 'diversity_jensenshannon': 0.6988500210983859, 'diversity_hellinger': 0.8137566176210534, 'diversity_cosine': 0.8959202664671793, 'perplexity': 12375.1484375, 'ppl_fair': 12375.1484375, 'ppl_cheatty': 6512.36279296875}
 50%|███████████████████████                       | 10/20 [51:20<52:19, 313.99s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/1 [00:00<?, ?it/s]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.45it/s]
Using absoulte threshold: 0.9918260892662304.
Creating first level with 19 topics. Dictionary: artm.Dictionary(name=c8880f58-b4a8-459d-939b-6d4e17581a43, num_entries=61688).
Copying phi for the first level. Phi shape: (61688, 19). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           )
Creating second level with 51 topics
Copying phi for the second level. Phi shape: (61688, 51). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 11941.9033203125, 'coherence_20': 1.2343980666151573, 'diversity_euclidean': 0.07182968590884665, 'diversity_jensenshannon': 0.6958409227261936, 'diversity_hellinger': 0.8097781487185564, 'diversity_cosine': 0.8933411098479948, 'perplexity': 11941.9033203125, 'ppl_fair': 11941.9033203125, 'ppl_cheatty': 6404.04638671875}
 55%|█████████████████████████▎                    | 11/20 [56:45<47:36, 317.33s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/1 [00:00<?, ?it/s]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.40it/s]
Using absoulte threshold: 0.9918260892662304.
Creating first level with 20 topics. Dictionary: artm.Dictionary(name=c8880f58-b4a8-459d-939b-6d4e17581a43, num_entries=61688).
Copying phi for the first level. Phi shape: (61688, 20). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           )
Creating second level with 51 topics
Copying phi for the second level. Phi shape: (61688, 51). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 11941.9033203125, 'coherence_20': 1.2343980666151573, 'diversity_euclidean': 0.07182968590886725, 'diversity_jensenshannon': 0.6958409227266205, 'diversity_hellinger': 0.8097781487229984, 'diversity_cosine': 0.8933411098481467, 'perplexity': 11941.9033203125, 'ppl_fair': 11941.9033203125, 'ppl_cheatty': 6404.04638671875}
 60%|██████████████████████████▍                 | 12/20 [1:02:02<42:18, 317.27s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/1 [00:00<?, ?it/s]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.44it/s]
Using absoulte threshold: 0.9918260892662304.
Creating first level with 20 topics. Dictionary: artm.Dictionary(name=c8880f58-b4a8-459d-939b-6d4e17581a43, num_entries=61688).
Copying phi for the first level. Phi shape: (61688, 20). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           )
Creating second level with 51 topics
Copying phi for the second level. Phi shape: (61688, 51). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 11941.9033203125, 'coherence_20': 1.2343980666151573, 'diversity_euclidean': 0.07182968586547622, 'diversity_jensenshannon': 0.6958409227157338, 'diversity_hellinger': 0.8097781487242658, 'diversity_cosine': 0.8933411097924296, 'perplexity': 11941.9033203125, 'ppl_fair': 11941.9033203125, 'ppl_cheatty': 6404.04638671875}
 65%|████████████████████████████▌               | 13/20 [1:07:20<37:01, 317.31s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/1 [00:00<?, ?it/s]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.42it/s]
Using absoulte threshold: 0.9918260892662304.
Creating first level with 20 topics. Dictionary: artm.Dictionary(name=c8880f58-b4a8-459d-939b-6d4e17581a43, num_entries=61688).
Copying phi for the first level. Phi shape: (61688, 20). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           )
Creating second level with 51 topics
Copying phi for the second level. Phi shape: (61688, 51). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 11941.9033203125, 'coherence_20': 1.2343980666151573, 'diversity_euclidean': 0.07182968590887721, 'diversity_jensenshannon': 0.695840922726394, 'diversity_hellinger': 0.8097781487213075, 'diversity_cosine': 0.8933411098477126, 'perplexity': 11941.9033203125, 'ppl_fair': 11941.9033203125, 'ppl_cheatty': 6404.04638671875}
 70%|██████████████████████████████▊             | 14/20 [1:12:37<31:42, 317.15s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/1 [00:00<?, ?it/s]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.37it/s]
Using absoulte threshold: 0.9918260892662304.
Creating first level with 20 topics. Dictionary: artm.Dictionary(name=c8880f58-b4a8-459d-939b-6d4e17581a43, num_entries=61688).
Copying phi for the first level. Phi shape: (61688, 20). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           )
Creating second level with 51 topics
Copying phi for the second level. Phi shape: (61688, 51). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 12220.9853515625, 'coherence_20': 1.2349884841277, 'diversity_euclidean': 0.07067268849460412, 'diversity_jensenshannon': 0.6936712452006281, 'diversity_hellinger': 0.8070857323047971, 'diversity_cosine': 0.8927977887766133, 'perplexity': 12220.9853515625, 'ppl_fair': 12220.9853515625, 'ppl_cheatty': 6413.28759765625}
 75%|█████████████████████████████████           | 15/20 [1:18:08<26:47, 321.52s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/1 [00:00<?, ?it/s]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.41it/s]
Using absoulte threshold: 0.9918260892662304.
Creating first level with 20 topics. Dictionary: artm.Dictionary(name=c8880f58-b4a8-459d-939b-6d4e17581a43, num_entries=61688).
Copying phi for the first level. Phi shape: (61688, 20). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           )
Creating second level with 51 topics
Copying phi for the second level. Phi shape: (61688, 51). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 10243.0380859375, 'coherence_20': 1.223723606971305, 'diversity_euclidean': 0.0699165288503625, 'diversity_jensenshannon': 0.6986660844864573, 'diversity_hellinger': 0.8132052865228567, 'diversity_cosine': 0.897576230354233, 'perplexity': 10243.0380859375, 'ppl_fair': 10243.0380859375, 'ppl_cheatty': 6010.6982421875}
 80%|███████████████████████████████████▏        | 16/20 [1:23:56<21:58, 329.55s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/1 [00:00<?, ?it/s]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.42it/s]
Using absoulte threshold: 0.9918260892662304.
Creating first level with 21 topics. Dictionary: artm.Dictionary(name=c8880f58-b4a8-459d-939b-6d4e17581a43, num_entries=61688).
Copying phi for the first level. Phi shape: (61688, 21). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           )
Creating second level with 51 topics
Copying phi for the second level. Phi shape: (61688, 51). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 10243.0380859375, 'coherence_20': 1.223723606971305, 'diversity_euclidean': 0.06991652885035739, 'diversity_jensenshannon': 0.6986660844864492, 'diversity_hellinger': 0.8132052865207822, 'diversity_cosine': 0.8975762303541931, 'perplexity': 10243.0380859375, 'ppl_fair': 10243.0380859375, 'ppl_cheatty': 6010.6982421875}
 85%|█████████████████████████████████████▍      | 17/20 [1:29:18<16:21, 327.18s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/1 [00:00<?, ?it/s]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.41it/s]
Using absoulte threshold: 0.9918260892662304.
Creating first level with 21 topics. Dictionary: artm.Dictionary(name=c8880f58-b4a8-459d-939b-6d4e17581a43, num_entries=61688).
Copying phi for the first level. Phi shape: (61688, 21). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           )
Creating second level with 51 topics
Copying phi for the second level. Phi shape: (61688, 51). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 11450.986328125, 'coherence_20': 1.1620746262671466, 'diversity_euclidean': 0.06887567701857561, 'diversity_jensenshannon': 0.6896500937558667, 'diversity_hellinger': 0.8011683157320049, 'diversity_cosine': 0.8829096008750076, 'perplexity': 11450.986328125, 'ppl_fair': 11450.986328125, 'ppl_cheatty': 6134.23974609375}
 90%|███████████████████████████████████████▌    | 18/20 [1:35:22<11:16, 338.23s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/1 [00:00<?, ?it/s]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.41it/s]
Using absoulte threshold: 0.9918260892662304.
Creating first level with 21 topics. Dictionary: artm.Dictionary(name=c8880f58-b4a8-459d-939b-6d4e17581a43, num_entries=61688).
Copying phi for the first level. Phi shape: (61688, 21). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           )
Creating second level with 51 topics
Copying phi for the second level. Phi shape: (61688, 51). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 11298.396484375, 'coherence_20': 1.1589140383647176, 'diversity_euclidean': 0.0691448355362054, 'diversity_jensenshannon': 0.6896389671004165, 'diversity_hellinger': 0.800975990258223, 'diversity_cosine': 0.8826898277031303, 'perplexity': 11298.396484375, 'ppl_fair': 11298.396484375, 'ppl_cheatty': 6092.97412109375}
 95%|█████████████████████████████████████████▊  | 19/20 [1:41:00<05:38, 338.05s/it]No spec topics
No spec topics

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).
Detected bcg topics! Skipping for diversity computation (and now 50 topics).

  0%|                                                         | 0/1 [00:00<?, ?it/s]Detected bcg topics! Skipping for coherence computation (and will have 50 topics).

100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.30it/s]
Using absoulte threshold: 0.9918260892662304.
Creating first level with 22 topics. Dictionary: artm.Dictionary(name=c8880f58-b4a8-459d-939b-6d4e17581a43, num_entries=61688).
Copying phi for the first level. Phi shape: (61688, 22). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           )
Creating second level with 51 topics
Copying phi for the second level. Phi shape: (61688, 51). First words: MultiIndex([('@lemmatized',              'рлэ'),
            ('@lemmatized',      'локационный'),
            ('@lemmatized', 'неподверженность'),
            ('@lemmatized',         'даякский'),
            ('@lemmatized',           'рэдкот'),
            ('@lemmatized',        'галоархея'),
            ('@lemmatized',          'babcock'),
            ('@lemmatized',            'лунец'),
            ('@lemmatized',   'средненапорный'),
            ('@lemmatized',           'попуск')],
           names=['modality', 'token'])
Skipping saving scores for bcg topic

/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/cooking_machine/model_constructor.py:37: UserWarning: Parameter `dictionary` is obsolete: it is not used in the function "add_standard_scores"!
  warnings.warn(

Bank scores: {'perplexity_score': 11298.396484375, 'coherence_20': 1.1589140383647176, 'diversity_euclidean': 0.06914483553623833, 'diversity_jensenshannon': 0.6896389671000702, 'diversity_hellinger': 0.8009759902579212, 'diversity_cosine': 0.8826898277026235, 'perplexity': 11298.396484375, 'ppl_fair': 11298.396484375, 'ppl_cheatty': 6092.97412109375}
100%|████████████████████████████████████████████| 20/20 [1:46:23<00:00, 319.18s/it]
CPU times: user 3h 11min 58s, sys: 4min 41s, total: 3h 16min 39s
Wall time: 1h 46min 24s

In [89]:
optimizer._main_modality

'@lemmatized'

What topics we have in bank

In [90]:
optimizer._topic_bank.view_topics().head()

                              topic_0  topic_1  topic_2  topic_3  topic_4  \
@lemmatized рлэ                   0.0      0.0      0.0      0.0      0.0
            локационный           0.0      0.0      0.0      0.0      0.0
            неподверженность      0.0      0.0      0.0      0.0      0.0
            даякский              0.0      0.0      0.0      0.0      0.0
            рэдкот                0.0      0.0      0.0      0.0      0.0

                              topic_5  topic_6  topic_7  topic_8  topic_9  \
@lemmatized рлэ                   0.0      0.0      0.0      0.0      0.0
            локационный           0.0      0.0      0.0      0.0      0.0
            неподверженность      0.0      0.0      0.0      0.0      0.0
            даякский              0.0      0.0      0.0      0.0      0.0
            рэдкот                0.0      0.0      0.0      0.0      0.0

                              ...  topic_12  topic_13  topic_14  topic_15  \
@lemmatized рлэ               ...       0.0       0.0       0.0       0.0
            локационный       ...       0.0       0.0       0.0       0.0
            неподверженность  ...       0.0       0.0       0.0       0.0
            даякский          ...       0.0       0.0       0.0       0.0
            рэдкот            ...       0.0       0.0       0.0       0.0

                              topic_16  topic_17  topic_18  topic_19  \
@lemmatized рлэ                    0.0       0.0       0.0       0.0
            локационный            0.0       0.0       0.0       0.0
            неподверженность       0.0       0.0       0.0       0.0
            даякский               0.0       0.0       0.0       0.0
            рэдкот                 0.0       0.0       0.0       0.0

                              topic_20  topic_21
@lemmatized рлэ                    0.0       0.0
            локационный            0.0       0.0
            неподверженность       0.0       0.0
            даякский               0.0       0.0
            рэдкот                 0.0       0.0

[5 rows x 22 columns]

In [91]:
bank_topics = optimizer._topic_bank.view_topics()

In [92]:
bank_topics.shape

(61688, 22)

In [93]:
bank_topics.head()

                              topic_0  topic_1  topic_2  topic_3  topic_4  \
@lemmatized рлэ                   0.0      0.0      0.0      0.0      0.0
            локационный           0.0      0.0      0.0      0.0      0.0
            неподверженность      0.0      0.0      0.0      0.0      0.0
            даякский              0.0      0.0      0.0      0.0      0.0
            рэдкот                0.0      0.0      0.0      0.0      0.0

                              topic_5  topic_6  topic_7  topic_8  topic_9  \
@lemmatized рлэ                   0.0      0.0      0.0      0.0      0.0
            локационный           0.0      0.0      0.0      0.0      0.0
            неподверженность      0.0      0.0      0.0      0.0      0.0
            даякский              0.0      0.0      0.0      0.0      0.0
            рэдкот                0.0      0.0      0.0      0.0      0.0

                              ...  topic_12  topic_13  topic_14  topic_15  \
@lemmatized рлэ               ...       0.0       0.0       0.0       0.0
            локационный       ...       0.0       0.0       0.0       0.0
            неподверженность  ...       0.0       0.0       0.0       0.0
            даякский          ...       0.0       0.0       0.0       0.0
            рэдкот            ...       0.0       0.0       0.0       0.0

                              topic_16  topic_17  topic_18  topic_19  \
@lemmatized рлэ                    0.0       0.0       0.0       0.0
            локационный            0.0       0.0       0.0       0.0
            неподверженность       0.0       0.0       0.0       0.0
            даякский               0.0       0.0       0.0       0.0
            рэдкот                 0.0       0.0       0.0       0.0

                              topic_20  topic_21
@lemmatized рлэ                    0.0       0.0
            локационный            0.0       0.0
            неподверженность       0.0       0.0
            даякский               0.0       0.0
            рэдкот                 0.0       0.0

[5 rows x 22 columns]

In [94]:
bank_topics['topic_5'].sort_values(ascending=False)[:20]

@lemmatized  игра           0.028238
             sonic          0.012376
             персонаж       0.010788
             версия         0.008670
             уровень        0.008087
             серия          0.007883
             сайт           0.005664
             игрок          0.005655
             герой          0.005283
             проект         0.004974
             final          0.004794
             fantasy        0.004590
             сюжет          0.004245
             мир            0.004234
             процесс        0.004171
             выпустить      0.004023
             playstation    0.003988
             хороший        0.003925
             игровой        0.003732
             hedgehog       0.003682
Name: topic_5, dtype: float64

And topic scores

In [95]:
optimizer._topic_bank.view_topic_scores()

,topic_0,topic_1,topic_2,topic_3,topic_4,topic_5,topic_6,topic_7,topic_8,topic_9,...,topic_12,topic_13,topic_14,topic_15,topic_16,topic_17,topic_18,topic_19,topic_20,topic_21
kernel_size,4995.000000,3361.000000,3652.000000,4251.000000,3710.000000,4818.000000,3604.000000,3997.000000,3164.000000,3199.000000,...,4409.000000,5424.000000,4725.000000,3860.000000,3918.000000,4646.000000,3871.000000,4977.000000,4024.000000,4207.000000
coherence_20,1.024162,1.195538,1.108464,1.062690,1.436570,1.007472,1.110294,1.001930,1.085643,1.817216,...,1.441053,1.090981,1.053423,1.082654,1.185210,1.015100,1.093561,1.230209,1.111099,1.092542
distance_to_nearest,0.000000,0.869286,0.874917,0.782039,0.725369,0.689765,0.858649,0.870273,0.889012,0.610435,...,0.730083,0.583112,0.736938,0.700414,0.855759,0.851559,0.544376,0.566511,0.641814,0.598573

All models are also saved (topics as $\Phi$ matrices and topic score values)

In [96]:
! ls $optimizer._topic_bank._path

model_0__phi.bin	    model_19__topic_scores.bin
model_0__topic_scores.bin   model_1__phi.bin
model_10__phi.bin	    model_1__topic_scores.bin
model_10__topic_scores.bin  model_2__phi.bin
model_11__phi.bin	    model_2__topic_scores.bin
model_11__topic_scores.bin  model_3__phi.bin
model_12__phi.bin	    model_3__topic_scores.bin
model_12__topic_scores.bin  model_4__phi.bin
model_13__phi.bin	    model_4__topic_scores.bin
model_13__topic_scores.bin  model_5__phi.bin
model_14__phi.bin	    model_5__topic_scores.bin
model_14__topic_scores.bin  model_6__phi.bin
model_15__phi.bin	    model_6__topic_scores.bin
model_15__topic_scores.bin  model_7__phi.bin
model_16__phi.bin	    model_7__topic_scores.bin
model_16__topic_scores.bin  model_8__phi.bin
model_17__phi.bin	    model_8__topic_scores.bin
model_17__topic_scores.bin  model_9__phi.bin
model_18__phi.bin	    model_9__topic_scores.bin
model_18__topic_scores.bin  topics.bin
model_19__phi.bin	    topic_scores.bin

In [109]:
optimizer._result.keys()

dict_keys(['optimum', 'optimum_std', 'bank_scores', 'bank_topic_scores', 'model_scores', 'model_topic_scores', 'num_bank_topics', 'num_model_topics'])

In [110]:
optimizer._result['num_bank_topics']

[5, 5, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9]

In [111]:
len(optimizer._result['bank_topic_scores'])

20

In [112]:
optimizer._result

{'optimum': 9,
 'optimum_std': 0.0,
 'bank_scores': [{'perplexity_score': 20257.470703125,
   'coherence_20': 1.0863093667972832,
   'diversity_euclidean': 0.0619528730977368,
   'diversity_jensenshannon': 0.7010445276298223,
   'diversity_hellinger': 0.8168848068884893,
   'diversity_cosine': 0.8948451692109236,
   'perplexity': 20257.470703125,
   'ppl_fair': 20257.470703125,
   'ppl_cheatty': 7362.07666015625},
  {'perplexity_score': 20805.96484375,
   'coherence_20': 1.0628352670334091,
   'diversity_euclidean': 0.06146307847354089,
   'diversity_jensenshannon': 0.7009344857959255,
   'diversity_hellinger': 0.8172129050151774,
   'diversity_cosine': 0.8982419304818527,
   'perplexity': 20805.96484375,
   'ppl_fair': 20805.96484375,
   'ppl_cheatty': 7570.44873046875},
  {'perplexity_score': 18369.23046875,
   'coherence_20': 1.0340908704800558,
   'diversity_euclidean': 0.06003163324628971,
   'diversity_jensenshannon': 0.699532733844726,
   'diversity_hellinger': 0.8147690493135615,
   'diversity_cosine': 0.8912036028917382,
   'perplexity': 18369.23046875,
   'ppl_fair': 18369.23046875,
   'ppl_cheatty': 7258.9873046875},
  {'perplexity_score': 18369.23046875,
   'coherence_20': 1.0340908704800558,
   'diversity_euclidean': 0.06003163324632008,
   'diversity_jensenshannon': 0.6995327338461343,
   'diversity_hellinger': 0.8147690493127235,
   'diversity_cosine': 0.8912036028930148,
   'perplexity': 18369.23046875,
   'ppl_fair': 18369.23046875,
   'ppl_cheatty': 7258.9873046875},
  {'perplexity_score': 18369.23046875,
   'coherence_20': 1.0340908704800558,
   'diversity_euclidean': 0.06003163324626595,
   'diversity_jensenshannon': 0.699532733845683,
   'diversity_hellinger': 0.8147690493128296,
   'diversity_cosine': 0.8912036028929841,
   'perplexity': 18369.23046875,
   'ppl_fair': 18369.23046875,
   'ppl_cheatty': 7258.9873046875},
  {'perplexity_score': 14237.3046875,
   'coherence_20': 1.01043349853368,
   'diversity_euclidean': 0.057325962673423526,
   'diversity_jensenshannon': 0.6972198360202069,
   'diversity_hellinger': 0.8114324120929495,
   'diversity_cosine': 0.8859822271453117,
   'perplexity': 14237.3046875,
   'ppl_fair': 14237.3046875,
   'ppl_cheatty': 7112.5283203125},
  {'perplexity_score': 14854.3681640625,
   'coherence_20': 1.014732636717317,
   'diversity_euclidean': 0.05789381957049725,
   'diversity_jensenshannon': 0.6945483943939036,
   'diversity_hellinger': 0.8073877303869053,
   'diversity_cosine': 0.8848232646428077,
   'perplexity': 14854.3681640625,
   'ppl_fair': 14854.3681640625,
   'ppl_cheatty': 7198.04931640625},
  {'perplexity_score': 14854.3681640625,
   'coherence_20': 1.014732636717317,
   'diversity_euclidean': 0.05789381957048122,
   'diversity_jensenshannon': 0.6945483943960294,
   'diversity_hellinger': 0.8073877303867254,
   'diversity_cosine': 0.8848232646468157,
   'perplexity': 14854.3681640625,
   'ppl_fair': 14854.3681640625,
   'ppl_cheatty': 7198.04931640625},
  {'perplexity_score': 14854.3681640625,
   'coherence_20': 1.014732636717317,
   'diversity_euclidean': 0.05789381957033006,
   'diversity_jensenshannon': 0.6945483944002587,
   'diversity_hellinger': 0.8073877303875766,
   'diversity_cosine': 0.8848232646541502,
   'perplexity': 14854.3681640625,
   'ppl_fair': 14854.3681640625,
   'ppl_cheatty': 7198.04931640625},
  {'perplexity_score': 12507.763671875,
   'coherence_20': 1.0148813708926725,
   'diversity_euclidean': 0.05682438684229898,
   'diversity_jensenshannon': 0.6934664372555107,
   'diversity_hellinger': 0.8061389053672338,
   'diversity_cosine': 0.8797247447874925,
   'perplexity': 12507.763671875,
   'ppl_fair': 12507.763671875,
   'ppl_cheatty': 6762.705078125},
  {'perplexity_score': 13488.5419921875,
   'coherence_20': 1.0050008231517094,
   'diversity_euclidean': 0.05817561740360074,
   'diversity_jensenshannon': 0.6825732710682779,
   'diversity_hellinger': 0.7923710384625373,
   'diversity_cosine': 0.8676679938654883,
   'perplexity': 13488.5419921875,
   'ppl_fair': 13488.5419921875,
   'ppl_cheatty': 7007.44921875},
  {'perplexity_score': 13488.5419921875,
   'coherence_20': 1.0050008231517094,
   'diversity_euclidean': 0.05817561740285033,
   'diversity_jensenshannon': 0.6825732710679179,
   'diversity_hellinger': 0.7923710384444359,
   'diversity_cosine': 0.8676679938656916,
   'perplexity': 13488.5419921875,
   'ppl_fair': 13488.5419921875,
   'ppl_cheatty': 7007.44921875},
  {'perplexity_score': 13488.5419921875,
   'coherence_20': 1.0050008231517094,
   'diversity_euclidean': 0.05817561740353957,
   'diversity_jensenshannon': 0.6825732710679675,
   'diversity_hellinger': 0.7923710384613106,
   'diversity_cosine': 0.8676679938664371,
   'perplexity': 13488.5419921875,
   'ppl_fair': 13488.5419921875,
   'ppl_cheatty': 7007.44921875},
  {'perplexity_score': 13488.5419921875,
   'coherence_20': 1.0050008231517094,
   'diversity_euclidean': 0.05817561740358906,
   'diversity_jensenshannon': 0.6825732710678478,
   'diversity_hellinger': 0.7923710384620188,
   'diversity_cosine': 0.8676679938655573,
   'perplexity': 13488.5419921875,
   'ppl_fair': 13488.5419921875,
   'ppl_cheatty': 7007.44921875},
  {'perplexity_score': 13488.5419921875,
   'coherence_20': 1.0050008231517094,
   'diversity_euclidean': 0.058175617402845735,
   'diversity_jensenshannon': 0.6825732710666969,
   'diversity_hellinger': 0.7923710384442961,
   'diversity_cosine': 0.8676679938647137,
   'perplexity': 13488.5419921875,
   'ppl_fair': 13488.5419921875,
   'ppl_cheatty': 7007.44921875},
  {'perplexity_score': 13488.5419921875,
   'coherence_20': 1.0050008231517094,
   'diversity_euclidean': 0.058175617402921966,
   'diversity_jensenshannon': 0.6825732710686013,
   'diversity_hellinger': 0.7923710384475691,
   'diversity_cosine': 0.8676679938686814,
   'perplexity': 13488.5419921875,
   'ppl_fair': 13488.5419921875,
   'ppl_cheatty': 7007.44921875},
  {'perplexity_score': 12956.1708984375,
   'coherence_20': 1.0198770555312777,
   'diversity_euclidean': 0.06300116602107929,
   'diversity_jensenshannon': 0.6894934345906877,
   'diversity_hellinger': 0.8011505487480138,
   'diversity_cosine': 0.8798738518513286,
   'perplexity': 12956.1708984375,
   'ppl_fair': 12956.1708984375,
   'ppl_cheatty': 6915.634765625},
  {'perplexity_score': 12956.1708984375,
   'coherence_20': 1.0198770555312777,
   'diversity_euclidean': 0.0630011660210848,
   'diversity_jensenshannon': 0.6894934345925926,
   'diversity_hellinger': 0.8011505487472589,
   'diversity_cosine': 0.8798738518532896,
   'perplexity': 12956.1708984375,
   'ppl_fair': 12956.1708984375,
   'ppl_cheatty': 6915.63525390625},
  {'perplexity_score': 12956.1708984375,
   'coherence_20': 1.0198770555312777,
   'diversity_euclidean': 0.06300116602098876,
   'diversity_jensenshannon': 0.6894934345894774,
   'diversity_hellinger': 0.8011505487378512,
   'diversity_cosine': 0.8798738518512682,
   'perplexity': 12956.1708984375,
   'ppl_fair': 12956.1708984375,
   'ppl_cheatty': 6915.63525390625},
  {'perplexity_score': 12956.1708984375,
   'coherence_20': 1.0198770555312777,
   'diversity_euclidean': 0.0630011660210022,
   'diversity_jensenshannon': 0.6894934345906027,
   'diversity_hellinger': 0.8011505487381404,
   'diversity_cosine': 0.8798738518529864,
   'perplexity': 12956.1708984375,
   'ppl_fair': 12956.1708984375,
   'ppl_cheatty': 6915.63525390625}],
 'bank_topic_scores': [[{'kernel_size': 5068,
    'coherence_20': 1.0297691355246918,
    'distance_to_nearest': 0.0},
   {'kernel_size': 5007,
    'coherence_20': 1.1756616093491055,
    'distance_to_nearest': 0.9197807889016681},
   {'kernel_size': 4070,
    'coherence_20': 1.3298810340740868,
    'distance_to_nearest': 0.8783019854111281},
   {'kernel_size': 4652,
    'coherence_20': 0.9104903714039343,
    'distance_to_nearest': 0.8806710301929691},
   {'kernel_size': 4803,
    'coherence_20': 0.9857446836345978,
    'distance_to_nearest': 0.8523585978250594}],
  [{'kernel_size': 5068,
    'coherence_20': 1.0297691355246918,
    'distance_to_nearest': 0.0},
   {'kernel_size': 5007,
    'coherence_20': 1.1756616093491055,
    'distance_to_nearest': 0.9197807889016681},
   {'kernel_size': 4070,
    'coherence_20': 1.3298810340740868,
    'distance_to_nearest': 0.8783019854111281},
   {'kernel_size': 4652,
    'coherence_20': 0.9104903714039343,
    'distance_to_nearest': 0.8806710301929691},
   {'kernel_size': 5384,
    'coherence_20': 0.8683741848152282,
    'distance_to_nearest': 0.6518186505277321}],
  [{'kernel_size': 5068,
    'coherence_20': 1.0297691355246918,
    'distance_to_nearest': 0.0},
   {'kernel_size': 4070,
    'coherence_20': 1.3298810340740868,
    'distance_to_nearest': 0.8783019854111281},
   {'kernel_size': 4652,
    'coherence_20': 0.9104903714039343,
    'distance_to_nearest': 0.8806710301929691},
   {'kernel_size': 5384,
    'coherence_20': 0.8683741848152282,
    'distance_to_nearest': 0.6518186505277321},
   {'kernel_size': 5097,
    'coherence_20': 0.8732924274477326,
    'distance_to_nearest': 0.7920755781872806},
   {'kernel_size': 4785,
    'coherence_20': 1.1927380696146608,
    'distance_to_nearest': 0.8226825750211674}],
  [{'kernel_size': 5068,
    'coherence_20': 1.0297691355246918,
    'distance_to_nearest': 0.0},
   {'kernel_size': 4070,
    'coherence_20': 1.3298810340740868,
    'distance_to_nearest': 0.8783019854111281},
   {'kernel_size': 4652,
    'coherence_20': 0.9104903714039343,
    'distance_to_nearest': 0.8806710301929691},
   {'kernel_size': 5384,
    'coherence_20': 0.8683741848152282,
    'distance_to_nearest': 0.6518186505277321},
   {'kernel_size': 5097,
    'coherence_20': 0.8732924274477326,
    'distance_to_nearest': 0.7920755781872806},
   {'kernel_size': 4785,
    'coherence_20': 1.1927380696146608,
    'distance_to_nearest': 0.8226825750211674}],
  [{'kernel_size': 5068,
    'coherence_20': 1.0297691355246918,
    'distance_to_nearest': 0.0},
   {'kernel_size': 4070,
    'coherence_20': 1.3298810340740868,
    'distance_to_nearest': 0.8783019854111281},
   {'kernel_size': 4652,
    'coherence_20': 0.9104903714039343,
    'distance_to_nearest': 0.8806710301929691},
   {'kernel_size': 5384,
    'coherence_20': 0.8683741848152282,
    'distance_to_nearest': 0.6518186505277321},
   {'kernel_size': 5097,
    'coherence_20': 0.8732924274477326,
    'distance_to_nearest': 0.7920755781872806},
   {'kernel_size': 4785,
    'coherence_20': 1.1927380696146608,
    'distance_to_nearest': 0.8226825750211674}],
  [{'kernel_size': 5068,
    'coherence_20': 1.0297691355246918,
    'distance_to_nearest': 0.0},
   {'kernel_size': 4070,
    'coherence_20': 1.3298810340740868,
    'distance_to_nearest': 0.8783019854111281},
   {'kernel_size': 4652,
    'coherence_20': 0.9104903714039343,
    'distance_to_nearest': 0.8806710301929691},
   {'kernel_size': 5384,
    'coherence_20': 0.8683741848152282,
    'distance_to_nearest': 0.6518186505277321},
   {'kernel_size': 5097,
    'coherence_20': 0.8732924274477326,
    'distance_to_nearest': 0.7920755781872806},
   {'kernel_size': 4785,
    'coherence_20': 1.1927380696146608,
    'distance_to_nearest': 0.8226825750211674},
   {'kernel_size': 5697,
    'coherence_20': 0.8684892668554253,
    'distance_to_nearest': 0.8484545037818898}],
  [{'kernel_size': 5068,
    'coherence_20': 1.0297691355246918,
    'distance_to_nearest': 0.0},
   {'kernel_size': 4070,
    'coherence_20': 1.3298810340740868,
    'distance_to_nearest': 0.8783019854111281},
   {'kernel_size': 4652,
    'coherence_20': 0.9104903714039343,
    'distance_to_nearest': 0.8806710301929691},
   {'kernel_size': 5097,
    'coherence_20': 0.8732924274477326,
    'distance_to_nearest': 0.7920755781872806},
   {'kernel_size': 4785,
    'coherence_20': 1.1927380696146608,
    'distance_to_nearest': 0.8226825750211674},
   {'kernel_size': 5697,
    'coherence_20': 0.8684892668554253,
    'distance_to_nearest': 0.8484545037818898},
   {'kernel_size': 4689,
    'coherence_20': 0.8984681521006888,
    'distance_to_nearest': 0.8435919720118529}],
  [{'kernel_size': 5068,
    'coherence_20': 1.0297691355246918,
    'distance_to_nearest': 0.0},
   {'kernel_size': 4070,
    'coherence_20': 1.3298810340740868,
    'distance_to_nearest': 0.8783019854111281},
   {'kernel_size': 4652,
    'coherence_20': 0.9104903714039343,
    'distance_to_nearest': 0.8806710301929691},
   {'kernel_size': 5097,
    'coherence_20': 0.8732924274477326,
    'distance_to_nearest': 0.7920755781872806},
   {'kernel_size': 4785,
    'coherence_20': 1.1927380696146608,
    'distance_to_nearest': 0.8226825750211674},
   {'kernel_size': 5697,
    'coherence_20': 0.8684892668554253,
    'distance_to_nearest': 0.8484545037818898},
   {'kernel_size': 4689,
    'coherence_20': 0.8984681521006888,
    'distance_to_nearest': 0.8435919720118529}],
  [{'kernel_size': 5068,
    'coherence_20': 1.0297691355246918,
    'distance_to_nearest': 0.0},
   {'kernel_size': 4070,
    'coherence_20': 1.3298810340740868,
    'distance_to_nearest': 0.8783019854111281},
   {'kernel_size': 4652,
    'coherence_20': 0.9104903714039343,
    'distance_to_nearest': 0.8806710301929691},
   {'kernel_size': 5097,
    'coherence_20': 0.8732924274477326,
    'distance_to_nearest': 0.7920755781872806},
   {'kernel_size': 4785,
    'coherence_20': 1.1927380696146608,
    'distance_to_nearest': 0.8226825750211674},
   {'kernel_size': 5697,
    'coherence_20': 0.8684892668554253,
    'distance_to_nearest': 0.8484545037818898},
   {'kernel_size': 4689,
    'coherence_20': 0.8984681521006888,
    'distance_to_nearest': 0.8435919720118529}],
  [{'kernel_size': 5068,
    'coherence_20': 1.0297691355246918,
    'distance_to_nearest': 0.0},
   {'kernel_size': 4070,
    'coherence_20': 1.3298810340740868,
    'distance_to_nearest': 0.8783019854111281},
   {'kernel_size': 4652,
    'coherence_20': 0.9104903714039343,
    'distance_to_nearest': 0.8806710301929691},
   {'kernel_size': 5097,
    'coherence_20': 0.8732924274477326,
    'distance_to_nearest': 0.7920755781872806},
   {'kernel_size': 4785,
    'coherence_20': 1.1927380696146608,
    'distance_to_nearest': 0.8226825750211674},
   {'kernel_size': 5697,
    'coherence_20': 0.8684892668554253,
    'distance_to_nearest': 0.8484545037818898},
   {'kernel_size': 4689,
    'coherence_20': 0.8984681521006888,
    'distance_to_nearest': 0.8435919720118529},
   {'kernel_size': 5057,
    'coherence_20': 1.015922510120161,
    'distance_to_nearest': 0.8612299059752945}],
  [{'kernel_size': 5068,
    'coherence_20': 1.0297691355246918,
    'distance_to_nearest': 0.0},
   {'kernel_size': 4070,
    'coherence_20': 1.3298810340740868,
    'distance_to_nearest': 0.8783019854111281},
   {'kernel_size': 4652,
    'coherence_20': 0.9104903714039343,
    'distance_to_nearest': 0.8806710301929691},
   {'kernel_size': 5097,
    'coherence_20': 0.8732924274477326,
    'distance_to_nearest': 0.7920755781872806},
   {'kernel_size': 5697,
    'coherence_20': 0.8684892668554253,
    'distance_to_nearest': 0.8484545037818898},
   {'kernel_size': 4689,
    'coherence_20': 0.8984681521006888,
    'distance_to_nearest': 0.8435919720118529},
   {'kernel_size': 5057,
    'coherence_20': 1.015922510120161,
    'distance_to_nearest': 0.8612299059752945},
   {'kernel_size': 4407,
    'coherence_20': 1.1136936876869548,
    'distance_to_nearest': 0.6077845200819454}],
  [{'kernel_size': 5068,
    'coherence_20': 1.0297691355246918,
    'distance_to_nearest': 0.0},
   {'kernel_size': 4070,
    'coherence_20': 1.3298810340740868,
    'distance_to_nearest': 0.8783019854111281},
   {'kernel_size': 4652,
    'coherence_20': 0.9104903714039343,
    'distance_to_nearest': 0.8806710301929691},
   {'kernel_size': 5097,
    'coherence_20': 0.8732924274477326,
    'distance_to_nearest': 0.7920755781872806},
   {'kernel_size': 5697,
    'coherence_20': 0.8684892668554253,
    'distance_to_nearest': 0.8484545037818898},
   {'kernel_size': 4689,
    'coherence_20': 0.8984681521006888,
    'distance_to_nearest': 0.8435919720118529},
   {'kernel_size': 5057,
    'coherence_20': 1.015922510120161,
    'distance_to_nearest': 0.8612299059752945},
   {'kernel_size': 4407,
    'coherence_20': 1.1136936876869548,
    'distance_to_nearest': 0.6077845200819454}],
  [{'kernel_size': 5068,
    'coherence_20': 1.0297691355246918,
    'distance_to_nearest': 0.0},
   {'kernel_size': 4070,
    'coherence_20': 1.3298810340740868,
    'distance_to_nearest': 0.8783019854111281},
   {'kernel_size': 4652,
    'coherence_20': 0.9104903714039343,
    'distance_to_nearest': 0.8806710301929691},
   {'kernel_size': 5097,
    'coherence_20': 0.8732924274477326,
    'distance_to_nearest': 0.7920755781872806},
   {'kernel_size': 5697,
    'coherence_20': 0.8684892668554253,
    'distance_to_nearest': 0.8484545037818898},
   {'kernel_size': 4689,
    'coherence_20': 0.8984681521006888,
    'distance_to_nearest': 0.8435919720118529},
   {'kernel_size': 5057,
    'coherence_20': 1.015922510120161,
    'distance_to_nearest': 0.8612299059752945},
   {'kernel_size': 4407,
    'coherence_20': 1.1136936876869548,
    'distance_to_nearest': 0.6077845200819454}],
  [{'kernel_size': 5068,
    'coherence_20': 1.0297691355246918,
    'distance_to_nearest': 0.0},
   {'kernel_size': 4070,
    'coherence_20': 1.3298810340740868,
    'distance_to_nearest': 0.8783019854111281},
   {'kernel_size': 4652,
    'coherence_20': 0.9104903714039343,
    'distance_to_nearest': 0.8806710301929691},
   {'kernel_size': 5097,
    'coherence_20': 0.8732924274477326,
    'distance_to_nearest': 0.7920755781872806},
   {'kernel_size': 5697,
    'coherence_20': 0.8684892668554253,
    'distance_to_nearest': 0.8484545037818898},
   {'kernel_size': 4689,
    'coherence_20': 0.8984681521006888,
    'distance_to_nearest': 0.8435919720118529},
   {'kernel_size': 5057,
    'coherence_20': 1.015922510120161,
    'distance_to_nearest': 0.8612299059752945},
   {'kernel_size': 4407,
    'coherence_20': 1.1136936876869548,
    'distance_to_nearest': 0.6077845200819454}],
  [{'kernel_size': 5068,
    'coherence_20': 1.0297691355246918,
    'distance_to_nearest': 0.0},
   {'kernel_size': 4070,
    'coherence_20': 1.3298810340740868,
    'distance_to_nearest': 0.8783019854111281},
   {'kernel_size': 4652,
    'coherence_20': 0.9104903714039343,
    'distance_to_nearest': 0.8806710301929691},
   {'kernel_size': 5097,
    'coherence_20': 0.8732924274477326,
    'distance_to_nearest': 0.7920755781872806},
   {'kernel_size': 5697,
    'coherence_20': 0.8684892668554253,
    'distance_to_nearest': 0.8484545037818898},
   {'kernel_size': 4689,
    'coherence_20': 0.8984681521006888,
    'distance_to_nearest': 0.8435919720118529},
   {'kernel_size': 5057,
    'coherence_20': 1.015922510120161,
    'distance_to_nearest': 0.8612299059752945},
   {'kernel_size': 4407,
    'coherence_20': 1.1136936876869548,
    'distance_to_nearest': 0.6077845200819454}],
  [{'kernel_size': 5068,
    'coherence_20': 1.0297691355246918,
    'distance_to_nearest': 0.0},
   {'kernel_size': 4070,
    'coherence_20': 1.3298810340740868,
    'distance_to_nearest': 0.8783019854111281},
   {'kernel_size': 4652,
    'coherence_20': 0.9104903714039343,
    'distance_to_nearest': 0.8806710301929691},
   {'kernel_size': 5097,
    'coherence_20': 0.8732924274477326,
    'distance_to_nearest': 0.7920755781872806},
   {'kernel_size': 5697,
    'coherence_20': 0.8684892668554253,
    'distance_to_nearest': 0.8484545037818898},
   {'kernel_size': 4689,
    'coherence_20': 0.8984681521006888,
    'distance_to_nearest': 0.8435919720118529},
   {'kernel_size': 5057,
    'coherence_20': 1.015922510120161,
    'distance_to_nearest': 0.8612299059752945},
   {'kernel_size': 4407,
    'coherence_20': 1.1136936876869548,
    'distance_to_nearest': 0.6077845200819454}],
  [{'kernel_size': 5068,
    'coherence_20': 1.0297691355246918,
    'distance_to_nearest': 0.0},
   {'kernel_size': 4070,

In [113]:
optimizer._result['bank_topic_scores']

[[{'kernel_size': 5068,
   'coherence_20': 1.0297691355246918,
   'distance_to_nearest': 0.0},
  {'kernel_size': 5007,
   'coherence_20': 1.1756616093491055,
   'distance_to_nearest': 0.9197807889016681},
  {'kernel_size': 4070,
   'coherence_20': 1.3298810340740868,
   'distance_to_nearest': 0.8783019854111281},
  {'kernel_size': 4652,
   'coherence_20': 0.9104903714039343,
   'distance_to_nearest': 0.8806710301929691},
  {'kernel_size': 4803,
   'coherence_20': 0.9857446836345978,
   'distance_to_nearest': 0.8523585978250594}],
 [{'kernel_size': 5068,
   'coherence_20': 1.0297691355246918,
   'distance_to_nearest': 0.0},
  {'kernel_size': 5007,
   'coherence_20': 1.1756616093491055,
   'distance_to_nearest': 0.9197807889016681},
  {'kernel_size': 4070,
   'coherence_20': 1.3298810340740868,
   'distance_to_nearest': 0.8783019854111281},
  {'kernel_size': 4652,
   'coherence_20': 0.9104903714039343,
   'distance_to_nearest': 0.8806710301929691},
  {'kernel_size': 5384,
   'coherence_20': 0.8683741848152282,
   'distance_to_nearest': 0.6518186505277321}],
 [{'kernel_size': 5068,
   'coherence_20': 1.0297691355246918,
   'distance_to_nearest': 0.0},
  {'kernel_size': 4070,
   'coherence_20': 1.3298810340740868,
   'distance_to_nearest': 0.8783019854111281},
  {'kernel_size': 4652,
   'coherence_20': 0.9104903714039343,
   'distance_to_nearest': 0.8806710301929691},
  {'kernel_size': 5384,
   'coherence_20': 0.8683741848152282,
   'distance_to_nearest': 0.6518186505277321},
  {'kernel_size': 5097,
   'coherence_20': 0.8732924274477326,
   'distance_to_nearest': 0.7920755781872806},
  {'kernel_size': 4785,
   'coherence_20': 1.1927380696146608,
   'distance_to_nearest': 0.8226825750211674}],
 [{'kernel_size': 5068,
   'coherence_20': 1.0297691355246918,
   'distance_to_nearest': 0.0},
  {'kernel_size': 4070,
   'coherence_20': 1.3298810340740868,
   'distance_to_nearest': 0.8783019854111281},
  {'kernel_size': 4652,
   'coherence_20': 0.9104903714039343,
   'distance_to_nearest': 0.8806710301929691},
  {'kernel_size': 5384,
   'coherence_20': 0.8683741848152282,
   'distance_to_nearest': 0.6518186505277321},
  {'kernel_size': 5097,
   'coherence_20': 0.8732924274477326,
   'distance_to_nearest': 0.7920755781872806},
  {'kernel_size': 4785,
   'coherence_20': 1.1927380696146608,
   'distance_to_nearest': 0.8226825750211674}],
 [{'kernel_size': 5068,
   'coherence_20': 1.0297691355246918,
   'distance_to_nearest': 0.0},
  {'kernel_size': 4070,
   'coherence_20': 1.3298810340740868,
   'distance_to_nearest': 0.8783019854111281},
  {'kernel_size': 4652,
   'coherence_20': 0.9104903714039343,
   'distance_to_nearest': 0.8806710301929691},
  {'kernel_size': 5384,
   'coherence_20': 0.8683741848152282,
   'distance_to_nearest': 0.6518186505277321},
  {'kernel_size': 5097,
   'coherence_20': 0.8732924274477326,
   'distance_to_nearest': 0.7920755781872806},
  {'kernel_size': 4785,
   'coherence_20': 1.1927380696146608,
   'distance_to_nearest': 0.8226825750211674}],
 [{'kernel_size': 5068,
   'coherence_20': 1.0297691355246918,
   'distance_to_nearest': 0.0},
  {'kernel_size': 4070,
   'coherence_20': 1.3298810340740868,
   'distance_to_nearest': 0.8783019854111281},
  {'kernel_size': 4652,
   'coherence_20': 0.9104903714039343,
   'distance_to_nearest': 0.8806710301929691},
  {'kernel_size': 5384,
   'coherence_20': 0.8683741848152282,
   'distance_to_nearest': 0.6518186505277321},
  {'kernel_size': 5097,
   'coherence_20': 0.8732924274477326,
   'distance_to_nearest': 0.7920755781872806},
  {'kernel_size': 4785,
   'coherence_20': 1.1927380696146608,
   'distance_to_nearest': 0.8226825750211674},
  {'kernel_size': 5697,
   'coherence_20': 0.8684892668554253,
   'distance_to_nearest': 0.8484545037818898}],
 [{'kernel_size': 5068,
   'coherence_20': 1.0297691355246918,
   'distance_to_nearest': 0.0},
  {'kernel_size': 4070,
   'coherence_20': 1.3298810340740868,
   'distance_to_nearest': 0.8783019854111281},
  {'kernel_size': 4652,
   'coherence_20': 0.9104903714039343,
   'distance_to_nearest': 0.8806710301929691},
  {'kernel_size': 5097,
   'coherence_20': 0.8732924274477326,
   'distance_to_nearest': 0.7920755781872806},
  {'kernel_size': 4785,
   'coherence_20': 1.1927380696146608,
   'distance_to_nearest': 0.8226825750211674},
  {'kernel_size': 5697,
   'coherence_20': 0.8684892668554253,
   'distance_to_nearest': 0.8484545037818898},
  {'kernel_size': 4689,
   'coherence_20': 0.8984681521006888,
   'distance_to_nearest': 0.8435919720118529}],
 [{'kernel_size': 5068,
   'coherence_20': 1.0297691355246918,
   'distance_to_nearest': 0.0},
  {'kernel_size': 4070,
   'coherence_20': 1.3298810340740868,
   'distance_to_nearest': 0.8783019854111281},
  {'kernel_size': 4652,
   'coherence_20': 0.9104903714039343,
   'distance_to_nearest': 0.8806710301929691},
  {'kernel_size': 5097,
   'coherence_20': 0.8732924274477326,
   'distance_to_nearest': 0.7920755781872806},
  {'kernel_size': 4785,
   'coherence_20': 1.1927380696146608,
   'distance_to_nearest': 0.8226825750211674},
  {'kernel_size': 5697,
   'coherence_20': 0.8684892668554253,
   'distance_to_nearest': 0.8484545037818898},
  {'kernel_size': 4689,
   'coherence_20': 0.8984681521006888,
   'distance_to_nearest': 0.8435919720118529}],
 [{'kernel_size': 5068,
   'coherence_20': 1.0297691355246918,
   'distance_to_nearest': 0.0},
  {'kernel_size': 4070,
   'coherence_20': 1.3298810340740868,
   'distance_to_nearest': 0.8783019854111281},
  {'kernel_size': 4652,
   'coherence_20': 0.9104903714039343,
   'distance_to_nearest': 0.8806710301929691},
  {'kernel_size': 5097,
   'coherence_20': 0.8732924274477326,
   'distance_to_nearest': 0.7920755781872806},
  {'kernel_size': 4785,
   'coherence_20': 1.1927380696146608,
   'distance_to_nearest': 0.8226825750211674},
  {'kernel_size': 5697,
   'coherence_20': 0.8684892668554253,
   'distance_to_nearest': 0.8484545037818898},
  {'kernel_size': 4689,
   'coherence_20': 0.8984681521006888,
   'distance_to_nearest': 0.8435919720118529}],
 [{'kernel_size': 5068,
   'coherence_20': 1.0297691355246918,
   'distance_to_nearest': 0.0},
  {'kernel_size': 4070,
   'coherence_20': 1.3298810340740868,
   'distance_to_nearest': 0.8783019854111281},
  {'kernel_size': 4652,
   'coherence_20': 0.9104903714039343,
   'distance_to_nearest': 0.8806710301929691},
  {'kernel_size': 5097,
   'coherence_20': 0.8732924274477326,
   'distance_to_nearest': 0.7920755781872806},
  {'kernel_size': 4785,
   'coherence_20': 1.1927380696146608,
   'distance_to_nearest': 0.8226825750211674},
  {'kernel_size': 5697,
   'coherence_20': 0.8684892668554253,
   'distance_to_nearest': 0.8484545037818898},
  {'kernel_size': 4689,
   'coherence_20': 0.8984681521006888,
   'distance_to_nearest': 0.8435919720118529},
  {'kernel_size': 5057,
   'coherence_20': 1.015922510120161,
   'distance_to_nearest': 0.8612299059752945}],
 [{'kernel_size': 5068,
   'coherence_20': 1.0297691355246918,
   'distance_to_nearest': 0.0},
  {'kernel_size': 4070,
   'coherence_20': 1.3298810340740868,
   'distance_to_nearest': 0.8783019854111281},
  {'kernel_size': 4652,
   'coherence_20': 0.9104903714039343,
   'distance_to_nearest': 0.8806710301929691},
  {'kernel_size': 5097,
   'coherence_20': 0.8732924274477326,
   'distance_to_nearest': 0.7920755781872806},
  {'kernel_size': 5697,
   'coherence_20': 0.8684892668554253,
   'distance_to_nearest': 0.8484545037818898},
  {'kernel_size': 4689,
   'coherence_20': 0.8984681521006888,
   'distance_to_nearest': 0.8435919720118529},
  {'kernel_size': 5057,
   'coherence_20': 1.015922510120161,
   'distance_to_nearest': 0.8612299059752945},
  {'kernel_size': 4407,
   'coherence_20': 1.1136936876869548,
   'distance_to_nearest': 0.6077845200819454}],
 [{'kernel_size': 5068,
   'coherence_20': 1.0297691355246918,
   'distance_to_nearest': 0.0},
  {'kernel_size': 4070,
   'coherence_20': 1.3298810340740868,
   'distance_to_nearest': 0.8783019854111281},
  {'kernel_size': 4652,
   'coherence_20': 0.9104903714039343,
   'distance_to_nearest': 0.8806710301929691},
  {'kernel_size': 5097,
   'coherence_20': 0.8732924274477326,
   'distance_to_nearest': 0.7920755781872806},
  {'kernel_size': 5697,
   'coherence_20': 0.8684892668554253,
   'distance_to_nearest': 0.8484545037818898},
  {'kernel_size': 4689,
   'coherence_20': 0.8984681521006888,
   'distance_to_nearest': 0.8435919720118529},
  {'kernel_size': 5057,
   'coherence_20': 1.015922510120161,
   'distance_to_nearest': 0.8612299059752945},
  {'kernel_size': 4407,
   'coherence_20': 1.1136936876869548,
   'distance_to_nearest': 0.6077845200819454}],
 [{'kernel_size': 5068,
   'coherence_20': 1.0297691355246918,
   'distance_to_nearest': 0.0},
  {'kernel_size': 4070,
   'coherence_20': 1.3298810340740868,
   'distance_to_nearest': 0.8783019854111281},
  {'kernel_size': 4652,
   'coherence_20': 0.9104903714039343,
   'distance_to_nearest': 0.8806710301929691},
  {'kernel_size': 5097,
   'coherence_20': 0.8732924274477326,
   'distance_to_nearest': 0.7920755781872806},
  {'kernel_size': 5697,
   'coherence_20': 0.8684892668554253,
   'distance_to_nearest': 0.8484545037818898},
  {'kernel_size': 4689,
   'coherence_20': 0.8984681521006888,
   'distance_to_nearest': 0.8435919720118529},
  {'kernel_size': 5057,
   'coherence_20': 1.015922510120161,
   'distance_to_nearest': 0.8612299059752945},
  {'kernel_size': 4407,
   'coherence_20': 1.1136936876869548,
   'distance_to_nearest': 0.6077845200819454}],
 [{'kernel_size': 5068,
   'coherence_20': 1.0297691355246918,
   'distance_to_nearest': 0.0},
  {'kernel_size': 4070,
   'coherence_20': 1.3298810340740868,
   'distance_to_nearest': 0.8783019854111281},
  {'kernel_size': 4652,
   'coherence_20': 0.9104903714039343,
   'distance_to_nearest': 0.8806710301929691},
  {'kernel_size': 5097,
   'coherence_20': 0.8732924274477326,
   'distance_to_nearest': 0.7920755781872806},
  {'kernel_size': 5697,
   'coherence_20': 0.8684892668554253,
   'distance_to_nearest': 0.8484545037818898},
  {'kernel_size': 4689,
   'coherence_20': 0.8984681521006888,
   'distance_to_nearest': 0.8435919720118529},
  {'kernel_size': 5057,
   'coherence_20': 1.015922510120161,
   'distance_to_nearest': 0.8612299059752945},
  {'kernel_size': 4407,
   'coherence_20': 1.1136936876869548,
   'distance_to_nearest': 0.6077845200819454}],
 [{'kernel_size': 5068,
   'coherence_20': 1.0297691355246918,
   'distance_to_nearest': 0.0},
  {'kernel_size': 4070,
   'coherence_20': 1.3298810340740868,
   'distance_to_nearest': 0.8783019854111281},
  {'kernel_size': 4652,
   'coherence_20': 0.9104903714039343,
   'distance_to_nearest': 0.8806710301929691},
  {'kernel_size': 5097,
   'coherence_20': 0.8732924274477326,
   'distance_to_nearest': 0.7920755781872806},
  {'kernel_size': 5697,
   'coherence_20': 0.8684892668554253,
   'distance_to_nearest': 0.8484545037818898},
  {'kernel_size': 4689,
   'coherence_20': 0.8984681521006888,
   'distance_to_nearest': 0.8435919720118529},
  {'kernel_size': 5057,
   'coherence_20': 1.015922510120161,
   'distance_to_nearest': 0.8612299059752945},
  {'kernel_size': 4407,
   'coherence_20': 1.1136936876869548,
   'distance_to_nearest': 0.6077845200819454}],
 [{'kernel_size': 5068,
   'coherence_20': 1.0297691355246918,
   'distance_to_nearest': 0.0},
  {'kernel_size': 4070,
   'coherence_20': 1.3298810340740868,
   'distance_to_nearest': 0.8783019854111281},
  {'kernel_size': 4652,
   'coherence_20': 0.9104903714039343,
   'distance_to_nearest': 0.8806710301929691},
  {'kernel_size': 5097,
   'coherence_20': 0.8732924274477326,
   'distance_to_nearest': 0.7920755781872806},
  {'kernel_size': 5697,
   'coherence_20': 0.8684892668554253,
   'distance_to_nearest': 0.8484545037818898},
  {'kernel_size': 4689,
   'coherence_20': 0.8984681521006888,
   'distance_to_nearest': 0.8435919720118529},
  {'kernel_size': 5057,
   'coherence_20': 1.015922510120161,
   'distance_to_nearest': 0.8612299059752945},
  {'kernel_size': 4407,
   'coherence_20': 1.1136936876869548,
   'distance_to_nearest': 0.6077845200819454}],
 [{'kernel_size': 5068,
   'coherence_20': 1.0297691355246918,
   'distance_to_nearest': 0.0},
  {'kernel_size': 4070,
   'coherence_20': 1.3298810340740868,
   'distance_to_nearest': 0.8783019854111281},
  {'kernel_size': 4652,
   'coherence_20': 0.9104903714039343,
   'distance_to_nearest': 0.8806710301929691},
  {'kernel_size': 5097,
   'coherence_20': 0.8732924274477326,
   'distance_to_nearest': 0.7920755781872806},
  {'kernel_size': 5697,
   'coherence_20': 0.8684892668554253,
   'distance_to_nearest': 0.8484545037818898},
  {'kernel_size': 4689,
   'coherence_20': 0.8984681521006888,
   'distance_to_nearest': 0.8435919720118529},
  {'kernel_size': 5057,
   'coherence_20': 1.015922510120161,
   'distance_to_nearest': 0.8612299059752945},
  {'kernel_size': 4407,
   'coherence_20': 1.1136936876869548,
   'distance_to_nearest': 0.6077845200819454},
  {'kernel_size': 3169,
   'coherence_20': 1.1388869145678242,
   'distance_to_nearest': 0.8845605346474589}],
 [{'kernel_size': 5068,
   'coherence_20': 1.0297691355246918,
   'distance_to_nearest': 0.0},
  {'kernel_size': 4070,
   'coherence_20': 1.3298810340740868,
   'distance_to_nearest': 0.8783019854111281},
  {'kernel_size': 4652,
   'coherence_20': 0.9104903714039343,
   'distance_to_nearest': 0.8806710301929691},
  {'kernel_size': 5097,
   'coherence_20': 0.8732924274477326,
   'distance_to_nearest': 0.7920755781872806},
  {'kernel_size': 5697,
   'coherence_20': 0.8684892668554253,
   'distance_to_nearest': 0.8484545037818898},
  {'kernel_size': 4689,
   'coherence_20': 0.8984681521006888,
   'distance_to_nearest': 0.8435919720118529},
  {'kernel_size': 5057,
   'coherence_20': 1.015922510120161,
   'distance_to_nearest': 0.8612299059752945},
  {'kernel_size': 4407,
   'coherence_20': 1.1136936876869548,
   'distance_to_nearest': 0.6077845200819454},
  {'kernel_size': 3169,
   'coherence_20': 1.1388869145678242,
   'distance_to_nearest': 0.8845605346474589}],
 [{'kernel_size': 5068,
   'coherence_20': 1.0297691355246918,
   'distance_to_nearest': 0.0},
  {'kernel_size': 4070,
   'coherence_20': 1.3298810340740868,
   'distance_to_nearest': 0.8783019854111281},
  {'kernel_size': 4652,
   'coherence_20': 0.9104903714039343,
   'distance_to_nearest': 0.8806710301929691},
  {'kernel_size': 5097,
   'coherence_20': 0.8732924274477326,
   'distance_to_nearest': 0.7920755781872806},
  {'kernel_size': 5697,
   'coherence_20': 0.8684892668554253,
   'distance_to_nearest': 0.8484545037818898},
  {'kernel_size': 4689,
   'coherence_20': 0.8984681521006888,
   'distance_to_nearest': 0.8435919720118529},
  {'kernel_size': 5057,
   'coherence_20': 1.015922510120161,
   'distance_to_nearest': 0.8612299059752945},
  {'kernel_size': 4407,
   'coherence_20': 1.1136936876869548,
   'distance_to_nearest': 0.6077845200819454},
  {'kernel_size': 3169,
   'coherence_20': 1.1388869145678242,
   'distance_to_nearest': 0.8845605346474589}],
 [{'kernel_size': 5068,
   'coherence_20': 1.0297691355246918,
   'distance_to_nearest': 0.0},
  {'kernel_size': 4070,
   'coherence_20': 1.3298810340740868,
   'distance_to_nearest': 0.8783019854111281},
  {'kernel_size': 4652,
   'coherence_20': 0.9104903714039343,
   'distance_to_nearest': 0.8806710301929691},
  {'kernel_size': 5097,
   'coherence_20': 0.8732924274477326,
   'distance_to_nearest': 0.7920755781872806},
  {'kernel_size': 5697,
   'coherence_20': 0.8684892668554253,
   'distance_to_nearest': 0.8484545037818898},
  {'kernel_size': 4689,
   'coherence_20': 0.8984681521006888,
   'distance_to_nearest': 0.8435919720118529},
  {'kernel_size': 5057,
   'coherence_20': 1.015922510120161,
   'distance_to_nearest': 0.8612299059752945},
  {'kernel_size': 4407,
   'coherence_20': 1.1136936876869548,
   'distance_to_nearest': 0.6077845200819454},
  {'kernel_size': 3169,
   'coherence_20': 1.1388869145678242,
   'distance_to_nearest': 0.8845605346474589}]]

In [114]:
optimizer._result['model_scores'][0]

{'perplexity_score': 4860.8017578125,
 'coherence_20': 0.6750048319629702,
 'diversity_euclidean': 0.05157965876247023,
 'diversity_jensenshannon': 0.6647405644367678,
 'diversity_hellinger': 0.7666404062821004,
 'diversity_cosine': 0.8294436907285049,
 'perplexity': 4860.8017578125}

In [118]:
sum(s['coherence_20'] for s in optimizer._result['bank_topic_scores'][-1]) / 9

1.0198770555312775

In [119]:
len(optimizer._result['bank_scores'])

20

In [120]:
optimizer._result['bank_scores'][-1]

{'perplexity_score': 12956.1708984375,
 'coherence_20': 1.0198770555312777,
 'diversity_euclidean': 0.0630011660210022,
 'diversity_jensenshannon': 0.6894934345906027,
 'diversity_hellinger': 0.8011505487381404,
 'diversity_cosine': 0.8798738518529864,
 'perplexity': 12956.1708984375,
 'ppl_fair': 12956.1708984375,
 'ppl_cheatty': 6915.63525390625}

In [121]:
optimizer._result['model_topic_scores']

[[{'kernel_size': 5842, 'coherence_20': 0.6362738850913598},
  {'kernel_size': 5796, 'coherence_20': 0.7017274275328904},
  {'kernel_size': 4873, 'coherence_20': 0.4808373246649988},
  {'kernel_size': 4946, 'coherence_20': 0.5641984460697425},
  {'kernel_size': 5715, 'coherence_20': 0.5445732395217968},
  {'kernel_size': 5068, 'coherence_20': 0.4520213308964054},
  {'kernel_size': 5068,
   'coherence_20': 1.0297691355246918,
   'distance_to_nearest': 0.0},
  {'kernel_size': 5805, 'coherence_20': 0.5174446740493418},
  {'kernel_size': 5254, 'coherence_20': 0.4274255286876996},
  {'kernel_size': 5007,
   'coherence_20': 1.1756616093491055,
   'distance_to_nearest': 0.9197807889016681},
  {'kernel_size': 5578, 'coherence_20': 0.6489807489743467},
  {'kernel_size': 4070,
   'coherence_20': 1.3298810340740868,
   'distance_to_nearest': 0.8783019854111281},
  {'kernel_size': 4652,
   'coherence_20': 0.9104903714039343,
   'distance_to_nearest': 0.8806710301929691},
  {'kernel_size': 4433, 'coherence_20': 0.7010289149515939},
  {'kernel_size': 5105, 'coherence_20': 0.7160766307085249},
  {'kernel_size': 4803,
   'coherence_20': 0.9857446836345978,
   'distance_to_nearest': 0.8523585978250594},
  {'kernel_size': 4319, 'coherence_20': 0.5140276006067114},
  {'kernel_size': 5410, 'coherence_20': 0.5036891512656438},
  {'kernel_size': 5208, 'coherence_20': 0.7049916212013724},
  {'kernel_size': 5808, 'coherence_20': 0.7772228704947631}],
 [{'kernel_size': 5597, 'coherence_20': 0.5396902854275227},
  {'kernel_size': 5215, 'coherence_20': 0.3722808264465644},
  {'kernel_size': 5757, 'coherence_20': 0.4475570501589715},
  {'kernel_size': 5143, 'coherence_20': 1.1431616921636167},
  {'kernel_size': 5000, 'coherence_20': 0.5419178241552643},
  {'kernel_size': 4486, 'coherence_20': 1.1933504971919415},
  {'kernel_size': 6052, 'coherence_20': 0.6457727408450418},
  {'kernel_size': 4947, 'coherence_20': 1.0073802549165003},
  {'kernel_size': 6175, 'coherence_20': 0.7688040632131219},
  {'kernel_size': 4896, 'coherence_20': 0.444065397260907},
  {'kernel_size': 5090, 'coherence_20': 0.5404802525686955},
  {'kernel_size': 5384,
   'coherence_20': 0.8683741848152282,
   'distance_to_nearest': 0.6518186505277321},
  {'kernel_size': 4190, 'coherence_20': 1.1524286799264933},
  {'kernel_size': 5284, 'coherence_20': 0.6282021983787992},
  {'kernel_size': 5425, 'coherence_20': 0.6243926478406314},
  {'kernel_size': 4965, 'coherence_20': 0.5445462172848061},
  {'kernel_size': 4649, 'coherence_20': 0.5397980509206309},
  {'kernel_size': 4531, 'coherence_20': 1.1763487585449393},
  {'kernel_size': 4509, 'coherence_20': 0.6360890883291339},
  {'kernel_size': 5235, 'coherence_20': 0.5563637920731452}],
 [{'kernel_size': 4939, 'coherence_20': 0.7826998423381184},
  {'kernel_size': 4594, 'coherence_20': 0.8455394418871257},
  {'kernel_size': 5281, 'coherence_20': 0.45586793023330807},
  {'kernel_size': 5369, 'coherence_20': 0.6158473105876622},
  {'kernel_size': 4646, 'coherence_20': 0.47189740819510295},
  {'kernel_size': 5433, 'coherence_20': 0.7195773608043738},
  {'kernel_size': 3747, 'coherence_20': 1.437635545405359},
  {'kernel_size': 5846, 'coherence_20': 0.6428823372410538},
  {'kernel_size': 5097,
   'coherence_20': 0.8732924274477326,
   'distance_to_nearest': 0.7920755781872806},
  {'kernel_size': 5485, 'coherence_20': 0.6598415343894899},
  {'kernel_size': 5381, 'coherence_20': 0.46423619142432526},
  {'kernel_size': 5402, 'coherence_20': 0.8045835662114041},
  {'kernel_size': 4099, 'coherence_20': 0.8527521775876804},
  {'kernel_size': 4785,
   'coherence_20': 1.1927380696146608,
   'distance_to_nearest': 0.8226825750211674},
  {'kernel_size': 5237, 'coherence_20': 0.48385717672428075},
  {'kernel_size': 5359, 'coherence_20': 0.7818419770430218},
  {'kernel_size': 5463, 'coherence_20': 1.141784805420542},
  {'kernel_size': 6076, 'coherence_20': 0.5603562470071296},
  {'kernel_size': 5127, 'coherence_20': 0.8829710238530692},
  {'kernel_size': 4265, 'coherence_20': 0.8406721801287738}],
 [{'kernel_size': 4576, 'coherence_20': 0.8593431164304997},
  {'kernel_size': 5544, 'coherence_20': 0.4030844199938033},
  {'kernel_size': 5451, 'coherence_20': 0.5127491841235817},
  {'kernel_size': 5113, 'coherence_20': 0.8083031553720866},
  {'kernel_size': 4582, 'coherence_20': 0.8774038896371681},
  {'kernel_size': 5484, 'coherence_20': 0.6732238259648101},
  {'kernel_size': 4835, 'coherence_20': 0.7144021442878106},
  {'kernel_size': 4165, 'coherence_20': 1.4545749444732223},
  {'kernel_size': 4834, 'coherence_20': 1.1086257638497508},
  {'kernel_size': 4651, 'coherence_20': 0.6238572817152017},
  {'kernel_size': 3597, 'coherence_20': 1.7288431430919424},
  {'kernel_size': 4453, 'coherence_20': 1.0718680762993942},
  {'kernel_size': 5691, 'coherence_20': 0.7390199596325874},
  {'kernel_size': 4836, 'coherence_20': 0.9236689348983469},
  {'kernel_size': 4353, 'coherence_20': 0.9609723969000091},
  {'kernel_size': 4632, 'coherence_20': 0.5202835233010801},
  {'kernel_size': 5667, 'coherence_20': 0.6250313450068045},
  {'kernel_size': 4375, 'coherence_20': 0.5810338834221149},
  {'kernel_size': 6457, 'coherence_20': 0.6724899554295911},
  {'kernel_size': 6038, 'coherence_20': 0.5250236433943247}],
 [{'kernel_size': 3911, 'coherence_20': 0.7191256657296935},
  {'kernel_size': 5742, 'coherence_20': 0.6317642129385314},
  {'kernel_size': 5131, 'coherence_20': 0.99413568388225},
  {'kernel_size': 4853, 'coherence_20': 0.6432440811374035},
  {'kernel_size': 4607, 'coherence_20': 0.8024659089482266},
  {'kernel_size': 4719, 'coherence_20': 0.7038702636760389},
  {'kernel_size': 5335, 'coherence_20': 0.4502868696889806},
  {'kernel_size': 5331, 'coherence_20': 0.6822216573007923},
  {'kernel_size': 5749, 'coherence_20': 0.6859056636762408},
  {'kernel_size': 5311, 'coherence_20': 0.47268079324113377},
  {'kernel_size': 4027, 'coherence_20': 0.9148676150216797},
  {'kernel_size': 5383, 'coherence_20': 0.553577949950346},
  {'kernel_size': 5988, 'coherence_20': 0.7791207369283849},
  {'kernel_size': 4487, 'coherence_20': 0.8315225827478838},
  {'kernel_size': 5178, 'coherence_20': 1.0757495435346498},
  {'kernel_size': 6251, 'coherence_20': 0.562023639593199},
  {'kernel_size': 5486, 'coherence_20': 0.48669444068163187},
  {'kernel_size': 4217, 'coherence_20': 1.4794722242732823},
  {'kernel_size': 5641, 'coherence_20': 0.5125258588764388},
  {'kernel_size': 3910, 'coherence_20': 0.8675657362079289}],
 [{'kernel_size': 5118, 'coherence_20': 0.4568995081481809},
  {'kernel_size': 5013, 'coherence_20': 0.5711584057934599},
  {'kernel_size': 5946, 'coherence_20': 0.6895536959716403},
  {'kernel_size': 4790, 'coherence_20': 0.6160272822141549},
  {'kernel_size': 5697,
   'coherence_20': 0.8684892668554253,
   'distance_to_nearest': 0.8484545037818898},
  {'kernel_size': 4052, 'coherence_20': 1.2597877005059532},
  {'kernel_size': 5704, 'coherence_20': 0.6527939522844116},
  {'kernel_size': 4772, 'coherence_20': 0.9752047628806342},
  {'kernel_size': 4700, 'coherence_20': 0.8603669709951757},
  {'kernel_size': 4186, 'coherence_20': 1.3298810340740868},
  {'kernel_size': 5534, 'coherence_20': 0.7553255828012603},
  {'kernel_size': 5775, 'coherence_20': 1.0866827880972962},
  {'kernel_size': 4064, 'coherence_20': 0.935117473367967},
  {'kernel_size': 4719, 'coherence_20': 0.408131216563029},
  {'kernel_size': 4487, 'coherence_20': 0.5812686315536558},
  {'kernel_size': 5664, 'coherence_20': 0.5027892212706795},
  {'kernel_size': 5193, 'coherence_20': 0.4740773964721891},
  {'kernel_size': 4924, 'coherence_20': 0.6210386619265225},
  {'kernel_size': 5132, 'coherence_20': 0.6725688738622692},
  {'kernel_size': 6040, 'coherence_20': 0.8217836829876803}],
 [{'kernel_size': 4675, 'coherence_20': 0.9650459081433241},
  {'kernel_size': 4784, 'coherence_20': 0.5794201886308246},
  {'kernel_size': 5047, 'coherence_20': 1.2091199101205974},
  {'kernel_size': 4689,
   'coherence_20': 0.8984681521006888,
   'distance_to_nearest': 0.8435919720118529},
  {'kernel_size': 4418, 'coherence_20': 0.7907506008822671},
  {'kernel_size': 4782, 'coherence_20': 0.8513056620828662},
  {'kernel_size': 5412, 'coherence_20': 0.49512668568556567},
  {'kernel_size': 4863, 'coherence_20': 0.7911070568509502},
  {'kernel_size': 6485, 'coherence_20': 0.5840537895709419},
  {'kernel_size': 4939, 'coherence_20': 0.5121023239458181},
  {'kernel_size': 4862, 'coherence_20': 0.656587305154116},
  {'kernel_size': 5629, 'coherence_20': 0.41211549573831935},
  {'kernel_size': 4864, 'coherence_20': 0.6734112276584496},
  {'kernel_size': 5785, 'coherence_20': 0.510180233311145},
  {'kernel_size': 5213, 'coherence_20': 0.731647897753709},
  {'kernel_size': 4895, 'coherence_20': 0.5354039180354397},
  {'kernel_size': 5146, 'coherence_20': 0.7075907256660539},
  {'kernel_size': 5814, 'coherence_20': 0.8860206032913247},
  {'kernel_size': 4636, 'coherence_20': 1.2478595709791316},
  {'kernel_size': 5136, 'coherence_20': 0.5469821069459536}],
 [{'kernel_size': 4631, 'coherence_20': 0.8827794632415356},
  {'kernel_size': 4648, 'coherence_20': 0.8234607244084104},
  {'kernel_size': 5619, 'coherence_20': 0.6069420112573812},
  {'kernel_size': 4799, 'coherence_20': 0.6411560827425579},
  {'kernel_size': 5098, 'coherence_20': 0.8126827799963168},
  {'kernel_size': 5145, 'coherence_20': 0.6062205165716585},
  {'kernel_size': 5310, 'coherence_20': 0.5632514237453714},
  {'kernel_size': 4404, 'coherence_20': 1.329881034074087},
  {'kernel_size': 4914, 'coherence_20': 0.8886644900259871},
  {'kernel_size': 4576, 'coherence_20': 0.42924118209164847},
  {'kernel_size': 5304, 'coherence_20': 0.7021080050554561},
  {'kernel_size': 4330, 'coherence_20': 0.8982173605171376},
  {'kernel_size': 5693, 'coherence_20': 0.6010252154694804},
  {'kernel_size': 6230, 'coherence_20': 0.7570646364429013},
  {'kernel_size': 5858, 'coherence_20': 0.5994703719109289},
  {'kernel_size': 5002, 'coherence_20': 0.6866492099122941},
  {'kernel_size': 3580, 'coherence_20': 1.35238361662245},
  {'kernel_size': 4785, 'coherence_20': 0.9365902284333054},
  {'kernel_size': 6231, 'coherence_20': 0.6539676094325603},
  {'kernel_size': 5075, 'coherence_20': 1.1009203341305995}],
 [{'kernel_size': 4745, 'coherence_20': 0.9000164684439399},
  {'kernel_size': 4726, 'coherence_20': 0.9015874960953398},
  {'kernel_size': 4572, 'coherence_20': 0.7253183758099111},
  {'kernel_size': 3729, 'coherence_20': 1.596032478593424},
  {'kernel_size': 4552, 'coherence_20': 0.4060801687419614},
  {'kernel_size': 4782, 'coherence_20': 0.6293623290267147},
  {'kernel_size': 6141, 'coherence_20': 0.9803659780534206},
  {'kernel_size': 4997, 'coherence_20': 0.7044972860566215},
  {'kernel_size': 5438, 'coherence_20': 0.4525939886315921},
  {'kernel_size': 5397, 'coherence_20': 0.6975626429528025},
  {'kernel_size': 5103, 'coherence_20': 0.47742022969185494},
  {'kernel_size': 4814, 'coherence_20': 0.7320714193453678},
  {'kernel_size': 4908, 'coherence_20': 0.54015656895741},
  {'kernel_size': 4107, 'coherence_20': 0.9616476095934583},
  {'kernel_size': 4889, 'coherence_20': 1.1019931803527474},
  {'kernel_size': 3908, 'coherence_20': 0.8917432053896212},
  {'kernel_size': 5321, 'coherence_20': 0.8152211179867683},
  {'kernel_size': 5861, 'coherence_20': 0.5753178760175929},
  {'kernel_size': 5028, 'coherence_20': 0.48418893522848033},
  {'kernel_size': 6208, 'coherence_20': 0.6462219175369381}],
 [{'kernel_size': 5182, 'coherence_20': 0.469905897795024},
  {'kernel_size': 4754, 'coherence_20': 0.8061287395948099},
  {'kernel_size': 5856, 'coherence_20': 0.606008957022093},
  {'kernel_size': 5373, 'coherence_20': 0.7472614807599438},
  {'kernel_size': 5646, 'coherence_20': 0.45202559307874507},
  {'kernel_size': 4724, 'coherence_20': 0.7423243053488542},
  {'kernel_size': 5542, 'coherence_20': 0.581953426957697},
  {'kernel_size': 4955, 'coherence_20': 0.7120113421953679},
  {'kernel_size': 4397, 'coherence_20': 1.3298810340740868},
  {'kernel_size': 4564, 'coherence_20': 0.8626987810861331},
  {'kernel_size': 5057,
   'coherence_20': 1.015922510120161,
   'distance_to_nearest': 0.8612299059752945},
  {'kernel_size': 6204, 'coherence_20': 0.6591942898120813},
  {'kernel_size': 4728, 'coherence_20': 0.6048041472210302},
  {'kernel_size': 5405, 'coherence_20': 0.8511910401163003},
  {'kernel_size': 4376, 'coherence_20': 0.6070519290715083},
  {'kernel_size': 5238, 'coherence_20': 0.664731049284264},
  {'kernel_size': 5571, 'coherence_20': 0.7855453312805215},
  {'kernel_size': 4793, 'coherence_20': 0.5780108293803998},
  {'kernel_size': 4243, 'coherence_20': 1.1054598611783717},
  {'kernel_size': 4994, 'coherence_20': 0.6502792008660964}],
 [{'kernel_size': 4273, 'coherence_20': 0.9263424578691576},
  {'kernel_size': 4244, 'coherence_20': 1.3298810340740868},
  {'kernel_size': 4269, 'coherence_20': 0.48940752935615},
  {'kernel_size': 6029, 'coherence_20': 0.6595079121749639},
  {'kernel_size': 5191, 'coherence_20': 0.5506718487350086},
  {'kernel_size': 4407,
   'coherence_20': 1.1136936876869548,
   'distance_to_nearest': 0.6077845200819454},
  {'kernel_size': 5952, 'coherence_20': 0.6958732462140121},
  {'kernel_size': 4217, 'coherence_20': 1.0063066325423766},
  {'kernel_size': 4965, 'coherence_20': 1.138250523433373},
  {'kernel_size': 5498, 'coherence_20': 0.42740598175546685},
  {'kernel_size': 4444, 'coherence_20': 0.8638016370383118},
  {'kernel_size': 5889, 'coherence_20': 0.9804240265061905},
  {'kernel_size': 5662, 'coherence_20': 0.7921787519905689},
  {'kernel_size': 5606, 'coherence_20': 0.4606471502273102},
  {'kernel_size': 4969, 'coherence_20': 0.7080594856134208},
  {'kernel_size': 4360, 'coherence_20': 0.528529073718312},
  {'kernel_size': 4865, 'coherence_20': 0.7111180745272372},
  {'kernel_size': 5145, 'coherence_20': 0.7602466987900695},
  {'kernel_size': 5174, 'coherence_20': 0.5835788086602967},
  {'kernel_size': 5636, 'coherence_20': 0.923244705372171}],
 [{'kernel_size': 4224, 'coherence_20': 0.8216420070659225},
  {'kernel_size': 4626, 'coherence_20': 0.5941432410115014},
  {'kernel_size': 4201, 'coherence_20': 0.790769801347285},
  {'kernel_size': 4190, 'coherence_20': 1.208996926300371},
  {'kernel_size': 4693, 'coherence_20': 0.5897603452742466},
  {'kernel_size': 3587, 'coherence_20': 1.7915463424973972},
  {'kernel_size': 5055, 'coherence_20': 0.6986481014000091},
  {'kernel_size': 4523, 'coherence_20': 0.8312766186262622},
  {'kernel_size': 4855, 'coherence_20': 0.637249675137521},
  {'kernel_size': 4165, 'coherence_20': 1.3298810340740868},
  {'kernel_size': 4271, 'coherence_20': 0.8634084108395933},
  {'kernel_size': 5764, 'coherence_20': 0.6853666678100566},
  {'kernel_size': 6660, 'coherence_20': 0.6671448781969185},
  {'kernel_size': 5302, 'coherence_20': 1.158582176247928},
  {'kernel_size': 5034, 'coherence_20': 0.523463053324874},
  {'kernel_size': 6005, 'coherence_20': 0.664255232253418},
  {'kernel_size': 5503, 'coherence_20': 0.6353928266537566},
  {'kernel_size': 5395, 'coherence_20': 0.46782707655870986},
  {'kernel_size': 4038, 'coherence_20': 0.7965571600233645},
  {'kernel_size': 5620, 'coherence_20': 0.6030235244861738}],
 [{'kernel_size': 5102, 'coherence_20': 0.5103443198871027},
  {'kernel_size': 5398, 'coherence_20': 0.8382035687468394},
  {'kernel_size': 4380, 'coherence_20': 0.5837986073754083},
  {'kernel_size': 4988, 'coherence_20': 0.5190947273845876},
  {'kernel_size': 4092, 'coherence_20': 0.9119189118663689},
  {'kernel_size': 6510, 'coherence_20': 0.5345975280739981},
  {'kernel_size': 4410, 'coherence_20': 0.9972728217076641},
  {'kernel_size': 5026, 'coherence_20': 0.940590128707932},
  {'kernel_size': 4982, 'coherence_20': 0.6732238259648101},
  {'kernel_size': 5605, 'coherence_20': 0.6550196429335589},
  {'kernel_size': 5167, 'coherence_20': 0.7024024361435829},
  {'kernel_size': 4329, 'coherence_20': 0.5937002102579196},
  {'kernel_size': 5260, 'coherence_20': 0.6167581419744079},
  {'kernel_size': 4427, 'coherence_20': 1.1650984504211566},
  {'kernel_size': 4319, 'coherence_20': 0.7039008255756519},
  {'kernel_size': 5641, 'coherence_20': 0.903140848829499},
  {'kernel_size': 5593, 'coherence_20': 0.6501212376436246},
  {'kernel_size': 4998, 'coherence_20': 0.7533407745256695},
  {'kernel_size': 4670, 'coherence_20': 0.8851883001704314},
  {'kernel_size': 4649, 'coherence_20': 0.5210311791571117}],
 [{'kernel_size': 5100, 'coherence_20': 0.9425140137250276},
  {'kernel_size': 5093, 'coherence_20': 0.851691413276802},
  {'kernel_size': 4353, 'coherence_20': 1.2742046877191562},
  {'kernel_size': 4947, 'coherence_20': 0.757878515491989},
  {'kernel_size': 5167, 'coherence_20': 0.583224650961388},
  {'kernel_size': 5163, 'coherence_20': 0.6001219063613151},
  {'kernel_size': 5368, 'coherence_20': 0.6237864339762759},
  {'kernel_size': 5038, 'coherence_20': 0.7193644003480515},
  {'kernel_size': 5271, 'coherence_20': 1.1431616921636167},
  {'kernel_size': 4659, 'coherence_20': 0.956789286938844},
  {'kernel_size': 5191, 'coherence_20': 0.6544201137277793},
  {'kernel_size': 6453, 'coherence_20': 0.6025839572895583},
  {'kernel_size': 5302, 'coherence_20': 0.47084076406722225},
  {'kernel_size': 4710, 'coherence_20': 0.9142013620689555},
  {'kernel_size': 5179, 'coherence_20': 0.41062500248828004},
  {'kernel_size': 5187, 'coherence_20': 0.4865615262436947},
  {'kernel_size': 4662, 'coherence_20': 0.8727464044436518},
  {'kernel_size': 6122, 'coherence_20': 0.9248854295353953},
  {'kernel_size': 4636, 'coherence_20': 0.6884926358585081},
  {'kernel_size': 3867, 'coherence_20': 1.329881034074087}],
 [{'kernel_size': 4789, 'coherence_20': 0.5092200020083723},
  {'kernel_size': 5464, 'coherence_20': 0.6003824535607182},
  {'kernel_size': 5438, 'coherence_20': 0.645461223870627},
  {'kernel_size': 4867, 'coherence_20': 0.6586782583469641},
  {'kernel_size': 4892, 'coherence_20': 0.6227694031487658},
  {'kernel_size': 5828, 'coherence_20': 0.5281610911466676},
  {'kernel_size': 4480, 'coherence_20': 0.8986364582995819},
  {'kernel_size': 5260, 'coherence_20': 0.6744072278687676},
  {'kernel_size': 6024, 'coherence_20': 0.5372268626065656},
  {'kernel_size': 4473, 'coherence_20': 0.6744232066396302},
  {'kernel_size': 5614, 'coherence_20': 1.025151211275251},
  {'kernel_size': 4429, 'coherence_20': 0.8990938577492135},
  {'kernel_size': 5142, 'coherence_20': 0.46342286203320004},
  {'kernel_size': 4789, 'coherence_20': 0.8849763923062258},
  {'kernel_size': 5390, 'coherence_20': 0.5421637874916074},
  {'kernel_size': 3724, 'coherence_20': 1.4794217040130335},
  {'kernel_size': 4722, 'coherence_20': 0.4852765362624597},
  {'kernel_size': 4985, 'coherence_20': 0.941712825212483},
  {'kernel_size': 6412, 'coherence_20': 0.7602162410760849},
  {'kernel_size': 5122, 'coherence_20': 0.4880883860829445}],
 [{'kernel_size': 4998, 'coherence_20': 0.6456621324457774},
  {'kernel_size': 5374, 'coherence_20': 1.1860213339651169},
  {'kernel_size': 5676, 'coherence_20': 0.5162280099336254},
  {'kernel_size': 5603, 'coherence_20': 0.7313686130938397},
  {'kernel_size': 4718, 'coherence_20': 0.8843916447253765},
  {'kernel_size': 4725, 'coherence_20': 0.8376219570670854},
  {'kernel_size': 4158, 'coherence_20': 1.3298810340740868},
  {'kernel_size': 5105, 'coherence_20': 0.823987698878097},
  {'kernel_size': 5840, 'coherence_20': 0.6772761374270698},
  {'kernel_size': 5119, 'coherence_20': 0.6701733821046219},
  {'kernel_size': 5167, 'coherence_20': 0.4221458028667911},
  {'kernel_size': 4723, 'coherence_20': 1.0312487861796864},
  {'kernel_size': 5100, 'coherence_20': 0.4508283836103323},
  {'kernel_size': 5334, 'coherence_20': 0.4798352288441816},
  {'kernel_size': 4717, 'coherence_20': 0.9700287514902586},
  {'kernel_size': 4673, 'coherence_20': 0.7881316367892152},
  {'kernel_size': 4503, 'coherence_20': 0.8833699742685971},
  {'kernel_size': 4981, 'coherence_20': 0.9123950810884037},

In [123]:
! echo $SEARCH_RESULTS_FOLDER_PATH
! ls $SEARCH_RESULTS_FOLDER_PATH

./Good_RU_Wiki__internals/result2
bank__0  search_result__0.json

In [124]:
! ls Good_RU_Wiki__internals

batches  dict.dict  result  result2  vw.txt