In [2]:
! ls /data_mil/shared/CompressaAI/deploy/models/models

IlyaGusev_saiga_mistral_7b_merged   TheBloke_Llama-2-7B-fp16
microsoft_phi-2			    TheBloke_Llama-2-7B-GPTQ
mistralai_Mistral-7B-Instruct-v0.2  TheBloke_Mistral-7B-Instruct-v0.2-GPTQ
openchat_openchat-3.5-1210	    TheBloke_phi-2-GPTQ
Saiga2-7B-Lora-Merged-OmniQuant     TheBloke_TinyLlama-1.1B-Chat-v1.0-GPTQ
TheBloke_Llama-2-13B-fp16	    throughput.log
TheBloke_Llama-2-13B-GPTQ	    TinyLlama_TinyLlama-1.1B-Chat-v1.0

# **Tutorial** - Topic Modeling with BERTopic
(last updated 01-09-2022)

In this tutorial we will be exploring how to use BERTopic to create topics from the well-known 20Newsgroups dataset. The most frequent use-cases and methods are discussed together with important parameters to keep a look out for.


## BERTopic
BERTopic is a topic modeling technique that leverages 🤗 transformers and a custom class-based TF-IDF to create dense clusters allowing for easily interpretable topics whilst keeping important words in the topic descriptions.

<br>

<img src="https://raw.githubusercontent.com/MaartenGr/BERTopic/master/images/logo.png" width="40%">

# Enabling the GPU

First, you'll need to enable GPUs for the notebook:

- Navigate to Edit→Notebook Settings
- select GPU from the Hardware Accelerator drop-down

[Reference](https://colab.research.google.com/notebooks/gpu.ipynb)

# **Installing BERTopic**

We start by installing BERTopic from PyPi:

## Restart the Notebook
After installing BERTopic, some packages that were already loaded were updated and in order to correctly use them, we should now restart the notebook.

From the Menu:

Runtime → Restart Runtime

# Data
For this example, we use the popular 20 Newsgroups dataset which contains roughly 18000 newsgroups posts

In [3]:
from topicnet.cooking_machine import Dataset

In [4]:
DATA_FOLDER_PATH = '/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/dataset_manager'

In [5]:
! ls $DATA_FOLDER_PATH

20NG.csv	 MKB10__internals      RTL_Wiki_person.csv
20NG__internals  postnauka.csv	       RTL_Wiki_person__internals
api.py		 postnauka__internals  ruwiki_good__internals
Brown		 __pycache__	       ruwiki_good.txt
Brown_BOW.csv	 Reuters	       WikiRef-220
Brown_NOOW.csv	 Reuters_BOW.csv       wiki_ref220_bow.csv
__init__.py	 Reuters_NOOW.csv      wiki_ref220_natural_order.csv
MKB10.csv	 RTL_Wiki.csv

In [16]:
dataset = Dataset(
    f'{DATA_FOLDER_PATH}/20NG.csv',
)

dataset.get_possible_modalities()

{'@bigram', '@lemmatized'}

In [17]:
from sklearn.datasets import fetch_20newsgroups

orig_docs = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))['data']

In [18]:
docs[:3]

['@title Автограф # «Математический дивертисмент» | @snippet Авторы кейс-стади по математике рассказывают об образовании, красоте и, конечно, о своей книге\n',
 '@title Главы: Маскулинности в российском контексте | @snippet Отрывок из книги «12 лекций по гендерной социологии» социологов Елены Здравомысловой и Анны Темкиной о трансформации различных моделей маскулинности в российском контексте\n',
 '@title Пиджины и креольские языки | @snippet Лингвист Владимир Беликов о языке-лексификаторе, креолизации и языках Новой Гвинеи\n']

In [19]:
dataset._data.head()

,Unnamed: 0,raw_text,filenames,target,id,tokenized,lemmatized,bigram,vw_text
id,,,,,,,,,
rec_autos_102994,0,I was wondering if anyone out there could enli...,/home/egorov/scikit_learn_data/20news_home/20n...,7,rec_autos_102994,"[('was', 'VBD'), ('wondering', 'VBG'), ('if', ...","['wonder', 'anyone', 'could', 'enlighten', 'ca...","['wonder_anyone', 'anyone_could', 'sport_car',...",rec_autos_102994 |@lemmatized wonder:1 anyone:...
comp_sys_mac_hardware_51861,1,A fair number of brave souls who upgraded thei...,/home/egorov/scikit_learn_data/20news_home/20n...,4,comp_sys_mac_hardware_51861,"[('fair', 'JJ'), ('number', 'NN'), ('of', 'IN'...","['fair', 'number', 'brave', 'soul', 'upgrade',...","['clock_oscillator', 'please_send', 'top_speed...",comp_sys_mac_hardware_51861 |@lemmatized fair:...
comp_sys_mac_hardware_51879,2,"well folks, my mac plus finally gave up the gh...",/home/egorov/scikit_learn_data/20news_home/20n...,4,comp_sys_mac_hardware_51879,"[('well', 'RB'), ('folks', 'NNS'), ('my', 'PRP...","['well', 'folk', 'mac', 'plus', 'finally', 'gi...","['mac_plus', 'life_way', 'way_back', 'market_n...",comp_sys_mac_hardware_51879 |@lemmatized well:...
comp_graphics_38242,3,\nDo you have Weitek's address/phone number? ...,/home/egorov/scikit_learn_data/20news_home/20n...,1,comp_graphics_38242,"[('do', 'VBP'), ('you', 'PRP'), ('have', 'VB')...","['weitek', 'address', 'phone', 'number', 'like...","['address_phone', 'phone_number', 'number_like...",comp_graphics_38242 |@lemmatized weitek:1 addr...
sci_space_60880,4,"From article <C5owCB.n3p@world.std.com>, by to...",/home/egorov/scikit_learn_data/20news_home/20n...,14,sci_space_60880,"[('from', 'IN'), ('article', 'NN'), ('by', 'IN...","['article', 'tom', 'baker', 'understanding', '...","['system_software', 'thing_check', 'introduce_...",sci_space_60880 |@lemmatized article:1 tom:1 b...

In [20]:
dataset._data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11301 entries, rec_autos_102994 to rec_motorcycles_104440
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  11301 non-null  int64
 1   raw_text    11083 non-null  object
 2   filenames   11301 non-null  object
 3   target      11301 non-null  int64
 4   id          11301 non-null  object
 5   tokenized   11301 non-null  object
 6   lemmatized  11301 non-null  object
 7   bigram      11301 non-null  object
 8   vw_text     11301 non-null  object
dtypes: int64(2), object(7)
memory usage: 882.9+ KB

In [21]:
dataset._data.shape

(11301, 9)

In [22]:
dataset._data.dropna(axis=0, inplace=True)

In [23]:
dataset._data.shape

(11083, 9)

In [24]:
dataset._data['raw_text']

id
rec_autos_102994                  I was wondering if anyone out there could enli...
comp_sys_mac_hardware_51861       A fair number of brave souls who upgraded thei...
comp_sys_mac_hardware_51879       well folks, my mac plus finally gave up the gh...
comp_graphics_38242               \nDo you have Weitek's address/phone number?  ...
sci_space_60880                   From article <C5owCB.n3p@world.std.com>, by to...
                                                        ...
sci_med_58069                     DN> From: nyeda@cnsvax.uwec.edu (David Nye)\nD...
comp_sys_mac_hardware_51712       I have a (very old) Mac 512k and a Mac Plus, b...
comp_sys_ibm_pc_hardware_60695    I just installed a DX2-66 CPU in a clone mothe...
comp_graphics_38319               \nWouldn't this require a hyper-sphere.  In 3-...
rec_motorcycles_104440            Stolen from Pasadena between 4:30 and 6:30 pm ...
Name: raw_text, Length: 11083, dtype: object

In [25]:
docs = list(dataset._data['raw_text'].values)

In [26]:
docs[:3]

['I was wondering if anyone out there could enlighten me on this car I saw\nthe other day. It was a 2-door sports car, looked to be from the late 60s/\nearly 70s. It was called a Bricklin. The doors were really small. In addition,\nthe front bumper was separate from the rest of the body. This is \nall I know. If anyone can tellme a model name, engine specs, years\nof production, where this car is made, history, or whatever info you\nhave on this funky looking car, please e-mail.',
 "A fair number of brave souls who upgraded their SI clock oscillator have\nshared their experiences for this poll. Please send a brief message detailing\nyour experiences with the procedure. Top speed attained, CPU rated speed,\nadd on cards and adapters, heat sinks, hour of usage per day, floppy disk\nfunctionality with 800 and 1.4 m floppies are especially requested.\n\nI will be summarizing in the next two days, so please add to the network\nknowledge base if you have done the clock upgrade and haven't answered this\npoll. Thanks.",
 'well folks, my mac plus finally gave up the ghost this weekend after\nstarting life as a 512k way back in 1985.  sooo, i\'m in the market for a\nnew machine a bit sooner than i intended to be...\n\ni\'m looking into picking up a powerbook 160 or maybe 180 and have a bunch\nof questions that (hopefully) somebody can answer:\n\n* does anybody know any dirt on when the next round of powerbook\nintroductions are expected?  i\'d heard the 185c was supposed to make an\nappearence "this summer" but haven\'t heard anymore on it - and since i\ndon\'t have access to macleak, i was wondering if anybody out there had\nmore info...\n\n* has anybody heard rumors about price drops to the powerbook line like the\nones the duo\'s just went through recently?\n\n* what\'s the impression of the display on the 180?  i could probably swing\na 180 if i got the 80Mb disk rather than the 120, but i don\'t really have\na feel for how much "better" the display is (yea, it looks great in the\nstore, but is that all "wow" or is it really that good?).  could i solicit\nsome opinions of people who use the 160 and 180 day-to-day on if its worth\ntaking the disk size and money hit to get the active display?  (i realize\nthis is a real subjective question, but i\'ve only played around with the\nmachines in a computer store breifly and figured the opinions of somebody\nwho actually uses the machine daily might prove helpful).\n\n* how well does hellcats perform?  ;)\n\nthanks a bunch in advance for any info - if you could email, i\'ll post a\nsummary (news reading time is at a premium with finals just around the\ncorner... :( )\n--\nTom Willis  \\  twillis@ecn.purdue.edu    \\    Purdue Electrical Engineering']

In [58]:
[d for d in docs if len(d) > 2]

['I was wondering if anyone out there could enlighten me on this car I saw\nthe other day. It was a 2-door sports car, looked to be from the late 60s/\nearly 70s. It was called a Bricklin. The doors were really small. In addition,\nthe front bumper was separate from the rest of the body. This is \nall I know. If anyone can tellme a model name, engine specs, years\nof production, where this car is made, history, or whatever info you\nhave on this funky looking car, please e-mail.',
 "A fair number of brave souls who upgraded their SI clock oscillator have\nshared their experiences for this poll. Please send a brief message detailing\nyour experiences with the procedure. Top speed attained, CPU rated speed,\nadd on cards and adapters, heat sinks, hour of usage per day, floppy disk\nfunctionality with 800 and 1.4 m floppies are especially requested.\n\nI will be summarizing in the next two days, so please add to the network\nknowledge base if you have done the clock upgrade and haven't answered this\npoll. Thanks.",
 'well folks, my mac plus finally gave up the ghost this weekend after\nstarting life as a 512k way back in 1985.  sooo, i\'m in the market for a\nnew machine a bit sooner than i intended to be...\n\ni\'m looking into picking up a powerbook 160 or maybe 180 and have a bunch\nof questions that (hopefully) somebody can answer:\n\n* does anybody know any dirt on when the next round of powerbook\nintroductions are expected?  i\'d heard the 185c was supposed to make an\nappearence "this summer" but haven\'t heard anymore on it - and since i\ndon\'t have access to macleak, i was wondering if anybody out there had\nmore info...\n\n* has anybody heard rumors about price drops to the powerbook line like the\nones the duo\'s just went through recently?\n\n* what\'s the impression of the display on the 180?  i could probably swing\na 180 if i got the 80Mb disk rather than the 120, but i don\'t really have\na feel for how much "better" the display is (yea, it looks great in the\nstore, but is that all "wow" or is it really that good?).  could i solicit\nsome opinions of people who use the 160 and 180 day-to-day on if its worth\ntaking the disk size and money hit to get the active display?  (i realize\nthis is a real subjective question, but i\'ve only played around with the\nmachines in a computer store breifly and figured the opinions of somebody\nwho actually uses the machine daily might prove helpful).\n\n* how well does hellcats perform?  ;)\n\nthanks a bunch in advance for any info - if you could email, i\'ll post a\nsummary (news reading time is at a premium with finals just around the\ncorner... :( )\n--\nTom Willis  \\  twillis@ecn.purdue.edu    \\    Purdue Electrical Engineering',
 "\nDo you have Weitek's address/phone number?  I'd like to get some information\nabout this chip.\n",
 "From article <C5owCB.n3p@world.std.com>, by tombaker@world.std.com (Tom A Baker):\n\n\nMy understanding is that the 'expected errors' are basically\nknown bugs in the warning system software - things are checked\nthat don't have the right values in yet because they aren't\nset till after launch, and suchlike. Rather than fix the code\nand possibly introduce new bugs, they just tell the crew\n'ok, if you see a warning no. 213 before liftoff, ignore it'.",
 '\n\n\n\n\nOf course.  The term must be rigidly defined in any bill.\n\n\nI doubt she uses this term for that.  You are using a quote allegedly\nfrom her, can you back it up?\n\n\n\n\nI read the article as presenting first an argument about weapons of mass\ndestruction (as commonly understood) and then switching to other topics.\nThe first point evidently was to show that not all weapons should be\nallowed, and then the later analysis was, given this understanding, to\nconsider another class.\n\n\n\n',
 'There were a few people who responded to my request for info on\ntreatment for astrocytomas through email, whom I couldn\'t thank\ndirectly because of mail-bouncing probs (Sean, Debra, and Sharon).  So\nI thought I\'d publicly thank everyone.\n\nThanks! \n\n(I\'m sure glad I accidentally hit "rn" instead of "rm" when I was\ntrying to delete a file last September. "Hmmm... \'News?\' What\'s\nthis?"....)',
 '                                                                      \nALL this shows is that YOU don\'t know much about SCSI.\n\nSCSI-1 {with a SCSI-1 controler chip} range is indeed 0-5MB/s\nand that is ALL you have right about SCSI\nSCSI-1 {With a SCSI-2 controller chip}: 4-6MB/s with 10MB/s burst {8-bit}\n Note the INCREASE in SPEED, the Mac Quadra uses this version of SCSI-1\n so it DOES exist. Some PC use this set up too.\nSCSI-2 {8-bit/SCSI-1 mode}:          4-6MB/s with 10MB/s burst\nSCSI-2 {16-bit/wide or fast mode}:  8-12MB/s with 20MB/s burst\nSCSI-2 {32-bit/wide AND fast}:     15-20MB/s with 40MB/s burst\n \nBy your OWN data the "Although SCSI is twice as fast as ESDI" is correct\nWith a SCSI-2 controller chip SCSI-1 can reach 10MB/s which is indeed\n"20% faster than IDE" {120% of 8.3 is 9.96}. ALL these SCSI facts have been\nposted to this newsgroup in my Mac & IBM info sheet {available by FTP on \nsumex-aim.stanford.edu (36.44.0.6) in the info-mac/report as \nmac-ibm-compare[version #].txt (It should be 173 but 161 may still be there)}\n\nPart of this problem is both Mac and IBM PC are inconsiant about what SCSI\nis which.  Though it is WELL documented that the Quadra has a SCSI-2 chip\nan Apple salesperson said "it uses a fast SCSI-1 chip" {Not at a 6MB/s,\n10MB/s burst it does not. SCSI-1 is 5MB/s maximum synchronous and Quadra\nuses ANsynchronous SCSI which is SLOWER}  It seems that Mac and IBM see\nSCSI-1 interface and think \'SCSI-1\' when it maybe a SCSI-1 interface driven\nin the machine by a SCSi-2 controller chip in 8-bit mode {Which is MUCH\nFASTER then true SCSI-1 can go}.',
 'I have win 3.0 and downloaded several icons and BMP\'s but I can\'t figure out\nhow to change the "wallpaper" or use the icons.  Any help would be appreciated.\n\n\nThanx,\n\n-Brando',
 "\n\n\nI've had the board for over a year, and it does work with Diskdoubler,\nbut not with Autodoubler, due to a licensing problem with Stac Technologies,\nthe owners of the board's compression technology. (I'm writing this\nfrom memory; I've lost the reference. Please correct me if I'm wrong.)\n\nUsing the board, I've had problems with file icons being lost, but it's\nhard to say whether it's the board's fault or something else; however,\nif I decompress the troubled file and recompress it without the board,\nthe icon usually reappears. Because of the above mentioned licensing\nproblem, the freeware expansion utility DD Expand will not decompress\na board-compressed file unless you have the board installed.\n\nSince Stac has its own product now, it seems unlikely that the holes\nin Autodoubler/Diskdoubler related to the board will be fixed.\nWhich is sad, and makes me very reluctant to buy Stac's product since\nthey're being so stinky. (But hey, that's competition.)\n-- ",
 'I have a line on a Ducati 900GTS 1978 model with 17k on the clock.  Runs\nvery well, paint is the bronze/brown/orange faded out, leaks a bit of oil\nand pops out of 1st with hard accel.  The shop will fix trans and oil \nleak.  They sold the bike to the 1 and only owner.  They want $3495, and\nI am thinking more like $3K.  Any opinions out there?  Please email me.\nThanks.  It would be a nice stable mate to the Beemer.  Then I\'ll get\na jap bike and call myself Axis Motors!\n\n-- \n-----------------------------------------------------------------------\n"Tuba" (Irwin)      "I honk therefore I am"     CompuTrac-Richardson,Tx\nirwin@cmptrc.lonestar.org    DoD #0826          (R75/6)',
 '\nYep, that\'s pretty much it. I\'m not a Jew but I understand that this is the\nJewish way of thinking. However, the Jews believe that the Covenant between\nYHWH and the Patriarchs (Abraham and Moses, in this case) establishes a Moral\nCode to follow for mankind. Even the Jews could not decide where the boundaries\nfall, though.\n\nAs I understand it, the Sadducees believed that the Torah was all that was\nrequired, whereas the Pharisees (the ancestors of modern Judaism) believed that\nthe Torah was available for interpretation to lead to an understanding of\nthe required Morality in all its nuances (->Talmud).\n\nThe essence of all of this is that Biblical Morality is an interface between\nMan and YHWH (for a Jew or Christian) and does not necessarily indicate\nanything about YHWH outside of that relationship (although one can speculate).\n\n\nThe trouble with all of this is that we don\'t really know what the "created\nin His image" means. I\'ve heard a number of different opinions on this and\nhave still not come to any conclusion. This rather upsets the Apple Cart if\none wants to base a Life Script on this shaky foundation (to mix metaphors\nunashamedly!) As to living by Christ\'s example, we know very little about\nJesus as a person. We only have his recorded utterances in a set of narratives\nby his followers, and some very small references from comtemporary historians.\nRevelation aside, one can only "know" Christ second-hand or worse.\n\nThis is not an attempt to debunk Christianity (although it may seem that way\ninitially), the point I`m trying to make is that we only really have the Bible\nto interpret, and that interpretation is by humanity. I guess this is where\nFaith or Relevation comes in with all its inherent subjectiveness.\n\n\nNo. There may be an absolute moral code. There are undoubtably multiple\nmoral codes. The multiple moral codes may be founded in the absolute moral\ncode. As an example, a parent may tell a child never to swear, and the child\nmay assume that the parent never swears simply because the parent has told\nthe child that it is "wrong". Now, the parent may swear like a trooper in\nthe pub or bar (where there are no children). The "wrongness" here is if\nthe child disobeys the parent. The parent may feel that it is "inappropriate"\nto swear in front of children but may be quite happy to swear in front of\nanimals. The analogy does not quite hold water because the child knows that\nhe is of the same type as the parent (and may be a parent later in life) but\nyou get the gist of it? Incidentally, the young child considers the directive\nas absolute until he gets older (see Piaget) and learns a morality of his own.\n\nDavid.\n\n---\nOn religion:',
 '--\n',
 '\n   {Description of "External Tank" option for SSF redesign deleted}\n\n\nYo Ken, let\'s keep on-top of things! Both the "External Tank" and\n"Wingless Orbiter" options have been deleted from the SSF redesign\noptions list. Today\'s (4/23) edition of the New York Times reports\nthat O\'Connor told the panel that some redesign proposals have\nbeen dropped, such as using the "giant external fuel tanks used\nin launching space shuttles," and building a "station around\nan existing space shuttle with its wings and tail removed."\n\nCurrently, there are three options being considered, as presented\nto the advisory panel meeting yesterday (and as reported in\ntoday\'s Times).\n\nOption "A" - Low Cost Modular Approach\nThis option is being studied by a team from MSFC. {As an aside,\nthere are SSF redesign teams at MSFC, JSC, and LaRC supporting\nthe SRT (Station Redesign Team) in Crystal City. Both LeRC and\nReston folks are also on-site at these locations, helping the respective\nteams with their redesign activities.} Key features of this\noption are:\n  -  Uses "Bus-1", a modular bus developed by Lockheed that\'s\n     qualified for STS and ELV\'s. The bus provides propulsion, GN&C\n     Communications, & Data Management. Lockheed developed this\n     for the Air Force.\n  -  A "Power Station Capability" is obtained in 3 Shuttle Flights.\n     SSF Solar arrays are used to provide 20 kW of power. The vehicle\n     flies in an "arrow mode" to optimize the microgravity environment.\n     Shuttle/Spacelab missions would utilize the vehilce as a power\n     source for 30 day missions.\n  -  Human tended capability (as opposed to the old SSF sexist term\n     of man-tended capability) is achieved by the addition of the\n     US Common module. This is a modified version of the existing\n     SSF Lab module (docking ports are added for the International\n     Partners\' labs, taking the place of the nodes on SSF). The\n     Shuttle can be docked to the station for 60 day missions.\n     The Orbiter would provide crew habitability & EVA capability.\n  -  International Human Tended. Add the NASDA & ESA modules, and\n     add another 20 kW of power\n  -  Permanent Human Presence Capability. Add a 3rd power module,\n     the U.S. habitation module, and an ACRV (Assured Crew Return\n     Vehicle).\n\nOption "B" - Space Station Freedom Derived\nThe Option "B" team is based at LaRC, and is lead by Mike Griffin.\nThis option looks alot like the existing SSF design, which we\nhave all come to know and love :)\n\nThis option assumes a lightweight external tank is available for\nuse on all SSF assembly flights (so does option "A"). Also, the \nnumber of flights is computed for a 51.6 inclination orbit,\nfor both options "A" and "B".\n\nThe build-up occurs in six phases:\n  -  Initial Research Capability reached after 3 flights. Power\n     is transferred from the vehicle to the Orbiter/Spacelab, when\n     it visits.\n  -  Man-Tended Capability (Griffin has not yet adopted non-sexist\n     language) is achieved after 8 flights. The U.S. Lab is\n     deployed, and 1 solar power module provides 20 kW of power.\n  -  Permanent Human Presence Capability occurs after 10 flights, by\n     keeping one Orbiter on-orbit to use as an ACRV (so sometimes\n     there would be two Orbiters on-orbit - the ACRV, and the\n     second one that comes up for Logistics & Re-supply).\n  -  A "Two Fault Tolerance Capability" is achieved after 14 flights,\n     with the addition of a 2nd power module, another thermal\n     control system radiator, and more propulsion modules.\n  -  After 20 flights, the Internationals are on-board. More power,\n     the Habitation module, and an ACRV are added to finish the\n     assembly in 24 flights.\n\nMost of the systems currently on SSF are used as-is in this option, \nwith the exception of the data management system, which has major\nchanges.',
 "Reduced Prices! \nI have a list of things forsale on behalf of my brother, who's moving (moved\nalready)\n\n\t\t\t\t\t\t\t\tOffer:\n1) Black and Decker Duster Plus (Portable Hand Vaccum)\t\n \tpurchased for $32, \t\t\t\t\t  $12\n\n2) SR-1000 Dual Cassette Portable Player, AM/FM\n5-Band graphics Equalizer, high speed dubing, Duo \nTape.Tape deck A, seems to have lost treble sound. \nBut, I bet  it's fixable.\n\tpurchased for $80\t\t\t\t\t  $25\n\n3)Monolux Zoom MicroScope, up to 1200X magnification\nMade in Japan, includes case and accessories\n\tpurchased for $50\t\t\t\t\t  $20\n\n4)Sunbeam 1400 Hair Dryer, the dryer you put your \nhead under/into. You know, the ones you see in the salons.\n(Don't ask me why my bro had it)\n\tpurchased for $60\t\t\t\t          $24\n\n5)Everylast Speed Bag, all leather. Brand new, never \nused\t\t\t\t\t\t\t\t  $10\n\n6)Osterizer Pusle Matic Blender, with 10 speeds \nand a cookbook, 5 years old\t\t\t\t\t  $10\n\tpurchased for $50\n\n8)Binolux Binoculars . 7x35, extra wide angle\n525ft. at 1000yds. with case. very new.\t\t                  $20\n\n9)Proctor and Silex Spray,Steam and Dry Iron.\nvery new.\t\t\t\t\t\t\t  $10\n\n\nAny questions, contact me thru e-mail and I will reply expeditously\nAnd always, S+H are not included, so please consider this.\n\nAnd lastly, I'm a very reasonable.Very Reasonable.",
 '\nDon\'t be so sure.  Look what happened to Japanese citizens in the US during\nWorld War II.  If you\'re prepared to say "Let\'s round these people up and\nstick them in a concentration camp without trial", it\'s only a short step to\ngassing them without trial.  After all, it seems that the Nazis originally\nonly intended to imprison the Jews; the Final Solution was dreamt up partly\nbecause they couldn\'t afford to run the camps because of the devastation\ncaused by Goering\'s Total War.  Those who weren\'t gassed generally died of\nmalnutrition or disease.\n',
 '\nI certainly do use it whenever I have to do TIFF, and it usually works\nvery well.  That\'s not my point.  I\'m >philosophically< opposed to it\nbecause of its complexity.\n\nThis complexity has led to some programs\' poor TIFF writers making\nsome very bizarre files, other programs\' inability to load TIFF\nimages (though they\'ll save them, of course), and a general\ninability to interchange images between different environments\ndespite the fact they all think they understand TIFF.\n\nAs the saying goes, "It\'s not me I\'m worried about- it\'s all the\nabuse of TIFF over the years, and I chalk it all up to the immense (and\nunnecessary) complexity of the format.\n\nIn the words of the TIFF 5.0 spec, Appendix G, page G-1 (capitalized\nemphasis mine):\n\n"The only problem with this sort of success is that TIFF was designed\nto be powerful and flexible, at the expense of simplicity.  It takes a\nfair amount of effort to handle all the options currently defined in\nthis specification (PROBABLY NO APPLICATION DOES A COMPLETE JOB),\nand that is currently the only way you can be >sure< that you will be\nable to import any TIFF image, since there are so many\nimage-generating applications out there now."\n\n\nIf a program (or worse all applications) can\'t read >every< TIFF\nimage, that means there are some it won\'t- some that I might have to\ndeal with.  Why would I want my images to be trapped in that format?  I\ndon\'t and neither should anyone who agrees with my reasoning- not\nthat anyone does, of course! :-)',

In [27]:
for d in docs:
    if isinstance(d, float):
        print(d)

# **Topic Modeling**

In this example, we will go through the main components of BERTopic and the steps necessary to create a strong topic model.

## Training

We start by instantiating BERTopic. We set language to `english` since our documents are in the English language. If you would like to use a multi-lingual model, please use `language="multilingual"` instead.

We will also calculate the topic probabilities. However, this can slow down BERTopic significantly at large amounts of data (>100_000 documents). It is advised to turn this off if you want to speed up the model.

In [36]:
from bertopic import BERTopic

topic_model = BERTopic(language="english", calculate_probabilities=True, verbose=True, top_n_words=20,)

topics, probs = topic_model.fit_transform(docs)
# topics, probs = topic_model.fit_transform(orig_docs)

2024-03-29 12:46:41,929 - BERTopic - Embedding - Transforming documents to embeddings.

Batches:   0%|          | 0/347 [00:00<?, ?it/s]

2024-03-29 12:46:56,258 - BERTopic - Embedding - Completed ✓
2024-03-29 12:46:56,259 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2024-03-29 12:47:01,862 - BERTopic - Dimensionality - Completed ✓
2024-03-29 12:47:01,863 - BERTopic - Cluster - Start clustering the reduced embeddings
2024-03-29 12:47:11,675 - BERTopic - Cluster - Completed ✓
2024-03-29 12:47:11,680 - BERTopic - Representation - Extracting topics from clusters using representation models.
2024-03-29 12:47:13,739 - BERTopic - Representation - Completed ✓

multi_topic_model = BERTopic(language="multilingual", calculate_probabilities=True, verbose=True)
multi_topics, multi_probs = multi_topic_model.fit_transform(docs)

**NOTE**: Use `language="multilingual"` to select a model that support 50+ languages.

## Extracting Topics
After fitting our model, we can start by looking at the results. Typically, we look at the most frequent topics first as they best represent the collection of documents.

In [29]:
freq = topic_model.get_topic_info()
freq.head(5)

,Topic,Count,Name,Representation,Representative_Docs
0,-1,3755,-1_the_to_and_of,"[the, to, and, of, is, for, in, you, it, that]","[\nTo answer your irrelevant question, yes a p..."
1,0,1070,0_team_game_he_season,"[team, game, he, season, games, players, play,...","[\nWales Conference, Adams Division, Semifinal..."
2,1,515,1_patients_msg_of_is,"[patients, msg, of, is, medical, in, it, healt...","[\n\nIf people are going to do this, I really ..."
3,2,360,2_key_clipper_chip_encryption,"[key, clipper, chip, encryption, keys, escrow,...","[Hmm, followup on my own posting... Well, who ..."
4,3,271,3_card_monitor_video_vga,"[card, monitor, video, vga, drivers, diamond, ...",[I'd like to add a second S3 based video card ...

-1 refers to all outliers and should typically be ignored. Next, let's take a look at a frequent topic that were generated:

In [65]:
freq = multi_topic_model.get_topic_info()
freq.head(5)

,Topic,Count,Name,Representation,Representative_Docs
0,-1,3360,-1_the_to_of_is,"[the, to, of, is, and, you, for, in, it, that]","[I posted this a couple of weeks ago, and it d..."
1,0,1054,0_team_he_game_play,"[team, he, game, play, season, the, games, hoc...",[The FLYERS blew a 3-0 lead over the Buffalo S...
2,1,1037,1_car_bike_my_it,"[car, bike, my, it, the, you, on, to, and, for]",[I recently posted an article asking what kind...
3,2,477,2_space_nasa_launch_the,"[space, nasa, launch, the, of, and, orbit, ear...",[Archive-name: space/data\nLast-modified: $Dat...
4,3,371,3_patients_is_it_of,"[patients, is, it, of, pain, doctor, in, disea...","[\n\nIf people are going to do this, I really ..."

In [64]:
topic_model.get_topic(0)  # Select the most frequent topic

[('team', 0.011090837747563202),
 ('game', 0.010082598442136367),
 ('he', 0.00933413944479827),
 ('season', 0.008111574605667046),
 ('games', 0.007966659852699811),
 ('players', 0.007633296514570323),
 ('play', 0.007615551440357539),
 ('hockey', 0.007405560212048965),
 ('year', 0.0068618746601442175),
 ('league', 0.006384852499537817)]

In [66]:
multi_topic_model.get_topic(0)

[('team', 0.012701221592541735),
 ('he', 0.011861797680272164),
 ('game', 0.011816955650784425),
 ('play', 0.00874444699048821),
 ('season', 0.008665341424932227),
 ('the', 0.008655117617141196),
 ('games', 0.008449333628273395),
 ('hockey', 0.00843882164882089),
 ('year', 0.008330963163616978),
 ('players', 0.0082644798844652)]

**NOTE**: BERTopic is stocastich which mmeans that the topics might differ across runs. This is mostly due to the stocastisch nature of UMAP.

In [ ]:
### Attributes

In [65]:
len(topic_model.topics_)

11083

In [68]:
len(topic_model.topic_sizes_)

140

In [69]:
topic_model.topics_[:10]

[9, 15, -1, -1, -1, -1, -1, 28, -1, -1]

In [70]:
len(set(topic_model.topics_))

140

In [71]:
topic_model.c_tf_idf_.shape

(140, 97851)

# **Embedding Models**
The parameter `embedding_model` takes in a string pointing to a sentence-transformers model, a SentenceTransformer, or a Flair DocumentEmbedding model.

## Sentence-Transformers
You can select any model from sentence-transformers here and pass it through BERTopic with embedding_model:

In [ ]:
topic_model = BERTopic(embedding_model="xlm-r-bert-base-nli-stsb-mean-tokens")

Or select a SentenceTransformer model with your own parameters:

In [76]:
from sentence_transformers import SentenceTransformer

sentence_model = SentenceTransformer("all-mpnet-base-v2")  #, device="cpu")
topic_model = BERTopic(embedding_model=sentence_model, verbose=True)

In [77]:
# RU+ENG: distiluse-base-multilingual-cased-v1
# paraphrase-multilingual-MiniLM-L12-v2

# ENG: all-mpnet-base-v2
# RU: DeepPavlov/rubert-base-cased-sentence

In [78]:
topics, probs = topic_model.fit_transform(docs)

2024-03-23 19:30:59,109 - BERTopic - Embedding - Transforming documents to embeddings.

Batches:   0%|          | 0/347 [00:00<?, ?it/s]

2024-03-23 19:33:10,976 - BERTopic - Embedding - Completed ✓
2024-03-23 19:33:10,977 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2024-03-23 19:33:20,808 - BERTopic - Dimensionality - Completed ✓
2024-03-23 19:33:20,810 - BERTopic - Cluster - Start clustering the reduced embeddings
2024-03-23 19:33:21,203 - BERTopic - Cluster - Completed ✓
2024-03-23 19:33:21,209 - BERTopic - Representation - Extracting topics from clusters using representation models.
2024-03-23 19:33:23,939 - BERTopic - Representation - Completed ✓

Click [here](https://www.sbert.net/docs/pretrained_models.html) for a list of supported sentence transformers models.

In [79]:
import numpy as np

In [89]:
topics

[10,
 15,
 -1,
 -1,
 -1,
 4,
 -1,
 26,
 -1,
 7,
 22,
 -1,
 102,
 2,
 -1,
 -1,
 -1,
 -1,
 11,
 12,
 -1,
 0,
 9,
 41,
 -1,
 -1,
 57,
 0,
 -1,
 -1,
 -1,
 1,
 82,
 6,
 -1,
 0,
 -1,
 3,
 133,
 4,
 0,
 28,
 -1,
 0,
 0,
 -1,
 37,
 -1,
 34,
 -1,
 -1,
 119,
 18,
 1,
 36,
 3,
 71,
 -1,
 7,
 2,
 -1,
 -1,
 -1,
 53,
 -1,
 56,
 -1,
 8,
 96,
 -1,
 36,
 4,
 34,
 100,
 25,
 9,
 3,
 -1,
 7,
 7,
 35,
 8,
 -1,
 27,
 -1,
 26,
 -1,
 19,
 0,
 -1,
 -1,
 36,
 25,
 7,
 -1,
 87,
 -1,
 13,
 -1,
 21,
 7,
 -1,
 -1,
 -1,
 -1,
 64,
 -1,
 11,
 5,
 103,
 72,
 39,
 20,
 47,
 -1,
 35,
 1,
 3,
 13,
 -1,
 -1,
 68,
 25,
 14,
 -1,
 2,
 -1,
 4,
 0,
 58,
 11,
 1,
 83,
 46,
 2,
 47,
 0,
 5,
 -1,
 81,
 1,
 0,
 -1,
 -1,
 1,
 -1,
 4,
 -1,
 66,
 -1,
 2,
 6,
 2,
 104,
 -1,
 32,
 105,
 -1,
 6,
 4,
 18,
 69,
 -1,
 -1,
 44,
 -1,
 11,
 24,
 -1,
 -1,
 0,
 12,
 9,
 1,
 9,
 0,
 1,
 -1,
 1,
 68,
 -1,
 20,
 -1,
 -1,
 44,
 28,
 -1,
 -1,
 3,
 1,
 51,
 -1,
 -1,
 24,
 4,
 9,
 4,
 -1,
 6,
 -1,
 3,
 -1,
 -1,
 0,
 -1,
 84,
 -1,
 4,
 126,
 5,
 1,
 -1,
 9,
 1,
 6,
 -1,
 -1,
 47,
 -1,
 0,
 4,
 40,
 40,
 4,
 22,
 1,
 41,
 2,
 0,
 7,
 18,
 79,
 -1,
 -1,
 18,
 -1,
 96,
 5,
 15,
 3,
 3,
 1,
 -1,
 9,
 -1,
 1,
 17,
 50,
 8,
 7,
 0,
 3,
 0,
 -1,
 81,
 -1,
 91,
 0,
 2,
 0,
 0,
 6,
 -1,
 -1,
 5,
 -1,
 1,
 -1,
 97,
 80,
 -1,
 -1,
 126,
 83,
 7,
 2,
 0,
 -1,
 -1,
 -1,
 95,
 -1,
 -1,
 -1,
 0,
 -1,
 9,
 8,
 6,
 -1,
 0,
 6,
 0,
 -1,
 -1,
 103,
 15,
 -1,
 -1,
 12,
 -1,
 33,
 29,
 6,
 78,
 9,
 96,
 -1,
 16,
 0,
 -1,
 12,
 1,
 2,
 0,
 12,
 3,
 103,
 66,
 -1,
 1,
 1,
 24,
 -1,
 16,
 0,
 2,
 21,
 -1,
 0,
 -1,
 -1,
 -1,
 2,
 -1,
 0,
 48,
 -1,
 5,
 -1,
 0,
 108,
 -1,
 -1,
 -1,
 0,
 -1,
 92,
 25,
 69,
 -1,
 38,
 2,
 2,
 -1,
 1,
 -1,
 -1,
 -1,
 38,
 1,
 0,
 124,
 19,
 25,
 5,
 -1,
 -1,
 36,
 -1,
 54,
 81,
 4,
 -1,
 -1,
 2,
 -1,
 14,
 22,
 110,
 -1,
 33,
 -1,
 28,
 -1,
 -1,
 16,
 1,
 5,
 3,
 30,
 11,
 -1,
 57,
 10,
 0,
 86,
 -1,
 -1,
 4,
 -1,
 30,
 -1,
 -1,
 8,
 -1,
 -1,
 68,
 -1,
 1,
 -1,
 72,
 -1,
 23,
 64,
 9,
 82,
 -1,
 5,
 -1,
 34,
 88,
 -1,
 -1,
 1,
 35,
 0,
 5,
 -1,
 -1,
 0,
 -1,
 3,
 -1,
 10,
 -1,
 3,
 110,
 1,
 7,
 -1,
 2,
 6,
 3,
 1,
 4,
 3,
 14,
 -1,
 -1,
 -1,
 16,
 10,
 53,
 19,
 -1,
 2,
 -1,
 -1,
 -1,
 0,
 0,
 -1,
 6,
 14,
 -1,
 0,
 23,
 1,
 0,
 -1,
 -1,
 7,
 16,
 -1,
 0,
 51,
 8,
 -1,
 -1,
 -1,
 0,
 -1,
 76,
 1,
 27,
 22,
 -1,
 7,
 0,
 45,
 1,
 8,
 -1,
 6,
 -1,
 6,
 2,
 20,
 128,
 7,
 4,
 5,
 0,
 54,
 128,
 -1,
 57,
 5,
 43,
 84,
 45,
 -1,
 75,
 5,
 -1,
 -1,
 -1,
 -1,
 4,
 2,
 75,
 -1,
 -1,
 110,
 -1,
 12,
 0,
 0,
 -1,
 -1,
 -1,
 2,
 0,
 -1,
 11,
 0,
 25,
 -1,
 27,
 89,
 29,
 13,
 6,
 56,
 -1,
 -1,
 65,
 -1,
 -1,
 6,
 -1,
 19,
 -1,
 11,
 18,
 26,
 46,
 -1,
 -1,
 24,
 -1,
 -1,
 9,
 2,
 23,
 -1,
 3,
 0,
 21,
 -1,
 0,
 42,
 -1,
 -1,
 23,
 4,
 -1,
 3,
 41,
 -1,
 -1,
 3,
 -1,
 17,
 32,
 39,
 31,
 100,
 43,
 -1,
 7,
 -1,
 -1,
 2,
 12,
 14,
 1,
 16,
 -1,
 -1,
 66,
 22,
 -1,
 -1,
 66,
 -1,
 -1,
 13,
 -1,
 8,
 57,
 -1,
 -1,
 127,
 25,
 62,
 -1,
 0,
 14,
 1,
 -1,
 -1,
 8,
 19,
 -1,
 -1,
 24,
 -1,
 6,
 15,
 1,
 81,
 -1,
 8,
 -1,
 13,
 74,
 0,
 -1,
 9,
 29,
 3,
 36,
 -1,
 16,
 21,
 26,
 1,
 0,
 0,
 0,
 -1,
 -1,
 0,
 49,
 0,
 -1,
 4,
 6,
 7,
 -1,
 12,
 5,
 0,
 -1,
 110,
 -1,
 0,
 76,
 7,
 -1,
 38,
 -1,
 29,
 -1,
 69,
 -1,
 3,
 39,
 38,
 32,
 -1,
 -1,
 -1,
 58,
 3,
 1,
 15,
 -1,
 13,
 14,
 -1,
 5,
 21,
 55,
 -1,
 0,
 84,
 23,
 11,
 -1,
 113,
 0,
 -1,
 -1,
 19,
 0,
 49,
 51,
 -1,
 30,
 1,
 10,
 42,
 3,
 0,
 -1,
 13,
 0,
 -1,
 -1,
 112,
 123,
 -1,
 -1,
 -1,
 21,
 78,
 16,
 23,
 -1,
 -1,
 -1,
 111,
 15,
 0,
 8,
 -1,
 2,
 -1,
 29,
 -1,
 2,
 43,
 -1,
 5,
 0,
 -1,
 -1,
 9,
 42,
 10,
 5,
 -1,
 1,
 -1,
 19,
 0,
 89,
 5,
 0,
 13,
 124,
 84,
 -1,
 41,
 36,
 -1,
 8,
 -1,
 -1,
 23,
 1,
 1,
 83,
 -1,
 5,
 -1,
 -1,
 2,
 17,
 -1,
 3,
 17,
 -1,
 -1,
 2,
 -1,
 9,
 119,
 23,
 2,
 7,
 8,
 0,
 83,
 8,
 1,
 77,
 7,
 34,
 66,
 9,
 15,
 -1,
 -1,
 30,
 130,
 11,
 -1,
 36,
 -1,
 37,
 129,
 7,
 92,
 9,
 50,
 53,
 -1,
 26,
 -1,
 -1,
 2,
 59,
 117,
 33,
 -1,
 -1,
 32,
 65,
 -1,
 4,
 -1,
 78,
 45,
 9,
 35,
 -1,
 11,
 0,
 0,
 52,
 126,
 4,
 -1,
 1,
 0,
 -1,
 23,
 2,
 11,
 -1,
 10,
 10,
 6,
 7,
 -1,
 5,
 31,
 23,
 -1,
 31,
 112,
 -1,
 3,
 14,
 86,
 -1,
 6,
 38,
 45,
 98,
 13,
 -1,
 36,
 6,
 24,
 23,
 5,
 -1,
 90,
 -1,
 6,
 0,
 18,
 -1,
 10,
 0,
 1,
 -1,
 8,
 -1,
 38,
 5,
 0,
 46,
 0,
 4,
 135,
 0,
 -1,
 34,
 -1,
 -1,
 -1,
 17,
 0,
 3,
 -1,
 11,
 0,
 130,
 -1,
 -1,
 -1,
 1,
 53,
 24,
 3,
 7,
 -1,
 -1,
 0,
 127,
 -1,
 0,
 4,
 0,
 -1,
 2,
 7,
 4,
 -1,
 0,
 10,
 13,
 71,
 130,
 5,
 0,
 -1,
 0,
 93,
 -1,
 0,
 25,
 1,
 41,
 4,
 57,
 6,
 115,
 70,
 22,
 -1,
 10,
 3,
 -1,
 30,
 -1,
 32,
 -1,
 0,
 0,
 2,
 60,
 61,
 0,
 -1,
 2,
 85,
 28,
 77,
 51,
 1,
 -1,
 5,
 -1,
 -1,
 -1,
 4,
 -1,
 -1,
 -1,
 5,
 4,
 -1,
 2,
 89,
 -1,
 -1,
 79,
 -1,
 -1,
 16,
 -1,
 -1,
 -1,
 ...]

In [90]:
probs

array([[2.10871402e-003, 3.43343582e-003, 5.87803299e-003, ...,
        2.84141345e-003, 2.26239610e-002, 2.37913465e-003],
       [1.20205407e-003, 1.51519140e-003, 2.51081534e-003, ...,
        8.41054211e-003, 2.33791211e-003, 1.24118720e-003],
       [7.55399138e-004, 9.96603915e-004, 1.89602825e-003, ...,
        7.83042595e-003, 1.73500574e-003, 8.81361670e-004],
       ...,
       [6.44168527e-308, 8.62108609e-308, 1.53190821e-307, ...,
        5.11565124e-307, 1.45717394e-307, 7.32710859e-308],
       [6.28874762e-308, 9.48535902e-308, 2.00793887e-307, ...,
        1.86045136e-307, 1.17331657e-307, 8.16496906e-308],
       [8.42516338e-004, 1.55914919e-003, 2.67497649e-003, ...,
        1.19661522e-003, 1.67518170e-002, 1.08344222e-003]])

In [95]:
probs.shape

(11083, 137)

In [92]:
log_perplexity = -1 * np.mean(np.log(np.sum(probs, axis=1)))
perplexity = np.exp(log_perplexity)

In [93]:
perplexity

1.4731329155600184

In [94]:
log_perplexity

0.3873913680056718

## What to Vary

In [ ]:
# language="english"
# language="multilingual"
# DeepPavlov/rubert-base-cased-sentence


# raw text or vw text


# default topics (whatever)
# specific number of topics


# KeyBERTInspired
# openchat

## Coherence

In [205]:
import gensim.corpora as corpora

from gensim.models.coherencemodel import CoherenceModel

In [206]:
# Preprocess documents
cleaned_docs = topic_model._preprocess_text(docs)

# Extract vectorizer and tokenizer from BERTopic
vectorizer = topic_model.vectorizer_model
tokenizer = vectorizer.build_tokenizer()

# Extract features for Topic Coherence evaluation
# words = vectorizer.get_feature_names_out()
tokens = [tokenizer(doc) for doc in cleaned_docs]
dictionary = corpora.Dictionary(tokens)
corpus = [dictionary.doc2bow(token) for token in tokens]
topic_words = [[words for words, _ in topic_model.get_topic(topic)] 
               for topic in range(len(set(topics))-1)]

In [40]:
docs[:2]

['I was wondering if anyone out there could enlighten me on this car I saw\nthe other day. It was a 2-door sports car, looked to be from the late 60s/\nearly 70s. It was called a Bricklin. The doors were really small. In addition,\nthe front bumper was separate from the rest of the body. This is \nall I know. If anyone can tellme a model name, engine specs, years\nof production, where this car is made, history, or whatever info you\nhave on this funky looking car, please e-mail.',
 "A fair number of brave souls who upgraded their SI clock oscillator have\nshared their experiences for this poll. Please send a brief message detailing\nyour experiences with the procedure. Top speed attained, CPU rated speed,\nadd on cards and adapters, heat sinks, hour of usage per day, floppy disk\nfunctionality with 800 and 1.4 m floppies are especially requested.\n\nI will be summarizing in the next two days, so please add to the network\nknowledge base if you have done the clock upgrade and haven't answered this\npoll. Thanks."]

In [39]:
cleaned_docs[:2]

['I was wondering if anyone out there could enlighten me on this car I saw the other day It was a 2door sports car looked to be from the late 60s early 70s It was called a Bricklin The doors were really small In addition the front bumper was separate from the rest of the body This is  all I know If anyone can tellme a model name engine specs years of production where this car is made history or whatever info you have on this funky looking car please email',
 'A fair number of brave souls who upgraded their SI clock oscillator have shared their experiences for this poll Please send a brief message detailing your experiences with the procedure Top speed attained CPU rated speed add on cards and adapters heat sinks hour of usage per day floppy disk functionality with 800 and 14 m floppies are especially requested  I will be summarizing in the next two days so please add to the network knowledge base if you have done the clock upgrade and havent answered this poll Thanks']

In [41]:
tokens[:2]

[['was',
  'wondering',
  'if',
  'anyone',
  'out',
  'there',
  'could',
  'enlighten',
  'me',
  'on',
  'this',
  'car',
  'saw',
  'the',
  'other',
  'day',
  'It',
  'was',
  '2door',
  'sports',
  'car',
  'looked',
  'to',
  'be',
  'from',
  'the',
  'late',
  '60s',
  'early',
  '70s',
  'It',
  'was',
  'called',
  'Bricklin',
  'The',
  'doors',
  'were',
  'really',
  'small',
  'In',
  'addition',
  'the',
  'front',
  'bumper',
  'was',
  'separate',
  'from',
  'the',
  'rest',
  'of',
  'the',
  'body',
  'This',
  'is',
  'all',
  'know',
  'If',
  'anyone',
  'can',
  'tellme',
  'model',
  'name',
  'engine',
  'specs',
  'years',
  'of',
  'production',
  'where',
  'this',
  'car',
  'is',
  'made',
  'history',
  'or',
  'whatever',
  'info',
  'you',
  'have',
  'on',
  'this',
  'funky',
  'looking',
  'car',
  'please',
  'email'],
 ['fair',
  'number',
  'of',
  'brave',
  'souls',
  'who',
  'upgraded',
  'their',
  'SI',
  'clock',
  'oscillator',
  'have',
  'shared',
  'their',
  'experiences',
  'for',
  'this',
  'poll',
  'Please',
  'send',
  'brief',
  'message',
  'detailing',
  'your',
  'experiences',
  'with',
  'the',
  'procedure',
  'Top',
  'speed',
  'attained',
  'CPU',
  'rated',
  'speed',
  'add',
  'on',
  'cards',
  'and',
  'adapters',
  'heat',
  'sinks',
  'hour',
  'of',
  'usage',
  'per',
  'day',
  'floppy',
  'disk',
  'functionality',
  'with',
  '800',
  'and',
  '14',
  'floppies',
  'are',
  'especially',
  'requested',
  'will',
  'be',
  'summarizing',
  'in',
  'the',
  'next',
  'two',
  'days',
  'so',
  'please',
  'add',
  'to',
  'the',
  'network',
  'knowledge',
  'base',
  'if',
  'you',
  'have',
  'done',
  'the',
  'clock',
  'upgrade',
  'and',
  'havent',
  'answered',
  'this',
  'poll',
  'Thanks']]

In [42]:
corpus[:2]

[[(0, 1),
  (1, 1),
  (2, 1),
  (3, 1),
  (4, 1),
  (5, 1),
  (6, 2),
  (7, 1),
  (8, 1),
  (9, 1),
  (10, 1),
  (11, 2),
  (12, 1),
  (13, 1),
  (14, 1),
  (15, 1),
  (16, 1),
  (17, 4),
  (18, 1),
  (19, 1),
  (20, 1),
  (21, 1),
  (22, 1),
  (23, 1),
  (24, 1),
  (25, 2),
  (26, 1),
  (27, 1),
  (28, 1),
  (29, 1),
  (30, 1),
  (31, 1),
  (32, 2),
  (33, 1),
  (34, 1),
  (35, 1),
  (36, 1),
  (37, 1),
  (38, 1),
  (39, 1),
  (40, 1),
  (41, 2),
  (42, 2),
  (43, 1),
  (44, 1),
  (45, 1),
  (46, 1),
  (47, 1),
  (48, 1),
  (49, 1),
  (50, 1),
  (51, 1),
  (52, 1),
  (53, 1),
  (54, 1),
  (55, 1),
  (56, 5),
  (57, 1),
  (58, 3),
  (59, 1),
  (60, 4),
  (61, 1),
  (62, 1),
  (63, 1),
  (64, 1),
  (65, 1),
  (66, 1)],
 [(12, 1),
  (19, 1),
  (28, 2),
  (30, 1),
  (41, 2),
  (42, 1),
  (46, 1),
  (56, 4),
  (58, 2),
  (59, 1),
  (66, 1),
  (67, 1),
  (68, 1),
  (69, 1),
  (70, 1),
  (71, 1),
  (72, 1),
  (73, 1),
  (74, 1),
  (75, 2),
  (76, 3),
  (77, 1),
  (78, 1),
  (79, 1),
  (80, 1),
  (81, 1),
  (82, 1),
  (83, 1),
  (84, 2),
  (85, 1),
  (86, 1),
  (87, 1),
  (88, 1),
  (89, 1),
  (90, 2),
  (91, 1),
  (92, 1),
  (93, 1),
  (94, 1),
  (95, 1),
  (96, 1),
  (97, 1),
  (98, 1),
  (99, 1),
  (100, 1),
  (101, 1),
  (102, 1),
  (103, 1),
  (104, 1),
  (105, 1),
  (106, 1),
  (107, 2),
  (108, 1),
  (109, 1),
  (110, 1),
  (111, 1),
  (112, 1),
  (113, 1),
  (114, 1),
  (115, 1),
  (116, 2),
  (117, 1),
  (118, 2),
  (119, 1),
  (120, 1),
  (121, 1),
  (122, 1),
  (123, 1),
  (124, 1),
  (125, 2),
  (126, 1)]]

In [73]:
sum(c[1] for c in corpus[0]), len(tokens[0])

(85, 85)

In [43]:
topic_words[:2]

[['team',
  'game',
  'he',
  'season',
  'games',
  'players',
  'play',
  'hockey',
  'year',
  'league',
  '550',
  '25',
  'the',
  'was',
  'his',
  'teams',
  '10',
  'win',
  'in',
  'at'],
 ['patients',
  'msg',
  'of',
  'medical',
  'is',
  'in',
  'health',
  'it',
  'disease',
  'food',
  'and',
  'my',
  'pain',
  'doctor',
  'to',
  'that',
  'the',
  'are',
  'with',
  'not']]

In [89]:
topic_model.get_topic(0,)

[('team', 0.010900269256075847),
 ('game', 0.009921793726551586),
 ('he', 0.009044523204047363),
 ('season', 0.00804268091819568),
 ('games', 0.007850551383096465),
 ('players', 0.007532173536717949),
 ('play', 0.007504459736665745),
 ('hockey', 0.007266414562241137),
 ('year', 0.006724242233375871),
 ('league', 0.006301846257518863),
 ('550', 0.006271816338817607),
 ('25', 0.006112477134347127),
 ('the', 0.006083746567518168),
 ('was', 0.0060144870280279894),
 ('his', 0.0059936997114055065),
 ('teams', 0.005948035737391088),
 ('10', 0.005773877378121432),
 ('win', 0.0056401455618762765),
 ('in', 0.005637556953264539),
 ('at', 0.00545797057214139)]

In [213]:
len(topic_words)

(146, (97851, 146))

In [215]:
print(topic_words[0])
print()
print(tokens[0])
print([dictionary.token2id[t] for t in tokens[0]])
print(corpus[0])

['team', 'game', 'he', 'season', 'games', 'players', 'play', 'hockey', 'year', 'league', '550', '25', 'the', 'was', 'his', 'teams', '10', 'win', 'in', 'at']

['was', 'wondering', 'if', 'anyone', 'out', 'there', 'could', 'enlighten', 'me', 'on', 'this', 'car', 'saw', 'the', 'other', 'day', 'It', 'was', '2door', 'sports', 'car', 'looked', 'to', 'be', 'from', 'the', 'late', '60s', 'early', '70s', 'It', 'was', 'called', 'Bricklin', 'The', 'doors', 'were', 'really', 'small', 'In', 'addition', 'the', 'front', 'bumper', 'was', 'separate', 'from', 'the', 'rest', 'of', 'the', 'body', 'This', 'is', 'all', 'know', 'If', 'anyone', 'can', 'tellme', 'model', 'name', 'engine', 'specs', 'years', 'of', 'production', 'where', 'this', 'car', 'is', 'made', 'history', 'or', 'whatever', 'info', 'you', 'have', 'on', 'this', 'funky', 'looking', 'car', 'please', 'email']
[60, 64, 30, 11, 45, 57, 18, 24, 38, 42, 58, 17, 50, 56, 44, 19, 6, 60, 0, 54, 17, 35, 59, 12, 25, 56, 34, 1, 21, 2, 6, 60, 15, 3, 7, 20, 61, 48, 52, 5, 9, 56, 26, 14, 60, 51, 25, 56, 49, 41, 56, 13, 8, 32, 10, 33, 4, 11, 16, 55, 39, 40, 23, 53, 65, 41, 47, 63, 58, 17, 32, 37, 29, 43, 62, 31, 66, 28, 42, 58, 27, 36, 17, 46, 22]
[(0, 1), (1, 1), (2, 1), (3, 1), (4, 1), (5, 1), (6, 2), (7, 1), (8, 1), (9, 1), (10, 1), (11, 2), (12, 1), (13, 1), (14, 1), (15, 1), (16, 1), (17, 4), (18, 1), (19, 1), (20, 1), (21, 1), (22, 1), (23, 1), (24, 1), (25, 2), (26, 1), (27, 1), (28, 1), (29, 1), (30, 1), (31, 1), (32, 2), (33, 1), (34, 1), (35, 1), (36, 1), (37, 1), (38, 1), (39, 1), (40, 1), (41, 2), (42, 2), (43, 1), (44, 1), (45, 1), (46, 1), (47, 1), (48, 1), (49, 1), (50, 1), (51, 1), (52, 1), (53, 1), (54, 1), (55, 1), (56, 5), (57, 1), (58, 3), (59, 1), (60, 4), (61, 1), (62, 1), (63, 1), (64, 1), (65, 1), (66, 1)]

In [209]:
# Evaluate
coherence_model = CoherenceModel(topics=topic_words, 
                                 texts=tokens, 
                                 corpus=corpus,
                                 dictionary=dictionary, 
                                 coherence='c_v')
coherence = coherence_model.get_coherence()

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

In [208]:
coherence

-7.049882990674028

In [224]:
ndw = None
pwt = None

ndw = np.zeros(shape=(len(tokens), len(dictionary.token2id)))

for i, doc in enumerate(tokens):
    ids = [dictionary.token2id[t] for t in doc]
    ndw[i, ids] = 1.0

In [232]:
pwt = np.zeros(shape=(len(dictionary.token2id), len(topic_words)))

# Wtf...
# "empty words" https://github.com/MaartenGr/BERTopic/issues/90#issuecomment-1455027341

for i, top in enumerate(topic_words):
    if any(t not in dictionary.token2id for t in top):
        print(i, 'Wow', len([t for t in top if t in dictionary.token2id]))
        print([t for t in top if t not in dictionary.token2id])
    # ids = [dictionary.token2id[t] for t in top]
    # pwt[ids, i] = 1.0

2 Wow 19
['nsa']
4 Wow 19
['fbi']
8 Wow 19
['ssf']
11 Wow 18
['o157h7', 'hus']
15 Wow 19
['jfif']
18 Wow 7
['', '', '', '', '', '', '', '', '', '', '', '', '']
21 Wow 19
['bj200']
24 Wow 17
['enviroleague', 'cramer', 'bsa']
25 Wow 19
['mathcad']
28 Wow 15
['armenian', 'armenians', 'turks', 'armenia', 'argic']
29 Wow 17
['quran', 'rushdie', 'muhammad']
31 Wow 18
['scsi2', 'scsi1']
32 Wow 19
['irqs']
33 Wow 18
['sega', 'snes']
35 Wow 18
['plplot', 'grafsys']
36 Wow 17
['judas', 'decenso', 'matthew']
37 Wow 18
['pmp', 'ccitt']
38 Wow 17
['duke', 'gritz', 'hillary']
39 Wow 19
['fsk']
40 Wow 16
['reagan', 'vat', 'clintons', 'gnp']
41 Wow 15
['cooper', 'spence', 'harris', 'degan', 'atlantic']
42 Wow 16
['hitler', 'limbaugh', 'dg', 'chancellor']
43 Wow 17
['gre', 'dss', 'ets']
44 Wow 19
['atm']
49 Wow 11
['greece', 'cyprus', 'turks', 'cypriot', 'yalcin', 'onur', 'thrace', 'pkk', 'salonica']
50 Wow 17
['zbibs', 'christie', 'c5j0tk52blazecsjhuedu']
52 Wow 13
['x11', 'xremote', 'ncsa', 'xtm', 'urls', 'xrunner', 'ncd']
53 Wow 19
['lsd']
54 Wow 15
['nt', 'os2', 'chicogo', 'c7', 'vc']
56 Wow 18
['stephanopoulos', 'myers']
57 Wow 18
['larsons', 'larson']
58 Wow 16
['armenians', 'azerbaijan', 'sumgait', 'armenian']
63 Wow 15
['nec', 'cdtechnology', 'trantor', '3m', 'md']
64 Wow 18
['ripem', 'rsa']
65 Wow 18
['perth', 'ser']
68 Wow 16
['vinge', 'vernor', 'gibson', 'baen']
70 Wow 18
['sgi', 'pci']
72 Wow 18
['spss', 'ndw']
73 Wow 10
['sleeve1045', 'promopicture', 'sleeve545', 'dec', 'sep', 'london', 'jun', 'sleeve10', 'sleeve1545', 'mccartney']
74 Wow 19
['nec']
75 Wow 19
['hotelco']
76 Wow 18
['celp', 'pcboard']
78 Wow 19
['supra']
80 Wow 14
['libxmulibxmuso', 'libxmulibxmua', 'liblibx11so', 'lxext', 'lx11', 'lxmu']
82 Wow 17
['decibell', 'dbm', 'ohmite']
83 Wow 19
['ch']
84 Wow 19
['mormons']
86 Wow 18
['mactools', 'irwin']
88 Wow 18
['r12', 'militech']
89 Wow 19
['r3']
90 Wow 19
['x11r5']
91 Wow 14
['nec', 't560i', 'nanao', 'viewsonic', '5fg', 'mitsubishi']
92 Wow 19
['mb80']
93 Wow 15
['mary', 'maria', 'joseph', 'alessandro', 'aloysius']
94 Wow 15
['glock', 'glocks', 'kratz', 'ar15', 'm16']
95 Wow 17
['mod2mask', 'xlookupstring', 'mod3mask']
97 Wow 12
['iran', 'iraq', 'iranian', 'irans', 'kuwaitis', 'mack', 'somalia', 'mumin']
99 Wow 15
['hb', 'sb', 'nra', 'hci', 'senate']
100 Wow 19
['aerostitch']
102 Wow 18
['medin', 'ssdnetworking']
104 Wow 19
['euclidean']
105 Wow 13
['pds', 'lciii', 'spigot', 'marvins', 'lclcii', 'lclc', 'etherlan']
106 Wow 17
['dwi', 'beav', 'dwidui']
107 Wow 18
['sb', 'microsofts']
108 Wow 18
['xmugetcolormapallocation', 'xalloccolor']
109 Wow 18
['ishtar', 'bede']
110 Wow 18
['devguide', 'cosecomplient']
111 Wow 17
['cb650', 'ooo', 'anneser']
112 Wow 15
['sandvik', 'ks', 'kent', 'malcolm', 'gen']
113 Wow 17
['alice', 'douglas', 'adams']
115 Wow 19
['grayhill']
116 Wow 16
['solaris', 'x11r5', 'wcl', '22mar93']
117 Wow 14
['scanman', 'ocr', 'mustek', 'paintbrush', 'ocr104zip', 'dexxa']
119 Wow 18
['kirlian', 'krillean']
120 Wow 13
['ejv2jvirginiaedu', '1993apr150242468076virginiaedu', '1r3jgbinn35ielicsyaleedu', 'cheryl', '8aohonj024nsktbdemoncouk', 'strnlghtc5t3nhis1netcomcom', 'velapoldi']
121 Wow 19
['darius']
122 Wow 19
['soundbase']
123 Wow 19
['vip']
124 Wow 19
['bbbbb']
125 Wow 15
['gxxor', 'xsetfunction', 'xdrawline', 'drawindex', 'xflush']
126 Wow 18
['sehari', 'babak']
128 Wow 19
['stephanopoulos']
129 Wow 7
['oto', 'reuss', 'rosicrucian', 'ordo', 'crowley', 'frater', 'orientis', 'templi', 'crucis', 'rosae', 'masonic', 'amorc', 'jose']
130 Wow 17
['tuscon', 'asicic', 'flywrite']
131 Wow 18
['saturns', 'sc1']
132 Wow 15
['archbishop', 'popes', 'sspx', 'lefebvre', 'pius']
133 Wow 18
['eofnotok', 'xvoid']
134 Wow 19
['gudgeon']
135 Wow 19
['clancys']
136 Wow 18
['meguiars', 'mcquires']
137 Wow 16
['powerpc', 'macrescue', 'rocketshare', 'alphas']
138 Wow 11
['masonry', 'masons', 'masonic', 'baptists', 'baptist', 'lewis', 'boobtists', 'holly', 'wbt']
140 Wow 17
['quincy', 'sept', 'cambridge']
141 Wow 15
['wolverine', 'liefeld', 'punisher', 'hobgoblin', 'sabretooth']
142 Wow 19
['bridgend']
143 Wow 15
['c17', 'registries', 'admistration', 'irs', 'hultman']
145 Wow 18
['radiusware', 'nonftp']

In [ ]:
def calc_doc_occurrences(dataset, modality):
    """
    :param n_dw_matrix: sparse document-word matrix, shape is D x W
    :return: sparse matrix of co-occurrences

    doc_occurrences[w1, w2] = the number of the documents
    where there are w1 and w2
    """
    n_dw_matrix = dataset2sparse_matrix(dataset, modality, modalities_to_use=[modality])
    matrix = (scipy.sparse.csc_matrix(n_dw_matrix) > 0).astype(int)
    co_occurrences = matrix.T * matrix

    return co_occurrences.diagonal(), co_occurrences


def create_pmi_top_function(
    doc_occurrences, doc_co_occurrences,
    documents_number, top_sizes,
    topic_indices,
    co_occurrences_smooth=1.
):
    """
    :param doc_occurrences: array of doc occurrences of words
    :param doc_co_occurrences: sparse matrix of doc co-occurrences of words
    :param documents_number: number of the documents
    :param top_sizes: list of top values to calculate top-pmi for
    :param co_occurrences_smooth: constant to smooth co-occurrences in log
    :return: function which takes phi and theta and returns
    pair of two arrays: pmi-s of the tops and ppmi-s of the tops

    pmi[i] - pmi(top of size top_sizes[i])
    ppmi[i] - ppmi(top of size top_sizes[i])

    pmi(words) = sum_{u in words, v in words, u != v}
    log(
        (doc_co_occurrences[u, v] * documents_number + co_occurrences_smooth)
        / doc_occurrences[u] / doc_occurrences[v]
    )

    ppmi(words) = sum_{u in words, v in words, u != v}
    max(log(
        (doc_co_occurrences[u, v] * documents_number + co_occurrences_smooth)
        / doc_occurrences[u] / doc_occurrences[v]
    ), 0)

    """
    def func(phi):
        _T, W = phi.shape
        T = len(topic_indices)

        max_top_size = max(top_sizes)
        topic_pmis, topic_ppmis = dict(), dict()
        pmi, ppmi = np.zeros(max_top_size), np.zeros(max_top_size)
        tops = np.argpartition(phi, -max_top_size, axis=1)[:, -max_top_size:]
        
        for t in topic_indices:
            top = sorted(tops[t], key=lambda w: - phi[t, w])
            co_occurrences = doc_co_occurrences[top, :][:, top].todense()
            occurrences = doc_occurrences[top]
            values = np.log(
                (co_occurrences * documents_number + co_occurrences_smooth)
                / (occurrences[:, np.newaxis] * occurrences[np.newaxis, :] + co_occurrences_smooth)
            )
            diag = np.diag_indices(len(values))
            # values.cumsum(axis=0).cumsum(axis=1)[diag] - values[diag].cumsum()

            current_pmi = np.array(
               values.cumsum(axis=0).cumsum(axis=1)[diag] - values[diag].cumsum()
            ).ravel()
            topic_pmis[t] = current_pmi
            pmi += current_pmi

            values[values < 0.] = 0.
            current_ppmi = np.array(
               values.cumsum(axis=0).cumsum(axis=1)[diag] - values[diag].cumsum()
            ).ravel()
            topic_ppmis[t] = current_ppmi
            ppmi += current_ppmi
            
        sizes = np.arange(2, max_top_size + 1)
        pmi[1:] /= (T * sizes * (sizes - 1))
        ppmi[1:] /= (T * sizes * (sizes - 1))
        indices = np.array(top_sizes) - 1

        for t in topic_indices:
            topic_pmis[t][1:] /= (sizes * (sizes - 1))
            topic_ppmis[t][1:] /= (sizes * (sizes - 1))

        result_topic_pmis = {t: p[indices] for t, p in topic_pmis.items()}
        result_topic_ppmis = {t: p[indices] for t, p in topic_ppmis.items()}

        return pmi[indices], ppmi[indices], result_topic_pmis, result_topic_ppmis

    return func

In [77]:
dataset._data.shape, len(tokens)

((11083, 9), 11083)

### Phi

In [105]:
len(set(topic_model.topics_))

147

In [189]:
mtw = topic_model.c_tf_idf_.todense()

In [135]:
mtw.shape

(147, 97851)

In [191]:
np.array(mtw)[1:, :].sum(axis=1)

array([3.56346638, 3.10507882, 2.7128722 , 2.87366985, 2.74077779,
       2.79496891, 3.4636554 , 3.49910445, 3.0041436 , 3.79459693,
       2.89601544, 3.42699553, 3.08754752, 3.10149963, 2.57138417,
       3.04817793, 3.00007196, 3.0888956 , 3.83028344, 3.22280488,
       3.26336416, 3.02883657, 2.71429369, 2.58917649, 2.83053583,
       2.96035581, 3.07137245, 2.81007088, 3.28559624, 2.6313342 ,
       2.90238166, 2.90559659, 3.03690316, 3.37879376, 2.97614201,
       3.46568821, 2.80391311, 3.00966998, 2.79691684, 2.98821067,
       3.19023788, 3.07400291, 3.0576354 , 3.28224952, 2.90925636,
       2.77563647, 2.82191305, 2.96962409, 2.84291141, 3.13372643,
       2.85583678, 2.8622914 , 3.22138824, 2.8856095 , 2.90385275,
       2.63012925, 2.51448622, 2.77497707, 2.69110536, 3.12499031,
       2.9372357 , 2.77689309, 2.81788986, 3.05512201, 3.17054371,
       4.16136356, 2.83414191, 2.49675063, 3.93767399, 2.64416388,
       3.65592748, 2.76652162, 2.80120099, 4.40402619, 2.87936769,
       4.0090749 , 3.20359689, 2.78470656, 2.94961661, 2.94148024,
       3.73081336, 3.07289674, 3.14768503, 4.14852035, 2.8008932 ,
       3.00884848, 2.82949658, 2.6221306 , 3.0744486 , 3.6582623 ,
       3.08463826, 2.75536351, 2.72654457, 2.87443893, 2.72980994,
       3.13715101, 3.00296921, 2.85917103, 2.63861915, 3.34828506,
       3.07246052, 2.81698589, 3.04694694, 2.90028638, 2.4723626 ,
       2.8296773 , 3.01797055, 2.83290202, 3.00631913, 2.77823365,
       2.89007713, 3.0527487 , 2.82250207, 2.74443139, 2.45520805,
       3.06348305, 2.92529203, 3.20237998, 2.7949877 , 3.21525988,
       2.61655598, 2.51401136, 2.70583224, 2.67367901, 2.67022699,
       3.72613376, 2.6654288 , 2.63767117, 2.5205753 , 3.15923781,
       3.23259867, 2.86868345, 2.86499786, 3.37501539, 3.04607283,
       2.91006993, 3.07443149, 2.93409111, 3.14857603, 2.57057503,
       4.09815818, 4.75630265, 3.22913783, 2.92081211, 3.07636124,
       2.70902728])

In [192]:
words = topic_model.vectorizer_model.get_feature_names_out()

len(words)

97851

In [155]:
sorted(np.array(mtw)[0, :].flatten().tolist())[::-1][:20]

[0.0063124177956318805,
 0.006276808249519071,
 0.006019346309468212,
 0.005973046315855734,
 0.005793875713362026,
 0.005668864903128205,
 0.005517152093163091,
 0.005506158747157938,
 0.005487276281724556,
 0.005388592316167027,
 0.005004271827506273,
 0.004995842743094767,
 0.004908532961604449,
 0.004863292821726821,
 0.004837585272654976,
 0.004793237371584069,
 0.004790825284531761,
 0.004649127977137603,
 0.004562797231896392,
 0.004313145695547128]

In [154]:
sorted(mtw[0, :].A1.flatten().tolist())[::-1][:20]

[0.0063124177956318805,
 0.006276808249519071,
 0.006019346309468212,
 0.005973046315855734,
 0.005793875713362026,
 0.005668864903128205,
 0.005517152093163091,
 0.005506158747157938,
 0.005487276281724556,
 0.005388592316167027,
 0.005004271827506273,
 0.004995842743094767,
 0.004908532961604449,
 0.004863292821726821,
 0.004837585272654976,
 0.004793237371584069,
 0.004790825284531761,
 0.004649127977137603,
 0.004562797231896392,
 0.004313145695547128]

In [134]:
topic_model.get_topic(-1)

[('the', 0.0063124177956318805),
 ('to', 0.006276808249519071),
 ('of', 0.006019346309468212),
 ('and', 0.005973046315855734),
 ('is', 0.005793875713362026),
 ('it', 0.005668864903128205),
 ('you', 0.005517152093163091),
 ('in', 0.005506158747157938),
 ('that', 0.005487276281724556),
 ('for', 0.005388592316167027),
 ('this', 0.005004271827506273),
 ('on', 0.004995842743094767),
 ('have', 0.004908532961604449),
 ('or', 0.004863292821726821),
 ('be', 0.004837585272654976),
 ('are', 0.004793237371584069),
 ('with', 0.004790825284531761),
 ('not', 0.004649127977137603),
 ('as', 0.004562797231896392),
 ('if', 0.004313145695547128)]

In [137]:
sorted(mtw[1, :].A1.flatten().tolist())[::-1][:20]

[0.010900269256075847,
 0.009921793726551586,
 0.009044523204047363,
 0.00804268091819568,
 0.007850551383096465,
 0.007532173536717949,
 0.007504459736665745,
 0.007266414562241137,
 0.006724242233375871,
 0.006301846257518863,
 0.006271816338817607,
 0.006112477134347127,
 0.006083746567518168,
 0.0060144870280279894,
 0.0059936997114055065,
 0.005948035737391088,
 0.005773877378121432,
 0.0056401455618762765,
 0.005637556953264539,
 0.00545797057214139]

In [139]:
topic_model.get_topic(0)

[('team', 0.010900269256075847),
 ('game', 0.009921793726551586),
 ('he', 0.009044523204047363),
 ('season', 0.00804268091819568),
 ('games', 0.007850551383096465),
 ('players', 0.007532173536717949),
 ('play', 0.007504459736665745),
 ('hockey', 0.007266414562241137),
 ('year', 0.006724242233375871),
 ('league', 0.006301846257518863),
 ('550', 0.006271816338817607),
 ('25', 0.006112477134347127),
 ('the', 0.006083746567518168),
 ('was', 0.0060144870280279894),
 ('his', 0.0059936997114055065),
 ('teams', 0.005948035737391088),
 ('10', 0.005773877378121432),
 ('win', 0.0056401455618762765),
 ('in', 0.005637556953264539),
 ('at', 0.00545797057214139)]

In [140]:
sorted(mtw[2, :].A1.flatten().tolist())[::-1][:20]

[0.008225435670288439,
 0.007675207243832949,
 0.007097770156330537,
 0.007076393680885589,
 0.006857175282278966,
 0.006750022312755742,
 0.00674334665663572,
 0.006675360874634684,
 0.0065142434634148155,
 0.006365144616629374,
 0.006327225914152524,
 0.006265112378657712,
 0.005992096694001469,
 0.005982135032937046,
 0.0059308194023600744,
 0.005876374098087719,
 0.005674275999080568,
 0.005454009676637061,
 0.005275251949351446,
 0.005172557279229124]

In [141]:
topic_model.get_topic(1)

[('patients', 0.008225435670288439),
 ('msg', 0.007675207243832949),
 ('of', 0.007097770156330537),
 ('medical', 0.007076393680885589),
 ('is', 0.006857175282278966),
 ('in', 0.006750022312755742),
 ('health', 0.00674334665663572),
 ('it', 0.006675360874634684),
 ('disease', 0.0065142434634148155),
 ('food', 0.006365144616629374),
 ('and', 0.006327225914152524),
 ('my', 0.006265112378657712),
 ('pain', 0.005992096694001469),
 ('doctor', 0.005982135032937046),
 ('to', 0.0059308194023600744),
 ('that', 0.005876374098087719),
 ('the', 0.005674275999080568),
 ('are', 0.005454009676637061),
 ('with', 0.005275251949351446),
 ('not', 0.005172557279229124)]

In [193]:
ptw = np.array(mtw[1:, :])

ptw.shape

(146, 97851)

In [194]:
pwt = ptw.T

pwt.shape

(97851, 146)

In [181]:
topic_model.vectorizer_model.vocabulary_

{'do': 32133,
 'you': 97300,
 'have': 42823,
 'weiteks': 93882,
 'addressphone': 13502,
 'number': 65239,
 'id': 45264,
 'like': 52319,
 'to': 88041,
 'get': 40254,
 'some': 82231,
 'information': 46549,
 'about': 12889,
 'this': 87379,
 'chip': 24028,
 'from': 38908,
 'article': 16753,
 'c5owcbn3pworldstdcom': 22038,
 'by': 21914,
 'tombakerworldstdcom': 88149,
 'tom': 88138,
 'baker': 18253,
 'my': 62545,
 'understanding': 90297,
 'is': 47780,
 'that': 87055,
 'the': 87078,
 'expected': 36023,
 'errors': 35183,
 'are': 16415,
 'basically': 18632,
 'known': 50438,
 'bugs': 21501,
 'in': 45986,
 'warning': 93432,
 'system': 85798,
 'software': 82098,
 'things': 87321,
 'checked': 23798,
 'dont': 32381,
 'right': 76658,
 'values': 91810,
 'yet': 97186,
 'because': 18927,
 'they': 87273,
 'arent': 16433,
 'set': 79983,
 'till': 87763,
 'after': 13910,
 'launch': 51383,
 'and': 15272,
 'suchlike': 84782,
 'rather': 74183,
 'than': 87031,
 'fix': 37714,
 'code': 25114,
 'possibly': 70716,
 'introduce': 47428,
 'new': 63739,
 'just': 49238,
 'tell': 86665,
 'crew': 27922,
 'ok': 65968,
 'if': 45385,
 'see': 79392,
 'no': 64277,
 '213': 5821,
 'before': 19009,
 'liftoff': 52273,
 'ignore': 45445,
 'it': 47988,
 'of': 65779,
 'course': 27574,
 'term': 86807,
 'must': 62086,
 'be': 18845,
 'rigidly': 76700,
 'defined': 29916,
 'any': 15814,
 'bill': 19670,
 'doubt': 32520,
 'she': 80327,
 'uses': 91295,
 'for': 38263,
 'using': 91308,
 'quote': 73662,
 'allegedly': 14544,
 'her': 43326,
 'can': 22386,
 'back': 18062,
 'up': 91004,
 'read': 74395,
 'as': 16794,
 'presenting': 71377,
 'first': 37628,
 'an': 15161,
 'argument': 16481,
 'weapons': 93754,
 'mass': 55936,
 'destruction': 30612,
 'commonly': 25625,
 'understood': 90306,
 'then': 87142,
 'switching': 85594,
 'other': 66880,
 'topics': 88261,
 'point': 70331,
 'evidently': 35658,
 'was': 93479,
 'show': 80697,
 'not': 64943,
 'all': 14522,
 'should': 80669,
 'allowed': 14624,
 'later': 51331,
 'analysis': 15209,
 'given': 40504,
 'consider': 26585,
 'another': 15551,
 'class': 24584,
 'win': 94528,
 '30': 7039,
 'downloaded': 32575,
 'several': 80050,
 'icons': 45232,
 'bmps': 20271,
 'but': 21808,
 'cant': 22492,
 'figure': 37406,
 'out': 66950,
 'how': 44491,
 'change': 23601,
 'wallpaper': 93323,
 'or': 66555,
 'use': 91223,
 'help': 43236,
 'would': 95160,
 'appreciated': 16140,
 'thanx': 87052,
 'brando': 20911,
 'yep': 97166,
 'thats': 87068,
 'pretty': 71469,
 'much': 61651,
 'im': 45623,
 'jew': 48589,
 'understand': 90292,
 'jewish': 48595,
 'way': 93589,
 'thinking': 87334,
 'however': 44502,
 'jews': 48603,
 'believe': 19145,
 'covenant': 27611,
 'between': 19454,
 'yhwh': 97206,
 'patriarchs': 68308,
 'abraham': 12897,
 'moses': 60534,
 'case': 22849,
 'establishes': 35349,
 'moral': 60429,
 'follow': 38166,
 'mankind': 55533,
 'even': 35581,
 'could': 27467,
 'decide': 29646,
 'where': 94173,
 'boundaries': 20736,
 'fall': 36642,
 'though': 87447,
 'sadducees': 78003,
 'believed': 19146,
 'torah': 88291,
 'required': 75880,
 'whereas': 94175,
 'pharisees': 69274,
 'ancestors': 15258,
 'modern': 60042,
 'judaism': 49088,
 'available': 17714,
 'interpretation': 47289,
 'lead': 51555,
 'morality': 60434,
 'its': 48051,
 'nuances': 65200,
 'talmud': 86131,
 'essence': 35334,
 'biblical': 19553,
 'interface': 47184,
 'man': 55428,
 'christian': 24164,
 'does': 32244,
 'necessarily': 63345,
 'indicate': 46248,
 'anything': 15837,
 'outside': 67095,
 'relationship': 75365,
 'although': 14822,
 'one': 66177,
 'speculate': 82749,
 'trouble': 89117,
 'with': 94781,
 'we': 93726,
 'really': 74490,
 'know': 50416,
 'what': 94121,
 'created': 27857,
 'his': 43794,
 'image': 45628,
 'means': 56927,
 'ive': 48105,
 'heard': 43021,
 'different': 31102,
 'opinions': 66433,
 'on': 66153,
 'still': 83944,
 'come': 25469,
 'conclusion': 26183,
 'upsets': 91087,
 'apple': 16047,
 'cart': 22805,
 'wants': 93383,
 'base': 18591,
 'life': 52238,
 'script': 79065,
 'shaky': 80203,
 'foundation': 38525,
 'mix': 59102,
 'metaphors': 57535,
 'unashamedly': 90051,
 'living': 52678,
 'christs': 24204,
 'example': 35744,
 'very': 92299,
 'little': 52637,
 'jesus': 48568,
 'person': 69036,
 'only': 66255,
 'recorded': 74825,
 'utterances': 91476,
 'narratives': 63055,
 'followers': 38170,
 'small': 81691,
 'references': 75047,
 'comtemporary': 26104,
 'historians': 43819,
 'revelation': 76335,
 'aside': 16881,
 'christ': 24156,
 'secondhand': 79308,
 'worse': 95135,
 'attempt': 17373,
 'debunk': 29591,
 'christianity': 24168,
 'may': 56204,
 'seem': 79414,
 'initially': 46696,
 'trying': 89214,
 'make': 55285,
 'bible': 19547,
 'interpret': 47288,
 'humanity': 44723,
 'guess': 41805,
 'faith': 36615,
 'relevation': 75411,
 'comes': 25476,
 'inherent': 46653,
 'subjectiveness': 84564,
 'there': 87197,
 'absolute': 12928,
 'undoubtably': 90352,
 'multiple': 61837,
 'codes': 25130,
 'founded': 38527,
 'parent': 67989,
 'child': 23970,
 'never': 63727,
 'swear': 85506,
 'assume': 17053,
 'swears': 85509,
 'simply': 81085,
 'has': 42728,
 'told': 88119,
 'wrong': 95294,
 'now': 65051,
 'trooper': 89105,
 'pub': 72560,
 'bar': 18443,
 'children': 23986,
 'wrongness': 95303,
 'here': 43350,
 'disobeys': 31675,
 'feel': 37079,
 'inappropriate': 46014,
 'front': 38920,
 'quite': 73638,
 'happy': 42539,
 'animals': 15406,
 'analogy': 15199,
 'hold': 44040,
 'water': 93525,
 'knows': 50441,
 'he': 42950,
 'same': 78198,
 'type': 89649,
 'gist': 40497,
 'incidentally': 46063,
 'young': 97313,
 'considers': 26595,
 'directive': 31327,
 'until': 90925,
 'gets': 40287,
 'older': 66018,
 'piaget': 69550,
 'learns': 51616,
 'own': 67350,
 'david': 29292,
 'religion': 75444,
 'so': 81954,
 'sure': 85264,
 'look': 52998,
 'happened': 42528,
 'japanese': 48344,
 'citizens': 24456,
 'us': 91171,
 'during': 33193,
 'world': 95104,
 'war': 93386,
 'ii': 45475,
 'youre': 97328,
 'prepared': 71317,
 'say': 78496,
 'lets': 51949,
 'round': 77373,
 'these': 87248,
 'people': 68805,
 'stick': 83919,
 'them': 87123,
 'concentration': 26142,
 'camp': 22358,
 'without': 94806,
 'trial': 88942,
 'short': 80615,
 'step': 83798,
 'gassing': 39794,
 'seems': 79418,
 'nazis': 63218,
 'originally': 66710,
 'intended': 47099,
 'imprison': 45947,
 'final': 37490,
 'solution': 82212,
 'dreamt': 32735,
 'partly': 68120,
 'couldnt': 27469,
 'afford': 13862,
 'run': 77681,
 'camps': 22379,
 'devastation': 30747,
 'caused': 23005,
 'goerings': 40840,
 'total': 88374,
 'those': 87440,
 'who': 94299,
 'werent': 93996,
 'gassed': 39790,
 'generally': 40050,
 'died': 31058,
 'malnutrition': 55387,
 'disease': 31560,
 'question': 73549,
 'exact': 35718,
 'entry': 34858,
 'parameter': 67948,
 'syntax': 85759,
 'please': 70095,
 'xterminal': 96539,
 'configuration': 26313,
 'file': 37413,
 'loaded': 52771,
 'when': 94168,
 'boots': 20576,
 'add': 13460,
 'tcpip': 86417,
 'access': 13065,
 'control': 26960,
 'list': 52549,
 'background': 18088,
 'two': 89567,
 'unix': 90614,
 'systems': 85825,
 'att': 17321,
 '3b2': 7927,
 'running': 77695,
 'x11r3': 95474,
 'mits': 59072,
 'x11r4': 95477,
 'sun': 84957,
 'ss10': 83254,
 'want': 93375,
 'window': 94559,
 'ncd': 63241,
 'at': 17171,
 'time': 87779,
 'manually': 55580,
 'network': 63650,
 'off': 65786,
 'login': 52908,
 'telnet': 86674,
 'session': 79977,
 'great': 41385,
 'tried': 88982,
 'xhost': 95900,
 'work': 95056,
 'failed': 36571,
 'either': 33949,
 'implementation': 45870,
 'bogus': 20382,
 'am': 14913,
 'edit': 33687,
 'matter': 56090,
 'containing': 26747,
 'manuals': 55581,
 'worthless': 95154,
 'most': 60556,
 'thanks': 87041,
 'me': 56867,
 'least': 51625,
 'orders': 66613,
 'motto': 60675,
 'think': 87327,
 'thing': 87316,
 'will': 94468,
 'specific': 82698,
 'problem': 71749,
 'mentioned': 57319,
 'your': 97326,
 'message': 57461,
 'definitely': 29928,
 'had': 42166,
 'scsi': 79108,
 'problems': 71764,
 'q700': 73266,
 'venerable': 92137,
 'jasmine': 48367,
 'megadrive': 57106,
 '10': 1419,
 'cartridge': 22827,
 'drives': 32812,
 'silverlining': 81015,
 'none': 64502,
 'loops': 53027,
 'involved': 47554,
 'blind': 20101,
 'writes': 95282,
 'worked': 95066,
 'fact': 36508,
 'loop': 53022,
 'macintosh': 54885,
 'whatever': 94127,
 'yes': 97173,
 'adamantly': 13412,
 'environmentalist': 34898,
 'styrofoam': 84492,
 'table': 85945,
 'service': 79947,
 'keep': 49713,
 'mind': 58598,
 'post': 70717,
 'wish': 94761,
 'attack': 17348,
 'environmentalism': 34895,
 'half': 42260,
 'truth': 89194,
 'dangerous': 29052,
 'complete': 25866,
 'lie': 52216,
 'rarely': 74130,
 'readily': 74409,
 'accepted': 13057,
 'while': 94210,
 'subtly': 84717,
 'hidden': 43547,
 'more': 60447,
 'powerfully': 70889,
 'offered': 65812,
 'masquerades': 55934,
 'angel': 15364,
 'light': 52279,
 'satan': 78385,
 'loosened': 53033,
 'grip': 41544,
 'treating': 88882,
 'earth': 33432,
 'something': 82258,
 'gods': 40824,
 'intricate': 47414,
 'handiwork': 42443,
 'which': 94199,
 'health': 43009,
 'future': 39394,
 'generations': 40063,
 'based': 18601,
 'being': 19091,
 'treated': 88880,
 'respect': 76061,
 'hes': 43438,
 'going': 40859,
 'happily': 42537,
 'leave': 51633,
 'error': 35179,
 'rejected': 75328,
 'style': 84481,
 'push': 73121,
 'opposite': 66476,
 'therefore': 87207,
 'rubbish': 77572,
 'god': 40793,
 'mother': 60586,
 'primarily': 71553,
 'love': 53137,
 'serve': 79931,
 'facets': 36487,
 'response': 76091,
 'care': 22675,
 'environment': 34893,
 'treat': 88878,
 'proper': 72122,
 'both': 20689,
 'generation': 40062,
 'showing': 80710,
 'facet': 36483,
 'disregardful': 31781,
 'such': 84780,
 'constitute': 26669,
 'apostle': 15983,
 'paul': 68351,
 'called': 22273,
 'becoming': 18937,
 'men': 57272,
 'possible': 70712,
 'might': 58376,
 'save': 78469,
 'forget': 38362,
 'got': 41023,
 'important': 45905,
 'spend': 82813,
 'putting': 73149,
 'foot': 38235,
 'mouth': 60725,
 'manner': 55541,
 'destroy': 30595,
 'credibility': 27885,
 'expressing': 36196,
 'ultimate': 89954,
 'entity': 34830,
 'creature': 27880,
 'creator': 27876,
 'beauty': 18916,
 'glory': 40656,
 'points': 70349,
 'greater': 41387,
 'tapestry': 86217,
 'many': 55614,
 'cords': 27234,
 'woven': 95182,
 'infinite': 46453,
 'depends': 30331,
 'priorities': 71664,
 'lot': 53093,
 'put': 73140,
 'higher': 43589,
 'gas': 39768,
 'mileage': 58468,
 'cost': 27428,
 'safety': 78040,
 'buying': 21868,
 'unsafe': 90825,
 'econoboxes': 33620,
 'instead': 46971,
 'volvos': 92910,
 'personally': 69051,
 'take': 86053,
 'middle': 58303,
 'ground': 41593,
 'threepoint': 87508,
 'seatbelt': 79248,
 '5mph': 9720,
 'bumpers': 21611,
 '30mph': 7204,
 'collisions': 25327,
 'into': 47381,
 'brick': 21086,
 'walls': 93327,
 'common': 25620,
 'enough': 34741,
 'extra': 36264,
 'money': 60232,
 'protection': 72249,
 'lots': 53095,
 'lowspeed': 53206,
 'worry': 95133,
 'covers': 27626,
 'sony': 82300,
 'check': 23795,
 'local': 52807,
 'car': 22604,
 'stereo': 83827,
 'shop': 80599,
 'probably': 71736,
 'provide': 72326,
 'units': 90577,
 'serial': 79893,
 'hopefully': 44280,
 'registered': 75189,
 'warranty': 93453,
 'card': 22648,
 'replacements': 75729,
 'damage': 28994,
 'face': 36468,
 'cover': 27614,
 'stands': 83492,
 'reason': 74539,
 'replaced': 75727,
 'deterring': 30685,
 'theft': 87103,
 'referred': 75056,
 'customer': 28627,
 '800': 11148,
 'sell': 79627,
 'nor': 64848,
 'did': 31041,
 'came': 22339,
 'asking': 16901,
 'pullout': 72972,
 'sleave': 81522,
 'disheartened': 31595,
 'find': 37510,
 'acquired': 13292,
 'deck': 29673,
 'occurs': 65684,
 'decks': 29676,
 'notify': 64987,
 'numbers': 65251,
 'catch': 22940,
 'theives': 87118,
 'interest': 47174,
 'subject': 84556,
 'exploding': 36111,
 'televisions': 86659,
 'were': 93991,
 'major': 55262,
 'cause': 23004,
 'domestic': 32319,
 'accidents': 13095,
 'soviet': 82463,
 'union': 90543,
 'past': 68216,
 'years': 97120,
 'once': 66163,
 'again': 13942,
 'appears': 16026,
 'oneeyed': 66191,
 'appeared': 16023,
 'land': 51110,
 'sighted': 80912,
 'strange': 84176,
 'resaon': 75906,
 'appointed': 16109,
 'himself': 43721,
 'ruler': 77642,
 'supreme': 85250,
 'power': 70873,
 'oh': 65912,
 'boy': 20784,
 'kbike': 49653,
 'versus': 92275,
 'scuffling': 79130,
 'grow': 41637,
 'goes': 40842,
 'hope': 44277,
 'dump': 33130,
 'dempster': 30226,
 'campaign': 22360,
 'works': 95087,
 'crook': 28044,
 'suprised': 85256,
 'taken': 86056,
 'long': 52948,
 'done': 32359,
 'obviously': 65637,
 'aint': 14177,
 'over': 67128,
 'hand': 42407,
 'bed': 18943,
 'wackos': 93209,
 'throwing': 87562,
 '20oo': 5720,
 'down': 32561,
 'rathole': 74185,
 'effective': 33805,
 'sending': 79735,
 'club': 24908,
 'wouldnt': 95167,
 'magazine': 55028,
 'ever': 35611,
 'since': 81122,
 'moa': 59940,
 'politburo': 70418,
 'installed': 46954,
 'don': 32345,
 'lacked': 51008,
 'sort': 82356,
 'panache': 67794,
 'ah': 14070,
 'western': 94035,
 'digital': 31154,
 '18008324778sam': 4568,
 'easy': 33489,
 'rider': 76621,
 'harleys': 42648,
 'drugs': 32877,
 'rednecks': 74948,
 'orleans': 66737,
 'mad': 54979,
 'max': 56151,
 'violence': 92605,
 'dod': 32198,
 'wannabes': 93373,
 'honda': 44207,
 'thumper': 87602,
 'travel': 88833,
 'sunday': 84989,
 'documentary': 32190,
 'dirtbike': 31355,
 'racers': 73792,
 'escape': 35242,
 'steve': 83870,
 'mcqueen': 56688,
 'rebel': 74576,
 'james': 48290,
 'dean': 29531,
 'doders': 32214,
 'last': 51301,
 'old': 66013,
 'movies': 60758,
 'havent': 42829,
 'seen': 79419,
 '8177': 11386,
 'techniciandr': 86502,
 'speed': 82764,
 'student': 84415,
 'pat': 68241,
 'sez': 80098,
 'yeah': 97090,
 'windscreen': 94596,
 'cut': 28641,
 'canopies': 22485,
 'ended': 34579,
 'completely': 25871,
 'space': 82493,
 'continues': 26815,
 'suck': 84784,
 'tommy': 88160,
 'mac': 54799,
 'mcwilliams': 56722,
 '5173552178': 9266,
 'wk': 94854,
 'radius': 73878,
 'vision': 92670,
 'increases': 46155,
 '18084tmibmclmsuedu': 4617,
 '3369591': 7476,
 'hm': 43905,
 'circumference': 24409,
 'mystery': 62684,
 'grows': 41643,
 'write': 95274,
 'display': 31733,
 'program': 71913,
 'mit': 59031,
 'shared': 80257,
 'memory': 57262,
 'extension': 36229,
 'segment': 79443,
 'allocated': 14609,
 'attached': 17343,
 'process': 71794,
 'crashes': 27815,
 'call': 22261,
 'xshmputimage': 96361,
 'following': 38175,
 'request': 75866,
 'badshmseg': 18193,
 'invalid': 47469,
 'opcode': 66335,
 '133': 3256,
 'mitshm': 59079,
 'minor': 58722,
 '0x0': 1371,
 '741': 10809,
 'current': 28569,
 'output': 67054,
 'stream': 84232,
 '742': 10815,
 'said': 78071,
 'checking': 23802,
 'calls': 22290,
 'shmget': 80557,
 'shmat': 80556,
 'necessary': 63346,
 'create': 27855,
 'well': 93903,
 'xshmattach': 96359,
 'anybody': 15817,
 'used': 91227,
 'having': 42839,
 'let': 51942,
 'openwindows': 66391,
 'sparc2': 82598,
 'squid': 83200,
 'tradition': 88569,
 'alive': 14509,
 'kinda': 50144,
 'fish': 37662,
 'unh': 90466,
 'games': 39631,
 'notice': 64978,
 'toshiba': 88365,
 '3401': 7510,
 'versions': 92271,
 'internal': 47243,
 'external': 36245,
 'portable': 70619,
 'anyone': 15830,
 'difference': 31100,
 'version': 92267,
 'sf': 80099,
 'bay': 18752,
 'area': 16416,
 'model': 59998,
 'ford': 38289,
 'automobile': 17660,
 'need': 63380,
 'whether': 94190,
 'partially': 68085,
 'responsible': 76102,
 'depletion': 30339,
 'ozone': 67408,
 'layer': 51467,
 'also': 14745,
 'additional': 13478,
 'greatly': 41393,
 'sssssoooooooooooo': 83296,
 'fault': 36905,
 'thank': 87036,
 'louis': 53109,
 'chevrolet': 23922,
 'innocent': 46777,
 'guy': 41990,
 'diesel': 31072,
 'otto': 66912,
 'guilty': 41837,
 'twin': 89539,
 'size': 81297,
 'mattress': 56106,
 'box': 20771,
 'spring': 83089,
 'frame': 38624,
 'sale': 78112,
 'medicopedic': 57033,
 'excellent': 35776,
 'condition': 26232,
 'yrs': 97374,
 'maintained': 55220,
 'pick': 69565,
 'stuff': 84434,
 'located': 52835,
 'paloalto': 67771,
 '75': 10857,
 'contact': 26731,
 'suresh': 85271,
 '4156173522': 8353,
 '4153249553': 8343,
 'email': 34250,
 'sureshpadeccom': 85272,
 'yo': 97260,
 'watch': 93514,
 'attributionsi': 17438,
 'didnt': 31051,
 'isnt': 47889,
 'appropriate': 16167,
 'forum': 38492,
 'discussions': 31556,
 'shoot': 80588,
 'someone': 82245,
 'property': 72127,
 'damagevandalismtheft': 28998,
 'every': 35628,
 'gun': 41879,
 'owner': 67352,
 'realizes': 74483,
 'limits': 52378,
 'punishment': 73026,
 'fit': 37684,
 'crime': 27938,
 'mean': 56916,
 'itis': 48044,
 'harmless': 42656,
 'prank': 71029,
 'worth': 95150,
 'killing': 50104,
 'situation': 81264,
 'described': 30468,
 'punks': 73032,
 'setting': 80009,
 'alarms': 14331,
 'taunting': 86326,
 'turn': 89431,
 'ugly': 89868,
 'quickly': 73586,
 'potentially': 70817,
 'line': 52415,
 '1986': 5069,
 'acura': 13384,
 'integra': 47064,
 '95000': 12246,
 'miles': 58470,
 'positively': 70683,
 'worst': 95148,
 'owned': 67351,
 '83': 11450,
 'prelude': 71278,
 '160k': 4067,
 'sold': 82149,
 'strong': 84356,
 'religious': 75451,
 'attention': 17390,
 'maintenance': 55230,
 'oil': 65943,
 'changes': 23614,
 'etc': 35394,
 'cars': 22796,
 'driven': 32794,
 'exactly': 35719,
 'gone': 40918,
 'through': 87548,
 'clutches': 24935,
 'underrated': 90280,
 'sets': 80003,
 'tires': 87912,
 'eats': 33507,
 'careful': 22684,
 'align': 14496,
 'struts': 84385,
 'started': 83564,
 'leaking': 51590,
 '2530k': 6409,
 'windshield': 94600,
 'wiper': 94713,
 'motor': 60646,
 'burned': 21706,
 'note': 64954,
 'seek': 79405,
 'stop': 84084,
 'working': 95074,
 'radio': 73847,
 '20k': 5702,
 'timing': 87845,
 'belts': 19204,
 'constant': 26650,
 'signals': 80936,
 'computer': 26064,
 'finally': 37495,
 'rod': 77076,
 'bearing': 18882,
 'went': 93987,
 'piston': 69800,
 'seriously': 79910,
 'damaging': 28999,
 'crankshaft': 27802,
 'contaminating': 26754,
 'engine': 34670,
 'overhaul': 67177,
 'week': 93816,
 'cam': 22320,
 'shaft': 80171,
 'camshaft': 22385,
 'shattered': 80307,
 'mill': 58512,
 'took': 88212,
 'weeks': 93828,
 'national': 63121,
 'order': 66603,
 'everything': 35638,
 'unique': 90556,
 'year': 97095,
 'design': 30505,
 '87': 11625,
 ...}

In [187]:
topic_model.vectorizer_model.vocabulary_['zysv2j6q8hb0nsrlxeod3ediwnpqzmthd2']

97841

In [184]:
topic_model.vectorizer_model

CountVectorizer()

In [162]:
topic_model.vectorizer_model.get_feature_names_out()[-100:]

array(['zopfi', 'zorasterism', 'zorastrian', 'zorg', 'zork', 'zorns',
       'zoro', 'zoroaster', 'zoroasters', 'zoroastrian', 'zoroastrianism',
       'zoroastrians', 'zoronenecnpurdueedu', 'zorro', 'zortech', 'zou',
       'zpixmap', 'zpqwcm', 'zq6kkf8hkjoj5jcwcfper6j', 'zqat0',
       'zqqwx8ymnm', 'zqvos', 'zr', 'zr1100', 'zr550',
       'zrai02houamococom', 'zrcj81yupzzkr6cgetl911p8dvvcfjdv', 'zs',
       'zsc3tiztgzqbhv4wtgqhlt0fhy9xc', 'zset', 'zsofts', 'zt5k2hjoj',
       'zterm', 'ztimer', 'zu', 'zua1', 'zubin', 'zubkoff', 'zubov',
       'zuck', 'zucker', 'zues', 'zugcsmilumichedu', 'zuiko', 'zullen',
       'zulu', 'zum', 'zuma', 'zumatomnetcomsvnetcomcom', 'zumdahl',
       'zumrut', 'zumwalt', 'zup1y2p', 'zupancic', 'zupcic',
       'zuqjfl4ck064i', 'zur', 'zurbrins', 'zurich', 'zurueckfuehren',
       'zurvanism', 'zusman', 'zuur14af', 'zv', 'zvfd', 'zvg', 'zvi',
       'zviqrbth3b3f0rhcpuy1ju53jy5prcdpaxafrlxrhfydmv1i',
       'zvjt84i3j3nru', 'zvkxy', 'zvri', 'zvt7k8mjo8bmffs6q5m6',
       'zvv17uq9q5vcaosp', 'zw4', 'zwaartepunten', 'zwak', 'zwakke',
       'zware', 'zwarte', 'zwhw3x', 'zwischen', 'zwl18345',
       'zwo8psg6hced7pcm1r4kil', 'zx10', 'zx11', 'zx49fzqsjh2podxtz1',
       'zx6', 'zx7', 'zx900', 'zx900a',
       'zysv2j6q8hb0nsrlxeod3ediwnpqzmthd2', 'zyugh5pzi72g', 'zyxel',
       'zyxel1496b', 'zz', 'zz960', 'zzc2', 'zzzs', 'zzzzzz', 'zzzzzzt'],
      dtype=object)

In [188]:
for d in docs:
    if 'zysv2j6q8hb0nsrlxeod3ediwnpqzmthd2' in d:
        print(d)

In [195]:
phi = pd.DataFrame(
    index=topic_model.vectorizer_model.get_feature_names_out(),
    columns=[f'topic_{i}' for i in range(pwt.shape[1])],
    data=pwt
)

In [196]:
phi.shape

(97851, 146)

In [197]:
phi.head()

,topic_0,topic_1,topic_2,topic_3,topic_4,topic_5,topic_6,topic_7,topic_8,topic_9,...,topic_136,topic_137,topic_138,topic_139,topic_140,topic_141,topic_142,topic_143,topic_144,topic_145
00,0.002510,0.000000,0.0,0.000000,0.0,0.0,0.000548,0.0,0.0,0.001562,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
000,0.002201,0.000061,0.0,0.000093,0.0,0.0,0.000000,0.0,0.0,0.000338,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
0000,0.001564,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
00000,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000676,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [198]:
phi.sum(axis=0)

topic_0      3.563466
topic_1      3.105079
topic_2      2.712872
topic_3      2.873670
topic_4      2.740778
               ...
topic_141    4.756303
topic_142    3.229138
topic_143    2.920812
topic_144    3.076361
topic_145    2.709027
Length: 146, dtype: float64

phi = phi / phi.sum(axis=0)

In [170]:
phi.sum(axis=0)

topic_0      1.0
topic_1      1.0
topic_2      1.0
topic_3      1.0
topic_4      1.0
            ...
topic_141    1.0
topic_142    1.0
topic_143    1.0
topic_144    1.0
topic_145    1.0
Length: 146, dtype: float64

In [199]:
phi.to_csv('test_bt_phi.csv')

In [200]:
phi.sum(axis=0)

topic_0      3.563466
topic_1      3.105079
topic_2      2.712872
topic_3      2.873670
topic_4      2.740778
               ...
topic_141    4.756303
topic_142    3.229138
topic_143    2.920812
topic_144    3.076361
topic_145    2.709027
Length: 146, dtype: float64

In [203]:
import json

In [202]:
topic_top_words = {
    f'topic_{t}': topic_model.get_topic(t)
    for t in range(pwt.shape[1])
}

In [204]:
with open('test_bt_topwords.json', 'w') as f:
    f.write(
        json.dumps(
            topic_top_words, indent=4, ensure_ascii=False
        )
    )

In [201]:
topic_model.get_topic(0)

[('team', 0.010900269256075847),
 ('game', 0.009921793726551586),
 ('he', 0.009044523204047363),
 ('season', 0.00804268091819568),
 ('games', 0.007850551383096465),
 ('players', 0.007532173536717949),
 ('play', 0.007504459736665745),
 ('hockey', 0.007266414562241137),
 ('year', 0.006724242233375871),
 ('league', 0.006301846257518863),
 ('550', 0.006271816338817607),
 ('25', 0.006112477134347127),
 ('the', 0.006083746567518168),
 ('was', 0.0060144870280279894),
 ('his', 0.0059936997114055065),
 ('teams', 0.005948035737391088),
 ('10', 0.005773877378121432),
 ('win', 0.0056401455618762765),
 ('in', 0.005637556953264539),
 ('at', 0.00545797057214139)]

### Dataset

In [176]:
texts = [
    d + ' |@word ' + ' '.join(t)
    for d, t in zip(dataset._data.index, tokens)
]
new_data = pd.DataFrame(
    columns=['id', 'vw_text'],
    data=[[d, t] for d, t in zip(dataset._data.index, texts)],
)

In [177]:
new_data.head()

,id,vw_text
0,rec_autos_102994,rec_autos_102994 |@word was wondering if anyon...
1,comp_sys_mac_hardware_51861,comp_sys_mac_hardware_51861 |@word fair number...
2,comp_sys_mac_hardware_51879,comp_sys_mac_hardware_51879 |@word well folks ...
3,comp_graphics_38242,comp_graphics_38242 |@word Do you have Weiteks...
4,sci_space_60880,sci_space_60880 |@word From article C5owCBn3pw...

In [178]:
new_data.to_csv('test_bt_dataset.csv')

In [ ]:
# language="english"
# language="multilingual"
# DeepPavlov/rubert-base-cased-sentence


# raw text or vw text


# default topics (whatever)
# specific number of topics


# KeyBERTInspired
# openchat

In [159]:
from topicnet.cooking_machine import Dataset

from bertopic import BERTopic
from bertopic.representation import KeyBERTInspired, MaximalMarginalRelevance, TextGeneration

from umap import UMAP
from hdbscan import HDBSCAN

from hdbscan.flat import HDBSCAN_flat

from sklearn.feature_extraction.text import CountVectorizer

import gensim.corpora as corpora

from gensim.models.coherencemodel import CoherenceModel

import pandas as pd

In [2]:
DATA_FOLDER_PATH = '/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/dataset_manager'

In [3]:
! ls $DATA_FOLDER_PATH

20NG.csv	 MKB10__internals      RTL_Wiki_person.csv
20NG__internals  postnauka.csv	       RTL_Wiki_person__internals
api.py		 postnauka__internals  ruwiki_good__internals
Brown		 __pycache__	       ruwiki_good.txt
Brown_BOW.csv	 Reuters	       WikiRef-220
Brown_NOOW.csv	 Reuters_BOW.csv       wiki_ref220_bow.csv
__init__.py	 Reuters_NOOW.csv      wiki_ref220_natural_order.csv
MKB10.csv	 RTL_Wiki.csv

In [4]:
dataset = Dataset(
    f'{DATA_FOLDER_PATH}/20NG.csv',
)

dataset.get_possible_modalities()

{'@bigram', '@lemmatized'}

In [102]:
MAIN_MODALITY = '@lemmatized'

In [5]:
dataset._data.head()

,Unnamed: 0,raw_text,filenames,target,id,tokenized,lemmatized,bigram,vw_text
id,,,,,,,,,
rec_autos_102994,0,I was wondering if anyone out there could enli...,/home/egorov/scikit_learn_data/20news_home/20n...,7,rec_autos_102994,"[('was', 'VBD'), ('wondering', 'VBG'), ('if', ...","['wonder', 'anyone', 'could', 'enlighten', 'ca...","['wonder_anyone', 'anyone_could', 'sport_car',...",rec_autos_102994 |@lemmatized wonder:1 anyone:...
comp_sys_mac_hardware_51861,1,A fair number of brave souls who upgraded thei...,/home/egorov/scikit_learn_data/20news_home/20n...,4,comp_sys_mac_hardware_51861,"[('fair', 'JJ'), ('number', 'NN'), ('of', 'IN'...","['fair', 'number', 'brave', 'soul', 'upgrade',...","['clock_oscillator', 'please_send', 'top_speed...",comp_sys_mac_hardware_51861 |@lemmatized fair:...
comp_sys_mac_hardware_51879,2,"well folks, my mac plus finally gave up the gh...",/home/egorov/scikit_learn_data/20news_home/20n...,4,comp_sys_mac_hardware_51879,"[('well', 'RB'), ('folks', 'NNS'), ('my', 'PRP...","['well', 'folk', 'mac', 'plus', 'finally', 'gi...","['mac_plus', 'life_way', 'way_back', 'market_n...",comp_sys_mac_hardware_51879 |@lemmatized well:...
comp_graphics_38242,3,\nDo you have Weitek's address/phone number? ...,/home/egorov/scikit_learn_data/20news_home/20n...,1,comp_graphics_38242,"[('do', 'VBP'), ('you', 'PRP'), ('have', 'VB')...","['weitek', 'address', 'phone', 'number', 'like...","['address_phone', 'phone_number', 'number_like...",comp_graphics_38242 |@lemmatized weitek:1 addr...
sci_space_60880,4,"From article <C5owCB.n3p@world.std.com>, by to...",/home/egorov/scikit_learn_data/20news_home/20n...,14,sci_space_60880,"[('from', 'IN'), ('article', 'NN'), ('by', 'IN...","['article', 'tom', 'baker', 'understanding', '...","['system_software', 'thing_check', 'introduce_...",sci_space_60880 |@lemmatized article:1 tom:1 b...

In [6]:
dataset._data.shape

(11301, 9)

In [7]:
dataset._data.dropna(axis=0, inplace=True)

In [8]:
dataset._data.shape

(11083, 9)

In [9]:
dataset._data['raw_text']

id
rec_autos_102994                  I was wondering if anyone out there could enli...
comp_sys_mac_hardware_51861       A fair number of brave souls who upgraded thei...
comp_sys_mac_hardware_51879       well folks, my mac plus finally gave up the gh...
comp_graphics_38242               \nDo you have Weitek's address/phone number?  ...
sci_space_60880                   From article <C5owCB.n3p@world.std.com>, by to...
                                                        ...
sci_med_58069                     DN> From: nyeda@cnsvax.uwec.edu (David Nye)\nD...
comp_sys_mac_hardware_51712       I have a (very old) Mac 512k and a Mac Plus, b...
comp_sys_ibm_pc_hardware_60695    I just installed a DX2-66 CPU in a clone mothe...
comp_graphics_38319               \nWouldn't this require a hyper-sphere.  In 3-...
rec_motorcycles_104440            Stolen from Pasadena between 4:30 and 6:30 pm ...
Name: raw_text, Length: 11083, dtype: object

In [10]:
docs = list(dataset._data['raw_text'].values)

In [11]:
docs[:3]

['I was wondering if anyone out there could enlighten me on this car I saw\nthe other day. It was a 2-door sports car, looked to be from the late 60s/\nearly 70s. It was called a Bricklin. The doors were really small. In addition,\nthe front bumper was separate from the rest of the body. This is \nall I know. If anyone can tellme a model name, engine specs, years\nof production, where this car is made, history, or whatever info you\nhave on this funky looking car, please e-mail.',
 "A fair number of brave souls who upgraded their SI clock oscillator have\nshared their experiences for this poll. Please send a brief message detailing\nyour experiences with the procedure. Top speed attained, CPU rated speed,\nadd on cards and adapters, heat sinks, hour of usage per day, floppy disk\nfunctionality with 800 and 1.4 m floppies are especially requested.\n\nI will be summarizing in the next two days, so please add to the network\nknowledge base if you have done the clock upgrade and haven't answered this\npoll. Thanks.",
 'well folks, my mac plus finally gave up the ghost this weekend after\nstarting life as a 512k way back in 1985.  sooo, i\'m in the market for a\nnew machine a bit sooner than i intended to be...\n\ni\'m looking into picking up a powerbook 160 or maybe 180 and have a bunch\nof questions that (hopefully) somebody can answer:\n\n* does anybody know any dirt on when the next round of powerbook\nintroductions are expected?  i\'d heard the 185c was supposed to make an\nappearence "this summer" but haven\'t heard anymore on it - and since i\ndon\'t have access to macleak, i was wondering if anybody out there had\nmore info...\n\n* has anybody heard rumors about price drops to the powerbook line like the\nones the duo\'s just went through recently?\n\n* what\'s the impression of the display on the 180?  i could probably swing\na 180 if i got the 80Mb disk rather than the 120, but i don\'t really have\na feel for how much "better" the display is (yea, it looks great in the\nstore, but is that all "wow" or is it really that good?).  could i solicit\nsome opinions of people who use the 160 and 180 day-to-day on if its worth\ntaking the disk size and money hit to get the active display?  (i realize\nthis is a real subjective question, but i\'ve only played around with the\nmachines in a computer store breifly and figured the opinions of somebody\nwho actually uses the machine daily might prove helpful).\n\n* how well does hellcats perform?  ;)\n\nthanks a bunch in advance for any info - if you could email, i\'ll post a\nsummary (news reading time is at a premium with finals just around the\ncorner... :( )\n--\nTom Willis  \\  twillis@ecn.purdue.edu    \\    Purdue Electrical Engineering']

In [12]:
NUM_TOP_WORDS = 20

In [13]:
import torch
import transformers
import os

import json
import numpy as np

os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"   # see issue #152
os.environ["CUDA_VISIBLE_DEVICES"] = "0"

In [14]:
from torch import bfloat16
import transformers

# set quantization configuration to load large model with less GPU memory
# this requires the `bitsandbytes` library

bnb_config = transformers.BitsAndBytesConfig(
    load_in_4bit=True,  # 4-bit quantization
    bnb_4bit_quant_type='nf4',  # Normalized float 4
    bnb_4bit_use_double_quant=True,  # Second quantization after the first
    bnb_4bit_compute_dtype=bfloat16  # Computation type
)

In [15]:
model_path = '/data_mil/shared/CompressaAI/deploy/models/models/openchat_openchat-3.5-1210'
tokenizer = transformers.AutoTokenizer.from_pretrained(model_path)

model = transformers.AutoModelForCausalLM.from_pretrained(
    model_path,
    trust_remote_code=True,
    quantization_config=bnb_config,
    device_map='auto',
)
model.eval()

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

MistralForCausalLM(
  (model): MistralModel(
    (embed_tokens): Embedding(32002, 4096)
    (layers): ModuleList(
      (0-31): 32 x MistralDecoderLayer(
        (self_attn): MistralSdpaAttention(
          (q_proj): Linear4bit(in_features=4096, out_features=4096, bias=False)
          (k_proj): Linear4bit(in_features=4096, out_features=1024, bias=False)
          (v_proj): Linear4bit(in_features=4096, out_features=1024, bias=False)
          (o_proj): Linear4bit(in_features=4096, out_features=4096, bias=False)
          (rotary_emb): MistralRotaryEmbedding()
        )
        (mlp): MistralMLP(
          (gate_proj): Linear4bit(in_features=4096, out_features=14336, bias=False)
          (up_proj): Linear4bit(in_features=4096, out_features=14336, bias=False)
          (down_proj): Linear4bit(in_features=14336, out_features=4096, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): MistralRMSNorm()
        (post_attention_layernorm): MistralRMSNorm()
      )
    )
    (norm): MistralRMSNorm()
  )
  (lm_head): Linear(in_features=4096, out_features=32002, bias=False)
)

In [42]:
generator = transformers.pipeline(
    model=model, tokenizer=tokenizer,
    task='text-generation',
    temperature=0.1,
    max_new_tokens=256,
    repetition_penalty=1.1
)

In [43]:
prompt = "Could you explain to me how 4-bit quantization works as if I am 5?"
res = generator(prompt)
print(res[0]["generated_text"])

Could you explain to me how 4-bit quantization works as if I am 5?

Well, imagine you have a big box of crayons. You have 16 different colors to choose from. Each color represents a number from 0 to 15. When we want to represent sound or a picture with just 4 bits, we are only using 4 of these colors at a time. So, each color can be one of 4 different things. This means that we can represent many different sounds and pictures with just a few colors! And that's how 4-bit quantization works.

## Answer (2)

Quantization is the process of reducing the amount of information in a signal. In this case, 4-bit quantization means that the signal is reduced to 4 bits. This is done by taking the original signal and mapping it to one of 16 possible values (since there are 2^4 = 16 possible combinations of 4 bits).

For example, let's say we have an analog signal that varies continuously over time. We could take samples of this signal at regular intervals and assign each sample a value between 0 and 255 (since there are 8 bits in a byte, and we can represent 256

# System prompt describes information given to all conversations
system_prompt = """
<s>[INST] <<SYS>>
You are a helpful, respectful and honest assistant for labeling topics.
<</SYS>>
"""

# Example prompt demonstrating the output we are looking for
example_prompt = """
I have a topic that contains the following documents:
- Traditional diets in most cultures were primarily plant-based with a little meat on top, but with the rise of industrial style meat production and factory farming, meat has become a staple food.
- Meat, but especially beef, is the word food in terms of emissions.
- Eating meat doesn't make you a bad person, not eating meat doesn't make you a good one.

The topic is described by the following keywords: 'meat, beef, eat, eating, emissions, steak, food, health, processed, chicken'.

Based on the information about the topic above, please create a short label of this topic. Make sure you to only return the label and nothing more.

[/INST] Environmental impacts of eating meat
"""

# Our main prompt with documents ([DOCUMENTS]) and keywords ([KEYWORDS]) tags
main_prompt = """
[INST]
I have a topic that contains the following documents:
[DOCUMENTS]

The topic is described by the following keywords: '[KEYWORDS]'.

Based on the information about the topic above, please create a short label of this topic. Make sure you to only return the label and nothing more.
[/INST]
"""

In [21]:
"""<s>You are a friendly chatbot who always responds in the style of a pirate<|end_of_turn|>GPT4 Correct User: Hello, my name is<|end_of_turn|>GPT4 Correct Assistant: Charlie<|end_of_turn|>GPT4 Correct User: How are you, Charlie?<|end_of_turn|>GPT4 Correct Assistant: 
"""

'<s>You are a friendly chatbot who always responds in the style of a pirate<|end_of_turn|>GPT4 Correct User: Hello, my name is<|end_of_turn|>GPT4 Correct Assistant: Charlie<|end_of_turn|>GPT4 Correct User: How are you, Charlie?<|end_of_turn|>GPT4 Correct Assistant: \n'

In [31]:
# System prompt describes information given to all conversations
system_prompt = """<s>You are a helpful, respectful and honest assistant for labeling topics.<|end_of_turn|>"""

# Example prompt demonstrating the output we are looking for
example_prompt = """GPT4 Correct User: I have a topic that contains the following documents:
- Traditional diets in most cultures were primarily plant-based with a little meat on top, but with the rise of industrial style meat production and factory farming, meat has become a staple food.
- Meat, but especially beef, is the word food in terms of emissions.
- Eating meat doesn't make you a bad person, not eating meat doesn't make you a good one.

The topic is described by the following keywords: 'meat, beef, eat, eating, emissions, steak, food, health, processed, chicken'.

Based on the information about the topic above, please create a short label of this topic. Make sure you to only return the label and nothing more.<|end_of_turn|>GPT4 Correct Assistant: Environmental impacts of eating meat<|end_of_turn|>"""

# Our main prompt with documents ([DOCUMENTS]) and keywords ([KEYWORDS]) tags
main_prompt = """GPT4 Correct User: I have a topic that contains the following documents:
[DOCUMENTS]

The topic is described by the following keywords: '[KEYWORDS]'.

Based on the information about the topic above, please create a short label of this topic. Make sure you to only return the label and nothing more.<|end_of_turn|>GPT4 Correct Assistant: """

In [32]:
prompt = system_prompt + example_prompt + main_prompt

In [33]:
prompt

"<s>You are a helpful, respectful and honest assistant for labeling topics.<|end_of_turn|>GPT4 Correct User: I have a topic that contains the following documents:\n- Traditional diets in most cultures were primarily plant-based with a little meat on top, but with the rise of industrial style meat production and factory farming, meat has become a staple food.\n- Meat, but especially beef, is the word food in terms of emissions.\n- Eating meat doesn't make you a bad person, not eating meat doesn't make you a good one.\n\nThe topic is described by the following keywords: 'meat, beef, eat, eating, emissions, steak, food, health, processed, chicken'.\n\nBased on the information about the topic above, please create a short label of this topic. Make sure you to only return the label and nothing more.<|end_of_turn|>GPT4 Correct Assistant: Environmental impacts of eating meat<|end_of_turn|>GPT4 Correct User: I have a topic that contains the following documents:\n[DOCUMENTS]\n\nThe topic is described by the following keywords: '[KEYWORDS]'.\n\nBased on the information about the topic above, please create a short label of this topic. Make sure you to only return the label and nothing more.<|end_of_turn|>GPT4 Correct Assistant: "

In [221]:
def get_phi(topic_model):
    mtw = topic_model.c_tf_idf_.todense()
    # ptw = np.array(mtw[1:, :])
    ptw = np.array(mtw[0:, :])
    pwt = ptw.T
    vocabulary = topic_model.vectorizer_model.get_feature_names_out()

    assert pwt.shape[0] == len(vocabulary)

    # topic_names = [f'topic_{i}' for i in range(pwt.shape[1])]
    topic_names = ['background_1'] + [f'topic_{i}' for i in range(NUM_TOPICS)]
    phi = pd.DataFrame(
        index=vocabulary,
        columns=topic_names,
        data=pwt,
    )

    return phi


def get_top_words(topic_model):
    topic_names = [f'topic_{i}' for i in range(pwt.shape[1])]
    topic_top_words = {
        n: topic_model.get_topic(t)
        for t, n in enumerate(topic_names)
    }

    return topic_top_words


def get_dataset(topic_model, dataset, docs):
    cleaned_docs = topic_model._preprocess_text(docs)
    vectorizer = topic_model.vectorizer_model
    tokenizer = vectorizer.build_tokenizer()
    doc_tokens = [tokenizer(doc) for doc in cleaned_docs]
    doc_texts = [
        d + f' |{MAIN_MODALITY} ' + ' '.join(t)
        for d, t in zip(dataset._data.index, doc_tokens)
    ]
    data = [[d, t] for d, t in zip(dataset._data.index, doc_texts)]

    new_dataset = pd.DataFrame(
        columns=['id', 'vw_text'],
        data=data,
    )

    return new_dataset

In [62]:
# KeyBERT
keybert = KeyBERTInspired(top_n_words=NUM_TOP_WORDS)

# MMR
mmr = MaximalMarginalRelevance(diversity=0.3, top_n_words=NUM_TOP_WORDS)

# Text generation with Llama 2
# llama2 = TextGeneration(generator, prompt=prompt)

# All representation models
representation_model = {
    "KeyBERT": keybert,
    # "OpenChat": llama2,
    "MMR": mmr,
}

In [206]:
topic_model = BERTopic(
    language="english",
    top_n_words=NUM_TOP_WORDS,
    calculate_probabilities=True,
    verbose=True,

    # embedding_model=embedding_model,          # Step 1 - Extract embeddings
    # umap_model=umap_model,                    # Step 2 - Reduce dimensionality
    # hdbscan_model=hdbscan_model,              # Step 3 - Cluster reduced embeddings
    # vectorizer_model=vectorizer_model,        # Step 4 - Tokenize topics
    # ctfidf_model=ctfidf_model,                # Step 5 - Extract topic words
    # representation_model=representation_model # Step 6 - (Optional) Fine-tune topic represenations
)

In [207]:
topic_model.umap_model

UMAP(low_memory=False, metric='cosine', min_dist=0.0, n_components=5)

In [208]:
topic_model.umap_model.n_neighbors

15

In [146]:
# Step 2 - Reduce dimensionality
umap_model = UMAP(n_neighbors=15, n_components=5, min_dist=0.0, metric='cosine', random_state=1)

# https://stackoverflow.com/questions/48269092/hdbscan-python-choose-number-of-clusters
# Step 3 - Cluster reduced embeddings
# hdbscan_model = HDBSCAN(min_cluster_size=100, metric='euclidean', cluster_selection_method='eom', prediction_data=True)
# hdbscan_model = flat.HDBSCAN_flat(train_df, n_clusters, prediction_data=True)


# Step 4 - Tokenize topics
vectorizer_model = CountVectorizer(stop_words="english")

In [147]:
topic_model = BERTopic(
    language="english",
    top_n_words=NUM_TOP_WORDS,
    calculate_probabilities=True,
    verbose=True,

    # embedding_model=embedding_model,          # Step 1 - Extract embeddings
    umap_model=umap_model,                    # Step 2 - Reduce dimensionality
    # hdbscan_model=hdbscan_model,              # Step 3 - Cluster reduced embeddings
    vectorizer_model=vectorizer_model,        # Step 4 - Tokenize topics
    # ctfidf_model=ctfidf_model,                # Step 5 - Extract topic words
    representation_model=representation_model # Step 6 - (Optional) Fine-tune topic represenations
)

In [148]:
topic_model.umap_model.random_state

1

In [149]:
topics, probs = topic_model.fit_transform(docs)

2024-03-29 22:04:34,456 - BERTopic - Embedding - Transforming documents to embeddings.

Batches:   0%|          | 0/347 [00:00<?, ?it/s]

2024-03-29 22:04:48,373 - BERTopic - Embedding - Completed ✓
2024-03-29 22:04:48,374 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2024-03-29 22:04:57,422 - BERTopic - Dimensionality - Completed ✓
2024-03-29 22:04:57,424 - BERTopic - Cluster - Start clustering the reduced embeddings
2024-03-29 22:05:06,532 - BERTopic - Cluster - Completed ✓
2024-03-29 22:05:06,537 - BERTopic - Representation - Extracting topics from clusters using representation models.
2024-03-29 22:05:19,399 - BERTopic - Representation - Completed ✓

In [150]:
len(set(topic_model.topics_))

136

In [151]:
dataset._data.shape

(11083, 9)

In [117]:
topic_model.umap_model.embedding_.shape

(11083, 5)

In [152]:
hdbscan_model = HDBSCAN_flat(topic_model.umap_model.embedding_, n_clusters=20)  #, prediction_data=True)

In [153]:
hdbscan_model

HDBSCAN(cluster_selection_epsilon=0.33129008180280073, prediction_data=True)

In [154]:
topic_model = BERTopic(
    language="english",
    top_n_words=NUM_TOP_WORDS,
    calculate_probabilities=True,
    verbose=True,

    # embedding_model=embedding_model,          # Step 1 - Extract embeddings
    umap_model=umap_model,                    # Step 2 - Reduce dimensionality
    hdbscan_model=hdbscan_model,              # Step 3 - Cluster reduced embeddings
    vectorizer_model=vectorizer_model,        # Step 4 - Tokenize topics
    # ctfidf_model=ctfidf_model,                # Step 5 - Extract topic words
    representation_model=representation_model # Step 6 - (Optional) Fine-tune topic represenations
)

In [155]:
topics, probs = topic_model.fit_transform(docs)

2024-03-29 22:05:46,013 - BERTopic - Embedding - Transforming documents to embeddings.

Batches:   0%|          | 0/347 [00:00<?, ?it/s]

2024-03-29 22:05:59,983 - BERTopic - Embedding - Completed ✓
2024-03-29 22:05:59,985 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2024-03-29 22:06:08,646 - BERTopic - Dimensionality - Completed ✓
2024-03-29 22:06:08,648 - BERTopic - Cluster - Start clustering the reduced embeddings
2024-03-29 22:06:56,664 - BERTopic - Cluster - Completed ✓
2024-03-29 22:06:56,669 - BERTopic - Representation - Extracting topics from clusters using representation models.
2024-03-29 22:07:01,047 - BERTopic - Representation - Completed ✓

In [156]:
len(set(topic_model.topics_))

21

In [158]:
topic_model.c_tf_idf_.shape

(21, 97541)

In [157]:
topic_model.get_topic(0)

[('people', 0.015297706905967537),
 ('god', 0.012687628400613112),
 ('think', 0.010985258485161426),
 ('dont', 0.010980406138379617),
 ('just', 0.010369635420305565),
 ('know', 0.009540448616711755),
 ('like', 0.009174781367005965),
 ('say', 0.008689509094080002),
 ('time', 0.00860874843720445),
 ('does', 0.008502158794777346),
 ('government', 0.00812413700368287),
 ('believe', 0.008070026197978602),
 ('jesus', 0.007788213345369761),
 ('law', 0.007614496560170818),
 ('make', 0.007425778785642179),
 ('did', 0.007395395346989908),
 ('right', 0.007374335839871709),
 ('space', 0.007333386229654495),
 ('key', 0.00725698599971484),
 ('way', 0.007247474834753649)]

In [77]:
topic_model.get_topic(0, full=True)['KeyBERT']

[('nhl', 0.57515335),
 ('flyers', 0.52925265),
 ('puck', 0.4984485),
 ('hockey', 0.48788503),
 ('leafs', 0.45429933),
 ('playoffs', 0.44142944),
 ('braves', 0.4068522),
 ('scoring', 0.40493107),
 ('cubs', 0.40447882),
 ('pitching', 0.38590068),
 ('montreal', 0.3821814),
 ('rangers', 0.37668484),
 ('baseball', 0.34920204),
 ('league', 0.3386966),
 ('calgary', 0.29792172),
 ('division', 0.2952005),
 ('players', 0.29363966),
 ('teams', 0.29198802),
 ('toronto', 0.28364572),
 ('philadelphia', 0.28136683)]

In [186]:
phi = get_phi(topic_model)
top_words = get_top_words(topic_model)

In [ ]:
phi.to_csv('test_bt_phi.csv')

with open('test_bt_topwords.json', 'w') as f:
    f.write(
        json.dumps(
            topic_top_words, indent=4, ensure_ascii=False
        )
    )

In [193]:
new_dataset = get_dataset(topic_model, dataset, docs)

In [194]:
new_dataset.head()

,id,vw_text
0,rec_autos_102994,rec_autos_102994 @lemmatized was wondering if ...
1,comp_sys_mac_hardware_51861,comp_sys_mac_hardware_51861 @lemmatized fair n...
2,comp_sys_mac_hardware_51879,comp_sys_mac_hardware_51879 @lemmatized well f...
3,comp_graphics_38242,comp_graphics_38242 @lemmatized Do you have We...
4,sci_space_60880,sci_space_60880 @lemmatized From article C5owC...

In [ ]:
new_dataset.to_csv('test_bt_dataset.csv')

In [209]:
NUM_TOPICS = 20
NUM_TOP_WORDS = 20
NUM_TRAINS = 20
STOP_WORDS = 'english'
LANGUAGE = 'english'

In [200]:
! ls ../results

20newsgroups  mkb10  postnauka	rtlwikiperson  ruwikigood

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

In [204]:
SAVE_FOLDER = os.path.join('/data_mil/shared/CompressaAI/BERTopic', 'results', '20newsgroups')

In [205]:
! mkdir -p $SAVE_FOLDER

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

In [224]:
for seed in range(NUM_TRAINS):
    print(seed)

    seed_save_folder = os.path.join(SAVE_FOLDER, str(seed))

    os.makedirs(seed_save_folder)

    keybert = KeyBERTInspired(top_n_words=NUM_TOP_WORDS)
    mmr = MaximalMarginalRelevance(diversity=0.3, top_n_words=NUM_TOP_WORDS)
    
    representation_model = {
        "KeyBERT": keybert,
        "MMR": mmr,
    }

    umap_model = UMAP(n_neighbors=15, n_components=5, min_dist=0.0, metric='cosine', random_state=seed)
    vectorizer_model = CountVectorizer(stop_words=STOP_WORDS)

    topic_model = BERTopic(
        language=LANGUAGE,
        top_n_words=NUM_TOP_WORDS,

        calculate_probabilities=True,
        verbose=True,
    
        umap_model=umap_model,                    # Step 2 - Reduce dimensionality
        # hdbscan_model=hdbscan_model,            # Step 3 - Cluster reduced embeddings
        vectorizer_model=vectorizer_model,        # Step 4 - Tokenize topics
        representation_model=representation_model # Step 6 - (Optional) Fine-tune topic represenations
    )
        
    topics, probs = topic_model.fit_transform(docs)
    orig_num_topics = len(set(topic_model.topics_))
    doc_embeddings = topic_model.umap_model.embedding_

    hdbscan_model = HDBSCAN_flat(doc_embeddings, n_clusters=NUM_TOPICS)
    
    topic_model = BERTopic(
        language=LANGUAGE,
        top_n_words=NUM_TOP_WORDS,
        calculate_probabilities=True,
        verbose=True,
    
        umap_model=umap_model,                    # Step 2 - Reduce dimensionality
        hdbscan_model=hdbscan_model,              # Step 3 - Cluster reduced embeddings
        vectorizer_model=vectorizer_model,        # Step 4 - Tokenize topics
        representation_model=representation_model # Step 6 - (Optional) Fine-tune topic represenations
    )

    topics, probs = topic_model.fit_transform(docs)
    
    new_num_topics = len(set(topic_model.topics_))
    
    assert new_num_topics < orig_num_topics
    assert new_num_topics == NUM_TOPICS + 1
    assert topic_model.c_tf_idf_.shape[0] == new_num_topics
    
    phi = get_phi(topic_model)
    top_words = get_top_words(topic_model)
    new_dataset = get_dataset(topic_model, dataset, docs)
    
    phi.to_csv(f'{seed_save_folder}/phi.csv')
    
    with open(f'{seed_save_folder}/top_words.json', 'w') as f:
        f.write(
            json.dumps(
                top_words, indent=4, ensure_ascii=False
            )
        )
    
    new_dataset.to_csv(f'{seed_save_folder}/dataset.csv')

    del topic_model, phi, new_dataset

2024-03-29 23:21:53,767 - BERTopic - Embedding - Transforming documents to embeddings.

0

Batches:   0%|          | 0/347 [00:00<?, ?it/s]

2024-03-29 23:22:07,707 - BERTopic - Embedding - Completed ✓
2024-03-29 23:22:07,709 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2024-03-29 23:22:16,327 - BERTopic - Dimensionality - Completed ✓
2024-03-29 23:22:16,329 - BERTopic - Cluster - Start clustering the reduced embeddings
2024-03-29 23:22:24,769 - BERTopic - Cluster - Completed ✓
2024-03-29 23:22:24,774 - BERTopic - Representation - Extracting topics from clusters using representation models.
2024-03-29 23:22:36,647 - BERTopic - Representation - Completed ✓
2024-03-29 23:22:38,926 - BERTopic - Embedding - Transforming documents to embeddings.

Batches:   0%|          | 0/347 [00:00<?, ?it/s]

2024-03-29 23:22:52,838 - BERTopic - Embedding - Completed ✓
2024-03-29 23:22:52,839 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2024-03-29 23:23:02,262 - BERTopic - Dimensionality - Completed ✓
2024-03-29 23:23:02,264 - BERTopic - Cluster - Start clustering the reduced embeddings
2024-03-29 23:23:54,641 - BERTopic - Cluster - Completed ✓
2024-03-29 23:23:54,645 - BERTopic - Representation - Extracting topics from clusters using representation models.
2024-03-29 23:23:58,801 - BERTopic - Representation - Completed ✓
2024-03-29 23:24:01,228 - BERTopic - Embedding - Transforming documents to embeddings.

1

Batches:   0%|          | 0/347 [00:00<?, ?it/s]

2024-03-29 23:24:15,222 - BERTopic - Embedding - Completed ✓
2024-03-29 23:24:15,223 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2024-03-29 23:24:23,814 - BERTopic - Dimensionality - Completed ✓
2024-03-29 23:24:23,816 - BERTopic - Cluster - Start clustering the reduced embeddings
2024-03-29 23:24:32,547 - BERTopic - Cluster - Completed ✓
2024-03-29 23:24:32,552 - BERTopic - Representation - Extracting topics from clusters using representation models.
2024-03-29 23:24:45,888 - BERTopic - Representation - Completed ✓
2024-03-29 23:24:48,154 - BERTopic - Embedding - Transforming documents to embeddings.

Batches:   0%|          | 0/347 [00:00<?, ?it/s]

2024-03-29 23:25:02,007 - BERTopic - Embedding - Completed ✓
2024-03-29 23:25:02,008 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2024-03-29 23:25:10,822 - BERTopic - Dimensionality - Completed ✓
2024-03-29 23:25:10,823 - BERTopic - Cluster - Start clustering the reduced embeddings
2024-03-29 23:25:59,214 - BERTopic - Cluster - Completed ✓
2024-03-29 23:25:59,219 - BERTopic - Representation - Extracting topics from clusters using representation models.
2024-03-29 23:26:03,646 - BERTopic - Representation - Completed ✓
2024-03-29 23:26:06,017 - BERTopic - Embedding - Transforming documents to embeddings.

2

Batches:   0%|          | 0/347 [00:00<?, ?it/s]

2024-03-29 23:26:20,245 - BERTopic - Embedding - Completed ✓
2024-03-29 23:26:20,246 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2024-03-29 23:26:29,076 - BERTopic - Dimensionality - Completed ✓
2024-03-29 23:26:29,077 - BERTopic - Cluster - Start clustering the reduced embeddings
2024-03-29 23:26:36,908 - BERTopic - Cluster - Completed ✓
2024-03-29 23:26:36,912 - BERTopic - Representation - Extracting topics from clusters using representation models.
2024-03-29 23:26:48,707 - BERTopic - Representation - Completed ✓
2024-03-29 23:26:50,972 - BERTopic - Embedding - Transforming documents to embeddings.

Batches:   0%|          | 0/347 [00:00<?, ?it/s]

2024-03-29 23:27:05,026 - BERTopic - Embedding - Completed ✓
2024-03-29 23:27:05,027 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2024-03-29 23:27:13,734 - BERTopic - Dimensionality - Completed ✓
2024-03-29 23:27:13,736 - BERTopic - Cluster - Start clustering the reduced embeddings
2024-03-29 23:28:05,971 - BERTopic - Cluster - Completed ✓
2024-03-29 23:28:05,976 - BERTopic - Representation - Extracting topics from clusters using representation models.
2024-03-29 23:28:10,160 - BERTopic - Representation - Completed ✓
2024-03-29 23:28:12,584 - BERTopic - Embedding - Transforming documents to embeddings.

3

Batches:   0%|          | 0/347 [00:00<?, ?it/s]

2024-03-29 23:28:26,612 - BERTopic - Embedding - Completed ✓
2024-03-29 23:28:26,613 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2024-03-29 23:28:35,750 - BERTopic - Dimensionality - Completed ✓
2024-03-29 23:28:35,752 - BERTopic - Cluster - Start clustering the reduced embeddings
2024-03-29 23:28:45,014 - BERTopic - Cluster - Completed ✓
2024-03-29 23:28:45,019 - BERTopic - Representation - Extracting topics from clusters using representation models.
2024-03-29 23:28:57,128 - BERTopic - Representation - Completed ✓
2024-03-29 23:28:59,470 - BERTopic - Embedding - Transforming documents to embeddings.

Batches:   0%|          | 0/347 [00:00<?, ?it/s]

2024-03-29 23:29:13,413 - BERTopic - Embedding - Completed ✓
2024-03-29 23:29:13,414 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2024-03-29 23:29:22,049 - BERTopic - Dimensionality - Completed ✓
2024-03-29 23:29:22,050 - BERTopic - Cluster - Start clustering the reduced embeddings
2024-03-29 23:30:13,588 - BERTopic - Cluster - Completed ✓
2024-03-29 23:30:13,592 - BERTopic - Representation - Extracting topics from clusters using representation models.
2024-03-29 23:30:17,774 - BERTopic - Representation - Completed ✓
2024-03-29 23:30:20,860 - BERTopic - Embedding - Transforming documents to embeddings.

4

Batches:   0%|          | 0/347 [00:00<?, ?it/s]

2024-03-29 23:30:34,850 - BERTopic - Embedding - Completed ✓
2024-03-29 23:30:34,851 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2024-03-29 23:30:43,852 - BERTopic - Dimensionality - Completed ✓
2024-03-29 23:30:43,854 - BERTopic - Cluster - Start clustering the reduced embeddings
2024-03-29 23:30:52,388 - BERTopic - Cluster - Completed ✓
2024-03-29 23:30:52,393 - BERTopic - Representation - Extracting topics from clusters using representation models.
2024-03-29 23:31:04,648 - BERTopic - Representation - Completed ✓
2024-03-29 23:31:06,976 - BERTopic - Embedding - Transforming documents to embeddings.

Batches:   0%|          | 0/347 [00:00<?, ?it/s]

2024-03-29 23:31:21,002 - BERTopic - Embedding - Completed ✓
2024-03-29 23:31:21,004 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2024-03-29 23:31:29,895 - BERTopic - Dimensionality - Completed ✓
2024-03-29 23:31:29,897 - BERTopic - Cluster - Start clustering the reduced embeddings
2024-03-29 23:32:17,984 - BERTopic - Cluster - Completed ✓
2024-03-29 23:32:17,989 - BERTopic - Representation - Extracting topics from clusters using representation models.
2024-03-29 23:32:22,177 - BERTopic - Representation - Completed ✓
2024-03-29 23:32:24,623 - BERTopic - Embedding - Transforming documents to embeddings.

5

Batches:   0%|          | 0/347 [00:00<?, ?it/s]

2024-03-29 23:32:38,953 - BERTopic - Embedding - Completed ✓
2024-03-29 23:32:38,955 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2024-03-29 23:32:47,678 - BERTopic - Dimensionality - Completed ✓
2024-03-29 23:32:47,680 - BERTopic - Cluster - Start clustering the reduced embeddings
2024-03-29 23:32:57,033 - BERTopic - Cluster - Completed ✓
2024-03-29 23:32:57,038 - BERTopic - Representation - Extracting topics from clusters using representation models.
2024-03-29 23:33:10,158 - BERTopic - Representation - Completed ✓
2024-03-29 23:33:12,425 - BERTopic - Embedding - Transforming documents to embeddings.

Batches:   0%|          | 0/347 [00:00<?, ?it/s]

2024-03-29 23:33:26,818 - BERTopic - Embedding - Completed ✓
2024-03-29 23:33:26,820 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2024-03-29 23:33:36,122 - BERTopic - Dimensionality - Completed ✓
2024-03-29 23:33:36,124 - BERTopic - Cluster - Start clustering the reduced embeddings
2024-03-29 23:34:26,228 - BERTopic - Cluster - Completed ✓
2024-03-29 23:34:26,232 - BERTopic - Representation - Extracting topics from clusters using representation models.
2024-03-29 23:34:30,505 - BERTopic - Representation - Completed ✓
2024-03-29 23:34:32,937 - BERTopic - Embedding - Transforming documents to embeddings.

6

Batches:   0%|          | 0/347 [00:00<?, ?it/s]

2024-03-29 23:34:46,884 - BERTopic - Embedding - Completed ✓
2024-03-29 23:34:46,886 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2024-03-29 23:34:55,563 - BERTopic - Dimensionality - Completed ✓
2024-03-29 23:34:55,564 - BERTopic - Cluster - Start clustering the reduced embeddings
2024-03-29 23:35:03,620 - BERTopic - Cluster - Completed ✓
2024-03-29 23:35:03,625 - BERTopic - Representation - Extracting topics from clusters using representation models.
2024-03-29 23:35:16,063 - BERTopic - Representation - Completed ✓
2024-03-29 23:35:18,341 - BERTopic - Embedding - Transforming documents to embeddings.

Batches:   0%|          | 0/347 [00:00<?, ?it/s]

2024-03-29 23:35:32,568 - BERTopic - Embedding - Completed ✓
2024-03-29 23:35:32,569 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2024-03-29 23:35:41,922 - BERTopic - Dimensionality - Completed ✓
2024-03-29 23:35:41,924 - BERTopic - Cluster - Start clustering the reduced embeddings
2024-03-29 23:36:33,742 - BERTopic - Cluster - Completed ✓
2024-03-29 23:36:33,751 - BERTopic - Representation - Extracting topics from clusters using representation models.
2024-03-29 23:36:38,001 - BERTopic - Representation - Completed ✓
2024-03-29 23:36:40,427 - BERTopic - Embedding - Transforming documents to embeddings.

7

Batches:   0%|          | 0/347 [00:00<?, ?it/s]

2024-03-29 23:36:54,388 - BERTopic - Embedding - Completed ✓
2024-03-29 23:36:54,389 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2024-03-29 23:37:03,011 - BERTopic - Dimensionality - Completed ✓
2024-03-29 23:37:03,013 - BERTopic - Cluster - Start clustering the reduced embeddings
2024-03-29 23:37:11,946 - BERTopic - Cluster - Completed ✓
2024-03-29 23:37:11,951 - BERTopic - Representation - Extracting topics from clusters using representation models.
2024-03-29 23:37:25,027 - BERTopic - Representation - Completed ✓
2024-03-29 23:37:27,292 - BERTopic - Embedding - Transforming documents to embeddings.

Batches:   0%|          | 0/347 [00:00<?, ?it/s]

2024-03-29 23:37:41,274 - BERTopic - Embedding - Completed ✓
2024-03-29 23:37:41,275 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2024-03-29 23:37:49,925 - BERTopic - Dimensionality - Completed ✓
2024-03-29 23:37:49,927 - BERTopic - Cluster - Start clustering the reduced embeddings
2024-03-29 23:38:40,326 - BERTopic - Cluster - Completed ✓
2024-03-29 23:38:40,331 - BERTopic - Representation - Extracting topics from clusters using representation models.
2024-03-29 23:38:44,505 - BERTopic - Representation - Completed ✓
2024-03-29 23:38:46,899 - BERTopic - Embedding - Transforming documents to embeddings.

8

Batches:   0%|          | 0/347 [00:00<?, ?it/s]

2024-03-29 23:39:00,961 - BERTopic - Embedding - Completed ✓
2024-03-29 23:39:00,962 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2024-03-29 23:39:09,570 - BERTopic - Dimensionality - Completed ✓
2024-03-29 23:39:09,572 - BERTopic - Cluster - Start clustering the reduced embeddings
2024-03-29 23:39:18,397 - BERTopic - Cluster - Completed ✓
2024-03-29 23:39:18,402 - BERTopic - Representation - Extracting topics from clusters using representation models.
2024-03-29 23:39:31,212 - BERTopic - Representation - Completed ✓
2024-03-29 23:39:33,449 - BERTopic - Embedding - Transforming documents to embeddings.

Batches:   0%|          | 0/347 [00:00<?, ?it/s]

2024-03-29 23:39:47,452 - BERTopic - Embedding - Completed ✓
2024-03-29 23:39:47,454 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2024-03-29 23:39:56,287 - BERTopic - Dimensionality - Completed ✓
2024-03-29 23:39:56,289 - BERTopic - Cluster - Start clustering the reduced embeddings
2024-03-29 23:40:47,817 - BERTopic - Cluster - Completed ✓
2024-03-29 23:40:47,821 - BERTopic - Representation - Extracting topics from clusters using representation models.
2024-03-29 23:40:52,124 - BERTopic - Representation - Completed ✓
2024-03-29 23:40:54,564 - BERTopic - Embedding - Transforming documents to embeddings.

9

Batches:   0%|          | 0/347 [00:00<?, ?it/s]

2024-03-29 23:41:08,598 - BERTopic - Embedding - Completed ✓
2024-03-29 23:41:08,599 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2024-03-29 23:41:17,900 - BERTopic - Dimensionality - Completed ✓
2024-03-29 23:41:17,902 - BERTopic - Cluster - Start clustering the reduced embeddings
2024-03-29 23:41:26,241 - BERTopic - Cluster - Completed ✓
2024-03-29 23:41:26,246 - BERTopic - Representation - Extracting topics from clusters using representation models.
2024-03-29 23:41:38,827 - BERTopic - Representation - Completed ✓
2024-03-29 23:41:41,120 - BERTopic - Embedding - Transforming documents to embeddings.

Batches:   0%|          | 0/347 [00:00<?, ?it/s]

2024-03-29 23:41:55,180 - BERTopic - Embedding - Completed ✓
2024-03-29 23:41:55,181 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2024-03-29 23:42:03,970 - BERTopic - Dimensionality - Completed ✓
2024-03-29 23:42:03,972 - BERTopic - Cluster - Start clustering the reduced embeddings
2024-03-29 23:42:53,268 - BERTopic - Cluster - Completed ✓
2024-03-29 23:42:53,272 - BERTopic - Representation - Extracting topics from clusters using representation models.
2024-03-29 23:42:57,347 - BERTopic - Representation - Completed ✓
2024-03-29 23:42:59,735 - BERTopic - Embedding - Transforming documents to embeddings.

10

Batches:   0%|          | 0/347 [00:00<?, ?it/s]

2024-03-29 23:43:13,804 - BERTopic - Embedding - Completed ✓
2024-03-29 23:43:13,805 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2024-03-29 23:43:22,463 - BERTopic - Dimensionality - Completed ✓
2024-03-29 23:43:22,464 - BERTopic - Cluster - Start clustering the reduced embeddings
2024-03-29 23:43:30,779 - BERTopic - Cluster - Completed ✓
2024-03-29 23:43:30,784 - BERTopic - Representation - Extracting topics from clusters using representation models.
2024-03-29 23:43:42,890 - BERTopic - Representation - Completed ✓
2024-03-29 23:43:45,155 - BERTopic - Embedding - Transforming documents to embeddings.

Batches:   0%|          | 0/347 [00:00<?, ?it/s]

2024-03-29 23:43:59,704 - BERTopic - Embedding - Completed ✓
2024-03-29 23:43:59,706 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2024-03-29 23:44:08,370 - BERTopic - Dimensionality - Completed ✓
2024-03-29 23:44:08,372 - BERTopic - Cluster - Start clustering the reduced embeddings
2024-03-29 23:44:54,421 - BERTopic - Cluster - Completed ✓
2024-03-29 23:44:54,426 - BERTopic - Representation - Extracting topics from clusters using representation models.
2024-03-29 23:44:58,899 - BERTopic - Representation - Completed ✓
2024-03-29 23:45:01,376 - BERTopic - Embedding - Transforming documents to embeddings.

11

Batches:   0%|          | 0/347 [00:00<?, ?it/s]

2024-03-29 23:45:15,523 - BERTopic - Embedding - Completed ✓
2024-03-29 23:45:15,525 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2024-03-29 23:45:24,549 - BERTopic - Dimensionality - Completed ✓
2024-03-29 23:45:24,551 - BERTopic - Cluster - Start clustering the reduced embeddings
2024-03-29 23:45:34,298 - BERTopic - Cluster - Completed ✓
2024-03-29 23:45:34,305 - BERTopic - Representation - Extracting topics from clusters using representation models.
2024-03-29 23:45:47,617 - BERTopic - Representation - Completed ✓
2024-03-29 23:45:49,878 - BERTopic - Embedding - Transforming documents to embeddings.

Batches:   0%|          | 0/347 [00:00<?, ?it/s]

2024-03-29 23:46:04,205 - BERTopic - Embedding - Completed ✓
2024-03-29 23:46:04,206 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2024-03-29 23:46:12,945 - BERTopic - Dimensionality - Completed ✓
2024-03-29 23:46:12,947 - BERTopic - Cluster - Start clustering the reduced embeddings
2024-03-29 23:47:00,928 - BERTopic - Cluster - Completed ✓
2024-03-29 23:47:00,932 - BERTopic - Representation - Extracting topics from clusters using representation models.
2024-03-29 23:47:05,080 - BERTopic - Representation - Completed ✓
2024-03-29 23:47:08,137 - BERTopic - Embedding - Transforming documents to embeddings.

12

Batches:   0%|          | 0/347 [00:00<?, ?it/s]

2024-03-29 23:47:22,392 - BERTopic - Embedding - Completed ✓
2024-03-29 23:47:22,393 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2024-03-29 23:47:31,040 - BERTopic - Dimensionality - Completed ✓
2024-03-29 23:47:31,041 - BERTopic - Cluster - Start clustering the reduced embeddings
2024-03-29 23:47:40,362 - BERTopic - Cluster - Completed ✓
2024-03-29 23:47:40,366 - BERTopic - Representation - Extracting topics from clusters using representation models.
2024-03-29 23:47:53,805 - BERTopic - Representation - Completed ✓
2024-03-29 23:47:56,070 - BERTopic - Embedding - Transforming documents to embeddings.

Batches:   0%|          | 0/347 [00:00<?, ?it/s]

2024-03-29 23:48:10,273 - BERTopic - Embedding - Completed ✓
2024-03-29 23:48:10,275 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2024-03-29 23:48:18,926 - BERTopic - Dimensionality - Completed ✓
2024-03-29 23:48:18,928 - BERTopic - Cluster - Start clustering the reduced embeddings
2024-03-29 23:49:10,139 - BERTopic - Cluster - Completed ✓
2024-03-29 23:49:10,143 - BERTopic - Representation - Extracting topics from clusters using representation models.
2024-03-29 23:49:14,306 - BERTopic - Representation - Completed ✓
2024-03-29 23:49:16,722 - BERTopic - Embedding - Transforming documents to embeddings.

13

Batches:   0%|          | 0/347 [00:00<?, ?it/s]

2024-03-29 23:49:30,846 - BERTopic - Embedding - Completed ✓
2024-03-29 23:49:30,847 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2024-03-29 23:49:39,482 - BERTopic - Dimensionality - Completed ✓
2024-03-29 23:49:39,484 - BERTopic - Cluster - Start clustering the reduced embeddings
2024-03-29 23:49:48,892 - BERTopic - Cluster - Completed ✓
2024-03-29 23:49:48,897 - BERTopic - Representation - Extracting topics from clusters using representation models.
2024-03-29 23:50:01,922 - BERTopic - Representation - Completed ✓
2024-03-29 23:50:04,245 - BERTopic - Embedding - Transforming documents to embeddings.

Batches:   0%|          | 0/347 [00:00<?, ?it/s]

2024-03-29 23:50:18,417 - BERTopic - Embedding - Completed ✓
2024-03-29 23:50:18,418 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2024-03-29 23:50:27,338 - BERTopic - Dimensionality - Completed ✓
2024-03-29 23:50:27,340 - BERTopic - Cluster - Start clustering the reduced embeddings
2024-03-29 23:51:22,016 - BERTopic - Cluster - Completed ✓
2024-03-29 23:51:22,021 - BERTopic - Representation - Extracting topics from clusters using representation models.
2024-03-29 23:51:26,294 - BERTopic - Representation - Completed ✓
2024-03-29 23:51:28,755 - BERTopic - Embedding - Transforming documents to embeddings.

14

Batches:   0%|          | 0/347 [00:00<?, ?it/s]

2024-03-29 23:51:42,685 - BERTopic - Embedding - Completed ✓
2024-03-29 23:51:42,686 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2024-03-29 23:51:51,340 - BERTopic - Dimensionality - Completed ✓
2024-03-29 23:51:51,342 - BERTopic - Cluster - Start clustering the reduced embeddings
2024-03-29 23:51:59,691 - BERTopic - Cluster - Completed ✓
2024-03-29 23:51:59,696 - BERTopic - Representation - Extracting topics from clusters using representation models.
2024-03-29 23:52:11,744 - BERTopic - Representation - Completed ✓
2024-03-29 23:52:13,950 - BERTopic - Embedding - Transforming documents to embeddings.

Batches:   0%|          | 0/347 [00:00<?, ?it/s]

2024-03-29 23:52:28,934 - BERTopic - Embedding - Completed ✓
2024-03-29 23:52:28,935 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2024-03-29 23:52:37,650 - BERTopic - Dimensionality - Completed ✓
2024-03-29 23:52:37,652 - BERTopic - Cluster - Start clustering the reduced embeddings
2024-03-29 23:53:36,372 - BERTopic - Cluster - Completed ✓
2024-03-29 23:53:36,377 - BERTopic - Representation - Extracting topics from clusters using representation models.
2024-03-29 23:53:40,773 - BERTopic - Representation - Completed ✓
2024-03-29 23:53:43,187 - BERTopic - Embedding - Transforming documents to embeddings.

15

Batches:   0%|          | 0/347 [00:00<?, ?it/s]

2024-03-29 23:53:57,208 - BERTopic - Embedding - Completed ✓
2024-03-29 23:53:57,210 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2024-03-29 23:54:05,850 - BERTopic - Dimensionality - Completed ✓
2024-03-29 23:54:05,852 - BERTopic - Cluster - Start clustering the reduced embeddings
2024-03-29 23:54:14,569 - BERTopic - Cluster - Completed ✓
2024-03-29 23:54:14,580 - BERTopic - Representation - Extracting topics from clusters using representation models.
2024-03-29 23:54:27,633 - BERTopic - Representation - Completed ✓
2024-03-29 23:54:29,981 - BERTopic - Embedding - Transforming documents to embeddings.

Batches:   0%|          | 0/347 [00:00<?, ?it/s]

2024-03-29 23:54:44,034 - BERTopic - Embedding - Completed ✓
2024-03-29 23:54:44,035 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2024-03-29 23:54:52,738 - BERTopic - Dimensionality - Completed ✓
2024-03-29 23:54:52,739 - BERTopic - Cluster - Start clustering the reduced embeddings
2024-03-29 23:55:51,190 - BERTopic - Cluster - Completed ✓
2024-03-29 23:55:51,195 - BERTopic - Representation - Extracting topics from clusters using representation models.
2024-03-29 23:55:55,400 - BERTopic - Representation - Completed ✓
2024-03-29 23:55:57,869 - BERTopic - Embedding - Transforming documents to embeddings.

16

Batches:   0%|          | 0/347 [00:00<?, ?it/s]

2024-03-29 23:56:12,004 - BERTopic - Embedding - Completed ✓
2024-03-29 23:56:12,005 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2024-03-29 23:56:20,766 - BERTopic - Dimensionality - Completed ✓
2024-03-29 23:56:20,768 - BERTopic - Cluster - Start clustering the reduced embeddings
2024-03-29 23:56:30,332 - BERTopic - Cluster - Completed ✓
2024-03-29 23:56:30,337 - BERTopic - Representation - Extracting topics from clusters using representation models.
2024-03-29 23:56:43,191 - BERTopic - Representation - Completed ✓
2024-03-29 23:56:45,423 - BERTopic - Embedding - Transforming documents to embeddings.

Batches:   0%|          | 0/347 [00:00<?, ?it/s]

2024-03-29 23:57:00,231 - BERTopic - Embedding - Completed ✓
2024-03-29 23:57:00,232 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2024-03-29 23:57:08,829 - BERTopic - Dimensionality - Completed ✓
2024-03-29 23:57:08,831 - BERTopic - Cluster - Start clustering the reduced embeddings
2024-03-29 23:58:02,746 - BERTopic - Cluster - Completed ✓
2024-03-29 23:58:02,751 - BERTopic - Representation - Extracting topics from clusters using representation models.
2024-03-29 23:58:07,036 - BERTopic - Representation - Completed ✓
2024-03-29 23:58:09,438 - BERTopic - Embedding - Transforming documents to embeddings.

17

Batches:   0%|          | 0/347 [00:00<?, ?it/s]

2024-03-29 23:58:23,813 - BERTopic - Embedding - Completed ✓
2024-03-29 23:58:23,814 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2024-03-29 23:58:33,192 - BERTopic - Dimensionality - Completed ✓
2024-03-29 23:58:33,194 - BERTopic - Cluster - Start clustering the reduced embeddings
2024-03-29 23:58:42,898 - BERTopic - Cluster - Completed ✓
2024-03-29 23:58:42,908 - BERTopic - Representation - Extracting topics from clusters using representation models.
2024-03-29 23:58:56,536 - BERTopic - Representation - Completed ✓
2024-03-29 23:58:58,811 - BERTopic - Embedding - Transforming documents to embeddings.

Batches:   0%|          | 0/347 [00:00<?, ?it/s]

2024-03-29 23:59:12,951 - BERTopic - Embedding - Completed ✓
2024-03-29 23:59:12,952 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2024-03-29 23:59:21,570 - BERTopic - Dimensionality - Completed ✓
2024-03-29 23:59:21,572 - BERTopic - Cluster - Start clustering the reduced embeddings
2024-03-30 00:00:13,581 - BERTopic - Cluster - Completed ✓
2024-03-30 00:00:13,585 - BERTopic - Representation - Extracting topics from clusters using representation models.
2024-03-30 00:00:17,901 - BERTopic - Representation - Completed ✓
2024-03-30 00:00:20,335 - BERTopic - Embedding - Transforming documents to embeddings.

18

Batches:   0%|          | 0/347 [00:00<?, ?it/s]

2024-03-30 00:00:34,457 - BERTopic - Embedding - Completed ✓
2024-03-30 00:00:34,458 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2024-03-30 00:00:43,128 - BERTopic - Dimensionality - Completed ✓
2024-03-30 00:00:43,130 - BERTopic - Cluster - Start clustering the reduced embeddings
2024-03-30 00:00:52,427 - BERTopic - Cluster - Completed ✓
2024-03-30 00:00:52,432 - BERTopic - Representation - Extracting topics from clusters using representation models.
2024-03-30 00:01:04,649 - BERTopic - Representation - Completed ✓
2024-03-30 00:01:06,899 - BERTopic - Embedding - Transforming documents to embeddings.

Batches:   0%|          | 0/347 [00:00<?, ?it/s]

2024-03-30 00:01:21,002 - BERTopic - Embedding - Completed ✓
2024-03-30 00:01:21,003 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2024-03-30 00:01:29,722 - BERTopic - Dimensionality - Completed ✓
2024-03-30 00:01:29,724 - BERTopic - Cluster - Start clustering the reduced embeddings
2024-03-30 00:02:24,767 - BERTopic - Cluster - Completed ✓
2024-03-30 00:02:24,772 - BERTopic - Representation - Extracting topics from clusters using representation models.
2024-03-30 00:02:29,077 - BERTopic - Representation - Completed ✓
2024-03-30 00:02:31,532 - BERTopic - Embedding - Transforming documents to embeddings.

19

Batches:   0%|          | 0/347 [00:00<?, ?it/s]

2024-03-30 00:02:45,856 - BERTopic - Embedding - Completed ✓
2024-03-30 00:02:45,857 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2024-03-30 00:02:54,461 - BERTopic - Dimensionality - Completed ✓
2024-03-30 00:02:54,463 - BERTopic - Cluster - Start clustering the reduced embeddings
2024-03-30 00:03:02,867 - BERTopic - Cluster - Completed ✓
2024-03-30 00:03:02,872 - BERTopic - Representation - Extracting topics from clusters using representation models.
2024-03-30 00:03:15,262 - BERTopic - Representation - Completed ✓
2024-03-30 00:03:17,469 - BERTopic - Embedding - Transforming documents to embeddings.

Batches:   0%|          | 0/347 [00:00<?, ?it/s]

2024-03-30 00:03:32,319 - BERTopic - Embedding - Completed ✓
2024-03-30 00:03:32,320 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2024-03-30 00:03:41,669 - BERTopic - Dimensionality - Completed ✓
2024-03-30 00:03:41,671 - BERTopic - Cluster - Start clustering the reduced embeddings
2024-03-30 00:04:29,847 - BERTopic - Cluster - Completed ✓
2024-03-30 00:04:29,852 - BERTopic - Representation - Extracting topics from clusters using representation models.
2024-03-30 00:04:34,135 - BERTopic - Representation - Completed ✓

In [225]:
1

1

In [160]:
# Preprocess documents
cleaned_docs = topic_model._preprocess_text(docs)

# Extract vectorizer and tokenizer from BERTopic
vectorizer = topic_model.vectorizer_model
tokenizer = vectorizer.build_tokenizer()

# Extract features for Topic Coherence evaluation
# words = vectorizer.get_feature_names_out()
tokens = [tokenizer(doc) for doc in cleaned_docs]
dictionary = corpora.Dictionary(tokens)
corpus = [dictionary.doc2bow(token) for token in tokens]
topic_words = [[words for words, _ in topic_model.get_topic(topic)] 
               for topic in range(len(set(topics))-1)]

In [161]:
# print(topic_words[0])
# print()
# print(tokens[0])
# print([dictionary.token2id[t] for t in tokens[0]])
# print(corpus[0])

In [162]:
dataset._data.shape, len(tokens)

((11083, 9), 11083)

### Phi

In [163]:
len(set(topic_model.topics_))

21

In [164]:
mtw = topic_model.c_tf_idf_.todense()

In [165]:
mtw.shape

(21, 97541)

In [166]:
ptw = np.array(mtw[1:, :])

ptw.shape

(20, 97541)

In [167]:
pwt = ptw.T

pwt.shape

(97541, 20)

In [175]:
vocabulary = list(topic_model.vectorizer_model.get_feature_names_out())

In [169]:
phi = pd.DataFrame(
    index=vocabulary,
    columns=[f'topic_{i}' for i in range(pwt.shape[1])],
    data=pwt
)

In [170]:
phi.shape

(97541, 20)

In [171]:
phi.head()

,topic_0,topic_1,topic_2,topic_3,topic_4,topic_5,topic_6,topic_7,topic_8,topic_9,topic_10,topic_11,topic_12,topic_13,topic_14,topic_15,topic_16,topic_17,topic_18,topic_19
00,0.000306,0.001210,0.0,0.005406,0.000000,0.00000,0.0,0.0,0.0,0.0,0.0,0.000738,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
000,0.000086,0.000280,0.0,0.004598,0.000152,0.00000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
0000,0.000000,0.000051,0.0,0.003193,0.000000,0.00012,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
00000,0.000000,0.000040,0.0,0.000000,0.000000,0.00000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
000000,0.000080,0.000130,0.0,0.000000,0.000000,0.00000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [172]:
topic_model.get_topic(0)

[('people', 0.015297706905967537),
 ('god', 0.012687628400613112),
 ('think', 0.010985258485161426),
 ('dont', 0.010980406138379617),
 ('just', 0.010369635420305565),
 ('know', 0.009540448616711755),
 ('like', 0.009174781367005965),
 ('say', 0.008689509094080002),
 ('time', 0.00860874843720445),
 ('does', 0.008502158794777346),
 ('government', 0.00812413700368287),
 ('believe', 0.008070026197978602),
 ('jesus', 0.007788213345369761),
 ('law', 0.007614496560170818),
 ('make', 0.007425778785642179),
 ('did', 0.007395395346989908),
 ('right', 0.007374335839871709),
 ('space', 0.007333386229654495),
 ('key', 0.00725698599971484),
 ('way', 0.007247474834753649)]

In [177]:
phi.iloc[vocabulary.index('people'), 0]

0.015297706905967537

In [178]:
phi.iloc[vocabulary.index('god'), 0]

0.012687628400613112

In [179]:
phi.iloc[vocabulary.index('believe'), 0]

0.008070026197978602

In [181]:
for i, t in enumerate(phi.columns):
    tops = topic_model.get_topic(i)

    for p in tops:
        if p[0] not in vocabulary:
            print(f'WTF: {p}')
            continue

        word_index = vocabulary.index(p[0])
        phi_value = phi.iloc[word_index, i]

        assert phi_value == p[1]

WTF: ('', 1e-05)
WTF: ('', 1e-05)
WTF: ('', 1e-05)
WTF: ('', 1e-05)
WTF: ('', 1e-05)
WTF: ('', 1e-05)
WTF: ('', 1e-05)
WTF: ('', 1e-05)
WTF: ('', 1e-05)
WTF: ('', 1e-05)
WTF: ('', 1e-05)
WTF: ('', 1e-05)
WTF: ('', 1e-05)
WTF: ('', 1e-05)

In [98]:
phi.to_csv('test_bt_phi.csv')

In [99]:
topic_top_words = {
    f'topic_{t}': topic_model.get_topic(t)
    for t in range(pwt.shape[1])
}

In [100]:
with open('test_bt_topwords.json', 'w') as f:
    f.write(
        json.dumps(
            topic_top_words, indent=4, ensure_ascii=False
        )
    )

In [ ]:
def get_phi(topic_model):
    mtw = topic_model.c_tf_idf_.todense()
    ptw = np.array(mtw[1:, :])
    pwt = ptw.T
    vocabulary = topic_model.vectorizer_model.get_feature_names_out()

    assert pwt.shape[0] == len(vocabulary)

    topic_names = [f'topic_{i}' for i in range(pwt.shape[1])]
    phi = pd.DataFrame(
        index=vocabulary,
        columns=topic_names,
        data=pwt,
    )

    topic_top_words = {
        n: topic_model.get_topic(t)
        for t, n in enumerate(topic_names)
    }

    return phi, topic_top_words

### Dataset

In [103]:
texts = [
    d + f' {MAIN_MODALITY} ' + ' '.join(t)
    for d, t in zip(dataset._data.index, tokens)
]
new_data = pd.DataFrame(
    columns=['id', 'vw_text'],
    data=[[d, t] for d, t in zip(dataset._data.index, texts)],
)

In [104]:
new_data.head()

,id,vw_text
0,rec_autos_102994,rec_autos_102994 @lemmatized was wondering if ...
1,comp_sys_mac_hardware_51861,comp_sys_mac_hardware_51861 @lemmatized fair n...
2,comp_sys_mac_hardware_51879,comp_sys_mac_hardware_51879 @lemmatized well f...
3,comp_graphics_38242,comp_graphics_38242 @lemmatized Do you have We...
4,sci_space_60880,sci_space_60880 @lemmatized From article C5owC...

In [105]:
new_data.to_csv('test_bt_dataset.csv')

In [106]:
! df -h

Filesystem      Size  Used Avail Use% Mounted on
tmpfs           9,4G  2,8M  9,4G   1% /run
/dev/nvme0n1p1  458G  410G   25G  95% /
tmpfs            47G   12K   47G   1% /dev/shm
tmpfs           5,0M  4,0K  5,0M   1% /run/lock
/dev/sda1       9,1T  5,6T  3,0T  66% /data_mil
tmpfs           9,4G   16K  9,4G   1% /run/user/1127
tmpfs           9,4G   16K  9,4G   1% /run/user/1113

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

In [189]:
len(docs)

11083

In [190]:
cleaned_docs = topic_model._preprocess_text(docs)
vectorizer = topic_model.vectorizer_model
tokenizer = vectorizer.build_tokenizer()
doc_tokens = [tokenizer(doc) for doc in cleaned_docs]

doc_texts = [
    d + f' {MAIN_MODALITY} ' + ' '.join(t)
    for d, t in zip(dataset._data.index, doc_tokens)
]
data = [[d, t] for d, t in zip(dataset._data.index, doc_texts)]
new_dataset = pd.DataFrame(
    columns=['id', 'vw_text'],
    data=data,
)

In [191]:
new_dataset.head()

,id,vw_text
0,rec_autos_102994,rec_autos_102994 @lemmatized was wondering if ...
1,comp_sys_mac_hardware_51861,comp_sys_mac_hardware_51861 @lemmatized fair n...
2,comp_sys_mac_hardware_51879,comp_sys_mac_hardware_51879 @lemmatized well f...
3,comp_graphics_38242,comp_graphics_38242 @lemmatized Do you have We...
4,sci_space_60880,sci_space_60880 @lemmatized From article C5owC...

In [105]:
new_dataset.to_csv('test_bt_dataset.csv')